### ISSUE TITLE
terraform init error

### ISSUE THREAD

**Issue by sugreal** [terraform-providers/terraform-provider-azurerm#10008]
![image](https://user-images.githubusercontent.com/34484229/103194635-352cb880-491b-11eb-9f69-c3929cd47797.png)
An error occurred when I execute "terraform init", the description as above.

**Comment by tombuildsstuff** [comment]
hi @sugreal 

Thanks for opening this issue.

Taking a look through here this appears to be a temporary issue with the Terraform Registry, as such I believe this should now be resolved - if your still experiencing issues here would you mind [reopening this issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone from that team should be able to take a look?

Thanks!
