### ISSUE TITLE
acctests example from README.md doesn't work

### ISSUE THREAD

**Issue by sharebear** [terraform-providers/terraform-provider-azurerm#10018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.14.2 provider branch from master (see #9609)

### Affected Resource(s)

All

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behaviour

A small subset of acceptance tests should run, confirming that environment is configured correctly.

### Actual Behaviour

```
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./azurerm/internal/services/resource/tests/ -run=TestAccAzureRMResourceGroup -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
can't load package: package ./azurerm/internal/services/resource/tests: cannot find package "." in:
        /home/jshare/go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/resource/tests
GNUmakefile:107: recipe for target 'acctests' failed
make: *** [acctests] Error 1
```

### Steps to Reproduce

1. `make tools`
2. `make`
3. Configure environment variables as per documentation
3. `make acctests SERVICE='resource' TESTARGS='-run=TestAccAzureRMResourceGroup' TESTTIMEOUT='60m'` Copy-paste from README.md

### Important Factoids

I'm a complete golang n00b, and not so experienced with make either, maybe I'm missing something obvious.

### References

N/A

**Comment by sharebear** [comment]
Digging into this further, I found the "testacc" goal in the makefile, changing to this goal and changing the TESTARGS to match a test that exists ( `make testacc TESTARGS='-run=TestAccResourceGroup' TESTTIMEOUT='60m'` ) does appear to work although it's a lot of time compiling just for running a single test.

Investgating the codebase a little more I see that only a few resources have a tests package

```
find . -name "tests"
./.teamcity/tests
./azurerm/internal/services/network/tests
./azurerm/internal/services/containers/tests
./azurerm/internal/services/compute/tests
```

Am I correct in assuming that the `acctests` target is legacy and can be removed, and the documentation can be updated to use the `testacc` target? If I've understood the makefile correctly then testacc will also work for the "old" tests.

**Comment by katbyte** [comment]
@sharebear - this issue was created during our move towards individual test packages - as such i don't think its relevant anymore and am going to close it. Please do open another issue if its till an issue
