### ISSUE TITLE
azurerm_security_center_workspace plans to change workspace_id with each plan, even if workspace didn't change

### ISSUE THREAD

**Issue by bertschronja** [terraform-providers/terraform-provider-azurerm#10019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.3
Provider azurerm Version 2.41.0

### Affected Resource(s)
azurerm_security_center_workspace

### Terraform Configuration Files
data "azurerm_subscription" "current" {}

resource "azurerm_log_analytics_workspace" "la2" {
  name                = "ronja-test-3"
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  sku                 = "pergb2018"
}

resource "azurerm_security_center_workspace" "subscription_logging" {
  scope        = data.azurerm_subscription.current.id #"/subscriptions/ad0a4482-e1e3-4b80-98a0-96a3493c06d9"
  workspace_id = azurerm_log_analytics_workspace.la2.id
}

### Debug Output

Terraform will perform the following actions:

  # azurerm_security_center_workspace.subscription_logging will be updated in-place
  ~ resource "azurerm_security_center_workspace" "subscription_logging" {
        id           = "/subscriptions/ad0a4482-e1e3-4b80-98a0-96a3493c06d9/providers/Microsoft.Security/workspaceSettings/default"
      ~ workspace_id = "/subscriptions/ad0a4482-e1e3-4b80-98a0-96a3493c06d9/resourcegroups/rg-terraform-tryout/providers/microsoft.operationalinsights/workspaces/ronja-test-3" -> "/subscriptions/ad0a4482-e1e3-4b80-98a0-96a3493c06d9/resourceGroups/rg-terraform-tryout/providers/Microsoft.OperationalInsights/workspaces/ronja-test-3"
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Panic Output

No panic output

### Expected Behaviour

0 to add, 0 to change, 0 to destroy because resource actually does not change

### Actual Behaviour

Terraform wants to upgrade the resource in-place.

### Steps to Reproduce

1. Create a log analytics workspace.
2. Set this workspace as security center workspace (to log the VM logs in there).
3. Run Terraform plan and apply once.
4. Run Terraform plan again.

### Important Factoids

Azure Germany

### References

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #9931 which shipped in v2.42.0
