### ISSUE TITLE
r/storage_queue: support for `max_dequeue_count`

### ISSUE THREAD

**Issue by springcomp** [terraform-providers/terraform-provider-azurerm#10021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: v0.14.3.

### Description

Messages from an Azure Storage Queue are never transferred to the poison queue after several failures.
The value for the dequeue count property should default to `5` to match the value set by other popular tools, including the Azure Portal.

Please, consider also exposing a `max_dequeue_count` parameter for user-specified configuration.

### Affected Resource(s)

* `azurerm_storage_queue`

### Terraform Configuration Files

```
resource "azurerm_storage_queue" "queue" {
  name                                                    = var.storage_queue_name
  storage_account_name                                    = module.mod-azurerm-storage-account.name
}
```

### Panic Output

N/A

### Expected Behaviour

After some failures, the message from the queue should be transferred to the corresponding `-poison` queue. By default, queues created from the Azure Portal or using the Storage Explorer have a max dequeue count property set to `5`.

### Actual Behaviour

Messages in the Azure Storage Queue are never routed to the corresponding `-poison` queue. It can reach potentially large values for the  `DequeueCount` property. Here is what is shown by a message received by a Logic App from the queue:

![image](https://user-images.githubusercontent.com/8488398/103365612-c38e6f00-4ac0-11eb-9375-0a41f62d7292.png)

### Steps to Reproduce

1. `terraform apply`
2. Create a Logic App that receives a message from the queue and fail with an arbitrary error. For instance, you can use an HTTP request to an unknown or invalid endpoint.

### Important Factoids

N/A

### References

N/A

**Comment by jbinko** [comment]
I'm not seeing support for such attribute in SDK or ARM Templates.

**Comment by springcomp** [comment]
You are absolutely right.

The `MaxDequeueCount` property is indeed not a property of the Queue service, but instead, of the Azure WebJobs SDK. This is therefore available to Web Jobs and Function Apps.

Unfortunately, it seems that we need to do this explicitly in a Logic App.
