### ISSUE TITLE
azurerm_sql_

### ISSUE THREAD

**Issue by BinLiuSeattle** [terraform-providers/terraform-provider-azurerm#10024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
+ provider registry.terraform.io/hashicorp/http v2.0.0

### Affected Resource(s)

* `azurerm_sql_firewall_rule`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-test"
  location = "westus2"
}

data "http" "myip" {
  url = "http://ipv4.icanhazip.com"
}

resource "azurerm_sql_server" "sqlsvr" {
  name                         = "sql-haha-test-1234"
  resource_group_name          = azurerm_resource_group.rg.name
  location                     = azurerm_resource_group.rg.location
  version                      = "12.0"
  administrator_login          = "admin"
  administrator_login_password = "password"
}

resource "azurerm_sql_firewall_rule" "firewall_rule" {
  name                = "home office"
  resource_group_name = azurerm_resource_group.rg.name
  server_name         = azurerm_sql_server.sqlsvr.name
  start_ip_address    = "11.22.33.44" # This is ok
  end_ip_address      = data.http.myip.body # This produces error during `terraform plan`
}
```

### Expected Behaviour

`terraform plan` succeeds without error.

### Actual Behaviour

`terraform plan` produces error complaining about IP invalid, if the IP is not string literal but a data element. This applies to both `start_ip_address` and `end_ip_address`. In the example, I had start_ip_address using a literal IP, but end_id_address using a data element. The latter one produced an error.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

Error: expected end_ip_address to contain a valid IP, got: 71.197.166.49

  on main.tf line 23, in resource "azurerm_sql_firewall_rule" "firewall_rule":
  23: resource "azurerm_sql_firewall_rule" "firewall_rule" {

* #0000

**Comment by allantargino** [comment]
This is because the IP website returns a `\n` appended to your IP. You can verify that by inspecting `.tfstate`:

```json
"resources": [
    {
      "mode": "data",
      "type": "http",
      "name": "myip",
      "provider": "provider[\"registry.terraform.io/hashicorp/http\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "body": "123.123.123.123\n",
            "id": "http://ipv4.icanhazip.com",
            "url": "http://ipv4.icanhazip.com"
          },
```

You can fix it by using [`chomp`](https://www.terraform.io/docs/configuration/functions/chomp.html):

```hcl
resource "azurerm_sql_firewall_rule" "firewall_rule" {
  name                = "home office"
  resource_group_name = azurerm_resource_group.rg.name
  server_name         = azurerm_sql_server.sqlsvr.name
  start_ip_address    = "11.22.33.44"
  end_ip_address      = chomp(data.http.myip.body)
}
```

**Comment by BinLiuSeattle** [comment]
Thank you very much for the reply. I've verified that adding `chomp` works.
