### ISSUE TITLE
Update Provider resources for MySql and PostgreSQL to support new pricing tier

### ISSUE THREAD

**Issue by jeffreyCline** [terraform-providers/terraform-provider-azurerm#1004]
For more information on the change see the [announcement](https://azure.microsoft.com/en-gb/blog/updates-to-azure-database-for-mysql-and-azure-database-for-postgresql/) on the Microsoft Azure Blog.

**Comment by metacpp** [comment]
@jeffreyCline 

The new SDK contains the GA APIs now:
https://github.com/Azure/azure-sdk-for-go/releases/tag/v14.6.0

**Comment by metacpp** [comment]
@jeffreyCline I updated the title of this issue a common one.

**Comment by jeffreyCline** [comment]
Currently waiting on Hotfix version of the v12.5.0-Beta Go SDK, because upgrading to v14.6.0 breaks the Provider code.
