### ISSUE TITLE
Can't create app service plan: AppService and Functions

### ISSUE THREAD

**Issue by potatofarmersally** [terraform-providers/terraform-provider-azurerm#10057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I tried to create an app service plan only to be blocked by the parameter "SKU.Name" being invalid. 

### Terraform (and AzureRM Provider) Version
Terraform: >=0.14
AzureRM: 2.39 and 2.41

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

App Service
```hcl
resource "azurerm_app_service_plan" "asp" {
  name                = "${var.app_service_name}-ASP"
  location            = var.deployment_location
  resource_group_name = var.resource_group_name

  sku {
    tier = lookup(var.app_service_plan_sku, "tier", "Basic")
    size = lookup(var.app_service_plan_sku, "size", "B1")
  }

  tags = var.tags
}

variable "app_service_plan_sku" {
  description = "App service plan details"
  type = object({
    tier = string,
    size = string
  })
}
```
Function app
```hcl
resource "azurerm_app_service_plan" "azure_functions_asp" {
  name                = "${var.functions_app_name}-ASP"
  location            = var.deployment_location
  resource_group_name = var.resource_group_name
  kind                = "FunctionApp"

  sku {
    tier = lookup(var.app_service_plan_sku, "tier")
    size = lookup(var.app_service_plan_sku, "size")
  }

  tags = var.tags
}

variable "app_service_plan_sku" {
  description = "App service plan details"
  type = object({
    tier = string,
    size = string
  })
  default = {
    tier = "Dynamic"
    size = "Y1"
  }
}
```

### Expected Behaviour

An App Service Plan should've been created. 

### Actual Behaviour

Error creating/updating App Service Plan "AppServicePlanName-PPE-ASP" (Resource Group "ResourceGroup-PPE"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter SKU.Name has an invalid value." Details=[{"Message":"The parameter SKU.Name has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"The parameter SKU.Name has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["SKU.Name"]}}][0m

### Steps to Reproduce

1. Create a new release for plan and apply 
2. Deploy release.

### References
https://github.com/terraform-providers/terraform-provider-azurerm/issues/4658 I referenced this but to no avail.

**Comment by derekschauland** [comment]
I am seeing this issue as well, when trying to create an App Service Plan / App service. Though it just surfaced today - terraform version is 14.9 and Azure RM 2.54.0 - started happening on 14.8 as well. There is no mention of any required value for naming SKU and it had worked to build other resources.  

The SKU is configured as Standard | S1 and all of a sudden, it cannot build an app service plan.  Not sure what to try next.

**Comment by derekschauland** [comment]
My previous comment was all the way user error... corrected that and things are rolling again

**Comment by katbyte** [comment]
closing as per above comment!
