### ISSUE TITLE
Case sensitive resource_group_name

### ISSUE THREAD

**Issue by Tbohunek** [terraform-providers/terraform-provider-azurerm#10077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
```

### Affected Resource(s)

* `azurerm_windows_virtual_machine`
* `azurerm_linux_virtual_machine` (possibly)

Surprisingly, the issue does not seem to impact `azurerm_network_interface`

### Terraform Configuration Files

```hcl
resource azurerm_resource_group "rg" {
  name     = var.name
  location = var.location
}

resource "azurerm_windows_virtual_machine" "vm" {
  name                  = var.name
  resource_group_name   = azurerm_resource_group.rg.name
  ...
}
```

### Expected Behaviour

Terraform would ignore the fact that the RG name is uppercase, not replacing the VM.

### Actual Behaviour

Terraform wants to replace the VM, but it does not plan to replace the RG because that is already case-insensitive.
The result is a never-functional configuration

```
  # azurerm_resource_group.rg will be updated in-place
  ~ resource "azurerm_resource_group" "rg" {
        id       = "/subscriptions/xxx/resourceGroups/TESTRG"
        name     = "testrg"
      ~ tags     = {
          + "Owner"          = "me"
        }
        # (1 unchanged attribute hidden)
        # (1 unchanged block hidden)
    }

  # azurerm_windows_virtual_machine.vm must be replaced
  -/+ resource "azurerm_windows_virtual_machine" "vm" {
      ~ id                         = "/subscriptions/xxx/resourceGroups/TESTRG/providers/Microsoft.Compute/virtualMachines/testvm" -> (known after apply)
      ~ resource_group_name        = "TESTRG" -> "testrg" # forces replacement
      ~ tags                       = {
          - "Owner"          = "me"
        }
        ...
    }
```

### Steps to Reproduce

1. Manually create a Resource group with UPPERCASE name (I don't know how that happened but it did)
2. Create a VM in the RG
3. Import the RG and the VM into Terraform
4. `terraform plan`

### References

* #0000

**Comment by stawii** [comment]
It might be related to API misbehaving.. Sometimes, even in UI, I see some of the resource groups all in caps for whatever reason. We have all resource group names' is all lower, but on some particular resources (randomly) it shows up all upper.. Never seen the change like this in Terraform, tho...

**Comment by dgadelha** [comment]
Also impacts `azurerm_virtual_network`:

```
  # azurerm_virtual_network.aks_vnet_westus2 must be replaced
-/+ resource "azurerm_virtual_network" "aks_vnet_westus2" {
      # irrelevant stuff hidden
      ~ id                    = "/subscriptions/.../resourceGroups/MC_name_westus2-asr/providers/Microsoft.Network/virtualNetworks/aks-vnet-test-asr" -> (known after apply)
      ~ resource_group_name   = "MC_name_westus2-asr" -> "mc_name_westus2-asr" # forces replacement
    }
```

**Comment by AgelM** [comment]
Also impacted `azurerm_managed_disk`.
```
# azurerm_virtual_network.aks_vnet_westus2 must be replaced
-/+ resource "azurerm_managed_disk" "disk" {
      # ...
      ~ resource_group_name   = "RESOURCE_GROUP" -> "resource_group" # forces replacement
      #...
    }
```

Terraform Version:
```
Terraform v0.12.28
+ provider.azurerm v2.38.0
```

**Comment by tombuildsstuff** [comment]
Consolidating into #12184
