### ISSUE TITLE
Operation not supported. RepoUrl VSTSRM is not supported.

### ISSUE THREAD

**Issue by pharnishcloudiq** [terraform-providers/terraform-provider-azurerm#10073]
I am getting this error which is a repeat of issue 8171, which has been closed. This is for a release pipeline in TFS. Terraform version is 0.14.3. Azurerm version is 2.41.0. This happens when updating an azurerm_function_app.
This error pops up whenever I run the deployment step the first time for a release. Upon redeploying the stage, the error does not happen.

**Comment by StefanSchoof** [comment]
In #9007 the same problem for app service is reported

**Comment by tombuildsstuff** [comment]
Duplicate of #9007 (App Service and Function App are similar under the hood) - please subscribe to that issue for updates - thanks for the heads up @StefanSchoof
