### ISSUE TITLE
Support for adding dynamic content in file path for Data Factory datasets

### ISSUE THREAD

**Issue by rajshrimohanks** [terraform-providers/terraform-provider-azurerm#10081]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating Datasets in Data Factory V2 via the Azure Portal, there is an option to provide file paths using dynamic expressions.

![2021-01-07 14_58_35-Window](https://user-images.githubusercontent.com/1328247/103883434-36bc6480-5103-11eb-9277-d435375c30aa.png)

However I was not able to replicate the same using the current data set provider. This needs to be supported.

### New or Affected Resource(s)

* azurerm_data_factory_dataset_azure_blob
* azurerm_data_factory_dataset_delimited_text
* azurerm_data_factory_dataset_delimited_text

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_dataset_azure_blob" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  data_factory_name   = azurerm_data_factory.example.name
  linked_service_name = azurerm_data_factory_linked_service_azure_blob_storage.example.name

  path     = "foo"
  filename = "'acc-' + lpad(toString(month(currentDate())),2,'0') + lpad(toString(dayOfMonth(currentDate())),2,'0')  + toString(year(currentDate()))"
  is_dynamic_filename = true  # Could be a potential flag to treat filename as dynamic content
}
```

**Comment by katbyte** [comment]
closing as this appears to have beed fixed by #12034
