### ISSUE TITLE
Support for creating Data Factory Data flows

### ISSUE THREAD

**Issue by rajshrimohanks** [terraform-providers/terraform-provider-azurerm#10080]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, I do not see a way to create a Data Flow in Azure Data Factory v2 using this provider. I believe it would make a good addition.

### New or Affected Resource(s)

* azurerm_data_factory

### Potential Terraform Configuration

```hcl
azurerm_data_factory_data_flow { }
```

**Comment by akorobanov** [comment]
I also need to define Data Flow using this provider. Going to try ARM (executed in TF) as a temporary solution.

**Comment by rajshrimohanks** [comment]
@akorobanov I got it working with ARM for the moment. But the caveat is that, terraform doesn't know about the created resources if using ARM deployments. So every time you run the pipeline, it'll deploy the template again. This is not a problem if you are configuring the template correctly though. Also, be careful to set the `deployment_mode` to `"Incremental"`, else terraform would wipe other resources and deploy only the ARM template in the resource group.

**Comment by akorobanov** [comment]
Got it, thank you!
