### ISSUE TITLE
App Service Plan resource documentation error

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1009]
How do I report an error in documentation?  I am working on deploying an App Service Plan into and App Service Environment and the the documentation on the terraform.io website incorrectly states that if you are attaching an App Service Plan to an App Service Environment you must use the Premium SKU.  It should read that it is required to use the Isolated SKU.

**Comment by tombuildsstuff** [comment]
hi @Phydeauxman 

Thanks for opening this issue :)

> How do I report an error in documentation?

On Github's generally the best place, we can take a look and open a PR as needed :)

> I am working on deploying an App Service Plan into and App Service Environment and the the documentation on the terraform.io website incorrectly states that if you are attaching an App Service Plan to an App Service Environment you must use the Premium SKU. It should read that it is required to use the Isolated SKU.

AFAIK it's possible to do both - depending on the version of the App Service Environment being used (e.g. ASEv1/ASEv2 and if it's dedicated vs shared/a consumption plan). Given this is reliant on an App Service Environment which isn't natively supported by Terraform at this time - I'm going to mark this issue as dependent on #869, when we'll add some examples covering both use-cases.

Thanks!

**Comment by Phydeauxman** [comment]
@tombuildsstuff Thanks, I have not done a v1 ASE but when I did a deployment today in the GUI into my v2 ASE...the only option I had was for an Isolated sku.  Not sure about v1 but you can't do shared/consumption in a v2 ASE.

**Comment by tombuildsstuff** [comment]
hey @Phydeauxman 

I've taken a look into this to update the documentation, during which I've tried to provision an App Service Plan within a v1 and v2 App Service Environment in the Portal but in both cases it appears the App Service Plan requires the `Premium` SKU? I may well be missing/overlooking something, but would you be able to point me to an example where the Isolated SKU is set for the App Service Plan?

Thanks!

**Comment by Phydeauxman** [comment]
In the portal I am in as I am writing this response, if I want to provision an ASP into the v2 ASE I have, the only option I have are the Isolated skus.  If I want to provision an ASP into a new rg, I get all of the plans as options...Premium, Standard, Basic, Free, Shared.  I can send you some screen shots if it will help.

**Comment by tombuildsstuff** [comment]
hey @Phydeauxman 

Got it - I was trying to create a new ASEv2 at the same time as creating an App Service Plan, and was checking the generated template for confirmation; I'll push an update to fix the docs :)

Thanks!
