### ISSUE TITLE
for_each used to deploy azurerm_virtual_network. Dependency error

### ISSUE THREAD

**Issue by 802856294** [terraform-providers/terraform-provider-azurerm#10096]
Define networks in data to be able to pass them in a module later.
      networks = {
        transit-vnet = {
          name                  = var.vnet_name,
          resource_group_key    = "transit",
          location              = var.location,
          bgp_community         = null,
          ddos_protection_plan  = null,
          dns_servers           = null,
          vm_protection_enabled = null,

          address_space = [var.address_space],
          subnets = {
            snet-transit-mgmt = {
              name                                           = var.subnet_name_1,
              address_prefixes                               = [cidrsubnet(var.address_space, 3, 1)],
              enforce_private_link_endpoint_network_policies = null,
              enforce_private_link_service_network_policies  = null,
              service_endpoints                              = null

            },
            snet-transit-untrust = {
              name                                           = var.subnet_name_2,
              address_prefixes                               = [cidrsubnet(var.address_space, 3, 2)],
              enforce_private_link_endpoint_network_policies = null,
              enforce_private_link_service_network_policies  = null,
              service_endpoints                              = null
            },
            snet-transit-trust = {
              name                                           = var.subnet_name_3,
              address_prefixes                               = [cidrsubnet(var.address_space, 3, 3)],
              enforce_private_link_endpoint_network_policies = null,
              enforce_private_link_service_network_policies  = null,
              service_endpoints                              = null
            },
            snet-transit-app-gw = {
              name                                           = var.subnet_name_4,
              address_prefixes                               = [cidrsubnet(var.address_space, 3, 4)],
              enforce_private_link_endpoint_network_policies = null,
              enforce_private_link_service_network_policies  = null,
              service_endpoints                              = null
            }
          }
        }

      }

I then use for_each to recursively deploy networks and subnets:

network module call
module "network_deploy" {

  source = "./../new_network_with_subnets"

  for_each = var.networks == null ? {} : var.networks

  name                  = each.value.name
  location              = each.value.location
  resource_group_ids    = var.resource_group_ids
  address_space         = each.value.address_space
  bgp_community         = each.value.bgp_community
  ddos_protection_plan  = each.value.ddos_protection_plan
  dns_servers           = each.value.dns_servers
  vm_protection_enabled = each.value.vm_protection_enabled
  subnets               = each.value.subnets
  key_value             = each.value.resource_group_key
}

called module create network and then calls module to create subnets
# Create a new network 
resource "azurerm_virtual_network" "module_new_network" {

  name                  = var.name
  location              = var.location
  resource_group_name   = module.get_resource_group_name_deploy.result
  vm_protection_enabled = var.vm_protection_enabled
  bgp_community         = var.bgp_community

  dns_servers = var.dns_servers

  address_space = var.address_space

}

# makes the wait explicit between subnet creation and network creation

module "get_network_name" {

  source = "./../../../../core_functions/Extract_resource_name_from_resource_id"

  resource_id = azurerm_virtual_network.module_new_network.id

}

#deploy subnets

module "subnets_deploy" {

  source = "./../new_network_subnets"

  name                = module.get_network_name.result
  resource_group_name = module.get_resource_group_name_deploy.result
  subnets             = var.subnets

  depends_on = [azurerm_virtual_network.module_new_network]
}

However, I can deploy individual networks. But, when I pass the same data in the created the networks individually to create two or more networks. the modules error. It like each for iteration does not complete before the next one is invoked.

[1m[31mError: [0m[0m[1mError waiting for completion of Virtual Network "transit-vnet" (Resource Group 
"BT-CAF-uksouth-1-bt-transit-vNET-rg"): Code="Canceled" Message="Operation was canceled." 
Details=[{"code":"CanceledAndSupersededDueToAnotherOperation","message":"Operation PutVirtualNetworkOperation 
(e4922188-c08f-48a5-946b-9a8339b29d6b) was canceled and superseded by operation PutVirtualNetworkOperation 
(25cc9c0a-acb7-4f4c-aa67-fb66b26f11db)."}][0m
[0m  on ..\core_modules\resources\networks\networks\new_network_with_subnets\new_network_with_subnets.tf line 26, in resource 
"azurerm_virtual_network" "module_new_network":
  26: resource "azurerm_virtual_network" "module_new_network" [4m{[0m

**Comment by tombuildsstuff** [comment]
hi @802856294 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
