### ISSUE TITLE
Support for id field in azurerm_subscriptions list

### ISSUE THREAD

**Issue by stawii** [terraform-providers/terraform-provider-azurerm#10093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The list of subscriptions returned by data resource `azurerm_subscriptions` does not provide id, however data from `azurerm_subscription` have it.
I'm not reffering UUID-like identification but full resource link (the `/subscriptions/00000000-0000-0000-0000-000000000000` format) which is required for scope in `azurerm_role_assignment`.

### New or Affected Resource(s)

* azurerm_subscriptions

**Comment by Tbohunek** [comment]
@stawii Try `subscription_ids = data.azurerm_subscriptions.dev.subscriptions.*.subscription_id`

**Comment by stawii** [comment]
@Tbohunek This gives UUID-like subscription ID, but not resource URI that is needed for role assignments scope. I know it is easy to create, but it is inconsistent and error prone.

**Comment by Tbohunek** [comment]
Right you are @stawii. While it would be great to get a native functionality, it could be done such as 
```HCL
subscription_ids = [for sub in data.azurerm_subscriptions.dev.subscriptions : "/subscriptions/${sub.subscription_id}"]
```

Given that you already depend on a dynamic structure `data.azurerm_subscriptions`, I don't think this is any more unsafe.

Nonetheless, don't `azurerm_management_group` help you? You can then assign your role on the MG instead, which is better. I just played with that today as I learned about `azurerm_subscriptions` thanks to your post:

```HCL
data "azurerm_subscriptions" "dev" {
  display_name_contains = "_DEV"
}
resource "azurerm_management_group" "dev" {
  parent_management_group_id = azurerm_management_group.core.id
  display_name               = "mg-dev"
  name                       = "mg-dev-xxxxxxxx"

  subscription_ids = data.azurerm_subscriptions.dev.subscriptions.*.subscription_id
}
resource "azurerm_role_assignment" "dev_owners" {
  scope                = azurerm_management_group.dev.id
  role_definition_name = "Owner"
  principal_id         = xxx
}
```
