### ISSUE TITLE
Support for Azure Synapse Workspace Git Configuration

### ISSUE THREAD

**Issue by markhoiland** [terraform-providers/terraform-provider-azurerm#10091]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The GA release of Azure Synapse Analytics workspaces supports Git Configurations similar to Data Factory.  This is a critical feature for most big data architecture platforms.

### New or Affected Resource(s)

* azurerm_synapse_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_synapse_workspace" "example" {
  name                                 = "example"
  resource_group_name                  = azurerm_resource_group.example.name
  location                             = azurerm_resource_group.example.location
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.example.id
  sql_administrator_login              = "sqladminuser"
  sql_administrator_login_password     = "H@Sh1CoR3!"

  aad_admin {
    login     = "AzureAD Admin"
    object_id = "00000000-0000-0000-0000-000000000000"
    tenant_id = "00000000-0000-0000-0000-000000000000"
  }

  **vsts_configuration {
      account_name    = "org_name"
      branch_name     = "master"
      project_name    = "project_name"
      repository_name = "repo_name"
      root_folder     = "/"
      tenant_id       = "00000000-0000-0000-0000-000000000000"
  }

   github_configuration {
      account_name    = "org_name"
      branch_name     = "master"
      repository_name = "repo_name"
      root_folder     = "/"
      git_url      = "https://github.mydomain.com"
  }**

  tags = {
    Env = "production"
  }
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/synapse/workspaces/createorupdate#workspacerepositoryconfiguration
* https://docs.microsoft.com/en-us/azure/synapse-analytics/cicd/source-control#:~:text=Azure%20Synapse%20Studio%20git%20integration%20is%20not%20available,with%20only%20one%20git%20repository%20at%20a%20time.

**Comment by allantargino** [comment]
That's definitely a critical feature. I am working on this @markhoiland and should send a PR soon.

**Comment by allantargino** [comment]
```hcl
  azure_devops_configuration {
      account_name    = "org_name"
      branch_name     = "master"
      project_name    = "project_name"
      repository_name = "repo_name"
      root_folder     = "/"
  }

   github_configuration {
      account_name    = "org_name"
      branch_name     = "master"
      repository_name = "repo_name"
      root_folder     = "/"
      git_url         = "https://github.mydomain.com"
  }
```
I propose to `azure_devops_configuration` instead of `vsts_configuration` (since this is the convention on the portal). Also, on Synapse git integration, `tenant_id` is not necessary (and neither is a valid field, seems they detect it)
