### ISSUE TITLE
azurerm_virtual_hub_route_table does not support next hop ip

### ISSUE THREAD

**Issue by 802856294** [terraform-providers/terraform-provider-azurerm#10101]
azurerm_virtual_hub_route_table route contains:
next_hop which is the resourceId of the peering connection of the hub. In the portal, there is a another parameter "Next Hop IP".. This is allows you to direct traffic to an NFV (filewall) or firewall VIP of a load balancer - firewall sandwich. See Palo deployment guides.

azurerm_virtual_hub_route_table  does not support this parameter. If you specify the resourceId of the NFV or loadbalancer rather the peering connection id then following error occurs:
Code="InternalServerError" Message="An error occurred."

The failed route has to be manually deleted in Azure  as a failed hub route is created
[1m[31mError: [0m[0m[1mA resource with the ID "/subscriptions/8607f216-f9f2-4140-8343-ab8cda82ec14/resourceGroups/vwan/providers/Micros
oft.Network/virtualHubs/vwan_hub_1/hubRouteTables/example-vhubroutetable" already exists - to be managed via Terraform this resource needs 
to be imported into the State. Please see the resource documentation for "azurerm_virtual_hub_route_table" for more information.[0m
[0m  on ..\core_modules\standard_templates\bt-fw-ha-blueprint\bf_fw_ha_blueprint.tf line 398, in resource 
"azurerm_virtual_hub_route_table" "example":
 398: resource "azurerm_virtual_hub_route_table" "example" [4m{[0m
[0m
[0m[0m

If the "azurerm_virtual_hub_route_table" uses the hub connection Id. The route is lefts with Next Hop IP is left with  value "configure"

**Comment by katbyte** [comment]
@802856294 - as @djryanj has pointed out how to configure this i'm going to close the issue - please do let us know if this is still an issue for you
