### ISSUE TITLE
azurerm_subnet do not accept a network_security_group_id as input in Terraform 0.13+

### ISSUE THREAD

**Issue by torkilp** [terraform-providers/terraform-provider-azurerm#10102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
azurerm_subnet

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: Unsupported argument

  on modules\edm_basicnetwork\main.tf line 223, in resource "azurerm_subnet" "subnet":
 223:   network_security_group_id       = data.azurerm_network_security_group.nsg_collection[each.value].id

An argument named "network_security_group_id" is not expected here.

### Expected Behaviour

In the Azure UI I can associate a **network secutity group** when creating a **subnet**. A company policicy can enforce the Subnet to be created with a NSG. In Terraform is devided into a seperate resource **azurerm_subnet_network_security_group_association**. 

# #########################################################################
# NSG TO SUBNET ASSOCIATION
# #########################################################################
resource "**azurerm_subnet_network_security_group_association**" "subnet_nsg_association" {
  for_each                  = toset(var.application_services)

  subnet_id                 = data.azurerm_subnet.subnet_collection[each.value].id
  network_security_group_id = data.azurerm_network_security_group.nsg_collection[each.value].id
  
  depends_on = [ azurerm_subnet.subnet, azurerm_network_security_group.nsg  ]
}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @torkilp 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by petems** [comment]
As an FYI it seems to be related to this: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3054 which was a planned deprecation

**Comment by tombuildsstuff** [comment]
@petems notably there's an issue tracking an updated Azure Policy example to account for this here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/9022
