### ISSUE TITLE
error 400 - EventHub capacity out of range for AutoInflate - azurerm_eventhub_namespace

### ISSUE THREAD

**Issue by mlcooper** [terraform-providers/terraform-provider-azurerm#10117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.3
+ provider registry.terraform.io/carlpett/sops v0.5.3
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.42.0
```

### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_cluster" "daml" {
  name                = local.event_hub_cluster_name
  resource_group_name = data.azurerm_resource_group.resource_groups["EventHubs"].name
  location            = data.azurerm_resource_group.resource_groups["EventHubs"].location
  sku_name            = "Dedicated_1"

  tags = var.common_tags
}

resource "azurerm_eventhub_namespace" "activity_logs" {
  name                 = local.activity_logs_namespace_name
  location             = data.azurerm_resource_group.resource_groups["EventHubs"].location
  resource_group_name  = data.azurerm_resource_group.resource_groups["EventHubs"].name
  sku                  = "Standard"
  dedicated_cluster_id = azurerm_eventhub_cluster.daml.id
  zone_redundant       = true
  auto_inflate_enabled = true
  
  network_rulesets {
    default_action = "Deny"
    ip_rule = [
      for cidr in var.internet_facing_cidrs: {
        ip_mask = cidr
        action = "Allow"
      }
    ]
  }

  tags = var.common_tags
}
```

### Debug Output

Debug output can be found [here](https://gist.github.com/mlcooper/d4f6e89e10b19ebfc180c7facdfcc537).

### Trace Output
Trace output can be found [here](https://gist.github.com/mlcooper/f76263ce466d145ab02744ccb543fb81).

### Expected Behaviour
I would have expected Terraform to create this namespace with `auto_inflate_enabled = true`, because if I go into the Azure Portal after Terraform has created this namespace (if I leave `auto_inflate_enabled = false`), I am able to successfully enable it manually.  If I can do it manually, why does Terraform error?

### Actual Behaviour
Terraform produces this error:
```
Error: eventhub.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="EventHub capacity out of range for AutoInflate. CorrelationId: 279a4a1b-13ac-2308-7af6-c636117e1baa"

  on event-hub-cluster.tf line 15, in resource "azurerm_eventhub_namespace" "activity_logs":
  15: resource "azurerm_eventhub_namespace" "activity_logs" {
```

### Steps to Reproduce

1. Use the code snippet pasted above and do a `terraform apply`

### Important Factoids

Azure Region = `Central US`

### References

* #0000

**Comment by mlcooper** [comment]
I found that [`maximum_throughput_units`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub_namespace#maximum_throughput_units) is a **required** field when `auto_inflate_enabled` is set to `true`.  Perhaps you could update the documentation reflecting this?

**Comment by favoretti** [comment]
Might have something to do with the fact that this namespace is on a dedicated eventhub cluster. Those are "special". That said, setting TU on dedicated clusters for namespaces doesn't really do a whole lot. You pay for dedicated CU's, regardless of how much your namespaces use.

**Comment by mlcooper** [comment]
Yes, turns out it was because I'm using an event hub cluster.  Microsoft recommended that `auto_inflate_enabled` be set to `false` as dedicated event hub clusters do not throttle events so this setting becomes N/A.

My namespace setup is working correctly with the code below, so this issue can be closed if you wish
```
resource "azurerm_eventhub_namespace" "activity_logs" {
  name                 = local.activity_logs_namespace_name
  location             = azurerm_resource_group.resource_groups["EventHubs"].location
  resource_group_name  = azurerm_resource_group.resource_groups["EventHubs"].name
  sku                  = "Standard"
  dedicated_cluster_id = azurerm_eventhub_cluster.daml.id
  # Dedicated Event Hub Clusters do not throttle events so auto_inflate_enabled is not required and should remain false
  auto_inflate_enabled = false
  capacity             = 10

  network_rulesets {
    default_action = "Deny"
    ip_rule = [
      for cidr in var.whitelisted_ips_for_event_hub : {
        ip_mask = cidr
        action  = "Allow"
      }
    ]
  }

  tags = var.common_tags
}
```
