### ISSUE TITLE
Support for default_ttl on azurerm_cosmosdb_gremlin_graph

### ISSUE THREAD

**Issue by jonathaneckman** [terraform-providers/terraform-provider-azurerm#10123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to set the `default_ttl` of a `azurerm_cosmosdb_gremlin_graph`, but the property is not available. I need to set the value to -1. 

### New or Affected Resource(s)

* azurerm_cosmosdb_gremlin_graph

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_gremlin_graph" "example" {
  name                = "tfex-cosmos-gremlin-graph"
  resource_group_name = azurerm_cosmosdb_account.example.resource_group_name
  account_name        = azurerm_cosmosdb_account.example.name
  database_name       = azurerm_cosmosdb_gremlin_database.example.name
  partition_key_path  = "/Example"
  throughput          = 400
  default_ttl         = -1                  <----- NEW

  index_policy {
    automatic      = true
    indexing_mode  = "Consistent"
    included_paths = ["/*"]
    excluded_paths = ["/\"_etag\"/?"]
  }

  conflict_resolution_policy {
    mode                     = "LastWriterWins"
    conflict_resolution_path = "/_ts"
  }

  unique_key {
    paths = ["/definition/id1", "/definition/id2"]
  }
}
```

### References

* [Microsoft.DocumentDB databaseAccounts/gremlinDatabases/graphs 2019-08-01](https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/2019-08-01/databaseaccounts/gremlindatabases/graphs#gremlingraphresource-object)

**Comment by brunhil** [comment]
Seems like this should be an easy add. I'll take a look at adding this over the next few days!
