### ISSUE TITLE
Support for Synapse SQL Pool Transparent Data Encryption

### ISSUE THREAD

**Issue by markhoiland** [terraform-providers/terraform-provider-azurerm#10145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Dedicated SQL Pools in Synapse have a transparent data encryption setting that is required to be enabled by most enterprise security controls.

### New or Affected Resource(s)

* azurerm_synapse_sql_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_synapse_sql_pool" "example" {
  name                        = "examplesqlpool"
  synapse_workspace_id        = azurerm_synapse_workspace.example.id
  sku_name                    = "DW100c"
  create_mode                 = "Default"
  transparent_data_encryption = true
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/synapse/sqlpooltransparentdataencryptions/createorupdate
* https://docs.microsoft.com/en-us/azure/synapse-analytics/security/workspaces-encryption#workspace-encryption-configuration

**Comment by njuCZ** [comment]
@markhoiland thanks for pointing this issue. azurerm_synapse_sql_pool has supported this feature, but the doc missed it. I have submitted a PR to add it back
