### ISSUE TITLE
Support for Synapse Workspace new roles for Role Assignment

### ISSUE THREAD

**Issue by markhoiland** [terraform-providers/terraform-provider-azurerm#10141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New role assignments for Azure Synapse Workspace have been released with GA, replacing the old role definitions.
- Existing role definitions
  - Workspace Admin
  - Sql Admin
  - Apache Spark Admin
- New role definitions
  - **Synapse Administrator**
  - **Synapse SQL Administrator**
  - **Synapse Spark Administrator**
  - **Synapse Contributor (preview)**
  - **Synapse Artifact Publisher (preview)**
  - **Synapse Artifact User (preview)**
  - **Synapse Compute Operator (preview)**
  - **Synapse Credential User (preview)**

### New or Affected Resource(s)

* azurerm_synapse_role_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_synapse_role_assignment" "example" {
  synapse_workspace_id = azurerm_synapse_workspace.example.id
  role_name            = "Synapse Administrator"
  principal_id         = data.azurerm_client_config.current.object_id

  depends_on = [azurerm_synapse_firewall_rule.example]
}
```

### References

* https://docs.microsoft.com/en-us/azure/synapse-analytics/overview-faq
* https://docs.microsoft.com/en-us/azure/synapse-analytics/security/synapse-workspace-synapse-rbac-roles

**Comment by gerardwolf** [comment]
This is a big one, none of the existing roles work since Synapse went GA. The are now all prefixed with Synapse e.g. Synapse Administrator.

**Comment by brnn8r** [comment]
> This is a big one, none of the existing roles work since Synapse went GA. The are now all prefixed with Synapse e.g. Synapse Administrator.

A workaround is to continue to use `Workspace Admin` for role_name. This appears to correctly map to `Synapse Administrator` once your terraform is applied.

**Comment by gerardwolf** [comment]
> > This is a big one, none of the existing roles work since Synapse went GA. The are now all prefixed with Synapse e.g. Synapse Administrator.
> 
> A workaround is to continue to use `Workspace Admin` for role_name. This appears to correctly map to `Synapse Administrator` once your terraform is applied.

Though this likely works for the "Synapse Administrator" role, it doesn't resolve the issue of wanting to set more granular security for other roles, which more and more of our customers are trying to to.

**Comment by Dave-EMIS** [comment]
In case anyone needs it, you can workaround using `az synapse role assignment` CLI: 

https://docs.microsoft.com/en-us/cli/azure/synapse/role/assignment?view=azure-cli-latest#az_synapse_role_assignment_create

**Comment by chrsundermann** [comment]
> In case anyone needs it, you can workaround using `az synapse role assignment` CLI:
> 
> https://docs.microsoft.com/en-us/cli/azure/synapse/role/assignment?view=azure-cli-latest#az_synapse_role_assignment_create

Problem is that you need a intelligent script to update acls. Much prettier is to do it via automation. But it's frustrating that it needs so much time to implement such a small change...
