### ISSUE TITLE
Update for Synapse Workspace naming requirements

### ISSUE THREAD

**Issue by markhoiland** [terraform-providers/terraform-provider-azurerm#10140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The naming convention requirements for the Azure Synapse Workspace name have been updated with the GA release.  
- Current azurerm provider naming requirements for azurerm_synapse_workspace name:  
  - "name can contain only lowercase letters or numbers, and be between 1 and 45 characters long"
- New Azure naming requirements:
  - Workspace name must be between 1 and **50 characters long**.
  - Workspace name must contain only lowercase letters or numbers or **hyphens**.
  - Workspace name must start with a letter or a number.
  - Workspace name must end with a letter or a number.
  - Workspace name must not contain '-ondemand' word.
  - Workspace name must be unique.

### New or Affected Resource(s)

* azurerm_synapse_workspace

### References

*

**Comment by lagebj** [comment]
Is it possible to say anything about when this will be available?

**Comment by gerardwolf** [comment]
Also need this to enable customer CI/CD pipelines for Synapse workloads to align with customer naming conventions.
