### ISSUE TITLE
Error parsing Key Vault Child ID when creating adisk_encryption_set

### ISSUE THREAD

**Issue by jrblanno** [terraform-providers/terraform-provider-azurerm#10158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_disk_encryption_set`

### Terraform Configuration Files
```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "XXXXXXXXXXXXXXXXXXXX"
    storage_account_name = "XXXXXXXXXXXXXXXXXXXX"
    container_name       = "XXXXXXXXXXXXXXXXXXXX"
    key                  = "XXXXXXXXXXXXXXXXXXXX"
  }
  required_providers {
    azurerm = {
      version = "= 2.40"
    }
  }
}
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  
  name = "rg-des-test"
  location = "germanywestcentral"
}

data "azurerm_client_config" "current" {
  
}
resource "azurerm_key_vault" "akv" {
  
  name                        = "akv-des-test"
  resource_group_name         = azurerm_resource_group.rg.name
  location                    = azurerm_resource_group.rg.location
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = "premium"
  enabled_for_disk_encryption = true
  purge_protection_enabled    = false
  network_acls {
    default_action = "Allow"
    bypass = "AzureServices"
  }
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    key_permissions = [
      "decrypt",
      "encrypt",
      "sign",
      "unwrapKey",
      "verify",
      "wrapKey",
      "backup",
      "create",
      "delete",
      "get",
      "import",
      "list",
      "purge",
      "recover",
      "restore",
      "update",
    ]
  secret_permissions = [
    "backup",
    "delete",
    "get",
    "list",
    "purge",
    "recover",
    "restore",
    "set",
    ]
  certificate_permissions = [ 
    "backup",
    "create",
    "delete",
    "deleteissuers",
    "get",
    "getissuers",
    "import",
    "list",
    "listissuers",
    "managecontacts",
    "manageissuers",
    "purge",
    "recover",
    "restore",
    "setissuers",
    "update", 
    ]
  }
}

resource "azurerm_disk_encryption_set" "des" {
  name                = "des-test"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  key_vault_key_id    = azurerm_key_vault.akv.id
  identity {
    type = "SystemAssigned"
  }
}
resource "azurerm_key_vault_access_policy" "current-user" {
  key_vault_id = azurerm_key_vault.akv.id

  tenant_id = data.azurerm_client_config.current.tenant_id
  object_id = data.azurerm_client_config.current.object_id

  key_permissions = [
    "get",
    "create",
    "delete"
  ]
}
resource "azurerm_key_vault_access_policy" "des" {
  key_vault_id = azurerm_key_vault.akv.id
  tenant_id = azurerm_disk_encryption_set.des.identity.0.tenant_id
  object_id = azurerm_disk_encryption_set.des.identity.0.principal_id
  key_permissions = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
    "get",
    "list",
    "update",
  ]
}

output "id" {
  value = azurerm_key_vault.akv.id
}
output "vault_uri" {
  value = azurerm_key_vault.akv.vault_uri
}
```

### Expected Behaviour

Summary: 
azurerm_disk_encryption_set should be created linked to the azurekeyvault. 

A disk encryption set, Azure keyvault , and resource_group should be created. 
Current object_id should have read permissions on the keyvault. 

### Actual Behaviour

Error: Error parsing Key Vault Child ID: Azure KeyVault Child Id should have 3 segments, got 8: 'subscriptions/XXXXXXXXXXXXXXXXXXXX/resourceGroups/rg-des-test/providers/Microsoft.KeyVault/vaults/akv-des-test'

  on main.tf line 92, in resource "azurerm_disk_encryption_set" "des":
  92: resource "azurerm_disk_encryption_set" "des" {

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
1. `terraform apply`

### Important Factoids

- Ofuscated subscription ID and Backend configuration.
- reproduced on provider version 2.40.0 , 2.41.0 , 2.42.0 
### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @jrblanno 

Thanks for opening this issue.

Taking a look at the error being returned above:

> Error: Error parsing Key Vault Child ID: Azure KeyVault Child Id should have 3 segments, got 8: 'subscriptions/XXXXXXXXXXXXXXXXXXXX/resourceGroups/rg-des-test/providers/Microsoft.KeyVault/vaults/akv-des-test'

which is stating that the ID of a Key Vault is being threaded through when a Key Vault Child (e.g. Certificate, Key, Secret) is expected - to look at the Terraform Configuration:

```
resource "azurerm_disk_encryption_set" "des" {
  name                = "des-test"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  key_vault_key_id    = azurerm_key_vault.akv.id
  identity {
    type = "SystemAssigned"
  }
}
```

It appears that the ID of the Azure Key Vault is being passed in, rather than the ID of the Key Vault Key (which doesn't exist in the configuration above) - as such you'd need [to add an `azurerm_key_vault_key` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key) and then thread that through into the Terraform Configuration:

```
resource "azurerm_key_vault_key" "generated" {
  name         = "generated-certificate"
  key_vault_id = azurerm_key_vault.akv.id
  # ...
}


resource "azurerm_disk_encryption_set" "des" {
  name                = "des-test"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  key_vault_key_id    = azurerm_key_vault_key.generated.id
  identity {
    type = "SystemAssigned"
  }
}
```

At which point this should then work - would you be able to take a look and see if that works for you?

Since this is a question regarding Terraform Configuration, I'm going to close this issue for the moment but should you have further questions I'd point you towards the [community discuss forum](https://discuss.hashicorp.com) where you should be able to get further help :)

Thanks!
