### ISSUE TITLE
Unable to read secrets from key vault located in another subscription using aliased provider

### ISSUE THREAD

**Issue by springcomp** [terraform-providers/terraform-provider-azurerm#10152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0
```

### Affected Resource(s)

* `azurerm_key_vault`
* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
#######################################################        GLOBAL    ###############################################################

provider "azurerm" {
    features {}
    tenant_id = var.tenant-id
    subscription_id = var.subscription-id
}

provider "azurerm" {
    alias = "devops"
    features {}
    subscription_id = var.devops_key_vault_subscription_id
}

terraform {
    required_providers {
      azurerm = {
        version = "=2.20.0"
      }
    }
}

data "azurerm_key_vault" "devops_key_vault" {
    name = var.devops_key_vault_name
    resource_group_name = var.devops_key_vault_resource_group_name
    provider = azurerm.devops
}

data "azurerm_key_vault_secret" "kv_devops_apim_oauth_client_secret" {
    name = var.kv_devops_client_secret_secret_name
    key_vault_id = data.azurerm_key_vault.devops_key_vault.id
}
```

### Debug Output

```
Error: Error looking up Secret "kv_devops_client_secret_secret_name" vault url from id
"/subscriptions/subscription-di/resourceGroups/resource-group-name/providers/Microsoft.KeyVault/vaults/vault-name":
failed to find KeyVault "vault-name" (Resource Group "resource-group-name"):
keyvault.VaultsClient#Get: Failure responding to request:
StatusCode=404 -- Original Error: autorest/azure:
Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'resource-group-name' could not be found."
```

### Expected Behaviour

Terraform should lookup the secret from the Key Vault resource located in another subscription.

### Actual Behaviour

An error message, stating that the resource group (containing the specified Key Vault resource) does not exist.

### Steps to Reproduce

1. `terraform plan`

I can confirm that the corresponding resource works and the identity under which `terraform` is run has indeed access to the corresponding key vault, and that the specified secret exists.

```
PS> $id = "/subscriptions/subscription-di/resourceGroups/resource-group-name/providers/Microsoft.KeyVault/vaults/vault-name"
PS> az account set --subscription subscription-id
PS> $id -eq (az keyvault show --resource-group resource-group-name --name vault-name --query "id" --output tsv)
True
PS> az keyvault secret show --vault-name vault-name --name kv_devops_client_secret_secret_name --query "value" --output tsv
value-for-the-kv-devops-client-secret-secret-name
```

### Important Factoids

N/A.

### References

N/A.

**Comment by tombuildsstuff** [comment]
hi @springcomp 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Terraform Configuration rather than a bug with the Azure Provider, where the Data Source `azurerm_key_vault_secret.kv_devops_apim_oauth_client_secret` is missing the `provider` alias present on the `azurerm_key_vault.devops_key_vault` data source, for example:

```hcl
data "azurerm_key_vault" "devops_key_vault" {
    name = var.devops_key_vault_name
    resource_group_name = var.devops_key_vault_resource_group_name
    provider = azurerm.devops
}

data "azurerm_key_vault_secret" "kv_devops_apim_oauth_client_secret" {
    name = var.kv_devops_client_secret_secret_name
    key_vault_id = data.azurerm_key_vault.devops_key_vault.id
}
```

needs to become:

```hcl
data "azurerm_key_vault" "devops_key_vault" {
    name = var.devops_key_vault_name
    resource_group_name = var.devops_key_vault_resource_group_name
    provider = azurerm.devops
}

data "azurerm_key_vault_secret" "kv_devops_apim_oauth_client_secret" {
    name = var.kv_devops_client_secret_secret_name
    key_vault_id = data.azurerm_key_vault.devops_key_vault.id
    provider = azurerm.devops # <-- added
}
```

As such adding this `provider` block in should fix this here. Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider, I'm going to close this issue for the moment - but should you have further questions I'd point you towards [the community discussion forum](https://discuss.hashicorp.com).

Thanks!

**Comment by springcomp** [comment]
That works, thank you very much.
