### ISSUE TITLE
Support for user-assigned managed identities for AKS clusters

### ISSUE THREAD

**Issue by arvan-pritchard** [terraform-providers/terraform-provider-azurerm#10154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently only system-assigned managed identities are supported when creating an AKS Cluster via terraform but the CLI also supports user-assigned identities

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
  identity {
    type = "UserAssigned"
    id = <identity-id>
  }
```

### References

* https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by arestarh** [comment]
@arvan-pritchard Seems like PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/8737 already exists to address this request.

**Comment by arvan-pritchard** [comment]
Thanks, I did search before raising this and failed to find that or issue 7979, sorry.

Happy for this to be closed as a dupe.
