### ISSUE TITLE
Error destroying running Streaming Endpoint

### ISSUE THREAD

**Issue by kmorales90** [terraform-providers/terraform-provider-azurerm#10156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

version: 2.42.0

### Affected Resource(s)

* `azurerm_media_streaming_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_media_streaming_endpoint" "endpoint" {
  name                        = "endpoint"
  resource_group_name         = azurerm_resource_group.resource_group.name
  media_services_account_name = azurerm_media_services_account.media_account.name
  location                    = azurerm_resource_group.resource_group.location
  scale_units                 = 1
  auto_start_enabled          = true
  cdn_enabled                 = false
  tags                        = var.tags
}
```

### Expected Behaviour

Run "Terraform destroy" should destroy Streaming Endpoint. I tested with stopped Streaming Endpoint and works fine, so the problem is only with running Streaming Endpoints.

### Actual Behaviour

Raise an error:
Error: Error deleting Streaming Endpoint "endpoint" in Media Services Account "medianonprod" (Resource Group "rg_media_streaming"): media.StreamingEndpointsClient#Delete: Failure sending request: StatusCode=412 -- Original Error: Code="InvalidOperation" Message="The server cannot execute the operation in its current state."

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by jcanizalez** [comment]
It seems like we need to stop Streaming endpoint before deleted it. Let me try to fix it
