### ISSUE TITLE
Support for Azure Search Service Data Source

### ISSUE THREAD

**Issue by Flink-Jordan** [terraform-providers/terraform-provider-azurerm#10153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently you cannot add a Data Source of type azurerm_search_service. 

### New or Affected Resource(s)

* azurerm_search_service

```hcl
data "azurerm_search_service" "ss_some_search_service" {
  name                = "ss-some-search-service"
  resource_group_name = "rg-myResourceGroup"
}
```

**Comment by brunhil** [comment]
This looks like a fun one to take on. I'll take a stab at it!
