### ISSUE TITLE
azure_mssql_server: Invalid parameter 'storageEndpoint'

### ISSUE THREAD

**Issue by ekowcharles** [terraform-providers/terraform-provider-azurerm#10160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: `0.12.23`
AzureRM Provider version: `2.33.0`
Go runtime version: `go1.12.13`

### Affected Resource(s)

* `azurerm_sql_server`
* `azurerm_mssql_server_extended_auditing_policy`

#### Initial setup which works

Storage account for storing audit logs has firewall enabled. The SQL MSI is granted `Storage Blob Data Contributor` role scoped to the auditing storage account.

```hcl
resource "azurerm_sql_server" "mssql_server" {
  name = "backend"
  resource_group_name = "backend-rg"
  location = "eastus2"
  
  version = "12.0"
  administrative_login = "username"
  administrative_login_password = "supersecure"
  
  identity {
      type = "SystemAssigned"
  }
}

resource "azurerm_mssql_server_extended_auditing_policy" "server_auditing_policy" {
  server_id = azurem_sql_server.mssql_server.id
  
  storage_endpoint = azurerm_storage_account.audit.primary_blob_endpoint
  storage_account_access_key = azurerm_storage_account.audit.primary_access_key
  storage_account_access_key_is_secondary = false
  
  retention_in_days = 30
}
```

#### Final setup which fails on subsequent re-runs

In subsequent setup we completely drop the azurerm_mssql_server_extended_auditing_policy.server_auditing_policy resource.

```hcl
resource "azurerm_sql_server" "mssql_server" {
  name = "backend"
  resource_group_name = "backend-rg"
  location = "eastus2"
  
  version = "12.0"
  administrative_login = "username"
  administrative_login_password = "supersecure"
  
  identity {
      type = "SystemAssigned"
  }
}
```

### Expected Behaviour

Existing extended auditing policy setting should be cleared on SQL server. Terraform should successfully provision SQL server.

### Actual Behaviour

Existing extended auditing policy setting is cleared on SQL server. Terraform fails with the following error:

```sh
Error: Error issuing create/update request for SQL Server "backend" Blob Auditing Policies(Resource Group "backend-rg") sql.ExtendedServerBlobAuditingPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="DataSecurityInvalidUserSuppliedParameter" Message="Invalid parameter 'storageEndpoint'. Value should be a blob storage endpoint (e.g. https://MyAccount.blob.core.windows.net)."

on ../server.main line 40, in resource "azurerm_sql_server" "mssql":
40: resource "azurerm_sql_server" "mssql" {
```

### Steps to Reproduce

1. `terraform apply` on initial configuration
2. `terraform apply` on configuration after the configuration for the `azurerm_mssql_server_extended_auditing_policy` resource is removed.

### Important Factoids

Location: eastus2

Inspecting the state file after the last `terraform apply` reveals the following in the state file:
```json
...
"extended_auditing_policy": [
  {
    "retention_in_days": 0,
    "storage_account_access_key": "",
    "storage_account_access_key_is_secondary": false,
    "storage_endpoint": ""
  }
]
...
```

The expectation is that extended_auditing_policy should have the value of `[]`. 

### References

* #8915 
* https://github.com/Azure/azure-rest-api-specs/issues/11271

**Comment by tombuildsstuff** [comment]
👋 

Based on what we can tell this appears to be an API issue - from our side we've been requesting that the Service Team reply to the upstream issue since mid-November, but frustratingly it's been closed instead.

As such to encourage the Service Team to look into this issue, would you mind commenting [on the upstream issue](https://github.com/Azure/azure-rest-api-specs/issues/11271) where someone from the Service Team should be able to take a look - I'd also encourage you to open a Microsoft Support ticket referencing that Github issue.

Since this appears to be an issue in the Azure API rather than something specific to Terraform I'm going to close this issue for the moment.

Thanks!

**Comment by kaveaa** [comment]
got answer back from microsoft:
<--snip-->
I was able to find the request logs in the backend.
The request body we get is :

{"blobAuditingPolicyName":""default"""parameters":"{
  "Properties": {
    "RetentionDays": 0,
    "IsStorageSecondaryKeyInUse": false,
    "State": "Enabled",
    "StorageEndpoint": "",
    "StorageAccountSubscriptionId": "00000000-0000-0000-0000-000000000000"
  }
}"}

Meaning, that Azure back get a request which have state enabled, however, there is no “StorageEndpoint” nor “isAzureMonitorTargetEnabled”: true provided. Which makes this request invalid ( and so the 400).
<--snip-->`

This is the body that was sent as a result of terraform redeployment after auditing to log analytics had been set.

If the following would be added to the body, the deployment would not fail:
"isAzureMonitorTargetEnabled" : true
