### ISSUE TITLE
Dead link in Azure RM Windows Virtual Machine documentation

### ISSUE THREAD

**Issue by lazarillo** [terraform-providers/terraform-provider-azurerm#10173]
The standard template seemed inappropriate for this small issue.

Upon clicking on the "using the features setting within the Provider block" text at the top of [`azurerm_windows_virtual_machine`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine) documentation, it goes to a dead link.

I *suspect* it is meant to go to this link:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#virtual_machine

**Comment by cgoettel** [comment]
Same issue in the [Azure RM Linux Virtual Machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine) documentation.

**Comment by cgoettel** [comment]
Probably supposed to be this link: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#features

**Comment by cgoettel** [comment]
Interesting. The code is correct (`website/docs/r/` contains four files with the phrase "using the `features` setting within the Provider block" and each of them have the appropriate link). However, the website is linking to "https://www.terraform.io../docs?&_ga=2.54311912.1718379335.1612797792-1085174846.1611941895#argument-reference"

**Comment by lazarillo** [comment]
Well, @cgoettel , if it is supposed to actually point somewhere else, all the more reason to update the docs.  If you are sure it should go to "https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#features", I can fix it and make a PR.

**Comment by tombuildsstuff** [comment]
hey @lazarillo 

Thanks for reporting this - this is a hold-over from when the documentation has been moved from `terraform.io` to the registry, but yes that link is the updated link for the registry 👍 

Thanks!

**Comment by cgoettel** [comment]
Both features links (in Windows and Linux docs) are still dead. They should point to the link I provided above.
