### ISSUE TITLE
Destination Ports doesnt support *(any)  in Azurerm_firewall

### ISSUE THREAD

**Issue by kgopi1** [terraform-providers/terraform-provider-azurerm#10187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_firewall_policy_rule_collection_group`

### Terraform Configuration Files

destination_ports = [ "*" ]

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

![image](https://user-images.githubusercontent.com/37423050/104573985-72988200-564d-11eb-93d3-e5fcf366e58f.png)

### Steps to Reproduce

1. When we pass the destination ports as *(any) , resource is not picking up and giving error as invalid format. 
i'm passing the destination_ports = [*]
2.  In azure portal Firewall_policy allows * for destination ports . 

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
You can specify them as a range = `1-65535`.

**Comment by kgopi1** [comment]
> You can specify them as a range = `1-65535`.

Thanks , from latest version provider 2.42 , it supports this port ranges , earlier it supported only for 64000. 

Also it would nice to include the support for * so it makes sense ..

**Comment by tombuildsstuff** [comment]
@kgopi1 on the backend Azure ends up translating `*` to `1-65535` anyway, so this is the same thing :)

Closing this out since this is achievable using `1-65535` (which is the same as `*`) - but if you have further usage questions I'd direct you to [the community discuss forum](https://discuss.hashicorp.com))

Thanks!
