### ISSUE TITLE
Support for Custom Private DNS Zone for AKS

### ISSUE THREAD

**Issue by EppO** [terraform-providers/terraform-provider-azurerm#10193]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

BYO Private Zone DNS is now supported: https://docs.microsoft.com/en-us/azure/aks/private-clusters#configure-private-dns-zone

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_private_dns_zone" "my_private_dns_zone" {
  name                = "<unique-id-in-east-us>.privatelink.eastus.azmk8s.io"
  resource_group_name = azurerm_resource_group.my_rg.name
}

resource "azurerm_kubernetes_cluster" "aks_private_cluster" {
  name                    = "aks-private-cluster-test"
  location                = "eastus"
  resource_group_name     = azurerm_resource_group.my_rg.name
  dns_prefix              = "..."
  kubernetes_version      = "1.19.0"
  private_cluster_enabled = true
  private_dns_zone_id     = azurerm_private_dns_zone.my_private_dns_zone.id

  lifecycle {
    ignore_changes = [
      # Ignore nodes_count on node pool where autoscaling is on
      default_node_pool[0].node_count,
    ]
  }

  default_node_pool {
    name                = "nodepool1"
    enable_auto_scaling = true
    node_count          = 2
    max_count           = 5
    min_count           = 1
    vm_size             = "Standard_DS2_v2"
    vnet_subnet_id      = azurerm_subnet.my_subnet.id
  }

  identity {
    type = "SystemAssigned"
  }

  linux_profile {
    ...
  }

  addon_profile {
    ...
  }

  network_profile {
    network_plugin     = "azure"
    dns_service_ip     = "192.168.1.10"
    docker_bridge_cidr = "172.17.0.1/16"
    service_cidr       = "192.168.1.0/24"
  }
}
```

**Comment by favoretti** [comment]
```
	// PrivateDNSZone - Private dns zone mode for private cluster.
	PrivateDNSZone *string `json:"privateDNSZone,omitempty"`
```

As vague as it can be... is that a zone ID that's supposed to go in there or something else?

**Comment by favoretti** [comment]
Implementing it now, however we need UserAssigned identities implemented first, since...

```
        Error: creating Managed Kubernetes Cluster "acctestaks210115143211727426" (Resource Group "acctestRG-aks-210115143211727426"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SystemAssignedIdentityNotSupportedForCustomPrivateDNSZone" Message="System assigned identity not supported for custom private dns zone"
```

I'll open a PR and block it on the one with UserAssigned identity implementation.

**Comment by EppO** [comment]
> ```
> 	// PrivateDNSZone - Private dns zone mode for private cluster.
> 	PrivateDNSZone *string `json:"privateDNSZone,omitempty"`
> ```
> 
> As vague as it can be... is that a zone ID that's supposed to go in there or something else?

based on the docs:

```
az aks create -n <private-cluster-name> -g <private-cluster-resource-group> --load-balancer-sku standard --enable-private-cluster --private-dns-zone [none|system|custom private dns zone]
```

> "Custom private dns zone name" should be in this format for azure global cloud: privatelink.<region>.azmk8s.io. The user assigned identity or service principal must be granted at least private dns zone contributor role to the custom private dns zone.

I assume it's not the ID but the name of the zone like `<random-id>.privatelink.eastus.azmk8s.io`

```
Error: creating Managed Kubernetes Cluster "acctestaks210115143211727426" (Resource Group "acctestRG-aks-210115143211727426"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SystemAssignedIdentityNotSupportedForCustomPrivateDNSZone" Message="System assigned identity not supported for custom private dns zone"
```
Strangely enough, docs talked about service principal along with User Assigned Identities
> The user assigned identity or **service principal** must be granted at least private dns zone contributor role to the custom private dns zone.

**Comment by favoretti** [comment]
From my tests - zone must be just privatelink.blah. No prefix is allowed,
API didn’t accept anything in front of it.

I’ll spin up a cluster by hand next week to see what’s possible.

Generally privatelink dns doesn’t allow fully custom domains, just azure
pre-defined ones.

**Comment by EppO** [comment]
I thought the main purpose of BYO private DNS zone was to create the DNS zone first (with a prefix), then give it to AKS to create the A record for the K8S API endpoint in it. I'm not sure what we achieve here just to give the region of the private link. How AKS gets what DNS zone inside `privatelink.<region>.azmk8s.io` we'd like to use if we have multiple zones per region?

**Comment by joeslazaro** [comment]
@favoretti It doesn't look like your PR doesn't add support for the second option listed in the Microsoft documentation for Configure Private DNS Zone:  _"None" means AKS will not create a Private DNS Zone. This requires you to Bring Your Own DNS Server and configure the DNS resolution for the Private FQDN. If you don't configure DNS resolution, DNS is only resolvable within the agent nodes and will cause cluster issues after deployment._

My customer wants to use their on-premise DNS servers with AKS instead of private DNS zones in Azure, so we're hoping to see that feature supported. Any thoughts?

**Comment by favoretti** [comment]
@joeslazaro Hmm, I'll try adding None as a valid option and test it tomorrow.

**Comment by cconkrig** [comment]
We also have the nees for using our own DNS servers. If we can be of help, please let us know. I can test in an enterprise environment. If we need coding on this front I can try to help there as well.

**Comment by EppO** [comment]
for the record docs were updated, it takes the private DNS zone ResourceID:
> "Custom private dns zone name" should be in this format for azure global cloud: privatelink.<region>.azmk8s.io. You will need the **Resource Id of that Private DNS Zone**. Additionally, you will need a user assigned identity or service principal with at least the private dns zone contributor role to the custom private dns zone.

**Comment by favoretti** [comment]
Check the PR, System is just one of the options. I have added an example to the resource docs too.
