### ISSUE TITLE
Terraform with order change issue by using keys (function)

### ISSUE THREAD

**Issue by lbsolar** [terraform-providers/terraform-provider-azurerm#1019]
Hi there,

We found out the order number using key() function is changing and it cause destroy behavior which we couldn't except it.

It seems terraform is working on the bug and issue. Maybe, 1.0.0 release will be fixed these issue.

related with terraform bugs
https://github.com/hashicorp/terraform/issues/14275
https://github.com/hashicorp/terraform/issues/14477

**Comment by tombuildsstuff** [comment]
Closing this since we've not heard back - please feel free to reopen if this is still an issue and we'll take another look.

Thanks!
