### ISSUE TITLE
Support for analytical store in azurerm_cosmosdb_sql_container

### ISSUE THREAD

**Issue by TobiTh** [terraform-providers/terraform-provider-azurerm#10198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Could you please add the possibility to enable the analytical store when creating a new sql container?
In Azure, you can enable it in the "create container" dialog:
![image](https://user-images.githubusercontent.com/1315244/104718829-ce393d00-572b-11eb-898e-2dd282eab69f.png)

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_sql_container" "example" {
  name                  = "example-container"
  resource_group_name   = azurerm_cosmosdb_account.example.resource_group_name
  account_name          = azurerm_cosmosdb_account.example.name
  database_name         = azurerm_cosmosdb_sql_database.example.name
  partition_key_path    = "/definition/id"
  partition_key_version = 1
  throughput            = 400
  enable_analytical_store = true #new

  indexing_policy {
    indexing_mode = "Consistent"

    included_path {
      path = "/*"
    }

    included_path {
      path = "/included/?"
    }

    excluded_path {
      path = "/excluded/?"
    }
  }

  unique_key {
    paths = ["/definition/idlong", "/definition/idshort"]
  }
}
```

### References

The following pull request fixes the enabling of the analytical storage for a cosmosdb account (not a sql container)
#10055

**Comment by favoretti** [comment]
This one has been implemented and merged as part of #10055

**Comment by TobiTh** [comment]
@favoretti Yes, this enables the capability of analytical storage in the cosmosdb account. But we still need to enable the analytical store for each cosmosdb sql container seperately.

**Comment by favoretti** [comment]
Ahh, sorry, lacked coffee...

**Comment by T1loc** [comment]
> This one has been implemented and merged as part of #10055

That's what I meant by the PR I didn't open.
The option shown by @TobiTh can only be define at container creation time. 

There is also this parameter to take into account: 
![Screenshot 2021-01-20 at 10 46 07](https://user-images.githubusercontent.com/7666426/105157124-f4385600-5b0c-11eb-9bc6-91104dd3d014.png)

**Comment by bm77525-kr** [comment]
It looks like the capability for this _should_ be there in the current SDK if I'm reading it right. The [other SDK's](https://docs.microsoft.com/en-us/azure/cosmos-db/configure-synapse-link#net-sdk) seem to enable this on containers by setting the `analyticalStorageTtl` property at creation. From the looks of the [latest azurerm provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.56.0/azurerm/internal/services/cosmos/cosmosdb_sql_container_resource.go#L8), it's using the [2020-04-01 API](https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/2020-04-01/databaseaccounts/sqldatabases/containers?tabs=json) which supports that property. Does this just need to be exposed in the provider?

**Comment by FlipABit** [comment]
@favoretti Sounds like this is potentially supported via the SDK that's currently in use now, yes?

**Comment by favoretti** [comment]
Yep, I'm happy to implement it, just trying to understand how the portal shows off/on (no default)/on as a choice and API has an integer as a value..

**Comment by favoretti** [comment]
Nevemind, tests showed how it works, which is sort of weird, but let me try an implementation.
