### ISSUE TITLE
Terraform don't support resource azurerm_eventhub_authorization_rule on namespace level

### ISSUE THREAD

**Issue by lbsolar** [terraform-providers/terraform-provider-azurerm#1020]
Hi there,

currently, terraform don't support resource azurerm_eventhub_authorization_rule on namespace level. We currently create this using an ARM template, because this resource requires an `eventhub_name` which means we cant create a namespace level rule.

https://www.terraform.io/docs/providers/azurerm/r/eventhub_authorization_rule.html

There is not support for a `namespace` level authorization rule for event hub.

**Comment by tombuildsstuff** [comment]
hi @lbsolar 

Thanks for opening this issue :)

This functionality is also called `Shared Access Policies` within Azure and has previously been requested in #626. Rather than having multiple issues open tracking the same thing - I'm going to close this issue in favour of #626.

Thanks!
