### ISSUE TITLE
azurerm_monitor_diagnostic_setting still forces replacement although no change in id

### ISSUE THREAD

**Issue by gro1m** [terraform-providers/terraform-provider-azurerm#10203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.13.0
AzureRM 2.43.0

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
-/+ resource "azurerm_monitor_diagnostic_setting" "pyt_monitoring_subscription_diagnostics" {
      ~ id                         = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|SubscriptionActivityLogToAnalyticsWS" -> (known after apply)
      ~ log_analytics_workspace_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/monitoring-prod-rg/providers/Microsoft.OperationalInsights/workspaces/monitoring-prod-law" -> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/monitoring-prod-rg/providers/microsoft.OperationalInsights/workspaces/monitoring-prod-law" # forces replacement
<this part does not matter>
}
```

### Expected Behaviour

No replacement of azurerm_monitor_diagnostic_setting (maybe in-change place)

### Actual Behaviour

Replacement of azurerm_monitor_diagnostic_setting

### Steps to Reproduce

1. `terraform plan`

### References

@tombuildsstuff I do not find it anymore, but you closed it as a duplicate for Version 2.43.0, but the error seems to still occur. Otherwise I can provide more info here.

**Comment by tombuildsstuff** [comment]
hi @gro1m 

Thanks for opening this issue.

Taking a look through here it appears the value used for the `log_analytics_workspace_id` field here is using the incorrect casing (`microsoft.OperationalInsights`) vs `Microsoft.OperationalInsights`, which is why this diff is occuring - as such it should be possible to update this and remove this diff. Would you be able to confirm the source of this input, is this user input or a Terraform data source/resource?

Thanks!

**Comment by gro1m** [comment]
@tombuildsstuff You nailed it once again. Although I am quite good at spotting errors, this somehow slipped through. I will try harder in future. I am going to close this and thank you again 👍
