### ISSUE TITLE
Support for Managed HSMs

### ISSUE THREAD

**Issue by bg2132332** [terraform-providers/terraform-provider-azurerm#10209]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add full support for Managed HSMs.  That is creating Managed HSMs themselves, similar to how we can create a key vault. Also, provisioning keys in Managed HSMs.  Activation doesn't have to be done through Terraform, but I'd like to be able to provision the resource itself.  

Also, I opened a separate issue where we cant use Managed HSM keys because of key ID validation errors, so the goal is to generate the HSM, activate it offline, then provision a key and use the key ID for storage encryption at rest and wherever else CMK is supported, for ex. for VM encryption etc.

https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/quick-create-cli

### New or Affected Resource(s)

* azurerm_managed_hsm
* azurerm_managed_hsm_key

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/quick-create-cli

* #0000

**Comment by katbyte** [comment]
closing as this appears to have been fixed by @10873
