### ISSUE TITLE
Azurerm - Create namespace does not not work

### ISSUE THREAD

**Issue by hostettler** [terraform-providers/terraform-provider-azurerm#10215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
+ provider registry.terraform.io/hashicorp/helm v2.0.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 2.40"
    }

    local = {
      source = "hashicorp/local"
      version = "~>1.4"
    }
  }
}

provider "azurerm" {
  features {
   }
}




###############################################
#     Create Azure Resource Group for AKS     #
###############################################
resource "azurerm_resource_group" "aks-rd" {
    name     = "ns-test"
    location = "westeurope"

    tags = {
        Environment = "dev"
    }
}

###############################################
#             Create AKS cluster              #
###############################################
resource "azurerm_kubernetes_cluster" "aks-rd" {

    name                = "aks-ns-bug"
    location            = azurerm_resource_group.aks-rd.location
    resource_group_name = azurerm_resource_group.aks-rd.name
    dns_prefix          = "aks-ns-bug"

    role_based_access_control {
        enabled = true
    }

    default_node_pool {
        name            = "agentpool"
        node_count      = 1
        vm_size         = "Standard_D2_v2"
    }

    identity {
        type = "SystemAssigned"
    }

    addon_profile {
        kube_dashboard {
            enabled = true
        }
    }

    tags = {
        Environment = "dev"
    }

}

resource "local_file" "kube_config" {
  content = azurerm_kubernetes_cluster.aks-rd.kube_config_raw
  filename = "/tmp/cluster.conf"
  depends_on = [ azurerm_kubernetes_cluster.aks-rd]
}




###############################################
#             Load Provider helm              #
###############################################
 provider "helm" {
    kubernetes {
        config_path = "/tmp/cluster.conf"
    }
}


resource "kubernetes_namespace" "new-namespace-bug" {
  metadata {
    annotations = {
      name  = "new-namespace-bug"
    }
    labels = {
      mylabel = "new-namespace-bug"
    }
    name  = "new-namespace-bug"
  }

  depends_on = [ azurerm_kubernetes_cluster.aks-rd]
}
```

### Debug Output
https://gist.github.com/hostettler/1919668efbac3297f6975a6fe6571a57

### Expected Behaviour
A new namespace with name "new-namespace-bug" is created

### Actual Behaviour
The new namespace has not been created:
XXXX@XXXXXX-XX:~/terraform-ns-bug$ kubectl --kubeconfig /tmp/cluster.conf get namespaces
NAME              STATUS   AGE
default           Active   29m
kube-node-lease   Active   29m
kube-public       Active   29m
kube-system       Active   29m

### Steps to Reproduce

1. `az login`
2. `terraform init`
3. `terraform plan`
4. `terraform apply -auto-approve`

### Important Factoids
Running in a Azure

**Comment by tombuildsstuff** [comment]
hi @hostettler 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Kubernetes provider rather than something regarding the Azure Provider, as such [would you mind reopening this on that provider](https://github.com/hashicorp/terraform-provider-kubernetes) so that someone can take a look?

Thanks!

**Comment by hostettler** [comment]
thanks for looking into it. Done, here is the link https://github.com/hashicorp/terraform-provider-kubernetes/issues/1117
