### ISSUE TITLE
Support for setting Java version in azurerm_function_app using Windows consumption plan

### ISSUE THREAD

**Issue by wiebeck** [terraform-providers/terraform-provider-azurerm#10229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I played around a lot trying to provision and deploy an Azure Java 11 function using a Windows consumption plan and stumbled upon an issue (or rather a missing feature?). The function was being provisioned and deployed successfully but it simply wouldn't run (timeout with http 5xx error).

I have prepared a demo repository to show what's going on: https://github.com/wiebeck/azure-terraform-function-demo

I found out that the Function App configuration on Azure was missing the Java version for the runtime stack and I couldn't find a way to set it via Terraform.
![image](https://user-images.githubusercontent.com/61313842/104919369-6dfa0380-5996-11eb-8a4c-b71d88a8cf58.png)
When I changed the value manually via the Azure Portal the function started working as expected.

The only related option I could find was `site_config.linux_fx_version` which required a Linux plan. The branch `WORKING` in the above repository changed the Function App to use a Linux consumption plan where I could set:
```hcl
site_config {
  linux_fx_version = "JAVA|11"
}
```
With this config the Function App could successfully be provisioned, deployed and is working properly, so I assume that the **Azure provider is missing the feature to set the Java runtime stack version in a Windows app service plan**.

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

See https://github.com/wiebeck/azure-terraform-function-demo/blob/master/infrastructure/function-app.tf for a configuration example.

### References

Similar (loosely related) issue using the Azure Gradle plugin which does not detect the Java runtime version properly: https://github.com/microsoft/azure-gradle-plugins/issues/72

**Comment by markphillipsbjss** [comment]
I've ran into this issue also, it also appears that the Linux version doesn't seem to work with the latest provider (2.45.1) It works on 2.35.0.

I've looked as working around this issue, but the Azure CLI also lacks support for this. https://github.com/Azure/azure-cli/issues/12963

**Comment by sschmeck** [comment]
The Azure portal sets a `javaVersion` property for the associated `Microsoft.Web/sites/config` resource.

- Java 8 - `"javaVersion": "1.8"`
- Java 11 = `"javaVersion": "11"`

**Comment by opticyclic** [comment]
URL for the cli doc is https://docs.microsoft.com/en-us/cli/azure/functionapp/config?view=azure-cli-latest#az_functionapp_config_set

**Comment by opticyclic** [comment]
There is a separate problem that causes this to not work.
Despite the function version being set to 3 it gets set to 1
```
  app_settings = {
    FUNCTIONS_EXTENSION_VERSION = "~3"
    FUNCTIONS_WORKER_RUNTIME    = "java"
  }
```

Do `terraform apply` to create it then do `terraform plan` straight after and you will see:

        tags                           = {}
      ~ version                        = "~3" -> "~1"
        # (18 unchanged attributes hidden)

Since this is not set correctly the az cli command won't set the java version until you change this as well.

**Comment by sschmeck** [comment]
@opticyclic You should set `version` instead of `FUNCTION_EXTENSION_VERSION` of the `app_settings` block, see #11577.

**Comment by wiebeck** [comment]
@sschmeck Will check... but I already spread the news in our company. ;-)

**Comment by wiebeck** [comment]
@sschmeck I just confirmed that v2.57.0 (#10495) fixes this issue. By specifying
```
site_config {
  java_version = "11"
}
```
I was able to provision a Java 11 function that worked out of the box and had the right configuration:
![image](https://user-images.githubusercontent.com/61313842/117113428-be04a680-ad8a-11eb-9fe7-c1815a61461f.png)

Thanks a lot to all contributors! 👍🏻
