### ISSUE TITLE
Error: Unsupported attribute when trying to access/output multiple azurerm_windows_virtual_machine attributes

### ISSUE THREAD

**Issue by Smily0** [terraform-providers/terraform-provider-azurerm#10250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am attempting to export a list of vm names and IP addresses from terraform to generate an inventory file for Ansible. My goal is to roughly follow [this example](https://www.linkbynet.com/produce-an-ansible-inventory-with-terraform) .  I am unable to pass a list of names/private IPs from the azurerm_windows_virtual_machine resource to a template file. To simply testing, I've removed the template and am only using the output command.  I am able to see all attributes for all machines created in the for loop under azurerm_windows_virtual_machine and I can access a single attribute of a single VM in the set, but not a single attribute for all VMs in the set.

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

azurerm_windows_virtual_machine

### Terraform Configuration Files

```hcl

# Define data references from existing objects
data "azurerm_resource_group" "rg" {
  name     = "DEV-C01-AdamTesting"
  provider = azurerm.infraProvider
}

data "azurerm_virtual_network" "targetvnet" {
  name                = var.targetVnet
  resource_group_name = var.targetVnetRG
  provider            = azurerm.infraProvider
}

data "azurerm_subnet" "targetSubnetvnet" {
  name                 = var.targetSubnet
  virtual_network_name = data.azurerm_virtual_network.targetvnet.name
  resource_group_name  = data.azurerm_virtual_network.targetvnet.resource_group_name
  provider             = azurerm.infraProvider
}

data "azurerm_shared_image_version" "image" {
  name                = var.image.version
  image_name          = var.image.name
  gallery_name        = var.image.gallery
  resource_group_name = var.image.rg
  provider            = azurerm.imageProvider
}

# Begin creating new resources
# Create the availability set to be used by this group of servers

# Creat a nic for each VM to be created
resource "azurerm_network_interface" "nic" {
  for_each                      = toset(var.all_servers.servers)
  name                          = "D${var.primaryRegion}${var.all_servers.name}${each.value}-nic"
  location                      = var.region
  resource_group_name           = "DEV-C01-AdamTesting"
  provider                      = azurerm.infraProvider


  ip_configuration {
    name                          = "configuration1"
    subnet_id                     = data.azurerm_subnet.targetSubnetvnet.id
    private_ip_address_allocation = "dynamic"
  }
  tags = {
    CostCenter = var.costCenter
    Project    = var.projectTag
  }
}

# Create a random password to be used for the .\AzureUser account across all of the created VM(s). Note the same password will be used for each machine of the same type
resource "random_password" "password" {
  for_each = toset(var.all_servers.servers)
  length   = 18
  special  = true
}

# Begin creating the actual Windows VM(s)
resource "azurerm_windows_virtual_machine" "vm" {
  for_each            = { for idx, vm in toset(var.all_servers.servers) : vm => idx }
  name                = "D${var.primaryRegion}${var.all_servers.name}${each.key}"
  resource_group_name = "DEV-C01-AdamTesting"
  location            = var.region
  provider            = azurerm.infraProvider
  size                = var.all_servers.size
  admin_username      = "AzureUser"
  admin_password      = random_password.password[each.key].result
  timezone            = "Central Standard Time"
  network_interface_ids = [
    azurerm_network_interface.nic[each.value].id,
  ]
  tags = {
    CostCenter = var.costCenter
    Project    = var.projectTag
  }
  identity {
    type = "SystemAssigned"
  }
  os_disk {
    name                 = "D${var.primaryRegion}${var.all_servers.name}${each.value}-osdisk"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = var.all_servers.osDiskSize
  }
  source_image_id = data.azurerm_shared_image_version.image.id
  depends_on = [
    azurerm_network_interface.nic
  ]
}

output "vminfo" {
  value = azurerm_windows_virtual_machine.vm[*].name

}
```

### Expected Behaviour

Output should display a list of names (or other attributes) for each/all VM(s) created under this resource

### Actual Behaviour

Error: Unsupported attribute

  on main.tf line 123, in output "vminfo":
 123:   value = azurerm_windows_virtual_machine.vm[*].name

This object does not have an attribute named "name".

### Steps to Reproduce

1. `terraform plan -var-file local-demo.tfvars`
or
2. `terraform apply -var-file local-demo.tfvars`

### Important Factoids

Running the output command on the entire resource set created works, as does returning a single attribute value for a single VM referenced in the set, the only issue is trying to return a single attribute for all VMs created in a set.

Running output without the "name" attribute returns all attribute/value pairs for each VM created, showing "name" exists with a value as I try to receive.
output "vminfo" {
  value = azurerm_windows_virtual_machine.vm[*]
}
`This displays all attribute pairs for all VMs`

Running output with a specific VM instance return the single attribute/value that specific  VM created, showing "the overall syntax works when I try to access a single machine.
output "vminfo" {
  value = azurerm_windows_virtual_machine.vm["05"].name
}
`This outputs the name of the one machine just fine`

**Comment by tombuildsstuff** [comment]
hi @Smily0 

Thanks for opening this issue - apologies for the delayed response here.

Taking a look through here this appears to be a question regarding Terraform Configuration rather than a bug in the Azure Provider -(which is what this forum is intended for) - as such I'd point you towards [the Community Discuss forum](https://discuss.hashicorp.com) where someone should be able to assist with the syntax here.

Thanks!
