### ISSUE TITLE
azurerm_api_management_custom_domain: resource gets updated every time

### ISSUE THREAD

**Issue by AmudaPalani** [terraform-providers/terraform-provider-azurerm#10253]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_api_management_custom_domain`

### Terraform Configuration Files

![image](https://user-images.githubusercontent.com/53053396/105090619-41142200-5a64-11eb-83a3-cc13aa11ccd3.png)

### Expected Behaviour

Since this resource already exists and no changes were requested, this should not be updated.

### Actual Behaviour

resource gets updated every time.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by larsmaes** [comment]
same issue here. This also reulst in downtime because the service gets restarted when this change gets applied

**Comment by larsmaes** [comment]
This also results in the removal of the custom domain in the first run; and when i run it again it get added again and so on..

**Comment by hgutvik** [comment]
I would also like to add a couple of things. 

First, it's not very clear whether or not one should include the default proxy in the custom domains definition.
[The example usage shown in Terraform azurerm_api_management_custom_domain docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_custom_domain#example-usage) only lists the custom domains.
[The automated tests for azurerm_api_management_custom_domain ](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/apimanagement/api_management_custom_domain_resource_test.go) list the default proxy along with the custom domains.
Perhaps clarify this in the docs, and align with tests?

Second, I'll add some additional info from our attempts, might help for debugging.
We tried both the approaches mentioned above, resulting in slightly different behavior:

### (a) Defining only our custom domains
This approach performs the same updates on every _apply_ after initial creation.

**Definition - azurerm_api_management_custom_domain**
- proxy (custom)
- developer_portal
- management

The initial create-deployment runs successfully and correctly.

**Running terraform plan/apply (same code - no changes):**
- Update azurerm_api_management - delete hostname_configuration (containing only the three custom domains): 
![image](https://user-images.githubusercontent.com/72432100/105479608-f2a19600-5ca4-11eb-9854-0c38f28c50bf.png)
- Update azurerm_api_management_custom_domain - replace default proxy with custom proxy
![image](https://user-images.githubusercontent.com/72432100/105483657-77db7980-5caa-11eb-9fe2-060c88704b22.png)

### (b) Defining default proxy along with our custom domains
This approach performs almost the same update as above, except split in two steps, in consequent pairs of _apply_.
The slight difference is that the custom domains, when added back in, are not conflicting with the default proxy in Terraform, but added in addition to it. 


**Definition - azurerm_api_management_custom_domain**
- proxy (custom)
- proxy (default)
- developer_portal
- management

Like above, the initial create-deployment runs successfully and correctly.

**1st Running terraform plan/apply (same code - no changes):**
- Update azurerm_api_management - delete hostname_configuration (containing only the three custom domains): 
![image](https://user-images.githubusercontent.com/72432100/105484670-fd135e00-5cab-11eb-9d04-7e39e6ab3a63.png)

Result of _apply_: all custom domains deleted. The default proxy remains, and gets default_ssl_binding auto-toggled to _true_.

**2nd Running terraform plan/apply (same code - no changes):**
- Update azurerm_api_management_custom_domain - add custom domains _alongside_ the default proxy, and toggle default_ssl_binding of default proxy correctly back to _false_
![image](https://user-images.githubusercontent.com/72432100/105483309-f4ba2380-5ca9-11eb-8678-dbb5bcffa47e.png)

Result of _apply:_ custom domains added back in, alongside the default proxy, which gets default_ssl_binding toggled correctly back to _false_

**3rd Running terraform plan/apply (same code - no changes) [same as 1st]:**
- Update azurerm_api_management - delete hostname_configuration (containing only the three custom domains): 
![image](https://user-images.githubusercontent.com/72432100/105484670-fd135e00-5cab-11eb-9d04-7e39e6ab3a63.png)

And so it goes, 4th terraform plan / apply is identical to 1st one.

**Comment by maximivanov** [comment]
Getting same problem here. 

A related Github issue where the need for the `azurerm_api_management_custom_domain` resource was originally raised: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3058

For those who can't wait till this bug is fixed:

There's also a workaround in the comments there with a custom domain configured via a call to an external script: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3058#issuecomment-542631798

And a blog post by the same guy: https://www.jeanpaulsmit.com/2020/03/terraform-deploy-apim/#custom-domains

**Comment by kensykora** [comment]
The latest version of azurerm fixed this issue, thank you @patst!

**Comment by katbyte** [comment]
closing as it sounds like its fixed!
