### ISSUE TITLE
The azurerm_app_service ressource should apply the app_settings before the source_control section

### ISSUE THREAD

**Issue by kinwolfqc** [terraform-providers/terraform-provider-azurerm#10286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_2.44`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "app_service" {
  name                    = "app-${local.namespace}"
  location                = azurerm_resource_group.default.location
  resource_group_name     = azurerm_resource_group.default.name
  app_service_plan_id     = azurerm_app_service_plan.service_plan.id
  client_affinity_enabled = false

  site_config {
    java_version           = "11"
    java_container         = "TOMCAT"
    java_container_version = "9.0"
    always_on              = true
  }
  app_settings = {
    "sonar.jdbc.password" = azurerm_mssql_server.sql_server.administrator_login_password
    "sonar.jdbc.url"      = "jdbc:sqlserver://${azurerm_mssql_server.sql_server.name}.database.windows.net:1433;database=${azurerm_mssql_database.sql_database.name};encrypt=true"
    "sonar.jdbc.username" = azurerm_mssql_server.sql_server.administrator_login
    "SonarQubeEdition"    = var.sonarQubeEdition
    "SonarQubeVersion"    = var.sonarQubeVersion

  }

  source_control {
    repo_url           = "https://<edited>"
    branch             = "edition"
    manual_integration = true
  }



}
```

### Expected Behaviour

When terraform deploy the service app, the app_settings should be written before it configure the Deployment settings(the source control block) since the deployment starts as soon as the soruce control is set.   The reason is that often, the deployment code requires ENV variables that are written by the app_settings section.  So, if the code is deployed before, the ENV variables aren't there yet and the end result is a failure.

### What actually happens
the app_settings are configured/added only **after** the deployment is finished

### References

* #0000

**Comment by jhajduk-microsoft** [comment]
Hello, 

We have the same issue when deploying Teams Apps with Terraform. We need the App Settings to be applied prior to source control evaluation, otherwise the deployment fails.
