### ISSUE TITLE
Azure Cloud Shell Bash: Azure CLI authentication broken in azurerm v2.44.0

### ISSUE THREAD

**Issue by doherty100** [terraform-providers/terraform-provider-azurerm#10292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4 (current release in Azure Cloud Shell)
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0

### Affected Resource(s)

* `provider "azurerm"`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}
```

### Debug Output

Unable to enable trace debug output in Azure Cloud Shell.

### Panic Output

N/A

### Expected Behaviour

Terraform plan should use Azure CLI authentication and complete with no errors.

### Actual Behaviour

Terraform plan results in the following error:

Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/f6d69ee2-34d5-4ca8-a143-7a2fc1aeca55/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"bad_request_102","message":"Required metadata header not specified"}} Endpoint http://localhost:50342/oauth2/token?api-version=2017-09-01&resource=https%3A%2F%2Fmanagement.azure.com%2F

  on 10-common.tf line 1, in provider "azurerm":
   1: provider "azurerm" {

### Steps to Reproduce

1. Navigate to portal.azure.com and sign in
2. Open a new Bash Cloud Shell
3. Move to a directory that has any valid Terraform configuration using azurerm provider v2.44.0
4. `terraform init`
5. `terraform plan`
6. Observe error
7. Switch to azurerm provider v2.42.0
8. `terraform init`
9. `terraform plan`
10. Command completes and plan output is shown

### Important Factoids

This is only happening in Azure Cloud Shell bash. The same configuration works fine in Ubuntu client. This is a new problem I noticed when switching from azurerm v2.42 to azurerm v2.44.

### References

* [aka.ms/cloudshell](https://aka.ms/cloudshell)

**Comment by tombuildsstuff** [comment]
hey @doherty100 

Thanks for opening this issue.

Taking a look through here this appears to be a regression in `Azure/go-autorest` - I've opened [this issue](https://github.com/Azure/go-autorest/issues/612) upstream to track this bug - and once it's fixed we can take a look into upgrading. For the moment it should be possible to use the previous version in CloudShell via pinning:

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.43.0"
    }
  }
}
```

Thanks!

**Comment by doherty100** [comment]
@tombuildsstuff FYI this is still broken in azurerm v2.45.1

**Comment by tombuildsstuff** [comment]
@doherty100 as this breakage is in the Azure SDK's base library, unfortunately this needs to be fixed there: https://github.com/Azure/go-autorest/issues/612

**Comment by jasonrakers** [comment]
This still appears broken in 2.46.1 despite https://github.com/Azure/go-autorest/issues/612 being resolved.

**Comment by Scarlettliuyc** [comment]
Hi team, could you please tell what's the progress of this issue, we are facing same error.
Thank you

**Comment by wtkwsk** [comment]
Still the same issure with **terraform-provider-azurerm_2.47.0**

**Comment by doherty100** [comment]
@tombuildsstuff this is still broken in azurerm v2.48.0.
