### ISSUE TITLE
azurerm_user_assigned_identity resource creation results in an output of resource ID with resource group name in lower case

### ISSUE THREAD

**Issue by sean-t-shen** [terraform-providers/terraform-provider-azurerm#10296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5, provider registry.terraform.io/hashicorp/azurerm v2.32.0

### Affected Resource(s)

* `azurerm_user_assigned_identity`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

The resource id created has the text like this: 
/subscriptions/xyz/resourceGroups/rgname/providers/Microsoft.ManagedIdentity/userAssignedIdentities/resourceId
### Actual Behaviour
/subscriptions/xyz/resourcegroups/rgname/providers/Microsoft.ManagedIdentity/userAssignedIdentities/resourceId

The difference is the spelling of the word "resourcegroups" where the case of the letter "G" is actual lower case.
The resource still got created without problem. But in subsequent plan runs, sometimes, TF will regard "resourcegroups" to be different from "resourceGroups" where the letter G is upper case, thus resulting this resource to be modified/recreated when there is no need to do so.  I think all we need to do is to change the behavior of TF to generate the output of the resource ID to have the upper case letter G in the word "resourceGroups", then I am happy.

### Steps to Reproduce

create such a resource and associate the user assigned identity to an Azure VM resource. In the terraform plan output, when it comes to this identity, you will see the resource ID to be as I described.  I am not sure what situation this will cause TF to try to make the forced modification to a VM's user-defined identity.  In one of my simple situations, it does not.  But in real production where my TF code is more complex, it does regard "resourcegroups" and "resourceGroups" to be different, thus causing the VM to be modified because of this difference.

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @sean-t-shen 

This is fixed in newer versions of the Azure Provider - at the time of writing the latest version is `2.44.0` - you can upgrade to this by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.44.0"
    }
  }
}
```

Since this should be fixed by updating to the latest version of the Azure Provider - I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
