### ISSUE TITLE
No valid (unexpired) Azure CLI Auth Tokens found. when setting tenant_id

### ISSUE THREAD

**Issue by tobiaswi** [terraform-providers/terraform-provider-azurerm#1029]
Hi there,

i found a bug when using azure cli for authentication. 
My setup:

### Terraform Version
Terraform v0.11.5
+ provider.azurerm v1.3.0
+ provider.random v1.1.0

### Terraform Configuration Files
```hcl
###################################
# Connectinon to Azure
###################################

provider "azurerm" {
  tenant_id       = "[my-tenant-uuid]"
  subscription_id = "[my-subscription-id]"
  version         = "1.3"
}

provider "random" {
  version = "~> 1.1"
}
```

### Debug Output
relevant line:
2018-03-26T12:11:09.598+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.3.0_x4: 2018/03/26 12:11:09 [DEBUG] Resource "https://management.core.windows.net/" isn't for the correct Tenant

### Expected Behavior
after authentication with azure cli my terraform plan runs successfully while my accessToken is valid.

### Actual Behavior
terraform plan does not run and throws:
* provider.azurerm: No valid (unexpired) Azure CLI Auth Tokens found. Please run `az login`.

### Steps to Reproduce
1. `az login -t tenantdomain.onmicrosoft.com`
2. `terraform init -upgrade=true`
2. `terraform plan`

### References
- release v1.0.0
- commit fe1e0f53c7e6bf84627092cf31b1fb2aacba652b
- commit d42caca05988d6fe96e4d2c3ca8925699a51d2aa

# Root cause:
When defining tenant_id in my provider as a tenant UUID
```hcl
provider "azurerm" {
  tenant_id       = "[my-tenant-uuid]"
  subscription_id = "[my-subscription-id]"
  version         = "1.3"
}
```
but logging into azure cli with the tenants domain name
```bash
az login -t tenantdomain.onmicrosoft.com
```
my accessToken looks like this:
```json
[
    {
        "expiresIn": 3599,
        "_authority": "https://login.microsoftonline.com/[tenantdomain.onmicrosoft.com]",
        "refreshToken": "[removed]",
        "accessToken": "[removed]",
        "expiresOn": "[removed]",
        "userId": "[removed]",
        "isMRRT": true,
        "_clientId": "[removed]",
        "tokenType": "Bearer",
        "resource": "https://management.core.windows.net/",
        "identityProvider": "[removed]"
    }
]
```
this causes:

azurerm/helpers/authentication/config.go
Line: 60 -> Does not load config from cliProfile if TenantID is set in terraform config
Line: 81 -> findValidAccessTokenForTenant passes the accessToken from disk aswell as the terraform config defined c.TenantID

azurerm/helpers/authentication/access_token.go
Line: 41 -> string compares the suffixes which evaluate to false (domain.onmicrosoft.com != xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

I tried to come up with a fix but im not sure about the use cases that require to load the c.SubscriptionID and c.TenantID from the terraform file when running LoadTokensFromAzureCLI(). This bug could be avoided if we ignore the terraform provider config values as the local azureProfile.json holds the same "tenantId" as the accessTokens.json "_authority" suffix value no matter how you choose to login with the cli (-t uuid / -t dns)

The solution to avoid this bug is removing the defined tenant_id and subscription_id from the terraform provider config.
Maybe an entry in the documentation could show that this is a valid provider config for cli authentication?
```json
provider "azurerm" {
  version = "1.3"
}
```

**Comment by tombuildsstuff** [comment]
hi @tobiaswi 

Thanks for opening this issue - apologies for the delayed response here!

We've split the authentication helpers out into their own library so that we can iterate on it and then reuse it across multiple Providers - as such I'm going to migrate this issue over to the new repository: https://github.com/hashicorp/go-azure-helpers/issues/2

Thanks!
