### ISSUE TITLE
r/linux|windows_virtual_machine: should parse userAssignedIdentities insensitively to work around broken api

### ISSUE THREAD

**Issue by zumic96** [terraform-providers/terraform-provider-azurerm#10300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After user managed identity was assigned to one of Azure VMs I noticed it breaking terraform and I couldn't run any action on it.
Error that I am getting is:
`Error: ID was missing the `userAssignedIdentities` element`

At first I thought that's because I didn't use `identity` block in my module. So I went to change that but error remained the same.
I tired to delete the instance from state and import it but without luck.
When deploying new VM with updated module everything was working as expected, I could add new identity, remove it altogether.
Then I checked output on [resources.azure.com](resources.azure.com) and noticed this difference in Identity block of VM instance.
Identity assigned via portal:
```json
"identity": {
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "/subscriptions/<subscriptionID>/resourceGroups/<rg_of_managed_identitiy>/providers/microsoft.managedidentity/userassignedidentities/ib-azure-metrics-exporter": {
        "principalId": "<principalID>",
        "clientId": "<clientID>"
      }
    }
  }
```
Identity assigned via terraform/API:
```json
"identity": {
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "/subscriptions/<subscriptionID>/resourceGroups/<rg_of_managed_identitiy>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ib-azure-metrics-exporter": {
        "principalId": "<principalID>",
        "clientId": "<clientID>"
      }
    }
  }
```
As you can see difference is in case of userAssignedIdentities and provider is doing check based on that string. Seems like another awful inconsistency from MS side but this will probably be fixed sooner.

### New or Affected Resource(s)

azurerm_linux_virtual_machine
azurerm_windows_virtual_machine

**Comment by lengland** [comment]
I'm also facing this on a DataSource of `azurerm_virtual_machine_scale_set`. 
After upgrading to the 2.44.0 provider, I am unable to run my Terraform  configuration, with it bailing on the same `missing the userAssignedIdentities element` error. 

Checking through [Azure Resources](https://resources.azure.com) There is a mismatch in the casing between Terraform assigned and Azure assigned identities. 

Azure assigned: 
`/subscriptions/<subscription_id>/resourcegroups/<resource_group_name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/omsagent`

Terraform assigned:
`/subscriptions/<subscription_id>/resourcegroups/<resource_group_name>/providers/microsoft.managedidentity/userassignedidentities/<identity_name>`

**Comment by pkaminskiPGS** [comment]
I suppose that also affects AKS somehow. While trying to update an existing cluster, I get following error:

> Invalid value for the identities <resource_id>. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property.

**Comment by lengland** [comment]
@pkaminskiPGS what compute are you using to run your AKS

My errors were from updating AKS, but the error was thrown by the underlying VMSS

**Comment by terrycain** [comment]
This is still a problem in v2.45.1, getting `Error: ID was missing the `userAssignedIdentities` element` for azurerm_linux_virtual_machine that have managed identities assigned to them.

**Comment by terrycain** [comment]
Still an issue on v2.47.0

**Comment by cpressland** [comment]
I'm still having issues with this one on 2.48.0, blocking our rollout of M1 Macs across the DevOps Team. I know the 2.48.0 changelog doesn't mention fixing this, but, the 2.43/2.44 changelogs don't explicitly mention breaking this either.
