### ISSUE TITLE
VMScaleSet Documentation is wrong for accelerated_networking

### ISSUE THREAD

**Issue by djsly** [terraform-providers/terraform-provider-azurerm#1030]
Code: https://github.com/terraform-providers/terraform-provider-azurerm/blob/218dc6e71f880c5d6a8b17862b49c94608820cfa/azurerm/resource_arm_virtual_machine_scale_set.go#L255-L258

DOC: https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html#accelerated_networking

the accelerated networking is at the network config, not the ip_configuration

**Comment by tombuildsstuff** [comment]
hey @djsly 

Thanks for opening this issue - I've opened #1049 which updates the documentation to fix this.

Thanks!

**Comment by djsly** [comment]
np. thanks for the PR link, next time I'll know where to fix it :)
