### ISSUE TITLE
azurerm_storage_account.id prepends C:/Program Files/Git (tested in Git Bash for windows and WSL)

### ISSUE THREAD

**Issue by mirakelsvampen** [terraform-providers/terraform-provider-azurerm#10315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0

### Affected Resource(s)
* `azurerm_storage_account`
* `azurerm_private_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {
  name                       = var.name
  resource_group_name        = var.resource_group_name
  location                   = var.location
  account_tier               = var.account_tier
  access_tier                = var.access_tier
  account_replication_type   = var.account_replication_type
  enable_https_traffic_only  = var.enable_https_traffic_only

  network_rules {
    default_action = "Deny"
    ip_rules = var.ip_rules
  }

  tags = var.tags
}

resource "azurerm_private_endpoint" "this" {
  count = var.enable_private_endpoint != false ? 1 : 0

  name                           = var.private_endpoint_name
  location                       = var.location
  resource_group_name = var.resource_group_name
  subnet_id                    = var.subnet_id

  private_service_connection {
    name                                        = "${var.private_endpoint_name}-connection"
    private_connection_resource_id = azurerm_storage_account.this.id
    is_manual_connection               = false
    subresource_names                  = [
      "blob",
      "file",
    ]
  }

  tags = var.tags
}
```

### Expected Behaviour

```
      + private_service_connection {
          + is_manual_connection           = false
          + name                           = "storageaccountname-privlink-connection"
          + private_connection_resource_id = "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Storage/storageAccounts/storageaccountname"
          + private_ip_address             = (known after apply)
          + subresource_names              = [
              + "blob",
              + "file",
            ]
        }
```

### Actual Behaviour
```
      + private_service_connection {
          + is_manual_connection           = false
          + name                           = "storageaccountname-privlink-connection"
          + private_connection_resource_id = "C:/Program Files/Git/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Storage/storageAccounts/storageaccountname"
          + private_ip_address             = (known after apply)
          + subresource_names              = [
              + "blob",
              + "file",
            ]
        }
```
### Steps to Reproduce

Create following resource:
* [azurerm_storage_account](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account)
* [azurerm_private_endpoint](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint)

Set the attribute `private_connection_resource_id` to azurerm_storage_account.this.id and run `terraform plan`

1. `terraform apply`

### Important Factoids

I am running on Windows 10 OS build 192042.746. The problem first showed when running in git bash for windows. Then I tested in WSL (Ubuntu 18.08). I removed the .terraform folder and ran init again after switching to WSL.

**Comment by tombuildsstuff** [comment]
hi @mirakelsvampen 

Thanks for opening this issue.

Unfortunately this is a known issue in Terraform Core when using cygwin - where the working directory can be prefixed into arguments as they're passed through. In this case you should be able to quote the ID, or run Terraform from either PowerShell or Command Prompt which should ensure this is interpreted correctly.

Since this is a bug in Terraform Core I'm going to close this issue for the moment - but if one of the suggestions above doesn't work I'd recommend opening an issue on [the Terraform Core repository](https://github.com/hashicorp/terraform) where someone from the Core team should be able to take a look.

Thanks!
