### ISSUE TITLE
[Testing]M2 Resource Validation Testing

### ISSUE THREAD

**Issue by WodansSon** [terraform-providers/terraform-provider-azurerm#1031]
## App Service Resource
* Certificates (TBD)
* Domains (TBD)
* Web Apps (TBD)

## App Service (Web Apps) Resource
- [x] [azurerm_app_service](https://www.terraform.io/docs/providers/azurerm/r/app_service.html)
- [x] [azurerm_app_service_plan](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html) *
- [x] [azurerm_app_service_active_slot](https://www.terraform.io/docs/providers/azurerm/r/app_service_active_slot.html) *
- [x] [azurerm_app_service_slot ](https://www.terraform.io/docs/providers/azurerm/r/app_service_slot.html) *

## CDN Resource
  - [x] [azurerm_cdn_endpoint](https://www.terraform.io/docs/providers/azurerm/r/cdn_endpoint.html) (P1) [Test Pass Results](https://gist.github.com/lrxtom2/6761d18dcf57bd0dccb3c38d496b11dd)
    - [x] [origin](https://www.terraform.io/docs/providers/azurerm/r/cdn_endpoint.html#origin)
  - [x] [azurerm_cdn_profile](https://www.terraform.io/docs/providers/azurerm/r/cdn_profile.html) (P1) [Test Pass Result](https://gist.github.com/lrxtom2/b92874aecf2b36f5c167352d7bb238ea)
* Edge Nodes (**???**)
* Custom Domains (TBD)
* List Operations (**???**)

## Compute Resource
* Attach Encrypted Disks (TBD)

## Container Resource
- [x] [azurerm_kubernetes_cluster](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html) (P1) [Test Pass Results](https://gist.github.com/jeffreyCline/4dd0bffffd9341ee1d3590d94f729bbd)
- [x] [azurerm_container_registry](https://www.terraform.io/docs/providers/azurerm/r/container_registry.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/66b64bf47354a4fd46687e5f72536d49)

## CosmosDB Resource
- [X] [azurerm_cosmos_db_account](https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/5fd36c68a94de97ecdde3086d7c197c7)

## Data Source
- [x] [azurerm_application_security_group](https://www.terraform.io/docs/providers/azurerm/d/application_security_group.html)  (P1) * [Test Pass Results](https://gist.github.com/jeffreyCline/0525505e167256037341cc1781ed3e99)
- [x] [azurerm_eventhub_namespace](https://www.terraform.io/docs/providers/azurerm/d/eventhub_namespace.html) (P1) [Test Pass Results](https://gist.github.com/jeffreyCline/2a05fc0e9d30164f5d2c8c57e7a52d8e)
- [x] [azurerm_subscription](https://www.terraform.io/docs/providers/azurerm/d/subscription.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/6be535576451f63e863f71138190c3c0)
- [x] [azurerm_traffic_manager_geographical_location](https://www.terraform.io/docs/providers/azurerm/d/traffic_manager_geographical_location.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/32cf887d9bf560eafd62da35689b5ef0)

## Messaging Resource
- [x] [azurerm_eventhub](https://www.terraform.io/docs/providers/azurerm/r/eventhub.html) (P1) [Test Pass Results](https://gist.github.com/jeffreyCline/822e9fb317a36ea7e0a71c54ab3f860a)
- [x] [azurerm_eventhub_consumer_group](https://www.terraform.io/docs/providers/azurerm/r/eventhub_consumer_group.html) (P1) [Test Pass Results](https://gist.github.com/lrxtom2/359ba02459d8703a98181ed51d01e9f9)
- [x] [azurerm_eventhub_authorization_rule](https://www.terraform.io/docs/providers/azurerm/r/eventhub_authorization_rule.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/bf4f4506c99d6191f5db7a0a33cf645f)

## Management Resource
- [x] [azurerm_management_lock](https://www.terraform.io/docs/providers/azurerm/r/management_lock.html) (P1) [Test Pass Results](https://gist.github.com/jeffreyCline/a2612d7c57101c59e307f30a0d8d4f6b)
* Policy Assignments (**???**)
* Resource Links (TBD)
* Tenants (TBD)

## Network Resource
- [x] [azurerm_traffic_manager_endpoint](https://www.terraform.io/docs/providers/azurerm/r/traffic_manager_endpoint.html) (P1) [Test Pass Results](https://gist.github.com/lrxtom2/77efd26fee61c4106cac10477912efce)
- [x] [azurerm_traffic_manager_profile](https://www.terraform.io/docs/providers/azurerm/r/traffic_manager_profile.html) (P1) [Test Pass Result](https://gist.github.com/lrxtom2/3a7804d3c6f71e7ba34cda30e18a2f1d)
- [x] [azurerm_network_watcher](https://www.terraform.io/docs/providers/azurerm/r/network_watcher.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/1b35ef938e88e09de699dde8741f64e6)
- [x] [azurerm_virtual_network_gateway](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/22e09695c4ad57c53877aa4ac6ce45b4)
- [x] [azurerm_virtual_network_gateway_connection](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway_connection.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/cfa08fc149964af7686b0b77a3b2aaf0)
- [x] [azurerm_local_network_gateway](https://www.terraform.io/docs/providers/azurerm/r/local_network_gateway.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/05fc87d8873d8363feda9789333c6ef3)
- [x] [azurerm_express_route_circuit](https://www.terraform.io/docs/providers/azurerm/r/express_route_circuit.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/7c8c45c2ba55917bde031cf0ed64553b)
- [x] [azurerm_express_route_circuit_authorization](https://www.terraform.io/docs/providers/azurerm/r/express_route_circuit_authorization.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/4a40fa57e4db15589a81a07358d332ec)
- [x] [azurerm_express_route_circuit_peering](https://www.terraform.io/docs/providers/azurerm/r/express_route_circuit_peering.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/9bb32208cf635772c96b7cffe701f807)
* BGP Service communities (TBD)
* Packet Capture (TBD)

## Policy Resource
- [ ] [azurerm_policy_definition](https://www.terraform.io/docs/providers/azurerm/r/policy_definition.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/9bb7d0f3887c52ef58b8d48814b5a0c0)

## Redis Resource
- [x] [azurerm_redis_cache](https://www.terraform.io/docs/providers/azurerm/r/redis_cache.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/a36c5c27223a0a267df2d8984af763bf)
  - [x] [patch_schedule](https://www.terraform.io/docs/providers/azurerm/r/redis_cache.html#patch_schedule)

## Scheduler Resource
- [x] [azurerm_scheduler_job_collection](https://www.terraform.io/docs/providers/azurerm/r/scheduler_job_collection.html) (P2) [Test Pass Results](https://gist.github.com/lrxtom2/2ec7292ce5975c774a64db4b345f9dc8)
* Jobs (TBD)

`*` = New Resource

**Comment by metacpp** [comment]
@irxtom2
