### ISSUE TITLE
Support for Cosmosdb Cassandra tables

### ISSUE THREAD

**Issue by blame19** [terraform-providers/terraform-provider-azurerm#10327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be good to have support for cassandra tables - at the moment we can create keyspaces thanks to this (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_cassandra_keyspace), however we need to resort to the portal or AZ cli to add tables once the keyspaces are in place.

### New or Affected Resource(s)

* azurerm_cosmosdb_cassandra_tables

**Comment by favoretti** [comment]
Working on it as we speak.
