### ISSUE TITLE
Getting permission errors creating azurerm_key_vault_secret despite adding correct permissions

### ISSUE THREAD

**Issue by sonic1981** [terraform-providers/terraform-provider-azurerm#10329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-providers/mongodbatlas v0.8.0
```

### Affected Resource(s)

* `azurerm_key_vault_secret`
* `azurerm_key_vault_access_policy`
* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "kv" {
  name                                = "<name>"
  location                            = var.rg.location
  resource_group_name                 = var.rg.name
  enabled_for_disk_encryption         = true
  tenant_id                           = data.azurerm_client_config.current.tenant_id
  soft_delete_enabled                 = true
  purge_protection_enabled            = false

  sku_name                            = "standard"

}

resource "azurerm_key_vault_access_policy" "self" {
  key_vault_id                    = azurerm_key_vault.kv.id

  tenant_id                           = data.azurerm_client_config.current.tenant_id
  object_id                           = data.azurerm_client_config.current.object_id

  secret_permissions = [
      "Get",
	    "Set",
      "Delete",
      "Purge",
      "List"
    ]
  storage_permissions  = [
      "get",
      "set",
      "list",
      "delete",
      "purge"
    ]
}

resource "azurerm_key_vault_secret" "secret" {
  key_vault_id                      = azurerm_key_vault.kv.id
  name                              = "name"
  value                             = "value"
}

```

### Expected Behaviour

Key vault secret should of been created successfully first time (this used to work in version 2.29.0 but seems to of been broken in the latest version)

### Actual Behaviour

Terraform created the keyvault but then error'd when creating the `azurerm_key_vault_secret` stating that it did not have permissions to add the secret to the keyvault. Running `terraform apply` a second time resulting the in secret being created successfully, so this appears to be a timing issue.

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
@sonic1981 in the Terraform Configuration above there's no dependency between the Secret and the Access Policy, so these can be created in parallel - [more information about dependencies in Terraform can be found in this article](https://learn.hashicorp.com/tutorials/terraform/dependencies)

Since this should be fixed by updating the Terraform Configuration being used here, I'm going to close this issue for the moment - but should you have further usage questions I'd point you towards [the community discussion forum](https://discuss.hashicorp.com).

Thanks!
