### ISSUE TITLE
Creating Azure Container Group with GPU returns The requested resource is not available in the location...

### ISSUE THREAD

**Issue by markokole** [terraform-providers/terraform-provider-azurerm#10332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem description

Im trying to provision a container with GPU with no luck. I tried from Azure portal and with az cli and it worked. I have managed to provision a container withiut the gpu block as well. Only when running with gpu block with terraform I get this error message.

### Terraform (and AzureRM Provider) Version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0

### Affected Resource(s)
* `azurerm_container_group`

### Expected Behaviour

Successful provisioning

### Actual Behaviour

azurerm_container_group.gpu: Creating...
azurerm_container_group.gpu: Still creating... [10s elapsed]

Error: Error creating/updating container group "gpu-group" (Resource Group "test-rg"): containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceUnavailable" Message="The requested resource is not available in the location 'westeurope' at this moment. Please retry with a different resource request or in another location. Resource requested: '1' CPU '2' GB memory 'Linux' OS '2' 'K80' GPU virtual network"

### Steps to Reproduce

```
resource "azurerm_container_group" "gpu" {
  name                = "gpu-group"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  ip_address_type     = "Private"
  network_profile_id  = azurerm_network_profile.network_profile.id
  os_type             = "Linux"
  restart_policy      = "Never"
  image_registry_credential {
    server   = azurerm_container_registry.acr.login_server
    username = var.ARM_CLIENT_ID 
    password = var.ARM_CLIENT_SECRET
  }

  container {
    name   = "gpu"
    image  = "testXYZ.azurecr.io/docker-image:test"
    cpu    = 1
    memory = 2
    gpu {
      count = 2
      sku = "K80"
    }
    ports {
      port     = 80
      protocol = "TCP"
    }
    commands = [ "python", "./run.py" ]
  }
}
```

`1. `terraform apply`

Open for suggestions. Thank you.

**Comment by phatcher** [comment]
First try creating one from the Azure portal to see if it's a subscription-level issue, this might also highlight any issue regarding the resource group being associated with Windows etc.

If you can do it from the portal, try creating a new resource group to use in the terraform and it should be ok

**Comment by markokole** [comment]
please read my post, @phatcher

**Comment by tombuildsstuff** [comment]
hi @markokole 

Thanks for opening this issue.

Taking a look at the response being returned from the Azure API here:

> The requested resource is not available in the location 'westeurope' at this moment. Please retry with a different resource request or in another location. Resource requested: '1' CPU '2' GB memory 'Linux' OS '2' 'K80' GPU virtual network

Azure is stating that it doesn't have any capacity/quota for this resource when this was provisioned (I presume this is related to the GPU requirement, since these are only available on a subset of their nodes) - as such unfortunately there's not much Terraform can do to work around this and you'd need to provision this into an different region (where there may be additional capacity/quota to handle this).

Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - I'm going to close this issue for the moment, but I'd suggest reaching out to Azure Support to confirm where capacity/quota is available should you continue to have issues here.

Thanks!

**Comment by markokole** [comment]
@tombuildsstuff 
Like I wrote in my original post, this WORKS using az cli and from Azure portal, its only from Terraform that it does not deliver.

**Comment by blacksheep--** [comment]
This also happens when a container group needs to be recreated on image change.
