### ISSUE TITLE
acctests failing on Recoveryservices

### ISSUE THREAD

**Issue by MitchDrage** [terraform-providers/terraform-provider-azurerm#10346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.5
AzureRM v2.44.0

### Affected Resource(s)

* `azurerm_recoveryservices`

### Terraform Configuration Files

N/A

### Debug Output

[Acctest output](https://gist.github.com/MitchDrage/c4dfcc2bb095ae287719d464c8c3ff97)

### Panic Output

N/A

### Expected Behaviour

All tests run against current version (2.44.0) should pass.

### Actual Behaviour

The following specific tests are failing:

1. --- FAIL: TestAccBackupProtectionPolicyVM_requiresImport
2. --- FAIL: TestAccSiteRecoveryProtectionContainer_basic
3. --- FAIL: TestAccSiteRecoveryReplicationPolicy_basic
4. --- FAIL: TestAccSiteRecoveryReplicatedVm_basic
5. --- FAIL: TestAccBackupProtectedVm_updateBackupPolicyId
6. --- FAIL: TestAccBackupProtectionPolicyVM_updateDailyToWeekly

### Steps to Reproduce

1. `make acctests SERVICE='recoveryservices'`

This acctests is being run on v2.44.0 with the following changes:
- VM resource changed from Standard_A0 to Standard_B1ms due to my MPN subscription not allowing A0.
- GNUmakefile acctests adjusted to remove the trailing /tests folder - not sure why it's there in the first place because I can't find any service that keeps the tests in a specific folder.

### Important Factoids

I'm raising a PR to resolve these issues as they should be resolved before an SDK bump is conducted - bump required as prereq for [Issue-8837](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8837)

I've found the following causes:

1. --- FAIL: TestAccBackupProtectionPolicyVM_requiresImport
- The test config in 'requiresImport' and the inherited config 'template' doesn't include a resource 'azurerm_backup_policy_vm' 'test', however basicDaily does.
- Changing 'requiresImport' to reference 'basicDaily' instead of 'template' resolves the issue (basicDaily inherits from template anyway, and appears not to have any other purpose).
- Result: --- PASS: TestAccRecoveryServicesVault_requiresImport (143.37s)

2. --- FAIL: TestAccSiteRecoveryProtectionContainer_basic
- Caused by dangling resources from issue 1.
- Result after fixing above: --- PASS: TestAccSiteRecoveryProtectionContainer_basic (333.44s)

3.  --- FAIL: TestAccSiteRecoveryReplicationPolicy_basic
- Caused by dangling resources from issue 1.
- Result after fixing above: --- PASS: TestAccSiteRecoveryReplicationPolicy_basic (202.54s)

4. --- FAIL: TestAccSiteRecoveryReplicatedVm_basic
- Caused by dangling resources from issue 1.
- Result after fixing above: --- PASS: TestAccSiteRecoveryReplicatedVm_basic (2952.41s)

5. --- FAIL: TestAccBackupProtectedVm_updateBackupPolicyId
- Issues with this test are unrelated to issue 1. Details below, but they will be hard to understand without a diff. See the PR that I'll raise and it might make more sense.
- Failure in test step 0 is due to a duplicate VM resource between the 'withVM' and 'base'. Removing 'withVM' and getting the config from 'withSecondPolicy' resolves the issue.
- Failure in test step 1 also used the 'withVM' config. Moving this one to 'withSecondPolicy' also resolves this issue.
- Step 2 is a step to revert the policy in step 1, so moving the config from 'withVM' to 'withSecondPolicy' removes the dependency on 'withVM' and resolves the 3rd issue.
- The resource '"azurerm_backup_policy_vm" "test"' within 'withFirstPolicy' is also created in 'base' so throws a duplicate resource error. Removing 'withFirstPolicy' resolves the issue - it is redundant as best I can tell since all of it's resources are in 'base'.
- Lastly, by linking 'withSecondPolicy' directly to 'base', the following configs are now redundant and can be removed: withVM, withFirstPolicy, withVault. As touched on above, these three configs are all duplicating resources that are in 'base' and therefore throwing conflict errors.

6. --- FAIL: TestAccBackupProtectionPolicyVM_updateDailyToWeekly
- Caused by dangling resources from issue 1.
- Result after fixing above: --- PASS: TestAccBackupProtectionPolicyVM_updateDailyToWeekly (234.85s)

### References

N/A

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #10347
