### ISSUE TITLE
Terraform code feature azurerm_mssql_server for enabling Transparent data encryption using customer manged key

### ISSUE THREAD

**Issue by jayanthrajanna** [terraform-providers/terraform-provider-azurerm#10357]
Can any please share the terrform code for enabling Transparent data encryption for azurerm_mssql_server. Currently i see this feature is available for mysql but not for mssql. 

Please help. Thanks in advance.

**Comment by tdrimmelen** [comment]
👍 
As far as I see from the documentation, it is not supported yet.

**Comment by manicminer** [comment]
Hi @jayanthrajanna, this is supported using the [azurerm_mssql_server_transparent_data_encryption](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server_transparent_data_encryption) resource.
