### ISSUE TITLE
Support for Azure Purview

### ISSUE THREAD

**Issue by xyzzykdj** [terraform-providers/terraform-provider-azurerm#10358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to provision azure purview accounts with terraform
https://azure.microsoft.com/en-us/services/purview/

### New or Affected Resource(s)

* azurerm_purview_account

### Potential Terraform Configuration

```hcl
resource "azurerm_purview_account" "example" {
  name                = "string"
  location            = "string"
  resource_group_name  = "string"
}
```

### References

* #0000

**Comment by allantargino** [comment]
It depends on #10393

**Comment by allantargino** [comment]
I suggest the following interface:

```hcl
resource "azurerm_purview_account" "example" {
  name                   = "string"
  location               = "string"
  resource_group_name    = "string"
  sku_capacity           = 4
  public_network_enabled = true
}
```

**Comment by samvruggink** [comment]
It would be great to also add the Purview integrations with Azure Data Factory and Azure Data Share.

**Comment by allantargino** [comment]
Yes @samvruggink, but it is not yet available on the REST API spec: https://github.com/Azure/azure-rest-api-specs/blob/16f08cbbd9f207f808270cf6fb5375e46bc5ab2c/specification/purview/resource-manager/Microsoft.Purview/preview/2020-12-01-preview/purview.json
