### ISSUE TITLE
Since upgrading 2.45, want to recreate all azurerm_key_vault_secret !

### ISSUE THREAD

**Issue by alex-3sr** [terraform-providers/terraform-provider-azurerm#10366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azuread v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.45.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)
* `azurerm_key_vault_secret `

### Terraform Configuration Files
not relevant

### Debug Output

```hcl
# azurerm_key_vault_secret.kvsecret_xxxx will be created
  + resource "azurerm_key_vault_secret" "kvsecret_xxxx" {
      + id           = (known after apply)
      + key_vault_id = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.KeyVault/vaults/xxx"
      + name         = "xxx"
      + value        = (sensitive value)
      + version      = (known after apply)
    }
etc...
```

### Expected Behaviour
It's not need to recreate all Key Vaults secrets

### Actual Behaviour
Want to recreate all Key Vaults secrets

### Steps to Reproduce
1. `upgrade ARM 2.45 on a project with existing key vault secrets`
2.  `terraform plan`

### Important Factoids
if downgrading to 2.44, we don't have anymore terraform plan want to recreate all key vaults secrets

**Comment by arkiaconsulting** [comment]
I would add that if we try to import the existing secret given its id, in order to resync the state, the provider says that it cannot find it.

**Comment by dkirrane** [comment]
I'm seeing this in azurerm `2.44.0` also. 

Secrets are already in terraform state and in key vault but terraform plan want to create them again.
```
  # azurerm_key_vault_secret.datadog_api_key will be created
  + resource "azurerm_key_vault_secret" "datadog_api_key" {
```

it will fail on terraform apply
```
Error: A resource with the ID "https://my-kv.vault.azure.net/secrets/datadog-api-key/11f30059c3c24363a8b200f68c093100" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_secret" for more information.
```

**Comment by dlm69** [comment]
> I'm seeing this in azurerm `2.44.0` also.
> 
> Secrets are already in terraform state and in key vault but terraform plan wants to create them again.
> 
> ```
>   # azurerm_key_vault_secret.datadog_api_key will be created
>   + resource "azurerm_key_vault_secret" "datadog_api_key" {
> ```
> 
> it will fail on terraform apply
> 
> ```
> Error: A resource with the ID "https://my-kv.vault.azure.net/secrets/datadog-api-key/11f30059c3c24363a8b200f68c093100" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_secret" for more information.
> ```

I have reverted to 2.44 and everything seems fine. If you've run terraform apply using 2.45.1 then you will need to import the key vault secrets again but 2.44 seems to be working as expected.

**Comment by tombuildsstuff** [comment]
Consolidating this into #10371
