### ISSUE TITLE
Feature Request: Support for Azure Relay

### ISSUE THREAD

**Issue by OOPMichael** [terraform-providers/terraform-provider-azurerm#1036]
Service Bus (WCF) Relay And/Or the newer Azure Relay Service.

**Comment by tombuildsstuff** [comment]
hey @OOPMichael 

Thanks for opening this issue :)

I was able to spend a little time looking into Relay Namespaces yesterday and have opened #1233 which adds support for these.

Thanks!

**Comment by katbyte** [comment]
Hey @OOPMichael,

Just wanted to let you know we have released [v1.6.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#160-may-24-2018) of the provider containing support for Azure Relay 🙂
