### ISSUE TITLE
Error: Provider produced inconsistent result after apply when creating keyvault_secret or keyvault_certificate

### ISSUE THREAD

**Issue by calebak404** [terraform-providers/terraform-provider-azurerm#10371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.30
+ provider.azurerm v2.45.1

### Affected Resource(s)

* `azurerm_keyvault_certificate`
* `azurerm_keyvault_secret`

### Terraform Configuration Files

Basic keyvault configuration with only required arguments.

### Expected Behaviour

Terraform should have added the secrets or certificates to the keyvault.

### Actual Behaviour

Terraform produces the following error:
```
Error: Provider produced inconsistent result after apply

When applying changes to azurerm_key_vault_secret.kvs,
provider "registry.terraform.io/-/azurerm" produced an unexpected new value
for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Note: Resource is actually created in Azure, but is absent from the terraform state

### Steps to Reproduce

Update to azurerm provider to 2.45 or 2.45.1 and add a new secret or certificate to an existing keyvault

Issue is resolved if pinning the version number to =< 2.44

### Important Factoids

Remote state is managed by TFE, issue happens both when running locally with a remote backend and when being run by TFE

### References

* #10366
* #10330

**Comment by aglees** [comment]
We're also seeing secrets failing to be imported too

```
terraform import azurerm_key_vault_secret.{secretResourceName} "https://{keyvaultName}.vault.azure.net/secrets/{secretName}/{secretId}"

Acquiring state lock. This may take a few moments...
var.client_id
  Enter a value: 

var.client_secret
  Enter a value: 

azurerm_key_vault_secret.{secretResourceName}: Importing from ID "https://{vaultName}.azure.net/secrets/{secretName}/{secretId}"...
azurerm_key_vault_secret.{secretResourceName}: Import prepared!
  Prepared azurerm_key_vault_secret for import
azurerm_key_vault_secret.{secretResourceName}: Refreshing state... [id=https://{vaultName}.azure.net/secrets/{secretName}/{secretId}]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
azurerm_key_vault_secret.{secretResourceName}, the provider detected that no
object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.
```

**Comment by aglees** [comment]
It also wants to create existing secrets, as I'm guessing that it's having issues reliably communicating with the KeyVault API?

```
  # azurerm_key_vault_secret.{secretResourceName} will be created
  + resource "azurerm_key_vault_secret" "{secretResourceName}" {
      + id           = (known after apply)
      + key_vault_id = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults/{keyvaultName}}"
      + name         = "{secretName}"
      + tags         = {}
      + value        = (sensitive value)
      + version      = (known after apply)
    }
```

**Comment by shubhisethi** [comment]
@tombuildsstuff Thanks for resolving the issue quickly
