### ISSUE TITLE
Support for new AKS cluster autoscaler profile options

### ISSUE THREAD

**Issue by mkozioro** [terraform-providers/terraform-provider-azurerm#10375]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Please support new options of AKS cluster autoscaler profile:
https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#autoscalerprofile

Currently supported options:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#balance_similar_node_groups

### New or Affected Resource(s)
azurerm_kubernetes_cluster (auto_scaler_profile)

**Comment by brunhil** [comment]
I'll take a look at this one after #10407

**Comment by MichalKoziorowski-TomTom** [comment]
Hi @brunhil.

Yes, auto_scaler_profile is already supported, but not all options, for example skip-nodes-with-local-storage and skip-nodes-with-system-pods.
