### ISSUE TITLE
Setting key_vault_key_uri on azurerm_cosmosdb_account produces invalid URI passed to Azure

### ISSUE THREAD

**Issue by thomasspatzier** [terraform-providers/terraform-provider-azurerm#10379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.45.1

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
# snippet of my resource that causes the issue
resource "azurerm_cosmosdb_account" "cosmosdb-account" {
  name                = "my-account"
  location            = "centralus"
  resource_group_name = "my-rg"
  offer_type          = "Standard"
  kind                = "MongoDB"

  # enable CMK encryption
  key_vault_key_id = "https://my-key-vault.vault.azure.net/keys/my-cmk-key"

}
```

### Debug Output

```
Error: Error creating CosmosDB Account "my-account" (Resource Group "my-rg"): Error creating/updating CosmosDB Account "my-account" (Resource Group "my-rg"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Provided KeyVaultKeyUri https://my-key-vault.vault.azure.net//keys/my-cmk-key/ is Invalid.\r\nActivityId: adadada-12134-332553-def1, Microsoft.Azure.Documents.Common/2.11.0"
```

### Expected Behaviour

The Cosmos DB account should have been created with my custom CMK key used for encryption.

### Actual Behaviour

Resource creation fails with the error message above under Debug Output.
Note that the key URI stated in the error message is not exactly my string, but contains an additional slash after the vault URI and an additional one at the end, i.e. `https://my-key-vault.vault.azure.net//keys/my-cmk-key/` instead of my original `https://my-key-vault.vault.azure.net/keys/my-cmk-key`.
Seems like this makes lookup of the key fail in Azure. I just tried it myself in Azure Portal and can successfully create an account when I supply a key URI like what I can in my resource definition, but fails when I add the extra slashes.

My `terraform plan` output looks fine like 

```
  # azurerm_cosmosdb_account.my-account will be created
  + resource "azurerm_cosmosdb_account" "my-account" {
      + analytical_storage_enabled        = false
      + connection_strings                = (sensitive value)
      + enable_automatic_failover         = true
      + enable_free_tier                  = false
      + enable_multiple_write_locations   = false
      + endpoint                          = (known after apply)
      + id                                = (known after apply)
      + is_virtual_network_filter_enabled = true
      + key_vault_key_id                  = "https://my-key-vault.vault.azure.net/keys/my-cmk-key"
      
```

but at some point, the extra slashes get injected when I do `terraform apply` which causes the error.

I also tried using a reference to an `azurerm_key_vault_key` `id` attributes instead of using a hardcoded string, but got the same error.

Note: I made sure that *Azure Cosmos DB*  has access to my key vault before.

### Steps to Reproduce

1. create hcl configuration with respective resources
1. `terraform apply`

### Additional hints

I tried the sample config with version 2.36.0 of the azurerm resource provider, which I think is the one where support for the `key_vault_key_uri` property of `azurerm_cosmosdb_account` got introcuded, and it works fine with that older version.

**Comment by TPPWC** [comment]
Hi there,

we have the same problem but we are using a variable to generate the uri like this:

`key_vault_key_id = "${module.key_vault_test.vault_uri}keys/test01"`

We get the same error with the 2 //:

**https://kvtesasddda12.vault.azure.net//keys/test001/ is Invalid**

/cheers

Tom
