### ISSUE TITLE
Terraform provider fails to find images

### ISSUE THREAD

**Issue by tomtechnologies** [terraform-providers/terraform-provider-azurerm#10374]
https://github.com/terraform-providers/terraform-provider-azurerm/blob/74a15527eafd05fd9d28e4800338dd5e0ea857ac/azurerm/internal/services/compute/shared_image_version_data_source.go#L158

When there are many image versions in a shared image gallery 'latest' and 'recent' will fail to find images due to failing to deal with pagination (ie: the API call used  by the Azure SDK returns a partial set and requires recursion to discover the full set).

Code should be updated to use either process nextLink (available in the result from the call to the SDK) or offload capability and use ListByGalleryImageComplete (as available in the golang Azure SDK).

A workaround is to delete the older images to prevent the result set from requiring multiple pages to be returned.

Here you can see the rest API returns partial result sets:
https://docs.microsoft.com/en-us/rest/api/compute/galleryimages/listbygallery#galleryimagelist

Here you can see the documentation of the SDK suggesting that this will be an issue:
https://godoc.org/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute#GalleryImageVersionsClient.ListByGalleryImageComplete

**Comment by claque2000** [comment]
This issue is quite annoying. 
But when looking more deeply in code, the ListByGalleryImage function contains a reference in structure to listByGalleryNextResults function which should take the result of former API call and search through the next page of result.
But it seems it's never called.
