### ISSUE TITLE
Hide sensitive publishing password in azurerm_function_app

### ISSUE THREAD

**Issue by Jeppeks1** [terraform-providers/terraform-provider-azurerm#10385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v13.3 and AzureRM provider v2.45.0

### Affected Resource(s)

* `azurerm_function_app`

### Debug Output

```
# Only some settings are shown
# module.function_app.azurerm_function_app.app["my-function-app"] will be destroyed
- resource "azurerm_function_app" "app" {
      - app_service_plan_id = "/subscriptions/***/resourceGroups/MyResourceGroup/providers/Microsoft.Web/serverfarms/my-app-service-plan" -> null
      - id                  = "/subscriptions/***/resourceGroups/MyResourceGroup/providers/Microsoft.Web/sites/my-function-app" -> null
      - kind                = "functionapp" -> null
      - location            = "westeurope" -> null
      - name                = "my-function-app" -> null
      - resource_group_name = "MyResourceGroup" -> null
      - site_credential = [
          - {
              - password = "actual password" <-------- This password is in plaintext
              - username = "$my-function-app"
            },
        ] -> null
      - storage_account_access_key = (sensitive value)
      - storage_account_name       = "mystorageaccount" -> null
      - storage_connection_string  = (sensitive value)
      - version                    = "~3" -> null
 }
```

### Expected Behaviour

The password(s) in the site_credential block should be marked as sensitive.

### Actual Behaviour

The password is visible in plaintext when the Function App is about to be deleted. As there is an approval gate between the plan-step and apply-step, there is a high risk of exposing the actual password. My understanding of the publishing functionality of the Function App is that the username and password alone is enough to publish code to the Function App, making it a security risk.

### Steps to Reproduce

1. `terraform apply` on any valid Function App configuration.
2. `terraform destroy`

**Comment by tombuildsstuff** [comment]
hi @Jeppeks1 

Thanks for opening this issue.

Taking a look whilst this field is marked as Sensitive within the Azure Provider, the root cause of this appears to be [this upstream issue in the Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk/issues/201). Since this needs to be fixed upstream I'm going to close this issue in favour of that one, but once this is fixed upstream we can update the version of the SDK in use that which will fix this issue.

Thanks!
