### ISSUE TITLE
Feature Request: resource for adding backend_pools_ids to a NIC's IP Configuration

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#1038]
### Terraform Version
Terraform v0.11.5
provider.azurerm v1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_network_interface
- azurerm_lb_backend_address_pool

### Request Details
AFAIK, placing a NIC into a Load Balancer's Backend Pool requires referencing the pool (or pools) as a list in the NIC's `ip_configuration {  }` sub-section. However, this becomes an issue if building an LB and VMs separately and then trying to bind them together later. An attachment-type resource like `aws_lb_target_group_attachment` would be very useful.

### References
This request (https://github.com/terraform-providers/terraform-provider-azurerm/issues/769) is related, but is a more complicated approach to the problem.

**Comment by katbyte** [comment]
Hi @kjhosein,

This was recently added in `v1.17` as the `azurerm_network_interface_backend_address_pool_association` resource.

I am going to close this issue for now, please feel free to reopen it if you continue to have problems 🙂
