### ISSUE TITLE
Support for AKS Host Encryption

### ISSUE THREAD

**Issue by etaham** [terraform-providers/terraform-provider-azurerm#10387]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Encryption in transit for azure storage is now in preview for AKS (https://docs.microsoft.com/en-us/azure/aks/enable-host-encryption#use-host-based-encryption-on-new-clusters-preview). Please add the needed flag as an option for AKS node pools.

This feature is available many vm sku's, but not all. It may be worth delegating to the azure api when trying to set the flag. It also seems like changing the flag requires the node pool to be recreated.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster (default_node_pool specifically)
* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2s_v2"
    enable_encryption_at_host = true //Set to true to activate the preview functionality. 
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  enable_encryption_at_host = true //Set to true to activate the preview functionality. 

  tags = {
    Environment = "Production"
  }
}
```

### References

* #0000

**Comment by brunhil** [comment]
I'll take a look into this, seems like it may be available in the current Go SDK
