### ISSUE TITLE
Error updating ExpressRoute circuit bandwidth

### ISSUE THREAD

**Issue by mud5150** [terraform-providers/terraform-provider-azurerm#1039]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.5
+ provider.azurerm v1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_express_route_circuit

### Terraform Configuration Files
```hcl
resource "azurerm_express_route_circuit" "exp_route_circuit" {
  name                  = "${var.project}-exp-route-circuit"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  location              = "${azurerm_resource_group.rg.location}"
  service_provider_name = "${var.service_provider_name}"
  peering_location      = "${var.peering_location}"
  bandwidth_in_mbps     = "${var.express_route_bandwidth}"

  sku {
    tier   = "${var.circuit_sku["tier"]}"
    family = "${var.circuit_sku["family"]}"
  }

  tags {
    projectname = "${var.project}"
    environment = "${var.environment}"
    team        = "${var.team}"
  }
}
```
Here is the plan output
```
~ azurerm_express_route_circuit.exp_route_circuit 
      bandwidth_in_mbps: "50" => "1000" 
```

### Debug Output
https://gist.github.com/mud5150/80f1b41dbc64d6840f885098a2ab3ee6

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
I should be able to modify the bandwidth settings on the ExpressRoute circuit and run apply successfully.

### Actual Behavior
Got an error
`'Failed': Code="ConflictError" Message="The specified bgp peering is in use. Please delete the links associated with the specified service key and try again."`

The bandwidth update did appear to go through correctly however and I used refresh to update the terraform state.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
It's possible this is an issue with the Azure api and not Terraform. In the web interface the circuit started showing a failed state for a moment. It's also possible it may be related to the fact that someone else was refreshing the peering routes on the circuit via the azure portal at the same time. Interesting that in the resource activity log it shows the write as successful with a 200 response but the RouteTables read from the user doing the refresh in the portal gives the same 400 error that terraform displayed. Here's some output from those logs

```
eventTimestamp": "2018-03-28T20:56:27.6347386Z",
    "id": "/subscriptions/**********************/resourceGroups/azeast-hubvnet-rg/providers/Microsoft.Network/expressRouteCircuits/azeast-hubvnet-exp-route-circuit/events/366a0257-c59c-4fb4-9d66-497531a568ee/ticks/636578673876347386",
    "level": "Informational",
    "operationId": "3d4a88cb-6542-46a1-9f33-104cf2719957",
    "operationName": {
        "value": "Microsoft.Network/expressRouteCircuits/write",
        "localizedValue": "Microsoft.Network/expressRouteCircuits/write"
    },
    "resourceGroupName": "azeast-hubvnet-rg",
    "resourceProviderName": {
        "value": "Microsoft.Network",
        "localizedValue": "Microsoft.Network"
    },
    "resourceType": {
        "value": "Microsoft.Network/expressRouteCircuits",
        "localizedValue": "Microsoft.Network/expressRouteCircuits"
    },
    "resourceId": "/subscriptions/**********************/resourceGroups/azeast-hubvnet-rg/providers/Microsoft.Network/expressRouteCircuits/azeast-hubvnet-exp-route-circuit",
    "status": {
        "value": "Accepted",
        "localizedValue": "Accepted"
    },
    "subStatus": {
        "value": "OK",
        "localizedValue": "OK (HTTP Status Code: 200)"
    },
    "submissionTimestamp": "2018-03-28T20:56:46.1715247Z",
    "subscriptionId": "**********************",
    "properties": {
        "statusCode": "OK",
        "serviceRequestId": "7bef7719-6f1c-4e75-b2ad-50dbe36bd242"
    },
    "relatedEvents": []
}
```

```
"eventTimestamp": "2018-03-28T20:56:28.2986133Z",
    "id": "/subscriptions/**********************/resourceGroups/azeast-hubvnet-rg/providers/Microsoft.Network/expressRouteCircuits/azeast-hubvnet-exp-route-circuit/peerings/AzurePrivatePeering/routeTables/Primary/events/d94256de-2a6c-478b-ad84-43c1284caace/ticks/636578673882986133",
    "level": "Error",
    "operationId": "3e02f7e1-b731-44cd-95a5-414d54d9104d",
    "operationName": {
        "value": "Microsoft.Network/expressRouteCircuits/peerings/routeTables/action",
        "localizedValue": "Microsoft.Network/expressRouteCircuits/peerings/routeTables/action"
    },
    "resourceGroupName": "azeast-hubvnet-rg",
    "resourceProviderName": {
        "value": "Microsoft.Network",
        "localizedValue": "Microsoft.Network"
    },
    "resourceType": {
        "value": "Microsoft.Network/expressRouteCircuits/peerings",
        "localizedValue": "Microsoft.Network/expressRouteCircuits/peerings"
    },
    "resourceId": "/subscriptions/**********************/resourceGroups/azeast-hubvnet-rg/providers/Microsoft.Network/expressRouteCircuits/azeast-hubvnet-exp-route-circuit/peerings/AzurePrivatePeering/routeTables/Primary",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "BadRequest",
        "localizedValue": "Bad Request (HTTP Status Code: 400)"
    },
    "submissionTimestamp": "2018-03-28T20:56:46.15956Z",
    "subscriptionId": "**********************",
    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": "99e0792f-5e2e-48af-ba9b-15e081d2a8ac",
        "statusMessage": "{\"error\":{\"code\":\"ExpressRouteBgpPeeringNotFound\",\"message\":\"The BGP Peering AzurePrivatePeering with Service Key 34d8601c-2c63-4010-b664-f9aabe06d69a is not found.\",\"details\":[]}}"
    },
    "relatedEvents": []
}
```

I will do some more research on this but I wanted to get an issue opened asap.

**Comment by tombuildsstuff** [comment]
hey @mud5150 

Thanks for opening this issue :)

Looking at the error message being returned:

> 'Failed': Code="ConflictError" Message="The specified bgp peering is in use. Please delete the links associated with the specified service key and try again."

and the behaviour you're seeing (the value's updated, but it's in the Failed state) - it sounds like it's only possible to change the bandwidth for a given Circuit when there's no peerings attached? The Failed state will appear since the configuration is invalid according to Azure (but should be valid upon a new connection/peering being initiated) - out of interest does this work as expected when trying to change the `bandwidth_in_mbps` field when no connections are present?

If so, the best way to solve this for the moment would probably be to add a section to the documentation suggesting folks run `terraform taint` for any peerings (which will be available natively in the next Provider release) before making this change?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @mud5150 

Since we've not heard back from you here - I'm going to close this issue for the moment. Should this still be an issue please feel free to re-open it and we'll take another look :)

Thanks!

**Comment by mud5150** [comment]
Unfortunately project deadlines forced me to move on from troubleshooting this further. Once this particular project is finished I may be able to come back around and try to dig into this more.
