### ISSUE TITLE
Support for auto upgrade channel

### ISSUE THREAD

**Issue by dkirrane** [terraform-providers/terraform-provider-azurerm#10407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support setting auto-upgrade channel on an AKS cluster
https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "foo"
  vm_size               = "Standard_DS2_v2"
  node_count            = 3
  
  auto_upgrade_channel = "patch"
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

**Comment by brunhil** [comment]
Should be doable! I'll get this for the `azurerm_kubernetes_cluster_node_pool` and `azurerm_kubernetes_cluster` resources

**Comment by shapeofarchitect** [comment]
We are all on AKS and this feature would be super helpful for us to be able to run TF apply via schedule pipeline and not worry about the manual triggers. Appreciate in advance !
