### ISSUE TITLE
r/kubernetes_cluster: api returns InvalidIdentityValues during update

### ISSUE THREAD

**Issue by ortelli-oxalide** [terraform-providers/terraform-provider-azurerm#10406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.14.5 (same behaviour with 0.14.4)
Azurerm 2.45.0 (same behaviour with 2.44.0)

### Affected Resource(s)

* `azurerm_kubernetes_cluster` when using identity.type="UserAssigned"

### Terraform Configuration Files

```hcl
resource "azurerm_user_assigned_identity" "aks" {
  resource_group_name = "myresourcegroup"
  location                         = "francecentral"
  name                             = "mycluster-identity"
}

resource "azurerm_kubernetes_cluster" "aks" {
  name     = "mycluster"
  location = "francecentral"
  
  resource_group_name = "myresourcegroup"
  node_resource_group  = "myresourcegroup-nodes"

  identity {
    type                                    = "UserAssigned"
    user_assigned_identity_id = azurerm_user_assigned_identity.aks.id
  }
  
  network_profile {
    network_plugin     = "kubenet"
    network_policy     = "calico"
    load_balancer_sku  = "Standard"
    outbound_type      = "userDefinedRouting"
    ...
  }

  private_cluster_enabled = false
  kubernetes_version        = "1.18.14"

  addon_profile {
    ...
  }

  default_node_pool {
    ...
    enable_auto_scaling = true
    min_count = 3
    max_count = 18
  }
```

### Debug Output

```
Error: updating Managed Kubernetes Cluster "mycluster" (Resource Group "myresourcegroup"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidIdentityValues" Message="Invalid value for the identities '/subscriptions/xxxxxxxxx/resourceGroups/myresourcegroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mycluster-identity'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."

  on aks.tf line 1, in resource "azurerm_kubernetes_cluster" "aks":
   1: resource "azurerm_kubernetes_cluster" "aks" {
```

### Expected Behaviour

The creation of azurerm_kubernetes_cluster worked without any problem. When I change a simple property (not related with user assigned identity), like default_node_pool.min_count I would expect the apply to not raise issues with UserAssignedIdentities

### Actual Behaviour

The creation of azurerm_kubernetes_cluster worked without any problem. When I change a simple property like default_node_pool.min_count or any other, I receive the error reported in Debug Output section.

### Steps to Reproduce

1. Create a cluster with user assigned identity (of course via terraform)
2. Change an azurerm_kubernetes_cluster property such as default_node_pool.min_count
3. `terraform plan`, no problem in the plan  
4. `terraform apply` and approve : error raised here

### References

Using UserAssigned identity, a feature released in 1.44.0 (https://github.com/terraform-providers/terraform-provider-azurerm/pull/8737/files)

**Comment by Aohzan** [comment]
Quote from Azure support:

> This is a known issue and we are working internally to solve it. In the meanwhile could you please try to use private flight using this link, once the portal opens try to change one of the setting on  your aks cluster: https://portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_ContainerService=flight1#home . The fix will be merged to prod soon.

**Comment by wiebeck** [comment]
@Aohzan Can you (or anyone else) explain what this "private flight" link is about? I must admit I don't get it.

**Comment by Aohzan** [comment]
No idea, Azure support don't give any information about this

**Comment by tombuildsstuff** [comment]
@Aohzan my understanding is that link should show you the latest ui hotfixes rather than waiting for them to roll out - but in this instance this isn't a Portal issue but an API issue. It's possible that what they're suggesting (e.g. adding/removing a tag through that link) may update the API model on the backend to include the latest bugfixes, which I _think_ is what they're referring too - but if I'm honest I'm unsure if that'll fix this since Terraform doesn't connect to this API but the main (management.azure.com) one.

That said, it would be interesting to confirm if this does fix this for you, since the fix needs to be applied at Azure's side (namely in the API)?

**Comment by caldwell2000** [comment]
Is there any update from Microsoft?  I'm getting the same error even if I don't change a single line of code and run an apply.  The first time the AKS cluster is built, there are no errors, but every subsequent "apply" produces this error.

**Comment by ortelli-oxalide** [comment]
The same error is raised by Azure console, for instance when trying to update AKS network settings. That prove this is not a bug with TF provider, but with Azure itself. I suppose that the link provided by @Aohzan is the "beta version" containing the fix, and it's going to be released hopefully soon !

**Comment by tsproull** [comment]
Is there a link to the Microsoft ticket so we can track it?

**Comment by caldwell2000** [comment]
I temporarily am using a lifecycle policy with ignore = all with success until the issue is resolved.
  lifecycle {  ignore_changes = all  }

**Comment by Aohzan** [comment]
> Is there a link to the Microsoft ticket so we can track it?

no sorry

**Comment by rafagsiqueira** [comment]
I can confirm the issue still happens on Azurerm 2.48.0.

**Comment by Aohzan** [comment]
Hello,

Azure fix the problem on their side, I can update the cluster from the web portal.

WIth Terraform (with provider in version 2.49.0), I still get an error :
```Error: updating Managed Kubernetes Cluster "cluster-name" (Resource Group "resource-group-name"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidIdentityValues" Message="Invalid value for the identities '/subscriptions/sub-id/resourceGroups/resource-group-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."```

**Comment by Ledermayer** [comment]
Hi Folks,

So I have a thread with msft on this very topic, and this is the latest they were coming back to me:

On TF create plan:

```
identity: [
    {
        "type": "UserAssigned",
        "user_assigned_identity_id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rgrp-tva2-do-akstest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umid-pva2-do-akstest001"
    }
],
```
However when you are updating existing cluster:

```
identity: [
    {
        "principal_id": "",
        "tenant_id": "",
        "type": "UserAssigned",
        "user_assigned_identity_id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rgrp-tva2-do-akstest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umid-pva2-do-akstest001"
    }
],
```
As you can see the principal_id and tenant_id is not populated by terraform , I do not know whether is this api or azurerm problem, tough folks at msft I was in contact with insisting this is a tf problem, as you do not populate those fields.

Also in the plan output is is "known after apply", so I feel that you guys try to populate it, just not going through ARM:

```
identity:{
          + principal_id              = (known after apply)
          + tenant_id                 = (known after apply)
          + type                      = "UserAssigned"
          + user_assigned_identity_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rgrp-tva2-do-akstest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umid-pva2-do-akstest001"
}
```

Not sure is that drives us closer to some resolution, I hope this will resolved soon.

Regards,
Leder

**Comment by Ledermayer** [comment]
@tombuildsstuff 

I was getting some more response from msft yesterday, here it is:

> Let me share an understanding about what we have gathered from the Product Team along with the code block that Terraform is using.
The error “InvalidIdentityValues” is returned by ARM, it happens when identity.userAssignedIdentities.<IDENTITY_RESOURCE_ID> is not an empty object when sending PUT managedCluster/ request. That’s to say, when PUT a managedCluster, expected identity property looks like:
    "identity": {
        "principalId": "",  // This property can be deleted, but having this will not lead to error.
        "tenantId": "", // This property can be deleted, but having this will not lead to error.
        "type": "UserAssigned",
        "userAssignedIdentities": {
            "/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/resourcegroups/tosi/providers/Microsoft.ManagedIdentity/userAssignedIdentities/control-plane-identity": {} // Note, the value MUST be an empty object
        }
},

> After the cluster is created, if you GET managedCluster/, and directly use the GET response as PUT managedCluster/ request body, its identity property looks like:

    "identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
            "/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/resourcegroups/tosi/providers/Microsoft.ManagedIdentity/userAssignedIdentities/control-plane-identity": {
                "clientId": "aad80805-a1a5-444e-9f99-22c37c0e4b78",
                "principalId": "399e3606-a3b3-4386-87eb-1430bf97f30c"
            }  // Note, the value is not an empty object, and PUT it will lead to error “InvalidIdentityValues”
        }
    },

> Product Team even tried to reproduce this error using POSTMAN by simply GET and PUT the cluster. 

> For terraform-provider-azurerm, it is using azure-sdk-for-go to GET managedCluster/ in updating resource operation: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.49.0/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L907 , in the response, identity.userAssignedIdentities.<IDENTITY_RESOURCE_ID> will be a non-empty object, containing the identity’s clientId and principalId, just similar as above example. And if identity property is not updated, when sending out the request, the serialized identity.userAssignedIdentities.<IDENTITY_RESOURCE_ID> will be a non-empty object, which will cause the error.

I hope you can find anything usefull in the above, so this problem can be fixed. We are eager to start using managed identity deployments, with userDefinedRoute and this is a major blocker to provide a stable solution.

Many Thanks,
Leder

**Comment by nniikkoollaaii** [comment]
Does somebody have a workaround?

A [previous comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10406#issuecomment-788774955) states an update is possible via the Azure Portal.

I can update the aks version in my .tf-files and ignore the change to the azurerm_kubernetes_cluster resource via lifecycle settings.
Then I can update the cluster via the portal.

How is terraform reacting if only the state file contains an older version?

**Comment by BartVanBerkel** [comment]
We have exactly the same issue as described here and opened a ticket with MSFT (ref. 2104080050000277)

After some testing the MSFT engineer discovered that the resourceId of the identity contains a uppercase `g` in `resourcegroups`.

**Working MI ID**: 
"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**g**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"

**Non-working MI ID**: 
"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**G**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"

So if I use the following configuration (see below) it will actually deploy and update. 

```
resource "azurerm_user_assigned_identity" "uai" {
  resource_group_name = "my_rg"
  location            = "westeurope"
  name                = "my_identity"
}

data "azurerm_subscription" "current" {}

resource "azurerm_kubernetes_cluster" "aks" {
  name                = "my_aks"
  location            = "westeurope"
  resource_group_name = "my_rg"

  identity {
    type                      = "UserAssigned"
    user_assigned_identity_id = "${data.azurerm_subscription.current.id}/resourcegroups/${azurerm_user_assigned_identity.uai.resource_group_name}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${azurerm_user_assigned_identity.uai.name}"
  }
```

In #10296 the resourceId has been changed to have the uppercase `G`.. Azure isn't really clear whether it should contain a `g` or `G`. Because if you look in the portal at the properties of the user assigned identity resource it will show you the resourceId with a `G`. But when you use powershell of az-cli to see the resourceId it will show you the lowercase `g`.

Please do note that I don't consider this as a good workaround.. But hopefully it shines a light on what is going wrong here.

**Comment by aging-dh** [comment]
> We have exactly the same issue as described here and opened a ticket with MSFT (ref. 2104080050000277)
> 
> After some testing the MSFT engineer discovered that the resourceId of the identity contains a uppercase `g` in `resourcegroups`.
> 
> **Working MI ID**:
> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**g**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"
> 
> **Non-working MI ID**:
> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**G**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"
> 
> So if I use the following configuration (see below) it will actually deploy and update.
> 
> ```terraform
> resource "azurerm_user_assigned_identity" "uai" {
>   resource_group_name = "my_rg"
>   location            = "westeurope"
>   name                = "my_identity"
> }
> 
> data "azurerm_subscription" "current" {}
> 
> resource "azurerm_kubernetes_cluster" "aks" {
>   name                = "my_aks"
>   location            = "westeurope"
>   resource_group_name = "my_rg"
> 
>   identity {
>     type                      = "UserAssigned"
>     user_assigned_identity_id = "${data.azurerm_subscription.current.id}/resourcegroups/${azurerm_user_assigned_identity.uai.resource_group_name}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${azurerm_user_assigned_identity.uai.name}"
>   }
> ```
> 
> In #10296 the resourceId has been changed to have the uppercase `G`.. Azure isn't really clear whether it should contain a `g` or `G`. Because if you look in the portal at the properties of the user assigned identity resource it will show you the resourceId with a `G`. But when you use powershell of az-cli to see the resourceId it will show you the lowercase `g`.
> 
> Please do note that I don't consider this as a good workaround.. But hopefully it shines a light on what is going wrong here.


Also, this worked for me without having to write out the whole id string.

```hcl
user_assigned_identity_id = replace(azurerm_user_assigned_identity.r_aksUserIdentity.id,"resourceGroups","resourcegroups")
```

**Comment by twendt** [comment]
I can confirm that the workaround works, but I end up in the same issue as with #11223 that it wants to do an update each time I run terrafrom apply asit  wants to change the user_assigned_identity_id from resourceGroups to resourcegroups.

**Comment by justin-chizer** [comment]
> > We have exactly the same issue as described here and opened a ticket with MSFT (ref. 2104080050000277)
> > After some testing the MSFT engineer discovered that the resourceId of the identity contains a uppercase `g` in `resourcegroups`.
> > **Working MI ID**:
> > "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**g**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"
> > **Non-working MI ID**:
> > "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**G**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"
> > So if I use the following configuration (see below) it will actually deploy and update.
> > ```terraform
> > resource "azurerm_user_assigned_identity" "uai" {
> >   resource_group_name = "my_rg"
> >   location            = "westeurope"
> >   name                = "my_identity"
> > }
> > 
> > data "azurerm_subscription" "current" {}
> > 
> > resource "azurerm_kubernetes_cluster" "aks" {
> >   name                = "my_aks"
> >   location            = "westeurope"
> >   resource_group_name = "my_rg"
> > 
> >   identity {
> >     type                      = "UserAssigned"
> >     user_assigned_identity_id = "${data.azurerm_subscription.current.id}/resourcegroups/${azurerm_user_assigned_identity.uai.resource_group_name}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${azurerm_user_assigned_identity.uai.name}"
> >   }
> > ```
> > 
> > 
> > In #10296 the resourceId has been changed to have the uppercase `G`.. Azure isn't really clear whether it should contain a `g` or `G`. Because if you look in the portal at the properties of the user assigned identity resource it will show you the resourceId with a `G`. But when you use powershell of az-cli to see the resourceId it will show you the lowercase `g`.
> > Please do note that I don't consider this as a good workaround.. But hopefully it shines a light on what is going wrong here.
> 
> Also, this worked for me without having to write out the whole id string.
> 
> ```terraform
> user_assigned_identity_id = replace(azurerm_user_assigned_identity.r_aksUserIdentity.id,"resourceGroups","resourcegroups")
> ```

This worked for me as well. Thank you @BartVanBerkel and @aging-dh Cheers!

**Comment by norshtein** [comment]
The workaround works because it triggers the update logic for `identity` property. If terraform thinks the `identity` property is updated, it will generate a correct `identity` body. Any letter case change can trigger this updating logic. Related code part: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.49.0/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L1120  
https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.49.0/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L1835

This can be a temporary workaround before the issue is fully fixed. 

Personally, I would like a fix in azure-sdk-for-go to permanently fix this. The reason for this issue is introduced in this comment:  https://github.com/terraform-providers/terraform-provider-azurerm/issues/10406#issuecomment-791930148 . In [AKS's swagger]( https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-03-01/managedClusters.json#L3349-L3368), we have defined `userAssignedIdentities.additionalProperties.properties.principalId` and `userAssignedIdentities.additionalProperties.properties.clientId` as readonly. In the [specification](https://swagger.io/specification/), readonly is defined as:
> Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. 

It should be SDK's responsibility to handle this part of work. It's quite common for developers to GET an object and then PUT it, it's not reasonable to let SDK user to manually handle this. For some language, such as python, the auto-generated SDK already has the ability to set readonly properties to none before sending the request, but that's not the case for go. I think some manual work need to be done in azure-sdk-for-go, the related issue: https://github.com/Azure/azure-sdk-for-go/issues/14478

**Comment by pedrohdz** [comment]
> > We have exactly the same issue as described here and opened a ticket with MSFT (ref. 2104080050000277)
> > After some testing the MSFT engineer discovered that the resourceId of the identity contains a uppercase `g` in `resourcegroups`.
> > **Working MI ID**:
> > "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**g**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"
> > **Non-working MI ID**:
> > "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/_resource**G**roups_/my_rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my_identity"
> > So if I use the following configuration (see below) it will actually deploy and update.
> > ```terraform
> > resource "azurerm_user_assigned_identity" "uai" {
> >   resource_group_name = "my_rg"
> >   location            = "westeurope"
> >   name                = "my_identity"
> > }
> > 
> > data "azurerm_subscription" "current" {}
> > 
> > resource "azurerm_kubernetes_cluster" "aks" {
> >   name                = "my_aks"
> >   location            = "westeurope"
> >   resource_group_name = "my_rg"
> > 
> >   identity {
> >     type                      = "UserAssigned"
> >     user_assigned_identity_id = "${data.azurerm_subscription.current.id}/resourcegroups/${azurerm_user_assigned_identity.uai.resource_group_name}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${azurerm_user_assigned_identity.uai.name}"
> >   }
> > ```
> > 
> > 
> > In #10296 the resourceId has been changed to have the uppercase `G`.. Azure isn't really clear whether it should contain a `g` or `G`. Because if you look in the portal at the properties of the user assigned identity resource it will show you the resourceId with a `G`. But when you use powershell of az-cli to see the resourceId it will show you the lowercase `g`.
> > Please do note that I don't consider this as a good workaround.. But hopefully it shines a light on what is going wrong here.
> 
> Also, this worked for me without having to write out the whole id string.
> 
> ```terraform
> user_assigned_identity_id = replace(azurerm_user_assigned_identity.r_aksUserIdentity.id,"resourceGroups","resourcegroups")
> ```

Sorry for the thumbs down!  I just wanted to flag that the work around is not working for me.  I'm still getting the original `The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property.` error.

```
$ terraform0.14 version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0
```
