### ISSUE TITLE
Support Key Vault secret from azurerm_api_management_named_value

### ISSUE THREAD

**Issue by alex-3sr** [terraform-providers/terraform-provider-azurerm#10416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi All,

Recently, now APIM Named Values support sensitive data directly from Key Vault, like we can have from other services as webapp, functionapp, ... It can be really useful to support it directly on azurerm_api_management_named_value

### New or Affected Resource(s)

* azurerm_api_management_named_value

### Potential Terraform Configuration

The code could like as purposed above, with just add **keyvault_enabled** as True/False boolean, and on **value** to use the uri Id of key vaul secrets reference. If keyvault_enabled is set to False, the value is set as string, else as Key Vault references.

```hcl
resource "azurerm_api_management_named_value" "apim_namedvalue_example1" {
  name                = "example-1"
  resource_group_name = azurerm_resource_group.rg.name
  api_management_name = azurerm_api_management.apim.name
  display_name        = "example-1"
  value               = azurerm_key_vault_secret.kvsecret_example1.id
  secret              = true
  keyvault_enabled    = true
}
```

### References
MS Article about this feature in APIM : 
* https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-properties

Rest API Refernce for create Named Value referencing a Key Vault Secret : 
* https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/namedvalue/createorupdate#apimanagementcreatenamedvaluewithkeyvault

Thanks, and have a nice day
Regards
Alexandre

**Comment by alex-3sr** [comment]
Hi,

When I wrote this feature request, I was able to finalize the Key Vault configuration with Named Values in GUI, and next plan didn't have any issue to detect this drift.
But recently, I got this error now : 
`Error:  making Read request for Property "xxxxxxxx" (Resource Group "xxxxxx" / API Management Service "xxxxxx"): apimanagement.NamedValueClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="Operation not allowed for keyVault derived NamedValue with id 'xxxxx'."`

I'm not sure why I got this error on new plan now, I didn't upgrade providers since last time IIRC but not 100% sure. I link new named values for a 2nd dedicated Key Vault, it's the main change that I did recently.

By the way, it could be very nice to have this feature ^^

Regards
Alexandre

**Comment by imiacat** [comment]
Where did you took this from? keyvault_enabled doesn't exists and as of "hashicorp" documentation, now there is no possibility to do this. Please provide more details as I really need this on my project these days.

Regards,
Catalin

**Comment by alex-3sr** [comment]
Hi @imiacat ,

Thank you for your response. I got this error when I just start a tf plan with refresh. The only workaround that I have is to disable refresh. In more, i've the same error if I use PowerShell ARM with a cmdlet like Get-AzApiManagementNamedValueSecretValue.

What do you need as more details ? I'm working in this project too, and the this tf project is almost broken, and very active. So i can give you further details and more debug logs if need, just let me know exactly what you need.

Regards
Alex

**Comment by imiacat** [comment]
Hi @alex-3sr, thank you for reply. 
I have a key vault where I created 4 secrets (with terraform) and need to add those 4 secrets as key vault values for 4 azurerm_api_management_named_value. Basically the manual steps from below picture, but with terraform
![Capture1](https://user-images.githubusercontent.com/78728636/113678490-585bc680-96c7-11eb-92cc-643477c1cb49.PNG)

**Comment by imiacat** [comment]
Also, since it is somehow related, do you have any idea on how to pass an "api_management_named_value" into an api_management_backend Authorization credential Header, as named value (auto-detected), not manual (manual step in below picture)? I've tried adding api_management_backend terraform confg:
credentials {
      header = {
        "x-functions-key" = "XXXX"
      }
but "headers" field doesn't automatically detects api_management_named_values, even written as variable. 
![Capture2](https://user-images.githubusercontent.com/78728636/113681255-6c54f780-96ca-11eb-834f-8b66a03ae925.PNG)

Thank you,
Catalin

**Comment by alex-3sr** [comment]
Hi,

So in fact I'm unablme to setup it with Terraform, cause there are not yet the available attribute with it. So, I juste created from terraform a faked value on Named Value, a Key Vault Secret with Terraform too and an Access Policy from APIM Identity.
Then from Azure portal GUI, I just finish manually the link from Named Value with Key Vault Secret.

When I did that 3 weeks ago, If I ran again terraform plan I didn't have any drift detection and no error. All was still working fine (except that I had an extra step manually on GUI). But I was able to update Key Vault secrets and APIM fetched it the new one. So it was acceptable.

And since recently I've now the mentionned error above, and now terraform plan was unable to continue to work silently without error on this named values. I noticed that all APIM got an update last week from Microsoft. Im' wondering if error is linked with recent system updates
![image](https://user-images.githubusercontent.com/38663389/113681495-4e839480-96c2-11eb-9639-a905a42d83a1.png)

**Comment by alex-3sr** [comment]
> Also, since it is somehow related, do you have any idea on how to pass an "api_management_named_value" into an api_management_backend Authorization credential Header, as named value (auto-detected), not manual (manual step in below picture)? I've tried adding api_management_backend terraform confg:
> credentials {
> header = {
> "x-functions-key" = "XXXX"
> }
> but "headers" field doesn't automatically detects api_management_named_values, even written as variable.
> ![Capture2](https://user-images.githubusercontent.com/78728636/113681255-6c54f780-96ca-11eb-834f-8b66a03ae925.PNG)
> 
> Thank you,
> Catalin

We stop using APIM Backend, cause we had some issue when using GIT synchronization between APIM environnements, so I've no experience for help you about this topic, sorry

**Comment by OmnipotentOwl** [comment]
Perhaps for the implementation support for both the id value and the versionless_id value would be possible to allow control over the refresh functionality to be handled by the end-user.
> Key vault secret identifier for fetching secret. Providing a versioned secret will prevent auto-refresh. This requires Api Management service to be configured with aka.ms/apimmsi

Example:
``` terraform
resource "azurerm_api_management_named_value" "apim_namedvalue_example1" {
  name                = "example-1"
  resource_group_name = azurerm_resource_group.rg.name
  api_management_name = azurerm_api_management.apim.name
  display_name        = "example-1"
  value               = azurerm_key_vault_secret.kvsecret_example1.versionless_id
  secret              = true
  keyvault_enabled    = true
}
```

**Comment by akorobanov** [comment]
Hi!
Any updates on when this feature will be added?

**Comment by alex-3sr** [comment]
> Hi!
> Any updates on when this feature will be added?

Hi,

I think that will be in short time, the PR seem to be ok -> https://github.com/terraform-providers/terraform-provider-azurerm/pull/12309
