### ISSUE TITLE
azurerm_sql_database: add support of vcore and data_max_size

### ISSUE THREAD

**Issue by ncsiki** [terraform-providers/terraform-provider-azurerm#10432]
Please add support for the vCore and Data Max Size to Azure SQL.

resource "azurerm_sql_database" "test" {
  name                = "mysqldatabase"
  resource_group_name = "best_rg_ever"
  location = "West US"
  server_name = "mysqlserver1"
  vcore = 2
  data_max_size = 32
}

Thanks for your help!

**Comment by tombuildsstuff** [comment]
hi @ncsiki 

Support for [vCores can be found in the `azurerm_mssql_database`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database) resource - the older `azurerm_sql_*` resources which use the older SKU billing model are still valid in some cases - however the `azurerm_mssql_*` resources are substantially different enough that these have been split out to capture the different use-cases.

Thanks!
