### ISSUE TITLE
Support for Signal R Upstream Settings

### ISSUE THREAD

**Issue by schlbra** [terraform-providers/terraform-provider-azurerm#10436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Upstream allows Azure SignalR Service to send messages and connection events to a set of endpoints in serverless mode. You can use upstream to invoke a hub method from clients in serverless mode and let endpoints get notified when client connections are connected or disconnected.

This is currently available via ARM but not terraform.

### New or Affected Resource(s)

* azurerm_signalr_service_upstream

### Potential Terraform Configuration

```hcl
resource "azurerm_signalr_service_upstream" "example" {
  azurerm_signalr_service_id = azurerm_signalr_service.example.id
  url_template               = "http://host.com/{hub}/api/{category}/{event}"
  event_pattern              = "*"
  hub_pattern                = "*"
  category_pattern           = "*"
  auth_type                  = "managed_identity"
}
```

### References
[ARM Template](https://docs.microsoft.com/en-us/azure/azure-signalr/concept-upstream)

**Comment by brunhil** [comment]
This requires an upgrade in the client SDK - https://github.com/Azure/azure-sdk-for-go/tree/master/services/signalr/mgmt/2020-05-01. I'll take a look at this one!

**Comment by brunhil** [comment]
Due to the way this is defined in Azure I am going down the following resource definition,



```
resource "azurerm_signalr_service" "test" {
  name                = "test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    name     = "Free_F1"
    capacity = 1
  }

  features {
    flag  = "ServiceMode"
    value = "Serverless"
  }

  upstream_setting {
    url_template = "http://foo.com"
  }

  upstream_setting {
    category_pattern = "connections,messages"
    event_pattern    = "*"
    hub_pattern      = "hub1"
    url_template     = "http://foo.com"
  }

  upstream_setting {
    category_pattern = "*"
    event_pattern    = "connect,disconnect"
    hub_pattern      = "hub1,hub2"
    url_template     = "http://foo3.com"
  }

  upstream_setting {
    category_pattern = "connections"
    event_pattern    = "disconnect"
    hub_pattern      = "*"
    url_template     = "http://foo4.com"
  }
}
```

**Comment by schlbra** [comment]
Thoughts on `auth_type` ?

**Comment by brunhil** [comment]
> Thoughts on `auth_type` ?

Did not see this in the version I used to upgrade. It's in a newer preview version. I'll see if it's a decent amount of rework to adopt the new version
