### ISSUE TITLE
inline key_vault_access_policy requires optional application_id and certificate_permissions for tf.json HCL

### ISSUE THREAD

**Issue by ilons** [terraform-providers/terraform-provider-azurerm#10445]
Trying to run the official example Azure Key Vault (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault), I encounter an issue where terraform would say that `application_id` and `certificate_permissions` are required for `access_policy` objects. 
Looking at the documentation, neither of them should be required.

Since I run terraform against the JSON HCL, I then tried to run against the regular TF HCL, which worked.

I'm not sure if this is a bug in the azurerm provider or in terraform core, but I'll file it here, as I suspect it is the right place.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.45.1

### Affected Resource(s)
* azurerm_key_vault

### Terraform Configuration Files
JSON:
```json
{
  "provider": {
    "azurerm": {
      "features": {
        "key_vault": {
          "purge_soft_delete_on_destroy": true
        }
      }
    }
  },
  "data": {
    "azurerm_client_config": {
      "current": {}
    }
  },
  "resource": {
    "azurerm_resource_group": {
      "example": {
        "name": "example-resources",
        "location": "West Europe"
      }
    },
    "azurerm_key_vault": {
      "example": {
        "name": "examplekeyvault",
        "location": "${azurerm_resource_group.example.location}",
        "resource_group_name": "${azurerm_resource_group.example.name}",
        "enabled_for_disk_encryption": true,
        "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
        "soft_delete_retention_days": 7,
        "purge_protection_enabled": false,
        "sku_name": "standard",
        "access_policy": [
          {
            "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
            "object_id": "${data.azurerm_client_config.current.object_id}",
            "key_permissions": [
              "get"
            ],
            "secret_permissions": [
              "get"
            ],
            "storage_permissions": [
              "get"
            ]
          }
        ]
      }
    }
  }
}

```
TF:
```hcl
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_key_vault" "example" {
  name                        = "examplekeyvault"
  location                    = azurerm_resource_group.example.location
  resource_group_name         = azurerm_resource_group.example.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get",
    ]

    storage_permissions = [
      "get",
    ]
  }
}
```

### Debug Output

Output for `terraform plan`, using;
JSON: https://gist.github.com/ilons/b4d89ac3d78c84d8e109f399e97e0703
TF: https://gist.github.com/ilons/e7c3bff72073764c8718fed1dcaaa7c6

### Expected Behaviour
A plan to create the key vault are generated

### Actual Behaviour
An error (`Incorrect attribute value type`) are shown, complaining that `application_id` and `certificate_permissions` are required for the `access_policy` object.

### Steps to Reproduce
0. Insert the JSON config in a file named test.tf.json
1. `terraform init`
2. `terraform apply`

### References
* Resource documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault
* JSON HCL documentation: https://www.terraform.io/docs/language/syntax/json.html

**Comment by ilons** [comment]
And just to confirm that the syntax in the JSON HCL are correct, I tried adding the access policy separately instead of inline, which worked as expected:
```json
{
  "provider": {
    "azurerm": {
      "features": {
        "key_vault": {
          "purge_soft_delete_on_destroy": true
        }
      }
    }
  },
  "data": {
    "azurerm_client_config": {
      "current": {}
    }
  },
  "resource": {
    "azurerm_resource_group": {
      "example": {
        "name": "example-resources",
        "location": "West Europe"
      }
    },
    "azurerm_key_vault": {
      "example": {
        "name": "examplekeyvault",
        "location": "${azurerm_resource_group.example.location}",
        "resource_group_name": "${azurerm_resource_group.example.name}",
        "enabled_for_disk_encryption": true,
        "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
        "soft_delete_retention_days": 7,
        "purge_protection_enabled": false,
        "sku_name": "standard"
      }
    },
    "azurerm_key_vault_access_policy": {
      "example": {
        "key_vault_id": "${azurerm_key_vault.example.id}",
        "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
        "object_id": "${data.azurerm_client_config.current.object_id}",
        "key_permissions": [
          "get"
        ],
        "secret_permissions": [
          "get"
        ],
        "storage_permissions": [
          "get"
        ]
      }
    }
  }
}

```

**Comment by tombuildsstuff** [comment]
hi @ilons 

Thanks for opening this issue,.

Taking a look through here unfortunately this is more of a Core issue than a Provider issue specifically, whilst the HCL and JSON schemas are compatible in HCL2, there do appear to be some issues between the two when nested items are involved (as is the case here) - as such would you mind [reopening this issue on the Terraform Core repository](https://github.com/hashicorp/terraform) so that someone from that team can take a look?

Thanks!

**Comment by ilons** [comment]
> hi @ilons
> 
> Thanks for opening this issue,.
> 
> Taking a look through here unfortunately this is more of a Core issue than a Provider issue specifically, whilst the HCL and JSON schemas are compatible in HCL2, there do appear to be some issues between the two when nested items are involved (as is the case here) - as such would you mind [reopening this issue on the Terraform Core repository](https://github.com/hashicorp/terraform) so that someone from that team can take a look?
> 
> Thanks!

Hi Tom,

I'll reopen the issue upstream, and hopefully it could be sorted.

Thanks for the prompt reply!
