### ISSUE TITLE
Azure/Terraform: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token

### ISSUE THREAD

**Issue by pbhullar06** [terraform-providers/terraform-provider-azurerm#10465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform- 0.14.0
AzureRM- 2.4.0

### Affected Resource(s)

* Unable to Read/Write any resources or data sources

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version                     = "~> 2.4.0"
  skip_credentials_validation = "true"
  features {}
  use_msi                     = var.use_msi
  subscription_id             = var.subscription_id
  tenant_id                   = var.tenant_id
}

# verify if pipeline can access resource groups in Azure account
data "azurerm_resource_group" "example" {
  name = "<name-of-the-resource-group>"
}

output "id" {
  value = data.azurerm_resource_group.example.id
}
```

### Debug Output

```hcl
Error: Error checking for presence of existing resource group: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscription_id>/resourcegroups/<name-of-the-resource-group>?api-version=2020-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
```

### Expected Behaviour

IT SHOULD HAVE READ RESOURCE AND GIVEN RESOURCE ID AS AN OUTPUT

### Actual Behaviour

- We do az login using managed user identity
- `terraform init` and `terraform plan` works fine
- env vars `use_msi`, `subscription_id` and `tenant_id` are provided in terraform commands with `-var` flag
- Fails at `terraform apply`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

PLEASE NOTE THAT THIS TERRAFORM CONFIG WAS WORKING FOR US A WEEK AGO UNTIL IT SUDDENLY STOPPED AND STARTED THROWING THIS ERROR:
```
Error: Error checking for presence of existing resource group: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscription_id>/resourcegroups/<name-of-the-resource-group>?api-version=2020-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @pbhullar06 

Taking a look at the error coming back from the Azure API here:

>  {"error":"invalid_request","error_description":"Identity not found"}

It looks like the Managed/User Assigned Identity being either isn't assigned, or has been deleted, or (presumably) doesn't exist in the Tenant ID being used - so I'd suggest looking into that. Since this is a configuration question rather than a bug in the Azure Provider, I'm going to close this issue for the moment - but you should be able to get further assistance with configuration issues in [the community Discuss forum](https://discuss.hashicorp.com).

Thanks!
