### ISSUE TITLE
Execute AZ CLI commands using local-exec provisioner

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1046]
Have a Terraform config that creates a Network Security Group with Rules.  Since there is currently no ability natively with Terraform to assign the new NSG to an existing NIC or Subnet, I have been trying to use the local-exec provisioner to run an az cli command that assigns the NSG to an existing subnet.  I have tried several derivatives of the command format but none work and all seem to be ignored.  The Terraform config is being executed from within Azure Cloud Shell.

### Terraform Version
Terraform v0.11.5
+ provider.azurerm v1.2.0
+ provider.external v1.0.0

### Affected Resource(s)
-azurerm_network_security_group
-azurerm_subnet

### Terraform Configuration Files
I have tried multiple derivations of the provisioner block and have included each of them below, only show the NSG resource in the first one:

```hcl
resource "azurerm_network_security_group" "asensg" {
  name                = "${var.ilbase_nsg1_name}"
  location            = "${data.terraform_remote_state.rg.rglocation}"
  resource_group_name = "${data.terraform_remote_state.rg.rgname}"

  security_rule {
    name                       = "Inbound-Management"
    description                = "Used to manage ASE from public VIP"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "454-455"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
    access                     = "Allow"
    priority                   = 100
    direction                  = "Inbound"
  }
  provisioner "local-exec" {
     command = <<EOT
       az network vnet subnet update
       --resource-group ${data.terraform_remote_state.rg.rgname}
       --vnet-name ${data.terraform_remote_state.rg.vnetname}
       --name ${data.terraform_remote_state.rg.sn1name}
       --network-security-group ${azurerm_network_security_group.asensg.name}
  EOT
  }
```
```hcl
  provisioner "local-exec" {
    command = "az network vnet subnet update --resource-group ${data.terraform_remote_state.rg.rgname} --vnet-name ${data.terraform_remote_state.rg.vnetname} --name ${data.terraform_remote_state.rg.sn1name} --network-security-group ${azurerm_network_security_group.asensg.name}"
  }
```

```hcl
  provisioner "local-exec" {
    command = "az network vnet subnet update"
    interpreter = ["az", "--resource-group ${data.terraform_remote_state.rg.rgname}", "--vnet-name ${data.terraform_remote_state.rg.vnetname}", "--name ${data.terraform_remote_state.rg.sn1name}", "--network-security-group ${azurerm_network_security_group.asensg.name}"]
  }
```
```hcl
  provisioner "local-exec" {
    command = "network vnet subnet update"
    interpreter = ["az", "--resource-group ${data.terraform_remote_state.rg.rgname}", "--vnet-name ${data.terraform_remote_state.rg.vnetname}", "--name ${data.terraform_remote_state.rg.sn1name}", "--network-security-group ${azurerm_network_security_group.asensg.name}"]
  }
```
### Expected Behavior
The expected behavior from the provisioner running as expected is that the NSG should be applied to the subnet

### Actual Behavior
Nothing, the provisioner is being ignored.  No error is generated and no output is observed

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Terraform is being run from a Bash Azure Cloud Shell

**Comment by tombuildsstuff** [comment]
hey @Phydeauxman 

Thanks for opening this issue :)

> Since there is currently no ability natively with Terraform to assign the new NSG to an existing NIC or Subnet

It's possible to configure the Network Security Group for both [a `azurerm_network_interface`](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#network_security_group_id) and [`azurerm_subnet`](https://www.terraform.io/docs/providers/azurerm/r/subnet.html#network_security_group_id) using the `network_security_group_id` field; as such I don't believe you'll need to shell out to the Azure CLI to achieve this.

Looking at your code samples - this sample should work in-line within any regular resource like so:

```
resource "foo" "bar" {
  provisioner "local-exec" {
    command = "az network vnet subnet update --resource-group ${data.terraform_remote_state.rg.rgname} --vnet-name ${data.terraform_remote_state.rg.vnetname} --name ${data.terraform_remote_state.rg.sn1name} --network-security-group ${azurerm_network_security_group.asensg.name}"
  }
}
```

However the Provisioner will only be run when the resource has a change applied; as such you may wish to run this separately via the `null_resource`:

e.g.

```
resource "null_resource" "test" {
  provisioner "local-exec" {
    command = "az network vnet subnet update --resource-group ${data.terraform_remote_state.rg.rgname} --vnet-name ${data.terraform_remote_state.rg.vnetname} --name ${data.terraform_remote_state.rg.sn1name} --network-security-group ${azurerm_network_security_group.asensg.name}"
  }
}
```

That said - we'd highly recommend using the native fields where possible, since otherwise Terraform won't detect changes. The following code sample should achieve what you're after:

```
resource "azurerm_network_security_group" "test" {
  # ..
}

resource "azurerm_network_interface" "test" {
  # ..
  network_security_group_id = "${azurerm_network_security_group.test.id}"
  # ..
}

resource "azurerm_subnet" "test" {
  # ..
  network_security_group_id = "${azurerm_network_security_group.test.id}"
  # ..
}
```

Regarding assigning these to existing resources; you can import these into Terraform using the `terraform import` command, [there's more information about that here](https://www.terraform.io/docs/import/index.html). Would you be able to take a look and see if that works for you?

Thanks!

**Comment by Phydeauxman** [comment]
Thanks for the info.  I did get it to work using the null_resource.  The reason we can't use the native commands is because our vnet and subnets were made via a separate deployment...so I would have to go modify that deployment and re-run it.  Not really the way we want to do it.  The nsg is only for the ASE so we wanted to include it in the deployment of the ASE for manageability reasons.  What would be nice would be to have the ability to apply an nsg to a nic or subnet at the time of creating the nsg.
