### ISSUE TITLE
waf_configuration documentation for azurerm_application_gateway is wrong

### ISSUE THREAD

**Issue by iljoong** [terraform-providers/terraform-provider-azurerm#1047]
**Document:**
The `waf_configuration` block supports:
`name` - (Required) User defined name for a web application firewall.
https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#waf_configuration

**Code:**
```
  waf_configuration {
    name             = "test"
    firewall_mode    = "Detection" // "Prevention"
    rule_set_type    = "OWASP"
    rule_set_version = "3.0" 
  }
```
**Output:**
```
Error: azurerm_application_gateway.appgw: "waf_configuration.0.enabled": required field is not set
Error: azurerm_application_gateway.appgw: waf_configuration.0: invalid or unknown key: name
```

`name` is not a valid field but `enabled` is a required field for `waf_configuration`

**Fixed code:**
```
  waf_configuration {
    firewall_mode    = "Detection" // "Prevention"
    rule_set_type    = "OWASP"
    rule_set_version = "3.0"
    enabled          = true
  }
```
this works!

**Comment by tombuildsstuff** [comment]
hey @iljoong 

Thanks for opening this issue! I've opened #1048 which will fix this - we'll get this merged / published later today :)

Thanks!
