### ISSUE TITLE
regression jsonencode behaviour in 0.14.5 different then in 0.13.5

### ISSUE THREAD

**Issue by alexeyauslender** [terraform-providers/terraform-provider-azurerm#10484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.5

### Affected Resource(s)
jsonencode function

### Expected Behaviour
In terraform 0.13.5
 jsonencode({"hello"="world"})
{"hello":"world"}

### Actual Behaviour

jsonencode({"hello"="world"})
"{\\"hello\\":\\"world\\"}"

### Steps to Reproduce

jsonencode({"hello"="world"})

**Comment by alexeyauslender** [comment]
Looks like regression, the returned object is just a string and not a valid JSON.

**Comment by tombuildsstuff** [comment]
hi @alexeyauslender 

Thanks for opening this issue.

The `jsonencode` function is a part of Terraform Core, whereas this repository is for the Azure Provider - as such would you mind [reopening this issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues), where someone from the Core team should be able to take a look?

Thanks!

**Comment by alexeyauslender** [comment]
Sorry for that, moving this into terraform core.
