### ISSUE TITLE
Issues with existing script

### ISSUE THREAD

**Issue by tdsan** [terraform-providers/terraform-provider-azurerm#10515]
Identified 5 items you need to get this process to work

Assumption - resource_group = RG

1. Log analytics workspace

resource "random_id" "log_analytics_workspace_name_suffix" {
    byte_length = 8
}

2. Log analytics workspace name
variable "log_analytics_workspace_name" {
	type	= string
	description	= "Enter workspace name"
	default = "<name of workspace>"
}

3. Log analytics workspace
resource "azurerm_log_analytics_workspace" "test" {
    name = "${var.log_analytics_workspace_name}-${random_id.log_analytics_workspace_name_suffix.dec}"
    location            = azurerm_resource_group.RG.location
    resource_group_name = azurerm_resource_group.RG.name
    sku                 = "Free"
}

4. Log analytics solution
resource "azurerm_log_analytics_solution" "test" {
    solution_name         = "ContainerInsights"
    location              = azurerm_log_analytics_workspace.test.location
    resource_group_name   = azurerm_resource_group.RG.name
    workspace_resource_id = azurerm_log_analytics_workspace.test.id
    workspace_name        = azurerm_log_analytics_workspace.test.name

    plan {
        publisher = "Microsoft"
        product   = "OMSGallery/ContainerInsights"
    }
}

5. From a test standpoint, disable oms_agent (enabled = false).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @tdsan 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
