### ISSUE TITLE
Firewall Policy Rule Collection Rule does not accept "*" for destination port

### ISSUE THREAD

**Issue by p1johnson** [terraform-providers/terraform-provider-azurerm#10524]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
provider registry.terraform.io/hashicorp/azurerm v2.42.0

### Affected Resource(s)

* azurerm_firewall_policy_rule_collection_group

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_policy_rule_collection_group" "sample" {
  name               = "sample-rule-collection"
  firewall_policy_id = azurerm_firewall_policy.local_policy.id
  priority           = 2000

  network_rule_collection {
    name     = "example"
    priority = 2010
    action   = "Allow"
    rule {
      name                  = "out"
      protocols             = ["Any"]
      source_addresses      = ["10.0.0.0/8]
      destination_addresses = ["172.16.0.0/16"]
      destination_ports     = ["*"]
    }
  }
}

```

### Expected Behaviour

Create rule in rule collection with * set for destination port

### Actual Behaviour

Error invalid format of "network_rule_collection.0.rule.0.destination_ports.0"

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @p1johnson 

Thanks for opening this issue.

On the backend Azure ends up translating `*` to `1-65535`, so this should be possible by setting this field to `1-65535` - as such I'm going to close this out for the moment but if you have further usage questions I'd direct you to [the community discuss forum](https://discuss.hashicorp.com))

Thanks!
