### ISSUE TITLE
[AKS][Documentation] Change the k8s version to 1.8.7 in the sample on page https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

### ISSUE THREAD

**Issue by evandropaula** [terraform-providers/terraform-provider-azurerm#1053]
Please change the k8s version to 1.8.7 in the sample on page:
- https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html
- https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/kubernetes_cluster.html.markdown

Priority = Low
Terraform Version = 0.11.5
Affected Resource = azurerm_kubernetes_cluster

**Comment by tombuildsstuff** [comment]
hey @evandropaula 

Thanks for opening this issue :)

Given the rapid release cycle of Kubernetes - and that the "Example Usages" within the Terraform documentation are meant to be references/starting-points - I believe we'll end up playing a cat-and-mouse game here trying to keep this version number up to date.

As this resource will deploy the latest version of Kubernetes if the `kubernetes_version` attribute isn't specified - I think it might be worth removing the `kubernetes_version` attribute from the Example Usage and documenting this - I'll push a PR for this.

Thanks!
