### ISSUE TITLE
Cannot delete subnet with service delegation?

### ISSUE THREAD

**Issue by tomconte** [terraform-providers/terraform-provider-azurerm#10546]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.36.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/tls v3.0.0

### Affected Resource(s)

`azurerm_subnet`

### Terraform Configuration Files

I have created a subnet with a service delegation:

```hcl
resource "azurerm_subnet" "pgfs_subnet" {
  name                 = var.pgfs_subnet_name
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.2.0/24"]

  enforce_private_link_endpoint_network_policies = true

  delegation {
    name = "Microsoft.DBforPostgreSQL.flexibleServers"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
    }
  }
}
```

### Expected Behaviour

When destroying the deployment, I was expecting the provider to first remove the service association, and then delete the subnet. 

### Actual Behaviour

In practice it seems the provider does not remove the service association on destroy? Then deleting the subnet fails:

> Error: Error deleting Subnet "snet-pgfs" (Virtual Network "vnet-amdocs" / Resource Group "rg-amdocsqdjr"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet snet-pgfs is in use by /subscriptions/252281c3-8a06-4af8-8f3f-d6af13e4fde3/resourceGroups/rg-amdocsqdjr/providers/Microsoft.Network/virtualNetworks/vnet-amdocs/subnets/snet-pgfs/serviceAssociationLinks/snet-pgfs-service-association-link and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by phatcher** [comment]
@tomconte Just a thought, I think the delegation mentioned here are the _possibility_ of delegation - the actual delegation is created by the association of a resource to the subnet, just going from my experiences with subnets and app services.

So. you would have to remove the subnet association against your database first and then delete the subnet, since this resource doesn't control the db -> subnet resource.

**Comment by tomconte** [comment]
Thanks @phatcher, I have checked that during destruction, the delegated service has indeed been destroyed:

```
module.flexible_server.azurerm_resource_group_template_deployment.flexible_server_deployment: Destruction complete after 1m3s
```

This happens a while before the subnet deletion attempt... And I checked the database resource has disappeared from the resource group.

In my case said service was deployed using an ARM template via azurerm_resource_group_template_deployment, not sure if this could cause the issue...

**Comment by tomconte** [comment]
After some more testing I think this is some kind of race condition indeed, where the database server still has some resources attached to the subnet, even though it has been deleted. Thanks again @phatcher for your insights!
