### ISSUE TITLE
Support for connect the Keyvault to private AKS existing Vnet

### ISSUE THREAD

**Issue by Navbar** [terraform-providers/terraform-provider-azurerm#10544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to implement a higher feature like CSI - AKS and KV must have net connectivity.
I would like to have the ability to add the following steps to the Keyvault resource group using Terraform code and not via the Azure Portal :
1. Set the Private endpoint and selected network radio button check
2. Add virtual existing network with all its details

### New or Affected Resource(s)
Keyvault, AKS
* azurerm_key_vault

### Potential Terraform Configuration

TF 14, Azure cloud, Keyvault alongside private AKS – I need to connect the AKS VNET to the Keyvault

This is the KV source code:
![image](https://user-images.githubusercontent.com/25344898/107617096-f13a0c80-6c57-11eb-9821-9f74fa260afe.png)

And I wish to add the following steps to the Keyvault resource group Terraform code and not via the Azure Portal :
1.	Set the Private endpoint and selected network radio button check
2.	Add virtual existing network with all its details

![image](https://user-images.githubusercontent.com/25344898/107617122-fa2ade00-6c57-11eb-92c0-c751159e3559.png)

**Comment by tombuildsstuff** [comment]
hi @Navbar 

Support for this can be found in [the `virtual_network_subnet_ids` field within the `network_acls` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#virtual_network_subnet_ids) which allows you to do this. This forum is intended to be used for Bugs and Feature Requests with the Azure Provider - since this is a usage question I'm going to close this for the moment - but should you have further usage questions I'd direct you towards [the community Discuss forum](https://discuss.hashicorp.com)

Thanks!

**Comment by Navbar** [comment]
That was a quick closer.. I opened this ticket after Hashicorp support team instructed me.
zendesk issue: https://support.hashicorp.com/hc/en-us/signin?return_to=https%3A%2F%2Fsupport.hashicorp.com%2Fhc%2Fen-us%2Frequests%2F41593

I tried the virtual_network_subnet_ids within the network_acls block - however it doesnt 
* turn on the Private endpoint and selected network radio button 
* and it doesnt have the ability to specify all those files as in the UI: subnet,rg,subscription
