### ISSUE TITLE
Unable to perform azurerm_role_assignment for 'providers/Microsoft.Billing/enrollmentAccounts'

### ISSUE THREAD

**Issue by cktwo** [terraform-providers/terraform-provider-azurerm#10547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.5

-  provider registry.terraform.io/hashicorp/azurerm v2.46.1
- provider registry.terraform.io/hashicorp/azuread v1.3.0
- provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

* `azurerm_role_assignment` - scope

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "billingOwner" {
  principal_id                = azuread_group.subscriptionCreator.object_id
  scope                         = "/providers/Microsoft.Billing/enrollmentAccounts/<HIDDEN_ID>"
  role_definition_name = "Owner"
}
```

### Expected Behaviour

Role assignement will be created for the service principal and it won't be blocked by the new filter rule introduced in version 2.46.0 #10438.

### Actual Behaviour

Role assignement for "/providers/Microsoft.Billing/enrollmentAccounts" is not working/beeing filtered:

```
Error: Can not parse "scope" as a management group id: Unable to parse Management Group ID "/providers/Microsoft.Billing/enrollmentAccounts/<HIDDEN_ID>"

  on spi_create_subscription.tf line 79, in resource "azurerm_role_assignment" "billingOwner":
  79: resource "azurerm_role_assignment" "billingOwner" {
```

### Steps to Reproduce

1. `terraform plan`

**Comment by cktwo** [comment]
Hi @jackofallops 
first of all, thanks for the quick response.
Exaclty, prior to the addition of a validation the creation was working flawlessly.
While setting an older version (up to 2.45.1), the code is working fine.
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.45.1"
    }
    ...
}
```

**Comment by jackofallops** [comment]
Thanks @cktwo - It wasn't intentionally supported, so we need to be mindful about re-introducing it,  but we're going to take a look at it.

**Comment by cktwo** [comment]
In case anybody has the same problem, but wants to use the current provider version:

We were looking into how to do this role assignement (with the REST api) using the official [Microsoft documentation](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/grant-access-to-create-subscription?tabs=rest%2Crest-2).
But since the documentation does not mention how to get all necessary parameters, here is what we did:

```bash
SPI_NAME="<SPI_DISPLAY_NAME_FOR_ROLE_ASSIGNEMENT>"
ENROLLMENT_ACCOUNT_NAME=$(az billing enrollment-account list | jq '.[0]' | jq '.name' --raw-output)
ENROLLMENT_ACCOUNT_SCOPE=$(az billing enrollment-account list | jq '.[0]' | jq '.id' --raw-output)
UUID=$(cat /proc/sys/kernel/random/uuid)
ROLE_DEFINITION_ID=$(az rest --method get --url https://management.azure.com/providers/Microsoft.Billing/enrollmentAccounts/$ENROLLMENT_ACCOUNT_NAME/providers/Microsoft.Authorization/roleDefinitions?api-version=2018-01-01-preview --url-parameter \$filter="roleName eq 'Owner'" | jq '.value' | jq '.[0]' | jq '.id' --raw-output)
SPI_OBJECT_ID=$(az ad sp list --filter "displayname eq '${SPI_NAME}'" --query "[].[objectId]" -o tsv)
ALREADY_ASSIGNED=$(az rest --method get --url https://management.azure.com/providers/Microsoft.Billing/enrollmentAccounts/$ENROLLMENT_ACCOUNT_NAME/providers/Microsoft.Authorization/roleAssignments?api-version=2020-04-01-preview --url-parameter \$filter="principalId eq '${SPI_OBJECT_ID}'" | jq '[.value]'| jq '.[0]'| jq '.[].name')

if [[ -z $ALREADY_ASSIGNED ]];then
  echo "Add service principal $SPI_NAME to role assignement scope $ENROLLMENT_ACCOUNT_SCOPE"
  az rest --method put --url https://management.azure.com/providers/Microsoft.Billing/enrollmentAccounts/$ENROLLMENT_ACCOUNT_NAME/providers/Microsoft.Authorization/roleAssignments/$UUID?api-version=2020-04-01-preview --body "{\"properties\": {\"roleDefinitionId\": \"$ROLE_DEFINITION_ID\", \"principalId\": \"$SPI_OBJECT_ID\"}}"
else
  echo "Service principal $SPI_NAME already assigned to role scope $ENROLLMENT_ACCOUNT_SCOPE"
fi
```

It would still be nice if there was a way to perform this role assignement via terraform.
