### ISSUE TITLE
Support for capacityReservationLevel in azurerm_log_analytics_workspace

### ISSUE THREAD

**Issue by NillsF** [terraform-providers/terraform-provider-azurerm#10553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Azure Log Analytics Workspaces have an option for capacityReservationLevel. 

This option is not surfaced in AzureRM Terraform module

### New or Affected Resource(s)

* azurerm_log_analytics_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "CapacityReservation"
  capacityReservationLevel = 100
  retention_in_days   = 30
}
```

### References

Supported in Azure ARM template: https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/2020-03-01-preview/workspaces 
* #0000

**Comment by brunhil** [comment]
I'll take a look at this one! should be able to expose it with the current API version

**Comment by brunhil** [comment]
I'll take a look at this!
