### ISSUE TITLE
Support for CosmosDB Continuous Backup Mode

### ISSUE THREAD

**Issue by chriszacny** [terraform-providers/terraform-provider-azurerm#10557]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to create a CosmosDB instance using continuous backup mode per: https://docs.microsoft.com/en-us/azure/cosmos-db/continuous-backup-restore-introduction

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl

resource "azurerm_cosmosdb_account" "db" {
  # Options for backup_restore_type would be {"periodic" (default) | "continuous"} 
  backup_restore_type = "continuous"

}
```

### References

* https://docs.microsoft.com/en-us/azure/cosmos-db/continuous-backup-restore-introduction
* https://docs.microsoft.com/en-us/azure/cosmos-db/online-backup-and-restore

**Comment by brunhil** [comment]
This will require an upgrade to the Cosomos API to version 2020-06-01-preview, I'll take a peek to see if this can be an in place upgrade or if there'd be breaking changes.
