### ISSUE TITLE
Error if patterns_to_match is empty in routing_rule in azurerm_frontdoor resource

### ISSUE THREAD

**Issue by varnav** [terraform-providers/terraform-provider-azurerm#10574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.14.6
* provider registry.terraform.io/hashicorp/azurerm v2.47.0

### Affected Resource(s)

* azurerm_frontdoor

### Terraform Configuration Files

Piece of relevant code:

```hcl
resource "azurerm_frontdoor" "main" {
  name                                         = "test"
  resource_group_name                          = "test"

  routing_rule {
    name               = "http2httpsrr"
    accepted_protocols = ["Http"]
    patterns_to_match  = [""]
    frontend_endpoints = ["defaultfee"]
    redirect_configuration {
      redirect_protocol = "HttpsOnly"
      redirect_type     = "Moved"
    }
  }
  }
```

### Expected Behaviour

Error saying value cannot be empty

### Actual Behaviour

Error: rpc error: code = Unavailable desc = transport is closing

**Comment by tombuildsstuff** [comment]
Fixed via #10580
