### ISSUE TITLE
Adding a Priority Argument in VMSS, with value = default value, causes VMSS to be recreated.

### ISSUE THREAD

**Issue by CarelvanHeerden** [terraform-providers/terraform-provider-azurerm#10594]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform v0.14.3`
* `hashicorp/azurerm v2.47.0`

### Affected Resource(s)

* `azurerm_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_scale_set" "123123123" {
  name                = "${lookup(var.prefix, terraform.workspace)}123123123"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  upgrade_policy_mode = "Rolling"
  overprovision       = false
  priority            = terraform.workspace == "PROD" ? "Regular" : "Low"

/*removed the rest of the VMSS config*/

}
```

### Expected Behaviour

When adding an argument, that has the same value as the argument default, do not replace the resource.

For example, in  `azurerm_virtual_machine_scale_set`
```
priority - (Optional) Specifies the priority for the Virtual Machines in the Scale Set. Defaults to Regular. Possible values are Low and Regular.
```

On our internal Terraform Workspaces, Test and UAT, we are changing over to Spot instances

The default value, as shown above, is Regular. Priority has never been configured, because the default value took care of everything

To change the value for our TEST and UAT workspaces, I added this:

  priority              = terraform.workspace == "PROD" ? "Regular" : "Low"

So if Workspace is PROD, keep it Regular, else set it to Low. 
I expected this to not touch our production resources.

### Actual Behaviour

![image (1)](https://user-images.githubusercontent.com/17004772/107982360-2fbb2880-6fc4-11eb-9638-c03bee91c76e.png)

### Steps to Reproduce

Add a argument to a resource, with its default value

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set

**Comment by CarelvanHeerden** [comment]
# Update on the above.

The `ForceNew` on the priority was not ideal, however I have decided to use this as an opportunity to move over to `azurerm_linux_virtual_machine_scale_set`

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here as you've mentioned the older `azurerm_virtual_machine_scale_set` has been superseded by `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources - and as such the older `azurerm_virtual_machine_scale_set` resource is feature-frozen for compatibility with users relying on it's older behaviours.

At this point in time we'd recommend switching over to the `azurerm_linux_virtual_machine_scale_set` resource, where this is set by default - but otherwise you should be able to omit this field (e.g. change the coalesce statement to output `null` instead) to work around this using the legacy resource.

Thanks!
