### ISSUE TITLE
azurerm_site_recovery_fabric returns "FabricArmEntityMissing" error

### ISSUE THREAD

**Issue by philbal611** [terraform-providers/terraform-provider-azurerm#10595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform 0.12.29
- azurerm 2.47.0

### Affected Resource(s)

* `azurerm_site_recovery_fabric`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "primary" {
  name     = "tfex-network-mapping-primary"
  location = "West US"
}

resource "azurerm_resource_group" "secondary" {
  name     = "tfex-network-mapping-secondary"
  location = "East US"
}

resource "azurerm_recovery_services_vault" "vault" {
  name                = "example-recovery-vault"
  location            = azurerm_resource_group.secondary.location
  resource_group_name = azurerm_resource_group.secondary.name
  sku                 = "Standard"
}

resource "azurerm_site_recovery_fabric" "fabric" {
  name                = "primary-fabric"
  resource_group_name = azurerm_resource_group.secondary.name
  recovery_vault_name = azurerm_recovery_services_vault.vault.name
  location            = azurerm_resource_group.primary.location
}
```

### Expected Behaviour

Service fabric should be created successfully.

### Actual Behaviour

An error is received stating that the resource does not exist (UUIDs do not return all zeros. This was just masked for the ticket):

`Error: Error checking for presence of existing site recovery fabric primary-fabric (vault example-recovery-vault): siterecovery.ReplicationFabricsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Fabric with name primary-fabric could not be located." Details=[{"activityId":"00000000-0000-0000-0000-000000000000","clientRequestId":"00000000-0000-0000-0000-000000000000","code":"FabricArmEntityMissing","message":"Fabric with name primary-fabric could not be located.","possibleCauses":"The fabric might have been unregistered from the Microsoft Azure Site Recovery vault.","recommendedAction":"Retry the operation with a valid site."}]`

### Steps to Reproduce

1. Setup the above configuration
2. `terraform apply`

### References

This appears to be tracked by HashiCorp internally, but I haven't seen an issue raised here for public tracking:
- Found a comment where this error is being output in the provider config, added by @MitchDrage : https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/recoveryservices/site_recovery_fabric_resource.go#L67
- @tombuildsstuff raised an issue with the Azure API and is still open: https://github.com/Azure/azure-rest-api-specs/issues/12759

**Comment by LaurentLesle** [comment]
same issue in 2.47.0 
https://github.com/aztfmod/terraform-azurerm-caf/runs/1948806442?check_suite_focus=true

**Comment by tombuildsstuff** [comment]
As mentioned above this is a bug in the Azure API - as such it'd need to be fixed there, so I'm going to close this in favour of the upstream issue: https://github.com/Azure/azure-rest-api-specs/issues/12759
