### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AlexL-CC** [terraform-providers/terraform-provider-azurerm#1061]
Hi there,

Trying to run "terraform plan" but get crash instead.

### Terraform Version
0.11.5  342c529aa58d824f2f2ed1f6ec6118059876aad0

### Affected Resource(s)
unsure

### Terraform Configuration Files
https://github.com/AlexL-CC/tmp

### Debug Output
https://gist.github.com/AlexL-CC/cfd258c9232ba34ba9fc005c9d36a124
or
https://github.com/AlexL-CC/tmp/blob/master/console.log

### Panic Output
https://github.com/AlexL-CC/tmp/blob/master/crash.log

### Expected Behavior
plan should be created

### Actual Behavior
"treeaform crash" message

### Steps to Reproduce
1. delete `.terraform` directory
2. log in to azure `az login --service-principal -u 11111111-c66a-489a-ad17-111111111111 -p 11111111-3293-4d9e-a354-111111111111 --tenant 11111111-fe37-49b9-9d5c-111111111111`
3. make sure we're logged in: `az vm list-sizes --location "West Europe"`
4. `terraform init' or `terraform init -reconfigure`
5. `terraform plan`, this step produces the error

### Important Factoids
Few days ago it works like a charm, and of course nothing was changed. I know it sounds stupid but...

### References
None known

Thank you!

**Comment by JunyiYi** [comment]
This issue has been fixed in https://github.com/terraform-providers/terraform-provider-azurerm/commit/0b5f3b3895221e4f4df898098d9238ea7f05b5fd#diff-713fa2d463bac2c3e06221804a7f86afR180.

**Comment by katbyte** [comment]
@AlexL-CC,

To clarify: it seems this was an issue where older resources would not return their location. The panic points to the line @JunyiYi linked to above. This particular problem was fixed by #1074 in `v1.3.3`.

**Comment by tombuildsstuff** [comment]
Closing since this issue has been resolved and we’ve not heard back here
