### ISSUE TITLE
azurerm_dashboard causes HTTP 400 when calling portal.DashboardsClient#CreateOrUpdate

### ISSUE THREAD

**Issue by booyaa** [terraform-providers/terraform-provider-azurerm#10616]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
+ provider.azurerm v2.47.0

Your version of Terraform is out of date! The latest version
is 0.14.6. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_dashboard `

### Terraform Configuration Files

```hcl
resource "azurerm_dashboard" "my-board" {
  name                = "my-cool-dashboard"
  resource_group_name = azurerm_resource_group.my-group.name
  location            = azurerm_resource_group.my-group.location
  tags = {
    source = "terraform"
  }
  dashboard_properties = templatefile("dash.tpl",
    {
      md_content = "__My data2__"
  })
}
```

dash.tpl can be found [here](https://github.com/booyaa/tf_azurerm_dashboard_bug_10616/blob/main/dash.tpl)
### Debug Output

https://gist.github.com/booyaa/65c9222909236663bb282b80eb5da326

### Expected Behaviour

Dashboard should been create

### Actual Behaviour

```sh
terraform apply "dev.plan"
azurerm_dashboard.my-board: Creating...

Error: creating/updating Dashboard "my-cool-dashboard" (Resource Group "rg-dev"): portal.DashboardsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "{\"error\":{\"code\":37,\"message\":\"The request content was invalid and could not be deserialized: 'Required property 'lenses' not found in JSON. Path 'properties', line 1, position 39.'.\"}}" error: json: cannot unmarshal number into Go struct field RequestError.error of type string

  on main.tf line 30, in resource "azurerm_dashboard" "my-board":
  30: resource "azurerm_dashboard" "my-board" {
```

### Steps to Reproduce

1. `terraform apply`

An example has been provided: [link](https://github.com/booyaa/tf_azurerm_dashboard_bug_10616)

### Important Factoids

The example repo is pretty much based on the example given in the documentation: [link](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dashboard)

### References

* #0000

**Comment by trennepohl** [comment]
Hey @booyaa I was facing this issue too. I ran several tests using Azure API to understand what was happening. Would be correct to assume you downloaded the `json` file from the Azure Portal? because I did this and had the same issue.

After adapting the json file to look like the one below, I had no more issues. 
```json
{
    "lenses": {
        "0": {
            "order": 0,
            "parts": {
                "0": {
                    "position": {
                        "x": 0,
                        "y": 0,
                        "colSpan": 6,
                        "rowSpan": 4
                    },
                    "metadata": {
                        "inputs": [],
                        "type": "Extension/HubsExtension/PartType/MarkdownPart",
                        "settings": {
                            "content": {
                                "settings": {
                                    "content": "${md_content}",
                                    "title": "My title2",
                                    "subtitle": "My subtitle2",
                                    "markdownSource": 1,
                                    "markdownUri": null
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "metadata": {
        "model": {
            "timeRange": {
                "value": {
                    "relative": {
                        "duration": 24,
                        "timeUnit": 1
                    }
                },
                "type": "MsPortalFx.Composition.Configuration.ValueTypes.TimeRange"
            }
        }
    }
}
```


Note that the `metadata` field` shouldn't be inside the `properties` field. because the template gets unmarshaled to `portal.DashboardProperties` 

```go
type DashboardProperties struct {
	// Lenses - The dashboard lenses.
	Lenses map[string]*DashboardLens `json:"lenses"`
	// Metadata - The dashboard metadata.
	Metadata map[string]interface{} `json:"metadata"`
}
```

That's why it doesn't work when the `metadata` and `lenses` fields are child elements of `properties`

**Comment by booyaa** [comment]
@trennepohl hey thanks for sleuthing I'll give your suggested fix a go!

**Comment by katbyte** [comment]
@booyaa given it seems the solution posed worked i'm goping to close this, please do let us know if its still an issue for you thou@
