### ISSUE TITLE
Plan reports unexpected change of subnet_id in azurerm_app_service_virtual_network_swift_connection

### ISSUE THREAD

**Issue by thecodetinker** [terraform-providers/terraform-provider-azurerm#10617]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.6
azurerm v2.47.0

### Affected Resource(s)

* `azurerm_app_service_virtual_network_swift_connection`

### Terraform Configuration Files

```hcl

resource "azurerm_app_service" "main" {
  ... properties
}

data "azurerm_resource_group" "main" {
  name = var.rg_name
}

data "azurerm_subnet" "vnet_integration" {
  name                 = var.vnet_integration_subnet_name
  virtual_network_name = var.vnet_name
  resource_group_name  = data.azurerm_resource_group.main.name
}

resource "azurerm_app_service_virtual_network_swift_connection" "administrator_vnet_integration" {
  app_service_id = azurerm_app_service.main.id
  subnet_id      = data.azurerm_subnet.vnet_integration.id
}
```

### Expected Behaviour

No changes have been made to the terraform files here, so plan should not have picked up any changes. 

### Actual Behaviour

The terraform plan indicates that a change of subnet_id is required, although the two IDs listed by the plan are in fact identical.

```
  # azurerm_app_service_virtual_network_swift_connection.vnet_integration will be updated in-place
  ~ resource "azurerm_app_service_virtual_network_swift_connection" "vnet_integration" {
        app_service_id = "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Web/sites/sandbox-site"
        id             = "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Web/sites/sandbox-site/config/virtualNetwork"
      ~ subnet_id      = "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Network/virtualNetworks/VNET-SANDBOX/subnets/vnet-integration-app" -> "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Network/virtualNetworks/VNET-SANDBOX/subnets/vnet-integration-app"
    }
```

### Steps to Reproduce

1. Create an `azurerm_app_service` and an `azurerm_subnet` resource
2. Note that here the `azurerm_subnet` resource and resource group are created by an upstream TF project, and brought in here via Datasources. I'm not sure if that is relevant.
3. Create an `azurerm_app_service_virtual_network_swift_connection` resource to inject the App Service into the vNet
4. `terraform apply` to create the resources
5. Run `terraform plan` to verify

No changes are expected, but the plan indicates the `subnet_id` needs to change (yet displays the two IDs as identical).

I know the above TF is not complete but hopefully is enough to go on. Let me know if you need any further details.

### References

* #10105 is a very different resource, but exhibited similar behaviour. Probably unrelated, but I was glad when that got fixed :)

**Comment by tombuildsstuff** [comment]
hey @thecodetinker 

Thanks for opening this issue.

Taking a look through here:

>      ~ subnet_id      = "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Network/virtualNetworks/VNET-SANDBOX/subnets/vnet-integration-app" -> "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Network/virtualNetworks/VNET-SANDBOX/subnets/vnet-integration-app"

As you've mentioned these appear to be the same to me - as such I believe this may be an issue with Terraform Core, where the Data Source is dynamically refreshed and so for some reason this is triggering an update here even though there isn't one. From the Azure Providers side I've just merged #10570 which does fix these ID's within Terraform to be a consistent value - however I don't believe that'll solve this since I have a feeling this is a Core issue.

As such I'd suggest upgrading to the latest version of Terraform Core, which at the time of writing is 0.14.6 - and [opening an issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) if that's still an issue, where someone from the Core team should be able to take a look - but since this appears to be an issue with Terraform Core I'm going to close this issue for the moment.

Thanks!

**Comment by thecodetinker** [comment]
Hi @tombuildsstuff and thank you so much for the quick reply. Ironically, I did open this in the core repo, erroneously as I thought! Maybe I should re-open it :) 

https://github.com/hashicorp/terraform/issues/27803

However, I'll try a test with 0.14.6 first and see what happens!

**Comment by thecodetinker** [comment]
FYI - it turns out this is still an issue with 0.14.7 :(
