### ISSUE TITLE
Support for bind user-assigned identity on AKS VMSS

### ISSUE THREAD

**Issue by amosricky** [terraform-providers/terraform-provider-azurerm#10623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
After the AKS created, there have one or many VMSS for nodepools, and all of VMSS naming is dynamic. (eg. aks-agentpool-34xxx601-vmss)

Because the VMSS is auto created when AKS provision, it seems have no way to bind user-assigned identity on VMSS with terraform. 

```hcl
resource "azurerm_user_assigned_identity" "mi" {
  resource_group_name = {resource_group_name}
  location            = {location}
  name                = {name}
}

resource "azurerm_kubernetes_cluster" "k8s" {
    name                = XXX
    location            = XXX
    linux_profile {...}

    default_node_pool {
        name            = "agentpool"
        node_count      = var.agent_count
        vm_size         = "Standard_D2_v2"
    }
    identity {
        type = "SystemAssigned"
    }
    network_profile {
        network_plugin = "azure"
    }
    tags = {...}
}
```

![image](https://user-images.githubusercontent.com/24655194/108237721-24fac200-7183-11eb-9086-0ec4ef5eaa4a.png)

### New or Affected Resource(s)

* azurerm_user_assigned_identity
* azurerm_kubernetes_cluster

### Potential Terraform Configuration

Similar to whats already available in VMSS
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#identity

But the VMSS is auto created by AKS, it seems have no way with this.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #9965

**Comment by tombuildsstuff** [comment]
hi @amosricky 

Support for this is available as [the `user_assigned_identity_id` field within the `identity` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#user_assigned_identity_id) - as such you should be able to configure this field to use a User Assigned Identity here (and also setting `type` to `UserAssigned`.

Since this should be fixed by updating the Terraform Configuration being used here I'm going to close this issue for the moment - but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by amosricky** [comment]
hi @tombuildsstuff ,
Actually I want to use these identity for "AAD Pod Identity", so I need to bind different user-assigned identity on different VMSS. 
An VMSS probably have one or many user-assigned identity, is it possible to do this by terraform?

Tks for your reply =)

**Comment by amosricky** [comment]
Hi @tombuildsstuff ,
I have tried your solution
###
Support for this is available as the user_assigned_identity_id field within the identity block - as such you should be able to configure this field to use a User Assigned Identity here (and also setting type to UserAssigned.
###

However, this way seems only set an "user assigned managed identity" for VMSS access control as contributor.

`    identity {
        type = "UserAssigned"
        user_assigned_identity_id = {myidentityid}
    }`
![image](https://user-images.githubusercontent.com/24655194/108314892-93786800-71f5-11eb-8f5b-9e42b1d87500.png)

But it still not bind selected identity in VMSS user-assigned identity.
![image](https://user-images.githubusercontent.com/24655194/108315292-29ac8e00-71f6-11eb-9ddd-9ec9fccf842e.png)

So I think this feature still not be support.

Thanks!

**Comment by tombuildsstuff** [comment]
@amosricky support for that is being tracked in #10206

**Comment by tehho** [comment]
I have the same problem with UserAssigned identity that it does not select the chosen identity but creates its own.
We use blue green setup for our aks clusters and would like to reuse the identity so not to need owner on all different acr and whatnots.
#10938 

@amosricky 
If you only use this to select identitys you should be able to solve it by giving the cluster identity reader, or some rbac, over the identity the pod identity wants to use. AAD Pod Identity should then use the cluster identity and bind the pod identity to the cluster.
