### ISSUE TITLE
[BUG] [azurerm_eventgrid_event_subscription] advanced_filter string_contains MaxItems increase from 5 to 25

### ISSUE THREAD

**Issue by nfx** [terraform-providers/terraform-provider-azurerm#10620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Greetings azurerm provider community,

Please change 1 line of code to increase the limits from 5 to 25 of advanced filters for `azurerm_eventgrid_event_subscription`.
<img width="764" alt="databricks-checkins-two_-_Microsoft_Azure" src="https://user-images.githubusercontent.com/259697/108203254-82aaf200-7122-11eb-9f41-4c0536ae133a.png">

```
resource "azurerm_eventgrid_event_subscription" "this" {
  ...
  advanced_filter {
    string_contains {
      key = "d"
      values = ["a", "b", "c", "e", "f"] <------ currently there's limitation of 5, but there must be 25
    }
}
```

**Comment by jbinko** [comment]
I'll take this one

**Comment by jackofallops** [comment]
Closed by 10625
