### ISSUE TITLE
Unnecessary restriction on number of match_condition elements within azurerm_frontdoor_firewall_policy

### ISSUE THREAD

**Issue by thecodetinker** [terraform-providers/terraform-provider-azurerm#10634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.6
azurerm v2.47.0

### Affected Resource(s)

* `azurerm_frontdoor_firewall_policy`

### Terraform Configuration Files

```hcl
locals {
    ip_list = [
        "192.168.0.1",
        "192.168.0.2",
        "192.168.0.3",
        # etc... this is just for test and could be done with a CIDR format, but in our case these IPs are not contiguous
        "192.168.0.101",
        "192.168.0.102"
    ]
}

resource "azurerm_frontdoor_firewall_policy" "waf-policy" {
  name                = "WafPolicy"
  resource_group_name = "Main"
  enabled             = true

  custom_rule {
    name     = "IPAllowList"
    enabled  = true
    priority = 1
    type     = "MatchRule"
    action   = "Block"

    match_condition {
      match_variable     = "RemoteAddr"
      operator           = "IPMatch"
      negation_condition = true
      match_values       = local.ip_list
    }
  }
}
```

### Expected Behaviour

All the match conditions should be added to the WAF Policy custom rule.

### Actual Behaviour

Terraform plan reported an error:

```
Error: custom_rule.0.match_condition.0.match_values: attribute supports 100 item maximum, config has 109 declared

  on front-door-waf-policy.tf line 1, in resource "azurerm_frontdoor_firewall_policy" "waf-policy":
   1: resource "azurerm_frontdoor_firewall_policy" "waf-policy" {

```

### Steps to Reproduce

We wish to restrict access to a website to only known IP ranges via the Front Door WAF policy. Being a large organisation, this list is quite long, with various global express routes, VPN egress points, access via firewalls etc. Therefore we need a large number of match conditions on the custom rule. 

In Azure there is a limit to the number of custom rules that can be applied to a WAF (100) but as far as I can tell there is no limit to the number of match conditions for a single rule. Indeed, having added 100 using Terraform I was successfully able to add more via the Azure Portal.

Therefore I believe the provider is erroneously restricting the number of match conditions, rather than (or as well as) the number of custom rules.

1. Create a WAF policy and custom rule with more than 100 match conditions
1. Run `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
@WodansSon you've got the context for this one - mind double-checking this?

**Comment by thecodetinker** [comment]
Have verified this is working in 2.49 - thank you!
