### ISSUE TITLE
PostgreSQL schema still uses the preview version of the REST API

### ISSUE THREAD

**Issue by devigned** [terraform-providers/terraform-provider-azurerm#1065]
I'm guessing this is a point in time issue, but someone reached out to me regarding the difference between options for server SKUs.

The issue is that the current PG features target the preview version of the Azure REST API. They need to be upgraded to use the latest stable version. That latest version has the updated SKU schema, which includes a handful of changes from the preview version.

[Usage of the preview version](https://github.com/terraform-providers/terraform-provider-azurerm/blob/23af7a2ccda0903822a7b654e5909cee48e4f118/azurerm/resource_arm_postgresql_server.go#L8)
[Preview version of REST API SKU](https://github.com/Azure/azure-rest-api-specs/blob/64122e98211412bc22f81f40b7460c92452ecab9/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2017-04-30-preview/postgresql.json#L1090-L1101)
[Latest version of REST API SKU](https://github.com/Azure/azure-rest-api-specs/blob/64122e98211412bc22f81f40b7460c92452ecab9/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json#L1151-L1163)

### Terraform Version
Terraform v0.11.5

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_postgresql_server

### Expected Behavior
The PG server should have the same SKU options as advertised in documentation and the portal.

### Actual Behavior
The PG server uses the preview SKU options, which are no longer advertised.

**Comment by tombuildsstuff** [comment]
hey @devigned 

Thanks for opening this issue :)

Support for the new API version for both MySQL and Postgres is being tracked in #1004 - rather than having multiple issues open tracking the same thing; I'm going to close this issue in favour of that one - but we're looking into this at the moment and this should be fixed soon.

Thanks!

**Comment by devigned** [comment]
Sorry, @tombuildsstuff. I searched, but I didn't find the issue. I should have known you'd already be on top of the issue. Cheers!
