### ISSUE TITLE
Issue when deploying Key Vault using modules

### ISSUE THREAD

**Issue by Abhishekqwerty** [terraform-providers/terraform-provider-azurerm#10651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Facing Issue to create Key Vault when using modules for Key Vault and Resource Group, but it works fine when using a single terraform file to create Key Vault.

### Terraform (and AzureRM Provider) Version

* `Terraform v0.14.6`
* `azurerm v2.47.0`

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

* `azureResourceGroupModule`
```hcl
resource "azurerm_resource_group" "resourceGroup" {
  name     = "example-resources"
  location = "North Europe"
}
````

* `azureKeyVaultModule`
```hcl
data "azuread_users" "admins" {
  user_principal_names = ["kat@hashicorp.com", "byte@hashicorp.com"]
}

locals {
  admin_objectId = data.azuread_users.admins.object_ids
}

resource "azurerm_key_vault" "keyvault" {
  name                = "examplekeyvault"
  location            = "North Europe"
  resource_group_name = "example-resources"
  tenant_id           = "2xxx7xxf-2xxa-4xx3-8xx9-xxxxxxxx"
  soft_delete_enabled = true
  soft_delete_retention_days = 7
  purge_protection_enabled = false
  sku_name = "standard"
}

resource "azurerm_key_vault_access_policy" "admin_access_policy" {
  count = length(local.admin_objectId)
  depends_on = [ azurerm_key_vault.keyvault ]
  key_vault_id = azurerm_key_vault.keyvault.id
  tenant_id    = "2xxx7xxf-2xxa-4xx3-8xx9-xxxxxxxx"
  object_id = local.admin_objectId[count.index]

  key_permissions = ["get", "list","update","create","import",]"delete","recover","backup","restore","purge",]

  secret_permissions = ["get","list","set","delete","recover","backup","restore","purge",]
}
```
* `Parent terraform script`
```hcl
module "resource_group" {
  source = "./azureResourceGroupModule"
}

module "keyvault" {
  depends_on = [ module.resource_group ]
  source = "./azureKeyVaultModule"
}
```

### Expected Behaviour

Key Vault Module should get the list of admins object Id and calculate the length of the list.

### Actual Behaviour

Getting the error as following:
Error: Invalid count argument

  on azureKeyVault\main.tf line 28, in resource "azurerm_key_vault_access_policy" "admin_access_policy":
  28:   count = length(local.admin_objectId)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @Abhishekqwerty 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by Abhishekqwerty** [comment]
@tombuildsstuff Do you think is this a question! 
This is a type of bug that works when all resources are deployed using a single terraform script and when deploying resources using modules are not working as expected. The data sources are known after apply, but this should not be the expected results as the data source should reading the data before apply.

**Comment by tombuildsstuff** [comment]
@Abhishekqwerty this is tagged `question` since this is a Terraform usage question - as Terraform Core is highlighting:

```
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
