### ISSUE TITLE
Azure Front Door Deployment Issues

### ISSUE THREAD

**Issue by tpeterson66** [terraform-providers/terraform-provider-azurerm#10661]
When creating a new or updating an existing Azure Front Door it takes an extremely long time to update or create the new service. Based on the documentation for the front door, it should be possible to create/update multiple frontend HTTPs configurations at once.
```
Defining custom https configurations using a separate azurerm_frontdoor_custom_https_configuration resource allows for parallel creation/update.
```

However, when I configure the "azurerm_frontdoor_custom_https_configuration" resources and add the respective frontends and apply, Terraform updates each frontend sequentially and then updates all the frontends at once after sequentially updating them. 

For example, I have 4 frontends, the default azurefd.net, and www.example.com, api.example.com, and search.example.com. When I apply, even with the "azurerm_frontdoor_custom_https_configuration" resources configured, Terraform updates www.example.com first and waits for that to complete before updating api.example.com and then finally, search.example.com. Once the sequential updates are complete, the "azurerm_frontdoor_custom_https_configuration" resources are finally deployed and update all three domains at once, which only takes 5-10 minutes to complete.

My problem is not with how long it takes, but with the order in which updates the frontends. If there are 5 frontends configured, this apply can take ~60 minutes to complete, which is not acceptable for production apps. Is it possible to update this so it updates all the frontends at once rather than sequentially?

I'm running TF version 0.14.7 and have tested with other versions with similar results.
I'm also running provider version v2.48.0 and have tested earlier versions as well.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ericjohnson2** [comment]
I would reference this issue which is being addressed in 2 parts. [Part 1 ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/9357) has been merged as of 2.47.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/9153

I addition, I have noticed similar outcomes when using `azurerm_frontdoor_custom_https_configuration` resources where updates take 40+ minutes.

**Comment by mihma** [comment]
Really looking forward to Part 2 fix, Front Door deployments taking ages.

**Comment by brnwn4** [comment]
Can we get any further traction?

**Comment by WodansSon** [comment]
As part of the fix for sorting I noticed in the code, back when v2.20.0 was released, that was the version of the provider where we pulled out the `azurerm_frontdoor_custom_https_configuration` to be a stand alone resource. However, when this was don't the update logic to the frontend endpoints was not removed from the main `azurerm_frontdoor` resource which would cause the frontends to be updated twice. In the #11456 PR I have removed all logic pertaining to the maintenance of the frontend endpoints and delegated that task solely to the `azurerm_frontdoor_custom_https_configuration` resource and in doing so you should no longer see this issue after v2.58.0 is released.
