### ISSUE TITLE
Creating windows VM with reference to keyvault certificate URL fails

### ISSUE THREAD

**Issue by pixelicous** [terraform-providers/terraform-provider-azurerm#1067]
I am creating a Keyvault, Certificate in it and a VM that will use that certificate in its "My" store and for WinRM.
I am getting the errors below, for some reason the version ID as the last part of the certificate URL never matches what i see in the portal. By the last part is the 'xxxxxxx' below:
> https://my_keyvault.vault.azure.net/secrets/my_cert_name/xxxxxxxxxxxxx

I think there is an issue and terraform is reading some other ID, even when just trying to read the certificate id with "${azurerm_key_vault_certificate.cert.id}" it gives a completely different number at the end of the url. It doesn't seem like there is a support for secret or certificate datasource or have a ".url" property when creating the resource.

### Terraform Version
```
Terraform v0.11.5
+ provider.azurerm v1.3.1
```

### Affected Resource(s)
azurerm_key_vault
azurerm_key_vault_certificate

### Terraform Configuration Files
```
resource "azurerm_key_vault" "certs_keyvault" {
  name                = "${local.name_prefix}-kv"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"

  sku {
    name = "standard"
  }

  tenant_id = "${data.azurerm_client_config.current.tenant_id}"

  access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${data.azurerm_client_config.current.service_principal_object_id}"

    key_permissions = [
      "backup",
      "create",
      "decrypt",
      "delete",
      "encrypt",
      "get",
      "import",
      "list",
      "purge",
      "recover",
      "restore",
      "sign",
      "unwrapKey",
      "update",
      "verify",
      "wrapKey",
    ]

    secret_permissions = [
      "backup",
      "delete",
      "get",
      "list",
      "purge",
      "recover",
      "restore",
      "set",
    ]

    certificate_permissions = [
      "create",
      "delete",
      "deleteissuers",
      "get",
      "getissuers",
      "import",
      "list",
      "listissuers",
      "managecontacts",
      "manageissuers",
      "setissuers",
      "update",
    ]
  }

  enabled_for_deployment          = true
  enabled_for_template_deployment = true

  tags = "${var.tags}"
}

resource "azurerm_key_vault_certificate" "cert" {
  name      = "${local.name_prefix}-name-cert"
  vault_uri = "${azurerm_key_vault.certs_keyvault.vault_uri}"

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    lifetime_action {
      action {
        action_type = "AutoRenew"
      }

      trigger {
        days_before_expiry = 30
      }
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }

    x509_certificate_properties {
      key_usage = [
        "cRLSign",
        "dataEncipherment",
        "digitalSignature",
        "keyAgreement",
        "keyCertSign",
        "keyEncipherment",
      ]

      subject            = "CN=${azurerm_network_interface.vm_name.private_ip_address}"
      validity_in_months = 12
    }
  }
}

resource "azurerm_virtual_machine" "vm_name" {
  name                  = "${local.name_prefix}-name"
  location              = "${var.location}"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  network_interface_ids = ["${azurerm_network_interface.vm_name_nic.id}"]
  vm_size               = "${lookup(var.virtual_machine_sizes, lookup(var.vmSizeAllocation, "name"))}"
  depends_on            = ["azurerm_network_interface.vm_name_nic"]

  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }

  storage_os_disk {
    name              = "${local.name_prefix}-name-osdisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "${var.environment}vm"
    admin_username = "${var.admUser}"
    admin_password = "${var.admPass}"
  }

  os_profile_windows_config {
    provision_vm_agent = true

    winrm {
      protocol        = "https"
      certificate_url = "${azurerm_key_vault.certs_keyvault.vault_uri}secrets/${azurerm_key_vault_certificate.cert.name}/${azurerm_key_vault_certificate.cert.version}"
    }
  }

  os_profile_secrets {
    source_vault_id = "${azurerm_key_vault.certs_keyvault.id}"

    vault_certificates {
      certificate_url   = "${azurerm_key_vault.certs_keyvault.vault_uri}secrets/${azurerm_key_vault_certificate.cert.name}/${azurerm_key_vault_certificate.cert.version}"
      certificate_store = "My"
    }
  }

  tags = "${var.tags}"
}
```

### Debug Output
Using:
certificate_url   = "${azurerm_key_vault.certs_keyvault.vault_uri}secrets/${azurerm_key_vault_certificate.cert.name}/${azurerm_key_vault_certificate.cert.version}"
```
* azurerm_virtual_machine.vm_name: Long running operation terminated with status 'Failed': Code="KeyVaultAccessForbidden" Message="Key Vault https://my_keyvault.vault.azure.net/secrets/my_cert_name/xxxxxxxxxxxxx either has not been enabled for deployment or the vault id provided, /subscriptions/my_subscription_name/resourceGroups/my_rg_name/providers/Microsoft.KeyVault/vaults/my_kv_name, does not match the Key Vault's true resource id."
```

### Expected Behavior
Keyvault created with certificate, VM created with certificate imported, winrm enabled and using that certifcate

### Actual Behavior
Keyvault and certificate are created, VM crashes

### Steps to Reproduce
Terraform init (working ok)
Terraform apply

### Important Factoids

- The names have changed in the HCL and output above, but i have verified the subscription id, resource group name, keyvault name and certificate, they are all fine during execution.

- It seems like Microsoft has moved certificates to their own namespace under the provider, but are still called using /secrets, when i tried to use /certificates it also failed. I tried using hcl syntax certificate_url   = "${azurerm_key_vault_certificate.cert.id}" but then i am getting
```
* azurerm_virtual_machine.vm_name: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="https://my_kv_name.vault.azure.net/certificates/amy_cert_name/xxxxxxxx is not a valid versioned Key Vault Secret URL. It should be in the format https://<vaultEndpoint>/secrets/<secretName>/<secretVersion>
```
- In terms of permissions the SPN and the user running terraform both have relevant permission to the keyvault.

- It seems weird that it is erroring out on a keyvault but the actual url that it is showing is the whole url of the secret, not the keyvault!

**Comment by pixelicous** [comment]
I think i might be passing the wrong object, certificate url should be:
{
"data":"",
"dataType":"pfx",
"password":""
}

But it doesn't have a password or anything.. i will need to further check and close if not relevant

**Comment by pixelicous** [comment]
I tried using (Get-AzureKeyVaultSecret -VaultName my_kv_name -Name my_certificate_name).Id
I am getting a different ID than what terraform shows. Maybe i should work with azurerm_key_vault_secret instead..

**Comment by pixelicous** [comment]
I am reading here:
https://docs.microsoft.com/en-us/rest/api/keyvault/about-keys--secrets-and-certificates#BKMK_CertificateIssuer

"When a Key Vault certificate is created, an addressable key and secret are also created with the same name"
No secrets have been created.. even if so.. i will not be able to reference them without a data source..

**Comment by pixelicous** [comment]
@katbyte can you hint if you think this could be solved soon?
It's really breaking the ability to provision winrm in a very easy way

**Comment by noderat** [comment]
Confirmed. This also occurs with linux VMs. Inspecting the URL with curl from the tfstate returns what appears to be a deleted certificate but I can't seem to query it from the azure CLI directly

```json
{
    "id": "https://[redacted].vault.azure.net/certificates/[redacted]/b30d7c19750041a894cfe928103e98dd",
    "attributes": {
        "enabled": false,
        "nbf": 1523264547,
        "exp": 1554801147,
        "created": 1523265147,
        "updated": 1523265147,
        "recoveryLevel": "Purgeable"
    },
    "tags": {}
}
```

**Comment by pixelicous** [comment]
@tombuildsstuff thanks again for taking things over :) this is critical, it also affects users using service fabric, we have to rely on arm template due to not having a resource for it, and we need to push certificates to the scale sets' certificate repositories, which cannot happen today, we need to hard code the IDs of the certificates..

**Comment by noderat** [comment]
Awesome! Thanks @tombuildsstuff for the speedy response

**Comment by ChethanRavulaGit** [comment]
@tombuildsstuff 
azurerm_key_vault_certificate has only methods to import and create certificate. If a certificate is already imported and i want to get the thumprint and secret ID, is there a way to do it?
