### ISSUE TITLE
Version incompatibility in azurerm_sql_database import

### ISSUE THREAD

**Issue by samar-upadhyay** [terraform-providers/terraform-provider-azurerm#10685]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v0.14.7

### Affected Resource(s)

* `azurerm_sql_server`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_sql_server" "test_sql_server" {
  name                         = "sql-server"
  resource_group_name          = "test-rg"
  location                     = var.central_region
  version                      = "12.0"
  administrator_login          = var.user
  administrator_login_password = var.pw
}

resource "azurerm_sql_database" "test_database" {
  name                             = "testdb"
  resource_group_name              = "test-rg"
  location                         = azurerm_resource_group.test_sql_server.location
  server_name                      = azurerm_sql_server.test_sql_server.name
  create_mode                      = "Default"
  edition                          = "BusinessCritical"
  x_size_bytes                   = "1099511627776"
  requested_service_objective_name = "BC_Gen5_20"

  extended_auditing_policy {
    storage_endpoint                        = azurerm_storage_account.audit_storage.primary_blob_endpoint
    storage_account_access_key              = azurerm_storage_account.audit_storage.primary_access_key
    storage_account_access_key_is_secondary = true
    retention_in_days                       = 6
  }

  import {
    storage_uri                  = "<redacted-bacpac>"
    storage_key                  = data.azurerm_storage_account.import_data_storage.primary_access_key
    storage_key_type             = "StorageAccessKey"
    administrator_login          = var.user
    administrator_login_password = var.pw
    authentication_type          = "SQL"
  }
}
```

### Debug Output

Message from azure:

IMPORT TO EXISTING DATABASE
Could not import package. Warning SQL0: A project which specifies SQL Server 2019 or Azure SQL Database Managed Instance as the target platform may experience compatibility issues with Microsoft Azure SQL Database v12. Warning SQL72012: The object [data_0] exists in the target, but it will not be dropped even though you selected the 'Generate drop statements for objects that are in the target database but that are not in the source' check box. Warning SQL72012: The object [log] exists in the target, but

### Expected Behaviour

Manual import from the azure portal of the same bacpac is successful. However, terraform import reports the above incompatibility error.

### Actual Behaviour

Error in azure database notification blade.

### Steps to Reproduce

Take a sql server database backup from Sql server 2019.
Run terraform db import to import this data into a new db. The available values for versions in azurerm_sql_server are:
version - (Required) The version for the new server. Valid values are: 2.0 (for v11 server) and 12.0 (for v12 server).

No options for v14 and v15

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @samar-upadhyay 

Thanks for opening this issue.

There's two different versions of SQL Server support within Azure - the `mssql` resources (using the newer API/featureset/pricing model) and the `sql` resources (using the older API's/featureset/pricing model) - as such it should be possible to work around this by using [the newer `azurerm_mssql_database` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database)).

Since this should be fixed by switching to use the `mssql` resources - I'm going to close this issue for the moment, but should you have further usage questions I'd direct you towards [the community Discuss forum](https://discuss.hashicorp.com).

Thanks!
