### ISSUE TITLE
docs: azurerm_application_insights_web_test

### ISSUE THREAD

**Issue by ppanyukov** [terraform-providers/terraform-provider-azurerm#10682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0
```

### Affected Resource(s)

* `azurerm_application_insights_web_test`

### Terraform Configuration Files

**Scenario 1. Web Test is in not in the same RG as App Insights.**

FAILS.

```hcl
resource "azurerm_resource_group" "ai" {
  name     = "philip-test-appi-rg"
  location = "westeurope"
}

resource "azurerm_application_insights" "ai" {
  name                = "philip-test-appi"
  location            = "westeurope"
  resource_group_name = azurerm_resource_group.ai.name
  application_type    = "web"
}


resource "azurerm_resource_group" "webtest" {
  name     = "philip-test-webtest-rg"
  location = "westeurope"
}

# This is a wrapper over 'azurerm_application_insights_web_test'.
module "webtest" {
  source                  = "./modules/webtest"
  name                    = "philip-test-webtest"
  resource_group_name     = azurerm_resource_group.webtest.name
  location                = "westeurope"
  application_insights_id = azurerm_application_insights.ai.id
  url                     = "https://example.com/"
}

```

Error message:

```
Error: creating/updating Application Insights WebTest "philip-test-webtest" 
(Resource Group "philip-test-webtest-rg"): insights.WebTestsClient#CreateOrUpdate: 
Failure responding to request: StatusCode=400 -- 

Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" 
Message="
    Resource should exist in the same resource group as the linked component: 
    /subscriptions/REDACTED/resourceGroups/philip-test-appi-rg/providers/microsoft.insights/components/philip-test-appi
" 

InnerError={"diagnosticcontext":"REDACTED","time":"2021-02-22T14:27:26.9363617Z"}
```

**Scenario 2. Web Test IS in the same RG as App Insights. But it is NOT in the same location.**

FAILS.

```hcl
resource "azurerm_resource_group" "ai" {
  name     = "philip-test-appi-rg"
  location = "westeurope"
}

resource "azurerm_application_insights" "ai" {
  name                = "philip-test-appi"
  location            = "westeurope"
  resource_group_name = azurerm_resource_group.ai.name
  application_type    = "web"
}


# This is a wrapper over 'azurerm_application_insights_web_test'.
module "webtest" {
  source                  = "./modules/webtest"
  name                    = "philip-test-webtest"
  resource_group_name     = azurerm_resource_group.ai.name
  location                = "northeurope"
  application_insights_id = azurerm_application_insights.ai.id
  url                     = "https://example.com/"
}
```

Error message:

```
Error: creating/updating Application Insights WebTest "philip-test-webtest" 
(Resource Group "philip-test-appi-rg"): insights.WebTestsClient#CreateOrUpdate: 
Failure responding to request: StatusCode=400 -- 

Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" 
Message="
    Resource must exist in the same location as the linked component: westeurope
" 

InnerError={"diagnosticcontext":"45fdc272-a0af-4644-989d-7a4496554093","time":"2021-02-22T14:32:59.4047808Z"}
```

### Expected Behaviour

**Docs for `azurerm_application_insights_web_test`**

Expected behaviour:
* Requirement that webtest needs to be in the same resource group **and** location should be stated.

* Argument `geo_locations`. Please link to somwhere which tells us what they are, as these are not the same as Azure locations. They are `us-il-ch1-azr` and `emea-nl-ams-azr`.  Where are we supposed to dig these out?

* Argument `configuration`. Please link to the docs on this XML. What is actually required in that XML? Everything? I know that `id` and `guid` attributes can be empty strings from experience. Right now we have to second-guess everything.

* Argument `tags`. Should either state that a "special" tag in the form of `"hidden-link:${var.application_insights_id}" = "Resource"` must be supplied by the user, or the provider should take care of this.

### Actual Behaviour

The docs here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_web_test:

* Does not have doc for `resource_group_name` at all.

* Incorrect docs for `location` argument: currently says `(Required) The location of the resource group.` which obviously needs to say "web test" not "resource group"/

* No mention that both `location` and `resource_group_name` must be same as of the App Insights component specified by `application_insights_id`.

* No useful docs for `geo_locations` and `configuration`.

* The special `tags` value is not documented. This leads to contant the immediate configuration drift right after we create web test if we failed to supply this special tag.

**Comment by jbinko** [comment]
@ppanyukov 
I'll prepare fix/update documentation

Just few comments here:
-	Argument geo_locations – I'll provide link where values can be seen
-	Argument configuration – I have not found any documentation/specification/schema around it. I believe it is related to Visual Studio Web Tests
-	Argument tags – this is standard Azure/TF attribute. See: Tag resources, resource groups, and subscriptions for logical organization - Azure Resource Manager | Microsoft Docs
-	Argument resource_group_name - documentation will be added
-	Argument location – it needs to corellate with location of parent resource (azurerm_application_insights) rather than location of resource group. I’ll change example in doc

**Comment by ppanyukov** [comment]
@jbinko thanks for this. Docs look so much better now! 

We can make them even better.

* **XML configuration**. I'm not sure this is a valid option to point to Azure RM docs which also have no documentation on what this XML should be, it's like sending users on a wild goose chase. Basically the current docs are still not helpful in this area. If people at MSFT don't know what that XML should be and can't find docs for it, I'm sure you will agree that pushing this problem down to the users to figure it out on their own is not a good option? Would you agree? Lets please dig out the docs, they must be somewhere.


* **resource_group_name**: we can/should state it needs to be in the same rg as parent AI resource, just like for location. I believe this is true.

* **tags**. Let me clarify what exactly the problem is.

Consider I create a webtest without any tags like so:

```hcl
resource "azurerm_application_insights_web_test" "availability_test" {
  # no tags
}
```

Immediately after the resource is created, I run `terraform plan` and I immediately see the configuration drift in tags like so:

```hcl
  # module.webtest.azurerm_application_insights_web_test.availability_test will be updated in-place
  ~ resource "azurerm_application_insights_web_test" "availability_test" {
      ~ tags                    = {
          - "hidden-link:/subscriptions/REDACTED/resourceGroups/philip-test-appi-rg/providers/microsoft.insights/components/philip-test-appi" = "Resource" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Do you see the problem? Somehow this "hidden-link" tag was added without my knowledge. Not only this causes immediate drift (it shouldn't), but what happens if I apply my configuration and remove this "hidden-link"? Let's try it.

Oh, I've applied my config to remove the tag, and guess what? It's still there! So when I run my `terraform plan` again, I get exactly same config drift. It's a permanent drift!

So, if this tag is required, then I propose one of the following:

* Either docs explicitly say it's required (not the best option in my opinion but hey).
* Or the provider itself adds this tag on behalf of the user, in which case it's much better for us users and also resolves this permanent drift.

Hope this makes sense.
