### ISSUE TITLE
Azurerm_managed_disk Does Not Destroy Resource

### ISSUE THREAD

**Issue by jak119** [terraform-providers/terraform-provider-azurerm#1069]
### Terraform Version
Terraform v0.11.5

### Affected Resource(s)
- azurerm_managed_disk

### Terraform Configuration Files
Able to reproduce with the [example from the docs](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#example-usage-with-managed-disks-and-custom-images-recommended-).

### Panic Output
N/A

### Expected Behavior
Terraform should've picked up on the disk being destroyed

### Actual Behavior
Terraform does not register the disk as having been destroyed and eventually the run needs to be terminated.

### Steps to Reproduce
1. Create a VM with a data disk
1. Comment out the VM and run `terraform apply` or run `terraform destroy`

### Important Factoids
N/A

### References
N/A

**Comment by tombuildsstuff** [comment]
hi @jak119 

Thanks for opening this issue - apologies for the delayed response here!

Would it be possible to confirm if you're seeing this issue with the latest version of the Provider, and to share a Terraform Configuration where this is the issue? I'm going to close this issue for the moment but please feel free to reopen it if this is still an issue with the latest version of the Provider.

Thanks!
