### ISSUE TITLE
Support for Internal Load Balancer

### ISSUE THREAD

**Issue by benhurjoel** [terraform-providers/terraform-provider-azurerm#10700]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At this time, the Terraform resource does not show an option to create an Internal Load Balancer. I'm able to create only the Internet-facing LB.

### New or Affected Resource(s)

* azurerm_lb

### Potential Terraform Configuration

```hcl
resource "azurerm_lb" "example" {
  name                = "TestLoadBalancer"
  location            = "West US"
  resource_group_name = azurerm_resource_group.example.name
  type          = internal  (<---  new  )

}
```

### References

https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb

**Comment by tombuildsstuff** [comment]
Taking a look through here this likely wants to be a new resource rather than inlined within the existing resource - since the behaviour and feature-set are different

**Comment by favoretti** [comment]
@tombuildsstuff When I compare ARM templates for both - they are essentially the same.
Public LB has a public IP address attached as:
![image](https://user-images.githubusercontent.com/805046/109137443-7eea2180-7759-11eb-9737-0d1f934b19ed.png)

Whereas private one has a subnet linked in case of dynamic IP address allocation:
![image](https://user-images.githubusercontent.com/805046/109137578-a4772b00-7759-11eb-883e-f6e9d0cbd52c.png)

And with static IP allocation:
![image](https://user-images.githubusercontent.com/805046/109137675-bf499f80-7759-11eb-9f23-9bc8d28623f5.png)

I think it could fit into an existing resource as well?

**Comment by benhurjoel** [comment]
@favoretti Thank  you for the hint. It indeed works! 

My test code :

```
provider "azurerm" {
    features {}
}

resource "azurerm_resource_group" "test" {
  name     = "test-rg"
  location = "Southeast Asia"
}

resource "azurerm_virtual_network" "test" {
  name                = "test-vnet"
  address_space       = ["10.1.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "test-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.1.1.0/24"]
}

resource "azurerm_lb" "example" {
  name                = "TestLoadBalancer"
  location            = "Southeast Asia"
  resource_group_name = azurerm_resource_group.test.name

  frontend_ip_configuration {
    name                 = "Internal"
    subnet_id            = azurerm_subnet.test.id
    private_ip_address   = "10.1.1.5"
    private_ip_address_allocation = "Static"
  }
}
```

and the result seen on the portal:

![image](https://user-images.githubusercontent.com/57881441/109150625-11171780-77a4-11eb-88ba-41e5fb14f8d6.png)


@tombuildsstuff we can close this issue. But, may I request to place this information on the docs page, please? 

Thank you, again @favoretti  and @tombuildsstuff .
