### ISSUE TITLE
The Identity block is not exporting the principal_id as listed in the article.

### ISSUE THREAD

**Issue by sunkaris** [terraform-providers/terraform-provider-azurerm#10708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

The **principal_id** value should be available.

### Actual Behaviour

Can't read the principal_id
 principal_id         = azurerm_synapse_workspace.rpt_synapse_ws_name.identity.principal_id | tried with object_id

### Steps to Reproduce

#Adds Synapse Workspace Managed Identity to the "Storage Blob Data Contributor"
 resource "azurerm_role_assignment" "msidatacontributor" {
  scope = azurerm_storage_account.rpt_synapse_sa_name.id
  #scope = azurerm_storage_data_lake_gen2_filesystem.synapse_storage_filesystem.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_synapse_workspace.rpt_synapse_ws_name.identity.principal_id
} 

Error: Unsupported attribute

  on main.tf line 104, in resource "azurerm_role_assignment" "msidatacontributor":
 104:   principal_id         = azurerm_synapse_workspace.rpt_synapse_ws_name.identity.principal_id

This value does not have any attributes.

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_workspace#identity

* #0000

**Comment by favoretti** [comment]
Can you try:
```
principal_id = azurerm_synapse_workspace.rpt_synapse_ws_name.identity[0].principal_id
```
please?

Looking at the code `identity` field is a list.

**Comment by sunkaris** [comment]
Thank you! This worked. I had few errors adding the "Storage Blob Data Contributor role".  Resolved it from my end.
