### ISSUE TITLE
azurerm_storage_container: Metadata containing Upper Case characters breaks

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#10723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform 0.14.4
* AzureRM 2.48

### Affected Resource(s)

* `azurerm_storage_container`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "container" {
  name                  = module.container_name.name
  storage_account_name  = var.storage_account_name
  container_access_type = var.container_access_type
  metadata              = var.metadata
}
```
Where `metadata` looks something like this
```hcl
metadata = {
  meta        = "data"
  noUpperCase = "none"
}
```

### Debug Output

Debug output may contain sensitive stuff to which I don't think I can share publicly.

### Expected Behaviour

It should either accept that upper case characters is a valid name. Or, if this is a known Azure limitation, it should be documented as such that only lower case characters plus underscores are allowed in the container metadata.

### Actual Behaviour

```
Error: MetaData must start with letters or an underscores. Got "noUpperCase".

  on ../../_modules/container/main.tf line 9, in resource "azurerm_storage_container" "container":
   9: resource "azurerm_storage_container" "container" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by favoretti** [comment]
```
          ~ resource "azurerm_storage_container" "test" {
                id                      = "https://acctestacc2vr04.blob.core.windows.net/vhds"
              ~ metadata                = {
                  + "upperCase" = "something"
                  - "uppercase" = "something" -> null
                    # (2 unchanged elements hidden)
                }
                name                    = "vhds"
                # (5 unchanged attributes hidden)
            }
```

Seems to be Azure API limitation, will adjust error message and docs.
