### ISSUE TITLE
cannot adjust postgres server configuration

### ISSUE THREAD

**Issue by kzw** [terraform-providers/terraform-provider-azurerm#10721]
i managed to change a postgres server configuration which did not have anything set for `azure.replication_support` to `logical`.  But then I cannot turn off this attribute for the same instance.  Nor can I change it back to any other values.  I had to use `az cli` to turn it off.  Here is the message from `az` cli

```
az postgres server configuration set --resource-group redacted --server-name redacted2 --name azure.replication_support --value replica
{- Finished ..
  "allowedValues": "OFF,REPLICA,LOGICAL",
  "dataType": "Enumeration",
  "defaultValue": "OFF",
  "description": "Sets the level of replication support (Read Replicas). Any change requires restarting the server to take effect.",
  "id": "/subscriptions/8redacteda/resourceGroups/redacted/providers/Microsoft.DBforPostgreSQL/servers/redacted/configurations/azure.replication_support",
  "name": "azure.replication_support",
  "resourceGroup": "redacted",
  "source": "user-override",
  "type": "Microsoft.DBforPostgreSQL/servers/configurations",
  "value": "replica"
}

```

terraform now says

```
Error: Code="InvalidConfigurationValue" Message="The value 'OFF' for configuration 'azure.replication_support' is not valid. The allowed values are 'REPLICA,LOGICAL'."


```
regardless of the state and code.  

terraform 12.30
azurerm provider 2.45

**Comment by tombuildsstuff** [comment]
👋 

Unfortunately this is a bug in the Azure API, which is being [tracked in this ticket](https://github.com/Azure/azure-rest-api-specs/issues/10037) - as such I'm going to close this in favour of that issue, would you mind subscribing [to the upstream issue](https://github.com/Azure/azure-rest-api-specs/issues/10037) for updates?

Thanks

**Comment by kzw** [comment]
For those coming for terraform solution, I had to go from `logical` to `replica` to `off` using `az` cli.  Then terraform state is synced again as if there is no such resource.
