### ISSUE TITLE
Support for secrets in key vault for azurerm_data_factory_linked_service_azure_sql_database

### ISSUE THREAD

**Issue by drjwelch** [terraform-providers/terraform-provider-azurerm#10758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_data_factory_linked_service_sql_server supports the use of a key_vault_password block

azurerm_data_factory_linked_service_azure_sql_database does not; instead the full connection string has to be specified in plain text

Please provide support for the key_vault_password block and/or a new key_vault_connection_string block - thanks.

If these resources have to be created manually and not managed by terraform then they create a dependency that prevents terraform from destroying the parent resources.

### New or Affected Resource(s)

azurerm_data_factory_linked_service_azure_sql_database 

### Potential Terraform Configuration

```
resource "azurerm_data_factory_linked_service_azure_sql_database" "example" {
  name                           = "example"
  resource_group_name  = azurerm_resource_group.example.name
  data_factory_name       = azurerm_data_factory.example.name

  connection_string         = "Integrated Security=False;Data Source=test;Initial Catalog=test;User ID=test;"
  key_vault_password {
      linked_service_name = azurerm_data_factory_linked_service_key_vault.example.name
      secret_name             = "secret_password"
  }
}
```
and/or
```
resource "azurerm_data_factory_linked_service_azure_sql_database" "example" {
  name                           = "example"
  resource_group_name  = azurerm_resource_group.example.name
  data_factory_name       = azurerm_data_factory.example.name

  key_vault_connection_string {
      linked_service_name = azurerm_data_factory_linked_service_key_vault.example.name
      secret_name             = "secret_connstring"
  }
}
```

**Comment by drjwelch** [comment]
@favoretti maybe you would consider extending your current PR?

**Comment by favoretti** [comment]
@drjwelch Possibly. I'll take a look at it later this week.

**Comment by drjwelch** [comment]
Very kind 🙇 - I would willingly contribute myself if I had the skills

**Comment by favoretti** [comment]
@drjwelch Adapted my PR to add this in the same fashion as sql_server implements it.

**Comment by kevinmatthews-kpmg** [comment]
The password for sql server is done, but the connection string still needs to be passed in as a string instead of key vault, does anyone know if this is being added?
Thanks

**Comment by favoretti** [comment]
@kevinmatthews-kpmg I'm quite a monkeycoder in this case, would you be so kind to elaborate on the use-case and the issue here, since we're not using this particular linked service ourselves.

**Comment by kevinmatthews-kpmg** [comment]
Hi,

Yes no problem. ok so when you add an sql server linked service within the data factory there are 2 options.

One is to add the connection string as a value (which is how terraform does it) or via key vault (**this option is not available in terraform**)

If you choose connection string, you then have a second option which is to add the password from key vault (terraform has this option available)
 
We would prefer to not have to put a connection string in to the terraform and instead have that in keyvault and use the option in the data factory to get the connection string from key vault. 

So although there is a key_vault_password option in the terraform provider, a key_vault_connection_string as the OP describes in the second instance is missing. 

Thanks
Kevin

**Comment by favoretti** [comment]
@kevinmatthews-kpmg PR for SQL server is submitted. Will shoot another one for `azure_sql_database` after this one is reviewed.
