### ISSUE TITLE
Terraform Refresh takes 5 minutes for storage account blob private endpoint when privatelink.blob.core.windows.net dns zone exists

### ISSUE THREAD

**Issue by mleziva** [terraform-providers/terraform-provider-azurerm#10755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.28
+ provider.azurerm v2.44.0

### Affected Resource(s)

* `azurerm_private_endpoint`
* `azurerm_storage_account`

### Terraform Configuration Files

```hcl

resource "azurerm_resource_group" "example" {
  name     = "ausmlebugtest"
  location = "eastus2"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "endpoint" {
  name                 = "endpoint"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]

  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_storage_account" "example" {
  name                     = "bugtest2"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
}

resource "azurerm_private_endpoint" "example" {
  name                = "example-endpoint"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  subnet_id           = azurerm_subnet.endpoint.id

  private_service_connection {
    name                           = "example-privateserviceconnection"
    private_connection_resource_id = azurerm_storage_account.example.id
    is_manual_connection           = false
    subresource_names = ["blob"]
  }
}
```

### Debug Output

https://gist.github.com/mleziva/487263c6736b7b7e1f13901d7c2ed82d
### Expected Behaviour

Terraform refresh on storage account with a blob private endpoint should take the normal amount of time that it takes when running from any machine.

### Actual Behaviour
When running terraform refresh from an ubuntu machine in Azure with privatelink.blob.core.windows.net private dns linked to the vnet, refresh takes 5 minutes every time it is executed. 

### Steps to Reproduce

1. Create a VM in a vnet in Azure and add the privatelink.blob.core.windows.net private dns zone and link it to the vnet
2. Execute the above terraform code to deploy those resources to a separate resource group
3. After deployed successfully, execute terraform refresh and it will take 5 minutes to refresh

### Important Factoids

Only reproducible from Azure where a private dns already exists. If I create a private endpoint to the storage account in the VNET where I am executing the terraform and add that endpoint to the existing DNS with the appropriate a-record and IP address, the problem no longer occurs. 

If I remove the storage account from state, the problem no longer occurs.

I have tried the same thing with a file private endpoint and it did not take 5 minutes

It seems like from the terraform machine it is trying to manage the storage account blobs via the private endpoint and not able to resolve the resource and times out after 5 minutes

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @mleziva 

Thanks for opening this issue.

Unfortunately at this time Terraform doesn't support provisioning nested items within a Storage Account within a Private Endpoint - support for this is being tracked in various issues, so I've just consolidated this into #10765 so that there's a single place for it.

As mentioned in this issue, unfortunately support for this is blocked on the Azure API's - we're working with the teams at Microsoft to unblock this, but for the moment I'm going to consolidate this into #10765 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by mleziva** [comment]
Hi @tombuildsstuff ,

What do you mean by: _Terraform doesn't support provisioning nested items within a Storage Account within a Private Endpoint_? 

My understanding was that the code above is just provisioning a storage account and then provisioning a private endpoint for the blob access to that storage account, not creating any nested resources?

The issue is that the above code works fine if there is not an existing private DNS zone for blob storage, once there is a private DNS zone, it takes 5 minutes to refresh the storage account unless there is a private endpoint created for it available to the machine that is executing the terraform.

If the problem is with one of the storage account APIs, if you let me know which endpoints are being called, I can work with that team on resolving this issue.
