### ISSUE TITLE
azurerm_netapp_volume broken in 2.49 

### ISSUE THREAD

**Issue by nshores** [terraform-providers/terraform-provider-azurerm#10773]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_netapp_volume`

### Terraform Configuration Files

```hcl
resource "azurerm_netapp_volume" "netapp-volume-1" {
  lifecycle {
    prevent_destroy = false
  }

  name                  = var.volume_name_1
  account_name          = azurerm_netapp_account.netapp.name
  location              = "westus"
  resource_group_name   = var.resource_group_name
  pool_name             = azurerm_netapp_pool.netapp.name
  volume_path           = var.volume_path_1
  subnet_id             = var.subnet_id
  service_level         = var.service_level
  storage_quota_in_gb   = var.storage_quota_in_gb_1
}
```

### Debug Output

https://gist.github.com/nshores/5ecd47ddc351fff1030256e557596850

### Expected Behaviour
azurerm_netapp_volume should refresh state of current volumes.

### Actual Behaviour

Crash when refreshing state of volume. 

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Rolling back to 2.46.1 fixes the issue.

### References

#10610  appears to be the breaking change. @paulomarquesc

**Comment by paulomarquesc** [comment]
I'm looking into this.

**Comment by paulomarquesc** [comment]
@nshores , can you provide more details on what is being done? I could not reproduce your issue, steps I took was:

1. Perform an init, plan and apply to build up
2. Re-run plan after all was created and got no changes as result

This is the screenshot of running plan being executed the second time:

![image](https://user-images.githubusercontent.com/17993275/109710700-3b2d5880-7b5b-11eb-80fd-ec935628f738.png)

This is my testing TF code:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = var.location
}

resource "azurerm_virtual_network" "example" {
  name                = "${var.prefix}-virtualnetwork"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "${var.prefix}-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]

  delegation {
    name = "testdelegation"

    service_delegation {
      name    = "Microsoft.Netapp/volumes"
      actions = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    }
  }
}

resource "azurerm_netapp_account" "example" {
  name                = "${var.prefix}-netappaccount"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_netapp_pool" "example" {
  name                = "${var.prefix}-netapppool"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  account_name        = azurerm_netapp_account.example.name
  service_level       = "Standard"
  size_in_tb          = 4
}

resource "azurerm_netapp_volume" "example" {
  lifecycle {
    prevent_destroy = true
  }

  name                = "${var.prefix}-netappvolume"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  account_name        = azurerm_netapp_account.example.name
  pool_name           = azurerm_netapp_pool.example.name
  volume_path         = "${var.prefix}-netappvolume"
  service_level       = "Standard"
  protocols           = ["NFSv3"]
  subnet_id           = azurerm_subnet.example.id
  storage_quota_in_gb = 100
}

```

**Comment by paulomarquesc** [comment]
I was actually able to reproduce it, if using the same 2.49.0 it works fine, but I retried my steps using 2.48.0, then upgraded (init with -upgrade) to 2.49.0 and when executed the plan with the new version I could reproduce it.
