### ISSUE TITLE
New Log Analytics Workspace Sku (PerGB2018)

### ISSUE THREAD

**Issue by MattMencel** [terraform-providers/terraform-provider-azurerm#1078]
### Terraform Version
0.11.5

### Affected Resource(s)
- azurerm_log_analytics_workspace

### Terraform Configuration Files
```hcl
resource "azurerm_log_analytics_workspace" "law-demo" {
  name                = "demo-workspace-${random_id.workspace.hex}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.oms.name}"
  sku                 = "Free"
}
```

### Debug Output
https://gist.github.com/MattMencel/bc48429af5d1021756a9eb44f649d8c2

### Expected Behavior
Azure API accepts the Sku

### Actual Behavior
Azure API rejected the Skus currently documented in the API.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
On April 3rd, 2018 Microsoft changed the pricing tiers for Log Analytics.

https://azure.microsoft.com/en-us/blog/introducing-a-new-way-to-purchase-azure-monitoring-services/

I did some research and was able to find the new Sku name, `PerGB2018`.  This is not officially documented anywhere yet that I can find.  I successfully tested deployment using the new Sku.

I believe the old Skus will still work if you have an older Azure subscription and have deployed Log Analytics services prior to April 3, 2018.  I am unable to test this in my subscription.

### References
#1079

**Comment by Jakexx360** [comment]
Found this same issue - seems terraform refuses to use the working SKU you provided.

`Error: azurerm_log_analytics_workspace.test: expected sku to be one of [Free PerNode Premium Standalone Standard Unlimited], got PerGB2018`

**Comment by MattMencel** [comment]
@Jakexx360 It's in my PR.  I'm running a local copy of my terraform-provider-azurerm fork.

#1079 

I'm not sure, but it might be waiting on the PerGB2018 changes to appear in the Azure SDK.

**Comment by tombuildsstuff** [comment]
@metacpp whilst the Swaggers been fixed, would you be able to reach out to the service team about getting the API fixed here too? Due to this API change this service isn't usable - whereas other resources such as MySQL and Postgres will silently update the SKU as needed. Thanks!

**Comment by IronCore864** [comment]
If it's a dev env, as a temporary solution, you can put as "PerNode", which could at least create the cluster successfully.

**Comment by whytoe** [comment]
@metacpp This should be resolved now as Terraform is detecting the API setting now

```      sku:                   "pergb2018" => "Standard" (forces new resource)```

**Comment by katbyte** [comment]
Hi @whytoe,

I can't be entirely certain but it looks like from that snippet terraform is changing the `sku` from `pergb2018` (the one it doesn't know about) to `Standard ` (one it does)

**Comment by whytoe** [comment]
@katbyte you are correct but the Azure API is still returning that value, I thought the upstream Microsoft tag related to the Azure API not having that functionality

This is also a link to have i changed my old Terraform OMS from free to pergb2018

https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-usage-and-estimated-costs#new-pricing-model-and-operations-management-suite-subscription-entitlements
