### ISSUE TITLE
azurerm_storage_account allow_blob_public_access is an unsupported argument

### ISSUE THREAD

**Issue by pgr-jeremy-m** [terraform-providers/terraform-provider-azurerm#10794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 13.5
AzureRM: 2.49.0

### Affected Resource(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  min_tls_version = "TLS1_2"
  allow_blob_public_access = "false"

  tags = {
    environment = "staging"
  }
}
```

### Debug Output

Error: Unsupported argument

  on .terraform/modules/storage_bot/storage_account.tf line 15, in resource "azurerm_storage_account" "storage_account":
  15:   allow_blob_public_access = "false"

An argument named "allow_blob_public_access" is not expected here.

### Expected Behaviour

storage account should be created with "allow blob public access" set to false in portal.

### Actual Behaviour

See error above

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This is also occuring for min_tls_version.   I will open another issue for this if this one is found to be valid and updates are required. 

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#argument-reference

**Comment by ruandersMSFT** [comment]
@pgr-jeremy-m Are you receiving "An argument named ___ is not expected here", or "allow_blob_public_access" and "min_tls_version" are not supported for a Storage Account located in ____"?  

I ask as these two variables have a close "allowed" rule in the Terraform code base (my previous code change for USGov was on #9128).

I'll try a test myself to see if I can help with a quick code change here since I did the code change on USGov previously.

**Comment by pgr-jeremy-m** [comment]
Error: Unsupported argument

  on ../modules/storage.tf line 7, in resource "azurerm_storage_account" "example":
   7:   allow_public_blob_access = false

An argument named "allow_public_blob_access" is not expected here.

**Comment by ruandersMSFT** [comment]
allow_blob_public_access = "false"  (Correct)

vs.

allow_public_blob_access = false  (Incorrect)

**Comment by favoretti** [comment]
@pgr-jeremy-m Same guess here as in #10793 - Somehow you started using an older provider version. Would you be able to show your `required_versions` part of HCL or whichever method of provider version control you're using in your code please?

**Comment by pgr-jeremy-m** [comment]
@favoretti  you nailed it.  I have to AzureRM Providers and some how had different version constraints (copy paste issue on my end) and that was causing two versions to be installed:

Initializing provider plugins...
**- Finding hashicorp/azurerm versions matching "~> 2.1.0, ~> 2.0, ~> 2.0"...**
- Finding latest version of hashicorp/azuread...
- Finding latest version of hashicorp/vault...
- Finding latest version of -/vault...
- Finding latest version of -/azuread...
- Finding latest version of -/azurerm...
**- Installing -/azurerm v2.49.0...
- Installed -/azurerm v2.49.0 (signed by HashiCorp)
- Installing hashicorp/azurerm v2.1.0...
- Installed hashicorp/azurerm v2.1.0 (signed by HashiCorp)**
