### ISSUE TITLE
Unable to authenticate with SP in ADO

### ISSUE THREAD

**Issue by samhughes91** [terraform-providers/terraform-provider-azurerm#10790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl

terraform {
  backend "azurerm" {
  }
}

variable "subscription_id" {
}
variable "client_id" {
}
variable "client_secret" {
}
variable "tenant_id" {
}

provider "azurerm" {
  version = "=2.46.1"
   features {}
   
    subscription_id = var.subscription_id
    client_id       = var.client_id
    client_secret   = var.client_secret
    tenant_id       = var.tenant_id
}

data "terraform_remote_state" "remote-state-rg" {
  backend = "azurerm"
  config = {
    resource_group_name     = "rg-terraform-dev"
    storage_account_name    = "terraformstatefiles"
    container_name          = "tf-state"
    key                     = "resource-group.tfstate"
  }
}

resource "azurerm_storage_account" "vmtest-stdiag" {
  name                     = "savmtestdiag"
  resource_group_name      =  data.terraform_remote_state.remote-state-rg.outputs.rg 
  location                 = "westeurope"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}
```

### Expected Behaviour

Authenticate SP, run terraform plan and run terraform apply

### Actual Behaviour

Error: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:adal.tokenRefreshError{message:"adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS90002: Tenant 'tenantid' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\\r\\nTrace ID: 17b800e4-0da7-45bb-a238-abf11f0e1c00\\r\\nCorrelation ID: fda8925c-209d-42f0-b73d-1cd866647709\\r\\nTimestamp: 2021-03-02 15:05:27Z\",\"error_codes\":[90002],\"timestamp\":\"2021-03-02 15:05:27Z\",\"trace_id\":\"17b800e4-0da7-45bb-a238-abf11f0e1c00\",\"correlation_id\":\"fda8925c-209d-42f0-b73d-1cd866647709\",\"error_uri\":\"https://login.microsoftonline.com/error?code=90002\"} Endpoint https://login.microsoftonline.com/tenantId/oauth2/token?api-version=1.0", resp:(*http.Response)(0xc000e158c0)}, PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:400, Message:"Failed to refresh the Token for request to https://graph.windows.net/tenantId/servicePrincipals?%24filter=appId+eq+%27***%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc000e158c0)}

### Steps to Reproduce

In Azure DevOps:
```yml
    - task: AzureCLI@2
      displayName: TF init/plan
      inputs:
        azureSubscription: ${{ parameters.serviceconnection }}
        scriptLocation: inlineScript
        ScriptType: 'ps'
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform-isolation-file-layout/$(terraformcomponent)
        addSpnToEnvironment: true
        failOnStandardError: true
        inlineScript: |
            terraform version

            $subscriptionId = (az account show --query id)
            $servicePrincipalId = $env:servicePrincipalId
            $servicePrincipalKey = $env:servicePrincipalKey
            $tenantId = $env:tenantId

            $env:ARM_CLIENT_ID = $servicePrincipalId
            $env:ARM_CLIENT_SECRET = $servicePrincipalKey
            $env:ARM_TENANT_ID = $tenantId
            $env:ARM_SUBSCRIPTION_ID = $subscriptionId
            $env:ARM_ACCESS_KEY=$(az storage account keys list --resource-group "rg-sam-dev" --account-name "saterraformstateenv" --query '[0].value' -o tsv)

            az logout

            terraform.exe init `
              -input=false `
              -backend-config="storage_account_name=saterraformstateenv" `
              -backend-config="container_name=tf-state" `
              -backend-config="key=$(terraformcomponent).tfstate"

            terraform.exe plan `
              -var="client_id=$servicePrincipalId" `
              -var="client_secret=$servicePrincipalKey" `
              -var="tenant_id=tenantId" `
              -var="subscription_id=$(subscriptionId)" `
              -out $(Build.Buildnumber)${{ parameters.env }}.tfplan

```

### Important Factoids

I need to authenticate with Service Principal for data "terraform_remote_state"

### References

* #0000

**Comment by nnellans-acts** [comment]
What happens if you remove `az logout` from your inlineScript?

**Comment by favoretti** [comment]
Next to what @nnellans-acts said, have a look at https://github.com/charleszipp/azure-pipelines-tasks-terraform - it's free and available from AzDO marketplace, it will significantly reduce the toil to run Terraform from AzDO.

**Comment by favoretti** [comment]
@samhughes91 Thank you for reporting this, but since this isn't a provider issue, I'm going to close it. Please feel free to get back to us if anything doesn't work with the provider itself. A good place to talk about general usage of Terraform is [HashiCorp Forums](https://discuss.hashicorp.com/).

**Comment by samhughes91** [comment]
First of all a big thanks is in order. I've been able to modify the script and I now have it working! The tenant_id was indeed an issue, I also removed the `az logout`  and modified my .tf file see snippet:

````hcl
terraform {
  backend "azurerm" {
      # resource_group_name     = "rg-sam-dev"
      # storage_account_name    = "saterraformstateenv"
      # container_name          = "tf-state"
      # key                     = "storage-account.tfstate"
  }
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.46.0"
    }
  }
}

variable "subscription_id" {
}
variable "client_id" {
}
variable "client_secret" {
}
variable "tenant_id" {
}

provider "azurerm" {
  features {}
    subscription_id = var.subscription_id
    client_id       = var.client_id
    client_secret   = var.client_secret
    tenant_id       = var.tenant_id
}

````

> Furthermore, the AzureRM provider can automatically pick up on the ARM_ environment variables. If you wanted you could remove the configuration from the provider block and let the environment variables take over. You could then remove the -var switches on `terraform plan` as well.

I did try your suggestion, setting the the env variables as suggested and removing the -var flags and var references from my tf file. Unfortunately this still gave me the error message as stated in my original post. 

@favoretti Thank you for the pointing out https://github.com/charleszipp/azure-pipelines-tasks-terraform. To be honest I stopped using this task due to all the error messages I was running into. The AzureCLI task gave me a little extra to play around with. When I get round to code refactoring I will give it another shot. 

Cheers guys :)

**Comment by favoretti** [comment]
@samhughes91 If you want - beam me up on slack, I can give you pipeline templates for that extension that we're using.

**Comment by favoretti** [comment]
@samhughes91 In your case since you're configuring provider with `var.client_id` and `var.client_secret` you can override those as `TF_VAR_client_id` and `TF_VAR_cliend_secret` environment variables. If you remove those from the configuration provider will pick up `ARM_*` env vars.
