### ISSUE TITLE
A managed Resource "Azurerm_public_Ip" "example" has not been declared in the root module

### ISSUE THREAD

**Issue by Johno420** [terraform-providers/terraform-provider-azurerm#10808]
Trying to create an Azure Virtual Network Gateway to connect to a ExpressRoute Circuit, 
below are the codes, 

resource "azurerm_public_ip" "example" {
  name                = "PIP-EXPR-example${var.EXPR_environment}-AUSEAST-01"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"

  allocation_method = "Dynamic"
  
}

resource "azurerm_virtual_network_gateway" "example" {
  name                = "VNGW-${var.example_environment}-AUSE-01"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"

  type     = "ExpressRoute"
  sku      = "Standard"
  
  ip_configuration {
    name                          = "EXPRVNNWGConfig"
    public_ip_address_id          = "${azurerm_public_ip.example.id}"
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = "${azurerm_subnet.GATEWAY.id}"
  }
}

I am getting error, 

A managed resource "azurerm_public_ip" "VNWG" has not been declared in the root module. 

?? help. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Johno420 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
