### ISSUE TITLE
Updating azurerm_subnet with ipv6 does not change the subnet to dual stack

### ISSUE THREAD

**Issue by thejohnbackes** [terraform-providers/terraform-provider-azurerm#10818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.21.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource azurerm_resource_group "add-ipv6-to-subnet" {
    name = "add-ipv6-to-subnet"
    location = "eastus"
}

resource azurerm_virtual_network "add-ipv6-to-subnet" {
    name = "add-ipv6-to-subnet"
    resource_group_name = azurerm_resource_group.add-ipv6-to-subnet.name
    location = azurerm_resource_group.add-ipv6-to-subnet.location

    address_space = [
        "10.0.0.0/8",
        "2a05:f500::/56"
    ]
}

resource azurerm_subnet "add-ipv6-to-subnet" {
    name = "add-ipv6-to-subnet"
    virtual_network_name = azurerm_virtual_network.add-ipv6-to-subnet.name
    resource_group_name = azurerm_virtual_network.add-ipv6-to-subnet.resource_group_name

    # create with ipv4 only:
    # address_prefixes = ["10.0.0.0/16"]

    # update with ipv4 + ipv6:
    address_prefixes = ["10.0.0.0/16", "2a05:f500::/64"]
}
```

### Debug Output

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_subnet.add-ipv6-to-subnet will be updated in-place
  ~ resource "azurerm_subnet" "add-ipv6-to-subnet" {
      ~ address_prefixes                               = [
            "10.0.0.0/16",
          + "2a05:f500::/64",
        ]
        id                                             = "/subscriptions/XXXXXXXXXXXXX/resourceGroups/add-ipv6-to-subnet/providers/Microsoft.Network/virtualNetworks/add-ipv6-to-subnet/subnets/add-ipv6-to-subnet"
        name                                           = "add-ipv6-to-subnet"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_subnet.add-ipv6-to-subnet: Modifying... [...]
azurerm_subnet.add-ipv6-to-subnet: Modifications complete after 1s [...]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.

✗ terraform state show azurerm_subnet.add-ipv6-to-subnet
# azurerm_subnet.add-ipv6-to-subnet:
resource "azurerm_subnet" "add-ipv6-to-subnet" {
    address_prefix                                 = "10.0.0.0/16"
    address_prefixes                               = [
        "10.0.0.0/16",      # <--- where's the ipv6 address prefix?
    ]
    ...
}
```

### Expected Behaviour

Update existing subnet with new IPv6 range.

### Actual Behaviour

Apply completes successfully, but IPv6 range is not added.

### Steps to Reproduce

1. `terraform apply`
2. Uncomment the "address_prefixes" line with two subnets. Comment the "address_prefixes" line with one subnet.
3. `terraform apply`

### References

These lines seem to be to blame:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/fce3efa75eb952c34a067471f2ca9d468e25360a/azurerm/internal/services/network/subnet_resource.go#L285

**Comment by magodo** [comment]
This is caused by setting both `addressPrefixes` (two items) and `addressPrefix` (one item) in the request, in which case the service get confused and current behavior is only takes the `addressPrefix` into consideration.
In this case, meaning updating the amount of prefixes from 1 to N, we should ensure we only set the `addressPrefixes` and clear the `addressPrefix`.
