### ISSUE TITLE
azurerm_kusto_eventhub_data_connection requires too many arguments

### ISSUE THREAD

**Issue by oliverchristen** [terraform-providers/terraform-provider-azurerm#10838]
This is a copy of issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/10409 which has been closed without a reason.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
provider registry.terraform.io/hashicorp/azurerm v2.45.1

### Affected Resource(s)

* `azurerm_kusto_eventhub_data_connection`

### Terraform Configuration Files

```hcl
resource "azurerm_kusto_eventhub_data_connection" "eventhub_connection" {
  name                = "conn-eventhubtodataexplorer"
  resource_group_name = "rg-01"
  location            = "West Europe"
  cluster_name        = "my-azure-data-explorer-cluster"
  database_name       = "my-adx-database"

  eventhub_id    = "<id of the event hub>"
  consumer_group = "myConsumerGroup"

  # table_name        = "" this argument is not required
  mapping_rule_name = "Json_Mapping"
  data_format       = "MULTIJSON"
}
```

### Expected Behaviour

terraform apply should run successfully because only mapping_rule_name is a required argument. table_name and data_format are optional.

### Actual Behaviour

Error: if one of the target table properties table_name, mapping_rule_name or data_format are set, the other values must also be defined

### Steps to Reproduce

Configure kusto_eventhub_data_connection as on: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_eventhub_data_connection
but without table_name argument.
`terraform apply`

**Comment by favoretti** [comment]
@oliverchristen Hi there. Thank you for reporting this. Can you help me understand the added value of creating an unbound mapping? Also, can you create a data connection without specifying table name through the portal? Currently azurerm provider indeed expect either none or all three. I'd be happy to change that behavior if you could help me understand the rationale and viability.

**Comment by oliverchristen** [comment]
Hi @favoretti. Thank you very much for your immediate response!

I assume you did notice the previous [issue ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10409). You're right, that's not so obvious. I want to leave `table_name` empty because it is filled automatically by a event system property called `Table` which is described [here](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub-overview#ingestion-properties) The same would be possible for `mapping_rule_name` and `data_format`. This approach makes it possible to set those properties dynamically. E.g. ingest data dynamically to different tables.

Yes, it is possible to create a data connection without specifying table name through the portal. I demonstrated it [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10409#issuecomment-783499003)

I hope I have helped you to understand my goal and why this is kind of a bug.

**Comment by favoretti** [comment]
@oliverchristen thank you, this is super helpful. I’ll spend some time early next week to run a few tests and if Azure API allows for it - I’ll submit a PR that will lift the limitations in the code for the review of maintainers.

**Comment by oliverchristen** [comment]
@favoretti that would be great! Thank you!

**Comment by oliverchristen** [comment]
@favoretti that was ultra fast! Thank you.

**Comment by favoretti** [comment]
@oliverchristen My pleasure. :)
