### ISSUE TITLE
Support for Parquet Datasets in Azure Data Factory

### ISSUE THREAD

**Issue by ScoGroMSFT** [terraform-providers/terraform-provider-azurerm#10847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Since Parquet is a very common format and is available in Azure Data Factory, it seems like something that should be available via the Terraform provider but it isn't. 

I was attempting to do a simple pipeline to transform data from CSV to Parquet but found that there is not direct support for Parquet data sources. 

I was able to get a workaround functioning by using a regular azurerm_data_factory_dataset_azure_blob and then invoking the RM REST API to add a format tag to specify Parquet. This worked to convert the CSV to Parquet in my example. I attempted to specify this via the built-in fields, like additional_properties but none seemed to work to get the desired behavior. 

Note: This workaround provisions a blob dataset that uses Parquet formatting, not a native Parquette dataset. The latter allows selection of which compression algorithm to use.

https://github.com/ScoGroMSFT/examples/blob/dfe62e813d8b568eed7fdeac5485e62bee5ed050/adf-terraform/data_factory.tf#L48

### New or Affected Resource(s)

azurerm_data_factory_dataset_parquet

### Potential Terraform Configuration

```json
resource "azurerm_data_factory_dataset_parquet" "parquetdataset" {
  name                = "parquetdataset"
  resource_group_name = azurerm_resource_group.rg.name
  data_factory_name   = azurerm_data_factory.datafactory.name
  linked_service_name = azurerm_data_factory_linked_service_azure_blob_storage.parquetlinkedservice.name

  azure_blob_storage_location {
    container = azurerm_storage_blob.parquetblob.storage_container_name
    path     = "/"
    filename = azurerm_storage_blob.parquetblob.name
  }
  compression_algorithm = "snappy" | "lz0" | "gzip" | "none" (optional - defaults to the type's default of snappy)
}

```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

This line uses the Azure RM REST API to change the resource type from a blob to a parquet data, which appears as one would expect in the ADF UI:
![image](https://user-images.githubusercontent.com/49792089/110037881-e07b3480-7cf3-11eb-93cb-42147bc24ee7.png)

* #0000

**Comment by favoretti** [comment]
Hi @ScoGroMSFT, thank you for reporting this. I've submitted a PR implementing this resource.
