### ISSUE TITLE
Support for Service Bus Topic and Queue Data Sources

### ISSUE THREAD

**Issue by TylerHaigh** [terraform-providers/terraform-provider-azurerm#10845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like a way to refer to a Service Bus Topic or Queue as a Data Source

### New or Affected Resource(s)

* azurerm_servicebus_topic
* azurerm_servicebus_queue

### Potential Terraform Configuration

```hcl
data "azurerm_servicebus_topic" "example" {
  name                = "tfex_servicebus_topic"
  namespace_name      = "tfex-servicebus-namespace"
  resource_group_name = "terraform-servicebus"
}

data "azurerm_servicebus_queue" "example" {
  name                = "tfex_servicebus_queue"
  namespace_name      = "tfex-servicebus-namespace"
  resource_group_name = "terraform-servicebus"
}
```

**Comment by tombuildsstuff** [comment]
Fixed via #10985
