### ISSUE TITLE
Express Route Circuit (Microsoft Peering) Missing Arguments.

### ISSUE THREAD

**Issue by rafael6** [terraform-providers/terraform-provider-azurerm#1084]
### Terraform Version
0.11.6

### Affected Resource(s)
express_route_circuit_pering (Microsoft Peering)

### Terraform Configuration Files
```
resource "azurerm_express_route_circuit_peering" "test" {
  peering_type                  = "MicrosoftPeering"
  express_route_circuit_name    = "${azurerm_express_route_circuit.test.name}"
  resource_group_name           = "${azurerm_resource_group.test.name}"
  peer_asn                      = 100
  primary_peer_address_prefix   = "123.0.0.0/30"
  secondary_peer_address_prefix = "123.0.0.4/30"
  vlan_id                       = 300

  microsoft_peering_config {
    advertised_public_prefixes = ["123.1.0.0/24"]
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Support for the following arguments related to Azurerm Express Route Circuit Peering (Microsoft Peering):

-PeerAddressType
-MicrosoftConfigCustomerAsn
-MicrosoftConfigRoutingRegistryName

https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-routing-arm#next-steps

### Actual Behavior
I don't see documentation or support for the following Azurerm Express Route Circuit Peering (Microsoft Peering) arguments:

-PeerAddressType
-MicrosoftConfigCustomerAsn
-MicrosoftConfigRoutingRegistryName

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
 Below is a powershell script with PeerAddressType, MicrosoftConfigCustomerAsn, and MicrosoftConfigRoutingRegistryName arguments:

Add-AzureRmExpressRouteCircuitPeeringConfig 
-Name "MicrosoftPeering" 
-ExpressRouteCircuit $ckt 
-PeeringType MicrosoftPeering 
-PeerASN 100 
-PeerAddressType IPv4 
-PrimaryPeerAddressPrefix "123.0.0.0/30" 
-SecondaryPeerAddressPrefix "123.0.0.4/30" 
-VlanId 300 
-MicrosoftConfigAdvertisedPublicPrefixes "123.1.0.0/24" 
-MicrosoftConfigCustomerAsn 23 
-MicrosoftConfigRoutingRegistryName "ARIN"

https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-routing-arm#next-steps

**Comment by mashbynz** [comment]
This is still an issue. 
```
Terraform v0.12.5
```
Currently unable to configure peerings as I receive the following error message:
```
Error: network.ExpressRouteCircuitPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ExpressRouteMicrosoftPeeringConfigIncomplete" Message="The Express Route Microsoft Peering /subscriptions/ef3df766-183a-45cd-aa69-xxxxxx/resourceGroups/prodsharedservices1-rg/providers/Microsoft.Network/expressRouteCircuits/prodsharedservices1-ergw/peerings/MicrosoftPeering config for Protocol Ipv4 is incomplete.." Details=[]
```

if the `microsoft_config_routing_registry_name` parameter as part of the `microsoft_peering_config` block is not completed. This parameter is unable to be enetered as terraform does not recognise the parameter.

**Comment by pearcec** [comment]
So looks like the following are missing?  I will take a look at adding them.
-MicrosoftConfigCustomerAsn 23
-MicrosoftConfigRoutingRegistryName "ARIN"
