### ISSUE TITLE
v2.50.0 Invalid address error with azurerm_monitor_action_group datasource 

### ISSUE THREAD

**Issue by uncycler** [terraform-providers/terraform-provider-azurerm#10854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.50.0
```
### Affected Resource(s)

* `data.azurerm_monitor_action_group`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_action_group" "myaction" {
  name                = "myaction"
  resource_group_name = "myrg"
  short_name          = "myaction"

  webhook_receiver {
    name                    = "mywebhook"
    service_uri             = "https://webhoook.com"
    use_common_alert_schema = true
  }
}

##########

data "azurerm_monitor_action_group" "myaction" {
  resource_group_name = "myrg"
  name = "myaction"
}
```

### Expected Behaviour

No error message

### Actual Behaviour

```
Error: Error setting `webhook_receiver`: Invalid address to set: []string{"webhook_receiver", "0", "aad_auth"}
```

### Steps to Reproduce

Execute `terraform apply` with a datasource `azurerm_monitor_action_group` as shown.

### Important Factoids

It works as expected with version 2.49.0 and earlier.

### References

It seems related to #10509

**Comment by alastairtree** [comment]
FYI @yupwei68

**Comment by jabba2324** [comment]
Whats the status of this ticket?
