### ISSUE TITLE
Error making Read request on Azure PostgreSQL Configuration backslash_quote

### ISSUE THREAD

**Issue by dkirrane** [terraform-providers/terraform-provider-azurerm#10855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/aiven/aiven v2.1.6
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.49.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/time v0.7.0

### Affected Resource(s)

* `azurerm v2.49.0`

### Terraform Configuration Files

Its a postgres module with 
```hcl
resource "azurerm_resource_group" "example" {
  name     = "api-rg-pro"
  location = "West Europe"
}

resource "azurerm_postgresql_server" "example" {
  name                = "postgresql-server-1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku_name = "B_Gen5_2"

  storage_mb                   = 5120
  backup_retention_days        = 7
  geo_redundant_backup_enabled = false
  auto_grow_enabled            = true

  administrator_login          = "psqladminun"
  administrator_login_password = "H@Sh1CoR3!"
  version                      = "9.5"
  ssl_enforcement_enabled      = true
}

resource "azurerm_postgresql_database" "example" {
  name                = "exampledb"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_postgresql_server.example.name
  charset             = "UTF8"
  collation           = "English_United States.1252"
}

resource "azurerm_postgresql_configuration" "example" {
  name                = "backslash_quote"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_postgresql_server.example.name
  value               = "on"
}
```

### Expected Behaviour

No failure.

### Actual Behaviour

```
Error: Error making Read request on Azure PostgreSQL Configuration backslash_quote: postgresql.ConfigurationsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ResourceNotFound" Message="The requested resource does not exist"
```

### Steps to Reproduce

Plan run on Terraform Cloud.

### References

* #0000

**Comment by aristosvo** [comment]
I believe this one is fixed [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10754)

@WodansSon should we add this to the release notes as well?

**Comment by katbyte** [comment]
@dkirrane - looks like this has been fixed so i'm going to close it, do reopen an issue if its still a problem!
