### ISSUE TITLE
Support for mutable rolling upgrade properties

### ISSUE THREAD

**Issue by IamBread** [terraform-providers/terraform-provider-azurerm#10851]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Turning on rolling upgrade policy for linux virtual machine scale set requires a **rolling_upgrade_policy**.  The block has the following properties:

- max_batch_instance_percent
- max_batch_instance_percent
- max_unhealthy_instance_percent
- max_unhealthy_upgraded_instance_percent
- pause_time_between_batches 

Currently, these properties are immutable, as far as the Terraform provider is concerned. 
Each property change forces the resource to be recreated, which is not the behaviour when altering values through web UI or Azure cli. 

Feature request is that these field do not force recreate on the entire scale set.

### New or Affected Resource(s)

azurerm_linux_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl

rolling_upgrade_policy {
      max_batch_instance_percent                         = ceil((1/var.some_int) * 100)
      max_unhealthy_instance_percent                  = ceil((1/var.some_int) * 100)
      max_unhealthy_upgraded_instance_percent = ceil((1/var.some_int) * 100)
      pause_time_between_batches                       = "PT15S"
    }

```

outputs:

 ~ rolling_upgrade_policy {
          ~ max_batch_instance_percent              = 10 -> 50 # forces replacement
          ~ max_unhealthy_instance_percent          = 100 -> 50 # forces replacement
          ~ max_unhealthy_upgraded_instance_percent = 100 -> 50 # forces replacement
          ~ pause_time_between_batches              = "PT10S" -> "PT12S" # forces replacement
        }

### References

[Documentation on rolling upgrade policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set#rolling_upgrade_policy)

**Comment by favoretti** [comment]
Hi @IamBread, thank you for reporting this. Would you be able to share full HCL test case? This would help me run some tests and potentially fix this quicker if API indeed supports updating those properties.

**Comment by IamBread** [comment]
Hi @favoretti, thanks for the quick update. 
You can use the sample, provided [here](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/vm-scale-set/virtual_machine_scale_set/automatic-rolling-updates).
Test case would be to change any of [these values](https://github.com/terraform-providers/terraform-provider-azurerm/blob/5c4323adacf476aa598667f502d0829a51f8eb24/examples/vm-scale-set/virtual_machine_scale_set/automatic-rolling-updates/main.tf#L82-L85).

**Comment by favoretti** [comment]
Hi @IamBread.

Ok, there are a few things at play here.
1. `azurerm_virtual_machine_scale_set` is a deprecated resource, I would discourage you from using it. Instead I suggest you choose one of `azurerm_linux_virtual_machine_scale_set` or `azurerm_windows_virtual_machine_scale_set`, whichever suits your purpose. Examples for linux can be found [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/5c4323adacf476aa598667f502d0829a51f8eb24/examples/vm-scale-set/linux/rolling-upgrade-policy/main.tf).
2. Resources I recommend also force recreation on policy change, but I just ran a test and that's unwarranted, they can be updated, therefore I'll shoot in a PR to fix this momentarily.

Thanks again for bringing this to our attention.

**Comment by mleziva** [comment]
To add on to this, _health_probe_id_ is also immutable through Terraform but can be changed without recreation through the Azure portal.

**Comment by IamBread** [comment]
Hi @favoretti, thank you so much for the fast update. We're indeed using the linux_virtual_machine_scale_set, but i figured this would affect all scale sets,  linux or windows. 
When can we expect a version with this patch?

**Comment by favoretti** [comment]
@mleziva thank you for this. I updated my PR to include that as well.

@IamBread if maintainers will be able to review this before next Thursday this will ship as part of `2.51.0`, but I don't have influence on their working schedules :) 🤞🏻 with a bit of luck - next week thus.
