### ISSUE TITLE
PostgreSQL provider doesn't seem to support Azure AD users

### ISSUE THREAD

**Issue by waynejnicklin** [terraform-providers/terraform-provider-azurerm#10877]
I can successfully add an Azure AD user as PostgreSQL admin, but when I try and connect to the PostgreSQL server using the same user (to add SQL roles etc.), I get the following error:

Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: An error occurred while validating the access token. Please acquire a new token and retry

Do I have to do something different with the Terraform provider to use an Azure AD user? Here is my config:

provider "postgresql" {
    host            = var.sql_server
    port            = 5432
    database        = var.service_name
    username        = var.sql_username
    password        = var.sql_password
    sslmode         = "require"
    superuser       = false
    connect_timeout = 15
}

Thanks,
Wayne

**Comment by jackofallops** [comment]
Hi @waynejnicklin - this is the repository for the Azure RM provider. We don't support a postgres provider here, but if the provider you're using published on the registry, you can possibly reach that provider's developer through the project links there? https://registry.terraform.io/search/providers?q=postgres

Since this is a question on another provider I'm going to close this issue.

**Comment by waynejnicklin** [comment]
The provider I'm assuming is the hashicorp one. If I try and create an issue there it says the archive is closed and read-only.

https://github.com/hashicorp/terraform-provider-postgresql

terraform {
    required_providers {
        postgresql = {
            source = "terraform-providers/postgresql"
        }
    }
}

**Comment by jackofallops** [comment]
Hi @waynejnicklin - That's an archived provider from a time when all providers were held in our GitHub Org.  There's a note on that repo directing you to the owner and maintainer's Github project, they may be able to assist: https://registry.terraform.io/providers/cyrilgdn/postgresql / https://github.com/cyrilgdn/terraform-provider-postgresql

**Comment by waynejnicklin** [comment]
Great thank you :-)
