### ISSUE TITLE
Support for Azure App Registration Logo

### ISSUE THREAD

**Issue by thecodetinker** [terraform-providers/terraform-provider-azurerm#10889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a Terraform user I would like the ability to configure a Logo on an App Registration for branding purposes. Currently this is possible via PowerShell, but obviously would be great to set this in Terraform.

https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureadapplicationlogo?view=azureadps-2.0

### New or Affected Resource(s)

* azuread_application

### Potential Terraform Configuration

```hcl
resource "azuread_application" "example" {
  name = "MyApp"
  logo = "./logo.png" # or maybe filebase64("./logo.png") depending on implementation
}
```

### References

* #0000

**Comment by favoretti** [comment]
Hi there, thank you for reporting this. `azuread_*` resources aren't a part of `azurerm` provider, but rather part of `azuread` [found here](https://github.com/hashicorp/terraform-provider-azuread).

I'm going to close this one since I can't migrate it, but would appreciate it a lot if you could raise this issue in the corresponding repo.

**Comment by thecodetinker** [comment]
D'oh, yes of course it is, sorry. I've raised https://github.com/hashicorp/terraform-provider-azuread/issues/418 for this now. Thank you!
