### ISSUE TITLE
azurerm_local_network_gateway - make address_space argument optional

### ISSUE THREAD

**Issue by K-RON25** [terraform-providers/terraform-provider-azurerm#10891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If possible, i would like the ability to create local network gateways without address spaces. Address spaces can be removed in the azure UI and are not required when using bgp peering. Currently we have to setup local network gateways and then remove the address spaces afterwards via the UI. Maybe it can be created with an empty list of address spaces?

### Affected Resource(s)

* `azurerm_local_network_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_local_network_gateway" "home" {
  name                = "backHome"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  gateway_address     = "12.13.14.15"
}
```

* #0000

**Comment by jackofallops** [comment]
closed by #10983
