### ISSUE TITLE
Resource group name change results in complete destruction of resources

### ISSUE THREAD

**Issue by samirageb** [terraform-providers/terraform-provider-azurerm#109]
### Affected Resource(s)
- azurerm_resource_group
- Appears to be any resources within the resource group (confirmed with VM, NIC, PIP, LB)

### Expected Behavior
- New resource group created (or err if existing)
- Resources migrated to new Rg
- Remove Rg

There should be no need to destroy these resources for a simple move between RGs.

### Actual Behavior
All resources in Rg destroyed, then Rg recreated, then all resources recreated

### Steps to Reproduce
1. `terraform apply` on any config where you change the Rg name with resources inside

### Important Factoids
None

### References
None

**Comment by achandmsft** [comment]
Hi @samirageb, Thanks for reporting this interesting requirement. The semantic of a resource group in Azure is as a hard environment, that is immutable, not a metadata reference pointer to switch/migrate resources from one to the other. 

It is also the fundamental unit on which actions can be taken together using the Resource Manager. For treating groups of resources in the softer way you need for your scenario, the best way to do that would be to use Azure Tags with the same name when creating multiple resources. This is a soft environment, then all you would need to do is delete and add new tags to "move" them from one environment to another.  This is our best practice recommendation for any lightweight logical organization as described [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags).

As this issue has been open for a while, and is not fixable without fundamental changes to Azure platform architecture, or hacks in the provider, I am closing the same. If this is still blocking you in your scenario and the above workaround is inadequate, please open an issue with the scenario you are trying to use this in, and we will try and address the same as best we can. 

Hope this helps. 

Thanks,
Arun Chandrasekhar
Principal Program Manager - Azure OSS Integrations
[https://twitter.com/rcarunmsft](https://twitter.com/rcarunmsft)

**Comment by samirageb** [comment]
Thank you for the response @achandmsft. I've since managed to find some workarounds that work.
