### ISSUE TITLE
Error: decoding certificate ("xyz"): pkcs12: expected exactly two safe bags in the PFX PDU

### ISSUE THREAD

**Issue by hazzik** [terraform-providers/terraform-provider-azurerm#10909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_key_vault_certificate_data`

### Terraform Configuration Files

```hcl
data "azurerm_key_vault" "xxx" {
  name                = "xxx" 
  resource_group_name = "mygroup"
}

data "azurerm_key_vault_certificate_data" "xyz" {
  name         = "xyz"
  key_vault_id = data.azurerm_key_vault.xxx.id
}
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by 4x0v7** [comment]
Also experiencing this issue

**Comment by markbangert** [comment]
I have the same issue. Same provider version...

**Comment by Extant-1** [comment]
Experiencing this issue with provider 2.54.0.

It is caused when the pfx that is uploaded to the key vault contains more than one public certificate. For example if it contains an intermediate and/or root certificate as well.
