### ISSUE TITLE
Support for creating subscriptions straight into management group

### ISSUE THREAD

**Issue by matt-garner-nw** [terraform-providers/terraform-provider-azurerm#10912]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is possible to create Azure Subscription (Alias) straight into a Management Group, as part of Enterprise Scale deployments using ARM Templates. This speeds up Subscription Vending and avoids any "Management Group Cache" issues found when trying to deploy resources inherited from management groups onto new Subscriptions, such as Custom Roles or assigning Policy Definitions.

### New or Affected Resource(s)

* azurerm_subscription

### Potential Terraform Configuration

```hcl
resource "azurerm_subscription" "example" {
  subscription_name = "My Example EA Subscription"
  billing_scope_id  = data.azurerm_billing_enrollment_account_scope.example.id
  management_group_id = data.azurerm_management_group.example.id
}
```

### References

Please see the official Enterprise-Scale ARM template here that shows the functionality:

https://github.com/Azure/Enterprise-Scale/blob/main/examples/landing-zones/empty-subscription/emptySubscription.json

* #0000

**Comment by tombuildsstuff** [comment]
hey @matt-garner-nw 

Thanks for opening this issue.

Taking a quick look into this one it appears that support for this isn't available in the Azure SDK at this time, since there's no ManagementGroupID field exposed within the SDK:

<img width="974" alt="Screenshot 2021-03-10 at 10 25 46" src="https://user-images.githubusercontent.com/666005/110606925-fb81f480-818a-11eb-97fd-f31598f54d77.png">

As such we'd need to wait for this functionality to become available in the Azure SDK before we can support it unfortunately - so I'll mark this as "blocked on the Azure SDK" for the moment.

Thanks!

**Comment by jackofallops** [comment]
Hi @matt-garner-nw - I plan to investigate creating an association resource to permit Subscriptions to be assigned to management groups. Tom is correct in that there's no direct support to do as you request, and in my conversations with the Service team at Azure responsible for this there's been no indication that such functionality is being considered.  

I'd welcome feedback on this idea, so if you feel it would / wouldn't meet your use case do let us know.

**Comment by matt-garner-nw** [comment]
Hi @jackofallops, I think this will be a great interim until the SDK can support it so we can do the full subscription vending process in Terraform, although I'm not sure this would fix the cache issue I sometimes get.

**Comment by jackofallops** [comment]
Hi @matt-garner-nw - In looking into this, I've realised support already exists in the provider to manage this.  The `azurerm_management_group` resource accepts a list of Subscription ID's, which should be able to consume a list of `azurerm_subscription.subscription_id`  to achieve what you need without an additional resource? 

* Note: `azurerm_subscription.id` is the Alias ID, and won't work, unfortunately this is how we needed to track this resource in the state, as that's the service we have to use to create Subscriptions.

**Comment by matt-garner-nw** [comment]
Hi @jackofallops, I've seen that resource before. I geuss it's easy to use if all your subs are in the same state file. But we have one file per sub and using this would mean having another statefile just for managing the management group. It's bit over complicated whereas an association resource would not need to know about all the other subs and we can keep it in the same state file as the subscription.

**Comment by donwlewis** [comment]
@jackofallops I would like to see a resource for associating management group to subscriptions.  In our case, the code creating the subscription won't necessarily be managing the subscriptions, so being able to lookup the management group, and then associate it to the subscriptions would be awesome.
