### ISSUE TITLE
azurerm_redis_enterprise_cluster resource is not exporting the 'hostname' attribute

### ISSUE THREAD

**Issue by dashaun** [terraform-providers/terraform-provider-azurerm#10925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Verified with versions:
- 0.14.1
- 0.14.7
- 0.14.8

### Affected Resource(s)

* `azurerm_redis_enterprise_cluster`

### Terraform Configuration Files

outputs.tf
```
locals {
  redisgeek_config = {
    cluster = azurerm_redis_enterprise_cluster.redisgeek.*
    database = azurerm_redis_enterprise_database.redisgeek.*
  }
}

output "redisgeek_config" {
  value = jsonencode(local.redisgeek_config)
  sensitive = false
}
```

### Debug Output

Output (not debug):
```
redisgeek_config = {
  "cluster" = [
    {
      "hostname" = ""
      "id" = "/subscriptions/xxx/resourceGroups/redisgeek-RCea/providers/Microsoft.Cache/redisEnterprise/redisgeek-j9xf"
      "location" = "eastus"
      "name" = "redisgeek-j9xf"
      "resource_group_name" = "redisgeek-RCea"
      "sku_name" = "Enterprise_E10-2"
      "tags" = tomap({})
      "timeouts" = null /* object */
      "version" = ""
      "zones" = tolist([
        "1",
        "2",
        "3",
      ])
    },
  ]
  "database" = [
    {
      "client_protocol" = "Encrypted"
      "cluster_id" = "/subscriptions/xxx/resourceGroups/redisgeek-RCea/providers/Microsoft.Cache/redisEnterprise/redisgeek-j9xf"
      "clustering_policy" = "EnterpriseCluster"
      "eviction_policy" = "VolatileLRU"
      "id" = "/subscriptions/xxx/resourceGroups/redisgeek-RCea/providers/Microsoft.Cache/redisEnterprise/redisgeek-j9xf/databases/default"
      "module" = tolist([])
      "name" = "default"
      "port" = 10000
      "resource_group_name" = "redisgeek-RCea"
      "timeouts" = null /* object */
    },
  ]
}
```

### Panic Output
NA
### Expected Behaviour

According to the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_enterprise_cluster#attributes-reference):

```
hostname - DNS name of the cluster endpoint.
```

### Actual Behaviour

hostname value is an empty string

### Steps to Reproduce

[Example repository](https://github.com/redisgeek/acre-terraform-simple).

1. `terraform apply`
2. `terraform output`

### Important Factoids

None.

### References

None.

**Comment by favoretti** [comment]
Hi and thank you for reporting this. I'll try to have a look at this in the next couple of days. One remark though, switching terraform versions will have no influence on provider capabilities, only switching provider versions will :)

**Comment by WodansSon** [comment]
Unfortunately, this is a known bug with the API. I will open a PR to deprecate these fields temporarily as a heads up until the service team begins to support them. Feel free to close this issue or ask any further questions you may have. Thanks for opening the issue!

**Comment by dashaun** [comment]
Thank you!
