### ISSUE TITLE
azurerm_function_app: functionAppScaleLimit is missing from site_config

### ISSUE THREAD

**Issue by booyaa** [terraform-providers/terraform-provider-azurerm#10933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This parameter controls how many instances should be spawned by the function app.

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_function_app" "example" {
  name                       = "test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key

  # new item in site_config object
  site_config {
    function_app_scale_limit = 3
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/azure-functions/event-driven-scaling#limit-scale-out - note this replaces the app setting config as the preferred way to configure this feature
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_max_dynamic_application_scale_out - original method of configuring this feature

* #0000

**Comment by booyaa** [comment]
I'd like to pick this up

**Comment by jackofallops** [comment]
> I'd like to pick this up

Thanks for volunteering to take a look @booyaa - just be mindful that the `site_config` schema is shared with the `azurerm_function_app_slot` resource also, so this may be a bigger change than it first appears on the surface.
