### ISSUE TITLE
account_kind StorageV2 not recognised by azurerm_storage_account 

### ISSUE THREAD

**Issue by andrew-best-diaxion** [terraform-providers/terraform-provider-azurerm#1093]
Morning,

I am attempting to create a new storage account in Azure using the AzureRM provider. My resource definition says:

```
resource "azurerm_storage_account" "logstrggrp" { 
name = "${var.prefix}logs" 
location = "${var.location}" 
resource_group_name = "${azurerm_resource_group.rg.name}" 
account_kind = "StorageV2" 
account_tier = "Standard" 
account_replication_type = "LRS" 
tags = "${var.tags}"
```

Using the documentation at https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#account_kind I have added the 'account_kind' optional parameter.

When I do a terraform plan though it responds with:

```
Error: azurerm_storage_account.logstrggrp: expected account_kind to be one of [Storage BlobStorage], got StorageV2
```

I'm unsure why this isn't working.

**Comment by andrew-best-diaxion** [comment]
🤦‍♂️

```
$ terraform version
Terraform v0.11.6
+ provider.azurerm v1.3.2
```

**Comment by tombuildsstuff** [comment]
hi @andrew-best-diaxion 

Using v1.3.2 of the AzureRM Provider I've been able to provision a StorageV2 account using this config:

```
provider "azurerm" {
  version = "=1.3.2"
}

resource "azurerm_resource_group" "test" {
  name = "tom-dev"
  location = "West Europe"
}

resource "azurerm_storage_account" "testsa" {
  name                     = "tomdevsa"
  resource_group_name      = "${azurerm_resource_group.test.name}"
  location                 = "${azurerm_resource_group.test.location}"
  account_kind             = "StorageV2"
  account_replication_type = "GRS"
  account_tier = "Standard"
  access_tier = "Hot"
}
```

which provisions the account in Azure:

<img width="491" alt="screen shot 2018-04-09 at 11 29 32" src="https://user-images.githubusercontent.com/666005/38490730-32c24754-3bea-11e8-947e-41a094e610ca.png">

Would it be possible to see if the above snippet works for you too?

Thanks!

**Comment by andrew-best-diaxion** [comment]
Morning Tom,

My config doesnt have the `access_tier` value. Once I added it the build succeeded.

Seems we have a documentation problem here.

When `account_kind = "StorageV2"` is used then the `access_tier` value becomes mandatory. The documentation doesn't state this.

If you create a new V2 SG via the Azure Portal the access_tier option appears in the GUI.

Are you able to move this issue over to the doco people or do I need to raise a new issue for the documentation problem?

**Comment by tombuildsstuff** [comment]
@andrew-best-diaxion thanks for confirming that, glad to hear that it's now working. The documentation's contained within this repository, so I'll flag this as a documentation issue and we'll open a PR to fix this soon :)

Thanks!

**Comment by katbyte** [comment]
Hello @andrew-best-diaxion,

It seems that if `access_tier` is not specified the provider will always default to `hot` and I was able to create an account without specifying the property on both `v1.3.2` and `v1.4.0` of the provider.

Can you verify that it fails to create if you exclude that property? 
Thanks 🙂

**Comment by andrew-best-diaxion** [comment]
Hi @katbyte,

I can slot some time in soon to do that. Leave it with me a few days and i'll come back to you.

Regards
Andrew

**Comment by katbyte** [comment]
That would be great, no rush.

Thank you!

**Comment by katbyte** [comment]
@andrew-best-diaxion,

Thats great to hear! Thank you for verifying on your end 🙂 

I'll go ahead and close this issue out now.
