### ISSUE TITLE
frontdoor provider doesn't permit to use the "Latest" Version of certificate in keyvault

### ISSUE THREAD

**Issue by Cedric-Bravo** [terraform-providers/terraform-provider-azurerm#10935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.21
+ provider.azurerm v2.8.0
```

### Affected Resource(s)

frontend_endpoint
data "azurerm_key_vault_secret"

The certificate is not updated, it's related to the issue [#6057](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6057) but not been solve.

Azure introduce a new option allowing to select the latest version of the certificate and warn you if you don't use it.
![image](https://user-images.githubusercontent.com/13778646/110792302-7de5e380-8273-11eb-9b93-9697af4a2913.png)

Because updating certificate is not working with TF Code and you want to use TF for the first time provisioning, you want at least be able to configure "latest" certificate from the portal.

If you force the "latest" option **from the portal**, TF apply crash.

### Terraform Configuration Files

The following code does not result in using the latest certificate (version is not update).
Same thing, if you try to migrate to a "Azure Managed Certificate" code change have no impact on the resource.

```hcl
data "azurerm_key_vault_secret" "WildcardCert" {
    name         = var.WildcardCert
    key_vault_id = data.azurerm_key_vault.myvault.id 
}

  frontend_endpoint {
    name                              = "MYHOST"
    host_name                         = "myhost.mydomain.com"

    custom_https_provisioning_enabled = true    
    custom_https_configuration {
      certificate_source = "AzureKeyVault" 
       azure_key_vault_certificate_vault_id = data.azurerm_key_vault.myvault.id
       azure_key_vault_certificate_secret_name =  var.WildcardCert
       azure_key_vault_certificate_secret_version = data.azurerm_key_vault_secret.WildcardCert.version
    } 
  }
```

### Actual Behaviour
We should be able to use the "lastest" option in order to update the certificate
It's really a shame to not be able to automate certificate renew (remove a lot of Front Door interest).

`       azure_key_vault_certificate_secret_version = "lastest"`

### Steps to Reproduce

Using the the "latest" certificate version option into the portal with the provided code cause a panic crash.

1. `terraform apply`

### References

* #0000

**Comment by Evilweebl** [comment]
I'm having a similar issue. I'm trying to setup the frontdoor custom https configuration and I'm being forced to supply a secret version. Using the api (https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontendendpoints/enablehttps) we can just leave the secret version blank and it will be set to "latest" so I'm not sure why it is a required field.

```
resource "azurerm_frontdoor_custom_https_configuration" "endpoint_https" {
  frontend_endpoint_id              = var.subscription_id
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source                         = "AzureKeyVault"
    azure_key_vault_certificate_secret_name    = var.cert_key_vault_secret
    azure_key_vault_certificate_secret_version = ""
    azure_key_vault_certificate_vault_id       = var.cert_key_vault_id
  }
}
```
Error:
_"Error: validating Front Door Custom Https Configuration for Endpoint %endpoint% "custom_https_configuration" is invalid, all of the following keys must have values in the "custom_https_configuration" block: "azure_key_vault_certificate_secret_name", "azure_key_vault_certificate_secret_version", and "azure_key_vault_certificate_vault_id"_

**Comment by cinni99** [comment]
We have the same issue. 
My assumption is to make the azure_key_vault_certificate_secret_version optional might solve the problem.

**Comment by nboaldin** [comment]
Same issue. I have tried "Latest", "latest" and "". None of these work for me.

**Comment by KennyEliasson** [comment]
Is there any known workaround for this? Ignoring doesn't work either since the validation will fail. Secret is provided in the terraform file but I guess its missing in the Azure API response so it fails.

**Comment by michaelelleby** [comment]
@nboaldin @KennyEliasson @Evilweebl described the workaround: Leave azure_key_vault_certificate_secret_version blank, i.e. `azure_key_vault_certificate_secret_version = ""` this works fine for me.

**Comment by Cedric-Bravo** [comment]
@michaelelleby What is your provider version ?

**Comment by rubbish** [comment]
I have a potentital fix that @nboaldin and I are working on at https://github.com/terraform-providers/terraform-provider-azurerm/pull/11310 We've only tested it locally, but it does not appear that the azurerm API requires that version to be set.

**Comment by timja** [comment]
This worked for me by just not setting `azure_key_vault_certificate_secret_version` is there a reason people are trying to set it?

I've ran it twice so far and haven't had any issues and the portal looks fine

**Comment by nboaldin** [comment]
@timja I would assume its because of version differences. Some are having success with what you mentioned and others are not. @rubbish PR removes the validation of `azure_key_vault_certificate_secret_version` on what I believe is the latest version of the provider.

**Comment by timja** [comment]
Right I used `2.41.0`
