### ISSUE TITLE
azurerm_ssh_public_key - resource group name is being uppercased

### ISSUE THREAD

**Issue by richeney** [terraform-providers/terraform-provider-azurerm#10957]
The azurerm_ssh_public_key resource is uppercasing the resource group name when running through a plan and will recreate the resource each time.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* `azurerm_ssh_public_key`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "Example-Title"
  location = "UK South"
}

resource "azurerm_ssh_public_key" "example" {
  name                = "mySshKey"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  public_key          = file("~/.ssh/id_rsa.pub")
}
```

### Expected Behaviour

No planned changes once the ssh key resource is created.

### Actual Behaviour

```text
Terraform will perform the following actions:

  # azurerm_ssh_public_key.example must be replaced
-/+ resource "azurerm_ssh_public_key" "example" {
      ~ id                  = "/subscriptions/2ca40be1-7e80-4f2b-92f7-06b2123a68cc/resourceGroups/EXAMPLE-TITLE/providers/Microsoft.Compute/sshPublicKeys/mySshKey" -> (known after apply)
        name                = "mySshKey"
      ~ resource_group_name = "EXAMPLE-TITLE" -> "Example-Title" # forces replacement
      - tags                = {} -> null
        # (2 unchanged attributes hidden)
    }

```

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

**Comment by richeney** [comment]
@AliAllomani it looks like the original contribution was yours. (Thank you!) I'm not sure if this is an issue with the provider or with the Azure Go SDK?

**Comment by richeney** [comment]
Current workaround as the resource group names are case-insensitive: 

```yaml
resource_group_name = upper(azurerm_resource_group.example.name)
```

**Comment by AliAllomani** [comment]
@richeney this issue is not related to the provider, it seems an issue with Azure API, it's always returning the resource group name for Microsoft.Compute/sshPublicKeys in upper case.

```bash
$ az group create --name "lower-case" -l "westus"
{
  "id": "/subscriptions/xxx/resourceGroups/lower-case",
  "location": "westus",
  "managedBy": null,
  "name": "lower-case",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}

$ az sshkey create -l "westus" --name "TestSshKey" --public-key "@~/.ssh/id_rsa.pub" --resource-group "lower-case"
{
  "id": "/subscriptions/xxx/resourceGroups/LOWER-CASE/providers/Microsoft.Compute/sshPublicKeys/TestSshKey",
  "location": "westus",
  "name": "TestSshKey",
  "publicKey": "ssh-rsa xxx",
  "resourceGroup": "LOWER-CASE",
  "tags": null,
  "type": null
}
```
