### ISSUE TITLE
Bug/Feature: azurerm_eventhub_authorization_rule - namespace wide rule

### ISSUE THREAD

**Issue by anoff** [terraform-providers/terraform-provider-azurerm#1095]
I am trying to automate secret handling in my system using TF and Azure KeyVault. While trying to create a config for eventhub access I noted that the [authorization rule](https://www.terraform.io/docs/providers/azurerm/r/eventhub_authorization_rule.html#eventhub_name) for EH has the `eventhub_name` as a required argument. However the portal allows to create SAS on a namespace level which are valid for all underlying eventhubs. See pic below
![screen shot 2018-04-09 at 14 27 14](https://user-images.githubusercontent.com/7142618/38497661-254e5fd2-3c02-11e8-8f8c-a1c534c9b599.png)

Is it possible to allow a similar behavior with TF?

**Comment by tombuildsstuff** [comment]
hey @anoff 

Thanks for opening this issue :)

Support for this functionality has previously been requested in #626 - rather than have multiple issues open tracking the same thing - I'm going to close this in favour of that issue.

Thanks!
