### ISSUE TITLE
azurerm_kusto_eventgrid_data_connection is missing table_name, mapping_rule_name, data_format

### ISSUE THREAD

**Issue by derSchtefan** [terraform-providers/terraform-provider-azurerm#10977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_kusto_eventgrid_data_connection`

### Terraform Configuration Files

azurerm_kusto_eventgrid_data_connection

```hcl
resource "azurerm_kusto_eventgrid_data_connection" "example" {
  name                         = "my-kusto-eventgrid-data-connection"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  cluster_name                 = azurerm_kusto_cluster.example.name
  database_name                = azurerm_kusto_database.example.name
  storage_account_id           = azurerm_storage_account.example.id
  eventhub_id                  = azurerm_eventhub.example.id
  eventhub_consumer_group_name = azurerm_eventhub_consumer_group.example.name

  depends_on = [azurerm_eventgrid_event_subscription.example]
}
```

vs.

azurerm_kusto_eventhub_data_connection

```hcl
resource "azurerm_kusto_eventhub_data_connection" "eventhub_connection" {
  name                = "my-kusto-eventhub-data-connection"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  cluster_name        = azurerm_kusto_cluster.cluster.name
  database_name       = azurerm_kusto_database.database.name

  eventhub_id    = azurerm_eventhub.evenhub.id
  consumer_group = azurerm_eventhub_consumer_group.consumer_group.name

  table_name        = "my-table"         #(Optional)
  mapping_rule_name = "my-table-mapping" #(Optional)
  data_format       = "JSON"             #(Optional)
}
```

### Expected Behaviour

`azurerm_kusto_eventgrid_data_connection` is missing `table_name, mapping_rule_name and data_format` elements. These are required to setup ingesting from storage account blobs into ADX. The event hub provider has them.

You can create a mapping manually and then observe the output of
`az kusto data-connection list -o json -g RG --cluster-name CLUSTER --database-name DB`

You see them also being there.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_eventhub_data_connection
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventgrid_event_subscription

**Comment by derSchtefan** [comment]
Sorry, should not have service/event-grid but service/kusto as tag.  My mistake, I had a typo in the title and it got misclassified (it belongs to event-grid connections in Kusto specifically)

**Comment by maurocon3ras** [comment]
PR #11157 may solve this
