### ISSUE TITLE
Provider should error on duplicate resource_group names

### ISSUE THREAD

**Issue by dvdvorle** [terraform-providers/terraform-provider-azurerm#11000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_resource_group`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.34"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example1" {
  name     = "same-name"
  location = "westeurope"
}

resource "azurerm_resource_group" "example2" {
  name     = "same-name"
  location = "westeurope"
}
```

### Debug Output

https://gist.github.com/dvdvorle/6fda875e0ea15a814c4dec87d59d4fd4

### Expected Behaviour

Error: A resource with the ID "/subscriptions/4ee80320-4a5b-4e74-adfb-8711c592c7d4/resourceGroups/same-name" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_resource_group" for more information.

### Actual Behaviour

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

On it's own this example doesn't seem too bad, but especially with `resource_group`s which contain other resources this will lead to very hard to diagnose issues on destroy; where TF might think `example1` is empty and delete it, while there actually are still resources in it (but through `example2`).

### References

* Found this (closed by inactivity) example of someone explaining a worse consequence of this issue #7972

**Comment by dvdvorle** [comment]
This seems to be dependant on hashicorp/terraform-plugin-sdk#224

**Comment by tombuildsstuff** [comment]
hi @dvdvorle 

Thanks for opening this issue.

As you've mentioned unfortunately this functionality requires changes to Terraform's Plugin SDK, once support for this is available there then we should be able to take a look at supporting this across all resources. Since this issue's blocked until [the upstream issue](https://github.com/hashicorp/terraform-plugin-sdk/issues/224) is resolved, I'm going to temporarily close this issue for the moment - but once this is fixed upstream we should be able to take another look.

Thanks!
