### ISSUE TITLE
azurerm_linux_virtual_machine or azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by CedSadowski** [terraform-providers/terraform-provider-azurerm#11017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_windows_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "linux" {
  name                  = "linuxVM"
  location              = azurerm_resource_group.main.location
  resource_group_name   = azurerm_resource_group.main.name
  network_interface_ids = [azurerm_network_interface.linux.id]
  size                  = var.linux_vm_size
  license_type          = "RHEL_BYOS"

  source_image_reference {
    publisher = "redhat"
    offer     = "rhel-byos"
    sku       = "rhel-lvm83"
    version   = "latest"
  }

  plan {
    name      = "rhel-lvm83"
    product   = "rhel-byos"
    publisher = "redhat"
  }

  os_disk {
    name                 = "Linux-OS-Disk"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  computer_name                   = "linuxVM"
  admin_username                  = var.linux_admin_user
  disable_password_authentication = true
  # admin_password                  = random_password.linux.result
  admin_ssh_key {
    username   = var.linux_admin_user
    public_key = local.ssh_key
  }

  boot_diagnostics {
    storage_account_uri = ""
  }

  # Install some packages
  provisioner "local-exec" {
    working_dir = "${path.root}/../ansible"
    command     = "/bin/bash -c 'source venv/bin/activate && ansible-playbook linux.yml -v'"
  }

  tags = {
    kind = "linux"
  }

  depends_on = [azurerm_marketplace_agreement.rhel_byos]
}
```

### Debug Output
      
```
azurerm_linux_virtual_machine.linux: Importing from ID "/subscriptions/xxxxxxxx-xxxx-xxxx
-xxxx-xxxxxxxxxxxx/resourceGroups/ced-ad-lab-dev-rg/providers/Microsoft.Compute/virtualMachines/linuxVM"...

Error: The "azurerm_linux_virtual_machine" resource doesn't support attaching OS Disks - please use the `azurerm_virtual_machine` resource instead
```

### Expected Behaviour

Could import resource : see [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#import)

### Steps to Reproduce

1. `terraform import azurerm_linux_virtual_machine.linux /subscriptions/xxxxxxxx-xxxx-xxxx
-xxxx-xxxxxxxxxxxx/resourceGroups/ced-ad-lab-dev-rg/providers/Microsoft.Compute/virtualMachines/linuxVM`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @CedSadowski 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
