### ISSUE TITLE
`automatic_channel_upgrade` does not accept "none" for AKS

### ISSUE THREAD

**Issue by justin-chizer** [terraform-providers/terraform-provider-azurerm#11030]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
TF version=0.14.8
hashicorp/azurerm v2.52.0 (signed by HashiCorp)

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  automatic_channel_upgrade = "none"
}
```

### Debug Output

`Error: expected automatic_channel_upgrade to be one of [patch rapid stable], got none`

### Expected Behaviour
According to [AZURERM DOCUMENTATION](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade) "The upgrade channel for this Kubernetes Cluster. Possible values are none, patch, rapid, and stable. The default value is none."

### Actual Behaviour
"none" is not an accepted value.

### Steps to Reproduce

1. `terraform plan`

### References
Did not find an open issue on automatic_channel_upgrade.

**Comment by MattiasAng** [comment]
Looking at the implementation #10530 it seems to be as intended but documentation was not updated correctly.
Created a PR.
