### ISSUE TITLE
azurerm_spatial_anchors_account tags argument always forces replacement of spatial_anchors_account resource

### ISSUE THREAD

**Issue by ChrisEke** [terraform-providers/terraform-provider-azurerm#11037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
```

### Affected Resource(s)

* `azurerm_spatial_anchors_account`

### Terraform Configuration Files

**main.tf:**
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.48"
    }
  }

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "resource_group" {
  name     = "rg-asa-example"
  location = "West Europe"
}

resource "azurerm_spatial_anchors_account" "spatial_anchors_account" {
  name                = "asa-example-101"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  tags                = {  
    "foo" = "bar" }
}
```

### Expected Behaviour
Terraform applies change to `azurerm_spatial_anchors_account.spatial_anchors_account` **without force replacement of resource** when tags argument is changed.
```hcl
# azurerm_spatial_anchors_account.spatial_anchors_account must be replaced
-/+ resource "azurerm_spatial_anchors_account" "spatial_anchors_account" {
      ~ id                  = "/subscriptions/f4b25ef4-e1a9-468c-b855-7417a32e0bf1/resourceGroups/rg-asa-example/providers/Microsoft.MixedReality/spatialAnchorsAccounts/asa-example-101" -> (known after apply)
        name                = "asa-example-101"
      ~ tags                 = {
          ~ "foo" = "bar" -> "foo"
        }
        # (2 unchanged attributes hidden)
    }
```

### Actual Behaviour
Terraform applies removal and re-creation of `azurerm_spatial_anchors_account.spatial_anchors_account` **with force replacement of resource** when tags argument is changed.
```hcl
# azurerm_spatial_anchors_account.spatial_anchors_account must be replaced
-/+ resource "azurerm_spatial_anchors_account" "spatial_anchors_account" {
      ~ id                  = "/subscriptions/f4b25ef4-e1a9-468c-b855-7417a32e0bf1/resourceGroups/rg-asa-example/providers/Microsoft.MixedReality/spatialAnchorsAccounts/asa-example-101" -> (known after apply)
        name                = "asa-example-101"
      ~ tags                = { # forces replacement
          ~ "foo" = "bar" -> "foo"
        }
        # (2 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform apply` to create resource `azurerm_spatial_anchors_account.spatial_anchors_account`
2. Modify k/v-pair in tags argument of  resource `azurerm_spatial_anchors_account.spatial_anchors_account`
2. `terraform apply or terraform plan`

### References

* #0000

**Comment by kohei3110** [comment]
I'd like to pick this one.

**Comment by kohei3110** [comment]
I submitted a pull request [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11985).
Please review my request.

**Comment by kohei3110** [comment]
What's going on with this?

**Comment by ChrisEke** [comment]
Thank you!
