### ISSUE TITLE
Azure role-based access control (RBAC) for Azure Key Vault Resource

### ISSUE THREAD

**Issue by joegajeckyj** [terraform-providers/terraform-provider-azurerm#11045]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure role-based access control (RBAC) for Azure Key Vault Resource

### New or Affected Resource(s)

* azurerm_key_vault

### Potential Terraform Configuration

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_key_vault" "example" {
  name                      = "examplekeyvault"
  location                  = azurerm_resource_group.example.location
  resource_group_name       = azurerm_resource_group.example.name
  tenant_id                 = data.azurerm_client_config.current.tenant_id
  sku_name                  = "premium"
  enable_rbac_authorization = true
}

```

### References

* https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide

**Comment by dylanhughes** [comment]
Need to be able to apply RBAC per certificate, per secret, per key. This needs to replace access policies, so this is RBAC at the data tier and not at the control tier on the Azure_key_vault. This needs to be at resource - azurerm_key_vault_secret, azurerm_key_vault_certificate, azurerm_key_vault_key

**Comment by dylanhughes** [comment]
This feature is already there so this can be closed.

**Comment by katbyte** [comment]
closing as requested
