### ISSUE TITLE
AKS BYO Custom Private DNS Zone fails with error for the user identity

### ISSUE THREAD

**Issue by MikeForster100** [terraform-providers/terraform-provider-azurerm#11042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.50.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_private_dns_zone" "dnszone" {
  name                = "privatelink.uksouth.azmk8s.io"
  resource_group_name = azurerm_resource_group.uksouth_aks_resources.name
}

resource "azurerm_user_assigned_identity" "dnsidentity" {
  name                = "aks-dns-identity"
  resource_group_name = azurerm_resource_group.uksouth_aks_resources.name
  location            = azurerm_resource_group.uksouth_aks_resources.location
}

resource "azurerm_role_assignment" "dnsrole" {
  scope                = azurerm_private_dns_zone.dnszone.id
  role_definition_name = "Private DNS Zone Contributor"
  principal_id         = azurerm_user_assigned_identity.dnsidentity.principal_id
}

resource "azurerm_kubernetes_cluster" "mikef-aks-cluster" {
  name                = var.cluster_name
  location            = azurerm_resource_group.uksouth_aks.location
  resource_group_name = azurerm_resource_group.uksouth_aks.name
  dns_prefix          = var.cluster_dns_name
  kubernetes_version  = data.azurerm_kubernetes_service_versions.current.latest_version
  node_resource_group = var.resource_group_name_nodepool
  private_cluster_enabled = true
  private_dns_zone_id     = azurerm_private_dns_zone.dnszone.id

  default_node_pool {
    name                 = var.systempool_name
    vm_size              = var.vm_size
    orchestrator_version = data.azurerm_kubernetes_service_versions.current.latest_version
    availability_zones   = var.av_zones
    enable_auto_scaling  = true
    max_count            = var.max_count
    min_count            = var.min_count
    os_disk_size_gb      = var.disk_size
    type                 = var.scale_set
    vnet_subnet_id       = var.vnet_subnet_id
    node_labels          = var.node_labels
   tags                  = var.tag
  }
  identity {
    type = var.identity
  }

  addon_profile {
    azure_policy {enabled =  true}
    oms_agent {
      enabled =  true
      log_analytics_workspace_id = var.log_analytics
    }
  }

  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed = true
      admin_group_object_ids = var.cluster_admins
    }
  }

  disk_encryption_set_id = azurerm_disk_encryption_set.aks-Cluster-des2.id

  network_profile {
    network_plugin = var.network_plugin
    network_policy = var.network_policy
    load_balancer_sku = var.load_balancer_sku
    service_cidr = var.service_cidr
    dns_service_ip = var.dns_service_ip
    docker_bridge_cidr = var.docker_bridge_cidr
    outbound_type = var.outbound_type
  }

  tags = {
    Environment = var.environment
  }
    depends_on = [
    azurerm_disk_encryption_set.aks-Cluster-des2,
    azurerm_role_assignment.dnsrole
  ]
}
### Debug Output
Error: a user assigned identity or a service principal must be used when using a custom private dns zone

  on aks-cluster.tf line 24, in resource "azurerm_kubernetes_cluster" "mikef-aks-Cluster":
  24: resource "azurerm_kubernetes_cluster" "mikef-aks-Cluster" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Works with Az aks cli which has the additional required parameter to tell the cluster which identity to use for the DNS zone --assign-identity (but this does not appear to be an option in terraform)

az aks create -n aksprivatecluster -g 0c-uksouth-aks --load-balancer-sku standard
--enable-private-cluster
--enable-managed-identity
*************--assign-identity 
/subscriptions/XXXX/resourceGroups/0c-uksouth-aks/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-dns-identity **************
--private-dns-zone /subscriptions/XXXX/resourceGroups/f6-uksouth-privatedns/providers/Microsoft.Network/privateDnsZones/privatelink.uksouth.azmk8s.io

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @MikeForster100 

Thanks for opening this issue.

Taking a look through this appears to be a configuration question, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by MikeForster100** [comment]
Hi Tom,

This is a bug it does not work code taken from terraform code

Thanks

Mike
