### ISSUE TITLE
Support for dataset type SnowflakeTable (azurerm_data_factory)

### ISSUE THREAD

**Issue by fernandomdiaz-exxom** [terraform-providers/terraform-provider-azurerm#11051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We want a dataset type SnowflakeTable to related with the Snowflake Linked Service (SnowflakeLS).

ARM Code example:

        {
            "name": "[concat(variables('factory_name'), '/SnowflakeTable_source')]",
            "type": "Microsoft.DataFactory/factories/datasets",
            "apiVersion": "2018-06-01",
            "properties": {
                "linkedServiceName": {
                    "referenceName": "SnowflakeLS",
                    "type": "LinkedServiceReference"
                },
                "annotations": [],
                "type": "SnowflakeTable",
                "schema": [],
                "typeProperties": {
                    "schema": "[parameters('snowflake_schema_source')]",
                    "table": "[parameters('snowflake_table_source')]"
                }
            },
            "dependsOn": []
        }

### New or Affected Resource(s)

* azurerm_data_factory

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_dataset_snowflake" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  data_factory_name   = azurerm_data_factory.example.name
  linked_service_name = azurerm_data_factory_linked_service_web.example.name

  properties {
    schema = "schema"
    table = "table"
  }
}
```

### References

* #0000

**Comment by mbfrahry** [comment]
Hey @fernandomdiaz-exxom, thanks for opening this PR! It has been fixed with #11116 and should go out in 2.57.0 of the provider
