### ISSUE TITLE
Feature request: MSI support for APP Service

### ISSUE THREAD

**Issue by pixelicous** [terraform-providers/terraform-provider-azurerm#1106]
Hi,

I see that MSI support is slowly being added to resources.
Is it possible to also add it to an app service?

Thank you.

**Comment by metacpp** [comment]
@pixelicous what's the scenario of using MSI ? Is this for the authentication for Terraform to provision resource ?

If you want to use Terraform with MSI on Azure VM, you probably can try this:
https://azure.microsoft.com/en-us/blog/announcing-terraform-availability-in-the-azure-marketplace/

And MSI support for App Service is supported now:
https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview

**Comment by tombuildsstuff** [comment]
@metacpp heads up that this feature request is to support MSI within App Services as we do for other resources, such as Virtual Machines. Support for this [is available in the SDK here](https://github.com/Azure/azure-sdk-for-go/blob/0b745831a99da5f43aa3cc641cfcb9ed323e1f9f/services/web/mgmt/2016-09-01/web/models.go#L739) :)

**Comment by pixelicous** [comment]
@metacpp @tombuildsstuff we provision app services through terraform, today the only reason we need to call an arm template is to set https and add msi, https will be supported on 1.3. 3 but msi still not.. Adding the ability to bind ssl to "custom domain" would be amazing too but currenty referencing certificate in tf is broken anyways

**Comment by simongh** [comment]
I'm using a provisioner script to switch on MSI for my app service, but when I do, it kills TF - you can't do anything with the resource, even if you switch MSI off again. Hoping the latest release will fix this as I'm stuck using 1.0.1 - the last release that worked with MSI, but actual support for MSI would be most welcome.

**Comment by Phydeauxman** [comment]
Any update on when this will get incorporated?  Just wondering if I should press forward with doing an ARM template for it or wait (if it is relatively soon).

**Comment by tombuildsstuff** [comment]
Fixed via #1130

**Comment by pixelicous** [comment]
@tombuildsstuff great stuff! thanks! Hopefully the dreadful #894 would be gone next release too 😁 I Actually there is another networking matter i should open a ticket for, long ago i tested detaching and reattaching NSGs and it didn't play nice, i need to run a test and send the output, just not too much time on my hands

**Comment by katbyte** [comment]
Hello @pixelicous,

We have just released [v1.5.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#150-may-14-2018) of the provider that includes this fix 🙂

**Comment by pixelicous** [comment]
@katbyte ive been updated! thanks! :) will test soon
