### ISSUE TITLE
r/(linux|windows)_virtual_machine: support for Force Delete

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#11089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Preview feature `Force Delete` for a Linux & Windows Virtual Machine is coming out of Preview and should be supported as a feature-toggle for the new virtual machine resources.

### New or Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_windows_virtual_machine`

**Comment by magodo** [comment]
Does it make sense to simply change the semantic of current `graceful_shutdown` a bit: when enabled, do what we did today; otherwise, skip poweroff and call force delete? Given user requirements can be categorized into "just want the vm to delete as far as possible" or "want real graceful shutdown".

**Comment by tombuildsstuff** [comment]
@magodo the service team indicated there's value in supporting force delete as a separate function, since it's possible to use Force Delete to work around issues within the Azure Platform (e.g. force-detach all of the items connected to this VM, so these shouldn't cause errors in other API's).

The Service Team ultimately raised a weird API behaviour where the "Power Off" API actually doesn't guarantee it'll power the machine off, whereas Force Delete does make that guarantee, so whilst it may seem odd to support these as two separate flags here, I think that's the best we can do given this weird API design.

To come back to the use-cases:

- When deleting a Legacy/Windows VM that's been shut-down gracefully, in practice deleting this via Force Delete or non-Force Delete doesn't really make any difference (Force Delete should be quicker, and arguably should be the default API behaviour - but it's an opt-in API behaviour for now so it can't be)
- When deleting a machine that's (for example) running Batch operations, we can skip the graceful shutdown and force delete - meaning this is deleted asap

Generally speaking I'd agree with you that this should be a single flag - but to do so would require the "Power Off" API to support a flag for "gracefully" or (essentially) "pull the power cord" - so whilst I appreciate this seems odd, I don't think we have much choice given this API behaviour where the Power Off API doesn't actually guarantee it'll turn the machine off (but that we need to support this to save costs for users during deletion, as highlighted in #4920).
