### ISSUE TITLE
Support for Time To Live on azurerm_cosmosdb_table

### ISSUE THREAD

**Issue by ArveSystad** [terraform-providers/terraform-provider-azurerm#11098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Cosmos DB Tables support Time To Live (TTL), but this is not exposed on the `azurerm_cosmosdb_table` resource.

Seems to be supported to do [both by hand in the portal and via SDKs](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live?tabs=dotnetv2,javav4), so it looks doable.

Should support a toggle for `On/Off/On (No default)` and how long the TTL should be.

### New or Affected Resource(s)

* azurerm_cosmosdb_table

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_table" "my_table" {
  [...]
  time_to_live      = 1000 # 1000 seconds. Or -1 for "off", null for On(No default) to conform to the official documentation.
}
```

**Comment by yupwei68** [comment]
Hi @ArveSystad , thanks for opening this issue.
Unfortunately, currently the service `azurerm_cosmosdb_table` doesn't support `default_ttl`.
The link you provided to set the TTL via portal or SDK, seems to be the setting `default_ttl` in `azurerm_cosmsodb_sql_container`. You can see the details here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_sql_container#default_ttl.

**Comment by ArveSystad** [comment]
Yeah, you're right. My bad then. I'll check in again next time I need it, if they have updated the SDK 🚀

Thanks for the response!
