### ISSUE TITLE
can't set oms_agent_identity to kubernetes oms_agent addon

### ISSUE THREAD

**Issue by ronaldmiranda** [terraform-providers/terraform-provider-azurerm#11104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.13.0
+ provider registry.terraform.io/-/azurerm v2.52.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource azurerm_kubernetes_cluster aks {
  name                            = local.aks_cluster_name
  location                        = var.location
  resource_group_name             = var.resource_group_name
  dns_prefix                      = var.prefix
  tags                            = var.tags
  kubernetes_version              = var.kubernetes_version
  node_resource_group             = format("%s-node-rg", local.aks_cluster_name)
  api_server_authorized_ip_ranges = length(var.api_server_authorized_ips) > 0 ? var.api_server_authorized_ips : []

  addon_profile {

    oms_agent {
      enabled                    = var.log_analytics.enable
      log_analytics_workspace_id = var.log_analytics.workspace_id

      dynamic oms_agent_identity {
        for_each = var.log_analytics.oms_agent_identity.enable == true ? [1] : []

        content {
          client_id                 = try(var.log_analytics.oms_agent_identity.client_id, null)
          object_id                 = try(var.log_analytics.oms_agent_identity.object_id, null)
          user_assigned_identity_id = try(var.log_analytics.oms_agent_identity.user_assigned_identity_id, null)
        }
      }
    }
  }
}
```

### Expected Behaviour

it should create correctly the oms_agent_identity with the values set in the var.log_analytics.oms_agent_identity variable.

### Actual Behaviour

```
Error: "addon_profile.0.oms_agent.0.oms_agent_identity": this field cannot be set

  on ../../../modules/aks/main.tf line 11, in resource "azurerm_kubernetes_cluster" "aks":
  11: resource azurerm_kubernetes_cluster aks {
```

### Steps to Reproduce

1. `terraform plan / terraform apply`

### References

* #0000

**Comment by mbfrahry** [comment]
Hey @ronaldmiranda, it looks like you can't set any values under `oms_agent_identity` because it's Computed. I've opened a PR to better reflect that in the docs. I believe the `oms_agent_identity` is generated for you when requesting `oms` support but, if this isn't the case, please do let me know and we'll figure out what needs to be changed.

**Comment by ronaldmiranda** [comment]
@mbfrahry thanks for your response, i thought that as a possibility to authenticate the oms addon with managed identities.

**Comment by MattiasAng** [comment]
@mbfrahry I think it would be better to remove the documentation for oms_agent_identity under supported attributes rather than the edit you made, should make it a bit less confusing. 

Take identity-block as an example that exports the same information, it is not noted under configuration documentation.

**Comment by mbfrahry** [comment]
Thanks for the input @MattiasAng. I went ahead and move that block into the exported section of the docs
