### ISSUE TITLE
azurerm_cdn_endpoint origin_host_header doesn't default to host name of the origin

### ISSUE THREAD

**Issue by lukasz-mitka** [terraform-providers/terraform-provider-azurerm#11107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0

### Affected Resource(s)

* `azurerm_cdn_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "cdn-rg"
  location = "westeurope"
}

resource "azurerm_storage_account" "example" {
  name                     = "uniquesaname"
  location                 = azurerm_resource_group.rg.location
  resource_group_name      = azurerm_resource_group.rg.name
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_cdn_profile" "example" {
  name                = "example-cdn"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard_Verizon"
}

resource "azurerm_cdn_endpoint" "example" {
  name                = "example"
  profile_name        = azurerm_cdn_profile.example.name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  origin {
    name      = "example"
    host_name  = azurerm_storage_account.example.primary_blob_host
  }
  # origin_host_header = azurerm_storage_account.example.primary_blob_host
}

output "origin_host_header" {
  value = azurerm_cdn_endpoint.example.origin_host_header
}
```

### Expected Behaviour
`origin_host_header` should default to "host name of the origin" as in documentation:
[azurerm_cdn_endpoint](https://registry.terraform.io/providers/hashicorp/azurerm/2.51.0/docs/resources/cdn_endpoint)

### Actual Behaviour
`origin_host_header` defaults to null. It also overrides exiting values to null.
This is either an error or unclarity in documentation.

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
Fixed via #11852
