### ISSUE TITLE
VMSS with Automatic OS Update and Shared Images needs documentation improvement

### ISSUE THREAD

**Issue by ceesios** [terraform-providers/terraform-provider-azurerm#11123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.14.5
- provider registry.terraform.io/hashicorp/azurerm v2.51.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine_scale_set`
* maybe also `azurerm_windows_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
data "azurerm_shared_image_version" "linux" {
  name                = "latest"
  image_name          = "linux"
  gallery_name        = "gallery"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_linux_virtual_machine_scale_set" "example" {
  name                = "example-vmss"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "Standard_F2"
  instances           = 1
  admin_username      = "adminuser"
  source_image_id     = data.azurerm_shared_image.linux.id
  upgrade_mode        = "Automatic"

  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadWrite"
  }

  network_interface {
    name    = "example"
    primary = true

    ip_configuration {
      name      = "internal"
      primary   = true
      subnet_id = azurerm_subnet.internal.id
    }
  }
}


```

### Expected Behaviour

Since the image version defined as latest i would expect `upgrade_mode` to work

### Actual Behaviour

Error: Error creating Linux Virtual Machine Scale Set "example" (Resource Group "example"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="virtualMachineScaleSets with Automatic OS Upgrade enabled must use Platform or Gallery Image with version set to 'latest'."

When i change the image reference (`azurerm_shared_image_version`) to `azurerm_shared_image` it does work. I believe that this should be added to the documentation.

### Steps to Reproduce

1. `terraform apply`

### References

* #8301

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I believe the docs are actually fine. When you're using `azurerm_shared_image_version, the `id` attribute of it returns the ID of the _version_ and not of the image. So behavior is actually correct in this case, as well as the docs. 

I'm going to close this for now - feel free to reopen if you feel there's still something we should do.
