### ISSUE TITLE
azurerm_virtual_network_gateway and peering_addresses conflict

### ISSUE THREAD

**Issue by Yakuza-UA** [terraform-providers/terraform-provider-azurerm#11136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
 
### Terraform (and AzureRM Provider) Version

Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_virtual_network_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway" "this" {
  name                = "vgw-${local.scope_name}-001"
  location            = azurerm_resource_group.network["vgw"].location
  resource_group_name = azurerm_resource_group.network["vgw"].name
  type                = "Vpn"
  vpn_type            = "RouteBased"
  enable_bgp          = true
  active_active       = false
  sku                 = "VpnGw1"

  ip_configuration {
    name                          = "default"
    public_ip_address_id          = azurerm_public_ip.vgw.id
    subnet_id                     = azurerm_subnet.this["hub-001-vgw"].id
    private_ip_address_allocation = "Dynamic"
  }

  bgp_settings {
    asn               = 65515
    peering_addresses = {
      apipa_addresses = ["169.254.21.1"]
    }
  }
}
```

### Debug Output

https://gist.github.com/Yakuza-UA/8c06cdcbcc998d39ecf84b994a570a5d

### Panic Output

https://gist.github.com/Yakuza-UA/422df64d03aa3af2a3d13df7c407657c

### Expected Behaviour

As per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_gateway this configuration is correct, and `peering_address` has been deprecated. 

### Actual Behaviour

Terraform suggests that `peering_addresses` under `bgp_settings` is not expected and suggests to use `peering_address` instead which is now deprecated. I am on latest AzureRM provider (v2.52.0)

### Steps to Reproduce

1. `terraform validate`
2. observe error
3. remove `peering_addresses` from `bgp_settings` block
4. `terraform validate` - reports no issues

### Important Factoids

West Europe region in Azure

### References

* #0000

**Comment by mbfrahry** [comment]
Hi @Yakuza-UA, thanks for opening this issue! It looks like this is a syntax issue. Can you try running this with
```
peering_addresses {
```
instead of
```
peering_addresses = {
```

Feel free to reopen this issue if that doesn't solve your issue.

**Comment by Yakuza-UA** [comment]
@mbfrahry omg. I feel stupid. Thanks for spotting this and replying back!

**Comment by mbfrahry** [comment]
No worries at all!
