### ISSUE TITLE
Error building Authorizer: malformed storage account key: illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by DreadKong** [terraform-providers/terraform-provider-azurerm#11133]
when I run a "terraform init" locally (via VS code) I receive this error:

Error: Error inspecting states in the "azurerm" backend:
    Error building Authorizer: malformed storage account key: illegal base64 data at input byte 0

My Backend code block is simple:

terraform {
  backend "azurerm" {
    resource_group_name  = "RG_Storage_Dev"
    storage_account_name = "tfstorefp"
    container_name       = "terraform"
    key                  = "terraform.tfstate"
    access_key           = "__storagekey__"  ( Here I also tried putting the access key directly to see if that helps, but it didnt)

  }
}

This worked until last week, I started getting this problem today, could somebody suggest what could be wrong? or what can I do?

Any help would be appreciated.

Below is the exact message I receive:

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.

Error: Error inspecting states in the "azurerm" backend:
    Error building Authorizer: malformed storage account key: illegal base64 data at input byte 0

Prior to changing backends, Terraform inspects the source and destination
states to determine what kind of migration steps need to be taken, if any.
Terraform failed to load the states. The data in both the source and the
destination remain unmodified. Please resolve the above error and try again.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Azure RM version: 2.46.0
Terraform Version: 0.14. 9

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.46.0"
    }
  }
}

provider "azurerm" {
  features {}
}

terraform {
  backend "azurerm" {
    resource_group_name  = "RG_Storage_Dev"
    storage_account_name = "tfstorefp"
    container_name       = "terraform"
    key                  = "terraform.tfstate"
    access_key           = "__storagekey__"

  }
}

```

### Debug Output

<!---
Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
--->

### Panic Output

<!--- If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behaviour

<!--- What should have happened? --->
Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v2.51.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see  
any changes that are required for your infrastructure. All Terraform commands  
should now work.

If you ever set or change modules or backend configuration for Terraform,      
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
### Actual Behaviour
PS C:\Users\sss\Documents\Repo\fp-dbf-terraform\terraform> terraform init

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.

Error: Error inspecting states in the "azurerm" backend:
Error building Authorizer: malformed storage account key: illegal base64 data at input byte 0

Prior to changing backends, Terraform inspects the source and destination
states to determine what kind of migration steps need to be taken, if any.
Terraform failed to load the states. The data in both the source and the
destination remain unmodified. Please resolve the above error and try again.
<!--- What actually happened? --->

### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform init`

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

* #0000

**Comment by AliciaDapplications** [comment]
I got this to work after switching my terraform version from 15 to 13.7

**Comment by sunkarakamal** [comment]
changed  to different version , But still the same issue. Any inputs

**Comment by tombuildsstuff** [comment]
hi @DreadKong 

Thanks for opening this issue - apologies for the delayed response here.

Taking a look through here it appears that the Storage Account Key that's being specified here isn't valid Base64 (since this needs to be a base64-encoded value) - as such I'd recommend checking that this is a Base64-encoded value.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
