### ISSUE TITLE
azurerm_virtual_machine_scale_set does not support autoscale rules

### ISSUE THREAD

**Issue by deyjcode** [terraform-providers/terraform-provider-azurerm#1114]
### Terraform Version
Terraform v0.11.7
+ provider.azurerm v1.3.2
+ provider.random v1.2.0

### Affected Resource(s)
- azurerm_virtual_machine_scale_set

### Expected Behavior
Terraform Azure Scale Set resource should support auto-scaling capability. 
This is the primary use case for Azure Scale Sets.

### Actual Behavior
azurerm_virtual_machine_scale_set does not support autoscale rules.

### Important Factoids
See the following JSON code as example for deploying such capability in Azure (as written in referenced material):

Create a profile;
```json
{
"type": "Microsoft.insights/autoscalesettings",
"name": "Autoscale",
"apiVersion": "2014-04-01",
"location": "[variables('location')]",
"scale": null,
"properties": {
  "profiles": [
    {
      "name": "Autoscale by percentage based on CPU usage",
      "capacity": {
        "minimum": "2",
        "maximum": "10",
        "default": "2"
      }
    }
  ]
}
```

Define a rule to autoscale out;
```json
"rules": [
  {
    "metricTrigger": {
      "metricName": "Percentage CPU",
      "metricNamespace": "",
      "metricResourceUri": "[concat('/subscriptions/',subscription().subscriptionId, '/resourceGroups/',  resourceGroup().name, '/providers/Microsoft.Compute/virtualMachineScaleSets/', variables('vmssName'))]",
      "metricResourceLocation": "[variables('location')]",
      "timeGrain": "PT1M",
      "statistic": "Average",
      "timeWindow": "PT5M",
      "timeAggregation": "Average",
      "operator": "GreaterThan",
      "threshold": 70
    },
    "scaleAction": {
      "direction": "Increase",
      "type": "ChangeCount",
      "value": "3",
      "cooldown": "PT5M"
    }
  }
]
```

### References
[Define an autoscale profile](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/tutorial-autoscale-template#define-an-autoscale-profile)
[Define a rule to autoscale out](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/tutorial-autoscale-template#define-a-rule-to-autoscale-out)
[Full JSON example of scale set with autoscale rules on Azure github](https://raw.githubusercontent.com/Azure-Samples/compute-automation-configurations/master/scale_sets/autoscale.json)

**Comment by tombuildsstuff** [comment]
hey @deyjcode 

Thanks for opening this issue :)

Support for Auto Scale Settings has previously been requested in #50 - rather than having multiple issues tracking the same feature request I'm going to close this issue in favour of #50.

Thanks!
