### ISSUE TITLE
Support for Azure service_tag headers in ip_restrictions azurerm_app_service

### ISSUE THREAD

**Issue by MarkPerry24** [terraform-providers/terraform-provider-azurerm#11156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For Services such as securing FrontDoor access to web services it is currently not possible to restrict using the service tag + unique identifier of your specific front door without deploying via ARM template or Azure Cli tasks.

### New or Affected Resource(s)

*  azurerm_app_service

### Potential Terraform Configuration

add support for headers in similar way to ARM template.  e.g. https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?tabs=json

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by aristosvo** [comment]
This shouldn't be too hard, I'll try to pick this up if the REST APIs support it
