### ISSUE TITLE
Azure App Service > Java Stack Settings missing

### ISSUE THREAD

**Issue by djones8389** [terraform-providers/terraform-provider-azurerm#11171]
Hi I want to create an App Service which is:
     
Stack: Java
Major Version: Java 11
Java Web Version: Tomcat 9.0
Java web server version: Tomcat (autoupdate)

This seems to get the Java section working
 linux_fx_version = "JAVA|11-java11"

but these don't seem to make any difference, so the other fields aren't populated with Tomcat:

 java_version = "1.8"
 java_container = "TOMCAT"           #this doesn't work
 java_container_version = "9.0"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_app_service

### Terraform Configuration Files

resource "azurerm_app_service" "example" {
  name                = "example-app-servicedj105937"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id
  https_only                = true   
auth_settings{
    enabled                 = true
    default_provider        = "AzureActiveDirectory"
   }
   identity{
     type                     = "SystemAssigned"
   }
   site_config{
     
      linux_fx_version = "JAVA|11-java11" # need this to make it v11
      java_version = "1.8"
      java_container = "TOMCAT"           #this doesn't work
      java_container_version = "9.0"
      ftps_state               = "FtpsOnly"
      scm_use_main_ip_restriction = true
    }

    app_settings = {
      "dsurl" = "url"
      "dsusername" = "username"
      "dspassword" = "password"
    }

    lifecycle {
    ignore_changes = [
      	app_settings["WEBSITE_RUN_FROM_PACKAGE"],
      	site_config["scm_type"],
        auth_settings["enabled"],
        auth_settings["default_provider"],
    ]
  }  
}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by djones8389** [comment]
Fixed!!

      linux_fx_version = "TOMCAT|9.0-java11"
      always_on              = true
      java_version           = "11"
      java_container         = "JAVA"
      java_container_version = "11"

**Comment by favoretti** [comment]
Hi, thank you for reporting this. Happy to hear you were able to solve it. Closing :)
