### ISSUE TITLE
Add capability to remove storage_os_disk when running destroy

### ISSUE THREAD

**Issue by deyjcode** [terraform-providers/terraform-provider-azurerm#1117]
### Terraform Version
Terraform v0.11.7
+ provider.azurerm v1.3.2
+ provider.random v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_machine
- azurerm_managed_disk (_maybe_)

### Terraform Configuration Files
```hcl
# Create a single virtual machine
resource "azurerm_virtual_machine" "vm" {
    name                  = "webvm"
    location              = "${var.location}"
    resource_group_name   = "${azurerm_resource_group.resourcegroup.name}"
    network_interface_ids = ["${azurerm_network_interface.nic.id}"]
    vm_size               = "Standard_F1s"

    storage_os_disk {
        name              = "osdisk"
        caching           = "ReadWrite"
        create_option     = "FromImage"
        managed_disk_type = "Premium_LRS"
    }
}
```

### Expected Behavior
When running `terraform destroy -target='azurerm_virtual_machine.vm'` managed disks that are part of terraform configuration are not removed. 

When running 'terraform destroy' managed disk created for `storage_os_disk` should also be apart of the destruction process.

### Actual Behavior
Since an azure managed disk has no dependencies *and* user provides no 'azurerm_managed_disk' data source in configuration data, user will not be able to destroy azure managed disk created during `terraform apply`

### Discussion / Workaround
I am not entirely certain how the workflow might apply here. Due to the fact that using the `-target` flag removes dependencies, this may be normal behavior since a managed disk does not necessarily have a dependency on the virtual machine in Azure. 

Since a managed disk can simply be re-attached to a virtual machine, this might be a non-issue for deploying a resource on top of and already managed disk. 

**However**, this might pose issues when user wishes to destroy all resources but finds that the only remaining resource in resource group is the managed disk and the terraform configuration file does not explicitly use a managed disk resource.

This might be a misunderstanding of my applicable knowledge of terraform in this instance. Possible to maybe have a note in the documentation regarding this behavior?

**Comment by deyjcode** [comment]
Tom,

Thanks. I ran through the configuration with that property. That fixes the issue and as well, provides needed context for this type of operation. I completely missed the comment in the example. Thanks for reminding me to RTFM more! Still learning the docs on Terraform's site.

**Comment by tombuildsstuff** [comment]
@deyjcode awesome - glad to hear this works for you :)
