### ISSUE TITLE
Feature request: Custom Domain support for APP Service

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1118]
I was shocked to find that Terraform does not support something that seems so trivial...adding additional hostnames on the "Custom Domains" property page of an App Service.  Is this on the roadmap?

**Comment by tombuildsstuff** [comment]
Closing since based on the comments in https://github.com/terraform-providers/terraform-provider-azurerm/pull/1087#issuecomment-381085495 I believe this is regarding App Service Custom Hostname Bindings
