### ISSUE TITLE
Documentation Mismatch in policy_definition_reference

### ISSUE THREAD

**Issue by studentacc17** [terraform-providers/terraform-provider-azurerm#11208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_policy_set_definition / policy_definition_reference
`
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_set_definition#group_names

### Terraform Configuration Files

No files.

### Expected Behaviour

When applying group_names, the code should compile.

### Actual Behaviour

Terraform gave an error. Unexpected argument / invalid argument error.

### Steps to Reproduce

Add the optional group_names to a policy_definition_reference

1. `terraform plan`

### Important Factoids

Seems like a general bug or mismatch in documentation. When I dive into the .tfstate file the variable exists but it listed as policy_group_names and not group_names as is stated in the documentation.  

Please update this piece of documentation accordingly, I spent (too much) time trying to figure out what was wrong, save others the time. Thank you :)

### References

* #0000

**Comment by Shatakshi0805** [comment]
Hi, I have submitted a Pull Request.

**Comment by manicminer** [comment]
Fixed in #11210
