### ISSUE TITLE
azurerm_api_management_api_policy always "will be updated in-place", even when nothing has changed

### ISSUE THREAD

**Issue by seanke** [terraform-providers/terraform-provider-azurerm#11230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.9
AzureRM v2.54.0

### Affected Resource(s)

azurerm_api_management_api_policy

### Terraform Configuration Files

```hcl
variable "api_management_name" {}
variable "resource_group_name" {}
variable "name" {}
variable "revision" { default = 1 }
variable "display_name" {}
variable "path" {}
variable "swagger_file_location" {}
variable "policy_file_location" {}
variable "subscription_required" {
  type = bool
  default = true
}

resource "azurerm_api_management_api" "apim_swagger_api" {
  name = var.name
  resource_group_name = var.resource_group_name
  api_management_name = var.api_management_name
  revision = var.revision
  display_name = var.display_name
  path = var.path
  subscription_required = var.subscription_required
  protocols = [
    "https"]

  import {
    content_format = "openapi"
    content_value = file(var.swagger_file_location)
  }
}

resource "azurerm_api_management_api_policy" "apim_api_policy" {
  api_name = azurerm_api_management_api.apim_swagger_api.name
  api_management_name = var.api_management_name
  resource_group_name = var.resource_group_name

  xml_content = file(var.policy_file_location)
}
```

### Debug Output

```
  # module.****["ae"].module.****[0].azurerm_api_management_api_policy.apim_api_policy will be updated in-place
  ~ resource "azurerm_api_management_api_policy" "apim_api_policy" {
        id                  = "/subscriptions/****/resourceGroups/****/providers/Microsoft.ApiManagement/service/****/apis/****/policies/policy"
~ xml_content         = <<-EOT
          - <policies>
          - 	<inbound>
          - 		<base />
          - 		<cors allow-credentials="true">
          - 			<allowed-origins>
          - 				<origin>http://localhost:3000/</origin>
          - 				<origin>https://localhost:3000/</origin>
          - 			</allowed-origins>
          - 			<allowed-methods preflight-result-max-age="300">
          - 				<method>*</method>
          - 			</allowed-methods>
          - 			<allowed-headers>
          - 				<header>*</header>
          - 			</allowed-headers>
          - 			<expose-headers>
          - 				<header>*</header>
          - 			</expose-headers>
          - 		</cors>
          - 	</inbound>
          - 	<backend>
          - 		<base />
          - 	</backend>
          - 	<outbound>
          - 		<base />
          - 	</outbound>
          - 	<on-error>
          - 		<base />
          - 	</on-error>
          + ﻿<policies>
          +     <inbound>
          +         <base />
          +         <cors allow-credentials="true">
          +             <allowed-origins>
          +                 <origin>http://localhost:3000/</origin>
          +                 <origin>https://localhost:3000/</origin>
          +             </allowed-origins>
          +             <allowed-methods preflight-result-max-age="300">
          +                 <method>*</method>
          +             </allowed-methods>
          +             <allowed-headers>
          +                 <header>*</header>
          +             </allowed-headers>
          +             <expose-headers>
          +                 <header>*</header>
          +             </expose-headers>
          +         </cors>
          +     </inbound>
          +     <backend>
          +         <base />
          +     </backend>
          +     <outbound>
          +         <base />
          +     </outbound>
          +     <on-error>
          +         <base />
          +     </on-error>
            </policies>
        EOT
```

### Expected Behaviour

azurerm_api_management_api_policy should not update the resource if nothing has changed

### Actual Behaviour

azurerm_api_management_api_policy updates the resource.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If instead of using this syntax 
```
xml_content = file(var.policy_file_location)
```
I use this syntax, it works correctly as expected.
```
  xml_content = <<XML
<policies>
  <inbound>
    <find-and-replace from="xyz" to="abc" />
  </inbound>
</policies>
XML
```

It seems to happen regardless of what is in the XML.

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. From what I can see it might be a tabs vs spaces issue? Indentation changed in the diff you've pasted.

**Comment by seanke** [comment]
Something strange happened with the output I posted before. This one is more accurate. I think you're onto something. My IDE (Rider 2021.1.1) is using spaces and not tabs, however what is in APIM after a deploy is Tabs, and so the string is not equal.

,,,
# module.***["ae"].***[0].azurerm_api_management_api_policy.apim_api_policy will be updated in-place
  ~ resource "azurerm_api_management_api_policy" "apim_api_policy" {
        id                  = "***"
      ~ xml_content         = <<-EOT
            <policies>
          - 	<inbound>
          - 		<base />
          - 		<cors allow-credentials="true">
          - 			<allowed-origins>
          - 				<origin>http://localhost:3000/</origin>
          - 				<origin>https://localhost:3000/</origin>
          - 			</allowed-origins>
          - 			<allowed-methods preflight-result-max-age="300">
          - 				<method>*</method>
          - 			</allowed-methods>
          - 			<allowed-headers>
          - 				<header>*</header>
          - 			</allowed-headers>
          - 			<expose-headers>
          - 				<header>*</header>
          - 			</expose-headers>
          - 		</cors>
          - 	</inbound>
          - 	<backend>
          - 		<base />
          - 	</backend>
          - 	<outbound>
          - 		<base />
          - 	</outbound>
          - 	<on-error>
          - 		<base />
          - 	</on-error>
          +     <inbound>
          +         <base />
          +         <cors allow-credentials="true">
          +             <allowed-origins>
          +                 <origin>http://localhost:3000/</origin>
          +                 <origin>https://localhost:3000/</origin>
          +             </allowed-origins>
          +             <allowed-methods preflight-result-max-age="300">
          +                 <method>*</method>
          +             </allowed-methods>
          +             <allowed-headers>
          +                 <header>*</header>
          +             </allowed-headers>
          +             <expose-headers>
          +                 <header>*</header>
          +             </expose-headers>
          +         </cors>
          +     </inbound>
          +     <backend>
          +         <base />
          +     </backend>
          +     <outbound>
          +         <base />
          +     </outbound>
          +     <on-error>
          +         <base />
          +     </on-error>
            </policies>
        EOT
        # (3 unchanged attributes hidden)
    }
,,,

**Comment by seanke** [comment]
@favoretti Thanks for your help! I've updated my IDE to use tabs not spaces and it's almost all working. There's just the first line now, any ideas what is going on here?

```
      ~ xml_content         = <<-EOT
          - <policies>
          + ﻿<policies>
```

**Comment by seanke** [comment]
Also something else I noticed is that when looking at the policy in the Azure Portal, it has spaces not tabs when I have spaces in my file.

**Comment by seanke** [comment]
Here's an example of what is happening now:

```
  # module.***["ae"].***.policy will be updated in-place
  ~ resource "azurerm_api_management_api_operation_policy" "policy" {
        id                  = "/subscriptions/***/resourceGroups/***/providers/Microsoft.ApiManagement/service/***/apis/***-/operations/post-auth-arrangements-revoke/policies/policy"
      ~ xml_content         = <<-EOT
          - <policies>
          + ﻿<policies>
            	<inbound>
            		<set-variable name="skipValidateJwt" value="true" />
            		<base />
            	</inbound>
            	<backend>
            		<base />
            	</backend>
            	<outbound>
            		<base />
            	</outbound>
            	<on-error>
            		<base />
            	</on-error>
            </policies>
        EOT
        # (4 unchanged attributes hidden)
    }
```

**Comment by seanke** [comment]
Tried all the different line separators, CRLF, CR, and LF. No luck, the first line always needs to be updated.

~ xml_content         = <<-EOT
    - <policies>
    + ﻿<policies>

**Comment by seanke** [comment]
I managed to solve this by removing BOM using Rider. I wonder if it is possible for Terraform to ignore this. Also it would be great it tabs and spaces outside of an xml element were ignored.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/207059975-What-is-Remove-BOM-
