### ISSUE TITLE
Support for Azure Machine Learning Inference cluster (requires new resource)

### ISSUE THREAD

**Issue by gro1m** [terraform-providers/terraform-provider-azurerm#11252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure offers Inference clusters on Azure Kubernetes Service to use ML models in a productive service.

A general description of the machine learning workflow by Azure can be found here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-attach-compute-studio. Would be cool if of all of these resources were to provided via Terraform (but probably also a huge effort)

### New or Affected Resource(s)

* azurerm_machine_learning_aks_inference_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_machine_learning_aks_inference_cluster" "ml_aks_inference" {
workspace_name = "aml-workspace"
web_service_name = "my-aml-webservice"
location = "westeurope"
environment_name = "AzureML-Scikit-learn-0.20.3" #https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-environments, https://docs.microsoft.com/en-us/azure/machine-learning/resource-curated-environments
environment_version = "3"
driver_program = "predict.py"
model_configuration = {name="my_model.pkl", path = "modles/my_model.pkl", framework = "ScikitLearn", framework_version = "0.20.3"}
scoring_timeout_ms = 1
app_insights_enabled = false
auth_enabled = false
aad_auth_enabled = false
compute_name = "ml_aks_inference_cluster"
kubernetes_service = <reference to aks cluster resource or data source>
}
```
Question: How much of Azure Kubernetes cluster configuration could be reused here, i.e. from azurerm_kubernetes_cluster and azurerm_kubernetes_cluster_node_pool resources and data sources? It does not seem sensible to me to redo another AKS redefinition in this resource anymore, but unfortunately I am not sure on to how much would be needed here apart from specific naming and model-specific configurations.

### References

* https://docs.microsoft.com/en-us/azure/machine-learning/how-to-secure-inferencing-vnet?tabs=python (Kubernetes Service for Machine Learning documentation)
* https://github.com/Azure/azure-quickstart-templates/tree/master/101-machine-learning-service-create-aks (ARM template for Azure Machine Learning with AKS)

**Comment by gro1m** [comment]
@ArcturusZhang  I started implementing the above resource and that you are heavily involved in bringing the Azure-SDK-for-go forward, but did not find you here. I would just like to make sure that I am focusing on the right code, as the terminology can be sometimes a bit confusing regarding ML resources (e.g. "Compute Cluster" <-> "AmlCompute", et cetera).
I plan to use https://github.com/Azure/azure-sdk-for-go/blob/e19a30aca35ffb0f3baca123eb374633b1462e9a/services/machinelearningservices/mgmt/2020-04-01/machinelearningservices/models.go#L282 to implement the inference cluster.
And if Kubernetes cluster already exists I plan to use: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/compute/container_cluster.go#L90.
Am I on the right track or do I have to adjust something? - thank you!

**Comment by ArcturusZhang** [comment]
Hi @gro1m thanks for your contribution!

To be honest I am not fully understand the terminology of machine learning resources. As far as I know, `AmlCompute` refers to Azure Machine Learning Compute resource created by [this API](https://github.com/Azure/azure-sdk-for-go/blob/e19a30aca35ffb0f3baca123eb374633b1462e9a/services/machinelearningservices/mgmt/2019-06-01/machinelearningservices/machinelearningcompute.go#L53). As for the AKS type of compute instance here, based on its model definition [here](https://github.com/Azure/azure-sdk-for-go/blob/e19a30aca35ffb0f3baca123eb374633b1462e9a/services/machinelearningservices/mgmt/2019-06-01/machinelearningservices/models.go#L35), it has a property of `ResourceID`, which might accept a resource ID of existing AKS cluster. This might need to find out in its own doc, sorry I do not have much knowledge about this.
