### ISSUE TITLE
Support for Azure Backup Vault

### ISSUE THREAD

**Issue by dkirrane** [terraform-providers/terraform-provider-azurerm#11261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to have support for Azure Backup Vault to support backing up Postgres dbs.

### References

- https://docs.microsoft.com/en-us/azure/backup/backup-vault-overview
- https://docs.microsoft.com/en-us/azure/backup/backup-azure-database-postgresql#configure-backup-on-azure-postgresql-databases

**Comment by Ticallion22** [comment]
We'd love to see this implemented to use operational backup for Azure Blob storage. Is this feature on the roadmap?

https://docs.microsoft.com/en-us/azure/backup/blob-backup-overview

**Comment by ms-henglu** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/pull/12081
https://github.com/terraform-providers/terraform-provider-azurerm/pull/12072

**Comment by katbyte** [comment]
@dkirrane - looks like the two related PRs have been merged and the final one should go out with tomorrow release

**Comment by Ticallion22** [comment]
do these PRs only cover PostgreSQL backup or also Azure Blob backup?

https://docs.microsoft.com/en-us/azure/backup/blob-backup-overview

**Comment by ms-henglu** [comment]
hi @Ticallion22 
> Related PRs
> #12081
> #12072

These PRs are used to backup PostgreSQL only, but I have developed similar resources to backup Blob and Disks.
