### ISSUE TITLE
Support for switching from Service Principal to Managed Identity for azurerm_kubernetes_cluster without cluster recreation

### ISSUE THREAD

**Issue by ToxicWar** [terraform-providers/terraform-provider-azurerm#11288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, an AKS cluster with Service Principal can't migrate to Managed Identity without recreating the cluster from scratch.
But for updating Azure AD from Service Principal to Managed one, this works as "update in-place"

```hcl
~ role_based_access_control {
      # (1 unchanged attribute hidden)

    ~ azure_active_directory {
        ~ admin_group_object_ids = [
            + "********-****-****-****-b84c7e895b53",
          ]
        - client_app_id          = "********-****-****-****-34e3ae56d094" -> null
        ~ managed                = false -> true
        - server_app_id          = "********-****-****-****-1bc5e70c4750" -> null
        - server_app_secret      = (sensitive value)
          # (1 unchanged attribute hidden)
      }
  }
```

As I see in documentation: https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities-preview
AKS has some process to migrate from SP to MI, and it in the Preview at the moment.
After GA of this feature, will this behavior be switched to update in-place?

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

**Comment by favoretti** [comment]
Hi @ToxicWar and thank you for reporting this. From what I can see it's not yet supported in the SDK. As soon as this functionality becomes available we'll be able to make the change in the provider.

**Comment by ToxicWar** [comment]
Upgrading to Managed Identity is GA now
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities

Released in AZ cli `2.23.0`
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.23.0
https://github.com/Azure/azure-cli/commit/7627ed540cc7c41159418f03649f51ecabcb2d1b

**Comment by hieumoscow** [comment]
@favoretti, are we able to upgrade the provider to support in place update from SP to MSI for AKS Cluster?

It seems the API is available in the SDK?

**Comment by favoretti** [comment]
@hieumoscow If it's available in the SDK - we should be able to, however I personally am not able to commit to implementing it now, but you're most welcome to submit a PR!

**Comment by aristosvo** [comment]
@hieumoscow @ToxicWar I gave it a go, feel free to test it or add potential scenario's you'd want it to support!
