### ISSUE TITLE
azurerm_frontdoor updates take an impractical amount of time

### ISSUE THREAD

**Issue by elliotchaim** [terraform-providers/terraform-provider-azurerm#11287]
Creating and updating [azurerm_frontdoor](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor) resources takes an impractical amount of time.

This has [already been raised](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9295), and was incorrectly closed. 

As @veteixei said in the above issue, the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-faq#how-long-does-it-take-to-deploy-an-azure-front-door--does-my-front-door-still-work-when-being-updated-) states that creating or updating AFDs takes 3 to 5 minutes.

Please can this be resolved? I have been forced to manage my AFD resources outside of terraform, and I imagine others are in the same position. Thank you.

**Comment by favoretti** [comment]
Hi @elliotchaim, thank you for reporting this. As I've been working on some of the AFD issues in the last couple of months - I did not experience this behavior - could you share some TF code that you're using to see what could potentially be causing this? In all my tests AFD is created/destroyed/updated in minutes.

**Comment by bcline760** [comment]
I'm running into this problem as well and I'm using the configuration in my other issue #8039 if you need some example configuration. My current configuration is at nearly an hour to run.

**Comment by bcline760** [comment]
From what I'm gathering, it looks like the task of provisioning the certificate in the custom domain HTTPS is where the issue is. I initially thought this was something introduced in 2.55, but I downgraded to version 2.54 and it is still taking very long to provision the certificate. I did open a support ticket with Microsoft asking why it is taking so long to provision a certificate.

**Comment by fdebuire** [comment]
I am getting the same issue with the provisioning of the certificate, but according to the UI it can take a long time:
![image](https://user-images.githubusercontent.com/50776984/114712648-9cd30c00-9d30-11eb-9a3b-7718061accaa.png)

If you have only one frontend 20 minutes is still kind of OK but with multiple frontends it gets really long.

**Comment by bcline760** [comment]
This might all be related to the API changes Microsoft did for Front Door and CDN. I created a Front Door and added two custom domains with HTTPS using a Front Door provided certificate all through Azure Portal (i.e. no Terraform). It's so far taking 43 minutes to complete the process.

**Comment by michaelelleby** [comment]
This is a bug in Azure, not Terraform. I tried deploying an Azure Front Door instance with two customHttpsConfiguration blocks yesterday using an ARM template and it took approximately 1 hour to finish.

**Comment by fdebuire** [comment]
@michaelelleby I agree that it seems like a bug in Azure but it also impacts update of an existing Front Door instance. 

Even if the certificate has not changed (using the same Keyvault version), the update takes a really long time. Yesterday (using Terraform) it took two hours to update two frontends domains whereas the only change I made was to rename a routing rule. It seems to be already discussed in #10661.

**Comment by michaelelleby** [comment]
> @michaelelleby I agree that it seems like a bug in Azure but it also impacts update of an existing Front Door instance.
> 
> Even if the certificate has not changed (using the same Keyvault version), the update takes a really long time. Yesterday (using Terraform) it took two hours to update two frontends domains whereas the only change I made was to rename a routing rule. It seems to be already discussed in #10661.

I agree, I see the same results updating existing Front Door issue. But that is still an Azure bug, I see the same result when using ARM template to deploy certificates using the same certificate version. It is not Terraform specific, this is Azure behavior.

**Comment by fdebuire** [comment]
I have never tried with ARM template, but using directly the Azure Portal you can update a backend, a routing table without impacting frontends.
Also if you have two HTTPS frontends and you update one, the other one is not updated. 
From what you are saying I understand that the API/SDK seems not so nice to use but using the Azure Portal can achieve the deployment time they mention in their documentation ([Frontdoor deployment time](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-faq#how-long-does-it-take-to-deploy-an-azure-front-door--does-my-front-door-still-work-when-being-updated-)) so there might be a way to achieve the same using Terraform/ARM.
