### ISSUE TITLE
`azurerm_storage_blob` file uploads

### ISSUE THREAD

**Issue by seitosan** [terraform-providers/terraform-provider-azurerm#1129]
Hello,

I have a question about the creation of blob file in a blob container.

I Have a Resource Group wich contain a storage account and a container blob inside it. I would like create a file in this blob container but I failed. 

I use the source parameter but the file doesn't created in the blob container. 

Can you help me to understand the reason ? 

Regards,

**Comment by tombuildsstuff** [comment]
hi @seitosan 

Thanks for opening this issue.

So that we can take a look into this would it be possible to know which version of Terraform and the AzureRM Provider you're using - and to see the configuration which you're attempting to use?

Thanks!

**Comment by seitosan** [comment]
Hello,

this is my version : 
Terraform v0.11.7
azurerm v1.3.2


and my configuration is the following : 

`
resource "azurerm_resource_group" "resgrp" {
   name = "${var.azurerm_RG_name}"
   location = "${var.azurerm_location}"
}
resource "azurerm_storage_account" "storageaccount" {
   name = "${var.azurerm_sa_name}"
   resource_group_name = "${var.azurerm_RG_name}"
   location = "${var.azurerm_location}"
   account_tier = "Standard"
   account_replication_type = "GRS"
}
resource "azurerm_storage_container" "blobstorage" {
   name = "${var.azurerm_website_reponame}"
   resource_group_name = "${azurerm_resource_group.resgrp.name}"
   storage_account_name = "${azurerm_storage_account.storageaccount.name}"
   container_access_type = "blob"
}
resource "azurerm_storage_blob" "blobobject" {
   depends_on=  ["azurerm_storage_container.blobstorage"]
   name = "index.html"
   resource_group_name = "${azurerm_resource_group.resgrp.name}"
   storage_account_name = "${azurerm_storage_account.storageaccount.name}"
   storage_container_name = "${azurerm_storage_container.blobstorage.name}"
   source="./index.html"

}

# Configure your outputs
output "url" {
   value = "http://${azurerm_storage_account.storageaccount.name}.blob.core.windows.net/${azurerm_storage_container.blobstorage.name}/index.html"
}
`

**Comment by tombuildsstuff** [comment]
@seitosan from what I can see the `source` value may need to be `index.html` rather than `./index.html` - but this otherwise looks correct. is there an associated error message that you see? In addition - are you running this within a Module?

Thanks!

**Comment by seitosan** [comment]
Nop, i have only this message : 

azurerm_storage_blob.blobobject: Creating...
  attempts:               "" => "1"
  name:                   "" => "index.html"
  parallelism:            "" => "8"
  resource_group_name:    "" => "artifaktrg"
  size:                   "" => "0"
  source:                 "" => "./index.html"
  storage_account_name:   "" => "storageaccount"
  storage_container_name: "" => "testartifactsimplestaticindex"
  url:                    "" => "<computed>"
azurerm_storage_blob.blobobject: Creation complete after 0s

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

I run terraform in a docker container and not in a module. 

Thanks

**Comment by seitosan** [comment]
@tombuildsstuff Nop, i have only this message :

azurerm_storage_blob.blobobject: Creating...
attempts: "" => "1"
name: "" => "index.html"
parallelism: "" => "8"
resource_group_name: "" => "resgrp"
size: "" => "0"
source: "" => "./index.html"
storage_account_name: "" => "storageaccount"
storage_container_name: "" => "testsimpleindex"
url: "" => ""
azurerm_storage_blob.blobobject: Creation complete after 0s

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

I run terraform in a docker container and not in a module.

I edit the configuration and the index.html instead of ./index.html doesn't work

Thanks

**Comment by seitosan** [comment]
I enable more verbosity on the configuration

I see this logs : 

```
2018/04/16 15:07:13 [DEBUG] apply: azurerm_storage_blob.blobobject: executing Apply
azurerm_storage_blob.blobobject: Creating...
  attempts:               "" => "1"
  name:                   "" => "index.html"
  parallelism:            "" => "8"
  resource_group_name:    "" => "resgrp"
  size:                   "" => "0"
  source:                 "" => "src/index.html"
  storage_account_name:   "" => "storagenamesa"
2018-04-16T15:07:13.568Z [DEBUG] plugin.terraform-provider-azurerm_v1.3.2_x4: 2018/04/16 15:07:13 [INFO] Creating blob "index.html" in storage account "storagenamesa"
  storage_container_name: "" => "simpleindexfilequickstart"
  url:                    "" => "<computed>"
2018-04-16T15:07:13.569Z [DEBUG] plugin.terraform-provider-azurerm_v1.3.2_x4: 2018/04/16 15:07:13 [INFO] Checking for existence of storage blob "index.html".
2018-04-16T15:07:13.588Z [DEBUG] plugin.terraform-provider-azurerm_v1.3.2_x4: 2018/04/16 15:07:13 [INFO] Storage blob "index.html" no longer exists, removing from state...
azurerm_storage_blob.blobobject: Creation complete after 0s```

**Comment by seitosan** [comment]
I try without docker container and I have the same behavior. 

the deploy stay in the apply complete state but the file isn't present in the blob container

**Comment by tombuildsstuff** [comment]
@seitosan taking a look into this I can confirm this behaviour - from what I can see this looks like a regression. I'll update the tags accordingly.

**Comment by seitosan** [comment]
@tombuilsstuff thanks.

I follow this issue and i try again when the problem was solved

**Comment by seitosan** [comment]
@JunyiYi 
Yes as you write  is required when the new blob is not copied from an existing blob. In this case I upload an existing file like specify with source parameter. 

The documentation explain : 

source - (Optional) An absolute path to a file on the local system. Cannot be defined if source_uri is defined

Best regards

**Comment by JunyiYi** [comment]
@seitosan  , but an existing file is not an existing blob. So you are still required to pass the `type` field.
In technical detail, the [source code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_storage_blob.go#L163) indicates that a local file is not a blob, and we need the user to tell us how to upload it (using block or page).

**Comment by seitosan** [comment]
@JunyiYi  It's created an empty file 



```
azurerm_storage_blob.blobobject: Creating...
  attempts:               "" => "1"
  name:                   "" => "index.html"
  parallelism:            "" => "8"
  resource_group_name:    "" => "resgrp"
  size:                   "" => "0"
  source:                 "" => "./src/index.html"
  storage_account_name:   "" => "storagenamesa"
  storage_container_name: "" => "simpleindexfilequickstart"
  type:                   "" => "block"
  url:                    "" => "<computed>"
azurerm_storage_blob.blobobject: Creation complete after 1s (ID: index.html)

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

Normal ?

**Comment by seitosan** [comment]
I have this file tree

Root
    Terraform.tf
     src
          Index.html

**Comment by JunyiYi** [comment]
@seitosan , can you just try exactly my code snippet above because it is working for me. I can see my HTML by clicking the output URL. Make sure your file structure to be:
main.tf
index.html

**Comment by seitosan** [comment]
@JunyiYi it's doesn't work 

```
azurerm_storage_blob.blobobject: Creating...
  attempts:               "" => "1"
  name:                   "" => "index.html"
  parallelism:            "" => "8"
  resource_group_name:    "" => "resgrp"
  size:                   "" => "0"
  source:                 "" => "index.html"
  storage_account_name:   "" => "storagenamesa"
  storage_container_name: "" => "simpleindexfilequickstart"
  type:                   "" => "block"
  url:                    "" => "<computed>"
azurerm_storage_blob.blobobject: Creation complete after 0s (ID: index.html)
```


This create an empty file named index.html


this is my code : 
```

resource "azurerm_storage_blob" "blobobject" {
  depends_on             = ["azurerm_storage_container.blobstorage"]
  name                   = "index.html"
  resource_group_name    = "${azurerm_resource_group.resgrp.name}"
  storage_account_name   = "${azurerm_storage_account.storageaccount.name}"
  storage_container_name = "${azurerm_storage_container.blobstorage.name}"
  source                 = "index.html"
  type                   = "block"
}
```

My index.html is in my root folder with main.tf like you specify. 

Best regards

**Comment by JunyiYi** [comment]
@seitosan , then it might be some issues with your side because it is completely working on my side. You may check the terraform plugin version, your subscription status. I'm not able to reproduce what you have said. Remember that the portal won't show you anything, you need to use Azure Storage Explorer to confirm whether the blob is uploaded or not.

**Comment by seitosan** [comment]
hello

I removed .terraform folder and all tfstate files . I cleaned all resources on the  subscriptions  and I created a new spn. Now  it work

I have a question about the behaviour. When I reach the output url, I download the file instead of print it on web browser. This behaviour is normal, isn't it ? 

Regards,

**Comment by tombuildsstuff** [comment]
hi @seitosan

> I removed .terraform folder and all tfstate files . I cleaned all resources on the subscriptions and I created a new spn. Now it work

Great - thanks for confirming that.

> I have a question about the behaviour. When I reach the output url, I download the file instead of print it on web browser. This behaviour is normal, isn't it ?

Yes - this behaviour is configured based on the metadata stored against Blobs in Blob Storage, which uses this behaviour by default. At this time it's not possible to configure this metadata via Terraform - but we can look into supporting this in the future; if you're interested in configuring the metadata please open a Feature Request :)

Thanks!

**Comment by AvinashReddyVaka** [comment]
Hi guys, this discussion is very helpful , I am using the same code but in my case I am uploading powershell script into the blob. Terraform uploads it but in the portal I see this warning
"The file 'disableunwantedservices' may not render correctly as it contains an unrecognized extension."

any pointers??? Thank you in advance

**Comment by tombuildsstuff** [comment]
hi @AvinashReddyVaka

> "The file 'disableunwantedservices' may not render correctly as it contains an unrecognized extension."

This error message is returned from the portal since it's unsure how to render the PowerShell Script; however the blob should have uploaded successfully; you can confirm this for sure by checking the SHA of the file / downloading it :)

Given this issue has been resolved I'm going to lock this issue for the moment - please feel free to open another issue if you're noticing specific with specific bugs with Terraform and we'll take a look :)

Thanks!
