### ISSUE TITLE
`azurerm_frontdoor` with custom HTTPS domain causes Terraform Panic when destroying

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#11316]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- AzureRM 2.55
- Terraform 0.14.10
- 
### Affected Resource(s)

* `azurerm_frontdoor`
* `azurerm_frontdoor_custom_https_configuration`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.0"
    }
  }
  required_version = "~> 0.14.4"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "issue-35-brc"
  location = "eastus"
}

resource "azurerm_frontdoor" "fd" {
  name                                         = "fdissue35brc"
  resource_group_name                          = azurerm_resource_group.rg.name
  enforce_backend_pools_certificate_name_check = true
  tags = {
    "Version" = "4.0.2"
  }

  backend_pool {
    health_probe_name   = "health-probe"
    load_balancing_name = "backend-lb"
    name                = "backend"
    backend {
      address     = "www.bing.com"
      host_header = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }
  }

  backend_pool_load_balancing {
    name = "backend-lb"
  }

  backend_pool_health_probe {
    enabled      = true
    name         = "health-probe"
    path         = "/"
    probe_method = "GET"
    protocol     = "Https"
  }

  frontend_endpoint {
    name      = "default"
    host_name = "fdissue35brc.azurefd.net"
  }

  frontend_endpoint {
    name      = "custom"
    host_name = "fdissue35brc.provider.engineering"
  }

  routing_rule {
    accepted_protocols = ["Https"]
    enabled            = true
    frontend_endpoints = ["default"]
    name               = "routing"
    patterns_to_match  = ["/*"]
    forwarding_configuration {
      backend_pool_name             = "backend"
      cache_enabled                 = false
      cache_use_dynamic_compression = false
      custom_forwarding_path        = ""
      forwarding_protocol           = "MatchRequest"
    }
  }
}

resource "azurerm_frontdoor_custom_https_configuration" "fd_custom_url" {
  frontend_endpoint_id              = azurerm_frontdoor.fd.frontend_endpoint[1].id
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

### Debug Output

[Debug Output](https://gist.github.com/bcline760/52d057efdfb85e04be2ebe71db2aba41)

### Panic Output

[Panic Output](https://gist.github.com/bcline760/0cf52fd7a5d8def8a6ef4cbde1ac967a)

### Expected Behaviour

The Front Door should have been deleted

### Actual Behaviour

A Terraform Panic is produced

### Steps to Reproduce

1. `terraform apply`
2. Wait for resources to be created
3. `terraform destroy`

### Additional Info

I've noticed a new behavior w/r/t Front Door from Azure API/Portal. I'm getting errors when attempting to destroy Front Door that the CNAME record has to be removed first.

This is the error I get.
```
Cannot delete frontend endpoint "[custom domain]" because it is still CNAMEd to front door
"[front door name].azurefd.net". Please remove the DNS CNAME records and try again.
```
I don't recall ever seeing that kind of error before.

### References

Could be related to issues
- #11287 
- #8039

**Comment by bcline760** [comment]
I just saw the pinned issue up top. Is this the reason why the Terraform Panic?

**Comment by tiny-dancer** [comment]
@bcline760  very likely- you can check out the az command to opt your sub out of the breaking change in the pinned issue

**Comment by WodansSon** [comment]
**NOTE:** If you have not disabled the behavior on your subscription, it will cause a PANIC in the terraform runtime when you call `destroy`. This is not a bug, it is an expected behavior at this point in time because the `delete` call does not return a future object causing a `nil` reference. 😕 

You can disable the behavior on your subscription by registering the feature flag: 
`az feature register --namespace Microsoft.Network --name BypassCnameCheckForCustomDomainDeletion`
