### ISSUE TITLE
Failure sending request: StatusCode=0 -- Original Error: autorest/azure

### ISSUE THREAD

**Issue by noxouille** [terraform-providers/terraform-provider-azurerm#11356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
AzureRM v2.0.0

### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

https://keybase.pub/noxouille/Terraform-Databricks.zip.encrypted

### Debug Output

Full trace log:
https://gist.github.com/noxouille/17ddb123f7cafd9d417cc0513efcf8a5

```
Error: Error creating/updating Databricks Workspace "iagdat2a02-cac-dbr-dbpm-01" (Resource Group "iagdat2a02-cac-rg-dbpm-01"): databricks.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="WorkspacePatchFailed" Message="Unable to perform Patch operation for the workspace update
```

### Expected Behaviour

Changes should be applied.
In this case, I was trying to change the "Tag" of existing Azure Databricks Workspace Resource.

### Actual Behaviour

Changes (Tag value) have not successfully been applied, cause by the error.

### Steps to Reproduce

1. `terraform validate and apply` via Azure DevOps

### Important Factoids

Based on the codes, there are other resources involved (storage account, keyvault, etc) for the changes of Tag value. The changes were successfully applied to all the resources except Azure Databricks Workspace.
I have discussed this issue with Microsoft support but they were not able to pinpoint the root cause of this particular issue.

### References

None

* #0000

**Comment by njuCZ** [comment]
@noxouille thanks for pointing out this problem. this issue has been solved, could you upgrade the azurerm provider to the latest version and have a try?

**Comment by noxouille** [comment]
hey, thanks for the reply! I have upgraded the azurerm provider and it resolved the issue.
