### ISSUE TITLE
Enable set enable_automatic_updates = false when upgrade_mode = "Automatic" in azurerm_windows_virtual_machine_scale_set

### ISSUE THREAD

**Issue by nellya-alf** [terraform-providers/terraform-provider-azurerm#11361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_windows_virtual_machine_scale_set`
`
### Expected Behaviour
 
Create Service Fabric Cluster with  upgrade_mode = "Automatic" and enable_automatic_updates = false as in the image below:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/74546272/115143452-0e23ff00-a050-11eb-8d94-f57d9fd8a261.png)
s.githubusercontent.com/74546272/115143352-69a1bd00-a04f-11eb-8814-8620e1b46929.png)

### Actual Behaviour

I'm currently using ARM templates to create Service Fabric clusters. The cluster uses windows VMSS with the following configurations: 
upgradePolicy = "Automatic" 
enableAutomaticUpdates = "false"
The cluster was created with no issues every time, as shown in the image below in the Expected Behavior section. 

However, when I try to create a Service Fabric cluster in Terraform with the same configurations 

```terraform
resource "azurerm_windows_virtual_machine_scale_set" "sf_vmss" {
  upgrade_mode         = "Automatic"
  enable_automatic_updates = false
}
````
I'm getting the following error :
```terraform
Error: `enable_automatic_updates` must be set to `true` when `upgrade_mode` is set to `Automatic`

  on .terraform\modules\stg_servicefabric_cluster\vmss.tf line 2, in resource "azurerm_windows_virtual_machine_scale_set" "sf_vmss":
   2: resource "azurerm_windows_virtual_machine_scale_set" "sf_vmss" {
```

I would like to know why this option is not available? And could it be fixed?
Since, as long as it is not possible, it prevents us from using Terraform for service fabric creation instead of the ARM templates.

**Comment by assafbari** [comment]
I'm encountering the same issue while using azurerm_windows_virtual_machine_scale_set to configuring a scale set via Terraform.
This issues seems related to provisioning via TF specifically, because it dose not reproduced when using ARM deployment or UI (Azure portal)
