### ISSUE TITLE
Azure sentinel analytics scheduled rule cannot be applied.

### ISSUE THREAD

**Issue by rikunarhi-solita** [terraform-providers/terraform-provider-azurerm#11369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.13.6
Azurerm tested 2.56.0,2.45.1 and 2.49.1

### Affected Resource(s)

* `azurerm_sentinel_alert_rule_scheduled`

### Terraform Configuration Files

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "example" {
  name                       = data.azurerm_sentinel_alert_rule_template.template.id
  log_analytics_workspace_id = var.workspace_resource_id
  display_name               = each.key
  severity                   = data.azurerm_sentinel_alert_rule_template.template.scheduled_template.0.severity
  query                      = data.azurerm_sentinel_alert_rule_template.template.scheduled_template.0.query
}
```

### Expected Behaviour

Scheduled  analytics rule alert would be created

### Actual Behaviour

##[error]Error: checking for existing Sentinel Alert Rule Scheduled "Alert Rule: (Name \"/subscriptions/zzzzz/resourceGroups/xxxxx/providers/Microsoft.OperationalInsights/workspaces/xxxxx/providers/Microsoft.SecurityInsights/AlertRuleTemplates/26a3b261-b997-4374-94ea-6c37f67f4f39\" / Workspace Name \"xxxxx\" / Resource Group \"xxxxxx\")": securityinsight.AlertRulesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'westeurope' and API version '2019-01-01-preview' for type 'workspaces'. The supported api-versions are '2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiacentral, australiaeast, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast'."

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Tested on two different tenants

### References

* #0000

**Comment by rikunarhi-solita** [comment]
Any updates on the issue?

**Comment by kaovd** [comment]
Can you provide a larger snippet of the config you are using? Easier to debug if I can reproduce. I'm using a similar sort of implemenation for fetching various templates i.e msincident, scheduled, fusion and pushing them back into rules

**Comment by rikunarhi-solita** [comment]
```HCL
data "azurerm_sentinel_alert_rule_template" "template_aad" {
    for_each = toset(var.azure_sentinel_rule_template_scheduled_AAD_displaynames)
    log_analytics_workspace_id = var.workspace_resource_id
    display_name = each.key
}

resource "azurerm_sentinel_alert_rule_scheduled" "rules_aad" {
  for_each = toset(var.azure_sentinel_rule_template_scheduled_AAD_displaynames)
  name                       = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].id
  log_analytics_workspace_id = var.workspace_resource_id
  display_name               = each.key
  severity                   = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.severity
  query                      = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.query
  query_frequency            = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.query_frequency
  query_period               = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.query_period
  tactics                    = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.tactics
  trigger_operator           = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.trigger_operator
  trigger_threshold          = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.trigger_threshold
}

variable "azure_sentinel_rule_template_scheduled_AAD_displaynames" {
  description = "Displaynames for Azure Active Directory rules that want to applied"
  default = [
      "Modified domain federation trust settings",
      "First access credential added to Application or Service Principal where no credential was present",
      "Suspicious application consent similar to O365 Attack Toolkit",
      "Correlate Unfamiliar sign-in properties and atypical travel alerts",
      "Brute force attack against Azure Portal",
      "MFA disabled for a user",
      "Password spray attack against Azure AD application",
      "Rare application consent",
      "Credential added after admin consented to Application",
      "Mail.Read Permissions Granted to Application",
      "Sign-ins from IPs that attempt sign-ins to disabled accounts",
      "Successful logon from IP and failure from a different IP",
      "Explicit MFA Deny",
      "Failed AzureAD logons but success logon to host",
      "Anomalous sign-in location by user account and authenticating application",
      "Attempts to sign in to disabled accounts",
      "Distributed Password cracking attempts in AzureAD",
      "Anomalous login followed by Teams action",
      "User added to Azure Active Directory Privileged Groups",
      "Suspicious application consent similar to PwnAuth",
      "Failed host logons but success logon to AzureAD",
      "New access credential added to Application or Service Principal",
      "Suspicious application consent for offline access",
      "Failed login attempts to Azure Portal",
      "Azure Active Directory PowerShell accessing non-AAD resources",
      "Attempt to bypass conditional access rule in Azure AD",
  ]
}
```

Here is part what we are trying to achieve.

**Comment by kaovd** [comment]
I see you are specifying the output of the .id result into the name value, the .id output actually exports the fully qualified sentinel resource Id, so rather than ending up with a GUID you end ip with /subscriptions/... etc. As you can imagine this causes the API to freak out. Off the back of this if anything should probably make docs more clear / make a .guid export as an option from the rule. 

This will fix this:
```hcl
data "azurerm_sentinel_alert_rule_template" "template_aad" {
    for_each = toset(var.azure_sentinel_rule_template_scheduled_AAD_displaynames)
    log_analytics_workspace_id = var.workspace_resource_id
    display_name = each.key
}

resource "azurerm_sentinel_alert_rule_scheduled" "rules_aad" {
  for_each = toset(var.azure_sentinel_rule_template_scheduled_AAD_displaynames)
  name                       = element(split("/", data.azurerm_sentinel_alert_rule_template.template_aad[each.key].id), length(split("/", data.azurerm_sentinel_alert_rule_template.template_aad[each.key].id))-1)
  log_analytics_workspace_id = var.workspace_resource_id
  alert_rule_template_guid = element(split("/", data.azurerm_sentinel_alert_rule_template.template_aad[each.key].id), length(split("/", data.azurerm_sentinel_alert_rule_template.template_aad[each.key].id))-1)
  display_name               = each.key
  severity                   = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.severity
  query                      = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.query
  query_frequency            = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.query_frequency
  query_period               = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.query_period
  tactics                    = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.tactics
  trigger_operator           = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.trigger_operator
  trigger_threshold          = data.azurerm_sentinel_alert_rule_template.template_aad[each.key].scheduled_template.0.trigger_threshold
}
```
We have to essentially pull the GUID out via a split then element grab as referenced in  the docs. I'm not actually sure if the provider has an option to return this value from a quick glance although if it was really needed we could implement it as an output, although using the split and element functions should do for now.

**Comment by rikunarhi-solita** [comment]
Hey,
This fix was indeed the correct one. We had the wrong name which was casing this.
