### ISSUE TITLE
azurerm_subscription should be able to search by display_name

### ISSUE THREAD

**Issue by donwlewis** [terraform-providers/terraform-provider-azurerm#11379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to be able to find an exact subscription via display name.  I know that the `azurerm_subscriptions` research is able to do it, but it would be great to be able to pin-point an exact subscription.

### New or Affected Resource(s)

`azurerm_subscription`

### Potential Terraform Configuration

```hcl
data azurerm_subscription "main" {
  display_name = "mysubscription"
}
```

### References

* #0000

**Comment by donwlewis** [comment]
After doing a little research on this, I think the best approach would be the leverage the `azurerm_subscriptions` resource, and then add an `exact_match` property.  I have something working in testing.  I can try and submit a PR for this.

**Comment by magodo** [comment]
Does a [for expression](https://www.terraform.io/docs/language/expressions/for.html) like below do the same thing:

```
> [for elem in [{name= "foo", id=123}, {name="foo", id=456}, {name="bar", id=789}]: elem if elem.name=="foo"]
[
  {
    "id" = 123
    "name" = "foo"
  },
  {
    "id" = 456
    "name" = "foo"
  },
]
```
