### ISSUE TITLE
Destroy azurerm_network_security_rule resource is not working as expected

### ISSUE THREAD

**Issue by DavyGuedes** [terraform-providers/terraform-provider-azurerm#11381]
This issue was originally opened by @skal from StackOverflow and I have the same issue.
```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.49.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```
Terraform Configuration Files
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.49.0"
    }
  }
}

provider "azurerm" {
  features {}
}

locals {
  prefix = "reproducecore"
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "rg-${local.prefix}"
  location = "westeurope"
}

resource "azurerm_network_security_group" "example" {
  name                = "example-nsg"
  location            = var.LOCATION
  resource_group_name = azurerm_resource_group.example.name
}


resource "azurerm_network_security_rule" "example" {

  count = var.ENABLE_RULE ? 1 : 0
                                                   
  name                                                   = "example"
  description                                          = "example"
  priority                                                = 1000
  direction                                              = "Inbound"
  access                                                  = "Allow"
  protocol                                               = "Tcp"
  source_port_range                               = "*"
  destination_port_range                        = "8080"
  source_address_prefix                          = "103.85.181.50"
  destination_address_prefix                   = "*"
  resource_group_name                          = azurerm_resource_group.example.name
  network_security_group_name             = azurerm_network_security_group.example.name
  
}
```
Error Output
I can add or update a rule successfully. If I remove an azurerm_network_security_rule resource terraform tells me it is destroyed, but if I look at the rule definition in Azure, it is still there.

Expected Behavior
Destroy rule when remove the rule block or set ENABLE_RULE  to false, it should destroy the network security rule.

Actual Behavior
Terraform says the resources have been destroyed. But when I check the Azure portal, the feature is still there.

Steps to Reproduce
- terraform init && terraform apply with ENABLE_RULE=true `terraform apply -var="ENABLE_RULE=true"`
- comment the network rule or set ENABLE_RULE false 
- terraform plan 
- terraform apply (`terraform apply -var="ENABLE_RULE=false"`)
- Additional Context

References
https://stackoverflow.com/questions/67025281/terraform-resource-azurerm-network-security-rule-destroy

**Comment by magodo** [comment]
@DavyGuedes Would you please be more specific on *the feature is still there*? Do you mean you can still see the exact NSR named "example" shows up in the NSG's "Overview" blade in portal?

**Comment by DavyGuedes** [comment]
Hi @magodo 
Yes, the NSG rule is still present in the NSG, although Terraform reports that the resource has been destroyed. That is, it is as if after the terraform "destroys" the resource, the resource would be destroyed only in the state but not in Azure.

**Comment by magodo** [comment]
That's weired. Can you confirm if the NSR is of the exact name as you've defined in the TF config, rather than introduced by some policy elsewhere?

**Comment by magodo** [comment]
Another way to confirm this is you can try to do a second `terraform apply` after you destroyed the NSRs, if the resouce still exist in Azure, then Terraform will raise error complaining the resource already exist and ask you to import it.

**Comment by DavyGuedes** [comment]
After a second `terraform apply` it throw a error and says that resource already existing and should be imported.
If, for example, a create two rules with terraform, run `terraform apply`, delete the first one form .tf code and update the second one, terraform will destroy the first rule from state and says that destruction is completed and regarding the second one it will be updated.
So far, it only create or update network security rule, but not destroy on Azure.

**Comment by DavyGuedes** [comment]
I can provide a sample project to demonstrate this behavior at night.

**Comment by skal** [comment]
Dear both,
thank you for sharing, but unfortunately, I'm not really involved within
this code: @skal from StackOverflow != @skal from Github ;-)
Regards,
    Samuel

**Comment by magodo** [comment]
@DavyGuedes Thank you and that would be helpful! BTW, I indeed tried with your config above, and a second `terraform apply` can succeed. Also, I can see the DELETE request for the destroy operation, and the first GET in the second `terraform apply` for the NSR returns 404.

**Comment by DavyGuedes** [comment]
Hi you are right
Sorry, my mistake. I will close this issue now. (I appreciate your help.)
Thanks!

I am using a YAML pipeline to use terraform commands as pipelines in Azure DevOps.
So I have a pipeline with two stage for apply commands, one with the security rule enabled by override the `-var` parameter with cli arguments, and the second to apply the configuration using the same library from DevOPs (but with security rule disabled by default)
I found that in my library had that rule enabled by mistake.
