### ISSUE TITLE
Support for data sources: azurerm_storage_table_entity and azurerm_storage_blob

### ISSUE THREAD

**Issue by avishnyakov** [terraform-providers/terraform-provider-azurerm#11384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to have data sources to support `azurerm_storage_blob` and  `azurerm_storage_table_entity` resources. This way, Terraform can benefit from data stored in either storage blob or storage table. 

This is useful for sharing data between configs, for examples as per this article by HashiCorp:
* [Alternative Ways to Share Data Between Configurations](https://www.terraform.io/docs/language/state/remote-state-data.html#alternative-ways-to-share-data-between-configurations)

### New or Affected Resource(s)

* azurerm_storage_table_entity 
* azurerm_storage_blob

### Potential Terraform Configuration

```hcl
# TBD
```

### References

* [HashiCorp: The terraform_remote_state Data Source](https://www.terraform.io/docs/language/state/remote-state-data.html#alternative-ways-to-share-data-between-configurations)
* [HashiCorp: The terraform_remote_state Data Source, Alternative Ways to Share Data Between Configurations](https://www.terraform.io/docs/language/state/remote-state-data.html#alternative-ways-to-share-data-between-configurations)
* [azurerm_storage_blob](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_blob)
* [azurerm_storage_table_entity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_table_entity)

**Comment by alvintang** [comment]
submitted a PR for storage blob data source. I can also work on the table entity data source if that's ok.
