### ISSUE TITLE
Feature Request: azurerm_policy_assignment - add support for setting Exclusions

### ISSUE THREAD

**Issue by russellds** [terraform-providers/terraform-provider-azurerm#1138]
Please add support for setting Azure Policy Assignment Exclusions. Exclusions allow Resource Groups or Resources in a Resoure Group to be excluded from the policy.

**Comment by KevinBrooke** [comment]
+1 this would be great for locking down resource types to certain resource groups. e.g. Policy = no network resources, scope = subscription, exception = networking resource group. Only the networking team have access to the networking resource group.

**Comment by JasonNguyenTX** [comment]
Hi, is there plan to support policy exclusion?  it would be great to have it supported.  thx
