### ISSUE TITLE
The azurerm_subscription Reference Page is Truncated

### ISSUE THREAD

**Issue by endajf** [terraform-providers/terraform-provider-azurerm#11385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Details

The "Import" section of the azurerm_subscription resource page is truncated. The "e.g." part of the last sentence is not finished:

> In this scenario, the subscription_id property can be completed and Terraform will assume control of the existing subscription by creating an Alias. e.g.

The documentation link is here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription.

The source code is here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/subscription.html.markdown.

**Comment by jackofallops** [comment]
Closed by #11469 (Thanks for the catch @endajf !)
