### ISSUE TITLE
azurerm_databricks_workspace tags argument always forces replacement of databricks_workspace resource

### ISSUE THREAD

**Issue by JeetSharan** [terraform-providers/terraform-provider-azurerm#11395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.15.0 
AzureRM version = ">= 2.26"

### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

```hcl
#
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 2.26"
    }
  }

  required_version = ">= 0.14.9"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "testrg"
  location = "eastus2"
}
resource "azurerm_databricks_workspace" "workspace" {
  name                = "testws"
  resource_group_name = "testrg"
  location            = "eastus2"
  sku                 = "standard"

  tags = {
    Environment = "terraformtest"
	WorkspacePatch = "terraformtest"
  }
}
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour
If user changes the tags param and terraform apply - it should only update the tags i.e it should call PATCH

### Actual Behaviour
Tags change forces to destroy and re-create the complete workspace object. It is calling PUT even though only tags are changed

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by WodansSon** [comment]
@JeetSharan I am unable to reproduce this behavior. It appears to be working as expected.

**Comment by JeetSharan** [comment]
> @JeetSharan I am unable to reproduce this behavior. It appears to be working as expected.

The tags update is calling the PUT call from RP side- it changes the tags in the workspace object. But we want the same tags to be propagate to the Managed resource group resources associated to workspace. This propagation is handled in our PATCH call.
So the ask is to have the tags update in terraform such that it calls PATCH API from RP end

**Comment by WodansSon** [comment]
@JeetSharan, once we had our teams meeting I was able to get a repro for this and have created a PR for the fix.
