### ISSUE TITLE
azurerm_virtual_network_gateway custom_route change recreates gateway

### ISSUE THREAD

**Issue by chriskinsman** [terraform-providers/terraform-provider-azurerm#11403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0

### Affected Resource(s)

* `azurerm_virtual_network_gateway `

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "vpn" {
  name     = "VPN"
  location = "West US"
}

resource "azurerm_virtual_network" "vpn" {
  name                = "vpn"
  location            = "West US"
  resource_group_name = azurerm_resource_group.vpn.name
  address_space       = ["10.40.0.0/26"]
}

resource "azurerm_subnet" "gateway_subnet" {
  name                 = "GatewaySubnet"
  resource_group_name  = azurerm_resource_group.vpn.name
  virtual_network_name = azurerm_virtual_network.vpn.name
  address_prefixes     = ["10.40.0.0/26"]
}

resource "azurerm_public_ip" "vpn_public_ip" {
  name                = "VPNGatewayPublicIP"
  resource_group_name = azurerm_resource_group.vpn.name
  allocation_method   = "Dynamic"
  location            = "West US"
  domain_name_label   = "my-vpn"

resource "azurerm_virtual_network_gateway" "gw" {
  name                = "VPNGateway"
  location            = azurerm_resource_group.vpn.location
  resource_group_name = azurerm_resource_group.vpn.name

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false
  sku           = "VpnGw1"

  ip_configuration {
    public_ip_address_id          = azurerm_public_ip.vpn_public_ip.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.gateway_subnet.id
  }

  custom_route {
    address_prefixes = ["10.1.0.0/16"]
  }

  vpn_client_configuration {
    address_space = ["10.40.1.0/24"]

    vpn_client_protocols = ["OpenVPN"]

    aad_tenant   = "https://login.microsoftonline.com/${local.tenant_id}"
    aad_issuer   = "https://sts.windows.net/${local.tenant_id}/"
    aad_audience = "41b23e61-6c1e-4545-b367-cd054e0ed4b4"
  }
}

```

### Expected Behaviour

New route is added to existing VPN Gateway

### Actual Behaviour

VPN Gateway is deleted and then created with the new custom routes

### Steps to Reproduce

1. terraform apply
2. Add a new address prefix
3. terraform apply

### Important Factoids

Adding custom routes to an existing gateway is supported: 

```ps
Set-AzVirtualNetworkGateway -VirtualNetworkGateway $gw -CustomRoute x.x.x.x/xx , y.y.y.y/yy
```

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. This property is currently set as `ForceNew` indeed. I'll shoot in a PR and run some tests.
