### ISSUE TITLE
Support for retrieving Storage Account Key from KV in Data Factory File Storage Linked Service 

### ISSUE THREAD

**Issue by Robinson308** [terraform-providers/terraform-provider-azurerm#11408]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
### Description
#10735 recently introduced Key Vault password support for Azure SQL Linked Services in Data Factory.
Could we have something similar for File Storage Linked Services, to allow the Storage Account Key to be retrieved from a KV secret? 

### New or Affected Resource(s)

azurerm_data_factory_linked_service_azure_file_storage

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_linked_service_azure_file_storage" "AzureFileStorage23" {
  name                     = "AzureFileStorage23"
  resource_group_name      = azurerm_resource_group.myrg.name
  data_factory_name        = azurerm_data_factory.myfactory.name
  integration_runtime_name = "AutoResolveIntegrationRuntime"
  connection_string        = "DefaultEndpointsProtocol=https;AccountName=mystorage;"
  file_share               = "datashare"
  key_vault_password {
    linked_service_name = "AzureKeyVault"
	secret_name = "StorageAccountKey"
  }
}
```

### References

* #10735

**Comment by favoretti** [comment]
Hi, thank you for reporting this. I'll try to get this added after I'm done working on something else. Should be able to do it today though.
