### ISSUE TITLE
Feature Request: Support Image Registry Credentials for Azure Container Instance Groups

### ISSUE THREAD

**Issue by cscheib** [terraform-providers/terraform-provider-azurerm#1142]
Use Case: I'm looking to use ACI for a few multi-container deployments, until AKS is out of preview.  I'm building a couple custom images, and storing them in the Azure Container Registry.  It appears as though the current provider is not providing an interface to input registry credentials.

I'm hoping not to have to resort to learning AzureRM Templating 😄 

**Terraform Resource Documentation:**
https://www.terraform.io/docs/providers/azurerm/r/container_group.html

**Microsoft Azure Container Instance Documentation:**
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups
https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/createorupdate#imageregistrycredential

**Comment by lawrencegripper** [comment]
This is done here #1529 should be good to close this one

**Comment by tombuildsstuff** [comment]
@lawrencegripper thanks for the ping, agreed this appears to be fixed - closing.
