### ISSUE TITLE
Support for Public IP Prefix in Azure Kubernetes Cluster

### ISSUE THREAD

**Issue by vsabella** [terraform-providers/terraform-provider-azurerm#11424]
Azure Kubernetes Cluster supports using Public IP Prefixes for node pools. AKS terraform Provider should support this feature:

https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#use-a-public-ip-prefix 

```bash
az aks create -g MyResourceGroup3 -n MyManagedCluster -l eastus --enable-node-public-ip --node-public-ip-prefix /subscriptions/<subscription-id>/resourcegroups/MyResourceGroup3/providers/Microsoft.Network/publicIPPrefixes/MyPublicIPPrefix
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by nickvth** [comment]
Please also add --node-public-ip-prefix-id to cluster nodepool
