### ISSUE TITLE
Review and update Azure Verified Modules in the Registry using this provider

### ISSUE THREAD

**Issue by achandmsft** [terraform-providers/terraform-provider-azurerm#1146]
Review and update all Azure verified modules in the registry

**Comment by catsby** [comment]
Hello! There looks to 15 verified modules for Azure at this time, is there an issue you're encountering? Mentioning specific things you're looking for, or issues you're encountering, will help us take the right action. Thanks!

**Comment by achandmsft** [comment]
@catsby we are standardizing tests across the board. This tracks that work.

**Comment by metacpp** [comment]
All the verified modules under Azure organization has been enabled the CI with Terratest integration. I am going to close this issue, no any further action item.
