### ISSUE TITLE
Static azurerm_public_ip known only after apply

### ISSUE THREAD

**Issue by BostjanBozic** [terraform-providers/terraform-provider-azurerm#11477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
`0.15.0`

### Affected Resource(s)
* `azurerm_public_ip`

### Terraform Configuration Files
```hcl
resource "azurerm_public_ip" "ingress" {
  name                              = "aks-ingress"
  resource_group_name = data.azurerm_resource_group.main.name
  location                          = data.azurerm_resource_group.main.location
  allocation_method        = "Static"

  tags = var.tags
}

resource "azurerm_dns_a_record" "ingress" {
  depends_on                  = [azurerm_public_ip.ingress]
  name                              = ""
  resource_group_name = data.azurerm_resource_group.main.name
  zone_name                    = "test-dns"
  ttl                                    = 180
  records                          = azurerm_public_ip.ingress.ip_address
}
```

### Debug Output
https://gist.github.com/BostjanBozic/813db31abeb1b60b277ca8590eddf3e3

### Expected Behaviour
As `allocation_method` is set to `Static`, IP should be available and be used for creating new DNS record.

### Actual Behaviour
Eventhough `allocation_method` is set to `Static`, IP can not be used for other resources.

### Steps to Reproduce

1. `terraform apply`

### References
I found similar issue, though `Dynamic` allocation method is used there. https://github.com/terraform-providers/terraform-provider-azurerm/issues/11115

* #0000

**Comment by CaptainStealthy** [comment]
Looking at the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_a_record), I think you just need to wrap the IP in an array, because the resource expects a *set* of IP addresses, not a string.

```
records = [azurerm_public_ip.ingress.ip_address]
```

**Comment by smford** [comment]
> Looking at the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_a_record), I think you just need to wrap the IP in an array, because the resource expects a _set_ of IP addresses, not a string.
> 
> ```
> records = [azurerm_public_ip.ingress.ip_address]
> ```

This is the correct answer, and isn't an issue.

You can do it two ways:
1. records = [azurerm_public_ip.ingress.ip_address]
or
2. target_resource_id  = azurerm_public_ip.ingress.id

**Comment by BostjanBozic** [comment]
That did the trick, it seems I was mixing id and ip structure there.

What could maybe still be changed is first part of error output, as this got me off the track:
```
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 83, in resource "azurerm_dns_a_record" "ingress":
│   83:   records             = azurerm_public_ip.ingress.ip_address
│     ├────────────────
│     │ azurerm_public_ip.ingress.ip_address is a string, known only after apply
│ 
│ Inappropriate value for attribute "records": set of string required.
```

I thought the problem is that IP at that point is not available (error below points toward correct error though).
