### ISSUE TITLE
azurerm_app_service_plan - Unable to configure imported ASP (says kind is "app")

### ISSUE THREAD

**Issue by Midacts** [terraform-providers/terraform-provider-azurerm#1148]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.11.7
+ provider.azurerm v1.3.2

### Affected Resource(s)
Please list the resources as a list, for example:
- app_service_plan

### Terraform Configuration Files
```hcl
resource "azurerm_app_service_plan" "ASP-1" {

	name                		= "ASP-1"
	location            		= "${azurerm_resource_group.ASE-1.location}"
	resource_group_name 		= "${azurerm_resource_group.ASE1.name}"
	
	sku {
		tier		= "Isolated"
		size		= "I1"
		capacity	= 0
	}

	properties {
		app_service_environment_id	= "/subscriptions/xxxxxx/resourceGroups/ASE-1/providers/Microsoft.Web/hostingEnvironments/ASE-1"
	}

}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/Midacts/d0b9508407c3eeb91fe226969db5abf1

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

No panic

### Expected Behavior
What should have happened?

It should see the already existing ASP and not try to create a new one

### Actual Behavior
What actually happened?

terraform apply says it will remove the existing ASP and create a new one instead of seeing the settings as being correct

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Nothing special

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by tombuildsstuff** [comment]
hey @Midacts 

Thanks for opening this issue :)

Taking a look into this, I can confirm based on [this ARM Template](https://github.com/Azure/azure-quickstart-templates/blob/c41b781c2df3050d4ef3be8685fe36aa72161cde/101-webapp-custom-deployment-slots/azuredeploy.json#L37) that `app` is also a valid value for the `kind` field - however I can only find limited references to this field. Out of interest was this an existing resource that you've imported, or for a new one created via Terraform?

Thanks!

**Comment by Midacts** [comment]
This is an existing resources that I am trying to import.

I'm working on importing our sandbox azure environment into Terraform to
get our team onboard to using it.

**Comment by Midacts** [comment]
Awesome.
Thanks for your help on this (and for knowing what was going on to troubleshoot).

**Comment by tombuildsstuff** [comment]
@Midacts apologies, I thought I'd posted a comment in here. This isn't released yet but will be as part of v1.4.0 in the near future - when that's released, you can update to the new version by using:

```
provider "azurerm" {
  version = "=1.4.0"
}
```

and re-running `terraform init` :)

**Comment by Midacts** [comment]
No problem.
Sounds good. Thanks again for the help.

**Comment by tombuildsstuff** [comment]
hey @Midacts 

Just to let you know that v1.4.0 of the Azure Provider has been released which includes the fix for this :)

Thanks!

**Comment by Phydeauxman** [comment]
@Midacts I ran the same thing in Cloud Shell and it is still telling me 1.3

**Comment by Midacts** [comment]
@Phydeauxman 
This probably isn't best practice, but I did it for testing. I renamed my .terraform directory and ran `terraform init` and it repulled in all the requirements I had including the azurerm provider plugin..
