### ISSUE TITLE
Error waiting for Container Group to finish deleting: couldn't find resource (21 retries)

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#11495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0

### Affected Resource(s)

* `azurerm_container_group`

### Expected Behaviour

The Container Group is expected to be deleted and re-created afterwards.

### Actual Behaviour

Error: Error waiting for Container Group "XXXX" (Resource Group "XXXX") to finish deleting: couldn't find resource (21 retries)

### Steps to Reproduce

Create container group with default configuration
terraform apply
Change parameters (f.e. Environment)
terraform apply

**Comment by JamesDLD** [comment]
Just tested and same issue with hashicorp/azurerm v2.57.0

**Comment by JamesDLD** [comment]
Just tried this morning with azurerm v2.57.0 and Terraform v0.15.1 on linux_amd64 and the deletion and re creation worked well, it's probably an Issue with Azure API.

**Comment by katbyte** [comment]
Going to close this as it seems to be working now - do reopen this if it becomes a problem again!
