### ISSUE TITLE
azurerm_eventgrid_system_topic doesn't support 'Microsoft.PolicyInsights.PolicyStates' topic type

### ISSUE THREAD

**Issue by matt-ward-airwalk** [terraform-providers/terraform-provider-azurerm#11523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.14.10
AzureRM 2.56.0

### Affected Resource(s)

azurerm_eventgrid_system_topic

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_system_topic" "main" {
  name                   = "example-system-topic"
  location               = "Global"
  resource_group_name    = azurerm_resource_group.main.name
  source_arm_resource_id = data.azurerm_subscription.current.subscription_id
  topic_type             = "Microsoft.PolicyInsights.PolicyStates"
}
```
### Expected Behaviour

System topic should be created with a type of event set as "Microsoft.PolicyInsights.PolicyStates"

### Actual Behaviour

Fails with;

Error: expected topic_type to be one of [Microsoft.AppConfiguration.ConfigurationStores Microsoft.Communication.CommunicationServices Microsoft.ContainerRegistry.Registries Microsoft.Devices.IoTHubs Microsoft.EventGrid.Domains Microsoft.EventGrid.Topics Microsoft.Eventhub.Namespaces Microsoft.KeyVault.vaults Microsoft.MachineLearningServices.Workspaces Microsoft.Maps.Accounts Microsoft.Media.MediaServices Microsoft.Resources.ResourceGroups Microsoft.Resources.Subscriptions Microsoft.ServiceBus.Namespaces Microsoft.SignalRService.SignalR Microsoft.Storage.StorageAccounts Microsoft.Web.ServerFarms Microsoft.Web.Sites], got Microsoft.PolicyInsights.PolicyStates

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. When I look at the code, the topic type is just a string, which tells me that the error you're getting is coming from the API itself, rather than being a provider limitation. Are you able to create a system topic of that particular type using the portal and if so, can you see which API version does portal use?

**Comment by matt-ward-airwalk** [comment]
I've tested this on the most recent provider and it's now working as expected. So assume the changes to System Event Topic that were included, have also resolved this behaviour

**Comment by favoretti** [comment]
Interesting. Didn't work for me until I upgraded the API. Oh well, this won't hurt either I suppose :)
