### ISSUE TITLE
Using ignore_changes from lifecycle in order to ignore the changes of an object list element actually ignores the entire list

### ISSUE THREAD

**Issue by ben-002** [terraform-providers/terraform-provider-azurerm#11522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform  0.15.0
AzureRM 2.56.0

### Affected Resource(s)

azurerm_function_app

### Terraform Configuration Files
```hcl

resource "azurerm_function_app" "functionapp" {
...
    site_config {
        scm_type = "VSTSRM"
        always_on = true
    }
    lifecycle {
        ignore_changes = [ site_config["scm_type"]
    }
...
}
```

### Expected Behaviour

Only site_config["scm_type"] changes should be ignored

### Actual Behaviour

All site_config changes are ignored, including  site_config["always_on"].

**Comment by favoretti** [comment]
Hey, thank you for reporting this. Can you try `site_config.0.scm_type` instead?

**Comment by ben-002** [comment]
It worked, thank you!

**Comment by favoretti** [comment]
Awesome. Closing then.
