### ISSUE TITLE
azurerm for flexible server - create database

### ISSUE THREAD

**Issue by LukaszSzalek-Tomtom** [terraform-providers/terraform-provider-azurerm#11539]
hi
I would like to use azurerm_postgresql_database to create db on azurerm_postgresql_flexible_server.
but is seems that the call goes to Server instead of FlexibleServer.
Error:
Error: postgresql.DatabasesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.DBForPostgreSQL/servers/fakeDB' under resource group 'myRG' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

Code
resource "azurerm_postgresql_database" "fakeDB_abc" {
depends_on = [azurerm_postgresql_flexible_server.fakeDB]
name = "abc"
resource_group_name = var.RESOURCE_GROUP_NAME
server_name = data.azurerm_postgresql_flexible_server.fakeDB.name
charset = "UTF8"
collation = "English_United States.1252"
}

provider 2.57
TF v0.15.1

Thanks

Lukasz

**Comment by wasfree** [comment]
Please see my new resource request #11538, resource azurerm_postgresql_database won't work with postgres flexible server. This is a different implementation and different API.

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. As @wasfree mentioned, this is indeed a different API and needs a different resource. I'm therefore going to close this issue in favor of #11538, where support for that can be tracked.
