### ISSUE TITLE
New Data Source: `azurerm_route_table`

### ISSUE THREAD

**Issue by valtos** [terraform-providers/terraform-provider-azurerm#1155]
Hi there,
can a data source for "azurerm_route_table" can be added?
We use a script acs-engine to deploy kubernetes cluster (so without terraform) and this autocreate a route table, problem is: all infrastructure vnet/subnet are already created by terraform, so without data source added, it will remove the route table if we tf apply.
Today we add the route_table_id in a static variable in the subnet creation file, but since they happen to destroy and recreate cluster, this is not dynamic...
Thank you

**Comment by tombuildsstuff** [comment]
hey @valtos 

Thanks for opening this issue - I took a look into this on Friday and opened #1203 which adds a new Data Source for Route Tables to the Azure Provider; I've just merged this and as such this will ship with the next version of the AzureRM Provider :)

Thanks!
