### ISSUE TITLE
Support for azurerm_container_registry_token credentials creation

### ISSUE THREAD

**Issue by McSlow** [terraform-providers/terraform-provider-azurerm#11566]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_container_registry_token

### Potential Terraform Configuration

```hcl
Tf 0.15, azurerm 2.57.0
```

There is an azurerm_container_registry_token resource which can generate a Token for an Azure Container Registry.
To use it, one has to generate one or two passwords. This can be done using the UI 
![image](https://user-images.githubusercontent.com/1178921/116895923-f645a100-ac33-11eb-9f96-15404083ad9a.png)
or by using the corresponding az cli command ( https://docs.microsoft.com/en-us/cli/azure/acr/token/credential?view=azure-cli-latest#az_acr_token_credential_generate )

Unfortunately it can't be done using Terraform yet, rendering the azurerm_container_registry_token resource more or less useless ( as far as I did not misunderstood anything )

So it would be nice if there either is an option to generate PW1 and/or PW2 and export them, or add another subresource like azurerm_container_registry_token_password or equal.

**Comment by magodo** [comment]
@McSlow Thank you for openning this issue!

IIRC the password is only available at the first time users generate it (via the `generateCredentials` POST operation), which can't be retrieved later. This means Terraform has no way to get the password on following provisions. 

Therefore, this is not a good candidate in context of Terraform. Instead, you shall provision the token resource via Terraform, whilst generate the passwords via other means and pass in the generated token to Terrafrom via input variables, so as to provision other resources which depend on that token.

For above reason, I'm gonna close this issue for now. If you have any further question, you can ask in one of the [Community Resources](https://www.terraform.io/community.html).
