### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by rjacobsen0** [terraform-providers/terraform-provider-azurerm#11576]
On the page https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_slot there is a Note near the bottom that says

> When type is set to SystemAssigned, The assigned principal_id and tenant_id can be retrieved after the App Service has been created. More details are available below.

But no details are forthcoming!

**Comment by aristosvo** [comment]
This is just fixed in https://github.com/terraform-providers/terraform-provider-azurerm/pull/11574! 👍
