### ISSUE TITLE
Support for App Service deployment slots - Azure Key Vault references

### ISSUE THREAD

**Issue by SebastianBalle** [terraform-providers/terraform-provider-azurerm#11572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `identity` attribute must be exported for the resource `azurerm_app_service_slot` to support Azure Key Vault reference using the object id of the App Service slot. 

### New or Affected Resource(s)

* azurerm_app_service_slot

### Potential Terraform Configuration

Azure Key Vault access policy could use the identity object id similarly as for the azurerm_app_service resource.  

```hcl
resource "azurerm_key_vault_access_policy" "backend" {

  # Key vault reference
  key_vault_id = azurerm_key_vault.main.id

  # Identity IDs
  tenant_id = data.azurerm_client_config.current.tenant_id
  object_id = azurerm_app_service.backend.identity[0].principal_id

  # Permissions
  secret_permissions = [
    "get",
  ]

}
```

### References

* https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

**Comment by aristosvo** [comment]
AFAIK, you can access the Principal ID via `${azurerm_app_service_slot.example.identity.0.principal_id}` and the Tenant ID via `${azurerm_app_service_slot.example.identity.0.tenant_id}`. The logic in the code looks the same for both and it seems even tested, so I expect this to work. Can you try this?

I'll update the documentation after you've confirmed.

**Comment by SebastianBalle** [comment]
I can confirm the functionality. You can close this issue. Thank you for the help.
