### ISSUE TITLE
 app_settings properties from azurerm_function_app_slot added at each plan/apply

### ISSUE THREAD

**Issue by ben-002** [terraform-providers/terraform-provider-azurerm#11577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.15.0
azurerm v2.57.0
### Affected Resource(s)

* `azurerm_function_app_slot`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app_slot" "staging_slot_example" {
  name                       = "staging"
  location                   = "placeholder"
  resource_group_name        = "placeholder"
  app_service_plan_id        = "placeholder"
  function_app_name = "placeholder"
  storage_account_name       = "placeholder"
  storage_account_access_key = "placeholder"
  enable_builtin_logging     = false
  version                    = "~3"

  app_settings = {
    "APPINSIGHTS_INSTRUMENTATIONKEY"        = "placeholder"
    "APPLICATIONINSIGHTS_CONNECTION_STRING" = "placeholder"
    "AzureWebJobsStorage"                   = "storage account connection string placeholder"
    "FUNCTIONS_EXTENSION_VERSION"           = "~3"
    "FUNCTIONS_WORKER_RUNTIME"              = "dotnet"
    "WEBSITE_RUN_FROM_PACKAGE"              = "1"
    "WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG" = "1" 
  }
```

### Expected Behaviour

Use the same app_settings values for "AzureWebJobsStorage" and "FUNCTIONS_EXTENSION_VERSION" at each terraform plan/apply as they already exist and values are not changing. Both are visible in Azure Portal -> Configuration section of the related function app slot.
### Actual Behaviour
At each terraform plan/apply, "AzureWebJobsStorage" and "FUNCTIONS_EXTENSION_VERSION" are considered newly added.

![image](https://user-images.githubusercontent.com/69915112/117022053-97019280-ad00-11eb-837e-bf93637ae54e.png)

**Comment by aristosvo** [comment]
`AzureWebJobsStorage` is created by default based on `storage_account_name` and `storage_account_access_key`, `FUNCTIONS_EXTENSION_VERSION` is set based on `version`.

It's probably good to add this behavior to the docs, I'll try to fix it in a PR.

**Comment by ben-002** [comment]
It worked. Thank you!
