### ISSUE TITLE
ServiceAlreadyExistsInSoftDeletedState error with azurerm_api_management

### ISSUE THREAD

**Issue by TamasSzerb** [terraform-providers/terraform-provider-azurerm#11580]
The following terraform code:

```
resource "azurerm_api_management" "apim" {
  name = var.name
  location = var.location
  resource_group_name = var.resource_group_name
  publisher_name = var.publisher_name
  publisher_email = var.publisher_email
  sku_name = "Developer_1"

  virtual_network_type = var.virtual_network_type
  virtual_network_configuration {
    subnet_id = var.subnet_id
  }

  tags = var.tags
}
```
results this error message:

```
Error: creating/updating API Management Service "apim" (Resource Group "xyz"):
apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- 
Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceAlreadyExistsInSoftDeletedState" 
Message="Api service xyz was soft-deleted. In order to create the new service with the same name, you have to either undelete the service or purge it. See https://aka.ms/apimsoftdelete."
```

is there any idea how to solve this? As I see, terraform with APIM has no soft-delete option as keyvault does:

```
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
      recover_soft_deleted_key_vaults = true
    }
  }
}
```

Maybe there is a time for creating APIM provider feature as well, as Azure is rolling out the new management API for: https://docs.microsoft.com/en-us/azure/api-management/soft-delete

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v0.15.1
on linux_amd64

- Using previously-installed hashicorp/azurerm v2.57.0

**Comment by yupwei68** [comment]
Hi @TamasSzerb , thanks for opening this issue.
I'm working on this. But currently there is some upstream service problems in fixing and releasing. 
I'll raise PR for this once the fix is released.

**Comment by yupwei68** [comment]
duplicated of https://github.com/terraform-providers/terraform-provider-azurerm/issues/11061

**Comment by tombuildsstuff** [comment]
Closing in favour of #11061
