### ISSUE TITLE
Need ability to configure the "performance tier" for `azurerm_managed_disk`

### ISSUE THREAD

**Issue by fcatacut** [terraform-providers/terraform-provider-azurerm#11585]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For certain storage types other than `Standard_LRS`, a "performance tier" option is available in Azure Porta which can be set to a higher performance tier to meet higher demand and return to the initial baseline performance tier once this period is complete.

![image](https://user-images.githubusercontent.com/20847572/117073449-c3a8b080-ace6-11eb-8f36-f0cfba9009b7.png)

This is not currently supported in the `azurerm_managed_disk` resource.

### New or Affected Resource(s)

* azurerm_managed_disk

### Potential Terraform Configuration

```hcl
resource "azurerm_managed_disk" "source" {
  name                 = "data"
  location             = "centralus"
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = "64"
  tier                 = "P6" # New argument
}
```

#### ARM Template snippet

```
"properties": {
    "creationData": {
        "createOption": "Empty"
    },
    "diskSizeGB": 64,
    "diskIOPSReadWrite": 500,
    "diskMBpsReadWrite": 100,
    "encryption": {
        "type": "EncryptionAtRestWithPlatformKey"
    },
    "diskState": "Attached",
    "networkAccessPolicy": "AllowAll",
    "tier": "P10"
}
```

**Comment by aristosvo** [comment]
Gave it a shot, but need some extra configuration around only enabling the option only for Premium SSDs + acceptance tests.
