### ISSUE TITLE
Front Door Creation fails - "We couldn't find a DNS record for custom domain Org-int013.azurefd.net that points to Front Door Org.azurefd.net.To map a domain to this Front Door, create a CNAME record with your DNS provider for custom domain that points to Front Door."

### ISSUE THREAD

**Issue by guywood13** [terraform-providers/terraform-provider-azurerm#11589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_v2.52.0`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "frontdoor" {
  name                                         = "Org-${var.environment}"
  resource_group_name                          = azurerm_resource_group.main.name
  enforce_backend_pools_certificate_name_check = false

  routing_rule {
    name               = "DefaultBackendForwardRule"
    accepted_protocols = ["Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["FrontendEndpoint"]
    forwarding_configuration {
      forwarding_protocol = "HttpsOnly"
      backend_pool_name   = "BackendWebapps"
    }
  }

  # Routing rule to redirect all HTTP traffic to HTTPS endpoint
  routing_rule {
    name               = "HTTPSRedirect"
    accepted_protocols = ["Http"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["FrontendEndpoint"]
    redirect_configuration {
      redirect_protocol = "HttpsOnly"
      redirect_type     = "Moved"
    }
  }

  backend_pool_load_balancing {
    name                            = "LoadBalancingSettings"
    additional_latency_milliseconds = 200 # adding some extra latency ensures even load balancing between both regions, no matter where the client sits
  }

  backend_pool_health_probe {
    name                = "HealthProbeSetting"
    protocol            = "Https"
    probe_method        = "HEAD"
    path                = "/api/Healthz"
    interval_in_seconds = 30
  }

  backend_pool {
    name = "BackendWebapps"

    dynamic "backend" {
      for_each = var.frontdoor_backend_locations
      content {
        host_header = "Org-${var.environment}-${backend.value}-web.azurewebsites.net"
        address     = "Org-${var.environment}-${backend.value}-web.azurewebsites.net"
        http_port   = 80
        https_port  = 443
        enabled     = true
      }
    }

    load_balancing_name = "LoadBalancingSettings"
    health_probe_name   = "HealthProbeSetting"
  }

  backend_pools_send_receive_timeout_seconds = 240

  frontend_endpoint {
    name                                    = "FrontendEndpoint"
    host_name                               = "Org-${var.environment}.azurefd.net"
    custom_https_provisioning_enabled       = false
    session_affinity_enabled                = var.session_affinity_enabled
    web_application_firewall_policy_link_id = var.frontdoor_waf_enable ? azurerm_frontdoor_firewall_policy.waf_policy[0].id : null
  }
  # Due to Terraform swapping the routing rules unnecessarily (i.e. even without any changes to the code above) and potentially impacting live, temp fix to avoid this.
  lifecycle {
    ignore_changes = [
      routing_rule 
    ]
  }

  tags = local.tags
}
```

### Expected Behaviour

A new Front Door resource to be created.

### Actual Behaviour
```
Error: creating Front Door "Org-int013" (Resource Group "Org-int013-shared"): frontdoor.FrontDoorsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="We couldn't find a DNS record for custom domain Org-int013.azurefd.net that points to Front Door Org.azurefd.net.To map a domain to this Front Door, create a CNAME record with your DNS provider for custom domain that points to Front Door."

on front-door.tf line 1, in resource "azurerm_frontdoor" "frontdoor":
1: resource "azurerm_frontdoor" "frontdoor" {
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

First saw this last week and now we cannot setup any new Front Doors with this code which has worked fine previously using this same provider version.  Seems a change on the MS side has caused this and looks very closely related to this issue already raised #11231 although we are not using custom domains.

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/11231

**Comment by guywood13** [comment]
For additional info.  MS asked me to try changing frontend_endpoint host_name as follows:

```hcl
frontend_endpoint {
    host_name                               = "Org-${var.environment}"
```
But this gave the following invalid host_name error:

```
2021-05-05T13:27:18.9939870Z Error: creating Front Door "Org-int013" (Resource Group "Org-int013-shared"): frontdoor.FrontDoorsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Frontend hostname \"111-int013\" is invalid. It must be a valid domain name."
2021-05-05T13:27:18.9940483Z 
2021-05-05T13:27:18.9941034Z   on front-door.tf line 1, in resource "azurerm_frontdoor" "frontdoor":
2021-05-05T13:27:18.9941661Z    1: resource "azurerm_frontdoor" "frontdoor" {
```

**Comment by guywood13** [comment]
Just had a call with MS who wanted me to test hardcoding the Front Door name and host_name so changing in the code:
```
"Org-${var.environment}" to "Org-int013"
"Org-${var.environment}.azurefd.net" to "Org-int013.azurefd.net"
```
This then allowed the Front Door to be created.  However, my previous plans using the original code, the plans looked good:
```
2021-05-05T09:41:12.7178338Z       + name                                         = "Org-int013"
2021-05-05T09:41:12.7297297Z           + host_name                         = "Org-int013.azurefd.net"
```
I'm going to test some different Terraform/provider combos.

**Comment by guywood13** [comment]
I'm now less convinced removing ${var.environment} did anything and it wasn't just a 2nd attempt that was more lucky than the 1st here because I've been testing different permutations of this now with exact same Terraform & provider and subsequent runs with the same versions/code have worked.  I'd be really interested if anyone could recreate this as I'm struggling to nail down the exact root cause.

**Comment by WodansSon** [comment]
@guywood13, thanks for opening this issue. Front door is very particular about the default instance and the mapping to it. It is a general best practice rule for the default frontend endpoint to point to the name of the front door resource like this:

```terraform
azurerm_frontdoor.frontdoor.name
```

However a better option, IMHO, would be to move away from the `vars` file and use a `locals` setting block like this:

```terraform
locals {
  environment    = "int013"
  frontdoor_name = "Org-${local.environment}"
  host_name      = "${local.frontdoor_name}.azurefd.net"
}

resource "azurerm_frontdoor" "frontdoor" {
  name                                         = local.frontdoor_name
  resource_group_name                          = azurerm_resource_group.main.name
  enforce_backend_pools_certificate_name_check = false

  frontend_endpoint {
    name                                    = "FrontendEndpoint"
    host_name                               = local.host_name
    custom_https_provisioning_enabled       = false
    session_affinity_enabled                = var.session_affinity_enabled
    web_application_firewall_policy_link_id = var.frontdoor_waf_enable ? azurerm_frontdoor_firewall_policy.waf_policy[0].id : null
  }
```  

In the original error message it appears that the front door name, at least according to the API, is just `Org` as if your `var` did not get expanded for whatever reason. HTH 🚀

**Comment by guywood13** [comment]
Hi @WodansSon, where am I supposed to reference azurerm_frontdoor.frontdoor.name?  As I just get this error if I try use it for name or host_name:
```
Configuration for azurerm_frontdoor.frontdoor may not refer to itself.
```
Also, not really sure using locals is an option for us.

**Comment by guywood13** [comment]
This now seems completely intermittent, using either hardcoded name values or variables.  Most of the time, it fails 1st attempt and succeeeds on the 2nd attempt.  Sometimes it suceeds 1st attempt.  Other times it takes a 3rd of 4th attempt to succeed.  All with the exact same code, Terraform version and provider version.

**Comment by WodansSon** [comment]
> This now seems completely intermittent, using either hardcoded name values or variables. Most of the time, it fails 1st attempt and succeeds on the 2nd attempt. Sometimes it succeeds 1st attempt. Other times it takes a 3rd of 4th attempt to succeed. All with the exact same code, Terraform version and provider version.

@guywood13, I will attempt to repro this on my dev box. Could you by any chance also post your `vars` files so I can repro this exactly how you are running it in your environment? If not I will build my own based off the configuration file. 🙃

**Comment by WodansSon** [comment]
@guywood13, I have tried to reproduce this issue locally and I can not seem to get it to fail. It consistently provisions the resources as expected every time on the first try.  I am using the latest version of the provider (v2.58.0) so it may have something to do with they changes I made in PR #11456 .

```
terraform apply -auto-approve
azurerm_resource_group.main: Creating...
azurerm_resource_group.main: Creation complete after 2s [id=/subscriptions/XXXXX/resourceGroups/XXXXX-repro-11589-rg]
azurerm_frontdoor.frontdoor: Creating...
azurerm_frontdoor.frontdoor: Still creating... [10s elapsed]
azurerm_frontdoor.frontdoor: Still creating... [20s elapsed]
azurerm_frontdoor.frontdoor: Still creating... [30s elapsed]
azurerm_frontdoor.frontdoor: Still creating... [40s elapsed]
azurerm_frontdoor.frontdoor: Still creating... [50s elapsed]
azurerm_frontdoor.frontdoor: Still creating... [1m0s elapsed]
azurerm_frontdoor.frontdoor: Still creating... [1m10s elapsed]
azurerm_frontdoor.frontdoor: Still creating... [1m20s elapsed]
azurerm_frontdoor.frontdoor: Creation complete after 1m24s [id=/subscriptions/XXXXX/resourceGroups/XXXXX-repro-11589-rg/providers/Microsoft.Network/frontDoors/Org-int013]
```
That said, I did make a few tweaks to the configuration file, please see my version of the `configuration` and `vars` file below.

<details>
  <summary>Terraform main.tf</summary>

```terraform
provider "azurerm" {
  features {}
}

locals {
  fd_name = "Org-${var.environment}"
  default_location = "westeurope"
  tags    = {}
  afd_settings = {
    default_host = "${local.fd_name}.azurefd.net"
  }
}

resource "azurerm_resource_group" "main" {
  name     = "XXXXX-repro-11589-rg"
  location = local.default_location
  tags     = local.tags
}

resource "azurerm_frontdoor" "frontdoor" {
  name                                         = local.fd_name
  resource_group_name                          = azurerm_resource_group.main.name
  enforce_backend_pools_certificate_name_check = false

  routing_rule {
    name               = "DefaultBackendForwardRule"
    accepted_protocols = ["Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["FrontendEndpoint"]

    forwarding_configuration {
      forwarding_protocol = "HttpsOnly"
      backend_pool_name   = "BackendWebapps"
    }
  }

  # Routing rule to redirect all HTTP traffic to HTTPS endpoint
  routing_rule {
    name               = "HTTPSRedirect"
    accepted_protocols = ["Http"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["FrontendEndpoint"]

    redirect_configuration {
      redirect_protocol = "HttpsOnly"
      redirect_type     = "Moved"
    }
  }

  backend_pool_load_balancing {
    name                            = "LoadBalancingSettings"
    additional_latency_milliseconds = 200 # adding some extra latency ensures even load balancing between both regions, no matter where the client sits
  }

  backend_pool_health_probe {
    name                = "HealthProbeSetting"
    protocol            = "Https"
    probe_method        = "HEAD"
    path                = "/api/Healthz"
    interval_in_seconds = 30
  }

  backend_pool {
    name = "BackendWebapps"

    dynamic "backend" {
      for_each = var.frontdoor_backend_locations
      content {
        host_header = "${local.fd_name}-${backend.value}-web.azurewebsites.net"
        address     = "${local.fd_name}-${backend.value}-web.azurewebsites.net"
        http_port   = 80
        https_port  = 443
        enabled     = true
      }
    }

    load_balancing_name = "LoadBalancingSettings"
    health_probe_name   = "HealthProbeSetting"
  }

  backend_pools_send_receive_timeout_seconds = 240

  frontend_endpoint {
    name                                    = "FrontendEndpoint"
    host_name                               = local.afd_settings.default_host
    session_affinity_enabled                = var.session_affinity_enabled
    web_application_firewall_policy_link_id = var.frontdoor_waf_enable ? azurerm_frontdoor_firewall_policy.waf_policy[0].id : null
  }

  tags = local.tags
}

```

</details>

<details>
  <summary>Terraform vars.tf</summary>

```terraform
variable "environment" {
  type = string
  default = "int013"
}

variable "frontdoor_backend_locations" {
  type    = list(string)
  default = ["westeurope"]
}

variable session_affinity_enabled {
  type = bool
  default = false
}

variable frontdoor_waf_enable {
  type = bool
  default = false
}
```

</details>

**Comment by WodansSon** [comment]
> @guywood13, thanks for opening this issue. Front door is very particular about the default instance and the mapping to it. It is a general best practice rule for the default frontend endpoint to point to the name of the front door resource like this:

DOH! 🤦 Sorry about that... that is correct, you **can not** self reference a resource... I don't know what I was thinking... to many late nights and not enough sleep. 🤣

**Comment by guywood13** [comment]
Hi @WodansSon thanks for your efforts on this.  I think I may have found the issue!  I don't actually use "Org-", I was obsfucating.  The FD name and host_name I use contains 3 **preceeding** numbers.  E.g.  **777-int019**.azurefd.net.  Could you test with numbers like this please?  I've asked MS to do the same.  Hopefully you can reproduce the error if you try a few applies.  I tested without preceeding numbers and it applies correctly every time.  I have also tried using different preceeding numbers and can reproduce the error.

FYI, I also tried the latest provider 2.58 and got the error again.  Can you see anything in the code where FD name or host_name starting with a number may cause a problem?  However, I can only assume it is something that has changed on the MS side as this code/Terraform/provider combination worked fine for months.

**Comment by guywood13** [comment]
FYI MS have reported they've been able to replicate this issue using ARM templates after my latest revelation and are escalating to the relevant team to fix it.

**Comment by WodansSon** [comment]
> FYI MS have reported they've been able to replicate this issue using ARM templates after my latest revelation and are escalating to the relevant team to fix it.

@guywood13, yes... once I change `Org` -> `777` I am able to reproduce this issue. That would lend that this is an API issue and not a Terraform issue. There are three options at this point.

* Do nothing and wait for the service team to fix their bug.
* I can add a validation rule in Terraform to block the Frontdoor resource from starting with a digit.
* Update your scripts to start with `Org-` then append the number and var.environment values (e.g. Org-777-int013)

Of the three options, I would favor on waiting for the service team to fix their bug, but who knows how long that would take for them to actually release a fix. But for the sake of unblocking you in a timely manner I would suggest option 3 above. 🤔 

If that answer is satisfactory to you feel free to close this issue... sorry about the API moving underneath you, but that is out of our control. Have a great day. 🚀

**Comment by guywood13** [comment]
Thanks @WodansSon we're gonna wait for MS to fix it too. They've said it'll take at least a week. Thanks for all your help, I will close the issue!
