### ISSUE TITLE
ID was missing the `notificationHubs` element not error while running plan and apply

### ISSUE THREAD

**Issue by chetansir** [terraform-providers/terraform-provider-azurerm#11602]
Below error is appearing while running plan on azurerm provider.

"ID was missing the `notificationHubs` element"

Below is the main file code.

terraform {
    required_providers {
      azurerm={
          source="hashicorp/azurerm"
          version=">2.48.0"
      }
    }
}

provider "azurerm" {
    features {
      
    }
  
}
Trying to create the notification hub in brazilsouth. I can see the hub and namespace created in the RG, however plan is still throwing this error.

Guess it's related to provider using this namespace "Microsoft.NotificationHubs" instead of "Microsoft.notificationhubs"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by daniel-anova** [comment]
Hit this issue as well after applying a change to a notification-hub module.
Only way I found to work around it was to remove the resource from state and import i by changing "NotificationHubs" to "notificationHubs" in the resource ID.

**Comment by andysousa** [comment]
I am not GO expert, but it actually looks correct in the code.. not sure where the "Notificationhubs" is coming from for the ID.

You workaround ti reimport it works... but super less than ideal

**Comment by andysousa** [comment]
The more I am digging into this... 

What happening is on the create the ID thats getting stored in state has the "NotificationsHubs" and not "notificationHubs".  If you import it, its fine.. it just on the initial write to state from the looks of it.

**Comment by andysousa** [comment]
In azure its stored with capital "N"... i was looking at this from the wrong angle.  The fix is to just regenerate the ids in the parser i believe.  I will take a stab at this and raise a PR
![image](https://user-images.githubusercontent.com/42151009/125849420-4bfdcb55-3111-4e9a-ab2e-168f6c3aa1f7.png)

**Comment by andysousa** [comment]
I raised a PR if you want to pull it down and test for yourself
