### ISSUE TITLE
Failure when deploying new azure_kubernetes_cluster resource into centralus

### ISSUE THREAD

**Issue by g0atcheez** [terraform-providers/terraform-provider-azurerm#1160]
Starting yesterday, our automation has broken with the following error.

* azurerm_kubernetes_cluster.test: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.agentPoolProfiles[0].vnetSubnetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."

As a test, I took the sample from the resource documentation and tried deploying it to multiple regions with the same result.

### Terraform Version
Terraform v0.11.7
+ provider.azurerm v1.3.3

### Affected Resource(s)
Please list the resources as a list, for example:
- azure_kubernetes_cluster

### Terraform Configuration Files
```hcl
provider "azurerm" {}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG1"
  location = "centralus"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestaks1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  dns_prefix          = "acctestagent1"

  linux_profile {
    admin_username = "azureuser"

    ssh_key {
      key_data = "${file("modules/azure/terraform.pub")}"
    }
  }

  agent_pool_profile {
    name            = "default"
    count           = 1
    vm_size         = "Standard_A0"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
}
```

### Debug Output
https://gist.github.com/g0atcheez/4cbdcb9b26b067239c5808eac9140dce

### Expected Behavior
Terraform provisions the AKS cluster.

### Actual Behavior
The apply errors out stating that the subnet ID is blank.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @g0atcheez 

Thanks for opening this issue :)

We also detected this API change in our acceptance tests run this morning and have opened https://github.com/terraform-providers/terraform-provider-azurerm/pull/1158 which includes a fix - which will be released as part of v1.4.0 in the near future.

Thanks!

**Comment by tombuildsstuff** [comment]
@g0atcheez I'm going to close this issue since I've just merged the fix for this into `master` - as mentioned above we'll be shipping this fix as a part of v1.4.0 very soon.

Thanks!

**Comment by g0atcheez** [comment]
Thanks for the quick response and fix! I'm closing out the issue.

**Comment by tombuildsstuff** [comment]
hey @andyt530 

Just to let you know that v1.4.0 of the Azure Provider has been released which includes the fix for this :)

Thanks!

**Comment by damian-robo** [comment]
This issue is still present.

**Comment by katbyte** [comment]
Hello @damian-robo,

Could you please open a new issue and supply the terraform exhibiting the issue and the error you are getting? 

Thanks!
