### ISSUE TITLE
Destroying Failures

### ISSUE THREAD

**Issue by FrenchBen** [terraform-providers/terraform-provider-azurerm#1161]
I do quite a bit of terraform deployments on Azure, via jenkins (10 per PR).
There's always 3-4 of those deployments that are marked as failed, because terraform couldn't delete the AzureRM resources, and essentially gave up. 

Even worse, I've seen errors such as:
```
Long running operation terminated with status 'Failed': Code="InternalExecutionError" Message="An internal execution error occurred."
```

Once that happens, there's a disconnect between the overall operation, and the actual state, needing a full refresh.

**Comment by tombuildsstuff** [comment]
hi @FrenchBen 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look at the error message being returned here this, this appears to be an internal error message returned from Azure - as such whilst we could potentially retry on this, this is generally indicative of a larger issue (for instance, such as an issue with the underlying API). Out of interest - are you still seeing this issue, and if so with which resources?

Thanks!

**Comment by FrenchBen** [comment]
thanks @tombuildsstuff for taking a look - I'm no longer involved with the project, and thus couldn't tell. 
Back when the issue was open, I could've provided more info. 
Thanks for taking the time to reply. Since I can't add any valuable details, I'll go ahead and close this.
