### ISSUE TITLE
Verbiage Inconsistency at registry.terraform.io

### ISSUE THREAD

**Issue by connor-miller-kr** [terraform-providers/terraform-provider-azurerm#11658]
This may or may not be the place for this - please correct me if there is another way to report an issue of this sort, I just did not see an option on the site - but there is a documentation verbiage issue here:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_service_data_lake_storage_gen2

Note in the image below that `use_managed_identity` is incompatible with `service_principal_id` and `service_principal_key`, BUT the latter two fields contradict this statement by saying they are "Required if `use_managed_identity` is true."  I believe this should be corrected to "Required if `use_managed_identity` is **false**."

![image](https://user-images.githubusercontent.com/65360035/117821026-23e4a880-b239-11eb-869c-17315d5ae1ec.png)

**Comment by favoretti** [comment]
Thank you for reporting this. Looks like my bad in copy-pasting something. I'll look into this shortly.
