### ISSUE TITLE
ARM_USE_MSI causes user assigned identity rate limiting of token request, preventing Terraform from working

### ISSUE THREAD

**Issue by devlincashman** [terraform-providers/terraform-provider-azurerm#11665]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.15.1 and latest AzureRM

### Affected Resource(s)

All terraform resources, this is a problem with the MSI authentication not caching tokens.

### Expected Behaviour

Utilizing MSI with user assigned identity it seems like Terraform makes a request to 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' on every terraform run.  This has worked fine until recently.

### Actual Behaviour

Now it seems that Azure is more aggressively rate limiting these requests:
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance

We use terragrunt which will call several terraform configurations in a row. This now quickly trips the MSI throttling limits giving us the following error:

failed to get an oauth token from MSI for user assigned identity from MSI endpoint "http://169.254.169.254/metadata/identity/oauth2/token" with client ID "" for endpoint "https://management.azure.com/": MSI not available

Attempting to call a token with curl after attempting to run terraform gives this more useful error:

Error detail: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ba19ee670>: Failed to establish a new connection: [Errno 111] Connection refused'))

Is there a way the MSI authentication method can be updated to cache the token and only request a new one once it has expired? This is also the suggested practice from the Azure docs:
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#token-caching

### Steps to Reproduce

Run terraform or terragrunt on multiple terraform resources quickly.

* #0000

**Comment by manicminer** [comment]
Hi @devlincashman, thanks for requesting this. Whilst we may be able to take steps to improve in-memory caching within a single Terraform process, we would not be able to persist this elsewhere and so it's likely you would still be rate limited if you execute multiple Terraform processes in parallel.

**Comment by tombuildsstuff** [comment]
hi @devlincashman 

Unfortunately this is more of a Terraform Core lifecycle enhancement, where providers are launched twice (once for Plan and once for Apply) as such any caching within the provider (which we already do) wouldn't have any effect here - but ultimately I'd suggest this isn't strictly a Terraform bug (since caching the plugin will still cause an issue) but is ultimately something the Terragrunt project would need to account for when launching parallel deployments.

Since this isn't strictly a provider issue and we're unable to provide support for Terragrunt, I'm going to close this issue for the moment, but I'd suggest filing an issue on the Terragrunt repository where someone from that project should be able to take a look.

Thanks!
