### ISSUE TITLE
azurerm_maintenance_configuration case sensitivity

### ISSUE THREAD

**Issue by jeffwmiles** [terraform-providers/terraform-provider-azurerm#11664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0
```

### Affected Resource(s)

* `azurerm_maintenance_configuration`

### Terraform Configuration Files
```hcl
resource "azurerm_maintenance_configuration" "hostgroup-maint" {
  name                = "hostgroup-maint"
  resource_group_name = azurerm_resource_group.hosts-rg.name
  location            = azurerm_dedicated_host_group.hostgroup.location
  scope               = "All"
}
resource "azurerm_dedicated_host" "host1" {
  name                    = "host1"
  location                = azurerm_dedicated_host_group.hostgroup.location
  dedicated_host_group_id = azurerm_dedicated_host_group.hostgroup.id
  sku_name                = "ESv3-Type3"
  platform_fault_domain   = 1
}
resource "azurerm_maintenance_assignment_dedicated_host" "host1-maint" {
  location                     = azurerm_resource_group.hosts-rg.location
  maintenance_configuration_id = azurerm_maintenance_configuration.hostgroup-maint.id
  dedicated_host_id            = azurerm_dedicated_host.host1.id
}


```

### Debug Output

```
Error: ID was missing the 'maintenanceConfigurations' element
```
![image](https://user-images.githubusercontent.com/40004712/117853916-30233280-b246-11eb-898b-d2c1fb42dc8e.png)

### Expected Behaviour

Expected successful terraform plan/apply

### Actual Behaviour

Error presented (as in debug output).

Upon investigation, it appears that the actual resource ID produced and provided by Azure includes the "maintenanceConfigurations" element, as such:
```
/subscriptions/subid/resourceGroups/hosts-rg/providers/Microsoft.Maintenance/maintenanceConfigurations/hostgroup-maint
```
However, "terraform console" output of the state reference for this resource does NOT have proper capitalization:
![image](https://user-images.githubusercontent.com/40004712/117854402-b17ac500-b246-11eb-9291-00bcaf699131.png)

Performing a `terraform state rm <resource name>` and a new `terraform import` with the correct resource ID including capitalization resolves the issue. 

### Steps to Reproduce

1. `terraform apply`

**Comment by njuCZ** [comment]
@jeffwmiles thanks for pointing out this issue. It has been fixed by #11608 and It will be released in this week on version v2.59.0
