### ISSUE TITLE
Support for [PrivateLinkServiceIdType Microsoft.Web/sites/slots]

### ISSUE THREAD

**Issue by SadokLadhari** [terraform-providers/terraform-provider-azurerm#11677]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AzureRm version : 2.58.0
When I tried creating a Private Endpoint for my Azure App Service Staging Slot (type : Microsoft.Web/sites/slots) I received this error : 

```yml
InvalidPrivateLinkServiceIdType" Message="Private link service Id /subscriptions/SUBSCRIPTION_ID/resourceGroups/RG_NAME/providers/Microsoft.Web/sites/APP_SERVICE_NAME/slots/staging has an invalid resource type. Permitted type(s): Microsoft.DocumentDB/databaseAccounts, Microsoft.Sql/servers, Microsoft.Network/privateLinkServices, Microsoft.Web/sites ...
```

So please support the new type: **Microsoft.Web/sites/slots** !

### New or Affected Resource(s)

* azurerm_private_endpoint

### Potential Terraform Configuration

```hcl
resource "azurerm_private_endpoint" "example" {
  name                = "staging-slot-private-endpoint"
  location            = "westeurope"
  resource_group_name = "RG_NAME"
  subnet_id           = "/subscriptions/SUBSCRIPTION_ID/resourceGroups/RG_NAME/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME"

  private_service_connection {
    name                           = "staging-slot-private-endpoint-connection"
    private_connection_resource_id = "/subscriptions/SUBSCRIPTION_ID/resourceGroups/RG_NAME/providers/Microsoft.Web/sites/APP_SERVICE_NAME/slots/staging"
    is_manual_connection           = false
    subresource_names              = ["sites-staging"]
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#private-link-resource

**Comment by SadokLadhari** [comment]
The private_connection_resource_id need to have the production slot not the staging and for subresource_names need to have sites-{SLOT_NAME} to work preperly.

**Comment by nickkeyzer** [comment]
You just saved me a bunch of time troubleshooting this issue. 

Thank you!
