### ISSUE TITLE
Feature Request: Active Directory Applications

### ISSUE THREAD

**Issue by achandmsft** [terraform-providers/terraform-provider-azurerm#1168]
The Azure Active Directory Graph API provides programmatic access to Azure AD to perform create, CRUD operations on directory data and objects. This issues is to track interest around native support for this in Terraform. 
[REST API](https://docs.microsoft.com/en-us/rest/api/graphrbac/) 
[Azure SDK for Go]( https://github.com/Azure/azure-sdk-for-go/tree/master/services/graphrbac/1.6/graphrbac)

Please express your interest to this issue using thumbs up emoji.

**Comment by achandmsft** [comment]
There is work being done to partially solve this for Service Principal and AAD Application as defined here #16. Scope of this would be the rest of the Graph API calls, so reducing the priority.

**Comment by tombuildsstuff** [comment]
Closing since support for Azure AD Application has shipped in v1.9 of the AzureRM Provider as the `azurerm_azuread_application` resource
