### ISSUE TITLE
macaddress

### ISSUE THREAD

**Issue by saiprasannasastry** [terraform-providers/terraform-provider-azurerm#1169]
resource "azurerm_virtual_machine" "vm" {
    name = "a132vm"
    location = "ukwest"
    resource_group_name = "${azurerm_resource_group.terraform.name}"
    network_interface_ids = ["${azurerm_network_interface.ni.id}"]
    vm_size = "Standard_A6"
...
...}
how do i output mac address from virtual machine

**Comment by tombuildsstuff** [comment]
hey @saiprasannasastry 

Thanks for opening this issue :)

The Mac Address is tied to a Network Interface, as such it's available on the `azurerm_network_interface` resource as [the `mac_address` property](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html). Would you be able to take a look and see if this solves your issue?

Thanks!
