### ISSUE TITLE
Feature Request: Global VNET peering support

### ISSUE THREAD

**Issue by achandmsft** [terraform-providers/terraform-provider-azurerm#1171]
This is to gauge community interest in Global VNET peering support which is now GA (Generally Available). 

The same API seems to handle intra- and inter-regional (global) peerings, and if so contributor who picks this up can use the following from the Azure SDK for Go:
[VirtualNetworkPeeringsClient](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-02-01/network#VirtualNetworkPeeringsClient) and [VirtualNetworkPeeringsClient.CreateOrUpdate](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-02-01/network#VirtualNetworkPeeringsClient.CreateOrUpdate)

Please add a positive reaction to this feature request if it is important to you, to help us prioritize this feature.

**Comment by pixelicous** [comment]
Would be great, supporting this request as well!

**Comment by mb290** [comment]
There's a good chance i'm missing something, but what difference is this to the exist vNet Pairing setup? I've been using Global vNet Peering with the existing module and it's been working fine. Here is some sample code that I just tested now peering West US and South India

```
resource "azurerm_resource_group" "test1" {
  name     = "peeringTest-RG-West"
  location = "West US"
}

resource "azurerm_resource_group" "test2" {
  name     = "peeringTest-RG-India"
  location = "South India"
}

resource "azurerm_virtual_network" "test1" {
  name                = "vNetWestUS"
  resource_group_name = "${azurerm_resource_group.test1.name}"
  address_space       = ["10.0.0.0/24"]
  location            = "${azurerm_resource_group.test1.location}"
}

resource "azurerm_virtual_network" "test2" {
  name                = "vNetIndia"
  resource_group_name = "${azurerm_resource_group.test2.name}"
  address_space       = ["10.0.1.0/24"]
  location            = "${azurerm_resource_group.test2.location}"
}

resource "azurerm_virtual_network_peering" "test1" {
  name                      = "peerWestToIndia"
  resource_group_name       = "${azurerm_resource_group.test1.name}"
  virtual_network_name      = "${azurerm_virtual_network.test1.name}"
  remote_virtual_network_id = "${azurerm_virtual_network.test2.id}"
}

resource "azurerm_virtual_network_peering" "test2" {
  name                      = "peerIndiaToWest"
  resource_group_name       = "${azurerm_resource_group.test2.name}"
  virtual_network_name      = "${azurerm_virtual_network.test2.name}"
  remote_virtual_network_id = "${azurerm_virtual_network.test1.id}"
}
```

**Comment by LaurentLesle** [comment]
@mb290 I followed your approach and it creates a global vnet peering successfully. Looks like it is working fine.
