### ISSUE TITLE
Support for encryption in transit for azurerm_hdinsight_kafka_cluster

### ISSUE THREAD

**Issue by mahpatil** [terraform-providers/terraform-provider-azurerm#11732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

HDInsight Kafka clusters supports encryption in transit that is by default false. The terraform resource currently doesn't support setting this and as a result is not usable in enterprise context. 

https://docs.microsoft.com/en-us/azure/hdinsight/domain-joined/encryption-in-transit
 "encryptionInTransitProperties": {
      "isEncryptionInTransitEnabled": false
    },

### New or Affected Resource(s)

* azurerm_hdinsight_kafka_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_hdinsight_kafka_cluster" "example" {
  name                = "example-hdicluster"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  cluster_version     = "4.0"
  tier                = "Standard"
  
 encryption_in_transit {
   enabled = true
 }
  component_version {
    kafka = "2.1"
  }

  gateway {
    enabled  = true
    username = "acctestusrgw"
    password = "TerrAform123!"
  }

  storage_account {
    storage_container_id = azurerm_storage_container.example.id
    storage_account_key  = azurerm_storage_account.example.primary_access_key
    is_default           = true
  }

  roles {
    head_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }

    worker_node {
      vm_size                  = "Standard_D3_V2"
      username                 = "acctestusrvm"
      password                 = "AccTestvdSC4daf986!"
      number_of_disks_per_node = 3
      target_instance_count    = 3
    }

    zookeeper_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }
  }
}
```

### References

* #0000

**Comment by mahpatil** [comment]
Thanks @favoretti I had started working on this myself offline separately but I see the PR has also been raised against this feature. Thanks a lot for tackling this so quickly. Will this get merged soon (this week perhaps) or should we use a local build, just need this a bit urgently.

**Comment by favoretti** [comment]
@mahpatil looking at reviews - it will ship with next release (normally Thursday-Friday).
