### ISSUE TITLE
Add "public network access' setting to azurerm_healthcare_service

### ISSUE THREAD

**Issue by cginmn** [terraform-providers/terraform-provider-azurerm#11730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add ability to update the network access values of the azurerm_healthcare_service.
"privateEndpointConnections": [],
"publicNetworkAccess": "Enabled"

Similar to how it has been done with other services, looking for ability to disable, as it is set to enabled by default. Additionally, the ability to also add the privateEnpointConnections value to fully configure the service through automation.  

### New or Affected Resource(s)

azurerm_healthcare_service

### References

https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/configure-private-link#disable-public-network-access

* #0000

**Comment by favoretti** [comment]
I'm working on adding control to enable or disable public network access, however I believe that for private endpoints you should use `azurerm_private_endpoint` resource, which in turn will auto-populate the other field.
