### ISSUE TITLE
custom_data is not working for Debian image

### ISSUE THREAD

**Issue by elhostis** [terraform-providers/terraform-provider-azurerm#1173]
Hi all,

It seems custom_data is not working for a debian image.

`> terraform --version
Terraform v0.11.1`

An example that is working.

>resource "azurerm_virtual_machine" "example" {
    name                  = "example-delete-me"
    location              = "${azurerm_resource_group.resource.location}"
    resource_group_name   = "${azurerm_resource_group.resource.name}"
    network_interface_ids = ["${azurerm_network_interface.example.id}"]
    vm_size               = "Standard_DS1_v2"
    delete_os_disk_on_termination = true
    storage_image_reference {
      publisher = "Canonical"
      offer     = "UbuntuServer"
      sku       = "16.04-LTS"
      version   = "latest"
    }
    storage_os_disk {
      name              = "example-os_disk"
      caching           = "ReadWrite"
      create_option     = "FromImage"
      managed_disk_type = "Standard_LRS"
    }
    os_profile {
      computer_name  = "example"
      admin_username = "example"
      admin_password = "Gu8da3Aeshiefee0CHANGED"
      custom_data    = <<-EOF
        #!/bin/bash
        echo "coucou" > /var/tmp/tutu
        EOF
    }
    os_profile_linux_config {
      disable_password_authentication = false
    }
  }

When I'm connection to the vm, I see the hello file.

An other example. The only difference is the image reference.

>resource "azurerm_virtual_machine" "example" {
  name                  = "example-delete-me"
  location              = "${azurerm_resource_group.resource.location}"
  resource_group_name   = "${azurerm_resource_group.resource.name}"
  network_interface_ids = ["${azurerm_network_interface.example.id}"]
  vm_size               = "Standard_DS1_v2"
  delete_os_disk_on_termination = true
  storage_image_reference {
    publisher = "credativ"
    offer     = "Debian"
    sku       = "8"
    version   = "latest"
  }
  storage_os_disk {
    name              = "example-os_disk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  os_profile {
    computer_name  = "example"
    admin_username = "example"
    admin_password = "Gu8da3Aeshiefee0CHANGED"
    custom_data    = <<-EOF
      #!/bin/bash
      echo "coucou" > /var/tmp/tutu
      EOF
  }
  os_profile_linux_config {
    disable_password_authentication = false
  }
}

I don't find the hello file.
I have found the image reference here : [https://wiki.debian.org/Cloud/MicrosoftAzure](https://wiki.debian.org/Cloud/MicrosoftAzure)

Eric

**Comment by tombuildsstuff** [comment]
hey @elhostis 

Thanks for opening this issue :)

As far as I'm aware the `custom_data` file on Linux places this file on disk, so it'll be outputting it to a folder, rather than running the script specified in the `custom_data` field. That said - my understanding is that the `custom_data` field is processed by `cloud-init` via the Azure Agent on the machine - would it be possible to confirm that both of those are available and started in the Debian image?

Given this is an Azure/Image configuration question rather than a bug in Terraform - I'm going to close this issue for the moment.

Thanks!
