### ISSUE TITLE
Terraform destroys and deploys function app

### ISSUE THREAD

**Issue by syedyakoobali** [terraform-providers/terraform-provider-azurerm#11743]
Greetings

I am using Terraform version (Terraform v0.14.10) and deploying multiple resources together. Once the deployment is completed, if I add any other resource or modify the existing resources the function app automatically destroyed and get redeployed. Same is the case with the Application Gateway.

Please share your thoughts and recommendations.

![errorcode](https://user-images.githubusercontent.com/77827916/118443504-978b2780-b709-11eb-89a3-df11a1dc3f0c.PNG)

**Comment by favoretti** [comment]
@syedyakoobali Thank you for reporting this. Would you be so kind to share the actual plan output? That would help us determine which changes cause resource re-creation.

**Comment by syedyakoobali** [comment]
[fapp.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/6492540/fapp.txt)
[functionapp.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/6492556/functionapp.txt)

Please find the attachments.

**Comment by favoretti** [comment]
Ok, for the function app, you need to set `os_type` argument:
```
os_type                        = "linux" -> null # forces replacement
```

**Comment by syedyakoobali** [comment]
Thank you very much. Now function app is working fine without redeployments.
