### ISSUE TITLE
Feature Request: Azure Monitor Log Profiles

### ISSUE THREAD

**Issue by nicholasmhughes** [terraform-providers/terraform-provider-azurerm#1175]
Require the capability to create/update log profiles to export Activity Log data to Event Hubs.

https://github.com/Azure/azure-sdk-for-go/blob/master/services/monitor/mgmt/2018-03-01/insights/logprofiles.go

**Comment by meirf** [comment]
I think there is a real demand to have a new resource which associates diagnosable resources (in the ui, this is anything under Monitor -> Diagnostic Settings) with monitor log profiles. For example to have an application gateway's ApplicationGatewayAccessLog, ApplicationGatewayPerformanceLog, and ApplicationGatewayFirewallLog data go to e.g. a storage account and an event hub.

My assumption is that this issue encompasses such a new resource. @tombuildsstuff, is this assumption correct?

Tthe only question I have is on the wording of the description:
> Require the capability to create/update log profiles to export Activity Log data to Event Hubs.

@nicholasmhughes, am I correct in my understanding that you don't think the new resource should support _**only**_ the Activity Logs -> Event Hubs use case, but rather that the new resource should _**encompass**_ the Activity Logs -> Event Hubs use case?

**Comment by meirf** [comment]
> @nicholasmhughes, am I correct in my understanding...

Sorry this was incoherent. All I'm trying to do is confirm that this issue encompasses a (wide) range of log profiles not just Activity Log data.

**Comment by arichiardi** [comment]
Newbie here, but it seems that a new resources would be required: 

https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/monitoring-and-diagnostics/monitoring-overview-of-diagnostic-logs.md#enable-collection-of-resource-diagnostic-logs-via-azure-cli-20

This is required on Function Apps as well I guess.

**Comment by tombuildsstuff** [comment]
Support for this has been merged as a part of #1792 which is now available as a part of the v1.17 release: https://www.terraform.io/docs/providers/azurerm/r/monitor_log_profile.html
