### ISSUE TITLE
azurerm_virtual_network_gateway  peering_addresses block

### ISSUE THREAD

**Issue by wrighbr** [terraform-providers/terraform-provider-azurerm#11758]
Hi There

We have just bumped the azurerm provider from `2.14.0` to the latest provider `2.59.0` when we do a terraform plan it looks we are going to make remove the `peering_addresses` setting which can be very scary in a prod env.

after dig though the provider code I found the following comment
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/virtual_network_gateway_resource.go#L347 

So since we have configured the ip_configuration block. I commented out the `peering_address` argument and `peering_addresses` block. However when I ran terraform plan it still looks like the `peering_addresses` will still be removed.

Thankfully when you do a terraform apply nothing happen to the virtual network gateway.

```
 ~ resource "azurerm_virtual_network_gateway" "vpn_virtual_gateway" {
        id                         = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/Shared_Services/providers/Microsoft.Network/virtualNetworkGateways/vpn-gw1"
        name                       = "vpn-gw1"
       
        # (9 unchanged attributes hidden)

      ~ bgp_settings {
            # (3 unchanged attributes hidden)

          - peering_addresses {
              - apipa_addresses       = [] -> null
              - default_addresses     = [
                  - "xx.xxx.x.xx",
                ] -> null
              - ip_configuration_name = "default" -> null
              - tunnel_ip_addresses   = [
                  - "xxx.xxx.xx.xxx",
                ] -> null
            }
        }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.59.0

### Affected Resource(s)

* `azurerm_virtual_network_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway" "vpn_virtual_gateway" {
  name                = "${local.resource_prefix}-gw1"
  location            = var.location
  resource_group_name = var.rgname
  type                = "Vpn"
  vpn_type            = "RouteBased"
  active_active       = false
  enable_bgp          = true
  sku                 = "VpnGw2AZ"
  generation          = "Generation2"

  ip_configuration {
    name                          = "default"
    public_ip_address_id          = azurerm_public_ip.vpn_public_ip.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.vpn_subnet.id
  }

  bgp_settings {
    asn             = var.virtual_network_gateway_bgp_asn
    peering_address = [cidrhost(azurerm_subnet.vpn_subnet.address_prefix, -2)]
    peer_weight     = var.virtual_network_gateway_bgp_peer_weight
  }

  
  }

}
```

### Expected Behaviour
That `peering_addresses` block is read correctly from azure that inform me that nothing will change  

### Actual Behaviour
that the `peering_addresses` block is not read correctly from azure and looks like that these setting will be removed / destroyed. 

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by magodo** [comment]
@wrighbr Thank you for submitting this issue!

I've submit #11789 to suppress the unexpected diff during a migration. Meanwhile, I would assume that if you comment the `peering_address` and add an empty `peering_addressess` block as:

```hcl
  bgp_settings {
    #peering_address = cidrhost(azurerm_subnet.test.address_prefix, -2)
    peering_addresses {}
  }
```

It should also work, means no diff during a plan.
