### ISSUE TITLE
Support for Azure Backup for an Azure Managed Disk

### ISSUE THREAD

**Issue by brownoxford** [terraform-providers/terraform-provider-azurerm#11768]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to configure backup of my azure managed disks using Azure's recovery services vault.

### New or Affected Resource(s)

Potential new resources:
* azurerm_backup_policy_managed_disk
* azurerm_backup_protected_managed_disk

### Potential Terraform Configuration

Configuration should be similar to existing resources:

* azurerm_backup_policy_vm
* azurerm_backup_protected_vm

### References

* https://docs.microsoft.com/en-us/azure/backup/backup-managed-disks

**Comment by anttipo** [comment]
I just bumped into this issue this morning myself and realized that the Azure services have changed somewhere along the lines.

- Recovery Services Vault (azurerm_recovery_services_vault) is used to back up entire VM's, Azure Files and such.
- Backup Vault is used to back up blob storages and individual disks.

![image](https://user-images.githubusercontent.com/32951699/118775348-7fddab80-b88f-11eb-8744-1c870e51e0d9.png)

To me, it seems like azurerm provider is missing the Backup Vault resource entirely.

**Comment by schnerring** [comment]
So [`v2.62.0`](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.62.0) introduced the [`data_protection_backup_vault` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_vault#example-usage).

But it seems incomplete, or I just don't know how to properly use it?

**Comment by mark-auderli** [comment]
@schnerring looks to me like the vault can be coded up in terraform using the data_protection_backup_vault resource, but I can't see how to code up any policies.

**Comment by apa976** [comment]
@katbyte could you please confirm if the resource "azurerm_data_protection_backup_instance_disk" will be available in the v2.70.0?

**Comment by tombuildsstuff** [comment]
Fixed via #12361
