### ISSUE TITLE
azurerm_virtual_network_peering does not import attributes to state to prevent replacement

### ISSUE THREAD

**Issue by olbees** [terraform-providers/terraform-provider-azurerm#11766]
Import of vnet peering does not prevent replacement of resource upon apply.

terraform defined in the config as:

resource "azurerm_virtual_network_peering" "PEER_VNET_INTTST_DEV_VNET_INF" {
  provider                 = azurerm.INTTST
  name                      = "PEER-VNET-INTTST-DEV-VNET-INF"
  resource_group_name       = azurerm_resource_group.RG_INF_NETWORK.name
  virtual_network_name      = azurerm_virtual_network.VNET_INTTST_DEV.name
  remote_virtual_network_id = data.azurerm_virtual_network.DATA_VNET_INF.id
  use_remote_gateways       = true
  allow_virtual_network_access = true
}

state after import shows as:

terraform state show azurerm_virtual_network_peering.PEER_VNET_INTTST_DEV_VNET_INF
 azurerm_virtual_network_peering.PEER_VNET_INTTST_DEV_VNET_INF:
resource "azurerm_virtual_network_peering" "PEER_VNET_INTTST_DEV_VNET_INF" {
    id                   = "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/RG-INF-NETWORK/providers/Microsoft.Network/virtualNetworks/VNET-INTTST-DEV"
    resource_group_name  = "RG-INF-NETWORK"
    virtual_network_name = "VNET-INTTST-DEV"

    timeouts {}
}

On terraform plan, shows replacement:

Terraform will perform the following actions:

   azurerm_virtual_network_peering.PEER_VNET_INTTST_DEV_VNET_INF must be replaced
-/+ resource "azurerm_virtual_network_peering" "PEER_VNET_INTTST_DEV_VNET_INF" {
      + allow_forwarded_traffic      = (known after apply)
      + allow_gateway_transit        = (known after apply)
      + allow_virtual_network_access = true
      ~ id                           = "/subscriptions/xxxxxxxxxxxx/resourceGroups/RG-INF-NETWORK/providers/Microsoft.Network/virtualNetworks/VNET-INTTST-DEV" -> (known after apply)
      + name                         = "PEER-VNET-INTTST-DEV-VNET-INF" # forces replacement
      + remote_virtual_network_id    = "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/RG-INF-NETWORK/providers/Microsoft.Network/virtualNetworks/VNET-INF" # forces replacement
      + use_remote_gateways          = true
        # (2 unchanged attributes hidden)

       timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.

**Comment by magodo** [comment]
@olbees Thank you for submitting this issue!

From the log above, are you importing the vnet into the vnet peering by accident, as the `terraform show` of the `azurerm_virtual_network_peering` has following id:

> id = "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/RG-INF-NETWORK/providers/Microsoft.Network/virtualNetworks/VNET-INTTST-DEV"

**Comment by olbees** [comment]
Thanks Magodo, you are right. I have imported it with the correct object reference and it is now working fine.
