### ISSUE TITLE
Support for Azure Cache for Redis for Private Endpoint

### ISSUE THREAD

**Issue by mcabrito** [terraform-providers/terraform-provider-azurerm#11773]
### Community note

* Vote for this issue by adding a reaction [reaction] (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original question to help community and maintainers to prioritize this request
* Don't leave comments "+1" or "me too", they generate extra noise for the followers of the problem and do not help to prioritize the order
* If you are interested in working on this issue or have submitted a pull request, leave a comment

### Description

Add the ability to define a PrivateEnpoint in the Cache for the Redis service to use in the private zone.

### New or affected resource (s)

[Cache for Redis Private link](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-private-link)

* azurerm_redis_cache

### Potential configuration of Terraform

```hcl
resource "azurerm_redis_cache" "example" {
  name                = "example-cache"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  capacity            = 2
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"
  public_network_access_enabled = false
  private_static_ip_address = "10.0.0.5"

  private_endpoint_id = data.azurerm_private_endpoint.redis_pe.id
  

  redis_configuration {
  }
}
```

**Comment by mcabrito** [comment]
@favoretti ... Thanks for the contribution, but that's not exactly the problem ... the problem is that when I'm provisioning with terraform, Cache for Redis is enabled for caching within the Virtual Network. I need this for the Private Terminal.

Look at the image.

![redis-endpoint](https://user-images.githubusercontent.com/26750300/118866322-3f465800-b8b8-11eb-8957-a059f1c9be40.JPG)

**Comment by favoretti** [comment]
Do you specify subnet_id as a parameter to the resource?

**Comment by mcabrito** [comment]
@favoretti 
```
resource "azurerm_redis_cache" "redis" {
  name = "Redis"
  resource_group_name = "RG"
  location = var.location
  capacity                  = var.capacidade
  family                    = var.familia
  sku_name                  = var.sku
  shard_count               = var.sku == "Premium" ? var.shard : 0
  minimum_tls_version = "1.2"
  public_network_access_enabled     = false
  
  subnet_id                 =  var.subnet_id
  
  redis_configuration {
    enable_authentication = var.authentication
    maxmemory_reserved = var.mem_reservada
    maxmemory_delta    = var.mem_delta
    maxmemory_policy   = var.mem_policy
  }
}
```


Ooohhh God!
Thanks... I didn't saw that is optional.
