### ISSUE TITLE
azurerm_container_registry_scope_map uses incorrect validator

### ISSUE THREAD

**Issue by LP0101** [terraform-providers/terraform-provider-azurerm#11783]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

The azurerm_container_registry_scope_map uses an incorrect validator. It accepts only alphanumeric characters, while scopemaps themselves can accept other characters too (such as hyphens). This discrepancy can also be seen in the docs, where a name with hyphens is used as an example: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry_scope_map

**Comment by tombuildsstuff** [comment]
Fixed via #11784 - thanks @LP0101
