### ISSUE TITLE
Using Data DNS Zone to find a zone without knowing it's resource group.

### ISSUE THREAD

**Issue by genevieve** [terraform-providers/terraform-provider-azurerm#1178]
Hey y'all.

We want to use the dns zone data source to find a dns zone with a specified name in order to add records to that zone instead of forcing the creation of a new dns zone in our templates and adding records to that zone. We can do this with the gcp and aws providers now and would like to add that functionality to the azure provider.

If a resource group name is [not specified](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/data_source_dns_zone.go#L49-L51), the dns zone data source will use the [zones client to list](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2016-04-01/dns/zones.go#L264-L267) zones in the resource groups of your subscription and return the first that matches the provided zone name. Would y'all accept a PR for that functionality?

**Comment by tombuildsstuff** [comment]
hey @genevieve 

> Would y'all accept a PR for that functionality?

Yes definitely, that sounds like a great enhancement - given that #1180 has been opened I'm going to close this in favour of that PR :)

Thanks!

**Comment by katbyte** [comment]
Hey @genevieve ,

Just wanted to let you know we have released [v1.6.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#160-may-24-2018) of the provider allowing dns zones to be looked up by name only 🙂
