### ISSUE TITLE
Feature Request: Allow updating of linux ssh public keys

### ISSUE THREAD

**Issue by TraGicCode** [terraform-providers/terraform-provider-azurerm#1179]
### Terraform Version
```
Terraform v0.11.7
+ provider.azurerm v1.4.0
+ provider.template v1.0.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_machine

### Expected Behavior
When updating the ssh_keys key_data i expect terraform to update the VM in place and apply this change in order to remove, update, or add ssh-keys via terraform.

### Actual Behavior
Running a terraform plan after updating the ssh_keys key data says nothing needs to be updated.

**Comment by TraGicCode** [comment]
Hey @VaijanathB ,

Any updates on this?

**Comment by VaijanathB** [comment]
We can achieve this using VMAccessExtension using theazurerm_virtual_machine_extension resource. 

```
resource "azurerm_virtual_machine_extension" "test" {
  name                       = "VMAccessExtension"
  location                   = "${data.azurerm_resource_group.rg.location}"
  resource_group_name        = "${data.azurerm_resource_group.rg.name}"
  virtual_machine_name       = "${azurerm_virtual_machine.testvm.name}"
  publisher                  = "Microsoft.OSTCExtensions"
  type                       = "VMAccessForLinux"
  type_handler_version       = "1.4"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
      {
      }
      SETTINGS

  protected_settings = <<SETTINGS
      {
        "username": "terraform",
        "ssh_key": "new ssh-key"
      }
      SETTINGS
}
```

**Comment by VaijanathB** [comment]
I am going ahead and closing this issue. Please re open if this does not resolve your problem.
