### ISSUE TITLE
Error when creating databricks workspace where managed RG Name equals workspace name

### ISSUE THREAD

**Issue by KSLiquid** [terraform-providers/terraform-provider-azurerm#11803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.15.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.59.0

### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.59.0"
    }
  }
}
# Configure the Microsoft Azure Provider
provider "azurerm" {
  skip_provider_registration = true
  features {
  }
}

resource "azurerm_databricks_workspace" "example" {
  name                        = "databricks-test"
  managed_resource_group_name = "databricks-test"
  resource_group_name         = "some-rg"
  location                    = "westeurope"
  sku                         = "standard"
}

```

### Debug Output

```
│ Error: creating/updating Workspace: (Name "databricks-test" / Resource Group "bsh-dev"): databricks.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidApplicationManagedResourceGroupId" Message="The managed resource group '/subscriptions/f4545903-594c-4add-8e07-298bcab692a5/resourceGroups/databricks-test' cannot be same as the application's resource group."
│
│   with azurerm_databricks_workspace.example,
│   on main.tf line 16, in resource "azurerm_databricks_workspace" "example":
│   16: resource "azurerm_databricks_workspace" "example" {
```

### Expected Behaviour

I expect the workspace to be created with the same name as the managed rg.

### Actual Behaviour

The error (see above) occur.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The same script worked a few weeks ago.
It works when you change the name of the managed rg, e.g. to "databricks-test-a"

**Comment by alexott** [comment]
do you have "normal" resource group with the same name?

**Comment by KSLiquid** [comment]
No

**Comment by WodansSon** [comment]
This is actually a bug in the API, I have contacted the Service team and they believe this has already been fixed.
