### ISSUE TITLE
Support for generating ssh key pair in azurerm_ssh_public_key

### ISSUE THREAD

**Issue by amasover** [terraform-providers/terraform-provider-azurerm#11823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current implementation of `azurerm_ssh_public_key` doesn't support generating a key. Azure API lets you generate a key pair that includes:

* public key resource
* private key (azure doesn't store this, but the API returns it)

I'm not sure exactly how to deal with the private key. Can it be exported as an attribute and stored in state?

### New or Affected Resource(s)

* azurerm_ssh_public_key

### Potential Terraform Configuration

```hcl
resource "azurerm_ssh_public_key" "example" {
  name                = "example"
  resource_group_name = "example"
  location            = "West Europe"
  generate_key        = true
}
```

### References

* #9822
* https://docs.microsoft.com/en-us/rest/api/compute/sshpublickeys/generatekeypair

**Comment by amasover** [comment]
@AliAllomani just wondering if I could ask your thoughts as you originally implemented `azurerm_ssh_public_key`

**Comment by AliAllomani** [comment]
@amasover created PR #11831

Another way would be using `tls_private_key` resource from `tls` provider to create the key pair and provide the public key to `azurerm_ssh_public_key` resource

**Comment by amasover** [comment]
Closing this issue -- please see discussion in #11831
