### ISSUE TITLE
Terraform apply would throw value of parameter imageReference.version is invalid

### ISSUE THREAD

**Issue by PardhaGanta** [terraform-providers/terraform-provider-azurerm#11829]
PS I:\Devops\selfpractice\sqlvm> terraform apply
var.location
  The Azure location where all resources in this example should be created.

  Enter a value: westeurope

var.prefix
  The prefix used for all resources used by this NetApp Account

  Enter a value: pard

azurerm_resource_group.example: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources]
azurerm_virtual_network.example: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/virtualNetworks/pard-VN]
azurerm_network_security_group.example: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/networkSecurityGroups/pard-NSG]
azurerm_public_ip.vm: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/publicIPAddresses/pard-PIP]
azurerm_subnet.example: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/virtualNetworks/pard-VN/subnets/pard-SN]
azurerm_network_security_rule.MSSQLRule: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/networkSecurityGroups/pard-NSG/securityRules/MSSQLRule]
azurerm_network_security_rule.RDPRule: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/networkSecurityGroups/pard-NSG/securityRules/RDPRule]
azurerm_subnet_network_security_group_association.example: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/virtualNetworks/pard-VN/subnets/pard-SN]
azurerm_network_interface.example: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/networkInterfaces/pard-NIC]
azurerm_network_interface_security_group_association.example: Refreshing state... [id=/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/networkInterfaces/pard-NIC|/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/networkSecurityGroups/pard-NSG]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_mssql_virtual_machine.example will be created
  + resource "azurerm_mssql_virtual_machine" "example" {
      + id                    = (known after apply)
      + sql_connectivity_port = 1433
      + sql_connectivity_type = "PRIVATE"
      + sql_license_type      = "PAYG"
      + virtual_machine_id    = (known after apply)
    }

  # azurerm_virtual_machine.example will be created
  + resource "azurerm_virtual_machine" "example" {
      + availability_set_id              = (known after apply)
      + delete_data_disks_on_termination = false
      + delete_os_disk_on_termination    = false
      + id                               = (known after apply)
      + license_type                     = (known after apply)
      + location                         = "westeurope"
      + name                             = "pard-VM"
      + network_interface_ids            = [
          + "/subscriptions/3fc3bd06-663c-4fa2-9971-d4c28bdfba19/resourceGroups/pard-resources/providers/Microsoft.Network/networkInterfaces/pard-NIC",
        ]
      + resource_group_name              = "pard-resources"
      + vm_size                          = "Standard_DS14_v2"

      + identity {
          + identity_ids = (known after apply)
          + principal_id = (known after apply)
          + type         = (known after apply)
        }

      + os_profile {
          + admin_password = (sensitive value)
          + admin_username = "exampleadmin"
          + computer_name  = "winhost01"
          + custom_data    = (known after apply)
        }

      + os_profile_windows_config {
          + enable_automatic_upgrades = true
          + provision_vm_agent        = true
          + timezone                  = "Pacific Standard Time"
        }

      + storage_data_disk {
          + caching                   = (known after apply)
          + create_option             = (known after apply)
          + disk_size_gb              = (known after apply)
          + lun                       = (known after apply)
          + managed_disk_id           = (known after apply)
          + managed_disk_type         = (known after apply)
          + name                      = (known after apply)
          + vhd_uri                   = (known after apply)
          + write_accelerator_enabled = (known after apply)
        }

      + storage_image_reference {
          + offer     = "SQL2017-WS2016"
          + publisher = "MicrosoftSQLServer"
          + sku       = "SQLDEV"
          + version   = "laexample"
        }

      + storage_os_disk {
          + caching                   = "ReadOnly"
          + create_option             = "FromImage"
          + disk_size_gb              = (known after apply)
          + managed_disk_id           = (known after apply)
          + managed_disk_type         = "Premium_LRS"
          + name                      = "pard-OSDisk"
          + os_type                   = (known after apply)
          + write_accelerator_enabled = false
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_virtual_machine.example: Creating...
╷
│ Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="The value of parameter imageReference.version is invalid." Target="imageReference.version"
│
│   with azurerm_virtual_machine.example,
│   on main.tf line 88, in resource "azurerm_virtual_machine" "example":
│   88: resource "azurerm_virtual_machine" "example" {

**Comment by magodo** [comment]
@PardhaGanta This is an azure API error, persumably the configs blow (especially the `version`) is invalid/doesn't exist:

```
      + storage_image_reference {
          + offer     = "SQL2017-WS2016"
          + publisher = "MicrosoftSQLServer"
          + sku       = "SQLDEV"
          + version   = "laexample"
        }
```

**Comment by PardhaGanta** [comment]
version   = "latest" fixed my issue. thanks

**Comment by bingerk** [comment]
Well my mystery was solved.  The SQL VM Version does not correlate with the SQL build numbers.  Running the following command shows all the images available:

Get-AzVMImage -Location eastus -PublisherName "MicrosoftSQLServer" -Offer "SQL2016SP2-WS2016" -Skus "enterprise"  

From this, I was able to confirm that the image I was trying to find was not available any longer.
