### ISSUE TITLE
Support for Service Tags on azurerm_route_table routes

### ISSUE THREAD

**Issue by matt-garner-nw** [terraform-providers/terraform-provider-azurerm#11836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for Service Tags in Route Table routes address prefix argument, similar functionality to NSG Rules.

### New or Affected Resource(s)

* azurerm_route_table

### Potential Terraform Configuration

```hcl
resource "azurerm_route_table" "example" {
  name                          = "acceptanceTestSecurityGroup1"
  location                      = azurerm_resource_group.example.location
  resource_group_name           = azurerm_resource_group.example.name
  disable_bgp_route_propagation = false

  route {
    name           = "route1"
    address_prefix = "BatchNodeManagement"
    next_hop_type  = "vnetlocal"
  }

  tags = {
    environment = "Production"
  }
}
```

### References

https://azure.microsoft.com/en-gb/updates/public-preview-service-tags-for-user-defined-routing/

NSG Rules Tags:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_group#source_address_prefix

* #0000

**Comment by favoretti** [comment]
Looking at the code `address_prefix` in route table resource is just a string, with a `NotEmpty` validation. Did you try specifying service tags? If so, which error are you getting? (Might be that we'll need newer API version in provider, but last attempts to upgrade `network` package resulted in some massive breakage unfortunately).

**Comment by matt-garner-nw** [comment]
Ah, looks like it works @favoretti . Can we get the docs updated?

**Comment by favoretti** [comment]
Good news. I'll try to update the docs later today, unless someone beats me to it.
