### ISSUE TITLE
When using "only_critical_addons_enabled = true" and "ingress_application_gateway enabled = true". The AGIC for AKS "ingress-appgw-deployment" pod does not start

### ISSUE THREAD

**Issue by philthynz** [terraform-providers/terraform-provider-azurerm#11845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.15.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.59.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
```

### Affected Resource(s)

 - azurerm_kubernetes_cluster

### Terraform Configuration Files

```
resource "azurerm_kubernetes_cluster" "aks" {
  name                            = local.resource_name
  location                        = data.azurerm_resource_group.inf_resource_group.location
  resource_group_name             = azurerm_resource_group.k8s_resource_grp.name
  dns_prefix                      = local.resource_name
  node_resource_group             = local.node_resource_name
  kubernetes_version              = var.KUBERNETES.KubernetesVersion
  api_server_authorized_ip_ranges = var.KUBERNETES_ALLOWED_IP_RANGES
  tags                            = var.TAGS

  default_node_pool {
    name                         = "default"
    type                         = "VirtualMachineScaleSets"
    node_count                   = var.KUBERNETES.InitialNodeCount
    availability_zones           = var.KUBERNETES.AvailabilityZones
    vm_size                      = var.KUBERNETES.NodeVmSize
    enable_auto_scaling          = var.KUBERNETES.AutoScaleBool
    enable_host_encryption       = var.KUBERNETES.EnableHostEncryption
    os_disk_size_gb              = var.KUBERNETES.OSDiskSize
    os_disk_type                 = var.KUBERNETES.OSDiskType
    max_pods                     = var.KUBERNETES.MaxPods
    node_labels                  = var.KUBERNETES.Labels
    min_count                    = var.KUBERNETES.AutoScaleMinCount
    max_count                    = var.KUBERNETES.AutoScaleMaxCount
    vnet_subnet_id               = data.azurerm_subnet.aks_pods_subnet.id
    only_critical_addons_enabled = true
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed                = true
      admin_group_object_ids = var.KUBERNETES.AdminGroupObjectIds
    }
  }

  addon_profile {

    kube_dashboard {
      enabled = false
    }

    azure_policy {
      enabled = true
    }

    ingress_application_gateway {
      enabled    = true
      gateway_id = azurerm_application_gateway.app_gateway.id
    }
  }

  network_profile {
    load_balancer_sku = "standard"
    outbound_type     = "loadBalancer"
    network_plugin    = "azure"
    network_policy    = "azure"
  }
}
```

### Debug Output

None in Terraform

### Panic Output

None in Terraform

### Expected Behaviour

AKS Pods are created and running

### Actual Behaviour

The AGIC pod is not running and has errors:

![image](https://user-images.githubusercontent.com/17504095/119408062-34b51400-bd39-11eb-9084-f59e32e4e21b.png)

I am not sure if this is an issue with the way Terraform apply's the AGIC pod and the taint, or if it's an AKS issue. If I use the az cli, it works fine. Potentially Terraform would need to apply the pods before the taint, if possible.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

No

### References

No

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. This is a bit of a tough one. For `only_critical_addons_enabled` functionality, people wanted a hard taint to make sure default nodepool runs only control plane/"system" pods. Apparently AKS team implemented AGIC as a non-critical addon. You'll either need another nodepool, so that AKS is able to schedule AGIC or we need to work with AKS team to make sure AGIC is considered a part of control plane (which I personally believe it's not).

**Comment by philthynz** [comment]
@favoretti thanks for the response.

Correct me if I'm wrong, but having a separate node pool to run AGIC still wouldn't allow me to use "ingress_application_gateway, enabled = true"?

I would need to deploy AGIC separately into another node pool and namespace via Helm and do some role assignments for the permissions. Which I have done before the "enable agic" feature was available.

Unless there is a way to deploy AGIC onto the other node pool?

**Comment by favoretti** [comment]
@philthynz As far as I understand it - addon profiles are not nodepool specific. So it will try to schedule a workload and if there are nodes in any nodepool that can accommodate that workload - it should get scheduled. I didn't run an actual test with AGIC though, so YMMV :)

**Comment by philthynz** [comment]
@favoretti Yes your right, adding another node pool did the trick. The agic pod deploys to whatever node pool can accommodate it.

I'll try and find some time to make a PR to update the terraform documentation. A note next to "ingress_application_gateway" would be handy to say there is a conflict when using "only_critical_addons_enabled" at the same time, and another node pool is required.

**Comment by philthynz** [comment]
Hopefully this should be ok https://github.com/philthynz/terraform-provider-azurerm/pull/1

**Comment by favoretti** [comment]
@philthynz Thanks for the contribution! Could you also open a PR against this repo, rather than your own, then we can also review and merge it :)

**Comment by philthynz** [comment]
My apologies, here you go https://github.com/terraform-providers/terraform-provider-azurerm/pull/11954
