### ISSUE TITLE
azure_key_vault Resource documentation lists incorrect permissions

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1189]
The azure_key_vault documentation for "certificate_permissions" lists `recovery` and `purge` as permissions but when trying to apply config with these permissions, Terraform throws an error saying they are invalid.

**Comment by Phydeauxman** [comment]
I am doing this in Cloud Shell and it is version 1.3.  I am not sure why I am not able to get existing deployments to upgrade to 1.4 but when I initialize a new deployment it uses 1.4

**Comment by tombuildsstuff** [comment]
@Phydeauxman what approach are you taking to upgrade? We’d recommend specifying the version in the provider block, for instance:

```
terraform {
  version = "=1.4.0"
}
```

at which point running `terraform init` will download the new version

Thanks!

**Comment by Phydeauxman** [comment]
That seemed to do the trick.  I thought that without the version parameter that when you did an init it would upgrade to latest version of a provider.

**Comment by tombuildsstuff** [comment]
@Phydeauxman 

> That seemed to do the trick.

👍 as such I'll close this issue for the moment

> I thought that without the version parameter that when you did an init it would upgrade to latest version of a provider.

Terraform caches the Provider binaries in the folder, so it can vary based on the machine. You can do that with `terraform init -update`, but we strongly recommend pinning the version of the provider being used

Thanks!
