### ISSUE TITLE
Feature Request: Add Missing Options for azurerm_cosmosdb_account Firewall

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1192]
The azurerm_cosmosdb_account resource currently has a parameter called `ip_range_filter` that allows you to restrict CosmosDB access to specific IPs or CIDR blocks but there are also 2 check box options in the UI that do not appear to be supported in the current resource:

`Allow access to Azure Services`

and

`Allow access to Azure Portal`

Is this functionality not exposed in the current version of the SDK?

**Comment by katbyte** [comment]
Hello @Phydeauxman,

There is no mention of these options in the current SDK, however it does appear that they simply insert IPs into the `ip_range_filter` field:

`104.42.195.92, 40.76.54.131, 52.176.6.30, 52.169.50.45, 52.187.184.26` for `Allow access to Azure Portal`.
`104.42.195.92, 40.76.54.131, 52.176.6.30, 52.169.50.45, 52.187.184.26, 0.0.0.0` for both options.

**Comment by Phydeauxman** [comment]
@katbyte that is odd that they would not include those as simple default to "false" and "true" to enable.  I will give a try to the IPs.  What I wonder is if I add the IPs, does it check those boxes when viewed in the portal?

**Comment by tombuildsstuff** [comment]
@katbyte @Phydeauxman IIRC this is pretty undocumented but "Azure Services" seems to be used pretty consistently across multiple Azure Services as an alias for the IP Address `0.0.0.0` - so I believe this is the only IP address you'll need to use to enable this, but it'd be worth testing this to be sure :)

**Comment by katbyte** [comment]
@Phydeauxman, I just checked and using those IPs with terraform will check the boxes in the portal 🙂

However, I did discover that there cannot be spaces in the set of IPs provided and the error message returned by the API is less then helpful. So I will add in some additional validation to clarify.

**Comment by Phydeauxman** [comment]
@katbyte thanks for testing it out.
