### ISSUE TITLE
azurerm_kusto_eventhub_data_connection doesn't support '$Default' consumer group name

### ISSUE THREAD

**Issue by Kavyeshs41** [terraform-providers/terraform-provider-azurerm#11958]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

 - Terraform v0.14.4
 - registry.terraform.io/hashicorp/azurerm v2.54.0

### Affected Resource(s)

* `azurerm_kusto_eventhub_data_connection`

### Terraform Configuration Files

```hcl
resource "azurerm_kusto_eventhub_data_connection" "eventhub_connection" {
  name     = "my-name"

  resource_group_name = var.resource_group_name
  location            = var.location
  cluster_name        = var.cluster_name
  database_name       = var.database_name

  eventhub_id    = var.eventhub_id   
  consumer_group = "$Default"
}
```

### Expected Behaviour

Should have accepted the name $Default as this is the name that the azure portal assigns by default if one is not specified

### Actual Behaviour

Error: invalid value for consumer_group (The consumer group name can contain only letters, numbers, periods (.), hyphens (-),and underscores (_), up to 50 characters, and it must begin and end with a letter or number.)

### Steps to Reproduce

1. `terraform apply`

### References

* #7720 - This is for data source

### Possible Solution

* #8388

**Comment by oleanders** [comment]
`ValidateEventHubConsumerName()` is used to validate `consumer_group` in `azurerm_kusto_eventhub_data_connection`
https://github.com/terraform-providers/terraform-provider-azurerm/blob/0a29f734f5406e4772c65b871df5ef871454ab81/azurerm/internal/services/kusto/kusto_eventhub_data_connection_resource.go#L95-L100

#8388 is solved by adding validation of `$Default` outside `ValidateEventHubConsumerName()`. 

A simple fix might be to move `validation.StringInSlice([]string{"$Default"}, false)`...
https://github.com/terraform-providers/terraform-provider-azurerm/blob/c976891a87cb3bb7177ef9163babc889719953a6/azurerm/internal/services/eventhub/eventhub_consumer_group_data_source.go#L28-L31

....into `ValidateEventHubConsumerName()`:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/be97ca6ab3913220a16eadb76fb7cbdccf711dff/azurerm/internal/services/eventhub/validate/eventhub_names.go#L25-L30
