### ISSUE TITLE
Support for encryption in transit for azurerm_hdinsight_spark_cluster, azurerm_hdinsight_interactive_query_cluster

### ISSUE THREAD

**Issue by sullub** [terraform-providers/terraform-provider-azurerm#11968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

HDInsight spark/hadoop/hdinsight_interactive_query clusters supports encryption in transit that is by default false. The terraform resource currently doesn't support setting this and as a result is not usable in enterprise context.

https://docs.microsoft.com/en-us/azure/hdinsight/domain-joined/encryption-in-transit
encryption_in_transit_enabled  = true

Support for encryption in transit for azurerm_hdinsight_kafka_cluster has already been requested in #11732 and has been released in version 2.60.0 

### New or Affected Resource(s)
 

* azurerm_hdinsight_spark_cluster
* azurerm_hdinsight_interactive_query_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,


New or Affected Resource(s)

Potential Terraform Configuration
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_hdinsight_spark_cluster" "example" {
  name                = "example-hdicluster"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  cluster_version     = "3.6"
  tier                = "Standard"

 encryption_in_transit_enabled  = true

  component_version {
    spark = "2.3"
  }

  gateway {
    enabled  = true
    username = "acctestusrgw"
    password = "TerrAform123!"
  }

  storage_account {
    storage_container_id = azurerm_storage_container.example.id
    storage_account_key  = azurerm_storage_account.example.primary_access_key
    is_default           = true
  }

  roles {
    head_node {
      vm_size  = "Standard_A3"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }

    worker_node {
      vm_size               = "Standard_A3"
      username              = "acctestusrvm"
      password              = "AccTestvdSC4daf986!"
      target_instance_count = 3
    }

    zookeeper_node {
      vm_size  = "Medium"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }
  }
}

# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by mahpatil** [comment]
@favoretti, @katbyte by any chance would this one get any attention? is this something you guys are going to work toward?

**Comment by sullub** [comment]
@katbyte. @favoretti  any idea when will this be picked up?

**Comment by favoretti** [comment]
Working on it as we speak.
