### ISSUE TITLE
Support Bring your own kubelet MI

### ISSUE THREAD

**Issue by pmuz** [terraform-providers/terraform-provider-azurerm#11980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Request to add support to assign kubelet MI at cluster creation as per microsoft [docs](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#bring-your-own-control-plane-mi) so that it is possible to set UAMI as a kubelet identity.  

At the moment azurerm supports only export of the [kubelet_identity attributes](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kubelet_identity) but it doesn't support setting it as an AKS cluster attribute. 

With azure cli this can be done as documented [here](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#create-a-cluster-using-kubelet-identity).

### New or Affected Resource(s)
azurerm_kubernetes_cluster

### Potential Terraform Configuration
```
resource "azurerm_kubernetes_cluster" "example" {
  name                    = "aksexamplewithprivatednszone1"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  dns_prefix              = "aksexamplednsprefix1"
  private_cluster_enabled = true
  private_dns_zone_id     = azurerm_private_dns_zone.example.id

  ... rest of configuration omitted for brevity

  kubeletidentity": {
    "clientId": "<client-id>",
    "objectId": "<object-id>",
    "resourceId": "/subscriptions/<subscriptionid>/resourcegroups/resourcegroups/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myKubeletIdentity"
  }
```

### References
* microsoft docs on bring your own identity for kubelet MI:
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#bring-your-own-control-plane-mi

* azurerm_kubelet_identity
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kubelet_identity

**Comment by aristosvo** [comment]
I want to try and solve this one!
