### ISSUE TITLE
Azure Fileshare syntax error in azurerm 2.61 provider

### ISSUE THREAD

**Issue by arock76** [terraform-providers/terraform-provider-azurerm#11996]
Starting in 2.61 I get an error on existing Azure file share role assignments. The module tries to remove the role assignment and re-assign to an incorrect resource pathway. There is an extra "file" in "/fileServices/default/filefileshares". It should be "/fileServices/default/filefileshares". See attached: 
![image](https://user-images.githubusercontent.com/55249396/119902454-db054300-bf0c-11eb-9986-f315eba4c2b1.png)

It works fine in earlier versions.

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. Could you please share a piece of HCL where that role assignment is defined? ID was broken in releases prior to `2.61.0` and got fixed with this last release. I assume if it was working before your HCL appends that extra "file" somewhere.

**Comment by arock76** [comment]
Here is the code snippet I am using in the module. I wrote this a while back and it looks like I coded to replace the "shares" with "fileshares". Now that you have it fixed my replace is breaking the path. I will update my code and test tomorrow to verify.  
#assign RBAC role to primary fileshares scoperesource "azurerm_role_assignment" "assignroletoprimarysharesa" {    for_each = { for hostpoolshare in var.hostpoolshares: hostpoolshare.name => hostpoolshare }    scope                    = replace(azurerm_storage_share.newprimarystoragesharesa[each.value.name].resource_manager_id, "/shares/", "fileshares")    role_definition_name     = "Storage File Data SMB Share Contributor"    principal_id             = each.value.azureobjid}


    On Thursday, May 27, 2021, 05:35:52 PM CDT, Vladimir Lazarenko ***@***.***> wrote:  
 
 


Hi there and thank you for reporting this. Could you please share a piece of HCL where that role assignment is defined? ID was broken in releases prior to 2.61.0 and got fixed with this last release. I assume if it was working before your HCL appends that extra "file" somewhere.

**Comment by arock76** [comment]
This is working correctly. I just had to remove my workaround. I will close the bug.

Sent from Yahoo Mail on Android 
 
  On Thu, May 27, 2021 at 9:41 PM, Aaron ***@***.***> wrote:    Here is the code snippet I am using in the module. I wrote this a while back and it looks like I coded to replace the "shares" with "fileshares". Now that you have it fixed my replace is breaking the path. I will update my code and test tomorrow to verify.  
#assign RBAC role to primary fileshares scoperesource "azurerm_role_assignment" "assignroletoprimarysharesa" {    for_each = { for hostpoolshare in var.hostpoolshares: hostpoolshare.name => hostpoolshare }    scope                    = replace(azurerm_storage_share.newprimarystoragesharesa[each.value.name].resource_manager_id, "/shares/", "fileshares")    role_definition_name     = "Storage File Data SMB Share Contributor"    principal_id             = each.value.azureobjid}


    On Thursday, May 27, 2021, 05:35:52 PM CDT, Vladimir Lazarenko ***@***.***> wrote:  
 
 


Hi there and thank you for reporting this. Could you please share a piece of HCL where that role assignment is defined? ID was broken in releases prior to 2.61.0 and got fixed with this last release. I assume if it was working before your HCL appends that extra "file" somewhere.
