### ISSUE TITLE
Error by deployment an application gateway with ssl certificate from keyvault

### ISSUE THREAD

**Issue by chris87-concat** [terraform-providers/terraform-provider-azurerm#11991]
I want to create an application gateway "waf" for protect the aks cluster.

The problem is that I get an error message when I deploy the application gateway with ssl_certficates block. 

The error called "Error: Error expanding `ssl_certificate`: either `key_vault_secret_id` or `data` must be specified for the `ssl_certificate` block" 

Here the part of the terraform script:

```
  ssl_certificate {
    name                = "https-tpx"
    key_vault_secret_id = data.azurerm_key_vault_certificate.tpx_website.secret_id
  }
```

I use azurerm provider version 2.60 and terraform version 0.14.9

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I actually just tested on one of my own appgws with the following config:
```
  ssl_certificate {
    name                = data.azurerm_key_vault_certificate.wildcard_api.name
    key_vault_secret_id = data.azurerm_key_vault_certificate.wildcard_api.secret_id
  }
```
and it works just fine.

Could you maybe share a sanitized version of complete resource ACL?

**Comment by chris87-concat** [comment]
Hi Vladimir.

Thanks for the fast response the error was a typing issue by data.azurerm_key_vault_certificate and the certificate could not be got with wrong name.

But this don´t catch an error so the other function of application gateway crashes. After I have corrected the name of the certificate everything works fine.

Kind regards
Christian Holl

Senior Lead Cloud Architect
Microsoft Azure



[Concat Homepage]<https://www.concat.de/>

        [concat on facebook] <https://www.facebook.com/ConcatAG>    [concat on xing] <https://www.xing.com/companies/concatag>    [concat on linkedin] <https://www.linkedin.com/company/concat-ag/>

Concat AG
Auf dem Seidenberg 5
53721 Siegburg

www.concat.de
Tel.:     +49 2241 97377-35
Fax:     +49 2241 9737711
Mobil:  +49 162 2985588
***@***.***

Hauptsitz Bensheim a. d. Bergstraße | Vorstand Olaf von Heyer
Aufsichtsratsvorsitzender Tim Patronik  | Amtsgericht Darmstadt (HRB 25326)



***@***.***<https://www.concat.de/concat-loesungen/concat-applications/concat-2net/teamwork2net/>

HINWEIS: Diese E-Mail ist nur für den Adressaten bestimmt und kann Geschäftsgeheimnisse oder sonstige vertrauliche Informationen enthalten. Sollten Sie diese Nachricht irrtümlich erhalten haben, benachrichtigen Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Es ist streng untersagt, diese Nachricht zu kopieren oder Dritten zugänglich zu machen. Vielen Dank.

NOTICE: This e-mail is intended for the addressee only and may contain business secrets or other confidential information. If you have received this message in error please notify the sender immediately and destroy this e-mail. It is strictly forbidden to copy this e-mail or disclose it to third parties. Thank you.


Please consider the environment before printing this email
Von: Vladimir Lazarenko ***@***.***>
Datum: Freitag, 28. Mai 2021 um 00:40
An: terraform-providers/terraform-provider-azurerm ***@***.***>
Cc: Christian Holl ***@***.***>, Author ***@***.***>
Betreff: Re: [terraform-providers/terraform-provider-azurerm] Error by deployment an application gateway with ssl certificate from keyvault (#11991)

Hi there and thank you for reporting this. I actually just tested on one of my own appgws with the following config:

  ssl_certificate {

    name                = data.azurerm_key_vault_certificate.wildcard_api.name

    key_vault_secret_id = data.azurerm_key_vault_certificate.wildcard_api.secret_id

  }

and it works just fine.

Could you maybe share a sanitized version of complete resource ACL?

**Comment by favoretti** [comment]
Thank you for your response. From what I'm reading the problem has been solved, so I'll go ahead and close this issue. Feel free to reopen it again if the problem persists.
