### ISSUE TITLE
administrator_login_password silently changed

### ISSUE THREAD

**Issue by noqcks** [terraform-providers/terraform-provider-azurerm#12007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
* provider.azurerm v2.25.0

### Affected Resource(s)

* `azurerm_postgresql_server `

### Terraform Configuration Files

```hcl
resource azurerm_postgresql_server server {
  ...
  administrator_login_password = var.password
  ... 
  lifecycle {
    ignore_changes = [
      administrator_login_password
    ]
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

#### Scenario 1
1. Create `azurerm_postgresql_server` in terraform with a default `administrator_login_password`
2. Change the admin login password in azure portal
3. `tf apply`

**_Expected_**: tf plan shows no change for `administrator_login_password`, and no change is applied. 
**_Actual_**: tf plan shows no change for `administrator_login_password`. On apply the admin password in the portal _IS NOT_ changed back to the default, as expected. 

#### Scenario 2 
1. Create `azurerm_postgresql_server` in terraform with default `administrator_login_password`
2. Change the admin login password in azure portal
3. Make a change on any other attribute of the terraform resource.
4. `tf apply`

**_Expected_**: tf plan shows no change for `administrator_login_password`, and no change is applied.
**_Actual_**: tf plan shows changes for the other resources, but not `administrator_login_password`. On apply the admin password in the portal _IS_ changed back to the default. This is unexpected.

### References

- #1823 
- https://github.com/terraform-providers/terraform-provider-azurerm/pull/2263

cc: @tombuildsstuff

**Comment by carolguo-dd** [comment]
Maybe we should make skip changing `administrator_login_password` if `lifecycle.ignore_changes` is enabled for `administrator_login_password` ?

**Comment by aristosvo** [comment]
@noqcks  This is Postgres, the PR you're referring to is for Azure SQL. I think this one is easy to solve, let me check!
