### ISSUE TITLE
Support for CustomKubeletIdentity in AKS

### ISSUE THREAD

**Issue by jkroepke** [terraform-providers/terraform-provider-azurerm#12017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In addition to a control plane managed identity, it's possible to BYO managed identity for the kubelet.

Why?

In a Hub and Spoke model, there is a central Azure Container Registry. The platform team wants to pre provision managed identities with the permissions for the kubelet service.

Product teams inside spokes are able to use both managed identities to create a AKS cluster independently with any interaction from plattform team. 

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                    = "aksexamplewithprivatednszone1"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  ... rest of configuration omitted for brevity

  kubelet_identity {
    type                      = "UserAssigned"
    user_assigned_identity_id = data.azurerm_user_assigned_identity.kubelet_aks.id
  }
}
```

### References

* https://github.com/Azure/AKS/issues/1428#issuecomment-670657468

Upstream documentation: 
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#bring-your-own-kubelet-mi-preview

**Comment by aristosvo** [comment]
Hi @jkroepke!

I believe this is a duplicate of #11980

**Comment by jkroepke** [comment]
Yes! I search for "CustomKubeletIdentity" but I could not find the issue.
