### ISSUE TITLE
azurerm_data_factory returns empty identity attribute

### ISSUE THREAD

**Issue by alge0** [terraform-providers/terraform-provider-azurerm#12018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
% terraform -version
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
```

### Affected Resource(s)

* `azurerm_data_factory`

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory" "df" {
  name                = "df-example"
  location            = local.location
  resource_group_name = local.rgr_name
}

output "df" {
  value = azurerm_data_factory.df.identity
}
```

### Expected Behaviour

The object ID (i.e., principal ID) of the managed identity of the Date Factory is returned.

```hcl
df = tolist([
  {
    "principal_id" = "xxx-xxx-xxx-xxx-xxx"
    "tenant_id" = "xxx-xxx-xxx-xxx-xxx"
  },
])
```

### Actual Behaviour

An empty list is retured. So I don't have access to the object ID of the managed identity.

```hcl
df = tolist([])
```

### Steps to Reproduce

1. `terraform apply`

**Comment by njuCZ** [comment]
@alge0 if you want to enable the system assigned identity for data factory, you should use following code snippet
```
resource "azurerm_data_factory" "df" {
  name                = "df-example"
  location            = local.location
  resource_group_name = local.rgr_name

  identity {
    type = "SystemAssigned"
  }
}
```

**Comment by alge0** [comment]
Thank you for your reply. I also tried to use the identity argument. Here is my HCL Code:

```
resource "azurerm_data_factory" "df" {
  name                = "df-${local.resource_name_postfix}"
  location            = local.location
  resource_group_name = local.rgr_name

  identity {
    type = "SystemAssigned"
  }
}

output "df" {
  value = azurerm_data_factory.df.identity
}
```

And that is the outcome in this case:
```
df = tolist([
  {
    "identity_ids" = tolist(null) /* of string */
    "principal_id" = tostring(null)
    "tenant_id" = tostring(null)
    "type" = "SystemAssigned"
  },
])
```

When I check in Active Directory, the managed identity for Data Factory is created with or without the identity argument. I just don't have access to the managed identity object ID in Terraform and cannot use it for any role assignments.

**Comment by njuCZ** [comment]
@alge0 could you modify to use following config and have a try?
```
resource "azurerm_data_factory" "df" {
  name                = "df-${local.resource_name_postfix}"
  location            = local.location
  resource_group_name = local.rgr_name

  identity {
    type = "SystemAssigned"
  }
}

output "df" {
  value = azurerm_data_factory.df.identity.0.principal_id
}
```

everything is fine in my local

**Comment by alge0** [comment]
Strange, yesterday and this morning, output always returned an empty identity attribute. In last tests, however, the resource behaves as expected. It returns the object ID of the managed identity. 
For now, the problem seems to be solved. But it leaves me with mixed feeling since I don't know what fixed the problem.

**Comment by katbyte** [comment]
@alge0 - my money is on a transitory API issue not returning that block - we see them regularly in our tests. as such i'm going to close this. if you see it again please do open a new issue!
