### ISSUE TITLE
Support for powerbi embedded Gen2 (preview)

### ISSUE THREAD

**Issue by Nordes** [terraform-providers/terraform-provider-azurerm#12048]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, we can create a PowerBI embedded resource. However, we can't choose the **resource mode** (Gen1 or Gen2). It now always default to Gen1.

### New or Affected Resource(s)

* azurerm_powerbi_embedded

### Potential Terraform Configuration

Simply add a new field `resource_mode` with possible values of `Gen1`, `Gen2` defaulting to Gen1.

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_powerbi_embedded" "example" {
  name                = "examplepowerbi"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  resource_mode  = "Gen2" # <== New
  sku_name            = "A1"
  administrators      = ["azsdktest@microsoft.com"]
}
```

### References

* https://docs.microsoft.com/en-us/power-bi/developer/embedded/power-bi-embedded-generation-2

**Comment by manicminer** [comment]
Closed with #12394
