### ISSUE TITLE
Support for setting global parameters on Azure Data Factory

### ISSUE THREAD

**Issue by JCZuurmond** [terraform-providers/terraform-provider-azurerm#12042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am looking for an options to set [global parameters](https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters) on a Azure Data Factory.

### New or Affected Resource(s)

1. azurerm_data_factory (add argument to set the global parameters
2. azurerm_data_factory_global_parameters (have a separate resource to set global parameters).

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  global_parameters = {
         parameter1 = value1
         parameter2 = value2
  }
}
```

### References

- https://docs.microsoft.com/en-us/azure/data-factory/author-global-parameters

**Comment by sskoklev** [comment]
> This functionality has been released in [v2.64.0 of the Terraform Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.64.0/CHANGELOG.md). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
> 
> For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new/choose) following the template. Thank you!

Can someone point me to an example if how to use the global_parameter?

**Comment by JCZuurmond** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/blob/8b1ad7950e4140b4dc3fd1f709955940f1f8b045/azurerm/internal/services/datafactory/data_factory_resource_test.go#L551

If someone could update the docs: that would be great!

**Comment by sskoklev** [comment]
> https://github.com/terraform-providers/terraform-provider-azurerm/blob/8b1ad7950e4140b4dc3fd1f709955940f1f8b045/azurerm/internal/services/datafactory/data_factory_resource_test.go#L551
> 
> If someone could update the docs: that would be great!

@JCZuurmond:
Thanks that did the trick. 
May be worth noting in the docs that the 'type' is case sensitive, as in 'String' worked 'string' did not.

**Comment by JCZuurmond** [comment]
Apparently this is added to the docs in the #12178 PR. It does not show on the Terraform provider website.
