### ISSUE TITLE
App Config tags keeps re-applying since AzureRM v2.61

### ISSUE THREAD

**Issue by dhmoto17** [terraform-providers/terraform-provider-azurerm#12050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_app_configuration`

### Expected Behaviour

No changes to app configuration resource

### Actual Behaviour

Every run of terraform reports an planned change to tags.
It also randomly picks one of the current tag values and reports that as the value for all the tags, which it will change to what is expected in code.
When checking Azure the tags are as they should be according to the code (i.e. no changes should be planned)

 azurerm_app_configuration.app_conf will be updated in-place
  ~ resource "azurerm_app_configuration" "app_conf" {
        endpoint            = "https://XXXX-appconfig.azconfig.io"
        id                  = "/subscriptions/XXXX-dc49-4afe-8839-bfa2fc3fc974/resourceGroups/XXXX-appconfig-rg/providers/Microsoft.AppConfiguration/configurationStores/XXXX-appconfig"
        location            = "uksouth"
        name                = "XXXX-appconfig"
        primary_read_key    = [
            {
                connection_string = "Endpoint=https://XXXX-appconfig.azconfig.io;Id=XXXX;Secret=XXXX"
                id                = "XXXX"
                secret            = "XXXX"
            },
        ]
        primary_write_key   = [
            {
                connection_string = "Endpoint=https://XXXX-appconfig.azconfig.io;Id=XXXX;Secret=XXXX"
                id                = "XXXX"
                secret            = "XXXX"
            },
        ]
        resource_group_name = "XXXX-appconfig-rg"
        secondary_read_key  = [
            {
                connection_string = "Endpoint=https://XXXX-appconfig.azconfig.io;Id=XXXX;Secret=XXXX"
                id                = "XXXX"
                secret            = "XXXX"
            },
        ]

        ]
        secondary_write_key = [
            {
                connection_string = "Endpoint=https://XXXX-appconfig.azconfig.io;Id=XXXX;Secret=XXXX"
                id                = "XXXX"
                secret            = "XXXX"
            },
        ]
        sku                 = "standard"
      ~ tags                = {
          ~ "business_owner"        = "5m" -> "Platform"
          ~ "data_sensitivity"      = "5m" -> "High"
          ~ "docs_location"         = "5m" -> ""
          ~ "environment"           = "5m" -> "dev"
          ~ "function_of_component" = "5m" -> "Stores and manages application configuration"
          ~ "function_of_system"    = "5m" -> "Stores and manages application configuration"
          ~ "name_of_system"        = "5m" -> "Application Configuration"
          ~ "namespace_environment" = "5m" -> "XXXX"
          ~ "parent"                = "5m" -> "XXXX-appconfig-rg"
            "rto"                   = "5m"
          ~ "tech_owner"            = "5m" -> "Platform"
        }
    }
    

### Steps to Reproduce

terraform plan with code containing an app configuration resource.

**Comment by nnnvvvcv** [comment]
I'm also seeing this. Seems something is randomly populating the tag map during the apply stage (or at some other point)
