### ISSUE TITLE
using delegated_subnet_id postgresql_flexible_server error

### ISSUE THREAD

**Issue by shayshahak** [terraform-providers/terraform-provider-azurerm#12053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
### Affected Resource(s)

* `azurerm_postgresql_flexible_server`

### Terraform Configuration Files

```hcl
provider "azurerm" {
   features {}
   subscription_id = "${var.subscription_id}"
   client_id       = "${var.client_id}"
   client_secret   = "${var.client_secret}"
   tenant_id       = "${var.tenant_id}"
}


resource "azurerm_resource_group" "main" {
  name     = "${var.prefix}-ResourceGroup"
  location = "${var.location}"
}

resource "azurerm_virtual_network" "main" {
  name                = "${var.prefix}-network"
  address_space       = ["172.16.0.0/16"]
  resource_group_name = "${azurerm_resource_group.main.name}"
  location            = "${azurerm_resource_group.main.location}"
}

resource "azurerm_subnet" "main" {
  name                 = "example-sn"
  resource_group_name  = "${azurerm_resource_group.main.name}"
  virtual_network_name = "${var.prefix}-network"
  address_prefixes       = ["172.16.0.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
  delegation {
    name = "fs"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_postgresql_flexible_server" "main" {
  name                   = "example-psqlflexibleserver"
  resource_group_name    = "${azurerm_resource_group.main.name}"
  location               = "${azurerm_resource_group.main.location}"
  version                = "12"
  delegated_subnet_id    = azurerm_subnet.main.id
  administrator_login    = "psqladminun"
  administrator_password = "H@Sh1CoR3!"

  storage_mb = 32768

  sku_name = "GP_Standard_D4s_v3"
}
```

### Expected Behaviour

when using the "delegated_subnet_id" option the provisioning fails. if commenting it out it runs successfully 

### Actual Behaviour

 failure of:
postgresqlflexibleservers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="MissingRequiredParameter" Message="Parameter'' must be specified. This parameter cannot be NULL or empty."
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jjindrich** [comment]
I have same problem and getting same error, just using example from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server

**Comment by yupwei68** [comment]
Hi @shayshahak @jjindrich , Thanks for opening this issue. We have contacted with the service team. Some changes in service have caused the break. We'll discuss for a solution.

**Comment by yupwei68** [comment]
Unfortunately, this is a breaking change from service. `delegated_subnet_id` is deprecated. We'll support for private dns zones in flexible server when the service is released in stable version.

**Comment by jjindrich** [comment]
Why do you mean is deprecated. This doc is reffering deployment into virtual network https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking. There is delegated subnet.

**Comment by yupwei68** [comment]
Unfortunately delegated subnet is deprecated. That is what I have got from service side. I will update the doc once I have got the breaking change announcement.

**Comment by Shaybs** [comment]
Hi @yupwei68,

How can we then refer to the private dns zone in the template?

Shuaib

**Comment by yupwei68** [comment]
Hi @Shaybs private dns zone is not supported in Terraform yet. We will enhance flexible server and support it when the api is released in stable version

**Comment by Shaybs** [comment]
Hi, @yupwei68 thanks for the update.

**Comment by yupwei68** [comment]
Hi all, the upstream service has reverted the breaking change temporarily (maybe one month). Currently we could set the vnet as before. But it'll requires a private dns zones when setting a vnet finally.
