### ISSUE TITLE
PostgreSQL Flexible Server not able to create using "delegated_subnet_id" option. 

### ISSUE THREAD

**Issue by ksadineni13** [terraform-providers/terraform-provider-azurerm#12073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

 Terraform ~> 0.14.11
  AzureRM ~> 2.62

### Affected Resource(s)

* `azurerm_postgresql_flexible_server`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "ks-rg"
  location = "eastus"
}

resource "azurerm_virtual_network" "example" {
  name                = "ks-vn"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "ks-sn"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
  delegation {
    name = "fs"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_postgresql_flexible_server" "example" {
  name                   = "ks-psqlflexibleserver"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  version                = "12"
  delegated_subnet_id    = azurerm_subnet.example.id
  administrator_login    = "psqladminun"
  administrator_password = "H@Sh1CoR3!"

  storage_mb = 32768

  sku_name = "GP_Standard_D4s_v3"
}
```

### Panic Output

Error: creating Postgresql Flexible Server "ks-psqlflexibleserver" (Resource Group "ks-rg"): postgresqlflexibleservers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="MissingRequiredParameter" Message="Parameter '' must be specified. This parameter cannot be NULL or empty."

### Expected Behaviour

Create Flexible server with Vnet integration using delegated subnet id. 

### Actual Behaviour

With `delegated_subnet_id` parameter we also need parameter to set `Private DNS Zone id` like below one. Its failing looking for Private DNS zone id saying its emply or null. Current module is missing option to set Private DNS Zone id.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server

"delegatedSubnetArguments": {
                    "subnetArmResourceId": "[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('virtualNetworks_ks_vnet_name'), 'ks-pg-subnet')]"
                },
                "**privateDnsZoneArguments**": {
                    "privateDnsZoneArmResourceId": "[resourceId('Microsoft.Network/privateDnsZones', parameters('privateDnsZones_ks_fs_private_postgres_database_azure_com_name'))]"
                },

### Steps to Reproduce

1. `terraform apply`

Error: creating Postgresql Flexible Server "ksad-psqlflexibleserver" (Resource Group "ksad-rg"): postgresqlflexibleservers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="MissingRequiredParameter" Message="Parameter '' must be specified. This parameter cannot be NULL or empty."

### References

* #0000

**Comment by rusticshiv86** [comment]
I also face similar issue, please get it fixed on priority.

**Comment by yupwei68** [comment]
duplicated of https://github.com/terraform-providers/terraform-provider-azurerm/issues/12053

**Comment by katbyte** [comment]
closing in favour of #12053
