### ISSUE TITLE
Provider produced inconsistent result after apply (on role binding)

### ISSUE THREAD

**Issue by gstolz** [terraform-providers/terraform-provider-azurerm#12087]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.15.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.62.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.1
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_2.62.0`

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "azure_kubernetes_service_rbac_cluster_admin" {
  principal_id         = var.aad_group_objectid
  role_definition_name = var.aad_rbac_cluster_admin
  scope                = azurerm_kubernetes_cluster.k8s.id
}
```

### Debug Output

```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_role_assignment.azure_kubernetes_service_rbac_cluster_admin, provider
│ "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Expected Behaviour

Creation of role assignment with success feddback in terraform

### Actual Behaviour

role assignment is indeed created, but Terraform repsonds with an error

### Steps to Reproduce

I'm not sure if this is liked to the creation of other resources as well. So I assume it is just about creating the role-binding-resource.

1. `terraform apply`

### Important Factoids

plain Azure public cloud

**Comment by aristosvo** [comment]
@gstolz Thanks for submitting!

I think this is a duplicate of #12057.

**Comment by gstolz** [comment]
yes sorry about that!

**Comment by aristosvo** [comment]
No problem 👍🏽
