### ISSUE TITLE
Instructions for importing non-TF created Subscriptions incomplete or inaccurate

### ISSUE THREAD

**Issue by danabrash** [terraform-providers/terraform-provider-azurerm#12101]
Hello,

When attempting to follow the syntax on this page to import a previously created subscription, I receive only errors that TF is unable to parse the resource ID.  

I followed the instructions "see adding an alias..." instructions as best I could understanding and included the resource block form my existing subscription including name, alias and ID.

I have tried every iteration of subscription identifier trying to interpret "the subscription_id property can be completed".  In every instance I receive an error.

If I terraform plan I get:

` Error: Error building AzureRM Client: obtain subscription(7aaaa1045-9aaa-42ae-9aae-0aaaaaaa7869) from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: Subscription '7aaaa1045-9aaa-42ae-9aae-0aaaaaaa7869' not found. Check the spelling and casing and try again.`

If I try to import, I get something similar to:

`
azurerm_subscription.alias: Importing from ID "/providers/Microsoft.Subscription/7aaaa1045-9aaa-42ae-9aae-0aaaaaaa7869"...
╷
│ Error: parsing Resource ID "/providers/Microsoft.Subscription/7aaaa1045-9aaa-42ae-9aae-0aaaaaaa7869": cannot parse resource id: "/providers/Microsoft.Subscription/7aaaa1045-9aaa-42ae-9aae-0aaaaaaa7869"
│
`

As I mentioned, I've tried numerous combinations of that resource ID path, with and without quotes.  I suspect something there my help and I just haven't hit it right somehow.  

In any case, please update with working instructions and examples please.

thank you!

**Comment by magodo** [comment]
The `azurerm_subscription` is used to *Manages an Alias for a Subscription - which adds an Alias to an existing Subscription, allowing it to be managed in Terraform - or create a new Subscription with a new Alias*. You can only import a subscription that is created outside of Terraform when it has an alias. Then you can follow [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription#import) to import it into Terraform's management. Note that the `subscription1` in the ID is the display name of the subscription in the Portal.

**Comment by danabrash** [comment]
Hello, thanks very much for the response.  Unfortunately I'm getting the same error following those steps.  
Perhaps I've missed something?

where \<subname\> is the name of the exiting subscription in the portal.

command:  

> terraform import azurerm_subscription.\<subname\> "/providers/Microsoft.Subscription/aliases/*\<subname\>"


results in:  

> Azurerm_subscription.\<subname\>: Importing from ID "/providers/Microsoft.Subscription/aliases/\<subname\>"...
> ╷
> │ Error: failed reading Subscription Alias: subscription.AliasClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionAliasNotFound" Message="Subscription alias not found"

The instructions indicate (or I misread) the need to create an alias for the subscription to import, so I also tried to create the alias as linked to in the section you reference, but this also fails.  The syntax in the article is a resource block.

I _think_ this may be related to my subscriptions are Azure Plan with a CSP and I don't have direct control of them.  However, all I'm trying to do is import them to state so that I can reference them and the rest of my apply can complete.  Would billing scope matter just for an import?

Thanks very much,
Dana

**Comment by magodo** [comment]
@danabrash If you are simply importing an existing alias into Terraform, then you'd only need to specify the properties as shown below:

```hcl
resource "azurerm_subscription" "example" {
  alias             = "examplesub"
  subscription_name = "My Example Subscription"
  subscription_id   = "12345678-12234-5678-9012-123456789012"
}
```

Following is my local execution:

```shell
💤 tf import azurerm_subscription.example "/providers/Microsoft.Subscription/aliases/mgd"
azurerm_subscription.example: Importing from ID "/providers/Microsoft.Subscription/aliases/mgd"...
azurerm_subscription.example: Import prepared!
  Prepared azurerm_subscription for import
azurerm_subscription.example: Refreshing state... [id=/providers/Microsoft.Subscription/aliases/mgd]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

Actually, the command the import the subscription alias is a bit different than what you have posted above:

`terraform import azurerm_subscription.<resource label name> "/providers/Microsoft.Subscription/aliases/<alias name>"`

**Comment by danabrash** [comment]
@magodo 

thanks for your reply

you have two different code samples, the first is for "examplesub" and the second is for "mgd"

is this an either one is enough, or do you need to resource block to add the alias and then reference it in an import to fetch it to state?

For my command, the resource label and alias are the same for simplicity

When I add the resource as per your first section  

```
>resource "azurerm_subscription" "ProdNet" {
  alias             = "ProdNet"
  subscription_name = "ProdNet"
  subscription_id   = "dbbbbbbb-8bbb-4bbb-bbbb-5aaebbbbbb3d"
}

```
When I plan it out is says it's going to create the subscription, yet it already exists.
I can't destroy these subscriptions.  I'm hoping 'will be created' means 'will add existing to state'.  
Will it overwrite my existing? It doesn't say it's  going to destroy anything....

```

# azurerm_subscription.ProdNet will be created
  + resource "azurerm_subscription" "ProdNet" {
      + alias             = "ProdNet"
      + id                = (known after apply)
      + subscription_id   = "dbbbbbbb-8bbb-4bbb-bbbb-5aaebbbbbb3d"
      + subscription_name = "ProdNet"
      + tags              = (known after apply)
      + tenant_id         = (known after apply)
   }

```
When I try to import the subscription it fails, and throws an error that my provider configuration will fail as well.  This error is what I interpreted as the redirect in the registry page to create an alias as above.  So then the import is not necessary after we have the resource block in the code?

```
> terraform import azurerm_subscription.ProdNet "/providers/Microsoft.Subscription/aliases/ProdNet"

azurerm_subscription.ProdNet: Importing from ID "/providers/Microsoft.Subscription/aliases/ProdNet"...
╷
│ Error: failed reading Subscription Alias: subscription.AliasClient#Get: Failure responding to request: 
StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionAliasNotFound" Message="Subscription alias not found"
│
│
╵

╷
│ Error: Invalid provider configuration
│
│   on C:\Repos\-----\main.tf line 49:
│   49: provider "azurerm" {
│
│ The configuration for provider["registry.terraform.io/hashicorp/azurerm"].ProdNet depends on values    
│ that cannot be determined until apply.

```

so on the one hand, it seems if I try to just add the resource specifically by alias with the subscription ID that I know, then I can 'create' that subscription, and presumably it'd be just part of state at that point and all is well.

However, if I want to directly import it into state, that basically is telling me it can't find the alias. 

Do I just go with the resource block in the code and let it 'create' the resource to add it to state without actually trying to create the resource in my environment?

Thanks for your help!

**Comment by magodo** [comment]
@danabrash You can use the resource block above to create the alias, though it looks like to create a subscription, but somehow the current implementation will see the `subscription_id` is specified and know the user is trying to create an alias. So the end result will be creating an alias.

However, note that **if you later destroy the resource, the subscription will be "destroyed" (actually moved into the cancel state)**. So for your use case, if you simply want to import an existing subscription by alias, I'd suggest you to create an alias via other means (e.g. `az account alias create`), then import it into terraform via the `azurerm_subscription` data source.

The error you got indicates there is no alias for your subscription for now.

**Comment by danabrash** [comment]
Thank you for the confirmation.  That makes sense, thank you.

My goal is actually to have the subscriptions managed in the state, so this works out fine having them aliased here.

Once I’ve applied the terraform with the aliases in it, can I remove the resource alias blocks just call the subscriptions as ‘data’?

**Comment by magodo** [comment]
If you intend to create the alias via Terraform and later replace it via using the data source, then after remove the resource block, you'd also need to remove it from the state via `terraform state rm`. Otherwise, Terraform will think you are explicitly removing the resource, which will end up into trying to remove/cancel the subscription.

**Comment by danabrash** [comment]
Thanks, so with that confidence I tried to apply.  My results:

```
│ Error: creating new Subscription (Alias "Connectivity"): subscription.AliasClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="AccountNotAllowed" Message="This account is not allowed for PUT subscription API"
│
│   with azurerm_subscription.Connectivity,
│   on existingsubs.tf line 28, in resource "azurerm_subscription" "Connectivity":
│   28: resource "azurerm_subscription" "Connectivity" {
│

```

I'm GA in the tenant.  Only thing I can think of is this is a CSP owned subscription (through partner center) and my account doesn't have permissions to manipulate the subscription directly.  We have to get them to create new subs for us.

In other words, I don't think this is a problem with my Terraform code anymore, I just need to get permissions from the CSP.  Does that sound right to you?

Super grateful for all your help with this.

**Comment by magodo** [comment]
@danabrash That makes sense.
