### ISSUE TITLE
Insufficient features blocks when having azurerm aliases

### ISSUE THREAD

**Issue by doonto** [terraform-providers/terraform-provider-azurerm#12111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```hcl
- name: terraformVersion
  default: '0.15.5'
```

```hcl
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~> 2.62.0"
      configuration_aliases = [azurerm.mcs, azurerm.shared]
    }
    azuread = {
      source = "hashicorp/azuread"
      version = "~> 1.5.0"
    }
  }
```

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    storage_account_name = "mcs-tf-${var.stage}-${var.environment}-st"
    container_name       = "tf-${var.stage}-${var.environment}"
    key                  = "${var.environment}.terraform.tfstate"
    use_msi              = true
    subscription_id      = "0f2abe48-bb4d-479d-aba3-94c9287cf29c"
    tenant_id            = "30f52344-4663-4c2e-bab3-61bf24ebbed8"
  }

provider "azurerm" {
  features {}
  subscription_id = "0f2abe48-bb4d-479d-aba3-94c9287cf29c"
  skip_provider_registration = "true"
  alias  = "mcs"
}

provider "azurerm" {
  features {}
  subscription_id = "2d9b064d-01f4-42f7-9c17-27f5fd5ee68b"
  skip_provider_registration = "true"
  alias  = "shared"
}

data "azurerm_resource_group" "MCSACRrg" {
  provider = azurerm.shared
  name = var.MCSACRrg
}

# Assign AcrPull role to rg
resource "azurerm_role_assignment" "acrpull_role" {
  scope                            = data.azurerm_resource_group.MCSACRrg.id
  role_definition_name             = "AcrPull"
  principal_id                     = data.azurerm_kubernetes_cluster.k8s.kubelet_identity.0.object_id
  skip_service_principal_aad_check = true
}
```

### Actual Behaviour

│ Error: Insufficient features blocks
│ 
│   on  line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The cluster is in one subscription, and the ACR is in another one. I need to assign the ACR pull role to the ACR rg. To do that simple thing, I have to declare another provider, working with another subscription. When I try to do so, I see that the features tag is missed, but it's there.

The googled approach to delete the alias, run successfully and return the alias doesn't work.
It builds successfully without the aliases, but when I return it back - I get the same error.

**Comment by aristosvo** [comment]
Hi @doonto!

I think you are using modules, can you show how you are forwarding the providers to the modules?

**Comment by nnellans-acts** [comment]
If this is in the root module (and not a child module) then you need to fix your azurerm_role_assignment resource and use the "provider" attribute to point it at one of the two providers you defined.  As of right now, the resource is using the default azurerm provider, of which, you don't have a provider block defined.

**Comment by doonto** [comment]
Hi and thanks for your replies!

```hcl
data "azurerm_resource_group" "MCSACRrg" {
  provider = azurerm.shared
  name = var.MCSACRrg
}

# Assign AcrPull role to rg
resource "azurerm_role_assignment" "acrpull_role" {
  scope                            = data.azurerm_resource_group.MCSACRrg.id
  role_definition_name             = "AcrPull"
  principal_id                     = data.azurerm_kubernetes_cluster.k8s.kubelet_identity.0.object_id
  skip_service_principal_aad_check = true
}
```
are in the 

```hcl
module "cluster-addons" {
  source = "./modules/cluster-addons"
  providers = {
    azurerm.shared = azurerm.shared
    azurerm.mcs    = azurerm.mcs
  }
```

Initially, I didn't declare providers in the module, since read, that this is a legacy way, and is not required in current versions.
But I just added providers declaration and still getting the same

`
│ Error: Insufficient features blocks
│ 
│   on  line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.
`

**Comment by nnellans-acts** [comment]
Your resources in the child module must reference one of the 2 providers that you are passing to the child module.  Add the "provider" line to the resources in the child module, see below.

`resource "azurerm_role_assignment" "acrpull_role" {
  provider                            = azurerm.shared or azurerm.mcs
  scope                            = data.azurerm_resource_group.MCSACRrg.id
  role_definition_name             = "AcrPull"
  principal_id                     = data.azurerm_kubernetes_cluster.k8s.kubelet_identity.0.object_id
  skip_service_principal_aad_check = true
}`

**Comment by doonto** [comment]
@nnellans-acts thanks, but this block is currently commented out, and my issue is the providers with aliases VS features {}.
By the way, I suppose, that if no provider is specified in the recourse block, it should take the default one, defined in the 
```hcl
backend "azurerm" {}
```

**Comment by nnellans-acts** [comment]
The backend block tells terraform where to store its remote state.  It has nothing to do with the providers being used by resources.

Any resource that looks like this:  **resource "azurerm_*"** which does NOT have a _provider_ property, will use the default azurerm provider.  That default provider must be defined in your code, like so:

    provider "azurerm" {
      features {}
      subscription_id
      tenant_id
      etc
    }

**Comment by doonto** [comment]
@nnellans-acts Thank you a lot!
However, I still think, that `Error: Insufficient features blocks` is not really a relevant error to describe this situation.

What set up worked for me:

```hcl
provider "azurerm" {
  features {}
  subscription_id = "0f2abe48-bb4d-479d-aba3-94c9287cf29c"
  skip_provider_registration = "true"
}

provider "azurerm" {
  features {}
  subscription_id = "2d9b064d-01f4-42f7-9c17-27f5fd5ee68b"
  skip_provider_registration = "true"
  alias  = "shared"
}

module "cluster-addons" {
  source = "./modules/cluster-addons"
  providers = {
    azurerm.shared = azurerm.shared
    azurerm    = azurerm
  }
}

```

```hcl
data "azurerm_resource_group" "MCSACRrg" {
  provider = azurerm.shared
  name = var.MCSACRrg
}

resource "azurerm_role_assignment" "acrpull_role" {
  scope                            = data.azurerm_resource_group.MCSACRrg.id
  role_definition_name             = "AcrPull"
  principal_id                     = data.azurerm_kubernetes_cluster.k8s.kubelet_identity.0.object_id
  skip_service_principal_aad_check = true
}
```
