### ISSUE TITLE
azurerm_app_service_plan: docs for webapp on linux

### ISSUE THREAD

**Issue by jeff1985** [terraform-providers/terraform-provider-azurerm#1213]
The docs under https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html state the following example:

    resource "azurerm_resource_group" "test" {
      name     = "api-rg-pro"
      location = "West Europe"
    }

    resource "azurerm_app_service_plan" "test" {
      name                = "api-appserviceplan-pro"
      location            = "${azurerm_resource_group.test.location}"
      resource_group_name = "${azurerm_resource_group.test.name}"
      kind                = "Linux"
      reserved            = true
    
      sku {
        tier = "Standard"
        size = "S1"
      }
    }

In the same time on the same page we find the description, which states:

> properties supports the following:
> reserved - (Optional) Is this App Service Plan Reserved. Defaults to false.

For me the example does not work, instead it shows the following message:
> Error: azurerm_app_service_plan.appserviceplan-alpha: : invalid or unknown key: reserved

The correct way to specify the reserved would be:

    resource "azurerm_app_service_plan" "test" {
        ...
        properties {
          reserved = true
        }

**Comment by tombuildsstuff** [comment]
hey @jeff1985 

Thanks for opening this issue :)

I've opened #1215 which updates the documentation (and the acceptance test) to fix this.

Thanks!
