### ISSUE TITLE
Support for azurerm_key_vault_secrets data source to bulk download secrets.

### ISSUE THREAD

**Issue by alex-goncharov** [terraform-providers/terraform-provider-azurerm#12146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to have a data source that will get all secrets in the given key vault (could be a list of names only).  

For the environment we are running, multiple KV's are used: one per `user`, where user can be anything: databricks, aks namespace, function app, etc. Terraform is responsible for the distribution of required secrets to "user" key vaults. Normally, human operators do not have access to these key vaults. Instead, they get a separate one to store secrets that come from the outside, an API token issued by 3rd party for example. Terraform is used to distribute these external secrets to "user" key vaults. This makes for a uniform way of managing such secrets: update value in ops key vault, run terraform pipeline. 

The ability to pull all secrets from the key vault will give us the ability to develop terraform code irrespective of the state of the ops key vault. 

### New or Affected Resource(s)

data azurerm_keyvault_secrets

### Potential Terraform Configuration

```hcl

data "azurerm_key_vault_secrets "these" {
 key_vault_id = azurerm_key_vault_this.id
}

data "azurerm_key_vault_secret" "this" {
  for_each = data.azurerm_key_vault_secrets.these.all
  name = each.key
  version = try(each.value[0], "latest")
}

resource "azurerm_key_vault_secret" {
  foreach = try({s = data.azurerm_key_vault_secret["secretly-secret-api-token"]}, {})
  name = each.value.name
  value = each.value..value
}
```

**Comment by favoretti** [comment]
As discussed offline - working on this.

// cc @tombuildsstuff
