### ISSUE TITLE
azurerm_postgresql_flexible_server - Error occurs when setting optional `zone` argument to `none`

### ISSUE THREAD

**Issue by fcatacut** [terraform-providers/terraform-provider-azurerm#12205]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/azurerm v2.63.0
```

### Affected Resource(s)

* `azurerm_postgresql_flexible_server`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "eastus"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vn"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "example-sn"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
  delegation {
    name = "fs"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_postgresql_flexible_server" "example" {
  name                   = "example-psqlflexibleserver"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  version                = "12"
  administrator_login    = "psqladminun"
  administrator_password = "H@Sh1CoR3!"

  sku_name   = "GP_Standard_D4s_v3"
  storage_mb = 32768
  zone       = "none"
}
```

### Debug Output

<https://gist.github.com/fcatacut/72403c770d4e45d2ed2ac461a863a7e2>

### Expected Behaviour

`terraform apply` successfully completes, and the PostgreSQL Flexible Server is successfully provisioned.

Note: `terraform apply` successfully completes when `zone` is set to `null`. However, Azure Portal indicates that `zone` is `3`.

### Actual Behaviour

`terraform apply` fails:

```
Error: waiting for creation of the Postgresql Flexible Server "example-psqlflexibleserver" (Resource Group "example-resources"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'a7c664ca-b42e-41e8-b648-66638a2312dc'"

  on main.tf line 34, in resource "azurerm_postgresql_flexible_server" "example":
  34: resource "azurerm_postgresql_flexible_server" "example" {
```

1. `terraform apply`

### References

* N/A

**Comment by wasfree** [comment]
@fcatacut i was able to reproduce this issue, from my prospective value "none" should be removed in azurerm provider as accepted parameter. 

If we want Azure to decide in which zone our postgres flexserver should be placed, zone argument should be unset. I'm not even sure if "none" is an accepted parameter, but InternalServerError indicate it's not. Azure Postgres Flexserver is a preview resource and there is probably a validation missing (on Azure API) if zone parameter has valid value.

**Comment by fcatacut** [comment]
@wasfree, in my head, I was thinking `zone` designated the availability zone where you want the standby replica to reside. It turns out that it designate the availability zone where the primary server resides, and Azure automatically picks a different zone in the same region.

> You can choose the region and the availability zone to deploy your primary database server. A standby replica server is automatically provisioned and managed in a different availability zone in the same region with the same compute, storage, and network configuration as the primary server.

Source: <https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/postgresql/flexible-server/concepts-high-availability.md#zone-redundant-high-availability-architecture>

I'll submit a PR to update the documentation. Thanks for the clarification.
