### ISSUE TITLE
Support for automatic_channel_upgrade = "node-image" in kubernetes_cluster_resource

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#12202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for "node-image" on `automatic_channel_upgrade` (https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel)

there was already a PR for this here, not sure why this was never reviewed/approved https://github.com/terraform-providers/terraform-provider-azurerm/pull/11588 (cc @liammoat )

### New or Affected Resource(s)

* kubernetes_cluster_resource

**Comment by liammoat** [comment]
@sebader - i had closed my PR as the underlying SDK version used didn't have support for "node-image" at the time. Happy to re-open it when that changes 👍

**Comment by heoelri** [comment]
Seems like that's the case now. PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/12667 (by @liammoat) brings support for "node-image" as was merged yesterday.

**Comment by tombuildsstuff** [comment]
Fixed via #12667
