### ISSUE TITLE
Cosmosdb account firewall exceptions

### ISSUE THREAD

**Issue by MMollyy** [terraform-providers/terraform-provider-azurerm#12201]
Description
Is there plans for the checkbox options "access to portal" & "Accept connections from within public Azure datacenters" ?

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```
resource "azurerm_cosmosdb_account" "cosmosdb" {
  firewall_exceptions = {
    portal_access = true
    public_azure_datacenter_access = true
  }
|
```

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/11965
https://github.com/terraform-providers/terraform-provider-azurerm/issues/9752

**Comment by tombuildsstuff** [comment]
Duplicate of #11965 and #9752
