### ISSUE TITLE
Azure IAM using Terraform - A side effect of this feature when executing the user provisioning code with a different set of users is the purging of existing users and replacing them with new ones

### ISSUE THREAD

**Issue by jhansinaidu** [terraform-providers/terraform-provider-azurerm#12214]
Using Terraform to provision users and groups in Azure Active Directory

As we know Terraform is a declarative IaC language wchich, unlike procedural languages, allows for the provisioning of immutable-like infrastructure resources by pushing the intended configuration state in its plan to the target environment. This is made possible by maintaining the state of the created resources in a state backend.

1. A side effect of this feature when executing the user provisioning code with a different set of users is the purging of existing users and replacing them with new ones:

![image](https://user-images.githubusercontent.com/60767139/122076307-c3f99880-cdc8-11eb-827c-f676e67f86d1.png)

Below there is the affected code:

![image](https://user-images.githubusercontent.com/60767139/122076421-de337680-cdc8-11eb-8a0b-c7023d22c09d.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.11
on linux_amd64

![image](https://user-images.githubusercontent.com/60767139/122076840-379ba580-cdc9-11eb-8edd-d3e1df255714.png)

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

![image](https://user-images.githubusercontent.com/60767139/122077698-f35cd500-cdc9-11eb-9338-93f43a7b5456.png)

{
  ad_group_name = "tenant_grp_01"

  tenant_users = [
      {
        displayname           = "Tenant User 1"
        password              = ""
        principal_name        = "tenant.user1@bell.ca"
        force_password_change = true
        given_name            = "Tenant"
        surname               = "User 1"
        usage_location        = "CA"
      }
      ,
      {
        displayname           = "Tenant User 2"
        password              = ""
        principal_name        = "tenant.user2@bell.ca"
        force_password_change = false
        given_name            = "Tenant"
        surname               = "User 2"
        usage_location        = "CA"
      }
    ]
}

### Debug Output

![image](https://user-images.githubusercontent.com/60767139/122077810-0ec7e000-cdca-11eb-960d-8c4f772c558f.png)

### Expected Behaviour

When provisioning a new users or group task repetitively terraform has got configuration state in its plan to the target environment. This is made possible by maintaining the state of the created resources in a state backend.

A side effect of this feature when executing the user provisioning code with a different set of users is the purging of existing users and replacing them with new ones

### Steps to Reproduce

1. `terraform apply`

### References

#0

**Comment by tombuildsstuff** [comment]
hi @jhansinaidu 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
