### ISSUE TITLE
Support for PostgreSQL Flexible Server Parameters

### ISSUE THREAD

**Issue by alexrosenfeld10** [terraform-providers/terraform-provider-azurerm#12222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Flexible servers can have server parameters (for example, `pgbouncer.enabled`), but the terraform provider seems to be lacking support for setting them.

### New or Affected Resource(s)

* azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server" "server" {
  name                   = "example"
  location               = "West US 2"
//  .... other params ....
  parameters = {
     pgbouncer.enabled = true
     otherkey = "othervalue"
  }
}
```

**Comment by wasfree** [comment]
@alexrosenfeld10 server parameters for Azure Postgres Flexserver should be configurable with it's own resource `azurerm_postgresql_flexible_server_configuration` similar than [Azure Postgres Server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_configuration). There is already a issue open see https://github.com/terraform-providers/terraform-provider-azurerm/issues/11538 to support this new resource.

**Comment by tombuildsstuff** [comment]
Closing in favour of #11538, since that's tracking this feature request - thanks @wasfree
