### ISSUE TITLE
Support for manual Service Principal token

### ISSUE THREAD

**Issue by adamconnelly** [terraform-providers/terraform-provider-azurerm#12237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm investigating whether it's possible to create an integration for Spacelift that would automatically generate short-lived credentials for use by the AzureRM provider. At the moment my thoughts are that we could create a multi-tenant Azure Application that could be installed into customer AAD tenants, creating a Service Principal that could be used for RBAC.

The idea is that before we run any Terraform commands, we would generate an Access Token for the relevant customer tenant, and then automatically configure an environment variable to pass that in (maybe something like `ARM_TOKEN`). So we'd basically be doing the step that the provider currently does to generate a token in advance, rather than in the provider.

The issue is that currently the provider only supports configuring the Service Principal via a Client Secret or Client Certificate.

In theory, I'm thinking this could work as an additional authentication method (https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/vendor/github.com/hashicorp/go-azure-helpers/authentication/builder.go#L65) that just returns static tokens.

So what I'm wondering is:

- Does the approach even make sense?
- Would this make sense as a feature for the provider, and would you potentially accept a contribution?

Thanks in advance!

### New or Affected Resource(s)

N/A

### Potential Terraform Configuration

N/A

### References

* https://endjin.com/blog/2019/01/managing-applications-using-azure-ad-service-principals-and-managed-identities

**Comment by tombuildsstuff** [comment]
hey @adamconnelly 

This has been requested previously (specifically passing in a token from the CLI, but the principle is the same), after looking into this we realised this won't work due the token refresh - since there's no guarantee the token can be refreshed - meaning that unfortunately this wouldn't fit with the current lifecycle of the provider. That said, I believe this should already be possible by generating a short-lived service principal, scoped to the Subscription/resources in question, using the existing Client Secret/Client Certificate functionality?

Since I believe this request isn't feasible due to the token refresh issue - whilst I'd like to thank you for opening this issue I'm going to close this for the moment - but as mentioned above it should be possible to achieve the same thing using the Client Secret/Client Certificate functionality and a short-lived Service Principal.

Thanks!

**Comment by adamconnelly** [comment]
@tombuildsstuff thanks a lot for the quick reply. I'm guessing the other issue you mentioned is https://github.com/terraform-providers/terraform-provider-azurerm/issues/5271? Sorry, I just couldn't figure out quite the right thing to search for initially.

> That said, I believe this should already be possible by generating a short-lived service principal, scoped to the Subscription/resources in question, using the existing Client Secret/Client Certificate functionality?

I'm not sure the short-lived service principal would work in this case, because it would require us to have the ability to grant it permissions over the resources being managed unless I'm missing something. The issue here is that the resources would be in a separate Azure subscription we don't have access to (the customer account).

> Since I believe this request isn't feasible due to the token refresh issue

Just so I understand this better, is the issue that the access token might expire while the provider still has an operation outstanding, so you need to be able to refresh the token to try to avoid a failure? Would it help if we could provide both the access and refresh tokens, or are you talking about a situation where the token just can't be refreshed and a completely new token needs to be requested?

Thanks again, and sorry if I'm asking annoying questions! :smile:

**Comment by marcinwyszynski** [comment]
Hey @tombuildsstuff !

> Since I believe this request isn't feasible due to the token refresh issue

I'm not sure this is a problem in practice. It just makes it the responsibility of the user to make sure that they generate a token for long enough to complete the job. In practice, Terraform jobs are not supposed to take hours. In the AWS world, at least [Spacelift](https://docs.spacelift.io/integrations/cloud-providers/aws) and [env0](https://docs.env0.com/docs/connect-your-cloud-account#using-aws-assume-role) support generating short-lived credentials by using a trust relationship. Doing the same thing for Azure surely can't hurt.

An example of the same approach outside of the Terraform world would be one of the most widely used GitHub Actions - [aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials), specifically looking at the way [assuming a role is handled](https://github.com/aws-actions/configure-aws-credentials#assuming-a-role). It's just up to the caller to generate credentials for long enough to let your job finish.

All I'm trying to argue here is that not supporting refresh is *fine*, as long as it's properly communicated and documented.

WDYT?
