### ISSUE TITLE
Private Link Service cannot modify Load balancer frontend id

### ISSUE THREAD

**Issue by jhisc** [terraform-providers/terraform-provider-azurerm#12249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.15.1

### Affected Resource(s)

* `azurerm_private_link_service`

### Terraform Configuration Files

```hcl
resource "azurerm_private_link_service" "example" {
  name                = "example-privatelink"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  auto_approval_subscription_ids              = ["00000000-0000-0000-0000-000000000000"]
  visibility_subscription_ids                 = ["00000000-0000-0000-0000-000000000000"]
  load_balancer_frontend_ip_configuration_ids = [azurerm_lb.example1.frontend_ip_configuration.0.id]

  nat_ip_configuration {
    name                       = "primary"
    private_ip_address         = "10.5.1.17"
    private_ip_address_version = "IPv4"
    subnet_id                  = azurerm_subnet.example.id
    primary                    = true
  }

  nat_ip_configuration {
    name                       = "secondary"
    private_ip_address         = "10.5.1.18"
    private_ip_address_version = "IPv4"
    subnet_id                  = azurerm_subnet.example.id
    primary                    = false
  }
}
```

### Expected Behaviour

Chaning a load balancer ID would update the existing private link service.

### Actual Behaviour

Terraform attempts to modify the resource but azure returns an error:

```
│ Error: Error creating Private Link Service "example-privatelink" (Resource Group "example-resources"): network.PrivateLinkServicesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="PrivateLinkServiceLoadBalancerReferenceCannotBeChanged" Message="Load balancer reference on private link service /subscriptions/removed/resourceGroups/example-resources/providers/Microsoft.Network/privateLinkServices/example-privatelink cannot be changed from /subscriptions/removed/resourceGroups/EXAMPLE-RESOURCES/providers/Microsoft.Network/loadBalancers/1-EXAMPLE-LB to /subscriptions/removed/resourceGroups/EXAMPLE-RESOURCES/providers/Microsoft.Network/loadBalancers/2-EXAMPLE-LB." Details=[]
```

### Steps to Reproduce

1. Create a private link service pointing to load balancer 1
2. Update that service to point at load balancer 2

### Important Factoids

This appears to be expected behaviour. Azure does not appear to support changing a private link service target.
Changing this value should force the creation of a new resource.

### References

* https://docs.microsoft.com/en-gb/rest/api/virtualnetwork/private-link-services/create-or-update#privatelinkservice

**Comment by tombuildsstuff** [comment]
Fixed via #12250
