### ISSUE TITLE
azurerm_storage_share_directory does not allow '_' in the name. 

### ISSUE THREAD

**Issue by iharrington** [terraform-providers/terraform-provider-azurerm#12241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_storage_share_directory allow for "name" to contain `_` (underscore).

### New or Affected Resource(s)

* azurerm_storage_share_directory

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

azurerm/internal/services/storage/validate/storage.go

```if !regexp.MustCompile(`^[A-Za-z0-9-]+(/[A-Za-z0-9-]+)*$`).MatchString(value) {		errors = append(errors, fmt.Errorf("%s must contain only uppercase and lowercase alphanumeric characters, numbers and hyphens, and can be nested multiple levels", k))	}```

Poposed solution: change  `^[A-Za-z0-9-]+(/[A-Za-z0-9-]+)*$` to `^[A-Za-z0-9-_]+(/[A-Za-z0-9-_]+)*$`

this will match `dir_name/child_dir_name` and not break other changes like nested child or hyphen inclusion.

* #0000

**Comment by brconnell4** [comment]
The hypens should be explicit as well and not amibgously declared as hyphens implicitly

`^[A-Za-z0-9\-_]+(/[A-Za-z0-9\-_]+)*$`

**Comment by iharrington** [comment]
Thanks!
