### ISSUE TITLE
Seems that data source when using azurerm_resources is not working as expected

### ISSUE THREAD

**Issue by evmimagina** [terraform-providers/terraform-provider-azurerm#12245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
v1.0.0
azurerm provider version 2.63.0
```

### Affected Resource(s)

* `azurerm_resources `

### Terraform Configuration Files

```hcl
#Create AKS Cluster using module
module "main_aks" {
  source = "./modules/azure/aks"

...

}

#I want to query the NSG linked to the AKS Default Node Pool for enabling diagnostic settings afterwards
data "azurerm_resources" "diag_nsg_aks_agentpool" {
  resource_group_name = module.main_aks.default_node_resource_group_name
  type = "Microsoft.Network/networkSecurityGroups"
}


```

### Actual Behaviour

The first time I run this, it fails, the second time I run, it works. 
I've been trying to set some dependencies manually, even using a time_sleep which depends on AKS module and afterwards the data "azurerm_resources" depending on the time_sleep.

When using other data sources, e.g. `"azurerm_lb"` , it works fine.

```terraform
data "azurerm_lb" "diag_aks_loadbalancer" {
  name                = "kubernetes"
  resource_group_name = module.main_aks.default_node_resource_group_name
}
```

### Expected Behaviour

Should work on first pass, the data source "azurerm_resources" should wait until the module which will be passing some details ends, and it doesn't.

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @evmimagina 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by evmimagina** [comment]
Hi @tombuildsstuff , I'm not asking, sorry, but I though I was explaining about something that doesn't work and that might be a problem...

**Comment by evmimagina** [comment]
Or this one from your github: https://github.com/terraform-providers/terraform-provider-azurerm/issues/10233
