### ISSUE TITLE
azurerm_virtual_machine_scale_set is missing the ip_forwarding property

### ISSUE THREAD

**Issue by djsly** [terraform-providers/terraform-provider-azurerm#1226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
`azurerm_virtual_machine_scale_set` should allow the user to set the ip forwarding for the VM scale set nics as part of the network profile configuration

### New or Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ruzin** [comment]
@djsly this hasn't been documented on terraform.

**Comment by tombuildsstuff** [comment]
@ruzin please open a new issue for this :)
