### ISSUE TITLE
Support for acrUseManagedIdentityCreds in azurerm_app_service

### ISSUE THREAD

**Issue by haraldatbmw** [terraform-providers/terraform-provider-azurerm#12277]
### Description

Add argument for enabling to use managed identity to login to ACR.

By now I have to add an execution of an az command to enable this.

```hcl
  resource "azurerm_app_service" "myapp" {
    ...

    # Use managed identity to login to ACR
    # https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_system-assigned_managed_identities.md
    provisioner "local-exec" {
      command = "az resource update --ids ${self.id}/config/web --set properties.acrUseManagedIdentityCreds=True -o none"
    }
  }
```

### New or Affected Resource(s)

* azurerm_app_service

### References

https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_system-assigned_managed_identities.md

**Comment by mozts2005** [comment]
The Azure Go SDK version 55.2.0 supports API version 2020-12-01. 

Which adds the needed properties.  https://github.com/Azure/azure-sdk-for-go/blob/main/services/web/mgmt/2020-12-01/web/CHANGELOG.md 
 
https://github.com/Azure/azure-sdk-for-go/releases/tag/v55.2.0
