### ISSUE TITLE
Unable to change storage account replication type

### ISSUE THREAD

**Issue by michaelelleby** [terraform-providers/terraform-provider-azurerm#12271]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.0. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_storage_account" "storage" {
  name = local.storage_account_name
  resource_group_name = azurerm_resource_group.rg.name
  location = azurerm_resource_group.rg.location
  account_tier = "Standard"
  account_replication_type  = "GZRS"
  enable_https_traffic_only = true
  min_tls_version = "TLS1_2"
}
```

### Expected Behaviour

https://docs.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal#switch-between-types-of-replication describes how to change replication type and ZRS to GZRS requires a Live Migration to be performed by Azure Support. Changing from ZRS to GZRS should be denied by Terraform.

### Actual Behaviour

`Error: Error updating Azure Storage Account type "...": storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="StorageAccountTypeConversionNotAllowed" Message="Storage account type Standard_ZRS cannot be changed to Standard_GZRS."`

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
this will likely need a force new oni the property as the API isn't allowing us to change it inplace
