### ISSUE TITLE
MSI with count unusable for role assignment

### ISSUE THREAD

**Issue by cehoffman** [terraform-providers/terraform-provider-azurerm#1227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`0.11.7`

### Affected Resource(s)

* azurerm_virtual_machine
* azurerm_role_assignment

### Terraform Configuration Files

```hcl
  principal_id       = "${lookup(element(azurerm_virtual_machine.worker.*.identity[0], count.index), "principal_id")}"
```

### Debug Output

~~~sh
${element(azurerm_virtual_machine.worker.*.identity[0], count.index)}
* module.masters-v5.azurerm_role_assignment.worker_role_assignment[2]: element: element() may only be used with flat lists, this list contains elements of type map in:
~~~

### Expected Behavior

Could apply a role to a set of VMs created using count.

### Actual Behavior

Failure parsing terraform config due to list of maps.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This make usage of MSI with availability sets untenable. The machines can not be bound to roles to give the necessary access. Using a scale set works though since there is no need to index by `count.index` in the role assignment although if you used count with a scale set it would have this problem.

### References

* #482

**Comment by cehoffman** [comment]
I gave this a try and it worked. I had tried a similar thing inline, but it always complained about the `.` indexing after identity. Another one of those terraform syntax odditites.

**Comment by hbuckle** [comment]
It's going to get even more interesting when VMs with multiple identities start cropping up

**Comment by tombuildsstuff** [comment]
hey @cehoffman 

Thanks for opening this issue.

Taking a look into this this appears to be a question more for Terraform Core than the Azure Provider (since this is regarding configuration syntax), but I believe this should have become less painful with Terraform 0.12 - as such if this is still an issue for you with Terraform 0.12 would you mind [re-opening this issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone on the Core team should be able to comment further?

Thanks!
