### ISSUE TITLE
Azure role assignment - PrincipalType attribute required but field cannot be set

### ISSUE THREAD

**Issue by DanGiffen** [terraform-providers/terraform-provider-azurerm#12303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

![image](https://user-images.githubusercontent.com/38534725/122813579-02acb880-d2cb-11eb-8a6f-422ed35771ef.png)
### Affected Resource(s)

azurerm_role_assignment

### Terraform Configuration Files

![image](https://user-images.githubusercontent.com/38534725/122814544-405e1100-d2cc-11eb-8b94-0414b8210fb2.png)

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Assign IAM role to an Azure AD Group

### Actual Behaviour

Plan is fine but apply errors as default principal type is ServicePrincipal but PrincipalType attribute is not supported so cannot define it as "Group"

![image](https://user-images.githubusercontent.com/38534725/122815779-d2b2e480-d2cd-11eb-8fab-4ebd4f09c03a.png)

Note also spelling error in the error, reads "PrinciaplType"

![image](https://user-images.githubusercontent.com/38534725/122816041-21f91500-d2ce-11eb-9633-fb03c0dfa2e7.png)

### Steps to Reproduce

Assign anything but ServicePrincipal a role

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. As stated in the docs:
```
`skip_service_principal_aad_check` - (Optional) If the principal_id is a newly provisioned Service Principal set this value to true to skip the Azure Active Directory check which may fail due to replication lag. This argument is only valid if the principal_id is a Service Principal identity. If it is not a Service Principal identity it will cause the role assignment to fail. Defaults to false.
```
Since in your case this is a group and not an SP you need to remove this option.

**Comment by DanGiffen** [comment]
Ok sure, thanks for the feedback @favoretti. Shame plan doesn't highlight that issue and the error messaging could do with some revising. Cheers Dan
