### ISSUE TITLE
azurerm_mssql_database short_term_retention_policy is too restrictive

### ISSUE THREAD

**Issue by OmerLaza** [terraform-providers/terraform-provider-azurerm#12315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0
+ provider registry.terraform.io/hashicorp/random v3.1.0  # Irrelevant
+ provider registry.terraform.io/hashicorp/time v0.7.1 # Irrelevant

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "db" {
  name           = var.db_name
  server_id      = azurerm_sql_server.db_server.id
  collation      = var.collation
  license_type   = "LicenseIncluded"
  max_size_gb    = var.storage_in_gb
  read_scale     = true
  sku_name       = var.sku_size
  zone_redundant = true
  short_term_retention_policy {
    retention_days = 3 # This is the important line
  }
  tags = local.common_tags
}
```

### Debug Output

https://gist.github.com/OmerLaza/3b90626e162df96fe49595bdaf7fa67f

### Expected Behaviour

Being able to set ```short_term_retention_policy``` ```retention_days``` to number<7 (and >=1), as possible via the portal and as documented [here](https://docs.microsoft.com/en-us/azure/azure-sql/database/automated-backups-overview?tabs=single-database#backup-retention).

### Actual Behaviour

Getting ```Error: expected short_term_retention_policy.0.retention_days to be in the range (7 - 35), got 3``` while the action feasible through the Portal. 

### Steps to Reproduce

1.  Put the TF code motioned above with the other relevant resources it depends on.
1. `terraform apply`

### Solution
I believe the problem is cased because of [this line](https://github.com/terraform-providers/terraform-provider-azurerm/blob/8b1ad7950e4140b4dc3fd1f709955940f1f8b045/azurerm/internal/services/mssql/helper/sql_retention_policies.go#L70), and changing it to ```ValidateFunc: validation.IntBetween(1, 35),``` will fix the problem (I can even do it myself as my first contribution if more experienced devs think it's a good idea 💪). 

### References

https://docs.microsoft.com/en-us/azure/azure-sql/database/automated-backups-overview?tabs=single-database#backup-retention

**Comment by katbyte** [comment]
Hey @OmerLaza - i believe this was fixed in 12198 🙂 which will go out this thursday. as such i'm going to close this

**Comment by OmerLaza** [comment]
Thanks for the response @katbyte 😄 
I'm not really very experienced in either Go or TF internals, but I've looked the PR you've mentioned  (#12198) and the ```ShortTermRetentionPolicySchema()``` validation seems to still contain the restriction to min of 7 days as it (the PR) only changes stuff related to Long Term Retention. So I'm not really sure it'll fix the problem.
