### ISSUE TITLE
Support for private_ip_ranges on azurerm_firewall_policy

### ISSUE THREAD

**Issue by jkroepke** [terraform-providers/terraform-provider-azurerm#12311]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable to configure SNAT private IPs, if Azure Firewall configured with a firewall polices.

TF provides private_ip_ranges for the firewall resource, but looking at UI

![image](https://user-images.githubusercontent.com/1560587/122890708-3841b800-d344-11eb-968c-a8b5defec6ff.png)

It was managed by firewall polices

### New or Affected Resource(s)

* azurerm_firewall_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_firewall_policy" "base" {
  ...

  # Must be set though UI
  private_ip_ranges = ["172.16.0.0/12"]
}
```

**Comment by katbyte** [comment]
property exists in `Snat *FirewallPolicySNAT` :

```
// FirewallPolicySNAT the private IP addresses/IP ranges to which traffic will not be SNAT.
type FirewallPolicySNAT struct {
	// PrivateRanges - List of private IP addresses/IP address ranges to not be SNAT.
	PrivateRanges *[]string `json:"privateRanges,omitempty"`
}
```
