### ISSUE TITLE
Support for setting Databricks custom parameter amlWorkspaceId 

### ISSUE THREAD

**Issue by noderat** [terraform-providers/terraform-provider-azurerm#12321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [amlWorkspaceId](https://docs.microsoft.com/en-us/azure/templates/microsoft.databricks/workspaces?tabs=json#workspacecustomparameters-object) custom parameter used to link an Azure Machine Learning workspace to Databricks is not currently a custom parameter that is available in Terraform.

### New or Affected Resource(s)

* azurerm_databricks_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_machine_learning_workspace" "example" {
  ...
}

resource "azurerm_databricks_workspace" "example" {
  ...

  custom_parameters {
    aml_workspace_id = azurerm_machine_learning_workspace.example.id
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/templates/microsoft.databricks/workspaces?tabs=json#workspacecustomparameters-object

**Comment by WodansSon** [comment]
This was fixed in #12331
