### ISSUE TITLE
Error "azurerm_bot_channel_directline" ouput 'key' and 'key2'

### ISSUE THREAD

**Issue by stefan-rapp** [terraform-providers/terraform-provider-azurerm#12338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.15.4 
on windows_amd64 
+ provider registry.terraform.io/hashicorp/azuread v1.5.0 
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1
```

### Affected Resource(s)

* `azurerm_bot_channel_directline`

### Terraform Configuration Files

```hcl
...

resource "azurerm_bot_channel_directline" "directline" {
    bot_name              = azurerm_bot_web_app.botservice.name   
    location              = azurerm_bot_web_app.botservice.location   
    resource_group_name   = azurerm_resource_group.rg.name   
    
    site {
        name    = "Default Site"
        enabled = true   
    }
    
    depends_on = [ azurerm_resource_group.rg, azurerm_bot_web_app.botservice ]
}


output "key1" {
    value       = azurerm_bot_channel_directline.directline.site[*].key
}

...

```

### Expected Behaviour

Output should return the `key` value of the `azurerm_bot_channel_directline ` in the block `site `in clear text. The output should be used to put it as secret to an Azure Key Vault later on.

### Actual Behaviour

Error:
`To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as │ sensitive, to confirm your intent. │ │ If you do intend to export this data, annotate the output value as sensitive by adding the following argument: │     sensitive = true`

We already used `sensitive = true ` in the output to solve the problem, but that did not help. Then we get the following error:

`Block type "site" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.`

Any ideas how to get the output of the site for `key`.

### Steps to Reproduce

1. `terraform apply`

### References

* #8248

**Comment by tombuildsstuff** [comment]
hi @stefan-rapp 

Thanks for opening this issue.

Taking a look through this appears to be a Configuration question, so that we can keep this forum focused on feature enhancements and bugs in the Azure Provider we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
