### ISSUE TITLE
azurerm_vpn_gateway.hub_vpn_gateway wants to replace resource

### ISSUE THREAD

**Issue by JackStromberg** [terraform-providers/terraform-provider-azurerm#12340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0

### Affected Resource(s)

* `azurerm_vpn_gateway.hub_vpn_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_hub" "vwan_hub" {
    name                = "vhub-vwan-eastus"
    location            = "eastus"
    resource_group_name = "my-RG"
    virtual_wan_id      = var.vwan_id
    address_prefix      = "10.10.10.0/24"
}
resource "azurerm_vpn_gateway" "hub_vpn_gateway" {
    name                = "vhub_vpn_gateway"
    location            = "eastus"
    resource_group_name = "my-RG"
    virtual_hub_id      = azurerm_virtual_hub.vwan_hub.id
}
```

Alternatively, you can copy and paste from docs here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_gateway

### Debug Output

https://gist.github.com/JackStromberg/1aa6c44f6560199b91f4bfd31fe5068a

### Expected Behaviour

Values determined after provisioning should not cause replacement of the resource.  More specifically, ignore the values that are dynamically determined by the service post-resource creation.

### Actual Behaviour

Terraform will try to replace the deployed resource.

### Steps to Reproduce

1. `terraform apply`

### References

This seems to be a similar issue happening, but on an Azure Firewall resource: #11043

**Comment by magodo** [comment]
@JackStromberg Thank you for submitting this! I've tried to reproduce this using the same TF & provider version as you've used, by applying the config from the doc: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_gateway. However, after the provisioning, the `terraform plan` shows no diff.

Would you please kindly guide me with the detailed steps to reproduce this?

**Comment by JackStromberg** [comment]
I copied my project to a new directory to remove all state.  Looks like things are working / I cannot repro now.  Will close out.  Sorry about that!
