### ISSUE TITLE
azurerm_application_gateway.network: Still creating... [30m50s elapsed]

### ISSUE THREAD

**Issue by shreyansbardia** [terraform-providers/terraform-provider-azurerm#12345]
I am getting this while trying to create application Gateway. The application Gateway is created but it is still showing this.
azurerm_application_gateway.network: Still creating... [30m50s elapsed]
I am following this https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway

It is like this

 
azurerm_application_gateway.network: Creating...
azurerm_application_gateway.network: Still creating... [10s elapsed]
azurerm_application_gateway.network: Still creating... [20s elapsed]
azurerm_application_gateway.network: Still creating... [30s elapsed]
azurerm_application_gateway.network: Still creating... [40s elapsed]
azurerm_application_gateway.network: Still creating... [50s elapsed]
azurerm_application_gateway.network: Still creating... [1m0s elapsed]
azurerm_application_gateway.network: Still creating... [1m10s elapsed]
azurerm_application_gateway.network: Still creating... [1m20s elapsed]
azurerm_application_gateway.network: Still creating... [1m30s elapsed]
azurerm_application_gateway.network: Still creating... [1m40s elapsed]
azurerm_application_gateway.network: Still creating... [1m50s elapsed]
azurerm_application_gateway.network: Still creating... [2m0s elapsed]
azurerm_application_gateway.network: Still creating... [2m10s elapsed]
azurerm_application_gateway.network: Still creating... [2m20s elapsed]
azurerm_application_gateway.network: Still creating... [2m30s elapsed]
azurerm_application_gateway.network: Still creating... [2m40s elapsed]
azurerm_application_gateway.network: Still creating... [2m50s elapsed]
azurerm_application_gateway.network: Still creating... [3m0s elapsed]
azurerm_application_gateway.network: Still creating... [3m10s elapsed]
azurerm_application_gateway.network: Still creating... [3m20s elapsed]
azurerm_application_gateway.network: Still creating... [3m30s elapsed]
azurerm_application_gateway.network: Still creating... [3m40s elapsed]
azurerm_application_gateway.network: Still creating... [3m50s elapsed]
azurerm_application_gateway.network: Still creating... [4m0s elapsed]
azurerm_application_gateway.network: Still creating... [4m10s elapsed]
azurerm_application_gateway.network: Still creating... [4m20s elapsed]
azurerm_application_gateway.network: Still creating... [4m30s elapsed]
azurerm_application_gateway.network: Still creating... [4m40s elapsed]
azurerm_application_gateway.network: Still creating... [4m50s elapsed]
azurerm_application_gateway.network: Still creating... [5m0s elapsed]
azurerm_application_gateway.network: Still creating... [5m10s elapsed]
azurerm_application_gateway.network: Still creating... [5m20s elapsed]
azurerm_application_gateway.network: Still creating... [5m30s elapsed]
azurerm_application_gateway.network: Still creating... [5m40s elapsed]
azurerm_application_gateway.network: Still creating... [5m50s elapsed]
azurerm_application_gateway.network: Still creating... [6m0s elapsed]
azurerm_application_gateway.network: Still creating... [6m10s elapsed]
azurerm_application_gateway.network: Still creating... [6m20s elapsed]
azurerm_application_gateway.network: Still creating... [6m30s elapsed]
azurerm_application_gateway.network: Still creating... [6m40s elapsed]
azurerm_application_gateway.network: Still creating... [6m50s elapsed]
azurerm_application_gateway.network: Still creating... [7m0s elapsed]
azurerm_application_gateway.network: Still creating... [7m10s elapsed]
azurerm_application_gateway.network: Still creating... [7m20s elapsed]
azurerm_application_gateway.network: Still creating... [7m30s elapsed]
azurerm_application_gateway.network: Still creating... [7m40s elapsed]
azurerm_application_gateway.network: Still creating... [7m50s elapsed]
azurerm_application_gateway.network: Still creating... [8m0s elapsed]
azurerm_application_gateway.network: Still creating... [8m10s elapsed]
azurerm_application_gateway.network: Still creating... [8m20s elapsed]
azurerm_application_gateway.network: Still creating... [8m30s elapsed]
azurerm_application_gateway.network: Still creating... [8m40s elapsed]
azurerm_application_gateway.network: Still creating... [8m50s elapsed]
azurerm_application_gateway.network: Still creating... [9m0s elapsed]
azurerm_application_gateway.network: Still creating... [9m10s elapsed]
azurerm_application_gateway.network: Still creating... [9m20s elapsed]
azurerm_application_gateway.network: Still creating... [9m30s elapsed]
azurerm_application_gateway.network: Still creating... [9m40s elapsed]
azurerm_application_gateway.network: Still creating... [9m50s elapsed]
azurerm_application_gateway.network: Still creating... [10m0s elapsed]
azurerm_application_gateway.network: Still creating... [10m10s elapsed]
azurerm_application_gateway.network: Still creating... [10m20s elapsed]
azurerm_application_gateway.network: Still creating... [10m30s elapsed]
azurerm_application_gateway.network: Still creating... [10m40s elapsed]
azurerm_application_gateway.network: Still creating... [10m50s elapsed]
azurerm_application_gateway.network: Still creating... [11m0s elapsed]
azurerm_application_gateway.network: Still creating... [11m10s elapsed]
azurerm_application_gateway.network: Still creating... [11m20s elapsed]
azurerm_application_gateway.network: Still creating... [11m30s elapsed]
azurerm_application_gateway.network: Still creating... [11m40s elapsed]
azurerm_application_gateway.network: Still creating... [11m50s elapsed]
azurerm_application_gateway.network: Still creating... [12m0s elapsed]
azurerm_application_gateway.network: Still creating... [12m10s elapsed]
azurerm_application_gateway.network: Still creating... [12m20s elapsed]
azurerm_application_gateway.network: Still creating... [12m30s elapsed]
azurerm_application_gateway.network: Still creating... [12m40s elapsed]
azurerm_application_gateway.network: Still creating... [12m50s elapsed]
azurerm_application_gateway.network: Still creating... [13m0s elapsed]
azurerm_application_gateway.network: Still creating... [13m10s elapsed]
azurerm_application_gateway.network: Still creating... [13m20s elapsed]
azurerm_application_gateway.network: Still creating... [13m30s elapsed]

**Comment by tombuildsstuff** [comment]
hi @shreyansbardia 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
