### ISSUE TITLE
Support PostgreSQL Flexible Server Version 13

### ISSUE THREAD

**Issue by sigv** [terraform-providers/terraform-provider-azurerm#12375]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```text
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
```

### Affected Resource(s)

* `azurerm_postgresql_flexible_server`

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
  name                   = "example-psqlflexibleserver"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  version                = "13"
  delegated_subnet_id    = azurerm_subnet.example.id
  administrator_login    = "psqladminun"
  administrator_password = "H@Sh1CoR3!"

  storage_mb = 32768

  sku_name = "GP_Standard_D4s_v3"
}
```

### Expected Behaviour

```text
Terraform will perform the following actions:

  # azurerm_postgresql_flexible_server.example will be created
  + resource "azurerm_postgresql_flexible_server" "example" {
      + administrator_login           = "psqladminun"
      + administrator_password        = (sensitive value)
      + backup_retention_days         = 7
      + cmk_enabled                   = (known after apply)
      + create_mode                   = "Default"
      + fqdn                          = (known after apply)
      + id                            = (known after apply)
      + location                      = "westeurope"
      + name                          = "example-psqlflexibleserver"
      + public_network_access_enabled = (known after apply)
      + resource_group_name           = "example"
      + sku_name                      = "GP_Standard_D4s_v3"
      + storage_mb                    = 32768
      + version                       = "13"
      + zone                          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Actual Behaviour

```text
Error: expected version to be one of [11 12], got 13

  with azurerm_postgresql_flexible_server.example,
  on example.tf line 15, in resource "azurerm_postgresql_flexible_server" "example":
   5:   version                = "13"
```

### Steps to Reproduce

1. `terraform plan`

**Comment by sigv** [comment]
For reference, [Supported versions - Azure Database for PostgreSQL - Flexible Server | Microsoft Docs](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions) says:
> **PostgreSQL version 13**
> The current minor release is 13.3.
>
> **PostgreSQL version 12**
> The current minor release is 12.7. 
>
> **PostgreSQL version 11**
> The current minor release is 11.12.
>
> **PostgreSQL version 10 and older**
> We do not support PostgreSQL version 10 and older for Azure Database for PostgreSQL - Flexible Server.

**Comment by matt961** [comment]
Ran into this yesterday too, looks like 13 was added to the Azure SDK enum yesterday

https://github.com/Azure/azure-sdk-for-go/pull/14914

**Comment by sigv** [comment]
Oh, did not get around to digging into it deeper. Thank you for the reference!

Will leave this ticket for the SDK dependency update in that case.
