### ISSUE TITLE
Error: Empty non-retryable error received with "azurerm_eventhub_authorization_rule"

### ISSUE THREAD

**Issue by blame19** [terraform-providers/terraform-provider-azurerm#12387]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

We're hitting this problem with the following versions:

Terraform v1.0
Azurerm ">= 2.46.0"

Terraform v1.0
Azurerm ">= 2.65.0"

Terraform v0.13.8
Azurerm ">= 2.46.0"

Terraform v0.13.8
Azurerm ">= 2.0"

### Affected Resource(s)

azurerm_eventhub_authorization_rule

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test-eventhub-resources" {
  name     = var.rg_name
  location = "eastus2"
}

resource "azurerm_resource_group" "test-eventhub-resources-secondary" {
  name     = "${var.rg_name}-secondary"
  location = "westus2"
}

module "test-no-cluster" {
  source = "../../"
  providers = {
    azurerm.default = azurerm
  }

  environment = "prod"
  resource_group = {
    name     = azurerm_resource_group.test-eventhub-resources.name
    location = azurerm_resource_group.test-eventhub-resources.location
  }

  eh_namespaces = {
    ci-test-mock = {
      sku                         = "Standard"
      capacity                    = 1
      auto_inflate_enabled        = true
      maximum_throughput_units    = 20
      network_rule_default_action = "Allow"
      virtual_network_rules       = []
      ip_rules                    = []
      environment                 = "prod"
      zone_redundant              = false
    }
  }
  eh_namespace_auth_rules = {
    eader = {
      namespace      = "ci-test-mock"
      listen_allowed = true
      send_allowed   = false
      manage_allowed = false
    }
  }

  eventhub_configs = {
    logs = {
      partition_count   = 2
      message_retention = 1
      namespace         = "ci-test-mock"
    }
  }
  eventhub_authorization_rules = {
    log-reader = {
      eventhub_name  = "logs"
      listen_allowed = true
      send_allowed   = false
      manage_allowed = false
      namespace      = "ci-test-mock"
    }
  }
}
```

### Expected Behaviour

The resource should have been created correctly, or returned a terraform understandable error.

### Actual Behaviour

We got
```
Error: empty non-retryable error received. This is a bug with the Terraform provider and should be reported as a GitHub issue in the provider repository.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

///

### References

The same issue is opened here:
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/10704

Opening this since we're hitting this with different tf/azurerm provider versions.

**Comment by regiluze** [comment]
Hi there,

I'm having the same issue, the terraform and provider version are:

Terraform v0.15.4
Azurerm ">= 2.65.0

thanks 👍

**Comment by SPea-1** [comment]
I hit this same issue today when I upgraded from version 2.47.0 of the azurerm provider to 2.65.0. When I reverted to 2.47.0 the issue went away. I'm using terraform v0.14.8.

**Comment by Ryan-Hzh** [comment]
Same issue when I am using terraform 1.0.1 + azurerm >= 2.65

**Comment by timothymathison** [comment]
Downgrading to `2.60` resolved this for me. I'm wondering if it was introduced in `2.61` by major changes from #11973?

**Comment by Ryan-Hzh** [comment]
> Same issue when I am using terraform 1.0.1 + azurerm >= 2.65

Resolved moving back to 2.47

**Comment by sebader** [comment]
is anybody looking into this? It has now been 4 versions and we cannot use anything newer than 2.64 since we are dependent on Event Hubs.

**Comment by favoretti** [comment]
FWIW once rules are created with 2.64 one can use the latest version again. Not ideal, but a semi-workaround.
