### ISSUE TITLE
Support for Azure storage blob backup

### ISSUE THREAD

**Issue by thomasmRavn** [terraform-providers/terraform-provider-azurerm#12389]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi
We have a requirement to backup azure blob storage in our company. I have looked though the docs and it doesn't seem to be enabled in terraform. 
Following the docs https://docs.microsoft.com/en-us/azure/backup/blob-backup-configure-manage I can see how to do this in the portal. However in terraform the only resource I can see is azurerm_data_protection_backup_vault which creates the backup vault, but doesn't then link that backup vault to a storage account.
I believe we need a new tf resource to create that link

### New or Affected Resource(s)
would need something like
* azurerm_data_protection_backup_blob
* azurerm_data_protection_backup_policy_blob

* azurerm_data_protection_backup_vault

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_data_protection_backup_vault" "example" {
  name                = "example-backup-vault"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  datastore_type      = "VaultStore"
  redundancy          = "LocallyRedundant"
}
### extra tf config to create backup, taken from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_container_storage_account
```

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_container_storage_account
* https://docs.microsoft.com/en-us/azure/backup/blob-backup-configure-manage

**Comment by tombuildsstuff** [comment]
Fixed via #12362
