### ISSUE TITLE
azurerm_storage_account reveals sensitive data in console

### ISSUE THREAD

**Issue by subesokun** [terraform-providers/terraform-provider-azurerm#1239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
provider.azurerm: version = "~> 1.4"

### Affected Resource(s)

* azurerm_storage_account

### Expected Behavior

While creating or applying an execution plan no sensitive data should be printed into the console logs. This is very important in case TF is running as part of a CI/CD pipeline.

### Actual Behavior

If TF detects a change on a `azurerm_storage_account` resource and needs to recreate it then sensitive data such as the `primary access key` for the current active storage accounts gets printed in clear text into the console. This is very critical if your CI/CD pipeline just performed the planning step but did not execute yet the plan as in our case sometimes a manual approval is required before we allow the execution of the plan. As the current active `primary access key` gets revealed anybody with access to the console logs is now able to infiltrate the storage account.

List of attributes that should be marked as sensitive to avoid this issue:

- primary_access_key
- primary_blob_connection_string
- primary_connection_string
- secondary_access_key
- secondary_blob_connection_string
- secondary_connection_string

### Steps to Reproduce

1. `terraform apply`
2. Change some attribute that causes an recreation of the storage account resource (e.g. changing the name)
3. `terraform plan`

**Comment by katbyte** [comment]
@subesokun,

Thanks again for noticing this 🙂 I looked for this problem in other resources and discovered over 20 other ones had similar issues 😅

I have just opened a PR (#1242) that will resolve all the ones I found in v1.6.0.

**Comment by katbyte** [comment]
Hey @OOPMichael,

Just wanted to let you know we have released [v1.6.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#160-may-24-2018) of the provider fixing this leakage of sensitive info.
