### ISSUE TITLE
context deadline exceeded during azurerm_private_dns_a_record refresh 

### ISSUE THREAD

**Issue by doherty100** [terraform-providers/terraform-provider-azurerm#12426]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_private_dns_a_record`

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_a_record" "private_dns_a_record_1" {
  name                = azurerm_storage_account.storage_account_01.name
  zone_name           = azurerm_private_dns_zone.private_dns_zone_1.name
  resource_group_name = azurerm_resource_group.resource_group_01.name
  ttl                 = 300
  records             = [azurerm_private_endpoint.storage_account_01_private_endpoint_file.private_service_connection[0].private_ip_address]
}
```

### Debug Output

https://gist.github.com/doherty100/3bffd411723eca19ed97c773385ee0de

### Expected Behaviour

Terraform refresh operation should complete successfully.

### Actual Behaviour

│ Error: shares.Client#GetProperties: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│
│   with azurerm_storage_share.storage_share_01,
│   on 40-storage.tf line 87, in resource "azurerm_storage_share" "storage_share_01":
│   87: resource "azurerm_storage_share" "storage_share_01" {

### Steps to Reproduce

1. `terraform apply`
2. `terraform refresh`

### Important Factoids

* Refresh operations only began failing recently

### References

* N/A

**Comment by patst** [comment]
Not sure if it is related:

 But we are seeing a lot of `context deadline exceeded` errors as well right now. It started an hour ago and different resources cannot be refreshed because of `HTTP/2.0 500 Internal Server Error` returned by the Azure REST endpoints.

So _maybe_ the error is not related to the resource.

**Comment by doherty100** [comment]
Closing this issue as it is miscategorized. I will open up another issue.
