### ISSUE TITLE
azurerm_kubernetes_cluster net_ipv4_ip_local_port_range_max allowed max value is incorrect

### ISSUE THREAD

**Issue by Ledermayer** [terraform-providers/terraform-provider-azurerm#12483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 1.0.1
azurerm. 2.66.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks_cluster" {
    default_node_pool {
        linux_os_config {
            sysctl_config {
              net_ipv4_ip_local_port_range_max  = 65000
            }
         }
     }
}
```

### Expected Behaviour

As per microsoft (and official kernel docs) the net.ipv4.ip_local_port_range maximum value is 65000 and not 60999, which is the top of the minimum value.

### Actual Behaviour

 Error: expected default_node_pool.0.linux_os_config.0.sysctl_config.0.net_ipv4_ip_local_port_range_max to be in the range (1024 - 60999), got 65000

### References

https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration

**Comment by katbyte** [comment]
closed by #12859
