### ISSUE TITLE
Terraform Script for SQL Server 2014 on Windows Server 2012 R2 Datacenter VM on Azure

### ISSUE THREAD

**Issue by siddthota** [terraform-providers/terraform-provider-azurerm#1248]
Hello,

I'm trying to spin-up a SQL Server 2014 SP2 Enterprise on Windows Server 2012 R2 using Terraform. 

I was not able to find required documentation/extension details for this.

I'm doing something like this 

```
module "ms-sql-vm" {
  source                                 = ".../terraform_module/windows_vm"
  vm_name                                = "ex-sql-vm"
  name_space                             = "${module.randomename}"
  arm_location                           = "centralus"
  vm_resource_group_name                 = "${module....}"
  availability_set_id                    = "${module....}"
  vm_network_interface_ids               = ["${module....}"]
  vm_size                                = "Standard_D2s_v3"
  vm_os_disk_name                        = "example-os-disk-${randomname}"
  vm_os_caching                          = "ReadWrite"
  vm_os_publisher                        = "MicrosoftSQLServer"
  vm_os_offer                            = "SQL2014SP2-WS2012R2"
  vm_os_sku                              = "Enterprise"
  vm_os_version                          = "12.10.0"
  vm_os_disk_size_gb                     = "127"
  vm_data_disk_name                      = "${module.....}"
  vm_data_disk_id                        = "${module.....}"
  vm_managed_disk_type                   = "Standard_LRS"
  vm_data_disk_size_gb                   = "${module.....}"
  vm_data_caching                        = "ReadWrite"
  vm_data_lun                            = 1
  vm_admin_name                          = "exampleusername"
  vm_admin_password                      = "Example12345!!"
  boot_diagnostics_primary_blob_endpoint = "${module......}"
  vm_delete_os_disk_on_termination       = true
  vm_delete_data_disk_on_termination     = true
}
```

This code is spinning just the Windows 2012 R2 Server, but not SQL Server as I was not able to find SQL Server Configuration option in my setting on VM Dashboard on Azure. 

Is there anyway I can spin up this instance using terraform?

I've explained more on this stackoverflow questions - https://stackoverflow.com/questions/50381871/terraform-script-for-sql-server-2014-on-windows-server-2012-r2-datacenter-vm-on

Thanks!

**Comment by jeffreyCline** [comment]
Closing per StackOverflow comment by @siddthota "I've figured it out. I need to add azure_vm_extension for this"

**Comment by siddthota** [comment]
Hello,

I've figured out how to add the extensions, but the SQL Server 2014 on Windows Server 2012 R2 Datacenter VM isn't spinning up. Even after adding the extension, I still don't see that SQL Server Configuration. 

Is there anyway, or anything that I need to do other than adding the extension to have that option?

**Comment by johnpaultthomas** [comment]
Hi
You need to make sure you are using the SQL image from Azure market place as your base image.Azure SQL extension cannot be used on an standalone widows server image. Also can you please share your terraform template I am trying to do the same with SQL server 2016 and WS 2016 in azure

**Comment by siddthota** [comment]
Hi,
I figured it out. They have SQL Image for Azure VM, but it still needs extension that spins up the SQL Server.

module "create-vm-extension" {
  source                            = "vm-config-above"
  vm_ext_name                       = "SqlIaasExtension"
  arm_location                      = "centralus"
  vm_ext_resource_group_name        = "resource-group-name"
  vm_ext_virtual_machine_name       = "vm-name"
  vm_ext_publisher                  = "Microsoft.SqlServer.Management"
  vm_ext_type                       = "SqlIaaSAgent"
  vm_ext_type_handler_version       = "1.2"
  vm_ext_auto_upgrade_minor_version = true

  vm_ext_settings = <<SETTINGS
  {
    "AutoTelemetrySettings": {
      "Region": "centralus"
    },
    "AutoPatchingSettings": {
      "PatchCategory": "WindowsMandatoryUpdates",
      "Enable": true,
      "DayOfWeek": "Sunday",
      "MaintenanceWindowStartingHour": "2",
      "MaintenanceWindowDuration": "60"
    },
    "KeyVaultCredentialSettings": {
      "Enable": false,
      "CredentialName": ""
    },
    "ServerConfigurationsManagementSettings": {
      "SQLConnectivityUpdateSettings": {
          "ConnectivityType": "Public",
          "Port": "1433"
      },
      "SQLWorkloadTypeUpdateSettings": {
          "SQLWorkloadType": "GENERAL"
      },
      "SQLStorageUpdateSettings": {
          "DiskCount": "1",
          "NumberOfColumns": "1",
          "StartingDeviceID": "2",
          "DiskConfigurationType": "NEW"
      },
      "AdditionalFeaturesServerConfigurations": {
          "IsRServicesEnabled": "true"
      }
    }
  }
  SETTINGS

  vm_ext_protected_settings = <<SETTINGS
  null
  SETTINGS
}

**Comment by johnpaultthomas** [comment]
Thank you Siddthartha

**Comment by stonefury** [comment]
@siddthota This is great, thank you.  Can someone help me find the documentation on the values for settings for SqlIaasExtension?  For example, where can I enter in a master username and password? I can't seem to find a full doc on all available options.
