### ISSUE TITLE
Low priority VM Scale Set support

### ISSUE THREAD

**Issue by CoRfr** [terraform-providers/terraform-provider-azurerm#1249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This feature is still in preview but it would be quite useful to have it supported in terraform.
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-low-priority

### New or Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine_scale_set" "scaleset" {
  name                = "autoscalewad"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  upgrade_policy_mode = "Manual"
  overprovision       = true
  depends_on          = ["azurerm_lb.lb", "azurerm_virtual_network.vnet"]
  priority            = "Low"
```

### References

* https://azure.microsoft.com/en-us/updates/public-preview-low-priority-vms-on-vm-scale-sets/
* https://github.com/ecalder6/azure-gaming/blob/master/LowPri.json

**Comment by katbyte** [comment]
Hey @CoRfr ,

Just wanted to let you know we have released [v1.6.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#160-may-24-2018) of the provider containing your PR for this issue 🙂
