### ISSUE TITLE
How to define content_format = application/json in Terraform file

### ISSUE THREAD

**Issue by ghariin** [terraform-providers/terraform-provider-azurerm#12519]
resource "azurerm_api_management" "API-Gateway" {
  name                = "apitspoc"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.RG.name
  publisher_name      = "xyz"
  publisher_email     = "xyz@abc.com"
  sku_name = "Developer_1"
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_api_management_api" "Api1" {
  name                = "name"
  resource_group_name = data.azurerm_resource_group.RG.name
  api_management_name = azurerm_api_management.API-Gateway.name
  revision            = "1"
  display_name        = "name"
  path                = ""
  protocols           = ["https", "http"]

  import {
    content_format = "swagger-json"
    content_value  = "url"
  }
}
azurerm_api_management_api.Api1: Creating...
╷
│ Error: creating/updating API Management API "name" (Resource Group "RGName"): apimanagement.APIClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Parsing error(s): Unexpected character encountered while parsing value: h. Path '', line 0, position 0.","target":"representation"}]
│
│   with azurerm_api_management_api.Api1,
│   on API.tf line 13, in resource "azurerm_api_management_api" "Api1":
│   13: resource "azurerm_api_management_api" "Api1" {

**Comment by manicminer** [comment]
Hi @ghariin, thanks for raising this issue. As the nature of what you are reporting is unclear, can I ask that you refile this issue using one of our issue templates and provide as much relevant information as possible? Thanks!
