### ISSUE TITLE
New Resource: Azure Monitor Signal

### ISSUE THREAD

**Issue by szinck1** [terraform-providers/terraform-provider-azurerm#1252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform supports creating metrics-based alerts with `azurerm_metric_alertrule` but I don't see any support for creating newer "signal" logic alerts.  For example, from the Azure Portal, I can create an alert to notify me on Slack when a new App Service state changes (start/stop etc).

More information on the new alerts:
https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview-unified-alerts

### New or Affected Resource(s)

A new resource for managing the the newer qalerts experience in Azure Monitor.

**Comment by JunyiYi** [comment]
Hi @szinck1 , your proposed resource has been released in `1.17.0`: https://www.terraform.io/docs/providers/azurerm/r/monitor_activity_log_alert.html. Please have a try and feel free to give us feedback.
