### ISSUE TITLE
Add Network Access Control support to Azure SignalR Service

### ISSUE THREAD

**Issue by pucciniplagiarist** [terraform-providers/terraform-provider-azurerm#12536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.31
AzureRM 2.66.0

### Affected Resource(s)

* `azurerm_signalr_service`

### Expected Behaviour

Within the Azure Portal it is possible to toggle public access to the Azure SignalR endpoint independently of whether a private endpoint exists.

Also it is possible to select connection types that are supported when connecting publicly and (independently) via an private endpoint.

This is important as public access is enabled by default.

### Actual Behaviour

As per https://github.com/terraform-providers/terraform-provider-azurerm/issues/8328 it is possible to add a private endpoint but it is not possible to switch off public access and it is not possible to configure the connection types.

### References

* https://docs.microsoft.com/en-us/azure/azure-signalr/howto-network-access-control
* #8328

**Comment by jayendranarumugam** [comment]
FYI: I already opened an issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/11777

**Comment by tombuildsstuff** [comment]
Fixed via #12434
