### ISSUE TITLE
docs: azurerm_api_management_diagnostic: sample has invalid casing

### ISSUE THREAD

**Issue by jwefers** [terraform-providers/terraform-provider-azurerm#12541]
On https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_diagnostic

it says
```
resource "azurerm_api_management_diagnostic" "example" {
   ...
   verbosity                 = "Verbose"
   ...
```

which is invalid, it must be lowercase `verbose`, which is also states as a valid value down below.

**Comment by krishrocks1904** [comment]
If you refer the documentation in terraform website they mentioned it as lowercase only 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_diagnostic#verbosity

**Comment by jwefers** [comment]
I know but if you copy paste the sample, you're gonna have a bad time
