### ISSUE TITLE
az disk-encryption-set cannot set auto-rotation to true  

### ISSUE THREAD

**Issue by tanvirahmed-deloitte** [terraform-providers/terraform-provider-azurerm#12559]
I was looking at the https://github.com/terraform-providers/terraform-provider-azurerm/pull/7913 changes.  But I do not see this being an option even in 2.59 version to set the auto-rotation to true. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Hi @tanvirahmed-deloitte, thanks for reporting this issue. It seems like you have not included any details with your bug report - unfortunately this is not enough information for us to be able to diagnose the problem you are experiencing. Can I ask you to re-submit your issue, adding relevant details such as your Terraform config, a description of your issue and any detailed output you get from Terraform? Thanks!
