### ISSUE TITLE
While using the count parameter, adding more VMs leads to deletion and recreation of existing network interfaces, subnet, Resource IDs. I am using terraform version 14 and Azurerm resource provider version 2.60

### ISSUE THREAD

**Issue by Kings-TF** [terraform-providers/terraform-provider-azurerm#12557]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment]
Hi @Kings-TF, thanks for reporting this issue. It seems like you have not included any information in your report apart from the title - unfortunately this is not enough information for us to be able to diagnose the problem you are having. Can I ask you to re-submit your issue, adding relevant details such as your Terraform config, a description of your issue and any detailed output you get from Terraform? Thanks!
