### ISSUE TITLE
Resource azurerm_cosmosdb_sql_user_defined_function is not working according to documentation

### ISSUE THREAD

**Issue by Nilsas** [terraform-providers/terraform-provider-azurerm#12564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Introduction

It seems that the resource `azurerm_cosmosdb_sql_user_defined_function` is not named correctly and is not recognized in AzureRM provider. Usability extends when I shorten the resource name to `azurerm_cosmosdb_sql_function` as it is referred to in the code.

### Terraform (and AzureRM Provider) Version

Terraform version: 0.14.8
AzureRM provider version: 2.58.0 / 2.66.0

### Affected Resource(s)

* `azurerm_cosmosdb_sql_user_defined_function`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_sql_user_defined_function" "example" {
  name         = "test-function"
  container_id = azurerm_cosmosdb_sql_container.example.id
  body         = "function trigger(){}"
}
```

### Expected Behaviour

Resource recognized and works properly

### Actual Behaviour

```bash
on ..\main.tf line 223, in resource "azurerm_cosmosdb_sql_user_defined_function" "example":
 223: resource "azurerm_cosmosdb_sql_user_defined_function" "example" {
The provider provider.azurerm does not support resource type
"azurerm_cosmosdb_sql_user_defined_function".
```

### Steps to Reproduce

1. Get the example code from [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_sql_user_defined_function)
1. Create necessary prerequisites (CosmosDB Account)
1. `terraform init`
1. `terraform apply`

### References

* #11537

**Comment by manicminer** [comment]
Thanks for reporting @Nilsas, this does appear to be a documentation bug.
