### ISSUE TITLE
Container registry change of SKU destroys and recreates 

### ISSUE THREAD

**Issue by twem** [terraform-providers/terraform-provider-azurerm#1256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
# terraform -v
Terraform v0.11.7
+ provider.azurerm v1.5.0
```

### Affected Resource(s)

* azurerm_container_registry

### Terraform Configuration Files

Create as SKU standard
```hcl
resource "azurerm_resource_group" "acr-rg" {
  name      = "${var.registry_name}-acr-rg"
  location  = "${var.location}"
}

resource "azurerm_container_registry" "acr" {
  name                = "${var.registry_name}acr"
  resource_group_name = "${azurerm_resource_group.acr-rg.name}"
  location            = "${azurerm_resource_group.acr-rg.location}"
  admin_enabled       = "false"
  sku                 = "Standard"
}
```
Update to SKU Premium
```hcl
resource "azurerm_resource_group" "acr-rg" {
  name      = "${var.registry_name}-acr-rg"
  location  = "${var.location}"
}

resource "azurerm_container_registry" "acr" {
  name                = "${var.registry_name}acr"
  resource_group_name = "${azurerm_resource_group.acr-rg.name}"
  location            = "${azurerm_resource_group.acr-rg.location}"
  admin_enabled       = "false"
  sku                 = "Premium"
}
```

### Debug Output

```

Terraform will perform the following actions:

-/+ azurerm_container_registry.acr (new resource required)
      id:                  "/subscriptions/xxxxx/resourceGroups/xxx-acr-rg/providers/Microsoft.ContainerRegistry/registries/xxxxacr" => <computed> (forces new resource)
      admin_enabled:       "false" => "false"
      admin_password:      "" => <computed>
      admin_username:      "" => <computed>
      location:            "uksouth" => "uksouth"
      login_server:        "xxxxacr.azurecr.io" => <computed>
      name:                "xxxxacr" => "xxxxacr"
      resource_group_name: "xxx-acr-rg" => "xxx-acr-rg"
      sku:                 "Standard" => "Premium" (forces new resource)
      tags.%:              "0" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.

```
### Expected Behavior

Update SKU from Standard to Premium
You are able to change up and down SKU's via the Azure portal

### Actual Behavior

Destroys the standard registry and creates a new premium registry.

### Steps to Reproduce

1. `terraform apply`
1. Update confirm from standard to premium
1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
Hey @twem ,

Just wanted to let you know we have released [v1.6.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#160-may-24-2018) of the provider fixing this issue 🙂
