### ISSUE TITLE
Support for "TypeMap with Elem *Resource" in Schema

### ISSUE THREAD

**Issue by sinbai** [terraform-providers/terraform-provider-azurerm#12561]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I intend to support the Automation Connection Type resource in Terraform Azure Provider, but when I wrote the code, I found that the format of the field "fieldDefinitions" was not supported in the schema. Is there any other way to replace it, or is there any plan to support this way?

Request Body In API:
<img width="232" alt="RequestBody" src="https://user-images.githubusercontent.com/39109137/125388485-2480f300-e3d2-11eb-915e-0f2ccc8c82e4.png">

Schema in Terraform Azure Provider:
<img width="349" alt="Schema" src="https://user-images.githubusercontent.com/39109137/125388493-2945a700-e3d2-11eb-8d59-5c2961500079.png">
			
Error:
<img width="582" alt="Error" src="https://user-images.githubusercontent.com/39109137/125388507-2ea2f180-e3d2-11eb-9c0c-c4598a077754.png">

### New or Affected Resource(s)

* New Resource: https://docs.microsoft.com/en-us/rest/api/automation/connection-type/create-or-update

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by manicminer** [comment]
Hi @sinbai, thanks for choosing to contribute to the AzureRM Provider and for your question. Typically we implement this sort of schema using blocks, although every scenario is unique and may warrant a different approach.

This issue tracker is primarily for reporting bugs and feature requests for the provider; whilst we often discuss implementation details for a pull request I believe you would get quicker advice from our development community on Slack. I encourage you to join, you can find an invite link in the [project README](https://github.com/terraform-providers/terraform-provider-azurerm#terraform-provider-for-azure-resource-manager). As this isn't the best forum, I'm going to close this issue for now but I look forward to seeing you on Slack if you choose to join. Thanks!

**Comment by sinbai** [comment]
Hi @manicminer, thank you for your reply. I have joined slack and raised this issue in development community on slack , but it has not yet been resolved. Regarding your reply, it is mentioned that this situation is implemented through blocks. Could you share how to write the schema in this case? Thank you very much!
