### ISSUE TITLE
Error: Cycle: azurerm_subnet_service_endpoint_storage_policy

### ISSUE THREAD

**Issue by manzurshaikh** [terraform-providers/terraform-provider-azurerm#12593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `2.65.0 & 2.58.0`

### Terraform Configuration Files

```
resource "azurerm_subnet_service_endpoint_storage_policy" "stg" {
  depends_on           = [module.vnet]
  name                = "storage-policy-bsai"
  resource_group_name = "${var.env}-bsai"
  location            = var.region
  definition {
    name        = "storage"
    #description = "definition1"
    service_resources = [
      module.resource_group.id,
      module.storage_bsai.id
    ]
  }
}

resource "azurerm_subnet" "backend" {
  depends_on           = [module.vnet]
  name                 = "backend"
  virtual_network_name = "${var.env}-${var.region}-bsai"
  resource_group_name  = "${var.env}-bsai"
  address_prefixes     = ["10.0.0.0/24"]
  service_endpoints = ["Microsoft.Storage", "Microsoft.AzureCosmosDB", "Microsoft.ServiceBus", "Microsoft.Web", "Microsoft.ContainerRegistry"]
  service_endpoint_policy_ids = azurerm_subnet_service_endpoint_storage_policy.stg.id

  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.Web/serverFarms"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

```

### Expected Behaviour

should attached azurerm_subnet_service_endpoint_storage_policy.stg to subnet

### Actual Behaviour

Error: Cycle: azurerm_subnet_service_endpoint_storage_policy.stg, azurerm_subnet.backend, module.storage_bsai.var.vnet_subnet_id (expand), module.storage_bsai.azurerm_storage_account.storageaccount_name, module.storage_bsai.output.id (expand)

### Steps to Reproduce

1. `terraform apply`

**Comment by jackofallops** [comment]
Hi @manzurshaikh - This appears that you have a cyclic dependency in your config? (i.e. where 2 or more resources depend on each other, meaning Terraform cannot reconcile what needs to happen in what order)

**Comment by krishrocks1904** [comment]
i think in the terraform documentation you can have one of more policies attached to subnet (its a list type attribute)
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#service_endpoint_policy_ids

can you please try that?

**Comment by krishrocks1904** [comment]
this is error you will get with above code.
Error: Incorrect attribute value type


  on main.tf line 41, in resource "azurerm_subnet" "backend":
  41:   service_endpoint_policy_ids = azurerm_subnet_service_endpoint_storage_policy.stg.id

Inappropriate value for attribute "service_endpoint_policy_ids": set of string
required.


--------------------------------------------------------------
here is the correct code and its working for me

`resource "azurerm_virtual_network" "example" {
  name                = "virtualNetwork1"
  location            = "West Europe"
  resource_group_name = "friday-demo-rg"
  address_space       = ["10.0.0.0/16"]
 
}

resource "azurerm_subnet" "backend" {
  name                 = "backend"
  virtual_network_name = azurerm_virtual_network.example.name
  resource_group_name  = "friday-demo-rg"
  address_prefixes     = ["10.0.0.0/24"]
  service_endpoints = ["Microsoft.Storage", "Microsoft.AzureCosmosDB", "Microsoft.ServiceBus", "Microsoft.Web", "Microsoft.ContainerRegistry"]
  service_endpoint_policy_ids = [azurerm_subnet_service_endpoint_storage_policy.stg.id]

  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.Web/serverFarms"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

data "azurerm_storage_account" "example" {
  name                = "learnadfst"
  resource_group_name = "friday-demo-rg"
}

resource "azurerm_subnet_service_endpoint_storage_policy" "stg" {
  name                = "storage-policy-bsai"
  resource_group_name = "friday-demo-rg"
  location            = "West Europe"
  definition {
    name        = "storage"
    service_resources = [
      data.azurerm_storage_account.example.id
    ]
  }
}`

here is the result
![image](https://user-images.githubusercontent.com/67486994/125920418-0c22c27f-7e7b-465a-b609-a0fea1c403f5.png)
