### ISSUE TITLE
"azurerm_synapse_role_assignment" is not accepting Principal_id of a service principal

### ISSUE THREAD

**Issue by asishr** [terraform-providers/terraform-provider-azurerm#12628]
### Terraform (and AzureRM Provider) Version

Terraform v 1.0.2
hashicorp/azurerm v2.68.0 

### Affected Resource(s)

* `azurerm_synapse_role_assignment `

### Debug Output

Error: creating Synapse RoleAssignment "Synapse User": accesscontrol.RoleAssignmentsClient#CreateRoleAssignment: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPrincipalId" Message="Invalid Principal Id '000000-0000-0000-0000-0000000000'."
│ 

### Expected Behaviour

Same response of Apply complete as when applied an User/Group principal id.

### Actual Behaviour

Error: creating Synapse RoleAssignment "Synapse User"

### Steps to Reproduce

run the example as is with static values. Tried applying both Application(Client_id) & Object_id  of the Service Principal as Principal_id 
```
provider "azurerm" {
  features {}
}
resource "azurerm_synapse_role_assignment" "example" {
  synapse_spark_pool_id = "/subscriptions/------------/resourceGroups/testsynapse_rg/providers/Microsoft.Synapse/workspaces/synapsstestws/bigDataPools/synapsesparkpo"
  role_name            = "Synapse User"
  principal_id         = "000000-0000-0000-0000-0000000000"

  # depends_on = [azurerm_synapse_firewall_rule.example]
} 
```
1. `terraform apply`

NOTE::: all the firewall rules were already applied, so for test purpose commented those out.

**Comment by manicminer** [comment]
Hi @asishr, thanks for reporting this. Can you confirm exactly from where you are sourcing the ID for the service principal?

**Comment by asishr** [comment]
@manicminer ::  i am manually copying the value from AAD through azure portal.

**Comment by manicminer** [comment]
We regularly test this resource with a service principal and it works on our CI platform. Are you sure you're copying the object ID of the service principal and not the object ID of the application? i.e. Azure Active Directory > Enterprise Applications > yourServicePrincipal and not Azure Active Directory > Applications > yourApplication

**Comment by asishr** [comment]
Thanks, Object_id from enterprise applications resolved it. I have been using the Applications Object_id.
