### ISSUE TITLE
Support for start/activation of Azure Data Factory blob event-based triggers

### ISSUE THREAD

**Issue by aristosvo** [terraform-providers/terraform-provider-azurerm#12621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to start/activate my triggers automatically based on a flag within the `azurerm_data_factory_trigger_blob_event` resource. Also, when I delete a trigger it should deactivate/stop the trigger as it blocks my deletion actions for now.

### New or Affected Resource(s)

* `azurerm_data_factory_trigger_blob_event`

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_trigger_blob_event" "test" {
   activated = true

   name                = "acctestdf%d"
   data_factory_id     = azurerm_data_factory.test.id
   storage_account_id  = azurerm_storage_account.test.id
   events              = ["Microsoft.Storage.BlobCreated", "Microsoft.Storage.BlobDeleted"]
   blob_path_ends_with = ".txt"
   ignore_empty_blobs  = true

   annotations = ["test1", "test2", "test3"]
   description = "test description"

   pipeline {
     name = azurerm_data_factory_pipeline.test.name
     parameters = {
       Env = "Test"
     }
   }

   additional_properties = {
     foo = "test1"
     bar = "test2"
   }
 }
```

### References

* #7574

### CC

- @njuCZ Did you leave this open on purpose (or to implement it as a separate resource)? Would you mind if I integrated it in this trigger as specified above?

**Comment by njuCZ** [comment]
@aristosvo sorry I missed this feature, please take this task as you would like.
