### ISSUE TITLE
Wrong documentation for azurerm_subscription resource

### ISSUE THREAD

**Issue by artyom-krot** [terraform-providers/terraform-provider-azurerm#12622]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription

Please update **Attributes Reference** part.
In addition to the Arguments listed, we can also get **subscription_id** argument

**Comment by manicminer** [comment]
Hi @artyom-krot, thanks for reporting. `subscription_id` is actually listed in the Arguments section, so it is not included in the Attributes section as we don't duplicate those.
