### ISSUE TITLE
Implement data block for azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by gfortil** [terraform-providers/terraform-provider-azurerm#12636]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There doesn't seem to be a data block for azurerm_linux_virtual_machine.

### New or Affected Resource(s)

* azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by manicminer** [comment]
Hi @gfortil, thanks for requesting this. It seems like you have not included any details with your request - unfortunately this is not enough information for us to be able to understand exactly what you are requesting. Can I ask you to re-submit your issue, adding relevant details such as your suggested/expected Terraform config, a description of the feature and any documentation links you have? Thanks!
