### ISSUE TITLE
dns_prefix argument is required for k8s cluster declarations, despite docs saying it's optional

### ISSUE THREAD

**Issue by ericpaulsen** [terraform-providers/terraform-provider-azurerm#12649]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform version `1.0.1`
- AzureRM provider version `2.46.0`

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "primary" {
  name                     = "${var.name}-cluster"
  location                 = azurerm_resource_group.primary.location
  resource_group_name      = azurerm_resource_group.primary.name
  http_application_routing {
      enabled = true
  }
  network_profile {
    network_policy           = var.network_policy
    network_plugin           = var.network_plugin
  }
```

### Debug Output

[GitHub Gist](https://gist.github.com/ericpaulsen/20f2f5ee60581975648c7e999fe298b2)

### Expected Behaviour

I left out the `dns_prefix` argument from my `azurerm_kubernetes_cluster` resource declaration, since the documentation said it is optional.

### Actual Behaviour

Since my code did not include the `dns_prefix` argument, it threw a `Missing required argument` error. It should not have thrown such an error, as the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#dns_prefix) says it is optional. Either the documentation is incorrect, or there is an issue with the argument itself.

### Steps to Reproduce

1. `terraform apply` or `terraform validate`

### References

Relevant AzureRM provider [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#dns_prefix)

**Comment by manicminer** [comment]
Hi @ericpaulsen, thanks for reporting this. In the `azurerm_kubernetes_cluster` resource, either one of the `dns_prefix` or `dns_prefix_private_cluster` properties must be set. You are correct that this is missing from the documentation - due to the way Terraform schema works, these properties are individually optional but together comprise a required argument, this is most likely the reason for the omission.

**Comment by ericpaulsen** [comment]
Understood. Thank you for clarifying. I look forward to seeing the docs updated accordingly.
