### ISSUE TITLE
Support for downgrade AKS sku_tier without recreate

### ISSUE THREAD

**Issue by tjololo** [terraform-providers/terraform-provider-azurerm#12643]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently downgrading fra Paid sku_tier to Free forces recreation of the AKS-cluster.
Enforced by this [code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/2552105474de549733a0f93901df666763074e3c/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L44-L47):
```go
			// Downgrade from Paid to Free is not supported and requires rebuild to apply
			pluginsdk.ForceNewIfChange("sku_tier", func(ctx context.Context, old, new, meta interface{}) bool {
				return new == "Free"
			}),
```

Also this is also adressed in comments [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/2552105474de549733a0f93901df666763074e3c/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L660-L664)
Checking with wayback machine this was true ref: [wayback aks uptime sla](https://web.archive.org/web/20210202085007/https://docs.microsoft.com/en-us/azure/aks/uptime-sla). 
AKS now supports downgrade from Paid to Free ref: [aks uptime sla](https://docs.microsoft.com/en-us/azure/aks/uptime-sla).

Could the force new if changed for sku_tier Paid -> Free be removed to support downgrading sku_tier without recreation?

I would be happy to create a pull request on this issue

### New or Affected Resource(s)

* [azurerm_kubernetes_cluster](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster)

### Potential Terraform Configuration

There would be no changes to the terraform configuration only the sync/plan/apply logic

**Comment by aristosvo** [comment]
I'll look into it tonight!

**Comment by tjololo** [comment]
Thanks @aristosvo and @tombuildsstuff for looking into, fixing, approving, merging, closing and releasing the issue all within four days!
