### ISSUE TITLE
Support for IDPS in azurerm_firewall_policy

### ISSUE THREAD

**Issue by bandarr** [terraform-providers/terraform-provider-azurerm#12655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_firewall_policy currently supports threat_intelligence_mode.   It should also support  idps_mode or similarly named for IDPS.   

### New or Affected Resource(s)

* azurerm_firewall_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_firewall_policy" "example" {
    name                = "example"
    resource_group_name = "example"
    location            = "West Europe"
    threat_intelligence_mode = "Deny"
    idps_mode = "Deny"
}
```
### References

* #0000

**Comment by gro1m** [comment]
@bandarr This overlaps with my issue here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/11438. Of course the company I work for would need it for URL Filtering. But I guess it would make sense to try to cover all Premium features. Unfortunately I am not quite sure yet what would be the `Potential Terraform Configuration`, which I am discussing with @favoretti also with respect to feasibility. So if you have any inputs there that would be great. As far as my understanding goes this should be _somehow_ possible, but I am still much too unclear about how much the Azure Go SDK supports this already and on how to implement.
