### ISSUE TITLE
Support for terraform_remote_state with RBAC instead of SAS-token

### ISSUE THREAD

**Issue by kevinharing** [terraform-providers/terraform-provider-azurerm#12679]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Due to policy I need to disable Shared Key Access on my Azure Storage Account. Remote state management should thus go through Azure AD with RBAC. I have assigned the correct roles, authenticate via the correct Service Principal, but I get back the following error:

``
Error: Failed to get existing workspaces: containers.Client#ListBlobs: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account.
``

I tried adding 'use_azuread_auth = true', but this is only supported for user accounts and not Service Principals. Am I overlooking something?

In the link referenced below there's another person with the same problem.

### New or Affected Resource(s)

* terraform_remote_state

### References

* https://discuss.hashicorp.com/t/why-does-the-azurerm-backend-not-support-storage-use-azuread/20571

**Comment by kevinharing** [comment]
I’m not at my machine right now, but this is probably the setting I’m looking for, right?

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread

**Comment by aristosvo** [comment]
I thought configuration of remote state is done from Terraform Core, so the change might be out of scope of the provider.

Authentication for remote state in Azure Storage is separate from authentication towards your resources.

**Comment by kevinharing** [comment]
I’m not sure. Just wanted to let you know that storage_use_azuread works!

**Comment by aecom-billhammond** [comment]
This doesn't seem to be an option for backend config - the storage_use_azuread seems to only be for the provider configuration. I have the exact same issue with security requirements, and the backend is first grabbing the MSI token and then using it to try to get the shared keys and using those to access the blob, and shared key access has been disabled account wide for security concerns.

**Comment by aecom-billhammond** [comment]
If you have any code examples of an azurerm blob storage backend that works with only MSI and shared key access disabled please share it if possible.
Thanks

**Comment by aecom-billhammond** [comment]
The fix actually seems to be adding use_azuread_auth=true to the backend config.

**Comment by kevinharing** [comment]
> The fix actually seems to be adding use_azuread_auth=true to the backend config.

For user accounts it is indeed (local development). For CI/CD and SPN I used storage_use_azuread (not this actual setting but the environment variable).
