### ISSUE TITLE
multitenant azurerm not respecting provider alias

### ISSUE THREAD

**Issue by sseppola** [terraform-providers/terraform-provider-azurerm#12688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.68.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Working on upgrading terraform to 0.15, then 1.0

### Affected Resource(s)

Confirmed with:
* `azurerm_role_assignment`
* `azurerm_role_definition`
* `azurerm_resource_group`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "= 0.14.11"

  backend "azurerm" {
    resource_group_name  = "rg-hidden"
    storage_account_name = "sthidden"
    container_name       = "terraformstate"
    key                  = "terraform-azurerm-test-tfstate"
  }

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.68.0"
    }
  }
}


provider "azurerm" {
  subscription_id = var.subscription
  tenant_id       = var.main_tenant_id

  features {}
}

provider "azurerm" {
  alias           = "b2c"
  subscription_id = var.subscription
  tenant_id       = var.b2c_tenant_id

  features {}
}

resource "azurerm_resource_group" "test-azurerm" {
  name     = "rg-test-azurerm"
  location = var.location
}
resource "azurerm_resource_group" "test-azurerm-b2c" {
  provider = azurerm.b2c
  name     = "rg-test-azurerm-b2c"
  location = var.location
}
```

### Debug Output
```log
azurerm_resource_group.test-azurerm-b2c: Creating...
azurerm_resource_group.test-azurerm: Creating...
azurerm_resource_group.test-azurerm: Creation complete after 1s [id=/subscriptions/[SUBSCRIPTION_ID]/resourceGroups/rg-test-azurerm]
azurerm_resource_group.test-azurerm-b2c: Creation complete after 2s [id=/subscriptions/[SUBSCRIPTION_ID]/resourceGroups/rg-test-azurerm-b2c]
```

### Panic Output
N/A

### Expected Behaviour
Expected the resource groups to be created in separate tenants

### Actual Behaviour
Resource groups are created in the same tenant (default)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The backend is configured to use a storage account from the main tenant, ARM_ACCESS_KEY is provided via an environment variable.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @sseppola 

Thanks for opening this issue.

From what I've seen of the Azure API the relationship between a Tenant and a Subscription is a 1:many - such that one Tenant may have many Subscriptions but one Subscription can only have one Tenant. Whilst Azure allows different service principals (from different tenants) to have access to the subscription, any resources are provisioned within the subscription and not the tenant (and the Resource ID's being returned here include the Subscription ID for this reason). As such I believe this is working as intended, can you provide some more information here?

Thanks!

**Comment by sseppola** [comment]
I think you're right, this is probably not a azurerm problem, but rather a problem in Azure.
Thanks for helping me understand.

For context:
We have a separate directory/tenant for AAD B2C, however, somehow it doesn't have a subscription associated with it (I cannot create resource groups in the portal). That said, when I go to my subscriptions I only have a single subscription (same across both directories). This conflicts with the diagram here: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory, in that either the directory has 0 subscriptions, or the subscription has 2 directories. I have no idea how it got to this state.

I can add that the `azuread` provider is able to manage resources in both directories, however azurerm is not.
