### ISSUE TITLE
Delete managed OS disk when destroying VM

### ISSUE THREAD

**Issue by cehoffman** [terraform-providers/terraform-provider-azurerm#127]
Given an `azurerm_virtual_machine` using a managed OS disk is created then destroyed. The same configuration can not be reused because the managed OS disk resource still exists. When a VM is destroyed and has a managed OS disk, the OS disk should be destroyed too to prevent leaking of resources.

Data disks have the problem too, but it can be mitigated using the `azurerm_managed_disk` resource separately and linking to that created instance in the `storage_data_disk` block. The OS block can not do this due to `azurerm_managed_disk` not supporting creation `FromImage`.

**Comment by DWSR** [comment]
I can confirm this behaviour +1

**Comment by StephenWeatherford** [comment]
Have you tried https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#delete_os_disk_on_termination?

**Comment by cehoffman** [comment]
Huh, I'll have to give that a try. Thought I had read over all the flags, but apparently that one didn't stick in my head. Will report back once I get to try it.

**Comment by StephenWeatherford** [comment]
Is there a way we can improve the documentation so that you would have found this more easily?  Thx.

**Comment by cehoffman** [comment]
Only suggestion I have is to include it in one of the examples. Overall the examples are so good you don't usually need to look much at the detailed options to get going.

**Comment by cehoffman** [comment]
This works as advertised.

**Comment by StephenWeatherford** [comment]
To summarize - the behavior noted is by design.  If users want to have the OS or data disks deleted with the VM, they can use the delete_{os,data}_disk{,s}_on_termination flags.

Looking into whether the docs can make this easier to find.

**Comment by tombuildsstuff** [comment]
Associated PR: #139
