### ISSUE TITLE
Cannot create storage account in AzureChinaCloud

### ISSUE THREAD

**Issue by woozar** [terraform-providers/terraform-provider-azurerm#12717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 1.0.0.
Azure RM: 2.69.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    # the config will be set during "terraform init"
  }
 
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.69.0"
    }
  }
}
 
provider "azurerm" {
  skip_provider_registration = true
  features {}
  subscription_id = var.subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id
  environment     = "china"
}
 
resource "azurerm_resource_group" "default" {
  name     = var.resource_group
  location = "China East 2"
  tags     = var.tags
}
 
resource "azurerm_storage_account" "manufacturingui" {
  name                     = "saourstoragecne2"
  resource_group_name      = azurerm_resource_group.default.name
  location                 = azurerm_resource_group.default.location
  account_tier             = "Standard"
  account_replication_type = "ZRS"
  allow_blob_public_access = true
 
  static_website {
    error_404_document = "404.html"
    index_document     = "index.html"
  }
 
  tags = var.tags
}

```

### Debug Output

Due to regulations regarding our chinese cloud, I cannot provide debug output, but only the error message.

Error: Error creating Azure Storage Account "saourstoragecne2": storage.AccountsClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="LocationNotValid" Message="Supplied location chinaeast2 is not valid."

### Expected Behaviour

Create a resource group and a storage account in azure china

### Actual Behaviour

Creation of resoruce group is working but creation of storage account returns the error posted above.

### Steps to Reproduce

1. ```terraform init -no-color \
 -backend-config="subscription_id=$SUBSCRIPTION_ID" \
 -backend-config="tenant_id=$TENANT" \
 -backend-config="resource_group_name=$STATE_RESOURCE_GROUP" \
 -backend-config="storage_account_name=$STATE_ACCOUNT_NAME" \
 -backend-config="container_name=$STATE_CONTAINER" \
 -backend-config="environment=china" \
 -backend-config="key=cne2.tfstate"```

2. ```# we need to execute some az cli commands, so we need to log in with az cli anyways. Doing it before terraform should not be an issue.
az cloud set --name AzureChinaCloud
az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT"
az account set --subscription="$SUBSCRIPTION_ID"```

3. `terraform apply`

### Important Factoids

Running in Azure China

**Comment by tombuildsstuff** [comment]
hi @woozar 

Thanks for opening this issue.

Taking a look through here it appears [that Storage Accounts are supported in Azure China in China East 2](https://azure.microsoft.com/en-us/global-infrastructure/services/?regions=china-non-regional,china-east,china-east-2,china-north,china-north-2&products=storage) - since this error is coming from the Azure API rather than Terraform, I'd recommend reaching out to Microsoft Support who should be able to investigate this further.

Thanks!

**Comment by woozar** [comment]
It was caused by account_replication_type = "ZRS" which is not available in china east 2. After changing it to "LRS", it is working properly. The returned error message was pretty confusing, but I believe it is coming from azure, so there is probably not much, you can do about it.
