### ISSUE TITLE
Terraform plan showing changes when there are no change

### ISSUE THREAD

**Issue by satsmur** [terraform-providers/terraform-provider-azurerm#12732]
**Community Note**
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Terraform (and AzureRM Provider) Version**
Terraform v1.0.3
provider.azurerm v2.63.0

**Affected Resource(s)**
Affected resources so far are,
azurerm_kubernetes_cluster
azurerm_role_assignment

**Description**
Terraform Configuration Files

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.prefix}-k8s"
  location            = azurerm_resource_group.fro.location
  resource_group_name = azurerm_resource_group.fro.name
  dns_prefix          = "${var.prefix}-k8s"
  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed = true
      admin_group_object_ids = [
        var.adadmingroup
      ]
    }
resource "azurerm_role_assignment" "kub_to_acr" {
  scope                = azurerm_container_registry.acr.id
  role_definition_name = "AcrPull"
  principal_id         = azurerm_kubernetes_cluster.k8s.kubelet_identity[0].object_id
}
resource "azurerm_role_assignment" "kub_keyvault_Secrets" {
  scope                = azurerm_key_vault.keyvault.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_kubernetes_cluster.k8s.kubelet_identity[0].object_id
}
resource "azurerm_role_assignment" "kub_keyvault_Certificates" {
  scope                = azurerm_key_vault.keyvault.id
  role_definition_name = "Key Vault Certificates Officer"
  principal_id         = azurerm_kubernetes_cluster.k8s.kubelet_identity[0].object_id
}

**Expected Behavior**
Terraform plan should detect no changes

**Actual Behavior**
Initially, I have created AKS cluster and all resources created successfully. However, later on terraform plan shows changes even though i havent made any changes in the code.
If I do Terraform apply, it is completely destroys the resources and creating again.

**Steps to Reproduce**
terraform plan

**Comment by tombuildsstuff** [comment]
hi @satsmur 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by satsmur** [comment]
Hi @tombuildsstuff 

Thanks for your response.
I already looked into suggested forum however there is no luck. this issue should be reopened and labelled not as a question. Please let me know if more info/output/code should be added.

**Comment by tombuildsstuff** [comment]
@satsmur as mentioned above unfortunately this forum is only for bugs or feature requests in the Azure Provider - since this is a usage question/issue, those are instead supported [on the community discuss forum](https://discuss.hashicorp.com).
