### ISSUE TITLE
create_option parameter of azurerm_virtual_machine_data_disk_attachment resource with Empty value doesn't work as expected

### ISSUE THREAD

**Issue by madhavidhurve** [terraform-providers/terraform-provider-azurerm#12758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.0
AzureRM Provider v2.63.0

### Affected Resource(s)

* `azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

We have used the same example as documented in Terraform document version 2.63.0
https://registry.terraform.io/providers/hashicorp/azurerm/2.63.0/docs/resources/virtual_machine_data_disk_attachment
**Note** : We have done changes in **azurerm_virtual_machine_data_disk_attachment** resource wherein we had added only
**create_option ="Empty"**
```
variable "prefix" {
  default = "example"
}
```
```

locals {
  vm_name = "${var.prefix}-vm"
}

resource "azurerm_resource_group" "main" {
  name     = "${var.prefix}-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "main" {
  name                = "${var.prefix}-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_subnet" "internal" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "main" {
  name                = "${var.prefix}-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.internal.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_virtual_machine" "example" {
  name                  = local.vm_name
  location              = azurerm_resource_group.main.location
  resource_group_name   = azurerm_resource_group.main.name
  network_interface_ids = [azurerm_network_interface.main.id]
  vm_size               = "Standard_F2"

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }

  storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = local.vm_name
    admin_username = "testadmin"
    admin_password = "Password1234!"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
}

resource "azurerm_managed_disk" "example" {
  name                 = "${local.vm_name}-disk1"
  location             = azurerm_resource_group.main.location
  resource_group_name  = azurerm_resource_group.main.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "example" {
  managed_disk_id    = azurerm_managed_disk.example.id
  virtual_machine_id = azurerm_virtual_machine.example.id
  lun                = "10"
  caching            = "ReadWrite"
  create_option      = "Empty"
}
```
### Expected Behaviour
With terraform apply the resource should get created successfully i.e. **Empty managed disk** should get attached to Virtual machine

### Actual Behaviour
With **create_option = "Empty" in azurerm_virtual_machine_data_disk_attachment** its throwing error as 
**Message="Disk example-vm-disk1 already exists in resource group example-resource. Only CreateOption.Attach is supported."**

### Steps to Reproduce

1. Set **create_option** parameter of **azurerm_virtual_machine_data_disk_attachment** resource to "**Empty**" value.
2. Then perform terraform apply.

Please let us know, where exactly is the issue and what is the usage of **Empty value in create_option parameter of azurerm_virtual_machine_data_disk_attachment** resource

**Comment by tombuildsstuff** [comment]
hi @madhavidhurve 

Thanks for opening this issue.

Taking a look through this appears to be a configuration question rather than a bug in the Azure Provider - as per the API Response it should be possible to set this field to `Attach` to attach the new disk being created above which should fix this.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
