### ISSUE TITLE
Support for AKS HTTP Application Routing

### ISSUE THREAD

**Issue by rlucioni** [terraform-providers/terraform-provider-azurerm#1276]
The [HTTP Application Routing](https://docs.microsoft.com/en-us/azure/aks/http-application-routing) add-on can be enabled through the Azure portal when deploying an AKS cluster. It would be great if enabling this was an option when creating new `azurerm_kubernetes_cluster` resources (e.g., via a Boolean argument like `enable_http_application_routing`).

**Comment by tombuildsstuff** [comment]
hey @rlucioni 

Thanks for opening this issue :)

We took a look into this recently and this is available in the new version of the AKS API - however there's no matching Swagger for that at this time. @dcaro was following up internally about getting this available - once that's done and a new version of [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) is available - we can take a look at support this.

Thanks!

**Comment by rlucioni** [comment]
Great, thanks @tombuildsstuff. Looking forward to seeing this supported.

**Comment by tombuildsstuff** [comment]
To provide an update here, the Swagger for this has been merged: https://github.com/Azure/azure-rest-api-specs/pull/3131

**Comment by lfshr** [comment]
Not quite as simple as the boolean. This is an AddonProfile. - Related to #1434

@mb290 nodeResourceGroup addition is a much simpler one. @tombuildsstuff I can bundle up the nodeResourceGroup with #1479 if you like, it's a relatively small change.

**Comment by lfshr** [comment]
@tombuildsstuff this functionality is provided by addonProfiles. I think we should move this alongside #1434

**Comment by tombuildsstuff** [comment]
@lfshr 👍 closing this in favour of #1434
