### ISSUE TITLE
Support for public or private AKS creation based on condition

### ISSUE THREAD

**Issue by DesislavaNPetrova** [terraform-providers/terraform-provider-azurerm#12805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.65.0"
    }
  }
  required_version = ">= 0.13"
}
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                            = var.kubernetes_cluster_name
  kubernetes_version              = var.kubernetes_version
  api_server_authorized_ip_ranges = var.private_cluster_enabled == false ? var.api_server_authorized_ip_ranges == [] ? null : var.api_server_authorized_ip_ranges : null
  enable_pod_security_policy      = var.enable_pod_security_policy
  private_cluster_enabled         = var.private_cluster_enabled
  node_resource_group             = var.node_resource_group
}

module "azure_aks_cluster" {
  private_cluster_enabled                  = var.private_cluster_enabled
  api_server_authorized_ip_ranges          = var.api_server_authorized_ip_ranges
}

variable "api_server_authorized_ip_ranges" {
  description = "(Optional) The IP ranges to whitelist for incoming traffic to the masters."
  type        = list
  default     = []
}
  
variable "private_cluster_enabled" {
  description = "(Optional)"
  default     = true
}
```

### Actual Behaviour
```hcl
Error: creating Managed Kubernetes Cluster "k8s" (Resource Group "k8s"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="Private cluster cannot be enabled with AuthorizedIPRanges."
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @DesislavaNPetrova 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by DesislavaNPetrova** [comment]
@tombuildsstuff This is a bug, where to open it?

**Comment by Cyanopus** [comment]
@tombuildsstuff This is causing a single resource to not be able to be used as a public or private cluster. You should be able to do conditional and set it null so it won't interfere with private cluster= true setup instead the moment the api_server_authorized_ip_ranges is added although it's not configured you get an immediate error.
