### ISSUE TITLE
cannot create nsg with source_address_prefixes

### ISSUE THREAD

**Issue by eladmotola** [terraform-providers/terraform-provider-azurerm#12802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform 1.0.1
azurerm - 2.65.0

### Affected Resource(s)

* `azurerm_network_security_group`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "nsg" {
  name                = "name"
  location            = var.location
  resource_group_name = var.rg_name

  dynamic "security_rule" {
    for_each = var.security_groups_list

    content {
      name                   = security_rule.key
      priority               = security_rule.value.priority
      direction              = "Inbound"
      access                 = "Allow"
      protocol               = security_rule.value.protocol
      source_port_range      = "*"
      destination_port_range = security_rule.value.port
      source_address_prefixes    = []  # or even with value like ["0.0.0.0"] 
      destination_address_prefix = "*"
    }
  }
}
```

### Actual Behaviour

```
Error: Error creating/updating NSG "name" (Resource Group "rgname"): network.SecurityGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="SecurityRuleParametersMissing" Message="Required security rule parameters are missing for security rule with Id: /longid . Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups." Details=[]

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @eladmotola 

Taking a look at the error coming back from the Azure API here, it appears that one the `destination_port_range` field must have a value:

> Required security rule parameters are missing for security rule with Id: /longid . Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups.

.. but that one is missing for the rule `/longid` - as such adding a value for this field (rather than an empty array) should fix this.

Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment, but if you have further usage questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
