### ISSUE TITLE
Support for azurerm_monitor_action_rule_action_group suppression

### ISSUE THREAD

**Issue by MattGarner-N** [terraform-providers/terraform-provider-azurerm#12807]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support Alert Suppression functionality within Azure Action Rules.

### New or Affected Resource(s)

* azurerm_monitor_action_rule_action_group

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_action_rule_action_group" "example" {
  name                = "example-amar"
  resource_group_name = azurerm_resource_group.example.name
  action_group_id     = azurerm_monitor_action_group.example.id

  type = "Suppression"

  suppression_config {
    recurrence_type = "Daily"
    schedule = {
      start_date = "12/09/2018"
      end_date = "12/18/2018"
      start_time = "06:00:00"
      end_time = "14:00:00"
    }
  }

  scope {
    type         = "ResourceGroup"
    resource_ids = [azurerm_resource_group.example.id]
  }

  tags = {
    foo = "bar"
  }
}
```

### References

Action Rule REST API showing Suppression:

https://docs.microsoft.com/en-us/rest/api/monitor/alertsmanagement/action-rules/create-update#actionrule

More info here:

https://docs.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-action-rules?tabs=portal

* #0000

**Comment by teowa** [comment]
There is another resource support `Action Rules` suppression, see [azurerm_monitor_action_rule_suppression](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_action_rule_suppression).

**Comment by mybayern1974** [comment]
@MattGarner-N , I'm closing this issue by assuming this feature request has been supported per teowa's comments above, or feel free to suggest to reopen this issue if you found this feature is still not supported yet.
