### ISSUE TITLE
Need support OWASP 3.2 for azurerm_application_gateway

### ISSUE THREAD

**Issue by alex-3sr** [terraform-providers/terraform-provider-azurerm#12821]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi all,

for Azure Application Gateway, the rule set version 3.2 is available, but this value is not accepted in terraform azurerm_application_gateway ressources. When using 3.2, we have this error ->
**Error: expected waf_configuration.0.rule_set_version to be one of [0.1 1.0 2.2.9 3.0 3.1], got 3.2**

### New or Affected Resource(s)

* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "waf" {
....
waf_configuration {
      enabled            = true
      firewall_mode      = "Detection"
      rule_set_type      = "OWASP"
      rule_set_version   = "3.2"
  }
...
}
```

Thanks
Alex

**Comment by favoretti** [comment]
HI there and thank you for reporting this. When I look at the code, version `3.2` is supported as of 7th of April 2021. Which version of the provider you're using?

**Comment by alex-3sr** [comment]
> HI there and thank you for reporting this. When I look at the code, version `3.2` is supported as of 7th of April 2021. Which version of the provider you're using?

Hi ;)

Thanks for your quick reply. I don't use latest, you're right ->
```
Terraform v1.0.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
```

I'm upgrading, and will try again

Thanks
Alex

**Comment by alex-3sr** [comment]
OK sorry, it was an outdated provider, it was static in required_providers config, so that's why init -upgrade did'nt help me.
It's ok now ;) and thank you for take time to reply me.

Regards
Alex
