### ISSUE TITLE
panic in services/privatedns.resourcePrivateDnsZoneDelete

### ISSUE THREAD

**Issue by jhyot** [terraform-providers/terraform-provider-azurerm#12837]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

When deleting:

* `azurerm_private_dns_zone`

### Panic Output

https://gist.github.com/jhyot/0a07b61189d8956d344857115c95468f

### Expected Behaviour

The resource is deleted

### Actual Behaviour

panic

### Steps to Reproduce

Try to delete a private_dns_zone resource by removing it from the config and running `terraform apply`

### Important Factoids

It might be relevant that the Private DNS Zone where I tested this still had a virtual network link defined, and consequently I wasn't able to delete the DNS Zone manually via Azure Portal either. Only after I removed the vnet link, I was able to delete the Zone manually. I didn't test at that moment whether the deletion via Terraform would have worked or not.

**Comment by tombuildsstuff** [comment]
Fixed via #12824
