### ISSUE TITLE
Error: context deadline exceeded while creating kubernetes_persistent_volume_claim

### ISSUE THREAD

**Issue by paleti5** [terraform-providers/terraform-provider-azurerm#12841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform version
Terraform v0.13.4
+ provider registry.terraform.io/gavinbunney/kubectl v1.11.2
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
### Affected Resource(s)

* `kubernetes_persistent_volume_claim`

### Terraform Configuration Files

```hcl
variable "spark_namespace" {
  type        = string
  description = "Namespace to create for spark and associated storage to be hosted in"
  default = "test"
}
# Creates Spark & associated storage namespace
resource "kubernetes_namespace" "sparkns" {
  metadata {
    name = var.spark_namespace
  }
}
resource "kubernetes_persistent_volume" "datalake" {
  metadata {
    name = "pv-data-lake"
  }
  spec {
    capacity = {
      storage = "800Gi"
    }
    access_modes                     = ["ReadWriteMany"]
    persistent_volume_reclaim_policy = "Retain"
    mount_options = [
      "-o allow_other",
      "--file-cache-timeout-in-seconds=120"
    ]
    persistent_volume_source {
      csi {
        driver        = "blob.csi.azure.com"
        read_only     = false
        volume_handle = "unique-volumeid"
        volume_attributes = {
          resource_group  = var.datalake_resource_group_name
          storage_account = var.target_datalake
          container_name  = "fiona"
        }
        node_stage_secret_ref {
          name      = "az-dl-connection"
          namespace = kubernetes_namespace.sparkns.metadata[0].name
        }
      }
    }
  }
}

resource "kubernetes_persistent_volume_claim" "spark_pvc_dl" {
  metadata {
    name = "pvc-data-lake"
    namespace = kubernetes_namespace.sparkns.metadata[0].name
  }
  spec {
    access_modes = ["ReadWriteMany"]
    resources {
      requests = {
        storage = "10Gi"
      }
    }
    volume_name = kubernetes_persistent_volume.datalake.metadata[0].name
  }
}

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @paleti5 

Thanks for opening this issue.

Taking a look through this appears to be related to the Kubernetes Provider rather than the AzureRM Provider - as such [would you mind reopening this on the Kubernetes Provider repository](https://github.com/hashicorp/terraform-provider-kubernetes)?

Thanks!
