### ISSUE TITLE
Lock off "internalFQDN" field when executing "TestAccAzureRMNetworkInterface_internalFQDN" test.

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#1289]
Automation has broken with the following error.

**TestAccAzureRMNetworkInterface_internalFQDN**: testing.go:513: Step 0 error: Check failed: Check 2/2 error: azurerm_network_interface.test: Attribute 'internal_fqdn' expected "acctestnic-6584041529954921755.example.com", got "".
**It might because api don't return "internalFQDN" field anymore.**
[https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/get](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/get)

### Terraform Version

- Terraform v0.11.8-dev

- provider.azurerm v1.5.0

### Affected Resource(s)
network_interface

**Comment by tombuildsstuff** [comment]
hey @lrxtom2 

Thanks for opening this issue :)

The field `internalFQDN` is part of the API, however it may not necessarily be being returned from the API - here's a reference from the documentation:

<img width="779" alt="screen shot 2018-05-24 at 10 23 28" src="https://user-images.githubusercontent.com/666005/40476668-849e4abc-5f3c-11e8-87c9-c4779559aa6d.png">

In general we don't open issues for failing tests (we instead favouring fixing the issues when we pass through that resource) - as such I'm going to close this issue for the moment.

Thanks!

**Comment by metacpp** [comment]
@lrxtom2 can you provide a PR to fix the testing issue?

**Comment by lrxtom2** [comment]
@tombuildsstuff 
Hi Tom,
Azure Rest-Api will not return this “internal_fqdn” field. So it always return empty string. But it’s required in our documents https://www.terraform.io/docs/providers/azurerm/d/network_interface.html
I think it's a bug to fix.
Thanks,
Chang

**Comment by tombuildsstuff** [comment]
@lrxtom2 since this exists in the API documentation and isn't documented as deprecated, that's a bug in the Azure API. Would you be able to file a bug on [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go/issues) about that field not being returned from the API (since it's in the SDK)?

Thanks!
