### ISSUE TITLE
Azure NetApp Files - Resource Type Not Found

### ISSUE THREAD

**Issue by Lachlan-White** [terraform-providers/terraform-provider-azurerm#12894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v1.0.4
* azurerm v2.71.0

### Affected Resource(s)

* azurerm_netapp_account
* azurerm_netapp_pool

### Terraform Configuration Files

```hcl
resource "azurerm_netapp_account" "example" {
  name                = "example-netapp"
  resource_group_name = "rg-netapp-example"
  location            = "australiaeast"
}
 ```

### Expected Behaviour

* Ability to provision NetApp Account / NetApp resources

### Actual Behaviour

Receive the following error:
`Error: Error creating NetApp Account "netapp-sap-sandbox" (Resource Group "rg-database-sap"): netapp.AccountsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidResourceType" Message="The resource type could not be found in the namespace 'Microsoft.NetApp' for api version '2020-09-01'."`

![image](https://user-images.githubusercontent.com/41881046/128623591-4e82116a-6534-4fd1-9073-f27305f27bbe.png)
### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hey @Lachlan-White 

Thanks for opening this issue.

Taking a look at the response from the Azure API here:

```
{
      "apiVersions": [
        "2021-06-01",
        "2021-04-01",
        "2021-02-01",
        "2020-12-01",
        "2020-11-01",
        "2020-10-01",
        "2020-09-01",
        "2020-08-01",
        "2020-07-01",
        "2020-06-01",
        "2020-05-01",
        "2020-03-01",
        "2020-02-01",
        "2019-11-01",
        "2019-10-01",
        "2019-08-01",
        "2019-07-01",
        "2019-06-01",
        "2019-05-01",
        "2017-08-15"
      ],
      "capabilities": "SystemAssignedResourceIdentity, SupportsTags, SupportsLocation",
      "locations": [
        "Australia Central",
        "Australia East",
        "Australia Southeast",
        "Brazil South",
        "Canada Central",
        "Canada East",
        "Central India",
        "Central US",
        "East US",
        "East US 2",
        "France Central",
        "Germany North",
        "Germany West Central",
        "Japan East",
        "Japan West",
        "Korea Central",
        "North Europe",
        "Norway East",
        "Norway West",
        "South Central US",
        "South India",
        "Southeast Asia",
        "UAE North",
        "UAE Central",
        "UK South",
        "UK West",
        "West Europe",
        "West US",
        "West US 2"
      ],
      "resourceType": "netAppAccounts"
    },
```

which you can get by running `az rest --method GET --uri "https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.NetApp?api-version=2020-09-01` - it appears this is supported, but [based on the "register now" button on this page](https://azure.microsoft.com/en-us/services/netapp/), access to NetApp Files may be gated on a per-subscription basis? Would you be able to show the output of that command to confirm that?

Thanks!

**Comment by Lachlan-White** [comment]
Thanks Tom, you got me on this one, for sure needs a per subscription registration to enable the API that Terraform touches.

I might have to raise a PR for the docs to include this to save others!

Feel free to close the Issue!

**Comment by tombuildsstuff** [comment]
@Lachlan-White that's a good point this is missing from the docs, if you get a chance that'd be a great inclusion 👍
