### ISSUE TITLE
r/mssql_server: support for `azuread_only_authentication`

### ISSUE THREAD

**Issue by ulankford** [terraform-providers/terraform-provider-azurerm#12965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to also set to 'True' or 'False' the ability to set Azure AD Only Authentication (azureADOnlyAuthentications) as part of this resource?
https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/azureadonlyauthentications?tabs=bicep

It's great that one can set an AD Administrator as the first step to enable Azure AD Single Sign-On, but there doesn't seem to be a way to enable AD Only Authentication, apart from the GUI, or using the Azure CLI

### New or Affected Resource(s)

* azurerm_sql_active_directory_administrator

### Potential Terraform Configuration

```
resource "azurerm_sql_active_directory_administrator" "adadmin" {
  server_name         = azurerm_mssql_server.sqlServer.name
  resource_group_name = azurerm_resource_group.rg.name
  login               = "sqladmin"
  tenant_id           = data.azurerm_client_config.current1.tenant_id
  object_id           = data.azurerm_client_config.current1.object_id

  ad_only_auth    = "true"
}

```

### References

* #0001 https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/azureadonlyauthentications?tabs=bicep

**Comment by ajklotz** [comment]
This might be something you should set at the azurerm_mssql_server resource instead of azurerm_sql_active_directory_administrator - just a suggestion if this gets implemented
