### ISSUE TITLE
Feature Request: Attach azurerm_application_insights to a azurerm_app_service

### ISSUE THREAD

**Issue by test-in-prod** [terraform-providers/terraform-provider-azurerm#1303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Greetings, this is just a feature request to enable attachment of a azurerm_application_insights to a azurerm_app_service.

Right now, this can only be done via the portal (or assuming also via Azure ARM template) by going to an App Service -> Application Insights, then creating or selecting an existing resource. After this, I see it creates APPINSIGHTS_* environment variables (app settings) and also a peculiar "hidden" tag on the target application insights resource with a value `"hidden-link:/subscriptions/<subscription id>/resourceGroups/<rg name>/providers/Microsoft.Web/sites/<site name>": "Resource"`

I tried to replicate this via terraform, however it does not appear to be working even though the resulting exported ARM template is exactly the same as one generated manually via Azure Portal.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @CryptonZylog 

Thanks for opening this issue :)

Would it be possible to show the Terraform Configuration that you've attempted to use? From what I can see above it should be possible to set a tag on the `azurerm_application_insights` resource for:

```
resource "azurerm_application_insights" "test" {
  tags {
    "hidden-link:/subscriptions/<subscription id>/resourceGroups/<rg name>/providers/Microsoft.Web/sites/<site name>": "Resource"
  }
}
```

Thanks!

**Comment by CryptonZylog** [comment]
Actually, you got it. That's what I've tried anyway (setting that tag).

**Comment by Phydeauxman** [comment]
I am not sure I understand what the Terraform integration of App Insights is buying us right now. I have created an AI instance and stored its key as an output. When I create an App I want to attach to the AI instance, I add the `app_settings` section like below:
```
  app_settings {
    "APPINSIGHTS_INSTRUMENTATIONKEY" = "${data.terraform_remote_state.rg.app_insights_key}"
    "APPINSIGHTS_JAVASCRIPT_ENABLED" = true
  }

```
These two settings get added to my app but I am not sure what the first one even does because I still have to go into the portal, select Web App > Application Insights and enable it by selecting the recently created AI instance that was created by Terraform. When I do this, I do not see any additional app settings on the Web App. Where would I go to see the hidden tag mentioned above?

**Comment by tombuildsstuff** [comment]
@Phydeauxman unfortunately the hidden tag needs to be applied on the `azurerm_application_insights` resource from that to whatever Application Insights should be connected too (e.g. a Web App) - which isn't really a great UX. That said - it should be possible using that approach alone (rather than having to go into the portal).

I've requested that Microsoft investigate adding an API for attaching/detaching Application Insights to things rather than use tags - so it's possible to make this attachment independently; but I'm unsure of the status of that feature request, unfortunately.

**Comment by Phydeauxman** [comment]
@tombuildsstuff so, I would use the property below under my `azurerm_application_insights` resource?
```
resource "azurerm_application_insights" "test" {
  tags {
    "hidden-link:/subscriptions/<subscription id>/resourceGroups/<rg name>/providers/Microsoft.Web/sites/<site name>": "Resource"
  }
}
```
I am assuming I can use variables in that `hidden-link` string...right?

**Comment by CyanMass45** [comment]
So I've just completed a project where we are doing this using terraform. The way I accomplish this is as below:

resource "azurerm_application_insights" "webappai" {
  name                = "$webappname-wa-ai"
  location            = "North Europe"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  application_type    = "Web"
}

output "webapp_key" {
  value = "${azurerm_application_insights.webappai.instrumentation_key}"
}

output "webapp_id" {
  value = "${azurerm_application_insights.webappai.app_id}"
}

# Create Webapp
resource "azurerm_app_service" "webapp" {
  name                = "webappname-wa"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  app_service_plan_id = "${azurerm_app_service_plan.webappsp.id}"
  https_only = "true"

  site_config {
    dotnet_framework_version = "v4.0"
    scm_type                 = "None"
    always_on                 = "true"
    use_32_bit_worker_process = "true"
    default_documents = [
    "Default.htm",
    ]
  }

  app_settings {
    "APPINSIGHTS_INSTRUMENTATIONKEY" = "${azurerm_application_insights.webappai.instrumentation_key}"
    "APPINSIGHTS_PORTALINFO" = "ASP.NET"
    "APPINSIGHTS_PROFILERFEATURE_VERSION" = "1.0.0"
    "DIAGNOSTICS_AZUREBLOBCONTAINERSASURL" = "${var.logstore}"
    "DIAGNOSTICS_AZUREBLOBRETENTIONINDAYS" = "35"
    "WEBSITE_HTTPLOGGING_RETENTION_DAYS" = "35"
  }

  depends_on = [
      "azurerm_app_service_plan.webappsp",
      "azurerm_application_insights.webappai"
      ]
}

The only catch in above is "${var.logstore}" needs to be specified before. I do this by means of a copied connection string of a previously working App Insights. Also, the above does not install the Application Insights extension for the app (webapp) so I take care of this after using a local-exec powershell script.

Hope this helps?

**Comment by drdamour** [comment]
did they ever come back with an api for this?  the docs are still having you modify everything with app settings, seems like most the gui is a thin layer on top of that https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps#automate-monitoring

would it fit in terraform to have the options in their own stanza, but in the end they just end up being appsettings? or is that a no-no cause it would cause conflicts with app settings

**Comment by drdamour** [comment]
@test-in-prod where did you see that hidden tag? in resource explorer?

**Comment by drdamour** [comment]
i might be missing it, but i don't see that tag anymore. maybe they stopped using it.  It appears the only thing that triggers the Portal GUI to show app insights is needed is if the app has various settings on the slot.  Here's what i ended up doc'ing

```
    # Note: per https://github.com/terraform-providers/terraform-provider-azurerm/issues/1440 terraform has no direct control of making these deployment slot settings or not, but luckily the default is
    # to mark them as deployment slot and that's what we want for these. see https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#which-settings-are-swapped as to why

    # This is a master setting that links the app to the monitor. It also controls the Azure Portals GUI to show insights options in app services.
    "APPINSIGHTS_INSTRUMENTATIONKEY" = azurerm_application_insights.<your insight name>.instrumentation_key

    # This is another master setting. Insights works behind the scenes as a https://www.siteextensions.net/ which just transform the IIS config or the most part
    # it apparently started as an extension and they turned it into a first class gui concept, but behind the scenes it's still an extension, however it does
    # not appear as an extension in your sites extension list.
    # the possible values appear to be ~2 and disabled (though one day someone shoud try ~1 for fun).
    "ApplicationInsightsAgent_EXTENSION_VERSION" = "~2"

    # values are default or recommended. for .net core default is actually disabled and insights will get no data. recommedned starts tracking basic stuff.
    "XDT_MicrosoftApplicationInsights_Mode"= "recommended"

    # There are 3 functions we can turn on for insights beyond basic monitoring in .net
    # Profiler - Collect profiling traces that help you see where time is spent in code. - https://go.microsoft.com/fwlink/?linkid=869613
    # Snapshot Debugger - Collect call stacks for your application when an exception is thrown. (w/ option to turn on local variables) - https://go.microsoft.com/fwlink/?linkid=869614
    # SQL Commands - Enable dependency tracking to show compiled SQL command and local variables in a web request.
    #
    # Depending on what you want on you need to flip sets of various values. Some collide, each are doc'd below.


    # values are disabled or 1.0.0
    # must be 1.0.0 to enable the profiler
    "APPINSIGHTS_PROFILERFEATURE_VERSION" = "1.0.0"

    # values are disabled or ~3
    # must be ~3 to enable the profiler or snapshot debugger
    "DiagnosticServices_EXTENSION_VERSION" = "~3"

    # values are disabled or 1.0.0
    # must be 1.0.0 to enable Snapshot Debugger
    "APPINSIGHTS_SNAPSHOTFEATURE_VERSION" = "1.0.0"

    # values are disabled or ~1
    # must be ~1 to enable local variables in snapshot debugger
    "SnapshotDebugger_EXTENSION_VERSION" = "~1"

    # values are disabled or ~1
    # must be ~1 to enable SQL Commands or local variables in snapshot debugger
    "InstrumentationEngine_EXTENSION_VERSION" = "~1"

    # values are disabled or ~1
    # must be ~1 forto enable SQL Commands
    "XDT_MicrosoftApplicationInsights_BaseExtensions" = "~1"
```

**Comment by phekmat** [comment]
> 
> 
> did they ever come back with an api for this? the docs are still having you modify everything with app settings, seems like most the gui is a thin layer on top of that https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps#automate-monitoring
> 
> would it fit in terraform to have the options in their own stanza, but in the end they just end up being appsettings? or is that a no-no cause it would cause conflicts with app settings

fwiw, this is similar to how the log configuration settings work. The app settings generated by the API are ignored by the provider (though I'm not sure if there's a separate API yet for app insights).

**Comment by Marcus-James-Adams** [comment]
with MS now contributing to the azurerm provider is there any plan to resolve this issue.
it seems to be common amongst a number of resources now that you can create the resource, create the application insights but can't link them togeather.

**Comment by sonic1981** [comment]
Not sure if this has changed in the Ms side but it now seems to add a app_settings when you enable App insights, something along the lines of:

```
"APPLICATIONINSIGHTS_CONNECTION_STRING"      = "InstrumentationKey=<guid>;IngestionEndpoint=https://uksouth-0.in.applicationinsights.azure.com/
```

**Comment by sonic1981** [comment]
So it seems setting this value hooks up app insights correctly now. This is what I did:

```
APPINSIGHTS_INSTRUMENTATIONKEY  = var.appinsight.instrumentation_key
    APPLICATIONINSIGHTS_CONNECTION_STRING         = "InstrumentationKey=${azurerm_application_insights.appinsight.instrumentation_key};IngestionEndpoint=https://${azurerm_resource_group.rg.location}-0.in.applicationinsights.azure.com/"
    WEBSITE_RUN_FROM_PACKAGE                      = ""
    FUNCTIONS_WORKER_RUNTIME                      = "dotnet"
    "ApplicationInsightsAgent_EXTENSION_VERSION"  = "~2"
```
not too sure about the `IngestionEndpoint` bit but ti seems to work for now...

**Comment by joaocpribeiro** [comment]
@sonic1981 Your solution helped me, but the ingestion endpoint is "-1" for me (westeurope). I do not know where this number comes from.

**Comment by jackofallops** [comment]
Closing as appears to be resolved by 8699 but wasn't linked successfully to this issue.

**Comment by drdamour** [comment]
@jackofallops  isn't this request for more native support, IE an app_insights attribute or more likely block within app_service?  so we do NOT have to hack through the property namings? in such a case this should stay open i'd think

**Comment by Marcus-James-Adams** [comment]
I agree
This needs to be fully integrated as config

**Comment by AdamCoulterOz** [comment]
@drdamour / @Marcus-James-Adams / @bkaid  - if that's what you want then go tell Microsoft, it is them, not the resource provider who implement connecting the connection in this way (using app settings). Terraform's Azure provider just follows the Azure APIs. The change made to resolve this to make it nicer is the following:

What used to be this:

```terraform
resource "azurerm_app_service" "example" {

    # ....

    app_settings {
        APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.appinsight.instrumentation_key
        APPLICATIONINSIGHTS_CONNECTION_STRING = "InstrumentationKey=${azurerm_application_insights.appinsight.instrumentation_key};IngestionEndpoint=https://${azurerm_resource_group.rg.location}-0.in.applicationinsights.azure.com/"
    }
}
```

is now this:

```terraform
resource "azurerm_app_service" "example" {

    # ....

    app_settings {
        APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.appinsight.instrumentation_key
        APPLICATIONINSIGHTS_CONNECTION_STRING = azurerm_application_insights.appinsight.connection_string
    }
}
```

Which imo is much better than it was, and is exactly native.

**Comment by CyanMass45** [comment]
Attaching application insights to a webapp works as expected using the app settings for instrumentation key and connection string.

Oddly though for function apps the same approach does not work. When attached using the portal it adds a hidden tag to the app insights resource.

Running terraform removes the hidden tag, therefore disconnecting the two, so I've tried adding the tag to the app insights resource code using the ID output from the function app. 

This however causes a race condition in terraform as the function app needs the app insights resource to get the instrumentation key and connection string, and the app insights resource now needs the function app for the app ID, and terraform can't cope with this.

**Comment by drdamour** [comment]
@CyanMass45 whats the tag

**Comment by CyanMass45** [comment]
> @CyanMass45 whats the tag
@drdamour 

"hidden-link:/subscriptions/<subscription id>/resourceGroups/<rg name>/providers/Microsoft.Web/sites/<site name>": "Resource"

**Comment by AdamCoulterOz** [comment]
does the hidden tag actually break it? I don't think it does... and it would seem to create a circular dependency if you were to make it yourself... my way around it is to deterministically calculate what the resource_id _will be_ after the other side is created and create the hidden-link tag using terraform also, then it won't remove it next time you apply it. Again, this is a circular dependency introduced by Microsoft and not the terraform providers fault.

**Comment by drdamour** [comment]
> @drdamour / @Marcus-James-Adams / @bkaid - if that's what you want then go tell Microsoft, it is them, not the resource provider who implement connecting the connection in this way (using app settings). Terraform's Azure provider just follows the Azure APIs. The change made to resolve this to make it nicer is the following:
> 
> What used to be this:
> 
> ```terraform
> resource "azurerm_app_service" "example" {
> 
>     # ....
> 
>     app_settings {
>         APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.appinsight.instrumentation_key
>         APPLICATIONINSIGHTS_CONNECTION_STRING = "InstrumentationKey=${azurerm_application_insights.appinsight.instrumentation_key};IngestionEndpoint=https://${azurerm_resource_group.rg.location}-0.in.applicationinsights.azure.com/"
>     }
> }
> ```
> 
> is now this:
> 
> ```terraform
> resource "azurerm_app_service" "example" {
> 
>     # ....
> 
>     app_settings {
>         APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.appinsight.instrumentation_key
>         APPLICATIONINSIGHTS_CONNECTION_STRING = azurerm_application_insights.appinsight.connection_string
>     }
> }
> ```
> 
> Which imo is much better than it was, and is exactly native.

i didn't realize that terraform azurerm provide was against making these types of abstractions.  consider me learned.  

this issue which is over 2 years old wasn't just about this connectionstring property which just showed up recently so the closure reason seemed not to be compatible with the request.

> I've requested that Microsoft investigate adding an API for attaching/detaching Application Insights to things rather than use tags - so it's possible to make this attachment independently; but I'm unsure of the status of that feature request,

given that thought the request was already in progress.

**Comment by nickstw** [comment]
> does the hidden tag actually break it? I don't think it does... and it would seem to create a circular dependency if you were to make it yourself... my way around it is to deterministically calculate what the resource_id _will be_ after the other side is created and create the hidden-link tag using terraform also, then it won't remove it next time you apply it. Again, this is a circular dependency introduced by Microsoft and not the terraform providers fault.

So is there a way to get Application Insights and a Function App to attach using Terraform?

**Comment by BradAF** [comment]
@nickstw 
> So is there a way to get Application Insights and a Function App to attach using Terraform?

I got it to work by doing the following to avoid the 'cycle':

1. Define the function name in a local variable
2. Configure APPINSIGHTS_INSTRUMENTATIONKEY and APPLICATIONINSIGHTS_CONNECTION_STRING in the function apps app_settings

Example snippet:
 `
locals` {
  function_app_name     = "func-${local.system_name}-${var.environment}"
}

resource "azurerm_function_app" "func01" {
...
  app_settings = {   
    APPINSIGHTS_INSTRUMENTATIONKEY               = azurerm_application_insights.ai01.instrumentation_key
    APPLICATIONINSIGHTS_CONNECTION_STRING = azurerm_application_insights.ai01.connection_string
  }
}

resource "azurerm_application_insights" "ai01" {
 ...
  tags = {
    "hidden-link:/subscriptions/${data.azurerm_subscription.current.subscription_id}/resourceGroups/${azurerm_resource_group.all.name}/providers/Microsoft.Web/sites/${local.function_app_name}" = "Resource"
  }

}`

**Comment by CyanMass45** [comment]
Weirdly, the "APPLICATIONINSIGHTS_CONNECTION_STRING" seems to change at random as well. I just had a plan throw out changes to my function apps with below:

      ~ app_settings                   = {
            "APPINSIGHTS_INSTRUMENTATIONKEY"                  = "XXXXXXX-5f3a-42ef-8b29-491a06346fd0"
          ~ "APPLICATIONINSIGHTS_CONNECTION_STRING"           = "InstrumentationKey=XXXXXXX-5f3a-42ef-8b29-491a06346fd0;IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/" -> "InstrumentationKey=XXXXXXX-1cd1-4b39-959b-7ac66c968455;IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/"

Seems like there is a lot of unpredictable behaviour with this still. I might just add an ignore_changes section instead.
