### ISSUE TITLE
Cannot set empty boot diagnostic URL for scale set

### ISSUE THREAD

**Issue by bpoland** [terraform-providers/terraform-provider-azurerm#1310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Terraform Configuration Files

This is the relevant portion inside my scale set.  When the azure_bootdiag_storage_account variable has an empty value, and azure_bootdiag_enabled is false, the problem happens.
```hcl
   boot_diagnostics {
        enabled = "${var.azure_bootdiag_enabled}"
        storage_uri = "${var.azure_bootdiag_storage_account}"
    }
```

### Expected Behavior

Terraform should have sent a boot diagnostics block with enabled = false and no URL, the same way it does for a standard virtual machine.

### Actual Behavior

Terraform sends a diagnostics block with enabled = false and the blank URL, which causes Azure to reject the request.

### Steps to Reproduce

Set a boot diagnostics block in your scale set with enabled = false and an empty storage URL, then apply.

### References

I notice the standard virtual machine has a check in there to not set the storage_uri when enabled = false: https://github.com/terraform-providers/terraform-provider-azurerm/blob/9ab3f72a96f864596a6711aac1168c12e31ccc5c/azurerm/resource_arm_virtual_machine.go#L927

But the scale set does not have this check: https://github.com/terraform-providers/terraform-provider-azurerm/blob/9ab3f72a96f864596a6711aac1168c12e31ccc5c/azurerm/resource_arm_virtual_machine_scale_set.go#L1016

Perhaps it would be as simple as bringing that check over from virtual machine to the scale set?

**Comment by JunyiYi** [comment]
This issue is duplicated with #1167 . We may use that one to track the progress.

**Comment by tombuildsstuff** [comment]
Closing this in favour of #1167 - please subscribe to that issue for updates
