### ISSUE TITLE
Feature Request: resource azurerm_automation_variable

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#1312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Variable assets are values that are available to all runbooks and DSC configurations in your automation account.

It will be usefull if they can be created, modified, and retrieved from Terraform.

### New or Affected Resource(s)

* Affected resource : azurerm_automation_account
* New Automation resource : azurerm_automation_variable
* New Data resource : azurerm_automation_variable

### Potential Terraform Configuration

1. Automation resource : azurerm_automation_variable
```hcl
resource "azurerm_automation_variable" "auto_variable" {
  name                = "myvariable"
  resource_group_name = "myautoaccount_rgname"
  account_name        = "myautoaccount_rgname"
  value               = "myvalue"
  encrypted           = true
  description         = "mydescription"
}
```

2. Data resource : azurerm_automation_variable
```hcl
data "azurerm_automation_variable" "auto_variable" {
  name      = "myvariable"
  azurerm_automation_account_id = "/subscriptions/xxx-subscription_id-xxx/resourceGroups/my_rg_name/providers/Microsoft.Automation/automationAccounts/my_auto_account_name"
}

output "auto_variable" {
  value = "${data.azurerm_automation_variable.auto_variable.value}"
}
```

### References
[Vendor blog post or documentation](https://docs.microsoft.com/en-us/azure/automation/automation-variables)

**Comment by JunyiYi** [comment]
Hi @JamesDLD , thanks for using terraform and creating this feature request. I would like to implement them and please allow me to track the progress here:

[ ] Implements new resource `azurerm_automation_variable`
[ ] Implements new data-source `azurerm_automation_variable`

**Comment by laughtonsm** [comment]
Any news on this guys?  Just wondering when this feature is going to be included in the provider

**Comment by odee30** [comment]
This feature would be really useful..  Any ideas what version of the provider this will be released with?

**Comment by jeffreyCline** [comment]
> Any news on this guys? Just wondering when this feature is going to be included in the provider

> This feature would be really useful..  Any ideas what version of the provider this will be released with?

Sorry for the delay in replying @laughtonsm and @odee30... Yes I do, this will be in **v1.28.0** of the provider which should be shipping very soon.

**Comment by odee30** [comment]
Thanks @jeffreyCline .  Good news.  Really appreciate the update.

**Comment by laughtonsm** [comment]
Great stuff. Thanks for the update!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
