### ISSUE TITLE
Support for `zone_redundant` in `azurerm_app_service_plan`

### ISSUE THREAD

**Issue by shibayan** [terraform-providers/terraform-provider-azurerm#13144]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Now that the App Service (not ASE) supports zone redundancy, I want to create an App Service Plan that also supports zone redundancy in Terraform.

### New or Affected Resource(s)

* azurerm_app_service_plan

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "api-rg-pro"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "example" {
  name                = "api-appserviceplan-pro"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  zone_redundant      = true

  sku {
    tier = "PremiumV3"
    size = "P1v3"
  }
}
```

### References

* https://azure.github.io/AppService/2021/08/25/App-service-support-for-availability-zones.html

**Comment by phatcher** [comment]
I notice that this doesn't support the `capacity` value mentioned in the [blog article](https://azure.github.io/AppService/2021/08/25/App-service-support-for-availability-zones.html)
