### ISSUE TITLE
Storage account kind documentation 

### ISSUE THREAD

**Issue by franciscocabral** [terraform-providers/terraform-provider-azurerm#1316]
The documentation don't mention StorageV2 kind. I needed to go through the issues/prs and the code to know how to use StorageV2 as a kind for my storage account.

In the [docs](https://www.terraform.io/docs/providers/azurerm/d/storage_account.html#account_kind) we have 

>account_kind - Defines the Kind of account, either BlobStorage or Storage.

Where is missing the StorageV2 option.

**Comment by katbyte** [comment]
Hi @franciscocabral,

Thank you for noticing this. As this is a datasource we typically don't list all possible values. I have pushed through a PR to make the documentation more consistent with other datasources.
