### ISSUE TITLE
Add outbound_ip_addresses export to azurerm_app_service_slot 

### ISSUE THREAD

**Issue by perbergland** [terraform-providers/terraform-provider-azurerm#1317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_app_service_slot share many of the properties of azurerm_app_service.
One such export property that is currently missing is outbound_ip_addresses which can be used to set up firewall entries for resources like SQL server.

### New or Affected Resource(s)

* azurerm_app_service_slot 

### Potential Terraform Configuration

```hcl
locals {
  warmup_outbound_ips      = "${sort(split(",",azurerm_app_service_slot.warmup.outbound_ip_addresses))}"
}
```

### References

* #700 
* #1268

**Comment by tombuildsstuff** [comment]
hey @perbergland 

Thanks for opening this issue :)

From what I understand, the IP Addresses for an App Service Slot will be the same as the IP Addresses for an App Service - as such whilst we can add support for this; are you seeing a difference between the two?

Thanks!

**Comment by perbergland** [comment]
Yeah well once I found out by experience that the outbound addresses change periodically and can take on any ip from that location (unless you cough up a lot of dough for [ASE](https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-intro)) the value of this output degraded significantly :(
But thanks for the swift reply

**Comment by perbergland** [comment]
Hmmm maybe I was wrong - it does seem like the list of IP addresses given is static within a tier:
https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-addresses#find-outbound-ips

regardless, if the slot has the same IP addresses as the app_service then that is enough.
