### ISSUE TITLE
Feature Request:  Support enhanced key usage (eku) for keyvault certificate creation

### ISSUE THREAD

**Issue by dubeaud** [terraform-providers/terraform-provider-azurerm#1319]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a new certificate with the azurerm_keyvault_certificate we would like to specify enhanced key usage (eku) properties for the certificate.  

### New or Affected Resource(s)

* azurerm_key_vault_certificate

### References

* https://docs.microsoft.com/en-us/rest/api/keyvault/createcertificate/createcertificate#x509certificateproperties

**Comment by draggeta** [comment]
I've created the PR mentioned above to fix this issue. There are still some things I'm not sure about so any critique is welcome.
