### ISSUE TITLE
azurerm_application_gateway request_routing_rule missing redirection configuration 

### ISSUE THREAD

**Issue by robsonpeixoto** [terraform-providers/terraform-provider-azurerm#1326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a feature to configure redirection from a Listener to another Listener. Really useful to implement redirect from http to https

### New or Affected Resource(s)

* azurerm_application_gateway.*.request_routing_rule

### Potential Terraform Configuration

```hcl
...
  request_routing_rule {
    name                 = "http-to-https-rule"
    rule_type            = "Basic"
    redirect             = true
    from_listener        = "http-listener"
    configure_redirect   = true
    redirect_type        = "Permanent"          # options: ["Permanent", "Temporary", "Found", "SeeOther"]
    target_listener      = "https-listener"
    include_query_string = true
    include_path         = true
  }
...
```

### References

https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-http-redirect-powershell

**Comment by tombuildsstuff** [comment]
hey @robsonpeixoto 

Thanks for opening this issue :)

Support for this has previously been requested in https://github.com/terraform-providers/terraform-provider-azurerm/issues/552 which I'm going to close this issue in favour of. Unfortunately at the moment we're blocked on a bug in the Application Gateway API which needs to be fixed before we extend this resource (but is apparently being deployed in the near future; there's additional details in the other issue)

Thanks!
