### ISSUE TITLE
Feature Request: Split key vault access policy

### ISSUE THREAD

**Issue by yzhang-myob** [terraform-providers/terraform-provider-azurerm#1330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Split Azure key vault to separate resource. E.g. azurerm_key_vault_access_policy. I have a user case where a function app is depended on a Key Vault. However, I need to grant key vault access through function managed service identity (currently done through resource template). In this situation, the current key vault config will cause circular dependency. 

### New or Affected Resource(s)

* azurerm_key_vault
* azurerm_key_vault_access_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_access_policy" "test" {
    key_vault_id = ""
    tenant_id = "${local.tenant_id}"
    object_id = "${local.object_id}"

    key_permissions    = []
    secret_permissions = ["get", "list"]
}
```

**Comment by tombuildsstuff** [comment]
hey @yzhang-myob 

Thanks for opening this feature request :)

Support for splitting this out has been requested previously in https://github.com/terraform-providers/terraform-provider-azurerm/issues/754 which will be fixed by #1149 - as such I'm going to close this issue in favour of #754.

Thanks1
