### ISSUE TITLE
Relax naming requirements of app_service_plan

### ISSUE THREAD

**Issue by phekmat** [terraform-providers/terraform-provider-azurerm#1336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azurerm_app_service_plan` uses a more strict naming convention than the API (notably, `_` is not allowed in terraform, but is via the API and ARM templates). We have app service plans with an `_` in the name, so this is a blocker when it comes to using this resource. 

### New or Affected Resource(s)

* azurerm_app_service_plan

**Comment by katbyte** [comment]
Hey @phekmat,

1.7 that was released today and it should allow for underscores in the `azurerm_app_service_plan` name.
