### ISSUE TITLE
Add a "data" class for importing existing AAD principals

### ISSUE THREAD

**Issue by perbergland** [terraform-providers/terraform-provider-azurerm#1338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is quite common to want to assign roles to existing azure applications that have unique AD principal ids in each tenant but where the name is well known.
It would be very nice if the Azure provider could provide a data class for importing these well-known principals so that they can be used in the azurerm_role_assignment resource.

### New or Affected Resource(s)

* azurerm_service_principal

### Potential Terraform Configuration

```hcl
data "azurerm_service_principal" "test" {
    name = "Backup Management Service"
}

resource "azurerm_role_assignment" "test" {
  scope                = "${data.azurerm_subscription.primary.id}"
  role_definition_name = "Reader"
  principal_id         = "${data.azurerm_service_principal.test.id}"
}
```

**Comment by perbergland** [comment]
The corresponding Powershell AzureRM cmdlet is called Get-AzureRmADServicePrincipal.

`Get-AzureRmADServicePrincipal -SearchString "Backup Management Service" `

**Comment by tombuildsstuff** [comment]
hey @perbergland 

Thanks for opening this issue :)

Based on [this comment](https://github.com/Azure/azure-powershell/issues/1165) - I believe this should be partially resolved by https://github.com/terraform-providers/terraform-provider-azurerm/pull/1349. Once this exists, we should be able to provide a helper Data Source similar to [`azurerm_builtin_role_definition`](https://www.terraform.io/docs/providers/azurerm/d/builtin_role_definition.html) which exposes this information.

Thanks!

**Comment by perbergland** [comment]
Yeah well what I *really* want is an AzureAD terraform provider so I can move away from a hybrid setup where I first create AD groups through powershell and create an ad.auto.tfvars file that terraform picks up and then finally run more powershell to add principals creates by terraform to appropriate AD groups. I don't think #1349 achieves this since what I'm after are the AD object ids for AD items like groups.
A specific example is to set the admin ad for a sql server to an existing AD group, and instead of having to look up the AD object id before terraform have some terraform provider do that work as part of the run.

**Comment by perbergland** [comment]
The corresponding cmdlet in AzureRM Powershell for my example would be Get-AzureRmADGroup.

**Comment by perbergland** [comment]
This seems to be discussed in #1272 and I think we can close this issue in favor of that one.
