### ISSUE TITLE
Cannot change route from VirtualAppliance to None

### ISSUE THREAD

**Issue by glenjamin** [terraform-providers/terraform-provider-azurerm#1352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.6.0
```

### Affected Resource(s)

* azurerm_route_table

### Terraform Configuration Files

Before
```hcl
resource "azurerm_route_table" "primary" {
  name                = "primary"
  location            = "${azurerm_resource_group.routes.location}"
  resource_group_name = "${azurerm_resource_group.routes.name}"

  route {
    name                   = "UDR_to_InternetProxy"
    address_prefix         = "0.0.0.0/0"
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = "192.168.0.1"
  }
}
```

After
```hcl
resource "azurerm_route_table" "primary" {
  name                = "primary"
  location            = "${azurerm_resource_group.routes.location}"
  resource_group_name = "${azurerm_resource_group.routes.name}"

  route {
    name           = "UDR_BlackHole"
    address_prefix = "0.0.0.0/0"
    next_hop_type  = "None"
  }
}
```

### Expected Behavior

Route is updated

### Actual Behavior

```
1 error(s) occurred:

* azurerm_route_table.primary: 1 error(s) occurred:

* azurerm_route_table.primary: Error Creating/Updating Route Table "primary" (Resource Group "Network-Routes"): network.RouteTablesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NextHopIpAddressNotAllowed" Message="NextHopIpAddress 192.168.0.1 for route UDR_BlackHole cannot be specified. This field can only be specified for NextHopType VirtualAppliance." Details=[]
```

### Steps to Reproduce

1. `terraform apply` the "before" config
2. `terraform apply` the "after" config

**Comment by draggeta** [comment]
Ran into this same issue, but with the routes itself. There the issue isn't as apparent, as changing the name creates a new resource, but if the name stays the same, it doesn't work.
