### ISSUE TITLE
Multiple run of terraform apply required

### ISSUE THREAD

**Issue by jondkent** [terraform-providers/terraform-provider-azurerm#1361]
Hi,

We are having to run terraform apply multiple time when provisioning a new Azure environment.  This will eventually work, usually after 4 runs, but obviously this doesn't look correct.

For example, on the first run I get the error below, stating the resource group is not found.  However, when I look at the Azure portal I do see this RG, so I can only assume there is some sort of timing issue here.

> Error:
>
> Error applying plan:
>
> 13 error(s) occurred:
>
> module.storage-public.azurerm_storage_account.StorageAccount: 1 error(s) occurred:
>
> azurerm_storage_account.StorageAccount: Error creating Azure Storage Account "sandbox2public": storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'Hello-Cloud-Sandbox-2-Public-RG-1' could not be found."
> module.networksecuritygroups-public.azurerm_network_security_rule.NetworkSecurityRules-1: 1 error(s) occurred:
>
> azurerm_network_security_rule.NetworkSecurityRules-1: Error Creating/Updating Network Security Rule "DenyInternetIn" (NSG "Hello-Cloud-Sandbox-2-Public-NSG-1" / Resource Group "Hello-Cloud-Sandbox-2-Public-RG-1"): network.SecurityRulesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'Hello-Cloud-Sandbox-2-Public-RG-1' could not be found."
> module.networking-public.azurerm_virtual_network.VirtualNetwork: 1 error(s) occurred:
>
> azurerm_virtual_network.VirtualNetwork: Error Creating/Updating Virtual Network "Hello-Cloud-Sandbox->2-Public-VNet-1" (Resource Group "Hello-Cloud-Sandbox-2-Public-RG-1"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original 
> Error: Code="ResourceGroupNotFound" Message="Resource group 'Hello-Cloud-Sandbox-2-Public-RG-1' could not be found."
>module.manageddisk-public.azurerm_managed_disk.ManagedDisk: 1 error(s) occurred:

### Terraform Version
Terraform v0.11.7
+ provider.azurerm v1.6.0
+ provider.random v1.2.0

### Expected Behavior

Deploy new infrastructure to Azure with just one run of terraform apply

### Actual Behavior

Have to run terraform apply multiple time to complete infrastructre

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by katbyte** [comment]
hi @jondkent,

I'm sorry to hear you are having this issue. To better assist us investigating could you please supply us with the terraform config exhibiting this behaviour? thank you!

**Comment by jondkent** [comment]
I've done a bit more digging here and have discovered the following:

- In the first run the resource group is created, but I get a 404 error when terraform tries to create the network security group
- On the second run the storage account is created, but the container creation fails stating the account cannot be found
- The third run completed the infrastructure rollout

Regarding the configuration, this quite large and calling 18 modules in total to setup 2 infrastructures.  These modules just use resources.  This is also wholly variable driven.  TPresently finding out if I can send these to you

Regards,
Jon

**Comment by katbyte** [comment]
@jondkent,

Thank you for the additional information. It sounds like the problem is terraform is trying to create the storage account before the resource group has been created. Are you passing along the names via outputs & resource properties, eg: 
```hcl
location            = "${azurerm_resource_group.rg.location}"
resource_group_name = "${azurerm_resource_group.rg.name}"
```

Or have you hard coded the values?

**Comment by jondkent** [comment]
Hi,

Ah, currently passing hardcoded variable to all the underlying modules for both the resource group and the storage account.  Could it be as simple as that causing the issue?

Regards,
Jon

**Comment by jondkent** [comment]
Hi,

Changed hardcoded variables to outputs and that seems to have fixed it, all working perfectly now.

Many thanks,
Jon

**Comment by katbyte** [comment]
Thats great! Happy to hear everything is working now :)
