### ISSUE TITLE
r/linux_virtual_machine_scale_set: support for TerminateNotificationProfile

### ISSUE THREAD

**Issue by m4r1u2** [terraform-providers/terraform-provider-azurerm#13664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add missing ```terminate_notification```for the General and Linux ScaleSet resource. 
This is already implemented for Windows, so should be easy to reuse code.

### New or Affected Resource(s)

* `azurerm_linux_virtual_machine_scale_set`
* ~azurerm_virtual_machine_scale_set~ (@tombuildsstuff: this resource is feature-frozen)

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine_scale_set" "example" {
..
  terminate_notification {
    enabled = true
    timeout = "PT5M"
  }
..
}
```

### References

This is already implemented for ```windows_virtual_machine_scale_set```

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine_scale_set#terminate_notification

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/windows_virtual_machine_scale_set_resource.go#L286

**Comment by tombuildsstuff** [comment]
hi @m4r1u2 

Thanks for opening this issue.

The older `azurerm_virtual_machine_scale_set` resource is feature-frozen (and will be deprecated in the future) and thus we won't be able to add this functionality to that resource - but we'll look to support this on the `azurerm_linux_virtual_machine_scale_set` resource - as such I'm going to update this feature request to be targeted to the `azurerm_linux_virtual_machine_scale_set` resource instead.

Thanks!
