### ISSUE TITLE
Feature Request: Support for Gremlin/Graph databases in Cosmos DB

### ISSUE THREAD

**Issue by mrtoby** [terraform-providers/terraform-provider-azurerm#1370]
Hi,

I use the graph/gremlin interface for Cosmos DB in my application and would like to be able to do so using terraform. The gremlin interface is activated by providing a capability "EnableGremlin", see attached file. I got this information from microsoft support since I had a hard time to get it to work with ARM-templates also.

I guess this support could be added by adding "kind" = "Gremlin" or "Graph" or something.

Thanks for a fantastic tool!

**Comment by katbyte** [comment]
Hi @mrtoby,

If you could supply the ARM template that would be a huge help 🙂

Thanks!

**Comment by tombuildsstuff** [comment]
hey @mrtoby 

Would you be able to provide the ARM Template you've referenced above? Taking a quick look into this it appears Capability exist in the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go/blob/v17.3.1/services/cosmos-db/mgmt/2015-04-08/documentdb/models.go#L150) - so it appears possible to support this at some point :)

Thanks!

**Comment by mrtoby** [comment]
Sorry for my late response, here is a template I mentioned above:
(Seems not to be possible to attach, so I inlined it)

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.DocumentDB/databaseAccounts",
            "kind": "GlobalDocumentDB",
            "name": "your-account-name",
            "apiVersion": "2015-04-08",
            "location": "West US",
            "properties": {
                "databaseAccountOfferType": "Standard",
                "consistencyPolicy": {
                    "defaultConsistencyLevel": "Session",
                    "maxIntervalInSeconds": 5,
                    "maxStalenessPrefix": 100
                },
                "locations": [
                    {
                        "locationName": "westus",
                        "failoverPriority": 0
                    }
                ],
                "capabilities": [
                    {
                        "name": "EnableGremlin"
                    }
                ]
            }
        }
    ]
}
