### ISSUE TITLE
Getting error when recreating SQL extension for existing SQL VM with terraform

### ISSUE THREAD

**Issue by iqmetrix-cloudops** [terraform-providers/terraform-provider-azurerm#13737]
Getting error when recreating SQL extension for existing SQL VM with terraform:

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version: 0.14.2
Azurerm provider: 2.50.0

### Affected Resource(s)

azurerm_mssql_virtual_machine

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: waiting for creation of Sql Virtual Machine (Sql Virtual Machine Name "xxxxxxxxxx" / Resource Group "xxxxxxxxxxxxxxxxxxxx"): Code="Ext_AutomatedBackupError" Message="Error: 'This request operation sent to net.pipe://localhost/MicrosoftSqlIaaSAgent/SqlIaaSExtensionQuerySvc did not receive a reply within the configured timeout (00:01:00).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client.'"

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
