### ISSUE TITLE
SCM deployment support Azure Web App

### ISSUE THREAD

**Issue by metacpp** [terraform-providers/terraform-provider-azurerm#1375]

**Comment by metacpp** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/git-pull-request.svg) [[WIP]Add support of GitHub as deployment option #1121](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1121) [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/Fbp2/issues/6436799) | Soon | metacpp | Backlog | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by tombuildsstuff** [comment]
Duplicate of #1104
