### ISSUE TITLE
Private azurerm_kubernetes_cluster with 'private_dns_zone_id' and 'dns_prefix_private_cluster' attributes set during creation incorrectly shows changes requiring destroy on subsequent apply 

### ISSUE THREAD

**Issue by eehret** [terraform-providers/terraform-provider-azurerm#13763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.78.0

NOTE:  I'm aware that this isn't the latest version of the 'azurerm' provider but I cannot use the latest because of another  unresolved bug that is currently affecting me: https://github.com/Azure/AKS/issues/2584

### Affected Resource(s)
* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks_cluster" {
  name                = var.cluster_name
  location            = var.location
  resource_group_name = var.resource_group_name

  default_node_pool {
    name                  = "nodepool1"
    vm_size               = var.node_size
    enable_node_public_ip = false
    max_pods              = var.max_pods
    os_disk_size_gb       = var.os_disk_size_gb
    type                  = "VirtualMachineScaleSets"
    tags                  = var.tags
    vnet_subnet_id        = var.subnet_id
    node_count            = var.node_count
  }

  dns_prefix_private_cluster = var.dns_prefix

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = var.log_analytics_workspace_id
    }
  }

  identity {
    type = "UserAssigned"
    user_assigned_identity_id = var.user_assigned_identity_id
  }

  kubernetes_version = var.kubernetes_version

  network_profile {
    network_plugin    = "azure"
    outbound_type     = "userDefinedRouting"
    load_balancer_sku = "Standard"
  }

  node_resource_group     = "${var.resource_group_name}-aks-nodes"
  private_cluster_enabled = true
  private_dns_zone_id = var.private_dns_zone_id
  private_cluster_public_fqdn_enabled = false

  role_based_access_control {
    azure_active_directory {
      managed                = true
      admin_group_object_ids = var.administrator_group_id_list
    }

    enabled = true
  }

  tags = var.tags
/*
  lifecycle {
    ignore_changes = [ dns_prefix_private_cluster, dns_prefix ]
  }
*/
}
```

### Expected Behaviour
Upon applying the above configuration with the required input variables provided, Terraform should have created the private cluster integrated with the specified `private_dns_zone_id`.  Immediately after successful creation of the resource, when running a subsequent 'apply' no changes should be detected.

### Actual Behaviour
Terraform shows a change to both the `dns_prefix` and `dns_prefix_private_cluster` fields, forcing replacement of the cluster that was just created.

### Steps to Reproduce
1. `terraform apply` the above (with required variables populated)
2. `terraform plan`

### Important Factoids

1. The Private DNS zone that was configured when I did the initial apply is in a different subscription than the cluster.  It appears that it was properly integrated and working fine, despite Terraform's behaviour;
2. A workaround for now is to uncomment the `lifecycle` block shown above to ignore changes to the `dns_prefix_private_cluster` and `dns_prefix` fields

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @eehret 

Thanks for opening this issue.

In order to be able to look into this we're going to need to see the diff that Terraform is proposing here, my guess is there's a casing difference between the two values which is causing this; but it may also be that this isn't being returned from the API - as such if you can post the diff for this line then we should be able to track this down.

Thanks!

**Comment by stephybun** [comment]
Hi @eehret,

I attempted to reproduce this error using v2.78.0 of the provider and the information you provided in the issue but I was unsuccessful. Seeing as you are also using some advanced networking options for the cluster, the details of which I do not know - would you be able to provide a minimal config that is able to reproduce the error?

Thanks!

**Comment by stephybun** [comment]
Closing since we haven't heard back. If this is still an issue and you can provide additional information to help us troubleshoot this let us know and we can reopen this.
