### ISSUE TITLE
Add UserAssigned identity type

### ISSUE THREAD

**Issue by bg2132332** [terraform-providers/terraform-provider-azurerm#1377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to see support for user-assigned managed identities, in addition to system-assigned identities.

https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#type

### New or Affected Resource(s)

* azurerm_virtual_machine

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by logachev** [comment]
I'm working on this feature now. I think it will be ready for the PR next week.
https://github.com/logachev/terraform-provider-azurerm/tree/feature/userManagedIdentity

**Comment by tombuildsstuff** [comment]
Added via #1448
