### ISSUE TITLE
Redis Cache Resource - Minor documentation error

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1379]
redis_configuration supports several values.  In the documentation, one of the values is `maxmemory_reserve` when it should be `maxmemory_reserved`.

The documentaion states that maxmemory_reserved is only available for the Standard and Premium caches but it appears that this is also true for maxmemory_delta as Terraform thru an error with this value.

**Comment by katbyte** [comment]
Hello @Phydeauxman,

Thank you for spotting this! I have opened #1381 to correct these mistakes.
