### ISSUE TITLE
subscription_id provider property not enforcing the subscription for all resources.

### ISSUE THREAD

**Issue by lra** [terraform-providers/terraform-provider-azurerm#13830]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.40.0
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.81.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`
* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```
provider "azurerm" {
  features {}
  tenant_id = "TENANT_ID"
  subscription_id = "SUB_A"
}
```

### Expected Behaviour

When planning, terraform should be able to plan the resources in the specified subscription ID.

### Actual Behaviour

The terraform provider does not follow the specified subscription ID and instead uses the subscription ID of the CLI set with `az account set --subscription="SUB_B"`

### Steps to Reproduce

1. Have 2 subscriptions SUB_A and SUB_B and a `azurerm_kubernetes_cluster` in the terraform state created in SUB_A.
2. Specify SUB_A in the azurerm provider as `subscription_id`
3. `terraform plan`: No changes
4. Set SUB_B in the CLI: `az account set --subscription="SUB_B"`
5. `terraform plan: The `azurerm_kubernetes_cluster` shows as "will be created"

### Workaround

I can define the `ARM_SUBSCRIPTION_ID="SUB_A"` env var, then the bad subscription set in the az cli is not followed.

### Notes

Most resources follow the `subscription_id` property, we have lots of resources and only `azurerm_kubernetes_cluster` `azurerm_kubernetes_cluster_node_pool` don't follow the `subscription_id` property.

**Comment by lpiob** [comment]
I'd like to confirm the issue. The azurerm provider seems to ignore the `subscription_id` parameter. This causes errors and confusion. 

Using `az account set --subscription="sub-name"` allows to override that, but disallows working on multiple subscriptions at once. An ARM_SUBSCRIPTION_ID environment variable is a working workaround, but it's error-prone.

**Comment by MindAwakeBodyAsleep** [comment]
I can agree with @lpiob. @tombuildsstuff can you reopen this issue?
