### ISSUE TITLE
App_Service SCM Type Addition - VSTSRM

### ISSUE THREAD

**Issue by whytoe** [terraform-providers/terraform-provider-azurerm#1387]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Addition of the Deployment Centre Source Control from VSTSRM

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

site_config {
  scm_type = VSTSRM
}

Example being thrown currently in Terraform
~ azurerm_app_service.app1 
      site_config.0.scm_type: "VSTSRM" => "None"

Error: azurerm_app_service.rusbitsapp: expected site_config.0.scm_type to be one of [None LocalGit], got VSTSRM

### References
https://blogs.msdn.microsoft.com/appserviceteam/2018/06/04/app-service-deployment-center-preview/

* #0000

**Comment by tombuildsstuff** [comment]
hey @whytoe 

Thanks for opening this issue :)

Support for other SCM types has previously been requested in #1104 - as such I'm going to close this issue in favour of that one.

Thanks!
