### ISSUE TITLE
"context deadline exceeded" when refreshing state for azurerm_storage_account

### ISSUE THREAD

**Issue by davetustin** [terraform-providers/terraform-provider-azurerm#13889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.82.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
  location = var.location
  
  tags = var.default_tags
}

resource "azurerm_storage_account" "tiering" {
  name                     = var.storage_account_tiering_name
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier              = "Cool"
  min_tls_version          = "TLS1_2"
  allow_blob_public_access = "true"

  network_rules {
    default_action = "Deny"
    ip_rules       = var.storage_account_tiering_network_rules
  }

  tags = var.default_tags
}

resource "azurerm_storage_container" "tiering" {
  name                  = var.storage_account_tiering_container_name
  storage_account_name  = azurerm_storage_account.tiering.name
  container_access_type = "blob"
}
```

### Expected Behaviour

When running terraform plan the state should be refreshed

### Actual Behaviour

```
azurerm_storage_container.containername: Refreshing state... [id=https://storageaccount.blob.core.windows.net/container]

Error: Error retrieving Container "container" (Account "storageaccount" / Resource Group "resourcegroup"): containers.Client#GetProperties: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The state files are saved to a remote backend in Azure.

**Comment by y2kbugger** [comment]
@davetustin  Do you have a workaround for the state refreshing on plan? #2977 bugs out on apply andso they work-around using ARM templates.

**Comment by davetustin** [comment]
@y2kbugger The only way I can run the plan is by skipping the refresh by using the `-refresh=false`, which isn't ideal, but it might work for you in certain scenarios.

I can see this becoming more of an issue going forward as Microsoft promote the use of Private Links to meet Security policies and companies use them to be compliant.

Fingers crossed this will get sorted out in the future! 🤞
