### ISSUE TITLE
Validate arguments before applying them

### ISSUE THREAD

**Issue by antonbabenko** [terraform-providers/terraform-provider-azurerm#1405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Validate obvious arguments before calling SDK. It is probably better to validate on both sides (SDK and Terraform provider).

This is an example of a failure which took 2 minutes:

```
* azurerm_kubernetes_cluster.test: Long running operation terminated with status 'Failed': Code="InvalidParameter" Message="The Admin Username specified is not allowed."
```

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "test" {
  linux_profile {
    admin_username = "user"
    # ...
  }
}

```

**Comment by metacpp** [comment]
@antonbabenko Thanks for opening this issue.

I'd like to share some updates here:
1. `user` is acceptable format by `admin_username` now.
2. Working on PR to add more validations for K8s fields.
