### ISSUE TITLE
Splat operator on iothub shared_access_policy is not interpolated correctly 

### ISSUE THREAD

**Issue by alex0ptr** [terraform-providers/terraform-provider-azurerm#1414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.7.0
```

### Affected Resource(s)

* azurerm_iothub

### Terraform Configuration Files

```hcl
provider "azurerm" {}

resource "azurerm_resource_group" "rg" {
  name     = "foo"
  location = "germanycentral"
}

resource "azurerm_iothub" "iothub" {
  name                = "bar-asdasdas"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  location            = "germanycentral"

  sku {
    name     = "S1"
    tier     = "Standard"
    capacity = "1"
  }
}

locals {
  servicePolicyKeys = "${azurerm_iothub.iothub.shared_access_policy.*.primary_key}"

  # what I actually want:
  # servicePolicyKey   = "${element(matchkeys(azurerm_iothub.iothub.shared_access_policy.*.primary_key, azurerm_iothub.iothub.shared_access_policy.*.key_name, list("service")), 0)}"
}

```

### Debug Output

The output contains non-expired JWT tokens with confidential information and is not safe to share. Please add a notice to other users about this. Here is the normal output after creating the resource group:

```
azurerm_resource_group.rg: Refreshing state... (ID: /subscriptions/.../resourceGroups/foo)
azurerm_iothub.iothub: Refreshing state... (ID: /subscriptions/...Microsoft.Devices/IotHubs/bar-asdasdas)

Error: Error applying plan:

1 error(s) occurred:

* local.servicePolicyKeys: local.servicePolicyKeys: Resource 'azurerm_iothub.iothub' does not have attribute 'shared_access_policy.*.primary_key' for variable 'azurerm_iothub.iothub.shared_access_policy.*.primary_key'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior

The program should terminate normally and provide the primary keys as a list in a local variable.

### Actual Behavior

Terraform crashed because of an interpolation error.

### Steps to Reproduce

1. `terraform apply`

**Comment by thoregilk** [comment]
I am currently not getting any output from shared_access_policy other than the number of policies configured. Tried in a couple of different ways to refer the first access policy in the list. (iothubowner)

```
output "primary_key" {
  value = ["${azurerm_iothub.default.shared_access_policy.*.primary_key}"]
}
output "key_name" {
  value = ["${azurerm_iothub.default.shared_access_policy.*.key_name}"]
}
```
```
  app_settings = {
    partnerEventHubEndpoint       = "Endpoint=${module.iot_hub_test.events_endpoint};${element(module.iot_hub_test.key_name, 0)};${element(module.iot_hub_test.primary_key, 0)}"
}
```
Terraform will perform the following actions:

 ~ module.function_test.azurerm_function_app.default
      app_settings.partnerEventHubEndpoint: "Endpoint=sb://iothub-ns-iot-we-par-123456-12345678910.servicebus.windows.net/;7;7"

**Comment by neil-yechenwei** [comment]
@alex0ptr, Thanks for opening this issue. I assume this issue has been fixed since I cannot repro this issue anymore. Maybe I missed something. Could you have a try with latest azurerm and below tfconfig to check whether the issue still exists? Thanks.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "rg-iot-policy-v1r7u-issue"
  location = "eastus2"
}

resource "azurerm_iothub" "test" {
  name                = "iot-iot-policy-v1r7u-issue"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  sku {
    name     = "S1"
    capacity = "1"
  }
}

locals {
  servicePolicyKeys = "${azurerm_iothub.test.shared_access_policy.*.primary_key}"

  servicePolicyKey   = "${element(matchkeys(azurerm_iothub.test.shared_access_policy.*.primary_key, azurerm_iothub.test.shared_access_policy.*.key_name, list("service")), 0)}"
}

output "servicePolicyKeys1" {
  value = "${azurerm_iothub.test.shared_access_policy.*.primary_key}"
}

output "servicePolicyKey" {
  value = "${element(matchkeys(azurerm_iothub.test.shared_access_policy.*.primary_key, azurerm_iothub.test.shared_access_policy.*.key_name, list("service")), 0)}"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Based on what I can see above this has been fixed in a patch release of Terraform Core - as such I'm going to close this issue for the moment - but if you're still having issues after upgrading to the latest version of Terraform Core then you should be able to get further assistance for this [using one of the Community Resources](https://www.terraform.io/community.html)

Thanks!
