### ISSUE TITLE
AKS cluster creation fails with no error message if VM size is incorrect

### ISSUE THREAD

**Issue by timwebster9** [terraform-providers/terraform-provider-azurerm#1416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.6
+ provider.azurerm v1.7.0
```

### Affected Resource(s)

* azurerm v1.7.0

### Debug Output

https://gist.github.com/timwebster9/0b71442e8e04c6fcfc03f586b3df7aad

### Expected Behavior

Terraform should have provided the actual error

### Actual Behavior

```
* module.default.azurerm_kubernetes_cluster.aks_cluster: 1 error(s) occurred:

* azurerm_kubernetes_cluster.aks_cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="" Message=""
```

### Steps to Reproduce

You just need to provide an incorrect VM size value.  I used `D2s_v3` instead of `Standard_D2s_v3` by mistake.

**Comment by tombuildsstuff** [comment]
hey @timwebster9 

Thanks for opening this issue :)

All communication with from Terraform to the Azure API's is handled by [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go), in this case it appears the error is available in the HTTP Response but isn't being parsed out correctly - as such [I've opened an issue on the Azure SDK for Go repository](https://github.com/Azure/azure-sdk-for-go/issues/2085) about this.

Thanks!

**Comment by dano0b** [comment]
As mentioned in https://github.com/Azure/azure-sdk-for-go/issues/2085 it requires an upgrade of the sdk v16 -> v17), would be awesome if that will be picked up soon.

**Comment by tombuildsstuff** [comment]
👋 We've upgraded to SDKv17 in #1418 - as such this should be fixed in the next release (and I'm going to close this for the moment)
