### ISSUE TITLE
Postgresql Gen4 deployment not working

### ISSUE THREAD

**Issue by spacekitty76** [terraform-providers/terraform-provider-azurerm#1425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7
+ provider.azurerm v1.3.1

### Affected Resource(s)
azurerm_postgresql_server
azurerm_postgresql_database

### Terraform Configuration Files
I'm following the documentation here (https://www.terraform.io/docs/providers/azurerm/r/postgresql_database.html) to deploy postgresql to a Gen4 supported region.  I've tried using several different provider versions, and tried deploying to different regions that support Gen4 on Azure.  I get the same errors each time.

```hcl
provider "azurerm" {
  version = ">= 1.3"
}

resource "azurerm_resource_group" "test" {
  name     = "westus-test"
  location = "westus"
}

resource "azurerm_postgresql_server" "test" {
  name                = "postgresql-server-1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    name = "B_Gen4_2"
    capacity = 2
    tier = "Basic"
    family = "Gen4"
  }

  storage_profile {
    storage_mb = 5120
    backup_retention_days = 7
    geo_redundant_backup = "Disabled"
  }

  administrator_login = "psqladminun"
  administrator_login_password = "H@Sh1CoR3!"
  version = "9.5"
  ssl_enforcement = "Enabled"
}

resource "azurerm_postgresql_database" "test" {
  name                = "exampledb"
  resource_group_name = "${azurerm_resource_group.test.name}"
  server_name         = "${azurerm_postgresql_server.test.name}"
  charset             = "UTF8"
  collation           = "English_United States.1252"
}
```

### Debug Output
Terraform didn't crash so I don't know what kind of debug output you want here?  I've put the error messages into the "Actual Behavior" section of this report.

### Panic Output
None

### Expected Behavior
The postgresql resource should have been created

### Actual Behavior
The following errors were produced:
```
$ terraform plan
Error: azurerm_postgresql_server.test: "storage_mb": required field is not set
Error: azurerm_postgresql_server.test: : invalid or unknown key: storage_profile
Error: azurerm_postgresql_server.test: expected "sku.0.capacity" to be one of [50 100 200 400 800], got 2
Error: azurerm_postgresql_server.test: expected sku.0.name to be one of [PGSQLB50 PGSQLB100 PGSQLS100 PGSQLS200 PGSQLS400 PGSQLS800], got B_Gen4_2
Error: azurerm_postgresql_server.test: sku.0: invalid or unknown key: family
```

### Steps to Reproduce
Change to the directory where the config is.
Run 'terraform plan'.

### Important Factoids
None that I can think of right now.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @spacekitty76 

Thanks for opening this issue :)

> provider.azurerm v1.3.1

Support for the GA version of Postgresql was added in v1.5 of the AzureRM Provider - whereas you're currently using v1.3.1 of the Provider which only supports the Preview/older SKU's; which is why you're seeing this error message. You can update to the new version of the Provider by specifying the version in the Provider block (as shown below) and then running `terraform init`:

```
provider "azurerm" {
  version = "=1.7.0"
}
```

Thanks!
