### ISSUE TITLE
Standard SSD Managed Disk Type option not available to set in terraform

### ISSUE THREAD

**Issue by pbbpage** [terraform-providers/terraform-provider-azurerm#1432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In ARM, you are able to create a Standard SSD managed disk type. [managed disk types](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/managed-disks-overview#pricing-and-billing), but in terraform the `managed_disk_type' only has the options `"Standard_LRS"` and `"Premium_LRS"`.  These do not account for the Standard SSD option.  My request is a new flag for this type of managed disk.

**Comment by tombuildsstuff** [comment]
hey @pbbpage 

Thanks for opening this issue :)

From what I can see support isn't available for this [in the Azure SDK for Go at the moment](https://github.com/Azure/azure-sdk-for-go/blob/v18.0.0/services/compute/mgmt/2018-04-01/compute/models.go#L516) which is how we interact with Azure - however once support's available within the SDK we can look into supporting this.

Thanks!

**Comment by ira-bryndzei** [comment]
hi @tombuildsstuff, thanks for your reply. On your [last commit](https://github.com/terraform-providers/terraform-provider-azurerm/commit/e6b197776c02f5036dc0f539312f863e8dacf1af) I see that you added support for v.20.1.0 which supports StorageAccountTypesStandardSSDLRS disk type but I wonder why you didn't updated it to use StandardSSDLRS disk type

**Comment by ira-bryndzei** [comment]
Hi @tombuildsstuff 
I created pull request [pull request](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1901) to update provider to use Standard SSD lisk type

**Comment by ira-bryndzei** [comment]
@tombuildsstuff could you please take a look at this  [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1901)  I'm a little bit blocked by it.

**Comment by ChrisPr1** [comment]
Is there any way to also have standardHDD and premiumSSD added as well?

**Comment by rifaterdemsahin** [comment]
standard SSD I am also waiting for any updates on this one ?

**Comment by ira-bryndzei** [comment]
@rifaterdemsahin standard ssd disk type has been added already. looks like you didn't updated azure provider locally. You can try to delete .terraform folder from a folder with you tf scripts and run `terraform init` again to force to update provider. Hope this could help you
