### ISSUE TITLE
Feature Request : addonProfiles and networkProfile for Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by idelix** [terraform-providers/terraform-provider-azurerm#1434]
AKS now allows to place cluster in custom vnet and also to integrate monitoring with log analytics workspace, this is now available in ARM template but seems to be missing from terraform resource: azurerm_kubernetes_cluster.

Just for reference here is working example of ARM Template with both addonProfiles and networkProfile:

```
        {
            "name": "[variables('aksClusterName')]",
            "type": "Microsoft.ContainerService/managedClusters",
            "apiVersion": "2018-03-31",
            "location": "[resourceGroup().location]",
            "tags": {
                "Owner": "[variables('tagName')]"
            },
            "dependsOn": [
                "[concat('Microsoft.OperationalInsights/workspaces/', variables('laName'))]",
                "[concat('Microsoft.Network/virtualNetworks/', variables('vnetName'))]"
            ],
            "properties": {
                "mode": "Incremental",
                "dnsPrefix": "[variables('aksDnsPrefix')]",
                "kubernetesVersion": "[variables('aksVersion')]",
                "agentPoolProfiles": [
                    {
                        "name": "[variables('aksPoolName')]",
                        "osDiskSizeGB": "[variables('aksOsDiskSizeGB')]",
                        "count": "[variables('aksVmCount')]",
                        "vmSize": "[variables('aksVmSize')]",
                        "osType": "Linux",
                        "vnetSubnetID": "[variables('subnetId')]",
                        "maxPods": 30,
                        "storageProfile": "ManagedDisks"
                    }
                ],
                "linuxProfile": {
                    "adminUsername": "[parameters('aksUserName')]",
                    "ssh": {
                        "publicKeys": [
                            {
                                "keyData": "[variables('aksKeyData')]"
                            }
                        ]
                    }
                },
                "servicePrincipalProfile": {
                    "clientId": "[parameters('aksServicePrincipalClientId')]",
                    "secret": "[parameters('aksServicePrincipalSecret')]"
                },
                "addonProfiles": {
                    "omsagent": {
                        "enabled": true,
                        "config": {
                            "logAnalyticsWorkspaceResourceID": "[resourceId('Microsoft.OperationalInsights/workspaces', variables('laName'))]"
                        }
                    }
                },
                "networkProfile": {
                    "networkPlugin": "[variables('aksNetworkPlugin')]",
                    "serviceCidr": "[variables('aksServiceCidr')]",
                    "dnsServiceIP": "[variables('aksDnsServiceIP')]",
                    "dockerBridgeCidr": "[variables('aksDockerBridgeCidr')]"
                }
            }
        }
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tombuildsstuff** [comment]
Dependent on #1389

**Comment by lfshr** [comment]
Started working on these features.
https://github.com/lfshr/terraform-provider-azurerm/tree/containerservices-advancednetworking

@tombuildsstuff  I was planning on keeping the work part of #1389, If we're separating them out should we close #1389 now that it's merged?

**Comment by tombuildsstuff** [comment]
@lfshr indeed, I've closed the other issue in favour of this one - thanks for the heads up :)

**Comment by lfshr** [comment]
Started work on the addonProfiles
https://github.com/lfshr/terraform-provider-azurerm/tree/containerservices-addonprofile

**Comment by lfshr** [comment]
#1502 opened

**Comment by flyinprogrammer** [comment]
agent_pool_profile is also missing `maxPods`

**Comment by sijusamueltech** [comment]
when is this 'advanced networking feature'  expected to be released ?

**Comment by mbrancato** [comment]
@sijusamueltech advanced networking is available today, but the network profile is not. Due to a combination of issues, AKS will not create a functional cluster with advanced networking specified but without a network profile.

Don't do this today, but an example of how to pass the subnet ID is below.
```
  agent_pool_profile {
    name            = "default"
    vm_size         = "Standard_DS1_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = "${var.vnet_subnet_id}"
  }
```

**Comment by tombuildsstuff** [comment]
Fixed via #1479

**Comment by schweikert** [comment]
Does it mean that also in the future specifying something in "vnet_subnet_id" but without an explicit network profile configuration will get you non-functional clusters?

**Comment by sijusamueltech** [comment]
@mbrancato   @tombuildsstuff       Looking forward to create a fully functioning AKS with advanced networking option using terraform.   Following are the most important features of our interest.    Networking  - Option to chose  Virtual network, subnet and  other configs(DNS Ip, K8 service address range, Docker bridge address )  - [this is mapped from the azure portal UI for creating kubernetes services ].     Currently using just the  ARM template to automate the AKS cluster creation.   May be going with the default network profile is also ok .  Can you please point to right terraform version, when ever it is ready..  thx.

**Comment by mbrancato** [comment]
@schweikert This probably could use testing. I'm not certain if a default networkProfile will be sent.

@sijusamueltech All the network profile information should be in the next release of the azurerm provider as it is currently targeted for 1.12.0. The HashiCorp team has been really good about adding features and quick releases recently.
