### ISSUE TITLE
parameters_body  generates an "The request content was invalid and could not be deserialized" error for any parameter file

### ISSUE THREAD

**Issue by sam-cogan** [terraform-providers/terraform-provider-azurerm#1437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

provider.azurerm v1.7.0

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
```
resource "azurerm_template_deployment" "acscluster" {
  name                = "${var.dns_prefix}"
  resource_group_name = "${var.rgName}"
  deployment_mode     = "Incremental"
  template_body       = "${file("./_output/${var.dns_prefix}/azuredeploy.json")}"
  parameters_body     = "${file("./_output/${var.dns_prefix}/azuredeploy.parameters.json")}"
}

```
### Actual Behavior

When attempting to use the parameters_body parameter in the azurerm_template_deployment resource to read in a  parameters file, an error is generated. This parameter file works fine when used manually in either the Azure CLI or PowerShell deployment but when using this provider it fails with this error:

`azurerm_template_deployment.acscluster: Error creating deployment: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Error converting value \"http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#\" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 1, position 152673.'."`

I have tested with simple parameter files with a single parameter and get the same problem, so it does not seem to be related to the size.

### Steps to Reproduce

Attempt to use the azurerm_template_deployment and specificity an parameters_body pointing to a resource

### References

* #0000

**Comment by joshlrogers** [comment]
This also seems to be occurring in version 1.9.0 of the azurerm provider.

**Comment by tombuildsstuff** [comment]
👋 

Since this should be fixed by updating the Parameters file ([as mentioned in @joshlrogers's comment above](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1437#issuecomment-406307845)) - and [the documentation has recently been updated to clarify this](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html#parameters_body) I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.
