### ISSUE TITLE
Feature Request: Add missing input and outputs for azurerm_app_service_slot 

### ISSUE THREAD

**Issue by kevinneufeld** [terraform-providers/terraform-provider-azurerm#1439]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azurerm_app_service_slot` would be great to have the following input and outputs :

#### Inputs:
- identity

#### Outputs:
- identity
- site_credential

### New or Affected Resource(s)
- `azurerm_app_service` as reference
- `azurerm_app_service_slot`

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_slot" "test" {
  name                = "${random_id.server.hex}"
  app_service_name    = "${azurerm_app_service.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  app_service_plan_id = "${azurerm_app_service_plan.test.id}"

  site_config {
    dotnet_framework_version = "v4.0"
  }

  app_settings {
    "SOME_KEY" = "some-value"
  }

  connection_string {
    name  = "Database"
    type  = "SQLServer"
    value = "Server=some-server.mydomain.com;Integrated Security=SSPI"
  }
}

output "slot_site_credentials_username"{
   value = "${azurerm_app_service_slot.test.site_credential.0.username}"
}
output "slot_site_credentials_password"{
   value = "${azurerm_app_service_slot.test.site_credential.0.password}"
}
```

**Comment by tombuildsstuff** [comment]
hey @kevinneufeld 

Thanks for opening this issue - this functionality has previously been requested in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1268 and https://github.com/terraform-providers/terraform-provider-azurerm/issues/1104 - so that we don't have multiple issues open tracking the same thing I'm going to close this issue in favour of those issues above.

Thanks!

**Comment by Leon99** [comment]
@tombuildsstuff Please forgive me if I'm missing something, but neither of the issues you referenced mentions implementing `site_credential` output for `azurerm_app_service_slot`.

**Comment by tombuildsstuff** [comment]
@Leon99 the `site_credential` block is the SCM block - given the App Service and App Service Slot resources share a bunch of common logic we can add it to both in #1104 :)

**Comment by Leon99** [comment]
Sounds good but I still feel like I'm missing something :) site_credential currently works just fine for App Services but not for the slots. #1104 is about adding support for more SCM types. So what's the link between supporting more SCM types and site_credential for slots? Also, if you're saying that they share a lot (expectedly), what's the problem with supporting it specifically for slots?
