### ISSUE TITLE
data_disk_attachment implementation help

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#1441]
This is in reference to testing the following PR - https://github.com/terraform-providers/terraform-provider-azurerm/pull/1207 (Working great so far!  Thank you @tombuildsstuff )

The goal would be to build out an environment with more than 2 VMs with X data disks.  It works perfectly using this TF file - https://gist.github.com/rohrerb/0cac6f3b24691674538067fd491c460d

**Builds out the following:**
https://imgur.com/hS8bb1X 

Once the environment is built, increment the variable for data_disk_count from "1" to "2" and re-run a plan.  

> variable "data_disk_count" {  default = 2}

You will see that it wants to destroy the the 2nd VM disk because the element changed based on the new count.index.   I know that AWS has had attached disk logic for a while and im hoping that someone figured out how to apply this sort of logic.

**Comment by tombuildsstuff** [comment]
@rohrerb thanks for this feedback - since this isn't an issue with the AzureRM Provider directly (but instead an issue with Terraform Core) I'm going to close this issue for the moment

**Comment by rohrerb** [comment]
@tombuildsstuff  - Is something similar open in TF Core?

**Comment by tombuildsstuff** [comment]
@rohrerb I have a feeling this should be fixed by the next major version of Terraform - [it may well be worth opening an issue specifically about this on that repository](https://github.com/hashicorp/terraform/issues) however to be able to subscribe to updates :)
