### ISSUE TITLE
Feature Request: App Service VNET Integration

### ISSUE THREAD

**Issue by samcook** [terraform-providers/terraform-provider-azurerm#1445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability to connect an app service (or app service slot) to a virtual network via an existing virtual network gateway.

### New or Affected Resource(s)

* azurerm_app_service
* azurerm_app_service_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service" "app" {
  resource_group_name = "appservice-rg"
  location            = "westus"
  name                = "appservice-name"
  app_service_plan_id = "appserviceplan-id"

  virtual_network_integration {
    gateway_name        = "vnetgateway-name"
    resource_group_name = "vnetgateway-rg"
  }
}
```

### References

https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet
https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/virtualnetworkconnections
https://gallery.technet.microsoft.com/scriptcenter/Connect-an-app-in-Azure-ab7527e3

**Comment by tombuildsstuff** [comment]
hi @samcook 

Thanks for opening this issue :)

App Services can be attached to Virtual Network's by attaching the App Service Plan containing the App Service to an App Service Environment; [this property is available in the `properties` block on the `azurerm_app_service_plan ` resource as  `app_service_environment_id`](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#app_service_environment_id). It's not currently possible to create an App Service Environment using Terraform - however support for this is being tracked in this issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/438.

Since this is a question regarding Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment.

Thanks!

**Comment by tombuildsstuff** [comment]
@samcook 

> Is this still something that you'd consider implementing?

Yes it is (whilst this isn't on our short-term roadmap at the moment, we're happy to help with a PR for this). Apologies, I missed that this wasn't related to the App Service Environment connection method - I'll reopen this :)

**Comment by tombuildsstuff** [comment]
@samcook 

> If this link is to be believed, it's not even something that can be done using ARM templates alone. 🙁

The good news is it appears there's an API's for both of these:

https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdatevnetconnection
https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdatevnetconnectiongateway

I've not checked the SDK yet - but assuming there's matching SDK methods for these (which there should be if there's docs) it should be possible to add this to Terraform :)

**Comment by losandes** [comment]
I think this is the SDK documentation that correlates to those APIs @tombuildsstuff 

https://godoc.org/github.com/Azure/azure-sdk-for-go/services/web/mgmt/2016-09-01/web#VirtualNetworkProfile

**Comment by thoregilk** [comment]
Would it not make sense to also include virtual_network_name for azurerm_function_app since they do share the same api calls and both of them are app service?

**Comment by tombuildsstuff** [comment]
@thoregilk given that's a separate resource (since it's slightly different) - there's a feature request for Virtual Network Integration within Function Apps here https://github.com/terraform-providers/terraform-provider-azurerm/issues/1460 - which I'd recommend subscribing to for updates
