### ISSUE TITLE
Subnet IDs not available as a list greater than a size of 1

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#1447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.7.0

### Affected Resource(s)

* azurerm_subnet

### Terraform Configuration Files
A basic configuration is below. A list of subnet prefixes is expected in the `subnet_prefixes` variable.

```hcl
provider "azurerm" {
  version = "~> 1.7.0"
}

resource "azurerm_resource_group" "test_rg" {
  name     = "test-rg"
  location = "eastus"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "test-vnet"
  address_space       = ["10.10.0.0/16"]
  location            = "${azurerm_resource_group.test_rg.location}"
  resource_group_name = "${azurerm_resource_group.test_rg.name}"
}

resource "azurerm_subnet" "subnets" {
  count                     = "${length(var.subnet_prefixes)}"
  name                      = "test-subnet-${count.index}"
  resource_group_name       = "${azurerm_resource_group.test_rg.name}"
  virtual_network_name      = "${azurerm_virtual_network.vnet.name}"
  address_prefix            = "${var.subnet_prefixes[count.index]}"
}

resource "azurerm_network_interface" "nic" {
  name                = "test-nic"
  location            = "${azurerm_resource_group.test_rg.location}"
  resource_group_name = "${azurerm_resource_group.test_rg.name}"

  ip_configuration {
    name                          = "ipconfig0"
    subnet_id                     = "${azurerm_subnet.subnets.1.id}"
    private_ip_address_allocation = "dynamic"
  }
}
```

### Debug Output

https://gist.github.com/mbrancato/b79158e407193b152539ee095a5e39ed

### Expected Behavior

Plan should complete, properly assigning the net to subnet[1].

### Actual Behavior

The value for `azurerm_subnet.subnets.1.id` is invalid. However, `azurerm_subnet.subnets.0.id` is valid and works.

### Steps to Reproduce

1. `terraform plan`

**Comment by straubt1** [comment]
You need to use a splat (*) and the `element()` interpolation. 

Try:
```hcl
resource "azurerm_network_interface" "nic" {
  ...
  ip_configuration {
    name                          = "ipconfig0"
    subnet_id                     = "${element(azurerm_subnet.subnets.*.id,1)}"
  }
}
```

**Comment by mbrancato** [comment]
Thanks. I realized this later on as well, it just seem odd that it can be accessed with `.0.`
Closing.
