### ISSUE TITLE
azurerm_management_lock errors on creation

### ISSUE THREAD

**Issue by JulienPlantier** [terraform-providers/terraform-provider-azurerm#14495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.0.11
AzureRM provider 2.88.1

### Affected Resource(s)

* `azurerm_management_lock`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = true
}

terraform {
  required_version = ">= 1.0"
  required_providers {
    azurerm = {
      version = "~> 2.0"
      source  = "hashicorp/azurerm"
    }
  }
}

resource "azurerm_resource_group" "resourcegroup" {
  name     = "Test_lock_rg"
  location = "westeurope"
}

resource "azurerm_management_lock" "resourcegroup_delete_lock" {
  name       = "CanNotDelete"
  scope      = azurerm_resource_group.resourcegroup.id
  lock_level = "CanNotDelete"
}
```

### Expected Behaviour

Resource lock is created on the resource group and terraform exits successfully

### Actual Behaviour

Apply exits with an error on scope parsing :

```
│ Error: parsing "CanNotDelete": parsing scope prefix: unable to find the scope prefix from the value "CanNotDelete" with the regex "^((.){1,})/providers/Microsoft.Authorization/locks/(.){1,}"
│
│   with azurerm_management_lock.resourcegroup_delete_lock,
│   on test_rg.tf line 21, in resource "azurerm_management_lock" "resourcegroup_delete_lock":
│   21: resource "azurerm_management_lock" "resourcegroup_delete_lock" {
│
```
The lock is still created in Azure and all subsequent terraform plan fails with the same error.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by tombuildsstuff** [comment]
regression, this should be `.ID()` - https://github.com/hashicorp/terraform-provider-azurerm/blame/e4944d6be67d74bd324a518982ef9af1dd1a7d1c/internal/services/resource/management_lock_resource.go#L102

**Comment by JamieH-risual** [comment]
Temporary work around while we await a fix is to manually update the id field in your state file. The ID will be a concatenation of the scope + '/providers/Microsoft.Authorization/locks/' + your lock name. E.g. 

` "/subscriptions/********/resourceGroups/********/providers/Microsoft.Storage/storageAccounts/********/providers/Microsoft.Authorization/locks/sa-lock"`

**Comment by patrickjahns** [comment]
Related issue https://github.com/hashicorp/terraform-provider-azurerm/issues/14536

**Comment by mpjtaylor** [comment]
This doesn't seem to be fixed in 2.89

│ Error: parsing "virtual_machine_lock": parsing scope prefix: unable to find the scope prefix from the value "virtual_machine_lock" with the regex "^((.){1,})/providers/Microsoft.Authorization/locks/(.){1,}"

**Comment by patrickjahns** [comment]
@mpjtaylor 
Are you operating on a state that was created before the fix? 
The initial problem was, that the wrong attribute was written on the state. 
The Bugfix I wrote no writes the correct value for the is attribute on the state. If the state is still corrupt I suggest to remove the resource and re-inport it
```
terraform state rm <resource>
terraform import <resource> <id>
```
See https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_lock#import

**Comment by mpjtaylor** [comment]
Yes, this is the case, the state exists. I will look at whether we can import it
