### ISSUE TITLE
Role based permission Issue using Terrafrom

### ISSUE THREAD

**Issue by reddyed** [terraform-providers/terraform-provider-azurerm#1454]
I am using terraform script for creating role assignment and associating the AD group (principal id) with a resource group. First time when we are applying changes using terraform apply it works fine and when we do terraform plan, it shows all those roles to be recreated(force new resources). Following is the code we are using

```
resource 'azurerm_role_assignment' 'di-dev-shared-rg-Dev-Ops-Owner' {
scope = '${azurerm_resource_group.di-dev-shared-rg.id}'
role_definition_id = '${data.azurerm_builtin_role_definition.Owner.id}'
principal_id = 'xxxx-xxx-xxx-852b-xxxxxx'
}
```

and following is the message that we get when we do terraform plan after applying changes

```
-/+ azurerm_role_assignment.di-dev-shared-rg-Dev-Sec-Ops-Owner (new resource required)
id: '/subscriptions/xxxxx-xxx-41d9-xxxx-xxxx/resourceGroups/di-dev-shared-rg/providers/Microsoft.Authorization/roleAssignments/xxxxxx-xxx-xxx-xxxx-xxxxxxxxxx' => <computed> (forces new resource)
name: 'xxxxx-321e-xxxx-6bd1-xxxxxxx' => <computed>
principal_id: 'xxxxxxxxxx-axa82-xxxx-b69e-xxxxxxxx' => 'xxxx-xxx-4fc1-b69e-xxxx'
role_definition_id: '/subscriptions/ff70
xxxxxxx-xxxx-41d9-xxxx-xxxxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxxx-xxxx-xxx-xxx-xxxxxxxx' => '/providers/Microsoft.Authorization/roleDefinitions/xxxxxx-a8ff-xxx-xxx-xxxxxxx' (forces new resource)
scope: '/subscriptions/xxxxx-xxxx-xxxx-xxxxxxxx/resourceGroups/di-dev-shared-rg' => '/subscriptions/xxxxx-xxxx-xxxx-bf7d-xxxxxxxx/resourceGroups/di-dev-shared-rg'
```

I am using the following terraform versions
Terraform v0.11.7
+ provider.azurerm v1.7.0

**Comment by reddyed** [comment]
Any help with this issue will be appreciated.

**Comment by Leon99** [comment]
We observe the same behaviour. The scenario is extremely straightforward. Not sure why this is marked as **question**, it's clearly a bug.

**Comment by worldspawn** [comment]
I have a similar experience importing service bus namespace, service bus queues, topics and subscriptions. As well as storage tables and queues.

Immediately after import I then do a plan and get output like
```module.service_bus.azurerm_servicebus_topic.service_bus_topics[4] (new resource required)
      id:                                      "/subscriptions/54a0f177-752a-417d-994a-87ea280a839e/resourceGroups/env-staging-staging/providers/Microsoft.ServiceBus/namespaces/env-staging-staging/topics/v4-device-ratings" => <computed> (forces new resource)
      auto_delete_on_idle:                     "P10675199DT2H48M5.4775807S" => <computed>
      default_message_ttl:                     "P10675199DT2H48M5.4775807S" => <computed>
      duplicate_detection_history_time_window: "PT10M" => <computed>
      enable_batched_operations:               "true" => "true"
      enable_partitioning:                     "false" => "true" (forces new resource)
      max_size_in_megabytes:                   "5120" => "1024"
      name:                                    "v4-device-ratings" => "v4-device-ratings"
      namespace_name:                          "env-staging-staging" => "env-staging-staging"
      resource_group_name:                     "env-staging-staging" => "env-staging-staging"
      status:                                  "Active" => "Active"
      support_ordering:                        "true" => "false"```

In particular the id going from set to <computed> seems to force a new resource. I've compared tfstate between imported resources vs resources created by terraform and can't see how the id is different. As you can see there are other properties that have "changed" (note - didn't actually change).

**Comment by barker1889** [comment]
I've come across the same issues as @reddyed and @Leon99 today. If you take a look at the state file generated you'll see it's storing the `role_definition_id` property prefixed with the subscription id - it doesn't have this when you retrieve it from the `azurerm_builtin_role_definition` data source.

It should stop recreating it if you add the same prefix in your terraform script like this:

```
role_definition_id = '/subscriptions/${var.subscriptionId}/${data.azurerm_builtin_role_definition.Owner.id}'
```

However, after a bit of investigation I think a better solution is to use the `azurerm_role_definition` data source instead of the `azurerm_builtin_role_definition` data source. It get's scoped to the subscription id inline which makes the assignment cleaner:

```
data "azurerm_subscription" "primary" {}

# Retrieve the contributor role, scoped to our subscription
data "azurerm_role_definition" "contributor" {
    name  = "Contributor"
    scope = "${data.azurerm_subscription.primary.id}"
}

# Set the role definition to the id of the contributor data source
resource "azurerm_role_assignment" "vm_storage_contributor" {
  role_definition_id = "${data.azurerm_role_definition.contributor.id}"
  principal_id       = "{principal id of thing you're applying the role to}"
  scope              = "${azurerm_storage_account.mystorageaccount.id}"
}
```

**Comment by Leon99** [comment]
@barker1889 you're right, seems like they extended the functionality of
`azurerm_role_assignment` and deprecated `azurerm_builtin_role_definition` in the latest version of the provider. It now works correctly. Too bad it wasn't announced here :(
@tombuildsstuff what do you reckon is the best way to see changes in the provider's releases as they happen?

**Comment by tombuildsstuff** [comment]
@Leon99 all of these changes [are published in the changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md) :)

Reading through this, I believe if the `azurerm_role_definition` data source is being used then this is no longer an issue? Due to this and the fact that the older `azurerm_builtin_role_definition` data source is deprecated - I'm going to close this issue for the moment; however please let us know if that doesn't work for you and we'll take another look

Thanks!
