### ISSUE TITLE
Cosmos ip_range_filter argument broken after azurerm provider version 1.4

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1456]
### Terraform Version

Terraform v0.11.7
provider.azurerm v1.4.0

### Affected Resource(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
resource azurerm_cosmosdb_account "cdb" {
  name                = "${var.cdba_name}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  location            = "${azurerm_resource_group.rg.location}"
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"
  ip_range_filter     = "${var.vnet_address_space},1.2.3.4,5.6.7.8,9.1.4.7,8.3.6.9,8.2.5.4,0.0.0.0"
  depends_on          = ["azurerm_resource_group.rg"]

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  geo_location {
    location          = "${azurerm_resource_group.rg.location}"
    failover_priority = 0
  }
}
```

### Expected Behavior

The resource creates successfully

### Actual Behavior

When we upgraded from 1.4 to 1.7 of the provider, the ip_range_filter value started throwing the error below.  We tried reverting to version 1.6 but still got the same error.  Had to revert to 1.4 for it to create successfully again:

```hcl
Error: azurerm_cosmosdb_account.cdb: invalid value for ip_range_filter (Cosmos DB ip_range_filter must be a set of CIDR IP addresses separated by commas with no spaces: '10.0.0.1,10.0.0.2')
```
### Steps to Reproduce

Run terraform -plan with config using azurerm provider 1.6 or 1.7

**Comment by katbyte** [comment]
Hi @Phydeauxman,

What is the value you are passing into the `ip_range_filter`? is ${var.vnet_address_space} potentially empty some of the time leading to an empty element in the comma separated list?

**Comment by Phydeauxman** [comment]
@katbyte the value is `10.20.0.0/16`.  It is defined in my `variables.tf file`.  I can literally put the line `version = "1.4.0"` in my `main.tf` and it works fine.  Change that to `version = "1.6.0"` or `version = "1.7.0"`, run `terraform init`, and now `terraform plan` fails with the error I indicated.
