### ISSUE TITLE
Feature Request: Resource DocumentDb/CosmoDb

### ISSUE THREAD

**Issue by mjgpy3** [terraform-providers/terraform-provider-azurerm#147]
A pretty wicked ["globally distributed, multi-model database"](https://docs.microsoft.com/en-us/azure/cosmos-db/introduction). It would be neat to support it.

It's "multi-model-ness" appears to just mean that it namespaces other databases (e.g. DocumentDb, MongoDb, ...). Perhaps we can take "inspiration" from the AWS mongo resource or another to handle that child resource?

Personally my use-case is totally DocumentDb-specific but Mongo might be a good way to get the ball rolling.

**Comment by tombuildsstuff** [comment]
Hey @mjgpy3 

Thanks for opening this feature request :)

Support for CosmosDB Accounts was added recently in PR #108 - which shipped in [version 0.1.2 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#012-june-29-2017).

At this point this new split-out AzureRM Provider is only shipped with the Terraform 0.10-beta1 - so you'd either need to use the Terraform 0.10 beta, or the [`azurerm_template_deployment`](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html) resource in Terraform 0.9 in order take advantage of this functionality for the moment.

Thanks!

**Comment by mjgpy3** [comment]
@tombuildsstuff awesome, thank you very much! I should have looked at the source and not the online docs.
