### ISSUE TITLE
Documentation update : Application Security Groups is GA

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#1489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Application Security Groups is announced to be in Public Preview whereas it's GA, adding below few Terraform links where it's written to be in Public Preview : 
https://www.terraform.io/docs/providers/azurerm/r/network_interface.html
https://www.terraform.io/docs/providers/azurerm/d/application_security_group.html
https://www.terraform.io/docs/providers/azurerm/r/application_security_group.html

### New or Affected Resource(s)

* application_security_group

### References

* GA announcement : #https://azure.microsoft.com/en-us/blog/applicationsecuritygroups/

**Comment by straubt1** [comment]
<https://github.com/terraform-providers/terraform-provider-azurerm/pull/1490>
