### ISSUE TITLE
Could not get ip_configuration parameter with data resource azurerm_network_interface

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#1497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
provider.azurerm v1.8.0

### Affected Resource(s)

* Data Source: azurerm_network_interface 

### Terraform Configuration Files

```hcl
data "azurerm_network_interface" "nic" {
  name                = "vm-eth1"
  resource_group_name = "rg1"
}

output "nic_name" {
  value = "${data.azurerm_network_interface.nic.name}"
}

output "nic_ip_configuration" {
  value = "${data.azurerm_network_interface.nic.ip_configuration}"
}
```

### Expected Behavior

Display the variable ip_configuration

### Actual Behavior

Error: Error running plan: 1 error(s) occurred:

* output.nic_ip_configuration: Resource 'data.azurerm_network_interface.nic' does not have attribute 'ip_configuration' for variable 'data.azurerm_network_interfac
e.nic.ip_configuration'

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/azurerm/d/network_interface.html

**Comment by tombuildsstuff** [comment]
hey @JamesDLD 

Thanks for opening this issue :)

I've taken a look at the documentation for the Data Source and have seen that a few things are missing - as such I've opened #1504 which updates this to be correct (apologies about this!).

Looking at the code you've posted above, the `ip_configuration` field is a List - as such it can be accessed like so:

```
output "private_ip_address" {
  value = "${data.azurerm_network_interface.test.ip_configuration.0.private_ip_address}"
}
```

it's also possible to retrieve all values in the list via:

```
output "private_ip_addresses" {
  value = "${data.azurerm_network_interface.test.ip_configuration.*.private_ip_address}"
}
```

Would you be able to take a look and see if that solves your issue? Since this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue replying 😄)

Thanks!

**Comment by JamesDLD** [comment]
To go deeper it's appears that the "ip_configuration" object doesn't give us all the parameters that are asked at the creation.

For example it doesn't reply the "name" or the "subnet_id".

The following code : 
```hcl
data "azurerm_network_interface" "pan_setup_in_unstrust" {
  name                = "${var.PANName}${var.ZSEName}in1vm-eth1"
  resource_group_name = "${azurerm_template_deployment.pan_setup_in.0.resource_group_name}"
}

resource "azurerm_network_interface" "pan_setup_in_unstrust_nic1" {
  name                 = "${data.azurerm_network_interface.pan_setup_in_unstrust.name}"
  location             = "${data.azurerm_network_interface.pan_setup_in_unstrust.location}"
  resource_group_name  = "${data.azurerm_network_interface.pan_setup_in_unstrust.resource_group_name}"
  enable_ip_forwarding = "${data.azurerm_network_interface.pan_setup_in_unstrust.enable_ip_forwarding}"

  ip_configuration {
    name                                    = "${data.azurerm_network_interface.pan_setup_in_unstrust.ip_configuration.0.name}"
    subnet_id                               = "${data.azurerm_network_interface.pan_setup_in_unstrust.ip_configuration.0.subnet_id}"
    private_ip_address_allocation           = "Dynamic"                                                                                                        
  }

  tags = "${data.azurerm_network_interface.pan_setup_in_unstrust.tags}"
}

```

Reverts the following error : 
```hcl

Error: Error running plan: 1 error(s) occurred:

* azurerm_network_interface.pan_setup_in_unstrust_nic1: 1 error(s) occurred:

* azurerm_network_interface.pan_setup_in_unstrust_nic1: Resource 'data.azurerm_network_interface.pan_setup_in_unstrust' does not have attribute 'ip_configuratio
n.0.name' for variable 'data.azurerm_network_interface.pan_setup_in_unstrust.ip_configuration.0.name'


```
