### ISSUE TITLE
AzureRM Appservice Plan fails to refresh after import

### ISSUE THREAD

**Issue by pfiene** [terraform-providers/terraform-provider-azurerm#1507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
C:\Terraform\swk>terraform version
Terraform v0.11.7
+ provider.azurerm v1.8.0

### Affected Resource(s)
* azurerm_app_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "testapp" {
  name                = "testapp1234567"
  location            = "westeurope"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  kind                = "App"

  sku {
    tier = "Standard"
    size = "S1"
  }
}

```

### Expected Behavior

after performing terraform Import the resource should not be changed

### Actual Behavior

a new resource is created because multiple fields are empty

```
-/+ azurerm_app_service_plan.testapp (new resource required)
      id:                               "/subscriptions/603270d0-b196-42e0-a2f0-954087d4037c/resourceGroups/xxxxxx/providers/Microsoft.Web/serverFarms/testapp1234567" => <computed> (forces new resource)
      kind:                             "" => "App" (forces new resource)
      location:                         "" => "westeurope" (forces new resource)
      maximum_number_of_workers:        "" => <computed>
      name:                             "" => "testapp1234567" (forces new resource)
      properties.#:                     "" => <computed>
      resource_group_name:              "XXXXXX" => "XXXXXX"
      sku.#:                            "" => "1"
      sku.0.capacity:                   "" => <computed>
      sku.0.size:                       "" => "S1"
      sku.0.tier:                       "" => "Standard"
      tags.%:                           "0" => <computed>
```
### Steps to Reproduce

1. `terraform import`
1. `terraform apply`

**Comment by brianpcurran** [comment]
Oh fun, it looks like an issue with case sensitivity. For the unsuccessful import, I had copied the resource ID of the ASP from the Azure portal. For the successful import, I copied the resource ID from the Terraform azurerm_app_service_plan documentation. Notice `serverFarms` vs `serverfarms`. I was able to successfully import both by using `serverfarms`.

**Comment by jnancel** [comment]
Works like a charm with `serverfarms` ( all lowercase ). You're a life savior @brianpcurran 👍

**Comment by tombuildsstuff** [comment]
hey @pfiene @jnancel 

Glad to hear this has been resolved - as such I'm going to close this issue for the moment.

For other users running into this issue - Resource ID's are case-sensitive in Terraform - as such please ensure the casing on the `serverfarms` segment of the ID is in the correct casing, which will resolve this issue - for example from [the App Service Plan Documentation](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#import):

```
$ terraform import azurerm_app_service_plan.instance1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Web/serverfarms/instance1
```

Thanks!

**Comment by ChethanRavulaGit** [comment]
Creating App Service Plan with ASE is taking 40 minutes to finish. Some times returns 500 - internal server error. 
Do we know if this known issue deploying app service plan with ASE?
