### ISSUE TITLE
app_service IP Restrictions from a list

### ISSUE THREAD

**Issue by istairbn** [terraform-providers/terraform-provider-azurerm#1518]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Following on from #1157, currently each ip_restriction has to be an individual block. 

This means white-listing a large number of client IPs is a pain, not to mention that passing it through to a module is almost impossible. 

Could it be upgraded to accept a list of IP ranges - would allow us to dynamically generate from outbound as per @perbergland's suggestion

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

ip_restrictions = ["IP1","IP2"]

**Comment by perbergland** [comment]
The kludge I currently use is to concatenate an input list of IPs with a list of unusable (reserved) ips in the 239.0.0.x range, i.e.

```
variable "whitelistedIPs" {
  type = "list" # of maps with name|fromip|toip

  default = [
    {
      name   = "office"
      fromip = "10.1.1.1"
      toip   = "10.1.1.1"
    },
    {
      name   = "other-office"
      fromip = "10.1.2.2"
      toip   = "10.1.2.2"
    },
  ]
}

data "template_file" "whitelisted_external_ip_ranges" {
  count    = "${length(var.whitelistedIPs)}"
  template = "$${ip_address},255.255.255.255"      # only support values where fromip = toip

  vars {
    ip_address = "${lookup(var.whitelistedIPs[count.index],"fromip")}"
  }
}

data "template_file" "unused_ip_ranges_for_padding" {
  count    = 10
  template = "239.0.0.${count.index},255.255.255.255" # 239.0.0.x are unused
}

# Locals allow us to created derived values from variables
locals {
  numWhitelistedIPs = "${length(var.whitelistedIPs)}"

  # We mustn't repeat the same IP address in IP filtering so pad the list with unique but unused IP addresses
  whitelisted_external_ips_with_mask = "${concat(data.template_file.whitelisted_external_ip_ranges.*.rendered,data.template_file.unused_ip_ranges_for_padding.*.rendered)}"
}
```
and then I just create enough IP filter sections to allow for enough items to be added to the whitelistedIPs list

```
site_config {
    dotnet_framework_version = "v4.0"
    always_on                = true

    ip_restriction {
      ip_address  = "${element(split(",",element(local.whitelisted_external_ips_with_mask,0)),0)}"
      subnet_mask = "${element(split(",",element(local.whitelisted_external_ips_with_mask,0)),1)}"
    }

    ip_restriction {
      ip_address  = "${element(split(",",element(local.whitelisted_external_ips_with_mask,1)),0)}"
      subnet_mask = "${element(split(",",element(local.whitelisted_external_ips_with_mask,1)),1)}"
    }

# etc.
```

**Comment by tombuildsstuff** [comment]
@ddarwent I _believe_ that should be the case - however @apparentlymart should be able to confirm

**Comment by DinoSourcesRex** [comment]
It would be useful to add an example to the documentation on how this would be done as well, as part of the same PR.

Currently each app service returns a comma separated string with all the ip's that are associated to it. It would be useful to be able to re-use that comma separated string when doing ip restriction.

e.g.
I provision `app_service_foo`, and `app_service_bar`.

I want to be able to set `app_service_bar.ip_restriction` to equal `app_service_foo.outbound_ip_addresses`.

**Comment by tombuildsstuff** [comment]
@Phydeauxman yes - however the key is [`ip_restriction`](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#ip_restriction) within the `site_config` block - there's an example of how to use this [in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1518#issuecomment-403527219)

---

Based on [this comment](XXX
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1518#issuecomment-419379502) - I believe this issue should be fixed by the new `for_each` syntax coming in Terraform 0.12 - as such I'm going to close this issue for the moment.

Thanks!
