### ISSUE TITLE
New Feature Request - Network Security Group Diagnostic Logs

### ISSUE THREAD

**Issue by whytoe** [terraform-providers/terraform-provider-azurerm#1521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The ability to configure Network Security Logging to either a storage account or Log Analytics resource
There could be 1 of 3 optional endpoints for the logging data

>Storage Account
>Event Hub
>Log Analytics

### New or Affected Resource(s)

* azurerm_network_security_group

### Potential Terraform Configuration

```hcl
diagnostic_settings {
  workspace_name  = "${var.workspace_name}
  network_security_group_event = "true"
  network_security_group_rule_counter = "true"
 }
```
![image](https://user-images.githubusercontent.com/12265878/42475781-abe528e4-8399-11e8-9629-9f7ed5f3a30a.png)

### References

https://github.com/Azure/azure-sdk-for-go/blob/master/services/monitor/mgmt/2017-05-01-preview/insights/diagnosticsettings.go

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-nsg-manage-log

* #0000

**Comment by tombuildsstuff** [comment]
hey @whytoe 

Thanks for opening this issue :)

Support for the Diagnostic Settings resource has previously been requested in https://github.com/terraform-providers/terraform-provider-azurerm/issues/657 which I'm going to close this issue in favour of.

Thanks!
