### ISSUE TITLE
Documentation problem: VMSS & MSI

### ISSUE THREAD

**Issue by Supermathie** [terraform-providers/terraform-provider-azurerm#1539]
The documentation on https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html has incorrect sample code for the `identity` block:

```hcl
resource "azurerm_virtual_machine_scale_set" "test" {
  name                = "vm-scaleset"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  …
  output "principal_id" {
    value = "${lookup(azurerm_virtual_machine.test.identity[0], "principal_id")}"
  }
```

There's two problems:

* should be `azurerm_virtual_machine_scale_set` not `azurerm_virtual_machine`
* output block should be outside of the resource block

**Comment by tombuildsstuff** [comment]
hey @Supermathie 

Thanks for opening this issue - I've opened #1549 which includes a fix for this :)

Thanks!
