### ISSUE TITLE
Conditionals for application gateway backend pools

### ISSUE THREAD

**Issue by PleaseStopAsking** [terraform-providers/terraform-provider-azurerm#1542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful if there was a way to conditionally create certain arguments when using the application gateway resource. Specifically, I would like to be able to create additional ```backend_address_pool```, ```probe```, ```backend_http_settings ``` and ```path_rule``` based on a true/false variable that I am also using to conditionally deploy extra servers behind the application gateway.

### New or Affected Resource(s)

azurerm_application_gateway

### Potential Terraform Configuration
```hcl
resource "azurerm_application_gateway" "appGateway" {
 ...

  backend_address_pool {
    count = "${var.deployInfo["enableExtraServers"] == "true" ? 1 : 0}"
    name = "${var.extraServers["name"]}"
    ip_address_list = ["${var.extraServers["ip_address_list"]}"]
  }

  probe {
    count = "${var.deployInfo["enableExtraServers"] == "true" ? 1 : 0}"
    name = "${var.extraServers["name"]}"
    protocol = "Https"
    path = "${var.extraServers["healthCheckPath"]}"
    host = "127.0.0.1"
    interval  = 30
    timeout = 30
    unhealthy_threshold = 3
  }

  backend_http_settings {
    count = "${var.deployInfo["enableExtraServers"] == "true" ? 1 : 0}"
    name = "${var.extraServers["name"]}"
    cookie_based_affinity = "Disabled"
    port = 443
    protocol = "Https"
    request_timeout = 20
    probe_name = "${var.extraServers["name"]}"
    }
  }

  url_path_map {
    ...

    path_rule {
      count = "${var.deployInfo["enableExtraServers"] == "true" ? 1 : 0}"
      name = "${var.extraServers["name"]}"
      backend_address_pool_name = "${var.extraServers["name"]}"
      backend_http_settings_name = "${var.extraServers["name"]}"
      paths = ["/${var.extraServers["path"]}/*"]
    }
  }
}
```
### References

**Comment by tombuildsstuff** [comment]
hi @PleaseStopAsking 

Thanks for opening this issue :)

Whilst this isn't possible today using Terraform 0.11 - I believe this may be possible with [some of the changes coming in Terraform 0.12](https://www.hashicorp.com/blog/terraform-0-1-2-preview) later this summer (although using lists/the `for_each` attribute on nested resources vs the `count` attribute). The other option we're looking into here is if we can split this resource out as we have for the Load Balancer resource to create multiple resources - the API doesn't currently allow for this however [there's an issue tracking this Feature Request here](https://github.com/Azure/azure-rest-api-specs/issues/2313) after which time this may be possible.

It's worth noting that we're currently blocked on [an upstream issue in the Azure API](https://github.com/Azure/azure-rest-api-specs/issues/2187) that means we're holding off on enhancements to the Application Gateway resource; we're tracking that on our side in #1576 which I'm going to close this in favour of to allow us to keep track of this in a single place.

Thanks!
