### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by alex0ptr** [terraform-providers/terraform-provider-azurerm#1547]
Sorry not sure where to put it.

The Azure Documentation contains a typo for the azure sql database resource. The attribute `creation_data` is not available as attribute, instead its name is `creation_date`.

https://www.terraform.io/docs/providers/azurerm/r/sql_database.html#creation_data

**Comment by tombuildsstuff** [comment]
hey @alex0ptr 

Thanks for opening this issue - I've opened #1548 which includes a fix for this :)

Thanks!
