### ISSUE TITLE
Terraform doesn't dissociate the Public IP address before deleting it and deletion fails

### ISSUE THREAD

**Issue by boysaurel** [terraform-providers/terraform-provider-azurerm#15483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.6

+ provider registry.terraform.io/hashicorp/azurerm v2.96.0

### Affected Resource(s)

*azurerm_network_interface
*azurerm_public_ip

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "test-ip" {
  name                = "test-ip"
  resource_group_name = azurerm_resource_group.ip-test.name
  location            = azurerm_resource_group.ip-test.location
  allocation_method = "Static"
}

resource "azurerm_network_interface" "test-nic" {
  name                 = "test-nic"
  resource_group_name = azurerm_resource_group.ip-test.name
  location            = azurerm_resource_group.ip-test.location
  enable_ip_forwarding = true

  ip_configuration {
    name                          = "test-nic-config"
    subnet_id                     = azurerm_subnet.ip-test-subnet.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id = azurerm_public_ip.test-ip.id
  }
}
```

### Expected Behaviour

Terraform should:

1. Dissociate Public IP
2. Delete Public IP resource.

```
Terraform will perform the following actions:

  # azurerm_network_interface.test-nic will be updated in-place
  ~ resource "azurerm_network_interface" "test-nic" {
        id                            = "********resourceGroups/ip-test/providers/Microsoft.Network/networkInterfaces/test-nic"
        name                          = "test-nic"
        tags                          = {}
        # (11 unchanged attributes hidden)

      ~ ip_configuration {
            name                          = "test-nic-config"
          - public_ip_address_id          = "*******r/esourceGroups/ip-test/providers/Microsoft.Network/publicIPAddresses/test-ip" -> null
            # (5 unchanged attributes hidden)
        }
    }

  # azurerm_public_ip.test-ip will be destroyed
  # (because azurerm_public_ip.test-ip is not in configuration)
  - resource "azurerm_public_ip" "test-ip" {
      - allocation_method       = "Static" -> null
      - availability_zone       = "No-Zone" -> null
      - id                      = "/****resourceGroups/ip-test/providers/Microsoft.Network/publicIPAddresses/test-ip" -> null
      - idle_timeout_in_minutes = 4 -> null
      - ip_address              = "52.147.207.202" -> null
      - ip_tags                 = {} -> null
      - ip_version              = "IPv4" -> null
      - location                = "eastus" -> null
      - name                    = "test-ip" -> null
      - resource_group_name     = "ip-test" -> null
      - sku                     = "Basic" -> null
      - sku_tier                = "Regional" -> null
      - tags                    = {} -> null
      - zones                   = [] -> null
    }
```

### Actual Behaviour

It seems that Terraform tries to delete the Public IP in first place before doing the dissociation and it fails.
```
Enter a value: yes

azurerm_public_ip.test-ip: Destroying... [/********/ip-test/providers/Microsoft.Network/publicIPAddresses/test-ip]
╷
│ Error: deleting Public Ip Address: (Name "test-ip" / Resource Group "ip-test"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /********ip-test/providers/Microsoft.Network/publicIPAddresses/test-ip can not be deleted since it is still allocated to resource /********ip-test/providers/Microsoft.Network/networkInterfaces/test-nic/ipConfigurations/test-nic-config. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This issue was supposedly fixed by https://github.com/hashicorp/terraform-provider-azurerm/issues/2566

### References

* #2566

**Comment by sinbai** [comment]
@boysaurel thank you for opening this issue. Could you add the lifecycle in azurerm_public_ip(added when creating) and try like so:


```
resource "azurerm_public_ip" "test-ip" {
  name                = "test-ip"
  resource_group_name = azurerm_resource_group.ip-test.name
  location            = azurerm_resource_group.ip-test.location
  allocation_method = "Static"
  lifecycle {
      create_before_destroy = true
  }
}
```

**Comment by boysaurel** [comment]
@sinbai Thank you for your reply. I have recreated the structure with the public ip block as below:

```
resource "azurerm_public_ip" "test-ip" {
  name                = "test-ip"
  resource_group_name = azurerm_resource_group.ip-test.name
  location            = azurerm_resource_group.ip-test.location
  allocation_method = "Static"
  lifecycle {
      create_before_destroy = true
  }
}
```

However, after trying to delete only the public ip, I'm getting the below error when trying to run apply:

```
│ Error: Reference to undeclared resource
│
│   on phoenix-rc-data.tf line 53, in resource "azurerm_network_interface" "test-nic":
│   53:     public_ip_address_id = azurerm_public_ip.test-ip.id
│
│ A managed resource "azurerm_public_ip" "test-ip" has not been declared in the root module.
```

**Comment by sinbai** [comment]
> @sinbai Thank you for your reply. I have recreated the structure with the public ip block as below:
> 
> ```
> resource "azurerm_public_ip" "test-ip" {
>   name                = "test-ip"
>   resource_group_name = azurerm_resource_group.ip-test.name
>   location            = azurerm_resource_group.ip-test.location
>   allocation_method = "Static"
>   lifecycle {
>       create_before_destroy = true
>   }
> }
> ```
> 
> However, after trying to delete only the public ip, I'm getting the below error when trying to run apply:
> 
> ```
> │ Error: Reference to undeclared resource
> │
> │   on phoenix-rc-data.tf line 53, in resource "azurerm_network_interface" "test-nic":
> │   53:     public_ip_address_id = azurerm_public_ip.test-ip.id
> │
> │ A managed resource "azurerm_public_ip" "test-ip" has not been declared in the root module.
> ```

This is the expected result since an undefined resource is referenced.

**Comment by boysaurel** [comment]
@sinbai I forgot to remove the reference from the NIC, after removing it, the public ip gets destroyed as expected.

In my opinion this could be added to the [public ip documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip).
