### ISSUE TITLE
Cannot put a lock at resource level with azurerm_management_lock

### ISSUE THREAD

**Issue by progreswing** [terraform-providers/terraform-provider-azurerm#1550]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.9.0
+ provider.random v1.3.1

### Affected Resource(s)

* azurerm_management_lock

### Terraform Configuration Files
```hcl
resource "azurerm_management_lock" "container_lock" {
  name       = "resource-storage-container-lock"
  scope      = "${azurerm_storage_container.storage_container.id}"
  lock_level = "CanNotDelete"
  notes      = "Locked because it contains lots of data"
}
```

### Debug Output Sample

[DEBUG] plugin.terraform-provider-azurerm_v1.9.0_x4
[DEBUG] AzureRM Response for https://management.azure.com/{storage_id}/providers/Microsoft.Authorization/locks/resource-storage-container-lock?api-version=2016-09-01:
[DEBUG] plugin.terraform-provider-azurerm_v1.9.0_x4: HTTP/1.1 404 Not Found
...
[ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* azurerm_management_lock.container_lock: locks.ManagementLocksClient#CreateOrUpdateByScope: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="MissingSubscription" Message="The request did not have a provided subscription. All requests must have an associated subscription Id."

### Expected Behavior

PUT https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}/providers/Microsoft.Authorization/locks/{lockName}?api-version=2016-09-01

### Actual Behavior

PUT https://management.azure.com/{scope}/providers/Microsoft.Authorization/locks/{lock-name}?api-version={api-version}

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-lock-resources

Obsolete REST API usage 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-lock-resources
```
PUT https://management.azure.com/{scope}/providers/Microsoft.Authorization/locks/{lock-name}?api-version={api-version}
```

Current REST API usage 
https://docs.microsoft.com/fr-fr/rest/api/resources/managementlocks/createorupdateatresourcelevel
```
PUT https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}/providers/Microsoft.Authorization/locks/{lockName}?api-version=2016-09-01```

**Comment by tombuildsstuff** [comment]
hi @progreswing 

Thanks for opening this issue :)

Taking a look into this - the ID of the Storage Container in Terraform is the name of the Storage Container (since that's how it's accessed within a Storage Account) - rather than what's needed in this case of a full Resource ID. From what I can tell I believe the Lock can be applied at a Storage Account level rather than a Storage Container within a Storage Account - would you be able to take a look and see if applying it there solves your issue?

Thanks!

**Comment by progreswing** [comment]
hello @tombuildsstuff 

My bad, it works indeed perfectly well targeting an upper level, the Storage Account, rather than the Storage Container.

Issue solved, thanks

**Comment by tombuildsstuff** [comment]
@progreswing glad to hear it's now working for you 👍
