### ISSUE TITLE
Support for Automation Variable

### ISSUE THREAD

**Issue by cdeli** [terraform-providers/terraform-provider-azurerm#1551]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the Azure Automation Variable for both data reference and creation. Many times I have needed to capture the primary/secondary keys of an item or URL path and store it someplace temporariy, unfortunately this is not possible to do the easy way due to Azure Automation Variables not being supported at this time.

### New or Affected Resource(s)

* azurerm_automation > azurerm_automation_variable

### Potential Terraform Configuration

https://docs.microsoft.com/en-us/azure/automation/automation-variables

**Comment by tombuildsstuff** [comment]
hey @cdeli 

Thanks for opening this issue :)

Support for Automation Variables has previously been requested in #1312 - so that we don't have multiple issues open tracking the same thing I'm going to close this issue in favour of #1312.

Thanks!
