### ISSUE TITLE
Support for CreateOption.Attach in newer virtual machine resources

### ISSUE THREAD

**Issue by horvatal** [terraform-providers/terraform-provider-azurerm#15513]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The new virtual machine resources does not support the _CreateOption.Attach_. I created a VM with ZRS OS disk in zone 1 and destroyed it (with `delete_os_disk_on_deletion = false`) leaving the OS disk intact. But I could not create a new VM in zone 2 with the existing OS disk:
```bash
azurerm_windows_virtual_machine.vm: Creating...
╷
│ Error: creating Windows Virtual Machine: (Name "zrs-vm" / Resource Group "ach-ccoe-dr-test"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ConflictingUserInput" Message="Disk zrs-vm-os-disk already exists in resource group ACH-CCOE-DR-TEST. Only CreateOption.Attach is supported." Target="/subscriptions/fda892b2-7af7-447f-ab15-c06669c056b1/resourceGroups/ach-ccoe-dr-test/providers/Microsoft.Compute/disks/zrs-vm-os-disk"
```
CreateOption is supported in the deprecated `azurerm_virtual_machine`. Please support it also in the newer resources `azurerm_windows_virtual_machine` and `azurerm_linux_virtual_machine`. The use case here an availability zone outage, where I have to force delete the VM and create it in another healthy zone in the same region.

### New or Affected Resource(s)
* azurerm_windows_virtual_machine
* azurerm_linux_virtual_machine

### Potential Terraform Configuration
```hcl
resource "azurerm_windows_virtual_machine" "vm" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.nic.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    managed_disk_id      = azurerm_managed_disk.osdisk.id
    create_option        = "Attach"
  }
```
I do not know if we can take `azurerm_managed_disk` here or another new resource is needed.

### References
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#create_option
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#managed_disk_id

**Comment by horvatal** [comment]
I think https://github.com/hashicorp/terraform-provider-azurerm/issues/6117 is about attaching data disks (azurerm_virtual_machine_data_disk_attachment) which is also missing in the new azurerm_windows_virtual_machine resource. My request is related to attach OS disk at VM creation phase, like this sample: https://github.com/Azure-Samples/azure-cli-samples/blob/master/virtual-machine/create-vm-attach-existing-managed-os-disk/create-vm-attach-existing-managed-os-disk.sh

**Comment by horvatal** [comment]
@tombuildsstuff did you read my comment above? Can you reopen the ticket please?

**Comment by tombuildsstuff** [comment]
@horvatal apologies, I meant to link #8195
