### ISSUE TITLE
Feature Request: Allow to set static_ip and subnet in azurerm_redis_cache

### ISSUE THREAD

**Issue by snebel29** [terraform-providers/terraform-provider-azurerm#156]
Hi,
According to Azure documentation it's possible to deploy to an specific subnet when choosing the Premium family
https://docs.microsoft.com/en-us/azure/redis-cache/cache-premium-tier-intro

Confirmed by the Azure CLI tool
https://docs.microsoft.com/en-us/cli/azure/redis#create

However Terraform does not allow this, at least is not present within the argument reference section
https://www.terraform.io/docs/providers/azurerm/r/redis_cache.html

### Terraform Version
v0.9.10

### Affected Resource(s)
azurerm_redis_cache

Would be nice to add that, I guess this should be relatively effortless to add

**Comment by tombuildsstuff** [comment]
Hey @snebel29 

Thanks for opening this issue :)

Support for Internal Redis Clusters has been requested previously in Issue #82 - as such I'm going to close this issue in favour of that one. The work to enable this is mostly done, we're just waiting on a bug in Azure to be fixed before we can send a PR and ship support for this - I'd recommend subscribing to the other thread for updates :)

Thanks!

**Comment by snebel29** [comment]
Sorry for that, will check the issues list better next time :-)
