### ISSUE TITLE
azurerm_azuread_application fails with error 403: Authorization_RequestDenied

### ISSUE THREAD

**Issue by lordgordon** [terraform-providers/terraform-provider-azurerm#1580]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.9.0
```

### Affected Resource(s)

* azurerm_azuread_application

### Terraform Configuration Files

```hcl
resource "azurerm_azuread_application" "test" {
  name                       = "test"
  homepage                   = "https://myendpoint.com"
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = false
}
```

### Expected Behavior

Being able to create the resource.

### Actual Behavior

Azure returns the following error:

```
* azurerm_azuread_application.test: 
graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- 
Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" 
Message="Unknown service error" Details=[{"odata.error":
{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient 
privileges to complete the operation."}}}]
```

### Important Factoids

I have only one subscription and I'm authenticated with `az login --service-principal` with an  user having `owner` role to the main subscription. The Terraform app has "owner" role itself on the mian subscription.

**Comment by lordgordon** [comment]
My fault, I was not using a Service Principal login.

**Comment by tombuildsstuff** [comment]
hi @lordgordon 

Thanks for opening this issue

> I have only one subscription and I'm authenticated with az login --service-principal with an user having owner role to the main subscription. The Terraform app has "owner" role itself on the mian subscription.

Terraform doesn't support authenticating using a Service Principal via the Azure CLI; you need to instead specify the credentials either through Environment Variables or in the Provider block.

In addition [as listed on the `azurerm_azuread_application` page](https://www.terraform.io/docs/providers/azurerm/r/azuread_application.html) - the Service Principal being used needs to have the appropriate permissions to Azure Active Directory (which is unrelated to the Azure Subscription):

> NOTE: If you're authenticating using a Service Principal then it must have permissions to both Read and write all applications and Sign in and read user profile within the Windows Azure Active Directory API.

Thanks!

**Comment by kautsig** [comment]
Thanks @tombuildsstuff! 

I guess that answers my question as well. Apologies for not checking the manual first.

**Comment by cdesewell** [comment]
For anyone finding this issue now, you need to grant these permissions to the **legacy** active directory graph API not the new one.
