### ISSUE TITLE
data source: azurerm_activedirectory_{user,group,sp}

### ISSUE THREAD

**Issue by Supermathie** [terraform-providers/terraform-provider-azurerm#1583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I need to be able to look up attributes of users, groups and SPs in Azure Active Directory.

The specific use case here is to be able to use the object_id in azurerm_key_vault_access_policy

### New or Affected Resource(s)

* azurerm_activedirectory_user

### Potential Terraform Configuration

```hcl
data "azurerm_activedirectory_user" "michael" {
  name = "michael"
}

data "azurerm_activedirectory_group" "people" {
  display_name = "Tall People"
}

resource "azurerm_key_vault_access_policy" "michael" {
  vault_name = "${azurerm_key_vault.top.name}"
  resource_group_name = "${azurerm_resource_group.top.name}"

  tenant_id = "xxxx-xxxx-xxxx-xxxx-xxxx" // our tenant ID
  object_id = "${data.azurerm_activedirectory_user.michael.id}"
  …
}
```

### References

* https://www.terraform.io/docs/providers/azurerm/r/key_vault_access_policy.html

**Comment by tombuildsstuff** [comment]
hey @Supermathie 

Thanks for opening this issue :)

Support for AzureAD Users and Groups has previously been requested in #1272; so that we don't have multiple issues open tracking the same thing I'm going to close this issue in favour of #1272.

Thanks!
