### ISSUE TITLE
IP Address Inconsistencies When Deploying AKS using Terraform

### ISSUE THREAD

**Issue by metazog** [terraform-providers/terraform-provider-azurerm#1596]
When deploying AKS using Terraform (v1.7.0 and 1.9.0) the can be some inconsistencies related to IP addresses of the pods.

The IP addresses are a mixture of the range they specified when creating the cluster and the default 10.244.x.0 range. This causes connectivity problems.

This results from the network plugin not being specified in the network profile.

Since no --network-plugin is specified, it will default to use Kubenet, and in the Kubenet case, node will get IPs from the input subnet, which is something like 10.4.x.x/y but pods will get IPs from some CIDR called pod CIDR. Since there is also no pod CIDR specified, the default one, which is 10.244.0.0/16 will be used.

You will see some pods are in the 10.4.x.x range and others are 10.244.x.x.

**Comment by tombuildsstuff** [comment]
hey @metazog 

Thanks for opening this issue :)

Support for Network Profiles isn't available in Terraform just yet - however there's an issue requesting it #1434 (which I'm going to close this in favour of) - and a PR which with add support for this in #1479. That PR's currently blocked on a bug in the Azure SDK to be fixed, but when that's done we should be able to run the tests and ship this feature :)

Thanks!
