### ISSUE TITLE
Feature Request: Add Log Analytics Workspace to AKS cluster

### ISSUE THREAD

**Issue by wesback** [terraform-providers/terraform-provider-azurerm#1599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS now allows you to attach a Log Analytics Workspace in order to monitor container health and capture logs.  I can't seem to find the parameter to do this in Terraform.

### New or Affected Resource(s)
azurerm_kubernetes_cluster 

### Potential Terraform Configuration

'resource "azurerm_kubernetes_cluster" "aksCluster" {
  name                = "my-aks-weu-dev"
  log_analytics_workspace = "${azurerm_log_analytics_workspace.mylogananlyticsworkspace.id}"
  ..."'

**Comment by tombuildsstuff** [comment]
hi @wesback 

Thanks for opening this issue :)

Log Analytics Workspaces are configured as an add-on within the AKS Cluster - support for this functionality is being tracked in 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1434 which I'm going to close this issue in favour of.

Thanks!

**Comment by wesback** [comment]
Thanks Tom.  Missed that one but makes total sense to track in a single issue.
