### ISSUE TITLE
azurerm_data_lake_store add "Enable Firewall" option

### ISSUE THREAD

**Issue by junbug178** [terraform-providers/terraform-provider-azurerm#1603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Although we can create the ip rules to add to the firewall, there is not an option to enable firewall.  Thus, adding ip addresses to the firewall does virtually nothing as the firewall is "off".

This is my first time submitting a request so I apologize in advance if I didn't get all of the information required.

### New or Affected Resource(s)

azurerm_data_lake_store
azurerm_data_lake_store_firewall_rule

**Comment by tombuildsstuff** [comment]
appears there's a FirewallState which can be set at the Data Lake Store level which can be used to set this

**Comment by tombuildsstuff** [comment]
I'm bundling this up with #1623
