### ISSUE TITLE
Feature Request: IOT Hub

### ISSUE THREAD

**Issue by mooperd** [terraform-providers/terraform-provider-azurerm#162]
Is there any plan to provide support for the IOT Hub?

**Comment by tombuildsstuff** [comment]
hey @mooperd 

Just to let you know that initial support for [IotHubs was added to Terraform in v1.3.1](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.3.1/CHANGELOG.md#131-march-29-2018) which [is now available on the Terraform Website](https://www.terraform.io/docs/providers/azurerm/r/iothub.html)

Thanks!
