### ISSUE TITLE
Network Security Group Rule support for Azure Service Tags

### ISSUE THREAD

**Issue by paulschwarzenberger** [terraform-providers/terraform-provider-azurerm#1629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Set Azure Service Tags in Network Security Group Rule, e.g. Destination "Service Tag", Destination service tag "Sql.WestEurope" 

See attached screenshot of example rule configured manually
![image](https://user-images.githubusercontent.com/26303407/43074886-c25d1518-8e76-11e8-93ab-732306587f18.png)

### New or Affected Resource(s)

azurerm_network_security_rule

### Potential Terraform Configuration

new  arguments "destination_service_tags", type list and "source_service_tags", type list

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @paulschwarzenberger 

Thanks for opening this issue :)

Taking a quick look into this it appears support for Service Tags isn't available [in the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) at the moment. Once it's available we can investigate adding support for this - for the moment I'll tag this as `upstream-microsoft` since we're waiting on the SDK :)

Thanks!

**Comment by paulschwarzenberger** [comment]
Hi @tombuildsstuff thanks for your quick response. 

I see version [19.1.0](https://github.com/Azure/azure-sdk-for-go/releases) of the Azure SDK for Go has recently been released, which includes new Network and Security APIs.

Do these include the ability to set service tags in NSG rules?

**Comment by ranokarno** [comment]
I also encounter issue and hopefully new feature can be supported.
I wonder why service tag "internet' can be applied but not for specific "storage.EastAsia" or "sql.xxx"

**Comment by paulschwarzenberger** [comment]
Thank you! When I tested before, I used:
``
destination_address_prefixes  = ["Sql.WestEurope"]
``
This errors on terraform apply, saying the only allowed tags are Internet, VirtualNetwork and LoadBalancers. 

However, when I change it to:
``
destination_address_prefix    = "Sql.WestEurope"
``
it does work.

If this is supported, it would be useful to update the documentation.

**Comment by a138076** [comment]
Still an issue, and quite a big hinderance to the use of this NSG capability. When following the above comments the NSG Rule is created but not configured properly. Creating an NSG with the below code:
`resource "azurerm_network_security_rule" "storage" {
  name                        = "Storage"
  priority                    = "101"
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "*"
  destination_address_prefix  = "Storage.AustraliaEast"
  source_address_prefix       = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  resource_group_name         = "${local.resource_group_name}"
  network_security_group_name = "amls-nsg"
}
`
Leads to the below configuration of an NSG which doesn't match
![image](https://user-images.githubusercontent.com/41881046/60264000-7e1a4000-9925-11e9-8b00-12f16f3bfb6c.png)

**Comment by paulschwarzenberger** [comment]
Service tag NSG rules in Azure are generally outbound - does it work if you change the direction in Terraform to outbound?

**Comment by a138076** [comment]
Thanks @paulschwarzenberger realised my silly mistake

**Comment by paulschwarzenberger** [comment]
No problem, I've done the same thing myself more than once!

**Comment by neil-yechenwei** [comment]
Hopes this [PR ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7659) would be helpful.
