### ISSUE TITLE
azurerm_servicebus_subscription does not create where the topic name contains ~

### ISSUE THREAD

**Issue by spittwood** [terraform-providers/terraform-provider-azurerm#1638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.10.0

### Affected Resource(s)

azurerm_servicebus_subscription

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_topic" "topic_newsalesorder" {
  name                = "ordermanagement~v1~newsalesorder"
  resource_group_name = "${azurerm_resource_group.rg_integration.name}"
  namespace_name      = "${azurerm_servicebus_namespace.sb_integration.name}"

  enable_partitioning = false
  enable_express = false
  enable_batched_operations = true
  max_size_in_megabytes ="1024"
  status = "Active"
  support_ordering = true
}

resource "azurerm_servicebus_subscription" "sub_orderManagementPublisher" {
  name                = "orderManagementPublisher"
  resource_group_name = "${azurerm_resource_group.rg_integration.name}"
  topic_name          = "${azurerm_servicebus_topic.topic_newsalesorder.name}"
  namespace_name      = "${azurerm_servicebus_namespace.sb_integration.name}"
  max_delivery_count  = 1
}
```

### Panic Output

Error: Error running plan: 1 error(s) occurred:

* azurerm_servicebus_subscription.sub_orderManagementPublisher: invalid value for topic_name (The topic name can contain only letters, numbers, periods, hyphens and underscores. The namespace must start with a letter, and it must end with a letter or number and be less then 260 characters long.)

### Expected Behavior

The subscription to the topic should have been created

### Actual Behavior

The creation of the subscription failed since the topic has ~ in the name

### Steps to Reproduce

1. simply plan or apply the configuration

### Important Factoids

Using version 1.9.0 of the azurerm provider doesn't exhibit this behaviour
I am still able to provision the topic with ~ in the name using azurerm_servicebus_topic

### References

* #0000

**Comment by katbyte** [comment]
Hi @spittwood,

Thank you for opening this issue, additional validation for service bus resources names was recently added and this character was missed. 

I have opened a PR (#1640) to resolve this issue in v1.11.
