### ISSUE TITLE
[Documentation]pod_cidr can't bee set when network plugin is azure

### ISSUE THREAD

**Issue by metacpp** [terraform-providers/terraform-provider-azurerm#1648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.11.7

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-2022"
  location = "westeurope"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvirtnet2022"
  address_space       = ["10.1.0.0/16"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  tags {
    environment = "Testing"
  }
}

resource "azurerm_subnet" "test" {
  name                 = "acctestsubnet2022"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.1.0.0/24"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestaks2022"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  dns_prefix          = "acctestaks2022"
  kubernetes_version  = "1.7.7"

  linux_profile {
    admin_username = "acctestuser2022"

    ssh_key {
      key_data = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqaZoyiz1qbdOQ8xEf6uEu1cCwYowo5FHtsBhqLoDnnp7KUTEBN+L2NxRIfQ781rxV6Iq5jSav6b2Q8z5KiseOlvKA/RF2wqU0UPYqQviQhLmW6THTpmrv/YkUCuzxDpsH7DUDhZcwySLKVVe0Qm3+5N2Ta6UYH3lsDf9R9wTP2K/+vAnflKebuypNlmocIvakFWoZda18FOmsOoIVXQ8HWFNCuw9ZCunMSN62QGamCe3dL5cXlkgHYv7ekJE15IA9aOJcM7e90oeTqo+7HTcWfdu0qQqPWY5ujyMw/llas8tsXY85LFqRnr3gJ02bAscjc477+X+j/gkpFoN1QEmt terraform@demo.tld"
    }
  }

  agent_pool_profile {
    name           = "default"
    count          = "2"
    vm_size        = "Standard_DS2_v2"
    vnet_subnet_id = "${azurerm_subnet.test.id}"
  }

  service_principal {
    client_id     = "################"
    client_secret = "################"
  }

  network_profile {
    network_plugin = "azure"
    pod_cidr       = "10.244.0.0/24"
  }
}
```

### Expected Behavior
Rerun of `terraform plan` should be not have any change.

### Actual Behavior
```sh
network_profile.0.pod_cidr:                 "" => "10.244.0.0/24" (forces new resource)
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

**Comment by metacpp** [comment]
When syncing with AKS engineering team, when network plugin is `azure`, any setting to `pod_cidr` will be ignored inside. They're working on a proposal to reject the setting of `pod_cird` if network plugin is `azure`.

From Terraform side, we need to update documentation.

**Comment by metacpp** [comment]
https://github.com/Azure/acs-engine/pull/3562

**Comment by tombuildsstuff** [comment]
hi @metacpp 

Terraform's doing the correct thing here by stating that the combination is invalid (since a nil-value's being returned from the Azure API) - as such I don't believe there's an issue to fix within Terraform here. Instead the better fix here would be to add a note to the documentation - would you be able to send a PR to add a "This field can only be set when the Network Profile is of the type `kubenet`" type statement to this field?

Since this isn't a bug in Terraform but instead a potential enhancement for the documentation - I'm going to close this issue for the moment.

Thanks!

**Comment by metacpp** [comment]
@tombuildsstuff I've stated the action item in above comment:

> From Terraform side, we need to update documentation.

In the sample code(v1.12.0), by default it uses `azure` as network plugin, which will easily make user trigger this issue.

Let me reopen this issue for track and once PR is ready, I will close it.
