### ISSUE TITLE
azurerm_autoscale_settings: tag "$type" is treated as changed on plan

### ISSUE THREAD

**Issue by Supermathie** [terraform-providers/terraform-provider-azurerm#1661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.11.0
+ provider.random v1.3.1
+ provider.template v1.0.0

### Affected Resource(s)

* azurerm_autoscale_settings

### Terraform Configuration Files

```hcl
resource "azurerm_autoscale_setting" "app" {
  name                = "${var.label}DefaultSettings"
  resource_group_name = "${azurerm_resource_group.app.name}"
  location            = "${azurerm_resource_group.app.location}"
  target_resource_id  = "${azurerm_virtual_machine_scale_set.app.id}"

  tags {
    Cluster = "${var.label}"
    DC = "${terraform.workspace}"
  }
…
}
```

### Expected Behavior

After a clean apply, a re-plan should show no changes

### Actual Behavior

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.coffee_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"

  ~ module.discuss_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"

  ~ module.meta_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"

  ~ module.sushi_cluster.azurerm_autoscale_setting.app
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "3" => "2"


Plan: 0 to add, 4 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
1. `terraform apply`

### References

* analogous to the following issue on a different resource: https://github.com/terraform-providers/terraform-provider-azurerm/issues/945

**Comment by tombuildsstuff** [comment]
hi @Supermathie 

Thanks for reporting this issue - just to let you know that a fix for this issue has been released as part of v1.13.0 of the AzureRM Provider :)

Thanks!
