### ISSUE TITLE
Terraform failed creating Kubernetes cluster with no error message

### ISSUE THREAD

**Issue by catt231** [terraform-providers/terraform-provider-azurerm#1663]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.5.0

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "k8s" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.cluster_name}"
  location            = "${azurerm_resource_group.k8s.location}"
  resource_group_name = "${azurerm_resource_group.k8s.name}"
  dns_prefix          = "${var.dns_prefix}"

  linux_profile {
    admin_username = "ububtu"

    ssh_key {
      key_data = "${file("${var.ssh_public_key}")}"
    }
  }

  agent_pool_profile {
    name            = "default"
    count           = "${var.agent_count}"
    vm_size         = "Standard_D2"
    os_type         = "Linux"
    os_disk_size_gb = 30
  }

  service_principal {
    client_id     = "${var.client_id}"
    client_secret = "${var.client_secret}"
  }

  tags {
    Environment = "Development"
  }
}

```

### Debug Output

azurerm_kubernetes_cluster.k8s: Creating...
  agent_pool_profile.#:                      "" => "1"
  agent_pool_profile.0.count:                "" => "3"
  agent_pool_profile.0.dns_prefix:           "" => "<computed>"
  agent_pool_profile.0.fqdn:                 "" => "<computed>"
  agent_pool_profile.0.name:                 "" => "default"
  agent_pool_profile.0.os_disk_size_gb:      "" => "30"
  agent_pool_profile.0.os_type:              "" => "Linux"
  agent_pool_profile.0.vm_size:              "" => "Standard_D2"
  dns_prefix:                                "" => "k8stest"
  fqdn:                                      "" => "<computed>"
  kube_config.#:                             "" => "<computed>"
  kube_config_raw:                           "<sensitive>" => "<sensitive>"
  kubernetes_version:                        "" => "<computed>"
  linux_profile.#:                           "" => "1"
  linux_profile.0.admin_username:            "" => "ububtu"
  linux_profile.0.ssh_key.#:                 "" => "1"
  linux_profile.0.ssh_key.0.key_data:        "" => *****
  location:                                  "" => "westeurope"
  name:                                      "" => ****
  resource_group_name:                       "" => ****
  service_principal.#:                       "" => "1"
  service_principal.332349426.client_id:     "" => ****
  service_principal.332349426.client_secret: "<sensitive>" => "<sensitive>"
  tags.%:                                    "" => "1"
  tags.Environment:                          "" => "Development"

Error: Error applying plan:

1 error(s) occurred:

* azurerm_kubernetes_cluster.k8s: 1 error(s) occurred:

* azurerm_kubernetes_cluster.k8s: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="" Message=""

### Expected Behavior

Create an AKS cluster

### Actual Behavior

Cluster failed to create with StatusCode 400

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Azure Activity Log shows error

Error code
BadRequest
Message
The VM size of AgentPoolProfile:default is not allowed in your subscription in location 'westeurope'. The available VM sizes are

**Comment by tombuildsstuff** [comment]
hi @catt231 

Thanks for opening this issue :)

More recent versions of the AzureRM Provider include a fix for this bug - would you be able to upgrade to a newer version and take a look? You can do this by specifying the version in your provider block, like so:

```
provider "azurerm" {
  version = "=1.11.0"
}
```

In the interim I'm going to close this issue since this has been fixed in a prior release - but we'll continue responding here :)

Thanks!

**Comment by catt231** [comment]
Ah sorry, feel foolish now! was following an example, first time using terraform, also not helped by linux subsystem on windows :) Error message being helpfully returned to console window now!

**Comment by tombuildsstuff** [comment]
@catt231 not at all - glad to hear this is now working for you :)
