### ISSUE TITLE
Feature Request: CosmosDB Database

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#1671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a new Terraform resource to build a CosmosDB database inside a CosmosDB account.

### New or Affected Resource(s)

* azurerm_cosmosdb_account
* [new] azurerm_cosmosdb_database
* [in progress] azurerm_cosmosdb_collection

### Potential Terraform Configuration

At a minimum, I imagine it _might_ look roughly like this:
```hcl
resource "azurerm_cosmosdb_account" "cosmos_acct" {
    ...
}

resource "azurerm_cosmosdb_database" "cosmos_database" {
    ...
    account_id = "${azurerm_cosmosdb_account.cosmos_acct.id}"
    cosmos_key = "${azurerm_cosmosdb_account.cosmos_acct.primary_master_key}"
}
```

### References

Cosmos Collections can then reference the Database resource so they go into the right db.
* #548

**Comment by tombuildsstuff** [comment]
hey @kjhosein 

Thanks for opening this issue :)

Just to let you know that there's currently no support for creating Databases within a CosmosDB Account in [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) at this time - however once there is we can take a look into this and #548

Thanks!

**Comment by elizabethhalper** [comment]
Hey @tombuildsstuff thanks for all your contributions to the Azure SDK for Go! How far along is the work to support creating DBs using the SDK? Is there a branch I could fork so I don't duplicate any work?

**Comment by tombuildsstuff** [comment]
hey @elizabethhalper 

Given CosmosDB supports multiple drivers (e.g. DocumentDB, MongoDB etc) - the question's more _which_ one(s) we should support. At this time the Azure SDK for Go only supports creating a Database for the MongoDB type (which would probably be represented as something like `azurerm_cosmosdb_mongo_database`) - and we've been chatting with the SDK team about adding a DocumentDB (Data Plane) SDK so that we could add support for this. Out of interest which CosmosDB type were you looking to create a database for?

> How far along is the work to support creating DBs using the SDK? Is there a branch I could fork so I don't duplicate any work?

There's an issue requesting support for the DocumentDB SDK https://github.com/Azure/azure-sdk-for-go/issues/1637#issuecomment-392828828 - but I don't believe there's any work committed on this at the moment? Perhaps @joshgav would know if there's anything in the pipeline?

Thanks!

**Comment by elizabethhalper** [comment]
Thanks @tombuildsstuff! I am not necessarily looking to create a specific type of DB (DocumentDB or MongoDB would be fine), but I'm curious: is it necessary to have the DocumentDB SDK available before adding MongoDB support in Terraform?

I'm also happy to talk to @joshgav about what is in the pipeline. Thanks!

**Comment by tombuildsstuff** [comment]
@elizabethhalper 

>  is it necessary to have the DocumentDB SDK available before adding MongoDB support in Terraform?

No - we can add/release them both independently (my understanding is that they're different databases under the hood, but I might be wrong?) - the questions more about which of the CosmosDB Kind's makes the most sense to support (if that's Mongo or otherwise), based on feedback.

Thanks!

**Comment by joshgav** [comment]
Hi @tombuildsstuff and @elizabethhalper, no concrete plans yet for a first-party Go package for the SQL (fka DocumentDB) API, but OTOH users might want to provision the account and databases with Terraform and access them at run-time from other languages. Should you perhaps surface the `Kind` parameter [here](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2015-04-08/documentdb#DatabaseAccountCreateUpdateParameters) as a top-level property in Terraform?

You can also get a bit deeper than the "account" level, e.g. there's a [DatabaseClient](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2015-04-08/documentdb#DatabaseClient) too.

I *think* the underlying implementation is the same but need to verify with @kirankumarkolli

**Comment by tombuildsstuff** [comment]
@joshgav thanks for that :)

> You can also get a bit deeper than the "account" level, e.g. there's a DatabaseClient too.

I don't see any CRUD operations on the Database Client however - so I'm wondering if we need to create the database using one of the Provider-Type (e.g. SQL/Mongo etc) SDK's? At the moment [we expose the `kind` field on the `azurerm_cosmosdb_account` resource](https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html#kind).

> I think the underlying implementation is the same but need to verify with @kirankumarkolli and the Cosmos DB team, will work on doing so, thanks!

I main question from my end is whether creating a DB via one `kind` creates it for all types (e.g. creating via SQL also creates via MongoDB) - or if a Mongo client needs to be used to create the Mongo driver / a SQL (DocumentDB) Driver needs to be used to create a SQL (DocumentDB) DB within the CosmosDB Account - but we should be able to test that and confirm for sure :)

Thanks!

**Comment by khaliddermoumi** [comment]
Hi @tombuildsstuff, IMHO supporting a database/collection/etc. for the MongoDB type alone would make a lot of sense. I don't see it is necessary to provide the DocumentDB support at the same time.
Thanks for your work :)

**Comment by cmpxchg16b** [comment]
Hi @tombuildsstuff. Only specified API can be used. SQL API is needed because only it can be used for azure function bindings.

**Comment by MattHartz** [comment]
Hi @tombuildsstuff , awesome stuff so far. Any update on this?

Thanks!

**Comment by mohamedainab** [comment]
Any update on this?

**Comment by MattHartz** [comment]
@mohamedainab I looked into the Azure SDK for GO and it appears that they still don't support it there. Also I noticed .net core 3.0 will support a Cosmos DB Provider so what might be best is... Is create the Account via Terraform, then create the db/collections via Data Seeding (once it's supported).

**Comment by holmesb** [comment]
I'm seeing support for [documentdb](https://github.com/Azure/azure-sdk-for-go/tree/master/services/cosmos-db/mgmt/2015-04-08/documentdb) and [mongodb](https://github.com/Azure/azure-sdk-for-go/tree/master/services/cosmos-db/mongodb).  What am I missing?

**Comment by MattHartz** [comment]
@tracypholmes Collections.go doesn't appear to have any Update/Create APIs for example while Accounts APIs have Create/Update

**Comment by katbyte** [comment]
Exactly, until there is support in the go Azure SDK to create the databases there is really not much we can do @holmesb.

**Comment by cgkades** [comment]
I was looking into this for a project and it looks like the Azure doc for using python with CosmosDB uses pydocumentdb.. it's not using the Azure skd.. so anyone having this issue might want to look into a go documentdb module, and it will probably work for creating the Database and Collections.. just wanted to throw that out there
