### ISSUE TITLE
Volume attach not working with azurerm version upgrade to 1.11

### ISSUE THREAD

**Issue by git-krunal** [terraform-providers/terraform-provider-azurerm#1675]
Hi Team,

We are getting below error when trying to create and attach the volume to one of the server in our azure environment.
The volume does not get attached to the server.

==============||================||===================
Error: Error applying plan:

1 error(s) occurred:

azurerm_virtual_machine_data_disk_attachment.abcserver-app01-dataXX: 1 error(s) occurred:

azurerm_virtual_machine_data_disk_attachment.abcserver-app01-dataXX: Error updating Virtual Machine "abcserver-app01" (Resource Group "abc-XXXX") with Disk "abcserver-app01-dataXX": compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 9330.'."
==============||================||===================

Terraform plan output runs without errors and below is the output of resources created:

==============||================||===================
Terraform will perform the following actions:

azurerm_managed_disk.abcserver-app01-dataXX
id: 
create_option: "Empty"
disk_size_gb: "4095"
location: "westeurope"
name: "abcserver-app01-dataXX"
resource_group_name: "abc-XXXX"
source_uri: 
storage_account_type: "Premium_LRS"
tags.%: "4"
tags.app-number: "XXXX"
tags.environment: "XXXX"
tags.stack-name: "XXXX"
tags.stack-number: "XXXX"

azurerm_virtual_machine_data_disk_attachment.abcserver-app01-dataXX
id: 
caching: "None"
create_option: "Attach"
lun: "12"
managed_disk_id: "${azurerm_managed_disk.abcserver-app01-dataXX.id}"
virtual_machine_id: "/subscriptions/0000000000000/resourceGroups/abc-XXXX/providers/Microsoft.Compute/virtualMachines/abcserver-app01"
==============||================||===================

Regards,
Krunal Shah

**Comment by Stuti05** [comment]
Hi Krunal

You can try checking the code

**Comment by tombuildsstuff** [comment]
hey @git-krunal 

Thanks for opening this issue :)

This issue has previously been reported in #1675 which I'm going to close this in favour or - would you mind subscribing to that issue for updates?

Thanks!

**Comment by git-krunal** [comment]
Hi Tom

Can you please give me the correct link where it is reported?
The link which i see in your reply is of current link where the issue is raised. :-) 

Regards,
Krunal Shah

**Comment by git-krunal** [comment]
@tombuildsstuff can you please provide me with the correct link where the issue is reported.

Regards,
Krunal Shah

**Comment by tombuildsstuff** [comment]
@git-krunal sorry, copy-paste error - the correct issue number is #1600 - thanks!

**Comment by git-krunal** [comment]
Thanks @tombuildsstuff for your reply.

Regards,
Krunal Shah

**Comment by git-krunal** [comment]
Hi @tombuildsstuff -- today we saw the the version 1.12 was released and we upgraded the module to the newest version.

We are getting the same error that we got previously.
================
* azurerm_virtual_machine_data_disk_attachment.ABCXXX-XX02: Error updating Virtual Machine "ABCXXX-XX02" (Resource Group "ABCXXX-XX02") with Disk "ABCXXX-XX02": compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 4750.'."
================


Below is the syntax for azurerm
================
"azurerm" {
 version         = "1.12.0"
 client_id       = "${xxxxxxxxx}"
 client_secret   = "${xxxxxxx"]}"
 subscription_id = "${xxxxx"]}"
 tenant_id       = "${xxxx]}"
}
================


Regards,
Krunal Shah
