### ISSUE TITLE
Failing to add volume using terraform code

### ISSUE THREAD

**Issue by Stuti05** [terraform-providers/terraform-provider-azurerm#1676]
Hi Team,

We are getting below error when trying to create and attach the volume to one of the server in our azure environment.
The volume does not get attached to the server. I have tried using version 1.8.0 and 1.11.0
No luck

==============||================||===================
Error: Error applying plan:

1 error(s) occurred:

azurerm_virtual_machine_data_disk_attachment.abcserver-dataXX: 1 error(s) occurred:

azurerm_virtual_machine_data_disk_attachment.abcserver-dataXX: Error updating Virtual Machine "abcserver" (Resource Group "abc-XXXX") with Disk "abcserver-dataXX": compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 9330.'."
==============||================||===================

Terraform plan output runs without errors and below is the output of resources created:

==============||================||===================
Terraform will perform the following actions:

azurerm_managed_disk.abcserver-dataXX
id:
create_option: "Empty"
disk_size_gb: "4095"
location: "westeurope"
name: "abcserver-dataXX"
resource_group_name: "abc-XXXX"
source_uri:
storage_account_type: "Premium_LRS"
tags.%: "4"
tags.app-number: "XXXX"
tags.environment: "XXXX"
tags.stack-name: "XXXX"
tags.stack-number: "XXXX"

azurerm_virtual_machine_data_disk_attachment.abcserver-dataXX
id:
caching: "None"
create_option: "Attach"
lun: "12"
managed_disk_id: "${azurerm_managed_disk.abcserver-dataXX.id}"

**Comment by tombuildsstuff** [comment]
hey @Stuti05 

Thanks for opening this issue :)

This issue has previously been reported in #1600 which I'm going to close this issue in favour of - would you mind subscribing to that issue for updates?

Thanks!
