### ISSUE TITLE
Feature request: Configure instances to use Recovery Services Vault

### ISSUE THREAD

**Issue by MarcoMol** [terraform-providers/terraform-provider-azurerm#1677]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it is possible to deploy a Recovery Services vault, however having virtual machines use the recovery vault, and assigning a policy to them isn't. Which means that currently these are manual tasks either by using the portal, or powershell.
Additionally, this makes it difficult to use a CI/CD pipeline, because it requires RBAC to be expanded on - which is undesirable when you don't want anyone clicking in the portal.

### New or Affected Resource(s)

[new]* azurerm_virtual_machine backup_property
[new]* azurerm_recovery_services_backup_policy

### Potential Terraform Configuration

```
resource "azurerm_recovery_services_policy" "Policy01" {
    name = "DailyPolicy"
    vault = "${azurerm_recovery_services_vault.vault.id}"
    ...
}
```

```resource "azurerm_virtual_machine" "main" {
    recovery_services_vault {
        vault = "${azurerm_recovery_services_vault.vault.id}"
        policy = "${azurerm_recovery_services_policy.Policy01}"
    }
}
```
At least this is my suggestion. Much like when doing this via the portal, there should be no re-create of the VM. So I'm not sure if configuring the backup should then become a separate resource in terraform code or not.
I'm also un-certain if this should then include the recovery of a snapshot or if that would have to go in a separate request, so I'll wait on any comments.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
I have no references to any GitHub page, this is also my first feature request here so if I left out anything you're expecting. I do have one reference to ARM code if that is of any help: https://stackoverflow.com/questions/43884921/azure-arm-json-template-add-vm-to-recovery-services-vault-in-different-resourc

**Comment by tombuildsstuff** [comment]
hey @MarcoMol 

Thanks for opening this issue :)

Support for protecting Virtual Machines with a Recovery Vault has previously been requested in #1143 (and support for Backup Policies is being tracked in #1007). Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of those two - which you should be able to subscribe to for updates.

Thanks!
