### ISSUE TITLE
Remove the *location* from the azurerm_traffic_manager_profile sample on documentation

### ISSUE THREAD

**Issue by evandropaula** [terraform-providers/terraform-provider-azurerm#169]
**Observed:**
Trying Azure Traffic Manager Profile sample available at https://www.terraform.io/docs/providers/azurerm/r/traffic_manager_profile.html leads to the following error:
* azurerm_traffic_manager_profile.xxxxx: : invalid or unknown key: location

**Fix**
Remove the *location* from the azurerm_traffic_manager_profile sample on documentation available at https://www.terraform.io/docs/providers/azurerm/r/traffic_manager_profile.html.

**Comment by tombuildsstuff** [comment]
Hey @evandropaula 

Thanks for reporting this - I've opened PR #173 with a fix :)

Thanks!
