### ISSUE TITLE
azurerm_virtual_machine_scale_set: support eviction policy

### ISSUE THREAD

**Issue by CoRfr** [terraform-providers/terraform-provider-azurerm#1690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With low-priority scale sets, it can be interesting to set the 'eviction policy', cf https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-low-priority#eviction-policy.

> When creating low-priority scale sets, you can set the eviction policy to Deallocate (default) or Delete.
> 
> The Deallocate policy moves your evicted VMs to the stopped-deallocated state allowing you to redeploy evicted instances. However, there is no guarantee that the allocation will succeed. The deallocated VMs will count against your scale set instance quota and you will be charged for your underlying disks.

### New or Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine_scale_set" "test" {
  name                = "acctvmss-%[1]d"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  upgrade_policy_mode = "Manual"
  overprovision       = false
  priority            = "Low"
  eviction_policy = "Delete"
```

### References

* https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate#virtualmachineevictionpolicytypes

**Comment by CoRfr** [comment]
A brief analysis shows that {{vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2017-12-01/compute/}} does not mention EvictionPolicy, while the REST API 2017-12-01 already does support setting this parameter, which makes me a bit confused ...

Seems like it starts appearing at v19.0.0 of the azure-sdk-for-go, while the current version is v15.0.0 (last updated in April 2018).

**Comment by dghubble** [comment]
Looks like https://github.com/terraform-providers/terraform-provider-azurerm/pull/1861 updated to v20.1.0 of github.com/Azure/azure-sdk-for-go for the Sept 14, 2018 release.
