### ISSUE TITLE
print assumed timezone on stderr when access tokens seem to be stale

### ISSUE THREAD

**Issue by cruwe** [terraform-providers/terraform-provider-azurerm#1707]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To use terraform with MS Azure, a _valid_ access token must be obtained beforehand with `az login`.

One may be tempted to run `az` packaged as a docker container (to prevent polluting the workstation). terraform (statically linked) does not warrant such hooks and loops.

By standard, docker containers run on UTC and accordingly, `az` formats and stores access tokens in UTC. When the _host_ terraform is then invoked on runs on a different timezone _and_ the variable `$TZ` is unset, tokens may be stale without the user realizing.

I have requested to document this behaviour with PR #1706. I do not know how to (I would do it myself then), but it may be of value to stderr the `$TZ` terraform assumes for the az token so that debugging such failures may be easier.

### New or Affected Resource(s)

* azurerm provider

### References

* PR #1706

**Comment by tombuildsstuff** [comment]
hey @cruwe 

Thanks for opening this issue - apologies for the delayed response here!

We've recently migrated the Authentication logic out of this repository and into a common helper library so that we're able to iterate on it and then reuse it across Providers - as such I'm going to migrate this issue over to that repository: https://github.com/hashicorp/go-azure-helpers/issues/3

Thanks!
