### ISSUE TITLE
 ip_forwarding property for azurerm_virtual_machine_scale_set is not documented in terraform.io

### ISSUE THREAD

**Issue by ruzin** [terraform-providers/terraform-provider-azurerm#1709]
**Terraform Version**
terraform -v
Terraform v0.11.7

provider.azurerm v1.11.0

**Affected Resource(s)**
ls

azurerm_virtual_machine_scale_set

Issue
The page https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html does not include any documentation on the ip_forwarding property for the scale set network interface which was added here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1226

**Comment by katbyte** [comment]
Hi @ruzin,

Thank you for noticing this omission in our documentation! I have just opened a PR adding the missing information that with luck will go out in the new few days.
