### ISSUE TITLE
New Resource request: Azure Data Factory

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#1720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a new Terraform resource to create an [Azure Data Factory](https://docs.microsoft.com/en-us/azure/data-factory/introduction).

### New or Affected Resource(s)

* new: azurerm_data_factory

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory" "data_factory" {
  name = "df1"
  resource_group_name = "rg1"
  location = "eastus"
  version = "v2"
  tags = {
    desc = "I am a little data factory"
  }
```

### References

Appears that the Azure Go SDK has support for Data Factory:
* https://github.com/Azure/azure-sdk-for-go/blob/master/services/datafactory/mgmt/2018-06-01/datafactory/factories.go

**Comment by iain-peddie-tessella** [comment]
The workflows within a data factory are really part of the configuration as well. While I would really like to see a data factory resource, it's of limited value to me without being able to configure the ingest pipelines within a data factory. So if this task is done, it would be really helpful to have resources for the input and output datasets as well as the activity types as well.

**Comment by YoSarin** [comment]
:+1:

**Comment by bugblatter2016** [comment]
Any idea when this might be picked up by someone?

**Comment by tomweston** [comment]
Need this ASAP!
🙏🙏🙏🙏🙏

**Comment by dkyanakiev** [comment]
Any update if this will be implemented soon?

**Comment by TheMacStack** [comment]
Another use case - Looking to migrate Datalake gen1 to gen2 and seems the recommended way is using data factory, i would like to be able to be able to spin and configure the datafactory via terraform for this so they can be easily cleaned up afterwards (As they will be short-lived just for the migrations), and also easily repeatable for the many different datalake stores in scope over time.

**Comment by mbfrahry** [comment]
Closing this in favor of #3159. Thanks @hbuckle!

**Comment by tombuildsstuff** [comment]
re-opening this (it should have been the other PR that got closed 😄)
