### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment import CRASH

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#1721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.12.0

### Affected Resource(s)

azurerm_virtual_machine_data_disk_attachment

### Terraform Configuration Files

https://gist.github.com/rohrerb/ee3852c4fe8120898fbbc048ab7eebe3 

### Steps

1. Run the above TF file to create the base resources.
2. Go to the Portal and add a new data disk [USAVlxyz001-datadisk1] to the VM. (https://imgur.com/a/1qXrz90)
3. Grab the ResourceID from the new created disk in the portal.
4. Run the following command to add the disk into state (This Works)
 `terraform import azurerm_managed_disk.data_disk /subscriptions/7d559a72-c8b6-4d07-9ec0-5ca5b14a25e7/resourceGroups/USAV-WEB/providers/Microsoft.Compute/disks/USAVlxyz001-datadisk1`
5. Run the following command to import the attach resource into state.
 `terraform import azurerm_virtual_machine_data_disk_attachment.data_disk_attach /subscriptions/7d559a72-c8b6-4d07-9ec0-5ca5b14a25e7/resourceGroups/USAV-WEB/providers/Microsoft.Compute/disks/USAVlxyz001-datadisk1`

I get the following CRASH.

> Error: azurerm_virtual_machine_data_disk_attachment.data_disk_attach (import id: /subscriptions/7d559a72-c8b6-4d07-9ec0-5ca5b14a25e7/resourceGroups/USAV-WEB/providers/Microsoft.Compute/disks/USAVlxyz001-datadisk1): 1 error(s) occurred:
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a37595]
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: goroutine 57 [running]:
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmVirtualMachineDataDiskAttachmentRead(0xc42027c4d0, 0x1e51e60, 0xc4203f8000, 0xc42027c4d0, 0x0)
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_machine_data_disk_attachment.go:195 +0x335
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420526bd0, 0xc4207e6050, 0x1e51e60, 0xc4203f8000, 0xc4204e7758, 0x616a465236534d01, 0x8004c365373)
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x17e
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420527c00, 0xc4207e6000, 0xc4207e6050, 0x7f70db1a1b20, 0x0, 0x18)
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4202d2ec0, 0xc4206614d0, 0xc420661730, 0x0, 0x0)
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: reflect.Value.call(0xc4202f2c60, 0xc420550360, 0x13, 0x1e8eef4, 0x4, 0xc42057cf20, 0x3,
> 0x3, 0x0, 0x0, ...)
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /usr/local/go/src/reflect/value.go:434 +0x905
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: reflect.Value.Call(0xc4202f2c60, 0xc420550360, 0x13, 0xc420345720, 0x3, 0x3, 0x0, 0x0, 0x0)
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /usr/local/go/src/reflect/value.go:302 +0xa4
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: net/rpc.(*service).call(0xc420059500, 0xc420080050, 0xc42049c278, 0xc4202f4500, 0xc4202d3800, 0x1b55720, 0xc4206614d0, 0x16, 0x1b55760, 0xc420661730, ...)
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /usr/local/go/src/net/rpc/server.go:381 +0x142
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4: created by net/rpc.(*Server).ServeCodec
> 2018-08-03T11:45:56.686-0400 [DEBUG] plugin.terraform-provider-azurerm_v1.12.0_x4:      /usr/local/go/src/net/rpc/server.go:475 +0x36b
> 2018-08-03T11:45:56.687-0400 [DEBUG] plugin: plugin process exited: path=/mnt/c/Projects/Terraform/src/Isolated/vm_disk_import/.terraform/plugins/linux_amd64/terraform-provider-azurerm_v1.12.0_x4
> 2018/08/03 11:45:56 [ERROR] root: eval: *terraform.EvalRefresh, err: azurerm_virtual_machine_data_disk_attachment.data_disk_attach: unexpected EOF
> 2018/08/03 11:45:56 [ERROR] root: eval: *terraform.EvalSequence, err: azurerm_virtual_machine_data_disk_attachment.data_disk_attach: unexpected EOF
> 2018/08/03 11:45:56 [TRACE] [walkImport] Exiting eval tree: import azurerm_virtual_machine_data_disk_attachment.data_disk_attach result: /subscriptions/7d559a72-c8b6-4d07-9ec0-5ca5b14a25e7/resourceGroups/USAV-WEB/providers/Microsoft.Compute/disks/USAVlxyz001-datadisk1
> 2018/08/03 11:45:56 [TRACE] dag/walk: upstream errored, not walking "provider.azurerm (close)"
> 2018/08/03 11:45:56 [DEBUG] plugin: waiting for all plugin processes to complete...
> 2018-08-03T11:45:56.688-0400 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
> 
> * import azurerm_virtual_machine_data_disk_attachment.data_disk_attach result: /subscriptions/7d559a72-c8b6-4d07-9ec0-5ca5b14a25e7/resourceGroups/USAV-WEB/providers/Microsoft.Compute/disks/USAVlxyz001-datadisk1: azurerm_virtual_machine_data_disk_attachment.data_disk_attach: unexpected EOF
> 
> 
> 
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Terraform crashed! This is always indicative of a bug within Terraform.
> A crash log has been placed at "crash.log" relative to your current
> working directory. It would be immensely helpful if you could please
> report the crash with Terraform[1] so that we can fix this.
> 
> When reporting bugs, please include your terraform version. That
> information is available on the first line of crash.log. You can also
> get it by running 'terraform --version' on the command line.
> 
> [1]: https://github.com/hashicorp/terraform/issues
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

@JunyiYi | @tombuildsstuff for awareness.

**Comment by tombuildsstuff** [comment]
hey @rohrerb 

Thanks for opening this issue :)

The error you're seeing here is because the wrong ID's being imported for a Data Disk Attachment; the format used for [importing a Data Disk Attachment](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_data_disk_attachment.html#import) is:

> terraform import azurerm_virtual_machine_data_disk_attachment.test /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/microsoft.compute/virtualMachines/machine1/dataDisks/disk1

Would you be able to update the import command you're running and take another look?

Thanks!

**Comment by rohrerb** [comment]
`terraform import azurerm_virtual_machine_data_disk_attachment.data_disk_attach  /subscriptions/7d559a72-c8b6-4d07-9ec0-5ca5b14a25e7/resourceGroups/USAV-WEB/providers/microsoft.compute/virtualMachines/USAVlxyz001/dataDisks/USAVlxyz001-datadisk1`

Works Perfectly.   Thank you for the quick response.
