### ISSUE TITLE
Support for Determining AzureAD Principal Type from Object ID

### ISSUE THREAD

**Issue by bargokr** [terraform-providers/terraform-provider-azurerm#17252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently AzureAD does not allow the assignment of AD groups as "Owners" of a Azure Application Registration and/or Azure Enterprise Application. Due to this limitation, we have to pull all users from the AD group we would like to assign (using data.azuread_group) and pass all object ids (using data.azuread_group.[name].members) to the "owners" attribute of the application registration / enterprise application. See below:

```
data "azuread_client_config" "tf_spn" {}

data "azuread_group" "ad_group" {
  object_id     = var.ra_object_id
  security_enabled = true
}

resource "azuread_application" "app_reg" {
  display_name = "${var.tenant}-${var.subscription}-${var.spn_name_short}"
  owners       = concat([data.azuread_client_config.tf_spn.object_id], data.azuread_group.ad_group.members)
}

```
This works fine for AD groups with only users as members, but when you have AD groups that have a mix of groups (nested) and members, it does not work.

We are proposing an additional data source that takes the input of "object_id" and exports attributes about the principal, including principal type. This would allow us to get the type of each principal and then do additional data pulls based on the principal type (either data.azuread_group or data. azuread_user).

Please provide similar functionality or a recommendation on how to handle this use case.

### New or Affected Resource(s)/Data Source(s)

Data Source - azuread_principal_type or azuread_principal_lookup

### Potential Terraform Configuration

```hcl
# Get principal details (including type)
data "azuread_principal_type" "principal_lookup" {
  object_id     = var.object_id
}

# If type is group, get the object id of members of the group
data "azuread_group" "ad_group" {
  count         = data.azuread_principal_type.principal_lookup.type == "Group" ? "1" : "0"
  object_id     = var.object_id
}

# If principal type is group, add the object ids of all members as owners
resource "azuread_application" "app_reg" {
  count        = data.azuread_principal_type.principal_lookup.type == "Group" ? "1" : "0"
  display_name = var.app_name
  owners       = data.azuread_group.ad_group.members
}

# If principal type is user, add the object id of the user
resource "azuread_application" "app_reg" {
  count        = data.azuread_principal_type.principal_lookup.type == "User" ? "1" : "0"
  display_name = var.app_name
  owners       = var.object_id
}
```

### References

https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadobjectbyobjectid?view=azureadps-2.0

**Comment by favoretti** [comment]
Hey, thank you for reporting this issue, although shouldn't it be reported in azuread repo, rather than azurerm? :)

**Comment by bargokr** [comment]
> 

Absolutely. Closing and recreating over there.

Thanks!
