### ISSUE TITLE
Referencing resource_group_name by string results in `ResourceGroupNotFound`

### ISSUE THREAD

**Issue by errygg** [terraform-providers/terraform-provider-azurerm#1730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.7
+ provider.azurerm v1.12.0
```

### Affected Resource(s)

* `azurerm_resource_group`
* `azurerm_virtual_network`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "my_rg" {
  name = "my_rg"
  location = "West US"
}

resource "azurerm_virtual_network" "my_vnet" {
  name = "my_vnet"
  address_space = "10.0.0.0/16"
  location = "West US"
  resource_group_name = "my_rg"
}
```

### Debug Output

https://gist.github.com/errygg/f5ae7758873ab01a41fe62424c20d876#file-terraform-azurerm-resource-group-issue

### Expected Behavior

The provider should recognize string name references to resource groups and create the virtual network without issue.

### Actual Behavior

Terraform errors because the reference to the resource group can't be found.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The reference works with the following resource reference:

```hcl
resource "azurerm_resource_group" "my_rg" {
  name     = "my_rg"
  location = "West US"
}

resource "azurerm_virtual_network" "my_vnet" {
  name                             = "my_vnet"
  address_space             = "10.0.0.0/16"
  location                         = "West US"
  resource_group_name = "${azurerm_resource_group.my_rg.name}"
}
```

Additionally, when running `terraform apply` a second time, the virtual network will get created. Seems as though there is a timing issue?

### References

* #532

**Comment by katbyte** [comment]
Hi @errygg,

This definitely appears to be an ordering issue. Terraform is not aware of the dependancy between the virtual network and the resource group until you let it know with `depends_on` or either reference it: `"${azurerm_resource_group.my_rg.name}"`.

The provider will not recognize a simple string as the name of another resource.

I hope this helps.

**Comment by errygg** [comment]
Hi @katbyte - 

Ok, that is what I figured. Thanks for the info! I'll close this issue.

Thanks,
Erik
