### ISSUE TITLE
Feature Request: Azure Database for MySQL

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#174]
Splitting this out into it's own issue to make it clearer, rather than bundling it within the PostgreSQL issue.

[I've started this work in this branch](https://github.com/terraform-providers/terraform-provider-azurerm/compare/mysql) - but like #158 this is blocked on the AutoRest Generator being updated. Once this has been updated we can open a PR.

**Comment by tombuildsstuff** [comment]
Support for this has landed in the Azure SDK - as such I've opened PR #209 which upgrades this Provider to that version. Once that's merged we can proceed with this :)

**Comment by bailantaotao** [comment]
Hello, do you have any updates on this?

**Comment by tombuildsstuff** [comment]
This has now shipped in v0.2.2 of the AzureRM Provider - as such I'm going to close this issue out.

**Comment by bailantaotao** [comment]
thank you!! 💃
