### ISSUE TITLE
Error in terraform script during creation of Managed sql database instance using ARM template

### ISSUE THREAD

**Issue by reddyed** [terraform-providers/terraform-provider-azurerm#1741]
Hi,

i am getting an error when i deploy terraform script using ARM template for Managed SQL Database. Since there is no support for direct terraform script, i am using ARM template. 
resource "azurerm_template_deployment" "test" {
  name                = "sqltemplate04"
  resource_group_name = "test-prod-db-rg"

  template_body = <<DEPLOY
   {
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageAccounts_testproddbsa_name": {
            "defaultValue": "testproddbsa",
            "type": "String"
        },
        "routeTables_test_mi_sqlserver_rt_name": {
            "defaultValue": "test-mi-sqlserver-rt",
            "type": "String"
        },
        "managedInstances_test_di_mi_prd_name": {
            "defaultValue": "test-di-mi-prd",
            "type": "String"
        },
        "managedInstances_test_test_mi_prd_subnetId": {
            "defaultValue": "/subscriptions/xxxxx-xxxxf7d-ffc5/resourceGroups/xxx-xxx-shared-rg/providers/Microsoft.Network/virtualNetworks/xxx-x-euxxs-vnet/subnets/data-mi-kubeprod-emetric-eus-subnet",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "comments": "Generalized from resource: '/subscriptions/xxxx-xxx-41d9-xxx-x/resourceGroups/di-prod-db-rg/providers/Microsoft.Network/routeTables/test-mi-sqlserver-rt'.",
            "type": "Microsoft.Network/routeTables",
            "name": "[parameters('routeTables_test_mi_sqlserver_rt_name')]",
            "apiVersion": "2018-02-01",
            "location": "eastus",
            "scale": null,
            "properties": {
                "provisioningState": "Succeeded",
                "disableBgpRoutePropagation": false,
                "routes": [
                    {
                        "name": "default",
                        "etag": "W/\"xxxx-85c8-4723-a55b-xxxx\"",
                        "properties": {
                            "provisioningState": "Succeeded",
                            "addressPrefix": "0.0.0.0/0",
                            "nextHopType": "Internet"
                        }
                    }
                ]
            },
            "dependsOn": []
        },
        {
            "comments": "Generalized from resource: '/subscriptions/xxx-xxx-41d9-xxx-xxxxxx/resourceGroups/test-prod-db-rg/providers/Microsoft.Sql/managedInstances/test-di-mi-prd'.",
            "type": "Microsoft.Sql/managedInstances",
            "sku": {
                "name": "GP_Gen5",
                "tier": "GeneralPurpose",
                "family": "Gen5",
                "capacity": 8
            },
            "name": "[parameters('managedInstances_test_di_mi_prd_name')]",
            "apiVersion": "2015-05-01-preview",
            "location": "eastus",
            "identity": {
                "principalId": "xxxxx-xxx-4c20-xxx-xxxxx",
                "tenantId": "xxxx-xxxx-47b1-xxx-xxxxx",
                "type": "SystemAssigned"
            },
            "scale": null,
            "properties": {
                "administratorLogin": "admin",
                "subnetId": "[parameters('managedInstances_test_test_mi_prd_subnetId')]",
                "licenseType": "LicenseIncluded",
                "vCores": 8,
                "storageSizeInGB": 2048
            },
            "dependsOn": []
        },
        {
            "comments": "Generalized from resource: '/subscriptions/xxxx-b234-41d9-bfxxxx7d-xxxx/resourceGroups/test-prod-db-rg/providers/Microsoft.Storage/storageAccounts/testproddbsa'.",
            "type": "Microsoft.Storage/storageAccounts",
            "sku": {
                "name": "Standard_LRS",
                "tier": "Standard"
            },
            "kind": "Storage",
            "name": "[parameters('storageAccounts_testproddbsa_name')]",
            "apiVersion": "2018-03-01-preview",
            "location": "eastus",
            "tags": {},
            "scale": null,
            "properties": {
                "networkAcls": {
                    "bypass": "AzureServices",
                    "virtualNetworkRules": [],
                    "ipRules": [],
                    "defaultAction": "Allow"
                },
                "supportsHttpsTrafficOnly": false,
                "encryption": {
                    "services": {
                        "file": {
                            "enabled": true
                        },
                        "blob": {
                            "enabled": true
                        }
                    },
                    "keySource": "Microsoft.Storage"
                }
            },
            "dependsOn": []
        }
    ]
}
DEPLOY

  deployment_mode = "Incremental"
}

The following is the error i am getting
* azurerm_template_deployment.test: 1 error(s) occurred:

* azurerm_template_deployment.test: Error creating deployment: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceIdentityPrincipalId\",\r\n    \"message\": \"The principalId 'xxx-7b21-xxx-xxx-xxxx' on the resource's Identity property must be null or empty for 'SystemAssigned' identity type.\"\r\n  }\r\n}"}]

i am getting the same error using the principal id from the ARM template or giving null or creating a new one using az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/${SUBSCRIPTION_ID}"

Any help is appriciated. Thanks.

**Comment by tombuildsstuff** [comment]
hi @reddyed 

Thanks for opening this issue :)

The error from the Template Deployment API here is stating that a Principal ID can't be specified for a IdentityType of `SystemAssigned` - however I believe these fields can be set for `UserAssigned`. Unfortunately since this is an issue with the contents of an ARM Template and not something specific to Terraform (such that I'm going to close this issue for the moment) - we'd instead recommend opening an issue on [the Azure Quickstart Templates repository](https://github.com/Azure/azure-quickstart-templates/issues) where someone more familiar with ARM Templates may be able to help. However I'd suggest opening a new issue requesting support for Managed SQL Databases so that we can look to add native support for this.

Thanks!
