### ISSUE TITLE
url_path_map used instead of url_path_map_name in docs

### ISSUE THREAD

**Issue by ndarilek** [terraform-providers/terraform-provider-azurerm#1749]
At https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html I see the following:

```
    url_path_map       = "pbr.contoso.com"
```

I suspect this should be:

```
    url_path_map_name       = "pbr.contoso.com"
```

Thanks.

**Comment by katbyte** [comment]
Hi @ndarilek,

Thank you for spotting this and letting us know, I've opened #1759 to correct this.
