### ISSUE TITLE
Data source for Azure AD principals

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-azurerm#1758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating resources, one often wants to also create role bindings for IAM, but I can't find a way to reference Azure AD principals with the currently available data sources. It would be nice to be able to query for e.g. users by email in the same way I can query for applications by name, and get e.g. their object ids.

### New or Affected Resource(s)

* `data azurerm_azuread_user`

### Potential Terraform Configuration
```hcl
provider "azurerm" {}

data azurerm_azuread_user "tomas" {
    username = "tomas@example.com"
}

output "tomas_object_id" {
    id = "${data.azurerm_azuread_user.tomas.id}"
}
```

**Comment by tiwood** [comment]
I'm going to work on this in the next days.

**Comment by tombuildsstuff** [comment]
hey @tomasaschan 

Thanks for opening this issue - apologies for the delayed response here!

Support for a Data Source for AzureAD Principals (Users / Groups) has previously been requested in #1272; so that we don't have multiple issues open tracking the same thing I'm going to close this issue in favour of #1272.

Thanks!
