### ISSUE TITLE
Feature Request: Application Gateway - Override backend path on HTTP Settings

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When implementing a Path-based routing rule to vector traffic to multiple Web Apps sitting inside of an App Service Environment it can be required to populate the "Override backend path" field to get the rule to function correctly.  The current documentation for the Application Gateway resource does not provide a means to populate this filed.

### New or Affected Resource(s)

* azurerm_application_gateway

**Comment by tombuildsstuff** [comment]
Closing since this has been fixed via #2879
