### ISSUE TITLE
Bug on the resource: azurerm_kubernetes_cluster, the argument automatic_channel_upgrade doesn't work has expected.

### ISSUE THREAD

**Issue by BriceLag** [terraform-providers/terraform-provider-azurerm#17618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.13.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "= 3.13.0"
    }
    tls = {
      version = ">=3.0.0"
    }
  }
}

provider "azurerm" {
  subscription_id = "YOUR-SUB-ID"
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                      = "example-aks1"
  location                  = azurerm_resource_group.example.location
  resource_group_name       = azurerm_resource_group.example.name
  dns_prefix                = "exampleaks1"
  automatic_channel_upgrade = "none"
  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Test"
  }
}
```

### Debug Output/Panic Output

```shell
2022-07-13T11:37:30.313+0200 [DEBUG] provider: using plugin: version=5
2022-07-13T11:37:30.313+0200 [DEBUG] provider.terraform-provider-azurerm_v3.13.0_x5: plugin address: address=/tmp/plugin1159798836 network=unix timestamp=2022-07-13T11:37:30.312+0200
2022-07-13T11:37:30.523+0200 [ERROR] vertex "azurerm_kubernetes_cluster.example" error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none
╷
│ Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none
│
│   with azurerm_kubernetes_cluster.example,
│   on main.tf line 27, in resource "azurerm_kubernetes_cluster" "example":
│   27:   automatic_channel_upgrade = "none"
```

### Expected Behaviour

  # azurerm_kubernetes_cluster.example will be created
  + resource "azurerm_kubernetes_cluster" "example" {
      + automatic_channel_upgrade           = "none"
      + dns_prefix                          = "exampleaks1"
      + fqdn                                = (known after apply)
      + http_application_routing_zone_name  = (known after apply)
      + id                                  = (known after apply)
      + kube_admin_config                   = (sensitive value)
      + kube_admin_config_raw               = (sensitive value)
      + kube_config                         = (sensitive value)
      + kube_config_raw                     = (sensitive value)
      + kubernetes_version                  = (known after apply)
      + location                            = "westeurope"
      + name                                = "example-aks1"
      + node_resource_group                 = (known after apply)
      + oidc_issuer_url                     = (known after apply)
      + portal_fqdn                         = (known after apply)
      + private_cluster_public_fqdn_enabled = false
      + private_dns_zone_id                 = (known after apply)
      + private_fqdn                        = (known after apply)
      + public_network_access_enabled       = true
      + resource_group_name                 = "example-resources"
      + role_based_access_control_enabled   = true
      + run_command_enabled                 = true
      + sku_tier                            = "Free"
      + tags                                = {
          + "Environment" = "Production"
        }

### Actual Behaviour

Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none

### References

Hello team,
Thank you for your job.
Following the documentation: https://registry.terraform.io/providers/hashicorp/azurerm/3.0.0/docs/resources/kubernetes_cluster#automatic_channel_upgrade
I was expecting that the value "none" can be set on the argument: automatic_channel_upgrade.
But he can't.
Other github issue about that problem here:
https://github.com/hashicorp/terraform-provider-azurerm/issues/11030.

In other hand I've perform the action manually  on my cluster following this documentation: https://docs.microsoft.com/en-us/azure/aks/auto-upgrade-cluster.
I've set the auto-upgrade-channel of my cluster from "none", to "stable" and back to "none" whitout any problem.
`az aks show --resource-group example-resources --name example-aks1 | grep -i chann`
`az aks update  --resource-group  example-resources --name example-aks1 --auto-upgrade-channel none`
Can you do something ?
Best regards,

Brice

**Comment by ms-henglu** [comment]
Hi @BriceLag ,

From the document, https://registry.terraform.io/providers/hashicorp/azurerm/3.0.0/docs/resources/kubernetes_cluster#automatic_channel_upgrade

> Omitting this field sets this value to `none`.

**Comment by BriceLag** [comment]
Hi @ms-henglu,
Thank you for your answer.
But how can I wrote a module, to let the user choose the value, or back to 'none' on that parameter with terraform ?
Best regards,

Brice

**Comment by ms-henglu** [comment]
Hi @BriceLag ,

You can use value `null`, more information can be found [here](https://www.terraform.io/language/expressions/types#null)
