### ISSUE TITLE
App insights resource returns Failure responding to request: StatusCode=201

### ISSUE THREAD

**Issue by dubeaud** [terraform-providers/terraform-provider-azurerm#1766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.7
+ provider.azurerm v1.12.0
```

### Affected Resource(s)

* azurerm_application_insights

### Expected Behavior

The application insights resource in the last day or so started to error on a new resource being created due to the API returning at 201 response code.

The resource should get created successfully.

### Actual Behavior

terraform error in which the resource gets created, but the terraform script reports an error.
```
azurerm_application_insights.appinsights: insights.ComponentsClient#CreateOrUpdate: Failure responding to request: StatusCode=201 -- Original Error: autorest/azure: Service returned an error. Status=201 Code="Unknown" Message="Unknown service error"
```

**Comment by SlOrbA** [comment]
Looks like a duplicate for Issue #1762

**Comment by tombuildsstuff** [comment]
@SlOrbA thanks for the heads up - so that we can track this in a single place I'm going to close this in favour of #1762
