### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment shows incorrect changes during plan

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#1784]
### Terraform Version

```
Terraform v0.11.8
+ provider.azurerm v1.13.0
```

### Affected Resource(s)

`azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

Terraform files can be found here - https://gist.github.com/rohrerb/4b449b778a6d902014f580a34e7390df

File format as follows:

- module/linux/main.tf
- module/linux/variables.tf
- main.tf

### Expected Behavior

The first VM shouldn't have any changes when we increment the VM count. 

### Actual Behavior

The first [0] VM's `azurerm_virtual_machine_data_disk_attachment` resource is prompting for change. 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3.  After the creation you will have a VM with a disk which is attached.
4.  Increment `instance_count` from 1 to 2 in main.tf 
5. `terraform apply`

You will see that the first VM disk attach is wanting to be modified.  

```
-/+ module.x11x.azurerm_virtual_machine_data_disk_attachment.data_disk_attach[0] (new resource required)
      id:                                                                 "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/TUS1E11-Web/providers/Microsoft.Compute/virtualMachines/tus1e11x11x001/dataDisks/tus1e11x11x001-datadisk1" => <computed> (forces new resource)
      caching:                                                            "ReadOnly" => "ReadOnly"
      create_option:                                                      "Attach" => "Attach"
      lun:                                                                "0" => "0"
      managed_disk_id:                                                    "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/TUS1E11-Web/providers/Microsoft.Compute/disks/tus1e11x11x001-datadisk1" => "${element(azurerm_managed_disk.data_disk.*.id, count.index)}" (forces new resource)
      virtual_machine_id:                                                 "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/TUS1E11-Web/providers/Microsoft.Compute/virtualMachines/tus1e11x11x001" => "${element(azurerm_virtual_machine.vm.*.id, ceil((count.index + 1) * 1.0 / var.data_disk_count) - 1)}" (forces new resource)
      write_accelerator_enabled:                                          "false" => "false"
```

The interesting part is **that it will go away** if you just apply the 2nd vm & disk creation.  

6.  `terraform apply -target module.x11x.azurerm_managed_disk.data_disk[1] -target module.x11x.azurerm_virtual_machine.vm[1]`
7. `terraform plan`

The `module.x11x.azurerm_virtual_machine_data_disk_attachment.data_disk_attach[0]` is no longer prompting.   I did nail it down to the `managed_disk_id` which is causing the resource mod, but no clue why yet. 

Any ideas?

FYI - @tombuildsstuff

**Comment by jcmaasb** [comment]
I have not thoroughly reviewed your code, but I think your problem is related to the "element ()" function

Check these threads:
https://github.com/hashicorp/terraform/issues/3449
https://github.com/hashicorp/terraform/issues/17014

**Comment by rohrerb** [comment]
Hi @jcmaasb - Not related to either of the issues you mentioned.

**Comment by tombuildsstuff** [comment]
hey @rohrerb 

Thanks for opening this issue - apologies for the delayed response here!

There's a couple of known issues with `count` in Terraform 0.11 in conjunction with the splat operator and `element` - for example when the number of items in a list changes. My understanding is that these may be fixed as a part of Terraform 0.12, but in the interim it may be possible to work around the issue with the `element/splat/count` issue by switching to use the `[]` syntax rather than `element()` e.g.

```
resource "azurerm_virtual_machine_data_disk_attachment" "data_disk_attach" {
  count =   "${var.instance_count == 0 ? 0 : var.instance_count * var.data_disk_count}"
  virtual_machine_id    = "${azurerm_virtual_machine.vm[ceil((count.index + 1) * 1.0 / var.data_disk_count) - 1)].id}"
  managed_disk_id    = "${azurerm_managed_disk.data_disk[count.index].id}"
  lun                = "${floor((count.index +1) / ceil((count.index + 1) * 1.0 / var.data_disk_count)) - 1}"
  caching            = "ReadOnly"
  create_option      = "Attach"
}
```

Would you be able to take a look and see if that works for you?

Thanks!

**Comment by rohrerb** [comment]
Hi @tombuildsstuff,

Thank you for the suggestion.  That fixed my issue...

Looking forward to 0.12 :D

**Comment by tombuildsstuff** [comment]
@rohrerb glad to hear that's now working for you :) Since this has now been resolved I'm going to  close this issue for the moment.
