### ISSUE TITLE
Application Gateway HTTP Settings missing property

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.11.7`
`azurerm 1.13.0`

### Affected Resource(s)

* azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "appgw" {
  name                = "${var.appgw_name}"
  location            = "${data.terraform_remote_state.rg.rglocation}"
  resource_group_name = "${data.terraform_remote_state.rg.rgname}"

  sku {
    name     = "WAF_Medium"
    tier     = "WAF"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "AppGW-ip-configuration"
    subnet_id = "${data.terraform_remote_state.rg.vnetid}/subnets/${data.terraform_remote_state.rg.sn1name}"
  }

  frontend_port {
    name = "${data.terraform_remote_state.rg.vnetname}-feport"
    port = 80
  }

  frontend_ip_configuration {
    name                 = "${data.terraform_remote_state.rg.vnetname}-feip"
    public_ip_address_id = "${azurerm_public_ip.pip.id}"
  }

  http_listener {
    name                           = "${var.listener_name}"
    frontend_ip_configuration_name = "${data.terraform_remote_state.rg.vnetname}-feip"
    frontend_port_name             = "${data.terraform_remote_state.rg.vnetname}-feport"
    protocol                       = "HTTP"
  }

  # Configuration for API web app
  backend_address_pool {
    name            = "${var.apiapp_name}-beap"
    fqdn_list       = ["${var.apiapp_name}.${var.domain_name_private}"]
  }

  probe {
    name                = "${var.apiapp_name}-probe"
    path                = "/"
    protocol            = "Http"
    host                = "${var.apiapp_name}.${var.domain_name_private}"
    interval            = 30
    timeout             = 30
    unhealthy_threshold = 3
  }

  backend_http_settings {
    name                  = "${var.apiapp_name}"
    cookie_based_affinity = "Disabled"
    port                  = "${var.apiapp_port}"
    protocol              = "Http"
    request_timeout       = 30
    probe_name            = "${var.apiapp_name}-probe"
  }

  # Configuration for UI web app
  backend_address_pool {
    name            = "${var.uiapp_name}-beap"
    fqdn_list       = ["${var.uiapp_name}.${var.domain_name_private}"]
  }

  probe {
    name                = "${var.uiapp_name}-probe"
    path                = "/"
    protocol            = "Http"
    host                = "${var.uiapp_name}.${var.domain_name_private}"
    interval            = 30
    timeout             = 30
    unhealthy_threshold = 3
  }

  backend_http_settings {
    name                  = "${var.uiapp_name}"
    cookie_based_affinity = "Disabled"
    port                  = "${var.uiapp_port}"
    protocol              = "Http"
    request_timeout       = 30
    probe_name            = "${var.uiapp_name}-probe"
  }

  request_routing_rule {
    name                       = "${var.rule_name}"
    rule_type                  = "PathBasedRouting"
    http_listener_name         = "${var.listener_name}"
    backend_address_pool_name  = "${data.terraform_remote_state.ase.asename}-beap"
    backend_http_settings_name = "${var.uiapp_name}"
    url_path_map_name          = "${var.rule_name}"
  }

  url_path_map {
    name = "${var.rule_name}"
    default_backend_address_pool_name = "${var.uiapp_name}-beap"
    default_backend_http_settings_name = "${var.uiapp_name}"

    path_rule {
      name = "${var.apiapp_name}"
      paths = ["/api*"]
      backend_address_pool_name = "${var.apiapp_name}-beap"
      backend_http_settings_name = "${var.apiapp_name}"
    }
  }

  # WAF Configuration
  waf_configuration {
    enabled          = "true"
    firewall_mode    = "Detection"
    rule_set_type    = "OWASP"
    rule_set_version = "3.0"
  }
}
```

### Expected Behavior

The config should create an WAF configured Application Gateway with a single Listener objects, 2 HTTP Settings objects, 2 Backend pool objects, 2 Health Probe objects, and a single Path Based Rule.  The default backend pool on the Path-based rule should point to the ${var.uiapp_name}-beap backend pool and there should be a route called ${var.apiapp_name} that maps /api* to the ${var.apiapp_name}-beap backend pool and the ${var.apiapp_name} HTTP Settings object.

The architecture that this Application Gateway is being deployed into has the gateway sitting in front of an ILB ASE.  The ILB ASE relies on host header names in order to route traffic to the correct WebApp sitting inside the ASE.

The desired behavior of the resultant Application Gateway is that when a user browses to http://${var.uiapp_name}.domainname.com they should be taken to http://${var.uiapp_name}.${var.domain_name_private} and then when a user browses to http://${var.uiapp_name}.domainname.com/api they should be taken to http://${var.apiapp_name}.${var.domain_name_private}.

### Actual Behavior

The Application Gateway does get created with the included config but there are some key pieces missing from the HTTP Setting objects that break the functionality.  There is currently no way to set the "Override backend path" property on the HTTP Setting object.  This setting is required for our configuration to get the /api mapping to route to http://${var.apiapp_name}.${var.domain_name_private}.  I previously create Feature request 1760 to have this ability added to the resource.

The other key missing component is the absence of the host header name written to the HostName field of the HTTP Setting object.  While this field is not exposed in the portal UI for the object, it is readily visible when querying the object with PowerShell.  This property gets automatically populated when creating the HTTP Setting object manually thru the portal.  When creating via PowerShell, this field is populated by using the "-Hostname" argument with the Set-AzureRmApplicationGatewayBackednHttpSettings cmdlet.
### Steps to Reproduce

1. `terraform apply`

### References

* #1760

**Comment by tombuildsstuff** [comment]
hey @Phydeauxman 

Thanks for opening this issue - apologies for the delayed response here!


> The Application Gateway does get created with the included config but there are some key pieces missing from the HTTP Setting objects that break the functionality. There is currently no way to set the "Override backend path" property on the HTTP Setting object. This setting is required for our configuration to get the /api mapping to route to http://${var.apiapp_name}.${var.domain_name_private}. I previously create Feature request 1760 to have this ability added to the resource.

> The other key missing component is the absence of the host header name written to the HostName field of the HTTP Setting object. While this field is not exposed in the portal UI for the object, it is readily visible when querying the object with PowerShell. This property gets automatically populated when creating the HTTP Setting object manually thru the portal. When creating via PowerShell, this field is populated by using the "-Hostname" argument with the Set-AzureRmApplicationGatewayBackednHttpSettings cmdlet.

These feature requests are being tracked in #1760 and #1875 respectively -rather than having multiple issues open tracking the same issue - I'm going to close this issue in favour of those two issues for the moment

Thanks!
