### ISSUE TITLE
Failure sending storage account create requests

### ISSUE THREAD

**Issue by subesokun** [terraform-providers/terraform-provider-azurerm#1796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.13.0

### Affected Resource(s)

* azurerm_storage_account

### Panic Output

```
* azurerm_storage_account.mystorage: Error creating Azure Storage Account "mystorage": storage.AccountsClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="RequestIsNotValidJson" Message="The request cannot be interpreted as valid Json: {\"kind\":\"Storage\",\"location\":\"westeurope\",\"properties\":{\"encryption\":{\"services\":{\"blob\":{\"enabled\":true},\"file\":{\"enabled\":true}},\"keySource\":\"Microsoft.Storage\"},\"networkAcls\":{\"defaultAction\":\"Allow\"},\"supportsHttpsTrafficOnly\":false},\"sku\":{\"name\":\"Standard_GRS\"},\"tags\":{}}."
```

### Expected Behavior

TF should create the storage account

### Actual Behavior

TF fails with the above listed error

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

TF apply worked until this morning and no changes have been introduced since then. Maybe something is wrong or changed within the Azure API?

**Comment by alanwales** [comment]
We also experienced this behaviour (worked fine yesterday, not today).

Interestingly enough we get exactly the same issue from the Azure Portal itself, so it looks like you cannot create a storage account in the West Europe data center:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"RequestIsNotValidJson\",\r\n \"message\": \"The request cannot be interpreted as valid Json: {\\\"sku\\\":{\\\"name\\\":\\\"Standard_LRS\\\"},\\\"kind\\\":\\\"Storage\\\",\\\"location\\\":\\\"westeurope\\\",\\\"properties\\\":{\\\"supportsHttpsTrafficOnly\\\":false,\\\"encryption\\\":{\\\"services\\\":{\\\"blob\\\":{\\\"enabled\\\":true},\\\"file\\\":{\\\"enabled\\\":true}},\\\"keySource\\\":\\\"Microsoft.Storage\\\"}}}.\"\r\n }\r\n}"}]}

**Comment by subesokun** [comment]
https://twitter.com/dtretyakov/status/1031468141635952641

**Comment by subesokun** [comment]
Closing as it's not a provider issue but an issue with the Azure WestEurope region itself. Paired region North Europe works.
