### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment import causes issues with create_option

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#1797]
### Terraform Version

```
Terraform v0.11.8
+ provider.azurerm v1.13.0
```

### Affected Resource(s)

`azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

main.tf - https://gist.github.com/rohrerb/3a2e227076213b734e449b7cd842c2c5

### Actual Behavior

Goal is to migrate existing disks into the new resource `azurerm_virtual_machine_data_disk_attachment` so that we can leverage count to attach multiple disks.   

Our existing VM's were created using: 

```
 storage_data_disk {
    name              = "${format("%s%03d", local.base_hostname, count.index + 1)}-datadisk1"
    create_option     = "Empty"
    lun               = 0
    disk_size_gb      = 5
    caching           = "ReadOnly"
    managed_disk_type = "Standard_LRS"
  }   
```

We then import disks using the following commands:

```
terraform import azurerm_managed_disk.data_disk /subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/USTV-Web/providers/Microsoft.Compute/disks/USTVlxyz001-datadisk1

terraform import azurerm_virtual_machine_data_disk_attachment.data_disk_attach /subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/USTV-Web/providers/Microsoft.Compute/virtualMachines/USTVlxyz001/dataDisks/USTVlxyz001-datadisk1
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3.  After the creation you will have a VM with a disk which is attached.
4.  Run the above import commands to import the disk into the `azurerm_managed_disk` and `azurerm_virtual_machine_data_disk_attachment`
5. Comment out the `storage_data_disk` block in `azurerm_virtual_machine` 
6. Increment the variable `data_disk_count` to 1
7. `terraform plan` 

You will see that `azurerm_virtual_machine_data_disk_attachment.data_disk_attach` is forcing a new resource because of `create_option`:

```
-/+ azurerm_virtual_machine_data_disk_attachment.data_disk_attach (new resource required)
      id:                        "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/USTV-Web/providers/Microsoft.Compute/virtualMachines/USTVlxyz001/dataDisks/USTVlxyz001-datadisk1" => <computed> (forces new resource)
      caching:                   "ReadOnly" => "ReadOnly"
      **create_option:             "Empty" => "Attach" (forces new resource)**
      lun:                       "0" => "0"
      managed_disk_id:           "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/USTV-Web/providers/Microsoft.Compute/disks/USTVlxyz001-datadisk1" => "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/USTV-Web/providers/Microsoft.Compute/disks/USTVlxyz001-datadisk1"
      virtual_machine_id:        "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/USTV-Web/providers/Microsoft.Compute/virtualMachines/USTVlxyz001" => "/subscriptions/55546ce0-6c1c-40d0-98dd-007c68adfcd6/resourceGroups/USTV-Web/providers/Microsoft.Compute/virtualMachines/USTVlxyz001"
      write_accelerator_enabled: "false" => "false"

```

We can get around this by putting `create_option = "Empty"` on the `azurerm_virtual_machine_data_disk_attachment`.  However this doesn't help us.  Leaving  `create_option = "Empty"` will break adding any new disks, `attach` is needed to create new disks.    **Lets test this...**

8. Add  `create_option = "Empty" under `azurerm_virtual_machine_data_disk_attachment` 
9. `terraform plan` > You will see **no changes**.
10.  Increment the variable `data_disk_count` to 2.
11. `terraform apply` > You will see that `azurerm_virtual_machine_data_disk_attachment` changed for disk 1 which is another open GHI #1784 (ignore that).

You will get a error that you can't attach with `Empty`.  

Error: Error applying plan:

> 1 error(s) occurred:
> 
> * azurerm_virtual_machine_data_disk_attachment.data_disk_attach[1]: 1 error(s) occurred:
> 
> * azurerm_virtual_machine_data_disk_attachment.data_disk_attach.1: Error updating Virtual Machine "USTVlxyz001" (Resource Group "USTV-Web") with Disk "USTVlxyz001-datadisk2": compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameterConflictingProperties" Message="The property 'dataDisk.managedDisk.id' cannot be used together with property 'dataDisk.createOption'."
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.

We also tried modifying the state for existing disks which were marked as `Empty` > `Attach`, which didn't work.

This is blocking us on migrating large environments into the new resource `azurerm_virtual_machine_data_disk_attachment`.  We can't recreate these disks which is why we are forced to import them.

Any help or guidance would be appreciated.

cc @tombuildsstuff 

-Brandon

**Comment by tombuildsstuff** [comment]
hi @rohrerb 

Since #1600 has now been fixed and there's a suggest solution to this issue above I'm going to close this issue for the moment; but please let us know if you're still seeing this issue with the updated configuration on the latest version of the provider.

Thanks1
