### ISSUE TITLE
azurerm_virtual_machine os_profile custom_data changes aren't detected

### ISSUE THREAD

**Issue by craigedmunds** [terraform-providers/terraform-provider-azurerm#1803]
When changing the contents of azurerm_virtual_machine os_profile custom_data (as I want a different startup script) terraform doesn't detect the change at all. I would expect the VM to be recreated. Have tested up to v0.11.8

Is there some fundamental reason this doesn't work, or workaround that i can use to workaround this? Have tried:
* using depends_on with a null_resource
* sticking a hash of the custom_data somewhere that would then trigger a change (admin_password, computer_name)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tombuildsstuff** [comment]
hi @craigedmunds 

Thanks for opening this issue. This bug's previously been reported in #148 which I'm going to close this issue in favour of - would you mind subscribing to that issue for updates?

Thanks!

**Comment by craigedmunds** [comment]
Thanks @tombuildsstuff - apologies for not finding that issue!
