### ISSUE TITLE
changing the contents of a azurerm_storage_blob source

### ISSUE THREAD

**Issue by craigedmunds** [terraform-providers/terraform-provider-azurerm#1804]
When changing the contents of a azurerm_storage_blob source terraform doesn't detect the change at all. I would expect the blob to be updated. Have tested up to v0.11.8

Is there some fundamental reason this doesn't work, or workaround that i can use to workaround this? The only way i've been able to get it to work is to put a hash of the file content into the name, but this is likely to cause unexpected issues!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by perbergland** [comment]
Yes, the ContentMD5 property of the blob should be checked against a locally calculated hash so you don't have to manually taint the blob every time you update it,

**Comment by tombuildsstuff** [comment]
hey @craigedmunds @perbergland @passbt 

I'm going to close this issue in favour of #1990 which I believe should resolved this - please subscribe to that for updates :)

Thanks!
