### ISSUE TITLE
Cannot import Storage Account container

### ISSUE THREAD

**Issue by alexvicegrab** [terraform-providers/terraform-provider-azurerm#1830]
How can I import a container I have previously created in a Storage Account?

The following link does not provide information on how to do this, unlike that of storage_account:

https://www.terraform.io/docs/providers/azurerm/r/storage_container.html

Thanks in advance!

**Comment by tombuildsstuff** [comment]
hey @alexvicegrab 

Thanks for opening this issue :)

I've recently opened https://github.com/terraform-providers/terraform-provider-azurerm/pull/1816 which adds support for importing all of the Storage Resources - which should be merged for the next release.

Thanks!

**Comment by alexvicegrab** [comment]
Thank you for the swift response @tombuildsstuff

**Comment by tombuildsstuff** [comment]
hey @alexvicegrab 

Just to let you know that this has been released in v1.14.0 of the AzureRM Provider which is now available: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.14.0/CHANGELOG.md

Thanks!

**Comment by alexvicegrab** [comment]
Thank you very much for the heads up @tombuildsstuff
