### ISSUE TITLE
AzureRM Multiple Subscriptions with different providers

### ISSUE THREAD

**Issue by ranokarno** [terraform-providers/terraform-provider-azurerm#1831]
Hi,

I am trying to work on Azurerm with multiple subscriptions, and therefore will have more than 1 providers in my code.

While creating individual resources are working fine with different provider, but it does not work well when using Module.

I saw similar issue which related with AWS by assigning provider in module, but there is no reference in AzureRM.

Thanks,
Rano

### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
* provider.azurerm v1.13.0

### Terraform Configuration Files
`provider "azurerm" {
  subscription_id = "abc1"
  client_id       = ""
  client_secret   = ""
  tenant_id       = "abc"
}

provider "azurerm" {
  alias  = "sub2"
  subscription_id = "abc2"
  client_id       = ""
  client_secret   = ""
  tenant_id       = "abc"
}

resource "azurerm_resource_group" "vnet1" {
  name     = "rg-vnet1"
  location = "southeastasia"
}

resource "azurerm_resource_group" "vnet2" {
  provider = "azurerm.sub2"
  name     = "rg-vnet2"
  location = "southeastasia"
}

module "vnet1" { 
    source          = "modules/vnets"
    name        = "vnet1"
    vnet-prefix = "10.10.0.0/16"
    rsg-name        = "rg-vnet1"
}

module "vnet2" {
    source          = "modules/vnets"
    name        = "vnet2"
    vnet-prefix = "10.20.0.0/16"
    rsg-name        = "rg-vnet2"

    **providers = {
        azurerm = "azurerm.nsi"  <-- not supported provider inside module
    }**

}
`

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

## Error output
`$ terraform plan

Error: module "vnet2": cannot pass non-existent provider "azurerm.sub1"
`

### Related issue
[https://www.terraform.io/docs/modules/usage.html](url)

**Comment by kevinneufeld** [comment]
ranokarno, 
given the above example, you would need to pass the provider explicitly in your module block.

In you
```hcl 
provider "azurerm" {
  subscription_id = "abc1"
  client_id = ""
  client_secret = ""
  tenant_id = "abc"
}

provider "azurerm" {
  alias = "sub2"
  subscription_id = "abc2"
  client_id = ""
  client_secret = ""
  tenant_id = "abc"
}

resource "azurerm_resource_group" "vnet1" {
  name = "rg-vnet1"
  location = "southeastasia"
}

resource "azurerm_resource_group" "vnet2" {
  name = "rg-vnet2"
  location = "southeastasia"
}

module "vnet1" {
  source = "modules/vnets"
  name = "vnet1"
  vnet-prefix = "10.10.0.0/16"
  rsg-name = "rg-vnet1"
}

module "vnet2" {
  source = "modules/vnets"
  name = "vnet2"
  vnet-prefix = "10.20.0.0/16"
  rsg-name = "rg-vnet2"
  providers {
    azurerm = "azurerm.sub2"
  }
}
```

**Comment by ranokarno** [comment]
thanks @kevinneufeld , I notice this is a syntax error problem.
