### ISSUE TITLE
Automatically enable Diagnostic Settings at resource creation using a Resource Manager template

### ISSUE THREAD

**Issue by VaijanathB** [terraform-providers/terraform-provider-azurerm#1834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently ARM supports Diagnositic Settings at resource creation which is increasingly used by customers. Here is the link that explains how to do it. https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-enable-diagnostic-logs-using-template
This would be really usefull feature. 

### New or Affected Resource(s)

All Non Compute Resources. 

### References
https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-enable-diagnostic-logs-using-template

**Comment by tombuildsstuff** [comment]
Given there's already a PR for this - creating a new issue to track an existing PR seems unnecessary - as such I'm closing this in favour of #1291

**Comment by VaijanathB** [comment]
Great. Apologies for the duplication. Somehow did not find this.
