### ISSUE TITLE
azurerm_template_deployment should not display sensitive information during apply

### ISSUE THREAD

**Issue by iszekely** [terraform-providers/terraform-provider-azurerm#1838]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `azurerm_template_deployment` resource prints all parameters on screen when applied. These parameters might contain passwords or other sensitive information. For example, in case of an HDInsight deployment, clusterLoginPassword, sshPassword, hivePassword, identityCertificate, and identityCertificatePassword are all sensitive data. However, they are printed on screen.

When the resource reads the template, it should read the type information for the parameters. If the type is `SecureString`, the same `<sensitive>` string should be printed instead, just like for sensitive outputs.

### New or Affected Resource(s)

* azurerm_template_deployment

### References

* #37

**Comment by tombuildsstuff** [comment]
hi @iszekely 

Thanks for opening this issue :)

Within Terraform the attributes of a resource (and if they are required/optional/sensitive, etc.) is defined in the Schema - which Terraform Core requires is a static representation of an object. As such unfortunately there's no way for us to conditionally apply logic to make this field conditionally sensitive. In addition - it's possible that this field could contain information which isn't sensitive (and is useful to show the difference between each of the fields, which we're interested in improving in the future) to identify what's changed.

As I don't see a path forward for this issue which would allow us to support this in the Provider code at this time I'm going to close this issue for the moment.

Thanks!

**Comment by tylerfox** [comment]
Hi, I'm from the HDInsight team. I can look into this, but I have not been able to reproduce the issue. I have tried making a PUT request to create a cluster followed by a GET request to view the cluster details, but did not see any sensitive fields printed in the response. Could you give me an example of an API request that returns sensitive parameters? Thanks.

**Comment by iszekely** [comment]
Hi @tylerfox 
Thanks for your reply. It think the issue is purely related to Terraform. It stores everything in its state file, so it can (and does) display everything it can. As you can see, Tom has already answered it too, and what he wrote makes sense, but it's a bit unfortunate on the other hand.

**Comment by tylerfox** [comment]
@tombuildsstuff I'd be happy to coordinate with you and your team to dig into this more and look for a solution.
