### ISSUE TITLE
Add Support for EnableAggregationPipeline Capability in Cosmos DB (Mongo)

### ISSUE THREAD

**Issue by jamesggraf** [terraform-providers/terraform-provider-azurerm#1848]
### Description

Cosmos DB has added a preview feature to enable aggregation pipelines to its implementation of Mongo. In Cosmos parlance this feature is called `EnableAggregationPipeline`

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_account" "db" {
  name                = "my-cosmos-db"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  offer_type          = "Standard"
  kind                    = "MongoDB"

  enable_automatic_failover = false
  capabilities        = [{
    name = "EnableAggregationPipeline"
  }]
}
```

### References

More information about this capability can be found here:

* https://azure.microsoft.com/en-us/updates/azure-documentdb-now-supports-aggregate-functions/

**Comment by jamesggraf** [comment]
I've created a PR for this feature. I've never written anything in Go and I'm not sure how to test this so please be gentle :)

https://github.com/terraform-providers/terraform-provider-azurerm/pull/1849

**Comment by katbyte** [comment]
Blocked on https://github.com/Azure/azure-sdk-for-go/issues/2864

**Comment by brunofurmon** [comment]
I actually had to come to this issue to find out how to configure the **capabilities** parameter of the azurerm module. Documentation lacks the correct format it needs to accept the parameter.
