### ISSUE TITLE
azure_iothub, free sku Failure sending request:

### ISSUE THREAD

**Issue by thoregilk** [terraform-providers/terraform-provider-azurerm#1854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.13.0
+ provider.null v1.0.0

### Affected Resource(s)

azurerm_iothub

### Terraform Configuration Files

```hcl
  module "iot_hub_bringup" {
  source = "../../modules/iot_hub?ref=master"
  name        = "bringup"

  location              = "${var.location}"
  resource_group_name   = "${module.rg_default.resource_group_name}"
  sku_name              = "F1"
  sku_tier              = "Free"
  capacity              = "1"
}

resource "azurerm_iothub" "default" {
  name                = "${module.name_label.name}"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.location}"
  tags                = "${module.null_label.tags}"

  sku {
    name = "${var.sku_name}"
    tier = "${var.sku_tier}"
    capacity = "${var.capacity}"
  }
  
}
```

### Expected Behavior

Create new resources on the Free plan

### Actual Behavior
module.iot_hub_bringup.azurerm_iothub.default: Creating...
  hostname:               "" => "<computed>"
  location:               "" => "westeurope"
  name:                   "" => "iot-we-internal-bringup-prod"
  resource_group_name:    "" => "rg-we-internal-prod"
  shared_access_policy.#: "" => "<computed>"
  sku.#:                  "" => "1"
  sku.0.capacity:         "" => "1"
  sku.0.name:             "" => "F1"
  sku.0.tier:             "" => "Free"
  tags.%:                 "" => "4"
  tags.Environment:       "" => "prod"
  tags.Name:              "" => "iot-we-internal-bringup-prod"
  tags.Namespace:         "" => "internal"
  tags.Stage:             "" => "<computed>"
  type:                   "" => "<computed>"

Error: Error applying plan:
1 error(s) occurred:

* module.iot_hub_bringup.azurerm_iothub.default: 1 error(s) occurred:
* azurerm_iothub.default: Error creating/updating IotHub "iot-we-internal-bringup-prod" (Resource Group "rg-we-internal-prod"): devices.IotHubResourceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: json: cannot unmarshal number into Go struct field serviceError2.code of type string

### Steps to Reproduce

1. `terraform apply`

**Comment by thoregilk** [comment]
Never mind, the issue was that the total number of Free Tiers can not exceed 1 per subscription.

If possible, error message should be a bit more descriptive

**Comment by tombuildsstuff** [comment]
hey @thoregilk 

Thanks for opening this issue :)

> Original Error: json: cannot unmarshal number into Go struct field serviceError2.code of type string

Taking a quick look into this - I believe this issue will be solved by upgrading to the next version of the Azure SDK for Go/Go-Autorest - which we'll be picking up next week once #1746 is merged.

> Never mind, the issue was that the total number of Free Tiers can not exceed 1 per subscription.

We should also update the documentation to mention this in the interim

Thanks!

**Comment by zhughes3** [comment]
I am having a similar error trying to create an IoTHub with the Standard tier. I listed my issue [here:](https://github.com/hashicorp/terraform/issues/19968)

I can provide more information if needed. Any help would be greatly appreciated.
