### ISSUE TITLE
The resource azurerm_role_assignment is not state aware

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#1857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)

provider.azurerm v1.5.0
terraform 0.11.7
resource azurerm_role_assignment

### Actual Behavior

If a role is already assigned Terraform returns an Error saying that the role is already assigned.
Other Terraform resource like azurerm_resource_group or azurerm_virtual_network will just not return an error and the Terraform tfstate will integrate this resource as a compliant one.

```hcl
Error: Error applying plan:

1 error(s) occurred:

* module.Enable-AzureRmRoleAssignment.azurerm_role_assignment.assignments: 1 error(s) occurred:

* azurerm_role_assignment.assignments: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

1.  Assign a role manually
2. Try assigning it with Terraform, see this how to for example : https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html

Note : you can also assign the role through Terraform, remove your tfstate and re apply your Terraform code

**Comment by tombuildsstuff** [comment]
hey @JamesDLD 

Thanks for opening this issue :)

This is actually a bug in the AzureRM Provider where the Azure API's allow Upserts in most cases (without tracking items in the state) - #1746 includes a fix to every resource where every resource will require Importing into the State before it can be updated (otherwise an error will be displayed saying `please import this via ...`).

Thanks!

**Comment by sebader** [comment]
sorry to resurface this one, but it still does not seem to be fixed. I am also still getting the same error if a role assignment already exists. Using latest version of terraform and the azurerm provider.
Any guidance?
