### ISSUE TITLE
Support for pickHostnameFromBackendAddress setting on Application Gateway

### ISSUE THREAD

**Issue by ndarilek** [terraform-providers/terraform-provider-azurerm#1875]
I've been trying to set up an application gateway that proxies to two backend apps by FQDN. Unfortunately, with a configuration as generated by Terraform, this setup doesn't seem to work. Requests hit an application gateway with a `Host:` header like staging.example.com. Then they're proxied to a backend app on azurewebsites.net which expects a hostname like app-staging.azurewebsites.net, only the header still contains the original FQDN, so the app returns a 404 even though it is up. I can reach the backend by hitting the gateway IP with Curl and manually setting the host header to match the FQDN of the backend, but I don't have control over the headers after they traverse the gateway.

Dialogues with Azure support and Google searches led me to [this](http://devchat.live/en/2018/07/02/how-to-map-url-path-based-rules-in-application-gateway-for-your-azure-web-app-service/) and [this](https://medium.com/@stephen.weinrich/configuring-azure-traffic-manager-application-gateway-and-app-services-with-terraform-57afce390fa1) which hopefully shed a little more light on the issue. I'm fairly new to Azure, so hopefully the above gives enough of an indication of what I hope can be supported, but I'm happy to answer any additional questions if I can.

Thanks!

**Comment by mdsills** [comment]
hopefully PR2658 https://github.com/terraform-providers/terraform-provider-azurerm/pull/2658 addresses this issue

**Comment by agrcrobles** [comment]
that's great! when are you creating a new stable release? is it even possible to consume the provider from master branch?

**Comment by tombuildsstuff** [comment]
Closing since this has been fixed via #2658

@agrcrobles it's possible to build this provider locally (there's [instructions for how to do that in the README](https://github.com/terraform-providers/terraform-provider-azurerm#building-the-provider)) - otherwise I expect we'll be doing a release this week :)

Thanks!

**Comment by stonefury** [comment]
This only added support to check the box "pick hostname from backend".  It is missing (I believe) the hostname field that you can provide to pass the hostname of your choice to the header.

![image](https://user-images.githubusercontent.com/4722084/53659290-086cc480-3c10-11e9-96cf-63dd8e2577a0.png)
