### ISSUE TITLE
azurerm_lb fails with "invalid URI for request"

### ISSUE THREAD

**Issue by PleaseStopAsking** [terraform-providers/terraform-provider-azurerm#1880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.34.0
+ provider.azurerm v1.13.0
+ provider.random v2.0.0
+ provider.template v1.0.0

### Affected Resource(s)

azurerm_lb

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "IlbSubnet" {
  name                      = "Ilb"
  virtual_network_name      = "${azurerm_virtual_network.vnet.name}"
  resource_group_name       = "${azurerm_resource_group.rg.name}"
  address_prefix            = "${var.network["ilbSubnetPrefix"]}"
  network_security_group_id = "${azurerm_network_security_group.networkSecurityGroup.id}"
}

resource "azurerm_lb" "ServerIlb" {
  name                = "${var.deployInfo["customerProject"]}${var.deployInfo["environment"]}${var.machineAcronyms["Server"]}-ilb"
  location            = "${var.deployInfo["azRegion"]}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  sku                 = "Standard"

  frontend_ip_configuration {
    name                          = "Server"
    subnet_id                     = "{azurerm_subnet.IlbSubnet.id}"
    private_ip_address_allocation = "Static"
    private_ip_address            = "${cidrhost(var.network["ilbSubnetPrefix"], 10)}"
  }
}
```

### Expected Behavior

It creates the Load Balancer.

### Actual Behavior

Template fails at the plan phase with the following error.

```hcl
Error: azurerm_lb.ServerIlb: Can not parse "frontend_ip_configuration.0.subnet_id" as a resource id: Cannot parse Azure ID: parse {azurerm_subnet.IlbSubnet.id}: invalid URI for request
```
If I remove the subnet_id line, it will plan successfully but fails on the apply phase because no subnet or public IP is specified.

### Steps to Reproduce

1. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @PleaseStopAsking 

Thanks for opening this issue :)

In this case you're seeing this error as the interpolation syntax used in the `subnet_id` field is incorrect (it's missing a `$` at the start) - would you be able to take a look and see if updating this to the following works for you?

```
    subnet_id                     = "${azurerm_subnet.IlbSubnet.id}"
```

Since this is a question about Terraform Configuration rather than a bug in the AzureRM Provider - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by PleaseStopAsking** [comment]
@tombuildsstuff 

If you stare at something long enough, you will start to glaze over the obvious issue it seems. That is certainly the root cause. The shame now sets in....

Thanks,

**Comment by tombuildsstuff** [comment]
@PleaseStopAsking no worries, glad to hear this is now working for you :)
