### ISSUE TITLE
Site Credentials / Trigger url

### ISSUE THREAD

**Issue by thoregilk** [terraform-providers/terraform-provider-azurerm#1881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to be able to reference the deployment trigger url on an webapp, and maby other settings on the properties blade of an webapp and an function app, but most of the information available is static or can be referenced else where like usernames - only the publishing password would be required.

At our environment this is used with GitLab to configure the webhooks and set up the pipelines, and it is currently a manual step to copy this from the portal, and adding it to git while we could have used the provider.

### New or Affected Resource(s)

* azurerm_function_app
* azurerm_app_service

### References

The information is currently available with Azure CLI, I am not aware if the value are exposed under "site_credential" export as the documentation states that it is only exported when scm_type is localgit if so, the scm_type requirements could be removed as the userPWD is the same for FTP deployment etc.

az webapp deployment list-publishing-profiles

**Comment by arichiardi** [comment]
I think my question #1965 is kind of related.

**Comment by thoregilk** [comment]
@arichiardi  I did some more testing on this, "site_credential" is available for references, and not just when using scm_type = localgit, also the url for kudu is static, so the "scm" needs to be referenced and just pass inn the name of the function app.

We are currently using it to set the webhooks in GitLab and also extract the ssh_rsa key for the deployment token.


${module.name_label.id}, is reference to a module we have to handle our naming convention, it could just as easily be ${azurerm_function_app.default.name}

```
data "http" "ssh_rsa" {
  url = "https://${azurerm_function_app.default.site_credential.0.username}:${azurerm_function_app.default.site_credential.0.password}@${module.name_label.id}.scm.azurewebsites.net/api/sshkey?ensurePublicKey=1"
}
```
```
resource "gitlab_project_hook" "webhook" {
count = "${var.enable_external_scm ? 1 : 0}"

  project                   = "${var.gitlab_group}/${var.gitlab_project}"
  url                       = "https://${azurerm_function_app.default.site_credential.0.username}:${azurerm_function_app.default.site_credential.0.password}@${module.name_label.id}.scm.azurewebsites.net/deploy"
  enable_ssl_verification   = true
  push_events               = true
}
```
