### ISSUE TITLE
Expected release of 1.14.0

### ISSUE THREAD

**Issue by stonefury** [terraform-providers/terraform-provider-azurerm#1883]
Sorry to write this question, I never learned how to contact another github user.

I am deploying managed disks in azure and have spent the past few days struggling to deal with what has been reported as a bug but @tombuildsstuff has put in a potential fix in 1.14.0. 

When can we expect 1.14.0 to be released? I might just stop trying to work-around the problem and wait.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @stonefury 

> When can we expect 1.14.0 to be released? I might just stop trying to work-around the problem and wait.

We don't generally comment on when the next release will be (since things can change) - however this is a case of good timing since I've just kicked off the release for v1.14 - so this should be available shortly :)

Thanks!
