### ISSUE TITLE
azurerm_app_service scm_type does not accept VSTSRM as an option

### ISSUE THREAD

**Issue by DinoSourcesRex** [terraform-providers/terraform-provider-azurerm#1888]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

I am deploying to my terraform infrastructure using VSTS.

However, based on the [documentation ](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#scm_type)(and trying myself), Terraform does not accept VSTSRM as a valid option for the `scm_type`.

It would be great if it did.

### New or Affected Resource(s)

azurerm_app_service

### Potential Terraform Configuration

```hcl

resource "azurerm_resource_group" "environment" {
  name     = "env-rg"
  location = "westindia"
}

resource "azurerm_app_service_plan" "sp01" {
  name                = "sp01"
  location            = "${azurerm_resource_group.environment.location}"
  resource_group_name = "${azurerm_resource_group.environment.name}"

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "appservice" {
  name                = "as"
  location            = "${azurerm_resource_group.environment.location}"
  resource_group_name = "${azurerm_resource_group.environment.name}"
  app_service_plan_id = "${azurerm_app_service_plan.sp01.id}"

  site_config {
    always_on = true
    scm_type  = "VSTSRM"
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @DinoSourcesRex  

Thanks for opening this issue :)

Support for this has previously been requested in #1104 - which I'm going to close this issue in favour of, please subscribe to that issue for updates.

Thanks!
