### ISSUE TITLE
azurerm_app_service_plan is failing

### ISSUE THREAD

**Issue by kalyanrajsista** [terraform-providers/terraform-provider-azurerm#1894]
Hi,

Starting yesterday night, I am getting this error while applying `terraform plan`. I see there is a new azurerm provider released yesterday and probably this might be causing the issue.

* azurerm_app_service_plan.app_service_plan
azurerm_app_service_plan.app_service_plan: web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

**Comment by kalyanrajsista** [comment]
@tombuildsstuff FYI.

**Comment by tombuildsstuff** [comment]
hi @kalyanrajsista 

Thanks for opening this issue.

So that we could investigate this further would it be possible to show the Terraform Configuration which returns this error? I'm wondering if this error was returned due to the recent outage in West Central US

Thanks!

**Comment by kalyanrajsista** [comment]
This issue appeared during the outage and I don't think outage is the real issue. One of my other team member had the same issue and later we found that issue could be because of Azure RM resource provider release v1.14. We pinned Azure RM provider to 1.13 in our code and didn't have any issues.

**Comment by kalyanrajsista** [comment]
Terraform Version
`2018-09-07T01:53:17.1438354Z Terraform version:`
`2018-09-07T01:53:26.7560452Z Terraform v0.11.8`

Terraform configuration

`2018-09-07T02:03:29.8277272Z Initializing the backend...`
`2018-09-07T02:03:30.2925595Z `
`2018-09-07T02:03:30.2927915Z Initializing provider plugins...`
`2018-09-07T02:03:30.7699282Z `
`2018-09-07T02:03:30.7706601Z The following providers do not have any version constraints in configuration,`
`2018-09-07T02:03:30.7706921Z so the latest version was installed.`
`2018-09-07T02:03:30.7707082Z `
`2018-09-07T02:03:30.7707296Z To prevent automatic upgrades to new major versions that may contain breaking`
`2018-09-07T02:03:30.7707587Z changes, it is recommended to add version = "..." constraints to the`
`2018-09-07T02:03:30.7708036Z corresponding provider blocks in configuration, with the constraint strings`
`2018-09-07T02:03:30.7716806Z suggested below.`
`2018-09-07T02:03:30.7717083Z `
`2018-09-07T02:03:30.7724085Z * provider.archive: version = "~> 1.1"`
`2018-09-07T02:03:30.7724418Z * provider.azurerm: version = "~> 1.14"`
`2018-09-07T02:03:30.7724708Z * provider.external: version = "~> 1.0"`
`2018-09-07T02:03:30.7724953Z * provider.null: version = "~> 1.0"`
`2018-09-07T02:03:30.7725754Z * provider.random: version = "~> 2.0"`
`2018-09-07T02:03:30.7726077Z * provider.template: version = "~> 1.0"`
`2018-09-07T02:03:30.7726420Z * provider.ultradns: version = "~> 0.1"`
`2018-09-07T02:03:30.7726638Z `
`2018-09-07T02:03:30.7726929Z Terraform has been successfully initialized! `

Actual Error

`2018-09-07T02:22:49.5524829Z Error: Error applying plan:`
`2018-09-07T02:22:49.5534443Z `
`2018-09-07T02:22:49.5558038Z 1 error(s) occurred:`
`2018-09-07T02:22:49.5558561Z `
`2018-09-07T02:22:49.5558917Z * azurerm_app_service_plan.app_service_plan: 1 error(s) occurred:`
`2018-09-07T02:22:49.5559118Z `
`2018-09-07T02:22:49.5559489Z * azurerm_app_service_plan.app_service_plan: web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- `
`Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>`
`2018-09-07T02:22:49.5559823Z `
`2018-09-07T02:22:49.5560259Z Terraform does not automatically rollback in the face of errors.`
`2018-09-07T02:22:49.5564950Z Instead, your Terraform state file has been partially updated with`
`2018-09-07T02:22:49.5566274Z any resources that successfully completed. Please address the error`
`2018-09-07T02:22:49.5567145Z above and apply again to incrementally change your infrastructure.`
`2018-09-07T02:22:49.5567395Z `
`2018-09-07T02:22:49.5578443Z `

**Comment by tombuildsstuff** [comment]
@kalyanrajsista are you still seeing this issue, or was this only during the outage? if so - would you be able to give an example Terraform Configuration which shows this issue? Thanks!

**Comment by tombuildsstuff** [comment]
Closing this since we've not heard back here - please feel free to reopen this with the associated Terraform Configuration if you're still seeing this.

Thanks!
