### ISSUE TITLE
azurerm_service_fabric_cluster upgrade_mode manual should be able to specify cluster_code_version

### ISSUE THREAD

**Issue by steve-hawkins** [terraform-providers/terraform-provider-azurerm#1906]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently we allow either 'Automatic' or 'Manual' for upgrade_mode of Service Fabric Clusters, when selecting 'Manual' we are left to the latest supported version.  It would be preferable if the version could be specified.

You could argue that with the rate at which Microsoft drops support for versions would mean latest would be acceptable, but realistically we would want to control the version of Service Fabric we are using.

### New or Affected Resource(s)

* azurerm_service_fabric_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_service_fabric_cluster" "service_fabric" {
  name                = "test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  reliability_level   = "Bronze"
  vm_image            = "Windows"
  management_endpoint = "https://test.cloudapp.azure.com:19080"

  node_type {
    name                 = "backend"
    instance_count       = 5
    is_primary           = true
    client_endpoint_port = 19000
    http_endpoint_port   = 19080
  }

  upgrade_mode         = "Manual"
  cluster_code_version = "6.3.176.9494"
}
```

**Comment by steve-hawkins** [comment]
I guess the complication around this will be searching for valid versions first:-

[ClusterCodeVersionsResult](https://github.com/Azure/azure-sdk-for-go/blob/master/services/servicefabric/mgmt/2018-02-01/servicefabric/models.go#L1405)

**Comment by tombuildsstuff** [comment]
@steve-hawkins given the error message is pretty clear here - I'd suggest we should be fine to rely on that message (at least for the moment).

In the future we could look to add some extra validation here would require reaching out to Azure (via the SDK, which would require credentials/an API client), which isn't populated during validation at the current time (since the API Client's aren't initialized until after validation's been applied - but potentially could be in the future)

Thanks!
