### ISSUE TITLE
Doc for application gateway is corrupt

### ISSUE THREAD

**Issue by claw-real** [terraform-providers/terraform-provider-azurerm#1907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* Website documentation

### Expected Behavior

The documentation on the website should be correct?
There seems to have been an error copying from the azure api source documentation.

The [azure api source doc](https://docs.microsoft.com/en-us/rest/api/application-gateway/applicationgateways/createorupdate#applicationgatewaysslcertificate)

has the following

properties.data | string | Base-64 encoded pfx certificate. Only applicable in PUT Request.

properties.password | string | Password for the pfx file specified in data. Only applicable in PUT request.

properties.publicCertData | string | Base-64 encoded Public cert data corresponding to pfx specified in data. Only applicable in GET request.

### Actual Behavior

The azurerm documentation online has the following

name - (Required) User defined name for an SSL certificate.

data - (Required) Base-64 encoded Public cert data corresponding to pfx specified in data. Only applicable in GET request.

password - (Required) Password for the pfx file specified in data. Only applicable in PUT request.

ie it looks like publiccertdata and data have been merged.

### Steps to Reproduce

Go to https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html

### Important Factoids

**Comment by tombuildsstuff** [comment]
This'll be fixed by #2054
