### ISSUE TITLE
[azurerm_scheduler_job] setting schedule to never end

### ISSUE THREAD

**Issue by hbuckle** [terraform-providers/terraform-provider-azurerm#1932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform -v
Terraform v0.11.8
+ provider.azurerm v1.15.0

### Affected Resource(s)

* azurerm_scheduler_job

### Terraform Configuration Files

```hcl
resource "azurerm_scheduler_job" "scheduler_job_1" {
  name                = "job1"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
  job_collection_name = "${azurerm_scheduler_job_collection.scheduler_job_collection.name}"
  state               = "enabled"

  action_storage_queue = {
    storage_account_name = "${azurerm_storage_account.storage_account.name}"
    storage_queue_name   = "${azurerm_storage_queue.storage_queue.name}"
    sas_token            = "${data.azurerm_storage_account_sas.storage_account_sas.sas}"
    message              = "${base64encode(file("${path.module}/message_job1.json"))}"
  }

  recurrence {
    frequency = "Minute"
    interval  = 15
  }
}
```

### Expected Behavior

I want to create a schedule that runs every 15 minutes and never ends

### Actual Behavior

The schedule is created and but is only set to run once

### Additional information

I'm not sure if this is an issue in Terraform or the SDK, but something is setting the `count` to 0 when the request is sent to the API:

```
PUT https: //management.azure.com/subscriptions/xxx/resourceGroups/schedule/providers/Microsoft.Scheduler/jobCollections/jobcollection/jobs/job1?api-version=2016-03-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.10.3 (amd64-windows) go-autorest/v10.15.4 Azure-SDK-For-Go/v20.1.0 scheduler/2016-03-01;HashiCorp-Terraform-v0.11.3
Content-Length: 577
Authorization: Bearer xxx
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip

{
  "properties": {
    "startTime": "2018-01-01T09:00:00Z",
    "action": {
      "type": "StorageQueue",
      "queueMessage": {
        "storageAccount": "xxx",
        "queueName": "xxx",
        "sasToken": "xxx",
        "message": "xxx"
      },
      "retryPolicy": {
        "retryType": "None"
      }
    },
    "recurrence": {
      "frequency": "minute",
      "interval": 15,
      "count": 0
    },
    "state": "enabled"
  }
}
```

**Comment by tombuildsstuff** [comment]
@katbyte would you be able to take a look into this?

**Comment by tombuildsstuff** [comment]
hi @hbuckle 

Apologies for the delayed reply to this.

Azure Scheduler is deprecated we're removing support for these resources in version 2.0 of the Azure Provider (more information can be found in #2807) - since this resource is being removed unfortunately this isn't something we're likely to fix in the Scheduler resource and as such I'm going to close this issue for the moment, however my understanding is that Azure Scheduler has been replaced by Azure Logic Apps.

Thanks!
