### ISSUE TITLE
Expose Application Gateway DNS record as an output

### ISSUE THREAD

**Issue by maxburke** [terraform-providers/terraform-provider-azurerm#1936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Our back-end services all have application gateways in front of them, and to make things easy for our front end developers we have friendly names (like api.urbanlogiq.ca) to point to our backend. 

Because the frontend IP configuration specifies that the provided IP needs to be dynamic, I am using CNAME records (azurerm_dns_cname_record) to point to the application gateway's DNS record (ie: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.cloudapp.net). Right now I am hardcoding the CNAME record to this cloudapp.net DNS address, but I could avoid doing so if the output of the application gateway resource included its DNS record.

### New or Affected Resource(s)

* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_dns_cname_record" "dnsc_centralca_prod_ulgate" {
  name                = "api"
  zone_name           = "${azurerm_dns_zone.dz_ul_ca.name}"
  resource_group_name = "${azurerm_resource_group.grp_infra_dns.name}"
  ttl                 = 3600

  # This is the current state:
  # record = "xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx.cloudapp.net"
  # This is what I would like:
  record = "${azurerm_application_gateway.ag_centralca_prod_ulgate.cname}"
}
```

**Comment by maxburke** [comment]
Not silly at all, @draggeta! I was thinking of the same thing, but the APG requires a dynamic IP address and I don't want to have to rush to update my (created) A-record should its IP address be changed without my knowledge. I would rather create a CNAME to the APG's CNAME.

**Comment by draggeta** [comment]
@maxburke Well, in that case, from what I can see, the FQDN is  not a property of the APG, but of the public IP assigned to it. See this *anonymized* example from one of mine:
```json
{
    "type": "Microsoft.Network/publicIPAddresses",
    "sku": {
        "name": "Basic",
        "tier": "Regional"
    },
    "name": "[parameters('publicIPAddresses_name')]",
    "apiVersion": "2018-02-01",
    "location": "westeurope",
    "scale": null,
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "00000000-0000-0000-0000-000000000000",
        "ipAddress": "192.0.2.100",
        "publicIPAddressVersion": "IPv4",
        "publicIPAllocationMethod": "Dynamic",
        "idleTimeoutInMinutes": 4,
        "dnsSettings": {
            "fqdn": "10000001-1001-1001-1001-100000000001.cloudapp.net",
            "domainNameLabel": "[parameters('publicIPAddresses_name_domainNameLabel')]"
        },
        "ipTags": []
    },
    "dependsOn": []
}
```
The CNAME can be exported from the IP address by referring to its fqdn property:
https://www.terraform.io/docs/providers/azurerm/d/public_ip.html#fqdn

**Comment by maxburke** [comment]
Brilliant, that works! I thought it wouldn't because these IPs wouldn't reverse DNS to a name. Many thanks for your help!
