### ISSUE TITLE
Feature Request: Support for Linux Container based Function Apps

### ISSUE THREAD

**Issue by wbreza** [terraform-providers/terraform-provider-azurerm#1937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Function apps now support being deployed as a docker image within a Linux app service plan.  The only primary difference in the underlying ARM properties are the following:

**kind**: `functionapp,linux,container`
**siteProperties/LinuxFxVersion**: `DOCKER|{path_to_registry}/{image_name}:{tag}`

**I don't have a PR yet but would like to volunteer to add support for this.**

Based on reading the threads for the referenced items its unclear how it would be best to handle the overloaded `kind` attribute to automatically be built based on other settings.

The default value for kind in function apps is `functionapp`.  If it's a linux app then it becomes `functionapp,linux` and finally if its a linux container the value is `functionapp,linux,container`

One option would be to dynamically build up the `kind` attribute based on inspecting the app_service_plan_id and other related properties.

Another approach vs. continuing with the `linux_fx_version` approach would be to split this configuration out into a common object with the properties required to configure a container

```hcl
container_config = {
    registry_url = "{path_to_registry}"
    image_name = "{image_name}"
    tag_name = "{tag_name}"
}
```

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "function_app" {
    name                      = "{name_of_resource}"
    location                  = "{region_for_resource}"
    resource_group_name       = "{resource_group_name}"
    app_service_plan_id       = "{app_service_plan_id}"
    storage_connection_string = "{storage_connection_string}"

    site_config = {
        linux_fx_version = "DOCKER|{path_to_registry}/{image_name}:{tag}"
    }

    #OR

    container_config = {
        registry_url = "{path_to_registry}"
        image_name = "{image_name}"
        tag_name = "{tag_name}"
    }
}
```

### References

* #1045, #580

**Comment by joakimhew** [comment]
I might be wrong. But it seems like there is already support for this? [1578](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1578 ) @tombuildsstuff @wbreza
