### ISSUE TITLE
Terraform plan coredumps on new and old code

### ISSUE THREAD

**Issue by georgespatton** [terraform-providers/terraform-provider-azurerm#1941]
Using the latest version:

Terraform v0.11.8
+ provider.azurerm v1.15.0
+ provider.random v2.0.0

Terraform is crashing.  I tried going back to old code as well as old versions of the provider.azurerm and provider.random providers.  See this gist.

https://gist.github.com/georgespatton/34780ec9352998d371f8a4d99b6969fe

### Steps to Reproduce

1. `terraform plan`

This worked 24 hours ago.

**Comment by abrocklesby** [comment]
Also experiencing this unexpected EOF error during plan with azurerm v1.15.0 works ok with with v1.13.0 & v1.14.0

**Comment by georgespatton** [comment]
Downgrading to v1.13.0 with terraform v0.11.8  also crashes.  Also tried v1.13.0 with terraform v0.11.7 and didn't work. Then, I went into Azure, removed two instances that were in terraform config that had failed initialization.  Then ran terraform plan again and it worked.  I tried on all the above versions and they all worked.  I can provide a private crash file (147k lines long) and terraform config if you like, but it appears that the problem is when an Azure virtual machine is in a failed state that it causes this crash during a terraform plan.

**Comment by georgespatton** [comment]
Looks great, we'll anticipate this in the 1.16.0 release.  Thanks for the quick turnaround.  Amazing work here.

**Comment by tombuildsstuff** [comment]
hey @georgespatton @abrocklesby 

Just to let you know that this fix has now landed in v1.16 of the AzureRM Provider (here's the full changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.16.0/CHANGELOG.md)). You can upgrade to to this version by specifying it in your provider block:

```
provider "azurerm" {
  version = "=1.16.0"
}
```

... and then running `terraform init -upgrade` :)

Thanks!
