### ISSUE TITLE
New resouce/feature. Link a azurerm schedule with a runbook

### ISSUE THREAD

**Issue by jcmaasb** [terraform-providers/terraform-provider-azurerm#1955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi team,
This request comes from the following thread [#1711 ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1711)

From powershell it is possible to link runbooks with a schedule created in an automation account, as suggested @holmesb.
With terraform I can not find any resource that can do it.

To be able to close the minimum cycle of possibilities that an automation account allows, I think it is necessary to have this resource available,

- Create automation account
- Create runbooks
- Create schedule
- **Create link between runbook and schedule** 
- To future, others features

**Comment by jcmaasb** [comment]
:(

**Comment by ernstae** [comment]
I was a bit curious why this wasn't supported, as well.  I suppose the best we can do at this point, is to add a :+1: and a me too

**Comment by tom-dudley** [comment]
I've had a go at fleshing out the required resource.

### New or Affected Resource(s)



* azurerm_job_schedule

### Potential Terraform Configuration



```hcl
resource "azurerm_job_schedule" "example" {
    name = "${azurerm_schedule.my_schedule.name}"
    runbook = "${azurerm_runbook.my_runbook.name}"
    parameters {
        "foo" = "bar"
        "baz" = "thing"      
    }
}
```
* `parameters` is optional and could potentially be called `runbook_parameters`
* `jobScheduleId` could be an attribute of the resource.

**Comment by brunoscota** [comment]
Subscribed to get to know when it will be available. Very useful feature.

**Comment by draggeta** [comment]
Opened a PR to fix this issue as I'm needing this (and a few other automation resources) myself.

**Comment by odee30** [comment]
Watching this one closely as this would be a very useful addition to the automation suite.

**Comment by Matasiete** [comment]
Also watching for a solution for this issue

**Comment by katbyte** [comment]
@odee30 @ @Matasiete this is currently blocked on an upstream issue with the API.

**Comment by odee30** [comment]
That's a shame.  Thanks for checking it out @katbyte

**Comment by pranavdesai1900** [comment]
As a workaround, I have used "azurerm_template_deployment" resource to implement this functionality, here is a code that works completely fine for me:

```
resource "random_uuid" "test" { }

resource "azurerm_template_deployment" "template_deployment" {
  name                = "DeploymentTemplateName"
  resource_group_name = "${data.azurerm_resource_group.example.name}"
  deployment_mode     = "Incremental"
  template_body = <<DEPLOY
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Automation/automationAccounts/jobSchedules",
      "apiVersion": "2015-10-31",
      "name": "${azurerm_automation_account.example.name}/${random_uuid.test.result}",      
      "properties": {
          "runbook": {
              "name": "${azurerm_automation_runbook.example.name}"
          },
          "schedule": {
              "name": "${azurerm_automation_schedule.hour.name}"
          }
      }
    }
  ]
}
DEPLOY
}
```

Do let me know if this helps!
Cheers!

**Comment by kajahno** [comment]
In addition to what @pranavdesai1900 has posted, if it happens that you get an error like this one:
<pre>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/> <title>404 - File or directory not found.</title> <style type="text/css">  </style> </head> <body> <div id="header"><h1>Server Error</h1></div> <div id="content"> <div class="content-container"><fieldset> <h2>404 - File or directory not found.</h2> <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3> </fieldset></div> </div> </body> </html> 
</pre>

Is probably because you want to use a fancy name for the resource. This Azure API really likes this form (with the uuid):
```
"name": "${azurerm_automation_account.example.name}/${random_uuid.test.result}",
```
