### ISSUE TITLE
Bug in the new version: 1.15, while provisioning Scaleset it's asking os.profile.admin_password when "disable_password_authentication = true"

### ISSUE THREAD

**Issue by vijayakrishnarg1** [terraform-providers/terraform-provider-azurerm#1956]
os_profile {
    computer_name_prefix  = "testcompute"
    admin_username = "${var.user["name"]}"
    admin_password = ""
  }

  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      path = "/home/${var.user["name"]}/.ssh/authorized_keys"
      key_data = "${var.user["sshcert"]}"
    }
  }

**Comment by vijayakrishnarg1** [comment]
Error: azurerm_virtual_machine_scale_set.virtual_machine_scale_set: os_profile.0.admin_password must not be empty

**Comment by vijayakrishnarg1** [comment]
When we explicitly mention provider version = 1.14 it works.

provider "azurerm" {
  subscription_id = "${var.arm_subscription_id}"
  client_id       = "${var.arm_client_id}"
  client_secret   = "${var.arm_client_secret}"
  tenant_id       = "${var.arm_tenant_id}"
  version         = "1.14"
}

**Comment by katbyte** [comment]
Hi @vijayakrishnarg1,

I have opened a PR #1958 making this property optional for release in 1.16. Until then you I believe you should be able to just put in any password and still have password auth disabled.

**Comment by tombuildsstuff** [comment]
hey @vijayakrishnarg1 

Just to let you know that this fix has now been released in v1.16 of the AzureRM Provider (here's the full changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.16.0/CHANGELOG.md)). You can upgrade to to this version by specifying it in your provider block:

```
provider "azurerm" {
  version = "=1.16.0"
}
```

... and then running `terraform init -upgrade` :)

Thanks!
