### ISSUE TITLE
Feature Request: Azure Subscription Creation with Terraform

### ISSUE THREAD

**Issue by a138076** [terraform-providers/terraform-provider-azurerm#1975]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Now that Microsoft have finally enabled the creation of subscriptions programatically (see references section) It would be amazing to have this ability from within the azurerm provider.

### New or Affected Resource(s)

* azurerm_subscription

### References

- https://docs.microsoft.com/en-us/azure/azure-resource-manager/programmatically-create-subscription?tabs=rest

**Comment by tombuildsstuff** [comment]
hi @a138076 

Thanks for opening this issue :)

Support for creating subscriptions programatically has previously been requested in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1216 which I'm going to close this in favour of (but I believe we'll be picking up in the near future) - please subscribe to that issue for updates.

Thanks!

**Comment by a138076** [comment]
@tombuildsstuff thanks Tom, sorry i couldn't find that existing Issue! thanks for the information, will subscribe
