### ISSUE TITLE
Ability to set max_delivery_count on azurerm_servicebus_queue

### ISSUE THREAD

**Issue by SLStinson** [terraform-providers/terraform-provider-azurerm#1977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.15.0

### Affected Resource(s)

* azurerm_servicebus_queue

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_queue" "test_queue" {
  name                = "test_queue"
  resource_group_name = "${azurerm_resource_group.test.name}"
  namespace_name      = "${azurerm_servicebus_namespace.test.name}"

  enable_partitioning = true
  requires_duplicate_detection = true
  max_delivery_count = 10
}
```

### Expected Behavior

The maxDeliveryCount property is set to 10

### Actual Behavior

Error: azurerm_servicebus_queue.test_queue: : invalid or unknown key: max_delivery_count

### Steps to Reproduce

1. `terraform apply`

### References

https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/namespaces/queues

**Comment by tombuildsstuff** [comment]
hi @tkbky 

Since support for this has been merged and now released in v1.17 I'm going to close this issue for the moment.

Thanks!
