### ISSUE TITLE
Question about Runbooks, how use "content" setting with resource "azurerm_automation_runbook"

### ISSUE THREAD

**Issue by jcmaasb** [terraform-providers/terraform-provider-azurerm#1980]
I have doubts about how to use the runbook resource with the new "content" configuration included in version 1.15.0

Versions:
Terraform v0.11.8
provider.azurerm v1.15.0

In the resource documentation, the team added comments indicating that even if "content" is declared, "publish_content_link" must be supplied:

> NOTE The Azure API requires publish_content_link to be supplied even when you specify your own content.

In the tests that I have been doing, I have found strange results.

1. If I use "content" and "publish content link" and both point to the same content, everything is correct. _I have tested with PowerShell and PowerShellWorkFlow in the setting runbook_type without errors_

> This code is extracted from the official documentation. 
> I use the same script ("Get-AzureVM Tutorial.ps1") downloaded to use at "content".

```hcl
resource "azurerm_automation_runbook" "example" {
  name                = "Get-AzureVMTutorial"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  account_name        = "${azurerm_automation_account.example.name}"
  log_verbose         = "true"
  log_progress        = "true"
  description         = "This is an example runbook"
  runbook_type        = "PowerShell" #<-- it's also fine with "PowerShellWorkFlow"
  publish_content_link {
    uri = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-automation-runbook-getvms/Runbooks/Get-AzureVMTutorial.ps1"
  }
  content             = "${data.local_file.example.content}"
}
```

2. If I use "content" and "publish_content_link" and leave this last empty (""), I get an error, the resource is not found (the resource is not created).

```hcl
  publish_content_link {
    uri = ""
  }
```
_Note. The error is the same in all cases, I only indicate it once:_
```hcl
azurerm_automation_runbook.example: Error setting the draft Automation Runbook "Get-AzureVMTutorial" (Account "storageA0" / Resource Group "RG_TEST"): automation.RunbookDraftClient#ReplaceContent: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/storageA0/runbooks/Get-AzureVMTutorial' under resource group 'RG_TEST' was not found."
```

3. If I use "content" and "publish_content_link" and use a non-accessible url (example: https://www.microsoft.fff), an error occurs, the resource is not found (the resource is not created).

```terraform.io
  publish_content_link {
    uri = "https://www.microsoft.fff"
  }
```

4. If I use "content" and "publish content link" and use a valid random url (example: www.microsoft.com), create the resource ok

```hcl
  publish_content_link {
    uri = "https://www.microsoft.com"
  }
```

5. Same as the previous point but with runbook_type = "PowerShellWorkFlow", I get the same error (the resource is not created).

```hcl
  name                = "Get-AzureVMTutorial" # <-- same name of script
  runbook_type        = "PowerShellWorkFlow"
  publish_content_link {
    uri = "https://www.microsoft.com" # <-- does not point to the file with the same name, this is verified by az with runbook_type = "PowerShellWorkFlow"??
    }
  content             = "${data.local_file.example.content}"
```
In official documentation of microsoft show this:
https://docs.microsoft.com/en-es/azure/automation/automation-powershell-workflow
_The name of the workflow must match the name of the Automation runbook. If the runbook is being imported, then the filename must match the workflow name and must end in .ps1._

All of these requirements are correct, but an error is occurring again.
**_Line extraction of script Get-AzureVMTutorial.ps1_**
`
...
workflow Get-AzureVMTutorial
{
...
}
`

**My conclusions:**
- Of these tests, point 1 is discarded because it does not make sense to use "content" and "publish_content_link" with the same content, or in other words, "content" is not necessary.

- The only valid one I see is point 4, but only if I use runbook_type = "PowerShell". Even so, I find it strange to have to indicate a URL that does not lead anywhere.

- Finally, point 5, it´s a bug?

I do not understand how to create the resource correctly. I would like someone to guide me or indicate the correct way to use this feature (content).

Thanks!!

**Comment by jcmaasb** [comment]
Any suggestions?

**Comment by hbuckle** [comment]
I added the content functionality and during my testing found that you must specify the publish content link when creating a runbook through the API - basically you can't create an empty runbook - hence the requirement. Internally what happens in Terraform is the runbook is created using the publish content link and the content is then overwritten with the custom content.
I can't remember testing against PowerShellWorkflows but I suspect the API may be validating the content of the publish content link and failing to create the runbook if it does not meet the requirements. 
If the runbook fails to create then that error should happen before the call to ReplaceContent - I'm not sure why that is not the case.

**Comment by jeffreyCline** [comment]
@jcmaasb , did @hbuckle answer your question? If so I will close this issue. Thanks.

**Comment by jcmaasb** [comment]
Hi @jeffreyCline,
I read @hbuckle's answer and I understand your conclusions and you can close the issue.

The only suggestion would be to add a note in the documentation to include what @hbuckle says in relation to runbook_type = "PowerShellWorkFlow" to inform other users of the current behavior.

In my personal situation, I decided not to use this resource or any other related to runbooks because I am stuck (see also #1955) and forces me to use powershell scripts to finish creating all the resources. For this reason, at this time I prefer to use only powershell and eliminate complexity.

Thanks!!
