### ISSUE TITLE
creating  azurerm_app_service_plan returned an error. Status=<nil>

### ISSUE THREAD

**Issue by lumy** [terraform-providers/terraform-provider-azurerm#1981]
### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.14.0

### Affected Resource(s)

* azurerm_app_service_plan
* azurerm_app_service

### Terraform Configuration Files

```hcl

resource "azurerm_app_service_plan" "plan" {
  name                = "plan"
  location            = "${azurerm_resource_group.sandbox.location}"
  resource_group_name = "${azurerm_resource_group.sandbox.name}"
  kind                = "Linux"

  sku {
    tier = "Standard"
    size = "S1"
  }

  properties {
    reserved = true
  }
}

resource "azurerm_app_service" "app" {
  name                = "as-content-api"
  location            = "${azurerm_resource_group.sandbox.location}"
  resource_group_name = "${azurerm_resource_group.sandbox.name}"
  app_service_plan_id = "${azurerm_app_service_plan.plan.id}"

  site_config {
    linux_fx_version = "DOCKER|hello-world:latest"
  }

  app_settings {
    "WEBSITES_PORT"                       = "8080"
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "false"
  }
}
```
### Actual Behavior

Throw an error:

* azurerm_app_service_plan.plan: 1 error(s) occurred:

* azurerm_app_service_plan.plan: web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

### Steps to Reproduce

1. `terraform apply`

**Comment by elthariel** [comment]
iirc, it works correctly whithout `reserved = true`

**Comment by tombuildsstuff** [comment]
hi @lumy @elthariel 

Thanks for opening this issue :)

Just to let you know that I've added some examples for using Containers within an App Service in #2913 which should help clarify this.

Thanks!
