### ISSUE TITLE
How to update Azure PowerShell modules in Azure Automation

### ISSUE THREAD

**Issue by VipinAgarwal** [terraform-providers/terraform-provider-azurerm#1982]
Hello,
I would like to know how can we update the "Azure Powershell modules" using Azure Automation resource in Terraform?
For reference: This is how we can do through Azure Portal https://docs.microsoft.com/en-us/azure/automation/automation-update-azure-modules

**Comment by hbuckle** [comment]
It can't be done programatically, the option in the portal just runs another runbook in the background to update the modules. The source for that runbook is [here](https://github.com/azureautomation/runbooks/blob/master/Utility/ARM/Update-ModulesInAutomationToLatestVersion.ps1)

**Comment by arcotek-ltd** [comment]
It can be done with an ARM template!
[https://github.com/Azure/azure-quickstart-templates/blob/master/azure-resource-optimization-toolkit/nestedtemplates/Automation.json](https://github.com/Azure/azure-quickstart-templates/blob/master/azure-resource-optimization-toolkit/nestedtemplates/Automation.json).

My first real-life outing with Terraform and there seems to be a lot missing, such as uploading PowerShell modules to an automation account. I'm currently trying to find out if there is a way to call ARM templates or APIs from TF scripts, to cover off the missing resources, hence Google leading me here.

**Comment by katbyte** [comment]
Hi @arcotek-ltd,

You can use the [azurerm_template_deployment](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html) resource to deploy an arbitrary ARM template.

@VipinAgarwal, It looks like this can be done via a runbook and not an API so i am going to close this issue.
