### ISSUE TITLE
omsAgent profile is wrongly cased - it should be omsagent all lowercase

### ISSUE THREAD

**Issue by jobytdev** [terraform-providers/terraform-provider-azurerm#1983]
AKS cluster created with monitoring enabled is broken due to mixed case used in the 'omsAgent' where all other part of the azure is expecting lower case 'omsagent' 

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/data_source_kubernetes_cluster.go

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by metacpp** [comment]
Thanks @jobytdev for opening this issue. The naming convention for `omsagent` is not consistent with `httpApplicationRouting`, I feel that we'd better make it consistent here.
