### ISSUE TITLE
Feature Request: Shared Image Galleries

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#1986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Shared Image Galleries have [recently been announced](https://azure.microsoft.com/en-gb/blog/announcing-the-public-preview-of-shared-image-gallery/) ([more info](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/shared-image-galleries)) - which Terraform should support.

### New or Affected Resource(s)

* `azurerm_shared_image_gallery`
* `azurerm_shared_image`
* `azurerm_shared_image_version`

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "test" {
  # ...
}


data "azurerm_image" "test" {
  # ...
}


resource "azurerm_shared_image_gallery" "test" {
  name                = "mygallery"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
}

resource "azurerm_shared_image" "test" {
  name                = "example"
  gallery_name        = "${azurerm_shared_image_gallery.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  os_type             = "Linux"

  identifier {
    publisher = "ExamplePublisher"
    offer     = "ExampleOffer"
    sku       = "ExcitingSku"
  }
}

resource "azurerm_shared_image_version" "test" {
  name                = "0.0.1"
  gallery_name        = "${azurerm_shared_image_gallery.test.name}"
  image_name          = "${azurerm_shared_image.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  managed_image_id    = "${data.azurerm_image.test.id}"
  regions             = ["${azurerm_resource_group.test.location}"]
}
```

### References

* Announcement: https://azure.microsoft.com/en-gb/blog/announcing-the-public-preview-of-shared-image-gallery

* More Info: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/shared-image-galleries

**Comment by tombuildsstuff** [comment]
hey @LW81 

Just to let you know that support for this has now landed in v1.16 of the AzureRM Provider (here's the full changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.16.0/CHANGELOG.md)). You can upgrade to to this version by specifying it in your provider block:

```
provider "azurerm" {
  version = "=1.16.0"
}
```

... and then running `terraform init -upgrade` :)

Thanks!

**Comment by LW81** [comment]
Hi guys,

i am trying to deploy from a Shared Image agllery for the first time now, but i am a bit confused by looking at the docs.

The purpose of using Shared Image Galleries for us is to deploy from a central image repo accross all our subscriptions.
But looking at the data sources for shared_image and shared_image_version etc. there seems to be no way of specifying where this gallery actually is (the subscription)

Am i missing something ?

Steffen

**Comment by tombuildsstuff** [comment]
hey @LW81 

You can achieve this by using multiple instances of a Provider (also known as Aliasing Providers) - there's [some more information on this here](https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances).

This'd look something like this:

```
provider "azurerm" {
  version =  "=1.19.0"
  subscription_id = "00000000-0000-0000-0000-000000000000"
  alias = "primary"
}

provider "azurerm" {
  version =  "=1.19.0"
  subscription_id = "11111111-1111-1111-1111-111111111111"
  alias = "secondary"
}

"azurerm_shared_image_version" "test" {
  name                = "1.0.0"
  image_name          = "my-image"
  gallery_name        = "my-image-gallery"
  resource_group_name = "example-resources"
  provider = "azurerm.primary"
}

resource "azurerm_virtual_machine" "test" {
  # ...
  provider = "azurerm.secondary"
}
```

Thanks!

**Comment by LW81** [comment]
As always, you guys rock :-)
I will give this a try

Many thanks

**Comment by LW81** [comment]
Hi,

i finally tried to use that today for the first time but it's failing and i don't know why.

Here is my code:

**provider_config.tf**

```
#Define the Provider Config Variables

variable "subscription_id" {}
variable "subscription_id_sig" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}
variable "environment" {}

provider "azurerm" {
  version         = ">= 1.17.0"
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
  environment     = "${var.environment}"
}

provider "azurerm" {
  alias           = "sig"
  version         = ">= 1.17.0"
  subscription_id = "${var.subscription_id_sig}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
  environment     = "${var.environment}"
}
```
**data.tf**

```
data "azurerm_shared_image_version" "linux" {
  provider            = "azurerm.sig"
  name                = "7.6.0"
  image_name          = "SharedImageDefinitionLinux"
  gallery_name        = "SharedImageGallery"
  resource_group_name = "BuildImages-RG"
```


**output.tf**

```
output "sig_id" {
  value = "${data.azurerm_shared_image_version.linux.id}"
}
```

When running this, while handing over the credentials via tfvars file i get the following:

```
Error: Error applying plan:

1 error(s) occurred:

* output.sig_id: Resource 'data.azurerm_shared_image_version.linux' not found for variable 'data.azurerm_shared_image_version.linux.id'
```
