### ISSUE TITLE
Enabling basic metrics in Azure

### ISSUE THREAD

**Issue by nKaloussian** [terraform-providers/terraform-provider-azurerm#199]
Hi,

Terraform Version
0.9.11

I am willing to enable basic metrics while creating a `azurerm_virtual_machine`, however, no such argument is available (unless I am missing something). I am able to enable `boot_diagnostics` without any problems. See screenshot:

![image](https://user-images.githubusercontent.com/476611/28636585-99121c1c-720c-11e7-9c5a-06e0d21f092b.png)

Would be cool to have this argument available sooner or later.

Thanks!

**Comment by tombuildsstuff** [comment]
Hey @nKaloussian 

Thanks for opening this issue :)

I've taken a look into this issue and from what I can see checking the box in the Portal actually installs a VM Extension on the machine.

I've [attempted to replicate this in Terraform](https://gist.github.com/tombuildsstuff/4418f5c58516affed5bd5a6c3cadf4ff) - however I'm having issues with the VM Extension itself not installing as expected; as such I've [opened this issue](https://github.com/Azure/azure-rest-api-specs/issues/1490) requesting more information on this functionality - and I'll update here when I hear back.

Thanks!

**Comment by tombuildsstuff** [comment]
Hey @nKaloussian 

I've spent some time looking into this - and as I previously assumed this can be configured through a VM Extension.

For `Linux` Virtual machines, the `LinuxDiagnostic` extension in `Microsoft.OSTCExtensions` can be used - [there's an example here](https://gist.github.com/tombuildsstuff/1e214b15fe12664d175622c8a02fdf00). For `Windows` Virtual Machines the `IaaSDiagnostics` extension in `Microsoft.Azure.Diagnostics` can be used - [there's an example of it's use here](https://gist.github.com/tombuildsstuff/92191dd7de42310b2874884777e87fbe).

Would you be able to take a look and see if that provides the functionality you're looking for?

Thanks!

**Comment by dominik-lekse** [comment]
@tombuildsstuff Thanks for your research on this. In my opinion, setting up these extensions properly is overcomplicated. In practise, you would need these infrastructure monitoring metric for all machines.

What do you think about integrating a simple switch for the basic diagnostics as the portal does, so the the virtual machine terraform resource does the rest in the background?

**Comment by tombuildsstuff** [comment]
@dominik-lekse from a UX standpoint I'd completely agree, but I think we're going to need a change in the Compute API to support that.

Whilst we could potentially add a flag to the `azurerm_virtual_machine` resource to install a VM Extension; this isn't ideal as Terraform would need to store up-to-date (basic) configurations for each OS type - in addition users submitting their own VM Extension for Azure Monitoring who opt to use a different name for the VM Extension would see errors from Azure.

As such I think for the moment we're better not adding this flag unfortunately - at least until the API allows a route forward here. I've [opened an issue on the Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs/issues/1534) to request this feature is added to the Compute API here - which I'd recommend watching.

In the mean time - given I don't think there's an immediate path forward here I'm going to close this issue - however should an API become available we'll take another look :)

Thanks!
