### ISSUE TITLE
Add Support Application Gateway v2

### ISSUE THREAD

**Issue by guitarrapc** [terraform-providers/terraform-provider-azurerm#1991]
Is there any plan to support v2 resources?
They includes significant improvements and will be happy to migrate from v1 to v2 with terraform.

![image](https://user-images.githubusercontent.com/3856350/46184503-d974be80-c310-11e8-97f2-d5efce295e0a.png)

**Comment by kautsig** [comment]
This would be great. In the current sdk it seems supported at first sight, at least it's in ´vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-04-01/network/models.go´

I'd hope that adjusting the sku and tier validation functions would be enough.

**Comment by kautsig** [comment]
The PR works for my simple scenario.

Azure denied e.g. public ip sku `Basic` to be used with a `WAF_v2`, but I think that's ok, because it does not make so much sense to re-implement azure validation on terraform side.

**Comment by guitarrapc** [comment]
seems simple but enough approach:)
