### ISSUE TITLE
New Resource: `azurerm_monitor_metric_alert`

### ISSUE THREAD

**Issue by mmclane** [terraform-providers/terraform-provider-azurerm#2007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I can currently use terraform to create an azurerm_metric_alertrule and azurerm_monitor_action_group  separately.  But I can't create an azurerm_metric_alertrule  and point it at an action group (either the one created by terraform or an existing one).  This seems like a huge oversight.

### New or Affected Resource(s)

* azurerm_metric_alertrule 
* azurerm_monitor_action_group 

### Potential Terraform Configuration

```hcl
resource "azurerm_metric_alertrule" "test" {
  name = "${azurerm_virtual_machine.test.name}-cpu"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location = "${azurerm_resource_group.test.location}"

  description = "An alert rule to watch the metric Percentage CPU"

  enabled = true

  resource_id = "${azurerm_virtual_machine.test.id}"
  metric_name = "Percentage CPU"
  operator = "GreaterThan"
  threshold = 75
  aggregation = "Average"
  period = "PT5M"

  email_action {
    send_to_service_owners = false
    custom_emails = [
      "some.user@example.com",
    ]
  }

  webhook_action {
    service_uri = "https://example.com/some-url"
      properties = {
        severity = "incredible"
        acceptance_test = "true"
      }
  }
}
resource "azurerm_resource_group" "test" {
  name     = "monitoring-resources"
  location = "West US"
}

resource "azurerm_monitor_action_group" "test" {
  name                = "CriticalAlertsAction"
  resource_group_name = "${azurerm_resource_group.test.name}"
  short_name          = "p0action"

  email_receiver {
    name          = "sendtoadmin"
    email_address = "admin@contoso.com"
  }

  email_receiver {
    name          = "sendtodevops"
    email_address = "devops@contoso.com"
  }

  sms_receiver {
    name         = "oncallmsg"
    country_code = "1"
    phone_number = "1231231234"
  }

  webhook_receiver {
    name        = "callmyapiaswell"
    service_uri = "http://example.com/alert"
  }
}

```

### References

* https://www.terraform.io/docs/providers/azurerm/r/metric_alertrule.html
* #0000

**Comment by mmclane** [comment]
Well, as it turns out I need this to support the new alert rules, not the classic ones.

**Comment by JunyiYi** [comment]
Hi @mmclane , yes you are right. This involves a new resource called: [Azure metric alert](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview-alerts?toc=/azure/azure-monitor/toc.json) instead of the old [alertrule resource](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview-alerts-classic?toc=/azure/azure-monitor/toc.json). And we are currently working that new resource now.

**Comment by mmclane** [comment]
cool

**Comment by kundan123456** [comment]
When I am trying to execute azurerm_monitor_metric_alert : It throws an error with Provider does not support this resource.. Could any one tell me please why this is happening ?

**Comment by JunyiYi** [comment]
Hi @mmclane @kundan123456 , `azurerm_monitor_metric_alert` has been published just now in 1.17.0: https://www.terraform.io/docs/providers/azurerm/r/monitor_metric_alert.html. Please have a try and feel free to give us feedback.

**Comment by kundan123456** [comment]
Hi @JunyiYi , now its working fine. Thanks for information.

One more thing, how to create multiple unique alerts with different dimensions in same template ? Just by copy and pasting same thing again and changing the dimension or do we have any shortcuts here ?

Anyone can share their ideas. Thanks.

**Comment by baladevops** [comment]
> Hi @JunyiYi , now its working fine. Thanks for information.
> 
> One more thing, how to create multiple unique alerts with different dimensions in same template ? Just by copy and pasting same thing again and changing the dimension or do we have any shortcuts here ?
> 
> Anyone can share their ideas. Thanks.

Can anyone update above query...I am having same requirment, how to create mutiple unique alerts with differernt Operators....in terraform Criteria... thanks

**Comment by baladevops** [comment]
@JunyiYi  @tombuildsstuff  - Could you please suggest a solution for above my requirement. thanks

**Comment by tombuildsstuff** [comment]
@baladevops you should be able to use a `*` to signify multiple sources such as `Microsoft.Network/networkSecurityGroups/securityRules/*`

---

Since the most recent comments are unrelated to the original issue I'm going to lock this issue for the moment.
