### ISSUE TITLE
Documentation for azurerm_redis_firewall_rule incorrectly states it only works on Premium SKU

### ISSUE THREAD

**Issue by adam-resdiary** [terraform-providers/terraform-provider-azurerm#2012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8

### Affected Resource(s)

* azurerm_redis_firewall_rule

### Description

The documentation for azurerm_redis_firewall_rule at https://www.terraform.io/docs/providers/azurerm/r/redis_firewall_rule.html has a note stating:

> Note: Redis Firewall Rules can only be assigned to a Redis Cache with a Premium SKU.

This doesn't seem to be correct anymore - we've just managed to create firewall rules against a Standard redis cache (via terraform), and all tiers of cache support adding firewall rules via the portal.

If you're happy to accept PRs, I don't mind updating the markdown file, although it would be good if someone else could just double check I'm not misunderstanding what the note means first.

**Comment by katbyte** [comment]
Hi @adam-resdiary,

It would appear you are correct! the [documentation](https://docs.microsoft.com/en-us/azure/redis-cache/cache-configure#firewall) does not say a premium SKU is required.

We would be more then happy to accept a PR to fix this 🙂

**Comment by adam-resdiary** [comment]
@katbyte there you go. Let me know if that's ok or if I need to change anything.
