### ISSUE TITLE
Resource Group and VNET Names Swapped in Not Found Error

### ISSUE THREAD

**Issue by beh9540** [terraform-providers/terraform-provider-azurerm#2016]
The error message in data.azurerm_subnet not found has resource group where vnet should be and vice versa.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.8

### Affected Resource(s)

* azurerm_subnet

### Terraform Configuration Files

```hcl
# Find the subnet
data "azurerm_subnet" "subnet" {
  name                 = "${var.subnet_name}"
  virtual_network_name = "${data.azurerm_virtual_network.api_vnet.name}"
  resource_group_name  = "${var.resource_group_name}"
}
```

### Expected Behavior

Error: Error refreshing state: 1 error(s) occurred:

* module.apis.data.azurerm_subnet.api_subnet_aks: 1 error(s) occurred:

* module.apis.data.azurerm_subnet.api_subnet_aks: data.azurerm_subnet.api_subnet_aks: Error: Subnet "subnet" (Virtual Network "VNET_NAME" / Resource Group "RESOURCE_GROUP_NAME") was not found

### Actual Behavior

Error: Error refreshing state: 1 error(s) occurred:

* module.apis.data.azurerm_subnet.api_subnet_aks: 1 error(s) occurred:

* module.apis.data.azurerm_subnet.api_subnet_aks: data.azurerm_subnet.api_subnet_aks: Error: Subnet "subnet" (Virtual Network "RESOURCE_GROUP_NAME" / Resource Group "VNET_NAME") was not found

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

None

### References

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #2017 - thanks @beh9540 :)

**Comment by arcotek-ltd** [comment]
Hi,
I'm seeing exactly the same error. Init pulls down version 1.16. Is this the fixed version? If not, is there a way to force it to get the fixed version?

Thanks

**Comment by arcotek-ltd** [comment]
It seems like this is also happening for azurerm_virtual_network:

```
Error: Error refreshing state: 1 error(s) occurred:

* data.azurerm_virtual_network.shared: 1 error(s) occurred:

* data.azurerm_virtual_network.shared: data.azurerm_virtual_network.shared: Error: Virtual Network "$(var.shared_virtual_network_name)" (Resource Group "$(var.shared_resource_group_name)") was not found
```
