### ISSUE TITLE
Error 500 when creating a loadbalancer with a backend pool and load balancing rule

### ISSUE THREAD

**Issue by ResDiaryLewis** [terraform-providers/terraform-provider-azurerm#2022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.8
+ provider.azurerm v1.13.0
```

### Affected Resource(s)

* azurerm_lb
* azurerm_lb_backend_address_pool
* azurerm_lb_rule

### Terraform Configuration Files

https://github.com/ResDiaryLewis/Terraform-Azure-Issue

### Expected Behavior

The load balancer, backend pool, probe and rule should be created.

### Actual Behavior

The backend pool is not created:
```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_lb_backend_address_pool2018-10-03T16:41:32.155+0100 [DEBUG] plugin: plugin process exited: path=C:\Users\Me\workspace\Terraform-Azure-Issue\.terraform\plugins\windows_amd64\terraform-provider-azurerm_v1.16.0_x4.exe
.example-backendpool: 1 error(s) occurred:

* azurerm_lb_backend_address_pool.example-backendpool: Error Creating/Updating Load Balancer "example-lb" (Resource Group "terraform-example-resource-group"): network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="An error occurred." Details=[]

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

1. `$ENV:TF_LOG="trace"`
2. `terraform init`
3. `terraform apply`

### Additional Context

If you comment out the loadbalancer rule, Terraform will create the backend pool. However, uncommenting the rule after successfully doing this will result in a similar error when you try to apply the rule. If you successfully apply the backend pool, you *can* manually add the loadbalancer rules to the loadbalancer in the portal. However, if you apply the rules and the backend pool fails to create, the rules are left in a broken state as they are supposed to be created after the backend pool.

**Comment by neil-yechenwei** [comment]
@ResDiaryLewis , Thanks for opening this issue. After tested, seems I can create these resources successfully with your tfconfig. If it's possible, could you double check whether the problem still exists? if still exists, could you possibly share your latest tf config that trigger this problem?

**Comment by ResDiaryLewis** [comment]
Hello @neil-yechenwei which versions of Terraform and the AzureRM provider would you like me to retry this with?

**Comment by neil-yechenwei** [comment]
I think latest version should be fine.
Terraform: v0.12.25
AzureRM provider: v2.12.0

**Comment by ResDiaryLewis** [comment]
I've just tested this with:
```
Terraform v0.12.26
+ provider.azurerm v2.12.0
```
and it seems to be working as expected.
