### ISSUE TITLE
terraform doesn't work on tenants without an associated subscription

### ISSUE THREAD

**Issue by mattdot** [terraform-providers/terraform-provider-azurerm#2025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.16.0

### Affected Resource(s)

* azurerm_azuread_application

### Terraform Configuration Files

```hcl
resource "azurerm_azuread_application" "test" {
  name                       = "My First AzureAD Application"
  homepage                   = "https://homepage"
  identifier_uris            = ["https://uri"]
  reply_urls                 = ["https://replyurl"]
  available_to_other_tenants = false
  oauth2_allow_implicit_flow = true
}
```

### Panic Output

https://gist.github.com/mattdot/d9ffe17f56723d050ffe5895f4ac5ac1

### Expected Behavior

Should have created an app registration in the tenant.

### Actual Behavior

provider.azurerm: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'eb61ad58-722d-4237-a534-5945a8f870b5' could not be found."

### Steps to Reproduce

1. Create an Azure Active Directory Tenant https://portal.azure.com/#create/Microsoft.AzureActiveDirectory

2. Configure terraform to point at that tenant

3. `az login -t TENANT_ID --allow-no-subscriptions`

4. Try creating an Active Directory object like an app registration or service principal, which is possible to do using Azure CLI but not using `terraform apply`

### Important Factoids

It should be possible to manage AD objects in an empty tenant without an associated subscription.  From az login --help … 
--allow-no-subscriptions : Support access tenants without subscriptions. It's uncommon but                               useful to run tenant level commands, such as 'az ad'.

### References

* #0000

**Comment by davepattie** [comment]
--allow-no-subscriptions is also required for customers who only have a tenant because of Office365 and want to manage app registrations but no infrastructure in Azure

**Comment by tombuildsstuff** [comment]
👋🏻

We've just posted a proposal regarding splitting the Azure Active Directory resources out into their own Provider in #2322, which would allow us to support managing AzureAD resources without requiring a Subscription to be specified. If you're subscribed to this thread we'd be interested to hear any feedback you may have on the proposal in that thread :)

Thanks!

**Comment by tombuildsstuff** [comment]
👋 

To give an update here: we're splitting the AzureAD resources out into their own Provider as documented in #2322 - given this Provider will work at the Tenant level the Subscription ID shouldn't be necessary (or at least mandatory). As such I believe #2322 should resolve this issue - and rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #2322.

Thanks!
