### ISSUE TITLE
Changing a storage account type fails to remove dependant resources from terraform state

### ISSUE THREAD

**Issue by KyleMartin901** [terraform-providers/terraform-provider-azurerm#2048]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.16.0

### Affected Resource(s)

* azurerm_storage_container

### Terraform Configuration Files

Originial
```hcl
resource "azurerm_storage_account" "storacc" {
  name                     = "${replace("${var.resource_group_name}", "-", "")}"
  resource_group_name      = "${var.resource_group_name}"
  location                 = "${var.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind = " BlobStorage"
  access_tier = "Hot"

  enable_https_traffic_only = true
}

resource "azurerm_storage_container" "images" {
  name                  = "images"
  resource_group_name   = "${var.resource_group_name}"
  storage_account_name  = "${azurerm_storage_account.storacc.name}"
  container_access_type = "private"
}

resource "azurerm_storage_container" "logs" {
  name                  = "logs"
  resource_group_name   = "${var.resource_group_name}"
  storage_account_name  = "${azurerm_storage_account.storacc.name}"
  container_access_type = "private"
}
```

Changed storage account type
```hcl
resource "azurerm_storage_account" "storacc" {
  name                     = "${replace("${var.resource_group_name}", "-", "")}"
  resource_group_name      = "${var.resource_group_name}"
  location                 = "${var.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind = " StorageV2"
  access_tier = "Hot"

  enable_https_traffic_only = true
}

resource "azurerm_storage_container" "images" {
  name                  = "images"
  resource_group_name   = "${var.resource_group_name}"
  storage_account_name  = "${azurerm_storage_account.storacc.name}"
  container_access_type = "private"
}

resource "azurerm_storage_container" "logs" {
  name                  = "logs"
  resource_group_name   = "${var.resource_group_name}"
  storage_account_name  = "${azurerm_storage_account.storacc.name}"
  container_access_type = "private"
}
```

### Expected Behavior

When the storage kind is changed it triggers a recreation of the storage account which in turn should recreate any containers. Or changing storage kind doesn't cause a recreation as described in Issue #1186

### Actual Behavior

When the storage kind is changed it triggers a recreation of the storage account but Terraform doesn't register that the associated containers in the storage account will be deleted and keeps them in the state file, causing an error on the apply command. If you then run a plan again it picks up that the storage account and associated containers need creating.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. Change Storage Account kind to `StorageV2`
4. `terraform plan` -> https://gist.github.com/KyleMartin901/6ddcbe7ecdfdbf5bef163d508f535aa0
5. `terraform apply` -> `* azurerm_storage_account.service_history: Error creating Azure Storage Account "tmcaservicehistoryinfra": storage.AccountsClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account tmcaservicehistoryinfra was not found."`
6. `terraform plan`
7. `terraform apply` -> Success

### References

* #1686

**Comment by JunyiYi** [comment]
Thanks @KyleMartin901 for reporting the issue. It is a common problem across all providers, the up-streaming issue is tracked here: https://github.com/hashicorp/terraform/issues/8099, https://github.com/hashicorp/terraform/issues/16065.

**Comment by tombuildsstuff** [comment]
hey @KyleMartin901 

Thanks for opening this issue.

As @JunyiYi has mentioned this is a bug which would need to be fixed within Terraform Core (and not something that we're able to fix within the Azure Provider directly) - as such rather than leaving this open I'm going to close this issue in favour of the upstream issue (https://github.com/hashicorp/terraform/issues/8099) where the Core team can take a look - as once the fix is available in Terraform Core it will be available to all providers.

Thanks!
