### ISSUE TITLE
Application Security Groups not supported for Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by chapmonkey** [terraform-providers/terraform-provider-azurerm#2051]
The ability to attach an application security group to a virtual machine created by a scale set is not available in the 'azurerm_virtual_machine_scale_set' resource type.

I have created a PR to add this feature #2009

**Comment by chapmonkey** [comment]
#2009

**Comment by daniel-ciaglia** [comment]
According to Microsoft, that feature is now supported in their API:

https://feedback.azure.com/forums/216843-virtual-machines/suggestions/34102438-vm-scale-set-application-security-groups?tracking_code=f8b66593df5137ea5b92bd3fe702e363

Thanks for the (merged) PR
👍

**Comment by tombuildsstuff** [comment]
Closing since this PR has been merged - this'll ship as a part of v1.18 :)

Thanks!

**Comment by tombuildsstuff** [comment]
hi @chapmonkey @daniel-ciaglia 

Just to let you know that this has been released as a part of v1.18 of the AzureRM Provider ([the full changelog is available here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.18.0/CHANGELOG.md)). You can upgrade to this by specifying the version in the provider block (as shown below) and then running `terraform init -upgrade`

```
provider "azurerm" {
  version = "=1.18.0"
}
```

Thanks!
