### ISSUE TITLE
AzureRM provider in Azure Cloud Shell error

### ISSUE THREAD

**Issue by jeffwmiles** [terraform-providers/terraform-provider-azurerm#2057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.azurerm v1.13.0

Also occurs with provider.azurerm v1.16.0

### Affected Resource(s)

* provider.azurerm

### Terraform Configuration Files

```hcl
provider "azurerm" {

}
resource "azurerm_resource_group" "Default" {
  name     = "Testnsg"
  location = "EastUS"
}
```

### Debug Output

[https://gist.github.com/jeffwmiles/ac59597be7ac9d61184b713e2c1ad3b0](https://gist.github.com/jeffwmiles/ac59597be7ac9d61184b713e2c1ad3b0)

### Expected Behavior

As per [Microsoft Doc](https://docs.microsoft.com/en-us/azure/terraform/terraform-cloud-shell) on using Terraform with Azure Cloud Shell, expecting no additional parameters needed for the AzureRm provider, and it successfully completing "terraform plan". 

This appeared to be working as recent as last week, with no change in terraform files. 
 

### Actual Behavior

See debug output. 

### Steps to Reproduce

1. Start Azure Cloud Shell
2. Perform `terraform init` and note it succeeds
3. Perform `terraform apply`

### Important Factoids

This error now occurs across multiple subscriptions, with both remote and local backend. 

### References

* #0000

**Comment by metacpp** [comment]
@jeffwmiles Thanks for reporting this issue. It's a regression issue for Cloud Shell, we're rolling out the hotfix. Please retry it after 24 hours.

**Comment by jeffwmiles** [comment]
Thanks @metacpp, after testing this evening I can confirm that Terraform within Azure Cloud Shell is functioning again as expected.

**Comment by tombuildsstuff** [comment]
@jeffwmiles thanks for confirming that, glad to hear this is now working for you - I'm going to close this issue for the moment. Thanks!
