### ISSUE TITLE
Applying alert rule ActiveMessaged error

### ISSUE THREAD

**Issue by arthurspooner** [terraform-providers/terraform-provider-azurerm#2060]
### Terraform Version
Terraform v0.11.8
+ provider.azurerm v1.16.0

### Affected Resource(s)

azurerm_metric_alertrule

### Terraform Configuration Files

(Sensitive information replaced with [XXX])

```
provider "azurerm" {
  tenant_id       = "[XXX]"
  subscription_id = "[XXX]"
  client_id       = "[XXX]"
  client_secret   = "[XXX]"
}

resource "azurerm_metric_alertrule" "test" {
  name                = "ecs-prod-v2-service-bus-dyn-100-alert"
  resource_group_name = "ecs-prod-v2-service-bus-rg"
  location            = "westeurope"

  resource_id = "/subscriptions/[XXX]/topics/ecs-prod-v2-rma-periodic-events-topic-full-dynamic_1.0.0"
  metric_name = "ActiveMessages"
  operator    = "GreaterThan"
  threshold   = 100
  aggregation = "Average"
  period      = "PT5M"
}
```
### Expected Behavior

Apply working

### Actual Behavior
...
azurerm_metric_alertrule.test: Still creating... (7m30s elapsed)
Error: Error applying plan:
1 error(s) occurred:
* azurerm_metric_alertrule.test: 1 error(s) occurred:
* azurerm_metric_alertrule.test: insights.AlertRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException' was thrown."

### Steps to Reproduce

1.  create service bus with topic
2. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @arthurspooner 

Thanks for opening this issue :)

Taking a look into this the error message posted above is an internal error being returned from the Azure API - as such I'm wondering if this was a temporary error or if this is an ongoing issue; out of interest are you still seeing this issue?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @arthurspooner 

Since we've not heard back here I'm going to close this issue for the moment - however if this is still an issue you're seeing please let us know and we'll re-open this/take another look.

Thanks!
