### ISSUE TITLE
Add enableSoftDelete and enablePurgeProtection attributes to Keyvault

### ISSUE THREAD

**Issue by LaurentLesle** [terraform-providers/terraform-provider-azurerm#2066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add enableSoftDelete and enablePurgeProtection attributes to KeyVault 
Required to support Storage Account Encryption with Keyvault
https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/vaults_createorupdate

### New or Affected Resource(s)

* azurerm_keyvault

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @LaurentLesle 

Thanks for opening this issue :)

Support for soft-deleting Key Vaults has previously been requested in #1329 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one - please subscribe to that issue for updates.

Thanks!
