### ISSUE TITLE
Allow specifying which resource providers are supposed to exist or be registered when `skip_provider_registration` is false

### ISSUE THREAD

**Issue by Nirusu** [terraform-providers/terraform-provider-azurerm#20673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, Terraform tries to register all possible Azure subscription resource providers it supports when `skip_provider_registration` is not set.

This feature is frankly quite annoying when working in a restricted subscription that only allows the registration of certain providers or that already has all required providers activated. In both cases, you get unnecessary errors.

So far the workaround is to set `skip_provider_registration` to true and either:
a) out-of-band register the resource providers on Azure manually (or in a separate Terraform state)
b) use `azurerm_resource_provider_registration` and register the required providers manually

a) is doable, but of course this is now a manual extra step that has to be taken.
b) has the disadvantage that it errors when the provider is already registered, and also binds the provider registrations to the lifecycle of the to-be-created Terraform state, while these are usually global across a subscription.

My suggestion would be to offer a middle-way: 

Instead of having trying to register *all* possible resource providers, either:
a) be aware what resources require which provider and register them dynamically based on the specified resources (probably harder to implement, but cleaner)
b) manually allow the user to specify which providers are supposed to "be ensured" to exist and use this list instead of the internal list of "all supported providers" (should be relatively easy to implement, while avoiding the issues of using  `skip_provider_registration` +  `azurerm_resource_provider_registration`) 

### New or Affected Resource(s)/Data Source(s)

provider "azurerm" 

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  ensure_providers_exist = ["Microsoft.Compute", "Microsoft.Network"]
}
```

**Comment by daisy-timms-xlab** [comment]
This would be a massive improvement - attempting to update our azurerm version to 3.90.0 has caused us a real headache as we were previously using `azurerm_resource_provider_registration` to register `Microsoft.AppConfiguration` for all of our subscriptions. 
We don't want to skip provider registration for any new subscriptions we create, as we've benefitted from the automatic registration til now. We would also prefer not to pin our azurerm version or introduce sub-optimal workarounds in terraform to get around this.

**Comment by katbyte** [comment]
Hey @Nirusu & @daisy-timms-xlab - we recently merged https://github.com/hashicorp/terraform-provider-azurerm/pull/26574 which allows for a much more fine control (and listing what RPs to register) on provider startup. it will go out in the 4.0 release scheduled for this week
