### ISSUE TITLE
Terraform crashes when Azure returns a azurerm_virtual_machine with empty Network interface properties

### ISSUE THREAD

**Issue by pather87** [terraform-providers/terraform-provider-azurerm#207]
Hi there,

I am experiencing a crash when using Terraform v0.9.2+
The crash.log shows that a response from the Azure API returns a azurerm_virtual_machine configuration with a network Interface and an empty properties field.

The Bug was introduced with [Commit](https://github.com/hashicorp/terraform/pull/11290/commits/e514dc2da050dd11758552c7497a5b3d7586cd70
)

On Line 659 it is checked if NetworkInterfaceReferenceProperties is nil, which is not when a empty properties field is returned. The following attempt to access the "Primary" key is resulting in a nil pointer dereference.

I'm not sure if it is a Bug at Azure site that an empty properties field is returned. If not, it must be further checked if the properties field is empty before trying to access a key.

### Affected Resource(s)
- azurerm_virtual_machine

### Panic Output
[crash.log](https://gist.github.com/pather87/ce399367e1b8af1baa285de3b2949061)

**Comment by pather87** [comment]
#208

**Comment by tombuildsstuff** [comment]
Fixed via #208
