### ISSUE TITLE
Described 'Name' filed is not accurate in azurerm_shared_image_gallery

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#2081]
Name in azurerm_shared_image_gallery only accept uppercase or lowercase letters, digits.
And simple code is failed.

**Relate resource:**
azurerm_shared_image_gallery
azurerm_shared_image

**From API response:**
* azurerm_shared_image_gallery.test: Error creating/updating Shared Image Gallery "example-image-gallery" (Resource Group "example-resources"): compute.GalleriesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Gallery name is invalid. Allowed characters in gallery name are uppercase or lowercase letters, digits.

**Comment by DexterPOSH** [comment]
Pardon me, if I am wrong here (pretty new to Go and Terraform) but I see that @tombuildsstuff  added the validate function for the Image gallery name under [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/validate/compute.go) which accepts underscore, hyphen and a dot character.

It appears that hyphen is not one of the allowed chars:

```bash
deepak@Azure:~$ az sig create -g example-image-gallery  --gallery-name myGallery-test
Gallery name is invalid. Allowed characters in gallery name are uppercase or lowercase letters, digits.
```

Should be an easy fix to remove the hyphen from the regex in the below function. If someone backs me up here, I would be willing to make my first contribution here 😅 

```golang
func SharedImageGalleryName(v interface{}, k string) (ws []string, es []error) {
	value := v.(string)

	r, _ := regexp.Compile("^[A-Za-z0-9._-]+$")
	if !r.MatchString(value) {
		es = append(es, fmt.Errorf("%s can only contain alphanumeric, full stops, underscores and dashes. Got %q.", k, value))
	}

	length := len(value)
	if length >= 80 {
		es = append(es, fmt.Errorf("%s can be up to 80 characters, currently %d.", k, length))
	}

	return
}

func SharedImageName(v interface{}, k string) (ws []string, es []error) {
	// same as Shared Image Gallery name, for now.
	return SharedImageGalleryName(v, k)
}
```

**Comment by katbyte** [comment]
Hi @DexterPOSH,

Your definitely headed in the right direction 🙂 Look forward to reviewing and merging your first PR!

**Comment by DexterPOSH** [comment]
@katbyte Awesome, thanks. I am on it.
