### ISSUE TITLE
'TestAccAzureRMSharedImageVersion_basic' test failed.

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#2093]
go test -v -timeout 0 -count=1 ./azurerm -run TestAccAzureRMSharedImageVersion_basic
=== RUN   TestAccAzureRMSharedImageVersion_basic
--- FAIL: TestAccAzureRMSharedImageVersion_basic (1004.64s)
        testing.go:513: Step 2 error: Error applying: 1 error(s) occurred:

                * azurerm_shared_image_version.test: 1 error(s) occurred:

                * azurerm_shared_image_version.test: Error creating Shared Image Version "0.0.1" (Image "acctestimg6236585598652540783" / Gallery "acctestsig6236585598652540783" / Resource Group "acctestRG-6236585598652540783"): compute.GalleryImageVersionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="Duplicate regions are not allowed in target publishing regions." Target="galleryImageVersion.properties.publishingProfile.targetRegions"
FAIL
FAIL    github.com/terraform-providers/terraform-provider-azurerm/azurerm       1004.683s

**Comment by katbyte** [comment]
Hi @lrxtom2,

I just ran the test and it works fine for me:
```
[03:50:51] kt@snowbook:~/hashi/..3../terraform-providers/terraform-provider-azurerm$ make fmt; make testacc TEST=./azurerm TESTARGS=-test.run=TestAccAzureRMSharedImageVersion_basic
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccAzureRMSharedImageVersion_basic -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMSharedImageVersion_basic
--- PASS: TestAccAzureRMSharedImageVersion_basic (1896.74s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	1896.778s
```

What is your alt test location set too? If it is the same as your test location there will be a conflict and the test will fail.

**Comment by tombuildsstuff** [comment]
hi @lrxtom2 

Since we've not heard back from you here (and we've got a solution proposed above) - I'm going to close this issue for the moment.

Thanks!
