### ISSUE TITLE
Encrypt managed disk on AZ via terraform

### ISSUE THREAD

**Issue by cfabrizio-gig** [terraform-providers/terraform-provider-azurerm#2095]
### Community Note

- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform version

Terraform v0.11.7
+ provider.azurerm v1.16.0

Hi community, is it possible to encrypt managed disk via terraform?

**Comment by tombuildsstuff** [comment]
hi @cfabrizio-gig 

Thanks for opening this issue :)

Unfortunately this isn't supported at this time - however there's an issue tracking support for this here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/486 which I'm going to close this issue in favour of, please subscribe to that issue for updates.

Thanks!
