### ISSUE TITLE
Allow linking a Logic App to an Integration Account

### ISSUE THREAD

**Issue by ajhall** [terraform-providers/terraform-provider-azurerm#2106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'd like to be able to link an Logic App to an Integration Account. Certain actions in a logic app require schemas, maps, and so on from a linked Integration Account, but I can't find a way to plug one in to the azurerm_logic_app_workflow resource.

### New or Affected Resource(s)

* azurerm_logic_app_workflow

### References

* #1266

**Comment by slessardjr** [comment]
There are integration accounts and integrated service environments.  This should be able to cover both.
