### ISSUE TITLE
Retrieve keys for Automation Account

### ISSUE THREAD

**Issue by jamielennox** [terraform-providers/terraform-provider-azurerm#2107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We can create an automation account with terraform, and we can create a virtual machine with terraform. I'm trying to follow the [guide here](https://medium.com/modern-stack/bootstrap-a-vm-to-azure-automation-dsc-using-terraform-f2ba41d25cd2) to register that virtual machine onto the automation account, however we need the keys retrievable from the portal to connect the two.

There is an [API for retrieving keys](https://docs.microsoft.com/en-us/rest/api/automation/keys/keys_listbyautomationaccount) and there is prior art here as a number of services (eg azurerm_storage_account) fetch keys and either return them or manipulate them into connection strings.

(We also need the URL, I'm still looking at how that's calculated and returned but it can be a different bug). 

### New or Affected Resource(s)

* azurerm_automation_account

### Potential Terraform Configuration

The return values for keys are an array, but they seem to simply be primary and secondary. There are resources such as [azurerm_servicebus_topic_authorization_rule](https://www.terraform.io/docs/providers/azurerm/r/servicebus_topic_authorization_rule.html) that exports a `primary_key` and `secondary_key` and i assume this would follow the same format.

**Comment by tombuildsstuff** [comment]
hi @jamielennox 


Just to let you know that this has been released as a part of v1.18 of the AzureRM Provider ([the full changelog is available here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.18.0/CHANGELOG.md)). You can upgrade to this by specifying the version in the provider block (as shown below) and then running `terraform init -upgrade`

```
provider "azurerm" {
  version = "=1.18.0"
}
```

Thanks!

**Comment by jamielennox** [comment]
@tombuildsstuff that's awesome, thanks for taking the time to figure that out.
