### ISSUE TITLE
AKS cluster recreation triggered on apply since v1.17

### ISSUE THREAD

**Issue by kautsig** [terraform-providers/terraform-provider-azurerm#2114]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.17.0
```

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Expected Behavior

The resource does not report any change when `terraform apply` is executed without any change a second time.

### Actual Behavior

When creating the kubernetes cluster and apply again, some attributes will be reported as changed and therefore cause a cluster recreation:

```
agent_pool_profile.0.os_disk_size_gb:       "30" => "0" (forces new resource)
```

### Steps to Reproduce

1. Create an AKS cluster
2. Execute `terraform apply` again.

### Workaround

The obvious workaround is to ignore changes in the reported changed fields.
```
  lifecycle {
    ignore_changes = ["agent_pool_profile"]
  }
```

**Comment by kautsig** [comment]
@subesokun I think we're seeing two issues here. Cluster creation and recreation is fine for me for a kubernetes `1.11.3` cluster. I definitely only did upgrade the terraform plugin since yesterday. An azure API change would be quite a coincidence, but I can try to verify by downgrading the terraform plugin though.

The error message you describe was already posted here: https://github.com/Azure/AKS/issues/103

**Comment by katbyte** [comment]
Hi @kautsig,

Thanks for opening this issue. Looking into it I can confirm that this is a result of an API change and will affect recent version of the provider. Currently if `os_disk_size_gb` is not specified, we send `0` to the API, it uses a default of `30`, and still returns `0`. Now the API is returning `30` causing terraform to think a change is required.

I hopefully will have a fix ready later today.

**Comment by kautsig** [comment]
@katbyte thanks for your response. I applied the suggested workaround to simply set the default value, it's definitely the better one.

I re-tried with a simpler example, now the 2 mentioned other attributes are also not affected. Probably I was seeing something this because of some other glitch. I adjusted the issue text to reflect that.

**Comment by kautsig** [comment]
Hey @subesokun,
it seems my coworker stumbled across the issue you posted, which is indeed *not related* to the API change which was fixed in this PR.

To me it seems that azure removed a supported k8s versions from their API. We had a `1.10.5` cluster in westeurope, but `az aks get-versions --location westeurope -o table` doesn't list this version any more.

I'd guess this could lead to the validation error you posted, because orchestratorVersion is the k8s version in acs-engine. Hope this helps.
