### ISSUE TITLE
SQL Database import error

### ISSUE THREAD

**Issue by alant94** [terraform-providers/terraform-provider-azurerm#2127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.9
+ provider.azurerm v1.17.0

### Affected Resource(s)

* azurerm_sql_database

### Terraform Configuration Files

```hcl
resource "azurerm_sql_database" "some-sql-db" {
    name                = "terraform-test"
    resource_group_name = "my-resource-group"
    location            = "eastus2"
    server_name         = "my-sql-server"
    edition             = "Standard"
    requested_service_objective_name = "S2"

    import {
        storage_uri                  = "https://devops.blob.core.windows.net/db-dump/some-dump.bacpac"
        storage_key                  = "***"
        storage_key_type             = "StorageAccessKey"
        administrator_login          = "fantom"
        administrator_login_password = "P@ssw0rd"
        authentication_type          = "SQL"
    }
}
```

### Expected Behavior

If something is wrong with credentials or storage_key, the corresponding error should appear, like the one that can be found in the activity log of the database (wrong storage_key here): 
```
There was an error that occurred during this operation : '<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Error encountered during the service operation. ; Exception Microsoft.SqlServer.Management.Dac.Services.ServiceException:Unexpected exception encountered while retrieving metadata for blob &amp;#39;https://devops.blob.core.windows.net/db-dump/some-dump.bacpac&amp;#39;.; Inner exception Microsoft.WindowsAzure.Storage.StorageException:The remote server returned an error: (403) Forbidden.; Inner exception System.Net.WebException:The remote server returned an error: (403) Forbidden.; </string>'
```

### Actual Behavior

After approximately a minute (during which an empty database is being created) the error occurs: 

```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_sql_database.some-sql-db: 1 error(s) occurred:

* azurerm_sql_database.some-sql-db: sql.DatabasesClient#CreateImportOperation: Failure sending request: StatusCode=0 -- Original Error: json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface {}
```

### Steps to Reproduce

In order to reproduce this error you obviously need sql server and dump of sql database somewhere on the storage account.
1. Provide wrong storage_key or administrator_login/password in terraform file
2. `terraform init`
3. `terraform apply`

### References

Looks like the root of this issue could be the same as #1605

**Comment by tombuildsstuff** [comment]
hi @alant94 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this this appears to be the same underlying issue as #1605 as such I'm going to close this issue in favour of #1605.

Thanks!
