### ISSUE TITLE
azurerm_key_vault -  Virtual Network Rules not working with multiple subnet id's

### ISSUE THREAD

**Issue by virtualbubble** [terraform-providers/terraform-provider-azurerm#2129]
azurerm_key_vault - support for Virtual Network Rules (#2027) not working with multiple subnet id's

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.9

### Affected Resource(s)

* azurerm_key_vault

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "keyvault-testvault-rg01"
  location = "westeurope"
}

resource "azurerm_key_vault" "test" {
  name                        = "keyvault-we-test-key01"
  location                    = "${azurerm_resource_group.test.location}"
  resource_group_name         = "${azurerm_resource_group.test.name}"
  enabled_for_disk_encryption = true
  tenant_id                   = "<TENANT_ID>"

  sku {
    name = "standard"
  }

  network_acls {
    default_action             = "Deny"
    bypass                     = "AzureServices"
    virtual_network_subnet_ids = ["<SUBNET_ID_1>","<SUBNET_ID_2>"]
  }

  tags {
    environment = "tEST"
  }
}

provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}


variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}


```

### Debug Output

Resources do not build at all. Continues for over an hour.

### Expected Behavior

Build key vault and add muliple subnet id's

### Actual Behavior

Keyvault does not build when supplying more than one subnet id 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Keyvault does not build when supplying more than one subnet id . Copy the code above to test and test with one subnet id and then destroy and add an additional subnet id and test.

### References
-->

* #0000

**Comment by bpoland** [comment]
I am seeing the same thing -- it works fine with one subnet ID but when you add a second one, it gets stuck in "Still creating..." forever.  I have enabled trace logging but nothing useful seems to be in there.

**Comment by rhollins** [comment]
I have exactly same issue
