### ISSUE TITLE
Re-allow HTTP urls for Azure AD Application properties (revert #1960)?

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-azurerm#2130]
Hi!

I'm wondering if the root cause of #1953 was incorrectly diagnosed, or if maybe Azure have changed their API again. If i peg my `azurerm` provider version to `= 1.15` (i.e. the latest release before the "fix" in #1960 was merged) I can apply the following template without problems:
```
provider "azurerm" {
  version = "= 1.15"
}

resource "azurerm_azuread_application" "ad_app" {
  name = "tomas-testing"
}
```
In other words, I cannot reproduce the original issue (#1953).

However, as of #1960 and version `1.16`, no URLs on the application can be `http`, which disallows something like this:
```
resource "azurerm_azuread_application" "ad_app" {
  name = "tomas-testing"

  reply_urls = ["http://localhost:8080"]
}
```
Again, this template applies successfully with 1.15 but fails on 1.16. This effectively makes impossible to e.g. set reply urls for AzureAD applications that enable local testing of OAuth flows (without configuring your local development environment to run https).

Is there any chance #1960 could be reverted for the next release, to re-enable this configuration?

PS. This template, touching all three types of URLs and setting them to HTTP-schemed values, also works without problems on 1.15:
```
provider "azurerm" {
  version = "= 1.15"
}

resource "azurerm_azuread_application" "ad_app" {
  name     = "tomas-testing"
  homepage = "http://tomas-testar.com"

  identifier_uris = [
    "http://tomas-testar",
  ]

  reply_urls = ["http://localhost:8080"]
}
```

**Comment by katbyte** [comment]
Hi @tomasaschan,

I've been able to verify that http is allowed again. I'm not sure why it wasn't for a while but 🤷‍♀️ 

I've opened #2320 to revert the change 🙂
