### ISSUE TITLE
Cannot increase maximum size of Azure VMSS 

### ISSUE THREAD

**Issue by georgespatton** [terraform-providers/terraform-provider-azurerm#2136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

I can't increase the size of an existing VMSS within Azure.  It was created via terraform originally.  I am using the latest version of terraform.  I tried the latest version of provider.azurerm (v1.17.0) with the same behavior.  

```
$ terraform plan

Error: module.ourmodule.azurerm_autoscale_setting.vmss-autoscale-cpu: expected profile.0.capacity.0.maximum to be in the range (1 - 40), got 1000

$ terraform -version
Terraform v0.11.9
+ provider.azurerm v1.16.0
+ provider.random v2.0.0


$ git diff
diff --git a/avmss.tf
index 152733e..de42594 100644
--- a/vmss.tf
+++ b/vmss.tf
@@ -91,7 +91,7 @@ resource "azurerm_autoscale_setting" "vmss-autoscale-cpu" {
     capacity {
       default = 10
       minimum = 10
-      maximum = 40
+      maximum = 1000
     }
 
$ cat vmss.tf 

.......

### Configuration for Service azurerm_autoscale_setting ###
##
##
resource "azurerm_autoscale_setting" "prod-autoscale-cpu" {
  name                = "Percentage CPU"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.location}"
  target_resource_id  = "${azurerm_virtual_machine_scale_set.prod-ss.id}"

  profile {
    name = "Percentage CPU"
    capacity {
      default = 10
      minimum = 10
      maximum = 1000
    }

.........

```

To reproduce, create an Azure VMSS with terraform with set minimum/maximum/default values.  Then increase the maximum setting.  It should fail as this does.

**Comment by jgabinet** [comment]
+1

**Comment by georgespatton** [comment]
Why are we limited to 40 VMSS max instances in the terraform config?

**Comment by georgespatton** [comment]
PR pending review here:  https://github.com/terraform-providers/terraform-provider-azurerm/pull/2806
