### ISSUE TITLE
Error applying azurerm_recovery_services_protected_vm to virtual machine

### ISSUE THREAD

**Issue by RobbieBinnie** [terraform-providers/terraform-provider-azurerm#2143]
Hello,

I have been trying to configure pre-existing VMs to be backed up using a pre-existing vault, however, it is producing errors. I have initially had to comment out a few lines from the documentation as the terraform plan fails when they are present. Once that has happened and I run the apply, I receive a 400 error stating the following:

Code="BMSUserErrorInvalidConfigureProtectionRequest" Message="Input for configure protection is not in proper format\r\nPlease ensure that container exists and other parameters are in valid format" 

further information below.

### Terraform Version
Terraform v0.11.9
+ provider.azurerm v1.17.0

### Affected Resource(s)
* azurerm_recovery_services_protected_vm

### Terraform Configuration Files
variable "location" {
  default = "West Europe"
}

variable "backuppolicyname" {
  default = "DailyBackup"
}

variable "resource_group_name" {
  default = "#####"
}

variable "vm_name" {
  default = "testdscconfig23"
}

variable "vm_id" {
  default = "/subscriptions/#####/resourceGroups/#######/providers/Microsoft.Compute/virtualMachines/testdscconfig23"
}

variable "recovery_vault_name" {
  default = "basicvault-rb"
}

data "azurerm_resource_group" "example" {
  name     = "${var.resource_group_name}"
}

data "azurerm_recovery_services_vault" "example" {
  name                = "${var.recovery_vault_name}"
  resource_group_name = "${data.azurerm_resource_group.example.name}"
}

resource "azurerm_recovery_services_protected_vm" "example" {
  #location            = "${data.azurerm_resource_group.example.location}"
  resource_group_name = "${data.azurerm_resource_group.example.name}"
  recovery_vault_name = "${data.azurerm_recovery_services_vault.example.name}"
  #source_vm_name      = "${var.vm_name}"
  source_vm_id        = "${var.vm_id}"
  #backup_policy_name  = "${var.backuppolicyname}"
}

### Debug Output
Error: Error applying plan:

1 error(s) occurred:

* azurerm_recovery_services_protected_vm.example: 1 error(s) occurred:

* azurerm_recovery_services_protected_vm.example: Error creating/updating Recovery Service Protected VM "VM;iaasvmcontainerv2;AIS-RB-TEST;testdscconfig23" (Resource Group "AIS-RB-TEST"): backup.ProtectedItemsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure:Service returned an error. Status=400 Code="BMSUserErrorInvalidConfigureProtectionRequest" Message="Input for configure protection is not in proper format\r\nPlease ensure that container exists and other parameters are in valid format"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior
the Virtual machine should have been added to the backup schedule.

### Actual Behavior
Terraform fails to apply

### Steps to Reproduce
1. `terraform apply`

### References
may be linked to this:
https://github.com/Azure/azure-sdk-for-python/issues/1331
https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protected_vm.html

**Comment by katbyte** [comment]
Hi @AndreasMWalter, @RobbieBinnie

The documentation was based on an draft version of the resource and is incorrect 🙁 As well as the field `backup_policy_id` should have been required. I have opened 2154 to fix it for the next release.
