### ISSUE TITLE
azurerm_dev_test_virtual_network only denies use of public IPs on second apply

### ISSUE THREAD

**Issue by PatrickMcAfee-Eagle** [terraform-providers/terraform-provider-azurerm#2152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform -v
Terraform v0.11.9
* provider.azurerm v1.17.0

### Affected Resource(s)

* azurerm_dev_test_virtual_network

### Terraform Configuration Files

```hcl
resource "azurerm_dev_test_lab" "lab" {
  name                = "${lower(var.name)}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
}

resource "azurerm_dev_test_virtual_network" "base_network" {
  name                = "${azurerm_dev_test_lab.lab.name}-base-network"
  lab_name            = "${azurerm_dev_test_lab.lab.name}"
  resource_group_name = "${azurerm_dev_test_lab.lab.resource_group_name}"

  subnet {
    use_public_ip_address           = "Deny"
    use_in_virtual_machine_creation = "Allow"
  }
}

```
### Expected Behavior

Terraform should set "use_public_ip_address" to DENY on the first apply

### Actual Behavior

Terraform sets "use_public_ip_address" to DENY on the *second* run of apply

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan` <-- will show that DENY needs to be set
1. `terraform apply`
1. `terraform plan` <-- will show that no changes are needed

**Comment by mbfrahry** [comment]
Thanks for opening this issue @PatrickMcAfee-Eagle. This has been merged and will make it into the next release 1.29.0
