### ISSUE TITLE
list to string migration in loadbalancer backend pools

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#2172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.10
+ provider.azurerm v1.17.0
+ provider.random v1.3.1
+ provider.template v1.0.0
```

### Affected Resource(s)

* azurerm_network_interface
* azurerm_network_interface_backend_address_pool_association

### Terraform Configuration Files

I have a module with now deprecated code like this:

```hcl
resource "azurerm_network_interface" "vm" {
  count                     = "${var.nb_instances}"
  name                      = "${var.vm_hostname}-${count.index}-nic"
  location                  = "${var.location}"
  resource_group_name       = "${var.resource_group_name}"
  network_security_group_id = "${azurerm_network_security_group.vm.id}"

  ip_configuration {
    name                          = "ipconfig${count.index}"
    subnet_id                     = "${var.vnet_subnet_id}"
    private_ip_address_allocation = "Dynamic"
    load_balancer_backend_address_pools_ids = ["${var.lb_backend_pool_ids}"]
  }
}
```

### Expected Behavior

I want to be able to do the following to migrate to the new pool association resource.

```hcl
resource "azurerm_network_interface_backend_address_pool_association" "vm" {
  count                    = "${var.nb_instances}"
  network_interface_id     = "${element(azurerm_network_interface.vm.*.id,count.index)}"
  ip_configuration_name    = "ipconfig${count.index}"
  backend_address_pool_ids = ["${var.lb_backend_pool_ids}"]
}
```

### Actual Behavior

The `azurerm_network_interface_backend_address_pool_association` resource however has moved to a string for singular backend pools, and does not allow a list to be provided. This normally in other code would need a nested loop, but we don't have that here. There is probably a way with some creative math (`${var.nb_instances * length(var.lb_backend_pool_ids)}` etc.) to accomplish this, but that seems overly complex.

### Steps to Reproduce

1. `terraform apply`

### References

* #2079

**Comment by magodo** [comment]
@mbrancato Thank you for this issue!
Unfortunately, terraform core doesn't correctly model `count = X * Y` resources, whilst it should.
I hope you don't mind that I close this issue for now.

**Comment by mbrancato** [comment]
@magodo To be clear (and I know this code is old), it has nothing to do with the `count` field or multiplication.

**Comment by magodo** [comment]
From your config, I assume you want to bind the same list of the backend pool id to multiple nic, in which case it is a X*Y cases, which is not supported by core for now.

**Comment by mbrancato** [comment]
@magodo no, that was not the intent. The original config is mapping a list of backend pools to a single interface. This list is already built, there is no recursion / looping in core needed here AFAIK.

In the migration from `azurerm_network_interface` to breaking out `azurerm_network_interface_backend_address_pool_association` as a separate resource, the field `load_balancer_backend_address_pools_ids` was a list and supported multiple backend address pools and become `backend_address_pool_id` as a string representing a single backend pool.
