### ISSUE TITLE
 [Azure] on Terraform Cloud - statusCode=0 -- Original Error: Code="ParameterOutOfRange" Message="The value of the 'Version' should be in: []. Verify that the specified parameter value is correct

### ISSUE THREAD

**Issue by iamraj007** [terraform-providers/terraform-provider-azurerm#21757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "mycompanyxxxx"
    workspaces {
      name = "dev"
    }
  }
}

terraform {
  required_version = ">= 0.13"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.55.0"
    }
  }
}
...terraform config...

resource "azurerm_postgresql_flexible_server" "postgresql" {
  name                = "${var.prefix}-postgresql"
  resource_group_name = var.resource_group_name
  location            = "**germanywestcentral**"
  version             = var.db_postgresql_version ## "12"
  delegated_subnet_id = var.postgres_subnet_cidr
  administrator_login    = var.login_username_postgres
  administrator_password = var.login_password_postgres
  zone                   = var.db_numberof_zone  ## 2
  private_dns_zone_id    = var.private_zone_id
  backup_retention_days        = var.backup_retention_days  ## 7
  geo_redundant_backup_enabled = var.db_geo_redundant_backup_enabled
  # public_network_access_enabled = var.db_public_network_access_enabled
  storage_mb = var.db_storage_mb  ##  524288
  sku_name   = var.db_sku_name_type GP_Standard_D4s_v3
  depends_on = [var.private_link]
  tags = {
    Name        = "${var.resource_prefix}-postgresql-db"
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Flexible Server (Subscription: "de5cxxxx-xxxx-xxxxb3be9c" Resource Group Name: "az-dev" Flexible Server Name: "cluster-postgresql"): performing Create: servers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="ParameterOutOfRange" Message="The value of the 'Version' should be in: []. Verify that the specified parameter value is correct."
with module.postgres-flexiable-server.azurerm_postgresql_flexible_server.postgresql

on modules/postgres-flexiable-server/main.tf line 2, in resource "azurerm_postgresql_flexible_server" "postgresql":
```

### Expected Behaviour

Flexible Server should be created with **NO** issue at all.
Same code have been tested and work fine with no issue for region "West Europe" but FAIL for "**germanywestcentral**"

### Actual Behaviour

fail with exception.

Error: creating Flexible Server.
Failure sending request: StatusCode=0 -- Original Error: Code="ParameterOutOfRange"
Message="The value of the 'Version' should be in: [].
_Verify that the specified parameter value is correct.

The version have provided have been tested with both given value as variable for give as simple value like  = "12".

### Steps to Reproduce

copy this code etc..
terraform init
terraform apply (with tfvars file)
make sure the region is "germanywestcentral" (to test fail) Same code work fine for "West Europe".

### Important Factoids

Code was run in EU region

### References

33182

**Comment by aristosvo** [comment]
Hi @iamraj007! I'm not too familiar with the complete status of this resource on Azure, but [this link](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview#azure-regions) shows some red crosses for Germany West Central.., that might have to do with it?

It seems like an Azure issue to me..

**Comment by iamraj007** [comment]
> Hi @iamraj007! I'm not too familiar with the complete status of this resource on Azure, but [this link](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview#azure-regions) shows some red crosses for Germany West Central.., that might have to do with it?
> 
> > $$ New server deployments are temporarily blocked in these regions. Already provisioned servers are fully supported.
> 
> It seems like an Azure issue to me..

Jesus!!
a better error message would have helped on either terraform code (preferably.._though i understand the challenge tf side_) or Azure cloud side also a simple "subsection not allowed to provision is FREAKING not helping.. anyone AZURE!

**Comment by rcskosir** [comment]
Thank you @iamraj007 for opening this issue and thank you @aristosvo for helping figure out what was going on in the Germany West Central region. 
I am going to go ahead and close this issue since the failure reasoning has been discovered in the above comments. 
I am happy to see the community helping solve issues when error messaging isn't descriptive enough.

Cheers,
Renae
