### ISSUE TITLE
azurerm_application_insights has no application_type Node.JS

### ISSUE THREAD

**Issue by StefanSchoof** [terraform-providers/terraform-provider-azurerm#2179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.9
+ provider.azurerm v1.17.0

### Affected Resource(s)

* azurerm_application_insights

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "tf-test"
  location = "West Europe"
}

resource "azurerm_application_insights" "node" {
  name                = "node"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  application_type    = "Node.JS"
}
```

### Expected Behavior

Creates a Application insights for Node.JS, like in [Monitor your Node.js services and apps with Application Insights](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs) described.

### Actual Behavior

`terrafrom plan` results into a:

```
Error: azurerm_application_insights.node: expected application_type to be one of [web other java MobileCenter phone store ios], got Node.JS
```

### Steps to Reproduce

1. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @StefanSchoof 

Thanks for opening this issue :)

Taking a quick look into this, whilst it's not overly clear (unfortunately) I believe `Node.JS` in the Azure Portal is actually represented as `Other` in the Azure API/Terraform Resource - would you be able to take a look and see if this works for you?

Thanks!

**Comment by StefanSchoof** [comment]
Thanks for your reply.

I created an application insight over the portal and select Node. Then I imported the resource into terraform. When I set the `application_type` web, terraform tries to change the type from `"Node.Js" --> "web"`.

I will try if a resource of this type works for me.

**Comment by StefanSchoof** [comment]
I tried the "other" application type. It seems to work in my use case. I could not spot any difference between the "other" and the "Node.JS" type.

But I think azure has an "Node.JS" type. If I take a look into "Automation script" in the azure Portal for a Insights I created over the portal and selected Node.JS. I got

```
        {
            "comments": "Generalized from resource: '/subscriptions/xxxxx/resourceGroups/yyyy/providers/microsoft.insights/components/yyyyy-node'.",
            "type": "microsoft.insights/components",
            "kind": "Node.JS",
            "name": "[parameters('components_zzzz_node_name')]",
            "apiVersion": "2015-05-01",
            "location": "westeurope",
            "tags": {},
            "scale": null,
            "properties": {
                "Application_Type": "Node.JS",
                "Flow_Type": "Redfield",
                "Request_Source": "IbizaAIExtension",
                "HockeyAppId": null,
                "SamplingPercentage": null
            },
            "dependsOn": []
        },
```

and the other 



```
{
            "comments": "Generalized from resource: '/subscriptions/xxxx/resourceGroups/yyyyy/providers/microsoft.insights/components/zzzz-node'.",
            "type": "microsoft.insights/components",
            "kind": "other",
            "name": "[parameters('components_yyyy_node_name')]",
            "apiVersion": "2015-05-01",
            "location": "westeurope",
            "tags": {},
            "scale": null,
            "properties": {
                "Application_Type": "other",
                "Flow_Type": null,
                "Request_Source": null,
                "HockeyAppId": null,
                "SamplingPercentage": null
            },
            "dependsOn": []
        },
```
