### ISSUE TITLE
azurerm_storage_blob dynamic source content

### ISSUE THREAD

**Issue by mb290** [terraform-providers/terraform-provider-azurerm#2180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the azurerm_storage_blob resource only allows for a source file or source uri. This is fine for an initial deployment, but TF doesn't detect if the source file changes. What we'd like to do is update the source file and have TF update the target Blob.

If there is appetite for this functionality i'm happy to try and give building it a go, but don't want to waste energy. Alternatively if there is a solution that exists today that i'm just not aware of then i'd love to be pointed in that direction.

### New or Affected Resource(s)

* azurerm_storage_blob

### Potential Terraform Configuration

```hcl

data "template_file" "test_file" {
  template = "${file("files/testFile.txt")}"
}

resource "azurerm_storage_blob" "testsb" {
  name = "testFile.txt"

  resource_group_name    = "${azurerm_resource_group.test.name}"
  storage_account_name   = "${azurerm_storage_account.test.name}"
  storage_container_name = "${azurerm_storage_container.test.name}"

  source_data = "${data.template_file.test_file.rendered}"

  type = "blob"
  size = 5120
}

```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @mb290 

Thanks for opening this issue :)

Taking a quick look into this I'd agree that it'd make sense for the Terraform Resource to be able to determine that this file needs to be changed based off some internal hash of the file. Support for detecting changes on the etag/file content changing has previously been requested in #1990 which I'm going to close this issue in favour of.

Thanks!
