### ISSUE TITLE
azurerm_network_interface_backend_address_pool_association not working with count

### ISSUE THREAD

**Issue by LW81** [terraform-providers/terraform-provider-azurerm#2181]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.11.8
azurerm v1.17.0

### Affected Resource(s)

azurerm_network_interface_backend_address_pool_association

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_public_ip" "test" {
  name                         = "example-pip"
  location                     = "${azurerm_resource_group.test.location}"
  resource_group_name          = "${azurerm_resource_group.test.name}"
  public_ip_address_allocation = "static"
}

resource "azurerm_lb" "test" {
  name                = "example-lb"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  frontend_ip_configuration {
    name                 = "primary"
    public_ip_address_id = "${azurerm_public_ip.test.id}"
  }
}

resource "azurerm_lb_backend_address_pool" "test" {
  resource_group_name = "${azurerm_resource_group.test.name}"
  loadbalancer_id     = "${azurerm_lb.test.id}"
  name                = "acctestpool"
}

resource "azurerm_network_interface" "test" {
  count = "2"
  name                = "example-nic${count.index}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  ip_configuration {
    name                          = "testconfiguration${count.index}"
    subnet_id                     = "${azurerm_subnet.test.id}"
    private_ip_address_allocation = "dynamic"
  }
}

resource "azurerm_network_interface_backend_address_pool_association" "test" {
  network_interface_id    = "${element(azurerm_network_interface.test.*.id,count.index)}"
  ip_configuration_name   = "${element(azurerm_network_interface.test.ip_configuration.*.name,count.index)}"
  backend_address_pool_id = "${azurerm_lb_backend_address_pool.test.id}"
}

```
### Expected Behavior

We often deploy resources using count paramter and then link them with other resources using the function: element(resource,count.index).

In the case of azurerm_network_interface_backend_address_pool_association  we should associate each created Network interface with the LB Backend Pool

### Actual Behavior

Error: Error running plan: 1 error(s) occurred:

* azurerm_network_interface_backend_address_pool_association.test: 1 error(s) occurred:

* azurerm_network_interface_backend_address_pool_association.test: Resource 'azurerm_network_interface.test' not found for variable 'azurerm_network_interface.test.ip_configuration.*.name'

### Steps to Reproduce

1. `terraform plan | apply`

* #0000

**Comment by LW81** [comment]
I think i had a mistake in there ...sorry

**Comment by rgl** [comment]
sorry, why did you close this issue?
