### ISSUE TITLE
No node.js language support in azurerm_app_service?

### ISSUE THREAD

**Issue by samitpal** [terraform-providers/terraform-provider-azurerm#2183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems like there is no support for node.js language in azurerm_app_service.  I can see dot net, java, python and php though.
### New or Affected Resource(s)

* azurerm_app_service

### References

* https://www.terraform.io/docs/providers/azurerm/r/app_service.html/

**Comment by tombuildsstuff** [comment]
hi @samitpal @miguelemosreverte 

Thanks for opening this issue :)

Taking a look into this it appears this can be configured using the `linux_fx_version` parameter - which I've opened #2973 which includes an example of how to configure a Linux App Service with support for Node.JS.

Thanks!

**Comment by tombuildsstuff** [comment]
Fixed via #2973
