### ISSUE TITLE
Changing AKS linux_profile key data forces new resource

### ISSUE THREAD

**Issue by cmeyertons** [terraform-providers/terraform-provider-azurerm#2186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.17.0

### Affected Resource(s)

azurerm_kubernetes_cluster

### Expected Behavior

Terraform should update the `linux_profile.ssh_key.key_data` w/o forcing a new resource

### Actual Behavior

Terraform forces new resource

### Steps to Reproduce

1. create a kubernetes cluster w/ specified ssh key
1. `terraform apply`
1. change the ssh key
```
linux_profile {
        admin_username = "ubuntu"

        ssh_key {
          key_data = "${file("${var.ssh_public_key}")}" #<- new key!
        }
    }
```
1. terraform plan forces new resource

### References
https://docs.microsoft.com/en-us/azure/monitoring/monitoring-container-insights-onboard

**Comment by tombuildsstuff** [comment]
hi @cmeyertons 

Thanks for opening this issue :)

I've just checked via the Portal and it's not possible to change the SSH Key on an AKS Cluster at this time (I also can't see a relevant section in the link you've posted) - as such I don't think there's anything we can fix here at this time unfortunately. That said, I'd suggest [opening an issue on the ACS-Engine Repository](https://github.com/Azure/acs-engine/issues) (which is what AKS is based on) so the team can know that you're looking for this functionality.

Given I don't believe there's a way for us to move forward with this issue at this time - I'm going to close this issue for the moment.

Thanks!
