### ISSUE TITLE
Support "Custom Header Settings" field for Traffic Manager Endpoint

### ISSUE THREAD

**Issue by izpavlovich** [terraform-providers/terraform-provider-azurerm#2187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently Azure implemented support for adding custom headers to automatically for Traffic Manager endpoint. This functionally is currently missing from the provider

### New or Affected Resource(s)

Traffic Manager Endpoint

* azurerm_resource_arm_traffic_manager_endpoint

**Comment by sinvalmendes** [comment]
+1

**Comment by leonfs** [comment]
The latest Traffic Manager models for the Azure SDK support custom headers. 

https://github.com/Azure/azure-sdk-for-go/blob/master/services/trafficmanager/mgmt/2018-03-01/trafficmanager/models.go#L521

**Comment by mk811** [comment]
Thank you for raising this up. Yes, we definitely need this functionality.
Here is our use case.

[Use Case]
We have OpenShift Cluster, which is RedHat supported Kubernetes Cluster solution, on Azure.
Our OpenShift router, which is L7 load balancer in front of PODs, resolve request endpoint by HOSTNAME, which means that all requests to OpenShift are same IP but different hostnames.
To check our application in the cluster we definitely need to resolve health check coming from Traffic Manager by hostname.

I really hope to configure Custom Header Settings by Terraform

**Comment by YashwanthMannem** [comment]
When can we expect "custom header settings" attribute on the "azurerm_traffic_manager_profile" and "azurerm_traffic_manager_endpoint" terraform resources?
Also, I have noticed that "azurerm_traffic_manager_profile" terraform resource does not contain the following attributes "Expected Status Code Ranges", "Probing Interval", "Tolerated Number of Failures", "Probe Timeout"
