### ISSUE TITLE
Enable azurerm_policy_* operations at Management Group scope

### ISSUE THREAD

**Issue by pilor** [terraform-providers/terraform-provider-azurerm#2195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Policy resources (and RBAC resources for that matter) can be operated on at Management Group scope.  Management Groups are organizational entities in Azure that let you group subscriptions together into a tree and apply controls across many subscriptions at once.  This is a key feature for managing large-scale Azure environments.

These Management Group level operations are not supported in azurerm_policy_* terraform resources currently.

### New or Affected Resource(s)

* azurerm_policy_assignment
* azurerm_policy_definition

### Potential Terraform Configuration

I can provide REST API swagger specs upon request.

### References

* https://docs.microsoft.com/en-us/rest/api/resources/policydefinitions/createorupdateatmanagementgroup
* https://docs.microsoft.com/en-us/rest/api/resources/policyassignments/createbyid
* https://docs.microsoft.com/en-us/azure/governance/management-groups/

**Comment by liemnotliam** [comment]
I tried implementing this a while ago and kept on getting a 403 Authorization Failed when creating a management group policy (https://github.com/liemnotliam/terraform-provider-azurerm/tree/management-group-policy). This was tested with an identity that was elevated to Global Admin and had Owner permissions across. There was no problem when creating via the portal with that same identity. I've asked Microsoft about this but haven't heard anything back.

**Comment by pilor** [comment]
@liemnotliam what exact URI was being used by terraform when creating the policy definition (or assignment)?  

The identity had owner permissions explicitly on that management group (or inherited from above)?

**Comment by liemnotliam** [comment]
@pilor could you clarify which URI do you mean?

The identity has Owner permission both explicitly on that management group and inherited from above. It is also a [Global Admin](https://docs.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin) so it has User Access Administrator at the root scope (`/`)

**Comment by ksix** [comment]
@pilor - This code has just made it to release 1.21.0, was waiting for management group id to be assignable on policy definition creation. When we get the 403 Auth Failed, the URI it is attempting to do a PUT against when creating the policy definition is:

`https://management.azure.com/providers/Microsoft.Management/managementgroups//providers/Microsoft.Management/managementGroups/<mgmt_group_GUID>/providers/Microsoft.Authorization/policyDefinitions/<Policy_Definition_Name>?api-version=2018-05-01`

Line 153, here: [https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_policy_definition.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_policy_definition.go)

I'm super new to terraform and go, so at the limits of my ability to trace it further than that.

Full error I'm getting is:

`policy.DefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Servicereturned an error. Status=403 Code="AuthorizationFailed" Message="The client '<email address>' with object id '<User_GUID>' does not have authorization to perform action 'Microsoft.Management/managementgroups/Microsoft.Management/<Mgmt_Group_Guid>/Microsoft.Authorization/RequiredTag/write' over scope '/providers/Microsoft.Management/managementgroups/providers/Microsoft.Management/managementGroups/<Mgmt_Group_Guid>/providers/Microsoft.Authorization/policyDefinitions'."`

I've tried it with multiple accounts each with owner permissions on the mgmt group. Even creating the mgmt group in the exact same terraform apply as the previous step causes this error.

**Comment by olohmann** [comment]
@tombuildsstuff - I think this issue can be closed.

**Comment by tombuildsstuff** [comment]
@olohmann agreed - thanks for the heads-up :)

@ksix glad to hear this is now working for you :)
