### ISSUE TITLE
azurerm_storage_account does not persist 'bypass' network rule and reapplies same change on each run

### ISSUE THREAD

**Issue by OwenGr** [terraform-providers/terraform-provider-azurerm#2198]
A 'bypass' rule on `azurerm_storage_account` is recreated on each invocation of `terraform apply`, when no changes have been made.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.10
+ provider.azurerm v1.17.0
```

### Affected Resource(s)

* azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage" {
  name                      = "${var.storage_account_name}"
  resource_group_name       = "${var.resource_group_name}"
  location                  = "${var.location}"
  account_kind              = "${var.account_kind}"
  account_tier              = "${var.account_tier}"
  account_replication_type  = "${var.account_replication_type}"
  access_tier               = "${var.access_tier}"
  enable_https_traffic_only = "${var.enable_https_traffic_only}"
  account_encryption_source = "${var.account_encryption_source}"

  network_rules {
    bypass                     = "${var.bypass}"
  }
}

```

### Debug Output

```
  network_rules.#:                 "0" => "1"
  network_rules.0.bypass.#:        "0" => "1"
  network_rules.0.bypass.86530918: "" => "Logging"

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Panic Output

n/a

### Expected Behavior

Network_rules are created once.

### Actual Behavior

Network_rules are recreated with each invocation of Terraform apply.

### Steps to Reproduce

1. Run `terraform apply` two or more times. The first execution results in successful creation. Subsequent executions result in resource recreation every time. 

### Important Factoids

This does not occur with the `ip_rules` or `virtual_network_subnet_ids` properties.

### References

* #2164

**Comment by Leon99** [comment]
I have a similar problem, but with `virtual_network_subnet_ids` (see #2969).

**Comment by Lucretius** [comment]
Looking at the code, it appears that this happens because the set will just return an empty array if `ip_rules` and `virtual_network_subnet_ids` are both empty.  @Leon99 @OwenGr . I believe this makes sense, so this sounds like just a documentation update.

**Comment by Leon99** [comment]
Hold on, what about my problem? It doesn't involve bypass at all.

**Comment by Leon99** [comment]
@tombuildsstuff looks like #2969 is not a duplicate after all?

**Comment by Lucretius** [comment]
Hi @Leon99 - it looks like your issue is different to me after taking a look at it.  So you are saying that you used to have that network rule, deleted it from terraform, but terraform is not tracking that it was actually deleted?  Do you see that network rule in the portal anymore?

**Comment by Leon99** [comment]
I don't see that rule in the portal anymore.
