### ISSUE TITLE
Function App fetching a docker image from an Azure Container Registry.

### ISSUE THREAD

**Issue by tappoz** [terraform-providers/terraform-provider-azurerm#2202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8

### Affected Resource(s)

* azurerm_app_service

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "my_rg" {
  name = "${var.rg_name}"
  location = "${var.location}"
}

resource "azurerm_app_service_plan" "my_rg" {
  name                = "${var.app_service_plan}"
  location            = "${azurerm_resource_group.my_rg.location}"
  resource_group_name = "${azurerm_resource_group.my_rg.name}"
  kind                = "Linux"

  sku {
    tier = "Standard"
    size = "S1"
    capacity = 1
  }

  properties {
    reserved = true
  }
}

resource "azurerm_app_service" "my_rg" {
  name                = "${var.app_service}"
  location            = "${azurerm_resource_group.my_rg.location}"
  resource_group_name = "${azurerm_resource_group.my_rg.name}"
  app_service_plan_id = "${azurerm_app_service_plan.my_rg.id}"

  site_config {
    linux_fx_version = "DOCKER|<MY_CUSTOM_NAMESPACE>/<MY_CUSTOM_IMAGE_NAME>"
  }
}
```

The variables names (e.g. `${var.app_service}`) are defined in a separate `terraform.tfvars` file.

### Expected Behavior

I would like to create an Azure Function App of type "docker" picking the image from an Azure Container Registry. When using `linux_fx_version` with prefix `DOCKER|`, then the Function App tries (failing - see logs below) to fetch the image from the public Docker Hub, but on the Azure Portal I can select a private Azure Container Registry providing the authentication details. 

Checking here: https://www.terraform.io/docs/providers/azurerm/r/app_service.html#linux_fx_version
`DOCKER|` is mentioned as an example, what are the other values to use instead of `DOCKER|` for a private Azure Container Registry? How to specify the authentication details of the Azure Container Registry?

I've tried to use the Chrome Dev Tools to check IDs / ARM variable names in the HTML to see if I could spot this `DOCKER` prefix and use the Azure Container Registry ID/variable instead. This helped in the past in troubleshooting poorly documented ARM templates/functionality, but those HTML bits don't map in any way to the `terraform` terminology.

### Actual Behavior

The logs on the Azure Portal show:

```
2018_11_01_RD0003FF4328E9_docker.log:
2018-11-01 11:18:00.982 INFO  - Issuing docker pull: imagename =<MY_CUSTOM_NAMESPACE>/<MY_CUSTOM_IMAGE_NAME>
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tappoz** [comment]
This one does using the Terraform resource `azurerm_template_deployment` as described here: https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html
is not working.

Terraform seems to expect the resource (the Azure App) is already there, see the error message below.

I am not sure the 2 issues are related, probably not, but anyway there seems to be no way to deploy an Azure App using a docker image coming from a private Azure Container Registry.

See the details below:

```hcl
resource "azurerm_resource_group" "ci_rg" {
  name = "${var.rg_name}"
  location = "${var.location}"
}

resource "azurerm_app_service_plan" "ci_rg" {
  name                = "${var.app_service_plan}"
  location            = "${azurerm_resource_group.ci_rg.location}"
  resource_group_name = "${azurerm_resource_group.ci_rg.name}"
  kind                = "Linux"

  sku {
    tier = "Standard"
    size = "S1"
    capacity = 1
  }

  properties {
    reserved = true
  }
}

resource "azurerm_template_deployment" "ci_rg" {
  name = "template-01"
  resource_group_name = "${azurerm_resource_group.ci_rg.name}"

  template_body = <<DEPLOY
  {
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "app_name": {
        "type": "String",
        "metadata": {
          "description": "App Name"
        }
      },
      "docker_image_name": {
        "type": "String",
        "metadata": {
          "description": "Docker namespace/image_name:latest"
        }
      },
      "docker_registry_url": {
        "type": "String",
        "metadata": {
          "description": "Docker registry URL"
        }
      },
      "docker_registry_username": {
        "type": "String",
        "metadata": {
          "description": "Docker registry username"
        }
      },
      "docker_registry_password": {
        "type": "String",
        "metadata": {
          "description": "Docker registry password"
        }
      },
      "app_service_plan_id": {
        "type": "string",
        "metadata": {
          "description": "App Service Plan ID"
        }
      },
      "appLocation": {
        "type": "String",
        "value": "westeurope"
      }
    },
    "resources": [
      {
        "type": "Microsoft.Web/sites",
        "apiVersion": "2016-08-01",
        "name": "[parameters('appName')]",
        "kind": "app,linux,container",
        "location": "[parameters('appLocation')]",
        "properties": {
          "name": "[parameters('appName')]",
          "siteConfig": {
            "linuxFxVersion": "[concat('DOCKER|', parameters('dockerImageName'))]",
            "alwaysOn": true,
            "appSettings": [
              {
                "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                "value": "false"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_URL",
                "value": "[parameters('docker_registry_url')]"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                "value": "[parameters('docker_registry_username')]"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                "value": "[parameters('docker_registry_password')]"
              }
            ],
          },
          "serverFarmId": "[parameters('app_service_plan_id')]"
        }
      }
    ]
  }
DEPLOY

  // https://github.com/terraform-providers/terraform-provider-azurerm/issues/580
  parameters {
    app_service_plan_id      = "${azurerm_app_service_plan.ci_rg.id}"
    app_name                 = "${var.app_name}"
    docker_image_name        = "${var.docker_image_name}"
    docker_registry_url      = "${var.docker_registry_url}"
    docker_registry_username = "${var.docker_registry_username}"
    docker_registry_password = "${var.docker_registry_password}"
 }

  deployment_mode = "Incremental"
}
```

The variables values are defined in a separate file `terraform.tfvars`.

This is the output of the command `terraform plan`:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_resource_group.ci_rg: Refreshing state... (ID: /subscriptions/2010efac-93a5-49f4-8469-33e4e8d5a4b2/resourceGroups/CiTestRg)
azurerm_app_service_plan.ci_rg: Refreshing state... (ID: /subscriptions/2010efac-93a5-49f4-8469-...t.Web/serverfarms/foo-app-service-plan)
azurerm_app_service.ci_rg: Refreshing state... (ID: /subscriptions/2010efac-93a5-49f4-8469-...ers/Microsoft.Web/sites/orsted-fetcher)

Error: Error refreshing state: 1 error(s) occurred:

* azurerm_app_service.ci_rg: azurerm_app_service.ci_rg: Error making Read request on AzureRM App Service Configuration "<MY_APP_NAME>": web.AppsClient#GetConfiguration: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/<MY_APP_NAME>' under resource group '<MY_RG>' was not found."
```

**Comment by tappoz** [comment]
This last attempt using the resource `azurerm_template_deployment` worked after:
- removing some Terraform files which probably contained an inconsistent state from previous executions: `rm terraform.tfstate*`
- fixing some JSON validation and the docker image name to be like the pattern: `<MY_REGISTRY>.azurecr.io/<MY_NAMESPACE>/<MY_DOCKER_IMAGE_NAME>:latest`, see below for the full template.

However I still can not find a way to recall the Azure Container Registry authentication details inside the Terraform resource `azurerm_app_service`, is it possible at all? That would be much more compact and neat.

```hcl
  template_body = <<DEPLOY
  {
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "app_name": {
        "type": "String",
        "metadata": {
          "description": "App Name"
        }
      },
      "docker_image_name": {
        "type": "String",
        "metadata": {
          "description": "Docker namespace/image_name:latest"
        }
      },
      "docker_registry_url": {
        "type": "String",
        "metadata": {
          "description": "Docker registry URL"
        }
      },
      "docker_registry_username": {
        "type": "String",
        "metadata": {
          "description": "Docker registry username"
        }
      },
      "docker_registry_password": {
        "type": "String",
        "metadata": {
          "description": "Docker registry password"
        }
      },
      "app_service_plan_id": {
        "type": "string",
        "metadata": {
          "description": "App Service Plan ID"
        }
      },
      "app_location": {
        "type": "String",
        "metadata": {
          "description": "Azure Region"
        }
      }
    },
    "resources": [
      {
        "type": "Microsoft.Web/sites",
        "apiVersion": "2016-08-01",
        "name": "[parameters('app_name')]",
        "kind": "app,linux,container",
        "location": "[parameters('app_location')]",
        "properties": {
          "name": "[parameters('app_name')]",
          "siteConfig": {
            "linuxFxVersion": "[concat('DOCKER|', parameters('docker_image_name'))]",
            "alwaysOn": true,
            "appSettings": [
              {
                "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                "value": "false"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_URL",
                "value": "[parameters('docker_registry_url')]"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                "value": "[parameters('docker_registry_username')]"
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                "value": "[parameters('docker_registry_password')]"
              }
            ]
          },
          "serverFarmId": "[parameters('app_service_plan_id')]"
        }
      }
    ]
  }
DEPLOY
```

**Comment by tombuildsstuff** [comment]
hi @tappoz 

Thanks for opening this issue :)

Looking at the Terraform Configuration posted above the credentials are being specified as AppSettings - as such these should be able to be specified using [the `app_settings` block within the `azurerm_app_service` resource](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#app_settings). As such you should be able to make this:

```
resource "azurerm_app_service" "test" {
  # ...
  app_settings {
      "DOCKER_REGISTRY_SERVER_URL" = "some-url",
      "DOCKER_REGISTRY_SERVER_USERNAME" = "some-username",
      "DOCKER_REGISTRY_SERVER_PASSWORD" = "some-password",
  }
}
```

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment (however we'll continue responding 😄).

One thing of note - in the Terraform Configuration posted above all the resources/fields being used exist on the native Terraform Resource (`azurerm_app_service`) - as such I'd /strongly recommend/ using the native Terraform Resource where possible rather than the `azurerm_template_deployment` resource.

Thanks!

**Comment by tappoz** [comment]
Thanks @tombuildsstuff always very helpful, those extra `app_settings` worked :) 
Is there a way to specify also that we want logs to be enabled and the retention period in number of days? I am wondering if there is a place where all those settings e.g. `DOCKER_REGISTRY_SERVER_URL` are defined so someone can combine the settings they need knowing which key/value pairs the are allowed to use.

**Comment by tombuildsstuff** [comment]
@tappoz support for configuring the Log Settings for an App Service / Function Apps are being tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1082 - please subscribe to that issue for updates :)

Thanks!
