### ISSUE TITLE
azurerm_recovery_services_protected_vm documentation is not consistent with code requirements

### ISSUE THREAD

**Issue by brenak** [terraform-providers/terraform-provider-azurerm#2206]
https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protected_vm.html

The documentation states location, source_vm_name, and backup_policy_name are required.  The code does not have location,source_vm_name or backup_policy_name.  It does have backup_policy_id though.  Code shows the following as required:

resource_group_name
recovery_vault_name (forces new)
source_vm_id (forces new)

The following as optional:
backup_policy_id (forces new)

_Originally posted by @brenak in https://github.com/terraform-providers/terraform-provider-azurerm/pull/1637#issuecomment-434758474_

**Comment by katbyte** [comment]
Hi @brenak,

Thanks for opening this issue, this has already been fixed & merged and should go out in 1.18 🙂 

As such i am going to close the issue.
