### ISSUE TITLE
azurerm_recovery_services_protected_vm fails to create backup

### ISSUE THREAD

**Issue by brenak** [terraform-providers/terraform-provider-azurerm#2207]
Error creating/updating Recovery Service Protected VM "VM;iaasvmcontainerv2;my_rg;my_vm" (Resource Group "my_rg"): backup.ProtectedItemsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BMSUserErrorInvalidConfigureProtectionRequest" Message="Input for configure protection is not in proper format\r\nPlease ensure that container exists and other parameters are in valid format"

_Originally posted by @brenak in https://github.com/terraform-providers/terraform-provider-azurerm/pull/1637#issuecomment-434770289_

**Comment by tombuildsstuff** [comment]
hi @brenak 

Thanks for opening this issue :)

So that we can take a look into this would it be possible for you to provide the Terraform Configuration that you're experiencing this error with?

Thanks!

**Comment by AndreasMWalter** [comment]
> hi @brenak
> 
> Thanks for opening this issue :)
> 
> So that we can take a look into this would it be possible for you to provide the Terraform Configuration that you're experiencing this error with?
> 
> Thanks!

The issue described, sounds a lot like the issue which I reported here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2143#issuecomment-432960306
Sadly it was closed, however I will open another one  since the other issue only resolved the documentation, but not the incorrect Input.

**Comment by geertn** [comment]
FWIW: hitting the same issue as this and #2142, #2215.

```
## Conditional backup
resource "azurerm_recovery_services_protected_vm" "enable_backup" {
  count               = "${var.bck_enable == "true" && var.vm_count > 0 ? var.vm_count : 0}"

  resource_group_name = "${var.rs-vault-rg_name}"
  recovery_vault_name = "${var.rs-vault_name}"
  source_vm_id        = "${element(azurerm_virtual_machine.vm.*.id,count.index)}"
  backup_policy_id    = "${var.rs-vault-policy_id}"
}
```

Output:

> * module.vm.azurerm_recovery_services_protected_vm.enable_backup: 1 error(s) occurred:
> 
> * azurerm_recovery_services_protected_vm.enable_backup: Error creating/updating Recovery Service Protected VM "VM;iaasvmcontainerv2;vscsbx-recovery-services-rg;vscsbx-tst-vm-0" (Resource Group "vscsbx-recovery-services-rg"): backup.ProtectedItemsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BMSUserErrorInvalidInput" Message="Input provided for the call is invalid\r\nPlease check the required inputs"
> 

Using my previous approach with an ARM template it all works fine.

**Comment by brenak** [comment]
How much detail do you need.  If you want a full replication I can do that, but I'm not sure trying to post that in code blocks here is the best way.  

If this one small section that is failing isn't enough let me know and we can figure a better way to get you the whole set of code.  (I know in 1.18 the backup policy ID will be required, but this is for 1.17 and I do not have it in, hoping it uses the default, it did take it, no complaints from running the plan/apply)

```
resource "azurerm_recovery_services_protected_vm" "backup" {
  resource_group_name   = "${var.rg_name}"
  recovery_vault_name   = "${var.recovery_vault_name}"
  source_vm_id          = "${azurerm_virtual_machine.vm.id}"
}
```

**Comment by brenak** [comment]
This is the exact error that is in #2143.  That one was closed and issue #2215 was opened by Andreas, which is also the same error.  He added the required backup_policy_id, but had the vm in a different resource group than the recovery vault, which threw the error.  

Mine are in the same resource group, and I have not tested yet adding in the backup policy id.  I will do that soon and report back.  If that works this ticket can be closed as its fixed in 1.18 showing that its required.  #2215 by Andreas would then be considered a different issue than this, even though the error message is the same.

**Comment by AndreasMWalter** [comment]
> > *  Error creating/updating Recovery Service Protected VM "VM;iaasvmcontainerv2;**vscsbx-recovery-services-rg**;vscsbx-tst-vm-0"

Judging by your output I would assume that you as well as I tried to protect a VM which is in a different resource group as the recovery vault? That will of course work fine with an ARM template since the "protectionContainer" and "protectedItems" parameters expects the VM resource group and not the "Recovery vault resource group", which is incorrectly provided by the provider.

But then again I may be wrong and you have a different issue producing the same error.

**Comment by brenak** [comment]
I'm actually having a hard time finding out how to get the default backup_policy_id through terraform.  I can do it with scripts but that kind of defeats the purpose.

**Comment by brenak** [comment]
I have confirmed this is working for me.  It was the missing backup_policy_id.  

I tested two ways.  The first I created my own backup policy, and referenced its ID.  That worked fine (provided the VM and Recovery Vault are in the same Resource Group.  

Second, I used the default policy.  In order to obtain the DefaultPolicy ID, I just used the recovery_vault_id I created, then added "/backupPolicies/DefaultPolicy" to it.  There is no way to query for the policy id.  You can't even see it in Resource Explorer.  This is again, only works when the VM is in the same Resource Group as the Recovery Vault).

Working Code:
```
resource "azurerm_recovery_services_protected_vm" "backup" {
  resource_group_name   = "${var.rg_name}"
  recovery_vault_name   = "${var.recovery_vault_name}"
  source_vm_id          = "${azurerm_virtual_machine.vm.id}"
  backup_policy_id      = "${var.recovery_vault_id}/backupPolicies/DefaultPolicy"
}
```

Closing this.
