### ISSUE TITLE
Network Interface.Id prepends C:/Program Files/Git (running in Git Bash for Windows)

### ISSUE THREAD

**Issue by DinoSourcesRex** [terraform-providers/terraform-provider-azurerm#2208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version 
Terraform v0.11.10
+ provider.azurerm v1.17.0

### Affected Resource(s)

azurerm_network_interface

Specifically `.id`

### Terraform Configuration Files

The sample from [here](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html) is enough to try this, simply output 

```
output "nicid" {
  value = [
    "${azurerm_network_interface.nic.*.id}",
    "${azurerm_network_interface.nic.mac_address}",
    "${azurerm_network_interface.nic.private_ip_address}",
    "${azurerm_network_interface.nic.virtual_machine_id}",
    "${azurerm_network_interface.nic.applied_dns_servers}",
    "${azurerm_network_interface.nic.internal_fqdn}",
  ]
}
```

### Expected Behavior

`/subscriptions/------/resourceGroups/------/providers/microsoft.network/networkInterfaces/name_of_nic`

### Actual Behavior

`C:/Program Files/Git/subscriptions/------/resourceGroups/------/providers/microsoft.network/networkInterfaces/name_of_nic`

### Steps to Reproduce

Get the sample from [here](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html).
Add 
```
output "nicid" {
  value = [
    "${azurerm_network_interface.nic.*.id}",
    "${azurerm_network_interface.nic.mac_address}",
    "${azurerm_network_interface.nic.private_ip_address}",
    "${azurerm_network_interface.nic.virtual_machine_id}",
    "${azurerm_network_interface.nic.applied_dns_servers}",
    "${azurerm_network_interface.nic.internal_fqdn}",
  ]
}
```

### Important Factoids

I am running Windows 10. I am executing Terraform using Git Bash for Windows.

**Comment by tombuildsstuff** [comment]
hi @DinoSourcesRex 

Thanks for opening this issue :)

So that we're able to take a look into this would it be possible for you to paste a screenshot of the terminal output you're seeing here?

Thanks!

**Comment by DinoSourcesRex** [comment]
@tombuildsstuff Sure. You can see it [here](https://imgur.com/e5Fzl17).

**Comment by tombuildsstuff** [comment]
hi @DinoSourcesRex 

Thanks for that - taking a quick look into this this appears to e a Cygwin specific issue; out of interest do you see this issue using either the `cmd.exe` / `powershell.exe` terminals?

Thanks!

**Comment by DinoSourcesRex** [comment]
@tombuildsstuff I just ran `terraform apply` from both powershell and cmd as posted above.

**Comment by hazardsec** [comment]
I am seeing the same issue importing an existing resource group from Azure. I have tried surrounding the ID I am passing into import with quotes (single and double), no quotes, and escaping the backslashes and it still prepends the path C:/Program Files/Git.

``
$ terraform import azurerm_resource_group.RG_NAME \/subscriptions\/00000000-0000-0000-0000-000000000000\/resourceGroups\/RG_NAME
azurerm_resource_group.RG_NAME: Importing from ID "C:/Program Files/Git/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RG_NAME"...
azurerm_resource_group.RG_NAME: Import complete!
  Imported azurerm_resource_group (ID: C:/Program Files/Git/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RG_NAME)
azurerm_resource_groupRG_NAME: Refreshing state... (ID: C:/Program Files/Git/subscriptions/0000...esourceGroups/RG_NAME)

Import successful!
''

**Comment by hazardsec** [comment]
I found a workaround here https://stackoverflow.com/questions/48427366/docker-build-command-add-c-program-files-git-to-the-path-passed-as-build-argu. However, only the environmental variable works, not the double slash technique at beginning of path.

`
export MSYS_NO_PATHCONV="1 git blame -L/pathconv/ msys2_path_conv.cc"
`

**Comment by tombuildsstuff** [comment]
hey @DinoSourcesRex @hazardsec 

Thanks for confirming that - apologies for the delayed response here!

Taking a look into this, this appears to be a bug in Terraform Core (or potentially the CLI library that we use) - so that this can be investigated further I've ported this issue over to the Terraform Core repository: https://github.com/hashicorp/terraform/issues/20565 - would you mind subscribing to that issue for updates?

Thanks!
