### ISSUE TITLE
'azurerm_recovery_services_protected_vm' document fields don't match dev code.

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#2210]
Hi Team,
I found a document issue that 'azurerm_recovery_services_protected_vm' fields don't match dev code. Please have a check.
Thanks,
Chang

Reference:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/recovery_services_protected_vm.markdown
https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protected_vm.html

**Comment by katbyte** [comment]
Hi @lrxtom2,

Thanks for opening the issue, this has already been fixed in #2154 and should go out in 1.18 🙂 

As such i am going to close this.
