### ISSUE TITLE
Unable to launch workspace after create succesfully an azurerm_databricks_workspace

### ISSUE THREAD

**Issue by beeva-davidduque** [terraform-providers/terraform-provider-azurerm#2214]
Using the new "azurerm_databricks_workspace" i'm unable to launch the workspace. It's created and accesible through Azure Portal, but when I try to "Launch Workspace" it is unable to access (the error code is that the workspace doesn't exists on that location)

I was doing some test using an ARM template (trying to replicate the same error than the databricks created with terraform) and I think that the problem is the uppercase in SKU. If I create a databricks with my ARM template and select SKU to "Standard" (Uppercase) it doesn't work. But If launch the same ARM template with SKU to "standard" (Lowercase) it's fully accesible.

It could be an error or maybe I'm doing something wrong?

Thank you so much. Regards!

**Comment by sblack4** [comment]
I'm running into the same behavior - the code below produces a resource group with the correct IAM roles and a Databricks instance. When I go to launch the workspace I'm greeted with an error though 😢 

```
provider "azurerm" {
}
resource "azurerm_resource_group" "test" {
  name     = "test-steven-databricks"
  location = "westus2"
}

resource "azurerm_databricks_workspace" "test" {
  name                = "databricks-test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  sku                 = "Standard"

  tags {
    Environment = "test-steven-2018-11-14"
  }
}
```

![screen shot 2018-11-15 at 9 39 46 am](https://user-images.githubusercontent.com/15880760/48559929-b602d480-e8ba-11e8-94b8-800022bb5498.png)

**Comment by tombuildsstuff** [comment]
Whilst #2399 includes a fix to work around this - I've opened a bug on the Azure API to get the underlying issue fixed (since almost every other API in Azure requires that the Sku is in Title Case)

**Comment by sblack4** [comment]
Thank you @tombuildsstuff! 

Unfortunately, I'm still seeing the issue. What region did you test against? Is it possible that the issue is with the API? 

```
$ terraform version
Terraform v0.11.11
+ provider.azurerm v1.21.0
```

```
resource "azurerm_resource_group" "test" {
  name     = "steven-testing-databricks"
  location = "East US"
}

resource "azurerm_databricks_workspace" "test" {
  name                = "databricks-test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  sku                 = "standard"

  tags {
    Environment = "deleteme"
  }
}
```

**Comment by tombuildsstuff** [comment]
@sblack4 just to double check, you’re seeing that behaviour with a freshly provisioned DataBricks cluster too? I’ve asked for an update from the API team - but unfortunately this appears to be an issue at that end, so I don’t believe there’s a way to work around this unfortunately

**Comment by sblack4** [comment]
@tombuildsstuff, yes I tried provisioning a few times to make sure my eyes weren't deceiving me 😢 

Thank you for bringing this up with them!

**Comment by sblack4** [comment]
@tombuildsstuff I tried it with the script in the below gist and had success. Looking back at it I tried using `centralus` instead of `eastus`. I'll test terraform with `centralus` as well in case it's location-specific. 

https://gist.github.com/sblack4/e12f5b68d97afa799be82ea65c007e44

**Comment by sblack4** [comment]
First, sorry to be blowing this issue's comments up!

I ran [the script](https://gist.github.com/sblack4/e12f5b68d97afa799be82ea65c007e44) with `eastus` instead of `centralus` and got the no-sign-in bug again 

However `eastus` is on the list of supported regions, https://docs.azuredatabricks.net/administration-guide/cloud-configurations/regions.html

It seems this is a bug with the Azure REST Api and not terraform
