### ISSUE TITLE
Add `etag` attribute to `azurerm_storage_blob`

### ISSUE THREAD

**Issue by alxsey** [terraform-providers/terraform-provider-azurerm#2216]
Lacking of `etag` attribute for `azurerm_storage_blob` (like the one in `aws_s3_bucket_object`) complicates update procedures on source change.

**Comment by tombuildsstuff** [comment]
hi @alxsey 

Thanks for opening this issue :)

Support for this has previously been requested in #1990 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one - please subscribe to that issue for updates :)

Thanks!
