### ISSUE TITLE
azurerm_sql_server: Audit Configuration

### ISSUE THREAD

**Issue by midacts** [terraform-providers/terraform-provider-azurerm#2217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add SQL Server audit configuration

### New or Affected Resource(s)

- azurerm_sql_server
- azurerm_sql_database

![image](https://user-images.githubusercontent.com/3960208/47931104-3a5d5c80-dea4-11e8-8c67-e2943eae3a7d.png)

**Comment by mybayern1974** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/7597
https://github.com/hashicorp/terraform/issues/23161

**Comment by conork123** [comment]
Hi Guys I can see auditing is available in the azurerm_sql_database resource, but not in the azurerm_sql_serrver resource still. Will this be implemented?

Once applied at the server level it's inherited by any future DB's created. While we can enforce auditing through a DB terraform module, it would be nice to just set this once at the SQL server level.

**Comment by iandvt** [comment]
+1 - This is included in the CIS benchmarks and is available on the database resource but no the server. This is preventing my company from implementing proper IAC for CIS benchmarks.

**Comment by tomjosekal** [comment]
extended_auditing_policy supports only storage based auditing. 
What about Log Analytics and Event Hub based auditing?
