### ISSUE TITLE
azurerm_firewall: No option to create NAT rule collections and NAT rules

### ISSUE THREAD

**Issue by martinhacker1965** [terraform-providers/terraform-provider-azurerm#2224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable to create NAT rule collections or rules using the azurerm_firewall provider.

### New or Affected Resource(s)

azurerm_firewall

### Potential Terraform Configuration

```hcl
resource "azurerm_firewall_nat_rule_collection" "test" {
  name                = "test"
  azure_firewall_name = "test"
  resource_group_name = "test"
  priority            = 100
  action              = "Destination Network Address Translation (DNAT)"

  rule {
    name = "test"
    source_addresses = [""]
    destination_ports = [""]
    destination_addresses = [""]
    translated_address = [""]
    translated_port = [""]
    protocols = ["Any",]
  }
}
```

### References

* #0000

**Comment by rikribbers** [comment]
👍
