### ISSUE TITLE
Support Public IP Prefixes

### ISSUE THREAD

**Issue by rhnewtron** [terraform-providers/terraform-provider-azurerm#2239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Azure terraform provider does not support Azure Public IP Prefixes. Please support them. This would mean:

- I can create azure public ip prefixes
- I can create azurerm public ip's (standard) referencing the azure public ip prefix created before

This make on premise firewalling for larger clusters with a lot of NAT (e.g. Kubernetes/Openshift) easier.

### New or Affected Resource(s)

* azurerm_public_ip_prefix
* azurerm_public_ip (modified, add support to create from azurerm_public_ip_prefix)

### References

* See https://docs.microsoft.com/en-us/azure/virtual-network/manage-public-ip-address-prefix

**Comment by katbyte** [comment]
depends on #2433

**Comment by pixelicous** [comment]
@katbyte @tombuildsstuff Please push thissss :)

**Comment by steve-hawkins** [comment]
@pixelicous I have started to take a look at adding these resources today:-

azurerm_public_ip_prefix
azurerm_public_ip_prefix_association

will update with results

**Comment by pixelicous** [comment]
@steve-hawkins Hey! thanks for this! I understand what you mean, when creating ip address in the prefix you cannot choose which prefix it will be, very idiotic design decision imo, it also doesnt work very well in terraform, sometimes when generating it will skip a public ip that was created and deleted.

Again, thanks for your time, wish i knew GO or had time to learn/handle it myself..
