### ISSUE TITLE
Unable to compile provider

### ISSUE THREAD

**Issue by PleaseStopAsking** [terraform-providers/terraform-provider-azurerm#2242]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Azurerm provider

### Expected Behavior

The provider should have compiled.

### Actual Behavior

It hangs at 
```
PS C:\Go\src\github.com\terraform-providers\terraform-provider-azurerm> ls

    Directory: C:\Go\src\github.com\terraform-providers\terraform-provider-azurerm

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/5/2018   6:34 AM                .github
d-----        11/5/2018   6:34 AM                azurerm
d-----        11/5/2018   6:34 AM                examples
d-----        11/5/2018   6:34 AM                scripts
d-----        11/5/2018   6:34 AM                vendor
d-----        11/5/2018   6:34 AM                version
d-----        11/5/2018   6:34 AM                website
-a----        11/5/2018   6:34 AM            450 .gitignore
-a----        11/5/2018   6:34 AM            692 .gometalinter.json
-a----        11/5/2018   6:34 AM            539 .travis.yml
-a----        11/5/2018   6:34 AM          94868 CHANGELOG.md
-a----        11/5/2018   6:34 AM           2664 GNUmakefile
-a----        11/5/2018   6:34 AM          17098 LICENSE
-a----        11/5/2018   6:34 AM            231 main.go
-a----        11/5/2018   6:34 AM           3796 README.md

PS C:\Go\src\github.com\terraform-providers\terraform-provider-azurerm> make build
==> Checking that code complies with gofmt requirements...
FIND: Parameter format not correct
```

### Steps to Reproduce

1. Install newest version of Go and validated it was correctly working.
2. Install newest version of Make for Windows and validated it was correctly working.
3. Install newest Git and enabling "Use Git and optional Unix tools from Windows Command Prompt".
4. Cloned repo locally
5. Run ```make build```
### References

* #0000

**Comment by tombuildsstuff** [comment]
@metacpp would you be able to take a look at this?

**Comment by PleaseStopAsking** [comment]
I tested it on MacOS and had no issues compiling. I would like to be able to compile on Windows as that is my daily driver.

<img width="567" alt="screen shot 2018-11-05 at 8 15 35 am" src="https://user-images.githubusercontent.com/35308946/48000338-23e91800-e0d3-11e8-992e-cd7b379dcf94.png">

**Comment by metacpp** [comment]
@PleaseStopAsking 

This is because you don't have `find` utility installed on Windows.
```
FIND: Parameter format not correct
```

You can run below command under the root folder of `terraform-provider-azurerm` to double confirm:
```
find . -name '*.go' | grep -v vendor
```

**Comment by metacpp** [comment]
> find.exe is still located in C:\windows\system32\ but produces the same error when called directly. Will investigate further. Thanks for the guidance.

That "find" is not the same one as on Unix. If you have Git Bash installed with Unix tools, you should be able to use it directly under Git Bash console or add the "Git_install_folder\usr\bin" to PATH

**Comment by metacpp** [comment]
@PleaseStopAsking I am going to close this issue. If you still have issue while building provider on Windows, feel free to reopen it.
