### ISSUE TITLE
Question, version 1.18.0 azurerm_virtual_machine - making availability_set_id conflict with zones (#2185)

### ISSUE THREAD

**Issue by jcmaasb** [terraform-providers/terraform-provider-azurerm#2246]
Hi, this change in version 1.18.0 is necessary?
I have a module in which I have a resource azurerm_virtual_machine with the properties of availability_set_id and zones, and I can choose which method to use through the configuration.

If the configuration is not correct and I choose both, I receive an error indicating the reason. that's not enough?
_Message =" The virtual machine can not be created because
using both the Availability Zone and the Availability Set were specified. The implementation of an availability set in an availability zone is not compatible. "_

But now with version 1.18.0, if I want to declare the two options in the resource, I need to duplicate the code, because it generates an error that can not be avoided.
_Error: module.backend.azurerm_virtual_machine.cz_lin [2]: "Availability_set_id": conflicts with zones_

Is there something I do not understand or my approach is not right?

**Comment by tombuildsstuff** [comment]
hi @jcmaasb 

Thanks for opening this issue :)

Version 1.18 of the AzureRM Provider introduced a plan-time conflict between the `availability_set_id` field and the `zones` field - since as you'e highlighted this configuration isn't valid. It should be possible to support both in a module by setting the value to an empty string (which means that Terraform will ignore it) - from the error message you're seeing (`"Availability_set_id": conflicts with zones`) - it sounds like a default value may be being set for both fields - would it be possible to paste the Terraform Configuration you're using so we can take a look?

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by cfabrizio-gig** [comment]
Hi @tombuildsstuff , I'm having the same problem, how can I pass a default value? I tried to set `zone = "null"` or `zone = 0` both the value have been ignored, an I got the same error `"Availability_set_id": conflicts with zones`, any suggestions? :-)
Thanks

**Comment by tombuildsstuff** [comment]
@cfabrizio-gig you should be able to set this value to an empty string :)

**Comment by cfabrizio-gig** [comment]
@tombuildsstuff I tried with empty value too, but nothing still getting the same error :-(

main.tf

`module "TEST-VM-CF001" {
  source              = "../modules/linux"
  prefix              = "TEST-VM-CF001"
  resource_group_name = "LAB-TERRAFORM"
  location            = "westeurope"

  zones      = ""
  vm_size    = "Standard_F4s_v2"
  net-id     = "${module.TEST-VM-CF001-net.network_VM}"
  network_IP = "${module.TEST-VM-CF001-net.network_IP}"
  tags       = "${var.tags}"

  availabilityset = "${module.TEST-VM-CF001-as.availabilityset-id}"
}

module "TEST-VM-CF001-net" {
  source              = "../modules/network"
  prefix              = "TEST-VM-CF001"
  resource_group_name = "LAB-TERRAFORM"
  location            = "westeurope"

  zones       = "/"
  subnet_name = "gig-lab-subnet"
  network_IP  = "${module.TEST-VM-CF001-net.network_IP}"
  dns         = ["1.2.3.4", "5.6.7.8"]
}

module "TEST-VM-CF001-as" {
  source                       = "../modules/availability_set"
  availability_set_name        = "TEST-VM-CF001"
  resource_group_name          = "LAB-TERRAFORM"
  location                     = "westeurope"
  platform_fault_domain_count  = "3"
  platform_update_domain_count = "5"
  tags                         = "${var.tags}"
}`

linux/main.tf

`locals {
  virtual_machine_name = "${var.prefix}"
  admin_username       = "user"
  admin_password       = "Password123!"
}

# Create virtual machine
resource "azurerm_virtual_machine" "template" {
  name                             = "${local.virtual_machine_name}"
  location                         = "${var.location}"
  resource_group_name              = "${var.resource_group_name}"
  network_interface_ids            = ["${var.net-id}"]
  availability_set_id              = "${var.availabilityset}"
  vm_size                          = "${var.vm_size}"
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_os_disk {
    name              = "${local.virtual_machine_name}-OsDisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Premium_LRS"
  }

  storage_image_reference {
    publisher = "OpenLogic"
    offer     = "CentOS"
    sku       = "7.5"
    version   = "latest"
  }

  os_profile {
    computer_name  = "${local.virtual_machine_name}"
    admin_username = "${local.admin_username}"
    admin_password = "${local.admin_password}"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }

  zones = ["${var.zones}"]
  tags  = "${var.tags}"
}
`

**Comment by tombuildsstuff** [comment]
@cfabrizio-gig got it - you should be able to make `var.zones` a list via:

```
variable "zones" {
  type = "list"
}
```

and then assign that via:

```
zones = "${var.zones}"
```

**Comment by cfabrizio-gig** [comment]
@tombuildsstuff no luck, now I'm getting ` module.TEST-VM-CF001.var.zones: variable zones in module TEST-VM-CF001 should be type list, got string` there is something wrong that I cannot figure it out.

main.tf

```
module "TEST-VM-CF001" {
  source              = "../modules/linux"
  prefix              = "TEST-VM-CF001"
  resource_group_name = "GIG-LAB-TERRAFORM"
  location            = "westeurope"

  zones      = ""
  vm_size    = "Standard_F4s_v2"
  net-id     = "${module.TEST-VM-CF001-net.network_VM}"
  network_IP = "${module.TEST-VM-CF001-net.network_IP}"
  tags       = "${var.tags}"

  availabilityset = "${module.TEST-VM-CF001-as.availabilityset-id}"
}

module "TEST-VM-CF001-net" {
  source              = "../modules/network"
  prefix              = "TEST-VM-CF001"
  resource_group_name = "LAB-TERRAFORM"
  location            = "westeurope"
  subnet_name         = "gig-lab-subnet"
  network_IP          = "${module.TEST-VM-CF001-net.network_IP}"
  dns                 = ["1.2.3.4", "5.6.7.8"]
}

module "TEST-VM-CF001-as" {
  source                       = "../modules/availability_set"
  availability_set_name        = "TEST-VM-CF001"
  resource_group_name          = "LAB-TERRAFORM"
  location                     = "westeurope"
  platform_fault_domain_count  = "3"
  platform_update_domain_count = "5"
  tags                         = "${var.tags}"
}
```

linux/main.tf

```
locals {
  virtual_machine_name = "${var.prefix}"
  admin_username       = "user"
  admin_password       = "Password123!"
}

# Create virtual machine
resource "azurerm_virtual_machine" "template" {
  name                             = "${local.virtual_machine_name}"
  location                         = "${var.location}"
  resource_group_name              = "${var.resource_group_name}"
  network_interface_ids            = ["${var.net-id}"]
  availability_set_id              = "${var.availabilityset}"
  vm_size                          = "${var.vm_size}"
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_os_disk {
    name              = "${local.virtual_machine_name}-OsDisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Premium_LRS"
  }

  storage_image_reference {
    publisher = "OpenLogic"
    offer     = "CentOS"
    sku       = "7.5"
    version   = "latest"
  }

  os_profile {
    computer_name  = "${local.virtual_machine_name}"
    admin_username = "${local.admin_username}"
    admin_password = "${local.admin_password}"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }

  zones = "${var.zones}"
  tags  = "${var.tags}"
}
```



linux/variables.tf


```
variable "prefix" {}
variable "location" {}

variable "zones" {
  type = "list"
}

variable "resource_group_name" {}
variable "vm_size" {}
variable "net-id" {}
variable "network_IP" {}
variable "availabilityset" {}

variable "tags" {
  type = "map"
}
```
 like so I am getting the conflicts error

```
module "TEST-VM-CF001" {
  source              = "../modules/linux"
  prefix              = "TEST-VM-CF001"
  resource_group_name = "GIG-LAB-TERRAFORM"
  location            = "westeurope"

  zones      = ["0"]
  vm_size    = "Standard_F4s_v2"
  net-id     = "${module.TEST-VM-CF001-net.network_VM}"
  network_IP = "${module.TEST-VM-CF001-net.network_IP}"
  tags       = "${var.tags}"

  availabilityset = "${module.TEST-VM-CF001-as.availabilityset-id}"
}
```

**Comment by tombuildsstuff** [comment]
@cfabrizio-gig a string is being passed in here:

```
module "TEST-VM-CF001" {
  # ...
  zones      = ""
  # ...
}
```

when an empty list should be passed (since the variable is now a list):


```
module "TEST-VM-CF001" {
  # ...
  zones      = []
  # ...
}
```

Hope that helps :)

**Comment by cfabrizio-gig** [comment]
@tombuildsstuff nope no luck

still ```Error: module.TEST-VM-CF001.azurerm_virtual_machine.template: "availability_set_id": conflicts with zones```

**Comment by tombuildsstuff** [comment]
@cfabrizio-gig in which case I'd suggest it'd be easier to split that into two different modules to obtain that behaviour. In general we'd recommend creating specific/opinionated modules (e.g. deploying a cluster of VM's one per Zone) vs a generic module (trying to support both availability sets and zones) - since it makes the upgrade path easier when modifying the module longer term

**Comment by cfabrizio-gig** [comment]
alright thanks mate, this is exactly what I did
