### ISSUE TITLE
Built against v0.12 causes too many items for attribute "os_profile"

### ISSUE THREAD

**Issue by kim0** [terraform-providers/terraform-provider-azurerm#2256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.0-dev (c795302ab2d844a6d56d520e32639af3d0801763+CHANGES)
+ provider.azurerm v1.28.0 (Built from trunk, I gave it this version number)

### Affected Resource(s)

* azurerm_virtual_machine

### Terraform Configuration Files

```hcl
variable "prefix" {
  default = "tfvmex"
}

resource "azurerm_resource_group" "main" {
  name     = "${var.prefix}-resources"
  location = "West US 2"
}

resource "azurerm_virtual_network" "main" {
  name                = "${var.prefix}-network"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
}

resource "azurerm_subnet" "internal" {
  name                 = "internal"
  resource_group_name  = "${azurerm_resource_group.main.name}"
  virtual_network_name = "${azurerm_virtual_network.main.name}"
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "main" {
  name                = "${var.prefix}-nic"
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = "${azurerm_subnet.internal.id}"
    private_ip_address_allocation = "dynamic"
  }}

resource "azurerm_virtual_machine" "main" {
  name                  = "${var.prefix}-vm"
  location              = "${azurerm_resource_group.main.location}"
  resource_group_name   = "${azurerm_resource_group.main.name}"
  network_interface_ids = ["${azurerm_network_interface.main.id}"]
  vm_size               = "Standard_DS1_v2"

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  # delete_os_disk_on_termination = true


  # Uncomment this line to delete the data disks automatically when deleting the VM
  # delete_data_disks_on_termination = true
  os_profile {
          computer_name = "foo"
          admin_username = "kim0"
  }

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
  storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  # os_profile {
  #   computer_name  = "hostname"
  #   admin_username = "testadmin"
  #   admin_password = "Password1234!"
  # }
  os_profile_linux_config {
    disable_password_authentication = false
  }
}
```

### Expected Behavior
TF would create the VM

### Actual Behavior

`Error: too many items for attribute "os_profile"; must have at least 0`
Interestingly, commenting out the os_profile section, causes `plan` to succeed!

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Both terraform and the provider are built from master. I'm trying to assess if the new v0.12 is able to meet my needs.

**Comment by tombuildsstuff** [comment]
hi @kim0 

Thanks for opening this issue.

At this time bugs in the 0.12-alpha are being tracked in [the Terraform Core](https://github.com/hashicorp/terraform) repository, since they're likely issues with Terraform Core itself. Would you mind re-opening this on that repository instead?

Thanks!
