### ISSUE TITLE
azurerm_application_gateway configure backend_http_settings hostname

### ISSUE THREAD

**Issue by CryptonZylog** [terraform-providers/terraform-provider-azurerm#2258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure supports configuring backend HTTP setting rule to specify a Host Name (host header) when proxying requests. Right now terraform doesn't seem to have support for this in `backend_http_settings`.

### New or Affected Resource(s)

* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
...

backend_http_settings {
    name                  = "${azurerm_virtual_network.vnet.name}-be-htst"
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 1
    host_name        = "backend-host.azurewebsites.net" # Host Name textbox
}

...
```

Now, I wonder if emulating the checkbox to pick from backend address, terraform could look into fqdn list of `backend_address_pool` respective via `request_routing_rule`.

---------------------

## Custom Host specified

![2](https://user-images.githubusercontent.com/1175100/48093921-90444400-e1c5-11e8-8ed5-1d0cdd928823.png)

## Using backend address
![1](https://user-images.githubusercontent.com/1175100/48093922-90444400-e1c5-11e8-8918-1b8fb8f0bef2.png)

**Comment by CryptonZylog** [comment]
I guess a temporary workaround could be running a null_resource provisioner that calls:

`az network application-gateway http-settings update -g <rg name> --gateway-name <apg name> -n <http setting name> --host-name-from-backend-pool true`

**Comment by tombuildsstuff** [comment]
hi @CryptonZylog 

Thanks for opening this issue :)

Support for this has previously been requested in #1875 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #1875 - please subscribe to that issue for updates.

Thanks!
