### ISSUE TITLE
Data source to be used with azurerm_role_assignment.principal_id 

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#2266]
It would be good to have a data source that could retrieve the value needed for principal_id given a name of an AAD user/group. I.e. I know the name of a group/user, and I want to give some permissions to them, but I'm required to supply the id rather than the name, so I define a data source and use its output.

**Comment by tombuildsstuff** [comment]
hi @Leon99 

Thanks for opening this issue :)

Support for this has previously been requested in #1272 which I'm going to close this issue in favour of - please subscribe to that issue for updates.

Thanks!
