### ISSUE TITLE
principal_id vs. object id

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#2267]
This provider uses name principal_id (e.g. https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html#principal_id), while PowerShell references this ID as Object ID. I'm curious as to why principal_id is used instead of object_id?

**Comment by Leon99** [comment]
Oh, and it's actually named object_id, for instance, in azurerm_key_vault.access_policy.

**Comment by tombuildsstuff** [comment]
hi @Leon99 

Thanks for opening this issue :)

Different API's within Azure have slightly different terminology for the same thing - as such we try and use the terms provided by the API where they make sense. In this case [the field `principal_id` is used in the Role Assignments API](https://docs.microsoft.com/en-us/rest/api/authorization/roleassignments/createbyid) and ObjectID is used by [the Key Vault API's](https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/updateaccesspolicy) - as such we've opted to use the terminology used by each API.

Thanks!

**Comment by Leon99** [comment]
Well, the official Azure CLI/PowerShell module masks this inconsistency by using ObjectId everywhere (https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest/https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermroleassignment?view=azurermps-6.12.0), I don't see why not fix it here as well.
