### ISSUE TITLE
Documentation updates to azurerm_recovery_services_protected_vm

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#2278]
In the documentation for azurerm_recovery_services_protected_vm (https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/recovery_services_protected_vm.markdown) there are the following problems:

* The example name is invalid. `invalid value for name (Backup Policy name must be 3 - 150 characters long, start with a letter, contain only letters and numbers.)`
* location is not valid here, it is determined by the vault. `invalid or unknown key: location`

**Comment by katbyte** [comment]
Hi @mbrancato,

Thank you for bringing these mistakes to our attention! I have opened #2282 to resolve this.

**Comment by mbrancato** [comment]
Hi @katbyte 

Sorry I couldn't review before merge.  The `location` is still listed as required below the examples, when it is not actually allowed to be specified.

**Comment by katbyte** [comment]
Thank you very much for checking @mbrancato,

I have removed it as part of #2287

**Comment by mbrancato** [comment]
Thanks @katbyte. Y’all are awesome.
