### ISSUE TITLE
TTL is in seconds or minutes?

### ISSUE THREAD

**Issue by cmeyertons** [terraform-providers/terraform-provider-azurerm#2290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the azure terraform docs, please supply the units for TTL (seconds / minutes)

### New or Affected Resource(s)

azurerm_dns_*

https://www.terraform.io/docs/providers/azurerm/r/dns_mx_record.html#ttl

**Comment by cmeyertons** [comment]
Thanks -- any chance this can make its way into the Terraform docs?

**Comment by katbyte** [comment]
Hi @cmeyertons,

I have updated to documentation in #2302 🙂 It should go live when 1.19 is released soonish.

**Comment by cmeyertons** [comment]
@katbyte thank you!
