### ISSUE TITLE
Terraform apply not idempotent for managed disks on Azure

### ISSUE THREAD

**Issue by lubars** [terraform-providers/terraform-provider-azurerm#2291]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.8
+ provider.azurerm v1.13.0
```

### Affected Resource(s)

* azurerm_managed_disk
* azurerm_network_interface
* azurerm_network_security_group
* azurerm_public_ip
* azurerm_resource_group
* azurerm_storage_account
* azurerm_storage_container
* azurerm_subnet
* azurerm_virtual_machine
* azurerm_virtual_network

### Terraform Configuration Files

terraform.tfvars (with bogus credentials):

```
SubscriptionId = "6364n0q5-8673-6794-1718-141s4pp87spr"
ClientId = "opo3581q-1501-ssr4-722n-r0n63orrs19p"
ClientSecret = "z688QR9tZq5ekvSVrqVcWErV6N2Dtzirk5CBXrqzw4n="
TenantId = "4nonn747-8292-2794-25po-743687o0os55"
PublisherName = "RedHat"
Offer = "RHEL"
Sku = "7-RAW"
Version = "7.5.2018050901"
SSHUser = "azureuser"
SSHPassword = "AzureUser_123"
Location = "Central US"
TimeZone = "America/New_York"
Size = "Standard_DS2_v2"
AccountTier = "Standard"
AccountReplicationType = "LRS"
DataVolumeSize = "10"
OSVolumeSize = "32"
```

infrastructure.tf:
```
variable "Count" {default = "1"}
variable "AccountReplicationType" {}
variable "AccountTier" {}
variable "Location" {}
variable "Size" {}
variable "PublisherName" {}
variable "Offer" {}
variable "Sku" {}
variable "Version" {}
variable "ClientId" {}
variable "ClientSecret" {}
variable "SubscriptionId" {}
variable "TenantId" {}
variable "net_subnet_cidr" {default = "10.0.0.0/24"}
variable "net_vpc_cidr" {default = "10.0.0.0/16"}
variable "public_ip_config_name" {default = "PublicIPAddress"}
variable "SSHPassword" {}
variable "SSHUser" {}
variable "OSVolumeSize" {}
variable "DataVolumeSize" {}

provider "azurerm" {
  subscription_id = "${var.SubscriptionId}"
  client_id       = "${var.ClientId}"
  client_secret   = "${var.ClientSecret}"
  tenant_id       = "${var.TenantId}"
}

resource "azurerm_resource_group" "default" {
  name = "test"
  location = "${var.Location}"
}

resource "azurerm_storage_account" "default" {
  name = "test"
  resource_group_name = "${azurerm_resource_group.default.name}"
  location = "${var.Location}"
  account_tier = "${var.AccountTier}"
  account_replication_type = "${var.AccountReplicationType}"
}

resource "azurerm_storage_container" "default" {
  name = "test"
  resource_group_name = "${azurerm_resource_group.default.name}"
  storage_account_name  = "${azurerm_storage_account.default.name}"
  container_access_type = "private"
}

resource "azurerm_virtual_network" "default" {
  name = "test"
  address_space       = ["${var.net_vpc_cidr}"]
  location = "${var.Location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
}

resource "azurerm_subnet" "default" {
  name = "test"
  resource_group_name = "${azurerm_resource_group.default.name}"
  virtual_network_name = "${azurerm_virtual_network.default.name}"
  address_prefix       = "${var.net_subnet_cidr}"
  network_security_group_id = "${azurerm_network_security_group.default.id}"
}

resource "azurerm_network_interface" "default" {
  count = "${var.Count}"
  name = "test{count.index}"
  location = "${var.Location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  network_security_group_id = "${azurerm_network_security_group.default.id}"
  ip_configuration {
    name = "test"
    subnet_id = "${azurerm_subnet.default.id}"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id = "${azurerm_public_ip.default.*.id[count.index]}"
  }
}

resource "azurerm_public_ip" "default" {
  count = "${var.Count}"
  name = "test{count.index}"
  location = "${var.Location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  public_ip_address_allocation = "Static"
  sku = "standard"
  domain_name_label = "test{count.index}"
}

resource "azurerm_network_security_group" "default" {
  name = "test"
  location = "${var.Location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
}

resource "azurerm_managed_disk" "data" {
  count = "${var.Count}"
  name = "data${count.index}"
  location = "${var.Location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  storage_account_type = "${var.AccountTier}_${var.AccountReplicationType}"
  create_option = "empty"
  disk_size_gb  = "${var.DataVolumeSize}"
}

resource "azurerm_virtual_machine" "default" {
  name = "test${count.index}"
  location = "${var.Location}"
  count = "${var.Count}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  network_interface_ids = ["${azurerm_network_interface.default.*.id[count.index]}"]
  vm_size               = "${var.Size}"
  delete_os_disk_on_termination = true
  //delete_data_disks_on_termination = false

  storage_image_reference {
    publisher = "${var.PublisherName}"
    offer = "${var.Offer}"
    sku = "${var.Sku}"
    version = "${var.Version}"
  }
  storage_os_disk {
    name = "os${count.index}"
    managed_disk_type = "${var.AccountTier}_${var.AccountReplicationType}"
    disk_size_gb = "${var.OSVolumeSize}"
    create_option = "FromImage"
    os_type = "linux"
  }
  storage_data_disk {
    name = "data${count.index}"
    managed_disk_id = "${azurerm_managed_disk.data.*.id[count.index]}"
    disk_size_gb  = "${azurerm_managed_disk.data.*.disk_size_gb[count.index]}"
    create_option = "Attach"
    lun = 0
  }
  os_profile {
    computer_name  = "test${count.index}"
    admin_username = "${var.SSHUser}"
    admin_password = "${var.SSHPassword}"
  }
  os_profile_linux_config {
    disable_password_authentication = false
  }
}
```

### Debug Output
Debug output (with bogus credentials) is [here](https://gist.githubusercontent.com/lubars/6f23479c59e25926340aec904434e6f1/raw/4108da4a85551021449573575f71eaf6522fb7c4/debug.out).

### Expected Behavior

Should have been able to terraform apply twice in a row (with no intervening changes)

### Actual Behavior

Got the following error on the second invocation of terraform apply:
```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_managed_disk.data (destroy): 1 error(s) occurred:

* azurerm_managed_disk.data: compute.DisksClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Disk data0 is attached to VM /subscriptions/6364n0q5-8673-6794-1718-141s4pp87spr/resourceGroups/test/providers/Microsoft.Compute/virtualMachines/test0."
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform apply`

### Important Factoids

This problem occurs when I `apply` twice in a row with _any_ count (including a count of "1").  I originally discovered it when trying to scale up a deployment (e.g. changing the count from "3" to "4"), but again, this occurs when no changes to the configuration are made.

### References

Originally filed [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2275), but was closed due to a misunderstanding about what was being reported.

I looked at the following issues (before I realized the problem occurred even when the count remained the same):

[Azure Official Example fails when augmenting it with a count logic to support VM scaling](https://github.com/terraform-providers/terraform-provider-azurerm/issues/40)
[Azure Official Example fails when augmenting it with a count logic to support VM scaling](https://github.com/hashicorp/terraform/issues/11821)
[Azure Example fails when augmenting it with count to support VM scaling](https://github.com/azdevops/terraform/issues/6)
[Increasing Count of Elements causes Plan with destruction of all previous](https://github.com/hashicorp/terraform/issues/17014)
[Please allow data disks to be added to existing machines in inventory in-line without destroy/recreate](https://github.com/terraform-providers/terraform-provider-azurerm/issues/582)

Two of the things I tried (to no avail) were:

1. Based on [this ](https://github.com/hashicorp/terraform/issues/17014#issuecomment-355153582)comment, changed from element syntax:
`managed_disk_id = "${element(azurerm_managed_disk.data.*.id,count.index)}"`
to array syntax:
`managed_disk_id = "${azurerm_managed_disk.data.*.id[count.index]}"`

Based on [this ](https://github.com/hashicorp/terraform/issues/11821#issuecomment-306222716)comment, added the following to the azurerm_managed_disk resource:

```
lifecycle {
    ignore_changes = [ "azurerm_virtual_machine", "storage_os_disk", "storage_data_disk", "os_profile" ]
}
```

**Comment by tombuildsstuff** [comment]
hi @lubars 

Thanks for opening this issue. Since this topic is already being discussed in #2275 - I'm going to close this issue in favour of that issue.

Thanks!

**Comment by mbrancato** [comment]
Hi @lubars,

Have you tried using the `element()` interpolation to access all of your items instead of trying to access the list item directly? You are doing this in multiple places under `azurerm_virtual_machine`.

I’m guessing this works fine with `var.Count = 1`?

**Comment by lubars** [comment]
Hi @mbrancato,

1.  I was using element() before I switched to array indexing (see "Things I Tried").  It fails both ways.
2.  This fails with var.Ccount = 1 (as per the terraform.tfvars file included).

**Comment by lubars** [comment]
Hi @tombuildsstuff,

If you're going to close this in favor of [#2275](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2275), please re-open that issue; I feel it was closed prematurely, thanks.

**Comment by lubars** [comment]
@mbrancato, you solved it!  The problem was using "empty" instead of "Empty".  From the [azure_managed_disk](https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html) documentation:

> create_option - (Required) The method to use when creating the managed disk. Possible values include:
> - Import - Import a VHD file in to the managed disk (VHD specified with source_uri).
> - Empty - Create an empty managed disk.
> - Copy - Copy an existing managed disk or snapshot (specified with source_resource_id).
> - FromImage - Copy a Platform Image (specified with image_reference_id)

Perhaps this should be caught during the `plan` phase?

(As for the invalid characters, that's a cut-and-paste issue between emacs and github - for some reason it has been stripping off some of the dollar signs.)

Much thanks.
