### ISSUE TITLE
How to transfer a Binary File via Custom Data?

### ISSUE THREAD

**Issue by KbLev** [terraform-providers/terraform-provider-azurerm#2297]
I have a zip file that I want to drop on my Azure Windows VM. The VM does not have internet access therefore the file provisioner is out of question, but custom_data should do it. Worst case scenario I can base64 encode the file and decode it later via first_logon_commands.xml (at least that's what I was thinking).

However, when I try to provision the file, I get different errors.
I think I tried all combinations that I can think of:

`custom_data      = "${file("../scripts.zip")}` # vm creation fails

`custom_data      = "${base64encode(file("../scripts.zip"))}`  # vm creation fails with error:  _azurerm_virtual_machine.vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20181112T174017Z', subscription id '309777eb-7336-4573-ae5b-8382df0f3615', tracking id '7d590526-408c-42e2-91ab-b820437f3af5', request correlation id '7d590526-408c-42e2-91ab-b820437f3af5'."_

`custom_data      = "${base64decode(file("../scripts.zip.b64"))}"`  # takes forever to load because all characters are outputted to the screen, don't know if it works at all.

`custom_data      = "${base64encode(file("../scripts.zip.b64"))}"`  # terraform apply fails with error: * _azurerm_virtual_machine.vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF_

`data "template_file" "scripts" {   template = "${file("../scripts.zip.b64")}" }`
`custom_data      = "${data.template_file.scrips.rendered}" ` #
_azurerm_virtual_machine.vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20181112T194947Z', subscription id '309777eb-7336-4573-ae5b-8382df0f3615', tracking id '779af7dd-f1ae-4606-9138-fdc92527d35c', request correlation id '779af7dd-f1ae-4606-9138-fdc92527d35c'."_

So, how can I drop this scripts.zip on the VM? The file is 4MB in size.

**Comment by KbLev** [comment]
Reading my post again, looks like it's never going to work as 4 MB > 64 K (facepalm)

**Comment by tombuildsstuff** [comment]
hey @KbLev 

Thanks for opening this issue :)

As you've mentioned there's a limit of 64kb for the custom data block - so unfortunately that approach won't work. Since there's 4MB worth - may I ask what's in the scripts you're attempting to apply as a part of this ZIP file? If there's no internet access one approach would be to use [Packer](https://packer.io) to build an image with this pre-installed - but there may well be another approach here depending on the scripts being used.

Thanks!
