### ISSUE TITLE
azurerm_virtual_machine_extension error code 1007

### ISSUE THREAD

**Issue by gsjaya-19** [terraform-providers/terraform-provider-azurerm#2303]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---We are trying to run a PowerShell script during the spin up windows vms
we are able to run the exact same script using the web portal and when we run it on the web portal it uses version 1.9.2
when I run it in terraform it tries to use version 2.0.6

this is the error message I get

Error: Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine_extension.saetVmNs: 1 error(s) occurred:

* azurerm_virtual_machine_extension.saetVmNs: Code="VMExtensionHandlerNonTransientError" Message="Handler 'Microsoft.Azure.Extensions.CustomScript' has reported failure for VM Extension 'saet-ausc-01-ns-vm' with terminal error code '1007' and error message: 'Install failed for plugin (name: Microsoft.Azure.Extensions.CustomScript, version 2.0.6) with exception The specified executable is not a valid application for this OS platform.'"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

and this is the code we are using in terraform
resource "azurerm_virtual_machine_extension" "saetVmNs" {
  name                 = "${azurerm_resource_group.saetRsg.name}-ns-vm"
  location             = "${azurerm_resource_group.saetRsg.location}"
  resource_group_name  = "${azurerm_resource_group.saetRsg.name}"
  virtual_machine_name = "${azurerm_virtual_machine.saetVmAp.name}"
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"

  #type_handler_version = "${var.typeHandlerV}"
  type_handler_version = "2.0"

  settings = <<SETTINGS
    {
        "fileUris": "${var.fileUris}"
    }
SETTINGS

  protected_settings = <<PROTECTED_SETTINGS
    {
      "commandToExecute": "./${var.fileName}",
      "storageAccountName": "${var.storageAccountName}",
      "storageAccountKey": "${var.storageAccountKey}"
    }
PROTECTED_SETTINGS

  tags {
    Name = "saet"
  }
}

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @gsjaya-19 

Thanks for opening this issue :)

The error message being returned here states that `the specified executable is not a valid application for this OS platform`:

```
azurerm_virtual_machine_extension.saetVmNs: Code="VMExtensionHandlerNonTransientError" Message="Handler 'Microsoft.Azure.Extensions.CustomScript' has reported failure for VM Extension 'saet-ausc-01-ns-vm' with terminal error code '1007' and error message: 'Install failed for plugin (name: Microsoft.Azure.Extensions.CustomScript, version 2.0.6) with exception The specified executable is not a valid application for this OS platform.'"
```

As such it appears that either the command, binary or script being used here isn't valid - as such you may wish to check the command/script being executed.

> We are trying to run a PowerShell script during the spin up windows vms. we are able to run the exact same script using the web portal and when we run it on the web portal it uses version 1.9.2. when I run it in terraform it tries to use version 2.0.6

Taking a look at your Terraform Configuration this is because you're using a Type Handler Version of 2.0:

```
type_handler_version = "2.0"
```

Whilst you could set this to `1.9` (which would use 1.9.x as in the Azure Portal) - however this won't solve the issue since the command provided in the Virtual Machine Extension doesn't appear to be correct. So that we could debug this further - would you be able to show the full command being run here? 

Since this is a question about a Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by gsjaya-19** [comment]
We  were able to get past that error by changing
publisher = "Microsoft.Azure.Extensions"
type = "CustomScript"

to

publisher = "Microsoft.Compute"
type = "CustomScriptExtension"

but now we get the following error
Error: Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine_extension.xxxx: 1 error(s) occurred:

* azurerm_virtual_machine_extension.xxxx: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'xxx-xx-xx-xx'. Error message: \"Invalid handler configuration. Exiting. Error Message: Error converting value \"https://xxxxxxx.blob.core.windows.net/xxxxx/xxxx.ps1\" to type 'System.Collections.Generic.IList`1[System.String]'. Path 'runtimeSettings[0].handlerSettings.publicSettings.fileUris', line 7, position 116.\"."

**Comment by gsjaya-19** [comment]
Hello Tom
that cleared up the last error but this is what i get now
Error: Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine_extension.saetVmDb: 1 error(s) occurred:

* azurerm_virtual_machine_extension.saetVmDb: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'xxx-xxxx-xx-xx-xx'. Error message: \"Finished executing command\"."

**Comment by tombuildsstuff** [comment]
@gsjaya-19 VM Extensions need to return an exit code of `0` to be treated as executed successfully - in the case above the error message indicated the exit code for the script/process wasn't 0. You can see [an example of how to do this here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/vm-joined-to-active-directory/modules/active-directory/3-provision-domain.tf#L9)
