### ISSUE TITLE
Auto-Scale Settings Example is broken

### ISSUE THREAD

**Issue by Workshop2** [terraform-providers/terraform-provider-azurerm#2313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have lots of app services managed by terraform, but we aren't able to handle the scaling rules (has to be done manually). Please implement this feature to complete our terraform migration.

### New or Affected Resource(s)

* azurerm_app_service_plan

### Potential Terraform Configuration

n/a

### References

* https://blogs.msdn.microsoft.com/benjaminperkins/2017/07/26/how-to-configure-auto-scaling-for-an-azure-app-service-with-powershell/

**Comment by tombuildsstuff** [comment]
hi @Workshop2 

Thanks for opening this issue :)

Taking a quick look into this this appears to be using an AutoScale Rule - which is supported in Terraform using [the `azurerm_autoscale_setting` resource](https://www.terraform.io/docs/providers/azurerm/r/autoscale_setting.html). Would you be able to take a look and see if that works for you?

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by Workshop2** [comment]
@tombuildsstuff Hey Tom, are you able to provide an example of it working with App Services? I get errors with the following and I can't figure it out (e.g. "profile.0.recurrence.0.days": required field is not set)

```terraform
resource "azurerm_autoscale_setting" "test" {
  name                = "${var.resource_group_name}-${var.region-prefix["${var.location}"]}-test-scaling"
  target_resource_id  = "${azurerm_app_service_plan.test.id}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"

  profile {
    name = "Week Days"

    capacity {
      default = 10
      minimum = 5
      maximum = 10
    }

    rule {
      metric_trigger {
        metric_name        = "Percentage CPU"
        metric_resource_id = "${azurerm_app_service_plan.test.id}"
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT10M"
        time_aggregation   = "Average"
        operator           = "GreaterThan"
        threshold          = 70
      }

      scale_action {
        direction = "Increase"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT15M"
      }
    }

    rule {
      metric_trigger {
        metric_name        = "Percentage CPU"
        metric_resource_id = "${azurerm_app_service_plan.test.id}"
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT10M"
        time_aggregation   = "Average"
        operator           = "LessThan"
        threshold          = 50
      }

      scale_action {
        direction = "Decrease"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT5M"
      }
    }

    recurrence {
      frequency = "Week"

      schedule {
        timezone = "UTC"
        days     = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
        hours    = [6]
        minutes  = [30]
      }
    }
  }

  notification {
    email {
      send_to_subscription_administrator    = false
      send_to_subscription_co_administrator = false
    }
  }
}
```

**Comment by Workshop2** [comment]
@tombuildsstuff thanks for that, seems to be working. 

Do you mind updating the documentation, as I got the above example from there.

Many thanks for the help

**Comment by tombuildsstuff** [comment]
@Workshop2 thanks for the heads up on the documentation/example being broken - we'll do that as a part of this release :)

**Comment by Workshop2** [comment]
Thanks all 👍
