### ISSUE TITLE
Microsoft.StorageSync/storageSyncServices

### ISSUE THREAD

**Issue by midacts** [terraform-providers/terraform-provider-azurerm#2315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for Microsoft.StorageSync/storageSyncServices resources

### New or Affected Resource(s)

* azurerm_storage_sync

### References

https://docs.microsoft.com/en-us/azure/storage/files/storage-sync-files-deployment-guide

**Comment by sean-nixon** [comment]
This went GA a while ago so I think the `preview` label should be removed. It would be great if Terraform supported this service with resources for `azurerm_storage_sync_service`, `azurerm_storage_sync_sync_group`, and `azurerm_storage_sync_cloud_endpoint`

**Comment by yupwei68** [comment]
I'm working on this.

**Comment by paulablasco** [comment]
Hello, is this available already? thanks!

**Comment by yupwei68** [comment]
hi @paulablasco , sorry that it's blocked by one issue in microsoft service team https://github.com/Azure/azure-rest-api-specs/issues/8348
