### ISSUE TITLE
apn certificate credentials for azurerm_notification_hub resource

### ISSUE THREAD

**Issue by kgarlikowski** [terraform-providers/terraform-provider-azurerm#2316]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `azurerm_notification_hub` allows defining token based APNS credentials only. Azure also supports certificate credentials (AFAIK as well as Azure SDK fo Go). It would be great to be able to define those in `azurerm_notification_hub` resource as creating ARM template for defining just APNS credentials seems close to impossible and the only fallback strategy seems to be to define whole notification hub via ARM template.

### New or Affected Resource(s)

* azurerm_notification_hub

### Potential Terraform Configuration

```hcl
resource "azurerm_notification_hub" "hub" {
  name                = "${var.prefix}-notification-hub"
  namespace_name      = "${azurerm_notification_hub_namespace.hub.name}"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.location}"

  apns_credential {
    certificate = "${base64encode(data.azurerm_key_vault_secret.apns_certificate.value)}"
    certificate_key = "${data.azurerm_key_vault_secret.apns_certificate_key.value}"
   apnsEndpoint = "gateway.push.apple.com"
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @kgarlikowski 

Thanks for opening this issue :)

My understanding (I may be wrong 😄) is that Certificate Authentication for APNS is deprecated in favour of using Tokens for Authentication. Given this is deprecated (and thus presumably will be removed from APNS/Azure at some point in the not-too-distant future) - the `azurerm_notification_hub` resource intentionally omitted support for using Certificate Authentication (even though it's supported in the Go SDK / API). Out of interest is there a reason why you're unable to use the Token authentication instead?

Thanks!

**Comment by kgarlikowski** [comment]
Hi @tombuildsstuff,

thanks for a quick feedback and pointing the status of Certificate Authentication for APNS in Azure. I totally understand the decision.

The reason to use it was the dependency on a already existing mobile app, but seems that it's much safer to take it back to mobile team and switch over as you kindly suggested.

Thanks!
