### ISSUE TITLE
azurerm_sql_database: edition options

### ISSUE THREAD

**Issue by midacts** [terraform-providers/terraform-provider-azurerm#2317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform:    0.11.10
azurerm:      0.1.18

### Affected Resource(s)

* azurerm_sql_database

### Terraform Configuration Files

```hcl
resource "azurerm_sql_database" "myserver-master" {
  name                = "master"
  resource_group_name = "${azurerm_resource_group.myrg.name}"
  location            = "${azurerm_resource_group.myrg.location}"
  server_name         = "${azurerm_sql_server.myserver.name}"
  edition             = "System"
  collation           = "SQL_Latin1_General_CP1_CI_AS"
  max_size_bytes      = 32212254720
}
```

### Debug Output

 ~ azurerm_sql_database.myserver-master
     __edition:                      "System" => "Standard"__

### Expected Behavior

Import/create/update the database

### Actual Behavior

Error: expected edition to be one of [Basic Standard Premium DataWarehouse], got System

### Important Factoids

This is the `master` database.

**Comment by tombuildsstuff** [comment]
hey @midacts 

Thanks for opening this issue / apologies for the delayed response here!

Taking a look through it appears [this is now supported](https://www.terraform.io/docs/providers/azurerm/r/sql_database.html#edition) and as such I'm going to close this issue for the moment.

Thanks!
