### ISSUE TITLE
azurerm_monitor_action_group data source

### ISSUE THREAD

**Issue by andyredhead-adv365** [terraform-providers/terraform-provider-azurerm#2323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be really handy to have a data source that could locate an existing azurerm_monitor_action_group

Basically, we'd like to create a single (webhook) actiongroup per subscription which is defined in its own config file and has state stored in its own state file then use a data source to reference that action group instance in metric alert instances, each of which are declared in config files related to the resources they are monitoring (and has their related state in different state files).

At present this is not possible because we cannot get a reference to the action group id.

### New or Affected Resource(s)

azurerm_monitor_action_group data source
### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
@JunyiYi would you be able to take a look into this? :)

**Comment by JunyiYi** [comment]
Sure @tombuildsstuff , I will attach a priority to it.
