### ISSUE TITLE
azurerm_virtual_network resource guid attribute

### ISSUE THREAD

**Issue by steve-hawkins** [terraform-providers/terraform-provider-azurerm#2325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be good to have the resourceGuid as an attribute of the Virtual Network resource

This is to support the Azure App Service Virtual Network Integration (that is currently in Preview) which requires the site_config virtual_network_name value to consist of the Virtual Network resourceGuid and the name of the subnet separated by an underscore like follows:-

```
azurerm_app_service.my_app_service
      site_config.0.virtual_network_name: "911e37e1-7283-452c-bec4-f24c5e7e2aaf_my_subnet"
```

### New or Affected Resource(s)

* azurerm_virtual_network

### Potential Terraform Configuration

```hcl
data "azurerm_virtual_network" "example" {
  name                = "virtual_network"
  resource_group_name = "${azurerm_resource_group.example.name}"
}

output "virtual_network_guid" {
  value = "${data.azurerm_virtual_network.example.guid}"
}
```

**Comment by tombuildsstuff** [comment]
hey @steve-hawkins 

Thanks for opening this issue :)

Whilst we've tagged this as a feature request - since other resources in Azure reference each other using a Resource ID rather than a GUID, I've also reached out to the Service Team to see if there's plans to update this to use a Resource ID in the future.

Thanks!

**Comment by steve-hawkins** [comment]
hi @tombuildsstuff thanks for looking into this and I agree, if this could be switched to resource ID it would make a lot more sense

**Comment by jlorich** [comment]
I'd like to note that the App Service Preview VNet integration does not appear to work as intended without this feature.  When you look at a properly configured resource the App Service VNet Name needs to be:

"vnetResourceGuid_subnetName", which is not currently available.

**Comment by tombuildsstuff** [comment]
👋 

Jotting some notes down whilst taking a look into this it appears this is available in the SDK as `props.ResourceGUID` - as such it should be possible to expose this in both the Data Source and the Resource for the Virtual Networks. At the same time it'd be good to add a snippet to the documentation for App Service explaining the intended format for the Virtual Network link here (`resourceGuid_subnetName`).

**Comment by dreasan** [comment]
> At the same time it'd be good to add a snippet to the documentation for App Service explaining the intended format for the Virtual Network link here (`resourceGuid_subnetName`).

Would be much appreciated. While on it, the Function App resource would also need an update or added example.

**Comment by sonata82** [comment]
I don't see the resourceGuid being mapped in [data_source_virtual_network.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/data_source_virtual_network.go )?

**Comment by wtassi** [comment]
Hello, guys, did you have any outcome on this issue?
Because I'm having the exact same problem. Since microsoft promoted vnet integration it is no longer a preview. Thanks.

**Comment by akonrath** [comment]
I am interested in working on this issue. I have this working on a local branch for both the vnet data and resource. I'll do further testing, update the docs for the new attribute, and submit a PR.

**Comment by kokarn** [comment]
Great work! Looking forward to a proper vnet integration with Terraform :)
