### ISSUE TITLE
New Resource: App Service Backups -> Storage Account

### ISSUE THREAD

**Issue by MVP072000** [terraform-providers/terraform-provider-azurerm#2329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can you please enable configuration of scheduled web app backup to storage account, including database (for wordpress sites)?

**Comment by tombuildsstuff** [comment]
👋 

Support for this is available within the `azurerm_app_service` resource [using the `backup` block](https://www.terraform.io/docs/providers/azurerm/r/app_service.html) which can be set at the top level f the resource - and as such I'm going to close this issue for the moment :)

Thanks!
