### ISSUE TITLE
Getting a Service Principal not found error even with depends_on

### ISSUE THREAD

**Issue by btai24** [terraform-providers/terraform-provider-azurerm#2332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.10
+ provider.azurerm v1.18.0

### Affected Resource(s)

* module.aks_cluster.azurerm_kubernetes_cluster.aks_cluster: 1 error(s) occurred:

* azurerm_kubernetes_cluster.aks_cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ServicePrincipalNotFound" Message="Service principal clientID: 4063cb12-6b91-4cf2-8bf0-5077357ea040 not found in Active Directory tenant bdac6543-2671-43d9-9ffe-8b61e08ab18a, Please see https://aka.ms/acs-sp-help for more details."

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks_cluster" {
  name       = "${local.name}"
  location   = "${var.region}"
  dns_prefix = "${local.name}"

  kubernetes_version  = "${var.kubernetes_version}"
  resource_group_name = "${azurerm_resource_group.aks_resource_group.name}"
  enable_rbac         = "${var.enable_rbac}"

  linux_profile {
    admin_username = "soxhub"

    ssh_key {
      key_data = "${var.ssh_public_key}"
    }
  }

  agent_pool_profile {
    count = "${var.node_count}"

    name            = "agentpool"
    vm_size         = "${var.vm_size}"
    os_disk_size_gb = "${var.os_disk_size}"
    os_type         = "Linux"
    vnet_subnet_id  = "${azurerm_subnet.private.id}"
  }

  service_principal {
    client_id     = "${azurerm_azuread_service_principal.service_principal.application_id}"
    client_secret = "${random_string.service_principal_password.result}"
  }

  addon_profile {
    http_application_routing {
      enabled = true
    }
  }

  network_profile {
    network_plugin = "azure"
  }

  depends_on = [
    "azurerm_azuread_service_principal.service_principal",
  ]

  tags {
    environment = "${var.environment}"
    name        = "${local.name}"
  }
}

resource "azurerm_azuread_service_principal" "service_principal" {
  application_id = "${azurerm_azuread_application.service_principal_app.application_id}"
}
```

### Expected Behavior

Adding a dependency on a service principal with a `depends_on` should wait for the service principal to be created to continue. Instead the AKS cluster tries to reference a "created" service principal that is not actually created yet. This is probably an "eventually consistent" issue where the azure api returns that the service principal is created while it is still in the process.

### Steps to Reproduce

1. Create an AKS resource & Service Principal resource in terraform
2. Add a depends_on in the AKS resource to depend on the service principal resource
3. Run `terraform apply`
4. Notice the (intermittent) error
5. Rerun `terraform apply`
6. Succeeds on second run

**Comment by tombuildsstuff** [comment]
hi @btai24 

Thanks for opening this issue :)

This bug has previously been reported in #1635 which rather than having multiple issues open tracking the same thing - I'm going to close this issue in favour of that one - please subscribe to that one for updates.

Thanks!
