### ISSUE TITLE
New Resource: Dev Test Schedules

### ISSUE THREAD

**Issue by guitarrapc** [terraform-providers/terraform-provider-azurerm#2334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add functionality to configure Auto-shutdown for azurerm_virtual_machine. This functionality is not yet supported with terraform azurerm provider.

### New or Affected Resource(s)

* azurerm_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine_schedule" "example" {
  resource_group_name = "${azurerm_resource_group.example.name}"
  virtual_machine_id  = "${azurerm_virtual_machine.example.id}"
  enabled             = true
  scheduled_shutdown  = "20:00:00"
  timezone            = "arizona"
  webhook_url         = "https://example.io/webhook"
  email_address       = "exmaple@example.io"
}

```

### References

I was posted question about to resolve this and creating feature request as suggested.

* #2169 

reference comment.

> Taking a look into how the Azure Portal achieves this - it appears it configures a Schedule inside of DevTest Labs (even for Virtual Machines not provisioned using/attached with DevTest Labs) - since the "Auto Shutdown" page for a Virtual Machine makes a request out to this URL:

> https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/acctestRG-727834829814149628/providers/Microsoft.DevTestLab/schedules/shutdown-computevm-acctestvm?api-version=2018-10-15-preview

> As such, I believe this would require a DevTest Labs Schedule to be configured to be used (it may also be possible through Azure Automation, but I'm unsure). We don't support DevTest Labs Schedules natively in Terraform at this time - if you'd like to see support for these please open an issue about it and we'll take a look

**Comment by tombuildsstuff** [comment]
hi @guitarrapc 

Thanks for opening this issue :)

As I mentioned in #2169, there's no native support for this through the Virtual Machine API's / resources - instead support for this would be possible by adding support for Dev Test Schedules - as such I've updated the title to reflect this.

Thanks!

**Comment by guitarrapc** [comment]
Off course it's fine!

**Comment by pedrofurtado** [comment]
Configure auto-shutdown of azure VM's will be great. Today, we need to configure this manually. 👍

**Comment by pc-dok** [comment]
is there any news, can we configure that now direct with terraform or is that not possible at this time? would be great when yes, if there is an example in github or so. i would like it

**Comment by maniSbindra** [comment]
I will work on this. Just to verify, seems like the dev_test_lab_schedule just needs a resource  and not a datasource (similar to vm extensions)

**Comment by tombuildsstuff** [comment]
@maniSbindra awesome, thanks - yeah this should only need a Resource not a Data Source 👍

**Comment by wtassi** [comment]
Hello, this functionality will be of valuable help, since for production machines we usually have to disable the auto-shutdown and in Dev machines we can put Enabled to reduce costs.
Looking forward to this functionality :)

**Comment by diegoitaliait** [comment]
I would like to ask if there is news about a release date?

Having this feature, would save my poor account that is eaten every time by the machines left active
