### ISSUE TITLE
azurerm_virtual_machine disk properties trying to overwrite managed_disk properties

### ISSUE THREAD

**Issue by MMollyy** [terraform-providers/terraform-provider-azurerm#2336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform: 0.11.7
azurerm: 1.18.0

### Affected Resource(s)

azurerm_virtual_machine
azurerm_managed_disk

```Virtual machine:
resource "azurerm_virtual_machine" "-app02" {
  resource_group_name = "${azurerm_resource_group.rg.name}"
  name                = "-app02"

  os_profile = {
    admin_username = "user"
    admin_password = "${data.vault_generic_secret.default_azure_administrator.data["password"]}"
    computer_name  = "-app02"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data1.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data1.disk_size_gb}"
    create_option   = "Attach"
    lun             = "0"
    name            = "${azurerm_managed_disk.-app02-data1.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data2.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data2.disk_size_gb}"
    create_option   = "Attach"
    lun             = "1"
    name            = "${azurerm_managed_disk.-app02-data2.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data3.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data3.disk_size_gb}"
    create_option   = "Attach"
    lun             = "2"
    name            = "${azurerm_managed_disk.-app02-data3.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data4.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data4.disk_size_gb}"
    create_option   = "Attach"
    lun             = "3"
    name            = "${azurerm_managed_disk.-app02-data4.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data5.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data5.disk_size_gb}"
    create_option   = "Attach"
    lun             = "4"
    name            = "${azurerm_managed_disk.-app02-data5.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data6.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data6.disk_size_gb}"
    create_option   = "Attach"
    lun             = "5"
    name            = "${azurerm_managed_disk.-app02-data6.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data7.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data7.disk_size_gb}"
    create_option   = "Attach"
    lun             = "6"
    name            = "${azurerm_managed_disk.-app02-data7.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data8.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data8.disk_size_gb}"
    create_option   = "Attach"
    lun             = "7"
    name            = "${azurerm_managed_disk.-app02-data8.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data11.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data11.disk_size_gb}"
    create_option   = "Attach"
    lun             = "10"
    name            = "${azurerm_managed_disk.-app02-data11.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data12.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data12.disk_size_gb}"
    create_option   = "Attach"
    lun             = "11"
    name            = "${azurerm_managed_disk.-app02-data12.name}"
  }

  storage_data_disk = {
    managed_disk_id = "${azurerm_managed_disk.-app02-data9.id}"
    disk_size_gb    = "${azurerm_managed_disk.-app02-data9.disk_size_gb}"
    create_option   = "Attach"
    lun             = "8"
    name            = "${azurerm_managed_disk.-app02-data9.name}"
  }

  os_profile_linux_config = {
    disable_password_authentication = true

    ssh_keys = {
      key_data = "${var.bootstrap-key-content}"
      path     = "/home/sbp_root/.ssh/authorized_keys"
    }
  }

  storage_image_reference = {
    sku       = "12-SP1"
    publisher = "SUSE"
    version   = "latest"
    offer     = "SLES-SAP"
  }

  network_interface_ids = ["${azurerm_network_interface.-app02-nic1.id}"]
  location              = "${var.azure-region}"

  storage_os_disk = {
    managed_disk_type = "Standard_LRS"
    create_option     = "FromImage"
    name              = "-app02-disk"
  }

  delete_os_disk_on_termination = true
  vm_size                       = "Standard_DS12_v2"

  lifecycle = {
    ignore_changes = ["storage_image_reference"]
  }
}

Datadisks:
resource "azurerm_managed_disk" "-data9" {
  resource_group_name  = "${azurerm_resource_group.rg.name}"
  disk_size_gb         = "4095"
  name                 = "-data9"
  storage_account_type = "Standard_LRS"
  location             = "${var.azure-region}"
  create_option        = "Empty"
}

resource "azurerm_managed_disk" "-data11" {
  resource_group_name  = "${azurerm_resource_group.rg.name}"
  disk_size_gb         = "4095"
  name                 = "-data11"
  storage_account_type = "Premium_LRS"
  location             = "${var.azure-region}"
  create_option        = "Empty"
}

resource "azurerm_managed_disk" "-data12" {
  resource_group_name  = "${azurerm_resource_group.rg.name}"
  disk_size_gb         = "32"
  name                 = "-data12"
  storage_account_type = "Premium_LRS"
  location             = "${var.azure-region}"
  create_option        = "Empty"
}
```
Scenario sketch: 
Considering above configuration, and not having the option of changing these inline disks to disk_attachment resources: We make our disk changes by commenting any of these inline disks, applying it, making disk changes, applying it, and uncommenting the disk again.
Why can't we change these inline disks to disk_attachment resources?
Because these are production servers, and it's not possible to mix-match between inline disks and the attachment resource.

### Debug Output

https://gist.github.com/MarcoMol/7d326c57baaa2c699d12cc608cb3b4b4

### Expected Behavior

It should iterate through the list only for the number of disks that are found, without 'remembering' the configuration of a disk. That's what the managed_disk resource is for.

### Actual Behavior

The way of working introduces an issue which can be seen in the Gist.
As terraform iterates through the inline disks, it discoveres that there is a disk less in the list. So it changes from 11 to 10. However when the disk being detached is anywhere from the first to the second last, it seems to want to overwrite the configuration of the disk:
From the gist: Datadisk 11 gets removed as such the list gets smaller and the following disks move up. datadisk12 gets the spot where datadisk 11 used to be. And datadisk 9 gets the spot where datadisk 12 used to be.
Resulting in an error that seems to think that the previous storage_data_disk.10 (datadisk 12) is of the type Premium, thus trying to be overwritten with the type of the new storage_data_disk.10 (datadisk 9)which is Standard. -> It's not possible to make type changes to disks that are attached.

### Steps to Reproduce

1. Create a VM with inline disks (2+)
2. Point each inline disks to an azurerm_managed_disks
disk1 - premium
disk2 - premium
disk3 - standard
Apply this code
3. Uncomment or remove disk2 inline from the VM, but leave the managed_disk existing, terraform apply

It should crash at this point with the error reported.

### Important Factoids
Nothing in particular, except that our machines are in production and it is impossible to switch all of the disks to azurerm_disk_attachment resources. 

Also I can test with a newer terraform version, but I don't think that will solve the logic in the code which is already in there.

Commenting/removing disk2 and disk3 at the same time, and then re-arranging them works.
But that's not an option on a server with 10+ disks, of which most can't be detached while it's running.
Which then basically returns to a lousy corporate process needing to be started, where a request is made to detach/attach disks manually in the portal. Without the code being leading, and post-work has to be done to get the code reflecting the environment.

Ofcourse the same error applies when the order of disks would be, because terraform would try to overwrite a standard disk type with a premium disk type -> which is not allowed so long as the disk is attached:
disk1 - standard
disk2 - standard
disk3 - premium

**Comment by MMollyy** [comment]
Hello,

any feedback on this?

**Comment by tombuildsstuff** [comment]
hi @MMollyy 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward. Support for this functionality on those resources is being tracked in #7193 - would you mind subscribing to that issue for updates?

Thanks!
