### ISSUE TITLE
authenticating via a Service Principal not recognized by terraform

### ISSUE THREAD

**Issue by whiggs** [terraform-providers/terraform-provider-azurerm#2341]
I have a service account that I created in azure according to [this](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html) document.  However, after I successfully login to the service account via the azure cli and attempt to run "terraform plan", I get the below error:
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error refreshing state: 1 error(s) occurred:

* provider.azurerm: Error building AzureRM Client: No (unexpired) Authorization Tokens were found - please re-authenticate using `az login`.
```
The very next command I ran after the failed "terraform plan" command was "az vm list-sizes --location westus", which successfully ran to completion, so I know that it is not an issue with authentication, especially considering I got the error just seconds after authenticating via azure cli.  It would seem that the feature to authenticate using a Service Principal is broken in the azurerm provider.  

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

# terraform -v
Terraform v0.11.10
+ provider.azurerm v1.19.0

### Affected Resource(s)

Not sure how to answer this.  Terraform is unable to authenticate with azure when there is already clearly a connection, so that is the affected resource.

* azurerm_XXXXX

### Terraform Configuration Files

Not sure how this will help, considering terraform can't even get this far into the process, but here it is anyway.

```hcl
provider "azurerm" { }

data "azurerm_resource_group" "rgroup_one" {
	name = "Box_resources"
}
data "azurerm_virtual_network" "vnet_south" {
    name = "${var.south_vnet_name}"
    resource_group_name = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "azsubnet_south" {
    name = "${var.south_subnet_name}"
    virtual_network_name = "${var.south_vnet_name}"
    resource_group_name = "${var.vnet_resource_group_name}"
}
resource "azurerm_public_ip" "me" {
	name = "teehee"
	location = "East US"
	resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    public_ip_address_allocation = "static"
}
resource "azurerm_network_interface" "aznic_one" {
    name = "${var.nic_name}01-nic"
    resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    location = "${var.location_one}"
    ip_configuration = {
        name = "${var.ip_config}01"
        subnet_id = "${data.azurerm_subnet.azsubnet_south.id}"
        private_ip_address_allocation = "dynamic"
		public_ip_address_id = "${azurerm_public_ip.me.id}"
    }
    provisioner "local-exec" {
        command = "az network nic ip-config update -n ${var.ip_config}01 --nic-name ${var.nic_name}01-nic -g ${var.rgroup_name_one} --private-ip-address ${azurerm_network_interface.aznic_one.private_ip_address}"
    }
}
resource "azurerm_virtual_machine" "azvm_one" {
    name = "${var.vm_one}"
    location = "${var.location_one}"
    resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    network_interface_ids = ["${azurerm_network_interface.aznic_one.id}"]
    vm_size = "${var.vm_size}"
    delete_os_disk_on_termination = true
    license_type = "Windows_Server"
    delete_data_disks_on_termination = true
    primary_network_interface_id = "${azurerm_network_interface.aznic_one.id}"
    storage_image_reference {
        publisher = "${var.publisher}"
        offer = "${var.offer}"
        sku = "${var.sku}"
        version = "${var.version}"
    }
    storage_os_disk {
        name = "${var.disk_name}"
        caching = "ReadWrite"
        create_option = "FromImage"
        managed_disk_type = "Standard_LRS"
    }
    storage_data_disk {
        name = "${var.data_disk_name}"
        caching = "ReadWrite"
        create_option = "Empty"
        lun = 0
        disk_size_gb = 250
        managed_disk_type = "Standard_LRS"
    }
    os_profile {
        computer_name = "${var.vm_one}"
        admin_username  = "${var.admin_username}"
        admin_password = "${var.admin_password}"
    }
     os_profile_windows_config {
        provision_vm_agent        = true
        enable_automatic_upgrades = true

        additional_unattend_config {
            pass = "oobeSystem"
            component    = "Microsoft-Windows-Shell-Setup"
            setting_name = "AutoLogon"
            content      = "<AutoLogon><Password><Value>${var.admin_password}</Value></Password><Enabled>true</Enabled><LogonCount>1</LogonCount><Username>${var.admin_username}</Username></AutoLogon>"
        }
        additional_unattend_config {
            pass = "oobeSystem"
            component    = "Microsoft-Windows-Shell-Setup"
            setting_name = "FirstLogonCommands"
            content      = "<FirstLogonCommands><SynchronousCommand><CommandLine>${var.winrm_command}</CommandLine><Description>Enable winrm</Description><Order>10</Order></SynchronousCommand></FirstLogonCommands>"
        }
    }
}
output "ip" {
    value = "${azurerm_network_interface.aznic_one.private_ip_address}"
}
```

### Debug Output

https://gist.githubusercontent.com/whiggs/b1a4a4bc7d57514ef85b568b4ffc1d07/raw/ac35ad7e6154b0be12b786f61f06d0e20c6d460c/terraformdebug.txt

### Expected Behavior

For terraform to authenticate and build the configured infrastructure.

### Actual Behavior

It fails to authenticate.  Supposedly due to an expired token, but that is crap for answer.

### Steps to Reproduce

1. Create a service principal and authenticate to azure using the service principal as described [here](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html)
2. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @whiggs 

Thanks for opening this issue :)

This issue has previously been reported in #502 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #502 - please subscribe to that issue for updates.

One thing of note - in this instance you're seeing the error message from the Azure CLI since that's being used for authentication, rather than a Service Principal, which is either configured as Environment Variables (where it's used rather than the Azure CLI auth) or inline in the Provider block:

```
provider "azurerm" {
  client_id = "..."
  client_secret = "..."
  subscription_id = "..."
  tenant_id = "..."
}
```

Thanks!
