### ISSUE TITLE
Terraform Authentication with MSI

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#2352]
Would it be possible for Terraform to support Managed Service Identity for one of its authentication options?  

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

It is beginning to be to much overhead to managed service principals in +10 environments (must be use isolated credentials).    It would be terrific if we could run terraform on a VM in each environment and use MSI to authenticate, instead of SP. 

@JunyiYi | @tombuildsstuff

**Comment by tombuildsstuff** [comment]
hi @rohrerb 

Thanks for opening this issue :)

Using MSI for authentication is supported by [the AzureRM Provider today](https://www.terraform.io/docs/providers/azurerm/authenticating_via_msi.html) and will be coming to [the AzureRM Backend in a future update](https://github.com/hashicorp/terraform/issues/18425) - please subscribe to that issue for updates.

Thanks!

**Comment by rohrerb** [comment]
@tombuildsstuff  - Can you provide a link to the issue?

**Comment by tombuildsstuff** [comment]
@rohrerb it's linked above ([here](https://github.com/hashicorp/terraform/issues/18425)) :)

**Comment by rohrerb** [comment]
I need more coffee...  Thanks Tom.
