### ISSUE TITLE
AzureRM: Key Vault Certificate Thumbprint output not accepted

### ISSUE THREAD

**Issue by iharrington** [terraform-providers/terraform-provider-azurerm#2361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.11.10`

### Affected Resource(s)

* azurerm_key_vault_certificate

### Terraform Configuration Files

```hcl
I'm using test code from your docs "Example Usage (Generating a new certificate)"
```

### Expected Behavior

thumbprint - The X509 Thumbprint of the Key Vault Certificate returned as hex string.

Should be available attribute 

### Actual Behavior

'Unresolved resource' via HCL plugin.

### Steps to Reproduce

1. Copy code from docs
2. Create output block (example below)
```
output "thumbprint" {
  value = "${azurerm_key_vault_certificate.test.thumbprint}"
}
```
### Important Factoids

I'm using IntelliJ IDEA (version 2018.2.6 CE) w/ HashiCorp Terraform /HCL Languag Support (Version: 0.6.12)

### References

[Terraform docs](https://www.terraform.io/docs/providers/azurerm/r/key_vault_certificate.html#attributes-reference)
[Closed issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1851)

* #2361

**Comment by tombuildsstuff** [comment]
hi @iharrington 

Thanks for opening this issue :)

So that we could take a look into this - would it be possible to post which version of the AzureRM Provider you're using? You can find this out by running `terraform version`.

Thanks!

**Comment by iharrington** [comment]
@tombuildsstuff This is in the .terraform plugin folder `terraform-provider-azurerm_v1.19.0_x4` it should be the latest.

**Comment by iharrington** [comment]
@tombuildsstuff Sorry to bug you, is anyone looking into this?
