### ISSUE TITLE
Docs: Storage Account doesn't accept cidr

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#2367]
There's also an error in [the documentation](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#ip_rules) for this property, which is that Azure does not accept CIDR format for it.

_Originally posted by @carlin-q-scott in https://github.com/terraform-providers/terraform-provider-azurerm/issues/828#issuecomment-440536279_

**Comment by carlin-q-scott** [comment]
I found out while setting this option through the Azure Portal that they allow CIDR format but require the netmask be at most a 30. So 192.168.1.0/30 is allowed but not 192.168.1.2/32. Several other APIs they provide require CIDR format and allow /32, but not this one.

**Comment by neil-yechenwei** [comment]
Hopes this [PR ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7660)would be helpful.
