### ISSUE TITLE
Event hub capture returns 400

### ISSUE THREAD

**Issue by jamie3** [terraform-providers/terraform-provider-azurerm#2373]
I have a terraform capture applied to a storage account. It is returning 400 when trying to associate the capture with the storage account. No description as to why it fails. Any help would be appreciated.

```
# Module
resource "azurerm_storage_account" "storage_account" {
  name                     = "${var.storage_account_name}"
  resource_group_name      = "${var.resource_group_name}"
  location                 = "${var.resource_group_location}"
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  access_tier              = "${var.access_tier}"
  account_replication_type = "RAGRS"
  enable_blob_encryption   = true
  enable_file_encryption   = true
  enable_https_traffic_only = true
  
  tags {
    environment = "${var.environment}"
    implementor = "${var.implementor}"
    owner = "${var.owner}"
    application = "${var.resource_group_name}"
    tier = "1"
  }

  network_rules {
    virtual_network_subnet_ids = ["${data.azurerm_subnet.appl1.id}", "${data.azurerm_subnet.appl2.id}", "${data.azurerm_subnet.appl3.id}", "${data.azurerm_subnet.transit.id}", "${data.azurerm_subnet.mgmtsubnet.id}", "${data.azurerm_subnet.private.id}", "${data.azurerm_subnet.servicesendpoint.id}", "${data.azurerm_subnet.gatewaysubnet.id}"]
  }
}

# Capture storage
module "storage_account_capture" {
  source = "../../../../modules/storageaccount-tier1" 

  environment = "${var.environment}"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
  resource_group_location = "${azurerm_resource_group.resource_group.location}"
  storage_account_name = "${local.storage_account_name_capture}"

  sharedservices_vnet_name = "${var.sharedservices_vnet_name}"
  sharedservices_vnet_rg_name = "${var.sharedservices_vnet_rg_name}"

  access_tier = "Cool"

  owner = "${var.resource_group_tags["owner"]}"
  implementor = "${var.resource_group_tags["implementor"]}"
}

resource "azurerm_eventhub" "eventhub_resource"{
    name = "${var.eventhub_name}"
    namespace_name = "${azurerm_eventhub_namespace.eventhub_namespace.name}"
    resource_group_name = "${azurerm_resource_group.resource_group.name}"
    partition_count  = 2
    message_retention = 7
    capture_description {
        enabled = "true"
        encoding = "AVro"
        destination {
            name = "EventHubArchive.AzureBlockBlob"
            blob_container_name = "${var.eventhub_name}"
            storage_account_id = "${local.storage_account_name_capture}"
            archive_name_format = "{Namespace}/{EventHub}/{PartitionId}/{Year}/{Month}/{Day}/{Hour}/{Minute}/{Second}"
        }
    }

    depends_on = ["module.storage_account_capture"]
}
```

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.eventhub.azurerm_eventhub.eventhub_resource
      capture_description.#:                                   "0" => "1"
      capture_description.0.destination.#:                     "0" => "1"
      capture_description.0.destination.0.archive_name_format: "" => "{Namespace}/{EventHub}/{PartitionId}/{Year}/{Month}/{Day}/{Hour}/{Minute}/{Second}"
      capture_description.0.destination.0.blob_container_name: "" => "siemeventhub"
      capture_description.0.destination.0.name:                "" => "EventHubArchive.AzureBlockBlob"
      capture_description.0.destination.0.storage_account_id:  "" => "wjeventhubdevcapture"
      capture_description.0.enabled:                           "" => "true"
      capture_description.0.encoding:                          "" => "AVro"
      capture_description.0.interval_in_seconds:               "" => "300"
      capture_description.0.size_limit_in_bytes:               "" => "314572800"

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: wjeventhub.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "wjeventhub.tfplan"

{ DEV } feature/eventhub-capture » terraform apply wjeventhub.tfplan                                               /c/dev/code/SharedServices/CloudOperations/Security/wjeventhub/DEV
module.eventhub.azurerm_eventhub.eventhub_resource: Modifying... (ID: /subscriptions/69c88e31-4843-45cf-baee-...s/wjeventhubdev/eventhubs/siemeventhub)
  capture_description.#:                                   "0" => "1"
  capture_description.0.destination.#:                     "0" => "1"
  capture_description.0.destination.0.archive_name_format: "" => "{Namespace}/{EventHub}/{PartitionId}/{Year}/{Month}/{Day}/{Hour}/{Minute}/{Second}"
  capture_description.0.destination.0.blob_container_name: "" => "siemeventhub"
  capture_description.0.destination.0.name:                "" => "EventHubArchive.AzureBlockBlob"
  capture_description.0.destination.0.storage_account_id:  "" => "wjeventhubdevcapture"
  capture_description.0.enabled:                           "" => "true"
  capture_description.0.encoding:                          "" => "AVro"
  capture_description.0.interval_in_seconds:               "" => "300"
  capture_description.0.size_limit_in_bytes:               "" => "314572800"

Error: Error applying plan:

1 error(s) occurred:

* module.eventhub.azurerm_eventhub.eventhub_resource: 1 error(s) occurred:

* azurerm_eventhub.eventhub_resource: eventhub.EventHubsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="SubCode=40000. StorageAccountResourceId. TrackingId:e65baeb2-5da5-4e80-880f-eff0f4790b7d_M10CH3_M10CH3_G6, SystemTracker:wjeventhubdev.servicebus.windows.net:siemeventhub, Timestamp:11/21/2018 10:06:27 PM CorrelationId: 71d0dc90-e224-49f2-896e-2bb489e4acae"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by tombuildsstuff** [comment]
hi @jamie3 

Thanks for opening this issue :)

Taking a quick look into this the `storage_account_id` field needs to be a Resource ID, but is being set as the name of the Storage Account (which is why an error about the Storage Account Resource ID is being returned). Whilst I'm going to open a PR to add validation to ensure this is a Resource ID - in the interim you should be able to update this field value to be the Resource ID (e.g. `azurerm_eventhub.{name}.id`) which should allow this to provision.

Thanks!

**Comment by jamie3** [comment]
Thanks Tom!
