### ISSUE TITLE
Missing Acceptance Test Sweepers

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#238]
Taking a look through an acceptance test run against an empty Azure subscription - it appears we could do with adding Sweepers to the following resources:

- [x] CosmosDB Accounts #306 
- [x] ~Load Balancer~ no longer needed
- [x] Network Interface #679
- [x] Resource Group #296 <-- needs a Subscription-specific issue fixed before merging
- [x] ~Search Services~ no longer needed
- [x] Service Bus Namespace #279
- [x] SQL Server #289
- [x] ~Storage Account~ no longer needed
- [x] Virtual Network #679

**Comment by stack72** [comment]
Servicebus Namespace - #279

**Comment by tombuildsstuff** [comment]
Looks like Search Services, LB's and Storage Accounts are no longer needed, the rest will be covered in #679. Closing this for the moment.
