### ISSUE TITLE
Add VpnGw*AZ SKU to the Virtual Network Gateway

### ISSUE THREAD

**Issue by nmkleiberg** [terraform-providers/terraform-provider-azurerm#2383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment it is not possible to use the VpnGw1AZ option. This is needed for an customer, can this be added to the default configuration?

### New or Affected Resource(s)

* azurerm_virtual_network_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network_gateway" "VNGTest" {
  name                      = "VirtualNetworkGateway"
  location                  = "${var.resource_location}"
  resource_group_name       = "${var.resource_group_name}"
  tags                      = "${var.tags}"

  type                      = "Vpn"
  vpn_type                  = "RouteBased"

  active_active             = true
  enable_bgp                = false
  sku                       = "VpnGw1AZ"

  ip_configuration {
    name                          = "VirtualGatewayIP01"
    public_ip_address_id          = "${azurerm_public_ip.PublicIpVpn.id}"
    subnet_id                     = "****"
  }
```

### References

* #0000

**Comment by joranm** [comment]
Should be great if this new additional SKU can be added!
