### ISSUE TITLE
Add user_agent argument to azurerm provider

### ISSUE THREAD

**Issue by richeney** [terraform-providers/terraform-provider-azurerm#2393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add user_agent attribute into the AzureRM provider.  If set then append value to the UserAgent header value.

The user_agent value in this context is used for adding a generated pid-<guid> to the telemetry. Having an argument in the provider would allow the value to be set within modules, or to set different values dependant on which provider alias is in effect.

### New or Affected Resource(s)

* [provider "AzureRM"](https://www.terraform.io/docs/providers/azurerm/index.html)

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  user_agent = "pid-c8bdea86-f226-11e8-82db-bc838515ccd4"
}
```

### References

The AzureRM provider already appends the value of the AZURE_HTTP_USER_AGENT environment variable to the UserAgent header :

* [Append AZURE_HTTP_USER_AGENT environment variable to UserAgent string](https://github.com/terraform-providers/terraform-provider-azurerm/pull/483)
* [Override User-Agent for Azure partner customer attribution](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2157)

Azure documentation on using GUIDs to attribute customer usage of solutions to the partner's offer and channel:
* <https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution#create-guids>

**Comment by tombuildsstuff** [comment]
hey @richeney 

Thanks for opening this issue :)

Taking a quick look into this, rather than exposing the user-agent string I think it'd be better to support an optional UUID/GUID for `partner_id`, which would allow us to validate that this is a UUID/GUID. What do you think?

Thanks!

**Comment by richeney** [comment]
Hi @tombuildsstuff,

You're welcome! I thought it would be a nice distraction from all that 0.12 nonsense. ;)

The value must be in the form `pid-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` or it won't get picked up and attributed to them.  

It isn't a partner ID as such - we have the MPN ID for that - and the partners may generated multiple GUIDs to represent the various combinations of offer and channel.  The official backend metric name in the Azure health telemetry report is "Publisher Tracking GUID", so perhaps `tracking_guid`?

**Comment by tombuildsstuff** [comment]
@richeney yeah I was thinking we could string format the `pid` bit to make it easier, such that we'd use `fmt.Sprintf("pid-%s", attributionId)` - perhaps `attribution_id` could make more sense?

**Comment by richeney** [comment]
Excuse my basic Go, but how about something close to:

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	var attribution_id string = "pid-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
	var attribution_guid string = strings.TrimPrefix(attribution_id, "pid-")
	attribution_id = fmt.Sprintf("pid-%s", attribution_guid)
	fmt.Println(attribution_id)
}
```

This way we could check that the attribution_guid has a valid format whilst tolerating the presence of a `pid-` prefix?

**Comment by richeney** [comment]
Thanks Tom and Jeffrey! 👍
