### ISSUE TITLE
Changing the taints and node_labels in azurerm_kubernetes_cluster_node_pool should not force replacement

### ISSUE THREAD

**Issue by SebSa** [terraform-providers/terraform-provider-azurerm#24038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

As was [raised some time ago]( https://github.com/hashicorp/terraform-provider-azurerm/issues/9730), the azurerm_kubernetes_cluster_node_pool is forced to be recreated when a taint or a node label is mutated after initial creation.

It was quite rightly closed pending upstream support for mutable node taints and labels.

But now that [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2682) has been merged, and the feature [has apparently been GA](https://github.com/Azure/AKS/issues/1515) for a over a year, can this be revisited?

Changing the taints and node_labels in azurerm_kubernetes_cluster_node_pool should not force replacement of the nodepool.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### References

 https://github.com/hashicorp/terraform-provider-azurerm/issues/9730

https://github.com/Azure/AKS/issues/1515
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2682

https://github.com/Azure/AKS/issues/2934

**Comment by fabio-s-franco** [comment]
In addition to that, I believe there is a bug. If I manually taint through kubectl, plan still tries to recreate the node pool.
So plan does not verify if the taints have been modified, before trying to apply them.
