### ISSUE TITLE
Continuation of incorrectly closed issue #2341

### ISSUE THREAD

**Issue by whiggs** [terraform-providers/terraform-provider-azurerm#2420]
**If you are going to require that we spend the time filling out the absurd amount of information you request of us, please do us the courtesy of looking at the info you demand of us before jumping to conclusions.**  @tombuildsstuff closed an issue I submitted a couple of days ago (#2341) stating that my issue was a duplicate.  I actually took a look at the supposed duplicate issue, and I am appalled to find that my issue is not even **REMOTELY related** to this issue.  Now, I am going to copy and paste the content of the old issue into this one.  I really shouldn't have to tell grown men this, but actually **READ IT THIS TIME.**

I have a service account that I created in azure according to [this](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html) document.  However, after I successfully login to the service account via the azure cli and attempt to run "terraform plan", I get the below error:
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error refreshing state: 1 error(s) occurred:

* provider.azurerm: Error building AzureRM Client: No (unexpired) Authorization Tokens were found - please re-authenticate using `az login`.
```
The very next command I ran after the failed "terraform plan" command was "az vm list-sizes --location westus", which successfully ran to completion, so I know that it is not an issue with authentication, especially considering I got the error just seconds after authenticating via azure cli.  It would seem that the feature to authenticate using a Service Principal is broken in the azurerm provider.  

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

# terraform -v
Terraform v0.11.10
+ provider.azurerm v1.19.0

### Affected Resource(s)

Not sure how to answer this.  Terraform is unable to authenticate with azure when there is already clearly a connection, so that is the affected resource.

* azurerm_XXXXX

### Terraform Configuration Files

Not sure how this will help, considering terraform can't even get this far into the process, but here it is anyway.

```hcl
provider "azurerm" { }

data "azurerm_resource_group" "rgroup_one" {
	name = "Box_resources"
}
data "azurerm_virtual_network" "vnet_south" {
    name = "${var.south_vnet_name}"
    resource_group_name = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "azsubnet_south" {
    name = "${var.south_subnet_name}"
    virtual_network_name = "${var.south_vnet_name}"
    resource_group_name = "${var.vnet_resource_group_name}"
}
resource "azurerm_public_ip" "me" {
	name = "teehee"
	location = "East US"
	resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    public_ip_address_allocation = "static"
}
resource "azurerm_network_interface" "aznic_one" {
    name = "${var.nic_name}01-nic"
    resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    location = "${var.location_one}"
    ip_configuration = {
        name = "${var.ip_config}01"
        subnet_id = "${data.azurerm_subnet.azsubnet_south.id}"
        private_ip_address_allocation = "dynamic"
		public_ip_address_id = "${azurerm_public_ip.me.id}"
    }
    provisioner "local-exec" {
        command = "az network nic ip-config update -n ${var.ip_config}01 --nic-name ${var.nic_name}01-nic -g ${var.rgroup_name_one} --private-ip-address ${azurerm_network_interface.aznic_one.private_ip_address}"
    }
}
resource "azurerm_virtual_machine" "azvm_one" {
    name = "${var.vm_one}"
    location = "${var.location_one}"
    resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    network_interface_ids = ["${azurerm_network_interface.aznic_one.id}"]
    vm_size = "${var.vm_size}"
    delete_os_disk_on_termination = true
    license_type = "Windows_Server"
    delete_data_disks_on_termination = true
    primary_network_interface_id = "${azurerm_network_interface.aznic_one.id}"
    storage_image_reference {
        publisher = "${var.publisher}"
        offer = "${var.offer}"
        sku = "${var.sku}"
        version = "${var.version}"
    }
    storage_os_disk {
        name = "${var.disk_name}"
        caching = "ReadWrite"
        create_option = "FromImage"
        managed_disk_type = "Standard_LRS"
    }
    storage_data_disk {
        name = "${var.data_disk_name}"
        caching = "ReadWrite"
        create_option = "Empty"
        lun = 0
        disk_size_gb = 250
        managed_disk_type = "Standard_LRS"
    }
    os_profile {
        computer_name = "${var.vm_one}"
        admin_username  = "${var.admin_username}"
        admin_password = "${var.admin_password}"
    }
     os_profile_windows_config {
        provision_vm_agent        = true
        enable_automatic_upgrades = true

        additional_unattend_config {
            pass = "oobeSystem"
            component    = "Microsoft-Windows-Shell-Setup"
            setting_name = "AutoLogon"
            content      = "<AutoLogon><Password><Value>${var.admin_password}</Value></Password><Enabled>true</Enabled><LogonCount>1</LogonCount><Username>${var.admin_username}</Username></AutoLogon>"
        }
        additional_unattend_config {
            pass = "oobeSystem"
            component    = "Microsoft-Windows-Shell-Setup"
            setting_name = "FirstLogonCommands"
            content      = "<FirstLogonCommands><SynchronousCommand><CommandLine>${var.winrm_command}</CommandLine><Description>Enable winrm</Description><Order>10</Order></SynchronousCommand></FirstLogonCommands>"
        }
    }
}
output "ip" {
    value = "${azurerm_network_interface.aznic_one.private_ip_address}"
}
```

### Debug Output

https://gist.githubusercontent.com/whiggs/b1a4a4bc7d57514ef85b568b4ffc1d07/raw/ac35ad7e6154b0be12b786f61f06d0e20c6d460c/terraformdebug.txt

### Expected Behavior

For terraform to authenticate and build the configured infrastructure.

### Actual Behavior

It fails to authenticate.  Supposedly due to an expired token, but that is crap for answer.

### Steps to Reproduce

1. Create a service principal and authenticate to azure using the service principal as described [here](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html)
2. `terraform apply`

### References

* #0000

**Comment by haodeon** [comment]
Hi there, from what you have described I think you are using Terraform in an unsupported manner.

You can either use a user account with az login or use a service account with the 5 required values in the terraform configuration.

It is not supported to login through the azure cli with a service account via az login --service-principal.

**Comment by tombuildsstuff** [comment]
Hi @whiggs 

Apologies to hear that you're still having issues authenticating to Azure.

To give a little context - Terraform supports authenticating to Azure through a few different methods: using the Azure CLI, MSI and using a Service Principal. When Terraform runs we look at the credentials which have been set in the Provider block, which optionally can come from Environment Variables - and then decide which authentication method should be used.

Taking a look at your original issue - the error being returned:

```
* provider.azurerm: Error building AzureRM Client: No (unexpired) Authorization Tokens were found - please re-authenticate using `az login`.
```

is an error being returned from the Azure CLI - this is as we don't support authenticating using the Azure CLI as a Service Principal (as the Azure CLI doesn't store the information we require when using a Service Principal for authentication, whereas it does when using a User account for authentication).

Whilst there are [some callouts to this in the documentation](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html#configuring-your-service-principal), we're working on making these clearer for the next release as part of some other work in this area. The underlying issue reported in #2341 (from the error above) has previously been reported in #502 - which is why the original issue was closed in favour of that one.

---

The other part of that question is how to configure the credentials when using a Service Principal - this is something we've been working on better documenting as a part of some other work in this area - which will ship in the next release. For the sake of completeness, allow me to cover each of those briefly:

When opting to authenticate using the Azure CLI (and your user account) - no Provider block is required, but we'd recommend pinning the version of the Provider being used, like so:

```hcl
provider "azurerm" {
  version = "=1.19.0"
}
```

When opting to use a Service Principal, the credentials must either be configured as Environment Variables, as shown below:

```bash
$ export ARM_CLIENT_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_CLIENT_SECRET="bfdbxafjfbdijdbjrgwndsadkndfdkdasnd="
$ export ARM_SUBSCRIPTION_ID="11111111-1111-1111-1111-111111111111"
$ export ARM_TENANT_ID="22222222-2222-2222-2222-222222222222"
```

which means the Provider block can just have the version defined:

```hcl
provider "azurerm" {
  version = "=1.19.0"
}
```

Alternatively you can define them directly in the Provider block (as shown below) - however we'd generally recommend against doing this since it means the credentials could be accidentally checked into version control.

```hcl
provider "azurerm" {
  version         = "=1.19.0"
  client_id       = "00000000-0000-0000-0000-000000000000"
  client_secret   = "bfdbxafjfbdijdbjrgwndsadkndfdkdasnd="
  subscription_id = "11111111-1111-1111-1111-111111111111"
  tenant_id       = "22222222-2222-2222-2222-222222222222"
}
```

Given you're looking to authenticate using a Service Principal - one of the methods outlined above should work for you. Would you be able to take a look and see if this works for you?

Thanks!

**Comment by mitchellh** [comment]
Hi @whiggs. 

I'm sorry that you've been frustrated. It is completely understandable and expected that someone would be frustrated by both the product not working and issues being closed when they feel they aren't adequately resolved. 

However, I want to remind you that there are humans on the other side of all your issues and the way we communicate as humans is important at all times. I've witnessed your reports across products and the tone and word choice is not in line with our [Community Guidelines](https://www.hashicorp.com/community-guidelines). The second paragraph in particular stands out, starting with "Please be careful in the words and phrases that you choose when communicating with others..." 

Your tone in the issues up to this point has been very aggressive (directly or passively). We're open to having a reasonable dialog to diagnose your issues, but its hard to do so when one side of the dialog responds with "yelling" (bolded statements that appear to be the for the purpose of aggression vs. general emphasis) or attacks to the project or maintainers (i.e. calling an answer "crap"). 

Our community and employees are doing our best to respond to your issues, and in many cases provide multiple paragraphs of detailed information regarding your issue (such as this one, but also others I've seen). If you feel we're mistaken, then please let us know, but do so with kindness, patience, and understanding. We want to fix issues, we want to help make the product work for you. But at the same time, we have a lot of issues to get to and lot of other folks pulling at us, so it's a balance!

I also recognize that a core part of your frustration is that the issues you opened get closed. They all get closed for a stated reason, but if you feel they were mistakenly closed, then responding to that or opening a new issue (what you've been doing) is totally valid. We certainly make mistakes sometimes when closing issues and you should point that out. But when doing so, please do so respectfully. 

Also, I must remind you that a project lead of another HashiCorp project has [already felt the need to apprise you of the Community Guidelines](https://github.com/hashicorp/vagrant/issues/9828#issuecomment-388487091). We'd like to address your issues and we'd like to engage in meaningful discourse about those issues, but if the same tone continues we may be forced to block you from engaging via our standard community channels.

**Comment by whiggs** [comment]
Was the "waiting response" tag in regards to a question concerning the actual issue, or was it my response to the soap box lecture?  I would like to think the former, yet do not see any question to answer that would facilitate resolving the issue.

**Comment by mitchellh** [comment]
The "waiting-response" is a tag that is automatically removed by a bot when the original poster responds. It was added when Tom added this response here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2420#issuecomment-443829873 and removed because you responded.
