### ISSUE TITLE
Feature Request: Azure Batch

### ISSUE THREAD

**Issue by MHHenriksen** [terraform-providers/terraform-provider-azurerm#2427]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for [Azure Batch](https://docs.microsoft.com/en-us/azure/batch/batch-technical-overview) service, to create infrastructure components (Batch account and pool).

### New or Affected Resource(s)

To support Azure Batch, the following resources need to be created:
 
* azurerm_batch_account
* azurerm_batch_pool

### Potential Terraform Configuration

```hcl
# Configure the Microsoft Azure Provider
provider "azurerm" {
  # if you're using a Service Principal (shared account) then either set the environment variables, or fill these in:  # subscription_id = "..."  # client_id       = "..."  # client_secret   = "..."  # tenant_id       = "..."
}
 
resource "azurerm_resource_group" "rg" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
}
 
resource "random_integer" "ri" {
  min = 10000
  max = 99999
}
 
resource "azurerm_storage_account" "stor" {
  name                     = "stor${random_integer.ri.result}"
  resource_group_name      = "${azurerm_resource_group.rg.name}"
  location                 = "${azurerm_resource_group.rg.location}"
  account_tier             = "${var.storage_account_tier}"
  account_replication_type = "${var.storage_replication_type}"
}
 
resource "azurerm_batch_account" "batch" {
  name                     = "batch${random_integer.ri.result}"
  resource_group_name      = "${azurerm_resource_group.rg.name}"
  location                 = "${azurerm_resource_group.rg.location}"
  storage_account_name     = "${azurerm_storage_account.stor.name}"
}
 
resource "azurerm_batch_pool" "pool" {
  id                    = "pool${random_integer.ri.result}"
  vm_size               = "${var.batch_pool_nodes_vm_size}"
  target_dedicated_node = "${var.batch_pool_nodes_count}"
  vm_image              = "${var.batch_pool_nodes_vm_image}"
  node_agent_sku_id     = "${var.batch.pool_nodes_agent_sku_id}"
}
```

### References

* Azure Batch Overview: https://docs.microsoft.com/en-us/azure/batch/batch-technical-overview
* Azure Batch API basics: https://docs.microsoft.com/en-us/azure/batch/batch-api-basics
* Azure SDK for Go - Batch: https://github.com/Azure/azure-sdk-for-go/blob/master/services/batch/
* REST API docs: https://docs.microsoft.com/en-us/rest/api/batchmanagement/
* Az CLI docs: https://docs.microsoft.com/en-us/cli/azure/batch?view=azure-cli-latest
* PowerShell docs: https://docs.microsoft.com/en-us/powershell/module/azurerm.batch/?view=azurermps-6.13.0

**Comment by jcorioland** [comment]
@tombuildsstuff @katbyte - FYI, I am working with @MHHenriksen on this implementation.
Let me know if you have any feedback.
