### ISSUE TITLE
azurerm_app_service_slot_custom_hostname_binding

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#2431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is `azurerm_app_service_custom_hostname_binding` but there is no `azurerm_app_service_slot_custom_hostname_binding`. Seems easy to implement given that the only difference between an app service and its slots is another two levels of hierarchy (`.../slots/slotName/...`)

### New or Affected Resource(s)

* azurerm_app_service_slot_custom_hostname_binding

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_slot_custom_hostname_binding" "test" {
  hostname            = "www.mywebsite.com"
  slot_name           = "staging"
  app_service_name    = "${azurerm_app_service.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}
```

**Comment by tombuildsstuff** [comment]
👋 

I'm going to close this in favour of #4240 - since there's more activity on that issue than this one (and these two issues are duplicates) - would you mind subscribing to that issue for updates?

Thanks!
