### ISSUE TITLE
AzureRm provider not working with instance metadata MSI endpoint?

### ISSUE THREAD

**Issue by LaurentLesle** [terraform-providers/terraform-provider-azurerm#2441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

provider azurerm version 0.19

### Affected Resource(s)

provider "azurerm"

- use_msi
- msi_endpoint

Current msi implementation of the azurerm provider is using the original MSI implementation through VM custom extension that is deprecated on January 2019. See recommended approach: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

https://www.terraform.io/docs/providers/azurerm/authenticating_via_msi.html

MSI can only be retrieved using the localhost endpoint. I could not get it working when overwriting the msi_endpoint to the instance metadata endpoint (recommended approach)

### Expected Behavior

Happy paths:

With System assigned identity:
- Create a VM with a system assigned identity,
- Grant permission to the system assigned identity as owner on a resource group or subscription,
- Execute from that VM terraform scripts with the azurerm provider configured to use msi

With User assigned identity:
- Create a user assigned identity and link it to a VM,
- Grant permission to the user assigned identity as owner on a resource group or subscription,
- Execute from that VM terraform scripts with the azurerm provider configured to use msi. It would require to pass the client_id of the user assigned identity (see: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http)

### Steps to Reproduce

With System assigned identity:
- Create a VM with a system assigned identity,
- Grant permission to the system assigned identity as owner on a resource group or subscription,
- Execute from that VM a terraform script to create a resource group with the azurerm provider configured to use msi. You are asked to authenticate

To confirm the system assigned identity is working with correct permissions, login to that VM, install azure cli and you should be able to login with 
az login --identity -u system_assigned_id
az group create -n "test" -l "westeurope"

### References

* #0000

**Comment by hbuckle** [comment]
The SDK is [returning](https://github.com/terraform-providers/terraform-provider-azurerm/blob/b5889d297162b138edd326cd8c566097ac963dd3/vendor/github.com/Azure/go-autorest/autorest/adal/token.go#L64) the instance metadata endpoint so system assigned identities should work without setting `msi_endpoint`

User assigned identities would need a code change to accept the `client_id`

**Comment by tombuildsstuff** [comment]
hey @LaurentLesle 

Thanks for opening this issue :)

Taking a quick look into this as @hbuckle has mentioned this appears to require an upstream change in [Azure/go-autorest](https://github.com/Azure/go-autorest) prior to us being able to support this. We've recently moved all the core authentication logic out of this repository and as such I'm going to migrate (read: close/re-open) this issue over to that repository, since that's where the work for this would be done: https://github.com/hashicorp/go-azure-helpers/issues/18 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by LaurentLesle** [comment]
Thanks @tombuildsstuff Will follow on the other repo.
