### ISSUE TITLE
Feature Request: Batch Pool Start Task

### ISSUE THREAD

**Issue by MHHenriksen** [terraform-providers/terraform-provider-azurerm#2458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Building on #2427, please add support for configuring a start task for a pool.
### New or Affected Resource(s)

* azurerm_batch_pool
* New data source: azurerm_batch_auto_user

### Potential Terraform Configuration

I'm a Terraform rookie, so take this suggestion with a pound of salt.

```hcl
# Configure the Microsoft Azure Provider
provider "azurerm" {
  # if you're using a Service Principal (shared account) then either set the environment variables, or fill these in:  # subscription_id = "..."  # client_id       = "..."  # client_secret   = "..."  # tenant_id       = "..."
}
 
resource "azurerm_resource_group" "rg" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
}
 
resource "random_integer" "ri" {
  min = 10000
  max = 99999
}
 
resource "azurerm_storage_account" "stor" {
  name                     = "stor${random_integer.ri.result}"
  resource_group_name      = "${azurerm_resource_group.rg.name}"
  location                 = "${azurerm_resource_group.rg.location}"
  account_tier             = "${var.storage_account_tier}"
  account_replication_type = "${var.storage_replication_type}"
}

resource "azurerm_batch_account" "batch" {
  name                     = "batch${random_integer.ri.result}"
  resource_group_name      = "${azurerm_resource_group.rg.name}"
  location                 = "${azurerm_resource_group.rg.location}"
  storage_account_name     = "${azurerm_storage_account.stor.name}"
}

data "azurerm_batch_auto_user" "pool_admin"
{
    scope = "pool" # or job
    elevated = true
}

resource "azurerm_batch_pool" "pool" {
  id                    = "pool${random_integer.ri.result}"
  vm_size               = "${var.batch_pool_nodes_vm_size}"
  target_dedicated_node = "${var.batch_pool_nodes_count}"
  vm_image              = "${var.batch_pool_nodes_vm_image}"
  node_agent_sku_id     = "${var.batch.pool_nodes_agent_sku_id}"
  start_task {
      command_line         = "/bin/bash -c 'apt-get -y update && apt-get -y install cowsay && cowsay Hello, $person!'"
      user_identity        = "${data.azurerm_batch_auto_user.pool_admin}"
      max_task_retry_count = 1
      environment {
          person = "World"
      }
  }
}
```

### References

* #2427 Feature Request: Azure Batch
* Start Task basics: https://docs.microsoft.com/en-us/azure/batch/batch-api-basics#start-task
* About user accounts: https://docs.microsoft.com/en-us/azure/batch/batch-user-accounts
* Azure Batch Overview: https://docs.microsoft.com/en-us/azure/batch/batch-technical-overview
* Azure SDK for Go - Batch: https://github.com/Azure/azure-sdk-for-go/blob/master/services/batch/

**Comment by jcorioland** [comment]
@MHHenriksen @katbyte - will look at this now that Batch pool feature (#2461) is implemented.

**Comment by stuartleeks** [comment]
@MHHenriksen - it looks like @jcorioland  has implemented the `start_task`: https://www.terraform.io/docs/providers/azurerm/d/batch_pool.html#start_task

Does that do what you need?

**Comment by MHHenriksen** [comment]
Yeah, looks good! We'll let you know if it breaks via new issues.
