### ISSUE TITLE
Feature Request: Service Fabric Mesh

### ISSUE THREAD

**Issue by Pothulapati** [terraform-providers/terraform-provider-azurerm#2486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure announced a Managed Service Fabric Experience on the name Service Fabric Mesh, and has API's to create and manage applications, services, volumes, etc. It is still in preview. 

Having terraform be able to manage these resources would be awesome. 

### New or Affected Resource(s)

* azurerm_servicefabricmesh

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.microsoft.com/en-us/rest/api/servicefabric/sfmeshrp-index
* https://docs.microsoft.com/en-gb/azure/service-fabric-mesh/

**Comment by Pothulapati** [comment]
I'm willing to take this issue and work on it. :smile:

**Comment by jcorioland** [comment]
@tombuildsstuff I am happy to have a look on this issue in the following weeks, if no work has been started yet.

**Comment by tombuildsstuff** [comment]
@Pothulapati / @jcorioland that'd be awesome 👍 - we briefly looked into this (vs the other Service Fabric) - from memory there's an SDK available (at least for the Preview API version)

Thanks!

**Comment by jcorioland** [comment]
@tombuildsstuff I will double check in Azure SDK for Go, but I think so. keep you posted.

**Comment by praneetloke** [comment]
Is this being worked on?

**Comment by jcorioland** [comment]
Hello, not on my side, I finally had to jump on something else, sorry!

**Comment by Pothulapati** [comment]
@praneetloke @jcorioland I don't think service fabric mesh is still being worked on! I think its on hold right now as there aren't any updates! 
Not even sure if the creation would work!

Feel free to take this up, if its working. :)

**Comment by mbfrahry** [comment]
Hey all. Service Fabric Mesh Application is now supported in the latest version of Terraform!
