### ISSUE TITLE
cannot destroy azurerm_network_interface_backend_address_pool_association when the network interface was manually deleted

### ISSUE THREAD

**Issue by rgl** [terraform-providers/terraform-provider-azurerm#2491]
I was trying to launch two virtual machines behind a load balancer. But after 45 minutes, azure failed to create one of the machines, to try to recover the situation, I've manually deleted the virtual machine and tried to run terraform apply again, but it kept on failing due to missing resources, until I've end-up with:

```
Error: Error refreshing state: 1 error(s) occurred:

* azurerm_network_interface_backend_address_pool_association.web: 2 error(s) occurred:

* azurerm_network_interface_backend_address_pool_association.web[1]: azurerm_network_interface_backend_address_pool_association.web.1: Network Interface "web2" (Resource Group "rgl-load-balancer-example") was not found!
* azurerm_network_interface_backend_address_pool_association.web[0]: azurerm_network_interface_backend_address_pool_association.web.0: Network Interface "web1" (Resource Group "rgl-load-balancer-example") was not found!
```

Which I could not recover from. This made me think that terraform should not refuse to run when a resource was manually delete from azure portal. It should ignore that fact and assume the resource was MIA and re-create it again.

### Terraform (and AzureRM Provider) Version

Terraform v0.11.9
+ provider.azurerm v1.19.0
+ provider.random v2.0.0

### Affected Resource(s)

* azurerm_network_interface_backend_address_pool_association

### Configuration

```hcl
resource "azurerm_lb_backend_address_pool" "web" {
  resource_group_name = "${azurerm_resource_group.example.name}"
  loadbalancer_id     = "${azurerm_lb.web.id}"
  name                = "web"
}

resource "azurerm_network_interface_backend_address_pool_association" "web" {
  count                   = "${var.web_vm_count}"
  network_interface_id    = "${azurerm_network_interface.web.*.id[count.index]}"
  ip_configuration_name   = "web"
  backend_address_pool_id = "${azurerm_lb_backend_address_pool.web.id}"
}
```

### Expected Behavior

It should ignore manually deleted / non-long existing resources.

### Actual Behavior

It refuses to do anything.

### Steps to Reproduce

1. `terraform apply`
2. manually delete a network interface that is also inside the load balancer backend
3. try terraform apply or destroy

**Comment by cehoffman** [comment]
Additional information for this since we have experience this issue as well. This worked in the 1.19 release and was broken in 1.20. We have logs verifying such.

**Comment by jawiz** [comment]
How did you recover from this state?

**Comment by OffColour** [comment]
Having the same issue.
After removing various items from the state, I finally got it to run after running:
terrafrom state rm azurerm_network_interface_backend_address_pool_association.nameoftheassociation
for the association that had the NIC in it.

Don't know if it would have worked if that had been the first thing I deleted or it was cumulative.

**Comment by ArcturusZhang** [comment]
I am trying to reproduce this issue in go sdk using this [code snippet](https://gist.github.com/ArcturusZhang/2c79235fb75d3d3ab95437bbf9aae592), but I did not reproduce this issue.
When I change the order of destruction of each resource, it may fail, but with different error message.

**Comment by ArcturusZhang** [comment]
This issue is a subset of issue #4330

**Comment by danielgriggs** [comment]
This is still an unsolved problem.
If a VM NIC that is in a load balancer is removed from outside TF, on a plan, apply, or refresh TF just bails. I would expect it to recreate the resource. Not pack a sad.
