### ISSUE TITLE
Add attributes reference for azurerm_signalr_service

### ISSUE THREAD

**Issue by karpenkoKhAI** [terraform-providers/terraform-provider-azurerm#2506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please, add attributes for azurerm_signalr_service resource:
* primary_access_key
* primary_connection_string
* secondary_access_key
* secondary_connection_string

### New or Affected Resource(s)

* azurerm_signalr_service

### Potential Terraform Configuration

```hcl
resource "azurerm_signalr_service" "example" {
  name                = "tfex-signalr"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  sku {
    name     = "Free_F1"
    capacity = 1
  }
}
output "example_primary_key" {
  value = "${azurerm_signalr_service.example.primary_access_key}"
}
output "example_secondary_key" {
  value = "${azurerm_signalr_service.example.secondary_access_key}"
}
output "example_primary_connection_string" {
  value = "${azurerm_signalr_service.example.primary_connection_string}"
}
output "example_secondary_connection_string" {
  value = "${azurerm_signalr_service.example.secondary_connection_string}"
}
```

### References
* https://docs.microsoft.com/en-us/cli/azure/signalr/key?view=azure-cli-latest

**Comment by katbyte** [comment]
Hi @karpenkoKhAI,

Thanks for bringing this to our attention, these attributes have been added to the next upcoming release 1.22 that should come out with in the next few weeks 🙂
