### ISSUE TITLE
Feature Request: Support AKS Virtual Nodes

### ISSUE THREAD

**Issue by geertn** [terraform-providers/terraform-provider-azurerm#2508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently AKS implemented AKS Virtual Nodes
https://azure.microsoft.com/en-us/blog/bringing-serverless-to-azure-kubernetes-service/

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

**Comment by metacpp** [comment]
@geertn `Virtual Nodes` was released in v1.21.0:
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#aci_connector_linux

You can still leave comment here, we will keep responding.
