### ISSUE TITLE
Allow to provide a azure partner customer usage GUID to tag the resources provisioned by Terraform?

### ISSUE THREAD

**Issue by luisdavim** [terraform-providers/terraform-provider-azurerm#2515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft parteners can use a GUID to track customer usage:
https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution

### New

I would like to be able to add the GUID to mark the resources provisioned through our Terraform code.

**Comment by tombuildsstuff** [comment]
hi @luisdavim 

Thanks for opening this issue :)

Support for this has previously been requested in #2393 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #2393.

Thanks!
