### ISSUE TITLE
Missing Settings: azurerm_app_service Backups

### ISSUE THREAD

**Issue by midacts** [terraform-providers/terraform-provider-azurerm#2569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

the azurerm_app_service does not allow admins to configure web app's backups.

### New or Affected Resource(s)

azurerm_app_service

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service" "test" {
  name                = "${random_id.server.hex}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  app_service_plan_id = "${azurerm_app_service_plan.test.id}"

  site_config {
    java_version           = "1.8"
    java_container         = "JETTY"
    java_container_version = "9.3"
    scm_type               = "LocalGit"
  }

  backup_settings {
    interval          = "1 days"
    start             = "01/01/2019 00:00:00 EST"
    retention         = "30"
    retain_one_backup = true
    included_sql_db   = "testdb_name"
  }
}
```

**Comment by tombuildsstuff** [comment]
👋 

Support for App Service Backups is available via [the `backup` block within the `azurerm_app_service` resource](https://www.terraform.io/docs/providers/azurerm/r/app_service.html) - as such I'm going to close this issue for the moment.

Thanks!

**Comment by midacts** [comment]
Thanks for all you and your team's hard work.
