### ISSUE TITLE
Monitor Diagnostic Setting: invalid or unknown key: event_hub_authorization_rule_id

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#2571]
I did see issues #626 and #1020, but I think this is a bit of a new one.

The documentation shows that one of the parameters is [event_hub_authorization_rule_id](https://www.terraform.io/docs/providers/azurerm/r/monitor_diagnostic_setting.html#event_hub_authorization_rule_id) in the monitor diagnostic setting resource, however, I'm getting this error returned:
`Error: module.example_kv_diagnostic.azurerm_monitor_diagnostic_setting.azure_mds_log: : invalid or unknown key: event_hub_authorization_rule_id`

This would be my example code

```hcl
resource "azurerm_monitor_diagnostic_setting" "azure_mds_log" {
  count              = "${length(var.log_category) > 0 && length(var.metric_category) < 1 ? 1 : 0}"
  name               = "${module.namespace.name}"
  target_resource_id = "${var.monitored_resource_id}"
  storage_account_id = "${var.log_storage_account}"

  event_hub_name                  = "${var.event_hub_name}"
  event_hub_authorization_rule_id = "${var.event_hub_auth_rule_id}"
  log_analytics_workspace_id      = "${var.log_analytics_workspace}"

  log {
    category = "${var.log_category}"
    enabled  = true

    retention_policy {
      days    = "${var.log_retention_days}"
      enabled = true
    }
  }
}
```

Doing the standard init & apply would reproduce the error.

**Comment by tombuildsstuff** [comment]
hey @bcline760 

Thanks for opening this issue :)

So that we could take a look into this would it be possible to know which version of Terraform and the Azure Provider you're running?

Thanks!

**Comment by bcline760** [comment]
Terraform v0.11.10
+ provider.azurerm v1.20.0
+ provider.null v1.0.0
+ provider.random v2.0.0

Your version of Terraform is out of date! The latest version
is 0.11.11. You can update by downloading from www.terraform.io/downloads.html

**Comment by tombuildsstuff** [comment]
hey @bcline760 

Thanks for confirming that / apologies for the delayed response here.

Taking a look into this this appears to be a bug in the documentation - the fields are `eventhub_authorization_rule_id` and `eventhub_name` (without an underscore between event and hub) - which got renamed during the PR which added support for this but missed in the documentation. I'll open a PR to fix this shortly - but would you be able to take a look and see if using the names without the underscores works for you?

Thanks!
