### ISSUE TITLE
Terraform doesn't support mysql provision in China Azure

### ISSUE THREAD

**Issue by juanahx** [terraform-providers/terraform-provider-azurerm#2573]
I tried to use below configuration to provision a mysql server in China Azure:
`resource "azurerm_mysql_server" "testmysql" {
  name                = "${var.projectname}-${var.env}-mysql"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"

  sku {
    name     = "MS1"
    capacity = 2
    tier     = "Basic"
    family   = "Gen4"
  }

  storage_profile {
    storage_mb            = 5120
    backup_retention_days = 7
    geo_redundant_backup  = "Disabled"
  }

  administrator_login          = "${var.mysql_user}"
  administrator_login_password = "${var.mysql_password}"
  version                      = "5.7"
  ssl_enforcement              = "Enabled"
}`

But got  below error message:
`Error: azurerm_mysql_server.testmysql: expected sku.0.name to be one of [B_Gen4_1 B_Gen4_2 B_Gen5_1B_Gen5_2 GP_Gen4_2 GP_Gen4_4 GP_Gen4_8 GP_Gen4_16 GP_Gen4_32 GP_Gen5_2 GP_Gen5_4 GP_Gen5_8 GP_Gen5_16 GP_Gen5_32 GP_Gen5_64 MO_Gen5_2 MO_Gen5_4 MO_Gen5_8 MO_Gen5_16 MO_Gen5_32], got MS1`

I also tried sku name with "B_Gen4_2", "B_Gen4_1"

But got below error:
`* azurerm_mysql_server.testmysql: Error waiting for creation of MySQL Server "testmysql" (Resource Group "rg"): Code="ProvisioningDisabled" Message="Gen4 hardware is not supported for this region."`

Does it mean mysql provision in China Azure not supported yet?

Thanks

**Comment by LINGTLL** [comment]
二区不支持gen4，换gen5

**Comment by katbyte** [comment]
Hi @juanahx,

Sorry to hear that your having this problem. It looks like you are trying to use `MS1` as the `sku` name and it is not part of the current validation set. Are the SKU's different in china?

**Comment by juanahx** [comment]
> Sorry to hear that your having this problem. It looks like you are trying to use `MS1` as the `sku` name and it is not part of the current validation set. Are the SKU's different in china?

Hi @katbyte ,

I found sku name like "MS1" from "MySQL Database on Azure" which will be retired soon.
I am supposed to use "Azure Database for MySQL servers" instead.
So this issue is invalid.
I will close this issue.

Thanks

**Comment by juanahx** [comment]
> 二区不支持gen4，换gen5

多谢了哥们 搞定。
