### ISSUE TITLE
Unable to Authenticate to Azure via Terraform

### ISSUE THREAD

**Issue by cdeli** [terraform-providers/terraform-provider-azurerm#2575]
Recieving the following error

Error: Error refreshing state: 1 error(s) occurred:

`* provider.azurerm: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<MySub>/providers?api-version=2017-05-10: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: b027f77f-ff87-44e6-970b-6e9aa3390100\r\nCorrelation ID: c355907d-99a4-48a0-977a-45fea20a0ae2\r\nTimestamp: 2018-12-26 23:33:22Z","error_codes":[70002,50012],"timestamp":"2018-12-26 23:33:22Z","trace_id":"b027f77f-ff87-44e6-970b-6e9aa3390100","correlation_id":"c355907d-99a4-48a0-977a-45fea20a0ae2"}`

I checked my service principal and it was good. I changed the SP to a new one I just made, following the instructions {here](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html) and run into the same error. I attempted to run the code directly in the Azure console and received the same error.

I am unsure of where the issue is at this point in time. Any help would be appreciated.

**Comment by cdeli** [comment]
May close this. Secret was being generated in the past.

**Comment by tombuildsstuff** [comment]
hey @cdeli 

Thanks for opening this issue :)

Since this appears to have been resolved I'm going to close this issue for the moment - but please feel free to re-open it if you're still having issues and we can take another look :)

Thanks!
