### ISSUE TITLE
azurerm_monitor_diagnostic_setting: Invalid resource types for event hub logging.

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#2601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.10
+ provider.azurerm v1.20.0
+ provider.null v1.0.0
+ provider.random v2.0.0

Your version of Terraform is out of date! The latest version
is 0.11.11. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)

* azurerm_monitor_diagnostic_setting
* azurerm_eventhub (maybe)

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "kvdiag_eventhub_ns" {
  name                = "keyvaultdiagexehns-${local.namespace}"
  location            = "centralus"
  resource_group_name = "${module.create-resource-group.name}"
  sku                 = "Standard"
  capacity            = 2
}

resource "azurerm_eventhub" "kvdiag_eventhub" {
  name                = "keyVaultDiagExEventHub-${local.namespace}"
  namespace_name      = "${azurerm_eventhub_namespace.kvdiag_eventhub_ns.name}"
  location            = "centralus"
  resource_group_name = "${module.create-resource-group.name}"
  partition_count     = 2
  message_retention   = 2
}

resource "azurerm_eventhub_authorization_rule" "kvdiag_eventhub_rule" {
  name                = "keyVaultDiagExAuthRule-${local.namespace}"
  namespace_name      = "${azurerm_eventhub_namespace.kvdiag_eventhub_ns.name}"
  eventhub_name       = "${azurerm_eventhub.kvdiag_eventhub.name}"
  resource_group_name = "${module.create-resource-group.name}"
  listen              = true
  send                = false
  manage              = false
}

# This is referenced as a module in the actual file, but I'll show the actual resource it would execute.
resource "azurerm_monitor_diagnostic_setting" "azure_mds_metriclog_eventhub" {
  count              = "${length(var.metric_category) > 0 && length(var.log_category) > 0 ? 1 : 0}"
  name               = "${module.namespace.name}"
  target_resource_id = "${var.monitored_resource_id}"

  eventhub_name                  = "${var.event_hub_name}"
  eventhub_authorization_rule_id = "${var.event_hub_auth_rule_id}"

  metric {
    category = "${var.metric_category}"

    retention_policy {
      days    = "${var.log_retention_days}"
      enabled = true
    }
  }

  log {
    category = "${var.log_category}"
    enabled  = true

    retention_policy {
      days    = "${var.log_retention_days}"
      enabled = true
    }
  }
}
```

### Debug Output

Contact me if debug output is required. Output contains values like subscription IDs and the like.

### Expected Behavior

According to documentation provided, I should see the resource created.

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:
module.diagnostic_log_keyvault_eventhub.azurerm_monitor_diagnostic_setting.azure_mds_metriclog_eventhub: 1 error(s) occurred:

azurerm_monitor_diagnostic_setting.azure_mds_metriclog_eventhub: Error creating Monitor Diagnostics Setting "kv_diag_ex-etf5hpdk" for Resource "/subscriptions/[redacted]/resourceGroups/keyvault-diag-ex-etf5hpdk/providers/Microsoft.KeyVault/vaults/examplekvdiag-etf5hpdk": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="\"Resource type 'microsoft.eventhub/namespaces/eventhubs/authorizationrules' is invalid for property 'properties.eventHubAuthorizationRuleId'. Expected types are 'microsoft.servicebus/namespaces/authorizationrules', 'microsoft.eventhub/namespaces/authorizationrules'\""
```

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by katbyte** [comment]
Ji @bcline760,

Sorry to hear you are having this issue. I've noticed you are using a variable for the rule ID. Could you change:
```hcl
eventhub_authorization_rule_id = "${var.event_hub_auth_rule_id}"
```

to

```hcl
eventhub_authorization_rule_id = "${azurerm_eventhub_authorization_rule.kvdiag_eventhub_rule.id}"
```

and see if that works? generally it is always best to refer to other resources than rely on variables being correct.

**Comment by bcline760** [comment]
That is kind of how I do it. So like I said, I'm actually calling it by an encapsulated module. This is what the calling module looks like

```hcl
resource "azurerm_eventhub" "kvdiag_eventhub" {
  name                = "keyVaultDiagExEventHub-${local.namespace}"
  namespace_name      = "${azurerm_eventhub_namespace.kvdiag_eventhub_ns.name}"
  location            = "centralus"
  resource_group_name = "${module.create-resource-group.name}"
  partition_count     = 2
  message_retention   = 2
}

resource "azurerm_eventhub_authorization_rule" "kvdiag_eventhub_rule" {
  name                = "keyVaultDiagExAuthRule-${local.namespace}"
  namespace_name      = "${azurerm_eventhub_namespace.kvdiag_eventhub_ns.name}"
  eventhub_name       = "${azurerm_eventhub.kvdiag_eventhub.name}"
  resource_group_name = "${module.create-resource-group.name}"
  listen              = true
  send                = false
  manage              = false
}

module "diagnostic_log_keyvault_eventhub" {
  source                 = "../../modules/event_hub_logging"
  name                   = "kv_diag_ex"
  namespace              = "${local.namespace}"
  event_hub_name         = "${azurerm_eventhub.kvdiag_eventhub.name}"
  event_hub_auth_rule_id = "${azurerm_eventhub_authorization_rule.kvdiag_eventhub_rule.id}"
  monitored_resource_id  = "${module.example_key_vault.id}"
  log_category           = "AuditEvent"
  metric_category        = "AllMetrics"
}
```

**Comment by tombuildsstuff** [comment]
hey @bcline760 

Thanks for confirming that :)

Taking a look at the error message being returned from the API here:

> Resource type 'microsoft.eventhub/namespaces/eventhubs/authorizationrules' is invalid for property 'properties.eventHubAuthorizationRuleId'. Expected types are 'microsoft.servicebus/namespaces/authorizationrules', 'microsoft.eventhub/namespaces/authorizationrules'

There's two different kinds of Authorization Rules for an EventHub:

* `azurerm_eventhub_namespace_authorization_rule` - which is a Authorization Rule for an EventHub Namespace (the top-level)
* `azurerm_eventhub_authorization_rule` - which is a Authorization Rule for an EventHub (nested within an EventHub Namespace)

I've noticed that the `azurerm_eventhub_namespace_authorization_rule` resource is missing from the sidebar, so I've opened #2610 which adds these back in.

In this instance it appears the Diagnostics Setting resource requires the ID of a `azurerm_eventhub_namespace_authorization_rule` resource, rather than the ID of the `azurerm_eventhub_authorization_rule` resource - would you mind taking a look and seeing if that works for you? Here's an example of the configuration we use in our tests to test this configuration: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_monitor_diagnostic_setting_test.go#L158-L225

Thanks!

**Comment by bcline760** [comment]
Ah that worked, using `azurerm_eventhub_namespace_authorization_rule` instead.

Thanks for the assist! 👊🏼👍🏼

**Comment by tombuildsstuff** [comment]
@bcline760 awesome - I've opened https://github.com/terraform-providers/terraform-provider-azurerm/pull/2612 which updates the documentation to make this clearer too :)
