### ISSUE TITLE
API Management Consumption Tier

### ISSUE THREAD

**Issue by scottrangerio** [terraform-providers/terraform-provider-azurerm#2613]
Hey all,

API Management has a consumption tier which is currently in preview. It would be great to see the azurerm_api_management resource updated to support the additional tier.

I've had a quick look and the property does exist in the Azure sdk https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go#L510 so it appears this should just be a case of updating the vendored package, updating the schema to include the additional tier and then testing it.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_api_management

**Comment by tombuildsstuff** [comment]
Dependent on https://github.com/Azure/azure-rest-api-specs/issues/4409 (since this exposes the new API/SDK version required)

**Comment by tombuildsstuff** [comment]
👋 

The upstream issue's been fixed: https://github.com/Azure/azure-rest-api-specs/issues/4409 - once the SDK's been updated #3335 we should be able to go to the new version of the API Management API - at which point it should be possible to add support for this

Thanks!

**Comment by mikhailshilkov** [comment]
[Azure API Management Consumption Tier is generally available](https://azure.microsoft.com/en-us/updates/azure-api-management-consumption-tier-is-now-generally-available/) since May 29

**Comment by tminhein** [comment]
Is Terraform stopped supporting Azure.  a lot of new features aren't available in terraform.  I.E: 
1. Consumption Tier in Azure apim
2. throughput option in cosmos db database layer.

Those are already reported in Github months and months ago.

**Comment by tombuildsstuff** [comment]
@tminhein this functionality requires upgrading to the new version of the API Management API (2019-01-01) - which unfortunately [doesn't match the API response](https://github.com/Azure/azure-rest-api-specs/pull/6065) - as such we're unable to add support for this until the API/SDK is fixed.

**Comment by stena-dev** [comment]
> @tminhein this functionality requires upgrading to the new version of the API Management API (2019-01-01) - which unfortunately [doesn't match the API response](https://github.com/Azure/azure-rest-api-specs/pull/6065) - as such we're unable to add support for this until the API/SDK is fixed.

@tombuildsstuff  i can see that the api response bug has been closed.  I wonder that the consumption has available in the terraform ?

**Comment by tombuildsstuff** [comment]
@stena-dev unfortunately the API's still broken, which is now being tracked in https://github.com/Azure/azure-rest-api-specs/pull/6065

**Comment by arifsundrani** [comment]
@tombuildsstuff 

Sorry to poke you, but do you have an update on this? I am wondering as the [pull request](https://github.com/Azure/azure-rest-api-specs/pull/6065) has been closed.

Thanks

**Comment by tombuildsstuff** [comment]
@arifsundrani we're still waiting on Microsoft to fix the API: https://github.com/Azure/azure-rest-api-specs/issues/6372

**Comment by brunhil** [comment]
> @tminhein this functionality requires upgrading to the new version of the API Management API (2019-01-01) - which unfortunately doesn't match the API response - as such we're unable to add support for this until the API/SDK is fixed

@tombuildsstuff , is there any chance that we could migrate from the _2018-01-01_ API spec to the _2018-06-01-preview_ API spec? This has the consumption tier in the Go SDK, [link](https://github.com/Azure/azure-sdk-for-go/blob/392ea0b046cfb0cb05942ea92baf22af9ff7f9df/services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go#L518)

**Comment by tombuildsstuff** [comment]
@brunhil it's technically possible since the preview api has [the field with the correct type](https://github.com/Azure/azure-sdk-for-go/blob/392ea0b046cfb0cb05942ea92baf22af9ff7f9df/services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go#L9062) - however older preview versions can be pulled at any time - as such we tend to avoid them where a stable API is available instead (such as in this case, where the API is available but the Swagger doesn't match the API definition).

**Comment by devedse** [comment]
It seems that the consumption tier is now available in most regions:
https://azure.microsoft.com/en-us/updates/api-management-consumption-tier-in-19-regions/

It seems the issue with the API is still not resolved:
https://github.com/Azure/azure-rest-api-specs/issues/6372

Any updates / timelines on this as our project would like to make use of the Consumption tier of APIM?

**Comment by mjunker** [comment]
We're interested in this as well. Any update on this?

**Comment by szaher** [comment]
so api version 2019-12-01 is release 3 days ago, can we go ahead and use it to fix this issue ?

https://github.com/Azure/azure-sdk-for-go/tree/master/services/apimanagement/mgmt/2019-12-01/apimanagement 

https://github.com/Azure/azure-sdk-for-go/releases/tag/v40.6.0 

If there anything that I can do to help I will be more than happy :)

**Comment by Harmindersingh05** [comment]
Hi @tombuildsstuff any chance this could be included the next release?

**Comment by szaher** [comment]
hey @tombuildsstuff I was working on a patch to bump the api version to either 2019-01-01 or 2019-12-01 but looks like there are lots of changes in the new APIs. Is there a way you guys are following to judge what fields to add and what to ignore ?

**Comment by szaher** [comment]
The fix is available at following locations
REST API doc; https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apischema/createorupdate

.NET SDK :
https://www.nuget.org/packages/Microsoft.Azure.Management.ApiManagement/5.0.0-preview
ChangeLog; https://aka.ms/apimdotnetsdkchangelog

Python SDK
https://pypi.org/project/azure-mgmt-apimanagement/0.2.0/

JS SDK
https://www.npmjs.com/package/@azure/arm-apimanagement/v/6.0.0

Go SDK
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-12-01/apimanagement?tab=doc

**Comment by tikicoder** [comment]
any updates to get this included?  I have a client wanting to use it.

**Comment by brunhil** [comment]
There's a two part change that needs to happen for this to be completed.

1. Upgrade the API Management SDK from the current version, 2018-01-01, to the new version, 2019-02-01
2. Upgrade the **azurerm_api_management** resource to be able to use the new SKUs

It looks like @katbyte is working on #1 currently in the following PR: [[WIP] provider: upgrade API Management to 2019-12-01](https://github.com/terraform-providers/terraform-provider-azurerm/pull/6479).

You can follow along that PR to see the changes. Once those are completed you should be able to tackle this issue!

**Comment by szaher** [comment]
Well, I was working on a patch locally but as I never got answer from @tombuildsstuff  so I wasn't If I must submit it or not, I was looking for an answer regarding `SchemaDocumentProperties` as it has changed from 2018-01-01 to 2019-12-01 ...
Any way will be waiting for @katbyte patch to land and will be more than happy to help.

@brunhil It can be in the same patch no need for another patch for the SKU I think, it could happen as part of the SDK upgrade as it's not straight forward

**Comment by katbyte** [comment]
@scottrangerio & @szaher #6479 has been merged so master is on the latest version of the API 🙂🚀

**Comment by szaher** [comment]
@katbyte Thanks very much for the patch. 
Can we get this one merged as well  https://github.com/terraform-providers/terraform-provider-azurerm/pull/6602 ?

I think you forgot the consumption tier for apim
