### ISSUE TITLE
Default Availability Sets to Managed Disks

### ISSUE THREAD

**Issue by errygg** [terraform-providers/terraform-provider-azurerm#2614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently Managed Disks default to `false` for the `azurerm_availability_set` resource; however, Managed Disks default to `true` in the Azure Portal per https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq-for-disks. Suggest that the default for Managed Disks be set to `true` in the `azurerm_availability_set` resource.

### New or Affected Resource(s)

* azurerm_availability_set

### Potential Terraform Configuration

N/A

### References

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq-for-disks

**Comment by metacpp** [comment]
@errygg Thanks for reporting this issue.

`azurerm_availability_set` supports both managed and unmanaged disks:
https://www.terraform.io/docs/providers/azurerm/r/availability_set.html

You may consider to use `module` to wrap `azurerm_availability_set` a bit to have some default value in your scenario. WDYT ?

**Comment by tombuildsstuff** [comment]
@metacpp we can update this value in 2.0, since it'll be a breaking change

**Comment by metacpp** [comment]
@tombuildsstuff Yes, we can. The only thing I am not sure is what if the `managed` is majority here. WDYT?
