### ISSUE TITLE
Terraform plan does not report an invalid subnet. Terraform apply fails.

### ISSUE THREAD

**Issue by asubmani** [terraform-providers/terraform-provider-azurerm#2615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version: 
Terraform v0.11.11
+ provider.azurerm v1.20.0

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "akscluster" {
  name                = "${var.cluster_name}"
  location            = "${azurerm_resource_group.aksrg.location}"
  resource_group_name = "${azurerm_resource_group.aksrg.name}"
  dns_prefix          = "${var.dns_prefix}"
  kubernetes_version  = "${var.k8s_version}"

network_profile {
     network_plugin = "azure"
     docker_bridge_cidr = "172.17.0.1/16"
     dns_service_ip = "10.0.0.10"
     service_cidr = "10.0.0/16"
  }
}
```

### Expected Behavior

`terraform plan`  should report on the invalid subnet, i.e. 10.0.0/16

### Actual Behavior
1. ` terraform plan -out out.plan`

Plan: 3 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: out.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "out.plan"

2. `terraform apply out.plan`

Error: Error applying plan:

1 error(s) occurred:

* azurerm_kubernetes_cluster.akscluster: 1 error(s) occurred:

* azurerm_kubernetes_cluster.akscluster: Error creating/updating Managed Kubernetes Cluster "kumaakstfdemo3" (Resource Group "tf-aks-demo"): containerservice.ManagedClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedClusterProperties.NetworkProfile.ServiceCidr constraint=Pattern value="10.0.0/16" details: value doesn't match pattern ^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$

### Steps to Reproduce

1. `terraform plan`  # this does not catch the invalid subnet
2. `terraform apply` # this will report an error due to error from azure go SDK?

### References

* #0000

**Comment by tracypholmes** [comment]
Hi @asubmani! Thank you for opening this. It appears this issue no longer exists. Using the configuration you provided, I receive the following when using `terraform plan`:
```sh

Error: network_profile.0.service_cidr must start with IPV4 address and/or slash, number of bits (0-32) as prefix. Example: 127.0.0.1/8. Got "10.0.0/16".

  on reproduction.tf line 37, in resource "azurerm_kubernetes_cluster" "test":
  37: resource "azurerm_kubernetes_cluster" "test" {
```
I am going to close this for now. But if this issue still persists for you, please feel free to open another issue.
