### ISSUE TITLE
Sku Name Parameter for azurerm_mssql_elasticpool Doesn't Accept 'StandardPool'

### ISSUE THREAD

**Issue by ktobin-occm** [terraform-providers/terraform-provider-azurerm#2622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
'Terraform v0.11.11
+ provider.azurerm v1.20.0'

### Affected Resource(s)

* azurerm_mssql_elasticpool 

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "pool" {
  name                = "Pool001"
  resource_group_name = "${var.resource_group_name}"
  location            = "eastus"
  server_name         = "${azurerm_sql_server.server.name}"

  sku {
    name     = "StandardPool"
    capacity = "200"
    tier     = "GeneralPurpose"
  }

  per_database_settings {
    min_capacity = "0"
    max_capacity = "100"
  }
}
```
### Expected Behavior

The resource should have accepted the SKU Name of `StandardPool` as a valid SKU Name and created the pool.

### Actual Behavior

Using the value 'StandardPool' generates the folling error:

>azurerm_mssql_elasticpool.pool: sql.ElasticPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidSkuName" Message="Invalid SKU name 'StandardPool'."

Attempting to use a different value such as `Standard` returns a list of acceptable values including `StandardPool`:

>Error: module.sqlserver.azurerm_mssql_elasticpool.pool: expected sku.0.name to be one of [BasicPool StandardPool PremiumPool GP_Gen4 GP_Gen5 BC_Gen4 BC_Gen5], got Standard

### Steps to Reproduce

1. Create terraform code using the value `StandardPool` for the Sku Name parameter on the azurerm_mssql_elasticpool resource.

2. `terraform apply`

* #0000

**Comment by jeffreyCline** [comment]
@ktobin-occm Thanks for opening this issue. This can be terribly confusing, the new API merges support for `DTU` and `vCore` based **ElasticPool SKUs** into a single API. The current way you have your **SKU** defined you have the `name` set for a `DTU` based **SKU** and the `tier` for a `vCore` based **SKU** which is not valid and why you are seeing the error you are getting. The correct configuration for a `StandardPool` **SKU** would be:

```
  sku {
    name     = "StandardPool"
    capacity = "200"
    tier     = "Standard"
  }
```

**Comment by jeffreyCline** [comment]
@ktobin-occm with my new PR if you attempted to use your sample configuration file you would now get the below error, which I fill is easier to understand and points out what the issue is with the file.

```
Error: Error running plan: 1 error(s) occurred:

* azurerm_mssql_elasticpool.test: 1 error(s) occurred:

* azurerm_mssql_elasticpool.test: Mismatch between SKU name 'StandardPool' and tier 'GeneralPurpose', expected 'tier' to be 'Standard'
```
