### ISSUE TITLE
Unable to set autoscaling setting for vmss to 0 min/default, also max too low

### ISSUE THREAD

**Issue by slikk66** [terraform-providers/terraform-provider-azurerm#2624]
In the console, I can apply an autoscaling rule to a VMSS and set it to 0 for min/default:  https://imgur.com/a/B5WE7i3

Checking resouces.azure.com, this is confirmed:

    "properties": {
      "profiles": [
        {
          "name": "Auto created scale condition",
          "capacity": {
            "minimum": "0",
            "maximum": "300",
            "default": "0"
          },

However, trying to do so via Terraform I hit a limit of 1-40, apparently controlled here:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/47a920a9fdd0e8b82d7d7c568caee6b9fb6db410/azurerm/resource_arm_autoscale_setting.go#L74

    azure:autoscale:Setting (Stage-Eus2-Scale-Config):
      error: azure:autoscale/setting:Setting resource 'Stage-Eus2-Scale-Config' has a problem: expected profile.0.capacity.0.default to be in the range (1 - 40), got 0                                                                                            
      error: azure:autoscale/setting:Setting resource 'Stage-Eus2-Scale-Config' has a problem: expected profile.0.capacity.0.minimum to be in the range (1 - 40), got 0 

Also, the max is 40.. why on earth?  We can have somewhere upwards of 1000 for a vmss.. please fix this!

**Comment by georgespatton** [comment]
This is the exact same bug I am seeing here:

https://github.com/terraform-providers/terraform-provider-azurerm/issues/2136

**Comment by georgespatton** [comment]
PR pending review here:  https://github.com/terraform-providers/terraform-provider-azurerm/pull/2806
