### ISSUE TITLE
Validation of the Key Vault's name is not executed when it is terraform plan

### ISSUE THREAD

**Issue by changeworld** [terraform-providers/terraform-provider-azurerm#265]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

`Terraform v0.10.2`

### Affected Resource(s)

Please list the resources as a list, for example:
- azurerm_key_vault

### Terraform Configuration Files
```hcl
variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}

# Configure the Microsoft Azure Provider
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}

resource "azurerm_resource_group" "test" {
  name     = "testKeyVault"
  location = "West US"
}

resource "azurerm_key_vault" "test" {
  name                = "abcdefghijklmnopqrstuvwxyz"
  location            = "West US"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    name = "standard"
  }

  tenant_id = "${var.tenant_id}"

  access_policy {
    tenant_id = "${var.tenant_id}"
    object_id = "d746815a-0433-4a21-b95d-fc437d2d475b"

    key_permissions = [
      "all",
    ]

    secret_permissions = [
      "get",
    ]
  }

  enabled_for_disk_encryption = true

  tags {
    environment = "Test"
  }
}
```

### Debug Output

[Debug Output](https://gist.github.com/changeworld/99870b04bb3e55b9cc525a3d2a628a3a)

### Expected Behavior

Run Validation at running terraform plan.

### Actual Behavior

There was no error when running terraform plan.
However, validation error occurred when running terraform apply.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by tombuildsstuff** [comment]
Hey @changeworld 

Thanks for opening this issue - I've opened #270 which includes a fix for this.

Thanks!

**Comment by changeworld** [comment]
Thanks!
