### ISSUE TITLE
Set FTP Settings for azurem_function_app

### ISSUE THREAD

**Issue by kplantus** [terraform-providers/terraform-provider-azurerm#2651]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1467

Just like the above closed issue for azurerm_app_service - can we add support for disabling the insecure ftp access in Azure Function Apps?

Request for possible values would be same as the azurerm_app_service:

- AllAllowed
- FtpsOnly
- Disabled

**Comment by daveobike** [comment]
Love to see this in as security posture and audits are requiring this type of configuration for enterprise facing apps

**Comment by aqche** [comment]
Opened a PR adding the `ftps_state` option to `azurem_function_app ` 👍
