### ISSUE TITLE
unable to authenticate to azure via Service Principal

### ISSUE THREAD

**Issue by alldayanyday** [terraform-providers/terraform-provider-azurerm#2660]
I have a service account that I created in azure according to [this](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html) document.  However, after I successfully login to the service account via the azure cli and attempt to run "terraform plan", I get the below error:
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error refreshing state: 1 error(s) occurred:

* provider.azurerm: Error building AzureRM Client: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please re-authenticate using `az login`.
```
The very next command I ran after the failed "terraform plan" command was "az vm list-sizes --location westus", which successfully ran to completion, so I know that it is not an issue with authentication, especially considering I got the error just seconds after authenticating via azure cli.  It would seem that the feature to authenticate using a Service Principal is broken in the azurerm provider.  

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

# terraform -v
Terraform v0.11.11
+ provider.azurerm v1.20.0

### Affected Resource(s)

Not sure how to answer this.  Terraform is unable to authenticate with azure when there is already clearly a connection, so that is the affected resource.

* azurerm_XXXXX

### Terraform Configuration Files

Not sure how this will help, considering terraform can't even get this far into the process, but here it is anyway.

```hcl
provider "azurerm" { }

data "azurerm_resource_group" "rgroup_one" {
	name = "Box_resources"
}
data "azurerm_virtual_network" "vnet_south" {
    name = "${var.south_vnet_name}"
    resource_group_name = "${var.vnet_resource_group_name}"
}

data "azurerm_subnet" "azsubnet_south" {
    name = "${var.south_subnet_name}"
    virtual_network_name = "${var.south_vnet_name}"
    resource_group_name = "${var.vnet_resource_group_name}"
}
resource "azurerm_public_ip" "me" {
	name = "teehee"
	location = "East US"
	resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    public_ip_address_allocation = "static"
}
resource "azurerm_network_interface" "aznic_one" {
    name = "${var.nic_name}01-nic"
    resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    location = "${var.location_one}"
    ip_configuration = {
        name = "${var.ip_config}01"
        subnet_id = "${data.azurerm_subnet.azsubnet_south.id}"
        private_ip_address_allocation = "dynamic"
		public_ip_address_id = "${azurerm_public_ip.me.id}"
    }
    provisioner "local-exec" {
        command = "az network nic ip-config update -n ${var.ip_config}01 --nic-name ${var.nic_name}01-nic -g ${var.rgroup_name_one} --private-ip-address ${azurerm_network_interface.aznic_one.private_ip_address}"
    }
}
resource "azurerm_virtual_machine" "azvm_one" {
    name = "${var.vm_one}"
    location = "${var.location_one}"
    resource_group_name = "${data.azurerm_resource_group.rgroup_one.name}"
    network_interface_ids = ["${azurerm_network_interface.aznic_one.id}"]
    vm_size = "${var.vm_size}"
    delete_os_disk_on_termination = true
    license_type = "Windows_Server"
    delete_data_disks_on_termination = true
    primary_network_interface_id = "${azurerm_network_interface.aznic_one.id}"
    storage_image_reference {
        publisher = "${var.publisher}"
        offer = "${var.offer}"
        sku = "${var.sku}"
        version = "${var.version}"
    }
    storage_os_disk {
        name = "${var.disk_name}"
        caching = "ReadWrite"
        create_option = "FromImage"
        managed_disk_type = "Standard_LRS"
    }
    storage_data_disk {
        name = "${var.data_disk_name}"
        caching = "ReadWrite"
        create_option = "Empty"
        lun = 0
        disk_size_gb = 250
        managed_disk_type = "Standard_LRS"
    }
    os_profile {
        computer_name = "${var.vm_one}"
        admin_username  = "${var.admin_username}"
        admin_password = "${var.admin_password}"
    }
     os_profile_windows_config {
        provision_vm_agent        = true
        enable_automatic_upgrades = true

        additional_unattend_config {
            pass = "oobeSystem"
            component    = "Microsoft-Windows-Shell-Setup"
            setting_name = "AutoLogon"
            content      = "<AutoLogon><Password><Value>${var.admin_password}</Value></Password><Enabled>true</Enabled><LogonCount>1</LogonCount><Username>${var.admin_username}</Username></AutoLogon>"
        }
        additional_unattend_config {
            pass = "oobeSystem"
            component    = "Microsoft-Windows-Shell-Setup"
            setting_name = "FirstLogonCommands"
            content      = "<FirstLogonCommands><SynchronousCommand><CommandLine>${var.winrm_command}</CommandLine><Description>Enable winrm</Description><Order>10</Order></SynchronousCommand></FirstLogonCommands>"
        }
    }
}
output "ip" {
    value = "${azurerm_network_interface.aznic_one.private_ip_address}"
}
```

### Expected Behavior

For terraform to authenticate and build the configured infrastructure.

### Actual Behavior

It fails to authenticate. 

### Steps to Reproduce

1. Create a service principal and authenticate to azure using the service principal as described [here](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html)
2. `terraform init`
3. `terraform apply`

### References

* #0000

**Comment by hbuckle** [comment]
Hi, if you want to authenticate using a service principal you need to pass the details to the provider, either using environment variables or in the Terraform code

```hcl
provider "azurerm" {
  subscription_id = "00000000-0000-0000-0000-000000000000"
  client_id       = "00000000-0000-0000-0000-000000000000"
  client_secret   = "xxx"
  tenant_id       = "00000000-0000-0000-0000-000000000000"
}
```

If you want to authenticate using the Azure CLI you cannot use a service principal, it must be a user account

```cmd
az login --username myuser@thing.com --password xxx
```

**Comment by tombuildsstuff** [comment]
hi @alldayanyday 

As @hbuckle has mentioned authenticating using a Service Principal is only supported by defining the variables in the Provider block (or through Environment Variables) - [this guide covers how to Authenticate using a Service Principal (and a Client Secret)](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html) either by defining the details in-line or using Environment Variables.

It's also possible to use the Azure CLI to authenticate when [you're logged into the Azure CLI as a User Account](https://www.terraform.io/docs/providers/azurerm/auth/azure_cli.html) - however we do not support authenticating using the Azure CLI when you're logged in as a Service Principal (which is why you're seeing this error). Instead we support [authenticating as a Service Principal (with a Client Secret](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html) or [authenticating as a Service Principal (using a Client Certificate)](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_certificate.html) as separate authentication methods.

Since this is a question regarding Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment - however I believe [this guide should solve this issue for you](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html).

Thanks!

**Comment by jamesbannan** [comment]
@tombuildsstuff Actually I do find the behaviour of Terraform with the Azure CLI when using a Service Principal rather inconsistent. For example, if I'm using VSCode and I'm authenticated using a Service Principal with the Azure CLI, I can happily run `init`, `validate`, `plan` and `apply` and everything works as expected, using both the `azurerm` and `azuread` providers. 

But, when using an Azure CLI task in an Azure DevOps pipeline, I see the same authentication error and have to go back to passing in the credentials and account details manually, which is cumbersome.

So, the local development experience doesn't match the production deployment experience, where something that shouldn't work actually does (until you go to use it in CI/CD). And on that note, why doesn't Terraform support authenticating using a Service Principal via the Azure CLI, when this is clearly a method of interacting with Azure which is fully supported by Microsoft?

**Comment by tombuildsstuff** [comment]
@jamesbannan 

> And on that note, why doesn't Terraform support authenticating using a Service Principal via the Azure CLI, when this is clearly a method of interacting with Azure which is fully supported by Microsoft?

Unfortunately the credentials files output by the Azure CLI don't contain all of the information we need when authenticated as a Service Principal compared to when it's authenticated as a User - such that this isn't possible. I'm aware of some users exporting the Services Principal's credentials (and the additional Subscription ID's / Tenant ID's they wish to use) from the Azure CLI via a Bash/PowerShell script prior to running Terraform - which would be a potential workaround here.

**Comment by jamesbannan** [comment]
Thanks for the prompt reply @tombuildsstuff - makes sense.
