### ISSUE TITLE
Unable to set multiple environment settings in start task for batch pool

### ISSUE THREAD

**Issue by jschicht** [terraform-providers/terraform-provider-azurerm#2673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_batch_pool`

### Terraform Configuration Files

```hcl
    environment {
      KEY1 = "value1"
      KEY2 = "value2"
      
    }
```

### Actual Behavior

Running terraform apply returns;

Error: Error applying plan:

1 error(s) occurred:

* azurerm_batch_pool.test: 1 error(s) occurred:

* azurerm_batch_pool.test: Error creating Batch pool "joakimstestaccpool" (Resource Group "joakims-test-batch-rg"): batch.PoolClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPropertyValue" Message="The value provided for one of the properties in the request body is invalid.\nRequestId:24fb8aca-f432-4242-8019-38c99d148351\nTime:2019-01-15T09:02:16.8171408Z" Target="BatchAccount" Details=[{"code":"PropertyName","message":"environmentSettings"},{"code":"PropertyPath","message":"properties.startTask.environmentSettings"},{"code":"Reason","message":"Property environmentSettings has duplicate values 'KEY1'."}]

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jcorioland** [comment]
@jschicht thanks for reporting this. I am looking at this.
