### ISSUE TITLE
Latest version of resource_arm_express_route_circuit.go - removes Premium sku?

### ISSUE THREAD

**Issue by neilbailie** [terraform-providers/terraform-provider-azurerm#2687]
Hi,

The latest version of terraform-provider-azurerm/azurerm/resource_arm_express_route_circuit.go has removed premium as an available sku tier.  This is still available as a sku in the Azure portal, have Microsoft dropped this sku?

Thanks,

Neil

**Comment by tombuildsstuff** [comment]
hey @neilbailie 

Thanks for opening this issue :)

Taking a quick look into this this appears to be a bug which got introduced during the recent SDK upgrade (since the name of the Constant used for validation has changed) - I'll open a PR to fix this shortly.

Thanks!
