### ISSUE TITLE
azurerm_cosmosdb_account ip_range_filter can't be "" when try to skip

### ISSUE THREAD

**Issue by snerting** [terraform-providers/terraform-provider-azurerm#2700]
I'm creating a terraform config (let's call it config A) who is used as a module in another config (config B). 
In config A I have a optional variable who is a comma separated string (without space) contain IP addresses or IP address ranges in CIDR form.
What I want is to skip or not set value of this variable if there is no IP's as input from config B.
I tried set "" as value, but that of course not work. Also tried other values, but can't figure it out.

Is there any way to have this work or must I create two config (let's call it config A.1 and A.2) where A.1 contains the string variable, and A.2 not.

Maybe a sample code can help.

```
#Config A
resource "azurerm_cosmosdb_account" "db" {
  name                = "${var.name_from_module_caller}"
  location            = "northeuropa"
  resource_group_name = "test-cosmos-db-from-terraform"
  offer_type = "Standard"
  consistency_policy  = {
    consistency_level = "Session"
  }
  geo_location        = {
  location            = "northeuropa"
    location          = "${azurerm_resource_group.rg.location}"
    failover_priority = 0
  }
  ip_range_filter     = "${var.whitelis_ip_from_module_caller}" #Need a way to skip this, if var.whitelis_ip_from_module_caller is "". Can't use ""
}

#Config B
module "test-cosmos-db" {
  source              = "/module/azure_cosmos_module"
  name_from_module_caller = "test-cosmosdb"
  # whitelis_ip_from_module_caller //NOT SET, BECAUSE THIS MUST BE OPENED FOR EVERYONE
}
```

If ip_range_filter had been an list instead, this could easly been set to empty, so maybe that should have been used, instead of string?

**Comment by katbyte** [comment]
Hi @snerting,

Thank you for bringing this to our attention, I've opened #2713 that will allow empty strings for the ip filter
