### ISSUE TITLE
azurerm_virtual_machine_scale_set's extension's protected_settings not updated when protected_settings value changes

### ISSUE THREAD

**Issue by AtOMiCNebula** [terraform-providers/terraform-provider-azurerm#2709]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.11
+ provider.azurerm v1.21.0
```

### Affected Resource(s)

* `azurerm_virtual_machine_scale_set`
* Have not tried `azurerm_virtual_machine_extension` to see if it is affected, but it might be...?

### Terraform Configuration Files

```hcl
variable "secret" {
    type = "string"
}

resource "azurerm_virtual_machine_scale_set" "vmssExample" {
    …

    extension {
        name = "DoSomething"
        publisher = "Microsoft.Compute"
        type = "CustomScriptExtension"
        type_handler_version = "1.9"
        auto_upgrade_minor_version = true
        protected_settings = <<EXTENSIONJSON
{
    "commandToExecute": "c:\\doSomething.cmd ${var.secret}"
}
EXTENSIONJSON
    }
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

When the variable `secret` changes, I would expect Terraform to update the extension's `commandToExecute`.

### Actual Behavior

No plan is generated.

### Steps to Reproduce

1. `terraform apply` with one variable value
2. `terraform apply` with a different variable value

### Important Factoids

Nothing atypical about my environment that I can think of.

I tried debugging into the AzureRM provider to figure out what's going on here, and it's been a rollercoaster ride.  At first I thought I had a patch I could send along, but eventually convinced myself that the approach I was taking was not the right approach.

The [resourceArmVirtualMachineScaleSetExtensionHash](https://github.com/terraform-providers/terraform-provider-azurerm/blob/acc815a9a2c64404bf82ea3be73c88521cb7a5bc/azurerm/resource_arm_virtual_machine_scale_set.go#L1542) function doesn't include the `protected_settings` value in its hash calculation at all, so my very naïve approach was to add it.  This works when the state for the extension was not refreshed from live AzureRM data, but since the state frequently gets refreshed, that's a pretty big deal-breaker.  It sounds like a VMSS Extension's "protected data" is expected to not be round-trippable, so it makes sense that we don't get a copy back from the service (and presumably this is why there is no `protected_settings` handling in [flattenAzureRmVirtualMachineScaleSetExtensionProfile](https://github.com/terraform-providers/terraform-provider-azurerm/blob/acc815a9a2c64404bf82ea3be73c88521cb7a5bc/azurerm/resource_arm_virtual_machine_scale_set.go#L1434)).

So after spending a few hours in the code, I'm not sure what a good fix here is.  I've worked around it in my currently Terraform configuration by updating our extension's config block to the following:

```hcl
    extension {
        name = "DoSomething-${substr(sha512("DoSomething-{$var.secret}"), 0, 8)}"
        publisher = "Microsoft.Compute"
        type = "CustomScriptExtension"
        type_handler_version = "1.9"
        auto_upgrade_minor_version = true
        protected_settings = <<EXTENSIONJSON
{
    "commandToExecute": "c:\\doSomething.cmd ${var.secret}"
}
EXTENSIONJSON
    }
```

I'm essentially forcing the extension name to change as the secret changes, without betraying anything really interesting about the secret itself.  However, this feels like a huge kludge, and there must be a cleaner/smarter way to go about this.

So, _is_ there a cleaner/smarter way to go about this?  I'm interested in helping to write a fix, assuming that fix is relatively straightforward.

**Comment by katbyte** [comment]
Hi @AtOMiCNebula, 

Just a heads up, in v2.0 of the provider we going to be doing some work on the VMSS resource and splitting it out into two new resources, hopefully neither will exhibit this behaviour.

You can see the details in #2807 where the reasons are detailed.

**Comment by AtOMiCNebula** [comment]
Alright. I'm not blocked, since we're using the workaround I called out above.  I'm happy to help test any new versions, and to contribute a fix if need be (just need help discussing what an acceptable fix would look like). :)
