### ISSUE TITLE
Support for Azure Media Services

### ISSUE THREAD

**Issue by seushermsft** [terraform-providers/terraform-provider-azurerm#2710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To deploy Azure Media Services via Terraform, you currently have to use an ARM template, which oesn't allow Terraform to manage the actual resources that are deployed. Instead, there should be a resource of type `azurerm_media_services` that manages Azure Media Services

### New or Affected Resource(s)

* azurerm_media_services

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_resource_group" "testrg" {
  name     = "amstestrg"
  location = "westus"
}

resource "azurerm_storage_account" "testsa" {
  name                     = "amstestsa"
  resource_group_name      = "${azurerm_resource_group.testrg.name}"
  location                 = "${azurerm_resource_group.testrg.location}"
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags {
    environment = "staging"
  }
}

resource "azurerm_media_services" "ams" {

        name = "amstest"
        location = "${azurerm_resource_group.testrg.location}"
        resource_group_name = "${azurerm_resource_group.testrg.name}"
		
        storage_account {
				  id = "${azurerm_storage_account.testsa.id}"
				  is_primary = true
		    }
}
```

### References

* #0000

**Comment by Lucretius** [comment]
@tombuildsstuff looks like we can close this one

**Comment by tombuildsstuff** [comment]
@Lucretius thanks for the heads up, closing :)
