### ISSUE TITLE
azurerm_autoscale_setting fails on app_service_plan

### ISSUE THREAD

**Issue by Revolucio** [terraform-providers/terraform-provider-azurerm#2726]
### Community Note
Please vote on this issue by adding a +1 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
AzureRM 1.21.0

### Affected Resource(s)
azurerm_autoscale_setting

### Terraform Configuration Files
https://gist.github.com/Revolucio/c0151f3d9d24cfe4055628ec86f57674

### Panic Output
https://gist.github.com/Revolucio/646dd6245b0e8f0eeaecfbf91fc7e742

### Expected Behavior
It should add autoscale_setting to an app service plan

### Actual Behavior
I'm following https://www.terraform.io/docs/providers/azurerm/r/autoscale_setting.html
If I comment the rule it works, but once I add it it always fail.

### Steps to Reproduce
terraform apply

**Comment by Revolucio** [comment]
Hi,

I found that on the documentation it is said:

`metric_name        = "Percentage CPU"`

but checking on Azure templates I found that the right metric name is CpuPercentage, so 

`metric_name        = "CpuPercentage"`

works.

**Comment by metacpp** [comment]
@Revolucio Thanks for reporting this issue and share the investigation result.

This is because that different types of resources will have different naming convention even for same metric concept. I've updated the documentation to put the link shared by you.
