### ISSUE TITLE
azurerm_firewall: No option to create rule with TargetFqdn

### ISSUE THREAD

**Issue by ntdt** [terraform-providers/terraform-provider-azurerm#2748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable  to specify rule with TargetFqdn for protocol http and https

### New or Affected Resource(s)

* azurerm_firewall

### Potential Terraform Configuration

```hcl
resource "azurerm_firewall_nat_rule_collection" "test" {
  name                = "test"
  azure_firewall_name = "test"
  resource_group_name = "test"
  priority            = 100
  action              = "Destination Network Address Translation (DNAT)"

  rule {
    name = "test"
    source_addresses = [""]
    destination_ports = [""]
    destination_addresses = [""]
    translated_address = [""]
    translated_port = [""]
    protocols = ["Https",]
    target_fqdn = ""
  }
}
```

### References

* #0000

**Comment by metacpp** [comment]
@ntdt Thanks for opening this issue.

I've read the above configuration, but I could not find `azurerm_firewall_nat_rule_collection`, did you mean `azurerm_firewall_network_rule_collection` instead ?

If it's `azurerm_firewall_network_rule_collection`, according to below documentation, we don't support `target_fqdn` and we only support `Any, ICMP, TCP and UDP` as protocols.
https://www.terraform.io/docs/providers/azurerm/r/firewall_network_rule_collection.html

**Comment by hbuckle** [comment]
@ntdt You should be able to use `azurerm_firewall_application_rule_collection` with fqdn tags. It was added in `1.21.0` but hasn't shown up on the documentation site yet. As noted NAT rules haven't been added yet.

```hcl
resource "azurerm_firewall_application_rule_collection" "test" {
  name                = "acctestarc"
  azure_firewall_name = "${azurerm_firewall.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  priority            = 100
  action              = "Allow"

  rule {
    name = "rule1"

    source_addresses = [
      "10.0.0.0/16",
    ]

    fqdn_tags = [
      "<tag name>",
    ]

    protocol {
      port = 443
      type = "Https"
    }
  }
}
```

**Comment by ntdt** [comment]
@hbuckle Thanks for the information. I'm waiting for the documentation update to user fqdn_tags.
