### ISSUE TITLE
azurerm_signalr_service doesn't properly handle SignalR SKU types

### ISSUE THREAD

**Issue by egorchabala** [terraform-providers/terraform-provider-azurerm#2749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.11.3
* provider.azurerm v1.21.0

### Affected Resource(s)

* `azurerm_signalr_service`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "terraform-signalr-test"
  location = "West US"
}

resource "azurerm_signalr_service" "free" {
  count = 5
  name                = "tfex-signalr-free${count.index + 1}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    name     = "Free_F1"
    capacity = 1
  }
}

resource "azurerm_signalr_service" "standard" {
  name                = "tfex-signalr-standard"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    name     = "Standard_S1"
    capacity = 1
  }

  depends_on = ["azurerm_signalr_service.free"]
}


provider "azurerm" {
    version = "= 1.21"
}

terraform {
    required_version = "= 0.11.3"
}
```

### Expected Behavior

Assume you have 5 SignalR resources with Free tier (Free_F1) in one region. This is a maximum number of Free SKU SignalR units according to [Microsoft docs](https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/signalr-service-limits.md).
Now you want to create additional SignalR resource with Standard tier (Standard_S1) in the same region as other 5 Free tier units. 
Expected behavior: Terraform creates additional SignalR resource with Standard tier.

### Actual Behavior

Terraform execution fails with the following error

> azurerm_signalr_service.standard: Error creating or updating SignalR "tfex-signalr-standard" (Resource Group "terraform-signalr-test"): signalr.Client#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadArgument" Message="/subscriptions/<subscription_id>/providers/Microsoft.SignalRService/locations/westus/usages/FreeTierInstances cannot have more than 5 SignalR services of Free tier."

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
@JunyiYi would you be able to take a look into this?

**Comment by JunyiYi** [comment]
Hi @egorchabala , thanks for reporting the issue. To let the service team diagnostic your issue, do you mind sharing your subscription ID with me through junyi@microsoft.com?

**Comment by egorchabala** [comment]
> Hi @egorchabala , thanks for reporting the issue. To let the service team diagnostic your issue, do you mind sharing your subscription ID with me through [junyi@microsoft.com](mailto:junyi@microsoft.com)?

Done.

**Comment by JunyiYi** [comment]
Thanks @egorchabala for the quick response. The service team is working on a fix which is expected to be realeased in about two weeks.

**Comment by egorchabala** [comment]
Hi @JunyiYi do you have any updates from MS side?

**Comment by tombuildsstuff** [comment]
@JunyiYi is there a Rest API Specs issue for this?

**Comment by JunyiYi** [comment]
Hi @egorchabala @tombuildsstuff , I can confirm the issue has been fixed. Thanks.

![image](https://user-images.githubusercontent.com/6908392/57262905-277a3f00-7023-11e9-9986-fca5cb6969ae.png)
