### ISSUE TITLE
Terraform does not wait for resource groups to be created

### ISSUE THREAD

**Issue by VNDCK** [terraform-providers/terraform-provider-azurerm#2754]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
+ Terraform v0.11.11
+ provider.azurerm v1.21.0

### Affected Resource(s)

* `azurerm_resource_group`

### Terraform Configuration Files

**main.tf - root**
```hcl
module "resource_group" {
	source = "/modules/resource_group"

	resourceGroup_name = "TerraformRG"
	resourceGroup_location = "West Europe"
}

module "virtual_network" {
	source = "/modules/virtual_network"

	resourceGroup_name = "${module.resource_group.resourceGroup_name}"
	resourceGroup_location = "${module.resource_group.resourceGroup_location}"
	virtualNetwork_name = "virtualNetwork_00"
	virtualNetwork_vnet = ["10.10.0.0/16"]
	virtualSubnet_name = "virtualNetworkSubnet_00"
	virtualSubnet_snet	=  "10.10.0.0/24"
} 
```
**main.tf - Resource Group Module**
```hcl
resource "azurerm_resource_group" "ResourceGroup" {
  	name     = "${var.resourceGroup_name}"
	location = "${var.resourceGroup_location}"

	tags {
		environment  = "Production"
		deployment  = "Terraform"
  	}	
}
```
**outputs.tf - Resource Group Module**
```hcl
output "resourceGroup_name" {
	value = "${azurerm_resource_group.ResourceGroup.name}"
}

output "resourceGroup_location" {
	value = "${azurerm_resource_group.ResourceGroup.location}"
}
```
**vars.tf - Resource Group Module**
```hcl
variable "resourceGroup_name" {
	description = "The name of the Resource Group"
}
variable "resourceGroup_location" {
	description = "Location of the Resource Group"
}
```

**main.tf - Virtual Network Module**
```hcl
resource "azurerm_virtual_network" "virtualNetwork" {
	name  = "${var.virtualNetwork_name}"
	location = "${var.resourceGroup_location}"
	resource_group_name = "${var.resourceGroup_name}"
	
	address_space = "${var.virtualNetwork_vnet}"

    tags {
        environment = "Production"
	deployment = "Terraform"
    }
}

## Subnet aanmaken
resource "azurerm_subnet" "virtualSubnet" {
	resource_group_name = "${var.resourceGroup_name}"
	
	name  = "${var.virtualSubnet_name}"
	virtual_network_name = "${var.virtualNetwork_name}"
	address_prefix  =  "${var.virtualSubnet_snet}"
}
```

**vars.tf - Virtual Network Module**
```hcl
variable "resourceGroup_name" {}
variable "resourceGroup_location" {}
variable "virtualNetwork_name" {}
variable "virtualNetwork_vnet" {
    type = "list"
}
variable "virtualSubnet_name" {}
variable "virtualSubnet_snet" {}

```

### Debug Output

```hcl
Error: Error applying plan:

1 error(s) occurred:

* module.virtual_network.azurerm_virtual_network.virtualNetwork: 1 error(s) occurred:

* azurerm_virtual_network.virtualNetwork: Error waiting for completion of Virtual Network "virtualNetwork_00" (Resource Group "TerraformRG"): Code="Canceled" Message="Operation was canceled." Details=[{"code":"CanceledAndSupersededDueToAnotherOperation","message":"Operation PutVirtualNetworkOperation (2efa0d54-383c-4112-8dec-116a9c3f191f) was canceled and superseded by operation PutSubnetOperation (e367ce6f-49d3-454d-ad5a-99d5400a00e3)."}]
```

### Expected Behavior

Creation of a resource group and a virtual network in that resource group.

### Actual Behavior

Resource group got created but it fails on the virtual network. When applying again, it continues creating the virtual network.

### Steps to Reproduce

1. `terraform apply`
2. `Error 404`
3. `terraform apply`
4. `Done!`

**Comment by dougmacqueen** [comment]
On your subnet resource, dont use the network name variable, use the name output.
Change virtual_network_name on the subnet resource to "${azurerm_virtual_network.virtualNetwork.name}".

This should create a dependency so that network is complete before subnet tries to create itself.

**Comment by tombuildsstuff** [comment]
hey @VNDCK

Just to add a little more background to what @dougmacqueen has said here - Terraform doesn't determine dependencies between resources itself, instead you need to 'hint' to it using either an Implicit Dependency (using [the Interpolation Syntax](https://www.terraform.io/docs/configuration-0-11/interpolation.html), as shown above) or an [Explicit Dependency using the `depends_on` parameter](https://www.terraform.io/docs/configuration-0-11/resources.html#explicit-dependencies).

In general we'd recommend using the Interpolation Syntax where possible since this means Terraform is able to infer the dependencies without tracking them yourself, as is the case with the `depends_on` parameter.

Since this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding).

Thanks!

**Comment by VNDCK** [comment]
Thank you very much!
