### ISSUE TITLE
Public ip for dev test lab windows vm

### ISSUE THREAD

**Issue by alldayanyday** [terraform-providers/terraform-provider-azurerm#2779]
So, quick question specifically regarding the azurerm provider. I am trying to create a dev test lab containing a lab network (which allows
for the use of public ips), and one windows vm. In fact, to test it out, I just copied and pasted the example provided in the documentation on the below page, and only fixed the "gallery_image_reference" section:
https://www.terraform.io/docs/providers/azurerm/r/dev_test_windows_virtual_machine.html
My question has to do specifically with how I would go about obtaining/assigning a public ip address that would actually allow access to the vm. Terraform does not appear to generate a public IP for the dev test lab network.  Tried asking this question in the community gitter, and only posted here after 2 days of being ignored.

![error](https://i.imgur.com/CLKybZp.png)

## Terraform config file

```hcl
provider "azurerm" {

}

resource "azurerm_resource_group" "test" {
  name     = "devtestlab"
  location = "East US"
}

resource "azurerm_dev_test_lab" "test" {
  name                = "vm-devopslab"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_dev_test_virtual_network" "test" {
  name                = "devtestnetwork"
  lab_name            = "${azurerm_dev_test_lab.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  subnet {
    use_public_ip_address           = "Allow"
    use_in_virtual_machine_creation = "Allow"
  }
}

resource "azurerm_dev_test_windows_virtual_machine" "test" {
  name                   = "devvm01"
  lab_name               = "${azurerm_dev_test_lab.test.name}"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  location               = "${azurerm_resource_group.test.location}"
  size                   = "Standard_D3_v2"
  username               = "abl"
  password               = "eNYfsA4q91k76yQ"
  lab_virtual_network_id = "${azurerm_dev_test_virtual_network.test.id}"
  lab_subnet_name        = "${azurerm_dev_test_virtual_network.test.subnet.0.name}"
  storage_type           = "Premium"
  notes                  = "First machine"

  gallery_image_reference {
    offer     = "WindowsServer"
    publisher = "MicrosoftWindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }
}
```

**Comment by dpnl87** [comment]
Hi @alldayanyday,

Microsoft Azure has a nice documentation page that provides examples that will get you going. Have a look at https://docs.microsoft.com/en-us/azure/virtual-machines/linux/terraform-create-complete-vm

It seems like to need to add the `azurerm_public_ip` resource. Please note you also need to add a `azurerm_network_security_group` for safety.

Example
```
# Create public IPs
resource "azurerm_public_ip" "myterraformpublicip" {
    name                         = "myPublicIP"
    location                     = "eastus"
    resource_group_name          = "${azurerm_resource_group.myterraformgroup.name}"
    public_ip_address_allocation = "dynamic"

    tags {
        environment = "Terraform Demo"
    }
}

# Create Network Security Group and rule
resource "azurerm_network_security_group" "myterraformnsg" {
    name                = "myNetworkSecurityGroup"
    location            = "eastus"
    resource_group_name = "${azurerm_resource_group.myterraformgroup.name}"

    security_rule {
        name                       = "SSH"
        priority                   = 1001
        direction                  = "Inbound"
        access                     = "Allow"
        protocol                   = "Tcp"
        source_port_range          = "*"
        destination_port_range     = "22"
        source_address_prefix      = "*"
        destination_address_prefix = "*"
    }

    tags {
        environment = "Terraform Demo"
    }
}

# Create network interface
resource "azurerm_network_interface" "myterraformnic" {
    name                      = "myNIC"
    location                  = "eastus"
    resource_group_name       = "${azurerm_resource_group.myterraformgroup.name}"
    network_security_group_id = "${azurerm_network_security_group.myterraformnsg.id}"

    ip_configuration {
        name                          = "myNicConfiguration"
        subnet_id                     = "${azurerm_subnet.myterraformsubnet.id}"
        private_ip_address_allocation = "dynamic"
        public_ip_address_id          = "${azurerm_public_ip.myterraformpublicip.id}"
    }

    tags {
        environment = "Terraform Demo"
    }
}

```

**Comment by alldayanyday** [comment]
@dpnl87 ..  Ok....  So I see how the code snippet would apply when building a regular vm...  However, I am trying to build a dev lap windows vm.  In a windows dev lab, the network and subnet that is used for the vm are dev lab resources within terraform specifically.  You can find the documentation for these resources below:
https://www.terraform.io/docs/providers/azurerm/r/dev_test_virtual_network.html
https://www.terraform.io/docs/providers/azurerm/r/dev_test_windows_virtual_machine.html

Therefore, given the arguments that these resources accept, can you please explain how one would go about assigning a public ip address to a **dev lab test windows virtual machine.**

**Comment by alldayanyday** [comment]
@dpnl87 Any feedback would be really appreciated as to how I can assign a public ip to a **dev lab test windows virtual machine** would be really appreciated.....

**Comment by paultyng** [comment]
Hello @alldayanyday - Please note that you have previously been restricted from contributing to HashiCorp repositories under your alias account @whiggs due to continued violations of our [Code of Conduct](https://www.hashicorp.com/community-guidelines).

Attempts to create additional accounts to bypass this restriction are also in violation of our community guidelines.  As such, we regret to inform you that this account has also been restricted effective immediately.

If you feel this has been done in error or would like to discuss a reasonable alternative, please contact us at any time at security@hashicorp.com and we will be happy to help you.
