### ISSUE TITLE
Incorrect casing for SKU name values in azurerm_key_vault documentation

### ISSUE THREAD

**Issue by stijnherreman** [terraform-providers/terraform-provider-azurerm#2780]
[The documentation for azurerm_key_vault](https://www.terraform.io/docs/providers/azurerm/r/key_vault.html) says:

> A `sku` block supports the following:
> 
> * `name` - (Required) The Name of the SKU used for this Key Vault. Possible values are `Standard` and `Premium`.

The values must be lowercase: `standard` and `premium`. Using incorrect casing results in an error:

> Error: azurerm_key_vault.default: expected sku.0.name to be one of [standard premium], got Standard

**Comment by katbyte** [comment]
Hi @stijnherreman,

Thanks for letting us know about the error, i've opened #2790 that will fix it 🙂

**Comment by stijnherreman** [comment]
Thanks @katbyte. I wasn't sure if only the markdown files needed to be changed for documentation changes. I'll submit PRs for any other issues I find :)
