### ISSUE TITLE
boot_diagnostics enabling keeps adding a forward slash to the path, causing a diff every apply

### ISSUE THREAD

**Issue by stonefury** [terraform-providers/terraform-provider-azurerm#2796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_account`
* `azurerm_virtual_machine`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
boot_diagnostics_sa           = "${azurerm_storage_account.coldblobsqldmz.primary_blob_endpoint}"
```

### Debug Output

https://gist.github.com/stonefury/1513f7b9f379aa8c9da3f9677bf490b9

### Expected Behavior

Once I run apply and enable boot diagnostics, I would expect subsequent terraform applys to not detect a change. 

### Actual Behavior

Every apply finds the same difference. Seems to be relate to the trailing forward slash that shows up as the difference

 ~ module.vms_dmz_sqldmz.module.SQLDMZ2.azurerm_virtual_machine.vm-windows-with-datadisk
      boot_diagnostics.0.storage_uri: "https://coldblobsqldmzdr77aa.blob.core.windows.net" => "https://coldblobsqldmzdr77aa.blob.core.windows.net/"

https://coldblobsqldmzdr77aa.blob.core.windows.net
https://coldblobsqldmzdr77aa.blob.core.windows.net/ (tf finds the trailing slash as a diff)

### Steps to Reproduce

1. `terraform apply`

### References

I create my VM with a module I modified frmo microsoft. I have this code that enables boot diagnostics only if the user passes a value for boot_diagnostics.  But I don't see how this would add a forward slash.

  boot_diagnostics {
    enabled     = "${length(var.boot_diagnostics_sa) > 0 ? "true" : "false" }"
    storage_uri =  "${length(var.boot_diagnostics_sa) > 0 ? var.boot_diagnostics_sa : "" }"
  }

* #0000

**Comment by katbyte** [comment]
Hi @stonefury,

Sorry that your having this issue. The root cause here is that `azurerm_storage_account.primary_blob_endpoint` property is returning the value with a /, and the `boot_diagnostics` is returning it with the / stripped. I don't believe terraform is doing anything incorrectly here.

The module you have modified could be altered to strip away the / as such:
```
[14:39:27] kt@snowbook:~/hashi/gh/az-2796$ cat main.tf
locals {
  url = "http://kt.example.me/"
}

output "address" {
  value = "${substr(local.url,0,length(local.url)-1)}"
}
[14:39:35] kt@snowbook:~/hashi/gh/az-2796$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

address = http://kt.example.me
[14:39:36] kt@snowbook:~/hashi/gh/az-2796$
```

**Comment by tombuildsstuff** [comment]
hey @stonefury 

Since we've not heard back from you here I'm going to close this issue for the moment - however if the workaround proposed by @katbyte doesn't work for you please let us know and we'll take another look :)

Thanks!

**Comment by stonefury** [comment]
It's a fine workaround. Thanks.
