### ISSUE TITLE
PostgreSQL replica support

### ISSUE THREAD

**Issue by jay7x** [terraform-providers/terraform-provider-azurerm#2819]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft introduced PostgreSQL read replica support in Azure just recently. It'd be great to be able to manage them using Terraform!

There are my (semi-random) ideas about this. Please note I'm not TF developer so I'm unsure about style guidelines.. So please consider this as roughly draft or RFC.

* I was able to set `azure.replication_support=REPLICA` using `azurerm_postgresql_configuration` w/o any issues. So this step is already done. But this step requires server restart when changing pre-existing server. For newly created server restart it's not required **I guess** (depends on how those settings are applied to server).

* Replica is kind of yet another PostgreSQL server instance. So it should be possible to reuse current `azurerm_postgresql_server` for this from one side. But from other side replica means relation with master instance which should be described somehow. May be AWS RDS provider may give some ideas (didn't read it yet).

* It's impossible to change replica pricing tier, compute generation, vCores, storage and backup retention period during replica creation. It will be created as copy of master. But it's possible to change those params after creation independently.

* I'm not sure how to deal with role switchover. It's possible to break replication and promote replica to master in Azure portal. But I'm unsure how to describe this action in terms of "Configuration as a Code".

### New or Affected Resource(s)

* azurerm_postgresql_configuration
* azurerm_postgresql_server

May be we will need new resource to manage this. Can't propose anything here yet.

### Potential Terraform Configuration

```hcl
// To be defined
```

### References

* https://docs.microsoft.com/en-us/azure/postgresql/concepts-read-replicas
* https://docs.microsoft.com/en-us/azure/postgresql/howto-read-replicas-portal

**Comment by tobyhersey** [comment]
i've have also recently encountered this limitation when trying to add replica support

**Comment by cwebbtw** [comment]
This would certainly be useful given read replica support in multiple locations now being available.

**Comment by booyaa** [comment]
Until support has been added to the provider I’ve created a module that achieved this via azure cli and the local-exec provisioner. Any feedback is welcome! https://registry.terraform.io/modules/booyaa/postgresql-read-replica/azurerm

**Comment by cwebbtw** [comment]
It may be worth using `when    = "destroy"` to take care of the destruction of the read-replica.

**Comment by booyaa** [comment]
Should we handle breaking replication? This turns the replica into a primary server i.e. stand-alone. Might be interesting how other providers handle this.

**Comment by booyaa** [comment]
I've been thinking about this feature and was wondering if we could borrow a leaf out of the AWS [provider](https://www.terraform.io/docs/providers/aws/r/db_instance.html#replicate_source_db) and extend the `azurem_postgresql_server` to include a new argument `source_server`.

So to create a new read replica, you could do the following:

```hcl
resource "azurerm_resource_group" "test" {
  name                = "api-rg-pro"
  location            = "West Europe"
}

resource "azurerm_postgresql_server" "source" {
  name                = "postgresql-server-1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  ...
}

resource "azurerm_postgresql_server" "read-replica" {
  name                = "postgresql-server-rr"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  source_server       = "${azurerm_postgresql_server.source.name}"
...
}
```

**Comment by ma3u** [comment]
How is the status of this Terraform feature? Our partner and customer need to build-up a PostgreSQL cluster 

As I understood the Terraform Azure provider is built on Azure CLI. Create and manage read replicas from the Azure CLI, REST API is available already:

https://docs.microsoft.com/en-us/azure/postgresql/howto-read-replicas-cli

az postgres server configuration set 
--resource-group myresourcegroup 
--server-name mydemoserver 
--name azure.replication_support 
--value REPLICA


az postgres server replica create 
--name mydemoserver-replica 
--source-server mydemoserver 
--resource-group myresourcegroup


@tombuildsstuff: Do you have a plan for this Azure Provider feature already?
