### ISSUE TITLE
Iot Hub resource definition doesn't have device-to-cloud partitions settings

### ISSUE THREAD

**Issue by darthkurak** [terraform-providers/terraform-provider-azurerm#2821]
Hi! When creating IoT Hub resource in Azure in portal or Azure CLI we have ability to set device-to-cloud partitions. Default is 4, and we can setup this to 32. This is something that cannot be change after creation.
This is really important setting if we are talking about high throughput applications.
Unfortunately there is not equivalent in Terraform. As this setting cannot be changed later, the whole provisioning IoT hub with Terraform doesn't make sense - if we want this value different than default.
Please, add this one :)  

Terraform Resource:
azurerm_iothub

Example of potential configuration:

```
resource "azurerm_iothub" "test" {
  name                = "test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  sku {
    name     = "S1"
    tier     = "Standard"
    capacity = "1"
    device-to-cloud_partitions = "32"
  }
}
```

**Comment by msjonathan** [comment]
We are experiencing the same issue - as you can't update the partitions after creation.
