### ISSUE TITLE
Add setting for certificates on batch pool

### ISSUE THREAD

**Issue by jschicht** [terraform-providers/terraform-provider-azurerm#2822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On the Batch pool it would be good to have the option of configuring certificates.

### New or Affected Resource(s)

* azurerm_batch_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_batch_pool" "test" {
  certificates {
    certname1 {
      certificate = "path-to-cert"
      store_name = ""
      store_location = ""
      visibility = ""
	  }
  }
}
```

### References

* #0000

**Comment by stuartleeks** [comment]
Currently working on this. Have a crude implementation in place, now refining and adding tests/docs
