### ISSUE TITLE
Provision Web App for Containers

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-azurerm#2827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Azure Web App for Containers](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-multi-container-app#create-an-azure-app-service-plan) are really cool, and I think it would be awesome if this provider supported them!

As far as I can tell, the CLI [handles creating them with a couple of extra flags](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create). Basically, you do 
```sh
az webapp create <other required params> --deployment-container-image-name <image>
```
to create a single-container app service, and
```sh
az webapp create <other required params> --multicontainer-config-type COMPOSE --multicontainer-config-file <path-to-docker-compose>
az webapp create <other required params> --multicontainer-config-type KUBE --multicontainer-config-file <path-to-kubernetes-definition>
```
to create a multi-container app. However, I haven't been able to figure out whether - and, if it does, how - the Azure SDK for Go supports this yet.

Interestingly, if I create the service plan and web app using the CLI, according to the instructions linked above, I can then import them into my Terraform state and have the following configurations propose no changes:

```sh
az group create --name my-rg --location "West Europe"
az appservice plan create --name my-svc-plan --resource-group my-rg --sku S1 --is-linux
az webapp create --resource-group my-rg --plan my-svc-plan --name a-globally-unique-name --multicontainer-config-type compose --multicontainer-config-file a-compose-file-on-disk.yml
```
```hcl
resource "azurerm_app_service" "app" {
  name = "a-globally-unique-name"
  resource_group_name = "my-rg"
  location = "westeurope"
  app_service_plan_id = "${azurerm_app_service_plan.svcplan.id}"
}
resource "azurerm_app_service_plan" "svcplan" {
  name = "my-svc-plan"
  resource_group_name = "my-rg"
  location = "westeurope"
  sku = {
    tier = "Standard"
    size = "S1"
  }

  kind = "linux"
}
resource "azurerm_resource_group" "rg" {
  name = "my-rg"
  location = "westeurope"
}
```

### New or Affected Resource(s)

* azurerm_app_service

**Comment by tomasaschan** [comment]
As a workaround, I just figured out I can do this:

```
  provisioner "local-exec" {
    command     = "echo version: '3' > docker-compose.yml && echo 'services:' >> docker-compose.yml && az webapp config container set --ids ${azurerm_app_service.frontend.id} --multicontainer-config-type='COMPOSE' --multicontainer-config-file='docker-compose.yml'"
    interpreter = ["bash", "-c"]
  }
```
It feels hacky and brittle, though... :)

**Comment by tomasaschan** [comment]
@Djiit Nice! I came back here to write that I'd found that out too :)

I'm currently using the following config:

```
  site_config = {
    # ...
    linux_fx_version = "COMPOSE|${base64encode("version: '3'\nservices:\n")}"
  }

  lifecycle {
    ignore_changes = [
      "site_config.0.linux_fx_version", # will be updated with every deployment
    ]
  }
```
The `lifecycle` annotation is nice because it lets me update the Docker Compose file from my deployment pipelines using the Azure CLI without Terraform being confused next time I want to apply infrastructure changes.

**Comment by jnancel** [comment]
@Djiit Would be great if that could be documented here : https://www.terraform.io/docs/providers/azurerm/r/app_service.html#

A specific example usage for containers would also be great, like what exists for .net and Java.

But it's already great enough that it's supported.

**Comment by Djiit** [comment]
I agree with you, I've already been contacted by a team member to enhance
the docs. I hope it gets updated soon !

--
Julien

**Comment by tombuildsstuff** [comment]
hi @tomasaschan @Djiit @jnancel 

Thanks for opening this issue :)

Just to let you know that I've added some examples for using Containers within an App Service in #2913 which should help clarify this.

Thanks!
