### ISSUE TITLE
Azure test dev lab public ip

### ISSUE THREAD

**Issue by alldayanyday** [terraform-providers/terraform-provider-azurerm#2829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

So I am upgrading my previous question #2779 to a bug, as not only did the supplied answer not relate to the azure resource that the question was about, but I have also found another recent issue which was somewhat similar to mine.  I am trying to create a **dev test lab** containing a **dev test lab** network (which allows for the use of public ips), and one **dev test lab** windows vm.  In fact, to test it out, I just copied and pasted the example provided in the documentation on the below page, and only fixed the "gallery_image_reference" section:
https://www.terraform.io/docs/providers/azurerm/r/dev_test_windows_virtual_machine.html
Terraform does not appear to generate a public IP for the **dev test lab** network:
![image](https://user-images.githubusercontent.com/27664871/52140396-b3458f00-2620-11e9-8d97-41b84e3834dd.png)

The response that I got for my previous issue makes me think the post was not read, as it details how to create a public ip for a regular azure network/nic, rather than a **dev test lab** resource, so I will attempt to more accurately communicate that this is about **dev test labs.**  Specifically, the **dev test lab** network, even when public ip is set to allow, does not generate a public ip to actually access any of the **dev test lab** windows vms which are connected to the **dev test lab** network. 

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v0.11.11
+ provider.azurerm v1.20.0

### Affected Resource(s)

azurerm_dev_test_lab
azurerm_dev_test_virtual_network
azurerm_dev_test_windows_virtual_machine

### Terraform Configuration Files

Like I said, if you change the "gallery_image_reference" section so that it references a windows vm, the example provided on the below doc page is a perfect example:
https://www.terraform.io/docs/providers/azurerm/r/dev_test_windows_virtual_machine.html

```hcl
provider "azurerm" {}

resource "azurerm_resource_group" "test" {
  name     = "devtestlab"
  location = "East US"
}

resource "azurerm_dev_test_lab" "test" {
  name                = "vm-devopslab"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_dev_test_virtual_network" "test" {
  name                = "devtestnetwork"
  lab_name            = "${azurerm_dev_test_lab.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  subnet {
    use_public_ip_address           = "Allow"
    use_in_virtual_machine_creation = "Allow"
  }
}

resource "azurerm_dev_test_windows_virtual_machine" "test" {
  name                   = "devvm01"
  lab_name               = "${azurerm_dev_test_lab.test.name}"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  location               = "${azurerm_resource_group.test.location}"
  size                   = "Standard_D3_v2"
  username               = "grr"
  password               = "nothing here"
  lab_virtual_network_id = "${azurerm_dev_test_virtual_network.test.id}"
  lab_subnet_name        = "${azurerm_dev_test_virtual_network.test.subnet.0.name}"
  storage_type           = "Premium"
  notes                  = "First machine"

  gallery_image_reference {
    offer     = "WindowsServer"
    publisher = "MicrosoftWindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }
}
```

### Expected Behavior

Public ips for the **dev test lab** windows vms would be created.  

### Actual Behavior

![image](https://user-images.githubusercontent.com/27664871/52141068-99a54700-2622-11e9-895e-6db111840007.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @alldayanyday 

Since this questions also been asked in #2779 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #2779 where we'll answer this.

Thanks!
