### ISSUE TITLE
Web App Logging

### ISSUE THREAD

**Issue by JoeHitchenXtract** [terraform-providers/terraform-provider-azurerm#2835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Web apps have a number of logging options, some of which can be accessed via the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az-webapp-log-config) but which are not available through Terraform.
Configuring a web app to put logs in a storage account would be a prime target for Terraforming, but this does not yet appear to be configurable via the CLI.

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @JoeHitchenXtract 

Thanks for opening this issue :)

Support for adding logging functionality to App Services has previously been requested in #2835 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that issue; would you mind subscribing to that issue for updates?

Thanks!

**Comment by JoeHitchenXtract** [comment]
Hi @tombuildsstuff 
The issue you've linked to is the issue in hand. Did you mean to link to a different one?
Joe

**Comment by JoeHitchenXtract** [comment]
Ah cheers, I'll subscribe to that one! I must have missed it in my search before :/
