### ISSUE TITLE
Existing storage containers may not be listed using a single ListContainers call

### ISSUE THREAD

**Issue by davidwisch** [terraform-providers/terraform-provider-azurerm#2843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.11.11
+ provider.azurerm v1.21.0
```

### Affected Resource(s)

* `azurerm_storage_container`

### Expected Behavior

When running `terraform plan` or `terraform apply`, the list of containers to create accurately represents the difference between the resources that exist in Azure the the desired state.

### Actual Behavior

Depending on how data is partitioned in Azure, the ARM provider can calculate that it should create storage containers that already exist.

### Steps to Reproduce

Reproducing this depends on how data is partitioned in Azure. Anecdotally, most of the time a single "list container" operation (what the ARM provider does today) with the subject container as the search prefix, will return the expected results (a list of 0+ containers, one of which will be the container we're looking for). However, depending how the data is partitioned it's possible that a single `ListContainers` call will return zero results for an existing container, but also include a `NextMarker` token which if used as the marker in subsequent `ListContainers` queries would return a list including the subject container.

If data happens to be partitioned in the way I describe above, it has the effect of terraform reporting that it should create containers that already exist.

The partition splits and merges are automatically performed by Azure in response to changes in load/request volume, so the results of a single `ListContainers` query may change over time.

Here's an example request/response using `curl`:

```
$ curl -SsL -H "x-ms-version: 2017-11-09" -H "x-ms-date: [TIMESTAMP]" "https://[ACCOUNT].blob.core.windows.net/?comp=list&prefix=[CONTAINER_NAME]&timeout=90&[SAS TOKEN]" | xq
<EnumerationResults ServiceEndpoint="https://[ACCOUNT].blob.core.windows.net/">
  <Prefix>[CONTAINER NAME]</Prefix>
  <Containers/>
  <NextMarker>[NEXT MARKER VALUE]</NextMarker>
</EnumerationResults>
```

As you can see, no containers were returned, but a `NextMarker` was provided. Using the value of `NextMarker` as the `&marker=[NextMarker]` query parameter returns additional containers that match the original prefix criteria.

### Potential Solutions

I believe that roughly lines [166 through 186](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.21.0/azurerm/resource_arm_storage_container.go#L166) of `resource_arm_storage_container.go` is where the problem is. Here are some ideas for what a solution might look like:

1. The `ListContainers` call should be called repeatedly until (a) we find the container we're looking for,  (b) we encounter a container that sorts after the container of interest (indicating a prefix match but not the container we want), or (c) a truly empty list (no `NextMarker`) indicating the container doesn't exist.
1. Use a different method to determine the existence of a container, perhaps using the return code from the get container properties operation.

### References

* The possibility of a partition triggering the presence of `NextMarker` is mentioned in the REST docs for the container list operation
  * https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2
* The splitting and merging behavior of RangePartitions is explained in this paper from Microsoft
  * https://sigops.org/s/conferences/sosp/2011/current/2011-Cascais/printable/11-calder.pdf

// cc @shraboin (Microsoft engineer who helped explain the behavior)

**Comment by shraboin** [comment]
Azure support ticket associated with this is SR: 119020424003235
