### ISSUE TITLE
Joining multiple servers to AD domain with VM Extension in Azure?

### ISSUE THREAD

**Issue by bostrowski13** [terraform-providers/terraform-provider-azurerm#2844]
Wondering if there is a way to join multiple VMs do a Active Directory domain using an VM Extension in Azure. 

Trying to connect to traditional AD DCs, not Azure AD.  

Extension works great for 1 server, but the moment you pass in more than 1, failure with the below error.

Error: Error applying plan:

1 error(s) occurred:

* module.vm_domain_join.azurerm_virtual_machine_extension.domjoinextn: 1 error(s) occurred:

* azurerm_virtual_machine_extension.domjoinextn: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'server01,server02,server03' not found."

**Comment by ghostinthewires** [comment]
Hi,

My example might help. Here I am joining multipe servers to AD domain using count:

https://github.com/ghostinthewires/Terraform-Templates/tree/master/Azure

Thanks

**Comment by OffColour** [comment]
Offering unsolicited advice here, but you might find it better in the long run to start using an Automation account with DSC to do this if you have other Windows specific configurations you want to use post build.

**Comment by bostrowski13** [comment]
@OffColour  actually i found this to work great after reviewing @ghostinthewires solution.  

i (for some reason) didn't realize the resource supported the count param, and now this works well.

**Comment by bostrowski13** [comment]
Just wanted to share 1 thing I came across.  I hit a snag in my ordering where I was trying to create a set of VMs and this wasn't waiting on the creation of those VMs before trying to join to the domain.  In order to help with ordering in my manifest, I am passing in the output of my VM creation module to this and creating a list from that and using each of those in the creation.  This solves my ordering problem.

`
locals {
  type            = "JsonADDomainExtension"
  publisher       = "Microsoft.Compute"
  handler_version = "1.3"
  vm_list         = "${split(",", var.vm_name)}"
}

resource "azurerm_virtual_machine_extension" "domjoinextn" {
  name                       = "${element(local.vm_list, count.index)}-domainjoin"
  location                   = "${var.location}"
  resource_group_name        = "${var.resource_group_name}"
  virtual_machine_name       = "${element(local.vm_list, count.index)}"
  publisher                  = "${local.publisher}"
  type                       = "${local.type}"
  type_handler_version       = "${local.handler_version}"
  auto_upgrade_minor_version = true
  count                      = "${var.instance_count}"
`

**Comment by ghostinthewires** [comment]
Thanks for sharing.

You could also use the "depends on" to help with ordering
