### ISSUE TITLE
CORS settings for App Service

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-azurerm#2848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `azurerm_app_service` object does currently not support [editing CORS settings](https://docs.microsoft.com/en-us/cli/azure/webapp/cors?view=azure-cli-latest), and I can't find any issues that cover this. Are there any plans to implement this that have not been logged yet? If not, I might take a stab at implementing it (the SDK has support for it, so it should be pretty straightforward).

### New or Affected Resource(s)

* `azurerm_app_service` (both resource and data source)

### Potential Terraform Configuration

I imagine something like this:
```hcl
resource "azurerm_app_service" {
  # name, resource_group etc

  cors = {
    allowed_origins     = ["http://foo.bar", "http://baz"] # default empty
    support_credentials = true                             # default false
  }
}    
```

### References

* There's an open issue for the same thing in function apps, #1374, and one for blob storage, #19, but those are orthogonal to this one.

**Comment by joakimhew** [comment]
@tomasaschan Unfortunately Microsoft does support setting the `support_credentials` property through their SDK as of now. There is however support for `allowed_origins`, so I might look into this in the upcoming days and add a PR for that!

@katbyte Should we perhaps move `support_credentials` into a new issue and label it label it with `upstream-microsoft`?

**Comment by tomasaschan** [comment]
@joakimhew @tombuildsstuff Are you sure it's missing? I haven't looked that closely, but there's at least a reference to it in [services\web\mgmt\2018-02-01\web\models.go (line 6898) in the SDK](https://github.com/Azure/azure-sdk-for-go/tree/master/services/web/mgmt/2016-09-01/web/models.go#L6898) that indicates it knows about it.

**Comment by joakimhew** [comment]
@tomasaschan Hmm you're right, it seems to be there. It was added 26 days ago though so might explain why we don't have it in the SDK references in the provider yet: 

[models #L6894](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/vendor/github.com/Azure/azure-sdk-for-go/services/web/mgmt/2018-02-01/web/models.go#L6894)

@tombuildsstuff Since it was added quite recently to the SDK, I'm supposing it would be available here too soon, right?

**Comment by tombuildsstuff** [comment]
@joakimhew @tomasaschan good spot - we can look to upgrade the Azure SDK to `v25.1.0` in `v1.23.0` of the Provider :)

**Comment by tombuildsstuff** [comment]
PR for upgrading the Azure SDK: https://github.com/terraform-providers/terraform-provider-azurerm/pull/2886
