### ISSUE TITLE
New resource: azurerm_mssql_database with support for vCore model

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#2849]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for the [vCore licensing model](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-service-tiers-vcore) to the single SQL database resource or create a new resource that does.

(I had originally opened this in ticket #1779, but it was closed and I was unable to re-open it.)

### New Resource(s)

* New resource: azurerm_mssql_database

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_database" "test" {
  name                = "MyDatabase"
  resource_group_name = "best_rg_ever"
  location            = "West US"
  server_name         = "mysqlserver1"
  sku {
    name     = "GP_Gen5"
    capacity = 4
    tier     = "GeneralPurpose"
    family   = "Gen5"
  }

  per_database_settings {
    min_capacity = 0.25
    max_capacity = 4
  }
}
```

Structured the above potential sample code similarly to the [azurerm_mssql_elasticpool](https://www.terraform.io/docs/providers/azurerm/r/mssql_elasticpool.html) resource. 

### References

* https://docs.microsoft.com/en-us/azure/sql-database/sql-database-service-tiers-vcore
* #1779

**Comment by Kevat** [comment]
Will this change include any of the following:

1. Support for General Purpose, Hyperscale and Business Critical options as a part of the "tier" setting?
2. Support for Provisioned vs. Serverless options as a part of the "Compute Tier" setting for General Purpose?
3. Support for Secondary Replicate for Hyperscale?
4. Support for Read Scale Out for Business Critical?

**Comment by frugecn** [comment]
Any update on this request?  With the move away from DTU model to vCore model, we really need to get this one out the door, please.

**Comment by frugecn** [comment]
This doesn't necessarily need to be a new resource.  It can be a modification to azurerm_sql_database.  We just need to add the sku like we did in the elastic pool #1745

**Comment by ranokarno** [comment]
@frugecn  is correct, we can just modify "requested_service_objective_name" to spin up VCORE database.
```resource "azurerm_sql_database" "example" {
  name                = "mysqldatabase"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "West US"
  server_name         = "${azurerm_sql_server.example.name}"
  requested_service_objective_name = "GP_Gen4_1"

  tags = {
    environment = "production"
  }
}
```

can refer to this link here to find out more 
https://docs.microsoft.com/en-us/rest/api/sql/databases/createorupdate#database
```az sql db list-editions -l <location> -o table```

**Comment by yupwei68** [comment]
I'm working on this.

**Comment by adback03** [comment]
Can someone explain why this is a new resource? When should we be using `azurerm_sql_database` versus `azurerm_mssql_database`? Is the old one going to get deprecated?

**Comment by yupwei68** [comment]
hi @adback03 ,You're right that the old one is going to be deprecated. But currently, we want to still support the old ones while those still are in use.
