### ISSUE TITLE
New Resources: azurerm_eventgrid_[subscription, domain, topictype]

### ISSUE THREAD

**Issue by katbyte** [terraform-providers/terraform-provider-azurerm#2855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Meta tracking issue for the following Event Grid resources:

- [x] azurerm_eventgrid_domain
- [x] azurerm_eventgrid_subscription additionall issue @ #1794)
- [ ] azurerm_eventgrid_topic_type

**Comment by tombuildsstuff** [comment]
Taking a look into this, we've believe that Topic Types doesn't necessarily make sense as a Data Source in Terraform at this time - as such I'm going to close this issue since the other resources have shipped 👍
