### ISSUE TITLE
Automatic provisioning for a subscription Security Center

### ISSUE THREAD

**Issue by MelleD** [terraform-providers/terraform-provider-azurerm#2857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I would like to enable "Automatic provisioning" with terraform.

Azure Console
Go to Security Center
Click on Security Policy
Click on Edit Setting for subscription
Click on Data Collection
Ensure that Automatic provisioning of monitoring agent is set to On

**Comment by SirWayne** [comment]
Is there any news here?

**Comment by szaher** [comment]
Not sure how would this resource https://www.terraform.io/docs/providers/azurerm/r/security_center_workspace.html be useful without auto provisioning turned on!

Can we please add that to azurerm 2.0 ? if you can backport it  to 1.x that would be great as well!

**Comment by MelleD** [comment]
Is there an update here?

**Comment by njuCZ** [comment]
@MelleD there is already such a resource:, please refer to: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_auto_provisioning
