### ISSUE TITLE
Feature Request: Azure AD Resources

### ISSUE THREAD

**Issue by kmcquade** [terraform-providers/terraform-provider-azurerm#286]
Hi,

I'd really like to see support for resource creation WRT Azure AD. Application objects, user group assignments, etc. etc. AWS has a lot of these features available through terraform but it's lacking in Azure. 

Examples: 

- I can't create a resource group and limit permissions to a specific group in Azure AD; I'd have to do that manually in the portal. AWS provides this: [here](https://www.terraform.io/docs/providers/aws/d/iam_group.html).

- I can't create a service principal for use in the /global directory that specifies the permissions for users creating the resources. Example of a terraform repo that performs this similar action [here](https://github.com/segmentio/stack/blob/master/iam-role/main.tf). 

Having this would allow organizations using terraform to create a resource group for Dev, QA, Staging, and Prod and limit the permissions of users + SPs to each individual resource group - all within a single subscription.

**Comment by tombuildsstuff** [comment]
hi @kmcquade 

Thanks for opening this issue - apologies for the delayed response here!

To reply to each issue in-line:

> I can't create a resource group and limit permissions to a specific group in Azure AD; I'd have to do that manually in the portal.

This should be possible now using the [`azurerm_role_definition `](https://www.terraform.io/docs/providers/azurerm/r/role_definition.html) and [`azurerm_role_assignment `](https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html) resources. Would you be able to take a look and see if that solves your issue?

> I can't create a service principal for use in the /global directory that specifies the permissions for users creating the resources.

Issue #16 is tracking the feature request to create Service Principals via Terraform - as such (and given I believe the above issue has been resolved) - I'm going to close this issue in favour of that one.

Thanks!

**Comment by KbLev** [comment]
Is there a way to retrieve the ObjectID of an AzureAD Group by name, that I can use with [azurerm_role_assignment](https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html) ?
