### ISSUE TITLE
azurerm_automation_runbook fails with 404 Error - Unless Published version of runbook already exists

### ISSUE THREAD

**Issue by divgo** [terraform-providers/terraform-provider-azurerm#2868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
* provider.azurerm: version = "~> 1.21"

### Affected Resource(s)
azurerm_automation_runbook

### Terraform Configuration Files
resource azurerm_automation_runbook automation_runbook {
  name                = "TagResourcesOnCreate"
  location            = "${module.resource_group.location}"
  resource_group_name = "${module.resource_group.name}"
  account_name        = "${module.automation_account.name}"
  log_verbose         = "true"
  log_progress        = "true"
  description         = "Tag Resource Groups on Create"
  runbook_type        = "Powershell"

  publish_content_link {
    uri = "https://[blob_account].blob.core.windows.net/[container]/[runbook_filename]"
  }

  depends_on = ["module.automation_account"]
}

----   ALSO -----
data "local_file" "tag_resources" {
  filename = "C:/ashley/scm/devops_dsc/runbooks/TagResourcesOnCreate.ps1"
}

module automation_runbook {
  source                  = "git::ssh://git@ssh.dev.azure.com/v3/ashleyfurniture/Infra-Cloud/terraform-modules//automation/automation-runbook?ref=v1.7.5"
  runbook_name            = "TagResourcesOnCreate"
  resource_group_name     = "${module.resource_group.name}"
  location                = "${module.resource_group.location}"
  automation_account_name = "${module.automation_account.name}"
  description             = "Tag Resource Groups on Create"
  publish_content_link    = "https://[blob_account].blob.core.windows.net/[container_name]/[runbook_filename]"

  content = "${data.local_file.tag_resources.content}"
}

Where the module is simply a complete definition of azurerm_automation_runbook. 

### Debug Output
None

### Panic Output
No Panic Output

### Expected Behavior
Azure Automation Runbook would have been created with its Content being set. Using either publish_content_link alone, or publish_content_link WITH the "content" attribute both produce the same output. 

Confirmed that the blob storage account container does indeed have its permissions set to "blob". Also tried setting container permissions to Container, but it did not resolve the error. 

### Actual Behavior
Error: Error applying plan:

1 error(s) occurred:

* module.devops.azurerm_automation_runbook.automation_runbook: 1 error(s) occurred:

* azurerm_automation_runbook.automation_runbook: Error retrieving Automation Runbook "TagResourcesOnCreate" (Account "DevOpsAutomation" / Resource Group "devops-rg"): automation.RunbookClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/DevOpsAutomation/runbooks/TagResourcesOnCreate' under resource group 'devops-rg' was not found."

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The 404 error happens whether you specify JUST publish_content_link or publish_content_link AND content attributes. 

Confirmed that the blob storage account Container does indeed have its permissions set to "blob". Also tried setting Container permissions to Container, but it did not resolve the error. 

To resolve the Terraform error, I had to first manually Create the Runbook in the Portal and then Publish it. Once I published an empty Runbook, the 404 error went away and Terraform was able to deploy the Runbook content as expected. 

* #0000

**Comment by tombuildsstuff** [comment]
hi @divgo 

Thanks for opening this issue :)

At this time Terraform doesn't support dependencies between modules in the form you're using above (`depends_on = ["module.automation_account"]`) - there's an issue tracking this here which you can follow for updates: https://github.com/hashicorp/terraform/issues/10462.

One thing I wanted to call out however is that the syntax being used above isn't officially supported and will stop working in Terraform 0.12:

```
resource azurerm_automation_runbook automation_runbook {
  # ...
}
```

The officially supported way of defining a Data Source/Resource is like so (which works in Terraform 0.11 and will continue working in Terraform 0.12+):

```hcl
resource "azurerm_automation_runbook" "automation_runbook" {
  # ...
}
```

However since this issue is a feature request for Terraform Core (to support dependencies between modules) rather than something specific to the AzureRM Provider for the moment I'm going to close this issue for the moment.

Thanks!

**Comment by mattbowes** [comment]
I ran into this issue recently and it was because the` publish_content_link { uri = }` was set to a dummy URL that had nothing in it. Once I set it to a valid ps1 script with just "Hello World" in it and then used `content =` to set it to the local file it worked
