### ISSUE TITLE
bufio.Scanner: token too long

### ISSUE THREAD

**Issue by bentterp** [terraform-providers/terraform-provider-azurerm#2878]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.0-dev (built from master, last commit Mon Feb 11 18:53:33 2019 -0800)
+ provider.azurerm v1.17.0-5-ga3b48ba3-dev (from the last alpha)

### Affected Resource(s)

N/A
* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
locals {
  prefix = "bugtest"
}
  
resource "azurerm_resource_group" "test" {
  name     = "${local.prefix}-rgp-test"
  location = var.region

  tags = {
    "name" = "${local.prefix}-rgp-test"
  }
}
```

### Debug Output
https://gist.github.com/bentterp/8fc08509ebb8329b004fc278c875e6eb
### Expected Behavior
A plan for creating a resource group

### Actual Behavior
The process freezes totally:
```sh
PS H:\Documents\azure_devops\folksamcloudcoe\bugtest> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...
Two interrupts received. Exiting immediately. Note that data
loss may have occurred.

Error: operation canceled


PS H:\Documents\azure_devops\folksamcloudcoe\bugtest>
```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @bentterp 

Thanks for opening this issue :)

Taking a look into this, this appears to be an issue with Terraform 0.12 rather than a bug in the Azure Provider - would you mind re-opening this issue [on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where the Core team could take a look?

Thanks!
