### ISSUE TITLE
azurerm_recovery_services_protected_vm - incorrect documentation for RG attribute?

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#2880]
In the documentation for the [azurerm_recovery_services_protected_vm](https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protected_vm.html) resource, it states that the required Resource Group is where it will create the Recovery Services Protected VM. 

However, I've found this does not work. 
What works is specifying the RG of the Recovery Services _Vault_.

Sample error message:
`StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.RecoveryServices/vaults/example-vault' under resource group 'rg-my-app' was not found."`

I didn't want to submit a documentation update PR, until someone else could verify.

**Comment by kjhosein** [comment]
Here's some corroborating info: 
https://docs.microsoft.com/en-us/azure/backup/quick-backup-vm-cli#enable-backup-for-an-azure-vm

In the _Note_, it says: 

> If the VM is not in the same resource group as that of vault, then myResourceGroup refers to the resource group where vault was created.

**Comment by neil-yechenwei** [comment]
Hopes this [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7775)would be helpful.
