### ISSUE TITLE
Unknown resource 'template_cloudinit_config'

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#2888]
Receive a **unknown resource** error when using `template_cloudinit_config`.  

```
data "template_file" "cloudconfig" {
  template = "${file(format("%s/cloudconfig.tpl", path.module))}"
}

 data "template_cloudinit_config" "config" {
  gzip          = true
  base64_encode = true

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.cloudconfig.rendered}"
  }
} 
```

Results in:
`Error: resource 'azurerm_virtual_machine.vm' config: unknown resource 'data.template_cloudinit_config.cloudconfig' referenced in variable data.template_cloudinit_config.cloudconfig.rendered`

Full solution can be found here > https://gist.github.com/rohrerb/8daffbf8292742ed2923436d533d625a

cc @tombuildsstuff

**Comment by katbyte** [comment]
Hi @rohrerb,

That resource is provided by a [different provider](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html)

Simply add a template provider block as such:
```
provider "template" {
}
```

and you should be good to go 🙂
