### ISSUE TITLE
Add is_hns_enabled property to storage account

### ISSUE THREAD

**Issue by r0bnet** [terraform-providers/terraform-provider-azurerm#2897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Data Lake Store Gen2 is general available since ~2 weeks. There is no new resource or something like that but a flag that enables this for a normal storage account. In ARM templates this property is called `isHnsEnabled` (defines wether this storage account has a hierarchical namespace), is of type `boolean` and is set to false per default. I tried to implement it by myself but it didn't work out as expected. I found out that i had to upgrade the currently used golang lib for the storage account from `2017-10-01` to either `2018-02-01` or `2018-07-01`. Both upgrades led to some issues that i was not capable of resolving myself.

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

I'd propose something like this:

```hcl
resource "azurerm_resource_group" "testrg" {
  name     = "resourceGroupName"
  location = "westus"
}

resource "azurerm_storage_account" "testsa" {
  name                     = "storageaccountname"
  resource_group_name      = "${azurerm_resource_group.testrg.name}"
  location                 = "westus"
  account_tier             = "Standard"
  account_replication_type = "GRS"
  is_hns_enabled           = true
}
```

### References

* https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-quickstart-create-account

**Comment by Lucretius** [comment]
@tombuildsstuff looks like this one got resolved and can be closed?

**Comment by tombuildsstuff** [comment]
@Lucretius good spot - agreed, I'll close this - thanks!
