### ISSUE TITLE
Feature Request: extend CosmosDB Account to allow the kind of DB to be specified

### ISSUE THREAD

**Issue by StuartGreenhall** [terraform-providers/terraform-provider-azurerm#290]
Hey, 

It would be great it cosmosdb resource was extend to enable a user to specify which kind of database they would like to use within cosmos. 

This looks to be possible via the REST API: https://docs.microsoft.com/en-us/rest/api/documentdbresourceprovider/DatabaseAccounts/List#definitions_databaseaccountslistresult_databaseaccount_properties

I looked into the [code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_cosmos_db_account.go) and think this would require a addition field in the schema call **Kind** that can be one of the following values: 
- GlobalDocumentDB
- MongoDB
- {Unknown Value for GraphDB}  
- {Unknown Value for KeyValue}  

Perhaps the default would be GlobalDocumentDB as that's the current behaviour.

**Comment by tombuildsstuff** [comment]
Hey @StuartGreenhall 

Thanks for this request - I've just added support for setting this to `MongoDB` or `GlobalDocumentDB` (which is the default) in #299 - which should go out in the next version of the AzureRM provider :)

Thanks!
