### ISSUE TITLE
Firewall rule names for Redis Cache doesn't support underscores

### ISSUE THREAD

**Issue by inkel** [terraform-providers/terraform-provider-azurerm#2903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.1
+ provider.azurerm (unversioned)
```

I've also confirmed that the latest [`master`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/7f6e370fdce3c7e5ddca017a678d76cd3db99b88/azurerm/resource_arm_redis_firewall_rule.go#L164) at the time of writing this has the same bug.

### Affected Resource(s)

* [`redis_firewall_rule`](https://www.terraform.io/docs/providers/azurerm/r/redis_firewall_rule.html)

### Terraform Configuration Files

```hcl
# Variables are all of type string and defined in variables.tf

resource "azurerm_redis_firewall_rule" "rule" {
  name                = "${var.redis_cache_name}_firewall_rule"
  redis_cache_name    = "${var.redis_cache_name}"
  resource_group_name = "${var.resource_group_name}"
  start_ip            = "${var.firewall_rule_start_ip}"
  end_ip              = "${var.firewall_rule_end_ip}"
}
```

### Debug Output

N/A

### Panic Output

N/A
### Expected Behavior

When trying to create an `azurerm_redis_firewall_rule` it should've accepted using `_` in the name. Running `terraform validate` should've succeeded, but it reports an error that the `name` property only allows for alphanumeric characters.

The [documentation for this resource](https://www.terraform.io/docs/providers/azurerm/r/redis_firewall_rule.html) doesn't state this requirement, which is confusing.

Using Azure's portal I was able to create a Redis Cache Firewall Rule with the name `az_0_9_A`. The official Azure's documentation for the [Redis Firewall Rule - Create Or Update](https://docs.microsoft.com/en-us/rest/api/redis/redisfirewallrule/createorupdate) doesn't specify the alphanumeric constraint.

### Actual Behavior

```
$ terraform validate

Error: azurerm_redis_firewall_rule.rule: "name" may only contain alphanumeric characters
```

### Steps to Reproduce

1. Try creating an `azurerm_redis_firewall_rule` resource with a `name` property with underscores.
1. Run `terraform validate`

### Important Factoids

N/A

### References

I couldn't find any issues related to this.

**Comment by inkel** [comment]
For the record, I was also able to create a firewall rule named `_az_`. I have a local fix for this issue that I can send as a pull request.

**Comment by RiverPhillips** [comment]
I've raised PR #2903 which resolves this

**Comment by inkel** [comment]
Thank you so much!
