### ISSUE TITLE
 provisioner "file" is failing

### ISSUE THREAD

**Issue by vishwavijayverma** [terraform-providers/terraform-provider-azurerm#2907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
+ provider.azurerm v1.22.1

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl

data "azurerm_resource_group" "test" {
  name = "rGroup-ATGnoPRD"
}

#refer to a subnet
data "azurerm_subnet" "test" {
  name                 = "Transversal"
  virtual_network_name = "vNet-ATGnoPRD"
  resource_group_name  = "rGroup-ATGnoPRD"
}

provider "azurerm" {
  client_id       = "${var.azurerm_client_id}"
  client_secret   = "${var.azurerm_client_secret}"
  tenant_id       = "${var.azurerm_tenant_id}"
  subscription_id = "${var.azurerm_subscription_id}"
}

resource "azurerm_resource_group" "myterraformgroup" {
  name     = "${var.name}"
  location = "${var.location}"
}

resource "azurerm_network_interface" "myterraformnic" {
  name                = "performanceagent-nic"
  location            = "${azurerm_resource_group.myterraformgroup.location}"
  resource_group_name = "${azurerm_resource_group.myterraformgroup.name}"

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = "${data.azurerm_subnet.test.id}"
    private_ip_address_allocation = "dynamic"
  }
}

resource "azurerm_network_security_group" "agent" {
  name                = "vmagent"
  location            = "East US 2"
  resource_group_name = "${azurerm_resource_group.myterraformgroup.name}"

  security_rule {
    name                       = "SSH"
    priority                   = 1001
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_virtual_machine" "myterraformvm" {
  name                  = "agent-vm"
  location              = "${azurerm_resource_group.myterraformgroup.location}"
  resource_group_name   = "${azurerm_resource_group.myterraformgroup.name}"
  network_interface_ids = ["${azurerm_network_interface.myterraformnic.id}"]
  vm_size               = "Standard_D4s_v3"

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  # delete_os_disk_on_termination = true


  # Uncomment this line to delete the data disks automatically when deleting the VM
  # delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
  storage_os_disk {
    name              = "agentosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  #put mentioned value just testing, we will put ssh based auth  
  os_profile {
    computer_name  = "xxxx"
    admin_username = "jenkins"
    admin_password = "xxxx"
  }
  os_profile_linux_config {
    disable_password_authentication = false
  }
 provisioner "local-exec" {
      command = "sleep 180"
      } 
  connection {
      type     = "ssh"
      host     = "${azurerm_network_interface.myterraformnic.private_ip_address}"
      user     = "${var.vm_admin_user}"
      password = "${var.vm_admin_password}"
      agent    = false
      timeout  = "10m"
    }
  
  provisioner "file" {
      source      = "package.sh"
      destination = "package.sh"

}
  provisioner "remote-exec" {
    inline = [
      "chmod +x ~/package.sh",
      "cd ~",
      "echo ${var.vm_admin_password} | sudo -S ./package.sh",
    ]

    connection {
      type     = "ssh"
      host     = "${azurerm_network_interface.myterraformnic.private_ip_address}"
      user     = "${var.vm_admin_user}"
      password = "${var.vm_admin_password}"
      agent    = false
      timeout  = "10m"
    }
  }

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
2019-02-17T16:10:47.500+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.22.1_x4: 2019/02/17 16:10:47 [DEBUG] Unlocking "azurerm_virtual_machine.agent-vm"
2019-02-17T16:10:47.500+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.22.1_x4: 2019/02/17 16:10:47 [DEBUG] Unlocked "azurerm_virtual_machine.agent-vm"
azurerm_virtual_machine.myterraformvm: Provisioning with 'local-exec'...
azurerm_virtual_machine.myterraformvm (local-exec): Executing: ["/bin/sh" "-c" "sleep 180"]
azurerm_virtual_machine.myterraformvm: Still creating... (40s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (50s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (1m0s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (1m10s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (1m20s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (1m30s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (1m40s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (1m50s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (2m0s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (2m10s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (2m20s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (2m30s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (2m40s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (2m50s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (3m0s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (3m10s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (3m20s elapsed)
azurerm_virtual_machine.myterraformvm: Still creating... (3m30s elapsed)
azurerm_virtual_machine.myterraformvm: Provisioning with 'file'...
2019-02-17T16:13:47.531+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/17 16:13:47 [DEBUG] connecting to TCP connection for SSH
2019-02-17T16:13:48.029+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/17 16:13:48 [DEBUG] handshaking with SSH
azurerm_virtual_machine.myterraformvm: Still creating... (3m40s elapsed)
2019-02-17T16:13:53.505+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/17 16:13:53 [WARN] ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2019-02-17T16:13:53.505+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/17 16:13:53 [WARN] retryable error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2019-02-17T16:13:53.505+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/17 16:13:53 [INFO] sleeping for 1s
2019-02-17T16:13:54.507+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/17 16:13:54 [DEBUG] connecting to TCP connection for SSH
2019-02-17T16:13:55.007+0530 [DEBUG] plugin.terraform: file-provisioner (internal) 2019/02/17 16:13:55 [DEBUG] handshaking with SSH

provisioner "remote-exec" working as expected but provisioner "file" is failing.

### Actual Behavior
terraform apply should work

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @vishwavijayverma 

Thanks for opening this issue :)

Taking a look at the configuration posted above - it appears the configuration isn't being set for the File provisioner, as such Terraform is unable to determine which credentials should be used to connect:

```hcl
resource "azurerm_virtual_machine" "myterraformvm" {
  # ...
  provisioner "file" {
      source      = "package.sh"
      destination = "package.sh"
  }
  provisioner "remote-exec" {
    inline = [
      "chmod +x ~/package.sh",
      "cd ~",
      "echo ${var.vm_admin_password} | sudo -S ./package.sh",
    ]

    connection {
      type     = "ssh"
      host     = "${azurerm_network_interface.myterraformnic.private_ip_address}"
      user     = "${var.vm_admin_user}"
      password = "${var.vm_admin_password}"
      agent    = false
      timeout  = "10m"
    }
  }
}
```

You should be able to update the Configuration to include the `connection` block within the `File` block (as you've done within the `remote-exec` block), like so:

```hcl
resource "azurerm_virtual_machine" "myterraformvm" {
  # ...
  provisioner "file" {
      source      = "package.sh"
      destination = "package.sh"

    connection {
      type     = "ssh"
      host     = "${azurerm_network_interface.myterraformnic.private_ip_address}"
      user     = "${var.vm_admin_user}"
      password = "${var.vm_admin_password}"
      agent    = false
      timeout  = "10m"
    }
  }

  provisioner "remote-exec" {
    inline = [
      "chmod +x ~/package.sh",
      "cd ~",
      "echo ${var.vm_admin_password} | sudo -S ./package.sh",
    ]

    connection {
      type     = "ssh"
      host     = "${azurerm_network_interface.myterraformnic.private_ip_address}"
      user     = "${var.vm_admin_user}"
      password = "${var.vm_admin_password}"
      agent    = false
      timeout  = "10m"
    }
  }
}
```

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment, however please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by varunnair82** [comment]
I have a similar problem while provisioning with file. I am trying to create a windows VM and trying to copy a file to the Azure VM from my local machine.

Terraform goes on creating VM for a while and stops with error timeout

I have specified port 5985 in the network security group inbound rule for winrm.
Is the host specified in your example above correct ? as I think it should have been

host     = "${azurerm_public_ip.myterraformnic.fqdn}"
