### ISSUE TITLE
azurerm_mssql_elasticpool requiring max_size_gb when it should be optional

### ISSUE THREAD

**Issue by laurencee** [terraform-providers/terraform-provider-azurerm#2909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.22.1

### Affected Resource(s)

azurerm_mssql_elasticpool

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "default" {
  name                = "${local.sql_elasticpool_name}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  location            = "${local.location}"
  server_name         = "${azurerm_sql_server.default.name}"

  sku {
    name     = "BasicPool"
    capacity = "50"
    tier     = "Basic"
  }

  per_database_settings {
    min_capacity = 0
    max_capacity = "5"
  }
}
```

### Expected Behavior

The elastic pool should be created or updated

### Actual Behavior

The following error is returned: `* module.global.azurerm_mssql_elasticpool.default: service tier 'Basic' with a 'capacity' of 50 must have a 'max_size_gb' of 4.8828125 GB, got 0.0000000 GB`

### Steps to Reproduce

1. `terraform plan` or `terraform apply`

### Notes

This was working in 1.20.0 of the azurerm provider

**Comment by neil-yechenwei** [comment]
@laurencee , Thanks for opening this issue. Although `max_size_gb` is optional property but it has additional [check logic](https://github.com/terraform-providers/terraform-provider-azurerm/blob/09ea91d043fd0fb61cf108e3c73d56c0ab7df26d/azurerm/helpers/azure/elasticpool.go#L332) when `sku` is speicified. So you have to specify `max_size_gb`.

**Comment by ArcturusZhang** [comment]
Hi @neil-yechenwei could you please provide a modification for the documentations regarding this issue?
