### ISSUE TITLE
Unable to create azurerm_kubernetes_cluster resource with multiple agent_pool_profile blocks

### ISSUE THREAD

**Issue by robinkb** [terraform-providers/terraform-provider-azurerm#2915]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.22.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "kubernetes" {
  name                = "${local.env}-kubernetes"
  location            = "${azurerm_resource_group.kubernetes.location}"
  resource_group_name = "${azurerm_resource_group.kubernetes.name}"

  kubernetes_version = "1.12.5"

  dns_prefix = "${local.env}-kubernetes"

  agent_pool_profile {
    name            = "standardd2"
    count           = 2
    vm_size         = "Standard_D2_v3"
    os_disk_size_gb = 30
    os_type         = "Linux"
    vnet_subnet_id  = "${data.azurerm_subnet.kubernetes.id}"
  }

  agent_pool_profile {
    name            = "standardd3"
    count           = 2
    vm_size         = "Standard_D3_v3"
    os_disk_size_gb = 30
    os_type         = "Linux"
    vnet_subnet_id  = "${data.azurerm_subnet.kubernetes.id}"
  }

  service_principal {
    client_id     = "${azuread_application.kubernetes.application_id}"
    client_secret = "${random_string.service_principal_kubernetes_password.result}"
  }

  network_profile {
    network_plugin     = "azure"
    service_cidr       = "172.16.0.0/20"
    dns_service_ip     = "172.16.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
  }

  role_based_access_control {
    enabled = true
  }

  tags {
    managed-by = "Terraform"
  }
}
```

### Debug Output

Not applicable? I can produce it if necessary.

### Expected Behavior

Terraform provisions an AKS cluster with two agent pools, as documented.
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#agent_pool_profile

### Actual Behavior

Terraform prints the following message:

```
Error: azurerm_kubernetes_cluster.kubernetes: agent_pool_profile: attribute supports 1 item maximum, config has 2 declared
```

### Steps to Reproduce

1. `terraform apply`

### Notes

This seems to be an error in the provider documentation. [The Azure REST API reference states that currently only one agent pool can exist.](https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#request-body)

**Comment by RespawnDespair** [comment]
I'm having this exact issue. I want both a Linux and a Windows agent_pool_profile.
Is this possible and just poorly documenten? The docs say `One or more agent_pool_profile blocks as documented below.`.
Really hung up on this...
