### ISSUE TITLE
azurerm_subnet_network_security_group_association getting removed on re-applying changes.

### ISSUE THREAD

**Issue by kundan123456** [terraform-providers/terraform-provider-azurerm#2918]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
terraform-provider-azurerm_v1.22.0_x4

### Affected Resource(s)

* `azurerm_subnet_network_security_group_association`

### Terraform Configuration Files

```hcl

resource "azurerm_resource_group" "claims" {
  name     = "Network-RG"
  location = "East US"
}
resource "azurerm_virtual_network" "claims" {
  name                = "Vnet1"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.claims.location}"
  resource_group_name = "${azurerm_resource_group.claims.name}"
}
resource "azurerm_network_security_group" "claims" {
  name                = "NSG1"
  location            = "${azurerm_resource_group.claims.location}"
  resource_group_name = "${azurerm_resource_group.claims.name}"
}
resource "azurerm_subnet" "claims" {
  name                      = "SN1"
  virtual_network_name      = "${azurerm_virtual_network.claims.name}"
  resource_group_name       = "${azurerm_resource_group.claims.name}"
  address_prefix            = "10.0.1.0/24"
  #network_security_group_id = "${azurerm_network_security_group.claims.id}"
}
resource "azurerm_subnet_network_security_group_association" "claims" {
  subnet_id                 = "${azurerm_subnet.claims.id}"
  network_security_group_id = "${azurerm_network_security_group.claims.id}"
}
```

### Expected Behavior
After creating 5 resources, If again I run terraform plan or apply it should not remove NSG and Subnet association.

### Actual Behavior
After giving command terraform apply, its creating all 5 resources. But again if I do terraform apply it is removing the association of NSG and Subnet.

And also, while creating the resources I had to comment out **network_security_group_id** inside azurerm_subnet resource as it is [DEPRECATED]. But if I add this field **network_security_group_id** inside azurerm_subnet while re-applying it does not remove the association. 

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by juanjojulian** [comment]
Unfortunately we have to use both methods until v2.0 is released, "azurerm_subnet_network_security_group_association" and "network_security_group_id", see the note at the beginning of [subnet_network_security_group_association](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html)
>"NOTE: Subnet <-> Network Security Group associations currently need to be configured on both this resource and using the network_security_group_id field on the azurerm_subnet resource. The next major version of the AzureRM Provider (2.0) will remove the network_security_group_id field from the azurerm_subnet resource such that this resource is used to link resources in future."

A possible workaround is adding:
```
  lifecycle { 
     ignore_changes = ["network_security_group_id"]
 }
```
To your azurerm_subnet resource avoiding any change of that attribute each time after each re-deployment.

**Comment by kundan123456** [comment]
Thank you @juanjojulian for the clarification, will use the following workaround until v2.0 is released.
