### ISSUE TITLE
Cannot Modify Rule and Priority Simultaneously 

### ISSUE THREAD

**Issue by bernadinm** [terraform-providers/terraform-provider-azurerm#293]
# Cannot Modify Rule and Priority Simultaneously 
It looks like Azure provider gave Terraform the impression that a change to the azurerm_network_security_rule were applied successfully, but when a request to swap a azurerm_network_security_rule with a priority that was previously used, Azure/Terraform throws an error stating that it already exist.

It seems like there might be a bug with the Azurerm provider and terraform doesn't know exactly when a changes to the azurerm_network_security_rule has been made. 

### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
Please list the resources as a list, for example:
azurerm_network_security_rule

### Terraform Plan
```hcl
  + azurerm_network_security_rule.master-MarathonRule
      access:                      "Allow"
      destination_address_prefix:  "*"
      destination_port_range:      "8080"
      direction:                   "Inbound"
      name:                        "Marathon"
      network_security_group_name: "mbernadin-tf29dc-master-security-group"
      priority:                    "150"
      protocol:                    "Tcp"
      resource_group_name:         "dcos-mbernadin-tf29dc"
      source_address_prefix:       "VirtualNetwork"
      source_port_range:           "*"

  ~ azurerm_network_security_rule.master-everythingElseOutBound
      priority: "160" => "170"

  ~ azurerm_network_security_rule.master-internalEverything
      priority: "150" => "160"

```

### Debug Output

Detailed logs located here: https://gist.github.com/bernadinm/4eacbcd05636febf3bfc8013a6632025

#### Error Snippet 
```hcl 
* azurerm_network_security_rule.master-MarathonRule: 1 error(s) occurred:

* azurerm_network_security_rule.master-MarathonRule: network.SecurityRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="SecurityRuleConflict" Message="Security rule allOtherInternalTraffric conflicts with rule Marathon. Rules cannot have the same Priority and Direction." Details=[]
```

### Expected Behavior
What should have happened?
Azure should have applied the changes after `terraform apply`

### Actual Behavior
What actually happened?
It required me to rerun another `terraform apply` in order to make this change.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Attempt to create rules with the same priority.
2. Azure will add one rule with `terraform apply`
3. Modify the rules so they are different. `terraform apply`
4. Terraform / Azure will error out saying that you cannot have duplicate priorities. 
5. Rerun `terraform apply` and watch it make the correct changes.

**Comment by tombuildsstuff** [comment]
hi @bernadinm 

Thanks for opening this issue - apologies for the delayed response here!

Since this issue was opened we've added a lock inside of the Network Security Group and Network Security Rule resources so that this now works as expected (since only one item within a Network Security Group, [such as the Group or any Rules] can be modified at any one time).

As this has been fixed I'm going to close this issue for the moment - however would you be able to upgrade to a recent version of the AzureRM Provider and see if that fixes your issue?

Thanks!

**Comment by osudude** [comment]
@tombuildsstuff Similar issue here.. NSG default rule previous had priority 100 allow all tcp ports.  Changed NSG rule name, kept 100 priority, but changed allowed ports and terraform encounters the following error during apply:

**Message="Security rule AllowAllInboundTcp conflicts with rule allow-ase-management. Rules cannot have the same Priority and Direction."**

azurerm 1.32.0
