### ISSUE TITLE
Service Fabric - Node Type - Placement Properties and Capacities

### ISSUE THREAD

**Issue by steve-hawkins** [terraform-providers/terraform-provider-azurerm#2935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For multi node type clusters you will more than likely want to have some sort of control over placement of services, for more information [refer to this article](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-cluster-description#node-properties-and-placement-constraints)

### New or Affected Resource(s)

* azurerm_service_fabric_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "test" {
  name     = "test-cluster"
  location = "uksouth"
}

resource "azurerm_service_fabric_cluster" "test" {
  name                = "test-cluster"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  reliability_level   = "Bronze"
  upgrade_mode        = "Automatic"
  vm_image            = "Windows"
  management_endpoint = "http://example:80"

  node_type {
    name                 = "first"
    placement_properties {
      "HasSSD" = "true"
    }
    capacities {
      "ClientConnections" = "20000"
      "MemoryGB" = "8"
    }
    instance_count       = 3
    is_primary           = true
    client_endpoint_port = 2020
    http_endpoint_port   = 80
  }

  tags {
    "Hello" = "World"
  }
}
```

### References

#2936

**Comment by tombuildsstuff** [comment]
Fixed via #2936 - thanks again @steve-hawkins :)
