### ISSUE TITLE
When `terraform apply` after changing sku of azurerm_cdn_profile, azurerm_cdn_endpoint associated with azurerm_cdn_profile becomes incorrect

### ISSUE THREAD

**Issue by changeworld** [terraform-providers/terraform-provider-azurerm#294]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

`Terraform v0.10.2`

### Affected Resource(s)

Please list the resources as a list, for example:
- azurerm_cdn_profile
- azurerm_cdn_endpoint

### Terraform Configuration Files
```hcl
variable "subscription_id"  {}
variable "client_id"        {}
variable "client_secret"    {}
variable "tenant_id"        {}

variable "name"                           {}
variable "location"                       {}
variable "storage_account_name"           {}
variable "storage_account_type"           {}
variable "storage_container_name"         {}
variable "storage_container_access_type"  {}
variable "cdn_profile_name"               {}
variable "cdn_profile_sku"                {}
variable "cdn_endpoint_name"              {}
variable "cdn_origin_name"                {}

provider "azurerm" {
  subscription_id   = "${var.subscription_id}"
  client_id         = "${var.client_id}"
  client_secret     = "${var.client_secret}"
  tenant_id         = "${var.tenant_id}"
}

resource "azurerm_resource_group" "prod" {
  name      = "${var.name}"
  location  = "${var.location}"
}

resource "azurerm_storage_account" "prod" {
  name                  = "${var.storage_account_name}"
  resource_group_name   = "${azurerm_resource_group.prod.name}"
  location              = "${var.location}"
  account_type          = "${var.storage_account_type}"
}

resource "azurerm_storage_container" "prod" {
  name                  = "${var.storage_container_name}"
  resource_group_name   = "${azurerm_resource_group.prod.name}"
  storage_account_name  = "${azurerm_storage_account.prod.name}"
  container_access_type = "${var.storage_container_access_type}"
}

resource "azurerm_cdn_profile" "prod" {
  name                = "${var.cdn_profile_name}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.prod.name}"
  sku                 = "${var.cdn_profile_sku}"
}

resource "azurerm_cdn_endpoint" "prod" {
  name                = "${var.cdn_endpoint_name}"
  profile_name        = "${azurerm_cdn_profile.prod.name}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.prod.name}"

  origin {
    name       = "${var.cdn_origin_name}"
    host_name  = "${azurerm_storage_account.prod.name}.blob.core.windows.net"
    http_port  = "80"
    https_port = "443"
  }
}
```

### Debug Output

[Debug Output](https://gist.github.com/changeworld/6a3f465873d77f8a7cb36d8003bb1b5e)

### Expected Behavior

Maintain a relationship that links each resource.
For example, to process in the following order.

1. azurerm_cdn_endpoint: Destroy
2. azurerm_cdn_profile: Destroy
3. azurerm_cdn_profile: Create
4. azurerm_cdn_endpoint: Create

### Actual Behavior

1. azurerm_cdn_profile: Destroy
2. azurerm_cdn_profile: Create

As a result, azurerm_cdn_endpoint associated with azurerm_cdn_profile becomes incorrect.
The illegal state means that azurerm_cdn_endpoint is displayed at https://portal.azure.com, but when clicked, the message "resource can not be referenced" is displayed.

### Steps to Reproduce

1. sku set `Standard_Verizon`
2. `terraform apply`
3. sku set `Premium_Verizon`
4. `terraform plan`
5. `terraform apply`
6. Browse https://portal.azure.com/#resource/subscriptions/[subscription id]/resourceGroups/[resource group name]/providers/Microsoft.Cdn/profiles/[cdn profile name]/endpoints/[cdn endpoint name]/overview

**Comment by mioi** [comment]
I have similar issues. After doing a `terraform apply` (Step #5), while Terraform said it was successful, the CDN endpoint actually didn't get created, so doing another `terraform apply` and it fails with:
```
15:16:13 Error: Error applying plan:
15:16:13 
15:16:13 1 error(s) occurred:
15:16:13 
15:16:13 * azurerm_cdn_endpoint.cdn-endpoint: 1 error(s) occurred:
15:16:13 
15:16:13 * azurerm_cdn_endpoint.cdn-endpoint: cdn.EndpointsClient#Create: Failure sending request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="We couldn't configure QueryStringCachingBehavior, IsCompressionEnabled, ContentTypesToCompress, GeoFilters and DeliveryPolicy for premium profile endpoints. You'll need to manage these endpoints in the supplemental portal."
```

**Comment by tombuildsstuff** [comment]
hey @changeworld 

Thanks for opening this issue - apologies for the delayed response here!

The root cause of this is a bug in Terraform Core's graph computation - where resources which aren't chained by their ID's aren't detected as needing recreation until the second `apply`. Given this is a bug in Terraform Core I'm going to suggest relocating this issue over [to that repository](https://github.com/hashicorp/terraform) where it can be fixed - since we can't do a whole bunch about this here.

Thanks!
