### ISSUE TITLE
Creating ACR with existing name taken doesnt error out

### ISSUE THREAD

**Issue by jamie3** [terraform-providers/terraform-provider-azurerm#2940]
Terraform 0.11.11
AzureRM version 1.17.0

1) Create an azure container registry with a DNS name that already exists
2) terraform plan
3) terraform apply

Terraform doesnt error out, instead it times out after 5-10min with no conflict.

```
resource "azurerm_container_registry" "acr" {

  name     = "testacr"    // this already exists
  resource_group_name = "testacr"
  location = "westus2"

  sku                      = "Standard"
  admin_enabled            = false
}
```

**Comment by erindatkinson** [comment]
I ran into this with an `azurerm_resource_group` resource as well so it doesn't look like it's localized to the container_registry resource.

**Comment by tombuildsstuff** [comment]
hey @jamie3 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this it appears the Azure SDK exposes a method (`CheckNameAvailability`) we can use to check for a globally unique name here ([as we do in other resources](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_app_service.go#L201-L212)) as such it should be possible to add a check for this 👍

Thanks!
