### ISSUE TITLE
IaaSDiagnostics Installation fails targetting to Windows server

### ISSUE THREAD

**Issue by iamsoorya** [terraform-providers/terraform-provider-azurerm#2943]
The following code is being used but fails to provision the extension for the VM.

#https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostics-extension-schema-1dot3
#https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/diagnostics-template
resource "azurerm_virtual_machine_extension" "win-extn-diagn" {
  name                 = "${var.computer_name}-diagnosis-extn"
  location             = "${var.location}"
  resource_group_name  = "${var.rg_for_server}"
  virtual_machine_name = "${var.computer_name}"
  publisher            = "Microsoft.Azure.Diagnostics"
  type                 = "IaaSDiagnostics"
  type_handler_version = "1.12"
  auto_upgrade_minor_version = true
  settings = <<SETTINGS
  {
      "xmlCfg": "${base64encode(var.diagnostics_config)}",
      "storageAccount": "${data.azurerm_storage_account.storage_acct.name}"
  }
  SETTINGS

  protected_settings = <<SETTINGS
  {
      "storageAccountName": "${data.azurerm_storage_account.storage_acct.name}",
      "storageAccountKey": "${data.azurerm_storage_account.storage_acct.primary_access_key}"
  }
  SETTINGS

  tags {
    tag_BusinessUnit	          = "${var.tag_BusinessUnit}"
    tag_Department	            = "${var.tag_Department}"
    tag_Environment             = "${var.tag_Environment}"
    tag_ProjectOrSystem         = "${var.tag_ProjectOrSystem}"
    tag_Resilience              = "${var.tag_Resilience}"
    tag_BusinessFunction	      = "${var.tag_BusinessFunction}"
    tag_BusinessSubFunction	    = "${var.tag_BusinessSubFunction}"
    tag_ConsumptionModel        = "${var.tag_ConsumptionModel}"
  } 
  depends_on          = ["azurerm_virtual_machine.win_server",
                         "azurerm_virtual_machine_extension.win_extn_log_analytics",
                         "azurerm_virtual_machine_extension.win_extn_nw_wathcer"]
}
below is the JSON file :+1: 
{
    "StorageAccount": "$$StorageName",
    "WadCfg": {
      "DiagnosticMonitorConfiguration": {
        "overallQuotaInMB": 5120,
        "Metrics": {
          "resourceId": "$$resourceId",
          "MetricAggregation": [
            {
              "scheduledTransferPeriod": "PT1H"
            },
            {
              "scheduledTransferPeriod": "PT1M"
            }
          ]
        },
        "DiagnosticInfrastructureLogs": {
          "scheduledTransferLogLevelFilter": "Error",
          "scheduledTransferPeriod": "PT1M"
        },
        "PerformanceCounters": {
          "scheduledTransferPeriod": "PT1M",
          "PerformanceCounterConfiguration": [
            {
              "counterSpecifier": "\\Processor Information(_Total)\\% Processor Time",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Processor Information(_Total)\\% Privileged Time",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Processor Information(_Total)\\% User Time",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Processor Information(_Total)\\Processor Frequency",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\System\\Processes",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Process(_Total)\\Thread Count",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Process(_Total)\\Handle Count",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\System\\System Up Time",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\System\\Context Switches/sec",
              "unit": "CountPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\System\\Processor Queue Length",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\% Committed Bytes In Use",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\Available Bytes",
              "unit": "Bytes",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\Committed Bytes",
              "unit": "Bytes",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\Cache Bytes",
              "unit": "Bytes",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\Pool Paged Bytes",
              "unit": "Bytes",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\Pool Nonpaged Bytes",
              "unit": "Bytes",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\Pages/sec",
              "unit": "CountPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Memory\\Page Faults/sec",
              "unit": "CountPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Process(_Total)\\Working Set",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Process(_Total)\\Working Set - Private",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\% Disk Time",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\% Disk Read Time",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\% Disk Write Time",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\% Idle Time",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Disk Bytes/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Disk Read Bytes/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Disk Write Bytes/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Disk Transfers/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Disk Reads/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Disk Writes/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Avg. Disk sec/Transfer",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Avg. Disk sec/Read",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Avg. Disk sec/Write",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Avg. Disk Queue Length",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Avg. Disk Read Queue Length",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Avg. Disk Write Queue Length",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\% Free Space",
              "unit": "Percent",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\LogicalDisk(_Total)\\Free Megabytes",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Bytes Total/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Bytes Sent/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Bytes Received/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Packets/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Packets Sent/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Packets Received/sec",
              "unit": "BytesPerSecond",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Packets Outbound Errors",
              "unit": "Count",
              "sampleRate": "PT60S"
            },
            {
              "counterSpecifier": "\\Network Interface(*)\\Packets Received Errors",
              "unit": "Count",
              "sampleRate": "PT60S"
            }
          ]
        },
        "WindowsEventLog": {
          "scheduledTransferPeriod": "PT1M",
          "DataSource": [
            {
              "name": "Application!*[System[(Level=1 or Level=2 or Level=3)]]"
            },
            {
              "name": "System!*[System[(Level=1 or Level=2 or Level=3)]]"
            },
            {
              "name": "Security!*[System[(band(Keywords,4503599627370496))]]"
            }
          ]
        },
        "Directories": {
          "scheduledTransferPeriod": "PT1M"
        },
        "sinks": "applicationInsights"
      },
      "SinksConfig": {
        "Sink": [
          {
            "name": "applicationInsights",
            "ApplicationInsights": "$$AppInstKey"
          }
        ]
      }
    }
  }

**Comment by tombuildsstuff** [comment]
hi @iamsoorya 

Thanks for opening this issue :)

Taking a look at the Terraform Configuration posted above this looks correct from Terraform's side, however Virtual Machine Extensions API won't return the full error, instead this is present in the VM Extension Logs within the Virtual Machine, which should help debug this.

Since the Terraform Configuration looks correct here, I believe this is an issue with the configuration of the Virtual Machine Extension itself, as such I'm going to suggest either [opening an issue on the Azure Custom Script Extension repository](https://github.com/Azure/azure-linux-extensions) where they should be able to help diagnose this further.

Thanks!

**Comment by con-ran** [comment]
Hello All,

I'm having a similar issue but I think it's my terraform code.  Any help is highly appreciated.  I'm newbish into coding so I think I may be missing something.  I did follow terraform's structure and the original post here for context.  I did remove some items from the configuration as I didn't need them.  

Am I supposed to be using a json config file where the "xmlCfg": "${base64encode(var.diagnostics_config)}" points to?  or an xml file?

I've attached both my terraform config for the extension and my xml config file.

########################

Here's the error I receive:

Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'IaaSDiagnostics'. Error message: \"Exception when parsing configuration: Error: The element 'PublicConfig' in namespace 'http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration' cannot contain text. List of possible elements expected: 'WadCfg, LocalResourceDirectory, StorageAccount, WadCfgBlob, StorageType' in namespace 'http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration'. line: 1 column: 100\r\n See the troubleshooting guide to diagnose the problem: https://go.microsoft.com/fwlink/?linkid=852271\"."

  on APP.tf line 162, in resource "azurerm_virtual_machine_extension" "MicrosoftInsightsVMDiagnostics-app_vm":
 162: resource "azurerm_virtual_machine_extension" "MicrosoftInsightsVMDiagnostics-app_vm" {

########################


[Azure Diagnostics Terraform Code.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/3462297/Azure.Diagnostics.Terraform.Code.txt)
[Azure Diagnsotics Extensions XML configuration file.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/3462298/Azure.Diagnsotics.Extensions.XML.configuration.file.txt)
