### ISSUE TITLE
Azure IoT Hub File Upload Support

### ISSUE THREAD

**Issue by mark-greene** [terraform-providers/terraform-provider-azurerm#2948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current resource "azurerm_iothub" does not support file upload.  When applied it removes existing configuration (portal or cli).

* https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-configure-file-upload-cli#file-upload
* https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-file-upload

### New or Affected Resource(s)

* azurerm_iothub

### Potential Terraform Configuration

```hcl
  file_upload {
    connection_string   = "${azurerm_storage_account.test.primary_blob_connection_string}"
    container_name      = "${azurerm_storage_container.test.name}"
    # When enabled, IoT Hub will log information about uploaded files to the messages/servicebound/filenotifications IoT Hub endpoint.
    notifications       = true
    # The number of times the IoT hub will attempt to deliver a file notification message, between 1 and 100.
    max_delivery_count  = 10
    # The amount of time a SAS URI generated by IoT Hub is valid before it expires, between 1 and 24 hours.
    sas_ttl             = 1
    # The amount of time a file upload notification is available for the service to consume before it is expired by IoT Hub, between 1 and 48 hours.
    default_ttl         = 1
  }
```

**Comment by Lucretius** [comment]
It looks like the existing Azure Go SDK has support for all of these properties.
