### ISSUE TITLE
getting error while creating shared image gallery

### ISSUE THREAD

**Issue by aakanshaverma1310** [terraform-providers/terraform-provider-azurerm#2952]
Im trying to create a shared image gallery trough Terraform -
Can someone help me to fix the error --

My main.tf code -

provider "azurerm" {
  version = "=1.16.0"
}
data "azurerm_resource_group" "test" {
  name     = "ge-aakansha"
  //location = "West Europe"
}

resource "azurerm_shared_image_gallery" "test" {
  name                = "example_image_gallery"
  resource_group_name = "${data.azurerm_resource_group.test.name}"
  location            = "${data.azurerm_resource_group.test.location}"
  description         = "Shared images and things."
}

error -

PS C:\Terraform\sig-test> terraform apply
data.azurerm_resource_group.test: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + azurerm_shared_image_gallery.test
      id:                  <computed>
      description:         "Shared images and things."
      location:            "westeurope"
      name:                "example_image_gallery"
      resource_group_name: "ge-aakansha"
      tags.%:              <computed>
      unique_name:         <computed>

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_shared_image_gallery.test: Creating...
  description:         "" => "Shared images and things."
  location:            "" => "westeurope"
  name:                "" => "example_image_gallery"
  resource_group_name: "" => "ge-aakansha"
  tags.%:              "" => "<computed>"
  unique_name:         "" => "<computed>"

****Error: Error applying plan:**

1 error(s) occurred:

* azurerm_shared_image_gallery.test: 1 error(s) occurred:

* azurerm_shared_image_gallery.test: Error creating/updating Shared Image Gallery "example_image_gallery" (Resource Group "ge-aakansha"): compute.GalleriesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="InvalidResourceType" Message="The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2018-06-01'."**

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by tombuildsstuff** [comment]
hi @aakanshaverma1310 

Thanks for opening this issue :)

Since you're running an older version of the AzureRM Provider (`1.16.0`) can you please update to the latest release to confirm if this fixes your issue? You can do this by updating the version in the Provider block:

```
provider "azurerm" {
version = "=1.22.1"
}
```

and then running `terraform init`.

Thanks!

**Comment by tombuildsstuff** [comment]
hi @aakanshaverma1310 

Since we've not heard back from you here I'm going to close this issue for the moment - however please let us know if upgrading to the latest version of the Azure Provider doesn't solve this for you and we'll take another look.

Thanks!
