### ISSUE TITLE
TF keeps removing already removed virtual network rule from storage account

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#2969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
azurerm v1.22.1

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "main" {
  name                      = "xxx"
  resource_group_name       = "${azurerm_resource_group.infrastructure.name}"
  location                  = "${data.terraform_remote_state.shared.default_location}"
  account_kind              = "BlobStorage"
  account_tier              = "Standard"
  access_tier               = "Hot"
  account_replication_type  = "RAGRS"
  enable_https_traffic_only = "true"

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output

https://gist.github.com/ecfbdd265dae58835cda3b9ce3151c5d

### Expected Behavior

It shouldn't attempt to remove the network rule that had been removed already.

### Actual Behavior

This keeps popping up each time on `apply`. No errors reported during execution.
```
 ~ module.staging-env.azurerm_storage_account.main
      network_rules.#:                                       "1" => "0"
      network_rules.0.virtual_network_subnet_ids.#:          "1" => "0"
      network_rules.0.virtual_network_subnet_ids.nnn: "/subscriptions/nnnn/resourceGroups/infrastructure-rg/providers/Microsoft.Network/virtualNetworks/infrastructure-rg/subnets/staging" => ""
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by tombuildsstuff** [comment]
hey @Leon99 

Thanks for opening this issue :)

Taking a look at this it appears this bug has previously been reported in #2198 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #2198 - would you mind subscribing to that one for updates?

Thanks!

**Comment by Leon99** [comment]
@tombuildsstuff #2198 is about `bypass` and explicitly states 
> This does not occur with the ip_rules or virtual_network_subnet_ids properties

while this is what happens in my case.

**Comment by Leon99** [comment]
Both this and #2198 are closed now. @tombuildsstuff does that mean that you're not going to fix this? Also, @lucretius admitted that this one is not a duplicate, but it's still marked as one.
