### ISSUE TITLE
Error with finding resource - bug or config issue?

### ISSUE THREAD

**Issue by sheffski** [terraform-providers/terraform-provider-azurerm#2983]
Hi

I'm using terraform layers for my azure environment and have got just one issue which I'm hoping isn't a bug but just my limited knowledge.

I have created a networking layer which outputs the following info needed for the VM layer

  output "resource_group_name" {
  value = "${azurerm_resource_group.shared-rg.name}"
}

output "resource_group_location" {
  value = "${azurerm_resource_group.shared-rg.location}"
}

output "dmz_subnet_01" {
  value = "${azurerm_subnet.subnet2-DMZ1.address_prefix}"
}

This info I use for the following VM config

resource "azurerm_network_interface" "main" {
  name                      = "vm-nic"
  location                  = "${data.terraform_remote_state.network.resource_group_location}"
  resource_group_name       = "${data.terraform_remote_state.network.resource_group_name}"
  

  ip_configuration {
    name                          = "vmNICconfig"
    subnet_id                     = "${data.terraform_remote_state.network.dmz_subnet_01}"
    private_ip_address_allocation = "Dynamic"
   
   }
  }
  
  
  resource "azurerm_virtual_machine" "jenkinsvm" {
  name                          = "jenkins"
  location                      = "${data.terraform_remote_state.network.resource_group_location}"
  resource_group_name           = "${data.terraform_remote_state.network.resource_group_name}"
  network_interface_ids = ["${azurerm_network_interface.main.id }"]
  vm_size                       = "Standard_DS1_V2"
  delete_os_disk_on_termination = "true"
---rest is omitted for brevity-----

unfortunately the network interface ids reports an error saying that it cannot find the resource
I've defined the backend state as a data source with the credentials needed to see the state file and get no errors accept the one below

Error: Error running plan: 1 error(s) occurred:

* azurerm_virtual_machine.jenkinsvm: 1 error(s) occurred:

* azurerm_virtual_machine.jenkinsvm: Resource 'azurerm_network_interface.main' not found for variable 'azurerm_network_interface.main.id'

I have racked my brain now for 3 days and need some guidance from you enlightened folks

any help is greatly received
kind regards
Stuart

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @sheffski 

Thanks for opening this issue :)

Unfortunately this appears to be the standard issue template above - would it be possible to update this to include the resource in question? When resources are added to the Azure Provider they're [documented in the changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md) - it's possible that the resource you're trying to use is available in a newer version of the Azure Provider than you're using. It's possible to upgrade the version of the Azure Provider that you're using, which you can do via:

```hcl
provider "azurerm" {
  version = "=1.22.1"
}
```

Thanks!

**Comment by sheffski** [comment]
sorry I'm new to submitting stuff like this and hope I haven't hit the wrong place

**Comment by tombuildsstuff** [comment]
@sheffski sorry for the delayed response here.

Taking a look into this, it appears you're trying to reference a local resource: (`network_interface_ids = ["${azurerm_network_interface.main.id }"]`) - rather than one from within the remote state/from the other module.

FWIW rather than using the `terraform_remote_state` resource - I'd strongly suggest using a Data Source to look this information up instead, since this means your code can be more modular (and refactored more easily).

Providing the `network` module  is updated to output the ID of the Subnet, e.g.

```
output "dmz_subnet_id" {
value = "${azurerm_subnet.subnet2-DMZ1.id}"
}
```

then it should be possible to access that using the Remote State:

```hcl
resource "azurerm_virtual_machine" "jenkinsvm" {
  name = "jenkins"
  location = "${data.terraform_remote_state.network.resource_group_location}"
  resource_group_name = "${data.terraform_remote_state.network.resource_group_name}"
  network_interface_ids = ["${data.terraform_remote_state.network.dmz_subnet_id}"]
  vm_size = "Standard_DS1_V2"
  delete_os_disk_on_termination = "true"
  # ...
}
```

or by looking it up using the Data Source:

```hcl
data "azurerm_subnet" "test" {
  name                 = "backend"
  virtual_network_name = "production"
  resource_group_name  = "networking"
}

resource "azurerm_virtual_machine" "jenkinsvm" {
  name = "jenkins"
  location = "${data.terraform_remote_state.network.resource_group_location}"
  resource_group_name = "${data.terraform_remote_state.network.resource_group_name}"
  network_interface_ids = ["${data.azurerm_subnet.test.id}"]
  vm_size = "Standard_DS1_V2"
  delete_os_disk_on_termination = "true"
  # ...
}
```

but either approach should work - but please let us know fi that doesn't work for you and we'll take another look.

Thanks!
