### ISSUE TITLE
Demo code and test defect with NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#2992]
Hi there,
I was found a issue about resource of **NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation**. Demo code and test code should to be fixed both. details below:
1. [Demo code] An error thrown: resource 'azurerm_network_interface_application_gateway_backend_address_pool_association.test' config: unknown resource 'azurerm_application_gateway.test' referenced in variable azurerm_application_gateway.test.backend_address_pool.0.id
2. [Demo code] Wrong address_space setting in virtual network block
3. [Demo code] An error thrown after #2 fixed: azurerm_network_interface.test: network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewaySubnetCannotBeUsedByOtherResources"
4. [Test Defect] Same error message with #3.

Thanks,
Chang

**Comment by brasco10** [comment]
fuck
