### ISSUE TITLE
Upgrading Kubernetes cluster via Azure Portal causes terraform to try to recreate it

### ISSUE THREAD

**Issue by guitmz** [terraform-providers/terraform-provider-azurerm#2993]
### Terraform (and AzureRM Provider) Version
`terraform` **v0.11.7**
`azurerm` **1.22.1**

### Affected Resource(s)
`azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "main" {
...
 addon_profile {
    http_application_routing {
      enabled = false
    }
  }
...
}
```
### Expected Behavior
Nothing should happen. Terraform plan should return no changes after the cluster upgrade is done via azure portal.

### Actual Behavior
Terraform tries to recreate the cluster because of 2 problems:
1. `http_application_routing` addon profile
2. cluster `id`

```
-/+ azurerm_kubernetes_cluster.main (new resource required)
      id:                                                                            "/subscriptions/XXXXXX-XXXX-XXXX-XXX-XXXXX/resourcegroups/myResourceGroup/providers/Microsoft.ContainerService/managedClusters/myCluster" => <computed> (forces new resource)
      addon_profile.#:                                                               "1" => "1"
      addon_profile.0.http_application_routing.#:                                    "0" => "1" (forces new resource)
      addon_profile.0.http_application_routing.0.enabled:                            "" => "false" (forces new resource)
      addon_profile.0.http_application_routing.0.http_application_routing_zone_name: "" => <computed>
...
```

`id` does not change (as far as I can tell) during a upgrade and yet terraform think it does.
`http_application_routing` was already disabled but the sate doesnt seem to match the one from azure backend after the cluster upgrade.
Removing the `addon_profile` block seems to bypass the issue after the cluster upgrade but terraform still wants to recreate the cluster because of the `id` field anyway.

### Steps to Reproduce
1. Create cluster with terraform (with `addon_profile` containing `http_application_routing` **enabled=false**
2. Go to Azure Portal, upgrade your cluster version.
3. Run `terraform plan` (after fixing `kubernetes_version` to match the upgraded version, of course) and the errors will be displayed.

**Comment by guitmz** [comment]
This issue is still present with the version `1.24.0`. I just upgraded the cluster from the portal UI and ran terraform plan and got the exact same error. Any feedback?

**Comment by guitmz** [comment]
This workaround is what I've been successfully using for now (but its not ideal):

```
lifecycle {
    ignore_changes = ["id", "addon_profile"]
  }
```

**Comment by CapoD** [comment]
We are currently facing the same problem. Is there any progress resolving this issue?

**Comment by chufgard** [comment]
> We are currently facing the same problem. Is there any progress resolving this issue?

After some deeper investigation we found out, that our problem might have been a different one. We had different subnets configured and loaded the relevant id for k8s via a data call. After that call was removed, the cluster was no longer recreated.

**Comment by kim0** [comment]
I am hitting this now! I have to upgrade through the portal, since terraform based upgrades are basically broken till we have proper support for node pools. The annoying part is that `http_application_routing` is already set to `enabled = false`, so I have no idea why it wants to recreate 😕 

Hoping any of the maintainers can take a look and advise. cc: @tombuildsstuff
