### ISSUE TITLE
azurerm_app_service windows container support

### ISSUE THREAD

**Issue by Ashtonian** [terraform-providers/terraform-provider-azurerm#2999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azurerm_app_service doesn't currently seem to support windows + docker. 

### New or Affected Resource(s)

azurerm_app_service

**Comment by tombuildsstuff** [comment]
hey @Ashtonian 

Thanks for opening this issue :)

Taking a quick look into this, it appears that support for this [exists in the Azure SDK for Go as the `WindowsFxVersion` field:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/vendor/github.com/Azure/azure-sdk-for-go/services/web/mgmt/2018-02-01/web/models.go#L17694-L17665 (although this doesn't render in GH's UI.. so here's a snippet)

```
// SiteConfig configuration of an App Service app.
type SiteConfig struct {
	# ...
  
	// LinuxFxVersion - Linux App Framework and version
	LinuxFxVersion *string `json:"linuxFxVersion,omitempty"`
	// WindowsFxVersion - Xenon App Framework and version
	WindowsFxVersion *string `json:"windowsFxVersion,omitempty"`

  # ...
}
```

As such it should be possible to add support for this ([and add another example to the App Service Examples folder](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/app-service)) at the same time 👍

Thanks!

**Comment by jcorioland** [comment]
@Ashtonian did you plan to work on that? Otherwise I can do it :)

**Comment by Ashtonian** [comment]
@jcorioland Nope, have at it!

**Comment by jcorioland** [comment]
Ok, looking at this now :)
