### ISSUE TITLE
AppService name needs to be globally unique even in internal app service environments

### ISSUE THREAD

**Issue by eliasgrueninger** [terraform-providers/terraform-provider-azurerm#3003]
### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.22.1

### Affected Resource(s)

* resource_arm_app_service

### Expected Behavior

Creation of AppServices in isolated App Service Environements should be possible with names which are only unique in the scope of the ASE. Working well on the Azure Portal (need to set the subscription, resource group and app service plan in order to get the correct dns zone for the name validation)

### Actual Behavior

Error Message "The name [...] used for the App Service needs to be globally unique and isn't available: Hostname [...] already exists. Please select a different name."

### Steps to Reproduce

Create an AppService Resource into an ASEv2 with an Isolated AppServicePlan with a name of an AppService which is already taken [...].azurewebsites.net

### References

Quickly checked the source code. Looks like the name check in resource_arm_app_service.go starting on line 216 does not consider being executed on a isolated ASE.
https://github.com/terraform-providers/terraform-provider-azurerm/blob/a28128133d8c66a03927b81a765a7539e590599b/azurerm/resource_arm_app_service.go#L216-L227

**Comment by kpatryk** [comment]
I faced the same issue for isolated VNET. I applied **quick and dirty fix** and released it [here](https://github.com/kpatryk/terraform-provider-azurerm/releases/tag/v1.24.0_kpatryk)

To download fix locally:

`curl -L https://github.com/kpatryk/terraform-provider-azurerm/releases/download/v1.24.0_kpatryk/terraform-provider-azurerm_v1.24.0 -o ~/.terraform.d/plugins/terraform-provider-azurerm_v1.24`

**Note: It should be used only for VNET internal deployments as the global check has been ignored.**
