### ISSUE TITLE
Application gateway WAF upload file size limit is set to 0 by default

### ISSUE THREAD

**Issue by uritau** [terraform-providers/terraform-provider-azurerm#3011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Latest

### Affected Resource(s)

* `azurerm_application_gateway`
More specific: in the waf configuration block upload file size limit (file_upload_limit_mb) 

### Expected Behavior
If Application gateway WAF upload file size limit is not set, the default value must be 100. (file_upload_limit_mb).

From the documentation: 
> file_upload_limit_mb - (Optional) The File Upload Limit in MB. Accepted values are in the range 1MB to 500MB. Defaults to 100MB.

### Actual Behavior
The Application Gateway it's deployed with a 0 as file size limit.
Theorically, the size limit (from Azure documentation) goes from 1 to 100 (or 500) Mb.
But, in fact, it's possible to define as 0, and it seems that, by default, Terraform is setting it to this value.

### Steps to Reproduce

1. Deploy without specifiying file_upload_limit_mb.
2. Check the upload file max size allowed, (You can check it uploading a file (even small than 1 Mb) and it will block you.)

### References
https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html
https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-waf-configuration

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #3012
