### ISSUE TITLE
Use multiple variables & Strings in terraform - Azure

### ISSUE THREAD

**Issue by emacdonald25** [terraform-providers/terraform-provider-azurerm#3013]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
provider.azurerm v1.22.0

### Affected Resource(s)
azurerm_resource_group

### Terraform Configuration Files

```hcl
provider "azurerm" {

version = "=1.22.0"
subscription_id = "${var.subscription_id}"
client_id = "${var.client_id}"
client_secret = "${var.client_secret}"
tenant_id = "${var.tenant_id}"
}

#Create Resource Groups
resource "azurerm_resource_group" "rg1" {
name = "${var.cus}-${var.region}-rg-compute-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg2" {
name = "${var.cus}-${var.region}-rg-networking-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg3" {
name = "${var.cus}-${var.region}-rg-storage-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg4" {
name = "${var.cus}-${var.region}-rg-web-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg5" {
name = "${var.cus}-${var.region}-rg-databases-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg6" {
name = "${var.cus}-${var.region}-rg-intelligence-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg7" {
name = "${var.cus}-${var.region}-rg-iot-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg8" {
name = "${var.cus}-${var.region}-rg-security-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg9" {
name = "${var.cus}-${var.region}-rg-devlopertools-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg10" {
name = "${var.cus}-${var.region}-rg-management-${var.env}"
location = "${var.region}"
}

resource "azurerm_resource_group" "rg11" {
name = "${var.cus}-${var.region}-rg-addons-${var.env}"
location = "${var.region}"

}
```

### Debug Output
```hcl
azurerm_resource_group.rg9: "name" may only contain alphanumeric characters, dash, underscores, parentheses and periods
```

### Expected Behavior
Create Resource Groups

### Actual Behavior
Error - see error message
azurerm_resource_group.rg9: "name" may only contain alphanumeric characters, dash, underscores, parentheses and periods

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
hi @emacdonald25,

Without seeing your var file, or the contents of the variables your passing in it is hard to see whats going on, do you mind sharing those so we can debug this further?

Thanks

**Comment by emacdonald25** [comment]
variables.tf

#variables
variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id"  {}
variable "region" {}
variable "cus" {}
variable "env" {}

Outside of the subkeys, I'm passing this in from VS code


C:\Users\emc\Desktop\terraform> .\terraform.exe plan
var.cus
  Enter a value: lul

var.env
  Enter a value: prod

var.region
  Enter a value: East US

**Comment by tombuildsstuff** [comment]
hi @emacdonald25 

Looking at this resource:

```
resource "azurerm_resource_group" "rg9" {
name = "${var.cus}-${var.region}-rg-devlopertools-${var.env}"
location = "${var.region}"
}
```

and the values being provided:

```
C:\Users\emc\Desktop\terraform> .\terraform.exe plan
var.cus
Enter a value: lul

var.env
Enter a value: prod

var.region
Enter a value: East US
```

It appears there's a space in the region (which in itself would be fine) - however since it's being used for the resource group name (which doesn't allow spaces in the name) - is why you're seeing this validation error:

```
azurerm_resource_group.rg9: "name" may only contain alphanumeric characters, dash, underscores, parentheses and periods
```

If you remove the space from the region (for example, updating it to `eastus`) this should work as expected - would you be able to take a look and see if that works for you? Since this is a question regarding Terraform Configuration rather than a bug in Terraform, I'm going to close this issue however please let us know if that doesn't work for you and we'll take another look :)

Thanks!
