### ISSUE TITLE
PEM certificate support of key_vault_certificate resource

### ISSUE THREAD

**Issue by dominik-lekse** [terraform-providers/terraform-provider-azurerm#3017]
I intend to import a certificate including a private key in PEM format into an Azure Key Vault using the resource `key_vault_certificate`. The documentation provides an example for this for a certificate in PFX/PKCS12 format.

I tried to set the `secret_properties.content_type` to `application/x-pem-file` and provided the certificate as follows in PEM format.

```hcl
resource "azurerm_key_vault_certificate" "certificate" {
    ...
    
    certificate {
        contents = "${base64encode("${tls_locally_signed_cert.certificate.cert_pem}\n${tls_self_signed_cert.ca.cert_pem}\n${tls_private_key.certificate.private_key_pem}")}"
        password = ""
    }

    secret_properties {
      content_type = "application/x-pem-file"
    }
    ...
}
```

If the import of a PEM certificate including, it would be great if we could add an additional example to the documentation of the 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.11
+ provider.azurerm v1.22.1
+ provider.tls v1.2.0
```

### Affected Resource(s)

* `azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
resource "tls_private_key" "ca" {
    algorithm = "RSA"
    rsa_bits = 2048
}

resource "tls_self_signed_cert" "ca" {
    key_algorithm   = "${tls_private_key.ca.algorithm}"
    private_key_pem = "${tls_private_key.ca.private_key_pem}"

    validity_period_hours = "${24 * 30 * 12 * 4}" // 4 Years
    early_renewal_hours = "${24 * 30}"

    is_ca_certificate = true

    allowed_uses = [
      "cert_signing",
      "crl_signing",
    ]

    subject {
      common_name  = "Some CA"
      organization = "Some Organization"
      organizational_unit = ""
      country = ""
      locality = ""
      postal_code = ""
      province = ""
      serial_number = ""
    }
}

resource "tls_private_key" "certificate" {
    algorithm = "RSA"
    rsa_bits = 2048
}

resource "tls_cert_request" "certificate" {
    key_algorithm   = "${tls_private_key.certificate.algorithm}"
    private_key_pem = "${tls_private_key.certificate.private_key_pem}"

    subject {
        common_name  = "some.service.com"
        organization = "Some Organization"
    }
}

resource "tls_locally_signed_cert" "certificate" {
    cert_request_pem = "${tls_cert_request.certificate.cert_request_pem}"

    ca_cert_pem = "${tls_self_signed_cert.ca.cert_pem}"
    ca_key_algorithm = "${tls_self_signed_cert.ca.key_algorithm}"
    ca_private_key_pem = "${tls_private_key.ca.private_key_pem}"

    validity_period_hours = "${24 * 30 * 12 * 4}" // 4 Years

    allowed_uses = [
        "key_encipherment",
        "digital_signature",
        "server_auth",
    ]
}

resource "azurerm_key_vault_certificate" "certificate" {
  name     = "some-certificate"
  key_vault_id = "${azurerm_key_vault.vault.id}"

  certificate {
    contents = "${base64encode("${tls_locally_signed_cert.certificate.cert_pem}\n${tls_self_signed_cert.ca.cert_pem}\n${tls_private_key.certificate.private_key_pem}")}"
    password = ""
  }

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = "${tls_private_key.certificate.rsa_bits}"
      key_type   = "${tls_private_key.certificate.algorithm}"
      reuse_key  = false
    }

    secret_properties {
      # content_type = "application/x-pkcs12"
      content_type = "application/x-pem-file"
    }
  }
}
```

### Debug Output

```
* azurerm_key_vault_certificate.tfe_mgmt: 1 error(s) occurred:

* azurerm_key_vault_certificate.tfe_mgmt: keyvault.BaseClient#ImportCertificate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="PEM is in unexpected format"
```

### Expected Behavior

- The certificate is successfully imported into the key vault

### Actual Behavior

- Creating the azurerm_key_vault_certificate fails with `PEM is in unexpected format`

## References

- https://github.com/MicrosoftDocs/azure-docs/issues/16543
- https://github.com/MicrosoftDocs/azure-docs/issues/23558

**Comment by msfcolombo** [comment]
It looks like you are trying to concatenate the certificate and private key `.pem` files, and **then converting to base64url**. Did you try to import directly without this encoding?

**Comment by erwabo** [comment]
This is great, I was wondering how I could do this with a 3rd party CA. I need to request a cert from Sectigo (Used to be commodo) and likewise end up with a PFX to dump to Azure KV

**Comment by njuCZ** [comment]
according to https://github.com/MicrosoftDocs/azure-docs/issues/23558#issuecomment-460485031 it's a service bug. I think maybe we should wait for the fix of this feature. Before that, we would better use the format `pfx`, rather than work it around

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through this appears to be fixed in the API now, albeit with some changes required to make the PEM readable to KeyVault: https://github.com/MicrosoftDocs/azure-docs/issues/23558#issuecomment-499396930

As such I'm going to close this issue for the moment - but please let us know if your still seeing this and we'll take another look.

Thanks!
