### ISSUE TITLE
azurerm_api_management.security.disable_triple_des_chipers has incorrect spelling

### ISSUE THREAD

**Issue by SeanEGray** [terraform-providers/terraform-provider-azurerm#3021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.22.1

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "example" {
  name                = "example"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"
  sku {
    name     = "Standard"
    capacity = 1
  }
  security {
    disable_triple_des_chipers = true
  }
}
```

### Expected Behavior

The property azurerm_api_management.security.disable_triple_des_chipers should be spelt azurerm_api_management.security.disable_triple_des_ciphers.

### Actual Behavior

The property is spelt azurerm_api_management.security.disable_triple_des_chipers.

### Suggested resolution

I'm happy to submit a pull request updating the name of this property, but this would be a breaking change so would appreciate guidance on how you'd like to handle that.

**Comment by mbfrahry** [comment]
Hey @SeanEGray, thanks for opening this issue. Apologies for the delay. Luckily this is a fairly straightforward fix. You'll want to add the new attribute and add a `ConflictsWith: []string{"security.0.disable_triple_des_chipers"}`. Then in the wrongly named attribute, you'll add a deprecated messaged like `				

```
Deprecated:    "This property has been deprecated in favour of security.0.disable_triple_des_ciphers property. This  will be removed in version 2.0 of the provider",
```
.

You'll want to keep the old attribute the same but make sure that you read/set the new attribute name properly in the create/update/read methods. Feel free to ask any further questions and I'll be happy to help get this issue closed if you don't have the time anymore.

**Comment by ReenuSaluja** [comment]
I will work on this.
