### ISSUE TITLE
New Data Source: ExpressRoute

### ISSUE THREAD

**Issue by rambk** [terraform-providers/terraform-provider-azurerm#3022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Creating a peering on an ExpressRoute circuit is dependent on Provider Status of the ExpressRoute circuit being "Provisioned". To change the provider status to "Provisioned", the service provider have to call certain API (this is not instantaneous, and involves activation through the provider portal).

In order to check if the provider status is changed to Provisioned and kick off peering creation, we need the ExpressRoute data source for provider_status. 

### New or Affected Resource(s)

* azurerm_express_route data source

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-routing-portal-resource-manager

**Comment by tombuildsstuff** [comment]
Fixed via #3158
