### ISSUE TITLE
ExpressRoute Fastpath connection option

### ISSUE THREAD

**Issue by rambk** [terraform-providers/terraform-provider-azurerm#3027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Virtual network gateway connection object for ExpressRoute supports 'ExpressRouteGatewayBypass' option. This option needs to be made available under Terraform.

### New or Affected Resource(s)

VirtualNetworkGatewayConnection

The swagger spec is available at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-12-01/virtualNetworkGateway.json

### References

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-12-01/virtualNetworkGateway.json

**Comment by mattdot** [comment]
It looks like the gateway_bypass option was added to the provider already, is this issue asking for a VirtualNetworkGatewayConnection data source?

**Comment by tombuildsstuff** [comment]
@mattdot agreed, thanks for the ping - [from what I can see this has been fixed](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway_connection.html#express_route_gateway_bypass) and as such I'm going to close this issue for the moment. Thanks!
