### ISSUE TITLE
Update documentation for azurerm_key_vault_* according to #2396

### ISSUE THREAD

**Issue by mjiderhamn** [terraform-providers/terraform-provider-azurerm#3029]
The changes in #2396 are not reflected in the documentation. See #2396 discussion.

**Comment by dominik-lekse** [comment]
I assume this issue includes updating the documentation `azurerm_key_vault_*` data sources.

The examples provided in the documentation of the `azurerm_key_vault_*` data sources are currently broken as the preferred `key_vault_id` field is not documented.
