### ISSUE TITLE
Remote state lock release error - severe issue

### ISSUE THREAD

**Issue by samirageb** [terraform-providers/terraform-provider-azurerm#303]
This behavior appears to have started with terraform 10.3 and the only workaround I have atm is to disable state locking.

### Terraform Version
0.10.3
go runtime 1.9

### Affected Resource(s)
- azurerm_resource_group
- anything really, this this is tied to remote state

### Terraform Configuration Files
```hcl
variable "rg_name"                      { }
variable "location"                     { }

# Remote state data source, no interpolations allowed
terraform {
  backend "azurerm" {
    key = "***.terraform.tfstate"
    storage_account_name = "***"
    container_name       = "terraform-state"
  }
}

# Configure TF provider: Microsoft Azure
provider "azurerm" {
  version         = "~> 0.1"
  subscription_id = "***"
  client_id       = "***"
  client_secret   = "***"
  tenant_id       = "***"
}

resource "azurerm_resource_group" "bug_eastus" {
  name     = "${var.rg_name}"
  location = "${var.location}"
}
```

### Debug Output
[Terraform Init Output](https://gist.github.com/samirageb/01ae95a16c5342e8b47c6d9781fcb818)

[Terraform Apply Output](https://gist.github.com/samirageb/d31c2e4414d72f8ba2f80bfbb79a7027)

### Expected Behavior
Command returns upon completion

### Actual Behavior
-Azure Rg successfully gets provisioned
-Lease on remote .tfstate Azure blob still shows 'leased', and must be manually broken

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
-I have confirmed this happens regardless of Azure storage account encryption at rest
-Appending a `-lock=false` to all terraform commands is the current workaround
-The repro steps were conducted on a fresh directory, with no .terraform folder created, or existing remote state file.
-Eventually this issue results in a .errorstate, which CAN be succesfully pushed if I manually delete the lease on the .tfstate blob

### References
None

**Comment by nbering** [comment]
As of Terraform v0.1.0, each of the provider plugins that were previously part of Terraform Core were split into their own repositories.

The functionality you're describing actually still belongs to [Terraform Core](https://github.com/hashicorp/terraform). In particular the source can be found under [backends](https://github.com/hashicorp/terraform/tree/master/backend/remote-state/azure). I would check with core to see if there is an existing related issue, and if not report it to the core maintainers.

**Comment by samirageb** [comment]
I've posted up the issue in TF core.  [Reference](https://github.com/hashicorp/terraform/issues/16012)

**Comment by tombuildsstuff** [comment]
Hey @samirageb 

Thanks for opening this issue :)

I've taken a look into this today and have opened the PR https://github.com/hashicorp/terraform/pull/16015 which includes a fix for this issue. Given this issue is being tracked on the main repository - I'm going to close this issue in favour of the issue on the main repository.

Thanks!
