### ISSUE TITLE
Terraform for Azure SQL Managed instance

### ISSUE THREAD

**Issue by ganeshmedhekar** [terraform-providers/terraform-provider-azurerm#3041]
We do have a requirement where we have to build the customize Terraform script for Azure SQL managed instance. do we have existing any template or the feature has not been added yet?

**Comment by tombuildsstuff** [comment]
hi @ganeshmedhekar 

Thanks for opening this issue :)

Support for SQL Managed Instances is being tracked in #3041 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one, would you mind subscribing to that one for updates?

Thanks!

**Comment by katbyte** [comment]
this is being tracked in #1747
