### ISSUE TITLE
Importing azurerm_lb infrastructure does not import frontend_ip_configuration

### ISSUE THREAD

**Issue by pather87** [terraform-providers/terraform-provider-azurerm#305]
Hi there,

i recognized that when import an azurerm_lb it does not import the frontend_ip_configuration.

### Terraform Version
Terraform v0.10.3

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_lb

### Terraform .tfstate
https://gist.github.com/pather87/0670cf13a66360de068edbb605d0f5dd

### Expected Behavior
frontend_ip_configuration state exists inside azure_lb state

### Actual Behavior
No frontend_ip_configuration state

### Important Factoids
Nothing special known

**Comment by mbfrahry** [comment]
Hey @pather87, just ran some tests to confirm that this is still an issue and could not reproduce it. Are you still having trouble with this and if so could you post what the resource block of the load balancer looks like in your tffile?

**Comment by tombuildsstuff** [comment]
ping @panther87 :)

**Comment by tombuildsstuff** [comment]
ping @pather87

**Comment by tombuildsstuff** [comment]
hey @panther87

Given we've not heard back and @mbfrahry has been unable to reproduce this, I'm going to close this issue for the moment - however please feel free to comment/re-open this if you're still seeing issues and we'll take another look

Thanks!

**Comment by jkubrynski** [comment]
I confirm that on 
```
Terraform v0.11.2
+ provider.azurerm v1.1.0
```
the issue still exists.

**Comment by jkubrynski** [comment]
@rcarun how can I help with reproducing this issue?
