### ISSUE TITLE
"network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead

### ISSUE THREAD

**Issue by enorlando** [terraform-providers/terraform-provider-azurerm#3054]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.11.13
+ provider.azuread v0.2.0
+ provider.azurerm v1.23.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "xx" {
  name                 = "xx"
  resource_group_name  = "${azurerm_resource_group.xx.name}"
  virtual_network_name = "${azurerm_virtual_network.xx.name}"
  address_prefix       = "xx"

  # network_security_group_id = "${azurerm_network_security_group.xx.id}"
}

```

### Expected Behavior

Once we remove  `network_security_group_id = "${azurerm_network_security_group.xx.id}"`
from the `azurerm_subnet` resource and use below resource instead
`resource "azurerm_subnet_network_security_group_association"`
we should have no infrastructure changes.

We have followed

https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html
### Actual Behavior

When Terraform plan is run, it wants to change the resource

~ azurerm_subnet.scgaddssubnet
     ` network_security_group_id: "/subscriptions/xx/resourceGroups/xx/providers/Microsoft.Network/networkSecurityGroups/xx" => ""`

If we include `network_security_group_id = "${azurerm_network_security_group.xx.id}"` under `azurerm_subnet` we get the following warning 

`Warning: azurerm_subnet.scgaddssubnet: "network_security_group_id": [DEPRECATED] Use the azurerm_subnet_network_security_group_association resource instead`
### Steps to Reproduce

1. `az login`
2. `Terraform init`
3. `Terraform plan`
### References

* https://github.com/Azure/terraform-azurerm-vnet/issues/15
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/2526

**Comment by brent-robinson** [comment]
Agreed. I'm experiencing Terraform add or remove the NSG in each run.

**Second run:**
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_subnet.blue-compute-subnet
      network_security_group_id: "/subscriptions/********-****-****-****-************/resourceGroups/dev1/providers/Microsoft.Network/networkSecurityGroups/blue-compute-subnet-nsg" => ""

  ~ azurerm_subnet.green-compute-subnet
      network_security_group_id: "/subscriptions/********-****-****-****-************/resourceGroups/dev1/providers/Microsoft.Network/networkSecurityGroups/green-compute-subnet-nsg" => ""


Plan: 0 to add, 2 to change, 0 to destroy.
```

**Third run**
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + azurerm_subnet_network_security_group_association.blue-compute-subnet-nsg-association
      id:                        <computed>
      network_security_group_id: "/subscriptions/********-****-****-****-************/resourceGroups/dev1/providers/Microsoft.Network/networkSecurityGroups/blue-compute-subnet-nsg"
      subnet_id:                 "/subscriptions/********-****-****-****-************/resourceGroups/dev1/providers/Microsoft.Network/virtualNetworks/dev1-network/subnets/blue-compute-subnet"

  + azurerm_subnet_network_security_group_association.green-compute-subnet-nsg-association
      id:                        <computed>
      network_security_group_id: "/subscriptions/********-****-****-****-************/resourceGroups/dev1/providers/Microsoft.Network/networkSecurityGroups/green-compute-subnet-nsg"
      subnet_id:                 "/subscriptions/********-****-****-****-************/resourceGroups/dev1/providers/Microsoft.Network/virtualNetworks/dev1-network/subnets/green-compute-subnet"


Plan: 2 to add, 0 to change, 0 to destroy.
```

The process repeats after this.

Using _both_ `azurerm_subnet_network_security_group_association` and `azurerm_subnet.network_security_group_id` works around this issue, until destroy, in which case an infinite loop of waiting occurs.

**Comment by dcuenot** [comment]
Same behavior on my side :(

**Comment by tombuildsstuff** [comment]
hi @enorlando 

Thanks for opening this issue :)

Unfortunately at this time the association between the Subnet and the Network Security Group needs to be specified in both the `azurerm_subnet` and the `azurerm_subnet_network_security_group_association` resource, this is to ensure this isn't a breaking change. We plan to change this behaviour in version 2.0 of the Provider, such that this will only need to be set on the `azurerm_subnet_network_security_group_association ` resource (and the `network_security_group_id` field on the `azurerm_subnet` field will be removed); however as mentioned above unfortunately prior to 2.0 this needs to be specified in both resources, as such this is noted in the documentation:

> NOTE: Subnet <-> Network Security Group associations currently need to be configured on both this resource and using the network_security_group_id field on the azurerm_subnet resource. The next major version of the AzureRM Provider (2.0) will remove the network_security_group_id field from the azurerm_subnet resource such that this resource is used to link resources in future.

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by enorlando** [comment]
Hi @tombuildsstuff 

Thanks for the reply.

We have added `network_security_group_id` back to resource `azurerm_subnet`. The warning below is seen when we run a terraform plan

`Warning: azurerm_subnet.scgaddssubnet: "network_security_group_id": [DEPRECATED] Use the azurerm_subnet_network_security_group_association resource instead.`

So the assumption is we will continue to get this warning until veriosn 2.0 of  the `azurerm` provider is released?

**Comment by tombuildsstuff** [comment]
@enorlando correct, as mentioned above it's unfortunate both have to be specified at this time, but this is to prevent a breaking change. When 2.0 of the Provider comes out ([more details on what's included here](https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html)) - you'll only need to use the `azurerm_subnet_network_security_group_association` resource.

**Comment by weskerfoot** [comment]
Why was this issue closed?
