### ISSUE TITLE
Feature Request: Azure Event Hub - Add 'Do not emit empty files' option

### ISSUE THREAD

**Issue by sinn1** [terraform-providers/terraform-provider-azurerm#3057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Event Hub capture_description doesn't include the option 'Do not emit empty files when no events occur during the Capture time window' which is available in the Azure UI portal.

![event-hub-capture](https://user-images.githubusercontent.com/2838605/54450607-bf0c9100-4748-11e9-9d26-1079d0731a50.jpg)

### New or Affected Resource(s)

* azurerm_eventhub

### Potential Terraform Configuration

```hcl
capture_description {
    emitEmptyFiles = false|true
  }
```

**Comment by Lucretius** [comment]
I have picked this up and got it working - I just need to add some unit tests.
