### ISSUE TITLE
Data Source: azurerm_recovery_services_protection_policy_vm

### ISSUE THREAD

**Issue by mariuszdotnet** [terraform-providers/terraform-provider-azurerm#3063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.23.0
+ provider.random v2.0.0

### Affected Resource(s)

Data Source: [azurerm_recovery_services_protection_policy_vm](https://www.terraform.io/docs/providers/azurerm/d/recovery_services_protection_policy_vm.html)

### Debug Output

Error: Error running plan: 1 error(s) occurred:

* azurerm_recovery_services_protected_vm.vmstamp: Can not parse "backup_policy_id" as a resource id: No subscription ID found in: "Subscriptions/5aec60e9-f535-4bd7-a951-2833f043e918/resourceGroups/backup-vault-rg/providers/Microsoft.RecoveryServices/vaults/mk-vm-vault/backupPolicies/DefaultPolicy"

### Expected Behavior

backup_policy_id    = "${data.azurerm_recovery_services_protection_policy_vm.vmstamp.id}"

should return the resource id of the policy.

"subscriptions/5aec60e9-f535-4bd7-a951-2833f043e918/resourceGroups/backup-vault-rg/providers/Microsoft.RecoveryServices/vaults/mk-vm-vault/backupPolicies/DefaultPolicy"

### Actual Behavior

I get this error

Error: Error running plan: 1 error(s) occurred:

* azurerm_recovery_services_protected_vm.vmstamp: Can not parse "backup_policy_id" as a resource id: No subscription ID found in: "Subscriptions/5aec60e9-f535-4bd7-a951-2833f043e918/resourceGroups/backup-vault-rg/providers/Microsoft.RecoveryServices/vaults/mk-vm-vault/backupPolicies/DefaultPolicy"

### Steps to Reproduce

define data reference for existing resource:

data "azurerm_recovery_services_protection_policy_vm" "vmstamp" {
  name                = "DefaultPolicy"
  recovery_vault_name = "mk-vm-vault"
  resource_group_name = "backup-vault-rg"
}

try to reference its ID in resource "azurerm_recovery_services_protected_vm"

resource "azurerm_recovery_services_protected_vm" "vmstamp" {
  resource_group_name = "${data.azurerm_recovery_services_protection_policy_vm.vmstamp.resource_group_name}"
  recovery_vault_name = "${data.azurerm_recovery_services_protection_policy_vm.vmstamp.recovery_vault_name}"
  backup_policy_id    = "${data.azurerm_recovery_services_protection_policy_vm.vmstamp.id}"
  source_vm_id        = "/subscriptions/5aec60e9-f535-4bd7-a951-2833f043e918/resourceGroups/sql-server-rg/providers/Microsoft.Compute/virtualMachines/testsqlserver"
}

terraform plan

### Important Factoids

Hardcoding the backup_policy_id to the resource works.  Note the subscription Key/Value starts with a lower S, where as the error returns it with a capital S.

backup_policy_id    = "/subscriptions/5aec60e9-f535-4bd7-a951-2833f043e918/resourceGroups/backup-vault-rg/providers/Microsoft.RecoveryServices/vaults/mk-vm-vault/backupPolicies/DefaultPolicy"

another way to confirm this is to put lower() function around the id from the data source and it works fine.

backup_policy_id    = "${lower(data.azurerm_recovery_services_protection_policy_vm.vmstamp.id)}"

* #0000

**Comment by mcharriere** [comment]
I've found that this is a know [issue in the azure SDK ](https://github.com/Azure/azure-sdk-for-go/issues/2824)
I'm adding a workaround as in the azurerm_recovery_service_protection_policy_vm resource.
