### ISSUE TITLE
Feature Request: Add support for Azure Container SAS tokens

### ISSUE THREAD

**Issue by jrauschenbusch** [terraform-providers/terraform-provider-azurerm#3068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is no native support for Azure Service SAS tokens.

As already mentioned #59 there are different types of SAS tokens.

To allow a more fine-grained access control it would be nice to have native support inside terraform without the need to use local-exec. 

As the configuration options (especially the permission semantic) for Service SAS tokens depends on the service type i would suggest to create different SAS data sources for each of the following types: `blob`, `container`, `share`, `file`, `queue`, `table`

### New or Affected Resource(s)

* azurerm_storage_container_sas
* azurerm_storage_\<type\>_sas

### Potential Terraform Configuration

```hcl
data "azurerm_storage_container_sas" "foo" {
  connection_string = "DefaultEndpointsProtocol=https;..."
  https_only = true
  ip = "127.0.0.1" // optional

  container_name = "bar"

   // Response header settings
  cache-control = ""
  content-disposition = ""
  content-encoding =  ""
  content-language = ""
  content-type = ""

  start  = "2019-03-18" // optional
  expiry = "2020-01-01"

  permissions {
    read    = true
    write   = true
    delete  = true
    list    = true
    add     = true
    create  = true
  }

  // access policy as alternative for permissions and  validity period
  policy-name = ""
}

```

### References
* https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas
* https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas
*  https://github.com/terraform-providers/terraform-provider-azurerm/issues/59#issuecomment-374761772

**Comment by dominik-lekse** [comment]
I agree with @jrauschenbusch that there is a need for more extensive support for SAS tokens of different types.

In my opinion, it would be helpful to have resources instead of data sources for SAS tokens. The advantage of resources in this case is, that the generated SAS tokens stay persistent across multiple Terraform runs. An example use case is passing an Azure Storage Blob URL in the virtual machine custom script extension with a SAS token.

**Comment by aambert** [comment]
Bump really need to get SAS Token for a Azure File Share to append file upload for local exec

**Comment by r0bnet** [comment]
I'll implement it as soon as this PR is through: https://github.com/hashicorp/go-azure-helpers/pull/34

**Comment by r0bnet** [comment]
PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4195
