### ISSUE TITLE
Data source azurerm_api_management breaks when custom domain present

### ISSUE THREAD

**Issue by laurencee** [terraform-providers/terraform-provider-azurerm#3072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.23.0

### Affected Resource(s)

* data source `azurerm_api_management`

### Terraform Configuration Files

```hcl
data "azurerm_api_management" "test" {
  name                = "my-apim-instance"
  resource_group_name = "my-rg"
}
```

### Expected Behavior

The data source is usable

### Actual Behavior

```
data.azurerm_api_management.test: data.azurerm_api_management.test: Error setting `hostname_configuration`: Invalid address to set: []string{"hostname_configuration", "0", "portal", "0", "default_ssl_binding"}
```

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

**Comment by magodo** [comment]
Fixed by #3385
