### ISSUE TITLE
Crash when importing container group

### ISSUE THREAD

**Issue by booyaa** [terraform-providers/terraform-provider-azurerm#3078]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.22.1

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "instance1" {}
```

### Debug Output

[debug.log](https://gist.github.com/booyaa/092322af0fc82458daf45c5a7a2063c4)

### Panic Output

[crash.log](https://gist.github.com/booyaa/e6e7c3cf90ae05a29cce0863d54e7512)

### Expected Behavior

Terraform state should have been updated with the newly imported `azurerm_container_group` resource `instance`.

### Actual Behavior

Terraform crashed out.

### Steps to Reproduce

```bash
terraform import azurerm_container_group.instance1 /subscriptions/__SUBSCRIPTION_ID_REDACTED__/resourceGroups/__RESOURCE_GROUP_REDACTED__/providers/Microsoft.ContainerInstance/containerGroups/__CONTAINER_GROUP_NAME_REDACTED__
```

### References

Suspect the cause for the crash is that I'm trying to import a container group that uses an IP Address type of Private. There's an outstanding PR for this.

* [PR#2314](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2314)

**Comment by neil-yechenwei** [comment]
@booyaa , Thanks for opening this issue. I suspect [`props.IPAddress.Ports`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/57c6727c6d4e9f468ea51693c5d31f17759eada8/azurerm/resource_arm_container_group.go#L391) is `nil` during apply. In latest azurerm version, I assume this issue has been [fixed](https://github.com/terraform-providers/terraform-provider-azurerm/blob/1b0da11661ac81ea7ef02096d7ae94557c27fa97/azurerm/internal/services/containers/container_group_resource.go#L547). And I can import successfully now with below tfconfig and latest azurerm. Could you help to double check whether the issue still exists? If still exists, could you share you tfconfig to create container group? Thanks.
tfconfig to create container group:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-containergrouptest"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "testcgvnet"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.1.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "testcgsubnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.1.0.0/24"

  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.ContainerInstance/containerGroups"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_network_profile" "test" {
  name                = "testnetcgprofile"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  container_network_interface {
    name = "testcnic"

    ip_configuration {
      name      = "testipconfig"
      subnet_id = azurerm_subnet.test.id
    }
  }
}

resource "azurerm_container_group" "test" {
  name                = "acctestcontainergroup-cgtest"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  ip_address_type     = "Private"
  network_profile_id  = azurerm_network_profile.test.id
  os_type             = "Linux"

  container {
    name   = "hw"
    image  = "microsoft/aci-helloworld:latest"
    cpu    = "0.5"
    memory = "0.5"
	ports {
      port = 80
    }
  }
}
```

cmd to import container group:
```
terraform import azurerm_container_group.test /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-containergrouptest/providers/Microsoft.ContainerInstance/containerGroups/acctestcontainergroup-cgtest
```

**Comment by booyaa** [comment]
Yup can confirm this has been fixed! Thanks everyone!
