### ISSUE TITLE
Storage Account - Support Web and DFS endpoints

### ISSUE THREAD

**Issue by pallxk** [terraform-providers/terraform-provider-azurerm#3082]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Storage Account of kind StorageV2 (general purpose v2) offers endpoints for web and dfs, in addition to blob, file, queue and table. I'd like to have those endpoints exported by terraform azurerm provider.

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "demo" {
  name                     = "demo"
  location                 = "location"
  resource_group_name      = "resource_group_name"

  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "RAGRS"
}

output "primary_web_endpoint" {
  value = "${azurerm_storage_account.demo.primary_web_endpoint}"
}
output "primary_web_host" {
  value = "${azurerm_storage_account.demo.primary_web_host}"
}
output "secondary_web_endpoint" {
  value = "${azurerm_storage_account.demo.secondary_web_endpoint}"
}
output "secondary_web_host" {
  value = "${azurerm_storage_account.demo.secondary_web_host}"
}
output "primary_dfs_endpoint" {
  value = "${azurerm_storage_account.demo.primary_dfs_endpoint}"
}
output "primary_dfs_host" {
  value = "${azurerm_storage_account.demo.primary_dfs_host}"
}
output "secondary_dfs_endpoint" {
  value = "${azurerm_storage_account.demo.secondary_dfs_endpoint}"
}
output "secondary_dfs_host" {
  value = "${azurerm_storage_account.demo.secondary_dfs_host}"
}

```

### References

* `az storage account show`
* https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website
* https://azure.microsoft.com/en-us/blog/static-websites-on-azure-storage-now-generally-available/

**Comment by Lucretius** [comment]
This will require an SDK bump - these endpoints are supported in storage version 2018-02-01 which is not included in our SDK version.

**Comment by pallxk** [comment]
It seems that we just bumped the SDK version to 2018-02-01 several days ago.. See 7bf3fdc6d413fe4329b31ab7a6d4bac761672bbd

By the way, I'm willing to help on this since the change required seems trivial.
