### ISSUE TITLE
Provide terraform 0.12 beta support

### ISSUE THREAD

**Issue by darkedges** [terraform-providers/terraform-provider-azurerm#3101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Morning,
in https://github.com/terraform-providers/terraform-provider-azurerm/issues/2686 it mentions that you wont provide support till the 0.12 beta is released.

https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta1

If this is possible it would be great, as I have a number of issues that I want  to check with 0.12 and its new language support, mainly around resources that have not been defined.

Regards
Nicholas Irving

**Comment by tombuildsstuff** [comment]
hi @darkedges 

Thanks for opening this issue :)

Support for Terraform 0.12 is underway and being tracked in #2968 - at this time we're still waiting for some bugs in the Provider SDK to be fixed before we're able to merge this, however our intention is for this to go out in it's own release (currently scheduled for v1.25, but it may change) - depending on when those bugs are fixed.

Thanks!
