### ISSUE TITLE
API Management Product Not Setting Attributes

### ISSUE THREAD

**Issue by simongh** [terraform-providers/terraform-provider-azurerm#3105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.11.11
AzureRm 1.23.0

### Affected Resource(s)

* `azurerm_api_management_product`

### Terraform Configuration Files

```
resource "azurerm_api_management_product" "my_cool_product" {
  product_id = "my-cool-product"
  api_management_name = "${azurerm_api_management.api.name}"
  resource_group_name = "${azurerm_api_management.api.resource_group_name}"
  display_name = "My Cool API"
  subscription_required = true
  approval_required = true
  published = true
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
The approval required should be set

### Actual Behavior
Everytime you deploy this:

```
Terraform will perform the following actions:

  ~ azurerm_api_management_product.my_cool_product
      approval_required: "false" => "true"
```

### Steps to Reproduce

Create a api management resource
Add a product as above

1. `terraform apply`

### References

* #0000

**Comment by Lucretius** [comment]
Looking at the code, there is this check:

```
	if subscriptionRequired && subscriptionsLimit > 0 {
		properties.ProductContractProperties.ApprovalRequired = utils.Bool(approvalRequired)
		properties.ProductContractProperties.SubscriptionsLimit = utils.Int32(int32(subscriptionsLimit))
	}
```

However, `subscriptions_limit` is optional, and will default to the zero value if not set.  Could you try setting it and re-applying to see if this solves the problem?  If so, I can update the documentation to make this requirement obvious.

**Comment by simongh** [comment]
@Lucretius That worked. Setting the subscriptions limit caused it to set the attribute correctly

**Comment by Lucretius** [comment]
Great - I’ll update the documentation accordingly

**Comment by mbfrahry** [comment]
Hey @simongh, we've added validation to  prevent this specific interaction from happening. It'll come out in the next release (1.32.1) and feel free to reopen this issue if you continue to see this.
