### ISSUE TITLE
Error importing azurerm_lb_backend_address_pool

### ISSUE THREAD

**Issue by martin-displayr** [terraform-providers/terraform-provider-azurerm#3120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.23.0

### Affected Resource(s)

* `azurerm_lb_backend_address_pool`

### Terraform Configuration Files

I don't want to share for now as this contains propitiatory information. I can email to whoever is looking into this.

### Debug Output

I don't want to share for now as this contains propitiatory information. I can email to whoever is looking into this.

### Expected Behavior

Resources get imported into .tf configuration

### Actual Behavior

This error (I have replaced the guids and some of the resource names):

```
Acquiring state lock. This may take a few moments...
azurerm_lb_backend_address_pool.test: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"...
azurerm_lb_backend_address_pool.test: Import complete!
  Imported azurerm_lb_backend_address_pool (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes)
azurerm_lb_backend_address_pool.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-000000000000-...ernetes/backendAddressPools/kubernetes)

Error: azurerm_lb_backend_address_pool.test (import id: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes): 1 error(s) occurred:

* import azurerm_lb_backend_address_pool.test result: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes: azurerm_lb_backend_address_pool.test: Error retrieving Load Balancer by ID: Error making Read request on Azure Load Balancer kubernetes: network.LoadBalancersClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '00000000-0000-0000-0000-000000000000' with object id '00000000-0000-0000-0000-000000000000' does not have authorization to perform action 'Microsoft.Network/loadBalancers/read' over scope '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/loadBalancers/kubernetes'."
```

### Steps to Reproduce

I have replaced the guids and some of the resource names:

0. Authenticated with azure as user with full access to subscription.
1. `terraform init`
2. `terraform import azurerm_lb_backend_address_pool.test /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes`

and I also tried with backendPools, as per Azure Portal url:

2. `terraform import azurerm_lb_backend_address_pool.test /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/loadBalancers/kubernetes/backendPools/kubernetes`

### Useful info

The pool I am importing is one that was itself auto-generated by Terraform-Kubernetes. This was using a configuration that didn't explicitly set up the loadbalancer. The loadbalancer it created had a pool created with a backend pool with the Kubernetes' nodes' VMs attached, and with health monitoring probes for all of the services set up.

The reason I am doing this is because I want the load balancer that TF sets up to be on the Standard SKU not Basic, but there is a significant amount of manual work to achieve this simple goal, it seems.

### References

https://www.terraform.io/docs/providers/azurerm/r/loadbalancer_backend_address_pool.html

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested with below steps and latest azurerm, seems I cannot repro this issue. Could you have a try below tfconfig to check if the issue still exists? If still exists, could you share your tfconfig that triggers this problem? Thanks.

1. tf apply
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-lb-test10"
  location = "eastus2"
}

resource "azurerm_public_ip" "test" {
  name                = "test-ip-test10"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
}

resource "azurerm_lb" "test" {
  name                = "arm-test-loadbalancer-test10"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  frontend_ip_configuration {
    name                 = "one-test10"
    public_ip_address_id = azurerm_public_ip.test.id
  }
}

resource "azurerm_lb_backend_address_pool" "test" {
  resource_group_name = azurerm_resource_group.test.name
  loadbalancer_id     = azurerm_lb.test.id
  name                = "lbaptest10"
}
```

2. Delete terraform.tfstate file

3. tf import:
```
terraform import azurerm_lb_backend_address_pool.test "/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-lb-test10/providers/Microsoft.Network/loadBalancers/arm-test-loadbalancer-test10/backendAddressPools/lbaptest10"
```

Result:
![image](https://user-images.githubusercontent.com/19754191/88141295-e3725a80-cc25-11ea-8ef1-773999fd3f29.png)

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if the solution proposed above doesn't work and we'll take another look.

Thanks!
