### ISSUE TITLE
azurerm_api_management.security boolean settings are the wrong way round

### ISSUE THREAD

**Issue by SeanEGray** [terraform-providers/terraform-provider-azurerm#3125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.11.13
AzureRM: 1.23

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "apim" {
  name                = "apim-${var.environment}"
  location            = "${azurerm_resource_group.apim.location}"
  resource_group_name = "${azurerm_resource_group.apim.name}"
  publisher_name      = "Sean"
  publisher_email     = "${var.apim_email}"
  sku {
    name     = "${var.apim_sku}"
    capacity = "${var.apim_capacity}"
  }
  security {
    # These parameters are the wrong way round - true means enable
    disable_backend_ssl30 = false
    disable_backend_tls10 = false
    disable_backend_tls11 = false
    disable_frontend_ssl30 = false
    disable_frontend_tls10 = false
    disable_frontend_tls11 = false
    disable_triple_des_chipers = false
  }
}
```

### Expected Behavior

Setting a disable_<protocol> setting to true should disable the protocol.
Setting a disable_<protocol> setting to false should enable the protocol.

### Actual Behavior

Setting a disable_<protocol> setting to true enables the protocol.
Setting a disable_<protocol> setting to false disables the protocol.

### Steps to Reproduce

1. `terraform apply`

**Comment by ReenuSaluja** [comment]
I will work on this.

**Comment by NickMetz** [comment]
Hi @ReenuSaluja,

not sure if you already had some time to look into this issue. If so, can you please advice on how the solution will look afterwards ? It seems that just switching over to the expected behavior could cause impact.
