### ISSUE TITLE
Allow Keyvault Network ACL to be set independently

### ISSUE THREAD

**Issue by simonlegeek** [terraform-providers/terraform-provider-azurerm#3130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice if we could set the Network ACLs (especially for the IP rules) config block from Azure Keyvault independantly from the Keyvault resource itself (like with Azure SQL Server). This would prevent some dependancy cycle issues between resources. (Let's say a WebApp that needs the Keyvault URI in his app settings and the keyvault that needs the oubound IP from the Webapp in his network ACLs.) 

### New or Affected Resource(s)

* azurerm_key_vault

### Potential Terraform Configuration
Examples below of the dependancy cycle I often encounter.

```hcl
resource "azurerm_app_service" "hub_webapp" {
  name                = "hub-webapp-${var.deployment_suffix}"
  location            = "${azurerm_resource_group.main_rg.location}"
  resource_group_name = "${azurerm_resource_group.main_rg.name}"
  app_service_plan_id = "${azurerm_app_service_plan.hub_webapp_plan.id}"

  site_config {
    always_on                = true
    dotnet_framework_version = "v4.0"
  }
  app_settings {
        
    "azure:KeyVaultURL"                         = "${azurerm_key_vault.regional-keyvault.vault_uri}"
  }

resource "azurerm_key_vault" "regional-keyvault" {
    name                            = "hub-keyvault-${var.deployment_suffix}"
    location                        = "${azurerm_resource_group.main_rg.location}"
    resource_group_name             = "${azurerm_resource_group.main_rg.name}"
    enabled_for_disk_encryption     = false
    enabled_for_template_deployment = true
    tenant_id                       = "${var.tenantid}"

    sku {
        name = "standard"
    }

    network_acls {
        default_action             = "Deny"
        bypass                     = "AzureServices"
        ip_rules                   = ["${azurerm_app_service.hub_webapp.possible_outbound_ip addresses}"]
    }
}

```

**Comment by Shr3ps** [comment]
We need this too! For now to break this dep cycle, we need to use a terraform null_resource which execute `az cli` to update those Network ACLs.

**Comment by andrewboxer** [comment]
my use case is slightly different:
My terraform is applied in layers, multiple environments are then constructed from different subsets of the layers.
I create my key vault in a base layer, subsequent layers then create a subnet for their resources.
In order to permit access to the key vault I now have to create all my subnets upfront in order to permit access to the key vault from each, this imposes a dependency between the layers and makes it difficult to build different configurations from a subset of the layers.
Ideally I would be able to create each subnet as required then add it to the network acls for the key vault and preserve a modular approach.

**Comment by andrewboxer** [comment]
@Shr3ps  that is one solution I had not considered, trying it now, thank you.

**Comment by andrewboxer** [comment]
solution in case in helps anyone else in the same situation:
```resource "azurerm_subnet" "manage_subnet" {
  count                = length(var.manage_subnets)
  name                 = "${var.environment}-manage-subnet-${count.index}"
  resource_group_name  = data.terraform_remote_state.project.outputs.project_resource_group_name
  virtual_network_name = data.terraform_remote_state.project.outputs.project_vn_name
  address_prefix       = element(var.manage_subnets, count.index)

  service_endpoints = ["Microsoft.KeyVault"]

  provisioner "local-exec" {
    command = "az keyvault network-rule add --name ${data.terraform_remote_state.project.outputs.keyvault_name} --subnet ${azurerm_subnet.manage_subnet[count.index].id}"
  }
}```

**Comment by jnsgruk** [comment]
Any update on this? Presumably a new resource definition similar to that used to apply "azurerm_key_vault_access_policy" rules would work?

A resource like "azurerm_key_vault_network_allowed_subnet" or similar?

**Comment by dgcaron** [comment]
i was running into an issue when activate the firewall (default action deny) on creation of the keyvault we would get intermittent errors on creating access policies.. 

expanding on @andrewboxer our solution looks like this:
Set-Firewall.ps1
```
param (
    [Parameter(Mandatory = $true)]
    [string]$name = "",
    [Parameter(Mandatory = $true)]
    [string]$resource_group = "",
    [Parameter(Mandatory = $false)]
    [string[]]$ip_rules = @(),
    [Parameter(Mandatory = $false)]
    [string[]]$subnets = @()
)

$existing_rules = az keyvault network-rule list --name $name --resource-group $resource_group --query '{subnets:virtualNetworkRules[].id, ipRules:ipRules[].value}' | ConvertFrom-Json

foreach($ip_rule in $ip_rules) {
    if($False -eq $existing_rules.ipRules.Contains($ip_rule)){
        az keyvault network-rule add --name $name --resource-group $resource_group --ip-address $ip_rule --only-show-errors | Out-Null
    }
}

foreach($subnet in $subnets) {
    if($False -eq $existing_rules.subnets.Contains($subnet)){
        az keyvault network-rule add --name $name --resource-group $resource_group --subnet $subnet --only-show-errors | Out-Null
    }
}

az keyvault update --name $name --resource-group $resource_group --default-action Deny | Out-Null
```
and then in terraform
```
resource "null_resource" "network" {
  for_each = local.all_keyvaults
  }

  triggers = {
    build_number = timestamp()
  }

  provisioner "local-exec" {
    command     = <<EOF
      .\modules\keyvault\scripts\Set-Firewall.ps1 -name ${azurerm_key_vault.instances[each.key].name} -resource_group ${azurerm_key_vault.instances[each.key].resource_group_name} -ip_rules ${join(",",values(var.firewall_rules).*.cidr)} -subnets ${var.subnets[each.key]}
    EOF
    interpreter = ["PowerShell"]
  }

  depends_on = [ azurerm_key_vault_access_policy.dvlm_administrators, azurerm_key_vault_access_policy.prod_administrators, azurerm_key_vault_access_policy.datafactories, azurerm_key_vault_access_policy.serviceprincipal_id ]
}
```

the only problem now is that it leaves omitted firewall rules, so it needs a small tweak to do this

**Comment by m2hd1** [comment]
there is actually a PR ready to be merged. 

if you guys can put a comment in there so it gets approved: 

https://github.com/terraform-providers/terraform-provider-azurerm/pull/8560

**Comment by tombuildsstuff** [comment]
👋 

As detailed in [this comment](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8560#issuecomment-773267957) unfortunately this isn't something we plan to support at this time - as such whilst I'd like to thank you for the feedback here, I'm going to close this issue for the moment.

Thanks!
