### ISSUE TITLE
Remote-exec provisioner fails to connect with "when=destroy"

### ISSUE THREAD

**Issue by pixelicous** [terraform-providers/terraform-provider-azurerm#3150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi,

I am creating a windows VM in Azure, i create a keyvault with a certificate and push it to the machine in order to connect with winrm.

On terraform apply, the remote-exec runs successfully, both copying files and running commands
When destroying however, winrm cannot connect to the machine.
It might be due to the fact that the SPN i am using had permission on the keyvault, but during destroy the policy is removed. I tried to add back the policy to the SPN during the retry process of winrm but that didn't help.

I do not think the policy is the issue here because i am not sure if the provisioner uses it or not..

### Terraform (and AzureRM Provider) Version

Terraform 0.11.11
AzureRM Provider 1.23.0

### Affected Resource(s)

```
* azurerm_key_vault_access_policy
* azurerm_key_vault_certificate
* azurerm_virtual_machine (provisioner "remote-exec")
```

### Terraform Configuration Files

```
resource "azurerm_key_vault_certificate" "myVM" {
  name = "${local.vm_computer_name}"
  key_vault_id = "${azurerm_key_vault.myVM.id}"

  certificate_policy {
issuer_parameters {
  name = "Self"
}

key_properties {
  exportable = true
  key_size   = 2048
  key_type   = "RSA"
  reuse_key  = true
}

lifetime_action {
  action {
action_type = "AutoRenew"
  }

  trigger {
days_before_expiry = 30
  }
}

secret_properties {
  content_type = "application/x-pkcs12"
}

x509_certificate_properties {
  # Server Authentication = 1.3.6.1.5.5.7.3.1
  # Client Authentication = 1.3.6.1.5.5.7.3.2
  extended_key_usage = ["1.3.6.1.5.5.7.3.1"]

  key_usage = [
"cRLSign",
"dataEncipherment",
"digitalSignature",
"keyAgreement",
"keyCertSign",
"keyEncipherment",
  ]

  subject_alternative_names {
dns_names = ["${local.vm_computer_name}"]
  }

  subject= "CN=${local.vm_computer_name}"
  validity_in_months = 12
}
  }
}

#Keyvault
resource "azurerm_key_vault" "myVM" {
  name= "${module.naming.service_name_prefix}-kv"
  location= "${terraform.workspace}"
  resource_group_name = "${azurerm_resource_group.myVM.name}"

  tenant_id = "${data.azurerm_client_config.current.tenant_id}"

  sku {
name = "standard"
  }

  enabled_for_deployment  = true
  enabled_for_template_deployment = true

  tags = "${var.tags}"
}

#Policy

resource "azurerm_key_vault_access_policy" "my_spn" {
  key_vault_id = "${azurerm_key_vault.myVM.id}" #Subscriptions's Terraform SPN

  tenant_id = "${data.azurerm_client_config.current.tenant_id}"
  object_id = "${data.azurerm_client_config.current.service_principal_object_id}"

  certificate_permissions = [
"create","delete","deleteissuers","get","getissuers","import","list","listissuers","managecontacts","manageissuers","setissuers","update",
  ]

  key_permissions = [
"backup","create","decrypt","delete","encrypt","get","import","list","purge","recover","restore","sign","unwrapKey","update","verify","wrapKey",
  ]

  secret_permissions = [
"backup","delete","get","list","purge","recover","restore","set",
  ]
}

resource "azurerm_virtual_machine" "myVM" {
  name                  = "${module.names.prefix}"
  location              = "${terraform.workspace}"
  resource_group_name   = "${azurerm_resource_group.myVM.name}"
  network_interface_ids = ["${azurerm_network_interface.myVM.id}"]
  vm_size               = "Standard_DS2_V2"

  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "Latest"
  }

  storage_os_disk {
    name              = "${module.names.prefix}-OSDisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Premium_LRS"
  }

  os_profile {
    computer_name  = "${local.vm_computer_name}"
    admin_username = "${var.admin_username}"
    admin_password = "${var.admin_password}"
  }
  os_profile_windows_config {
    provision_vm_agent = true

    winrm {
      protocol        = "https"
      certificate_url = "${azurerm_key_vault_certificate.myVM.secret_id}"
    }
  }
  os_profile_secrets {
    source_vault_id = "${azurerm_key_vault.myVM.id}"

    vault_certificates {
      certificate_url   = "${azurerm_key_vault_certificate.myVM.secret_id}"
      certificate_store = "My"
    }
  }

    provisioner "remote-exec" {
    when = "destroy"
    connection {
      timeout  = "3m"
      type     = "winrm"
      https    = true
      port     = 5986
      use_ntlm = true
      insecure = true

      #cacert = "${azurerm_key_vault_certificate.myVM.certificate_data}"
      user     = "${var.admin_username}"
      password = "${var.admin_password}"
    }

    inline = [
      "cd c:\\directory",
      "powershell -ExecutionPolicy Unrestricted -File .\\script.ps1",
    ]
  }
    
  tags = "${var.tags)}"
}

```

### Debug Output

data.terraform_remote_state.network: Refreshing state...
azurerm_resource_group.myVM: Refreshing state... (ID: /subscriptions/xxx-xxx-xxx-.../resourceGroups/my-resource-rg)
data.azurerm_client_config.current: Refreshing state...
azurerm_network_interface.myVM: Refreshing state... (ID: /subscriptions/xxx-xxx-xxx-...orkInterfaces/my-resource-nic1)
azurerm_key_vault.myVM: Refreshing state... (ID: /subscriptions/xxx-xxx-xxx-...KeyVault/vaults/my-resource-kv)
azurerm_key_vault_certificate.myVM: Refreshing state... (ID: https://my-resource-kv.vault.az...agent/xxxxx-xx-xxx-xx-xx)
azurerm_key_vault_access_policy.spn_terraform: Refreshing state... (ID: /subscriptions/xxx-xxx-xxx-...d/xxxxx-xx-xxx-xx-xx)
azurerm_virtual_machine.myVM: Refreshing state... (ID: /subscriptions/xxx-xxx-xxx-...te/virtualMachines/my-resource)
azurerm_virtual_machine.myVM: Destroying... (ID: /subscriptions/xxx-xxx-xxx-...te/virtualMachines/my-resource)
azurerm_key_vault_access_policy.my_spn: Destroying... (ID: /subscriptions/xxx-xxx-xxx-...d/xxxxx-xx-xxx-xx-xx)
azurerm_virtual_machine.myVM: Provisioning with 'remote-exec'...
azurerm_virtual_machine.myVM (remote-exec): Connecting to remote host via WinRM...
azurerm_virtual_machine.myVM (remote-exec):   Host:
azurerm_virtual_machine.myVM (remote-exec):   Port: 5986
azurerm_virtual_machine.myVM (remote-exec):   User: my_user
azurerm_virtual_machine.myVM (remote-exec):   Password: true
azurerm_virtual_machine.myVM (remote-exec):   HTTPS: true
azurerm_virtual_machine.myVM (remote-exec):   Insecure: true
azurerm_virtual_machine.myVM (remote-exec):   NTLM: true
azurerm_virtual_machine.myVM (remote-exec):   CACert: false

### Expected Behavior

Steps that should be taken while destroying:
1. VM Should be destroyed
2. Certificate should be deleted
3. Policy should be destroyed
4. Keyvault should be destroyed
OR instead of point 2-4 Keyvault completely destroyed (taking down the policy and certificate with it)

### Actual Behavior

Policy removed and failed to connecto with remote-exec

### Steps to Reproduce

terraform init
terraform apply

**Comment by Lucretius** [comment]
I notice in the debug output the `host` property is empty.  If you are using a dynamic public IP, the IP address will not be known by the virtual machine due to how Azure provisions their dynamic public IPs.  You might try creating a static one and then using the `ip_address` attribute of that public IP as the provisioner host.

**Comment by pixelicous** [comment]
@lucretius no public ip here.. Only private and its static.. Even if dynamic.. Terraform already created the reaource it should be able to connect to it during destroy just like connecting in creation.. I guess

**Comment by tombuildsstuff** [comment]
hi @pixelicous 

Thanks for opening this issue :)

As @Lucretius has mentioned - in the example above you'll need to set the `host` property in the config block for this to be able to connect (which is why this is failing here) - would you be able to take a look and see if that works for you? Having said that, I believe that Terraform Core should return an error if the `host` property is empty - as such I've raised this with the Core team internally to clarify why this doesn't return an error if it's unset.

Since this is a question regarding Terraform Configuration rather than a bug in Terraform, I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by pixelicous** [comment]
@tombuildsstuff Hey! Thanks for the reply, that sound totally logical but how come that remote-exec and local-exec both worked when provisioning without providing this value??
Looking at the example here - 
https://www.terraform.io/docs/provisioners/connection.html

I do not see it's mandatory, it says it's usually provided by the provider. Maybe documentation should be updated as well..

**Comment by tombuildsstuff** [comment]
@pixelicous it's not mandatory since it's not required for all provisioners (e.g. `local-exec`) - but for provisioners which require that information (e.g. SSH/WinRM) it probably should be.

> Thanks for the reply, that sound totally logical but how come that remote-exec and local-exec both worked when provisioning without providing this value??

The connection information gets set during the `Create/Update` - but this isn't set at Destroy time ([AWS doesn't do this either](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_instance.go#L1906-L1919)) - so this would need input from the Core team on whether we should set these values or not.

Thanks!

**Comment by pixelicous** [comment]
@tombuildsstuff Thanks so much for the elaborated reply! Really helped! 🥇
