### ISSUE TITLE
Storage Accounts not destroying (1hr+)

### ISSUE THREAD

**Issue by runecalico** [terraform-providers/terraform-provider-azurerm#3156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

.\terraform.exe -v
Terraform v0.11.13
+ provider.azurerm v1.23.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl

resource "azurerm_storage_account" "repo" {
  depends_on = ["module.databricks"]
  name       = "fzeu2dtabrklinpdsto00"

  resource_group_name       = "${module.databricks.databricks_rg}"
  location                  = "${var.databricks_region}"
  account_tier              = "Standard"
  account_kind              = "StorageV2"
  account_replication_type  = "LRS"
  access_tier               = "Hot"
  enable_blob_encryption    = "True"
  enable_file_encryption    = "True"
  enable_https_traffic_only = "True"

  network_rules = {
    ip_rules                   = ["${module.azure_lookups.ip_rules}"]
    virtual_network_subnet_ids = ["${local.virtual_network_subnet_ids}"]
    bypass                     = ["AzureServices"]
  }

  tags {
    Product         = "${var.product_key}"
    ApplicationName = "${var.application_name}"

    #CostCenter      = "${var.costcenter}"


    #DeployScenario  = "${var.deploy_scenario}"

    Environment = "${var.environment}"
    CreatedBy   = "${var.created_by}"
    Version     = "${var.version}"
  }
}

resource "azurerm_storage_container" "repo_containers" {
  count = "${length(local.repo_containers)}"

  name                  = "${local.repo_containers[count.index]}"
  resource_group_name   = "${module.databricks.databricks_rg}"
  storage_account_name  = "${azurerm_storage_account.repo.name}"
  container_access_type = "private"
}

#Blob storage account for data scientist workspace
resource "azurerm_storage_account" "sandbox" {
  depends_on                = ["azurerm_storage_account.repo"]
  name                      = "fzeu2dtabrksbnpdsto01"
  resource_group_name       = "${module.databricks.databricks_rg}"
  location                  = "${var.databricks_region}"
  account_tier              = "Standard"
  account_kind              = "StorageV2"
  account_replication_type  = "LRS"
  access_tier               = "Hot"
  enable_blob_encryption    = "True"
  enable_file_encryption    = "True"
  enable_https_traffic_only = "True"

  network_rules = {
    ip_rules                   = ["${module.azure_lookups.ip_rules}"]
    virtual_network_subnet_ids = ["${local.virtual_network_subnet_ids}"]
    bypass                     = ["AzureServices"]
  }

  tags {
    Product         = "${var.product_key}"
    ApplicationName = "${var.application_name}"

    #CostCenter      = "${var.costcenter}"
    #DeployScenario  = "${var.deploy_scenario}"
    Environment = "${var.environment}"

    CreatedBy = "${var.created_by}"
    Version   = "${var.version}"
  }
}

resource "azurerm_storage_container" "sandbox_containers" {
  count = "${length(local.sandbox_containers)}"

  name                  = "${local.sandbox_containers[count.index]}"
  resource_group_name   = "${module.databricks.databricks_rg}"
  storage_account_name  = "${azurerm_storage_account.sandbox.name}"
  container_access_type = "private"
}


### Debug Output

How do I enable the Debug Output?

### Panic Output

It did not produce a panic

### Expected Behavior

I expect for terraform to delete the "repo" storage account and then the "sandbox" storage account. 

### Actual Behavior

The Containers delete fine, and then it just seems to "try" deleting the repo Storage account... which I cancelled after 1+Hr..
with messages like this... For 1Hr+

azurerm_storage_account.sandbox: Still destroying... (ID: /subscriptions/121257ae-f3ae-4bc8-b805-.../storageAccounts/fzeu2dtabrksbnpdsto01, 36m21s elapsed)

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

Not that I can think of.

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

* #0000

**Comment by jamie3** [comment]
Yes just noticed that now. It's possible that is the case.

**Comment by runecalico** [comment]
I am running the terraform destroy from "inside" our network, and while I do have the Storage Account Firewall enabled, terraform can create containers etc as it is originating from an IP in that list.
This may differ from #3217 , however the Storage account DOES have the vnet service endpoints configured, and the vnet/subnet it's configured to is NOT part of this terraform deployment.

Could the service endpoint configuration be causing a problem? I haven't tested it, but I find it hard to believe that Terraform can't in general destroy a Storage account.

It can destroy the blob containers:
28-May-2019 07:53:41	azurerm_storage_container.repo_containers: Destroying... (ID: https://fzeu2dtabrklinpdsto00.blob.core.windows.net/repo)
28-May-2019 07:53:41	azurerm_storage_container.sandbox_containers[1]: Destroying... (ID: https://fzeu2dtabrksbnpdsto01.blob.core.windows.net/product-images)
28-May-2019 07:53:41	azurerm_storage_container.sandbox_containers[2]: Destroying... (ID: https://fzeu2dtabrksbnpdsto01.blob.core.windows.net/sandbox)
28-May-2019 07:53:41	azurerm_storage_container.sandbox_containers[0]: Destroying... (ID: https://fzeu2dtabrksbnpdsto01.blob.core.windows.net/adobe)
28-May-2019 07:53:42	azurerm_storage_container.sandbox_containers[0]: Destruction complete after 0s
28-May-2019 07:53:42	azurerm_storage_container.sandbox_containers[1]: Destruction complete after 0s
28-May-2019 07:53:42	azurerm_storage_container.repo_containers: Destruction complete after 0s
28-May-2019 07:53:42	azurerm_storage_container.sandbox_containers[2]: Destruction complete after 0s

**Comment by runecalico** [comment]
Yep, it's something with the Service Endpoints.

I removed the Service endpoints from my code first, applied it (which removed the Service Endpoint bindings from the Storage accounts) and then ran a destroy.

It was able to delete the Storage accounts :)

Well, at least I have a work around... is there some missing dependency code or something such that it doesn't remove the Service Endpoint bindings first before trying to destroy the SA?

**Comment by fl-max** [comment]
This only happens when there's >1 Subnet configured in the Firewall. If there's only 1 Subnet, it destroys fine.

**Comment by dannysievers** [comment]
I have run into this same issue. I have two subnets configured as Service Endpoints and Terraform cannot destroy the Storage Account. Any updates on a solution to this issue?

**Comment by HeikoNeblung** [comment]
I'm facing the same issue. It happens as soon as there are more than one entries in virtual_network_subnet_ids.

**Comment by davidtom** [comment]
I'm still having this exact issue using version 1.39 of the provider. Is this still broken for anyone else?
