### ISSUE TITLE
Multiple VMs with different guest OS in one terraform apply

### ISSUE THREAD

**Issue by AsgharGhori** [terraform-providers/terraform-provider-azurerm#3172]
Hello!

I am wondering if TF has the capability available that allows us to spin up multiple VMs in Azure with a different guest OS - Ubuntu, CentOS, and Windows - in each, and all of that done in a single terraform apply. This is expected to be a common activity at my workplace in the near future and I want to get my TF scripts ready and tested before the first client request comes in.

**Comment by Lucretius** [comment]
Hi @AsgharGhori - each virtual machine can be configured separately and you can configure however many you need.  Take a look at the docs here https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html.  Take note of the following section:

```
storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
```

You can specify whatever OS you would like.

So you could have

```
resource "azurerm_virtual_machine" "ubuntu" {
...
storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
...
}

resource "azurerm_virtual_machine" "centos" {
...
storage_image_reference {
    publisher = "Canonical"
    offer     = "Centos"
    sku       = "<sku>"
    version   = "latest"
  }
...
}

resource "azurerm_virtual_machine" "windows" {
...
storage_image_reference {
    publisher = "Canonical"
    offer     = "<windows>"
    sku       = "<sku>"
    version   = "latest"
  }
...
}
```

One `terraform apply` will create all three machines.

**Comment by AsgharGhori** [comment]
Hi @Lucretius and @tombuildsstuff. Thanks for taking a look.

I have multiple VM resources defined that way in my TF file. I have separate TF files for extensions, roles, data disks, resource group, nic, and availability set. I have dependencies in place as well. It appears that I'll have to create multiple resources for extensions, roles assignments, etc. for each type of OS (VM resource).

resource "azurerm_virtual_machine_extension" "NetworkWatcher" {
  count                      = "${var.VMCount}"
  name                       = "NetworkWatcherAgentLinux"
  location                   = "${var.VMLocation}"
  resource_group_name        = "${var.RG4VM}"
  virtual_machine_name       = "${var.VMName}${format("%1d", count.index+1)}"
  publisher                  = "Microsoft.Azure.NetworkWatcher"
  type                       = "NetworkWatcherAgentLinux"
  type_handler_version       = "${var.NetWatcherVer}"
  auto_upgrade_minor_version = "true"

  depends_on = ["azurerm_virtual_machine.VM", "null_resource.4VMs"]

Let me play around with the config a bit and see how far I can go.

Thanks for your help.

Regards,
Asghar
