### ISSUE TITLE
azurerm_mssql_elasticpool, unknown key: zone_redundant with provider v1.24.0

### ISSUE THREAD

**Issue by jcmaasb** [terraform-providers/terraform-provider-azurerm#3176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```hcl
Terraform v0.11.13
provider.azurerm v1.24.0
```

### Affected Resource(s)

* `azurerm_mssql_elasticpool`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "my-resource-group"
  location = "westeurope"
}

resource "azurerm_sql_server" "test" {
  name                         = "my-sql-server"
  resource_group_name          = "${azurerm_resource_group.test.name}"
  location                     = "${azurerm_resource_group.test.location}"
  version                      = "12.0"
  administrator_login          = "4dm1n157r470r"
  administrator_login_password = "4-v3ry-53cr37-p455w0rd"
}

resource "azurerm_mssql_elasticpool" "test" {
  name                = "test-epool"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  server_name         = "${azurerm_sql_server.test.name}"
  max_size_gb         = 650

  sku {
    name     = "BC_Gen5"
    tier     = "BusinessCritical"
    family   = "Gen5"
    capacity = 4
  }

  per_database_settings {
    min_capacity   = 0.25
    max_capacity   = 4
    zone_redundant = false  <--- new value in provider v1.24.0, unknown key?
  }
}
```

### Expected Behavior

The resource must be created with the default value (false, or without redundant zone)

### Actual Behavior

Error: azurerm_mssql_elasticpool.test: per_database_settings.0: invalid or unknown key: zone_redundant

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It's just a test of a new mssql_elasticpool option in v1.24.0, but I was hoping it would not generate errors

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @jcmaasb 

Thanks for opening this issue :)

Taking a quick look into this, this is supported at the top level (the key is `zone_redundant`) - however the documentation isn't overly clear here, so I've labelled this appropriately for us to fix. Would you be able to take a look and see if setting this property at the top level works for you?

Thanks!

**Comment by jcmaasb** [comment]
Hi @tombuildsstuff,

you are right, it is a confusion about how it is indicated in the documentation, if it moves to the highest level it works fine!!

Thanks!
