### ISSUE TITLE
Error on changing app service plan

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#3185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.11.13
+ provider.azurerm v1.24.0
```
### Affected Resource(s)

* `azurerm_app_service`

### Expected Behavior

Resource re-created on changing app service plan as it used to happen before v1.24.0

### Actual Behavior

`azurerm_app_service.appservice: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>`

### Steps to Reproduce

1. Change `app_service_plan_id`
2. `terraform apply`

### Important Factoids

Not sure if it matters but I'm changing from a Windows plan to a Linux one

**Comment by Lucretius** [comment]
Hi @Leon99  - it looks like in the last release https://github.com/terraform-providers/terraform-provider-azurerm/pull/3048 changed this part of the code to stop forcing a new resource to support migrating between plans.  Maybe @tombuildsstuff can shed some light on this particular change?

**Comment by Leon99** [comment]
@tombuildsstuff I wonder if #3048 could be reverted for now, if fixing it is too hard? We're gradually migrating our apps to Linux plans and this bug stops us from upgrading the provider, however, there are fixes in the newer versions that we need.

**Comment by tombuildsstuff** [comment]
@Leon99 I don't believe reverting #3048 is the right approach here, unfortunately. Out of interest does using `terraform taint` work as a workaround in the interim?

Thanks!

**Comment by Leon99** [comment]
`taint` helps, thanks.

**Comment by Stolpe** [comment]
According to https://social.msdn.microsoft.com/Forums/en-US/6d59602e-b67e-4e33-a2b8-fd15b2e111fd/unable-to-quotchange-app-service-planquot-as-no-app-service-plans-are-listed, app service plans can only be changed within the same _webspace_. Maybe this is something that could be used to determine if an app_service resource can be updated in-place, or if a destroy-and-recreate is needed.

**Comment by tombuildsstuff** [comment]
Closing this in favour of #6348 which'll highlight the error here
