### ISSUE TITLE
Cannot create storage account that uses network rules

### ISSUE THREAD

**Issue by SirWayne** [terraform-providers/terraform-provider-azurerm#3187]
Hello,

i would like to create storage account that uses network rules, but i get follow error

`data.azurerm_storage_account.StorageAccount: : invalid or unknown key: network_rules`

This my config:
```
data "azurerm_storage_account" "StorageAccount" {
  name                = "${var.infrastructure_storage_account_name}"
  resource_group_name = "${var.resource_group_name}"

  network_rules {
    ip_rules                   = ["foo/bar"]
    virtual_network_subnet_ids = ["${azurerm_subnet.abc.id}"]
    bypass = "None"
  }
}
```

Iam using terraform azurerm 1.24.0. Is this a bug or doing iam something wrong?

**Comment by adamday2** [comment]
Are you trying to create it or reference an existing account?
You are using **data** rather than **resource**.

**Comment by SirWayne** [comment]
Existing account, but yes maybe i should try resource.

**Comment by Lucretius** [comment]
If you want to configure an existing resource not currently tracked via terraform you need to import it first (terraform import command) and then you can try to modify it via terraform.  A data source is essentially just a read only version of an existing azure resource and does not accept “network_rules” as an argument.

**Comment by SirWayne** [comment]
I import the storage account, but now i get always this error

```
* azurerm_storage_account.StorageAccount: Error creating Azure Storage Account "xys": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="AccountPropertyCannotBeUpdated" Message="The property 'isHnsEnabled' was specified in the input, but it cannot be updated."
```

I did try to modify it like

```
resource "azurerm_storage_account" "StorageAccount" {
  name                = "${var.infrastructure_storage_account_name}"
  resource_group_name = "${var.resource_group_name}"
  account_replication_type ="LRS"
  account_tier = "Standard"
  location = "${var.location}"

  network_rules {
    ip_rules                   = ["foo/bar"]
    virtual_network_subnet_ids = ["${azurerm_subnet.mybackend.id}"]
    bypass = ["None"]
  }
}
```

**Comment by Lucretius** [comment]
Does your storage account set HnsEnabled to true?  It defaults to false, so it may be the case that if you import one that has it set to true it does not get computed properly.

**Comment by SirWayne** [comment]
I tried to set is_hns_enabled to true and false, I get always the same error.

**Comment by mzhrbbs** [comment]
I was facing the same issue, my storage account was of type Storage and the `hns` was not set for it. It shouldn't be set anyway for type `Storage` because it only applies to type `StorageV2` as per azure docs. 
Anyways, I had to manually upgrade my storage account to V2 in the azure portal and then it worked

**Comment by SirWayne** [comment]
@mzhrbbs I upgraded the account to 'Account kind StorageV2 (general purpose v2) '

The Hierarchical namespace is is still grayed out in the UI.

The error is the same.

```
* azurerm_storage_account.StorageAccount: Error creating Azure Storage Account "foo": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="AccountPropertyCannotBeUpdated" Message="The property 'isHnsEnabled' was specified in the input, but it cannot be updated."
```

The config is:
```
resource "azurerm_storage_account" "StorageAccount" {
  name                = "${var.infrastructure_storage_account_name}"
  resource_group_name = "${var.resource_group_name}"
  account_kind = "StorageV2"
  account_replication_type ="LRS"
  account_tier = "Standard"
  location = "${var.location}"
}
```

The console ouput (why creating?)
```
azurerm_storage_account.StorageAccount: Creating...
  access_tier:                                           "" => "<computed>"
  account_encryption_source:                             "" => "Microsoft.Storage"
  account_kind:                                          "" => "StorageV2"
  account_replication_type:                              "" => "LRS"
  account_tier:                                          "" => "Standard"
  enable_blob_encryption:                                "" => "true"
  enable_file_encryption:                                "" => "true"
  identity.#:                                            "" => "<computed>"
  is_hns_enabled:                                        "" => "false"
```

**Comment by mzhrbbs** [comment]
The hns should not be grayed out but set to disabled in the UI after you upgrade to StorageV2.
After you did the import did you check your tf-state for the storage account, because if it is not there in your state then it will try to create it I guess. Also look at the tf_plan and see what it says

**Comment by SirWayne** [comment]
Yes you are right, the `enabled` button is grayed out.

Maybe i made something wrong with the import. Does the import with the resource need a separate terraform file?
How do I see that an import worked, only in the state file itself?

**Comment by mzhrbbs** [comment]
I don' think it needs a separate file and yes if the import was success then you will see it in the state file. If everything looks good to you, this(hnsEnabled) actually might be a bug with the azurerm provider version 1.24.0 so you could go back to using 1.23.0 and see if that works. that will tell you better about your import's success

**Comment by SirWayne** [comment]
@mzhrbbs i tried out the new version 1.27.1 but got the same error
```
* azurerm_storage_account.StorageAccount: Error creating Azure Storage Account "sorageaccount": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="AccountPropertyCannotBeUpdated" Message="The property 'isHnsEnabled' was specified in the input, but it cannot be updated."
```
