### ISSUE TITLE
Azure Key Vault Secret / Adding new secret to Azure key vault removes access policy

### ISSUE THREAD

**Issue by thejharvey** [terraform-providers/terraform-provider-azurerm#3189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform 0.11.13
Terraform AzureRM 1.24.0

### Affected Resource(s)

Hello!  I'm running a new release of our code to have a new secret added to an existing key vault in Azure.  In a prior release the key vault gets added and the key vault access policy gets applied using an SPN for the access with the get and set permissions applied.  As part of the initial deployment I had two secrets added to the vault.  When I go to add any new secrets to the vault, Terraform wants to strip out the key vault access policy per the terraform plan being run.  If this happens then the next time I do a deployment Terraform fails with access denied adding anything to the key vault and the only way to fix that is to manually add the SPN back to the key vault access policy manually in the Azure portal.

Here is how my code is referencing the key vault access policy and key vault modules.

module "kv_access" {
  source = "Source directory here"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  vault_name = "${module.kv.KeyVault_name}"
  service_principal_name = "SPN Name Here"
  secret_permissions = ["set","get"]
}
module "kv" {
  source = "Source directory here"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  vault_name = "#{vault_name}#"
  tags = {
    Department = "#{Department}#"
    Project = "#{Project}#"
    Shared = "#{Shared}#"
  }
}

This is what I see in the Terraform plan.  This should not be happening at all since nothing changed with key vault or the access policy.

‌module.kv.azurerm_key_vault.KV‌
access_policy.#:                              &quot;2&quot; =&gt; &quot;1&quot;‌
access_policy.1.object_id:                    "object id redacted" => ""
access_policy.1.secret_permissions.#:         "2" => "0"
access_policy.1.secret_permissions.0:         "set" => ""
access_policy.1.secret_permissions.1:         "get" => ""
access_policy.1.tenant_id:                    "***" => ""
tags.ModifiedDate:                            

### Steps to Reproduce

Create key vault, access policy, and add a secret.
Run a new release and add a new secret to the existing key vault.

**Comment by Lucretius** [comment]
Hi @thejharvey, I see you have the following modules being used:

```terraform
module "kv_access" {
  source = "Source directory here"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  vault_name = "${module.kv.KeyVault_name}"
  service_principal_name = "SPN Name Here"
  secret_permissions = ["set","get"]
}
module "kv" {
  source = "Source directory here"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  vault_name = "#{vault_name}#"
  tags = {
    Department = "#{Department}#"
    Project = "#{Project}#"
    Shared = "#{Shared}#"
  }
}
```

however, I do not see what resources these modules are creating.  Could you post the module code as well so we can see what resources are being generated?  This will help us diagnose the issue. Thanks!

**Comment by thejharvey** [comment]
Sure thing

data "azurerm_client_config" "current" {}

data "azurerm_subscription" "current" {}

locals {
  "DevOps_group_name" = {
   _names are in here and what they point to in AzureAD_
  }
}


data "azuread_group" "DevOps" {
  name = "${lookup(local.DevOps_group_name,data.azurerm_subscription.current.display_name)}"
}

data "azurerm_resource_group" "rg_name" {
  name = "${var.resource_group_name}"
}

locals {

tf_tag = {
  Source       = "TFModule-KeyVault_1.0.0.0"
  CreatedDate  = "${timestamp()}"
  ModifiedDate = "${timestamp()}"
}

}


resource "azurerm_key_vault" "KV" {
  name                        = "${var.vault_name}"
  location                    = "${data.azurerm_resource_group.rg_name.location}"
  resource_group_name         = "${data.azurerm_resource_group.rg_name.name}"
  enabled_for_disk_encryption = true
  tenant_id                   = "${data.azurerm_client_config.current.tenant_id}"
  tags   = "${merge(local.tf_tag,var.tags)}"

  sku {
    name = "standard"
  }

  access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${data.azuread_group.DevOps.id}"

    secret_permissions = [
      "get",
      "list",
      "set",
    ]
  }
  
  lifecycle {
    ignore_changes = "tags.CreatedDate"
  }
}

**Comment by Lucretius** [comment]
I see you have an access_policy specified in the `key_vault` resource.  I assume the module `kv_access` is using `key_vault_access_policy` to add more policies.  Is this the case?  If so, that would be your problem - see the note at the top of the [Key Vault resource](https://www.terraform.io/docs/providers/azurerm/r/key_vault.html) - you can either use `key_vault` itself to specify policy or the `azurerm_key_vault_access_policy` resource, but not both.  Otherwise one will always attempt to override the other.  In this case, it would appear your key vault resource is overriding your added policy.

**Comment by thejharvey** [comment]
I've moved the SPN and secret permissions up to the section in my code that references the key vault module, commented out the entirety of the section referencing the key vault module.  I'm running a test locally up to Azure and I see in the plan where it's going to apply the access policy but it never does and fails of course when trying to add the secrets.

Here's the new blurb of my code in reference to the key vault module.

module "kv" {
  source = "C:/AzureKeyVault_1.0.0.0"
  resource_group_name = "${data.azurerm_resource_group.rg.name}"
  vault_name = "vaultest"
  service_principal_name = "SPN"
  secret_permissions = ["set","get"]
  tags = {
    Department = "Tags"
    Project = "Tags"
    Shared = "false"
  }

If it helps any here's one of my code sections for adding one of the secrets.  This is failing since the access policy isn't getting applied.

module "kv_secret_storage_blob" {
  source = "C:/AzureKVSecret_1.0.0.0.zip"
  Secret_Name = "storage-blob-${module.storage.name}"
  Secret_Value = "${module.storage.primary_blob_endpoint}"
  KeyVault_id = "${module.kv.KeyVault_id}"

  tags {
        project     = "Tags"
        department  = "Tags"
        application = "Tags"
        shared      = "false"
} 

module "storage" {
  source = "C:/AzureStorage_1.0.0.0.zip"
  storage_account_name = "stgkeyvaulttest"
  resource_group_name = "${data.azurerm_resource_group.rg.name}"
  tags = {
    Department = "Tags"
    Project = "Tags"
    Shared = "false"
  }

Here's the Terraform Apply:

module.storage.azurerm_storage_account.sa: Creating...
  access_tier:                      "" => "<computed>"
  account_encryption_source:        "" => "Microsoft.Storage"
  account_kind:                     "" => "StorageV2"
  account_replication_type:         "" => "RAGRS"
  account_tier:                     "" => "Standard"
  enable_blob_encryption:           "" => "true"
  enable_file_encryption:           "" => "true"
  enable_https_traffic_only:        "" => "true"
  identity.#:                       "" => "<computed>"
  location:                         "" => "centralus"
  name:                             "" => "stgkeyvaulttest"
  primary_access_key:               "<sensitive>" => "<sensitive>"
  primary_blob_connection_string:   "<sensitive>" => "<sensitive>"
  primary_blob_endpoint:            "" => "<computed>"
  primary_connection_string:        "<sensitive>" => "<sensitive>"
  primary_file_endpoint:            "" => "<computed>"
  primary_location:                 "" => "<computed>"
  primary_queue_endpoint:           "" => "<computed>"
  primary_table_endpoint:           "" => "<computed>"
  resource_group_name:              "" => "RGName"
  secondary_access_key:             "<sensitive>" => "<sensitive>"
  secondary_blob_connection_string: "<sensitive>" => "<sensitive>"
  secondary_blob_endpoint:          "" => "<computed>"
  secondary_connection_string:      "<sensitive>" => "<sensitive>"
  secondary_location:               "" => "<computed>"
  secondary_queue_endpoint:         "" => "<computed>"
  secondary_table_endpoint:         "" => "<computed>"
  tags.%:                           "" => "6"
  tags.CreatedDate:                 "" => ""
  tags.Department:                  "" => "Tags"
  tags.ModifiedDate:                "" => ""
  tags.Project:                     "" => "Tags"
  tags.Shared:                      "" => "false"
  tags.Source:                      "" => "TFModule-AzureStorage_1.0.0.0"
module.kv.azurerm_key_vault.KV: Creating...
  access_policy.#:                      "" => "1"
  access_policy.0.object_id:            "" => "sensitive"
  access_policy.0.secret_permissions.#: "" => "2"
  access_policy.0.secret_permissions.0: "" => "set"
  access_policy.0.secret_permissions.1: "" => "get"
  access_policy.0.tenant_id:            "" => "sensitive"
  enabled_for_disk_encryption:          "" => "true"
  location:                             "" => "centralus"
  name:                                 "" => "vaultest"
  resource_group_name:                  "" => "RGName"
  sku.#:                                "" => "1"
  sku.0.name:                           "" => "standard"
  tags.%:                               "" => "6"
  tags.CreatedDate:                     "" => ""
  tags.Department:                      "" => "Tags"
  tags.ModifiedDate:                    "" => "Tags"
  tags.Project:                         "" => "Project"
  tags.Shared:                          "" => "false"
  tags.Source:                          "" => "TFModule-KeyVault_1.0.0.0"
  tenant_id:                            "" => "sensitive"
  vault_uri:                            "" => "<computed>"
module.ai.azurerm_application_insights.ai: Creation complete after 4s (ID: /sensitive/Microsoft.insights/components/SBXENV-AI)
module.kv.azurerm_key_vault.KV: Still creating... (10s elapsed)
module.storage.azurerm_storage_account.sa: Still creating... (10s elapsed)
module.storage.azurerm_storage_account.sa: Creation complete after 19s (ID: /sensitive/storageAccounts/stgkeyvaulttest)
module.kv.azurerm_key_vault.KV: Still creating... (20s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (30s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (40s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (50s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (1m0s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (1m10s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (1m20s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (1m30s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (1m40s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (1m50s elapsed)
module.kv.azurerm_key_vault.KV: Still creating... (2m0s elapsed)
module.kv.azurerm_key_vault.KV: Creation complete after 2m4s (ID: /sensitive/providers/Microsoft.KeyVault/vaults/vaultest)
module.kv_secret_storage_blob.azurerm_key_vault_secret.KV_secret: Creating...
  key_vault_id:      "" => "/sensitive/providers/Microsoft.KeyVault/vaults/vaultest"
  name:              "" => "storage-blob-stgkeyvaulttest"
  tags.%:            "" => "7"
  tags.CreatedDate:  "" => ""
  tags.ModifiedDate: "" => ""
  tags.Source:       "" => "TFModule-KVSecret_1.0.0.0"
  tags.application:  "" => "Tag"
  tags.department:   "" => "Tag"
  tags.project:      "" => "Tag"
  tags.shared:       "" => "false"
  value:             "<sensitive>" => "<sensitive>"
  vault_uri:         "" => "<computed>"
  version:           "" => "<computed>"
module.kv_secret_storage_key.azurerm_key_vault_secret.KV_secret: Creating...
  key_vault_id:      "" => "sensitive"
  name:              "" => "storage-key-stgkeyvaulttest"
  tags.%:            "" => "7"
  tags.CreatedDate:  "" => "2019-04-05T18:27:07Z"
  tags.ModifiedDate: "" => "2019-04-05T18:27:07Z"
  tags.Source:       "" => "TFModule-KVSecret_1.0.0.0"
  tags.application:  "" => "Tag"
  tags.department:   "" => "Tag"
  tags.project:      "" => "Tag"
  tags.shared:       "" => "false"
  value:             "<sensitive>" => "<sensitive>"
  vault_uri:         "" => "<computed>"
  version:           "" => "<computed>"

Error: Error applying plan:

2 error(s) occurred:

* module.kv_secret_storage_blob.azurerm_key_vault_secret.KV_secret: 1 error(s) occurred:

* azurerm_key_vault_secret.KV_secret: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied" InnerError={"code":"AccessDenied"}
* module.kv_secret_storage_key.azurerm_key_vault_secret.KV_secret: 1 error(s) occurred:

* azurerm_key_vault_secret.KV_secret: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied" InnerError={"code":"AccessDenied"}

**Comment by thejharvey** [comment]
So I tried adding the SPN to the access policy through the Azure portal which added fine there.  I then ran a terraform plan and it wants to remove the access policy again, and this is with the SPN and secret permissions in my code for the key vault module, and not using the kv access module at all.

**------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  ~ module.kv.azurerm_key_vault.KV
      access_policy.#:                      "2" => "1"
      access_policy.1.object_id:            "id" => ""
      access_policy.1.secret_permissions.#: "2" => "0"
      access_policy.1.secret_permissions.0: "Get" => ""
      access_policy.1.secret_permissions.1: "Set" => ""
      access_policy.1.tenant_id:            "id" => ""

**Comment by Lucretius** [comment]
You need to add that SPN access policy via Terraform.  If you make a change outside of Terraform to the Key Vault access policy but don't track it via Terraform, Terraform will try to match what state it knows about (which doesn't include the manual change) - so it will delete your changes that were made in the portal.

You will need to run Terraform using a service principal and give it the necessary permissions.  You can access the current client_id, tenant_id, etc. using the data_source for client_config.

**Comment by thejharvey** [comment]
This was resolved by adding a lifecycle profile to our key vault module to ignore changes to the access policy.  Thank you for the help!!
