### ISSUE TITLE
SQL Database dependecy to SQL Server is missing

### ISSUE THREAD

**Issue by StefanSchoof** [terraform-providers/terraform-provider-azurerm#319]
### Terraform Version
v0.10.3

### Affected Resource(s)
- azurerm_sql_database

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "production" {
  name     = "terraformTest"
  location = "West Europe"
}

resource "azurerm_sql_server" "sqlserver" {
  name="mysqlservergfdgdhgdg"
  resource_group_name="${azurerm_resource_group.production.name}"
  location="westeurope"
  version="12.0"
  administrator_login="xxxxxxx"
  administrator_login_password="xxxxxxxxxx"
}

resource "azurerm_sql_database" "sqldatabase" {
  name="MyDatabase"
  resource_group_name="${azurerm_resource_group.production.name}"
  location="westeurope"
  server_name="mysqlservergfdgdhgdg"
}
```

### Panic Output
`azurerm_sql_database.sqldatabase: sql.DatabasesClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentRes
ourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'mysqlserversshdg' not found."`

### Expected Behavior
The azurerm_sql_database waits unitl the azurerm_sql_server is ready.

### Actual Behavior
`terrarform apply` starts the provisioning of database and server in parallel. A `graph | dot -Tpng > graph.png` show that there is no dependency from the server to the database.

### Steps to Reproduce
1. `terraform apply`
or
1. `graph | dot -Tpng > graph.png`

**Comment by tombuildsstuff** [comment]
Hi @StefanSchoof 

Thanks for opening this issue :)

Given it's possible to use any resource in any combination between any providers - we don't define the relationships between each resource automatically. Instead Terraform builds up a graph of changes based on the relationships between resources and works through this.

It's possible to specify dependencies either explicitly (by referencing the other resource, as you've done for the resource group name) or through the `depends_upon` attribute. More information on this can about [Resource Dependencies can be found here](https://www.terraform.io/intro/getting-started/dependencies.html) - and [more information about the Graph can be found here](https://www.terraform.io/docs/internals/graph.html).

I'd recommend making use of Explicit Dependencies, by referencing between resources where possible as it's less code / more readable - however the `depends_upon` attribute will also work :)
I've updated your sample below to use Explicit Dependencies - would it be possible to take a look and see if that solves your issue?

```
resource "azurerm_resource_group" "production" {
  name     = "terraformTest"
  location = "West Europe"
}

resource "azurerm_sql_server" "sqlserver" {
  name="mysqlservergfdgdhgdg"
  resource_group_name="${azurerm_resource_group.production.name}"
  location="westeurope"
  version="12.0"
  administrator_login="xxxxxxx"
  administrator_login_password="xxxxxxxxxx"
}

resource "azurerm_sql_database" "sqldatabase" {
  name="MyDatabase"
  resource_group_name="${azurerm_resource_group.production.name}"
  location="westeurope"
  server_name="${azurerm_sql_server.sqlserver.name}"
}
```

Thanks!

**Comment by StefanSchoof** [comment]
Thanks @tombuildsstuff for explaining me this (even If it was a stupid beginners error). Now I understand how this works and my `terraform apply` works.
