### ISSUE TITLE
azurerm_log_analytics_solution trying to change workspace_resource_id on each apply (case sensitivity)

### ISSUE THREAD

**Issue by brent-robinson** [terraform-providers/terraform-provider-azurerm#3201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.24.0

### Affected Resource(s)

* `azurerm_log_analytics_solution`

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "log-analytics" {
  resource_group_name = "${data.azurerm_resource_group.default.name}"
  name                = "${local.log_analytics_name}"
  location            = "${data.azurerm_resource_group.default.location}"
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "container-insights" {
  solution_name         = "ContainerInsights"
  location              = "${data.azurerm_resource_group.default.location}"
  resource_group_name   = "${data.azurerm_resource_group.default.name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.log-analytics.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.log-analytics.name}"

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}
```

### Debug Output

For the **workspace**, it looks like Azure is returning the provider name in the resource ID in lowercase.

```
2019/04/07 17:15:46 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/********-****-****-****-************/resourcegroups/****/providers/Microsoft.OperationalInsights/workspaces/*****-****-********?api-version=2015-11-01-preview:

{
  "properties": {
    "source": "Azure",
    "customerId": "********-****-****-****-************",
    "provisioningState": "Succeeded",
    "sku": {
      "name": "pergb2018"
    },
    "retentionInDays": 30,
    "features": {
      "legacy": 0,
      "searchVersion": 1,
      "enableLogAccessUsingOnlyResourcePermissions": true
    },
    "workspaceCapping": {
      "dailyQuotaGb": -1.0,
      "quotaNextResetTime": "Mon, 08 Apr 2019 04:00:00 GMT",
      "dataIngestionStatus": "RespectQuota"
    }
  },
  "id": "/subscriptions/********-****-****-****-************/resourcegroups/****/providers/microsoft.operationalinsights/workspaces/*****-****-********",
  "name": "*****-****-********",
  "type": "Microsoft.OperationalInsights/workspaces",
  "location": "australiaeast",
  "tags": {}
}
```

And for the **solution**, the provider name is in mixed case.

```
2019/04/07 17:15:47 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/********-****-****-****-************/resourcegroups/****/providers/Microsoft.OperationsManagement/solutions/ContainerInsights%28*****-****-********%29?api-version=2015-11-01-preview:

{
  "plan": {
    "name": "ContainerInsights(*****-****-********)",
    "publisher": "Microsoft",
    "promotionCode": "",
    "product": "OMSGallery/ContainerInsights"
  },
  "properties": {
    "workspaceResourceId": "/subscriptions/********-****-****-****-************/resourcegroups/****/providers/Microsoft.OperationalInsights/workspaces/*****-****-********",
    "provisioningState": "Succeeded",
    "creationTime": "Mon, 01 Jan 0001 00:00:00 GMT",
    "lastModifiedTime": "Mon, 01 Jan 0001 00:00:00 GMT",
    "containedResources": []
  },
  "id": "/subscriptions/********-****-****-****-************/resourcegroups/****/providers/Microsoft.OperationsManagement/solutions/ContainerInsights(*****-****-********)",
  "name": "ContainerInsights(*****-****-********)",
  "type": "Microsoft.OperationsManagement/solutions",
  "location": "eau"
}
```

### Expected Behavior

Applying this configuration twice should result in no changes on the second apply.

### Actual Behavior

The id is being changed on each apply.

```text
  ~ azurerm_log_analytics_solution.container-insights
      workspace_resource_id:                        "/subscriptions/********-****-****-****-************/resourcegroups/****/providers/Microsoft.OperationalInsights/workspaces/*****-****-********" => "/subscriptions/********-****-****-****-************/resourcegroups/****/providers/microsoft.operationalinsights/workspaces/*****-****-********"
```

Note the provider name casing:

* Microsoft.OperationalInsights
* microsoft.operationalinsights

All other elements are identical (subscription, resource group, workspace).

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

* From the logs, it looks like Azure is inconsistent here - I'm not sure if this is common for other resource types. Could Terraform be more permissive of casing inconsistencies for resource ids?

### References

* There is another issue causing this resource to be recreated each time, but this looks like it [might be an Azure problem](https://social.msdn.microsoft.com/Forums/en-US/1a0296a6-d71f-448a-bb90-ee3ccdee8a51/log-analytics-solution-name-is-displaying-as-a-short-form-in-the-portal-and-api?forum=opinsights).

**Comment by bcraun** [comment]
I'm having a similar issue `azurerm_log_analytics_workspace.location`. I enbaled Terraform debugging and am seeing the issue clearly demonstrated by the debug output above. 

Look at the difference between the location for the workspace and solution returned from Azure (`eau` vs. `australiaeast`), respectively. In my case, the location for the workspace is `eastus2` yet the location for the solution being returned from Azure is  `eus2`. 

As a result of the discrepancy, _**any**_ changes made to the configuration, for example, adding a tag to an unrelated resource, causes Terraform to (correctly) identify that the `azurerm_log_analytics_solution.location` should be changed from `eus2` to `eastus2`. More concerning to me is that it's a destructive change. I haven't used the log analytics soltuion long enought to know if that's a bad thing, or not, but it seems to me that it is a potential source of problems and definitely violates the principle of least astonishment. What's even more puzzling is that even _**after**_ deployment, the Log Analytics Solution location in the Azure portal _**still**_ shows the location as `eus2`?

I've attached a couple of screenshots to corroborate the observed behavior. Any idea if this behavior from Azure is by design?

![log-analytics-solution](https://user-images.githubusercontent.com/641584/56083599-08014500-5ddc-11e9-9945-8231deab25aa.jpg)

![log-analytics-solution-portal](https://user-images.githubusercontent.com/641584/56083590-c1abe600-5ddb-11e9-8a5f-e930de7a6b66.jpg)

**Comment by AntonChernysh** [comment]
I think Azure fixed this over last weekend: It works as expected now:
```List of available regions for the resource type is 'eastus,westeurope,southeastasia,australiasoutheast,westcentralus,japaneast,uksouth,centralindia,canadacentral,westus2,australiaeast,australiacentral,francecentral,koreacentral,northeurope,centralus,eastus2,eastasia,westus,southcentralus'```
No more "Short" locations for log analytics solution.

**Comment by brent-robinson** [comment]
Can also confirm the Azure issue with the incorrect location name has been resolved. I need to retest the workspace resource id issue.
