### ISSUE TITLE
azurerm_storage_share doesn't support import

### ISSUE THREAD

**Issue by LukeCarrier** [terraform-providers/terraform-provider-azurerm#321]
### Terraform Version

0.10.4

### Affected Resource(s)

* azurerm_storage_share

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
variable "storage_shares" {
  type    = "map"
  default = {
    "someshare"      = "100",
    "someothershare" = "10"
  }
}

resource "azurerm_storage_share" "storage_shares" {
  count                = "${length(var.storage_shares)}"
  name                 = "${element(keys(var.storage_shares), count.index)}"
  resource_group_name  = "${var.resource_group_name}"
  storage_account_name = "${azurerm_storage_account.storage_account.name}"
  quota                = "${lookup(var.storage_shares, element(keys(var.storage_shares), count.index))}"
}
```

### Debug Output

```
$ terraform import module.alp-shares-uat.azurerm_storage_share.ss[7] jellyfish
module.alp-shares-uat.azurerm_storage_share.ss: Importing from ID "jellyfish"...
Error importing: 1 error(s) occurred:
* module.alp-shares-uat.azurerm_storage_share.ss[7] (import id: jellyfish): import module.alp-shares-uat.azurerm_storage_share.ss (id: jellyfish): resource azurerm_storage_share doesn't support import
```

### Panic Output

Not this time :+1:

### Expected Behavior

The resource should have been imported.

### Actual Behavior

The resource was not imported and the following error was emitted:

```
* module.alp-shares-uat.azurerm_storage_share.ss[7] (import id: jellyfish): import module.alp-shares-uat.azurerm_storage_share.ss (id: jellyfish): resource azurerm_storage_share doesn't support import
```

### Steps to Reproduce

1. Declare an `azurerm_storage_share` in the configuration.
2. Manually create the storage share in Azure (via the portal, CLI or API).
3. Attempt to import the storage share resource from Terraform.

### Important Factoids

Not that we're aware of.

### References

* hashicorp/terraform#1389 - end of the ticket details issue with map ordering that brought us here in the first place
* hashicorp/terraform#14477 - issue specifically about map ordering

**Comment by mbfrahry** [comment]
This is addressed in #1650.
