### ISSUE TITLE
Application gateway backend address pool fqdn list changes don't seem to be checked or applied

### ISSUE THREAD

**Issue by jnancel** [terraform-providers/terraform-provider-azurerm#3215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When I change the `fqdn_list` parameter on `backend_address_pool` inside `azurerm_application_gateway`, plan correctly see the changes to be done and apply do say that everything is ok and done but nothing was changed.

Plus, there was an error in my terraform and the URL I used contained `https://` and plan and apply didn't tell me it was not the format they were waiting for, but Azure portal did.

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.24.0
+ provider.external v1.1.0
+ provider.null v2.1.0
+ provider.random v2.1.0

### Affected Resource(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "app_gateway" {
...
  backend_address_pool = {
    name      = "${local.pool_name}"
    fqdn_list = ["${var.myfqdn}"]
  }
...
}
```

### Debug Output

```
Acquiring state lock. This may take a few moments...
module.application_gateway.azurerm_application_gateway.app_gateway: Modifying... (ID: /subscriptions/xxxxxxxx-...work/applicationGateways/app_gateway)
  backend_address_pool.0.fqdn_list.0: "my-url-before.example.com" => "https://my-url-after.example.com"
module.application_gateway.azurerm_application_gateway.app_gateway: Modifications complete after 2s (ID: /subscriptions/xxxxxxxx-...work/applicationGateways/app_gateway)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Plus a modification to an application gateway in 2 seconds is already very suspicious given the time it usually takes to change anything. :-)

### Expected Behavior

apply should tell me that the URL is not on the expected format and it should also apply the change.

### Actual Behavior

apply doesn't give me any warning and ends successfully.

### Steps to Reproduce

1. Change the `fqdn_list` of the `backend_address_pool` inside `azurerm_application_gateway` to a poorly formed URL ( for example with `https://` in front of it )
2. `terraform apply`

Thanks

**Comment by Lucretius** [comment]
`fqdn_list` appears to be both deprecated in favor of `fqdns` as well being optional and computed.  I  believe this combination means that you can only set these properties on create and subsequent updates to these fields will be ignored.

**Comment by jnancel** [comment]
You're right, RTFM for me, thanks for the quick answer.
