### ISSUE TITLE
Auto scaling not enabling via azure cli through terraform creation in kubernetes

### ISSUE THREAD

**Issue by hitesh1907nayyar** [terraform-providers/terraform-provider-azurerm#3225]
Hi,

I have created kubernetes cluster through terraform script. I have even enabled VMSSPreview using the link : https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#install-aks-preview-cli-extension.

Script through which i have created kubernetes on azure via terraform is attached,

provider "azurerm" {
}

resource "azurerm_resource_group" "k8s" {
    name     = "${var.resource_group_name}"
    location = "${var.location}"
}

data "azurerm_resource_group" "rg" {
  name = "${var.resource_group_name}"
}

resource "azurerm_virtual_network" "test" {
   name                = "${var.virtual_network_name}"
   location            = "${data.azurerm_resource_group.rg.location}"
   resource_group_name = "${data.azurerm_resource_group.rg.name}"
   address_space       = ["${var.virtual_network_address_prefix}"]
 
   subnet {
     name           = "${var.aks_subnet_name}"
     address_prefix = "${var.aks_subnet_address_prefix}" 
   }
 
 
   tags = "${var.tags}"
 }

data "azurerm_subnet" "kubesubnet" {
   name                 = "${var.aks_subnet_name}"
   virtual_network_name = "${azurerm_virtual_network.test.name}"
   resource_group_name  = "${data.azurerm_resource_group.rg.name}"
   
   depends_on = ["azurerm_virtual_network.test"]
 }

resource "azurerm_kubernetes_cluster" "k8s" {
    name                = "${var.cluster_name}"
    location            = "${azurerm_resource_group.k8s.location}"
    resource_group_name = "${azurerm_resource_group.k8s.name}"
    dns_prefix          = "${var.dns_prefix}"

    agent_pool_profile {
        name            = "agentpool"
        count           = "${var.agent_count}"
        vm_size         = "${var.agent_vmsize}"
        os_type         = "Linux"
        vnet_subnet_id  = "${data.azurerm_subnet.kubesubnet.id}"
    }

    service_principal {
        client_id     = "xxxxxxx-xxxxxxx-xxxxxxx"
        client_secret = "xxxxxxx-xxxxxxx-xxxxxxx"
    }

   network_profile {
    network_plugin     = "azure"
    dns_service_ip     = "${var.aks_dns_service_ip}"
    docker_bridge_cidr = "${var.aks_docker_bridge_cidr}"
    service_cidr       = "${var.aks_service_cidr}"
  }
    
   
    depends_on = ["azurerm_virtual_network.test"]
     tags       = "${var.tags}"

}

output "kube_config" {
  value = "${azurerm_kubernetes_cluster.k8s.kube_config_raw}"
}

After running the azure command i am getting an error:
$ az aks update \
>   --resource-group cluster1\
>   --name k8stest_cluster1 \
>   --enable-cluster-autoscaler \
>   --min-count 1 \
>   --max-count 3
Operation failed with status: 'Bad Request'. Details: AgentPool 'agentpool' has set auto scaling as enabled but is not on Virtual Machine Scale Sets, this is not allowed

What i need to do to modify the script?
Also  my present version of kubernetes installed is 1.11.9 and i want to update to 1.12.6. How can i do that ?

**Comment by tombuildsstuff** [comment]
hi @hitesh1907nayyar 

Thanks for opening this issue :)

Terraform doesn't support Kubernetes Auto Scaling (or it's dependencies, VMSS agents) at this time - as such we're unable to assist with workarounds such as via the Azure CLI. Support for Auto Scaling in Kubernetes is being tracked in #2502 which I'm going to close this issue in favour of, please subscribe to that issue for updates.

It's worth noting that we generally use the issues on this repository to track bugs and enhancements in the Github project; for questions we generally recommend [using one of the Community Resources](https://www.terraform.io/community.html) since there's more people available to answer more generic Azure questions.

Thanks!
