### ISSUE TITLE
Function App IP Restrictions

### ISSUE THREAD

**Issue by simonlegeek** [terraform-providers/terraform-provider-azurerm#3229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice if we could have the ip_restrictions configuration block in Azure Function App resource. This is already available in the App Service resource.

Keep up the good work!

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "global_app_function" {
    name                      = "hub-deployer-${var.deployment_suffix}"
    location                  = "${azurerm_resource_group.main_rg.location}"
    resource_group_name       = "${azurerm_resource_group.main_rg.name}"
    app_service_plan_id       = "${azurerm_app_service_plan.global_app_serviceplan.id}"
    storage_connection_string = "${azurerm_storage_account.global_function_storage.primary_connection_string}"
    https_only                = "true"
    # NOT AVAILABLE FOR FUNCTION APP IN TERRAFORM
    ip_restriction  = {
        ip_address = "65.245.25.32"
        subnet_mask = "255.255.255.255"
    }
```

**Comment by jitendrakandpal55** [comment]
Hi , Can we expect this change request will be implemented soon or not?

**Comment by alastairtree** [comment]
Can we also get the SCM/kudu IP restriction filter added as well as it is almost identical? Propose a syntax like so:

```hcl
resource "azurerm_function_app" "global_app_function" {
    name                      = "hub-deployer-${var.deployment_suffix}"
    location                  = "${azurerm_resource_group.main_rg.location}"
    resource_group_name       = "${azurerm_resource_group.main_rg.name}"
    app_service_plan_id       = "${azurerm_app_service_plan.global_app_serviceplan.id}"
    storage_connection_string = "${azurerm_storage_account.global_function_storage.primary_connection_string}"
    https_only                = "true"
    # NOT AVAILABLE FOR FUNCTION APP IN TERRAFORM
    ip_restriction  = {
        ip_address = "1.2.3.4"
        subnet_mask = "255.255.255.255"
    }
    scm_ip_restriction  = {
        ip_address = "5.6.7.8"
        subnet_mask = "255.255.255.255"
    }
}
```

**Comment by LucaPrete** [comment]
It would also be nice to be able to set vnet/subnet based restrictions.

**Comment by mbfrahry** [comment]
Hey all, I believe we now have all the functionality for restrictions in the provider so I'll be closing this down. Feel free to reopen or submit a new PR if some functionality has been missed after version 1.34.0 of the provider goes out.

**Comment by LucaPrete** [comment]
Guys, this is great, but I don't see this reflected in the docs, here: https://www.terraform.io/docs/providers/azurerm/r/function_app.html

Am I missing anything?

BTW, I don't even see an option for the VNET integration, which would preclude vnet/subnet filtering from working.

Thanks

**Comment by mbfrahry** [comment]
Hey @LucaPrete, unfortunately it hasn't released yet. You'll have to wait until version 1.34.0 goes out the door before you'll be able to see it on terraform.io. You could build your own provider off the master branch if you need it immediately

**Comment by jitendrakandpal55** [comment]
Hi Matthew,

Does the vnet subnet based restrictions are also available in this release.

Thanks,
Jitendra

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LucaPrete** [comment]
Great, thanks. Do you know the release date?

Il giorno dom 1 set 2019 alle ore 09:19 jitendrakandpal55 <
notifications@github.com> ha scritto:

**Comment by tombuildsstuff** [comment]
@LucaPrete we don't have a defined release date yet, but as we get closer we tend to post it on the milestone.

I've assigned this to the milestone so when this is released @hashibot will comment here that it's available :)

**Comment by LucaPrete** [comment]
Thanks!

Il giorno dom 1 set 2019 alle 11:25 Tom Harvey <notifications@github.com>
ha scritto:

**Comment by jungopro** [comment]
hello
I couldn't find any reference to this feature in the docs or release notes
Was that implemented?

thank you
Omer
