### ISSUE TITLE
Feature Request: Get object_id of current user

### ISSUE THREAD

**Issue by joakimhellum-in** [terraform-providers/terraform-provider-azurerm#3234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform AzureRM provider currently supports getting the object ID of the logged in Service Principal, but not the object ID of the logged in user. 

We can use the `azurerm_client_config` data source to get the current Service Principal object ID (`service_principal_object_id`). It would be nice to be able to get the current user object ID as well.

Use case: For currently logged in user to be able to self-assign permissions, for example when creating Key Vault. For reference Azure CLI does this when creating Key Vault using `az keyvault create`.

### New or Affected Resource(s)

* azurerm_client_config

### Potential Terraform Configuration

```hcl
data "azurerm_client_config" "current" {}

output "user_object_id" {
  value = "${data.azurerm_client_config.current.user_object_id}"
}
```

### References

* https://godoc.org/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac#SignedInUserClient
* https://godoc.org/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac#User

**Comment by tombuildsstuff** [comment]
hey @joakimhellum-in 

Thanks for opening this issue :)

I've been wanting to expose this functionality for a while, however I believe it should take a slightly different direction to what's proposed above; so that the same Terraform Configuration can be used both with a Service Principal or a User Account, whereas today a slightly different configuration has to be used which is confusing. As such I believe it'd be better to deprecate the existing `service_principal_object_id` field and introduce a new field `object_id` which returns the Object ID associated with the current authentication mechanism (either the Service Principal, or the logged in user) - what do you think?

Thanks!

**Comment by joakimhellum-in** [comment]
@tombuildsstuff Yes, completely agree it would be better to introduce new field `object_id` that returns the object ID of current service principal, user or managed identity.

My only justification for splitting this into `service_principal_object_id` and `user_object_id` is being able to determine if current object ID is a service principal or user. Example Terraform configuration for this:

```hcl
locals {
  service_principal_object_id = "${data.azurerm_client_config.current.service_principal_object_id}"
  user_object_id              = "${data.azurerm_client_config.current.user_object_id}"

  is_service_principal = "${local.service_principal_object_id != "" ? true : false}"
}
```

But after your comment and second thought I guess it's better to possibly introduce new field similar to `user.type` in output of `az account show` Azure CLI command. For example:

Run `az login` to log in to Azure as user, and then run `az account show` (type is "user):

```json
{
  "environmentName": "AzureCloud",
  "id": "ddab71c1-4649-46e2-8b63-9ecfb860c3fa",
  "isDefault": true,
  "name": "terraform-test-1",
  "state": "Enabled",
  "tenantId": "f4683495-fdad-496a-82fb-e2c3a24082f3",
  "user": {
    "name": "user@example.com",
    "type": "user"
  }
}
```

Run `az login --service-principal -u http://terraform-test-1 -p ...` to log in to Azure with service principal, and then run `az account show` (type is "servicePrincipal"):

```json
{
  "environmentName": "AzureCloud",
  "id": "ddab71c1-4649-46e2-8b63-9ecfb860c3fa",
  "isDefault": true,
  "name": "terraform-test-1",
  "state": "Enabled",
  "tenantId": "f4683495-fdad-496a-82fb-e2c3a24082f3",
  "user": {
    "name": "http://terraform-test-1",
    "type": "servicePrincipal"
  }
}
```

I don't have any use case for this other than doing a "who am I", meaning if object ID is user, then get user information from Azure AD.

**Comment by JustinGrote** [comment]
I'm for this one, currently my users have to run a powershell "prep" script to save their objectID as an environment variable before their terraform will "work", I should have access to a single datasource attribute for the current logged in user (or service) objectID for the purposes of assigning permissions.

**Comment by JustinGrote** [comment]
### Workaround
Here's a workaround. Requires az cli to be present in the path.

```
data "external" "thisAccount" {
  program = ["az","ad","signed-in-user","show","--query","{displayName: displayName,objectId: objectId,objectType: objectType}"]
}

resource "azurerm_key_vault_access_policy" "this" {
  vault_name          = "${azurerm_key_vault.this.name}"
  resource_group_name = "${azurerm_resource_group.this.name}"
  #Grant access to the terraform account for purposes of adding additional keys
  tenant_id = "${data.azurerm_client_config.this.tenant_id}"
  object_id = "${data.external.thisAccount.result.objectId}"
  secret_permissions = [
    "set",
    "get",
    "list"
  ]
}

output "displayName" {
  value = "${data.external.thisAccount.result.displayName}"
}
output "objectId" {
  value = "${data.external.thisAccount.result.objectId}"
}

output "objectType" {
  value = "${data.external.thisAccount.result.objectType}"
}
```

**Comment by dgdarlington** [comment]
If implementing a unified object ID for both user and service principal is too much, I'm thinking a simple if function would suffice for those who may need both.

```
object_id = "${data.azurerm_client_config.current.service_principal_object_id != "" 
                ? data.azurerm_client_config.current.service_principal_object_id 
                : data.azurerm_client_config.current.object_id}"
```

My use case is sometimes 
1.  I will build a Key Vault with my account and I will need access. 
1.  Other times a Service Principal through Azure DevOps will build the Key Vault and will need access.

**Comment by jpluscplusm** [comment]
@JustinGrote fantastic workaround! Thanks a million! :-D

2 minor points:
- You've got `thisAccount` and `this_az_account` referring to the same thing;, possibly from before an edit? I don't think the example works in its current form, quite!
- in the external data source, please add a `-o=json` param for folks who might have configured a non-JSON default output format :-)

**Comment by JustinGrote** [comment]
@jpluscplusm I think I've since refactored it to be *way* simpler in 0.12, may post that later if I have time.

**Comment by samueljmello** [comment]
Any update on this? Trying to create an access policy for a keyvault and need to get the authenticated users object id.

**Comment by mbrancato** [comment]
I've run into the same use-case as https://github.com/terraform-providers/terraform-provider-azurerm/issues/3234#issuecomment-494797190
