### ISSUE TITLE
Azure PostgreSQL Server storage sizes are invalid

### ISSUE THREAD

**Issue by hexadite-tomer** [terraform-providers/terraform-provider-azurerm#324]
The postgresql_server resource receives 'storage_mb' as an argument to set the capacity of the database. In the documentation and the code, the only 2 legitimate arguments are 51200 and 102400. 

From /azurerm/resource_arm_postgresql_server.go:

`"storage_mb": {
				Type:     schema.TypeInt,
				Required: true,
				ForceNew: true,
				ValidateFunc: validateIntInSlice([]int{
					51200,
					102400,
				}),`

The issue is that azure receives as valid database sizes 51200 up to 947200 in increments of 128000, so for example 179200 is a legitimate value, and 102400 is not. Applying a template with 102400 as an argument will fail with an error from azure, and applying a template with 179200 as an argument will fail with an error from terraform.

The function should be updated to reflect all the legitimate values.

**Comment by tombuildsstuff** [comment]
Hey @hexadite-tomer 

Thanks for opening this issue :)

I can confirm this is an issue - when we were first building support for the PostgreSQL Resources, it was only possible to select 50GB or 100GB of storage, however it appears between finishing testing and shipping this that it's now possible to select another storage options.. as such we'll be sure to update the validation to reflect this.

Thanks!

**Comment by hexadite-tomer** [comment]
Hey @tombuildsstuff 

Thanks for the fast response. Looking forward to seeing the fix. Appreciate all your work!

**Comment by tombuildsstuff** [comment]
Hey @hexadite-tomer

Just to let you know that I've opened #329 which includes a fix for this :)

Thanks!
