### ISSUE TITLE
"eus2" => "eastus2" (forces new resource) for azurerm_log_analytics_solution

### ISSUE THREAD

**Issue by adubnik** [terraform-providers/terraform-provider-azurerm#3256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, I'm using the AzureRM 1.24 and it seem API or TF interpretation publishes wrong convention for the region affinity for the azurerm_log_analytics_solution, namely when resource is created in eastus2 terraform records it as located in eus2. 

This can be a result of TF code or most likely Azure API in any case this does not look right as every time TF template gets applied to the region it forces resource rebuild as it assumes location have changed.

**Comment by ganga1980** [comment]
@adubnik, Region of the Log analytics solution should be same as region of Log Analytics workspace. 
 Can you please provide TF template snippet  which you have used to deploy the log analytics solution?

**Comment by adubnik** [comment]
@ganga1980 here you go - if applied 2 times triggers a bug

`
resource "azurerm_resource_group" "test" {
  name     = "k8s-log-analytics-test"
  location = "eastus2"
}

resource "random_id" "workspace" {
  keepers = {
    # Generate a new id each time we switch to a new resource group
    group_name = "${azurerm_resource_group.test.name}"
  }

  byte_length = 8
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "k8s-workspace-${random_id.workspace.hex}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "PerGB2018"
}

resource "azurerm_log_analytics_solution" "test" {
  solution_name         = "ContainerInsights"
  location              = "${azurerm_resource_group.test.location}"
  resource_group_name   = "${azurerm_resource_group.test.name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.test.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.test.name}"

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}
`

`
-/+ azurerm_log_analytics_solution.test (new resource required)
...
      location:              "eus2" => "eastus2" (forces new resource)
...
`

**Comment by tombuildsstuff** [comment]
hi @adubnik @ganga1980 

Thanks for opening this issue :)

Taking a look into this this appears to be a breaking change in the Azure API, but only within specific regions (since this is returned as `westeurope` within the West Europe region). As such [I've opened an issue on the Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs/issues/5676) where someone should be able to take a look at this.

Since the underlying issue here is with the upstream API - I'm going to close this issue for the moment but would you mind subscribing to that issue for updates?

Thanks!

**Comment by AntonChernysh** [comment]
I think Azure fixed this over last weekend: It works as expected now:
```List of available regions for the resource type is 'eastus,westeurope,southeastasia,australiasoutheast,westcentralus,japaneast,uksouth,centralindia,canadacentral,westus2,australiaeast,australiacentral,francecentral,koreacentral,northeurope,centralus,eastus2,eastasia,westus,southcentralus'```
No more "Short" locations for log analytics solution.
