### ISSUE TITLE
Can't delete key vault

### ISSUE THREAD

**Issue by jungopro** [terraform-providers/terraform-provider-azurerm#3258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azuread v0.2.0
+ provider.azurerm v1.22.0
+ provider.random v2.1.1
+ provider.template v2.1.1

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource "random_string" "random_string" {
  keepers = {
    # Generate a new ID only when a new resource group is defined
    resource_group = "${var.resource_group}"
  }

  length  = 4
  upper   = false
  special = false
}

locals {
  name_length = "${length("${var.name}")}"
  name        = "${local.name_length < 24 ? "${var.name}" : "${substr("${var.name}", 0, "${min("${local.name_length}", 20)}")}${random_string.random_string.result}" }"
}

resource "azurerm_key_vault" "key-vault" {
  name                = "${local.name}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group}"

  sku {
    name = "${var.sku_name}"
  }

  network_acls {
    default_action = "Allow"
    bypass         = "AzureServices"
  }
  tenant_id                       = "${var.tenant_id}"
  enabled_for_deployment          = "${var.enabled_for_deployment}"
  enabled_for_disk_encryption     = "${var.enabled_for_disk_encryption}"
  enabled_for_template_deployment = "${var.enabled_for_template_deployment}"
  tags                            = "${var.tags}"
}
resource "azurerm_key_vault_access_policy" "policy" {
  key_vault_id = "${azurerm_key_vault.key-vault.id}"
  tenant_id    = "${var.tenant_id}"
  object_id    = "${var.object_id}"

  key_permissions = [
    "backup",
    "create",
    "decrypt",
    "delete",
    "encrypt",
    "get",
    "import",
    "list",
    "purge",
    "recover",
    "restore",
    "sign",
    "unwrapKey",
    "update",
    "verify",
    "wrapKey",
  ]

  secret_permissions = [
    "backup",
    "delete",
    "get",
    "list",
    "purge",
    "recover",
    "restore",
    "set",
  ]

  certificate_permissions = [
    "create",
    "delete",
    "deleteissuers",
    "get",
    "getissuers",
    "import",
    "list",
    "listissuers",
    "managecontacts",
    "manageissuers",
    "purge",
    "recover",
    "setissuers",
    "update",
  ]
}

```

### Steps to Reproduce

1. `terraform apply`
1. `terraform destroy`

error:

* azurerm_key_vault_secret.secret: keyvault.BaseClient#DeleteSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied" InnerError={"code":"AccessDenied"}
* module.admin_region.module.customer_db_1_admin_password.azurerm_key_vault_secret.secret (destroy): 1 error(s) occurred:

* azurerm_key_vault_secret.secret: keyvault.BaseClient#DeleteSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied" InnerError={"code":"AccessDenied"}

### References

Hello

I'm having trouble with proper setup of Key Vault:
The scenario is this:

- Terraform SPN creates a KV
- Terraform SPN creates an access policy for itself with full permissions on the KV
- Terraform SPN creates a secret inside the KV
- Terraform SPN creates other access policies for Azure resources (such as function apps, users, groups, etc.)

The problem is this:
1. If I create the access policy **for the terraform spn** as a separate object using `azurerm_key_vault_access_policy` resource, the **create** phase works fine but the **destroy** phase fails. This is because:
- The policy for terraform SPN is deleted before the secret
- Terraform SPN can't delete the secret
- The automation fails

2. If I create the **Terraform SPN** policy inline inside the `azurerm_key_vault` resource, any other policies I create in additions are deleted upon updates of the environment

So, assuming I want a full key-vault setup using policies and secrets and such, what is the proper way to achieve that, end-to-end (apply-update-destroy)

Thanks

Omer

**Comment by paultyng** [comment]
If there isn't an explicit dependency to control the ordering (you can use `terraform graph` to confirm the ordering), you can use `depends_on` to explicitly create a dependency so that the ordering is appropriate. If you aren't able to influence the graph to get the ordering required though, there isn't a lot Terraform can do to adjust that ordering.

**Comment by jungopro** [comment]
thanks @paultyng, I think my bigger problem is that i'm over-using modules and in resource is a module of it's own. depends_on doesn't support modules...
I think I will do a deep refactoring to simplify the code base and couple some of the resources together

I will close this case for now as it is more architectural than a bug

Thanks
