### ISSUE TITLE
azurerm_managed_disk does not support FromImage

### ISSUE THREAD

**Issue by jzampieron** [terraform-providers/terraform-provider-azurerm#327]
The Azure REST API supports creating a separate managed disk instance from a standard offering image, as opposed to within a VM OS disk definition block.

https://docs.microsoft.com/en-us/rest/api/compute/manageddisks/disks/disks-create-or-update

There are a number of terraform use-cases where separating the disk definition from the VM definition is extremely useful. 
Particularly: Certain changes to a VM require a destroy/rebuild and terraform can't reattach an existing OS disk without code changes (FromImage -> Attach).

This means that all your VM redeploys that don't set `delete os disk on termination` will fail.

This means otherwise generic and maintainable IaaS code is now operation specific to that one change.

### Terraform Version
0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_managed_disk

### Expected Behavior
Terraform creates the managed disk and then attaches it to the VM.

### Actual Behavior
Terraform throws the following error:
`module.dcos.azurerm_managed_disk.dcosBootstrapOSDisk: expected create_option to be one of [Import Empty Copy], got FromImage`

**Comment by nbering** [comment]
I tried adding this myself once, but found it functionally impossible to use an OS disk created from an image because seeding the image with user credentials occurs when azure is issued the create command. You could attach the created image but there's no way to log in.

**Comment by michiels** [comment]
Maybe related to this:

I have the problem that I'm currently importing an OS disk that I created via the Azure Portal, and now try to import into our Terraform definition. When viewing Terra form state it lists the "FromImage" `create_option`, but this is not a valid option so it means I cannot define/import my OS Disk in my Terraform files without destroying the disk when running plan/apply.

My short term solution is to just leave it out.

**Comment by nbering** [comment]
I hadn't thought of custom os images, or I would have submitted a PR wish what I had done. My changes were virtually the same as what @tombuildsstuff added.

**Comment by michiels** [comment]
Many thanks @tombuildsstuff
