### ISSUE TITLE
Terraform don't support MySQL DB replica 

### ISSUE THREAD

**Issue by Arun-Ghosh** [terraform-providers/terraform-provider-azurerm#3276]
Hi,

It would be really good if we able to manage or create MySQL DB replica from terraform. Currently Azure support replica of same size with same configuration.

**Comment by tombuildsstuff** [comment]
hi @Arun-Ghosh 

Thanks for opening this issue.

So that we can track this feature request correctly would you mind re-opening this with the Feature Request issue template?

Thanks!
