### ISSUE TITLE
Feature Request: Support for Azure Virtual WAN and child resources

### ISSUE THREAD

**Issue by Jandakast** [terraform-providers/terraform-provider-azurerm#3279]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Support for Azure Virtual WAN and child resources

Looking for the ability to deploy and manage Azure Virtual WAN resources with Terraform.

* ~azurerm_virtual_wan~ [now available](https://www.terraform.io/docs/providers/azurerm/r/virtual_wan.html)
* azurerm_virtual_wan_hub
* azurerm_virtual_wan_site_to_site_vpn
* azurerm_virtual_wan_expressroute_circuits (Currently in Preview)

### References

https://docs.microsoft.com/en-us/azure/virtual-wan/
https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2018-11-01/virtualwans
https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2018-11-01/virtualhubs
https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2018-11-01/vpnsites

**Comment by nathanlctnstn** [comment]
Subscribed.

**Comment by joakimhellum-in** [comment]
Hi, we need this in the organization ASAP so we started working on some of the resources for Azure Virtual WAN, such as: `azurerm_virtual_wan`, `azurerm_virtual_hub`, `azurerm_vpn_gateway`, `azurerm_vpn_gateway_connection`, `azurerm_p2s_vpn_gateway`, `azurerm_express_route_gateway`, `azurerm_virtual_hub_route_table`, `azurerm_virtual_hub_network_connection`. We hope to make PR ready for review early next week.

**Comment by lctnstn** [comment]
Hi @joakimhellum-in , have you made any traction here?

**Comment by venkybems** [comment]
@joakimhellum-in - Any update on the virtual-wan resources?

**Comment by mybayern1974** [comment]
An update for ```azurerm_p2s_vpn_gateway``` that this resource is not functionality ready yet though it's in the preview stage now. The rough estimated date when it could work is going to be around Sep 20, 2019

**Comment by skalragg** [comment]
Apologies if I should be posting this somewhere else, any timeline on the virtual WAN child functions. eg. building a site to site VPN after resource **azurerm_vpn_gateway** has been attached to a virtual hub

I can see PR like where it looks like some of this functionality was removed #5004 

I would be really grateful if the vwan and child resources were expanded.  Thanks

**Comment by tombuildsstuff** [comment]
@skalragg unfortunately the Azure API is broken, so the `connections` functionality ended up having to be removed; however the resource development is mostly done - so once the API's in a good state we can look to reintroduce it; but at the moment we're waiting on the Networking team

Thanks!

**Comment by skalragg** [comment]
> @skalragg unfortunately the Azure API is broken, so the `connections` functionality ended up having to be removed; however the resource development is mostly done - so once the API's in a good state we can look to reintroduce it; but at the moment we're waiting on the Networking team
> 
> Thanks!

@tombuildsstuff Thanks for the quick response! is this the best thread #3279 to keep checking for updates, or should I be looking elsewhere? Thanks

**Comment by tombuildsstuff** [comment]
@skalragg for now, I'd suggest subscribing to this issue as the best place to ask, since we can run the tests to confirm this has been fixed

**Comment by skalragg** [comment]
> @skalragg for now, I'd suggest subscribing to this issue as the best place to ask, since we can run the tests to confirm this has been fixed

Hi tombuildsstuff,  
Any feedback from the network team in relation to when this may be resolved.  Many thanks

**Comment by LaurentLesle** [comment]
@tombuildsstuff are you saying it is broken with the version 2019-11-01 of the networking sdk?

**Comment by tombuildsstuff** [comment]
@LaurentLesle last time we took a look at this (November/December) the API (2019-09-01) was broken so this ended up having to be reverted. The [original work can be found in this commit](https://github.com/terraform-providers/terraform-provider-azurerm/commit/6b498367ecda8edeee6fd7222d128469a1c07811) (this is intentionally split-out rather than in-lined) but unfortunately we've not tested 2019-11-01 yet

**Comment by skalragg** [comment]
@tombuildsstuff any timeline for retesting / or is there any way to use the previous commit 
Thanks

**Comment by baljitaujlaVD** [comment]
Hi, any update on this request?

**Comment by jturver1** [comment]
It would also be great if the VWAN capability will include the "Secure Virtual Hub" and - independently - Firewall Manager integration for deployment of Azure Firewall into a VWAN hub Azure firewall instance, and subsequent management of firewall policy. 

This is not GA yet (I'm guessing it will be soon), but it will be a very highly adopted use case vs. traditional VNET hubs/NVA firewalls going forward.

**Comment by petr-x** [comment]
for 'Azure Firewall Manager resources' see #7319

**Comment by cidwtz** [comment]
The Azure virtualwans API version is updated to "2020-05-01" with a few new features rolled out include routing table on the hub/connections.  Do it still have the bug in API in 2019?  I just wonder if it is possible to implement those features now?

**Comment by arnaudlh** [comment]
hi, are we tracking the creation of the Express Route Circuit to a Virtual Hub? From the UI, we can connect multiple circuits into the ER attached to the virtual hub, would be nice to support it with TF - cc @LaurentLesle @arnoldna

**Comment by neil-yechenwei** [comment]
@cidwtz , thanks for your comment. I assume the most features of VirtualWans API except Express Route Circuit have been implemented in the latest azurerm.

**Comment by tombuildsstuff** [comment]
👋 

Since this is turning into more of an open-ended meta-issue (which'll obviously expand over time as new functionality is added) - I'm going to suggest we close this issue for the moment, since support for the majority of these resources are now supported.

For new functionality going forward, including the Express Route Circuit functionality that @arnaudlh has mentioned above, would you mind [opening a new Feature Request including the relevant details so that we can track this](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) in a more granular fashion?

Thanks!
