### ISSUE TITLE
log_analytics_workspace: enable daily volume cap setting

### ISSUE THREAD

**Issue by jfcoz** [terraform-providers/terraform-provider-azurerm#3288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow to set daily volume cap on log analytics workspace

### New or Affected Resource(s)

* azurerm_log_analytics_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_log_analytics_workspace" "test" {
  name                = "acctest-01"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "PerGB2018"
  retention_in_days   = 30
  daily_volume_cap    = 2
}
```

### References

* https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-cost-storage#daily-cap

**Comment by GCole64** [comment]
👍

**Comment by katbyte** [comment]
Currently not in SDK v32 and the `2015-11-01-preview` API version

**Comment by MATTHEWTAYLOR1995** [comment]
Hey guys, does anyone know if there has been any movement on this?

**Comment by fl-max** [comment]
Seems the SDK has been updated but still not seeing an [option](https://github.com/Azure/azure-sdk-for-go/blob/090dc0ee4d8d2d60e2a9525774d967a4111a2b0c/services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go#L104) for daily cap.
