### ISSUE TITLE
azurerm_subnet_network_security_group_association is changing each time terraform apply

### ISSUE THREAD

**Issue by npigit** [terraform-providers/terraform-provider-azurerm#3289]
**Terraform Version**

Terraform v0.11.13
+ provider.azurerm v1.25.0
+ provider.random v2.1.0

**Affected Resource(s)**
azurerm_subnet_network_security_group_association

**Terraform Configuration Files**

`
provider "azurerm" {
  subscription_id = "${var.azure["subscription_id"]}"
  client_id       = "${var.azure["client_id"]}"
  client_secret   = "${var.azure["client_secret"]}"
  tenant_id       = "${var.azure["tenant_id"]}"

  version = "=1.25.0"
}

resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_security_group" "test" {
  name                = "example-nsg"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet_network_security_group_association" "test" {
  subnet_id                 = "${azurerm_subnet.test.id}"
  network_security_group_id = "${azurerm_network_security_group.test.id}"
}`

**Result**
each time I execute terraform apply without modifying the code, I have this behavior

terraform apply:
network_security_group_id: "" => "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg"
subnet_id: "" => "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/virtualNetworks/example-network/subnets/internal"

next terraform apply:
~ azurerm_subnet.test
network_security_group_id: "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg" => ""

next terraform apply

    azurerm_subnet_network_security_group_association.test
    id:
    network_security_group_id: "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg"
    subnet_id: "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/virtualNetworks/example-network/subnets/internal"

next terrafom apply:
~ azurerm_subnet.test
network_security_group_id: "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg" => ""

and so on

**Expected behaviour**
Terraform should applied once the nsg association and not change it each time terraform apply is executed

**Comment by npigit** [comment]
each time I execute terraform apply, I have this behavior

terraform apply:
   network_security_group_id: "" => "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg"
  subnet_id:                 "" => "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/virtualNetworks/example-network/subnets/internal"

next terraform apply:
~ azurerm_subnet.test
      network_security_group_id: "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg" => ""

next terraform apply
 + azurerm_subnet_network_security_group_association.test
      id:                        <computed>
      network_security_group_id: "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg"
      subnet_id:                 "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/virtualNetworks/example-network/subnets/internal"

next terrafom apply:
~ azurerm_subnet.test
      network_security_group_id: "/subscriptions/xxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/example-nsg" => ""

and so on

**Comment by npigit** [comment]
`

provider "azurerm" {
  subscription_id = "${var.azure["subscription_id"]}"
  client_id       = "${var.azure["client_id"]}"
  client_secret   = "${var.azure["client_secret"]}"
  tenant_id       = "${var.azure["tenant_id"]}"

  version = "=1.25.0"
}

resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_security_group" "test" {
  name                = "example-nsg"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet_network_security_group_association" "test" {
  subnet_id                 = "${azurerm_subnet.test.id}"
  network_security_group_id = "${azurerm_network_security_group.test.id}"
}
`

**Comment by tombuildsstuff** [comment]
hi @npigit 

Thanks for opening this issue :)

Unfortunately at this time the association between the Subnet and the Network Security Group needs to be specified in both the `azurerm_subnet` and the `azurerm_subnet_network_security_group_association` resource, this is to ensure this isn't a breaking change. We plan to change this behaviour in version 2.0 of the Provider, such that this will only need to be set on the `azurerm_subnet_network_security_group_association ` resource (and the `network_security_group_id` field on the `azurerm_subnet` field will be removed); however as mentioned above unfortunately prior to 2.0 this needs to be specified in both resources, as such this is noted in the documentation:

> NOTE: Subnet <-> Network Security Group associations currently need to be configured on both this resource and using the network_security_group_id field on the azurerm_subnet resource. The next major version of the AzureRM Provider (2.0) will remove the network_security_group_id field from the azurerm_subnet resource such that this resource is used to link resources in future.

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by npigit** [comment]
Hello Tom,

Thank you for your email.

I already successfully applied the workaround ☺

I am looking forward for the version 2.0 ☺☺☺

Best regards,
Nicolas
