### ISSUE TITLE
`azurerm_redis_cache` - support for georeplication

### ISSUE THREAD

**Issue by archmangler** [terraform-providers/terraform-provider-azurerm#3294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to deploy redis cache via terraform with geo-replication enabled.

However there is nothing in the documentation that mentions this option.

There is a configuration for rediscache clustering, however, nothing indicates if this includes geo-replication (or if this is simply a local intra-region clustering).

The microsoft documentation on redis cache georeplication indicates an option for adding a "geo-replication link", which the terraform resource has no mention of:

https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-geo-replication

I would assume this means no support for georeplication?

**Comment by tombuildsstuff** [comment]
hi @archmangler

Thanks for opening this issue.

At this time the Azure Provider doesn't support georeplication for Redis Caches, but we'll take this as an enhancement request for that. Taking a look [it appears support for this is available in the Azure SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/services/redis/mgmt/2018-03-01/redis/linkedserver.go) and that this'd be best implemented as a new resource.

Thanks!

**Comment by DeanPH** [comment]
Hi,
Any progress on this?
Thanks!

**Comment by MNashDev** [comment]
Looking for an update on this issue please, 
We're looking to implement Geo-Replicated Redis for a client.
We have built the rest of the environment via terraform and so would be good to get the Redis instances deployed this way aswell.

**Comment by pearcec** [comment]
@DeanPH and @MNashDev give it a test if you can.  Maybe the maintainers will cut it into the next release.

**Comment by LaurentLesle** [comment]
@katbyte Looks like it has been released in the 2.23 including the documentation but the documentation is is not showing up on the public website

![image](https://user-images.githubusercontent.com/4702224/91714338-17925100-ebbe-11ea-9517-325b2ad09f6a.png)

https://github.com/terraform-providers/terraform-provider-azurerm/pull/8026/files
