### ISSUE TITLE
IoT hub endpoint created assuming same resource group

### ISSUE THREAD

**Issue by ukphillips** [terraform-providers/terraform-provider-azurerm#3295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.23.0

### Affected Resource(s)

IoT Hub

* `azurerm_iothub`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub" "module" {
  name                = "${var.hubname}-iothub"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.location}"

  sku {
    name     = "${var.iothub_sku_name}"
    tier     = "${var.iothub_sku_tier}"
    capacity = "${var.iothub_sku_capacity}"
  }

  endpoint {
    type              = "AzureIotHub.ServiceBusQueue"
    connection_string = "${var.sb-queue-endpoint-connection-string}"
    name              = "myevent-queue"
  }

  route {
    name           = "myevent"
    source         = "DeviceMessages"
    condition      = "$body.eventType = 'myevent'"
    endpoint_names = ["myevent-queue"]
    enabled        = true
  }
}
```

Created successfully 

### Panic Output

N/A

### Expected Behavior

Custom endpoint should be created on IoT hub

### Actual Behavior

Custom endpoint appears created, but when you drill into it, there is a not found message. Upon drilling into the resources in the resource explorer:

![image](https://user-images.githubusercontent.com/18452981/56504349-3d95e480-64e6-11e9-9186-f10199e99f51.png)

My test12 queue was manually created in the portal, and is correct, but the one above it (created by TF) is created with the assumption that the servicebus will reside in the same resource group as the parent (which is the IoT hub), this is not correct and is failing to connect the resourced together properly. 

I would expect there to be an optional override to specify a different resourcegrouo/subscriptionid for the queue. This also seems to be an issue with other endpoint resources as well.

### Steps to Reproduce

1. Create a servicebus queue
2. Reference sb queue in an IoT endpoint 

### Important Factoids

N/A

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems currently terraform would use the resource group where iothub exists as the resource group of endpoint by default. So I made a [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8032)to allow to specify the endpoint resource group. Hopes it would be helpful. Thanks.
