### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment attempts to change or destroy existing resources

### ISSUE THREAD

**Issue by nickmhankins** [terraform-providers/terraform-provider-azurerm#3297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Terraform Version**

Terraform v0.11.13
+ provider.azurerm v1.21.0

**Affected Resource(s)**

azurerm_virtual_machine_data_disk_attachment
azurerm_managed_disk

**Terraform Configuration Files**
Terraform files can be found here - https://gist.github.com/nickmhankins/d594427e71fe018b5b4de18bf5e82d97

**Debug Output**

**Expected Behavior**
Adding either a Virtual Machine (increasing count) or adding an additional data disk to the datadisk variable should add the requested disk or additional VM with correct disk layout

**Actual Behavior**

Adding a disk or virtual machine causes what appears to be a shuffling of drives.  It will attempt to resize existing disks, move existing disks to other VMs, move disks to different luns, change disk ID or name, etc.

**Steps to Reproduce**

   terraform init
   terraform apply
   After initial creation, increase VM count or attempt to add a disk to the data disks variable

Here is a small sample of some of the changes terraform wants to make.  It should also be noted that the disks it wants to add already exists in Azure, created by the previous run:
```
-/+ module.aas_resources.module.aas_vm_avzone_creation.azurerm_virtual_machine_data_disk_attachment.disk_attachments[11] (new resource required)
      id:                        "<subscription_info>/resourceGroups/p0-sap-rg-rfp/providers/Microsoft.Compute/virtualMachines/saprfpaasp004/dataDisks/saprfpaasp004-ca" => <computed> (forces new resource)
      caching:                   "None" => "None"
      create_option:             "Attach" => "Attach"
      lun:                       "2" => "3" (forces new resource)
      managed_disk_id:           "<subscription_info>/resourceGroups/p0-sap-rg-rfp/providers/Microsoft.Compute/disks/saprfpaasp004-ca" => "${element(azurerm_managed_disk.data_disk.*.id, count.index)}" (forces new resource)
      virtual_machine_id:        "<subscription_info>/resourceGroups/p0-sap-rg-rfp/providers/Microsoft.Compute/virtualMachines/saprfpaasp004" => "<subscription_info>/resourceGroups/p0-sap-rg-rfp/providers/Microsoft.Compute/virtualMachines/saprfpaasp003" (forces new resource)
      write_accelerator_enabled: "false" => "false"

  + module.aas_resources.module.aas_vm_avzone_creation.azurerm_managed_disk.data_disk[15]
      id:                        <computed>
      create_option:             "Empty"
      disk_size_gb:              "50"
      location:                  "westus2"
      name:                      "saprfpaasp004-sid"
      resource_group_name:       "p0-sap-rg-rfp"
      source_uri:                <computed>
      storage_account_type:      "Premium_LRS"
      zones.#:                   "1"
      zones.0:                   "3"

  + module.aas_resources.module.aas_vm_avzone_creation.azurerm_virtual_machine_data_disk_attachment.disk_attachments[12]
      id:                        <computed>
      caching:                   "None"
      create_option:             "Attach"
      lun:                       "0"
      managed_disk_id:           "${element(azurerm_managed_disk.data_disk.*.id, count.index)}"
      virtual_machine_id:        "<subscription_info>/resourceGroups/p0-sap-rg-rfp/providers/Microsoft.Compute/virtualMachines/saprfpaasp004"
      write_accelerator_enabled: "false"

  ~ module.aas_resources.module.aas_vm_avzone_ha_creation.azurerm_managed_disk.data_disk[7]
      disk_size_gb:              "128" => "50"
```

I have a feeling it is partially because of the way the nested loop is constructed but I can't seem to figure out why it wants to make these changes, particularly since things like lun and size are coming from a variable.

**Comment by tombuildsstuff** [comment]
hi @nickmhankins 

Thanks for opening this issue :)

This is a bug in Terraform (Core) 0.11 where `count` is based on an index, rather than using the values within the data - which means Terraform's validation logic believes a new resource is required because the values have changed when they're not allowed too. This issue's being tracked upstream in https://github.com/hashicorp/terraform/issues/17179 - since this is an issue in Terraform Core, rather than keeping this issue open (when the fix is in another repo) I'm going to close this issue for the moment - would you mind subscribing to that issue for updates?

Thanks!

**Comment by NathanPrado** [comment]
Hey @tombuildsstuff  - Understanding that this is an issue with the Core code to be fixed elsewhere, is there a recommended workaround when one is trying to generate a dynamic number of disks/disk attachments per run as in the issue?
