### ISSUE TITLE
azurerm_network_interface does not maintain the order of the dns_servers list

### ISSUE THREAD

**Issue by raphaelcardoso** [terraform-providers/terraform-provider-azurerm#3298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.13
+ provider.azurerm v1.25.0

### Affected Resource(s)
* `azurerm_network_interface`

### Terraform Configuration Files
```hcl
resource "azurerm_network_interface" "this" {
  name                = "${var.vm_name}-nic"
  location            = "${azurerm_resource_group.this.location}"
  resource_group_name = "${azurerm_resource_group.this.name}"

  dns_servers = [
    "10.0.0.5",
    "10.0.0.6",
    "172.27.0.5"
  ]

  ip_configuration {
    name      = "ipconfig1"
    subnet_id = "${data.azurerm_subnet.this.id}"

    private_ip_address_allocation = "Static"
    private_ip_address            = "172.27.1.10"
  }
}
```

### Expected Behavior
Fragment from the terraform.tfstate file, containing sequential numbers that rule the order.
```
"primary": {
	"id": "/subscriptions/...",
	"attributes": {
		"applied_dns_servers.#": "3",
		"applied_dns_servers.0": "10.0.0.5",
		"applied_dns_servers.1": "10.0.0.6",
		"applied_dns_servers.2": "172.27.0.5",
		"dns_servers.#": "3",
		"dns_servers.0": "10.0.0.5",
		"dns_servers.1": "10.0.0.6",
		"dns_servers.2": "172.27.0.5",
		"...": "...",
	},
	"meta": {},
	"tainted": false
},
```

### Actual Behavior
Fragment from the terraform.tfstate file, containing random numbers that rule the order.
```
"primary": {
	"id": "/subscriptions/...",
	"attributes": {
		"applied_dns_servers.#": "3",
		"applied_dns_servers.2028884304": "10.0.0.6",
		"applied_dns_servers.3210460864": "172.27.0.5",
		"applied_dns_servers.3790012650": "10.0.0.5",
		"dns_servers.#": "3",
		"dns_servers.2028884304": "10.0.0.6",
		"dns_servers.3210460864": "172.27.0.5",
		"dns_servers.3790012650": "10.0.0.5",
		"...": "...",
	},
	"meta": {},
	"tainted": false
},
```

### Steps to Reproduce
1. `terraform apply`

**Comment by odee30** [comment]
This still seems to be an issue with Terraform 0.12.6 and AzureRM provider v1.34.
