### ISSUE TITLE
Azure Firewall subnet change

### ISSUE THREAD

**Issue by Nepomuceno** [terraform-providers/terraform-provider-azurerm#3299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When you create an Azure firewall provider you are required to create a subnet called AzureFirewallSubnet. and them pass this subnet as the subnet Id of azure firewall currently there is no validation that this subnet has the correct required name and that other subnets do no have this name.

The problem with that is that when you do any change in the Firewall Subnet that requires the destruction of this subnet the firewall it is not marked for destruction. 

### Terraform (and AzureRM Provider) Version
Terraform v0.11.13
+ provider.azurerm v1.23.0

* `azurerm_subnet`
* `azurerm_firewall`

**Comment by sjones-sot** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/pull/3406

I believe this addresses the above correctly.
