### ISSUE TITLE
Support Auth users on function apps using siteAuthSettings

### ISSUE THREAD

**Issue by joakimhew** [terraform-providers/terraform-provider-azurerm#3304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
A user, @a144359, requested in the PR #2831 that we also add support for setting authentication settings for function apps.

I've briefly looked into it and don't see any problems implementing this for function apps as well. I will try to find some time in the upcoming week(s) to do this but if anyone else wants to work on this, please let me know.

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

I suggest a configuration that looks exactly like the one for web apps: 

```hcl
auth_settings {
  enabled                       = true
  issuer                        = "https://sts.windows.net/d13958f6-b541-4dad-97b9-5a39c6b01297"
  default_provider              = "AzureActiveDirectory"
  unauthenticated_client_action = "RedirectToLoginPage"

  active_directory {
    client_id     = "aadclientid"
    client_secret = "aadsecret"

    allowed_audiences = [
      "someallowedaudience",
    ]
  }
    
  microsoft {
    client_id     = "microsoftclientid"
    client_secret = "microsoftclientsecret"

    oauth_scopes = [
      "somescope",
    ]
  }
}
```

### References

* #1992
* #2831

**Comment by StefanSchoof** [comment]
I think this was done in #3893 and is in 1.32 version of the plugin.

**Comment by StefanSchoof** [comment]
@katbyte or @joakimhew Do want to close this, where it is done?
