### ISSUE TITLE
Update Azure Postgres Server versions

### ISSUE THREAD

**Issue by rolanddb** [terraform-providers/terraform-provider-azurerm#3327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the `azurerm_postgresql_server` resource supports PG 9.5, .. , 10.2.
However, the latest PG version supported by Azure is 10.7: https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions#postgresql-version-107.

### New or Affected Resource(s)

* azurerm_postgresql_server

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by gkluoe** [comment]
> However, the latest PG version supported by Azure is 10.7

Not only that, but Azure no longer supports 10.2 so it's not possible to create a 10.x server using terraform

**Comment by rolanddb** [comment]
> > However, the latest PG version supported by Azure is 10.7
> 
> Not only that, but Azure no longer supports 10.2 so it's not possible to create a 10.x server using terraform

I've created a 10.0 server last week, so that is still an option.

**Comment by gkluoe** [comment]
> I've created a 10.0 server last week, so that is still an option.

You're right - that does work. Thanks. I was going by this, which doesn't list any versions of 10 < 10.7
https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions

**Comment by rolanddb** [comment]
> Edit to add: I've also just realised that specifying 10.0 actually gives you 10.7:
> 
> `psql (11.2, server 10.7)`

Ha, I didn't notice that! I was looking at the Azure Portal which states `PostgreSQL version 10.0`, but indeed, my database client tells me it is PG 10.7.

At this point I'm not sure what should happen with this ticket. Something strange is happening somewhere between Terraform and Azure..
