### ISSUE TITLE
No way to configure security/ user authorization for an API using Azure API management API resource

### ISSUE THREAD

**Issue by ben5556** [terraform-providers/terraform-provider-azurerm#3341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Trying to create an API using Terraform azurerm_api_management_api resource and realized that there is NO way to configure security/ user authorization for the api.

https://www.terraform.io/docs/providers/azurerm/r/api_management_api.html

See attached screenshot which shows the security option for API in Azure Portal -> API Management services -> APIs -> API settings

![API_user_authorization](https://user-images.githubusercontent.com/39107453/56940181-d5d43f00-6b60-11e9-9d86-2813ab810ab7.PNG)

Without this, we need to manually configure user authorization after creating the API which is not what we prefer. We would like to avoid manual intervention/ configuration as much as possible.

### New or Affected Resource(s)

azurerm_api_management_api

**Comment by Singley** [comment]
This is also a big issue for me- there appears to be no option for setting the User Authorization option on this resource.  For reference, it appears to this option from the [ARM template for APIM](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/apis): 

![image](https://user-images.githubusercontent.com/29473162/67984507-e4291380-fbf4-11e9-921f-ba26d412dd61.png)

(On a side note- but maybe related- when you generate the ARM template from Azure, it also seems to exclude this block - took me a long time to find what I was actually looking for here).


Side note- I've also tried this on Terraform 12.12 - obviously this is more related to the provider, but wanted to add that point.

**Comment by kraihn** [comment]
These settings are also available in the currently used version (2018-01-01, as opposed to 2019-01-01 in the screenshot) of the API, so this should be possible to implement.

https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2018-01-01/service/apis

**Comment by swapnilbjadhav** [comment]
Any update on this fix yet?

**Comment by sirlatrom** [comment]
I'll see if I can add these fields in a PR.

**Comment by nicolasbailly1** [comment]
Hello,

have you any update on this fix?
On each release, I hope this improvement will be delivered :-)
Maybe 2.23.0?

**Comment by sirlatrom** [comment]
> Hello,
> 
> have you any update on this fix?
> On each release, I hope this improvement will be delivered :-)
> Maybe 2.23.0?

@nicolasbailly1 If you go and vote for [this PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7617) by adding your :+1: to the PR top comment itself, it might get attention sooner.
