### ISSUE TITLE
Some Stream Analytics properties shouldn't be required

### ISSUE THREAD

**Issue by r0bnet** [terraform-providers/terraform-provider-azurerm#3342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
AzureRM:  1.26.0

### Affected Resource(s)

* `azurerm_stream_analytics_job`

### Terraform Configuration Files

Sample code from the documentation is sufficient.

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_stream_analytics_job" "example" {
  name                                     = "example-job"
  resource_group_name                      = "${azurerm_resource_group.example.name}"
  location                                 = "${azurerm_resource_group.example.location}"
  compatibility_level                      = "1.1"
  data_locale                              = "en-GB"
  events_late_arrival_max_delay_in_seconds = 60
  events_out_of_order_max_delay_in_seconds = 50
  events_out_of_order_policy               = "Adjust"
  output_error_policy                      = "Drop"
  streaming_units                          = 3

  transformation_query = <<QUERY
    SELECT *
    INTO [YourOutputAlias]
    FROM [YourInputAlias]
QUERY
}
```

### Expected Behavior

I was hoping that properties `compatibility_level`, `data_locale`, `events_late_arrival_max_delay_in_seconds`, `events_out_of_order_max_delay_in_seconds`, `events_out_of_order_policy`, `output_error_policy`, `streaming_units` and `transformation_query` wouldn't be required. When you have a look at the [ARM definition](https://docs.microsoft.com/de-de/azure/templates/microsoft.streamanalytics/2016-03-01/streamingjobs#StreamingJobProperties) or at the [API specs](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/stable/2016-03-01/streamingjobs.json) none of those properties are required. That means that using Terraform forces you to have more strict constraints than ARM templates or the API directly.
In my case we have a different type of deployment when it comes to the transformation query. Our developers / data engineers keep the code for the transformation query in their own repo and deploy it from time to time. If this happens and the query got updated Terraform complains with a `404 Transformation not found` error when doing `terraform plan`. So i only want to create the bare minimum of configuration that's really needed for the job. I think the properties mentioned above shouldn't be mandatory. This wouldn't even be a breaking change since all users of this resource had to set it anyway.

### Actual Behavior

Properties mentioned above are required.

**Comment by nexxai** [comment]
Submitted PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/4190
