### ISSUE TITLE
Feature Request: Azure Batch custom image

### ISSUE THREAD

**Issue by egegunes** [terraform-providers/terraform-provider-azurerm#3352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It's typical to use custom images to create Batch Pools. Create support to use custom images.

### New or Affected Resource(s)

* azurerm_batch_pool

### Potential Terraform Configuration

```hcl
data "azurerm_image" "test" {
  name                = "test"
  resource_group_name = "packerimages"
}

resource "azurerm_batch_pool" "test" {
  name                = "testaccpool"
  resource_group_name = "${azurerm_resource_group.test.name}"
  account_name        = "${azurerm_batch_account.test.name}"
  display_name        = "Test Acc Pool Auto"
  vm_size             = "Standard_A1"
  node_agent_sku_id   = "batch.node.ubuntu 16.04"

  custom_image_reference = "${azurerm_image.test.id}"
}
```

**Comment by jcorioland** [comment]
@tombuildsstuff - Looking at this now
