### ISSUE TITLE
Error importing an app service plan

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#3368]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.11.13
+ provider.azurerm v1.27.1
```
### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl

resource "azurerm_app_service_plan" "win_auea_1" {
  name                = "win-auea-1"
  kind                = "Windows"
  location            = "${local.default_location}"
  resource_group_name = "${data.azurerm_resource_group.infrastructure.name}"

  sku {
    tier = "Standard"
    size = "S1"
  }
}
```
### Expected Behavior

App service plan successfully imported

### Actual Behavior
```
azurerm_app_service_plan.win_auea_1: Importing from ID "/subscriptions/xxx/resourceGroups/infrastructure-rg/providers/Microsoft.Web/serverFarms/win-auea-1"...
azurerm_app_service_plan.win_auea_1: Import complete!
  Imported azurerm_app_service_plan (ID: /subscriptions/xxx/resourceGroups/infrastructure-rg/providers/Microsoft.Web/serverFarms/win-auea-1)

Error: azurerm_app_service_plan.win_auea_1 (import id: /subscriptions/xxx/resourceGroups/infrastructure-rg/providers/Microsoft.Web/serverFarms/win-auea-1): Can't import azurerm_app_service_plan.win_auea_1, would collide with an existing resource.

Please remove or rename this resource before continuing.
```
### Steps to Reproduce

Note that I was changing a data to a resource, Deleting `data.azurerm_app_service_plan.win_auea_1` from the state resolved the problem, but the output is clearly wrong and I'm sure I've done the same change before with no problems.

1. `tf import azurerm_app_service_plan.win_auea_1 /subscriptions/xxx/resourceGroups/infrastructure-rg/providers/Microsoft.Web/serverFarms/win-auea-1`

**Comment by Leon99** [comment]
Looks like that import created an incorrect entry tfstate, see https://github.com/terraform-providers/terraform-provider-azurerm/issues/3369#issuecomment-488942823.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested with below steps, seems I cannot repro this issue anymore. Maybe I missed something. If you want, you can have a try to check whether the issue still exists?

```
Terraform v0.12.28
+ provider.azurerm v1.27.1
```

tf apply:
```
provider "azurerm" {
  version = "1.27.1"
}

resource "azurerm_resource_group" "test" {
  name     = "test-appservice-rg01"
  location = "eastus2"
}

resource "azurerm_app_service_plan" "windows" {
  name                = "acctestASP-windows"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    tier = "Standard"
    size = "S1"
  }

  kind             = "Windows"
}
```

Delete terraform.tfstate

tf import:
```
terraform import azurerm_app_service_plan.windows /subscriptions/xx-xx-xx-xx/resourceGroups/test-appservice-rg01/providers/Microsoft.Web/serverfarms/acctestASP-windows
```

Result:
![image](https://user-images.githubusercontent.com/19754191/87741585-76228c00-c817-11ea-8141-5ed66117efbe.png)

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment but please let us know if that's still an issue on the latest version of the Azure Provider and we'll take another look.

Thanks!
