### ISSUE TITLE
azurerm_key_vault_certificate.ssl: unexpected EOF, panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#3369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.13
+ provider.azurerm v1.27.1
```

### Affected Resource(s)

* `azurerm_key_vault_certificate`

### Panic Output
https://gist.github.com/Leon99/a5af6e5a65c8417c28ad1df6df7a0111

### Actual Behavior

```
Error: Error refreshing state: 2 error(s) occurred:

* azurerm_key_vault_certificate.ssl: 1 error(s) occurred:

* azurerm_key_vault_certificate.ssl: azurerm_key_vault_certificate.ssl: unexpected EOF
* module.win_auea_1_app_service_plan_certificate.data.azurerm_app_service_plan.default: 1 error(s) occurred:

* module.win_auea_1_app_service_plan_certificate.data.azurerm_app_service_plan.default: data.azurerm_app_service_plan.default: unexpected EOF

panic: runtime error: invalid memory address or nil pointer dereference
```

### Steps to Reproduce

1. `tf refresh` or `tf plan` or `tf apply`

### References
The only change that was made since the same config worked described in #3368, although I don't see how it's related.

**Comment by Leon99** [comment]
Looks like it's related to #3368 after all. I noticed that recently imported azurerm_app_service_plan.win_auea_1 doesn't look right in .tfstate, replicated it from another proper azurerm_app_service_plan and the refresh succeeded.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here I believe this has been fixed, since this issue was one of the reasons why we now check for the presence of an existing resource during creation, if your still encountering this on the latest release then please open a new issue with an updated stack trace and we'll take another look.

Thanks!
