### ISSUE TITLE
Issue : actionGroup update fails with StatusCode=500 on existing database alerts

### ISSUE THREAD

**Issue by sasikanthpamuru** [terraform-providers/terraform-provider-azurerm#3370]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.23.0
+ provider.template v2.1.2

### Affected Resource(s)

* `azurerm_monitor_metric_alert`

### Terraform Configuration Files

```
db_namespace="/subscriptions/<subscription-id>/resourceGroups/test-RG/providers/Microsoft.Sql/servers/testdb/databases/test123"

resource "azurerm_monitor_metric_alert" "testcount" {
  name                = "${var.name_prefix}-${var.environment}-test-alert" 
  resource_group_name = "${var.resource_group_name}"
  scopes              = ["${var.db_namespace}"]
  description         = "Action will be triggered when Transactions count is greater than 70."
  criteria {
    metric_namespace = "Microsoft.Sql/servers/databases"
    metric_name      = "cpu_percent"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 70
  }
  action = "${var.action_group_slack}"  
}
```

### Expected Behavior

The new action group entries should have been added successfully.
### Actual Behavior

* module.database.azurerm_monitor_metric_alert.testcount: 1 error(s) occurred:

* azurerm_monitor_metric_alert.testcount: Error creating or updating metric alert "test-alert" (resource group "test-RG"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "The server encountered an internal error, please retry. If the problem persists, contact support." error: invalid character 'T' looking for beginning of value

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sasikanthpamuru** [comment]
This only fails on database alerts , all the other resource metric alerts updates worked fine. Just the database update alerts are failing.

**Comment by tombuildsstuff** [comment]
hi @sasikanthpamuru 

Thanks for opening this issue :)

Taking a look at the error message returned from the API:

> The server encountered an internal error, please retry. If the problem persists, contact support

This appears to be a temporary issue with the Azure API - as such I don't believe there's much we can do around this until the API is fixed - out of interest are you still encountering this issue?

Thanks!

**Comment by sasikanthpamuru** [comment]
Resolved now.
