### ISSUE TITLE
AKS: Enable apiserver authorized IP ranges on azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by landro** [terraform-providers/terraform-provider-azurerm#3371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for limiting access to the management server.
It should be quick to implement. 

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

Add the follwing option to 

```hcl
resource "azurerm_kubernetes_cluster" "default" {

api-server-authorized-ip-ranges = ["172.0.0.10/16", "168.10.0.10/18"]

}
```
The ip range property is exposed like this in the go SDK:

```go 

type ManagedClusterProperties struct {
...
	APIServerAuthorizedIPRanges *[]string `json:"apiServerAuthorizedIPRanges,omitempty"`
}
```

### References

https://github.com/Azure/azure-cli-extensions/tree/master/src/aks-preview#enable-apiserver-authorized-ip-ranges
https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerservice/mgmt/2019-04-30/containerservice/models.go

**Comment by tombuildsstuff** [comment]
hey @landro 

Thanks for opening this issue :)

Just to let you know that support for this functionality is being added by @fraserdarwent in #3262

Thanks!

**Comment by landro** [comment]
Oh man, completely missed that. I’ll close this issue.
