### ISSUE TITLE
App Service Plan update to `reserved = true`

### ISSUE THREAD

**Issue by mbfrahry** [terraform-providers/terraform-provider-azurerm#3379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.0-dev

### Affected Resource(s)

* `azurerm_app_service_plan.test`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "test" {
  name                = "matthewtest"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  kind                = "Linux"


  sku {
    tier = "Standard"
    size = "S1"
  }

}
```

->

```hcl
resource "azurerm_app_service_plan" "test" {
  name                = "matthewtest"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  kind                = "Linux"


  sku {
    tier = "Standard"
    size = "S1"
  }

    reserved = true
}
```

### Expected Behavior

The app service plan should have been updated to reserved true

### Actual Behavior

```
Error: Error creating/updating App Service Plan "appserviceplan" (Resource Group "appserviceplan"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS." Details=[{"Message":"You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"59315","Message":"You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.","MessageTemplate":"You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.","Parameters":[]}}]
```

### Steps to Reproduce

1. `terraform apply` the first config

2. `terrafrom apply` the second config

### References

* #0000

**Comment by r0bnet** [comment]
Did you set Linux after you created the resource? Default `kind` is `Windows`. If you use `Linux` then `reserved` has always to be set to `true`.

![image](https://user-images.githubusercontent.com/13856391/57210863-823d7780-6fde-11e9-8877-41683fa9f476.png)

This can be found in documentation but could also be checked as precondition before creating the service plan.

Btw: the ordering seems kind of weird in the documentation and also there is one or two other mistakes. Will create a PR to fix that.

**Comment by mbfrahry** [comment]
Thanks for the detailed response @r0bnet! This issue looks resolved
