### ISSUE TITLE
Zone resilient property not optional for azurerm_image

### ISSUE THREAD

**Issue by georgespatton** [terraform-providers/terraform-provider-azurerm#3387]
### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
provider.azurerm v1.27.1
provider.random v2.0.0

### Affected Resource(s)

* `azurerm_image.myimage-2`

### Terraform Configuration Files

resource "azurerm_image" "myimage-2" {
  name = "myimage-2"
  location = "${var.mylocation}"
  resource_group_name = "${azurerm_resource_group.myrg.name}"
  source_virtual_machine_id = "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Compute/virtualMachines/myimage-2"
}
### Expected Behavior

The zone resilient property is not optional on an azurerm_image resource.  If It is not defined in 1.24.0+ it will force a new resource and image.  1.23.0 and before did not have this behavior.  Per https://github.com/terraform-providers/terraform-provider-azurerm/pull/3100 this parameter should be optional.  This behavior probably started with 1.24.0, but it is observed in 1.27.1 as well.  

### Actual Behavior

Forced resource recreation.

### Steps to Reproduce

1. Use the following terraform version with the config above:

Terraform v0.11.13
provider.azurerm v1.23.0
provider.random v2.0.0

2. Terraform plan.  This should not force the recreation of the image.

3. Use the following terraform version with the config above:

Terraform v0.11.13
provider.azurerm v1.27.1
provider.random v2.0.0

4. Terraform plan.  This will force the recreation of the image as shown by the terraform plan output here.

-/+ azurerm_image.myimage-2 (new resource required)
      id:                             "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Compute/images/myimage-2" => <computed> (forces new resource)
      location:                       "eastus" => "eastus"
      name:                           "myimage-2" => "myimage-2"
      resource_group_name:            "myrg" => "myrg"
      source_virtual_machine_id:      "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Compute/virtualMachines/myimage-2" => "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Compute/virtualMachines/myimage-2"
      tags.%:                         "3" => <computed>
      zone_resilient:                 "" => "true" (forces new resource)

### Important Factoids

Running in Azure EASTUS.
### References

https://github.com/terraform-providers/terraform-provider-azurerm/pull/3100

**Comment by akonrath** [comment]
Hi @georgespatton , are you still seeing this behavior in the latest version of the provider? I was unable to replicate this from my end.

It was successfully created with the zone_resilient variable set to false, and when checking with the azure cli, the zoneResilient value was set to null, which is identical to what is set when using the azure cli to create an image without setting the zone-resilient flag.

Subsequent plans/applies of an undefined zone_resilient did not force a new resource to be created.

Example resource (in East US, referencing a Generalized VM):
```
resource "azurerm_image" "example" {
  name                      = "acctest"
  location                  = azurerm_resource_group.main.location
  resource_group_name       = azurerm_resource_group.main.name
  source_virtual_machine_id = azurerm_virtual_machine.main.id
}
```

Versions tested:
```
$ terraform --version
Terraform v0.12.24
+ provider.azurerm v2.5.0
```

**Comment by georgespatton** [comment]
No, in a later version of terraform it has been resolved.  Thanks for asking!
