### ISSUE TITLE
Support for non-global API Management policies

### ISSUE THREAD

**Issue by brianpcurran** [terraform-providers/terraform-provider-azurerm#3396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As noted in [this comment](https://github.com/terraform-providers/terraform-provider-azurerm/pull/3151#issuecomment-482728594), support for API Management policies is limited to global policies (set on the `azurerm_api_management` resource). It would be great to have support for policies at the product and operation levels as well (we make heavy use of product-level policies and can't use Terraform for these). I'm opening this issue as requested in [this comment](https://github.com/terraform-providers/terraform-provider-azurerm/pull/3151#issuecomment-482972881) by @tombuildsstuff.

### New or Affected Resource(s)

* azurerm_api_management
* azurerm_api_management_policy
* azurerm_api_management_product_policy
* azurerm_api_management_operation
* azurerm_api_management_operation_policy

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/1177
* https://github.com/terraform-providers/terraform-provider-azurerm/pull/3151

**Comment by tombuildsstuff** [comment]
hey @brianpcurran 

Thanks for opening this issue :)

Taking a look into this it appears we've recently added support for `azurerm_api_management_api_operation_policy`, `azurerm_api_management_api_policy` and `azurerm_api_management_product_policy` but they've not made it into a release yet (but will soon) - out of interest will these cover your use-cases?

Thanks!

**Comment by brianpcurran** [comment]
@tombuildsstuff Awesome! We use per-operation policies and per-API policies, so I think we should be covered by those resources.

**Comment by tombuildsstuff** [comment]
@brianpcurran cool, thanks for confirming that - since this should be fixed by the next release I'm going to close this issue for the moment.

Thanks!

**Comment by brianpcurran** [comment]
@tombuildsstuff Is there a rough ETA on 1.28 (I know this might be an annoying question...)? We're needing a solution for the per-operation policies in particular pretty soon, and I'm hoping to use Terraform instead of spending a bunch of time on ARM templates or another solution.
