### ISSUE TITLE
Please add public_ip_address capability to azurerm_virtual_machine_scale_set

### ISSUE THREAD

**Issue by samirageb** [terraform-providers/terraform-provider-azurerm#340]
According to this [blog post](https://azure.microsoft.com/en-us/blog/new-networking-features-in-azure-scale-sets/) Azure scale sets can now get IPv4 addresses assigned directly to the VM. For our particular workload, this would help us tremendously. 

### Terraform Version
Terrraform 0.10.5
AzureRM TF Provider 0.2.0

### Affected Resource(s)
- azurerm_virtual_machine_scale_set

**Comment by tombuildsstuff** [comment]
Hey @samirageb 

Thanks for opening this issue :)

From what I can see this functionality requires the new API version - [which is requested in this issue](https://github.com/Azure/azure-sdk-for-go/issues/744) - and should be available to us once [the v11 SDK](https://github.com/Azure/azure-sdk-for-go/pull/768) has been merged :)

Thanks!

**Comment by katbyte** [comment]
I believe this was fixed by #448 as can be seen https://github.com/terraform-providers/terraform-provider-azurerm/pull/448/files#diff-35d6282e7fd373522705ded934097ca0R298
