### ISSUE TITLE
Dependency issue with resource groups and modules

### ISSUE THREAD

**Issue by SirWayne** [terraform-providers/terraform-provider-azurerm#3403]
Hello,

iam using a own module with terraform. After upgrade to azure provider version 1.27.1 (before 1.24.0) i have dependencies issue when i setup a subscription.

The main.tf looks like:
```
resource "azurerm_resource_group" "DatabaseResourceGroup" {
  name     = "${var.db_resource_group_name}"
  location = "${var.location}"
}

module "sql_server" {
  source                       = "..."
  resource_group_name          = "${azurerm_resource_group.DatabaseResourceGroup.name}"
...
}
```

In the module `sql_server` iam using the `data` which is now not working
```
data "azurerm_resource_group" "ResourceGroup" {
  name = "${var.resource_group_name}"
}

resource "azurerm_sql_server" "SqlServer" {
  name                         = "${var.name}"
  resource_group_name          = "${data.azurerm_resource_group.ResourceGroup.name}"
  location                     = "${var.location}"
  version                      = "${var.version}"
  administrator_login          = "${var.administrator_login}"
  administrator_login_password = "${var.administrator_login_password}"
}
```

The error is
```
* module.sql_server.data.azurerm_resource_group.ResourceGroup: 1 error(s) occurred:

* module.sql_server.data.azurerm_resource_group.ResourceGroup: data.azurerm_resource_group.ResourceGroup: Error: Resource Group "my-database-rg" was not found
```

Does anyone know the mistake?

**Comment by jackspyder** [comment]
@SirWayne did you ever resolve this issue? I'm finding exactly the same thing!

**Comment by SirWayne** [comment]
We solved the problem with 2 options. I am not sure which one fixed the problem:
1. We upgrade to terraform 0.12.x
2. We use instead of data directly the `"${var.resource_group_name}"`

**Comment by dantheman999301** [comment]
Also having this issue, specifically with Resource Groups and ARM templates. Resource group definitely exists.

**Comment by MichaelMeelisRTL** [comment]
I'm having the same issue as well. Changing it to the var seems a bit of a work around. I'm curious what is going on here. I'm not ready yet to upgrade to 0.12 so I will use that work around. I guess it's a dependency issue.

**Comment by szymon3** [comment]
I'm still having this error with:
```
Terraform v0.12.19
+ provider.azurerm v1.41.0
```

**Comment by BarnumD** [comment]
Seeing this with 0.12.24 and azurerm 2.4.0.
Creating a resource group and calling a module including the resource group name.

**Comment by tombuildsstuff** [comment]
👋 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through this appears to be an issue with Terraform Core, rather than something specific to this Provider; since the dependency for the Data Source shouldn't be being resolved until the Resource has finished provisioning (which is where this error is coming from). As such would you mind re-opening this issue on [the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone from the Terraform Core Team should be able to take a look?

Thanks!
