### ISSUE TITLE
Add enableTcpReset parameter for Standard Load Balancer rules and nat rules

### ISSUE THREAD

**Issue by serbrech** [terraform-providers/terraform-provider-azurerm#3404]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Standard LB introduces support for [TCP Reset](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset)

The outbound rule already exposes the functionality : [enable_tcp_reset](https://www.terraform.io/docs/providers/azurerm/r/loadbalancer_outbound_rule.html#enable_tcp_reset)
 
However it's missing from [loadbalancer rule](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_loadbalancer_rule.go) and [loadbalancer nat rule](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_loadbalancer_nat_rule.go)

### New or Affected Resource(s)

* `azurerm_lb_nat_rule`
* `azurerm_lb_rule`

### Potential Terraform Configuration

see https://github.com/terraform-providers/terraform-provider-azurerm/blob/54ce52395ce71bcde2e0e983e06061159faea106/azurerm/resource_arm_loadbalancer_outbound_rule.go#L79-L83

### Note 
Outbound rules is for `Standard` sku only so `enableTcpReset` is always allowed as a parameter.
For `lb_rule` and `nat_rule`, it needs to validate that the lb sku is `Standard`.

**Comment by ernstae** [comment]
This resource appears to be available rather generally in both Commercial and Government clouds.  Any ETA on availability in the AzureRM provider?
