### ISSUE TITLE
Please add ability to link NSGs to azurerm_virtual_machine_scale_set

### ISSUE THREAD

**Issue by samirageb** [terraform-providers/terraform-provider-azurerm#341]
According to this  [blog post](https://azure.microsoft.com/en-us/blog/new-networking-features-in-azure-scale-sets/) Azure scale sets can now get NSGs addresses assigned directly to the set. For our particular workload, this would help us tremendously.

Terraform Version

Terrraform 0.10.5
AzureRM TF Provider 0.2.0

Affected Resource(s)
- azurerm_virtual_machine_scale_set

**Comment by tombuildsstuff** [comment]
Hey @samirageb 

Thanks for opening this issue :)

From what I can see this functionality requires the new API version - [which is requested in this issue](https://github.com/Azure/azure-sdk-for-go/issues/744) - and should be available to us once [the v11 of the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go/pull/768) has been merged :)

Thanks!

**Comment by rcarun** [comment]
Hi @samirageb 
Could you please confirm if this issue is now fixed as the new API version is available and the new SDK has been merged? @tombuildsstuff (please confirm)

Thanks,
Arun

**Comment by tombuildsstuff** [comment]
hey @samirageb 

Thanks for opening this issue - apologies for the delayed response here!

Support for this was added in #448 which was released in `v0.3.1` of the AzureRM Provider - since this functionality has been added I'm going to close this issue; but would you be able to take a look?

Thanks!
