### ISSUE TITLE
Multiple azurerm_key_vault_access_policy with count overwrites previous apply

### ISSUE THREAD

**Issue by fl-max** [terraform-providers/terraform-provider-azurerm#3418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -v
Terraform v0.11.11
+ provider.azurerm v1.27.1
+ provider.tls v2.0.1

### Affected Resource(s)

* `azurerm_key_vault_access_policy`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "eastus2"
}

resource "azurerm_key_vault" "kafka_admin" {
  name                        = "test"
  location                    = "${azurerm_resource_group.test.location}"
  resource_group_name         = "${azurerm_resource_group.test.name}"
  tenant_id                   = "${var.tenant_id}"

  enabled_for_disk_encryption = false
  enabled_for_template_deployment = false
  sku {
    name = "standard"
  }
}

resource "azurerm_key_vault_access_policy" "admin" {
  count        = "${length(var.keyvault_admins)}"
  key_vault_id = "${azurerm_key_vault.test.id}"
  tenant_id    = "${var.tenant_id}"

  object_id = "${element(var.keyvault_admins, count.index)}"

  certificate_permissions = [
    "create",
    "delete",
    "deleteissuers",
    "get",
    "getissuers",
    "import",
    "list",
    "listissuers",
    "managecontacts",
    "manageissuers",
    "setissuers",
    "update",
  ]

  key_permissions = [
    "backup",
    "create",
    "decrypt",
    "delete",
    "encrypt",
    "get",
    "import",
    "list",
    "purge",
    "recover",
    "restore",
    "sign",
    "unwrapKey",
    "update",
    "verify",
    "wrapKey",
  ]

  secret_permissions = [
    "backup",
    "delete",
    "get",
    "list",
    "purge",
    "recover",
    "restore",
    "set",
  ]
}

resource "azurerm_key_vault_access_policy" "reader" {
  depends_on = [ "azurerm_key_vault_access_policy.admin" ]
  count        = "${length(var.keyvault_readers)}"
  key_vault_id = "${azurerm_key_vault.test.id}"
  tenant_id    = "${var.tenant_id}"

  object_id = "${element(var.keyvault_readers, count.index)}"

  certificate_permissions = [
    "get",
    "getissuers",
    "list",
    "listissuers",
  ]

  key_permissions = [
    "decrypt",
    "get",
    "list",
    "unwrapKey",
    "verify",
  ]

  secret_permissions = [
    "get",
    "list",
  ]
}
```

### Expected Behavior

If given 2 object_ids in the list ```var.keyvault_admins``` and 1 in ```var.keyvault_readers```, I would expect 3 Access Policies.

### Actual Behavior

First run: 1 access policy (azurerm_key_vault_access_policy.readers overwrites azurerm_key_vault_access_policy.admins)
Second run: 2 access policies (azurerm_key_vault_access_policy.admin overwrites azurerm_key_vault_access_policy.readers)

### Steps to Reproduce

1. `terraform apply`
Observe readers overwrite admins
2. `terraform apply`
Observe admins overwrite readers

**Comment by szaher** [comment]
Is that solved yet ?

**Comment by tombuildsstuff** [comment]
hey @fl-max

Thanks for opening this issue.

This behaviour exists due to a bug in Terraform Core when using `count` - we instead recommend using `for_each` instead when the ordering doesn't matter (such as in this instance), [more information can be found here](https://www.terraform.io/docs/configuration/resources.html#when-to-use-for_each-instead-of-count) - would you be able to take a look and see if that works for you?

Since this should be resolved by switching to `for_each` (which it's worth noting requires Terraform 0.12) I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look.

Thanks!
