### ISSUE TITLE
Feature Request: Provider-Level "Global" Tags

### ISSUE THREAD

**Issue by JustinGrote** [terraform-providers/terraform-provider-azurerm#3420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Implement https://github.com/hashicorp/terraform/issues/2283#issuecomment-452062056 to enable global tags to be defined for a terraform configuration. I'd like to be able to tag that a resource was deployed with terraform, and where it was deployed from, without having to specify tag blocks on every single resource.

Tags specified in the provider block should merge with ones specified in resource blocks, with resource block tags overriding what is specified globally.

### New or Affected Resource(s)

* azurerm provider

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  global_tags = {
    terraform = "true"
    terraform_version = "11.1"
    terraform_statefilepath = "https://..../terraform.tfstate"
  }
}
```

### References

* https://github.com/hashicorp/terraform/issues/2283#issuecomment-452062056

**Comment by tombuildsstuff** [comment]
hey @JustinGrote

Thanks for opening this issue :)

Taking a look into this, whilst I can see the potential use-case for this unfortunately not all resources in Azure use a Dictionary/Key-Value Pair as Tags - some resources instead use an array of strings (e.g. `["foo", "bar"]`. Whilst it could be possible to work around this, for example by using `Key=Value` for the items requiring a list of strings, unfortunately that's not going to work for everybody. As such whilst I can see the benefit to this idea, unfortunately I don't believe this approach would work in the Azure Provider at this time and as such I'm going to close this feature request for the moment.

Thanks!
