### ISSUE TITLE
Add Redis Cache data source

### ISSUE THREAD

**Issue by J00MZ** [terraform-providers/terraform-provider-azurerm#3432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add new data resource for Azure Redis Cache service

### New Data Resource

* azurerm_redis_cache

### Example HCL code
```hcl
data "azurerm_redis_cache" "test" {
  name                = "example-cache"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
}
```

**Comment by Zenocolo** [comment]
Having a look at this.
