### ISSUE TITLE
Eventhub partition count currently cannot be one when namespace has kafka enabled

### ISSUE THREAD

**Issue by BBeauchemin** [terraform-providers/terraform-provider-azurerm#3433]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.13

### Affected Resource(s)

* `azurerm_eventhub `

see also: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_eventhub.go#L269

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "namespace" {
  name                = "the-namespace"
  location            = "East US"
  resource_group_name = "<YOUR_RESOURCE_GROUP_NAME>"
  sku                 = "Standard"
  capacity            = "1"
  kafka_enabled       = "true"
}

resource "azurerm_eventhub" "eventhub_topic" {
  name                = "named-for-one-partition"
  namespace_name      = "${azurerm_eventhub_namespace.namespace.name}"
  resource_group_name = "<YOUR_RESOURCE_GROUP_NAME>"
  partition_count     = "1"
  message_retention   = "7"
}

```

### Debug Output

` Error: azurerm_eventhub.eventhub_topic: EventHub Partition Count has to be between 2 and 32 ` 

### Expected Behavior

In Azure portal, when the eventhub namespace is kafka enabled, eventhub created in it can have the partition_count set to one (which is the default value in the UI)

### Actual Behavior

The limitation of an eventhub namespace that is not kafka enabled is applyed, which is a minium partition count value to 2

### Steps to Reproduce

0. Get the azurem config defined previously and set your ressource_group_name
1. `terraform plan`

**Comment by prasadker** [comment]
@jeffreyCline Please look into this issue.
