### ISSUE TITLE
azurerm_user_assigned_identity tags keyName change

### ISSUE THREAD

**Issue by ranokarno** [terraform-providers/terraform-provider-azurerm#3443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.10
azurerm v1.21

### Affected Resource(s)

* `azurerm_user_assigned_identity`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "acceptanceTestResourceGroup1"
  location = "southeastasia"
  tags = {
    KeyName1 = "tag_value1"
    KeyName2 = "tag_value2"
    KeyName3 = "tag_value3"
    KeyName4 = "tag_value4"
    KeyName5 = "tag_value5"
  }
}

resource "azurerm_user_assigned_identity" "testidentity" {
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  name = "test-manage-identity"

  tags = {
    KeyName1 = "tag_value1"
    KeyName2 = "tag_value2"
    KeyName3 = "tag_value3"
    KeyName4 = "tag_value4"
    KeyName5 = "tag_value5"
  }
}
```

### Expected Behavior

* tags `KeyName` should not be changed and consistenst across multiple deployment

### Actual Behavior

* during terraform `apply`, tag keyname was converted into cammelCase 
* e.g. tags **K**eyName1 --> tags **k**eyName1

```hcl
Terraform will perform the following actions:

~ module.eventhub.azurerm_user_assigned_identity.testidentity
      tags.KeyName1:           "" => "tag_value1"
      tags.KeyName2:           "" => "tag_value2"
      tags.KeyName3:           "" => "tag_value3"
      tags.KeyName4:           "" => "tag_value4"
      tags.KeyName5:           "" => "tag_value5"
      tags.keyName1:           "tag_value1" => ""     <-- KeyName1 changed to keyName1
      tags.keyName2:           "tag_value2" => ""
      tags.keyName3:           "tag_value3" => ""
      tags.keyName4:           "tag_value4" => ""
      tags.keyName5:           "tag_value5" => ""
```

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`

**Comment by neil-yechenwei** [comment]
@ranokarno, thanks for opening this issue. Seems this service API issue has been fixed from service side since I cannot repro it anymore with below tfconfig. If it's possible, could you help to double check whether the issue still exists?
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-uai-test"
  location = "eastus"
}

resource "azurerm_user_assigned_identity" "test" {
  name                = "acctest-uai02"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  tags = {
    FooTest = "BarTest"
	envGo = "testGo"
	nameusing = "neiltest"
	KeyName1 = "tag_value1"
  }
}

output "tags" {
  value = azurerm_user_assigned_identity.test.tags
}
```

**Comment by tombuildsstuff** [comment]
@neil-yechenwei just to confirm: did you change the casing on the Keys when updating the Tags? A one-time apply won't take affect here (and works as expected)

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , yes, for the scenario of updating the tags, I tried before and it works as expected.

**Comment by tombuildsstuff** [comment]
@neil-yechenwei changing the values will ensure the tags are updated - there's a bug in some ARM API's where changing the casing on the keys of tags (but not changing the value) doesn't update the value of the keys in the tags - so I think this wants confirming without updating the values of the tags (but only the keys) to confirm that this is an API bug

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , I can repro it now while changing `AeyName1 = "tag_value1"` to `aeyName1 = "tag_value1"`. After do more investigation, I found although Azure portal displays `AeyName1 = "tag_value1"` after updated tags, but "User Assigned Identities - Get API" returns `aeyName1 = "tag_value1"` and there is diff on terraform side. So I think it's just Azure portal issue not api issue.

Tags on Azure Portal:
![image](https://user-images.githubusercontent.com/19754191/89882865-fb704500-dbf9-11ea-9a29-b129c6bd6c4e.png)

Tags in api response:
```
{
  "id": "/subscriptions/xx-xx-xx-xx/resourcegroups/acctestRG-uai-test/providers/Microsoft.ManagedIdentity/userAssignedIdentities/acctest-uai02",
  "name": "acctest-uai02",
  "type": "Microsoft.ManagedIdentity/userAssignedIdentities",
  "location": "eastus",
  "tags": {
    "aeyName1": "tag_value1"
  },
  "properties": {
    "tenantId": "xxxx",
    "principalId": "xxxx",
    "clientId": "xxxxx"
  }
}
```
![image](https://user-images.githubusercontent.com/19754191/89883502-cd3f3500-dbfa-11ea-9a3d-c66107fd2cbb.png)

**Comment by tombuildsstuff** [comment]
Closing this out since this appears to be resolved - but please let us know if you're still experiencing this issue and we'll take another look.
