### ISSUE TITLE
Grant the Azure Data Factory managed identity access to Azure Key Vault

### ISSUE THREAD

**Issue by eXXL** [terraform-providers/terraform-provider-azurerm#3454]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to use Data Factory in combination with Key Vault and Data Lake Gen 2.
I have to create an access policy in Key Vault for the Data Factory's system assigned identity.
Currently this is not possible with Terraform.

A solution approach might be:

The Terraform resource "azurerm_data_factory"returns the "Managed Identity Application ID" so it can be referenced by the Terraform resource "azurerm_key_vault".

### New or Affected Resource(s)

* azurerm_data_factory
* azurerm_key_vault

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* Store credential in Key Vault:
https://docs.microsoft.com/en-us/azure/data-factory/store-credentials-in-key-vault

* Retrieve managed identity from Data Factory:
https://docs.microsoft.com/en-us/azure/data-factory/data-factory-service-identity#retrieve-managed-identity

**Comment by eXXL** [comment]
The same approach might be useful for accessing the data lake from the data factory.

See block "Managed identities for Azure resources authentication":
https://docs.microsoft.com/en-us/azure/data-factory/connector-azure-data-lake-store#linked-service-properties

**Comment by tombuildsstuff** [comment]
hi @eXXL 

Thanks for opening this issue :)

Taking a look into this, it appears we do export these properties but they're missing from the documentation; you should be able to access these as: `azurerm_data_factory.foo.identity.0.principal_id` and `azurerm_data_factory.foo.identity.0.tenant_id`.

I'll open a PR shortly which updates the documentation to export these fields - but would you be able to take a look and see if that works for you?

Thanks!

**Comment by eXXL** [comment]
Hi @tombuildsstuff,
I just had time to refactor my code and wanted to let you know that it worked fine!
Thanks, keep up the great work!
