### ISSUE TITLE
[azurerm] Provider doesn't support resource: azurerm_key_vault_secret

### ISSUE THREAD

**Issue by ncmpuolitaival** [terraform-providers/terraform-provider-azurerm#346]
Hi,

Trying to define Azure KeyVault secret gives an 'Provider doesn't support resource' error. Tested with custom code as well as the given example.

### Terraform Version
Terraform v0.10.5

### Affected Resource(s)
- Azure Key Vault secret

### Terraform Configuration Files
```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "my-resource-group"
  location = "West US"
}

resource "azurerm_key_vault" "test" {
  name                = "my-key-vault"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  tenant_id           = "${data.azurerm_client_config.current.tenant_id}"

  sku {
    name = "premium"
  }

  access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${data.azurerm_client_config.current.service_principal_object_id}"

    key_permissions = [
      "all",
    ]

    secret_permissions = [
      "all",
    ]
  }

  tags {
    environment = "Production"
  }
}

resource "azurerm_key_vault_secret" "test" {
  name      = "secret-sauce"
  value     = "szechuan"
  vault_uri = "${azurerm_key_vault.test.vault_uri}"

  tags {
    environment = "Production"
  }
}
```

### Expected Behavior
New secret added to Azure Key Vault

### Actual Behavior
Provider doesn't support resource: azurerm_key_vault_secret error

### Steps to Reproduce
1. Copy the example from https://www.terraform.io/docs/providers/azurerm/r/key_vault_secret.html
2. Run **terraform plan**

**Comment by tombuildsstuff** [comment]
Hey @ncmpuolitaival

Thanks for opening this issue :)

Would it be possible version of the AzureRM Provider are you running (this is separate from the Terraform version)? You can find this out by running `terraform providers` which will output the versions used:

```
$ terraform providers
.
└── provider.azurerm 0.2.0
```

The latest is `0.2.0`, which can be set via:

```
provider "azurerm" {
  version = "0.2.0"
}
```

Thanks!

**Comment by ncmpuolitaival** [comment]
Yes, it seems that I'm running an old provider version. After updating the provider it started to work.

Noob mistake, please close this issue. :)

**Comment by tombuildsstuff** [comment]
@ncmpuolitaival no worries - glad to hear it's working for you :)
