### ISSUE TITLE
azurerm_key_vault doesn't allow "all" permission

### ISSUE THREAD

**Issue by andyt530** [terraform-providers/terraform-provider-azurerm#3469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform --version
Terraform v0.11.14

 provider "azurerm" (1.28.0)...

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource azurerm_key_vault rg-dsvms__prodd46772529 {
  name                = "prod46772529"
  location            = "uksouth"
  resource_group_name = "rg-dsvms"

  sku {
    name = "standard"
  }

  tenant_id              = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  enabled_for_deployment = "True"

  access_policy {
    tenant_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    object_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

    secret_permissions = [
      "all",
    ]
    key_permissions = [
      "all",
    ]
    certificate_permissions = [
      "all",
    ]

  }

  tags {
    "commissionedDate"          = ""
    "environmentIdentifier"     = "prod"
    "CreatedBy"                 = "Eng"
    "department"                = "DA-DSC"
    "environmentVersion"        = "1.0"
    "serviceOwner"              = ""
  }
}
```

### Expected Behavior

The "all" permission is valid for secret, keys and certificates

### Actual Behavior

Error: azurerm_key_vault.rg-dsvms__prodd46772529: expected access_policy.0.certificate_permissions.0 to be one of [backup create delete deleteissuers get getissuers import list listissuers managecontacts manageissuers purge recover restore setissuers update], got all

Error: azurerm_key_vault.rg-dsvms__prodd46772529: expected access_policy.0.key_permissions.0 to be one of [backup create decrypt delete encrypt get import list purge recover restore sign unwrapKey update verify wrapKey], got all

Error: azurerm_key_vault.rg-dsvms__prodd46772529: expected access_policy.0.secret_permissions.0 to be one of [backup delete get list purge recover restore set], got all

### Steps to Reproduce

1. `terraform plan .`

### Important Factoids

The "all permission can be seen in the output from the azure cli command:

az keyvault show -n prodd46772529

az2tf:az2tfpy AndyT$ az keyvault show -n prodd46772529
{
  "id": "/subscriptions//resourceGroups/rg-dsvms/providers/Microsoft.KeyVault/vaults/prodd46772529",
  "location": "uksouth",
  "name": "prodd46772529",
  "properties": {
    "accessPolicies": [
      {
        "applicationId": null,
        "objectId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "permissions": {
          "certificates": null,
          "keys": null,
          "secrets": [
            **"all"**
          ],

### References

* #0000

**Comment by andyt530** [comment]
Need t check if "all" is still a valid permission - it used to be.

**Comment by tombuildsstuff** [comment]
@andyt530 "all" was a valid permission at one point in time, but was deprecated in favour of listing all of the required permissions instead - as such we disallow this value at this time (since the API now returns an error).

Thanks!
