### ISSUE TITLE
[azurerm_v0.2.0] azurerm remote state seems to be broken

### ISSUE THREAD

**Issue by donestefan** [terraform-providers/terraform-provider-azurerm#347]
### Terraform Version
Terraform v0.10.3
terraform-provider-azurerm_v0.2.0

### Affected Resource(s)
remote state / backend

### Terraform Configuration Files
```hcl
provider "azurerm" {
        subscription_id = "some-subscription-id"
        ...
}

#define an existing azurerm storage we can use for storing the remote state
terraform {
  backend "azurerm" {
    storage_account_name  = "some"
    container_name        = "some"
    access_key            = "some-access-key"
    key                   = "terraform storage"
  }
}

resource "azurerm_resource_group" "test-rg" {
        name            = "remote-state-test-rg"
        location        = "westeurope"
}
```

### Debug Output
```
$ terraform apply

azurerm_resource_group.test-rg: Creating...
  location: "" => "westeurope"
  name:     "" => "remote-state-test-rg"
  tags.%:   "" => "<computed>"
azurerm_resource_group.test-rg: Creation complete after 0s (ID: ...)


Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Error releasing the state lock!

Error message: failed to retrieve lock info: blob metadata terraformlockid was empty

Terraform acquires a lock when accessing your state to prevent others
running Terraform to potentially modify the state at the same time. An
error occurred while releasing this lock. This could mean that the lock
did or did not release properly. If the lock didn't release properly,
Terraform may not be able to run future commands since it'll appear as if
the lock is held.

In this scenario, please call the "force-unlock" command to unlock the
state manually. This is a very dangerous operation since if it is done
erroneously it could result in two people modifying state at the same time.
Only call this command if you're certain that the unlock above failed and
that no one else is holding a lock.

1 error(s) occurred:

* Error releasing the state lock. Please see the longer error message above.
```

### Expected Behavior
- the remote state should be written to the backend after the resources are created
- the state file lock should be released successfully afterwards

### Actual Behavior
- resources will be created but the state file locking is messed up.
- this makes re-using the remote-state data is impossible.
- there is no way to use `terraform force-unlock LOCK_ID` since the error message does not contain a lock-id

### Steps to Reproduce
create a resource using a Config Files like above
"terraform init" works fine:
```
Initializing the backend...
Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

```
"terraform plan" works fine
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
...
  + azurerm_resource_group.test-rg
      location: "westeurope"
      name:     "remote-state-test-rg"
      tags.%:   "<computed>"
```
`terraform apply` creates the resources, but the remote state will be "damaged" (see error message written in "Debug Output" Section above)

**Comment by tombuildsstuff** [comment]
Hey @donestefan 

Thanks for opening this issue :)

Terraform's Remote State is distributed as a part of [Terraform Core](https://github.com/hashicorp/terraform) - rather than part of the separate provider; and this bug has been fixed in Terraform v0.10.4 - would you be able to upgrade to a newer version of Terraform (v0.10.5 is the latest at the time of writing) and try again? I'm going to close this issue in the interim since this appears to be fixed :)

Thanks!
