### ISSUE TITLE
Terraform does not update the number of nodes in a cluster if the agent pool profile node count is changed

### ISSUE THREAD

**Issue by kbrady-wooliesx** [terraform-providers/terraform-provider-azurerm#3478]
### Terraform (and AzureRM Provider) Version
Terraform v0.11.14

### Affected Resource(s)

* azurerm_kubernetes_cluster -> agent_pool_profile

### Terraform Configuration Files

```hcl
  agent_pool_profile {
    name            = "agentpool"
    count           = "${data.external.aks_cluster.result.node_count}"
    vm_size         = "${lookup(var.agent_pool_profile,"vm_size")}"
    os_type         = "${lookup(var.agent_pool_profile,"os_type")}"
    os_disk_size_gb = "${lookup(var.agent_pool_profile, "os_disk_size_gb")}"

    # Required for advanced networking
    vnet_subnet_id = "/subscriptions/${var.subscription_id}/resourceGroups/${var.vnet_subnet_resource_group_name}/providers/Microsoft.Network/virtualNetworks/${var.vnet_name}/subnets/${var.subnet_name}"

    max_pods = "${var.max_pods}"
  }
```

### Expected Behavior

The node count in the pool used by the AKS cluster is changed

### Actual Behavior

Node pool count does not change

### Steps to Reproduce

1. Create cluster using `terraform apply`
2. Update node count in `agent_pool_profile`
3. `terraform apply`

### Important Factoids

Running in Australia East

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by katbyte** [comment]
Hi @kbrady-wooliesx,

Looks like this was closed by #3491 and as such i am going to close this 🙂
