### ISSUE TITLE
Feature Request: Site Recovery - Replication

### ISSUE THREAD

**Issue by LuisLRodriguez** [terraform-providers/terraform-provider-azurerm#3480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add AzureRM Resource Site Recovery replication functionality

### New or Affected Resource(s)

* azurerm_site_recovery_replication

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://docs.microsoft.com/en-us/rest/api/site-recovery/
https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-quickstart

**Comment by dedamico** [comment]
FYI, (in discussing this with Luis) we both concluded that site recovery 'backups' are currently supported with the Azure Terraform resources (recovery_services_protected_vm, etc.) however replication is not.  This feature request is to track adding replication.  The proposed resource name is just a suggestion and we understand several resources/changes may need to be made.
