### ISSUE TITLE
Missing documentation on Terraform main website for azurerm_sql_database

### ISSUE THREAD

**Issue by simonlegeek** [terraform-providers/terraform-provider-azurerm#3492]
Hi,

Terraform main documentation website doesn't state the valid values for the parameter `create_mode` for the resource `azurerm_sql_database`. 

It says `(Optional) Specifies the type of database to create. Defaults to Default. See below for the accepted values/` 

But nowhere in the document it defines the accepted values. 

Source: https://www.terraform.io/docs/providers/azurerm/r/sql_database.html

**Comment by katbyte** [comment]
Hi @simonlegeek,

Thank you for opening this issue. Looks like the values are there now 🙂 As such i am going to close this.
