### ISSUE TITLE
Support AKS node pools

### ISSUE THREAD

**Issue by kim0** [terraform-providers/terraform-provider-azurerm#3493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS support for multiple node pools is now available in preview => https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#add-a-node-pool

Also, the API docs no longer mention that only one "agent pool profile" can be sent in the API.
https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#examples

### New or Affected Resource(s)

* `agent_pool_profile`

**Comment by katbyte** [comment]
Hi @kim0,

Looks like this was closed by #3491 and as such i am going to close this 🙂
