### ISSUE TITLE
azurerm_public_ip cannot be destroyed because it is still attached to network interface

### ISSUE THREAD

**Issue by TheLinuxNinja** [terraform-providers/terraform-provider-azurerm#350]
### Terraform Version
0.10.6

### Affected Resource(s)
azurerm_public_ip

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "azurerm_public_ip" "bastion-ip" {
  name                         = "bastion-ip-${var.environment}-${var.region}"
  location                     = "${var.region_description}"
  resource_group_name          = "${azurerm_resource_group.ops-mgmt-rg.name}"
  public_ip_address_allocation = "static"
}

resource "azurerm_network_interface" "bastion-nic" {
  name                = "bastion-nic-${var.environment}-${var.region}"
  location            = "${var.region_description}"
  resource_group_name = "${azurerm_resource_group.ops-mgmt-rg.name}"

  ip_configuration {
    name                          = "bastion-${var.environment}-${var.region}"
    subnet_id                     = "${azurerm_subnet.opsnet1.id}"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id          = "${azurerm_public_ip.bastion-ip.id}"
  }
}
```

### Debug Output
https://gist.github.com/TheLinuxNinja/3e62af20d5a59a33998d484e3df769e7

### Panic Output
n/a

### Expected Behavior
public_ip should have been properly re-created by removing it from the nic before attempting to re-create, then re-attaching to the nic afterwards.

### Actual Behavior
azure produced an error that the public_ip cannot be deleted because it is still attached to the nic.

### Steps to Reproduce
use the resources to create a nic and attached public_ip. change the 'name:' of the public_ip. (I added '-${var.environment}-${var.region}' to the name)
terraform apply

### Important Factoids
n/a

### References
I found none.

**Comment by achandmsft** [comment]
This is the same issue as #98 where VM connected to a NIC cannot be destroyed, while here it is IP connected to a NIC. Closing this in favor of the older bug above.
