### ISSUE TITLE
Typo in error message for load balancer rule

### ISSUE THREAD

**Issue by CamelCaseNotation** [terraform-providers/terraform-provider-azurerm#3503]
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_loadbalancer_rule.go#L138

Saw the error message `Error Exanding Load Balancer Rule:`, I'm guessing it's supposed to be "Expanding"

**Comment by brijrajsingh** [comment]
Working on this

**Comment by brijrajsingh** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/pull/3536 made a PR #3536

**Comment by tombuildsstuff** [comment]
Thanks for the PR / fixing this @brijrajsingh :)
