### ISSUE TITLE
Is there support for creating collections and containers for Cosmos Global Document DB ?

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3506]
As above.

**Comment by katbyte** [comment]
Hi @cdesewell, there is! it was just released in [v1.28](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1280-may-17-2019)

**Comment by mikhailshilkov** [comment]
@katbyte so what's the resource name for a SQL Collection?

**Comment by ryancrawcour** [comment]
I see there's a resource for SQL Database https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_sql_database.html but i don't see anything for Collections within that Database.

**Comment by cdesewell** [comment]
Same @ryancrawcour how would I create a collection ?

**Comment by ryancrawcour** [comment]
I don't believe you can create a SQL API collection, only a Mongo API collection, which is not what we want to do.

**Comment by piizei** [comment]
Please add creation of the  SQL Collection, should be pretty straight forward as it is very similar to Mongo.

**Comment by katbyte** [comment]
This was added in #3871 and released in `v1.33` of the provider! as such i am closing it.
