### ISSUE TITLE
data.terraform_remote_state does not recognize backend = "azurerm"

### ISSUE THREAD

**Issue by TheLinuxNinja** [terraform-providers/terraform-provider-azurerm#351]
### Terraform Version
0.10.6

### Affected Resource(s)
data.terraform_remote_state

### Terraform Configuration Files
```hcl
terraform {
  backend "azurerm" {
    storage_account_name = "xxxxx"
    container_name       = "xxxxx"
    environment          = "public"
    resource_group_name  = "xxxxx"
    key                  = "dev-eastus.terraform.tfstate"
  }
}

data "terraform_remote_state" "dev-eastus" {
  backend = "azurerm"

  config {
    storage_account_name = "xxxxx"
    container_name       = "xxxxx"
    environment          = "public"
    resource_group_name  = "xxxxx"
    key                  = "dev-eastus.terraform.tfstate"
  }
}
```

### Debug Output
no gist required:

Error refreshing state: 1 error(s) occurred:

* data.terraform_remote_state.dev-eastus: 1 error(s) occurred:

* data.terraform_remote_state.dev-eastus: data.terraform_remote_state.dev-eastus: Unknown backend type: azurerm

can provide full DEBUG upon request if needed. this seems unnecessary.

### Panic Output
n/a

### Expected Behavior
terraform plan should complete successfully

### Actual Behavior
when running terraform plan, backend = "azurerm" produces the "Unknown backend type: azurerm".
changing backend = "azure" for the data.terraform_remote_state seems to work, but this is not how the backend is documented.

### Steps to Reproduce
Configure a data.terraform_remote_state resource to use a backend of type "azurerm"
terraform plan

### Important Factoids
n/a

### References
None Found.

**Comment by tombuildsstuff** [comment]
Hey @TheLinuxNinja 

Thanks for opening this issue :)

Taking a quick look into this, it appears this is an issue with [the `terraform` provider](https://github.com/terraform-providers/terraform-provider-terraform) which hasn't been updated to include this new backend. I've [opened this issue](https://github.com/terraform-providers/terraform-provider-terraform/issues/13) to update the vendored copy of Terraform to a version which supports for this new backend.

Thanks!

**Comment by lkamrat** [comment]
Hi,
Any updates on this?

**Comment by joda10** [comment]
Hi,

Any update on this as I just ran the following and added this code to the end of the main code file .tf:
```
data "terraform_remote_state" "trss" {
  backend = "azurerm"

  config {
    storage_account_name = "devtrss"
    container_name       = "trss"
    key                  = "terraform.tfstate"
    access_key           = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```
And I'm getting the following error:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.trss: Refreshing state...
Error refreshing state: 1 error(s) occurred:

* data.terraform_remote_state.trss: 1 error(s) occurred:

* data.terraform_remote_state.trss: data.terraform_remote_state.trss: Unknown backend type: azurerm
```

Terraform version v0.10.7

Thanks

**Comment by tombuildsstuff** [comment]
Hi @TheLinuxNinja @lkamrat @joda10 

Support for the renamed backend has been released in v1.0.1 of the `terraform` provider - which can be pinned as follows:

```
provider "terraform" {
  version = "1.0.1"
}
```

Thanks!

**Comment by gunndabad** [comment]
I still see this issue even with version 1.0.1 of the Terraform provider.

`Downloading plugin for provider "terraform" (1.0.1)...`
...
`data.terraform_remote_state.platform: data.terraform_remote_state.platform: Unknown backend type: azurerm`

**Comment by tombuildsstuff** [comment]
@gunndabad sorry about this - I'm looking into this at the moment.

**Comment by joda10** [comment]
Hi tombuildsstuff,

I get the same issue and want to know does the upgrade fix the issue?

**Comment by gunndabad** [comment]
Sorted for me with version 1.0.2. Cheers
