### ISSUE TITLE
provider.azurerm: plugin exited before we could connect

### ISSUE THREAD

**Issue by swathiAMD** [terraform-providers/terraform-provider-azurerm#3541]
Hi,

   I m trying to build an Linux server using terraform and azurerm provider. I m trying to use existing virtual network and subnet which already been assigned to 2 other Vm machines. When i m trying to run the command  :  terraform plan -out out.plan the below error is thrown. Can anyone please help me?
---
Error: Error asking for user input: 1 error occurred:
        * provider.azurerm: plugin exited before we could connect
---

Thanks,
Swathi S

**Comment by katbyte** [comment]
Hi @swathiAMD,

Without an terraform configuration and debug/crash log i'm afraid we cannot help you. As such i am going to close this. Please feel free to reopen it with a completed issue template 🙂
