### ISSUE TITLE
REQ - Ability to add new cidr to an existing vnet

### ISSUE THREAD

**Issue by tomasquith** [terraform-providers/terraform-provider-azurerm#3545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be goof to be able to add new CIDRs to existing VNets without destroying them in order to expand the address space on some of our longer lived vnets, without this feature we have to deploy a new VNet and peer which introduces additional cost and complexity.

This is possible via the CLI

https://docs.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-update

### New or Affected Resource(s)

https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html

* azurerm_virtual_network

* #0000

**Comment by katbyte** [comment]
Hi @tomasaschan,

It looks like this functionality already exists? I have added a new test that updates a vnet with a new CIDR in #v3639 to confirm it can be done:
```
[12:01:00] kt@snowbook:~/hashi/tf/azure/azurerm▸r/vendor_azuread$ testazure TestAccAzureRMVirtualNetwork_basicUpdated
==> Fixing source code with gofmt...
# This logic should match the search logic in scripts/gofmtcheck.sh
find . -name '*.go' | grep -v vendor | xargs gofmt -s -w
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./azurerm -v -test.run=TestAccAzureRMVirtualNetwork_basicUpdated -timeout 180m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMVirtualNetwork_basicUpdated
=== PAUSE TestAccAzureRMVirtualNetwork_basicUpdated
=== CONT  TestAccAzureRMVirtualNetwork_basicUpdated
--- PASS: TestAccAzureRMVirtualNetwork_basicUpdated (121.50s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	121.553s
[12:35:32] kt@snowbook:~/hashi/tf/azure/azurerm▸vnet/add_cidr_test$
```

Please let us know if we missed something else or attach a tf config exhibiting the error. 

Thanks!

**Comment by tomasaschan** [comment]
@katbyte I think you meant to tag @tomasquith :)

**Comment by katbyte** [comment]
I did! sorry about that 😅

**Comment by tomasaschan** [comment]
No worries - I've kind of gotten used to it (lots of people talking in the issues here tag me when they mean `@tombuildsstuff`...). I see it as a way to keep tabs on the project without getting notifications about _everything_ 😂
