### ISSUE TITLE
Chicken and Egg scenario accessing Datasource

### ISSUE THREAD

**Issue by DYNSOL** [terraform-providers/terraform-provider-azurerm#3546]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.0
AzureRM v1.28.0

### Affected Resource(s)

* `azurerm_key_vault`
* `azurerm_subnet`

### Terraform Configuration Files

First of all, this is how my folder structure looks:

```
├── environments
│   ├── Production
│   │ └── main.tf
│   ├── Virtual Networks
│   │ └── main.tf
├── Modules  
│   ├── Compute
│   │ ├── Windows
│   │ │ ├── with AS
│   │ │ │ └── main.tf
│   │ │ │ └── output.tf 
│   │ │ │ └── variables.tf
│   ├── Networking
│   │ ├── VNET
│   │ │ └── main.tf
│   │ │ └── output.tf 
│   │ │ └── variables.tf
│   │ ├── Subnet
│   │ │ └── main.tf
│   │ │ └── output.tf 
│   │ │ └── variables.tf
│   ├── KeyVault
│   │ └── main.tf
│   │ └── output.tf 
│   │ └── variables.tf
├── main.tf
└── provider.tf
```

```hcl

My main.tf looks like this:

module "Production" {
  source = "./Environments/Production"
  providers = {
    azurerm = "azurerm.Production"
  }
}

module "VirtualNetworks" {
  source = "./Environments/Virtual Networks"
  providers = {
    azurerm = "azurerm.Production"
  }
}

```

### Expected Behavior

I have 2 environments:

Virtual Network environment contains 5 or so TF files which create seperate VNETs, Subnets and Peers the networks. These are all in the same folder as it made it easier read the module outputs to peer the networks.

Production environment contains two tf files for a VM deployment and KeyVault.

I have 2 Datasources that reside in the Windows VM\With AS module which i use to get a Subnet from a VNET created in the Virtual Networks Module and KeyVault ID from the KeyVault module to save a KeyVault Secret to.

I need a dependency on the Datasources to wait for the Subnet and KeyVault to be created before they try and read the Datasource. Is this possible in the way that i have configured my modules and folder structure?

### Actual Behavior
```

Error: Error: Subnet "subnetname-frontend-1" (Virtual Network "vn-1" / Resource Group "rg-we-1") was not found

  on Modules\Compute\Windows VM\with AS\Main.tf line 25, in data "azurerm_subnet" "Subnet":
  25: data "azurerm_subnet" "Subnet" {
```
```
Error: KeyVault "kv-name" (Resource Group "KeyVault-RG-Test") does not exist

  on Modules\Compute\Windows VM\with AS\Main.tf line 53, in data "azurerm_key_vault" "keyvault":
  53: data "azurerm_key_vault" "keyvault" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by moisedo** [comment]
Can you show the module block for both Subnet & Key Vault? it may be just a quick `module.mod_name.output` to create a simple dependency.

**Comment by DYNSOL** [comment]
> 
> 
> Can you show the module block for both Subnet & Key Vault? it may be just a quick `module.mod_name.output` to create a simple dependency.

Hi @moisedo thanks for getting back to me. Below are the module blocks.

````
module "keyvault" {
  source = "../../modules/KeyVault"
  KVRG = "${module.KVResourceGroup.Name}" 
  KVLocation = "${module.KVResourceGroup.Location}"
  KVName = "kv-name"
  EnvironmentTag = "Production"  
  KeyVaultEnabledforDeployment = true
  KeyVaultEnabledforDiskEncrypt = true
  KeyVaultEnabledforTempDeploy = true
}
````
module "FrontEndSubnet" {

    source = "../../modules/Networking/Subnet/with RouteTable"

    #Module variables
    SubnetName                  = "frontend-1"
    RGName                      = "${module.vNetResourceGroup.Name}"
    vNetName                    = "${module.vNet.Name}"
    Subnetaddressprefix         = "10.102.160.0/24"
    EnvironmentTag              = "#####"

    RouteTableName              = "${module.FrontEndSubnet.Name}" # Creates RT name based on Subnet name above.
    RTLocation                  = "${module.vNetResourceGroup.Location}"
    BGPDisabled                 = false   
}

````

````

**Comment by DYNSOL** [comment]
I need to dynamically get it for example:

````
data "azurerm_subnet" "Subnet" {
  name                  = "${var.ExistingSubnetName}"
  resource_group_name   = "${var.ExistingVNETRG}" 
  virtual_network_name  = "${var.ExistingVNETName}"
  #depends_on = ["data.terraform_remote_state.subnet.subnet_id"]      
}
````

**Comment by moisedo** [comment]
Thank you for showing your code. It seems that your problem is simple. In your `Main.tf` part of the `Modules\Compute\Windows VM\with AS\` seems that you are calling the `data source` at the time of the resource creation, therefore it wont find such resource. 

Suggestion: Isolate the creation of your resources from modules. example:

`vnet.tf`
```hcl
resource "azurerm_virtual_network" "vnet" {
  name                = "${var.vnet_name}"
  location            = "${var.location}"
  resource_group_name = "${var.vnet_rg_name}"
  address_space       = "${var.vnet_address_prefix}"
  dns_servers         = "${var._vnet_dns_servers}"
  tags                = "${var.tags}"
}
```
`subnet.tf`
```hcl
resource "azurerm_subnet" "subnet" {
  count                     = "${length(keys(var.subnets_info))}"
  name                      = "${element(split(",",element(values(var.subnets_info),count.index)), 0)}"
  resource_group_name       = "${var.vnet_rg_name}"
  virtual_network_name      = "${var.vnet_name}"
  address_prefix            = "${element(split(",",element(values(var.subnets_info),count.index)), 1)}"
  service_endpoints         = ["Microsoft.Storage", "Microsoft.KeyVault"]
  network_security_group_id = "${var.nsg_id}"
  route_table_id            = "${var.rt_id}"
}
```
the `var.subnets_info` is an environment variable and it would look something like this:
```sh
export TF_VAR_subnets_info"{
     \"Subnet1\" = \"Subnet1,10.102.160.0/28\"
     \"Subnet2\" = \"Subnet2,10.102.160.16/28\"
     \"Subnet3\" = \"Subnet3,10.102.160.32/28\"
}"
```
then your modules should look something like this:

`Network.tf`

```hcl
module "vnet_rg" {
  source   = "<location/of/rg.tf.file>"
  rg_name  = "${var.vnet_rg_name}"
  location = "${var.loc}"
  tags     = "${var.default_tags}"
}

module "vnet" {
  source              = "<location/of/vnet.tf.file>"
  vnet_name           = "${var.vnet_name}"
  location            = "${var.loc}"
  vnet_rg_name        = "${module.vnet_rg.rg_name}"
  vnet_address_prefix = ["${var.vnet_cidr}"]
  vnet_dns_servers    = ["${var.vnet_dns_servers}"]
  tags                = "${var.default_tags}"
}

module "subnet" {
  source       = "<location/of/subnet.tf.file>"
  subnets_info = "${var.subnets_info}"
  vnet_rg_name = "${module.vnet_rg.rg_name}"
  vnet_name    = "${module.vnet.vnet_name}"
  nsg_id       = "${module.nsg.nsg_id}"
  rt_id        = "${module.udr.rt_id}"
}
```

You get the idea... once you have it this way it would be much simpler to identity and to avoid the "chicken vs egg" problem. You are also creating "Soft" dependencies by calling the module above to to reference what was previously created.

I hope this helps!

**Comment by DYNSOL** [comment]
Thank you. That definitely makes sense. I will give it a try :) 

The reason i created this issue is that it worked in v.0.11.14.. but i guess it was likely a fluke :)

**Comment by DYNSOL** [comment]
@moisedo - how would the folder structure look like for that?

I am actually isolating resources.

````
resource "azurerm_virtual_network" "vNet" {
  name                = "vn-${var.EnvironmentPrefix}-${var.vNetName}"
  resource_group_name = "${var.RGName}"
  address_space       = "${var.vNetAddressSpace}"
  location            = "${var.vNetLocation}"
  dns_servers         = "${var.vNetDNSServers}"

  tags = {
    Environment       = "${var.EnvironmentTag}"    
  }
}

````

i have a subnet with RT as it makes it easier to Manage:

````
resource "azurerm_subnet" "SubnetwithRouteTable" {
  name                      = "sn-${var.vNetName}-${var.SubnetName}"
  resource_group_name       = "${var.RGName}"
  virtual_network_name      = "${var.vNetName}"
  address_prefix            = "${var.Subnetaddressprefix}"  
  service_endpoints         = "${var.SVCEP}" 
  lifecycle { 
     ignore_changes = ["route_table_id"]
 }  
}

resource "azurerm_subnet_route_table_association" "RouteTableAssociation" {
  subnet_id      = "${azurerm_subnet.SubnetwithRouteTable.id}"
  route_table_id = "${azurerm_route_table.RouteTable.id}"
}

resource "azurerm_route_table" "RouteTable" {
  name                          = "rt-${var.RouteTableName}"
  location                      = "${var.RTLocation}"
  resource_group_name           = "${var.RGName}"
  disable_bgp_route_propagation = "${var.BGPDisabled}"

    tags = {
    Environment         = "${var.EnvironmentTag}"    
    }
}
````

I'm getting the logic of resource isolation. But i still can't get around accessing the Subnet info and the Keyvault info.

Modules\Compute\Windows VM\with AS\ looks like this:

````
data "azurerm_key_vault" "keyvault" {  
  name                = "${var.KVName}"
  resource_group_name = "${var.KVRG}"       
}

resource "random_string" "password" {
  count = "${var.VMCount}"
  length = 14
  special = true
  override_special = "!#@"  
}

resource "azurerm_key_vault_secret" "KVSecret" {
  count     = "${var.VMCount}"
  name      = "${var.VMName}-${count.index + 1}-Password"
  value     =  "${element(random_string.password.*.result, count.index)}"  
  key_vault_id = "${data.azurerm_key_vault.keyvault.id}" 
  depends_on = ["azurerm_availability_set.AS"]   
}
````
The Keyvault Resides ````Modules\KeyVault\````

So when i call both modules which reside in the production folder which creates the VM and KeyVault it just doesn't create that dependency. I've got no issues with the Network creating the VNETs, Subnets and RT's becasue i've got the soft dependencies as you've mentioned. I think this is slightly different to your solution?

**Comment by moisedo** [comment]
Its ok, i believe you need to restructure your code to make more sense ( hope i am not interfering with your flow...)

`1. Lets separate the blocks by their purpose:`
     a. resources
     b. variables (resources) 
     c. output (resources)
     d. modules
     e. variables (modules)
     f. output (modules)
     g. providers (modules)
     h. data (modules)
     i. backend (modules)

`2. Now you can create 2 folder structure with the following tree:`
```sh
.
├── modules
│   ├── DEV
│   │   ├── 01.Network
│   │   │   ├── backend.tf
│   │   │   ├── data.tf
│   │   │   ├── module.tf
│   │   │   ├── output.tf
│   │   │   ├── providers.tf
│   │   │   └── variables.tf
│   │   └── 02.Compute
│   │       ├── backend.tf
│   │       ├── data.tf
│   │       ├── module.tf
│   │       ├── output.tf
│   │       ├── providers.tf
│   │       └── variables.tf
│   └── PRD
│       ├── 01.Network
│       │   ├── backend.tf
│       │   ├── data.tf
│       │   ├── module.tf
│       │   ├── output.tf
│       │   ├── providers.tf
│       │   └── variables.tf
│       └── 02.Compute
│           ├── backend.tf
│           ├── data.tf
│           ├── module.tf
│           ├── output.tf
│           ├── providers.tf
│           └── variables.tf
└── resources
    ├── compute
    │   ├── output.tf
    │   ├── resource.tf
    │   └── variables.tf
    ├── resource_group
    │   ├── output.tf
    │   ├── resource.tf
    │   └── variables.tf
    └── vnet
        ├── output.tf
        ├── resource.tf
        └── variables.tf
```
`3. define you resources vs your modules`

At this stage you want to start constructing the resources, in this example, i gave you 3 resources (Compute, vNet, resource group) - Now, lets see how would those look like:

Resource Group (resource.tf)
```hcl
resource "azurerm_resource_group" "rg"
     name       = "${var.rg_name}"
     location   = "${var.location}"
     tags         = "${var.tags}"
}
```
resource group (variables.tf)
```hcl
variable "rg_name" {
    type = "string"
}

variable "location" {
    type = "string"
}

variable "tags" {
    type = "map"
    description = "Key Value pair TAG = VALUE"
}
```
note: You dont have to specify the type for `string` every time, i just do it for fun... ;)

resource group (output.tf)
```hcl
output "output_rg_name" {
     value = "${azurerm_resource_group.rg.name}"
}

output "output_rg_id" {
     value = "${azurerm_resource_group.rg.id}"
}
```
`4. Final, create your modules:`

- Keep in mind, the reason why you have backend, data, module, output, provider, variables files is so you can segregate the block that are within those and only have such in their respective files. ie, do NOT put `module` in `data` or `data` in `providers` etc. you get the drill

So, your DEV Module will look like this:

module.tf
```hcl
module "rg" {
  source       = "../../Resources/resource_group"
  rg_name  = "VALUE" or "${var.TFVAR_VALUE}" or "${TF_VAR_ENV_Var}"
  location = "${var.location}"
  tags     = "${var.tags}"
}

module "vnet" {
  source                  = "../../Resources/vnet"
  vnet_name           = "${var.vnet_name}"
  location            = "${var.location}"
  vnet_rg_name        = "${module.rg.output_rg_name}"  #<--- Output from the resource group above
  vnet_address_prefix = ["${var.vnet_cidr}"]
  vnet_dns_servers    = ["${var.vnet_dns_servers}"]
  tags                = "${var.tags}"
}
```

Last, delcare your `Module` variables, set your data sources, your backend, etc etc. and you are all set... all i wanted to show you here is how you can use the output for the resource with this folder structure.

This has worked for me for years of TF implementation as well is more organized. WHY? - well because if tomorrow TF decides to support a new `RESOURCE` all i have to do is add it to my resource folder and then i deploy from the module and now its in State. 

You can add more functionality to this tree structure, which ill leave it up to your specific use case, but at the end of the day this is what i believe to be a good start. 

I hope this helps.
--Abe M.

**Comment by DYNSOL** [comment]
Thanks @moisedo you've gone above and beyond here. 

If i have a VM in `compute\resource.tf` which has a NIC and the code looks like the below. Then i create the module in `dev\compute\module.tf` How would i be able to retrieve the subnet data? i'm still struggling to understand how it gets the data source across folder directories. Because **01.Network** and **02.Compute** aren't together so `"${module.vnet_subnet1.output_subnet_id}"` (for example) won't work. 
````
resource "azurerm_network_interface" "vm_with_as_nic" {
    name                = "${var.VMName}-nic-${count.index + 1}"
    count               = "${var.VMCount}"
    location            = "${var.VMLocation}"
    resource_group_name = "${var.VMRG}"      

    ip_configuration {
        name                          = "ipconfig"
        subnet_id                     = "${data.azurerm_subnet.Subnet.id}"
        private_ip_address_allocation = "static"
        private_ip_address            = "${cidrhost(data.azurerm_subnet.Subnet.address_prefix, var.IPAddress+count.index)}"
        #"${cidrhost(var.IPAddress, 4+count.index)}"              
    }

    tags = {
        Environment = "${var.EnvironmentTag}"       
    }
}
````

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here this appears to be an issue regarding Module Dependencies - which unfortunately aren't supported in Terraform Core at this time. As such I'm going to close this in favour of the upstream issue on Terraform Core where this is being tracked: https://github.com/hashicorp/terraform/issues/10462 - would you mind subscribing to that issue for updates?

Thanks!
