### ISSUE TITLE
New resource: azurerm_management_group_subscription_association

### ISSUE THREAD

**Issue by richeney** [terraform-providers/terraform-provider-azurerm#3555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New azurerm_management_group_subscription_association resource to decouple the management group definitions from the subscription membership.

Setting the tenancy level governance (management groups, custom policies and initiatives, mg level role and policy assignments) could be configured separately from the subscription association. An MSP could centralise their default governance in a module and then associate a subscription to an mg to inherit default role assignments and policy assignments.

Version 2.0 could remove `subscription_ids` list as an option from management groups, in line with other association changes.

### New or Affected Resource(s)

New: 

* azurerm_management_group_subscription_association 

Affected (2.0 - optional)

* azurem_management_group

### Potential Terraform Configuration

```hcl
resource "azurerm_management_group" "non-prod" {
  display_name = "Non-Prod"
}

resource "azurerm_management_group" "dev" {
  display_name               = "Dev"
  parent_management_group_id = azurerm_management_group.non-prod.id
}

resource "azurerm_management_group_subscription_association" "project_x" {
  management_group_id      = azurerm_management_group.dev.id
  subscription_id          = "2d31be49-d999-4415-bb65-8aec2c90ba62"
}
```

### References

* #0000

**Comment by benc-uk** [comment]
Under investigation

**Comment by richeney** [comment]
Picking this one up
