### ISSUE TITLE
[Clarification] Location vs Region?

### ISSUE THREAD

**Issue by JustinGrote** [terraform-providers/terraform-provider-azurerm#3556]
This is a terminology clarification. I notice all the resources use "location" when specifying an azure "region" like "US West 2", etc.

MS has two different documents for locations and regions, and seem to define locations as the "state" or "city" a region is located in
https://azure.microsoft.com/en-us/global-infrastructure/locations/

So why is this parameter "location" and not "region"? Is it a legacy API thing? Did regions used to be called locations but were renamed regions to be in line with AWS?

**Comment by sean-nixon** [comment]
The Azure API uses the term "location" to specify the Azure region. All tools I've used to interact with Azure (PowerShell, Azure CLI, ARM templates, etc.) all use the `location` terminology as a result. Region is effectively the marketing term. An example from the Azure API docs in the "Request Body" section https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#request-body

**Comment by JustinGrote** [comment]
@sean-nixon I figured as much per above. Closing.
