### ISSUE TITLE
New Data Source: `azurerm_virtual_network_gateway_connection`

### ISSUE THREAD

**Issue by mattdot** [terraform-providers/terraform-provider-azurerm#3561]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Data Source for Virtual Network Gateway Connection

### New or Affected Resource(s)

* azurerm_virtual_network_gateway_connection

### Potential Terraform Configuration

```hcl
data "azurerm_virtual_network_gateway_connection" "test" {
	name                           = "myVirtualNetworkGatewayConnection"
	resource_group_name = "myResourceGroup"
}
```

### References

* https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways
* #3027

**Comment by mybayern1974** [comment]
@katbyte , so assume this issue could be closed?
