### ISSUE TITLE
azurerm_monitor_diagnostic_setting showing changes for logs/metrics not defined in the config

### ISSUE THREAD

**Issue by sawyerh** [terraform-providers/terraform-provider-azurerm#3572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.13
+ provider.azurerm v1.29.0
```

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "db" {
  name               = "db-audit-records"
  target_resource_id = "${azurerm_cosmosdb_account.db.id}"
  storage_account_id = "${azurerm_storage_account.audit_records.id}"

  log {
    category = "DataPlaneRequests"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }
}
```

### Expected Behavior

After an initial `terraform apply`, when I run another `terraform apply`, I should see no changes.

### Actual Behavior

After an initial `terraform apply`, when I run another `terraform apply`, I see settings for log and metric categories that I didn't define in my configuration being changed. Specifically, the category names are being set to `""`:

```
Terraform will perform the following actions:

  ~ module.instance.azurerm_monitor_diagnostic_setting.db
      log.#:                                        "3" => "1"
      log.2322944631.category:                      "DataPlaneRequests" => "DataPlaneRequests"
      log.2322944631.enabled:                       "true" => "true"
      log.2322944631.retention_policy.#:            "1" => "1"
      log.2322944631.retention_policy.0.days:       "0" => "0"
      log.2322944631.retention_policy.0.enabled:    "false" => "false"
      log.235918854.category:                       "QueryRuntimeStatistics" => ""
      log.235918854.enabled:                        "false" => "false"
      log.235918854.retention_policy.#:             "1" => "0"
      log.235918854.retention_policy.0.days:        "0" => "0"
      log.235918854.retention_policy.0.enabled:     "false" => "false"
      log.3876472479.category:                      "MongoRequests" => ""
      log.3876472479.enabled:                       "false" => "false"
      log.3876472479.retention_policy.#:            "1" => "0"
      log.3876472479.retention_policy.0.days:       "0" => "0"
      log.3876472479.retention_policy.0.enabled:    "false" => "false"
      metric.#:                                     "1" => "0"
      metric.1222937415.category:                   "Requests" => ""
      metric.1222937415.enabled:                    "false" => "false"
      metric.1222937415.retention_policy.#:         "1" => "0"
      metric.1222937415.retention_policy.0.days:    "0" => "0"
      metric.1222937415.retention_policy.0.enabled: "false" => "false"
```

### Steps to Reproduce

1. Add the configuration block above
1. Run `terraform apply` to set the initial diagnostic settings
1. Run `terraform apply` (or `terraform plan`) again to observe the planned changes

### References

- If this isn't a bug, I do have some [questions related to this behavior in the Google Group](https://groups.google.com/forum/#!topic/terraform-tool/nXp8NzP689g).

**Comment by sawyerh** [comment]
In order to not have Terraform indicate there are changes when no changes have been made, you currently need to define all log and metrics, indicating the ones that should NOT be enabled, along with the ones that should be enabled.

Here's an example of what you need to do to enable just the `DataPlaneRequests` category for Cosmos DB Diagnostic Logs:

```hcl
resource "azurerm_monitor_diagnostic_setting" "db" {
  name               = "db-audit-records"
  target_resource_id = "${azurerm_cosmosdb_account.db.id}"
  storage_account_id = "${azurerm_storage_account.audit_records.id}"

  log {
    category = "DataPlaneRequests"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }

  # Define the log and metrics that we don't want:

  log {
    category = "QueryRuntimeStatistics"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }

  log {
    category = "MongoRequests"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "Requests"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }
}
```

**Comment by magodo** [comment]
Hi @sawyerh Thank you for reporting this :+1:

This is seems duplicated to #7235, where I have put some explaination of this issue and a linked PR trying to suppress this annoying diff.
In order to better track this issue, hope you don't mind I close this issue in favor of #7235. You can also subscribe that issue for any update!
