### ISSUE TITLE
Add data source for azurerm_eventhub_namespace_authorization_rule

### ISSUE THREAD

**Issue by alastairtree** [terraform-providers/terraform-provider-azurerm#3577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Summary
Please add a new data source for an existing event hub namespace auth rule, in addition to the existing resource that creates authorisation rule resources.

#### Motivation

If using event hubs for diagnostic logging then many resources will need auth rule keys to be able send logs to the hub. Event hubs are limited to 12 auth rules, so an auth rule needs to be reused across many resources diagnostic settings. When using the azurerm_monitor_diagnostic_setting we need to pass the ID of the event hub auth rule in the eventhub_authorization_rule_id  argument, and there is no way to acquire the ID of the rule without creating it in the same template or string building based on the eventhub namespace datasource.

### New or Affected Resource(s)

* azurerm_eventhub_namespace_authorization_rule

### Potential Terraform Configuration

```hcl
data "azurerm_eventhub_namespace_authorization_rule" "test" {
  name                           = "test-rule"
  namespace_name        = "eventhub-ns"
  resource_group_name = "eventhug-rg"
}
```

**Comment by katbyte** [comment]
closing this as it was fixed by #4615! released in 1.36

**Comment by alastairtree** [comment]
@katbyte I don't think that #4615 contains any related changes? Should this be reopened?

**Comment by katbyte** [comment]
@alastairtree, you are correct! Seems i commented and closed on the wrong issue. Reopened
