### ISSUE TITLE
Support for managing firewall rules of Azure Redis Cache

### ISSUE THREAD

**Issue by dominik-lekse** [terraform-providers/terraform-provider-azurerm#358]
With the recent version of the Terraform Azurerm Provider, Azure Redis Cache firewall rules cannot be managed.

### Terraform AzureRM Provider Version
0.2.1

### Expected Behavior
A separate resource should exist which allows to manage firewall rules for Azure Redis Cache resources. Similar resources exist for [SQL Server instances](https://www.terraform.io/docs/providers/azurerm/r/sql_firewall_rule.html), or [PostgreSQL instances](https://www.terraform.io/docs/providers/azurerm/r/postgresql_firewall_rule.html).

### Actual Behavior
Firewall rules for Azure Redis Cache instances cannot be managed via Terraform.

### References
Microsoft Azure SDK for Go provides [support for managing firewall rules](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/redis/firewallrule.go).

**Comment by tombuildsstuff** [comment]
Hey @dominik-lekse 

Thanks for this issue - just to let you know that I've added support for Redis Firewall Rules in #529.

Thanks!

**Comment by dominik-lekse** [comment]
@tombuildsstuff Thanks for the resource and the update
