### ISSUE TITLE
Resource not working : azurerm_api_management_api_version_set

### ISSUE THREAD

**Issue by Djiit** [terraform-providers/terraform-provider-azurerm#3580]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.0
+ provider.azurerm v1.28.0

### Affected Resource(s)

* `azurerm_api_management_api_version_set`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api_version_set" "api-stocks-set" {
  name                = "stocks"
  resource_group_name = "<obfuscated>"
  api_management_name = "<obfuscated>"
  display_name        = "Stocks"
  versioning_scheme   = "Segment"
}
```

### Expected Behavior

It should create a working Version set., and the created version set should be usable in further `azurerm_api_management_api` (to group them under the version set).

### Actual Behavior

This resource is unusable : 
- The doc contains a typo : the resource is called (everywhere in the page) `azurerm_api_management_version_set`; try this and you will have an error saying this resource is not supported by the Azure RM provider; it should say `azurerm_api_management_api_version_set`. I guess I'm one of the few users of this resource.
- the versioning_scheme `Segment` does not exist in Azure. I guess it is mapped to `Path£ scheme. It should be renamed to `Path` to avoid confusion.
- On a `azurerm_api_management_api` resource, the attribute `version_set_id` is read-only. How are we supposed to link it to a given Version Set ?

### Steps to Reproduce

1. `terraform apply`

**Comment by hctv19** [comment]
@Djiit If I'm not mistaken I think this issue can be closed now. It looks like the docs are updated properly now (https://www.terraform.io/docs/providers/azurerm/r/api_management_api_version_set.html) and we're currently using the version set resources in production without issue (using versioning_scheme = "Segment"). 

I think the issue regarding the mismatch between calling the versioning strategy "Segment" vs "Path" is still relevant, but implementing this would be a breaking change for current users of this resource, and this is actually how the scheme is represented in the ARM resource, so I think it's probably ok the way it is.

**Comment by Djiit** [comment]
Hey, I'm not using this myself anymore. There is still at least 18+ people interested in a resolution. @katbyte what do you think ? Should we keep this one open ?

Thanks

**Comment by tombuildsstuff** [comment]
hey @Djiit 

Based on the comments from @hctv19 it sounds like the documentation issues are fixed. With regards to renaming the value from `segment` to `path` on Terraform's side, in this instance it appears the Azure API's changed the name of this value but is backwards compatible, so whilst we could look to force everybody to migrate over here - I don't think it's worth the upheaval at this time.

In this instance since these appear to serve the same purpose I'm going to suggest we close this issue for the moment, and we can look to handle this in the future if there's larger changes required here.

Thanks!
