### ISSUE TITLE
Allow to specify throughput for azurerm_cosmosdb_mongo_collection

### ISSUE THREAD

**Issue by bbung** [terraform-providers/terraform-provider-azurerm#3586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We need to specify the throughput for a collection. As this effects the performance and the costs this feature is really needed to use this resource.

### New or Affected Resource(s)

azurerm_cosmosdb_mongo_collection

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_mongo_database" "example" {
  name                = "tfex-cosmos-mongo-db"
  resource_group_name = "${data.azurerm_cosmosdb_account.example.resource_group_name}"
  account_name        = "${data.azurerm_cosmosdb_account.example.name}"
  throughput = "400"
}
```

### References
Azure CLI
https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest#az-cosmosdb-collection-create

**Comment by ronaldmiranda** [comment]
would be nice on SQL api too, i need this so much
