### ISSUE TITLE
azurerm_sql_managed_instance doesn't support import

### ISSUE THREAD

**Issue by kim0** [terraform-providers/terraform-provider-azurerm#3587]
### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.0
+ provider.azuread v0.3.1
+ provider.azurerm v1.30.0
+ provider.helm v0.9.1
+ provider.kubernetes v1.7.0
+ provider.random v2.1.2
```
I checked out the provider from commit `6391188a133e1271b38999844b4dfce197592deb` and built it myself to get the sql-mi resource

### Affected Resource(s)

* `azurerm_sql_managed_instance`

### Expected Behavior

The resource imports

### Actual Behavior

```
terraform import module.eu3.module.sqlmi.azurerm_sql_managed_instance.sqlmi /subscriptions/XXXXXXX/resourceGroups/eu3/providers/Microsoft.Sql/managedInstances/sqlmi-eu3-foo
module.eu3.module.sqlmi.azurerm_sql_managed_instance.sqlmi: Importing from ID "/subscriptions/XXXXXX/resourceGroups/eu3/providers/Microsoft.Sql/managedInstances/sqlmi-eu3-foo"...

Error: resource azurerm_sql_managed_instance doesn't support import
```

**Comment by tombuildsstuff** [comment]
hi @kim0 

Thanks for opening this issue.

Since this PR is being worked through but isn't yet merged - I'm going to close this issue for the moment; instead would you mind adding this feedback to #2727 where it can be incorporated into the PR?

Thanks!
