### ISSUE TITLE
azurerm_sql_managed_instance does not have fully_qualified_domain_name attribute

### ISSUE THREAD

**Issue by kim0** [terraform-providers/terraform-provider-azurerm#3593]
### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.0
+ provider.azuread v0.3.1
+ provider.azurerm v1.30.0
+ provider.helm v0.9.1
+ provider.kubernetes v1.7.0
+ provider.null v2.1.2
+ provider.random v2.1.2
```
### Affected Resource(s)

* `azurerm_sql_managed_instance`

The `attributes` as written in the `terraform.tfstate` file does **not** have a `fully_qualified_domain_name` attribute

This is really blocking me, so if it's a quick fix, would really appreciate pushing it .. Thanks

**Comment by kim0** [comment]
Hello @joranm @katbyte .. I think this attribute was accidentally dropped. Hope it's a quick fix! Thanks a lot for helping.

**Comment by tombuildsstuff** [comment]
hi @kim0 

Thanks for opening this issue.

Since this PR is being worked through but isn't yet merged - I'm going to close this issue for the moment; instead would you mind adding this feedback to #2727 where it can be incorporated into the PR?

Thanks!
