### ISSUE TITLE
Add missing features for Monitor Action Group senders

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#3603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Have a list of asks for the Azure Monitor Action Group resource:

1. When configuring a new Email/SMS/Push/Voice action within an Action Group via the portal, it is possible to enable the all of the different sender types (Email/SMS/Push/Voice) in a single action but when using the Terraform resource, you have to create a separate action for each type. Would be nice to be able to duplicate the functionality available in the portal

2. When creating an email receiver via Terraform, this creates a new action with the Email sender enabled and the email address. After attaching the action group to an Alert, we found that the even though the Alert was firing, it was not sending out emails via the Action Group. Once we went into the action via the portal and set `Enable the common alert schema` to `Yes`, emails would get sent each time the associated Alert fired.

3. Please add the ability to enable `Azure app Push Notifications` to the resource.

4. Please add the ability to enable the common alert schema to the resource.

### New or Affected Resource(s)

* azurerm_monitor_action_group

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_action_group" "secteam" {
  name                = "SecurityTeam"
  resource_group_name = "${data.terraform_remote_state.corerg.rgname}"
  short_name          = "SecTeam"

  email_receiver {
    name          = "${var.adm1_alertAction_name}_email"
    email_address = "${var.adm1_email}"
  }

  email_receiver {
    name          = "${var.adm2_alertAction_name}_email"
    email_address = "${var.adm2_email}"
  }

  email_receiver {
    name          = "${var.adm3_alertAction_name}_email"
    email_address = "${var.adm3_email}"
  }
}
```

**Comment by ArturDorochowicz** [comment]
Apart from _common alert schema_ I'd also be very much interested in support for `armRoleReceivers`.

https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2019-06-01/actiongroups#ArmRoleReceiver

**Comment by mcdafydd** [comment]
I just submitted a PR for some of these requests:

#4260

**Comment by ArturDorochowicz** [comment]
@tombuildsstuff There's now a minor issue in the documentation for `azurerm_monitor_action_group`. The example shows an invalid `arm_role_receiver` block with a `resource_id` attribute. It should be `role_id` and the value should be different.
