### ISSUE TITLE
update azurerm_eventhub_namespace resource 

### ISSUE THREAD

**Issue by razsha** [terraform-providers/terraform-provider-azurerm#361]
Hi,

azure eventhub support up to 20 Throughput Units (capacity variable in terraform). 
https://azure.microsoft.com/en-us/pricing/details/event-hubs/
however, terraform capacity variable can be 1, 2 or 4.
https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace.html
please update this to 20. 

thanks, 
Raz.

**Comment by tombuildsstuff** [comment]
From what I can see this was fixed in #556 - closing
