### ISSUE TITLE
Authentication failed. The 'Authorization' header is missing.

### ISSUE THREAD

**Issue by rolandjohann** [terraform-providers/terraform-provider-azurerm#3612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
$ terraform -v
Terraform v0.11.14
+ provider.azurerm v1.30.0
+ provider.consul v2.5.0
+ provider.template v2.1.2
```

### Actual Behavior

`terraform [apply|plan|destroy|` crashes with:
```
azurerm_user_assigned_identity.[...]-identity: Error making Read request on User Assigned Identity "[...]-identity" (Resource Group "[...]"): msi.UserAssignedIdentitiesClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing."
```

Using `provider.azurerm v1.29.0` "fixes" the problem.

**Comment by tombuildsstuff** [comment]
hey @rolandjohann 

Thanks for opening this issue.

Taking a look into this this appears to be a regression introduced with some recent work where the authorization endpoint is no longer called; apologies for the regression here - I'll send a PR shortly and release a hotfix (v1.30.1) later this afternoon.

Thanks!
