### ISSUE TITLE
azurerm_virtual_machine_extension CustomScript 2.0 runs as sudo

### ISSUE THREAD

**Issue by elduddz** [terraform-providers/terraform-provider-azurerm#3617]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
0.12.1

### Affected Resource(s)

* `azurerm_virtual_machine_extension`
* `CustomScript 2.0`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "VM01TeamServicesAgentLinux" {
  name                 = "${var.PREFIX}-${var.VM01}-TeamServicesAgentLinux"
  location             = "${azurerm_resource_group.main.location}"
  resource_group_name  = "${azurerm_resource_group.main.name}"
  virtual_machine_name = "${azurerm_virtual_machine.VM01.name}"
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"
  settings             = <<SETTINGS
    {
        "fileUris": ["https://gist.githubusercontent.com/elduddz/0f14f1c47e5569272a55cb415306e6f3/raw/1189acec19e34ea8c98785932525feef00e0c49d/agentinstall.sh"],
        "commandToExecute": "sh agentinstall.sh"
    }
SETTINGS
}
resource "azurerm_virtual_machine_extension" "VM01AgentStart" {
  name = "${var.PREFIX}-${var.VM01}-TeamServicesAgentLinux"
  location = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  virtual_machine_name = "${azurerm_virtual_machine.VM01.name}"
  publisher = "Microsoft.Azure.Extensions"
  type = "CustomScript"
  type_handler_version = "2.0"
  depends_on = ["azurerm_virtual_machine_extension.VM01TeamServicesAgentLinux"]
  
  settings = <<SETTINGS
    {
        "commandToExecute": "sh /usr/lib/agent/config.sh"
    }
SETTINGS
}
```

### Debug Output

Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'uks-monty-agents-VM01-TeamServicesAgentLinux'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\nMust not run with sudo\n\n[stderr]\n\"."

  on main.tf line 101, in resource "azurerm_virtual_machine_extension" "VM01AgentStart":
 101: resource "azurerm_virtual_machine_extension" "VM01AgentStart" {

### Expected Behavior

config.sh would run, in this case fail as I havent provided any variables

### Actual Behavior

Message states that config.sh cannot be run as sudo

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The TeamServiceForLinux only deal with Deployment Groups I need to add to the AgentPool, so have to use custom script

**Comment by nbering** [comment]
Have you tried running that script extension with Terraform, like using the Azure CLI?

It seems more likely to be an issue with the script itself, or the [CustomScript](https://github.com/Azure/custom-script-extension-linux) extension itself, unless the provider is somehow manipulating your extension configuration.

If are running a script that does not want to be run as root, I can imagine that being an issue, as the Agent that installs extensions runs the installation as root. Sometimes the errors people write for that will say "don't sudo" instead of "don't run as root", because sudo is more familiar to less experienced users.

**Comment by elduddz** [comment]
I haven't tried via the CLI.

The error is from the script provided by Microsoft for configuration of the agent, I'll have to look at what conditions are met.

If I log on the box and run the script with sudo at the start I get the message, don't run as sudo. Might have to try the run as root and see what happens.

If is the customscript element rather than terraform I'm still a bit stuck.

**Comment by elduddz** [comment]
I have found that the script was checking the user id (which for root is 0) but it also has an environment variable I could set to something that would make it bypass that check. I think I have the work around.

```
if [ $user_id -eq 0 -a -z "$AGENT_ALLOW_RUNASROOT" ]; then
    echo "Must not run with sudo"
    exit 1
fi
```
