### ISSUE TITLE
terraform v12 import Error with azurerm_logic_app_trigger_http_request

### ISSUE THREAD

**Issue by andyt530** [terraform-providers/terraform-provider-azurerm#3620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

az2tf$ terraform -v
Terraform v0.12.1
+ provider.azurerm v1.30.1

* `azurerm_logic_app_trigger_http_request`

### Terraform Configuration Files

```hcl
# File generated by az2tf see: https://github.com/andyt530/az2tf 
resource azurerm_logic_app_trigger_http_request pri__Entitysec {
         name = "Entitysec"
         logic_app_id = "${azurerm_logic_app_workflow.pri__Entitysec.id}"
schema = jsonencode(
{
    "required": [
        "PartitionKey",
        "RowKey"
    ],
    "type": "object",
    "properties": {
        "PartitionKey": {
            "type": "string"
        },
        "RowKey": {
            "type": "string"
        }
    }
})
}

```
```
terraform import azurerm_logic_app_trigger_http_request.pri__Entitysec /subscriptions/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/PRI/providers/Microsoft.Logic/workflows/Entitysec/triggers/Entitysec
```

### Debug Output

azurerm_logic_app_trigger_http_request.pri__Entitysec: Importing from ID "/subscriptions/a822c5a5-3eda-430a-af3e-a39be510a039/resourceGroups/PRI/providers/Microsoft.Logic/workflows/Entitysec/triggers/Entitysec"...
azurerm_logic_app_trigger_http_request.pri__Entitysec: Import complete!
  Imported azurerm_logic_app_trigger_http_request
azurerm_logic_app_trigger_http_request.pri__Entitysec: Refreshing state... [id=/subscriptions/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/PRI/providers/Microsoft.Logic/workflows/Entitysec/triggers/Entitysec]

**Error: Cannot import non-existent remote object**

While attempting to import an existing object to
azurerm_logic_app_trigger_http_request.pri__Entitysec,
the provider detected that no object exists with the given id. Only
pre-existing objects can be imported; check that the id is correct and that it
is associated with the provider's configured region or endpoint, or use
"terraform apply" to create a new remote object for this resource.

### Expected Behavior

Expecting import to work without error

The import resource ID does not exist in Azure and is "synthetic" to terraform - but should work according to the documentation (see reference below)

### References
From the docs page:

https://www.terraform.io/docs/providers/azurerm/r/logic_app_trigger_http_request.html

Logic App HTTP Request Triggers can be imported using the resource id, e.g.

terraform import azurerm_logic_app_trigger_http_request.request1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Logic/workflows/workflow1/triggers/request1

**NOTE: This ID is unique to Terraform and doesn't directly match to any other resource. To compose this ID, you can take the ID Logic App Workflow and append /triggers/{name of the trigger}.**

* #0000

**Comment by neil-yechenwei** [comment]
@andyt530, thanks for opening this issue. After tested with latest azurerm version and below tfconfig, seems I cannot repro it anymore. If it's possible, could you help to double check whether the issue still exists?
First apply with below tfconfig:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-lp-neiltest"
  location = "eastus2"
}

resource "azurerm_logic_app_workflow" "test" {
  name                = "workflow1neiltest"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_logic_app_trigger_http_request" "test" {
    name = "Entitysecneiltest"
    logic_app_id = azurerm_logic_app_workflow.test.id
	schema = jsonencode(
	{
		"required": [
			"PartitionKey",
			"RowKey"
		],
		"type": "object",
		"properties": {
			"PartitionKey": {
				"type": "string"
			},
			"RowKey": {
				"type": "string"
			}
		}
	})
}
```

terraform import:
```
terraform import azurerm_logic_app_trigger_http_request.test /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-lp-neiltest/providers/Microsoft.Logic/workflows/workflow1neiltest/triggers/Entitysecneiltest
```

Result:
![image](https://user-images.githubusercontent.com/19754191/84334796-d9405380-abc5-11ea-9fac-ce03422e146c.png)

**Comment by maciejgwizdala** [comment]
I noticed the same problem. Seems like this issue appears when your account has access to multiple subscriptions and az cli has set default subscription to different than this one, from which you want to import.
Here is workaround, which worked for me: https://stackoverflow.com/questions/60723765/error-cannot-import-non-existent-remote-object

**Comment by neil-yechenwei** [comment]
If so, I assume it's the resolution not workaround since it's the usage problem. For setting subscription id in terraform environment,  suggests to use below ways.

Method 1:
```
provider "azurerm" {
  features {}
  subscription_id = "00000000-0000-0000-0000-000000000000"
}

Method 2:
```
set ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
or
export ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
```

**Comment by tombuildsstuff** [comment]
Closing since updating the provider block to specify the correct subscription should resolve this
