### ISSUE TITLE
Azure DNS Alias records

### ISSUE THREAD

**Issue by mikhailshilkov** [terraform-providers/terraform-provider-azurerm#3624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support Alias records in Azure DNS for public zones. This feature allows referencing other Azure resources from within their DNS zones such that the DNS records get updated automatically when there is a lifecycle event on the referenced Azure resources.

Sample ARM template block:

``` json
{
    "type": "Microsoft.Network/dnszones/A",
    "apiVersion": "2018-05-01",
    "name": "[concat(parameters('dnszones_bla.foo_name'), '/@')]",
    "dependsOn": [
         "[resourceId('Microsoft.Network/dnszones', parameters('dnszones_bla.foo_name'))]"
    ],
    "properties": {
         "TTL": 3600,
         "targetResource": {
             "id": "[concat(parameters('profiles_cdnprofileabc_externalid'), '/endpoints/blafoobar')]"
         }
     }
},
```

### New or Affected Resource(s)

* azurerm_dns_a_record
* azurerm_dns_aaaa_record 
* azurerm_dns_cname_record 

### Potential Terraform Configuration

```hcl
resource "azurerm_dns_a_record" "test" {
  name                = "test"
  zone_name           = "${azurerm_dns_zone.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  ttl                 = 300
  targetResource      = "${azurerm_cdn_endpoint.test.name}"
}
```

### References

* [Announcing Alias records for Azure DNS](https://azure.microsoft.com/nl-nl/blog/announcing-alias-records-for-azure-dns/)
* [Azure DNS alias records overview](https://docs.microsoft.com/en-us/azure/dns/dns-alias)

**Comment by stack72** [comment]
FYI, this will require an update of the SDK version

**Comment by matt-FFFFFF** [comment]
I'm also affected by this. My use case requires the '@' record creating to enable aliasing at the zone level. Something like this:

```terraform
resource "azurerm_dns_a_record" "test" {
  name                = "@"
  zone_name           = "${azurerm_dns_zone.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  ttl                 = 300
  target_resource_id  = "${azurerm_cdn_endpoint.test.id}"
}
```

**Comment by matt-FFFFFF** [comment]
I have started taking a look at this: matt-FFFFFF/terraform-provider-azurerm#1

Initial testing with A records has been successful.

**Comment by matt-FFFFFF** [comment]
#5133
