### ISSUE TITLE
 No provider "azurerm" plugins meet the constraint "=2.0.0,>= 1.1.0".

### ISSUE THREAD

**Issue by bgarcial** [terraform-providers/terraform-provider-azurerm#3627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
⟩ terraform -v
Terraform v0.12.1

```
### Affected Resource(s)

* Network and compute modules

### Terraform Configuration Files

I am using[ the Getting Stated Azure guideline, and I want to create a compute and a network modules](https://learn.hashicorp.com/terraform/azure/modules_az) of this way:

- Azure RM Network Module to create a vnet and subnet.
- Azure RM Compute Module to create a Linux vm.

```hcl
# Use the network module to create a vnet and subnet
module "network" {
    source              = "Azure/network/azurerm"
    version             = "2.0.0"
    location            = "${var.location}"
    resource_group_name = "${azurerm_resource_group.rg.name}"
    address_space       = "10.0.0.0/16"
    subnet_names        = ["mySubnet"]
    subnet_prefixes     = ["10.0.1.0/24"]
}

# Use the compute module to create the VM
module "compute" {
    source            = "Azure/compute/azurerm"
    version           = "1.2.0"
    location          = "${var.location}"
    vnet_subnet_id    = "${element(module.network.vnet_subnets, 0)}"
    admin_username    = "plankton"
    admin_password    = "Password1234!"
    remote_port       = "22"
    vm_os_simple      = "UbuntuServer"
    vm_size           = "${lookup(var.vm_size, var.environment)}"
    public_ip_dns     = ["zzdns"]
}
```

### Debug Output
But when I apply terraform init I get this:

```
⟩ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "random" v1.3.1 is not compatible with Terraform 0.12.1.

Provider version 2.1.0 is the earliest compatible version. Select it with 
the following version constraint:

	version = "~> 2.1"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


No provider "azurerm" plugins meet the constraint "=2.0.0,>= 1.1.0".

The version constraint is derived from the "version" argument within the
provider "azurerm" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.


Error: incompatible provider version



Error: no suitable version is available


[I] 

```

### Expected Behavior

I expect that the modules version being downloaded and its works with the terraform 0.12.1 version, allowing initialize the provider plugins and initialize terraform itsef 

### Actual Behavior

Looks like `azurerm` provider is not compatible with 0.12.1 terraform version in order to  download and initialize the plugins providers and modules itself.

### Steps to Reproduce

- Please follow [this small part of the guide](https://learn.hashicorp.com/terraform/azure/modules_az) 

I am not using any provider explicitly, but when I add 

```
provider "azurerm" {
  version = "=2.0.0"
}
```
I get that output indicated previously. 

Even if I am using `1.28.0` azure provider version I get the same output.

It is a current error related with the azure provider version or does the modules causing some problem here? 

### References

- [Announcement: Upcoming Changes in Version 2.0 of the Azure Provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2807)

- [Plugin installer doesn't filter by protocol version during installation ("Incompatible API version with plugin")](https://github.com/hashicorp/terraform/issues/19221) 

- [Provider incompatible with terraform 0.12.x](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2686)

**Comment by tombuildsstuff** [comment]
hi @bgarcial 

Thanks for opening this issue.

At the time of writing version 2 of the AzureRM Provider isn't out yet, and is still being discussed [in this blog post](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2807). There are however versions of the Azure Provider which support Terraform 0.12, [which should be from 1.29 onwards](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1290-may-25-2019) - would you be able to take a look and see if updating your Provider block as below:

```
provider "azurerm" {
  version = "=1.29.0"
}
```

.. and then re-running `terraform init` works for you? Since this is a question regarding Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
