### ISSUE TITLE
Cannot Replace all Virtual Machines, out of list range error

### ISSUE THREAD

**Issue by bernadinm** [terraform-providers/terraform-provider-azurerm#364]
### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_machine.master[0]
- azurerm_virtual_machine.master[1]
- azurerm_virtual_machine.master[2]

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/bernadinm/0165ec81d286fcb0799fbc74151f7012

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

https://gist.github.com/bernadinm/1d1ab0ab62ad235a4aef0ac6fda1c625

### Expected Behavior
What should have happened?

All VMs should have been replaced

### Actual Behavior
What actually happened?

For the last node, it fails everytime.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `for i in $(seq 0 2); do terraform taint azurerm_virtual_machine.master.$i; done`
1. `terraform apply`

**Comment by katbyte** [comment]
Hi @bernadinm,

Apologies for letting this sit so long. This is a bug in terraform core and as it is well over 6 months old i am going to close the issue. If this is still a problem for you please open an issue on the main terraform repository.

Thanks!
