### ISSUE TITLE
Managed Identity for Application Gateway

### ISSUE THREAD

**Issue by fxgsell** [terraform-providers/terraform-provider-azurerm#3640]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support the Managed Service Identity for Application Gateway.

### New or Affected Resource(s)

* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "network" {
    ...
    identity = "${azurerm_user_assigned_identity.test.id}"
    ...
}
```

### References

* https://godoc.org/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-02-01/network#ApplicationGateway

* #0000

**Comment by dbilleci-lightstream** [comment]
Hi! Looking to implement keyvault certificates on HTTPS listener for application gateway.  Here are the powershell docs I found on the subject: https://docs.microsoft.com/bs-latn-ba/azure/application-gateway/configure-keyvault-ps

This seems to get us partially there by adding support for the identity on the gateway.

Am I correct that we'd also need to update the listener section to allow the "ID" of the vault certificate also?

Thanks!

**Comment by fxgsell** [comment]
@dbilleci-lightstream Hey, yes you're right, this is only half-way of what you need, for my use case I want to delegate the certificate choice to the ingress controller of a K8s cluster hence it wasn't required in terraform. You should open another issue for it.
