### ISSUE TITLE
unable to provision devtest labs with USE_IN_VIRTUAL_MACHINE_CREATION Allow Option

### ISSUE THREAD

**Issue by siva2krish** [terraform-providers/terraform-provider-azurerm#3662]
# Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Terraform Version

terraform -v
*	Terraform v0.12.0
*	+ provider.azurerm v1.29.0 

# Affected Resource(s)

*	azurerm_dev_test_virtual_network
* azurerm_dev_test_lab

# Terraform Configuration Files

```
provider "azurerm" {
        version = "~> 1.29.0"
}

resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West US"
}

resource "azurerm_dev_test_lab" "test" {
  name                = "example-devtestlab"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  tags = {
    "Sydney" = "Australia"
  }
}

resource "azurerm_dev_test_virtual_network" "test" {
  name                = "example-network"
  lab_name            = "${azurerm_dev_test_lab.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
subnet {
    use_public_ip_address           = "Deny"
    use_in_virtual_machine_creation = "Allow"
  }
}
resource "azurerm_dev_test_windows_virtual_machine" "test" {
  name                   = "snp-vm03"
  lab_name               = "${azurerm_dev_test_lab.test.name}"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  location               = "${azurerm_resource_group.test.location}"
  size                   = "Standard_DS2"
  username               = "snpadmin"
  password               = "Pa$$w0rd1234!"
  lab_virtual_network_id = "${azurerm_dev_test_virtual_network.test.id}"
  lab_subnet_name        = "example-networkSubnet"
  storage_type           = "Premium"
  notes                  = "windows virtual Machine."

  gallery_image_reference {
    offer     = "UbuntuServer"
    publisher = "Canonical"
    sku       = "18.04-LTS"
    version   = "latest"
  }
}
```
# Expected Behavior
* Terraform should set "use_in_virtual_machine_creation " to Allow on apply

# Actual Behavior
```
Terraform sets "use_in_virtual_machine_creation" to DENY on apply.
Error: Error creating/updating DevTest Windows Virtual Machine "snp-vm03" (Lab "example-devtestlab" / Resource Group "example-resources"): dtl.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidSubnetUsed" Message="Subnet example-networkSubnet either is not enabled or is not part of specified virtual network /subscriptions/84cf1cce-b695-4f60-8cc0-4d45168ae85a/resourcegroups/example-resources/providers/microsoft.devtestlab/labs/example-devtestlab/virtualnetworks/example-network."

  on clusterdefination.tf line 29, in resource "azurerm_dev_test_windows_virtual_machine" "test":
  29: resource "azurerm_dev_test_windows_virtual_machine" "test" {
 ```
# Steps to Reproduce
1.	terraform plan <-- will show that “use_in_virtual_machine_creation” Allow 
2.	terraform apply ---> Throwing error, tried allowing from azure portal by going to devtest labs virtual network but unable to save parameters from portal as well

**Comment by scarolan** [comment]
Can confirm, this is happening for me as well.

**Comment by DracoAter** [comment]
I have a similar problem. Terraform should set "use_in_virtual_machine_creation " to Allow on apply. But it does not.

## Versions
Terraform v0.11.14
+ provider.azurerm v1.29.0

## Actual behaviour
Terraform apply succeeds.

While terraform apply is in progress, I can go to azure web and see that Virtual network is created and has a subnet that allows "use_in_virtual_machine_creation". But when the "apply" process is complete "use_in_virtual_machine_creation" is false and I cannot also change it through web ui.

Same problem is with "use_public_ip_address", which should be true in my case, and it is until the apply process is finished. But then again it changes to false, exactly like with use_in_virtual_machine_creation.

**Comment by nadav2cohen** [comment]
there is also problem with Enable shared public IP in dev test lab, i'm not finding the command to control on this....  there is "use_in_virtual_machine_creation" command and "use_public_ip_address" but there is no syntax for "Enable shared public IP" in terraform v v0.12.0 and provider azurerm v1.36.0

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested with below tfconfig and latest azurerm, seems I cannot repro this issue anymore. Maybe I missed something. Could you have a try below tfconfig to check whether this issue still exists? Thanks.

```
provider "azurerm" {
    features {}
}

resource "azurerm_resource_group" "test" {
  name     = "examplerg-devlab-test11"
  location = "eastus2"
}

resource "azurerm_dev_test_lab" "test" {
  name                = "example-devtestlab-test11"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_dev_test_virtual_network" "test" {
  name                = "example-network"
  lab_name            = azurerm_dev_test_lab.test.name
  resource_group_name = azurerm_resource_group.test.name
  
  subnet {
    use_public_ip_address           = "Deny"
    use_in_virtual_machine_creation = "Allow"
  }
}
```

Result in azure portal:
![image](https://user-images.githubusercontent.com/19754191/88902780-3c289f80-d285-11ea-9308-5ebc50d5b03a.png)

**Comment by DracoAter** [comment]
@neil-yechenwei I am sorry, but this is not relevant for me anymore. I cannot check if this bug still exist, as I am not working with Azure for some time already.

**Comment by mybayern1974** [comment]
Hi @siva2krish, could you please check whether @neil-yechenwei 's way could work for you, or please allow me to ask whether this issue is still being used by you to track your question?

**Comment by jackofallops** [comment]
Closing this issue as stale. There have been over 30 releases and significant changes to the provider, along with @neil-yechenwei 's investigation this suggests that the underlying issue appears no longer present. If this is still an issue in 2.31 (released yesterday) or later, a new issue can/should be opened.
