### ISSUE TITLE
Unknown client ID being used when deploying azure_policy_definition

### ISSUE THREAD

**Issue by mjonespro** [terraform-providers/terraform-provider-azurerm#3671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform v0.12.2
+ provider.azurerm v1.30.0

### Affected Resource(s)

azurerm_policy_definition

### Terraform Configuration Files

```hcl

provider "azurerm" {
  subscription_id = "****"
}

terraform {
  backend "azurerm" {
    storage_account_name = "******"
    resource_group_name  = "rg-infra-centralus-terraform-01"
    container_name       = "terraformstate"
    key                  = "azure_policy.tfstate"
  }
}
resource "azurerm_policy_definition" "policy_agw_diagnostics" {
  name                = "AuditAGWDiagnostics"
  policy_type         = "Custom"
  mode                = "ALL"
  display_name        = "Audit Application Gateway Diagnostics Settings"
  management_group_id = "*****"

  policy_rule = <<POLICY_RULE
    {
    "if": {
        "field": "type",
        "equals": "Microsoft.Network/applicationGateways"
    },
    "then": {
        "effect": "AuditIfNotExists",
        "details": {
            "type": "Microsoft.Insights/diagnosticSettings",
            "existenceCondition": {
                "allOf": [
                    {
                        "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
                        "equals": "true"
                    },
                    {
                        "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",
                        "equals": "true"
                    }
                ]
            }
        }
    }
}
POLICY_RULE

}

```

### Expected Behavior

Deploy Azure Policy Definition

### Actual Behavior

Error: policy.DefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '15e8c3e2-2cb9-49ee-af81-a558616856c6' with object id '15e8c3e2-2cb9-49ee-af81-a558616856c6' does not have authorization to perform action 'Microsoft.Authorization/policyDefinitions/write' over scope '/providers/Microsoft.Management/managementgroups/******/providers/Microsoft.Authorization/policyDefinitions/AuditAGWDiagnostics'."

The client ID in this error message is not the client ID configured in my environment variables. I do not know where this client ID is coming from. It does not exist in my tenant so I understand the error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The client ID in this error message is not the client ID configured in my environment variables. I do not know where this client ID is coming from. It does not exist in my tenant so I understand the error.

### References

* #0000

**Comment by MohadKamil** [comment]
The same issue happens with me, it surfaced when I set the management_group_id, removing it results in a successful creation.

**Comment by mjonespro** [comment]
> The same issue happens with me, it surfaced when I set the management_group_id, removing it results in a successful creation.

Wow, I can confirm when I remove the management_group_id I can successfully do the terraform apply. This isn't a long term solution however as now the scope of my policy does not meet my requirements. Interesting enough, When I run terraform from azure cloud shell (.12.0 currently) I can do a successful terraform apply with management_group_id still in the configuration.

**Comment by jochenrichter** [comment]
I just struggeld with similar issues but not related to management groups.
But maybe it could help.
To check the client_id use az ad sp show --id 15e8c3e2-2cb9-49ee-af81-a558616856c6

Be shure to have the rights to create policies. The contributor role is not enough :-)
