### ISSUE TITLE
azurerm_cosmosdb_account virtual_network_rule required

### ISSUE THREAD

**Issue by chfrodin** [terraform-providers/terraform-provider-azurerm#3678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.2
+ provider.azurerm v1.29.0

### Affected Resource(s)

azurerm_cosmosdb_account 

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "cosmosdb_account" {
  name                              = "${local.prefix}${local.suffix}-cosmosdb"
  tags                              = merge( { Description = "${local.namebase} CosmosDB Account" } , local.rgtags )
  location                          = var.azurerm_resource_group_location
  resource_group_name               = var.azurerm_resource_group_name
  offer_type                        = "Standard"
  kind                              = var.kind
  ip_range_filter                   = var.ip_range_filter
  is_virtual_network_filter_enabled = var.is_virtual_network_filter_enabled
  enable_automatic_failover         = var.enable_automatic_failover


  consistency_policy {
    consistency_level       = var.consistency_level
    max_interval_in_seconds = var.max_interval_in_seconds
    max_staleness_prefix    = var.max_staleness_prefix
  }
  
  #main location
  geo_location {
    prefix            = "${var.prefix}-cosmosdb-location"
    location          = var.location
    failover_priority = "0"
  }
  #failover location
  geo_location {
    prefix            = "${var.prefix}-cosmosdb-failoverlocation"
    location          = var.failover_location
    failover_priority = "1"
  }

  capabilities {
    name              = var.capabilities_name
  }
  
  virtual_network_rule  {
    id                = var.virtual_network_rule_id
  }
}
```

### Expected Behavior

Terraform Plan should have gone through without requiring virtual_network_id
### Actual Behavior

Error: "virtual_network_rule.0.id": required field is not set

  on ../../IaC/aztfmod_cosmosdb/main.tf line 2, in resource "azurerm_cosmosdb_account" "cosmosdb_account":
   2: resource "azurerm_cosmosdb_account" "cosmosdb_account" {
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

In the azurerm_cosmosdb_account documentation virtual_network_id is listed as optional, yet when I do terraform plan without an input value, the error tells me it is a required field.

As you can also see the config text is from a module im building, all required parameters have inputs from core module, and all optional parameters have null value as default(this is to make it as reusable as possible)

Note here, the capabilities block gives me the same error when no input is given.

### References

https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html#virtual_network_rule
* #0000

**Comment by tombuildsstuff** [comment]
hi @chfrodin 

Thanks for opening this issue :)

Taking a look into this, the parent `virtual_network_rule` is Optional whilst the inner element (`id`) is Required, which means that if the outer block is specified, then you'll need to specify the inner element. You should be able to work around this by passing in a list for the `virtual_network_rule` property, similar to below:

```
variable "virtual_network_id" {}

locals {
  network_id = var.virtual_network_id == "" ? [] : [{
    id = var.virtual_network_id
  }]
}

resource "" "" {
  // ...
  virtual_network_id = local.network_id
}
```

Since this is a question about Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment - however please let us know i that doesn't work for you and we'll take another look :)

Thanks!
