### ISSUE TITLE
azurerm_app_service returning 400 on creation / Unknown service error

### ISSUE THREAD

**Issue by pjmolina** [terraform-providers/terraform-provider-azurerm#368]
Hi!
When creating an Azure App Service, creations fails and returns 400 error.
The sample config is adapted from the [documentation sample](https://www.terraform.io/docs/providers/azurerm/r/app_service.html).

Log extract:
```
Error applying plan:

1 error(s) occurred:

* azurerm_app_service.common_service: 1 error(s) occurred:

* azurerm_app_service.common_service: web.AppsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Unknown" Message="Unknown service error"
```

### Terraform Version
Terraform v0.10.6
Provider version: terraform-provider-azurerm_v0.2.2_x4

### Affected Resource(s)
- azurerm_app_service

### Terraform Configuration Files
```hcl
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}
resource "azurerm_resource_group" "g1" {
  name     = "acme-qa-app-01"
  location = "${var.location}"
}
resource "azurerm_app_service_plan" "plan0" {
  name                = "service-plan0-ireland"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.g1.name}"
  sku {
    tier = "Basic"  
    size = "B1"        
  }
}
resource "azurerm_app_service" "common_service" {
  name                = "sample_common_service-024"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.g1.name}"
  app_service_plan_id = "${azurerm_app_service_plan.plan0.id}"
  site_config {
    dotnet_framework_version = "v4.0"
  }
  app_settings {
    "SOME_KEY" = "some-value"
  }
}
```

### Debug Output
[Complete Output log](https://gist.github.com/pjmolina/8e0a8c8667cebf7dac6acf99006a4f8b)

### Panic Output
N.a.

### Expected Behavior
App Service resource should be created.

### Actual Behavior
App Service resource fails to be create.

### Steps to Reproduce
Provide vars for credentials and location and then:
```
terraform apply
```

### Important Factoids
Tested on locations WestEurope and WestUS, and with different plan sizes: S1 and B1. 
Same error still occurs.

### References
N.a.

**Comment by gunndabad** [comment]
Underscores are not valid in an app service name so I suspect this is the reason for the error.

**Comment by pjmolina** [comment]
Confirmed. Indeed! That is the reason @gunndabad 
Thanks for pointing out. The error code was not given much hint about it.
