### ISSUE TITLE
Error obtaining Authorization Token from the Azure CLI

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#3686]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.14
+ provider.azuread v0.4.0
+ provider.azurerm v1.30.1

### Debug Output

(Nothing suspicious)

### Actual Behavior

A few days ago, both azurerm and azuread started to fail with the following:
```
Error obtaining Authorization Token from the Azure CLI: Error waiting for the Azure CLI: exit status 1
```
If I do `az logout`/`az login`, azuread seems to refresh fine on the first run after that, but azurerm still fails. From the second run, azuread starts to fail again.

### Important Factoids
No changes to the environment had been made, no firewall or anything unusual.

**Comment by tombuildsstuff** [comment]
@Leon99 I'm wondering if this is the Azure CLI being updated automatically (since it updates itself) - out of interest is this an issue across terminal sessions?

**Comment by Leon99** [comment]
No, it's a local session.
Here is `az --version`:
```
azure-cli                         2.0.66

acr                                2.2.8
acs                                2.4.3
advisor                            2.0.0
ams                                0.4.6
appservice                        0.2.20
backup                             1.2.4
batch                              4.0.2
batchai                            0.4.9
billing                            0.2.1
botservice                         0.2.1
cdn                                0.2.3
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.23
consumption                        0.4.3
container                         0.3.17
core                              2.0.66
cosmosdb                          0.2.10
deploymentmanager                  0.1.0
dla                                0.2.5
dls                                0.1.9
dms                                0.1.3
eventgrid                          0.2.3
eventhubs                          0.3.6
extension                          0.2.5
feedback                           2.2.1
find                               0.3.3
hdinsight                          0.3.4
interactive                        0.4.4
iot                               0.3.10
iotcentral                         0.1.6
keyvault                          2.2.15
kusto                              0.2.2
lab                                0.1.7
maps                               0.3.4
monitor                           0.2.14
natgateway                         0.1.0
network                            2.5.1
nspkg                              3.0.3
policyinsights                     0.1.3
privatedns                         1.0.1
profile                            2.1.5
rdbms                             0.3.11
redis                              0.4.3
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.15
role                               2.6.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.5
servicefabric                     0.1.19
signalr                            1.0.0
sql                                2.2.4
sqlvm                              0.1.1
storage                            2.4.2
telemetry                          1.0.2
vm                                2.2.22

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\LeonVolovyk\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
Do you reckon I should try an older CLI?

**Comment by tombuildsstuff** [comment]
@Leon99 the same code's used between both of them, so if it works for AzureAD it should work for AzureRM.

Just to double-check: did you restart the terminal being used in that session to confirm?

**Comment by Leon99** [comment]
@tombuildsstuff I even restarted the machine

**Comment by Leon99** [comment]
Downgrading az to 2.0.65 didn't help

**Comment by Leon99** [comment]
It works on another machine with the same configuration - same .tfstate, same versions, same user, same network. @tombuildsstuff any ideas what can be machine-specific here?

**Comment by alastairtree** [comment]
I've seen a few of these of late, and we just try again and they go away.

**Comment by asubmani** [comment]
This is happening very consistently in my WSL2 Ubuntu 18.04. 
azure-cli version = 2.0.70
terraform 0.12.6
terraform_provider_azurerm = 1.32.1
I tried clearing my cred `az account clear`  ; restarting my laptop  didn't help either.

**Comment by tombuildsstuff** [comment]
👋 

So to give an update here, since I just ran into this when debugging - in my specific case this was that the password for my Azure account had changed, and thus the access tokens stored on disk became invalidated.

Terraform internally is just calling `az account get-access-token` - as such you should be able to run the same command to see the error; for example in my case:

```
The command failed with an unexpected error. Here is the traceback:

Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked. The user might have changed or reset their password. The grant was issued on '2019-XX-XXTXX:XX:XX.1767275Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2019-XX-XXTXX:XX:XX.0000000Z'.\r\nTrace ID: 00000000-0000-0000-0000-000000000000\r\nCorrelation ID: 00000000-0000-0000-0000-000000000000\r\nTimestamp: 2019-08-15 12:06:10Z","error_codes":[50173],"timestamp":"2019-08-15 12:06:10Z","trace_id":"00000000-0000-0000-0000-000000000000","correlation_id":"00000000-0000-0000-0000-000000000000","error_uri":"https://login.microsoftonline.com/error?code=50173"}
Traceback (most recent call last):
...
```

Would someone be able to take a look and confirm the next time this happens?

Thanks!

**Comment by asubmani** [comment]
> 👋
> 
> So to give an update here, since I just ran into this when debugging - in my specific case this was that the password for my Azure account had changed, and thus the access tokens stored on disk became invalidated.
> 
> Terraform internally is just calling `az account get-access-token` - as such you should be able to run the same command to see the error; for example in my case:
> 
> ```
> The command failed with an unexpected error. Here is the traceback:
> 
> Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked. The user might have changed or reset their password. The grant was issued on '2019-XX-XXTXX:XX:XX.1767275Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2019-XX-XXTXX:XX:XX.0000000Z'.\r\nTrace ID: 00000000-0000-0000-0000-000000000000\r\nCorrelation ID: 00000000-0000-0000-0000-000000000000\r\nTimestamp: 2019-08-15 12:06:10Z","error_codes":[50173],"timestamp":"2019-08-15 12:06:10Z","trace_id":"00000000-0000-0000-0000-000000000000","correlation_id":"00000000-0000-0000-0000-000000000000","error_uri":"https://login.microsoftonline.com/error?code=50173"}
> Traceback (most recent call last):
> ...
> ```
> 
> Would someone be able to take a look and confirm the next time this happens?
> 
> Thanks!

My grant is still active and I can see my token when I run `az account get-access-token`

`terraform plan` gives me:
Error: Error obtaining Authorization Token from the Azure CLI: Error retrieving access token from Azure CLI:
  on aks.tf line 1, in provider "azurerm":
   1: provider "azurerm" {

My first 3 lines of code in aks.tf look like:

``` 
provider "azurerm" {
  version = "=1.32.1"
}
```

**Comment by asubmani** [comment]
Update:

I had to login as root `sudo -i` to get this working.

The below methods do not work (all give the same error )

1.  `sudo terraform plan`  (all wsl shells; windows terminal as well as Ubuntu native shell from esl.exe)
2.  `terraform plan`  

The below works
1.  `sudo terraform plan`  -- from windows cmd shell
2.  `sudo -i `   # followed by `terraform plan` in the WSL2 shell

**Comment by techbunny** [comment]
I'm seeing this issue with Azure CLI 2.0.71. TF 12.2 and TF 11.11.  I tried several provider versions (1.28, 1.32, etc...)  I only get past authentication using azurerm provider version 1.20.

**Comment by ToruMakabe** [comment]
I got the same issue after changing my Azure AD password on my WSL. On Mac works fine (interesting). 

I tried some ways to find workaround, then it resolved with login with Tenant ID (az login --tenant <tenantid>). I hope it will be a clue to solve the problem.

**Comment by linbingdouzhe** [comment]
i use terraform for azure , face the same problem.
i use this command  to defiend env,and fix it.

export ARM_SUBSCRIPTION_ID=xxxxxxxxxxx
export ARM_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxx
export ARM_CLIENT_SECRET=xxxxxxxxxx
export ARM_TENANT_ID=xxxxxxxxxxxx
export ARM_ENVIRONMENT=public

**Comment by kasunsjc** [comment]
Getting the same error when I run terraform plan -var-file="variables.tfvars"

**Comment by SherwoodCH** [comment]
I had this issue on same versions of az cli and terraform. In my case I had an additional warning after the described error:
` Error: Error obtaining Authorization Token from the Azure CLI: Error retrieving access token from Azure CLI: WARNING: Unable to load extension 'azure-cli-iot-ext'. Use --debug for more information.'`

After reinstalling the azure-cli-iot-ext extension, terraform was able to retrieve the access token again.

**Comment by kasunsjc** [comment]
@SherwoodCH you can remove it and add it again. I got similar error `Error obtaining Authorization Token from the Azure CLI: Error retrieving access token from Azure CLI: WARNING: Unable to load extension 'resource-graph'. Use --debug for more information.` . This was fixed after following commands

`az extension remove --name resource-graph`
`az extension add --name resource-graph`

This will update to latest version

**Comment by tombuildsstuff** [comment]
👋 

So taking a look into this it appears the result of this is machine-specific Azure CLI issue which'll need to be diagnosed locally, rather than something we can fix unfortunately.

The Azure Provider shells out to the Azure CLI to run the command `az account get-access-token` - as such to debug this I'd suggest verifying that:

1. That the Azure CLI is available on your PATH (e.g. the `az` binary), by opening your default shell and running `az`)
2. That the Azure CLI is up to date
3. That running `az account get-access-token` returns a JSON token (and no errors)

But since these are machine specific issues unfortunately I don't believe there's a lot we can do to work around this from within the Azure Provider - and as such I'm going to close this issue for the moment. If that's still not working for you, you could instead use [one of the alternate mechanisms to authenticate to Azure](https://www.terraform.io/docs/providers/azurerm/index.html#authenticating-to-azure).

Thanks!

**Comment by kasunsjc** [comment]
I have the latest of the az 
`az --version
azure-cli                         2.0.71

command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
aks-preview                        0.4.5
azure-devops                      0.12.0
resource-graph                     1.0.0
interactive                        0.4.2

Python location '/usr/local/Cellar/azure-cli/2.0.71/libexec/bin/python'
Extensions directory '/Users/kasunrajapakse/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.`

**Terraform Version**
`terraform version
Terraform v0.12.6
+ provider.azurerm v1.32.0`

**az token**
`az account get-access-token
{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhY7vMtE4yg2CqS06pTj8qkcuKi8K0o9kxp8vejbaHamE6CSXsdGfzMFLxu6VBZ0sGTxyh_sD9p7bEbAw3oeaH9y8ZvPsiq8ZSqM97-IIHWm3gkKpGCx3DIXrLG-J8OGalVTOKJy66gk5V-zjt7imQx4dHm2P3Ys1x-FdKsJhi4_Oy2Fsqtzzk2tnWEVtxzijQPLONoug",
  "expiresOn": "2019-08-23 09:59:22.013324",
  "subscription": "",
  "tenant": "",
  "tokenType": "Bearer"
}`

I can get all the verifications you mentioned. but still when I run terraform plan it gives me the error 

`Error: Error obtaining Authorization Token from the Azure CLI: Error waiting for the Azure CLI: exit status 1

  on main.tf line 1, in provider "azurerm":
   1: provider "azurerm" {
`
