### ISSUE TITLE
Resource azurerm_cosmosdb_mongo_collection parameter default_ttl_seconds default value always trigger new action

### ISSUE THREAD

**Issue by matus-cuper** [terraform-providers/terraform-provider-azurerm#3691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi everyone,
I am using variables and multiple environment so I need to set `default_ttl_seconds` to its default value `-1` in resource `azurerm_cosmosdb_mongo_collection`. But when I run `terraform plan` after `terraform apply` it returns change in TTL property instead of `No changes`. When I tried to run `terraform apply` and `terraform plan` several times, the issue persists. Applying this change takes up to 1 minute.

### Terraform (and AzureRM Provider) Version

```bash
Terraform v0.12.2
+ provider.azurerm v1.30.1
```

### Affected Resource(s)

* `azurerm_cosmosdb_mongo_collection`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "cosmosdb_account" {
  name                = "test-cosmosdb-account"
  location            = "westeurope"
  resource_group_name = "rg_test"
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = false

  consistency_policy {
    consistency_level = "Eventual"
  }

  geo_location {
      location          = "westeurope"
      failover_priority = 0
  }
}

resource "azurerm_cosmosdb_mongo_database" "cosmosdb_db" {
  name                = "test"
  resource_group_name = "rg_test"
  account_name        = "test-cosmosdb-account"
}

resource "azurerm_cosmosdb_mongo_collection" "cosmosdb_collection" {
  name                = "documents"
  resource_group_name = "rg_test"
  account_name        = "test-cosmosdb-account"
  database_name       = "test"

  default_ttl_seconds = "-1"
  shard_key           = "myid"

  indexes {
    key    = "myid"
    unique = false
  }
}
```

### Expected Behavior

```bash
terraform apply
terraform plan
# No changes. Infrastructure is up-to-date.
```

### Actual Behavior

```bash
terraform apply
terraform plan
```

```bash
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_cosmosdb_mongo_collection.cosmosdb_collection will be updated in-place
  ~ resource "azurerm_cosmosdb_mongo_collection" "cosmosdb_collection" {
        account_name        = "test-cosmosdb-account"
        database_name       = "test"
      ~ default_ttl_seconds = 0 -> -1
        id                  = "..."
        name                = "documents"
        resource_group_name = "rg_test"
        shard_key           = "myid"

        indexes {
            key    = "myid"
            unique = false
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan`

**Comment by dberuben** [comment]
👍

**Comment by mike-brown-chr** [comment]
I arrived here thinking this is a documentation bug.  Setting the value to "0" instead of "-1" worked to meet the expected behavior for me.
