### ISSUE TITLE
azurerm_route - Add and Changes route on every plan/apply.

### ISSUE THREAD

**Issue by clarkcode** [terraform-providers/terraform-provider-azurerm#3699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `Terraform v0.12.0`
* `azurerm v1.30`

### Affected Resource(s)

* `azurerm_route`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example-rsg" {
    name     = "example-rsg"
    location = "uksouth"
}

resource "azurerm_virtual_network" "example-vnet" {
    name                = "example-vnet"
    location            = "uksouth"
    resource_group_name = "example-rsg"
    address_space       = ["10.0.0.0/24"]
}

resource "azurerm_subnet" "example-subnet" {
    name                        = "example-subnet"
    resource_group_name         = "example-rsg"
    virtual_network_name        = "${azurerm_virtual_network.example-vnet.name}"
    address_prefix              = "10.0.0.0/24"
    route_table_id              = "${azurerm_route_table.example-udr.id}"
    lifecycle { 
        ignore_changes = ["route_table_id"]
    }
}

resource "azurerm_route_table" "example-udr" {
    name                = "example-udr"
    location            = "uksouth"
    resource_group_name = "example-rsg"
    route {
        name           = "default-route"
        address_prefix = "0.0.0.0/0"
        next_hop_type  = "Internet"
    }
}

resource "azurerm_subnet_route_table_association" "perimeter-subnet-association" {
  subnet_id                 = "${azurerm_subnet.example-subnet.id}"
  route_table_id            = "${azurerm_route_table.example-udr.id}"
}

resource "azurerm_route" "example-route" {
    name                    = "example-route"
    resource_group_name     = "example-rsg"
    route_table_name        = "${azurerm_route_table.example-udr.name}"
    address_prefix          = "192.168.0.0/24"
    next_hop_type           = "VirtualAppliance"
    next_hop_in_ip_address  = "10.0.0.1"
}
```

### Expected Behavior

On Terraform plan/apply the resources are created and the route is added to the existing table. On subsequent plan/apply there should be no changes detected.

### Actual Behavior

On Terraform plan/apply the resources are created and the route is added to the existing table. On subsequent plan/apply there the route flips between adding and destroying despite there being no changes to the config.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### References

Very similar to this issue but Bot advised raising a new issue.
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/447

**Comment by NickMetz** [comment]
Hi @clarkcode,

the problem here is that you define default route inline (azurerm_route_table) + example-route as separated resource (azurerm_route). This is currently not possible, it should be configured inline or in separated resource but not both. 

This looks pretty similar behavior than subnet resource, but here we have a disclaimer that it is only possible to configure it one way. ( https://www.terraform.io/docs/providers/azurerm/r/subnet.html )

> At this time you cannot use a Virtual Network with in-line Subnets in conjunction with any Subnet resources. Doing so will cause a conflict of Subnet configurations and will overwrite Subnet's.

**Comment by clarkcode** [comment]
Hi @NickMetz 
Thanks for your comment. That was it! I have created a PR for the azurerm_route docs similar to that of the subnet note. Hopefully this would helps anyone else who may come across this behaviour.
https://github.com/terraform-providers/terraform-provider-azurerm/pull/3703
