### ISSUE TITLE
Feature Request - Availability Zones

### ISSUE THREAD

**Issue by tomasquith** [terraform-providers/terraform-provider-azurerm#370]
Hi, Following the announcements at Ignite it would be nice to explore the Availability Zones functionality which is now in preview via terraform. It's in a limited preview at the moment, only being in the one US region. It would be good to trial this as it means we can closely replicate AWS in terms of availability.

What is the stance on supporting preview features via terraform? 

https://azure.microsoft.com/en-gb/blog/introducing-azure-availability-zones-for-resiliency-and-high-availability/

**Comment by justaugustus** [comment]
@metacpp pinging you on this one, as you assigned yourself to #579.

**Comment by tombuildsstuff** [comment]
Support for this was added in #811 - closing.
