### ISSUE TITLE
api_management_api_operation.html import example is incorrect

### ISSUE THREAD

**Issue by SlOrbA** [terraform-providers/terraform-provider-azurerm#3701]
Terrafrom is not able to import using the example resource_id in api_management_api_operation.html. When looking at the same example in api_management_api_operation_policy.html it shows "/apis/api1" between the "/service/instance1" and the "/operations/operation1".

Defining the "/apis/api1" before the "/operations/operation1" provides the working example.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Part of the 1.30.1 release

### Affected Resource(s)

Documentation for the azurerm_api_management_api_operation

**Comment by mbfrahry** [comment]
Thanks for opening this issue @SlOrbA. The docs should be fixed in the next release.
