### ISSUE TITLE
azurerm_search_service tag change forces new resource

### ISSUE THREAD

**Issue by phosphre** [terraform-providers/terraform-provider-azurerm#3707]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v0.11.14
v1.30.1

### Affected Resource(s)

* `azurerm_search_service`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
  tags {
    environment      = "${var.env}"
    function         = "${var.function}"
    billingReference = "${var.billing}"
  }

then run, then edited to

  tags {
    environment      = "${var.env}"
    function         = "${var.function}"
    billingReference = "${var.billing}"
   newtag = "something"
  }
```

### Debug Output

```hcl
module.mymod.azurerm_search_service.main (new resource required)
 id:                                        "/subscriptions/blah/providers/Microsoft.Search/searchServices/mysearch" => <computed> (forces new resource)
...
      tags.%:                                    "3" => "4" (forces new resource)
      tags.billingReference:                     "mybill" => "mybill"
      tags.environment:                          "dev" => "dev"
      tags.function:                             "myfunc" => "myfunc"
      tags.newtag:                             "" => "something" (forces new resource)     # should not force new
```
### Expected Behavior

TF should have reported a modify.

### Actual Behavior

TF reported a destroy and create.

### Steps to Reproduce

1. As per the azurerm_search_service resource type with tags specified.
2. Add a new tag and rerun

### Important Factoids

This may be specific to the Azure API and not the azurerm provider, but as all other resource types are modify only for tag changes, I was expecting this to be the same, and suspect it might be a bug in the resource type.

**Comment by mbfrahry** [comment]
Hey @phosphre, thanks for opening this issue. This has been fixed in #3660 and should make it into the next release.
