### ISSUE TITLE
terraform error - with GeneralPurpose sql database

### ISSUE THREAD

**Issue by andyt530** [terraform-providers/terraform-provider-azurerm#3708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform --version
Terraform v0.12.1
azurerm 1.30.1

### Affected Resource(s)

* `azurerm_sql_database`

### Terraform Configuration Files

```hcl

resource azurerm_sql_database rg-caw__cawadmin {
         name = "cawadmin"
         location = "uksouth"
         resource_group_name = "rg-caw"
         server_name = "sql-caw"
         collation= "SQL_Latin1_General_CP1_CI_AS"
         edition= "GeneralPurpose"
         requested_service_objective_name= "GP_Gen5_2"
}

https://keybase.io/hashicorp
```

### Debug Output

```
$ terraform validate

Error: expected edition to be one of [Basic Standard Premium DataWarehouse], got GeneralPurpose
```

### Panic Output

* #0000

**Comment by mbfrahry** [comment]
Hey @andyt530, thanks for opening this issue. This has been fixed in #3710 and includes a slew of extra values as well. It should make it into the next release so I'll be closing this down
