### ISSUE TITLE
Allow multiple scopes to be passed to Monitor MetricAlert resource

### ISSUE THREAD

**Issue by praneetloke** [terraform-providers/terraform-provider-azurerm#3719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_monitor_metric_alert`

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior

Multiple `scopes` can be specified for a monitor metric alert resource.

### Actual Behavior

Only one scope is allowed due to an issue in the MS Go SDK, which has since been resolved (see References section below).

### Steps to Reproduce

```hcl
...
...
resource "azurerm_monitor_metric_alert" "test" {
  name                = "example-metricalert"
  resource_group_name = "${azurerm_resource_group.main.name}"
  // Cannot set more than one value here because `MaxItems` is set to 1.
  scopes              = ["${azurerm_storage_account.to_monitor.id}"]
  description         = "Action will be triggered when Transactions count is greater than 50."

  criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts"
    metric_name      = "Transactions"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 50

    dimension {
      name     = "ApiName"
      operator = "Include"
      values   = ["*"]
    }
  }

  action {
    action_group_id = "${azurerm_monitor_action_group.main.id}"
  }
}
...
...
```

### Important Factoids
N/A

### References

The relevant line in the resource is: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_monitor_metric_alert.go#L47.

The GitHub [issue](https://github.com/Azure/azure-sdk-for-go/issues/2920) linked in the comment for `scopes` has since been closed as resolved.

**Comment by e96wic** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/pull/4111

**Comment by markmqhr** [comment]
Any update on a fix for this?

**Comment by yupwei68** [comment]
Hi @praneetloke , Thanks for opening this issue. We might fix it later by opening this restriction of scope count. But in your case,` storage account` is still not supported for multiple resources alerts in metric alterts. Please refer to [the resouce types supported mulitple resources alerts](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-near-real-time#metrics-and-dimensions-supported).

**Comment by ArseniiPetrovich** [comment]
> Hi @praneetloke , Thanks for opening this issue. We might fix it later by opening this restriction of scope count. But in your case,` storage account` is still not supported for multiple resources alerts in metric alterts. Please refer to [the resouce types supported mulitple resources alerts](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-near-real-time#metrics-and-dimensions-supported).

Is this "later" is going to be in the near future? I want to use this feature in the project I'm currently working on as it essential to aggregate metrics over several resources, so it would be nice to have any deadlines for that issue. Is there any workaround I can use in the meanwhile?

**Comment by magodo** [comment]
@ArseniiPetrovich Looks like #4111 is quite close to addressing this issue, while somehow got closed.
Let me see if I can do anything to help here!

**Comment by ArseniiPetrovich** [comment]
That would be really nice, @magodo, thank you!

**Comment by magodo** [comment]
As #7159 has been merged, closing this issue for now.
