### ISSUE TITLE
Role assignment 403 error for Service Principal

### ISSUE THREAD

**Issue by jamie3** [terraform-providers/terraform-provider-azurerm#3723]
Terraform 0.12.2
Azure RM 1.30.1

I am trying to give a service principal (aka App registration) contributor role access to a resource group, and also ACR Pull role to an ACR.

When performing a terraform apply I receive the following error:

```
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalTypeNotSupported" Message="Principals of type Application cannot validly be used in role assignments."

  on main.tf line 66, in resource "azurerm_role_assignment" "acr_pull_role_assignment":
  66: resource "azurerm_role_assignment" "acr_pull_role_assignment" {



Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalTypeNotSupported" Message="Principals of type Application cannot validly be used in role assignments."

  on .terraform\modules\resource_group\main.tf line 30, in resource "azurerm_role_assignment" "contributor":
  30: resource "azurerm_role_assignment" "contributor" {
```

Here is the ACR role assignment:

```
resource "azurerm_role_assignment" "acr_pull_role_assignment" {
  name               = "398f0b7c-3cf3-4af5-9dac-e2681417ccb4"
  scope              = "/subscriptions/${var.subscription_id}/resourcegroups/${module.resource_group.name}/providers/Microsoft.ContainerRegistry/registries/${var.acr_name}"
  role_definition_id = "/subscriptions/${var.subscription_id}/providers/Microsoft.Authorization/roleDefinitions/${local.acr_pull_role_assignment_id}"
  principal_id       = "<application-id>"
}
```

This used to work in previous versions of terraform and Azure RM.

**Comment by jzoran05** [comment]
The same error. This is my configuration:

data "azurerm_subscription" "current" {}

data "azurerm_builtin_role_definition" "builtin" {
  name = "AcrPull"
}


output "contributor_role_definition_id" {
  value = data.azurerm_builtin_role_definition.builtin.id
}

resource "azurerm_role_assignment" "functionsjs" {
  scope              = "/subscriptions/${data.azurerm_subscription.current.subscription_id}/resourcegroups/${azurerm_resource_group.functionsjs.name}/providers/Microsoft.ContainerRegistry/registries/${azurerm_container_registry.functionsjs.name}"
  role_definition_id = data.azurerm_builtin_role_definition.builtin.id
  principal_id       = var.kubernetes_server_object_id
}

I am getting correct role ID when using data.azurerm_builtin_role_definition but still getting the error. role binding from Azure Portal for the same role works without problems...

**Comment by tombuildsstuff** [comment]
👋 

Since this appears to be a question regarding Terraform Configuration, rather than a bug in the Azure Provider - I'm going to close this out for the moment - but you should be able to get further assistance using [one of the community resources](https://discuss.hashicorp.com)

Thanks!
