### ISSUE TITLE
AKS: Support of standard load balancer

### ISSUE THREAD

**Issue by jluk** [terraform-providers/terraform-provider-azurerm#3726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS now supports standard load balancer in preview. GA is expected in the August timeframe and as a result we'd like to get this queued up for support in the provider. This enables selecting standard or basic SKUs as the load balancer provisioned for AKS.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### References

* Swagger reference is here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-06-01/managedClusters.json#L1585

* Public doc is here: docs.microsoft.com/en-us/azure/aks/load-balancer-standard

**Comment by Sahasrara** [comment]
This is a huge deal for us.  We get little to no insight into basic LB function and have had LB outages with no explanation.  Standard LB is cine qua non.

**Comment by gambtho** [comment]
submitted pull request #3890 for this
