### ISSUE TITLE
sku.0.tier in azurerm_cognitive_account is never set

### ISSUE THREAD

**Issue by robinmanuelthiel** [terraform-providers/terraform-provider-azurerm#3728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
Terraform v0.11.10
+ provider.azurerm v1.30.1
```

### Affected Resource(s)

* `azurerm_cognitive_account`

### Description

When creating a Cognitive Services Account `azurerm_cognitive_account`, setting the `sku.0.tier` field is required. At least for `SpeechServices` and `TextTranslation`, this tier is never set.

**This causes `terraform plan` to find changes every time!**

So even if nothing changed after `terraform apply`, the `terraform plan` command will always have the following output:

```bash
Terraform will perform the following actions:

  ~ azurerm_cognitive_account.speech
      sku.0.tier: "" => "Standard"

  ~ azurerm_cognitive_account.translate
      sku.0.tier: "" => "Standard"


Plan: 0 to add, 2 to change, 0 to destroy.
```

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_account" "speech" {
  name                = "${var.prefix}speech"
  location            = "${azurerm_resource_group.default.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  kind                = "SpeechServices"

  sku {
    name = "S0"
    tier = "Standard"
  }
}
```

### Expected Behavior

The `sku.0.tier` is set and won't show up in the diff if nothing changes.

### Actual Behavior

The `sku.0.tier` is not set and always shows up in the diff. Always.

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

**Comment by enorlando** [comment]
This is also true when kind is set to `QnAMaker`

**Comment by enorlando** [comment]
Any update for when this bug will be fixed?

**Comment by akonrath** [comment]
Hi @robinmanuelthiel ! Are you still encountering this issue on the latest provider version? The azurerm_cognitive_account resource no longer takes a sku block and instead just a sku_name. I was able to successfully create the SpeechServices kind from my end as a test.

```
$ terraform --version
Terraform v0.12.24
+ provider.azurerm v2.6.0
```

**Comment by robinmanuelthiel** [comment]
No, the issue is gone. Can be closed.
