### ISSUE TITLE
New Resource: Azure Machine Learning Service

### ISSUE THREAD

**Issue by lachie-white** [terraform-providers/terraform-provider-azurerm#3729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Azure Machine Learning service is a cloud service that you use to train, deploy, automate, and manage machine learning models, all at the broad scale that the cloud provides.

### New or Affected Resource(s)

* azurerm_machine_learning_service

### References

* https://docs.microsoft.com/en-us/azure/machine-learning/service/overview-what-is-azure-ml
* https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-workspace-template

**Comment by brigiyu** [comment]
it is a great resource. however, i continuously meet module not found issue while doing experiments. Jupyter notebook works well until I submit experiment (train.py). there were few modules not found even i installed the package. for example, librosa.

**Comment by bg2132332** [comment]
I see upcoming ML workspace resource.  Any plans to add training cluster deployment?

**Comment by tombuildsstuff** [comment]
Fixed via #3729
