### ISSUE TITLE
subnet delegation actions handling is incorrect.

### ISSUE THREAD

**Issue by alex-goncharov** [terraform-providers/terraform-provider-azurerm#3730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```bash
$ terraform version
Terraform v0.12.3
+ provider.azurerm v1.30.1
```

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "test" {
  name                 = "test"
  resource_group_name  = "test-rg"
  virtual_network_name = "test-vnet"
  address_prefix       = "10.1.0.0/24"

  delegation {
    name = md5("Microsoft.Sql/managedInstances")
    service_delegation {
      name = "Microsoft.Sql/managedInstances"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/action" 
        # "Microsoft.Network/virtualNetworks/subnets/join/action"
        # "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"
      ]
    }
  }
}
```

### Expected Behavior

Provider should accept all possible delegation action or if Azure API disallows delegation action modification (which, looking at the CLI it does not), then provider should not try to set or modify them.

### Actual Behavior

I'm fairly new to Azure API, but behaviour of the azurerm_subnet resource seems incorrect:

Provider allows me to create subnet delegation with empty actions list or with a single value in it (the one that's not commented out). Once subnet is created though, it looks like Azure API disregards actions list and create delegation with 3 options (full list above):
```
  # azurerm_subnet.test will be updated in-place
  ~ resource "azurerm_subnet" "test" {
        address_prefix       = "10.1.0.0/24"
        id                   = "..."
        ip_configurations    = []
        name                 = "test"
        resource_group_name  = "test-rg"
        service_endpoints    = []
        virtual_network_name = "test-vnet"

      ~ delegation {
            name = "5807eb7c8e7ae01071afecff5e0a7466"

          ~ service_delegation {
              ~ actions = [
                  - "Microsoft.Network/virtualNetworks/subnets/join/action",
                  - "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action",
                  + "Microsoft.Network/virtualNetworks/subnets/action",
                ]
                name    = "Microsoft.Sql/managedInstances"
            }
        }
    }
```

As a result terraform wants to change subnet delegation on every apply. And it is not possible to set all the actions because provider accepts only one: 

```
Error: expected delegation.0.service_delegation.0.actions.1 to be one of [Microsoft.Network/virtualNetworks/subnets/action], got Microsoft.Network/virtualNetworks/subnets/join/action
```

### Steps to Reproduce

1. create the plan from snippet above
2. `terraform apply`
3. `terrafrom plan`

**Comment by tusharbudhe0302** [comment]
###### I am still having this issue. It got fixed in Key vault, but still, an issue with a storage account.
####  "DefaultAction": "Allow" getting policy violation issue.
Error  : 
`Resource '{storage account name}' was disallowed by policy. Error Type: PolicyViolation` 

####  "DefaultAction": "Deny" getting network acls validation failure.
{
  "error": {
    "code": "NetworkAclsValidationFailure",
    "message": "Validation of network acls failure: SubnetsHaveNoServiceEndpointsConfigured:Subnets guy-dv-uset2-web of virtual network /subscriptions/{SubcriptionID}/resourceGroups/{resource-Group-Name}/providers/Microsoft.Network/virtualNetworks/{VNet-Name} do not have ServiceEndpoints for Microsoft.Storage resources configured. Add Microsoft.Storage to subnet's ServiceEndpoints collection before trying to ACL Microsoft.Storage resources to these subnets.."
  }
}

Plesae check below template code, which I am trying to execute : 
`
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#", 
  "contentVersion": "1.0.0.0", 
  "parameters": {
    "AppEnv": {
      "type": "Object"
    },
    "storageAccountObject": {
      "type": "Array"
    },
    "virtualNetworks_V_NET_NAME": {
      "type": "String"
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts", 
      "apiVersion": "2019-04-01", 
      "copy": {
        "name": "storageAccountObjectCopy", 
        "count": "[length(parameters('storageAccountObject'))]", 
        "mode": "serial", 
        "batchSize": 1
      },
      "name": "[parameters('storageAccountObject')[copyIndex()].storageAccounts_name]", 
      "location": "[resourceGroup().location]", 
      "tags": "[parameters('storageAccountObject')[copyIndex()].storageAccountTag]", 
      "sku": "[parameters('storageAccountObject')[copyIndex()].storageAccountSkuObject]", 
      "kind": "[parameters('storageAccountObject')[copyIndex()].storageAccountKindOff]", 
      "properties": {
        "networkAcls": {
          "bypass": "[parameters('storageAccountObject' [copyIndex()].storageAccountProperties.NetworkAcls.Bypass]", 
          "ipRules": [],
          "copy": [
            {
              "name": "**virtualNetworkRules**", 
              "count": "[length(parameters('storageAccountObject')[copyIndex()].storageAccountProperties.NetworkAcls.VNetSubNetRule)]", 
              "input": {
                **"id": "[concat(parameters('virtualNetworks_V_NET_NAME'),'/subnets/', parameters('storageAccountObject')[copyIndex()].storageAccountProperties.NetworkAcls.VNetSubNetRule[copyIndex('virtualNetworkRules')].subnets)]",** 
                "action": "[parameters('storageAccountObject')[copyIndex()].storageAccountProperties.NetworkAcls.VNetSubNetRule[copyIndex('virtualNetworkRules')].subnetsaction]", 
                "state": "[parameters('storageAccountObject')[copyIndex()].storageAccountProperties.NetworkAcls.VNetSubNetRule[copyIndex('virtualNetworkRules')].subnetsstate]"
              }
            }
          ],
          "defaultAction": "Deny"
        },
        "supportsHttpsTrafficOnly": true,
        "encryption": {
          "services": {
            "file": {
              "enabled": true
            },
            "blob": {
              "enabled": true
            }
          },
          "keySource": "Microsoft.Storage"
        },
        "accessTier": "[parameters('storageAccountObject')[copyIndex()].storageAccountProperties.AccessTier]"
      }
    }
  ]
}

`

please let me know if anyone found a fix for it. I am using VSTS CI/CD Pipeline

**Comment by bentterp** [comment]
PR #4137 should fix this issue

**Comment by bentterp** [comment]
@tusharbudhe0302 I think you may be commenting on a different issue?
AFAICT, your template does not seem to concern subnet delegation.
