### ISSUE TITLE
Azure Function App - adding support for min TLS version and HTTPS Only

### ISSUE THREAD

**Issue by alex-3sr** [terraform-providers/terraform-provider-azurerm#3740]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

Like for azurerm_app_service we really need to set min_tls_version for azurerm_function_app.
See #1601

Error  : 
2019-06-27T13:38:33.2907377Z   on main.tf line 90, in resource "azurerm_function_app" "functionapp":
2019-06-27T13:38:33.2908000Z   90:     min_tls_version          = "1.2"
2019-06-27T13:38:33.2908148Z 
2019-06-27T13:38:33.2908745Z An argument named "min_tls_version" is not expected here.

Thank you,
Alex

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "functionapp" {
  name                      = "AFA-01"
  location                  = "${azurerm_resource_group.rgproject.location}"
  resource_group_name       = "${azurerm_resource_group.rgproject.name}"
  app_service_plan_id       = "${azurerm_app_service_plan.planafa.id}"
  storage_connection_string = "${azurerm_storage_account.storage.primary_connection_string}"
  version                   = "~2"
  https_only                = true

    site_config {
        min_tls_version = "1.2"
    }

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
         "app_settings.FUNCTIONS_EXTENSION_VERSION"
     ]
  }
}
```

### References

* #0000

**Comment by aqche** [comment]
Looks like `https_only` is supported now. Opened a PR to add support for `min_tls_version`.
