### ISSUE TITLE
azure_policy_assignment not creating identity with appropriate permissions

### ISSUE THREAD

**Issue by cncoats** [terraform-providers/terraform-provider-azurerm#3743]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -v
Terraform v0.12.3
+ provider.azurerm v1.29.0
+ provider.random v2.1.2

### Affected Resource(s)

* azurerm_policy_assignment

### Terraform Configuration Files

```hcl

resource "azurerm_policy_definition" "nsg-policy" {
  name         = "Deploy Diagnostic Configuration for NSGs"
  policy_type  = "Custom"
  mode         = "Indexed"
  display_name = "Deploy Diagnostic Configuration for NSGs"

  policy_rule = <<POLICY_RULE
  {
    "if": {
          "field": "type",
          "equals": "Microsoft.Network/networkSecurityGroups"
        },
        "then": {
          "effect": "deployIfNotExists",
          "details": {
            "type": "Microsoft.Insights/diagnosticSettings",
            "name": "setbypolicy",
            "roleDefinitionIds": [
                "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
            ],
            "deployment": {
              "properties": {
                "mode": "incremental",
                "template": {
                  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                  "contentVersion": "1.0.0.0",
                  "parameters": {
                    "location": {
                      "type": "string"
                    },
                    "nsgName": {
                      "type": "string"
                    }
                  },
                  "resources": [
                    {
                      "type": "Microsoft.Network/networkSecurityGroups/providers/diagnosticSettings",
                      "name": "[concat(parameters('nsgName'),'/Microsoft.Insights/setbypolicy')]",
                      "apiVersion": "2017-05-01-preview",
                      "location": "[parameters('location')]",
                      "properties": {
                        "workspaceId": "${azurerm_log_analytics_workspace.main.id}",
                        "logs": [
                          {
                            "category": "NetworkSecurityGroupEvent",
                            "enabled": true,
                            "retentionPolicy": {
                              "enabled": false,
                              "days": 0
                            }
                          },
                          {
                            "category": "NetworkSecurityGroupRuleCounter",
                            "enabled": true,
                            "retentionPolicy": {
                              "enabled": false,
                              "days": 0
                            }
                          }
                        ]
                      }
                    }
                  ]
                },
                "parameters": {
                  "location": {
                    "value": "[field('location')]"
                  },
                  "nsgName": {
                    "value": "[field('name')]"
                  }
                }
              }
            }
          }
        }
  }
  POLICY_RULE
}

 resource "azurerm_policy_assignment" "nsg" {
    name                    = "${azurerm_policy_definition.nsg-policy.name} - assignment"
    scope                   = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
    policy_definition_id    = "${azurerm_policy_definition.nsg-policy.id}"
    description             = "Policy Assignment to check NSGs for diagnostics configuration"
    display_name            = "${azurerm_policy_definition.nsg-policy.name} Assignment"
    location                = "centralus"

    identity {
        type = "SystemAssigned"
    }

    depends_on = ["azurerm_policy_definition.nsg-policy"]
}
```

### Expected Behavior

When I create a policy assignment through the Portal on the same policy, it creates the identity with the appropriate permissions:

![image](https://user-images.githubusercontent.com/3587481/60301478-bfdbc400-98ee-11e9-9aa0-58e5bfec10a9.png)

### Actual Behavior

The assignment created by my terraform creates the following:

![image](https://user-images.githubusercontent.com/3587481/60301389-78edce80-98ee-11e9-987f-1e719b502b31.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lpohel** [comment]
👍

**Comment by pingwu90** [comment]
👍

**Comment by sean-keane25** [comment]
This issue still exists in the latest provider.azurerm v2.20.0 . 

This MSFT doc discuss the step to configure the managed identify via portal or powershell but doesn't cover how to accomplish it via REST API.

https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources#manually-configure-the-managed-identity

**Comment by flobeier** [comment]
The issue still exists.

**Comment by jkroepke** [comment]
I get this issue, too.

I want to create a "deployIfNotExists" policy through terraform from the documentation. https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale

The policy is created, alle parameters have a "strongType" are empty. If I have to reset the value inside the UI, then the policy is working.

**Comment by tombuildsstuff** [comment]
Permissions can be assigned using [the `azurerm_role_assignment` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment) - where the Principal ID would be the Principal ID from the Identity block of the Policy Assignment - as such this is possible in Terraform and I'm going to close this issue for the moment.

Thanks!
