### ISSUE TITLE
Cannot create AKS cluster with Windows worker nodes

### ISSUE THREAD

**Issue by SviataslauDauhuchyts** [terraform-providers/terraform-provider-azurerm#3751]
### Terraform (and AzureRM Provider) Version
Terraform v0.12.3
- provider.azurerm v1.30.1

### Affected Resource(s)
azurerm_kubernetes_cluster

### Terraform Configuration Files
```
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "${var.aks_cluster_name}"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  dns_prefix          = "${var.aks_dns_prefix}"

  agent_pool_profile {
    name            = "${var.linux_pool_name}"
    count           = "${var.linux_pool_count}"
    vm_size         = "${var.linux_pool_vm_size}"
    os_disk_size_gb = "${var.linux_pool_os_disk_size}"
    vnet_subnet_id  = "${var.subnet_id}"
    os_type         = "Linux"
    type            = "VirtualMachineScaleSets"
  }

  agent_pool_profile {
    name            = "${var.windows_pool_name}"
    count           = "${var.windows_pool_count}"
    vm_size         = "${var.windows_pool_vm_size}"
    os_disk_size_gb = "${var.windows_pool_os_disk_size}"
    vnet_subnet_id  = "${var.subnet_id}"
    os_type         = "Windows"
    type            = "VirtualMachineScaleSets"
  }

  linux_profile {
    admin_username = "${var.linux_pool_admin_user}"

    ssh_key {
      key_data = "${var.linux_pool_admin_key}"
    }
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = "${azurerm_log_analytics_workspace.workspace.id}"
    }
  }

  network_profile {
    network_plugin = "azure"
  }

  role_based_access_control {
    enabled = true
  }

  service_principal {
    client_id     = "${var.service_principal_id}"
    client_secret = "${var.service_principal_secret}"
  }

  kubernetes_version = "${var.k8s_version}"
}

resource "azurerm_log_analytics_workspace" "workspace" {
  name                = "sw-monitoring"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  sku                 = "Standard"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "solution" {
  solution_name         = "ContainerInsights"
  location              = "${azurerm_resource_group.rg.location}"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  workspace_resource_id = "${azurerm_log_analytics_workspace.workspace.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.workspace.name}"

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}
```

### Expected Behavior
AKS cluster created with Kubernetes version 1.14.0 and two VMSS node pools. One pool contains Linux worker nodes the other contains Windows worker nodes.

### Actual Behavior
Cluster is not created. Terraform throws an error during the creation process.

### Crash Output
```
Error creating/updating Managed Kubernetes Cluster "..." (Resource Group "..."): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="OSType Windows is not supported for managed cluster." Target="agentPoolProfile.osType"
```

### References
Used [this](https://docs.microsoft.com/en-us/azure/aks/windows-container-cli) article as a reference.
Managed to create cluster with the same configuration using Azure CLI.
[This](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#os_type) article mentions the possibility to create Windows worker nodes.

**Comment by 0x53A** [comment]
just as a note for anyone who finds this through google etc:

Afaik this should be fixed by PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/3519

**Comment by jluk** [comment]
This is related to other multiple agent pool issues in that currently, AKS requires additional agent pools to be added to the cluster after it is initially created. On the service side we have backlogged to ability to create all pools and the cluster together, targeting this Winter.

**Comment by tombuildsstuff** [comment]
hey @SviataslauDauhuchyts @0x53A 

Thanks for opening this issue.

Since #3519 has been merged and released, based on @jluk's comment I believe there's two remaining issues here:

1. AKS doesn't yet support upfront provisioning of multiple node pools for Windows Agents
2. Terraform doesn't support dynamically adding and removing node pools without re-creating the cluster (which is being tracked in #3971)

The first issue is out of our hands - but I believe that fixing the second one should allow Terraform to work around this API Limitation in the interim. As such I'm going to close this issue in favour of #3971 - would you mind subscribing to that issue for updates?

Thanks!
