### ISSUE TITLE
Applying taint via terraform template

### ISSUE THREAD

**Issue by smuthusa** [terraform-providers/terraform-provider-azurerm#3753]
I am creating Azure AKS cluster with multiple agentpools using terraform. I have gone through the documents and not able to find a way to set taint for the nodes in the agentpool. Any help would be greatly appreciated.

**Comment by jluk** [comment]
I think this is a new support needed in Terraform by consuming the 2019-06-01 AKS API version. We support defining taints that should persist on nodes in a nodepool not only on initial pool creation, but also to apply it for new nodes upon scale out of the pool.

The swagger for this availability is here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-06-01/managedClusters.json#L1418

**Comment by smuthusa** [comment]
Thanks jluk, I will raise a new feature request.
