### ISSUE TITLE
storage account kind "FileStorage" causes an Error

### ISSUE THREAD

**Issue by andyt530** [terraform-providers/terraform-provider-azurerm#3756]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

py-az2tf AndyT$ terraform -v
Terraform v0.12.2
 provider "azurerm" (terraform-providers/azurerm) 1.31.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl

resource azurerm_storage_account rg-test-at__strpfile {
         name = "strpfile"
         location = "uksouth"
         resource_group_name = "rg.test.at"
         account_tier = "Premium"
         account_kind = "FileStorage"
         account_replication_type = "LRS"
         enable_blob_encryption = true
         enable_file_encryption = true
         enable_https_traffic_only = true
         account_encryption_source = "Microsoft.Storage"
}

```

### Panic Output
terraform validate

Error: expected account_kind to be one of [Storage BlobStorage StorageV2], got FileStorage

  on azurerm_storage_account.rg-test-at__strpfile.tf line 1, in resource "azurerm_storage_account" "rg-test-at__strpfile":
   1: resource azurerm_storage_account rg-test-at__strpfile {

Error Validating

### Expected Behavior

"FileStorage" is a new Azure Premium Files storage kind and should not Error 
### Steps to Reproduce

terraform validate

### References

* #0000

**Comment by MattMencel** [comment]
Hey @andyt530... I just put in a PR for this a couple days ago...

#3750
