### ISSUE TITLE
Terraform Crash when no certificate_permissions present

### ISSUE THREAD

**Issue by civascu** [terraform-providers/terraform-provider-azurerm#376]
For an older tf file that creates a KeyVault but does not specify a certificate_permissions key, tf crashes when trying to compute the plan. 

Since the certificate_permissions node is a new one, and optional, this should work. In addition, even having a node will fail when the count of permissions for the key and certificates is different, due to a code bug - it uses the Permissions.Keys property to compute the list of permissions for the certificates

### Terraform Version
Terraform v0.10.5

### Affected Resource(s)
- azurerm_key_vault

### Terraform Configuration Files
Excerpt from a larger .tf file: 
```hcl
resource "azurerm_key_vault" "test-kv" {
  location = "southeastasia"
  name = "test-kv"
  resource_group_name = "kv-group"
  "sku" {
    name = "standard"
  }
  tenant_id = "${data.azurerm_client_config.current.tenant_id}"
  
  access_policy {
    key_permissions = ["encrypt"]
    object_id = "${var.sp_obj_id}"
    secret_permissions = ["get"]
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
  }
}
```

### Panic Output
https://gist.github.com/civascu/4d0151574944503a0c2d25da6b6ec850

### Expected Behavior
terraform plan to complete

### Actual Behavior
Terraform crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
PR that fixes the issue: https://github.com/terraform-providers/terraform-provider-azurerm/pull/374

**Comment by tombuildsstuff** [comment]
Fixed via #374 (thanks for this issue + sending the PR to fix it 😄)
