### ISSUE TITLE
Updating an app service with an access restriction rule involving a VNet crashes

### ISSUE THREAD

**Issue by midgleyc** [terraform-providers/terraform-provider-azurerm#3760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.14
+ provider.azurerm v1.30.1

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

Create an app service with an access restriction rule using a VNet, then run any terraform command that updates the app service.

```hcl
resource "azurerm_app_service" "test" {
  name  = "example-app-service"
  location = "West Europe"
  tags = {
      update = "${timestamp()}"
  }
}
```

### Debug Output

https://gist.github.com/midgleyc/4bc1f27e61a696bc3c5210b28437e9a7

### Expected Behavior

Terraform should apply my changes, ignoring the access restrictions.

### Actual Behavior

Terraform deletes all app services from the state, then crashes.

### Steps to Reproduce

Create an app service with an access restriction rule using a VNet. Import it (this works fine). Create a configuration file that will update the app service, then apply it.

### Notes

The ipSecurityRestriction section for VNets looks like
```
    "ipSecurityRestrictions": [
      {
        "vnetSubnetResourceId": "/subscriptions/<GUID>/resourceGroups/<resourceGroup>/providers/Microsoft.Network/virtualNetworks/<network>/subnets/<subnet>",
        "action": "Allow",
        "tag": "Default",
        "priority": 1,
        "name": "vnet"
      }
    ],
```
This doesn't have an "ipAddress" key, so it fails the existing "ip_restriction" schema (which parses the IP Access Restriction well enough that Terraform doesn't crash). This currently shows up in the state as
```
                            "site_config.0.http2_enabled": "true",
                            "site_config.0.ip_restriction.#": "1",
                            "site_config.0.java_container": "",
```

### References

This is like #3685, but while that wants a complete support of App Restrictions, I just want to be able to apply my configuration without removing and re-adding the VNet access restriction. This is also like #2488, but that one is about not breaking existing IP Address restrictions.

**Comment by mbfrahry** [comment]
Hey @midgleyc, thanks for opening this issue. The crash has been found and fixed with #4184. Feel free to reopen this issue if you continue to experience problems after 1.34.0 goes out
