### ISSUE TITLE
Support for 'UltraSSDEnabled' flag for a VM

### ISSUE THREAD

**Issue by normseq** [terraform-providers/terraform-provider-azurerm#3765]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to be able to map UltraSSD disks to a VM , the VM needs to be created with the ultra-ssd-enabled flag in CLI

az vm create --subscription $subscription -n $vmname -g $rgname --image Win2016Datacenter **--ultra-ssd-enabled** --zone $zone --authentication-type password --admin-password $password --admin-username $user --attach-data-disks $diskname --size Standard_D4s_v3 --location $location

Without this property set, mapping an UltraSSD disk to a VM results in the following error
_"Error: Error updating Virtual Machine "ultravm01" (Resource Group "ultraRG") with Disk "ultravm01-disk1": compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="StorageAccountType UltraSSD_LRS can be used only when additionalCapabilities.ultraSSDEnabled is set." Target="managedDisk.storageAccountType"_

### New or Affected Resource(s)

- azurerm_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine" "ultravm" {
    name                  = "ultravm01"
    resource_group_name   = "${azurerm_resource_group.ultragroup.name}"
    network_interface_ids = ["${azurerm_network_interface.ultravmnic.id}"]
    additional_capabilities {
        ultra_ssd_enabled = true
    }

```

### References
**CLI**
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disks-enable-ultra-ssd
**Property details**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.additionalcapabilities.ultrassdenabled?view=azure-dotnet

* #0000

**Comment by venkey1000** [comment]
Hi, 
I am working on this.
