### ISSUE TITLE
Azure Key Vault IP Rules override by 'Allow Access from' set to All networks

### ISSUE THREAD

**Issue by esuico** [terraform-providers/terraform-provider-azurerm#3774]
The issue I'm running into is that when I'm whitelisting IP addresses that have access to a instance of Azure Key Vault provisioned by Terraform, in the GUI under Settings -> Firewalls and virtual networks -> Allow access from: All networks is set, therefore overriding the IP rules that are defined as part of provisioning. When setting the radio button in the GUI to Selected networks, only then do the IP_rules populate under the Firewall section.

By setting the IP_rules value, it should also set the **Allow access from** to Selected Networks so that the settings of the whitelisting are taking into effect.

**Comment by visokoo** [comment]
We can close this issue now. Just tested it with the latest provider and everything checks out.

**Comment by ausfestivus** [comment]
Hey @esuico since this issue is opened by you, can you please close it per advice from @visokoo.

Failing that, maybe @katbyte can do it?
