### ISSUE TITLE
Error: IP Configuration "azurerm_network_interface_backend_address_pool_association" was not found on Network Interface "azurerm_network_interface"

### ISSUE THREAD

**Issue by tao-zhang** [terraform-providers/terraform-provider-azurerm#3794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terfarom: 0.12.1
AzureRM Provider: 1.31.0

### Affected Resource(s)

* `azurerm_network_interface_backend_address_pool_association`
* `azurerm_network_interface`

### Terraform Configuration Files

```hcl
resource "azurerm_lb_backend_address_pool" "lb_pool" {
  resource_group_name = "${var.resource_group_name}"
  loadbalancer_id     = "${azurerm_lb.alb.id}"
  name                = "${azurerm_lb.alb.name}-backend-pool"
}

resource "azurerm_network_interface_backend_address_pool_association" "lb_pool_assocication_bs1" {
  ip_configuration_name   = "${module.vm_bs1.host_name}-lb-pool-association"
  network_interface_id    = "${module.vm_bs1.nic_id}"
  backend_address_pool_id = "${azurerm_lb_backend_address_pool.lb_pool.id}"
}
```

### Expected Behavior

No error

### Actual Behavior

Error: Error: IP Configuration "ck-acc-bs1-lb-pool-association" was not found on Network Interface "ck-acc-bs1-nic" (Resource Group "vx-uat-rg")

  on main.tf line 60, in resource "azurerm_network_interface_backend_address_pool_association" "lb_pool_assocication_bs1":
  60: resource "azurerm_network_interface_backend_address_pool_association" "lb_pool_assocication_bs1" 

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/azurerm/r/network_interface_backend_address_pool_association.html

**Comment by dberuben** [comment]
Tested with AzureRM Provider: 1.32.0, same Behavior

**Comment by LukeCarrier** [comment]
Is this in any way related to [the comment on the `azurerm_network_interface` resource](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#load_balancer_backend_address_pools_ids), which seems to imply that this resource doesn't work?

**Comment by carloVentrella** [comment]
Same with AzureRM Provider: 1.39.0, but using the deprecated method  `load_balancer_backend_address_pools_ids` is not working for me.
What happens is that terraform output the following error but the association is created and I am able to see the pool.

`Error: IP Configuration "rp-0-backend-pool-association" was not found on Network Interface "rp-nic-0"`

This is my configuration

```

resource "azurerm_network_interface" "rp-netw-interface" {
  name                =  nic-0"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "private_id"
    subnet_id                     = azurerm_subnet.lb-subnet.id
    private_ip_address_allocation = "Dynamic"
    load_balancer_backend_address_pools_ids = [azurerm_lb_backend_address_pool.lb-backend-pool.id]
  }

}


resource "azurerm_network_interface_backend_address_pool_association" "backend-pool-association" {
  network_interface_id    = azurerm_network_interface.rp-netw-interface.id
  ip_configuration_name   = "backend-pool-association"
  backend_address_pool_id = azurerm_lb_backend_address_pool.lb-backend-pool.id
}
```

**Comment by dc232** [comment]
I have also run into this bug via provider 2.1 
details can be found via 
https://stackoverflow.com/questions/60693850/how-do-i-connect-an-azure-vm-network-interface-into-an-azure-load-balancer-addre

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here I believe this has been fixed in the latest version of the Azure Provider and as such I'm going to close this issue for the moment - however if you're still seeing this on the latest version of the Azure Provider (v2.33 at the time of writing) then please let us know and we can take another look here.

Thanks!

**Comment by tao-zhang** [comment]
Yes, I have upgraded to latest Azure provider, it's working now.
