### ISSUE TITLE
Dynamic threshold support for monitor metric alert

### ISSUE THREAD

**Issue by Djiit** [terraform-providers/terraform-provider-azurerm#3796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to be able to set a dynamic threshold on the `azurerm_monitor_metric_alert`. For now we can only set a static (numeric) threshold.

### New or Affected Resource(s)

* azurerm_monitor_metric_alert

**Comment by nexxai** [comment]
I don't know Go myself but an example of an azurerm_monitor_metric_alert could look like:

```hcl
resource "azurerm_monitor_metric_alert" "test" {
[...]
  threshold {
    type = "Dynamic"
    sensitivity = "High"
    ignore {
      before_date = "12/31/2009"
      before_time = "5:57 PM"
    }
  }
[...]
```

or 

```hcl
resource "azurerm_monitor_metric_alert" "test" {
[...]
  threshold {
    type = "Static"
  }
[...]
```
Where:
* "threshold" is _optional_
* "threshold.type" defaults to "Static" to avoid breaking existing implementations
* "threshold.type" is one of: "Static", or "Dynamic"
* "threshold.sensitivity" is mandatory if "threshold.type" = "Dynamic"
* "threshold.sensitivity" is one of: "High", "Medium" or "Low"
* "threshold.ignore" is _optional_

Thoughts?

**Comment by mholttech** [comment]
Any Update on this?

**Comment by BartoszDopke** [comment]
I also wait for this feature.

**Comment by AdamCoulterOz** [comment]
This is an example on how this could be implemented, following the Azure API... 4 additional attributes on the criteria block, and it will remain backwards compatible with people already using this resource type.

The Azure GoSDK client already exists to support these fields also. Can we understand what would be required to get this work done? Thanks! :-)

```hcl
// existing example of resource copied from terraform provider docs:
resource "azurerm_monitor_metric_alert" "example" {
  name                = "example-metricalert"
  resource_group_name = azurerm_resource_group.main.name
  scopes              = [azurerm_storage_account.to_monitor.id]
  description         = "Action will be triggered when Transactions count is greater than 50."

  criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts"
    metric_name      = "Transactions"
    aggregation      = "Total"
    operator         = "GreaterThan" // Add GreaterOrLessThan option
    threshold        = 50

    // Additional 4 attributes to add to criteria block to support dynamic thresholds
    type = "Static|Dynamic" // default "Static" (prevents breaking existing uses)
    sensitivity = "Low|Medium|High" // Static=not_allowed, Dynamic=required
    failing_periods = number // Static=not_allowed, Dynamic=required
    ignore_data_before = timestamp() // Static=not_allowed, Dynamic=optional

    dimension {
      name     = "ApiName"
      operator = "Include"
      values   = ["*"]
    }
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id
  }
}
```

**Comment by mholttech** [comment]
There's already been some work on this over on #7159

**Comment by magodo** [comment]
As #7159 has been merged, closing this issue for now.
