### ISSUE TITLE
Support Azure Networking Application Security Groups 

### ISSUE THREAD

**Issue by alexwo** [terraform-providers/terraform-provider-azurerm#380]
Microsoft has released the ASG - Azure Networking Application Security Groups to be available for preview on westcentralus region.
https://docs.microsoft.com/en-us/azure/virtual-network/create-network-security-group-preview
This feature allows filtering network traffic with network and application security groups based.

New Apis / changes:
application security group:
az network asg create
--resource-group myResourceGroup
--name WebServers
--location westcentralus
network security group:
az network nsg create
--resource-group myResourceGroup
--name myNsg
--location westcentralus

network nsg rule:
--resource-group myResourceGroup
--nsg-name myNsg
--name DatabaseRule
--priority 400
--access "Allow"
--direction "inbound"
--source-asgs "AppServers"
--destination-asgs "DatabaseServers"
--destination-port-ranges 1336
--protocol "TCP"

network nic:
--resource-group myResourceGroup
--name myNic2
--vnet-name myVnet
--subnet mySubnet
--network-security-group myNsg
--location westcentralus
--application-security-groups "AppServers"

We are very interested in having support for this new abilities as part of the Microsoft Azure terraform provider. This feature is essential for us and for many scenarios that require the deployment of VM clusters that share the same security concerns.

Thanks,
Alex

**Comment by tombuildsstuff** [comment]
Hey @alexwo 

Thanks for opening this issue :)

This has been previously requested in #369 - as such I'm going to close this issue in favour of the original, rather than having multiple tracking the same thing :)

Thanks!
