### ISSUE TITLE
Bumping API version for devspace resource

### ISSUE THREAD

**Issue by solacens** [terraform-providers/terraform-provider-azurerm#3805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.2
+ provider.azuread v0.4.0
+ provider.azurerm v1.31.0
```

### Affected Resource(s)

* `azurerm_devspace_controller`

### Terraform Configuration Files

```hcl
    name                = "${local.aks_dev_space_name}"
    location            = "southeastasia"
    resource_group_name = "${azurerm_resource_group.rg.name}"

    sku {
        name = "S1"
        tier = "Standard"
    }

    host_suffix                              = "${local.aks_dev_space_name_host_suffix}"
    target_container_host_resource_id        = "${azurerm_kubernetes_cluster.k8s.id}"
    target_container_host_credentials_base64 = "${base64encode(azurerm_kubernetes_cluster.k8s.kube_config_raw)}"

    tags                = "${var.tags}"
```

### Panic Output

```
Error: Error creating DevSpace Controller "xxxxxxxxxxx" (Resource Group "xxxxxxxxxx"): devspaces.ControllersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'southeastasia' and API version '2018-06-01-preview' for type 'controllers'. The supported api-versions are '2019-04-01'. The supported locations are 'eastus, canadaeast, westeurope, canadacentral, centralus, westus2, westcentralus, southeastasia, eastus2, northeurope, australiaeast, uksouth'."
```

### Steps to Reproduce

1. `terraform apply`

**Comment by solacens** [comment]
Seems the `2018-06-01-preview` cannot support southeastasia at the moment. Please bump the version 😀

**Comment by nexxai** [comment]
Submitted PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/4288
