### ISSUE TITLE
azurerm_virtual_machine_scale_set: image_data disk: docs say size is optional unless empty....

### ISSUE THREAD

**Issue by lrosenman** [terraform-providers/terraform-provider-azurerm#3808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

[I] ➜ terraform -v
Terraform v0.11.14
+ provider.azurerm v1.31.0
+ provider.null v2.1.2
### Affected Resource(s)

* `azurerm_virtual_machine _scale_set`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
```
resource "azurerm_virtual_machine_scale_set" "osrm" {
  name                = "osrm"
  location              = "${data.azurerm_resource_group.wherefor-vpc.location}"
  resource_group_name   = "${data.azurerm_resource_group.wherefor-vpc.name}"

  # automatic rolling upgrade
  automatic_os_upgrade = false
  upgrade_policy_mode  = "Manual"


  sku {
    name     = "Standard_E16s_v3"
    capacity = 2
  }

  storage_profile_image_reference {
  # temporary till HashiCorp fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/3800
	id = "/subscriptions/30e95a3d-74e7-489c-a2ba-2a39d9c772ec/resourceGroups/packerssd/providers/Microsoft.Compute/images/osrm-ssd-v5.22.0"
	#id = "/subscriptions/30e95a3d-74e7-489c-a2ba-2a39d9c772ec/resourceGroups/packerwork/providers/Microsoft.Compute/images/osrm-ssd-v5.22.0"
	#id = "/subscriptions/30e95a3d-74e7-489c-a2ba-2a39d9c772ec/resourceGroups/packerwork/providers/Microsoft.Compute/images/osrm-v5.22.0"
	#id = "${azurerm_image.osrm-image.id}"
  }

  storage_profile_os_disk {
    name              = ""
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Premium_LRS"
  }

 storage_profile_data_disk {
   lun           = 0
  caching       = "ReadWrite"
  create_option = "FromImage"
    managed_disk_type = "Premium_LRS"
    disk_size_gb = 25

  }
  storage_profile_data_disk {
    lun           = 1
    caching       = "ReadOnly"
    create_option = "FromImage"
    managed_disk_type = "Premium_LRS"
    disk_size_gb = 400
  }
  identity {
    type = "SystemAssigned"
    identity_ids = ["${azurerm_user_assigned_identity.w2-validator.id}]"]
  }

  os_profile {
    computer_name_prefix = "osrm-"
    admin_username       = "ubuntu"
    custom_data = "#!/bin/bash\n/etc/cloud-boot/user_boot.sh\n"
  }

  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys = [{
      path = "/home/ubuntu/.ssh/authorized_keys"
      key_data = "<elided>"
    }]
  }

  network_profile {
    name    = "osrm-config"
    primary = true

    ip_configuration {
      name               = "osrm"
      primary            = true
      subnet_id          = "${data.azurerm_subnet.WhereForV2_admin.id}"
    }
  }

  tags = {
    environment = "production"
  }
}
```
### Expected Behavior
data disk created with the size from the captured image.

### Actual Behavior

1 error occurred:
	* azurerm_virtual_machine_scale_set.osrm: 1 error occurred:
	* azurerm_virtual_machine_scale_set.osrm: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The value '0' of parameter 'dataDisk.diskSizeGB' is out of range. Value '0' must be between '1' and '32767' inclusive." Target="dataDisk.diskSizeGB"
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
👋 

At this point in time the older `azurerm_virtual_machine_scale_set` resource has been superseded by the `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources. Since the older `azurerm_virtual_machine_scale_set` resource has fallen out of sync from the behaviour of the Azure API, to avoid unintentionally breaking users relying on this behaviour the older resources are feature-frozen.

As this resource is feature-frozen to maintain compatibility, I'm going to close this issue for the moment - but I'd recommend instead checking out the `azurerm_linux_virtual_machine_scale_set` resource, which better represents how the Azure API behaves for this resource.

Thanks!
