### ISSUE TITLE
Network_rules section doesn't work with Function App

### ISSUE THREAD

**Issue by dariuszparzygnat** [terraform-providers/terraform-provider-azurerm#3816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- terraform: 0.12.3
- azurerm: 1.28.0
### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

file.tf
```hcl
provider "azurerm" {
  version = "=1.28.0"
}

resource "azurerm_resource_group" "my_rg" {
  name     = "${var.testprefix}${var.prefix}${var.resource_group_name}"
  location = "${var.region}"
}

resource "azurerm_storage_account" "my_storage" {
  name                     = "${var.testprefix}${var.storage_account_name}"
  resource_group_name      = "${azurerm_resource_group.my_rg.name}"
  location                 = "${azurerm_resource_group.my_rg.location}"
  account_tier             = "Standard"
  account_replication_type = "${var.storage_replication_type}"
  account_kind 			   = "${var.storage_account_kind}"
  
  network_rules {
    ip_rules                   = "${var.ipranges}"
	bypass 					   = ["AzureServices"]
  }
}

resource "azurerm_app_service_plan" "my_sp" {
  name                = "${var.testprefix}${var.function_app_name}plan"
  location            = "${azurerm_resource_group.my_rg.location}"
  resource_group_name = "${azurerm_resource_group.my_rg.name}"
  kind                = "FunctionApp"

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "my_funcapp" {
  name                      = "${var.testprefix}${var.function_app_name}"
  location                  = "${azurerm_resource_group.my_rg.location}"
  resource_group_name       = "${azurerm_resource_group.my_rg.name}"
  app_service_plan_id       = "${azurerm_app_service_plan.my_sp.id}"
  storage_connection_string = "${azurerm_storage_account.my_storage.primary_connection_string}"
  version 					= "~2"

}

resource "azurerm_storage_table" "my_table" {
  name                 = "xtable"
  resource_group_name  = "${azurerm_resource_group.my_rg.name}"
  storage_account_name = "${azurerm_storage_account.my_storage.name}"
}

resource "azurerm_storage_container" "my_container" {
  name                  = "xcontainer"
  resource_group_name   = "${azurerm_resource_group.my_rg.name}"
  storage_account_name  = "${azurerm_storage_account.my_storage.name}"
  container_access_type = "container"
}
```
file.variables.tf
```hcl
variable "prefix" {
	default = "x"
}
variable "region" {
	default = "West Europe"
}
variable "resource_group_name" {
	default = "MY-RG"
}
variable "function_app_name" {
	default = "my-app"
}
variable "storage_account_name" {
	default = "mystore" 
}
variable "storage_replication_type" {
	default = "LRS"
}
variable "storage_account_kind" {
	default = "StorageV2"
}
variable "testprefix" {
	default = ""
}

variable "ipranges" {
	default = ["132.144.185.0/23"]
}
```

### Expected Behavior

A resource group, together with a storage, an app service plan and a function app are created. 

### Actual Behavior

After a resource group, a storage and an app service plan are created then the following error arises:
`Error: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="There was a conflict. The remote server returned an error: (403) Forbidden." Details=[{"Message":"There was a conflict. The remote server returned an error: (403) Forbidden."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01020","Message":"There was a conflict. The remote server returned an error: (403) Forbidden.","MessageTemplate":"There was a conflict. {0}","Parameters":["The remote server returned an error: (403) Forbidden."]}}]`

### Steps to Reproduce

1. `terraform plan` - it works
2. `terraform apply` - it ends up with the error

### Important Factoids

When I've removed the section network_rules it works correctly. It looks like a new function app can't connect to the storage because of ip limitations.

**Comment by pather87** [comment]
This is not a terraform bug, function apps are not granted access when bypass "AzureServices" is active. See https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security#exceptions

**Comment by tombuildsstuff** [comment]
hey @dariuszparzygnat

Thanks for opening this issue - apologies for the delayed response here!

As @panther87 has mentioned unfortunately this appears to be an Azure Limitation where Function Apps isn't supported by the `AzureServices` configuration option; as such whilst it's not ideal you should be able to allow the IP Addresses being used by the Function App (which are exported fields from the `azurerm_function_app` resource) to connect to Azure Storage instead.

Since this is a question regarding Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment.

Thanks!
