### ISSUE TITLE
Feature Request: Azure Bastion

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#3829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for [Azure Bastion](https://docs.microsoft.com/en-us/azure/bastion/bastion-create-host-portal) service.

### New or Affected Resource(s)

* azurerm_bastion

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "testvnet"
  address_space       = ["192.168.1.0/24"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet" "test" {
  name                 = "AzureBastionSubnet"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "192.168.1.224/27"
}

resource "azurerm_public_ip" "test" {
  name                = "testpip"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_bastion" "test" {
  name                = "testbastion"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  ip_configuration {
    name                 = "configuration"
    subnet_id            = "${azurerm_subnet.test.id}"
    public_ip_address_id = "${azurerm_public_ip.test.id}"
  }
}

```

### References

* [Azure Bastion Documentation
](https://docs.microsoft.com/en-us/azure/bastion/)
* [Create an Azure Bastion host](https://docs.microsoft.com/en-us/azure/bastion/bastion-create-host-portal)
* [Preview announcement](https://azure.microsoft.com/en-us/updates/azure-bastion-now-available-for-preview/)

**Comment by JamesDLD** [comment]
For info, the following module creates the Azure bastion through an ARM template : https://github.com/JamesDLD/terraform/tree/master/module/Az-Bastion

**Comment by DanielMabbett** [comment]
I have noticed an issue with the AGS (Azure GO SDK) where the Struct for Bastion Host is not being converted to an acceptable json file for the put request: 
https://github.com/Azure/azure-sdk-for-go/issues/5233

Essentially, the JSON is missing the "Name" section for the ipconfiguration block:
```json
 "properties":{"ipConfigurations":[{"name":"thisismissing",.....}]
```
I have also created a PR that would fix this issue. Hopefully that gets added to the AGS
