### ISSUE TITLE
Please add support for multiple NIC to azurerm_virtual_machine_scale_set

### ISSUE THREAD

**Issue by dcaro** [terraform-providers/terraform-provider-azurerm#383]
The current implementation of the azure_rm_virtual_machine_scale_set does not allow to have multiple nic. It seems to be related to the PR that was pending: https://github.com/Azure/azure-sdk-for-go/pull/768 

### Terraform Version
- Terraform v0.10.6 
- AzureRM Provider v0.2.2

### Affected Resource(s)

- azurerm_virtual_machine_scale_set

### Debug Output
https://gist.githubusercontent.com/dcaro/62a20156cf5bb4722412eb4c11bb086a/raw/592000fe9972092e7061d3f1259f26b06ebcb323/TF-multiplenic

### Expected Behavior
Create a VM scale set with several interfaces

### References

- #160 
- #339

**Comment by tombuildsstuff** [comment]
Hey @dcaro 

Thanks for opening this issue :)

This should be fixed once PR #367 is merged - PR #378 adds a test case for multiple NIC's on a VM Scale Set.

Thanks!

**Comment by tombuildsstuff** [comment]
Fixed via #378
