### ISSUE TITLE
Support for Microsoft.TimeSeriesInsights

### ISSUE THREAD

**Issue by xtellurian** [terraform-providers/terraform-provider-azurerm#3844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Time Series Insights](https://docs.microsoft.com/en-gb/azure/time-series-insights/) is an Azure Resource that cannot be created via Terraform. It could be a supported resource. ~~However, it is not well supported by Microsoft at this time, as it cannot be created via an ARM template~~.

### New or Affected Resource(s)

* azurerm_time_series_insights

### References

* TSI Docs: https://docs.microsoft.com/en-gb/azure/time-series-insights/

**Comment by tombuildsstuff** [comment]
hey @xtellurian 

Thanks for opening this issue :)

Just to add some additional information here: the [documentation for this API is available here](https://docs.microsoft.com/en-us/rest/api/time-series-insights/) and [the Go SDK appears to support this](https://github.com/Azure/azure-sdk-for-go/tree/master/services/timeseriesinsights/mgmt/2017-11-15/timeseriesinsights). Would you be able to provide some more details on the kinds of functionality you're looking for Terraform to support here?

Thanks!

**Comment by xtellurian** [comment]
Hey @tombuildsstuff 

As a start, we really only need basic Create, Update, and Delete options for Time Series Insights Environments. 

My `go` skills aren't great, but if I get some time I might try creating a TSI environment using the Azure Go SDK as you suggested. If it's possible (and it looks like it is) then I believe it's possible for Terraform to support this as a **Resource**

**Comment by xtellurian** [comment]
FYI I was wrong above when I said 

> it cannot be created via an ARM template.

TSI can be created by ARM templates 👍

**Comment by BarbaraGoeller-AIT** [comment]
Hi,
we are also interested in deploying TSI via Terraform. Are there any news on this?

Best regards
Barbara
