### ISSUE TITLE
examples should be converted to 0.12 syntax

### ISSUE THREAD

**Issue by PavelSlepushkin** [terraform-providers/terraform-provider-azurerm#3845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Examples should be converted to 0.12 syntax.
Now  with terraform binary (for example with examples/virtual-machines/provisioners/linux) I'm getting
```
terraform version                                                                                       
Terraform v0.12.4                                                    
+ provider.azurerm v1.31.0   
..
terraform validate 
                                  
                                                                                                                     Error: Missing required argument                                                                                      
                                                                         
  on main.tf line 37, in resource "azurerm_virtual_machine" "example":                                                  37:     connection {                                                                                  
                                                                         
The argument "host" is required, but no definition was found.       
```
Simple conversion isn't helping in this case, after
terraform 0.12upgrade in main.tf there are
```hcl
  provisioner "remote-exec" {
    connection {
      host     = ""    # TF-UPGRADE-TODO: Set this to the IP address of the machine's primary network interface
      type     = "ssh" # TF-UPGRADE-TODO: If this is a windows instance without an SSH server, change to "winrm"
      user     = local.admin_username
      password = local.admin_password
    }

```

### New or Affected Resource(s)

* examples/virtual-machines/provisioners/linux, possible all examples directory

**Comment by immae1** [comment]
how can i use remote exec ? Whats the correct param for host ?  	  
`host = "${azurerm_public_ip.mypublicip.ip_address}"`
 
i always see that the host is empty if i try the above mentioned params. Could some one help?

**Comment by tombuildsstuff** [comment]
Closing since this was done as a part of the 2.x work, so these should all be updated
