### ISSUE TITLE
Feature request: data source for azurerm_network_ddos_protection_plan

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#3851]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure only allow one DDoS Protection Plan per region. 

### New or Affected Resource(s)

* azurerm_network_ddos_protection_plan

### Potential Terraform Configuration

```hcl
data "azurerm_network_ddos_protection_plan" "test" {
  name                = "ddospplan1"
  resource_group_name = "ddos-service"
}

output "ddos_protection_plan_id" {
  value = "${data.azurerm_network_ddos_protection_plan.test.id}"
}

```

### References

* Enable ddos protection on a vnet : https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html

**Comment by katbyte** [comment]
We should use `azurerm_network_ddos_protection_plan` as the `azurerm_ddos_protection_plan` resource has been deprecated in favour of it.
