### ISSUE TITLE
Invalid provider for azurerm_application_insights_webtest

### ISSUE THREAD

**Issue by jamie3** [terraform-providers/terraform-provider-azurerm#3853]
The application insights web tests were released in version 1.29.0 of the azurerm provider. The documentation is incorrect https://www.terraform.io/docs/providers/azurerm/r/application_insights_webtests.html.

```
resource "azurerm_application_insights_webtest" "test1" {
  #count = 0
  name                    = "test1"
  location                = "${azurerm_resource_group.appinsights.location}"
  resource_group_name     = "${azurerm_resource_group.appinsights.name}"
  application_insights_id = "${azurerm_application_insights.appinsights.id}"
  kind                    = "Ping"
  frequency               = 300
  timeout                 = 120
  enabled                 = true
  geo_locations           = ["us-tx-sn1-azr", "us-il-ch1-azr", "us-ca-sjc-azr"]
  test_configuration      = "${data.template_file.test.rendered}"
}
```

`terraform apply`

```
Error: Invalid resource type

  on main.tf line 76, in resource "azurerm_application_insights_webtest" "test":
  76: resource "azurerm_application_insights_webtest" "test" {

The provider provider.azurerm does not support resource type
"azurerm_application_insights_webtest".
```

The correct resource name should be `azurerm_application_insights_web_test` not `azurerm_application_insights_webtest`

**Comment by tombuildsstuff** [comment]
hey @jamie3 

Thanks for opening this issue :)

Taking a look at this the fix for this has already been merged in #3766 - I'm going to push a commit to fix the resource name from `azurerm_application_insights_web_tests` to `azurerm_application_insights_web_test` - but this should go out during the release later this week 👍 

Thanks!
