### ISSUE TITLE
MSSQL Server, allow access to azure services

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3862]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The UI has a toggle that enables azure services access via the firewall. This would be a useful terraform property.

### New or Affected Resource(s)

azurerm_sql_server

### Potential Terraform Configuration

allow_access_to_azure_services = true/false

### References

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-overview#a-allow-access-to-azure-services

* #0000

**Comment by tombuildsstuff** [comment]
hey @cdesewell 

Thanks for opening this issue :)

Unfortunately Azure doesn't expose a Boolean value for this - however you can configure this by using [the `azurerm_sql_firewall_rule` resource](https://www.terraform.io/docs/providers/azurerm/r/sql_firewall_rule.html) and setting the `start_ip_address` and `end_ip_address` fields to `0.0.0.0`

Thanks!
