### ISSUE TITLE
add support for specific instance count scale option and empty rules block

### ISSUE THREAD

**Issue by iamjaekim** [terraform-providers/terraform-provider-azurerm#3870]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

add support for static instance count mode for autoscaling. 
when i set to static instance count and checked on ARM setting, it had empty rules [ ] block with capacity block to my desire count. 

### New or Affected Resource(s)

azurerm_monitor_autoscale_setting
https://www.terraform.io/docs/providers/azurerm/r/monitor_autoscale_setting.html

### References
Image below is radio button from the portal on App service plan autoscale option
![image](https://user-images.githubusercontent.com/46606360/61463040-a18f4400-a941-11e9-805d-5ce3d9622b6e.png)

**Comment by ntmggr** [comment]
This is quite important and should be supported from day 1. If an instance is stuck and you delete it the scaleset won't be able to bring another instance unless you go and manually do it.

**Comment by al-lac** [comment]
Why is this still not supported? Please give it more priority.

**Comment by ResDiaryLewis** [comment]
We'd really like the empty rules block feature specifically here for our Virtual Machine Scale Sets. We think we've found a work-around by creating a rule that's always true, _(e.g. "Percentage CPU >= 0")_ but it's not ideal as we're not sure that the evaluation works correctly when no instances are available. Is there any update on this?

**Comment by estei** [comment]
I think I've managed to create an `azurerm_monitor_autoscale_setting` to a specific instance count without a rule block effectively giving me what I think the original poster was looking for.

```hcl
resource "azurerm_monitor_autoscale_setting" "manual" {
  name                = var.name
  resource_group_name = var.resource_group_name
  location            = var.location
  target_resource_id  = var.target_resource_id
  profile {
    name = "Manual"

    capacity {
      default = var.capacity.default
      minimum = var.capacity.minimum
      maximum = var.capacity.maximum
    }
  }
}
```

Which in the portal ended up looking like this

![image](https://user-images.githubusercontent.com/72443/103367035-5c72b980-4ac4-11eb-8161-cd0ceea2eaa6.png)

One caveat that I ran into, which might only apply to app services plans was that if you have fiddled around in the portal to try and manually set up a scaling plan, you will need to delete the "Autoscale Setting" on the json tab.

![image](https://user-images.githubusercontent.com/72443/103367312-0ce0bd80-4ac5-11eb-90c9-6c8ffca6ba5c.png)

If you don't delete this, you will be getting a lovely 409 from the rest api with not much info on what went wrong.

**Comment by ibalajiarun** [comment]
This appears to be a doc issue. The rule block is optional, but the documentation says otherwise.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/96dd941637212efeb9ef17c2f5f569e9503872ac/azurerm/internal/services/monitor/monitor_autoscale_setting_resource.go#L102
