### ISSUE TITLE
New Feature for azure postgreSQL 

### ISSUE THREAD

**Issue by vipinjain1584** [terraform-providers/terraform-provider-azurerm#3885]
Hi,

there are two new feature in Azure postgreSQL. we need to add them in Memory optimize pg instance.

   "previewFeature": {
            "value": "LargeStorage" or ""

     "storageAutoGrow": {
            "value": "Enabled" or "Disabled"

**Comment by rafa-pizzi** [comment]
Auto-grow is in GA as per 26th June
