### ISSUE TITLE
azurerm_dashboards: Create and share dashboards

### ISSUE THREAD

**Issue by arunyenumula** [terraform-providers/terraform-provider-azurerm#3887]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Requesting Terraform support for creating and sharing dashboards.
Currently we have to use ARM templates.

### New or Affected Resource(s)

* azurerm_dashboard

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

Create and share dashboards in Azure: https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards

**Comment by damoodamoo** [comment]
Hi @tombuildsstuff - is this work in progress (the `preview` tag) ?

I've just started work on this too - just checking if i've missed something that's already been done...?

**Comment by stuartleeks** [comment]
@damoodamoo I think the preview label is because the GO SDK client is preview. I chatted with @tombuildsstuff earlier and got the go-ahead for working on this with the preview client. Let's sync :-)

**Comment by damoodamoo** [comment]
Ok after chatting with @stuartleeks i'm going to continue work on this and he will guide/help when needed - this is my first work on this repo.

It feels like there are 2 approaches:
- the user populates a JSON block declaring the `properties` of the dashboard. This is nice as it's a copy+paste from the portal (where users will build the dashboards in the first place), but not nice in that it's a big JSON blob and we'd have to pass parameters in via another property like the ARM template resource. 
e.g.:
```
dashboard       = <<DASHBOARD
        "properties": {
            "lenses": {
                "0": {
                    "order": 0,
                    "parts": {
                        "0": {
                            "position": {
                                "x": 0,
                                "y": 0,
                                "rowSpan": 2,
                                "colSpan": 3
                            },
                            "metadata": {
                                "inputs": [],
                                "type": "Extension[azure]/HubsExtension/PartType/MarkdownPart",
                                "settings": {
                                    "content": {
                                        "settings": {
                                            "content": "## My cool dashboard!",
                                             ...
        }
        DASHBOARD
```
- we mimic the properties in the tf and the user re-keys the data. Nicer as it's more native-like in terraform and properties are inline, but potentially less nice for the user. 
e.g.:
```
 properties  {
            lenses  {
                order   = 0
                parts   {
                    partNo  = 0
                    position {
                        x = 1
                        y = 2
                        ...
                    }
                }
            }
        }
```

Any thoughts on the recommended approach - or if i've missed a better way?

**Comment by stuartleeks** [comment]
@tombuildsstuff - based on the discussion we had in #3316 I'm assuming that the preference is for the latter (i.e. HCL rather than JSON) - can you confirm?

**Comment by tombuildsstuff** [comment]
@stuartleeks @damoodamoo cool thanks. Taking a look at this I think it's unlikely folks are going to write these dashboards by hand, instead I think it'd likely they'll build them in the portal and then reuse them across Subscriptions; as such I think we'd be better to expose a field which takes JSON here (which can be sourced from a file) - WDYT?

**Comment by stuartleeks** [comment]
I agree that it's quite likely to not be hand generated from scratch! I suspect that a common workflow would be create in portal, export, tweak and clone sections etc
