### ISSUE TITLE
azurerm_network_connection_monitor Gets Recreated Every Run

### ISSUE THREAD

**Issue by derekrprice** [terraform-providers/terraform-provider-azurerm#3909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
PS D:\> terraform -v
Terraform v0.11.14
```

### Affected Resource(s)

* `azurerm_network_connection_monitor`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
data "external" "aks_node_ids" {
  program = [
    "Powershell.exe", "./get-resource-info.ps1",
    "-resource-group", "${data.terraform_remote_state.aks.node_resource_group}",
    "-resource-type", "Microsoft.Compute/virtualMachines",
    "-prop", "id"
  ]
}

data "external" "aks_node_names" {
  program = [
    "Powershell.exe", "./get-resource-info.ps1",
    "-resource-group", "${data.terraform_remote_state.aks.node_resource_group}",
    "-resource-type", "Microsoft.Compute/virtualMachines",
    "-prop", "name"
  ]
}

data "external" "network_watcher" {
  program = [
    "Powershell.exe", "./get-resource-info.ps1",
    "-resource-group", "NetworkWatcherRG",
    "-location", "${data.terraform_remote_state.aks.location}",
    "-resource-type", "Microsoft.Network/networkWatchers",
    "-prop", "name"
  ]
}

resource "azurerm_virtual_machine_extension" "node-network-watcher-agent" {
  count                      = "${length(data.external.aks_node_names.result)}"
  name                       = "${local.environment}-aks-node-network-watcher-${count.index}"
  location                   = "${data.terraform_remote_state.aks.location}"
  resource_group_name        = "${data.terraform_remote_state.aks.node_resource_group}"
  virtual_machine_name       = "${lookup(data.external.aks_node_names.result, count.index)}"
  publisher                  = "Microsoft.Azure.NetworkWatcher"
  type                       = "NetworkWatcherAgentLinux"
  type_handler_version       = "1.4"
  auto_upgrade_minor_version = true

  tags = "${var.tags}"
}

resource "azurerm_network_connection_monitor" "mongo-connectivity" {
  count                = "${length(data.external.aks_node_names.result)}"
  name                 = "AKS-${data.terraform_remote_state.aks.resource_group_name}-Node-to-Mongo-2"
  location             = "${data.terraform_remote_state.aks.location}"
  resource_group_name  = "NetworkWatcherRG"
  network_watcher_name = "${lookup(data.external.network_watcher.result, "0")}"

  source {
    virtual_machine_id = "${lookup(data.external.aks_node_ids.result, "2")}"
  }

  destination {
    address = "redacted.mlab.com"
    port    = "redacted"
  }

  depends_on = ["azurerm_virtual_machine_extension.node-network-watcher-agent"]

  tags = "${var.tags}"
}
```

### Expected Behavior

Should have created the resource and, on the second run, seen no required changes.

### Actual Behavior
The connection monitor resource was created correctly, but the "name" attribute was not set in the Terraform state.  On re-running `terraform apply`, Terraform wanted to destroy and recreate the original resource due to the empty "name".

### Steps to Reproduce

1. `terraform apply`
1, `terraform apply`

### Important Factoids

Running in the `centralus` region.

**Comment by vn50esu** [comment]
Hello,
I have exact the same issue, but in my case I cannot destroy the resource. I'm deploying this as a feature of an Azure Databricks Workspace and this is actually preventing the normal execution when destroying everything. I'm forced to remove the connection_monitor feature until a solution appears. 

Terraform v0.12.19
+ provider.azurerm v1.40.0

This is a fraction of the state file where you can see the resource name is empty:
`"interval_in_seconds": 60,
            "location": "southcentralus",
            "name": "",
            "network_watcher_name": "NetworkWatcher_southcentralus",
            "resource_group_name": "NetworkWatcherRG",`

This seems to cause the deletion error I've got in the NetworkWatcher activity logs:
`"status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "BadRequest",
        "localizedValue": "Bad Request (HTTP Status Code: 400)"
    },`

I would good if this issue were prioritized and fixed as soon as possible.

**Comment by neil-yechenwei** [comment]
@derekrprice, thanks for opening this issue. Seems terraform failed to parse resource id with "NetworkConnectionMonitors" since this segment is incorrect. After checked api doc, it should be ["connectionMonitors"](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/networkWatcher.json#L1975).
