### ISSUE TITLE
1.32 does not detect containers

### ISSUE THREAD

**Issue by BryceAshey** [terraform-providers/terraform-provider-azurerm#3919]
During a recent deployment it appears the azurerm updated to 1.32 (we specify ">=1.28"). That resulted in the error below deploying a container to a storage account. Reverting to 1.31 allows the deployment to proceed (account and resource group omitted)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.30.1
+ provider.null v2.1.2
+ provider.random v2.1.2

### Affected Resource(s)

azurerm_storage_account

### Debug Output

* azurerm_storage_container.ecacdbtracker: 1 error(s) occurred:

* azurerm_storage_container.ecacdbtracker: Error creating Container "<our container name>" (Account "xxxxxxxxxxxxxx" / Resource Group "xxxxxxxxxxxxx"): containers.Client#Create: Failure sending request: StatusCode=409 -- Original Error: Error occurred unmarshalling JSON - Error = 'invalid character '<' looking for beginning of value' JSON = '<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.
RequestId:16c30ec8-601e-0006-2b54-42139c000000
Time:2019-07-24T19:19:47.2508352Z</Message></Error>'

### Expected Behavior

It should have completed without changing any resources.

### Actual Behavior

It blew up with error above.

### Steps to Reproduce

Create a storage account using version 1.31:

Resource Statement:
resource "azurerm_storage_account" "<resource name>" {
  name                      = "<container name>"
  resource_group_name       = "${data.azurerm_resource_group.dr_rg.name}"
  location                  = "${var.location}"
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  enable_blob_encryption    = "true"
  enable_file_encryption    = "true"
  account_encryption_source = "Microsoft.Storage"
  enable_https_traffic_only = "true"

  tags = {
    EnvironmentType = "${var.namespace}"
  }

1. `terraform apply`

2. Change the provider to 1.32 and do another 'terraform apply'

* #0000

**Comment by katbyte** [comment]
Hi @BryceAshey,

I have tried to reproduce this but have been unable to. Going from 1.30.1 -> 1.32.0:
```shell
[19:21:33] kt@snowbook:~/hashi/tf/gh/az-3919$ cat main.tf
provider "azurerm" {
  version = "~> 1.30.0"
}


resource "azurerm_resource_group" "test" {
  name     = "kttest-20190725-az3919"
  location = "West Europe"
}

resource "azurerm_storage_account" "test" {
  name                      = "kttestaz3919"
  resource_group_name       = "${azurerm_resource_group.test.name}"
  location                  = "${azurerm_resource_group.test.location}"
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  enable_blob_encryption    = "true"
  enable_file_encryption    = "true"
  account_encryption_source = "Microsoft.Storage"
  enable_https_traffic_only = "true"

  tags = {
    EnvironmentType = "an environment would go here"
  }
}

resource "azurerm_storage_container" "test" {
  name                  = "kttestaz3919"
  resource_group_name   = "${azurerm_resource_group.test.name}"
  storage_account_name  = "${azurerm_storage_account.test.name}"
  container_access_type = "private"
}

[19:21:36] kt@snowbook:~/hashi/tf/gh/az-3919$ tfinitautoapply

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "azurerm" (terraform-providers/azurerm) 1.30.1...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
azurerm_resource_group.test: Creating...
azurerm_resource_group.test: Creation complete after 3s [id=/subscriptions/1a6092a6-137e-4025-9a7c-ef77f76f2c02/resourceGroups/kttest-20190725-az3919]
azurerm_storage_account.test: Creating...
azurerm_storage_account.test: Still creating... [10s elapsed]
azurerm_storage_account.test: Still creating... [20s elapsed]
azurerm_storage_account.test: Creation complete after 23s [id=/subscriptions/x/resourceGroups/kttest-20190725-az3919/providers/Microsoft.Storage/storageAccounts/kttestaz3919]
azurerm_storage_container.test: Creating...
azurerm_storage_container.test: Creation complete after 2s [id=https://kttestaz3919.blob.core.windows.net/kttestaz3919]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
[19:23:19] kt@snowbook:~/hashi/tf/gh/az-3919$ vim main.tf
[19:23:38] kt@snowbook:~/hashi/tf/gh/az-3919$ tfinitautoapply

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "azurerm" (terraform-providers/azurerm) 1.32.0...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
azurerm_resource_group.test: Refreshing state... [id=/subscriptions/x/resourceGroups/kttest-20190725-az3919]
azurerm_storage_account.test: Refreshing state... [id=/subscriptions/x/resourceGroups/kttest-20190725-az3919/providers/Microsoft.Storage/storageAccounts/kttestaz3919]
azurerm_storage_container.test: Refreshing state... [id=https://kttestaz3919.blob.core.windows.net/kttestaz3919]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
[19:24:25] kt@snowbook:~/hashi/tf/gh/az-3919$
```

Could you possibly provide a debug log or other information as the config you supplied is not triggering this bug for me. Does the config above work or trigger the error for you?

thnks,
-kt

**Comment by tombuildsstuff** [comment]
hi @BryceAshey 

Thanks for opening this issue.

There's a bug in the 1.x versions of the Azure Provider where creating a resource that already exists may "adopt" it into Terraform (since the Azure API's are Upserts); the next major version of the Azure Provider (being tracked in #2807) changes the behaviour of the Provider to work around this by checking if a resource exists prior to trying to create it.

Based on the error message being returned from Azure here it appears the Storage Container already exists - and as such I believe the Storage Resources prior to v1.32 supported this "adoption" of resources or weren't correctly returning this error.

As mentioned above the next major version of the Azure Provider supports this functionality for all resources (and returns a more helpful error message) - which is supported, but feature-toggled off in the current version of the Azure Provider; and you should be able to opt-into this by setting the Environment Variable `ARM_PROVIDER_STRICT` to `true`.

If you're seeing this behaviour with a new Storage Account/Storage Container please let us know and we'll take another look - however since we've not heard back from you here I'm going to close this issue for the moment.

Thanks!
