### ISSUE TITLE
dns_a_record_set.addrs +  = error

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#3923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.14
+ provider.azuread v0.5.1
+ provider.azurerm v1.32.0
+ provider.dns v2.2.0
```
### Affected Resource(s)

* `azurerm_dns_a_record`

### Terraform Configuration Files

```hcl
data "dns_a_record_set" "google" {
  host = "www.google.com"
}
resource "azurerm_dns_a_record" "google" {
  ...
  ...
  ...
  records             = "${data.dns_a_record_set.google.addrs}"
}
```

### Expected Behavior

According to the docs, both `dns_a_record_set.addrs` and `azurerm_dns_a_record.records` are both lists of IP addresses, so I'd expect to have it working.

### Actual Behavior

```
Error: azurerm_dns_a_record.google: records: should be a list
```

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
@Leon99 , thanks for opening this issue. Seems the issue has been fixed since I can't repro this issue anymore with below tfconfig. Maybe I missed something. If you want, you can try below tfconfig to check whether the issue still exists? Thanks.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-dnsrecord-test"
  location = "eastus2"
}

resource "azurerm_dns_zone" "test" {
  name                = "acctestzonetest.com"
  resource_group_name = azurerm_resource_group.test.name
}

data "dns_a_record_set" "test" {
  host = "www.google.com"
}

resource "azurerm_dns_a_record" "test" {
  name                = "myarecordtest"
  resource_group_name = azurerm_resource_group.test.name
  zone_name           = azurerm_dns_zone.test.name
  ttl                 = 300
  records             = data.dns_a_record_set.test.addrs
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to confirm if this is still an issue then we should be able to reopen this and take another look.

Thanks!
