### ISSUE TITLE
Upgrade to 1.32.0 breaks storage table

### ISSUE THREAD

**Issue by hbuckle** [terraform-providers/terraform-provider-azurerm#3924]
After upgrading to 1.32.0 refreshing an existing storage table fails with the error `Expected the Table Name to be in the format 'Tables('name')' but got "test"`
Creating a new storage table from scratch works

Repro: apply the following config

```hcl
provider "azurerm" {
  version = "= 1.31.0"
}

resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "uksouth"
}

resource "random_string" "test" {
  length  = 24
  upper   = false
  lower   = true
  number  = true
  special = false
}

resource "azurerm_storage_account" "test" {
  name                     = random_string.test.result
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_table" "test" {
  name                 = "test"
  resource_group_name  = azurerm_resource_group.test.name
  storage_account_name = azurerm_storage_account.test.name
}
```

The change the provider version to `1.32.0` and run apply again:

```
terraform apply -auto-approve
random_string.test: Refreshing state... [id=none]
azurerm_resource_group.test: Refreshing state... [id=/subscriptions/xxx/resourceGroups/test]
azurerm_storage_account.test: Refreshing state... [id=/subscriptions/xxx/resourceGroups/test/providers/Microsoft.Storage/storageAccounts/6zzpdiqsisr4vnw671hm32xf]
azurerm_storage_table.test: Refreshing state... [id=https://6zzpdiqsisr4vnw671hm32xf.table.core.windows.net/test]

Error: Expected the Table Name to be in the format `Tables('name')` but got "test"
```

```
terraform -v
Terraform v0.12.5
```

**Comment by kecirlotfi** [comment]
Hello
I confirm this issue on our side.
Can some one update the documentation please or help us to sort out this issue?
Thanks in advance.

**Comment by Kdecherf** [comment]
The issue seems to be related to #3834 

The construction of the id is not the same between 1.31 and 1.32. On the previous version the id is following the form `id=https://{storageaccount}.table.core.windows.net/{tablename}` whereas the new SDK uses this one: `id=https://{storageaccount}.table.core.windows.net/Tables('{tablename}')`.

Renaming the id in the tfstate or removing the whole resource and importing it seem to fix the issue seen during `terraform plan`. I don't know if it's the recommended way to work around this issue though :)

**Comment by t0klian** [comment]
> 
> 
> The issue seems to be related to #3834
> 
> The construction of the id is not the same between 1.31 and 1.32. On the previous version the id is following the form `id=https://{storageaccount}.table.core.windows.net/{tablename}` whereas the new SDK uses this one: `id=https://{storageaccount}.table.core.windows.net/Tables('{tablename}')`.
> 
> Renaming the id in the tfstate or removing the whole resource and importing it seem to fix the issue seen during `terraform plan`. I don't know if it's the recommended way to work around this issue though :)

No it won't work) I tried it and got the same 'Expected the Table Name to be in the format `Tables('blablabla')` but got "blablabla"' error when was trying to import resource back

**Comment by jungopro** [comment]
hitting the same issue. i can help with testing if needed

**Comment by mbfrahry** [comment]
Hey all, thanks for opening this issue. I just merged the fix for this that will go out in the next release. Going to close this down but feel free to reopen if you continue to have issues after the next release goes out.
