### ISSUE TITLE
The link dosent open up https://github.com/terraform-providers/terraform-provider-azurerm/pull/url

### ISSUE THREAD

**Issue by eashweragero101** [terraform-providers/terraform-provider-azurerm#3928]
looking for the documentation and terraform snippet  for aks autoscalling i see a github link in the chat but it is unable to open up getting  a 404 error ,when can we expect the terrraform documentation to be updated for auto scaling of aks(azure kubernetes)  nodes .

**Comment by katbyte** [comment]
Hi @eashweragero101,

May i ask where you found that link? as it is decidedly not correct (points to a non PR)

The documentation for AKS autoscaling can be found here: https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#enable_auto_scaling

**Comment by eashweragero101** [comment]
Thank you that was really helpfull   this is where i found it
https://github.com/terraform-providers/terraform-provider-azurerm/pull/3361

is there a github where the entire cluster is implemented with  auto
scaling


Thank you
Eashwer

**Comment by katbyte** [comment]
@eashweragero101,

We don't have anything in the examples folder yet, but you could look at the [test tf config](https://github.com/terraform-providers/terraform-provider-azurerm/blob/73f6b2bf7f2b44bdf3fa9a081fe37a87a2a6a7d8/azurerm/resource_arm_kubernetes_cluster_test.go#L1966)

As this seems to have answered your question i am going to close this issue. Please don't hesitate to reopen it if you have more questions!

**Comment by eashweragero101** [comment]
thank you for the speedy response
