### ISSUE TITLE
Add support for binding Azure Servicebus Namespace to a VNet

### ISSUE THREAD

**Issue by osudude** [terraform-providers/terraform-provider-azurerm#3930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft allows you to bind a Service Bus Namespace to a VNet so that service bus instance can not be accessed from other networks.  This is accomplished via ARM template [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-service-endpoints#binding-service-bus-to-virtual-networks).  Would be nice to be able to bypass ARM template and do this using native terraform.

**Comment by SadokLadhari** [comment]
Any news about this ! can any one give me a status please ?

**Comment by ArcturusZhang** [comment]
I am currently working on this by introducing a new resource `azurerm_servicebus_namespace_network_rule`

**Comment by andrew-kelleher** [comment]
@ArcturusZhang that's great! We have a need for this on my current project so will be good to see this implemented 👍
