### ISSUE TITLE
Error issuing create/update request for SQL server : api-version is invalid

### ISSUE THREAD

**Issue by guyjehu** [terraform-providers/terraform-provider-azurerm#3934]
Hello,

While creating a SQL server using the resource azurerm_sql_server (which worked well yesterday), I today get this error. I guess Microsoft removed the api used from the allowed list.

How can I find a workaround for that ?

 Error: Error issuing create/update request for SQL Server "xxxxxx" (Resource Group ""): sql.ServersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidApiVersionParameter" Message="The api-version '2015-05-01-preview' is invalid. The supported versions are '2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

Kind regards,

Guy Jéhu

**Comment by katbyte** [comment]
Hi @guyjehu,

May i ask what region you are using? Currently our nightly tests in west europe are not failing.

**Comment by tombuildsstuff** [comment]
hi @guyjehu 

Taking a look into the error being returned here: `Error: Error issuing create/update request for SQL Server "xxxxxx" (Resource Group ""): ` - it appears that the Resource Group name is empty. So that we can take a look into this, would it be possible to confirm the (sanitized) ID and value of the `resource_group_name` field here?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @guyjehu 

Since we've not heard back from you here I'm going to close this issue for the moment - if you're still having this issue and are able to provide the information requested above we should be able to take another look!

Thanks!
