### ISSUE TITLE
Implement Azure Netapp Files Support

### ISSUE THREAD

**Issue by sgsollie** [terraform-providers/terraform-provider-azurerm#3936]
### Description
Hi, 

With the general release of Azure Netapp Files, we'd like to see support in terraform for this.

Features and description: 
https://azure.microsoft.com/en-gb/blog/azure-netapp-files-is-now-generally-available/
https://cloud.netapp.com/azure-netapp-files

ARM template Documentation
https://docs.microsoft.com/en-us/azure/templates/microsoft.netapp/allversions

Something along the lines of the below could be useful for creating an account & a pool of storage:
```hcl
resource "azurerm_netapp_files" "account" {
  name                 = "${var.name}"
  location             = "${var.location}"
  subscription         = "${var.subscription}"
  resource_group_name  = "${var.resource_group_name}"
}

resource "azurerm_netapp_files" "capacity_pool" {
  name                 = "${var.pool_name}"
  size                 = ""
  properties           = ""
...
}
etc
```
& similar schema for creating volumes of different types (CIFS/NFS etc)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Ashjoker24** [comment]
Hi,
i need a terraform code to provision netapp volume and attach the same to a machine
how can i use this code for my task. Thanks in Advance

**Comment by jstewart612** [comment]
@Ashjoker24 you can't, yet.  The entire point of this issue is to add the support in the first place.  The product is new, and thus, the feature does not yet exist until this ticket is addressed by someone :)

**Comment by mybayern1974** [comment]
For account, [PR 4416](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4416
) is tracking
