### ISSUE TITLE
azurerm_app_service specifying site_config when service plan is in Free or Shared tier fails to create app service

### ISSUE THREAD

**Issue by gunndabad** [terraform-providers/terraform-provider-azurerm#394]
### Terraform Version
Terraform v0.10.7
* provider.azurerm: version = "~> 0.2"

### Affected Resource(s)
azurerm_app_service

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "test" {
  name     = "tf_test_rg"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "test" {
  name                = "some-app-service-plan"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    tier = "Free"
    size = "F1"
  }
}

resource "azurerm_app_service" "test" {
  name                = "my-app-service"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  app_service_plan_id = "${azurerm_app_service_plan.test.id}"

  site_config {
  }
}
```

### Debug Output
https://gist.github.com/gunndabad/9ba8badd1ddf44fb48e37b6367830ca5

### Expected Behavior
App service gets created

### Actual Behavior
App service creation fails

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I believe this is due to the AlwaysOn parameter getting set (https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_app_service.go#L442). As Always On is not supported on the Free and Shared tiers it should be omitted on the request.

**Comment by tombuildsstuff** [comment]
Hey @gunndabad 

Thanks for opening this issue :)

I've taken a look into this and from what I can see this is because `use_32_bit_worker_process` in the `site_config` block defaults to `false`. When setting this to `true` I've been able to successfully use the `site_config` block (as shown below) in the Free and Shared tiers - would it be possible for you to take a look and see if that solves the issue you're seeing here?

```
resource "azurerm_resource_group" "test" {
  name = "tharvey-dev"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "test" {
  name                = "testappserviceplan"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    tier = "Free"
    size = "F1"
  }
}

resource "azurerm_app_service" "test" {
  name                = "tomtestappservice"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  app_service_plan_id = "${azurerm_app_service_plan.test.id}"
  site_config {
	use_32_bit_worker_process = true
  }
}
```

In addition - I've also opened PR #550 which updates the documentation to mention this and the tests to include use-cases for both the Free and Shared tiers.

Thanks!

**Comment by gunndabad** [comment]
Hi @tombuildsstuff

Setting use_32_bit_worker_process to true does indeed solve the problem for me.

Many thanks

**Comment by tombuildsstuff** [comment]
@gunndabad thanks for confirming that - since this issue appears to be solved (and the documentation is being updated in #550) - I'm going to close this issue for the moment

Thanks!
