### ISSUE TITLE
Support alerts based on Log analytics queries

### ISSUE THREAD

**Issue by ivanthelad** [terraform-providers/terraform-provider-azurerm#3951]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Create Alerts based on Log analytics queries.  as documented here https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-log
The corresponding API
https://docs.microsoft.com/en-us/rest/api/monitor/scheduledqueryrules/createorupdate
Currently only possible to create alerts based on Azure monitor metrics. 
https://www.terraform.io/docs/providers/azurerm/r/monitor_metric_alert.html
### New or Affected Resource(s)

* azurerm_monitor

**Comment by sunnynazar** [comment]
This is really needed as Azure does not expose all metrics as default .

This is possible by enabling Diagnostic settings in VM using Diagnostic extension and then we use log analytics workspace with customised queries and create alert.

But terraform does n't support creating alerts based on log anayltics queries.

Please help to prioritise this enhancement in Terraform.

**Comment by mcdafydd** [comment]
I've just started working on this.  Not sure yet how long it would take to get a PR together.  Maybe a couple weeks.  Anyone else already taking this on?

**Comment by ichwill100** [comment]
Is there any update on this?

**Comment by batizar** [comment]
@mcdafydd any updates on this? thanks.

**Comment by mcdafydd** [comment]
Hi all, 

Two months flies by.  Sorry about that.  I had started working on this and put it down for a bit while #4638 was getting merged.  That's done and I'm ready to get back into this now.  I'll commit what I have into my fork as soon as I can and try to get the PR created.  I'll aim for the end of the week.

**Comment by mcdafydd** [comment]
It's not completed yet, but I've made solid progress in my fork.  Data source and doc is almost done.  Still need to finish the resource and tests.  I may not have a PR today, but should have it submitted before Thursday.

**Comment by maciejluczak** [comment]
+1

**Comment by mcdafydd** [comment]
All my WIP is in [this dev branch](https://github.com/terraform-providers/terraform-provider-azurerm/compare/master...mcdafydd:monitor-3951-dev).  It's getting a lot closer but is more work than I surmised.

I could use some feedback on the approach.  Right now, I've got everything under a single new resource called `azurerm_monitor_scheduled_query_rules`, matching the [API endpoint](https://docs.microsoft.com/en-us/rest/api/monitor/scheduledqueryrules).  The resource definition is getting kinda long as it needs to support two different styles of actions with different required and optional parameters.   I also decided to flatten the `action`, `schedule`, and `source` blocks.

I'm wondering if it would be better to break these out into two resources called `azurerm_monitor_alerting_action` and `azurerm_monitor_log_to_metric_action`.

An `AlertingAction` looks like this right now:

```hcl
resource "azurerm_scheduled_query_rule" "example" {
  name                   = format("%s-queryrule", var.prefix)
  location               = azurerm_resource_group.example.location
  resource_group_name    = azurerm_resource_group.example.name

  action_type              = "AlertingAction"
  azns_action              = {
    action_group           = []
    email_subject          = "Email Header"
    custom_webhook_payload = {}
  }
  data_source_id           = azurerm_application_insights.example.id
  description              = "Scheduled query rule AlertingAction example"
  enabled                  = true
  frequency                = 5
  query                    = "requests | where status_code >= 500 | summarize AggregatedValue = count() by bin(TimeGenerated, 5m)"
  query_type               = "ResultCount"
  severity                 = "1"
  time_window              = 30
  trigger                  = {
    threshold_operator     = "GreaterThan"
    threshold              = 3
  }
}
```

and a `LogToMetricAction` plan looks like this right now:

```hcl
resource "azurerm_scheduled_query_rule" "example3" {
  name                   = format("%s-queryrule3", var.prefix)
  location               = azurerm_resource_group.example.location
  resource_group_name    = azurerm_resource_group.example.name

  action_type            = "LogToMetricAction"
  criteria               = [{
      metric_name        = "Average_% Idle Time"
      dimensions         = [{
        name             = "dimension"
        operator         = "GreaterThan"
        values           = ["latency"]
      }]
  }]
  data_source_id         = azurerm_application_insights.example.id
  description            = "Scheduled query rule LogToMetric example"
  enabled                = true
}
```

Are there some common guidelines I could follow for new resources like this?

Thanks!

**Comment by sunnynazar** [comment]
@mcdafydd  - will this be released in 1.39.0 ? Thanks.

**Comment by mcdafydd** [comment]
:crossed_fingers:   I hope so!  That's not my decision to make.  I will keep checking the pull request and make sure it stays mergeable and issue-free.

**Comment by sunnynazar** [comment]
Still waiting for this to be released, any chances for this to be added to 1.40.0 release?

**Comment by antempus** [comment]
Also waiting for this, any updates?

**Comment by SIGAN** [comment]
@mcdafydd is there any way to push for review your pull request? I'm waiting on this.

**Comment by mcdafydd** [comment]
This is only my second PR to terraform, so I wouldn't expect I had a lot of `pull` on the matter.  I'm with ya though, excited to be able to create both alert actions and monitoring queries in code.

**Comment by mcdafydd** [comment]
@tombuildsstuff @katbyte do you think 1.42.0 will likely be a successful version to review the PR for this feature?  If there's anything I can do in the meantime, I'm of course willing to help.  The only slight concern I have is that if any significant refactoring is required for #5053 before it can be approved, I could definitely use some extra lead time to make sure I can get any requests completed in time for release.

Thanks for any help!

**Comment by stazz** [comment]
I wonder why this keeps being constantly pushed to later versions. Especially since the PR has all checks passed and no conflicts. I guess resourcing issue? :/

The reason why I am commenting on that log-analytics-query-based alerts and metrics are one of the few things that our current TF automation can't handle. So I am waiting on this keenly. :)

**Comment by mcdafydd** [comment]
Thanks @katbyte for doing an initial review!  I should be able to submit updates for all the issues by the end of the week.

**Comment by DanielFrei64** [comment]
Looking forward to getting this feature. Converting my resources one by one to Terraform and was on to working alerting today but alas, scheduled query rules do not exist. Thank you mcdafydd for all your work on this.

**Comment by mcdafydd** [comment]
We're getting close now, @DanielFrei64.  Now that we have complete Action Groups, after Scheduled Query Rules I think a good next step would be [Action Rules](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-action-rules).

**Comment by ecottd** [comment]
Also looking forward to getting this feature as well as the action rules to tie everything together. Thanks for working on this.

**Comment by johnnyhuy** [comment]
`2.0.0` just released, will this be included soon?

**Comment by batmanme** [comment]
Thanks for implementing this , Do we have any document reference for configuration?

**Comment by mateusz-kozub** [comment]
@batmanme Link: https://www.terraform.io/docs/providers/azurerm/r/monitor_scheduled_query_rules_alert.html#example-usage
