### ISSUE TITLE
Azure Kubernetes Clusters: load_balancer_sku breaks cluster definition from 1.31 --> 1.32

### ISSUE THREAD

**Issue by brondum** [terraform-providers/terraform-provider-azurerm#3952]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.3
AzureRM: 1.32

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version         = "1.32"
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}

resource "azurerm_subnet" "k8s-subnet" {
  name                 = "${var.cluster_name}"
  address_prefix       = "${var.subnet_address_prefix}"
  virtual_network_name = "${var.virtual_network_name}"
  resource_group_name  = "${var.subnet_resource_group_name}"
}

resource "azurerm_kubernetes_cluster" "k8s-internal" {
  name                = "${var.cluster_name}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  dns_prefix          = "${var.dns_prefix}"
  kubernetes_version  = "1.13.7"

  agent_pool_profile {
    name            = "default"
    count           = "${var.agent_count}"
    vm_size         = "${var.agent_type}"
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = "${azurerm_subnet.k8s-subnet.id}"
    max_pods        = "${var.max_pods}"
  }

  service_principal {
    client_id     = "${var.client_id}"
    client_secret = "${var.client_secret}"
  }

  network_profile {
    network_plugin     = "azure"
    service_cidr       = "${var.network_service_cidr}"
    dns_service_ip     = "${var.network_dns_service_ip}"
    docker_bridge_cidr = "${var.network_docker_bridge_cidr}"
  }

  tags = {
    Environment = "Development"
  }

  role_based_access_control {
    enabled = true
  }
}
```

### Expected Behavior
Updated azurerm version to 1.32.
Expected just to update/modify the cluster to desired.

### Actual Behavior
Terraform wants to recreate the resource:
`load_balancer_sku  = "Basic" -> "basic" # forces replacement`

This breaks our Terraform states. the problem is that we cant get around it, we can keep using 1.31 but not a valid option for long. We cant specify the load_balancer_sku to use a capital "B" in "basic", then it complains.

Any insights ?

### Steps to Reproduce

1. Update azurerm to 1.32 in your tf files.
2. make a simple change which should only cause a "modify".
3. `terraform apply` or `terraform plan`

### References

* #3890

**Comment by wrighbr** [comment]
👍

**Comment by brondum** [comment]
Additional info:
As far as i can tell, when querying azure, load balancer sku values is actually with capital e.g.
`az network lb show -g <some_group> -n <some_lb>`
```json
 "sku": {
    "name": "Basic",
    "tier": "Regional"
  },
```

**Comment by mbfrahry** [comment]
Hey @brondum. It looks like some assumptions were made with the sdk not taking casing other than lower-case. We've suppressed casing entirely and you should be able to pass upper or lower casing to the api in the next release.

**Comment by brondum** [comment]
@mbfrahry Thank you for investigating, and looking forward to the fix :)
