### ISSUE TITLE
Cross-tenant VNet Peering

### ISSUE THREAD

**Issue by BParka** [terraform-providers/terraform-provider-azurerm#3954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.3
+ provider.azurerm v1.32.0

### Affected Resource(s)

* `azurerm_virtual_network_peering`

### Terraform Configuration Files

Service principal credentials provided in a providers.tf file:

```hcl
provider "azurerm" {
  version         = "v1.32.0"
  alias           = "sub1"
  subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
}

provider "azurerm" {
  version         = "v1.32.0"
  alias           = "sub2"
  subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
}
```
Calling module:
```hcl
module "vnetpeering" {
  providers = {
    azurerm.azurerm1 = azurerm.sub1
    azurerm.azurerm2 = azurerm.sub2
  }
  source                           = "../.."
  vnet_peering_names               = ["vnetpeering1", "vnetpeering2"]
  vnet_names                       = ["${module.network1.vnet_name}", "${module.network2.vnet_name}"]
  resource_group_names             = ["${azurerm_resource_group.rg1.name}", "${azurerm_resource_group.rg2.name}"]
  allow_cross_subscription_peering = true
  subscription_ids                 = [data.azurerm_subscription.sub1.subscription_id, data.azurerm_subscription.sub2.subscription_id]
  allow_virtual_network_access     = false
  allow_forwarded_traffic          = false

  # `allow_gateway_transit` must be set to false for vnet Global Peering
  allow_gateway_transit            = false

  tags = {
    environment = "dev"
    costcenter  = "it"
  }
}
```

Child module:
```hcl
provider "azurerm" {
  alias = "azurerm1"
}

provider "azurerm" {
  alias = "azurerm2"
}

data "azurerm_resource_group" "rg1" {
  provider = azurerm.azurerm1
  name     = "${var.resource_group_names[0]}"
}

data "azurerm_resource_group" "rg2" {
  provider = azurerm.azurerm2
  name     = "${var.resource_group_names[1]}"
}

data "azurerm_virtual_network" "vnet1" {
  provider            = azurerm.azurerm1
  name                = "${var.vnet_names[0]}"
  resource_group_name = "${data.azurerm_resource_group.rg1.name}"
}

data "azurerm_virtual_network" "vnet2" {
  provider            = azurerm.azurerm2
  name                = "${var.vnet_names[1]}"
  resource_group_name = "${data.azurerm_resource_group.rg2.name}"
}

resource "azurerm_virtual_network_peering" "vnet_peer_1" {
  provider                     = azurerm.azurerm1
  name                         = "${var.vnet_peering_names[0]}"
  resource_group_name          = "${data.azurerm_resource_group.rg1.name}"
  virtual_network_name         = "${data.azurerm_virtual_network.vnet1.name}"
  remote_virtual_network_id    = "${data.azurerm_virtual_network.vnet2.id}"
  allow_virtual_network_access = "${var.allow_virtual_network_access}"
  allow_forwarded_traffic      = "${var.allow_forwarded_traffic}"
  use_remote_gateways          = "${var.use_remote_gateways}"
}

resource "azurerm_virtual_network_peering" "vnet_peer_2" {
  provider                     = azurerm.azurerm2
  name                         = "${var.vnet_peering_names[1]}"
  resource_group_name          = "${data.azurerm_resource_group.rg2.name}"
  virtual_network_name         = "${data.azurerm_virtual_network.vnet2.name}"
  remote_virtual_network_id    = "${data.azurerm_virtual_network.vnet1.id}"
  allow_virtual_network_access = "${var.allow_virtual_network_access}"
  allow_forwarded_traffic      = "${var.allow_forwarded_traffic}"
  use_remote_gateways          = "${var.use_remote_gateways}"
}
```

### Debug Output
```
Error: network.VirtualNetworkPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/XXXXXXX/resourceGroups/test_rg_1/providers/Microsoft.Network/virtualNetworks/acctvnet/virtualNetworkPeerings/vnetpeering1', however the current tenant 'XXXXXX' is not authorized to access linked subscription 'XXXXXX'."
```

### Expected Behavior

Service principal being used has correct permissions, and peering connections can be created by logging in using this service principal on Azure CLI. The same credentials don't work when used in Terraform.

Permissions setup followed as in this example: 
https://medium.com/@ArsenVlad/azure-vnet-peering-across-azure-active-directory-tenants-using-service-principal-authentication-13c52d3190ab
### Actual Behavior

Error with above output.

### Steps to Reproduce

Set up service principal on both accounts as in above example and use correct credentials in providers.tf (same client but different tenants)

1. `terraform apply`

### References

Almost identical to closed, although seemingly unresolved issue:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3609

In above issue permissions were blamed. I have proven that the service principal I am using has sufficient permissions by performing the peering via Azure CLI hence why I think the problem may be with the provider.

**Comment by siobam** [comment]
Hi, 
I had to create workaround. I guess the main problem here that even if service principal has access to both tenant, by default the terraform provide requires subscription, so provide is not able to manage resource in both subscription. 
I had to use workaround.
Here is my solution:
https://github.com/siobam/Terraform/tree/master/Module/cross_tenant_peering

**Comment by darryncurranHP** [comment]
I commented in an other thread about having the same issue and the way I managed to resolve it.

Link: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4378#issuecomment-537948435

**Comment by tombuildsstuff** [comment]
Closing since this is permissions/configuration related, rather than a bug in the provider - but if you're still having issues you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
