### ISSUE TITLE
Compile azurerm plugin totally static

### ISSUE THREAD

**Issue by jomeier** [terraform-providers/terraform-provider-azurerm#3962]
Hi,

we use Terraform in an Alpine image based OpenShift Operator to manage our infrastructure.

Because some shared libraries required by the AzureRM plugin are missing in the Alpine image we compile it totally static. 

To do that we replaced the line

```
build: fmtcheck
	go install
```
in the GNUmakefile with 
```
build: fmtcheck
	CGO_ENABLED=0 GOOS=linux go install -a -ldflags '-extldflags "-static"'
```

Does it make sense for you to integrate that in the main repo?

Best regards,

Josef

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by katbyte** [comment]
Hi @jomeier,

Thank you for opening this issue. At this time we do not have any plans to add this ability into the provider as it doesn't seem a common enough usecase to change the default build step for. For those who need this ability in their CI/CD pipeline it is easy enough to change `make build` to `make fmtcheck && `CGO_ENABLED=0 GOOS=linux go install -a -ldflags '-extldflags "-static"'`
