### ISSUE TITLE
Add logging to API Management

### ISSUE THREAD

**Issue by brynjarte** [terraform-providers/terraform-provider-azurerm#3981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It should be possible to enable the `azurerm_api_management_logger` for a chosen API.

### New or Affected Resource(s)

* azurerm_api_management_logger
* azurerm_api_management_api

**Comment by LaurentLesle** [comment]
Yes seen that as well 
![image](https://user-images.githubusercontent.com/4702224/62607326-7b513880-b930-11e9-913e-82999c4c0c55.png)

**Comment by hctv19** [comment]
FYI - I think this feature request (which has a PR against it already) may resolve this: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4760

**Comment by manicminer** [comment]
I believe this has been satisfied with the [azurerm_api_management_api_diagnostic](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7873) resource, so I'm going to close this issue. If this isn't the case, please feel free to command and we'll reopen it. Thanks!
