### ISSUE TITLE
Support for Azure API for FHIR®

### ISSUE THREAD

**Issue by paveljakov** [terraform-providers/terraform-provider-azurerm#3989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if support for [Azure API for FHIR®](https://azure.microsoft.com/en-in/services/azure-api-for-fhir/) could be implemented at some point. This managed service is still in preview state, but we plan to use it in one of our Electronic Medical Record projects that will be deployed on Azure.

### New or Affected Resource(s)

* azurerm_fhir_api - new resource

### References

* https://azure.microsoft.com/en-in/services/azure-api-for-fhir/
* https://docs.microsoft.com/en-in/azure/healthcare-apis/fhir-paas-cli-quickstart

**Comment by jwalter** [comment]
The Azure API for FHIR service has now moved to General Availability: https://azure.microsoft.com/sv-se/blog/azure-api-for-fhir-moves-to-general-availability/

**Comment by katbyte** [comment]
open PR related to this #4221
