### ISSUE TITLE
Terraform causing Azure Express Route Circuit to enter failed state after updating tags

### ISSUE THREAD

**Issue by djmcalister** [terraform-providers/terraform-provider-azurerm#3996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

azurerm_express_route_circuit

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

N/A

### Expected Behavior

Tags should have been updated without causing Express Route Circuit to enter failed state

### Actual Behavior

Tags got updated but Express Route Circuit got put into failed state and Refresh did not resolve the issue

Call logged with Microsoft who advised the following: -

Conclusions
We were able to see in the logs that the PUT call that triggered the circuit to be in failed state came via Terraform version 11.9 using Azure-SDK-for-Go (v21.3). 
This PUT call consisted of incomplete circuit details. This resulted in an attempt of deleting the Peering, because the PUT call had no entries for peering details.

I raised this internally to our product group and they manually restored the properties by fixing the necessary entries. This problem should now be mitigated. Can you please confirm by doing a refresh in the Azure portal?

Suggestions
To prevent this kind of scenario from happening again, Terraform should perform PATCH operation for updating tags instead of PUT. Or, if performing PUT, it must provide the complete set of properties.
Also, you may want to consider updating Terraform, or any tool based on it. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by pearcec** [comment]
I understand the conclusion, I understand why they would recommend a PATCH vs a PUT containing partial details, but my understanding is terraform is going to PUT the entire state it has back on an update.  Since we lack details such as configuration and output we don't have a lot to go one.  I am going write a test to confirm.

**Comment by pearcec** [comment]
Test added. Waiting on Travis.  I would close this bug out.

**Comment by katbyte** [comment]
Hi @djmcalister,

as @pearcec pointed out with the passing test there and no explicit config for us to check/test we have no way to debug your issue. As such i am going to close this out, please feel free to reopen it if this is still an issue with a failing config.
