### ISSUE TITLE
Error reading queue properties for AzureRM Storage Account

### ISSUE THREAD

**Issue by mattbowes** [terraform-providers/terraform-provider-azurerm#3997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.6
+ provider.azurerm v1.32.1
+ provider.null v2.1.2
+ provider.random v2.1.2

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "random_string" "appgateway_storageid" {
  length  = 8
  special = false
  upper   = false
  number  = true
}

resource "azurerm_storage_account" "appgateway_storage" {
  name                      = "${var.env}appgwlogs${random_string.appgateway_storageid.result}"
  resource_group_name       = "${azurerm_resource_group.appgateway.name}"
  location                  = "${var.location}"
  account_tier              = "${var.storage_tier}"
  account_replication_type  = "${var.storage_replication}"
  enable_https_traffic_only = "${var.storage_https_only}"
}
```

### Expected Behavior

Terraform should successfully plan

### Actual Behavior

During a terraform plan using provider version v1.32.1 or v1.32.0 the following error is thrown

Error: Error reading queue properties for AzureRM Storage Account "removed": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://removed.queue.core.windows.net?comp=properties&restype=service: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"invalid_request","message":"No token found for audience https://storage.azure.com/"}}

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

If i downgrade the provider to v1.31.0 everything works as normal. If i upgrade to v1.32.0 or v1.32.1 then the error occurs 

### References

* #0000

**Comment by danvy** [comment]
This script doesn't work with every single provider version 1.28 and up on an MS internal account or a pay as you go account.

provider "azurerm" {
  version = ">= 1.32"
}
terraform {
  required_version = ">= 0.12"
}
resource "random_string" "id" {
  length = 6
  upper = false
  lower = true
  special = false
}
resource "azurerm_resource_group" "resgroup" {
  name     = "resgroup"
  location = "northeurope"
}
resource "azurerm_storage_account" "storage" {
  name = "storage${random_string.id.result}"
  resource_group_name = "${azurerm_resource_group.resgroup.name}"
  location = "${azurerm_resource_group.resgroup.location}"
  account_tier = "Standard"
  account_replication_type = "LRS"
}

**Comment by squasta** [comment]
> This script doesn't work with every single provider version 1.28 and up on an MS internal account or a pay as you go account.
> 
> provider "azurerm" {
> version = ">= 1.32"
> }
> terraform {
> required_version = ">= 0.12"
> }
> resource "random_string" "id" {
> length = 6
> upper = false
> lower = true
> special = false
> }
> resource "azurerm_resource_group" "resgroup" {
> name = "resgroup"
> location = "northeurope"
> }
> resource "azurerm_storage_account" "storage" {
> name = "storage${random_string.id.result}"
> resource_group_name = "${azurerm_resource_group.resgroup.name}"
> location = "${azurerm_resource_group.resgroup.location}"
> account_tier = "Standard"
> account_replication_type = "LRS"
> }

It works for me with Azurerm provider 1.31 and crashes with azurerm provider version >=1.32

**Comment by tombuildsstuff** [comment]
hi @mattbowes 

Thanks for opening this issue.

So that we can take a look into this would it be possible to know which authentication method you're using?

Thanks!

**Comment by deaksa** [comment]
> hi @mattbowes
> 
> Thanks for opening this issue.
> 
> So that we can take a look into this would it be possible to know which authentication method you're using?
> 
> Thanks!

Same issue at me using azure cli authentication.

**Comment by mattbowes** [comment]
> 
> 
> hi @mattbowes
> 
> Thanks for opening this issue.
> 
> So that we can take a look into this would it be possible to know which authentication method you're using?
> 
> Thanks!

I am running this in the Azure Cloud Shell. Terraform authenticates automatically

**Comment by robdavey555** [comment]
> hi @mattbowes
> 
> Thanks for opening this issue.
> 
> So that we can take a look into this would it be possible to know which authentication method you're using?
> 
> Thanks!

I have the same issue using Bash in Azure Cloud Shell.

This is the error message returned in my case

` Error reading queue properties for AzureRM Storage Account "mystorageaccount": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://mystorageaccount.queue.core.windows.net?comp=properties&restype=service: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"invalid_request","message":"No token found for audience https://storage.azure.com/"}}`

**Comment by ljckennedy** [comment]
Same here also.  Upgraded this morning and it broke - luckily I found this post and downgraded again!

**Comment by doherty100** [comment]
Experienced the same behavior. Client is Ubuntu WSL. Authentication is via Azure CLI. Downgrading to  azurerm provider v1.31.0 resolved the issue.

**Comment by marcosgm** [comment]
+1 same issue here (internal MS subscription) while following https://azurecitadel.com/automation/terraform/lab1/

Pinning to 1.31 solves the issue

`# Configure the Azure Provider
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "=1.31"
}

resource "azurerm_resource_group" "lab1" {
  name     = "terraform-lab1"
  location = "West Europe"

  tags = {
    environment = "training"
  }
}

resource "azurerm_storage_account" "lab1sa" {
  name                     = "magarciastor2345tf"
  resource_group_name      = "${azurerm_resource_group.lab1.name}"
  location                 = "westeurope"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}`

**Comment by jnevins-gcm** [comment]
Bump. Is this getting resolved? Seems like a pretty fundamental regression gap.
