### ISSUE TITLE
Kubernetes aci_connector_linux  subnet_name typo/case sensitive

### ISSUE THREAD

**Issue by joseph-passineau** [terraform-providers/terraform-provider-azurerm#3998]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.6
AzureRM 1.32.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
locals {
  azurerm_virtual_network_cluster_name         = substr("${local.resource_name_prefix}-vnet-cluster-${local.uniqueString}", 0, 255)
  azurerm_kubernetes_cluster_name              = substr("${local.resource_name_prefix}-aks-cluster-${local.uniqueString}", 0, 255)
  azurerm_kubernetes_cluster_nodeResourceGroup = "${azurerm_resource_group.main.name}-nodes"
}

resource "azurerm_virtual_network" "cluster" {
  name                = local.azurerm_virtual_network_cluster_name
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  address_space       = ["10.240.0.0/20"]

  tags = var.tags
}

resource "azurerm_subnet" "cluster" {
  name                 = "default"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.cluster.name
  address_prefix       = "10.240.1.0/24"
}

resource "azurerm_subnet" "virtualnode" {
  name                 = "virtual-node-aci"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.cluster.name
  address_prefix       = "10.240.2.0/24"
}

resource "azurerm_kubernetes_cluster" "cluster" {
  name                = local.azurerm_kubernetes_cluster_name
  resource_group_name = azurerm_resource_group.main.name
  node_resource_group = local.azurerm_kubernetes_cluster_nodeResourceGroup
  location            = local.location
  dns_prefix          = var.azurerm_kubernetes_cluster_dns_prefix

  agent_pool_profile {
    name            = "default"
    count           = 1
    vm_size         = "Standard_B2s"
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.cluster.id
  }

  service_principal {
    client_id     = var.aks_app_client_id
    client_secret = var.aks_app_client_secret
  }

  addon_profile {
    aci_connector_linux {
      enabled     = true
      subnet_name = azurerm_subnet.virtualnode.name
    }
  }

  network_profile {
    network_plugin = "azure"
  }

  role_based_access_control {
    enabled = true
  }

  tags = var.tags
}
```

### Expected Behavior

Kubernetes cluster with a virtual node : virtual-node-aci-linux

### Actual Behavior

Kubernetes cluster doesnt have a virtual node

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Create 2 clusters. 
1st cluster created using azurerm_kubernetes_cluster
2nd cluster using identical config but using azurerm_template_deployment

![image](https://user-images.githubusercontent.com/16294504/62387465-ad296000-b528-11e9-80e0-02b201b1285e.png)

When comparing both cluster, we see that the subnetName has a typo when using azurerm_kubernetes_cluster.

When fixing the typo, the virtual node reappears.

**Comment by AlexandreArpin** [comment]
Can this be fixed by changing the casing on these 2 lines or are these configuration used elsewhere as well?

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L893

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L956

We'd be really happy to submit a PR with the fix if this is indeed the solution.

**Comment by AlexandreArpin** [comment]
Courtesy bump, we'd be happy to help and provide a solution, our Go experience is rather limited however.

@katbyte since you've triaged the issue, would you be able to point us to the right person to collaborate with in order for us to push a fix and help the community?

Thanks!

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems the issue has been resolved. See more details from below references. Thanks.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/528740f357677686a1c50ecfc822d145c488946a/azurerm/internal/services/containers/kubernetes_addons.go#L190
https://github.com/terraform-providers/terraform-provider-azurerm/blob/528740f357677686a1c50ecfc822d145c488946a/azurerm/internal/services/containers/kubernetes_addons.go#L274

**Comment by tombuildsstuff** [comment]
Closing since this appears to have been fixed (via @neil-yechenwei comment above)
