### ISSUE TITLE
Dependency checking when deleting a subnet

### ISSUE THREAD

**Issue by sebastus** [terraform-providers/terraform-provider-azurerm#400]
### Terraform Version
0.10.7-dev

### Affected Resource(s)
Using the "compute" and "network" modules from azure module registry.

### Terraform Configuration Files
```hcl
module "mycompute" {
  source = "Azure/compute/azurerm"
  resource_group_name = "mycompute"
  location = "East US 2"
  admin_password = "ComplxP@ssw0rd!"
  vm_os_simple = "WindowsServer"
  public_ip_dns = "mywinsrv252"
  remote_port = "3389"
  nb_instances = 2
  vnet_subnet_id = "${module.network.vnet_subnets[0]}"
}

module "network" {
  source = "Azure/network/azurerm"
  location = "East US 2"
  resource_group_name = "mycompute"
}
```

### Expected Behavior
all resources should be deleted cleanly

### Actual Behavior
Got an error message saying that the subnet can't be deleted because of a dependency:

* azurerm_subnet.subnet: network.SubnetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet subnet1 is in use by /subscriptions/743f6ed6-83a8-46f0-822d-ea93b953952d/resourceGroups/mycompute/providers/Microsoft.Network/networkInterfaces/nic0/ipConfigurations/ipconfig0 and cannot be deleted." Details=[]

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` the above HCL (in main.tf)
2. delete contents of main.tf
3. `terraform apply`

**Comment by tombuildsstuff** [comment]
Hey @sebastus 

From what I can see this is a known issue in Terraform Core - as such I've migrated this issue over to the Terraform Core repository: https://github.com/hashicorp/terraform/issues/16361

Thanks!
