### ISSUE TITLE
Azure Analysis Services import fails with value length error

### ISSUE THREAD

**Issue by tlaur** [terraform-providers/terraform-provider-azurerm#4004]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.5
AzureRM 1.32.1

### Affected Resource(s)

azurerm_analysis_services_server

### Expected Behavior

Azure Analysis Services Server imported successfully

### Actual Behavior

Import fails with error: 
`Error retrieving Analytics Services Server "" (Resource Group "resgroupname"): analysisservices.ServersClient#GetDetails: Invalid input: autorest/validation: validation failed: parameter=serverName constraint=MinLength value="" details: value length must be greater than or equal to 3`

Looks to me like the name of the resource is not passed on, which results in an empty string and hence the error.

### Steps to Reproduce
1. Manually create an azure analysis services server
2. terraform init
3. terraform import azurerm_analysis_services_server.analysis_services /subscriptions/***subid***/resourceGroups/***resgroupname***/providers/Microsoft.AnalysisServices/server/***resourcename***

**Comment by katbyte** [comment]
Hi @tlaur, 

It looks like the documentation is incorrect. the correct import command should be:
```
terraform import azurerm_analysis_services_server.analysis_services /subscriptions/subid/resourceGroups/resgroupname/providers/Microsoft.AnalysisServices/servers/resourcename
```

Could you please give that a try?

**Comment by tlaur** [comment]
Yep, can confirm it was the server -> servers in the uri, import succeeds after that change.
