### ISSUE TITLE
Omitting `default_action` should result in a deployment failure.

### ISSUE THREAD

**Issue by cvandal** [terraform-providers/terraform-provider-azurerm#4006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.12.6
Provider: 1.32.1

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage_account" {
  depends_on               = [""]

  name                     = ""
  location                 = ""
  resource_group_name      = ""
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "RAGRS"

  network_rules {
    ip_rules                   = [""]
    virtual_network_subnet_ids = [""]
  }
}
```

### Expected Behavior

If the required attribute `default_action` within the `network_rules` section is omitted, Terraform should fail to deploy.

Initially we never used this attribute and our Azure Storage Accounts were not publically accessible. We only noticed recently that it's no longer the case. After reviewing the provider documentation we became aware of the required `default_action` attribute which we did not have, and although it's required, our deployments have been successful.

### Actual Behavior

Successful deployment. I assume that if it's omitted, it defaults to `Allow`.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by philbal611** [comment]
Here to confirm that omitting this attribute does set the value to `Allow`. Any subsequent plans result in a limbo-state of "changes":

```hcl
~ azurerm_storage_account.test
      network_rules.0.default_action: "Allow" => ""
```
