### ISSUE TITLE
Redeploying a VM causes Backups to be deleted

### ISSUE THREAD

**Issue by phires** [terraform-providers/terraform-provider-azurerm#4012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -v                                                                                                                                                                                            
Terraform v0.12.6
+ provider.azurerm v1.32.1

### Affected Resource(s)

* `azurerm_recovery_services_protected_vm`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rgRecoveryTest" {
  name     = "recovery-test-rg"
  location = "westeurope"
}

resource "azurerm_recovery_services_vault" "rsv" {
  name                = "recovery-test-rsv"
  location            = "${azurerm_resource_group.rgRecoveryTest.location}"
  resource_group_name = "${azurerm_resource_group.rgRecoveryTest.name}"
  sku                 = "Standard"
}

resource "azurerm_recovery_services_protection_policy_vm" "daily_standard" {
  name                = "recovery-test-daily-standard"
  resource_group_name = "${azurerm_resource_group.rgRecoveryTest.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"

  timezone = "UTC"

  backup {
    frequency = "Daily"

    time = "00:00"
  }

  retention_daily {
    count = "7"
  }

  retention_weekly {
    weekdays = ["Sunday"]
    count    = 5
  }

  retention_monthly {
    weekdays = ["Sunday"]
    weeks    = ["First"]
    count    = 13
  }
}

data "azurerm_subnet" "testSubnet" {
  name                 = "test-subnet"
  resource_group_name  = "rg-test-subnet"
  virtual_network_name = "TestVNet"
}

resource "azurerm_network_interface" "nicRecoveryTest" {
  name                = "recovery-test-nic"
  location            = "${azurerm_resource_group.rgRecoveryTest.location}"
  resource_group_name = "${azurerm_resource_group.rgRecoveryTest.name}"

  ip_configuration {
    name                          = "config"
    subnet_id                     = "${data.azurerm_subnet.testSubnet.id}"
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_virtual_machine" "vmRecoveryTest" {
  name                  = "recovery-test-lvm"
  location              = "${azurerm_resource_group.rgRecoveryTest.location}"
  resource_group_name   = "${azurerm_resource_group.rgRecoveryTest.name}"
  vm_size               = "Standard_B1s"
  network_interface_ids = ["${azurerm_network_interface.nicRecoveryTest.id}"]

  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    version   = "latest"
    offer     = "CentOS"
    publisher = "OpenLogic"
    sku       = "7.5"
  }

  storage_os_disk {
    name              = "recovery-test-lvm-OS"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "recovery-test-lvm"
    admin_username = "phires"
    admin_password = "P@sSw0rd!"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
}

resource "azurerm_recovery_services_protected_vm" "protect_recovery_test_vm" {
  resource_group_name = "${azurerm_resource_group.rgRecoveryTest.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"
  source_vm_id        = "${azurerm_virtual_machine.vmRecoveryTest.id}"

  backup_policy_id = "${azurerm_recovery_services_protection_policy_vm.daily_standard.id}"
}

```

### Expected Behavior

I'm building the OS image using Packer (the example is using CentOS just for shortening the code). When redeploying (or deleting) the VM I expect all backups to be retained.

### Actual Behavior

When the VM is re-deployed (or tainted) because of the base image changing, it causes the `azurerm_recovery_services_protected_vm` resource to be redeployed aswell, as the `source_vm_id` changes. This causes the backup data to be deleted.

### Steps to Reproduce

1. `terraform apply`
2. `terraform taint azurerm_virtual_machine.vmRecoveryTest`
3. `terraform apply`

### References

When deleting a VM via the Azure Portal, all Backups are retained.
Not using the id of the VM as `source_vm_id` but a hardcoded string (`source_vm_id = "subscriptions/xxx/resourceGroups/recovery-test-rg/providers/Microsoft.Compute/virtualMachines/recovery-test-lvm"`) is a workaround, but a bad one...

* #0000

**Comment by phires** [comment]
Just as an addition, another workaround is just ignoring changes to `source_vm_id`:

```hcl
resource "azurerm_recovery_services_protected_vm" "protect_recovery_test_vm" {
  resource_group_name = "${azurerm_resource_group.rgRecoveryTest.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.rsv.name}"
  source_vm_id        = "${azurerm_virtual_machine.vmRecoveryTest.id}"

  backup_policy_id = "${azurerm_recovery_services_protection_policy_vm.daily_standard.id}"

  lifecycle {
      ignore_changes = [ "source_vm_id", ]
  }
}
```

But this still feels like just a workaround...

**Comment by tombuildsstuff** [comment]
hey @phires 

Thanks for opening this issue.

Taking a look into this unfortunately this appears to be a bug in Terraform Core and as such would need to be fixed there. There's an upstream issue tracking this (https://github.com/hashicorp/terraform/issues/8099) where the Terraform Core team should be able to take a look and make a fix; but once the fix is added that should automatically become available to all providers. Since this isn't something we're able to work around in the Azure Provider directly; for the moment I'm going to close this in favour of the upstream issue https://github.com/hashicorp/terraform/issues/8099 - would you mind subscribing to that issue for updates?

Thanks!
