### ISSUE TITLE
azurerm_dns_zone: Creating Private and Public zone with the same name fails

### ISSUE THREAD

**Issue by invidian** [terraform-providers/terraform-provider-azurerm#4017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
$ terraform version
Terraform v0.11.14
+ provider.azurerm v1.32.0
```

### Affected Resource(s)

* `azurerm_dns_zone`

### Terraform Configuration Files

```hcl
# Create delegated DNS zone on Azure
resource "azurerm_dns_zone" "test" {
  name                = "foo.example.com"
  resource_group_name = "${azurerm_resource_group.test.name}"
  zone_type           = "Public"
}

resource "azurerm_dns_zone" "private" {
  name                           = "foo.example.com"
  resource_group_name            = "${azurerm_resource_group.test.name}"
  zone_type                      = "Private"
}
```

### Expected Behavior

Both `Public` and `Private` zone should be created as stated in the [example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/dns_zone.html.markdown#example-usage) OR documentation should be changed to present working example.

### Actual Behavior

Creation fails with following error:
```
1 error occurred:
	* azurerm_dns_zone.private: 1 error occurred:
	* azurerm_dns_zone.private: Error creating/updating DNS Zone "foo.example.com" (Resource Group "test-testing"): dns.ZonesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="A different Type of Zone with same name under same resource group and subscription already exists."
```

### Steps to Reproduce

1. `terraform apply`

**Comment by timja** [comment]
Use private dns zone instead?
https://www.terraform.io/docs/providers/azurerm/r/private_dns_zone.html
That's the old preview that is being removed as far as I understand
