### ISSUE TITLE
Availability Zones for AKS cluster

### ISSUE THREAD

**Issue by kyanagimoto** [terraform-providers/terraform-provider-azurerm#4026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://docs.microsoft.com/en-us/azure/aks/availability-zones
This function is Preview phase, but do you have any plan to develop for this feature?
I want to create AKS cluster w/ availability-zones via Terraform.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

I think possibly to add like node_count or node_zone on the terraform file. 

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "azurerm_kubernetes_cluster" "az-sample" {
  name                = "az-sample"
  location            = "eastus2"
  resource_group_name = "az-sample"
  dns_prefix          = "az-sample"
  kubernetes_version  = "1.13.7"

  linux_profile {
    admin_username = "azuser"

    ssh_key {
      key_data = "${file("./id_rsa.pub")}"
    }
  }

  agent_pool_profile {
    name            = "default"
    **node_count  = 3**
    **node_zone = "1,2,3"**
    vm_size         = "Standard_B8ms"
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = "${data.azurerm_subnet.express_route.id}"
    
  }

  service_principal {
    client_id     = "${var.azure_client_id}"
    client_secret = "${var.azure_client_secret}"
  }

  network_profile {
    network_plugin = "azure"
  }
}
```

### References

https://docs.microsoft.com/en-us/azure/aks/availability-zones

* #0000

**Comment by bnookala** [comment]
@kyanagimoto seems like it's been released in version 1.32 of the provider - I started to see if I could do this work myself, when I found this PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/3361/files

which contributed [this line](https://github.com/terraform-providers/terraform-provider-azurerm/blame/master/azurerm/resource_arm_kubernetes_cluster.go#L1071). If I'm reading this correctly, you should be able to configure the agent pool profile like this to enable availability zones:

```
  agent_pool_profile {
    name            = "default"
**    count  = 3 **
**    availability_zones = ["1", "2", "3"] **
    vm_size         = "Standard_B8ms"
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = "${data.azurerm_subnet.express_route.id}"
  }
```

See: https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#availability_zones for more info

@tombuildsstuff you may know better, but I think this issue can be closed

**Comment by tombuildsstuff** [comment]
@bnookala thanks for the ping - yeah I'd agree this has been fixed and can be closed :)

**Comment by kyanagimoto** [comment]
@bnookala Thanks to let me know :)
