### ISSUE TITLE
Data Factory SFTP and FTP linked services

### ISSUE THREAD

**Issue by Kampfgnom** [terraform-providers/terraform-provider-azurerm#4029]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are a lot more Data Factory linked services than currently supported. We need FTP and FTPS services in particular.

We are willing to implement the resources on our own 🙂 We're opening this issue to make our effort visible in case anyone is already working on it.

In an older issue (https://github.com/terraform-providers/terraform-provider-azurerm/issues/3383#issuecomment-490304981) @mbfrahry "wanted to make the data factory resources as generic as possible but [...] couldn't find a clean way to do it". Is this still correct?

### New or Affected Resource(s)

* azurerm_data_factory
* azurerm_data_factory_linked_service_sftp_server
* azurerm_data_factory_linked_service_ftp_server

### Potential Terraform Configuration

```hcl

resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
}

data "azurerm_client_config" "current" {}

resource "azurerm_data_factory_linked_service_sftp_server" "example" {
  name                  = "example"
  resource_group_name   = "${azurerm_resource_group.test.name}"
  data_factory_name     = "${azurerm_data_factory.test.name}"
  host = "sftp.example.com"
  port = 22
  skip_host_key_validation = false
  host_key_finger_print = "ssh-rsa 2048 xx:00:00:00:xx:00:x0:0x:0x:0x:0x:00:00:x0:x0:00"
  authentication_type = "Basic"
  user_name = "<username>"
  password = "<password>"
}
```

### References

* #3383
* https://docs.microsoft.com/en-us/azure/data-factory/connector-sftp

**Comment by mbfrahry** [comment]
Hi @Kampfgnom. Glad to see you taking the charge here! My statement still stands that we can't make a generic linked service (or dataset) resource because there are soooo many different types linked services that take different attributes depending on which resource it is. I believe your best bet is too make them individually but I'm open to being wrong! If you find a better solution please let me know so we can chat through it. 

Your implementation of `azurerm_data_factory_linked_service_sftp_server` looks good as well. Let me know if you have any questions and I'll do my best to help out if needed

**Comment by Kampfgnom** [comment]
Just a quick update: We're started to work on this issue during what we call a "community day" at work (thanks @ https://github.com/grandcentrix). We did not finish the implementation since we're only learning this stuff along the way.

I think that during our next community day we'll be able to put out a PR, so expect an update next week on Wednesday :-)
