### ISSUE TITLE
Proximity placement groups(PPG) Terraform provider

### ISSUE THREAD

**Issue by srakesh28** [terraform-providers/terraform-provider-azurerm#4032]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @srakesh28 

Thanks for opening this issue.

Since the issue description here appears to be the default template and there's a PR open which adds support for this - I'm going to close this issue in favour of the PR (#4020) - would you mind subscribing to that for updates?

Thanks!

**Comment by srakesh28** [comment]
Please prioritize this provider as it will help many customers to leverage new Azure feature for latency sensitive applications.

**Comment by srakesh28** [comment]
Thank you I accidentally submitted default language but have updated comment. Thanks for adding pull request I will subscribe to it for tracking
