### ISSUE TITLE
azurerm_storage_share not supporting quotas above 5TB, regardless of storage account type

### ISSUE THREAD

**Issue by philbal611** [terraform-providers/terraform-provider-azurerm#4034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform -- 0.11.13
AzureRM -- 1.32.1

### Affected Resource(s)

* `azurerm_storage_share`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "test" {
  name                     = "azureteststorage"
  resource_group_name      = "${azurerm_resource_group.test.name}"
  location                 = "${azurerm_resource_group.test.location}"
  account_tier             = "Premium"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "testshare" {
  name                 = "sharename"
  storage_account_name = "${azurerm_storage_account.test.name}"
  quota                = 6144
}
```

### Expected Behavior

Per [MS documentation](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#azure-files-limits), Storage Shares that belong to Premium storage accounts are allowed quotas up to 100TB, and recently, Standard storage accounts are also allowing quotas up to 100TB (preview). Terraform should not be catching this 5TB limitation before the `plan` phase.

### Actual Behavior

Terraform returns an error before returning a plan:

`azurerm_storage_share.testshare: expected quota to be in the range (1 - 5120), got 6144`

### Steps to Reproduce

1. Configure code above
2. Run `terraform plan`

**Comment by nexxai** [comment]
Submitted a PR for this: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4054.  It's my first time doing something in Go so I hope I didn't mess things up too badly.
