### ISSUE TITLE
Add auto swap support to app service slots

### ISSUE THREAD

**Issue by alastairtree** [terraform-providers/terraform-provider-azurerm#4042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please can we add [auto swap support](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#configure-auto-swap) to the app service slot resource

### New or Affected Resource(s)

* azurerm_app_service_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_slot" "app_service_slot" {
  name                    = var.slot_name
  app_service_name        = azurerm_app_service.app_service.name
  location                = var.location
  resource_group_name     = var.resource_group_name
  app_service_plan_id     = var.app_service_plan_id

  site_config {
    always_on                = true
    dotnet_framework_version = "v4.0"
    http2_enabled            = true

    # NEW configuration property
    auto_swap_slot_name = "production"
  }
```

### References
The following template deployment allows you so set the autoSwapSlotName property on every terraform apply in addition to a regular azurerm_app_service_slot resource using an azureRM template as a temporary workaround:

```hcl
resource "azurerm_template_deployment" "app_service_slot_auto_swap" {
  name                = "${var.slot_name}-auto-swap"
  resource_group_name = var.resource_group_name
  deployment_mode     = "Incremental"

  template_body = <<JSON
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "variables": {
     "_force_terraform_to_always_redeploy": "${timestamp()}"
  },
  "resources": [{
      "type": "Microsoft.Web/sites/slots",
      "name": "${azurerm_app_service.app_service.name}/${azurerm_app_service_slot.app_service_slot.name}",
      "apiVersion": "2018-11-01",
      "location": "${var.location}",
      "properties": {
        "siteConfig": {
          "autoSwapSlotName": "production"
        }
      }
    }
  ]
}
  JSON
  depends_on    = [azurerm_app_service_slot.app_service_slot]
}
```

**Comment by kendaleiv** [comment]
This can be closed, implemented via https://github.com/terraform-providers/terraform-provider-azurerm/pull/4752.
