### ISSUE TITLE
azurerm_sql_database - Unsupported attribute

### ISSUE THREAD

**Issue by mateuszm123111** [terraform-providers/terraform-provider-azurerm#4044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

When implementing alerts for databses with terraform, it should support 'id' attribute as mentioned in terraform documentation.

### Actual Behavior

scopes              = ["${var.database.id}"]

var.database is "azurerm_sql_database.db"

This value does not have any attributes.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @mateuszm123111 

Thanks for opening this issue.

Taking a look at the code above - unfortunately this won't work as it's currently defined, as the variable `database` is a string - rather than the resulting interpolation of that value (e.g. it'll return the literal string "azurerm_sql_database.db", which won't have an "id" field, since it's a string not an object). Instead you should be able to access the `id` field from the `azurerm_sql_database` resource using this syntax: "${azurerm_sql_database.db.id}"

Thanks!

**Comment by mateuszm123111** [comment]
When I set up variable with full "id", I got - Error: Can not parse "scopes.0" as a resource id: Cannot parse Azure ID: parse azurerm_sql_database.db_report.id: invalid URI for request

**Comment by tombuildsstuff** [comment]
@mateuszm123111 can you post the full Terraform Configuration you're using?

**Comment by mateuszm123111** [comment]
Ok, so I have module database in which i have file called 'output.tf''
`output "report_database" {
  value = "azurerm_sql_database.db_report.id"
}`

Then I have module 'alerts' and file called 'variables.tf', where I have:
`variable "report_database" {}`
I use this variable in my code, like `${var.report_database}`, and also in my 'main.tf' I have something like this:
`module "alerts" {
    source = "./modules/alerts"
    resource_group = "${module.resource_group.resource_group}"
    k8s = "${module.k8s.k8s}"
    report_database = "${module.database.report_database}"`
I have exact the same configuration (I guess) with kubernetes cluster, and it's work as I expect.

Am I doing something wrong? If yes, please correct me, I will be grateful :)

**Comment by tombuildsstuff** [comment]
@mateuszm123111 unfortunately it's hard to diagnose this without a reproducible code sample - would you be able to put everything in a single file and post that file here?

**Comment by mateuszm123111** [comment]
Ok, I just realized that I had issue with my output variable in database module. I had:
`output "report_database" { value = "azurerm_sql_database.db_report.id" }`
but, it should be:
`output "report_database" { value = "${azurerm_sql_database.db_report.id}" }`
There was missing `${}`
Thanks @tombuildsstuff for your time :)

**Comment by tombuildsstuff** [comment]
@mateuszm123111 glad to hear this is now working for you :)
