### ISSUE TITLE
azurerm_kubernetes_cluster: Support for kubeDashboard addon profile

### ISSUE THREAD

**Issue by dominik-lekse** [terraform-providers/terraform-provider-azurerm#4053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- Add support for the AKS addon profile "kubeDashboard" in `azurerm_kubernetes_cluster`
- This would allow to disable the default Kubernetes Dashboard in an AKS cluster

https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#managedclusteraddonprofile

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "test" {
  ...

  addon_profile {
    kube_dashboard {
      enabled = false
    }
  }

  ...
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#managedclusteraddonprofile
* https://medium.com/@patrickpicard_50914/azure-kubernetes-service-disabling-kube-dashboard-fd0135beec60

**Comment by tombuildsstuff** [comment]
Supported via #4139 which shipped in v1.34 - thanks again @dominik-lekse :)
