### ISSUE TITLE
Error when trying to access keyvault secret in other subscription

### ISSUE THREAD

**Issue by ekarlso** [terraform-providers/terraform-provider-azurerm#4055]
### Terraform (and AzureRM Provider) Version
Terraform v0.12.6
+ provider.azurerm v1.32.1
+ provider.helm v0.10.2
+ provider.k8s (unversioned)
+ provider.kubernetes v1.8.1
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

Error: Error looking up Secret "x-db" vault url form id "/subscriptions/x/resourceGroups/x-rg/providers/Microsoft.KeyVault/vaults/x-kv": Error unable to find KeyVault "x-kv" (Resource Group "x-rg): keyvault.VaultsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'x-rg' could not be found."

### Terraform Configuration Files
```
provider "azurerm" {
  subscription_id = var.shared_subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id
  version         = "v1.32.1"
  alias           = "shared"
}
```

```
data "azurerm_key_vault_secret" "app-db-secret" {
  name         = "${terraform.workspace}-app-db"
  key_vault_id = data.terraform_remote_state.cicd-core.outputs.cicd_core_kv_id
  provider = azurerm.shared
}```

### Expected Behavior
Should be able to grab secret in a sub that the SP has access to.

**Comment by nexxai** [comment]
That 404 error is being returned from Azure saying that it can't find the resource group.  I see you replaced the subscription ID with an "x" in your post; can you confirm that the real subscription ID being shown in the error is the ID of the subscription that the key vault actually lives in?  I'm getting the feeling that it might be looking in the wrong subscription (for example looking in your app-db's subscription instead).

**Comment by ekarlso** [comment]
Yes the keyvault is located in the "shared" subscription but the app is actually located in the other subscription.

**Comment by ekarlso** [comment]
@nexxai Any ideas ?

**Comment by nexxai** [comment]
Not off the top of my head, no.  The 404 is Azure saying the key vault "x-kv" doesn't exist in the resource group "x-rg" which is supposed to exist in subscription "x", and that's a pretty well-tested resource in Terraform so I'm not sure what it might be sending.  

Can you confirm that if you just go to the Key Vault in the portal, that in the Properties section on the blade, the Resource ID shown matches character for character the one being shown in the Terraform error?

**Comment by ekarlso** [comment]
Yes indeed I just checked and it's matching.

**Comment by nexxai** [comment]
Ok so then the only thing left to check is that the login or SP that Terraform is using via az cli has rights to that Key Vault.  Are you able to run/dump the results of "az account show" to confirm that it's logged in as you expect?

**Comment by ekarlso** [comment]
Hi, yes I tested this and that works fine.

**Comment by ekarlso** [comment]
Any ideas @nexxai ?

**Comment by nexxai** [comment]
At this point, I'm not sure what else it would be, since the 404 is Microsoft telling you that the account/Service Principal that Terraform is running as doesn't have permission to see that Key Vault.  

You could try running `TFLOG=debug terraform apply` and see if there's anything else in the logs that might hint at something else, but this definitely seems like a permissions issue, not a problem with Terraform itself.

**Comment by ekarlso** [comment]
Well it does have full permission but I am unsure.. Anyways I guess this is partially a anti pattern to use a keyvault in another sub but we're gonna move to hashicorp vault for this now it seems anways.

**Comment by ekarlso** [comment]
Hi, I recently tried to do the same kind of thing just for DNS where the DNS is stored in a shared sub but env's are in a different one, my code block is the following: 

```
provider "azurerm" {
  alias           = "shared"
  subscription_id = var.shared_subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id
  version         = "v1.33.1"
}

resource "azurerm_dns_a_record" "foo-wildcard-record" {
  provider            = "azurerm.shared"
  name                = "*.foo"
  zone_name           = data.terraform_remote_state.dds_dns.outputs.foo.name
  resource_group_name = data.terraform_remote_state.dds_dns.outputs.foo.resource_group_name
  ttl                 = 600

  records = [
    azurerm_public_ip.foo-pip.ip_address
  ]
}```

It crashes with that the RG doesnt exist however I can 
```az group list --subscription $TF_VAR_shared_subscription_id -o table```

Totally fine?

**Comment by timdeluxe** [comment]
For others stumbling over this and searching for solutions:
Documentation here https://www.terraform.io/docs/providers/azurerm/d/key_vault_secret.html says this:

> NOTE: The vault must be in the same subscription as the provider. If the vault is in another subscription, you must create an aliased provider for that subscription.
