### ISSUE TITLE
An example to use Powershell script as custom data while provisioning a VMSS on Azure

### ISSUE THREAD

**Issue by kishorebasisth** [terraform-providers/terraform-provider-azurerm#4065]
I was wondering if it is possible to use Powershell as part of custom data while provisioning a VMSS on Azure, If so can someone post a few examples on how to do that?

As part of the powershell scripts I need to pass few parameters, would be great if the example also covers that. 

For a linux based servers, I would simply use the following:

```
 data "template_file" "cloud_init_config_app" {
 template = "${file("customscripts/cloud_init.sh")}"


vars {
     azure_tenant_id     = "xxxxxxxxxx"
    azure_client_id     = "${var.client_id}"
    azure_client_secret = "${var.client_secret}"
  }
 }
```

I am not sure if the same would also work for Powershell, if not what options do I have? My requirement is to run a PowerShell script once the VM's are booted. I know there exists a Custom Script Extension but I wanted a method where the Powershell script could be stored in the GIT repo along with Terraform sources and not being fetched from storage account/Internet.

Any help would be very appreciated.

**Comment by hbuckle** [comment]
For a Windows scale set you can do the following

```hcl
data "template_file" "auto_logon" {
  template = file("${path.module}/tpl.auto_logon.xml")

  vars = {
    admin_username = var.admin_username
    admin_password = var.admin_password
  }
}

resource "azurerm_virtual_machine_scale_set" "virtual_machine_scale_set" {
  os_profile {
    custom_data = file("${path.module}/init.ps1")
  }
  os_profile_windows_config {
    additional_unattend_config {
      pass         = "oobeSystem"
      component    = "Microsoft-Windows-Shell-Setup"
      setting_name = "AutoLogon"
      content      = data.template_file.auto_logon.rendered
    }

    additional_unattend_config {
      pass         = "oobeSystem"
      component    = "Microsoft-Windows-Shell-Setup"
      setting_name = "FirstLogonCommands"
      content      = file("${path.module}/tpl.first_logon_commands.xml")
    }
  }
}
```
tpl.auto_logon.xml
```xml
<AutoLogon>
  <Password>
    <Value>${admin_password}</Value>
  </Password>
  <Enabled>true</Enabled>
  <LogonCount>1</LogonCount>
  <Username>${admin_username}</Username>
</AutoLogon>
```

tpl.first_logon_commands.xml
```xml
<FirstLogonCommands>
  <SynchronousCommand>
    <CommandLine>cmd /c "copy C:\AzureData\CustomData.bin C:\init.ps1"</CommandLine>
    <Description>CopyScript</Description>
    <Order>11</Order>
  </SynchronousCommand>
  <SynchronousCommand>
    <CommandLine>powershell.exe -sta -ExecutionPolicy Unrestricted -File C:\init.ps1</CommandLine>
    <Description>RunScript</Description>
    <Order>12</Order>
  </SynchronousCommand>
</FirstLogonCommands>
```

This will make the VMs auto logon at first boot and run the script passed in to custom_data

**Comment by kishorebasisth** [comment]
@hbuckle Thanks for the quick response, just a quick question:
* In your init.ps1 file, how did you reference the variables: `${admin_password}`? 
* Is this part here:
```
    additional_unattend_config {
      pass         = "oobeSystem"
      component    = "Microsoft-Windows-Shell-Setup"
      setting_name = "AutoLogon"
      content      = data.template_file.auto_logon.rendered
    }
```
setting these two variables as environment variable that can be used by any Powershell scritps?

**Comment by hbuckle** [comment]
The init.ps1 is the script that will be run when the VM boots, you shouldn't need to pass the password to it. The admin password is used in the `tpl.auto_logon.xml` file and swapped out using the template_file data source. The admin username and password are the same ones you would set in `os_profile`
What the 2 `additional_unattend_config` blocks do is tell Windows to automatically log on as the local admin user the first time the machine boots and then run a command. The command runs the init script, which is copied to C:\AzureData\CustomData.bin by the `custom_data` field.
If you want to pass variables to the init script you can use a template_file data source for that as well

**Comment by kishorebasisth** [comment]
@hbuckle It makes complete sense now, thank a lot for your help.
