### ISSUE TITLE
New resource azurerm_container_registry_webhook

### ISSUE THREAD

**Issue by siddthota** [terraform-providers/terraform-provider-azurerm#4067]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

Does Terraform has a way to create webhook for ACR -> App Service?

Azure CLI can do that, just wondering if there is a hidden feature on Terraform that I'm missing?

**Comment by r0bnet** [comment]
It's currently not possible but as a workaround you could do this via ARM template. Otherwise you should / could request a new resource to be added for this use case.
Fortunately the webhook already exists in the Azure SDK for Go:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerregistry/mgmt/2019-05-01/containerregistry/webhooks.go

So i'd suggest to rename this Issue to something like this: **New resource azurerm_container_registry_webhook**.

Even better you could also add a possible resource design. Use the ARM template as orientation: https://docs.microsoft.com/de-de/azure/templates/microsoft.containerregistry/2019-05-01/registries/webhooks

**Comment by siddthota** [comment]
I'm tryin to pass in the arm template and getting this error. 

`provider "azurerm" {
  version = ">=1.28.0"
}

resource "azurerm_blah-resourcegroup {}

#### Creates container registry resource
**resource "azurerm_container_registry" "container_registry"** {
  name = "myacr-test-blah"
  resource_group_name = "${azurerm.myappresource_data_rg.name}"
  location = "${var.location}"
  admin_enabled = "true"
  sku = "${var.sku}"
}

**resource "azurerm_container_registry" "container_registry_template_webhook"** {
  name = "${azurerm_container_registry.container_registry.name}"
  resource_group_name = "${azurerm.myapp_data_rg.name}"
  location = "${azurerm_container_registry.container_registry.location}"

###   **template_body = <<DEPLOY**
  {
  "$schema": "https://schema.management.azure.com/schemas/2019-08-13/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "myList": {
      "type": "string",
      "metadata": {
        "description": "The list of comma separated items."
      }
    }
  },
  "variables": {
    "myArray": "[split(parameters('myList'),',')]",
    "webhookname": "myproject-acr-webhook",
    "location": "[resourceGroup().location]",
    "dnsLabelPrefix": "terraform-acctest"
  },
  "resources": [
    {
      "name": "[variables('webhook')]",
      "type": "Microsoft.ContainerRegistry/registries/webhooks",
      "apiVersion": "2019-05-01",
      "tags": {},
      "location": "[variables('location')]",
      "properties": {
        "serviceUri": "**myAppServiceWebHook-copiedmanually**",
        "customHeaders": {},
        "status": "enabled",
        "scope": "myapp:latest",
        "actions": [
          "push"
        ]
      }
    }
  ]
}
DEPLOY

###   **deployment_mode = "Incremental"**

}`

I'm currently getting this error -> Error: module.container-registry-webhook.azurerm_container_registry.container_registry_template_webhook: : invalid or unknown key: deployment_mode


Error: module.container-registry-webhook.azurerm_container_registry.container_registry_template_webhook: : invalid or unknown key: template_body

**Comment by siddthota** [comment]
I was trying to inject ARM into my terraform script leading to the following error.

> azurerm_template_deployment.acr-webhook: Error creating deployment: resources.DeploymentsGroupClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplate" Message="Deployment template validation failed: 'The template resource 'myappacrr' for type 'Microsoft.ContainerRegistry/registries/webhooks' at line '1' and column '530' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'." AdditionalInfo=[{"info":{"lineNumber":1,"positionNumber":530,"snippet":""},"type":"TemplateViolation"}]

Here is what I'm trying to do:

1.  Create ACR (without webhook template - since webhook needs service url and other details generated by App Service webapp)
2. Upload Docker Image into ACR
3. Create App Service Webapp using the Docker Image on ACR
4. Copy Webhook URL (Currently copying it manually)
5. Injecting the webhook template to tf script with all required details like serviceurl, status, actions, scope. 

Here is how my TF file looks like 

`locals {
  location 	= "eastus"
  namespace 	= "myapp"
}

resource "azurerm_container_registry" "container_registry" {
  name                = "myappacr"
  resource_group_name = "${azurerm_resourcegroup_blah_myapp.name}"
  location            = "${var.location}"
  admin_enabled       = "true"
  sku                 = "${var.sku}"
}

resource "azurerm_template_deployment" "acr-webhook" {
  name                = "MyApp-ARM"
  resource_group_name = "data-acr-rg"

  template_body = <<DEPLOY
  {
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "registries_myappacr_name": {
            "defaultValue": "myappacr",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.ContainerRegistry/registries",
            "apiVersion": "2017-10-01",
            "name": "[parameters('registries_myappacr_name')]",
            "location": "eastus",
            "tags": {
                "EnvironmentType": "NonProd"
            },
            "sku": {
                "name": "Standard",
                "tier": "Standard"
            },
            "properties": {
                "adminUserEnabled": true
            }
        },
      {
          "name": "[parameters('registries_myappacr_name')]",
          "type": "Microsoft.ContainerRegistry/registries/webhooks",
          "apiVersion": "2019-05-01",
          "tags": {},
          "location": "eastus",
          "properties": {
            "serviceUri": "https://$myapp-appservice-blah:XXXXXXX@myapp-appservice.scm.azurewebsites.net/docker/hook",
            "customHeaders": {},
            "status": "enabled",
            "scope": "myapp-dockerimage:latest",
            "actions": [
              "push"
            ]
          }
      }
    ]
}
DEPLOY

  deployment_mode = "Incremental"
}`
