### ISSUE TITLE
Not able to attach disk using "azurerm_virtual_machine_data_disk_attachment" even with provider version 1.24.0

### ISSUE THREAD

**Issue by AbhishekB15** [terraform-providers/terraform-provider-azurerm#4086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version 

Terraform Version - 0.12.6
AzureRM Provider - 1.24.0

### Affected Resource(s)

azurerm_virtual_machine_data_disk_attachment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

azurerm_virtual_machine_data_disk_attachment.xxxxxxx: Error updating Virtual Machine "xxxxxxxx" (Resource Group "xxxxxx") with Disk "xxxxxxxx": compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 7498.'."

### Expected Behavior

Trying to attach new 3 disks to a VM

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @AbhishekB15 

Thanks for opening this issue.

Taking a look into this this has been fixed in a newer version of the Azure Provider - we're currently on version 1.32.1 - which you can upgrade to by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=1.32.1"
}
```

.. which should solve this for you - would you be able to take a look and see if that works for you?

Thanks!
