### ISSUE TITLE
Add virtual network on batch pool

### ISSUE THREAD

**Issue by ThomasDekeyser** [terraform-providers/terraform-provider-azurerm#4088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
On Batch pool it would be good to have the option of configuring the virtual network.
Especially the VNET & subsnet selection are important for my use case.
This virtual network setting can't be modified after batch-pool-creation (using fe. AZ portal), so currently no manual workarounds possible.

### New or Affected Resource(s)
* azurerm_batch_pool

### References
https://docs.microsoft.com/en-us/azure/batch/batch-virtual-network

**Comment by petems** [comment]
Looks like there's a PR open for this now https://github.com/terraform-providers/terraform-provider-azurerm/pull/5392

**Comment by katbyte** [comment]
Fixed by #5392
