### ISSUE TITLE
Support for Event Grid Domain Topics and Domain-Scope Event Subscriptions

### ISSUE THREAD

**Issue by dreasan** [terraform-providers/terraform-provider-azurerm#4097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There is currently no visible support for adding a domain topic or a domain scope subscription with the provider.

### New or Affected Resource(s)

* azurerm_eventgrid_domain_topic
* azurerm_eventgrid_domain_scope_event_subscription

### References

It's related to this issue, although not exactly the request (as it's suggested to add a topic type)
https://github.com/terraform-providers/terraform-provider-azurerm/issues/2855

**Comment by jrauschenbusch** [comment]
Hi @dreasan,

imho `azurerm_eventgrid_domain_scope_event_subscription` does not need to be an dedicated resource.

See example:
```
resource "azurerm_eventgrid_domain" "test" {
    name =  "test-domain"
}

resource "azurerm_eventgrid_event_subscription" "test" {
    ...
    scope = azurerm_eventgrid_domain.test.id
    ...
}
```

The missing resource `azurerm_eventgrid_domain_topic` is implemented within my linked PR.

**Comment by dreasan** [comment]
hi @jrauschenbusch,

I would agree that the subscription to a domain topic can and should better be handled within the existing resource: `azurerm_eventgrid_event_subscription`

thank you for your contribution!

**Comment by jrauschenbusch** [comment]
@dreasan what i meant was, that this should already work using the `scope` property of `azurerm_eventgrid_event_subscription`. only a domain topic resource was missing, to also be able to subscribe to topics residing in domains.

**Comment by dreasan** [comment]
@jrauschenbusch got it, thanks!
