### ISSUE TITLE
Azure DevOps - azurerm_automation_runbook  created prior to azurerm_automation_account both with implicit and explicit dependencies

### ISSUE THREAD

**Issue by rkrishashokkumar** [terraform-providers/terraform-provider-azurerm#4101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.14

### Affected Resource(s)

azurerm_automation_account

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azurerm_resource_group" "rg_aut" {
  name = "TEST-TMP-${var.env}-NET-AUT-01"
        location = "${var.location}"
        tags = {
            uai = "${var.uai}"
            env = "${var.env}"
            SupportEmail = "${var.supportEmail}"
        }
}

resource "azurerm_automation_account" "aut_acc" {
  
  name                = "TEST-TMP-${var.env}-AUT-ACC-01"
  location            = "westus2" 
  resource_group_name = "${azurerm_resource_group.rg_aut.name}"
  sku_name = "Basic"

   provisioner "local-exec" {
     command = "powershell ../modules/security/Import-PowerShell-Modules.ps1 -automationaccname 'TEST-TMP-${var.env}-AUT-ACC-01' -rgname ${azurerm_resource_group.rg_aut.name} -svcUsername '${var.service_principal_name}' -svcPassword '${var.service_principal_secret}' -tenant '${var.tenantId}' -sub '${var.subscription}'"
  }

  provisioner "local-exec" {
    command = "powershell ../modules/security/Create-RunasAccounts.ps1 -ResourceGroup ${azurerm_resource_group.rg_aut.name} -AutomationAccountName 'TEST-TMP-${var.env}-AUT-ACC-01' -SelfSignedCertPlainPwd '*********' -CreateClassicRunAsAccount $false -svcUsername '${var.service_principal_name}' -svcPassword '${var.service_principal_secret}' -tenant '${var.tenantId}' -sub '${var.subscription}'"
  }
}

resource "azurerm_storage_account" "storageaccount" {
  name                     = "mystorage${lower(var.env)}aut001"
  resource_group_name      = "${azurerm_resource_group.rg_aut.name}"
  location                 = "${azurerm_resource_group.rg_aut.location}"
  account_tier             = "Standard"
  access_tier              = "Cool"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"  
  
  tags = {
            uai = "${var.uai}"
            env = "${var.env}"
            SupportEmail = "${var.supportEmail}"
        }
}

resource "azurerm_storage_container" "blobstorage" {
  name                  = "scripts"
  storage_account_name  = "${azurerm_storage_account.storageaccount.name}"
  container_access_type = "blob"
}


resource "azurerm_storage_blob" "blobobjectfornsgflowlogret" {
  name                   = "NSG-Flowlog-Retention.ps1"
  resource_group_name    = "${azurerm_resource_group.rg_aut.name}"
  storage_account_name   = "${azurerm_storage_account.storageaccount.name}"
  storage_container_name = "${azurerm_storage_container.blobstorage.name}"
  type                   = "block"
  source                 = "../modules/security/NSG-Flowlog-Retention.ps1"
}


resource "azurerm_automation_runbook" "aut_acc_rb_fl" {

  name                = "TEST-TMP-${var.env}-NSG-FL-RET-01"
  location            = "${azurerm_resource_group.rg_aut.location}"
  resource_group_name = "${azurerm_storage_blob.blobobjectfornsgflowlogret.resource_group_name}" 
  account_name        = "${azurerm_automation_account.aut_acc.name}"
  log_verbose         = "true"
  log_progress        = "true"
  
  runbook_type        = "PowerShellWorkflow"

  publish_content_link {
    uri = "http://${azurerm_storage_account.storageaccount.name}.blob.core.windows.net/${azurerm_storage_container.blobstorage.name}/NSG-Flowlog-Retention.ps1"
  }
```

### Expected Behavior

terraform should create resources successfully as per dependency order while azure devops executes. This seems to be working properly when we run terraform from local system. 

### Actual Behavior

It throws the following exception. tried it out both Implicit and Explicit dependencies.

azurerm_automation_runbook.aut_acc_rb_fl: Error creating/updating Automation Runbook "TEST-TMP-XYZ-NSG-FL-RET-01" (Account "TEST-TMP-XYZ-AUT-ACC-01" / Resource Group "TEST-TMP-XYZ-NET-AUT-01"): automation.RunbookClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="{\"Message\":\"Could not find the account. SubscriptionId: xxxx-xxxx-xxxx-xxxxx-xxxxxx AccountName: TEST-TMP-XYZ-AUT-ACC-01\"}"
### Steps to Reproduce

Azure DevOps - PowerShell - Task version 2.*

terraform apply -auto-approve plan.tfstate

### References

* #0000

**Comment by rkrishashokkumar** [comment]
Any update on this please ?

**Comment by tombuildsstuff** [comment]
hi @rkrishashokkumar 

Thanks for opening this issue.

Taking a quick look into this appears to be an issue running inside of Azure DevOps rather than something specific to Terraform; looking at the configuration above I believe this is due to the way that PowerShell's being invoked, where when running locally it's running within an interactive terminal (since there's a TTY attached to the parent `terraform` process) and as such it's blocking - whereas running it in a CI server (non-interactively) it may behave differently.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). Since this appears to be an issue regarding usage in Azure DevOps I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
