### ISSUE TITLE
Inconsistent behavior using consistency level [Session] when creating cosmos db account

### ISSUE THREAD

**Issue by smartpcr** [terraform-providers/terraform-provider-azurerm#4118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
**v0.12.6**

### Affected Resource(s)
**azurerm_cosmosdb_account**

### Terraform Configuration Files

- main.tf
```hcl
resource "azurerm_resource_group" "cosmosdb" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
}

resource "azurerm_cosmosdb_account" "cosmosdb_account" {
  name                      = "${var.cosmos_db_account}"
  location                  = "${azurerm_resource_group.cosmosdb.location}"
  resource_group_name       = "${azurerm_resource_group.cosmosdb.name}"
  offer_type                = "${var.cosmos_db_offer_type}"
  kind                      = "GlobalDocumentDB"
  enable_automatic_failover = true
  ip_range_filter           = "${var.enable_filewall ? "${var.allowed_ip_ranges}" : ""}"

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    prefix            = "${var.cosmos_db_account}-customid"
    location          = "${azurerm_resource_group.cosmosdb.location}"
    failover_priority = 0
  }

  geo_location {
    location          = "${var.alt_location}"
    failover_priority = 1
  }
}

resource "azurerm_cosmosdb_sql_database" "sqldb" {
  name                = "${var.cosmos_db_name}"
  resource_group_name = "${azurerm_cosmosdb_account.cosmosdb_account.resource_group_name}"
  account_name        = "${azurerm_cosmosdb_account.cosmosdb_account.name}"
}

```

### Expected Behavior

Should not need to specify the following variables when using `Session` consistency level:
- max_interval_in_seconds 
- max_staleness_prefix    

### Actual Behavior

It complains that `max_staleness_prefix` needs to be greater then 100000 and `max_interval_in_seconds ` needs to be greater then 300

After change the values to 100000 and 300, re-apply changes, it then detect the values should be changed from defaults:
- max_interval_in_seconds = 5 -> 300
- max_staleness_prefix = 100 -> 100000

Note: The above change was never applied (after 20 min)

**Comment by peterbev** [comment]
The issue appears to occur whenever there are multiple geo locations configured, provider insists on max_staleness_prefix and max_interval_in_seconds being set to the minimums required for BoundedStaleness
