### ISSUE TITLE
QNA Maker "kind" for Azure Cognitive Service

### ISSUE THREAD

**Issue by kevinsorenson** [terraform-providers/terraform-provider-azurerm#4124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Azure Cognitive Service "kind" field is missing the Qna Maker option.  This service is critical to all of our Azure chatbots, and there are 2 dozen other "kinds" of cognitive services already supported by Terraform, so I believe it's just 1 field to update.

### New or Affected Resource(s)

Cognitive Services

* azurerm_cognitive_account

### Potential Terraform Configuration

```hcl

resource "azurerm_cognitive_account" "QnA1" {
  name                = "qnamaker-1"
  location            = "East US"
  resource_group_name = "myresourcegroup"
  kind                = "QnAMaker"

  sku {
    name = "S0"
    tier = "Standard"
  }
}
```

### References

* #0000

**Comment by kevinsorenson** [comment]
Also requested in [https://github.com/terraform-providers/terraform-provider-azurerm/issues/3957](url)

**Comment by nexxai** [comment]
Submitted PR here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4124
