### ISSUE TITLE
add azurerm_proximity_placement_group resource

### ISSUE THREAD

**Issue by adubnik** [terraform-providers/terraform-provider-azurerm#4127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure introduced a new feature - Proximity Placement Group which allows placing VMs in the close network proximity from one another.

### New or Affected Resource(s)

* azurerm_proximity_placement_group

* azurerm_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_proximity_placement_group" "ppg" {
  name                = "myppg"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  tags = {
    Hello = "World"
  }
}

resource "azurerm_virtual_machine" "main" {
 
# PPG ID is optional parameter, forces the new resource
  proximity_placement_group_id = "${azurerm_proximity_placement_group.ppg.id}"

 # Standard VM sample from the TF docs
  name                  = "${var.prefix}-vm"
  location              = "${azurerm_resource_group.main.location}"
  resource_group_name   = "${azurerm_resource_group.main.name}"
  network_interface_ids = ["${azurerm_network_interface.main.id}"]
  vm_size               = "Standard_DS1_v2"

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  # delete_os_disk_on_termination = true


  # Uncomment this line to delete the data disks automatically when deleting the VM
  # delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
  storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  os_profile {
    computer_name  = "hostname"
    admin_username = "testadmin"
    admin_password = "Password1234!"
  }
  os_profile_linux_config {
    disable_password_authentication = false
  }
  tags = {
    environment = "staging"
  }
}

```

### References

https://docs.microsoft.com/en-ie/azure/virtual-machines/linux/proximity-placement-groups

**Comment by nexxai** [comment]
This is being worked on [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4020)
