### ISSUE TITLE
terrafrom plan fails with Error: Error making Read request on Azure KeyVault Secret

### ISSUE THREAD

**Issue by mattbowes** [terraform-providers/terraform-provider-azurerm#4146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.6
+ provider.azuread v0.5.1
+ provider.azurerm v1.33.0
+ provider.null v2.1.2
+ provider.random v2.2.0
### Affected Resource(s)

* `azurerm_key_vault_secret`
* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
 data "azurerm_key_vault_secret" "test" {
  name         = "test"
  key_vault_id = "${data.azurerm_key_vault.keyvault.id}"
}

data "azurerm_key_vault" "keyvault" {
  name                = "${var.keyvault_name}"
  resource_group_name = "${var.keyvault_resource_group_name}"
}

```

### Debug Output

2019/08/21 00:00:10 [ERROR] module.removed: eval: *terraform.EvalSequence, err: Error making Read request on Azure KeyVault Secret removed: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://removed.vault.azure.net/secrets/removed/?api-version=2016-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Get http://localhost:50342/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net: EOF'

### Expected Behavior

Terraform should plan 

### Actual Behavior

Error: Error making Read request on Azure KeyVault Secret removed: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://removed.vault.azure.net/secrets/removed/?api-version=2016-10-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Get http://localhost:50342/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net: EOF'
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The error occurs on the first run of a new Azure Cloud Shell session. If rerun `terrafrom plan` right after the failure then it plans correctly the second time 

### References

* #0000

**Comment by rkno82** [comment]
This issue occurs not just at the first run of terraform and/ or by using plan. The "timeout" can occur at any time and even while applying/ destroying your infrastructure.

We are using KeyVault for just 20 credentials, but it's already awful. :(

**Comment by mihaicoldea** [comment]
The main issue causing this is tracked at https://github.com/hashicorp/go-azure-helpers/issues/22.
IT requires user votes in order to get Hashicorp attention.
