### ISSUE TITLE
azurerm_postgresql_virtual_network_rule subnet_id broken

### ISSUE THREAD

**Issue by byF** [terraform-providers/terraform-provider-azurerm#4147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
TF 0.12.6
AzureRM 1.33.0

### Affected Resource(s)

* `azurerm_postgresql_virtual_network_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_virtual_network_rule" "test" {
  name                                 = "aks-access"
  resource_group_name                  = azurerm_resource_group.rg.name
  server_name                          = azurerm_postgresql_server.db.name
  subnet_id                            = "/subscriptions/ZZZ/resourceGroups/MC_XXX_XXX/providers/Microsoft.Network/virtualNetworks/aks-vnet-XXX/subnets/aks-subnet"
  ignore_missing_vnet_service_endpoint = true
}
```

### Expected Behavior

The rule is created

### Actual Behavior

```
Error: Can not parse "subnet_id" as a resource id: Cannot parse Azure ID: parse /subscriptions/ZZZ/resourceGroups/MC_XXX_XXX/providers/Microsoft.Network/virtualNetworks/aks-vnet-25407968/subnets/aks-subnet
: net/url: invalid control character in URL
```

I was able to create the rule in CLI with the same values I provided in TF configuration:

```bash
~ az postgres server vnet-rule create --resource-group XYZ --server-name XYZ --name aks-access --subnet /subscriptions/XXX/resourceGroups/MC_XXX_XXX/providers/Microsoft.Network/virtualNetworks/aks-vnet-25407968/subnets/aks-subnet
[
  {
    "id": "/subscriptions/ZZZ/resourceGroups/XYZ/providers/Microsoft.DBforPostgreSQL/servers/XXX/virtualNetworkRules/aks-acess",
    "ignoreMissingVnetServiceEndpoint": false,
    "name": "aks-access",
    "resourceGroup": "XXX",
    "state": "Ready",
    "type": "Microsoft.DBforPostgreSQL/servers/virtualNetworkRules",
    "virtualNetworkSubnetId": "/subscriptions/ZZZ/resourceGroups/MC_XXX_XXX/providers/Microsoft.Network/virtualNetworks/aks-vnet-25407968/subnets/aks-subnet"
  }
]
```

### Steps to Reproduce

1. `terraform apply`

**Comment by byF** [comment]
Apparently the same thing is happening for `virtual_network_rule` in `azurerm_cosmosdb_account`

**Comment by r0bnet** [comment]
The problem comes from the underlying `net/url` `ParseRequestURI` and i could reproduce this behaviour when i added a control character into the `subnet_id` like `\n`. But with the value you provided above as subnet_id it works fine for me.

**Comment by byF** [comment]
Gah, you're right of course... there was a trailing new line making its way through the variable into my configuration 🙄
