### ISSUE TITLE
azurerm_vnet_private_link_service

### ISSUE THREAD

**Issue by mybayern1974** [terraform-providers/terraform-provider-azurerm#4156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support a new Azure resource. The implementation is on going.

### New or Affected Resource(s)

azurerm_vnet_private_link_service

### Potential Terraform Configuration

```hcl
resource "azurerm_vnet_private_link_service" "test" {
    location                                    = "West US 2"
    auto_approval_subscription_names            = [""]
    fqdns                                       = [""]
    ip_configuration    = {
        private_ip_address                      = ""
        private_ip_address_version              = "" # {IPv4 | IPv6}
        allocation_method                       = "" # {Dynamic | Static}
        public_ip_address_id                    = azurerm_public_ip.test.id
        subnet_id                               = azurerm_subnet.test2.id
    }
    load_balancer_frontend_ip_configurations    = azurerm_lb.test.private_ip_addresses
    # private_endpoint_connection_id             =    # This seems like it would create a circular link so leaving out for now
    visibility_subscription_names               = [""]
}
```

**Comment by WodansSon** [comment]
@mybayern1974 How is this different than the existing [azurerm_private_link_service](https://www.terraform.io/docs/providers/azurerm/r/private_link_service.html)?
