### ISSUE TITLE
azurerm_vnet_private_endpoint

### ISSUE THREAD

**Issue by mybayern1974** [terraform-providers/terraform-provider-azurerm#4157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support a new [Azure resource](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview). 

### New or Affected Resource(s)

* azurerm_vnet_private_endpoint

### Potential Terraform Configuration

```hcl
resource "azurerm_vnet_private_endpoint" "test" {
    location                                    = "West US 2"
    subnet_id                                   = azurerm_subnet.test.id
    private_link_service_ connection            = {         # configuration can contain multiple of these
        group_ids                       = [""]
        private_link_ service_id        = azurerm_vnet_private_link_service.test.id
        request_message                 = ""
    }
    manual_private_link_service_ connection     = {        # configuration can contain multiple of these
        group_ids                       = [""]
        private_link_ service_id        = azurerm_vnet_private_link_service.test.id
        request_message                 = ""
    }
}
```

**Comment by tombuildsstuff** [comment]
hi @mybayern1974 

Thanks for opening this issue :)

Support for Service Endpoints is available via the `service_endpoints` block within [the `azurerm_subnet` resource](https://www.terraform.io/docs/providers/azurerm/r/subnet.html#service_endpoints), rather than on each specific resource (which instead takes the Subnet ID to connect to) - would you be able to take a look and see if that works for you? Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by mybayern1974** [comment]
hi @tombuildsstuff , this resource is a new resource rather than the service_endpoints that is a property of the existing resource [azurerm_subnet_resource](https://www.terraform.io/docs/providers/azurerm/r/subnet.html#service_endpoints)

I realized I may use a wrong resource-description link in the description section of this issue, so I just remove that hyperlink. 

To explain in the Azure CLI (command line tool) perspective, this resource is for this [command](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest), while the property you mentioned is for this [command](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#optional-parameters)
