### ISSUE TITLE
azurerm_p2s_vpn_gateway

### ISSUE THREAD

**Issue by mybayern1974** [terraform-providers/terraform-provider-azurerm#4159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support a new [Azure resource](https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-gateway-settings).

### New or Affected Resource(s)

* azurerm_p2s_vpn_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_p2s_vpn_gateway" "test" {
    # Required
    name                                = "p2sgw1"
    location                            = "West US 2"
    resource_group_name                 = ""
    virtual_hub_id                      = azurerm_virtual_hub.test.id
    p2s_vpn_server_configuration_id     = azurerm_p2s_vpn_server.test.id

    # Optional
    custom_route_address_prefixes       = [""]
    vpn_client_address_pool_prefixes    = [""]
    scale_unit                          = 3
    tags = {

    }
}
```

**Comment by tombuildsstuff** [comment]
hi @mybayern1974 

Thanks for opening this issue.

Support for this is available in [the `azurerm_virtual_network_gateway` resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway.html) which I believe should be what you're looking for - would you be able to confirm if this works for you?

I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by mybayern1974** [comment]
hi @tombuildsstuff , this requested resource is not the same as [azurerm_virtual_network_gateway_connection resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway_connection.html) you suggested here, instead, it is the sub-resource of the resource azurerm_virtual_wan, whose current status is lack of some sub-resources. So it's fine to close this issue but I suggest setup the link between this issue and the issue #3279
