### ISSUE TITLE
azurerm_p2s_vpn_server

### ISSUE THREAD

**Issue by mybayern1974** [terraform-providers/terraform-provider-azurerm#4160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support a new Azure resource

### New or Affected Resource(s)

* azurerm_p2s_vpn_server

### Potential Terraform Configuration

```hcl
resource "azurerm_p2s_vpn_server" "test" {
    # Required
    name                        = "vpns1"
    location                    = "West US 2"
    resource_group_name         = ""
    virtual_wan_id              = azurerm_virtual_wan.test.id
    vpn_protocols               = [""]  # {SSTP | IkeV2 | OpenVPN}

    # Optional
    radius_configuration = {
        server_address               = ""
        server_secret                = ""
        client_root_certificate     = {     # configuration can contain multiple of these
            name        = ""
            thumbprint  = ""
        }
        server_root_certificate     = {     # configuration can contain multiple of these
            name        = ""
            public_cert = ""
        }
    }
    vpn_client_configuration = {
        revoked_certificate     = {         # configuration can contain multiple of these
            name        = ""
            thumbprint  = ""
        }
        root_certificate        = {         # configuration can contain multiple of these
            name        = ""
            public_cert = ""
        }
        ipsec_policy            = {                         # configuration can contain multiple of these
            sa_life_time_seconds        = 86472
            sa_data_size_kilobytes      = 429497
            ipsec_encryption            = "AES256"          # {AES128 | AES192 | AES256 | DES | DES3 | GCMAES128 | GCMAES192 | GCMAES256 | None}
            ipsec_integrity             = "SHA256"          # {GCMAES128 | GCMAES192 | GCMAES256 | MD5 | SHA1 | SHA256}
            ike_encryption              = "AES256"          # {AES128 | AES192 | AES256 | DES | DES3 | GCMAES128 | GCMAES256}
            ike_integrity               = "SHA384"          # {GCMAES128 | GCMAES256 | MD5 | SHA1 | SHA256 | SHA384}
            dh_group                    = "DHGroup14"       # {DHGroup1 | DHGroup14 | DHGroup2 | DHGroup2048 | DHGroup24 | ECP256 | ECP384 | None}
            pfs_group                   = "PFS14"           # {ECP256 | ECP384 | None | PFS1 | PFS14 | PFS2 | PFS2048 | PFS24 | PFSMM}
        }
    }
}
```

**Comment by tombuildsstuff** [comment]
hi @mybayern1974 

Thanks for opening this issue.

Support for this is available in [the `azurerm_virtual_network_gateway` resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway.html) which I believe should be what you're looking for - would you be able to confirm if this works for you?

I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by mybayern1974** [comment]
hi @tombuildsstuff , this requested resource is not the same as [azurerm_virtual_network_gateway resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway.html) you suggested here, instead, it is the sub-resource of the resource azurerm_virtual_wan, whose current status is lack of some sub-resources. So it's fine to close this issue but I suggest setup the link between this issue and the issue #3279
