### ISSUE TITLE
Azure SQL Vulnerability Assessment

### ISSUE THREAD

**Issue by chfrodin** [terraform-providers/terraform-provider-azurerm#4161]
Hi,

 Having to implement this using ARM is shaky at best.

/Chris

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd be great to have not only have support for Threat Detection on Azure SQL, but also Vulnerability Assessment.
See: https://docs.microsoft.com/en-us/azure/sql-database/sql-vulnerability-assessment

### New or Affected Resource(s)

* azurerm_sql_server
* azurerm_sql_database

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #3806 - thanks again @benjamin37 :)
