### ISSUE TITLE
Feature Request: Set Access Control (IAM) on resource group

### ISSUE THREAD

**Issue by BarnumD** [terraform-providers/terraform-provider-azurerm#4167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'm looking on azurerm_resource_group to try to find out where I can add a role assignment to the access control (IAM) tab of a resource group.  If that's not in the module yet, could it be added?

### New or Affected Resource(s)

* azurerm_resource_group

**Comment by tombuildsstuff** [comment]
hi @BarnumD 

Thanks for opening this issue :)

Support for Role Assignments is available via [the `azurerm_role_assignment` resource](https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html) - would you be able to take a look and see if that works for you? I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
