### ISSUE TITLE
azurerm_application_gateway - sku capacity limited to 10

### ISSUE THREAD

**Issue by BruiserT** [terraform-providers/terraform-provider-azurerm#4188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Shouldn't the application gateway sku capacity limit be increased to azure's limit of 32. In the Azure portal I can create a WAF_Large WAF with resource count of 32. 

### Terraform (and AzureRM Provider) Version

Terraform v0.12.6
provider.azurerm v1.32.1

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  sku {
    name     = "WAF_Large"
    tier     = "WAF"
    capacity = 32
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = "${azurerm_subnet.frontend.id}"
  }

  frontend_port {
    name = "${local.frontend_port_name}"
    port = 80
  }

  frontend_ip_configuration {
    name                 = "${local.frontend_ip_configuration_name}"
    public_ip_address_id = "${azurerm_public_ip.test.id}"
  }

  backend_address_pool {
    name = "${local.backend_address_pool_name}"
  }

  backend_http_settings {
    name                  = "${local.http_setting_name}"
    cookie_based_affinity = "Disabled"
    path                  = "/path1/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 1
  }

  http_listener {
    name                           = "${local.listener_name}"
    frontend_ip_configuration_name = "${local.frontend_ip_configuration_name}"
    frontend_port_name             = "${local.frontend_port_name}"
    protocol                       = "Http"
  }

  request_routing_rule {
    name                       = "${local.request_routing_rule_name}"
    rule_type                  = "Basic"
    http_listener_name         = "${local.listener_name}"
    backend_address_pool_name  = "${local.backend_address_pool_name}"
    backend_http_settings_name = "${local.http_setting_name}"
  }
}


```

### Debug Output

Terraform command 'plan' failed with exit code '1'.:  expected sku.0.capacity to be in the range (1 - 10), got 32

### Expected Behavior

Deploy Azure's limit of 32

### Actual Behavior

Error message stating your limited to a range capacity of 10 

### Steps to Reproduce

1. `terraform plan`

**Comment by nexxai** [comment]
PR submitted: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4189
