### ISSUE TITLE
azurerm sas token format

### ISSUE THREAD

**Issue by jontreynes** [terraform-providers/terraform-provider-azurerm#4191]
Terraform v0.12.0

I am trying to figure out how to use the azurerm backend when authenticating using a SAS Token associated with the Storage Account as documented [here](https://www.terraform.io/docs/backends/types/azurerm.html)

It does not quite specify where exactly the sas token should be generated as you can create a sas token at the service level and the specific object level.

Anyways, Terraform complains when I do:

```
terraform {
  backend "azurerm" {
    storage_account_name = "abcd1234"
    container_name       = "tfstate"
    key                  = "prod.terraform.tfstate"

    # rather than defining this inline, the SAS Token can also be sourced
    # from an Environment Variable - more information is available below.
    sas_token = "sp=rcwd&st=1990-08-28T22:31:27Z&se=2030-09-01T06:31:27Z&spr=https&sv=2018-03-28&sig=randomrandom%random%random%random%random%randomr=d"
  }
}
```

Error creating storage client for storage account "<myaccount>": azure: malformed storage account key: illegal base64 data at input byte 2

Does it need to be a specific format?

**Comment by r0bnet** [comment]
Hey @jontreynes,
i had a look into this and the backend configuration is part of the main terraform repository and should be addressed [there](https://github.com/hashicorp/terraform).

I had also a look into their acceptance test for the SAS token and they use a format that starts with a `?`. So before creating another issue in the other board try to add a `?` in front of the sas token.

Example:
```hcl
terraform {
  backend "azurerm" {
    ...
    sas_token = "?sp=rcwd&st=1990-08-28T22:31:27Z&se=2030-09-01T06:31:27Z&spr=https&sv=2018-03-28&sig=randomrandom%random%random%random%random%randomr=d"
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @jontreynes 

Since we've not heard back from you here I'm going to close this issue for the moment - however please let us know if @r0bnet's suggestions above don't work for you and we'll take another look

Thanks!
