### ISSUE TITLE
Comma-separated source/destination addresses are not supported on NSG rules

### ISSUE THREAD

**Issue by stefan-rapp** [terraform-providers/terraform-provider-azurerm#4194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.6
+ provider.azurerm v1.33.1

### Affected Resource(s)

* `azurerm_network_security_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_rule" "nsg_rule" {
  name                        = "AllowSQLRemote"
  priority                    = 105
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "1433"
  destination_port_range      = "1433"
  source_address_prefix       = "10.56.2.5,172.56.41.20"
  destination_address_prefix  = "10.57.4.0/24,192.168.5.5"
  resource_group_name         = "rg-toporg-vnet-internaltest"
  network_security_group_name = "nsg-vnet-toporg-internaltest-TestSubnet"
}
```

### Expected Behavior

Terrafrom should add comma-separated IP addresses on the NSG rule, like the following screenshot of the Azure Portal illustrates (example).

![CSV_NSG_Rule](https://user-images.githubusercontent.com/45358082/64002561-a03d6380-cb0a-11e9-9e69-630d3ea977fa.png)

### Actual Behavior

The following error occured

`Error: Error Creating/Updating Network Security Rule "AllowSQLRemote" (NSG "nsg-vnet-toporg-internaltest-TestSubnet" / Resource Group "rg-toporg-vnet-internaltest"): network.SecurityRulesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SecurityRuleInvalidAddressPrefix" Message="Security rule /subscriptions/49bae408-b249-42fd-99d7-78ddf58ee3d3/resourceGroups/rg-toporg-vnet-internaltest/providers/Microsoft.Network/networkSecurityGroups/nsg-vnet-toporg-internaltest-TestSubnet/securityRules/AllowSQLRemote has invalid Address prefix. Value provided: 10.56.2.5,172.56.41.20" Details=[]`

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hey @stefan-rapp 

Thanks for opening this issue.

Support for this is available [via the `source_address_prefixes` field](https://www.terraform.io/docs/providers/azurerm/r/network_security_rule.html#source_address_prefixes) - which takes a list rather than exposing this as a comma separated string - would you be able to take a look and see if this works for you?

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look :)

Thanks!
