### ISSUE TITLE
Application gateway : other backend pool target types

### ISSUE THREAD

**Issue by pjeannet-dior** [terraform-providers/terraform-provider-azurerm#4200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello, while creating an application gateway in front of an app serice using `fqdn` in the `backend_address_pool` works, other backend pool types exist appart from IP and fqdn : 
- Virtual Machine
- VM Scale Set
- App Service

See following screen of the backend pool creation blade from the Azure portal, the last three ones can't be configured with terraform : 

![image](https://user-images.githubusercontent.com/47103110/64031561-f3cea200-cb48-11e9-83e3-5e884f896c6f.png)

### New or Affected Resource(s)

Block `backend_address_pool` from `azurerm_application_gateway`

### Potential Terraform Configuration

For example with an app service :

```hcl
data "azurerm_app_service" "test" {
  name                = "search-app-service"
  resource_group_name = "search-service"
}

resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = "azurerm_resource_group.test.name
  location            = "azurerm_resource_group.test.location

  backend_address_pool {
    name = local.backend_address_pool_name
    app_service_id = data.azurerm_app_service.id
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @pjeannet-dior 

Thanks for opening this issue.

Unfortunately the Azure Portal behaves a little differently to the API's, in that it appears that it's possible to configure this in both places (when under the hood it's obtaining this information from the original API and updating it - for example you can see this in the Developer Tools).

As such these configurations need to be configured either on the Network Interface (for the Virtual Machine, using [the `azurerm_network_interface` / `azurerm_network_interface_application_gateway_backend_address_pool_association` resources](https://www.terraform.io/docs/providers/azurerm/r/network_interface_application_gateway_backend_address_pool_association.html)) or [the `load_balancer_backend_address_pool_ids` field for a Virtual Machine Scale Set](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html#load_balancer_backend_address_pool_ids). Taking a look at adding a Web App to an Application Gateway, [by taking a look at this script](https://docs.microsoft.com/en-us/azure/application-gateway/create-web-app#configure-a-web-application-behind-a-new-application-gateway) uses the `fqdns` field within the `backend_address_pool` block on the Application Gateway itself.

As such I believe all of this should be possible and as such I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
