### ISSUE TITLE
AppService Backup Documentation is incorrect for Backup Name

### ISSUE THREAD

**Issue by andydkelly-ig** [terraform-providers/terraform-provider-azurerm#4223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.14
+ provider.azurerm v1.33.1

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
esource "azurerm_app_service" "default" {
  name                = "${var.appServiceName}"
  location            = "${var.appServiceLocation}"
  resource_group_name = "${var.resource_group_name}"
  app_service_plan_id = "${var.uiServicePlanId}"
  client_affinity_enabled  = "${var.clientAffinityEnabled}"


  site_config {
    dotnet_framework_version = "${var.dotnetFrameworkVersion}"
    websockets_enabled       = "${var.websocketsEnabled}"
    always_on                = "${var.alwaysOn}"
    http2_enabled            = "${var.http2Enabled}"
    default_documents        = "${var.defaultDocuments}"
    scm_type                 = "${var.scmType}"
  }

  app_settings {
    "AppInsightsInstrumentationKey"         = "${var.appInsightsInstrumentationKey}"
  }

  backup {
    "backup_name"                          = "${var.appServiceBackupName}"
    "enabled"                       = "${var.appServiceBackupEnabled}"
    "storage_account_url"           = "${var.appServiceBackupStorageAccountUrl}"    
  

    schedule {
      "frequency_interval"            = "${var.appServiceBackupFrequencyInterval}"
      "frequency_unit"                = "${var.appServiceBackupFrequencyUnit}"
      "keep_at_least_one_backup"      = "${var.appServiceBackupKeepOneBackup}"
      "start_time"                    = "${var.appServiceBackupStartTime}"
    }
  }
```

### Expected Behavior

According to the [documentation](https://www.terraform.io/docs/providers/azurerm/r/app_service.html), this should provision an App Service with a Backup Schedule. 

![image](https://user-images.githubusercontent.com/42772281/64162031-87002400-ce36-11e9-9513-02536b0496f0.png)

### Actual Behavior

Terraform throws an error because the correct Backup Syntax is `name` not `backup_name`. The documentation needs amending.

![image](https://user-images.githubusercontent.com/42772281/64161979-6f28a000-ce36-11e9-9afa-2992f9cbfb4b.png)

**Comment by nexxai** [comment]
Submitted PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/4265
