### ISSUE TITLE
Have the possibility to add an Azure VNET/Subnet to access an Azure Container Registery (Firewalls and virtual networks)

### ISSUE THREAD

**Issue by Imed-Eden** [terraform-providers/terraform-provider-azurerm#4236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We want to restrain the network access to our ACR (Azure Container Registry). For this, from the portal we have the ability to use the feature called Firewalls and virtual networks and select a specific VNET/Subnet to be able to access the ACR. However, Terraform does not seem to be able to provide us an attribute to configure that.

Currently, it appears that we can only use network_rule_set that supports the following:

- default_action
- ip_rule

So we can only specify CIDR or a public IP but what about a specific subnet inside a VNET? Because we can configure that for other services like Account Storage using the virtual_network_subnet_ids : 

```  
network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices"]
    virtual_network_subnet_ids = ["${azurerm_subnet.test.id}"]
}
```

### New or Affected Resource(s)
Terraform v0.12.7
+ provider.azurerm v1.33.1

### Terraform Configuration
``` 
  network_rule_set {
       default_action             = "Deny"
  }
```

Thank you in advance :)

**Comment by r0bnet** [comment]
Should be fixed with: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4293
