### ISSUE TITLE
Allow Application Gateway OWASP 3.1

### ISSUE THREAD

**Issue by sgissinger** [terraform-providers/terraform-provider-azurerm#4237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Application Gateway now support OWASP version 3.1.

When trying to set this version in Terraform we get this message
```
expected waf_configuration.0.rule_set_version to be one of [2.2.9 3.0], got 3.1
```

![image](https://user-images.githubusercontent.com/1426742/64243747-293c0c80-cf08-11e9-827a-4e877c70ada4.png)

### New or Affected Resource(s)

* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "main" {
  ...
  waf_configuration {
    enabled          = true
    firewall_mode    = "Detection"
    rule_set_type    = "OWASP"
    rule_set_version = "3.1"
  }
}
```

**Comment by nexxai** [comment]
Submitted PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/4263
