### ISSUE TITLE
Updating Kafka feature for Azure Eventhub Namespace fails

### ISSUE THREAD

**Issue by pather87** [terraform-providers/terraform-provider-azurerm#4239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.7
+ provider.azurerm v1.33.1

### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "ns" {
  name                     = var.namespace
  location                 = var.location
  resource_group_name      = var.resource_group_name
  sku                      = var.sku
  capacity                 = var.capacity
  auto_inflate_enabled     = var.auto_inflate_enabled
  maximum_throughput_units = var.maximum_throughput_units
  kafka_enabled            = var.kafka_enabled

  tags = var.tags
}
```

### Expected Behavior

Eventhub Namespace should destroy / create as updating kafka feature is not supported.

### Actual Behavior

Terraform fails with error:
Error: eventhub.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Updating the KafkaEnabled property on a namespace is not supported. CorrelationId: xxxx

## Steps to Reproduce

1. `terraform apply`
2. Change kafka_enabled to either true/false
3. `terraform apply`

**Comment by nexxai** [comment]
Submitted PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/4264

**Comment by mapdegree** [comment]
Just tested it via terraform with the provider version mentioned above and still returning the error message.

`* azurerm_template_deployment.event_hub_kafka_enabled_firewallrule: Error waiting for deployment: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"message\": \"Updating the KafkaEnabled property on a namespace is not supported. CorrelationId: af6cce11-e2d9-9674-6839-ceaaa9fb35e7\",\r\n    \"code\": \"BadRequest\"\r\n  }\r\n}"}]`

**Comment by tombuildsstuff** [comment]
@mapdegree unfortunately that's not supported using an ARM Template Deployment - this fix applies to [the Terraform resource `azurerm_eventhub_namespace`](https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace.html).
