### ISSUE TITLE
Auto-Shutdown in Azure

### ISSUE THREAD

**Issue by danieljax88** [terraform-providers/terraform-provider-azurerm#4255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Would liek to utilise Azure Dev Labs Auto Shutdown feature of a VM. It is hugely important for our organization to be able to shutdown our machines out of hours

### New or Affected Resource(s)

All Vm resources

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @danieljax88 

Just to let you know that support for this shipped in v1.33.1 - you can upgrade to this by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=1.33.1"
}
```

Taking a look at the Terraform Website it appears that this link is currently missing from the sidebar - [but you can find this here](https://www.terraform.io/docs/providers/azurerm/r/dev_test_lab_schedule.html) - would you be able to take a look and see if this works for you?

Thanks!
