### ISSUE TITLE
data.azurerm_virtual_network does not return the location attribute

### ISSUE THREAD

**Issue by BrendanThompson** [terraform-providers/terraform-provider-azurerm#4278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the Data Source for `azurerm_virtual_network` does not return the `location` attribute, something that is passed in for the resource itself. Although it could be said that there is always going to a dependency on an `azurerm_resource_group` which holds a `location` it would be ideal to have the `location` accessible via the `azurerm_virtual_network` DS too.

### New or Affected Resource(s)

* azurerm_virtual_network

### Potential Terraform Configuration

```hcl
data "azurerm_virtual_network" "example" {
  name                             = "vn-meow"
  resource_group_name = "rg-meow"
}

output "vn_location" {
  value = data.azurerm_virtual_network.example.location
}
```

**Comment by r0bnet** [comment]
Should be done here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4281
