### ISSUE TITLE
HTTP_1_1_REQUIRED error returned on calls

### ISSUE THREAD

**Issue by cchatfield** [terraform-providers/terraform-provider-azurerm#428]
Not sure if this is an issue with the AZURE mgmt api or if there is a change in the provider. This is also occurring for packer builds as well.

In the last 24 hours, I have gone from being able to run apply/destroy without issues to receiving errors on API calls

Terraform 0.10.7
Azure Provider v0.2.2

For terraform, some calls go through just fine and after a certain point api calls all return HTTP_1_1_REQUIRED. 
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: 2017/10/13 16:47:25 [DEBUG] AzureRM Request:
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: GET /subscriptions/xxxxx/resourceGroups/xxxx-core-prod-core-five/providers/Microsoft.Network/routeTables/xxxx-core-prod-route-table-five?api-version=2017-03-01 HTTP/1.1
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: Host: management.azure.com
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: User-Agent: HashiCorp-Terraform-v0.10.0-dev
2017/10/13 16:47:25 [TRACE] root: eval: *terraform.EvalVariableBlock
2017/10/13 16:47:25 [TRACE] root: eval: *terraform.EvalCoerceMapVariable
2017/10/13 16:47:25 [TRACE] root: eval: *terraform.EvalTypeCheckVariable
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: Authorization: Bearer  Redacted
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: Accept-Encoding: gzip
\
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: 
2017-10-13T16:47:25.493-0600 [DEBUG] plugin.terraform-provider-azurerm_v0.2.2_x4: 
2017/10/13 16:47:25 [ERROR] root.network_five: eval: *terraform.EvalSequence, err: azurerm_route_table.nat: Error making Read request on Azure Route Table foodflip-core-prod-route-table-five: network.RouteTablesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/foodflip-core-prod-core-five/providers/Microsoft.Network/routeTables/xxxx-core-prod-route-table-five?api-version=2017-03-01: stream error: stream ID 97; HTTP_1_1_REQUIRED

For packer, the first call fails

Build 'azure-arm' errored: storage.AccountsClient#ListKeys: Failure sending request: StatusCode=0 -- Original Error: Post https://management.azure.com/subscriptions/xxxxx/resourceGroups/foodflip-storage/providers/Microsoft.Storage/storageAccounts/xxxx/listKeys?api-version=2016-12-01: stream error: stream ID 1; HTTP_1_1_REQUIRED

Direct calls via POSTMAN work without issue.

**Comment by cchatfield** [comment]
After 24 hours, the Azure API started responding correctly to the calls.

**Comment by tombuildsstuff** [comment]
Hey @cchatfield

Thanks for opening this issue :)

From what I can tell this was an issue with the Azure API's returning a different response only within the USA (which appears to have been rolled back). Whilst I'm glad to hear that it's resolved I'm going to ask Microsoft to take a look into what's happened here so we can determine how to avoid this in the future.

Thanks!

**Comment by CoRfr** [comment]
Hey,

I've been using azurerm all week without any problem, but within the past hour I've been getting this kind of errors:
```
* azurerm_managed_disk.nas_data: disk.DisksClient#CreateOrUpdate:
Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/<id>/providers/Microsoft.Compute/locations/westus/DiskOperations/<id>?api-version=2016-04-30-preview:
stream error: stream ID 121; HTTP_1_1_REQUIRED
```
This is occurring with westus, not sure about other locations.

Anyone else seeing this?

**Comment by berney** [comment]
I am seeing this in Australia East. I will see it with `terraform plan`, where there has been no changes so it should return `No changes. Infrastructure is up-to-date.`.

There's similar bugs opened #526 and #503

**Comment by berney** [comment]
B333z posted the work-around in this comment https://github.com/terraform-providers/terraform-provider-azurerm/issues/503#issuecomment-345919279 disable HTTP2.

**Comment by paamand** [comment]
Resetting the http.version solved it for me:
(https://github.com/git-lfs/git-lfs/issues/3875#issuecomment-572108173)

    git config --global --unset http.version HTTP/1.1
    git config --global --add http.version HTTP/1.1
