### ISSUE TITLE
New data source: azurerm_servicebus_namespace_authorization_rule

### ISSUE THREAD

**Issue by maximbaz** [terraform-providers/terraform-provider-azurerm#4282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please implement `data.azurerm_servicebus_namespace_authorization_rule` so that it's possible to query the value of authorization rules created via `resource.azurerm_servicebus_namespace_authorization_rule`.

### New or Affected Resource(s)

- `azurerm_servicebus_namespace_authorization_rule`

**Comment by r0bnet** [comment]
Hey @maximbaz 
what data do you need from the authorization rule?
Only these values:
`id`
`primary_key`
`primary_connection_string`
`secondary_key`
`secondary_connection_string`

Or any additional information?

**Comment by maximbaz** [comment]
Only these 🙂

**Comment by r0bnet** [comment]
It's possible to implement it but would it be a workaround for you to get those information via the azurerm_servicebus_namespace data source? This has the required properties you're looking for except the auth rule ID of course.

`default_primary_connection_string`
`default_secondary_connection_string`
`default_primary_key`
`default_secondary_key`

https://www.terraform.io/docs/providers/azurerm/d/servicebus_namespace.html#attributes-reference

**Comment by maximbaz** [comment]
That only works with `RootManageSharedAccessKey` which gives full access to a service bus, in my case I need to retrieve key or connection string of a different, much more limited policy (which might have been created using `resource.azurerm_servicebus_namespace_authorization_rule`)

**Comment by r0bnet** [comment]
You're right, it's the `RootManageSharedAccessKey`. I'll give it a try.

**Comment by r0bnet** [comment]
PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4294

**Comment by katbyte** [comment]
@maximbaz, this has been fixed by #4294 and released in 1.34! as such i am going to close this 🙂
