### ISSUE TITLE
Unable to associate azurerm_api_management_api to azurerm_api_management_api_version_set

### ISSUE THREAD

**Issue by spudoss** [terraform-providers/terraform-provider-azurerm#4297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There is no way (as far as I can tell) to specify which version set an api belongs to. I dug into the azurerm_api_management_api resource source code and saw read only `version` and `version_set_id` properties. I would expect these two properties to be writable to allow for the linkage of an api to a version set. 

### Terraform (and AzureRM Provider) Version
Terraform v0.12.6
azurerm v1.32.0

### Affected Resource(s)

* `azurerm_api_management_api`
* `azurerm_api_management_api_version_set`

**Comment by itsmaryann** [comment]
Also found this issue logged at: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3580
