### ISSUE TITLE
Error: Unsupported block type, in resource "azurerm_function_app" : app_settings {

### ISSUE THREAD

**Issue by svangeti** [terraform-providers/terraform-provider-azurerm#4312]
## Terraform (and AzureRM Provider) Version

Terraform v0.12.8
+ provider.azurerm v1.33.1

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```
resource "azurerm_function_app" "testDeployTF" {
  name                      = "testDeployTF"
  location                  = "${azurerm_resource_group.rg-testDeployTF.location}"
  resource_group_name       = "${azurerm_resource_group.rg-testDeployTF.name}"
  app_service_plan_id       = "${azurerm_app_service_plan.sp-testDeployTF.id}"
  storage_connection_string = "${azurerm_storage_account.sa-testDeployTF.primary_connection_string}"
  version                    = "~2"
app_settings {
 FUNCTION_WORKER_RUNTIME = "dotnet"
 FUNCTION_APP_EDIT_MODE = "readonly"
 https_only = true
    HASH            = "${base64sha256(file("./../functionapp.zip"))}"
    WEBSITE_USE_ZIP = "https://${azurerm_storage_account.sa-testDeployTF.name}.blob.core.windows.net/${azurerm_storage_container.sc-testDeployTF.name}/${azurerm_storage_blob.sb-testDeployTF.name}${data.azurerm_storage_account_sas.sas-testDeployTF.sas}"
  }
}
```

### Expected Behavior

azurerm_function_app resource should allow the app_settings block as per the documentation 

### Actual Behavior

Error: Unsupported block type

  on functionapp.tf line 71, in resource "azurerm_function_app" "testDeployTF":
  71: app_settings {

Blocks of type "app_settings" are not expected here. Did you mean to define
argument "app_settings"? If so, use the equals sign to assign it a value.

### Steps to Reproduce

1. `terraform apply`

### References

https://www.terraform.io/docs/providers/azurerm/r/function_app.html

**Comment by StefanSchoof** [comment]
And did you try to use a `=`?

```
app_settings = {
    "SOME_KEY" = "some-value"
  }
```

**Comment by svangeti** [comment]
gosh, how couldn't I think. That worked. Thanks so much @StefanSchoof
