### ISSUE TITLE
Unable to create $web azurerm_storage_container

### ISSUE THREAD

**Issue by bytemech** [terraform-providers/terraform-provider-azurerm#4329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
PS C:\> terraform -v
Terraform v0.12.8
+ provider.azurerm v1.31.0
```
### Affected Resource(s)
* azurerm_storage_container 

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "web" {
    name = "$$web"
    resource_group_name = "${var.rg_name}"
    storage_account_name = "${azurerm_storage_account.web.name}"
}
```
### Expected Behavior

Storage Container created with $web name 

### Actual Behavior

```

Error: only lowercase alphanumeric characters and hyphens allowed in "name": "$$web"

  on ..\Terraform_Modules\azure_static_site\resource.blob_container.tf line 1, in resource "azurerm_storage_container" "web":
   1: resource "azurerm_storage_container" "web" {

```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### References

Issue appears to be with function [validateArmStorageContainerName](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_storage_container.go#L306)

See https://www.terraform.io/docs/configuration-0-11/interpolation.html for where I got the escape char for $ from. 

May just be me using an incorrect escape char, as I've tested the regex and it's valid (matches on $web), so not quite sure what's going on here.

**Comment by tombuildsstuff** [comment]
hey @bytemech 

Thanks for opening this issue :)

Support for this was added in version 1.33.0 of the AzureRM Provider - would you mind upgrading and seeing if that works for you? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look.

Thanks!
