### ISSUE TITLE
azurerm_cognitive_account QnAMaker missing api-properties

### ISSUE THREAD

**Issue by brad-kwisp** [terraform-providers/terraform-provider-azurerm#4338]
When running a terraform apply to create a QnAMaker service. I receive the following error.

```
Error: Error creating Cognitive Services Account "qnamaker-stable" (Resource Group "qnamaker-stable"): cognitiveservices
.AccountsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returne
d an error. Status=400 Code="ApiPropertiesInvalid" Message="The given 'apiProperties' '{}' is invalid. Validation errors
: Required properties are missing from object: qnaRuntimeEndpoint. Path ''." 
```

When adding:
```
api-properties = {
    "qnaRuntimeEndpoint" = module.qnamaker.default_site_hostname
  }
```

I get the following:
```
Error: Unsupported argument

  on qnamaker.tf line 56, in module "qnamaker":
  56:   api-properties = {

An argument named "api-properties" is not expected here.
 ```

For reference creating via CLI looks like this:
```
az cognitiveservices account create -g devexp-qnamaker -n devexp-qnamaker-account --kind QnAMaker --sku S0 --location westus --api-properties qnaRuntimeEndpoint=https://devexp-qnamaker-webapp.azurewebsites.net
```

**Comment by r0bnet** [comment]
Hey @brad-kwisp,

had a look into this and we might not be able to do anything against it right now as the needed properties are not specified in the Azure SDK and specification.

I created an issue for the API specification and lets hope they will add it sooner or later:
https://github.com/Azure/azure-rest-api-specs/issues/7244

**Comment by RJPearson94** [comment]
Hi @r0bnet,

It appears the Azure SDK was enhanced to allow the QnA Runtime Endpoint to be supplied in V25, so this issue is now unblocked. 
I have opened a PR #5778 to add support for setting this within the azurerm_cognitive_account resource. Is it possible for you to take a look and provide any feedback?

**Comment by r0bnet** [comment]
Hey @RJPearson94,

for me that looks fine but unfortunately i'm not responsible for merge or something like that. I think that @tombuildsstuff or @katbyte can help here. :)

**Comment by RJPearson94** [comment]
Thanks @r0bnet.

@tombuildsstuff & @katbyte are you able to take a look at the PR? As it would be great if it could go out as part of the 2.0.0 release.
