### ISSUE TITLE
"terraform import azurerm_role_definition" pulls null values for scope

### ISSUE THREAD

**Issue by Grant-Rc** [terraform-providers/terraform-provider-azurerm#4351]
Hello team,

I had a Team member show me a better way to structure my Terraform and pushing state to S3 and getting it into a local gitlab etc.
In doing so I lost the state file for my Azure custom roles, he said I can use the import function to sort this out.

Now this is were my issue comes, the import works fine but when I run Terraform plan it says 
azurerm_role_definition.customrole must be replaced
 scope              = "/subscriptions/00000000-0000-0000-0000-000000000000" # forces replacement
looking at the state file the entries for scope are null 
            "scope": null

and as defined here https://www.terraform.io/docs/providers/azurerm/r/role_definition.html

scope - (Required) The scope at which the Role Definition applies too, such as /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333, /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup, or /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup/providers/Microsoft.Compute/virtualMachines/myVM. **Changing this forces a new resource to be created.**

So its changing from "null" to a value and as such forcing a the role to be replaced. This would be fine but you cant delete the role because it is in use across multiple subscriptions.

workaround was to manual edit the state file to add the scope but that not ideal.

anyone come across this? googling i dont find direct link to this issue.

**Comment by tombuildsstuff** [comment]
Fixed via #7424
