### ISSUE TITLE
Unable to use azurerm_app_service_certificate with key_vault_secret_id if key vault is in a different subscription

### ISSUE THREAD

**Issue by MarkDordoy** [terraform-providers/terraform-provider-azurerm#4358]
Hello

im using terraform v0.12.6 and azurerm 1.34.0

When i use the `azurerm_app_service_certificate` resource with the key_vault_secret_id im getting back the error `Unable to determine the Resource ID for the Key Vault at URL <mykeyvaulturl>"

This is currently what i have:

```hcl
resource "azurerm_app_service_certificate" "mycert" {
  name                = "mycert"
  resource_group_name = data.azurerm_resource_group.resource_group.name
  location            = data.azurerm_resource_group.resource_group.location
  key_vault_secret_id = "https://mysecretkeyvaultname.vault.azure.net/certificates/mycert/766c23ae979c4b0fad603937af2511a5"
}
```

What i've used for the key_vault_secret_id is the certificate Identifier, what should i be using? 

Many thanks in advance. Once i understand i'll do a PR to the documentation to add clarity.

**Comment by MarkDordoy** [comment]
I should also add the resource group in my example above specified by `data.azurerm_resource_group.resource_group.name` is in a different subscription to where the key vault that has the certificate.

**Comment by joakimhellum-in** [comment]
Sorry about that. Here is complete example with comments:
```hcl
data "azurerm_client_config" "example" {}

# Get the Object ID for the "Microsoft Azure App Service" service principal, 
# since it need to be granted access to read secrets and certificates.
data "azuread_service_principal" "example" {
  display_name = "Microsoft Azure App Service"
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_key_vault" "example" {
  name                = "example-key-valt"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.example.tenant_id
  sku_name            = "standard"

  # Grant "Microsoft Azure App Service" service principal access
  # to get certificates and secrets.
  access_policy {
    tenant_id               = data.azurerm_client_config.example.tenant_id
    object_id               = data.azuread_service_principal.example.object_id
    secret_permissions      = ["get"]
    certificate_permissions = ["get"]
  }
}

resource "azurerm_key_vault_certificate" "example" {
  name         = "example-certificate"
  key_vault_id = azurerm_key_vault.example.id

  certificate {
    # Add example certificate 
    contents = filebase64("example-certificate.pfx")
    password = "terraform"
  }

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
}

# Use Key Vault secret reference since using Key Vault certificate reference 
# probably only provides public portion of a Key Vault certificate.
data "azurerm_key_vault_secret" "example" {
  name         = azurerm_key_vault_certificate.example.name
  key_vault_id = azurerm_key_vault.example.id
}

resource "azurerm_app_service_certificate" "example" {
  name                = "example-certificate"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  # Use Key Vault secret reference (see comment above).
  key_vault_secret_id = data.azurerm_key_vault_secret.example.id
}
```

Here is another example that doesn't require you to grat "Microsoft Azure App Service" service principal access to read certificates and secrets:

```hcl
resource "azurerm_app_service_certificate" "example" {
  name                = "example-certificate"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  pfx_blob            = data.azurerm_key_vault_secret.test.value
}
```

Sorry I didn't actually test the configurations, but most of it should be correct.

**Comment by MarkDordoy** [comment]
Thanks @joakimhellum-in 

I just used your data examples to get the secretId i need in isolation to my actually setup (as resources are in different subscriptions). Turns out i had the correct id.  

This suggests to me that the key_vault_secret_id (key vault) needs to be in the same subscription as where im using  `azurerm_app_service_certificate`. Would you agree? 

Its a shame as i have the key vault with the secret and the resources im creating in different subscriptions. Do you think this could be solved if we was to extend and provider the key vault resource ID?

**Comment by joakimhellum-in** [comment]
@MarkDordoy Good question, didn't think about that. Will make attempt to implement your suggested fix during coming weekend, unless you or anyone else is already working on it :)

**Comment by MarkDordoy** [comment]
I will take a look and see if i can work it out. Im still quite new to golang so you might be quicker. Will update this ticket if i manage it :-)

**Comment by dlm69** [comment]
Does anyone have an answer on this?

I too have this problem. I can create and "get" data when i keep everything contained to one subscription. When i try using provider alias to connect to a different subscription for data sources I get the same error as above. I am using the alias'd provider for loganalytics workspace id in another part of my TF script so it definately works so I can only assume its a Terraform error.

```
data "azurerm_key_vault" "default" {
  name                = "xxxxxxxCerts"
  resource_group_name = "KeyVault"
  provider            = azurerm.Primary
}

data "azurerm_key_vault_secret" "default" {
  name         = var.certificate
  key_vault_id = "${data.azurerm_key_vault.default.id}"
  provider     = azurerm.Primary
}

## Adds certificate to App Service 
resource "azurerm_app_service_certificate" "default" {
  name                = var.certificate
  resource_group_name = "${azurerm_resource_group.default.name}"
  location            = "${azurerm_resource_group.default.location}"
  key_vault_secret_id = "${data.azurerm_key_vault_secret.default.id}"
}

```
Error
> azurerm_app_service_certificate.default: Creating...
> 
> Error: Unable to determine the Resource ID for the Key Vault at URL "https://xxxxxxxcerts.vault.azure.net/"
> 
>   on default-backend.tf line 329, in resource "azurerm_app_service_certificate" "default":
>  329: resource "azurerm_app_service_certificate" "default" {


Does anyone have any ideas?

**Comment by katbyte** [comment]
Hi @MarkDordoy, @dlm69 

due to the way the API & resources work we currently don't supporent the keyvault being in a separate subscription as when we list key vaults to find the vault ID the client call is unaware of anything in another subscription.

Adding an optional `key_vault_id` is the best way to solve this i think.

**Comment by dlm69** [comment]
Hi @MarkDordoy  

_Adding an optional key_vault_id is the best way to solve this i think._


What do you mean by this? As you can see from my Terraform script I am already using the key_vault_id to get the secret. Can you expand on what you mean? Or better yet. Give an example?

Thanks

**Comment by MarkDordoy** [comment]
@dlm69 the current setup of the resource will not work if the key vault is in a different azure subscription. What i purposed was by updating the provider to have an additional attribute named key_vault_id which should then allow the provider to find the key vault. However this is yet to be implemented

**Comment by ignatz42** [comment]
Currently, the easy way to make this association across subscriptions is by passing the certificate thumbprint.  See https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest for an example.  Please consider adding support for the certificate thumbprint also.

**Comment by RavulaChetan** [comment]
Hi
I am trying to implement azurerm_app_service_custom_hostname_binding with SSL
data "azurerm_key_vault_secret" "secret" {
  name                = "secrets"
  #vault_uri           = "${name}"
  key_vault_id        = "${data.azurerm_key_vault.kv.id}"
}

my SP running the code and the KeyVault are in same subscription but i am getting that the KeyVault URI does not exist.

Error: KeyVault Secret "secrets" (KeyVault URI "https://####.vault.azure.net/") does not exist.

I am using azurerm provider version 1.40.

**Comment by AnunnakiSelva** [comment]
@MarkDordoy  @katbyte @dlm69  

   Hi am also exactly trying the same .  On creating a web app trying to refer key fault from other subscrption and i get "**Unable to determine the Resource ID for the Key Vault at URL "https://xxxxxxxxx.vault.azure.net/"**" on module **resource "azurerm_app_service_certificate" "certificate"**./
Any idea to support it anytime soon ? or Its already fixed ?

**Comment by mcollis2** [comment]
It looks like the ARM API uses keyvaultID and secret name to create this resource.  Also through portal, you select the subscription, keyvault, then secret name.  So this should behave similarly in terraform I would think.  Any update on adding keyvault_id as a property?  Thanks

**Comment by sebastianhutter** [comment]
I stumbled over the same problem. We store our certificates in a keyvault in a different subscription then our app services.

As a workaround I created a small powershell script which uses the API directly to register the certificate.
It is not very nice as it executed everytime but better that then no certs ;-)

Do we have an ETA for a fix in the provider itself?

Here the powershell script and how I am using it at the moment if anyone else has trouble using certificates in app services:


```bash
# use powershell new-azresource to register web app certificate
resource "null_resource" "certificate" {
  provisioner "local-exec" {
    command     = <<EOT
      ${path.module}/files/ImportWebappCertificate.ps1 `
        -subscriptionId ${data.azurerm_client_config.current.subscription_id} `
        -tenantId ${data.azurerm_client_config.current.tenant_id} `
        -clientId ${data.azurerm_client_config.current.client_id} `
        -clientSecret ${var.service_principal_secret} `
        -resourceGroupName ${var.app_service_resource_group_name} `
        -resourceGroupLocation ${var.app_service_location} `
        -webAppName ${var.app_service_name} `
        -keyvaultId ${data.azurerm_key_vault.acmebot.id} `
        -certificateName ${var.certificate_name}
EOT
    interpreter = ["sudo", "pwsh", "-Command"]
  }

  triggers = {
    force_trigger = timestamp()
  }
}

# retrieve data from the freshly registered cert
data "azurerm_app_service_certificate" "certificate" {
  name                = var.app_service_name
  resource_group_name = var.app_service_resource_group_name

  depends_on = [
    null_resource.certificate
  ]
}

# create custom hostname binding
resource "azurerm_app_service_custom_hostname_binding" "hostname" {
  hostname            = local.app_service_hostname
  app_service_name    = var.app_service_name
  resource_group_name = var.app_service_resource_group_name
  ssl_state           = "SniEnabled"
  thumbprint          = data.azurerm_app_service_certificate.certificate.thumbprint

  depends_on = [
    azurerm_dns_cname_record.record
  ]
}

```ps1
#--------------------------------------------------------------
# Script to import ssl certificate from keyvault into app services
#--------------------------------------------------------------
# https://briandunnington.github.io/webapp_certificate_from_keyvault
# https://github.com/terraform-providers/terraform-provider-azurerm/issues/4358

param
(
    [string] $resourceGroupName,
    [string] $resourceGroupLocation,
    [string] $webAppName,
    [string] $keyvaultId,
    [string] $certificateName,
    [string] $subscriptionId,
    [string] $tenantId,
    [string] $clientId,
    [string] $clientSecret
)

# disable any warning messages
$WarningPreference = 'SilentlyContinue'

try { 
    $securesecret = ConvertTo-SecureString -String $clientSecret -AsPlainText -Force
    $Credential = New-Object pscredential($clientId,$securesecret)
    Connect-AzAccount -Credential $Credential -Tenant $tenantId -ServicePrincipal
    Select-AzSubscription $subscriptionId

    # setup json object from which to create the arm resource
    $PropertiesObject = @{
        keyVaultId = $keyvaultId;
        keyVaultSecretName = $certificateName;
    }
    # register certificate with app service
    New-AzResource `
        -ResourceName $webAppName `
        -Location $resourceGroupLocation `
        -PropertyObject $PropertiesObject `
        -ResourceGroupName $resourceGroupName `
        -ResourceType Microsoft.Web/certificates `
        -ApiVersion 2019-08-01 `
        -Force

} catch {
  Write-Error "An error occurred:"
  Write-Error $_.Exception.Message
  Write-Error $_.ScriptStackTrace

  exit 1
}
```

**Comment by cpdohert** [comment]
I've tried a couple of workarounds for this and nothing is working.

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.32.0
```

## Workaround 1: Aliased provider for azurerm_key_vault_secret (NOT WORKING)
I thought perhaps the problem was terraform being unable to obtain the attributes of the secret.

This allows terraform to read the attributes of the key vault secret from another subscription.
```terraform
provider "azurerm" {
  features {}
}

provider "azurerm" {
  features {}
  alias           = "security"
  subscription_id = "000000000-0000-0000-0000-000000000"
}

data "azurerm_key_vault" "example" {
  provider            = azurerm.production
  name                = "example"
  resource_group_name = "example"
}

data "azurerm_key_vault_secret" "example" {
  provider     = azurerm.production
  name         = "example"
  key_vault_id = data.azurerm_key_vault.example.id
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_app_service_certificate" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  key_vault_secret_id = data.azurerm_key_vault_secret.example.id
}
```

Fails:
```
Error: Unable to determine the Resource ID for the Key Vault at URL "https://example.vault.azure.net/"
```

## Workaround 2: use a pfx blob reference instead of the secret (NOT WORKING)
This _should_ work, as using the pfx blob means no dependency on the key vault once I've read the
key_vault_secret from the other subscription.  I've checked the state and the `value` attribute is in there and is a b64 encoded string.

```terraform
resource "azurerm_app_service_certificate" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  pfx_blob            = data.azurerm_key_vault_secret.example.value
}
```

And yet no joy.
```
azurerm_app_service_certificate.example: Creating...
azurerm_app_service_certificate.example: Still creating... [10s elapsed]
azurerm_app_service_certificate.example: Still creating... [20s elapsed]

Error: Error creating/updating App Service Certificate "example" (Resource Group "example"): web.CertificatesClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

  on main.tf line 85, in resource "azurerm_app_service_certificate" "example":
  85: resource "azurerm_app_service_certificate" "example" {
```

According to Microsoft, imported PFX certificates must have a password: https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate#private-certificate-requirements
This certificate does not have a password and terraform will not allow a blank password:

```terraform
resource "azurerm_app_service_certificate" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  pfx_blob            = data.azurerm_key_vault_secret.example.value
  password            = ""
}
```
```
Error: password must not be empty, got 
```

But this certificate was generated via Microsoft's new (in preview) Azure App Certificate resource, it does not have a password, and I can import it into an App Service through the portal via **Private Key Certificates (*.pfx) > + Import Key Vault Certificate** just fine, so the back end APIs either do not /require/ a password, or will accept an empty string.

**Comment by RavulaChetan** [comment]
Thanks @cpdohert 
**Workaround2** worked for me.

**Comment by SamWhitby** [comment]
Thanks @cpdohert, workaround 2 does the job for now. Unfortunately you do loose the ability for the app services to sync certificate changes made in key vault doing it that way.
It would be great if someone could get this working.

**Comment by cpdohert** [comment]
@SamWhitby  Note that as long as you run your terraform declarations frequently you'll be all right.  The certificate tries to renew well before the expiry date (assuming you configured your App Service Certificate for Auto-Renew); when it does, the next terraform run will pick up the new pfx blob and import it into the app service.  It's a hack, but it'll keep your certs from spontaneously expiring on you.

**Comment by mtirionMSFT** [comment]
Could this issue be related to this article: https://azure.github.io/AppService/2016/05/24/Deploying-Azure-Web-App-Certificate-through-Key-Vault.html?
The Web App Resource Provider (RP) requires read access to keyvault. abfa0a7c-a6b6-4736-8310-5855508787cd is the RP service principal name and it remains same for all Azure subscriptions. Note for Azure Gov cloud environment you will need to use 6a02c803-dafd-4136-b4c3-5a6f318b4714 as the RP service principal name in the above command instead of ‘abfa0a7c-a6b6-4736-8310-5855508787cd’.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here there appear to be a couple of questions/issues being discussed. With regard to the original issue, you'll need to use an aliased Provider, [as described in the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_certificate) to access a Key Vault in another subscription:

> NOTE: The vault must be in the same subscription as the provider. If the vault is in another subscription, you must create an aliased provider for that subscription.

Bear in mind that the Service Principal/User being used in said aliased provider must have permissions to the Key Vault, that is an Access Policy configured against the Key Vault for that Service Principal/User.

For the second issue, regarding referencing this in an App Service Certificate - to support automatic key rotation you should be able to specify the "versionless" URI for the Key Vault Certificate (that is, without the last `version` segment) - which means that Key Vault will automatically detect there's a new version available and cycle this in.

Since this should be fixed by updating the Terraform Configuration - I'm going to close this issue for the moment - but should you have further usage questions [you should be able to discuss this further on the Community Forums](https://discuss.hashicorp.com).

Thanks!
