### ISSUE TITLE
azurerm provider 1.34 failds to deploy vm with image copy from blob

### ISSUE THREAD

**Issue by bottkars** [terraform-providers/terraform-provider-azurerm#4361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

 error occurred:
        * module.ops_manager.azurerm_image.ops_manager_image: 1 error occurred:
        * azurerm_image.ops_manager_image: compute.ImagesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Required parameter 'hyperVGeneration' is missing (null)." Target="hyperVGeneration"

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1.  Create a vm using managed disk using image copy from blob

https://github.com/pivotal-cf/terraforming-azure/blob/master/modules/ops_manager/ops_manager.tf
`terraform apply`

### References

* #0000

**Comment by voor** [comment]
Does anyone know of a temporary workaround for this issue?

**Comment by bottkars** [comment]
sure , put lines like 
https://github.com/bottkars/pcf-jump-azure/blob/4dcf47dc595518b589d6bf82d9f4d4ccc55fd1be/patches/main.tf#L11-L13
in your main.tf to pin you provider to a lower version

**Comment by voor** [comment]
Actually, I believe it's this line that'll fix it:
```
provider "azurerm" {
  version = "= 1.32"
}
```
At least that's what fixed it for me.

**Comment by bottkars** [comment]
if you use version = "< 1.34.0" or  version = "= 1.32", should both work ( i belivee you use terraforming azure )
, but L8 is the one you might look for
