### ISSUE TITLE
Windows Azure Guest Agent isn't Installed when provision_vm_agent is Enabled

### ISSUE THREAD

**Issue by raygervais** [terraform-providers/terraform-provider-azurerm#4363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As per the documentation linked below, when `provision_vm_agent` is set to `true` in the `os_profile_windows_config` block, it should install the Windows Azure Guest Agent. This is not the behavior that has been observed with the configuration below -despite the terraform output confirming the configuration settings as expected. Appreciate the help with this, since it's blocking an important use-case for us.

Thanks 👍  💻  🍻 !

### Terraform (and AzureRM Provider) Version

`Terraform Version: 0.11.14`
`AzureRM Provider Version: 1.24.0`

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "base_vm" {
  name                         = "${var.vm_name == "" ? "VM-${random_string.suffix.result}" : var.vm_name}"
  location                     = "${local.resource_group_location}"
  resource_group_name          = "${local.resource_group_name}"
  primary_network_interface_id = "${azurerm_network_interface.base_lb.0.id}"
  network_interface_ids        = ["${azurerm_network_interface.base_lb.*.id}"]
  vm_size                      = "${var.vm_sku}"
  license_type                 = "Windows_Server"

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  delete_os_disk_on_termination = "${var.delete_os_disk_on_termination}"

  # Uncomment this line to delete the data disks automatically when deleting the VM
  delete_data_disks_on_termination = "${var.delete_data_disks_on_termination}"

  storage_os_disk {
    name = "OS-Disk-${var.vm_name == "" ? "VM-${random_string.suffix.result}" : var.vm_name}"

    os_type         = "Windows"
    managed_disk_id = "${azurerm_managed_disk.copy.id}"
    create_option   = "Attach"
  }

  os_profile_windows_config = {
    provision_vm_agent = true
  }

  tags = "${var.tags}"

  availability_set_id = "${local.availability_set_id}"

  boot_diagnostics {
    enabled     = "true"
    storage_uri = "${azurerm_storage_account.base.primary_blob_endpoint}"
  }
```

### Debug Output
```
id:                                                                 <computed>
availability_set_id:                                                "/subscriptions/<super_secret_subscription>/resourcegroups/<super_secret_resource_group>/providers/microsoft.compute/availabilitysets/ls-scaffolding-labtest"
boot_diagnostics.#:                                                 "1"
boot_diagnostics.0.enabled:                                         "true"
boot_diagnostics.0.storage_uri:                                     "${azurerm_storage_account.base.primary_blob_endpoint}"
delete_data_disks_on_termination:                                   "true"
delete_os_disk_on_termination:                                      "true"
identity.#:                                                         <computed>
license_type:                                                       "Windows_Server"
location:                                                           "canadacentral"
name:                                                               "${var.vm_name == \"\" ? \"VM-${random_string.suffix.result}\" : var.vm_name}"
network_interface_ids.#:                                            <computed>
os_profile_windows_config.#:                                        "1"
os_profile_windows_config.3143587113.additional_unattend_config.#:  "0"
os_profile_windows_config.3143587113.enable_automatic_upgrades:     "false"
os_profile_windows_config.3143587113.provision_vm_agent:            "true"
os_profile_windows_config.3143587113.winrm.#:                       "0"
primary_network_interface_id:                                       "${azurerm_network_interface.base_vm.0.id}"
resource_group_name:                                                "<super_secret_resource_group>"
storage_data_disk.#:                                                <computed>
storage_image_reference.#:                                          <computed>
storage_os_disk.#:                                                  "1"
storage_os_disk.0.caching:                                          <computed>
storage_os_disk.0.create_option:                                    "Attach"
storage_os_disk.0.disk_size_gb:                                     <computed>
storage_os_disk.0.managed_disk_id:                                  "${azurerm_managed_disk.copy.id}"
storage_os_disk.0.managed_disk_type:                                <computed>
storage_os_disk.0.name:                                             "OS-Disk-${var.vm_name == \"\" ? \"VM-${random_string.suffix.result}\" : var.vm_name}"
storage_os_disk.0.os_type:                                          "Windows"
storage_os_disk.0.write_accelerator_enabled:                        "false"
tags.%:                                                             "3"
vm_size:                                                            "Standard_D2s_v3"
```

### Expected Behavior

Windows Guest Agent is installed on new Compute instance.

### Actual Behavior

Windows Guest Agent is not installed on new Compute instance.

### References

* https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#provision_vm_agent

**Comment by tombuildsstuff** [comment]
hey @raygervais 

Thanks for opening this issue :)

Taking a look into this it appears that Terraform's building up the object correctly to send to the Azure API - as such I believe this is a configuration issue.

When creating a Windows Virtual Machine (or VM Scale Set) Azure requires [that `sysprep` is run on the machine prior to the image being captured/the OS Disk being reused](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource#generalize-the-windows-vm-using-sysprep) which (amongst other things) resets machine specific identifiers. From memory the Azure API's behave differently when an image without sysprep is used - so would you be able to confirm if sysprep's been run on this source managed disk?

Thanks!

**Comment by raygervais** [comment]
Hey @tombuildstuff

Thanks for looking into this, I've added some context below which may help describe our situation.


```
Goal is to install the Windows extension through Terraform.
Our use-case doesn't work with a new image, but instead a pre-existing image which was created outside of Terraform and is considered legacy/dated.
```

Because of this, sysprep is not being utilized nor can it integrated into the workflow that I'm aware of at this time. Thoughts?

**Comment by tombuildsstuff** [comment]
@raygervais unfortunately you'll need to run sysprep on that image to be able to use it that way AFAIK. Whilst the image itself may have been taken a while back, you should be able to capture a new version by provisioning that image to a Virtual Machine, running SysPrep and then capturing an image from that Virtual Machine

Whilst it may be possible to install the Azure Virtual Machine Agent from an MSI/source using [a remote-exec provisioner](https://www.terraform.io/docs/provisioners/remote-exec.html) (a VM Extension wouldn't work since the VM Agent wouldn't be installed) - unfortunately the Azure Provider only natively supports doing this using the API and is something we'd be unable to assist further with here.

It's worth noting if you're using some of the built-in Windows Services (e.g. Messaging/MSMQ, AD or anything cluster related) - this uses the UUID of the machine; in previous roles I've seen machines duplicated from an image where sysprep hasn't been run, which ended up causing data loss (because two machines shared the same identifier when sending messages to one another, and so messages were lost rather than sent to other machines) - as such I would **strongly recommend** running `sysprep` on the existing image and capturing a new one; rather than trying to install the VM Agent through Terraform.

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - if you're still having issues you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!

**Comment by raygervais** [comment]
Thanks @tombuildsstuff for the feedback!

Just want to provide further context, in the case it changes the expectation of what should be occurring in the API and implementation.

The non-unique UUID is not an issue here. All the machines in our workflow have unique IDs. Likewise we are not making copies of the same machine in this case.

Appreciate the guidance you've provided so far, and sharing your previous experiences.

**Comment by tombuildsstuff** [comment]
@raygervais 

> Just want to provide further context, in the case it changes the expectation of what should be occurring in the API and implementation.

Unfortunately this is a limitation of the Azure API - as such this isn't something we're able to work around.

> Likewise we are not making copies of the same machine in this case

If you're provisioning the machines from the same image then the same UUID will be reused - which presumably is reused by the VM Agent on the Guest OS to communicate with the Hypervisor (there's a binary protocol which the Azure VM Agent uses to communicate with the Hypervisor, which I have a feeling uses this UUID in some form, which could be the underlying source of this issue - but I could be wrong).

As such to be able to successfully provision the VM Agent on these nodes the source image itself will need to be sysprep'd and re-captured - which (as mentioned above) should be just deploying this image to a Virtual Machine, running `sysprep` and capturing an updated image from that sysprep'd Virtual Machine.
