### ISSUE TITLE
azurerm 1.34.0 breaks: AuthorizationFailed on random providers

### ISSUE THREAD

**Issue by alexhudson** [terraform-providers/terraform-provider-azurerm#4365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.8
+ provider.azurerm v1.34.0

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.33"
  use_msi = true
}
```

### Expected Behavior

The terraform deployment should have worked as usual: I literally had it working yesterday, and then today it broke in CI/CD with no configuration changes (so the expectation was an empty plan file).

### Actual Behavior

Received this error:

`
Error: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.BotService with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.BotService/register/action' over scope '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' or the scope is invalid. If access was recently granted, please refresh your credentials.".

  on main.tf line 12, in provider "azurerm":
  12: provider "azurerm" {
`

I've also had errors for other providers. 

### Steps to Reproduce

1. `terraform plan`

### Workarounds

Setting the version pin to "= 1.33.1" makes the problem go away.

Keeping the pin the same and setting skip_provider_registration = true also avoids the issue. However, I didn't have that enabled previously, and the bug below indicates it shouldn't be necessary..

### References

* #3358

**Comment by tombuildsstuff** [comment]
hi @alexhudson 

Thanks for opening this issue :)

As mentioned in #3358 the Azure Provider attempts to automatically register any Resource Providers which it supports to provide a better user experience (since the error messages returned from Azure when a Resource Provider are unhelpful). Since there's no way for us to know within the Azure Provider which Resource Providers are needed (since this information isn't exposed in Terraform Core) we maintain [a list of all supported Resource Providers which we have Terraform Resources for](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/required_resource_providers.go#L16) and attempt to register them on launch, meaning that as version 1.34 of the Azure Provider now supports the Bot resources we now attempt to register `Microsoft.BotService`.

If you're running in a restricted environment you can configure Terraform to skip registering the Required Resource Providers using the `skip_provider_registration` setting (as you've seen) - albeit the error messages returned from Azure may be more unhelpful should you encounter a Resource Provider which is unregistered - but since this is an intentional behaviour I'm going to close this issue for the moment.

Thanks!

**Comment by alexhudson** [comment]
Hey @tombuildsstuff 

I'm not sure I would categorise the environment as "restricted" - the terraform is running with an Azure DevOps service connection into AzureRM. None of the permissions per-service provider were (knowingly) set during that process, and the pipeline was working fine with 1.33.1. When 1.34 rolled around with new service providers obviously it started failing, but it's not clear to me why 1.33.1 necessarily worked - the service connection was not "locked down" in any way to the providers I was using.

Is it the case that Azure subscriptions are more likely to be set up with the smaller list of providers available in 1.33 than 1.34? I haven't gone to enable "Azure.DataBricks" myself, for sure - but it's there enabled. BotService isn't. I haven't made that choice myself. 

It seems to me that as terraform-provider-azurerm continues to enable more resource providers, people are going to bump into this issue more and more frequently, and the output is only marginally more helpful than in the "skip registration" case.

**Comment by tombuildsstuff** [comment]
@alexhudson if a User/Service Principal with (for example) Owner/Contributor rights has run Terraform in that subscription, or provisioned those resources in the Azure Portal it's possible that those got registered via that; or that this is enabled by default (however even if it's enabled by default Terraform still needs to check the status and potentially attempt to register the Resource Provider in the case where it's been unregistered).

In your case if you're using a Service Principal/User which doesn't have permission to register the Resource Providers (which is what I meant by a restricted environment above) then it's possible to opt out of auto-registration via the `skip_provider_registration` flag - but the list of Resource Providers that Terraform supports is additive over time as Terraform supports new resources to provide a better user experience (as the Azure's API responses are unhelpful when calling API methods on a Resource Provider which is unregistered).

**Comment by alexhudson** [comment]
Ah, right, I see what you mean - thank you, I actually had read "registration" as being an internal housekeeping thing, it didn't click for me that it meant enabling the actual resource provider.

This all makes sense now, but it still feels like anyone running this in CI/CD is going to bump into this problem once they set their pipeline up - I would rarely run terraform as a regular user. I suppose the process could be "pin to exact version, and run plan before upgrading as an owner/contributor before releasing into CI/CD". I'm sure you've thought of this, but is there any more helpful message that could be output when receiving the 403 on provider registration?
