### ISSUE TITLE
New Data Source: azurerm_shared_image_versions

### ISSUE THREAD

**Issue by nicethomaslearngit** [terraform-providers/terraform-provider-azurerm#4369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi Team,

  I was trying to use filtering based on tags with the data source azurerm_shared_image_version, but  got to know from #4362 this is supported in azurerm_shared_image_version"s".

Could you kindly help me with a guide how to use this data source.

I am using the version 1.34.0

### New or Affected Resource(s)

* azurerm_1.34.0

### References

* #4362

**Comment by holtwilkins** [comment]
And also the ability to find the `latest`, not sure if that counts as a tag or not. Right now I'm using an external data source with a shell script.
