### ISSUE TITLE
release 0.3.0 brings in breaking changes, while the recommended way to prevent breaking changes was to use the following version string `~> 0.1`

### ISSUE THREAD

**Issue by djsly** [terraform-providers/terraform-provider-azurerm#437]
### Terraform Configuration Files
```hcl
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
  environment     = "${var.azure_environment}"
  version         = "~> 0.1"
}

provider "template" {
  version = "~> 0.1"
}

provider "terraform" {
  version = "~> 1.0"
}
```

### Debug Output
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "terraform" (1.0.0)...
- Downloading plugin for provider "azurerm" (0.3.0)...
- Downloading plugin for provider "template" (0.1.1)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraforming (force-destroy) on azure for product k8s with prefix: master
There are warnings related to your configuration. If no errors occurred,
Terraform will continue despite these warnings. It is a good idea to resolve
these warnings in the near future.

Warnings:

  * azurerm_storage_account.diagnostics_sa: "account_type": [DEPRECATED] This field has been split into `account_tier` and `account_replication_type`
  * azurerm_storage_account.etcd_backup_sa: "account_type": [DEPRECATED] This field has been split into `account_tier` and `account_replication_type`

4 error(s) occurred:

* azurerm_storage_account.diagnostics_sa: "account_replication_type": required field is not set
* azurerm_storage_account.diagnostics_sa: "account_tier": required field is not set
* azurerm_storage_account.etcd_backup_sa: "account_replication_type": required field is not set
* azurerm_storage_account.etcd_backup_sa: "account_tier": required field is not set

### Expected Behavior
terraform provider plugins should now bring breaking changes when using the permissive versionning filter.
```
~>: pessimistic constraint operator. Example: for ~> 0.9, this means >= 0.9, < 1.0. Example: for ~> 0.8.4, this means >= 0.8.4, < 0.9
```

### Actual Behavior
- Downloading plugin for provider "azurerm" (0.3.0)...

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I guess the main issue was with the output message from Terraform telling us that we should use 

```
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.0"
```

they should either put the full version number `~> 1.0.0` or the provider should follow a contract that breaking hcanges are only allowed in Major Releases (X.0.0)

**Comment by tombuildsstuff** [comment]
hey @djsly 

Thanks for opening this issue - apologies for the delayed response here!

We've had this issue across a number of providers, where they were initially released as `0.0.1` - since then most providers have now been bumped to at least `1.0.0` (where SemVer is followed by Terraform Core). The Azure Provider hit this milestone in December - which means that this issue should be resolved, as such I'm going to close this issue for the moment.

Thanks!
