### ISSUE TITLE
Documentation for azurerm_app_service Data Source is missing default_site_hostname

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#4373]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `data.azurerm_app_service`

### Actual Behavior

default_site_hostname is exported but is absent from the [doc page](https://www.terraform.io/docs/providers/azurerm/d/app_service.html)

**Comment by jrauschenbusch** [comment]
There are further missing documentation entrypoints in `website/azurerm.erb` in the last 1.34 release:

- azurerm_proximity_placement_group
- azurerm_storage_account_blob_container_sas
- azurerm_frontdoor
- azurerm_frontdoor_firewall_policy
- azurerm_kusto_database
- azurerm_proximity_placement_group
- azurerm_stream_analytics_output_servicebus_topic

Maybe there are more missing links from previous releases?
