### ISSUE TITLE
azurerm_virtual_machine_scale_set.extension.settings unable to set to local variable

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#4379]
### Terraform (and AzureRM Provider) Version

Terraform v0.12.7
provider.azurerm v1.28.0

### Affected Resource(s)

azurerm_virtual_machine_scale_set

### Terraform Configuration Files

Defining the VM Extension template to use as a local variable. There is another problem in that I can't nest resource / variable references inside this (keep getting an error about a '$' being an invalid character inside the local 'sf_settings_template'). My plan to solve this issue is to use the Terraform [replace](https://www.terraform.io/docs/configuration/functions/replace.html) function. But it's much easier to work with a string once I have it as a local variable!

```hcl
locals {
    
    sf_settings_template = <<JSON

{
    "clusterEndpoint": "https://CLUSTER_NAME.eastus.cloudapp.azure.com:19000",
    "nodeTypeRef": "clustervm",
    "dataPath": "D:\\SvcFab",
    "durabilityLevel": "Bronze",
    "enableParallelJobs": true,
    "nicPrefixOverride": "INSERT_SUBNET_RANGE_HERE",
    "certificate": {
        "thumbprint": "INSERT_THUMBPRINT_HERE",
        "x509StoreName": "My"
    }
}

JSON

}
```

Referencing the local template inside a azurerm_virtual_machine_scale_set
```hcl
    extension {
        name                        = "ServiceFabricNodeVmExt"
        publisher                   = "Microsoft.Azure.ServiceFabric"
        type                        = "ServiceFabricNode"
        type_handler_version        = "1.0"
        auto_upgrade_minor_version  = true

        settings = "$(local.sf_settings_template)"
        
    }
```

### Panic Output

> Error: "extension.0.settings" contains an invalid JSON: invalid character '$' looking for beginning of value

 > on cluster-compute.tf line 25, in resource "azurerm_virtual_machine_scale_set" "cluster-scaleset":
  25: resource "azurerm_virtual_machine_scale_set" "cluster-scaleset" {

I'm taking this error to mean it doesn't like the $ inside the setter of the 'settings' property of the extension. seen here:

`settings = "$(local.sf_settings_template)"`

### Expected Behavior

My local variable with a valid JSON string should be set to the settings property of the extension on the VM scaleset.

### Actual Behavior

Terraform throws an error saying there is an invalid character '$' when setting the 'settings' property.

### Steps to Reproduce

1. add a VM scaleset with an extension that uses a local to set its settings
2. terraform apply

### References

I am trying to get a service fabric cluster actually working. Never seen a real working sample from Microsoft. SAD.

https://github.com/markti/terraform-servicefabric-cluster

**Comment by katbyte** [comment]
Hi @markti,

It looks like you have the syntax there wrong. To use a local in .11 you must use `${}` instead of `$()`:
```
        settings = "${local.sf_settings_template}"
```
and in .12 you can drop the escape sequence all togeather
```
        settings = "local.sf_settings_template"
```

Could you give that a try? thanks

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment - however please let us know if the solution proposed by @katbyte doesn't work for you and we'll take another look.

Thanks!
