### ISSUE TITLE
azurerm_api_app - added in 1.35.0?

### ISSUE THREAD

**Issue by aberva** [terraform-providers/terraform-provider-azurerm#4382]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---
I take advantage of this topic :
https://github.com/terraform-providers/terraform-provider-azurerm/pull/4306#issuecomment-530945347

Do you think this resource "azurerp_api_app" will be supported with 1.35.0 ?

**Comment by tombuildsstuff** [comment]
hi @aberva 

Thanks for opening this issue.

Support for API Apps isn't available natively in Terraform yet but is being tracked in #443 - if you're interested in API Apps being natively supported in Terraform please subscribe/👍 #443 where updates will be posted when available :)

Thanks!
