### ISSUE TITLE
Azure Web App Bot

### ISSUE THREAD

**Issue by PathTech** [terraform-providers/terraform-provider-azurerm#4384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Upon the release of v1.34.0 of the Azure provider bot support was added. Upon closer inspection it seems that it only supports connections to existing bots and not the creation of a new WebApp Bot.

### New or Affected Resource(s)

* azurerm_bot_webapp

### Potential Terraform Configuration

```hcl
"azurerm_bot_webapp" "example"{
name = "example"
resource_group_name = "example"
resource_group_location = "uksouth"
app_name = "newapp.azurewebsites.com"
bot_template = "basicnode" //options: basicc, echoc, basicnode, echonode
luis_location = "westeurope" //options: westeurope, westus, eastaustralia
app_service_plan = "plan_name" // MUST BE a windows app service plan.
app_insights_enabled = true
app_insights_location = "uksouth" // Optional/Required based on app_insights_enabled
}
```

### References

* #4319

**Comment by katbyte** [comment]
Fixed by #4411
