### ISSUE TITLE
Example request: storage account with VM instance able to access blobs in it

### ISSUE THREAD

**Issue by eriksw** [terraform-providers/terraform-provider-azurerm#4388]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful if there was an example that:

* Creates a storage account
* Creates a container in the storage account
* Creates a VM instance that is able to read and write to that storage account (but not other storage accounts!)
* Creates a second VM instance that is able to read from that storage account, but cannot write to it (or access other storage accounts at all)

This would be of use for people who have experience using Terraform with a different cloud like Amazon or Google, and want to use Terraform examples as a "rosetta stone" of sorts for learning how to do things in Azure.

(Update with a pointer for anyone else, after figuring this out for myself: if you're coming from AWS for instance, `azurerm_user_assigned_identity` is thing you want if you're looking for the equivalent to `aws_iam_role`/`aws_iam_instance_profile`.)

### New or Affected Resource(s)

No changes to resources, just a comprehensive example including:

* azurerm_user_assigned_identity
* azurerm_role_assignment
* azurerm_storage_account
* azurerm_storage_container
* azurerm_virtual_machine

### Potential Terraform Configuration

Unsure, hence the request for this example.

### References

⁇

**Comment by borkod** [comment]
Created PR  #8723  with sample code demonstrating role assignment to a VM instance.

**Comment by tombuildsstuff** [comment]
Closed via #8723
