### ISSUE TITLE
azurerm_dns_a_record/azurerm_dns_cname_record to export FQDN

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#4391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very convenient if azurerm_dns_a_record and azurerm_dns_cname_record exported the FQDN.

### New or Affected Resource(s)

* azurerm_dns_a_record
* azurerm_dns_cname_record

### Potential Terraform Configuration

```hcl
resource "azurerm_dns_a_record" "test" {
  name                = "test"
  zone_name           = "${azurerm_dns_zone.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  ttl                 = 300
  records             = ["10.0.180.17"]
}

resource "azurerm_app_service_custom_hostname_binding" "test" {
  hostname = "${azurerm_dns_a_record.test.fqdn}"
...
...
}

```

**Comment by aqche** [comment]
Opened a PR to add `fqdn` to the two DNS record resources in the issue and went ahead and added it to all the DNS record resources.

**Comment by arkiaconsulting** [comment]
Please note that if you need to use this `fqdn` attribute with the `azurerm_app_service_custom_hostname_binding`, you will need to trim the dot at the end of the fqdn.
