### ISSUE TITLE
mysql Vnet rule creation getting 404 when the subnet_id is in a different subscription than the mysql DB

### ISSUE THREAD

**Issue by myrah** [terraform-providers/terraform-provider-azurerm#4392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.9
Azurerm v1.33.0

### Affected Resource(s)

* azurerm_mysql_virtual_network_rule

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

Error: Subnet with ID "/subscriptions/$sub-id/resourceGroups/$rg-name/providers/Microsoft.Network/virtualNetworks/$vnet/subnets/$subnet" was not found: network.SubnetsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '$rg-name' could not be found."

### Expected Behavior

vnet filtering added

### Actual Behavior

getting 404 error

### Steps to Reproduce

1. `terraform apply`

### References

https://stackoverflow.com/questions/54887254/terraform-azure-deploy-mysql-network-rule-on-another-subscription
* #0000

**Comment by djsly** [comment]
this is because of the hack that was coded in the code
```
NOTE: Due to a bug in the Azure API this resource currently doesn't expose the ignore_missing_vnet_service_endpoint field and defaults this to false. Terraform will check during the provisioning of the Virtual Network Rule that the Subnet contains the Service Rule to verify that the Virtual Network Rule can be created.
```
Since the `provider` blocks is configured with a single subID, it will never have access to the remote subnet SubIDs.

Now that : https://github.com/Azure/azure-rest-api-specs/issues/3719 is fixed the hack should be removed and we should be good to use remote Subnet...

**Comment by svdaddio** [comment]
This is still currently an issue for me
