### ISSUE TITLE
azurerm_platform_image: Add version argument

### ISSUE THREAD

**Issue by jpbuecken** [terraform-providers/terraform-provider-azurerm#4402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello,
is it possible to extend the data source azurerm_platform_image to allow `version` as argument?
Maybe we need a `all=true/false` flag es well, which is automatically true if `version` has been set.
The az image list command does not support a `--version` argument yet, but maybe it is possible to implement it anyway via `filter` Option in the API call (https://docs.microsoft.com/en-us/rest/api/compute/virtualmachineimages/list)

With this it will be possible to boot your instance from a disk, but use a specific image (not latest). And if we boot from VHD, we are able manage tags of the boot disk via terraform.

* azurerm_platform_image

### Potential Terraform Configuration

```hcl
data "azurerm_platform_image" "test" {
  location  = "West Europe"
  publisher = "Canonical"
  offer     = "UbuntuServer"
  sku       = "16.04-LTS"
  version = "16.04.201907290"
}

output "version" {
  value = "${data.azurerm_platform_image.test.id}"
}
```

**Comment by buec011** [comment]
Maybe it is possible to implement query. 

Request is to implement the following request via az cli in the datasource:

```
(azurecli) buec011@gtunxlvk05705:~> az vm image list --location westus --publisher Canonical --offer UbuntuServer --sku 18.04-LTS --all --query "[?contains(version,'18.04.201907080')]"
[
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "18.04-LTS",
    "urn": "Canonical:UbuntuServer:18.04-LTS:18.04.201907080",
    "version": "18.04.201907080"
  }
]
```
