### ISSUE TITLE
azurerm_monitor_metric_alert error Potentially dangerous request.path value

### ISSUE THREAD

**Issue by KefeGF** [terraform-providers/terraform-provider-azurerm#4415]
Hi 

I am trying to create an alert rule using "azurerm_monitor_metric_alert". No matter how I configure it, I get this error message:

Terraform v0.12.9
azurerm v1.33.0

* `azurerm_monitor_metric_alert`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "alert" {
  name                = "Poison queue alert for: ${var.resource_name}"
  resource_group_name = var.rg_name
  scopes              = [var.app_insights_id]
  description         = "Action will be triggered when poison-queue count is greater than 0."

  criteria {
    metric_namespace = "Azure.ApplicationInsights"
    metric_name      = var.metric_name
    aggregation      = "Maximum"
    operator         = "GreaterThanOrEqual"
    threshold        = 1
  }

  action {
    action_group_id = var.action_group_id
  }
}

```

Error message:
```hcl
Error: Error creating or updating metric alert "Poison queue alert for: xxxx" (resource group "xxxx"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>A potentially dangerous Request.Path value was detected from the client (:).</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n
        p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font" error: invalid character '<' looking for beginning of value

  on modules\monitoring\alertrule\main.tf line 1, in resource "azurerm_monitor_metric_alert" "alert":
   1: resource "azurerm_monitor_metric_alert" "alert" {
```

terraform plan does not produce error but terraform apply does.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by KefeGF** [comment]
Has noone experienced this?

**Comment by maydna** [comment]
I experienced this issue also when creating a % free disk alert using terraform

**Comment by KefeGF** [comment]
> I experienced this issue also when creating a % free disk alert using terraform

Did you find a resolution?

**Comment by KefeGF** [comment]
I finally found the mistake. I had the sign ":" in the name property.  After removing it, it worked!
