### ISSUE TITLE
azurerm_storage_account / account_type problems with modules

### ISSUE THREAD

**Issue by donestefan** [terraform-providers/terraform-provider-azurerm#442]
### Terraform Version
 * Terraform v0.10.7 on Win 
 * provider.azurerm: version = "~> 0.3"
 * provider.template: version = "~> 1.0"

### Affected Resource(s)
azurerm_storage_account:
 - account_type
 - account_tier
 - account_replication_type

### Terraform Configuration Files
```hcl
resource "azurerm_storage_account" "storeaccount" {
  #the old way of doing stuff
  #I keep this for backward compatibility
  account_type          = "Standard_GRS"

  #the new way of doing stuff
  account_tier          = "Standard"
  account_replication_type = "GRS"
}
```

### Expected Behavior
`terraform plan [DIR]` works with or without [DIR] or modules

### Actual Behavior

Using `cd /terraform/module1; terraform plan`  I get a warning (which is expected)
```
* module.module1.azurerm_storage_account.storeaccount: "account_type": [DEPRECATED] 
This field has been split into `acount_tier` and `account_replication_type`
```

Using `cd /terraform; terraform plan module1` I get an error which states exactly the opposite of the warning above
```
2 error(s) occurred:
* module.module1.azurerm_storage_account.storeaccount: : invalid or unknown key: account_replication_type
* module.module1.azurerm_storage_account.storeaccount: : invalid or unknown key: account_tier
```

### References
maybe #437 ?!?

**Comment by nbering** [comment]
@donestefan I wonder if you have a version mismatch of the locally-stored modules in the .terraform directory? So in one module, you're using the new version where the variable is deprecated and in the other you're using one where the new variables don't exist? Try `terraform init` maybe?

**Comment by donestefan** [comment]
Thanks for the hint!
We use modules and subdirectories to separate parts of our environment. Due to https://github.com/hashicorp/terraform/issues/15447 I have to change directories before tainting resources. I did not realize that this makes me use a separate copy of the azurerm provider in the sub-folder. After updating the second provider copy everything was smooth again...
