### ISSUE TITLE
Azure shared image gallery version

### ISSUE THREAD

**Issue by nicethomaslearngit** [terraform-providers/terraform-provider-azurerm#4420]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

Hi Team,

  Could you kindly assist me how to get all the image versions in my image definition. I tried multiple ways and no luck.

Any help is much appreciated.

Thank You

**Comment by LW81** [comment]
I would like to add a second part to that question.
Is there any way to get the "latest" version of a specific image ?

I see that the resource "azurerm_shared_image_version" has an argument called "exclude_from_latest"

But i have no idea how to query an image for its latest version.

Cheers

**Comment by nicethomaslearngit** [comment]
Hi @LW81 

The below will give you the latest image version

data "azurerm_shared_image" "latest" {
  name                = "test"
  gallery_name        = "test_gallery"
  resource_group_name = "test_resource"
}

 id = "${data.azurerm_shared_image.latest.id}"

**Comment by LW81** [comment]
Thx @nicethomaslearngit 

but i am afraid that's not correct what you are saying.
This will just give you back the ID of the Shared Image, but **not** the latest Image_Version of that Image.

Or am i missing something here ?

**Comment by nicethomaslearngit** [comment]
Hi @steffencircle 

Apologize I missed your comment, it will give the ID of the latest image - not the version number.

Thank You

**Comment by a8ree** [comment]
Was a solution for this found - I have the same issue :(
