### ISSUE TITLE
service-mode and allowed-origins arguments missing from azurerm_signalr_service

### ISSUE THREAD

**Issue by shiv-rajawat** [terraform-providers/terraform-provider-azurerm#4422]
## Community Note ##
- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
## Description ##
It would be really helpful if "allowed-origins" and "service-mode" are also included. Their absence introduces extra manual effort.

## References ##
https://docs.microsoft.com/en-us/cli/azure/signalr?view=azure-cli-latest

**Comment by brunhil** [comment]
I started working on this, should hopefully have a PR soon!
