### ISSUE TITLE
"Principal does not exist in the directory" when creating role assignment

### ISSUE THREAD

**Issue by james-miller** [terraform-providers/terraform-provider-azurerm#4430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We're trying to delegate permissions to a terraform application in the same tennant but from a different subscription. The objective here is to facilitate cross-subscription peering. When adding a role assignment to do this, Terraform fails on the apply stage saying the Principle cannot be found. We've checked the output of the data sources we're using and they are returning the correct values. We've also tried using the application_id and object_id attributes of the application but neither seem to work.

When the object_id is used (as suggested by the documentation here - https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html#principal_id) the following error is produced:
```
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalTypeNotSupported" Message="Principals of type Application cannot validly be used in role assignments."
```

### Terraform (and AzureRM Provider) Version
Terraform - 0.12.9
AzureRM Provider - 1.34.0

### Affected Resource(s)

* `azurerm_role_assignment`

### Terraform Configuration Files

```hcl
data "azurerm_virtual_network" "coa_extranet" {
  name                = "extranet-vnet"
  resource_group_name = "extranetnetwork-rg"
}

data "azuread_application" "ioj_terraform" {
  name = "ioj-terraform"
}

resource "azurerm_role_assignment" "ioj_network_peering" {
  scope                = data.azurerm_virtual_network.coa_extranet.id
  role_definition_name = "Network Contributor"
  principal_id         = data.azuread_application.ioj_terraform.application_id
}
```

### Panic Output

```
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal *********************** does not exist in the directory *****-****-****-****-*******."
````

### Expected Behavior

Role assignment should be created to give Network Contributor permissions to a terraform application in another subscription in the same tennant.

**Comment by tiwood** [comment]
You have to use the `object id`, not the `application id`:
```
resource "azurerm_role_assignment" "ioj_network_peering" {
  scope                = data.azurerm_virtual_network.coa_extranet.id
  role_definition_name = "Network Contributor"
  principal_id         = data.azuread_application.ioj_terraform.id
}
```

**Comment by james-miller** [comment]
We tried using the .id attribute and it returns this error:
```
Code="PrincipalTypeNotSupported" Message="Principals of type Application cannot validly be used in role assignments.
```

**Comment by tiwood** [comment]
My bad. You have to assign the role to a service principal, which is a representation of an application in your directory.

azuread_service_principal.foo.id

RBAC Permissions are always assigned to a principal, not an application.

**Comment by james-miller** [comment]
Yeah, that fixed it.

The documentation is pretty misleading in that case:
```
principal_id - (Required) The ID of the Principal (User, Group, Service Principal, or Application) to assign the Role Definition to. Changing this forces a new resource to be created.
```
