### ISSUE TITLE
New Data Source: azurerm_app_service_certificate

### ISSUE THREAD

**Issue by PSanetra** [terraform-providers/terraform-provider-azurerm#4456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to have a data source equivalent for the new `azurerm_app_service_certificate` resource.

### New or Affected Resource(s)

* data azurerm_app_service_certificate

### Potential Terraform Configuration

```hcl
data "azurerm_app_service_certificate" "example" {
  name                = "example-cert"
  resource_group_name = "${data.azurerm_resource_group.example.name}"
}
```

**Comment by r0bnet** [comment]
PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4468
