### ISSUE TITLE
azurerm_cosmosdb_mongo_collection does not seem to allow compound indexes

### ISSUE THREAD

**Issue by ragoragino** [terraform-providers/terraform-provider-azurerm#4460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

MongoDB API for CosmosDB supports compound indexes (https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing). However, there does not seem to be a way to create them through Terraform azurerm_cosmosdb_mongo_collection resource.

**Comment by Simon-Bru** [comment]
Same for DocumentDB API.

Custom indexes is possible via [powershell](https://docs.microsoft.com/fr-fr/azure/cosmos-db/manage-with-powershell#create-container-custom-index)

**Comment by ragoragino** [comment]
I just wanted to share an update. I have tried using Azure SDK with compound indexes that are unique and it works. Therefore, the schema for key in https://github.com/terraform-providers/terraform-provider-azurerm/blob/d8fefed6ac39fbbf5f41c2a433bc1df16a252904/azurerm/resource_arm_cosmosdb_mongo_collection.go#L91 could contain a list of strings (with a unique flag set to true in that case).

**Comment by rmihael** [comment]
Is it anywhere on the roadmap? This is a major limiting factor for CosmosDB provisioning through Terraform.
