### ISSUE TITLE
Support planned AKS API default swap to VMSS + SLB (from VMAS + BLB)

### ISSUE THREAD

**Issue by jluk** [terraform-providers/terraform-provider-azurerm#4465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS has made VMSS and SLB generally available. These two cluster configurations are the highly recommended options to be used for the long term and will be required for using future features such as availability zones and multiple node pools. To encourage adoption, the default configurations during cluster create will move from VMAS/basicLB to VMSS/standardLB. Given this is a behavior change AKS is phasing this in slowly.

In the first phase the Azure clients (Azure CLI and Azure portal) will update the client logic to use VMSS/SLB. These should be complete by November.

In the second phase the AKS API will update a new API version to default to using VMSS/SLB unless explicitly stated to use something else. This is planned for post-November in a new API version, each version release after that one will keep the new default setting.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

**Comment by tombuildsstuff** [comment]
Re-opening this to track the switch to a Standard LB in 2.0
