### ISSUE TITLE
azurerm_route_table with azurerm_route flipping resources

### ISSUE THREAD

**Issue by thiagocaiubi** [terraform-providers/terraform-provider-azurerm#447]
### Terraform Version
0.10.7

### AzureRM Provider Version
0.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_route_table
- azurerm_route

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "test" {
  name     = "acceptanceTestResourceGroup1"
  location = "West US"
}

resource "azurerm_route_table" "test" {
  name                = "acceptanceTestRouteTable1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_route" "test" {
  name                = "acceptanceTestRoute1"
  resource_group_name = "${azurerm_resource_group.test.name}"
  route_table_name    = "${azurerm_route_table.test.name}"
  address_prefix      = "10.1.0.0/16"
  next_hop_type       = "vnetlocal"
}
```

### Debug Output
https://gist.github.com/thiagocaiubi/1c39ca2a9e40f866cc8ae3473b273cf1

### Expected Behavior
First `terraform apply` must create the infrastructure.
Second `terraform apply` must do nothing.

### Actual Behavior
Subsequent `terraform apply` are creating/destroying the resources.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
2. `terraform apply`

### References
I guess is something related to the refactoring from Set to List.
Pretty sure that I'm facing the same issue with `azurerm_network_security_group` and `azurerm_network_security_rule`.

 - https://github.com/terraform-providers/terraform-provider-azurerm/pull/402

**Comment by thiagocaiubi** [comment]
I've tested the same HCL against terraform v0.10.7 and azurerm provider v0.2.2 and get the expected behavior successfully.

Debug output: https://gist.github.com/thiagocaiubi/4030764cf958207a125c28e9e856253e

**Comment by fstuck37** [comment]
I appear to have this issue as well.
I'm adding a default route via azurerm_route and when I do a subsequent plan it wants to delete it from the azurerm_route_table.  If I apply, allow it to remove it, and than plan again; it wants to add it based on azurerm_route. So it is flipping the route between the azurerm_route and azurerm_route_table.

  ~ module.vnet.azurerm_route_table.privrt
      route.#:                "1" => "0"
      route.0.address_prefix: "0.0.0.0/0" => ""
      route.0.name:           "DefaultGateway" => ""
      route.0.next_hop_type:  "VirtualAppliance" => ""

I'm using 0.10.7 as well and Azure provider 0.3.1.
(terraform-provider-azurerm_v0.3.1_x4.exe)
I didn't have this issue with a previous version v0.1.7.
(terraform-provider-azurerm_v0.1.7_x4.exe)

Still reviewing to see if I can work around it and will provide additional information if I find any.

Thanks,
Fred

**Comment by VaijanathB** [comment]
Hello @thiagocaiubi , 

Since you have already confirmed that this is no longer an issue, can you please go ahead and close this.

Thanks, 
VJ

**Comment by fstuck37** [comment]
VJ,
I still have this issue. I think thiagocaiubi was saying that this issue didn't exist in an older version (Terraform v0.10.7 and azurerm provider v0.2.2) and for me, I didn't have this issue with Azure version v0.1.7.

Seems like this issue was introduced between v0.2.2 and v0.3.0.
(v0.2.2 < v?.?.? <= v0.3.0)

Hope this helps

Thanks,
Fred

**Comment by keeperpl** [comment]
I have the same issue. 
Terraform v. 0.10.8
Azurerm provider v. 0.3.2
Plan is showing that all route tables would be cleared despite rules being defined in code.

**Comment by thiagocaiubi** [comment]
Thanks, @fstuck37. That's it!

**Comment by VaijanathB** [comment]
Hello @thiagocaiubi , @fstuck37 , 

Thanks for the clarification.  I tried the above repro provided by @thiagocaiubi , with Terraform version 0.10.9 and Azure provider version 0.3.2 and could not reproduce it.  
 When I perform, tf apply multiple times I get the following output. 
tf apply
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
tf apply 
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

If this is still an issue with latest version of Terraform and provider, can you provide with me updated repro steps ? 

Thanks, 
VJ

**Comment by fstuck37** [comment]
@VaijanathB - seems like v0.3.2 fixes the issue. Not sure what caused it but looks better now.
Thanks,
Fred

**Comment by thiagocaiubi** [comment]
Hi @VaijanathB .

I've tested with terraform v0.10.8 and azurerm provider v0.3.2 and it worked as expected. I will now close the issue. Thanks!

PS: You mentioned terraform v0.10.9, I'm afraid it doesn't exists.
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md

**Comment by clarkcode** [comment]
@thiagocaiubi 
Seeing the same issue:
Terraform `v0.12.0`
azurerm `v1.30`

- First-time plan + apply works as expected.
- Second plan sets the azurerm_route.example-route for destroy.

**Example:**
```hcl
resource "azurerm_resource_group" "example-rsg" {
    name     = "example-rsg"
    location = "uksouth"
}

resource "azurerm_virtual_network" "example-vnet" {
    name                = "example-vnet"
    location            = "uksouth"
    resource_group_name = "example-rsg"
    address_space       = ["10.0.0.0/24"]
}

resource "azurerm_subnet" "example-subnet" {
    name                        = "example-subnet"
    resource_group_name         = "example-rsg"
    virtual_network_name        = "${azurerm_virtual_network.example-vnet.name}"
    address_prefix              = "10.0.0.0/24"
    route_table_id              = "${azurerm_route_table.example-udr.id}"
    lifecycle { 
        ignore_changes = ["route_table_id"]
    }
}

resource "azurerm_route_table" "example-udr" {
    name                = "example-udr"
    location            = "uksouth"
    resource_group_name = "example-rsg"
    route {
        name           = "default-route"
        address_prefix = "0.0.0.0/0"
        next_hop_type  = "Internet"
    }
}

resource "azurerm_subnet_route_table_association" "perimeter-subnet-association" {
  subnet_id                 = "${azurerm_subnet.example-subnet.id}"
  route_table_id            = "${azurerm_route_table.example-udr.id}"
}

resource "azurerm_route" "example-route" {
    name                    = "example-route"
    resource_group_name     = "example-rsg"
    route_table_name        = "${azurerm_route_table.example-udr.name}"
    address_prefix          = "192.168.0.0/24"
    next_hop_type           = "VirtualAppliance"
    next_hop_in_ip_address  = "10.0.0.1"
}
```
