### ISSUE TITLE
Support sampling_percentage In azurerm_application_insights

### ISSUE THREAD

**Issue by SethNute** [terraform-providers/terraform-provider-azurerm#4487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

This is a feature request for the ability to manage the sampling rate of an application insights resource using the azurerm provider. 

It is currently possible to set the sampling percentage using the UI/ARM templates/AZ PowerShell/etc, see the references section below. It would be nice to be able to control it from TF, too.

### New or Affected Resource(s)

* azurerm_application_insights

### Potential Terraform Configuration

```hcl
resource "azurerm_application_insights" "example" {
  name                           = "example"
  location                       = "eastus2"
  resource_group_name            = azurerm_resource_group.example.name
  application_type               = "web"
  sampling_percentage            = var.env == "prod" ? 100 : 25
}
```

### References

Some other ways of creating application insights instances, these all support sampling percentage
* ARM https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-05-01/components
* AZ PowerShell https://docs.microsoft.com/en-us/powershell/module/az.applicationinsights/new-azapplicationinsights?view=azps-2.7.0

**Comment by aqche** [comment]
Looking into this, will have a PR open soon!
