### ISSUE TITLE
why azure front door name has to be same as fqdn

### ISSUE THREAD

**Issue by rvashishth** [terraform-providers/terraform-provider-azurerm#4495]
### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "tf-test-fds" {
  name                                         = sample-fds"
  frontend_endpoint {
    name                              = "my-tf-tamma-fds"
    host_name                         = "tf-test-fds.azurefd.net"
  }
```
### Panic Output

here resource name `tf-test-fds` has to be used as subdomain name in `frontend_endpoint.hostname` if i change hostname to something else from `**tf-test-fds**.azurefd.net` to  `**tf-test-fds-sometheelse**.azurefd.net` it gives following error 

```
frontdoor.FrontDoorsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="We couldn't find a DNS record for custom domain tf-test-fds-sometheelse.azurefd.net that points to Front Door tf-test-fds.To map a domain to this Front Door, create a CNAME record with your DNS provider for custom domain that points to Front Door."
```

### Expected Behavior

We should be allowed to choose resource names irrespective of what hostname we choose.

### Actual Behavior

Resource local name is used as front-door name. 

### Steps to Reproduce

1. `terraform apply`

**Comment by rvashishth** [comment]
developer mistake

**Comment by 777jacq777** [comment]
hey, can you shed some light on what was the mistake please? I am getting the same error, many thanks

**Comment by rvashishth** [comment]
Frontend endpoint Host name subdomain must be same as frontdoor name. In my case it must be sample-fds.azurefd.net

**Comment by 777jacq777** [comment]
Nice one, cheers bud

**Comment by andresbarcenas** [comment]
Hello,

When is this going to be corrected? I want to use terraform to create multiple custom domains within the same frontdoor resource.

Thanks.
