### ISSUE TITLE
Managed Identities for AKS

### ISSUE THREAD

**Issue by fxgsell** [terraform-providers/terraform-provider-azurerm#4506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS released support for managed identity in preview, it can be used with the cli by adding the flag `--enable-managed-identity`. (preview is public but the subscription must be opted-in the preview)

In the preview period, a service principal is still required but eventually this requirement in AKS will be removed completely.

This will also required new exported attributes (in an identity block):

* principal_id - The Principal ID for the Service Principal associated with the Managed Service Identity.
* tenant_id - The Tenant ID for the Service Principal associated with the Managed Service Identity.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration
2 options:

Either a simple flag:
```hcl
resource "azurerm_kubernetes_cluster" "test" {
  enable_managed_identity = true
  ...
}
```

Or a new identity block: (Example here is for Managed identity this should also support specifying a SP like other resources using identities)
```hcl
resource "azurerm_kubernetes_cluster" "test" {
  ...
  identity {
    type = "SystemAssigned"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by sauryadas** [comment]
at GA the SA managed identity will be created by default, no explicit flag will be required

**Comment by fxgsell** [comment]
Ok, we will still need to export the new identity information and remove/make optional the existing fields.

**Comment by mbrancato** [comment]
While the service identity may be created by default, there is still a schema change required for this resource as the `service_principal` block is required today. Also, explicit SP assignment is still supported as I understand it, so making this block optional seems good. It might also be good to align the name of this block with other resources supporting MSI like `azurerm_app_service` and `azurerm_virtual_machine`.

**Comment by shubham124** [comment]
Can someone share a link which contains aks creation through terraform using user managed identity.
It will  be really helpful as I am facing so many challenges and also above suggestion was not working.

**Comment by jkdey** [comment]
I get the following when attempting to set a managed_cluster_identity block:

```
validate: error: failed to validate Terraform configuration in .

Error: Unsupported block type

  on main.tf line 88, in resource "azurerm_kubernetes_cluster" "vault":
  88:   managed_cluster_identity {

Blocks of type "managed_cluster_identity" are not expected here.
```
