### ISSUE TITLE
Lifecycle "ignore_changes" does not work on AKS agent_pool_profile*

### ISSUE THREAD

**Issue by archmangler** [terraform-providers/terraform-provider-azurerm#4511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

We need to ignore changes the os_disk size for agent nodes in the cluster as changes to the agent disk force a destroy of the entire cluster (which means we can't expand AKS cluster node root disks without destroying the cluster!)

It seems the only way to accomplish this is to ignore_changes on the agentpool configuration, as described in this issue: 

https://github.com/terraform-providers/terraform-provider-azurerm/issues/2114

However it appears ignore_changes for the agent_pool_profile resource is completely ignored during plan, resulting in proposed destroy of the cluster.

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {

  .
  .
  .

  agent_pool_profile {
    name            = "agentpool"
    count           = "${var.aks_map["aks_agent_count"]}"
    vm_size         = "${var.aks_map["aks_agent_vm_size"]}"
    os_type         = "Linux"
    os_disk_size_gb = "${var.aks_map["aks_agent_os_disk_size"]}"
    vnet_subnet_id  = "${data.azurerm_subnet.aks.id}"
  }

  network_profile {
    network_plugin     = "${var.aks_map["aks_netPlugin"]}"
    dns_service_ip     = "${var.aks_map["aks_dns_service_ip"]}"
    docker_bridge_cidr = "${var.aks_map["aks_docker_bridge_cidr"]}"
    service_cidr       = "${var.aks_map["aks_service_cidr"]}"
  }

  lifecycle {
    ignore_changes = [
      "agent_pool_profile.agentpool.os_disk_size_gb"
    ]
  }
}

```

For the lifecycle bloc I have tested the following variations to no effect:

```
  lifecycle {
    ignore_changes = [
      "agent_pool_profile"
    ]
  }
.
.
  lifecycle {
    ignore_changes = [
      "agent_pool_profile.agentpool"
    ]
  }
.
.
.
```

### Debug Output

```
13:52:38 module.storageaccount_region1.output.primary_blob_endpoint - *terraform.NodeApplyableOutput
13:52:38 module.storageaccount_region1.output.primary_connection_string - *terraform.NodeApplyableOutput
13:52:38 module.storageaccount_region2.azurerm_storage_account.instance - *terraform.NodeAbstractResource
13:52:38 module.storageaccount_region2.data.azurerm_key_vault.instance - *terraform.NodeAbstractResource
13:52:38 module.storageaccount_region2.data.azurerm_key_vault_key.instance - *terraform.NodeAbstractResource
13:52:38 module.storageaccount_region2.data.azurerm_resource_group.instance - *terraform.NodeAbstractResourerm_subnet_network_security_group_association", RawCount:(*config.RawConfig)(0xc0002b6000), RawConfig:(*config.RawConfig)(0xc000167730), Provisioners:[]*config.Provisioner(nil), Provider:"", DependsOn:[]string(nil), Lifecycle:config.ResourceLifecycle{CreateBeforeDestroy:false, PreventDestroy:false, IgnoreChanges:[]string(nil)}}
13:52:38 2019/10/04 05:52:38 [TRACE] AttachResourceConfigTransformer: Attach resource config request: module.aks_region1.azurerm_kubernetes_cluster.k8s
13:52:38 2019/10/04 05:52:38 [TRACE] Attaching resource config: &config.Resource{Mode:0, Name:"k8s", Type:"azurerm_kubernetes_cluster", RawCount:(*config.RawConfig)(0xc0003bb030), RawConfig:(*config.RawConfig)(0xc0003ba070), Provisioners:[]*config.Provisioner(nil), Provider:"", DependsOn:[]string(nil), Lifecycle:config.ResourceLifecycle{CreateBeforeDestroy:false, PreventDestroy:false, IgnoreChanges:[]string{"agent_pool_profile.os_disk_size_gb"}}}
13:52:38 2019/10/04 05:52:38 [TRACE] AttachResourceConfigTransformer: Attach resource config request: module.nsg_rules_aks_region2.azurerm_network_security_rule.asg_rules_inbound
13:52:38 2019/10/04 05:52:38 [TRACE] Attaching resource config: &config.Resource{Mode:0, Name:"asg_rules_inbound", Type:"azurerm_network_security_rule", RawCount:(*config.RawConfig)(0xc000154230), RawConfig:(*config.RawConfig)(0xc000038850), Provisioners:[]*config.Provisioner(nil), Provider:"", DependsOn:[]string(nil), Lifecycle:config.ResourceLifecycle{CreateBeforeDestroy:false, PreventDestroy:false, IgnoreChanges:[]string(nil)}}
13:52:38 2019/10/04 05:52:38 [TRACE] AttachResourceConfigTransformer: Attach resource config request: module.nsg_rules_aks_region1.azurerm_network_security_rule.asg_rules_outbound
13:52:38 on2.local.resources - *terraform.NodeLocal
13:52:38 module.aks_region2.local.subsCode - *terraform.NodeLocal
13:52:38 module.aks_region2.local.vnet_ref - *terraform.NodeLocal
```

### Panic Output

n/a

### Expected Behavior

Use of this statement should result in any changes to agent_pool_profile not resulting in AKS cluster re-creation:

```
  lifecycle {
    ignore_changes = [
      "agent_pool_profile"
    ]
  }
```

Ideally it should be as granular as:

```
  lifecycle {
    ignore_changes = [
      "agent_pool_profile.agentpool.os_disk_size_gb"
    ]
  }
```

### Actual Behavior

Change in os_disk size returned by AKS platform triggers aks re-creation:

```

17:20:44       agent_pool_profile.0.max_pods:                                          "30" => <computed>
17:20:44       agent_pool_profile.0.name:                                              "agentpool" => "agentpool"
17:20:44       agent_pool_profile.0.os_disk_size_gb:                                   "32" => "300" (forces new resource)
17:20:44       agent_pool_profile.0.os_type:                                           "Linux" => "Linux"
17:20:44       agent_pool_profile.0.type:                                              "AvailabilitySet" => "AvailabilitySet"
17:20:44       agent_pool_profile.0.vm_size:                                           "Standard_D8s_v3" =>"Standard_D8s_v3"
```

### Steps to Reproduce

1. Deploy an AKS cluster with terraform.
2. Modify the os_disk  size in code 
3. Modify the actual node disks to match code configuration
4. Update the state to match code and physical resource
5. Plan
6. apply

NOTE: we've tested steps 2,3,4 in an effort to get terraform AKS resource to ignore changes in OS disk size. The fact that terraform  doesn't ignore_changes on this means a disk upgrade requires to destroy the cluster.

### Important Factoids

Azure Southeastasia, eastasia

### References

Essentially the same issue as this:

https://github.com/terraform-providers/terraform-provider-azurerm/issues/2114

* #0000

**Comment by archmangler** [comment]
Another related issue is that somehow the terraform azurerm provider reads the agent_node o.s disk size from Azure AKS API, instead of from the agent nodes or from the state only. AKS itself doesn't seem to refresh the os disk sizes if they're updated outside of the platform.

**Comment by phekmat** [comment]
I think you're missing the pool index `0` from your original `ignore_changes`. You want: 
```hcl
lifecycle {
    ignore_changes = "agent_pool_profile.0.os_disk_size_gb"
}
```

**Comment by archmangler** [comment]
Hi @phekmat  - I believe that's it, thanks. More needed to be added to ignore_change than just agent_pool_profile. 

You may mark this item closed.
