### ISSUE TITLE
Resources on creation of Web App Bot

### ISSUE THREAD

**Issue by tbviveiros** [terraform-providers/terraform-provider-azurerm#4515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
1.35.0

### Affected Resource(s)

* azurerm_bot_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "${var.environment}-${var.region_name}-${var.name}"
  location = "${var.region_code}"
}
resource "azurerm_application_insights" "ai" {
  name                = "AI-${var.name}"
  location            = "${var.region_code}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  application_type    = "web"
}

resource "azurerm_application_insights_api_key" "full_permissions" {
  name                    = "${lower(var.name)}-full-permissions-api-key"
  application_insights_id = "${azurerm_application_insights.ai.id}"
  read_permissions        = ["agentconfig", "aggregate", "api", "draft", "extendqueries", "search"]
  write_permissions       = ["annotations"]
}

resource "azurerm_bot_web_app" "bot" {
  name                                  = "${var.name}"
  resource_group_name                   = "${azurerm_resource_group.rg.name}"
  location                              = "global"
  sku                                   = "F0"
  microsoft_app_id                      = "${azuread_service_principal.app.application_id}"
  endpoint                              = "https://${lower(var.name)}.azurewebsites.net/api/messages"
  developer_app_insights_key            = "${azurerm_application_insights.ai.instrumentation_key}"
  developer_app_insights_api_key        = "${azurerm_application_insights_api_key.full_permissions.api_key}"
  developer_app_insights_application_id = "${azurerm_application_insights.ai.app_id}"
}

```

### Actual Behavior

It should create a Web App Bot, but the configuration of a App Service and a App Service plan, somehow should be create within the Web App Bot.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
Hi @tbviveiros,

I'm not sure what the issue is. Could you please elaborate on what is not working or include some terraform output?

thanks!
