### ISSUE TITLE
module.storage.azurerm_storage_container.vhds: Resource 'azurerm_storage_account.vhds' not found for variable 'azurerm_storage_account.vhds.name

### ISSUE THREAD

**Issue by przemolb** [terraform-providers/terraform-provider-azurerm#452]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_storage_account

### Terraform Configuration Files
```hcl
...
resource "azurerm_storage_account" "vhds" {
  name = "${var.prefix}r3storage"
  resource_group_name = "${var.group}"
  location = "${var.location}"
  account_tier = "${var.account_tier}"
  account_replication_type = "${var.account_replication_type}"
  enable_blob_encryption = true
}
resource "azurerm_storage_container" "vhds" {
  name = "vhds"
  storage_account_name = "${azurerm_storage_account.vhds.name}"
  container_access_type = "private"
  resource_group_name = "${var.group}"
}
...
...
module "group" {
  source = "git::ssh://git@bitbucket.org/sth/terraform-modules.git//resource_group/?ref=v1.15"
  group = "${var.name}"
  name = "${var.name}"
  location = "${var.location}"
}

module "storage" {
  source = "git::ssh://git@bitbucket.org/sth/terraform-modules.git//storage_vhds/?ref=elk"
  prefix = "${module.group.group}"
  location = "${var.location}"
  account_tier = "${var.account_tier}"
  account_replication_type = "${var.account_replication_type}"
  group = "${module.group.group}"
}

module "net" {
  source = "git::ssh://git@bitbucket.org/sth/terraform-modules.git//elk_network/?ref=v1.15"
  prefix = "${module.group.group}"
  location = "${var.location}"
  subnet_range ="${var.subnet_range}"
  network_ip_range ="${var.network_ip_range}"
  group = "${module.group.group}"
}


```

### Debug Output
https://gist.github.com/anonymous/2661c6ae66b21fde80999e266771e4fa

### Panic Output
Terraform didn't panic.

### Expected Behavior
Terraform should prepare plan.

### Actual Behavior
It is giving an error:
Resource 'azurerm_storage_account.vhds' not found for variable 'azurerm_storage_account.vhds.name

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform get
2. terraform init
3. terraform plan

**Comment by tombuildsstuff** [comment]
hey @przemolb

Thanks for opening this issue

Taking a look at the configuration you've posted above - I'm unable to see the issue; as such I believe the issue is within one of the modules, rather than in the root configuration. So that we can take a further look into this, would it be possible to produce a standalone configuration which exhibits this behaviour?

Thanks!

**Comment by przemolb** [comment]
It turned out (during debug session) that I was using wrong name for resource "azurerm_storage_account.vhds" (combination of upper case letters and hyphens).
But the error message wasn't helpful at all. I wonder why all errors are not displayed on the screen and only in debug session.
