### ISSUE TITLE
Extend azurerm_image to support searching for an image

### ISSUE THREAD

**Issue by clangaxon** [terraform-providers/terraform-provider-azurerm#454]
It would be very useful to modify azurerm_image to work like aws_ami and be able to at least do some basic filtering to return a particular image.  Even just a name prefix search with support for 'most_recent' would allow e.g. maintaining a series of images with Packer and always deploying with the latest one.

Thanks!

**Comment by choppedpork** [comment]
Having noticed #436 just got closed I was about to raise the same request! Our current flow in AWS creates base AMIs with unique (timestamped) names and terraform just looks up the most recent image. Would be great to be able to do this in Azure, especially considering it's not currently possible to overwrite Azure managed disk images with packer (https://github.com/hashicorp/packer/issues/5509).

**Comment by kmcquade** [comment]
+1
