### ISSUE TITLE
az premium files max at 5T (vs 100T)

### ISSUE THREAD

**Issue by surlypants** [terraform-providers/terraform-provider-azurerm#4552]
Given an azure premium files storage account, TF (0.12.9) constrains the quota/sizing between 100M and 5T, whereas the portal allows 100M - 100T.

attempting to supply (in TF) a quota > 50120 yields:

Invalid input: `input.QuotaInGB` must be greater than 0, and less than/equal to 5TB (5120 GB)

100T portal creation validated by az cli:

az storage share list --account-name ${my_premium_files_SA} | grep quota
      "quota": 102400

TF:
* provider.azuread: version = "~> 0.6"
* provider.azurerm: version = "~> 1.35"
* provider.external: version = "~> 1.2"
* provider.null: version = "~> 2.1"
* provider.random: version = "~> 2.2"

**Comment by surlypants** [comment]
per: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/vendor/github.com/tombuildsstuff/giovanni/storage/2018-11-09/file/shares/properties_set.go

```
	if newQuotaGB <= 0 || newQuotaGB > 5120 {
		return result, validation.NewError("shares.Client", "SetProperties", "`newQuotaGB` must be greater than 0, and less than/equal to 5TB (5120 GB)")
	}

**Comment by katbyte** [comment]
Hi @surlypants, 

if you open a PR on the giovanni we can get it merged and into 1.36 🙂

**Comment by surlypants** [comment]
the appropriate fix will need to case between std and premium storage, where std allowed values are 1-5120, and premium allowed values are 100-102400

**Comment by surlypants** [comment]
std files now also needs 100T:

https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-larger-more-powerful-standard-file-shares-for-azure-files/

**Comment by BzSpi** [comment]
For the standard tier, the `large file share` flag must be enabled, so additional configuration is expected.

https://docs.microsoft.com/en-us/azure/storage/files/storage-files-how-to-create-large-file-share

**Comment by rem-aj** [comment]
Same issue with AzureRM provider 2.0 version.
