### ISSUE TITLE
azurerm_key_vault_secret Forbidden and Client address is not authorized and caller is not a trusted service error

### ISSUE THREAD

**Issue by rkrishashokkumar** [terraform-providers/terraform-provider-azurerm#4553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.14

### Affected Resource(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_key_vault" "key_vlt" {
  name                        = "gavarvdev008"
  location                    = "East US" 
  resource_group_name         = "MYRESOURCEGROUP"
  enabled_for_disk_encryption = true
  tenant_id                   = "${var.tenantId}"  

  sku_name = "standard"

   network_acls {
    default_action             = "Deny"
    bypass                     = "AzureServices"
    virtual_network_subnet_ids = ["${var.ase_sbt_id}"]
    ip_rules                   = "${var.keyvault_exception_ip}"
  }
  
  tags = {
            uai = "${var.uai}"
            env = "${var.env}"
            SupportEmail = "${var.supportEmail}"
        }
}

resource "azurerm_key_vault_access_policy" "service_principal_access" {
  key_vault_id = "${azurerm_key_vault.key_vlt.id}"
  tenant_id = "${var.tenantId}"
  object_id = "${var.object_id}"	
  application_id = "${var.service_principal_id}"

    key_permissions = [
      "get",
	    "list",
      "create",
      "encrypt",
      "decrypt",
    ]

    secret_permissions = [
      "get",
	    "list",
      "set",
      "delete",
    ]
}

resource "azurerm_key_vault_secret" "azureanalytics_auth_id" {
  name     = "AzureAnalyticsAuthId"
  value    = "123"
  key_vault_id = "${azurerm_key_vault.key_vlt.id}"
  tags = {
    environment = "${var.env}"
  }
  depends_on = ["azurerm_key_vault_access_policy.service_principal_access"]
}

### Expected Behavior

terraform should create key vault and secrets successfully

### Actual Behavior

When the network_acls is set in keyvault, It expects the client address to be added . If that is the case, how can we add the client ip address dynamically when it is executed from azure DevOps ?

Error: Error applying plan:

1 error occurred:
        * azurerm_key_vault_secret.azureanalytics_auth_id: 1 error occurred:
        * azurerm_key_vault_secret.azureanalytics_auth_id: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Client address is not authorized and caller is not
a trusted service.\r\nClient address: 165.156.40.22\r\nCaller: appid=xxx-xx-xxx-xxx;oid=xxx-xxx-xx-xx-xx;iss=https://sts.windows.net/xxx-xxx-x-xx-xx/\r\nVault: gavarvdev008;location=eastus" InnerError={"code":"ForbiddenByFirewall"}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rkrishashokkumar** [comment]
Any updates on this please ?

**Comment by richardzone** [comment]
@rkrishashokkumar  have you tried using the Azure Devops IP ranges published in its documentation: https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#ip-addresses-and-range-restrictions​​​​​​​

**Comment by tombuildsstuff** [comment]
hi @rkrishashokkumar 

Thanks for opening this issue.

As @richardzone has mentioned you'll need to add the IP Ranges for Azure DevOps, since this isn't covered by the "Allow Azure Services" option - if you do this then you should be able to access them from this location. The same is true for any other location, you'll need to add the IP Addresss/Ranges to the Firewall Rules to be able to access the Key Vault if it's not one of the supported Azure Services - since otherwise you'll get this "Unauthorized" message.

Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look.

Thanks!
