### ISSUE TITLE
Azure Frontdoor: support custom timeout for backend pool

### ISSUE THREAD

**Issue by geertn** [terraform-providers/terraform-provider-azurerm#4558]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Frontdoor supports setting a custom timeout for the backend. The standard timeout is 30s which is quite short.

See also:
https://feedback.azure.com/forums/217313-networking/suggestions/36482500-allow-configurable-timeout-period-for-front-door
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-05-01/frontdoor.json

In the last link there are 2 backend pool settings:
1. enforceCertificateNameCheck
2. sendRecvTimeoutSeconds

(1) is supported by terraform using the `enforce_backend_pools_certificate_name_check` directive.

Please add a directive to support `sendRecvTimeoutSeconds`. I'm not sure if this directive applies to all backend pools or only a specified one.

### New or Affected Resource(s)

* azurerm_frontdoor

### Potential Terraform Configuration

```hcl
resource "azurerm_frontdoor" "example" {
  name                                         = "example-FrontDoor"
  location                                     = "${azurerm_resource_group.example.location}"
  resource_group_name                          = "${azurerm_resource_group.example.name}"
  enforce_backend_pools_certificate_name_check = false
  backend_pools_request_timeout = "60"
...
```

### References

https://feedback.azure.com/forums/217313-networking/suggestions/36482500-allow-configurable-timeout-period-for-front-door
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/frontdoor/resource-manager/Microsoft.Network/stable/2019-05-01/frontdoor.json

**Comment by WodansSon** [comment]
I will need to update the Azure SDK for GO used by Terraform, currently that attribute isn't exposed in the API version we are currently using....

API Version 2019-04-01 (currently used by Terraform):
```
720 // BackendPoolsSettings settings that apply to all backend pools.
721 type BackendPoolsSettings struct {
722 	// EnforceCertificateNameCheck - Whether to enforce certificate name check on HTTPS requests to all backend pools. No effect on non-HTTPS requests. Possible values include: 'EnforceCertificateNameCheckEnabledStateEnabled', 'EnforceCertificateNameCheckEnabledStateDisabled'
723 	EnforceCertificateNameCheck EnforceCertificateNameCheckEnabledState `json:"enforceCertificateNameCheck,omitempty"`
724 }
```
[SDK Link](https://github.com/Azure/azure-sdk-for-go/blob/c831e483e2058e9b2a8f9b4e35248f46f9516b4c/services/frontdoor/mgmt/2019-04-01/frontdoor/models.go#L720)


API Version 2019-05-01:
```
752 // BackendPoolsSettings settings that apply to all backend pools.
753 type BackendPoolsSettings struct {
754 	// EnforceCertificateNameCheck - Whether to enforce certificate name check on HTTPS requests to all backend pools. No effect on non-HTTPS requests. Possible values include: 'EnforceCertificateNameCheckEnabledStateEnabled', 'EnforceCertificateNameCheckEnabledStateDisabled'
755 	EnforceCertificateNameCheck EnforceCertificateNameCheckEnabledState `json:"enforceCertificateNameCheck,omitempty"`
756 	// SendRecvTimeoutSeconds - Send and receive timeout on forwarding request to the backend. When timeout is reached, the request fails and returns.
757 	SendRecvTimeoutSeconds *int32 `json:"sendRecvTimeoutSeconds,omitempty"`
758 }
```
[SDK Link](https://github.com/Azure/azure-sdk-for-go/blob/c831e483e2058e9b2a8f9b4e35248f46f9516b4c/services/frontdoor/mgmt/2019-05-01/frontdoor/models.go#L752)

**Comment by BenMitchell1979** [comment]
Tagged for tracking..

**Comment by davidobrien1985** [comment]
@WodansSon do you have an idea when this will be done?

**Comment by schmid37** [comment]
@WodansSon any updates to this topic? It's pretty anoying to increase the timeout via the Azure CLI after a deployment.

**Comment by WodansSon** [comment]
@schmid37, yes this is currently on my plate and I will be getting to this soon... sorry for the delay.
