### ISSUE TITLE
NEW FeatureRequest: AzureFrontDoor redirection configuration

### ISSUE THREAD

**Issue by naikajah** [terraform-providers/terraform-provider-azurerm#4562]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Frontdoor allows redirection configuration to allow redirect http traffic to https via following
https://docs.microsoft.com/en-us/azure/frontdoor/front-door-how-to-redirect-https

However, it seems that currently terraform does not allow redirect configuration to be added in its config. It would be great to add a **redirecting_configuration** similar to what we have currently in **forwarding_configuration**

### New or Affected Resource(s)

* azurerm_frontdoor

### Potential Terraform Configuration

```hcl
resource "azurerm_frontdoor" "example" {
  name                                         = "example-FrontDoor"
  location                                     = "${azurerm_resource_group.example.location}"
  resource_group_name                          = "${azurerm_resource_group.example.name}"
  enforce_backend_pools_certificate_name_check = false

  routing_rule {
      name                    = "exampleRoutingRule1"
      accepted_protocols      = ["Http", "Https"]
      patterns_to_match       = ["/*"]
      frontend_endpoints      = ["exampleFrontendEndpoint1"]
      redirecting_configuration {
         redirect_type                = "302"
         redirect_protocol         = "HTTPSOnly"
      }
  }

  backend_pool_load_balancing {
    name = "exampleLoadBalancingSettings1"
  }

  backend_pool_health_probe {
    name = "exampleHealthProbeSetting1"
  }

  backend_pool {
      name            = "exampleBackendBing"
      backend {
          host_header = "www.bing.com"
          address     = "www.bing.com"
          http_port   = 80
          https_port  = 443
      }

      load_balancing_name = "exampleLoadBalancingSettings1"
      health_probe_name   = "exampleHealthProbeSetting1"
  }

  frontend_endpoint {
    name                              = "exampleFrontendEndpoint1"
    host_name                         = "example-FrontDoor.azurefd.net"
    custom_https_provisioning_enabled = false
  }
}
```

### References

* #0000

**Comment by WodansSon** [comment]
This is actually already supported and you can use it now. Looks like I just forgot to add it to the documentation. DOH! 🙃 

While I'm fixing the docs if you want to use it here are the attributes for the `redirect_configuration` block:
```
redirect_configuration {
  custom_host         = "www.contoso.com"                             # Required
  redirect_protocol   = "HTTPSOnly"                                   # Required : (HTTPOnly|HTTPSOnly|MatchRequest)
  redirect_type       = "Found"                                       # Required : (Moved(301)|Found(302)|TemporaryRedirect(307)|PermanentRedirect(308))
  custom_fragment     = "example-fragment"                            # Optional
  custom_path         = "redirected-path"                             # Optional
  custom_query_string = "&utm_referrer=https%3A%2F%2Fwww.bing.com%2F" # Optional
 }
```
