### ISSUE TITLE
Key Vault access denied when first created

### ISSUE THREAD

**Issue by ymash13** [terraform-providers/terraform-provider-azurerm#4569]
When Terraform first creates the Key vault and then tries to use it to encrypt disks, I get an error message about the user lacking access right. When I check, access permissions are there. When I run terraform apply a second time, with no changes, it works. Seems that there is a delay when access polices are applied to the vault?

Error: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied. Caller was not found on any access policy.\r\nCaller: appid=********;oid=***********c;numgroups=0;iss=https://sts.windows.net/*******/\r\nVault: AZ-GWC4-keyvault;location=germanywestcentral" InnerError={"code":"AccessDenied"}

**Comment by vivekkranjan** [comment]
I am getting the same error. Seems the caller is not added to Access Policy of key vault. I am running a powershell script through CI/CD pipeline to create key in key vault and getting this error.

**Comment by ausfestivus** [comment]
Ive been seeing similar problems lately building Azure Keyvaults from TF.

```shell
2 errors occurred:
	* module.tfe_cluster.module.common.azurerm_key_vault_certificate.ptfe: 1 error occurred:
	* azurerm_key_vault_certificate.ptfe: keyvault.BaseClient#ImportCertificate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied. Caller was not found on any access policy.\r\nCaller: appid=04b07795-8ddb-461a-bbee-02f9e1bf7b46;oid=731b021b-d6c0-41f7-b417-9874875730dc;numgroups=2;iss=https://sts.windows.net/a5aa424e-5d6f-47c9-bf70-a1310f4be302/\r\nVault: demoTFE;location=australiaeast" InnerError={"code":"AccessDenied"}

Ive referenced this issue from the another issue I opened in the TFE repo.
```

**Comment by govale** [comment]
Have the same issue. I created key vault with related access policies for particular object id and grant full permissions. Simultaneously in Azure Portal UI I can able to see app id with all permissions in access policies...

**Comment by edjwhho** [comment]
hi any solution to this problem?

**Comment by cmdplusr** [comment]
Still a problem fo me to 

```
Error: Error checking for presence of existing Key "foo" (Key Vault "https://foo-key-vault.vault.azure.net/"): keyvault.BaseClient#GetKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied. Caller was not found on any access policy.\r\nCaller: appid=12345...;numgroups=1;iss=https://sts.windows.net/...8775553090w/\r\nVault: foo-dev-key-vault;location=uksouth" InnerError={"code":"AccessDenied"}
```
Terraform v0.12.23
+ provider.azuread v0.8.0
+ provider.azurerm v2.1.0
+ provider.random v2.2.1

**Comment by chrisjohnson** [comment]
I'm seeing this issue. If there's a policy or permission that needs to be granted, it's not obvious what it is.

**Comment by tombuildsstuff** [comment]
hi @ymash13 

Thanks for opening this issue

The Azure Key Vault API's require that any callers are present in the Access Policies, as you've mentioned - however within Terraform you'll need to configure explicit dependencies between these resources, to ensure that the Access Policies exist prior to attempting to set the Secret (as in this case):

```
$ cat main.tf
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "tom-devrg3"
  location = "West Europe"
}

resource "azurerm_key_vault" "example" {
  name                = "tomdevkv3"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "premium"
}

resource "azurerm_key_vault_access_policy" "example" {
  key_vault_id = azurerm_key_vault.example.id

  tenant_id = data.azurerm_client_config.current.tenant_id
  object_id = data.azurerm_client_config.current.object_id

  secret_permissions = [
    "delete",
    "get",
    "set",
  ]
}

resource "azurerm_key_vault_secret" "example" {
  name         = "secret-sauce"
  value        = "szechuan"
  key_vault_id = azurerm_key_vault.example.id

  depends_on = [azurerm_key_vault_access_policy.example]
}
```

As such this should be fixed by ensuring that the KeyVault Certificate/Key/Secret is created after the Key Vault Access Policy has been applied - can you take a look and see if updating the configuration as shown above works for you? Since this should be fixed by introducing a dependency between these resources I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
