### ISSUE TITLE
conditional custom frontend endpoint host

### ISSUE THREAD

**Issue by rvashishth** [terraform-providers/terraform-provider-azurerm#4579]
### Description

Mostly, we all have a static jenkins pipeline. PR, Dev, Test, Stage, Prod.  In case of front door, it does create multiple *.azurefd.net domain. In order to successfully run the TF script for front door. A CNAME mapping between our domain name and front door default endpoint name has to be done in advance on our DNS providers. 

now the mortal environments like PR only live for minutes and we can't have a domain name CNAME mapping available for it. There might be other scenarios also where a resource creation is only required in certain environments. Like for AKS we may don't want to have a scaleset VMs for lower environments. 

### New or Affected Resource(s)

* azurerm_frontdoor
* others

### Potential Terraform Configuration

```hcl
resource "azurerm_frontdoor"  "localname" {
 frontend_endpoint {
// PR Env
 host_name = "pr-1.myhost.com"
}
 frontend_endpoint { 
// Test/Prod Env
host = "myhost.com"
}
}
```

### References
There are trick can be used with some resource types, but not all.  [use of count param to optionally create an aws autoscalling group](https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9#0223)

**Comment by rvashishth** [comment]
this control of conditionally creating should also be available for internal arguments. we might need an argument for one environment and may not need it for others. 

if there is such a solution available, please suggest.

**Comment by WodansSon** [comment]
@rvashishth, sorry for the delayed response and thank you for the question. Terraform already supports [conditional expressions](https://www.terraform.io/docs/configuration/expressions.html#conditional-expressions) would this work for your scenario?

**Comment by WodansSon** [comment]
@rvashishth, I am going to go ahead and close this issue as I believe I have answered your question. If my assumption is in error please feel free to reopen this issue and I will work with you to answer your question fully. Thanks again for reaching out! 🚀
