### ISSUE TITLE
Slack Workspace for Contributors Invite Link is Dead

### ISSUE THREAD

**Issue by ckittel** [terraform-providers/terraform-provider-azurerm#4583]
The [Slack Workspace for Contributors](https://terraform-azure.slack.com/) invite link in [`README.md`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/README.md) doesn't appear to be active anymore.  Could the slack admin (@bajorgensen ?), if appropriate, generate a new invite link and update the document?  Thanks!

cc: @robnotto

**Comment by katbyte** [comment]
Hi @ckittel,

Thank you for letting is know the link is dead! I just updated the readme with a new link: https://join.slack.com/t/terraform-azure/shared_invite/enQtNDMzNjQ5NzcxMDc3LWNiY2ZhNThhNDgzNmY0MTM0N2MwZjE4ZGU0MjcxYjUyMzRmN2E5NjZhZmQ0ZTA1OTExMGNjYzA4ZDkwZDYxNDE
