### ISSUE TITLE
Azure Windows VM Disk Encryption

### ISSUE THREAD

**Issue by gurjitsk** [terraform-providers/terraform-provider-azurerm#459]
Hi , 

Can someone help me with an example of Azure VM disk encryption on creation of VM and to enable disk encryption on the running VM ? 
IT has to use KEK so that Azure VM backups can work.
AS described here , https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption

**Comment by tombuildsstuff** [comment]
hi @gurjitsk 

Thanks for opening this issue - apologies for the delayed response here!

There's multiple issues open tracking support for encrypted disks in VM's - rather than having multiple issues tracking the same thing I'm going to close this in favour of #486.

Thanks!
