### ISSUE TITLE
Error: Error setting database threat detection policy

### ISSUE THREAD

**Issue by edisonmndza** [terraform-providers/terraform-provider-azurerm#4590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
- `Terraform: 0.12.1`
- `AzureRM Provider: 1.35.0`

### Affected Resource(s)

* `azurerm_sql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_sql_server" "xxxxxx" {
  name                         = var.prefix
  resource_group_name          = var.rg
  location                     = var.location
  version                      = "12.0"
  administrator_login          = "xxxxxx-admin"
  administrator_login_password = "xxxxxx"
}

resource "azurerm_sql_firewall_rule" "AllowAzureServices" {
  name                = "AllowAzureServices"
  resource_group_name = var.rg
  server_name         = azurerm_sql_server.xxxxxx.name
  start_ip_address    = "0.0.0.0"
  end_ip_address      = "0.0.0.0"
}

# PBMM SQL PaaS
resource "azurerm_sql_database" "xxxxxx-billing" {
  name                = "billing"
  resource_group_name = var.rg
  location            = var.location
  server_name         = azurerm_sql_server.xxxxxx.name
  edition             = "Standard"
  requested_service_objective_name     = "S1"

  collation           = "SQL_LATIN1_GENERAL_CP1_CI_AI"

  threat_detection_policy {
    state = "enabled"
    email_addresses = ["test@xxxxxx.ca"]
    retention_days = 90
    storage_account_access_key = azurerm_storage_account.xxxxxx.primary_access_key
    storage_endpoint = azurerm_storage_container.sql-server-logs.name
  }
}

resource "azurerm_storage_container" "sql-server-logs" {
  name                 = "sql-server-logs"
  storage_account_name = azurerm_storage_account.xxxxxx.name
}
```

### Expected Behavior

Successful build of sql paas resource with threat logs enabled with a retention day set to 90 days. 

### Actual Behavior

``` bash
Error: Error setting database threat detection policy: sql.DatabaseThreatDetectionPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=504 -- Original Error: autorest/azure: Service returned an error. Status=504 Code="GatewayTimeout" Message="The gateway did not receive a response from 'Microsoft.Sql' within the specified time period."
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @edisonmndza 

Thanks for opening this issue

Unfortunately this is an issue within the Azure API where the Internal API isn't responding to the Public Azure API within a designated time period - as such unfortunately there's not a lot we can do to work around this. If you retry this call this should work; but as this issue is intermittent I'm going to suggest opening an issue with Microsoft Support (which we'll do on our side too) - but for the moment I'm going to close this issue since this is an issue with the Azure API, rather than something specific to Terraform.

Thanks!
