### ISSUE TITLE
Event Hub Namespace keeps wanting to update kafka_enabled

### ISSUE THREAD

**Issue by mikhailshilkov** [terraform-providers/terraform-provider-azurerm#4598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.8                                                                                                                           + provider.azurerm v1.35.0
```

### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.35"
}

resource "azurerm_resource_group" "test" {
  name     = "resourceGroup1"
  location = "westeurope"
}

resource "azurerm_eventhub_namespace" "test" {
  name                = "blabla"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "Standard"
}
```
### Expected Behavior

A subsequent run of `terraform apply` suggests no changes.

### Actual Behavior

Terraform keeps suggesting replacements of the namespace on every `terraform apply` because it thinks that `kafka_enabled` has changed from `true` to `false`.

### Steps to Reproduce

1. Run `terraform apply` for the first time and complete the deployment.
2. Without changing anything, run `terraform apply` again.
3. Terraform suggests replacing the Event Hub Namespace:

```
  # azurerm_eventhub_namespace.test must be replaced
...
      ~ kafka_enabled                       = true -> false # forces replacement
```

Terraform state file has `"kafka_enabled": true,` even though the default value is supposed to be `false`.

Adding an explicit `kafka_enabled       = "false"` doesn't change anything.

### References

* https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace.html

**Comment by pather87** [comment]
It looks to me as if Azure now enables Kafka feature per default for all Standard tier instances and disables it for Basic tier instances. 
In that case we would need to deprecate it from the configuration

**Comment by mikhailshilkov** [comment]
@djrosanova Do you know?

**Comment by stack72** [comment]
@tombuildsstuff this looks like this isn't actually a value we can change:

<img width="1435" alt="Screenshot 2019-10-15 at 11 47 05" src="https://user-images.githubusercontent.com/227823/66815948-e1b29280-ef41-11e9-8326-6ce09c8f7dff.png">

This means we need to change this resource to not allow the value tgo be set. What's the protocol for this? Do we just move the parameter to be `Computed: true` and remove the ability to set it or do we need to add a deprecation message?
