### ISSUE TITLE
Azure VM Backups

### ISSUE THREAD

**Issue by gurjitsk** [terraform-providers/terraform-provider-azurerm#460]
Any example for Azure VM Backups please ?

**Comment by draggeta** [comment]
Hmm, I don't think they are available yet. Would be nice thought to automatically add vm's to backup.

**Comment by gurjitsk** [comment]
Any ETA on Azure Backups ? or can we use extensions of some sort ?

**Comment by tombuildsstuff** [comment]
Closing this in favour of #1143 which contains more details
