### ISSUE TITLE
azure role definition required parameter scope, defined as optional

### ISSUE THREAD

**Issue by vsamidurai** [terraform-providers/terraform-provider-azurerm#4603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version v0.12.10 
AzureRM v1.35.0

### Affected Resource(s)

* azurerm_role_definition

### Terraform Configuration Files

```hcl
data "azurerm_role_definition" "identity_role" {
  count = length(var.roles)
  name  = "${var.roles[count.index].role_name}"
}
```

### Debug Output
Error loading Role Definition List: could not find role 

### Expected Behavior
As per Azure API documentation, scope (scope of the role definition) required path parameter. But within AzureRM resource manager defined as optional parameters.

Change scope to required parameter for role_definition 

### Steps to Reproduce

1. `terraform plan`

### References
Azure API documentation link
https://docs.microsoft.com/en-us/rest/api/authorization/roledefinitions/list

Azure SDK
https://github.com/Azure/azure-sdk-for-go/blob/c831e483e2058e9b2a8f9b4e35248f46f9516b4c/services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go#L395

Terraform provider Azure
https://github.com/terraform-providers/terraform-provider-azurerm/blob/ec64e47dd08da26636d24c9c23a8b98365a66535/azurerm/data_source_role_definition.go#L41

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, seems `scope` could be not specified when retrieving builtin role like below this. So it's by design. Thanks.
```
provider "azurerm" {
  //features {}
  version = "1.35.0"
}

data "azurerm_role_definition" "test" {
  name = "Contributor"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if the solution suggested above doesn't work for you and we'll take another look.

Thanks!
