### ISSUE TITLE
`azurerm_function_app` - Add support for UserAssigned identity

### ISSUE THREAD

**Issue by JayDoubleu** [terraform-providers/terraform-provider-azurerm#4607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add support for UserAssigned identity for function apps.

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
  identity {
    type         = "UserAssigned"
    identity_ids = []
  }
```

### References

* #0000

**Comment by joakimhew** [comment]
I can look into this 👍

**Comment by JayDoubleu** [comment]
Is there any movement on this? I believe it already missed 2 releases. Is it likely to be merged for next one ?
