### ISSUE TITLE
Azure Web App deployment

### ISSUE THREAD

**Issue by gurjitsk** [terraform-providers/terraform-provider-azurerm#461]
Looking for support of Azure Web App deployments. Any pointers / timelines on status would be awesome.

**Comment by kevinneufeld** [comment]
You can already deploy a Web App; it is under 
`azurerm_app_service_plan` and `azure_app_service`, the docs are down at the moment.

**Comment by tombuildsstuff** [comment]
Hi @gurjitsk 

There's been several names for App Services over the years - "Azure Websites", "Azure Web Apps" and now "Azure App Service". As @kevinneufeld has mentioned, Terraform supports App Services via the [`azurerm_app_service_plan`](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html) (formerly "Server Farm") and [`azurerm_app_service`](https://www.terraform.io/docs/providers/azurerm/r/app_service.html) (formerly Web App) resources (which are linked in-line) :)

Thanks!

**Comment by gurjitsk** [comment]
Thanks Tom :)

Is there a full working example you can share for Web App ?

**Comment by tombuildsstuff** [comment]
@gurjitsk sure - [here's an example of how to deploy a .net 4.x application as an App Service within an App Service Plan](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#example-usage-net-4-x-) :)

Thanks!

**Comment by goel-shubh** [comment]
can you help me to deploy a website template from git through terraform on azure webapp
