### ISSUE TITLE
Batch Pool support for metadata

### ISSUE THREAD

**Issue by ThomasDekeyser** [terraform-providers/terraform-provider-azurerm#4611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It should be possible to set a metadata map on an existing "azurerm_batch_pool" resource.

### New or Affected Resource(s)

* azurerm_batch_pool

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* Metadata is supported by the GO SDK https://github.com/Azure/azure-sdk-for-go/blob/master/services/batch/2019-08-01.10.0/batch/models.go

**Comment by sergiupantiru** [comment]
Hello,
I've made an attempt to add the metadata tag on batch pools. 
If this is ok I will make a PR but don't know if I missed anything :)
Thanks!
