### ISSUE TITLE
[1.35.0] AKS sensitive information in plan output

### ISSUE THREAD

**Issue by EPinci** [terraform-providers/terraform-provider-azurerm#4621]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Running terraform 0.12.10 with AzureRM provider v1.35.0.

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Expected Behavior

When running a plan on an AKS cluster that requires an in-place update (such as a kubernetes version upgrade) the plan output shows the following excerpt:

```
        kube_admin_config               = [
            {
                client_certificate     = "[ACTUAL_CERTIFICATE_IS_SHOWN]"
                client_key             = "[ACTUAL_KEY_IS SHOWN]"
                cluster_ca_certificate = "[ACTUAL_CA_CERTIFICATE_IS_SHOWN]"
                host                   = "https://myhost-aaaaaaaa.hcp.westeurope.azmk8s.io:443"
                password               = "[ACTUAL_PASSWORD_IS_SHOWN]"
                username               = "clusterAdmin_myCluster"
            },
        ]
        kube_admin_config_raw           = (sensitive value)
        kube_config                     = [
            {
                client_certificate     = ""
                client_key             = ""
                cluster_ca_certificate = "[ACTUAL_CA_CERTIFICATE_IS_SHOWN]"
                host                   = "https://mycluster-aaaaaaaa.hcp.westeurope.azmk8s.io:443"
                password               = ""
                username               = "clusterUser_myCluster"
            },
        ]
        kube_config_raw                 = (sensitive value)
```

Note that the raw version of the data is considered sensitive and redacted while the parsed data, including keys and password to gain access to the cluster, are actually shown in clear while they should be considered sensitive and redacted as well.

At least the following fields should be marked sensitive:
- kube_admin_config.client_key
- kube_admin_config.password
- kube_config.client_key
- kube_config.password

Also, please evaluata if the following fields can be be somehow hidden from screen dump given long base64 encoded string don't necessarily provide a valuable output for the plan review.
- kube_admin_config.client_certificate
- kube_admin_config.cluster_ca_certificate
- kube_config.client_certificate
- kube_config.cluster_ca_certificate

### Important Factoids

* #0000

**Comment by yusmadi** [comment]
Hoping for a hot fix. This information is internally exposed in a production pipeline which is not nice to see.

**Comment by tombuildsstuff** [comment]
hi @EPinci @yusmadi 

Thanks for opening this issue.

Taking a look into this unfortunately this appears to be a bug in Terraform Core [which is being tracked in this issue](https://github.com/hashicorp/terraform/issues/23118) - since this'd be fixed in Terraform Core rather than within this Provider I'm going to close this in favour of the upstream issue https://github.com/hashicorp/terraform/issues/23118.

Thanks!
