### ISSUE TITLE
azurerm_automation_schedule fails when recurring. Interval options missing/non-importable

### ISSUE THREAD

**Issue by draggeta** [terraform-providers/terraform-provider-azurerm#463]
### Terraform Version
0.10.8

### Affected Resource(s)
- azurerm_automation_schedule

### Terraform Configuration Files
```hcl
resource "azurerm_automation_schedule" "schedule_prd_tas_admin_sync" {
  name                = "ProductionTOPdeskAdministratorsSync"
  resource_group_name = "${azurerm_automation_account.automation.resource_group_name}"
  account_name        = "${azurerm_automation_account.automation.name}"
  frequency           = "Hour"
  timezone            = "W. Europe Standard Time"
  start_time          = "2017-10-28T02:07:00+01:00"
  description         = "Automation schedule to start the synchronization of admin accounts to TAS servers."
}
```

### Debug Output
https://gist.github.com/draggeta/8af664cd5858f5093c982763e4f2bd27

### Expected Behavior
When reading/creating a recurring schedule , this should not fail. Also there are missing options such as days of week, weeks of months etc.

### Actual Behavior
Any time you try to perform a CRUD operation on a recurring schedule, you get an error regarding the frequency interval. This seems to be caused by the fact that it is an integer and json cannot unmarshal it to a string. Sadly, that is as far as my Go knowledge goes.

### Steps to Reproduce
Happens on the following:
1. `terraform apply`
2. `terraform plan`
3. `terraform import`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

**Comment by katbyte** [comment]
Hey @draggeta,

A fix to allow add the interval property and allow recurring schedules was released today as part of 1.7!
