### ISSUE TITLE
Support attach-acr for AKS cluster creation

### ISSUE THREAD

**Issue by jmcshane** [terraform-providers/terraform-provider-azurerm#4636]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support the flag `--attach-acr <ACR_ID>` for cluster authentication to ACR, this can be done for new & existing clusters, as well as be removed.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "aks" {

  acr_id = "........../Microsoft.ContainerRegistry/registries/myRegistry"
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration#create-a-new-aks-cluster-with-acr-integration

**Comment by bancek** [comment]
This is already possible as `attach-acr` only creates a role assignment:

```hcl
# Assign AcrPull role to service principal
resource "azurerm_role_assignment" "acrpull_role" {
  scope                            = "${data.azurerm_subscription.current.id}/resourceGroups/${var.resource_group_name}"
  role_definition_name             = "AcrPull"
  principal_id                     = "${azuread_service_principal.server.id}"
  skip_service_principal_aad_check = true
}
```

**Comment by tombuildsstuff** [comment]
👋 

Thanks for opening this issue.

As @bancek has mentioned it appears that AKS achieves this using a built-in Azure Role and as such it should be possible to achieve this using a Role Assignment ([as detailed in this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4636#issuecomment-547202836)) - as such I'm going to close this issue for the moment since I don't believe there's anything for Terraform to do here :)

Thanks!

**Comment by esHack** [comment]
If we use --attach-acr from az cli , we don't need to use any service principal.
But terraform requires a mandatory service pricipal to create AKS which not true anymore from az cli.

I think terraform needs to add support for that
