### ISSUE TITLE
azurerm_role_assignment failing to find aks service principal

### ISSUE THREAD

**Issue by benfrisbie** [terraform-providers/terraform-provider-azurerm#4651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.10
+ provider.azurerm v1.35.0

### Affected Resource(s)

* `azurerm_role_assignment`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.35"
}

terraform {
  required_version = ">= 0.12.10"

  required_providers {
    azurerm = ">= 1.35"
  }
}

data "azurerm_resource_group" "rg" {
  name = "dev-bfrisbie-rg"
}

data "azurerm_kubernetes_cluster" "aks" {
  name = "dev-bfrisbie-aks"
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azurerm_user_assigned_identity" "identity" {
  name = "managed-identity"
  resource_group_name = data.azurerm_resource_group.rg.name
}

output "managed_identity_id" {
  value = data.azurerm_user_assigned_identity.identity.id
}

output "aks_service_principal_id" {
  value = data.azurerm_kubernetes_cluster.aks.service_principal.0.client_id
}

resource "azurerm_role_assignment" "role-assignment" {
  scope = data.azurerm_user_assigned_identity.identity.id
  role_definition_name = "Managed Identity Operator"
  principal_id = data.azurerm_kubernetes_cluster.aks.service_principal.0.client_id
}
```

### Expected Behavior
The role assignment should be successfully created.

### Actual Behavior
The role assignment fails stating the service principal does not exist after waiting for 5 minutes.
Output:
```
azurerm_role_assignment.role-assignment: Creating...
azurerm_role_assignment.role-assignment: Still creating... [10s elapsed]
azurerm_role_assignment.role-assignment: Still creating... [20s elapsed]
...
azurerm_role_assignment.role-assignment: Still creating... [4m50s elapsed]
azurerm_role_assignment.role-assignment: Still creating... [5m0s elapsed]

Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx does not exist in the directory dddddddd-dddd-dddd-dddd-dddddddddddd."
```

The service principal does exist and can be confirmed by looking at the terraform output values or by running `az aks show -n dev-bfrisbie-aks -g dev-bfrisbie-rg --query servicePrincipalProfile.clientId` which returns something like this:
`"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"`

The major difference I see is that the service principal appears to have it's dashes removed in the azurerm_role_assignment error (`xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`), while the az command has the dashes (`xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`).

I've confirmed that the dashes are required when searching for a service principal.
`az ad sp show --id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` successfully returns the service principal.
`az ad sp show --id xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` does not find the service principal. It outputs:
```
Resource 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' does not exist or one of its queried reference-property objects are not present.
```

One final validation that the service principal does exist and the role assignment can be completed. If the following local-exec block replaces the azurerm_role_assignment block in the terraform configuration, the role assignment is created.
```
resource "null_resource" "null" {
  provisioner "local-exec" {
    command = "az role assignment create --role \"Managed Identity Operator\" --assignee ${data.azurerm_kubernetes_cluster.aks.service_principal.0.client_id} --scope ${data.azurerm_user_assigned_identity.identity.id}"
  }
}
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
This is related to enabling pod managed identities on AKS. Specifically, the role assignment is required for this step: https://github.com/Azure/aad-pod-identity/blob/master/README.md#6-set-permissions-for-mic

**Comment by amasover** [comment]
The config below is working for us to enable pod identities. I think your problem might be that the `client_id` that you're retrieving in `data.azurerm_kubernetes_cluster` is perhaps actually an application id/client id, not a service principal object id, which is what `azurerm_role_assignment` needs.

From the `data.azurerm_kubernetes_cluster` doc:

> A service_principal block supports the following:
> client_id - The Client ID of the Service Principal used by this Managed Kubernetes Cluster..

So what you're getting is a client id.

From the `azuread_service_principal` doc:

>The following attributes are exported:
> id - The Object ID (internal ID) for the Service Principal.
> application_id - The Application ID (appId) for the Service Principal.
> object_id - The Service Principal's Object ID.

Below, I'm passing in a `azured_service_principal.id` (an object id) into the `azurerm_role_assignment` `principal_id` field.

```terraform
resource "azuread_application" "system" {
  name = local.prefix_environment
}

resource "azuread_service_principal" "system" {
  application_id = azuread_application.system.application_id
}

resource "random_password" "client_secret" {
  length = 20
  special = true
  keepers = {
    service_principal = azuread_service_principal.system.id
  }
}

resource "azuread_application_password" "system" {
  application_object_id = azuread_application.system.object_id
  value = random_password.client_secret.result
  end_date_relative     = "17520h" #expire in 2 years
}

resource "azurerm_user_assigned_identity" "pod_identity" {
  resource_group_name = azurerm_resource_group.rg.name
  location = "westus2"
  name = "pod-identity"
}

resource "azurerm_role_assignment" "managed_identity_operator_k8s" {
  scope                 = azurerm_user_assigned_identity.pod_identity.id
  role_definition_name  = "Managed Identity Operator"
  principal_id          = azuread_service_principal.system.id
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name = "my-cool-k8s-cluster"
  location = "westus2"

  service_principal {
    client_id = azuread_application.system.application_id
    client_secret = azuread_application_password.system.value
  }
}
```

**Comment by benfrisbie** [comment]
@amasover Is correct. Thank you for your help!

Modifying my original terraform to this works successfully:
```hcl
provider "azurerm" {
  version = "~> 1.35"
}

terraform {
  required_version = ">= 0.12.10"

  required_providers {
    azurerm = ">= 1.35"
  }
}

data "azurerm_resource_group" "rg" {
  name = "dev-bfrisbie-rg"
}

data "azurerm_user_assigned_identity" "identity" {
  name = "managed-identity"
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azurerm_kubernetes_cluster" "aks" {
  name = "dev-bfrisbie-aks"
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azuread_service_principal" "aks" {
  application_id = data.azurerm_kubernetes_cluster.aks.service_principal.0.client_id
}

resource "azurerm_role_assignment" "role-assignment" {
  scope = data.azurerm_user_assigned_identity.identity.id
  role_definition_name = "Managed Identity Operator"
  principal_id = data.azuread_service_principal.aks.id
}
```
