### ISSUE TITLE
Error ControlPlaneAddOnsNotReady when creating azurerm_kubernetes_cluster with multiple node pools

### ISSUE THREAD

**Issue by bbenoist** [terraform-providers/terraform-provider-azurerm#4653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```txt
$ terraform -version
Terraform v0.12.11
+ provider.azurerm v1.32.1
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

#### `main.tf`

<details>

```hcl
# Used by to generate random identifiers when names could conflict.
provider "random" {
  version = "~>2.2.1"
}

provider "azurerm" {
  version = "~>1.32.0"
}
```

</details>

#### `variables.tf`

<details>

```hcl
variable "ssh_public_key" { }
variable "arm_client_id" { }
variable "arm_client_secret" { }
```
</details>

#### `azure.tf`

```hcl
resource "azurerm_resource_group" "test" {
  name = "test-resource-group"
  location = "westeurope"
}

resource "random_id" "log_analytics_workspace_id" {
  byte_length = 8
}

resource "azurerm_log_analytics_workspace" "test" {
  name = "test-${random_id.log_analytics_workspace_id.dec}"
  location = "westeurope"
  resource_group_name = azurerm_resource_group.test.name
  sku = "PerGB2018"
}

resource "azurerm_log_analytics_solution" "test" {
  solution_name = "ContainerInsights"
  location = azurerm_log_analytics_workspace.test.location
  resource_group_name = azurerm_resource_group.test.name
  workspace_resource_id = azurerm_log_analytics_workspace.test.id
  workspace_name = azurerm_log_analytics_workspace.test.name
  plan {
    publisher = "Microsoft"
    product = "OMSGallery/ContainerInsights"
  }
}

resource "azurerm_kubernetes_cluster" "test" {
  name = "test-cluster"
  location = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix = "test"
  kubernetes_version = "1.15.4"

  linux_profile {
    admin_username = "test"
    ssh_key {
      key_data = file(var.ssh_public_key)
    }
  }

  role_based_access_control {
    enabled = true
  }

  agent_pool_profile {
    name = "pool1"
    type = "VirtualMachineScaleSets"
    enable_auto_scaling = true
    min_count = 1
    max_count = 3
    count = 1
    max_pods = 30
    vm_size = "Standard_F16s_v2"
    os_type = "Linux"
    os_disk_size_gb = 30
    node_taints = ["sku=pool1:NoSchedule"]
  }

  agent_pool_profile {
    name = "pool2"
    type = "VirtualMachineScaleSets"
    enable_auto_scaling = true
    min_count = 1
    max_count = 1
    count = 1
    max_pods = 80
    vm_size = "Standard_DS1_v2"
    os_type = "Linux"
    os_disk_size_gb = 30
    node_taints = ["sku=pool2:NoSchedule"]
  }

  service_principal {
    client_id = var.arm_client_id
    client_secret = var.arm_client_secret
  }

  addon_profile {
    oms_agent {
      enabled = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.test.id
    }
    http_application_routing {
      enabled = false
    }
  }

  tags = {
    Environment = "Development"
  }
}
```

#### `output.tf`

<details>

```hcl
output "client_key" {
  value = azurerm_kubernetes_cluster.test.kube_config.0.client_key
}

output "client_certificate" {
  value = azurerm_kubernetes_cluster.test.kube_config.0.client_certificate
}

output "cluster_ca_certificate" {
  value = azurerm_kubernetes_cluster.test.kube_config.0.cluster_ca_certificate
}

output "cluster_username" {
  value = azurerm_kubernetes_cluster.test.kube_config.0.username
}

output "cluster_password" {
  value = azurerm_kubernetes_cluster.test.kube_config.0.password
}

output "kube_config" {
  value = azurerm_kubernetes_cluster.test.kube_config_raw
}

output "host" {
  value = azurerm_kubernetes_cluster.test.kube_config.0.host
}
```

</details>

### Debug Output

[🔗 Click here to see the debug output (GitHub Gist)](https://gist.github.com/bbenoist/b6d9de1fed36a04a6c443f9b0601d536)

### Panic Output

N/A

### Expected Behavior

The cluster should have been created and the 2 nodes should be ready.

### Actual Behavior

* Terminal:

    ```text
    Error: Error waiting for completion of Managed Kubernetes Cluster "test-kubernetes-cluster" (Resource Group "test-resource-group"): Code="ControlPlaneAddOnsNotReady" Message="Pods not in Running status: tunnelfront-65f9f6957d-j9pxd,coredns-68c85fc5d4-7rscv,coredns-autoscaler-77799d76ff-nspgg,kubernetes-dashboard-5758d48c87-8fvpk,metrics-server-67bd858859-g6kw4"
    ```

* Azure:

    ![image](https://user-images.githubusercontent.com/2091902/67105224-a5dd2e80-f1c8-11e9-814d-27dacb57c6b1.png)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by tombuildsstuff** [comment]
hi @bbenoist 

Thanks for opening this issue

Unfortunately this is a provisioning error in the Azure API where the Kubernetes Cluster hasn't finished provisioning within the specified time period - since this is a hard-timeout within the Azure API (rather than something specific to Terraform) unfortunately there's not a lot that we can do to work around this; as such I'm going to close this issue for the moment. In terms of resolving this issue if you see this you should be able to destroy/re-create the cluster - however I'd recommend opening an issue with Azure Support since this timeout may want to be increased on their side.

Thanks!

**Comment by bbenoist** [comment]
@tombuildsstuff 

Thanks for your quick answer!

> Unfortunately this is a provisioning error in the Azure API where the Kubernetes Cluster hasn't finished provisioning within the specified time period - since **this is a hard-timeout within the Azure API** (rather than something specific to Terraform)

😭

> unfortunately there's not a lot that we can do to work around this; as such I'm going to close this issue for the moment.

OK I understand. I'll try to let you know about updates from MS.

> In terms of resolving this issue if you see this you should be able to destroy/re-create the cluster - 

It doesn't seems to change anything. I've re-tried many times without any change. It keeps failing with the same error as-long as I declare more than 1 node pool.

> however I'd recommend opening an issue with Azure Support since this timeout may want to be increased on their side.

Agreed, I guess that's my only remaining option.
