### ISSUE TITLE
Managed Disk Destory not being removed from state

### ISSUE THREAD

**Issue by rfc791** [terraform-providers/terraform-provider-azurerm#4655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.10
+ provider.azurerm v1.35.0
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_managed_disk`
* `azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

Managed Disk module
```hcl
resource "azurerm_managed_disk" "disk" {
  name                 = var.name
  resource_group_name  = var.resource_group
  location             = var.location
  storage_account_type = var.account_type
  create_option        = "Empty"
  disk_size_gb         = var.disk_size
}

resource "azurerm_virtual_machine_data_disk_attachment" "disk" {
  managed_disk_id    = azurerm_managed_disk.disk.id
  virtual_machine_id = var.host_id
  lun                = var.lun
  caching            = var.caching
}
```
VM Module
```hcl
resource "azurerm_virtual_machine" "host" {
  name                             = var.host_name
  location                         = var.location
  resource_group_name              = var.resource_group
  vm_size                          = var.vmsize
  availability_set_id              = var.availability_set_id != "" ? var.availability_set_id : null
  network_interface_ids            = [azurerm_network_interface.vm-nic.id]
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = var.publisher
    offer     = var.offer
    sku       = var.sku
    version   = "latest"
  }

  storage_os_disk {
    name              = "${var.host_name}-osdisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = var.os_disk_type
    os_type           = "windows"
  }

  os_profile {
    computer_name  = var.host_name
    admin_username = var.adminusername
    admin_password = var.adminpassword
  }

  os_profile_windows_config {
    enable_automatic_upgrades = true
    provision_vm_agent        = true
    timezone                  = "Eastern Standard Time"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = merge(local.custom_tags, map("unconfigured", var.configuration))

  lifecycle {
    ignore_changes = [tags]
  }

}
```

### Debug Output

[Output](https://gist.github.com/rfc791/1e122440569b3b0c2327385b10e16421)
### Expected Behavior

The state file removes the reference to the managed disk.
### Actual Behavior

The state file sometimes (sometime it works and other times it does not) has the azurerm_managed_disk and azurerm_virtual_machine_data_disk_attachment left over.  The resource has been deleted.  Need to do a ```terraform state rm``` to recover.
### Steps to Reproduce

1. Remove the vm and managed disk
1. `terraform apply`

### References

* #0000

**Comment by rfc791** [comment]
Is anyone else experiencing this?  We are running into this daily and has become a sticking point for people.   I am wondering if it is something wrong on our side or is it a Microsoft API issue.

**Comment by ctrombet** [comment]
Hello,

I am facing something similar using a similar codebase.
Steps to reproduce:

1) I create a VM, a managed disk and a disk attachment
2) I manually destroy on the Azure GUI the virtual machine and its image disk.
3) I run again terraform apply.

What I would like to see here is that terraform should maintain its managed disk as it is (with my data inside), and just reprovision another VM and attach this new VM to the same disk (so actually changing the disk attachment resource)

**Comment by neil-yechenwei** [comment]
@rfc791 , thanks for opening this issue. After tested with below tfconfig and latest azurerm, seems I cannot repro this issue anymore. Maybe I missed something. Could you have a try below tfconfig to check if the issue still exists? Thanks.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-manageddisk-test02"
  location = "eastus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctvn-test02"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "internalsubnet-test02"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "test" {
  name                = "acctni-test02"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = azurerm_subnet.test.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "test" {
  name                            = "acctestvm-test02"
  resource_group_name             = azurerm_resource_group.test.name
  location                        = azurerm_resource_group.test.location
  size                            = "Standard_D2s_v3"
  admin_username                  = "admuioser"
  admin_password                  = "Password1631!"
  disable_password_authentication = false

  network_interface_ids = [
    azurerm_network_interface.test.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}

resource "azurerm_managed_disk" "test" {
  name                 = "test02-disk1"
  location             = azurerm_resource_group.test.location
  resource_group_name  = azurerm_resource_group.test.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "test" {
  managed_disk_id    = azurerm_managed_disk.test.id
  virtual_machine_id = azurerm_linux_virtual_machine.test.id
  lun                = "0"
  caching            = "None"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment - but please let us know if you're able to take a look at the comment above and confirm if this is still an issue and we'll take another look.

Thanks!
