### ISSUE TITLE
Using MSI with Azure DevOps Pipelines.

### ISSUE THREAD

**Issue by RussellMaycock** [terraform-providers/terraform-provider-azurerm#4668]
Hi,
This isn't an issue, more a question about your docs that I think needs work on.
The doc https://www.terraform.io/docs/providers/azurerm/auth/managed_service_identity.html
recommends using a managed service identity with azure pipelines. The doc is very poor at getting across the terraform code needs to be ran from inside the VM you create. The doc suggests using MSI if you are using CI/CD pipelines, but doesn't explain how that is possible. 

If you create a VM in Azure and enable system-assigned identity, add the ID to the RBAC contributor role, add to the subscription. Then how do I run the scripts from the VM, in the pipelines? Surely I would have to login to the VM and run them from there. So how do I setup the pipelines, so it copies the scripts over to the VM and then runs them? 

Can you explain how this works in azure pipelines, please?

**Comment by KatteKwaad** [comment]
Also find the documentation regarding MSIs to be lackluster.

**Comment by yuri-tieto** [comment]
@RussellMaycock you can add your VM to Azure Devops Agent Pool as self hosted agent and in that case you can use Terraform Azure DevOps plugin to run terraform tasks on your VM which will be used as a resource deployer within subscription utilising managed identity - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser

**Comment by manojbale34** [comment]
With the self hosted agent installed in the VM ( enabled system-assigned identity), we are facing an issue with the terraform initialization with the below error.

Error: Error inspecting states in the "azurerm" backend:
Error retrieving keys for Storage Account "****": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/***/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/***/listKeys?api-version=2016-01-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'null' was not found in the directory '***'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by tombuildsstuff** [comment]
👋 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
