### ISSUE TITLE
azurerm_frontdoor resource does not support redirects

### ISSUE THREAD

**Issue by epvanhouten** [terraform-providers/terraform-provider-azurerm#4669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is currently not a way to configured a redirect in the azurerm_frontdoor resource.

### New or Affected Resource(s)

* azurerm_frontdoor

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_frontdoor" "example" {
  routing_rule {
    redirect_configuration {
      redirect_type = <"Found" | "Moved" | "TemporaryRedirect" | "PermanentRedirect">
      redirect_protocol = <"Http" | "Https" | "MatchRequest">
      destination_host {
        action = <"Preserve" | "Replace">
        replacement = [string]
      }
      destination_path {
        action = <"Preserve" | "Replace">
        replacement = [string]
      }
      query_string {
        action = <"Preserve" | "Replace">
        replacement = [string]
      }
      destination_fragment = [string]
    }
  }
}
```

### References

* [MSDN for az network front-door routing-rule create][1]

[1]: https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest#ext-front-door-az-network-front-door-routing-rule-create

**Comment by WodansSon** [comment]
This is already supported by the Front Door resource... see resource [documentation](https://www.terraform.io/docs/providers/azurerm/r/front_door.html#redirect_configuration)
