### ISSUE TITLE
azurerm_storage_account no longer syncs network_rules from > 1.33 

### ISSUE THREAD

**Issue by davidchua** [terraform-providers/terraform-provider-azurerm#4677]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`azurerm > 1.32.0`
`terraform v0.11.14`

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
  resource "azurerm_storage_account" "x" {
    name                      = "x"
    resource_group_name       = "${azurerm_resource_group.rg-qa-data-x.name}"
    location                  = "${azurerm_resource_group.rg-qa-data-x.location}"
    account_tier              = "Standard"
    account_kind              = "StorageV2"
    account_replication_type  = "LRS"
    enable_https_traffic_only = "True"


    network_rules {
      default_action = "Deny"
      virtual_network_subnet_ids = [
        <REDACTED>,
      ]
      bypass = ["Logging", "Metrics", "AzureServices"]
    }

    tags {
      env     = "qa"
      app     = "blobstorage"
      project = "x"
    }
  }
```

### Expected Behavior

When removing the `network_rules` block, and terraform plan, terraform should show a change to remove `network_rules` 

### Actual Behavior

Instead, no change is detected even though the network_rules is removed. Remote state also shows no change.

When downgrading to `azurerm 1.32`, the block is removed as expected

### Steps to Reproduce

1. remove the `network_rules` block
2. terraform plan & apply

**Comment by rk-tbrigley** [comment]
This looks like the azurerm storage account vnet/subnet network_rule issue is still happening and this is another use case hitting it.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/3156

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume it's by design. If you want to remove `network_rules`, please set  `default_action` of `network_rules` to `Allow`.
