### ISSUE TITLE
Azure function deployment slot

### ISSUE THREAD

**Issue by jbellmore** [terraform-providers/terraform-provider-azurerm#4684]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello!

I am trying to create an azure function with a deployment slot using Terraform and the azure provider. I am able to successfully create the app service plan and the azure function, however I can not seem to create the deployment slot no matter what I try. I am hoping this is supported and I am just missing something!

Thanks!

### Terraform (and AzureRM Provider) Version
Terraform v0.12.11
provider.azurerm v1.35.0

### Affected Resource(s)

* `azurerm_app_service_slot`

### Terraform Configuration Files
The terraform is using a module, included is the main.tf of the main repo and also the main.tf of the module:

Main repo:
```hcl
# Configure state to be stored remotely in terraform cloud
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "redacted"

    workspaces {
      prefix = "account-infrastructure-"
    }
  }
}

# Configure the Azure Provider
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "=1.35.0"
}

locals {
  app_name = "account"
}

data "azurerm_client_config" "main" {}

# Create a resource group
resource "azurerm_resource_group" "resource_group" {
  name     = "${local.app_name}-${terraform.workspace}"
  location = "Central US"
}

module "azurefunction" {
  source = "../Terraform.Module.AzureFunction"
  storage_account_name = "${local.app_name}${terraform.workspace}"
  app_service_plan_name = "${local.app_name}-${terraform.workspace}"
  function_name = "${local.app_name}-${terraform.workspace}"
  resource_group = azurerm_resource_group.resource_group
  azure_tenant_id = "${data.azurerm_client_config.main.tenant_id}"
  vault_name = "${local.app_name}-${terraform.workspace}"
}
```

Module:
```hcl
# Configure state to be stored remotely in terraform cloud
# Configure the Azure Provider
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "=1.35.0"
}

resource "azurerm_storage_account" "storage_account" {
  name                     = "${var.storage_account_name}"
  resource_group_name      = "${var.resource_group.name}"
  location                 = "${var.resource_group.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "app_service_plan" {
  name                = "${var.app_service_plan_name}"
  location            = "${var.resource_group.location}"
  resource_group_name = "${var.resource_group.name}"
  kind                = "FunctionApp"

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "function" {
    name                      = "${var.function_name}"
    location                  = "${var.resource_group.location}"
    resource_group_name       = "${var.resource_group.name}"
    app_service_plan_id       = "${azurerm_app_service_plan.app_service_plan.id}"
    storage_connection_string = "${azurerm_storage_account.storage_account.primary_connection_string}"
    version                   = "~2"

    identity {
        type = "SystemAssigned"
    }

    app_settings = {
        FUNCTIONS_WORKER_RUNTIME = "dotnet"
        FUNCTIONS_EXTENSION_VERSION = "~2"
        WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = "${azurerm_storage_account.storage_account.primary_connection_string}"
    }
}

resource "azurerm_app_service_slot" "staging_slot" {
    name                = "staging"
    location            = "${var.resource_group.location}"
    resource_group_name = "${var.resource_group.name}"
    app_service_plan_id = "${azurerm_app_service_plan.app_service_plan.id}"
    app_service_name    = "${azurerm_function_app.function.name}"

    app_settings = {
        WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = "${azurerm_storage_account.storage_account.primary_connection_string}"
    }
}

```

### Expected Behavior

New azure function should have been created with a deployment slot called "staging"

### Actual Behavior
```
Error: Error creating Slot "staging" (App Service "account-staging" / Resource Group "account-staging"): web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string." Details=[{"Message":"Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"04122","Message":"Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string.","MessageTemplate":"Function App app settings are not expected to be empty. Please try again with {0} as a storage account connection string.","Parameters":["WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"]}}]
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I initially tried this without the app_settings block, but when the error indicated I needed the app_settings block I added it to both the main function as well as the deployment slot. I have tried with those values in both resources, without them in either and with them in one but not the other. Every way I tried I get the same error.

**Comment by haodeon** [comment]
I've discovered a workaround which isn't the best but does allow terraform to manage the slot.

Create the slot with az CLI and then import the slot as an azurerm_app_service_slot resource.

You will need to also add in all the app_settings the slot has from being created with az CLI.

**Comment by tombuildsstuff** [comment]
hey @jbellmore 

Thanks for opening this issue - apologies for the delayed response here!

At this time there isn't a specific resource for Function App Slots (support for this is being tracked in #1307) - however as many folks have noticed they're structurally similar to App Service Slots and thus it's possible to reuse them in some cases. There's several App Settings which are a requirement for a Function App (which the Portal/CLI will deploy for you) which must be specified to successfully provision this - in the case of the `azurerm_function_app` resource we automatically set some of these for you (and omit them from the response) to differentiate App Settings from these other configuration values.

Whilst we'd like to natively support the Function App Slot resource unfortunately it's not something we've got to yet - that said there's an existing issue open tracking support for this in (#1307) - as such rather than having multiple issues tracking the same thing would you mind subscribing to #1307 for updates?

Thanks!
