### ISSUE TITLE
private_dns_zone does not support PTR records

### ISSUE THREAD

**Issue by cwebbtw** [terraform-providers/terraform-provider-azurerm#4691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.10
AzureRM provider: 1.34.0

### Affected Resource(s)

* `azurerm_private_dns_zone`

### Expected Behavior

Can create PTR records in private dns zone.

### Actual Behavior

I can create a DNS zone with a private zone type, which is deprecated and gives deprecated warnings, however if I create a private DNS zone, then ptr record are not supported.

* #0000

**Comment by cwebbtw** [comment]
@tombuildsstuff This can be closed now, given the merge of #4703 - happy to close the issue if you're ok with that.

**Comment by tombuildsstuff** [comment]
@cwebbtw thanks for the ping - sounds good to me 👍
