### ISSUE TITLE
Unable to check OAuth 2.0 security option under API Settings

### ISSUE THREAD

**Issue by kundan123456** [terraform-providers/terraform-provider-azurerm#4693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.5
provider.azurerm v1.35.0

### Affected Resource(s)

* `azurerm_api_management_api`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "test" {
  name                = "example-api"
  resource_group_name = "${azurerm_resource_group.test.name}"
  api_management_name = "${azurerm_api_management.test.name}"
  revision            = "1"
  display_name        = "Example API"
  path                = "example"
  protocols           = ["https"]

  import {
    content_format = "swagger-link-json"
    content_value  = "http://conferenceapi.azurewebsites.net/?format=json"
  }
}
```

### Expected Behavior
![image](https://user-images.githubusercontent.com/17154776/67394806-76606480-f5c2-11e9-9107-ec274a296a3f.png)

### Actual Behavior
After creation it is checking None option, how can I check oauth2.0 option ?

![image](https://user-images.githubusercontent.com/17154776/67394892-9728ba00-f5c2-11e9-99df-84ad966157e4.png)

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References

* #0000

**Comment by Singley** [comment]
This is also a big issue for me- there appears to be no option for setting the User Authorization option on this resource.  For reference, it appears to this option from the [ARM template for APIM](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/apis): 

![image](https://user-images.githubusercontent.com/29473162/67984507-e4291380-fbf4-11e9-921f-ba26d412dd61.png)

(On a side note- but maybe related- when you generate the ARM template from Azure, it also seems to exclude this block - took me a long time to find what I was actually looking for here).

**Comment by tombuildsstuff** [comment]
hi @kundan123456 

Thanks for opening this issue :)

As @Singley has mentioned this appears to be a duplicate of #3341 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3341 for updates?

Thanks!
