### ISSUE TITLE
azurerm_virtual_network_gateway_connection routing_weight must be 1..1000 but azure support having a routing_weight of 0

### ISSUE THREAD

**Issue by josibb** [terraform-providers/terraform-provider-azurerm#4698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

i'm trying to configure a routing_weight of 0 in an express-route connection, but terraform validation fails because its not within the allowed 1..1000 range.
I can configure a routing_weight of 0 in azure without using terraform. 
terraform should support setting the value to 0.

Thanks

**Affected Resource(s)**
azurerm_virtual_network_gateway_connection

**Terraform (and AzureRM Provider) Version**
Terraform v0.12.11
provider.azurerm v1.35.0

**Comment by tombuildsstuff** [comment]
Fixed via #4849 - thanks @SebRosander :)
