### ISSUE TITLE
Independently able to add Azure frontdoor configurations

### ISSUE THREAD

**Issue by naikajah** [terraform-providers/terraform-provider-azurerm#4699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At present everything for the Azure front door needs to be configured in the same resource block as stated in the docs below
https://www.terraform.io/docs/providers/azurerm/r/front_door.html

This makes the resource block huge when configuring more frontends. e.g.

In my scenario, I have approx 30-35 frontend hosts to be configured in FrontDoor. 
These frontends then route traffic to different backends (Azure Firewall or Palo Alto VMs) in different regions depending on the URL pattern specified in the routing rule.

This can also be managed by dynamic blocks but might end up having a complex data structure.

It would be nice to have a separate resource for each frontend, backend and routing rule which can enable configurations to be added independently to the Azure front door service.

### New or Affected Resource(s)

New resource to be added:

* azurerm_frontdoor_ frontend_endpoint
* azurerm_frontdoor_backend_pool
* azurerm_frontdoor_routing_rule

### Potential Terraform Configuration

```
Once the Azure Frontdoor has been created with the default configuration as mentioned in the example below i.e. 
https://www.terraform.io/docs/providers/azurerm/r/front_door.html

Then custom configurations can be done via:

resource "azurerm_frontdoor_ frontend_endpoint" "frontend_endpoint" {
  frontdoor_id                                         = azurerm_frontdoor.example.id
  name                                                    = "customFrontend1"
  host_name                                           = "example-FrontDoor.azurefd.net"
  custom_https_provisioning_enabled = false
}

resource "azurerm_frontdoor_backend_pool" "backend_pool {
  frontdoor_id = azurerm_frontdoor.example.id
   name            = "exampleBackendCustom"
      backend {
          host_header = "www.example.com"
          address        = "www.example.com"
          http_port      = 80
          https_port    = 443
      }

      load_balancing_name = "exampleLoadBalancingSettings1"
      health_probe_name   = "exampleHealthProbeSetting1"
}

resource "azurerm_frontdoor_routing_rule" "routing_rule {
  frontdoor_id              = azurerm_frontdoor.example.id
  frontend_endpoint    = azurerm_frontdoor_ frontend_endpoint.custom.id
  accepted_protocols = ["Http", "Https"]
  patterns_to_match   = ["/*"]

  forwarding_configuration {
        forwarding_protocol = "MatchRequest"
        backend_pool_name = azurerm_frontdoor_backend_pool.backend_pool.name
      }
}

```

### References

* #0000

**Comment by WodansSon** [comment]
@naikajah thanks for opening this and I originally started to create this resource I did attempt to structure it as above, but due to the way the API is designed this is not possible. You have to send all of the configuration data to the API and then it builds all of the different components behind the scenes.
