### ISSUE TITLE
Azure private-link resource creation via terraform?

### ISSUE THREAD

**Issue by shankarsundaram** [terraform-providers/terraform-provider-azurerm#4701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

when the azure private-link feature will be available in terraform?
More details about private-link is here, 
https://docs.microsoft.com/en-us/azure/private-link/private-link-overview

**Comment by mybayern1974** [comment]
For private link service: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4426
For private endpoint: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4493

**Comment by mb139h** [comment]
There is inconsistency with this implementation. Specifically, the same subnet can be used for both private link endpoint and private link service. The terraform validation as of now is failing stating:
