### ISSUE TITLE
azurerm_key_vault_secret cannot use keyvault from another subscription within the same tenancy

### ISSUE THREAD

**Issue by bikramgcnz** [terraform-providers/terraform-provider-azurerm#4702]
We are trying to access keyvault located in another subscription within the same tenancy, but after a recent update, vault_uri parameter has been removed that means we can no longer access keyvault secret from a uri.

We need to specify key_vault_id  but this doesn't work as expected because key vault won't be in the subscription its looking for. Either vault_uri needs to be re-added or a new parameter needs to be introduced to specify subscription_id, so the engine knows its from a different subscription.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by laughtonsm** [comment]
Hi.

You can actually create multiple `provider` blocks and alias a subscription:

```
provider "azurerm" {
  alias  = "keyvaultsub"
  subscription_id = "<other_subscription_id>"
}
```

Then try in your `azurerm_key_vault_secret` data source, reference the alternate provider with  `provider = "keyvaultsub"`

**Comment by bikramgcnz** [comment]
thanks @laughtonsm  this works great :)
