### ISSUE TITLE
azurerm_key_vault_key resource does not return the URI of a created Key

### ISSUE THREAD

**Issue by laughtonsm** [terraform-providers/terraform-provider-azurerm#4708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_key_vault_key resource does not return the URI of a created Key.  This makes it difficult to reference elsewhere in Terraform, example in BitLocker/Azure Disk Encryption scenarios

### New or Affected Resource(s)

* azurerm_key_vault_key

### Potential Terraform Configuration

No potential configuration changes, just for the output attributes to be as follows:

id - The Key Vault Key ID.
key_uri - The Key Vaul Key URI **NEW ATTRIBUTE**
version - The current version of the Key Vault Key.
n - The RSA modulus of this Key Vault Key.
e - The RSA public exponent of this Key Vault Key.
x - The EC X component of this Key Vault Key.
y - The EC Y component of this Key Vault Key.

### References

* #0000

**Comment by neil-yechenwei** [comment]
@laughtonsm , thanks for opening this issue. May I ask what is key_uri you mentioned referring? Could you share an example of key_uri?

**Comment by jackofallops** [comment]
Closing as has been in waiting-response for over a month.

Additionally, the `id` of a key resource is a complete HTTPS reference to the key which can be combined with the `version` to reference a particular version if required.
