### ISSUE TITLE
Feature Request: Support for AKS/managed Kubernetes

### ISSUE THREAD

**Issue by carlpett** [terraform-providers/terraform-provider-azurerm#471]
As of last week, Azure has a new Container Service, AKS: https://azure.microsoft.com/en-us/blog/introducing-azure-container-service-aks-managed-kubernetes-and-azure-container-registry-geo-replication/.

This would be a very nice thing to be able to manage with Terraform!

**Comment by koalalorenzo** [comment]
Do we have an ETA for this?

**Comment by moritzheiber** [comment]
Short update: AKS support is now available [in the latest golang SDK release](https://github.com/Azure/azure-sdk-for-go/releases/tag/v12.0.0-beta).

**Comment by tombuildsstuff** [comment]
👋 hey all

As @moritzheiber has pointed out - support for AKS is now in the latest release of the Azure SDK for Go (which we're planning on upgrading to this month). Once we've upgraded to the new version of the SDK, we should be able to add support for this resource :)

Thanks!
