### ISSUE TITLE
azurerm_logic_app_workflow parameters argument always throws error

### ISSUE THREAD

**Issue by JunyiYi** [terraform-providers/terraform-provider-azurerm#4731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.12
+ provider.azurerm v1.35.0
```

### Affected Resource(s)

* `azurerm_logic_app_workflow`

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_workflow" "main" {
  name                = "my-test-logic-app"
  location            = "West US 2"
  resource_group_name = "Some-Existing-RG"

  parameters = {
    "noidea" = "justtest"
  }
}
```

### Debug Output

```
Error: Error updating Logic App Workspace "my-test-logic-app" (Resource Group "Some-Existing-RG"): logic.WorkflowsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="The template validation failed: 'The workflow parameters 'noidea' are not valid; they are not declared in the definition and therefore cannot be provided. The only declared parameters for this definition are ''.'."
```

### Expected Behavior

Maybe we can remove `parameters` from this resource, and let other sub-resources (e.g. `azurerm_logic_app_trigger_http_request`) handle it. The sub-resource will provide the `definition` body together with the `parameters` as required by Azure API.

### Actual Behavior

We are not able to provision the logic workflow (logic app) resource.

Actually the `parameters` schema definition is also not correct, it could be any object instead of a simple string. For example, a teams connector parameter should be defined as:

```
"parameters": {
    "$connections": {
        "value": {
            "teams": {
                "connectionId": "...",
                "connectionName": "teams",
                "id": "..."
            }
        }
    }
},
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @JunyiYi 

Thanks for opening this issue

Support for Connections is being tracked in #1691 - rather than having multiple issues open I'm going to close this issue in favour of that one - would you mind subscribing to that one for updates?

Thanks!
