### ISSUE TITLE
azurerm_subnet_network_security_group_association for Databricks adds and then removes association on repeated runs

### ISSUE THREAD

**Issue by eliasvakkuri** [terraform-providers/terraform-provider-azurerm#4736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.12
+ provider.azurerm v1.35.0

### Affected Resource(s)

azurerm_subnet_network_security_group_association

### Terraform Configuration Files

```hcl
terraform {}

provider "azurerm" {
  version = "= 1.35.0"
}

resource "azurerm_resource_group" "networks_rg" {
  name     = "networksrg"
  location = "westeurope"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "testvnet"
  resource_group_name = azurerm_resource_group.networks_rg.name
  location            = azurerm_resource_group.networks_rg.location
  address_space       =["10.0.0.0/16"]
}

resource "azurerm_network_security_group" "databricks_nsg" {
  name                = "testnsg"
  location            =  azurerm_resource_group.networks_rg.location
  resource_group_name = azurerm_resource_group.networks_rg.name

  security_rule {
    name                       = "databricks-worker-to-worker-inbound"
    description                = "Required for worker nodes communication within a cluster."
    priority                   = 200
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_address_prefix      = "VirtualNetwork"
    source_port_range          = "*"
    destination_address_prefix = "*"
    destination_port_range     = "*"
  }
}

resource "azurerm_subnet" "subnet_landing_databricks_public" {
  name                      = "databricks-public"
  resource_group_name       = azurerm_resource_group.networks_rg.name
  virtual_network_name      = azurerm_virtual_network.vnet.name
  address_prefix            = "10.0.0.0/24"
  service_endpoints         = ["Microsoft.Storage", "Microsoft.KeyVault"]

  delegation {
    name = "databricks-del-public"

    service_delegation {
      name = "Microsoft.Databricks/workspaces"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
        "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"
      ]
    }
  }
}

resource "azurerm_subnet_network_security_group_association" "landing_databricks_public_subnet_association" {
  subnet_id                 = azurerm_subnet.subnet_landing_databricks_public.id
  network_security_group_id = azurerm_network_security_group.databricks_nsg.id
}
```

### Debug Output

https://gist.github.com/eliasvakkuri/18d55cd45729d9b6e8540fa2d459f8eb

### Expected Behavior

The NSG association should remain as-is after the 2nd apply, as indicated by the Terraform plan

### Actual Behavior

1. 1st apply: NSG-subnet association is added
1. 2nd apply: association is removed, without any indication in TF plan
1. 3rd apply: association is in plan as to be added
1. (repeat)

### Steps to Reproduce

1. `terraform apply` --> add association, shown in plan
1. `terraform apply` --> remove association, no mention in plan
1. `terraform apply` --> add association, shown in plan

And so on.  

### Important Factoids

Normal Azure

**Comment by tombuildsstuff** [comment]
hi @eliasvakkuri 

Thanks for opening this issue :)

Unfortunately at this time the association between the Subnet and the Network Security Group needs to be specified in both the `azurerm_subnet` and the `azurerm_subnet_network_security_group_association` resource, this is to ensure this isn't a breaking change. We plan to change this behaviour in version 2.0 of the Provider, such that this will only need to be set on the `azurerm_subnet_network_security_group_association ` resource (and the `network_security_group_id` field on the `azurerm_subnet` field will be removed); however as mentioned above unfortunately prior to 2.0 this needs to be specified in both resources, as such this is noted in the documentation:

> NOTE: Subnet <-> Network Security Group associations currently need to be configured on both this resource and using the network_security_group_id field on the azurerm_subnet resource. The next major version of the AzureRM Provider (2.0) will remove the network_security_group_id field from the azurerm_subnet resource such that this resource is used to link resources in future.

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by eliasvakkuri** [comment]
Hi @tombuildsstuff , thank you for the comment! I seem to have missed the note in the documentation. For the time being I can indeed proceed with setting the property in both places.

**Comment by eliasvakkuri** [comment]
If possible, you might add that note also to the deprecation warning that comes when you use the  subnet property:

Warning: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.
