### ISSUE TITLE
private_dns_zone does not support SRV records

### ISSUE THREAD

**Issue by alainvanhoof** [terraform-providers/terraform-provider-azurerm#4739]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

private_dns_zone does not support SRV records

### New or Affected Resource(s)

Terraform v0.12.12
provider.azurerm v1.35.0

### Potential Terraform Configuration

azurerm_private_dns_zone

### Expected Behavior

Can create SRV records in private DNS zone.

### Actual Behavior

I can create a DNS zone with a private zone type, which is deprecated and gives deprecated warnings, however if I create a private DNS zone, then SRV record are not supported.

**Comment by phires** [comment]
I'm currently looking into implementing all the missing types to the private dns zones, will create a pull request sometime next week.

**Comment by katbyte** [comment]
fixed by #4783###
