### ISSUE TITLE
azurerm_template_deployment fails when template_body and parameters body are unknown until apply

### ISSUE THREAD

**Issue by arodriguezdlc** [terraform-providers/terraform-provider-azurerm#4745]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.8
+ provider.azurerm v1.35.0

### Affected Resource(s)

* `azurerm_template_deployment`

### Terraform Configuration Files

```hcl
data "local_file" "aks_rm_template" {
  depends_on = [ null_resource.aks_engine_generate ]
  filename = local.aks_rm_parameters_path
}

data "local_file" "aks_rm_parameters" {
  depends_on = [ null_resource.aks_engine_generate ]
  filename = local.aks_rm_parameters_path
}

resource "azurerm_template_deployment" "aks_engine" {
  name                = "aks-engine"
  resource_group_name = azurerm_resource_group.rg.name

  template_body = data.local_file.aks_rm_template.content
  parameters_body = data.local_file.aks_rm_parameters.content

  deployment_mode = "Incremental"
}
```

### Debug Output

```
azurerm_template_deployment.aks_engine: Creating...

Error: Error creating deployment: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Could not find member 'agentSubnet' on object of type 'Template'. Path 'properties.template.agentSubnet', line 1, position 41.'."

  on aks_engine.tf line 69, in resource "azurerm_template_deployment" "aks_engine":
  69: resource "azurerm_template_deployment" "aks_engine" {
```

### Expected Behavior

Resource should use `template_body` and `parameters_body` from file datasource without problems. 

### Actual Behavior

It seems like the resource don't use correctly the `parameters_body` property if terraform doesn't know at plan time what is the template_body. If `file` function is used instead of `data "local_file"`, it works. However we can't do that because we need to read the file after is created by a provider. 

Plan shows correctly that `template_body` and `parameters_body` will be known after apply:
```
# azurerm_template_deployment.aks_engine will be created
  + resource "azurerm_template_deployment" "aks_engine" {
      + deployment_mode     = "Incremental"
      + id                  = (known after apply)
      + name                = "aks-engine"
      + outputs             = (known after apply)
      + parameters_body     = (known after apply)
      + resource_group_name = "baikal-alberto-terraform-rg"
      + template_body       = (known after apply)
    }
```

I think that the problem is that `azurerm_template_deployment` is trying to process parameters before have loaded the `template_body`. 

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @arodriguezdlc 

Thanks for opening this issue.

Taking a look into the error being returned from Azure here:

```
Could not find member 'agentSubnet' on object of type 'Template'. Path 'properties.template.agentSubnet', line 1, position 41.'
```

It appears that the property `agentSubnet` is missing from the ARM Template itself (which it appears is generated from the Azure/aks-engine project?) - as such the ARM Template is invalid, which is why this is failing.

If you're able to confirm that the ARM Template is valid (for example, using the Azure CLI) and are having issues specifically within Terraform, would you be able to provide the ARM Template (and some placeholder parameters) for us to take a deeper look? For the moment since this appears to be a configuration questionrather than a bug in the Azure Provider I'm going to close this issue, but please let us know if updating the ARM Template to be valid doesn't work and we'll take another look.

Thanks!

**Comment by arodriguezdlc** [comment]
No, template is valid because if I load it using `file` function, it works. Only fails if I read it using `local_file` datasource.

**Comment by arodriguezdlc** [comment]
Could you reopen the issue please? Thanks :)
