### ISSUE TITLE
New Resource: azurerm_api_management_policy

### ISSUE THREAD

**Issue by molinch** [terraform-providers/terraform-provider-azurerm#4758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There was a PR about adding a new resource: azurerm_api_management_policy
https://github.com/terraform-providers/terraform-provider-azurerm/pull/3145

In fact the policy should be a separate resource for a good reason. The policy can include the certificate thumbprint. So since the certificate is a separate resource, with terraform you cannot create yet, a policy that uses that thumbprint. The flow in this case should be:

1. Create api management
2. Create certificate
3. Create api management policy that uses the certificate

### New or Affected Resource(s)

- existing affected: azurerm_api_management
- new: azurerm_api_management_policy

### Potential Terraform Configuration

See previous PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/3145

**Comment by brunhil** [comment]
@molinch , for step 2 could you use [api_management_certificate](https://www.terraform.io/docs/providers/azurerm/r/api_management_certificate.html) to house the certificate in the API Management instance? Then you can use the thumbprint in the policy.

Example:

```
resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_api_management" "test" {
  name                = "example-apim"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku {
    name     = "Developer"
    capacity = 1
  }
}

resource "azurerm_api_management_certificate" "test" {
  name                = "example-cert"
  api_management_name = "${azurerm_api_management.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  data                = "${filebase64("example.pfx")}"
}

resource "azurerm_api_management_api_policy" "example" {
  api_name            = "${...}"
  api_management_name = "${azurerm_api_management_api.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  xml_content = <<XML
<policies>
  <inbound>
    ..... Something to validate the cert with....
	${azurerm_api_management_certificate.test.thumbprint}
  </inbound>
</policies>
XML
}
```

**Comment by molinch** [comment]
@brunhil the goal is to use the certificate in the api management policy.
Not for a single api.

**Comment by robinkb** [comment]
@tombuildsstuff @katbyte This ticket can be closed since the implementation of `azurerm_api_management_policy`, correct?

**Comment by tombuildsstuff** [comment]
Closing this out since this should now be available as mentioned above, thanks @robinkb
