### ISSUE TITLE
storage_data_disk needs to support count

### ISSUE THREAD

**Issue by clangaxon** [terraform-providers/terraform-provider-azurerm#476]
Not having count support ends up requiring both a mess and lots of duplication in order to support varying numbers of data disks attached to VMs.

I think this has been brought up before, but kicked down the road at the Terraform level instead of the provider level. Is it possible to implement this at the provider level?

Thanks.

**Comment by katbyte** [comment]
Hi @clangaxon,

Thanks for opening this issue, this will be fixed by #1207.
