### ISSUE TITLE
Feature request: azurerm_api_management_diagnostic

### ISSUE THREAD

**Issue by molinch** [terraform-providers/terraform-provider-azurerm#4760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it does not seem to be possible to specify the diagnostic settings for API management
This part was mentioned in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1177 but it seems like it got forgotten

![image](https://user-images.githubusercontent.com/5130190/67845181-f1f86f00-faf6-11e9-840c-ed0ed0514463.png)

### New or Affected Resource(s)

- azurerm_api_management_diagnostic
- azurerm_api_management_api_diagnostic

### Potential Terraform Configuration

Basic settings would be as simple as:
```hcl
resource "azurerm_api_management_diagnostic" "api_management_diagnostic" {
  logger = "${azurerm_api_management_logger.api_management_logger.name}"
  sampling = 20
  always_log_errors = true
}
```
But there are optional additional settings as well:
![image](https://user-images.githubusercontent.com/5130190/67845428-603d3180-faf7-11e9-8024-5d0970b25134.png)

### References

See the yaml that references diagnostics:
https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/example/diagnostics/application-insights.template.json

**Comment by aqche** [comment]
Hi, I was making an attempt at adding the `azurerm_api_management_diagnostic` resource and managed it get it working but since it is the provider is currently using `2018-01-01` version of the `apimanagement` service the resource only supports enabling and disabling Application Insights. Would it be valuable for me to open a PR with the `2018-01-01` `azurerm_api_management_diagnostic` resource?

**Comment by jeanpaulsmit** [comment]
Great feature request, looking for this myself. However, I don't think this should be enabled on APIM level, rather on API level?
Although you can enable it on all API's using the Azure portal, in my view it's a property of an API.
As the logging/diagnostics are going to App Insights, the resource should be called something like api-management-api-appinsights or api-management-api-logger-appinsights to be prepared for additional loggers.

**Comment by evertonmc** [comment]
> Potential Terraform Configuration
> Basic settings would be as simple as:
> 
> resource "azurerm_api_management_diagnostic" "api_management_diagnostic" {
>   logger = "${azurerm_api_management_logger.api_management_logger.name}"

What happened to this suggested config?
There is no link between both in the current implementation #6104

**Comment by hctv19** [comment]
@aqche Hey! I think the the API version in use by the provider has been updated to one of the 2019 versions in a previous PR, so it should be possible to build on the support for the diagnostics resources now. Any chance you'd be able to take another look at some point?
