### ISSUE TITLE
External cache property missing for azurerm_api_management

### ISSUE THREAD

**Issue by evertonmc** [terraform-providers/terraform-provider-azurerm#4765]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `0.12.5`

### Affected Resource(s)

* `azurerm_api_management`

There is no way to add an [external cache](https://github.com/Azure/azure-sdk-for-go/blob/master/services/apimanagement/mgmt/2019-01-01/apimanagement/cache.go) to the azurerm_api_management

**Comment by mluker** [comment]
Any updates on this?
