### ISSUE TITLE
Cannot destroy stopped VM if a VM extension is attached.

### ISSUE THREAD

**Issue by clangaxon** [terraform-providers/terraform-provider-azurerm#477]
Would it be possible to skip the vm_extension destruction on a VM that's about to be destroyed?

> * azurerm_virtual_machine_extension.vm_script.1: compute.VirtualMachineExtensionsClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Cannot modify extensions in the VM when the VM is not running."

**Comment by samirageb** [comment]
@clangaxon As a workaround, I typically will either do
`terraform state rm azurerm_virtual_machine_extension.default` (Cleaner output)
OR
`terraform taint -allow-missing azurerm_virtual_machine.default`

before destroying a VM. Just an FYI.

**Comment by rohrerb** [comment]
Do we have a ETA on when this will be fixed?  Very easy to reproduce and extremely annoying when we do run into it.

**Comment by VaijanathB** [comment]
This is an upstream dependency on Azure service side. Note we cannot delete an extension directly when the VM is stopped in azure portal too.

**Comment by achandmsft** [comment]
We will follow up with platform. @VaijanathB will add an issue with platform to track this.

**Comment by VaijanathB** [comment]
It should be easy to reproduce. If you provisoin a VM with extension like here https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html , then shut it down and call tf destroy, you should be able to reproduce it. 
@Phydeauxman which version of Terraform are you running ?

**Comment by Phydeauxman** [comment]
@VaijanathB I am not experiencing the same issue.  I have no problem deleting a VM that has a CSE no matter whether it is running or not.

**Comment by Phydeauxman** [comment]
@VaijanathB once I provision a VM using the config that includes the CSE previously posted...I basically just do a destroy on it that explicitly destroys the VM.  When I do this...it also destroys the CSE with no issues

**Comment by tombuildsstuff** [comment]
hi @clangaxon @samirageb @rohrerb 

Based on @Phydeauxman's comments it appears this issue has been resolved - given the remnants of this are an Azure API issue I'm going to close this issue for the moment.

Thanks!

**Comment by tescales** [comment]
This remains an issue for extensions/vms deployed as part of a module, as of TF 11.10. 

REPRO: Create a module that deploys both extension and a VM, apply, shutdown VM then destroy.

SAMPLE CODE
```
*** main.tf:
module "lin-vm" {
  source  = "../modules/lin-vm"
  vm-name = "mycoolvm"
  vm-location = "westus"
  vm-rsg = "mycoolrg"
  vm-size = "Standard_E2s_v3"
  vm-subnet_id = "${module.network.subnet_ids[2]}"
}

*** modules/lin-vm/main.tf:
resource "azurerm_network_interface" "nic" {
  name                = "${var.vm-name}-nic"
  location            = "${var.vm-location}"
  resource_group_name = "${var.vm-rsg}"

  ip_configuration {
    name                          = "${var.vm-name}-ipc"
    subnet_id                     = "${var.vm-subnet_id}"
    private_ip_address_allocation = "dynamic"
  }
}

resource "azurerm_virtual_machine" "vm" {
  name                             = "${var.vm-name}"
  location                         = "${var.vm-location}"
  resource_group_name              = "${var.vm-rsg}"
  network_interface_ids            = ["${azurerm_network_interface.nic.id}"]
  vm_size                          = "${var.vm-size}"
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }

  storage_os_disk {
    name              = "${var.vm-name}-osdisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "${var.vm-name}"
    admin_username = "${var.vm-username}"
    admin_password = "${var.vm-password}"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
}

resource "azurerm_virtual_machine_extension" "network-watcher" {
  name                    = "${var.vm-name}-la-ext"
  location                = "${var.vm-location}"
  resource_group_name     = "${var.vm-rsg}"
  virtual_machine_name    = "${azurerm_virtual_machine.vm.name}"
  publisher               = "Microsoft.Azure.NetworkWatcher"
  type                    = "NetworkWatcherAgentLinux"
  type_handler_version      = "1.4"
  auto_upgrade_minor_version = "true"
}

*** modules/lin-vm/variables.tf:
variable "vm-name" {
    description = "Name of the virtual machine"
}
variable "vm-location" {
    description = "Location to deploy virtual machine"
}
variable "vm-rsg" {
    description = "Resource group for the virtual machine"
}
variable "vm-size" {
    description = "VM Sku size"
}
variable "vm-username" {
    description = "Username"
}
variable "vm-password" {
    description = "Password"
}
variable "vm-subnet_id" {
    description = "Subnet ID for the virtual machine"
}
```

**Comment by marioanton** [comment]
Still an issue to me.

> * azurerm_virtual_machine_extension.azureDiskEncryption.1: compute.VirtualMachineExtensionsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Cannot modify extensions in the VM when the VM is not running."
