### ISSUE TITLE
Terraform crashes with empty body match in azurerm_application_gateway

### ISSUE THREAD

**Issue by i7c** [terraform-providers/terraform-provider-azurerm#4772]
Hi there, I've run into the following bug:

Terraform crashes when you try to create an `azurerm_application_gateway` and you set the _match body_ in the _backend health probe_ to empty string `""`. Please note, that empty string is the *default value* according to the Azure ARM API Spec https://docs.microsoft.com/en-us/rest/api/application-gateway/applicationgateways/createorupdate#applicationgatewayprobehealthresponsematch

Please also note, that there are other issues discussing why this terraform provider seems to think that `*` is a valid default value (#1920). Azure does *not* interpret the match body as a regex or wildcard.

Furthermore, please note that this configuration used to work in provider version `1.32`.

Lastly, note the following peculiarity:
- If I first set the match body to "x"
- apply
- then set it to ""
- repeatedly apply
 terraform is in an endless loop. It says it will perform the following change:
```
~ match {
    - body        = "x" -> null
    ~ status_code = [
        - "200-399",
      ]
  }
```
Apply is successful. If you apply again, it will report the **same** change again and again. Also note, that `-> null` is wrong, it should be `-> ""`.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.12
+ provider.azurerm v1.36.1

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "agtest"
  location = "westeurope"
}

resource "azurerm_virtual_network" "test" {
  name                = "agtest"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  address_space       = ["10.254.0.0/16"]
}

resource "azurerm_subnet" "frontend" {
  name                 = "agtest"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.254.0.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "agtest"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_application_gateway" "network" {
  name                = "agtest"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = "${azurerm_subnet.frontend.id}"
  }

  frontend_port {
    name = "test"
    port = 80
  }

  frontend_ip_configuration {
    name                 = "test"
    public_ip_address_id = "${azurerm_public_ip.test.id}"
  }

  backend_address_pool {
    name = "test"
  }

  backend_http_settings {
    name                  = "test"
    cookie_based_affinity = "Disabled"
    path                  = "/path1/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 1
  }

  http_listener {
    name                           = "test"
    frontend_ip_configuration_name = "test"
    frontend_port_name             = "test"
    protocol                       = "Http"
  }

  request_routing_rule {
    name                       = "test"
    rule_type                  = "Basic"
    http_listener_name         = "test"
    backend_address_pool_name  = "test"
    backend_http_settings_name = "test"
  }

  probe {
    name                                      = "backend-health-probe"
    pick_host_name_from_backend_http_settings = true
    interval                                  = "10"
    protocol                                  = "Http"
    path                                      = "/"
    timeout                                   = "30"
    unhealthy_threshold                       = "3"

    match {
      body = ""
    }
  }
}

```

### Panic Output
`panic: interface conversion: interface {} is nil, not map[string]interface {}`

https://gist.github.com/i7c/35c1f7a9443a1f19109a6cae0059884e

### Expected Behavior

Should apply without errors.

### Actual Behavior

Terraform crashes every time the match body is an empty string.

### Steps to Reproduce

Use the code above and 

1. `terraform apply`

### References

Might or might not be related to:
* #2817
* #1920

**Comment by mbfrahry** [comment]
Hey @i7c, thanks for opening this issue. We found and fixed your crash and allow setting an empty string. I'm not sure why `*` is the default but it's not something we can change in the short term as it would cause breaking changes for anyone using that default as Terraform would see it as a change and try to change `*` to `""`
