### ISSUE TITLE
Kafka API default value causes namespace recreation

### ISSUE THREAD

**Issue by cima** [terraform-providers/terraform-provider-azurerm#4773]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform v0.11.13
* provider.azurerm: version = "~> 1.35"

### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {}
}
provider "azurerm" {}

# Directly taken from https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace.html
resource "azurerm_resource_group" "eventhub_terraform_bug" {
  name     = "eventhub-terraform-bug"
  location = "west europe"
}
resource "azurerm_eventhub_namespace" "eventhub_terraform_bug_namespace" {
  name                = "eventhub-terraform-bug"
  location            = "${azurerm_resource_group.eventhub_terraform_bug.location}"
  resource_group_name = "${azurerm_resource_group.eventhub_terraform_bug.name}"
  sku                 = "Standard"
}
```

### Debug Output
* https://github.com/cima/eventhub-terraform-bug/blob/master/doc/first_run.log
* https://github.com/cima/eventhub-terraform-bug/blob/master/doc/second_run.log

### Expected Behavior

If I create eventhub namespace without `kafka_enable` and run terraform repeatedly it doesn't recreate the resource.

### Actual Behavior

Microsoft made Kafka API compulsory at new eventhub namespaces of *Standard tier*. Second and any consecusive execution of the script causes the eventhub namespace to be removed and created again.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

See extensive project with detailed description at https://github.com/cima/eventhub-terraform-bug

### Important facts

The SKU must be Standard.

### References

* A complete example project with outputs can be found at https://github.com/cima/eventhub-terraform-bug

* #0000

**Comment by tombuildsstuff** [comment]
hi @cima 

Thanks for opening this issue.

The fix for this has been merged in #4743 which will be shipping as a part of v1.37 - since the fix for this has been merged I'm going to close this issue for the moment - however as I've assigned this to the 1.37 milestone @hashibot will comment here when this has been released.

In the interim it should be possible to work around this using an `ignore_changes` element within the `lifecycle` block to ignore the changes to this field, like so:

```
resource "azurerm_eventhub_namespace" "example" {
  # ...

  lifecycle {
    ignore_changes = [
      "kafka_enabled",
    ]
  }
}
```

Thanks!
