### ISSUE TITLE
Error waiting for removal of Application Security Group

### ISSUE THREAD

**Issue by rjfmachado** [terraform-providers/terraform-provider-azurerm#4781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.12
+ provider.azurerm v1.36.1
+ provider.random v2.2.1

### Affected Resource(s)

azurerm_application_security_group

### Terraform Configuration Files

https://gist.github.com/rjfmachado/5857e37b2b7131e05f98bc649b9a1007

### Debug Output

https://gist.github.com/rjfmachado/7ea4c75bbda859682e6320386218d741
https://gist.github.com/rjfmachado/eaacc29bef7fa1fff24727f6c90af3f6
https://gist.github.com/rjfmachado/12a98c1ca62eb30b609b57ff26341d2b

### Expected Behavior

Terraform destroy should delete all resources

### Actual Behavior

Terraform destroy fails to delete all resources, requires 3 attempts.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. `terraform destroy`
4. `terraform destroy`

### References

* #0000

**Comment by neil-yechenwei** [comment]
@rjfmachado, thanks for opening this issue. After tested, these resources can be deleted successfully with latest azurerm version. Could you have a try with latest azurerm version to check whether the issue still exists? Thanks.

**Comment by rjfmachado** [comment]
Updated the code for azurerm 2.0 https://gist.github.com/rjfmachado/fe5facff3beadd3a57cd504d0e77cd84

It still fails on destroy with:
Terraform v0.12.26
+ provider.azurerm v2.15.0

Ist attempt:
Error: Error waiting for removal of Application Security Group for NIC "fkltmh897-nic" (Resource Group "testnetwork"): Code="OperationNotAllowed" Message="Operation 'startTenantUpdate' is not allowed on VM 'fkltmh897' since the VM is marked for deletion. You can only retry the Delete operation (or wait for an ongoing one to complete)." Details=[]

2nd attempt
Error: Error issuing delete request for Application Security Group "alllinux" (Resource Group "testnetwork"): network.ApplicationSecurityGroupsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationSecurityGroupCannotBeDeletedIfReferencedByNetworkInterface" Message="Application Security Group /subscriptions/dae80d11-9600-4f34-b59a-07628d7d9765/resourceGroups/testnetwork/providers/Microsoft.Network/applicationSecurityGroups/alllinux cannot be deleted because it is referenced by the following Network Interfaces(s): /subscriptions/dae80d11-9600-4f34-b59a-07628d7d9765/resourceGroups/testnetwork/providers/Microsoft.Network/networkInterfaces/fkltmh897-nic." Details=[]

3rd attempt succeeds

**Comment by neil-yechenwei** [comment]
Thanks. I can repro it now. The network interface is referenced by both azurerm_network_interface_application_security_group_association and azurerm_virtual_machine. After tested, seems network interface api doesn't allow to be executed with virtual machine api in parallel while deleting. I assume it's expected behavior for terraform. Because azurerm_network_interface_application_security_group_association cannot know the virtual machine name so that we cannot add virtual machine lock into this resource. For your scenario, suggests to add "depends_on = [azurerm_virtual_machine.example]" to fix this issue. And I submit a PR to add an example for this scenario. Thanks.

Sample code:
```
resource "azurerm_network_interface_application_security_group_association" "example" {
  network_interface_id          = azurerm_network_interface.example.id
  application_security_group_id = azurerm_application_security_group.example.id
  
  depends_on = [azurerm_virtual_machine.example]
}
```
