### ISSUE TITLE
Failed to create Azure File Share when quota is defined

### ISSUE THREAD

**Issue by rukawata** [terraform-providers/terraform-provider-azurerm#4782]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_share`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "nancyc-rg-1"
  location = "westus2"
}

resource "azurerm_storage_account" "sa" {
  name                     = "nancyctest1234"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_kind             = "FileStorage"
  account_tier             = "Premium"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "ss" {
  name                 = "bits"
  storage_account_name = azurerm_storage_account.sa.name
  quota                = 50
}
```

### Debug Output
[20191031.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/3795196/20191031.log)

### Actual Behavior
Error:

2019/10/31 10:57:28 [DEBUG] azurerm_storage_share.ss: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating Share "bits" (Account "nancyctest1234" / Resource Group "nancyc-rg-1"): shares.Client#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:942190c5-401a-003c-2c14-9033e1000000\nTime:2019-10-31T17:57:28.0079937Z</Message><HeaderName>x-ms-share-quota</HeaderName><HeaderValue>50</HeaderValue></Error>" error: invalid character 'ï' looking for beginning of value

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jcmaasb** [comment]
Hi, 
I had the same problem in the past, the minimum quota is 100GB. Any lower value shows this error. 
Team, can yoy change this output with other more accurate?

**Comment by DanielMabbett** [comment]
![image](https://user-images.githubusercontent.com/15195905/68212733-127e6880-ffd2-11e9-93bc-77abef0bad05.png)

**Comment by rukawata** [comment]
Please update the terraform [doc](https://www.terraform.io/docs/providers/azurerm/r/storage_share.html) as well.

> quota - (Optional) The maximum size of the share, in gigabytes. Must be greater than 0, and less than or equal to 5 TB (5120 GB) for Standard storage accounts or 100 TB (102400 GB) for Premium storage accounts. Default is 5120.
