### ISSUE TITLE
azurerm_storage_account network_rules block not included in Plan

### ISSUE THREAD

**Issue by lachie-white** [terraform-providers/terraform-provider-azurerm#4786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform Version = 12.12
Azurerm Version = 1.36.1

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "test-storage" {
  name                     = "lachlanstoragetestacc"
  resource_group_name      = azurerm_resource_group.test-rg.name
  location                 = local.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = [azurerm_subnet.test-subnet.id]
  }
}
```

### Expected Behavior
When removing the network_rules code block for a storage account a terraform plan should pick up the change in the requested state.

### Actual Behavior
When removing the network_rules block and running a terraform plan there is no "change" recorded.

When a terraform apply occurs the change is made though

### Steps to Reproduce

1. Create a azurerm_storage_account w/ a network_rules block:
```hcl
resource "azurerm_storage_account" "test-storage" {
  name                     = "lachlanstoragetestacc"
  resource_group_name      = azurerm_resource_group.test-rg.name
  location                 = local.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = [azurerm_subnet.test-subnet.id]
  }
}
```
2. Remove the network_rules block
```hcl
resource "azurerm_storage_account" "test-storage" {
  name                     = "lachlanstoragetestacc"
  resource_group_name      = azurerm_resource_group.test-rg.name
  location                 = local.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  # network_rules {
  #   default_action             = "Deny"
  #   virtual_network_subnet_ids = [azurerm_subnet.test-subnet.id]
  # }
}
```
3. Run a `terraform plan`
Notice no change is recorded

4. Make an additional change to your infrastrcuture, update a tag on the resource group

5. Run a `terraform plan`
You should have 1 change pending

6. Run a `terraforrm apply`
Notice that your pending change is applied and also the removal of the network_rules block that isn't recorded.

**Comment by djsly** [comment]
I'm getting the network_rule section recreated with each apply

```
 + network_rules {
          + bypass         = (known after apply)
          + default_action = "Allow"
          + ip_rules       = (known after apply)
        }
```

seems like the *plan* indeed is missing the section..

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume it's by design. If you want to remove `network_rules`, please set  `default_action` of `network_rules` to `Allow`.
