### ISSUE TITLE
`azurerm_key_vault_certificate` - support for speciying the `subject_alternative_name`

### ISSUE THREAD

**Issue by jameswhinn** [terraform-providers/terraform-provider-azurerm#479]
Currently the "azurerm_key_vault_certificate" resource does not allow for the creation of a SubjectAlternativeName within the X509CertificateProperties object. It would be great if the resource could be extended to allow for this.

**Comment by kevinneufeld** [comment]
+1 on the above.   
It would also be great to have the Thumbprint of the cert as an output.

**Comment by draggeta** [comment]
Due to hacktober I decided to try my hand at this. The PR i submitted should fix this.

@kevinneufeld: The thumbprint is already exported from what I can see. It was added in PR #1904

**Comment by tombuildsstuff** [comment]
hi @jameswhinn @kevinneufeld @draggeta 

Just to let you know that this has been released as a part of v1.18 of the AzureRM Provider ([the full changelog is available here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.18.0/CHANGELOG.md)). You can upgrade to this by specifying the version in the provider block (as shown below) and then running `terraform init -upgrade`

```
provider "azurerm" {
  version = "=1.18.0"
}
```

Thanks!
