### ISSUE TITLE
Hyphens not allowed in Azure Bastion ip configuration name

### ISSUE THREAD

**Issue by arestarh** [terraform-providers/terraform-provider-azurerm#4807]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

1.36.1

### Affected Resource(s)

azurerm_bastion_host

### Terraform Configuration Files

```hcl
resource "azurerm_bastion_host" "bastion" {
  name                = "myname-bastion-myenvironment"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"

  ip_configuration {
    name                 = "myname-bastion-myenvironment-configuration"
    subnet_id            = "${azurerm_subnet.bastion.id}"
    public_ip_address_id = "${azurerm_public_ip.bhpip.id}"
  }
}
```

### Expected Behavior

Resource ip configuration name should be myname-bastion-myenvironment-configuration.

### Actual Behavior

This error is generated: **Error**: _lowercase letters, highercase letters numbers only are allowed in "ip_configuration.0.name": "myname-bastion-myenvironment-configuration"_

### Steps to Reproduce

Create a bastion that contains hyphens as part of the ip configuration name

**Comment by arestarh** [comment]
Pretty similar issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/4759 that related to bastion host name was resolved by PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/4766

Seems like we have bastion ip configuration name constraints as well according to https://github.com/terraform-providers/terraform-provider-azurerm/blob/94cf18b287d634ee16aa5e37d3a73d3e8a356fa4/azurerm/resource_arm_bastion_host.go#L211

Unfortunately I didn't find info about bastion ip configuration name constraints neither in
https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-06-01/bastionhosts nor in https://docs.microsoft.com/en-us/rest/api/virtualnetwork/bastionhosts/createorupdate

**Comment by tombuildsstuff** [comment]
hey @arestarh 

Thanks for opening this issue.

As you've mentioned this was previously reported in #4762 which is fixed via #4766 - but it's not shipped yet; it's planned that this'll ship as a part of v1.37 in the near future.

Since this issue's been resolved I'm going to close this issue for the moment - but I've assigned this to the v1.37 milestone which means that @hashibot will comment when v1.37 has been released / this is usable :)

Thanks!

**Comment by arestarh** [comment]
@tombuildsstuff Seems like issue reported in https://github.com/terraform-providers/terraform-provider-azurerm/issues/4762 and https://github.com/terraform-providers/terraform-provider-azurerm/issues/4759 was related to **bastion name** itself and it was fixed by https://github.com/terraform-providers/terraform-provider-azurerm/pull/4766 in function **validateAzureRMBastionHostName** in https://github.com/terraform-providers/terraform-provider-azurerm/blob/94cf18b287d634ee16aa5e37d3a73d3e8a356fa4/azurerm/resource_arm_bastion_host.go#L194

I've reported issue related to bastion **ip configuration** name constraints that related to https://github.com/terraform-providers/terraform-provider-azurerm/blob/94cf18b287d634ee16aa5e37d3a73d3e8a356fa4/azurerm/resource_arm_bastion_host.go#L211 and function **validateAzureRMBastionIPConfigName** and was not covered by https://github.com/terraform-providers/terraform-provider-azurerm/pull/4766

**Comment by tombuildsstuff** [comment]
🤦‍♂ sorry @arestarh missed that critical word - reopening

**Comment by aqche** [comment]
Tested applying an ARM template with an invalid ip configuration name and looks like the naming requirements are the same as the bastion host names. I can have a PR for this open soon. :)

<img width="486" alt="Screen Shot 2019-11-05 at 4 39 47 PM" src="https://user-images.githubusercontent.com/39076898/68258373-5762c900-ffeb-11e9-964a-0080030e9384.png">
