### ISSUE TITLE
Error: Provider produced inconsistent final plan in azurerm_postgresql_server

### ISSUE THREAD

**Issue by ausfestivus** [terraform-providers/terraform-provider-azurerm#4813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
😀 abest@BARMIX2:~/xxxxxx/cptTerraformEnterprise/terraform-private/examples/bootstrap-azure (develop-andrewb) $ terraform -v
Terraform v0.12.13
+ provider.azurerm v1.36.1
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_server" "new" {
    name                = "${local.prefix}"
    location            = "${var.location}"
    resource_group_name = "${azurerm_resource_group.new.name}"

    sku {
        name     = "B_Gen5_2"
        capacity = 2
        tier     = "Basic"
        family   = "Gen5"
    }

    storage_profile {
        storage_mb            = 5120
        backup_retention_days = 30
        geo_redundant_backup  = "Disabled"
        auto_grow             = "Enabled"
    }

    administrator_login          = "psqladminun"
    administrator_login_password = "${random_string.dbserver.result}"
    version                      = "9.6"
    ssl_enforcement              = "Enabled"
    tags                         = "${var.additional_tags}"
}
```

### Debug Output

See the Gist here https://gist.github.com/ausfestivus/e66a004bcf1cf1c0fc4be8af735ee683

### Panic Output

nil

### Expected Behavior

apply should not have ended with an error.

### Actual Behavior

The following error is displayed at the end of the `apply` run:

```shell
2019/11/05 22:25:48 [ERROR] <root>: eval: *terraform.EvalCheckPlannedChange, err: Provider produced inconsistent final plan: When expanding the plan for azurerm_postgresql_database.new to include new values learned so far during apply, provider "azurerm" produced an invalid new value for .server_name: was cty.StringVal("cptTFE"), but now cty.StringVal("cpttfe").

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2019/11/05 22:25:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: Provider produced inconsistent final plan: When expanding the plan for azurerm_postgresql_database.new to include new values learned so far during apply, provider "azurerm" produced an invalid new value for .server_name: was cty.StringVal("cptTFE"), but now cty.StringVal("cpttfe").

This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

### Steps to Reproduce

With the above HCL run `terraform apply -var-file ../AFILE.tfvars -input false -auto-approv`

### Important Factoids

nil

### References

* [azurerm_postgresql_server documentation](https://www.terraform.io/docs/providers/azurerm/r/postgresql_server.html)
* [the gist](https://gist.github.com/ausfestivus/e66a004bcf1cf1c0fc4be8af735ee683)

* #0000

**Comment by katbyte** [comment]
Hi @ausfestivus,

I'm sorry that your having this issue, it seems like the API is either accepting uppercase in error, or not returning the correct case. Given that portal prevents uppercase server names i'm going to guess the API is just not correctly validating input and silently lowercasing it.

I've opened an (issue)[https://github.com/Azure/azure-sdk-for-go/issues/6305] on the sdk but i think you will have to change the server name to lowercase.
