### ISSUE TITLE
azurerm_search_service should be able to scale replicas and partitions without forcing a new resource

### ISSUE THREAD

**Issue by leyshon** [terraform-providers/terraform-provider-azurerm#4820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently the azurerm_search_service resource will delete and recreate the search service if you change the number of replicas or partitions. In the portal it is possible to scale both of these without creating a new resource. It seems that the same should be true in the terraform resource.  

### New or Affected Resource(s)

* azurerm_search_service

**Comment by katbyte** [comment]
Hey @leyshon, this was fixed in #5935 and released in v2.1.0 today 🙂
