### ISSUE TITLE
azurerm_iot_dps missing ability to provide AuthorizationPolicies

### ISSUE THREAD

**Issue by brunhil** [terraform-providers/terraform-provider-azurerm#4822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current **azurerm_iot_dps** is missing the ability to provide AuthorizationPolicies. The current Azure GO SDK supports providing this, [link](https://sourcegraph.com/github.com/Azure/azure-sdk-for-go@6355969b31502e528a7534fbdcd7cad04496a5fd/-/blob/services/provisioningservices/mgmt/2018-01-22/iothub/models.go#L259:27).

### New or Affected Resource(s)

* azurerm_iot_dps

### Potential Terraform Configuration

```hcl

resource "azurerm_iot_dps" "device-provisioning-service" {
  name                = "iot-device-provisioning-service"
  resource_group_name = "resource-group-name"
    location          = "location"

  linked_hub {
    connection_string = "blah"
    location          = "location"
  }

  sku {
    name     = "S"
    tier     = "Basic"
    capacity = "1"
  }

  authorization_policy {
    name = "test_policy"
    permissions = "DeviceConnect,EnrollmentRead"
  }
}
```

### References

* #1712 - IoT Device Provisioning Resource

**Comment by brunhil** [comment]
I plan on working on this, will have a PR shortly for this addition.

**Comment by kraihn** [comment]
Is there anything preventing this from becoming a new resource definition? I think it makes sense to follow the patterns used for IoT Hubs and Event Hubs. Each of the permissions would then become an argument on the resource.

https://www.terraform.io/docs/providers/azurerm/r/eventhub_authorization_rule.html

https://www.terraform.io/docs/providers/azurerm/r/iothub_shared_access_policy.html

**Comment by brunhil** [comment]
The main reason was because it was a property under the **iothub_dps** resource in the Azure API. Another leading factor was the fact that the linked hubs were defined under the resource as well. 

I can pull this out if we want to, I'm all for consistency where it is needed

**Comment by brunhil** [comment]
After thinking about this further, I'm going to go ahead with the approach recommended by@krain as this seems to be the recommended approach elsewhere in the provider.

**Comment by maxbog** [comment]
@brunhil Do you have any ETA on the PR? I also have a need to define the shared access policies in my project.

**Comment by brunhil** [comment]
Hi @maxbog , I started working on this late last week. I’ll try to wrap this up quickly then!
