### ISSUE TITLE
azurerm_front_door does not support all settings of API

### ISSUE THREAD

**Issue by davidobrien1985** [terraform-providers/terraform-provider-azurerm#4826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

`azurerm_front_door` is missing critical config setting to set timeout for requests:

https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontdoors/createorupdate#backendpoolssettings

Can this please be added to the resource?

**Comment by WodansSon** [comment]
@davidobrien1985 thanks for opening this issue, it has already been opened in #4558 so I am going to close this one as duplicate and track this with the other issue. Thanks.
