### ISSUE TITLE
azurerm_data_factory data source missing values

### ISSUE THREAD

**Issue by lukerosser** [terraform-providers/terraform-provider-azurerm#4827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.13
+ provider.azurerm v1.36.1
```

### Affected Resource(s)

https://www.terraform.io/docs/providers/azurerm/d/data_factory.html

* `azurerm_data_factory` data source

### Terraform Configuration Files

```hcl
data "azurerm_data_factory" "datafactory" {
  name                = "datafactory"
  resource_group_name = "datafactory-rg"
}

output "data_factory_principal" {
  value = data.azurerm_data_factory.datafactory.identity.principal_id
}

output "data_factory_location" {
  value = data.azurerm_data_factory.datafactory.location
}
```

### Expected Behavior

Datafactory principal ID displayed as an output

### Actual Behavior

Error on plan:

```
Error: Unsupported attribute

  on XXXX, in output "data_factory_principal":
  11:   value = data.azurerm_data_factory.datafactory.identity.principal_id

This value does not have any attributes.
```

**Comment by jleechp-occm** [comment]
Trying today with:

```sh
Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v2.0.0
```
Terraform code:

```hcl
locals {
  adf_prefix = "<redacted>"
}

data "azurerm_data_factory" adf {
  name                = "${local.adf_prefix}-adf"
  resource_group_name = "${local.adf_prefix}-rg"
}

data "azuread_service_principal" adf {
  display_name = "${local.adf_prefix}-adf"
}

output "ad_adf" {
  value = data.azuread_service_principal.adf
}

output "adf" {
  value = data.azurerm_data_factory.adf
}

provider azurerm {
  features {}
}
```

`terraform apply` and `terraform refresh` provide the following:

```hcl
ad_adf = {
  "app_roles" = []
  "application_id" = "<app-id>"
  "display_name" = "<name>"
  "id" = "<id>"
  "oauth2_permissions" = []
  "object_id" = "<id>"
}
adf = {}
```

It looks as though the Data Factory data source is not returning any properties.
