### ISSUE TITLE
InvalidValuesForRequestParameters when provisioning a BlockBlobStorage Account

### ISSUE THREAD

**Issue by RussiaTeam** [terraform-providers/terraform-provider-azurerm#4842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.13
+ provider.azurerm v1.36.1
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "st_account" {
  name                = "storagebugtest9000"
  resource_group_name = "foobar"
  location            = "East US"

  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "BlockBlobStorage"
}
```

### Debug Output

https://gist.github.com/GusAntoniassi/f41c29d40bcf04b482e809c6cab069d6#file-blockblobstorage-log

### Panic Output

None

### Expected Behavior

The resource should be provisioned as a BlockBlobStorage, as said [in the docs](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#account_kind)

### Actual Behavior

Terraform returns the following error message:

``` 
Error: Error creating Azure Storage Account "storagebugtest9000": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: kind, sku. For more information, see - https://aka.ms/storageaccounttypes"
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Commenting out the "account_kind" declaration fixes the problem.

### References

None

**Comment by gongjunhuang** [comment]
Got similar error while creating `FileStorage`:
```
Error creating Azure Storage Account "sa001kea": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: kind, sku. 
```

Template:
```
resource "azurerm_storage_account" "jira_sa" {
  name                     = "sa001kea"
  resource_group_name      = "foobar"
  location                 = "eastus2"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "FileStorage"

  tags = "${local.storage_tags}"
}
```

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. For `BlockBlobStorage` and `FileStorage` accounts only `Premium` is valid. See more details from [doc](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#types-of-storage-accounts). I will submit a fix to update doc. Thanks.
