### ISSUE TITLE
InvalidRequestPropertyValue when updating a storage account with an access tier defined

### ISSUE THREAD

**Issue by RussiaTeam** [terraform-providers/terraform-provider-azurerm#4843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.13
+ provider.azurerm v1.36.1
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "st_account" {
  name                = "storagebugtest9000"
  resource_group_name = "foobar"
  location            = "East US"

  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier              = "Hot"
}

```

### Debug Output

https://gist.github.com/GusAntoniassi/f41c29d40bcf04b482e809c6cab069d6#file-hotstorage-log

### Panic Output

None

### Expected Behavior

The resource should be updated correctly.

### Actual Behavior

Terraform returns the following error message:

``` 
Error: Error updating Azure Storage Account access_tier "storagebugtest9000": storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestPropertyValue" Message="The value 'Hot' is not allowed for property accessTier."
```

### Steps to Reproduce

1. `terraform apply` - First time it works normally
2. `terraform apply` - The second time, after the resource is created, it throws the reported error message.

### Important Factoids

The problem only happens with an existing storage account. 

It doesn't seem to matter whether the value is "Hot" or "Cold".

Commenting out the "access_tier" declaration fixes the problem.

### References

None

**Comment by t3mi** [comment]
StorageV1 accounts (which is default) do not support tiering. If the latter is needed set _account_kind_ to BlobStorage, FileStorage or StorageV2.

**Comment by neil-yechenwei** [comment]
@RussiaTeam, thanks for opening this issue. Seems API behavior has been changed. It can be updated directly now. Could you have a try below tfconfig which is similar with yours to check whether the problem still exists? Thanks.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-storage-test03"
  location = "eastus2"
}

resource "azurerm_storage_account" "test" {
  name                = "storageaccttest06"
  resource_group_name = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  
  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier              = "Hot"
  // access_tier              = "Cool"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if the solution proposed above doesn't work and we'll take another look.

Thanks!
