### ISSUE TITLE
azurerm_security_center_subscription_pricing does not enable pricing for all resource types

### ISSUE THREAD

**Issue by cananac** [terraform-providers/terraform-provider-azurerm#4846]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

I'm using azurerm_security_center_subscription_pricing to enable Standard pricing for Azure Security Center. But this does not enable the Standard pricing tier for all the resource types under subscription. Security Center -> Pricing & Settings ->  Pricing Tier, the plan is Disabled for resources apart from virtual machines. 

The case can be reproduced as follows:
- Enable Standard pricing from portal for Security Center and enable plan only for Virtual Machines. Save.
- Then change pricing as Free and save.
- Then set Standard pricing using azurerm_security_center_subscription_pricing

It would also be great to enable/disable resource types individually.

Thanks.

**Comment by cananac** [comment]
Hi,

Any updates on this issue?

**Comment by jarmbruster74** [comment]
Looked into this a bit more.  This actually appears to be a limitation that applies to several clients, when I create a new pricing from the Azure command line I see the same behavior.  I'm unable to find an option at this time other than through the Azure portal to turn on all resources.

**Comment by jarmbruster74** [comment]
From testing this page though it is supported in the underlying API with different pricingName values (e.g. KeyVaults, StorageAccounts, VirtualMachines, etc)

**Comment by redlineby** [comment]
Hi,
Any news with this issue. We have the same problem :\

**Comment by darren-johnson** [comment]
This would be handy for me also!

**Comment by fireblade95402** [comment]
I have a customer with the same issue. It would be great if we could get an update on this?
