### ISSUE TITLE
azurerm_virtual_machine does not store location

### ISSUE THREAD

**Issue by erlacherl-city** [terraform-providers/terraform-provider-azurerm#4855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue description

There appears to be an unspoken assumption that azure virtual machines are in the same location as their resource group. This is not necessarily true and requires that virtual machine location data is stored in the terraform state (or fetched from azure when needed).

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.13
+ provider.azurerm v1.35.0
+ provider.local v1.4.0
```

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

```
data "azurerm_virtual_machine" "main" {
  name                = "${var.virtual_machine_name}"
  resource_group_name = "${data.azurerm_resource_group.main.name}"
}

resource "azurerm_virtual_machine_extension" "linux" {
  count                      = "${lower(var.os_type) == "linux" ? 1 : 0}"
  name                       = "${var.virtual_machine_name}-run-command"
  location                   = "${data.azurerm_virtual_machine.main.location}"
  resource_group_name        = "${data.azurerm_resource_group.main.name}"
  virtual_machine_name       = "${data.azurerm_virtual_machine.main.name}"
  publisher                  = "Microsoft.CPlat.Core"
  type                       = "RunCommandLinux"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true
  protected_settings         = "${jsonencode(local.settings_linux)}"
  tags                       = "${var.tags}"
}
```

Error:

```
Error: Unsupported attribute

  on .terraform/modules/vm-run-command/erlacherl-city-terraform-azurerm-vm-run-command-4968795/main.tf line 26, in resource "azurerm_virtual_machine_extension" "linux":
  26:   location                   = "${data.azurerm_virtual_machine.main.location}"

This object has no argument, nested block, or exported attribute named
"location".
```

**Comment by tombuildsstuff** [comment]
hi @erlacherl-city 

Thanks for opening this issue.

> There appears to be an unspoken assumption that azure virtual machines are in the same location as their resource group. This is not necessarily true and requires that virtual machine location data is stored in the terraform state (or fetched from azure when needed).

The `location` field is a required property within the Azure API on this resource, as such for historical reasons we've asked the user to provide this information rather than looking it up dynamically. To your point about VM's being able to be in a different location to the Resource Group, you should be able to achieve this using the Resource Group & VM Resource with different locations - however this is an uncommon use-case, so we intentionally don't have examples of this.

Ultimately this'll be fixed by #2456 which switches to use the Virtual Machine ID rather than the Name & Resource Group (so we can look this information up at runtime) - and as such I'm going to close this issue in favour of #2456.

Thanks!

**Comment by erlacherl-city** [comment]
Hi Tom, my issue is *not* that vm location needs to be specified when creating a vm. The issue is that vm location is not stored in terraform state, and that when using the azurerm_virtual_machine *data* resource, it is not retrieved and exposed as an attribute.

**Comment by erlacherl-city** [comment]
By my reading, issue #2456 is entirely unrelated.
