### ISSUE TITLE
azurerm_eventgrid_event_subscription support for Service Bus Queue endpoint

### ISSUE THREAD

**Issue by landintrees** [terraform-providers/terraform-provider-azurerm#4857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are currently 5 endpoint types available when configuring an event grid event subscription (both through Azure portal and az cli):

- Webhook
- Storage Queue
- Event Hub
- Hybrid Connection
- Service Bus Queue

azurerm_eventgrid_event_subscription currently supports the first 4 of these, but not Service Bus Queue.

### New or Affected Resource(s)

* azurerm_eventgrid_event_subscription

### Potential Terraform Configuration
```
resource "azurerm_eventgrid_event_subscription" "default" {
  name  = "defaultEventSubscription"
  scope = azurerm_resource_group.default.id

  service_bus_queue_endpoint {
    connection_string = azurerm_servicebus_queue_authorization_rule.default.primary_connection_string
  }
}
```

* #0000

**Comment by francuesta** [comment]
Any news about this issue? Some workaround?

**Comment by landintrees** [comment]
> Any news about this issue? Some workaround?

Hi @francuesta, for now we've fallen back to using az cli to create the event subscription. Something like this:

`        az eventgrid event-subscription create \
            --subscription "$TEST_ORG_1_SUBSCRIPTION" \
            --name "$TEST_ACCOUNT-event-sub" \
            --source-resource-id "/subscriptions/$TEST_ORG_1_SUBSCRIPTION/resourceGroups/$IOTHUB_RESOURCE_GROUP/providers/Microsoft.Devices/IotHubs/$IOTHUB_NAME" \
            --endpoint-type servicebusqueue \
            --endpoint "/subscriptions/$TEST_ORG_1_SUBSCRIPTION/resourceGroups/$IOTHUB_RESOURCE_GROUP/providers/Microsoft.ServiceBus/namespaces/$IOTHUB_NAMESPACE/queues/$IOTHUB_QUEUE_NAME" \
			--advanced-filter data.deviceId StringBeginsWith $TEST_ACCOUNT
`
