### ISSUE TITLE
Support for set and get activation and expiration date on azurerm_key_vault_secret

### ISSUE THREAD

**Issue by Tomaswe** [terraform-providers/terraform-provider-azurerm#4858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The secrets can have activation and expiration date (datetime) set via Azure Portal or CLI.
Lacking the ability to set expiration date on the resource makes this security measure a manual task with the risk of forgetting and leaving the secrets valid forever.

### New or Affected Resource(s)

* azurerm_key_vault_secret

### Potential Terraform Configuration

```terraform
resource "azurerm_key_vault_secret" "expiring_secret" {
  name = "my-secret"
  value = "hush"
  key_vault_id = var.key_vault_id
  set_activation_date = false
  set_expiration_date = true
  expiration_date = "2020-01-01T12:00:00Z"
}
```
Today, while setting the expiration date manually, also setting a timestamp in a tag is the best way I've found to provide the expiration information to applications configuration during terraforming.
But that is manually synchronized and error prone or relying on some external scripting.
```terraform
resource "azurerm_key_vault_secret" "expiring_secret" {
  name = "my-secret"
  value = "hush"
  key_vault_id = var.key_vault_id
  tags = {
    expires = var.expire_date
  }
}
```
and then to retrieve it
```terraform
data "azurerm_key_vault_secret" "expiring_secret" {
  name = "my-secret"
  key_vault_id = var.key_vault_id
}
output "secret_expires"{
  value = data.azurerm_key_vault_secret.expiring_secret.tags["expires"]
}
```
### References

* https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-set
* https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-set-attributes

**Comment by aqche** [comment]
Took a crack at adding the `not_before_date` and `expiration_date` options to the `azurerm_key_vault_secret` in [this PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4873)!
