### ISSUE TITLE
azurerm_sql_active_directory_administrator allows mis-mapping of object_id and login without error 

### ISSUE THREAD

**Issue by andydkelly-ig** [terraform-providers/terraform-provider-azurerm#4867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.11.14 and v1.35.0

### Affected Resource(s)

azurerm_sql_active_directory_administrator

### Terraform Configuration Files

```
resource "azurerm_sql_active_directory_administrator" "eng" {
  server_name         = "${azurerm_sql_server.default.name}"
  resource_group_name = "${var.resourceGroupName}"
  login               = "testgroup"
  tenant_id           = "02292cae-2fe6-4371-8da1-b03d14808575"
  object_id           = "02292cae-2fe6-5432-7744-b03d1480857"
}
```

### Expected Behavior

I wouldn't expect to be able to enter the object-id of one AD Group and the Login name of another and for it to accept the values. Not sure if this is a Terraform bug or Azure SDK.

### Actual Behavior

If i put the Login name of Group A and the Object ID of Group B, then it accepts the config, show in the portal that Group A is the administrator of the SQL server but logins are not permitted df

### Steps to Reproduce

Use this resource and when choosing the Login Name and Object ID use a value from a different group for each entry.

**Comment by yupwei68** [comment]
Hi @andydkelly-ig , Thanks for opening this issue. On fact, it might be a feature of this service. The login name is just a defined username to display the AAD admin of the sql server, it's not required to the same with the AAD account display name.

**Comment by mybayern1974** [comment]
Hi @andydkelly-ig 

May we close this issue by assuming yupwei68’s reply has answered your question? Feel free to reopen this if you do not think so. Thank you.
