### ISSUE TITLE
Can't configure more than one IP_RULE in azurerm_eventhub_namespace

### ISSUE THREAD

**Issue by fabiotito** [terraform-providers/terraform-provider-azurerm#4868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.6
provider.azurerm v1.36.1

### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "ehubns" {
  name                = local.ehubns_name
  location            = local.location
  resource_group_name = local.resource_group_name
  sku                 = local.cond_ehub_ns_sku
  capacity            = var.cod_capacity
  kafka_enabled       = local.kafka
  tags                = "${merge(var.tags, local.tags)}"    

  dynamic "network_rulesets" {
    for_each = local.isstandard
    content {
      default_action = "Deny"
      ip_rule = [
        {
            ip_mask = "199.4.200.130/32"
            action  = "Allow"
        },
        {
            ip_mask = "199.244.162.194/32"
            action  = "Allow"
        }
      ]
    }
  }
}
```

### Expected Behavior

I should be able to configure more than one IP for the Ip_rule block just like the documentation says : https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace.html#ip_rule

### Actual Behavior

If  tried to put it as same as the example that im sharing i get this error:

**_network_rulesets.0.ip_rule: attribute supports 1 item maximum, config has 2 declared._**

The same error appears if i use just one ip_mask and action argument with arrays or count.index.

### Steps to Reproduce

Just use the example that provides terraform or mine but with actual values instead of local ones. 
Just for the record i use the dynamic block to create conditional based on environment since the "network_rulesets" block only can be used when the SKU is set in Standard. 

* #0000

**Comment by devedse** [comment]
@fabiotito @tracypholmes , I'm running into the same issue:

```
Error: network_rulesets.0.ip_rule: attribute supports 1 item maximum, config has 2 declared
```

**Comment by devedse** [comment]
I saw that my comment was marked as off-topic.

Was I wrong in assuming that the issue I'm running into is the same issue as the one in this topic? (If so, could you maybe point me to the place where I can get more information on solving my problem)?

**Comment by tombuildsstuff** [comment]
@devedse we minimize comments which are "+1's" / "I'm also running into this issue" as per the "Community Note" (above) since these mirror the contents of the issue. Since there's a lot of folks subscribed to this repo - we ask instead that folks use the 👍 button to show they're having the same issue too, since this shows the same thing without sending each person a notification

But to your point - yes it's the same issue, this issue's open tracking support for this 🙂

**Comment by prasadker** [comment]
@grayzu Do we have any update on this issue?
