### ISSUE TITLE
Resources are not recreated in a second apply after chaging the SKU of event hub namespace resource

### ISSUE THREAD

**Issue by fabiotito** [terraform-providers/terraform-provider-azurerm#4869]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.6
provider.azurerm v1.36.1

### Affected Resource(s)

* `azurerm_eventhub`
* `azurerm_eventhub_namespace_authorization_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "ehubns" {
  name                = local.ehubns_name
  location            = local.location
  resource_group_name = local.resource_group_name
  sku                 = local.cond_ehub_ns_sku
  capacity            = var.cod_capacity
  kafka_enabled       = local.kafka
  tags                = "${merge(var.tags, local.tags)}"    

}

resource "azurerm_eventhub_namespace_authorization_rule" "ehubrule" {
  name                = local.rule_name
  namespace_name      = azurerm_eventhub_namespace.ehubns.name
  resource_group_name = local.resource_group_name

  listen = true
  send   = false
  manage = false

  depends_on = [azurerm_eventhub_namespace.ehubns]

}

resource "azurerm_eventhub" "ehub" {
  name                = local.ehub_name
  namespace_name      = azurerm_eventhub_namespace.ehubns.name
  resource_group_name = local.resource_group_name
  partition_count     = var.partition_count
  message_retention   = local.message_retention

 depends_on = [azurerm_eventhub_namespace.ehubns]

}

```

### Expected Behavior

After the first apply if i change the "**sku**" value the authorization rule and the event hub instance should recreate along with the new event hub namespace since this one is being replaced.

### Actual Behavior

After a first apply, i do a terraform plan changing the "**sku**" value and terraform shows me that only the azurerm_eventhub_namespace is gonna be recreated and the other two don't. 
this happens even if i use the "depens_on" feature.

Is like terraform is detecting as there is no changes in this other two resources, they dont need to be recreated even if they depends on the Event Hub Namespaces resource.

### Steps to Reproduce

Implement the three resources and then try to execute a Terraform Plan changing the SKU argument. 

* #0000

**Comment by tombuildsstuff** [comment]
hey @fabiotito 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through it appears that the root-cause of this is a bug in Terraform Core where in a Grandparent-Parent-Child resource tree, that when recreating the Parent resource using a field other than `id` doesn't detect that the Child needs recreating.

Since this is a bug in Terraform Core, unfortunately this isn't something that we're able to fix in the Azure Provider directly - and as such I'm going to close this in favour of the upstream issue https://github.com/hashicorp/terraform/issues/24663 - would you mind subscribing to that issue for updates?

Thanks!
