### ISSUE TITLE
Support for Azure SQL Server Managed Identity

### ISSUE THREAD

**Issue by lukerosser** [terraform-providers/terraform-provider-azurerm#4875]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for assigning a managed identity to a SQL server.

### New or Affected Resource(s)

* azurerm_sql_server

```hcl
resource "azurerm_sql_server" "test" {
  name                         = "mysqlserver"
  resource_group_name          = "${azurerm_resource_group.test.name}"
  location                     = "${azurerm_resource_group.test.location}"
  version                      = "12.0"
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"

  identity {
    type = "SystemAssigned"
  }

  tags = {
    environment = "production"
  }
}
```

**Comment by aqche** [comment]
Looks like this issue has been covered by PR #4754

**Comment by tombuildsstuff** [comment]
@aqche thanks for the heads up - this'll ship in 1.37 as such I'm going to close this issue for the moment.

I've assigned this to the 1.37 milestone, so when that's released @hashibot will comment here to let you know when that's available :)

Thanks!
