### ISSUE TITLE
Support for Function App IP Restrictions

### ISSUE THREAD

**Issue by marmarama** [terraform-providers/terraform-provider-azurerm#4878]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This feature request was originally raised and closed in https://github.com/terraform-providers/terraform-provider-azurerm/issues/3229 but the closure was in error.  Support for the ip_restriction block was added to azurerm_app_service but *not* to azurerm_function_app.  Therefore I am opening a new feature request ticket and linking back to the original request.

### New or Affected Resource(s)

azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "global_app_function" {
    name                      = "hub-deployer-${var.deployment_suffix}"
    location                  = "${azurerm_resource_group.main_rg.location}"
    resource_group_name       = "${azurerm_resource_group.main_rg.name}"
    app_service_plan_id       = "${azurerm_app_service_plan.global_app_serviceplan.id}"
    storage_connection_string = "${azurerm_storage_account.global_function_storage.primary_connection_string}"
    https_only                = "true"
    # NOT AVAILABLE FOR FUNCTION APP IN TERRAFORM
    ip_restriction  = {
        ip_address = "65.245.25.32"
        subnet_mask = "255.255.255.255"
    }
}
```

### References
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/3229

**Comment by Gogeta094** [comment]
Hi. Any plans on this? This functionality is important for us.

**Comment by rohrerb** [comment]
@tombuildsstuff  any chance we can get this one prioritized for the next sprint?
