### ISSUE TITLE
failed to delete the subnet due to an internal error

### ISSUE THREAD

**Issue by bingosummer** [terraform-providers/terraform-provider-azurerm#488]
### Terraform Version
`Terraform v0.10.8`

### Affected Resource(s)
- azurerm_subnet
- azurerm_application_gateway

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
https://github.com/bingosummer/bosh-azure-cpi-release/blob/application-gateway/ci/assets/terraform/integration/template.tf

### Output
https://gist.github.com/bingosummer/a2d299f9523965f7a9e23c5cb39ef1ec

### Expected Behavior
The subnet which application gateway belongs to should be deleted.

### Actual Behavior
It failed to delete the subnet due to an internal error.

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

**Comment by bingosummer** [comment]
@sebastus Could you please have a look? Thanks.

**Comment by sebastus** [comment]
Hi, Bin. This has been in the works for a few months. See here: https://github.com/Azure/azure-rest-api-specs/issues/1233. PR #133 depends on it as well.
