### ISSUE TITLE
Azure Front Door Docs use the wrong provider name

### ISSUE THREAD

**Issue by sam-cogan** [terraform-providers/terraform-provider-azurerm#4880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
1.36.0

### Affected Resource(s)

* `azurerm_front_door

### Actual Behavior

The docs for the front door resource state the resource name as azurerm_front_door, however it appears the correct name (the only one that works) is azurerm_frontdoor

### Steps to Reproduce

View docs here [https://www.terraform.io/docs/providers/azurerm/r/front_door.html](https://www.terraform.io/docs/providers/azurerm/r/front_door.html)

**Comment by sam-cogan** [comment]
Looks like this has actually been fixed in the repo on 30th October, but hasn't made it into the actual website yet.

**Comment by tombuildsstuff** [comment]
@sam-cogan thanks for the heads up - since this is fixed in master I'm going to close this issue for the moment, but the fix will ship when v1.37 is released in the near future 👍
