### ISSUE TITLE
Support for state refresh from script

### ISSUE THREAD

**Issue by MarcelT-NL** [terraform-providers/terraform-provider-azurerm#4890]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if you could issue a forced “refresh” at the top of the script, forcing the saved state to be deleted/ignored and recreated from the live environment.

Rationale:

Sometimes a terraform script fails, for whatever reason and you need to delete some assets manually (eg. in the Azure portal).

Being able to have the state forcefully refreshed would solve a lot of manual work.

Also, when using Terraform.io (Cloud), there is no way to run CLI commands so no refresh option. Sometimes you have to delete and recreate the workspace because the state is out of sync with reality and terraform consistently fails when running.

### New or Affected Resource(s)

Terraform state

### Potential Terraform Configuration

New command for scripts:

terraform_state_refresh

**Comment by tombuildsstuff** [comment]
hi @MarcelT-NL 

Thanks for opening this issue.

Since this is a Feature Request for Terraform Core rather than being specific to the Azure Provider - would you [mind re-opening this issue on that repository](https://github.com/hashicorp/terraform/issues) where someone from the Core team should be able to comment?

Thanks!

**Comment by MarcelT-NL** [comment]
Hi Tom,

Yes, I will do that now. Thank you.
