### ISSUE TITLE
Support for Ultra Disk with VMSS

### ISSUE THREAD

**Issue by normseq** [terraform-providers/terraform-provider-azurerm#4892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to be able to map UltraSSD disks to a VMSS , the VMSS needs to be created with the ultra-ssd-enabled flag in CLI
https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create 

az vmss create -n MyVmss -g MyResourceGroup --instance-count 5 --image Win2016Datacenter --data-disk-sizes-gb 2  **--ultra-ssd-enabled  true**

### New or Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
"additional_capabilities": {
				Type:     schema.TypeList,
				Optional: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"ultra_ssd_enabled": {
							Type:     schema.TypeBool,
							Required: true,
							ForceNew: true,
						},
					},
				},
			},
```

### References
**Ultra SSD support for a VM**
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3765 

* #0000

**Comment by tombuildsstuff** [comment]
hi @normseq 

Thanks for opening this issue :)

As outlined in #2807 we're introducing a replacement for the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources in 2.0. Support for this is being worked on and will be available in an opt-in Beta in a 1.x release in the not-too-distant-future - as such I can confirm that support for VM Scale Sets with Ultra SSD's is included in this new resource.

For various reasons we've opted not to backport this back to the existing `azurerm_virtual_machine_scale_set` resource - instead this will only be available via the replacement `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources. However as mentioned above support for these is still being worked on and we're intending on shipping these in an opt-in basis in a 1.x release in the not-too-distant future (we're just working to complete the set of resources to ensure the design is correct, before pushing these out to a larger audience).

As support for this will be added via the new VM Scale Set resources (which have been merged, but are intentionally feature-toggled off at this time) - for the moment I'm going to close this in favour of #2807; where when the remaining new resources have been added we'll post an update describing how you can opt into the Beta and try out these new resources - as such would you mind subscribing to #2807 for updates?

Thanks!
