### ISSUE TITLE
Support for Failed Request Tracing and Detailed Error Message on azurerm_appservice

### ISSUE THREAD

**Issue by yfakariya** [terraform-providers/terraform-provider-azurerm#4902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure App Service on Windows can be enabled Failed Request Tracing and Detailed Error Message for trouble shooting. It is useful to investigate app or configuration errors. It can be enabled via `{app_service_id}/config/logs` as `properties.failedRequestsTracing.enabled=true` and `properties.detailedErrorMessage.enabled=true` in ARM or Azure CLI.

### New or Affected Resource(s)

* azurerm_app_service
* azurerm_app_service_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service" "test" {
  // Existing properties are omitted...
  logs {
    // Existing blocks are omitted...
    enable_failed_request_tracing = true
    enable_detailed_error_message = true
  }
}
```

### References

* Feature description on docs.microsoft.com: https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#log-detailed-errors
* Management API definition (it should be match with ARM model): https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.sitelogsconfig?view=azure-dotnet

**Comment by jackofallops** [comment]
Closing as fixed by #9162
