### ISSUE TITLE
Custom Timeout on State Refreshes

### ISSUE THREAD

**Issue by PSanetra** [terraform-providers/terraform-provider-azurerm#4907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Sometimes Azure APIs are not responding which leads to eventual timeouts during state refreshes. It would be nice if these timeouts could be configurable.

Edit: It seems like the terraform provider is sometimes retrying a request for a while when the API returns 503 as HTTP status. It would also be nice to make this retry count configurable. (I have experienced this when the provider tried to get the state of a Log Analytics workspace via this API: https://docs.microsoft.com/en-us/rest/api/loganalytics/workspaces/get)

**Comment by katbyte** [comment]
Hi @PSanetra, we have added custom timeouts to the majority of the resources. However it is feature flagged off until its release in 2.0. As this is being tracked in #2807 and implemented but not enabled by default i am going to close this issue.
