### ISSUE TITLE
Backend is not using a secure connection

### ISSUE THREAD

**Issue by giggio** [terraform-providers/terraform-provider-azurerm#4912]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

````
Terraform v0.12.12
+ provider.azuread v0.6.0
+ provider.azurerm v1.36.1
````

### Affected Resource(s)

* `azurerm backend`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.36.1"
}
terraform {
  backend "azurerm" {
    storage_account_name = "<REDACTED>"
    container_name       = "tfstate"
    key                  = "terraform.tfstate"
  }
}
```

### Debug Output

This is the result from the log:
https://gist.github.com/giggio/af99a12e8da9840b29ff5906be8674df

It is not showing everything. This is stdout/stderr:

````
Initializing the backend... 
Error: Error inspecting states in the "azurerm" backend:
    storage: service returned error: StatusCode=400, ErrorCode=AccountRequiresHttps, ErrorMessage=The account being accessed does not support http.
RequestId:12379063-601e-0010-027d-9ee7be000000
Time:2019-11-19T02:03:19.8622507Z, RequestInitiated=Tue, 19 Nov 2019 02:03:19 GMT, RequestId=12379063-601e-0010-027d-9ee7be000000, API Version=, QueryParameterName=, QueryParameterValue=
````

### Expected Behavior

The backend should have been created.

### Actual Behavior

The backend was not created.

### Steps to Reproduce

1. Create a storage account and set "Secure Transfer required" to true;
1. Create a .tf file with the contents from the above hcl;
1. Run `terraform init`.

### Important Factoids

As the blob is not being created, it seems that the current backend provider is passing the keys through a unencrypted channel, which is not secure.

**Comment by phekmat** [comment]
Does your SAS token have a `spr` value by any chance? You might be hitting https://github.com/Azure/azure-sdk-for-go/pull/4870

**Comment by giggio** [comment]
The token does not have an `spr` setting. Should I just add `&spr=true` as a temporary workaround?

**Comment by phekmat** [comment]
No, you'd have to regenerate the SAS token with the `spr` field specified as `https`. 

The query params are used when generating signature, so changing any of them will require you to recalculate it. You can see https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas for more details and an example with `spr` specified at the end.

**Comment by giggio** [comment]
Yes, that worked. I'm using `az`, so I had to add `--https-only` to the options:

```bash
az storage container generate-sas \
--https-only \
--subscription $ARM_SUBSCRIPTION_ID \
--permissions acdlrw \
--auth-mode login --as-user \
--account-name $STORAGE_ACCOUNT \
--name $CONTAINER \
--expiry $EXPIRY
````

This is solved to me, do you want to keep it open until terraform updates the Azure SDK version internally?

**Comment by phekmat** [comment]
This probably should be moved/recreated under the main repo https://github.com/hashicorp/terraform/, but I'm not a HashiCorp employee

**Comment by giggio** [comment]
Thank you @phekmat !
