### ISSUE TITLE
Crash when creating azurerm_container_group container with blank string in commands block

### ISSUE THREAD

**Issue by amasover** [terraform-providers/terraform-provider-azurerm#4937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.15
Azurerm 1.36.0

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "cg" {
  name = "container-group"
  location = var.location
  resource_group_name = azurerm_resource_group.rg.name
  ip_address_type = "public"

  dns_name_label = "mycontainergroup"
  os_type = "Linux"
  restart_policy = "OnFailure"

  container {
    name = "name"
    image = "some/image:latest"
    cpu = "1.0"
    memory = "2.0"

    commands = ["", "blah", "blah"]

    ports {
      port = 4141
      protocol = "TCP"
    }

    volume {
      name = azurerm_storage_account.sa.name
      mount_path = "/mnt/certs"
      storage_account_name = azurerm_storage_account.sa.name
      storage_account_key = azurerm_storage_account.sa.primary_access_key
      share_name = azurerm_storage_share.certs.name
    }
  }

  identity {
    type = "SystemAssigned"
  }
}

```

### Debug Output

[relevant stack trace](https://gist.github.com/amasover/90536415a0de51631181b6cfdb923700)

### Expected Behavior

Error message about blank string in `commands` block.

### Actual Behavior

Terraform crashed when applying this config.

### Steps to Reproduce

1. Add blank string at beginning of `commands` block in an `azurerm_container_group` container.
2. Run `terraform apply`
3. Terraform crashes `panic: interface conversion: interface {} is nil, not string`
4. Replace blank string with a non-empty string.
5. Terraform does not crash.

Crash example:

```hcl
commands = ["", "-f", "/dev/null"]
```

Non-crash example:

```hcl
commands = ["tail", "-f", "/dev/null"]
```

**Comment by mbfrahry** [comment]
Hi @amasover, thanks for opening this issue. My first inclination is to prevent an empty string from being passed in but is there a use case for passing an empty string into the command list?

**Comment by r0bnet** [comment]
@mbfrahry i think there is a use case for setting it blank. For example if you're using some tool as entrypoint in the container image and the default command is something you don't want and you just want to get rid of the default one. Then omitting it is not the right choice but rather to override it with an empty string.

**Comment by amasover** [comment]
I had no use case and simply passed an empty string in by accident, intending to pass in a full command. The one @r0bnet brought up sounds valid to me though.

**Comment by mbfrahry** [comment]
@r0bnet, that makes sense to me! I'll see if we can't pass in an empty string when we can't cast to a string and hopefully that'll prevent us from crashing again. Thanks for running across this happy little accident @amasover

**Comment by mbfrahry** [comment]
Alright. So the API doesn't let you pass in an empty string so we'll prevent that from our end as well

The below is from the API
```
The command cannot be empty for container
```

I've got a PR up to fix this and it should make it into the next release. Thanks for opening this again @amasover
