### ISSUE TITLE
Support for SignalR Serverless Mode

### ISSUE THREAD

**Issue by SimonKienzler** [terraform-providers/terraform-provider-azurerm#4945]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The SignalR resource allows for a setting called "service mode" in both the portal and the template manager. It allows to choose between the settings "Default", "Serverless" and "Classic" (see references for more information on those options).

The feature is currently flagged as a preview, but [has been around since march 2019](https://azure.microsoft.com/en-us/blog/real-time-serverless-applications-with-the-signalr-service-bindings-in-azure-functions/). I'd like to be able to set this flag with Terraform as well.

### New or Affected Resource(s)

`azurerm_signalr_service`

### Potential Terraform Configuration

```hcl
resource "azurerm_signalr_service" "example" {
  name                = "tfex-signalr"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"

  sku {
    name     = "Free_F1"
    capacity = 1
  }

  service_mode = "Serverless" # Other options: Default, Classic
}
```

### References
* Similiar proposal for serverless Azure SQL databases: #4185 
* https://github.com/Azure/azure-signalr/blob/dev/docs/faq.md#what-is-the-meaning-of-service-mode-defaultserverlessclassic-how-can-i-choose

I've never worked on a terraform provider before, but if this feature is welcome, I'd give it a shot!

**Comment by brunhil** [comment]
Hi @SimonKienzler , this should be coming in 1.37! 

This was fixed with https://github.com/terraform-providers/terraform-provider-azurerm/pull/4716

**Comment by SimonKienzler** [comment]
Great, thanks @brunhil ! I didn't find anything when searching for "serverless" in the issues and PRs instead of "service_mode", my mistake. Looking forward to using the feature, thank you for implementing it. I'll close this :)
