### ISSUE TITLE
Removing brackets after interpolation warning fails terraform plab

### ISSUE THREAD

**Issue by Zenocolo** [terraform-providers/terraform-provider-azurerm#4949]
Following code cause interpolation warning:

```
resource "azurerm_network_interface" "main" {
  name                = "${var.name}-nic"
  location            = "azurerm_resource_group.main.location"
  resource_group_name = "azurerm_resource_group.main.name"

  ip_configuration {
    name                          = "config1"
    subnet_id                     = "${azurerm_subnet.main.id}"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id          = "${azurerm_public_ip.main.id}"
  }
}
```

Warning:

> Warning: Interpolation-only expressions are deprecated
> 
>   on main.tf line 50, in resource "azurerm_network_interface" "main":
>   50:     subnet_id                     = "${azurerm_subnet.main.id}"
> 
> Terraform 0.11 and earlier required all non-constant expressions to be
> provided via interpolation syntax, but this pattern is now deprecated. To
> silence this warning, remove the "${ sequence from the start and the }"
> sequence from the end of this expression, leaving just the inner expression.
> 
> Template interpolation syntax is still used to construct strings from
> expressions when the template includes multiple interpolation sequences or a
> mixture of literal strings and interpolations. This deprecation applies only
> to templates that consist entirely of a single interpolation sequence.

> Warning: Interpolation-only expressions are deprecated
> 
>   on main.tf line 52, in resource "azurerm_network_interface" "main":
>   52:     public_ip_address_id          = "${azurerm_public_ip.main.id}"
> 
> Terraform 0.11 and earlier required all non-constant expressions to be
> provided via interpolation syntax, but this pattern is now deprecated. To
> silence this warning, remove the "${ sequence from the start and the }"
> sequence from the end of this expression, leaving just the inner expression.
> 
> Template interpolation syntax is still used to construct strings from
> expressions when the template includes multiple interpolation sequences or a
> mixture of literal strings and interpolations. This deprecation applies only
> to templates that consist entirely of a single interpolation sequence.

Removing brackets as described will fail terraform plan:
```
resource "azurerm_network_interface" "main" {
  name                = "${var.name}-nic"
  location            = "azurerm_resource_group.main.location"
  resource_group_name = "azurerm_resource_group.main.name"

  ip_configuration {
    name                          = "config1"
    subnet_id                     = "azurerm_subnet.main.id"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id          = "azurerm_public_ip.main.id"
  }
}
```
Error:

> Error: Can not parse "ip_configuration.0.public_ip_address_id" as a resource id: Cannot parse Azure ID: parse azurerm_public_ip.main.id: invalid URI for request
> 
>   on main.tf line 43, in resource "azurerm_network_interface" "main":
>   43: resource "azurerm_network_interface" "main" {
> 
> 
> 
> Error: Can not parse "ip_configuration.0.subnet_id" as a resource id: Cannot parse Azure ID: parse azurerm_subnet.main.id: invalid URI for request
> 
>   on main.tf line 43, in resource "azurerm_network_interface" "main":
>   43: resource "azurerm_network_interface" "main" {

**Comment by StefanSchoof** [comment]
You need also to remove the `"`.

**Comment by Zenocolo** [comment]
Thanks Stefan, looks like I need a coffee and vscode extension update :) That fixed it indeed!
