### ISSUE TITLE
Assign managed identity to azurerm_policy_assignment

### ISSUE THREAD

**Issue by kevinrosal** [terraform-providers/terraform-provider-azurerm#4950]
Been trying to assign a "Modify" policy in azure and i get this error when running my terraform code: 

Policy assignments must include a resource identity when assigning 'Modify' policy definitions."

can anyone point me to the right direction, clarify or help me how to add an identity to azurerm_policy_assignment? 

resource "azurerm_policy_assignment" "resource-tagpolicyassignment" {
  name                 = "${var.name}"
  scope                = "${var.assignment_scope}"
  policy_definition_id = "${azurerm_policy_set_definition.resource-tagmodifypolicyinitiative.id}"
  description          = "Tag Policy modify for Resources"

  identity = {
      type = "SystemAssigned"

  }
  location             = "Canada Central"
}

**Comment by makramjenayah** [comment]
I got the same error but on PowerShell and to resolve it I added -Location 'eastus' -AssignIdentity.

**Comment by joeyjesky** [comment]
You need to make use of the Identity block like below. Along with inserting the Identity you need to specify a valid location. 

 `  location = "centralus" `
`  identity {
      type = "SystemAssigned"
  }`

List of Valid Locations
`'southafricanorth, southafricawest, uaenorth, australiacentral, australiaeast, australiasoutheast, canadacentral, canadaeast, brazilsouth, centralindia, westindia, southindia, japanwest, japaneast, eastasia, southeastasia, koreacentral, koreasouth, northeurope, westeurope, ukwest, uksouth, switzerlandnorth, germanywestcentral, centralus, northcentralus, eastus, eastus2, southcentralus, westus, westus2, westcentralus, francecentral'`

> An identity block supports the following:
type - (Required) The Managed Service Identity Type of this Policy Assignment. Possible values are SystemAssigned (where Azure will generate a Service Principal for you), or None (no use of a Managed Service Identity).
NOTE: When type is set to SystemAssigned, identity the Principal ID can be retrieved after the policy has been assigned.



[https://www.terraform.io/docs/providers/azurerm/r/policy_assignment.html#identity](url)

**Comment by ArcturusZhang** [comment]
Hi, actually `location` is required (and has a list of acceptable values as listed by @joeyjesky ) when `identity` is set to `SystemAssigned`.

I am working on a PR to ensure this would be check on the side of terraform and also update the doc to include this.

**Comment by ArcturusZhang** [comment]
Hi @kevinrosal and I just found that `location is required when identity is assigned` was documented in the [doc page](https://www.terraform.io/docs/providers/azurerm/r/policy_assignment.html) here.
