### ISSUE TITLE
Shared Image Gallery version

### ISSUE THREAD

**Issue by nicethomaslearngit** [terraform-providers/terraform-provider-azurerm#4957]
This a bug/feature request for Azure Provider
Not  able to list the image versions using

https://www.terraform.io/docs/providers/azurerm/d/shared_image_gallery.html
https://www.terraform.io/docs/providers/azurerm/d/shared_image_version.html
https://www.terraform.io/docs/providers/azurerm/d/shared_image.html

Is there a way to list the image version? If not could you please add this feature?

**Comment by neil-yechenwei** [comment]
@nicethomaslearngit , thanks for opening this issue. I assume it's a feature request and it has been implemented by terraform. See the resource [`azurerm_shared_image_versions`](https://www.terraform.io/docs/providers/azurerm/d/shared_image_versions.html).

**Comment by tombuildsstuff** [comment]
Closing this out since these are now supported
