### ISSUE TITLE
Import terraform import azurerm_kubernetes_cluster.x leads to destroy

### ISSUE THREAD

**Issue by baboune** [terraform-providers/terraform-provider-azurerm#4963]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -v
Terraform v0.12.15
+ provider.azuread v0.6.0
+ provider.azurerm v1.36.1

Your version of Terraform is out of date! The latest version
is 0.12.16. You can update by downloading from https://www.terraform.io/downloads.html
### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
#
# AKS
# 
resource "azurerm_kubernetes_cluster" "prod_aks_isp" {
  
  api_server_authorized_ip_ranges = []
  name                = "prodIspAks"
  location            = data.azurerm_resource_group.isp_rg.location
  resource_group_name = data.azurerm_resource_group.isp_rg.name
  dns_prefix          = "prodIspAksDns"


  agent_pool_profile {    
    name            = "default"
    count           = "6"
    
    enable_auto_scaling = true
    #enable_node_public_ip ?
    min_count           = "2"
    max_count           = "6"
    availability_zones  = []
    #availability_zones  = ["1", "2", "3"]
    # force re-creates
    #max_pods            = 20
    node_taints         = []

    vm_size         = "Standard_D4s_v3"
    os_type         = "Linux"
    os_disk_size_gb = 30

    # Required for advanced networking
    vnet_subnet_id  = data.azurerm_subnet.ecn_subnet.id
    type            = "VirtualMachineScaleSets"
  }

  agent_pool_profile {
    name            = "medium"
    count           = "1"
    
    enable_auto_scaling = true
    #enable_node_public_ip ?
    min_count           = "1"
    max_count           = "1"
    availability_zones  = []
    #availability_zones  = ["1", "2", "3"]
    # force re-creates
    #max_pods            = 20
    node_taints         = []
    vm_size         = "Standard_DS5_v2"
    os_type         = "Linux"
    os_disk_size_gb = 100

    # Required for advanced networking
    vnet_subnet_id  = data.azurerm_subnet.ecn_subnet.id
    type            = "VirtualMachineScaleSets"
  }

  network_profile {
    network_plugin = "azure"
    network_policy = "azure"
    #
    # The following LB setting enables AvailabilityZones
    load_balancer_sku = "standard"
  }

  addon_profile {
    oms_agent {
      enabled = true
      log_analytics_workspace_id = data.azurerm_log_analytics_workspace.isp_log_analytics_workspace.id
    }
  }
  
  role_based_access_control {
    enabled = true

    # Service principals to exchange AD information.
    # See https://github.com/MicrosoftDocs/azure-docs/issues/14627
    azure_active_directory {
      # AD Application Client ID
      client_app_id = data.azuread_application.aad_client_application.application_id

      # AD Application Server ID
      server_app_id     = data.azuread_application.aad_server_application.application_id
      server_app_secret = var.aad_server_application_secret
      tenant_id         = "92e84ceb-fbfd-47ab-be52-080c6b87953f"
    }
  }

  # Service principal used for the AKS cluster to communicate with the Azure platform to 
  # create and manage resources such as networking or storage.
  #
  service_principal {
   client_id     = "f1d31bb3-dde6-43a8-90b9-067d245e20ab" # InServicePerformanceContributor
   client_secret = var.isp_contributor_service_principal_secret
   #client_id     = "52494e6f-7d6e-4a1b-82b1-ca800002c13e" # InServicePerformance AKS Server
   #client_secret = "${var.aad_server_application_secret}"
  }

  tags = {
    Environment = "Production"
  }
  # lifecycle {
  #    ignore_changes = [ 
  #      "kube_admin_config",
  #    ]
  # }
}

```

### Debug Output

https://gist.github.com/baboune/d76e5b74bf550ca2f0c31fc287675daf

### Expected Behavior

"terraform import "followed by a "terrafom plan" should propose a plan that do not require to delete the resource.  It should propose in place changes only.

### Actual Behavior

Terraform wants to destroy and re-create the resource in this case the whole K8s cluster.

### Steps to Reproduce

1. `terraform import azurerm_kubernetes_cluster.prod_aks_isp /subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourcegroups/BusInServicePerformanceProdUs-vnet-rg/providers/Microsoft.ContainerService/managedClusters/prodIspAks`
2. `terraform plan`-> Plan: 1 to add, 0 to change, 1 to destroy.

### References

* #0000

**Comment by atikhono** [comment]
I'm experiencing exactly this problem as well. RBAC-enabled cluster, single node pool and with custom node subnet.

**Comment by baboune** [comment]
The issue seems to be that Terraform wants to have a default node pool at all costs even when it is not there.

This is the info from "az aks list":

```
✗ az aks list
[
  {
    "aadProfile": {
      "clientAppId": "1a04faee-4761-44cb-8896-c4215d383d4f",
      "serverAppId": "52494e6f-7d6e-4a1b-82b1-ca800002c13e",
      "serverAppSecret": null,
      "tenantId": "92e84ceb-fbfd-47ab-be52-080c6b87953f"
    },
    "addonProfiles": {
      "omsagent": {
        "config": {
          "loganalyticsworkspaceresourceid": "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourcegroups/businserviceperformanceprodus-vnet-rg/providers/microsoft.operationalinsights/workspaces/businserviceperformanceproduslog"
        },
        "enabled": true
      }
    },
    "agentPoolProfiles": [
      {
        "availabilityZones": null,
        "count": 7,
        "enableAutoScaling": true,
        "enableNodePublicIp": null,
        "maxCount": 8,
        "maxPods": 15,
        "minCount": 2,
        "name": "average",
        "nodeTaints": null,
        "orchestratorVersion": "1.14.8",
        "osDiskSizeGb": 64,
        "osType": "Linux",
        "provisioningState": "Succeeded",
        "scaleSetEvictionPolicy": null,
        "scaleSetPriority": null,
        "type": "VirtualMachineScaleSets",
        "vmSize": "Standard_D8s_v3",
        "vnetSubnetId": "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourceGroups/BusInServicePerformanceProdUs-vnet-rg/providers/Microsoft.Network/virtualNetworks/ecn-BusInServicePerformanceProdUs-eastus/subnets/ecn-subnet-1"
      },
      {
        "availabilityZones": null,
        "count": 1,
        "enableAutoScaling": false,
        "enableNodePublicIp": null,
        "maxCount": null,
        "maxPods": 30,
        "minCount": null,
        "name": "default",
        "nodeTaints": null,
        "orchestratorVersion": "1.14.8",
        "osDiskSizeGb": 30,
        "osType": "Linux",
        "provisioningState": "Succeeded",
        "scaleSetEvictionPolicy": null,
        "scaleSetPriority": null,
        "type": "VirtualMachineScaleSets",
        "vmSize": "Standard_D4s_v3",
        "vnetSubnetId": "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourceGroups/BusInServicePerformanceProdUs-vnet-rg/providers/Microsoft.Network/virtualNetworks/ecn-BusInServicePerformanceProdUs-eastus/subnets/ecn-subnet-1"
      }
    ],
    "apiServerAccessProfile": null,
    "dnsPrefix": "prodIspAksDns",
    "enablePodSecurityPolicy": false,
    "enableRbac": true,
    "fqdn": "prodispaksdns-89503f4a.hcp.eastus.azmk8s.io",
    "id": "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourcegroups/BusInServicePerformanceProdUs-vnet-rg/providers/Microsoft.ContainerService/managedClusters/prodIspAks",
    "identity": null,
    "kubernetesVersion": "1.14.8",
    "linuxProfile": null,
    "location": "eastus",
    "maxAgentPools": 8,
    "name": "prodIspAks",
    "networkProfile": {
      "dnsServiceIp": "10.0.0.10",
      "dockerBridgeCidr": "172.17.0.1/16",
      "loadBalancerProfile": {
        "effectiveOutboundIps": [
          {
            "id": "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourceGroups/mc_businserviceperformanceprodus-vnet-rg_prodispaks_eastus/providers/Microsoft.Network/publicIPAddresses/7a3cf2c9-8f98-42a7-a2ca-7e69a7491a6f",
            "resourceGroup": "mc_businserviceperformanceprodus-vnet-rg_prodispaks_eastus"
          }
        ],
        "managedOutboundIps": {
          "count": 1
        },
        "outboundIpPrefixes": null,
        "outboundIps": null
      },
      "loadBalancerSku": "Standard",
      "networkPlugin": "azure",
      "networkPolicy": "azure",
      "podCidr": null,
      "serviceCidr": "10.0.0.0/16"
    },
    "nodeResourceGroup": "MC_BusInServicePerformanceProdUs-vnet-rg_prodIspAks_eastus",
    "privateFqdn": null,
    "provisioningState": "Succeeded",
    "resourceGroup": "BusInServicePerformanceProdUs-vnet-rg",
    "servicePrincipalProfile": {
      "clientId": "f1d31bb3-dde6-43a8-90b9-067d245e20ab"
    },
    "tags": {
      "Environment": "Production"
    },
    "type": "Microsoft.ContainerService/ManagedClusters",
    "windowsProfile": null
  }
]```

But terraform wants to create the following:

```

      ~ agent_pool_profile {
          ~ availability_zones    = [] -> (known after apply)
          ~ count                 = 7 -> (known after apply)
          + dns_prefix            = (known after apply)
          ~ enable_auto_scaling   = true -> (known after apply)
          ~ enable_node_public_ip = false -> (known after apply)
          ~ fqdn                  = "prodispaksdns-89503f4a.hcp.eastus.azmk8s.io" -> (known after apply)
          ~ max_count             = 8 -> (known after apply)
          ~ max_pods              = 15 -> (known after apply)
          ~ min_count             = 2 -> (known after apply)
          ~ name                  = "average" -> (known after apply)
          ~ node_taints           = [] -> (known after apply)
          ~ os_disk_size_gb       = 64 -> (known after apply)
          ~ os_type               = "Linux" -> (known after apply)
          ~ type                  = "VirtualMachineScaleSets" -> (known after apply)
          ~ vm_size               = "Standard_D8s_v3" -> (known after apply)
          ~ vnet_subnet_id        = "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourceGroups/BusInServicePerformanceProdUs-vnet-rg/providers/Microsoft.Network/virtualNetworks/ecn-BusInServicePerformanceProdUs-eastus/subnets/ecn-subnet-1" -> (known after apply)
        }
      - agent_pool_profile {
          - availability_zones    = [] -> null
          - count                 = 1 -> null
          - enable_auto_scaling   = false -> null
          - enable_node_public_ip = false -> null
          - fqdn                  = "prodispaksdns-89503f4a.hcp.eastus.azmk8s.io" -> null
          - max_count             = 0 -> null
          - max_pods              = 30 -> null
          - min_count             = 0 -> null
          - name                  = "default" -> null
          - node_taints           = [] -> null
          - os_disk_size_gb       = 30 -> null
          - os_type               = "Linux" -> null
          - type                  = "VirtualMachineScaleSets" -> null
          - vm_size               = "Standard_D4s_v3" -> null
          - vnet_subnet_id        = "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourceGroups/BusInServicePerformanceProdUs-vnet-rg/providers/Microsoft.Network/virtualNetworks/ecn-BusInServicePerformanceProdUs-eastus/subnets/ecn-subnet-1" -> null
        }

      - default_node_pool {
          - availability_zones    = [] -> null
          - enable_auto_scaling   = true -> null
          - enable_node_public_ip = false -> null
          - max_count             = 8 -> null
          - max_pods              = 15 -> null
          - min_count             = 2 -> null
          - name                  = "average" -> null # forces replacement
          - node_count            = 7 -> null
          - node_taints           = [] -> null
          - os_disk_size_gb       = 64 -> null
          - type                  = "VirtualMachineScaleSets" -> null
          - vm_size               = "Standard_D8s_v3" -> null # forces replacement
          - vnet_subnet_id        = "/subscriptions/8f818c9a-dfd8-41f0-b390-ff195bb08789/resourceGroups/BusInServicePerformanceProdUs-vnet-rg/providers/Microsoft.Network/virtualNetworks/ecn-BusInServicePerformanceProdUs-eastus/subnets/ecn-subnet-1" -> null # forces replacement
        } 
```

And that is with or without defining the node pools as an external object `azurerm_kubernetes_cluster_node_pool`:

```
resource "azurerm_kubernetes_cluster_node_pool" "average" {
  name                  = "average"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.prod_aks_isp.id
  vm_size               = "Standard_D8s_v3"
  #node_count            = 7

  enable_auto_scaling   = true
  enable_node_public_ip = false
  
  min_count           = "1"
  max_count           = "8"
  availability_zones  = []
  #availability_zones  = ["1", "2", "3"]
  # force re-creates
  max_pods            = 15
  node_taints         = []

  os_type         = "Linux"
  os_disk_size_gb = 64

  # Required for advanced networking
  vnet_subnet_id  = data.azurerm_subnet.ecn_subnet.id
}

resource "azurerm_kubernetes_cluster_node_pool" "default" {
  name                  = "default"
  availability_zones  = []
  kubernetes_cluster_id = azurerm_kubernetes_cluster.prod_aks_isp.id
  vm_size               = "Standard_D4S_v3"
  node_count            = 1
  enable_auto_scaling   = true
  enable_node_public_ip = false

  max_pods        = 30

  node_taints     = []

  os_type         = "Linux"
  os_disk_size_gb = 30

  # Required for advanced networking
  vnet_subnet_id  = data.azurerm_subnet.ecn_subnet.id
}
```

In short, it is impossible to import an AKS cluster with the Terraform import command.

**Comment by baboune** [comment]
My latest experiments were done with 
✗ terraform providers
.
├── provider.azuread =0.7.0
└── provider.azurerm =1.42.0

How to import an AKS cluster into terraform?

**Comment by atikhono** [comment]
> How to import an AKS cluster into terraform?

terraform import azurerm_kubernetes_cluster.default (whatever the cluster is known in your terraform code) <azure resource id>

**Comment by baboune** [comment]
@atikhono That does import a cluster, but then it generates the above problem.

**Comment by atikhono** [comment]
> @atikhono That does import a cluster, but then it generates the above problem.

In my case the behaviour is exactly the same. I can remove my cluster from the state, then import it again and still have the issue.

**Comment by baboune** [comment]
The problem is most likely tied to the ongoing changes with "agent_pool_profile".

```
Warning: "agent_pool_profile": [DEPRECATED] This has been replaced by `default_node_pool` and will be removed in version 2.0 of the AzureRM Provider

  on aks.tf line 4, in resource "azurerm_kubernetes_cluster" "prod_aks_isp":
   4: resource "azurerm_kubernetes_cluster" "prod_aks_isp" {

```

Two problems:
1) terraform azurerm_kubernetes_cluster expects a "default_node_pool" while that is optional.
2) It selects one of the "agent_pool_profile" and decides it is the "default_node_pool".
3) the terraform import command will import the "default_node_pool" and "agent_pool_profile" even though those are deprecated.

Lots of issues.

Any guides on how I could place back the above "az aks" cluster back under terraform control?

**Comment by tombuildsstuff** [comment]
hi @baboune 

Thanks for opening this issue - apologies for the delayed response here!

In version 1.37 of the Azure Provider the `azurerm_kubernetes_cluster` resource went through a bunch of changes to account for the way the API now works. Due to this the `agent_pool_profile` block has been deprecated (and removed in 2.0) and replaced by the `default_node_pool` block and the separate `azurerm_kubernetes_cluster_node_pool` resource.

The `agent_pool_profile` block has be removed in 2.0 - as such you'd need to switch over to the `default_node_pool` block instead:

```
resource "azurerm_kubernetes_cluster" "test" {
   # ...
   
   default_node_pool { ... }
}
```

At which point additional node pools can be defined using the `azurerm_kubernetes_cluster_node_pool` resource which should resolve this. Since this should be fixed from moving from the older `agent_pool_profile` block to the newer approach - I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look.

Thanks!
