### ISSUE TITLE
azurerm_kubernetes_cluster does not support labels in an agent_pool_profile

### ISSUE THREAD

**Issue by spanktar** [terraform-providers/terraform-provider-azurerm#4968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is possible to apply k8s labels to a node pool with the Azure CLI, but not with Terraform.  `node_taints` are available, which is great, but we use a combination of taints and label matching to place pods. It would be great to add `node_labels` in the same style as `node_taints`.

**Comment by patrickbsf** [comment]
Thanks for reporting this and I agree this is large omission.
Pods with nodeSelectors to have them only run on certain labeled nodes is a critical requirement for node pool configuration.
This is needed for the new azurerm_kubernetes_cluster_node_pool resource type as well as the default/agent pool profiles in the cluster resource.

**Comment by albertocsm** [comment]
+1
i was really not expecting this...

**Comment by dintel** [comment]
Submitted PR that adds support of node_labels in relevant resources.
