### ISSUE TITLE
azurerm_key_vault_secret creation works but running into 403 error when destroying...

### ISSUE THREAD

**Issue by Zenocolo** [terraform-providers/terraform-provider-azurerm#4971]
Hi all,

Checked for the last 4h all communities and issue logs, but didnt find solution. With the following code I can create Azure Key Vault and generate a secret, however I can not destroy my key_vault since I run into 403:

```
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "main" {
  name     = "${var.name}-rg"
  location = var.location
}

resource "random_password" "admin_pwd" {
  length = 24
  special = true
}


resource "azurerm_key_vault" "main" {
  name                        = "zenotestvault23"
  location                    = azurerm_resource_group.main.location
  resource_group_name         = azurerm_resource_group.main.name
  enabled_for_disk_encryption = true
  enabled_for_deployment      = true
  enabled_for_template_deployment = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name = "standard"

  tags = {
    environment = "Production"
  }
}

resource "azurerm_key_vault_access_policy" "main" {
  key_vault_id = azurerm_key_vault.main.id

  tenant_id = data.azurerm_client_config.current.tenant_id
  object_id = data.azurerm_client_config.current.service_principal_application_id 

  secret_permissions = [
    "list", "get", "delete", "set", "backup", "purge", "recover", "restore",
  ]
}

resource "azurerm_key_vault_access_policy" "second" {
  key_vault_id = azurerm_key_vault.main.id

  tenant_id = data.azurerm_client_config.current.tenant_id
  object_id = data.azurerm_client_config.current.service_principal_object_id

  secret_permissions = [
    "list", "get", "delete", "set", "backup", "purge", "recover", "restore",
  ]
}

resource "azurerm_key_vault_secret" "main" {
  name         = "vm-secret"
  value        = random_password.admin_pwd.result
  key_vault_id = azurerm_key_vault.main.id
}
```

Here is the destroy error:
`Error: keyvault.BaseClient#DeleteSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied. Caller was not found on any access policy.\r\nCaller: appid=xxx;oid=xxx;numgroups=0;iss=https://sts.windows.net/xxx/\r\nVault: zenotestvault23;location=centralus" InnerError={"code":"AccessDenied"`

Can someone help me with this? (I read somewhere that access_policy needs to be assigned for service_principal_object_id and service_principal_application_id, but didnt help in my case)

Thanks

**Comment by Zenocolo** [comment]
Checking on the portal I realized that Terraform deletes first the policy and is then not able to delete the password, I guess this is a bug?

However, when defining access_policy in the key_vault, then the destroy order seems to be right (this works for me at least):

```
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "main" {
  name     = "${var.name}-rg"
  location = var.location
}

resource "random_password" "admin_pwd" {
  length  = 24
  special = true
}


resource "azurerm_key_vault" "main" {
  name                            = "zenotestvault23"
  location                        = azurerm_resource_group.main.location
  resource_group_name             = azurerm_resource_group.main.name
  enabled_for_disk_encryption     = true
  enabled_for_deployment          = true
  enabled_for_template_deployment = true
  tenant_id                       = data.azurerm_client_config.current.tenant_id
  sku_name                        = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.service_principal_object_id

    secret_permissions = [
      "list", "get", "delete", "set", "backup", "purge", "recover", "restore",
    ]
  }
  tags = {
    environment = var.name
  }
}

resource "azurerm_key_vault_secret" "main" {
  name         = "vm-secret"
  value        = random_password.admin_pwd.result
  key_vault_id = azurerm_key_vault.main.id
}
```

**Comment by jaxidian** [comment]
In case this helps anybody, I am using a `depends_on` in my `azurerm_key_vault_secret` resources to handle this:

```
  depends_on   = [azurerm_key_vault_access_policy.permissions]
```

**Comment by tombuildsstuff** [comment]
hi @Zenocolo 

Thanks for opening this issue / apologies for the delayed response here!

> Checking on the portal I realized that Terraform deletes first the policy and is then not able to delete the password, I guess this is a bug?

This is more a dependency issue, since there's no dependency between the Key Vault Access Policy and the Key Vault Secret, Terraform believes it can provision/destroy them both in parallel - whereas the Key Vault Access Policy is required to make changes to the Key Vault Key in this instance - as such there needs to be a dependency between the two.

As @jaxidian has mentioned you can achieve this via a depends_on, which makes an explicit dependency like so:

```

resource "azurerm_key_vault" "test" { ... }

resource "azurerm_key_vault_access_policy" "test" { ... }

resource "azurerm_key_vault_key" "test" {
  # ...

  depends_on   = [azurerm_key_vault_access_policy.test]
}
```

Alternatively if you know the Access Policies required for the Key Vault ahead of time, you can nest them within the `azurerm_key_vault` resource and this shouldn't be an issue (since they'll be created before/removed after the Key Vault Key's been created/destroyed) - would you be able to take a look and see if that approach works for you?

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
