### ISSUE TITLE
Subnet NSG deprecation

### ISSUE THREAD

**Issue by OffColour** [terraform-providers/terraform-provider-azurerm#4983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Provider 1.37

### Affected Resource(s)

azurerm_subnet_network_security_group_association
azurerm_subnet

### Expected Behavior

Terraform apply gives a warning that network_security_group_id has been deprecated and to ALSO use azurerm_subnet_network_security_group_association ready for when the change is implemented.

### Actual Behavior

Terraform apply gives a warning that network_security_group_id has been deprecated and to use azurerm_subnet_network_security_group_association instead.
This results in the the NSG being removed from the subnet, reapplied on a second run, removed on a third and so on.

### Steps to Reproduce

Use azurerm_subnet_network_security_group_association without network_security_group_id in subnet

### Important Factoids

The documentation on this was improved on several months ago, but the Terraform message itself should also reflect this as it could lead to someone making the recommended change and removing the NSGs from their subnets.

**Comment by djfilipovic** [comment]
I confirm, I am having this issue right now as well, issue is present both in 1.36 and 1.37. 
Steps to reproduce are correct.

**Comment by ausfestivus** [comment]
Ping @tombuildsstuff unsure if this issue is on your radar for a fix soon.
Its a mind-bendingly annoying thing to triage when you hit it and has the potential to impact a lot of dependant widgets.

**Comment by tombuildsstuff** [comment]
Fixed via #5801
