### ISSUE TITLE
Support multi-versions of documentation for each resource

### ISSUE THREAD

**Issue by metacpp** [terraform-providers/terraform-provider-azurerm#499]
### Terraform Version
N/A. Documentation issue.

### Affected Resource(s)
Documentations for all the resources.

### Expected Behavior
1. Limited the version scope for documentation of each resource.
2. Keep old versions of documentations in the case some users don't like to upgrade provider to latest all the time(mature product team will lock the version of any dependency to avoid regression issue).

### Actual Behavior
No any provider information on the documentation, you can only assume it's for latest released provider.

### Steps to Reproduce
Visit any resource page at: https://www.terraform.io/docs/providers/azurerm/index.html

**Comment by tombuildsstuff** [comment]
Hi @metacpp 

Thanks for opening this issue.

This is a complicated issue for a number of reasons - primarily to do with the way we currently deploy the website - but it's something we're thinking about. Given this affects the whole of Terraform (both Core and the Providers) - I'm going to suggest we close this issue [in favour of one being tracked on Terraform Core](https://github.com/hashicorp/terraform/issues/12941).

That said - we tag each version of Terraform Core and each Provider using Github Releases - for instance [here's v0.3.2 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/tree/v0.3.2) - which contains the docs in the `website` folder. Whilst this isn't ideal, it's a solution to this issue for the moment until the issue mentioned above is resolved.

Thanks!
