### ISSUE TITLE
Add Function App support for client_cert_enabled for turning on Incoming client certificates

### ISSUE THREAD

**Issue by ben-burton** [terraform-providers/terraform-provider-azurerm#5006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add `client_cert_enabled` argument support the same as in azurerm_app_service

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "example" {
  name                      = "test-azure-functions"
  location                  = azurerm_resource_group.example.location
  resource_group_name       = azurerm_resource_group.example.name
  app_service_plan_id       = azurerm_app_service_plan.example.id
  storage_connection_string = azurerm_storage_account.example.primary_connection_string
  client_cert_enabled       = true
}
```

**Comment by alhazem** [comment]
Any updates on this, or any workarounds?

**Comment by Japeth** [comment]
Any updates on this?  This was submitted over a year ago, and not even an acknowledgement of the issue.

**Comment by mcalik77** [comment]
Any updates on this ?
