### ISSUE TITLE
Support for Azure files backup in Recovery Service Vault

### ISSUE THREAD

**Issue by Oicho** [terraform-providers/terraform-provider-azurerm#5026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently azure files in recovery service vault is in preview  and should soon be in GA. Currently terraform does not support this.

### New or Affected Resource(s)

* azurerm_recovery_services_vault
* azurerm_storage_share

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_recovery_services_protection_policy_file_share" "" {
  name                = "fs-recovery-vault-policy"
  resource_group_name = "${azurerm_resource_group.example.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.example.name}"

  timezone = "UTC"

  backup {
    time      = "23:00"
  }

  retention_range = 10
}

resource "azurerm_recovery_services_protected_file_share" "XXXX" {
  resource_group_name = "${azurerm_resource_group.example.name}"
  recovery_vault_name = "${azurerm_recovery_services_vault.example.name}"
  source_storage_account_id        = "${azurerm_virtual_machine.example.id}"
  source_file_share_name = "share1"
  backup_policy_id    = "${azurerm_recovery_services_protection_policy_vm.example.id}"
}

```

**Comment by tombuildsstuff** [comment]
fixed via #5213 - thanks @sean-nixon :)
