### ISSUE TITLE
New Data Source: azurerm_application_gateway

### ISSUE THREAD

**Issue by sephross** [terraform-providers/terraform-provider-azurerm#5030]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_1.37.0

### Potential Terraform Configuration

```hcl
data "azurerm_application_gateway" "main" {
  name                = var.appgw_name
  resource_group_name = var.rg
}
```

### References

* #0000

**Comment by JorTurFer** [comment]
Any news about this?

**Comment by AlexSH001** [comment]
I am also looking for a data source for checking if an application gateway/dns record set resource is ready. 
So that some scripts can go ahead to do the steps with API calls according to this data source information.

**Comment by reddyavinash5** [comment]
Is this available ? I still get azurerm does not support data source
"azurerm_application_gateway" error with latest version

**Comment by jozephp** [comment]
This would be a good to have solution to have appgateway refer as data source

**Comment by petems** [comment]
Started a WIP on adding an azurerm_application_gateway data source 👍 https://github.com/terraform-providers/terraform-provider-azurerm/pull/10268
