### ISSUE TITLE
azurerm_network_interface does not change dns_servers back to default

### ISSUE THREAD

**Issue by dcfsc** [terraform-providers/terraform-provider-azurerm#5055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.17
+ provider.azurerm v1.37.0

### Affected Resource(s)

* `azurerm_network_interface`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "azurerm_network_interface_issue_rg"
  location = "West US"
}

resource "azurerm_virtual_network" "example" {
  name                = "azurerm_network_interface_issue_vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "asubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_public_ip" "example" {
  name                = "azurerm_network_interface_issue_pip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Dynamic"
}

resource "azurerm_network_interface" "example" {
  name                = "azurerm_network_interface_issue_nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.example.id
  }
//  dns_servers = ["172.26.137.135", "168.63.129.16"]
}

resource "azurerm_virtual_machine" "example" {
  name                  = "azurerm_network_interface_issue-vm"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  network_interface_ids = [azurerm_network_interface.example.id]
  vm_size               = "Standard_DS1_v2"
  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true
  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
  storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  os_profile {
    computer_name  = "hostname"
    admin_username = "testadmin"
    admin_password = "Password1234!"
  }
  os_profile_linux_config {
    disable_password_authentication = false
  }
}

provider "azurerm" {
  version = "=1.37.0" // 04 OCT  2019
}
```

This is basically the demo program from `azurerm_network_interface` with a public IP added so I could login and test the DNS settings.

### Expected Behavior

After adding a DNS server successfully, commenting out the `dns_servers` attribute should remove the DNS servers from the NIC.

### Actual Behavior

The DNS servers setting was untouched.

#### Create the initial system

The code contains DNS servers settings:
```
  dns_servers = ["172.26.137.135", "168.63.129.16"]
```
Create the infrastructure:
```
$ terraform apply
```
The infrastructure is created with a DNS servers setting.
```
$ terraform show
# azurerm_network_interface.example:
resource "azurerm_network_interface" "example" {
    dns_servers                   = [
        "168.63.129.16",
        "172.26.137.135",
    ]
```
Planning shows no change pending
```
$ terraform plan
...
No changes. Infrastructure is up-to-date.
```
DNS in target VM is correct:
```
$ cat /etc/resolv.conf
nameserver 168.63.129.16
nameserver 172.26.137.135
```
#### Remove the DNS setting

Now comment out `dns_servers`
```
 // dns_servers = ["172.26.137.135", "168.63.129.16"]
```
Plan -- should show changes
```
$ terraform plan
...
No changes. Infrastructure is up-to-date.
```
Try apply
```
$ tf apply
...
/XXXX/resourceGroups/azurerm_network_interface_issue_rg/providers/Microsoft.Compute/virtualMachines/azurerm_network_interface_issue-vm]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
DNS in target VM is unchanged:
```
$ cat /etc/resolv.conf
nameserver 168.63.129.16
nameserver 172.26.137.135
```

#### Is the problem a missing element?

Perhaps a missing element says "leave it alone" vs "remove it"

Change to:
```
 dns_servers = []
```
Plan
```
$ terraform plan
...
Terraform will perform the following actions:

  # azurerm_network_interface.example will be updated in-place
  ~ resource "azurerm_network_interface" "example" {
      ~ dns_servers                   = [
          - "168.63.129.16",
          - "172.26.137.135",
        ]
```
Apply the change
```
$ terraform apply
...
   subnet_id  = "/subscriptions/XXXX/resourceGroups/azurerm_network_interface_issue_rg/providers/Microsoft.Network/virtualNetworks/azurerm_network_interface_issue_vnet/subnets/asubnet"
        }
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

#### Conclusion

I expect that the default setting would be used when the `dns_servers` element is removed, which should restore the DNS settings to the Azure default. 

If this is indeed expected behavior, a note in the documentation would be helpful:

* `dns_servers` - (Optional) List of DNS servers IP addresses to use for this NIC, overrides the VNet-level server list. If this setting was applied previously, one must use `dns_servers = []` to restore the default Azure DNS servers.

### References

[azurerm_network_interface](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html) doc

* #0000

**Comment by tombuildsstuff** [comment]
hi @dcfsc 

Thanks for opening this issue / apologies for the delayed response here!

The DNS Servers for a Network Interface can be set either at the Virtual Network/Subnet level and/or on the Network Interface, in which case they'll override this. In order to be able to model this in Terraform the field needs to be `Computed` which means that if no value's specified we'll use the value provided by the API. This means that to switch back to using the defaults you'd need to make this:

```
dns_servers = []
```

Would you be able to take a look and see if that works for you? Since this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by dcfsc** [comment]
hi @tombuildsstuff , I think I found the same fix that you offer.

But my thought was:

```
If this is indeed expected behavior, a note in the documentation would be helpful:

dns_servers - (Optional) List of DNS servers IP addresses to use for this NIC, overrides
the VNet-level server list. If this setting was applied previously, one must use 
dns_servers = [] to restore the default Azure DNS servers.
```
Perhaps this wording is not correct, but mentioning the "workaround" might be helpful.
