### ISSUE TITLE
Extend azurerm_monitor_metric_alert to support availability test alerts

### ISSUE THREAD

**Issue by dan-overton** [terraform-providers/terraform-provider-azurerm#5063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `azurerm_monitor_metric_alert` resource provides support for normal metric alerts, e.g. https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-create-templates#template-for-a-simple-static-threshold-metric-alert

but does not support availability test alerts, e.g.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-create-templates#template-for-a-availability-test-along-with-availability-test-alert

Both of these are of type 'Microsoft.Insights/metricAlerts', but have very different properties.

Importing an existing Availability Test Alert into `azurerm_monitor_metric_alert` results in an imported object with almost no properties populated. 

Would it be possible to extend `azurerm_monitor_metric_alert` to support this, or create a new resource to cover this use case? Happy to provide more info if required.

### New or Affected Resource(s)

* azurerm_monitor_metric_alert
* azurerm_application_insights_web_test

### Potential Terraform Configuration

None

### References

* Potentially blocked by https://github.com/terraform-providers/terraform-provider-azurerm/issues/3719 as Availability Test Alerts use multiple scopes
* https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-create-templates

**Comment by alex-3sr** [comment]
Hi,

Diving since few hours, you save my night :) OK, I was like stupid to integrate "Microsoft.Azure.Monitor.WebtestLocationAvailabilityCriteria" in criteria, but no options I found to get this. So OK, by reading you I understand that it's not possible at this time (unfortunately), so I'll workaround it tommorow in other way ^^

Thanks,
Alex

**Comment by magodo** [comment]
As #7159 has been merged (which adds the support for web availability test), closing this issue for now.
