### ISSUE TITLE
azurerm_iothub does not remove endpoints and routes

### ISSUE THREAD

**Issue by ukphillips** [terraform-providers/terraform-provider-azurerm#5065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.9
+ provider.azurerm v1.37.0

### Affected Resource(s)

* `azurerm_iothub`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub" "module" {
  name                = "testiothubxyz"
  resource_group_name = "test-fixture-sandbox"
  location            = "eastus2"

  sku {
    name     = "S1"
    tier     = "Standard"
    capacity = "1"
  }

endpoint {
    type              = "AzureIotHub.EventHub"
    connection_string = "XXXXXXXXXXXXXXXX"
    name              = "telemetry"
  }

  route {
    name           = "telemetry-eventhub"
    source         = "DeviceMessages"
    condition      = "true"
    endpoint_names = ["telemetry"]
    enabled        = true
  } 

}
```
followed by:
```hcl

resource "azurerm_iothub" "module" {
  name                = "testiothubxyz"
  resource_group_name = "test-fixture-sandbox"
  location            = "eastus2"

  sku {
    name     = "S1"
    tier     = "Standard"
    capacity = "1"
  }
}
```

### Debug Output
N/A

### Expected Behavior

Expected IoT hub created with endpoint and route. Followed by the next run removing the endpoint and route

### Actual Behavior

Terraform did not detect any changes on the second run, and left existing route/endpoint in place

### Steps to Reproduce

1. `terraform apply` first block
1. `terraform apply` second block

### Important Factoids

This appears to be the case across all endpoint and route types event hub, service bus, etc.

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems terraform doesn't detect the change since there is computed attribute on properties "endpoint" and "route". So I made a [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8028)for it.
