### ISSUE TITLE
Descriptive validation related error messages

### ISSUE THREAD

**Issue by lucashuet93** [terraform-providers/terraform-provider-azurerm#5070]
In deploying an API management service, I tried using the example resource blocks from the api_management resource [docs](https://www.terraform.io/docs/providers/azurerm/r/api_management.html). If you don't change the name of the service from "example-apim", the deployment fails with the message:

"Error creating/updating API Management Service "example-apim" (Resource Group "example-resources"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>"

A more descriptive error message with a reason for deployment failure would be helpful, assuming Azure throws a descriptive error itself.

**Repro Steps**
- Initialize new Terraform project
- Create main.tf file with example usage from the api_management resource [docs](https://www.terraform.io/docs/providers/azurerm/r/api_management.html)
- Plan and apply the changes
- Observe the error

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by vindupuri** [comment]
I'm also facing the same issue while using the azure APIM docs provided in terraform.io. Is there any resolution to it.

**Comment by manavalan619** [comment]
I am also   facing the same issue on terraform.

**Comment by naincypriya2206** [comment]
am getting error as resource already exists. what error response code already updated?
`Error: creating/updating API Management Service "example-apim" (Resource Group "example-resources"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceAlreadyExists" Message="Api service already exists: example-apim"`

you should update the name of your apim as the it should be unique value. example-apim already exists.
name                = "example-apim"

**Comment by gighead** [comment]
Facing the same issue 

`Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>`

**Comment by manicminer** [comment]
Hi, thanks for reporting this. Unfortunately the error messages you see are the same errors the provider receives from the service API. If the error is blank, there's very little that we can infer. As such there isn't anything we can do to improve the clarity of the failure message here.
