### ISSUE TITLE
azurerm_policy_assignment system assigned identity missing location

### ISSUE THREAD

**Issue by pscevt** [terraform-providers/terraform-provider-azurerm#5076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.15
+ provider.azurerm v1.36.1

### Affected Resource(s)

* azurerm_policy_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_policy_assignment" "pa-required-tags" {
  name                 = "pa-required-tags"
  scope                = azurerm_management_group.mg-managed.id
  policy_definition_id = azurerm_policy_set_definition.polset-required-tags.id
  display_name         = "Required tags for managed subscriptions"
  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output

https://gist.githubusercontent.com/pscevt/afbc0c9760c9031b35d5c31190240c73/raw/6f2584a32f28f89925ad833d367a49ef2b14df00/gistfile1.txt

### Expected Behavior

A managed identity should be created

### Actual Behavior

A managed identity needs a location, which is not supported in the azurerm_policy_assignment module

### Steps to Reproduce

Use config similar to the above

### References

* #0000

**Comment by anwather** [comment]
It's in the documentation at https://www.terraform.io/docs/providers/azurerm/r/policy_assignment.html 

> location - (Optional) The Azure location where this policy assignment should exist. This is required when an Identity is assigned. Changing this forces a new resource to be created.

**Comment by tombuildsstuff** [comment]
As mentioned above this is available via the `location` field - closing.
