### ISSUE TITLE
Container Groups -> output service principal id

### ISSUE THREAD

**Issue by rfink** [terraform-providers/terraform-provider-azurerm#5086]
Would it be possible to add the service principal id to the output of an azurerm_container_group? This would help in terraforming role assignments for container groups, with system assigned identities. It looks like it gets returned in the Go SDK. If I was a smarter person, I would take a crack at it myself.

**Comment by rfink** [comment]
Ah geez, it actually looks like it's available but undocumented:

${azurerm_container_group.xxx.identity[0].principal_id}

Should I leave this up to add to docs?

**Comment by brennerm** [comment]
@rfink The docs actually give you a hint about the principal ID. https://www.terraform.io/docs/providers/azurerm/r/container_group.html#type

Maybe the description could be made a bit clearer.

**Comment by rfink** [comment]
Roger - will close out. Thank you!
