### ISSUE TITLE
Support for "azurerm_mariadb_server"

### ISSUE THREAD

**Issue by jlundy2** [terraform-providers/terraform-provider-azurerm#5088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There should be a similar data source to `azurerm_sql_server` for `azurerm_mariadb_server`.

### New or Affected Resource(s)

New data source:
* azurerm_mariadb_server

### Potential Terraform Configuration

```hcl
data "azurerm_mariadb_server" "db_server" {
  name                = "mariadb-server"
  resource_group_name = "example"
}
```

**Comment by jlundy2** [comment]
I'm happy to take a crack at contributing the code for this feature. It looks very straightforward at first blush. I'm raising this issue to see if there's anything blocking doing this.

**Comment by katbyte** [comment]
I think this was already added in #2406?

**Comment by jlundy2** [comment]
The resource was added there, but there isn't a corresponding data source.
