### ISSUE TITLE
Proposal: Better distinguish Site Recovery and Azure Backup resource names

### ISSUE THREAD

**Issue by sean-nixon** [terraform-providers/terraform-provider-azurerm#5089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Recovery Services is used for both backups (Azure Backup) and VM replication (Azure Site Recovery or ASR). They share similar concepts and terminology (e.g. policies, protected items, protection containers, fabrics) and both use the same recovery services vaults; _**however**_, they do not share resources other than the underlying vault. They have two relatively distinct APIs, have different packages in the azure-go-sdk, and have distinct sections in the Azure API docs. 

Currently, the resources created so far in this provider are not clear in distinguishing between the two which causes issues with naming resources which causes potential issues as well as confusion.

For example, `azurerm_recovery_services_protection_container` creates a Site Recovery replication protection container (https://docs.microsoft.com/en-us/rest/api/site-recovery/replicationprotectioncontainers). Azure Backups also has a protection container that is used for registering storage accounts with the recovery vault for Azure File backup (https://docs.microsoft.com/en-us/rest/api/backup/protectioncontainers) among other purposes. A new resource for this would be required to implement #5026.  We could use `azurerm_recovery_services_backup_protection_container` for this hypothetical new resource, but that's not consistent with any of the other backup resources, is extremely long, and is IMHO not very intuitive.

I'm proposing that for clarity, consistency, and easier extensibility, recovery services resource names be updated with clear name spacing. I'm open to other suggestions, but my opinion is to make all Azure Site Recovery resources use the `site_recovery` prefix while Azure Backup resources would use the `backup` prefix. This is of course a breaking change, so I'd like it to be considered for the 2.0 release. 

I'm of course open for feedback and alternative approaches.

### New or Affected Resource(s)

I'm proposing the following resource name changes:

| Old Resource Name | New Resource Name |
| --- | --- |
| azurerm_recovery_services_vault | azurerm_recovery_services_vault (no change) |
| azurerm_recovery_services_fabric | azurerm_site_recovery_fabric |
| azurerm_recovery_network_mapping | azurerm_site_recovery_network_mapping |
| azurerm_recovery_services_protection_container | azurerm_site_recovery_protection_container |
| azurerm_recovery_services_protection_container_mapping | azurerm_site_recovery_protection_container_mapping |
| azurerm_recovery_services_replication_policy | azurerm_site_recovery_protection_policy |
| azurerm_recovery_replicated_vm | azurerm_site_recovery_replicated_vm  |
| azurerm_recovery_services_protection_policy_vm | azurerm_backup_policy_vm |
| azurerm_recovery_services_protected_vm | azurerm_backup_protected_vm |

### References

Azure Backup API docs: https://docs.microsoft.com/en-us/rest/api/backup/
Azure Site Recovery API docs: https://docs.microsoft.com/en-us/rest/api/site-recovery/

**Comment by katbyte** [comment]
Hi @sean-nixon,

This sounds like a great idea to me! And we would be happy to accept a PR that deprecates the old resources and adds them with the new names.

I do wonder if it would make sense to continue to include recovery in the names as backup and site recovery are a subset of recovery services:
| Old Resource Name | New Resource Name |
| --- | --- |
| azurerm_recovery_services_vault | azurerm_recovery_services_vault (no change) |
| azurerm_recovery_services_fabric | azurerm_recovery_site_fabric |
| azurerm_recovery_network_mapping | azurerm_recovery_site_network_mapping |
| azurerm_recovery_services_protection_policy_vm | azurerm_recovery_backup_policy_vm |
| azurerm_recovery_services_protected_vm | azurerm_recovery_backup_protected_vm |

?

**Comment by sean-nixon** [comment]
@katbyte Very glad you're onboard with this idea. I will try to get a PR prepared for this but it may take a while due to other obligations on my end.

You do make a valid point about them both being a subset of recovery services. My main concern about the naming you suggested is that it sounds like we're creating a "recovery site" fabric, etc. which is not quick accurate. I'd argue that while both services are technically under the "Recovery Services" umbrella, both services are independent and usually referred to on their own. For example, we almost always refer to "Azure Backup" not "Recovery Services Azure Backup".

One alternative would be to use the acronym "ASR" (e.g. `azurerm_recovery_asr_fabric`) which used to be commonly used to refer to Azure Site Recovery. I can't find any references to it in the official Microsoft documentation any more so I think it may have fallen out of favor. I wouldn't be opposed to using it, but personally I think I still prefer the names in my initial proposal.

In any case, I'll work on putting together a PR where there can be further discussion on the final naming convention.

**Comment by sean-nixon** [comment]
@katbyte I submitted a PR for review that implements the new resource names as specified in the initial table with the exception of changing `azurerm_backup_policy_vm` to `azurerm_backup_protection_policy_vm`. It also deprecates the old resources and updates (hopefully) all the necessary documentation.
