### ISSUE TITLE
azurerm_virtual_machine_scale_set doesn't let me specify a custom image

### ISSUE THREAD

**Issue by edgan** [terraform-providers/terraform-provider-azurerm#5090]
The documentation page below has an example of using storage_profile_image_reference with an id in a azurerm_virtual_machine_scale_set resource. This is to allow the use of a custom image. In my case one created with Packer. My code looks like example code 1. I have also tried a variation with a data resource, but it seems to end up being rendered exactly the same internally. Hence it has the same result.

To me this seems like a bug, but I am surprised it would exist. I would expect using a custom image as part of a scaling set to be an extremely common usage case. I am open to suggestions. Downgrading? Different code? Configuration? Alternative way?

I am using the latest version of terraform, and the azurerm provider plugin. The subscription id and image name in my code are filled in, and valid. I do a very like thing with azurerm_virtual_machine in example code 2. It works without an issue.

#### Terraform version:
```
Terraform v0.12.17
+ provider.azurerm v1.37.0
```

#### Documentation page:
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html

#### Example code 1:
```
variable image_name = "/subscriptions/{{ subscription id here }}/resourceGroups/development/providers/Microsoft.Compute/images/{{ image name here }}"

resource "azurerm_virtual_machine_scale_set" "azurerm_virtual_machine_scale_set" {
  name = local.componentclusterrole

  location = var.location

  network_profile {
    name = local.component_cluster_role

    ip_configuration {
      name = local.component_cluster_role

      application_security_group_ids = [
        var.application_security_group,
      ]
      primary = true
      subnet_id = var.subnet_id
    }

    network_security_group_id = azurerm_network_security_group.azurerm_network_security_group.id
    primary = true
  }

  os_profile {
    computer_name_prefix = local.componentclusterrole
    admin_username = var.usernames["ubuntu"]
  }

  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      key_data = var.ssh_public_keys["devops"]
      path = var.ssh_paths["ubuntu"]
    }
  }

  resource_group_name = var.rg_name

  sku {
    name = var.vm_size
    tier = "Standard"
    capacity = var.instance_count
  }

  storage_profile_image_reference {
    id = var.image_name
  }

  storage_profile_os_disk {
    name = local.component_cluster_role

    create_option = "FromImage"
  }

  tags = {
    account = var.account
  }

  upgrade_policy_mode = "Manual"
  zones = [
    "1", "2", "3"
  ]
}

```

#### Example code 2:
```
variable image_name = "/subscriptions/{{ subscription id here }}/resourceGroups/development/providers/Microsoft.Compute/images/{{ image name here }}"

resource "azurerm_virtual_machine" "azurerm_virtual_machines" {
  name = "${local.component_cluster_role}-${format("%02d", count.index + 1)}.${var.env}.${var.region}.${var.cloud_provider}.${var.root_domain}"

  availability_set_id = var.av_set_id
  count = var.instance_count
  location = var.location

  identity {
    type = "SystemAssigned"
  }

  network_interface_ids = [
    element(azurerm_network_interface.azurerm_network_interfaces.*.id, count.index)
  ]

  os_profile {
    computer_name  = "${local.component_cluster_role}-${format("%02d", count.index + 1)}.${var.env}.${var.region}.${var.cloud_provider}.${var.root_domain}"
    admin_username = var.usernames["ubuntu"]
    admin_password = var.password
  }

  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      key_data = var.ssh_public_keys["devops"]
      path = var.ssh_paths["ubuntu"]
    }
  }

  resource_group_name  = var.rg_name

  storage_image_reference {
    id = var.image_name
  }

  storage_os_disk {
    name = "${local.component_cluster_role}-${format("%02d", count.index + 1)}.${var.env}.${var.region}.${var.cloud_provider}.${var.root_domain}"

    create_option = "FromImage"
  }
  vm_size = var.vm_sizes[count.index]
}
```

#### Error message:
```
Error: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Parameter 'osDisk.name' is not allowed." Target="osDisk.name"

  on modules/kube-staging-worker/main.tf line 38, in resource "azurerm_virtual_machine_scale_set" "azurerm_virtual_machine_scale_set":
  38: resource "azurerm_virtual_machine_scale_set" "azurerm_virtual_machine_scale_set" {
```

**Comment by edgan** [comment]
I got to the bottom of my issue. The key was using "export TF_LOG=TRACE" to get an exact answer of what API call terraform was submitting. I was then able to see what was causing the error. It also gave lots of details which were clues.

I hadn't specified managed_disk_type, like managed_disk_type = "Premium_LRS". Which meant the api was going to give me unmanaged disks. This is because I created my own packer images, and didn't specify their type properly. Terraform has a requirement that if it is unmanaged it has to have a name, but the API disagrees. On the other hand, if you specify managed_disk_type, you get managed, and neither terraform or the API require a name.

What especially confused me was terraform code that looked the same from making a virtual machine worked, but for scale sets didn't.

The bug seems to be to be terraform have the opposite opinion the API on the question of an unmanaged disk requires a name. Though it could be a issue of the check ignore if it is managed, and always applies. It also seems like terraform could realize it is going to be unmanaged and tell you no, you can't give a name for unmanaged disks. But then tell you this only for scale sets.

**Comment by dhabierre** [comment]
@edgan 
Is it possible to post an example?
Thanks.

**Comment by dhabierre** [comment]
Ly 2 cents

```hcl
data "azurerm_resource_group" "packer-images" {
  name = "${local.domain}-packer-images"
}

data "azurerm_image" "images" {
  name                = "iis-apps-image-20200512.2-202005120801" # TODO => vars
  resource_group_name = data.azurerm_resource_group.packer-images.name
}

resource "azurerm_windows_virtual_machine_scale_set" "main" {
  ...
  source_image_id = data.azurerm_image.images.id
  ...
}
```

**Comment by tombuildsstuff** [comment]
hey @edgan 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through as @dhabierre has alluded to, the existing `azurerm_virtual_machine_scale_set` resources have been superseded by the `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources - which we'd recommend going forward; these have a field for the `source_image_id` to source this image from.

Since this should be fixed by updating the Terraform Configuration to use these new resources I'm going to close this issue for the moment - but please let us know if that doesn't solve your issue and we'll take another look.

Thanks!
