### ISSUE TITLE
azurerm_container_service DCOS example fails during apply

### ISSUE THREAD

**Issue by jeffreyCline** [terraform-providers/terraform-provider-azurerm#510]
### Terraform Version
Terraform v0.10.9-dev (46d2b76e5f7d1591f66c45312d7a25be37dba7c8)
provider.azurerm v0.3.2

### Affected Resource(s)
azurerm_container_service

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "test" {
  name     = "acctestRG1"
  location = "West US"
}

resource "azurerm_container_service" "test" {
  name                   = "acctestcontservice1"
  location               = "${azurerm_resource_group.test.location}"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  orchestration_platform = "DCOS"

  master_profile {
    count      = 1
    dns_prefix = "acctestmaster1"
  }

  linux_profile {
    admin_username = "acctestuser1"

    ssh_key {
      key_data = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqaZoyiz1qbdOQ8xEf6uEu1cCwYowo5FHtsBhqLoDnnp7KUTEBN+L2NxRIfQ781rxV6Iq5jSav6b2Q8z5KiseOlvKA/RF2wqU0UPYqQviQhLmW6THTpmrv/YkUCuzxDpsH7DUDhZcwySLKVVe0Qm3+5N2Ta6UYH3lsDf9R9wTP2K/+vAnflKebuypNlmocIvakFWoZda18FOmsOoIVXQ8HWFNCuw9ZCunMSN62QGamCe3dL5cXlkgHYv7ekJE15IA9aOJcM7e90oeTqo+7HTcWfdu0qQqPWY5ujyMw/llas8tsXY85LFqRnr3gJ02bAscjc477+X+j/gkpFoN1QEmt terraform@demo.tld"
    }
  }

  agent_pool_profile {
    name       = "default"
    count      = 1
    dns_prefix = "acctestagent1"
    vm_size    = "Standard_A0"
  }

  diagnostics_profile {
    enabled = false
  }

  tags {
    Environment = "Production"
  }
}
```

### Debug Output
https://gist.github.com/jeffreyCline/56f9726fb45cac29f4e843335920f94c

### Expected Behavior
1. Successfully roll out the azurerm_container_service 

### Actual Behavior
1. Error message stating "...Agent is not allowed in your subscription in location 'westus'..."

### Steps to Reproduce
1. `terraform apply`

**Comment by devigned** [comment]
Default VM size not available in region.

> The VM Size of Master, Agent is not allowed in your subscription in location 'westus'. Master VM Size 'Standard_D2_v2' is available in locations: eastus, southcentralus, westeurope, southeastasia. Agent VM Size 'Standard_A0' is available in locations: eastus, southcentralus, westeurope, southeastasia.

**Comment by devigned** [comment]
Doesn't look like ACS exposes a way to set the master size via the master_profile (https://docs.microsoft.com/en-us/rest/api/container-service/containerservices/createorupdate#definitions_containerservicemasterprofile). @rgardler might have some insights.

**Comment by tombuildsstuff** [comment]
Hey @jeffreyCline 

Thanks for opening this issue :)

I may be wrong (as I have context/understanding of ACS) - but from what I can see those error messages would be relatively clear to a new user? As such I think the simplest thing to do here would be to update the location to `East US` so the examples are valid?

From my end - I've been wondering for a while if it's worth removing the DCOS and Swarm examples in the documentation in favour of a link to a sample for each in the `examples/` folder - which would make the documentation clearer; what do you think?

Thanks!

**Comment by jeffreyCline** [comment]
Yes, and I did get this working by updating the location to East US.

**Comment by tombuildsstuff** [comment]
Great to hear - from what I can see this issue is resolved and as such I'm going to close the issue - however please feel free to reopen this if you're still seeing issues

Thanks!
