### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by ngallo** [terraform-providers/terraform-provider-azurerm#5100]
By mistake I passed **_ip_address_** instead of **_id_** to the **_public_ip_address_id_** property. The error was fixed using **_id_** .

Maybe it could be useful to handle this error message.

**SAMPLE CODE**

```
resource "azurerm_network_interface" "myApp_res_network_interface" {
    count                     = 3
    name                      = "${upper(local.global.prefix_short)}_NETWORK_INTERFACE_${count.index}"
    location                  = "${var.localtion}"
    resource_group_name       = "${azurerm_resource_group.myApp_res_resource_group.name}"
    network_security_group_id = "${azurerm_network_security_group.myApp_res_security_group.id}"

    ip_configuration {
        name                          = "${upper(local.global.prefix_short)}_NETWORK_INTERFACE_CONFIGURATION"
        subnet_id                     = "${azurerm_subnet.myApp_res_subnet.id}"
        private_ip_address_allocation = "Dynamic"
        public_ip_address_id          = "${element(azurerm_public_ip.myApp_res_public_ip.*.ip_address, count.index)}"
    }

    tags = "${local.global.tags}"

}

```
**ERROR**
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.
> 
> 
> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for
> azurerm_network_interface.myApp_res_network_interface[0] to include new values
> learned so far during apply, provider "azurerm" produced an invalid new value
> for .ip_configuration[0].public_ip_address_id: was cty.StringVal(""), but now
> cty.StringVal("13.90.231.67").
> 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. May I ask do you encounter this issue at first apply? if not, could you share your repro steps since I cannot repro this issue with below tfconfig? Or could you have a try below tfconfig to check whether the problem still exists?

Run `tf apply`:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-nic-test03"
  location = "eastus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvn-test03"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "nicsubnettestinternal"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "acctestpublicip-test03"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
}

resource "azurerm_network_interface" "test" {
  name                = "acctestni-test03"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  ip_configuration {
    name                          = "primary"
    subnet_id                     = azurerm_subnet.test.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.test.ip_address
  }
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to provide the information requested above then we should be able to re-open this and take another look.

Thanks!
