### ISSUE TITLE
subresource_names attribute on azurerm_private_link_endpoint.private_service_connection does not accept valid data

### ISSUE THREAD

**Issue by geekzter** [terraform-providers/terraform-provider-azurerm#5110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
# terraform -v
Terraform v0.12.17
```
```hcl
provider "azurerm" {
    version = "= 1.38" 
}
```

### Affected Resource(s)

* `azurerm_private_link_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "repro" {
  name                         = "${var.prefix}-private-endpoint-issue"
  location                     = var.location
}

resource "azurerm_virtual_network" "network" {
  name                         = "${var.prefix}-vnet"
  address_space                = ["10.0.0.0/16"]
  location                     = azurerm_resource_group.repro.location
  resource_group_name          = azurerm_resource_group.repro.name
}

resource "azurerm_subnet" "subnet" {
  name                         = "${var.prefix}-subnet"
  resource_group_name          = azurerm_resource_group.repro.name
  virtual_network_name         = azurerm_virtual_network.network.name
  address_prefix               = "10.0.1.0/24"
  enforce_private_link_endpoint_network_policies = false
}

resource "random_string" "password" {
  length                       = 12
  upper                        = true
  lower                        = true
  number                       = true
  special                      = true
  override_special             = "." 
}

resource "azurerm_sql_server" "sql_server" {
  name                         = "${var.prefix}sqlserver"
  resource_group_name          = azurerm_resource_group.repro.name
  location                     = azurerm_resource_group.repro.location
  version                      = "12.0"
  administrator_login          = "dbadmin"
  administrator_login_password = random_string.password.result
}

resource "azurerm_private_link_endpoint" "endpoint" {
  name                         = "${var.prefix}-endpoint"
  resource_group_name          = azurerm_resource_group.repro.name
  location                     = azurerm_resource_group.repro.location
  subnet_id                    = azurerm_subnet.subnet.id

  private_service_connection {
    is_manual_connection       = false
    name                       = "${var.prefix}-endpoint-connection"
    private_connection_resource_id = azurerm_sql_server.sql_server.id
    subresource_names          = ["sqlServer"]
  }
}
```
```hcl
variable "prefix" {
  description = "The Prefix used for all resources in this example"
}

variable "location" {
  description = "The Azure Region in which all resources in this example should be created."
}
```

### Panic Output

`Error: private_service_connection.0.subresource_names.0 must only contain upper or lowercase letters, numbers, underscores, and periods`

### Expected Behavior

Private Endpoint created for given sqlServer sub resource (GroupId)

### Actual Behavior

`Error: private_service_connection.0.subresource_names.0 must only contain upper or lowercase letters, numbers, underscores, and periods`
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

It appears the regex in ValidatePrivateLinkSubResourceName is single character only (`^[\w\.]$`)

### References

* #4493

**Comment by leewilson86** [comment]
Hey @WodansSon,

Is this something you are aware of? I understand you created the TF resource for private endpoints.

I have been experiencing this issue too.

Cheers!
