### ISSUE TITLE
azurerm_storage_account_network_rules ip_rules attribute does not accept CIDR expression

### ISSUE THREAD

**Issue by geekzter** [terraform-providers/terraform-provider-azurerm#5111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
# terraform -v
Terraform v0.12.17
```
```hcl
provider "azurerm" {
    version = "= 1.38" 
}
```

### Affected Resource(s)

* `azurerm_storage_account_network_rules`

### Terraform Configuration Files

```hcl
resource azurerm_resource_group repro {
  name                         = "${var.prefix}-private-endpoint-issue"
  location                     = var.location
}

resource azurerm_storage_account storage {
  name                         = "${var.prefix}storageaccount"
  location                     = azurerm_resource_group.repro.location
  resource_group_name          = azurerm_resource_group.repro.name
  account_tier                 = "Standard"
  account_replication_type     = "LRS"
}

resource azurerm_storage_account_network_rules rules {
  resource_group_name          = azurerm_resource_group.repro.name
  storage_account_name         = azurerm_storage_account.storage.name

  default_action               = "Allow"
  ip_rules                     = ["1.0.0.1/30"]
  bypass                       = ["Metrics"]
}
```
```hcl
variable "prefix" {
  description = "The Prefix used for all resources in this example"
}

variable "location" {
  description = "The Azure Region in which all resources in this example should be created."
}
```

### Panic Output

`Error: "ip_rules.0" is not a valid IPv4 address: "1.0.0.1/30"`

### Expected Behavior

Network rule created for CIDR expression

### Actual Behavior

`Error: "ip_rules.0" is not a valid IPv4 address: "1.0.0.1/30"`
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

* #5082

**Comment by mariojacobo** [comment]
Same issue here, the workaround is to drop the subnet mask
```
ip_rules                     = ["1.0.0.1"]
```

If however you wanted to apply the same on a Keyvault, it actually works with the subnet mask: 
```
network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
    virtual_network_subnet_ids = ["${azurerm_subnet.akssubnet.id}"]
    ip_rules = ["1.0.0.1/32"]
  }
```
