### ISSUE TITLE
Allow optional storage size with `auto_grow` enabled

### ISSUE THREAD

**Issue by Croissong** [terraform-providers/terraform-provider-azurerm#5121]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We're experiencing an undesired behavior when enabling `auto_grow` for a postgresql server.
As the `storage_mb` setting is required, each time the storage size is automatically increased via autogrow, terraform detects a change and `storage_mb` needs to be manually increased as well.
Ideally, `storage_mb` would be optionally if `auto_grow` is enabled.

### New or Affected Resource(s)

* `azurerm_postgresql_server`

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_server" "db" {
...
  storage_profile {
    storage_mb            = var.storage_mb
    auto_grow             = "Enabled"
  }
```

**Comment by r0bnet** [comment]
Hey @Croissong,

as a workaround i'd propose the following:

```hcl
resource "azurerm_postgresql_server" "db" {
...
  storage_profile {
    storage_mb            = var.storage_mb
    auto_grow             = "Enabled"
  }

  lifecycle {
    ignore_changes = [storage_profile.storage_mb]
  }
```

Is that a viable option for you? Tbf I didn't test that but i might work.

**Comment by jemrobinson** [comment]
For anyone else facing this issue, I found that the following minor tweak to @r0bnet 's solution worked in Terraform v0.12.20.

```
  lifecycle {
    ignore_changes = [storage_profile[0].storage_mb]
  }
```
