### ISSUE TITLE
HDInsight if apply uses wrong vm size gets into bad state

### ISSUE THREAD

**Issue by cicorias** [terraform-providers/terraform-provider-azurerm#5123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

when correctingVM sizes for the HDInsight cluster the error should fail, but not leave the HDInsight cluster in bad state. .

### Actual Behavior

First apply fails - which is expected. But the HDInsight cluster actually exists in Azure (see portal after failure).

On second apply after correcting the SKU for the VM Sizes, the Apply should "fix" or even recreate the cluster.

### Terraform (and AzureRM Provider) Version

```
provider "azurerm" {
  version         = "~> 1.37.0"
```

Terraform v0.12.17

### Affected Resource(s)

* `azurerm_hdinsight_hadoop_cluster`

### Terraform Configuration Files

see: https://github.com/cicorias/njit-bd-mr-project/tree/master/deploy/az
### Steps to Reproduce

1. create an HDInsight with a SKU for the VMs that is incorrect (docs page indicates ... is valid but is not).
1. Run terraform apply  - this errors out with the first error messsage
1. fix the VM size change to ....
1. Run terraform apply again - this again errors out with the 'nil' error message.

### Important Factoids

Full console log here: https://gist.github.com/cicorias/db0c0c1fcea24b30c042c74eea276b46

HDinsight Docs lists "standard_a2_v2" but that failed.
https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-supported-node-configuration#default-and-minimum-recommended-node-configuration-and-virtual-machine-sizes-for-clusters

### error message 1
```
data.azurerm_resource_group.hdpcluster: Refreshing state...
data.azurerm_storage_account.hdpcluster: Refreshing state...
azurerm_hdinsight_hadoop_cluster.hdpcluster: Creating...
azurerm_hdinsight_hadoop_cluster.hdpcluster: Still creating... [10s elapsed]
azurerm_hdinsight_hadoop_cluster.hdpcluster: Still creating... [30s elapsed]
azurerm_hdinsight_hadoop_cluster.hdpcluster: Still creating... [40s elapsed]
azurerm_hdinsight_hadoop_cluster.hdpcluster: Still creating... [50s elapsed]
azurerm_hdinsight_hadoop_cluster.hdpcluster: Still creating... [1m0s elapsed]

Error: Error waiting for creation of HDInsight Hadoop Cluster "scicoriahdicluster" (Resource Group "scicoria-hdp-cluster"): Code="InvalidDocumentErrorCode" Message="DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'standard_a2_v2' provided in the request is invalid or not supported for role 'workernode'. Valid values are: A6,A7,EXTRALARGE,LARGE,STANDARD_D12,STANDARD_D12_V2,STANDARD_D13,STANDARD_D13_V2,STANDARD_D14,STANDARD_D14_V2,STANDARD_D3,STANDARD_D3_V2,STANDARD_D4,STANDARD_D4_V2,STANDARD_D5_V2,STANDARD_DS12_V2,STANDARD_DS13_V2,STANDARD_DS14_V2,STANDARD_DS3_V2,STANDARD_DS4_V2,STANDARD_DS5_V2,STANDARD_A4_V2,STANDARD_A8_V2,STANDARD_A2M_V2,STANDARD_A4M_V2,STANDARD_A8M_V2,STANDARD_E16_V3,STANDARD_E2_V3,STANDARD_E20_V3,STANDARD_E32_V3,STANDARD_E4_V3,STANDARD_E64_V3,STANDARD_E64I_V3,STANDARD_E8_V3,STANDARD_A6,STANDARD_A7,STANDARD_F16,STANDARD_F4,STANDARD_F8'"

  12: resource "azurerm_hdinsight_hadoop_cluster" "hdpcluster" {
```

### error message 2
```
data.azurerm_resource_group.hdpcluster: Refreshing state...
data.azurerm_storage_account.hdpcluster: Refreshing state...
azurerm_hdinsight_hadoop_cluster.hdpcluster: Creating...

Error: Error creating HDInsight Hadoop Cluster "scicoriahdicluster" (Resource Group "scicoria-hdp-cluster"): hdinsight.ClustersClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

  12: resource "azurerm_hdinsight_hadoop_cluster" "hdpcluster" {

```

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, I found the root cause is that the cluster resource isn't deleted while creating this resource failed. I assume it should be deleted while create operation failed. So I made a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7994).

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if you're still seeing this when using the latest version of Terraform/the Azure Provider and we'll take another look.

Thanks!
