### ISSUE TITLE
AzureRM provider always destroys and recreates Topics in Premium service bus namespace

### ISSUE THREAD

**Issue by sl31pn1r** [terraform-providers/terraform-provider-azurerm#5131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform & Provider versions:
Terraform v0.12.17
provider.azuread v0.7.0
provider.azurerm v1.38.0

### Affected Resource(s)

* `azurerm_servicebus_topic`
* `azurerm_servicebus_namespace`

### Terraform Configuration Files

ServiceBus:
```
terraform {
  backend "azurerm" {}
}

provider "azurerm" {
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  version         = "~> 1.27"
}

provider "azuread" {
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  version         = "~> 0.2"
}

########################### dataSource ##########################
data "azurerm_resource_group" "rg01" {
  name = "${lower("rg-${var.location_shortcode}-${var.service}-${var.microservice}-${var.environment}")}"
}

########################### serviceBus ###########################
resource "azurerm_servicebus_namespace" "sbns01" {
  name                = "${lower("sb-${var.location_shortcode}-${var.service}-${var.microservice}-${var.environment}")}"
  location            = "${data.azurerm_resource_group.rg01.location}"
  resource_group_name = "${data.azurerm_resource_group.rg01.name}"
  sku                 = "${var.servicebus_sku}"
  capacity            = "${var.servicebus_capacity}"

  tags = {
    autodelete          = "false"
    businessunit        = "${lower("${var.businessunit}")}"
    environment         = "${lower("${var.environment}")}"
    service-environment = "${lower("${var.service}-${var.environment}")}"
  }
}

```

Topics:
```

######################## providers #############################
terraform {
  backend "azurerm" {}
}

provider "azurerm" {
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  version         = "~> 1.27"
}

provider "azuread" {
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  version         = "~> 0.2"
}

########################### dataSource ##########################
data "azurerm_resource_group" "rg01" {
  name = "${lower("rg-${var.location_shortcode}-${var.service}-${var.microservice}-${var.environment}")}"
}

data "azurerm_servicebus_namespace" "sbns01" {
  name                = "${lower("sb-${var.location_shortcode}-${var.service}-${var.microservice}-${var.environment}")}"
  resource_group_name = "${data.azurerm_resource_group.rg01.name}"
}


########################### Topics ###############################

resource "azurerm_servicebus_topic" "topic1" {
  name                = "topic1"
  resource_group_name = "${data.azurerm_resource_group.rg01.name}"
  namespace_name      = "${data.azurerm_servicebus_namespace.sbns01.name}"

  enable_partitioning = true
}

resource "azurerm_servicebus_topic" "topic2" {
  name                = "topic2"
  resource_group_name = "${data.azurerm_resource_group.rg01.name}"
  namespace_name      = "${data.azurerm_servicebus_namespace.sbns01.name}"

  enable_partitioning = true
}


```

### Debug Output

https://gist.github.com/sl31pn1r/eeee94e2d3911a275fda642715c82411

### Expected Behavior
Terraform should not destroy and recreate the Topics if the SKU of the Service Bus is Premium.

### Actual Behavior

Terraform always destroys and recreates topics if the SKU of the Service Bus is Premium. The same is not happening with Standard SKU. Tried it with different azurerm (1.27, 1.34, 1.38) and different terraform (0.12.3, 0.12.17) versions the issue is the same.

### Steps to Reproduce

1.create relevant env variables, use Premium as the servicebus_sku
2. use code provided and do `terraform apply`

### References

* #0000

**Comment by kubilaykaptanoglu** [comment]
I'm having a similar problem for the aks

**Comment by kubilaykaptanoglu** [comment]
@sl31pn1r azurerm version 1.35.0 worked for me

**Comment by tombuildsstuff** [comment]
@kubilaykaptanoglu please [see the changelog for 1.37 about how to update your config for Kubernetes](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1370-november-26-2019) - it's unrelated to this issue

**Comment by tombuildsstuff** [comment]
hi @sl31pn1r 

Thanks for opening this issue.

So that we can take a look into this would it be possible to also show the output of a `terraform plan` that you're seeing here?

Thanks!

**Comment by sl31pn1r** [comment]
Hi @tombuildsstuff 

Hope it's good in this format. 
Terraform plan for the Service bus namespace:
https://gist.github.com/sl31pn1r/a42618395acb694db693bba4ea173cc7

Terraform Plan for the Topics (which shows the destroy task for the topics):
https://gist.github.com/sl31pn1r/a481062c9113a42cbda30e7b924c293e

**Comment by tombuildsstuff** [comment]
hey @sl31pn1r 

Thanks for that.

Taking a look through it appears this is happening because `enable_partitioning` is set to `true` which the Azure API doesn't permit for Premium SKU's (and instead reverts to `false`). Since this behaviour is coming from the Azure API we've opted to document this behaviour [in the resource documentation](https://www.terraform.io/docs/providers/azurerm/r/servicebus_topic.html#enable_partitioning).

To workaround this requiring recreation within Terraform, it should be possible to change `enable_partitioning` to `false` rather than `true`. If you're looking for ServiceBus Topics to support Partitioning within a Premium Namespace I'd suggest opening a feedback request with the API team - however since this behaviour is current intentional (and documented) I'm going to close this issue for the moment.

Thanks!

**Comment by sl31pn1r** [comment]
Hi @tombuildsstuff 

Thanks a lot, not sure how I missed that :(

apologies for robbing you time with this.

**Comment by tombuildsstuff** [comment]
@sl31pn1r no worries at all :)
