### ISSUE TITLE
Support for azurerm_storage_file

### ISSUE THREAD

**Issue by amasover** [terraform-providers/terraform-provider-azurerm#5132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I think there should be an `azurerm_storage_file` resource, similar to the existing `azurerm_storage_blob` resource. This would allow an individual file in a file share (for example) to be managed by Terraform.

### New or Affected Resource(s)

* azurerm_storage_file

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_file" "example" {
  name = "my-awesome-file.zip"
  storage_account_name = azurerm_storage_account.example.name
  storage_share_name = azurerm_storage_share.example.name
  source = "some-local-file.zip"
}
```

Could also support `source_content` to define the file inline like in `azurerm_storage_blob`.

### References

* https://www.terraform.io/docs/providers/azurerm/r/storage_blob.html

**Comment by tombuildsstuff** [comment]
Giovanni SDK: https://github.com/tombuildsstuff/giovanni/tree/master/storage/2019-12-12/file/files
