### ISSUE TITLE
Subnets with multiple addressPrefixes cannot be used as a source or created

### ISSUE THREAD

**Issue by smarterclayton** [terraform-providers/terraform-provider-azurerm#5140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

7427e8c593607d30a49fa3d211c38151cf422ce0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
data "azurerm_subnet" "preexisting_worker_subnet" {
  count = var.preexisting_network ? 1 : 0

  resource_group_name  = var.network_resource_group_name
  virtual_network_name = var.virtual_network_name
  name                 = var.worker_subnet
}

locals {
  # empty when subnet has multiple addressPrefixes (2+)
  address_prefix data.azurerm_subnet.preexisting_worker_subnet[0].address_prefix
}
```

### Expected Behavior

* Retrieve address_prefixes when multiple are set on the subnet
* Allow creation of subnets with 2+ address_prefixes (ipv4 and ipv6, for example)

### Actual Behavior

Nil data on retrieval, unable to create with existing API

**Comment by sigv** [comment]
For completeness sake in this ticket: The response to `/subscriptions/guid/resourceGroups/name/providers/Microsoft.Network/virtualNetworks/vnet/subnets/subnet` has a `properties.subnets` array where each object has `properties.addressPrefix` string, which gets replaced by a `properties.addressPrefixes` array of strings. This seems to be already getting worked on in #5139 though.
