### ISSUE TITLE
azurerm_private_dns_zone_virtual_network_link different subscriptions

### ISSUE THREAD

**Issue by GramozKrasniqi** [terraform-providers/terraform-provider-azurerm#5172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide ability to specify private dns zone subscription (or the resource id e.g. ```/subscriptions/xxxxxxx/resourceGroups/xxxxx/providers/Microsoft.Network/privateDnsZones/xxxxx```).

In some cases there is another team that manages the private dns zones (the resource is probably in another subscription).

Even though we dont want to manage the private dns zone we want to be able to link the vnet  that we create using automation tools so that we can do name resolution .

Can a virtual network from a different subscription be linked to a private dns zone:
https://docs.microsoft.com/en-us/azure/dns/dns-faq-private#can-a-virtual-network-that-belongs-to-a-different-subscription-be-linked-to-a-private-zone.

Note: In Azure Portal you can select the VNET subscription.

### New or Affected Resource(s)

azurerm_private_dns_zone_virtual_network_link

* azurerm_1.38 > *

### Potential Terraform Configuration

```hcl
resource "azurerm_private_dns_zone_virtual_network_link" "link_to_private_dns_zone" {
  name                  = "${azurerm_virtual_network.vnet.name}-link"
  resource_group_name   = var.private_dns_zone_rg_name
  private_dns_zone_name = var.private_dns_zone_name
  virtual_network_id    = azurerm_virtual_network.vnet.id
}
```

**Comment by MikaSoinetsalo** [comment]
Any updates ?

**Comment by tombuildsstuff** [comment]
hi @GramozKrasniqi 

Thanks for opening this issue

You can use multiple provider blocks to work with different subscriptions, for example:

```
provider "azurerm" {
  alias   = "hub"
  version = "=2.2.0"
  features {}
}

provider "azurerm" {
  alias   = "spoke"
  version = "=2.2.0"
  features {}
}

data "azurerm_virtual_network" "vnet" {
  name                = "..."
  resource_group_name = "..."
  provider            = "azurerm.hub"
}

# ...

resource "azurerm_private_dns_zone_virtual_network_link" "link_to_private_dns_zone" {
  name                  = "${data.azurerm_virtual_network.vnet.name}-link"
  resource_group_name   = "..."
  private_dns_zone_name = "..."
  virtual_network_id    = data.azurerm_virtual_network.vnet.id
  provider              = "azurerm.spoke"
}
```

In this example we load the Virtual Network from the "Hub" subscription and then add this Virtual Network Link to the Private DNS Zone of the "Spoke" subscription - which allows creating resources in both.

Since this is a question about using Terraform rather than a feature request/bug in the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by MikaSoinetsalo** [comment]
Hi @tombuildsstuff ,

I actually used another provider that is configured using another subscription id. Depending on what I put on the resource group it either won't find the private_zone or the resource group.  Both errors are logical based on the resource_group used so it looks like it's missing the needed functionality "under the hood" - disclaimer - this was the first time when I'm creating that link so I might have something wrong there. 

`
Error: error creating/updating Private DNS Zone Virtual network link "link_name" (Resource Group "subs-1"): privatedns.VirtualNetworkLinksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'subs-1' could not be found."

Error: error creating/updating Private DNS Zone Virtual network link "link_name" (Resource Group "subs-2"): privatedns.VirtualNetworkLinksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'that_private_dns_zone' not found."`

**Comment by MikaSoinetsalo** [comment]
So yousing your example something like this:

```
provider "azurerm" {
  alias   = "hub"
  version = "=2.2.0"
  features {}
}

provider "azurerm" {
  alias   = "spoke"
  version = "=2.2.0"
  features {}
}

data "azurerm_virtual_network" "vnet-hub" {
  name                = "vnet-hub"
  resource_group_name = "rg-hub"
  provider            = "azurerm.hub"
}

data "azurerm_virtual_network" "vnet-spoke" {
  name                = "vnet-spoke"
  resource_group_name = "rg-spoke"
  provider            = "azurerm.spoke"
}


resource "azurerm_private_dns_zone_virtual_network_link" "link_to_private_dns_zone" {
  name                  = "${data.azurerm_virtual_network.vnet-spoke.name}-link"
  resource_group_name   = "rg-hub"
  private_dns_zone_name = "private.dns.zone.hub"
  virtual_network_id    = data.azurerm_virtual_network.vnet-spoke.id
  provider              = "azurerm.spoke"
}
```
