### ISSUE TITLE
Support for Generation 2 virtual network gateways

### ISSUE THREAD

**Issue by BHoggs** [terraform-providers/terraform-provider-azurerm#5173]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure now supports the deployment of Generation 2 virtual network gateways. This is a separate attribute to SKU, as the SKU names appear to overlap. This would map to "vpnGatewayGeneration" in ARM templates.

### New or Affected Resource(s)

* azurerm_virtual_network_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network_gateway" "example" {
    name                = "MyGateway"
    location            = azurerm_resource_group.example.location
    resource_group_name = azurerm_resource_group.example.name

    type     = "Vpn"
    vpn_type = "RouteBased"

    active_active = false
    enable_bgp    = false
    sku           = "VpnGw2"
    generation    = "Generation2"
```

### References

* https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-gateway-settings#gwsku

**Comment by phires** [comment]
Looking into this
