### ISSUE TITLE
Recovery Services: support for enabling/disabling soft delete

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#5177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for Enabling and Disabling Soft Delete for Recovery Services - which is Enabled by default (but must be toggled off to delete the cluster).

This requires upgrading to the latest version of the Azure SDK/new API version which exposes this functionality

### New or Affected Resource(s)

* `azurerm_recovery_services_vault`

### Potential Terraform Configuration

n/a

### References

Split out from https://github.com/terraform-providers/terraform-provider-azurerm/issues/4774

**Comment by pvrk** [comment]
Just for your information, we plan to release soft-delete capability for other workloads such as SQL running in Azure VMs. Can any one from the terraform community help us test this scenario before we roll-out to wider audience?

Thanks in advance.

**Comment by pvrk** [comment]
@tombuildsstuff : Can any one from the terraform community help us test the soft-delete capability for SQL backups scenario before we roll-out to wider audience?

**Comment by pvrk** [comment]
@tombuildsstuff : A gentle reminder.

**Comment by katbyte** [comment]
fixed by #5586
