### ISSUE TITLE
MX records in azurerm_dns_mx_record unable to provide for the domain, and the docs are wrong

### ISSUE THREAD

**Issue by armtuk** [terraform-providers/terraform-provider-azurerm#5199]
There should be some way to create an MX record for the root domain with terraform. This is super basic setup for a domain and it doesn't seem to work.  If you follow the documentation linked below, you get an MX record for a subdomain.  If you provide a name like you would for BIND or most other DNS systems, you get an error.  If you use an "@" that doesn't work.  A google search yields nothing useful either.

It appears as though there is no way to create a default MX record for a domain meaning that you can't set up a domain through terraform on Azure completely.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.16
+ provider.azurerm v1.36.0

### Affected Resource(s)

* `azurerm_dns_mx_record`

### Terraform Configuration Files

```hcl
resource "azurerm_dns_mx_record" "example-com-mx" {
  name = "example.com."
  resource_group_name = data.azurerm_resource_group.prod-rg.name
  zone_name = azurerm_dns_zone.example-com.name
  ttl = 300

  record {
    exchange = "ALT1.ASPMX.L.GOOGLE.COM."
    preference = "5"
  }
  record {
    exchange = "ALT2.ASPMX.L.GOOGLE.COM."
    preference = "5"
  }
  record {
    exchange = "ALT3.ASPMX.L.GOOGLE.COM."
    preference = "10"
  }
  record {
    exchange = "ALT4.ASPMX.L.GOOGLE.COM."
    preference = "10"
  }
  record {
    exchange = "verificationcodehere.mx-verification.google.com."
    preference = "15"
  }
}
```

### Expected Behavior

This should generate an MX record for the domain.

### Actual Behavior

Error: Error creating/updating DNS MX Record "example.com." (Zone "example.com" / Resource Group "prod"): dns.RecordSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The resource records' relative name 'example.com.' must not end with a dot."

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

No apparent or documented way to create a domain MX record.

### References

https://www.terraform.io/docs/providers/azurerm/r/dns_mx_record.html

This documentation is incorrect, unhelpful and misleading.  The above description will create an MX record for "test.mydomain.com", not an MX record called "test" for "mydomain.com".

**Comment by phires** [comment]
I'll look into this

**Comment by armtuk** [comment]
Thank you - works great!
