### ISSUE TITLE
Linux consumption plan apps created using terraform return 503 because of WEBSITE_CONTENT* settings

### ISSUE THREAD

**Issue by mlazowik** [terraform-providers/terraform-provider-azurerm#5209]
>If `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` app settings are set for Linux Consumption, the datarole will throw `AzureFiles mounting blocked for site` and both host and scm worker will return 503.

[Source](https://github.com/Azure/azure-functions-core-tools/pull/1437#issuecomment-511054506).

Should be restored once the backend is fixed, as per:
https://github.com/Azure/azure-functions-core-tools/issues/1439

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform `v0.12.13`
azurerm `v1.39.0`

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

Anything that sets `kind="Linux"` in the resource plan.

### Expected Behavior

Mentioned settings not present, empty function app loads the welcome page (`/`) properly.

### Actual Behavior

Settings preset, app returns 503.

### Steps to Reproduce

1. Create any Linux consumption plan app tf file.
2. `terraform apply`

### References

* Removal from core tools: https://github.com/Azure/azure-functions-core-tools/pull/1437
* Removal from cli: https://github.com/Azure/azure-cli/issues/9027
* these are already removed for app service plan deployments: #1453 
* the logic is here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/12226526ad2bfbd88b443e9842b4f37c6e8ee6f0/azurerm/resource_arm_function_app.go#L669
* https://github.com/Azure/azure-functions-core-tools/issues/1439

**Comment by robertlagrant** [comment]
@xuzhang3 - is this likely to be fixed soon? I'm hitting the problem as well. I'm happy to help test.

**Comment by borancar** [comment]
@robertlagrant, I've raised a PR that does what's requested here, however I'm not sure that it will resolve the issue fully and further unknown changes might be needed. Even without WEBSITE_CONTENTSHARE and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING, my Linux Consumption plan still couldn't get its requirements installed from requirements.txt.
