### ISSUE TITLE
Enable Advanced Threat Protection on Azure DB for MySQL

### ISSUE THREAD

**Issue by siddthota** [terraform-providers/terraform-provider-azurerm#5238]
Hello,

I'm looking for this feature on TF to Enable Advanced Threat Protection on the MySQL DB and I don't find it in the documentation. Azure says it's in preview state since very long, but we have few security constraints to have this feature enabled to get into production. Can you please add this feature?

**Potential Terraform Configuration**

 enable_advanced_threat_protection = true

**Comment by tombuildsstuff** [comment]
hi @siddthota 

Thanks for opening this issue.

Support for this functionality has been added in #4848 which will ship in version 1.40 of the Azure Provider - as such you should be able to utilize this when this version is released. I've assigned this issue to the 1.40 Milestone - as such when this version is released @hashibot will comment to let you know when you can start using this.

Thanks!

**Comment by tehyatt** [comment]
Hello @tombuildsstuff, I upgraded to 1.43.0 this morning and attempted to use the new azurerm_advanced_threat_protection resource, but got the following error. Seems the new resource only supports the storage account, not mysql server.

The documentation for #4848 seems to be specific to storage accounts as well.

Should this issue be reopened, or am I missing something?

Thanks!

Snippet of log below.

`
Error: Error updating Advanced Threat protection for resource "/subscriptions/****/resourceGroups/demo-group/providers/Microsoft.DBforMySQL/servers/demo-server": security.AdvancedThreatProtectionClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Not Supported" Message="Atp settings are not supported on resources of type servers"

on ../../main.tf line 25, in resource "azurerm_advanced_threat_protection" "mysql_advanced_threat_protection":
  25: resource "azurerm_advanced_threat_protection" "mysql_advanced_threat_protection" {
`

**Comment by tehyatt** [comment]
In addition, the new provider only supports enabling it. The ability to specify an email address and to enable or disable the option to "Also send email notification to admins and subscription owners" is not available in the new provider.
