### ISSUE TITLE
subnet_network_security_group_association keeps adding/deleting

### ISSUE THREAD

**Issue by rdvansloten** [terraform-providers/terraform-provider-azurerm#5246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Cloud, 0.12

### Affected Resource(s)
* `azurerm_subnet`
* `azurerm_subnet_network_security_group_association`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "redactedSubnet" {
  name                      = "appgateway"
  resource_group_name       = azurerm_resource_group.redactedResources.name
  virtual_network_name      = azurerm_virtual_network.redactedVnet.name
  address_prefix            = "10.0.2.32/28"
}

resource "azurerm_subnet_network_security_group_association" "redactedSubnetNSG" {
  subnet_id                 = azurerm_subnet.redactedSubnet.id
  network_security_group_id = azurerm_network_security_group.redactedSubnet-NSG.id
}
```

### Debug Output
```hcl
# azurerm_subnet.redactedSubnet will be updated in-place
  ~ resource "azurerm_subnet" "redactedSubnet" {
        address_prefix                                 = "10.0.2.32/28"
        enforce_private_link_endpoint_network_policies = false
        enforce_private_link_service_network_policies  = false
        id                                             = "/subscriptions/1234/resourceGroups/redactedResources/providers/Microsoft.Network/virtualNetworks/redactedVnet/subnets/appgateway"
        ip_configurations                              = []
        name                                           = "appgateway"
      - network_security_group_id                      = "/subscriptions/1234/resourceGroups/VanadTransaviaResources/providers/Microsoft.Network/networkSecurityGroups/redactedSubnet-NSG" -> null
        resource_group_name                            = "redactedResources"
        service_endpoints                              = []
        virtual_network_name                           = "redactedVnet"
    }
```

### Expected Behavior

Subnet NSG should not have been attempting to delete. There were no changes.

### Actual Behavior

Whenever the plan is run, the NSG will be added or removed to the subnet, depending on whether it is present/absent (if absent, it will +, if present, it will -)

### Steps to Reproduce

Run the above code to apply a Network Security Group to a subnet, keep re-running the plan to see it add/delete the NSG.

**Comment by katbyte** [comment]
Hi @rdvansloten,

it looks like you are not configuring the subnet <-> NSG association on both resources as stated in the [doc](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html):
```
resource "azurerm_subnet" "redactedSubnet" {
  name                      = "appgateway"
  resource_group_name       = azurerm_resource_group.redactedResources.name
  virtual_network_name      = azurerm_virtual_network.redactedVnet.name
  network_security_group_id = azurerm_network_security_group.redactedSubnet-NSG.id
  address_prefix            = "10.0.2.32/28"
}

resource "azurerm_subnet_network_security_group_association" "redactedSubnetNSG" {
  subnet_id                 = azurerm_subnet.redactedSubnet.id
  network_security_group_id = azurerm_network_security_group.redactedSubnet-NSG.id
}
```

This should fix your issue. Please don't hesitate to reopen this issue if the issues still persists!

**Comment by rdvansloten** [comment]
Hi @katbyte 

That's indeed how I have fixed it, the reason I removed adding it to both is because Terraform keeps yelling at me for doing that.

```
Warning: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.
```

**Comment by davidtom** [comment]
I've had to do the same. While it works, its a bit annoying to have to continue using a deprecated argument because the new `azurerm_subnet_network_security_group_association` isn't working correctly yet. Would love to be able to update this and just move on.
