### ISSUE TITLE
New data source: azurerm_signalr_service

### ISSUE THREAD

**Issue by Henery309** [terraform-providers/terraform-provider-azurerm#5247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Request for implementing a signalr data source to retrieve signalR `primary_connection_string`. We query connection strings straight from azure (for servicebus etc) and apply them to web configurations. We can't do this for signalR as data source is not available.

### New or Affected Resource(s)
`azurerm_signalr_service`

#### Attributes to be returned in data source
```
id
hostname 
primary_access_key 
primary_connection_string
secondary_access_key 
secondary_connection_string 
```

### References

Link for creating signalR resource
https://www.terraform.io/docs/providers/azurerm/r/signalr_service.html

**Comment by brunhil** [comment]
I'll work on getting this added today!
