### ISSUE TITLE
azurerm_redis_cache zones doesn't support a list of zones

### ISSUE THREAD

**Issue by jdamata** [terraform-providers/terraform-provider-azurerm#5280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
provider.azurerm v1.39.0

### Affected Resource(s)

azurerm_redis_cache 

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "redis" {

  name                = "joel-basic-redis"
  location            = "EastUS2"
  resource_group_name = "redacted"
  capacity            = 0
  family              = "C"
  sku_name            = "Basic"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"
  zones               = ["1", "2", "3"]

  patch_schedule {
    day_of_week    = "Saturday"
    start_hour_utc = 0
  }
}
```

### Debug Output

```
Error: zones: attribute supports 1 item maximum, config has 3 declared

  on ../modules/redis/redis.tf line 7, in resource "azurerm_redis_cache" "redis":
   7: resource "azurerm_redis_cache" "redis" {
```

### Steps to Reproduce

1. `terraform plan`

**Comment by njuCZ** [comment]
@jdamata now the Azure Cache for Redis service does not support multiple zones, so there is such restriction in terraform. If multi zones feature is supported, we will get ride of this limitation

**Comment by jdamata** [comment]
It appears that multiple zones are supported 
looking at https://docs.microsoft.com/en-us/azure/templates/microsoft.cache/2018-03-01/redis and https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest#az-redis-create

**Comment by njuCZ** [comment]
@jdamata in the rest api, this field is actually an array, but currently it only supports one element: 1, 2 or 3. The service does not support multi-zones for now. you can try the az cli, it can only support one zone too
