### ISSUE TITLE
EventHub recreation does not recreate depended resources

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#5296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12.18
azurerm provider 1.39.0

### Affected Resource(s)

* `azurerm_eventhub`
* `azurerm_eventhub_authorization_rule`
* `azurerm_eventhub_consumer_group`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "alwayson" {
  name                = "${var.prefix}-ehnamespace"
  location            = azurerm_resource_group.alwayson.location
  resource_group_name = azurerm_resource_group.alwayson.name
  sku                 = "Standard"
  capacity            = 1
}

resource "azurerm_eventhub" "alwayson" {
  name                = "${var.prefix}-backend"
  namespace_name      = azurerm_eventhub_namespace.alwayson.name
  resource_group_name = azurerm_resource_group.alwayson.name

  partition_count   = 1
  message_retention = 1
}

resource "azurerm_eventhub_authorization_rule" "eh-sender-rule" {
  name                = "${var.prefix}-sender-rule"
  namespace_name      = azurerm_eventhub_namespace.alwayson.name
  eventhub_name       = azurerm_eventhub.alwayson.name
  resource_group_name = azurerm_resource_group.alwayson.name

  listen = false
  send   = true
  manage = false
}

resource "azurerm_eventhub_consumer_group" "alwayson" {
  name                = "${var.prefix}-becs"
  namespace_name      = azurerm_eventhub_namespace.alwayson.name
  eventhub_name       = azurerm_eventhub.alwayson.name
  resource_group_name = azurerm_resource_group.alwayson.name
}
```

### Expected Behavior

When an EventHub resource gets recreated, all depended resources, such as consumer groups and authorization rules need to be recreated as well.

### Actual Behavior

I had the above deployment configuration. All was deployed fine. Then I changed the partition count of the Event Hub to a higher value. This caused Terraform - correctly - to destroy and recreate the Event Hub. This also worked.
However, it did not recreate the consumer group, nor the authorization rule. Thus, the recreated event hub didn't have either of those.

When I ran the same deployment afterwards once again, `terraform plan` did recognize that those resources were now indeed missing and created them. However, this should already happen in the first deployment when the EventHub gets recreated.

### Steps to Reproduce

1. Apply the above mentioned configuration
2. Change the partition count and apply the configuration again.

### References

Kinda related to this: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2049

* #0000

**Comment by tombuildsstuff** [comment]
hey @sebader 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through it appears that the root-cause of this is a bug in Terraform Core where in a Grandparent-Parent-Child resource tree, that when recreating the Parent resource using a field other than `id` doesn't detect that the Child needs recreating.

Since this is a bug in Terraform Core, unfortunately this isn't something that we're able to fix in the Azure Provider directly - and as such I'm going to close this in favour of the upstream issue https://github.com/hashicorp/terraform/issues/24663 - would you mind subscribing to that issue for updates?

Thanks!
