### ISSUE TITLE
AzureGoverment fail to refresh token 

### ISSUE THREAD

**Issue by asetiawan** [terraform-providers/terraform-provider-azurerm#5302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
+ provider.azurerm v1.39.0

### Description
Similar to #5009 , azurerm works fine on public cloud. But I keep getting error for GovCloud subscriptions. 

Using the following test (using Azure Cloud Shell)
```
provider "azurerm" {
  version = "=1.39.0"
  subscription_id = "e7130eb0-<redacted>"
  environment = "usgovernment"
}

resource "azurerm_resource_group" "testrgroup" {
  name     = "terraformtestrgp"
  location = "usgovvirginia"
}
```

Running terraform plan/apply should work just fine

### Expected Behavior

Resource group created

### Actual Behavior
Running `az account show` gives me:

```
{
  "environmentName": "AzureUSGovernment",
  "id": "e7130eb0-<redacted>",
  "isDefault": true,
  "name": "Azure Government Pay-As-You-Go",
  "state": "Enabled",
  "tenantId": "56f7ef94-<redacted>",
  "user": {
    "cloudShellID": true,
    "name": "<myuser-redacted>@<myorg-redacted>.onmicrosoft.com",
    "type": "user"
  }
}
```

Received error  when running terraform apply/plan `No token found for audience https://management.usgovcloudapi.net`

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.usgovcloudapi.net/subscriptions/<redacted>/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"invalid_request","message":"No token found for audience https://management.usgovcloudapi.net"}}

  on blah.tf line 1, in provider "azurerm":
   1: provider "azurerm" {

```

### Steps to Reproduce

`terraform plan`

**Comment by edwinsummers** [comment]
I have the same issue in Cloudshell but works fine from a Linux environment. I used same Terraform file as OP (correcting the typo for 'usgovvirginia' and using my own subscription) and attempted a deployment using Azure Cloudshell. Cloudshell fails upon `terraform plan` with the same error as OP.

Running from a Linux VM however I can perform a successful deploy of the same file, with the same credential, and same version of Terraform, provider, and Az CLI.

**Versions** used in both cloudshell and Linux VM:

- Terraform 0.12.18
- Azurerm provider 1.39.0
- azure-cli 2.0.78
- command-modules-nspkg 2.0.3
- core 2.0.78
- nspkg 3.0.4
- telemetry 1.0.4

Between tests on cloudshell I logged out of Az cli and logged in both using the --identity argument as well as the normal method with no impact on result.

**Comment by edwinsummers** [comment]
I have an open support case with Azure regarding the issue. They indicated they've reproduced the problem and are working on a mitigation.

**Comment by edwinsummers** [comment]
@asetiawan This has been fixed by the Azure Cloudshell team according to my support case. My test cases are now working.

**Comment by asetiawan** [comment]
Thanks @edwinsummers . My test cases and other templates are working now.

**Comment by tombuildsstuff** [comment]
👋 

Based on the information above it sounds like this is resolved - and as such I'm going to close this issue for the moment - but if you're still seeing this then please let us know and we'll take another look

Thanks!
