### ISSUE TITLE
azurerm_container_group will panic with *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [terraform-providers/terraform-provider-azurerm#5304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

1.39

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "master" {
  name                = "epijmeter-master"
  location            = "${azurerm_resource_group.jmeter_rg.location}"
  resource_group_name = "${azurerm_resource_group.jmeter_rg.name}"

  ip_address_type = "private"
  os_type         = "Linux"

  network_profile_id = "${azurerm_network_profile.example.id}"

  restart_policy = "Never"

  container {
    name   = "jmeter"
    image  = "${var.jmeter_docker_image}"
    cpu    = "4.0"
    memory = "16.0"

    ports {
      port     = 1099
      protocol = "TCP"
    }

    volume {
      name                 = "jmeter"
      mount_path           = "/jmeter"
      read_only            = false
      storage_account_name = "${azurerm_storage_account.example.name}"
      storage_account_key  = "${azurerm_storage_account.example.primary_access_key}"
      share_name           = "${azurerm_storage_share.example.name}"
    }

    commands = [
      "/bin/sh",
      "-c",
      "cd /jmeter; jmeter -n -Jserver.rmi.ssl.disable=true -t DocumentApiMod_addNew.jmx -l test.jtl -e -o report -R ${join(",", "${azurerm_container_group.slaves.*.ip_address}")}",
    ]
  }
  depends_on = [azurerm_storage_account.example, azurerm_storage_share.example]
}

```

### Debug Output

```
2020/01/03 21:30:45 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing 
2020/01/03 21:30:45 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing 
2020/01/03 21:30:45 [TRACE] [walkRefresh] Exiting eval tree: azurerm_container_group.master 
2020/01/03 21:30:45 [TRACE] vertex "azurerm_container_group.master": visit complete 
2020/01/03 21:30:45 [TRACE] vertex "azurerm_container_group.master": dynamic subgraph encountered errors 
```

### Panic Output

[crash.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/4021161/crash.log)

### Expected Behavior

execute terraform apply twice, it works fine.

### Actual Behavior

execute terraform apply twice, it will panic. 

### Steps to Reproduce

1. terraform apply -auto-approve -var 'client_id=$(ARM_CLIENT_ID)' -var 'subscription_id=$(ARM_SUBSCRIPTION_ID)' -var 'client_secret=$(ARM_CLIENT_SECRET)' -var 'tenant_id=$(ARM_TENANT_ID)' -var 'jmeter_docker_image=$(image_name)'

2. execute the same terraform apply as 1. -> panic

### Important Factoids

no

### References
The root cause might be this line. According to the log, the response doesn't include IPAddress on property.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/resource_arm_container_group.go#L581

* #0000

**Comment by rfink** [comment]
So I'm having a pretty similar issue. Running plan -or- apply after container group is created.


Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing

Error: panic: runtime error: invalid memory address or nil pointer dereference
2020-01-21T18:06:28.669-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.41.0_x4.exe: [signal 0xc0000005 code=0x0 addr=0x0 pc=0x30a8176]
2020-01-21T18:06:28.669-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.41.0_x4.exe:
2020-01-21T18:06:28.669-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.41.0_x4.exe: goroutine 1155 [running]:
2020-01-21T18:06:28.669-0500 [DEBUG] plugin.terraform-provider-azurerm_v1.41.0_x4.exe: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/containers.resourceArmContainerGroupRead(0xc0005096c0, 0x397a000, 0xc000b86200, 0x0, 0x0)


Nothing changed between the successful create and the next plan.

Terraform = 0.12.19
AzureRM = 1.41.0
