### ISSUE TITLE
New Datasource for azurerm_storage_container

### ISSUE THREAD

**Issue by darren-johnson** [terraform-providers/terraform-provider-azurerm#5310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.16
provider.azurerm v1.39.0

### Description

It appears there is no data source for azurerm_storage_container which surprises me.  Can one please be created?

### New or Affected Resource(s)

azurerm_storage_container

**Comment by minzhang28** [comment]
👍

**Comment by minzhang28** [comment]
@tombuildsstuff I am interested in this implementation and I am a newbie to go, it's  a good chance for me to get hands on it but it might take me sometime to ramp up

**Comment by tracypholmes** [comment]
Closing as was fixed by #5374.
