### ISSUE TITLE
Add support for kubernetes-keyvault-flexvol addon to azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by ira-bryndzei** [terraform-providers/terraform-provider-azurerm#5317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add support  for [kubernetes-keyvault-flexvol](https://github.com/Azure/kubernetes-keyvault-flexvol) addon to` addon_profile` section in resource `azurerm_kubernetes_cluster` to create a new Kubernetes cluster with Key Vault FlexVolume already deployed.

### New or Affected Resource(s)

- azurerm_kubernetes_cluster

### Potential Terraform Configuration
```
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  ...
 addon_profile {
    keyvault-flexvol {
      enabled = true
    }
    kube_dashboard {
      enabled = false
    }
  }
}


```
### References
Keyvault-flexvolume documentation(https://github.com/Azure/aks-engine/blob/master/examples/addons/keyvault-flexvolume/README.md)
[Add-on documentation](https://github.com/Azure/aks-engine/blob/master/examples/addons/keyvault-flexvolume/README.md)

**Comment by syedhassaanahmed** [comment]
+1

**Comment by syedhassaanahmed** [comment]
+1

**Comment by olsemenov** [comment]
+

**Comment by tombuildsstuff** [comment]
👋 

Taking a look into this it appears that this has been superseded ([from the readme](https://github.com/Azure/kubernetes-keyvault-flexvol)) by https://github.com/Azure/secrets-store-csi-driver-provider-azure - as such I'm going to close this issue for the moment since it appears this functionality is deprecated/EOL.

Thanks!
