### ISSUE TITLE
Unable to create custom Azure Application Gateway WAF rule

### ISSUE THREAD

**Issue by darrenk13** [terraform-providers/terraform-provider-azurerm#5354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.19
+ provider.azurerm v1.40.0

### Affected Resource(s)

* ` azurerm_web_application_firewall_policy`

### Terraform Configuration Files

The below code is a subset from the example usage given on the doc page at https://www.terraform.io/docs/providers/azurerm/r/web_application_firewall_policy.html  I receive the same error using the full example from that page.

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "West US 2"
}

resource "azurerm_web_application_firewall_policy" "example" {
  name                = "example-wafpolicy"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  custom_rules {
    name      = "Rule1"
    priority  = 1
    rule_type = "MatchRule"

    match_conditions {
      match_variables {
        variable_name = "RemoteAddr"
      }

      operator           = "IPMatch"
      negation_condition = false
      match_values       = ["192.168.1.0/24", "10.0.0.0/24"]
    }

    action = "Block"
  }
}
```

### Debug Output

https://gist.github.com/darrenk13/ff308c5a34378cac9193ba6dc0b5168f

### Expected Behavior

Custom Application Gateway WAF rule should have been created.

### Actual Behavior

I received an error from Azure and the resource was not created.
```
Error: Error creating Web Application Firewall Policy "example-wafpolicy" (Resource Group "example-rg"): network.WebApplicationFirewallPoliciesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.WebApplicationFirewallPolicyPropertiesFormat.ManagedRules constraint=Null value=(*network.ManagedRulesDefinition)(nil) details: value can not be null; required parameter

  on main.tf line 6, in resource "azurerm_web_application_firewall_policy" "example":
   6: resource "azurerm_web_application_firewall_policy" "example" {
```

### Steps to Reproduce

1. `terraform apply`

### References

*  https://www.terraform.io/docs/providers/azurerm/r/web_application_firewall_policy.html

**Comment by HumanJoubert** [comment]
Hi 

Do we know if this issue has been fixed yet ?

**Comment by darrenk13** [comment]
> Do we know if this issue has been fixed yet ?

I just checked with the azurerm provider 2.0.0 and I am still seeing the same error message when I try to create this waf policy.

**Comment by HumanJoubert** [comment]
Do we have any idea when this will be fixed. Its a major blocker for me ?

**Comment by JleruOHeP** [comment]
Would be good to just add the option to specify the `ManagedRules` for WAF policies, if you want to create one for Front Door, for example and want to use only common rulesets, like "Microsoft_BotManagerRuleSet_1.0" or "DefaultRuleSet_1.0"

**Comment by sirlatrom** [comment]
I have a pull request coming up for this, will try and accommodate the suggested Terraform config.

**Comment by robert-kopec** [comment]
Hi, is this far from fixing?

**Comment by sirlatrom** [comment]
@robert-kopec Please follow #6126 for progress.

Any further ETA questions on this issue will _not_ help speed up the progress.

**Comment by sirlatrom** [comment]
I'd like to ask the existing users of this resource if they are currently depending on the property naming such as `custom_rules`, `match_variables`, etc. If they haven't been able to instantiate resources due to the bug mentioned in this issue, would they mind changing the property names to comply with the rest of the `azurerm_` resources such that you would have multiple `custom_rule` blocks instead of multiple `custom_rules` blocks?

On the other hand, if someone had _previously_ been able to instantiate resources of this type and are dependent on the property current naming scheme, I'd like to know that too.
