### ISSUE TITLE
Support for transforms in custom Azure web application firewall rules

### ISSUE THREAD

**Issue by darrenk13** [terraform-providers/terraform-provider-azurerm#5359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability to specify transformations in custom WAF rules for when "operator" is set to one of the following values:
* Contains
* Equal
* BeginsWith 
* EndsWith
* Regex
* LessThan
* LessThanOrEqual
* GreaterThan

This new field should be a list of transformations and be optional in the configuration.  The current set of transformations:
* HTMLEntityDecode
* Lowercase
* RemoveNulls
* Trim
* URLDecode
* URLEncode

### New or Affected Resource(s)

* azurerm_web_application_firewall_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_web_application_firewall_policy" "example" {
  name                = "example-wafpolicy"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  custom_rules {
    name      = "Rule9"
    priority  = 9
    rule_type = "MatchRule"

    match_conditions {
      match_variables {
        variable_name = "RequestHeaders"
        selector      = "UserAgent"
      }

      operator           = "Contains"
      negation_condition = false
      transformations    = ["Lowercase", "Trim"]
      match_values       = ["evilbot"]
    }

    action = "Block"
  }
}
```

### References

* https://www.terraform.io/docs/providers/azurerm/r/web_application_firewall_policy.html
* https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/create-custom-waf-rules#example-4

**Comment by magodo** [comment]
@darrenk13 Thank you for submitting this!
I'll create a PR for this.
