### ISSUE TITLE
azurerm_app_service: backup settings block, where does it go?

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#5365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_app_service`

### Description

Noticed on the [AzureRM App Service](https://www.terraform.io/docs/providers/azurerm/r/app_service.html) documentation that there is a backup block that would assume it allows for setting backups for Azure App Service. However, I don't see where exactly the backup block would go in the configuration. Is it part of site_config block or the parent azurerm_app_service resource? Is this still even a feature of azurem_app_service? Issue #2569 is still open and it relates to backups.

**Comment by tombuildsstuff** [comment]
hey @bcline760 

Thanks for opening this issue - apologies for the delayed reply here!

Taking a look into this this appears to be an oversight in the documentation - the `backup` block is available at the top-level of the `azurerm_app_service` resource - I've opened #5687 to add this back to the documentation.

Thanks!
