### ISSUE TITLE
Missing key vault certificate permissions

### ISSUE THREAD

**Issue by JasonNguyenTX** [terraform-providers/terraform-provider-azurerm#538]
For certificate_permissions, purge, recover, and all are not accepted as permissions.  Can these be added?

**Comment by tombuildsstuff** [comment]
Hi @JasonNguyenTX 

Thanks for opening this issue :)

We previously supported the `all` permission across the KeyVault Permissions - however support for this has been removed by Azure in favour of listing each permission individually - so we're unable to support this unfortunately.

From what I can see `Purge` and `Recover` have also been deprecated - would it be possible to give an example usage of these? Here's the values for this field available in the Azure SDK for Go:

```
// KeyUsageType enumerates the values for key usage type.
type KeyUsageType string

const (
	// CRLSign specifies the crl sign state for key usage type.
	CRLSign KeyUsageType = "cRLSign"
	// DataEncipherment specifies the data encipherment state for key usage type.
	DataEncipherment KeyUsageType = "dataEncipherment"
	// DecipherOnly specifies the decipher only state for key usage type.
	DecipherOnly KeyUsageType = "decipherOnly"
	// DigitalSignature specifies the digital signature state for key usage type.
	DigitalSignature KeyUsageType = "digitalSignature"
	// EncipherOnly specifies the encipher only state for key usage type.
	EncipherOnly KeyUsageType = "encipherOnly"
	// KeyAgreement specifies the key agreement state for key usage type.
	KeyAgreement KeyUsageType = "keyAgreement"
	// KeyCertSign specifies the key cert sign state for key usage type.
	KeyCertSign KeyUsageType = "keyCertSign"
	// KeyEncipherment specifies the key encipherment state for key usage type.
	KeyEncipherment KeyUsageType = "keyEncipherment"
	// NonRepudiation specifies the non repudiation state for key usage type.
	NonRepudiation KeyUsageType = "nonRepudiation"
)
```

Thanks!

**Comment by tombuildsstuff** [comment]
ping @JasonNguyenTX :)

**Comment by tombuildsstuff** [comment]
Hi @JasonNguyenTX 

Given we've not heard back from you here, I'm going to close this issue for the moment - that said please feel free to re-open this if you're still having issues here and we'll take another look.

Thanks!
