### ISSUE TITLE
azurerm_kubernetes_cluster does not expose vmss principal_id

### ISSUE THREAD

**Issue by robgil-dds** [terraform-providers/terraform-provider-azurerm#5388]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.12.19
Azurerm: 1.40.0

### Affected Resource(s)

- `azurerm_kubernetes_cluster`
- `azurerm_kubernetes_node_pool`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "k8s" {
  name     = "${var.name}-${var.environment}-k8s-test"
  location = var.region
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.name}-${var.environment}-k8s-test"
  location            = azurerm_resource_group.k8s.location
  resource_group_name = azurerm_resource_group.k8s.name
  dns_prefix          = var.k8s_dns_prefix

  service_principal {
    client_id     = ***
    client_secret = ***
  }

  default_node_pool {
    name                  = "default"
    vm_size               = "Standard_D1_v2"
    os_disk_size_gb       = 30
    vnet_subnet_id        = module.vpc.subnets
    enable_node_public_ip = true
    enable_auto_scaling   = true
    max_count             = 2
    min_count             = 1
  }

  identity {
    type = "SystemAssigned"
  }
  lifecycle {
    ignore_changes = [
      default_node_pool.0.node_count
    ]
  }

  tags = {
    environment = var.environment
    owner       = var.owner
  }
}
```
Note the following
```
  identity {
    type = "SystemAssigned"
  }
```

### Expected Behavior
Both resources should expose the `principal_id` of the vmss. This is necessary for use in other resources such as `azurerm_keyvault_access_policy`.

Example keyvault access policy
```
resource "azurerm_key_vault_access_policy" "keyvault" {
  key_vault_id = azurerm_key_vault.keyvault.id

  tenant_id = data.azurerm_client_config.current.tenant_id
  object_id = azurerm_kubernetes_cluster.k8s.identity[0].principal_id

  key_permissions = [
    "get",
  ]

  secret_permissions = [
    "get",
  ]
}
```

### Actual Behavior
The principal_id returned is that of the kubernetes cluster, not the vmss. Ideally both are returned to be used for different permissioning. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
This is a typical use case with mounting FlexVol keyvault volumes in k8s. This configuration uses a SystemAssigned identity (which is now the default in `azurerm_kubernetes_cluster`)

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here this is available via the exported `identity` block as the field `principal_id` - which can be accessed as `azurerm_kubernetes_cluster.k8s.identity.0.principal_id` - as such I'm going to close this issue for the moment.

Thanks!
