### ISSUE TITLE
Is there a way to associate an Integration Service Environment with Logic Apps via Terraform?

### ISSUE THREAD

**Issue by ved3690** [terraform-providers/terraform-provider-azurerm#5390]
Is there a way to associate an Integration Service Environment with Logic Apps via Terraform?

I have been trying various options over the past few days and could n 't get the Logic Apps listed under the Logic Apps section in ISE via Terraform.

Could you please suggest.

Thanks in advance…

**Comment by slessardjr** [comment]
Does anyone else have any guidance on this?  I have a need to do this as well

**Comment by tombuildsstuff** [comment]
Thanks for the heads up @slessardjr 

Closing as a duplicate of #2106 - would you mind subscribing to that issue for updates?
