### ISSUE TITLE
Front Door resource creates a second frontend_endpoint when not told to

### ISSUE THREAD

**Issue by devblackops** [terraform-providers/terraform-provider-azurerm#5411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.10
  - provider.azurerm v1.39.0

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "fd" {
  name                = "${var.prefix}-fd1"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags

  routing_rule {
    name               = "routing-rule"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = [
      "frontendendpoint"
    ]

    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "backend"
    }
  }

  enforce_backend_pools_certificate_name_check = true

  backend_pool_load_balancing {
    name = "loadbalancing-settings"
  }

  backend_pool_health_probe {
    name                = "health-probe"
    path                = var.probe_path
    protocol            = var.health_probe_protocol
    interval_in_seconds = 30
  }

  backend_pool {
    name = "backend"
    backend {
      host_header = var.site_fqdn
      address     = var.appgw_fqdn
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = "loadbalancing-settings"
    health_probe_name   = "health-probe"
  }

  frontend_endpoint {
    name                              = "frontendendpoint"
    host_name                         = var.site_fqdn
    custom_https_provisioning_enabled = true

    custom_https_configuration {
      certificate_source                         = "AzureKeyVault"
      azure_key_vault_certificate_vault_id       = var.certificate_keyvault_id
      azure_key_vault_certificate_secret_name    = var.certificate_keyvault_secret_name
      azure_key_vault_certificate_secret_version = var.certificate_keyvault_secret_version
    }
  }
}
```

### Expected Behavior

When creating a frontend endpoint with custom DNS and SSL certificate, only one endpoint should be created.

### Actual Behavior

Along with the endpoint defined in the TF resource that uses a custom DNS name and certificate, a **second** endpoint is always created with the default endpoint name of `<front-door-name>.azurefd.net`. This second endpoint is not in the [TF plan output](https://gist.github.com/devblackops/7a71173b03a0bace5044fb430a44976a) when the FD resource is created.

When running `terraform apply` a second time, immediately after the first, and without changing anything, Terraform wants to remove this extra endpoint.

```
  frontend_endpoint {
    custom_https_provisioning_enabled = true
    host_name                         = "XXXXX"
    id                                = "XXXXX"
    name                              = "frontendendpoint"
    session_affinity_enabled          = false
    session_affinity_ttl_seconds      = 0

    custom_https_configuration {
        azure_key_vault_certificate_secret_name    = "XXXXX"
        azure_key_vault_certificate_secret_version = "XXXXX"
        azure_key_vault_certificate_vault_id       = "XXXXX"
        certificate_source                         = "AzureKeyVault"
        provisioning_state                         = "Enabled"
        provisioning_substate                      = "CertificateDeployed"
    }
  }
  - frontend_endpoint {
    - custom_https_provisioning_enabled = false -> null
    - host_name                         = "XXXXX" -> null
    - id                                = "XXXXX" -> null
    - name                              = "defaultHostName" -> null
    - session_affinity_enabled          = true -> null
    - session_affinity_ttl_seconds      = 0 -> null
  }
```

We've worked around this by explicitly defining this second endpoint in Terraform but the behavior is unexpected.

### Steps to Reproduce

1. Create a Front Door resource with a custom DNS name and certificate
2. `terraform apply`
3. Observe that a second endpoint is created.
4. Run `terraform plan` and observe that Terraform wants to remove this extra endpoint.

### References

- [TF plan showing no second endpoint to create](https://gist.github.com/devblackops/7a71173b03a0bace5044fb430a44976a)

**Comment by kingsleyadam** [comment]
The work-around, for now, is to add this front-end block to the FrontDoor config.

```
frontend_endpoint {
  name                              = "defaultHostName"
  host_name                         = "${var.name}.azurefd.net"
  custom_https_provisioning_enabled = false
}
```

Where `var.name` is the name of your FrontDoor resource.

**Comment by kensykora** [comment]
Please be aware, this behavior currently prevents apex level domain names from being mapped to frontdoor. The default domain is required for apex domains (e.g., domain.com vs sub.domain.com) to work properly with frontdoor.

We ran into this issue. We didn't intentionally want the default domain to be removed, but we didn't necessarily NEED it either. Regardless, it took a support case with Microsoft to discover this was happening. The error we'd run into when trying to map an apex domain name to frontdoor through Azure DNS:

```
Operation failed with status: ‘Bad Request’. Details: The referenced resource ‘/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/paas-prod/providers/Microsoft.Network/frontdoors/paas-prod-fd’ was not found
/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/paas-prod/providers/Microsoft.Network/frontdoors/paas-prod-fd
```

When the front door very much did exist. Apparently you're not supposed to remove the default domain name. I'm not sure if the management API is going to try and prevent fremoving the default domain this in the future or not, but it's required for a custom apex record mapped to frontdoor (since cname can't be used on apex domains)

**Comment by WodansSon** [comment]
As @michaelelleby mentioned in issue #8848:
> Azure created a workaround for apex domains: You have to create a regular CNAME record in your DNS, mapping afdverify.<yourdomain> to afdverify.<your front door name>.azurefd.net and then you can deploy Azure Front Door with a frontendEndpoint listening on that apex domain. [product documentation](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-custom-domain#map-the-temporary-afdverify-subdomain)

With that said I am going to go ahead and close this issue as it appears to be a configuration issue which Azure has offered a fix for. Thank you for reporting this issue.
