### ISSUE TITLE
Support for [Azure NetApp Files] - Create volume no IP address in the attributes

### ISSUE THREAD

**Issue by sudev5678** [terraform-providers/terraform-provider-azurerm#5416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When an Azure NetApp files volume is created, it does not output the full mount path. Currently, only the volume path (name) is provided in the output. Can we please add the IP address for the volume as well to the attributes section for the data source? 

### New or Affected Resource(s)

azurerm_netapp_volume

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://www.terraform.io/docs/providers/azurerm/d/netapp_volume.html

* #0000

**Comment by anhowe** [comment]
While we wait for the PR to be approved, a workaround is to use the template and extract the mountTarget IP Address from the ARM Output Variable.  This approach is implemented [here](https://github.com/Azure/Avere/blob/fa2c74709d5f9f9ec7bf807b42661ac7d24eea3f/src/terraform/examples/HPC%20Cache/netapp/main.tf#L99-L123) and the extraction of the output ipaddress is shown [here](https://github.com/Azure/Avere/blob/fa2c74709d5f9f9ec7bf807b42661ac7d24eea3f/src/terraform/examples/HPC%20Cache/netapp/main.tf#L195).
