### ISSUE TITLE
Providing a terraform-created log analytics workspace ID to kubernetes resource doesn't work

### ISSUE THREAD

**Issue by uipo78** [terraform-providers/terraform-provider-azurerm#5437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform version: 0.12.5
azurerm provider version: 1.41.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`
* `azurerm_log_analytics_workspace`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.41.0"
}

provider "random" {
  version = "~> 2.1.0"
}

resource "azurerm_resource_group" "example" {
  name = "example"
  location = "eastus"
}

resource "azurerm_log_analytics_workspace" "workspace" {
  name                = "k8s-workspace"
  location            = "eastus"
  resource_group_name = "example"
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azuread_application" "service_principal_app" {
  name = "mycluster"
}

resource "azuread_service_principal" "service_principal" {
  application_id = "${azuread_application.service_principal_app.application_id}"
}

resource "random_string" "service_principal_random_password" {
  length  = 16
  special = true

  keepers = {
    service_principal = "${azuread_service_principal.service_principal.id}"
  }
}


resource "azuread_service_principal_password" "service_principal_password" {
  service_principal_id = "${azuread_service_principal.service_principal.id}"
  value                = "${random_string.service_principal_random_password.result}"
  # 8760h = 1 year
  end_date             = "${timeadd(timestamp(), "8760h")}"
  lifecycle {
      ignore_changes = ["end_date"]
  }
  provisioner "local-exec" {
      command = "sleep 30"
  }
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                       = "mycluster"
  location                   = "eastus"
  resource_group_name        = "example"
  dns_prefix                 = "mycluster"


  service_principal {
    client_id     = "${azuread_service_principal.service_principal.application_id}"
    client_secret = "${random_string.service_principal_random_password.result}"
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = "${azurerm_log_analytics_workspace.workspace.id}"
    }
  }
 }
```

### Debug Output

Because of the way that my company uses terraform, I am unable to provide this.

### Expected Behavior

All of the resources should've been created.

### Actual Behavior

I received this error:
```
Can not parse "addon_profile.0.oms_agent.0.log_analytics_workspace_id" as a resource id: Cannot parse Azure ID: parse azurerm_log_analytics_workspace.workspace.id: invalid URI for request
```

### Steps to Reproduce

Assuming you have a backend set up and everything, all you'll need to do is apply the configuration that I've provided above.

### References

* #0000

**Comment by VijayRajagopalan-STW** [comment]
Hello @tracypholmes 

I have a similar issue, but with a different resource "azurerm_monitor_diagnostic_setting". I tried to pass log_analytics_workspace_id as a string, but got an error "Can not parse "log_analytics_workspace_id" as a resource id: Cannot parse Azure ID: parse xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx: invalid URI for request".

Could you please help? Thanks.

**Comment by goutammyneni** [comment]
Hello @uipo78 @VijayRajagopalan-STW \

you have to pass log_analytics_workspace_id as in this format "/subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupName>/providers/Microsoft.OperationalInsights/workspaces/<WorkspaceName>".

**Comment by VijayRajagopalan-STW** [comment]
Thanks @goutammyneni

**Comment by uipo78** [comment]
@VijayRajagopalan-STW did it work for you? I wasn't able to get it working with either of these:

`/subscriptions/${var.subscription_id}/resourceGroups/${var.resource_group_name}/providers/Microsoft.OperationalInsights/workspaces/${azurerm_log_analytics_workspace.workspace.id}`

`/subscriptions/${var.subscription_id}/resourceGroups/${var.resource_group_name}/providers/Microsoft.OperationalInsights/workspaces/${azurerm_log_analytics_workspace.workspace.workspace_id}`

**Comment by VijayRajagopalan-STW** [comment]
@uipo78. Yes, it worked for me in my case.

I used data source to query the log analytics workspace resource and used the id attribute

`data.azurerm_log_analytics_workspace.log_analytics_workspace.id`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems these resources can be created successfully after tested with below tfconfig which is similar with your config. Maybe I missed something. If you need, you can try below tf config to check whether the problem still exists.

tfconfig:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name = "acctestRG-aks-neil"
  location = "eastus"
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "k8s-workspace-neil"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_kubernetes_cluster" "test" {
  name                       = "neilakscluster"
  location                   = azurerm_resource_group.test.location
  resource_group_name        = azurerm_resource_group.test.name
  dns_prefix                 = "neilakscluster"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
  }

  service_principal {
    client_id     = "<insert your client id>"
    client_secret = "<insert your client secret>"
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.test.id
    }
  }
}
```

Result:
```
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
Outputs:
log_analytics_workspace_id = /subscriptions/xxx-xxx-xxx-xxx/resourcegroups/acctestrg-aks-neil/providers/microsoft.operationalinsights/workspaces/k8s-workspace-neil
```

**Comment by mybayern1974** [comment]
Hi @uipo78 

Glad to see you’ve got unblocked : ) Would you ok we close this issue for now? Feel free to reopen it if you run into it again. Thank you.
