### ISSUE TITLE
How to execute commands on AKS cluster?

### ISSUE THREAD

**Issue by jay8127** [terraform-providers/terraform-provider-azurerm#5438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files
locals {
  admin_username       = "testadmin"
  admin_password       = "Password1234!"
}

# Configure the Microsoft Azure Provider
provider "azurerm" {
    subscription_id = "${var.subscription_id}"
    client_id       = "${var.client_id}"
    client_secret   = "${var.client_secret}"
    tenant_id       = "${var.tenant_id}"
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-k8s-resources"
  location = "${var.location}"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "${var.prefix}-k8s"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  dns_prefix          = "${var.prefix}-k8s"

  linux_profile {
    admin_username = "${var.admin_username}"

    ssh_key {
        key_data = "${file("${var.ssh_public_key}")}"
    }
  }

  default_node_pool {
    name            = "agentpool"
    node_count      = "${var.agent_count}"
    vm_size         = "${var.vm_size}"
  }

  service_principal {
    client_id     = "${var.kubernetes_client_id}"
    client_secret = "${var.kubernetes_client_secret}"
  }

  tags = {
    Environment = "Production"
  }

}
output "client_certificate" {
  value = "${azurerm_kubernetes_cluster.example.kube_config.0.client_certificate}"
}
output "client_key" {
  value = "${azurerm_kubernetes_cluster.example.kube_config.0.client_key}"
}

output "host" {
  value = "${azurerm_kubernetes_cluster.example.kube_config.0.host}"
}
output "dns" {
  value = "${azurerm_kubernetes_cluster.example.kube_config.0.host}"
}
output "cluster_ca_certificate" {
  value = "${azurerm_kubernetes_cluster.example.kube_config.0.cluster_ca_certificate}"
}

output "kube_config" {
  value = "${azurerm_kubernetes_cluster.example.kube_config_raw}"
}

provider "kubernetes" {
  host = "${var.host_ip_address}"

...
}

resource "kubernetes_deployment" "jenkins-master" {
  metadata {
...
    }
  }
  spec {
    replicas = 1

...
      }
    }
  }
}

resource "kubernetes_service" "jenkins-master" {
  metadata {
...
  }
  spec {
    type = "LoadBalancer"
    selector = {
...
    }
    port {
  ..
    }
  }
}

### Debug Output
I created AKS. And using Kubernetes provider, set up container on it. I am trying to SSH into the cluster, execute some commands but it times out.

### Panic Output
I tried to SSH from another VM into cluster, as well my local to the cluster, both times out.

### Expected Behavior
SSH connection times out.

### Actual Behavior
Should be able to SSH into the AKS cluster and execute kubectl commands

### Steps to Reproduce
1. `terraform apply`
2. SSH into cluster using private/public key

**Comment by tombuildsstuff** [comment]
hi @jay8127 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!

**Comment by tombuildsstuff** [comment]
@jay8127 apologies looks like I posted the wrong link here - the community specific link is here: https://www.terraform.io/community.html
