### ISSUE TITLE
azure_storage_queue when creating a new queue the api is returning an unexpected 204 

### ISSUE THREAD

**Issue by izhelevJG** [terraform-providers/terraform-provider-azurerm#545]
When trying to create a new queue, I am getting the following error: 

```
Error creating storage queue on Azure: storage: status code from service response is 204 No Content; was expecting 201 Created
```

Reading the azure API documentation, it states that the response will return a 204 if you try and PUT a queue that already exists, but in this case, this resource does not. The result from running apply does create the queue as intended but it does not update the terraform state. 

It looks like they might have to change the way their API is working.

**Comment by katbyte** [comment]
Hi @izhelevJG,

I have run our tests and storage queues now create so i am going to close this issue. Please don't hesitate to reopen this with some additional details if you are still having a problem!

thanks
