### ISSUE TITLE
 azurerm_cosmosdb_sql_container needs TTL settings

### ISSUE THREAD

**Issue by md-waldron** [terraform-providers/terraform-provider-azurerm#5451]
### Description ###
Currently there is no setting in `azurerm_cosmosdb_sql_container` for TTL configuration. This is a key feature of CosmosDb collections and without it the TTL overrides at the item level cannot be set. 
https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live

### New or Affected Resource(s)  ###
azurerm_cosmosdb_sql_container

### Potential Terraform Configuration ### 
```
resource "azurerm_cosmosdb_sql_container" "example" {
  name                = "example-container"
  resource_group_name = "${azurerm_cosmosdb_account.example.resource_group_name}"
  account_name        = "${azurerm_cosmosdb_account.example.name}"
  database_name       = "${azurerm_cosmosdb_sql_database.example.name}"
  partition_key_path  = "/definition/id"
  ttl                 = 1000

  unique_key {
    paths = ["/definition/idlong", "/definition/idshort"]
  }
}
```
### References ###
This was mentioned in a previously closed issue. The resolution only addressed part of the issue (throughput) but sadly not the TTL part.
#4802

**Comment by aqche** [comment]
taking a look into this. will have a PR up shortly!
