### ISSUE TITLE
Support for App Service Slots with azurerm_app_service_virtual_network_swift_connection

### ISSUE THREAD

**Issue by Muxxx** [terraform-providers/terraform-provider-azurerm#5458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider now (as of v1.40) supports Regional VNet integrations, although they are limited to only App Services (Web Services), not their slots. When trying to use the swift_connection resource against a slot, TF accepts the configuration, although it creates the VNet integration for the App Service associated with the targeted slot, not the slot itself.

This feature request is to add support, either with a separate resource, or within the current resource, for App Service Slots.

### New or Affected Resource(s)

* azurerm_app_service_slot_virtual_network_swift_connection (suggested resource name)

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "Australia East"
}

resource "azurerm_virtual_network" "test" {
  name                = "test"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "test"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.1.0/24"

  delegation {
    name = "testdelegation"

    service_delegation {
      name    = "Microsoft.Web/serverFarms"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_app_service_plan" "test" {
  name                = "test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "test" {
  name                = "test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  app_service_plan_id = azurerm_app_service_plan.test.id
}

resource "azurerm_app_service_slot" "test" {
  name                = "staging"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  app_service_name        = azurerm_app_service.test.name
  app_service_plan_id = azurerm_app_service_plan.test.id
}

resource "azurerm_app_service_slot_virtual_network_swift_connection" "test" {
  app_service_id                  = azurerm_app_service_slot.test.id
  subnet_id                       = azurerm_subnet.test.id
}
```

### References

* I cannot find any GitHub issues / requests regarding this

**Comment by rudolphjacksonm** [comment]
@Muxxx I'm in the same boat--we want to add VNet integration at the slot level but it doesn't seem to be supported yet. Curiously enough I tried the same code you proposed in your solution and it doesn't give me an error on a `plan` or an `apply` however it doesn't set up the VNet integration either.

**Comment by jetsetwilly1** [comment]
Has anything progressed with this? As @rudolphjacksonm said there is no error thrown when attempting to set Vnet integration on a slot.  If i run an `apply` it looks like everything has run through successfully. Is there an update on this?

**Comment by christophecremon** [comment]
Same for me: waiting for an answer since no error is produced but config is not applied on the slot...

**Comment by Muxxx** [comment]
> Same for me: waiting for an answer since no error is produced but config is not applied on the slot...

If you attempt to target a slot with that code, it modifies the associated app service, that’s why it doesn’t error. It just won’t actually change the slot though.
