### ISSUE TITLE
Policy Assignment Referring to a Resource in a Different Subscription

### ISSUE THREAD

**Issue by dan-gibbons** [terraform-providers/terraform-provider-azurerm#5462]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
Azurerm Provider v1.40.0

### Affected Resource(s)

* `azurerm_policy_assignment`
* `azurerm_role_assignment`

N.B Trying to deploy the built-in policy initiative `[Preview]: Enable Azure Monitor for VMs`.

### Log Analytics Deployment

**1. main.tf**
```hcl
provider "azurerm" {
  version = "=1.40.0"
}

resource "azurerm_resource_group" "mon_rg" {
  name     = "monrg"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "mon_analytics_workspace" {
  name                = "my-unique-analyticsworkspace"
  location            = azurerm_resource_group.mon_rg.location
  resource_group_name = azurerm_resource_group.mon_rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 90
}

resource "azurerm_log_analytics_solution" "mon_service_map_solution" {
  solution_name         = "ServiceMap"
  location              = azurerm_resource_group.mon_rg.location
  resource_group_name   = azurerm_resource_group.mon_rg.name
  workspace_resource_id = azurerm_log_analytics_workspace.mon_analytics_workspace.id
  workspace_name        = azurerm_log_analytics_workspace.mon_analytics_workspace.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ServiceMap"
  }
}

output "log_analytics_workspace_id" {
  value = azurerm_log_analytics_workspace.mon_analytics_workspace.id
}
```

**Copy output of `log_analytics_workspace_id` in to the variables with the placeholder:
"<LOG_ANALYTICS_WORKSPACE_ID>"**

### Policy Initiative Deployment

**1. main.tf**
```hcl
provider "azurerm" {
  version = "=1.40.0"
}

data "azurerm_subscription" "current" {}

resource "azurerm_policy_assignment" "policy_monitor_vms" {
  name                 = "policy-monitor-vms"
  location             = "UK South"
  scope                = "/subscriptions/${data.azurerm_subscription.current.subscription_id}"
  policy_definition_id = "/providers/Microsoft.Authorization/policySetDefinitions/55f3eceb-5573-4f18-9695-226972c6d74a"
  display_name         = "[Preview]: Enable Azure Monitor for VMs"

  parameters = <<PARAMETERS
  {
    "logAnalytics_1": {
      "value": "<LOG_ANALYTICS_WORKSPACE_ID>"
    }
  }
  PARAMETERS

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_role_assignment" "policy_monitor_vms_role_assignment" {
  role_definition_name = "Log Analytics Contributor"
  scope                = "<LOG_ANALYTICS_WORKSPACE_ID>"
  principal_id         = azurerm_policy_assignment.policy_monitor_vms.identity[0].principal_id
}
```

### Expected Behavior

The policy initiative should be linked to the `Log Analytics Workspace` and require no manual intervention to come in to effect.

### Actual Behavior

1. When the policy initiative is deployed in the same subscription as the `Log Analytics Workspace` the initiative links up correctly and requires no manual intervention.

2. When the policy initiative is deployed in a different subscription to the `Log Analytics Workspace` the initiative doesn't link up correctly and it requires you to manually edit the initiative and then save it (making no changes to the initiative settings) before it comes in to effect.

### Steps to Reproduce

Ensure you can deploy to two different Azure Subscriptions - we'll call them `SUB1` and `SUB2`.

* Deploy a `Log Analytics Workspace` using `SUB1`.
* Deploy the initiative using `SUB2`
* Deploy a VM to `SUB2` and verify that the VM does not report to the `Log Analytics Workspace` in `SUB1`.
* Manually Edit the initiative created in `SUB2` as outlined in step 2 of `Actual Behaviour`.
* Deploy another VM to `SUB2` and verify that the VM does report to the `Log Analytics Workspace` in `SUB1`.

**Comment by vholubek** [comment]
Same problem here. It seems like when the policy assignment parameter is referencing a resource from another subscription, the metadata object of the policy properties object needs additional argument **parameterScopes**. Terraform is not creating this argument.

Example of a 'healthy' policy assignment that references a Log Analytics Workspace from another subscription as a policy assignment parameter:

```
"Properties": {
    
    "displayName":  "xxxx",
    "policyDefinitionId":  "xxxx",

    "parameters": {
        "logAnalytics": {
            "value": "/subscriptions/11111111-2222-3333-4444-555555555555/resourcegroups/xxxx/providers/microsoft.operationalinsights/workspaces/yyyy"
        }
    },
    
    "metadata": {
        "parameterScopes": {
            "logAnalytics": "/subscriptions/11111111-2222-3333-4444-555555555555"
        },

    }
}
```

Here's a PowerShell script to manually fix this issue post creation.:
`Set-AzureRmPolicyAssignment -Id "<policyId>" -Metadata '{"parameterScopes":  {"logAnalytics":  "/subscriptions/11111111-2222-3333-4444-555555555555"}}'`

**Comment by lubbers** [comment]
Having the same issue here as well with the built-in Azure Policy: "Enable Security Center's auto provisioning of the Log Analytics agent on your subscriptions with custom workspace." Whenever the policy is assigned to the subscription successfully, the Log Analytics workspace which live in another subscription will not populate as part of the parameters of the assignment.

`resource "azurerm_policy_assignment" "autoenable_asc_laa_customworkspace_assignment" {
  name                 = "Auto provision the Log Analytics agent with custom workspace"
  scope                = data.azurerm_subscription.current.id
  policy_definition_id = data.azurerm_policy_definition.autoenable_asc_laa_customworkspace_policy.id
  description          = "Policy Assignment created via an Unit Test"
  display_name         = "Auto provision the Log Analytics agent with custom workspace"
  location             = "East US 2"
  identity {
    type = "SystemAssigned"
  }
  parameters = <<PARAMETERS
{
  "logAnalytics": {
    "value": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/<ResourceGroupName>/providers/microsoft.operationalinsights/workspaces/<LogAnalyticsWorkspaceName>"
  }
}
PARAMETERS
}`

**Comment by gettek** [comment]
Since you are providing the full resource ID, the way around this is to remove `strongType` from the [parameter properties](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#parameter-properties). This ultimately means you must create your own custom definition from the Built-in one. 

Using Terraform this can be achieved with the replace function:

```hcl
data azurerm_policy_definition def {
  display_name = "Enable Security Center's auto provisioning of the Log Analytics agent on your subscriptions with custom workspace."
}

provider azurerm {
  features {}
}

resource azurerm_policy_definition def {
  name                = "asc_auto_deploy_la_agent"
  display_name        = "[Custom]: ${data.azurerm_policy_definition.def.display_name}"
  description         = data.azurerm_policy_definition.def.discription
  policy_type         = "Custom"
  mode                = "All"
  management_group_id = var.definition_scope_mg_id

  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      metadata,
    ]
  }

  # remove the OMS strongType
  parameters  = replace(data.azurerm_policy_definition.def.parameters, ",\"strongType\":\"omsWorkspace\"", "")
  metadata    = data.azurerm_policy_definition.def.metadata
  # edit the default assignment effect
  policy_rule = replace(data.azurerm_policy_definition.def.policy_rule, "\"effect\":\"DeployIfNotExists\"", "\"effect\":\"Disabled\"")
}
```

**Comment by tombuildsstuff** [comment]
Closing this out since this can be achieved as [in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/5462#issuecomment-716604066) - thanks @gettek
