### ISSUE TITLE
case sensitivity: azurerm_public_ip public_ip_address_allocation -> allocation_method enforces case sensitivity

### ISSUE THREAD

**Issue by drewmullen** [terraform-providers/terraform-provider-azurerm#5463]
azurerm provider should not be concerned with case sensitivity

### Terraform (and AzureRM Provider) Version

```
terraform -v
Terraform v0.12.18
+ provider.azuread v0.6.0
+ provider.azurerm v1.34.0
+ provider.local v1.4.0
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* `azurerm_public_ip`

### Terraform Configuration Files

WORKS
```hcl
resource "azurerm_public_ip" "azlb" {
  name                         = "${var.lb_prefix}-publicIP"
  location                     = var.location
  resource_group_name          = var.resource_group_name
  public_ip_address_allocation = "static"
  domain_name_label            = var.public_ip_dns
  sku                          = var.vault_lb_sku
}
```

FAILS
```hcl
resource "azurerm_public_ip" "azlb" {
  name                         = "${var.lb_prefix}-publicIP"
  location                     = var.location
  resource_group_name          = var.resource_group_name
  allocation_method            = "static"
  domain_name_label            = var.public_ip_dns
  sku                          = var.vault_lb_sku
}
```

OUTPUT
```
Error: expected allocation_method to be one of [Static Dynamic], got static

  on lb.tf line 7, in resource "azurerm_public_ip" "azlb":
   7: resource "azurerm_public_ip" "azlb" {
```

**Comment by tombuildsstuff** [comment]
hi @drewmullen 

Thanks for opening this issue.

Over the years we've spent a great deal of time working around case sensitivity/insensitivity issues in the Azure API. Unfortunately in this instance there's downstream dependencies which require the casing matches exactly - and so whilst the Azure API may allow a case-insensitive comparison in certain circumstances this ends up causing hard-to-debug issues downstream.

What this means in practice is that all new fields are case-sensitive by default - and we'll be retroactively making existing fields case-sensitive over time too. This should both ensure that downstream API's work as expected (as we add support for them) and ultimately matches the UX of other Terraform Providers which are case-sensitive.

As such unfortunately we have no plans to make this field case-insensitive and I'm going to close this issue for the moment; but you should be able to fix this by updating `static` to `Static` in your Terraform Configuration.

Thanks!
