### ISSUE TITLE
Terraform deletes Log Analytic Workspace resource without deleting the naming resource

### ISSUE THREAD

**Issue by thllxb** [terraform-providers/terraform-provider-azurerm#5465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
AzureRM: 1.38.0
Terraform: 0.12.18

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Panic Output

`Error: operationalinsights.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="Conflict" Message="The workspace name 'my-log-analytic-workspace-XXX' is not unique" Target="name"`

### Expected Behavior

After Terraform deletes one Log Analytic Workspace resource, a new one with the same name should be able to be recreated right after.
### Actual Behavior

After Terraform deletes on Log Analytic Workspace resource, a new one with the same name cannot be recreated within the next 14 days.
### Steps to Reproduce

1. `terraform destroy`

### References

* https://docs.microsoft.com/en-us/azure/azure-monitor/platform/delete-workspace#soft-delete-behavior

**Comment by thllxb** [comment]
The way to force a hard-delete is to add an REST API parameter "force": "true" to the delete request.

**Comment by zalyoung** [comment]
@thllxb 
> The way to force a hard-delete is to add an REST API parameter "force": "true" to the delete request.

Any more detailed description about this action?

**Comment by sebader** [comment]
@zalyoung here you go: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/delete-workspace#permanent-workspace-delete

````
DELETE https://management.azure.com/subscriptions/<subscription-id>/resourcegroups/<resource-group-name>/providers/Microsoft.OperationalInsights/workspaces/<workspace-name>?api-version=2015-11-01-preview&force=true
Authorization: Bearer eyJ0eXAiOiJKV1Qi….
````

I would also strongly vote for this to be incorporated into the TF provider. I ran `terraform destroy` on an environment before and now cannot recreate it without manually calling the API.

**Comment by aarroyoc** [comment]
This is the same as: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7282

**Comment by tombuildsstuff** [comment]
Closing in favour of #7282
