### ISSUE TITLE
Azure Storage provider doesn't use case insensitivity when comparing "account_kind" property

### ISSUE THREAD

**Issue by brandonh-msft** [terraform-providers/terraform-provider-azurerm#5466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

TF: 0.12.19
AzureRM: 1.41.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
variable "environmentName" {
  description="The environment to which this infrastructure is being deployed"
}

variable "resourceGroupBaseName" {
  description="The base name for the created Azure Resource group. This will be appended with the target environment name."
}

variable "storageAccountPrefix" {
  description="The base name for the storage account to use for the Function plan"
}

variable "location" {
  description="The Azure region in which to put all resources. This must map to an Azure Region id (e.g. 'westus', 'westus2', 'westeurope', etc)"
}

resource "azurerm_resource_group" "rg" {
  name     = "${var.resourceGroupBaseName}-${var.environmentName}"
  location = var.location
}

resource "azurerm_storage_account" "sa" {
  name                     = "${var.storageAccountPrefix}${var.environmentName}"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_kind             = "storagev2"
  account_replication_type = "LRS"
}
```

### Expected Behavior

back-to-back `tf apply` should result in 0 changes

### Actual Behavior

2nd `tf apply` says the `account_kind` doesn't match because Azure reports `StorageV2` as the kind while the `.tf` file has `storagev2` as its value. These shouldn't be case-sensitive comparisons.

### Steps to Reproduce

1. `terraform apply`
1. `terraform apply` again

**Comment by tombuildsstuff** [comment]
hi @brandonh-msft 

Thanks for opening this issue.

Over the years we've spent a great deal of time working around case sensitivity/insensitivity issues in the Azure API. Unfortunately in this instance there's downstream dependencies which require the casing matches exactly - and so whilst the Azure API may allow a case-insensitive comparison in certain circumstances this ends up causing hard-to-debug issues downstream.

What this means in practice is that all new fields are case-sensitive by default - and we'll be retroactively making existing fields case-sensitive over time too. This should both ensure that downstream API's work as expected (as we add support for them) and ultimately matches the UX of other Terraform Providers which are case-sensitive.

As such unfortunately we have no plans to make this field case-insensitive and I'm going to close this issue for the moment; but you should be able to fix this by updating the value for `account_kind` from `storagev2` to `StorageV2 ` in your Terraform Configuration.

Thanks!
