### ISSUE TITLE
tf init for azure backend doesn't prompt for everything it needs

### ISSUE THREAD

**Issue by brandonh-msft** [terraform-providers/terraform-provider-azurerm#5467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.12.19
AzureRm: 1.41.0

### Affected Resource(s)

* `tf init`

### Terraform Configuration Files

```hcl
# Configure the Azure Provider
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "~> 1"
}

terraform {
  backend "azure" {}
}
```

### Debug Output

https://gist.github.com/brandonh-msft/0aff742568641d06485db57d5aa96f49
### Panic Output

None
### Expected Behavior

TF should prompt for _everything_ it needs to init the backend.
### Actual Behavior

It's clearly missing a prompt for the Resource Group it needs - I think? I'm giving it an access key but that must not be enough.
### Steps to Reproduce

Use  the TF above and `tf init --backend=true`

### References

* #0000

**Comment by NickMetz** [comment]
Hi @brandonh-msft,

[Azure backend](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/azure/backend.go) initialization happens in terraform core, not in Terraform Azure Provider. Can you move this issue to [Terraform Core](https://github.com/hashicorp/terraform) ?

**Comment by brandonh-msft** [comment]
> Hi @brandonh-msft,
> 
> [Azure backend](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/azure/backend.go) initialization happens in terraform core, not in Terraform Azure Provider. Can you move this issue to [Terraform Core](https://github.com/hashicorp/terraform) ?

I'm not entirely sure but I think as repo owner you can issue a proper 'move' on an issue now, no? I can't see the option on my end, unfortunately.

**Comment by brandonh-msft** [comment]
moved via c/p
