### ISSUE TITLE
Front Door resource should support retrieving certificate objects from Key Vault

### ISSUE THREAD

**Issue by devblackops** [terraform-providers/terraform-provider-azurerm#5468]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Microsoft's Front Door [documentation](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-custom-domain-https#prepare-your-azure-key-vault-account-and-certificate), they state that custom certificates should be uploaded to Key Vault as **certificate objects** and not **secrets**. They don't state why this is the case, and it works when pulling them as secrets, but I think the Terraform resource should support Microsoft's recommendations.

### New or Affected Resource(s)

* azurerm_frontdoor

### Potential Terraform Configuration

Perhaps two new properties under `custom_http_configuration` can be added to pull from the certificate store rather than the secret store. These new properties would be invalid if the existing properties `azure_key_vault_certificate_name` and `azure_key_vault_certificate_version` are used.

```hcl
custom_https_configuration {
  certificate_source                   = "AzureKeyVault"
  azure_key_vault_certificate_vault_id = var.keyvault_id
  azure_key_vault_certificate_name     = var.keyvault_certificate_name
  azure_key_vault_certificate_version  = var.keyvault_certificate_version
}
```

### References

* https://docs.microsoft.com/en-us/azure/frontdoor/front-door-custom-domain-https#prepare-your-azure-key-vault-account-and-certificate

**Comment by sean-nixon** [comment]
From my understanding, raw certificate data is usually retrieved using the secrets API even when stored as a certificate in Key Vault. The current configuration maps directly to the Azure API / ARM which expects a `secretName` and `secretVersion`, so personally I don't think this should change. You can still upload the certificate as a certificate to Azure Key Vault and use the name and version of the certificate.

**References**
https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontdoors/createorupdate#customhttpsconfiguration

**Comment by slynickel** [comment]
I was able to use `azurerm_frontdoor` and have it reference a `azurerm_key_vault_certificate` resource just fine. Are you finding it doesn't work when you use variables? It may be that the ability to do reference `azurerm_key_vault_certificate`, is itself a bug, but I was able to get it to work. See #5933 for an example configuration. That configuration called out there works if you run `terraform apply` in two steps. The first step has to only create the key vault (to avoid the problem called out in that issue) then the next step creates the front door using this block for `customer_https_configuration`. I use a `count = 0/1` to control the deployment of the front door.

```hcl
    custom_https_configuration {
      certificate_source = "AzureKeyVault"
      azure_key_vault_certificate_vault_id = azurerm_key_vault.kvfd.id
      azure_key_vault_certificate_secret_name = azurerm_key_vault_certificate.example.name
      azure_key_vault_certificate_secret_version = azurerm_key_vault_certificate.example.version
    }
```

Not sure if trying to it using variables as you've done above is the issue? Perhaps if you should reference the certificate using the `azurerm_key_vault_certificate` data source definition?

**Comment by WodansSon** [comment]
@devblackops this is already currently supported by the existing [front door](https://www.terraform.io/docs/providers/azurerm/r/frontdoor.html) resource. If this isn't working for you can you make sure that you've granted the Azure Front Door Service access to your key vault?
