### ISSUE TITLE
azurerm_search_service fails to exit from creation and hangs there for more than 4 hours even after resource is created in Azure

### ISSUE THREAD

**Issue by VaijanathB** [terraform-providers/terraform-provider-azurerm#547]
### Terraform Version
Terraform v0.11.0-dev 
+ Latest Azurerm provider

### Affected Resource(s)
azurerm_search_service 
and following [example] (https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/search-create)

### Terraform Configuration Files
```hcl
Copy search-create example from azurerm terraform provider. 

```

### Debug Output
Hangs. Did not complete even after 5 hours. 
### Panic Output
None
### Expected Behavior
I notice that the search service is created in Portal. So the Terraform script should simply exit. THis does not happen and it thinks that the resource is still getting created. 

### Actual Behavior
What actually happened?
Never completes and remains in forver still creating ,,, loop. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by tombuildsstuff** [comment]
Hey @VaijanathB 

Thanks for opening this issue :)

I've been taking a look into this - and I've been able to reproduce this through Terraform. Digging into this it appears this is an issue in Go-AutoRest (which the Azure SDK for Go relies on) which doesn't handle the `provisioningState` field being in a different casing - as such [I've opened an issue on the Go-AutoRest repository about this](https://github.com/Azure/go-autorest/issues/195).

Also upon checking the Portal to try and diagnose this further I noticed this message which is visible for every Azure region - as such I've reached out to find out if this service is Deprecated, or just over capacity at this time:

<img width="287" alt="screen shot 2017-11-13 at 15 13 02" src="https://user-images.githubusercontent.com/666005/32732736-631593b2-c885-11e7-9dd1-7bd52b33e733.png">

Thanks!

**Comment by tombuildsstuff** [comment]
Hey @VaijanathB 

This issue has been resolved in Go AutoRest in this PR: https://github.com/Azure/go-autorest/pull/201 - which has now been merged into Terraform in #573. I've confirmed via our acceptance tests that this issue appears to be resolved - and this bug-fix will ship in the next version of Terraform. As such - I'm going to close this issue for the moment; but please feel free to re-open it if this doesn't fix it for you.

Thanks!

**Comment by VaijanathB** [comment]
@tombuildsstuff , 

I am still seeing this issue in the latest main branch build. Here is my build version. 
Terraform v0.11.1-dev (fc2913d6109ca7ca7fd94fda0493391efc259803)
+ provider.azurerm v0.3.3

I also tried to create this in Portal and was able to create it in West US region. I am reopening this as of now. Please do let me know if you need more information. 

Thanks,
VJ

**Comment by tombuildsstuff** [comment]
@VaijanathB looking at the output above you're using the latest released Provider and a build of the Provider from `master` - and as such the fix isn't present. We've merged the fix into master but we're still waiting to fix a few bugs before releasing the next version (unfortunately we've had Thanksgiving and a few other priorities in-between).

Would you be able to take another look using a build of the Provider from `master`? I've just re-confirmed this works using the code in `master` - as such I'm going to close this issue in the interim.

Thanks!

**Comment by VaijanathB** [comment]
Works with the latest build. 

Thanks,
VJ

**Comment by GreatSnoopy** [comment]
Is this issue fixed in the stable release? I think I have just been hit by the same problem: terraform plan hangs indefinitely. It happens only in certain subscriptions.
Tested on Terraform v0.11.1
with plugins:
- Downloading plugin for provider "azurerm" (1.0.0)...
- Downloading plugin for provider "consul" (1.0.0)...
- Downloading plugin for provider "external" (1.0.0)...
- Downloading plugin for provider "template" (1.0.0)...
Where could I get another provider build so that at least I can confirm that it is the same issue ?
