### ISSUE TITLE
azurerm_container_group

### ISSUE THREAD

**Issue by waynejnicklin** [terraform-providers/terraform-provider-azurerm#5472]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

v0.12.19

azurerm_container_group

I am trying to use the new "commands" property to pass multiple commands.
It works for a single command, for example:

commands = ["ls"]

But when I try and run two commands, it just joins them together, it doesn't execute them separately, for example:

commands = ["ls", "ls -l"]

This tries to execute a single command "ls ls -l" and obviously fails saying the folder "ls -l" doesn't exist.

Thanks,
Wayne

**Comment by jackofallops** [comment]
Hi @waynejnicklin 
This property mirrors the Docker CMD (exec form) functionality here https://docs.docker.com/engine/reference/builder/#cmd
and is expected behaviour.

- Ste
