### ISSUE TITLE
Azurerm provider is failing with "Unsupported block type" for azurerm_storage_account

### ISSUE THREAD

**Issue by carlessanagustin** [terraform-providers/terraform-provider-azurerm#5478]
### Terraform (and AzureRM Provider) Version

```shell
$ terraform --version
Terraform v0.12.19
+ provider.azurerm v1.38.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "resource" {
...
  blob_properties {
    delete_retention_policy {
      days                            = 7
    }
  }
...
}
```

### Debug Output

https://gist.github.com/carlessanagustin/fd531c9320d01bdfc614bcaf5aa711dc

### Expected Behavior

Continue with `terraform apply`

### Actual Behavior

```
Error: Unsupported block type

  on .terraform/modules/strg/main.tf line 18, in resource "azurerm_storage_account" "resource":
  18:   blob_properties {

Blocks of type "blob_properties" are not expected here.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @carlessanagustin 

Thanks for opening this issue.

Taking a look into this [support for the `blob_properties` block was added in v1.40.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1400-january-08-2020) - however v1.41.0 is the latest (at the time of writing) which you can upgrade to this by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=1.41.0"
}
```

Thanks!
