### ISSUE TITLE
Terraform plan always forces AKS cluster to be recreated

### ISSUE THREAD

**Issue by nidhi5885** [terraform-providers/terraform-provider-azurerm#5479]
Community Note

Please vote on this issue by adding a +1 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
Terraform (and AzureRM Provider) Version

```
Terraform v0.12.18
+ provider.azurerm v1.39.0
+ provider.helm v0.10.4
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
```

Affected Resource(s)

azurerm_kubernetes_cluster

Terraform Configration Files

```
resource "azurerm_kubernetes_cluster" "main" {
   depends_on = [
    "azurerm_public_ip.ingress_ip"
    # ,   "data.local_file.version"
  ]

  name                = "${var.PROJECT}${var.ENVIRONMENT}-aks"
  location            = "${var.location}"
  resource_group_name = "${var.rgname}"
  dns_prefix          = "${var.PROJECT}${var.ENVIRONMENT}dnsprefix"
  kubernetes_version  = "${var.K8S_VER}"


  linux_profile {
    admin_username = "${var.ADMIN_USER}"

    ssh_key {
      key_data = "${var.AKS_SSH_ADMIN_KEY}"
    }
  }

    default_node_pool {
    name                = "default"
    type                  = "VirtualMachineScaleSets"
    vm_size            = var.NODE_SIZE
    enable_auto_scaling = true
    min_count            = 2
    max_count           = 3
    vnet_subnet_id    = var.vnet_subnet_id
  }

  network_profile {
    network_plugin = "azure"
    service_cidr = "${var.SERVICE_CIDR}"
    dns_service_ip = "${var.DNS_IP}"
    docker_bridge_cidr = "${var.DOCKER_CIDR}"
  }

  role_based_access_control {
    enabled = true
  }

  service_principal {
    client_id     = var.service_principal_client_id
    client_secret = var.service_principal_client_secret
  }

 
  addon_profile {
        oms_agent {
        enabled                    = true
        log_analytics_workspace_id = var.log_analytics_id
 
     }
    }
}


```
"vnet_subnet_id" and "log_analytics_id"  is an output from network module, and root module is passing this id to compute module.

Expected Behavior

No changes to the aks cluster

Actual Behavior

Terraform will perform the following actions:

module.compute.azurerm_kubernetes_cluster.main must be replaced
-/+ resource "azurerm_kubernetes_cluster" "main" {}

Steps to Reproduce

Create two modules AKS and Network, call them from room module by passing VNET Subnet ID from network to AKS module definition.
terraform apply
Without doing any changes to the cluster, run terraform plan

**Comment by tombuildsstuff** [comment]
hi @nidhi5885 

Thanks for opening this issue.

Since this question is being discussed in #5460 I'm going to close this issue in favour of that one - so that we can consolidate our replies in a single Github issue.

Thanks!
