### ISSUE TITLE
Feature Request: CosmosDB Collections

### ISSUE THREAD

**Issue by deepaksap** [terraform-providers/terraform-provider-azurerm#548]
Hi there,

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
Cosmos DB

### Expected Behavior
What should have happened? --> terraform should be able to create mongo db collections under cosmos DB. 

### Actual Behavior
What actually happened? --> Terraform is only creating cosmos DB account.

**Comment by tombuildsstuff** [comment]
Hi @deepaksap 

Thanks for opening this issue / feature request :)

I've taken a look into this but unfortunately at this point in time there's no support for creating CosmosDB Collections in the Azure SDK for Go. That said - [a PR's been opened recently which should enable this](https://github.com/Azure/azure-sdk-for-go/pull/844) and once the PR's been merged we should be able to take a look at supporting this in Terraform.

Thanks!

**Comment by rossedman** [comment]
@tombuildsstuff looks like this was merged. I would love to see this happen. I know for a long time this was separate from the ARM API.

**Comment by Preskton** [comment]
Bump - would be great to simplify collection management through this interface.

**Comment by pussinboots** [comment]
I looked into this [a PR's been opened recently which should enable this](https://github.com/Azure/azure-sdk-for-go/pull/844) and this implements that you can
use the [mgo mongo driver](http://labix.org/mgo) to create just a mongo collection. 

The Azure SDK for go miss the possibility to create a CosmosDB collection with the following properties (that properties come from the azure cli tool)
* default-ttl
* indexing-policy 
* partition-key-path
* throughput

The azure cli tool offers the possibility to create a cosmosDB collection
```bash
az cosmosdb collection create 
```

Any suggestions how to create CosmosDb collection with terraform?
* use the azure cli tool and a bash script maybe

**Comment by idevchris** [comment]
Looks like the PR got merged meanwhile

**Comment by agnnn** [comment]
Any updates on this feature ??

**Comment by holmesb** [comment]
Would be great to have CosmosDB collections managed by Terraform.  The SDK support has been there for four months now, any ETA for this?

**Comment by tombuildsstuff** [comment]
@holmesb we're hoping to get to this soon - watch this space :)

**Comment by ChristianWeyer** [comment]
Do we have any possible ETA for this? ;-) It would be a great feature.
Thanks!

**Comment by reddyed** [comment]
any update on this feature?

**Comment by holmesb** [comment]
I see there's been some work on Cosmos at the [account level](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1961).  Having fully-featured accounts without any database\collection capability is incongruous IMO.  Any timeline for this?

**Comment by mikhailshilkov** [comment]
So, Mongo Collections got added, but not the "normal" Cosmos DB collections? Is there an issue which tracks those? (based on the title of this issue, I assumed they were included, but it got closed now)

**Comment by dandiellie** [comment]
Is "azurerm_cosmos_sql_container" the new resource for SQL Collections?

**Comment by mikhailshilkov** [comment]
> Is "azurerm_cosmos_sql_container" the new resource for SQL Collections?

It could be but I don't see it anywhere. Where have you found it?

**Comment by jlagarda** [comment]
@dandiellie where you able to get an answer? 

Also for anyone writing collections via terraform, is there
any modules like "azurerm_cosmosdb_mongo_collection" where I can configure RU's, ttl etc

Thank you in advance
