### ISSUE TITLE
"availability_set_id": conflicts with zones

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#5482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

`azurerm_virtual_machine`

### Terraform Configuration Files

```
  availability_set_id   = local.deploy_using_zones || var.number_of_vms_in_avset == 0 ? "" : element(concat(azurerm_availability_set.av_set.*.id, list("")), 0)
  zones                 = local.deploy_using_zones ? [(each.value.index % var.number_of_zones) + 1] : []
```
or 

```
  availability_set_id   = "" 
  zones                 = local.deploy_using_zones ? [(each.value.index % var.number_of_zones) + 1] : []
```
### Expected Behavior

Allow both zones and availability_set_id to coexist.  availability_set_id will already take a empty string which creates the VM with no AVSET.   Zones are not in every region so its important that we have flexibility (without having to VM resources) to deploy a VM in a AVSET or Zones.

### Actual Behavior

"availability_set_id": conflicts with zones

### Steps to Reproduce

Create a VM resource with availability_set_id = "" and zones = [1]

**Comment by tombuildsstuff** [comment]
hey @rohrerb 

Thanks for opening this issue :)

It should be possible to achieve this today by specifyig `null` rather than an empty string - would you be able to take a look and see if that works for you? From our side I'm currently working on the replacement Virtual Machine resources (defined in #2807) for 2.0 - so we'll take a look at this for that release either way 👍 

Thanks!

**Comment by rohrerb** [comment]
Magic!  Thank you @tombuildsstuff  that worked. :D
