### ISSUE TITLE
aks forces to delete even there is no change 

### ISSUE THREAD

**Issue by VipinAgarwal** [terraform-providers/terraform-provider-azurerm#5488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version 0.12.17, AzureRm 1.41.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jackofallops** [comment]
Hi @VipinAgarwal 
Can you provide some context and some output from a plan that shows this behaviour?

Thanks
- Ste

**Comment by tombuildsstuff** [comment]
hi @VipinAgarwal 

Since we've not heard back from you here I'm going to close this issue for the moment - but if you're able to provide the information requested above we'll circle around and take another look 👍 

Thanks!
