### ISSUE TITLE
Unable to create Azure NetApp File nfsv4.1 volumes

### ISSUE THREAD

**Issue by a0099953** [terraform-providers/terraform-provider-azurerm#5495]
Using the current provider for Azure NetApp, I am only able to create NFSv3 volumes. Appears to be missing the policy_type setting.

**Comment by katbyte** [comment]
This should be fixed by #5485

**Comment by paulomarquesc** [comment]
@a0099953, the PR #5485 carrying the fix was merged yesterday.

**Comment by katbyte** [comment]
Closed by #5485
