### ISSUE TITLE
azurerm_advanced_threat_protection support for Azure Database for PostgreSQL

### ISSUE THREAD

**Issue by cdunford** [terraform-providers/terraform-provider-azurerm#5515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

The recently added azurerm_advanced_threat_protection resource enables ATP on arbitrary resources. [ATP for Postgres](https://docs.microsoft.com/en-us/azure/postgresql/concepts-data-access-and-security-threat-protection) is currently in public preview, and does not appear to be supported by the azurerm_advanced_threat_protection resource; attempting to use it results in:

```
security.AdvancedThreatProtectionClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Not Supported" Message="Atp settings are not supported on resources of type servers"
```

It would be great if this is supported when the feature comes out of public preview.

### New or Affected Resource(s)

* azurerm_advanced_threat_protection
* azurerm_postgresql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_advanced_threat_protection" "atp" {
  enabled                  = true
  target_resource_id = "${azurerm_postgresql_server.server.id}"
}
```

### References

* #4614

**Comment by katbyte** [comment]
Hi @cdunford,

You should already be able to do this with the [azurerm_advanced_threat_protection](https://www.terraform.io/docs/providers/azurerm/r/advanced_threat_protection.html) resource. Please do let us know if it fails to work by opening a new issue about any incompatibilities with postgres.

**Comment by cdunford** [comment]
@katbyte yes I tried that and the error is in my issue description. It fails with a 400. I assumed it wasn't supported yet. Did you want me to open something different?
