### ISSUE TITLE
Unauthorized - Required Header authorization is missing

### ISSUE THREAD

**Issue by jjlauterbach** [terraform-providers/terraform-provider-azurerm#5519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v1.37.0
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_1.37.0`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=1.37.0"
}

resource "random_string" "group" {
  length = 6
  special = false
  upper = false
}

resource "azurerm_cosmosdb_account" "acct" {
  name                = "${random_string.group.result}-cosmos-db"
  location            = var.location
  resource_group_name = var.resource_group_name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = false
  enable_multiple_write_locations = false
  is_virtual_network_filter_enabled = false

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  geo_location {
    location          = var.location
    failover_priority = 0
  }
}

resource "azurerm_cosmosdb_sql_database" "db" {
  name                = "${random_string.group.result}-cosmos/sql/${var.cosmosDatabaseName}"
  resource_group_name = var.resource_group_name
  account_name        = "${random_string.group.result}-cosmos-db"

  depends_on = [azurerm_cosmosdb_account.acct]
}
```

### Actual Behavior

`terraform apply` returns an error when attempting to create a azurerm_cosmosdb_sql_database resource.

```
azurerm_cosmosdb_sql_database.db: Creating...

Error: Error issuing create/update request for Cosmos SQL Database 2zb4b0-cosmos/sql/databaseName (Account 2zb4b0-cosmos-db): documentdb.DatabaseAccountsClient#CreateUpdateSQLDatabase: Failure sending request: StatusCode=401 -- Original Error: Code="Unauthorized" Message="Required Header authorization is missing. Ensure a valid Authorization token is passed.\r\nActivityId: 3622141d-6e7e-40d9-b387-7de5bedfa135, Microsoft.Azure.Documents.Common/2.9.2"

  on cosmos.tf line 36, in resource "azurerm_cosmosdb_sql_database" "db":
  36: resource "azurerm_cosmosdb_sql_database" "db" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jackofallops** [comment]
Hi @jjlauterbach 

The header referenced is the auth for the client (terraform's SP or your login, depending on how you're running it) to request the DB creation.  This is supplied in every request sent to the API, suggesting that there may be a permissions issue with your auth for that account?   Can you check the permissions for the user/SP you're running terraform as? (Particularly on the `cosmosdb_account`)

NB: You can directly create a dependence for the DB by using:
`account_name        = "${azurerm_cosmosdb_account.acct.name}"`
instead of using the `depends_on` config, which is intended for cases where no direct dependency can be set.

-Ste

**Comment by jjlauterbach** [comment]
Thanks - Looks like you are correct and there's a permissions issue as I'm getting the same error through `az cosmosdb sql databaes create`
