### ISSUE TITLE
Azurerm provider fails to create Azure Storage Container resource

### ISSUE THREAD

**Issue by MarkKharitonov** [terraform-providers/terraform-provider-azurerm#5521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.20
+ provider.azurerm v1.41.0
+ provider.null v2.1.2
```
### Affected Resource(s)

* `azurerm_storage_container`

### Terraform Configuration Files

**modules\remote-state\main.tf**
```hcl
provider "azurerm" {
}

variable "env" {
  type        = string
  description = "The SDLC environment (qa, dev, prod, etc...)"
}

locals {
  extended_name = "dfpg-${lower(var.env)}-tfstate"
}

resource "azurerm_resource_group" "setup" {
  name     = "app505-${local.extended_name}-eastus2"
  location = "eastus2"
}

resource "azurerm_storage_account" "sa" {
  name                     = replace(local.extended_name, "-", "")
  resource_group_name      = azurerm_resource_group.setup.name
  location                 = azurerm_resource_group.setup.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "ct" {
  name                 = "terraform-state"
  storage_account_name = azurerm_storage_account.sa.name
}

data "azurerm_storage_account_sas" "state" {
  connection_string = azurerm_storage_account.sa.primary_connection_string
  https_only        = true

  resource_types {
    service   = true
    container = true
    object    = true
  }

  services {
    blob  = true
    queue = false
    table = false
    file  = false
  }

  start  = timestamp()
  expiry = timeadd(timestamp(), "17520h")

  permissions {
    read    = true
    write   = true
    delete  = true
    list    = true
    add     = true
    create  = true
    update  = false
    process = false
  }
}

resource "null_resource" "post-config" {

  depends_on = [azurerm_storage_container.ct]

  provisioner "local-exec" {
    command = <<EOT
Set-Content -Value 'storage_account_name = "${azurerm_storage_account.sa.name}"' -Path "backend-config.txt"
Add-Content -Value 'container_name = "terraform-state"' -Path "backend-config.txt"
Add-Content -Value 'key = "terraform.tfstate"' -Path "backend-config.txt"
Add-Content -Value 'sas_token = "${data.azurerm_storage_account_sas.state.sas}"' -Path "backend-config.txt"
EOT

    interpreter = ["PowerShell", "-NoProfile", "-Command"]
  }
}
```

**qa\bootstrap\rs\main.tf**
```hcl
module "bootstrap" {
    source = "../../../modules/remote-state"
    env = "qa"
}
```

### Debug Output

https://gist.github.com/MarkKharitonov/b95b87ef6a54b13eb6d42fdc9bff8e6c

### Expected Behavior

The container resource is created on the first run.

### Actual Behavior

The first apply failed, the next apply failed too. Finally the third apply was successful.

1. tf.log - the first apply
2. tf2.log - the second apply
3. tf3.log - the final successful apply

### Steps to Reproduce

Repeat several times. I have consistent failures on the first apply, but the second usually passes. Sometimes it passes right away, but usually fails.

1. `terraform apply -auto-approve`

I used several apply-destroy loops, In most cases the first apply fails.

### References

https://stackoverflow.com/questions/59904978/attempting-to-create-a-storage-container-for-azurerm-backend-fails-with-404-th

* #0000

**Comment by manishingole-coder** [comment]
I am also experiencing the same issue while creation of storage container however I am getting below error

Error: Error checking for existence of existing Container "walfiles" (Account "storagename" / Resource Group "rgname"): containers.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.\nRequestId:d0b6a7c2-b01e-00f6-0516-13e510000000\nTime:2020-04-15T11:11:58.4707719Z"

If I create manually on an azure portal I can do it so.

**Comment by boillodmanuel** [comment]
@manishingole-coder , it seems more related to #2977, doesn't it?

**Comment by tombuildsstuff** [comment]
hi @MarkKharitonov 

Thanks for opening this issue - apologies for the delayed response here.

Taking a look through this appears to be a configuration issue, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
