### ISSUE TITLE
azurerm_dns_zone => Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by senare** [terraform-providers/terraform-provider-azurerm#5529]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_dns_zone`

### Terraform Configuration Files

before (excerpt)
```hcl
resource "azurerm_resource_group" "infra_resource_group" {
  for_each = var.location

  name     = "${var.environment}-${each.value}-rg"
  location = each.value

  tags = {
    environment = var.environment
  }
}

resource "azurerm_dns_zone" "dns" {
  for_each = var.location

  name                = var.domain
  resource_group_name = "${var.environment}-${each.value}-rg"

  tags = {
    environment = var.environment
  }
}
```
after (excerpt)
```hcl
resource "azurerm_resource_group" "infra_resource_group" {
  for_each = var.location

  name     = "${var.environment}-${each.value}-rg"
  location = each.value

  tags = {
    environment = var.environment
  }
}

resource "azurerm_dns_zone" "dns" {
  for_each = var.location

  name                = var.domain
  resource_group_name = "${var.environment}-${each.value}-rg"

  tags = {
    environment = var.environment
  }
}

resource "azurerm_dns_ns_record" "subdomain_ns_records" {
  for_each = toset([for location in var.location : "${var.environment}-${location}-rg"])

  name                = "${var.environment}.${var.domain}"
  zone_name           = var.domain
  resource_group_name = each.value
  ttl                 = 300

  records = flatten([for l in var.location : azurerm_dns_zone.dns[l].name_servers])

  tags = {
    Environment = var.environment
  }
}
```

### Panic Output

Error: Provider produced inconsistent result after apply

When applying changes to module.infra.azurerm_dns_zone.dns["northeurope"],
provider "registry.terraform.io/-/azurerm" produced an unexpected new value
for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

I am actually new to Azure/Terraform so I found no relevant logs I think, if more is needed please provide instructions how to generate said information and I will do my best !

### Expected Behavior

I was trying to setup redundant DNS zones, so i expected the NS records to be mirrored in both zones.

I have no really idea how this should work be setup but this seams reasonable to me atleast, please feel free to correct me if I am in the wrong.

### Actual Behavior

Error: Provider produced inconsistent result after apply

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Terraform plan 

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # module.infra.azurerm_dns_ns_record.subdomain_ns_records["infra-northeurope-rg"] will be created
  + resource "azurerm_dns_ns_record" "subdomain_ns_records" {
      + fqdn                = (known after apply)
      + id                  = (known after apply)
      + name                = "infra.wcorn.net"
      + records             = (known after apply)
      + resource_group_name = "infra-northeurope-rg"
      + tags                = {
          + "Environment" = "infra"
        }
      + ttl                 = 300
      + zone_name           = "wcorn.net"

      + record {
          + nsdname = (known after apply)
        }
    }

  # module.infra.azurerm_dns_ns_record.subdomain_ns_records["infra-westeurope-rg"] will be created
  + resource "azurerm_dns_ns_record" "subdomain_ns_records" {
      + fqdn                = (known after apply)
      + id                  = (known after apply)
      + name                = "infra.wcorn.net"
      + records             = (known after apply)
      + resource_group_name = "infra-westeurope-rg"
      + tags                = {
          + "Environment" = "infra"
        }
      + ttl                 = 300
      + zone_name           = "wcorn.net"

      + record {
          + nsdname = (known after apply)
        }
    }

  # module.infra.azurerm_dns_zone.dns["northeurope"] will be created
  + resource "azurerm_dns_zone" "dns" {
      + id                        = (known after apply)
      + max_number_of_record_sets = (known after apply)
      + name                      = "wcorn.net"
      + name_servers              = (known after apply)
      + number_of_record_sets     = (known after apply)
      + resource_group_name       = "infra-northeurope-rg"
      + tags                      = {
          + "environment" = "infra"
        }
      + zone_type                 = "Public"
    }

  # module.infra.azurerm_dns_zone.dns["westeurope"] will be created
  + resource "azurerm_dns_zone" "dns" {
      + id                        = (known after apply)
      + max_number_of_record_sets = (known after apply)
      + name                      = "wcorn.net"
      + name_servers              = (known after apply)
      + number_of_record_sets     = (known after apply)
      + resource_group_name       = "infra-westeurope-rg"
      + tags                      = {
          + "environment" = "infra"
        }
      + zone_type                 = "Public"
    }

  # module.infra.azurerm_dns_zone.wcorn["northeurope"] will be destroyed
  - resource "azurerm_dns_zone" "wcorn" {
      - id                               = "/subscriptions/9c2d324b-47c7-4f19-ae87-16f0e8196b09/resourceGroups/infra-northeurope-rg/providers/Microsoft.Network/dnszones/wcorn.net" -> null
      - max_number_of_record_sets        = 10000 -> null
      - name                             = "wcorn.net" -> null
      - name_servers                     = [
          - "ns1-08.azure-dns.com.",
          - "ns2-08.azure-dns.net.",
          - "ns3-08.azure-dns.org.",
          - "ns4-08.azure-dns.info.",
        ] -> null
      - number_of_record_sets            = 3 -> null
      - registration_virtual_network_ids = [] -> null
      - resolution_virtual_network_ids   = [] -> null
      - resource_group_name              = "infra-northeurope-rg" -> null
      - tags                             = {
          - "environment" = "infra"
        } -> null
      - zone_type                        = "Public" -> null
    }

  # module.infra.azurerm_dns_zone.wcorn["westeurope"] will be destroyed
  - resource "azurerm_dns_zone" "wcorn" {
      - id                               = "/subscriptions/9c2d324b-47c7-4f19-ae87-16f0e8196b09/resourceGroups/infra-westeurope-rg/providers/Microsoft.Network/dnszones/wcorn.net" -> null
      - max_number_of_record_sets        = 10000 -> null
      - name                             = "wcorn.net" -> null
      - name_servers                     = [
          - "ns1-07.azure-dns.com.",
          - "ns2-07.azure-dns.net.",
          - "ns3-07.azure-dns.org.",
          - "ns4-07.azure-dns.info.",
        ] -> null
      - number_of_record_sets            = 3 -> null
      - registration_virtual_network_ids = [] -> null
      - resolution_virtual_network_ids   = [] -> null
      - resource_group_name              = "infra-westeurope-rg" -> null
      - tags                             = {
          - "environment" = "infra"
        } -> null
      - zone_type                        = "Public" -> null
    }

Plan: 4 to add, 0 to change, 2 to destroy.

Warning: "enable_advanced_threat_protection": [DEPRECATED] This property has been deprecated in favour of the new 'azurerm_advanced_threat_protection' resource and will be removed in version 2.0 of the provider

  on infra/terraform/terraform.tf line 2, in resource "azurerm_storage_account" "infra_storage":
   2: resource "azurerm_storage_account" "infra_storage" {

------------------------------------------------------------------------

### References

* #0000

**Comment by jackofallops** [comment]
Hi @senare 
The `toset` output is unordered, can you try your `for_each` with `tolist` instead?

-Ste

**Comment by senare** [comment]
> Hi @senare
> The `toset` output is unordered, can you try your `for_each` with `tolist` instead?
> 
> -Ste

Yes, I will try 

I however managed to find a workaround, if once declare all as a module it is possible to depend on the module output and then terraform will manage to sort out the implicit dependencies and it seams to work ... at least for me for now.

**Comment by neil-yechenwei** [comment]
@senare, thanks for opening this issue. I assume the issue has gone since I cannot repro it anymore after tested with below tfconfig and latest azurerm. Maybe I missed something. Could you have a try below tfconfig which is similar with yours to check whether the issue still exists? Thanks.

tfconfig:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  for_each = var.location

  name     = "${var.environment}-${each.value}-rg"
  location = each.value
  
  tags = {
    environment = var.environment
  }
}

resource "azurerm_dns_zone" "test" {
  for_each = var.location

  name                = var.domain
  resource_group_name = "${var.environment}-${each.value}-rg"
  
  tags = {
    environment = var.environment
  }
  
  depends_on = [azurerm_resource_group.test]
}

resource "azurerm_dns_ns_record" "test" {
  for_each = toset([for location in var.location : "${var.environment}-${location}-rg"])

  name                = "${var.environment}.${var.domain}"
  zone_name           = var.domain
  resource_group_name = each.value
  ttl                 = 300

  records = flatten([for l in var.location : azurerm_dns_zone.test[l].name_servers])

  tags = {
    Environment = var.environment
  }
}
```

variables.tf:
```
variable "location" {
  description = "location"
  default = {
     "eastus2" = "eastus2"
	 "westus"  = "westus"
  }
}

variable "environment" {
  description = "environment"
  default = "acctest"
}

variable "domain" {
  description = "domain"
  default = "testdomaintest10.com"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment - but please let us know if you're able to take a look at the comment above and confirm if this is still an issue and we'll take another look.

Thanks!
