### ISSUE TITLE
Support for Tags on Netapp Resources

### ISSUE THREAD

**Issue by philbal611** [terraform-providers/terraform-provider-azurerm#5532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Severak Netapp resources have support for tags in Azure, and would need support to be able to manage via TF provider.

### New or Affected Resource(s)

* `azurerm_netapp_account`
* `azurerm_netapp_pool`
* `azurerm_netapp_volume`

### Potential Terraform Configuration

```hcl
resource "azurerm_netapp_account" "example" {
  name                = "example-netapp"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"

  tags = {
    // tags
  }
}

resource "azurerm_netapp_pool" "example" {
  name                = "example-netapppool"
  account_name        = azurerm_netapp_account.example.name
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  service_level       = "Premium"
  size_in_tb          = 4

  tags = {
    // tags
  }
}

resource "azurerm_netapp_volume" "example" {
  name                = "example-netappvolume"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  account_name        = "${azurerm_netapp_account.example.name}"
  pool_name           = "${azurerm_netapp_pool.example.name}"
  volume_path         = "my-unique-file-path"
  service_level       = "Premium"
  subnet_id           = "${azurerm_subnet.example.id}"
  storage_quota_in_gb = 100

  tags = {
    // tags
  }
}
```

### References

AZ cli create commands regarding creating resources with tags option:

* https://docs.microsoft.com/en-us/cli/azure/netappfiles/account?view=azure-cli-latest#az-netappfiles-account-create
* https://docs.microsoft.com/en-us/cli/azure/netappfiles/pool?view=azure-cli-latest#az-netappfiles-pool-create
* https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume?view=azure-cli-latest#az-netappfiles-volume-create

**Comment by lsongcoles** [comment]
Any update for this issue?

**Comment by aqche** [comment]
I can take a look into getting a PR open for this.
