### ISSUE TITLE
azurerm_monitor_diagnostic_setting attempts to use a private preview feature on storage accounts

### ISSUE THREAD

**Issue by ToxicGLaDOS** [terraform-providers/terraform-provider-azurerm#5552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
provider.azurerm: version = "~> 1.42"

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`
* `azurerm_storage_account`

### Terraform Configuration Files

```
resource "azurerm_monitor_diagnostic_setting" "diagnostics" {
  name               = "VUE Diagnostics"
  target_resource_id = azurerm_storage_account.storage.id
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.log_analytics.id

  log {
    category = "Read"
    enabled  = true

    retention_policy {
      enabled = true
      days    = 365
    }
  }
}
```

### Debug Output

```Error: Error creating Monitor Diagnostics Setting "VUE Diagnostics" for Resource "/subscriptions/a2846387-879b-40ec-bce8-ee7a984a41e2/resourceGroups/sbuc-csnet-rg/providers/Microsoft.Storage/storageAccounts/sbucdiag99f8ce69b199384e": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Subscription 'a2846387-879b-40ec-bce8-ee7a984a41e2' is not whitelisted in the private preview of diagnostic log settings for Azure resource type 'microsoft.storage/storageaccounts', feature flag: 'microsoft.insights/diagnosticsettingpreview'."```

### Expected Behavior

The Diagnostic settings get created like they do when I go in the portal and select the settings manually.

### Actual Behavior

It errors out saying that my subscription isn't whitelisted

### Steps to Reproduce

1. Create a storage account and diagnostics settings in terraform
2. `terraform apply`

### Important Factoids

I'm using terragrunt.
azurerm_monitor_diagnostic_setting worked fine for APIM which doesn't have "(Classic)" in the name in the portal, which leads me to believe terraform is using the wrong API call (Calling the preview feature instead of classic) for storage accounts.

### References

* #3346 Had a very similar question that seemed to be resolved, but it doesn't seem to be working for me.

**Comment by lrxtom2** [comment]
@ToxicGLaDOS Hi, Thanks for opening the issue. If you could still repro the issue, please have a try to run the command below to register feature into your subscription. Thanks for that.
```
az feature register --namespace microsoft.insights --name diagnosticsettingpreview
az provider register --namespace 'microsoft.insights'
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to confirm if this is still an issue then we should be able to reopen this and take another look.

Thanks!
