### ISSUE TITLE
Terraform crashes if "system assigned identity" is enabled in App Service/Azure Function

### ISSUE THREAD

**Issue by iljoong** [terraform-providers/terraform-provider-azurerm#5557]
I'm trying to run terraform inside __Azure Function Powershell__ since Azure Function support to run any exe file.

Since Terraform does not support MSI for App Service/Azure Function, I enabled (for a workaround) __system assigned identity__ to access SP secret in Key Vault using KV reference like this [document](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references) and authenticate using [SP](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html)

If I run terraform.exe it crashes and produced following error:

```
Error: rpc error: code = Unavailable desc = transport is closing 
```

Running Environment:
- Azure Function: Version 3.0 / PowerShell / Consumption Plan
- Terraform exe: 0.12.20 (latest)

**Comment by deepakloke** [comment]
# Azure Function app
resource "azurerm_function_app" "funcapp" {  
  name                      = "test-azure-functions"
  location                  = azurerm_resource_group.example.location
  resource_group_name       = azurerm_resource_group.example.name
  app_service_plan_id       = azurerm_app_service_plan.example.id
  storage_connection_string = azurerm_storage_account.example.primary_connection_string
 
  identity {
    type = "SystemAssigned"
      }
  app_settings = {
     "APPINSIGHTS_INSTRUMENTATIONKEY" =  appinsight.instrumentation_key
     }
  }

Note :  setting the identity property above the app_setting worked for me else it was failing for me as well. Hope this helps

**Comment by tombuildsstuff** [comment]
hi @iljoong 

Thanks for opening this issue / apologies for the delayed response here!

Taking a look through as you've mentioned this is unsupported - as such I'm going to close this in favour of #5558 which is tracking adding support for this.

Thanks!
