### ISSUE TITLE
Feature request: azurerm_sql_server support for Active Directory

### ISSUE THREAD

**Issue by mparaz** [terraform-providers/terraform-provider-azurerm#557]
I would like `azurerm_sql_server` to support the `az sql server ad-admin update` command described at:

https://docs.microsoft.com/en-us/cli/azure/sql/server/ad-admin?view=azure-cli-latest

To set the Active Directory Admin for a SQL server upon creation.

**Comment by tombuildsstuff** [comment]
hey @mparaz

Thanks for opening this issue :)

Just to let you know that support for this shipped [in v1.3.0 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.3.0/CHANGELOG.md) as [the `azurerm_sql_active_directory_administrator` Resource](https://www.terraform.io/docs/providers/azurerm/r/sql_active_directory_administrator.html).

Thanks!
