### ISSUE TITLE
Support for AKS outboundType

### ISSUE THREAD

**Issue by jluk** [terraform-providers/terraform-provider-azurerm#5583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS is enabling a feature to skip setup of standard load balancers (public IP, backend pools) in favor of the user setup with a custom UDR. The AKS feature is here and releasing early Feb:

https://github.com/Azure/AKS/issues/1384

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/resource_arm_kubernetes_cluster.go#L346-L468

**Comment by jluk** [comment]
FYI @grayzu / @tombuildsstuff 

We're releasing this capability within the next week and half in preview, with GA around the corner. Our public docs will be up next week for deeper detail and I'll share here, but this is an early heads up.

**Comment by baboune** [comment]
This capability is now available.  See https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate#outboundtype.

We also need this.

**Comment by jluk** [comment]
@tombuildsstuff our public doc explaining this should be out by end of week. we can chat a bit more on this feature to clarify if needed.

**Comment by baboune** [comment]
OK I made some changes to the provider to fix this issue.  Since this requires a change of the go module dependencies, before I make a PR, how to handle all  the vendor changes triggered by the new github.com/Azure/azure-sdk-for-go v39.1.0+incompatible packge?

**Comment by tombuildsstuff** [comment]
@baboune thanks for the PR - for the moment I'd suggest holding off vendoring the updated SDK - we'll look to upgrade to version 39.1 of the Azure SDK once we've finished removing the older resources (which we're working through at the moment, since removing these resources also removes the associated packages from the vendor directory) - I'll comment in #5757 once that's done 👍

**Comment by baboune** [comment]
We need this urgently.   Could the associated PR be moved forward?

**Comment by baboune** [comment]
I already begged for this 17 days ago, any ETAs when this could be merged? Anything I could to to move this forward?

**Comment by wagnst** [comment]
FYI the official documentation for the outbound type is [here](https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype). Merging this, will help to avoid public IPs on the Load Balancer and make it compliant in many enterprise environments (where they do not like to see PIPs - for whatever reason). I really like to see progress here as well.

**Comment by evillgenius75** [comment]
> @baboune thanks for the PR - for the moment I'd suggest holding off vendoring the updated SDK - we'll look to upgrade to version 39.1 of the Azure SDK once we've finished removing the older resources (which we're working through at the moment, since removing these resources also removes the associated packages from the vendor directory) - I'll comment in #5757 once that's done 👍

@tombuildsstuff where are we with the upgrade of the Azure SDK to 39.1? This is a serious blocker for many and nowwe are having to resort to CLI builds for Enterprise clusters!
