### ISSUE TITLE
Can we data refer to Eventhub instances from Eventhub namespaces 

### ISSUE THREAD

**Issue by adeshreddy** [terraform-providers/terraform-provider-azurerm#5599]
Can we data refer to Eventhub instances through Eventhub namespaces in Terraform?
Right now I am data referring to Eventhub namespace but I am unable to get the instances in the output! 
I want to data refer the Eventhub's under the Eventhub namespace's and use them for creating IoT hub routes

Right now there is data refer block for [eventhub namespaces] with attribute refrences(https://www.terraform.io/docs/providers/azurerm/d/eventhub_namespace.html)
```
data "azurerm_eventhub_namespace" "eventhub_namespace" {
  name  ="example"
  resource_group_name = "example resource group"
}
```

But there is nothing for referring to eventhub's in eventhub namespaces .
is there something like 

```
data "azurerm_eventhub" "eventhub" {
  name_eventhub_namespace  ="example"
  eventhub_name = "example eventhub"
}
```

**Comment by tombuildsstuff** [comment]
Closing in favour of #6460 which is asking for the same thing
