### ISSUE TITLE
Add resource_group_name to azurerm_virtual_network datasource attributes

### ISSUE THREAD

**Issue by EppO** [terraform-providers/terraform-provider-azurerm#5600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When implementating a Terraform module, you may have to support inputs given as datasources or terraform references. The fact that the [`azurerm_virtual_network`](https://www.terraform.io/docs/providers/azurerm/d/virtual_network.html#attributes-reference) datasource doesn't include the `resource_group_name` the resource [`azurerm_virtual_network`](https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html#attributes-reference) exports makes it difficult to have a lean and common module interface for both kind of inputs.

### New or Affected Resource(s)

* data.azurerm_virtual_network

### Potential Terraform Configuration

```hcl
module "mymodule" {
  ...
  peerings = [ { vnet = data.azurerm_virtual_network.vnet_datasource, resource_group_name = "need-to-be-provided" },
               { vnet = azurerm_virtual_network.vnet_in_current_tf_state, resource_group_name = azurerm_virtual_network.vnet_in_current_tf_state.resource_group_name }]
}
```

In the former case, you have to explicitely pass the resource_group_name as it can't be inferred by the datasource, in the latter you can use the exported attribute of the vnet resource. 
IMHO both should provide the same attributes.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @EppO 

Thanks for opening this issue :)

In Terraform all input arguments to a Data Source/Resource/Module are also available as output attributes - as such you should be able to access this on the `azurerm_virtual_network` data source since this is present as an Input e.g.

```
data "azurerm_virtual_network" "example" {
  name                = "production"
  resource_group_name = "networking"
}

output "virtual_network_id" {
  value = "data.azurerm_virtual_network.example.id
}

output "resource_group_name" {
  value = "data.azurerm_virtual_network.example.resource_group_name
}
```

Would you be able to take a look and see if that works for you?

Thanks!

**Comment by EppO** [comment]
That indeed works, my bad! I didn't put resource_group_name in the object type specification of my variable, so it was not filtering it. Thanks for your help, really appreciated!
