### ISSUE TITLE
Service Bus authorization rules are lost when a queue is recreated

### ISSUE THREAD

**Issue by mwalton-esendex** [terraform-providers/terraform-provider-azurerm#5606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v1.40.0

### Affected Resource(s)

* `azurerm_service_bus_queue`
* `azurerm_service_bus_authorization_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_queue" "message_queue" {
  name                = "message_queue"
  resource_group_name = azurerm_resource_group.my_group.name
  namespace_name      = azurerm_servicebus_namespace.our_namespace.name
  enable_partitioning = false
}

resource "azurerm_servicebus_queue_authorization_rule" "write_rule"{
  name                = "message_queue_write_rule"
  namespace_name      = azurerm_servicebus_namespace.our_namespace
  queue_name          = azurerm_servicebus_queue.message_queue.name
  resource_group_name = azurerm_resource_group.my_group
  listen              = false 
  send                = true
  manage              = false
}
```

If you have this setup, and you then change `enable_partitioning` on the queue from `false` to `true` (or `true` to `false`), which causes the queue resource to be recreated.

### Expected Behavior

Authorization rule should exist on the recreated queue.

### Actual Behavior

Authorization rule has been deleted because the queue was deleted, but Terraform does not know that this happens, so does not recreate the authorization rule.

Running `terraform apply` a second time does notice the missing rules and recreate them, but in the mean time the system is broken.

We would very much like it if the provider was aware of this behaviour and able to invalidate the authorization rules when the queue they reference is recreated.

We've tried an explicit `depends_on`, but Terraform apparently considers that depending on a recreated resource means that everything is fine as long as that resource was indeed recreated. I was hoping it would check the underlying resource ID, but apparently it doesn't and I see no way to force a dependency on that to exist.

The result of this is that if we do anything that recreates a Service Bus queue (we're assuming this applies to topics as well although we've not tested that yet), we're going to have to run terraform twice in order to get a working system again. This is not desirable.

### Steps to Reproduce

1. Set up a service bus queue and an authorization rule for it
2. Change the queue's partitioning_enabled property
3. terraform apply
4. Observe that there are no authorization rules for the queue
5. terraform apply
6. Observe that the authorization rules have now been recreated

**Comment by tombuildsstuff** [comment]
hey @mwalton-esendex 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through it appears that the root-cause of this is a bug in Terraform Core where in a Grandparent-Parent-Child resource tree, that when recreating the Parent resource using a field other than `id` doesn't detect that the Child needs recreating.

Since this is a bug in Terraform Core, unfortunately this isn't something that we're able to fix in the Azure Provider directly - and as such I'm going to close this in favour of the upstream issue https://github.com/hashicorp/terraform/issues/24663 - would you mind subscribing to that issue for updates?

Thanks!
