### ISSUE TITLE
Azure API Management sku update

### ISSUE THREAD

**Issue by Lidestyle** [terraform-providers/terraform-provider-azurerm#5611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
- provider.azurerm v1.42.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
// Create API Management instance
resource "azurerm_api_management" "apim" {
  name                = local.apim_defaults.name
  resource_group_name = var.resource_group.gateway
  location            = var.location
  publisher_name      = local.apim_defaults.apim_publisher_name
  publisher_email     = local.apim_defaults.apim_publisher_email
  sku_name            = local.apim_defaults.default_sku // "Development_1" -> "Basic_1" as an example

  policy {
    xml_content = templatefile("${path.module}/apim/global.xml.tmpl",
      {
        allowed_origins = var.admin_domains
      }
    )
  }

  tags = {
    environment = var.environment_prefix
  }

}
```

### Expected Behavior

Terraform should update API Management instance to the basic tier.

### Actual Behavior

Terraform operation succeeded, but API Management is not updated.

### Steps to Reproduce

1. Update sku_name ("Development_1" -> "Basic_1" as an example)
2. Terraform apply
3. Check API Management SKU on Azure Portal

**Comment by tombuildsstuff** [comment]
hey @Lidestyle 

Thanks for opening this issue.

Whilst both you and @loopfish have opened the same issue - since that issue contains a little more information, so that we can keep this tracked in a single place I hope you don't mind but I'm going to close this issue in favour of #5612 which is tracking the same thing - would you mind subscribing to that issue for updates?

Thanks!

**Comment by loopfish** [comment]
@tombuildsstuff FYI, I have just discovered that using the deprecated 'sku' block (with 'name' and 'capacity' parameters) does still work, and does result in a tier SKU change...
![image](https://user-images.githubusercontent.com/39245344/73756713-f2408000-475f-11ea-9cfe-621c2e39527a.png)

![image](https://user-images.githubusercontent.com/39245344/73756861-2e73e080-4760-11ea-8395-f7fdfa1bfe27.png)
