### ISSUE TITLE
Support for Azure Key Vault Key creation with activation/expiration date

### ISSUE THREAD

**Issue by Aaron-ML** [terraform-providers/terraform-provider-azurerm#5615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure key vault key generation works in a similar way as the secret and certificate generation. Azure key vault has a field to set the expiration date of the locally generated key. This allows services (JWT) to validate correctly.  The secret expiration field has been added with #4858 and I'd imagine the key creation is generally the same implementation. 

### New or Affected Resource(s)

* azurerm_key_vault_key

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_key" "generated_key" {
  name         = "GeneratedKey"
  key_vault_id = var.key_vault_id
  key_type     = "RSA"
  key_size     = 2048
  expiration_date = "2019-01-01T01:02:03Z"
  not_before_date = "2019-01-01T01:02:03Z"
  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}
```

### References

* #4873 
* #4858

**Comment by aqche** [comment]
As you mentioned, looks like it would be a similar implementation to the PR I made for `azurerm_key_vault_secret`. I'll take a look into getting a PR up for this.
