### ISSUE TITLE
Support for Azure Service Bus Naming Conventions

### ISSUE THREAD

**Issue by ElvenSpellmaker** [terraform-providers/terraform-provider-azurerm#5639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Service Bus Namespaces have very weird arbitrary naming restrictions and it'd be nice if Terraform threw an error on plan if you violate them. 🙂  

Most importantly:
> The name does not end with “-“, “-sb“ or “-mgmt“.

Currently builds throw a generic error from Microsoft on `tf apply` when it could be linted against during a `tf plan`: `Error: servicebus.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The specified service namespace is invalid. CorrelationId: ..."`

### New or Affected Resource(s)

 * `azurerm_servicebus_namespace`

### References

 * https://docs.microsoft.com/en-us/rest/api/servicebus/create-namespace

**Comment by neil-yechenwei** [comment]
@ElvenSpellmaker , thank you for raising this issue. May I know why those suffixes “-“, “-sb“, “-mgmt“ are not allowed?

**Comment by ElvenSpellmaker** [comment]
@neil-yechenwei It's just an arbitrary Microsoft restriction it seems

**Comment by neil-yechenwei** [comment]
@ElvenSpellmaker , may I know is there any doc is talking about this restriction?

**Comment by ElvenSpellmaker** [comment]
@neil-yechenwei There's a link in my first post 🙂

**Comment by ElvenSpellmaker** [comment]
Thanks @neil-yechenwei
