### ISSUE TITLE
Feature Request: create a azurerm_managed_disk from a custom os-image

### ISSUE THREAD

**Issue by donestefan** [terraform-providers/terraform-provider-azurerm#565]
Hi there,

`azurerm_managed_disk` allows to create a managed disc from a marketplace os-image.
However, it does not allow to create a managed disk from a custom os-image (e.g. one created by `azurerm_image`).

I hope you can implement this feature.
It would make it easier to separate disk creation from vm creation.

### Terraform Version
0.10.8

**Comment by clangaxon** [comment]
This not working is thwarting work-around attempts on #734

**Comment by echuvyrov** [comment]
Hi @donestefan, I updated the docs that hopefully make it clearer how to create a VM using custom images with managed disks. Let me know if this helps: https://github.com/terraform-providers/terraform-provider-azurerm/pull/897

**Comment by donestefan** [comment]
Hi @echuvyrov and thanks for creating the example. It is much appreciated!
However, in this particular case your example unfortunately does not help.

I need to separate os-disk creation and vm creation like described here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/734#issuecomment-367672275
Currently this works only as long as you use os-images from the marketplace. This issue here is about making it work with custom images like `${data.azurerm_image.my_customized_os_image.id}`.

**Comment by tombuildsstuff** [comment]
@donestefan thanks for confirming that - out of interest have you tried accessing the OS Disk within an OS Image, like so:

```
data "azurerm_image" "test" {
  name                = "search-api"
  resource_group_name = "packerimages"
}

resource "azurerm_resource_group" "test" {
  name = "some-resource-group"
  location = "West Europe" # AFAIK this needs to be in the same location as the Image Resource Group
}

resource "azurerm_managed_disk" "test" {
  name                 = "datadisk_existing"
  location             = "${azurerm_resource_group.test.location}"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  storage_account_type = "Standard_LRS"
  create_option        = "Copy"
  source_resource_id   = "${azurerm_image.test.os_disk.0.managed_disk_id}"
  os_type              = "Linux"
  disk_size_gb         = "1023"
}
```

@echuvyrov thinking about this - do you think it'd be worth creating another example like we've got [for creating a vm with an unmanaged disk from a user image](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/vm-from-user-image/main.tf)? 🤔

**Comment by donestefan** [comment]
@tombuildsstuff No, I never tried this one.  I only used `create_option = "FromImage"`.
I'll will give it a try but it won't be before next week.

**Comment by donestefan** [comment]
Hi @tombuildsstuff. And Thanks again for your help!
I have tried your recommendationabout using `create_option = "FromImage"` . But unfortunately it does not work. For some reason my `managed_image` has an empty `managed_disk_id` attribute.
I guess this is because the image has been created from a blob_uri and not from a managed_disk.

Using `create_option = "import"` also does not work. I get an error message saying "A disk or snapshot cannot be imported from a SAS URI for a blob."

It also feels a little strange to re-extract the disk from the image, right after you have spend time and ressources putting it in there... It feels like this defeats the purpose why people start creating managed images in the first place.

**Comment by tombuildsstuff** [comment]
@donestefan ah ok, in which case you should be able to do the same thing from an unmanaged disk [using the `blob_uri` attribute](https://www.terraform.io/docs/providers/azurerm/r/image.html#blob_uri) - would you be able to take a look?

Thanks!

**Comment by donestefan** [comment]
@tombuildsstuff well, I think I tried all possible combinations `import` or `copy` create_options along with `blob_uri` or `source_uri`. "terraform apply" accepts some of the combinations and starts. But it always results in an (azure-api?) error message "A disk or snapshot cannot be imported from a SAS URI for a blob."
I copied the vhd file into my subscription, so I access the blob without the SAS parameters in the url.

**Comment by donestefan** [comment]
@tombuildsstuff I did some more testing and I can now successfully create a managed_disk from the same vhd I used to create my managed_image.
```
resource "azurerm_managed_disk" "osdisk1" {
  create_option = "import"
  source_uri    = "${azurerm_storage_blob.my-generalized-vhd-file.url}"
  ...
}
```

Of course I'm not actually using my managed_image any longer...

Anyways, now that I created the managed_disk seperately, I logically use `create_option = "attach"` when creating the vm. But then I am not allowed to use the `os_profile` block any longer. So I can no longer provide a password, username or custom_data file to the vm :(

**Comment by donestefan** [comment]
Is there a reason why the `os_profile` or `os_profile_linux_config` blocks are not allowed when using `create_option     = "attach"` during vm creation? Both blocks are needed when attaching a generalized linux disk.

**Comment by tombuildsstuff** [comment]
hi @donestefan 

Apologies for the delayed response here!

> Is there a reason why the os_profile or os_profile_linux_config blocks are not allowed when using create_option = "attach" during vm creation? Both blocks are needed when attaching a generalized linux disk.

Unfortunately this behaviour is coming from the Azure API which requires these aren't specified when creating a VM from a Custom Image.

That said - Shared Image Galleries have recently been announced by Azure / added to Terraform which provide another way of handling this - allowing you to add images to a Gallery and then use a Gallery reference to provision that image using the same approach you would a Public image (for example, allowing the `os_profile_linux_config` block. As such I'm wondering if that's a better solution/approach here?


Unfortunately in either case this behaviour is coming from the underlying Azure API - so I don't believe there's a great deal we can to work around this; that said we're planning on revamping the Virtual Machine / Virtual Machine Scale Set resources in the next major release of the AzureRM Provider (2.0) - so I'd recommend keeping an eye on [that milestone](https://github.com/terraform-providers/terraform-provider-azurerm/milestone/31) for updates (we'll be asking for feedback in the near future).

All that to say - at this point I don't believe there's much more we can do in the AzureRM Provider to fix this (since this is the behaviour of the underlying API) - and as such I'm going to close this issue for the moment.

Thanks!

**Comment by adamday2** [comment]
We're running into a use-case where the originally requested feature (if possible) would be greatly beneficial.

When combining with an image creation tool, such as packer, the suggestion to use source_resource_id does not work as the VHD may not necessarily exists. 

We are also unable to use `virtual_machine --> storage_os_disk` directly on VM creation as storage_os_disk does not provide the capability to enable disk encryption.
