### ISSUE TITLE
APIM Virtual Network Support

### ISSUE THREAD

**Issue by nezoic** [terraform-providers/terraform-provider-azurerm#5665]
It looks like this has been requested several times already but constantly gets closed from some other bugs that are closed but not resolved? Some from May of last year.

Any way we can get this implemented? 
[PR 2582](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2582)
[Issue 3667](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3667)

**Comment by tracypholmes** [comment]
Hi @nezoic! In the interest of keeping duplication down, I am going to close this issue in favor of #3667 as it is open. Please follow that issue for any updates and/or concerns. Thanks:smiley:
