### ISSUE TITLE
[azurerm_key_vault_secret] Writing a connection string into a key vault secret value, fails.

### ISSUE THREAD

**Issue by tobiasschueler** [terraform-providers/terraform-provider-azurerm#5674]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12.20
azurerm 1.43.0

### Affected Resource(s)
azurerm_key_vault_secret

### Terraform Configuration Files

```hcl

resource "azurerm_iothub_dps" "dps" {
  name                = local.provisioning-service-name
  resource_group_name = azurerm_resource_group.iothub.name
  location            = azurerm_resource_group.iothub.location

  sku {
    name     = "S1"
    capacity = "1"
  }

  linked_hub {
    location          = azurerm_resource_group.iothub.location
    connection_string = "HostName=${azurerm_iothub.iothub.hostname};SharedAccessKeyName=${azurerm_iothub.iothub.shared_access_policy.0.key_name};SharedAccessKey=${azurerm_iothub.iothub.shared_access_policy.0.primary_key}"
  }

}

#### Shared Access Policy - BE Service SDK
resource "azurerm_iothub_dps_shared_access_policy" "dpssapbeservices" {
  name                = "backend-services"
  resource_group_name = azurerm_resource_group.iothub.name
  iothub_dps_name     = azurerm_iothub_dps.dps.name

  service_config = false
  enrollment_write = true
  enrollment_read  = true
  registration_read = true
  registration_write = true
}

#### Key Vault Secret - BE Service primary key
data "azurerm_key_vault" "key_vault_name" {
  name                = "my-secret-vault"
  resource_group_name = "keyvault-group"
}

resource "azurerm_key_vault_secret" "key_vault_secret" {
  name         = "some-secret-name-dev"
  value        = azurerm_iothub_dps_shared_access_policy.dpssapbeservices.primary_connection_string
  key_vault_id = data.azurerm_key_vault.key_vault_name.id
  
  tags = {
    source      = "terraform"
    environment = var.namespace
  }
}
```

### Expected Behavior
- secret should be created

### Actual Behavior
Creation of secret did not happend. The following error message appears:
`Error: Provider produced inconsistent final plan

When expanding the plan for
module.iothub-dev.azurerm_key_vault_secret.dps_sap_be_services_key_vault_secret
to include new values learned so far during apply, provider
"registry.terraform.io/-/azurerm" produced an invalid new value for .value:
inconsistent values for sensitive attribute.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The value is an connection string which contains 172 characters: `HostName=xx-iothub-provisioning-service-dev.azure-devices-provisioning.net;SharedAccessKeyName=backend-services;SharedAccessKey=XXX` which will be detected as sensitiv data.
Adding a "normal" string as value work well.

**Comment by markti** [comment]
[1m[31mError: [0m[0m[1mProvider produced inconsistent final plan[0m
2020-03-21T19:56:13.8286096Z 
2020-03-21T19:56:13.8286605Z [0mWhen expanding the plan for
2020-03-21T19:56:13.8287301Z module.iot_hub.azurerm_key_vault_secret.secret_iotdps_connstr to include new
2020-03-21T19:56:13.8288038Z values learned so far during apply, provider "registry.terraform.io/-/azurerm"
2020-03-21T19:56:13.8288695Z produced an invalid new value for .value: inconsistent values for sensitive

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems secret can be created successfully with below tfconfig. Seems I cannot repro the issue. Maybe I missed something. If you need, you can try below config and check whether the problem still exists. Thanks.

tfconfig:
```
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-kvs-neil"
  location = "westus"
}

resource "azurerm_key_vault" "test" {
  name                = "acctestkv-neil"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "premium"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get",
      "delete",
      "set",
    ]
  }
}

resource "azurerm_iothub" "test" {
  name                = "acctestIoTHubneil"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  sku {
    name     = "S1"
    capacity = "1"
  }
}

resource "azurerm_iothub_dps" "test" {
  name                = "iotdps-neil"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  sku {
    name     = "S1"
    capacity = "1"
  }

  linked_hub {
    location          = azurerm_resource_group.test.location
    connection_string = "HostName=${azurerm_iothub.test.hostname};SharedAccessKeyName=${azurerm_iothub.test.shared_access_policy.0.key_name};SharedAccessKey=${azurerm_iothub.test.shared_access_policy.0.primary_key}"
  }
}

resource "azurerm_iothub_dps_shared_access_policy" "test" {
  name                = "backend-services-neil"
  resource_group_name = azurerm_resource_group.test.name
  iothub_dps_name     = azurerm_iothub_dps.test.name

  service_config = false
  enrollment_write = true
  enrollment_read  = true
  registration_read = true
  registration_write = true
}

resource "azurerm_key_vault_secret" "test" {
  name         = "secret-neil"
  value        = azurerm_iothub_dps_shared_access_policy.test.primary_connection_string
  key_vault_id = azurerm_key_vault.test.id
}

output "connectionstring" {
  value = azurerm_iothub_dps_shared_access_policy.test.primary_connection_string
}
```

The result of tf apply:
```
azurerm_key_vault_secret.test: Creating...
azurerm_key_vault_secret.test: Still creating... [10s elapsed]
azurerm_key_vault_secret.test: Creation complete after 10s [id=https://acctestkv-neil.vault.azure.net/secrets/secret-neil/a708cc294ba54ad3a039c29bc79fb0aa]

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.
```

The secret value in azure portal:
![image](https://user-images.githubusercontent.com/19754191/80459893-a61f6900-8965-11ea-8c3a-4cbc8a4cd42e.png)

**Comment by spudoss** [comment]
@neil-yechenwei Try changing the name of your Key Vault secret after the first successful run. That is where I am seeing a consistent failure. Here is the exact code that I am testing with:

`provider "azurerm" {
  version         = "=2.7.0"
  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  
  features {}
}

data "azurerm_client_config" "current" {}

resource "random_string" "resource_postfix" {
  length  = 5
  special = false
  upper   = false
}

resource "azurerm_resource_group" "rg" {
  name     = "test-rg-${random_string.resource_postfix.result}"
  location = "eastus"
}

resource "azurerm_iothub_dps" "dps" {
  name                = "test-dps-${random_string.resource_postfix.result}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  sku {
    name     = "S1"
    capacity = "1"
  }
}

resource "azurerm_iothub_dps_shared_access_policy" "policy" {
  name                = "test-dps-sap-${random_string.resource_postfix.result}"
  resource_group_name = azurerm_resource_group.rg.name
  iothub_dps_name     = azurerm_iothub_dps.dps.name

  enrollment_write   = true
  enrollment_read    = true
  registration_write = true
  registration_read  = true
  service_config     = false
}

resource "azurerm_key_vault" "kv" {
  name                        = "test-kv-${random_string.resource_postfix.result}"
  location                    = azurerm_resource_group.rg.location
  resource_group_name         = azurerm_resource_group.rg.name
  tenant_id                   = var.tenant_id
  sku_name                    = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get",
      "delete",
      "set",
    ]
  }
}

resource "azurerm_key_vault_secret" "secret" {
  name         = "DPSConnectionString"
  value        = azurerm_iothub_dps_shared_access_policy.policy.primary_connection_string
  key_vault_id = azurerm_key_vault.kv.id
}`

**Comment by neil-yechenwei** [comment]
Thanks. I can repro it now. Seems adding lifecycle can workaround this issue.

tfconfig
```
resource "azurerm_iothub_dps_shared_access_policy" "test" {
  name                = "acctest-idsap-tester"
  resource_group_name = azurerm_resource_group.test.name
  iothub_dps_name     = azurerm_iothub_dps.test.name
  enrollment_write    = true
  enrollment_read    = true
  registration_write = true
  registration_read  = true
  service_config     = false
  
  lifecycle {
    ignore_changes = [enrollment_read, registration_write, registration_read]
  }
}
```

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here this appears to be the same root-cause as #8745 and so will be fixed when that is fixed - as such I'm going to close this issue for the moment, but would you mind subscribing to #8745 for updates?

Thanks!
