### ISSUE TITLE
azurerm_policy_assignment error - Calling wrong API version?

### ISSUE THREAD

**Issue by juanjojulian** [terraform-providers/terraform-provider-azurerm#5677]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v1.43.0

### Affected Resource(s)

* `azurerm_policy_assignment `

### Terraform Configuration Files

```hcl
resource "azurerm_policy_assignment" "DenyPublicIPAssignment" {
  name                 = "DenyPublicIPAssignment"
  scope                = "/providers/Microsoft.Management/managementgroups/MyGroup/Spoke"
  policy_definition_id = azurerm_policy_definition.DenyPublicIP.id
  description          = "This policy denies public IP and public IP prefixes creation."
  display_name         = "Deny PublicIP Assignment"

  parameters = <<PARAMETERS
    {
      "listOfResourceTypesNotAllowed": {
        "value": [
          "Microsoft.Network/publicIPAddresses",
          "Microsoft.Network/publicIPPrefixes"
        ]
      }
    }
PARAMETERS
}
```

### Expected Behavior

Assign azurerm_policy_definition.DenyPublicIP.id to the scope: "/providers/Microsoft.Management/managementgroups/MyGroup/Spoke"

### Actual Behavior

azurerm_policy_assignment.DenyPublicIPAssignment: Creating...

Error: policy.AssignmentsClient#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="InvalidResourceType" Message="The resource type 'managementGroups' could not be found in the namespace 'Microsoft.Management' for api version '2018-05-01'. The supported api-versions are '2019-11-01,2018-03-01-preview,2018-01-01-preview,2017-11-01-preview,2017-08-31-preview,2017-06-30-preview,2017-05-31-preview,2018-03-01-beta'."

  on azure-policies-no_public_ip.tf line 73, in resource "azurerm_policy_assignment" "DenyPublicIPAssignment":
  73: resource "azurerm_policy_assignment" "DenyPublicIPAssignment" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It looks like azurerm provider is pointing to an invalid API version? Version 2018-05-01 is not listed as a supported API version: '2019-11-01,2018-03-01-preview,2018-01-01-preview,2017-11-01-preview,2017-08-31-preview,2017-06-30-preview,2017-05-31-preview,2018-03-01-beta'." and if I try to make use of it via Postman or Curl I get the same error as the Terraform provider.

**Comment by ArcturusZhang** [comment]
Hi @juanjojulian as far as I know, the valid scope of a policy assignment can only be one of the following:
1. management group (format: `/providers/Microsoft.Management/managementGroups/{managementGroup}`
1. subscription (format:
`/subscriptions/{subscriptionId}`
1. resource group (format: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}`
1. resource (format: `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/[{parentResourcePath}/]{resourceType}/{resourceName}`

The scope in your config should be a management group, but it does not conform the format above (with an extra segment `Spoke`).

**Comment by juanjojulian** [comment]
Hi @ArcturusZhang  thanks for your reply. "/providers/Microsoft.Management/managementgroups/MyGroup/Spoke" is a Management Group which ID is "Spoke". 
Take into account that management groups can be nested in the following form: /providers/Microsoft.Management/managementGroups/{managementGroup}/{managementGroup}. In my case "Spoke" management group is a child of "MyGroup" management group.

Hope I explained my self and made clear that 'Spoke" is a valid scope for a policy assignment, in fact I did the assignment manually using the portal with no problems.

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang thanks for your reply. "/providers/Microsoft.Management/managementgroups/MyGroup/Spoke" is a Management Group which ID is "Spoke".
> Take into account that management groups can be nested in the following form: /providers/Microsoft.Management/managementGroups/{managementGroup}/{managementGroup}. In my case "Spoke" management group is a child of "MyGroup" management group.
> 
> Hope I explained my self and made clear that 'Spoke" is a valid scope for a policy assignment, in fact I did the assignment manually using the portal with no problems.

I see. So is the mgmt group `MyGroup` is the parent of `Spoke` if I understand this right? I am going to try if I can reproduce your issue, and then may figure out a way to fix this.

**Comment by juanjojulian** [comment]
> I see. So is the mgmt group `MyGroup` is the parent of `Spoke` if I understand this right? I am going to try if I can reproduce your issue, and then may figure out a way to fix this.

Yes, that's correct. Thanks, I really appreciate it :-)

**Comment by ArcturusZhang** [comment]
> > I see. So is the mgmt group `MyGroup` is the parent of `Spoke` if I understand this right? I am going to try if I can reproduce your issue, and then may figure out a way to fix this.
> 
> Yes, that's correct. Thanks, I really appreciate it :-)

Well, first I am trying to create a management group with an ID of the format you are using, but I failed on that. My management group can only be in form of `/providers/Microsoft.Management/managementGroups/TestChild` even when it is a child of other management groups.
And I have some investigation on the api-versions listed in the error message. It is a super-set of all supported api-versions for management groups (you can find them [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/managementgroups/resource-manager/Microsoft.Management)). There are also three api-versions (`2017-06-30-preview`, `2017-05-31-preview`, `2018-03-01-beta`) is not in the list of mgmt group api-versions. But I did a thorough search in the azure-rest-api-specs, there is no service of these three api-versions.
Therefore I am still thinking that there is something wrong with your mgmt group id you are using. To investigate this, could you please use another cli tool such as the [`azure cli`](https://docs.microsoft.com/en-us/cli/azure/account/management-group?view=azure-cli-latest#az-account-management-group-show) or [`azure powershell`](https://docs.microsoft.com/bs-cyrl-ba/azure/governance/management-groups/manage) to directly get the full id of your mgmt group? Because as far as I know, the portal will do some extra work other than the pure rest api, and sometimes it may by-pass the rest api and use some internal api to do things.

**Comment by juanjojulian** [comment]
> Well, first I am trying to create a management group with an ID of the format you are using, but I failed on that. My management group can only be in form of `/providers/Microsoft.Management/managementGroups/TestChild` even when it is a child of other management groups.

Ok, your are completely right.
I'm completely nuts and embarrassed :-(
And the error response from Azure API makes no sense.

As you said, I was using the wrong ID for the child management group, correct one is:

```
/providers/Microsoft.Management/managementGroups/Spoke
```
Instead of
```
/providers/Microsoft.Management/managementGroups/MyGroup/Spoke
```


Thanks for your help and sorry for the inconvenience, I will close this issue now.
