### ISSUE TITLE
Terraform lifecycle flag "create_before_destroy" not working as expected

### ISSUE THREAD

**Issue by bhushangholve2006** [terraform-providers/terraform-provider-azurerm#568]
Hi there,

I want to set up lifecycle{create_before_destroy=true}  for virtual machine scale set so if I am modifying the os_profile of VM and run terraform apply again then it should create new vmss with new image and not modifying the existing one.
For terraform script for vmss I set up lifecycle flag "create_before_destroy" as true and when I am updating the image sku it is just modifying existing one and not creating the new instance.

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
azurerm_virtual_machine_scale_set

### Terraform Configuration Files
```
resource "azurerm_virtual_machine_scale_set" "az_vmss" {
name 			= "${var.az_vmss_name}"	 
location            = "${var.azure_region}"
resource_group_name = "somegroup"
upgrade_policy_mode ="Manual"
lifecycle  {
    create_before_destroy=true
 }

	sku {
	name	= "Standard_A1"
	tier	= "Standard"
	capacity = 2  
	}

storage_profile_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
   storage_profile_os_disk {
    name              = ""
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
   storage_profile_data_disk {
      lun          = 0
    caching        = "ReadWrite"
    create_option  = "Empty"
    disk_size_gb   = 10
  }
  os_profile {
    computer_name_prefix = "testvm"
    admin_username       = "myadmin"
    admin_password       = "Passwword1234"
  }
  os_profile_linux_config {
    disable_password_authentication = false
  }
  
  network_profile {
    name    = "terraformnetworkprofile"
    primary = true

    ip_configuration {
      name                                   = "TestIPConfiguration"
      subnet_id                              = "${var.subnetid}"
      load_balancer_backend_address_pool_ids = ["${azurerm_lb_backend_address_pool.az_lb1_pool1.id}"]
      load_balancer_inbound_nat_rules_ids    = ["${element(azurerm_lb_nat_pool.lbnatpool.*.id, count.index)}"]
    }
  }
  
  tags {
    environment = "terraform"
  }
}
```
Above script just runs fine but not giving the expected result.
Because If I am updating this and then doing terraform apply

```
storage_profile_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "**17.04-LTS**"
    version   = "latest"
  }
```
It modifying existing VMSS and not spinning up new one and destroy after new one finished creating as per the flag "lifecycle  {
    create_before_destroy=true
 }".

### Debug Output
Modifying existing VMSS

### Expected Behavior
It should have started creating new vmss by keeping existing one and then after creation delete old vmss. 

### Actual Behavior
It is modifying existing vmss that is not what i want

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Referred this document https://www.terraform.io/docs/configuration/resources.html

**Comment by paddycarver** [comment]
Hi @bhushangholve2006,

Sorry for the confusion! `lifecycle.create_before_destroy` doesn't actually impact whether a resource is updated in place or recreated--it just says that if a resource _is_ recreated, a new copy should be created before the old copy is destroyed. Otherwise, Terraform destroys the old copy, then creates the new copy.

Assuming what you want is for a resource to be destroyed even though it _could be_ updated in place, the closest thing I can think of is the [`terraform taint`](https://www.terraform.io/docs/commands/taint.html) command.

**Comment by bhushangholve2006** [comment]
Thanks for the response @paddycarver ,
Info you gave for `lifecycle.create_before_destroy` is correct.
No I don't want the resource to be destroyed. 
When I try to update the resource it should not modify the existing one, according to the documents it should create new resource before destroying the existing resource. But it is modifying the existing resource.
My understanding was when I use this flag it should spin up new resource like blue green deployment and when the new one finished creating, old one gets destroyed. `terraform taint` is destroying the existing one first before creating the new one.
Suppose I would not like to have any downtime for my application but when I am updating something on VMSS it should create similar VMSS first and then destroy the old one.
I hope you got my point!!!!!

**Comment by nbering** [comment]
@bhushangholve2006 You could use the [randome provider](https://www.terraform.io/docs/providers/random/index.html) with it's "keepers" feature, and then use a random ID in your scale set name to force a new resource when the keeper(s) change.

This has the added benefit of avoiding naming conflicts with create before destroy since the new scale set would have a different name.

**Comment by paddycarver** [comment]
@bhushangholve2006 From what I can tell, you want the provider to create a new resource with your changes, then destroy the old one, but instead it's updating the old one in place.

If that's the case, you'd need to update a field that forces a new resource as well, as there's no way to tell Terraform not to update in place, that I know of. If Terraform _can_ update in place, it will, so you have to force it to not be able to by changing a field that can't be updated in place. For the resource you listed, updating the `name` field would force Terraform to create a new one.

`create_before_destroy` does not force Terraform to not update in place. It just says if Terraform _can't_ update in place, the new resource should be created before the old resource is destroyed. Without it set, the old resource would be destroyed first, then the new resource would be created.

**Comment by bhushangholve2006** [comment]
okay got your point thanks for the inputs @paddycarver

**Comment by paulmackinnon-adv365** [comment]
@paddycarver is there a function that would do exactly what was originally asked? we have weekly rebuilds of VMs that need to be created before the older one dies, and this sounded like it could have been the solution.

**Comment by paddycarver** [comment]
Unfortunately, there isn't a built-in way to make Terraform recreate a resource it doesn't otherwise have to. The best I can suggest is the [`taint`](https://www.terraform.io/docs/commands/taint.html) command. If you need something more than that, I'd recommend opening an issue on [upstream Terraform](https://github.com/hashicorp/terraform/issues).

**Comment by tombuildsstuff** [comment]
@paulmackinnon-adv365 I've not tested this - but this should be possible by suffixing a random ID to the end of the name of the VM+related resources using the `random_id` resource?

**Comment by paulmackinnon-adv365** [comment]
@tombuildsstuff Good idea, thanks. I actually incorporated the date into the name via:

```
locals {
  name_prefix                       = "n1-${substr(lower(replace(replace(replace(timestamp(),"-",""),"T",""),":","")),0,8)}"
}

resource "azurerm_virtual_machine" "vm-windows" {
  name                              = "${local.name_prefix}"
```
