### ISSUE TITLE
Support for multiple frontends and backends in Azure Application Gateway

### ISSUE THREAD

**Issue by ctrombet** [terraform-providers/terraform-provider-azurerm#5697]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Azure application gateway is able to route based on URL to pool of resources.
It is possible to configure several gateway's frontends to allow Multi Sites routing and serve different URLs to different backend pools.
Terraform allow only one frontend and one backend pool, not being them considered separate resources.

### New or Affected Resource(s)

Affected:
* azurerm_application_gateway
New:
* azurerm_application_gateway_ip_configuration
* azurerm_application_gateway_ip_attachment
* azurerm_application_gateway_frontend_port
* azurerm_application_gateway_frontend_port_attachment
*  azurerm_application_gateway_frontend_ip_configuration
* azurerm_application_gateway_frontend_ip_configuration_attachment
* azurerm_application_gateway_backend_address_pool
* azurerm_application_gateway_backend_address_pool_attachment
* azurerm_application_gateway_backend_http_settings
* azurerm_application_gateway_backend_http_settings_attachment
* azurerm_application_gateway_request_routing_rule
* azurerm_application_gateway_request_routing_rule_attachment

### Potential Terraform Configuration

```
resource "azurerm_application_gateway" "test" {
  name                = "name"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }

  gateway_ip_configuration {
         ### OPTIONAL 
  }

  frontend_port {
         ### OPTIONAL 
  }

  frontend_ip_configuration {
         ### OPTIONAL 
  }

  backend_address_pool {
         ### OPTIONAL 
  }

  backend_http_settings {
         ### OPTIONAL 
  }

  http_listener {
         ### OPTIONAL 
  }

  request_routing_rule {
    name                       = "${local.request_routing_rule_name}"
    rule_type                  = "Basic"
    http_listener_name         = "${local.listener_name}"
    backend_address_pool_name  = "${local.backend_address_pool_name}"
    backend_http_settings_name = "${local.http_setting_name}"
  }
}

resource "azurerm_application_gateway_ip_configuration" "ip_configuration" {
   ...
}

resource "azurerm_application_gateway_ip_attachment" "gateway_ip_attachment" {
  application_gateway_id    = azurerm_application_gateway.test.id
  gateway_ip_id = azurerm_application_gateway_ip_configuration.ip_configuration.id
  ...
}

resource "azurerm_application_gateway_frontend_port" "frontend_port" {
  ...
}

resource "azurerm_application_gateway_frontend_port_attachment" "frontend_port_attachment" {
  application_gateway_id    = azurerm_application_gateway.test.id
  frontend_port_id = azurerm_application_gateway_frontend_port.frontend_port.id
  ...
}

resource "azurerm_application_gateway_frontend_ip_configuration" "frontend_ip_configuration" {
  ...
}

resource "azurerm_application_gateway_frontend_ip_configuration_attachment" "frontend_ip_configuration_attachment" {
  application_gateway_id    = azurerm_application_gateway.test.id
  frontend_port_id = azurerm_application_gateway_frontend_ip_configuration.frontend_ip_configuration.id
  ...
}

resource "azurerm_application_gateway_backend_address_pool" "backend_address_pool" {
  ...
}
resource "azurerm_application_gateway_backend_address_pool_attachment" "backend_address_pool_attachment" {
  application_gateway_id    = azurerm_application_gateway.test.id
  frontend_port_id = azurerm_application_gateway_backend_address_pool.backend_address_pool.id
  ...
}

resource "azurerm_application_gateway_backend_http_settings" "backend_http_settings" {
  ...
}

# Attachment for this following same conventions (avoided to replicate similar approach)

resource "azurerm_application_gateway_backend_address_pool" "backend_address_pool_attachment" {
  application_gateway_id    = azurerm_application_gateway.test.id
  frontend_port_id = azurerm_application_gateway_backend_address_pool.backend_address_pool.id
  ...
}

# Attachment for this following same conventions (avoided to replicate similar approach)
resource "azurerm_application_gateway_http_listener" "http_listener" {
  ...
}

resource "azurerm_application_gateway_request_routing_rule" "request_routing_rule" {
  ...
}

Attachment for this following same conventions (avoided to replicate similar approach)



```

### References

Step-by-Step tutorial: https://docs.microsoft.com/en-us/azure/application-gateway/create-url-route-portal
Documentation on the service (URL based rules) : https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview

* #0000

**Comment by tombuildsstuff** [comment]
hi @ctrombet 

Thanks for opening this issue.

It's possible to define multiple frontend/backend etc blocks within the `azurerm_application_gateway` resource - for example:

```
resource "azurerm_application_gateway" "test" {
  # ...

  backend_address_pool { ... }
  backend_address_pool { ... }

  frontend_port { .. }
  frontend_port { ... }
}
```

As such I believe this should be possible today - or are you more looking for this to be split out into multiple resources ala the Load Balancer resources?

Thanks!

**Comment by ctrombet** [comment]
Hi @tombuildsstuff  thanks a lot for your answer.
I was not aware of this syntax which is nice, but I am also considering/facing some issues due to the fact that I would like to be able to generate those dynamically based on several properties (for example based on number of vms to address or other parameters , number of environments to balance, etc.)

For example I want to be able to address via the gateway one single machine using **cutomer1-virtual-machine1.example.com** but also being able to access the entire pool in the backend, using for instance **customer1-virtual-machine.example.com**) and I possibly want to use the same gateway to balance other _environments_ like customer2-virtual-machine1.example.com or in general customer2-virtual-machine.example.com.

Let's say I'd like to use the **count**  property on the proper resource to be able to cycle through single virtual machines and cycle in general on environments.

I believe with this codebase it is not possible ATM.

Cheers!

**Comment by tombuildsstuff** [comment]
@ctrombet 

You can achieve this using the `for_each` operator - for example:

```
resource "azurerm_application_gateway" "test" {
  # ...

  dynamic "backend_address_pool" {
    for_each = var.list_of_pools
    content {
      name      = backend_address_pool.name
      value     = backend_address_pool.value
    }
  }
}
```

Since this is a usage question rather than a bug in the Azure Provider (which is what we use these issues for) I'm going to close this issue for the moment - however I believe that should solve your problem but more information on `for_each` can be found [in the launch blogpost for 0.12](https://www.hashicorp.com/blog/announcing-terraform-0-12/) and on Terraform.io :)

Thanks!
