### ISSUE TITLE
Cannot import azurerm_storage_container created from Azure static website

### ISSUE THREAD

**Issue by dcfsc** [terraform-providers/terraform-provider-azurerm#5701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.17
+ provider.azurerm v1.43.0

### Affected Resource(s)

* `azurerm_storage_container`

### Terraform Configuration Files

```hcl

resource azurerm_resource_group dollarweb {
  name     = "dollarweb-rg"
  location = "eastus2"
}

resource "azurerm_storage_account" "dollarweb" {
  name = "dollarwebsto"
  resource_group_name = azurerm_resource_group.dollarweb.name
  location            = azurerm_resource_group.dollarweb.location
  account_kind = "StorageV2"
  account_tier = "Standard"
}

// CASE 1
resource azurerm_storage_container dollarweb {
  name                  = "$web"
  storage_account_name  = azurerm_storage_account.dollarweb.name
  container_access_type = "blob"
}

// CASE 2
resource azurerm_storage_container dollardollarweb {
  name                  = "$$web" // escape the value?
  storage_account_name  = azurerm_storage_account.dollarweb.name
  container_access_type = "blob"
}
```

### Expected Behavior

We have existing Azure static website hosting. I am trying to backfill some Terraform to control future deployments.

Creating an Azure static website will create a storage container called `$web`. See the [setting-up-a-static-website](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website#setting-up-a-static-website) article.

This, of course, seems to be an illegal character in a storage container.  See [resource-name-rules for storage containers](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage)

`terrraform import` should link the resource with the container URL, in this case `https://dollarwebsto.blob.core.windows.net/$web`

### Actual Behavior

In case 1
```
$ terraform import azurerm_storage_container.dollarweb https://dollarwebsto.blob.core.windows.net/$web
Acquiring state lock. This may take a few moments...
azurerm_storage_container.dollarweb: Importing from ID "https://dollarwebsto.blob.core.windows.net/"...
azurerm_storage_container.dollarweb: Import prepared!
  Prepared azurerm_storage_container for import
azurerm_storage_container.dollarweb: Refreshing state... [id=https://dollarwebsto.blob.core.windows.net/]

Error: Error retrieving Container "" (Account "dollarwebsto" / Resource Group "dollarweb"): containers.Client#GetPropertiesWithLeaseID: Invalid input: `containerName` cannot be an empty string.
```

In case 2
```
$ terraform import azurerm_storage_container.dollardollarweb https://dollarwebsto.blob.core.windows.net/$web
Acquiring state lock. This may take a few moments...
azurerm_storage_container.dollardollarweb: Importing from ID "https://dollarwebsto.blob.core.windows.net/"...
azurerm_storage_container.dollardollarweb: Import prepared!
  Prepared azurerm_storage_container for import
azurerm_storage_container.dollardollarweb: Refreshing state... [id=https://dollarwebsto.blob.core.windows.net/]

Error: Error retrieving Container "" (Account "dollarwebsto" / Resource Group "dollarweb"): containers.Client#GetPropertiesWithLeaseID: Invalid input: `containerName` cannot be an empty string.
```

I was able to get the import to succeed by using the URLencoded form of the URL:

```
$ terraform import azurerm_storage_container.dollarweb https://dollarwebsto.blob.core.windows.net/%24web
azurerm_storage_container.dollarweb: Importing from ID "https://dollarwebsto.blob.core.windows.net/%24web"...
azurerm_storage_container.dollarweb: Import prepared!
  Prepared azurerm_storage_container for import
azurerm_storage_container.dollarweb: Refreshing state... [id=https://dollarwebsto.blob.core.windows.net/%24web]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

```

This seems bad somehow as the string URL is different. Also, the content of the state file persisted is (edited for brevity):

```json
 {
      "mode": "managed",
      "type": "azurerm_storage_container",
      "name": "dollarweb",
      "provider": "provider.azurerm",
      "instances": [
        {
          "attributes": {
            "id": "https://dollarwebsto.blob.core.windows.net/%24web",
            "name": "$web",
            "resource_group_name": "dollarweb-rg",
            "storage_account_name": "dollarwebsto"
 }}]}
```

I am not sure if this will affect future operations. It would be better if it just worked with `$web`.

### References

Related issues with `$web` name on creation

* #3894
* #3896
* #4329

**Comment by dcfsc** [comment]
Also, the name `$web` or `$$web` is not allowed. Not sure how I missed that.

```
$ terraform plan

Error: only lowercase alphanumeric characters and hyphens allowed in "name": "$$web"
  on dollarwebsto.tf line 44, in resource "azurerm_storage_container" "dollarweb":
  44: resource "azurerm_storage_container" "dollarweb" {
```

**Comment by tombuildsstuff** [comment]
hi @dcfsc 

Thanks for opening this issue.

The character `$` is a control character in Bash and thus needs to be escaped - in this instance since the ID's being passed in you can quote the ID, for example:

```bash
$ terraform import azurerm_storage_container.dollarweb "https://dollarwebsto.blob.core.windows.net/$web"
```

Terraform itself allows the use of `$web` as a string (since it's not a control character here) and thus this shouldn't need encoding so this should work:

```
resource azurerm_storage_container dollarweb {
  name                  = "$web"
  storage_account_name  = azurerm_storage_account.dollarweb.name
  container_access_type = "blob"
}
```

Would you be able to take a look and see if that works for you? Since this is a usage question rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by dcfsc** [comment]
```
resource "azurerm_storage_container" "dollarfred" {
  name                  = "$fred"
  storage_account_name  = azurerm_storage_account.dollarwebsto.name
  container_access_type = "private"
}
```
still fails
```
$ tf plan
Acquiring state lock. This may take a few moments...

Error: only lowercase alphanumeric characters and hyphens allowed in "name": "$fred"
  on dollarwebsto.tf line 68, in resource "azurerm_storage_container" "dollarfred":
  68: resource "azurerm_storage_container" "dollarfred" {
```

Interestingly, it also fails if I try to add the "$fred" storage container in the portal.

**Comment by tombuildsstuff** [comment]
@dcfsc there's validation that matches `$root` or `$web` (or `0-9a-z-`) since these are the only possible values - as such `$fred` isn't supported unfortunately (and why this doesn't work in the Portal either).

Presumably (I'm unsure) the `$[name]` prefix is reserved for Azure specific functionality - to ensure that existing Containers don't conflict?
