### ISSUE TITLE
Support for enabling encryption in azurerm_kusto_cluster

### ISSUE THREAD

**Issue by patrickbsf** [terraform-providers/terraform-provider-azurerm#5713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azurerm_kusto_cluster resource needs to allow cluster encryption to be enabled.

Based on other settings in azurerm resources which follow the pattern of enable_xx_encryption = true|false, something like:
enable_cluster_encryption = true
or simply:
enable_encryption = true   (since it's already in the cluster resource definition)
would be fine.

Currently, you have to enable it manually after creating the cluster through terraform.
There may be other options like this that aren't currently exposed in this resource, but this is what stands out to me right now.

### New or Affected Resource(s)

* azurerm_kusto_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kusto_cluster" "cluster" {
  name = var.name
  location  = var.location
  resource_group_name = var.resource_group_name

  enable_encryption = true

  sku {
    capacity = 2
    name     = "Standard_D11_v2"
  }
}
```

**Comment by aqche** [comment]
I can take a look into getting a PR up for this!

**Comment by njuCZ** [comment]
@aqche I am sorry it seems I have made a duplicate work...... I will close my PR. And would you mind to add more fields support in your PR: such as `enable_streaming_ingest`

**Comment by aqche** [comment]
Sorry @njuCZ, I didn't mean to end up duplicating work. I'll pull your commits into my PR to make sure the effort you put in will be included!
