### ISSUE TITLE
Removing Deprecated Fields

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#572]
For a while now we've had a series of fields marked as Removed (which should be able to be safely removed) and Deprecated (which can now be marked as Removed)

As part of the next major release, we should look into removing the `Removed` fields from the Schema and update the `Deprecated` fields to be `Removed` (so they can be removed in a future version) - off the top of my head, this includes:

 - ✅`diagnostics_profile` - Virtual Machine
 - `location` - LB/ServiceBus/EventHub

**Comment by katbyte** [comment]
Closing this as no longer relevant. This will be done from by searching the source.
