### ISSUE TITLE
How to create azure machine learning service using terrafom. Is there any direct module from azurerm provider? 

### ISSUE THREAD

**Issue by mithunvikram** [terraform-providers/terraform-provider-azurerm#5723]
To create azure machine learning serivce using terraform, I don't find any modules in azurerm provider docs.What is the possible way to achieve?

**Comment by tombuildsstuff** [comment]
hi @mithunvikram 

Support for provisioning Machine Learning Services is being tracked in #3729 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one - as such would you mind subscribing to #3729 for updates?

Thanks!
