### ISSUE TITLE
Support for WAF Policy Managed Rule definitions

### ISSUE THREAD

**Issue by rdbartram** [terraform-providers/terraform-provider-azurerm#5727]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In when configuring the WAF policy. In addition to defining custom rules I want to be able to defined which predefined/managed rules are active on the policy. This is supported by ARM right now and I assume az cli too.

### New or Affected Resource(s)

* azurerm_web_application_firewall_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_web_application_firewall_policy" "example" {
  name                = "example-wafpolicy"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  managedRuleSet {
    ruleSetType    = "OWASP"
    ruleSetVersion = "3.1"
    
    ruleGroupOverride {
      ruleGroupName = "REQUEST-920-PROTOCOL-ENFORCEMENT"
      disabledRules = [
        "920300",
        "920440"
      ]
    }

    ruleGroupOverride {
      ruleGroupName = "REQUEST-942-APPLICATION-ATTACK-SQLI"
      disabledRules = [
        "942440"
      ]
    }
  }
}
```

**Comment by sirlatrom** [comment]
I have a pull request coming for this. I'll try to accommodate the suggested Terraform config.
