### ISSUE TITLE
Resource "azurerm_kubernetes_cluster" is leaking sensitive data

### ISSUE THREAD

**Issue by subesokun** [terraform-providers/terraform-provider-azurerm#5730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: `0.12.20`
AzureRM: `1.41.0`

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Debug Output

```
~ resource "azurerm_kubernetes_cluster" "cluster" {
        ...redacted...
        kube_admin_config               = []
        kube_config                     = [
            {
                client_certificate     = "redacted"
                client_key             = "redacted"
                cluster_ca_certificate = "redacted"
                host                   = "redacted"
                password               = "redacted"
                username               = "redacted"
            },
        ]
        kube_config_raw                 = (sensitive value)
        kubernetes_version              = "1.15.7"
        ...redacted...
        service_principal {
            client_id     = "redacted"
            client_secret = (sensitive value)
        }
    }
```

### Expected Behavior

In case of in-place updates, sensitive data like the `kubecfg.client_key` gets redacted and is not visible in the logs.

### Actual Behavior

In case of in-place updates, sensitive data like the `kubecfg.client_key` gets printed in clear text into the logs.

### Steps to Reproduce

Change a property that causes an in-place update of the AKS cluster and run a `terraform plan`

**Comment by tombuildsstuff** [comment]
👋 

Thanks for opening this issue.

This issue needs to be fixed in the Terraform Plugin SDK, as such rather than tracking this issue in multiple places I'm going to close this issue in favour of the upstream issue. Once that's been fixed we'll update the version of the Plugin SDK being used and this should get resolved - as such [please subscribe to the upstream issue for updates](https://github.com/hashicorp/terraform-plugin-sdk/issues/201).

Thanks!
