### ISSUE TITLE
azurerm_virtual_machine_scale_set need ability to override default scale-in policy

### ISSUE THREAD

**Issue by jpveritone** [terraform-providers/terraform-provider-azurerm#5738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

We're using terraform v0.11.3 along with Azure terraform provider v1.41.0. 
We use https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html to create our VMSS. The problem is terraform is not giving option or way to change the VMSS default scale-in policy, Refer to https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-scale-in-policy.
As a result when we scale in it will remove the VM with highest ID, thus newer ones, whereas we want to remove older one which would be the policy named `OldestVM` I can do this via Azure CLI or fro Azure Portal but cannot find a way to do via terraform.
Are there any plans to fix this in terraform provider?

**Comment by ArcturusZhang** [comment]
I have already implemented this feature in this [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/5391).
But this feature only updates the 2.0 vmss resources, `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set`, the legacy vmss resource `azurerm_virtual_machine_scale_set` will not receive any further features.
