### ISSUE TITLE
Feature Request: Recovery Services Vaults

### ISSUE THREAD

**Issue by retheshnair** [terraform-providers/terraform-provider-azurerm#576]
Hi there,

### Terraform Version
0.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
- VM

Azure Recovery Services vaults  provisioning and attaching  VM to it missing

**Comment by tombuildsstuff** [comment]
👋 hey all

Just to let you know that the work for this is being tracked in #995 - we're currently blocked waiting on the Azure SDK upgrade (which is being tracked in #1006) - but we'll pick this up again once that's been merged :)

Thanks!

**Comment by tombuildsstuff** [comment]
hi @retheshnair 

Support for provisioning Recovery Service Vaults has been added in #995, which has just been merged and will be released in the next version of the AzureRM Provider. As such I'm going to close this issue for the moment.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @retheshnair 

Just to let you know that v1.4.0 of the Azure Provider has been released which includes support for this :)

Thanks!
