### ISSUE TITLE
Using azurerm_kusto_database_principal to add 'App' as user to database fails in provider

### ISSUE THREAD

**Issue by patrickbsf** [terraform-providers/terraform-provider-azurerm#5760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v1.43.0
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)

* azurerm_kusto_database_principal 

### Terraform Configuration Files

If it matters, the 'real' code pulls the values from module outputs, but for simplicity I'm showing synthetic variable names.
```hcl
resource "azurerm_kusto_database_principal" "sp_rights" {
  resource_group_name = var.resource_group_name
  cluster_name        = var.cluster.name
  database_name       = var.database.name

  role      = "User"
  type      = "App"
  client_id = var.service_principal_tenant_id
  object_id = var.service_principal_id
}

```

### Debug Output
azurerm_kusto_database_principal.sp_rights: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to azurerm_kusto_database_principal.sp_rights, provider
"registry.terraform.io/-/azurerm" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior

I'm trying to add a service principal 'app' as a user to a Kusto database.

### Actual Behavior

The permission actually gets applied, but the provider fails reading back the state, and the state never gets updated.
Re-running apply will try to apply the permission again, and always fail the same way.  

### Steps to Reproduce

1. `terraform apply`

See #4414

**Comment by neil-yechenwei** [comment]
@patrickbsf , it seems that I can add app as user to azurerm_kusto_database_principal successfully. Below is my tf config:
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "rg" {
  name     = "acctestRG-kusto-neil"
  location = "westus"
}

resource "azurerm_kusto_cluster" "cluster" {
  name                = "acctestkcneil"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  sku {
    name     = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }
}

resource "azurerm_kusto_database" "test" {
  name                = "acctestkd-neil"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  cluster_name        = azurerm_kusto_cluster.cluster.name
}

resource "azurerm_kusto_database_principal" "test" {
  resource_group_name = azurerm_resource_group.rg.name
  cluster_name        = azurerm_kusto_cluster.cluster.name
  database_name       = azurerm_kusto_database.test.name

  role      = "User"
  type      = "App"
  client_id = data.azurerm_client_config.current.tenant_id
  object_id = data.azurerm_client_config.current.client_id
}

**Comment by patrickbsf** [comment]
Interesting - once I switched the object_id to the 'right' id (I was using the 'id' of the service principal, not the application-id) then it stopped failing in the provider.  It seems like it should handle this better but it's working now at least.
