### ISSUE TITLE
Backend configuration with Service Principal (client secret)

### ISSUE THREAD

**Issue by gek0** [terraform-providers/terraform-provider-azurerm#5785]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform version: 0.12.20`
`AzureRM Provider version: terraform-provider-azurerm_v1.44.0_x4`

### Affected Resource(s)

* `backend "azurerm"`

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "my-resource-group"
    storage_account_name = "my-storage-account"
    container_name       = "my-container-name"
    key                  = "some-path/terraform.tfstate"
  }
}

provider "azurerm" {
  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
}

data "terraform_remote_state" "resource_group" {
  backend = "azurerm"
  config = {
    resource_group_name  = "my-resource-group"
    storage_account_name = "my-storage-account"
    container_name       = "my-container-name"
    key                  = "some-path/resource-group-state/terraform.tfstate"
  }
}

resource "azurerm_storage_account" "storage_account" {
  name                     = var.storage_account_name
  resource_group_name      = data.terraform_remote_state.resource_group.outputs.resource_group_info["name"]
  location                 = data.terraform_remote_state.resource_group.outputs.resource_group_info["location"]
  account_tier             = var.storage_account_tier
  account_replication_type = var.storage_account_replication_type
  enable_blob_encryption   = var.enable_blob_encryption
  tags                     = var.tags
}

resource "azurerm_storage_container" "storage_account_container" {
  name                  = var.storage_container_name
  storage_account_name  = azurerm_storage_account.storage_account.name
  container_access_type = var.storage_container_access
}

# terraform.tfvars.json 
{
  "tenant_id": "XXXXXXXXXXXXXX",
  "subscription_id": "XXXXXXXXXXXXXX5"
}

```

### Debug Output

https://pastebin.com/0xajf8M4

### Expected Behavior

Plan and apply successfully finish since the credentials are valid

### Actual Behavior

Error `Error building ARM Config` is thrown since the provider does not read variables present in .auto.tfvars.json files for the backend configuration.

### Steps to Reproduce

(any of these three are failing...)
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Important Factoids

This only works if I export `ARM_SUBSCRIPTION_ID` and `ARM_TENANT_ID` as environmental variables in the working shell. But this is a bit of inconvenience when working with CI/CD solutions such as Atlantis and with multiple subscriptions. We are setting subscription_id and tenant_id in variable files that are readable by provider {} configuration but not the backend {} one...

**Comment by tombuildsstuff** [comment]
hi @gek0 

Thanks for opening this issue.

Taking a look into this this appears to be an issue with Terraform Core not automatically loading variables from `*.tf.auto` files - as such this would need to be fixed in that repository. So that you can keep subscribed to that issue would you mind re-opening this issue on [the Terraform Core repository](https://github.com/hashicorp/terraform/issues) so that someone can take a look at this?

Thanks!
