### ISSUE TITLE
Custom image + plan block for VMSS (and VM)

### ISSUE THREAD

**Issue by AlessandroLascu** [terraform-providers/terraform-provider-azurerm#5789]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
provider.azurerm v1.44.0

### Affected Resource(s)

* `azurerm_azurerm_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_scale_set" "linux_compute_vmss" {

  name                = "${var.linux_vmss_info["prefix_name"]}${count.index}"
  location            = var.location
  resource_group_name = azurerm_resource_group.linux_compute.name

  count = var.linux_vmss_info["scale_set_count"]

  upgrade_policy_mode = var.linux_vmss_info["upgrade_policy_mode"]
  priority            = var.linux_vmss_info["priority"]
  eviction_policy     = var.linux_vmss_info["eviction_policy"]

  single_placement_group = false

  sku {
    name     = var.linux_vmss_info["sku_name"]
    tier     = var.linux_vmss_info["sku_tier"]
    capacity = var.linux_vmss_info["scale_set_instance_count"]
  }

  storage_profile_image_reference {
    id = data.azurerm_shared_image_version.linux_compute.id
  }

  storage_profile_os_disk {
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = var.linux_vmss_info["managed_disk_type"]
  }

  os_profile {
    computer_name_prefix = "${var.windows_vmss_info["instance_prefix_name"]}${count.index}" #"${var.linux_vmss_info["prefix_name"]}${count.index}"
    admin_username       = var.linux_vmss_info["local_admin_username"]
    admin_password       = data.azurerm_key_vault_secret.local_admin_password.value
  }

  os_profile_linux_config {
    disable_password_authentication = false

    ssh_keys {
      path     = "/home/${var.linux_vmss_info["local_admin_username"]}/.ssh/authorized_keys"
      key_data = data.azurerm_key_vault_secret.admin_public_key.value
    }
  }

  network_profile {
    name    = "Linux-Compute-Node-NIC"
    primary = true

    accelerated_networking = var.linux_vmss_info["accelerated_networking"]

    ip_configuration {
      name      = "IPConfiguration"
      primary   = true
      subnet_id = var.QA_env_linux_nodes_subnet.id
    }
  }

  # Block needed to deploy VMs with custom image starting from one with BYOS license
  # reference: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/byos#additional-information
  plan {
    name      = "rhel-lvm77"
    publisher = "redhat"
    product   = "rhel-byos"
  }

  tags = var.mandatory_tags
}
/hashicorp
```

### Expected Behavior

A VMSS with custom image (from Shared Image Version) and specifying a plan block should be created.
We require both of these configuration parameters in our scenario, described below:
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/byos#additional-information 

### Actual Behavior

The VMSS deployment fails with the follwing error:
Error: Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from a non-Marketplace image does not need Plan information. Please remove the Plan information from VM '/subscriptions/****************/resourceGroups/rg_name/providers/Microsoft.Compute/virtualMachineScaleSets/vssqh3clq0/virtualMachines/vssqh3clq0_0'

### Steps to Reproduce

Define a VMSS with custom image (from Shared Image Version), specifying also a plan block.

1. `terraform apply`

### References

I attach a zip file with both the Terraform definition of the VMSS that I use and the complete ARM Template that is generated upon deployment through the Azure CLI (showing that the configuration custom image + plan block, with the createOption set to FromImage, is supported).
[Code-Samples-Plan-And-Custom-Image.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/4214515/Code-Samples-Plan-And-Custom-Image.zip)

* #0000

**Comment by edwardwu-servian** [comment]
hit by the same issue `Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from Marketplace image requires Plan information in the request.`

**Comment by edwardwu-servian** [comment]
Upon digging into the resource code, a plan block with following syntax is actually supported. However, this is not reflected in documentation - https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html
```hcl
plan {
  name       = ""
  product   = ""
  publisher = ""
}
```

**Comment by tombuildsstuff** [comment]
👋 

At this point in time the older `azurerm_virtual_machine_scale_set` resource has been superseded by the `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources. Since the older `azurerm_virtual_machine_scale_set` resource has fallen out of sync from the behaviour of the Azure API, to avoid unintentionally breaking users relying on this behaviour the older resources are feature-frozen.

As this resource is feature-frozen to maintain compatibility, I'm going to close this issue for the moment - but I'd recommend instead checking out the `azurerm_linux_virtual_machine_scale_set` resource, which better represents how the Azure API behaves for this resource.

Thanks!
