### ISSUE TITLE
Feature Request: Add support for new Preview features (LB Standard, Public IP Standard, Availability Zones, High Availability Ports)

### ISSUE THREAD

**Issue by justaugustus** [terraform-providers/terraform-provider-azurerm#579]
This is a bucket issue for adding support for the following upcoming Azure Preview features:
- [x] Azure LB / Public IP Standard (https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-standard-overview): https://github.com/terraform-providers/terraform-provider-azurerm/pull/665
- [ ] Availability Zones (https://docs.microsoft.com/en-us/azure/availability-zones/az-overview)
- [ ] High Availability Ports (https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ha-ports-overview)
- [ ] Remove Preview notices on associated docs

We (CoreOS) would like to add support for this feature set in Tectonic, but it will be dependent on formal upstream support for the features in the [Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) and the [azurerm TF provider](https://github.com/terraform-providers/terraform-provider-azurerm).

x-ref: coreos/tectonic-installer#2443

Upstream refs:
* Azure/azure-sdk-for-go#871

cc: @robszumski / @metral

**Comment by tombuildsstuff** [comment]
hey @justaugustus 

Taking another look through this issue it appears the remaining feature requests are duplicates of #370 (for Availability Zones) and #372 (High Availability Ports) - as such I'm going to close this combined issue in favour of the specific ones - just so it's easier to track, I hope you don't mind!

Thanks!

**Comment by justaugustus** [comment]
Sounds good, @tombuildsstuff. Thanks for the heads-up!
