### ISSUE TITLE
Support for Bot Framework's Direct Line Channel

### ISSUE THREAD

**Issue by chris-redekop** [terraform-providers/terraform-provider-azurerm#5822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please create a `bot_channel` resource for the Direct Line channel.  Here is a description of the Direct Line channel, from https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline?view=azure-bot-service-4.0

> The Bot Framework Direct Line channel is an easy way to integrate your bot into your mobile app, webpage, or other application. Direct Line is available in three forms:
    Direct Line service – a global, robust service for most developers
    Direct Line App Service Extensions – dedicated Direct Line functionality for security and performance (available in public preview)
    Direct Line Speech – optimized for high-performance speech (GA)
You can choose which offering of Direct Line is best for you by evaluating the features each offers and the needs of your solution. Over time these offerings will be simplified.

### New or Affected Resource(s)

* azurerm_bot_channel_direct_line

### Potential Terraform Configuration

The configuration should include the enhanced-security options such as trusted domains.

### References

* [About Direct Line](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline?view=azure-bot-service-4.0) provides background info on Direct-Line channels.
* [bot_channel_email](https://www.terraform.io/docs/providers/azurerm/r/bot_channel_email.html) provides an example of a Terraform resource for a different Bot-Framework channel.

* #0000

**Comment by ZsoltPath** [comment]
Seems like you're banging on open doors: https://github.com/terraform-providers/terraform-provider-azurerm/pull/5445

**Comment by chris-redekop** [comment]
Thanks for the link!  I'll close this issue then.
