### ISSUE TITLE
Getting Error: Cycle while creating azure VM and NIC using existing resources

### ISSUE THREAD

**Issue by vijayraje23** [terraform-providers/terraform-provider-azurerm#5828]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---
I have existing resources like Resource group, NSG,Storage account, subnet and vnet, while creating azure VM and NIC getting below error or validate and plan.

[root@terraformvm terraform]# terraform validate
Error: Cycle: azurerm_network_interface.nic, azurerm_virtual_machine.vm

[root@terraformvm terraform]# cat main.tf
#Existing Resource Group
resource "azurerm_resource_group" "rg" {
  name     = "TerraformDemo-RG"
  location = "EAST US2"
}

#Existing virtual network
resource "azurerm_virtual_network" "vnet" {
  name = "TerraformDemo-vnet"
#  address_space       = ["10.0.0.0/16"]
#  location            = "eastus2"
  resource_group_name = azurerm_resource_group.rg.name
}

#Existing subnet
resource "azurerm_subnet" "snet" {
  name                 = "TerraformDemo-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = "TerraformDemo-vnet"
#  address_prefix       = "10.0.1.0/24"
}

#Existing Network Security Group and rule
resource "azurerm_network_security_group" "nsg" {
  name                = "TerraformDemo-nsg"
  location            = "eastus2"
  resource_group_name = azurerm_resource_group.rg.name
}

#Create virtual machine
resource "azurerm_virtual_machine" "vm" {
    name                  = "TerraformDemo-vm1"
    location              = "eastus2"
    resource_group_name   = azurerm_resource_group.rg.name
    network_interface_ids = [azurerm_network_interface.nic.id]
    vm_size               = "Standard_B1ms"

    storage_os_disk {
        name              = "myOsDisk"
        caching           = "ReadWrite"
        create_option     = "FromImage"
        managed_disk_type = "Standard_LRS"
    }

storage_image_reference {
    id = data.azurerm_image.custom.id
  }

os_profile {
    computer_name  = "TerraformDemo-vm1"
    admin_username = "adminuser"
    admin_password = "Password$12"
    }

os_profile_linux_config {
    disable_password_authentication = false
   }

boot_diagnostics {
    enabled = "true"
    storage_uri = azurerm_storage_account.storageaccount.primary_blob_endpoint
    }
}

# Create public IPs
resource "azurerm_public_ip" "pip" {
    name                         = "myPublicIP"
    location                     = "eastus2"
    resource_group_name          = azurerm_resource_group.rg.name
    allocation_method            = "Dynamic"

    tags = {
        environment = "Terraform Demo"
    }
}

# Create network interface
resource "azurerm_network_interface" "nic" {
    name                      = azurerm_virtual_machine.vm.name-nic
    location                  = "eastus2"
    resource_group_name       = azurerm_resource_group.rg.name
    network_security_group_id = azurerm_network_security_group.nsg.id

    ip_configuration {
        name                          = azurerm_virtual_machine.vm.name-nic-config
        subnet_id                     = azurerm_subnet.snet.id
        private_ip_address_allocation = "Dynamic"
        public_ip_address_id          = azurerm_public_ip.pip.id
    }

    tags = {
        environment = "Terraform Demo"
    }
}

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @vijayraje23 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
