### ISSUE TITLE
Support for trafficAnalyticsInterval in azurerm_network_watcher_flow_log

### ISSUE THREAD

**Issue by joedoss** [terraform-providers/terraform-provider-azurerm#5830]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

traffic_analytics inside azurerm_network_watcher_flow_log currently defaults to a "traffic analytics processing interval" of 1 hour.  The Azure portal allows setting this value to either 1 hour or 10 minutes.

The ARM template includes a parameter (trafficAnalyticsInterval) to set "The interval in minutes which would decide how frequently TA service should do flow analytics"
https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-11-01/networkwatchers/flowlogs#TrafficAnalyticsConfigurationProperties

It would be useful to add this setting to the terraform provider.

### New or Affected Resource(s)

affected resource: azurerm_network_watcher_flow_log

### Potential Terraform Configuration
```
resource "azurerm_network_watcher_flow_log" "ExampleFlowlog" {
  network_watcher_name = data.azurerm_network_watcher.networkwatcher.name
  resource_group_name  = data.azurerm_resource_group.networkwatcherrg.name

  network_security_group_id = azurerm_network_security_group.ExampleNSG.id
  storage_account_id        = azurerm_storage_account.nsgflowlogstorage.id
  enabled                   = true
  version                   = 2

  retention_policy {
    enabled = true
    days    = 14
  }

  traffic_analytics {
    enabled               = true
   trafficAnalyticsInterval = "10"
    workspace_id          = azurerm_log_analytics_workspace.hub-loganalyticsworkspace.workspace_id
    workspace_region      = azurerm_log_analytics_workspace.hub-loganalyticsworkspace.location
    workspace_resource_id = azurerm_log_analytics_workspace.hub-loganalyticsworkspace.id
  }
}
```

### References
https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-11-01/networkwatchers/flowlogs#TrafficAnalyticsConfigurationProperties

**Comment by katbyte** [comment]
closed by #5851
