### ISSUE TITLE
azurerm_storage_account default account_kind should be StorageV2 instead of Storage

### ISSUE THREAD

**Issue by juanjojulian** [terraform-providers/terraform-provider-azurerm#5836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**azurerm_storage_account** default account_kind should be StorageV2 instead of Storage (which pints to version 1). 

According to Microsoft documentation the recommended kind is now version 2, in fact version 1 will be deprecated soon:

> General-purpose v2 accounts: Basic storage account type for blobs, files, queues, and tables. Recommended for most scenarios using Azure Storage.
General-purpose v1 accounts: Legacy account type for blobs, files, queues, and tables. Use general-purpose v2 accounts instead when possible.

### New or Affected Resource(s)

* azurerm_storage_account

### References

* https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview

**Comment by StefanSchoof** [comment]
The az cli had changed recently with the 2.1 version: https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#storage
