### ISSUE TITLE
Feature Request: Support for Application Insights billing & pricing

### ISSUE THREAD

**Issue by mikegore1000** [terraform-providers/terraform-provider-azurerm#584]
### Terraform Version
Terraform v0.11.0
+ provider.azurevm v0.3.3

### Affected Resource(s)
- azurerm_application_insights

### Expected Behavior
It would be great if we could create a "microsoft.insights/components/CurrentBillingFeatures" resource so we can set billing features, data caps etc.

At present we need to work around this by configuring via an "azurerm_template_deployment" resource.

**Comment by evertonmc** [comment]
* [go for it](https://github.com/Azure/azure-sdk-for-go/blob/master/services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go)

* [model](https://github.com/Azure/azure-sdk-for-go/blob/master/services/appinsights/mgmt/2015-05-01/insights/models.go#L471-L493)

* [api specs](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentFeaturesAndPricing_API.json#L37)
