### ISSUE TITLE
Using Azure Vnet Peerings across subscriptions - Terraform

### ISSUE THREAD

**Issue by roshanp85** [terraform-providers/terraform-provider-azurerm#5843]
I am using the below code to peer my created vnet with an existing Vnet in a separate subscription.

provider "azurerm" {
alias = "core"
subscription_id = "REMOTESUBID"
tenant_id = "CurrentTenantID"
client_id = "ClientIDConstant"
client_secret = "ClientIDConstant"
}

data "azurerm_virtual_network" "remotevnet" {
provider = "azurerm.core"
name = "co-np-eastus-core1-vnet"
resource_group_name = "co-np-eastus-core1-rg"
}

module "applicationrg"
{
  source = "../modules/resource_group"
  resource_group_name = "${var.applicationrg_name}"  
  resource_group_location = "${var.application_rg_location}"

  tags = "${var.tags}"
}
module "applicationvnet"{
    source="../modules/virtual_network"
    virtual_network_name="${var.virtual_network_name}"
    resource_group_location = "${module.applicationrg.resource_group_location}"
    resource_group_name ="${module.applicationrg.resource_group_name}"
    address_space       = "${var.address_space}"
    dns_server       = "${var.dns_server}"
    tags                = "${var.tags}"
}

resource "azurerm_virtual_network_peering" "CreatedVnetToRemoteVnet" {
 name                        = "CreatedVnettoRemoteVnet"
 virtual_network_name         = "${module.applicationvnet.virtual_network_name}"
 resource_group_name          = "${module.applicationrg.resource_group_name}"
 remote_virtual_network_id    = "${data.azurerm_virtual_network.remotevnet.id}"
 allow_virtual_network_access = true
 allow_forwarded_traffic      = true
}

resource "azurerm_virtual_network_peering" "RemoteVnetToCreatedVnet" {
 name                        = "RemoteVnettoCreatedVnet"
 virtual_network_name         = "${data.azurerm_virtual_network.corevnet.name}"
 resource_group_name          = "${data.azurerm_virtual_network.corevnet.resource_group_name}"
 remote_virtual_network_id    = "/subscriptions/${data.azurerm_subscription.current.subscription_id}/resourceGroups/${module.applicationrg.resource_group_name}/providers/Microsoft.Network/virtualNetworks/${module.applicationvnet.virtual_network_name}"
 allow_virtual_network_access = true
 allow_forwarded_traffic      = true
}

I'm getting the error below as:Error: Error refreshing state: 1 error occurred:
        * provider.azurerm: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status  #1

Issue is related to #1253 (https://github.com/terraform-providers/terraform-provider-azurerm/issues/1253)

I'm using the same Service principal, which has contributor access to both the subscription. Kindly help. I am using the below versions.

terraform {
  required_version = "= 0.11.14"
}

provider "azurerm" {
  version = "= 1.44.0"
}

provider "null" {
  version = "= 2.1.1"
}

provider "template" {
  version = "= 2.1.1"
}

**Comment by roshanp85** [comment]
Current state is I'm able to see the resourceGroup and VirtualNetwork Details in the terraform state file which is correct. But while interpolating as "data.azurerm_resource_group.rgname.name", in azurerm_virtual_network_peering resource, it always gives me the error as : 

azurerm_virtual_network_peering.coretovnet: network.VirtualNetworkPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'co-np-eastus-core1-rg' could not be found." The RG-not-found is over the resource data.azurerm_resource_group.

The SPN has contributor access to both the subscriptions. Kindly help

**Comment by tombuildsstuff** [comment]
hi @roshanp85 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
