### ISSUE TITLE
Support for changes in load balancer profile AKS after creation

### ISSUE THREAD

**Issue by aristosvo** [terraform-providers/terraform-provider-azurerm#5846]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When the `load_balancer_profile` settings for `service/kubernetes-cluster` are all computed, changing (for example) from managed IPs to provided outbound IP addresses is not possible with in TerraForm after creation of your cluster.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

Example initial config:
```hcl
provider "azurerm" {
}

resource "azurerm_resource_group" "rg" {
  name     = "aks-rg"
  location = "West Europe"
}


resource "azurerm_public_ip" "outbound" {
  name                = "aks-outbound-pip"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  allocation_method   = "Static"
  sku = "Standard"
}

resource "azurerm_kubernetes_cluster" "aks" {
  location            = azurerm_resource_group.rg.location
  name                = "aks"
  resource_group_name = azurerm_resource_group.rg.name
  dns_prefix = "tf-test-loadbalancer-profile"
  kubernetes_version  = "1.15.7"
  role_based_access_control {
    enabled = true
  }
  
  default_node_pool {
    availability_zones    = []
    enable_auto_scaling   = false
    enable_node_public_ip = false
    max_pods              = 110
    node_count            = 1
    name                  = "nodepool1"
    os_disk_size_gb       = 100
    type                  = "VirtualMachineScaleSets"
    vm_size               = "Standard_DS2_v2"
    node_taints           = []
  }

  service_principal {
    client_id     = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    client_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }



  network_profile {
    load_balancer_sku  = "Standard"
    load_balancer_profile {
         managed_outbound_ip_count = 2
    }
    dns_service_ip     = "10.0.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
    network_plugin     = "kubenet"
    pod_cidr           = "10.244.0.0/16"
    service_cidr       = "10.0.0.0/16"
  }
}
```
Example updated config:
```hcl
provider "azurerm" {
}

resource "azurerm_resource_group" "rg" {
  name     = "aks-rg"
  location = "West Europe"
}


resource "azurerm_public_ip" "outbound" {
  name                = "aks-outbound-pip"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  allocation_method   = "Static"
  sku = "Standard"
}

resource "azurerm_kubernetes_cluster" "aks" {
  location            = azurerm_resource_group.rg.location
  name                = "aks"
  resource_group_name = azurerm_resource_group.rg.name
  dns_prefix = "tf-test-loadbalancer-profile"
  kubernetes_version  = "1.15.7"
  role_based_access_control {
    enabled = true
  }
  
  default_node_pool {
    availability_zones    = []
    enable_auto_scaling   = false
    enable_node_public_ip = false
    max_pods              = 110
    node_count            = 1
    name                  = "nodepool1"
    os_disk_size_gb       = 100
    type                  = "VirtualMachineScaleSets"
    vm_size               = "Standard_DS2_v2"
    node_taints           = []
  }

  service_principal {
    client_id     = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    client_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }



  network_profile {
    load_balancer_sku  = "Standard"
    load_balancer_profile {
        outbound_ip_address_ids = [ azurerm_public_ip.outbound.id ]
    }
    dns_service_ip     = "10.0.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
    network_plugin     = "kubenet"
    pod_cidr           = "10.244.0.0/16"
    service_cidr       = "10.0.0.0/16"
  }
}
```

**Comment by jluk** [comment]
There a few additional load balancer profile properties that are available to be supported as well.

* managedOutboundIps (mentioned above) (https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#scale-the-number-of-managed-public-ips)
* idleTimeoutInMinutes / allocatedOutboundPorts (SNAT handling) (https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-outbound-ports-and-idle-timeout)
* outboundIpPrefixes / outboundIps (BYO IP scenario) (https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#provide-your-own-public-ips-or-prefixes-for-egress)

The AKS swagger can be found here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-02-01/managedClusters.json#L1730

cc @tombuildsstuff here to help w questions if needed

**Comment by aristosvo** [comment]
@jluk `managedOutboundIps`, `outboundIpPrefixes` and `outboundIps` are already supported, the only thing this issue is focused on is to make this configuration changeable after cluster creation with TerraForm.

To add `idleTimeoutInMinutes / allocatedOutboundPorts (SNAT handling)` you'd probably need to raise another issue

**Comment by jluk** [comment]
Thanks for clarifying, ack will move to separate issues.
