### ISSUE TITLE
Logic App support outgoing ip addresses in the resources

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#5849]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for `Runtime outgoing IP addresses` and `Access endpoint IP addresses` on `azurerm_logic_app_workflow` resource.

### New or Affected Resource(s)

* azurerm_logic_app_workflow

### Potential Terraform Configuration

```hcl
azurerm_logic_app_workflow.logic_app_workflow.*.runtime_outgoing_ip_addresses
azurerm_logic_app_workflow.logic_app_workflow.*.access_endpoint_ip_addresses
```

**Comment by magodo** [comment]
I'll look into this.

**Comment by magodo** [comment]
@rohrerb 

Those two properties are not supported in current go sdk, I have submitted another [issue](https://github.com/Azure/azure-sdk-for-go/issues/7499) in azure go sdk repo to ask for a version update. After which, we can come back to implement what you need.
