### ISSUE TITLE
Support for Azure Media Services Configuration Options

### ISSUE THREAD

**Issue by dlm69** [terraform-providers/terraform-provider-azurerm#5859]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm relatively new to Terraform. I have seen the resource for azurerm_media_services_account but i cannot find any examples of how to configure more options within. For example how do you connect up a CDN profile/endpoint? Setup Live Streaming options. Is there an example for this? Or is there another way of doing this without resorting to an arm template resource? 

### New or Affected Resource(s)

azurerm_media_services_account

### References

https://www.terraform.io/docs/providers/azurerm/r/media_services_account.html

**Comment by jcanizalez** [comment]
I think that #9537 and #9457 resolves this issue too

**Comment by tombuildsstuff** [comment]
👋 

Closing this in favour of #6597 - since #9457 appears to have fixed the other items. If there's something else your looking for here then [please open a new feature request](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D)

Thanks!
