### ISSUE TITLE
azurerm_netapp_volume does not allow smb volumes to be created

### ISSUE THREAD

**Issue by jknash** [terraform-providers/terraform-provider-azurerm#5871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When creating a new volume, there is no option to create an SMB volume.  The volume always defaults to NFSv3 and it cannot be changed.  I think we need a protocol option on the azurerm_netapp_volume resource.

* azurerm_netapp_volume

### Potential Terraform Configuration

```hcl
resource "azurerm_netapp_volume" "example" {
  name                = "example-netappvolume"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  account_name     = azurerm_netapp_account.example.name
  pool_name            = azurerm_netapp_pool.example.name
  volume_path        = "my-unique-file-path"
  service_level        = "Premium"
  subnet_id             = azurerm_subnet.example.id
  **protocol                = smb**
  storage_quota_in_gb = 100
}

```

### References

* #0000

**Comment by seb-brack** [comment]
To accommodate potential future enhancements of ANF I suggest adding a List(String) instead of a simple String to the configuration:

`protocols = ["smb"]`

**Comment by paulomarquesc** [comment]
@sed-brack, yes, you're correct, this property is being exposed in the PR you just referenced.

**Comment by jknash** [comment]
> @seb-brack, yes, you're correct, this property is being exposed in the PR you just referenced.

@paulomarquesc 

PR 5485 looks like it references NFS though.  Can that same property be used to specify that it should be an SMB volume?

**Comment by paulomarquesc** [comment]
It is for all available protocols, CIFS, NFSv3 and NFSv4.1.

**Comment by paulomarquesc** [comment]
hi @jknash and @seb-brack just an update here, the PR #5485 that enables this among NFSv4,1 support got merged.

**Comment by paulomarquesc** [comment]
@tracypholmes, is this closed when the fix is released on v2.1 or can it be closed as soon as it got merged?

**Comment by tbugfinder** [comment]
Recently ANF was extended to create multi-protocol volumes.
https://docs.microsoft.com/en-us/azure/azure-netapp-files/create-volumes-dual-protocol

This should be added, too. `protocols` mustn't be filled with a single value then or a new value should be added.

**Comment by AnotherCorto** [comment]
Hi, I would like to see this implememented as well as the multi protocol volumes.

**Comment by paulomarquesc** [comment]
This is already supported since the time we enabled an array as protocol types, worth it to notice that the supported dual protocol scenario is CIFS+NFSv3.

I'll update the documentation to point that out and provide a sample on how to do it, for now here is the snippet that I used to test it:

```hcl
resource "azurerm_netapp_volume" "example" {
  lifecycle {
    prevent_destroy = true
  }

  name                = "${var.prefix}-netappvolume"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  account_name        = azurerm_netapp_account.example.name
  pool_name           = azurerm_netapp_pool.example.name
  volume_path         = "${var.prefix}-netappvolume"
  service_level       = "Standard"
  protocols           = ["CIFS","NFSv3"]
  subnet_id           = var.subnet_id
  storage_quota_in_gb = 100

  export_policy_rule {
    rule_index = 1
    allowed_clients = ["0.0.0.0/0"]
    cifs_enabled = true
    nfsv3_enabled = true
    nfsv4_enabled = false
    unix_read_write = true
  }
}
```

**Comment by paulomarquesc** [comment]
@katbyte , can you please close this one as well?
