### ISSUE TITLE
Support for iot hub message-enrichment

### ISSUE THREAD

**Issue by mfilotto** [terraform-providers/terraform-provider-azurerm#5872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for iot hub message enrichement.
This feature is available in azure cli: https://docs.microsoft.com/en-us/cli/azure/iot/hub/message-enrichment?view=azure-cli-latest

### New or Affected Resource(s)

* azurerm_iothub

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by chrome050** [comment]
Up!

**Comment by alex-3sr** [comment]
Hi,

It could be very nice to get this feature, really missing :o 

Thx
Alex

**Comment by kensykora** [comment]
Potential Terraform Configuration:

```hcl

resource "azurerm_iothub_enrichment" "events" {
  name = "legacyId"
  resource_group_name = azurerm_iothub.hub.resource_group_name
  iothub_name         = azurerm_iothub.hub.name

  value = "$twin.tags.legacyId"

  endpoint_names = ["events"] # builtin endpoint
}

```

**Comment by royto** [comment]
Hello,

I really need this functionality. my [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/9239 )
Could it be part of the next release?

Thanks
