### ISSUE TITLE
Version 2.0.0 shows unexpected missing features error when provider alias is provided

### ISSUE THREAD

**Issue by kendaleiv** [terraform-providers/terraform-provider-azurerm#5885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Provider version: 2.0.0
Terraform version: 0.12.21

### Terraform Configuration Files

```hcl
provider "azurerm" {
  alias = "test"
  version = "=2.0.0"
  features {}
}

resource "azurerm_app_service_plan" "app_service_plan_east_test" {
  name                = "test-app-service-east"
  location            = "eastus"
  resource_group_name = "my-test-resource-group"

  sku {
    tier = "Standard"
    size = "S1"
  }
}
```

### Steps to Reproduce

Version 2.0.0 throws missing features error when alias is provided.

Paste above 

1. `terraform init`
1. `terraform plan`

```
Error: "features": required field is not set
```

**Comment by jackofallops** [comment]
Hi @kendaleiv 

Thanks for opening this issue.

Using the alias field creates a non-default provider config. Without a default (non-aliased) config, and the alias not being used by any resource this is the expected behaviour.   Adding `provider = azurerm.test` to your resource example above would allow the init / plan to succeed.

**Comment by lexton** [comment]
Our variation was that the upgrade alias generated the output:
```
Error: "features": required field is not set
Error: "features": required field is not set
```

Even after fixing the one block we had:
```
provider "azurerm" {
  version         = "~>2.0.0"
  alias           = "other_sub"
  subscription_id = var.subscription_id
  features {}
}
```

The `alias` means that you need to create an additional default block since the block isn't automatically created. This is hard to spot since it wasn't required originally.

```
provider "azurerm" {
  version  = "~>2.0.0"
  features {}
}
```
