### ISSUE TITLE
Support for Disabling Health Probes in FrontDoor

### ISSUE THREAD

**Issue by kensykora** [terraform-providers/terraform-provider-azurerm#5903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the Azure FrontDoor product supports having health probes, and being able to disable those health probes. Currently the Terraform resource type for FrontDoor requires that health probes are enabled. Regardless of whether or not it's a good idea to have health probes or not, the front door resource type should support being able to turn them off since it is supported by the FrontDoor product.

![2020-02-25 15_48_49-](https://user-images.githubusercontent.com/64756/75290782-9c9f4680-57e6-11ea-9f52-bab2320d031c.png)

Per azurerm provider frontdoor resource documentation: https://www.terraform.io/docs/providers/azurerm/r/frontdoor.html#backend_pool_health_probe

> backend_pool_health_probe - (Required) A backend_pool_health_probe block as defined below.
>
> The backend_pool_health_probe block supports the following:
>
>    name - (Required) Specifies the name of the Health Probe.

### New or Affected Resource(s)

* azurerm_frontdoor

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "FrontDoorExampleResourceGroup"
  location = "EastUS2"
}

resource "azurerm_frontdoor" "example" {
  name                                         = "example-FrontDoor"
  location                                     = azurerm_resource_group.example.location
  resource_group_name                          = azurerm_resource_group.example.name
  enforce_backend_pools_certificate_name_check = false

  routing_rule {
    name               = "exampleRoutingRule1"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["exampleFrontendEndpoint1"]
    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "exampleBackendBing"
    }
  }

  backend_pool_load_balancing {
    name = "exampleLoadBalancingSettings1"
  }

# # Do not require health probe type
#
#  backend_pool_health_probe {
#    name = "exampleHealthProbeSetting1"
#  }

  backend_pool {
    name = "exampleBackendBing"
    backend {
      host_header = "www.bing.com"
      address     = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name  = "exampleLoadBalancingSettings1"

    # health_probe_name  = "exampleHealthProbeSetting1" # Do not require this

    # new property
    health_probe_enabled = false
  }

  frontend_endpoint {
    name                              = "exampleFrontendEndpoint1"
    host_name                         = "example-FrontDoor.azurefd.net"
    custom_https_provisioning_enabled = false
  }
}
```

### References

* Tangentially related to #5499

**Comment by WodansSon** [comment]
@kensykora it looks like in the new API they have now exposed a new attribute in the `HealthProbeSettingsProperties` called `EnabledState`. I will go ahead and expose that attribute in the Terraform resource so you can disable the Health Probe if you'd like, but keep in mind that `Health probes can only be disabled if there is a single enabled backend in a single enabled backend pool.`
