### ISSUE TITLE
New resource 'server endpoint' in 'storage sync' Question

### ISSUE THREAD

**Issue by yupwei68** [terraform-providers/terraform-provider-azurerm#5925]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.
---
Hi @tombuildsstuff @katbyte , I'm now working on a new resource "server endpoint" in subcategory "storage sync". It's a resource that synchronize a specific folder on a VM.
I have some design problems that might require your suggestions.

The steps to create a server_endpoint is: 
1. create a storage sync service, 
2. create a VM, 
3. set some configurations, download an agent .msi and install the agent, enter the storage sync service and subscription information to associate the vm with the storage sync service.
Refer: https://docs.microsoft.com/en-us/azure/storage/files/storage-sync-files-deployment-guide?tabs=azure-portal#prepare-windows-server-to-use-with-azure-file-sync
https://docs.microsoft.com/en-us/azure/storage/files/storage-sync-files-deployment-guide?tabs=azure-portal#install-the-azure-file-sync-agent

 In their way, a new resource "registered server" will be created under this storage sync service. 
![image](https://user-images.githubusercontent.com/56525716/75406767-4e0bbc80-594c-11ea-94c4-a29e13e7ab07.png)

4. create the server endpoint with the server Id of the registered server and the storage sync service.

For the step 3,  the creation of "registered server" is unimplementable in Golang. So I have written a powershell script the do all these thing (set configurations, install agent.msi, create the registered server). And I have created a "virtual_machine_extension" to run the script. 

So currently, I have two concerns:
1. Since the creation of the "registered server" is written in script in "virtual_machine_extension", we could not get the registeredServer.serverId. We could only get all the registered servers under the storage sync services, match the registeredServer.FriendlyName with VM.Osprofile.computer_name(There is no other matching fields). If there are several vm with the same computer_name, it could be wrong.

2. The deletion of the "registered server". First option, set a computed field "server_id" in "server endpoint". While deleting the server endpoint, delete the registered server. Second option, delete all these registered servers while deleting the storage sync service.

Do you think the solution is acceptable? And would you like to spare some time to give some suggestions?

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @yupwei68 

Thanks for opening this issue.

Based on the information above it appears this resource doesn't make sense in Terraform since this is better achieved using configuration management tooling - as such I'm going to close this issue for the moment.

Thanks!
