### ISSUE TITLE
DNS records tags are not saved properly

### ISSUE THREAD

**Issue by jaygridley** [terraform-providers/terraform-provider-azurerm#5926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `terraform 0.12.21`
* `azurerm 1.44.0`

### Affected Resource(s)

* `azurerm_dns_a_record`
* `azurerm_dns_txt_record`
* `azurerm_dns_cname_record`

### Terraform Configuration Files

```hcl
locals {
 tags = {
    "Application Name" = "ABC"
    "Project ID"       = "ABC"
    "Environment"      = "test"
    "Support"          = "unassigned"
    "Managed By"       = "Terraform"
  }
}
resource "azurerm_dns_a_record" "tooling_public_ip" {
  name                = "*"
  zone_name           = data.azurerm_dns_zone.tooling.name
  resource_group_name = data.azurerm_dns_zone.tooling.resource_group_name
  ttl                 = 3600

  records = [
    var.hub_firewall_public_ip
  ]

  tags = local.tags
}
```

### Expected Behavior

Terraform plan and apply was successful. All tags should be written to the resource.

### Actual Behavior

Only some tags are saved to the resource. It seems, that only tags without space in key are saved - I can see only `Environment` and `Support` in Portal.

When adding tags via Portal, tags with space in key are saved correctly.

Running `terrafom plan` and `apply` again tries to add missing tags again, but without any change to the actual resource in Azure.

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`
1. see resource metadata

**Comment by njuCZ** [comment]
It seems it's a bug of azure dns record service.
adding tags via Portal, it seems tags with space in key are saved but actually not. You can refresh the page and see the tags are restored

**Comment by tombuildsstuff** [comment]
👋 

Since this is a bug in the Azure API rather than Terraform (and as such would need to be fixed there out of band) I'm going to close this in favour of [the upstream API issue](https://github.com/Azure/azure-rest-api-specs/issues/8555) for the moment

Thanks!
