### ISSUE TITLE
Not able to create VM in existing resource group with existing network with version 2.0.0

### ISSUE THREAD

**Issue by vivek99singh** [terraform-providers/terraform-provider-azurerm#5938]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.21
+ provider.azurerm v2.0.0

### Affected Resource(s)

* `azurerm_virtual_machine_extension`
* `data "azurerm_subnet"`
ip_configuration.0.subnet_id
* ` azurerm_network_interface.private_nic.id`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
##Step to refer terraform state files
terraform {
  backend "azurerm" {
  }
}


##Step to refer the existing resource group
data "azurerm_resource_group" "test" {
    name = "HWE-HC-LCPIPELINEIMAGES-WEST-EUROPE-RG"
}

## Step to refer the network resources from existing resource group 

data "azurerm_resource_group" "test1" {
    name = "HWE-NETWORKS-WEST-EUROPE-RG"

}

## Locate the existing custom/golden image of LAS,EAS,THinkEHR..
data "azurerm_image" "search" {
  name                = "HWE-HC-IIS-image-20191010-v1"
  resource_group_name = "HWE-HC-LCPIPELINEIMAGES-WEST-EUROPE-RG"
}

output "image_id1" {
  value = "/subscriptions/4cbcff46-75ea-420f-bef3-bdea0e39fe9d/resourceGroups/HWE-HC-LCPIPELINEIMAGES-WEST-EUROPE-RG/providers/Microsoft.Compute/images/HWE-HC-IIS-image-20191010-v1"
}


##refer to the existing VNET and Subnet
data "azurerm_virtual_network" "sourcevnet" {
  name                = "HWE-TECA-WEST-EUROPE"
  resource_group_name = "data.azurerm_resource_group.test1.name"
}

data "azurerm_subnet" "workload" {
  name                 = "hwe-teca-workloads2"
  resource_group_name  = "data.azurerm_resource_group.test1.name"
  virtual_network_name = "data.azurerm_virtual_network.sourcevnet.name"
}

resource "azurerm_network_interface" "private_nic" {
  name ="nic-test"
  location = "var.location"
  resource_group_name = "data.azurerm_resource_group.test.name"
  
  ip_configuration {
    name = "privatenic"
    subnet_id = "azurerm_subnet.workload.id"
    private_ip_address_allocation = "dynamic"

  }

}

##Step to create VM 1
resource "azurerm_virtual_machine" "VM1" {
  name = "var.vm_name"
  location              = "var.location"
  resource_group_name   = "data.azurerm_resource_group.test.name"
  network_interface_ids = "azurerm_network_interface.private_nic.id"
  vm_size               = "Standard_D2s_v3"

#This will delete the OS disk automatically when deleting the VM
  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true

storage_image_reference {
    id = "data.azurerm_image.search.id"
  }

  storage_os_disk {
    name              = "OSDISKTESTVM"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "var.vm_name"
    admin_username = "var.vm_username"
    admin_password = "var.vm_password"
  }

  os_profile_windows_config {
    provision_vm_agent        = true
    enable_automatic_upgrades = true
    }

}

resource "azurerm_virtual_machine_extension" "MYADJOINEDVMADDE1" {
  name                 = "MYADJOINEDVMADDE1"
  virtual_machine_id   = "azurerm_virtual_machine.VM1.id"
  publisher            = "Microsoft.Compute"
  type                 = "JsonADDomainExtension"
  type_handler_version = "1.3"

  # What the settings mean: https://docs.microsoft.com/en-us/windows/desktop/api/lmjoin/nf-lmjoin-netjoindomain

  settings = <<SETTINGS
    {
        "Name": "domain-name",
        "OUPath": "",
        "User": "domainadminuser",
        "Restart": "true",
        "Options": "3"
    }
SETTINGS
  protected_settings = <<PROTECTED_SETTINGS
    {
      "Password": "<somegarbagevalue>"
    }
  PROTECTED_SETTINGS
  depends_on = [azurerm_virtual_machine.VM1]
}

# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behavior

Error: Can not parse "ip_configuration.0.subnet_id" as a resource id: Cannot parse Azure ID: parse azurerm_subnet.workload.id: invalid URI for request

  on customer.tf line 43, in resource "azurerm_network_interface" "private_nic":
  43: resource "azurerm_network_interface" "private_nic" {

Error: Incorrect attribute value type

  on customer.tf line 62, in resource "azurerm_virtual_machine" "VM1":
  62:   network_interface_ids = "azurerm_network_interface.private_nic.id"

Inappropriate value for attribute "network_interface_ids": list of string
required.

Releasing state lock. This may take a few moments...

### Steps to Reproduce

1. `terraform plan -var-file=values.tfvars`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @vivek99singh 

Thanks for opening this issue

Taking a look at the Terraform Configuration posted above it appears the interpolation syntax being used is incorrect, so this is being treated as a string literal rather than an interpolation - for example:

```
  location = "var.location"
```

rather than:

```
  location = var.location
```

whilst it's still possible to use the older interpolation syntax (example below):

```
  location = "${var.location}"
```

.. you can omit the quote marks and Terraform will instead treat this as an interpolation.

As such you should be able to update these fields (including location, virtual_machine_id) for the first error to be fixed.

For the second error (`Inappropriate value for attribute "network_interface_ids": list of string`) the field `network_interface_ids` requires a list (since multiple NIC's can be attached to a Virtual Machine) - as such you should be able to make this:

```
  network_interface_ids = ["azurerm_network_interface.private_nic.id"]
```

It's worth noting the `azurerm_virtual_machine` resource has been superseded in 2.0 and for all new deployments we'd recommend using the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources instead.

Since this is a usage question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look,

Thanks!

**Comment by vivek99singh** [comment]
Thank you Tom. I followed your advise and got it working.

##Step to refer terraform state files
##Step to refer the existing resource group
data "azurerm_resource_group" "test" {
    name = "HWE-HC-LCPIPELINEIMAGES-WEST-EUROPE-RG"
}

## Step to refer the network resources from existing resource group 

data "azurerm_resource_group" "test1" {
    name = "HWE-NETWORKS-WEST-EUROPE-RG"

}

## Locate the existing custom/golden image of LAS,EAS,THinkEHR..
data "azurerm_image" "search" {
  name                = "HWE-HC-IIS-image-20191010-v1"
  resource_group_name = "HWE-HC-LCPIPELINEIMAGES-WEST-EUROPE-RG"
}

output "image_id1" {
  value = "/subscriptions/4cbcff46-75ea-420f-bef3-bdea0e39fe9d/resourceGroups/HWE-HC-LCPIPELINEIMAGES-WEST-EUROPE-RG/providers/Microsoft.Compute/images/HWE-HC-IIS-image-20191010-v1"
}


##refer to the existing VNET and Subnet
data "azurerm_virtual_network" "sourcevnet" {
  name                = "HWE-TECA-WEST-EUROPE"
  resource_group_name = data.azurerm_resource_group.test1.name
}

data "azurerm_subnet" "workload" {
  name                 = "hwe-teca-workloads2"
  resource_group_name  = data.azurerm_resource_group.test1.name
  virtual_network_name = data.azurerm_virtual_network.sourcevnet.name
}

resource "azurerm_network_interface" "private_nic" {
  name ="nic-test"
  location = var.location
  resource_group_name = data.azurerm_resource_group.test.name
  
  ip_configuration {
    name = "privatenic"
    subnet_id = data.azurerm_subnet.workload.id
    private_ip_address_allocation = "dynamic"
  }

}

##Step to create VM 1
resource "azurerm_virtual_machine" "VM1" {
  name = "var.vm_name"
  location              = var.location
  resource_group_name   = data.azurerm_resource_group.test.name
  network_interface_ids = ["azurerm_network_interface.private_nic.id"]
  vm_size               = "Standard_D2s_v3"

#This will delete the OS disk automatically when deleting the VM
  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true

storage_image_reference {
    id = data.azurerm_image.search.id
  }

  storage_os_disk {
    name              = "OSDISKTESTVM"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "var.vm_name"
    admin_username = "var.vm_username"
    admin_password = "var.vm_password"
  }

  os_profile_windows_config {
    provision_vm_agent        = true
    enable_automatic_upgrades = true
    }

}

resource "azurerm_virtual_machine_extension" "MYADJOINEDVMADDE1" {
  name                 = "MYADJOINEDVMADDE1"
  virtual_machine_id   = azurerm_virtual_machine.VM1.id
  publisher            = "Microsoft.Compute"
  type                 = "JsonADDomainExtension"
  type_handler_version = "1.3"

  # What the settings mean: https://docs.microsoft.com/en-us/windows/desktop/api/lmjoin/nf-lmjoin-netjoindomain

  settings = <<SETTINGS
    {
        "Name": "",
        "OUPath": "",
        "User": "",
        "Restart": "true",
        "Options": "3"
    }
SETTINGS
  protected_settings = <<PROTECTED_SETTINGS
    {
      "Password": ""
    }
  PROTECTED_SETTINGS
  depends_on = [azurerm_virtual_machine.VM1]
}
