### ISSUE TITLE
Support for exporting fqdn attribute in azurerm_private_dns_* resources

### ISSUE THREAD

**Issue by Wiston999** [terraform-providers/terraform-provider-azurerm#5939]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to expose an `fqdn` attribute on `azurerm_private_dns_*` resources as in their `azurerm_dns_*` counterpart.

### New or Affected Resource(s)

* azurerm_private_dns_a_record
* azurerm_private_dns_aaaa_record
* azurerm_private_dns_cname_record
* azurerm_private_dns_mx_record
* azurerm_private_dns_ptr_record
* azurerm_private_dns_srv_record

### References

* #4391 issue requesting the same on `azure_dns_*` resources

**Comment by njuCZ** [comment]
I am working on this issue
