### ISSUE TITLE
convert arm template output array to string to be consumed by terraform

### ISSUE THREAD

**Issue by fgarcia-cnb** [terraform-providers/terraform-provider-azurerm#5940]
Forgive me as this is more an ARM template issue combined with a terraform limitation. We have an arm template with the following outputs (static list of managed identities):

```jsonc
"outputs": {
        "managedIdentity1": {
            "condition": "[if(greaterOrEquals(variables('webAppCountNum'), 1), bool('true'), bool('false'))]",
            "type": "string",
            "value": "[reference(variables('managedIdentities').managedIdentity[0].name, '2016-08-01', 'Full').identity.principalId]"
        },
        "managedIdentity2": {
            "condition": "[if(greaterOrEquals(variables('webAppCountNum'), 2), bool('true'), bool('false'))]",
            "type": "string",
            "value": "[reference(variables('managedIdentities').managedIdentity[1].name, '2016-08-01', 'Full').identity.principalId]"
        },
        "managedIdentity3": {
            "condition": "[if(greaterOrEquals(variables('webAppCountNum'), 3), bool('true'), bool('false'))]",
            "type": "string",
            "value": "[reference(variables('managedIdentities').managedIdentity[2].name, '2016-08-01', 'Full').identity.principalId]"
        }
//continues,
```

I'd like to refactor this to be a dynamic list that will match the webAppCountNum. I believe I can accomplish this using [output iteration](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/copy-outputs), although there might be an issue using the reference function with count (haven't tested yet):
from [msdoc](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#reference)
> You can't use it with count because the count must be determined before the reference function is resolved.

there is also a separate issue where terraform [can only access scalar outputs](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html#outputs)

with all these limitations...
### is there a way to generate this dynamic output list and have it be consumable by terraform?
My idea was to convert the output array into a comma delimited string and have terraform split the data, but the restrictions on the "reference" function limit its use. If i could generate the array, i could probably convert it using [this method](https://stackoverflow.com/questions/48324984/convert-array-parameter-values-to-comma-separated-string)

**Comment by tombuildsstuff** [comment]
hi @fgarcia-cnb 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
