### ISSUE TITLE
Private Hosted Zones or --internal-dns-name ?

### ISSUE THREAD

**Issue by akamalov** [terraform-providers/terraform-provider-azurerm#595]
*Environment:*

```
Terraform v0.11.0
+ provider.azurerm v0.3.3
+ provider.tls v1.0.1
```
Greetings,

Challenge:

I would like to be able to resolve VM instances deployed in a subnet in Azure using their DNS name (no ```/etc/hosts```). 

Question : Does Terraform + AzureRM support ```--internal-dns-name``` of azure-cli ? Or perhaps a support for private hosted zones ? If yes, where can I get any references or examples, if you please?

**Comment by tombuildsstuff** [comment]
Hey @akamalov 

Thanks for opening this issue :)

From what I can see in [this document about how that flag in the Azure CLI works](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/static-dns-name-resolution-for-linux-on-azure) - I believe this is exposed as [the `internal_dns_name_label ` property on the `azurerm_network_interface` resource](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#internal_dns_name_label).

```
resource "azurerm_network_interface" "test" {
  name                = "myexamplenic"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  internal_dns_name_label = "example"

  # ...
}
```

Would it be possible for you to take a look and see if this is what you're after?

Thanks!

**Comment by akamalov** [comment]
Thanks @tombuildsstuff, I will tested out and see if this solves the issue.

**Comment by akamalov** [comment]
Worked @tombuildsstuff ! Thank You! Wondering if it is possible somehow to configure a reverse lookup domain as well ? May be ?? Thanks so much again!!

**Comment by tombuildsstuff** [comment]
@akamalov great, thanks for confirming - I'm going to close this issue since it's resolved

Regarding the lookup domain - I'm assuming you're referring to adding it to DNS? That's available using the DNS Resources, for example: https://www.terraform.io/docs/providers/azurerm/r/dns_ptr_record.html

Thanks!

**Comment by akamalov** [comment]
Thanks again @tombuildsstuff !!
