### ISSUE TITLE
Support for mySQL server parameters

### ISSUE THREAD

**Issue by sanchetanparmar** [terraform-providers/terraform-provider-azurerm#5959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Every time create Server parameters  `azurerm_mysql_configuration`  Need,  name RG name,server_name and value.  Each  parameter needs 5 line code, instead of that we can reduce, create a  `azurerm_mysql_configuration` and add multiple parameters like  [aws_rds_cluster_parameter_group](https://www.terraform.io/docs/providers/aws/r/rds_cluster_parameter_group.html)

### New or Affected Resource(s)

* azurerm_mysql_server ,   azurerm_mysql_configuration

### Current terraform configuration 

```
resource "azurerm_mysql_configuration" "interactive_timeout" {
  name                = "interactive_timeout"
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_server.mysql.name
  value               = "600"
}

resource "azurerm_mysql_configuration" "character_set_client" {
  name                = "character_set_client"
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_server.mysql.name
  value               = "utf8"
}

resource "azurerm_mysql_configuration" "character_set_server" {
  name                = "character_set_server"
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_server.mysql.name
  value               = "utf8"
}
```

above code has resource dependency as well

### Potential Terraform Configuration

```
resource "azurerm_mysql_configuration" "default" {
  name        = "mysql_configuration"
  family      = "5.6"
  description = "default Server parameters "
 
parameter {
    name  = "interactive_timeout"
    value = "600"
  }
  parameter {
    name  = "character_set_server"
    value = "utf8"
  }
  parameter {
    name  = "character_set_client"
    value = "utf8"
  }
}.
```
 

### References

* # https://github.com/terraform-providers/terraform-provider-azurerm/issues/5041

**Comment by ejohnson3378** [comment]
Piggybacking on this issue, the specific parameter `audit_log_events` allows for multi-selection and I cannot seem to find a way to perform multiple selections via terraform as the `value` is expecting a single string.

This is considered an invalid configuration. 
```
{
    name  = "audit_log_events",
    value = "CONNECTION, ADMIN"
 }
```

If I stack multiple configurations the last of the stack is the only one selected.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here, this is possible using Terraform's "foreach" syntax - please see here for more information: https://learn.hashicorp.com/tutorials/terraform/for-each?in=terraform/0-13

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
