### ISSUE TITLE
AKS setup failing in Government Cloud

### ISSUE THREAD

**Issue by jlogsdon** [terraform-providers/terraform-provider-azurerm#5960]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s_cluster" {
  resource_group_name = "${local.resource_group_name}"
  location            = "${var.resource_group_location}"
  name                = "${var.cluster_name}"
  dns_prefix          = "${local.unique_resource_name}"
  kubernetes_version  = "${var.cluster_version}"

  default_node_pool {
    max_count           = "${var.cluster_pool_vm_max_count}"
    min_count           = "${var.cluster_pool_vm_min_count}"
    node_count          = "${var.cluster_pool_vm_count}"
    name                = "${var.cluster_pool_name}"
    vm_size             = "${var.cluster_pool_vm_size}"
    os_disk_size_gb     = "${var.cluster_pool_vm_disk}"
    enable_auto_scaling = "${var.cluster_pool_enable_auto_scaling}"
    type                = "${var.cluster_pool_enable_auto_scaling ? "VirtualMachineScaleSets" : "AvailabilitySet" }"
  }

  lifecycle {
    ignore_changes = [
      "default_node_pool.0.node_count"
    ]
  }

  role_based_access_control {
    enabled = true
  }

  # https://github.com/terraform-providers/terraform-provider-azurerm/issues/2510
  service_principal {
    client_id     = "${azurerm_azuread_application.aks_app.application_id}"
    client_secret = "${azurerm_azuread_service_principal_password.aks_sp_password.value}"
  }
}
```

### Expected Behavior

It should create the AKS cluster as configured (without any addons).

### Actual Behavior

The request to create the cluster failed with a 400 status.

```
azurerm_kubernetes_cluster.k8s_cluster: Error creating Managed Kubernetes Cluster "logrocket" (Resource Group "logrocketiew0s2"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="OperationNotAllowed" Message="Addon 'httpApplicationRouting' is not supported in this cloud environment.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is a Government Cloud customer; we do not have access to our own Government Cloud account to test with.

### References

* #0000

**Comment by jlogsdon** [comment]
Our assumption is that Azure's gov cloud sees the keys in the request, which are [always included if I am reading the code correctly](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.44.0/azurerm/internal/services/containers/kubernetes_addons.go#L125-L132), and rejecting them outright.

**Comment by e96wic** [comment]
Same issue in China
