### ISSUE TITLE
Support for namespace and dimension parameters in azurerm_monitor_autoscale_setting

### ISSUE THREAD

**Issue by GhostInThePotato** [terraform-providers/terraform-provider-azurerm#5969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide option to specify metric namespace and dimensions (dimension name, operator and value) in azurerm_monitor_autoscale_setting. 

These can be manually set in the Azure Portal for VMSS autoscaling, but can't be set in Terraform at the moment. I don't know enough about the Terraform code base to know how you would specify the dimension parameters so I've copied the Azure Resource Explorer view of what the settings look like when you manually set it in Azure Portal.

### New or Affected Resource(s)

* azurerm_monitor_autoscale_setting

### Potential Terraform Configuration

Terraform config:
```hcl
resource "azurerm_monitor_autoscale_setting" "example" {
  name                = "myAutoscaleSetting"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  target_resource_id  = azurerm_virtual_machine_scale_set.example.id

    rule {
      metric_trigger {
        metric_name        = "pods"
        metric_namespace   = "kubernetes custom metrics"
        metric_resource_id = "/subscriptions/.../resourceGroups/rg_.../providers/Microsoft.ContainerService/managedClusters/aks_..."
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT5M"
        time_aggregation   = "Maximum"
        operator           = "Equals"
        threshold          = 5
        dimension          = (list of dimensions with keys DimensionName, Operator, Values)
      }
    }
```

Azure Resource Explorer view (redacted):
```json
{
  "id": "/subscriptions/.../resourceGroups/MC_rg_.../providers/microsoft.insights/autoscalesettings/scale",
  "name": "dmzscale",
  "type": "Microsoft.Insights/autoscaleSettings",
  "location": "uksouth",
  "tags": {},
  "properties": {
    "profiles": [
      {
        "capacity": {
          "minimum": "4",
          "maximum": "10",
          "default": "4"
        },
        "rules": [
          {
            "metricTrigger": {
              "metricName": "pods",
              "metricNamespace": "kubernetes custom metrics",
              "metricResourceUri": "/subscriptions/.../resourceGroups/rg_.../providers/Microsoft.ContainerService/managedClusters/aks_...",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT5M",
              "timeAggregation": "Maximum",
              "operator": "Equals",
              "threshold": 5,
              "dimensions": [
                {
                  "DimensionName": "Label",
                  "Operator": "Equals",
                  "Values": [
                    "pod-name"
                  ]
                }
              ],
              "dividePerInstance": false
            },
            "scaleAction": {
              "direction": "Decrease",
              "type": "ChangeCount",
              "value": "1",
              "cooldown": "PT5M"
            }
          }
        ],
      }
    ],
    "enabled": true,
    "name": "scale",
    "targetResourceUri": "/subscriptions/.../resourceGroups/MC_RG_.../providers/Microsoft.Compute/virtualMachineScaleSets/aks-...-vmss",
    "notifications": []
  }
}
```

### References

* [Terraform doc for azurerm_monitor_autoscale_setting](https://www.terraform.io/docs/providers/azurerm/r/monitor_autoscale_setting.html)

**Comment by GhostInThePotato** [comment]
The Azure CLI `az` now supports metric dimensions and namespace. When will Terraform add this ability?

**Comment by Dmitry1987** [comment]
Really needed for us :( can't select dimension and it renders the module useless for us. 
What would be the temporary workaround? I guess az cli is the only way?

**Comment by Dmitry1987** [comment]
@GhostInThePotato could you please point me to where I can find how to use a dimension selection, when creating autoscale rule through the CLI?  Is it this command https://docs.microsoft.com/en-us/cli/azure/monitor/autoscale/rule?view=azure-cli-latest#az-monitor-autoscale-rule-create ?
They have namespace I see, but how to select the dimensions, can't find such flags. Maybe there's one more way to create it?

**Comment by GhostInThePotato** [comment]
> @GhostInThePotato could you please point me to where I can find how to use a dimension selection, when creating autoscale rule through the CLI? Is it this command https://docs.microsoft.com/en-us/cli/azure/monitor/autoscale/rule?view=azure-cli-latest#az-monitor-autoscale-rule-create ?
> They have namespace I see, but how to select the dimensions, can't find such flags. Maybe there's one more way to create it?

You specify the dimension in the condition flag, same place as namespace. I don't have my code to hand but I believe it is like:

`az monitor autoscale rule create -g {rg} --autoscale-name {name} --condition '"MetricNamespace" MetricName > 75 avg 5m where DimensionName == value1 or value2' --scale to 5`

**Comment by Dmitry1987** [comment]
awesome, thank you @GhostInThePotato , the documentation page does not mention an ability to specify "where DimensionName == value1 or value2", I will try!

**Comment by GhostInThePotato** [comment]
The documentation could definitely be better. I only found out how to do it from looking through the [`az` code on github](https://github.com/Azure/azure-cli/blob/814598f5e8fe3d0e418f0be392a0f2984b6bd215/src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py#L152).
