### ISSUE TITLE
Error reading the advanced threat protection settings of AzureRM Storage Account

### ISSUE THREAD

**Issue by jeanfrancoislelezec** [terraform-providers/terraform-provider-azurerm#5973]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform version: v0.12.20
* AzureRM provider version: 1.44.0

### Affected Resource(s)

* azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "filearchive" {
  name                     = var.file.name
  account_kind             = "FileStorage" 
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Premium"
  account_replication_type = "LRS"
  tags = var.tags
  network_rules {
    default_action = "Deny"
    ip_rules       = [var.devops_ip]   
    virtual_network_subnet_ids  = [var.aks_subnet_id]
  }
}
```

### Debug Output

https://gist.github.com/jeanfrancoislelezec/3a43a271e752a866ada593ffd76bf50c

### Expected Behavior

No error should be return 

### Actual Behavior

Storage account is created, but an error is handled by the api

### Steps to Reproduce

Create a standard tf script for deploying a azure storage on west europe .
1. terraform apply

### References

* #0000

**Comment by brunhil** [comment]
I also started running into this today. I am on version 1.43 and 1.38.

**Comment by brunhil** [comment]
I believe my issue is due to Azure issues in East US currrently. Will update accordingly when they are resolved.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems I cannot repro this issue with below tfconfig. Maybe I missed something. If you need, you can take a try on below tfconfig to check whether the problem still exists.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-storage-test"
  location = "west europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvirtnettest"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "acctestsubnettest"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.2.0/24"
  service_endpoints    = ["Microsoft.Storage"]
}

resource "azurerm_storage_account" "test" {
  name                     = "saaccttest"
  account_kind             = "FileStorage" 
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Premium"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Deny"
    ip_rules                   = ["127.0.0.1"]
    virtual_network_subnet_ids = [azurerm_subnet.test.id]
  }
  
  tags = {
    env = "test"
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @jeanfrancoislelezec 

Thanks for opening this issue.

Taking a look into this this has been fixed in a newer version of the Azure Provider - we're currently on version 2.11 - which you can upgrade to by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=2.11.0"
}
```

.. which should solve this for you - would you be able to take a look and see if that works for you?

Since this should be fixed by updating the version of the AzureRM Provider being used here I’m going to close this issue for the moment, but please let us know if you’re still having issues after doing so and we’ll take another look.

Thanks!
