### ISSUE TITLE
Support for Cosmos Db stored procedures, indexes and udfs.

### ISSUE THREAD

**Issue by TechWatching** [terraform-providers/terraform-provider-azurerm#5979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is not currently possible to create / update indexes, stored procedures, udfs in Cosmos Db (SQL API) using Terraform. ARM templates and Azure Ressource Provider support it so according to [Azure Cosmos Team](https://github.com/MicrosoftDocs/azure-docs/issues/49349), there is nothing preventing Terraform to support it. Is it on the roadmap ?

### New or Affected Resource(s)

*New resources*:
* azurerm_cosmosdb_sql_storedprocedure
* azurerm_cosmosdb_sql_index
* azurerm_cosmosdb_sql_udf
* azurerm_cosmosdb_sql_trigger

*Affected ressources* :
* azurerm_cosmosdb_sql_database
* azurerm_cosmosdb_sql_container

### References

https://github.com/MicrosoftDocs/azure-docs/issues/49349

**Comment by brunhil** [comment]
This functionality is available in the _2019-12-12_ API version for Cosmos, [link](https://github.com/Azure/azure-sdk-for-go/blob/master/services/cosmos-db/mgmt/2019-12-12/documentdb/sqlresources.go)

**Comment by liyubupt** [comment]
Our project is currently using terraform to provision cosmos db. This would be very useful

**Comment by jonmaestas** [comment]
Index policy for CosmosDB SQL Container is what we're currently looking for. 

Something similar to the [Gremlin Graph index policy](https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_gremlin_graph.html#index_policy) would be really nice.

**Comment by syedhassaanahmed** [comment]
+1 on this, particularly support for `azurerm_cosmosdb_sql_storedprocedure`

**Comment by katbyte** [comment]
closed by #6189
