### ISSUE TITLE
Support for configuring the Connection Security firewall and VNET settings in azurerm_mysql_server

### ISSUE THREAD

**Issue by troy256** [terraform-providers/terraform-provider-azurerm#5984]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We use azurerm_mysql_server to create MySQL instances in Azure.  It works great, but after creation we have to manually login into the Azure Portal, click on "Connection Security" and then change the settings under "Firewall rules" and "VNET rules" to control access.  We'd love if there was a way to define this in Terraform.

**Comment by IanMoroney** [comment]
@troy256 ,
There is a `azurerm_mysql_firewall_rule` resource to add firewall rules. 
There is a `azurerm_mysql_virtual_network_rule` to add VNET rules.

Does this answer your question?

**Comment by troy256** [comment]
It does, thank you.
