### ISSUE TITLE
azurerm_private_dns_zone_virtual_network_link causes configuration drift when using upper case names

### ISSUE THREAD

**Issue by pbstrein** [terraform-providers/terraform-provider-azurerm#5985]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.20
+ provider.azurerm v2.0.0

### Affected Resource(s)

* `azurerm_private_dns_zone_virtual_network_link`

### Terraform Configuration Files

```hcl
# provider definition
provider "azurerm" {
  version = ">= 1.44.0"
  features {}
}

terraform {
  backend "azurerm" {
    resource_group_name  = "rg-primary-shared-storage"
    storage_account_name = "primarysharedstorage"
    container_name       = "tfstate"
    key                  = "networklinkbug.terraform.tfstate"
  }
}

resource "azurerm_resource_group" "rg" {
  name     = format("rg-%s-%03d", "networklinkDRIFT", 0)
  location = "centralus"
  tags     = {}
}

resource "azurerm_virtual_network" "vNet" {
  name                = format("vnet-%s-%03d", "networklinkDRIFT", 0)
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  tags                = {}
}

resource "azurerm_private_dns_zone" "fileshareStorageAccount" {
  name                = "privatelink.file.core.windows.net"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "fileshareLink" {
  name                  = "link-${azurerm_virtual_network.vNet.name}"
  resource_group_name   = azurerm_resource_group.rg.name
  private_dns_zone_name = azurerm_private_dns_zone.fileshareStorageAccount.name
  virtual_network_id    = azurerm_virtual_network.vNet.id
}

resource "azurerm_private_dns_a_record" "fileshare" {
  name                = "arec"
  zone_name           = azurerm_private_dns_zone.fileshareStorageAccount.name
  resource_group_name = azurerm_resource_group.rg.name
  ttl                 = 300
  records             = ["10.0.0.112"] //arbitrary IP for issue
}
```

### Expected Behavior

After first creating the resources by running `terraform apply`, a subsequent `terraform plan` should produce an empty plan, even though the some of the names are capitalized. 

### Actual Behavior

A subsequent `terraform plan` creates a diff file where the link gets destroyed and recreated and dependent resources get destroyed and recreated.

![image](https://user-images.githubusercontent.com/21132293/75904959-b9043a00-5e09-11ea-8437-f9575ceb4755.png)
 

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` - configuration drift appears due to capital letters in `azurerm_private_dns_zone_virtual_network_link.name`

**Comment by pbstrein** [comment]
For those who run into this issue, a temporary workaround is to use the `lower` function that HCL offers.

**Comment by johnwildes** [comment]
I'm seeing the same with this configuration
```
Terraform v0.12.23
+ provider.azurerm v2.1.0
+ provider.random v2.2.1
```
@pbstrein I use the workaround you mention `lower` function.

**Comment by lrxtom2** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/10933
