### ISSUE TITLE
Azure Provider 2.0.0 Crash With "rpc error: code = Unavailable desc = transport is closing"

### ISSUE THREAD

**Issue by ItayPodhajcer** [terraform-providers/terraform-provider-azurerm#5991]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v0.12.21
* AzureRM Provider version: v2.0.0

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "rg-${var.deployment_name}-${var.location}"
  location = var.location
}

resource "azurerm_virtual_network" "this" {
  name                = "vnet-${var.deployment_name}-${var.location}"
  location            = var.location
  resource_group_name = azurerm_resource_group.this.name
  address_space       = ["10.1.0.0/26"]
}

resource "azurerm_subnet" "this" {
  name                 = "snet-${var.deployment_name}"
  resource_group_name  = azurerm_resource_group.this.name
  address_prefix       = "10.1.0.0/26"
  virtual_network_name = azurerm_virtual_network.this.name
}

resource "random_id" "storage" {
  keepers = {
    resource_group = azurerm_resource_group.this.name
  }

  byte_length = 8
}

resource "azurerm_storage_account" "this" {
  name                     = random_id.storage.hex
  resource_group_name      = azurerm_resource_group.this.name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  static_website {}
}

resource "azurerm_storage_share" "export" {
  name                 = "export"
  storage_account_name = azurerm_storage_account.this.name
  quota                = 5120
}

resource "azurerm_storage_share" "data" {
  name                 = "data"
  storage_account_name = azurerm_storage_account.this.name
  quota                = 5120
}

resource "azuread_application" "this" {
  name                       = "aks-${var.deployment_name}-${var.location}"
  available_to_other_tenants = false
  type                       = "native"
}

resource "azuread_service_principal" "this" {
  application_id = azuread_application.this.application_id
}

resource "random_password" "this" {
  length  = 32
  special = false
}

resource "azuread_service_principal_password" "this" {
  service_principal_id = azuread_service_principal.this.id
  value                = random_password.this.result
  end_date             = "2030-01-01T00:00:00Z"
}

resource "azurerm_kubernetes_cluster" "this" {
  name                = "aks-${var.deployment_name}-${var.location}"
  location            = var.location
  resource_group_name = azurerm_resource_group.this.name
  node_resource_group = "${azurerm_resource_group.this.name}-aks-nodes"
  dns_prefix          = "${var.deployment_name}-${var.location}"

  default_node_pool {
    name           = "default"
    node_count     = 1
    vm_size        = "Standard_B2s"
    type           = "VirtualMachineScaleSets"
    vnet_subnet_id = azurerm_subnet.this.id
  }

  service_principal {
    client_id     = azuread_application.this.application_id
    client_secret = azuread_service_principal_password.this.value
  }

  network_profile {
    network_plugin = "azure"
  }
}
```

**Generated crash log:** [crash.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/4290383/crash.log)

### Description / Feedback

The above module is being used twice with a different location but with the same deployment name. The module execution should complete and not crash.

### References

None that I'm aware of.

**Comment by ItayPodhajcer** [comment]
**UPDATE**
Executed `apply` without the storage related configurations (storage account and shares), and although there was an error that one of the aks clusters couldn't find the defined principal ID, re-running `apply` completed the creation of two clusters without any additional problems.

Destroyed everything, added back the storage account (without the file shares) and `apply` crushed with the `rpc error`.

It seems that it is related somehow to the storage account configuration.

**Comment by ItayPodhajcer** [comment]
**UPDATE 2**
After adding and removing options from the storage account configuration, I think it might be related to the `static_website` sub-section.

If I execute without it (as the [documentation says it's optional](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#static_website)) I get the following error:
_**Error reading static website for AzureRM Storage Account "f11d174c35c86766": accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationPermissionMismatch" Message="This request is not authorized 
to perform this operation using this permission.\nRequestId:0a0a10d3-f01e-0068-3330-f32b9e000000\nTime:2020-03-05T20:54:06.5353234Z"**_

When I add the `static_website` element with empty brackets like so:
```hcl
resource "azurerm_storage_account" "this" {
  ...
  static_website {}
}
```
I get the `rpc error`.

**Comment by lsmith130** [comment]
I faced this same issue, was able to work around it by setting static_website to:
```
static_website {
  index_document = "/dummy"
}
``` 
I also get a `AuthorzationPermissionMismatch` when omitting the `static_website`, and full Go panic with a nil interface error when using
```
static_website {}
```
