### ISSUE TITLE
Support for os_disk name in azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by philthynz** [terraform-providers/terraform-provider-azurerm#6003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add some functionality for us to change the os disk name in `azurerm_windows_virtual_machine`. That will allow us to reference that disk with `azurerm_snapshot` to make a snapshot.

To clone a VM without touching the existing machine. We need snapshots of the disks, attach the disks to a new VM, generalize that VM, and then image it.

### New or Affected Resource(s)

`azurerm_windows_virtual_machine`

### Potential Terraform Configuration

```
  os_disk {
    name = "${var.vm_name}_os_disk"
    caching = "ReadWrite"
    storage_account_type = var.os_disk_type
    disk_size_gb = var.os_disk_size
  }
```

### Current config

```
# Create Windows VMs if os_type is Windows
resource "azurerm_windows_virtual_machine" "win_vm" {
  count                 = var.os_type == "Windows" ? var.instance_numbers : 0
  name                  = "${var.instance_name}_${count.index}"
  resource_group_name   = "${var.team_name}_${var.release}_${var.owner}_${var.intention}"
  location              = var.loc
  size                  = var.vm_size
  enable_automatic_updates = var.enable_windows_updates
  provision_vm_agent    = true
  computer_name         = "${var.instance_name}-${count.index}"
  admin_username        = var.vm_username
  admin_password        = var.vm_password
  network_interface_ids = [element(azurerm_network_interface.net_int.*.id, count.index)]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = var.os_disk_type
    disk_size_gb         = var.os_disk_size
  }

  source_image_reference {
    publisher = var.storage_image_publisher
    offer     = var.storage_image_offer
    sku       = var.storage_image_sku
    version   = var.storage_image_version
  }

  tags = {
    team = var.team_name
    environment = var.env_name
    useby = var.useby
    release = var.release
    owner = var.owner
    intention = var.intention
  }
}
```

**Comment by njuCZ** [comment]
It seems `azurerm_windows_virtual_machine` already supports `name` in `os_disk` block.
please refer to https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html#name-1

**Comment by philthynz** [comment]
Either that's new or I am blind.
