### ISSUE TITLE
Terraform plan showing changes when there are no changes (not a question)

### ISSUE THREAD

**Issue by sai-ns** [terraform-providers/terraform-provider-azurerm#6007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
+ Terraform v0.12.21
+ provider.azurerm v2.0.0

### Affected Resource(s)

Below are what I have tested, could be same for other resources as well
* azurerm_app_service
* azurerm_app_service_plan

### Terraform Configuration Files

```hcl
module "appservice" {
  .
  .
  .
  appservice_plan_name  = "appservice-plan"
  resource_group_name  = "demo-resource-group"
  location                         = "eastus"
  appservice_name          = "demo-appservice"
}
```

### Expected Behavior
Terraform plan should detect no changes

### Actual Behavior
I am creating an appservice plan and appservice and not creating tags particularly for these resources since they are inherited from the resource group (which was created by a different team). Prior to azurerm provider v2.0, when I apply changes and run plan, it would detect no changes but ever since I upgraded, first apply works fine but when I run plan again with no changes made in the code, terraform would detect changes. It retrieved tags from the resources created by running applu and trying to change them to null.  
```
~ tags                         = {
          - "app-id"           = "1234" -> null
          - "application"      = "testapp" -> null
          - "sdlc-environment" = "test" -> null
     }
```

Also, ran into another issue when I tried to apply changes. 
Error: Error creating/updating App Service Plan "appservice-plan" (Resource Group "demo-resource-group"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.hostingEnvironmentProfile.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by sai-ns** [comment]
Did anyone get a chance to look at it? I am stuck in a situation where I need azurerm version 2.0 for storage account and 1.44 for appservice. I'd say this is a bug since I am seeing this behavior since upgrading to 2.0.

**Comment by harrymitchinson** [comment]
Also seeing this with azurerm_kubernetes_cluster when running `terraform apply` followed by `terraform plan` . Nothing has changed in my project but Terraform thinks my tags have changed.
```
  ~ resource "azurerm_kubernetes_cluster" "aks" {
      ... 

      ~ default_node_pool {
            availability_zones    = [
                "1",
                "2",
                "3",
            ]
            enable_auto_scaling   = true
            enable_node_public_ip = false
            max_count             = 3
            max_pods              = 110
            min_count             = 2
            name                  = "devappsys01"
            node_count            = 2
            node_labels           = {}
            node_taints           = []
            os_disk_size_gb       = 100
          ~ tags                  = {
              + "environment" = "dev"
              + "terraformed" = "true"
            }
            type                  = "VirtualMachineScaleSets"
            vm_size               = "Standard_D2s_v3"
        }

        ...
    }
```

**Comment by tombuildsstuff** [comment]
hi @sai-ns 

Thanks for opening this issue.

App Services behave differently to most other resources in Azure in that they inherit tags from the Resource Group they're contained in - as such you're seeing this behaviour since these are being set at the Resource Group level.

Version 2.0 of the Azure Provider fixed a bug where the `tags` field wouldn't show the assigned tags in cases like this (since it was Optional + Computed, which means we'd use Azure's default value when unspecified) - as such this behaviour is intentional. Instead you should be able to work around this by using [Terraform's `ignore_changes` feature](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to ignore changes to the `tags` field here.

Since this behaviour is intentional I'm going to close this issue for the moment - but please let us know if using `ignore_changes` doesn't work for you and we'll take another look.

Thanks!

**Comment by markslater** [comment]
@tombuildsstuff Would it be possible to get [the changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md) for 2.0.0 updated to include a link to the issue that resulted in the change, or failing that, this issue?  I saw that the change log specifies 

> The field `tags` is no longer computed

It wasn't clear to my what that meant, though I suspected it to be what you explained above.

**Comment by sai-ns** [comment]
@tombuildsstuff thanks! adding `ignore_changes` worked. Can I ask what(issue/bug) was fixed to trigger this change? Because it was working just fine before 2.0.
