### ISSUE TITLE
Issue with unable to attach the VM ( Normal VM not VM scale set ) under availability set to the load balancer backend #37

### ISSUE THREAD

**Issue by retheshnair** [terraform-providers/terraform-provider-azurerm#601]
Hi there,
Issue of unable to attach the VM ( Normal VM not VM scale set ) under an availability set to the load balancer backend

Terraform Version

[root@puppettest files]# terraform -v
Terraform v0.11.0

[root@puppettest files]#

Affected Resource(s)

Please list the resources as a list, for example:

VM
azure load balancer

**Comment by tombuildsstuff** [comment]
hi @retheshnair

Thanks for opening this issue.

So that we can take a look into this, are you able to post the Terraform Configuration you're using?

Thanks!

**Comment by tombuildsstuff** [comment]
ping @retheshnair :)

**Comment by retheshnair** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/63 it seems already issues opened for this issue

**Comment by tombuildsstuff** [comment]
Thanks for letting us know - closing in favour of #63
