### ISSUE TITLE
`azurerm_app_service`: support for creating Linux App Services

### ISSUE THREAD

**Issue by Pets** [terraform-providers/terraform-provider-azurerm#602]
### Terraform Version
Terraform v0.11.1
+ provider.azurerm v0.3.3

### Terraform Configuration Files
````
variable "azurerm_client_id" {
  type = "string"
  default = "<YOUR_CLIENT_ID>"
}

variable "azurerm_client_secret" {
  type = "string"
  default = "<YOUR_CLIENT_SECRET>"
}

variable "azurerm_subscription_id" {
  type = "string"
  default = "<YOUR_SUBSCRIPTION_ID>"
}

variable "azurerm_tenant_id" {
  type = "string"
  default = "<YOUR_TENANT_ID>"
}

variable "azurerm_location" {
  type = "string"
  default = "East US"
}

provider "azurerm" {
  client_id       = "${var.azurerm_client_id}"
  client_secret   = "${var.azurerm_client_secret}"
  subscription_id = "${var.azurerm_subscription_id}"
  tenant_id       = "${var.azurerm_tenant_id}"
}

resource "azurerm_resource_group" "staging" {
  name     = "dt-linux-resource-group"
  location = "${var.azurerm_location}"
}

resource "azurerm_app_service_plan" "staging" {
 name = "dt-linux-service-plan"
 location = "${var.azurerm_location}"
 resource_group_name = "${azurerm_resource_group.staging.name}"
 kind = "Linux"

 sku {
   tier = "Standard"
   size = "S1"
   capacity = 1
 }
}

resource "azurerm_app_service" "staging" {
  name                = "linux-webapp"
  location            = "${azurerm_resource_group.staging.location}"
  resource_group_name = "${azurerm_resource_group.staging.name}"
  app_service_plan_id = "${azurerm_app_service_plan.staging.id}"
  enabled = true
}
````

### Expected Behavior
We expect to define the kind of the machine (azurerm_app_service) we create OR more simple than that... if we create an azurerm_app_service_plan of "kind=Linux", we assume that the azurerm_app_service created will be of Linux type ("app, linux").

### Actual Behavior
Actually, the app_service created in Azure is a Windows app_service even if the azurerm_app_service_plan is a "kind=Linux".

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Go in Azure and see that the web app is Windows  and not Linux

**Comment by scottrangerio** [comment]
Hey all,

I had a look into this today and managed to figure out what was going wrong.

The main issue is that specifying `kind = "Linux"` on the service plan isn't enough for the underlying Azure sdk. You also need to pass `reserved = true` as a property for Azure to correctly detect the web app as a Linux app. Terraform already has support for setting this property so with Terraform version 0.11.0 I was able to create a Linux web app using the following basic configuration I put together to debug this, no code changes required!

```
resource "azurerm_resource_group" "test" {
  name = "sctftestlinux"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "test" {
  name                = "sctftestlinuxplan"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  kind                = "Linux"
  sku {
    tier = "Standard"
    size = "S1"
  }
  properties {
    reserved = true
  }
}

resource "azurerm_app_service" "test" {
  name                = "sctftestlinuxsite"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  app_service_plan_id = "${azurerm_app_service_plan.test.id}"
}
```

While this does work, this isn't exactly intuitive. Would it be an idea to add a note to the documentation about this Azure quirk, or maybe making a code change to set reserved = true when kind = Linux for better UX?

**Comment by mattops** [comment]
Yes this an really annoying quirk/bug.  Just wasted hours trying to figure out why my app service plan was in fact windows based, and not on linux.   Interestingly, from the portal the app service plan had a penguin in the logo suggesting it was linux, the `type` is listed as `linux` in the cli - however all apps deployed are on Windows.

**Comment by tombuildsstuff** [comment]
hey @Pets @scottrangerio @mattops 

Thanks for opening this issue - apologies for the delayed response here!

I've opened #1058 which updates the documentation to mention this behaviour - and I'm going to open another PR which to add another `example usage` to the documentation for provisioning a Linux App Service Plan so that this is clearer.

Thanks!
