### ISSUE TITLE
Error creating azurerm_storage_management_policy for storage account with zone redundant storage (ZRS)

### ISSUE THREAD

**Issue by khaliddermoumi** [terraform-providers/terraform-provider-azurerm#6031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Background: When you have a storage account with zone redundant storage ("ZRS"), then the archive storage feature is currently NOT supported in Azure, as it would be in local redundant storage ("LRS"). Still, lifecycle management policies are supported for these accounts, and make perfect sense. You just can't use the archive features of these policies with these ZRS storage accounts. 

The problem is, creating a management policy for such an account leads to an error with terraform, obviously because the provider tries to set the "archive" related features in the request.

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v2.0.0

### Affected Resource(s)

* `azurerm_storage_management_policy`
* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource azurerm_storage_management_policy backups {
  storage_account_id = module.storage_account.id

  rule {
    name    = "MoveToCoolStorage"
    enabled = true
    filters {
      prefix_match = [azurerm_storage_container.backups.name]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than = 1
        delete_after_days_since_modification_greater_than       = 2
      }
      snapshot {
        delete_after_days_since_creation_greater_than = 3
      }
    }
  }
}
```

### Expected Behavior

The storage management policy should be created. It is possible to create this policy in the azure portal.
The same policy just works with a storage account of redundancy "local" ("LRS"). Terraform should be able to generate the same policy in a "ZRS" storage account.

### Actual Behavior

The policy is not created, and terraform stops and an error is returned:
```text
Error: Error creating Azure Storage Management Policy "/subscriptions/42fcec17-b98f-42b5-bbf1-80dd9eae41af/resourceGroups/core-arg-dev/providers/Microsoft.Storage/storageAccounts/coreasadev001": storage.ManagementPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="tierToArchive is not supported for the account."
```

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested with below tfconfig, I can repro this issue and I found the root cause is tier_to_archive_after_days_since_modification_greater_than property is not nil when it is not specified in tfconfig. After do more testing, I found this issue has been fixed in latest azurerm version. Could you have a try latest version to check whether the issue still exists? Thanks a lot.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-storagerg-test10"
  location = "eastus2"
}

resource "azurerm_storage_account" "test" {
  name                = "acctestsatest10"
  resource_group_name = azurerm_resource_group.test.name

  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "ZRS"
}

resource "azurerm_storage_management_policy" "test" {
  storage_account_id = azurerm_storage_account.test.id

  rule {
    name    = "MoveToCoolStorage"
    enabled = true
	
    filters {
      prefix_match = ["container1/foo"]
      blob_types   = ["blockBlob"]
    }
	
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than = 1
        delete_after_days_since_modification_greater_than       = 2
      }
	  
      snapshot {
        delete_after_days_since_creation_greater_than = 4
      }
    }
  }
}
```

**Comment by khaliddermoumi** [comment]
Works!
Thx Tracy :)
