### ISSUE TITLE
Changes to azurerm_traffic_manager_profile destroys endpoints

### ISSUE THREAD

**Issue by vidarw** [terraform-providers/terraform-provider-azurerm#6041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_traffic_manager_profile`
* `azurerm_traffic_manager_endpoint`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azurerm_traffic_manager_profile" "api" {
  name                = "my-api"
  resource_group_name = var.resource_group_name
  traffic_routing_method = "Priority"

  dns_config {
    relative_name = "my-api.example.com"
    ttl           = 15
  }

  monitor_config {
    protocol                     = "https"
    port                         = 443
    path                         = "/health"
    interval_in_seconds          = 30
    timeout_in_seconds           = 5
    tolerated_number_of_failures = 3
    expected_status_code_ranges  = ["100-403"]
  }
}


resource "azurerm_traffic_manager_endpoint" "api_blue_endpoint" {
  name                = "my-api-blue"
  resource_group_name = var.resource_group_name
  profile_name        = azurerm_traffic_manager_profile.api.name

  target_resource_id = var.blue_ip_resource_id
  type               = "azureEndpoints"
  priority           = 10
  endpoint_status    = var.enable_blue == true ? "Enabled" : "Disabled"

  custom_header {
    name  = "Host"
    value = "my-apu."
  }
}
```

### Expected Behavior

Changes to values in the `azurerm_traffic_manager_profile` should not affect the `azurerm_traffic_manager_endpoint`.

### Actual Behavior
Changes to values in the `azurerm_traffic_manager_profile` like `monitor_config.path` or `dns_config.ttl` causes all the `azurerm_traffic_manager_endpoint` to disappear. You basically have to run terraform twice to reprovision them.

### Steps to Reproduce

1. `terraform apply`
2. Change `monitor_config.path` from `/health` to `/healthz`.
3. `terraform apply`

Your endpoints are now gone.

### References

* #0000

**Comment by djsly** [comment]
Seeing the same thing here... doing any change to the profiles wipes the endpoints...

**Comment by simonlegeek** [comment]
We also kicked ourselves in the nuts with this bug trying to apply a simple change in resource tags. Does anyone have an update on this?

**Comment by nitzanm** [comment]
I've created a pull request with a workaround: https://github.com/terraform-providers/terraform-provider-azurerm/pull/7471 . It was attached to a closed/duplicate issue so I'm mentioning it here to make sure it's seen.

**Comment by djsly** [comment]
@nitzanm  / @ArcturusZhang  which of the two PR should I follow to know when this is ready ? 

@katbyte  I see you are reviewing #7846 , should we expect this in 2.21.0 ? :)
