### ISSUE TITLE
Express Route gateway (VNG) connection with Express Route Circuit

### ISSUE THREAD

**Issue by gek0** [terraform-providers/terraform-provider-azurerm#6042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Basically, I'm missing an option to connect a VNET (Express Route Gateway) to a Express route Circuit as it's described here https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-linkvnet-portal-resource-manager
This is possible over Azure Portal but not seeing anywhere an API or Terraform resource that enables this option

### New or Affected Resource(s)

* azurerm_express_route_circuit_connection (new resource)

### Potential Terraform Configuration

```hcl
resource "azurerm_express_route_circuit_connection" "example" {
    express_route_circuit_id = "XXXX"
    virtual_network_gateway_id = "XXXX"
}
```

### References

* #0000

**Comment by ttyS0** [comment]
Isn't this done via the `azurerm_virtual_network_gateway_connection` resource?

```
resource "azurerm_virtual_network_gateway_connection" "foo" {
  location                   = "us-east"
  name                       = "foo"
  resource_group_name        = "network"
  type                       = "ExpressRoute"
  virtual_network_gateway_id = azurerm_virtual_network_gateway.foo.id
  express_route_circuit_id = azurerm_express_route_circuit.foo.id
}
```

**Comment by gek0** [comment]
Looks like it is! Thank you @ttyS0 and sorry for missing that out :(
I did go over the docs for this resource before https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway_connection.html
but it only mentions  Vnet-to-Vnet and Site-to-Site connections and since I'm doing an ExpressRouteCircuit-to-ExpressRouteGW connection must've missed it.

Closing this one then as resolved then.
