### ISSUE TITLE
Support for Security Center Event Hub export

### ISSUE THREAD

**Issue by davidobrien1985** [terraform-providers/terraform-provider-azurerm#6066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Export Security Center events to Azure Event Hub.

### New or Affected Resource(s)

* azurerm_security_center_export (new)

### References

https://github.com/Azure/azure-rest-api-specs/blob/06b9412319ada8678c0ce07016cac1bf66258b1d/specification/security/resource-manager/Microsoft.Security/preview/2019-01-01-preview/automations.json

* #0000

**Comment by njuCZ** [comment]
duplicated issues and it has already been implemented, please refer to: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_automation
