### ISSUE TITLE
Azure role assignment fails to assign service principal, shows "identity deleted"

### ISSUE THREAD

**Issue by kaylacrowder** [terraform-providers/terraform-provider-azurerm#6068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 12.21
* AzureRM Provider version: 1.35

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "aks_sp_contributor" {
  scope                = azurerm_kubernetes_cluster.akc2.id
  role_definition_name = "Contributor"
  principal_id         = var.aks_client_id
 skip_service_principal_aad_check = true
}
resource "azurerm_role_assignment" "acr_sp_contributor" {
  scope                = var.acr_id
  role_definition_name = "AcrPull"
  principal_id         = var.aks_client_id
 skip_service_principal_aad_check = true
}
```

### Description / Feedback

I'm not sure if the issue lies with the provider or terraform. I'm logging issues with both. 
Essentially, the script defines the service principal, which I have confirmed is accurate. Terraform outputs a "resource URL" that appears to be a valid azure resource, but you cannot browse it.
Verifying permissions in the UI shows the screenshot below, "identity deleted." 
I can manually assign the permissions with no issues. 
![image](https://user-images.githubusercontent.com/12941311/76434043-26bce280-6383-11ea-999e-3e4edb59536a.png)

**Comment by aristosvo** [comment]
It probably needs the object id of the service principal. It's really a mess and I'm always confused which one should be used where, but after trying the options you'll figure it out. I'm not sure if it's the fault of Azure or the Azure TF provider, but changes like this will trigger probably a new major version, I don't expect that to happen.

Changing it manually and check the results of a `terraform plan` should work fine here.

**Comment by tombuildsstuff** [comment]
👋🏻

Closing this out since this should be fixed by using the Object ID rather than the Application ID, as @aristosvo has mentioned above - however should that not work you should be able to get further assistance for this using [one of the community resources](https://discuss.hashicorp.com)

Thanks!
