### ISSUE TITLE
Link to examples page broken for azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by thehunmonkgroup** [terraform-providers/terraform-provider-azurerm#6070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

Visiting the examples link at https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html should take you to the repository examples.

### Actual Behavior

404 page.

I believe the correct link address is: https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/virtual-machines/linux

**Comment by njuCZ** [comment]
It seems I can open the examples link successfully, there is no problems

**Comment by thehunmonkgroup** [comment]
It appears to me that the link address has been updated and is now working.
