### ISSUE TITLE
403 Authorization Failed when using azurerm_management_lock

### ISSUE THREAD

**Issue by deyjcode** [terraform-providers/terraform-provider-azurerm#6073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_management_lock`

### Terraform Configuration Files

```hcl
locals {
  rg       = "log-analytics-1"
  location = "eastus2"
  vm_ip_address = "10.10.1.5"
}

resource "azurerm_network_interface" "nic-c-test-dc01-1" {
  name                = "nic-dc01-1"
  location            = local.location
  resource_group_name = local.rg

  ip_configuration {
    name                          = "NicConfiguration1"
    subnet_id                     = azurerm_subnet.subnet-test-01.id
    private_ip_address_allocation = "static"
    private_ip_address            = local.vm_ip_address
  }
}

resource "azurerm_management_lock" "nic-c-test-dc01-1-lock" {
  name       = "nic-c-test-dc01-1-lock"
  scope      = azurerm_network_interface.nic-c-test-dc01-1.id
  lock_level = "ReadOnly"
}
```

### Expected Behavior

Resource should be created.

### Actual Behavior

```cmd
Error: locks.ManagementLocksClient#CreateOrUpdateByScope: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'client-guid' with object id 'client-guid' does not have authorization to 
perform action 'Microsoft.Authorization/locks/write' over scope '/subscriptions/sub-guid/resourceGroups/log-analytics-1/providers/Microsoft.Network/networkInterfaces/nic-dc01-1/providers/Microsoft.Authorization/locks/nic-c-test-dc01-1-lock' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
The client id I am using for Terraform has the ability to create locks.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems you have insufficient permission. I think you need to check if your account is assigned to the Contributor role in your Azure subscription. Seems only the Owner role or User Access Administrator role have the Microsoft.Authorization/*/Write access to assign an AD app to a role. Contributor don’t have the adequate permission.

More details please refer to this doc:https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#check-azure-subscription-permissions

**Comment by deyjcode** [comment]
Good catch. I'll double-check permissions and update the issue with results of test.

**Comment by deyjcode** [comment]
The permissions were the issue! Thanks! Closing issue.
