### ISSUE TITLE
 "tenant_id" isn't a valid UUID ("xxx.onmicrosoft.com"): uuid string is wrong length

### ISSUE THREAD

**Issue by wagnst** [terraform-providers/terraform-provider-azurerm#6075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform v0.12.21`
* `azurerm 1.42.0`

### Affected Resource(s)

* `azurerm_key_vault`
* `azurerm_key_vault_access_policy`

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "myapp" {}

resource "azurerm_key_vault_access_policy" "myapp" {
  vault_name          = azurerm_key_vault.myapp.name
  resource_group_name = azurerm_key_vault.myapp.resource_group_name
  tenant_id           = data.azurerm_client_config.myapp.tenant_id
  object_id           = data.azurerm_client_config.myapp.service_principal_object_id

  key_permissions     = ["create", "delete", "get", "list", "update", "wrapKey", "unwrapKey"]
  secret_permissions  = ["delete", "get", "set"]
...
}
```

### Expected Behavior
`azurerm_client_config` data can be used to pass a valid `tenant_id` to `azurerm_key_vault` resource.

### Actual Behavior
```
Error: "tenant_id" isn't a valid UUID ("xxx.onmicrosoft.com"): uuid string is wrong length

  on .terraform/modules/keyvault/main.tf line 19, in resource "azurerm_key_vault" "main":
  19: resource "azurerm_key_vault" "main" {
```
Instead I get this error, when `azurerm_client_config` output is used. I suspect this could be a bug and may be related to #2103 which seems not have been verified working with TF 0.12.

### References
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/2103

**Comment by njuCZ** [comment]
@wagnst I am sorry I could not reproduce this problem using latest azurerm version. Could you please upgrade the azurerm and have a check?

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if the solution proposed above doesn't work and we'll take another look.

Thanks!
