### ISSUE TITLE
Can't assign azurerm_user_assigned_identity to virtual machines

### ISSUE THREAD

**Issue by jknash** [terraform-providers/terraform-provider-azurerm#6079]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
+ provider.azuread v0.7.0
+ provider.azurerm v2.1.0
+ provider.random v2.2.1
+ provider.vault v2.8.0

### Affected Resource(s)

azurerm_linux_virtual_machine
azurerm_windows_virtual_machine
azurerm_user_assigned_identity

### Terraform Configuration Files
The following code contains an identity block example from a virtual machine and the azurerm_user_assigned_identity resource.  The identity block errors out whether I'm using only SystemAssigned or UserAssigned as well as when I have both in type.  The virtual machine type doesn't matter, either.
```hcl
   identity {
    type = "SystemAssigned, UserAssigned"
    identity_ids = ["azurerm_user_assigned_identity.linmgmt.id"]
  }

resource "azurerm_user_assigned_identity" "linmgmt" {
  resource_group_name = azurerm_resource_group.prd-mgmt.name
  location            = azurerm_resource_group.prd-mgmt.location

  name = "prdMgmtLinmgmt"
}
```

### Expected Behavior

The user assigned identity should be associated with the virtual machine.

### Actual Behavior

No matter what I do, I receive the following error:

Error: Error updating Linux Virtual Machine "linmgmt01" (Resource Group "prd-mgmt01"): compute.VirtualMachinesClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id 'azurerm_user_assigned_identity.linmgmt.id' at path '' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."

### Steps to Reproduce
My Configuration always passes in the plan, but fails when I run apply.

1. `terraform apply`

### Important Factoids

I'm running in an azure sponsorship subscription, but every other resource works just fine. 

### References

None that I can find.

**Comment by ArcturusZhang** [comment]
Hi @jknash thanks for this issue!
I suppose this error is caused by a typo in your config file. `identity_ids = ["azurerm_user_assigned_identity.linmgmt.id"]` should be
```
identity_ids = [azurerm_user_assigned_identity.linmgmt.id]
```
or 
```
identity_ids = ["${azurerm_user_assigned_identity.linmgmt.id}"]
```

**Comment by jknash** [comment]
I will try it again, but I believe I tried both.  I’ll let you know shortly.

________________________________

**Comment by jknash** [comment]
Nope, you're right.  :). Thank you so much!  I just removed the quotes and it worked fine.  Sorry for wasting your time!!

  identity {
    type = "SystemAssigned, UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.consul.id]
  }

**Comment by ArcturusZhang** [comment]
> Nope, you're right. :). Thank you so much! I just removed the quotes and it worked fine. Sorry for wasting your time!!
> 
> identity {
> type = "SystemAssigned, UserAssigned"
> identity_ids = [azurerm_user_assigned_identity.consul.id]
> }

No problem, thanks!
