### ISSUE TITLE
Resource azurerm_cosmosdb_mongo_collection parameter default_ttl_seconds set to -1 doesn't set DefaultTimeToLive in Azure to -1

### ISSUE THREAD

**Issue by khoad** [terraform-providers/terraform-provider-azurerm#6081]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
Terraform v0.12.21
+ provider.azurerm v2.1.0
```

### Affected Resource(s)

* `azurerm_cosmosdb_mongo_collection`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "rg_test"
  location = "eastus2"
}

resource "azurerm_cosmosdb_account" "cosmosdb_account" {
  name                = "test-cosmosdb-account-1"
  location            = "eastus2"
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  consistency_policy {
    consistency_level = "Session"
  }

  geo_location {
      location          = "eastus2"
      failover_priority = 0
  }
}

resource "azurerm_cosmosdb_mongo_database" "cosmosdb_db" {
  name                = "test"
  resource_group_name = azurerm_resource_group.rg.name
  account_name        = "test-cosmosdb-account-1"
}

resource "azurerm_cosmosdb_mongo_collection" "cosmosdb_collection" {
  name                = "documents"
  resource_group_name = azurerm_resource_group.rg.name
  account_name        = "test-cosmosdb-account-1"
  database_name       = "test"

  default_ttl_seconds = "-1"
  shard_key           = "myid"
}
```

### Debug Output

https://gist.github.com/khoad/6bd3adf56a9b2460b0a2fedf2f771733

### Expected Behavior

DefaultTimeToLive set to -1, enabling TTL feature with no explicit TTL specified, [per Azure documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live)

### Actual Behavior

DefaultTimeToLive set to 0, turning TTL feature off

### Steps to Reproduce

1. `terraform apply`

### References

* https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live

**Comment by nohajc** [comment]
I'm not entirely sure this is terraform's fault.

If you configure your cosmosdb collection in azure portal and set ttl to "On (no default)", then the resulting _ts index looks like this:
`{
                "expireAfterSeconds" : -1,
                "v" : 1,
                "key" : {
                        "_ts" : 1
                },
                "name" : "_ts_1",
                "ns" : "dbName.collectionName"
        }`

Per documentation, you should also be able to create the same index in mongo shell like this:
`db.collectionName.createIndex( {"_ts": 1 }, { expireAfterSeconds: -1 } )`

If you do that, however, and inspect the resulting index, you will find out `expireAfterSeconds` was not set:

`{
                "v" : 1,
                "key" : {
                        "_ts" : 1
                },
                "name" : "_ts_1",
                "ns" : "dbName.collectionName"
        }`

The `createIndex` call works fine but only for positive values of `expireAfterSeconds`.

**Comment by nohajc** [comment]
Also, this is partially broken in `az cli`: https://github.com/Azure/azure-cli/issues/13229

There is one command I know of that can set the TTL properly but it's marked deprecated:
`az cosmosdb collection update --name {} --resource-group-name {} --db-name {} --collection-name {} --default-ttl -1`

**Comment by evandropomatti** [comment]
@nohajc I didn't understand your answer. I think what OP is pointing out is the difference between the documentation at Azure and Terraform SDK.

Can we confirm this is a bug?

From the docs:

> Time to Live on a container (set using DefaultTimeToLive):
> 
> - If missing (or set to null), items are not expired automatically.
> - If present and the value is set to "-1", it is equal to infinity, and items don’t expire by default.
> - If present and the value is set to some number "n" – items will expire "n" seconds after their last modified time.

You can set the TTL using Azure CLI with `--ttl`.

**Comment by nohajc** [comment]
> @nohajc I didn't understand your answer. I think what OP is pointing out is the difference between the documentation at Azure and Terraform SDK.
> 
> Can we confirm this is a bug?
> 
> From the docs:
> 
> > Time to Live on a container (set using DefaultTimeToLive):
> > 
> > * If missing (or set to null), items are not expired automatically.
> > * If present and the value is set to "-1", it is equal to infinity, and items don’t expire by default.
> > * If present and the value is set to some number "n" – items will expire "n" seconds after their last modified time.
> 
> You can set the TTL using Azure CLI with `--ttl`.

No, I suggested this is a bug in azure. OP is not pointing out difference in documentation but the fact the TTL -1 setting was not applied properly. I'm not sure how it is implemented in terraform but when I failed to set this via terraform I was also having trouble doing it by other means (such as mongo shell script or one variant of az cli command) which all failed except the one deprecated command I listed above.

**Comment by nohajc** [comment]
Although the wording could be changed to make it explicit that -1 enables TTL with no default value whereas with null/0/none TTL is disabled globally and per-document TTLs won't have any effect.
