### ISSUE TITLE
azurerm_data_factory_integration_runtime_managed catalog_info pricing_tier does not handle values other than Basic

### ISSUE THREAD

**Issue by JoeriMaez** [terraform-providers/terraform-provider-azurerm#6088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_data_factory_integration_runtime_managed

The azurerm_data_factory_integration_runtime_managed resource takes the following values according to the documentation and by my tests. 

Basic, Standard, Premium and PremiumRS

Azure takes  the following values

Basic, S0, S1, S2, ..., P1, P2, P3, ... 

When entering a valid terraform value like Standard we get

'catalogPricingTier' property is invalid. Code : 40804, Message : The specified service objective 'Standard' is invalid.

When entering an invalid terraform value but a valid Azure value the deployment already fails during validation. 

### Expected Behavior

The resourceshould allow more and correct values to be passed.

### Actual Behavior

The module does not allow this and other values than Basic are not processed correctly. 

### Steps to Reproduce

Deploy the terraform resource with a correct value (S1, S2, P2, ...) other than Basic

**Comment by r0bnet** [comment]
Hey @JoeriMaez,
back then i was developing this feature so i had quickly a look into it. You're right, in the portal there are now different values for the pricing tier but not yet in the TF resource (not not in the [API documentation](https://docs.microsoft.com/en-us/rest/api/datafactory/integrationruntimes/createorupdate#integrationruntimessiscatalogpricingtier)). Currently we are using API version `2018-06-01` for the data factory. In order to use the new values you mentioned we'd need to upgrade to `2017-09-01-preview`. In that version the pricing tier is not constrained to `Basic`, `Standard`, `Premium` and `PremiumRS`.

Strange thing here is that it already fails with the current API version. Maybe they introduced a breaking change here? 🤔

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume this issue has been fixed from service side since I cannot repro it anymore with below tfconfig in latest azurerm. Could you have a try below tf config to check if the issue still exists? Thanks.

```
provider "azurerm" {
  features {}
  version = "2.20.0"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-df-test01"
  location = "eastus2"
}

resource "azurerm_data_factory" "test" {
  name                = "acctestdfirmtest01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_sql_server" "test" {
  name                         = "acctestsqltest01"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "ssis_catalog_testn"
  administrator_login_password = "ab-s4cret-p4ssword!"
}

resource "azurerm_data_factory_integration_runtime_managed" "test" {
  name                = "managed-integration-runtime-test01"
  data_factory_name   = azurerm_data_factory.test.name
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  node_size = "Standard_D8_v3"

  catalog_info {
    server_endpoint        = azurerm_sql_server.test.fully_qualified_domain_name
    administrator_login    = "ssis_catalog_testn"
    administrator_password = "ab-s4cret-p4ssword!"
    pricing_tier           = "Standard"
  }
}
```

**Comment by tombuildsstuff** [comment]
Closing since we've not heard back here - if you're still able to replicate this with the latest version of Terraform please let us know and we'll take another look.
