### ISSUE TITLE
Bug: It is not possible to create Static (standard SKU) IPv6 addresses

### ISSUE THREAD

**Issue by TVH7** [terraform-providers/terraform-provider-azurerm#6090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.12.21

### Affected Resource(s)

* `azurerm_2.0.0`
* `azurerm_public_ip`

### Terraform Configuration Files

```hcl
 resource "azurerm_public_ip" "ipv6" {
   depends_on = [azurerm_kubernetes_cluster.k8s]
   name                = "${var.aks_cluster_name}-lb01-ipv6"
   resource_group_name = azurerm_kubernetes_cluster.k8s.node_resource_group
   location            = azurerm_resource_group.k8s.location
   sku                 = "Standard"
   allocation_method   = "Static"
   ip_version          = "IPv6"
 }
```

### Debug Output

https://gist.github.com/TVH7/c74c7c4df438795994fd50fa8b8e0cc0

### Panic Output

https://gist.github.com/TVH7/c74c7c4df438795994fd50fa8b8e0cc0

### Expected Behavior

When creating IPv6 Addresses with specific SKU's you have the following options: 

Standard SKU: Only static IPv6 IP addresses are allowed. 
Basic SKU: Only dynamic IPv6 IP Addresses are allowed. 

However, at the moment terraform only allows to create Dynamic IP addresses for IPv6 which is not working with the Standard SKU type, thus the creation of the object fails. 

### Actual Behavior

We get an error saying: Cannot specify publicIpAllocationMethod as Static for IPv6 PublicIp, this is also described in the manual of the Azurerm IP address terraform object but this is only correct when working with the Basic type of IP addresses, it is not valid for the Standard SKU type. 

Thus we can conclude that terraform's support for Standard SKU type IPv6 is broken at the moment. 

### Steps to Reproduce

1. Create a IPv6 address with SKU=Standard and allocation_type="static" 
2. You will receive an error message stating that it is not possible to do so. 
3. Now try the same with SKU=Standard and allocation_type="Dynamic" and you will also receive an error message as you can only create dynamic SKU type IPv6 addresses. 

### Important Factoids
None. 

### References

https://www.terraform.io/docs/providers/azurerm/r/public_ip.html

* #0000

**Comment by fabianofranz** [comment]
PR to fix this issue: https://github.com/terraform-providers/terraform-provider-azurerm/pull/6140
