### ISSUE TITLE
Error to create blob from source file 

### ISSUE THREAD

**Issue by RyanLWilliams** [terraform-providers/terraform-provider-azurerm#6092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
+ provider.azurerm v1.44.0

### Affected Resource(s)

"azurerm_storage_blob"

### Terraform Configuration Files

```hcl
main.tf
`resource "azurerm_resource_group" "rg-wvd-001" {
  name     = "${var.businessunit}-${var.environment}-${lookup(var.region, var.secondaryregion)}-WVD-001"
  location = var.secondaryregion
}

// Storage Account for build scripts
resource "azurerm_storage_account" "st-buildscripts-001" {
  name                     = lower("${var.businessunit}${var.environment}${lookup(var.region, var.primaryregion)}stbuildscripts001")
  location                 = var.secondaryregion
  resource_group_name      = azurerm_resource_group.rg-wvd-001.name
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "container-st-buildscripts-001" {
  name                  = "build-scripts"
  storage_account_name  = azurerm_storage_account.st-buildscripts-001.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "blob-powershellscript-formatrawdisks" {
  name                   = "FormatRawDisks.ps1"
  storage_account_name   = azurerm_storage_account.st-buildscripts-001.name
  storage_container_name = azurerm_storage_container.container-st-buildscripts-001.name
  type                   = "Page"
  source                 = "./Scripts/FormatRawDisks.ps1"
}`

variables.tf
`variable "businessunit" {
  type = string
}

variable "environment" {
  type = string
}

variable "primaryregion" {
  type    = string
  default = "westeurope"
}

variable "secondaryregion" {
  type    = string
  default = "westeurope"
}

variable "region" {
  default = {
    westeurope  = "WE"
    northeurope = "NE"
  }
}
```

### Expected Behavior

Blob created from source file

### Actual Behavior

Error: Error creating Blob "FormatRawDisks.ps1" (Container "build-scripts" / Account "rwdtwestbuildscripts001"): Error PutPageBlob: blobs.Client#PutPageBlob: Invalid input: `input.BlobContentLengthBytes` must be aligned to a 512-byte boundary.

### Steps to Reproduce

1. `terraform apply`

**Comment by RyanLWilliams** [comment]
Have also tested with provider.azurerm v2.0.0 and have the same issue

**Comment by DSakura207** [comment]
Your configuration file specified the blob as page blob. Page blob has to be aligned to a 512-byte boundary.
https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-page-blobs-only
