### ISSUE TITLE
Feature Request: Logic App Resource

### ISSUE THREAD

**Issue by scottrangerio** [terraform-providers/terraform-provider-azurerm#610]
Hi there!

It would be great to see support for Azure Logic Apps (https://azure.microsoft.com/en-gb/services/logic-apps/) via a new resource.

**Comment by auberryberry** [comment]
Just want to say thank you for this @tombuildsstuff, being able to orchestrate logic apps with terra is a massive win for me!

**Comment by rifaterdemsahin** [comment]
any updates ?

**Comment by tombuildsstuff** [comment]
@rifaterdemsahin this shipped in v1.10.0 of the AzureRM Provider: https://www.terraform.io/docs/providers/azurerm/r/logic_app_workflow.html
