### ISSUE TITLE
Removing 0.0.0.0 from Azure SQL firewall doesn't disable "AllowAzureServices" option

### ISSUE THREAD

**Issue by griogar** [terraform-providers/terraform-provider-azurerm#6109]
When removing the 0.0.0.0 rule from an existing Azure SQL server firewall rule set, the "Allow Azure Services" option remains enabled.

```variable "sql_custom_rules" {
  description = "List of custom IPs to include in the SQL Server firewall rules"
  type = list(object({
    name     = string
    start_ip = string
    end_ip   = string
  }))
  default = []
}

**Comment by jlt1267** [comment]
Calling the DELETE method on the API will disable this option:
`https://management.azure.com/subscriptions/{tenantId}/resourceGroups/{resourceGroup}/providers/Microsoft.Sql/servers/{serverName/firewallrules/AllowAllWindowsAzureIps?api-version=2019-06-01-preview`

**Comment by yupwei68** [comment]
Hi @griogar , Thanks for opening this issue. But I have problems in reproducing this error. For me, destroying resource `azurerm_sql_firewall_rule` with `start_ip_address` and `end_ip_address` of "0.0.0.0" will disable `Allow Azure services and resources to access this server`

**Comment by yupwei68** [comment]
I suppose you mean that destroying the resource bellow will not disable `Allow Azure services and resources to access this server`, which I can not reproduce it.
```
resource "azurerm_sql_firewall_rule" "example" {
  name                = "FirewallRule1"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_sql_server.example.name
  start_ip_address    = "0.0.0.0"
  end_ip_address      = "0.0.0.0"
}
```

**Comment by mybayern1974** [comment]
Hi @griogar 

Per yupwei68's investigation, may we close this issue for it cannot repro? Feel free to reopen it if things still repro at your side, and if so please provide more contexts if there are to help repro. Thank you.
