### ISSUE TITLE
Support for adding Azure AD admin user on Azure Database for PostgreSQL server

### ISSUE THREAD

**Issue by charmon79** [terraform-providers/terraform-provider-azurerm#6110]
Azure Database for PostgreSQL supports adding an Azure AD administrator account for the PostgreSQL server, but the Azure provider for Terraform doesn't have any facility for this. There needs to be an `azurerm_postgresql_...` resource equivalent to `azurerm_sql_active_directory_administrator`.

Relevant MS docs: https://docs.microsoft.com/en-us/azure/postgresql/howto-configure-sign-in-aad-authentication

**Comment by tzylla** [comment]
This would be a great addition to the module, we require to set AD admin user through terraform

**Comment by evertonmc** [comment]
hey @katbyte is that planned for the upcomming versions? It is currently not possible to do that even with local-exec az-cli.

**Comment by evertonmc** [comment]
#7411 implementation ready for review @katbyte
