### ISSUE TITLE
azurerm_storage_account_customer_managed_key: Managed Service Identity (MSI) is not set for this account.

### ISSUE THREAD

**Issue by jaredledvina** [terraform-providers/terraform-provider-azurerm#6111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 0.12.23
* AzureRM Provider version: 2.0.0

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "main" {
  name                = var.keyvault_name
  resource_group_name = var.resource_group_name
  location            = var.location
  tenant_id           = var.tenant_id

  sku_name = "premium"

  purge_protection_enabled = var.purge_protection_enabled
  soft_delete_enabled      = var.soft_delete_enabled

  enabled_for_disk_encryption = true
}

resource "azurerm_key_vault_key" "storage" {
  name         = "storage-encrypt-key"
  key_vault_id = azurerm_key_vault.main.id
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_storage_account" "main" {
  name                      = var.storage_account_name
  resource_group_name       = var.resource_group_name
  location                  = var.location
  account_kind              = var.account_kind
  account_tier              = var.account_tier
  account_replication_type  = var.account_replication_type
  enable_https_traffic_only = true

  network_rules {
    default_action = "Deny"

    ip_rules = concat(
      var.egress_ips,
      var.allowed_ips,
    )

    virtual_network_subnet_ids = var.allowed_subnet_ids
  }
}

resource "azurerm_storage_account_customer_managed_key" "main" {
  storage_account_id = azurerm_storage_account.main.id
  key_vault_id       = azurerm_key_vault.main.id
  key_name           = azurerm_key_vault_key.storage.name
  key_version        = azurerm_key_vault_key.storage.version
}
```

### Description / Feedback

I expect Terraform to not fail when configuration the `azurerm_storage_account_customer_managed_key` instead, this fails with:
```
Error: Error updating Customer Managed Key for Storage Account "devtestacct1234" (Resource Group "dev-test"): storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="MissingMsiHeaders" Message="Managed Service Identity (MSI) is not set for this account."

  on main.tf line 40, in resource "azurerm_storage_account_customer_managed_key" "main":
  40: resource "azurerm_storage_account_customer_managed_key" "main" {
```

However, if we follow the steps outlined in https://github.com/Azure/azure-sdk-for-go/issues/1772#issuecomment-399292516, where in the portal, I manually reconfigure the Storage Account to use the KeyVault key and save that, followed by immediately changing the Storage Account to use Microsoft Managed keys again and saving, Terraform runs without issue and successfully updates the Storage Account to use the configured KeyVault key. 

All in all, it seems that prior to manually reconfiguring a Storage Account via the Portal to use a KeyVault CMK, the API calls Terraform makes fail with `Managed Service Identity (MSI) is not set for this account.`. It's possible this is a misconfiguration with the auth that the provider is doing here but, I'm not entirely sure. 

### References

https://github.com/Azure/azure-sdk-for-go/issues/1772#issuecomment-399292516

**Comment by WodansSon** [comment]
@jaredledvina, thank you for opening this issue. IIRC, looking at this quickly, I think you are missing a few steps when doing this via Terraform, the portal does a lot of work behind the scenes to make this work.

The first think you need to do is create and access policy for **both** the storage account and the service principal that Terraform is running as like this:
  
```
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault_access_policy" "storage" {
  key_vault_id = azurerm_key_vault.example.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_storage_account.example.identity.0.principal_id

  key_permissions    = ["get", "create", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
  secret_permissions = ["get"]
}

resource "azurerm_key_vault_access_policy" "client" {
  key_vault_id = azurerm_key_vault.example.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions    = ["get", "create", "delete", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
  secret_permissions = ["get"]
}

``` 

The last thing i think you will need to do is in your storage account, you need to give it an AzureAD identity like this:
```
resource "azurerm_storage_account" "example" {
 # other SA account properties 

  identity {
    type = "SystemAssigned"
  }
}
```

If you can give that a try and let me know if that works for you.

**Comment by ashrayjain** [comment]
Hey, this fixed the issue for us. Thanks!

**Comment by jaredledvina** [comment]
Thanks so much @WodansSon, that did the trick!
