### ISSUE TITLE
Why PartitionId is required for Event Capture ?

### ISSUE THREAD

**Issue by raksit31667** [terraform-providers/terraform-provider-azurerm#6113]
Quick question about Event Capture on `azurerm_eventhub`.

I am about to enable Azure Event Capturing along with Blob Storage Account for troubleshooting and replaying mechanism purpose. However, it is not possible for me to skip `PartitionId` since it is one of required formats used in `archive_name_format`.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/35745e966495d67590daeb299d9284a1ff59c5d5/azurerm/internal/services/eventhub/resource_arm_eventhub.go#L299-L308

Does anyone know the reason why these components, especially `PartitionId` ? Are there anyway in the future that we are able to leave some fields as optional since `PartitionId` does not contribute anything to my system ?

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After double checked, seems these components are required according by [rest api spec](https://github.com/Azure/azure-rest-api-specs/blob/344eaaa5c7fc77679305cfae95ed070af07f57cf/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2017-04-01/eventhubs.json#L379).
