### ISSUE TITLE
VMSS data disk size validation appears to be inaccurate

### ISSUE THREAD

**Issue by mal** [terraform-providers/terraform-provider-azurerm#6115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 0.12.21
* AzureRM Provider version: 2.1.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine_scale_set` # directly observed
* `azurerm_windows_virtual_machine_scale_set` # inferred based on code

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "test" {
  name = "disk-test"

  [...]

  data_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = 2048
    lun                  = 0
  }

  [...]
}
```

### Panic Output

```hcl
Error: expected data_disk.0.disk_size_gb to be in the range (0 - 1023), got 2048

  on example.tf line 1, in resource "azurerm_linux_virtual_machine_scale_set" "test":
   1: resource "azurerm_linux_virtual_machine_scale_set" "test" {
```

### Expected Behavior

Should have booted a VMSS with instances using 2TiB data disks.

### Actual Behavior

Terraform panicked due to seemingly invalid validation check.

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

Validation rule appears here:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/7066eab51480cad38e2e321211eab222634e2d80/azurerm/internal/services/compute/virtual_machine_scale_set.go#L772

There is a `TODO` on the `lun` parameter defined immediately below about confirming upper bounds (plural) perhaps this also applied to the data disk size and such confirmation fell through the cracks during the 2.0 push?

I've confirmed the validity of the ask by successfully provisioning a VMSS with 32TiB disks via the Azure Portal interface.

**Comment by ArcturusZhang** [comment]
Hi @mal thanks for this issue!
Just had a quick try that on the portal the data disk size should be in range (0, 32TiB) (exclusive)
![image](https://user-images.githubusercontent.com/10554446/88016473-0af9f200-cb56-11ea-8f87-813ba67ca4fb.png)
`32768GiB = 32TiB`
