### ISSUE TITLE
azurerm_firewall_nat_rule_collection translated_address and translated_port validation not working 

### ISSUE THREAD

**Issue by sdcscripts** [terraform-providers/terraform-provider-azurerm#6124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) 

Terraform v0.12.18
+ provider.azurerm v2.0.0

### Affected Resource(s)

azurerm_firewall_nat_rule_collection

### Terraform Configuration Files

```hcl 

resource "azurerm_firewall_nat_rule_collection" "webtospoke1vm" {
  name                = "Allow_port_80_traffic_to_spoke1vm"
  azure_firewall_name = azurerm_firewall.hub.name
  resource_group_name = module.hubnetwork.vnet_rg_name
  priority            = 100
  action              = "Dnat"

  rule {
    name = "Dnat port 80 public to spoke1vm"

    source_addresses = [
      "*"
    ]

    destination_ports = [
      "80"
    ]

    destination_addresses = [
      azurerm_public_ip.firewall.ip_address
    ]

    translated_address = [
      "10.100.1.4"
    ]

    translated_port = [
      "80"
    ]
    protocols = [
      "TCP"
    ]
  }
}
```

### Expected Behavior

Should have created an azurerm nat rule

### Actual Behavior

Error: Incorrect attribute value type

  on azurefirewall.tf line 99, in resource "azurerm_firewall_nat_rule_collection" "webtospoke1vm":
  99:     translated_address = [

Inappropriate value for attribute "translated_address": string required.

Error: Incorrect attribute value type

  on azurefirewall.tf line 103, in resource "azurerm_firewall_nat_rule_collection" "webtospoke1vm":
 103:     translated_port = [

Inappropriate value for attribute "translated_port": string required.

### Steps to Reproduce

1. `terraform apply`

It appears that the translated_address and translated_port do not accept IP \ port number inputs, the validation fails when supplying valid IP address and port to those two properties. 
 
Also noticed that https://www.terraform.io/docs/providers/azurerm/r/firewall_nat_rule_collection.html does not have those fields in the example but it does list them as 'required' ? 

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated, seems you are using list as these two properties' type. Actually these two properties' type are string. So I use below tf config and it can succeed. If you need, you can try below tf config to check whether the issue still exists. And I agree with you for the incorrect example in the doc. I'll make a fix for it.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-fw-test"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvirtnettest"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "AzureFirewallSubnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "acctestpiptest"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_firewall" "test" {
  name                = "testfirewall"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  ip_configuration {
    name                 = "configurationtest"
    subnet_id            = azurerm_subnet.test.id
    public_ip_address_id = azurerm_public_ip.test.id
  }
}

resource "azurerm_firewall_nat_rule_collection" "test" {
  name                = "Allow_port_80_traffic_to_spoke1vm"
  azure_firewall_name = azurerm_firewall.test.name
  resource_group_name = azurerm_resource_group.test.name
  priority            = 100
  action              = "Dnat"

  rule {
    name = "Dnat port 80 public to spoke1vm"

    source_addresses = [
      "*"
    ]

    destination_ports = [
      "80"
    ]

    destination_addresses = [
      azurerm_public_ip.test.ip_address
    ]

    translated_address = "10.100.1.4"

    translated_port = "80"
	
    protocols = [
      "TCP"
    ]
  }
}
```
