### ISSUE TITLE
azurerm_sql_server/extended_auditing_policy signals changed on every run

### ISSUE THREAD

**Issue by bruceharrison1984** [terraform-providers/terraform-provider-azurerm#6130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 0.12.16
* AzureRM Provider version: 2.1.0

### Terraform Configuration Files

```hcl
resource azurerm_sql_server example{
  name                         = "${local.resource_prefix}-sql"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "12.0"
  administrator_login          = random_string.sql_username.result
  administrator_login_password = random_password.sql_password.result

  identity {
    type = "SystemAssigned"
  }

  extended_auditing_policy {
    storage_endpoint           = azurerm_storage_account.example.primary_blob_endpoint
    storage_account_access_key = azurerm_storage_account.example.primary_access_key
    retention_in_days          = 6
  }
}

##output
  + extended_auditing_policy {
      + retention_in_days          = 6
      + storage_account_access_key = (sensitive value)
      + storage_endpoint           = "https://example.blob.core.windows.net/"
    }
```

### Description / Feedback
After adding the `extended_auditing_policy` block to my sql_server resource, Terraform flags it as changed on every run, even though nothing has changed

**Comment by yupwei68** [comment]
Hi @bruceharrison1984 , Could you give your steps to reproduce? Because I could not reproduce it, for steps: `terraform apply`-> `terraform plan`, it shows `No changes`.

**Comment by MaximeMarck** [comment]
I had the same issue even if I am not setting the extended_auditing_policy block in my config.
At each plan/apply, terraform wanted to update its values for:

 ```
- extended_auditing_policy {
          - retention_in_days                       = 0 -> null
          - storage_account_access_key_is_secondary = false -> null
        }
```

As a workaround I have added the extended_auditing_policy to the ignore_changes for now

```
 lifecycle {

    ignore_changes = [
      extended_auditing_policy
    ]
  }
```

**Comment by bruceharrison1984** [comment]
@MaximeMarck I did the same thing, though I don't like having to do it on the chance I want to change it.

@yupwei68 Workflow to reproduce is just running an Apply, and then Applying again. I don't have anything particularly interesting in my template

```terraform
resource azurerm_sql_server cache {
  name                         = "${local.resource_prefix}-sql"
  resource_group_name          = azurerm_resource_group.cache.name
  location                     = azurerm_resource_group.cache.location
  version                      = "12.0"
  administrator_login          = random_string.sql_username.result
  administrator_login_password = random_password.sql_password.result

  identity {
    type = "SystemAssigned"
  }

  extended_auditing_policy {
    storage_endpoint           = azurerm_storage_account.cache.primary_blob_endpoint
    storage_account_access_key = azurerm_storage_account.cache.primary_access_key
    retention_in_days          = 6
  }

  lifecycle {
    ignore_changes = [
      extended_auditing_policy
    ]
  }

  tags = local.default_tags
}
```

**Comment by yupwei68** [comment]
Hi @bruceharrison1984 @MaximeMarck , sorry that I still could not reproduce this error. I have tried in azurerm 2.1 and 2.8. If the bug continue to show up, please catch the log for me

```
$ terraform plan -refresh=false

No changes. Infrastructure is up-to-date.

```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if the solution proposed above doesn't work and we'll take another look.

Thanks!
