### ISSUE TITLE
azurerm_security_center_contact multiple emails fails

### ISSUE THREAD

**Issue by Fernandomatsuo** [terraform-providers/terraform-provider-azurerm#6150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.20
- provider.azurerm v1.41.0

### Affected Resource(s)

* `azurerm_security_center_contact`

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_contact" "sc_contact" {
  email = "xxx@domain.com,yyy@domain.com"
  phone = "+55-11-1234-5678"

  alert_notifications = true
  alerts_to_admins    = true
}
```

### Expected Behavior

Should set security contact email to: xxx@domain.com,yyy@domain.com

### Actual Behavior

Error: Error updating Security Center Contact: security.ContactsClient#Update: Failure responding to request: StatusCode=400 – Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidInputJson" Message="Invalid security contact Email was provided."

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked rest api doc, seems setting multiple emails is not supported yet now.

The related references:
Azure rest api doc: https://docs.microsoft.com/en-us/rest/api/securitycenter/securitycontacts/create#request-body
Latest go sdk: https://github.com/Azure/azure-sdk-for-go/blob/e42f2c5809df82e0e99fcabcced1136d13924d21/services/preview/security/mgmt/v3.0/security/models.go#L6324

**Comment by tombuildsstuff** [comment]
👋 

Since this functionality doesn't appear to be supported by the Azure API at this time, unfortunately we're unable to add support for this - and so whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment, but when the Azure API supports configuring this then we can re-open this and then take another look

Thanks!
