### ISSUE TITLE
Provider produced inconsistent final plan for KeyVault and Function App while updating appsettings

### ISSUE THREAD

**Issue by jeanpaulsmit** [terraform-providers/terraform-provider-azurerm#6155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v1.44.0

### Affected Resource(s)

azurerm_function_app

### Terraform Configuration Files

```hcl

# Configure the provider
provider "azurerm" {
    version = "=1.44.0"
}

# --- Get reference to logged on Azure subscription ---
data "azurerm_client_config" "current" {}

# Create Resource Group 
resource "azurerm_resource_group" "rg" {
  name     = "test-tf-issue-rg"
  location = "westeurope"
}

# --- Storage Account section --
resource "azurerm_storage_account" "saFunctionApp" {
  name                     = "testtfissuesa"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  enable_https_traffic_only= true
}

# --- Key Vault section
# Create Key Vault
resource "azurerm_key_vault" "kv" {
  name                        = "test-tf-issue-kv"
  resource_group_name         = azurerm_resource_group.rg.name
  location                    = azurerm_resource_group.rg.location
  enabled_for_disk_encryption = false
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = "standard"
}
# Set access policy to allow service principal to set the secrets
resource "azurerm_key_vault_access_policy" "kvPermissions" {
  key_vault_id = azurerm_key_vault.kv.id

  tenant_id = data.azurerm_client_config.current.tenant_id
  object_id = data.azurerm_client_config.current.object_id

  secret_permissions = [
    "get",
    "list",
    "set"
  ]
}
# Add secret
resource "azurerm_key_vault_secret" "kvSecretKey" {
  name         = "MyKey"
  value        = "secret-value"
  key_vault_id = azurerm_key_vault.kv.id
}

# Create App Service Plan
resource "azurerm_app_service_plan" "asp" {
  name                = "test-tf-issue-asp"
  location            = "westeurope"
  resource_group_name = "test-tf-issue-rg"

  sku {
      tier = "Basic"
      size = "B1"
    }
}

# Create Function App
resource "azurerm_function_app" "fa" {
  name                      = "test-tf-issue-fa"
  resource_group_name       = azurerm_resource_group.rg.name
  location                  = azurerm_resource_group.rg.location
  app_service_plan_id       = azurerm_app_service_plan.asp.id
  storage_connection_string = azurerm_storage_account.saFunctionApp.primary_connection_string
  version                   = "~3"
  https_only                = true

  # Create identity to be able to read from Key Vault
  identity {
    type = "SystemAssigned"
  }

  site_config {
    use_32_bit_worker_process = false
    always_on = true
    http2_enabled = true
    ftps_state = "Disabled"
  }

  app_settings = {
    "FUNCTIONS_EXTENSION_VERSION"   = "~3"
    "FUNCTIONS_WORKER_RUNTIME"      = "dotnet"
    "WEBSITE_RUN_FROM_PACKAGE"      = "0"
    "MyKey"                         = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.kvSecretKey.id})"
  }
}

```

### Expected Behavior

App settings in the Fuction app is updated with the updated secret value

### Actual Behavior

Apply crashes while updating the app settings with a reference to the new secret value

Error: Provider produced inconsistent final plan

When expanding the plan for azurerm_function_app.fa to include new values
learned so far during apply, provider "registry.terraform.io/-/azurerm"
produced an invalid new value for .app_settings["MyKey"]: was
cty.StringVal("@Microsoft.KeyVault(SecretUri=https://test-tf-issue-kv.vault.azure.net/secrets/MyKey/c90f2439fcc949aa901c62e5d4656201)"),
but now
cty.StringVal("@Microsoft.KeyVault(SecretUri=https://test-tf-issue-kv.vault.azure.net/secrets/MyKey/d64eef28c6384c68a786fb526d5b0e47)").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. Execute `terraform apply` to create Key Vault, secrets and Function App
2. Change value of:  "secret-value"
3. `terraform apply` to make the changes

The configuration provided can reproduce the issue. First run everything works, after updating the secret the error occurs.

* #0000

**Comment by SadokLadhari** [comment]
@jeanpaulsmit I have a similar issue here : #6151 :(

**Comment by yupwei68** [comment]
Hi @jeanpaulsmit , thanks for opening this issue. On fact, due to the limit of Terraform, `Terraform plan` could not identify the changes caused by the field `force new`. In this case, the second `Terraform apply` identify two changes to make:
```
 ~ resource "azurerm_function_app" "fa" {
        app_service_plan_id            = "/subscriptions/XX/resourceGroups/test-tf-issue-rg/providers/Microsoft.Web/serverfarms/test-tf-issue-asp"
      ~ app_settings                   = {
          + "FUNCTIONS_EXTENSION_VERSION" = "~3"
...
 ~ resource "azurerm_key_vault_secret" "kvSecretKey" {
        id           = "https://test-tf-issue-kv.vault.azure.net/secrets/MyKey/XX"
        key_vault_id = "/subscriptions/XX/resourceGroups/test-tf-issue-rg/providers/Microsoft.KeyVault/vaults/test-tf-issue-kv"
        name         = "MyKey"
        tags         = {}
      ~ value        = (sensitive value)
        version      = "XX"
    }
Plan: 0 to add, 2 to change, 0 to destroy.
```
It doesn't identify another change `azurerm_function_app.fa.app_settings.MyKey` needs to be changed too.  That's the cause of the error. 

Despite the error, you could make a third `terraform apply`, it'll change the `azurerm_function_app.fa.app_settings.MyKey` with success.

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment but please let us know if this is still an issue and we'll take another look.

Thanks!
