### ISSUE TITLE
azurerm_sql_database StatusCode=404 -- Original Error: autorest/azure: Service returned an error.

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#6157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
+ provider.azurerm v2.1.0
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_sql_database`

### Terraform Configuration Files
```
provider "azurerm" {
  version = "=2.1.0"

  features {}
}

locals {
  dbs              = ["db1"]
  deploy_secondary = false

  primary_location   = "usgovvirginia"
}

resource "azurerm_resource_group" "group" {
  name     = "db_error"
  location = local.primary_location
}

resource "random_password" "sql_server_password" {
  for_each = toset(local.dbs)
  length   = 32
  special  = true
}

resource "azurerm_sql_server" "sqlserver" {
  for_each                     = toset(local.dbs)
  name                         = format("%s-sqlserver-%s", lower("xyzenv"), lower(each.key))
  resource_group_name          = azurerm_resource_group.group.name
  location                     = azurerm_resource_group.group.location
  version                      = "12.0"
  administrator_login          = format("%s_%s", each.key, "admin")
  administrator_login_password = random_password.sql_server_password[each.key].result
  provisioner "local-exec" {
    command = format("echo fully qualified sql server domain name %s with creds of '%s'", self.fully_qualified_domain_name, random_password.sql_server_password[each.key].result)
  }
}

resource "azurerm_sql_database" "db" {
  for_each = toset(local.dbs)

  name                             = each.key
  resource_group_name              = azurerm_resource_group.group.name
  location                         = azurerm_resource_group.group.location
  server_name                      = azurerm_sql_server.sqlserver[each.key].name
  edition                          = "Standard"
  requested_service_objective_name = "S0"  
}
```

### Expected Behavior

Apply should succeed.

### Actual Behavior

```
Error: Error reading SQL Server xyzenv-sqlserver-db1 Blob Auditing Policies: sql.ExtendedServerBlobAuditingPoliciesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '75406810-xxxx-xxxx-xxxx-e9027e0a0a45' could not be found."
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

- New provider update breaks the azurerm_sql_database resource in USGOV.
- Works fine with provider `2.0.0`

**Comment by ttfjustin** [comment]
Also fails terraform plan, seeing the same here. 

Unsure if it's worth mentioning, but the object I am attempting to plan against is an existing database. Other than what's previously mentioned by OP everything else is the same.

**Comment by msyinjie** [comment]
also failed in Azure Devops and using the provider 2.2.0 create Azure sql server, the error info as below:
Error issuing create/update request for SQL Server "xxx-sql-01" Blob Auditing Policies(Resource Group "xxx-db-rg"): sql.ExtendedServerBlobAuditingPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="SubscriptionNotFound" Message="The subscription '263f665e-xxxxxx-c7653141' could not be found.
back to 2.0.0 provider and delete the extended_auditing_policy code define, it works fine.
