### ISSUE TITLE
Support for cosmos db autopilot container

### ISSUE THREAD

**Issue by StefanSchoof** [terraform-providers/terraform-provider-azurerm#6164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Cosmos DB provides a new autopilot feature. This is currently in preview, but the new stable [2020-03](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-03-01/cosmos-db.json)  API support it.

### New or Affected Resource(s)

* azurerm_cosmosdb_sql_container

### References

* https://docs.microsoft.com/azure/cosmos-db/provision-throughput-autopilot
 * In the API it is called "provisionedThroughputSettings", see https://github.com/Azure/azure-rest-api-specs/pull/8609

**Comment by koalalorenzo** [comment]
Do we have any expected ETA on this?
Is there any way to help with this task?

**Comment by grayzu** [comment]
Hey @koalalorenzo, engineers from MS or HashiCorp are not working on this, yet, and based on the lack of response to this issue, it sounds like the community is not either. If you are still interested in submitting a PR for this, we would welcome it. The only complication that I can foresee is the requirement to upgrade the API as this can be complicated if there are breaking changes in the newer version.

**Comment by Zachery2008** [comment]
It seems an important feature for Terraform keeping update to CosmosDB's new autoscale feature. I want this.

**Comment by mcalik77** [comment]
Any news about autoscaling option with terraform?

**Comment by Zachery2008** [comment]
> Any news about autoscaling option with terraform?

I just walk round it by setting a throughput, and add a lifecycle block in resource "azurerm_cosmosdb_sql_database" to ignore changes to autoscale through the Azure portal. 
```
  lifecycle {
    ignore_changes = [
      throughput
    ]
  }
```

**Comment by marc-sensenich** [comment]
I'm starting the work on this via #7597 to get the Cosmos API up to the most recent version and then with a follow up PR to enable autoscaling throughput

**Comment by mcalik77** [comment]
> > Any news about autoscaling option with terraform?
> 
> I just walk round it by setting a throughput, and add a lifecycle block in resource "azurerm_cosmosdb_sql_database" to ignore changes to autoscale through the Azure portal.
> 
> ```
>   lifecycle {
>     ignore_changes = [
>       throughput
>     ]
>   }
> ```

Can you share sample code? I would like to select autoscale option when I provision cosmosdb and database

**Comment by Zachery2008** [comment]
> Can you share sample code? I would like to select autoscale option when I provision cosmosdb and database

Basically there are two choices: database level or container level. If you set at database level, all containers share the same limit, but since you're going to set to autoscale, setting at database level doesn't hurt anything. I did set at database level. The following is a sample.
```
# Create a database of CosmosDB
resource "azurerm_cosmosdb_sql_database" "db" {
  name                = var.db_name
  resource_group_name = azurerm_cosmosdb_account.db_account.resource_group_name
  account_name        = azurerm_cosmosdb_account.db_account.name

  # Autoscale throughput need to modify through the portal afterwards
  throughput          = 400
 
  lifecycle {
    ignore_changes = [
      throughput
    ]
  }
}
```
After your terraform scripts deployed, you can go to the Azure portal and change database's throughput to autoscale. It will not trigger the replacement since terraform will ignore the change of throughput.

This is just temporary remedy. Marc has started solve the issue.

**Comment by mcalik77** [comment]
> > Can you share sample code? I would like to select autoscale option when I provision cosmosdb and database
> 
> Basically there are two choices: database level or container level. If you set at database level, all containers share the same limit, but since you're going to set to autoscale, setting at database level doesn't hurt anything. I did set at database level. The following is a sample.
> 
> ```
> # Create a database of CosmosDB
> resource "azurerm_cosmosdb_sql_database" "db" {
>   name                = var.db_name
>   resource_group_name = azurerm_cosmosdb_account.db_account.resource_group_name
>   account_name        = azurerm_cosmosdb_account.db_account.name
> 
>   # Autoscale throughput need to modify through the portal afterwards
>   throughput          = 400
>  
>   lifecycle {
>     ignore_changes = [
>       throughput
>     ]
>   }
> }
> ```
> 
> After your terraform scripts deployed, you can go to the Azure portal and change database's throughput to autoscale. It will not trigger the replacement since terraform will ignore the change of throughput.
> 
> This is just temporary remedy. Marc has started solve the issue.

Thanks I though you could do it autoscale. I got your idea. I hope Marc can find the solution quickly we need it as soon as possible otherwise I will go to ARM template route which I dont like JSON solution :)

**Comment by tunminster** [comment]
> ### Community Note
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
> * If you are interested in working on this issue or have submitted a pull request, please leave a comment
> 
> ### Description
> Cosmos DB provides a new autopilot feature. This is currently in preview, but the new stable [2020-03](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-03-01/cosmos-db.json) API support it.
> 
> ### New or Affected Resource(s)
> * azurerm_cosmosdb_sql_container
> 
> ### References
> * https://docs.microsoft.com/azure/cosmos-db/provision-throughput-autopilot
> * In the API it is called "provisionedThroughputSettings", see [Azure/azure-rest-api-specs#8609](https://github.com/Azure/azure-rest-api-specs/pull/8609)

Definitely, it is needed.  would be if we have ETA for this feature.

**Comment by marc-sensenich** [comment]
I've opened the draft PR for autoscaling in https://github.com/terraform-providers/terraform-provider-azurerm/pull/7773. Still some design decisions to work through with a few more to probably come up

**Comment by mcalik77** [comment]
> I've opened the draft PR for autoscaling in #7773. Still some design decisions to work through with a few more to probably come up

Hi Marc, When will you finish this issue? Is there any progress?

**Comment by marc-sensenich** [comment]
@mcalik77 #7773 is open for review
