### ISSUE TITLE
Support for Azure Data Factory Linked Service for Azure Table Storage

### ISSUE THREAD

**Issue by stinkyfriend** [terraform-providers/terraform-provider-azurerm#6174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like support for Data Factory to process data in Azure Table Storage. We will be collecting ~1,000,000 rows of data a day in Table Storage and would like to process this data and require a linked service in order to do this. 

### New or Affected Resource(s)

* azurerm_data_factory_linked_service_table_storage

### References
Here are a couple that already exist: 
https://www.terraform.io/docs/providers/azurerm/r/data_factory.html

Here is the ARM template reference where a type is "AzureTableStorageLinkedService":
https://docs.microsoft.com/en-us/azure/templates/microsoft.datafactory/2018-06-01/factories/linkedservices

Here is another request for Linked Service for Blob Storage [open]:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/6167

Here is where I initially registered my interest [closed]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/5223

**Comment by jbinko** [comment]
@tombuildsstuff:  I guess this can be closed now.

**Comment by tombuildsstuff** [comment]
@jbinko good spot - thanks for the ping :)
