### ISSUE TITLE
Terraform support for point on time server restore for Azure managed PostgreSQL

### ISSUE THREAD

**Issue by singitamkr** [terraform-providers/terraform-provider-azurerm#6180]
Hi,
We are using terraform for our couple cluster deployment for our product in MS Azure. But, in case of managed PostgreSQL, when we do a parallel upgrades we are not able to restore an existing PostgreSQL DB to a new instance with point in time restore option. Azure cli supports the same as below command. Azure managed PostgreSQL server restore (point in time) is not supported in terraform at present.

./az postgres server restore -g DatabaseTestingnPOC -n NewPrimary -s primary --restore-point-in-time "2020-03-17T16:50:30.0000Z"

Can you please help in getting this through terraform.

Thanks best regards
Krishna
Official email - ksingita@cisco.com

**Comment by duaneguthrie** [comment]
to add on here:
azure sql db has https://www.terraform.io/docs/providers/azurerm/r/sql_database.html with "create_mode" = "restore"

we need similar api for PostgreSql https://docs.microsoft.com/en-us/rest/api/postgresql/databases/createorupdate

**Comment by njuCZ** [comment]
I am working on this issue

**Comment by duaneguthrie** [comment]
thanks so much
