### ISSUE TITLE
Authenticating using a Service Principal with a Client Certificate Fails to Run

### ISSUE THREAD

**Issue by pbstrein** [terraform-providers/terraform-provider-azurerm#6181]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.20
+ provider.azurerm v2.0.0

### Affected Resource(s)
Provider block and Authentication
Authenticating using a Service Principal with a Client Certificate [link](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_certificate.html)

### Terraform Configuration Files
This can be reproduced by any configuration file b/c it deals with authentication with a Service Principal using Certificates. 

```hcl
provider "azurerm" {

  version                     = "=2.0.0"
  subscription_id             = "00000000-0000-0000-0000-000000000000"
  client_id                   = "00000000-0000-0000-0000-000000000000"
  client_certificate_path     = "/path/to/cert.pfx"
  client_certificate_password = "Password"
  tenant_id                   = "00000000-0000-0000-0000-000000000000"
}

terraform {
  backend "azurerm" {
    resource_group_name  = "test
    storage_account_name = "testbug"
    container_name       = "tfstate"
    key                  = "testbug.terraform.tfstate"
  }
}
...
```
The same happens for environment variables

### Debug Output
https://gist.github.com/pbstrein/34ce8189fa8064036fb3b40472e8c05b
### Expected Behavior
When authenticating as a service principal using a certificate, I should be able to authenticate, or if I give wrong credentials, errors should be thrown with details.

### Actual Behavior
Terraform does not do any authentication with certificates. It automatically tries to use the credentials from Azure CLI, and if the user is logged out, it fails immediately. 

Note that the correct behavior DOES happen when using a Client Secret (instead of a client cert.) When secrets are used, the provider tries to authenticate with the secret and throws errors if something wrong happens. 

### Steps to Reproduce
1. Run `az logout` to clear any credentials stored by the CLI
2. Go to any terraform file with the provider block above put in, or the environment variables set as detailed [here](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_certificate.html#configuring-the-service-principal-in-terraform)
3. See error stating that a Service Principle cannot be used except in a certain way, and tries to link to a document that does not exist (I put another issue for that [here](https://github.com/hashicorp/go-azure-helpers/issues/50)

### References
#1573 is the issue that brought this issue. As part of it @tombuildsstuff mentioned that it would be released later as a feature. I don't know if something happened and it never got fully released or not because now it won't even run certificate validation even with the right variables set.

**Comment by pbstrein** [comment]
After further investigation, I only run into this issue if I have a remote backend configured in my terraform file. If I remove the remote backend, authentication using the client cert works.  

This [terraform documentation](https://www.terraform.io/docs/backends/types/azurerm.html#example-referencing) states that only supports client secret for backend. If we are allowing client cert authentication for general authentication, it should also be allowed for backend authentication. 


I will update the original issue to include the following backend for reproducibility:

```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "test
    storage_account_name = "testbug"
    container_name       = "tfstate"
    key                  = "testbug.terraform.tfstate"
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @pbstrein 

Thanks for opening this issue.

As you've mentioned at this time Client Certificates aren't supported using the AzureRM Backend - but [there's a PR open tracking support for this](https://github.com/hashicorp/terraform/pull/19606) - we're hoping to spend some time focusing on the AzureRM Backend in the not-too-distant-future.

As this issue is regarding the AzureRM Backend rather than the Azure Provider (which this repo tracks) I'm going to close this issue in favour of the upstream PR which is adding support for this - would you mind subscribing to that PR for updates?

Thanks!
