### ISSUE TITLE
Contents of custom data visible in plan as base64 encoded string

### ISSUE THREAD

**Issue by kazimierzbudzyk** [terraform-providers/terraform-provider-azurerm#6185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform v0.12.20
provider.azurerm v2.0.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  
  custom_data = base64encode(jsonencode({
    "key" = "value"
  }))

  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  admin_ssh_key {
    username   = "adminuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}
```

### Expected Behavior

Custom data not being printed in `terraform plan` output. Which was the behaviour in ARM1.X provider.

### Actual Behavior

ARM2.0 makes contents of custom data print out in plan as base64 encoded string. 
Most likely can be fixed by adding `Sensitive: true` to the schema of custom data field: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/tf/base64/schema.go

### Steps to Reproduce

1. `terraform plan`

**Comment by tombuildsstuff** [comment]
Fixed via #6225
