### ISSUE TITLE
No guidance for ACI deployment into VNet

### ISSUE THREAD

**Issue by tezzigator** [terraform-providers/terraform-provider-azurerm#6186]
### Terraform (and AzureRM Provider) Version
tf 0.12.23
azure 2.2.0

### Affected Resource(s)
azurerm_container_group

### Terraform Configuration Files

  ip_address_type     = "Private"
  network_profile_id = ???

### Expected Behavior

All examples provided, and the docs on terraform.io, assume public ip deployment.  Docs say if you wish to deploy into your Vnet, should use  `ip_address_type     = "Private"` and also set `network_profile_id` but then I can find no info anywhere on how to specify which vnet/subnet/privateIP, etc.

Any quick example on how to deploy into a subnet?

**Comment by markercm** [comment]
I also think better examples would be good.

The answer I found to work are using https://www.terraform.io/docs/providers/azurerm/r/network_profile.html

**Comment by tezzigator** [comment]
Hmm still cannot seem to get it to work.  Now, I can get terraform to create the azurerm_network_profile itself, but then later if I try to create a azurerm_container_group and have its network_profile_id line reference the azurerm_network_profile, I get error `Error: "network_profile_id": conflicts with identity`  I tried referencing with (.id at the end and without, also tried .name

```

resource "azurerm_network_profile" "containersubnet1" {
  name                = "containersubnetprofile1"
  location            = var.loc
  resource_group_name = var.rg

  container_network_interface {
    name = "containernic"

    ip_configuration {
      name      = "containeripconfig"
      subnet_id = var.privatesubnet
    }
  }
}

resource "azurerm_container_group" "signercontainer1" {
  name                = "signercontainergroup1"
  location            = azurerm_network_profile.containersubnet1.location
  resource_group_name = azurerm_network_profile.containersubnet1.resource_group_name
  identity {
    type         = "UserAssigned"
    identity_ids = [var.signer-identity.id]
  }
  container {
    name   = "hello-world"
    image  = "microsoft/aci-helloworld:latest"
    cpu    = "1"
    memory = "0.5"

    ports {
      port     = 443
      protocol = "TCP"
    }
  }
  os_type = "Linux"

  ip_address_type    = "Private"
  network_profile_id = azurerm_network_profile.containersubnet1.id
  tags = var.tags
}
```
was I even on the right track?

**Comment by markercm** [comment]
You are on the right path, there is a caveat in https://www.terraform.io/docs/providers/azurerm/r/container_group.html above network_profile_id that shows it is not compatible with  an ip_address_type of "Private"  so if you loose the Identity block it should run.
