### ISSUE TITLE
azurerm_monitor_metric_alert error Time aggregation must be  one of [Average].

### ISSUE THREAD

**Issue by IgorOrmus** [terraform-providers/terraform-provider-azurerm#6200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20

provider.azurerm v2.0.0 and v2.2.0

### Affected Resource(s)

* azurerm_monitor_metric_alert

### Terraform Configuration Files

```
resource "azurerm_monitor_metric_alert" "this" {
 

  count = length(var.queue_list) * var.enable_queue_alerts 
  name                = "alert-${var.queue_prefix}${element(var.queue_list,count.index)}-activemsg"
  resource_group_name = var.rg_name

  scopes      = ["${var.namespace_id}"]
  description = "[ALERT] [ENV: ${upper(var.environment)}] Active Message count exceeding: ${var.active_message_alert_threshold}"
  auto_mitigate = false 
  tags                = var.tags

  criteria {
    metric_namespace = "Microsoft.ServiceBus/namespaces"
    metric_name      = "ActiveMessages"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = var.active_message_alert_threshold

    dimension {
      name     = "EntityName"
      operator = "Include"
      values   = ["${element(var.queue_list,count.index)}"]
    }
  }
```

### Expected Behavior

Aggregation property should allow `Total`

### Actual Behavior

Error: Error creating or updating metric alert "alert-FLUX_CNS_TO_QUE-activemsg" (resource group "resourcegroupname"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Time aggregation must be 
one of [Average]."

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
This only seems to impact new resource creation as I was able to update existing alerts from Average to Total without issues. 

### References

Similar error to 
* #3039

**Comment by yupwei68** [comment]
Hi @IgorOrmus ,Thanks for opening this issue. Sorry that the service only support average of active messages monitoring. Please refer to https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftservicebusnamespaces.

**Comment by yupwei68** [comment]
Hi @IgorOrmus , as for 
`This only seems to impact new resource creation as I was able to update existing alerts from Average to Total without issues.`
Sorry that I could not reproduce this action. After I create a `azurerm_monitor_metric_alert` with `aggregation` `Average`, I update this resource :
```
      ~ criteria {
          ~ aggregation      = "Average" -> "Total"
            metric_name      = "ActiveMessages"
            metric_namespace = "Microsoft.ServiceBus/namespaces"
            operator         = "GreaterThan"
            threshold        = 30
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
I still get the error:
`Error: Error creating or updating metric alert XXX: insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Time aggregation must be one of [Average]."
`

**Comment by IgorOrmus** [comment]
Hi @yupwei68 and thank you for looking in to this. This must have been a recent change on Microsofts end as I had older alerts deployed via terraform which were using Total as aggregation . As you confirmed I can also no longer replicate the succesful update of existing alerts. Thank you for your help and clarification.
