### ISSUE TITLE
Missing lock_duration property on azurerm_servicebus_queue

### ISSUE THREAD

**Issue by faustos** [terraform-providers/terraform-provider-azurerm#622]
The property for lock_duration is missing for Servicebus Queues (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues)

**Comment by tombuildsstuff** [comment]
Hey @faustos 

Thanks for opening this issue :)

I've opened PR #624 which contains support for setting the LockDuration property on the `azurerm_servicebus_queue` resource which should go out in the next release.

Thanks!
