### ISSUE TITLE
Cannot not set custom webhook payload of azurerm_monitor_scheduled_query_rules_alert

### ISSUE THREAD

**Issue by ArturDorochowicz** [terraform-providers/terraform-provider-azurerm#6232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.21
provider.azurerm 2.2.0

### Affected Resource(s)

* `azurerm_monitor_scheduled_query_rules_alert`

### Terraform Configuration Files

This below is the current example from https://www.terraform.io/docs/providers/azurerm/r/monitor_scheduled_query_rules_alert.html with the only change being `custom_webhook_payload` commented out.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_resource_group" "example" {
  name     = "monitoring-resources"
  location = "West US"
}

resource "azurerm_application_insights" "example" {
  name                = "appinsights"
  location            = var.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

resource "azurerm_application_insights" "example2" {
  name                = "appinsights2"
  location            = var.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

# Example: Alerting Action with result count trigger
resource "azurerm_monitor_scheduled_query_rules_alert" "example" {
  name                = format("%s-queryrule", var.prefix)
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  action {
    action_group           = []
    email_subject          = "Email Header"
# --> custom_webhook_payload = "{}"   
  }
  data_source_id = azurerm_application_insights.example.id
  description    = "Alert when total results cross threshold"
  enabled        = true
  # Count all requests with server error result code grouped into 5-minute bins
  query       = <<-QUERY
  requests
    | where tolong(resultCode) >= 500
    | summarize count() by bin(timestamp, 5m)
  QUERY
  severity    = 1
  frequency   = 5
  time_window = 30
  trigger {
    operator  = "GreaterThan"
    threshold = 3
  }
}
```

### Expected Behavior

When I don't specify `custom_webhook_payload`, I expect the resource to not enable the custom payload and therefore let the default Azure payload be used (as described [here](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-log-webhook#webhook-actions).) 

### Actual Behavior

If `custom_webhook_payload` is not specified in the configuration, the resource still sets it to `"{}"`, which overrides the default payload that Azure would use.

### Steps to Reproduce

1. `terraform apply`

**Comment by Valentyn103** [comment]
The same problem
Terraform 0.12.24
provider.azurerm 2.3.0
