### ISSUE TITLE
Terraform fails recreating manually deleted VMs when these were attached to data disk, leaving state unusable afterwards.

### ISSUE THREAD

**Issue by easimon** [terraform-providers/terraform-provider-azurerm#6245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.2.0
+ provider.tls v2.1.1

### Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_managed_disk`
* `azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.12"
  required_providers {
    azurerm = "~> 2.2"
    tls = "~> 2.1"
  }
}

provider "azurerm" {
  features {}
}

locals {
  location       = "West Europe"
  name_prefix    = "test"
  admin_username = "(REDACTED)"
  admin_password = "(REDACTED)"
  address_prefix = "192.168.242.0/24"
}

resource "azurerm_resource_group" "rg" {
  name     = local.name_prefix
  location = local.location
}

resource "azurerm_linux_virtual_machine" "vm" {
  name                  = "${local.name_prefix}-vm"
  location              = azurerm_resource_group.rg.location
  resource_group_name   = azurerm_resource_group.rg.name
  network_interface_ids = [ azurerm_network_interface.if.id ]
  size                  = "Standard_D2s_v3"

  disable_password_authentication = false
  admin_username        = local.admin_username
  admin_password        = local.admin_password

  os_disk {
    name                 = "${local.name_prefix}-os-disk"
    caching              = "ReadOnly"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = 32
    diff_disk_settings {
      option             = "Local"
    }
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-LTS"
    version   = "latest"
  }
}

resource "azurerm_managed_disk" "data" {
  name                 = "${local.name_prefix}-data"
  location             = azurerm_resource_group.rg.location
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = 4
}

resource "azurerm_virtual_machine_data_disk_attachment" "data_disk_attachment" {
  managed_disk_id    = azurerm_managed_disk.data.id
  virtual_machine_id = azurerm_linux_virtual_machine.vm.id
  lun                = 0
  caching            = "ReadOnly"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "${local.name_prefix}-vnet"
  address_space       = [local.address_prefix]
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  name                 = "${local.name_prefix}-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefix       = local.address_prefix
}

resource "azurerm_network_interface" "if" {
  name                = "${local.name_prefix}-if"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  ip_configuration {
    name                                    = "${local.name_prefix}-ip-config"
    subnet_id                               = azurerm_subnet.subnet.id
    private_ip_address_allocation           = "Dynamic"
  }
}

output "ip_address" {
  value = azurerm_network_interface.if.private_ip_address
}
```

### Debug Output

https://gist.github.com/easimon/f9c13f048b4ea93273474937c82333ec

### Expected Behavior

I created the resources with `terraform apply` on the config above, and then manually deleted a VM from the Azure portal. Afterwards I ran `terraform plan` again.
Expected behaviour: Terraform detects that the machine has been deleted and plans to recreate it. 

### Actual Behavior

Terraform fails to refresh the state of the `azurerm_virtual_machine_data_disk_attachment` and bails out. This terraform state is then unusable, the only way to get out of this situation, is to manually delete the  `azurerm_virtual_machine_data_disk_attachment` from the state file.

### Steps to Reproduce

1. `terraform apply`
1. Delete the VM manually outside terraform, using the portal or az cli
1. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @easimon 

Thanks for opening this issue :)

This bug has been fixed in #6237 and will become available in version 2.3 of the Azure Provider - since the fix for this has been merged I'm going to close this issue for the moment; however I've assigned this to the 2.3 milestone so @hashibot will comment when the release is available.

Thanks!
