### ISSUE TITLE
data azurerm_policy_set_definition.html

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#6251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A resource to look up and reference a existing policy definition set 

### New or Affected Resource(s)

* data.azurerm_policy_set_definition

### Potential Terraform Configuration

```
data "azurerm_policy_set_definition" "example" {
  policy_set_definition_id= "<some-guid>"
}
```

**Comment by ArcturusZhang** [comment]
Hi @rohrerb thanks for this issue!
This is very similar with #6249 , I will work on this too.
