### ISSUE TITLE
Error with "Bypass" property in "network_rules" block of Azure Storage account template

### ISSUE THREAD

**Issue by ravitieto** [terraform-providers/terraform-provider-azurerm#6255]
### Terraform (and AzureRM Provider) Version

Terraform v0.12.0
+ provider.azuread v0.3.1
+ provider.azurerm v1.35.0
+ provider.kubernetes v1.11.1
+ provider.random v2.2.1

### Affected Resource(s)

azurerm_storage_account

### Error description
Error: Incorrect attribute value type

  on ..\..\rgs\audit\main.tf line 11, in resource "azurerm_storage_account" "audit":
  11:   bypass                     = "Azure Services"

Inappropriate value for attribute "bypass": set of string required.

### Steps to Reproduce
 `terraform plan`

**Comment by mbfrahry** [comment]
Hey @ravitieto, you can specify multiple values for bypass so we have it accept a set of strings. The below should get you going again:

```
bypass = ["Azure Services"]
```
