### ISSUE TITLE
Support for Consumtion SKU in api_management Service

### ISSUE THREAD

**Issue by szaher** [terraform-providers/terraform-provider-azurerm#6256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

resource azurerm_api_management sku list is missing Consumption which is available here https://github.com/Azure/azure-sdk-for-go/blob/89b3129aee15cb9fb017e12a1980f2993c609125/profiles/latest/apimanagement/mgmt/apimanagement/models.go#L281 

Can we add that please ?

I think the api management service is missing lots of parameters or needs to be clarified in the documentation!

### New or Affected Resource(s)

* azurerm_api_management

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/apimanagement/resource_arm_api_management.go#L78
* https://github.com/Azure/azure-sdk-for-go/blob/89b3129aee15cb9fb017e12a1980f2993c609125/profiles/latest/apimanagement/mgmt/apimanagement/models.go#L281

**Comment by szaher** [comment]
so this SKU is not available in the currently supported api version 2018-01-01 but it's supported from 2019-01-01. Can we pump the api version ? What do we need to that ?

**Comment by sschmeck** [comment]
There is an existing issue regarding the consumption tier - #2613.
