### ISSUE TITLE
azurerm_storage_blob with dynamic source path get recreated

### ISSUE THREAD

**Issue by miteax** [terraform-providers/terraform-provider-azurerm#6278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.21
+ provider.azurerm v2.0.0

### Affected Resource(s)

* azurerm_storage_blob 

### Terraform Configuration Files

```hcl
resource "azurerm_storage_blob" "uploaded_file" {
  for_each               = {for f in local.files: "${f.environment}.${f.file_name}" => f}
  
  name                   = each.value.file_name
  storage_account_name   = azurerm_storage_account.storage[each.value.environment].name
  storage_container_name = azurerm_storage_container.shared_files[each.value.environment].name
  type                   = "Block"
  source                 = "${path.cwd}/files/${each.value.file_name}"
}
```

### Expected Behavior

When comparing the source, the ${path.cwd} should not be considered as this can change depending on the environment terraform is running - When the code is checked into source control, different people may map to different local folders, also when running from Azure pipelines, the path is dynamic and likely different each time.

### Actual Behavior

The change in source path is causing the resource to be recreated despite the file not having been changed, this example showing where it was previously run from an Azure pipeline then again from a windows developer machine.
```
  # module.av_vn.azurerm_storage_blob.uploaded_file["test.setup.ps1"] must be replaced
-/+ resource "azurerm_storage_blob" "uploaded_file" {
      ~ access_tier            = "Cool" -> (known after apply)
        content_type           = "application/octet-stream"
      ~ id                     = "https://stmyiactest.blob.core.windows.net/files/setup.ps1" -> (known after apply)
      ~ metadata               = {} -> (known after apply)
        name                   = "setup.ps1"
        parallelism            = 8
        size                   = 0
      ~ source                 = "/vsts/agent/_work/26/s/iac/network/files/setup.ps1" -> "D:/git/iac/network/files/setup.ps1" # forces replacement
        storage_account_name   = "stmyiactest"
        storage_container_name = "files"
        type                   = "Block"
      ~ url                    = "https://stmyiactest.blob.core.windows.net/files/setup.ps1" -> (known after apply)
    }
```
This also happens when only running from Azure as the path often changes. The end result is correct as the files are uploaded where they need to be, but there are unnecessary changes made (also stopping outputs from terraform plan/apply from being clean) and it takes time to upload.

**Comment by tombuildsstuff** [comment]
hi @miteax 

Thanks for opening this issue.

As you've mentioned when switching between directories the value or `path.cwd` will change - however there's another value which should provide a more relative path to the module here (`path.module` - [as shown in this example](https://www.terraform.io/docs/configuration/functions/file.html)).

As such I believe it should be possible to fix this by switching to use `path.module` to refer to this directory rather than `path.cwd` - alternatively you should be able to use Terraform's `ignore_changes` functionality to ignore changes to this field after the initial creation, however I'd recommend using the `path.module` approach where possible.

Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by miteax** [comment]
Thanks for the reply @tombuildsstuff 

The problem with ```path.module``` is that it points to the path where the module is defined rather than from where it was called.

An example:
```
git_root
├── this_project
│   ├── network
│   │   ├── main.tf - defines an instance of module "network" with source = "../../shared/network" and other parameters
│   │   ├── files
│   │   |   └── some_file.txt
├── another_project
│   ├── network
│   │   ├── main.tf - defines an instance of module "network" with source = "../../shared/network" and other parameters
│   │   ├── files
│   │   |   └── another_file.txt
├── shared
│   │   ├── network
│   │   |   └── main.tf
```

When running terraform from this_project/network, ```path.cwd``` would give ```/git_root/this_project/network``` but ```path.module``` would give ```/git_root/shared/network```. Using ```path.module``` would need all the files to be stored in the shared network definition which isn't appropriate in this situation.

The only way I can think to get this to work with ```path.module``` is to pass in the current project and/or path as a variable then set the source to something like ```"${path.module}/../../${project_name}/${path}/files/${each.value.file_name}"```. It's not ideal but may be an option as a workaround. Being able to use ```path.cwd``` or another variable that gets the relative path of the calling module would be a much nicer implementation.

```ignore_changes``` isn't really ideal as it would stop actual changes to the file from being deployed.
