### ISSUE TITLE
azurerm_redis_cache: sll in primary and secondary connection string is wrong

### ISSUE THREAD

**Issue by rogersollberger** [terraform-providers/terraform-provider-azurerm#6279]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, i applied this terraform:

resource "azurerm_redis_cache" "redis" {
  name                = var.redis_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  capacity            = 0
  family              = "C"
  sku_name            = "Basic"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  tags = var.resource_tags
}

i also saved the azurerm_redis_cache.redis.primary_connection_string into a key vault.
after apply i saw a difference in the azure portal primary connection string settings in relation to the one stored in keyvault:

on azure portal the value was like: ....ssl=True,....
and in the kevault is was like: ....sll=false....

could it be that this line is wrong in the provider code:
resource_arm_redis_cache.go

`
if props != nil {
		d.Set("primary_connection_string", getRedisConnectionString(*props.HostName, *props.SslPort, *keysResp.PrimaryKey, *props.EnableNonSslPort))
		d.Set("secondary_connection_string", getRedisConnectionString(*props.HostName, *props.SslPort, *keysResp.SecondaryKey, *props.EnableNonSslPort))
`

in my view ssl=True means, that we should use ssl only but this property sais
props.EnableNonSslPort if true it enabled non ssl ports. this does not match for me.

**Comment by sebader** [comment]
same here. On azurerm version 2.3.0
