### ISSUE TITLE
Standard azurerm_eventhub_namespace defaulting to DENY firewall when created

### ISSUE THREAD

**Issue by runecalico** [terraform-providers/terraform-provider-azurerm#6280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.24
+ provider.azurerm v2.3.0
```
### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl

resource "azurerm_eventhub_namespace" "eventhub_namespace" {

  name                     = "testehn"
  resource_group_name      = "rgp-xxx-xx-xxx-xx"
  location                 = "Eastus2"
  sku                      = "standard"
  capacity                 = 2
  auto_inflate_enabled     = true
  maximum_throughput_units = 10
}
output "eventhub_namespace-object" {
  value       = azurerm_eventhub_namespace.eventhub_namespace
}
```

### Debug Output

https://gist.github.com/runecalico/fd55469ec16fc0f83af1788e91a66d32

### Expected Behavior

Terraform should have created a Standard Eventhub Namespace without firewall as the docs say network_rulesets is optional,  and no default value for deny_action is specified in the documentation. 

### Actual Behavior

The eventhub is created with the firewall default_action of deny, which enables the IP firewall with no configuration. The only way to work around it is to explicitly set default_action to "Allow".
The output of the terraform resource clearly shows that it configured the default_action to deny for some reason ..

Is this a bug in Terraform? Is this the default behavior in Azure and the terraform azurerm documentation needs to be updated to reflect?

```
eventhub_namespace-object = {
  "auto_inflate_enabled" = true
  "capacity" = 2
  "default_primary_connection_string" = "Endpoint=sb://testehn.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxx"
  "default_primary_key" = "xxx"
  "default_secondary_connection_string" = "Endpoint=sb://testehn.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xx"
  "default_secondary_key" = "xx"
  "id" = "/subscriptions/xx/resourceGroups/xx/providers/Microsoft.EventHub/namespaces/testehn"
  "location" = "eastus2"
  "maximum_throughput_units" = 10
  "name" = "testehn"
  "network_rulesets" = [
    {
      "default_action" = "Deny"
      "ip_rule" = []
      "virtual_network_rule" = []
    },
  ]
  "resource_group_name" = "xx"
  "sku" = "Standard"
}
```
This output in the debug seems interesting .. (not that I know why it enabled it)
```
2020-03-27T08:21:35.030-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.3.0_x4.exe: X-Ms-Routing-Request-Id: NORTHCENTRALUS:20200327T132136Z:72dbbda7-f411-4f99-9820-fcb1cf010ff0
27T08:21:35.030-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.3.0_x4.exe:
2020-03-27T08:21:35.030-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.3.0_x4.exe: {"id":"/subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.EventHub/namespaces/testehn/networkRuleSets
/default","name":"default","type":"Microsoft.EventHub/Namespaces/NetworkRuleSets","location":"East US 2","properties":{"defaultAction":"Deny","virtualNetworkRules":[],"ipRules":[]}}
2020-03-27T08:21:35.030-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.3.0_x4.exe: [DEBUG] AzureRM Request:
2020-03-27T08:21:35.030-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.3.0_x4.exe: POST /subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.EventHub/namespaces/testehn/AuthorizationRule
s/RootManageSharedAccessKey/listKeys?api-version=2017-04-01 HTTP/1.1
```
### Steps to Reproduce

terraform apply --auto-approve

1. `terraform apply`

### Important Factoids

This is an "normal" Azure Cloud subscription.

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After double checked, service api would return "Deny" as default. So the doc will be updated.
