### ISSUE TITLE
when i am trying to add the extension getting below issue (am using terraform 2.1.0)

### ISSUE THREAD

**Issue by anil88972** [terraform-providers/terraform-provider-azurerm#6281]
The provider provider.azurerm does not support resource type
"azurerm_windows_virtual_machine_extension".

is anyone having any idea?

**Comment by StefanSchoof** [comment]
I think you added a extra windows in the resource name and [azurerm_virtual_machine_extension](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html) is the one you want.

**Comment by katbyte** [comment]
@anil88972, @StefanScherer  is correct. there is no such resource as `azurerm_windows_virtual_machine_extension`, please use the `azurerm_virtual_machine_extension` resource 🙂 

as such i am going to close this. please do let us know if you continue to have problems!

**Comment by anil88972** [comment]
step1:Note: The azurerm_virtual_machine resource has been superseded by the azurerm_linux_virtual_machine and azurerm_windows_virtual_machine resources. The existing azurerm_virtual_machine resource will continue to be available throughout the 2.x releases however is in a feature-frozen state to maintain compatibility - new functionality will instead be added to the azurerm_linux_virtual_machine and azurerm_windows_virtual_machine resources.
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html
spep2: terraform 2.1.0 it won't support azurerm_virtual_machine_extension can you please check once extinction is created but it won't bring the VM in domine

**Comment by StefanSchoof** [comment]
The resource for the VM was renamed. The resource for the extension not.

I think we can help you only if you insert a complete sample.

**Comment by anil88972** [comment]
resource "azurerm_windows_virtual_machine_extension" "MYADJOINEDVMADDE1" {
  name                 = "MYADJOINEDVMADDE1"
  virtual_machine_id   = azurerm_windows_virtual_machine.VM1.id
  publisher            = "Microsoft.Compute"
  type                 = "JsonADDomainExtension"
  type_handler_version = "1.3"
 
  # What the settings mean: https://docs.microsoft.com/en-us/windows/desktop/api/lmjoin/nf-lmjoin-netjoindomain
 
  settings = <<SETTINGS
    {
        "Name": "xxxxxxxxxxx.LOCAL",
        "OUPath": "\"OU=Computers-xxxxxxxxxxxxxxxxx,DC=hcwtestsaas,DC=local\"",
        "User": "xxxxxxxxxxxxxxxxxxxxxxxxx",
        "Restart": "true",
        "Options": "3"
    }
SETTINGS
  protected_settings = <<PROTECTED_SETTINGS
    {
      "Password": "xxxxxxxxxxxxxxxxxxxxxx"
    }
  PROTECTED_SETTINGS
  depends_on = [azurerm_windows_virtual_machine.VM1]
} 
please check with above one

**Comment by StefanSchoof** [comment]
I misread your comment and did not understand, that the extension was installing but unsuccessful.  This means the error is outside of terraform. I think you have better chance to get help of https://stackoverflow.com

**Comment by anil88972** [comment]
ok fine could you please tell me how to bring the VM in domine 
am using terraform 2.1.0 (when am creating VM am using resource azurerm_windows_virtual_machine)
