### ISSUE TITLE
azurerm_private_link_service requires nonsensical parameters when trying to set up private link from VNet to Azure service

### ISSUE THREAD

**Issue by fabiendelpierre** [terraform-providers/terraform-provider-azurerm#6288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm new to Azure and was experimenting with their database SaaS, specifically Postgres, if it matters. We quickly figured out that all Azure DB endpoints are public by default, and also quickly found out about the private endpoint option to further lock down the database at the network level.

The way this works is you tie a private link to one of your Azure subnets, and a private endpoint to the Azure resource you wish to access privately (in my case, a database instance). This uses a private IP address within your subnet, and subsequently the DNS name for your database resolves to that private IP address, when the DNS query comes from within the subnet where the private link exists.

We've tested this and it works fine. Unfortunately, this simple scenario is not supported by Terraform. This is because `azurerm_private_link_service` **requires** a `load_balancer_frontend_ip_configuration_ids` parameter that does not apply here. There is no load balancer involved in my scenario, and we shouldn't have to create a load balancer just to get around this limitation (note I haven't tested that particular thing, and don't know if it would help anyway).

I understand that there is another possible use case for private link where a load balancer comes into play, I'm not too clear on what requirements that scenario satisfies, but I can say with confidence that my use case is different.

### New or Affected Resource(s)

* Existing resources `azurerm_private_link_service` and `azurerm_private_endpoint` (I believe that no change would need to be made to the latter, but both of them are required for what I'm trying to accomplish)

### Potential Terraform Configuration

I used the code from the [docs](https://www.terraform.io/docs/providers/azurerm/r/private_link_service.html) but modified it in the way I would like to use it, which is currently not possible, due to `load_balancer_frontend_ip_configuration_ids` being a required parameter.

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  address_space       = ["10.5.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                                          = "example-subnet"
  resource_group_name                           = azurerm_resource_group.example.name
  virtual_network_name                          = azurerm_virtual_network.example.name
  address_prefix                                = "10.5.1.0/24"
  enforce_private_link_service_network_policies = true
}

resource "azurerm_private_link_service" "example" {
  name                = "example-privatelink"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  auto_approval_subscription_ids = ["00000000-0000-0000-0000-000000000000"]
  visibility_subscription_ids    = ["00000000-0000-0000-0000-000000000000"]

  nat_ip_configuration {
    name      = "primary"
    subnet_id = azurerm_subnet.example.id
    primary   = true
  }
}

resource "azurerm_private_endpoint" "example" {
  name                = "example-endpoint"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  subnet_id           = azurerm_subnet.endpoint.id

  private_service_connection {
    name                           = "example-privateserviceconnection"
    private_connection_resource_id = azurerm_private_link_service.example.id
    subresource_names              = ["postgresqlServer"] # just an example that applies to my use case
    is_manual_connection           = false
  }
}
```

### References

- https://docs.microsoft.com/en-us/azure/postgresql/concepts-data-access-and-security-private-link
- https://docs.microsoft.com/en-us/azure/postgresql/howto-configure-privatelink-portal

**Comment by dwizzle204** [comment]
Drop this resource:
resource "azurerm_private_link_service" "example"


Change this to the id of your db

azurerm_private_endpoint:
private_connection_resource_id = azurerm_postgresql_server.example.id

**Comment by fabiendelpierre** [comment]
Thanks a lot @dwizzle204 -- that worked fine! 

I had to do this before it worked: https://docs.microsoft.com/en-us/azure/private-link/disable-private-endpoint-network-policy
