### ISSUE TITLE
Feature Request/Offer: Add support for some data processing and analytics services

### ISSUE THREAD

**Issue by thsutton** [terraform-providers/terraform-provider-azurerm#629]
I'm working for a client who already uses Terraform for a bunch of traditional infrastructure stuff and now has a need to manage some of the Azure managed services that aren't already supported by this provider.

Assuming the client approves my making open-source contributions on this project, would the maintainers be open to accepting PRs for at least the following services?

- `azurerm_streamanalytics_job` - use RM to manage a Stream Analytics job
- `azurerm_datalake_store_account` - use RM to manage a Data Lake Store account
- `azurerm_datalake_store_directory` - use WebHDFS to manage a directory and ACL in a Data Lake Store

Plus some additions to existing resources:

- `azurerm_eventhub` - add support for [capturing messages](https://docs.microsoft.com/en-us/rest/api/eventhub/EventHubs/CreateOrUpdate#definitions_capturedescription)

**Comment by achandmsft** [comment]
Hi Thomas,
We would be absolutely delighted to accept your PRs for the above services. These are not in our next milestone, so definitely something that we will appreciate contributions to. Please do confirm if you will be doing this, so we can prioritize reviewing the same. 

For EventHub, @tombuildsstuff is currently working on this, so please confirm with him that he is not working on this support so you don't end up duplicating this work. 

I would also like to have a brief call with you to understand your scenario and requirements. Please email me at achand at microsoft dot com, so I can setup a call with you. 

Thanks,
Arun Chandrasekhar
Principal Program Manager
Azure OSS Integrations (Microsoft)

**Comment by thsutton** [comment]
Hi @achandmsft, I'm not working on this project any more but the work is on-going. @rickerbh, @joshagudo, @afsalthaj, @rodneyjoyce, @leigh-perry might have the time to get our changes into a fit state to send a PR upstream.

**Comment by rodneyjoyce** [comment]
Hi Arun, I'll send you a mail to discuss... (we're actively working on this)

**Comment by achandmsft** [comment]
@rodneyjoyce any progress on this front?

**Comment by AodbeKulick** [comment]
I would also like to encourage support and be extraordinarily grateful for data lake storage support.  If there is any preliminary support, partial or otherwise, I could attempt a contribution with that as a starting point.

**Comment by iharrington** [comment]
Any headway on getting `azurerm_streamanalytics_job` working?

**Comment by thsutton** [comment]
It's been a long time since I left the project I worked on this for. I'll dig the code out and try to get a PR (probably with insufficient testing) submitted tonight.

**Comment by iharrington** [comment]
@thsutton I found this also https://github.com/terraform-providers/terraform-provider-azurerm/pull/888

**Comment by tombuildsstuff** [comment]
👋 hey @thsutton 

Apologies for the delayed reply here!

I appreciate this was opened a while ago, but to add to @achandmsft comments - we're definitely interested in PR's, so thanks for the offer :)

Taking a look through it appears that these features are now supported and as such whilst I'd like to thank you for the offer here, I'm going to close this issue for the moment.

Thanks!
