### ISSUE TITLE
Manually specifying recursive nameservers for propagation checks doesn't work as expected

### ISSUE THREAD

**Issue by harsh-vm** [terraform-providers/terraform-provider-azurerm#6291]
We are consuming acme provider alongside azure provider to get Let's Encrypt certificate provisioned. This was working absolutely fine till Thursday (26ht March) but stopped working now because DNS propagation check looks like timing out. We are using Azure public DNS service for our custom domains and they are resolvable but during certificate provisioning the DNS propagation check has started failing for all/few subject alternative names from Microsoft servers.

Hence, we tried to override the recursive nameserver to be something different from the default as per the documentation found [here](https://www.terraform.io/docs/providers/acme/r/certificate.html#manually-specifying-recursive-nameservers-for-propagation-checks). I tried the same value as in example - recursive_nameservers = ["8.8.8.8:53"]

But, the DNS resolution was still handled by default DNS challenge configuration which in our case is 'azure'.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform version - 0.11.14
azurerm version - 1.44.0
acme version - 1.5

### Affected Resource(s)

* `acme_certificate`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
```
resource "tls_private_key" "acme_account_private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "acme_account" {
  account_key_pem = "${tls_private_key.acme_account_private_key.private_key_pem}"
  email_address   = "${var.acme_email_address}"
}

resource "random_string" "pfx_password_sample_cert" {
  length  = 32
  special = true
}

resource "acme_certificate" "sample" {
  depends_on = ["acme_registration.acme_account"]

  account_key_pem = "${acme_registration.acme_account.account_key_pem}"
  common_name     = "${var.common_name}.${var.base_domain_nname}"

  subject_alternative_names = [
    "*.${var.common_name}.${var.base_domain_nname}",
    "*.${var.string01}.${var.base_domain_nname}",
    "*.${var.string02}.${var.base_domain_nname}",   
    "*.${var.string03}.${var.common_name}.${var.base_domain_nname}",
    "*.${var.string03}.${var.string02}.${var.base_domain_nname}",    
  ]

  certificate_p12_password = "${random_string.pfx_password_sample_cert.result}"

  recursive_nameservers = ["8.8.8.8:53"]
  dns_challenge {
    provider = "azure"
    config {
      AZURE_RESOURCE_GROUP = "${var.dns_zone_resource_group_name}"
    }
  }
}
```
### Debug Output

```
1 error occurred:
	* module.<module_name>.acme_certificate.sample: 1 error occurred:
	* acme_certificate.sample: error creating certificate: acme: Error -> One or more domains had a problem:
[*.string01.<base_domain_nname>] time limit exceeded: last error: read udp 10.240.0.33:55807->192.100.102.3:53: i/o timeout
[*.string02.<base_domain_nname>] time limit exceeded: last error: read udp 10.240.0.33:39834->192.100.102.3:53: i/o timeout
```

### Expected Behavior

While **recursive_nameserver** is mentioned in the config, the propagation check should have happened with 8.8.8.8:53. With the debug output mentioned, it looks like the azure dns resolution server is being hit even after adopting overriding method.

### Actual Behavior

The following action : **read udp 10.240.0.33:55807->192.100.102.3:53 **
suggests, overriding is not working and DNS resolution is still being going through Microsoft servers.

### Steps to Reproduce

`pre-requisite: You need to have a public Azure DNS configured for custom domains (reference [here](https://docs.microsoft.com/en-us/azure/dns/dns-getstarted-portal)).`

Have the Terraform configuration for the following with above provided versions:

1. `Host a sample app service on Azure (windows/linux)`
2. `Consume your public Azure DNS service to configure a custom domain for the app`
3. `Obtain a Let's Encrypt wildcard certificate for the site with multiple Subject Alternative Names (SAN) and try to attach the cert to app service.`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @harsh-vm 

Thanks for opening this issue.

Taking a quick look into this it appears this is a connectivity issue rather than an issue with Terraform specifically here: `read udp 10.240.0.33:55807->192.100.102.3:53: i/o timeout` - as such I believe this is likely a transient issue - would you be able to retry and see if this persists?

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

As such I'm going to close this issue for the moment, but if this persists I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by harsh-vm** [comment]
Thank you, @tombuildsstuff for coming back on this. The pointer you have given above in your comment about transient issue is possibly true. 

But, I logged this issue with more of impact on `acme_certificate` where I tried to override DNS resolver as per the documentation with recursive_nameservers and that didn't work. So, thought it is worth logging issue here. May be this issue should go in `acme provider` forum?

**Comment by eocern** [comment]
Hey harsh-vm did you report that somewhere else ? Actually I hit the same issue - I am in a restricted network, I need to set "recursive_nameservers" to our DNS but the terraform resource "acme_certificate" keeps on ignoring that recursive_nameservers value I have specified and even the documentation claims that this should be in dns_challenge block "To override this default behavior, supply the recursive_nameservers to use as a list in host:port form within the dns_challenge block:" but it is not supported there - it needs to be set outside the dns_challenge block - i think somebody did not finish his homework and forgot to implement that as part of the dns_challenge.

**Comment by harsh-vm** [comment]
Hey @eocern, sorry to come back bit late on this. Ya, I haven't logged this issue anywhere else. But you are right, somebody didn't finish the job well unless I am missing to understand the actual behaviour of this field. As far as documentation goes, really misguides! fyi, the original issue with default name server resolution still persists. Not sure where to log that bug :(

**Comment by eocern** [comment]
Hi @harsh-vm I opened an issue at https://github.com/terraform-providers/terraform-provider-acme/issues/104 Lets see how it goes there :-)
