### ISSUE TITLE
Container Registry doesn't detect changes to network_rule_set

### ISSUE THREAD

**Issue by elsesiy** [terraform-providers/terraform-provider-azurerm#6302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `azurerm v1.43.0`

### Affected Resource(s)

* `azurerm_container_registry`

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "acr" {
  name                = "testregistry"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "Premium"
  admin_enabled       = false

  network_rule_set {
    default_action = "Deny"

    ip_rule {
      action   = "Allow"
      ip_range = var.a_cidr
    }

    virtual_network {
      action    = "Allow"
      subnet_id = var.a_subnet
    }
  }
}
```

```hcl
resource "azurerm_container_registry" "acr" {
  name                = "testregistry"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "Premium"
  admin_enabled       = false
}
```

### Expected Behavior

Changing from the first code snippet to the second (hence removing the `network_rule_set`) should trigger a change in place.

### Actual Behavior

No change detected

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated, I think it's by design since `network_rule_set` only can be switched between "Allow all networks" and "Deny some networks" once you set them. If you want to remove existing network rule settings, please follow below tfconfig. Thanks.
```
resource "azurerm_container_registry" "test" {
  name                = "testAccCrneil"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "Premium"
  admin_enabled       = false

  network_rule_set {
    default_action = "Deny"
  }
}
```

**Comment by ArcturusZhang** [comment]
Hi @neil-yechenwei could you please open a PR to modify the document accordingly?
