### ISSUE TITLE
Documentation - importance of Storage vs StorageV2

### ISSUE THREAD

**Issue by billabongrob** [terraform-providers/terraform-provider-azurerm#6303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.16
2.3

### Affected Resource(s)

* `azurerm_storage_account`

### Expected Behavior

Documentation would highlight the changes in the the azurerm_storage_account would force recreate the storage accounts.  We had Terraform in our CI/CD build and it wasn't checking for deletions - Our fault - and the storage accounts in our pipeline were all destroyed.  

> The default value for the field account_kind has changed from Storage to StorageV2.
tucked way down at the bottom of the page.

### Actual Behavior

Note on the upgrade page which default settings are being changed that might cause your resources to be recreated if default settings are used.  

### References
[2.0 Upgrade docs](https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html)

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems the [documentation ](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#account_kind)has been updated.

**Comment by katbyte** [comment]
I'm going to close this as its been nearly a year without a response, please do let us know if this is still an issue for you!
