### ISSUE TITLE
Terraform state off when provisioning failed due to Azure capacity problems.

### ISSUE THREAD

**Issue by raidlman** [terraform-providers/terraform-provider-azurerm#6306]
### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.8
+ provider.archive v1.3.0
+ provider.azuread v0.7.0
+ provider.azurerm v2.1.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

Snip

```hcl
resource "azurerm_virtual_machine" "azrm_vm" {
...
  location = "westeurope"
  vm_size  = "Standard_D2as_v4"
  storage_os_disk {
    name              = "os_disk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "PremiumLRS"
  }
  storage_data_disk {
    name          = "data_disk1"
    caching       = "ReadOnly"
    create_option = "Empty"
    lun           = 0
    disk_size_gb  = 250
  }
...
}
```

### Expected Behavior

If Terraform provisioning fails due to Azure capacity issues, all created resources that failed are either destroyed (removed from Azure) or present in the current Terraform state.

Terraform should track all resources it created regardless of the "running state". If a machine can not be started due to capacity problems, Terraform should maybe issues a warning instead of an error.

### Actual Behavior

Terraform does not track the resources created for the virtual machine (vm and disks) if deployment fails due to Azure capacity problems. A terraform re-apply fails since virtual machine is already present (although not functional).

Failed message on Azure portal:

```
Provisioning state
Provisioning failed. Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance. AllocationFailed
Provisioning state error code
ProvisioningState/failed/AllocationFailed

```

Can either be fixed by deleting resources (vm, disks) in Azure portal and doing another `terraform apply` or by doing an `terraform import` of the vm resource.

### Steps to Reproduce

1. Terraform apply

```
$ terraform apply
...
Error: Code="AllocationFailed" Message="Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance"

  on modules/virtual_machine/main.tf line 58, in resource "azurerm_virtual_machine" "azrm_vm":
  58: resource "azurerm_virtual_machine" "azrm_vm" {
```

2. Apply again

```
$ terraform apply
[...]
azurerm_virtual_machine.azrm_vm: Creating...

Error: A resource with the ID "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/azrm_rg/providers/Microsoft.Compute/virtualMachines/azrm_vm" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_machine" for more information.

  on modules/virtual_machine/main.tf line 58, in resource "azurerm_virtual_machine" "azrm_vm":
  58: resource "azurerm_virtual_machine" "azrm_vm" {
```

### Important Factoids

This behaviour happens in all regions and for all vm sizes if capacity can not be met. Above snippet is just an example.
Since the disks are defined inline in this example, they are also not present in the state but are still created on Azure.

**Comment by tombuildsstuff** [comment]
👋 

Closing this in favour of #7952, which should make this more reliable on Azure's side - would you mind subscribing to that issue for updates?

Thanks!
