### ISSUE TITLE
Azure Key Vault - No passing user identity

### ISSUE THREAD

**Issue by mikenorgate** [terraform-providers/terraform-provider-azurerm#631]
I'm attempting to insert a secret into Key Vault but always get a 401 response. Looking at the Azure logs I can see that there is no identity being passed with the request

I am using Terraform version `0.10.6` and version `0.3` of the AzureRM provider

The terraform excerpt is 
```
resource "azurerm_key_vault_secret" "my_secret" {
  name      = "my_secret"
  value     = "my_secret_value"
  vault_uri = "https://XXX.vault.azure.net/"
}
```

In the Azure diagnostics logs I can see the request and it  doesn't show an identity
```
{
	 "category": "AuditEvent",
	 "operationName": "Authentication",
	 "resultType": "Success",
	 "identity": {},
	 "properties": {"clientInfo":"HashiCorp-Terraform-v0.10.6","httpStatusCode":401,"requestUri":"https://XXX.vault.azure.net/secrets/my_secret?api-version=2016-10-01"},
	 "operationVersion": "2016-10-01",
	 "resultSignature": "Unauthorized",
	 "durationMs": "60"
}
```

**Comment by digitaldelirium** [comment]
FWIW - I'm getting the same behavior on azurerm provider version 1.0 and Terraform version 0.11.1
Terraform v0.11.1
+ provider.azurerm v1.0.0
+ provider.random v1.1.0
But I'd definitely recommend that you upgrade with terraform init -upgrade

**Comment by tombuildsstuff** [comment]
Closing this in favour of #656 since it's a duplicate
