### ISSUE TITLE
data.azurerm_client_config.current.object_id empty in Azure Cloud Shell

### ISSUE THREAD

**Issue by geekzter** [terraform-providers/terraform-provider-azurerm#6310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
terraform -v 
Terraform v0.12.24
+ provider.azurerm v2.3.0
```

### Affected Resource(s)

* `azurerm_client_config` (data)

### Terraform Configuration Files

```hcl
provider "azurerm" {
    version = "~> 2.0" 
    features {}
}

data azurerm_client_config current {}

output client_object_id {
    value = data.azurerm_client_config.current.object_id
}
output client_tenant_id {
    value = data.azurerm_client_config.current.tenant_id
}
```

### Expected Behavior

```
Outputs:

client_object_id = 00000000-0000-0000-0000-000000000000
client_tenant_id = 00000000-0000-0000-0000-000000000000
```

### Actual Behavior
```
Outputs:

client_object_id = 
client_tenant_id = 00000000-0000-0000-0000-000000000000
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

This only happens when run from Azure Cloud Shell ([shell.azure.com](https://shell.azure.com))

```
az account show
{
  "environmentName": "AzureCloud",
  "homeTenantId": "00000000-0000-0000-0000-000000000000",
  "id": "00000000-0000-0000-0000-000000000000",
  "isDefault": true,
  "managedByTenants": [],
  "name": "Subscription Name",
  "state": "Enabled",
  "tenantId": "00000000-0000-0000-0000-000000000000",
  "user": {
    "cloudShellID": true,
    "name": "me@domain.com",
    "type": "user"
  }
}
```

**Comment by dsbrng25b** [comment]
It seems that there is the same issue when a managed identity is used for authentication.
I guess this [comment](https://github.com/terraform-providers/terraform-provider-azurerm/blob/57c73af925c1d2fd064a890e94ef3f0ae61e0f28/azurerm/internal/clients/auth.go#L23) refers to this problem?

**Comment by geekzter** [comment]
Yes, that appears to be the same problem. I was logged in as user though, Cloud Shell manages that.  This does get the object id in that case:
```hcl
data external account_info {
  program                      = [
                                 "az",
                                 "ad",
                                 "signed-in-user",
                                 "show",
                                 "--query",
                                 "{object_id:objectId}",
                                 "-o",
                                 "json",
                                 ]
}
```

**Comment by mehdi-ichka** [comment]
I have the exact same issue

**Comment by JoeSainsburys** [comment]
I get the same issue from a VM authenticating with MSI.

> It seems that there is the same issue when a managed identity is used for authentication.
> I guess this [comment](https://github.com/terraform-providers/terraform-provider-azurerm/blob/57c73af925c1d2fd064a890e94ef3f0ae61e0f28/azurerm/internal/clients/auth.go#L23) refers to this problem?

The feature they are waiting on was implemented in this commit https://github.com/hashicorp/go-azure-helpers/commit/c44370437748f79193266408802e7105c76bd8b8 - so I think that someone just need to get them to change the code.

**Comment by LoicAG** [comment]
@JoeSainsburys in the commit you linked to, the `GetAuthenticatedObjectID` method is not implemented for MSI : https://github.com/hashicorp/go-azure-helpers/commit/c44370437748f79193266408802e7105c76bd8b8#diff-f43fc9c83cbbbb2c45248e751f3fe26a6321d326ef2cfb5c9759ffa8d2108266

There is another related issue about this: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7787

**Comment by tombuildsstuff** [comment]
👋 

CloudShell utilizes MSI authentication, which is the root-cause of this bug - as such I'm going to close this in favour of #7787 which is tracking that issue, would you mind subscribing to that issue for updates?

Thanks!
