### ISSUE TITLE
Support for [Azure Functions Pre-Warmed Instances]

### ISSUE THREAD

**Issue by SadokLadhari** [terraform-providers/terraform-provider-azurerm#6329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Support for the Pre-warmed instances.

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "example" {
  name                      = "test-azure-functions"
  location                  = azurerm_resource_group.example.location
  resource_group_name       = azurerm_resource_group.example.name
  app_service_plan_id       = azurerm_app_service_plan.example.id
  storage_connection_string = azurerm_storage_account.example.primary_connection_string

  pre_warmed_instance_count = 1
}
```

### References

* https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?view=azurermps-5.6.0#pre-warmed-instances

**Comment by SadokLadhari** [comment]
@tombuildsstuff can you check this please ?

**Comment by aqche** [comment]
I can take a look at this
