### ISSUE TITLE
Azure Event Hub Namespace - for_each does not work for network rule blocks

### ISSUE THREAD

**Issue by eliasvakkuri** [terraform-providers/terraform-provider-azurerm#6338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.1.0
+ provider.random v2.2.1

### Affected Resource(s)

* azurerm_eventhub_namespace

### Terraform Configuration Files

```hcl
terraform {}

provider "azurerm" {
  version  = "~> 2"
  features {}
}

variable "eventhub_namespace_allowed_ips_list" {
  type        = list(string)
  default     = []
  description = <<-EOT
  "List of IP addresses to allow in Event Hub Namespace firewall. Provide in full
  CIDR format with the subnet mask suffix"
  EOT
}

resource azurerm_resource_group rg {
  name     = "elias-test-rg"
  location = "westeurope"
}

resource "azurerm_eventhub_namespace" "eventhub_namespace" {
  name                 = "elias-test-ehnamespace"
  location             = azurerm_resource_group.rg.location
  resource_group_name  = azurerm_resource_group.rg.name
  sku                  = "Standard"
  capacity             = 1
  auto_inflate_enabled = true

  network_rulesets {
    default_action = "Deny"

    dynamic "ip_rule" {
      for_each = var.eventhub_namespace_allowed_ips_list

      content {
        ip_mask = ip_rule.value
        action  = "Allow"
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/eliasvakkuri/9e146b6153a15a41dbc5f2be23ee43a3

### Panic Output

No Panic

### Expected Behavior

Similar to other resources where IP and subnet firewall rules are set with blocks within the main resource, Terraform creates the correct number of these blocks.

### Actual Behavior

Error similar to https://github.com/hashicorp/terraform/issues/22340.

When trying to use for_each to set a parametrized number of ip_rule blocks or virtual_network_rule blocks, the following error is raised:

```
Error: Unknown variable

  on resources.tf line XX, in resource "azurerm_eventhub_namespace" "eventhub_namespace":
 179:       for_each = var.eventhub_namespace_allowed_ips_list

There is no variable named "var".
```

However, this works for some reason:
```hcl
ip_rule = [
      for ip in var.eventhub_namespace_allowed_ips_list : {
        ip_mask = ip
        action   = "Allow"
      }
    ]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Normal Azure

### References

* https://github.com/hashicorp/terraform/issues/22340

**Comment by tombuildsstuff** [comment]
hi @eliasvakkuri 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by eliasvakkuri** [comment]
OK so this is not an issue with the Azure provider? Thanks, I'll open a ticket in the main Terraform forum
