### ISSUE TITLE
The checksum doesn't match so that it fails to install the plugin for provider "azurerm" (1.0.0)

### ISSUE THREAD

**Issue by bingosummer** [terraform-providers/terraform-provider-azurerm#636]
### Terraform Version
`Terraform v0.11.1`

### Affected Resource(s)
N/A

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
```
$ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "azurerm" (1.0.0)...

Error installing provider "azurerm": Checksums did not match.
Expected: 69b5cda0e12cc2353f529d7f41b6504722eef718b7b830b36c57db00a9d8daf1
Got: 8125c3848ff5f52a2bfe11b0e6a49bdd27ddfea5d03b05bedd16153365c70fff.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64
```

### Expected Behavior
The plugin is installed.

### Actual Behavior
The checksum doesn't match so that it fails to install the plugin.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids
N/A

### References
N/A

**Comment by mattpound808** [comment]
Hello, I'm getting the same issue as well.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "azurerm" (1.0.0)...

Error installing provider "azurerm": Checksums did not match.
Expected: 8ed71a3b630fdc6f490e37c906153d86f2844aacb5cf553e8607829151c58e40
Got: beabbe97ac4271659310c7b48d16960d81e45c28bdc45589509053988ae602d1.

**Comment by antonydenyer** [comment]
We've been having the same problem since the last release.

**Comment by patrick-motard** [comment]
Duplicate of #635

**Comment by tombuildsstuff** [comment]
Hey @bingosummer @mattpound808 @patrick-motard 

Thanks for opening this issue - apologies about this.

As mentioned in #635 I believe this issue is now resolved (there's more information [in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/635#issuecomment-352054210) - would it be possible to try re-running `terraform init` and confirming if that solves this issue for you?

Thanks!

**Comment by bingosummer** [comment]
It works for me. Thanks
