### ISSUE TITLE
Support for azurerm_container_group for setting DNS in private networks

### ISSUE THREAD

**Issue by kensykora** [terraform-providers/terraform-provider-azurerm#6360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://github.com/MicrosoftFeedback/aci-issues/issues/25

It's possible for azure container instances to support DNS inside a custom VNet, but this isn't exposed in the `azurerm_container_group` options. Please add the ability to support this. My use case is that I have a virtual network in which I want the ACI that is running to be able to use services by DNS rather than IP. Specifically I'm trying to setup a container that runs a bridge to with Azure Relay, and want the relay listener running in ACI.

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

```hcl
resource "azurerm_container_group" "hybrid-listener" {
  name                = "aci-listener"
  location            = "West Europe"
  resource_group_name = azurerm_resource_group.azwe01rg01_t_relay.name
  ip_address_type     = "Private"
  network_profile_id  = azurerm_network_profile.azwe01acr01_profile.id
  os_type             = "Linux"
                                                   1                                             2
  container {
    name   = "azbridge"
    image  = "azbridge:latest"
    cpu    = "0.5"
    memory = "1.5"

    ports {
      port     = 9998
      protocol = "UDP"
    }
  }

  // See: https://github.com/Azure/azure-rest-api-specs/blob/21f0dcbb89544101d79be7fc889a86ce0911901b/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/stable/2018-10-01/examples/ContainerGroupsCreateOrUpdate.json#L73
  dns_config {
    name_servers = ["10.0.1.1", "10.0.1.2"]
    search_domains = "internal.mydomain"
    options = "ndots:2"
  }
}
```

### References

* Found when trying to test and work around #1697

**Comment by Dilergore** [comment]
Bump! I'm also missing these settings. Would be really nice to have them.

**Comment by zparnold** [comment]
I'll see if I can take a crack at it 😄

**Comment by Houssem-Azzouz** [comment]
Hello guys, are there any news regarding this feature? It is terribly needed
