### ISSUE TITLE
x509_certificate_properties should be required to create certificate

### ISSUE THREAD

**Issue by rukawata** [terraform-providers/terraform-provider-azurerm#6373]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm v2.4.0 `

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_certificate" "sshkey" {
  name         = "nancyc-kv-cert-01"
  key_vault_id = azurerm_key_vault.kv.id

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    secret_properties {
      content_type = "application/x-pem-file"
    }
  }
}
```

### Expected Behavior
https://www.terraform.io/docs/providers/azurerm/r/key_vault_certificate.html

> certificate_policy supports the following:
> 
> issuer_parameters - (Required) A issuer_parameters block as defined below.
> key_properties - (Required) A key_properties block as defined below.
> lifetime_action - (Optional) A lifetime_action block as defined below.
> secret_properties - (Required) A secret_properties block as defined below.
> **x509_certificate_properties - (Optional) A x509_certificate_properties block as defined below.**

However this should be **Required**.

### Actual Behavior

```
Error: keyvault.BaseClient#CreateCertificate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Property policy has invalid value\r\n"

  on main.tf line 89, in resource "azurerm_key_vault_certificate" "sshkey":
  89: resource "azurerm_key_vault_certificate" "sshkey" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by njuCZ** [comment]
hi @rukawata, thanks for pointing this issue. If we generating a new key vault certificate, `x509_certificate_properties` is required. But this resource also supports importing a certificate, in this way, this field is optional.

**Comment by ArcturusZhang** [comment]
Hi @njuCZ could you please open a PR to update the document accordingly?

**Comment by njuCZ** [comment]
sure, I have submited a pr
