### ISSUE TITLE
not able to use variables for blocks in azurerm_storage_account

### ISSUE THREAD

**Issue by abhinavaGopagani** [terraform-providers/terraform-provider-azurerm#6377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.20
+ provider.azuread v0.8.0
+ provider.azurerm v2.4.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
# Variables
# https://www.terraform.io/docs/configuration/variables.html
# https://www.terraform.io/docs/configuration/types.html

variable "resource_group_name" {
  type        = string
  description = "Azure Resource Group name. Value must follow Microsoft's validation: https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/get#uri-parameters."
}

variable "storage_account_location" {
  type        = string
  description = "Azure Storage Account location. Value must follow Microsoft's validation: https://azure.microsoft.com/en-ca/global-infrastructure/locations."
}

variable "storage_account_name" {
  type        = string
  description = "Azure Storage Account name. Value must follow Microsoft's validation: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-storage-account-name."
}

variable "storage_account_kind" {
  type        = string
  description = "Azure Storage Account kind. Value must be one of: BlobStorage, BlockBlobStorage, FileStorage, Storage, StorageV2."
  default     = "StorageV2"
}

variable "storage_account_replication_type" {
  type        = string
  description = "Azure Storage Account replication type. Value must be one of: LRS, GRS, RAGRS, ZRS."
  default     = "LRS"
}

variable "storage_account_tier" {
  type        = string
  description = "Azure Storage Account tier. Value must be one of: Standard, Premium."
  default     = "Standard"
}

variable "storage_account_access_tier" {
  type        = string
  description = "Azure Storage Account access tier. Value must be one of: Hot, Cool."
  default     = "Hot"
}

variable "storage_account_https_only" {
  type        = bool
  description = "Azure Storage Account https only."
  default     = true
}

variable "storage_account_is_hns_enabled" {
  type        = bool
  description = "Is Hierarchical Namespace enabled? This can be used with Azure Data Lake Storage Gen 2"
  default     = false
}

variable "storage_account_custom_domain" {
  type = object(
    {
      name          = string,
      use_subdomain = bool
  })
  description = "Storage Account custom domain"
  default     = null
}

variable "storage_account_blob_properties" {
  type = object(
    {
      cors_rule = object(
        {
          allowed_headers    = list(string),
          allowed_methods    = list(string),
          allowed_origins    = list(string),
          exposed_headers    = list(string),
          max_age_in_seconds = number
        }
      ),
      delete_retention_policy = object(
        {
          days = number
        }
  ) })
  description = "cross-origin request and retention_policy properties of blob"
  default     = null
}

variable "storage_account_queue_properties" {
  type = object(
    {
      cors_rule = object(
        {
          allowed_headers    = list(string),
          allowed_methods    = list(string),
          allowed_origins    = list(string),
          exposed_headers    = list(string),
          max_age_in_seconds = number
        }
      ),
      logging = object(
        {
          delete                = bool,
          read                  = bool,
          version               = string,
          write                 = bool,
          retention_policy_days = number
        }
      ),
      minute_metrics = object(
        {
          enabled               = bool,
          version               = string,
          include_apis          = bool,
          retention_policy_days = number
        }
      ),
      hour_metrics = object(
        {
          enabled               = bool,
          version               = string,
          include_apis          = bool,
          retention_policy_days = number
        }
      )
  })
  description = "cross-origin request and logging properties of queue"
  default     = null
}

variable "storage_account_static_website" {
  type = object(
    {
      index_document     = string,
      error_404_document = string
  })
  description = "Storage Account static website"
  default     = null
}

variable "storage_account_tags" {
  type        = map(string)
  description = "Storage account tags."
  default = {
    Owner       = "DefaultValueFromPolicy"
    ContactDL   = "DefaultValueFromPolicy"
    Environment = "DefaultValueFromPolicy"
  }
}

variable "storage_account_network_rules" {
  type = map(object(
    {
      default_action             = string,
      bypass                     = list(string),
      ip_rules                   = list(string),
      virtual_network_subnet_ids = list(string)
  }))
  description = "Storage Account static website"
  default     = {}
}
# Providers
# https://www.terraform.io/docs/configuration/terraform.html
# https://www.terraform.io/docs/configuration/providers.html
# https://www.terraform.io/docs/configuration/expressions.html
# https://www.terraform.io/docs/configuration/functions.html

provider "azuread" {}
provider "azurerm" {
  features {}
}

terraform {
  required_version = ">= 0.12.6"
  required_providers {
    azuread = "~> 0.8"
    azurerm = "~> 2.2"
  }
}
# Data Sources
# https://www.terraform.io/docs/configuration/data-sources.html

# Modules and Resources
# https://www.terraform.io/docs/configuration/modules.html
# https://www.terraform.io/docs/configuration/resources.html

resource "azurerm_storage_account" "default" {
  resource_group_name       = var.resource_group_name
  location                  = var.storage_account_location
  name                      = var.storage_account_name
  account_kind              = var.storage_account_kind
  account_replication_type  = var.storage_account_replication_type
  account_tier              = var.storage_account_kind == "FileStorage" ? "Premium" : var.storage_account_tier
  access_tier               = var.storage_account_kind == "BlobStorage" || var.storage_account_kind == "FileStorage" || var.storage_account_kind == "StorageV2" ? var.storage_account_access_tier : null
  enable_https_traffic_only = var.storage_account_https_only
  is_hns_enabled            = var.storage_account_is_hns_enabled
  custom_domain             = var.storage_account_custom_domain
  identity { type = "SystemAssigned" }
  blob_properties  = var.storage_account_blob_properties
  queue_properties = var.storage_account_kind == "BlobStorage" ? null : var.storage_account_queue_properties
  static_website   = var.storage_account_kind == "StorageV2" ? var.storage_account_static_website : null
  tags             = var.storage_account_tags
}

### Debug Output
on resources.sa.tf line 18, in resource "azurerm_storage_account" "default":
  18:   custom_domain             = var.storage_account_custom_domain

An argument named "custom_domain" is not expected here. Did you mean to define
a block of type "custom_domain"?

Error: Unsupported argument

  on resources.sa.tf line 20, in resource "azurerm_storage_account" "default":
  20:   blob_properties  = var.storage_account_blob_properties

An argument named "blob_properties" is not expected here. Did you mean to
define a block of type "blob_properties"?

Error: Unsupported argument

  on resources.sa.tf line 21, in resource "azurerm_storage_account" "default":
  21:   queue_properties = var.storage_account_kind == "BlobStorage" ? null : var.storage_account_queue_properties

An argument named "queue_properties" is not expected here. Did you mean to
define a block of type "queue_properties"?

Error: Unsupported argument

  on resources.sa.tf line 22, in resource "azurerm_storage_account" "default":
  22:   static_website   = var.storage_account_kind == "StorageV2" ? var.storage_account_static_website : null

An argument named "static_website" is not expected here. Did you mean to
define a block of type "static_website"?

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @abhinavaGopagani 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
