### ISSUE TITLE
Dependency relation isn't detected after removed resource B and the reference of resource B in resource A from tfconfig

### ISSUE THREAD

**Issue by neil-yechenwei** [terraform-providers/terraform-provider-azurerm#6383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
v2.0

### Affected Resource(s)

* `azurerm_public_ip`
* `azurerm_nat_gateway`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "neil-pip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  public_ip_address_ids   = [azurerm_public_ip.test.id]
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```

### Panic Output

$ tf apply -auto-approve
azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/<subscription-id>/resourceGroups/test-nat]
azurerm_public_ip.natip: Refreshing state... [id=/subscriptions/<subscription-id>/resourceGroups/test-nat/providers/Microsoft.Network/publicIPAddresses/test-nat-ip]
azurerm_nat_gateway.nat: Refreshing state... [id=/subscriptions/<subscription-id>/resourceGroups/test-nat/providers/Microsoft.Network/natGateways/test-nat-gateway]
azurerm_subnet_nat_gateway_association.nat-worker-subnet-association: Refreshing state... [id=/subscriptions/<subscription-id>/resourceGroups/my-rg/providers/Microsoft.Network/virtualNetworks/test/subnets/test]
azurerm_public_ip.natip: Destroying... [id=/subscriptions/<subscription-id>/resourceGroups/test-nat/providers/Microsoft.Network/publicIPAddresses/test-nat-ip]

Error: Error deleting Public IP "test-nat-ip" (Resource Group "test-nat"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/<subscription-id>/resourceGroups/test-nat/providers/Microsoft.Network/publicIPAddresses/test-nat-ip can not be deleted since it is still allocated to resource /subscriptions/<subscription-id>/resourceGroups/test-nat/providers/Microsoft.Network/natGateways/test-nat-gateway. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]

### Expected Behavior
`azurerm_nat_gateway` resource should be updated first, then delete `azurerm_public_ip` resource.

### Actual Behavior

Terraform would delete `azurerm_public_ip` resource before updates `azurerm_nat_gateway`.

### Steps to Reproduce

1. Run `terraform apply --auto-approve` with below tfconfig.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "neil-pip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  public_ip_address_ids   = [azurerm_public_ip.test.id]
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```
2. Run `terraform apply --auto-approve` with below tfconfig:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```

**Comment by tombuildsstuff** [comment]
hi @neil-yechenwei 

Thanks for opening this issue.

This appears to be an issue with the ordering of dependencies in Terraform Core - since this is outside the scope of the Azure Provider can you please [reopen your issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) so that someone from the Terraform Core Team can take a look at it?

Thanks!
