### ISSUE TITLE
Disk Encryption Set properties inconsistent with documentation

### ISSUE THREAD

**Issue by davidobrien1985** [terraform-providers/terraform-provider-azurerm#6390]
The documentation shows that https://www.terraform.io/docs/providers/azurerm/r/disk_encryption_set.html#identity is an optional value, however, it is actually required, even according to your own code comment:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/01630bd0676ea7b7440feae377127b70b840874c/azurerm/internal/services/compute/resource_arm_disk_encryption_set.go#L64

Can the documentation please be updated?
Thanks.

**Comment by ArcturusZhang** [comment]
Hi @davidobrien1985 thanks for this issue.
Indeed the `identity` is marked as `Required` in the code, but it is documented as `Optional`. I will take some time to modify the docs accordingly.
