### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment does not work together with some cloud-init options

### ISSUE THREAD

**Issue by josemaia** [terraform-providers/terraform-provider-azurerm#6404]
### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
+ provider.azurerm v1.36.1

### Affected Resource(s)
* `azurerm_managed_disk`
* `azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files
Cloud-init file such as
```yml
#cloud-config
disk_setup:
  /dev/disk/azure/scsi1/lun0:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - device: /dev/disk/azure/scsi1/lun0
    partition: 1
    filesystem: ext4

mounts:
  - [
      "/dev/disk/azure/scsi1/lun0-part1",
      "/opt/data",
      auto,
      "defaults,noexec,nofail",
    ]
```

Module invocation like
```hcl
data "template_file" "cloudconfig" {
  template = file("${path.module}/cloud-init.tpl")
}

data "template_cloudinit_config" "config" {
  gzip          = true
  base64_encode = true

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.cloudconfig.rendered}"
  }
}

module "nexus_test_vm" {
  #unnecessary details ommitted - 1 VM with 1 external disk, fixed lun of 0, ubuntu 18.04
  vm_size            = "Standard_B2S"

  cloud_init_template = data.template_cloudinit_config.config.rendered
}
```

Module TF config such as
```hcl
resource "azurerm_virtual_machine" "generic-vm" {
  count               = var.number
  name                = "${local.my_name}-${count.index}-vm"
  location            = var.location
  resource_group_name = var.resource_group_name

  network_interface_ids         = [azurerm_network_interface.generic-nic[count.index].id]
  vm_size                       = var.vm_size
  delete_os_disk_on_termination = true

  storage_image_reference {
    id = var.image_id
  }

  storage_os_disk {
    name              = "${local.my_name}-${count.index}-os"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
    disk_size_gb      = var.os_disk_size
  }

  os_profile {
    computer_name  = "${local.my_name}-${count.index}"
    admin_username = local.my_admin_user_name
    custom_data    = var.cloud_init_template
  }

  os_profile_linux_config {
    disable_password_authentication = true

    ssh_keys {
      path = "/home/${local.my_admin_user_name}/.ssh/authorized_keys"
      //key_data = tls_private_key.vm_ssh_key.public_key_openssh
      key_data = var.public_key_openssh
    }
  }

  tags = {
    Name        = "${local.my_name}-${count.index}"
    Deployment  = local.my_deployment
    Prefix      = var.prefix
    Environment = var.env
    Location    = var.location
    Volatile    = var.volatile
    Terraform   = "true"
  }
}

resource "azurerm_managed_disk" "generic-disk" {
  name                 = "${azurerm_virtual_machine.generic-vm.*.name[0]}-1-generic-disk"
  location             = var.rg_location
  resource_group_name  = var.rg_name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = var.external_disk_size
}

resource "azurerm_virtual_machine_data_disk_attachment" "generic-disk" {
  managed_disk_id    = azurerm_managed_disk.generic-disk.id
  virtual_machine_id = azurerm_virtual_machine.generic-vm.*.id[0]
  lun                = 0
  caching            = "ReadWrite"
}
```

### Expected Behavior

On boot, configure the disk and mount it on /opt/data.

### Actual Behavior

Error in the logs, `Device /dev/disk/azure/scsi1/lun0 did not exist and was not created with a udevadm settle.`

### Steps to Reproduce
1. Configure a terraform script with a vm with azurerm_virtual_machine_data_disk_attachment
2. Configure the VM to have a cloud-init script hat has disk_setup invocation
3. Run a terraform apply, ssh into that machine and verify the disk_setup failed

### Important Factoids
My suggestion would be for this to be noted in the documentation, unless it is possible to automatically solve it in the dependency tree somehow.

**Comment by alk-rniveau** [comment]
@josemaia did you find a workaround or are you still stuck with that ? I have the same issue

**Comment by josemaia** [comment]
The workaround is defining the data disk(s) inside the azurerm_virtual_machine.

I did it with a dynamic block:
```terraform
  dynamic "storage_data_disk" {
    for_each = range(var.external_disk_count)
    content {
      name              = "${local.my_name}-${count.index}-external-disk-${storage_data_disk.value}"
      create_option     = "Empty"
      caching           = "ReadWrite"
      managed_disk_type = "Standard_LRS"
      disk_size_gb      = var.external_disk_size
      lun               = storage_data_disk.value
    }
  }
```

**Comment by OlivierMns** [comment]
Same issue on my side using "azurerm_linux_virtual_machine" and "azurerm_virtual_machine_data_disk_attachment", moreover I can't find a way to use a disk-encryption-set with the "azurerm_virtual_machine" and "storage_data_disk" workaround. 
Is there a way to postpone/pause the VM startup (to make sure the disk is attached before the cloud-init script is executed) ?

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here as @josemaia has mentioned this should be possible using the `storage_data_disk` block within the `azurerm_virtual_machine` resource - however it's worth noting that this resource has been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources.

Support for data disks for these resources is being tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/6117 - where once this is available we'd recommend investigating since the older `azurerm_virtual_machine` resource is feature-frozen (and so won't be receiving any new functionality going forwards).

Thanks!
