### ISSUE TITLE
Support private cluster option for AKS clusters

### ISSUE THREAD

**Issue by asubmani** [terraform-providers/terraform-provider-azurerm#6416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This issue #2241 was closed due to the AKS API not supporting private clusters. Now that AKS support for private clusters is GA, please add this important feature. Private cluster feature is GA and documented in the API  https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate 
Please note that this feature has a relationship with `api_server_authorized_ip_ranges` as only either can be enabled. 
### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "cluster" {
  enable_private_cluster = true ##if true then api_server_authorized_ip_ranges should be "false"
  ...
}
```

### References

* #2241

**Comment by aristosvo** [comment]
I'll give it a try!

**Comment by aristosvo** [comment]
@tombuildsstuff It seems this feature is already fixed [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/5161), doc [here](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#private_link_enabled), but the feature is called there `private_link_enabled`. Shall I deprecate `private_link_enabled` for `enable_private_cluster`?

@asubmani, apparently it seems to be already included, but the naming is a bit different: 
```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }
  
  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "standard"
  }
  
  private_link_enabled            = true
}
```
