### ISSUE TITLE
.azurerm_virtual_machine_data_disk_attachment - Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by RobinAggarwal** [terraform-providers/terraform-provider-azurerm#6418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.0.0
+ provider.random v2.2.1

### Affected Resource(s)
azurerm_virtual_machine_data_disk_attachment
azurerm_managed_disk

### Debug output

Error: Provider produced inconsistent result after apply

When applying changes to
module.sql_server1_dbdata.azurerm_virtual_machine_data_disk_attachment.disk1,
provider "registry.terraform.io/-/azurerm" produced an unexpected new value
for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior
azurerm_virtual_machine_data_disk_attachment should run to attach disk to VM.
Disk was created using azurerm_managed_disk.

### Actual Behavior
Behavior is inconsistent. On Azure portal; owner of disk are shown as VM or sometimes it is blank.
And got this error as shown in log above.

### Important Factoids
Created a module where I am creating a managed disk using azurerm_managed_disk.
Then attaching this disk to VM using azurerm_virtual_machine_data_disk_attachment

This is happening when multiple threads try to attach disks to same VM. 
Eg if I am creating 6 disks and attaching all to same VM; one pass and 5 fails.
If you apply again; one pass and 4 fails with above error.

**Comment by RobinAggarwal** [comment]
One Observation 

This is happening when multiple threads try to attach disks to same VM. 
Eg if I am creating 6 disks and attaching all to same VM; one pass and 5 fails.
If you apply again; one pass and 4 fails with above error.

**Comment by RobinAggarwal** [comment]
@katbyte  can you confirm this is bug; and tag it properly for team to priorities this issue.

**Comment by neil-yechenwei** [comment]
@RobinAggarwal , thanks for opening this issue. After tested with below tfconfig and latest azurerm, seems I cannot repro this issue. Could you have a try below tfconfig to check whether the issue still exists? If still exists, could you share your tfconfig that triggers this issue? Thanks.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-manageddisk-test02"
  location = "eastus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctvn-test02"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "internalsubnet-test02"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "test" {
  name                = "acctni-test02"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = azurerm_subnet.test.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "test" {
  name                            = "acctestvm-test02"
  resource_group_name             = azurerm_resource_group.test.name
  location                        = azurerm_resource_group.test.location
  size                            = "Standard_D2s_v3"
  admin_username                  = "adminuser"
  admin_password                  = "Password1234!"
  disable_password_authentication = false

  network_interface_ids = [
    azurerm_network_interface.test.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}

resource "azurerm_managed_disk" "test" {
  name                 = "test02-disk1"
  location             = azurerm_resource_group.test.location
  resource_group_name  = azurerm_resource_group.test.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "test" {
  managed_disk_id    = azurerm_managed_disk.test.id
  virtual_machine_id = azurerm_linux_virtual_machine.test.id
  lun                = "0"
  caching            = "None"
}

resource "azurerm_managed_disk" "test2" {
  name                 = "test02-disk2"
  location             = azurerm_resource_group.test.location
  resource_group_name  = azurerm_resource_group.test.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "test2" {
  managed_disk_id    = azurerm_managed_disk.test2.id
  virtual_machine_id = azurerm_linux_virtual_machine.test.id
  lun                = "1"
  caching            = "None"
}

resource "azurerm_managed_disk" "test3" {
  name                 = "test02-disk3"
  location             = azurerm_resource_group.test.location
  resource_group_name  = azurerm_resource_group.test.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "test3" {
  managed_disk_id    = azurerm_managed_disk.test3.id
  virtual_machine_id = azurerm_linux_virtual_machine.test.id
  lun                = "2"
  caching            = "None"
}

resource "azurerm_managed_disk" "test4" {
  name                 = "test02-disk4"
  location             = azurerm_resource_group.test.location
  resource_group_name  = azurerm_resource_group.test.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "test4" {
  managed_disk_id    = azurerm_managed_disk.test4.id
  virtual_machine_id = azurerm_linux_virtual_machine.test.id
  lun                = "3"
  caching            = "None"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment - but please let us know if you're able to take a look at the comment above and confirm if this is still an issue and we'll take another look.

Thanks!
