### ISSUE TITLE
2.5.0 Outputs no longer working. 

### ISSUE THREAD

**Issue by lukekhamilton** [terraform-providers/terraform-provider-azurerm#6422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hey guys, 

Updated to 2.5.0 this morning and looks like outputs arent working at all now..

Config:

```
output "test" {
  value = "This is a test"
}

output "kube_config" {
  value = azurerm_kubernetes_cluster.cluster.kube_config_raw
}

```

Returnings nothing when and `apply` is completed. Even running a refresh doesnt change anything. 

And when this cmd line is run `terrraform output` nothing is also returned. 

Help. Thanks

### Affected Resource(s)

```
❯ terraform version 
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.5.0
+ provider.helm v1.1.1
```

### Terraform Configuration Files

```
output "kube_config" {
  value = azurerm_kubernetes_cluster.cluster.kube_config_raw
}

```

### Expected Behavior

lots of k8s config stuff. 

### Actual Behavior

Nothing at all....

### Steps to Reproduce

I just updated to version 2.5.0 and it broke.

1. `terraform apply`

nothing.

**Comment by tombuildsstuff** [comment]
hi @lukekhamilton 

Thanks for opening this issue.

Taking a look through here using a cluster that I provisioned yesterday - and a cluster that I've provisioned today this appears to work:

```
$ cat main.tf
provider "azurerm" {
  version = "=2.5.0"
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "tomdev99-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "tom-devaks999"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "tom-devaks999"

  default_node_pool {
    name = "default"
    #node_count = 1
    min_count           = 1
    enable_auto_scaling = true
    max_count           = 2
    vm_size             = "Standard_DS2_v2"

    tags = {
      environment = "Staging"
    }
  }

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    network_plugin     = "kubenet"
    load_balancer_sku  = "Basic"
    pod_cidr           = "10.244.0.0/16"
    service_cidr       = "10.0.0.0/16"
    dns_service_ip     = "10.0.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "test" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  #node_count            = 1
  enable_auto_scaling = true
  min_count           = 1
  max_count           = 2

  tags = {
    environment = "Staging"
  }
}

output "kube_config" {
  value = azurerm_kubernetes_cluster.test.kube_config_raw
}
```

Would you be able to provide more details/an example configuration showing this issue?

Thanks!

**Comment by lukekhamilton** [comment]
Ok I just got this working again. I had to define my output in the `env/staging` config folder as well as in the `modules/azure` infra HCL folder... Has this behaviour changed at some point?

**Comment by tombuildsstuff** [comment]
@lukekhamilton afaik the behaviour of Terraform Core for outputs hasn't changed in years - it should should only output values in the root (module); perhaps an output was unintentionally defined in the root previously? Glad to hear this is now working anyway :)
