### ISSUE TITLE
Support native parallelism for test cases

### ISSUE THREAD

**Issue by metacpp** [terraform-providers/terraform-provider-azurerm#643]
### Terraform Version
N/A. Testing issue.

### Affected Resource(s)
All legacy testing cases, especially acceptance tests.

### Expected Behavior
1. Each test case can decide to enable parallelism or not through a simple parallelism flag.
2. "go test -v -parallel=N" should run N test cases(enabled by parallelism flag) in parallel.
 
### Actual Behavior
1. No simple way to enable it globally on legacy cases with minimum changes.
2. No simple way to enable it at case level.
3. If TF_LOG is turned on, the logs per test case are not grouped together in stdout & stderr.

### Steps to Reproduce
Run 'make testacc', then you will see that all the tests run in sequentially, which takes 3+ days to finish.

**Comment by metacpp** [comment]
@tombuildsstuff Go SDK 1.10 is going to resolve this issue through structured text(JSON), the Core runtime team should figure out how to resolve the logging issue while running tests in parallel. Please help with assigning this issue to the person who can resolve it from core runtime team.

**Comment by tombuildsstuff** [comment]
Fixed via #2227
