### ISSUE TITLE
Support for autoscale for HDInsight clusters

### ISSUE THREAD

**Issue by kosinsky** [terraform-providers/terraform-provider-azurerm#6470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

HDInsight clusters support [autoscale](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-autoscale-clusters) feature. Cluster could be scaled based on load (capacity) or schedule. Only worker nodes could be autoscaled

Autoscale can be set during creation via ARM: https://docs.microsoft.com/en-us/azure/templates/microsoft.hdinsight/2018-06-01-preview/clusters#autoscale-object and 

Autoscale can be enabled or disabled via REST API: https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-autoscale-clusters#using-the-rest-api
https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-autoscale-clusters#create-a-cluster-with-a-resource-manager-template

### New or Affected Resource(s)

* azurerm_hdinsight_(hadoop|hbase|spark|interactive_query)_cluster

#### Capacity based
```hcl
resource "azurerm_hdinsight_hadoop_cluster" "example" {
  name                = "example-hdicluster"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  cluster_version     = "3.6"
  tier                = "Standard"

 roles {
     head_node {
        // ...
     }
     worker_node {
       vm_size               = "Standard_D3_V2"
       username              = "acctestusrvm"
       password              = var.role_password
       target_instance_count = 2
       autoscale  {
            capacity {
               min_instance_count = 2
               max_instance_count = 3
            }
       }
     }
     zookeeper_node {
        // ...

     }
   }
}
```

#### Schedule based
```hcl
resource "azurerm_hdinsight_hadoop_cluster" "example" {
  name                = "example-hdicluster"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  cluster_version     = "3.6"
  tier                = "Standard"

 roles {
     head_node {
        // ...
     }
     worker_node {
       vm_size               = "Standard_D3_V2"
       username              = "acctestusrvm"
       password              = var.role_password
       target_instance_count = 2
       autoscale  {
           recurrence {
            timezone  = "Pacific Standard Time"
              schedule {
                days      = ["Monday"]
                time      = "10:00"
                min_instance_count = 5
                max_instance_count = 5    
              }            
              schedule {
                days      = ["Saturday", "Sunday"]
                time      = "10:00"
                min_instance_count = 2
                max_instance_count = 2                
              }
            }
       }
     }
     zookeeper_node {
        // ...

     }
   }

}
```

**Comment by kosinsky** [comment]
REST API has been supporting update Autoscale  for a while now. However, it was added to Go SDK only in v44.2.0 https://github.com/Azure/azure-sdk-for-go/pull/11841/files#diff-eb83effee75e9070818d473dc7064433

Looks like 44.2.0 update is pretty minor one (https://github.com/Azure/azure-sdk-for-go/pull/11841) hope we will get it pretty soon

**Comment by jackofallops** [comment]
Closing as this appears to have been resolved in https://github.com/terraform-providers/terraform-provider-azurerm/pull/11547
