### ISSUE TITLE
Support for Forwarding Dead Messages from Servicebus Queue not just subscription

### ISSUE THREAD

**Issue by vpetersen** [terraform-providers/terraform-provider-azurerm#6472]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have a need to forward dead lettering messages from a queue back into a topic not just a subscription, can we add this functionality. https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/2017-04-01/namespaces/queues

Similar to this request: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4542

**Comment by rlaveycal** [comment]
And also support forwarding to a queue/topic (the `forwardTo`) param.
