### ISSUE TITLE
Azure Container Service rebuilds every time

### ISSUE THREAD

**Issue by maganuk** [terraform-providers/terraform-provider-azurerm#648]
Hi there,

### Terraform Version
v0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_container_service

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "Test" {
    name                            = "${var.fb_test_resource_group_name}"
    location                        = "${var.fb_test_resource_group_location}"
}

resource "azurerm_container_service" "Test" {
  name                              = "${var.fb_test_acs_name}"
  location                          = "${azurerm_resource_group.Test.location}"
  resource_group_name               = "${azurerm_resource_group.Test.name}"
  orchestration_platform            = "Kubernetes"

  master_profile {
    count                           = "${var.fb_test_acs_master_count}"
    dns_prefix                      = "${var.fb_test_acs_master_dns_prefix}"
  }

  linux_profile {
    admin_username                  = "${var.fb_test_acs_linux_username}"

    ssh_key {
      key_data                      = "${var.fb_test_acs_linux_ssh_key}"
    }
  }

  agent_pool_profile {
    name                            = "${var.fb_test_acs_linux_agent_name}"
    count                           = "${var.fb_test_acs_linux_agent_count}"
    dns_prefix                      = "${var.fb_test_acs_linux_agent_dns_prefix}"
    vm_size                         = "${var.fb_test_acs_linux_agent_vm_size}"
  }

  service_principal {
    client_id                       = "${var.fb_test_acs_service_principal_client_id}"
    client_secret                   = "${var.fb_test_acs_service_principal_client_secret}"
  }

  diagnostics_profile {
    enabled                         = "${var.fb_test_acs_diagnostics_enabled}"
  }
}
```

### Debug Output
-/+ azurerm_container_service.Test (new resource required)
      id:                                                  "/subscriptions/xxxxxx-xxxxx-49bb-a9f3-cebad90bb69f/resourcegroups/XXXX-Testing/providers/Microsoft.ContainerService/containerServices/XXXX" => <computed> (forces new resource)
      agent_pool_profile.#:                                "1" => "1"
      agent_pool_profile.1147342673.count:                 "" => "1"
      agent_pool_profile.1147342673.dns_prefix:            "" => "xxxxagent1" (forces new resource)
      agent_pool_profile.1147342673.fqdn:                  "" => <computed>
      agent_pool_profile.1147342673.name:                  "" => "linux" (forces new resource)
      agent_pool_profile.1147342673.vm_size:               "" => "Standard_A0"
      agent_pool_profile.3554713841.count:                 "1" => "0"
      agent_pool_profile.3554713841.dns_prefix:            "" => ""
      agent_pool_profile.3554713841.name:                  "linux" => "" (forces new resource)
      agent_pool_profile.3554713841.vm_size:               "Standard_A0" => ""
      diagnostics_profile.#:                               "1" => "1"
      diagnostics_profile.734881840.enabled:               "false" => "false"
      diagnostics_profile.734881840.storage_uri:           "" => <computed>
      linux_profile.#:                                     "1" => "1"
      linux_profile.4167825415.admin_username:             "xxxx" => "xxxx"
      linux_profile.4167825415.ssh_key.#:                  "1" => "1"
      linux_profile.4167825415.ssh_key.810670071.key_data: "ssh-rsa ......."
      location:                                            "centralindia" => "centralindia"
      master_profile.#:                                    "1" => "1"
      master_profile.2055674301.count:                     "1" => "1"
      master_profile.2055674301.dns_prefix:                "xxxxmaster1" => "xxxxmaster1"
      master_profile.2055674301.fqdn:                      "xxxxmaster1.centralindia.cloudapp.azure.com" => <computed>
      name:                                                "xxxx" => "xxxx"
      orchestration_platform:                              "Kubernetes" => "Kubernetes"
      resource_group_name:                                 "xxxx-Testing" => "xxxx-Testing"
      service_principal.#:                                 "1" => "1"
      service_principal.1746194358.client_id:              "xxxx-xxxx-4290-b966-a0c53d10103c" => "xxxx-xxxx-4290-b966-a0c53d10103c"
      service_principal.1746194358.client_secret:          <sensitive> => <sensitive> (attribute changed)
      tags.%:                                              "0" => <computed>

### Expected Behavior
Should not re-create the entire resource (especially when nothing has changed)

### Actual Behavior
Wants to destroy and recreate the entire service.

### Steps to Reproduce
1. `terraform plam
2.  terraform apply`

**Comment by dcherniv** [comment]
bump. I can reproduce the issue.

**Comment by achandmsft** [comment]
Hi @maganuk and @dcherniv, Thanks for reporting this issue. I notice that you are using the Kubernetes flavor of ACS. We have just released native support for the fully managed Kubernetes cluster (azurerm_kubernetes_cluster) in Terraform to replace ACS-Kubernetes. Could you please let me know if you could use that instead of ACS in order to satisfy your requirements? 

Thanks,
Arun Chandrasekhar
Principal Program Manager
Azure OSS Integrations - Microsoft
