### ISSUE TITLE
Support for "deny public network access" in Azure Database for MySQL

### ISSUE THREAD

**Issue by lcaille** [terraform-providers/terraform-provider-azurerm#6482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When the Private Link is used, the MySql can be accessed using a private address. Therefore we should be able to `deny public network access`. This option should exists in `azurerm_mysql_server`

### New or Affected Resource(s)

- azurerm_mysql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_mysql_server" "example" {

  ...

  public_network_access_enabled = true
}
```

### References

* [Deny public network access ](https://docs.microsoft.com/en-gb/azure/mysql/concepts-data-access-security-private-link#deny-public-access-for-azure-database-for-mysql)
* [Support for "deny public network access" in Azure Database for PostgreSQL](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6216)

**Comment by m2b-arariba** [comment]
This issue was fixed in v2.7.0

**Comment by rajatrawat99** [comment]
I was looking for the similar functionality for Azure sql but I was not able to find it. is "Deny public network access" is there for Azure sql? if not is there any plan to add it in future?

**Comment by katbyte** [comment]
@rajatrawat99 - so far we only support it in postgres and mysql. It should make its way to mssql & maria db in the next few weeks.

Closing as this was released in 2.7!

**Comment by kfyhn** [comment]
Is it also on the roadmap for azurerm_sql_server?

**Comment by katbyte** [comment]
@kfyhn - this will not be added to `azurerm_sql_server` as it is using the older APIs which do not support that property. The replacement resource `azurerm_mssql_server` supports it but it seems like it didn't make it into the docs so i've opened #7011 to add that.

**Comment by rajatrawat99** [comment]
@katbyte so are you saying it wont be available for `azurerm_sql_server `  and will be available for `azurerm_mssql_server `. Does it  mean `azurerm_mssql_server ` is advanced version of `azurerm_sql_server ` and replacement for it? I am asking you as I can not see this on docs.
