### ISSUE TITLE
Failed to create CNAME record in a private dns zone.

### ISSUE THREAD

**Issue by ameukam** [terraform-providers/terraform-provider-azurerm#6500]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_private_dns_zone`
* `azurerm_dns_cname_record`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name = "test"
  location = "westeurope"
}

resource "azurerm_private_dns_zone" "privatedns" {
  name                = "azure-lab.net"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_dns_cname_record" "cnamerecord" {
  name                = "test"
  zone_name           = azurerm_private_dns_zone.privatedns.name
  resource_group_name = azurerm_resource_group.rg.name
  ttl                 = 300
  record              = "www.google.fr"

  depends_on = [
    azurerm_private_dns_zone.privatedns
  ]
}
```

### Debug Output

https://gist.github.com/ameukam/b39d6d852cf709d7093b6746c03924d9

### Expected Behavior

A CNAME record should be created in the private DNS zone :
`
test.azure-lab.net
`

### Actual Behavior
Failed to create the DNS record with the following output:
```console
Error: Error creating/updating CNAME Record "test" (DNS Zone "azure-lab.net" / Resource Group "co-preprod-ew1-rg"): dns.RecordSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'azure-lab.net' not found."
```

### Steps to Reproduce

1. `terraform apply`

**Comment by pearcec** [comment]
@ameukam 
Took me a minute to find it.  But you are using the wrong resource type.  You left out the private for `azurerm_private_dns_cname_record`.

```
lprovider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "test"
  location = "eastus"
}

resource "azurerm_private_dns_zone" "privatedns" {
  name                = "azure-lab.net"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_private_dns_cname_record" "cnamerecord" {
  name                = "test"
  zone_name           = azurerm_private_dns_zone.privatedns.name
  resource_group_name = azurerm_resource_group.rg.name
  ttl                 = 300
  record              = "www.google.fr"
}
```

**Comment by ameukam** [comment]
@pearcec Thanks for your help.

**Comment by pearcec** [comment]
> @pearcec Thanks for your help.

You are welcome, I was fishing for a bug to fix 🚀
