### ISSUE TITLE
Support for adding Managed Identity to Linked Services to ADLS Gen 2 for Azure Data Factory.

### ISSUE THREAD

**Issue by codepossible** [terraform-providers/terraform-provider-azurerm#6501]
## Managed Identity for Linked Service to ADLS Gen 2 for Azure Data Factory

As of January 2020, Azure Data Factory (ADF) now supports Managed Identity (formerly known as  Managed Service Identity - MSI) to connect to other Azure resources like Azure Data Lake Storage (ADLS).  Link to the update can be found [here](https://docs.microsoft.com/en-us/azure/data-factory/data-factory-service-identity)

It would be super nice, if we can perform this function in Terraform and add the corresponding role to the resource as a one step process.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_data_factory_linked_service_data_lake_storage_gen2

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by pearcec** [comment]
Related #6264
