### ISSUE TITLE
Several connection strings in one App Service

### ISSUE THREAD

**Issue by marchenko-devpro** [terraform-providers/terraform-provider-azurerm#651]
Hi there,

I use Terraform v0.11.1 to create Azure App Service. 
Now I have to add 3 different connection strings to the App. 
If I use standard approach:

  connection_string {
    name  = "Database"
    type  = "SQLServer"
    value = "Server=mydatabase;Integrated Security=SSPI"
 }
connection_string {  
    name  = "Database2"
    type  = "SQLServer"
    value = "Server=mydatabase;Integrated Security=SSPI2"
  }

Terrafrom is going to recreate the connection strings each time I run it. As far as I know, this is a well-known issue. We faced the same behavior during creating Security Group Rules in AWS - https://github.com/hashicorp/terraform/issues/11011

So, my question is how we can define several connection_strings in the Application to avoid recreating them.

Thanks.

**Comment by andydkelly-ig** [comment]
I have a similar issue not sure if it's the same. I have 2 Connection Strings in an Azure App Service and each time i run `terraform plan` it wants to change the order:

`  ~ module.devuat-govern-jobapp.azurerm_app_service.default
      connection_string.0.name:  "AzureWebJobsServiceBus" => "AzureWebJobsDashboard"
      connection_string.0.type:  "ServiceBus" => "Custom"
      connection_string.0.value: <sensitive> => <sensitive> (attribute changed)
      connection_string.1.name:  "AzureWebJobsDashboard" => "AzureWebJobsServiceBus"
      connection_string.1.type:  "Custom" => "ServiceBus"
      connection_string.1.value: <sensitive> => <sensitive> (attribute changed)`

if i allow this change to happen and run terraform plan again i will get

`      ~ module.devuat-govern-jobapp.azurerm_app_service.default
      connection_string.0.name:  "AzureWebJobsDashboard" => "AzureWebJobsServiceBus"
      connection_string.0.type:  "Custom" => "ServiceBus"
      connection_string.0.value: <sensitive> => <sensitive> (attribute changed)`
      connection_string.1.name:  "AzureWebJobsServiceBus" => "AzureWebJobsDashboard"
      connection_string.1.type:  "ServiceBus" => "Custom"
      connection_string.1.value: <sensitive> => <sensitive> (attribute changed)`

Please advise

**Comment by kplantus** [comment]
I have this issue as well where I have 6+ connection strings in single web apps.   I currently have this as a workaround:
`  lifecycle = {
    # to ignore connection strings  # ignore_changes = ["site_config.0.scm_type", "connection_string.0", "connection_string.1", "connection_string.2", "connection_string.3", "connection_string.4", "connection_string.5"]

    # when we need to update connection strings
    ignore_changes = ["site_config.0.scm_type"]
  }`
