### ISSUE TITLE
upgrade to azurerm 2 - multiple providers and child modules

### ISSUE THREAD

**Issue by roeymizrachi** [terraform-providers/terraform-provider-azurerm#6516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12.24
AzureRM 2.0.0

### Affected Resource(s)
Provider block and child modules

### Terraform Configuration Files

```hcl
# provider.tf
provider "azurerm" {
  alias   = "first"
  version = "=2.0.0"
  features {}
}
provider "azurerm" {
  alias           = "second"
  version         = "=2.0.0"
  features {}
}
#-----------------------------------------------------------------------

#main.tf 
module "custom-machine" {
  source             = "./modules/custom-machine"
  location           = var.location
  providers = {
    azurerm.first = azurerm.first
    azurerm.second     = azurerm.second
  }
#-----------------------------------------------------------------------

# custom-machine child module
provider "azurerm" {
  alias = "first"
    # version = "=2.0.0"
  # features {}
}

provider "azurerm" {
  alias = "second"
  # version = "=2.0.0"
  # features {}
}

resource "azurerm_public_ip" "custom-machine-public-ip" {
  provider            = azurerm.first
  #...........................
}

resource "azurerm_network_security_group" "custom-runner-machine-nsg" {
  provider            = azurerm.first
  #...........................
}

data "azurerm_shared_image" "custom-runner-machine-image" {
  provider            = azurerm.second
  #...........................
}
```

### Expected Behavior
Can use multiple provider in the child module.
In my case load shared imaged details from the secondary provider.
In my current project using azurerm 1.4.4 without the 'features' fields all works perfect.

### Actual Behavior
Get error during 'terraform plan'
_**Error: "features": required field is not set**_

### Steps to Reproduce
1. `terraform init`
2. 'terraform plan'

### References

* #0000

**Comment by roeymizrachi** [comment]
anyone? any idea?

**Comment by tombuildsstuff** [comment]
hi @roeymizrachi 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
