### ISSUE TITLE
Feature request: ability to assign multiple ssh keys to the same user 

### ISSUE THREAD

**Issue by dcherniv** [terraform-providers/terraform-provider-azurerm#652]
When provisioning a linux VM or container cluster it would be extremely useful to specify multiple ssh keys for a single admin user.
Right now i'm seeing that only the first key ever gets pushed to the VM:

`linux_profile.2815555209.ssh_key.573875922.key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmaIJIYY6urByLO7Kje+ImZMp
wk32o8apva7aN+McCYSdoyvUgu65veDSfVWB3kLIEZnQqbPqaGnLXNWQpvaRZiA2k5suv7zws48PWfPrZjfy6hBwFnXERVrkcloPIo/MD8P26f6oZVpQrBSWY27
rqI5rtpJmOvss0MA6NBbxoRUApzJkepwcjOUkYvJ61vo+P1/rEIEnyakFSVBCjcVFwhkKjLuno06sbGI/8iXAPZq0PG+ZDbQAV8Msd18YIUvhwC2ewTtO7uEWAK
CVBcOKv8xlZfhNmFJF0ajfR3dXs4jUSo3fcbyd5EovOerL0wD1D+DGiIQb8QRPVwsCq36St user1@localhost\nssh-rsa AAAAB3NzaC1yc2EAAA
ADAQABAAABAQDRwJ8LX4ouF4EhQ2j09HkXhnq2HHZ+QOO57eZUNuL4k3cCkm+gyavTzBctU/otYEPmTHDE+58kXc3plfOD1VfZGseBCSJoULxhN/3yV1qoWjBI4
JH01IsW/UUdstcKiv9LZloq6pzVw3nZq4EuSTfJRywFqerTpwnnzveu1HHTqAvj0uXvBpiBl6DBeBJMEIJ/JF/4kfJJFFbR0jFVTEG+MtDGsnqUMrFBo1bQqFxiVB+lmoClwQh9XfYmV7im3A5evkJ6/1rUQlV5Z1N6BviAKnGO/0rjCloDKY7qWM/MyhAKS7+maIk18wGyVE8XHfPyf5JUIB0UBfisPjYQduq9 user2@localhost\n" => "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmaIJIYY6urByLO7Kje+ImZMpwk32o8apva7aN+McCYSdoyvUgu65veDSfVWB3kLIEZnQqbPqaGnLXNWQpvaRZiA2k5suv7zws48PWfPrZjfy6hBwFnXERVrkcloPIo/MD8P26f6oZVpQrBSWY27rqI5rtpJmOvss0MA6NBbxoRUApzJkepwcjOUkYvJ61vo+P1/rEIEnyakFSVBCjcVFwhkKjLuno06sbGI/8iXAPZq0PG+ZDbQAV8Msd18YIUvhwC2ewTtO7uEWAKCVBcOKv8xlZfhNmFJF0ajfR3dXs4jUSo3fcbyd5EovOerL0wD1D+DGiIQb8QRPVwsCq36St user1@localhost\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRwJ8LX4ouF4EhQ2j09HkXhnq2HHZ+QOO57eZUNuL4k3cCkm+gyavTzBctU/otYEPmTHDE+58kXc3plfOD1VfZGseBCSJoULxhN/3yV1qoWjBI4JH01IsW/UUdstcKiv9LZloq6pzVw3nZq4EuSTfJRywFqerTpwnnzveu1HHTqAvj0uXvBpiBl6DBeBJMEIJ/JF/4kfJJFFbR0jFVTEG+MtDGsnqUMrFBo1bQqFxiVB+lmoClwQh9XfYmV7im3A5evkJ6/1rUQlV5Z1N6BviAKnGO/0rjCloDKY7qWM/MyhAKS7+maIk18wGyVE8XHfPyf5JUIB0UBfisPjYQduq9 user2@localhost\n"`

This should be straightforward to implement, because it is actually more work to parse key_data and pick the first key as opposed just dumping the whole thing to authorized_keys file

**Comment by tombuildsstuff** [comment]
Hey @dcherniv 

Thanks for opening this issue

Unfortunately at this time Azure's limited to only allows specifying a single SSH Key for each user. As such there's no way for us to workaround this at the current time (we're actually submitting the value of the `key_data` field to the Azure API and it's being truncated at Azure's end) - as such I'm going to suggest we close this issue for the moment.

Instead I'd recommend filing a feature request with Microsoft; you can do this either through a Support Ticket, or (given this is an API limitation) by opening a ticket on [the Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs).

Thanks!
