### ISSUE TITLE
azurerm_application_gateway refreshing behavior related to backend_address_pool

### ISSUE THREAD

**Issue by arestarh** [terraform-providers/terraform-provider-azurerm#6520]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
**Terraform v0.12.21
provider.azurerm v2.5.0**

### Affected Resource(s)

* `azurerm_application_gateway`

### Description
With the help of terraform:
1. We've created Application Gateway with 2 Backend Address Pools.
2. We've created 2 VMs.
3. We've associated NICs of those 2 VMs with 2 Backend Address Pools of Application Gateway.
4. We've changed terraform configuration and added 1 VM, 1 Backend Address Pool to Application Gateway and VM NICs association with Backend Address Pool.
5. We've executed **terraform plan** after configuration change from step 4 and got next error:
**azurerm_application_gateway.test.backend_address_pool is list of object with 2 elements 
The given key does not identify an element in this collection value.** 

Seems like it's somewhat expected behavior, but I have feeling that scenario when I wanted to add VM, backend address pool to Application Gateway and associate them worked for me some time ago.

Guys, could you help me with scenario from step 4 ?

**Comment by arestarh** [comment]
Guys, maybe someone can give some useful advice ?
Thanks.

**Comment by tombuildsstuff** [comment]
Thanks for opening this issue.

Taking a look through here this appears to be a bug in Terraform Core - and as such I'm going to close this in favour [of this issue which is tracking this bug](https://github.com/hashicorp/terraform/issues/25578) - would you mind subscribing to that issue for updates?

Thanks!

**Comment by arestarh** [comment]
@tombuildsstuff Sure. Thanks.
