### ISSUE TITLE
Documentation of network_profile_id in azurerm_container_group

### ISSUE THREAD

**Issue by elangelo** [terraform-providers/terraform-provider-azurerm#6562]
I'm trying to deploy a container instance in a subnet of our vnet. Like documented on [https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet](the azure docs) you are supposed to create a dedicated subne. I've tested this by manually creating the container instance and that seems to have worked.

Obviously i wanted to do this with terraform now and i'm stuck.... The documentation mentioned i can provide a 'network_profile_id'. 
>>network_profile_id - (Optional) Network profile ID for deploying to virtual network.

nothing else specified. I've tried to provide it with an azurerm_subnet.{...}.id but it was not happy with this.... just telling me this was an 'InvalidNetworkProfile'... while the reference id did seem to be a valid azure resource 
>> Error: Error creating/updating container group "mycontainergroup" (Resource Group "mycontainergroup-rg"): containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidNetworkProfile" Message="Network profile '/subscriptions/{mysubscriptionid}/resourceGroups/vnet-rg/providers/Microsoft.Network/virtualNetworks/vnetname/subnets/subnetname' is invalid for container group 'mycontainergroup'."

**Comment by r0bnet** [comment]
https://www.terraform.io/docs/providers/azurerm/r/network_profile.html

This is how you create a profile for a delegated subnet. If that's created you can receive the id via `azurerm_network_profile.example.id`.

**Comment by elangelo** [comment]
This does noet seem to be available as a data source? I was trying to use the 
```
## get the vnet / subnet reference
data "azurerm_subnet" "subnet" {
  name                 = var.subnet
  virtual_network_name = var.virtualnetwork
  resource_group_name  = var.network-rg
}```

but the resulting `data.azurerm_subnet.subnet.id` is apparently not usable.

As far as i understand terraform the resource you are linking is going to destory my existing network infrastructure and rebuild it... that is not what i want to do here...

**Comment by elangelo** [comment]
scratch that i just found azurerm_virtual_network data source

**Comment by r0bnet** [comment]
No, it's not destroying it. I'd create the vnet and subnet via TF and then create the profile and use its ID for your purpose. If you don't want to create the vnet and subnet via TF then you can use the data source for the subnet and use it within the profile resource.

**Comment by elangelo** [comment]
OK that didn't help. 
```
data "azurerm_virtual_network" "vnet" {
  name = var.virtualnetwork
  resource_group_name  = var.network-rg
}
``
using it in the container group:
`network_profile_id = data.azurerm_virtual_network.vnet.id`

results in 
>> Error: Error creating/updating container group "mycontainergroup" (Resource Group "mycontainergroup-rg"): containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidNetworkProfile" Message="Network profile '/subscriptions/{mysubscriptionid}/resourceGroups/vnet-rg/providers/Microsoft.Network/virtualNetworks/vnetname' is invalid for container group 'mycontainergroup'."

**Comment by elangelo** [comment]
ok i got it to work after indeed using the resource azurerm_network_profile. At first i did not grasp what it was actually going to do. 
What it actually does is set up the whole network configuration (not creating the vnets/subnets etc etc...)
Gonna blame that on the fact that it is only my second terraform i'm creating. 
Thnx @r0bnet  for the swift help... Closing this now!
