### ISSUE TITLE
Support for hostnames in azurerm_application_gateway to allow for wildcard rules on listener

### ISSUE THREAD

**Issue by tkubica12** [terraform-providers/terraform-provider-azurerm#6579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_application_gateway listener supports only hostname attribute that does not allow for wildcard listener. Azure has added this to API by introducing attribute hostnames that support wildcards. Could this be implemented in this module to support such scenarios?

API docs is here: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-11-01/applicationgateways#applicationgatewayhttplistenerpropertiesformat-object

### New or Affected Resource(s)

* azurerm_application_gateway http_listener

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Hope the fix https://github.com/terraform-providers/terraform-provider-azurerm/pull/6630 is useful.

**Comment by tkubica12** [comment]
Thanks!
