### ISSUE TITLE
changing k8s/nodepool `availability_zones` doesn't cause a recreate

### ISSUE THREAD

**Issue by jstevans** [terraform-providers/terraform-provider-azurerm#6584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`azurerm v1.43.0`
`terraform v0.12.8` 

### Affected Resource(s)

* `azurerm_kubernetes_cluster`
* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "autoscaled" {
  name                  = "autoscaled"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.k8s.id
  vm_size               = var.agent_pool.node_sku
  os_disk_size_gb       = var.agent_pool.os_disk_size_gb

 # step 1: omit availability_zones
# step 2: add the below line to this config
  availability_zones =  ["1", "2", "3"]

  os_type = "Linux"

  enable_auto_scaling = true
  min_count = 3
  max_count = 12
}
```

### Expected Behavior
`autoscaled` gets recreated.

### Actual Behavior
```
# module.aks-validation-eastus-rdi95ri27426.azurerm_kubernetes_cluster_node_pool.autoscaled will be updated in-place
~ resource "azurerm_kubernetes_cluster_node_pool" "autoscaled" {
availability_zones    = [
+"1",
+"2",
+"3",
]
enable_auto_scaling= true
enable_node_public_ip = false
id                    = "<snip>"
kubernetes_cluster_id = "<snip>"
max_count             = 12
mmax_pods              = 30
min_count             = 3
name                  = "autoscaled"
node_count            = 3
node_taints           = []
os_disk_size_gb       = 30
os_type               = "Linux"
vm_size               = "Standard_D8s_v3"
}

<...SNIP...>

Error: Error waiting for update of Default Node Pool "validation-eastus-rdi95ri27426" (Resource Group "validation-eastus-rdi95ri27426"): Code="AgentCountNotMatch" Message="Agent pool agentpool has 0 virtual machines, but expected is 2"
```

### Steps to Reproduce

1. `terraform apply` the terraform config above alongside an `azurerm_kubernetes_cluster`, omitting the `availability_zones` attribute.
1. `terraform apply` the terraform config again, this time including the `availability_zones` attribute.

### Important Facts
Per the notes on the `zones` attribute in [the VMSS REST API docs](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate), I believe `ForceNew` is required on the `availability_zones` attribute for both `azurerm_kubernetes_cluster` and `azurerm_kubernetes_cluster_node_pool`.

**Comment by neil-yechenwei** [comment]
@jstevans , thanks for raising the issue. After tested, seems availability_zones can be updated successfully. Maybe you can try below tfconfig.

first apply:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-aks-test"
  location = "westus2"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestakstest"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "acctestakstest"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "test" {
  name                  = "pooltest"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count             = 1
  max_count             = 3
}
```

Second apply:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-aks-test"
  location = "westus2"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestakstest"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "acctestakstest"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
	availability_zones =  ["1", "2", "3"]
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "test" {
  name                  = "pooltest"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count             = 1
  max_count             = 3
  availability_zones =  ["1", "2", "3"]
}
```

**Comment by tombuildsstuff** [comment]
hey @jstevans 

Thanks for opening this issue - apologies for the delayed response here.

Taking a look into this, the error being returned here:

> Error: Error waiting for update of Default Node Pool "validation-eastus-rdi95ri27426" (Resource Group "validation-eastus-rdi95ri27426"): Code="AgentCountNotMatch" Message="Agent pool agentpool has 0 virtual machines, but expected is 2"

Appears to be an internal inconsistency within the AKS API, rather than something specific to Terraform - as such I'm going to close this issue for the moment but [would you mind raising this issue with on AKS Repository](https://github.com/Azure/AKS/issues)) where the Service Team should be able to take a look?

Thanks!
