### ISSUE TITLE
Include property "license_type" in azurerm_sql_elasticpool

### ISSUE THREAD

**Issue by wtassi** [terraform-providers/terraform-provider-azurerm#6587]
### Description

The resource azurerm_sql_elasticpool cannot insert the property "license_type".

It would be interesting to have this option in Terraform, so you can insert the benefit of Microsoft discounts (for those who own it).

### New or Affected Resource(s)

* azurerm_sql_elasticpool

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_elasticpool" "sql_elastipool" {
  name                = "pool"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  server_name         = azurerm_sql_server.sql_server.name
  edition             = "Standard"
  dtu                 = 50
  db_dtu_min          = 0
  db_dtu_max          = 50
  pool_size           = 102400
  license_type        = "BasePrice"
}

```

**Comment by pearcec** [comment]
[Link](https://docs.microsoft.com/en-us/rest/api/sql/ElasticPools/CreateOrUpdate#elasticpoollicensetype) to REST interface.    It does exist for [azurerm_mssql_database](https://www.terraform.io/docs/providers/azurerm/r/mssql_database.html#license_type).

**Comment by wtassi** [comment]
Hi @pearcec , but it's option in Azure SQL servers, the resource that request is azurerm_sql_database not mssql.

The others options the same resource not create is type GeneralPurpose (Gen5), use vCore configuration.

**Comment by pearcec** [comment]
@wtassi I am looking to see if we should include it in other areas.  So I think we want to add it the [azurerm_sql_database](https://www.terraform.io/docs/providers/azurerm/r/sql_database.html) as well correct?

**Comment by wtassi** [comment]
@pearcec That's right! Exactly.
So, I looked at the resource documentation on Tf. It still doesn’t have the creation of an elastic pool of the azure sql server available in the General purpose type.
Can you evaluate this in this same issue or should you open another?

**Comment by pearcec** [comment]
@wtassi  Uh - I would open a separate issue and link by referencing this issue.  It could be the imported SDK doesn't support it.  That is the case with the the licenseType for database and elastic pools.  I want to check with the maintainers to see if I need to do anything special with bumping SDK version or if acceptance tests are enough.

@tombuildsstuff and @katbyte 👋 Hey I need to bump the SDK version to [preview/sql/mgmt/v3.0/sql](https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/sql/mgmt/v3.0/sql). Kaybyte saw you bumped to v3 in mssql in Jan.  Anything special I need to do or take care of specific to the project?  I am thinking no.

**Comment by pearcec** [comment]
First review the bump is going to cause some changes.  @wtassi I also noticed azurerm_sql_elasticpool is deprecated.  Did azurerm_mssql_elasiticpool replace it?

**Comment by katbyte** [comment]
Hey @wtassi,

You should be able to use the `azurerm_mssql_elasiticpool` resource with the `azurerm_sql_*` resources, and that is the new version of the sql. The old resources will not be updated to the new v3.0 composite SDK so i suggest moving to the new `azurerm_mssql_database` resource as well as the soon to follow later this/next week server.

as this has been added to mssql i'm going to close this out.

**Comment by wtassi** [comment]
Thank you, I will test with the resource azurerm_mssql_database.
:+1: 
:1st_place_medal:
