### ISSUE TITLE
Support for Alias connection string when using azurerm_eventhub_namespace_disaster_recovery_config

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#6593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using azurerm_eventhub_namespace_disaster_recovery_config to build a pairing between two event hub namespaces, all connections to this pair should use the connection string with the alias DNS name instead of the primary connection string. But so far I do not see a way to get this connection string via terraform - short of some ugly string replacement logic. Or did I miss this somehow?

### New or Affected Resource(s)

* azurerm_eventhub_namespace_disaster_recovery_config
* azurerm_eventhub_namespace
* azurerm_eventhub_authorization_rule

### Potential Terraform Configuration

Probably another two properties on `azurerm_eventhub_authorization_rule` would make sense. Something like 
````
alias_primary_connection_string
alias_secondary_connection_string
````
which are only available when a geo-pairing was created.

In the portal this looks today like this (don't worry about the keys being shown ;) ):
![image](https://user-images.githubusercontent.com/11445087/80073796-93152f00-8548-11ea-8bcc-f7afa10056a3.png)

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I can understand it but the fix isn't ready yet. I would continue to work on the fix but have to say there is no timeline for now.
