### ISSUE TITLE
azurerm_network_interface_security_group_association try to recreate existing ressource group

### ISSUE THREAD

**Issue by Kumoservices** [terraform-providers/terraform-provider-azurerm#6594]
Hello 

I migrate a old code from azurerm provider 1.32 with terraform 0.12.17 to 2.6.0 / 0.12.24 version pair.

Taking in count change with azurerm provider 2.x.x, i add the new ressource "azurerm_network_interface_security_group_association", but on apply/plan i have a error because it seems trying to recreate existing resource group

**Part of code :**

resource "azurerm_network_interface" "tad" {
  count                     = var.tad_vm_counter
  name                      = "${var.entity}-${var.keykats}-${var.environment}-nic-${var.app_code}${count.index +1}-001"
  location                  = var.location
  resource_group_name       = azurerm_resource_group.default.name
  internal_dns_name_label   = "${var.app_code}0${count.index + 1}-${var.environment}"

  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.services.id
    private_ip_address_allocation = "static"
    private_ip_address            = lookup(var.tad_private_ip_address, count.index)
 }

  tags = merge(local.mandatory_tags, local.extra_tags)
}

resource "azurerm_network_interface_security_group_association" "tad" {
  count                     = var.tad_vm_counter
  network_interface_id      = azurerm_network_interface.tad.*.id[count.index]
  network_security_group_id = data.azurerm_network_security_group.tad.id
}

**Error message :**

Error: A resource with the ID "xxx-xxxx-xxx-rgp-tad-001" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_network_interface_security_group_association" for more information.

  on virtual_machines.tf line 45, in resource "azurerm_network_interface_security_group_association" "tad":
  45: resource "azurerm_network_interface_security_group_association" "tad" {

Thx for your help

**Comment by pearcec** [comment]
It isn't trying to recereate it.  Terraform is telling you the resources exists but it wasn't found in the state.  So it is asking you to import it.  I would read through the documentation for [importing](https://www.terraform.io/docs/providers/azurerm/r/network_interface_security_group_association.html#import).  Or you could remove it by hand in the portal and let Terraform create it.

**Comment by Kumoservices** [comment]
azurerm_resource_group.default: Importing from ID "/subscriptions/********-*****-****-****-***********/resourceGroups/***-****-***-tad-rgp-001"...
azurerm_resource_group.default: Import prepared!
  Prepared azurerm_resource_group for import

Error: Resource already managed by Terraform

Terraform is already managing a remote object for
azurerm_resource_group.default. To import to this address you must first
remove the existing object from the state.

**Comment by pearcec** [comment]
Please provide a full DEBUG output and the command you ran.

**Comment by Kumoservices** [comment]
The Import command run was (part of homebuild pipeline shell) :

${TF_VERSION}/terraform import -var environment=${TF_VAR_env} -var-file=./environments/${TF_VAR_env}.tfvars -lock=false azurerm_resource_group.default /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/***-****-***-tad-rgp-001

**Comment by pearcec** [comment]
Looks to me like you are trying to import the resource group.  You need to import the azurerm_network_interface_security_group_association

**Comment by Kumoservices** [comment]
i will give you the debug log in some minutes ...

Sorry but the error message is : Error: A resource with the ID "xxx-xxxx-xxx-rgp-tad-001" already exists ...

So in my understanding, that was normal to try to import it as it ask me :

the azurerm_network_interface_security_group_association resource is added by my terraform changes, it seems to me so normal that is it not be included in the tfstate before apply it.

Notes: 
rgp naming is ressource group for me for information.

Debug log :  
[debug_tf.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/4523073/debug_tf.log)

**Comment by Kumoservices** [comment]
there is something near my issue here : https://github.com/Azure/terraform-azurerm-network-security-group/issues/47

in this case , the developper said on fix : "Before, by default, it'll create a resource group. Now we import an existing resource group. So there is no default name for an existing resource group."

it is not the same case on  "azurerm_network_interface_security_group_association" ??

**Comment by njuCZ** [comment]
@Kumoservices Thanks for pointing this problem. You should import the `azurerm_network_interface_security_group_association` but not `azurerm_resource_group`. The ID information in the error msg is wrong. It should print the id of `azurerm_network_interface_security_group_association`. I have submited a PR to fix it.

**Comment by Kumoservices** [comment]
Hi, thanks !

Just for your information i try now to import the ressource in the tfstate but it failed too 👍 

My terraform command :

${TF_VERSION}/terraform import -var environment=${TF_VAR_env} -var-file=./environments/${TF_VAR_env}.tfvars -lock=false azurerm_network_interface_security_group_association.tad /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/***-*****-***-tad-rgp-001/providers/microsoft.network/networkInterfaces/***-*****-***-nic-tad1-001/ipConfigurations/primary|/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/**********rgp001/providers/Microsoft.Network/networkSecurityGroups/***-*****-***-nsg-ser-tad

note : i have masked sensible naming / subscription id 

Terraform tell me this error message now i try to import the right ressource :
 /subscriptions/***-***-***-***-***/resourceGroups/**********rgp001/providers/Microsoft.Network/networkSecurityGroups/***-*****-***-nsg-ser-tad: No such file or directory
