### ISSUE TITLE
Support for Streaming Endpoints

### ISSUE THREAD

**Issue by sam-mundle** [terraform-providers/terraform-provider-azurerm#6597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hoping to get support for the creation and manipulation of Media Streaming Endpoints.

### New or Affected Resource(s)

* azurerm_media_streaming_endpoint

### Potential Terraform Configuration

```hcl
resource "azurerm_media_streaming_endpoint" "streaming" {
  name                     = "streaming-dev-eastus"
  resource_group_name      = azurerm_resource_group.streaming.name
  scale-units              = ...
  auto-start               = ...
  availability-set-name    = ...
  cdn-profile              = ...
  cdn-provider             = ...
  client-access-policy     = ...
  cross-domain-policy      = ...
  custom-host-names        = ...
  description              = ...
  ips                      = ...
  max-cache-age            = ...
  no-wait                  = ...
  only-show-errors         = ...
  subscription             = ...
  tags                     = ...
}
```

### References

* https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-streaming-endpoints-overview

**Comment by jcanizalez** [comment]
I'm working on this issue

**Comment by jcanizalez** [comment]
I created PR 9537 that resolves this issue
