### ISSUE TITLE
Data Source: azurerm_eventhub_namespace_authorization_rule | documentation error 

### ISSUE THREAD

**Issue by cdproyect** [terraform-providers/terraform-provider-azurerm#6598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
provider.azurerm v1.44.0

### Affected Resource(s)

* `azurerm_eventhub_namespace_authorization_rule`

### Terraform Configuration Files

https://gist.github.com/cdproyect/47e76a734f14079676036628248941c9

### Debug Output

https://gist.github.com/cdproyect/42858f05e2c5a7ebf7ebaaf0277895e2
### Expected Behavior

I follow up the official Terraform documentation [here](https://www.terraform.io/docs/providers/azurerm/d/eventhub_namespace_authorization_rule.html), I was expected to be able to have a successful terraform plan to  add the datasource related Authorization Rule for an Event Hub Namespace.

### Actual Behavior

Error: Missing required argument

  on datasources.tf line 105, in data "azurerm_eventhub_namespace_authorization_rule" "sumonamespaceauth":
 105: data "azurerm_eventhub_namespace_authorization_rule" "sumonamespaceauth" {

The argument "namespace_name" is required, but no definition was found.

**I was able to get around** the terraform plan error by adding the argument **"namespace_name"**. 

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. It's a good suggestion. We are working on the fix but there is no timeline for now.
