### ISSUE TITLE
azurerm_eventhub_namespace_authorization_rule unable to get id

### ISSUE THREAD

**Issue by cdproyect** [terraform-providers/terraform-provider-azurerm#6599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
provider.azurerm v1.44.0
### Affected Resource(s)

* `azurerm_eventhub_namespace_authorization_rule`

### Terraform Configuration Files

https://gist.github.com/cdproyect/3f9de6ae831f42eb1c8e88b7a3ce7f3c
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/cdproyect/f9ed0ca17f3149b7eab16a75289a59e5
### Expected Behavior

I should have been able to create a monitor diagnostic setting with azurerm_monitor_diagnostic_setting, I follow up the official docs [here](https://www.terraform.io/docs/providers/azurerm/r/monitor_diagnostic_setting.html). 

I am receiving the following error, even though I defined eventhub_authorization_rule_id using a value extracted from Datasource. 
```
rror: Either a `eventhub_authorization_rule_id`, `log_analytics_workspace_id` or `storage_account_id` must be set

  on appgateways-preprod.tf line 149, in resource "azurerm_monitor_diagnostic_setting" "agw-nimpreprod-diagnostic-eventhub":
 149: resource "azurerm_monitor_diagnostic_setting" "agw-nimpreprod-diagnostic-eventhub" {
```

The data source "data.azurerm_eventhub_namespace_authorization_rule.sumonamespaceauth.id" should have the value of the resource id associated to eventhub_namespace_authorization_rule, however, it returns an empty value, when query the value from the terraform console.

```
2020/04/23 14:41:27 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
Acquiring state lock. This may take a few moments...
> data.azurerm_eventhub_namespace_authorization_rule.sumonamespaceauth.id
null
>
```
The eventhub_namespace_authorization_rule exists, below is the output from az cli
```
az eventhubs namespace authorization-rule show --resource-group RGP-VA-xxx1-STAGE --namespace-name SumoAzureLogsNamespace-VA-STAGE --name RootManageSharedAccessKey
{
  "id": "/subscriptions/xxxxxxxx-yyyy-yyyy-yyyy-xxxxxxxxxxxx/resourceGroups/RGP-VA-xxx1-STAGE/providers/Microsoft.EventHub/namespaces/SumoAzureLogsNamespace-VA-STAGE/AuthorizationRules/RootManageSharedAccessKey",
  "location": "East US",
  "name": "RootManageSharedAccessKey",
  "resourceGroup": "RGP-VA-xxx1-STAGE",
  "rights": [
    "Listen",
    "Manage",
    "Send"
  ],
  "type": "Microsoft.EventHub/Namespaces/AuthorizationRules"
}
```
### Steps to Reproduce

1. `terraform apply`

### References

Please be aware that I have also submit [another issue 6598 ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6598) for this same data source * `azurerm_eventhub_namespace_authorization_rule`, which can be related. 

* #0000

**Comment by neil-yechenwei** [comment]
@cdproyect , thanks for opening this issue. After tested, seems there is value from the output of data source "data.azurerm_eventhub_namespace_authorization_rule.test.id". Seems I cannot repro the issue with below config. Maybe I missed something. If you need, you can try below config and check whether the problem still exists. If still exists, could you provide a simplest tf config for further investigation? Thanks.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-ehnar-ddd"
  location = "eastus"
}

resource "azurerm_eventhub_namespace" "test" {
  name                = "acctesteventhubnamespace-ddd"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Standard"
}

resource "azurerm_eventhub_namespace_authorization_rule" "test" {
  name                = "acctest-EHN-ARddd"
  namespace_name      = azurerm_eventhub_namespace.test.name
  resource_group_name = azurerm_resource_group.test.name

  listen = true
  send   = true
  manage = true
}

data "azurerm_resource_group" "test" {
  name = "acctestRG-ehnar-ddd"
}

data "azurerm_eventhub_namespace" "test" {
  name                = "acctesteventhubnamespace-ddd"
  resource_group_name = data.azurerm_resource_group.test.name
}

data "azurerm_eventhub_namespace_authorization_rule" "test" {
  name                = "RootManageSharedAccessKey"
  namespace_name      = data.azurerm_eventhub_namespace.test.name
  resource_group_name = data.azurerm_resource_group.test.name
}

output "eventhub_namespace_authorization_rule_id" {
  value = data.azurerm_eventhub_namespace_authorization_rule.test.id
}
```

Result:
```
Outputs:

eventhub_namespace_authorization_rule_id = /subscriptions/xxxx-xxx-xxx-xxx/resourceGroups/acctestRG-ehnar-ddd/providers/Microsoft.EventHub/namespaces/acctesteventhubnamespace-ddd/AuthorizationRules/RootManageSharedAccessKey
```

**Comment by mybayern1974** [comment]
Hi @cdproyect 

May we close this issue by assuming neil-yechenwei’s reply has answered your question? Feel free to reopen this if you do not think so. Thank you.

**Comment by cdproyect** [comment]
Hello Neil, sorry for my late response
The only difference I see in your proposed file, is the addition of
" features {} " 

I cannot use that attribute with the version the azurerm version "~>1.29"
As previously explained the issue is that I am receiving a null value for the data.azurerm_eventhub_namespace_authorization_rule.sumonamespaceauth.id
