### ISSUE TITLE
Question: Does the name used with azurerm_network_security_rule need to be unique?

### ISSUE THREAD

**Issue by runecalico** [terraform-providers/terraform-provider-azurerm#660]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
- azurerm_network_security_rule

### Terraform Configuration Files

I was expecting that as long as I use unique resource names, that I could use generic (thus the same) NSG rule names, as the portal allows this... However this doesn't seem to be the case. 
When I have NSG rules like so...

```hcl
resource "azurerm_network_security_rule" "snCmpUatApp_O_116" {
  name                        = "snCmpDataCus_Datastax_JMX_9042"
  description                 = "snCmpDataCus_Datastax_JMX_9042"
  priority                    = 116
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "tcp"
  source_port_range           = "*"
  destination_port_range      = "9042"
  source_address_prefix       = "172.30.21.32/28"
  destination_address_prefix  = "172.30.7.150/32"
  resource_group_name         = "${var.vnet_rg_name}"
  network_security_group_name = "${azurerm_network_security_group.snCmpUatApp.name}"
}

resource "azurerm_network_security_rule" "snCmpUatApp_O_117" {
  name                        = "snCmpDataCus_Datastax_JMX_9042"
  description                 = "snCmpDataCus_Datastax_JMX_9042"
  priority                    = 117
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "tcp"
  source_port_range           = "*"
  destination_port_range      = "9042"
  source_address_prefix       = "172.30.21.32/28"
  destination_address_prefix  = "172.30.7.151/32"
  resource_group_name         = "${var.vnet_rg_name}"
  network_security_group_name = "${azurerm_network_security_group.snCmpUatApp.name}"
}
```

and after you build it, you would see stuff like this in a terraform plan..
```
  ~ azurerm_network_security_rule.snCmpUatApp_O_120
      priority:                    "122" => "120"
```

etc. Basically it will switch the priority between the two "same" nsg rules, but not switch the destination_address_prefix.

### Expected Behavior
What should have happened?

terraform would create two rules, priority 116 and priority 117.

### Actual Behavior
What actually happened?

Terraform will create one rule (usually the first one, so snCmpUatApp_O_116 in this example), but not the second one (snCmpUatApp_O_117). Subsequent plan/applies will see terraform "flip" the priority values between the two rules, but not the difference destination_address_prefix. Every time you run plan/apply.

Changing the name to something else (so it's not identical) will correct this issue. Is this a bug or by design? (aka because of how the API is, using identical named nsg rules don't really work despite what you can do in the portal)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by bhushangholve2006** [comment]
Hi @runecalico ,

I suppose you are creating 2 rules for same port and it is taking only one that is on priority...
I was thinking why would anyone create same rule for same port with different priority?
And if you are creating it anyways then it should create only one with highest priority.
Try changing the destination port i think it will create two rules...

Thanks

**Comment by tombuildsstuff** [comment]
hey @runecalico 

Thanks for opening this issue :)

Indeed, the names of each Network Security Rule need to be unique within each Network Security Group. The issue you're seeing here (with the two resources conflicting) is due to the way Azure's API is an Upsert (in that it'll update an existing entry if it already exists, otherwise create a new one) and with both sharing the same name updating one is overwriting the value for the other.

Would you be able to take a look and see if using unique names for each Network Security Rule solves your issue here?

Thanks!

**Comment by runecalico** [comment]
@tombuildsstuff 

Yes, if I use different values for "name" everything works as expected. I submitted this inquiry to determine if it was a terraform bug, or just an Azure behavior.   From your explanation, I get the impression that this is an expected behavior on Azure due to the API and that using the same value for "name" as well as the same values for other fields causes the API to not be able to differentiate between the rules.

Using different values for the "name" field solves this issue completely, I just wanted to know why :).

@bhushangholve2006 
The reason I am creating two (or more) rules for the same port, but different priority is because we are restricting either the source or destination prefix to individual hosts (not entire subnets), and as you can't provide a list of IP's... If you are going to restrict a particular network service to say... 10 specific hosts that are NOT in the same subnet... That means 10 rules where the only different between the rules is the priority and and source/dest restriction.  I used the same names because I'm lazy and wanted the name to reflect the service & port.  

I'll just change the name to something like service_priority_port or some such where it's unique.
