### ISSUE TITLE
azurerm_api_management_api_version_set fails to update or craeate after 2.7.0

### ISSUE THREAD

**Issue by jonatasbaldin** [terraform-providers/terraform-provider-azurerm#6609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.23
+ provider.azurerm v2.7.0
```

### Affected Resource(s)
* `azurerm_api_management_api_version_set`

### Terraform Configuration Files
```hcl
resource "azurerm_api_management_api_version_set" "example" {
  name                = "example-apimapi"
  resource_group_name = var.resource_group_name
  api_management_name = var.apim_name
  display_name        = "ExampleAPIVersionSet"
  versioning_scheme   = "Segment"
}

resource "azurerm_api_management_api" "example" {
  name                = "example-api"
  resource_group_name = var.resource_group_name
  api_management_name = var.apim_name
  revision            = "1"
  display_name        = "Example API"
  path                = "example_me"
  protocols           = ["https"]
  service_url         = "https://conferenceapi.azurewebsites.net/"
  version             = "v1"
  version_set_id      = azurerm_api_management_api_version_set.example.id


  import {
    content_format = "swagger-link-json"
    content_value  = "http://conferenceapi.azurewebsites.net/?format=json"
  }
}
```

### Debug Output
Will try to include later. This is a private Terraform configuration, there's probably sensitive information in the DEBUG.

### Expected Behavior
After updating to `2.7.0` I expected APIM to keep working.

### Actual Behavior
The `azurerm_api_management_api_version_set` fails to **update** with the following error:
```bash
Error: creating/updating API "example-api" / Revision "1" (API Management Service "apimgmt-rnd-ui" / Resource Group "rg-infra-rnd"):
apimanagement.APIClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ValidationError" Message="One or more fields contain incorrect values:"

Details=[{"code":"ValidationError","message":"Parsing error(s): An error occured while parsing the input. Message: Value /api-version-sets/example-apimapi doesn't match required format /apiVersionSets/{id}","target":"representation"}]
```

I tried to remove and create again, then got this error:
```bash
Error: making Read request for Api Version Set "" (Resource Group "rg-infra-rnd" / Api Management Service "apimgmt-rnd-ui"):
apimanagement.APIVersionSetClient#Get: Invalid input: autorest/validation: validation failed: parameter=versionSetID constraint=MinLength value=""
details: value length must be greater than or equal to 1
```

### Steps to Reproduce

1. `terraform apply`

### References
This is probably related to #5769 and/or #6479.

**Comment by nzthiago** [comment]
@katbyte fyi

**Comment by mhennecke** [comment]
In the meantime, for anyone running into this issue, following workaround works for me:
`version_set_id = replace(azurerm_api_management_api_version_set.api.id, "api-version-sets", "apiVersionSets")`
