### ISSUE TITLE
Associate azurerm_network_security_group with subnet

### ISSUE THREAD

**Issue by bhushangholve2006** [terraform-providers/terraform-provider-azurerm#661]
Hi there,

I have encountered this issue while spinning up infrastructure using terraform. I have my vpn and subnet ready with me and I am creating network security group for my existing subnet. But I did not find the way to associate existing subnet with network security group. 

### Terraform Version
Terraform v0.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
-`azurerm_network_security_group`
-`subnet`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
provider "azurerm" {
  version = "1.0.0"
  subscription_id = "${var.azure_subscription_key}"
  client_id       = "${var.azure_client_id}"
  client_secret   = "${var.azure_client_secret}"
  tenant_id       = "${var.azure_tenant_id}"
}

# Create Network Security Group and rule
resource "azurerm_network_security_group" "terraformnsg" {
    name                = "${var.azure_network_security_group}"
    location            = "${var.azure_region}"
    resource_group_name = "${var.resource_group}"   
}
```
### Debug Output
terraform successfully created network security group.

### Expected Behavior
It is creating expected network security group but don't know how i can associate existing subnet or subnets with it.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I am serching for this from days how I can do association with of azurerm nsg with existing subnet.
It is being easy when i create nsg first and then create subnet and make the association.
But i have subnets ready just want to create nsg and make association with existing subnet.

### References
referred this document : [https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html](https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html)

**Comment by tombuildsstuff** [comment]
Hi @bhushangholve2006 

Thanks for opening this issue

Configuring the Subnet to use a Network Security Group can be done using [the `network_security_group_id` property in `azurerm_subnet` resource](https://www.terraform.io/docs/providers/azurerm/r/subnet.html#network_security_group_id) e.g.

```
resource "azurerm_resource_group" "test" {
  # ..
}

resource "azurerm_virtual_network" "test" {
  # ..
}

resource "azurerm_network_security_group" "test" {
  # ..
}

resource "azurerm_subnet" "test" {
  name                      = "testsubnet"
  resource_group_name       = "${azurerm_resource_group.test.name}"
  virtual_network_name      = "${azurerm_virtual_network.test.name}"
  address_prefix            = "10.0.1.0/24"
  network_security_group_id = "${azurerm_network_security_group.test.id}"
}
```

Given this is an issue with the Terraform Configuration and not a bug in the AzureRM Provider - I'm going to close this issue for the moment; but feel free to reply to this and we'll take another look if you're still having issues :)

Thanks!

**Comment by bhushangholve2006** [comment]
Hey Hi @tombuildsstuff ,

I know this resolution I can associate network security group with subnet while creating subnet using terraform.
My issue is "I have subnet and vpn ready with me and I want to create network security group" that is associated with my existing subnet."
we have vpn and subnet with us and we need to create further infrastructure in it. starts with network security group and i am not able to associate existing subnet while creating network security group.
