### ISSUE TITLE
Argument default_ttl_seconds wants to be still replaced in azurerm_cosmosdb_mongo_collection

### ISSUE THREAD

**Issue by PeterUherek** [terraform-providers/terraform-provider-azurerm#6611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `terraform - v0.12.24`
* `azurerm -  2.3.0`

### Affected Resource(s)

* `azurerm_cosmosdb_mongo_collection`

### Terraform Configuration Files

```hcl
data "azurerm_cosmosdb_account" "example" {
  name                = "tfex-cosmosdb-account"
  resource_group_name = "tfex-cosmosdb-account-rg"
}

resource "azurerm_cosmosdb_mongo_database" "example" {
  name                = "tfex-cosmos-mongo-db"
  resource_group_name = data.azurerm_cosmosdb_account.example.resource_group_name
  account_name        = data.azurerm_cosmosdb_account.example.name
}

resource "azurerm_cosmosdb_mongo_collection" "example" {
  name                = "tfex-cosmos-mongo-db"
  resource_group_name = data.azurerm_cosmosdb_account.example.resource_group_name
  account_name        = data.azurerm_cosmosdb_account.example.name
  database_name       = azurerm_cosmosdb_mongo_database.example.name

  default_ttl_seconds = "345600"
  shard_key           = "_id"
}
```

### Expected Behavior
Terraform will not replace the default_ttl_seconds value if it was not changed.

### Actual Behavior
Terraform replaces argument default_ttl_seconds in every run. 

```
~ default_ttl_seconds = 0 -> 345600
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by neil-yechenwei** [comment]
@PeterUherek , thanks for opening this issue. After tested, seems there is no diff between first apply and second apply with below tfconfig. Seems I cannot repro the issue. Maybe I missed something. If you need, you can try below config and check whether the problem still exists. Thanks.

My test steps:
Run below tfconfig with `terraform apply`:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-cosmos-neil"
  location = "eastus2"
}

resource "azurerm_cosmosdb_account" "test" {
  name                = "acctest-ca-neil"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    location          = azurerm_resource_group.test.location
    failover_priority = 0
  }
}

data "azurerm_cosmosdb_account" "test" {
  name                = azurerm_cosmosdb_account.test.name
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_cosmosdb_mongo_database" "test" {
  name                = "tfex-cosmos-mongo-db"
  resource_group_name = data.azurerm_cosmosdb_account.test.resource_group_name
  account_name        = data.azurerm_cosmosdb_account.test.name
}

resource "azurerm_cosmosdb_mongo_collection" "test" {
  name                = "tfex-cosmos-mongo-db"
  resource_group_name = data.azurerm_cosmosdb_account.test.resource_group_name
  account_name        = data.azurerm_cosmosdb_account.test.name
  database_name       = azurerm_cosmosdb_mongo_database.test.name

  default_ttl_seconds = "345600"
  shard_key           = "_id"
}
```

The result of running `tf plan`:
```
------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

The result of running `terraform apply` with above tfconfig again:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by PeterUherek** [comment]
I forget add this code:
```
provider "azurerm" {
  version = "2.3.0"
  features {}
}
```

I can simulate at azurerm with the 2.3.0 version, but I can not simulate with the 2.7.0 version.  It looks like it was somehow fixed.

**Comment by mybayern1974** [comment]
Hi @PeterUherek 

Glad to see you’ve got unblocked : ) Would you ok we close this issue for now? Feel free to reopen it if you run into it again. Thank you.
