### ISSUE TITLE
azurerm_api_management_diagnostic fails after 2.7.0

### ISSUE THREAD

**Issue by rvilike** [terraform-providers/terraform-provider-azurerm#6619]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
azurerm v2.7.0

### Affected Resource(s)

* `azurerm_api_management_diagnostic`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "apim" {
  name = var.name
  location = var.location
  resource_group_name = var.resource_group_name
  publisher_name = var.publisher_name
  publisher_email = var.publisher_email
  sku_name = var.sku_name

  virtual_network_type = var.virtual_network_type
  virtual_network_configuration {
    subnet_id = var.subnet_id
  }

  tags = var.tags
}

resource "azurerm_api_management_logger" "apim-logger" {
  name = var.name
  api_management_name = azurerm_api_management.apim.name
  resource_group_name = var.resource_group_name

  application_insights {
    instrumentation_key = var.appinsights_instrumentation_key
  }
}

resource "azurerm_api_management_diagnostic" "apim-diagnostic" {
  identifier = "applicationinsights"
  api_management_name = azurerm_api_management.apim.name
  resource_group_name = var.resource_group_name
}
```

### Expected Behavior

APIM diagnostic gets created

### Actual Behavior

Creating APIM diagnostic fails with:
`Error: creating or updating Diagnostic "applicationinsights" (Resource Group "..." / API Management Service "..."): apimanagement.DiagnosticClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.DiagnosticContractProperties.LoggerID constraint=Null value=(*string)(nil) details: value can not be null; required parameter`

### Steps to Reproduce

1. `terraform apply`

### References

* #6479

**Comment by yupwei68** [comment]
hi @rvilike ,thanks for opening this issue. This is a regression bug. And we will fix it by adding `logger_id` in `azurerm_api_management_diagnostic` later.

**Comment by evertonmc** [comment]
> This is a regression bug.

yes, and also the reason for #6104
