### ISSUE TITLE
azurerm_function_app fails name can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long in 2.7

### ISSUE THREAD

**Issue by enorlando** [terraform-providers/terraform-provider-azurerm#6633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.24
+ provider.azurerm v2.7.0
### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

This terraform code works fine in 2.5 and older:
```hcl

resource "azurerm_storage_account" "example" {
  name                      = "example"
  resource_group_name       = azurerm_resource_group.example.name
  location                  = var.location
  account_kind              = "Storage"
  account_tier              = "Standard"
  enable_https_traffic_only = false
  account_replication_type  = "LRS"

resource "azurerm_function_app" "example" {
  name                       = "exampleg"
  location                   = var.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.id
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
```

### Debug Output

```hcl
Error: name ("/subscriptions/710a352d-bb2f-4cff-9b8a-976d46f9479a/resourceGroups/prd-ctx-shared-services/providers/Microsoft.Storage/storageAccounts/prdctxopsintelfunction") can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long
```

### Expected Behavior

No infrastructure changes since we are just updating the provider. The storage account name only consists of letters and is 22 characters long

### Actual Behavior

error when running a terraform plan

### Steps to Reproduce

1.  Update provider azurerm provider block from 2.5.0 to 2.7.0
2. `terraform plan`

### References

* #0000

**Comment by JSkimming** [comment]
The documentation is incorrect.

Change 

```
  storage_account_name       = azurerm_storage_account.example.id
```

to

```
  storage_account_name       = azurerm_storage_account.example.name
```

I've raised #6641 to fix the documentation.

**Comment by enorlando** [comment]
@JSkimming 
Thank you. That fixed my issue. Appreciated
