### ISSUE TITLE
Support additional parameters like hbi_workspace in azurerm_machine_learning_workspace

### ISSUE THREAD

**Issue by devnadgir** [terraform-providers/terraform-provider-azurerm#6634]
Some additional parameters needs to be updated as per - https://docs.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/2020-03-01/workspaces

**Comment by ArcturusZhang** [comment]
This issue should have been fixed by PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/7703
