### ISSUE TITLE
azurerm_network_interface_security_group_association : Cannot import the ressource

### ISSUE THREAD

**Issue by Kumoservices** [terraform-providers/terraform-provider-azurerm#6638]
Hello,

After opening this case : https://github.com/terraform-providers/terraform-provider-azurerm/issues/6594

I try now to import the ressource in the tfstate but it failed too  !

My terraform command :

${TF_VERSION}/terraform import -var environment=${TF_VAR_env} -var-file=./environments/${TF_VAR_env}.tfvars -lock=false azurerm_network_interface_security_group_association.tad /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/xxx-xxxxx-xxx-tad-rgp-001/providers/microsoft.network/networkInterfaces/xxx-xxxxx-xxx-nic-tad1-001/ipConfigurations/primary|/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/xxxxxxxxxxrgp001/providers/Microsoft.Network/networkSecurityGroups/xxx-xxxxx-xxx-nsg-ser-tad

(note : i have masked sensible naming / subscription id)

Terraform tell me this error message now i try to import the right ressource :
 /subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/xxxxxxxxxxxrgp001/providers/Microsoft.Network/networkSecurityGroups/xxx-xxxxx-xxx-nsg-ser-tad: No such file or directory

I have also check to use the right {networkInterfaceId}|{networkSecurityGroupId} ID pair for the import command

Note too, my NSG is in a different resource group than the NIC.

Any Idea ??

**_Notice :_** 

The terraform documentation said for the import command :
terraform import azurerm_network_interface_security_group_association.association1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/microsoft.network/networkInterfaces/nic1/ipConfigurations/example|/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Network/networkSecurityGroups/**group1**

First, the doc says import command use the format : {networkInterfaceId}**/**|{networkSecurityGroupId}.
I think it should be {networkInterfaceId}|{networkSecurityGroupId} ...

Second, The import command specify group1 in place of the name of the NSG in the command example.

**Comment by njuCZ** [comment]
@Kumoservices thanks for pointing this problem, there is some problem with the doc. I have submitted a PR to update it.
I have tried in my local and succeed with no problems

![tempsnip](https://user-images.githubusercontent.com/2786738/80447069-fd641000-894a-11ea-9e92-7cd47d828f20.png)

**Comment by Kumoservices** [comment]
thanks 👍
