### ISSUE TITLE
azurerm_network_security_group with existing subnet

### ISSUE THREAD

**Issue by bhushangholve2006** [terraform-providers/terraform-provider-azurerm#664]
Hi there,

I have encountered this issue while spinning up infrastructure using terraform. I have my vpn and subnet ready with me and I am creating network security group for my existing subnet. But I did not find the way to associate existing subnet with network security group. 

### Terraform Version
Terraform v0.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
-`azurerm_network_security_group`
-`subnet`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
provider "azurerm" {
  version = "1.0.0"
  subscription_id = "${var.azure_subscription_key}"
  client_id       = "${var.azure_client_id}"
  client_secret   = "${var.azure_client_secret}"
  tenant_id       = "${var.azure_tenant_id}"
}

# Create Network Security Group and rule
resource "azurerm_network_security_group" "terraformnsg" {
    name                = "${var.azure_network_security_group}"
    location            = "${var.azure_region}"
    resource_group_name = "${var.resource_group}"   
}
```
### Debug Output
terraform successfully created network security group.

### Expected Behavior
It is creating expected network security group but don't know how i can associate existing subnet or subnets with it.

### **My Question here**
**Is it possible to associate existing subnet while creating azurerm_network_security_group ?**
**If it is possible then what parameters i need to use how its done?**

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I am serching for this from days how I can do association with of azurerm nsg with existing subnet.
It is being easy when i create nsg first and then create subnet and make the association.
But i have subnets ready just want to create nsg and make association with existing subnet.

### References
referred this document : [https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html](https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html)
#661

**Comment by tombuildsstuff** [comment]
Hi @bhushangholve2006 

Thanks for opening this issue :)

> Is it possible to associate existing subnet while creating azurerm_network_security_group ?
> But i have subnets ready just want to create nsg and make association with existing subnet.

Given that Network Security Groups are assigned to the Subnets (e.g. on the `azurerm_subnet` resource) the Subnet will need to be managed by Terraform. It's possible to import existing resources into Terraform using [the `terraform import` command](https://www.terraform.io/docs/import/usage.html) - in this case [there's an example for importing the `azurerm_subnet` resource here](https://www.terraform.io/docs/providers/azurerm/r/subnet.html#import).

Once the resource is imported you should be able to update the Subnet to include the Network Security Group by setting the `network_security_group_id` field and running `terraform plan` / `terraform apply`. Would you be able to take a look?

Thanks!

**Comment by bhushangholve2006** [comment]
Hi @tombuildsstuff ,

Thank you very much for the reply. I am trying your solution now.
Will give you reply in some time.

Thanks

**Comment by bhushangholve2006** [comment]
Resolved this using mentioned suggestions.
Thank you @tombuildsstuff 
Closing this.
