### ISSUE TITLE
Azure API Management Virtual Network with Multiple Locations

### ISSUE THREAD

**Issue by sam-cogan** [terraform-providers/terraform-provider-azurerm#6642]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
12.24
2.7.0

### Affected Resource(s)

* `azurerm_api_management`

### Expected Behavior

It is possible to deploy an instance of APIM in multiple locations using the "additional_location" property. It is also possible to attach an APIM to virtual network, however it seems that Terraform only provides the ability to set a single subnet ID, which does not work where you have multiple locations, as each location will use a different subnet ID. I would expect to have the ability to provide a subnet ID for each location.

### Actual Behavior

It does not seem possible to specify a subnet ID for each location

* #0000

**Comment by yupwei68** [comment]
hi @sam-cogan , Thanks for opening this issue. This enhancement currently is not supported from service team. You could open an issue to ask for new enhancement in service team https://github.com/Azure/azure-rest-api-specs/issues

**Comment by sam-cogan** [comment]
Thanks, I have created an issue for this - https://github.com/Azure/azure-rest-api-specs/issues/9255

**Comment by danbyrne-tal** [comment]
@yupwei68 , as per comments on the related REST API & provided sample - this already is possible via REST API... using the 'additionallocations' section... see example here - https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apimanagementservice/get#apimanagementservicegetmultiregioninternalvnet 

Can this be accommodated in the TF provider now?

**Comment by jake-scott** [comment]
Sorry about all the commits.  The linter is picky 😃  please test this and let me know if it resolves the issue.
