### ISSUE TITLE
Azure SQL Not supporting "memory_usage_percent" metric on monitor (azure gov)

### ISSUE THREAD

**Issue by Danielperga97** [terraform-providers/terraform-provider-azurerm#6644]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.7.0

### Affected Resource(s)
azurerm_monitor_metric_alert (for "Microsoft.Sql/servers/databases")

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "azuredb_Memory_Rule" {
  name                = "Azure SQL  Memory Alert"
  resource_group_name =  "my-rg"
  scopes              = [mydb.id]
  description         = "Action will be triggered when Memory is too close to limit."
  frequency           = "PT1M"


  criteria {
    metric_namespace =  "Microsoft.Sql/servers/databases"
    metric_name      = "memory_usage_percent"
    aggregation      = "Maximum"
    operator         = "GreaterThan"
    threshold        = 50

  }

  action {
    action_group_id = slack_action_group.id
  }
}
```

### Debug Output
Error: Error creating or updating metric alert "Azure SQL CC Memory Alert" (resource group "systest-command-center-data-chp-rg"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The metric names were not found memory_usage_percent."

  on .terraform/modules/azure-monitor-command-center/azure-monitor.tf line 126, in resource "azurerm_monitor_metric_alert" "azuredb_CC_Memory_Rule":
 126: resource "azurerm_monitor_metric_alert" "azuredb_CC_Memory_Rule" {

### Expected Behavior

Resource created

### Actual Behavior

Error creating the resource
### Steps to Reproduce

create an alert for an azure SQL db for memory_usage_percent metric

### References
documentation says this metric is supported for this resource:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported

**Comment by yupwei68** [comment]
Hi @Danielperga97 , thanks for opening this issue. Azure SQL db for memory_usage_percent metric is supported. Would you try changing metric_name into "`storage_percent`" to see if it works for you?
```
resource "azurerm_monitor_metric_alert" "azuredb_Memory_Rule" {
  name                = "Azure SQL  Memory Alert"
  resource_group_name =  "my-rg"
  scopes              = [mydb.id]
  description         = "Action will be triggered when Memory is too close to limit."
  frequency           = "PT1M"


  criteria {
    metric_namespace =  "Microsoft.Sql/servers/databases"
    metric_name      = "storage_percent"
    aggregation      = "Maximum"
    operator         = "GreaterThan"
    threshold        = 50

  }

  action {
    action_group_id = slack_action_group.id
  }
}
```

**Comment by katbyte** [comment]
Hey @Danielperga97,

It looks like @yupwei68 has suggested a fix that may work for you, and it could also be the case that what works/is supported in azurerm is not in azure gov. It might help to open a support case with azure so they can help figure out why the api is returning `The metric names were not found memory_usage_percent`, we just send that value off to azure 🙂 

As there has been no reply for 6 weeks i'm going to close this. Please do reopen this if this turns out to be an issue with the provider, thanks!
