### ISSUE TITLE
Is `application_logs` + `file_system` currently possible as of 2.7.0?

### ISSUE THREAD

**Issue by t-l-k** [terraform-providers/terraform-provider-azurerm#6645]
Here is my version:

```
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.7.0
```

my `required_providers`:

```
terraform {
   ...
  required_providers {
    azurerm = "~> 2.7.0"
    azuread = "~> 0.8.0"
  } 
   ...
}
```

And this is what I get when I have a resource of type: `azurerm_app_service`, with the following block:

```
logs {
    application_logs {
      file_system {
        retention_in_mb   = 30     # in Megabytes
        retention_in_days = 30     # in days
      }
    }
```

I get this:

```
terraform validate

Error: Unsupported block type

  on realtime-api.tf line 56, in resource "azurerm_app_service" "myapplication-api":
  56:       file_system {

Blocks of type "file_system" are not expected here.
```

Is this feature https://github.com/terraform-providers/terraform-provider-azurerm/issues/4021 actually available or am I missing something? I'm a bit new to Terraform, but this isn't quite making sense to me. There is no reference to it either on the [resource documentation](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#logs).

**Comment by magodo** [comment]
@t-l-k thank you for opening this issue!
Looks like the suggested config in #4021 is implemented in a slightly different way in #4025. The `file_system` block should exist inside of `http_logs` block, as stated [here](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#http_logs). So you can simply change the `application_logs` into `http_logs`, then it should work. Please feel free to let me know if it still not work!

**Comment by t-l-k** [comment]
Thanks @magodo  - I had already tried the `http_logs` block, but it does not take the intended effect in my experience.

I believe `http_logs` controls the circled **Web server logging** option below - yet **Application logging** remains turned off?

![image](https://user-images.githubusercontent.com/15836198/80493864-dbc05400-895d-11ea-88b0-7e5e385e1d30.png)

**Comment by magodo** [comment]
@t-l-k I'm sorry that I misunderstood your intention. Currently, the toggle to enable `Application Logging` is not supported in the provider. If you hover on the question mark in the above interface, it says:

> ... This setting turns itself off in 12 hours.

This is not idempotent behavior hence we might not support it in terraform. I will submit an issue to Azure to see if they can/already release this constraint.

**Comment by t-l-k** [comment]
@magodo Ah yes! Of course, well that solves that particular riddle. Thanks for taking the time to explain, and raising a follow up ticket!

**Comment by landro** [comment]
I believe it is now actually possible to solve this issue. I'd suggest config that looks like the following:

``` HCL
resource "azurerm_app_service" "main" {
  logs {
    application_logs {
      // Existing
      azure_blob_storage {
        level = ""
        retention_in_days = 0
        sas_url = ""
      }
     // Added 
      file_system {
        retention_in_days = 0
        retention_in_mb = 0
      }
    }
  }
}
```

This is particularly useful when deploying multi-container apps (docker-compose) on app service.

**Comment by tombuildsstuff** [comment]
👋 

Closing this out since it appears this question has been answered - but should you have further questions I'd point you towards [the community forum](https://discuss.hashicorp.com)

Thanks!
