### ISSUE TITLE
update terraform-provider-azurerm/website/docs/r/postgresql_server.html.markdown to reflect PR #6459

### ISSUE THREAD

**Issue by larryclaman** [terraform-providers/terraform-provider-azurerm#6646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation for terraform-provider-azurerm/website/docs/r/postgresql_server.html.markdown is out of date after the 2.7.0 release (PR #6459 ).  It needs to be updated to reflect the new configuration parameters noted in the PR:

```
support for create_mode, creation_source_server_id, infrastructure_encryption_enabled,public_network_access_enabled, ssl_minimal_tls_version_enforced properties
support replicas
computed storage_mb when auto_grow_enabled is true
use booleans for toggle properties by renaming:
-- ssl_enforcement -> ssl_enforcement_enabled
-- geo_redundant_backup -> geo_redundant_backup_enabled
-- auto_grow -> auto_grow_enabled
move all properties within the storage_profile block to the top level
```

### New or Affected Resource(s)

* azurerm/website/docs/r/postgresql_server.html.markdown

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

PR #6459 

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I can understand it and we are working on the fix but there is no timeline for now.
