### ISSUE TITLE
API Management large deploy fails when adding apim-product-subscriptions

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#6648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
+ provider.azuread v0.6.0
+ provider.azurerm v2.6.0
+ provider.random v2.2.0

### Affected Resource(s)

* `azurerm_api_management`
* `azurerm_api_management_subscription`
* `azurerm_api_management_product`

### Terraform Configuration Files

```hcl
module "api_management" {
  
  source                = "github.com/markti/terraform-azure/api/management/hub/apim"

  resource_group_name   = var.deployment_settings.resource_group_name
  location              = var.deployment_settings.location

  app_name              = var.context.app_name
  env_name              = var.context.env_name
  
  name                  = "${var.context.app_name}-${var.context.env_name}-apim"
  publisher_name        = "Demo Publisher"
  publisher_email       = "demo@foo.com"
  sku_name              = "Basic_1"
  cors_allowed_origins  = [ "https://localhost:44329", "http://localhost:58560/"] 
  cors_allowed_headers  = [ "FOO_TENANT_ID" ]

}
```

### Panic Output

Error: Error creating/updating Subscription "d89bd61b-371f-4792-bc3b-2ca444cb6fc2" (API Management Service "foo-test-apim" / Resource Group "foo-test-global"): apimanagement.SubscriptionClient#CreateOrUpdate: Failure responding to request: StatusCode=412 -- Original Error: autorest/azure: Service returned an error. Status=412 Code="PreconditionFailed" Message="Exception of type 'Microsoft.WindowsAzure.ApiManagement.Management.Core.Exceptions.PreconditionFailedException' was thrown."

  on .terraform\modules\api_shared_apim.subscription_public_web\api\management\hub\subscription\main.tf line 2, in resource "azurerm_api_management_subscription" "subscription":
   2: resource "azurerm_api_management_subscription" "subscription" {

Error: Error creating/updating Subscription "0e60f681-b904-4bb9-b273-cb36ac4ee6af" (API Management Service "foo-test-apim" / Resource Group "foo-test-global"): apimanagement.SubscriptionClient#CreateOrUpdate: Failure responding to request: StatusCode=412 -- Original Error: autorest/azure: Service returned an error. Status=412 Code="PreconditionFailed" Message="Exception of type 'Microsoft.WindowsAzure.ApiManagement.Management.Core.Exceptions.PreconditionFailedException' was thrown."

  on .terraform\modules\api_shared_apim.subscription_user_web\api\management\hub\subscription\main.tf line 2, in resource "azurerm_api_management_subscription" "subscription":
   2: resource "azurerm_api_management_subscription" "subscription" {

### Expected Behavior

It should provision an APIM, Product, and subscription on one go...

### Actual Behavior

you have to run terraform apply
get the error
run terraform apply again...error goes away

### Steps to Reproduce

1. `terraform apply`
2. get the error
3. `terraform apply`
4. error goes away

### Important Factoids

Azure Public

**Comment by yupwei68** [comment]
hi @markti , Thanks for opening this issue. I could not find your related source code. The code in the [module](https://github.com/markti/terraform-azure/blob/master/api/management/hub/apim/main.tf) might have been changed. Could you provide the source code for your issue?

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to provide the information requested above then we should be able to reopen this and take another look.

Thanks!
