### ISSUE TITLE
resource "azurerm_key_vault" "key_vault" 403 - Forbidden

### ISSUE THREAD

**Issue by yaroslavNikolaev** [terraform-providers/terraform-provider-azurerm#6666]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### AzureRM Provider =2.7.0`

```
resource "azurerm_key_vault" "key_vault" {
  name                        = "key-vault-${var.location}"
  location                    = var.location
  resource_group_name         = var.rg_name
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = "standard"
  tags                        = var.rg_tags

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "backup",
      "create",
      "decrypt",
      "delete",
      "encrypt",
      "get",
      "import",
      "list",
      "purge",
      "recover",
      "restore",
      "sign",
      "unwrapKey",
      "update",
      "verify",
      "wrapKey",
    ]

    secret_permissions = [
      "backup",
      "delete",
      "get",
      "list",
      "purge",
      "recover",
      "restore",
      "set",
    ]

    storage_permissions = [
      "backup",
      "delete",
      "deletesas",
      "get",
      "getsas",
      "list",
      "listsas",
      "purge",
      "recover",
      "regeneratekey",
      "restore",
      "set",
      "setsas",
      "update",
    ]
  }

  network_acls {
    bypass = "AzureServices"
    default_action = "Allow"
  }
}

data "azurerm_client_config" "current" {
}

output "id" {
  value = azurerm_key_vault.key_vault.id
}
output "tenant_id" {
  value = azurerm_key_vault.key_vault.tenant_id
}

variable "rg_name" {}
variable "rg_tags" {}
variable "location" {}
```

### Expected Behavior

Key vault should be created without errors. 

### Actual Behavior

```
17:45:44  Error: Error waiting for Key Vault "key-vault-centralus" (Resource Group "XXXX") to become available: Error connecting to "https://key-vault-centralus.vault.azure.net/": Get "https://key-vault-centralus.vault.azure.net/": Forbidden
17:45:44  
17:45:44    on ../../../modules/vault/vault.tf line 1, in resource "azurerm_key_vault" "key_vault":
17:45:44     1: resource "azurerm_key_vault" "key_vault" 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by pearcec** [comment]
Can you provide full TRACE log.  This code worked for me.

**Comment by yaroslavNikolaev** [comment]
Hi @pearcec 
We've found issue, we lauch it in CICD behind Proxy server which restict .azure.net due it's not whitelisted. 
My assumption, The message is misleading, Forbidden means 403 but very likely we had simple timeout. 
I'm trying to test results, of curl and wget , i know it's not the same but they have timeout.
As result investigation was started in incorrect direction. 
Probably it makes sence to modify output.
If you think it makes sense i can either modify this issue either create new one, otherwise it can be closed. 
Anyway thanks , sorry to disturb.

**Comment by pearcec** [comment]
@yaroslavNikolaev no prob.  Please close the issue.
