### ISSUE TITLE
azurerm_policy_assignment policy_definition_id fails validation in 2.6, for built in policy_set expects scope to be prepended #6

### ISSUE THREAD

**Issue by jarmbruster74** [terraform-providers/terraform-provider-azurerm#6671]
### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
AzureRM 2.7.0

### Affected Resource(s)
* azurerm_policy_assignment
### Terraform Configuration Files

```hcl
resource "azurerm_policy_assignment" "CIS_1_1" {
  name                 = "CIS_1_1"
  policy_definition_id = "/providers/Microsoft.Authorization/policySetDefinitions/1a5bb27d-173f-493e-9568-eb56638dde4d"
  scope                = local.subscription_id

  parameters = <<PARAMETERS
{
  "listOfRegionsWhereNetworkWatcherShouldBeEnabled": {
    "value": [ 
        "centralus",
        "eastus",
        "eastus2",
    ]
  }
}
PARAMETERS
}
```

### Expected Behavior

Policy Set Assignment should be created (this worked fine in 2.5)
This issue was recently fixed for Policy assignments, but the Policy Set Assignment validation is still broken

### Actual Behavior

Error: cannot parse "policy_definition_id" as a Policy Definition ID: unable to parse Policy Definition ID "/providers/Microsoft.Authorization/policySetDefinitions/1a5bb27d-173f-493e-9568-eb56638dde4d"
### Steps to Reproduce

1. `terraform apply`

### References

* #6523

**Comment by jarmbruster74** [comment]
@ArcturusZhang - would it be possible to add the same logic for the policy set defintion?

**Comment by ArcturusZhang** [comment]
Hi @jarmbruster74 no problem. I am working on this.
