### ISSUE TITLE
Impossible to create service SAS without protocol (pr=)

### ISSUE THREAD

**Issue by devbeard** [terraform-providers/terraform-provider-azurerm#6672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.12.24`

### Affected Resource(s)

* `azurerm_v2.7.0`

### Terraform Configuration Files

```hcl
data "azurerm_storage_account_blob_container_sas" "httplogs" {
  container_name    = azurerm_storage_container.httplogs.name
  connection_string = data.azurerm_storage_account.logs.primary_connection_string
  https_only        = var.httplogs_https_only # THIS
  start             = "2020-01-01"
  expiry            = "2022-01-01"

  permissions {
    read   = true
    add    = false
    create = false
    write  = true
    delete = true
    list   = true
  }
}
```

### Expected Behavior

That a SAS is generated that allows access to a storage container and that the output is equal to what you get when calling the .NET SDK, using the UI in the portal or calling the REST API.

Example from .NET SDK: `https://my-storage-account.blob.core.windows.net/httplogs?sv=2019-02-02&sr=c&sig=********&se=2022-01-01T12%3A00%3A00Z&sp=rwdl`

Example from UI: `https://my-storage-account.blob.core.windows.net/httplogs?sp=rwdl&st=2020-01-01T12:00:00Z&se=2022-01-01T12:00:00Z&sv=2019-10-10&sr=c&sig=******************`

### Actual Behavior

Example output from terraform: `https://my-storage-account.blob.core.windows.net/httplogs?sv=2018-11-09&sr=c&st=2020-01-01T12%3A00%3A00Z&se=2022-01-01T12%3A00%3A00Z&sp=rwdl&spr=https&sig=*************`

Notice that:

- `pr=https` is not set in the other SAS generation clients, and the only allowed values for `https_only` is true and false. Null results in true.
- `sv=2018-11-09` is lower than the other API versions 

Consequence: One of these parameters causes "http logs to blob account" from an app service to not work, and I strongly believe this is the `pr=https` parameter, and not the version. The change logs don't appear to contain any changes related to this. The version "2019-10-10" that the UI produces is not even documented (**shame on Microsoft!**) here: https://docs.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions

**Comment by SadokLadhari** [comment]
@devbeard I have created this issue #6519 to support all signed versions.

**Comment by devbeard** [comment]
Thanks for the link @SadokLadhari. I have verified that it is the «pr» parameter that causes the issue I am encountering. I have a working workaround by using an external block and calling into az-cli to generate a SAS token.

**Comment by SadokLadhari** [comment]
@devbeard After a quick verification, I can also confirm that **spr**(not pr) causes the issue.
The workaround that I did is using azurerm_template_deployment with this template :

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "variables": {
    "serviceSasFunctionValues": {
      "canonicalizedResource": "/blob/my_storageaccount/my_container",
      "signedResource": "c",
      "signedPermission": "rwdl",
      "signedStart" :"2020-01-01T00:00:00Z",
      "signedExpiry": "2050-01-01T00:00:00Z"
    }
  },
  "resources": [],
  "outputs": {
    "serviceSas": {
      "type": "string",
      "value": "[listServiceSas(concat('Microsoft.Storage/storageAccounts/','my_storageaccount'), '2019-06-01', variables('serviceSasFunctionValues')).serviceSasToken]"
    }
  }
}`

**Comment by magodo** [comment]
@SadokLadhari I wonder how do you confirm that it is the **spr** causes the issue, rather than the old version.

**Comment by SadokLadhari** [comment]
@magodo a Microsoft Support Engineer confirmed me that : 

> The way terraform generates SAS token is incompatible with app service currently because of the attribute spr=https or spr=http,https in the SAS token.

Also when I have removed the signedProtocol attribute from the serviceSasFunctionValues(in template) the SAS token generated worked for me (SAS token without spr attribute)

The ARM template (listServiceSas function) uses the version : 2015-04-05.

**Comment by magodo** [comment]
@SadokLadhari Thank you for the context!

I wonder if it only applies to App Service (as the reference are all about this resource).

**Comment by magodo** [comment]
@SadokLadhari I have tested on my own environment, which turns out both `spr` and `sv` cause this issue. The only working SAS is using `sv=2019-10-10` and without `spr`.

## Test Setup

- Provision a storage account with container blob
- Provision a web app service (windows) and upload the .NET webapp, with App Service logging provider enabled
- Configure the log config of app service via this [endpoint](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L1361), with request body like below:

```json
{
    "properties": {
        "applicationLogs": {
            "fileSystem": {
                "level": "Information"
            },
            "azureTableStorage": {
                "level": "Off",
                "sasUrl": null
            },
            "azureBlobStorage": {
                "level": "Information",
                "sasUrl": {{SASURL}},
                "retentionInDays": 10
            }
        },
        "httpLogs": {
            "fileSystem": {
                "retentionInMb": 35,
                "retentionInDays": 1,
                "enabled": false
            },
            "azureBlobStorage": {
                "sasUrl": null,
                "retentionInDays": 1,
                "enabled": false
            }
        },
        "failedRequestsTracing": {
            "enabled": false
        },
        "detailedErrorMessages": {
            "enabled": false
        }
    }
}
```
- Send a `GET` request to the web app page and refresh the blob in Portal to check the size change

**Comment by magodo** [comment]
@SadokLadhari Thank you for providing the context!

I tried the SAS token like this (provided by current data source): `?sv=2018-11-09&sr=c&st=2020-01-01&se=2022-01-01&sp=rwdl&spr=https&sig=***`, and it works for me.

So may I ask how do you do quick verification on your side?
(my test step is attached below)

## Test Setup

- Provision a storage account with container blob
- Provision a web app service (windows) and upload the .NET webapp, with App Service logging provider enabled
- Configure the log config of app service via this [endpoint](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L1361), with request body like below:

```json
{
    "properties": {
        "applicationLogs": {
            "fileSystem": {
                "level": "Information"
            },
            "azureTableStorage": {
                "level": "Off",
                "sasUrl": null
            },
            "azureBlobStorage": {
                "level": "Information",
                "sasUrl": {{SASURL}},
                "retentionInDays": 10
            }
        },
        "httpLogs": {
            "fileSystem": {
                "retentionInMb": 35,
                "retentionInDays": 1,
                "enabled": false
            },
            "azureBlobStorage": {
                "sasUrl": null,
                "retentionInDays": 1,
                "enabled": false
            }
        },
        "failedRequestsTracing": {
            "enabled": false
        },
        "detailedErrorMessages": {
            "enabled": false
        }
    }
}
```
Where SASURL is generated by the ComputeContainerSASToken() of go-azure-helpers library.
- Send a `GET` request to the web app page and refresh the blob in Portal to check the size change.

**Comment by magodo** [comment]
@devbeard you mentioned that:

> output from terraform: https://my-storage-account.blob.core.windows.net/httplogs?sv=2018-11-09&sr=c&st=2020-01-01T12%3A00%3A00Z&se=2022-01-01T12%3A00%3A00Z&sp=rwdl&spr=https&sig=*************

Actually, the data source only output the query string, instead of the full SAS URL. So may I double check that you have construct the SAS URL in the tf config for app service?

**Comment by devbeard** [comment]
Yes, I constructed the total URL that I give to the app service log block. Sorry, I should have provided a terraform example block showing the steps.

**Comment by magodo** [comment]
@devbeard Hmmm... That's weird. I assume you have already tried to update the SAS URL and verified that without `spr=https` will work, or no?
Also, it would be most helpful if you can provide the config for app service!

**Comment by SadokLadhari** [comment]
@magodo the **Secure transfer required** is enabled in your Storage Account ?

**Comment by devbeard** [comment]
@magodo The protocol is part of the signed payload. Changing the parameters is not possible, but I did create a SAS token outside of the azurerm resource and have it working without. Secure transfer required is on yes.

**Comment by magodo** [comment]
@devbeard One way to generate the SAS token is that you can create a dummy Go module, importing the `github.com/hashicorp/go-azure-helpers/storage` package and print out the output of `storage.ComputeContainerSASToken()`. You can simply pass in the `signedProtocol` parameter with `""`, in which case it will not show up in the output URL.

**dummy main.go**

```go
package main

import (
	"log"

	"github.com/hashicorp/go-azure-helpers/storage"
)

func main() {
	s, err := storage.ComputeContainerSASToken("rwdl", "2020-01-01", "2222-01-01", "accountName", "******", "containerName", "", "", "https", "", "", "", "", "", "")
	if err != nil {
		log.Fatal(err)
	}
	println(s)
}
```

**Comment by katbyte** [comment]
@SadokLadhari - I'm going to close this as its been nearly a year without a response, please do let us know if this is still an issue for you!
