### ISSUE TITLE
Can no longer create an azurerm_role_assignment

### ISSUE THREAD

**Issue by tezzigator** [terraform-providers/terraform-provider-azurerm#6673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
TF 0.12.24
Azure 2.7.0

### Affected Resource(s)
azurerm_role_assignment

### Terraform Configuration Files
```
resource "azurerm_role_assignment" "mic-signeridentity" {
  scope                = var.akssigner.id
  role_definition_name = "Managed Identity Operator"
  principal_id         = azurerm_kubernetes_cluster.aks.kubelet_identity.0.client_id
}
```

### Debug Output
 TF's plan says this (UUIDs randomized in here):
```
  # module.pricluster.azurerm_role_assignment.mic-signeridentity will be created
  + resource "azurerm_role_assignment" "mic-signeridentity" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = "7f15e1ee-8993-11ea-bc55-0242ac130003"
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Managed Identity Operator"
      + scope                            = "/subscriptions/8cc2e2a6-8993-11ea-bc55-0242ac130003/resourcegroups/RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ID"
      + skip_service_principal_aad_check = (known after apply)
    }
```

### Expected Behavior
Should have created the role assignment

### Actual Behavior
And then the result of the apply is:
```
2020-04-28T14:59:46.300-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.7.0_x5: 
2020-04-28T14:59:46.300-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.7.0_x5: {"error":{"code":"PrincipalNotFound","message":"Principal 7f15e1ee899311eabc550242ac130003 does not exist in the directory 8cc2e2a6-8993-11ea-bc55-0242ac130003."}}

Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal 7f15e1ee899311eabc550242ac130003 does not exist in the directory 8cc2e2a6-8993-11ea-bc55-0242ac130003."
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The dashes from the UUID from the error there seem to be missing, I suspect that may be the issue, as I can easily create the role assignment from AZ CLI using the same identical values.

**Comment by njuCZ** [comment]
@tezzigator I am not sure whether your `azurerm_kubernetes_cluster.aks.kubelet_identity.0.client_id` is the right value. Could you please follow this example: https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html#example-usage-using-a-built-in-role-

I have tried in my local using the latest provider , it works well

**Comment by tezzigator** [comment]
As best I can tell it is correct.  At least, what is shown from my `terraform plan` seems to indicate the correct principal id, where if I use the AZ CLI to create the same role assignment, using the same 3 inputs that is shown as the result of my `terraform plan`, then the AZ CLI command is successful.

Can you paste the result of your `terraform plan`?

**Comment by njuCZ** [comment]
@tezzigator could you please first confirm it's ok to create `azurerm_role_assignment` using the doc example? 
AS for your problem, May I ask whether the principal_id is a newly provisioned Service Principal, if so, according to https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html#skip_service_principal_aad_check, you should set `skip_service_principal_aad_check` to true

**Comment by tezzigator** [comment]
I think I found the error in that I have been trying to use the `client_id` as terraform's principal_id in the azurerm_role_assignment.  I did so as when testing with the az cli I found that using the client_id's number worked when entering in the AZ CLI, and so when deving for TF I then translated things and found that the kubelet's client_id resulted in the same id I had used when going with the CLI.

However, it appears that using the CLI that you can use either an object id or principal id and the cli will figure it out and execute the command into AD.  I did see that if you tried a random UUID it would fail, so Im confident in saying that the AZ CLI will allow either .
