### ISSUE TITLE
Add Identity attribute to Virtual Machine Datasource

### ISSUE THREAD

**Issue by EppO** [terraform-providers/terraform-provider-azurerm#6675]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When you want to get the Machine System Identity from a VM created oustide of Terraform or in a different state file, you have no way to get the identities using the Virtual Machine Datasource that exposes only the id.

### New or Affected Resource(s)

* data.azurerm_virtual_machine

### Potential Terraform Configuration

```hcl
data "azurerm_virtual_machine" "example" {
  name                = "production"
  resource_group_name = "networking"
}

output "virtual_machine_id" {
  value = data.azurerm_virtual_machine.example.id
}

output "virtual_machine_identities" {
  value = data.azurerm_virtual_machine.example.identity.*.principal_id}

```

### References

* #0000

**Comment by ArcturusZhang** [comment]
Hi @EppO thanks for opening this issue!
I will take some time to implement this.
