### ISSUE TITLE
Route table type is set incorrectly to "None" instead of "VirtualAppliance"

### ISSUE THREAD

**Issue by klafkas101** [terraform-providers/terraform-provider-azurerm#6686]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
Terraform Provider Azurerm: 2.6.0_x5

### Affected Resource(s)

* `azurerm_route_table`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_route_table" "spoketestroute" {
  name                = "${var.PREFIX}-RT-SPOKE-TEST"
  location            = var.LOCATION
  resource_group_name = azurerm_resource_group.resourcegroup.name

  route {
    name                   = "Default"
    address_prefix         = "0.0.0.0/0"
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = var.lb_internal_ipaddress
  }
}
```

### Expected Behavior

A route table with route of type "VirtualAppliance" is created in Azure.

### Actual Behavior

A route table with route of type "None" is created in Azure.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lrxtom2** [comment]
@klafkas101 , Thanks for this issue!
I can't reproduce this now. And could you please provide more information about that or specific terraform configuration file? Thanks for that.

**Comment by klafkas101** [comment]
@lrxtom2 I can't reproduce this anymore. It seems to work now.
