### ISSUE TITLE
azurerm_api_management_named_value consistently creating "value" resource attribute ignoring state file

### ISSUE THREAD

**Issue by Lidestyle** [terraform-providers/terraform-provider-azurerm#6688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.7.0

### Affected Resource(s)

* azurerm_api_management_named_value

### Terraform Configuration Files

```HCL

// The local value example:
locals {
    referenced_named_values = merge(
    ... ,
    {
      ## Restriction Named values => Function Application(s) address range
      for i in distinct(flatten(slice(local.helper, 0, 1))) :
      format("function-app-range-%s", index(distinct(flatten(slice(local.helper, 0, 1))), i)) => [i, ["function-app", "whitelist"]]
    },
    ...
    )
}

resource "azurerm_api_management_named_value" "referenced" {
  for_each            = local.referenced_named_values
  resource_group_name = var.resource_group.gateway.name
  api_management_name = azurerm_api_management.apim.name
  name                = each.key
  display_name        = each.key
  value               = element(each.value, 0)
  tags                = element(each.value, 1)
  secret              = local.default_named_value_access_mode // true
}
```

### Expected Behavior

Terraform should update the values for the Azure API Management Named Values in case there are updates.

### Actual Behavior

Terraform always create value attribute ignoring state file.

### Steps to Reproduce

1. Set 'secret' attribute to true
2. terraform apply // Create the resources
2. terraform apply

### Important Factoids

From the resource documentation:

> NOTE: setting the field secret to true doesn't make this field sensitive in Terraform, instead it marks the value as secret and encrypts the value in Azure.

### References

* https://www.terraform.io/docs/providers/azurerm/r/api_management_named_value.html

* #0000

**Comment by yupwei68** [comment]
hi @Lidestyle , thanks for opening this issue. When the `secret` is set true, the service api will not return the `value` back. Terraform has updated the `value` field, it just set empty value in `value` in local state file. We might fix it later.
