### ISSUE TITLE
azure_role_assignment:  unable to assign role to an SPN at subscription level

### ISSUE THREAD

**Issue by JasonNguyenTX** [terraform-providers/terraform-provider-azurerm#669]
I am not able to assign a role for an SPN at subscription level.  However, I can add the role manually.  Below is the error when using terraform.

azurerm_role_assignment.reader: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalTypeNotSupported" Message="Principals of type Application cannot validly be used in role assignments."

**Comment by JunyiYi** [comment]
Hi @JasonNguyenTX , I'm not able to repro your issue (see the following log). Could you please provide the HCL?

```sh
azurerm_role_assignment.test: Creating...
  name:                 "" => "<computed>"
  principal_id:         "" => "<my principal object id>"
  role_definition_name: "" => "Reader"
  scope:                "" => "/subscriptions/<my subscription id>"
azurerm_role_assignment.test: Creation complete after 3s (ID: /subscriptions/<my subscription id>/<creation id>)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by JunyiYi** [comment]
The similar code below works for me (you may query for the detailed information of you principal using the Azure CLI command: `az ad sp show --id <My Service Principal Object ID>`):

```HCL
data "azurerm_subscription" "primary" {}

resource "azurerm_role_assignment" "test" {
  scope                = "${data.azurerm_subscription.primary.id}"
  role_definition_name = "Reader"
  principal_id         = "<My Service Principal Object ID>"
}
```

So could you please try the following options on your side to see what is going wrong:

1. Create a new service principal (without role assignments) in Azure portal, get its object ID, and use the script above to assign a role to your subscription. [*This works on my subscription*]
2. Try to assign your `<var.client_id>` to your **subscription**.
3. Try to assign the new service principal created above to your **container registry**.

**Comment by tombuildsstuff** [comment]
hi @JasonNguyenTX @lionelperrin 

Since we've not heard back from you here I'm going to close this issue for the moment - however feel free to re-open this if you're still encountering this issue and we'll take another look :)

Thanks!

**Comment by maxirus** [comment]
I was facing this same issue and also had a MS support rep scratching their head because it would work in Portal but not Terraform or CLI. Turns out the Object ID reported in the Azure Portal is **different** than the one reported in the CLI command.

Using the Object ID reported by `az ad sp show —id <application_id>` instead worked for me.

**Comment by spmsaj** [comment]
Same issue here. Added the custom role using terraform, worked fine. Role assignment using the same custom role in TF says it cant find it. Allocating via gui is fine
* azurerm_role_assignment.test: Error loading Role Definition List: could not find role 'my-custom-role'

**Comment by btai24** [comment]
I am getting the same error with this HCL. 
```
resource "azurerm_role_assignment" "service_principal_aks_role" {
  scope                         = "${module.aks_cluster.agents_resource_group_id}" 
  role_definition_name = "${module.aks_role.name}"
  principal_id                = "${module.service_principal.id}"

  depends_on = [
    "module.service_principal",
    "module.aks_role",
  ]
}```

```
service-principal module

resource "azurerm_azuread_service_principal" "service_principal" {
  application_id = "${azurerm_azuread_application.service_principal_app.application_id}"
}

output "id" {
  value = "${azurerm_azuread_service_principal.service_principal.id}"
}
```

```
aks-role module

resource "azurerm_role_definition" "aks_role" {
  name        = "aks-role_${var.environment}"
  scope       = "${data.azurerm_subscription.primary.id}"
  description = "This role provides the least privilege permissions needed by AKS"

  permissions {
    actions = [
      "Microsoft.Compute/virtualMachines/read",
      "Microsoft.Compute/virtualMachines/write",
      "Microsoft.Compute/disks/write",
      "Microsoft.Compute/disks/read",
      "Microsoft.Network/loadBalancers/write",
      "Microsoft.Network/loadBalancers/read",
      "Microsoft.Network/routeTables/read",
      "Microsoft.Network/routeTables/routes/read",
      "Microsoft.Network/routeTables/routes/write",
      "Microsoft.Network/routeTables/routes/delete",
      "Microsoft.ContainerRegistry/registries/read",
      "Microsoft.Network/publicIPAddresses/read",
      "Microsoft.Network/publicIPAddresses/write",
    ]
  }

  assignable_scopes = [
    "${data.azurerm_subscription.primary.id}",
  ]
}

output "name" {
  value = "${azurerm_role_definition.aks_role.name}"
}

```
azurerm_role_assignment.service_principal_aks_role: Creating...
  name:                 "" => "<computed>"
  principal_id:         "" => "<redacted>"
  role_definition_name: "" => "aks-role_qa"
  scope:                "" => "/subscriptions/<redacted>/resourceGroups/<rg name>"

Error: Error applying plan:

1 error(s) occurred:

* azurerm_role_assignment.service_principal_aks_role: 1 error(s) occurred:

* azurerm_role_assignment.service_principal_aks_role: Error loading Role Definition List: could not find role 'aks-role_qa'
```

**Comment by lnovara** [comment]
@btai24 I got the same error and I was able to make it work using `role_definition_id` in place of `role_definition_name`. Hope it helps.
