### ISSUE TITLE
azurerm_log_analytics_workspace data source reports InvalidApiVersionParameter

### ISSUE THREAD

**Issue by laughtonsm** [terraform-providers/terraform-provider-azurerm#6691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.7

### Affected Resource(s)

* `azurerm_log_analytics_workspace` - Data Source

### Terraform Configuration Files

```hcl
data "azurerm_log_analytics_workspace" "security_center" {
  name                = var.log_analytics_workspace_name
  resource_group_name = var.log_analytics_workspace_resource_group_name
}
```

### Expected Behavior

Should return the output of the data source

### Actual Behavior

Generated the following error

```
Error: Error making Read request on AzureRM Log Analytics workspaces 'DefaultWorkspace-xxxxxxxxxxxxxxxxxxxx-SUK': operationalinsights.WorkspacesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2015-11-01-preview' is invalid. The supported versions are '2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by magodo** [comment]
Thank you for letting us know this issue :+1:
Would you please check whether you are passing in a resource group **ID** instead of its **name**? In case you incorrectly specify an ID, Azure would give you the "meaningless" error as shown above.
