### ISSUE TITLE
azurerm_virtual_hub_connection throws InternalServerError

### ISSUE THREAD

**Issue by doherty100** [terraform-providers/terraform-provider-azurerm#6694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.12.24
+ provider.azurerm v2.7.0`

### Affected Resource(s)

* `azurerm_virtual_hub_connection`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_wan" "vwan1" {
  name                           = var.vwan_name
  resource_group_name            = var.resource_group_name
  location                       = var.location
  disable_vpn_encryption         = false
  allow_branch_to_branch_traffic = true
  allow_vnet_to_vnet_traffic     = false
  tags                           = var.tags
}

resource "azurerm_virtual_hub" "vwanhub1" {
  name                = var.vwan_hub_name
  resource_group_name = var.resource_group_name
  location            = var.location
  virtual_wan_id      = azurerm_virtual_wan.vwan1.id
  address_prefix      = var.vwan_hub_address_prefix
  tags                = var.tags
}

# Note filed GitHub issue #6663 for misspelled argument names "hub_to_vitual_network_traffic_allowed" and "vitual_network_to_hub_gateways_traffic_allowed"
# Link: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6663 

resource "azurerm_virtual_hub_connection" "virtual_hub_connections" {
  for_each = var.remote_virtual_network_ids

  name                                           = each.key
  virtual_hub_id                                 = azurerm_virtual_hub.vwanhub1.id
  remote_virtual_network_id                      = each.value
  hub_to_vitual_network_traffic_allowed          = true
  vitual_network_to_hub_gateways_traffic_allowed = true
  internet_security_enabled                      = true
}

output "vwan1_id" {
  value = azurerm_virtual_wan.vwan1.id
}

output "vwanhub1_id" {
  value = azurerm_virtual_hub.vwanhub1.id
}

output "virtual_hub_connection_ids" {
  value = azurerm_virtual_hub_connection.virtual_hub_connections
}
```

### Debug Output

https://gist.github.com/doherty100/4e6b23cbdb85f34b305f6757fd9ce536 
### Panic Output

N/A

### Expected Behavior

Configuration should be applied successfully.

### Actual Behavior
```
azurerm_virtual_wan.vwan1: Creating...
azurerm_virtual_wan.vwan1: Creation complete after 14s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rd-vdc-eastus-dev-rg/providers/Microsoft.Network/virtualWans/rd-vdc-eastus-dev-vwan]
azurerm_virtual_hub.vwanhub1: Creating...
azurerm_virtual_hub.vwanhub1: Creation complete after 2m36s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rd-vdc-eastus-dev-rg/providers/Microsoft.Network/virtualHubs/rd-vdc-eastus-dev-vwan-hub-1]
azurerm_virtual_hub_connection.virtual_hub_connections["MyHubVNetId"]: Creating...
azurerm_virtual_hub_connection.virtual_hub_connections["MySpokeVnetId"]: Creating...
azurerm_virtual_hub_connection.virtual_hub_connections["MyHubVNetId"]: Still creating... [1m50s elapsed]
azurerm_virtual_hub_connection.virtual_hub_connections["MySpokeVnetId"]: Still creating... [3m40s elapsed]

Error: Error waiting for addition of Connection "MyHubVNetId" to Virtual Hub "rd-vdc-eastus-dev-vwan-hub-1" (Resource Group "rd-vdc-eastus-dev-rg"): Code="InternalServerError" Message="An error occurred." Details=[]

  on 01-network.tf line 23, in resource "azurerm_virtual_hub_connection" "virtual_hub_connections":
  23: resource "azurerm_virtual_hub_connection" "virtual_hub_connections" {

Error: Error waiting for addition of Connection "MySpokeVnetId" to Virtual Hub "rd-vdc-eastus-dev-vwan-hub-1" (Resource Group "rd-vdc-eastus-dev-rg"): Code="InternalServerError" Message="An error occurred." Details=[]

  on 01-network.tf line 23, in resource "azurerm_virtual_hub_connection" "virtual_hub_connections":
  23: resource "azurerm_virtual_hub_connection" "virtual_hub_connections" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Note when I only try to provision a single azurerm_virtual_hub_connection I do not get an InternalServerError. It only fails when I try provision multiple using for_each.

### References

* [azurerm_virtual_hub_connection](https://www.terraform.io/docs/providers/azurerm/r/virtual_hub_connection.html)
* [azurerm_virtual_hub_connection misspelled arguments #6663](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6663)

**Comment by magodo** [comment]
@doherty100 Thank you for letting us know this issue :+1:
The log you attached seems not complete, would you please send a complete one (and setting `TF_LOG` to `DEBUG` is enough, `TRACE` will bring too much noise)?
FWIW, there are some limitations for connecting multiple virtual networks to a single virtual hub. E.g. you should ensure the address space of the to be added virtual network doesn't overlap with the address space of either virtual hub itself or other virtual network(s) which are already peered with this virtual hub.
So would you please also guarantee that you meet this constraint?

**Comment by doherty100** [comment]
@magodo I deprovisioned all the virtual wan and virtual hub resources manually, then I commented out these three properties:

  # hub_to_vitual_network_traffic_allowed          = true
  # vitual_network_to_hub_gateways_traffic_allowed = true
  # internet_security_enabled                      = true

I reapplied the configuration and this time it worked with no errors.

**Comment by magodo** [comment]
@doherty100 Thank you for the update!

Then I assume you are hitting this case:

> Another constraint is that you should ensure you have setup up the azurerm_point_to_site_vpn_gateway as you have enabled vitual_network_to_hub_gateways_traffic_allowed.

If you want to enable `vitual_network_to_hub_gateways_traffic_allowed`, then please ensure you have a `azurerm_point_to_site_vpn_gateway` provisioned accordingly.
