### ISSUE TITLE
Support for creating Application Service Environments in a specific resource group

### ISSUE THREAD

**Issue by gpduck** [terraform-providers/terraform-provider-azurerm#6699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current App Service Environment provider creates the ASE in the same resource group as the subnet. We would like to be able to specify a different resource group for the ASE.

### New or Affected Resource(s)

* azurerm_app_service_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "network" {
  name     = "networkRG"
  location = "westeurope"
}

resource "azurerm_resource_group" "ase" {
  name     = "aseRG"
  location = "westeurope"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet1"
  location            = "${azurerm_resource_group.network.location}"
  resource_group_name = "${azurerm_resource_group.network.name}"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "ase" {
  name                 = "asesubnet"
  resource_group_name  = azurerm_resource_group.network.name
  virtual_network_name = azurerm_virtual_network.network.name
  address_prefix       = "10.0.1.0/24"
}

resource "azurerm_subnet" "gateway" {
  name                 = "gatewaysubnet"
  resource_group_name  = azurerm_resource_group.network.name
  virtual_network_name = azurerm_virtual_network.network.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_app_service_environment" "example" {
  name                   = "example-ase"
  subnet_id              = azurerm_subnet.ase.id
  pricing_tier           = "I2"
  front_end_scale_factor = 10
  resource_group_name    = "${azurerm_resource_group.ase.name}"
}
```

**Comment by magodo** [comment]
Thank you for letting us know this issue :+1:
Currently, the resource group underused is implicitly taken from the Subnet. I'll try to add an optional field `resource_group_name` to allow the user to override that behavior, but still keep compatibility.
