### ISSUE TITLE
virtual machine contributor:  map to classic rather than ARM

### ISSUE THREAD

**Issue by JasonNguyenTX** [terraform-providers/terraform-provider-azurerm#670]
Virtual Machine Contributor role currently maps to classic virtual machine contributor.  Is there a plan to update it to ARM virtual machine contributor role?

**Comment by tombuildsstuff** [comment]
hey @JasonNguyenTX 

Thanks for opening this issue

I've replicated this and we'll fix this in the next release of the AzureRM Provider, the correct GUID for for the Virtual Machine Contributor role is `9980e02c-c2be-4d73-94e8-173b1dc7cf3c`.

Thanks!
