### ISSUE TITLE
azure_builtin_role_definition:  missing support for other roles

### ISSUE THREAD

**Issue by JasonNguyenTX** [terraform-providers/terraform-provider-azurerm#671]
Is there a plan to support other roles beside the 4 existing roles?  Roles such as Monitoring Reader, Key Vault, SQL, Security are missing.

**Comment by paultyng** [comment]
Looks like we can possibly query these:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-api-authentication

https://docs.microsoft.com/en-us/rest/api/authorization/roledefinitions/list

I think we could probably swap the data source to just use the `List` endpoint and filter?
