### ISSUE TITLE
azurerm_lb frontend_ip_configuration clarification for argument "zones"

### ISSUE THREAD

**Issue by ryancbutler** [terraform-providers/terraform-provider-azurerm#6719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The **zones** argument in the **frontend_ip_configuration** block is confusing, since seeing this makes one assume you can pass multiple zone numbers to create IPs in each zone (eg `zones = ["1","2","3"]`). While the provider only supports one zone number and needs to be included in a list (eg `zones = ["1"]`).    Can this be changed to simply **zone** and allow the argument to accept a single string instead of a list?

### New or Affected Resource(s)

* azurerm_azurerm_lb

### Potential Terraform Configuration

Currently:
```hcl
  frontend_ip_configuration {
    name                          = "myfename"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Dynamic"
    zones                         = ["1"]
  }
```
Proposed:
```hcl
  frontend_ip_configuration {
    name                          = "myfename"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Dynamic"
    zone                         = "1"
  }
```

### References

* #3140

**Comment by magodo** [comment]
@ryancbutler Thank you for letting us know this issue :+1:
As you know, `zones` are used to specify the zonal lb, which means the lb only balance loads within the zone specified in this list. Currently, service only supports regional zone-redundant or zonal. In the future, it might support selectable zone-redundant, which means user can specify multiple `zone`(s). So we leave it as a list so that when it happens we do not need to change the schema (which also aligns with the API).

**Comment by jontreynes** [comment]
@ryancbutler and @magodo I had the same question. I went through the portal and created one lb that is zone redundant, looked at the ARM template that was generated and saw that the ARM Template did not show the [zones](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2018-08-01/loadbalancers#frontendipconfiguration-object) object specified. 

```
{
            "type": "Microsoft.Network/loadBalancers",
            "apiVersion": "2020-05-01",
            "name": "[parameters('loadBalancers_testlb_name')]",
            "location": "eastus2",
            "sku": {
                "name": "Standard"
            },
            "properties": {
                "frontendIPConfigurations": [
                    {
                        "name": "LoadBalancerFrontEnd",
                        "properties": {
                            "privateIPAddress": "172.16.0.7",
                            "privateIPAllocationMethod": "Dynamic",
                            "subnet": {
                                "id": "[concat(parameters('virtualNetworks_test_zones_vnet_externalid'), '/subnets/default')]"
                            },
                            "privateIPAddressVersion": "IPv4"
                        }
                    }
                ],
                "backendAddressPools": [],
                "loadBalancingRules": [],
                "probes": [],
                "inboundNatRules": [],
                "outboundRules": [],
                "inboundNatPools": []
            }
        }
```


I then made a second lb through the portal and specified one zone (you can only specify one zone which this [document](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-standard-availability-zones#zone-redundant) suggests and @magodo concurs.

```
{
            "type": "Microsoft.Network/loadBalancers",
            "apiVersion": "2020-05-01",
            "name": "[parameters('loadBalancers_testlb2_name')]",
            "location": "eastus2",
            "sku": {
                "name": "Standard"
            },
            "properties": {
                "frontendIPConfigurations": [
                    {
                        "name": "LoadBalancerFrontEnd",
                        "properties": {
                            "privateIPAddress": "172.16.0.8",
                            "privateIPAllocationMethod": "Dynamic",
                            "subnet": {
                                "id": "[concat(parameters('virtualNetworks_test_zones_vnet_externalid'), '/subnets/default')]"
                            },
                            "privateIPAddressVersion": "IPv4"
                        },
                        "zones": [
                            "2"
                        ]
                    }
                ],
                "backendAddressPools": [],
                "loadBalancingRules": [],
                "probes": [],
                "inboundNatRules": [],
                "outboundRules": [],
                "inboundNatPools": []
            }
        }
```

Anyways, it's interesting how the zone-redundant arm template does not specify any zones or even have a boolean for zone redundant. It is just zone redundant and implied.

If you'd like to make an all zone redundant LB like me, just make zones = null

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment - As I mentioned above, the limitation that you can only pass in one zone number to the `zones` is comes from the upstream API. We can make it as a non-list, but we choose to keep it as a list for the potential extension in future.

Thanks!
