### ISSUE TITLE
 Error when trying to access keyvault secret in other subscription

### ISSUE THREAD

**Issue by nerddtvg** [terraform-providers/terraform-provider-azurerm#6722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azurerm v2.7.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm`
* `azurerm_key_vault`
* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # The "feature" block is required for AzureRM provider 2.x. 
  # If you are using version 1.x, the "features" block is not allowed.
  version = "~>2.0"
  features {}
}

provider "azurerm" {
  # The "feature" block is required for AzureRM provider 2.x. 
  # If you are using version 1.x, the "features" block is not allowed.
  version = "~>2.0"
  features {}

  alias = "azurerm_domain_join_kv"
  subscription_id = var.domain_join_kv_subscription_id
}

# Reference a key vault (maybe in another subscription)
data "azurerm_key_vault" "tenant_admin_kv" {
  provider              = azurerm.azurerm_tenant_admin_kv
  name                  = var.tenant_admin_kv_name
  resource_group_name   = var.tenant_admin_kv_resource_group
}

# Make the secret available
data "azurerm_key_vault_secret" "tenant_admin_secret" {
  name                  = var.tenant_admin_secret_name
  key_vault_id          = data.azurerm_key_vault.tenant_admin_kv.id
}
```

### Debug Output

```
2020-04-30T15:17:09.420-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.7.0_x5.exe: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/primary-xxxx-yyyy-zzzz-dddddddd/resourceGroups/RGName/providers/Microsoft.KeyVault/vaults/KeyVaultName?api-version=2018-02-14:
2020-04-30T15:17:09.420-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.7.0_x5.exe: HTTP/2.0 404 Not Found
2020-04-30T15:17:09.420-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.7.0_x5.exe: Content-Length: 102
2020-04-30T15:17:09.421-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.7.0_x5.exe:

2020-04-30T15:17:09.421-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.7.0_x5.exe: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'RGName' could not be found."}}

2020/04/30 15:17:09 [ERROR] <root>: eval: *terraform.EvalReadData, err: Error looking up Secret "d-it-wvd-svc" vault url from id "/subscriptions/keyvault-aaaa-bbbb-cccc-dddddddd/resourceGroups/RGName/providers/Microsoft.KeyVault/vaults/KeyVaultName": Error unable to find KeyVault "KeyVaultName" (Resource Group "RGName"): keyvault.VaultsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'RGName' could not be found."

2020/04/30 15:17:09 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error looking up Secret "d-it-wvd-svc" vault url from id "/subscriptions/keyvault-aaaa-bbbb-cccc-dddddddd/resourceGroups/RGName/providers/Microsoft.KeyVault/vaults/KeyVaultName": Error unable to find KeyVault "KeyVaultName" (Resource Group "RGName"): keyvault.VaultsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'RGName' could not be found."

Error: Error looking up Secret "d-it-wvd-svc" vault url from id "/subscriptions/keyvault-aaaa-bbbb-cccc-dddddddd/resourceGroups/RGName/providers/Microsoft.KeyVault/vaults/KeyVaultName": Error unable to find KeyVault "KeyVaultName" (Resource Group "RGName"): keyvault.VaultsClient#Ge2020-04-30T15:17:09.445-0500 [DEBUG] plugin: plugin exited
t: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'RGName' could not be found."

  on keyvault.tf line 9, in data "azurerm_key_vault_secret" "domain_join_secret":
   9: data "azurerm_key_vault_secret" "domain_join_secret" {
```

### Expected Behavior

The Alias provider would be used to read from the proper keyvault.

### Actual Behavior

This is a re-opening of case #4055.

We see that the error message includes the correct subscription ID (keyvault-aaaa-bbbb-cccc-dddddddd), but the actual request to the Azure API is using the subscription ID used from the default provider (primary-xxxx-yyyy-zzzz-dddddddd). The default subscription is proper for the deployment and the aliased provider is setup for keyvault access. The account being used (az account show - not shown) has owner privileges to both subscriptions and full secret access to the key vault.

### Steps to Reproduce

1. `terraform plan`

### References

* #4055

**Comment by PSanetra** [comment]
I see a similar issue after upgrading from version < 2.0.0 of this provider.
In my case I am trying to access `azurerm_dns_zone` data sources via non default providers with different `subscription_id` properties.

**Comment by nickmhankins** [comment]
@nerddtvg 

It looks like you are missing `provider = azurerm.azurerm_tenant_admin_kv` on your `azurerm_key_vault_secret` resource. 

Try this:
```hcl
data "azurerm_key_vault_secret" "tenant_admin_secret" {
  provider              = azurerm.azurerm_tenant_admin_kv
  name                  = var.tenant_admin_secret_name
  key_vault_id          = data.azurerm_key_vault.tenant_admin_kv.id
}
```

I tried it with the provider in the block and it worked, once I took it out I got that same 404 error.

**Comment by nerddtvg** [comment]
@nickmhankins 

Unfortunately the project I was using this on has moved to another team so I can't test it at the moment.

I'm intrigued by that since I would have assumed (bad, I know) that it would inherit the provider from the key_vault_id/data source.

I'm not sure if this is the intended design or not, so I'll leave this open and let the product team decide its fate.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here as @nickmhankins has mentioned when using multiple KeyVaults in multiple Subscriptions you'll need to ensure the aliases match the Subscriptions where these Key Vaults exist.

Since I believe this should be fixed by updating the Terraform Configuration ([as shown in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6722#issuecomment-638410045)), I'm going to close this issue for the moment - but should you have any further questions I'd [point you towards the Community Forum where someone should be able to assist further](https://discuss.hashicorp.com).

Thanks!
