### ISSUE TITLE
Windows OS disk encryption (disk encryption set) cannot be updated after VM is created

### ISSUE THREAD

**Issue by kumarkran** [terraform-providers/terraform-provider-azurerm#6737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.12.18
+ provider.azurerm v2.7.0
`

### Affected Resource(s)

* `azurerm_windows_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_windows_virtual_machine" "windows_vm" {
  count               = local.is_windows ? var.vm_count : 0
  name                = local.vm_names[count.index]
  location            = var.vm_location
  resource_group_name = var.vm_resource_group_name
  availability_set_id = azurerm_availability_set.availability_set.id
  size                = var.vm_size
  network_interface_ids = [
    azurerm_network_interface.primary_network_interface[count.index].id
  ]
source_image_id = var.os_image_id
dynamic "source_image_reference" {
    for_each = var.os_image_id == null ? [1] : []
    content {
      publisher = local.resolved_image.publisher
      sku       = local.resolved_image.sku
      offer     = local.resolved_image.offer
      version   = local.resolved_image.version
    }
  }
  os_disk {
    name                   = "${local.vm_names[count.index]}-osdisk"
    caching                = "ReadWrite"
    storage_account_type   = var.data_disk_sku
    disk_encryption_set_id = var.disk_encryption_set_id
  }

  admin_username = var.admin_username
  admin_password = var.admin_password
}

```
### Expected Behavior

Windows OS  disk encryption set  updated to existing VM's

### Actual Behavior

Unable to update OS disk encryption (Disk encryption set) for existing VM's    

### Steps to Reproduce

1. `Terraform apply` VM initially without disk encryption set 
2. Set Disk encryption set id
3.Run terraform apply after updating disk encryption set id

### Important Factoids
This issue is similar to #6183 
Only Linux VM' got the fix in #6230

**Comment by ArcturusZhang** [comment]
Hi @kumarkran thanks for this issue!
I can reproduce this and will work on a similar fix to the linux VMs on windows VMs.
