### ISSUE TITLE
Change to KeyVault secret does not update dependency

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#6743]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.14
azurerm 2.8.0

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_secret" "web_username" {
  name         = "Web-Username"
  value        = var.web_username
  key_vault_id = azurerm_key_vault.main.id
}

resource "azurerm_app_service" "app" {
  name                    = "xxx"
  location                = var.common.location
  resource_group_name     = var.common.resource_group_name_windows
  app_service_plan_id     = var.app_service_plan_id

  app_settings = { 
    login_credential_user  = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.web_username.id})"
   }
}
```

### Expected Behavior

Any update to the KeyVault secret value should also update the dependencies in the same apply run.

### Actual Behavior

When an existing KeyVault secret value gets updated, dependencies, in the example above an App Service setting, does not get updated in the same TF apply run. Only when we run tf plan and apply again, it will update it.

### Steps to Reproduce

1. `terraform apply`

### References

Not sure if this could be related to this one?! https://github.com/hashicorp/terraform/issues/24663#issuecomment-622090067

**Comment by StefanSchoof** [comment]
This sounds like #3129

**Comment by sebader** [comment]
Ah yes you're right @StefanSchoof 

Closing as duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/3129
