### ISSUE TITLE
Can not parse "resource_id" as a resource id: Key/Value cannot be empty strings

### ISSUE THREAD

**Issue by dewolfs** [terraform-providers/terraform-provider-azurerm#6746]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.21
+ provider.azurerm v2.8.0
```
### Affected Resource(s)

- azurerm_log_analytics_linked_service

### Terraform Configuration Files

```hcl
# Retrieve details from automation account
data "azurerm_automation_account" "aut-p-we-001" {
  resource_group_name = var.aut_rg_name
  name                = var.aut_name
}

# Link Log Analytics workspace to automation account
resource "azurerm_log_analytics_linked_service" "log_link_aut" {
  resource_group_name = azurerm_resource_group.rg-log-p-we-001.name
  workspace_name      = azurerm_log_analytics_workspace.log-p-we-001.name
  linked_service_name = "automation"
  resource_id = data.azurerm_automation_account.aut-p-we-001.id
}
```

### Error message
When using azurerm_log_analytics_linked_service terraform plan throws the following error message
```
Error: Can not parse "resource_id" as a resource id: Key/Value cannot be empty strings. Key: '', Value: 'we-agentservice-prod-1.azure-automation.net'

  on log.tf line 39, in resource "azurerm_log_analytics_linked_service" "log_link_aut":
  39: resource "azurerm_log_analytics_linked_service" "log_link_aut" {
```

### Expected Behavior

ID of Automation account should be retrievable to make the link to Log Analytics workspace

### Actual Behavior

Deployment fails with above error message.
When I hardcode the automation ID value it does work. So there is clearly something wrong with the way how the ID is retrieved.  

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by magodo** [comment]
@dewolfs Thank you for letting us know this issue :+1:
This seems to be a bug in the `azurerm_automation_account` data source code, where it uses the **automation account agent registration info ID** as **ID of automation account**. I will submit a fix soon!
