### ISSUE TITLE
azurerm_log_analytics_workspace Free sku with 7 days of data retention

### ISSUE THREAD

**Issue by palmerabollo** [terraform-providers/terraform-provider-azurerm#6764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
azurerm provider version 2.7.0
```

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Terraform Configuration Files

```
resource "azurerm_log_analytics_workspace" "workspace" {
  name                = "${var.name}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  sku                 = "Free"
  retention_in_days   = 7
}
```

### Expected Behavior

The Azure Log Analytics workspace should be created with "Free" sku and 7 days of data retention. 7 days is a valid value for the "Free" sku.

![Screenshot 2020-05-05 at 08 24 40](https://user-images.githubusercontent.com/673420/81039658-f2a8fe00-8ea9-11ea-8f22-f5baeb3b5e51.png)

### Actual Behavior

Terraform plan fails. It says 30 days is the minimum value for `retention_in_days` even when 7 is the maximum value for the Free sku in Azure.

> Error: expected retention_in_days to be in the range (30 - 730), got 7

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/2949

**Comment by magodo** [comment]
@palmerabollo Thank you for letting us know this issue :+1:
I will submit a fix soon!
