### ISSUE TITLE
Feature Request: Support for Azure AD Service Principal / Application ID Creation

### ISSUE THREAD

**Issue by kmcquade** [terraform-providers/terraform-provider-azurerm#677]
### Terraform Version
0.11.1

### Affected Resource(s)

- Azure AD Service Principal creation (referred to as principal ID [here](https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html#principal_id).

### Expected Behavior
Create Azure AD Service Principal. It would be nice to create a service principal for an application without having to do it with PowerShell first.

### Example Flow

Example with currently supported terraform module:
https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html#principal_id
* In CI server, using CI server's service principal
* Supply subscription ID, etc.
* Create service principal for an application (without having to do powershell first)
* Create resource group for application
* Create role definition, limited to that resource group via scope
* Create role assignment, limited to that principal

### Benefits
* Create and destroy service principal for an application via Terraform at build time. 
* Prevents "dangling principals" so to speak
* Avoid ugly powershell before build and destroy

**Comment by tombuildsstuff** [comment]
Hey @kmcquade 

Thanks for opening this issue :)

This functionality has previously been requested in #16 - so that we don't have multiple issues tracking the same thing I'm going to close this issue in favour of #16.

Thanks!
