### ISSUE TITLE
Unexpected windows_profile block in azurerm kubernetes cluster 

### ISSUE THREAD

**Issue by manish-eros** [terraform-providers/terraform-provider-azurerm#6770]
Hi 

Community Note
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I've a weird issue with azurerm kubernetes cluster, my environment is as follows:
```
terraform version
Terraform v0.12.24
provider.azurerm v1.44.0
```

* Affected Resource(s)
```
azurerm_kubernetes_cluster
```

I see an unexpected block of windows_profile although it hasn't been defined anywhere in the k8s module.
```
- windows_profile {
          - admin_username = "azureuser" -> null # forces replacement
        }
```
Upon first invocation of module k8s cluster is created correctly, however a consecutive run results into cluster destruction & recreation. I only see above reference that triggers replacement.

My module definition is as follows:
```
resource "azurerm_kubernetes_cluster" "azure-k8s" {
  name                = "en-${var.env}-aks"
  location            = "${var.location}"
  dns_prefix          = "en${var.env}aks"
  resource_group_name = "${var.resource_group_name}"
  linux_profile {
    admin_username = "${var.os_username}"
    ssh_key {
      key_data = file("~/.ssh/stg.pub")
    }
  }
  addon_profile {
    kube_dashboard {
      enabled = "true"
    }
    oms_agent {
      enabled = true
      log_analytics_workspace_id = "${var.log_analytics_workspace_id}"
    }
  }
  default_node_pool {
    name            = "k8sagentpool"
    vm_size         = "${var.agent_pool_vmsize}"
    os_disk_size_gb = 30
    vnet_subnet_id = "${var.vnet_id}"
    enable_auto_scaling = "true"
    max_count = "${var.agent_pool_count}"
    min_count = "${var.min_count}"
    node_count = "${var.min_count}"
    availability_zones  = [1, 2, 3]
    type = "VirtualMachineScaleSets"
  }
  service_principal {
    client_id     = "${var.kubernetes_client_id}"
    client_secret = "${var.kubernetes_client_secret}"
  }
  network_profile {
    network_plugin = "azure"
    load_balancer_sku = "standard"
  }
  # If you're using AutoScaling, you may wish to use Terraform's ignore_changes functionality to ignore changes to the node_count field.
  lifecycle {
    ignore_changes = [default_node_pool["node_count"]]
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @manish-eros 

Unfortunately this is due to a Breaking Behavioural Change in the AKS API - version 2.5.0 of the Azure Provider (and later) account for this behaviour (although v2.8.0 is the latest/current release) - you can upgrade to this by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=2.8.0"
}
```

Since this should be fixed by upgrading the version of the Azure Provider being used, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by manish-eros** [comment]
Hi Tom,

I did upgrade azurerm provider version to 2.8.0 as per your suggestion & ran upgrade for all of my modules. However I'm getting mixed results only for azurerm_kubernetes_cluster.

I've two environments prod, stg & in both of these I've a k8s cluster. In production post upgrade when I run terraform plan, it says 
```
No changes. Infrastructure is up-to-date.
```
which is inline to my expectation. However when I run terraform plan for stage environment, plan confirms the k8s cluster needs to be destroyed & recreated.

```
  # module.azure-stgk8scluster.azurerm_kubernetes_cluster.azure-k8s must be replaced
-/+ resource "azurerm_kubernetes_cluster" "azure-k8s" {
      - api_server_authorized_ip_ranges = [] -> null
```

What could be reason for this behavior?

Thanks
