### ISSUE TITLE
Unable to create azurerm_monitor_metric_alert on Azure Monitor for Containers

### ISSUE THREAD

**Issue by jmcshane** [terraform-providers/terraform-provider-azurerm#6775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.24
Azurerm 2.3.0

### Affected Resource(s)

* `azurerm_monitor_metric_alert`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "alert" {
  name                = "metric"
  resource_group_name = azurerm_resource_group.group.name
  scopes              = [azurerm_kubernetes_cluster.aks.id]
  description         = "Alert will be triggered when utilization is more than 80%"
   
  criteria {
      metric_namespace = "Insights.Container/nodes"
      metric_name      = "CpuUsagePercentage"
      aggregation      = "Maximum"
      operator         = "GreaterThanOrEqual"
      threshold        = 80
       
      dimension {
          name     = "Host"
          operator = "Include"
          values   = ["*"]
      }
  }
   
  action {
    action_group_id = azurerm_monitor_action_group.action_group.id
  }
}
```

Also tried `cpuUsagePercentage`

### Expected Behavior

Terraform should create the metric

### Actual Behavior

Error: Error creating or updating metric alert "alert" (resource group "group"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The following metric name(s) were not found: CpuUsagePercentage. Please note that for custom metrics, the relevant metric namespace must be specified."

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

* https://www.terraform.io/docs/providers/azurerm/r/monitor_metric_alert.html

**Comment by jmcshane** [comment]
Information from the azure cli:

`az monitor metrics list-definitions --resource /subscriptions/************/resourceGroups/group/providers/Microsoft.ContainerService/managedClusters/cluster --namespace Insights.Container/nodes`

```
    "name": {
      "localizedValue": null,
      "value": "cpuUsagePercentage"
    },
    "namespace": "Insights.Container/nodes",
    "primaryAggregationType": "Average",
    "resourceGroup": "group",
    "resourceId": "aks_id",
    "supportedAggregationTypes": [
      "Average",
      "Maximum",
      "Minimum"
    ],
```

**Comment by Dipluz** [comment]
Hey, after struggling with this myself I came accross this from Microsoft's own documentation. https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-near-real-time

This solved my own issues with creating metric alerts.

**Comment by magodo** [comment]
@jmcshane Thank you for submitting this issue :+1: 

This issue is because the AKS you created in provider v2.3.0 is towards the API version **2019-11-01**, in which version the **metricDefinitions** doesn't have the `CpuUsagePercentage`. You can check that via either plain API or az CLI.

I suppose the output you pasted [above](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6775#issuecomment-624136723) is not the exact same resource in question since the old version AKS cluster have no namespace `Insights.Container/nodes` (you can list all the supported namespaces for a certain resource via [this](https://docs.microsoft.com/en-us/rest/api/monitor/metricnamespaces/list) API).

This issue doesn't exist in the latest provider (v2.9.0), where the API version underused for AKS is **2020-02-01**. The AKS clusters created in this endpoint now supports the **metricDefinitions** like `CpuUsagePercentage`. So I would suggest you bump the provider version to the latest.

**Comment by jmcshane** [comment]
@magodo  I delete the AKS cluster and recreated with v2.9.0 of the provider and received the same error message

**Comment by magodo** [comment]
@jmcshane Is it possible to share the terraform config and debug log (TF_LOG=DEBUG)? As I can't reproduce it on my side with v2.9.0.

**Comment by jmcshane** [comment]
```
resource "azurerm_monitor_metric_alert" "metric_alert" {
  name                = "util_alert"
  resource_group_name = azurerm_resource_group.group.name
  scopes              = [azurerm_kubernetes_cluster.aks.id]
  description         = "Alert will be triggered when avg utilization is more than 80%"

  criteria {
    metric_namespace = "Insights.Container/nodes"
    metric_name      = "CpuUsagePercentage"
    aggregation      = "Average"
    operator         = "GreaterThanOrEqual"
    threshold        = 80

    dimension {
      name     = "Host"
      operator = "Include"
      values   = ["*"]
    }
  }

  action {
    action_group_id = azurerm_monitor_action_group.action_group.id
  }
}
```

Getting tf debug log and removing sensitive info now

**Comment by jmcshane** [comment]
Ran with the latest provider and terraform version and everything worked, thanks for trying to reproduce

**Comment by jmcshane** [comment]
Ok, this worked once, but now is failing in the production environment. I have the relevant TF_LOG=debug section here:

```
2020-06-12T08:34:41.164-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.14.0_x5: {"location":"global","properties":{"description":"Alert will be triggered when utilization is more than 80%","severity":3,"enabled":true,"scopes":["/subscriptions/******/resourcegroups/******/providers/Microsoft.ContainerService/managedClusters/aks-cluster"],"evaluationFrequency":"PT1M","windowSize":"PT5M","criteria":{"allOf":[{"criterionType":"StaticThresholdCriterion","dimensions":[{"name":"Host","operator":"Include","values":["*"]}],"metricName":"CpuUsagePercentage","metricNamespace":"Insights.Container/nodes","name":"Metric1","operator":"GreaterThanOrEqual","threshold":80,"timeAggregation":"Maximum"}],"odata.type":"Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"},"autoMitigate":true,"actions":[{"actionGroupId":"/subscriptions/******/resourceGroups/******/providers/microsoft.insights/actionGroups/Email Alert For Aks Cluster","webHookProperties":{}}]},"tags":{}}
2020-06-12T08:34:42.059-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.14.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/*******/resourceGroups/*****/providers/Microsoft.Insights/metricAlerts/alert?api-version=2018-03-01:
2020-06-12T08:34:42.059-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.14.0_x5: HTTP/2.0 400 Bad Request
2020-06-12T08:34:42.059-0500 [DEBUG] plugin.terraform-provider-azurerm_v2.14.0_x5: {"Code":"BadRequest","Message":"The following metric name(s) were not found: CpuUsagePercentage. Please note that for custom metrics, the relevant metric namespace must be specified."}
```

It seems like the API version for Microsoft.Insights is potentially out of date?

**Comment by jmcshane** [comment]
OK, I needed to follow these steps: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-update-metrics
