### ISSUE TITLE
azurerm_express_route_circuit_peering optional resources are flagged as required

### ISSUE THREAD

**Issue by ttyS0** [terraform-providers/terraform-provider-azurerm#6776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform: `v0.12.24`
azurerm: `v2.8.0`

### Affected Resource(s)

* `azurerm_express_route_circuit_peering`

### Terraform Configuration Files

```hcl
resource "azurerm_express_route_circuit_peering" "foo" {
  express_route_circuit_name = azurerm_express_route_circuit.foo.name
  peering_type = "AzurePrivatePeering"
  resource_group_name = azurerm_resource_group.foo.name
}
```

### Expected Behavior

The resource should be created without requiring optional configuration elements. Alternatively the documentation should be updated to mark the above values as required. 

The documentation page is: https://www.terraform.io/docs/providers/azurerm/r/express_route_circuit_peering.html

### Actual Behavior

```
Error: Missing required argument

  on expressroute.tf line 23, in resource "azurerm_express_route_circuit_peering" "foo":
  23: resource "azurerm_express_route_circuit_peering" "foo" {

The argument "primary_peer_address_prefix" is required, but no definition was
found.


Error: Missing required argument

  on expressroute.tf line 23, in resource "azurerm_express_route_circuit_peering" "foo":
  23: resource "azurerm_express_route_circuit_peering" "foo" {

The argument "secondary_peer_address_prefix" is required, but no definition
was found.


Error: Missing required argument

  on expressroute.tf line 23, in resource "azurerm_express_route_circuit_peering" "foo":
  23: resource "azurerm_express_route_circuit_peering" "foo" {

The argument "vlan_id" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lrxtom2** [comment]
Thanks for reporting the issue. @ttyS0 
PR submitted to fix it.
