### ISSUE TITLE
Support for apex domains in azurerm_frontdoor

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#6781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Putting apex domains on a front door is a lot more complicated than simply adding a custom domain with the CNAME record. You have to create the front door first, add the A record with an ALIAS back to the front door, and then add the custom domain record to Front Door. This is not an easy thing to do in Terraform right now (that I'm aware). Judging by the reactions of [this thread](https://feedback.azure.com/forums/217313-networking/suggestions/35530549-add-custom-apex-naked-domains-as-front-end-hosts), this was a pretty sought after capability of Front Door. Documentation below in the [References](#references) from Microsoft explains it.

My suggestion is to have an optional parameter that points to the Azure DNS Zone by the ARM ID. I say the AzureRM ID because if it is provided, the requred A record and "afdverify" CNAME record can be created within the DNS Zone and can then verify the domain. If it's omitted, it does the `host_name` check for CNAME record like normal.

### New or Affected Resource(s)

Definitely

* azurerm_frontdoor

Potentially

* azurerm_dns_zone
* azurerm_dns_a_record

### Potential Terraform Configuration

```hcl

resource "azurerm_frontdoor" "fd_custom" {
  enforce_backend_pools_certificate_name_check = true
  name                                         = "myfrontdoor"
  resource_group_name                          = var.resource_group_name

  backend_pool_load_balancing {
    name = "default-balancer"
  }

  backend_pool_health_probe {
    name         = "default-probe"
  }

  frontend_endpoint {
    name                                    = "default"
    host_name                               = "myfrontdoor.azurefd.net"
    custom_https_provisioning_enabled       = false
    web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.fd_waf.id
  }

  frontend_endpoint {
    name                                    = "apex-domain"
    dns_zone_id                             = data.azurerm_dns_zone.dns_zone.id
    custom_https_provisioning_enabled       = true

    custom_https_configuration {
        # Brevity, this would have key vault settings if HTTPS
    }
  }

  backend_pool {
    # Brevity
  }

  routing_rule {
    # Brevity
  }
}
```

### References

[Onboarding Apex Domain to Front Door](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-how-to-onboard-apex-domain)

**Comment by sonersari** [comment]
Another problem is that `frontend_endpoint` should be added as a seperate resource like `custom_https_configuration` otherwise you'll have a circular dependency problem when you try to configure frontdoor with apex domain. 

For now we have to define the all frontend endpoints during creation of  the frontdoor but it fails if frontend endpoint does not have a dns record and you can't create alias record for frontdoor before creation of the frontdoor.

It is supported on azure api or cli but there is no way to figure it with terraform for now or I could not find :)

**Comment by michaelelleby** [comment]
> It is supported on azure api or cli but there is no way to figure it with terraform for now or I could not find :)

How is this supported on Azure CLI? I mean how do I trigger Front Door to skip validation of frontend endpoint hostnames, when creating frontend endpoints?

**Comment by WodansSon** [comment]
As @michaelelleby mentioned in issue #8848:
> Azure created a workaround for apex domains: You have to create a regular CNAME record in your DNS, mapping afdverify.<yourdomain> to afdverify.<your front door name>.azurefd.net and then you can deploy Azure Front Door with a frontendEndpoint listening on that apex domain. [product documentation](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-custom-domain#map-the-temporary-afdverify-subdomain)

With that said I am going to go ahead and close this issue as it appears to be a configuration issue which Azure has offered a fix for. Thank you for reporting this issue. 🚀
