### ISSUE TITLE
azurerm_api_management fails for Consumption SKU

### ISSUE THREAD

**Issue by phbarton** [terraform-providers/terraform-provider-azurerm#6794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
AzureRM provider: v2.8.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "apim" {
  name                = "${var.name_base}apim"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  publisher_email     = "email@example.com"
  publisher_name      = "Test Account"
  sku_name            = "Consumption_1"

  protocols {
    enable_http2 = true
  }

  tags = {
    environment = var.environment_tag
  }
}
```

### Expected Behavior

The APIM resource should have been provisioned.

### Actual Behavior

Failed with a 400 status code, stating that the capacity should be set to zero `Consumption_0`. When the value is changed to zero, the provided fails with an error stating that the capacity should be 1 or greater. Removing the capacity generates a format error.

### Steps to Reproduce

1. Create an azurerm_api_management resource as above with sku_name = "Consumption_1" or "Consumption_0" or "Consumption"
 
2. `terraform apply`

* #0000

**Comment by yupwei68** [comment]
Duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/6730

**Comment by phbarton** [comment]
Closing as duplicate
