### ISSUE TITLE
issues with subscription key and import in API-M since 2.7.0

### ISSUE THREAD

**Issue by tnicolaysen** [terraform-providers/terraform-provider-azurerm#6795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
terraform-provider-azurerm 2.8.0 (most likely 2.7.0 also)

### Affected Resource(s)

* `azurerm_api_management_api`
* `azurerm_api_management_subscription`

It's also likely that other API-M resources are affected.

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "= 2.8.0"
  skip_provider_registration = true
}

terraform {
  backend "azurerm" {}
  required_version = ">= 0.12.26"
}

data "azurerm_api_management" "apim" {
  name                = var.apim_name
  resource_group_name = var.apim_resource_group
}


resource "azurerm_api_management_user" "example" {
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = data.azurerm_api_management.apim.resource_group_name
  email               = "demo@example.org"
  first_name          = "John"
  last_name           = "Doe"
  user_id             = "john-doe"
}


resource "azurerm_api_management_product" "example" {
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = data.azurerm_api_management.apim.resource_group_name

  product_id            = "example"
  display_name          = "Example Product"
  published             = true
  subscription_required = true
}


resource "azurerm_api_management_subscription" "example" {
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = data.azurerm_api_management.apim.resource_group_name

  display_name = "Example Subscription"
  product_id   = azurerm_api_management_product.example.id
  user_id      = azurerm_api_management_user.example.id
  state        = "active"

  // NOTICE: Primary/Secondary subscription keys not set, supposed to be created automatically
}


resource "azurerm_key_vault_secret" "example_pk" {
  key_vault_id = var.keyvault_id
  name         = "SubscriptionPrimaryKey"
  value        = azurerm_api_management_subscription.example.primary_key

  // The value here is empty because the primary_key value is not properly set in the resource
}


resource "azurerm_api_management_product_api" "example" {
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = data.azurerm_api_management.apim.resource_group_name
  api_name            = azurerm_api_management_api.example.name
  product_id          = azurerm_api_management_product.example.product_id
}


resource "azurerm_api_management_api" "example" {
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = data.azurerm_api_management.apim.resource_group_name

  display_name      = "Example API"
  name              = "example-api"
  path              = "example-api"
  protocols         = ["https"]
  revision          = "1"
  service_url       = "http://example.org"
  soap_pass_through = true

  // NOTICE: It partially works when not having an import, but it's just one of the issues
  import {
    content_format = "wsdl"
    content_value = file("example.wsdl")
  }
}

// This one is empty because of the issue
output "primary_key" {
  value     = azurerm_api_management_subscription.example.primary_key
  sensitive = true
}
```

### Expected Behavior

Create API-M resources as defined in Terraform.

### Actual Behavior

* On my existing infrastructure my primary and secondary subscription key was changed to empty strings, and since it was referenced in Key Vault resources this lead to some unfortunate behavior

* When setting up in a new API-M instance it complains that the API already exists and that the AzureRM API returns HTTP 409. 
  * Likely related to import flow (see comments below)
* Primary and secondary subscription keys are not properly set on the resource

### Steps to Reproduce

1. `terraform apply`

The normal stuff...

### Important Factoids

* The problem is likely harder to detect for Terraform users that are just bumping the version and applying on an existing version.
* I have a strong suspicion that other things might have changed in subtle ways after upgrading to 2019 APIs. 
  * I think I had some issues caused by missing/faulty API deletion, but I didn't dive into this when creating this issue. I checked the debug logs, and at first glance I could not see a HTTP DELETE request being made to any API resource. Something to check. 🔍
* If creating the API without an import block, apply the infrastructure, then add the import block and run apply again, it works.

I looked at the resource code, and I can see some potential issues.

* I think there's something in the flow of this method that could be causing the missing subscription keys. https://github.com/terraform-providers/terraform-provider-azurerm/blob/63028d8188f747213967231bde38d559d2b91e71/azurerm/internal/services/apimanagement/resource_arm_api_management_subscription.go#L97
  * I checked that the Azure RM REST API returns the value 
* This workaround https://github.com/terraform-providers/terraform-provider-azurerm/blob/63028d8188f747213967231bde38d559d2b91e71/azurerm/internal/services/apimanagement/resource_arm_api_management_api.go#L241-L279 might have fixed an issue that was present in the 2018 version of the API, but which now is causing issues (specifically the HTTP 409 issue).
  * The error does not happen if I don't have an import, strengthening my suspicions

**Comment by yupwei68** [comment]
hi @tnicolaysen Thanks for opening this issue. This issue contains two bug: 1. `azurerm_api_management_subscription` primary/secondary key is empty 2.`azurerm_api_management_api`  `wsdlSelector` block required

**Comment by tnicolaysen** [comment]
@yupwei68 Do you want me to split it into to bugs? Also, I think this is a serious bug.

**Comment by yupwei68** [comment]
@tnicolaysen ,thanks. It's fine to be as current. I'm working on them. I'll raise PRs for them soon.
