### ISSUE TITLE
Can't delete and immediately recreate a storage container

### ISSUE THREAD

**Issue by algattik** [terraform-providers/terraform-provider-azurerm#6803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.24
"azurerm" (hashicorp/azurerm) 2.2.0

### Affected Resource(s)

* `azurerm_storage_container`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "capture_storage_container" {
  name                  = lower(var.area_name)
  storage_account_name  = var.capture_storage_account_name
  container_access_type = "private"
}
```

### Debug Output

```
terraform destroy
azurerm_storage_container.capture_storage_container: Destroying... [id=https://strgappmercurycd.blob.core.windows.net/master]
azurerm_storage_container.capture_storage_container: Destruction complete after 0s
```

```
terraform apply
Acquiring state lock. This may take a few moments...
azurerm_storage_container.capture_storage_container: Creating...
Error: Error creating Container "master" (Account "strgappmercurycd" / Resource Group “ci-rg-001"): containers.Client#Create: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ContainerBeingDeleted" Message="The specified container is being deleted. Try operation later.\nRequestId:38c204cc-f01e-001f-7cc4-239161000000\nTime:2020-05-06T16:36:08.1842227Z"

  on main.tf line 15, in resource "azurerm_storage_container" "capture_storage_container":
  15: resource "azurerm_storage_container" "capture_storage_container" {
```
```


### Panic Output

<!--- If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behavior

<!--- What should have happened? --->
For integration testing we delete and reprovision the full environment immediately. Thus it should be possible to delete a storage container and recreate it immediately afterwards.

### Actual Behavior

<!--- What actually happened? --->
Terraform apply failed.

### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform destroy`
1. `terraform apply`

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

* #0000

**Comment by algattik** [comment]
https://docs.microsoft.com/en-us/rest/api/storageservices/delete-container#remarks

*When a container is deleted, a container with the same name cannot be created for at least 30 seconds; the container may not be available for more than 30 seconds if the service is still processing the request. While the container is being deleted, attempts to create a container of the same name will fail with status code 409 (Conflict), with the service returning additional error information indicating that the container is being deleted.*

**Comment by ArcturusZhang** [comment]
Hi @algattik thanks for this issue!

Sometimes this kind of situation happens, when an async operation returns success, but in fact the operation is still in progress. We can add something like a `StateRefreshFunc` after the Delete operation to let terraform wait until the storage container is successfully deleted before it claims deletion success.

**Comment by algattik** [comment]
@ArcturusZhang probably that wouldn't work as it seems there's no way to query whether deletion has completed. If that is true, then the only fix is probably to retry on creation as long as this status is being returned.
