### ISSUE TITLE
Support for dedicated eventhub clusters

### ISSUE THREAD

**Issue by favoretti** [terraform-providers/terraform-provider-azurerm#6808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've noticed that azure-go-sdk got preview support for dedicated eventhub clusters - would it be possible to implement that resource? We're using those extensively and currently are forced to create them by hand. Moreover eventhub_namespace support max 32 partitions in hosted and unlimited in dedicated, but the resource in provider caps the partition count to 32.

**Comment by favoretti** [comment]
@mbfrahry It seems https://github.com/Azure/azure-sdk-for-go/issues/8533 has been addressed, any chance you could try your changes again and if they work merge them? Thank you!

**Comment by favoretti** [comment]
@mbfrahry Tested your branch with 43.0.0 and EHC creation works.

**Comment by brandonh-msft** [comment]
Any idea when we can expect to see this in a release? Just had a look at the associated milestone and says due today. Is it on track?

**Comment by favoretti** [comment]
@brandonh-msft it's released, but there's another thing that makes it tricky - namespace doesn't support assigning to the clusters yet :) see https://github.com/terraform-providers/terraform-provider-azurerm/pull/7347
