### ISSUE TITLE
Questions around subnet & mysql VNET rule post upgrade to 2.8.0 

### ISSUE THREAD

**Issue by manish-eros** [terraform-providers/terraform-provider-azurerm#6811]
Hi, 

We had been using azurerm version 1.44 till now & it was working very well. We ran into this [bug](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6770) & we ended up upgrading azure provider version from 1.44 to 2.8.0. 

Post upgrade when I'm trying to create a subnet (standalone resource) inside a VNET (VNET was created using provider version 1.44) I'm getting following error: 
```
Error: Error Creating/Updating Subnet "en-prod-vm-snet" (Virtual Network "en-prod-vnet" / Resource Group "en-prod-rg"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NetcfgInvalidSubnet" Message="Subnet 'en-prod-vm-snet' is not valid in virtual network 'en-prod-vnet'." Details=[]
```

Same goes for mysql VNET rule which was working alright under azure provider version 1.44, but now giving following error:

```
Error: Error creating MySQL Virtual Network Rule "pocmysql-vnet-rule" (MySQL Server: "en-prod-pocmysql-mysqldb", Resource Group: "en-prod-rg"): mysql.VirtualNetworkRulesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="VirtualNetworkRuleBadRequest" Message="Network resource provider returned following error: 'Subnets en-prod-db-snet of virtual network /subscriptions/b723e953-6f67-474e-8dae-13629c5d68e9/resourceGroups/en-prod-rg/providers/Microsoft.Network/virtualNetworks/en-prod-vnet do not have ServiceEndpoints for Microsoft.Sql resources configured. Add Microsoft.Sql to subnet's ServiceEndpoints collection before trying to ACL Microsoft.Sql resources to these subnets.'.
```
Our terraform version:
```
terraform version                                       
Terraform v0.12.24
provider.azurerm v2.8.0
```
I'd like to know following:
1. Is there a need to start rewriting modules to suit version 2.8? 
2. If point # 1 isn't necessarily true & we can manage resources (created using azurerm provider version 1.44) using 2.8, what do we need to do to overcome above errors?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @manish-eros 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
