### ISSUE TITLE
Subnet delete doesn't compute dependencies correctly

### ISSUE THREAD

**Issue by brandonh-msft** [terraform-providers/terraform-provider-azurerm#6818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.8.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

I used the sample HCL for Azure App Service Environment

### Expected Behavior

Resources _within_ the subnet should've been deleted, _then_ the subnet.

### Actual Behavior

```
Error: Error deleting Subnet "asesubnet" (Virtual Network "xxxx" / Resource Group "xxxx"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet asesubnet is in use by /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Web/hostingEnvironments/xxxxand cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
```

### Steps to Reproduce

1. `terraform apply`

**Comment by magodo** [comment]
Hi @brandonh-msft Thank you for letting us know this issue :+1:
Is it possible to check whether the `azurerm_app_service_environment` has been created successfully (instead of partially) before you trying to delete it. Additionally, it would be helpful if you could provide the `terraform.tfstate` file and the debug log (`TF_LOG=DEBUG`) output from `terraform apply` (for delete).

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to confirm if this is still an issue then we should be able to reopen this and take another look.

Thanks!
