### ISSUE TITLE
DoNotRunExtensionsOnOverprovisionedVMs wont work

### ISSUE THREAD

**Issue by ddccomp** [terraform-providers/terraform-provider-azurerm#6830]
DoNotRunExtensionsOnOverprovisionedVMs property for VMSS  won't work

Using following TF provider 

provider "azurerm" {
  version = "=2.5.0"
  features {}
}

resource "azurerm_linux_virtual_machine_scale_set" "instance" {
  .........
  .........
do_not_run_extensions_on_overprovisioned_machines = true
.........
.........
}

On running TF plan and apply we see changes are applicable but that wont effect Azure Resource and you see changes are need to be made in Azure resource with every further TF plan and apply

**Comment by ArcturusZhang** [comment]
Hi @ddccomp thanks for this issue!

I just went through the code of `azurerm_linux_virtual_machine_scale_set` and found nothing peculiar about it...
I know the `Overprovision` is on by default but still I will need to confirm, is `Overprovision` enabled in your case? And it would be best for us to determine where the problem is if you could provide a log when this happens. You could export two variables `TF_LOG=TRACE` and `TF_LOG_PATH=/path/to/your/log/file` to get the log.

**Comment by ddccomp** [comment]
Both properties are set to true

```
  overprovision                   = true
  do_not_run_extensions_on_overprovisioned_machines = true
```

Log shows following warning 

```
........
2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:   "zones": [
2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "1",
2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "2",
2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "3"
2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:   ]
2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5: }
2020/05/11 11:04:04 [WARN] Provider "registry.terraform.io/-/azurerm" produced an unexpected new value for module.XXXXgetsXXX.module.XXXXgetsXXX.azurerm_linux_virtual_machine_scale_set.instance, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .do_not_run_extensions_on_overprovisioned_machines: was cty.True, but now cty.False
2020/05/11 11:04:04 [TRACE] module.XXXXgetsXXX.module.XXXXgetsXXX: eval: *terraform.EvalMaybeTainted
2020/05/11 11:04:04 [TRACE] module.XXXXgetsXXX.module.XXXXgetsXXX: eval: *terraform.EvalWriteState

---------------
```

**Comment by ArcturusZhang** [comment]
> Both properties are set to true
> 
> ```
>   overprovision                   = true
>   do_not_run_extensions_on_overprovisioned_machines = true
> ```
> 
> Log shows following warning
> 
> ```
> ........
> 2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:   "zones": [
> 2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "1",
> 2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "2",
> 2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "3"
> 2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:   ]
> 2020-05-11T11:04:04.747+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5: }
> 2020/05/11 11:04:04 [WARN] Provider "registry.terraform.io/-/azurerm" produced an unexpected new value for module.XXXXgetsXXX.module.XXXXgetsXXX.azurerm_linux_virtual_machine_scale_set.instance, but we are tolerating it because it is using the legacy plugin SDK.
>     The following problems may be the cause of any confusing errors from downstream operations:
>       - .do_not_run_extensions_on_overprovisioned_machines: was cty.True, but now cty.False
> 2020/05/11 11:04:04 [TRACE] module.XXXXgetsXXX.module.XXXXgetsXXX: eval: *terraform.EvalMaybeTainted
> 2020/05/11 11:04:04 [TRACE] module.XXXXgetsXXX.module.XXXXgetsXXX: eval: *terraform.EvalWriteState
> 
> ---------------
> ```

Could you please post the log of the request body? I want to confirm that in the request, these two options are properly valued. If so, this may be an issue of the service itself rather than an issue with terraform.

**Comment by ddccomp** [comment]
```
2020-05-11T11:03:56.729+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5: X-Ms-Request-Id: 4e584325-3907-458e-9c3b-ee7df250b575
2020-05-11T11:03:56.729+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5: X-Ms-Routing-Request-Id: SOUTHINDIA:20200511T053356Z:74454e60-fa5c-466a-84ff-a2b9e7b57b02
2020-05-11T11:03:56.729+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5: 
2020-05-11T11:03:56.729+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5: {
2020-05-11T11:03:56.729+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:   "name": "XXXXXXXX",
.............................
.............................
.............................
2020-05-11T11:03:56.735+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "provisioningState": "Succeeded",
2020-05-11T11:03:56.735+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "overprovision": true,
2020-05-11T11:03:56.735+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "doNotRunExtensionsOnOverprovisionedVMs": false,
2020-05-11T11:03:56.735+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "uniqueId": "9c4cd8f9-587e-45d9-b8ef-3159fdb2368a",
2020-05-11T11:03:56.735+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "zoneBalance": false,
2020-05-11T11:03:56.735+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.5.0_x5:     "platformFaultDomainCount": 5

.............................
.............................
.............................
```

Hope this helps

**Comment by ArcturusZhang** [comment]
Hmmm... @ddccomp actually I think this should be the response. I see the `doNotRunExtensionsOnOverprovisionedVMs` is returned as `false` which means this is not enabled as the config says. But could you please provide the *request* of this? Should be right above these lines.
I think we should ensure that the request terraform attempting to send is correct first.

**Comment by ddccomp** [comment]
Hi,
I see three occurrences of doNotRunExtensionsOnOverprovisionedVMs in log and all says [DEBUG] `plugin.terraform-provider-azurerm_v2.5.0_x5:     "doNotRunExtensionsOnOverprovisionedVMs": false,`

**Comment by tombuildsstuff** [comment]
@ArcturusZhang looks like this field is missing from the update function - so we'll need to add:

```
	if d.HasChange("do_not_run_extensions_on_overprovisioned_machines") {
		v := d.Get("do_not_run_extensions_on_overprovisioned_machines").(bool)
		updateProps.DoNotRunExtensionsOnOverprovisionedVMs = utils.Bool(v)
	}
```

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang looks like this field is missing from the update function - so we'll need to add:
> 
> ```
> 	if d.HasChange("do_not_run_extensions_on_overprovisioned_machines") {
> 		v := d.Get("do_not_run_extensions_on_overprovisioned_machines").(bool)
> 		updateProps.DoNotRunExtensionsOnOverprovisionedVMs = utils.Bool(v)
> 	}
> ```

Thanks Tom... that explains a lot... I will be working on this to provide a quick fix.
