### ISSUE TITLE
'zone-reduntant' option is not available for azurerm_public_ip

### ISSUE THREAD

**Issue by rajatrawat99** [terraform-providers/terraform-provider-azurerm#6832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can not choose zones as zone-reduntant for azurerm_public_ip. Only possible options are 1, 2 or 3 whereas in azure portal you can choose zone-reduntant as zone.

### New or Affected Resource(s)

* azurerm_public_ip

### Potential Terraform Configuration

```hcl
resource "azurerm_public_ip_prefix" "example" {
  name                = "nat-gateway-publicIPPrefix"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  prefix_length       = 30
  zones               = ["Zone-reduntant"]
}

```

**Comment by ashijit** [comment]
@rajatrawat99 Correct me if I am wrong, but `zones` is an optional attribute. If it is not specified, then by default the IP has a Regional constraint, i.e. the public IP becomes zone redundant.

**Comment by rajat-rawat-sp** [comment]
@ashijit zones is a mandatory attribute if you creating sku standard type public ip address.

**Comment by rajatrawat99** [comment]
@ashijit zones is a mandatory attribute if you creating sku standard type public ip address.

**Comment by ashijit** [comment]
@rajatrawat99 You are right. I see that Standard SKU public IP addresses can be [zone-redundant or zonal](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-ip-addresses-overview-arm#standard).

**Comment by rajatrawat99** [comment]
I had opened a ticket with Terraform for this, they came back with a reply. if we dont give any zone then it becomes zone redundant by default. they have also updated the documentation for this.
Link of the updated doc:  https://www.terraform.io/docs/providers/azurerm/r/public_ip.html#argument-reference

Issue is solve so closing the issue.
