### ISSUE TITLE
azurerm_policy_set_definition does not set policyDefinitionReferenceId

### ISSUE THREAD

**Issue by cananac** [terraform-providers/terraform-provider-azurerm#6843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_policy_set_definition" "example" {
  name         = "testPolicySet"
  policy_type  = "Custom"
  display_name = "Test Policy Set"

  parameters = <<PARAMETERS
    {
        "allowedLocations": {
            "type": "Array",
            "metadata": {
                "description": "The list of allowed locations for resources.",
                "displayName": "Allowed locations",
                "strongType": "location"
            }
        }
    }
PARAMETERS

  policy_definitions = <<POLICY_DEFINITIONS
    [
        {
            "parameters": {
                "listOfAllowedLocations": {
                    "value": "[parameters('allowedLocations')]"
                }
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e765b5de-1225-4ba3-bd56-1ac6695af988",
            "policyDefinitionReferenceId": "TestRef"
        }
    ]
POLICY_DEFINITIONS
}


```

### Expected Behavior

Reference Id field for the policy should be set in the initiative definition

### Actual Behavior

Reference Id is not set

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ArcturusZhang** [comment]
Hi @cananac thanks for this issue!

After some investigation, the API version of the policy SDK terraform is using is low (`2018-05-01`) and it does not support set `policyDefinitionReferenceId`. In this version of SDK, an element of `policy_definitions` attribute can only consist of two attribute: `policyDefinitionId` and `parameters`. Due to internal marshaling mechanism of golang, it does not prevent you assign extra fields, but during the marshaling, all the extra fields will be ignored. Therefore the extra fields will not appear in the request, so it will not in response (and of course it will not take effect).

I will take some time to update the api-version of the policy resource in terraform to `2019-05-01` which supports `policyDefinitionReferenceId`.

In addition, I tried the same thing using Azure CLI like this:
```
az policy set-definition create --name "test-dapzhang" --definitions .\definitions.json --params .\paramters.json
```
content of `definitions.json`
```
[
    {
        "parameters": {
            "listOfAllowedLocations": {
                "value": "[parameters('allowedLocations')]"
            }
        },
        "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e765b5de-1225-4ba3-bd56-1ac6695af988",
        "policyDefinitionReferenceId": "TestRef"
    }
]
```
content of `parameters.json`
```
{
    "allowedLocations": {
        "type": "Array",
        "metadata": {
            "description": "The list of allowed locations for resources.",
            "displayName": "Allowed locations",
            "strongType": "location"
        }
    }
}
```
And it gives you the expected result:
```
{
  "description": null,
  "displayName": null,
  "id": "/subscriptions/subsID/providers/Microsoft.Authorization/policySetDefinitions/tes
t",
  "metadata": {
    "createdBy": "SomeUUID",
    "createdOn": "2020-05-12T03:55:33.8160867Z",
    "updatedBy": null,
    "updatedOn": null
  },
  "name": "test",
  "parameters": {
    "allowedLocations": {
      "allowedValues": null,
      "defaultValue": null,
      "metadata": {
        "additionalProperties": null,
        "description": "The list of allowed locations for resources.",
        "displayName": "Allowed locations"
      },
      "type": "Array"
    }
  },
  "policyDefinitionGroups": null,
  "policyDefinitions": [
    {
      "groupNames": null,
      "parameters": {
        "listOfAllowedLocations": {
          "value": "[parameters('allowedLocations')]"
        }
      },
      "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e765b5de-1225-4ba3-bd56-1ac6695af988"
,
      "policyDefinitionReferenceId": "TestRef"
    }
  ],
  "policyType": "Custom",
  "type": "Microsoft.Authorization/policySetDefinitions"
}
```

**Comment by cananac** [comment]
Hi @ArcturusZhang,

Will this version change make policyDefinitionGroups support enabled as well?

Thanks,
Canan

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang,
> 
> Will this version change make policyDefinitionGroups support enabled as well?
> 
> Thanks,
> Canan

Well, I did not include this in PR #7018 , but this is supported by the current api-version.

**Comment by cananac** [comment]
Ok created another ticket for that https://github.com/terraform-providers/terraform-provider-azurerm/issues/7532. 
Thanks!
