### ISSUE TITLE
Support for Log Analytics auditing on azurerm_mssql_server/database

### ISSUE THREAD

**Issue by dlm69** [terraform-providers/terraform-provider-azurerm#6849]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please can we get some support for adding the Log Analytics destination on auditing. At present only the storage option is supported in the extended_auditing_policy block.

### New or Affected Resource(s)

azurerm_sql_server
azurerm_mssql_server

### Potential Terraform Configuration

resource "azurerm_mssql_server" "example" {
  name                         = "mssqlserver"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "12.0"
  administrator_login          = "missadministrator"
  administrator_login_password = "thisIsKat11"

  extended_auditing_policy {
    azuremonitor_target_enabled  = true
    log_analytics_workspace_id = data.azurerm_log_analytics_workspace.oms.id
  }

The arm template when setting is configured looks like this:
        {
            "type": "Microsoft.Sql/servers/auditingSettings",
            "apiVersion": "2017-03-01-preview",
            "name": "[concat(parameters('servers_xxxxxxxxxxxxxxx_name'), '/Default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Sql/servers', parameters('servers_xxxxxxxxxxxxxxx_name'))]"
            ],
            "properties": {
                "state": "Enabled",
                "retentionDays": 0,
                "auditActionsAndGroups": [
                    "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP",
                    "FAILED_DATABASE_AUTHENTICATION_GROUP",
                    "BATCH_COMPLETED_GROUP"
                ],
                "storageAccountSubscriptionId": "00000000-0000-0000-0000-000000000000",
                "isStorageSecondaryKeyInUse": false,
                **"isAzureMonitorTargetEnabled": true**
            }
        }
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by yupwei68** [comment]
Hi @dlm69 Thanks for opening this issue. Currently Log Analytics auditing is still in preview stage.

**Comment by dlm69** [comment]
@yupwei68 i know it’s in preview. But it’s been in preview since 2017 or 2018. Haven’t other features been supported in Terraform whilst still in preview?

**Comment by tom-dudley** [comment]
On a related note, even if you enable log analytics auditing manually on the resource (without storage account auditing set), terraform currently assumes all of the `extended_auditing_policy` properties relate purely to the storage account auditing. Thus you get the following:

```
- extended_auditing_policy {
          - retention_in_days                       = 0 -> null
          - storage_account_access_key_is_secondary = false -> null
        }
```

This performs a PUT which disables **all** auditing.

`PUT /subscriptions/FOO/resourceGroups/BAR/providers/Microsoft.Sql/servers/BAZ/extendedAuditingSettings/default?api-version=2017-03-01-preview HTTP/1.1`
PUT content: `{"properties":{"state":"Disabled"}}`

**Comment by yupwei68** [comment]
Hi @tom-dudley , thanks for your comments. We plan to have a separate resource azurerm_mssql_server_auditing in the next major release to solve this problem.

**Comment by katbyte** [comment]
Hey @tom-dudley, the reason we cannot support it at this time is it is not in the current version of the SDK/API we are using. Once that has been released (and i'm not sure the timeframe on that) we can support it, as long as it as at the very least in public preview!

**Comment by lotaezhao** [comment]
After closing #7393 which requested both Logs Analytics and Eventhub auditing on azurerm_mssql_server/database. Can this issue please be updated to also include Eventhub auditing support too.

**Comment by BarbetM** [comment]
Hi @yupwei68 
in your last comment, you said that the resource azurerm_mssql_server_auditing separation will permit to not disable all auditing.
How can I only disable the storage account auditing with this ressource ?
It seems that the storage_endpoint option is mandatory.

**Comment by yupwei68** [comment]
Hi @BarbetM , the storage_endpoint is not a mandatory field when you want to disable it. If you use `azurerm_mssql_server_extended_auditing_policy`, you can disable it by destroying the resource. If you use block `extended_auditing_policy` in `azurerm_mssql_server`, you can disable it by removing the whole block.

**Comment by dhirschfeld** [comment]
Hi @yupwei68, I've upgraded to 2.39 and I can no longer run `terraform apply` on my database.

Since `terraform` doesn't yet support a log analytics destination I configure that via PowerShell in a post-deployment `local-exec`. Combined with ignoring changes to `extended_auditing_policy` this *used to* work fine.

Now when I apply I get the below errors:
```
Error: expected "extended_auditing_policy.0.storage_account_access_key" to not be an empty string
Error: expected "extended_auditing_policy.0.storage_endpoint" url to not be empty
```

...so it does indeed seem like storage account information is now mandatory if you have otherwise configured auditing outside of `terraform`.

**Comment by yupwei68** [comment]
Hi @dhirschfeld Sorry that I can not reproduce your error. I've created a MS sql server, then I enable the auditing with a log analytics namespace, then I apply one change of tags for the sql server. They're applied successfully.
Please provide your hcl configuration and reproducing steps  to open a new issue for bug reports, if it blocks you.

**Comment by dhirschfeld** [comment]
I'll try and recreate a minimal, reproducible example...

**Comment by aristosvo** [comment]
A quick look at the current state of the API shows that it is currently possible to implement, with a few interesting implementation details from Azure side.

When I look at the [REST API docs for SQL auditing creation](https://docs.microsoft.com/en-us/rest/api/sql/database%20auditing%20settings/createorupdate) I see the following:


||||
| -- | -- | ------ |
| properties.isAzureMonitorTargetEnabled		| boolean  | Specifies whether audit events are sent to Azure Monitor. In order to send the events to Azure Monitor, specify 'state' as 'Enabled' and 'isAzureMonitorTargetEnabled' as true. When using REST API to configure auditing, Diagnostic Settings with 'SQLSecurityAuditEvents' diagnostic logs category on the database should be also created. Note that for server level audit you should use the 'master' database as {databaseName}. Diagnostic Settings URI format: PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/providers/microsoft.insights/diagnosticSettings/{settingsName}?api-version=2017-05-01-preview . For more information, see Diagnostic Settings REST API or Diagnostic Settings PowerShell |

This is the same pattern I also see when looking for the [ARM templates implementation](https://github.com/Azure/azure-quickstart-templates/tree/master/201-sql-auditing-server-policy-to-oms).

This basically means we have to adapt a curious way of enabling this feature.
- Or we update also Diagnostic settings from this resource
- Or we only set `state=Enabled` and `isAzureMonitorTargetEnabled=true` and add documentation to set the Diagnostic settings as well.

I have to think about it, maybe @katbyte or @tombuildsstuff have a valid opinion about this?

**Comment by dlm69** [comment]
It is possible now using the azurerm_monitor_diagnostic_setting on the master database. (You do need to do this separately on all other managed databases as well which is why i created the module). 

The azurerm_monitor_diagnostic_categories are absolutely needed as it is able to pull the security (auditing) related logs which you can't seem to do by explicitly adding them to azurerm_monitor_diagnostic_setting.

It goes something like this:
Root tf

```
data "azurerm_mssql_database" "master" {
  name      = "master"
  server_id = azurerm_mssql_server.default.id
}

module "master-diagnostics" {
  environment        = var.environment
  source             = "../../diagnostics/v1.0"
  target_resource_id = data.azurerm_mssql_database.master.id
}

```

Module
```
data "azurerm_log_analytics_workspace" "default" {
  name                = var.workspace
  resource_group_name = var.workspace_rg_name
}

data "azurerm_monitor_diagnostic_categories" "default" {
  resource_id = var.target_resource_id
}

resource "azurerm_monitor_diagnostic_setting" "default" {
  name                       = "diagnostics"
  target_resource_id         = var.target_resource_id
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.default.id

  dynamic "log" {
    iterator = log_category
    for_each = data.azurerm_monitor_diagnostic_categories.default.logs

    content {
      category = log_category.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 0
      }
    }
  }

  dynamic "metric" {
    iterator = metric_category
    for_each = data.azurerm_monitor_diagnostic_categories.default.metrics

    content {
      category = metric_category.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 0
      }
    }
  }
}

```

**Comment by aristosvo** [comment]
@dlm69 Just curious, why enable everything instead of only enabling `SQLSecurityAuditEvents`? This should work, right?

```hcl
data "azurerm_mssql_database" "master" {
  name      = "master"
  server_id = azurerm_mssql_server.default.id
}

module "master-diagnostics" {
  environment        = var.environment
  source             = "../../diagnostics/v1.0"
  target_resource_id = data.azurerm_mssql_database.master.id
}
```
Module:
```hcl
data "azurerm_log_analytics_workspace" "default" {
  name                = var.workspace
  resource_group_name = var.workspace_rg_name
}

data "azurerm_monitor_diagnostic_categories" "default" {
  resource_id = var.target_resource_id
}

resource "azurerm_monitor_diagnostic_setting" "default" {
  name                       = "diagnostics"
  target_resource_id         = var.target_resource_id
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.default.id
  
  // Enable "SQLSecurityAuditEvents"
  log {
    category = "SQLSecurityAuditEvents"
    enabled  = true
    retention_policy {
      days    = 0
      enabled = false
    }
  }
  
  // Disable everything else
  dynamic "log" {
    iterator = log_category
    for_each =  {
      for k, r in data.azurerm_monitor_diagnostic_categories.default.logs : k => r
      if contains(keys(r), "SQLSecurityAuditEvents")
    }
    
    content {
      category = log_category.value
      enabled  = false

      retention_policy {
        enabled = false
        days    = 0
      }
    }
  }
  
  // Disable all metrics
  dynamic "metric" {
    iterator = metric_category
    for_each = data.azurerm_monitor_diagnostic_categories.default.metrics

    content {
      category = metric_category.value
      enabled  = false

      retention_policy {
        enabled = false
        days    = 0
      }
    }
  }
}
```

**Comment by dlm69** [comment]
In theory it should work but I needed all logs so i didn't spend much time on it.

**Comment by surlypants** [comment]
hi. please consider that a sql server that services DW/synapse (vs standard mssql) has no 'master' DB.
