### ISSUE TITLE
Learn Terraform - Azure - Resource Dependencies sample code issue

### ISSUE THREAD

**Issue by pvandervelde** [terraform-providers/terraform-provider-azurerm#6863]
The sample at the bottom of the [Learn Terraform - Azure - Resource Dependencies](https://learn.hashicorp.com/terraform/azure/dependencies_az) page seems to be out of sync with the current version of Terraform (0.12.24).
Line 61:

    # Create network interface
    resource "azurerm_network_interface" "nic" {
    name                      = "myNIC"
    location                  = "westus2"
    resource_group_name       = azurerm_resource_group.rg.name
    network_security_group_id = azurerm_network_security_group.nsg.id

    ip_configuration {
        name                          = "myNICConfg"
        subnet_id                     = azurerm_subnet.subnet.id
        private_ip_address_allocation = "dynamic"
        public_ip_address_id          = azurerm_public_ip.publicip.id
      }
    }

The `network_security_group_id` doesn’t seem to be a part of the `azurerm_network_interface`  resource anymore. Instead you now need one of these:

    resource "azurerm_network_interface_security_group_association" "nic-nsg" {
      network_interface_id      = azurerm_network_interface.nic.id
      network_security_group_id = azurerm_network_security_group.nsg.id
    }

I haven't been able to find the source for the getting-started documentation so I was unable to provide a PR.

Note: I've reported this on the [user forums](https://discuss.hashicorp.com/t/learn-terraform-azure-resource-dependencies-sample-code-issue/8382) as well because I couldn't find a suitable place to notify people of this issue.

**Comment by tracypholmes** [comment]
Hi @pvandervelde! Thank you for making us aware of this issue. I've notified the appropriate team, and they've let me know they will take care of it. I'm going to close this issue now. Thanks again 😄

**Comment by pvandervelde** [comment]
I just found another issue with the documentation. Should I open a new ticket for that? The issue is that the `azure` provider needs a `features` section. That is missing on all azure getting-started pages. I'll be happy to either create a new ticket or to put in a PR if that helps :)

**Comment by tracypholmes** [comment]
@pvandervelde you are on it! I will let them know of that also - Thanks 😃
