### ISSUE TITLE
azurerm_bot_connection Azure Active Directory

### ISSUE THREAD

**Issue by tommyJimmy87** [terraform-providers/terraform-provider-azurerm#6873]
### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.5
+ provider.azuread v0.8.0
+ provider.azurerm v2.3.0

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from www.terraform.io/downloads.html
```

### Expected Behavior

Creation of the **BOT** with the **Teams** Channel and the **OAuth** connection set to `Azure Active Directory` as service provider

### Actual Behavior

The Chatbot and the Channel registration work, but when I try to add the Connection setting the Service Provider Name to : `Azure Active Directory` I get an error :

botservice.BotConnectionClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidBotData" Message="Invalid Service Provider Name. "

The name of the provider should be fine because I got it from the export of the ARM template that I previously manually created, It looks like an API problem but I'm not sure.

### Steps to Reproduce

```
resource "azurerm_bot_channels_registration" "bot_channel_dev" {
  name                                  = "test-bot"
  location                              = "global"
  resource_group_name                   = "RESOURCE_GROUP"
  sku                                   = "S1"
  microsoft_app_id                      = "APP_ID"
  developer_app_insights_key            = "APP_INSIGHT_KEY"
  developer_app_insights_application_id = "APP_INSIGHT_APP_ID"
}

resource "azurerm_bot_channel_ms_teams" "bot_channel_ms_teams_dev" {
  bot_name            = "${azurerm_bot_channels_registration.bot_channel_dev.name}"
  location            = "${azurerm_bot_channels_registration.bot_channel_dev.location}"
  resource_group_name = "${azurerm_resource_group.resource_group_dev.name}"
}

resource "azurerm_bot_connection" "bot_channel_ad_connection_dev" {
  name                  = "testBotConn"
  bot_name              = "${azurerm_bot_channels_registration.bot_channel_dev.name}"
  location              = "${azurerm_bot_channels_registration.bot_channel_dev.location}"
  resource_group_name   = "${azurerm_resource_group.resource_group_dev.name}"
  service_provider_name = "Azure Active Directory"
  client_id             = "${var.dev_1_bot_app_id}"
  client_secret         = "${var.dev_1_bot_app_secret}"
  scopes                = "openid OnlineMeetings.ReadWrite"
  
  parameters = {
    loginUri    = "https://login.microsoftonline.com"
    grantType   = "authorization_code"
    tenantId    = "${var.tenant_id}"
    resourceUri = "https://graph.microsoft.com/"
  }
}

```
### References

https://www.terraform.io/docs/providers/azurerm/r/bot_connection.html

**Comment by njuCZ** [comment]
@tommyJimmy87 if you want to use the `Azure Active Directory` (it's just a display name, not name) as the Service Provider Name, we should set 
```
resource "azurerm_bot_connection" "bot_channel_ad_connection_dev" {
     ......
     service_provider_name = "Aad"
     ......
}
```
sorry for missing notes in the doc and missing relative error messages, I will submit a PR to address it soon

**Comment by tommyJimmy87** [comment]
@njuCZ  Ehi thanks. Yes that's the guy. Sorry, but I couldn't find any docs on that.
