### ISSUE TITLE
Support for SQL Virtual Machine StorageConfigurationSettings

### ISSUE THREAD

**Issue by r0bnet** [terraform-providers/terraform-provider-azurerm#6874]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently you're not able to add StorageConfigurationSettings to the `azurerm_mssql_virtual_machine`. We're changing some values in that configuration in our ARM template currently so I'm not able to switch to the resource itself. The SDK supports it so it just needs to be implemented I guess.

Example excerpt in ARM:
```json
...
"StorageConfigurationSettings": {
  "DiskConfigurationType": "NEW",
  "StorageWorkloadType": "OLTP",
  "SQLDataSettings": {
    "LUNs": [0],
    "DefaultFilePath": "F:\\data"
  },
  "SQLLogSettings": {
    "LUNs": [0],
    "DefaultFilePath": "F:\\log"
  },
  "SQLTempDbSettings": {
    "DefaultFilePath": "D:\\tempDb"
  }
},
...
```

### New or Affected Resource(s)

* azurerm_mssql_virtual_machine

### Potential Terraform Configuration

Rough idea below:

```hcl
...
storage_configuration_settings {
  disk_configuration_type = "NEW"
  workload_type           = "OLTP"

  sql_data_luns              = [0]
  sql_data_default_file_path = "F:\\data"

  sql_logs_luns             = [0]
  sql_log_default_file_path = "F:\\log"

  sql_temp_db_luns             = [0]
  sql_tem_db_default_file_path = "D:\\tempDb"
}
...
```

Not sure if we really need a block here or if we can simply put all the items as top level properties. Needs to be figured out. We can potentially even get rid of the `sql_` prefixes for the LUNs and file paths.

### References

* https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go#L1649

**Comment by jonclyde** [comment]
@r0bnet I know this isn't yet included under azurerm_mssql_virtual_machine, but do you know of any other workaround for this using terraform? 

I've tried various things but cannot get the disks to pool up correctly in windows. This is an example of settings I've tried in the SqlIaaSExtension:

resource "azurerm_virtual_machine_extension" "SqlIaaSAgent" {
  name                 = "SqlIaasExtension"
  virtual_machine_id = azurerm_virtual_machine.example.id
  publisher            = "Microsoft.SqlServer.Management"
  type                 = "SqlIaaSAgent"
  type_handler_version = "2.0"
  auto_upgrade_minor_version = true

settings = <<SETTINGS
  {
    "sqlManagement": "Full",
    "SqlServerLicenseType": "PAYG",
    "AutoTelemetrySettings": {
      "Region": "westeurope"
    },
    "AutoPatchingSettings": {
      "PatchCategory": "WindowsMandatoryUpdates",
      "Enable": true,
      "DayOfWeek": "Sunday",
      "MaintenanceWindowStartingHour": "2",
      "MaintenanceWindowDuration": "60"
    },
    "KeyVaultCredentialSettings": {
      "Enable": false,
      "CredentialName": ""
    },
      "StorageConfigurationSettings": {
          "DiskConfigurationType": "NEW",
          "StorageWorkloadType": "OLTP",
            "SQLDataSettings": {
                "LUNs": "[1,2]",
                "DefaultFilePath": "T:\\MSSQL\\Data"
            },
        "SQLLogSettings": {
                "LUNs": "[3,4]",
                "DefaultFilePath": "U:\\MSSQL\\Data"
        },
        "SQLTempDbSettings": {
                "LUNs": "[5,6]",
                "DefaultFilePath": "T:\\MSSQL\\TempDB"
            }
        },
    
    "ServerConfigurationsManagementSettings": {
        "SQLConnectivityUpdateSettings": {
            "ConnectivityType": "Private",
            "Port": "1433"
        },
        "SQLWorkloadTypeUpdateSettings": {
            "SQLWorkloadType": "GENERAL"
        },
        "AdditionalFeaturesServerConfigurations": {
            "IsRServicesEnabled": "false"
        }
      }
  }
SETTINGS

}

**Comment by r0bnet** [comment]
Hey @jonclyde,

I got it working by attaching and formatting disk (and give it the preferred drive letter). You could do that with a Custom Script Extension and the deployment of the ARM template should depend on the extension because otherwise the disk won't be visible. I didn't implement it myself yet but did that manually at least once.

The script for disk initialization can be found here:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/attach-disk-ps#initialize-the-disk
Here the disks will get "ascending" drive letters assigned. I'd create a script that will init the disk with the letter you want (`T:` from what i see).

**Comment by jonclyde** [comment]
Thanks for that. 

I assume you'd then need to override the paths for SQL. I wonder if doing it this way would be recognised by the SQL IaaS Extension?

![image](https://user-images.githubusercontent.com/35006633/85305648-447f0500-b4a5-11ea-9944-25459eacb650.png)

**Comment by r0bnet** [comment]
I guess so but since I did the deployment via ARM I didn't check what the portal said. I guess a quick test can tell you more ;)

For that you can also do the disk initialization via RDP.

**Comment by a30000931** [comment]
hi @jonclyde  the extension doesn't expose these attributes unfortunately - maybe it runs 'too late' or some other reason known only to MSFT

The azurerm_mssql_virtual_machine terraform resource uses the Microsoft.SqlVirtualMachine/SqlVirtualMachines API to do this task.

when looking at the ARM generated by a SQL VM build and specifying individual disks the template does not use the extension at all - only the Microsoft.SqlVirtualMachine/SqlVirtualMachines elements.

The missing elements from azurerm_mssql_virtual_machine versus Microsoft.SqlVirtualMachine/SqlVirtualMachines are:

```
      "StorageConfigurationSettings": {
        "DiskConfigurationType": "NEW",
        "StorageWorkloadType": "OLTP",
        "SQLDataSettings": {
          "LUNs": "0",
          "DefaultFilePath": "E:\\SQLData"
        },
        "SQLLogSettings": {
          "LUNs": "1",
          "DefaultFilePath": "F:\\SQLLog"
        },
        "SQLTempDbSettings": {
          "DefaultFilePath": "D:\\TempDB"
        }
      }

```

be great to get these into the resource

**Comment by valentin-stefan-popa** [comment]
Any advice how to implement these:
"StorageConfigurationSettings": {
        "DiskConfigurationType": "NEW",
        "StorageWorkloadType": "OLTP",
        "SQLDataSettings": {
          "LUNs": "0",
          "DefaultFilePath": "E:\\SQLData"
        },
        "SQLLogSettings": {
          "LUNs": "1",
          "DefaultFilePath": "F:\\SQLLog"
        },
        "SQLTempDbSettings": {
          "DefaultFilePath": "D:\\TempDB"
        }
      }
or any hack to attach disks?

**Comment by a30000931** [comment]
@valentin-stefan-popa  the PR raised by @mbfrahry  is the correct 'terraform' solution to this issue.
you could do same in ARM or help out with the testing..the PR looks pretty complete
