### ISSUE TITLE
Can not create azurerm_virtual_machine with azurerm_managed_disk

### ISSUE THREAD

**Issue by CharlKlein** [terraform-providers/terraform-provider-azurerm#6877]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version 
Terraform v0.12.24
+ provider.azurerm v2.9.0
+ provider.template v2.1.2

### Affected Resource(s)

* `azurerm_virtual_machine`
* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
## Data Sources
data "azurerm_disk_encryption_set" "az_encryptionset" {
  name                = var.DISK_ENCRYPTION_SET_NAME
  resource_group_name = var.DES_RESOURCE_GROUP
}

data "azurerm_platform_image" "rhel_image" {
  location  = "southafricanorth"
  publisher = "Redhat"
  offer     = "RHEL"
  sku       = "7-RAW-CI"
}


## Disk
resource "azurerm_managed_disk" "encrypted_disk" {
  count = var.VM_COUNT

  name                 = format("%s%d-datadisk0", var.VM_NAME, count.index)
  resource_group_name  = "myrg"
  storage_account_type = "Standard_LRS"
  create_option        = "FromImage"
  disk_size_gb         = 100

  location               = data.azurerm_resource_group.myrg.location
  image_reference_id     = data.azurerm_platform_image.rhel_image.id
  disk_encryption_set_id = data.azurerm_disk_encryption_set.az_encryptionset.id
}

## Vm
resource "azurerm_virtual_machine" "vm" {
  count = var.VM_COUNT

  name                             = format("%s%d", var.AZ_VM_NAME, count.index)
  location                         = "southafricanorth"
  resource_group_name              =  "myrg"
  network_interface_ids            = [element(azurerm_network_interface.net_interface.*.id, count.index)]
  vm_size                          = "Standard_B1ms"
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true
  tags = var.AZ_TAGS

  storage_os_disk {
    name            = format("%s%d-vm-datadisk0", var.VM_NAME, count.index)
    create_option   = "Attach"
    managed_disk_id = element(azurerm_managed_disk.encrypted_disk.*.id, count.index)
  }

  os_profile {
    computer_name  = format("%s%d", var.VM_NAME, count.index)
    admin_username = var.VM_USERNAME
    custom_data    = data.template_cloudinit_config.config.rendered
  }

  os_profile_linux_config {
    disable_password_authentication = true

    ssh_keys {
      ...... Removed ......
    }
  }

  depends_on = [
    azurerm_managed_disk.encrypted_disk
  ]
}

```

### Expected Behavior

Virtual Machine is created using a encrypted managed disk as the OS disk.

### Actual Behavior
Terraform apply errors out with:  
Code="InvalidParameter" Message="Required parameter 'osDisk.osType' is missing (null)." Target="osDisk.osType"

When **os_type** is included inside the **storage_os_disk** block
Code="InvalidParameter" Message="Parameter 'osProfile' is not allowed." Target="osProfile"

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### References

* #1364 (Possibly)

**Comment by tombuildsstuff** [comment]
hi @CharlKlein 

Thanks for opening this issue.

When attaching an existing OS disk to a Virtual Machine - Azure requires that no "OS Profile" block is specified (which maps to the `os_profile` block in Terraform - since the information within this block will be taken from the existing OS Disk instead.

It's worth noting that the older `azurerm_virtual_machine` resource has been superseded by the `azurerm_linux_virtual_machine` resource which has native support for Disk Encryption Sets (including rolling these keys) - whereas the older resources don't account for this functionality - as such you may wish to consider using this new resource instead.

Since this should be fixed by removing the `os_profile` block when attaching an existing OS Disk - I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by CharlKlein** [comment]
Great Thanks @tombuildsstuff 

There is a Capability that I am using with the os_profile block - the Custom Data to provide the Vm with a cloud Init script.
