### ISSUE TITLE
PublicIPAddressCannotBeDeleted / InUseSubnetCannotBeDeleted Issue

### ISSUE THREAD

**Issue by hmarcelodn** [terraform-providers/terraform-provider-azurerm#688]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.11.2

### Affected Resource(s)
- azurerm_subnet
- azurerm_public_ip

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
################################################################################################
###                     Configuration Section Azure - Terraform                              ###
################################################################################################
# Subscriptions
variable "subscription_id"                     { }
variable "client_id"                           { }
variable "client_secret"                       { }
variable "tenant_id"                           { }

# Resource Group Iaas
variable "resource_group_name_iaas"            { }
variable "resource_group_location_iaas"        { }

# Resource Group Paas
variable "resource_group_name_paas"            { }
variable "resource_group_location_paas"        { }

# VNET IAAS
variable "portal_vNet_iaas"                    { }
variable "vnet_iaas_address_space"             { }
variable "vnet_iaas_network_location"          { }
variable "vnet_iaas_address_masters_prefix"    { }
variable "vnet_iaas_subnet_masters_name"       { }
variable "vnet_iaas_address_nodes_prefix"      { }
variable "vnet_iaas_subnet_nodes_name"         { }
variable "vnet_iaas_address_gateway_prefix"    { }

# VNET PAAS
variable "vnet_paas_name"                      { }
variable "vnet_paas_address_space"             { }
variable "vnet_paas_network_location"          { }
variable "vnet_paas_subnet_api_address_prefix" { }
variable "vnet_paas_subnet_api_address_name"   { }

# Public IP
variable "public_ip_name"                      { }
variable "public_ip_location_name"             { }
variable "public_ip_address_allocation"        { }

# Tags
variable "environment_tag"                     { }

# Local Network Gateway
variable "lgw_name"                            { }
variable "lgw_gateway_address"                 { }
variable "lgw_address_space"                   { type = "list" }

# Virtual Network Gateway
variable "arm_template_name"                   { }
variable "arm_template_path"                   { }
variable "gateway_name"                        { }
variable "gateway_sku"                         { }
variable "vpn_type"                            { }
variable "connection_name"                     { }
variable "shared_key"                          { }
variable "route_based_create"                  { }

# Redis
variable "cache_name"                          { }
variable "cache_capacity"                      { }
variable "cache_family"                        { }
variable "sku_name"                            { }
variable "enable_non_ssl_port"                 { }
variable "create_redis_cache"                  { }

# SQL Server Instance
variable "instance_name"                       { }
variable "sql_version"                         { }
variable "administrator_login"                 { }
variable "administrator_login_password"        { }
variable "sql_databases"                       { type = "list" }
variable "sql_instance_location"               { }

# Storage Accounts
variable "productores_account_name"             { }
variable "productores_account_replication_type" { }
variable "productores_account_tier"             { }
variable "productores_container_name"           { }
variable "productores_container_type"           { }

# Service Farm
variable "app_service_plan_name"                { }
variable "app_service_locations"                { type = "list" }
variable "app_service_prefix"                   { }
variable "sku_tier"                             { }
variable "sku_size"                             { }
variable "traffic_name"                         { }
variable "create_traffic"                       { }

# DocumentDB
variable "cosmosdb_account_name"                { }
variable "cosmosdb_offer_type"                  { }
variable "cosmosdb_consistency_level"           { }
variable "cosmosdb_failover_locations"          { }
variable "cosmosdb_ip_range_filter"             { }

# CosmosDB
variable "create_cosmosdb"                      { }

# Express Route
variable "express_route_create"                 { }
variable "express_route_circuit_id"             { }
variable "express_route_shared_key"             { }
                          

# Automation subscription
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}

 # Remote State Management (Blob-Storage)
terraform {
   backend "azurerm" {
     storage_account_name = "#{backend_storage_account}#" #backend_storage_account - edgeterraform
     container_name       = "#{backend_container_name}#" #backend_container_name - tfstate
     key                  = "#{backend_key}#" #backend_key - staging.eastus.infrastructure.terraform.tfstate
     access_key           = "#{backend_access_key}#" #backend_access_key
   }
}

# Resource Groups

module "resource_group_iaas" {
    source                  = "../../modules/resource-group"
    resource_group_name     = "${var.resource_group_name_iaas}"
    resource_group_location = "${var.resource_group_location_iaas}"
}

module "resource_group_paas" {
    source                  = "../../modules/resource-group"
    resource_group_name     = "${var.resource_group_name_paas}"
    resource_group_location = "${var.resource_group_location_paas}"
}

# Virtual Net Iaas

resource "azurerm_virtual_network" "default_iaas" {
  name                = "${var.portal_vNet_iaas}"
  resource_group_name = "${module.resource_group_iaas.resource_group_name}"
  address_space       = ["${var.vnet_iaas_address_space}"]
  location            = "${var.vnet_iaas_network_location}"

  tags {
    environment = "${var.environment_tag}"
  }  
}

resource "azurerm_subnet" "default_masters" {
    name                 = "${var.vnet_iaas_subnet_masters_name}"
    resource_group_name  = "${module.resource_group_iaas.resource_group_name}"
    virtual_network_name = "${var.portal_vNet_iaas}"
    address_prefix       = "${var.vnet_iaas_address_masters_prefix}"

    depends_on = ["azurerm_virtual_network.default_iaas"]
    lifecycle {
        ignore_changes = ["route_table_id"]
    }
}

resource "azurerm_subnet" "default_nodes" {
    name                 = "${var.vnet_iaas_subnet_nodes_name}"
    resource_group_name  = "${module.resource_group_iaas.resource_group_name}"
    virtual_network_name = "${var.portal_vNet_iaas}"
    address_prefix       = "${var.vnet_iaas_address_nodes_prefix}"

    depends_on = ["azurerm_virtual_network.default_iaas"]
    lifecycle {
        ignore_changes = ["route_table_id"]
    }    
}

resource "azurerm_subnet" "default_gateway" {
    name                 = "GatewaySubnet"
    resource_group_name  = "${module.resource_group_iaas.resource_group_name}"
    virtual_network_name = "${var.portal_vNet_iaas}"
    address_prefix       = "${var.vnet_iaas_address_gateway_prefix}"

    depends_on = ["azurerm_virtual_network.default_iaas"]
    lifecycle {
        ignore_changes = ["route_table_id"]
    }    
}

# Virtual Net Paas

resource "azurerm_virtual_network" "default_paas" {
  name                = "${var.vnet_paas_name}"
  resource_group_name = "${module.resource_group_paas.resource_group_name}"
  address_space       = ["${var.vnet_paas_address_space}"]
  location            = "${var.vnet_paas_network_location}"

  tags {
    environment = "${var.environment_tag}"
  }  
}


# VNET Peering Iaas to API Gateway

resource "azurerm_virtual_network_peering" "iaas" {
  name                         = "iaasToApi"
  resource_group_name          = "${module.resource_group_iaas.resource_group_name}"
  virtual_network_name         = "${azurerm_virtual_network.default_iaas.name}"
  remote_virtual_network_id    = "${azurerm_virtual_network.default_paas.id}"
  allow_virtual_network_access = true
  allow_forwarded_traffic      = true

  depends_on = [
    "azurerm_virtual_network.default_iaas",
    "azurerm_virtual_network.default_paas"
  ]
}

resource "azurerm_virtual_network_peering" "api" {
  name                          = "apiToIaas"
  resource_group_name          = "${module.resource_group_paas.resource_group_name}"
  virtual_network_name         = "${azurerm_virtual_network.default_paas.name}"
  remote_virtual_network_id    = "${azurerm_virtual_network.default_iaas.id}"
  allow_virtual_network_access = true
  allow_forwarded_traffic      = true

  depends_on = [
    "azurerm_virtual_network.default_iaas",
    "azurerm_virtual_network.default_paas"
  ]  
}

# API Gateway Subnet

module "api_gateway_subnet" {
    source                   = "../../modules/subnet"
    virtual_network_name     = "${azurerm_virtual_network.default_paas.name}"
    resource_group_name      = "${module.resource_group_paas.resource_group_name}"
    address_prefix           = "${var.vnet_paas_subnet_api_address_prefix}"
    subnet_name              = "${var.vnet_paas_subnet_api_address_name}"
}

# Public IP

module "iaas_public_ip" {
  source                       = "../../modules/public-ip"
  public_ip_name               = "${var.public_ip_name}"
  location_name                = "${var.public_ip_location_name}"
  azurerm_resource_group_name  = "${module.resource_group_iaas.resource_group_name}"
  environment                  = "${var.environment_tag}"
  public_ip_address_allocation = "${var.public_ip_address_allocation}"
}

# Local Network Gateway

module "iaas_local_network_gw" {
  route_based_create         = "${var.route_based_create}"
  source                     = "../../modules/local-network-gw"
  local_network_gateway_name = "${var.lgw_name}"
  resource_group_name        = "${module.resource_group_iaas.resource_group_name}"
  resource_group_location    = "${module.resource_group_iaas.resource_group_location}"
  gateway_address            = "${var.lgw_gateway_address}"
  address_space              = "${var.lgw_address_space}"
  depends_on                 = "${module.iaas_public_ip.iass_public_ip_name}"
}

# Deploy ARM / Virtual Network Gateway / Connection (VNET - Virtual Local Gateway)

resource "azurerm_template_deployment" "default" {
  count               = "${var.route_based_create}"
  name                = "${var.arm_template_name}"
  resource_group_name = "${module.resource_group_iaas.resource_group_name}"

  template_body = "${file("./virtualNetworkGatewayARM.json")}"

  parameters {
    "gatewayPublicIPName" = "${module.iaas_public_ip.iass_public_ip_name}"
    "virtualNetworkName"  = "${azurerm_virtual_network.default_iaas.name}"
    "gatewayName"         = "${var.gateway_name}" 
    "gatewaySku"          = "${var.gateway_sku}"
    "vpnType"             = "${var.vpn_type}"
    "gatewaySubnet"       = "GatewaySubnet"
    "connectionName"      = "${var.connection_name}"
    "localGatewayName"    = "${module.iaas_local_network_gw.name[0]}"
    "sharedKey"           = "${var.shared_key}"
  }

  deployment_mode = "Incremental"

  depends_on = [
    "azurerm_virtual_network.default_iaas",
    "azurerm_virtual_network.default_paas"
  ]    
}

# Deploy ARM / Express Route MPLS / Connection (VNET - Virtual Local Gateway)

resource "azurerm_template_deployment" "default_express_route" {
  count               = "${var.express_route_create}"
  name                = "express_route_template"
  resource_group_name = "${module.resource_group_iaas.resource_group_name}"

  template_body = "${file("./expressRouteARM.json")}"

  parameters {
    "gatewayPublicIPName" = "${module.iaas_public_ip.iass_public_ip_name}"
    "virtualNetworkName"  = "${azurerm_virtual_network.default_iaas.name}"
    "gatewayName"         = "iaas-on-prem" 
    "gatewaySku"          = "Standard"
    "vpnType"             = "PolicyBased"
    "gatewaySubnet"       = "GatewaySubnet"
    "connectionName"      = "iaas-on-prem-connection"
    "sharedKey"           = "${var.express_route_shared_key}"
    "circuitId"           = "${var.express_route_circuit_id}"
  }

  deployment_mode = "Incremental"

  depends_on = [
    "azurerm_virtual_network.default_iaas",
    "azurerm_virtual_network.default_paas"
  ]    
}

# Paas Services

# Redis

module "paas_cache" {
  source                  = "../../modules/redis"
  cache_name              = "${var.cache_name}"
  resource_group_location = "${module.resource_group_paas.resource_group_location}"
  resource_group_name     = "${module.resource_group_paas.resource_group_name}"
  cache_capacity          = "${var.cache_capacity}"
  cache_family            = "${var.cache_family}"
  sku_name                = "${var.sku_name}"
  enable_non_ssl_port     = "${var.enable_non_ssl_port}" 
  create_redis_cache      = "${var.create_redis_cache}"
}

# SQL Server Instance

module "paas_sql_server_instance" {
  source                       = "../../modules/sql-server"
  name                         = "${var.instance_name}"
  resource_group_name          = "${module.resource_group_paas.resource_group_name}"
  resource_group_location      = "${var.sql_instance_location}"
  sql_version                  = "${var.sql_version}"
  administrator_login          = "${var.administrator_login}"
  administrator_login_password = "${var.administrator_login_password}"
  environment                  = "${var.environment_tag}"
  databases                    = "${var.sql_databases}"
}

# Storage Accounts

module "account_images" {
    source                   = "../../modules/productores-account"    
    resource_group           = "${module.resource_group_paas.resource_group_name}"
    resource_group_location  = "${module.resource_group_paas.resource_group_location}"
    environment              = "${var.environment_tag}"
    account_name             = "${var.productores_account_name}"
    account_replication_type = "${var.productores_account_replication_type}"
    account_tier             = "${var.productores_account_tier}"
    container_name           = "${var.productores_container_name}"
    container_type           = "${var.productores_container_type}"
}

# App Service Farm

module "productores_farm" {
  source                  = "../../modules/app-services-farm"
  app_service_plan_name   = "${var.app_service_plan_name}"
  locations               = "${var.app_service_locations}"
  app_service_prefix      = "${var.app_service_prefix}"
  resource_group_name     = "${module.resource_group_paas.resource_group_name}"
  resource_group_location = "${module.resource_group_paas.resource_group_location}"
  sku_tier                = "${var.sku_tier}"
  sku_size                = "${var.sku_size}"
  traffic_name            = "${var.traffic_name}"
  environment             = "${var.environment_tag}"
  create_traffic          = "${var.create_traffic}"
}

# DocumentDB

resource "azurerm_cosmosdb_account" "default" {
  count               = "${var.create_cosmosdb}"
  name                = "${var.cosmosdb_account_name}"
  location            = "${module.resource_group_paas.resource_group_location}"
  resource_group_name = "${module.resource_group_paas.resource_group_name}"
  offer_type          = "${var.cosmosdb_offer_type}"
  consistency_policy {
    consistency_level = "${var.cosmosdb_consistency_level}"
  }

  failover_policy {
    location = "${var.cosmosdb_failover_locations}"
    priority = "${count.index}"
  }

  tags {
    Environment = "${var.environment_tag}"
  }

  ip_range_filter = "${var.cosmosdb_ip_range_filter}"
}

```

### Debug Output

> 2018-01-12T10:24:49.4823368Z ##[section]Starting: Run terraform destroy
> 2018-01-12T10:24:49.4881808Z ==============================================================================
> 2018-01-12T10:24:49.4893403Z Task         : Command Line
> 2018-01-12T10:24:49.4905444Z Description  : Run a command line with arguments
> 2018-01-12T10:24:49.4917198Z Version      : 1.1.3
> 2018-01-12T10:24:49.4928655Z Author       : Microsoft Corporation
> 2018-01-12T10:24:49.4940405Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
> 2018-01-12T10:24:49.4952967Z ==============================================================================
> 2018-01-12T10:24:49.7610985Z [command]/usr/local/bin/terraform destroy -force -var-file=vars.development.tfvars
> 2018-01-12T10:24:52.3386239Z [0m[1mazurerm_resource_group.default: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...08f/resourceGroups/portal-cluster-paas)[0m
> 2018-01-12T10:24:52.3405896Z [0m[1mazurerm_resource_group.default: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...08f/resourceGroups/portal-cluster-iaas)[0m
> 2018-01-12T10:24:52.3957846Z [0m[1mazurerm_virtual_network.default_paas: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...irtualNetworks/portal-vNet-api-gateway)[0m
> 2018-01-12T10:24:52.4147919Z [0m[1mazurerm_virtual_network.default_iaas: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...twork/virtualNetworks/portal-vNet-iaas)[0m
> 2018-01-12T10:24:52.4305221Z [0m[1mazurerm_public_ip.default: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...twork/publicIPAddresses/iaas-public-ip)[0m
> 2018-01-12T10:24:52.4361349Z [0m[1mazurerm_subnet.default: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...api-gateway/subnets/api-gateway-subnet)[0m
> 2018-01-12T10:24:52.4686237Z [0m[1mazurerm_subnet.default_masters: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...Net-iaas/subnets/portal-masters-subnet)[0m
> 2018-01-12T10:24:52.4701223Z [0m[1mazurerm_subnet.default_gateway: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...portal-vNet-iaas/subnets/GatewaySubnet)[0m
> 2018-01-12T10:24:52.4718070Z [0m[1mazurerm_subnet.default_nodes: Refreshing state... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...-vNet-iaas/subnets/portal-nodes-subnet)[0m
> 2018-01-12T10:24:54.3977820Z [0m[1mazurerm_subnet.default_masters: Destroying... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...Net-iaas/subnets/portal-masters-subnet)[0m[0m
> 2018-01-12T10:24:54.3992425Z [0m[1mazurerm_subnet.default_gateway: Destroying... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...portal-vNet-iaas/subnets/GatewaySubnet)[0m[0m
> 2018-01-12T10:24:54.4006632Z [0m[1mmodule.iaas_public_ip.azurerm_public_ip.default: Destroying... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...twork/publicIPAddresses/iaas-public-ip)[0m[0m
> 2018-01-12T10:24:54.4028467Z [0m[1mazurerm_subnet.default_nodes: Destroying... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...-vNet-iaas/subnets/portal-nodes-subnet)[0m[0m
> 2018-01-12T10:24:54.4113881Z [0m[1mmodule.api_gateway_subnet.azurerm_subnet.default: Destroying... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...api-gateway/subnets/api-gateway-subnet)[0m[0m
> 2018-01-12T10:24:54.4127784Z [0m[1mazurerm_virtual_network.default_paas: Destroying... (ID: /subscriptions/fe2c20a9-d4c7-4eaa-919c-...irtualNetworks/portal-vNet-api-gateway)[0m[0m
> 2018-01-12T10:24:54.6801625Z [31m
> 2018-01-12T10:24:54.6829429Z [1m[31mError: [0m[0m[1mError applying plan:
> 2018-01-12T10:24:54.6851239Z 
> 2018-01-12T10:24:54.6892922Z 6 error(s) occurred:
> 2018-01-12T10:24:54.6978327Z 
> 2018-01-12T10:24:54.6989380Z * module.iaas_public_ip.azurerm_public_ip.default (destroy): 1 error(s) occurred:
> 2018-01-12T10:24:54.6995457Z 
> 2018-01-12T10:24:54.7008729Z * azurerm_public_ip.default: network.PublicIPAddressesClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/resourceGroups/portal-cluster-iaas/providers/Microsoft.Network/publicIPAddresses/iaas-public-ip can not be deleted since it is still allocated to resource /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/resourceGroups/portal-cluster-iaas/providers/Microsoft.Network/virtualNetworkGateways/iaas-on-prem/ipConfigurations/vnetGatewayConfig." Details=[]
> 2018-01-12T10:24:54.7021657Z * module.api_gateway_subnet.azurerm_subnet.default (destroy): 1 error(s) occurred:
> 2018-01-12T10:24:54.7027630Z 
> 2018-01-12T10:24:54.7040127Z * azurerm_subnet.default: network.SubnetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet api-gateway-subnet is in use by /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/providers/Microsoft.ApiManagement/service?vnetResourceGuid=40f8f9e2-b894-4b17-afca-c4891b647dab&subnet=api-gateway-subnet&api-version=2016-07-07 and cannot be deleted." Details=[]
> 2018-01-12T10:24:54.7052697Z * azurerm_subnet.default_nodes (destroy): 1 error(s) occurred:
> 2018-01-12T10:24:54.7081507Z 
> 2018-01-12T10:24:54.7101822Z * azurerm_subnet.default_nodes: network.SubnetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet portal-nodes-subnet is in use by /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/resourceGroups/portal-cluster-iaas/providers/Microsoft.Network/networkInterfaces/k8s-agentpool1-40880974-nic-0/ipConfigurations/ipconfig1 and cannot be deleted." Details=[]
> 2018-01-12T10:24:54.7114277Z * azurerm_virtual_network.default_paas (destroy): 1 error(s) occurred:
> 2018-01-12T10:24:54.7119994Z 
> 2018-01-12T10:24:54.7132671Z * azurerm_virtual_network.default_paas: network.VirtualNetworksClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet api-gateway-subnet is in use by /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/providers/Microsoft.ApiManagement/service?vnetResourceGuid=40f8f9e2-b894-4b17-afca-c4891b647dab&subnet=api-gateway-subnet&api-version=2016-07-07 and cannot be deleted." Details=[]
> 2018-01-12T10:24:54.7145539Z * azurerm_subnet.default_gateway (destroy): 1 error(s) occurred:
> 2018-01-12T10:24:54.7151565Z 
> 2018-01-12T10:24:54.7164368Z * azurerm_subnet.default_gateway: network.SubnetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet GatewaySubnet is in use by /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/resourceGroups/portal-cluster-iaas/providers/Microsoft.Network/virtualNetworkGateways/iaas-on-prem/ipConfigurations/vnetGatewayConfig and cannot be deleted." Details=[]
> 2018-01-12T10:24:54.7176918Z * azurerm_subnet.default_masters (destroy): 1 error(s) occurred:
> 2018-01-12T10:24:54.7182050Z 
> 2018-01-12T10:24:54.7194870Z * azurerm_subnet.default_masters: network.SubnetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InUseSubnetCannotBeDeleted" Message="Subnet portal-masters-subnet is in use by /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/resourceGroups/portal-cluster-iaas/providers/Microsoft.Network/networkInterfaces/k8s-master-40880974-nic-0/ipConfigurations/ipconfig1 and cannot be deleted." Details=[]
> 2018-01-12T10:24:54.7201831Z 
> 2018-01-12T10:24:54.7214420Z Terraform does not automatically rollback in the face of errors.
> 2018-01-12T10:24:54.7230801Z Instead, your Terraform state file has been partially updated with
> 2018-01-12T10:24:54.7246546Z any resources that successfully completed. Please address the error
> 2018-01-12T10:24:54.7258836Z above and apply again to incrementally change your infrastructure.[0m
> 2018-01-12T10:24:54.7265047Z 
> 2018-01-12T10:24:54.7276419Z [0m[0m[0m
> 2018-01-12T10:24:54.7376099Z ##[error]/usr/local/bin/terraform failed with return code: 1
> 2018-01-12T10:24:54.7410904Z ##[error]/usr/local/bin/terraform failed with error: /usr/local/bin/terraform failed with return code: 1
> 2018-01-12T10:24:54.7777281Z ##[section]Finishing: Run terraform destroy

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Destroy completes successfully.

### Actual Behavior
I tried 2 things:

- Remove all resource groups manually then clean the terraform state by running destroy command.
- Running terraform destroy without remove anything manually.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2.  `terraform destroy`

### Important Factoids
All running with resource manager.
My first part of the execution is by terraform to provision some resources. The second part is provisioning a Kuberntes cluster with ARM which creates some virtual machines. I removed the resource groups with the VMs previously to running destroy.

**Comment by pixelicous** [comment]
I face the same problem, i have a NSG on a subnet in a vnet.
I want to rename the name of the NSG
terraform cannot detach the NSG, rename it and then attach it back

**Comment by tombuildsstuff** [comment]
hi @hmarcelodn 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look at the error message you're seeing:

> Public IP address /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/resourceGroups/portal-cluster-iaas/providers/Microsoft.Network/publicIPAddresses/iaas-public-ip can not be deleted since it is still allocated to resource /subscriptions/748dd48c-c39d-4005-9bd7-969ace19089c/resourceGroups/portal-cluster-iaas/providers/Microsoft.Network/virtualNetworkGateways/iaas-on-prem/ipConfigurations/vnetGatewayConfig

This was related to a bug within the Virtual Network Gateway API within Azure where the Virtual Network Gateway API would return that it'd deleted a Virtual Network Gateway, but actually it was still in the process of being deleted. For this reason we only recently (~January) added support for Virtual Network Gateway's natively to Terraform - and as such I can confirm that this bug is now fixed, and as such I'm going to close this issue.

---

@pixelicous 

> I face the same problem, i have a NSG on a subnet in a vnet.
> I want to rename the name of the NSG
> terraform cannot detach the NSG, rename it and then attach it back

In this case you'd need to use a multi-step operation to detach the Network Security Group from the subnet, taint/recreate the Network Security Group with the new name and then reattach it. Given the Network Security Group is a separate resource and can be connected to multiple things (Subnets, NIC's, VM's etc) - unfortunately this isn't something I think we'll be able to support in the near-term; as such I'm going to close this issue for the moment. That said - I think it should be possible to rename a Network Security Group without requiring recreating it in the API - so I'd suggest opening an API Enhancement on [the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs/issues).

Thanks!
