### ISSUE TITLE
Can't Seem to Create a Linux Function App

### ISSUE THREAD

**Issue by CodingAnarchy** [terraform-providers/terraform-provider-azurerm#6882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.7.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Creates an Azure Function App with a Linux backend.

### Actual Behavior

Function app is created but attempts to upload the function produce the following error:

```
Python projects are not supported on Windows Function Apps. Deploy to a Linux Function App instead.
```

The function app appears to be set up to use Windows despite the language being set to Python and the `os_type` to `"linux"`.

Subsequent plans all recreate the function app based on the change in the `os_type` variable, but the OS is never set to Linux in the created resource.

### Steps to Reproduce

With TF resources laid out like:

```terraform
resource "azurerm_app_service_plan" "function-app" {
  name = "functions"
  location = azurerm_resource_group.foobar.location
  resource_group_name = azurerm_resource_group.foobar.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_function_app" "foo-function" {
  name = "foo-function"
  location = azurerm_resource_group.foobar.location
  resource_group_name = azurerm_resource_group.foobar.name
  app_service_plan_id = azurerm_app_service_plan.function-app.id
  storage_account_name = azurerm_storage_account.my-storage.name
  storage_account_access_key = azurerm_storage_account.my-storage.primary_access_key
  os_type = "linux"
  version = "~3"
  https_only = "true"

  app_settings = {
    FUNCTIONS_WORKER_RUNTIME = "python"
    FUNCTIONS_WORKER_PROCESS_COUNT = 10
  }

  site_config {
    use_32_bit_worker_process = false
    websockets_enabled = false
  }
}
```

1. `terraform apply`

I also tried setting `linux_fx_version` in the `site_config` block, but no matter what I put there (including the `DOCKER|(golang:latest)` in the documentation) I got an error saying it was invalid:

```
Error: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter LinuxFxVersion has an invalid value." Details=[{"Message":"The parameter LinuxFxVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The parameter LinuxFxVersion has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["LinuxFxVersion"]}}]
```

**Comment by viswanathanb** [comment]
Try `kind                = "Linux"` and `reserved            = true` in your app service plan for linux.

**Comment by CodingAnarchy** [comment]
@viswanathanb Looks like that solved my problem. Thanks for the help!
