### ISSUE TITLE
Managed Postgres public_network_access_enabled not working?

### ISSUE THREAD

**Issue by atrauzzi** [terraform-providers/terraform-provider-azurerm#6883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 - `v0.12.24`
 - `2.9.0`

### Affected Resource(s)

 - `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_server" "MINE" {
  name = "${var.project}-${var.environment}-MINE"
  location = azurerm_resource_group.environment.location
  resource_group_name = azurerm_resource_group.environment.name

  sku_name = "B_Gen5_1"
  version = "11"
  ssl_enforcement_enabled = true
  public_network_access_enabled = true

  administrator_login = var.genericUsername
  administrator_login_password = var.genericPassword

  storage_profile {
    storage_mb = 5120
    backup_retention_days = 14
    geo_redundant_backup = "Disabled"
    auto_grow = "Disabled"
  }

  tags = {
    orchestrator = "terraform"
    project = var.project
    environment = var.environment
    version = var.deploymentVersion
  }
}
```
### Expected Behavior

![image](https://user-images.githubusercontent.com/115199/81743178-e4894d80-9466-11ea-8e4c-736224beb67a.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/115199/81743207-f0750f80-9466-11ea-8ec7-989b013190d4.png)

### Steps to Reproduce

Just try to deploy a managed postgres instance with `public_network_access_enabled` set to true.

### Important Factoids

Not that I'm aware of.

**Comment by lrxtom2** [comment]
Hi @atrauzzi , Thanks for opening the issue. `public_network_access_enabled` means `Deny public network access` button in the portal. Please have check. 
![image](https://user-images.githubusercontent.com/20538091/82006785-2bf81f80-969b-11ea-9146-d9692378a9fe.png)

And you could refer [Postgresql Firewall Rule](https://www.terraform.io/docs/providers/azurerm/r/postgresql_firewall_rule.html) to create firewall rule in your resource. Thanks in advance.

**Comment by atrauzzi** [comment]
Thank you!  I assumed it would be an option on the resource itself rather than a rule, so I hadn't looked there.

For anyone arriving here in the future, there's a section in the link from @irxtom2:

**Comment by lrxtom2** [comment]
@atrauzzi Thanks for you!
