### ISSUE TITLE
azurerm_policy*_definition.management_group_* attribute inconsistency

### ISSUE THREAD

**Issue by mjiderhamn** [terraform-providers/terraform-provider-azurerm#6893]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azurerm v2.9.0
```

### Affected Resource(s)

* `azurerm_policy_definition`
* `azurerm_policy_set_definition`

### Expected Behavior

Consistency between `azurerm_policy_definition` and `azurerm_policy_set_definition` attributes.

### Actual Behavior

Since #6275 the `management_group_id` attribute of `azurerm_policy_definition` has been deprecated in favor of `management_group_name`. However for `azurerm_policy_set_definition` the `management_group_name` attribute isn't supported, and still requires the use of `management_group_id`.

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/pull/6275

**Comment by mjiderhamn** [comment]
Ping @ArcturusZhang

**Comment by ArcturusZhang** [comment]
Hi @mjiderhamn I will take some time to align the set definition with policy definition. Thanks!
