### ISSUE TITLE
azurerm_route_table - "next_hop_in_ip_address" is required

### ISSUE THREAD

**Issue by aberva** [terraform-providers/terraform-provider-azurerm#6898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_route_table

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

```
resource "azurerm_route_table" "RT_name01" {
  name                          = "nameroutetable"
  location                      = var.default-azure-region
  resource_group_name           = azurerm_resource_group.RG_nameresourcegroup01.name
  disable_bgp_route_propagation = false

  route =[
    {
      name = "xxxx"
      address_prefix = "xx.xx.xx.xxx/28"
      next_hop_type  = "VirtualAppliance"
      next_hop_in_ip_address = data.azurerm_lb.LB_loadbalancer01.private_ip_address
    },
    {
      name = "ASE-to-IPPublicRegion01"
      address_prefix = "13.64.115.203/32"
      next_hop_type  = "Internet"
    },
  ]
}
```

### Panic Output

**Inappropriate value for attribute "route": element 1: attribute
"next_hop_in_ip_address" is required.**

### Steps to Reproduce

1. `terraform apply`

### References

The documentation indicates that the "next_hop_in_ip_address" parameter is optional while at the output of terraform apply, it is indicated as required :

_next_hop_in_ip_address - (Optional) Contains the IP address packets should be forwarded to. Next hop values are only allowed in routes where the next hop type is VirtualAppliance._

https://www.terraform.io/docs/providers/azurerm/r/route_table.html#next_hop_in_ip_address

* #0000

**Comment by lrxtom2** [comment]
Hi @aberva , Thanks for opening the issue!
We don't suggest to write block with this style that use [Attributes as Blocks](https://www.terraform.io/docs/configuration/attr-as-blocks.html). We usually use this method to remove items. [Reference](https://www.terraform.io/docs/providers/azurerm/r/route_table.html#route)

So we suggest that you could use multiple `route` blocks in tf code like below.

```hcl
resource "azurerm_route_table" "RT_name01" {
  name                          = "nameroutetable"
  location                      = var.default-azure-region
  resource_group_name           = azurerm_resource_group.RG_nameresourcegroup01.name
  disable_bgp_route_propagation = false

  route {
      name = "xxxx"
      address_prefix = "xx.xx.xx.xxx/28"
      next_hop_type  = "VirtualAppliance"
      next_hop_in_ip_address = data.azurerm_lb.LB_loadbalancer01.private_ip_address
    }
  route {
      name = "ASE-to-IPPublicRegion01"
      address_prefix = "13.64.115.203/32"
      next_hop_type  = "Internet"
    }
}
```

Thanks for that.

**Comment by aberva** [comment]
Thanks lots @lrxtom2  !
