### ISSUE TITLE
Required virtual network service endpoint policies resource

### ISSUE THREAD

**Issue by inmishrar** [terraform-providers/terraform-provider-azurerm#6919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Virtual network service endpoint policy is something missing into the subnet, Possibly it should get added as a new resource of azurerm or we should introduce this property within the subnet so that it can be used. For more details about the requirement you can visit to the provided link in the references.

### New or Affected Resource(s)

* azurerm_subnet
* azurerm_virtual_network

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

*https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoint-policies-overview

**Comment by arpit-panchal** [comment]
Is this releasing part of v2.40.0? We are really eager for this feature release :)
