### ISSUE TITLE
azurerm_cosmosdb_mongo_collection errors when applying a Compound Index

### ISSUE THREAD

**Issue by Scudmeister** [terraform-providers/terraform-provider-azurerm#6924]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.21
provider.azurerm v2.7.0

### Affected Resource(s)

'

azurerm_cosmosdb_mongo_collection'

### Terraform Configuration Files

provider "azurerm" {
  version                    = "~> 2.7.0"
  features {}
  skip_provider_registration = true

  # Service Principal Details
  subscription_id       = "..."
  client_id             = "..."
  client_secret         = "..."
  tenant_id             = "..."
}

terraform {
  backend "azurerm" {
    resource_group_name  = "..."
    storage_account_name = "..."
    container_name       = "..."
    key                  = "..."
  }
}

resource "azurerm_cosmosdb_account" "cosmos-account" {
    name                = "my-cosmos-account")
    location            = "..."
    resource_group_name = "..."
    offer_type          = "Standard"
    kind                = "MongoDB"

    enable_automatic_failover = true

    capabilities {
        name = "EnableAggregationPipeline"
    }

    capabilities {
        name = "EnableMongo"
    }

    consistency_policy {
        consistency_level       = "BoundedStaleness"
        max_interval_in_seconds = 10
        max_staleness_prefix    = 200
    }

    geo_location {
        location          = "..."
        failover_priority = 0
    }
}

resource "azurerm_cosmosdb_mongo_database" "myDb" {
    name                = "timDb"
    resource_group_name = "..."
    account_name        = azurerm_cosmosdb_account.cosmos-account.name
}

resource "azurerm_cosmosdb_mongo_collection" "actions" {
    name                = "actions"
    resource_group_name = "..."
    account_name        = azurerm_cosmosdb_account.cosmos-account.name
    database_name       = azurerm_cosmosdb_mongo_database.myDb.name

    shard_key           = "_id"

    index              {keys = [ "audit.sender"]}
    index              {keys = [ "audit.status"]}
    index              {keys = [ "audit.timestamp"]}
    index              {keys = [ "id"]}
    index              {keys = [ "id", "action"]}

    throughput          = "20000"
}

### Expected Behavior

A compound index between "id" and "action" should of been created with the "actions" collection.

### Actual Behavior

Error: Error issuing create/update request for Cosmos Mongo Collection actions (Account my-cosmos-account, Database myDb): documentdb.DatabaseAccountsClient#CreateUpdateMongoDBCollection: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Unable to parse request payload due to the following reason: 'Compound Indexes are only supported for unique indexes. Instead create multiple single field indexes.'.\r\nActivityId: 381ccdec-5e9a-4ba4-9abf-9238bacd6529, Microsoft.Azure.Documents.Common/2.11.0"

  on main.tf line 57, in resource "azurerm_cosmosdb_mongo_collection" "actions":
  57: resource "azurerm_cosmosdb_mongo_collection" "actions" {

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`
3. `terraform plan -out="./plan.output`
4. `terraform apply "./plan.output"`

### Important Factoids

https://github.com/terraform-providers/terraform-provider-azurerm/issues/4460
Suggests that this was implemented or fixed for provider.azurerm v2.7.0

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I can repro this issue. Seems it must be unique key if you are using compound indexes. So you can add "unique = true" to create collection with compound indexes successfuly. See below sample code.

```
resource "azurerm_cosmosdb_mongo_collection" "test" {
  ......
  index {
    keys = [ "id", "action"]
    unique = true
  }
}
```

Related references:
https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing#unique-indexes

**Comment by ArcturusZhang** [comment]
Hi @Scudmeister 

This behaviour should be by-design of the API itself, you must explicitly set `unique=true` to make it work. Could you please have a try whether this works? For now I will close this issue if you do not mind. Please feel free to reopen or comment if you have further concerns or questions. Thank you!

**Comment by ArcturusZhang** [comment]
Hi @neil-yechenwei could you please take look at the order issue?

**Comment by ArcturusZhang** [comment]
Hi @cuizhanming after some consideration I believe this should be an irrelevant issue with this one, therefore I would still close this issue. But could you please open a new issue about this?
