### ISSUE TITLE
azurerm_application_gateway: Documentation Lacking for waf_configuration

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#6932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.9.0

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

waf_configuration.rule_set_type, a required parameter should list which types are valid input. The name suggests it is some kind of enumeration. It is forcing me to use the Googles to find out what I'm supposed to populate.

### Actual Behavior

waf_configuration.rule_set_type, a required parameter does not give accepted types or denotes it is a free text. Name and current documentation text suggests an enumeration is needed.

### Steps to Reproduce

1. Go [here](https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#rule_set_type)

### Important Factoids

N/A

### References

[https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#rule_set_type](https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#rule_set_type)

**Comment by bcline760** [comment]
https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-crs-rulegroups-rules?tabs=owasp31

Am I supposed to put in OWASP for that field?

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems it currently supports Microsoft_BotManagerRuleSet and OWASP. I'll submit a fix.

To get rule set type and version by cmd:
https://docs.microsoft.com/en-us/powershell/module/Az.Network/Get-AzApplicationGatewayAvailableWafRuleSet?view=azps-3.8.0
