### ISSUE TITLE
azurerm_function_app_slot - An argument named "storage_connection_string" is not expected here.

### ISSUE THREAD

**Issue by vpetersen** [terraform-providers/terraform-provider-azurerm#6933]
You can close this, the documentation was updated after I reported this.

**Comment by njuCZ** [comment]
@vpetersen thanks for pointing this issue. Since we have updated the doc, we will close this issue.

**Comment by aristosvo** [comment]
@njuCZ Did you also update the Slot resource, https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/function_app_slot.html.markdown? I can't find it, I think it's currently only in `azurerm_function_app`

**Comment by vpetersen** [comment]
You're correct they need to fix the slot documentation.
