### ISSUE TITLE
Unable to use tls_self_signed_cert with Azure Key Vault

### ISSUE THREAD

**Issue by atrauzzi** [terraform-providers/terraform-provider-azurerm#6937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 - `v0.12.24`
 - `2.9.0`

### Affected Resource(s)

`azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl

resource "tls_private_key" "environment" {
  algorithm = "RSA"
  rsa_bits = 2048
}

resource "tls_self_signed_cert" "environment" {
  key_algorithm = "RSA"
  private_key_pem = tls_private_key.environment.private_key_pem

  validity_period_hours = 12

  early_renewal_hours = 3

  set_subject_key_id = true

  allowed_uses = [
      "key_encipherment",
      "digital_signature",
      "server_auth",
  ]

  subject {
      common_name = "*.mydomain.com"
      organization = "DevOps"
  }
}

resource "azurerm_key_vault_certificate" "environment" {
  name = "my-certificate"
  key_vault_id = azurerm_key_vault.environment.id

  lifecycle {
    ignore_changes = all
  }

  certificate {
    contents = base64encode(tls_self_signed_cert.environment.cert_pem)
    password = ""
  }

  certificate_policy {

    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size = 2048
      key_type = "RSA"
      reuse_key = true
    }

    secret_properties {
      content_type = "application/x-pem-file"
    }
  }
```

### Expected Behavior

I get a new certificate with an initial version of my self signed certificate.

### Actual Behavior

I receive the following error:

```
Error: keyvault.BaseClient#ImportCertificate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Private key is not specified in the specified X.509 PEM certificate content. Please specify private key in the X.509 PEM certificate content."
```

### Steps to Reproduce
Try to use any Terraform-generated certificate.

### Important Factoids
None that I'm aware of.

**Comment by njuCZ** [comment]
duplicate as #3017

**Comment by mybayern1974** [comment]
@atrauzzi , would you please subscribe the dup issue and we close this issue? Or feel free to reopen this if you believe these two issues are not talking about the same thing. Thank you.

**Comment by atrauzzi** [comment]
I don't know, the example in that issue seems more involved than what I have as an example here.
