### ISSUE TITLE
New Data Source: Azure DNS Zone

### ISSUE THREAD

**Issue by kmcquade** [terraform-providers/terraform-provider-azurerm#694]
### Affected Resource(s)
- Azure DNS Zones

The Azure equivalent of this:
https://www.terraform.io/docs/providers/aws/d/route53_zone.html

### Desired Data
The data available in the API.
https://docs.microsoft.com/en-us/rest/api/dns/recordsets/get

**Comment by tombuildsstuff** [comment]
hey @kmcquade

Thanks for opening this issue - I've opened #702 which adds support for a new `azurerm_dns_zone` data source which should go out in the next release of the Azure provider.

Thanks!
