### ISSUE TITLE
azurerm_api_management_api_version_set should be accepted the name such as 'v1'

### ISSUE THREAD

**Issue by nanahoshi** [terraform-providers/terraform-provider-azurerm#6944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.20
- provider.azurerm v1.44.0

### Affected Resource(s)

* `azurerm_api_management_api_version_set `

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api_version_set" "external-api" {
  name= "v1"
  resource_group_name = azurerm_resource_group.frontend-apim-rg.name
  api_management_name = azurerm_api_management.api-management.name
  display_name= "v1"
  versioning_scheme   = "Segment"
  version_query_name = "v1"
}
```

### Expected Behavior

It should be accepted by terraform validation and we can apply it.

### Actual Behavior

```bash
Error: "name" may only contain alphanumeric characters and dashes up to 80 characters in length

  on external-api.tf line 3, in resource "azurerm_api_management_api_version_set" "external-api":
   3: resource "azurerm_api_management_api_version_set" "external-api" {

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I can add the api-management version using the name : v1 on Azure portal.

### References

https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.44.0/azurerm/helpers/validate/api_management.go#L12

**Comment by yupwei68** [comment]
Hi @nanahoshi , thanks for opening this issue. I'm now fixing this bug.
