### ISSUE TITLE
SecurityAlertPolicies APIs are not supported for Basic Postgresql server 

### ISSUE THREAD

**Issue by etiennetremel** [terraform-providers/terraform-provider-azurerm#6945]
After upgrading to terraform-provider-azurerm v2.10.0, I'm seeing the following error message with a Basic Postgresql instance defined:
```
Error: error making read request to postgres server security alert policy: postgresql.ServerSecurityAlertPoliciesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="SecurityAlertPoliciesNotSupportedServerEdition" Message="SecurityAlertPolicies APIs are not supported for Basic server edition"
```

At first I didn't use the `threat_detection_policy` block. So I tried disabling it and also made an attempt using the `lifecycle.ignore_changes` to ignore this field but no luck.

```hcl
resource "azurerm_postgresql_server" "psql" {
  name                = "psql"
  location            = data.azurerm_resource_group.resource_group.location
  resource_group_name = data.azurerm_resource_group.resource_group.name

  sku_name = "B_Gen5_1"

  threat_detection_policy {
    enabled = false
  }
}
```

Am I doing something wrong?

**Comment by etiennetremel** [comment]
Probably related to https://github.com/terraform-providers/terraform-provider-azurerm/commit/e1d441856b43820ee20f468af6bd9f8b37b0baef

It wasn't tested with Basic instance type. cc @katbyte

**Comment by atrauzzi** [comment]
Yikes. I think this project really needs to expand its test scenarios, it seems like every version fixes a bug and then introduces a bunch more.

**Comment by katbyte** [comment]
👋 hi @atrauzzi, 

Sorry that got past our tests, it looks like we were not testing anything but the GP sku 😞 I've opened #7015 which adds tests for both the basic and MO sku's and fixes this for basic. It should go out tomorrow or thursday in 2.11.
