### ISSUE TITLE
Documentation: Cosmos DB Connection strings

### ISSUE THREAD

**Issue by davidobrien1985** [terraform-providers/terraform-provider-azurerm#6951]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
terraform -v
Terraform v0.12.24
+ provider.azurerm v2.3.0
```

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl

resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"
  enable_automatic_failover = true
  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 10
    max_staleness_prefix    = 200
  }
  geo_location {
    prefix            = "tfex-cosmos-db-${random_integer.ri.result}-customid"
    location          = "${azurerm_resource_group.example.location}"
    failover_priority = 0
  }
}

output "cosmos_db_connection_string" {
  value = "${azurerm_cosmosdb_account.db.connection_strings}"
}
```

### Expected Behavior

`cosmos_db_connection_string` should be empty according to documentation. https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html#connection_strings

### Actual Behavior

It works now.
Documentation needs to be updated.

**Comment by lrxtom2** [comment]
@davidobrien1985, A PR to fix this issue! Thanks for opening the issue!
