### ISSUE TITLE
Support for eventgrid_domain_subscription

### ISSUE THREAD

**Issue by Hjortsberg** [terraform-providers/terraform-provider-azurerm#6952]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We make use of event grid domains, topics and subscriptions.
However Terraform seems to lack the ability to create eventgrid domain subscriptions.
@jrauschenbusch and @katbyte has made some really welcome contributions for the ability to create event grid domains and the related topics.
We would like to be able to have Terraform provision E.g a Function and an event grid domain subscription for that function.

We have tried to set it up with a normal `azurerm_eventgrid_event_subscription` but then the Terraform helper resourceid.go kicks in and considers the resource-id invalid and we get a `Error: ID contained more segments than required`.

### New or Affected Resource(s)

* azurerm_eventgrid_domain_subscription

### Potential Terraform Configuration

Currently this is what we tried and thought would work.
```hcl
locals{
  index = index(data.azurerm_resources.somename.resources.*.name, var.event_domain_name)
}

resource "azurerm_eventgrid_event_subscription" "somename" {
  name  = var.event_subscription_name
  scope = "${data.azurerm_resources.somename.resources[local.index].id}/topics/sometopic"
  webhook_endpoint {
    url = "https://${var.function_app_name}.azurewebsites.net/api/RecieveEvent${var.function_secret}"
  }
}
```
### References

* https://docs.microsoft.com/en-us/cli/azure/ext/eventgrid/eventgrid/event-subscription?view=azure-cli-latest

**Comment by jrauschenbusch** [comment]
Hi @Hjortsberg,

it's a bug inside the resource ID parsing logic for event subscriptions. Sorry for that. I try to fix it asap and write some tests for it.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/5e53ba67e213398fceb9554d4a4171017cf4d89c/azurerm/internal/services/eventgrid/parse/eventgrid_event_subscription.go#L34

and

https://github.com/terraform-providers/terraform-provider-azurerm/blob/5e53ba67e213398fceb9554d4a4171017cf4d89c/azurerm/helpers/azure/resourceid.go#L113

**Comment by Hjortsberg** [comment]
Much appriciated! 👍

**Comment by jrauschenbusch** [comment]
To be more precise here. There is no new resource needed here. Should work out of the box using the already existing `azurerm_eventgrid_event_subscription` as soon as the fix is merged and a release is published.

Furthermore maybe this PR is of interest for you:
https://github.com/terraform-providers/terraform-provider-azurerm/pull/6860

It contains support for the `azure_function_endpoint` type . So if you're using an Azure function you won't need to use the webhook endpoint type anymore.

**Comment by Hjortsberg** [comment]
Oh, I missed that you had implemented function endpoints too, will have to try that out! 
Good to hear that we can use the `azurerm_eventgrid_event_subscription` when that PR is merged.

**Comment by marcin-dudek** [comment]
If I will go back to one of previous versions will this be resolved temporarily?
