### ISSUE TITLE
EventGrid subscriptions throwing error in v2.10.0

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#6962]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_eventgrid_event_subscription`

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_event_subscription" "foo_fizz_events" {
  name                 = "${var.context.app_name}-${var.context.env_name}-foo-fizz-events"
  scope                = "${module.svc_fizz_admin.topic_id}"

  webhook_endpoint {
    url = "https://${module.svc_foo_admin.hostname}/runtime/webhooks/EventGrid?functionName=${local.encounter_fizz_events}&code=${module.svc_foo_admin.function_eventgrid_key}"
  }
}

```

### Panic Output

Error: ID contained more segments than required: "/subscriptions/{subscription_id}/resourceGroups/foo-dev-backend-us-east/providers/Microsoft.EventGrid/topics/foo-dev-bar-admin-us-east/providers/Microsoft.EventGrid/eventSubscriptions/foo-dev-bar-fizz-events"

### Expected Behavior

I upgraded from 2.6.0 to 2.10.0 and i ran terraform plan with NO changes to my eventgrid subsciptions...and it should succeed without error...

### Actual Behavior

throws an "ID contained more segments than required"...

### Steps to Reproduce

1. `terraform apply` using 2.6.0
2. 'terraform apply' using 2.10.0

### Important Factoids

Azure Public Cloud

**Comment by jrauschenbusch** [comment]
Same issue as this one: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6952

But this ticket title describes the core problem.

PR is already created: https://github.com/terraform-providers/terraform-provider-azurerm/pull/6958
