### ISSUE TITLE
Support for azurerm_eventhub data source's name attribute export

### ISSUE THREAD

**Issue by vikramhansawat** [terraform-providers/terraform-provider-azurerm#6993]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

data source azurerm_eventhub doesn't export name attribute. Name attribute is required for following resource. e.g:

resource "azurerm_monitor_diagnostic_setting" "test-diagnostic" {
name = "test-diagnostic"
target_resource_id = azurerm_kubernetes_cluster.test.id
eventhub_name = azurerm_eventhub.test.name
eventhub_authorization_rule_id = azurerm_eventhub_namespace_authorization_rule.test.id
..

### New or Affected Resource(s)

* azurerm_monitor_diagnostic_setting
* data source azurerm_eventhub

### Potential Terraform Configuration

```hcl
data "azurerm_eventhub" "example" {
  name                = "search-eventhub"
  resource_group_name = "search-service"
  namespace_name      = "search-eventhubns"
}

resource "azurerm_monitor_diagnostic_setting" "test-diagnostic" {
name = "test-diagnostic"
target_resource_id = azurerm_kubernetes_cluster.test.id
eventhub_name = data.azurerm_eventhub.example.id
eventhub_authorization_rule_id = azurerm_eventhub_namespace_authorization_rule.test.id
..

```

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/6460

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked code, seems terraform already outputs the name attribute. After tested, the value of "name" attribute can be exported successfully with below tfconfig. If you need, you can try below tfconfig to check whether the issue still exists. Thanks.

tfconfig:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-test"
  location = "westus"
}

resource "azurerm_eventhub_namespace" "test" {
  name                = "acctest-EHN-test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Basic"
}

resource "azurerm_eventhub" "test" {
  name                = "acctest-EH-test"
  namespace_name      = azurerm_eventhub_namespace.test.name
  resource_group_name = azurerm_resource_group.test.name
  partition_count     = 2
  message_retention   = 1
}

data "azurerm_eventhub" "test" {
  name                = azurerm_eventhub.test.name
  namespace_name      = azurerm_eventhub_namespace.test.name
  resource_group_name = azurerm_resource_group.test.name
}

output "resource_eventhub_name" {
  value = azurerm_eventhub.test.name
}

output "datasource_eventhub_name" {
  value = data.azurerm_eventhub.test.name
}
```

result:
```
azurerm_resource_group.test: Creation complete after 4s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-test]
azurerm_eventhub_namespace.test: Creation complete after 1m18s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-test/providers/Microsoft.EventHub/namespaces/acctest-EHN-test]
azurerm_eventhub.test: Creation complete after 9s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-test/providers/Microsoft.EventHub/namespaces/acctest-EHN-test/eventhubs/acctest-EH-test]
data.azurerm_eventhub.test: Refreshing state...

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

datasource_eventhub_name = acctest-EH-test
resource_eventhub_name = acctest-EH-test
```

**Comment by vikramhansawat** [comment]
Thanks a lot. This is working as mentioned above.
