### ISSUE TITLE
Support for configuring the file system level for application logs

### ISSUE THREAD

**Issue by jongio** [terraform-providers/terraform-provider-azurerm#7007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In ARM I have this:

```json
{
            "name": "[concat(variables('app'), '/logs')]",
            "type": "Microsoft.Web/sites/config",
            "apiVersion": "2018-11-01",
            "location": "[variables('location')]",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', variables('app'))]"
            ],
            "properties": {
                "applicationLogs": {
                    "fileSystem": {
                        "level": "Information"
                    }
                },
                "httpLogs": {
                    "fileSystem": {
                        "retentionInMb": 35,
                        "retentionInDays": 10,
                        "enabled": true
                    }
                }
            }
        }
```

In Terraform, I see that we have applicationLogs, blob, but I do not see fileSystem:level.

Here's the full ARM snippet for that section.
```json
{
  "id": "/subscriptions/subid/resourceGroups/azsdkdemo7rg/providers/Microsoft.Web/sites/azsdkdemo7app/config/logs",
  "name": "logs",
  "type": "Microsoft.Web/sites/config",
  "location": "West US",
  "tags": {
    "displayName": "app"
  },
  "properties": {
    "applicationLogs": {
      "fileSystem": {
        "level": "Information"
      },
      "azureTableStorage": {
        "level": "Off",
        "sasUrl": null
      },
      "azureBlobStorage": {
        "level": "Off",
        "sasUrl": null,
        "retentionInDays": null
      }
    },
    "httpLogs": {
      "fileSystem": {
        "retentionInMb": 35,
        "retentionInDays": 10,
        "enabled": true
      },
      "azureBlobStorage": {
        "sasUrl": null,
        "retentionInDays": 10,
        "enabled": false
      }
    },
    "failedRequestsTracing": {
      "enabled": false
    },
    "detailedErrorMessages": {
      "enabled": false
    }
  }
}
```

https://management.azure.com/subscriptions/subid/resourceGroups/azsdkdemo7rg/providers/Microsoft.Web/sites/azsdkdemo7app/config/logs?api-version=2018-02-01

It surfaces here in the Portal
![image](https://user-images.githubusercontent.com/2163001/82344344-c791d480-99a8-11ea-95e8-8f1fbee8baf0.png)

https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/subid/resourceGroups/azsdkdemo7rg/providers/Microsoft.Web/sites/azsdkdemo7app/appservicelogs

Would be great to that section full covered by terraform.

azsdke2e

**Comment by tombuildsstuff** [comment]
Looks like this exists in the SDK: https://github.com/Azure/azure-sdk-for-go/blob/c222f285c0f9d595c7ee186f24d4dfbf4cd8a6ad/services/web/mgmt/2019-08-01/web/models.go#L10287-L10291 - so this would need to go into the `application_logs` block as a new section `http_logs`
