### ISSUE TITLE
Support for hiding secret in Tf logs in azurerm_api_management_property

### ISSUE THREAD

**Issue by TLaborde** [terraform-providers/terraform-provider-azurerm#7022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the documentation for ` azurerm_api_management_property`
 fron [here](https://www.terraform.io/docs/providers/azurerm/r/api_management_property.html) there is a note:

> NOTE: setting the field secret to true doesn't make this field sensitive in Terraform, instead it marks the value as secret and encrypts the value in Azure.

Would it be possible to make the field sensitive in Terraform? Having password in clear text in logs is not very good... Maybe we need a  azurerm_api_management_secret_property` for it?

### New or Affected Resource(s)

azurerm_api_management_property

**Comment by tombuildsstuff** [comment]
hi @TLaborde 

Thanks for opening this issue.

The Azure Provider delegates to Terraform Core here - as such I'm going to close this issue in favour of [the upstream issue tracking this](https://github.com/hashicorp/terraform/issues/516) - one solution for which is encrypting the state file ([as is being tracked in this issue](https://github.com/hashicorp/terraform/issues/1421)) - would you mind subscribing to those for updates?

Thanks!
