### ISSUE TITLE
azurerm_application_insights_web_test creates hidden tag that always reflects a "change"

### ISSUE THREAD

**Issue by dlm69** [terraform-providers/terraform-provider-azurerm#7026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
provider.azurerm v2.10.0

### Affected Resource(s)

azurerm_application_insights_web_test

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights_web_test" "default" {
  name                    = "UpOrDown - ${var.applicationname} - ${var.appservicename}"
  location                = local.primarylocation
  resource_group_name     = var.appsharedmodule-rg-name
  application_insights_id = var.appsharedmodule-applicationinsightsid
  kind                    = "ping"
  frequency               = 300
  timeout                 = 120
  enabled                 = true
  geo_locations           = ["us-ca-sjc-azr", "emea-ru-msa-edge", "us-va-ash-azr", "apac-hk-hkn-azr", "emea-au-syd-edge"]

  configuration = <<XML
<WebTest Name="WebTest1" Id="ABD48585-0831-40CB-9069-682EA6BB3583" Enabled="True" CssProjectStructure="" CssIteration="" Timeout="0" WorkItemIds="" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" Description="" CredentialUserName="" CredentialPassword="" PreAuthenticate="True" Proxy="default" StopOnError="False" RecordedResultFile="" ResultsLocale="">
  <Items>
    <Request Method="GET" Guid="a5f10126-e4cd-570d-961c-cea43999a200" Version="1.1" Url="https://${local.custom_header}/heartbeat" ThinkTime="0" Timeout="300" ParseDependentRequests="True" FollowRedirects="True" RecordResult="True" Cache="False" ResponseTimeGoal="0" Encoding="utf-8" ExpectedHttpStatusCode="200" ExpectedResponseUrl="" ReportingName="" IgnoreHttpStatusCode="False" />
  </Items>
</WebTest>
XML
  tags = {
    Environment = local.environment_name
    Application = var.applicationname
  }
}
```

### Expected Behavior

I would expect this to be created and then never change.

### Actual Behavior

Always shows change. Always changes a hidden link in a tag to "null".

      ~ tags                    = {
            "Application"                                                                                                                                               = "Core"
            "Environment"                                                                                                                                               = "Production"
          - "hidden-link:/subscriptions/bf309ff1-579c-44c7-93b7-6e515b120e62/resourceGroups/HCBSAV-P-Core-Shared/providers/microsoft.insights/components/HCBSAV-P-Core" = "Resource" -> null

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Yes, you're right. Seems a hidden tag would be added to the resource. It should be suppressed. I'll submit a PR to fix it.

**Comment by tombuildsstuff** [comment]
hi @dlm69 

Thanks for opening this issue.

Application Insights is rather unique in Azure in that rather than having a means of linking resources together directly, integrations are handled via this `hidden-link:` tag.

Since this is the only means of connecting resources together using Application Insights, Terraform intentionally doesn't filter out this change - should you wish to ignore changes to this field then you should be able to do this using Terraform's `ignore_changes` functionality.

As this behaviour is intentional (since it's the way that Application Insights is designed) unfortunately this isn't something we plan to change at this time - and as such whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment.

Thanks!
