### ISSUE TITLE
azurerm_servicebus_topic - invalid value for name

### ISSUE THREAD

**Issue by janegilring** [terraform-providers/terraform-provider-azurerm#7027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

provider.azurerm v2.10.0

### Affected Resource(s)

* `azurerm_servicebus_topic`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "tfex-servicebus-topic"
  location = "West Europe"
}

resource "azurerm_servicebus_namespace" "example" {
  name                = "tfex_sevicebus_namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"

  tags = {
    source = "terraform"
  }
}

resource "azurerm_servicebus_topic" "example" {
  name                = "12345678
  resource_group_name = azurerm_resource_group.example.name
  namespace_name      = azurerm_servicebus_namespace.example.name

  enable_partitioning = true
}
```

### Expected Behavior

The topic should be deployed.

### Actual Behavior

Error: invalid value for name (The topic name can contain only letters, numbers, periods, hyphens, tildas and underscores. The namespace must start with a letter, and it must end with a letter or number and be less then 260 characters long.)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Adding a letter to the beginning of the topic name makes the provider accept the name. However, when creating the topic from the Azure portal, a name with only numbers is allowed - hence it should be allowed from Terraform as well.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. You're right. I'll submit a change to fix this issue.
