### ISSUE TITLE
Support for "transform" field in azurerm_web_application_firewall_policy

### ISSUE THREAD

**Issue by crawfs** [terraform-providers/terraform-provider-azurerm#7033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Per the microsoft documentation, the "transform" field should be present as an option for custom WAF policies to perform string transformations prior to checking for a match

### New or Affected Resource(s)

* azurerm_web_application_firewall_policy

### Potential Terraform Configuration

```terraform
resource "azurerm_web_application_firewall_policy" "default" {
  name                  = "${var.identifier}-${lower(var.environment)}-gatewaywafdefaultpolicy"
  resource_group_name   = var.rg_name
  location              = var.rg_location

  custom_rules {
    name      = "MatchQueryString"
    priority  = 1
    rule_type = "MatchRule"

    match_conditions {
      match_variables {
        variable_name = "QueryString"
      }

      operator           = "Contains"
      transform          = "Lowercase"
      negation_condition = false
      match_values       = ["aa", "bb", "xy", "yy", "zz"]
    }

    action = "Block"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/custom-waf-rules-overview#transform-optional

**Comment by darrenk13** [comment]
looks to be the same feature that I requested in #5359

**Comment by crawfs** [comment]
Yeah you're right, I did a search for azurerm_web_application_firewall_policy in issue titles which is why I didn't see yours.

**Comment by magodo** [comment]
@crawfs Thank you for submitting this.
Whilst in favor to keep the track in one place, I'm gonna close this issue in favor of #5359.
