### ISSUE TITLE
Create PostgreSQL server timeouts and ends in broken state

### ISSUE THREAD

**Issue by nickwilliams-codynamic** [terraform-providers/terraform-provider-azurerm#7043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.25

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
# main.tf
resource "random_password" "psql_admin_password" {
  length = 16
  special = true
  override_special = "_%@"
}

resource "azurerm_postgresql_server" "wlynx_psql_server" {
  name                = "psql-wlynx-${var.customer.name}-${var.customer.site}-${var.environment}"
  location            = var.location
  resource_group_name = "rg-wlynx-${var.environment}"

  administrator_login          = "psqladmin"
  administrator_login_password = random_password.psql_admin_password.result

  sku_name   = "GP_Gen5_2"
  version    = "11"
  storage_mb = 640000

  backup_retention_days        = 30
  geo_redundant_backup_enabled = true
  auto_grow_enabled            = true

  infrastructure_encryption_enabled = true
  public_network_access_enabled     = true
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
}

resource "azurerm_postgresql_configuration" "timescaledb" {
  name                = "shared_preload_libraries"
  resource_group_name = azurerm_postgresql_server.wlynx_psql_server.resource_group_name
  server_name         = azurerm_postgresql_server.wlynx_psql_server.name
  value               = "timescaledb"

  provisioner "local-exec" {
    command = "az postgres server restart -g ${azurerm_postgresql_server.wlynx_psql_server.resource_group_name} -n ${azurerm_postgresql_server.wlynx_psql_server.name}"
  }
} 

resource "azurerm_postgresql_database" "wlynx_psql_database" {
  name                = "wlynx"
  resource_group_name = azurerm_postgresql_server.wlynx_psql_server.resource_group_name
  server_name         = azurerm_postgresql_server.wlynx_psql_server.name
  charset             = "UTF8"
  collation           = "en-US"

  depends_on = [ azurerm_postgresql_configuration.timescaledb ]
}

# variables.tf
variable "location" {
  description = "The location which resources should run in"
  default = "UK South"
}

variable "environment" {
  description = "The configured environment name"
}

variable "customer" {
  description = "The customer details of this tenant"
  type = object({
    name      = string
    site      = string
    billingid = string
  })
}

# outputs.tf
output "server_fqdn" {
  value = azurerm_postgresql_server.wlynx_psql_server.fqdn
  description = "The FQDN of the server"
}

output "database_name" {
  value = azurerm_postgresql_database.wlynx_psql_database.name
  description = "The name of the database"
}

output "admin_password" {
  value = random_password.psql_admin_password.result
  description = "The admin password for the psql instance."
  sensitive = true
}
```

### Debug Output

https://gist.github.com/nickwilliams-codynamic/fbf07e1519d3561bbfc17b97a440e030

### Panic Output

None

### Expected Behavior

The operation times out, and the resource is never created:

```
Error: waiting for creation of PostgreSQL Server "psql-wlynx-fabrikam-london-sandbox" (Resource Group "rg-wlynx-sandbox"): Code="OperationTimedOut" Message="The operation timed out and automatically rolled back. Please retry the operation."

  on main.tf line 7, in resource "azurerm_postgresql_server" "wlynx_psql_server":
   7: resource "azurerm_postgresql_server" "wlynx_psql_server" {
```

However rerunning apply produces the below error:

```
creating PostgreSQL Server "psql-wlynx-contoso-manchester-sandbox" (Resource Group "rg-wlynx-sandbox"): postgresql.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceBusy" Message="Service is temporarily busy and the operation cannot be performed. Please try again later.
```

### Actual Behavior

The resource is created. Using the same values in the Azure portal the server is created in just over 1 minute.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The server name becomes unavailable after running the apply. As in, when trying to create the resource in the Azure portal the name field values validation as it is not unique.

Running on an Azure trial subscription.

### References
None

* #0000

**Comment by nickwilliams-codynamic** [comment]
This only fails when the `infrastructure_encryption_enabled` setting is set to true.

**Comment by yupwei68** [comment]
Hi @nickwilliams-codynamic , thanks for opening this issue. Currently please keep `infrastructure_encryption_enabled = false `. I have raised an issue to notify the service team https://github.com/Azure/azure-rest-api-specs/issues/9571.

**Comment by tombuildsstuff** [comment]
hi @nickwilliams-codynamic 

Thanks for opening this issue.

As @yupwei68 has mentioned unfortunately this appears to be an issue with the Azure API rather than something specific to Terraform - and as such @yupwei68 has opened the upstream issue https://github.com/Azure/azure-rest-api-specs/issues/9571 to track this with the Service Team.

Since this fix needs to be made in the Azure API, rather than leaving this issue open I'm going to close this issue in favour of the upstream issue where the Service Team should be able to take a look - would you mind [subscribing to that issue for updates](https://github.com/Azure/azure-rest-api-specs/issues/9571)?

Thanks!
