### ISSUE TITLE
Support for IP Groups in Azure Firewall

### ISSUE THREAD

**Issue by dduleep** [terraform-providers/terraform-provider-azurerm#7047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

IP Groups allow to group and manage IP addresses for Azure Firewall rules in the following ways:

- As a source address in DNAT rules
- As a source or destination address in network rules
- As a source address in application rules

An IP Group can have a single IP address, multiple IP addresses, or one or more IP address ranges.
IP Groups could be reused in Azure Firewall DNAT, network, and application rules for multiple firewalls across regions and subscriptions in Azure. Group names must be unique. 

### Affected Resource(s)

* rule{source_addresses} in azurerm_firewall_nat_rule_collection 
* rule{source_addresses} in azurerm_firewall_network_rule_collection
* rule{source_addresses} in azurerm_firewall_application_rule_collection

### New Resource(s)
 * azurerm_ip_groups
* data_ip_groups

### Potential Terraform Configuration

```hcl

azurerm_firewall_nat_rule_collection {
...
   rule{
     source_addresses = data_ip_groups.group-ip.name
  }
}

```

### References

* [Microsoft Doc - IP Groups in Azure Firewall](https://docs.microsoft.com/en-us/azure/firewall/ip-groups)

**Comment by LucianFrango** [comment]
I had a duplicate to this issue as I missed seeing this when i raised #7827 

Any ETA on this? Working with a customer that this functionality is a requirement.

**Comment by LucianFrango** [comment]
Bump...
