### ISSUE TITLE
Support for detailed error messages and failed request tracing in App Service

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#7050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure App Services support under "App Service Logs" to enable
- Detailed error messages
- Failed request tracing
![image](https://user-images.githubusercontent.com/11445087/82672792-1eb1d680-9c41-11ea-9fd9-dd8d0b9e65a1.png)

As far as I can see (and please correct me if I'm wrong), those settings cannot be set through Terraform today.

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by NT-D** [comment]
@tombuildsstuff Hi, nice to meet you. Can I handle this issue if no one drive this now ?

**Comment by NT-D** [comment]
@tombuildsstuff Hi, Can I handle this issue if no one drive this now ? I'm wondering whether this one or following issue is better challenge for beginner. I'm happy if you advice me which is good starting point.
https://github.com/terraform-providers/terraform-provider-azurerm/issues/6236

**Comment by NT-D** [comment]
Just sharing investigation result. We can do this setting via CLI, so I think we may be able to achieve this via Terraform, too.

1. Create App Service Plan
az appservice plan create --name {app service plan name} --sku S1 --location=japaneast --resource-group  {resource group name}

2. Provision app service
az webapp create --name {app service name} --plan {app service plan name} --runtime "node|6.9" --resource-group {resource group name}

3. Set up log configuration
az webapp log config --name {app service name} --resource-group {resource group name} --detailed-error-message true --failed-request-tracing true

**Comment by NT-D** [comment]
My colleague is now challenging this one, so let me try to find another good issue. Thanks.

**Comment by jackofallops** [comment]
Closing as this feature has been merged and released.
