### ISSUE TITLE
azurerm_storage_account account_replication_type GZRS

### ISSUE THREAD

**Issue by sblack4** [terraform-providers/terraform-provider-azurerm#7051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
>  terraform version                                                                                                                                                                                                   
Terraform v0.12.23
+ provider.azurerm v1.43.0
+ provider.errorcheck v2.0.3
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl

resource "azurerm_storage_account" "backend" {
  name                      = var.storage_account_name
  resource_group_name       = azurerm_resource_group.backend.name
  location                  = var.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "GZRS"
  enable_https_traffic_only = true

  tags = local.common_tags
}
```

### Expected Behavior

Resource Created with GZRS replication type 

### Actual Behavior

```
Error: expected account_replication_type to be one of [LRS ZRS GRS RAGRS], got GZRS

  on main.tf line 13, in resource "azurerm_storage_account" "backend":
  13: resource "azurerm_storage_account" "backend" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The [terraform documentation does not mention a GZRS type](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#account_replication_type), if this is a provider version problem (we have lots of code using the old provider) than this is a docs issue and the terraform docs should be updated to reflect [the GZRS replication type](https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy?toc=/azure/storage/blobs/toc.json#geo-zone-redundant-storage)

**Comment by lrxtom2** [comment]
@sblack4 Hi, Thanks for opening this good issue! I will take a look and try to fix that.
