### ISSUE TITLE
azurerm_kubernetes_cluster should support diskEncryptionSetID like ARM

### ISSUE THREAD

**Issue by jbinko** [terraform-providers/terraform-provider-azurerm#7058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure ARM Template supports - diskEncryptionSetID - ResourceId of the disk encryption set to use for enabling encryption at rest. See: https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-03-01/managedclusters#managedclusterproperties-object

The object azurerm_kubernetes_cluster doesn't have such field/support. TF supports everything around, including encryption sets, key vaults, keys, role assignements, etc. The only last thing which is missing is the field where you can specify created encryption set.
It should be easy to implement/quick win.
Customer needs such feature in TF enabled. No any workaround I'm aware of exists because it needs to be set during cluster creation.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by jlpedrosa** [comment]
I've created a detailed proposal on #7092  I can close the other one and paste the contents here.
I will also code it if no one is working on it.
@jbinko  Where you on it?
@tombuildsstuff  @katbyte Let me know if you want me to close the other ticket.

**Comment by tombuildsstuff** [comment]
👋 

Whilst this issue was opened earlier, I'm going to close this in favour of #7092 which is tracking the same enhancement but has a little more detail - would you mind subscribing to that issue for updates?

Thanks!

**Comment by tombuildsstuff** [comment]
@jlpedrosa given there's a number of PR's/feature requests open for AKS which are conflicting with one another, it'd probably help to ship this sooner if we can consolidate those into a single PR first. As such whilst we appreciate the offer, would you mind holding off on that for the moment?

I'm working through the open PR's/issues at the moment, working out how's best to proceed - but it should be possible to ship this at the same time / real soon 🤞 

Thanks!

**Comment by jlpedrosa** [comment]
Hi @tombuildsstuff 

I just read the message, the PR for the disk is done and in the other ticket. Let me know if I can help in any way,
