### ISSUE TITLE
[Azure Firewall] Deployment of Rules Sometimes Fails with duplicate rule errors

### ISSUE THREAD

**Issue by archmangler** [terraform-providers/terraform-provider-azurerm#7062]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Description
========

- When a terraform apply is run, the apply fails reporting duplicate rules present on the Azure Firewall.
- This occurs even after a clean `terraform destroy` has been run (but there is no indication that some azure firewall rules have been left behind on the Azure Firewall)
- Further, this happens when there has been at least 1 interrupted `terraform destroy` before a clean `terrform destroy` has been achieved. Specifically, if the terraform destroy was interrupted during the period the rules teardown was happening.
- The duplicate rules need to be removed from the Azure firewall via cli but there are no duplicate entries in the statefile.
- This suggests that possibly the API has returned OK for destruction Azure Firewall Rule Collection, but the rules not removed.
- This suggests that terraform:

 a) does not always refresh the state from the current configuration of the rules collection in Azure Firewall.
b) does lose a record of what resources remain deployed if interrupted during the destroy process

### Terraform (and AzureRM Provider) Version

```
bash-4.2# terraform -v
Terraform v0.11.11
```

- Azurerm provider version:

```
"azurerm" (1.44.0)
```

### Affected Resource(s)

* `azurerm_firewall_application_rule_collection`

### Terraform Configuration Files

- terraform.tfvars fw rule specification is defined as follows:

```hcl

firewall_application_collection = [
  {
    "rule_name"    = "permit_abc_outbound_sftps_require"
    "target_fqdn"  = "xxxxx,xxxxxx,xxxxxx,"
    "web_protocol" = "sftps"
    "web_port"     = "555"
  },
  {
    "rule_name"    = "permit_abc_outbound_rtsp_require"
    "target_fqdn"  = "xxx,xxxxx,xxxxx"
    "web_protocol" = "rtsp"
    "web_port"     = "21"
  },
  {
    "rule_name"    = "permit_abc_outbound_sftps_optional"
    "target_fqdn"  = "yyy,yyyy,yyyy,yyyy"
    "web_protocol" = "sftps"
    "web_port"     = "555"
  },
  {
    "rule_name"    = "permit_abc_outbound_rtsp_optional"
    "target_fqdn"  = "*.xxxxx.yyy"
    "web_protocol" = "rtsp"
    "web_port"     = "21"
  },
  {
    "rule_name"    = "permit_abc_outbound_sftps_sec"
    "target_fqdn"  = "my.domain.com,server.system.com"
    "web_protocol" = "sftps"
    "web_port"     = "555"
  },
.
.
.
```

- main.tf rule configuration is passed to a module wrapper which wraps the firewall rule.

```hcl
module "firewall_outbound_region1" {
  source = "somesou"
  resource_tags              = "${var.resource_tags}"
  bucode                   = "${var.buCode}"
  subscode                = "${var.SubsCode}"
  environment                = "${var.environment}"
  subscode                   = "${var.subsCode}"
  loccode                    = "${element(var.regions,index(var.regions, "az1"))}"
  ordercode                     = "${var.app_ref}"
  subnets                    = "${var.abc_subnets_map["region1"]}"
  resource_group_name        = "${data.terraform_remote_state.az1_abc_vnet_rg}"
  virtual_network_name       = "${data.terraform_remote_state.az1_abc_vnet_name}"
  firewall_network_rules     = "${var.firewall_network_collection}"
  firewall_application_rules = "${var.firewall_application_collection}"

  providers {
    azurerm = "azurerm.hub"
    azurerm = "azurerm"
  }
}
```

- module-side, the resource applies these rules as follows:

```hcl
resource "azurerm_firewall_application_rule_collection" "outbound" {
  provider = "azurerm.hub"
  count    = "${length(var.firewall_application_rules)}"

  name                = "rule-${var.bucode}-${var.subscode}-${var.ordercode}-${format("%02d", count.index + 1)}"
  azure_firewall_name = "${data.azurerm_firewall.frontend.name}"
  resource_group_name = "rsg-${var.bucode}-${var.subscode}-${var.loccode}-hubnetworkfrontend"
  priority            = "${local.firewall_priority + count.index}"
  action              = "Allow"

  rule {
    name             = "${lookup(var.firewall_application_rules[count.index], "rule_name")}"
    source_addresses = ["${data.azurerm_subnet.instance.*.address_prefix}"]
    target_fqdns     = ["${split(",", lookup(var.firewall_application_rules[count.index], "target_fqdn"))}"]

    protocol {
      type = "${title(lower(lookup(var.firewall_application_rules[count.index], "web_protocol")))}"
      port = "${lookup(var.firewall_application_rules[count.index], "web_port")}"
    }
```

### Debug Output

Error message (deploy output)

https://gist.github.com/archmangler/da7ec57ed04c5143e3aa0e318a674b2c

### Actual Behavior

1. A successful terraform deployment was successfully carried out, creating some resources and updating firewall rules on Azure firewall.
2. The deployment was destroyed (terraform destroy ...) successfully.
3. Redeploying the blueprint resulted in `terraform apply` failing due to duplicate rules being detected on the Azure Firewall (not in the state):

```
* azurerm_firewall_application_rule_collection.outbound.2 Error creating/updating Application Rule Collection "rule-lolcorp-dev-mydept-05" in Firewall
"afw-lolcorp-hub-region1-out" (Resource Group: "rsg-lolcorp-hub-region1-networkfrontend"): network.AzureFirewallsClient#CreateorUpdate: Failure sending request:
StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details =
[{"code","DuplicateResourceName"},"message","Resource /subscriptions//resourceGroups//providers/Microsoft.Network/azureFirewalls/ has two child resources with the same name (rule-lolcorp-dev-mydept-05)."}]
```

### Steps to Reproduce

1. `terraform destroy` and cancel terraform mid-way through destroy (during rules creation part)
2. `terraform destroy` (rerun)
3. `terraform apply`

#
## Important Factoids

- Azure Southeast Asia region

### References

* #0000

**Comment by archmangler** [comment]
This is due to running terraform with refresh=false

**Comment by archmangler** [comment]
Additional information:  terraform is being run with `refresh=true` for both destroy and plan.

**Comment by magodo** [comment]
@archmangler Thank you for submitting this!

Your concern that interruption of a destroys might cause state file into a corruption status actually doesn't exist, as terraform will guarantee to update the state only when an operation finished. So imagine the following two cases:
1. you interrupt terraform destroy at the time that API request has been sent, but the response has not been received. In this case, terraform will not update the state (as you have interrupted the process). And the next destroy will firstly check whether the resource still exists (as you are setting `refresh=true`) at the beginning, imagine the request succeeded at the service side, then terraform will update the state to remove the resource entry.
2. you interrupt terraform destroy right before it updates the state, or during it is updating the state. The same process as above will happen.
In your certain use case here, as `azurerm_firewall_application_rule_collection` is actually a property of `azurerm_firewall` in Azure, the interruption is even unrelated here. Because if you destroy the `azurerm_firewall` cleanly, then all the rule collections of that firewall will be cleaned up altogether. You can simply verify this by creating a single `azurerm_firewall_application_rule_collection` and `azurerm_firewall`, then remove the `azurerm_firewall_application_rule_collection` from the state via `terraform state rm <addr>`. Then destroy the provision and apply again, there should be no issue.

Is it possible to provide the complete definition of the terraform module you are using?
If you can provide the debug log (with `TF_LOG=DEBUG` set) when the issue happens, that will be most helpful.

**Comment by katbyte** [comment]
@archmangler I'm going to close this as its been nearly a year without a response, please do let us know if this is still an issue for you!
