### ISSUE TITLE
Azure RM 2.x "azurerm_linux_virtual_machine_scale_set" upgrade policy Manual doesn't work, rotates VMs each time

### ISSUE THREAD

**Issue by Dmitry1987** [terraform-providers/terraform-provider-azurerm#7077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
provider.azurerm v2.9.0

### Affected Resource(s)
azurerm_linux_virtual_machine_scale_set

### Terraform Configuration Files

```hcl

resource "azurerm_linux_virtual_machine_scale_set" "set" {
  name                = "${var.name}-${var.global_vars.environment}-set"
  resource_group_name = var.global_vars.resource_group
  location            = var.global_vars.location
  sku                 = var.vm_size
  instances           = var.number_of_servers
  zones               = [1, 2, 3]
  upgrade_mode        = "Manual"
  admin_username      = "devops"

  admin_ssh_key {
    username   = "devops"
    public_key = file("ssh_public_id_rsa.pub")
  }

  boot_diagnostics {
    storage_account_uri = var.global_vars.storage_blob_uri
  }

  source_image_id = var.source_image_id

  os_disk {
    storage_account_type = "StandardSSD_LRS"
    caching              = "ReadWrite"
    disk_size_gb         = var.disk_size_gb
  }

  network_interface {
    name    = "${var.name}-${var.global_vars.environment}-nic"
    primary = true

    ip_configuration {
      name      = "internal"
      primary   = true
      subnet_id = var.subnet
      # Can pass here the application gateway backend pools to connect those instances to app gateway
      application_gateway_backend_address_pool_ids = length(var.app_gw_address_pool_ids) > 0 ? var.app_gw_address_pool_ids : null
      # Can connect to LB pool that was created above, as well, optional
      load_balancer_backend_address_pool_ids = var.create_lb ? [azurerm_lb_backend_address_pool.addresspool[0].id] : null
    }
  }

  custom_data = base64encode(templatefile("user_data.sh.tmpl", {
    environment         = var.global_vars.environment
    host_type           = var.name
  }))
  tags = var.tags
}

```

### Expected Behavior

When   upgrade_mode        = "Manual"
VMSS should not rotate the VMs when custom_data script changes

### Actual Behavior
VMs rotated any time a custom_data script changes.

### Steps to Reproduce

Create VMSS, put upgrade_mode=Manual, assign a custom_data script (some bash). Any time you update the bash script, VMs will be forced to be recreated/rebooted (I'm not sure what exactly happens under the hood but I end up with a clean VM each time, I guess it's recreated.

Azure support technician says it's not the Azure side of the VMSS logic flaw that's recreating them on custom_data updates, but a "Terraform Plugin" entity logged as forcing the VMs to reboot/recreate o.O , how can I solve this?  I want them to be recreated only on manual action.

**Comment by ArcturusZhang** [comment]
Hi @Dmitry1987 thanks for this issue!

The custom data only takes effect during the first boot or initial setup on a VM, therefore when you changed the custom data, Azure will always mark the instances as `LatestModelApplied = false`, and hence terraform will always update them and reimage them to ensure the latest custom data can take effect. (Reference in terraform doc: https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html#custom_data, and reference from Azure: https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data)

The `upgrade_mode` is only saying that how an OS upgrade takes effect when the image or sku gets any update. In your case, the custom data changes make the VM instances tainted, therefore they will always be updated.

**Comment by Dmitry1987** [comment]
Oh these are bad news for me @ArcturusZhang  but thank you for explanation :) 
is there any way to make scale-set ignore those changes until new machines spawn (I want only the new ones to spawn with new settings and old VMs remain as is. it's easy in AWS, I wonder if possible in scale-set?)

**Comment by tombuildsstuff** [comment]
hey @Dmitry1987 

With the new `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources, Terraform by default will roll these instances as required (as we [mention in the documentation](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html#disclaimers)) to ensure the latest image is fully propagated.

That said, it's possible to opt-out of this behaviour (so Terraform will just update the configuration and new instances will roll this out of band/via a script) by using the `features` block to disable this setting - via:

```
provider "azurerm" {
  version = "=2.11.0"
  features {
    virtual_machine_scale_set {
      roll_instances_when_required = false
    }
  }
}

resource "azurerm_linux_virtual_machine_scale_set" "test" { ... }
```

Would you be able to take a look and see if that works for you? Since this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by ArcturusZhang** [comment]
Hi @tombuildsstuff but when I am checking the code [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/d15d71abc58729c194ac112e01d08d18a2c3bff8/azurerm/internal/services/compute/virtual_machine_scale_set_update.go#L49) this features option seems to only take effect when `upgrade_mode=Automatic`.

**Comment by Dmitry1987** [comment]
thanks everyone for suggestions!
@tombuildsstuff I already have this setting, had it from the start, but it doesn't have any effect - any time I change a tiny bit of the custom_data, a terraform apply will force rotate all VMs in a scale set :( 


![image](https://user-images.githubusercontent.com/9369080/83349178-a0f86580-a2e7-11ea-9a53-95855692c0c6.png)

**Comment by Dmitry1987** [comment]
@ArcturusZhang I think you found a bug 👍  looks like it.
