### ISSUE TITLE
The flag "skip_provider_registration" should also avoid reading the provider list

### ISSUE THREAD

**Issue by miiitch** [terraform-providers/terraform-provider-azurerm#7089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

AzureRM 2.11

### Expected Behavior

I need to use the flag "skip_credentials_validation" to avoid the resource provider list to be read. I should use the flag "skip_provider_registration".

### Actual Behavior
As the doc stated (https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration) this flag is here for environments with restricted permissions. My teams does not any role at the subscription level, so no way for them to read the provider list. Even with the flag "skip_provider_registration", the script failed because the provider list is still read:

> **Error**: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'XXXXXXXXX' with object id 'YYYYYYYYYYY' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/ZZZZZZZZZZZZZZ' or the scope is invalid. If access was recently granted, please refresh your credentials."

To avoid reading the provider list I need to use the flag "skip_credentials_validation" because it removes the query on the provider list.

### References

Source code : https://github.com/terraform-providers/terraform-provider-azurerm/blob/8174fd51cada9a1fd982d2e7e9fe36a5d70ce2b1/azurerm/internal/provider/provider.go

**Comment by njuCZ** [comment]
@miiitch, in this case, I think it's ok to use the flag "skip_credentials_validation". this flag is to list all available providers, if the api succeeds, it's regarded that the provider credentials are correct.  This flag is used no where else.

**Comment by miiitch** [comment]
Is it possible to update the doc to warn the user that Terraform will read the providers if the flag is true?
