### ISSUE TITLE
Unable to import role assignment that was added at the level of a resource group.

### ISSUE THREAD

**Issue by mo3taz1705** [terraform-providers/terraform-provider-azurerm#7097]
The role assignments that was added to resource group has different resource id in azure.
The resource id of this role assignments contains a reference to the resource group like this
`/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RESOURCE_GRP_NAME/providers/Microsoft.Authorization/roleAssignments/00000000-0000-0000-0000-000000000000`

while in the docs, the resource id provided in the examples has no reference to the resource group like this
`/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleAssignments/00000000-0000-0000-0000-000000000000`

This causes the terraform import command to fail as it can not find the wrong resource id in azure.

**Comment by njuCZ** [comment]
@mo3taz1705 because role assignments have different scopes: `management group`, `subscription`, `resource group`. The id format for different scope is not the same. in the docs,  the id format is for scope `subscription`.  for scope `resource group`, the id format is exactly what you say.

**Comment by mo3taz1705** [comment]
@njuCZ 
I think it would be better, if this can be mentioned in the docs.
