### ISSUE TITLE
[Azure][PostreSQL] Create db instance and database in the same script?

### ISSUE THREAD

**Issue by vap78** [terraform-providers/terraform-provider-azurerm#7108]
Hi

I have following script that is supposed to create a PostgreSQL instance and a database in it on Azure:

```
resource "azurerm_postgresql_server" "db" {
  name                = "${var.db_name}-p"
  location            = var.region
  resource_group_name = azurerm_resource_group.rg.name
  sku_name = "GP_Gen5_4"

  storage_profile {
    storage_mb            = 71680
    backup_retention_days = 7
    geo_redundant_backup  = "disabled"
    auto_grow             = "Enabled"
  }

  administrator_login          = var.database_admin_user
  administrator_login_password = azurerm_key_vault_secret.admin_password.value
  version                      = "9.6"
  ssl_enforcement              = "Disabled"
}


resource "azurerm_postgresql_database" "core" {
  name                = var.database_name
  resource_group_name = azurerm_resource_group.rg.name
  server_name         = azurerm_postgresql_server.db.name
  charset             = "UTF8"
  collation           = "en-US"
}
```
Instance creation is OK but database creation fails with one fails with:

> Error: A resource with the ID "/subscriptions/.../resourceGroups/.../providers/Microsoft.DBforPostgreSQL/servers/.../databases" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_postgresql_database" for more information.

I found a similar issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6389 that is closed with the comment that this is working as intended. The proposal is to import the resource. 

I see two things not right with this one:
- Why would the resource be considered not managed by Terraform? It was  literally just created by Terraform.
- How do I import the resource - I just run "terraform apply". There is no chance to import a resource mid-run.

What comes to my mind is to split the script - first create the instance, then import the resource and then create the database. This would most probably work, but will have to include some input/output variables between the two scripts and will also look extremely weird for the maintainer some years in the future (even if this maintainer is still me :) ).

Is there a way to have these two operations in one script?

Edit: this looks like a bug, because  when I try to execute :

`terraform import <resource> /subscriptions/subscription_id/resourceGroups/resource_group_id/providers/Microsoft.DBforPostgreSQL/servers/db_id/databases/`

I get following error:

> Error: [ERROR] Unable to parse Postgres Server ID "<ID_FROM_ABOVE>": The number of path segments is not divisible by 2 in ID_FROM_ABOVE

Used providers:

```
provider "azurerm" {
    version             = "=2.11.0"
    features {}
    subscription_id     = var.subscription_id
}

provider "null" {
    version     = "~> 2.1"
}

```

Best regards
Vasil

**Comment by yupwei68** [comment]
Hi @vap78 , thanks for opening this issue. You could import the existing database resource before applying the script. In your case, I suppose you could import the existing database by:
`terraform import azurerm_postgresql_database.core /subscriptions/subscription_id/resourceGroups/resource_group_id/providers/Microsoft.DBforPostgreSQL/servers/serverName/databases/dbName`

Please refer the [document](https://www.terraform.io/docs/providers/azurerm/r/postgresql_database.html#import)

`Error: [ERROR] Unable to parse Postgres Server ID "<ID_FROM_ABOVE>": The number of path segments is not divisible by 2 in ID_FROM_ABOVE` this error suggests that your id to be imported is incorrect.

**Comment by vap78** [comment]
Hi @yupwei68 

Thank you for your answer.

The database that that is supposed to be imported does not exist yet. The script attempted to create it before and failed. So I cannot refer it by ID.

Note that the ID that I provide to the "terraform import" command is the same that is mentioned in the error message from "terraform apply".

Again - why would I need to import a resource that was just created by Terraform ? 

I can provide a full debug trace if necessary. 

Best regards
Vasil

**Comment by vap78** [comment]
Finally figured it out - it was a configuration error all along. 

The problem was that the variable "var.database_name" was not set which by default is an empty string. Then the database path looks like this:

`/subscriptions/subscription_id/resourceGroups/resource_group_id/providers/Microsoft.DBforPostgreSQL/servers/serverName/databases/ `

 Looks like this Terraform decides that this path is a resource that is not managed by it and produces this error.

Thank you for looking into this!

Best regards
Vasil
