### ISSUE TITLE
Databricks tags are replaced on each call to apply

### ISSUE THREAD

**Issue by sdebruyn** [terraform-providers/terraform-provider-azurerm#7109]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.25
+ provider.azuread v0.9.0
+ provider.azurerm v2.11.0
+ provider.databricks (unversioned)
+ provider.http v1.2.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.time v0.5.0
```

### Affected Resource(s)
* `azurerm_databricks_workspace`

### Terraform Configuration Files
https://github.com/datarootsio/terraform-module-azure-datalake/blob/v0.1.0/databricks.tf

### Debug Output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_databricks_workspace.dbks will be updated in-place
  ~ resource "azurerm_databricks_workspace" "dbks" {
        id                          = "/subscriptions/hidden/resourceGroups/rgtfadl/providers/Microsoft.Databricks/workspaces/dbkstfadl"
        location                    = "eastus2"
        managed_resource_group_id   = "/subscriptions/hidden/resourceGroups/rgdbkstfadl"
        managed_resource_group_name = "rgdbkstfadl"
        name                        = "dbkstfadl"
        resource_group_name         = "rgtfadl"
        sku                         = "standard"
      ~ tags                        = {
          + "DataLake" = "tfadl"
        }
        workspace_id                = "hidden"
        workspace_url               = "adb-hidden.3.azuredatabricks.net"

        custom_parameters {
            no_public_ip = false
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior
After a succesful call to apply, another `terraform plan` or `terraform apply` should not propose any changes.

### Actual Behavior
Terraform updates the existing Databricks workspace (from the first call to `terraform apply`) with a PUT request to add the tags again.

### Steps to Reproduce
1. Add a `azurerm_databricks_workspace` resource to your config
1. Add at a tag to the resource
1. `terraform plan` --> the tag will be created
1. `terraform apply` --> the tag is created (can be validated through Azure Portal, as well as Azure REST API)
1. `terraform plan` --> terraform says the resource has to be updated and the tags have to be added again because they are missing

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems tags can be added and there is no diff in terraform with below tfconfig. Maybe I missed something. If you need, you can try below tfconfig to check whether the issue still exists.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-db-test"
  location = "westus"
}

resource "azurerm_databricks_workspace" "test" {
  name                = "acctestDBW-test"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "standard"
  tags = {
    env = "Test2"
  }
}

output "tags" {
  value = azurerm_databricks_workspace.test.tags
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-db-test"
  location = "westus"
}

resource "azurerm_databricks_workspace" "test" {
  name                = "acctestDBW-test"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "standard"
}

output "public_ip_address" {
  value = azurerm_databricks_workspace.test.tags
}
```

**Comment by sdebruyn** [comment]
Hi @neil-yechenwei I'm not sure I correctly understand what you're saying. Yes, tags can be added without issues, but Terraform wants to replace them on each call to apply. Terraform should not do that. It looks like Terraform thinks the tags are gone after a refresh.

**Comment by neil-yechenwei** [comment]
@sdebruyn , After tested, there is no diff after "tf apply" with my above tfconfig. If you want, you can have a try. THanks.

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to confirm if this is still an issue then we should be able to reopen this and take another look.

Thanks!
