### ISSUE TITLE
Unable to disable "default_ttl" once it is set for azurerm_cosmosdb_sql_container

### ISSUE THREAD

**Issue by fcatacut** [terraform-providers/terraform-provider-azurerm#7113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.24
- AzureRM v2.11.0

### Affected Resource(s)

* `azurerm_cosmosdb_sql_container`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

variable "namespace" {
  default = "<change me>"
}

resource "azurerm_resource_group" "myrg" {
  name     = format("myrg-%s", var.namespace)
  location = "westus"
}

resource "azurerm_cosmosdb_account" "mycosmosdb" {
  name                = format("mycosmosdb-%s", var.namespace)
  resource_group_name = azurerm_resource_group.myrg.name
  location            = "westus"
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"
  consistency_policy {
    consistency_level = "Session"
  }
  geo_location {
    location          = "westus"
    failover_priority = 0
  }
}

resource "azurerm_cosmosdb_sql_database" "mysqldb" {
  name                = "mysqldb"
  resource_group_name = azurerm_resource_group.myrg.name
  account_name        = azurerm_cosmosdb_account.mycosmosdb.name
  throughput          = 400
}

resource "azurerm_cosmosdb_sql_container" "cosmos_sqlcontainer" {
  name                = "mysqlcontainer"
  resource_group_name = azurerm_resource_group.myrg.name
  account_name        = azurerm_cosmosdb_account.mycosmosdb.name
  database_name       = azurerm_cosmosdb_sql_database.mysqldb.name
  # default_ttl         = 1800
  partition_key_path = "/definition/id"
  throughput         = 400
}
```

### Expected Behavior

Setting `default_ttl` to `null` or removing it should disable the setting when it has been previously set.

### Actual Behavior

`terraform plan` results in

    ```No changes. Infrastructure is up-to-date.```

`terraform apply` results in

    ```Apply complete! Resources: 0 added, 0 changed, 0 destroyed.````

### Steps to Reproduce

1. Set the `namespace` variable to a unique alphanumeric value.
2. `terraform apply`
3. Uncomment the `default_ttl` so that an item expires 30 minutes after its last modified date. Note: The actual value doesn't matter at this point.
4. `terraform plan`

    Observe that `default_ttl` is being added and not modified.
    ```
    Terraform will perform the following actions:

      # azurerm_cosmosdb_sql_container.cosmos_sqlcontainer will be updated in-place
      ~ resource "azurerm_cosmosdb_sql_container" "cosmos_sqlcontainer" {
            account_name        = "mycosmosdb-dev"
            database_name       = "mysqldb"
          + default_ttl         = 1800
            name                = "mysqlcontainer"
            partition_key_path  = "/definition/id"
            resource_group_name = "myrg-dev"
            throughput          = 400
        }

    Plan: 0 to add, 1 to change, 0 to destroy.
    ```
5. `terraform apply`
6. Try to disable this setting by setting `default_ttl` to `null` or comment it out.
7. `terraform plan` or `terraform apply`

**Comment by yupwei68** [comment]
Hi @fcatacut , thanks for opening this issue. This is an upstream Terraform bug. As a workaround, I'd like to suggest to set `default_ttl = -1` instead of commenting this line.

**Comment by ArcturusZhang** [comment]
Hi @fcatacut initially I would suppose that replace the `Computed: true` by `Default: -1` would solve your problem, but because of some historical reasons, to keep backward compatibility, we cannot do it, since there would be some users relying on the value returned by the service (when assigning it to 0 or leave it empty)

I believe you could solve your problem by explicitly assigning `default_ttl` to `-1`. Therefore for now I would close this issue hope you would not mind.
If you still have concerns or questions, please feel free to reopen or/and comment. 

Thank you!
