### ISSUE TITLE
azurerm_monitor_diagnostic_setting - cant be deployed because it already exists - but gets deployed right at this moment

### ISSUE THREAD

**Issue by renereinert** [terraform-providers/terraform-provider-azurerm#7114]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform v0.12.24
* azurerm 2.11.0

### Affected Resource(s)
* azurerm_resource_group
* azurerm_public_ip
* azurerm_application_gateway
* azurerm_monitor_diagnostic_setting (error causing)

### Terraform Plan File first deployment
First deployment (no statefile exists, no resources exists)
Terraform Plan shows:

```hcl
# azurerm_application_gateway.sharedagw will be created
  + resource "azurerm_application_gateway" "sharedagw" {
      + name                = "qa-shared-01-agw"
      + resource_group_name = "qa-shared-01-agw-rg"
		<...>

# azurerm_monitor_diagnostic_setting.sharedagw will be created
  + resource "azurerm_monitor_diagnostic_setting" "sharedagw" {
      + name                       = "qa-shared-01-agw-diag"
		<...>
	}	

# azurerm_public_ip.sharedagw will be created
  + resource "azurerm_public_ip" "sharedagw" {
		<...>
      + name                    = "qa-shared-01-agw-pip"
      + resource_group_name     = "qa-shared-01-agw-rg"
    }

# azurerm_resource_group.sharedagw will be created
  + resource "azurerm_resource_group" "sharedagw" {
		<...>
      + name     = "qa-shared-01-agw-rg"
    }

Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: specified.tfplan
```
Terraform Apply failes with "exisiting resources" error
```hcl
azurerm_resource_group.sharedagw: Creating...
azurerm_resource_group.sharedagw: Creation complete after 0s [id=/subscriptions/08ba601c-682a-41f5-b487-65dbff0c0653/resourceGroups/qa-shared-01-agw-rg]
azurerm_public_ip.sharedagw: Creating...
azurerm_public_ip.sharedagw: Creation complete after 3s [id=/subscriptions/08ba601c-682a-41f5-b487-65dbff0c0653/resourceGroups/qa-shared-01-agw-rg/providers/Microsoft.Network/publicIPAddresses/qa-shared-01-agw-pip]
azurerm_application_gateway.sharedagw: Creating...
azurerm_application_gateway.sharedagw: Still creating... [10s elapsed]
azurerm_application_gateway.sharedagw: Still creating... [5m10s elapsed]
azurerm_application_gateway.sharedagw: Creation complete after 5m14s [id=/subscriptions/08ba601c-682a-41f5-b487-65dbff0c0653/resourceGroups/qa-shared-01-agw-rg/providers/Microsoft.Network/applicationGateways/qa-shared-01-agw]
azurerm_monitor_diagnostic_setting.sharedagw: Creating...

Error: A resource with the ID "/subscriptions/08ba601c-682a-41f5-b487-65dbff0c0653/resourcegroups/qa-shared-01-agw-rg/providers/microsoft.network/applicationgateways/qa-shared-01-agw/providers/microsoft.insights/diagnosticSettings/qa-shared-01-agw-diag" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
```
### Terraform Plan File second deployment
Uses statefile of the first deployment

```hcl
# azurerm_monitor_diagnostic_setting.sharedagw will be created
  + resource "azurerm_monitor_diagnostic_setting" "sharedagw" {
      + name                       = "qa-shared-01-agw-diag"
		<...>
	}	

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: specified.tfplan
```
Terraform Apply failes with "exisiting resources" error
```hcl
azurerm_monitor_diagnostic_setting.sharedagw: Creating...

Error: A resource with the ID "/subscriptions/08ba601c-682a-41f5-b487-65dbff0c0653/resourcegroups/qa-shared-01-agw-rg/providers/microsoft.network/applicationgateways/qa-shared-01-agw/providers/microsoft.insights/diagnosticSettings/qa-shared-01-agw-diag" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
```

### Debug Output

I receive the following error:
Failes because of: "A resource with the ID "/subscriptions/xyz/resourcegroups/qa-shared-01-agw-rg/providers/microsoft.network/applicationgateways/qa-shared-01-agw/providers/microsoft.insights/diagnosticSettings/qa-shared-01-agw-diag" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information."

### Expected Behavior

deployment of the AGW with enabled Diagnostic Settings as expected

### Actual Behavior

cant deployment of the AGW with enabled Diagnostic Settings - we need to exclude the "azurerm_monitor_diagnostic_setting" to get the deployment running.

### Steps to Reproduce
1. Delete statefile and resources
2. `terraform plan` (first deployment)
3. `terraform apply` (will fail)
4. `terraform plan` (second deployment)
5. `terraform apply` (will fail)

### Important Factoids

We try to deploy: 
- RG
- PIP
- AGW with enabled Diagnostic Settings towards a shared log analytics workspace (outside of this deployment and running)

So the deployment shouldnt be a big deal and was running smooth in azurerm v1.xx.

If i run terraform import on the "azurerm_monitor_diagnostic_setting" at the fist deployment it tells me that there is no such a resource. So i run it without. And i face the upper error. If i run the import right infront of deployment 2. The import task works fine and every plan and apply run afterwards. But as soon as we redeploy everything from scratch we face this issue. 
I understand the intention of the "import existing resources" but in this case it makes clearly no sense - Terraform wants me to import a resource which gets deployed right at this moment. If i try to import it first i receive a non exisiting error. Also the id of the diag settings shows towards the application gateway.

### References

* #0000

**Comment by sebader** [comment]
had you ever created a diagnostic setting for the resource manually and then deleted the resource or resource group (and not through Terraform)? There is an issue in ARM that diagnostic settings are not deleted when deleting a resource or RG

**Comment by renereinert** [comment]
@sebader Yes we did that with the initial deployment with v1.xx

So let me summarize. We do not run Terraform destroy. Instead, we delete the RG and StateFile. However, the “DiagSettings” are stored somewhere outside the RG (you said it is an ARM issue, or is it Terraform related?). To delete this resource you need to run Terraform destroy to cover it.

So I run a few tests with this new point of view and in fact, running Terraform destroy will solve this issue. Anyway it is a little confusing and seems like a bug in the first way. Especially because it worked fine in 1.xx,

So you recommend to always destroy the resources you build with Terraform rather than deleting state file and resources via CLI or others?

**Comment by sebader** [comment]
yes, it has nothing to do with Terraform. In fact, when TF deletes resources (through tf destroy), it does it better than ARM in this case.

**Comment by renereinert** [comment]
Thank you.

running Terraform destroy will solve this issue

closed :)
