### ISSUE TITLE
Support for File Share soft delete

### ISSUE THREAD

**Issue by BzSpi** [terraform-providers/terraform-provider-azurerm#7115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure now allow to have deletion protection for File Share.
https://docs.microsoft.com/en-us/azure/storage/files/storage-files-prevent-file-share-deletion
This setting has to be set on the storage account resource.

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

There is many implementation possible, here's one to challenge:
```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  file_properties {
    share_soft_delete_retention = 42 # null by default
  }

  tags = {
    environment = "staging"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/storage/files/storage-files-enable-soft-delete?tabs=azure-powershell
* https://docs.microsoft.com/en-us/azure/storage/files/storage-files-prevent-file-share-deletion
* https://azure.microsoft.com/en-us/updates/azure-backup-now-provides-protection-against-accidental-deletion-of-azure-file-shares/

**Comment by tombuildsstuff** [comment]
@yupwei68 since this is waiting on API compatibility from the Service Team, I'm going to unmilestone this for now - please let us know when the Service Team have an update.
