### ISSUE TITLE
Way to convert FHIR API or FHIR server to swagger  in Azure API Management and terraform

### ISSUE THREAD

**Issue by swapnilbjadhav** [terraform-providers/terraform-provider-azurerm#7133]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

provider "azurerm"{
    subscription_id=var.azure_subscription_id
    client_id=var.azure_client_id
    client_secret=var.azure_client_secret
    tenant_id=var.azure_tenant_id  
version = "=2.0.0"
features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}

resource "azurerm_resource_group" "example" {
  name     = "apimanagementRG"
  location = "Central India"
}

resource "azurerm_api_management" "example" {
  name                = "fhirapimanagment"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "AzureFHIROrg"
  publisher_email     = "abc@tes.com"

  sku_name = "Developer_1"

  policy {
    xml_content = <<XML
    <policies>
      <inbound />
      <backend />
      <outbound />
      <on-error />
    </policies>
XML

  }
}

resource "azurerm_api_management_api" "example" {
  name                = "tf-fhir-api"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  revision            = "1"
  display_name        = "FHIR API"
  path                = "example"
  protocols           = ["https"]

  import {
    content_format = "swagger-link-json"
    content_value  = "https://fhirapiroles.azurehealthcareapis.com/?format=json"
  }
}

Is there any way to create the Azure FHIR API's in azure Api Mangement Service using the URL passed in the content_value of the above code.

It gives following error using Terraform:
Failed to import from specified resource https://fhirapiroles.azurehealthcareapis.com/?format=json: Response status code does not indicate success: 401 (Unauthorized).." 
and that's the correct error code but how do i get a valid swagger json?

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @swapnilbjadhav 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
