### ISSUE TITLE
azurerm_web_application_firewall_policy doc  examples are not up to date

### ISSUE THREAD

**Issue by kitkatneko** [terraform-providers/terraform-provider-azurerm#7137]
It seems that the documentation referrers to an older syntax in the example given, and so the following is not correct:

    managed_rule_set {
      rule_set_type    = "OWASP"
      rule_set_version = "3.1"
      rule_group_override {
        rule_group_name = "REQUEST-920-PROTOCOL-ENFORCEMENT"
        disabled_rules = [
          "920300",
          "920440"
        ]
      }
 

rule_set_type and rule_set_version have been replaced since 2.10 I believe. 
rule_set_type => type
rule_set_version => version

This block should say

    managed_rule_set {
      type    = "OWASP"
      version = "3.1"
      rule_group_override {
        rule_group_name = "REQUEST-920-PROTOCOL-ENFORCEMENT"
        disabled_rules = [
          "920300",
          "920440"
        ]
      }

**Comment by lrxtom2** [comment]
@kitkatneko Hi Thanks for this good issue! I have submitted a PR to fix that~
