### ISSUE TITLE
azurerm_web_application_firewall_policy should support "Microsoft_BotManagerRuleSet" current version

### ISSUE THREAD

**Issue by kitkatneko** [terraform-providers/terraform-provider-azurerm#7138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On Azure Web Application Gateway v2, earlier this year Microsoft added a new ruleset called Microsoft_BotManagerRuleSet which is version 0.1

Reference: https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/bot-protection-overview

in the managed_rules block, this should work:
 managed_rules {
    managed_rule_set {
      type    = "OWASP"
      version = "3.1"
      }
    managed_rule_set {
      type    = "Microsoft_BotManagerRuleSet"
      version = "0.1"
      }
  }

However, TF 2.12 complains to say this version is not acceptable.

TF plan and apply says: Error: expected managed_rules.0.managed_rule_set.1.version to be one of [1.0 2.2.9 3.0 3.1], got 0.1

### New or Affected Resource(s)

* azurerm_web_application_firewall_policy

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by MaxiPalle** [comment]
Really wondering, why this is missing ...

**Comment by MaxiPalle** [comment]
This is just a very small bug. Can someone pls. fix this? Maybe @tombuildsstuff you can have a short view on this?

**Comment by Lucretius** [comment]
@tombuildsstuff I was taking a look at the relevant validation functions for this and it appears they [are already there](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/validate/web_application_firewall_policy.go) so I believe this is resolved (also, PR [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7579))

**Comment by anderius** [comment]
This works, I have just used:

`managed_rules {

    managed_rule_set {
      type    = "Microsoft_BotManagerRuleSet"
      version = "0.1"
    }

    managed_rule_set {
      type    = "OWASP"
      version = "3.1"
    }
  }`
