### ISSUE TITLE
Azure azurerm_hdinsight_hadoop_cluster sample code has invalid parameter

### ISSUE THREAD

**Issue by dotIN** [terraform-providers/terraform-provider-azurerm#7143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

` terraform -v                                                                                                                       
Terraform v0.12.24
+ provider.azurerm v2.12.0
`
### Affected Resource(s)

* `azurerm_storage_container`

### Terraform Configuration Files

```hcl
provider "azurerm" {
features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "hdinsightstor"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "hdinsight"
  resource_group_name   = azurerm_resource_group.example.name
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}
```

### Expected Behavior
When I copy the example code from any resource it just works , good for reference and beginners , but for all HDI cluster creation documentation the parameter 
'resource_group_name   = azurerm_resource_group.example.name' parameter for resource 'azurerm_storage_container'  is provided which should not be the case 

Once I remove this parameter from that resource the code works 

It is a simple documentation/code Bug

### Actual Behavior

All the examples in HDI cluster documentation has 'resource_group_name   = azurerm_resource_group.example.name' parameter for resource 'azurerm_storage_container' 
This includes 
https://www.terraform.io/docs/providers/azurerm/r/hdinsight_hadoop_cluster.html
https://www.terraform.io/docs/providers/azurerm/r/hdinsight_hbase_cluster.html
https://www.terraform.io/docs/providers/azurerm/r/hdinsight_kafka_cluster.html
https://www.terraform.io/docs/providers/azurerm/r/hdinsight_spark_cluster.html

When I run terraform plan , I see below error 
`
terraform plan                                                                                                                          

Error: Unsupported argument

  on main.tf line 20, in resource "azurerm_storage_container" "example":
  20:   resource_group_name   = azurerm_resource_group.example.name

An argument named "resource_group_name" is not expected here.
`

### Steps to Reproduce

Go to https://www.terraform.io/docs/providers/azurerm/r/hdinsight_spark_cluster.html or any one of the HDI cluster documentation 
copy the Example Usage in to main.tf 
terraform init 
terraform plan or apply and we would see above error 

1. `terraform apply`

### References

* #0000

**Comment by lrxtom2** [comment]
@dotIN  Hi Thanks for opening the issue! There are issues about document. I will fix that. Thanks in advance!
