### ISSUE TITLE
Alias causes features to not be recognized

### ISSUE THREAD

**Issue by k7faq** [terraform-providers/terraform-provider-azurerm#7151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

```hcl
terraform {
  required_version = "0.12.24"
}

provider "azurerm" {
  subscription_id = lookup(var.project, "subscription_id")
  tenant_id       = var.tenant_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  version = "=2.0.0"
  alias = "this"
  features {}
}
```

```bash
+ terraform plan -out=eastus_dev_core_plan -var-file=../eastus-dev/terraform.tfvars

Error: "features": required field is not set
```

In the code sample provided, when `alias` is defined Terraform will fail and output the message `Error: "features": required field is not set`

* #0000

**Comment by jackofallops** [comment]
Hi @k7faq 
By setting an alias you are signifying that this is not the `default` provider config. You would also need a non-aliased provider block containing a `features {}` section to satisfy the requirements.

Hope this helps.
