### ISSUE TITLE
Support for Forced Tunneling / azurerm_firewall

### ISSUE THREAD

**Issue by johnwildes** [terraform-providers/terraform-provider-azurerm#7152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Forced tunneling configuration of Azure Firewall is now Generally Available.  Would be helpful if the provider supported this configuration for deployment.

### New or Affected Resource(s)

azurerm_firewall

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "firewall" {
  name     = "firewall-resources"
  location = "West US 2"
}

resource "azurerm_virtual_network" "firewall" {
  name                = "testvnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.firewall.location
  resource_group_name = azurerm_resource_group.firewall.name
}

resource "azurerm_subnet" "firewall" {
  name                 = "AzureFirewallSubnet"
  resource_group_name  = azurerm_resource_group.firewall.name
  virtual_network_name = azurerm_virtual_network.firewall.name
  address_prefix       = "10.0.1.0/24"
}

resource "azurerm_subnet" "firewall-mgmt" {
  name                 = "AzureFirewallManagementSubnet"
  resource_group_name  = azurerm_resource_group.firewall.name
  virtual_network_name = azurerm_virtual_network.firewall.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_public_ip" "firewall" {
  name                = "fw-public"
  location            = azurerm_resource_group.firewall.location
  resource_group_name = azurerm_resource_group.firewall.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_public_ip" "firewall-mgmt" {
  name                = "fw-mgmt"
  location            = azurerm_resource_group.firewall.location
  resource_group_name = azurerm_resource_group.firewall.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_firewall" "firewall" {
  name                = "testfirewall"
  location            = azurerm_resource_group.firewall.location
  resource_group_name = azurerm_resource_group.firewall.name
  forced_tunneling    = true

  public_ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.firewall.id
    public_ip_address_id = azurerm_public_ip.firewall.id
  }

  management_ip_configuration {
    name                 = "management"
    subnet_id            = azurerm_subnet.firewall-mgmt.id
    public_ip_address_id = azurerm_public_ip.firewall-mgmt.id
  }
}


```

### References
https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling

When you configure a new Azure Firewall, you can route all Internet-bound traffic to a designated next hop instead of going directly to the Internet. For example, you may have an on-premises edge firewall or other network virtual appliance (NVA) to process network traffic before it's passed to the Internet. However, you can't configure an existing firewall for forced tunneling.

By default, forced tunneling isn't allowed on Azure Firewall to ensure all its outbound Azure dependencies are met. User Defined Route (UDR) configurations on the AzureFirewallSubnet that have a default route not going directly to the Internet are disabled.

**Comment by lrxtom2** [comment]
@johnwildes Thanks for opening the issue! I will work on the issue, but sorry that there is no firm ETA for this now.

**Comment by draggeta** [comment]
@lrxtom2 Do you already start working on this and do you need any help? I need it and if wanted, I can assist you in writing this.

**Comment by lrxtom2** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/10257

**Comment by draggeta** [comment]
I believe forced tunneling is automatically possible when you have a management subnet. You just need to specify routes. Please correct me if I'm wrong.

**Comment by johnwildes** [comment]
It is not.  A separate IP address is created, a separate management subnet is created (or needs to exist) and then you have to add routes.  However, you can't build an AZFW resource without force tunneling and then add it later.  It has to be done during deployment.

**Comment by draggeta** [comment]
Sorry, that is what I meant. There is no toggle for forced tunneling like in the Azure portal. You create the subnet and ipconfig during deployment (as well as pub IP) and then forced tunneling is possible to be implemented.

**Comment by ropy1971** [comment]
Same issue here. Any updates since June 1st?
I'm deploying all Network infrastructure resources with terraform except Azure Firewall with PowerShell because Management support.

**Comment by runemy** [comment]
Other Azure resources, related to Azure Firewall, that I currently do not find any Terraform deployment options for is:
- Azure Firewall Manager Policy: https://docs.microsoft.com/en-us/azure/firewall-manager/policy-overview
- Azure Firewall IP Group: https://docs.microsoft.com/en-us/azure/firewall/ip-groups

Would be nice to get support for these also, but "Forced Tunneling" is most important.

**Comment by draggeta** [comment]
@lrxtom2 I've started work on this today and opened the pull request. If you've already started working on it, let me know and I'll close the PR.
