### ISSUE TITLE
Support for "Allow access to Azure services" configuration in PostgreSQL

### ISSUE THREAD

**Issue by evandropomatti** [terraform-providers/terraform-provider-azurerm#7153]
### Description

Azure PostgreSQL supports a property called "Allow access to Azure services" that allows for Azure resources connect to the database, useful when there is no network.

In my case I'm using an App Service with Basic plan and it doesn't support vnets, and this configuration would be handy.

![image](https://user-images.githubusercontent.com/6530769/83368595-cccf2600-a38f-11ea-9c90-6fdaf8796ebf.png)

### New or Affected Resource(s)

* azurerm_postgresql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_server" "default" {

  # ...

  allow_access_to_azure_services = true
}
```

### References

* [Connecting from Azure](https://docs.microsoft.com/en-us/azure/postgresql/concepts-firewall-rules#connecting-from-azure)

**Comment by mawippel** [comment]
I'm running into the same issue, it would be great to have this feature

**Comment by yupwei68** [comment]
Hi @evandropomatti , thanks for opening this issue. You could add a firewall rule from `0.0.0.0` to `0.0.0.0` to enable `Allow Azure services and resources to access this server group`. Example:

```
resource "azurerm_postgresql_firewall_rule" "test" {
  name                = "acctest-PSQL-fwrule-%d"
  resource_group_name = azurerm_resource_group.test.name
  server_name         = azurerm_postgresql_server.test.name
  start_ip_address    = "0.0.0.0"
  end_ip_address      = "0.0.0.0"
}
```

**Comment by evandropomatti** [comment]
Hi @yupwei68 I missed that one, it worked. Thanks for the rapid response.

I wonder how to declare dynamic firewall rules within the same `.tf` file. I would like that configuration for "dev" and "test" environments, but not for the "production" environment where I would use a vnet. I guess it would not be good practice, or is it possible to use the `dynamic` expression at the resource level?

Not related but in your example, how do I set the `%d` placeholder in "acctest-PSQL-fwrule-%d"? That would make for shorter `.yaml` files 😁

**Comment by anoff** [comment]
The proposed solution allows to activate the feature. But is there also a way to ensure it is disabled by using TF?
