### ISSUE TITLE
azure_subnet address_prefixes argument not supported in latest version

### ISSUE THREAD

**Issue by fustilarian01** [terraform-providers/terraform-provider-azurerm#7163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.0.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "my-mgmt-subnet" {
  resource_group_name = var.res_group_name
  virtual_network_name = data.azurerm_virtual_network.my-vnet.name
  address_prefixes = [var.mgmt_subnet_prefix]
  name = "management"
}
```

### Debug Output

https://gist.github.com/fustilarian01/76fe563a7900b6b8b2523b76b86fe630

### Expected Behavior

The plan would complete successfully

### Actual Behavior

I get an error saying 'An argument named "address_prefixes" is not expected here. Did you mean "address_prefix"?' Hasn't address_prefix been deprecated and replaced with address_prefixes?

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by tom-dudley** [comment]
Hi fustilarian01 - it looks like you're using the `2.0.0` provider. which doesn't support `address prefixes`. The docs on the terraform site refer to the latest release (`2.12.0`).

You can find the `2.0.0` docs here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.0.0/website/docs/r/subnet.html.markdown

**Comment by lrxtom2** [comment]
@fustilarian01 Thanks for opening the issue! In latest release that supports `[address_prefixes](https://www.terraform.io/docs/providers/azurerm/r/subnet.html#address_prefixes)` field. Please have a check. And by the way, one of address_prefix or address_prefixes is required.

**Comment by ArcturusZhang** [comment]
Hi @fustilarian01 

The `address_prefixes` has been supported in the latest version of the azure provider, therefore I would close this issue if you do not mind. 

Thank you!
