### ISSUE TITLE
NSG Association with Application Gateway v2

### ISSUE THREAD

**Issue by jgardner04** [terraform-providers/terraform-provider-azurerm#7165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.12.26`

### Affected Resource(s)

* `azurerm_subnet_network_security_group_association

### Terraform Configuration Files

```hcl
module "nsg_allow_required_manaagement_rule" {
  source = "./module/nsg-rule"

  nsg_name                    = "allow_management"
  resource_group_name         = module.rg.name
  network_security_group_name = module.nsg.name
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "TCP"
  source_port_range           = "*"
  destination_port_range      = "65200-65535"
  source_address_prefix       = "GatewayManager"
  destination_address_prefix  = "*"
}

# Associate NSG with Subnet
module "apply_nsg" {
  source = "./module/nsg-association"

  subnet_id = module.appgateway_subnet.id
  nsg_id    = module.nsg.id
}
```

### Debug Output

Error Output: https://gist.github.com/jgardner04/5eddcdb42ca44ddd079ea0409d3aeb24

### Expected Behavior

The NSG should have associated with the Subnet even with an Application Gateway v2 in the subnet

### Actual Behavior

The association threw [this](https://gist.github.com/jgardner04/5eddcdb42ca44ddd079ea0409d3aeb24) error.

### Steps to Reproduce

1. Create Vnet
2. Create Subnet
3. Create Application Gateway in Subnet
4. Create NSG
5. Create NSG rule to allow GatewayManager tagged to ports 65200-65535
6. Create NSG association 

1. `terraform apply`

### Important Factoids

When commenting out the association and creating the resources separately, then going into the portal and associating them, the NSG is associated with the subnet without issue.

**Comment by jgardner04** [comment]
This may be fixed. I am still evaluating

**Comment by magodo** [comment]
Hi @jgardner04 Thank you for submitting this :+1: 
Per the [document](https://docs.microsoft.com/en-us/azure/application-gateway/configuration-overview#network-security-groups-on-the-application-gateway-subnet):

> You must allow incoming Internet traffic on TCP ports 65503-65534 for the Application Gateway v1 SKU, and TCP ports 65200-65535 for the v2 SKU with the destination subnet as Any and source as GatewayManager service tag. This port range is required for Azure infrastructure communication.

Per your description above, you have *allow GatewayManager tagged to ports 65200-65535*. While from your error message, it indeed complaining:

> Network security group pip-nsg blocks incoming internet traffic on ports 65200 - 65535 to subnet appgateway, associated with Application Gateway appgatewaytest-ag. This is not permitted for Application Gateways that have V2 Sku

So would you please provide the terraform config of `pip-nsg` so that we can further analyze whether there is some misconfiguration in there?

**Comment by jgardner04** [comment]
@magodo below is the NSG I was using

```
resource "azurerm_network_security_group" "nsg" {
  name                = "${local.base_name}-nsg"
  location            = local.location
  resource_group_name = azurerm_resource_group.rg.name

  security_rule {
    name                       = "allow_management"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "65200-65535"
    source_address_prefix      = "GatewayManager"
    destination_address_prefix = "*"
  }
}
```

I opened an internal issue with the PG as there was some strange validation issues with an NSG on AG in the portal as well.

**Comment by jgardner04** [comment]
@magodo I had opened an internal ticket with my friends over on the portal team because there was a similar validation error on there as well. It looks like the fix for that took care of this issue and adding this NSG works now.
