### ISSUE TITLE
Change Azure Windows VM computer_name without re-creating the VM

### ISSUE THREAD

**Issue by sorbra** [terraform-providers/terraform-provider-azurerm#7169]
I am trying to change the computer_name attribute of an Azure Windows VM created with Terraform, without re-creating the VM from scratch.

The VM is running SQL server, is domain joined (domain controller provided by Azure Active Directory Domain Services (AADDS), and has a number of data disks attached.

I am using Terraform 0.12.24 and azurerm provider version 2.11.0

I have tried the following, without success:
1. Changed the os_profile.computer_name field in my Terraform template: "terraform plan" then wanted to re-create the VM.
1. Manually edited the state file (in remote storage): "terraform plan" completely ignored the change.

After the above failures, I then manually renamed the VM by logging in via RDP, and re-joined the domain. This fixed my short-term problem, but leaves me with a useless Terraform state.

I then tried:
1. Used "terraform state rm" to remove the VM from state (this worked), and then used terraform import to update the state file. The import worked, but for reasons beyond me, the imported os_profile.computer_name attribute after import contains the old name of the VM, before I manually renamed it.
1. Tried to change my template from using azurerm_virtual_machine to using azurerm_windows_virtual_machine, then "terraform state rm" followed by "terraform import". No luck.

So, back to my original need: How do I change the name of an Azure Windows VM created by Terraform, without re-creating the VM?

**Comment by ArcturusZhang** [comment]
Hi @sorbra thanks for this issue!

Unfortunately by checking [this documentation](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/update#osprofile) of REST API, it says in the `ComputerName` section
```
Specifies the host OS name of the virtual machine.

This name cannot be updated after the VM is created.

Max-length (Windows): 15 characters

Max-length (Linux): 64 characters.

For naming conventions and restrictions see Azure infrastructure services implementation guidelines.
```

Which shows that the change of compute_name is not supported by the API, therefore you will not be able to change that in terraform.

**Comment by sorbra** [comment]
Hi @ArcturusZhang. Thankyou for you response! This clarifies why I was unable to just do a Terraform "update-in-place" :).

But, I still do not understand why I cannot do a "terraform state rm" followed by "terraform import" on the VM, after I manually changed the computer name (via remote login, rather than using an API)? This seems to suggest that the API you linked to somehow cashes the computer_name, and thus returns the original computer_name to the azurerm provider, even though the computer_name was manually changed in the meantime?

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang. Thankyou for you response! This clarifies why I was unable to just do a Terraform "update-in-place" :).
> 
> But, I still do not understand why I cannot do a "terraform state rm" followed by "terraform import" on the VM, after I manually changed the computer name (via remote login, rather than using an API)? This seems to suggest that the API you linked to somehow cashes the computer_name, and thus returns the original computer_name to the azurerm provider, even though the computer_name was manually changed in the meantime?

Yeah, the computer name in the initial request may only take effect during the VM's creation, and this is one of the responsibility of the mgmt-plane operation (CRUD).

**Comment by sorbra** [comment]
Thank you!

Of course I would have preferred to be able to change the computer_name without re-creating the VM. My need for doing this is caused by a bug in my own Terraform module, that lead to multiple VM's with the same computer_name on a single domain. Which, as it turns out, is not a terribly good idea. I'll just have to stop making that kind of mistake in the future :)

**Comment by ArcturusZhang** [comment]
Since this is not an actual bug for terraform provider and the question seems resolved (though not very ideal), I will close this issue hope you do not mind. Thank you!
