### ISSUE TITLE
Feature Request:  Traffic Manager - Support TCP for monitor config protocol

### ISSUE THREAD

**Issue by WeAreGroot** [terraform-providers/terraform-provider-azurerm#717]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_traffic_manager_profile

Hopefully this is easy, just requesting that the azurerm_traffic_manager_profile resource can support TCP as an option for the protocol in monitor_config.  Thanks all.

**Comment by tombuildsstuff** [comment]
Hey @WeAreGroot 

Thanks for opening this issue - I've added support for this in #742 which should be available in the next release

Thanks!
