### ISSUE TITLE
"features": required field is not set error when using data sources

### ISSUE THREAD

**Issue by nziegler** [terraform-providers/terraform-provider-azurerm#7172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.26
+ provider.azurerm v2.12.0
+ provider.random v2.2.1

### Affected Resource(s)

* `data "azurerm_subnet"`
* `data "azurerm_virtual_network"`
### Terraform Configuration Files

```hcl
provider "azurerm" {
  alias           = "exampleprovider"
  tenant_id       = var.az_tenant_id
  subscription_id = var.az_subcription_id
  client_id       = var.az_client_id
  client_secret   = var.az_client_secret
  version         = ">=2.0.0"
  features {}
}

data "azurerm_virtual_network" "example" {
  providers = { azurerm = azurerm.exampleprovider}
  name                = "vnet1"
  resource_group_name = "rg-vnet1"
}
```

### Debug Output
https://gist.githubusercontent.com/nziegler/9cde3b928be4606678a579c3aac4eb54/raw/8cbbda00cf0b682de8f46b4ee08719b8193c61e4/debug.log

### Expected Behavior
Values from azurerm_subnet datasource should be available to use in other modules 

### Actual Behavior
Error: "features": required field is not set

### Steps to Reproduce

1. `have 2 providers using aliases`
2. `create datasource for azurerm_subnet or azurerm_virtual_network`
3. `terraform init`
4. `terraform apply`

### Important Factoids
I tried different pinned versions of the provider, but I can't go back to before 2.0.0.

### References
https://github.com/terraform-providers/terraform-provider-azurerm/issues/5867
https://github.com/MicrosoftDocs/azure-docs/issues/50961

* #0000

**Comment by tombuildsstuff** [comment]
hi @nziegler 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by nziegler** [comment]
This is not a question. When I remove the data source, the error goes away, but this makes the data sources unusable!

**Comment by nziegler** [comment]
@tombuildsstuff  Please reopen this, I tried everything, but this looks like a bug to me! It only happens when using a datasource in a module.

**Comment by tombuildsstuff** [comment]
@nziegler when using Modules you'll need to pass the Providers into it, please see this document for more information: https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly

**Comment by nziegler** [comment]
> 
> 
> @nziegler when using Modules you'll need to pass the Providers into it, please see this document for more information: https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly

That's exactly what I'm doing and the problem arises from the datasource, not the modules.
