### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert fails to assign action group, times out @ 9 mins with HTTP 503

### ISSUE THREAD

**Issue by DamonStamper** [terraform-providers/terraform-provider-azurerm#7174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24

provider "azurerm" {
    version = "~>2.5.0"
}

Provider exe is "terraform-provider-azurerm_v2.5.0_x5.exe"

### Affected Resource(s)

* `azurerm_monitor_scheduled_query_rules_alert`

### Terraform Configuration Files

```
resource "azurerm_resource_group" "example" {
  name     = "monitoring-resources"
  location = "West US"
}

resource "azurerm_monitor_action_group" "example" {
  name                = "CriticalAlertsAction"
  resource_group_name = azurerm_resource_group.example.name
  short_name          = "p0action"

  email_receiver {
    name          = "sendtoadmin"
    email_address = "admin@contoso.com"
  }
}

# Example: Alerting Action with result count trigger
resource "azurerm_monitor_scheduled_query_rules_alert" "example" {
  name                = format("%s-queryrule", var.prefix)
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  action {
    action_group           = [
		azurerm_monitor_action_group.example.id
		]
    email_subject          = "Email Header"
    custom_webhook_payload = "{}"
  }
  data_source_id = azurerm_application_insights.example.id
  description    = "Alert when total results cross threshold"
  enabled        = true
  # Count all requests with server error result code grouped into 5-minute bins
  query       = <<-QUERY
  requests
    | where tolong(resultCode) >= 500
    | summarize count() by bin(timestamp, 5m)
  QUERY
  severity    = 1
  frequency   = 5
  time_window = 30
  trigger {
    operator  = "GreaterThan"
    threshold = 3
  }
}
```
### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

azurerm_monitor_scheduled_query_rules_alert should link to     
```
action_group           = [
    azurerm_monitor_action_group.example.id
]
```

### Actual Behavior

It fails after 9 minutes and shows a 503 error.

```
terraform apply plan
azurerm_monitor_scheduled_query_rules_alert.errors: Modifying... [id=/subscriptions/00000000-0000-0000-0000-d1ee7d2038ff/resourceGroups/ResourceGroup/providers/microsoft.insights/scheduledqueryrules/company-dev-queryrule]
azurerm_monitor_scheduled_query_rules_alert.errors: Still modifying... [id=/subscriptions/00000000-0000-0000-0000-...queryrules/company-dev-queryrule, 10s elapsed]
...
azurerm_monitor_scheduled_query_rules_alert.errors: Still modifying... [id=/subscriptions/00000000-0000-0000-0000-...queryrules/company-dev-queryrule, 8m50s elapsed]
azurerm_monitor_scheduled_query_rules_alert.errors: Still modifying... [id=/subscriptions/00000000-0000-0000-0000-...queryrules/company-dev-queryrule, 9m0s elapsed]

Error: Error creating or updating Scheduled Query Rule "company-dev-queryrule" (resource group "ResourceGroup"): insights.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "{\r\n  \"error\": {\r\n    \"code\": \"The remote server returned an error: (503) Server Unavailable.\",\r\n    \"message\": {\r\n      \"lang\": \"en-US\",\r\n      \"value\": \"The remote server returned an error: (503) Server Unavailable.\"\r\n    }\r\n  }\r\n}" error: json: cannot unmarshal object into Go struct field RequestError.error of type string
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Changing the resource id to all lowercase resolves the issue. 

Change
```
action_group = [
    azurerm_monitor_action_group.example.id
    ]
```

to

```
action_group = [
    "${lower(azurerm_monitor_action_group.example.id)}"
    ]
```

**Comment by njuCZ** [comment]
@DamonStamper I am sorry I could not reproduce this issue. I could create all resources successfully using your snippet. From the log pasted, It seems you are making an update operation ? Could you please give more details?

**Comment by DamonStamper** [comment]
I was updating pre-existing resources but I can't recall if those were imported resources or ones that TF created earlier that I then changed the definitions for. This was also done in an environment where I don't have full permission but I wouldn't suspect a case change to fix that.

I'll try to recreate the behaviour again in the next few days and update with what I find.

**Comment by njuCZ** [comment]
@DamonStamper is there any updates about this issue? Could you reproduce it using the latest azurerm provider?

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but please let us know if this is still an issue using the latest version of the Azure Provider and we'll take another look.

Thanks!
