### ISSUE TITLE
terraform validate requires authentication to azure for "terraform_remote_state" data type with azurerm backend

### ISSUE THREAD

**Issue by mrbennett** [terraform-providers/terraform-provider-azurerm#7175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.0.0

### Affected Resource(s)

* "terraform_remote_state" (with backend "azurerm")

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

data "terraform_remote_state" "example_state" {
  backend = "azurerm"
  config = {
    subscription_id      = "fake-id"
    resource_group_name  = "rg-tfstate-01"
    storage_account_name = "examplestorageaccount"
    container_name       = "tfstate"
    key                  = "tfstate"
  }
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}
```

### Debug Output

[gist](https://gist.github.com/mrbennett/709a16262651e3fbaba6c1fe079a41d0)

### Expected Behavior

Terraform validate [according to the official docs](https://www.terraform.io/docs/commands/validate.html) should not access any remote services.

I checked with the s3 backend and it passes validation even without authentication to aws.

### Actual Behavior

When enabling the backend of "azurerm" on the terraform_remote_state data type and trying to run `terraform validate` in an unauthenticated context you get an error like:

```
Error: Error building ARM Config: Error retrieving the Profile from the Azure CLI: Subscription "fake-id" was not found in your Azure CLI credentials. Please verify it exists in `az account list`. Please re-authenticate using `az login`.
```

### Steps to Reproduce

You can use the sample configuration above:

1. Run `az logout` to ensure you are in an unauthenticated session
2. `terraform init` to install the providers
3. `terraform validate` to validate the terraform
4. You should get the error then, but commenting out the terraform_remote_state_block will work

**Comment by tombuildsstuff** [comment]
hi @mrbennett 

Thanks for opening this issue.

Since this is an issue with the Azure Backend, rather than the Azure Provider (which is tracked in this issue) - would you mind re-opening this on [the Terraform Core repository where the Backend is located](https://github.com/hashicorp/terraform/issues)?

Thanks!
