### ISSUE TITLE
Support for Azure Function endpoints on EventGrid Subscriptions

### ISSUE THREAD

**Issue by CodingAnarchy** [terraform-providers/terraform-provider-azurerm#7176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Functions are a supported endpoint for EventGrid subscription handling, as [described in the documentation here.](https://docs.microsoft.com/en-us/azure/event-grid/handler-functions)

Currently, `azurerm_eventgrid_event_subscription` does not support adding such a function as the endpoint.

### New or Affected Resource(s)

* azurerm_function_app
* azurerm_eventgrid_event_subscription

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "exampleResourceGroup"
  location = "West US 2"
}

resource "azurerm_eventgrid_event_subscription" "example" {
    name = "example"
    scope = azurerm_resource_group.example.id

   function_endpoint {
       function_app_id = azurerm_function_app.example.id
       function_name = "ExampleFunction"
  }
```

### References

* #0000

**Comment by jrauschenbusch** [comment]
I already started with an implementation of this. But one has to reference the function endpoint itself (by id) residing inside a function app. Hence one needs to have an already existing function with input binding type `eventGridTrigger`. As there is currently no way to create a function resource (important: `function`, not `function app`) out of the terraform-azurerm-provide, it's nearly impossible to create an acceptance test for it. Hence this would be an only manual tested feature.

One bright spot: there is also a way to deploy Azure functions via the `azure-sdk-for-go` lib. I've tested a bit using the AppsClient, but it feels like it's not a CRUD-like API. Hence it will not be that easy to write a clean resource type for it.
