### ISSUE TITLE
Support for softDeleteRetentionInDays on Key Vault

### ISSUE THREAD

**Issue by ubenmackin** [terraform-providers/terraform-provider-azurerm#7178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently we have the ability to enable Soft Delete and Purge Protection on a Key Vault resource. The API (2019-09-01) from Microsoft exposes a softDeleteRetentionInDays that can take a value >= 7 and <= 90. Being able to set this would be very beneficial, as the default of 90 days can be quite long.

### New or Affected Resource(s)

azurerm_key_vault

### Potential Terraform Configuration

soft_delete_retention_days

```hcl
resource "azurerm_key_vault" "example" {
  name                        = "testvault"
  location                    = azurerm_resource_group.example.location
  resource_group_name         = azurerm_resource_group.example.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id

  soft_delete_enabled         = true
  purge_protection_enabled    = true
  soft_delete_retention_days  = 7

  sku_name = "premium"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get",
    ]

    storage_permissions = [
      "get",
    ]
  }

  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults

**Comment by ubenmackin** [comment]
So I did a bit of research, and it looks like while this is exposed in the 2019-09-01 API, that version of the KeyVault API isn't yet available in the GO sdk, if I understand what I am seeing here:

https://github.com/Azure/azure-sdk-for-go/tree/master/services/keyvault/mgmt

Interestingly, it is available in the Python SDK:

https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-mgmt-keyvault/azure/mgmt/keyvault

So I don't know if there is a way to request the GO sdk to be updated to the newer available API version for the KeyVault resource? I know that is probably really more of a Microsoft question. But my assumption is that until the GO sdk gets updated for the new API, no progress can be made on this item.

**Comment by tombuildsstuff** [comment]
@ArcturusZhang hey - would you be able to add support for this API Version to the Go SDK? :)

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang hey - would you be able to add support for this API Version to the Go SDK? :)

Sure, I will add this package to the next minor version v43.1.0
