### ISSUE TITLE
Support for Enable Transparent Data Encryption on SQL Database 

### ISSUE THREAD

**Issue by scdesk** [terraform-providers/terraform-provider-azurerm#7187]
Hello, 

I tried browsing feature to enable Transparent Data Encryption on SQL Azure Database but I do not see any options to enable it. I can try using Json to Enable it but then its not recommended, Can you please guide here if we have any options to enable it on azure sql or help with enabling this feature.

Thank You,

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by sebader** [comment]
isn't TDE enabled by default anyway on new databases?

**Comment by SebRosander** [comment]
@mybayern1974 @sebader is correct, TDE is default on new databases. You may find it in the microsoft docs: https://docs.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-tde-overview?tabs=azure-portal

**Comment by mybayern1974** [comment]
@sebader , thank you for reminding! @scdesk , I'm removing the enhancement label by assuming what you want has been there by default. On the other hand, there could be an enhancement suggest to add the option in TF supporting both enable and disable, which could be another issue.
So would you be ok if we close this issue?

**Comment by tombuildsstuff** [comment]
👋 

Ultimately this is being tracked (for the Server, adding the DB is related) in #87 - as such I'm going to close this in favour of that issue for the moment, would you mind subscribing to that issue for updates?

Thanks!
