### ISSUE TITLE
Support for Azure Blockchain

### ISSUE THREAD

**Issue by joeydumont** [terraform-providers/terraform-provider-azurerm#7194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Blockchain is a fully managed consortium blockchain network service, currently in preview (is that an issue?). 

The main resource is a blockchain member. The REST API can be found [here][1].

Blockchain consortia could also be managed by Terraform, but I couldn't find a dedicated API for consortia (the [CLI][2] uses the generic `az resource` command to interact with consortia). That would be nice, as it would provide a way to manage the management aspects of the consortium separately from the blockchain member.

It would also be nice to be able to manage consortium invitations via Terraform, but I've only found information about using the portal or [PowerShell][4] to manage those. 

### New or Affected Resource(s)

  * azurerm_blockchain_member
  * azurerm_blockchain_member_firewall_rule (inline vs separate resource)
  * azurerm_blockchain_consortium (?, depends on API avaibility)
  * azurerm_blockchain_consortium_invitation (?, depends on API avaibility)

### Potential Terraform Configuration

```hcl
resource "azurerm_blockchain_member" "example" {
  name     = "exampleBlockchain"
  location = "eastus"
  protocol = "Quorum"
  sku      = "Basic"

  consortium {
    name        = "exampleConsortium"
    password    = var.password
    displayName = "TestConsortium"
  }

  firewall_rule {
    name  = "rule1"
    range = "192.168.0.0-255" # Needs to be parsed, API takes startIpAddress, and endIpAdress.
  }

  validatorNodesSku {
    capacity = 2
  }
}
```

### References

  * [Blockchain REST API][3]
  * [Managing blockchain consortia with the Azure CLI][2]
  * [Managing consortia with Powershell][4]

[1]: https://docs.microsoft.com/en-us/rest/api/blockchain/2019-06-01-preview/blockchainmembers/create
[2]: https://docs.microsoft.com/en-us/azure/blockchain/service/manage-cli
[3]: https://docs.microsoft.com/en-us/rest/api/blockchain/
[4]: https://docs.microsoft.com/en-us/azure/blockchain/service/manage-consortium-powershell

**Comment by tombuildsstuff** [comment]
hey @joeydumont 

[Azure Blockchain Service has been deprecated by Microsoft and will be unavailable from September 10th 2021](https://github.com/azure-deprecation/dashboard/issues/158) - as such whilst I'd like to thank you for opening this feature request - since this service is now end-of-life I'm going to close this feature-request out.

Thanks!
