### ISSUE TITLE
Api Management apis failing to create reliably

### ISSUE THREAD

**Issue by alanwales** [terraform-providers/terraform-provider-azurerm#7195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
Azure RM v2.12.0

### Affected Resource(s)

* `azurerm_api_management`

### Issue Description
The problem we are having is that we deploy the open api definitions and some work successfully, and others we see no api operations. I need to retry the deployment multiple times until it all finally works. The terraform logs always show success even when no api operations appear. This is a big issue for us as it means our api gateway is not working for around half an hour:
 
Result: no api operations
![image](https://user-images.githubusercontent.com/17590123/83647630-66c3e800-a5b5-11ea-91cd-13782e599e3f.png)

Terraform log:
azurerm_api_management_api.insurance-management-api-npd: Creation complete after 10s [id=/subscriptions/***/resourceGroups/<rg>/providers/Microsoft.ApiManagement/service/<name>/apis/insurance-management-api-npd] 
 
Result after multiple retries: success
![image](https://user-images.githubusercontent.com/17590123/83647657-6d525f80-a5b5-11ea-8aa7-f7b06fba3dde.png)

### Expected Behavior
All apis are created first time

### Actual Behavior

Multiple deletion of apis and retries is required until all are correct

**Comment by tombuildsstuff** [comment]
hi @alanwales 

Thanks for opening this issue.

Due to the way that API Management API's can be deployed (either as code, or imported from Swagger etc) there's not much for us to go on here - are you able to provide an example Terraform Configuration for us to take a look into this?

Thanks!

**Comment by alanwales** [comment]
I think this may be better handled as an Azure support ticket given the complexity of the issue but I'll try my best to explain what we are doing:

We have a Basic tier api management instance, and we have one api definition which is used to download the others:

```hcl
resource "azurerm_api_management_api" "openapi-download-api-npd" {
  name                = "openapi-download-npd"
  resource_group_name = azurerm_resource_group.gateway-persistent.name
  api_management_name = azurerm_api_management.platform.name
  revision            = "1"
  display_name        = "Download Open Api - NonProduction"
  description         = "Allows to download the open api definitions."
  path                = "npd/insurance-api/definition"
  protocols           = ["https"]
  service_url         = var.api_backend_url_npd

  import {
    content_format = "swagger-json"
    content_value  = file(abspath("api-management/apis/download-public-api.json"))
  }
}
```

Then we have the apis (5 of them) which fetch their definitions from the backend services:

```hcl
resource "azurerm_api_management_api" "insurance-public-generic-api-npd" {
  name                = "insurance-public-generic-api-npd"
  resource_group_name = azurerm_resource_group.gateway-persistent.name
  api_management_name = azurerm_api_management.platform.name
  revision            = replace(var.release_name, ".", "")
  display_name        = "Generic Insurance Api - NonProduction"
  description         = "Contains all of the endpoints to make aggregated data queries on base policy, claim and payment information."
  path                = "npd/api/insurance/v1/generic"
  protocols           = ["https"]
  service_url         = "${var.api_backend_url_npd}/api/insurance/v1/generic"

  subscription_key_parameter_names {
    header = "Subscription-Key"
    query  = "Subscription-Key"
  }

  import {
    content_format = "openapi-link"
    content_value  = var.insurance_public_generic_api_npd_link
  }
}
```

The revision is probably the only notable property: it seems that without incrementing this, terraform just ignores the api definition and does not attempt to update it, resulting in stale api definitions. Not sure if this is the recommended approach but it shouldn't be an issue in normal circumstances, cheers

**Comment by ANDMIC** [comment]
I am also noticing that when importing the api definitions from swagger (openapi-link/openapi 3.0.0 endpoint in our case), some or all operations will be missing after the terraform apply completes successfully.  In order for the full operation list to populate, re-deploying several times or going into the azure portal and import is required.

**Comment by yupwei68** [comment]
Hi @alanwales , thanks for opening this issue. I'm fixing this.

**Comment by alanwales** [comment]
It’s working now, thanks a lot!
