### ISSUE TITLE
Fail to create azurerm_kubernetes_cluster if NAT gateway is connected to subnet at time of creation

### ISSUE THREAD

**Issue by parmus** [terraform-providers/terraform-provider-azurerm#7201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.12.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

#### Failing configuration
This configuration creates the NAT gateway first, so it's connected to the subnet at the time of `azurerm_kubernetes_cluster` creation.:
```hcl
variable "subscription_id" {
  type        = string
  default     = "290907b3-e6a6-4cee-8760-828102dc619a"  # Replace with your own
  description = "Subscription ID"
}

variable "resource_group_prefix" {
  type    = string
  default = "k8-nat-first-test"
}

variable "resource_group_suffix" {
  type        = string
  default     = "01"
  description = "Use the suffix to quickly rerun experiments without waiting for deletion of previous resources"
}

variable "location" {
  type    = string
  default = "West Europe"
}


locals {
  resource_group_name = "${var.resource_group_prefix}-${var.resource_group_suffix}"
}



/**********************************************
 * Pin Terraform and Azure Provider versions
 **********************************************/
terraform {
  required_version = "= 0.12.26"
  backend "local" {
    path = "terraform.tfstate"
  }
}

provider "azurerm" {
  version = "~> 2.12.0"
  subscription_id = var.subscription_id
  features {}
}


/**********************************************
 * Resource group
 **********************************************/
resource "azurerm_resource_group" "resource_group" {
  name     = local.resource_group_name
  location = var.location
}



/**********************************************
 * Basic virtual network and subnet
 **********************************************/
resource "azurerm_virtual_network" "network" {
  name                = "${azurerm_resource_group.resource_group.name}-network"
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  address_space       = ["10.50.8.0/23"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "${azurerm_resource_group.resource_group.name}-subnet"
  resource_group_name  = azurerm_resource_group.resource_group.name
  virtual_network_name = azurerm_virtual_network.network.name
  address_prefixes     = ["10.50.8.0/24"]
  service_endpoints    = []
}



/**********************************************
 * NAT-gateway
 **********************************************/
resource "azurerm_public_ip" "nat-gateway-public-ip" {
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  name                = "nat-gateway"
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "nat-gateway-first" {
  name                  = "nat-gateway-first"
  resource_group_name   = azurerm_resource_group.resource_group.name
  location              = azurerm_resource_group.resource_group.location
  public_ip_address_ids = [azurerm_public_ip.nat-gateway-public-ip.id]
}

resource "azurerm_subnet_nat_gateway_association" "nat-gateway" {
  subnet_id      = azurerm_subnet.subnet.id
  nat_gateway_id = azurerm_nat_gateway.nat-gateway-first.id
}



/**********************************************
 * Kubernetes cluster
 **********************************************/
resource "azurerm_kubernetes_cluster" "kubernetes-cluster-last" {
  depends_on = [
    # This dependency forces the NAT gateway to be fully created first
    azurerm_nat_gateway.nat-gateway-first
  ]

  name                = "kubernetes-cluster-last"
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  dns_prefix          = "kubernetes-cluster-last"

  default_node_pool {
    name = "default"
    enable_auto_scaling = true
    min_count = 1
    max_count = 100

    vm_size = "Standard_F2"
    vnet_subnet_id = azurerm_subnet.subnet.id
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "Standard"
  }
}
```

#### Working configuration
This configuration creates the `azurerm_kubernetes_cluster` first, and then creates and connected the NAT gateway last:
```hcl
variable "subscription_id" {
  type        = string
  default     = "290907b3-e6a6-4cee-8760-828102dc619a"
  description = "Subscription ID"
}

variable "resource_group_prefix" {
  type    = string
  default = "k8-nat-last-test"
}

variable "resource_group_suffix" {
  type        = string
  default     = "01"
  description = "Use the suffix to quickly rerun experiments without waiting for deletion of previous resources"
}

variable "location" {
  type    = string
  default = "West Europe"
}


locals {
  resource_group_name = "${var.resource_group_prefix}-${var.resource_group_suffix}"
}



/**********************************************
 * Pin Terraform and Azure Provider versions
 **********************************************/
terraform {
  required_version = "= 0.12.26"
  backend "local" {
    path = "terraform.tfstate"
  }
}

provider "azurerm" {
  version = "~> 2.12.0"
  subscription_id = var.subscription_id
  features {}
}


/**********************************************
 * Resource group
 **********************************************/
resource "azurerm_resource_group" "resource_group" {
  name     = local.resource_group_name
  location = var.location
}



/**********************************************
 * Basic virtual network and subnet
 **********************************************/
resource "azurerm_virtual_network" "network" {
  name                = "${azurerm_resource_group.resource_group.name}-network"
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  address_space       = ["10.50.8.0/23"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "${azurerm_resource_group.resource_group.name}-subnet"
  resource_group_name  = azurerm_resource_group.resource_group.name
  virtual_network_name = azurerm_virtual_network.network.name
  address_prefixes     = ["10.50.8.0/24"]
  service_endpoints    = []
}



/**********************************************
 * NAT-gateway
 **********************************************/
resource "azurerm_public_ip" "nat-gateway-public-ip" {
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  name                = "nat-gateway"
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "nat-gateway-last" {
  depends_on = [
    # This dependency forces the Kubernetes cluster to be fully created first
    azurerm_kubernetes_cluster.kubernetes-cluster-first
  ]

  name                  = "nat-gateway-last"
  resource_group_name   = azurerm_resource_group.resource_group.name
  location              = azurerm_resource_group.resource_group.location
  public_ip_address_ids = [azurerm_public_ip.nat-gateway-public-ip.id]
}


resource "azurerm_subnet_nat_gateway_association" "nat-gateway" {
  subnet_id      = azurerm_subnet.subnet.id
  nat_gateway_id = azurerm_nat_gateway.nat-gateway-last.id
}



/**********************************************
 * Kubernetes cluster
 **********************************************/
resource "azurerm_kubernetes_cluster" "kubernetes-cluster-first" {
  name                = "kubernetes-cluster-first"
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  dns_prefix          = "kubernetes-cluster-first"

  default_node_pool {
    name = "default"
    enable_auto_scaling = true
    min_count = 1
    max_count = 100

    vm_size = "Standard_F2"
    vnet_subnet_id = azurerm_subnet.subnet.id
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "Standard"
  }
}
```

### Debug Output

The provided gist is from running `terraform apply` when everything but the Kubernetes cluster has been created, so Terraform should only create the cluster. This gives a shorter and more focused debug output than when Terraform is creating everything.

https://gist.github.com/parmus/fbd90ab8792f7f58221c41a2d468f196

### Expected Behavior

The Kubernetes cluster should be created correctly regardless of what else happens to be connected to the subnet. And if there is a fundamental incompatibility with Kubernetes and NAT gateway being on the same subnet the result should be the same regardless of creation order.

### Actual Behavior

When the Kubernetes cluster is created first and the NAT gateway last, then everything works fine and as expected. When inspecting the routing table created in the Kubernetes resource group, it is correctly connected to the subnet.

When the NAT gateway is created first, so it's present on the subnet at the time of creation of the Kubernetes cluster, the Kubernetes cluster creation fails with the following error:
```
Error: waiting for creation of Managed Kubernetes Cluster "kubernetes-cluster-last" (Resource Group "k8-nat-first-test-01"): Code="AssociateRouteTableToSubnetError" Message="Failed to associate route table /subscriptions/290907b3-e6a6-4cee-8760-828102dc619a/resourceGroups/mc_k8-nat-first-test-01_kubernetes-cluster-last_westeurope/providers/Microsoft.Network/routeTables/aks-agentpool-59080358-routetable to subnet /subscriptions/290907b3-e6a6-4cee-8760-828102dc619a/resourceGroups/k8-nat-first-test-01/providers/Microsoft.Network/virtualNetworks/k8-nat-first-test-01-network/subnets/k8-nat-first-test-01-subnet."
```
When inspecting the Kubernetes cluster in the Azure Portal, there's an error stating:

> This container service is in a failed state. Click here to open a new support request.

When inspecting the routing table created in the Kubernetes resource group, the routing table is not connected to the subnet.

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @parmus 

Thanks for opening this issue.

Taking a look into this, this appears to be an issue within AKS rather than something specific to Terraform - as such I'm going to suggest opening an issue on [the AKS repository](https://github.com/Azure/AKS/issues) where the AKS Team should be able to assist further/fix this.

Thanks!

**Comment by parmus** [comment]
Hi @tombuildsstuff 

This is exactly what I did first, and after many exchanges they ended up concluding that it must be a problem with Terraform:

> Thanks for sharing your findings. Please understand that AKS product group will not able to look into terraform related issues as it’s a 3rd party software, however they will look into these platform issues if there is no work around to the use cases or the user completely blocked. Gladly you found that cluster creation is successful, if nat gateway was provisioned before it.
> In this case, we were able to provision cluster with out any issues using your previous scripts. You can raise the issue in azurerm github repository so that the team can look into it for this specific use case.
> I looked at the open bugs and didn’t find any related to nat gateway and aks cluster provisioning.
> Let me know, if you have any follow up questions for me.
> Ref:
>     https://github.com/terraform-providers/terraform-provider-azurerm
 > Thank you for your support and understanding.

Now, I personally suspect that it's a problem with the Azure API, but the problem is that the `az` command doesn't seem to have this issue. This command creates _almost_ the same cluster configuration, but with two crucial differences:

1. `az` doesn't update the route table (which I actually think is wrong)
2. The `az` command succeeds, where Terraform fails.

```bash
az aks create --name kubernetes-cluster-last-az \
              --resource-group k8-nat-first-test-01 \
              -p kubernetes-cluster-last-az \
              --dns-service-ip 10.0.0.10 \
              --docker-bridge-address 172.17.0.1/16 \
              --enable-managed-identity  \
              --kubernetes-version 1.15.11 \
              --load-balancer-sku Standard \
              --location westeurope \
              --network-plugin kubenet \
              --no-ssh-key \
              --enable-cluster-autoscaler \
              --nodepool-name default \
              --node-vm-size Standard_F2 \
              --max-count 100 \
              --min-count 1 \
              --max-pods 110 \
              --outbound-type loadBalancer \
              --pod-cidr 10.244.0.0/16 \
              --service-cidr 10.0.0.0/16 \
              --vnet-subnet-id /subscriptions/290907b3-e6a6-4cee-8760-28102dc619a/resourceGroups/k8-nat-first-test-01/providers/Microsoft.Network/virtualNetworks/k8-nat-first-test-01-network/subnets/k8-nat-first-test-01-subnet --vm-set-type VirtualMachineScaleSets
```

Now, since I suspect neither Terraform nor `az` tries to explicitly mangle the routing table directly, but it probably happens on the Azure side, the question still is: Why does the Azure API do something different when called from Terraform compared to from `az`? Is Terraform doing something with the API, which it shouldn't?

**Comment by tombuildsstuff** [comment]
@parmus I can't find that issue on their repo, would you be able to share a link to the Github issue? For context an AKS Support Ticket (e.g. Microsoft/Azure Support) is handled differently to a Github issue with AKS (which goes direct to the AKS Engineering Team, who we work with as needed)

**Comment by parmus** [comment]
@tombuildsstuff I don't think there is such a ticket. My entry into Azure is through support, and I've been trying for days to get them to take my findings to the AKS Engineering Team, whom I don't have access to. Basically, the support team are seems to primarily be there to prevent information going into the organization, and I have no way of reaching the AKS Engineering Team.

**Comment by parmus** [comment]
@tombuildsstuff If you are convinced that this is not an issue with how Terraform uses the Azure API, which seems highly likely to me, do you have any contact for where to take this next?

**Comment by tombuildsstuff** [comment]
@parmus the AKS Engineering Team can be reached via Github on the AKS repository: https://github.com/Azure/AKS/issues - as such I'd suggest opening an issue there where the AKS Engineering Team should be able to take a look.

The specific error coming back here:

> Error: waiting for creation of Managed Kubernetes Cluster "kubernetes-cluster-last" (Resource Group "k8-nat-first-test-01"): Code="AssociateRouteTableToSubnetError" Message="Failed to associate route table /subscriptions/290907b3-e6a6-4cee-8760-828102dc619a/resourceGroups/mc_k8-nat-first-test-01_kubernetes-cluster-last_westeurope/providers/Microsoft.Network/routeTables/aks-agentpool-59080358-routetable to subnet /subscriptions/290907b3-e6a6-4cee-8760-828102dc619a/resourceGroups/k8-nat-first-test-01/providers/Microsoft.Network/virtualNetworks/k8-nat-first-test-01-network/subnets/k8-nat-first-test-01-subnet."

.. is an error being returned from the AKS "Create Or Update" API call - as such this is something that'd need to be fixed in the AKS API rather than something we can fix in Terraform.

As such it should be possible to reach out to the AKS Engineering Team via this Github repository: https://github.com/Azure/AKS/issues

cc @jluk for info

**Comment by parmus** [comment]
@tombuildsstuff Thank you. I'll go do that.
