### ISSUE TITLE
azurerm_frontdoor:  Ignore frontend_endpoints

### ISSUE THREAD

**Issue by frankvdbh** [terraform-providers/terraform-provider-azurerm#7208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.26
+ provider.azurerm v2.11.0

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "this" {
  lifecycle {
    ignore_changes = [
      frontend_endpoint,
      routing_rule
    ]
  }
  depends_on                                   = [azurerm_dns_cname_record.this]
  name                                         = "saas-frontdoor-${var.tenant_name}"
  resource_group_name                          = local.rg_name
  enforce_backend_pools_certificate_name_check = false
  backend_pools_send_receive_timeout_seconds   = 240 # seconds, maximum is 240
  load_balancer_enabled                        = true
  tags                                         = var.tags

  # Main forwarding rule
  routing_rule {
    name               = "base"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = concat(["default"], [for customdomain in var.ingress.custom_domains : customdomain.name])
    forwarding_configuration {
      backend_pool_name                     = "backendpool"
      cache_enabled                         = true
      cache_query_parameter_strip_directive = "StripNone"
      forwarding_protocol                   = "HttpOnly"
    }
  }

  # Redirect root url to /admin/interface.aspx
  routing_rule {
    name               = "redirectURL"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/"]
    frontend_endpoints = concat(["default"], [for customdomain in var.ingress.custom_domains : customdomain.name])
    redirect_configuration {
      redirect_type     = "Found"
      redirect_protocol = "HttpsOnly"
      custom_path       = "/admin/interface.aspx"
    }
  }


  backend_pool_health_probe {
    name                = "backendprobe"
    path                = var.api.probe_path
    protocol            = "Http"
    interval_in_seconds = 120
    enabled             = false
  }
  backend_pool_load_balancing {
    name = "backendloadbalancing"

  }
  backend_pool {
    name = "backendpool"
    backend {
      host_header = "${var.tenant_name}-origin.${var.dns_zone}"
      address     = "${var.tenant_name}-origin.${var.dns_zone}"
      http_port   = 80
      https_port  = 443
    }
    load_balancing_name = "backendloadbalancing"
    health_probe_name   = "backendprobe"
  }




  frontend_endpoint {
    name                                    = "default"
    host_name                               = "saas-frontdoor-${var.tenant_name}.azurefd.net"
    custom_https_provisioning_enabled       = false
    web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.this.id
  }

  # Custom domains based on variable. 
  dynamic "frontend_endpoint" {
    for_each = var.ingress.custom_domains
    content {
      name                              = frontend_endpoint.value.name
      host_name                         = frontend_endpoint.value.domain
      custom_https_provisioning_enabled = true
      custom_https_configuration {
        certificate_source = "FrontDoor"
      }
      web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.this.id
    }
  }
```

### Expected Behavior

We are creating a front door resource with x number of custom domains ("frontend endpoints") during tenant creation with terraform.
Afterwards the front door configuration is modified manually in Azure Portal / API to add additional custom domains.
For this reason we want to ignore the custom domain related properties in terraforms lifecycle block. 
We expected to use ignore changes functionality to ignore frontend_endpoint and routing_rule blocks once FrontDoor is created. 

### Actual Behavior

The problem is that as soon as we ignore the routing_rule blocks the terraform plan or apply errors out with this error:

Error: creating Front Door "saas-frontdoor-sandbox1" (Resource Group "saas-tenant-sandbox1"): "routing_rule":base" "frontend_endpoints":"" was not found in the configuration file. verify you have the "frontend_endpoint":"" defined in the configuration file

Same behavior with ignore 'all' setting.

### Steps to Reproduce

1.  Add e.g. ignore_changes = all to an existing FrontDoor resource. 

2. `terraform plan or apply`
* #0000

**Comment by vivaladan** [comment]
Running tf 0.12.28 and azurerm 2.18.0 I get the following (hopefully similar) issue when using `ignore_changes = all` on the `azurerm_frontdoor` resource.

I'm having to manually enable https on the endpoints due to #6351 and then I want to ignore those changes. Ignoring `frontend_endpoint` directly caused a whole load of other things it wanted to change so I'm attempting to ignore the whole resource now.

`Error: creating Front Door "***" (Resource Group "***"): routing_rule defaultForwardingRoute is invalid. "backend_pool_name" cannot be empty`

**Comment by lyubomirr** [comment]
Any update on this?
