### ISSUE TITLE
Sql Server "public_network_access_enabled" not mentioned in docs

### ISSUE THREAD

**Issue by ross-p-smith** [terraform-providers/terraform-provider-azurerm#7219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform: v0.12.7
AzureRM: v2.11.0

### Affected Resource(s)
azurerm_sql_server

### Expected Behavior

Documentation should include details about "public_network_access_enabled", but there is no mention of it and it was released in 2.8.0 of AzureRM provider

### Actual Behavior

No mention in the docs of "public_network_access_enabled"

### Steps to Reproduce

https://www.terraform.io/docs/providers/azurerm/r/sql_server.html

**Comment by magodo** [comment]
The `public_network_access_enabled` property is not available in `sql_server`, but available in [`mssql_server`](https://www.terraform.io/docs/providers/azurerm/r/mssql_server.html#public_network_access_enabled).
(FWIK, the `mssql_server` is superseding the `sql_server`)
