### ISSUE TITLE
change in subscription - getting 404 now

### ISSUE THREAD

**Issue by donfouts** [terraform-providers/terraform-provider-azurerm#7220]
so last time i ran terraform init with the azurerm provider i had a different subcription, different service princaple, different directory, different main.tf file   - it worked

but i changed all of those things (also updated to 0.12.26)

updated my variables
export ARM_CLIENT_ID="....."
export ARM_CLIENT_SECRET="...."
export ARM_SUBSCRIPTION_ID="...."
export ARM_TENANT_ID="...."

i am in a brand new directory on my local laptop:

main.tf (only the provider part as it doesn't pass this)

```
provider "azurerm" {
  alias = "westus"
  version = "=2.0.0"
}

terraform {
  backend "azurerm" {
    resource_group_name  = "westus_5_i_rnd_rg"
    storage_account_name = "..."
    container_name       = "..."
    key                  = "..."
  }
}

# Create a resource group
.....
```
and i am getting an error on error
_m$ terraform init

Initializing the backend...

Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "dsoterraformstate": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'RG-AZDSO-WUS' could not be found."_

this resource group listed in the error was from my old subscription where i was holding the statefiles before - that doesn't exist in the new subscription so obviously it is getting a 404....

but how do i clear this  - so it takes the vaules in my current main.tf file? 

if i do a workspace list i get the same error:

_m$ terraform workspace list
Error retrieving keys for Storage Account "dsoterraformstate": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'RG-AZDSO-WUS' could not be found."_

this storage account and resource group don't exist in my new subscription: the credentials ARM_CLIENT_ID="....."
ARM_CLIENT_SECRET="...."
ARM_SUBSCRIPTION_ID="...."
ARM_TENANT_ID="...."

don't have access to the Resource group 'RG-AZDSO-WUS or
Storage Account "dsoterraformstate"

but those two values are not in the .tf file anywhere. 
![image](https://user-images.githubusercontent.com/12280845/83830812-dd86e100-a69a-11ea-8dcc-cc97f3ab6cd0.png)

my understanding is if i have different folders with different main.tf files: those different directories only have one (but different) provider - terraform should initialize the backend only in that directory? what should i be checking that i did wrong?

thanks

**Comment by tombuildsstuff** [comment]
hi @donfouts 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by russews** [comment]
@donfouts I hit the same error earlier, running `terraform init -reconfigure` resolved it in my case.
