### ISSUE TITLE
Can not parse id values between separate configuration files without using interpolation syntax

### ISSUE THREAD

**Issue by PXPJamesCook** [terraform-providers/terraform-provider-azurerm#7225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When working with multiple configuration files, calling particular resource ids (listed in affected resources) from other configuration files generate errors (listed in actual behavior). Quotation used as per articles but only way to resolve is to use the older interpolation syntax but this pops up warnings when deploying.

### Terraform (and AzureRM Provider) Version

Terraform v0.12.25
+ provider.azurerm v2.12.0

### Affected Resource(s)

azurerm_backup_protected_vm
azurerm_site_recovery_replicated_vm

### Terraform Configuration Files

```
resource "azurerm_backup_protected_vm" "bkp_pro_vm_kp" {
  resource_group_name = "azurerm_resource_group.resource_gp_kp.name"
  recovery_vault_name = azurerm_recovery_services_vault.rec_srv_vlt_kp.name
  source_vm_id        = "azurerm_virtual_machine.vm_win_kp.id"
  backup_policy_id    = azurerm_backup_policy_vm.bkp_pol_vm_kp.id
}

resource "azurerm_site_recovery_replicated_vm" "sit_rec_rep_vm_kp" {
  name                                      = "site-replication"
  resource_group_name                       = "azurerm_resource_group.resource_gp_kp_rep.name"
  recovery_vault_name                       = azurerm_recovery_services_vault.rec_srv_vlt_kp.name
  source_recovery_fabric_name               = azurerm_site_recovery_fabric.sit_rec_fab_kp_pri.name
  source_vm_id                              = "azurerm_virtual_machine.vm_win_kp.id"
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.sit_rec_rep_pol_kp.id
  source_recovery_protection_container_name = azurerm_site_recovery_protection_container.sit_rec_pro_con_kp_pri.name

  target_resource_group_id                = "azurerm_resource_group.resource_gp_kp_rep.id"
  target_recovery_fabric_id               = azurerm_site_recovery_fabric.sit_rec_fab_kp_sec.id
  target_recovery_protection_container_id = azurerm_site_recovery_protection_container.sit_rec_pro_con_kp_sec.id

  managed_disk {
    disk_id                    = "azurerm_virtual_machine.vm_win_kp.storage_os_disk[0].managed_disk_id"
    staging_storage_account_id = "azurerm_storage_account.stor_acc_kp.id"
    target_resource_group_id   = "azurerm_resource_group.resource_gp_kp_rep.id"
    target_disk_type           = "Standard_LRS"
    target_replica_disk_type   = "Standard_LRS"
  }
}
```

### Expected Behavior

Anything with "azurerm_......id" (quotes around the values) will grab id values produced by the other configuration files

### Actual Behavior

Following example output (from resource "azurerm_backup_protected_vm"):

_"Error: Can not parse "source_vm_id" as a resource id: Cannot parse Azure ID: parse "azurerm_virtual_machine.vm_win_kp.id": invalid URI for request"_

### Steps to Reproduce

1. create configuration file with resource azure_virtual_machine
2. create another configuration file with resource azurerm_backup_protected_vm
3. where source_vm_id, enter syntax for azure_virtual_machine in the following format "azurerm_virtual_machine.vmname.id"
4. terraform plan

### Workaround

If I use the interpolation syntax "${azurerm_virtual_machine.vmname.id}" I do not receive the same error but get the following warning:

_"Warning: Interpolation-only expressions are deprecated"_

**Comment by tombuildsstuff** [comment]
hi @PXPJamesCook 

Thanks for opening this issue.

When moving from the older interpolation syntax to the newer syntax you can drop the quotes entirely, to use a cut-down version of your Terraform Configuration:

```hcl
resource "azurerm_backup_protected_vm" "bkp_pro_vm_kp" {
  resource_group_name = "azurerm_resource_group.resource_gp_kp.name"
  # ...
}

# ...
```

to this:

```hcl
resource "azurerm_backup_protected_vm" "bkp_pro_vm_kp" {
  resource_group_name = azurerm_resource_group.resource_gp_kp.name
  # ...
}

# ...
```

Would you be able to take a look and see if that works for you?

The first code-block above shows the value `"azurerm_virtual_machine.vmname.id"` - which is a string literal, meaning this'll be passed without interpolation (which is why you're getting this validation error saying this isn't a Resource ID). By contrast the second code block is the newer interpolation syntax, meaning this'll be transformed to the Resource ID (and matches the older format `"${azurerm_virtual_machine.vmname.id"}`).

Since this should be fixed by removing the quotes I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
