### ISSUE TITLE
[Bug] Logic App workflow should allow parameters to be any object (not just strings)

### ISSUE THREAD

**Issue by rrmistry** [terraform-providers/terraform-provider-azurerm#7241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.25
+ provider.archive v1.3.0
+ provider.azurerm v2.12.0
+ provider.null v2.1.2
```

### Affected Resource(s)

[`azurerm_logic_app_workflow`](https://www.terraform.io/docs/providers/azurerm/r/logic_app_workflow.html#parameters)

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_workflow" "default" {
  name                = var.name
  resource_group_name = data.azurerm_resource_group.default.name
  location            = data.azurerm_resource_group.default.location
  tags                = var.az_tags
  parameters = {
    # the parameter "environment" is of type "Object" in the definition
    environment = {
      subscriptionId = data.azurerm_subscription.default.subscription_id
      tenantId       = data.azurerm_subscription.default.tenant_id
      resourceGroup  = data.azurerm_resource_group.default.name
      datacenter     = data.azurerm_resource_group.default.location
    }
  }
}

data "azurerm_subscription" "default" {}
data "azurerm_resource_group" "default" {
  name = var.az_resource_group
}
```

There are items we cannot control, for which we need to have object type parameters.

Logic App definitions clearly allow objects to be passed as parameters:
![image](https://user-images.githubusercontent.com/25514145/83957244-6e44f480-a834-11ea-8583-4af42b108172.png)

Documentation: https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-workflow-definition-language#parameters

Schema reference: https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#

### Output

```
Error: Incorrect attribute value type

  on .terraform\modules\logicapp_dbEnvironment\main.tf line 11, in resource "azurerm_logic_app_workflow" "default":
2020-06-07T00:31:59.347Z [DEBUG] plugin: plugin process exited: path=C:\terraform\terraform-provider-azurerm_v2.12.0_x5.exe pid=23536
  11:   parameters          = 2020-06-07T00:31:59.347Z [DEBUG] plugin: plugin exited
var.parameters
    |----------------
    | var.parameters is object with 6 attributes

Inappropriate value for attribute "parameters": element "environment": string
required.
```

### Expected Behavior

Allow objects to be passed as parameters in logic app workflows

### Actual Behavior

Only string parameters are allowed in logic app workflows

### Steps to Reproduce

1. Use HCL provided above
1. `terraform apply`

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/5197
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/1691

**Comment by Tbohunek** [comment]
Hi, any chance of getting an ETA?
