### ISSUE TITLE
Error creating/updating IoT Device Provisioning Service "IotHubTF-DPS"

### ISSUE THREAD

**Issue by harshita3199** [terraform-providers/terraform-provider-azurerm#7242]
**Description:**
I am trying to create a IOT Device Provisioning Service in Azure using Terraform vs 0.12.26 in **F1** free tier then I am encountered with an error:
**Error creating/updating IoT Device Provisioning Service "IotHubTF-DPS" (Resource Group "myTFResourceGroup"): iothub.IotDpsResourceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: C into Go struct field serviceError2.code of type string"} AdditionalInfo=[{"code":400059,"httpStatusCode":"Bads correlation identifier: 5c7f6de0-2c0b-4f6a-9e37-1435ab6050c7, timestamp: 2020-06-07 20:44:14Z, errorcode: IH400059."}]**

But it gets successfully created in **S1** tier. I have used the sku names as per the terraform documentation. 
Is there anything which is getting wrong?? 

Also, attaching the screenshot of my code for reference.

**Code:**
#Create a IOT Device Provisioning Service
resource "azurerm_iothub_dps" "harshi" {
  name                = "IotHubTF-DPS"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  sku {
    name     = "F1"
    capacity = "1"
  }
}

Screenshot:
![Iot-dps](https://user-images.githubusercontent.com/39816522/83980406-25279a00-a933-11ea-97c3-e41aaa1b2c93.PNG)

**Comment by xuzhang3** [comment]
Hi @harshita3199. I can reproduce your error. This is bug when SKU is configured with `F1`. I will follow up this issue.

**Comment by harshita3199** [comment]
Hello @xuzhang3. Is there any update about this issue?

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. According by latest error message, it indicates the request parameter is invalid. After do more investigation, I found seems iothub dps api only supports `S1`. [Azure rest api doc](https://docs.microsoft.com/en-us/rest/api/iot-dps/iotdpsresource/createorupdate#iotdpssku) and [azure cli doc](https://docs.microsoft.com/en-us/cli/azure/iot/dps?view=azure-cli-latest#az-iot-dps-create) also indicates iothub dps api only supports S1. So I made a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7847). Hopes it would be helpful.

Error message:
```
{"code":400059,"httpStatusCode":"BadRequest","message":"Request body validation failed. If you contact a support representative please include this correlation identifier: xx-xx-xx-xx, timestamp: 2020-07-22 07:17:05Z, errorcode: IH400059."}
```
