### ISSUE TITLE
Error for multiple email addresses in Azure Security Center contacts

### ISSUE THREAD

**Issue by stefan-rapp** [terraform-providers/terraform-provider-azurerm#7247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azurerm v2.13.0
```

### Affected Resource(s)

* `azurerm_security_center_contact`

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_contact" "example" {
  email = "contact@example.com,test@example.com,test01@example.com"
  phone = "+1-555-555-5555"

  alert_notifications = true
  alerts_to_admins    = true
}
```

### Expected Behavior

Multiple (comma separated) email addresses can be added to the Azure Security Center email notifications, like the following screenshot illustrates.

![mail_notification_asc](https://user-images.githubusercontent.com/45358082/84005932-35a93600-a96e-11ea-8885-f806f97e49b1.png)

### Actual Behavior

```
Error: Error updating Security Center Contact: security.ContactsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidInputJson" Message="Invalid security contact Email was provided."

  on ..\..\..\..\Modules\Azure\ASC\ASC_Contact\main.tf line 1, in resource "azurerm_security_center_contact" "asc_contact":
   1: resource "azurerm_security_center_contact" "asc_contact" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

-

### References

-

**Comment by lrxtom2** [comment]
Hi @stefan-rapp , Thanks for opening the issue! 
Seems that API don't supports the feature. I have opened the issue about that. 
https://github.com/Azure/azure-rest-api-specs/issues/9772

**Comment by njuCZ** [comment]
duplicated as #9462
