### ISSUE TITLE
Azure Storage Account creation is stuck in state 'creating'

### ISSUE THREAD

**Issue by olblak** [terraform-providers/terraform-provider-azurerm#725]
### Terraform Version
Terraform v0.11.2
+ provider.azurerm v1.0.1
+ provider.random v1.1.0

### Affected Resource(s)
- azurerm_storage_account

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "example" {
    name     = "${var.prefix}-example"
    location = "East US"
}

resource "azurerm_storage_account" "example" {
    name                     = "${var.prefix}example"
    resource_group_name      = "${azurerm_resource_group.example.name}"
    location                 = "East US"
    account_tier             = "Standard"
    account_replication_type = "GRS"

    custom_domain {
        name = "${var.prefix == "production" ? "example.com" : ""}"
    }
}
```

### Panic Output
/

### Expected Behavior
If var.prefix == production
This resource should be deploy correctly with custom_domain set to 'example.com' 
else
This resource should be deploy correctly without custom_domain 

### Actual Behavior
If var.prefix == production
This resource is correctly deployed with custom_domain set to 'example.com'
else
This resource is stuck in the state 'creating'. 

### Steps to Reproduce
1. terraform apply

### Important Factoids
/

### References
/

**Comment by JunyiYi** [comment]
Hi @olblak , I'm not able to reproduce it anymore. Could you please try with the latest version and see whether it is still reproducible.

The steps I run: `terraform apply` with `var.prefix` set to `staging`, it is provisioned in 20 seconds.
But when I try `production`, it reports failure: `CNAME mapping from example.com to any of sa.blob.core.windows.net does not exist`. Maybe this indicates some configuration error in you HCL file?

**Comment by olblak** [comment]
Hi @JunyiYi,
I'll try when I have time for this, thanks for you investigation

**Comment by olblak** [comment]
Hi @JunyiYi,
It seems to be fixed now 
Thanks
