### ISSUE TITLE
Replace conflict setting of availability_set and zone on virtual_machine resources

### ISSUE THREAD

**Issue by gek0** [terraform-providers/terraform-provider-azurerm#7250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

update of existing resources
* azurerm_linux_virtual_machine
* azurerm_windows_virtual_machine

### Provider code
Linux VM
* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/compute/linux_virtual_machine_resource.go#L118
* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/compute/linux_virtual_machine_resource.go#L240

Windows VM
* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/compute/windows_virtual_machine_resource.go#L120
* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/compute/windows_virtual_machine_resource.go#L261

### Potential Terraform Configuration

```hcl
# example deployment of VMs in AZ setup - allow setting null/empty AS ID
resource "azurerm_*_virtual_machine" "example" {
    ...
    availability_set_id = null / ""
    zone = "<ZONE_ID>"
    ...
}

# or if current does not support AZ setup - fallback to AS for HA and set AZ to null/blank
resource "azurerm_*_virtual_machine" "example" {
    ...
    availability_set_id = azurerm_availability_set.example.id
    zone = null / ""
    ...
}
```

### Use case
Fallback to Availability Set deployment if Availability Zone redundancy is not available in current location/region.
We are trying to write a module for deploying virtual machines in Azure and to write it as DRY as possible.
With current limitations - `availability_set_id` and `zone` attributes are conflicted and cannot be defined under the same resource type. Neither as dynamic content and neither as null/blank string/boolean (as false) so that only one is used and others ignored.

I can understand that this is a limitation on Azure API, but I would like to be able to define both attributes - with only one of them being set to some value at a time. This way we wouldn't need to define the same `azurerm_*_virtual_machine` resource with repeated attributes

Proposal? Changing the provider validation to fail/scream only if both are set. Else ignore `null/""/false` values, whichever makes the most sense to you.

What do you think? I could update the provider via PR if this is a viable option and makes sense to you as well.

**Comment by gek0** [comment]
@tombuildsstuff I've made some changes that should allow this case, but I'm failing to push the changes to my branch (`issue_7250`) due to not enough permissions. Is it due to branch naming or?

If not, here is the diff I've made so you can check it out? Thanks! :) 

```diff
diff --git a/azurerm/internal/services/compute/linux_virtual_machine_resource.go b/azurerm/internal/services/compute/linux_virtual_machine_resource.go
index d7d6e4551..5bb58749c 100644
--- a/azurerm/internal/services/compute/linux_virtual_machine_resource.go
+++ b/azurerm/internal/services/compute/linux_virtual_machine_resource.go
@@ -115,7 +115,6 @@ func resourceLinuxVirtualMachine() *schema.Resource {
 				// availability_set_id:                 "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-200122113424880096/providers/Microsoft.Compute/availabilitySets/ACCTESTAVSET-200122113424880096" => "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-200122113424880096/providers/Microsoft.Compute/availabilitySets/acctestavset-200122113424880096" (forces new resource)
 				ConflictsWith: []string{
 					"virtual_machine_scale_set_id",
-					"zone",
 				},
 			},
 
@@ -237,7 +236,7 @@ func resourceLinuxVirtualMachine() *schema.Resource {
 				// and if the VMSS in not zonal, this value should be left empty
 				Computed: true,
 				ConflictsWith: []string{
-					"availability_set_id",
+					"virtual_machine_scale_set_id",
 				},
 			},
 
@@ -393,6 +392,10 @@ func resourceLinuxVirtualMachineCreate(d *schema.ResourceData, meta interface{})
 	}
 
 	if v, ok := d.GetOk("availability_set_id"); ok {
+		// dont allow setting availability_set_id attribute if using Availbility Zone deployment model
+		if v, ok := d.GetOk("zone"); ok && v.(string) != "" {
+			return fmt.Errorf("`availability_set_id` cannot be used/set if `zone` is set and likewise")
+		}
 		params.AvailabilitySet = &compute.SubResource{
 			ID: utils.String(v.(string)),
 		}
@@ -441,6 +444,10 @@ func resourceLinuxVirtualMachineCreate(d *schema.ResourceData, meta interface{})
 	}
 
 	if v, ok := d.GetOk("zone"); ok {
+		// dont allow setting zone attribute if using Availbility Sets deployment model
+		if v, ok := d.GetOk("availability_set_id"); ok && v.(string) != "" {
+			return fmt.Errorf("`zone` cannot be used/set if `availability_set_id` is set and likewise")
+		}
 		params.Zones = &[]string{
 			v.(string),
 		}
@@ -529,6 +536,10 @@ func resourceLinuxVirtualMachineRead(d *schema.ResourceData, meta interface{}) e
 
 	availabilitySetId := ""
 	if props.AvailabilitySet != nil && props.AvailabilitySet.ID != nil {
+		// cannot use availability set and zones in the same time
+		if resp.Zones != nil {
+			return fmt.Errorf("Error setting `availability_set_id` if `zone` is used")
+		}
 		availabilitySetId = *props.AvailabilitySet.ID
 	}
 	d.Set("availability_set_id", availabilitySetId)
@@ -627,6 +638,10 @@ func resourceLinuxVirtualMachineRead(d *schema.ResourceData, meta interface{}) e
 
 	zone := ""
 	if resp.Zones != nil {
+		// cannot use availability set and zones in the same time
+		if props.AvailabilitySet.ID != nil {
+			return fmt.Errorf("Error setting `zone` if `availability_set_id` is used")
+		}
 		if zones := *resp.Zones; len(zones) > 0 {
 			zone = zones[0]
 		}
```

**Comment by gek0** [comment]
@tombuildsstuff any updates on this?
I would like to create a PR for this but have no push rights - are there any restrictions on branch/commit name? if yes, what are they?
Anything missing in this change?
I would really like to implement this to keep the VM module as DRY as possible.

Defining an additional duplicate `azurerm_linux_virtual_machine` or `azurerm_windows_virtual_machine` resource and IF condition it with for_each/count just for the sake of 1 attribute is not nice :/ 
I believe that provider should not be in a way of API limitations - it should allow those values - point them in the documentation and leave the API to report an error and fail

**Comment by tombuildsstuff** [comment]
hi @gek0 

Thanks for opening this issue.

Whilst Azure (and subsequently Terraform) don't allow these fields to be set together - it's possible to use a single resource to represent this (as they are today) using a coalesce statement - for example:

```
variable "availability_set_id" {
  default = ""
  description = "The ID of an existing Availability Set"
}

variable "zone" {
  default = ""
  description = "The Zone in which this Virtual Machine should exist"
}

resource "azurerm_*_virtual_machine" "example" {
    ...
    availability_set_id = var.availability_set_id != "" ? var.availability_set_id : null
    zone = var.zone != "" ? var.zone : null
}
```

In the example above, passing in a value for the variable `availability_set_id` or `zone` will set only that field in the resource - whilst the resource validation will capture both being inadvertently set - would you be able to take a look and see if this works for you?

Since this use-case is supported with the existing resources today, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by gek0** [comment]
@tombuildsstuff thanks for pointing that out!
Yes, looks like the problem was that I've tried setting the value to a blank string instead of null value in our IF case

Example you stated does work. Will change the IF statement, thank you!
