### ISSUE TITLE
Support for publicNetworkAccess property on resource azurerm_search_service

### ISSUE THREAD

**Issue by jamiefrench** [terraform-providers/terraform-provider-azurerm#7255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This value can be set to 'enabled' to avoid breaking changes on existing customer resources and templates. If set to 'disabled', traffic over public interface is not allowed, and private endpoint connections would be the exclusive access method.

### New or Affected Resource(s)

* azurerm_search_service

### Potential Terraform Configuration

```
resource "azurerm_search_service" "example" {
  name                            = "example-search-service"
  resource_group_name = azurerm_resource_group.example.name
  location                        = azurerm_resource_group.example.location
  sku                               = "standard"

  public_network_access = false
}
```

### References

* https://docs.microsoft.com/en-us/azure/templates/microsoft.search/searchservices#searchserviceproperties-object

**Comment by lrxtom2** [comment]
@jamiefrench Hi, Thanks for opening the great issue! We are working on the go-sdk for implement the future. After new version go-sdk is released, we will implement it immediately. Thanks for that.

**Comment by lrxtom2** [comment]
https://github.com/Azure/sdk-release-request/issues/454
