### ISSUE TITLE
The network_profile.outbound_type setting forces replacement of kubernetes cluster

### ISSUE THREAD

**Issue by 0x7f** [terraform-providers/terraform-provider-azurerm#7262]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.26
+ provider.azurerm v2.13.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
  name                = var.cluster_name
  location            = var.location
  resource_group_name = var.resource_group_name
  dns_prefix          = replace(var.cluster_name, "/[-_]/", "")
  kubernetes_version  = var.kubernetes_version
  node_resource_group = var.node_resource_group

  role_based_access_control {
    enabled = true
  }

  enable_pod_security_policy = true

  default_node_pool {
    ...
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "Basic"
  }

  service_principal {
    client_id     = var.cluster_service_principal_client_id
    client_secret = var.cluster_service_principal_client_secret
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

When having an already existing cluster, upgrading to latest terraform (at least 2.5.0) should not require recreating my AKS cluster.

### Actual Behavior

The PR #6120 introduced support for the `network_profile.outbound_type` field. The value must be either `loadBalancer` or `userDefinedRouting`. When checking my current tfstate file, the value is set to empty string. When running `terraform plan`, the output shows that the cluster must be recreated due to that setting (no other settings are marked with `forces replacement`):

```
...
      ~ network_profile {
          ~ dns_service_ip     = "10.0.0.10" -> (known after apply)
          ~ docker_bridge_cidr = "172.17.0.1/16" -> (known after apply)
            load_balancer_sku  = "Basic"
            network_plugin     = "kubenet"
          + network_policy     = (known after apply)
          + outbound_type      = "loadBalancer" # forces replacement
          ~ pod_cidr           = "10.244.0.0/16" -> (known after apply)
          ~ service_cidr       = "10.0.0.0/16" -> (known after apply)

          + load_balancer_profile {
              + effective_outbound_ips    = (known after apply)
              + managed_outbound_ip_count = (known after apply)
              + outbound_ip_address_ids   = (known after apply)
              + outbound_ip_prefix_ids    = (known after apply)
            }
        }
...
```

Is there any way to get around the recreation of the cluster?

### Steps to Reproduce

1. Create a Kubernetes cluster with an old version of terraform using the settings listed above
2. Upgrade to latest terraform (at least `2.5.0`)
3. Run `terraform plan`

### Important Factoids

N/A

### References

* #5757
* #6120

**Comment by anirbansingharoy** [comment]
I am facing the same issue.  AKS cluster created on provider version `2.0.0` getting recreated after upgrade to `2.13.0`.

I also tried with removing the terraform state and importing it back again but that didn't helped

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems the issue has gone since I cannot repro it with below tfconfig and repro steps. Maybe I missed something. Could you have a try below tfconfig to check whether the issue still exists? Thanks.

Repro steps:
1. Create resource with provider version 2.0.0
```
provider "azurerm" {
  features {}
  version = "2.25.0"
}

resource "azurerm_resource_group" "example" {
  name     = "examplerg-aks-test01"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "example-law-test01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks-test01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "examplednsprefix"

  role_based_access_control {
    enabled = true
  }

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "Basic"
  }

  service_principal {
    client_id     = "xxxxx"
    client_secret = "xxxxx"
  }
}
```
2. Run `tf plan`
![image](https://user-images.githubusercontent.com/19754191/92081520-c79dcf00-edf5-11ea-8c60-01c55e7b3ad1.png)

3.Upgrade provider version from 2.0.0 to 2.25.0
4. Run `tf plan`
![image](https://user-images.githubusercontent.com/19754191/92081585-dc7a6280-edf5-11ea-967c-d0cf336ceb31.png)

**Comment by 0x7f** [comment]
@tombuildsstuff can confirm that it is working as expected now 👍
