### ISSUE TITLE
Support for permanent delete

### ISSUE THREAD

**Issue by Nilsas** [terraform-providers/terraform-provider-azurerm#7282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Log analytics workspace are now soft-deleted every time you `terraform destroy` it. For some cases we'd need a reliable way to destroy it and be able to create it with the same name.
Documentation here: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/delete-workspace#permanent-workspace-delete

### New or Affected Resource(s)

* azurerm_log_analytics_workspace

### Potential Terraform Configuration

I imagine this being part of the provider `features{}` block similar to `key_vault` block. 

```hcl
provider "azurerm" {
  features {
    log_analytics_workspace {
         purge_soft_delete_on_destroy = true
    }
  }
}
```

**Comment by brandonh-msft** [comment]
Where are we at on this? It's a constant source of pain for our team as we're doing development. we're on iteration #4 of our dev environment and keep having to change resource names solely because of this issue.

**Comment by mathieubrd** [comment]
Any update on this?

The workaround we found is to use a `random_integer` for the log analytics workspace.

**Comment by ahmddp** [comment]
Hi, any update on this issue?
