### ISSUE TITLE
azurerm_virtual_hub_connection resource fails when connection is recreated

### ISSUE THREAD

**Issue by jrominesf** [terraform-providers/terraform-provider-azurerm#7284]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
provider.azurerm v2.13.0

### Affected Resource(s)

* `azurerm_virtual_hub_connection`

### Terraform Configuration Files

```hcl
variable "subscription_id" {}

provider "azurerm" {
  subscription_id = var.subscription_id
  features {}
}

resource "azurerm_resource_group" "rg" {
  provider = azurerm
  name     = "vwan-issue-rg"
  location = "westus2"
}

resource "azurerm_virtual_wan" "vwan" {
  provider                   = azurerm
  name                       = "vwan-issue-vwan"
  resource_group_name        = azurerm_resource_group.rg.name
  location                   = azurerm_resource_group.rg.location
  allow_vnet_to_vnet_traffic = true
  tags = {
    env = "dev"
  }
}

resource "azurerm_virtual_hub" "vhub" {
  provider            = azurerm
  name                = "vwan-issue-vhub"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  virtual_wan_id      = azurerm_virtual_wan.vwan.id
  address_prefix      = "172.17.2.0/24"
  tags = {
    env = "dev"
  }
}

resource "azurerm_virtual_network" "vnet" {
  provider            = azurerm
  name                = "vwan-issue-vnet"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  address_space       = ["10.127.224.0/19"]
}

resource "azurerm_virtual_hub_connection" "vwanpeering" {
  provider                                       = azurerm
  name                                           = "${azurerm_virtual_network.vnet.name}-conn"
  virtual_hub_id                                 = azurerm_virtual_hub.vhub.id
  remote_virtual_network_id                      = azurerm_virtual_network.vnet.id
  hub_to_vitual_network_traffic_allowed          = false
  vitual_network_to_hub_gateways_traffic_allowed = false
  internet_security_enabled                      = false
}

```

### Debug Output

https://gist.github.com/jrominesf/115292106b31d4d52fbb38a998bba6d4

### Expected Behavior
When removing the virtual hub connection and re-applying, the connection should be added successfully.

### Actual Behavior
Whenever I remove the virtual hub connection from a virtual hub and try to re-apply it, the provider throws the exception below when trying to look up the virtual hub connection.

Error: Connection <connection name>  was not found in Virtual Hub <vhub name> / Resource Group <resource group name>

### Steps to Reproduce

1. `terraform apply`
2. Comment out the azurerm_virtual_hub_connection resource
3. `terraform apply`
4. Uncomment the azurerm_virtual_hub_connection resource
5. `terraform apply`

**Comment by neil-yechenwei** [comment]
@jrominesf , thanks for opening this issue. After tested, seems API doesn't take effect to recreate virtual network connection with same name. I filed an issue on Azure/azure-rest-api-specs#9810. After tested, connection can be recreated with different name. So once you want to recreate connection, suggests to use different name as workaround.

**Comment by jrominesf** [comment]
@neil-yechenwei, thanks for the quick response and the work around for this issue.  I was able to get this to work by renaming the connection.  My final solution was to add a random id to the vhub connection name, so I can destroy and recreate the resources.

```hcl
resource "random_id" "connection_id" {
  byte_length = 16
}

resource "azurerm_virtual_hub_connection" "vwanpeering" {
  provider                                       = azurerm
  name                                           = "${azurerm_virtual_network.vnet.name}-conn-${random_id.connection_id.hex}"
  virtual_hub_id                                 = azurerm_virtual_hub.vhub.id
  remote_virtual_network_id                      = azurerm_virtual_network.vnet.id
  hub_to_vitual_network_traffic_allowed          = false
  vitual_network_to_hub_gateways_traffic_allowed = false
  internet_security_enabled                      = false
}

```
