### ISSUE TITLE
azurerm_sql_firewall_rule: TLS minimal version support for AzureSQL server

### ISSUE THREAD

**Issue by Quantalian** [terraform-providers/terraform-provider-azurerm#7295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### AzureRM Provider Version

* 2.4.0

### Description

 After Azure latest update for App Registration 'TLS minimal version' is required in Azure SQL server firewall rules if you are using Msal.js <= 1.0 for Single Page Application.

### Expected behavior
ssl_minimal_tls_version  = "TLS1_2"

### Actual behavior
not supported, need to define it from portal after terraform apply

### New or Affected Resource(s)

* azurerm_sql_firewall_rule

### References
* https://azure.microsoft.com/en-au/updates/in-development-build-single-page-application-with-msal-js/

**Comment by HarleyB123** [comment]
Hey 👋 

Whilst this has been solved for azurerm_mssql_server, it would be really cool if this same sort of implementation was available for [azurerm_sql_server](https://www.terraform.io/docs/providers/azurerm/r/sql_server.html)

Will try and make a PR for this myself, though my Go is sketchy and would be copying the great work already done in the mssql PR :)

**Comment by dhirschfeld** [comment]
Hi @HarleyB123 👋 
Just wondering why you wouldn't simply port to `azurerm_mssql_server` since they spin up the same infrastructure?

Even though it's not apparently documented anywhere, from my inquiry `azurerm_sql_server` is effectively a deprecated api which has been superseded by `azurerm_mssql_server`: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8338#issuecomment-689933236

**Comment by HarleyB123** [comment]
Thanks @dhirschfeld , I agree that documentation would be beneficial on this as I thought they were two separate resources too! :) 

Will port over to ```azurerm_mssql_server```
