### ISSUE TITLE
azurerm_marketplace_agreement: publisher isn't correctly extracted from resource path

### ISSUE THREAD

**Issue by cnotin** [terraform-providers/terraform-provider-azurerm#7301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.26
+ provider.azurerm v2.14.0
```

### Affected Resource(s)

* `azurerm_marketplace_agreement`

### Terraform Configuration Files

```hcl
resource "azurerm_marketplace_agreement" "kali-linux" {
  publisher = "kali-linux"
  offer     = "kali-linux"
  plan      = "kali"
}
```

### Expected Behavior
Marketplace agreement import should work as it exists

### Actual Behavior
Terraform fails to find the agreement with:
```
Error: Error retrieving agreement for Publisher "current" / Offer "kali-linux" / Plan "kali": marketplaceordering.MarketplaceAgreementsClient#Get: Failure responding to request
```
Notice how `Publisher` = `current` which should be instead `kali-linux` as seen in the resource path
I think the responsible code is:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/3117bdb1947e705440cf3740de05eca3a4173074/azurerm/internal/services/compute/marketplace_agreement_resource.go#L136-L138
https://github.com/terraform-providers/terraform-provider-azurerm/blob/3117bdb1947e705440cf3740de05eca3a4173074/azurerm/internal/services/compute/marketplace_agreement_resource.go#L177-L179

### Steps to Reproduce
1. Accept agreements with `az vm image terms accept --urn kali-linux:kali-linux:kali`
1. Create marketplace agreement resource as shown above
1. Try to import it with:
`terraform import azurerm_marketplace_agreement.kali-linux /subscriptions/<FIXME_TENANT>/providers/Microsoft.MarketplaceOrdering/offerTypes/VirtualMachine/publishers/kali-linux/offers/kali-linux/plans/kali/agreements/current`

### Important Factoids
None

### References
PR #7302

**Comment by magodo** [comment]
Hi @cnotin Thank for submitting this!
Actually the code did the right thing. There are two types of objects in the loop: `offertype` and `agreement`. The provider code use `offertype` to create/delete an `agreement`, and use the ID of the `agreement` as the ID of this resource. In which case, the ID is of the form as: `/subscriptions/<subid>/providers/Microsoft.MarketplaceOrdering/agreements/<publisher>/offers/<offer>/plans/<plan>`.
So if you import using the format as above, it should work.
There should be a fix to the [document](https://www.terraform.io/docs/providers/azurerm/r/marketplace_agreement.html#import)

**Comment by cnotin** [comment]
Hi @magodo thanks for the feedback! Sorry I confused both and your explanation looks good :)
I think it comes from the fact that `az vm image terms ...` returns an ID path based on the `offertype` and not `agreement` for example:
```
/subscriptions/<subid>/providers/Microsoft.MarketplaceOrdering/offerTypes/VirtualMachine/publishers/<publisher>/offers/<offer>/plans/<plan>/agreements/current```
which was the format used in the documentation before your #7438
This is also the ID format that is used when trying to create an already existing agreement (here with azurerm v2.16.0):
```
Error: A resource with the ID "/subscriptions/<subid>/providers/Microsoft.MarketplaceOrdering/offerTypes/VirtualMachine/publishers/kali-linux/offers/kali-linux/plans/kali/agreements/current" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_marketplace_agreement" for more information.
```
Seeing this message I'm tempted to use this format when importing this agreement

I've never seen the format you mention in use, but I'm sure you have more experience than me ;)

**Comment by cnotin** [comment]
So I'm wondering, should I really have to change the format of the ID between the error message, and the import command?

**Comment by magodo** [comment]
Hey @cnotin 

The output of `az vm image terms` is actually the ID of `term`, while in `azurerm_marketplace_agreement`, it is using the ID of `agreement` as its resource ID.

The fact is that when a term is created, it will create both a `term` and an `agreement` behind the scenes. What terraform does is:

- Create: query the `term`, update the `term`'s `Accepted` field to `true`. Set the ID of `agreement` as the resource ID.
- Read: query the `term` based on the `agreement`'s ID.
- Delete: query the `term`, update the `term`'s `Accpeted` field to `false`.

In regards to the import part, currrently the error message is incorrect, I submit another PR to fix it. Also in this PR, I find that my last change to the document import path has a typo. Thank you for your follow-up questions to bring me to take more thoughts on this resource :+1:

**Comment by cnotin** [comment]
Thanks @magodo for the follow-up and your patience. It all makes sense!
I'm glad it helped and thank you for fixing the message 👍

**Comment by cnotin** [comment]
Thanks @magodo I confirm it's all good 👏
```
PS C:\> terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_marketplace_agreement.kali-linux will be created
  + resource "azurerm_marketplace_agreement" "kali-linux" {
      + id                  = (known after apply)
      + license_text_link   = (known after apply)
      + offer               = "kali-linux"
      + plan                = "kali"
      + privacy_policy_link = (known after apply)
      + publisher           = "kali-linux"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_marketplace_agreement.kali-linux: Creating...

Error: A resource with the ID "/subscriptions/<subscription_id>/providers/Microsoft.MarketplaceOrdering/agreements/kali-linux/offers/kali-linux/plans/kali" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_marketplace_agreement" for more information.

  on kali.tf line 3, in resource "azurerm_marketplace_agreement" "kali-linux":
   3: resource "azurerm_marketplace_agreement" "kali-linux" {


PS C:\> terraform import azurerm_marketplace_agreement.kali-linux /subscriptions/<subscription_id>/providers/Microsoft.MarketplaceOrdering/agreements/kali-linux/offers/kali-l
inux/plans/kali
azurerm_marketplace_agreement.kali-linux: Importing from ID "/subscriptions/<subscription_id>/providers/Microsoft.MarketplaceOrdering/agreements/kali-linux/offers/kali-linux/plans/kali"...
azurerm_marketplace_agreement.kali-linux: Import prepared!
  Prepared azurerm_marketplace_agreement for import
azurerm_marketplace_agreement.kali-linux: Refreshing state... [id=/subscriptions/<subscription_id>/providers/Microsoft.MarketplaceOrdering/agreements/kali-linux/offers/kali-linux/plans/kali]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

PS C:\> terraform apply
azurerm_marketplace_agreement.kali-linux: Refreshing state... [id=/subscriptions/<subscription_id>/providers/Microsoft.MarketplaceOrdering/agreements/kali-linux/offers/kali-linux/plans/kali]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
PS C:\>
```
