### ISSUE TITLE
Error: ID was missing the `AuthorizationRules` element

### ISSUE THREAD

**Issue by tamland** [terraform-providers/terraform-provider-azurerm#7310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
provider.azurerm v2.14.0

### Affected Resource(s)

* `azurerm_eventhub_namespace_authorization_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace_authorization_rule" "test" {
  name                = "test"
  namespace_name      = azurerm_eventhub_namespace.main.name
  resource_group_name = azurerm_resource_group.main.name
  listen              = true
  send                = false
  manage              = false
}
```

### Debug Output

https://gist.github.com/tamland/5bb469945bffe493b16d8ca4efd0fc5b

### Actual Behavior

`apply` fails with error `ID was missing the ``AuthorizationRules`` element`. Subsequent runs of `plan` fails with same error. The resource _is_ created and added to state file.

### Steps to Reproduce

1. `terraform apply`

**Comment by logachev** [comment]
It looks like a regression from this PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/7248

Looking at some previous PRs around it, it looks like new SDK expects lower case `authorizationRule` instead of upper case. @tombuildsstuff

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , seems [`StateUpgrader`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/0ade74d01c767d5ab7d89b86104361c6ea8231b5/azurerm/internal/services/eventhub/eventhub_namespace_authorization_rule_resource.go#L36) doesn't take effect so that it failed to parse resource id with [`AuthorizationRules`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/0ade74d01c767d5ab7d89b86104361c6ea8231b5/azurerm/internal/services/eventhub/parse/namespace_authorization_rule.go#L25) since the segment is still `authorizationRules`.

**Comment by evertonmc** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/pull/7147#issuecomment-640440573
> meaning that all EventHub Namespace Authorization Rules will have their Resource ID updated from the old (`authorizationRules`) to the new (`AuthorizationRules`).

@tombuildsstuff do I get it right? Actually the new resource is `authorizationRules` and #7248 did completely the opposite, which now leads to this one? 

Is that introduced [AuthorizationRules](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/eventhub/parse/namespace_authorization_rule.go#L25) correct, when the [new API](https://docs.microsoft.com/en-us/azure/templates/Microsoft.EventHub/namespaces/authorizationrules) uses `authorizationRules`?
