### ISSUE TITLE
Support for custom domains for azurerm_function_app

### ISSUE THREAD

**Issue by seandilda** [terraform-providers/terraform-provider-azurerm#7317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for adding custom domains to Azure functions

### New or Affected Resource(s)

* azurerm_function_app
* azurerm_function_app_custom_hostname_binding (new - based on naming of azurerm_app_service_custom_hostname_binding)

**Comment by aristosvo** [comment]
Have you tried using `azurerm_app_service_custom_hostname_binding` with a `azurerm_function_app`?

**Comment by xuzhang3** [comment]
Hi @seandilda, I did some research and test.  `azurerm_app_service_custom_hostname_binding` uses the same API that function app uses to bind domain. You can use `azurerm_app_service_custom_hostname_binding` to bind domain to function app.
[Reference document](https://www.terraform.io/docs/providers/azurerm/r/app_service_custom_hostname_binding.html) 
Example configuration:
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "test-res-group-name"
  location = "centralus"
}


resource "azurerm_storage_account" "test" {
  name                     = "test-store-account"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "test" {
  name                = "xz3funcSP1"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  kind                =  "Windows"
  reserved            =  true

  sku {
    tier = "Dynamic"
    size = "Y1"
  }

}

resource "azurerm_function_app" "test" {
  name                      = "test-function-app-name"
  location                  = azurerm_resource_group.test.location
  resource_group_name       = azurerm_resource_group.test.name
  app_service_plan_id       = azurerm_app_service_plan.test.id
  storage_connection_string = azurerm_storage_account.test.primary_connection_string
  version                   = "~2"

  app_settings              = {
    "FUNCTIONS_WORKER_RUNTIME"       = "python",
    "WEBSITE_NODE_DEFAULT_VERSION"   = "~10",
    "AzureWebJobsDashboard"          = azurerm_storage_account.test.primary_connection_string
    "AzureWebJobsStorage"            = azurerm_storage_account.test.primary_connection_string
  }

  site_config {
    linux_fx_version = "PYTHON|3.7"
  }
}

//domain bind
resource "azurerm_app_service_custom_hostname_binding" "example" {
  hostname            = "your domain"
  app_service_name    = azurerm_function_app.test.name
  resource_group_name = azurerm_resource_group.test.name
}
```

**Comment by seandilda** [comment]
@xuzhang3  Thanks for digging in and testing, that's really good to know.

Given that, can I change my issue to a documentation bug?  Based on the docs and resource names and documentation, I assumed azurerm_app_service_custom_hostname_binding would only work for azurerm_app_service resources.

**Comment by xuzhang3** [comment]
@seandilda I don't have permission to do this.  Suggest you can open another issue.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume the document is correct since function app is the feature of app service.

**Comment by tombuildsstuff** [comment]
This is a documentation bug - where the equivalent App Service resource can be used to provision the Custom Domain for the Function App; so this requires documenting to that effect.
