### ISSUE TITLE
Support for field `secret_url ` in azurerm_key_vault_secret

### ISSUE THREAD

**Issue by AlphaWong** [terraform-providers/terraform-provider-azurerm#7337]
while disk_encryption_key required `secret_url`
```tf
disk_encryption_key {
   secret_url=<url>
   source_vault_id=<id>
}
```

I cannot get the `secret_url` from the data source `key_vault_secret`
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/5622516/84764310-15c5e200-b000-11ea-8964-5eaaa5449e0e.png)

cc @wangoyuen

# reference
1. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret
2. https://github.com/terraform-providers/terraform-provider-azurerm/issues/606

**Comment by njuCZ** [comment]
@AlphaWong we could use the `id` property of  `key_vault_secret`, it's the same as `secret_url`
