### ISSUE TITLE
Support CustomSubDomain in azurerm_cognitive_account

### ISSUE THREAD

**Issue by jongio** [terraform-providers/terraform-provider-azurerm#7338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_cognitive_account does not allow supporting custom subdomain.  This is required for AAD auth against the service.

It is available in the SDK: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/vendor/github.com/Azure/azure-sdk-for-go/services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go#L477

azsdke2e

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by glennmusa** [comment]
This is also a requirement for configuring a Private Endpoint.

**Comment by pjolsen** [comment]
Would be nice to have this done in tandom with: **Support for network rules on cognitive services #10041**
Both are needed for private endpoints to work securely.

**Comment by jmeadowcroft** [comment]
@tombuildstuff Wasn't this added?

**Comment by afsalva1** [comment]
This functionality is indeed . Unable to setup the private endpoint .

**Comment by jongio** [comment]
Closing as I now see this here:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#custom_subdomain_name
