### ISSUE TITLE
Load balancer profile allocated ports is not in an allowable range for azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by etiennetremel** [terraform-providers/terraform-provider-azurerm#7340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.26
+ provider.azurerm v2.14.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "my-cluster" {
  // [...]

  default_node_pool {
    name = "default"
    type = "VirtualMachineScaleSets"

    vm_size             = "Standard_DS4_v2"
    enable_auto_scaling = true
    max_pods            = 94
    min_count           = 3
    max_count           = 15
    os_disk_size_gb     = 100
  }

  network_profile {
    network_plugin = "azure"

    load_balancer_sku = "Standard"
    load_balancer_profile {
      outbound_ip_address_ids = [ data.azurerm_public_ip.public-ip.id ]
      outbound_ports_allocated = 7104
    }
  }
}
```

### Debug Output

FYI the cluster size is 9 nodes.

```
Error: updating Managed Kubernetes Cluster "my-cluster" (Resource Group "my-resource-group"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidLoadBalancerProfileAllocatedOutboundPorts" Message="Load balancer profile allocated ports is not in an allowable range given the number of nodes and IPs provisioned. Refer to https://aka.ms/aks/slb-ports for more details." Target="networkProfile.loadBalancerProfile.allocatedOutboundPorts"

  on my-cluster.tf line 26, in resource "azurerm_kubernetes_cluster" "my-cluster":
  26: resource "azurerm_kubernetes_cluster" "my-cluster" {
```

### Panic Output

n/a

### Expected Behavior

It should update the allocated outbound port and validate as described [here](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#snatports).

### Actual Behavior

It throw the following error message:

> Load balancer profile allocated ports is not in an allowable range given the number of nodes and IPs provisioned. Refer to https://aka.ms/aks/slb-ports for more details.

### Steps to Reproduce

I can change the outbound ports allocation manually using the command line:
```bash
$ az network lb outbound-rule update --lb-name kubernetes -g mc_my-resource-group_my-cluster_westeurope --name aksOutboundRule --outbound-ports 7104

# double checking the value is correctly set:
$ az network lb outbound-rule list --lb-name kubernetes -g mc_my-resource-group_my-cluster_westeurope
{
    "allocatedOutboundPorts": 7104,
    [...]
}
```

All this work with the command line but it doesn't work when applying the state with `terraform apply`.

### References

- https://github.com/terraform-providers/terraform-provider-azurerm/pull/7233
- https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-the-allocated-outbound-ports

**Comment by Akhisar** [comment]
Hello @etiennetremel,

I faced the same issue. In my case I was having the optimum active node count but still the apply was failing. I could later find that auto scale was enabled. It worked after I considered the max node count also to my total node count. I think you need to take this into account when calculating ports/nodes. Along with that probably the maxSurge(by default 1) also need to be considered. I think it is worth you try with port count 6400 i.e  6400/(9 node + 1 maxSurge node). This is just an assumption, but should probably work. Let me know if it works ;).

**Comment by etiennetremel** [comment]
Hi @Akhisar, thanks, that was the issue! I wasn't taking in consideration the max_pod value from the autoscaler.

**Comment by adityasundaramurthy-maersk** [comment]
I've run into the exact same issue. I have an autoscaling cluster with max_count of the default nodepool set to 4. I'm trying to set `outbound_ports_allocated` to `64000/(4+1) = 12800` to accommodate for the possibility of surge (set to the default value). However, Terraform apply fails with the following error:

```
Error: updating Managed Kubernetes Cluster "the-cluster" (Resource Group "the-resource-group"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidLoadBalancerProfileAllocatedOutboundPorts" Message="Load balancer profile allocated ports is not in an allowable range given the number of nodes and IPs provisioned. Refer to https://aka.ms/aks/slb-ports for more details." Target="networkProfile.loadBalancerProfile.allocatedOutboundPorts"
```
