### ISSUE TITLE
Is there a way in terraform to give users choice of authentication ( like password or  azure keyvault… etc) at the input level? 

### ISSUE THREAD

**Issue by papineni87** [terraform-providers/terraform-provider-azurerm#7344]
I am using azure provider, and for the sake of vm authentication i want to provide users 2 types of authentication ( randomly generate password and key vault based) .

below is the snapshot of code how i am doing for individual approach, but i need to convert these based on user authentication choice. For example if user want to key vault authentication, it should ask vault related inputs and create password based on it. If user wants dynamic password it should not ask vault parameters or execute vault resources, it simply has to run random resource and create password.

data “azurerm_resource_group” “rg_keyvault” {
name = “${var.azure_secret_rg}”
}

data "azurerm_key_vault" "keyvault" {
  name = "${var.azure_keyvault_name}"
  resource_group_name = "${data.azurerm_resource_group.rg_keyvault.name}"
}

data "azurerm_key_vault_secret" "bigip_admin_password" {
  name = "${var.azure_keyvault_secret_name}"
  key_vault_id = "${data.azurerm_key_vault.keyvault.id}"
}

resource "random_password" "password" {
  length = 16
  special = true
  override_special = "_%@"
}

resource “azurerm_virtual_machine” “x” {

…
os_profile {
admin_username = var.f5_username

#admin_password = random_password.password.result
#admin_password = data.azurerm_key_vault_secret.bigip_admin_password.value

}

**Comment by magodo** [comment]
Hi @papineni87 Thank you for submitting this!
I think what you need is a conditional expression combined with the `count` to do the trick. Following is a runnable example illustrating the usage (to make things easy, I substitute the keyvault resource by a `random_integer`):

```hcl
variable "random" {
  type = bool
}

resource "random_password" "password" {
  count = var.random? 1:0
  length = 16
  special = true
  override_special = "_%@"
}

# play role as the key vault
resource "random_integer" "secret" {
  count = var.random? 0:1
  min = 1
  max = 50000
}

output "auth_value" {
  value = var.random? random_password.password[0].result : random_integer.secret[0].result
}
```

So when user specify `-var random=true`, the `random_integer` resource is skipped; Otherwise, the `random_password` resource is skipped.

**Comment by papineni87** [comment]
Got it .
Thanks
