### ISSUE TITLE
Support for keeping OS Disk on VM Destruction

### ISSUE THREAD

**Issue by danmanrique** [terraform-providers/terraform-provider-azurerm#7365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the scenario of having an existing VM, I need the ability to remove the VM, keep the OS disk, and create a new VM with the destroyed VM's OS disk. This is available in the RP and works effectively in Azure CLI. I tried the setting: delete_os_disk_on_termination = false on Terraform v0.12.26, provider.azurerm v2.0.0.

$originalVM = Get-AzVM  -ResourceGroupName $resourceGroup -Name $vmName

Remove-AzVM -ResourceGroupName $resourceGroup -Name $vmName    

$newVM = New-AzVMConfig -VMName $originalVM.Name -VMSize $originalVM.HardwareProfile.VmSize -AvailabilitySetId $availSet.Id

Set-AzVMOSDisk -VM $newVM -CreateOption Attach -ManagedDiskId $originalVM.StorageProfile.OsDisk.ManagedDisk.Id -Name $originalVM.StorageProfile.OsDisk.Name -Linux

foreach ($disk in $originalVM.StorageProfile.DataDisks) { 
    Add-AzVMDataDisk -VM $newVM `
    -Name $disk.Name `
    -ManagedDiskId $disk.ManagedDisk.Id `
    -Caching $disk.Caching `
    -Lun $disk.Lun `
    -DiskSizeInGB $disk.DiskSizeGB `
    -CreateOption Attach
}

### New or Affected Resource(s)

azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ArcturusZhang** [comment]
Hi @danmanrique thanks for this issue!

It is possible to keep the OS disk during the destruction of the VMs, by assigning the [`delete_os_disk_on_deletion` flag within the `features` block](https://www.terraform.io/docs/providers/azurerm/index.html#features-2) to `true`. Could you please have a try on this?

**Comment by tombuildsstuff** [comment]
hey @danmanrique 

As per @ArcturusZhang's comment it should be possible to achieve this by configuring the `feature` within the `features` block, for example:

```hcl
provider "azurerm" {
  version = "=2.15.0"

  features {
    virtual_machine {
      delete_os_disk_on_deletion = false
    }
  }
}

resource "azurerm_linux_virtual_machine" "test" {
  # ...
}
```

Since this functionality is available using the flag inside the features block - I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
