### ISSUE TITLE
Support for creating Linux VM with existing OS Disk

### ISSUE THREAD

**Issue by danmanrique** [terraform-providers/terraform-provider-azurerm#7366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As part of the ability to create a new Linux VM, there should be able to use an existing OS disk from a previously destroyed VM. This is available in Azure CLI as follows:

#create a Linux VM
az vm create --resource-group myResourceGroupAvailability --name myVM --availability-set myAvailabilitySet --size Standard_DS1_v2  --vnet-name myVnet --subnet mySubnet --image UbuntuLTS --admin-username azureuser --generate-ssh-keys

# Set variables for execution
$resourceGroup = "myResourceGroupAvailability"
$vmName = "myVM"
$newAvailSetName = "myAvailabilitySet"
$availSet = Get-AzureRmAvailabilitySet -ResourceGroupName "myResourceGroupAvailability" -Name "myAvailabilitySet"

#get the VM
$originalVM = Get-AzVM  -ResourceGroupName $resourceGroup -Name $vmName

#destroy the VM
Remove-AzVM -ResourceGroupName $resourceGroup -Name $vmName    

#create a new VM
$newVM = New-AzVMConfig -VMName $originalVM.Name -VMSize $originalVM.HardwareProfile.VmSize -AvailabilitySetId $availSet.Id

#set the OS Disk to the disk from the old VM
Set-AzVMOSDisk -VM $newVM -CreateOption Attach -ManagedDiskId $originalVM.StorageProfile.OsDisk.ManagedDisk.Id -Name $originalVM.StorageProfile.OsDisk.Name -Linux

### New or Affected Resource(s)

azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7365
--->

* #0000

**Comment by tombuildsstuff** [comment]
Closing this in favour of #8195 which has a little more context - would you mind subscribing to that issue for updates?
