### ISSUE TITLE
Support for Azure Firewall Manager

### ISSUE THREAD

**Issue by sarnowski** [terraform-providers/terraform-provider-azurerm#7368]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [Azure Firewall Manager](https://azure.microsoft.com/en-us/services/firewall-manager/) is in public preview. It is a new method to manage Azure Firewalls especially in combination with the [Virtual WAN](https://azure.microsoft.com/en-us/services/virtual-wan/). The Virtual WAN has deep integration with the Firewall Manager to provide centralized routing control in the [Hub and Spoke architecture](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke). In order to leverage the new construct, it is also necessary to implement the new Virtual Hub Route Tables that allow dynamic assignments to spokes.

### New or Affected Resource(s)

* **azurerm_firewall**: the resource needs to be enhanced to support the new Hub SKU which comes with the possibility to add new Azure Policies.
* **azurerm_firewall_policy**: is the general new approach to define policies also in hierarchies
* **azurerm_firewall_policy_rule_collection_group**: provides the rule groups, similar to the old collections attached to the new policies
* **azurerm_virtual_hub_route_table**: new routing table construct that allow spokes to be forced to use the firewall

### Potential Terraform Configuration

```hcl
resource "azurerm_firewall" "default" {
  name = "AzureFirewall_vhub-${var.global.location}"
  location = var.location

  resource_group_name = azurerm_resource_group.wan.name

  sku_name = "AZFW_Hub"
  virtual_hub_id = azurerm_virtual_hub.default.id

  firewall_policy_id = azurerm_firewall_policy.central.id
}

resource "azurerm_firewall_policy" "central" {
  name = "Central"
  location = var.location

  resource_group_name = azurerm_resource_group.wan.name

  threat_intel_mode = "Alert"
}

resource "azurerm_firewall_policy_rule_collection_group" "administration" {
  name = "azfwrg-administration"
  firewall_policy_name = azurerm_firewall_policy.central.name
  resource_group_name = azurerm_resource_group.wan.name

  priority = 100

  filter_rule {
    name = "ssh-access"
    action_type = "Allow"

    network_condition {
      destination_addresses = ["*"]
      destination_ports = ["22"]
      ip_protocols = ["TCP"]
      source_addresses = ["10.0.0.0/8"]
    }
  }
}

resource "azurerm_virtual_hub_route_table" "vnets" {
  name = "vnets"

  resource_group_name = azurerm_resource_group.wan.name

  virtual_hub_name = azurerm_virtual_hub.default.name

  attached_connections = ["All_Vnets"]

  route {
    destination_type = "CIDR"
    destinations = ["0.0.0.0/0"]

    next_hop_type = "IPAddress"
    next_hops = ["10.0.0.4"]
  }
}
```

### References

* Azure Resource Manager Quickstart Example: https://github.com/Azure/azure-quickstart-templates/blob/master/fwm-docs-qs/azuredeploy.json
* Azure Firewall API: https://docs.microsoft.com/en-us/rest/api/firewall/azurefirewalls/createorupdate
* Firewall Policies API: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/firewallpolicies/createorupdate
* Firewall Policy Rule Collection Groups API: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/firewallpolicyrulecollectiongroups/createorupdate
* Virtual Hub Route Table (V2) API: https://docs.microsoft.com/en-us/rest/api/virtualwan/virtualhubroutetablev2s/createorupdate

**Comment by Dilergore** [comment]
This is now GA: https://azure.microsoft.com/en-us/blog/azure-firewall-manager-is-now-generally-available/
