### ISSUE TITLE
postgresql - hyperscale support

### ISSUE THREAD

**Issue by az-cloud** [terraform-providers/terraform-provider-azurerm#7380]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.
Hi All,

Wanted to check if current Terraform version supports hyperscale option since iam not able to find one except for sql.
---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by az-cloud** [comment]
hi,  can someone please help me here.

**Comment by tombuildsstuff** [comment]
hi @az-cloud 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #5040 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #5040 for updates?

Thanks!

**Comment by az-cloud** [comment]
thanks Tom, subscribed to #5040
