### ISSUE TITLE
Support for azurerm_monitor_activity_log_alert - Adding Location to ServiceHealth Alerts

### ISSUE THREAD

**Issue by benhurjoel** [terraform-providers/terraform-provider-azurerm#7392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to create a Service Health Alert (On Portal : Azure Monitor > Service Health > Health Alerts ) using TF. I choose the category "ServiceHealth" and set the Scope for entire subscription. It works for Global Alerts but I do not see a way to specify a region here (option available on Portal). If I missed something, please feel free to correct me.

My Code:
======

resource "azurerm_monitor_activity_log_alert" "alert1" {
  name                = "demo-alert-01"
  resource_group_name = azurerm_resource_group.rg.name
  scopes              = ["/subscriptions/<subscription_id>"]
  description         = "service health alerts."

  criteria {
    category       = "ServiceHealth"
  }
  action {
    action_group_id = azurerm_monitor_action_group.ag1.id
  }
}

### New or Affected Resource(s)

* azurerm_monitor_activity_log_alert 

### Potential Terraform Configuration

  criteria {
    category       = "ServiceHealth"
   location  = "<RegionName> "  <---
  }

ARM Template :
==============
                "condition": {
                    "allOf": [
                        {
                            "field": "category",
                            "equals": "ServiceHealth",
                            "containsAny": null
                        },
                        {
                            "field": "properties.impactedServices[*].ImpactedRegions[*].RegionName",
                            "equals": null,
                            "containsAny": [
                                "Southeast Asia"
                               ]
                        }
                    ]
                },

### References

https://docs.microsoft.com/en-us/azure/service-health/service-health-overview
https://www.terraform.io/docs/providers/azurerm/r/monitor_activity_log_alert.html

**Comment by magodo** [comment]
Hi @benabineri Thank you for submitting this issue :+1: 
Currently, the Swagger lacks the definition for the `containsAny` property, I submit issue Azure/azure-rest-api-specs#9906 to track this. Once it has been addressed, then we can move on!

**Comment by benhurjoel** [comment]
Thank you @magodo . Appreciate it!

**Comment by mbfrahry** [comment]
Hey all. This is now fixed with #10978 and should make it into the 2.56.0 release

**Comment by benhurjoel** [comment]
Thank you @mbfrahry and @HappyTobi for the contribution, Appreciate it!
