### ISSUE TITLE
Support for Integration Service Environments

### ISSUE THREAD

**Issue by favoretti** [terraform-providers/terraform-provider-azurerm#7394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for Integration Service Environment

### New or Affected Resource(s)

* azurerm_integration_service_environment

### Potential Terraform Configuration (ARM template)

```
{
            "type": "Microsoft.Logic/integrationServiceEnvironments",
            "apiVersion": "[parameters('integrationServiceEnvironmentApiVersion')]",
            "name": "[parameters('integrationServiceEnvironmentName')]",
            "location": "[parameters('integrationServiceEnvironmentLocation')]",
            "dependsOn": [
                "Microsoft.Resources/deployments/updateVirtualNetworkSubnetWithDelegation"
            ],
            "tags": "[parameters('tags')]",
            "sku": {
                "name": "[parameters('skuName')]",
                "capacity": "[parameters('skuCapacity')]"
            },
            "properties": {
                "networkConfiguration": {
                    "subnets": "[parameters('subnetResourceIds')]",
                    "accessEndpoint": "[parameters('accessEndpoint')]"
                }
            }
        }
```

### References

https://azure.microsoft.com/nl-nl/blog/announcing-azure-integration-service-environment-for-logic-apps/

**Comment by favoretti** [comment]
Once this is created `azurerm_logic_app_workflow` would need to be updated to support linking to it.

**Comment by jbinko** [comment]
Just wrote specification #7492 and will focus on implementation. Please provide feedback on spec!

**Comment by jbinko** [comment]
### Description


Moving specification into this thread.
Support in Terraform for Integration Service Environment (ISE) / Azure Logic Apps
<https://docs.microsoft.com/en-us/azure/logic-apps/ise-manage-integration-service-environment>
<https://docs.microsoft.com/en-us/azure/templates/microsoft.logic/integrationserviceenvironments#IntegrationServiceEnvironmentAccessEndpoint>

Please see specification, will also initiate implementation based on the specification discussed and described here. Please provide feedback! Implementation self assigned to me @jbinko . Please assign me.

### New or Affected Resource(s)



* azurerm_integration_service_environment

### Potential Terraform Configuration



```hcl
resource "azurerm_resource_group" "example" {
  name     = "exampleRG1"
  location = "westeurope"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/22"]
}

resource "azurerm_subnet" "isesubnet1" {
  name                 = "isesubnet1"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.0/26"
}

resource "azurerm_subnet" "isesubnet2" {
  name                 = "isesubnet2"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.64/26"
}

resource "azurerm_subnet" "isesubnet3" {
  name                 = "isesubnet3"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.128/26"
}

resource "azurerm_subnet" "isesubnet4" {
  name                 = "isesubnet4"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.192/26"
}

resource "azurerm_integration_service_environment" "example" {
  name     = "example-ise"
  location = azurerm_resource_group.example.location
  sku_name = "Developer"
  capacity = 0

  access_endpoint_type = "Internal"
  virtual_network_subnet_ids = [
    azurerm_subnet.isesubnet1.id,
    azurerm_subnet.isesubnet2.id,
    azurerm_subnet.isesubnet3.id,
    azurerm_subnet.isesubnet4.id
  ]

  endpoint_workflow {
    outgoing_ip_addresses        = "52.23.25.3,52.143.43.12"
    access_endpoint_ip_addresses = "52.143.43.12,52.143.43.17"
  }

  endpoint_connector {
    outgoing_ip_addresses        = "52.23.25.3,52.143.43.12"
    access_endpoint_ip_addresses = "52.143.43.12,52.143.43.17"
  }

  tags = {
    environment = "development"
  }
}
```

**Comment by favoretti** [comment]
@jbinko Need any help finalizing this?

**Comment by katbyte** [comment]
@jbinko - thanks for working on this! took a quick look at your branch and loosk pretty good! feel free to open a PR so we can give it a proper review 🙂

**Comment by jbinko** [comment]
Just published PR. @favoretti , @katbyte thank you for interest. I'll be happy if you can do review and/or bring new ideas.

**Comment by jbinko** [comment]
Based on the feedback changing the spec. Capacity will not be used directly. sku_name will contain tier name and capacity. Effectively merging sku and capacity all together.
