### ISSUE TITLE
Kube-dashboard gets updated on every apply even though it's not configured/used

### ISSUE THREAD

**Issue by muellermatthias** [terraform-providers/terraform-provider-azurerm#7396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.25
provider.azurerm v2.14.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "example"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
    }
  }
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

provider "azurerm" {
  features {}
  version = "2.14.0"
}

```

### Expected Behavior

After provisioning the resources applying the same configuration again should show no changes.

### Actual Behavior

The plan wants to change the kube_dashboard addon:

```
~ addon_profile {
          - kube_dashboard {
              - enabled = true -> null
            }
...
```
Applying the change won't help, because after that the change will be shown again.

I tried the same configuration without addon_profile and it works fine.

### Steps to Reproduce

1. Run `terraform apply` to provision the resources

2. Run `terraform plan/apply` to see the changes

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems api would return default value "enabled = true" for kube_dashboard. Hopes the fix would be helpful.

**Comment by neil-yechenwei** [comment]
According by the [comment](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8320#issuecomment-685364070), I assume this issue should be resolved by specifying the block "kube_dashboard" within the tfconfig or using ignore_changes.

Specifying the block "kube_dashboard" to fix this issue:
```
resource "azurerm_kubernetes_cluster" "example" {
  ......	

    kube_dashboard {
      enabled = true
    }
  }
}
```

Using ignore_changes to fix this issue:
```
resource "azurerm_kubernetes_cluster" "example" {
  ......
  
  lifecycle {
    ignore_changes = [addon_profile.0.kube_dashboard]
  }
}
```

**Comment by muellermatthias** [comment]
@neil-yechenwei Thanks.
