### ISSUE TITLE
Support for creating Service Fabric Cluster in a existing Vnet

### ISSUE THREAD

**Issue by SUNIL23891YADAV** [terraform-providers/terraform-provider-azurerm#7398]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Service Fabric is a platform for orchestrating  microservices. As of now its deployment from Azure Portal or Terraform resource **azurerm_service_fabric_cluster** doesn't give any option to deploy the cluster in a existing Virtual Network. Each time you spin up a new cluster, it creates a Virtual network where it deploy the VMSS nodes for Service fabric cluster.
Although using ARM template it is possible to deploy the cluster into existing Vnet.

### New or Affected Resource(s)

**azurerm_service_fabric_cluster** : the resource needs to be enhanced to support deployment into existing Virtual Network. 

### Potential Terraform Configuration

```
resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_service_fabric_cluster" "example" {
  name                 = "example-servicefabric"
  resource_group_name  = azurerm_resource_group.example.name
  location             = azurerm_resource_group.example.location
  reliability_level    = "Bronze"
  upgrade_mode         = "Manual"
  cluster_code_version = "6.5.639.9590"
  vm_image             = "Windows"
  management_endpoint  = "https://example:80"
 subnet_id             = azurerm_subnet.example.id

  node_type {
    name                 = "first"
    instance_count       = 3
    is_primary           = true
    client_endpoint_port = 2020
    http_endpoint_port   = 80
  }
}
```

### References

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-portal
https://blog.techfabric.io/deploying-service-fabric-cluster-to-existing-vnet-with-containers/

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated, [the doc](https://blog.techfabric.io/deploying-service-fabric-cluster-to-existing-vnet-with-containers/) shows how to deploy service fabric cluster to existing vnet using VirtualMachineScaleSet. So I assume resource `azurerm_virtual_machine_scale_set` could implement this scenario. And I also checked rest api spec, seems service fabric cluster api doesn't support this scenario since there is no property related with vnet in [service fabric cluster api](https://github.com/Azure/azure-rest-api-specs/blob/82f599660e7ac7203bd30cc982992bcb351b1aae/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable/2020-03-01/cluster.json#L770). So I assume `azurerm_service_fabric_cluster` cannot support this scenario.

**Comment by SUNIL23891YADAV** [comment]
Resource ```azurerm_virtual_machine_scale_set``` can't help in implementing this scenario because while deploying resource ```azurerm_service_fabric_cluster``` it creates a Vnet and deploy a VMSS in it. As of now there is no way where can you choose existing Vnet or VMSS. Even when you do it manually from the Azure portal. 
I was hoping if we can pass a input to the ```azurerm_service_fabric_cluster``` to  specificy where to bring up the VMSS nodes. I am able to achieve this functionality by having an ARM template which spins up the **Service Fabric Cluster** and in its parameter we can inject the id of the existing Vnet. And then I am deploying this template from Terraform. I can share the code if it helps.
And if this is a blocker from Azure api end and nothing can be done about it. I am good to close this.

**Comment by neil-yechenwei** [comment]
Yes. I assume it's a blocker from azure api end.

**Comment by hbuckle** [comment]
The `azurerm_service_fabric_cluster` resource does not create the scale sets for you, you need to do it yourself using the scale set resources, and you can specify the vnet there

**Comment by tombuildsstuff** [comment]
👋 

The (older) Service Fabric service requires that you provision the Cluster and VM Scale Set separately (as @hbuckle has mentioned) - using a VM Extension to connect the two.

When provisioning the VM Scale Set, it's possible to pick the Subnet that the VM Scale Set should be deployed into - as such this should be feasible with Terraform today, so I'm going to close this issue for the moment.

Thanks!
