### ISSUE TITLE
Create PEM key from existing value

### ISSUE THREAD

**Issue by gchagan36** [terraform-providers/terraform-provider-azurerm#7402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to see a feature added where we can import an already existing key into Azure Key Vault, similiar to how it is done in azurerm_key_vault_secret.

### New or Affected Resource(s)

* azurerm_key_vault_key

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_key" "example" {
    name = "example_key"
    value = var.key
    key_vault_id = azurerm_key_vault.example.id
    key_type = "RSA"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here this appears to be the same feature request as #4283 - as such rather than having multiple issues open tracking the same thing, I'm going to consolidate this into that issue, would you mind subscribing to #4283 for updates?

Thanks!
