### ISSUE TITLE
can't manage Azure firewall_policy and application gateway with terraform

### ISSUE THREAD

**Issue by dl888888** [terraform-providers/terraform-provider-azurerm#7403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version.

Terraform v0.12.26
+ provider.azuread v0.7.0
+ provider.azurerm v2.14.0
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_XXXXX`
azurerm_application_gateway
azurerm_web_application_firewall_policy

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
see https://github.com/dl888888/terraform-issues/blob/master/production-ssui-agw.tf.20200618.share

### Debug Output

terraform import  existing Azure wafpolicy and application gateway resources into terraform. Then do a terraform plan. Terraform wants to update the application gateway in place. When I terraform apply it fails with 

Error: Error Creating/Updating Application Gateway "production-ssui-agw" (Resource Group "aerserv-prod-eastus-rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayWafConfigurationCannotBeChangedWithWafPolicy" Message="WebApplicationFirewallConfiguration cannot be changed when there is a WAF Policy /subscriptions/XXXX-XXXX/resourceGroups/aerserv-prod-eastus-rg/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/aerserv-prod-eastus-prod-ssui-agw-wafpolicy2 associated with it." Details=[]

see https://github.com/dl888888/terraform-issues/blob/master/bamboo-ci-cd-deploy-error-output

### Expected Behavior

I understand that terraform cannot update application gateway when there is a WAF Policy associated with it. However, terraform should not do anything when the state is just imported.

### Steps to Reproduce

terraform import  existing Azure wafpolicy and application gateway resources into terraform. Then do a terraform plan. Terraform wants to update the application gateway in place. When I terraform apply it fails 

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume you repeate defining the waf configuration. Could you remove the block `waf_configuration` of `azurerm_application_gateway` and have a retry to check whether the problem still exists? Thanks.

**Comment by dl888888** [comment]
Thanks for responding. Sorry we've been having a lot of operational issues. Anyway, got some time to try it today. Here's the new config: https://github.com/dl888888/terraform-issues/blob/master/production-ssui-agw.tf.20200624.rmwafconfig. Still got exactly the same error.

Is this basically a limitation of Azure app gateway?

**Comment by neil-yechenwei** [comment]
@dl888888 , sorry, could you help to check whether my below repro steps are incorrect since I still cannot repro this issue?

Run `tf apply` to create resources:
```
provider "azurerm" {
  features {}
  version = "2.14.0"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-fp-test"
  location = "eastus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctest-vnet-fp-test"
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
}

resource "azurerm_subnet" "test" {
  name                 = "subnet-fp-test"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.0.0/24"]
}

locals {
  backend_address_pool_name      = "fptest-beap"
  frontend_port_name             = "fptest-feport"
  frontend_ip_configuration_name = "fptest-feip"
  http_setting_name              = "fptest-be-htst"
  listener_name                  = "fptest-httplstn"
  request_routing_rule_name      = "fptest-rqrt"
}

resource "azurerm_public_ip" "teststd" {
  name                = "acctest-PubIpStd-test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_web_application_firewall_policy" "testfwp" {
  name                = "acctest-fwp-test"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  policy_settings {
    enabled = true
    mode    = "Detection"
  }

  managed_rules {
    managed_rule_set {
      type    = "OWASP"
      version = "3.1"
    }
  }
}

resource "azurerm_application_gateway" "test" {
  name                = "acctestag-test"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  sku {
    name     = "WAF_v2"
    tier     = "WAF_v2"
    capacity = 2
  }

  firewall_policy_id = azurerm_web_application_firewall_policy.testfwp.id

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.test.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 80
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.teststd.id
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    port                  = 443
    protocol              = "Https"
    request_timeout       = 1

    pick_host_name_from_backend_address = true
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Http"
  }

  request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }
}
```

Run `tf import`:
```
terraform import azurerm_resource_group.test /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-fp-test
terraform import azurerm_virtual_network.test /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-fp-test/providers/Microsoft.Network/virtualNetworks/acctest-vnet-fp-test
terraform import azurerm_subnet.test /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-fp-test/providers/Microsoft.Network/virtualNetworks/acctest-vnet-fp-test/subnets/subnet-fp-test
terraform import azurerm_public_ip.teststd /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-fp-test/providers/Microsoft.Network/publicIPAddresses/acctest-PubIpStd-test
terraform import azurerm_web_application_firewall_policy.testfwp /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-fp-test/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/acctest-fwp-test
terraform import azurerm_application_gateway.test /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-fp-test/providers/Microsoft.Network/applicationGateways/acctestag-test
```

Run `tf plan`:
![image](https://user-images.githubusercontent.com/19754191/85975854-bdcda900-ba0b-11ea-910f-91cec9314fd5.png)

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment - but please let us know if this is still an issue and we'll take another look.

Thanks!
