### ISSUE TITLE
Documentation for Front Door resource has wrong read timeout value

### ISSUE THREAD

**Issue by darrenk13** [terraform-providers/terraform-provider-azurerm#7405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.26
+ provider.azurerm v2.13.0
```

### Affected Resource(s)

* `azurerm_frontdoor`

### Important Factoids

The documentation at https://www.terraform.io/docs/providers/azurerm/r/frontdoor.html#read indicates the `read` timeout is 6 hours.  The source code at https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/frontdoor/frontdoor_resource.go#L36 seems to indicate to me that the default for the `read` timeout is 5 minutes.

I ran into this as I was creating a front door and was getting the following error in way less than 6 hours:
```
Error: retrieving Front Door Frontend Endpoint "my-frontdoor-name" (Resource Group "my-resource-group"): frontdoor.FrontendEndpointsClient#Get: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
```

**Comment by WodansSon** [comment]
@darrenk13, good catch... thanks for opening this issue, and sorry about that... 🙂
