### ISSUE TITLE
IoT Hub Consumer Group creation fails if the same 'apply' step tries to create a component, which depends on it

### ISSUE THREAD

**Issue by v1r7u** [terraform-providers/terraform-provider-azurerm#7444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure IoT Hub supports built-in event-hub endpoint, where device-telemetry messages are routed by default. Terraform supports adding Consumer Groups to this endpoint. Other parts of terraform configuration should be able to use Consumer Group resource as a reference.

We use a setup, when Azure Function reads telemetry data from IoT Hub, using a dedicated consumer group and IoT Hub policy. When this infrastructure is created the first time, terraform throws an exception like:

```text
Error: Error retrieving Consumer Group "normalizer" (Endpoint "events" / IoTHub "iothub-name" / Resource Group "rg-name"): devices.IotHubResourceClient#GetEventHubConsumerGroup: Failure sending request:
StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
```

**The problem appears if IoT Hub and Consumer Group resources are created in the same `apply` step with the dependent component.**

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.26
+ provider.azurerm v2.15.0
```

### Affected Resource(s)

* `azurerm_iothub_consumer_group`

### Terraform Configuration Files

The entire configuration is committed to the repo: https://github.com/v1r7u/azurerm_issues/blob/master/src/iot_eventhub_listener/main.tf

### Expected Behavior

Terraform is able to create in the same step: `IoT Hub`, `IoT Hub Policy`, `IoT Hub Consumer Group`, and `Azure Function` which consumes them.

### Actual Behavior

Terraform properly creates `IoT Hub` and `IoT Hub Policy`, fails during creating `Consumer Group` and `Azure Function`, which depends on it.

### Steps to Reproduce

Detailed steps to reproduce and terraform configuration sample I've committed to the repo:
https://github.com/v1r7u/azurerm_issues/tree/master/src/iot_eventhub_listener

**Comment by royto** [comment]
We had the same kind of issue on iothub when trying to create in the same apply 2 consumer group and 1 SAS Policy.

As a workaround, we set an [explicit dependency](https://learn.hashicorp.com/terraform/getting-started/dependencies#implicit-and-explicit-dependencies) with `depends_on` and it has fix our pb.

**Comment by v1r7u** [comment]
@royto, thanks for forcing me into this direction!
I did a few more tests and found that `azurerm_iothub_consumer_group` creation fails, because of explicitly defined default `route` as a part of IoT Hub.

Below are simplified version of my resources (I dropped registration of other endpoints/routes to shorten the sample)

What I had before (**this one fails**):
```hcl
resource "azurerm_iothub" "ingestion" {
  name                = var.iothub_name
  resource_group_name = azurerm_resource_group.rg_ingestion.name
  location            = azurerm_resource_group.rg_ingestion.location

  sku {
    name     = var.iot_sku.name
    capacity = var.iot_sku.capacity
  }

  route {
    name           = "defaultroute"
    source         = "DeviceMessages"
    condition      = "true"
    endpoint_names = ["events"]
    enabled        = true
  }
}

resource "azurerm_iothub_consumer_group" "normalizer" {
  name                   = "normalizer"
  iothub_name            = azurerm_iothub.ingestion.name
  eventhub_endpoint_name = "events"
  resource_group_name    = azurerm_resource_group.rg_ingestion.name
}
```

How I changed it (**this one works fine**):
```hcl
resource "azurerm_iothub" "ingestion" {
  name                = var.iothub_name
  resource_group_name = azurerm_resource_group.rg_ingestion.name
  location            = azurerm_resource_group.rg_ingestion.location

  sku {
    name     = var.iot_sku.name
    capacity = var.iot_sku.capacity
  }
}

resource "azurerm_iothub_route" "default_iot_eh_route" {
  resource_group_name = azurerm_resource_group.rg_ingestion.name
  iothub_name         = azurerm_iothub.ingestion.name
  name                = "defaultroute"

  source         = "DeviceMessages"
  condition      = "true"
  endpoint_names = ["events"]
  enabled        = true
}

resource "azurerm_iothub_consumer_group" "normalizer" {
  name                   = "normalizer"
  iothub_name            = azurerm_iothub.ingestion.name
  eventhub_endpoint_name = "events"
  resource_group_name    = azurerm_resource_group.rg_ingestion.name

  depends_on = [ azurerm_iothub_route.default_iot_eh_route ]
}
```

## Root cause
**If the default route for `events` endpoint is explicitly stated in the `azurerm_iothub` resource, dependent consumer group fails to create.** 

## Workaround
Move default route definition out of `azurerm_iothub` and define `azurerm_iothub_consumer_group` explicit dependency on the route (see example above)

**Comment by royto** [comment]
Glad it helps 😉

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated, I assume iothub seems api doesn't allow multiple operations in the same time. So I made a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8041) to add a lock on iothub while operating iothub consumer group. Hopes it would be helpful. Thanks.
