### ISSUE TITLE
IoT Hub Shared Access Policy should not change Key after changing permissions

### ISSUE THREAD

**Issue by v1r7u** [terraform-providers/terraform-provider-azurerm#7445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Changes in existing IoT Hub Policy permissions should not change associated secrets/connection_strings. For example, at Azure Portal, you can add/remove permissions to the existing policy without keys regeneration. But if the policy object managed by terraform, it leads to the changed connection string.

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.26
+ provider.azurerm v2.15.0
```

### Affected Resource(s)

* `azurerm_iothub_shared_access_policy`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub_shared_access_policy" "policy" {
  name                = "policy"
  resource_group_name = azurerm_resource_group.rg.name
  iothub_name         = azurerm_iothub.iot.name

  registry_read   = true
  registry_write  = true
  service_connect = true
  device_connect  = false
}
```

### Expected Behavior

After changing permissions of existing IoT Hub Policy, it stays with the same keys/connection_strings.

### Actual Behavior

After changing permissions of existing IoT Hub Policy, keys/connection_strings are regenerated (or the policy object is recreated?)

### Steps to Reproduce

Detailed steps to reproduce and terraform configuration sample I've committed to the repo:
https://github.com/v1r7u/azurerm_issues/tree/master/src/policy_recreation

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated, I found the root cause is that the returned existing primary key and secondary key haven't been added into http request body while updating. So api would always generate new primary key and secondary key. For this issue, I made a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8017). Hopes it would be helpful. Thanks.
