### ISSUE TITLE
`azurerm_function_app` & `azurerm_function_app_slot` support for name, priority & action

### ISSUE THREAD

**Issue by SebRosander** [terraform-providers/terraform-provider-azurerm#7446]
### Community Note

* Please vote on this issue by adding a 👍  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The fuction app could have the same IP restrictions as the App Service. Therefore it would be great to add support for name, priority & action for function app. This should also be done to the slot. 

### New or Affected Resource(s)
* azurerm_function_app
* azurerm_function_app_slot

### Potential Terraform Configuration
```hcl
ip_restriction = {
     ip_address = "1.2.3.0/24" # This exists today
     name = "foo" 
     priority = 101 
  }

ip_restriction = {
     ip_address = "1.2.3.4/32" # This exists today
     name = "bar"
     priority = 100 
     action = "Deny"
  }
]   
```
References
#6705 #6388 #6900

**Comment by jackofallops** [comment]
closed by #7945 - released in 2.23.0
