### ISSUE TITLE
Support for associating a Application Gateway WAF policy to an Application Gateway

### ISSUE THREAD

**Issue by rstra** [terraform-providers/terraform-provider-azurerm#7448]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an application gateway WAF policy, you can choose to associate one or more application gateways or HTTP listeners to the policy you are creating. There is no way to associate this Application Gateway WAF policy with the application gateway in terraform.

https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/create-waf-policy-ag#create-a-policy

Similar to the `azurerm_network_interface_application_gateway_backend_address_pool_association` resource, you could choose the Id of both the application gateway WAF policy and the application gateway to associate the policy.

Attributes:
- `waf_policy_id` (string)
- `application_gateway_id` (string): Required 
- `http_listener` (string): (Optional) Used to associate a http listner with the WAF policy

### New or Affected Resource(s)

* azurerm_web_application_firewall_policy_application_gateway_association

### Potential Terraform Configuration

```hcl
resource "azurerm_web_application_firewall_policy_application_gateway_association" "example" {
  association_type        = "ApplicationGateway"
  waf_policy_id           = azurerm_web_application_firewall_policy.example.id
  application_gateway_id  = azurerm_application_gateway.example.id
}
```

### References

* https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/create-waf-policy-ag#create-a-policy

**Comment by piotrgwiazda** [comment]
Currently, azurerm_application_gateway has "firewall_policy_id" that allows associating a WAF Policy on the Application Gateway level. 
https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html

However, this does not allow to associate a WAF Policy to a listener which is a useful case.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. For associating a WAF Policy on the Application Gateway level, I assume it has been implemented by [terraform](https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#firewall_policy_id). So suggest to close this issue. For associating a WAF Policy to a listener, suggest to file another new one. Thanks.

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment - but please let us know if this is still an issue and we'll take another look.

Thanks!
