### ISSUE TITLE
Feature Request: please add the ability to specify site_config in azurerm_function_app

### ISSUE THREAD

**Issue by dcherniv** [terraform-providers/terraform-provider-azurerm#745]
azurerm_app_service supports site_config options. Since functions is essentially an app_service, please add the ability to specify site_config for it.
Without this, there's no way to control things like 32/64 bit workers and others.
![image](https://user-images.githubusercontent.com/19437418/35285727-249adeb0-002c-11e8-9d29-5a415fe0c777.png)

**Comment by tombuildsstuff** [comment]
hey @dcherniv 

Thanks for opening this issue :)

So that we can look into this (and that there's differences between the App Service site config and a Function App site config) - would it be possible to know which fields are you looking to use within the `site_config` block?

Thanks!

**Comment by dcherniv** [comment]
@tombuildsstuff 
From: https://www.terraform.io/docs/providers/azurerm/r/app_service.html
always_on - (Optional) Should the app be loaded at all times? Defaults to false.
use_32_bit_worker_process - (Optional) Should the App Service run in 32 bit mode, rather than 64 bit mode?

use_32_bit_worker_process is probably more important because for me when function_app was provisioned with the following, it defaulted to 32 bit workers for some odd reason.

```
resource "azurerm_function_app" "default" {
  name                      = "${var.name}"
  location                  = "${var.region}"
  resource_group_name       = "${var.rg_name}"
  app_service_plan_id       = "${var.as_plan_id}"
  storage_connection_string = "${var.storage_connection}"
  app_settings              = "${var.app_settings}"
  tags {
     Environment    = "${var.tag_env}"
     Name           = "${var.tag_name}"
     Owner          = "${var.tag_owner}"
     Contact        = "${var.tag_contact}"
     CostProject    = "${var.tag_cost}"
     "Resource Group" = "${var.rg_name}"
  }
}
```

**Comment by gunzip** [comment]
I'd add [client_affinity_enabled as well](https://github.com/terraform-providers/terraform-provider-azurerm/blob/9257fc3233e5650620cc1562e9ea81d1bbf0784b/azurerm/resource_arm_app_service.go#L167):
https://www.terraform.io/docs/providers/azurerm/r/app_service.html#client_affinity_enabled

This is very important in the context of Functions which are served behind an API management resource:
when you have client_affinity_enabled the Function backend sends a cookie with a domain which is not the same as the one of the API gateway.

**Comment by gunzip** [comment]
always_on is now supported thanks of
https://github.com/terraform-providers/terraform-provider-azurerm/pull/695
