### ISSUE TITLE
Rules engine associations are removed when updating Frontdoor

### ISSUE THREAD

**Issue by jmacgowa-ks** [terraform-providers/terraform-provider-azurerm#7452]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.15.0

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

https://gist.github.com/jmacgowa-ks/5b200ba0a65bd83d9db617ec4e71ec3e

### Debug Output

https://gist.github.com/jmacgowa-ks/6995f731a6d43de0a1319bc3b30a0322

### Expected Behavior

While support for Rules engine configurations on Frontdoor resources is not yet available, any existing rules engine associations attached to routing rules should be left untouched when updating a Frontdoor resource.

### Actual Behavior

Rules engine associations are stripped from routing rules contained within the Frontdoor resource with no indication within the plan or apply stages that this will take place.

### Steps to Reproduce

1. `terraform apply` to deploy the Frontdoor.
2. From the portal, add a Frontdoor rules engine configuration.
```
Example:
Rules Engine Name: testrule
Rule Name: sourcerule
Action: Request header
Operator: Append
Header name: X-Source
Header value: frontdoor
```
3. Associate the rules engine configuration to a routing role within the Frontdoor resource deployed by Terraform.
4. `terraform apply` to update the Frontdoor.
5. Verify that the rules engine routing rule association has now been removed.

### Important Factoids

Changing a terraform deployed frontdoor resource from the portal causes all references (frontend_endpoints, backend_pool_name, health_probe_name, and load_balancing_name) to be altered from what Terraform deployed. While doing an export template comparison it looks like there are differences in resource ID capitalization between Azure and Terraform. Any post terraform apply will want to re-add those references. This would be another bug that is possibly the cause of this one.

**Comment by tombuildsstuff** [comment]
hi @jmacgowa-ks 

Thanks for opening this issue.

At this time Terraform doesn't support FrontDoor's Rule Engine Associations - support for that is being tracked in #7455 - as such I'm going to close this issue in favour of #7455 which looks to add support for that, which'll ultimately fix this - would you mind subscribing to that issue for updates?

Thanks!
