### ISSUE TITLE
Support for generation 2 azure VMs

### ISSUE THREAD

**Issue by NickAiello** [terraform-providers/terraform-provider-azurerm#7454]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Support creation of generation 2 Virtual Machines. Currently, there is no option to specify the generation 2 hypervisor when setting the `size` to a gen2 instance type. For example, setting `size = Standard_DC4s_v2` results in an error such as this:
```
Error: Error creating Linux Virtual Machine “nickgen2test-0” (Resource Group “nickgen2test-resources”): 
compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 – 
Original Error: Code=“BadRequest” Message=“The selected VM Size ‘Standard_DC4s_v2’ cannot boot Hypervisor
Generation ‘1’. If this was a Create operation please check that the Hypervisor Generation of the Image matches
the Hypervisor Generation of the selected VM Size.
If this was an Update operation please select a Hypervisor Generation ‘1’ VM Size.”
```
Since there is no available option to specify the "Generation" as the error message indicates, generation 2 vms cannot be created.

### New or Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_virtual_machine`

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine" "example" {
  ...
  generation = 2
  size = var.azureInstanceType
  ...
}
```
`generation` type int
  Must be either `1` or `2` matching the generation of the specified `size`. Defaults to 1

### References

* https://docs.microsoft.com/en-us/azure/virtual-machines/windows/generation-2

**Comment by sean-nixon** [comment]
@NickAiello I noticed this issue and thought I'd chime in. We've successfully deployed many Gen2 VMs using the `azurerm_linux_virtual_machine` resource. We're also using a VM size that also supports Gen 1, though, so it's not exactly that same as your configuration.  Still, it might be worth double checking if you are using a `gen2` VM image that supports UEFI. https://docs.microsoft.com/en-us/azure/virtual-machines/windows/generation-2#azure-cli

**Comment by NickAiello** [comment]
Hi @sean-nixon,
Thanks for the reply! I did not realize from the error I was seeing, but it was in fact the sku. Changing to sku = "16_04-lts-gen2" successfully deployed my gen2 image. That makes this enhancement request entirely unnecessary.

Appreciate the info, saved me a bit of trouble!
