### ISSUE TITLE
CosmosDB capabilities receives a string, not multiple values

### ISSUE THREAD

**Issue by Fernandomatsuo** [terraform-providers/terraform-provider-azurerm#7467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12.24
AzureRM 2.12.0

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl

resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }
}

```

### Expected Behavior

I expected to send multiple values to enable more than one capability at the same time. 

Example: 

```hcl
  capabilities {
    name = ["EnableAggregationPipeline","mongoEnableDocLevelTTL","MongoDBv3.4"]
  }
```

### Actual Behavior

Capabilities can receive only one value as a string, so I can not enable more than one  capability at the same time. 

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html

**Comment by yupwei68** [comment]
Hi @Fernandomatsuo , thanks for opening this issue. You're right that multiple capabilities are supported. Please try my code as bellows, I have tested with success:
```
resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }
  capabilities {
    name = "mongoEnableDocLevelTTL"
  }
  capabilities {
    name = "MongoDBv3.4"
  }

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    location          = azurerm_resource_group.test.location
    failover_priority = 0
  }
}
```

**Comment by Fernandomatsuo** [comment]
It works... Thanks, @yupwei68 !

**Comment by Fernandomatsuo** [comment]
We should add this information (or a sample) in docs.

[https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html](https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html)

**Comment by yupwei68** [comment]
Hi @Fernandomatsuo , 

It's about definition of set in HCL.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the Community Resources. I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html)..

Thanks!

**Comment by tombuildsstuff** [comment]
Agreed this wants an example in the docs - @yupwei68 could you send a PR for that adding a couple of capabilities to the example?
