### ISSUE TITLE
AKS cluster creating additional route table, additional NSG and its not using existing custom route table and NSG

### ISSUE THREAD

**Issue by sivamca127** [terraform-providers/terraform-provider-azurerm#7474]
Hi All,

I've recently started working on terraform with azure. As part of it i've gone through the documentation as much as possible to create resources. in this i'm trying to create AKS cluster. I was able to created successfully. but i've few concerns( which i felt bugs, correct if i'm wrong).

1) At present during AKS cluster provision, **aks-engine will create route table & Network security automatically**. i don't see any option to prevent these in terraform documentaion. As i wanted use existing route-table and NSG as because i'm under corporate network.

**expected behavior : ASK should pick existing route table and NSG instead of creating new resources.**
here is my code snippet. kindly help me.

```
provider "azurerm" {
    version = "~> 2.15"
    features {}
 }

resource "azurerm_resource_group" "aks" {
    name     = var.resource_group
    location = var.location
}
#fetch existing subnet 
data "azurerm_subnet" "aks" {
    name                 = var.subnetname
    virtual_network_name = var.virtual_network_name
    resource_group_name  = var.vnet_resource_group
}

resource "azurerm_subnet_network_security_group_association" "aks" {
    subnet_id                 = data.azurerm_subnet.aks.id
    network_security_group_id = var.network_security_group
}

resource "azurerm_route_table" "aks"{
    name                          = var.subnetname
    resource_group_name           = azurerm_resource_group.aks.name
    location                      = azurerm_resource_group.aks.location
    disable_bgp_route_propagation = false

    route{
        name                = var.route_name
        address_prefix      = var.route_address_prefix
        next_hop_type       = var.route_next_hop_type
    }

}
resource "azurerm_subnet_route_table_association" "aks" {
    subnet_id      = data.azurerm_subnet.aks.id
    route_table_id = azurerm_route_table.aks.id
}
resource "azurerm_kubernetes_cluster" "aks" {
    name                    = azurerm_resource_group.aks.name
    resource_group_name     = azurerm_resource_group.aks.name
    location                = azurerm_resource_group.aks.location
    dns_prefix              = "akstfpoc"   #The dns_prefix must contain between 3 and 45 characters, and can contain only letters, numbers, and hyphens. It must start with a letter and must end with a letter or a number.
    kubernetes_version      = "1.15.10"
    private_cluster_enabled = false
    node_resource_group     = var.node_resource_group
    
    api_server_authorized_ip_ranges = [] #var.api_server_authorized_ip_ranges
    default_node_pool {
        enable_node_public_ip   = false
        name                    = "agentpool" 
        node_count              = var.node_count
        orchestrator_version    = "1.15.10"
        vm_size                 = var.vm_size
        os_disk_size_gb         = var.os_disk_size_gb
        vnet_subnet_id          = data.azurerm_subnet.aks.id
    }

    linux_profile {
        admin_username = var.admin_username
        ssh_key {
            key_data = var.ssh_key
        }
    }
    service_principal {
        client_id     = var.client_id
        client_secret = var.client_secret
    }

    role_based_access_control {
        enabled = true
    }
    network_profile {
        network_plugin = "kubenet"
        #dns_service_ip     = "172.17.1.10"
        #service_cidr       = "172.16.0.0/14"
        pod_cidr           = "172.40.0.0/16"
        network_policy     = "calico"
        outbound_type      = "loadBalancer"
        load_balancer_sku  = "Standard"


        # load_balancer_profile {
        #     managed_outbound_ip_count = []
        #     outbound_ip_address_ids   = []
        #     outbound_ip_prefix_ids    = [""]
            
        # }
    }
            addon_profile {
            aci_connector_linux {
            enabled = false
        }

        azure_policy {
            enabled = false
        }

        http_application_routing {
            enabled = false
        }

        kube_dashboard {
            enabled = false
        }

        oms_agent {
            enabled = false
        }
    }
    
}

````

**Comment by stephenmoloney** [comment]
The key change required is  `outbound_type      = "userDefinedRoute"` and it should use the subnet with the route table. 

Please let me know how you get on.  If it works for you, I'm curious what the value you have  for `route_next_hop_type` as I'm in a very similar situation right now. I have the routetable created but traffic is not passing sucessfully. 

I'd appreciate if you could share how you get on.

**Comment by r0bnet** [comment]
@stephenmoloney are you sure you need to set that property like that? I skipped that value completely and it just works for me. We're using our internal Azure FW as next hop (target 0.0.0.0) and it's working.

**Comment by tombuildsstuff** [comment]
hi @sivamca127 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by stephenmoloney** [comment]
@r0bnet 
Thanks for the feedback.

Perhaps, your traffic isn't flowing through it but was a public ip address created when you went with `outbound_type = "loadBalancer"` ?

I don't want a public ip at all.

**Comment by sivamca127** [comment]
@stephenmoloney , its working with outboudn_type="UDR" but we need to set our internal Azure FW as next hop (target 0.0.0.0) and it's working. with this approach we can eliminate public ip generation.
