### ISSUE TITLE
Documentation Improvement: azurerm_application_gateway / backend_http_settings / request_timeout too low

### ISSUE THREAD

**Issue by mikebridge** [terraform-providers/terraform-provider-azurerm#7483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

The documentation at https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html uses a default timeout that is too low.
 
Microsoft support suggests the `request_timeout` for the Application Gateway should be 30 or 60 seconds.  The example suggests a `request_timeout` of 1 second, which for me generates many failed requests.

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  
// ...
  backend_http_settings {
    name                  = local.http_setting_name
    // ...
    request_timeout       = 1 # <--- should be 30 or 60
  }

```

### Expected Behavior

This should configure an application gateway with a practical timeout value in seconds

### Actual Behavior

Requests through the gateway time out.

### Important Factoids

I am setting up an http server on an Azure Container Instance behind an Azure gateway, using the above configuration *[taken from the documentation](https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#example-usage)*. The http request usually reaches the container instance but often the gateway times out before the response is processed.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Hopes [this](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7512) would be helpful.
