### ISSUE TITLE
Terraform fails to validate Service bus Subscription Rule SQL filter

### ISSUE THREAD

**Issue by RiverPhillips** [terraform-providers/terraform-provider-azurerm#7488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.12 
Azurerm 1.30

### Affected Resource(s)

* ` azurerm_servicebus_subscription_rule `

### Expected Behavior

Terraform plan should fail if SQL rule does not conform to the grammar defined [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-sql-filter)

### Actual Behavior

Terraform plan suceeds, the apply step fails, this has deleted valid rules and left subscriptions without any rules.

### Steps to Reproduce

1. Define a servcie bus subscription rule with and invalid SQL rule
2. `terraform plan`
3. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @RiverPhillips 

Thanks for opening this issue.

There's been a substantial number of changes between the v1.30 release and today (v2.15, at the time of writing) - are you able to confirm if this behaviour is present in the latest version?

Thanks!

**Comment by RiverPhillips** [comment]
using 2.15 I receive the following error, it still allows the plan but fails on the apply step with the following error

``` 
Error: Error issuing create/update request for Service Bus Subscription "tfex_sevicebus_rule" (Resource Group "tfex-servicebus-subscription-rule-sql", namespace "github-issue-7488-namespace"): servicebus.RulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="There was an error parsing the SQL expression. [Token line=2, column=0, Token in error= , Additional details= syntax error, unexpected EOF]  TrackingId:d9828cbe-a672-408f-9a58-8e3e32e4bd55_B0, SystemTracker:NoSystemTracker, Timestamp:2020-06-25T14:36:40 CorrelationId: 92ca73aa-310f-3581-3b13-d37d56ba64b9"
```

Here's the example causing the error: https://gist.github.com/RiverPhillips/d5bf105950eea5a64d11a043a922241f

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked [related API documents](https://github.com/Azure/azure-sdk-for-go/tree/master/services/servicebus/mgmt/2017-04-01/servicebus),  seems there is no exposed API to check the availability of the sql filter rule. So I assume terraform cannot validate it for now.

**Comment by katbyte** [comment]
I'm going to close this as its been nearly a year, please do let us know if this is still an issue for you!
