### ISSUE TITLE
Documentation - frontdoor - backend_pools_send_receive_timeout_seconds

### ISSUE THREAD

**Issue by Poil** [terraform-providers/terraform-provider-azurerm#7493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi

It looks like the default backend_pools_send_receive_timeout_seconds is 30 and not 60 like it's in the Terraform manual (https://www.terraform.io/docs/providers/azurerm/r/frontdoor.html#backend_pools_send_receive_timeout_seconds)

Ref. https://docs.microsoft.com/en-us/azure/frontdoor/front-door-troubleshoot-routing#503-response-from-front-door-after-a-few-seconds
This symptom happens when either your backend takes beyond the timeout configuration (default is 30 seconds) to receive the request from Front Door or if it takes beyond this timeout value to send a response to the request from Front Door. (...) configure the sendReceiveTimeout field for your Front Door to extend the default timeout up to 4 minutes (240 seconds). The setting is under the backendPoolSettings and is called sendRecvTimeoutSeconds.

Best regards,

**Comment by kshitijcode** [comment]
@Poil @tombuildsstuff I am interested to contribute. How do I assign this to myself?
Will be my first open-source contribution :)

**Comment by magodo** [comment]
@Poil Thank you for submitting this!

Terraform is not necessarily to set the same default value as API/Portal. Is there some specific reason that you want to change the default timeout to 30?

**Comment by WodansSon** [comment]
This issue has become stale due to lack of response. So I am going to go ahead and close this issue as such. If you encounter this error again in the new provider please feel free to open a new issue and I will address it. Thanks again! 🚀
