### ISSUE TITLE
Support for minimum elastic worker instance count on app service

### ISSUE THREAD

**Issue by brandonh-msft** [terraform-providers/terraform-provider-azurerm#7502]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enable setting the minimum plan worker count and minimum app worker count for Elastic Premium app service and Function App instances

![image](https://user-images.githubusercontent.com/20270743/85785601-513a6d80-b6de-11ea-9053-0f77b8448b74.png)

We have [max worker count](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#maximum_elastic_worker_count) available today, but not minimum (according to docs)

### New or Affected Resource(s)

* azurerm_app_service_plan
* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_plan" "fxnapp" {
  name                         = var.tierName
  location                     = var.location
  resource_group_name          = azurerm_resource_group.fxnrg.name
  kind                         = "elastic"
  maximum_elastic_worker_count = 100
# new property
  minimum_plan_instances = 3
  sku {
    tier = "ElasticPremium"
    size = "EP3"
  }
}
```

The `pre_warmed_instance_count` option for `azurerm_function_app` handles the pre-warmed section, but that number cannot exceed the minimum worker count of the plan. As such I'm not sure the pre-warmed property is even useful today if we're not able to increase the worker count. Or, does this take care of changing the worker count of the associated plan automatically?

### References

* #0000

**Comment by jigeay** [comment]
Please note that issue #8284 was created for azurerm_app_service, not azurerm_app_service_plan

**Comment by nexxai** [comment]
I did some quick digging and it doesn't look like this option is even supported in the latest azure-sdk-for-go.  I know someone on here has made requests to MS to get items added to the SDK but I don't remember how or when to reference.
