### ISSUE TITLE
Front door key vault certificate validation fails if value known after apply

### ISSUE THREAD

**Issue by elliots** [terraform-providers/terraform-provider-azurerm#7509]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "main" {
  frontend_endpoint {
    name                              = "frontend"
    host_name                         = local.hostname
    custom_https_provisioning_enabled = true
    web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.main.id
    custom_https_configuration {
      certificate_source = "AzureKeyVault"
      azure_key_vault_certificate_vault_id = data.azurerm_key_vault_certificate.main.key_vault_id
      azure_key_vault_certificate_secret_name = data.azurerm_key_vault_certificate.main.name
      azure_key_vault_certificate_secret_version = data.azurerm_key_vault_certificate.main.version
    }
  }
}

data "azurerm_key_vault_certificate" "main" { 
  name         = local.certificate_name
  key_vault_id = azurerm_key_vault.main.id

  depends_on = [ azurerm_key_vault_certificate.letsencrypt ]
}

```

### Expected Behavior

The certificate data is loaded before any validation is run

### Actual Behavior

It runs the validation straight away, which means the secret version and vault id are missing (empty string) from `custom_https_configuration` and the validation fails.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If i comment out the validation code and build my own provider binary, it creates everything successfully. 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/622455/85917248-d323c580-b89b-11ea-8098-e7a07a59b08c.png">

<img width="401" alt="image" src="https://user-images.githubusercontent.com/622455/85917453-7b865980-b89d-11ea-8636-b10400d3419c.png">

### References

* #5933

**Comment by elliots** [comment]
I'm happy to submit a pull request to 
 - remove the validation, on the assumption that azure will tell us if we try to create it with the wrong or missing values
 - run the validation just before sending the request to azure 
 - something else?

**Comment by WodansSon** [comment]
@elliots, this logic has changed multiple times since you opened this issue. I believe this issue will no longer repro in the current provider. I am closing this issue, but by all means if you still hit this issue please open a new issue I an I will address it. Thanks again! 🚀
