### ISSUE TITLE
Support for update existing AKS to enable uptime SLA

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [terraform-providers/terraform-provider-azurerm#7530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"
  sku_tier            = "Paid"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }
}
```
default value for sku_tier is `Free`. In terraform changing sku_tier from `Free` to `Paid` forces a new resource to be created. https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#sku_tier. Now Azure AKS supports to upgrade existing clusters to Uptime SLA paid SKU.

### References

* https://docs.microsoft.com/en-us/azure/aks/uptime-sla#modify-an-existing-cluster-to-use-uptime-sla
* https://github.com/Azure/AKS/issues/1603#issuecomment-651335745

**Comment by asubmani** [comment]
I am facing the same issue. Using terraform: **0.12.29**  and 1azurerm_provider` : **2.20.0** 

## BELOW WORKAROUND WORKS:

1.  Modify your terraform .tf files to add `sku_tier = paid`
2.  Use `az cli` commands to set `uptime-sla`
2.  Run terraform plan and then apply

## Actual Commands:

```py
az aks update --resource-group $RG --name $AKS --uptime-sla
```
```hcl
terraform plan -var-file="stg-terraform.tfvars" -out='stg.plan' -parallelism=200
terraform apply stg.plan
```

> NOTE: DO NOT run `terraform apply`  if `terraform plan` reports any change.
