### ISSUE TITLE
azurerm_policy_set_definition support for policyDefinitionGroups

### ISSUE THREAD

**Issue by cananac** [terraform-providers/terraform-provider-azurerm#7532]
Hi,
 
Can you add support for policyDefinitionGroups to azurerm_policy_set_definition ?

Thanks,
Canan

**Comment by ArcturusZhang** [comment]
Hi @cananac thanks for this issue!

This feature has already been introduced and released in [this PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/9259), therefore I am going to close this issue. Thanks again!
