### ISSUE TITLE
Support for a separate Terraform resource to add a subscription to a management group

### ISSUE THREAD

**Issue by ZachTB123** [terraform-providers/terraform-provider-azurerm#7541]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have a resource for adding a subscription to a management group. Currently the [azurerm_management_group](https://www.terraform.io/docs/providers/azurerm/r/management_group.html) resource exists which allows you to create a management group and then specify a list of subscriptions that will be assigned to the management group using `subscription_ids`. This does not work well in our situation because we have separate repos/state files for managing the management group hierarchy and for managing deployments to the subscriptions. In the repo that manages the management group hierarchy I had to `ignore_changes` on `subscription_ids` and then in the repo that manages subscriptions, I had to create a script that is called via a `null_resource` which just adds a subscription to the management group id that is passed in. I would like to replace this script with a Terraform resource.

### New or Affected Resource(s)

* `azurerm_management_group_subscription_membership`

### Potential Terraform Configuration

```hcl
resource azurerm_management_group_subscription_membership membership {
    management_group_name = "group-name-here"
    subscription_id = "subscription-id-that-should-be-added-to-management_group_name"
}
```

### References

This would potentially be similar to how you have the option to use [azurerm_network_security_rule](https://www.terraform.io/docs/providers/azurerm/r/network_security_rule.html) for creating NSG rules, or you can define them directly in the [azurerm_network_security_group](https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html) resource.

* #0000

**Comment by tombuildsstuff** [comment]
hi @ZachTB123 

Thanks for opening this issue :)

Taking a look through it appears that this will be implemented as (and is blocked/dependent on) #1216 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #1216 for updates?

Thanks!
