### ISSUE TITLE
azurerm_linux_virtual_machine_scale_set  terminate_notification  can't apply.

### ISSUE THREAD

**Issue by Dmitry1987** [terraform-providers/terraform-provider-azurerm#7544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.27
+ provider.azurerm v2.9.0
+ provider.cloudflare v2.6.0
+ provider.consul v2.7.0

### Affected Resource(s)
azurerm_linux_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "set" {
  name                = "${var.name}-${var.global_vars.environment}-set"
  resource_group_name = var.global_vars.resource_group
  location            = var.global_vars.location
  sku                 = var.vm_size
  instances           = var.number_of_servers
  zones               = [1, 2, 3]
  upgrade_mode        = "Manual"
  scale_in_policy     = "NewestVM"
  ...
  terminate_notification {
    enabled = true
    timeout = "10"
  }
...
...
...
```

### Debug Output
```
2020/06/30 21:01:09 [WARN] module.api: eval: *terraform.EvalValidateResource, non-fatal err: expected 'P' period mark at the start: 10
2020/06/30 21:01:09 [ERROR] module.api: eval: *terraform.EvalSequence, err: expected 'P' period mark at the start: 10
  on ../modules/server-group/main.tf line 51, in resource "azurerm_linux_virtual_machine_scale_set" "set":
  51: resource "azurerm_linux_virtual_machine_scale_set" "set" {

Error: expected 'P' period mark at the start: 10

  on ../modules/server-group/main.tf line 51, in resource "azurerm_linux_virtual_machine_scale_set" "set":
  51: resource "azurerm_linux_virtual_machine_scale_set" "set" {
```

### Expected Behavior
apply to work

### Actual Behavior
error about something missing?

### Steps to Reproduce
Try to use a terminate_notification block in azurerm_linux_virtual_machine_scale_set I guess, should do it.

Any ideas what it might be? the block doesn't get accepted by terraform :(

**Comment by tombuildsstuff** [comment]
hey @Dmitry1987 

Thanks for opening this issue.

Taking a look into this, the Azure API (and thus Terraform) require that this field is specified as a `ISO8601 Duration` ([examples](https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm)) - meaning that this needs to be formatted as (presuming seconds) `P10S`. 

Would you be able to take a look and see if that works for you? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but if that doesn't work then please let us know and we'll take another look.

Thanks!

**Comment by Dmitry1987** [comment]
thanks @tombuildsstuff ! it worked, I did `timeout = "P10M"`. Never saw this format before.
