### ISSUE TITLE
Support for Data Factory linked service connection to Databricks

### ISSUE THREAD

**Issue by markhoiland** [terraform-providers/terraform-provider-azurerm#7553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A common connection pattern for Azure Data Factory is to connect via a linked service to Azure Databricks workspaces.  Currently a Terraform resource does not exist for this linked service option in Data Factory.

### New or Affected Resource(s)

* azurerm_data_factory_linked_service_databricks

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_linked_service_databricks" "example" {
  name    =  "example"
  resource_group_name   = azurerm_resource_group.example.name
  data_factory_name  = azurerm_data_factory.example.name
  databricks_workspace_url  = data.azurerm_databricks_workspace.workspace_url
  databricks_access_token  = "exampleToken"
  description  = "example text"
  newclusternodetype  = "Standard_D3_v2"
  newclusternumworker  = "1:10"
  newClusterVersion  = "4.0.x-scala2.11"
}
```

### References

* https://docs.microsoft.com/en-us/azure/data-factory/compute-linked-services#azure-databricks-linked-service
* https://techcommunity.microsoft.com/t5/azure-data-factory/support-for-azure-databricks-instance-pool-for-operationalizing/ba-p/901006

**Comment by nfx** [comment]
it might be better to add [Managed Service Identity](https://techcommunity.microsoft.com/t5/azure-data-factory/azure-databricks-activities-now-support-managed-identity/ba-p/1922818). [databricks](https://github.com/databrickslabs/terraform-provider-databricks) provider can be used to set everything up in workspace itself.

**Comment by allantargino** [comment]
I was going to develop the initial version using MSI and existing workspaces/clusters, but unfortunately the go sdk doesn't support it yet (because the REST API doc is not updated)

References:
- https://docs.microsoft.com/en-us/rest/api/datafactory/linkedservices/createorupdate#azuredatabrickslinkedservice
- `AzureDatabricksLinkedServiceTypeProperties` at https://raw.githubusercontent.com/Azure/azure-sdk-for-go/master/services/datafactory/mgmt/2018-06-01/datafactory/models.go
- https://techcommunity.microsoft.com/t5/azure-data-factory/azure-databricks-activities-now-support-managed-identity/ba-p/1922818

**Comment by allantargino** [comment]
The proposed design would be:

```hcl
resource "azurerm_data_factory_linked_service_databricks" "example" {
  name    =  "example"
  resource_group_name   = azurerm_resource_group.example.name
  data_factory_name  = azurerm_data_factory.example.name

  databricks_workspace_id = azurerm_databricks_workspace.example.id
  databricks_cluster_id  = databricks_cluster.example.id
}
```

**Comment by nfx** [comment]
@allantargino i’d suggest to expose userProperties field for simplicity purposes. We should not limit running jobs from ADF only on existing clusters - running jobs on newCluster is at least 30%-40% cheaper.

Would you be open to a call on this?
