### ISSUE TITLE
Changing ultra_ssd_enabled should not force recreation

### ISSUE THREAD

**Issue by NilsBusche** [terraform-providers/terraform-provider-azurerm#7556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform v0.12.24`
* `terraform-provider-azurerm_v2.16.0_x5`

### Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_windows_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "instance" {

  [...]

  additional_capabilities {
    ultra_ssd_enabled = false
  }
}

```

### Expected Behavior

Changing `ultra_ssd_enabled` should be possible without recreation if the VM is stopped/deallocated.

### Actual Behavior

Changing `ultra_ssd_enabled` requires recreation of the VM resource also if the VM is stopped/deallocated. This possible using Azure CLI as well.

### Steps to Reproduce

1. Create configuration for a virtual machine as described above
2. `terraform apply`
3. Change `ultra_ssd_enabled` to `true`
4. `terraform plan/apply`

**Comment by jpbuecken** [comment]
This logic is similar to SKU (instance size) change, isn't it? -> Offline possible, no recreate needed.
