### ISSUE TITLE
azurerm_subnet enforce_private_link_endpoint_network_policies not working

### ISSUE THREAD

**Issue by colin-lyman** [terraform-providers/terraform-provider-azurerm#7563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.28
Azure Provider 2.16

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "example"
  name                 = "testsubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]

  enforce_private_link_endpoint_network_policies = false

 # I also set some service_endpoints
}
```

### Debug Output

Terraform completes successfully with no errors.

### Expected Behavior

running: az network vnet subnet show -g <resource_group_name> -n <subnet_name> --vnet-name <vnet name>
Should show "privateEndpointNetworkPolicies" are "Disabled"

### Actual Behavior

Running this command:

az network vnet subnet show -g <resource_group_name> -n <subnet_name> --vnet-name <vnet name>

which outputs the config for the subnets still shows that "privateEndpointNetworkPolicies" are "Enabled"

### Steps to Reproduce

See Above command

**Comment by colin-lyman** [comment]
CORRECTION - This isnt a bug, instead is a language issue.  

setting enforce_private_link_endpoint_network_policies = false means "privateEndpointNetworkPolicies" are "Enabled"

It makes more sense that true = Enabled and false = Disabled IMO

**Comment by gstevens-kyriba** [comment]
See provider details:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/subnet.html.markdown

**Comment by marrobi** [comment]
Agree, just wasted 30 mins on this. It's the wrong way round.

**Comment by tombuildsstuff** [comment]
Taking a look through here this is a documentation bug, we should fix this up so that it's clearer - @WodansSon as you've the most context on this would you mind sending a PR for this?

It's worth noting that Terraform intentionally doesn't mirror the Azure API, CLI and Portal behaviour, and diverges where it makes sense - since (as in this case) the field name reflects the boolean behaviour, rather than the inverse in the Azure CLI - so I'd recommend checking the documentation for the canonical reference here (albeit this needs updating as described above)

**Comment by marrobi** [comment]
@tombuildsstuff  thanks for the prompt reply. 

In your docs, network policies are defiend as follows:

> Network policies, like network security groups (NSG), are not supported for Private Link Endpoints or Private Link Services.

The behavior I'm observing is that setting `enforce_private_link_endpoint_network_policies` to `true` **disables** - i.e. the **opposite** of enforcing, the network policies for private link resources, hence enabling you to deploy private link resources into the subnet.

**Comment by moriyoshi** [comment]
I don't think I'll be convinced this is merely a documentation problem.  What is super-misleading is that the attribute names don't imply the semantics behind them at all.  One could suppose a true value would be treated as `Disabled` if it the attribue were named `disable_private_link_endpoint_network_policies` just how the corresponding argument of CLI is named.  This ends up making me believe that `enforce_private_link_endpoint_network_policies` and `enforce_private_link_service_network_policies` have to be renamed as `disable_*` if you really need to stick to the CLI semantics.

There are nothing unintuitive for the relevant properties of Azure RM as both `PrivateEndpointNetworkPolicies, PrivateEndpointNetworkPolicies` and `PrivateLinkServiceNetworkPolicies` take either `Enabled` or `Disabled`, not booleans.
