### ISSUE TITLE
Support for URL rewrite in azurerm_application_gateway

### ISSUE THREAD

**Issue by rstra** [terraform-providers/terraform-provider-azurerm#7565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft has a preview feature which allows URL rewrites to be part of a rewrite rule set. 

### New or Affected Resource(s)

* azurerm_applicatiion_gateway

### Potential Terraform Configuration

```hcl
  rewrite_rule_set {
    name = "example_rewrite_rule_set"

    rewrite_rule {
      name          = "example_rule"
      rule_sequence = 100
      
      condition {
        ignore_case = true
        negate      = true
        pattern     = "\\/\\w+"
        variable    = "var_request_uri"
      }
      url_configuration {
        components     = url_path
        url_path_value  = "/example.aspx"
      }
    }
}
```

**Comment by Console32** [comment]
Is there any plan to implement this features? Would you welcome a PR or will preview features not be implemented?

**Comment by tombuildsstuff** [comment]
@Console32 we'd definitely welcome a PR for this if you're interested 👍 - from our side we support features in Public Preview features but need to be sure this is highlighted as a preview feature (and thus, unfortunately subject to breaking changes in the Azure API)

**Comment by Console32** [comment]
@tombuildsstuff Thanks for the fast reply, I started working on a PR. Will evaluate if the url rewrites work for our use case and finish it if we will proceed with this that approach.

**Comment by Console32** [comment]
@tombuildsstuff We will go with virtual applications on app services instead of URL rewrites on the AGW therefore I can not work on this. Will probably work on https://github.com/terraform-providers/terraform-provider-azurerm/issues/1422 instead.

**Comment by RavulaChetan** [comment]
Any update on this?

**Comment by kbeaugrand** [comment]
Hi, 

URL rewrite is no more in preview on Azure Application Gateway. 
Any update ? 

Any body is working on a PR ?

**Comment by jonhadfield** [comment]
[This page](https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-url-portal) still says `URL rewrite feature is in preview and is available only for Standard_v2 and WAF_v2 SKU of Application Gateway. It is not recommended for use in production environment.`  
Where did you read that it's now GA?

**Comment by kbeaugrand** [comment]
Sorry,

It was maybe a mistake from my part but actual Azure portal doesn't mention anymore that this is a preview feature.

![image](https://user-images.githubusercontent.com/9513635/100131350-35e9af00-2e84-11eb-8df2-bc6aaa208ffe.png)

A few weeks ago, this  was clearly mentioned.

**Comment by piyush94** [comment]
Azure Docs content will be updated soon. https://github.com/MicrosoftDocs/azure-docs/issues/70710

**Comment by dhensby** [comment]
I have begun working on this in #10950
