### ISSUE TITLE
Moving MSSQL database between elastic pools

### ISSUE THREAD

**Issue by phatcher** [terraform-providers/terraform-provider-azurerm#7568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation (and plan) says that it will destroy/re-create a database if it is moved between elastic pools (or back to stand-alone).

Considering that Azure supports this with zero downtime, why does the provider drop/re-create, makes it almost useless?

### New or Affected Resource(s)

* azurerm_mssql_database

### References
https://docs.microsoft.com/en-us/azure/azure-sql/database/scripts/move-database-between-elastic-pools-powershell

**Comment by yupwei68** [comment]
Hi @phatcher , thanks for opening this issue. I'd like to raise another related issue to service team about disassociating sql db from elastic pool, which is the reason why I set `elastic_pool_id` as `forceNew`. Please track this issue: https://github.com/Azure/azure-rest-api-specs/issues/10031.

**Comment by phatcher** [comment]
If I look at the powershell example, we have...
```
# Move the database to the second pool
$firstDatabase = Set-AzSqlDatabase -ResourceGroupName $resourceGroupName `
    -ServerName $serverName `
    -DatabaseName $firstDatabaseName `
    -ElasticPoolName $secondPoolName

# Move the database into a standalone performance level
$firstDatabase = Set-AzSqlDatabase -ResourceGroupName $resourceGroupName `
    -ServerName $serverName `
    -DatabaseName $firstDatabaseName `
    -RequestedServiceObjectiveName "S0"
```
So my approach would be to look at the underlying Powershell code to see what API calls it is actually making, these two cases cover off changing the associated pool and setting the database to standalone.
