### ISSUE TITLE
Feature Request: Display Version Call-out in Documentation on terraform.io

### ISSUE THREAD

**Issue by jzampieron** [terraform-providers/terraform-provider-azurerm#757]
This is a documentation feature request. It would be good for the provider docs to call out the version of the AzureRM provider from which they were generated and to which they are applicable.

https://www.terraform.io/docs/providers/azurerm/index.html

My suggestion is to change the page title to "Azure Provider - vX.Y.Z" and add a version section.

Including a short changelog at the bottom of the page should also be considered.

**Comment by tombuildsstuff** [comment]
👋 

Versioned documentation is now available [on the Terraform Registry](https://registry.terraform.io/providers/hashicorp/azurerm/1.43.0/docs) as such I believe this issue's resolved :)
