### ISSUE TITLE
Unable to create SQL SQL Failover Group while secondary databases is managed through Terraform

### ISSUE THREAD

**Issue by ankitkotnala** [terraform-providers/terraform-provider-azurerm#7570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version terraform {
  required_version = ">= 0.12"
}

provider "azurerm" {
  version         = "~> 2.0"
  features {}
}

### Affected Resource(s)

* `azurerm_sql_failover_group`

### Terraform Configuration Files

```hcl
resource "azurerm_sql_failover_group" "es-us" {
  name                = "failover-group"
  resource_group_name = azurerm_resource_group.essql.name
  server_name         = azurerm_sql_server.essrvr.name
  databases           = [azurerm_sql_database.esdb.id]
  partner_servers {
    id = azurerm_sql_server.wssrvr.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 60
  }

  depends_on = [azurerm_sql_database.wsdbprd]
}
```

### Debug Output

Error issuing create/update request for SQL Failover Group "es-failover-group" (Resource Group "xxxxxxxxxx", Server "es-prd-sql-xxxxx"): sql.FailoverGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="FailoverGroupUnableToPerformGroupOperationOnDatabases" Message="The operation cannot be performed due to multiple errors." Details=[{"code":"45138","message":"The destination database name 'xxxxx' already exists on the server 'xxxxxxxxx'."}][0m

### Actual Behavior

Create a SQL Fail over group with target DB

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If you try omit the target DB from code and just create the fail over group without any dependency it works 

### References
 As per documentation at : https://www.terraform.io/docs/providers/azurerm/r/sql_failover_group.html

```
NOTE: The failover group will create a secondary database for each database listed in databases. If the secondary databases need to be managed through Terraform, they should be defined as resources and a dependency added to the failover group to ensure the secondary databases are created first.
```

* #0000

**Comment by yupwei68** [comment]
Hi @ankitkotnala , thanks for opening this issue. I don't think Azure Sql failover group support to fail over group a source sql db with a target existing db. It'll create a target db. I have tried in Portal, it doesn't support it with an existing db either. 

I think the Terraform resource doc [sql_failover_group](https://www.terraform.io/docs/providers/azurerm/r/sql_failover_group.html) might have caused some misunderstandings. It means for example in the code, failover group will back up your sql db1(server1) to server2, by creating a db1 in server2. If you wish to manage the db1 in server2, you could create a configuration of resource sql db for the db1(server2). And you should add a dependency to the sql db.

```
resource "azurerm_sql_failover_group" "es-us" {
  name                = "failover-group"
  resource_group_name = azurerm_resource_group.essql.name
  server_name         = azurerm_sql_server.server1.name
  databases           = [azurerm_sql_database.db1.id]
  partner_servers {
    id = azurerm_sql_server.server2.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 60
  }
}

resource "azurerm_sql_database" "test"{
   name = azurerm_sql_database.db1.name
   resource_group_name = ...
   server_name = azurerm_sql_server.server2.name
   ...
   
  depends_on = [azurerm_sql_failover_group.es-us]
}
```
