### ISSUE TITLE
Support for Azure Data Factory dataset for Azure Data Lake Storage Gen2

### ISSUE THREAD

**Issue by markhoiland** [terraform-providers/terraform-provider-azurerm#7573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Azure Data Factory dataset option for Azure Data Lake Storage Gen2 is required to be used along with the linked service for a common data analytics pattern.

### New or Affected Resource(s)

* azurerm_data_factory_dataset_data_lake_storage_gen2

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_dataset_data_lake_storage_gen2" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  data_factory_name   = azurerm_data_factory.example.name
  format _type  = "json"
  linked_service_name = azurerm_data_factory_linked_service_data_lake_storage_gen2.example.name
  file_system  = "filesystem"
  folder_path   = "directory/subfolder"
  file_name  = "filename"
  import_schema = []
  annotations = []
  compression_type = "gzip"
  parameters   = {}
}
```

### References

* https://docs.microsoft.com/en-us/azure/data-factory/concepts-datasets-linked-services#dataset-type

* https://docs.microsoft.com/en-us/azure/data-factory/connector-azure-data-lake-storage#dataset-properties

**Comment by allantargino** [comment]
Possible duplicated of #7103

**Comment by tombuildsstuff** [comment]
Thanks for the heads up @allantargino - agreed this looks to be a duplicate - @markhoiland would you mind subscribing to #7103 for updates?
