### ISSUE TITLE
Issue with App Service Plan and App Services Deployment with certificates and hostname binding via terraforms

### ISSUE THREAD

**Issue by rkpundhir90** [terraform-providers/terraform-provider-azurerm#7578]
### Error Message -

1. Error: Error creating/updating App Service Plan "ASP-rg-dev-irisplus" (Resource Group "rg-dev-irisplus"): web.AppServicePlansClient#CreateOrServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Ms not available in resourceessage="Requested feature is not available in resource group rg-dev-irisplus. Please try using a different resourquested feature is not avaice group or create a new one." Details=[{"Message":"Requested feature is not available in resource group rg-dev-ie":"BadRequest"},{"ErrorEntrisplus. Please try using a different resource group or create a new one."},{"Code":"BadRequest"},{"ErrorEntity":rg-dev-irisplus. Please try{"Code":"BadRequest","ExtendedCode":"59324","Message":"Requested feature is not available in resource group rg-deresource group {0}. Pleasev-irisplus. Please try using a different resource group or create a new one.","MessageTemplate":"Requested feature is not available in resource group {0}. Please try using a different resource group or create a new one.","Parameters":["rg-dev-irisplus"]}}]

2.  
![issue-app-service](https://user-images.githubusercontent.com/7354091/86470625-6a37c400-bd59-11ea-8248-7e2f9e93846d.png)

###  Terraform Script Used - 

```
resource "azurerm_app_service_plan" "servplan" {
  name                = "ASP-${azurerm_resource_group.rg.name}"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "Linux"
  reserved            = "true"
  sku {
    tier = "Standard"
    size = "S1"
  }

   depends_on = [azurerm_subnet.subnets1]
}

resource "azurerm_app_service" "appService" {
  name                = "${var.app_name}-${var.environment}"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  app_service_plan_id = azurerm_app_service_plan.servplan.id

  https_only          = "true"
  site_config {
    dynamic "ip_restriction" {
      for_each = var.ip_restrictions
      content {
        ip_address  = ip_restriction.value
      }
    }
  }
  tags = {
    Description = var.app_name
    environment = var.environment
    ASKID = var.askId
  }
  depends_on = [azurerm_subnet.subnets1]
}
resource "azurerm_app_service_certificate" "certificate" {
  name                = "example-cert"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  pfx_blob            = filebase64("${var.custom_hostname}.pfx")
  password            = data.azurerm_key_vault_secret.appserv-tls-pwd.value
}
resource "azurerm_app_service_custom_hostname_binding" "hostName" {
  hostname            = var.custom_hostname
  app_service_name    = azurerm_app_service.appService.name
  resource_group_name = azurerm_resource_group.rg.name
  ssl_state           = "IpBasedEnabled"
  thumbprint          = azurerm_app_service_certificate.certificate.thumbprint

  depends_on = [azurerm_app_service_certificate.certificate]
}

resource "azurerm_app_service_virtual_network_swift_connection" "app-service-vnet" {
 app_service_id = azurerm_app_service.appService.id
 subnet_id      = azurerm_subnet.subnets1.id
}
```

### Complete Error Log File for scenario -1 
[logs_azure.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/4869759/logs_azure.log)

**Comment by tombuildsstuff** [comment]
hi @rkpundhir90 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
