### ISSUE TITLE
Feature Request: support for custom IPsec/IKE policies

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#759]
As raised by @dominik-lekse in https://github.com/terraform-providers/terraform-provider-azurerm/pull/133#issuecomment-360162801:

Azure has added support for custom IPsec/IKE policies (see https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-ipsecikepolicy-rm-powershell)

**Comment by TheCookster** [comment]
Any progress on Terraform supporting custom IPsec/IKE policies in Azure?
