### ISSUE TITLE
Azure DB for PostgreSQL collation changes automatically (see #396)

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-azurerm#760]
Hi there,

I've placed a note on Issue #396 noting that the proposed work-around is no longer effective, apparently due to Azure performing better validation.

Therefore, please re-visting this issue.

Cheers!

**Comment by stuart-shelton-hmcts** [comment]
(To confirm, we're still using Terraform 0.10.5...)

**Comment by stuart-shelton-hmcts** [comment]
Additionally, if a configuration block defines `pgsql_srv_name` (a field which the platform rejects if it contains any upper-case characters) as, say, `pg-localenv`, then having applied this configuration, a subsequent plan will show:
```
-/+ module.pgsql-repo.azurerm_postgresql_database.pgsql_db (new resource required)
<...>
      name:                         "pg_localenv_db" => "pg_localenv_DB" (forces new resource)
```
... noting both that the hyphens in the configuration and now transformed into underscores, that an extra three characters have been added, and that the capitalisation of these characters is inconsistent!

**Comment by stuart-shelton-hmcts** [comment]
If the `srv_name` is updated to the apparently required value (with a '_DB' suffix) the error is still:

```
* azurerm_postgresql_server.pgsql_srv: postgresql.ServersClient#Create: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="InvalidServerName" Message="Server name 'pg_localenv_DB' cannot be empty or null. It can only be made up of lowercase letters 'a'-'z', the numbers 0-9 and the hyphen. The hyphen may not lead or trail in the name."
```

**Comment by stuart-shelton-hmcts** [comment]
Okay, ignore me - the '_DB'/'_db' thing was a local problem with a custom module we're using.

That just leaves the collation issue where 'en_US' becomes 'en-US', resulting in the original value appearing to be a change.

This is still present in terraform `0.11.2` with azurerm provider `1.1.0`.

**Comment by cpressland** [comment]
We're seeing the same thing, when provisioning with this block:

```
resource "azurerm_postgresql_database" "devExample" {
  name = "example"
  resource_group_name = "${azurerm_resource_group.devWestEurope.name}"
  server_name = "${azurerm_postgresql_server.devExample.name}"
  charset = "UTF8"
  collation = "en-GB"
}
```

We recieve the following error:

```
* azurerm_postgresql_database.devExample: Long running operation terminated with status 'Failed': Code="InvalidDatabaseCollation" Message="The provided database collation is invalid."
```

If we switch the collation to `en_GB`, provisioning works, but then subsiquent `terraform apply` tasks try to recreate the resource. For now, we're provisioning as `en_GB` and then modifying the resource to `en-GB` after to prevent recreation.

**Comment by jeffreyCline** [comment]
**Confirmed:** Still repro's in `GA 2017-12-01 PostgreSQL` API.

**Comment by jeffreyCline** [comment]
**Confirmed:** Per #396 if you attempt to provision `azurerm_postfresql_database` with the collation set to `en-US` it fails with the error message:
`* azurerm_postgresql_database.test: Long running operation terminated with status 'Failed': Code="InvalidDatabaseCollation" Message="The provided database collation is invalid."`

**Comment by jeffreyCline** [comment]
I have a fix for this issue based on the `u-PostgreSQL` branch which is pending merge with `Master` with PR #1190 

What I did was:
* Exposed a new validator which verifies that a collation **does not** include a dash (-)
* Exposed a new `AzureRMNormalizeCollation` function which on read replaces the malformed collation received from the Azure API into a valid collation which avoids the destroy/recreate issue #396 and #760

I will create a PR once #1190 has been merged.

**Comment by achandmsft** [comment]
@joshgav is there a plan to eventually fix this in Go SDK? @jeffreyCline please create a bug in their repo to track this as well.

**Comment by jeffreyCline** [comment]
@achandmsft @joshgav Opened tracking issue [#1862](https://github.com/Azure/azure-sdk-for-go/issues/1862) in the `azure-sdk-for-go` repository.
