### ISSUE TITLE
Updating the ZoneRedundant property on a namespace is not supported

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [terraform-providers/terraform-provider-azurerm#7606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "eventhub_namespace" {
  name                = var.namespace_name
  location            = var.location
  resource_group_name = var.resource_group_name
  sku                 = "Standard"
  capacity            = var.capacity
  auto_inflate_enabled = true
  maximum_throughput_units = var.maximum_throughput_units

  zone_redundant = true
...
}
```

### Debug Output
```
        sku                                 = "Standard"
        tags                                = {
            "environment" = "prod"
            "pattern"     = "choreo-prod"
            "project"     = "choreo"
            "terraform"   = "true"
        }
      ~ zone_redundant                      = false -> true
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
````

### Panic Output
```
Error: eventhub.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Updating the ZoneRedundant property on a namespace is not supported. CorrelationId: 4028e511-43cc-622e-f7ae-9c2bf0e5d980"

  on ../../../modules/azurerm/EventHub-Namespace/eventhub_namespace.tf line 1, in resource "azurerm_eventhub_namespace" "eventhub_namespace":
   1: resource "azurerm_eventhub_namespace" "eventhub_namespace" {
```

### Expected Behavior
Enable zone_redundant in eventhub namespace.

### Actual Behavior
Terraform fails

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/pull/7534

**Comment by favoretti** [comment]
I suppose I need to force resource re-creation there..
