### ISSUE TITLE
Support for adding Azure AD admin user on Azure Database for MySQL server

### ISSUE THREAD

**Issue by AdamCoulterOz** [terraform-providers/terraform-provider-azurerm#7607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Database for MySQL supports adding an Azure AD administrator account for the MySQL server, but the Azure provider for Terraform doesn't have any facility for this. A new resource equivalent to these should be created for this:

- `azurerm_sql_active_directory_administrator` (Azure SQL)
- `azurerm_postgresql_active_directory_administrator` (PostgreSQL)

Relevant MS docs:
- User Docs: (https://docs.microsoft.com/en-us/azure/mysql/concepts-azure-ad-authentication)
- API Docs: (https://docs.microsoft.com/en-us/rest/api/mysql/serveradministrators/createorupdate)

### New or Affected Resource(s)

__`azurerm_mysql_active_directory_administrator`__

### Potential Terraform Configuration

```hcl
resource "azurerm_mysql_active_directory_administrator" "example" {
  server_name         = azurerm_mysql_server.example.name
  login               = data.azuread_user.admin_user.mail
  user_object_id      = data.azuread_user.admin_user.object_id

   // can we avoid needing to set a resource group?
   // it can only ever be the same as the `azurerm_mysql_server.example`
  resource_group_name = azurerm_resource_group.example.name

   // does this need to be set if it can only ever be the tenant_id 
   // ... of the `azurerm_mysql_server.example`?
  tenant_id           = data.azurerm_client_config.current.tenant_id
}
```

**Comment by evertonmc** [comment]
Configuration will use the same format as the referenced existing resources
```
resource "azurerm_mysql_active_directory_administrator" "example" {
  server_name         = azurerm_mysql_server.example.name
  resource_group_name = azurerm_resource_group.example.name
  login               = "sqladmin"
  tenant_id           = data.azurerm_client_config.current.tenant_id
  object_id           = data.azurerm_client_config.current.object_id
}
```
