### ISSUE TITLE
Azure Key Vault Secret - Resource Creation Fails When Tag Has Empty Value

### ISSUE THREAD

**Issue by sjbodzo** [terraform-providers/terraform-provider-azurerm#7609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

``` 
Terraform v0.12.28
+ provider.azurerm v2.17.0
```

> Note: Issue replicated in AzureRM provider versions `2.10, 2.14, 2.15, and 2.16`

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "key_vault" {
  name                            = var.name
  location                        = var.location
  resource_group_name             = var.resource_group_name
  tenant_id                       = var.tenant_id
  enabled_for_disk_encryption     = var.enabled_for_disk_encryption
  enabled_for_deployment          = var.enabled_for_deployment
  enabled_for_template_deployment = var.enabled_for_template_deployment
  tags                            = var.tags
  sku_name                        = var.sku_name

  dynamic "access_policy" {
    for_each = var.access_policies
    iterator = policy
    content {
      tenant_id               = policy.value.tenant_id
      object_id               = policy.value.object_id
      key_permissions         = policy.value.key_permissions
      secret_permissions      = policy.value.secret_permissions
      certificate_permissions = policy.value.certificate_permissions
    }
  }

  dynamic "network_acls" {
    for_each = var.network_acls
    iterator = nacl
    content {
      default_action = nacl.value.default_action
      bypass         = nacl.value.bypass
      ip_rules                   = nacl.value.ip_rules
      virtual_network_subnet_ids = nacl.value.virtual_network_subnet_ids
    }
  }
}

resource "azurerm_key_vault_secret" "secrets" {
  name         = var.secret["name"]
  value        = var.secret["value"]
  key_vault_id = azurerm_key_vault.key_vault.id

  tags = var.tags
}
```

### Debug Output

https://gist.github.com/sjbodzo/759ac4d44f2dd71cfb916ba16503802f

### Panic Output

N/A

### Expected Behavior

Expected behavior is for the Key Vault to create the secret successfully.  

### Actual Behavior

The actual behavior observed is that the `terraform apply` failed with the error in the debug output link above: the property has an invalid value. 

### Steps to Reproduce

1. Create an `azurerm_key_vault` resource within your Terraform workspace / project. 
2. Create an `azurerm_key_vault_secret` resource within your Terraform workspace / project. 
3. Assign a `var.tags` object where *at least one of the keys in the tag variable has an empty value*. 
    For example: `tags = { foo: "bar", baz: "" }`
4. `terraform apply`

### Important Factoids

- This only occurs when the tags included on the `azurerm_key_vault_secret` include a tag key with an empty string for the value.

**Comment by njuCZ** [comment]
Hi @sjbodzo I am sorry that I could not reproduce this problem in my local. Here is my config
```
variable "tags" {
  default = {
      foo = "bar"
      baz = ""
  }
}

data "azurerm_key_vault" "test" {
  name                            = "xxx"
  resource_group_name = "xxx"
}

resource "azurerm_key_vault_secret" "test" {
  name            = "secret-test"
  value            = "test"
  key_vault_id = data.azurerm_key_vault.test.id

  tags = var.tags
}
``` 

everything is right and I don't see there is any error

**Comment by tombuildsstuff** [comment]
@njuCZ in the original post above the tags are set on both the Key Vault and the Key Vault Secret, so it looks like the issue is on the Key Vault resource?

**Comment by njuCZ** [comment]
@tombuildsstuff @sjbodzo I tried following config to create a key vault and key vault secret with empty tags, it seems everything is right and there is no diff in my local.
```
variable "tags" {
  default = {
      foo = "bar"
      baz = ""
  }
}

provider "azurerm" {
    features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "test" {
  name                        = "xxx"
  location                    = "xxx"
  resource_group_name         = "xxx"
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get",
      "set"
    ]

    storage_permissions = [
      "get",
    ]
  }

  tags = var.tags
}

resource "azurerm_key_vault_secret" "test" {
  name         = "secret-test"
  value        = "test"
  key_vault_id = azurerm_key_vault.test.id

  tags = var.tags
}
```

**Comment by sjbodzo** [comment]
Thank you @njuCZ for trying to reproduce. 

@tombuildsstuff may be right, that the actual issue is key vault related, since it appears I have applied the same tagging onto both. The error itself appears to be specific to complaining about the `azurerm_key_vault_secret` though.

**Comment by sjbodzo** [comment]
Perhaps it is something with the `value` field of the secret item resolving to an empty string in a lookup?

`value = var.secret["value"]` yielding a blank versus a `null` value type, for example?
