### ISSUE TITLE
Can't deploy a zip file to a function_app_slot

### ISSUE THREAD

**Issue by chrisgallivan** [terraform-providers/terraform-provider-azurerm#7618]
Can you point me to a working example of deploying a zip file to a function_app_slot?

Here is the gist:
###########################################################
###########################################################

provider "azurerm" {
   client_id = var.deployment_client_id
   client_secret = var.deployment_client_secret
   version = "~> 2.9.0"
   subscription_id= var.deployment_subscription_id
   tenant_id= var.deployment_tenant_id
   features {}
}

###########################################################
###########################################################

# create resource group
resource "azurerm_resource_group" "rg"{
name = "11679MMoparInnovationCloud-rg"
location = "eastus"
tags     = {                   
   "appid" = "11679" 
}                              
}

resource "azurerm_app_service_plan" "app" {
  name                = "ASP-11679MMoparInnovationCloudrg-8226"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "functionapp"
  sku {
    tier = "Dynamic"
    size = "Y1"
  }
  tags                         = {
          "AMS ID" = "11577"
          "appid"  = "11679"
  }
}

resource "azurerm_function_app" "function" {
  name                      = "cct-gsdp-vehicles-search"
  location                  = azurerm_resource_group.rg.location
  resource_group_name       = azurerm_resource_group.rg.name
  app_service_plan_id       = azurerm_app_service_plan.app.id
  storage_account_name     = azurerm_storage_account.storage.name
  storage_account_access_key = azurerm_storage_account.storage.primary_access_key 
  version                   = "~3"
  daily_memory_time_quota  = 0
  enable_builtin_logging   = false
  
  tags                         = {
          "AMS ID" = "11577"
          "appid"  = "11679"
  }
  app_settings                 = {
           "APPINSIGHTS_INSTRUMENTATIONKEY"        = "d4d22018-da2e-497d-8f60-d56e027b08df"
           "APPLICATIONINSIGHTS_CONNECTION_STRING" = "InstrumentationKey=d4d22018-da2e-497d-8f60-d56e027b08df"
           "FUNCTIONS_WORKER_RUNTIME"              = "java"
           "JAVA_HOME"                             = "D:\\Program Files\\Java\\jdk1.8.0_25"
           "TEST_FLAG"                             = "@Microsoft.KeyVault(VaultName=azuredemokeyvaulttest;SecretName=TestFlag;SecretVersion=d5d68f4ae4cf4bf4b6a6aa4f53d5de78)"
           "VEHICLES_SEARCH_API_KEY"               = "123" 
           "VEHICLES_SEARCH_CLIENT_ID"             = "123" 
           "VEHICLES_SEARCH_CLIENT_SECRET"         = "123" 
           "VEHICLES_SEARCH_GATEWAY_API_ID"        = "123" 
           "VEHICLES_SEARCH_GATEWAY_TOKEN_API_ID"  = "123" 
           "VEHICLES_SEARCH_LOCALE"                = "en-US" 
           "VEHICLES_SEARCH_TOKEN_URL"             = "https://prod-24.eastus.logic.azure.com:443/workflows/6b1eb935b8e84e368e93c540a05c2099/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6Dn9Sf21X_D-yvJM3GCj9UKI8jaWXWUqAKbg85HWQJA"
           "VEHICLES_SEARCH_URL"                   = "123"
     	     HASH = "${base64encode(filesha256(var.local_artifact_location))}"
           WEBSITE_RUN_FROM_PACKAGE = "https://${azurerm_storage_account.storage.name}.blob.core.windows.net/${azurerm_storage_container.service-storage-container.name}/${azurerm_storage_blob.service-storage-blob.name}${data.azurerm_storage_account_sas.service-storage-account-sas.sas}"

        }

        
}

resource "azurerm_storage_account" "storage" {
  name                     = "cctgsdpvehiclessearch"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  enable_https_traffic_only = true
  tags = {
          "ms-resource-usage" = "azure-cloud-shell"
          "appid"  = "11679"

  }
  account_kind              = "Storage"
}

resource "azurerm_function_app_slot" "slot" {
  name                     = "dev"
  location                 = azurerm_resource_group.rg.location
  resource_group_name      = azurerm_resource_group.rg.name
  app_service_plan_id      = azurerm_app_service_plan.app.id
  function_app_name        = azurerm_function_app.function.name
  storage_account_name     = azurerm_storage_account.storage.name
  storage_account_access_key = azurerm_storage_account.storage.primary_access_key 
  version                  = "~3"
  enable_builtin_logging         = false 
 
 
  app_settings               = {
           "APPINSIGHTS_INSTRUMENTATIONKEY"        = "d4d22018-da2e-497d-8f60-d56e027b08df"
           "APPLICATIONINSIGHTS_CONNECTION_STRING" = "InstrumentationKey=d4d22018-da2e-497d-8f60-d56e027b08df"
           "FUNCTIONS_WORKER_RUNTIME"              = "java"
           "GSDP_TOKEN_API_BODY"                   = "grant_type=client_credentials&client_id={{clientid}}&scope=integration.fcl.fcagcv.com/CAP.vehiclesearch"
           "JAVA_HOME"                             = "D:\\Program Files\\Java\\jdk1.8.0_25"
           "TEST_FLAG"                             = "TRUE"
           "TOKEN_KEY"                             = "2fodrliked2br1vas0ajdqq66h"
           "TOKEN_SECRET"                          = "13gmha46t1rel7a8eeqitjilc4q9d5rgm1jjtmddddef7e85of72"
           "TOKEN_URL"                             = "https://prod-24.eastus.logic.azure.com:443/workflows/6b1eb935b8e84e368e93c540a05c2099/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6Dn9Sf21X_D-yvJM3GCj9UKI8jaWXWUqAKbg85HWQJA"
           "VEHICLES_SEARCH_API_KEY"               = "ajSDlGFmEQ1qfwhNSNZjd3tbT7SbmnFQ8QJxQRfw"
           "VEHICLES_SEARCH_LOCALE"                = "en_US"
           "VEHICLE_SEARCH_API_URL"                = "https://prod-18.eastus.logic.azure.com:443/workflows/f3429c9c8ba7424887773445f2d5b5e7/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=rusTAR-CvpMMP33Nl0DJZQu8frjMWk4lG5nfnQ0n9h0"
           "language"                              = "en_US"
           "x-apigw-api-id"                        = ""
      
     } 
                                                        

   daily_memory_time_quota        = 0
   tags                           = {
           "appid" = "11679"
        }
timeouts {}
}

resource "azurerm_storage_container" "service-storage-container" {
  name                  = "function-releases"
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "service-storage-blob" {
  name = "cctgsdpvehiclessearch"
  storage_account_name   = azurerm_storage_account.storage.name
  storage_container_name = azurerm_storage_container.service-storage-container.name
  type   = "Block"
  source = var.local_artifact_location
}

data "azurerm_storage_account_sas" "service-storage-account-sas" {
  connection_string = azurerm_storage_account.storage.primary_connection_string
  https_only        = false
  resource_types {
    service   = false
    container = false
    object    = true
  }
  services {
    blob  = true
    queue = false
    table = false
    file  = false
  }
  start  = "2020-07-1"
  expiry = "2030-07-1"
  permissions {
    read    = true
    write   = false
    delete  = false
    list    = false
    add     = false
    create  = false
    update  = false
    process = false
  }
}

**Comment by tombuildsstuff** [comment]
hi @chrisgallivan 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
