### ISSUE TITLE
azurerm_cosmosdb_mongo_collection: Blocks of type "index" are not expected here.

### ISSUE THREAD

**Issue by ShwetaT0mer** [terraform-providers/terraform-provider-azurerm#7652]
Terraform script:

resource "azurerm_cosmosdb_mongo_database" "db" {
  name                = var.database_name
  resource_group_name = azurerm_cosmosdb_account.acc.resource_group_name
  account_name        = azurerm_cosmosdb_account.acc.name
}

resource "azurerm_cosmosdb_mongo_collection" "example" {
  name                  = var.collection_name
  resource_group_name   = azurerm_cosmosdb_account.acc.resource_group_name
  account_name          = azurerm_cosmosdb_account.acc.name
  database_name         = azurerm_cosmosdb_mongo_database.db.name

  default_ttl_seconds = "777"
  shard_key           = "accountID"
 
   indexes {
    keys = "transactionid"
    unique = true
  }
    
}

=======================================================================================
 terraform validate

Error: Unsupported block type

  on main.tf line 53, in resource "azurerm_cosmosdb_mongo_collection" "example":
  53:    index {

Blocks of type "index" are not expected here.

**Comment by yupwei68** [comment]
Hi @ShwetaT0mer , thanks for opening this issue. I suppose you mean block `index`. I have changed your code a little bit and I have tested it valid.

```
resource "azurerm_cosmosdb_mongo_collection" "example" {
  name                = "collection-yup"
  resource_group_name = azurerm_cosmosdb_account.acc.resource_group_name
  account_name        = azurerm_cosmosdb_account.acc.name
  database_name       = azurerm_cosmosdb_mongo_database.db.name

  default_ttl_seconds = "777"
  shard_key           = "accountID"

  index {
    keys   = ["transactionid"]
    unique = true
  }

}
```

**Comment by ShwetaT0mer** [comment]
I found out later that block index isn't supported in version 2.0.0 it's supported in newer versions.
Thanks
