### ISSUE TITLE
Unsupported argument orchestrator_version in azurerm_kubernetes_cluster_node_pool

### ISSUE THREAD

**Issue by leszekeljasz** [terraform-providers/terraform-provider-azurerm#7655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
$ terraform -v
Terraform v0.12.28
+ provider.azurerm v2.11.0
```

### Affected Resource(s)
* azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
variable "subscription_id" {
  type = string
  # default = "XXXXXXXXXXXXXXXX"
}

locals {
  region = "francecentral"
  virtual_network_cidr = "10.48.0.0/16"
}

terraform {
  required_version = ">=0.12"
  required_providers {
    azurerm = { version = "~>2.11.0" }
  }
}

provider "azurerm" {
  version         = ">=2.11.0"
  subscription_id = var.subscription_id
  features        {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg20200709"
  location = local.region
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet"
  resource_group_name = azurerm_resource_group.rg.name
  address_space       = [local.virtual_network_cidr]
  location            = local.region
}

resource "azurerm_subnet" "k8ssubnet" {
  name                  = "kubernetes"
  resource_group_name   = azurerm_resource_group.rg.name
  virtual_network_name  = azurerm_virtual_network.vnet.name
  address_prefixes      = [cidrsubnet(local.virtual_network_cidr, 4, 0)]
  service_endpoints     = []
  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_kubernetes_cluster" "akscluster" {
  name                = "akscluster"
  location            = local.region
  resource_group_name = azurerm_resource_group.rg.name
  kubernetes_version  = "1.15.11"
  dns_prefix          = "dnspref20200709"
  default_node_pool {
    name            = "default"
    vm_size         = "Standard_D2s_v3"
    node_count      = 1
    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.k8ssubnet.id
    type            = "VirtualMachineScaleSets"
  }
  role_based_access_control {
    enabled = true
  }
  addon_profile {
    http_application_routing {
      enabled = false
    }
  }
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "nodepool" {
  name                  = "mynodepool"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.akscluster.id
  orchestrator_version  = "1.15.10"

  vnet_subnet_id        = azurerm_subnet.k8ssubnet.id
  vm_size               = "Standard_D2s_v3"
  node_count            = 1
  os_disk_size_gb       = 30
}
```

### Debug Output
https://gist.github.com/leszekeljasz/aadb95c8991dc8d5c599be066399b487

### Expected Behavior

Terraform should recognize the `orchestrator_version` argument of `azurerm_kubernetes_cluster_node_pool` resource, as it appears as valid argument in the provider's doc. Specifying k8s version for a node pool is also supported in Azure.
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#orchestrator_version

### Actual Behavior

Terraform errors out with `Unsupported argument`:
```
$ terraform apply

Error: Unsupported argument

  on main.tf line 75, in resource "azurerm_kubernetes_cluster_node_pool" "nodepool":
  75:   orchestrator_version  = "1.15.10"

An argument named "orchestrator_version" is not expected here.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by davelosert** [comment]
I just stumbled across this and immidiately saw the issue:
The configuration option `orchestrator_version` only got introduced in this provider's version `v2.14.0` - but you are currently using `v2.11.0`.

If you update the provider-version, this should work (just tried it myself).

**Comment by tombuildsstuff** [comment]
hey @leszekeljasz 

Thanks for opening this issue.

As @davelosert has mentioned this property is available in a more recent version of the Azure Provider so you'll need to update the version of the Azure Provider being used here in order to configure this. You can do this by updating the version specified within the Provider block:

```hcl
provider "azurerm" {
  version = "=2.18.0" # the latest at the time of writing
  features {}
}
```

and then re-running `terraform init` which will download that version - at which point this property will be configurable - would you be able to take a look?

Since this should be fixed by updating the version of the Azure Provider being used here I'm going to close this issue for the moment - but if that doesn't work please let us know and we'll take another look.

Thanks!

**Comment by leszekeljasz** [comment]
Alright, sorry for the false alarm, I see now my provider version specification was messed up.
Thank you all!
