### ISSUE TITLE
There's a bug in Terraform

### ISSUE THREAD

**Issue by vermaaakansha** [terraform-providers/terraform-provider-azurerm#7658]
While creating Azure route table, Im getting below error. 

**Error: configuration for azurerm_route_table.this still contains unknown values during apply (this is a bug in Terraform; please report it!)**

Note- Firewall is getting deployed

Below is the snippet of the code..

#Firewall
module "Firewall" {
  source                   = "xxxx"
  resource_group_name      = module.xxx.resource_group_name 
  subnet_ids                        = module.xxx.map_subnet_ids
  firewalls                            = var.firewalls
  fw_network_rules             = var.fw_network_rules
  fw_nat_rules                     = var.fw_nat_rules
  fw_application_rules        = var.fw_application_rules
  firewall_additional_tags   = var.additional_tags
}
# Route Table 
resource "azurerm_route_table" "this" {
  name                          = "test-rt"
  location                      = "eastus2"
  resource_group_name           = module.xxx.resource_group_name
  disable_bgp_route_propagation = false
  route {
    name           = "azurefirewall"
    address_prefix = "0.0.0.0/0"
    next_hop_type  = "VirtualAppliance"
    next_hop_in_ip_address  = local.next_hop_in_ip_address
  }
  depends_on = [module.Firewall]
}
 
## route table association
resource "azurerm_subnet_route_table_association" "example" {
  subnet_id      = module.xxx.subnet_ids[4] /*Fifth subnet ID*/
  route_table_id = azurerm_route_table.this.id
  depends_on     = [azurerm_route_table.this]
}

locals {
  next_hop_in_ip_address = module.Firewall[0].firewall_private_ips
}

************************************************************
Can any one please help in resolving this error?

**Comment by magodo** [comment]
Hi @vermaaakansha Thank you for submitting this :+1:

This error might because `module.Firewall[0]` has the invalid index, so you might want to confirm the module has the expected output.

Additionally, would you please check which version of the terraform you are using? The useless error message has been improved since v0.12.11 (actually via hashicorp/terraform#22846).

**Comment by vermaaakansha** [comment]
closing this. this was resolved.
