### ISSUE TITLE
sku_name forces a replacement

### ISSUE THREAD

**Issue by gpthome** [terraform-providers/terraform-provider-azurerm#7666]
Through the Azure portal, one can change the DTUs for a database at will.  This is useful when I need to process a big job (increase the DTUs significantly, for a short period of time).
It appears that changing the "azurerm_mssql_database" sku_name forces a database replacement.  This is pretty significant.
![image](https://user-images.githubusercontent.com/5378257/87074733-e9f3e180-c1e4-11ea-9177-c8e2eb3ff570.png)
Is this the expected result?

Thanks.

**Comment by yupwei68** [comment]
Hi @gpthome , thanks for opening this issue. This has been fixed in PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/7559 and release in v2.18.0

**Comment by tombuildsstuff** [comment]
hi @gpthome 

As @yupwei68 has mentioned support for this shipped in v2.18.0 - you can upgrade to this by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=2.18.0"
  features {}
}
```

Thanks!

**Comment by gpthome** [comment]
Glad it's fixed.  Sorry I couldn't find it on my own. Thank you very much for the thorough response.  I'll upgrade and try it out.
