### ISSUE TITLE
Support for Blob Public Access setting in azurerm_storage_account

### ISSUE THREAD

**Issue by brycebarrickavanade** [terraform-providers/terraform-provider-azurerm#7673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Simply just want the ability to set the Blob Public Access setting on a storage account, couldn't find it in the documentation or in other feature requests

### New or Affected Resource(s)

azurerm_storage_account

### Potential Terraform Configuration

```
resource "azurerm_storage_account" "example" {
  name = "example"
  resource_group_name = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  blob_public_access = "true/false"   <-----         
}
```

### References

https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=azure-cli

**Comment by tombuildsstuff** [comment]
Closing in favour of #7738
