### ISSUE TITLE
Cycle: azurerm_virtual_machine.elastic_uk_0

### ISSUE THREAD

**Issue by sbutt** [terraform-providers/terraform-provider-azurerm#768]
Hi,

### Terraform Version
$ terraform version
Terraform v0.11.2
+ provider.azurerm v1.0.1
+ provider.template v1.0.0

### Affected Resource(s)
- azurerm_virtual_machine

### Terraform Configuration Files
https://gist.github.com/sbutt/d2398bf37c91d8430a347e21547c9255

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
none

### Expected Behavior
Was expecting all resources to stand up.

### Actual Behavior
Error: Error asking for user input: 1 error(s) occurred:

* Cycle: azurerm_virtual_machine.elastic_uk_0, data.azurerm_public_ip.elastic_uk_vm_pip_0

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Similar to issue 310, however when I tried the solution suggested there it complains that I've got a cycle. This is because the file resource is trying to access the IP address of the public IP, however data for the public IP depends on the VM (which has the file resource within it). 

### References
https://github.com/terraform-providers/terraform-provider-azurerm/issues/310

**Comment by tombuildsstuff** [comment]
hey @sbutt 

Thanks for opening this issue, apologies for the delayed response here!

It's possible to use [the `null_resource`](https://www.terraform.io/docs/providers/null/resource.html) to achieve this - for instance you can have the provisioner block within a `null_resource` taking the IP Address from the Public IP Data Source, as shown below:

```
resource "null_resource" "test" {
  depends_on = ["azurerm_virtual_machine.elastic_uk_0"]

 provisioner "file" {
    source  = "/setup_elasticsearch.sh"
    destination = "/home/adminuser/setup_elasticsearch.sh"

    connection {
      type        = "ssh"
      host        = "${data.azurerm_public_ip.elastic_uk_vm_pip_0.ip_address}"
      user        = "adminuser"
      private_key = "${file("~/.ssh/id_rsa")}"
      agent       = "false"
      timeout     = "1m"
    }
  }
}
```

Would you be able to take a look and see if that solves your issue?

Thanks!
