### ISSUE TITLE
Null values for parameters load_balancer_backend_address_pools_ids and load_balancer_inbound_nat_rules_ids 

### ISSUE THREAD

**Issue by horsey** [terraform-providers/terraform-provider-azurerm#769]
Hi there,

.### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.11.1
+ provider.azurerm v1.0.1
```
### Affected Resource(s)
- azurerm_network_interface

### Terraform Configuration Files
```hcl
#Module that creates the VMs
module "web" {
  source              = "Azure/compute/azurerm"                                                                                                                                                                                                
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  vm_hostname         = "${var.snap_web_hostname}"

  remote_port         = "${var.snap_web_remote_port}"
  nb_instances        = "${var.snap_instance_count}"
  nb_public_ip        = 0

  vm_os_publisher     = "Canonical"
  vm_os_offer         = "UbuntuServer"
  vm_os_sku           = "14.04.2-LTS"

  vnet_subnet_id      = "${module.network.vnet_subnets[1]}"
  boot_diagnostics    = "true"
  delete_os_disk_on_termination = "true"

  data_disk           = "true"
  data_disk_size_gb   = "64"
  data_sa_type        = "Premium_LRS"


  admin_username = "snap"
  ssh_key        = "~/.ssh/id_rsa.pub"
  tags           = "${var.snap_web_tags}"

  attach_to_lb = "true"

# These parameters are created by a different loadbalancer module 
  backend_address_pool = "${module.lb.azurerm_lb_backend_address_pool_id}"
  lb_nat_rules         = "${module.lb.azurerm_lb_nat_rule_ids}"
}

# Section of the module that attaches the NICs to the loadbalancer

<snip>
resource "azurerm_network_interface" "vm" {
  count                     = "${var.nb_instances}"
  name                      = "nic-${var.vm_hostname}-${count.index}"
  location                  = "${azurerm_resource_group.vm.location}"
  resource_group_name       = "${azurerm_resource_group.vm.name}"
  network_security_group_id = "${azurerm_network_security_group.vm.id}"

  ip_configuration {
    name                          = "ipconfig${count.index}"
    subnet_id                     = "${var.vnet_subnet_id}"
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = "${length(azurerm_public_ip.vm.*.id) > 0 ? element(concat(azurerm_public_ip.vm.*.id, list("")), count.index) : ""}"

# Receiving strings here instead of lists 
load_balancer_backend_address_pools_ids = "${var.attach_to_lb ? list(var.backend_address_pool) : list()}"
load_balancer_inbound_nat_rules_ids     = ["${element(concat(var.lb_nat_rules, list("")), count.index)}"]
  }

<snip>



```

### Debug Output
https://gist.github.com/horsey/fb2885b1c7e746f486a6e98fd38fdd36

### Panic Output
No

### Expected Behavior
``` load_balancer_backend_address_pools_ids```  and  ```load_balancer_inbound_nat_rules_ids ``` parameters treat  an empty list parameter correctly by not passing the same to Azure during resource creation. Can an empty string "" be given the same treatment? 
My use case: 
I am trying to have the above mentioned parameters passed to the implementation module via module parameters.
When these parameters are passed across modules, they don't seem to retain their original data type - a list. It appears that the list is converted to a string instead. 

How are these situations handled? 

Corollary, is there an universal NULL in Terraform that can be used for this?

**Comment by mytototo** [comment]
I have the exact same issue and have been looking for a solution for hours...
Any idea when a fix will be release? It currently blocks me completely.

Thanks.

**Comment by tombuildsstuff** [comment]
hi @horsey 

Thanks for opening this issue - apologies for the delayed response here!

In version 1.17 of the AzureRM Provider we added support for the `azurerm_network_interface_backend_address_pool_association` and `azurerm_network_interface_nat_rule_association` resources, which allow the association between a NIC and a Load Balancers Backend Address Pool / NAT Rule Association using these independent resources. At this time it's required to specify these fields both in the `azurerm_network_interface` resources and using the independent resources - however from version 2.0 of the AzureRM Provider these independent resources will be the only thing required to achieve this.

As such I believe it should be possible to use the independent `*_association` resources to achieve this and as such I'm going to close this issue for the moment.

Thanks!
