### ISSUE TITLE
Error building AzureRM Client: Azure CLI Authorization Profile was not found. on Windows 10 Sub-system Linux (Ubuntu)

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-azurerm#7708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.18.0
```

### Affected Resource(s)

* `azurerm`

### Terraform Configuration Files

```hcl
provider "azurerm" {
    version = "~> 2.18"
    features {}
}
resource "azurerm_resource_group" "rg" {
    name        = "rg-terraform-test"
    location    = "West US"

    tags = {
        environment = "Terraform Test RG"
    }
}
```

### Debug Output

https://gist.github.com/MatthewTatsch-fdx/be0a9695a49a2fa5fa7fd83647a9f261

### Expected Behavior

Create an execution plan

### Actual Behavior

```
Error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

  on resource_group.tf line 1, in provider "azurerm":
   1: provider "azurerm" {
```

### Steps to Reproduce

The issue only occurs when using Windows 10's Linux: Ubuntu sub-system. If I perform the same steps directly in Windows PowerShell I don't encounter the issue.

1. Open bash in Windows 10 sub-system for Linux: Ubuntu 
2. Run `az login` and authenticate as individual via browser
3. Run `terraform init`
4. Run `terraform plan`

**Comment by magodo** [comment]
@MatthewTatsch-fdx Thank you for submitting this!
Do you mind to check that in your WSL env, either file *$AZURE_CONFIG_DIR/azureProfile.json* or *~/.azure/azureProfile.json* exists and the content has valid json?
Besides, the default WSL has no GUI support, so CLI will fallback to device login, which displays a message telling you to enter a code in a specific URL. While you mentioned that you made the auth via a browser, so does that mean you have installed the GUI inside WSL, or do you run `az login` from (e.g.) PowerShell instead?

**Comment by MatthewTatsch-fdx** [comment]
Yes, _~/.azure/azureProfile.json_ exists with valid json.

When I `az login` from WSL it opens a browser via Windows, same as if I were to run from PowerShell.

**Comment by magodo** [comment]
Hi @MatthewTatsch-fdx it sounds like an environment setup issue.

Based on your debug out below:

> 2020/07/12 14:40:15 [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

I can tell the error comes from [here](https://github.com/hashicorp/go-azure-helpers/blob/master/authentication/auth_method_azure_cli_token.go#L37), where the actual error is hidden, though. [This function](https://github.com/Azure/go-autorest/blob/7ac73d3561eaa034f458f97362b2743e8b3c048e/autorest/azure/cli/profile.go#L67) basically read the token file and unmarshal the json it contains. So if you know a little Go, you might want to modify the [caller](https://github.com/hashicorp/go-azure-helpers/blob/master/authentication/auth_method_azure_cli_token.go#L37) a bit to keep the error (by wrapping it in `fmt.Errorf()`) and then we can see the exact error.

Another way we can try is to delete the file and run `az login` from WSL again, which will create the file if not exist. Then check if that file is regenerated as expected.

**Comment by tombuildsstuff** [comment]
👋 

Since unfortunately this is an environment specific issue we're unable to provide more granular suggestions here - and as such I'm going to close this issue for the moment. However if you're still seeing this issue then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
