### ISSUE TITLE
Dual SSL certificate issue

### ISSUE THREAD

**Issue by sabicd** [terraform-providers/terraform-provider-azurerm#7712]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.28

provider "azurerm" {
  version = "=2.18.0"
  features {}
}
```

### Affected Resource(s)

* `azurerm_application_gateway`

### Project setup
![image](https://user-images.githubusercontent.com/52485542/87280148-1a43c480-c4f2-11ea-9f24-1276cb9309c9.png)
![image](https://user-images.githubusercontent.com/52485542/87280240-37789300-c4f2-11ea-99ce-66e928ccd6c6.png)

### Additional information/context

Hello! We are using terraform to deploy one application gateway  (WAF, v1). Currently, we are facing an issue, where the wanted use-case is to have 2 separate certificates for the two domains that we use.

Workflow: Having 2 pfx files with their passwords provided, as the screenshot shows, but after applying the terraform scripts, we have a state where both uploaded certificates contain the same value, meaning the second domain uses the first domain SSL certificate. I'll provide screenshots of the setup, hopefully, someone could address this issue. Checked both pfx files, and when uploading manually, both certificates are valid.

### Expected Behavior

After applying the changes, the HTTP listeners would have the correct SSL certificate values, meaning all HTTP listeners would be valid, without throwing an SSL related error.

### Actual Behavior

After applying the changes all HTTP listeners that use HTTPS have the same SSL certificate value, even though we have 2 separate domains that have listeners.

### Steps to Reproduce
1 `Have listeners set up to use SSL certificates(at least two domain with one HTTP listener each)`
2. `Use WAF_v1 application gateway`
2. `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested with below tfconfig, seems I can attach these two certificates to application gateway. Maybe I missed something. Could you help to check whether below tfconfig is similar with yours? If not, could you provide your tfconfig that triggers this issue? And could you double check whether the certificates you passed are different?

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-appgw-test10"
  location = "eastus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctest-vnet-test10"
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
}

resource "azurerm_subnet" "test" {
  name                 = "subnet-test10"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.0.0/24"]
}

resource "azurerm_public_ip" "test" {
  name                = "acctest-pubip-test10"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Dynamic"
}

locals {
  backend_address_pool_name       = "${azurerm_virtual_network.test.name}-beap"
  frontend_port_name              = "${azurerm_virtual_network.test.name}-feport"
  frontend_port_name2             = "${azurerm_virtual_network.test.name}-feport2"
  frontend_ip_configuration_name  = "${azurerm_virtual_network.test.name}-feip"
  http_setting_name               = "${azurerm_virtual_network.test.name}-be-htst"
  listener_name                   = "${azurerm_virtual_network.test.name}-httplstn"
  listener_name2                  = "${azurerm_virtual_network.test.name}-httplstn2"
  request_routing_rule_name       = "${azurerm_virtual_network.test.name}-rqrt"
  ssl_certificate_name            = "${azurerm_virtual_network.test.name}-ssl1"
  ssl_certificate_name2           = "${azurerm_virtual_network.test.name}-ssl2"
}

resource "azurerm_application_gateway" "test" {
  name                = "acctestag-test10"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  
  sku {
    name     = "WAF_Medium"
    tier     = "WAF"
	capacity = 1
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.test.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 443
  }
  
  frontend_port {
    name = local.frontend_port_name2
    port = 8000
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.test.id
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 1
  }

  request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Https"
    ssl_certificate_name           = local.ssl_certificate_name
  }

  ssl_certificate {
    name     = local.ssl_certificate_name
    data     = filebase64("testdata/application_gateway_test.pfx")
    password = "terraform"
  }
  
  http_listener {
    name                           = local.listener_name2
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name2
    protocol                       = "Https"
    ssl_certificate_name           = local.ssl_certificate_name2
  }
  
  ssl_certificate {
    name     = local.ssl_certificate_name2
    data     = filebase64("testdata/application_gateway_test_2.pfx")
    password = "hello-world"
  }
}
```

Result on Azure portal:
![image](https://user-images.githubusercontent.com/19754191/87387431-47b56e80-c5d5-11ea-9c89-15c4b800b76e.png)
![image](https://user-images.githubusercontent.com/19754191/87387417-3e2c0680-c5d5-11ea-8ee5-2e456fa85225.png)

**Comment by sabicd** [comment]
Thanks for the answer! We have pretty much the same structure for the application gateway as you copied here. I modified ours to have the same order ( we had ssl_certificate blocks under each other and same goes for the HTTP_listeners as well), unfortunately it results in the same issue, where one of the http listeners( that uses domain X) gets the wrong SSL certificate ( cert for Domain Y). As I wrote above, uploading the same pfx file manually fixes the issue.

**Comment by sabicd** [comment]
We found the issue. It came from the fact that we tried to use the same frontend port definition ( same port number ) in both HTTPS listener, after moving them to different frontend port definitions, the issue went away. Thanks for caring @neil-yechenwei
