### ISSUE TITLE
azurerm_mysql_server: please update the example: the configuration is wrong

### ISSUE THREAD

**Issue by miiitch** [terraform-providers/terraform-provider-azurerm#7715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.18

### Affected Resource(s)

* `azurerm_mysql_server`

### Terraform Configuration Files
From the documentation at https://www.terraform.io/docs/providers/azurerm/r/mysql_server.html
```hcl
resource "azurerm_mysql_server" "example" {
  name                = "example-mysqlserver"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  administrator_login          = "mysqladminun"
  administrator_login_password = "H@Sh1CoR3!"

  sku_name   = "B_Gen5_2"
  storage_mb = 5120
  version    = "5.7"

  auto_grow_enabled                 = true
  backup_retention_days             = 7
  geo_redundant_backup_enabled      = true
  infrastructure_encryption_enabled = true
  public_network_access_enabled     = false
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
}
```

### Actual Behavior

Most of the fields are refused. For example `storage_mb` is not at the root of the resource by in a block called `storage_profile`

### References

* https://www.terraform.io/docs/providers/azurerm/r/mysql_server.html

**Comment by yupwei68** [comment]
Hi @miiitch , thanks for opening this issue. I have tested azurerm "2.18.0" and the example configuration runs well. Could you confirm that you are using azurerm "2.18.0"? If not, would you mind to upgrade the azurerm version?
The `storage_mb` in block `storage_profile` has been deprecated for a long time. (On fact, the whole block `storage_profile` is deprecated) Currently, we recommend to use the `storage_mb` in the root level.

**Comment by miiitch** [comment]
Hi, you are right. I do not know why the first time TF did not catch the latest version of the provider. Now I have all the warning you said.!
