### ISSUE TITLE
azurerm_eventhub_consumer_group doesn't support '$Default' consumer group name

### ISSUE THREAD

**Issue by olitomlinson** [terraform-providers/terraform-provider-azurerm#7720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.28
+ provider.azurerm v2.1.0

### Affected Resource(s)

* `azurerm_eventhub_consumer_group`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_consumer_group" "example" {
  name                = "$Default"
  namespace_name      = azurerm_eventhub_namespace.example.name
  eventhub_name       = azurerm_eventhub.example.name
  resource_group_name = azurerm_resource_group.example.name
  user_metadata       = "some-meta-data"
}
```

### Expected Behavior

Should have accepted the name `$Default` as this is the name that the azure portal assigns by default if one is not specified, when using the `Basic` Tier Event Hub Namespace.

### Actual Behavior

`Error: invalid value for name (The consumer group name can contain only letters, numbers, periods (.), hyphens (-),and underscores (_), up to 50 characters, and it must begin and end with a letter or number.)`

### Steps to Reproduce

As per example above

1. `terraform apply`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, I assume it's a default consumer group. This kind of naming rule ($Default) is not allowed by api. So current error message is expected.

![image](https://user-images.githubusercontent.com/19754191/87504285-c7f0d800-c698-11ea-9bb3-329bc4b42afe.png)

**Comment by favoretti** [comment]
It is a default consumer group, you don't need to create it, moreover, you can't manage it in any way.

**Comment by jackofallops** [comment]
For clarity - The Resource cannot create or otherwise manage `$Default`, however, the Data Source _should_ be able to reference this special case.
