### ISSUE TITLE
Support for configuring blob service properties in azurerm_storage_account

### ISSUE THREAD

**Issue by hasc** [terraform-providers/terraform-provider-azurerm#7722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Following the documentation it currently does not seem possible to configure the blob service properties of a storage account. In our case, we needed to be able to configure the property defaultServiceVersion 

### New or Affected Resource(s)

* azurerm_storage_account

### References

* https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties

**Comment by yupwei68** [comment]
Hi @katbyte , I think we could close this issue for the blob service has been supported.

**Comment by tombuildsstuff** [comment]
Fixed via #11301
