### ISSUE TITLE
azurerm_automation_schedule does not set timezone correctly

### ISSUE THREAD

**Issue by piraces** [terraform-providers/terraform-provider-azurerm#7735]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.28
Azurerm v2.18.0

### Affected Resource(s)

* `azurerm_automation_schedule`

### Terraform Configuration Files

```hcl
resource "azurerm_automation_schedule" "start_vmss" {
  name                    = "START_VMSS"
  resource_group_name     = data.azurerm_resource_group.automation.name
  automation_account_name = data.azurerm_automation_account.core.name
  frequency               = "Week"
  interval                = 1
  timezone                = "Romance Standard Time"
  start_time              = "${substr(timeadd(timestamp(), "24h"), 0, 11)}07:00:00+02:00"
  description             = "Encendido 07:00 (Hora Local España)"
  week_days               = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

  lifecycle {
    ignore_changes = [
      start_time
    ]
  }
}
```

### Debug Output

```
Terraform will perform the following actions:

  # azurerm_automation_schedule.start_vmss[0] will be created
  + resource "azurerm_automation_schedule" "start_vmss" {
      + automation_account_name = "AUTOMATIZACION"
      + description             = "Encendido 07:00 (Hora Local España)"
      + expiry_time             = (known after apply)
      + frequency               = "Week"
      + id                      = (known after apply)
      + interval                = 1
      + name                    = "START_VMSS"
      + resource_group_name     = "RG-AUTOMATIZACION"
      + start_time              = (known after apply)
      + timezone                = "Romance Standard Time"
      + week_days               = [
          + "Friday",
          + "Monday",
          + "Thursday",
          + "Tuesday",
          + "Wednesday",
        ]
    }
```

### Panic Output

No panic output.

### Expected Behavior

I expect terraform to actually set the timezone as said in the terraform plan, and see the timezone set in the Azure Portal (Schedule details).

I expect to see the timezone set in Azure Portal and see something in the timezone dropdown, like this (this was done manually):
![Expected behavior](https://i.imgur.com/fILJJpF.png)

### Actual Behavior

Timezone is not being set by terraform, as we can see in the following screenshot of Azure Portal (empty dropdown of timezone):
![Actual behavior](https://i.imgur.com/oB3UBgg.png)

### Steps to Reproduce

1. `terraform apply` of any configuration of the resource `azurerm_automation_schedule` results in timezone not being set.

### Important Factoids

No important Factoids.

### References

No references.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, seems api behavior has been changed. Currently seems timezone display name isn't supported anymore. You have to use timezone value. Get more available timezone list via https://s2.automation.ext.azure.com/api/Orchestrator/TimeZones?_=1594792230258
I also made a fix for this issue.

![image](https://user-images.githubusercontent.com/19754191/87511361-c084fb00-c6a7-11ea-889b-8ed827985fae.png)

**Comment by piraces** [comment]
Correct. I think this is the actual issue, the timezone values provided are not valid right now...
