### ISSUE TITLE
Error creating azurerm_vpn_gateway immediately after azurerm_virtual_hub

### ISSUE THREAD

**Issue by erichrockman** [terraform-providers/terraform-provider-azurerm#7742]
Getting this error when creating the vwan vpn gateway immediatelty after creating the vwan hub. Running another apply creates the resource.  

######################################
# Create Azure vWAN
######################################

# https://www.terraform.io/docs/providers/azurerm/r/virtual_wan.html

resource "azurerm_virtual_wan" "fgt-vwan" {
  name                = "vwan-fgt-${random_id.random_hex.hex}"
  resource_group_name = azurerm_resource_group.fgt-vwan.name
  location            = var.ARM_AZ_LOCATION
  allow_branch_to_branch_traffic = "true"
  allow_vnet_to_vnet_traffic = "true"

  tags     = local.common-tags
}

######################################
# Create Azure vWAN Hub
######################################

# https://www.terraform.io/docs/providers/azurerm/r/virtual_hub.html

resource "azurerm_virtual_hub" "fgt-vwan-hub" {
  name                = "vwan-hub-fgt-${random_id.random_hex.hex}"
  resource_group_name = azurerm_resource_group.fgt-vwan.name
  location            = var.ARM_AZ_LOCATION
  virtual_wan_id      = azurerm_virtual_wan.fgt-vwan.id
  address_prefix      = "10.60.128.0/23"

  route {
    address_prefixes = ["10.60.132.0/23","10.60.134.0/23"]
    next_hop_ip_address = "10.60.130.36"
  }

  tags     = local.common-tags
}

######################################
# Create Azure vWAN Hub VPN Gateway
######################################

# https://www.terraform.io/docs/providers/azurerm/r/vpn_gateway.html

resource "azurerm_vpn_gateway" "fgt-vwan-hub-gateway" {
  name                = "vwan-hub-fgt-vpn-gateway-${random_id.random_hex.hex}"
  location            = var.ARM_AZ_LOCATION
  resource_group_name = azurerm_resource_group.fgt-vwan.name
  virtual_hub_id      = azurerm_virtual_hub.fgt-vwan-hub.id
  scale_unit = "1"

  tags     = local.common-tags
}

Error: Error creating VPN Gateway "vwan-hub-fgt-vpn-gateway-5f7fae541b485bdb1cc6ebabebdd4050" (Resource Group "rg-fgt-vwan"): network.VpnGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ReferencedResourceNotProvisioned" Message="Cannot proceed with operation because resource /subscriptions/xxxxx/resourceGroups/rg-fgt-vwan/providers/Microsoft.Network/virtualHubs/vwan-hub-fgt-5f7fae541b485bdb1cc6ebabebdd4050 used by resource /subscriptions/xxxxx/resourceGroups/rg-fgt-vwan/providers/Microsoft.Network/vpnGateways/vwan-hub-fgt-vpn-gateway-5f7fae541b485bdb1cc6ebabebdd4050 is not in Succeeded state. Resource is in Updating state and the last operation that updated/is updating the resource is Microsoft.WindowsAzure.Networking.Nrp.Frontend.Operations.Csm.PutVirtualHubOperation." Details=[]

  on vwan.tf line 53, in resource "azurerm_vpn_gateway" "fgt-vwan-hub-gateway":
  53: resource "azurerm_vpn_gateway" "fgt-vwan-hub-gateway" {

**Comment by tombuildsstuff** [comment]
hi @erichrockman 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by erichrockman** [comment]
I would think that there should be a check in the azurerm_vpn_gateway resource that will check the state of the hub resource and wait until it is succeeded.
