### ISSUE TITLE
azurerm_api_management_openid_connect_provider keeps updating client_secret

### ISSUE THREAD

**Issue by sirlatrom** [terraform-providers/terraform-provider-azurerm#7757]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.16.0
```

### Affected Resource(s)

* `azurerm_api_management_openid_connect_provider`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_openid_connect_provider" "oidc" {
  name                = "oidc"
  api_management_name = azurerm_api_management.apim.name
  resource_group_name = data.azurerm_resource_group.rg.name
  client_id           = var.openid_client_id
  client_secret       = var.openid_client_secret
  display_name        = "Open Id Connect"
  metadata_endpoint   = var.openid_configuration_url
}
```

### Debug Output

N/A.

### Panic Output

N/A.

### Expected Behavior

Once created, the resource should show now changes unless a discrepancy arises or the configuration is altered.

### Actual Behavior

The `client_secret` field is shown as to be added in every plan/apply.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

N/A.

### References

* Similar to #7298, solution directly copied from #7529.

**Comment by yupwei68** [comment]
Hi @sirlatrom , thanks for opening this issue. This has been fixed https://github.com/terraform-providers/terraform-provider-azurerm/pull/7675 and released in 2.19.0. Please try a version later than 2.19.0.
