### ISSUE TITLE
Feature Request: App Services (Deployment) Slots

### ISSUE THREAD

**Issue by thatfrankdev** [terraform-providers/terraform-provider-azurerm#776]
Hi there,

It would be nice to have support for app service deployment slots.

Ideally, it would offer mostly the same parameters as `azurerm_app_service` (because they can have a totally different configuration), plus a slot name and a way to specify its parent app service.

Thanks!

**Comment by thatfrankdev** [comment]
#818 will fix this

**Comment by tombuildsstuff** [comment]
Support for App Service Slots (and setting the default slot for an App Service) has been added in #818 which has been merged - as such I'm going to close this issue - but this should go out in v1.1.2 of the AzureRM Provider later this week :)
