### ISSUE TITLE
Order changes for feature blocks of azurerm_signalr_service

### ISSUE THREAD

**Issue by derekwinters** [terraform-providers/terraform-provider-azurerm#7761]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

azurerm 2.18.0
terraform 0.12.28

### Affected Resource(s)

* `azurerm_signalr_service`

### Terraform Configuration Files

```hcl
locals {
  cors = {
    allowed_origins = ["*"]
  }

  features = {
    "EnableConnectivityLogs" = false
    "EnableMessagingLogs"    = false
    "ServiceMode"            = "Serverless"
  }

  sku = {
    "name"     = "Standard_S1"
    "capacity" = 1
  }

  tags = {
    REDACTED = "REDACTED"
  }
}
```

```hcl
resource "azurerm_signalr_service" "main" {
  name                = "test02"
  location            = data.azurerm_resource_group.parent_rg.location
  resource_group_name = data.azurerm_resource_group.parent_rg.name
  tags                = local.tags

  dynamic "cors" {
    for_each = { "cors" = local.cors }
    content {
      allowed_origins = cors.value.allowed_origins
    }
  }

  dynamic "features" {
    for_each = local.features
    content {
      flag  = features.key
      value = features.value
    }
  }

  sku {
    name     = local.sku.name
    capacity = local.sku.capacity
  }
}
```

### Expected Behavior

Apply the configuration and do not show configuration drift.

### Actual Behavior

After running `terraform apply`, an immediate followup `terraform plan` will indicate changes are needed.

```hcl
  ~ resource "azurerm_signalr_service" "main" {
        hostname                    = "(redacted)"
        id                          = "(redacted)"
        ip_address                  = "(redacted)"
        location                    = "(redacted)"
        name                        = "(redacted)"
        primary_access_key          = (sensitive value)
        primary_connection_string   = (sensitive value)
        public_port                 = 443
        resource_group_name         = ("redacted)"
        secondary_access_key        = (sensitive value)
        secondary_connection_string = (sensitive value)
        server_port                 = 443
        tags                        = {
          (redacted)
        }

        cors {
            allowed_origins = [
                "*",
            ]
        }

      ~ features {
          ~ flag  = "ServiceMode" -> "EnableConnectivityLogs"
          ~ value = "Serverless" -> "False"
        }
      ~ features {
          ~ flag  = "EnableConnectivityLogs" -> "EnableMessagingLogs"
            value = "False"
        }
      ~ features {
          ~ flag  = "EnableMessagingLogs" -> "ServiceMode"
          ~ value = "False" -> "Serverless"
        }

        sku {
            capacity = 20
            name     = "Standard_S1"
        }
    }
```

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### References

* #7677 
  * Looking at that issue, it looks like the features are a numbered list (features.0.flag, features.1.flag, etc) and may be getting reordered by the Azure API.

**Comment by lrxtom2** [comment]
@derekwinters ,Thanks for opening the issue! We can reproduce the issue and looking into about that.

**Comment by neil-yechenwei** [comment]
Sorry for the late response. After investigated, I assume there are two problems in your scenario. First issue is ordering issue as you mentioned and another issue is that API always returns the value in features block which starts with upper case. For first issue, I submitted a PR to fix. For second issue, I assume you have to make the value in features block start with upper case.
