### ISSUE TITLE
Support for azurerm_cognitive_account Data Source

### ISSUE THREAD

**Issue by h3yduck** [terraform-providers/terraform-provider-azurerm#7765]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* `data.azurerm_cognitive_account`

### Description

Add `azurerm_cognitive_account` data source.

### Potential Terraform Configuration

```hcl
data "azurerm_cognitive_account" "example" {
  name                = "example-name"
  resource_group_name = "example-resources"
}
```

**Comment by kshitijcode** [comment]
@tombuildsstuff @h3yduck I am interested to contribute. How do I assign this to myself?
Will be my first open-source contribution :)
