### ISSUE TITLE
Support for new resource azurerm_automation_dsc_compilation_job

### ISSUE THREAD

**Issue by neil-yechenwei** [terraform-providers/terraform-provider-azurerm#7771]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There is a new resource request to implement the scenario of "[Compile a configuration in Azure Automation](https://docs.microsoft.com/en-us/azure/automation/automation-dsc-getting-started#compile-a-configuration-in-azure-automation)".

### New or Affected Resource(s)

* azurerm_automation_dsc_compilation_job

### Potential Terraform Configuration

```hcl
resource "azurerm_automation_dsc_compilation_job" "example" {
  name                    = "example-compilationjob"
  resource_group_name     = azurerm_resource_group.example.name
  location                = azurerm_resource_group.example.location
  automation_account_name = azurerm_automation_account.example.name
  configuration_name      = "TestConfig"

  tags = {
    ENV = "prod"
  }
}
```

### References

* Rest api doc: https://docs.microsoft.com/en-us/rest/api/automation/dsccompilationjob/create
* Rest api spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/dscCompilationJob.json
* The scenario: https://docs.microsoft.com/en-us/azure/automation/automation-dsc-getting-started

**Comment by tombuildsstuff** [comment]
@neil-yechenwei based on the API Documentation it appears that's a deployment-time configuration, and thus something that doesn't necessarily make sense in Terraform - what's the use-case we're aiming to solve here?

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , you can find the whole scenario from https://github.com/terraform-providers/terraform-provider-azurerm/issues/7404. For the steps 3-4 customer described, seems we need to add this new resource to implement it.

**Comment by neil-yechenwei** [comment]
After do more investigation, I found [dsc complication job api spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/dscCompilationJob.json) doesn't support delete action. So I assume it's not appropriate to be as TF candidate.
