### ISSUE TITLE
azurerm_backup_policy_vm minimum daily retention count is inaccurate

### ISSUE THREAD

**Issue by akonrath** [terraform-providers/terraform-provider-azurerm#7792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
$ terraform -v
Terraform v0.12.28
+ provider.azurerm v2.19.0
```

### Affected Resource(s)

* `azurerm_backup_policy_vm`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "tfex-recovery_vault"
  location = "North Central US"
}

resource "azurerm_recovery_services_vault" "example" {
  name                = "tfex-recovery-vault"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
}

resource "azurerm_backup_policy_vm" "example" {
  name                = "tfex-recovery-vault-policy"
  resource_group_name = azurerm_resource_group.example.name
  recovery_vault_name = azurerm_recovery_services_vault.example.name

  timezone = "UTC"

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 1
  }
}
```

### Debug Output

```
Error: Error creating/updating Azure Backup Protection Policy "tfex-recovery-vault-policy" (Resource Group "tfex-recovery_vault"): backup.ProtectionPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BMSUserErrorInvalidPolicyInput" Message="Input for create or update policy is not in proper format\r\nPlease check format of parameters like schedule time, schedule days, retention time and retention days "

  on main.tf line 13, in resource "azurerm_backup_policy_vm" "example":
  13: resource "azurerm_backup_policy_vm" "example" {



```
### Expected Behavior
The minimum daily retention count is properly validated.

### Actual Behavior
An error is thrown regarding invalid policy.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
According to Azure's documentation, the accepted daily retention count is between 7 and 9999 days. Right now, the validation within the provider is set for 1 to 9999. I'm more than happy to put together a PR to get the correct range and update the documentation, as otherwise people following the documentation will be mislead, but Azure also notes this:
```
Any modification to an existing VM backup policy with less than seven days will require an update to meet the minimum retention range of seven days.
```
So if we get this fixed, this will invalidate anyone grandfathered into the less than 7 day retention policy. Thoughts?

Thank you!

### References
https://docs.microsoft.com/en-us/azure/backup/backup-azure-vm-backup-faq
https://www.terraform.io/docs/providers/azurerm/r/backup_policy_vm.html

* #0000

**Comment by njuCZ** [comment]
@akonrath thanks for pointing this problem. It would be nice for you to submit a PR to fix it !

**Comment by akonrath** [comment]
@njuCZ  - Thank you for the reply, and agreed about preserving current users with <7 backups. I will work on a PR and update once I have further details.
