### ISSUE TITLE
Client Affinity setting not applied. Should be at site_config level.

### ISSUE THREAD

**Issue by sjwaight** [terraform-providers/terraform-provider-azurerm#780]
When creating a new Web App in App Service using Terraform the client_affinity_enabled setting appears to have no affect.

Additionally, it would appear that this property should actually move to the site_config level as it appears at that level in the Azure management Portal (i.e. 'Always On' and 'ARR Affinity' are both available on the same management blade).

### Terraform Version
Terraform v0.11.2
+ provider.azurerm v1.1.0

### Affected Resource(s)
azurerm_app_service

### Terraform Configuration Files
```hcl
resource "azurerm_app_service" "demo_web_app" {
  name                      = "wa-demo-app"
  location                  = "westus2"
  resource_group_name       = "demo-test-rg"
  client_affinity_enabled   = false
  app_service_plan_id       = "${azurerm_app_service_plan.my_existing_appplan.id}"
  site_config {
                always_on                 = true
                dotnet_framework_version  = "v4.0"
              }
}
```
### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior

The ARR Affinity value for the resulting Web App should be set to 'Off'.

### Actual Behavior

ARR Affinity for Web App remains as default value ('On') and requires a manual change.

### Steps to Reproduce
Simply run a standard "apply" using the above HCL snippet being applied to an existing App Service Plan.

### Important Factoids
Windows App Service deployment.

**Comment by tombuildsstuff** [comment]
hey @sjwaight 

Thanks for opening this issue - just to let you know that this was fixed in #973 which shipped in v1.3.0 of the AzureRM Provider :)

Thanks!
