### ISSUE TITLE
Resizing the Managed AKS cluster node size or type destroys and recreates the cluster 

### ISSUE THREAD

**Issue by vakkur** [terraform-providers/terraform-provider-azurerm#7801]
This is a continuation of Resizing the Managed AKS cluster node size or type destroys and recreates the cluster #5311

I can resize the default node pool from Azure Portal, but when I resize it from terraform it actually destroys the entire cluster and recreating it.

I am not able to add the OMS_Agent and Kube Dashboard after the cluster creation, this is also triggering a destroy and recreate.

**Comment by Bessonov** [comment]
It seem like a duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/7093

**Comment by tombuildsstuff** [comment]
Thanks for the heads up @Bessonov - agreed, this appears to be a duplicate - would you mind subscribing to #7093 for updates?
