### ISSUE TITLE
azurerm_app_service_plan: Error: `reserved` has to be set to false when kind isn't set to `Linux`

### ISSUE THREAD

**Issue by scott1138** [terraform-providers/terraform-provider-azurerm#7804]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.28
+ provider.azuread v0.11.0
+ provider.azurerm v2.18.0
+ provider.external v1.2.0

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "asp_function" {
    name                = "ASP-${local.app_name}-${local.location_short}-Function-${local.env_name}"
    resource_group_name = azurerm_resource_group.rg.name
    location            = local.location
    kind                = "FunctionApp"
    reserved            = true

    sku {
        tier = "Dynamic"
        size = "Y1"
    }

    tags = local.tags
}
```

### Expected Behavior

The app service plan should have been created as consumption using Linux. This is from the documentation found at https://www.terraform.io/docs/providers/azurerm/r/function_app.html

```
resource "azurerm_app_service_plan" "example" {
  name                = "azure-functions-test-service-plan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "FunctionApp"
  reserved            = true

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}
```

### Actual Behavior

I receive the output:
```
Error: `reserved` has to be set to false when kind isn't set to `Linux`

  on main.tf line 276, in resource "azurerm_app_service_plan" "asp_function":
 276: resource "azurerm_app_service_plan" "asp_function" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by StefanSchoof** [comment]
From the documentation you linked. For the `os_type`:
> NOTE: This value will be linux for Linux Derivatives or an empty string for Windows (default). When set to linux you must also set azurerm_app_service_plan arguments as kind = "FunctionApp" and reserved = true

I think you should try to set os_type to linux if you want a function on linux.

**Comment by scott1138** [comment]
@StefanSchoof the app service plan must be created first and it does not have an os_type property, that's part of the azurerm_function_app resource.  I have tried using `kind = "linux"` and it creates the resource, but if you run another terraform plan it wants to destroy it because the new kind value is "functionapp,linux" and the config says "linux".  @katbyte @tombuildsstuff do you know if maybe "functionapp,linux" should be added as an available kind for azurerm_function_app?  Or does it need to be fixed to allow `reserved = true` with the kind functionapp, which is what the documentation seems to indicate.

**Comment by scott1138** [comment]
FYI - for now I am getting around this issue by setting `kind = "linux` and using the following lifecycle block in my azurerm_app_service_plan resource:
```
lifecycle {
    ignore_changes = [
         kind
    ]
}
```

If I do not ignore the kind property this is what I see in my subsequent plan operations:
```
Terraform will perform the following actions:

  # azurerm_app_service_plan.asp_function must be replaced
-/+ resource "azurerm_app_service_plan" "asp_function" {
      ~ id                           = "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP_NAME>/providers/Microsoft.Web/serverfarms/<APP_SERVICE_PLAN_NAME>" -> (known after apply)
      - is_xenon                     = false -> null
      ~ kind                         = "functionapp" -> "Linux" # forces replacement
        location                     = "southcentralus"
      ~ maximum_elastic_worker_count = 1 -> (known after apply)
      ~ maximum_number_of_workers    = 0 -> (known after apply)
        name                         = "<APP_SERVICE_PLAN_NAME>"
      - per_site_scaling             = false -> null
        reserved                     = true
        resource_group_name          = "<RESOURCE_GROUP_NAME>"
        tags                         = {
            "Component"   = "<APP_NAME>"
            "Environment" = "Prod"
        }

      ~ sku {
          ~ capacity = 0 -> (known after apply)
            size     = "Y1"
            tier     = "Dynamic"
        }
    }
```

**Comment by Dav1dde** [comment]
Seems to be the same issue as: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7759

**Comment by scott1138** [comment]
Thanks @Dav1dde - not sure how I missed that when I was looking.  I'll just close this, that issue is much better written than mine.

**Comment by Dav1dde** [comment]
I ran into the same issue, your workaround helped, so maybe worth copying that over?
