### ISSUE TITLE
Support for User Assigned Managed Identities

### ISSUE THREAD

**Issue by markti-persistent** [terraform-providers/terraform-provider-azurerm#7805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Managed identities for Azure resources provide Azure services with a managed identity in Azure Active Directory. You can use this identity to authenticate to services that support Azure AD authentication, without needing credentials in your code.

You can use SystemAssigned Managed Service Identities or User Assigned. User Assigned Identities give you more control over the provisioning of the identities. 

### New or Affected Resource(s)

* azurerm_managed_identity

### Potential Terraform Configuration

```hcl
resource "azurerm_managed_identity" "my_app_identity" {
  name = "acme-coolapp-us-east"
  resource_group_name = var.resource_group_name
  location = var.location
}
```

### References

* #0000

**Comment by sean-nixon** [comment]
I believe you're looking for `azurerm_user_assigned_identity`: https://www.terraform.io/docs/providers/azurerm/r/user_assigned_identity.html

**Comment by tombuildsstuff** [comment]
Closing since this is available as `azurerm_user_assigned_identity`
