### ISSUE TITLE
azurerm_firewall: allow empty zone specification

### ISSUE THREAD

**Issue by LucianFrango** [terraform-providers/terraform-provider-azurerm#7807]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
- when trying to deploy Azure Firewall in the Australia Southeast region that currently does not support Availability Zones, I'm not available to pass through and interpret a blank list of zones as "the zones are not specified".

### Terraform (and AzureRM Provider) Version
```hcl
Terraform v0.12.28
+ provider.azurerm v2.19.0
```

### Affected Resource(s)

* `azurerm_firewall`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

```hcl
  # module.as_azfw.azurerm_firewall.azfw will be created
  + resource "azurerm_firewall" "azfw" {
      + id                  = (known after apply)
      + location            = "australiasoutheast"
      + name                = "AZFW"
      + resource_group_name = "RG"
      + threat_intel_mode   = "Alert"
      + zones               = []
```

### Actual Behavior

```hcl
Error: zones: attribute supports 1 item as a minimum, config has 0 declared

  on ../modules/azurerm_firewall/main.tf line 15, in resource "azurerm_firewall" "azfw":
  15: resource "azurerm_firewall" "azfw" {
```

### Potential TF configuration

```hcl
resource "azurerm_firewall" "fw" {
  …
  zones = []
}
```

### References

- [https://www.terraform.io/docs/providers/azurerm/r/firewall.html#zones](https://www.terraform.io/docs/providers/azurerm/r/firewall.html#zones)

#### UPDATE
- I found a similar issue with another service that resulted in a fix: 
  - [https://github.com/terraform-providers/terraform-provider-azurerm/issues/1787](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1787)

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Hopes this [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7817)would be helpful.

**Comment by LucianFrango** [comment]
Awesome, that makes it easier/cleaner..?!
I did find a 'work around' to set "zones = null" in the instantiation files calling my root module.
I'm not sure if thats a best practice solution or not, so will wait for the PR. 
Thank you
