### ISSUE TITLE
allow_blob_public_access causes storage account deployment to break in government environment

### ISSUE THREAD

**Issue by Stosija** [terraform-providers/terraform-provider-azurerm#7812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Last week I tried deploying several storage accounts to a resource group in a US Government environment. The deployments threw an error saying that the feature was not available in that region. I replicated the behavior today. I discovered that change [#7739](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7739) was made last Tuesday, which was also the last day I successfully deployed a storage account via Terraform. I changed the provider version back to 2.18 and was able to deploy a storage account. 

### Affected Resource(s)

*azurerm_storage_account

### Terraform Configuration Files

```hcl
provider "azurerm" {
  environment = "usgovernment"
  version =  ">= 2.13.0"
  features {}
}

resource "azurerm_storage_account" "example" {
  name = "storageaccountname"
  resource_group_name = azurerm_resource_group.example.name
  location = "usgovvirginia"
  account_tier = "Standard"
  account_replication_type = "LRS"
  allow_blob_public_access = false
}
```

### Debug Output

`Failure sending request: StatusCode=400 -- Original Error: Code="FeatureNotAvailableInRegion" Message="allowBlobPublicAccess feature is not available in this region"
`
### Expected Behavior

Expected the storage account to successfully deploy. 

### Actual Behavior

The storage account failed to deploy.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This behavior is happening in a US Gov environment.

### References

* #7739 
* #7781

**Comment by lrxtom2** [comment]
@Stosija Thanks for opening the issue! For this time we could not reproduce the issue. If you are work on Azure US Gov environment, please check the azure-gov policy about the feature. We will follow up the issue, thanks in advance!

**Comment by vsabella** [comment]
> @Stosija Thanks for opening the issue! For this time we could not reproduce the issue. If you are work on Azure US Gov environment, please check the azure-gov policy about the feature. We will follow up the issue, thanks in advance!

@lrxtom2  We have the same problem as well, Why are you unable to reproduce it it's pretty straightforward.

**Comment by lstroud** [comment]
same issue here
