### ISSUE TITLE
Error flattening `default_node_pool`: The Default Agent Pool "" was not found when migrating  to version 2

### ISSUE THREAD

**Issue by DejeroDaniel** [terraform-providers/terraform-provider-azurerm#7813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.19.0
+ provider.kubernetes v1.11.2

### Affected Resource(s)

* `azurerm_kubernetes_cluster`
default_node_pool in particular

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azurerm_kubernetes_cluster" "aks" {
  name                = "${var.prefix}${var.environment}"
  resource_group_name = var.environment
  location            = var.location
  dns_prefix          = "${var.prefix}${var.environment}"
  kubernetes_version  = var.kubernetes_version

  default_node_pool {
    type            = "VirtualMachineScaleSets"
    name            = "default"
    node_count      = var.kubernetes_nodes
    vm_size         = var.vmsize
    os_disk_size_gb = var.vmdisksizegb
    vnet_subnet_id  = azurerm_subnet.k8snodes.id
  }

  network_profile {
    network_plugin    = "azure"
    network_policy    = "azure"
    load_balancer_sku = "standard"
  }

  role_based_access_control {
    enabled = "true"
  }

  service_principal {
    client_id     = var.kubernetes_sp_client_id
    client_secret = var.kubernetes_sp_client_secret
  }

  tags = {
    environment = var.environment
  }
}

```

### Debug Output
https://gist.github.com/DejeroDaniel/a194374412836776d31e4f582bafd0bf

### Expected Behavior
terraform plan should work without throwing an error, or at least give a better error description that enables the user to fix the error on their own.

### Actual Behavior
terraform plan throws an error

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am upgrading a terraform deployment from azurerm 1.39 to 2.19

**Comment by gsimoes** [comment]
Had the same issue today, so I used provider version v2.10.0 to import the cluster then after that switched back to provider.azurerm v2.19.0. Didn't have time to dig much further but this workaround worked.

**Comment by davidchua** [comment]
I'm experiencing the same problem but when migrating to `v2.17`

I was digging through the code and after some debugging, it seems like for some reason, during migration

https://github.com/terraform-providers/terraform-provider-azurerm/blob/76a112f5c206835e0b945305022112ffe8e939de/azurerm/internal/services/containers/kubernetes_nodepool.go#L384

returns nil and the path continues on to 

https://github.com/terraform-providers/terraform-provider-azurerm/blob/76a112f5c206835e0b945305022112ffe8e939de/azurerm/internal/services/containers/kubernetes_nodepool.go#L401-L403 as `v.Mode` is `User` and not `System`.

And therefore `agentPool` becomes `nil`.

**Comment by DejeroDaniel** [comment]
Thanks, I followed the advice of @gsimoes and went down in versions until I was able to do a successful terraform plan, which for me was 2.13.0.

However I don't have any actualy changes to make to my infra, I just needed to update the provider. And When I go back to 2.19.0, the same issue persists. So I guess I will just stay on 2.13.0 for now.

**Comment by DejeroDaniel** [comment]
Just updated to version 2.25, was able to apply changes without being forced to redeploy everything. Closing
