### ISSUE TITLE
Test defect about `AzureRMOrchestratedVirtualMachineScaleSet`

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#7818]
### Affected Resource(s)

* `azurerm_orchestrated_virtual_machine_scale_set`

### Related tests
* `TestAccAzureRMOrchestratedVirtualMachineScaleSet_basicZonal`
* `TestAccAzureRMOrchestratedVirtualMachineScaleSet_updateZonal`
* `TestAccAzureRMOrchestratedVirtualMachineScaleSet_basicNonZonal`

### Error Messages
```
=== RUN   TestAccAzureRMOrchestratedVirtualMachineScaleSet_basicZonal
=== PAUSE TestAccAzureRMOrchestratedVirtualMachineScaleSet_basicZonal
=== CONT  TestAccAzureRMOrchestratedVirtualMachineScaleSet_basicZonal
--- FAIL: TestAccAzureRMOrchestratedVirtualMachineScaleSet_basicZonal (88.05s)
    testing.go:684: Step 0 error: errors during apply:

        Error: creating Orchestrated Virtual Machine Scale Set "acctestVMO-200721122019703343" (Resource Group "acctestRG-VMSS-200721122019703343"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The value 'False' of parameter 'singlePlacementGroup' is not allowed. Allowed values are: True."
```

**Comment by lrxtom2** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/10212

**Comment by ArcturusZhang** [comment]
Hi @lrxtom2 this feature is currently in private preview, which means that only in the whitelisted subscription, you can assign SPG to false, in all other subscriptions, you still have to assign the SPG to true.

I will make a PR remove the validation and let the service just throws the correct error message.
