### ISSUE TITLE
azurerm_windows_virtual_machine certificate block error

### ISSUE THREAD

**Issue by kinwolfqc** [terraform-providers/terraform-provider-azurerm#7828]
I am trying to feed a certificate to a new windows vm using the certificate block as described in the doc, but terraform keeps complaining that a Certificate block is not expected in this ressource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.28
+ provider.azuread v0.11.0
+ provider.azurerm v2.16.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
### Affected Resource(s)

* `azurerm_windows_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_windows_virtual_machine" "windowsVm" {
  name                  = var.vm_hostname
  location              = var.location
  resource_group_name   = data.azurerm_resource_group.vm.name
  network_interface_ids = [azurerm_network_interface.nic.id]
  size               = "Standard_D2_v2" #proget requiert 2vCpu et 8Go RAM
  admin_username = var.admin_username
  admin_password = var.admin_password

    certificate {
        store     = "My"
        url       = var.certificateUrl
      }

    os_disk {
      name              = "${var.namespace}lab_OsDisk"
      caching              = "ReadWrite"
      storage_account_type = "Standard_LRS"
    }

    source_image_reference {
      publisher = "MicrosoftWindowsServer"
      offer     = "WindowsServer"
      sku       = lookup(var.sku, var.location)
      version   = "latest"
    }

  
  
   tags                         = var.tags

}
```

### Debug Output

Error: Unsupported block type

  on ..\modules\psget\windowsbase\main.tf line 48, in resource "azurerm_windows_virtual_machine" "windowsVm":
  48:     certificate {

Blocks of type "certificate" are not expected here.

**Comment by ArcturusZhang** [comment]
Hi @kinwolfqc thanks for opening this issue!

Actually the `certificate` block must be placed in a `secret` block as documented [here](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html#secret). Like this:
```
resource "azurerm_windows_virtual_machine" "windowsVm" {
  name                  = var.vm_hostname
  location              = var.location
  resource_group_name   = data.azurerm_resource_group.vm.name
  network_interface_ids = [azurerm_network_interface.nic.id]
  size               = "Standard_D2_v2" #proget requiert 2vCpu et 8Go RAM
  admin_username = var.admin_username
  admin_password = var.admin_password

    secret {
       key_vault_id = # you will have to also assign a key vault id here
       certificate {
           store     = "My"
           url       = var.certificateUrl
      }
    }

    os_disk {
      name              = "${var.namespace}lab_OsDisk"
      caching              = "ReadWrite"
      storage_account_type = "Standard_LRS"
    }

    source_image_reference {
      publisher = "MicrosoftWindowsServer"
      offer     = "WindowsServer"
      sku       = lookup(var.sku, var.location)
      version   = "latest"
    }

  
  
   tags                         = var.tags

}
```

**Comment by kinwolfqc** [comment]
Thanks for the information, it worked with that syntax  

I must admit, even looking at the part of the doc you linked to, I can't see how we are supposed to know the certificate block should be nested inside a secret block.  I still haven't figured out the cipher that seems to be used to write the terraform doc. :-/

**Comment by ArcturusZhang** [comment]
> Thanks for the information, it worked with that syntax
> 
> I must admit, even looking at the part of the doc you linked to, I can't see how we are supposed to know the certificate block should be nested inside a secret block. I still haven't figured out the cipher that seems to be used to write the terraform doc. :-/

Yeah... the documentation does not show the block hierarchy but only shows them all in one level and in alphabetical order. Sometimes this introduces confusion
