### ISSUE TITLE
azurerm_mysql_server ssl_minimal_tls_version_enforced always set to TLSEnforcementDisabled

### ISSUE THREAD

**Issue by mleziva** [terraform-providers/terraform-provider-azurerm#7837]
Deploy mysql server with ssl_minimal_tls_version_enforced set to TLS1_2
Review in Azure portal that minimum version enforced is not set
Attempt to run again and see the below output from terraform plan

azurerm_mysql_server
![image](https://user-images.githubusercontent.com/6925381/88115653-47d8df80-cb7c-11ea-8c34-5db328908f62.png)

**Comment by yupwei68** [comment]
Hi @mleziva , thanks for opening this issue. I think it has been fixed in https://github.com/terraform-providers/terraform-provider-azurerm/pull/7307 and it has been released in v2.19.0.

**Comment by mleziva** [comment]
Just tested with v2.19.0 and it works as long as the following is set:

` ssl_enforcement_enabled           = true`

Thanks

**Comment by mybayern1974** [comment]
Hi @mleziva , glad you've got unblocked！Would you mind we close this issue now? Feel free to suggest reopen if you believe it's necessary. Thank you！
