### ISSUE TITLE
domain_name_label not imported for azurerm_public_ip

### ISSUE THREAD

**Issue by jkubrynski** [terraform-providers/terraform-provider-azurerm#784]
### Terraform Version
```
Terraform v0.11.2
+ provider.azurerm v1.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
`- azurerm_public_ip`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Description
When importing public ip `terraform import azurerm_public_ip.name {ID}` the `domain_name_label` is ignored and not imported into state

**Comment by katbyte** [comment]
Hello @jkubrynski,

Thank you for opening this issue, it should be a relatively simple fix. 

What other resources are you seeing exhibit this behaviour? If you could supply a list here we can see about getting them all fixed at once 🙂

**Comment by katbyte** [comment]
@jkubrynski,

Just a heads up this fix was included in 1.7 released this afternoon.
