### ISSUE TITLE
Unable to set the type of managed disk with AKS

### ISSUE THREAD

**Issue by LordGordonQ** [terraform-providers/terraform-provider-azurerm#7845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azuread v0.11.0
+ provider.azurerm v2.19.0
+ provider.azurestack v0.9.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "xxx" {
    name                = "xxx"
    location            = "westeurope"
    resource_group_name = "xxx"
    dns_prefix          = "xxx"
    kubernetes_version  = "1.16.9"
    sku_tier            = "Free"

    default_node_pool {
        name                = "default"
        node_count          = 1
        vm_size             = "Standard_B2s"
        enable_auto_scaling = false
    }

    identity {
        type = "SystemAssigned"
    }

    addon_profile {
        kube_dashboard {
            enabled = true
        }

        oms_agent {
            enabled                     = true
            log_analytics_workspace_id  = "xxx"
        }
    }
}
```

### Expected Behavior

I should be able to specify the tier of the managed disk attached to the VM created for the AKS cluster to avoid incurring in unwanted costs.

### Actual Behavior

Since there is no way to specify the tier, the default `Premium SSD` tier is used, incurring in additional unexpected expensive costs.

### Steps to Reproduce

1. `terraform apply`

**Comment by njuCZ** [comment]
@LordGordonQ sorry for late reply. I am not so familiar with the kubernetes RP. I am not sure it's a terraform issue or not. There seems no way to set the managed disk in the portal, is there any relevant doc?

**Comment by LordGordonQ** [comment]
> @LordGordonQ sorry for late reply. I am not so familiar with the kubernetes RP. I am not sure it's a terraform issue or not. There seems no way to set the managed disk in the portal, is there any relevant doc?

@njuCZ I opened a ticket with Microsoft since there is no way to change this even from the Portal. Last time I checked, there is no API or CLI option. I missed to update this issue with the new discoveries. Apparently, with the `Standard_B2s` you are stuck with a Premium SSD.

**Comment by njuCZ** [comment]
@LordGordonQ thanks for your clarification. Since this is not a terraform issue, but a feature request for Azure Service, I am going to close this issue.

**Comment by tombuildsstuff** [comment]
Closing this out as mentioned above
