### ISSUE TITLE
Changing virtual_network_type in azurerm_api_management forces resource recreation

### ISSUE THREAD

**Issue by k-popov** [terraform-providers/terraform-provider-azurerm#7851]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
terraform {
  required_version = "0.12.26"
  required_providers {
    azurerm = "2.16.0"
  }
}
```

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files
main.tf:
```hcl
resource "azurerm_api_management" "this" {
  name                = var.apim_name
  resource_group_name = data.azurerm_resource_group.env.name
  location            = data.azurerm_resource_group.env.location
  publisher_name      = var.apim_publisher_name
  publisher_email     = var.apim_publisher_email

  sku_name = var.sku_name

  virtual_network_type = var.virtual_network_type
  virtual_network_configuration {
    subnet_id = var.subnet_id
  }

  tags = var.tags
}
```
Inputs:
```hcl
# changed from "Internal" to "External"
virtual_network_type = "External"
```

### Expected Behavior

API management service resource is updated in-place.
*Why is that expected?*
Changing this configuration item in Azure Web portal does not require resource recreation.
API documentation also defines method for updating this setting (see ref).

### Actual Behavior

Entire API management service (including all APIs in it) is destroyed and recreated.

### Steps to Reproduce

1. create API management service with `virtual_network_type = "Internal"`
2. Change `virtual_network_type = "External"`
3. `terraform apply`

### References

* https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apimanagementservice/applynetworkconfigurationupdates

**Comment by yupwei68** [comment]
Hi @k-popov , thanks for opening this issue. After further consideration, we might not support this feature. Because after we update the `virtual_network_type` from `Internal` to `None`, we could not destroy the `azurerm_virtual_network` in 3 hours. This is confirmed by the service team as by design to avoid downtime for customer Apps. Thus, currently we could not support this feature.

> The scenario where we move the service out of VNET, does not remove the link to subnet immediately.
> This is to avoid downtime for customer Apps, as their DNS refresh can take some time.

**Comment by k-popov** [comment]
Hello, @yupwei68 ! Thank you for your response.
Could you please explain what is the need for destruction of virtual network that you mentioned?

**Comment by yupwei68** [comment]
@k-popov It means, when we update the virtual network from `Internal` to `None` for the api management service, it'll not remove the usage from VNET in 3 hours. If we delete the VNET in 3 hours, it'll raise an error that the VNET could not be deleted for it's used in the api management.

**Comment by k-popov** [comment]
I got the point. Thank you!
