### ISSUE TITLE
Add Support for Azure Storage VNET Tunneling and Firewall.

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#787]
Could we please get support added for Azure Storage VNET Tunneling and Firewall?

https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security#grant-access-from-an-internet-ip-range

**Comment by katbyte** [comment]
Hi @rohrerb,

Closing as this appears to be a duplicate of #416.
