### ISSUE TITLE
Support for azurerm_container_group - mounting a Git repo to a container instance.

### ISSUE THREAD

**Issue by benhurjoel** [terraform-providers/terraform-provider-azurerm#7875]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Trying to create an Azure Container Group/Instances using Terraform. I see that it's possible to mount a GitRepo using Azure CLI but I do not see any reference for Terraform. Please feel free to advise, if I missed something.

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

resource "azurerm_container_group" "example" {
  name                = "${var.prefix}-packer"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  ip_address_type     = "public"
  os_type             = "linux"

  container {
    name     = "packer-demo"
    image    = "hashicorp/packer:full-1.6.0"
    cpu      = "1"
    memory   = "1.5"
    port     = "80"
    protocol = "tcp"

    volume {
      name       = "packer"
      mount_path = "/code/packer"
      read_only  = false
      git_repo_url = "<url> "    <--- new
     
    }
  }

### References

https://www.terraform.io/docs/providers/azurerm/r/container_group.html#volume
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-gitrepo

**Comment by njuCZ** [comment]
@benhurjoel I have submited a PR, hope it could unblock you soon

**Comment by benhurjoel** [comment]
@njuCZ Thank you and looking forward to it.

**Comment by celaus** [comment]
+1 that would be great to have

**Comment by nevesm** [comment]
+1 please add this for us!!

**Comment by benhurjoel** [comment]
Thank you folks! Appreciate it.
