### ISSUE TITLE
Failed to Provision Storage Container After Destroy 

### ISSUE THREAD

**Issue by massimo1993** [terraform-providers/terraform-provider-azurerm#7880]
### Terraform Version
Terraform v0.12.28
azurerm v2.20.0

### Terraform Configuration Files
```
resource azurerm_storage_account storage_account {
  name = lower(format("%s%s%s%02d",
    substr(
      module.naming.storage_account.name, 0, 
      module.naming.storage_account.max_length - 3
    ),
    substr(var.info.environment, 0, 1),
    substr(var.name, 0, 3),
    var.info.sequence
  ))

  resource_group_name      = var.resource_group
  location                 = var.location

  account_tier             = var.account_tier
  account_replication_type = var.account_replication_type
  is_hns_enabled           = var.is_hns_enabled

  tags = local.tags
}

resource azurerm_storage_account_network_rules network_rules {
  count = var.network_rules_enabled == true ? 1 : 0

  resource_group_name  = var.resource_group
  storage_account_name = azurerm_storage_account.storage_account.name

  default_action             = "Deny"
  ip_rules                   = [var.ip_rules_list]
  bypass                     = [var.bypass_list]
}

resource azurerm_storage_container container {
  count = var.storage_container_enabled == true ? 1 : 0

  name                  = var.container_name
  storage_account_name  = azurerm_storage_account.storage_account.name
  container_access_type = var.access_type
}
```

### Expected Behavior
A container should of been created after the storage account.

### Actual Behavior
```
Error: failed creating container: containers.Client#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The specified resource does not exist.\nRequestId:96d333ae-801e-0061-3b4b-6102d3000000\nTime:2020-07-23T23:48:36.2905446Z"

  on .terraform/modules/data_factory.storage_account/storage-account.tf line 33, in resource "azurerm_storage_container" "container":
  33: resource azurerm_storage_container container {
```

**Note:** If I wait x amount of minutes, 10 minutes for example and run another apply it works.

Also the storage account does exist when this issue happens.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. `terraform apply`
4. Wait x amount of minutes, maybe 5-10 minutes and apply again and issue solved.

### References
Seems to be related to issue #841

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested several times with your repro steps and below tfconfig which is similar with yours, seems I cannot repro this issue. Maybe I missed something. Could you have a try below tfconfig to check whether the issue still exists?
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-sc-test10"
  location = "eastus2"
}

resource "azurerm_storage_account" "test" {
  name                     = "acctestaccttest10"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "test" {
  name                  = "sctest10"
  storage_account_name  = azurerm_storage_account.test.name
  container_access_type = "private"
}
```

**Comment by massimo1993** [comment]
Thank you for the quick response, I will try out some more testing. The only thing that I can think of is that when I was using West US 2 as the location, I never faced the issue.

Thank you guys for the amazing provider, I use it at my job on a daily basis. I will test out my theory if the issue is related to location. I will let you know my findings.

**Comment by massimo1993** [comment]
I was able to reproduce the issue again by using the same location that I encountered the error.

```
azurerm_storage_account.storage_account: Creating...
azurerm_storage_account.storage_account: Still creating... [10s elapsed]
azurerm_storage_account.storage_account: Still creating... [20s elapsed]
azurerm_storage_account.storage_account: Creation complete after 26s [id=/subscriptions/8fa861fe-6a38-4b52-bc30-4df1ac4a70b5/resourceGroups/rgMassimoTf/providers/Microsoft.Storage/storageAccounts/stmassimo]
azurerm_storage_container.storage_container: Creating...
azurerm_storage_container.storage_container: Creation complete after 1s [id=https://stmassimo.blob.core.windows.net/massimotest]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

azurerm_storage_container.storage_container: Destroying... [id=https://stmassimo.blob.core.windows.net/massimotest]
azurerm_storage_container.storage_container: Destruction complete after 2s
azurerm_storage_account.storage_account: Destroying... [id=/subscriptions/8fa861fe-6a38-4b52-bc30-4df1ac4a70b5/resourceGroups/rgMassimoTf/providers/Microsoft.Storage/storageAccounts/stmassimo]
azurerm_storage_account.storage_account: Destruction complete after 3s

Destroy complete! Resources: 2 destroyed.

azurerm_storage_account.storage_account: Creating...
azurerm_storage_account.storage_account: Still creating... [10s elapsed]
azurerm_storage_account.storage_account: Still creating... [20s elapsed]
azurerm_storage_account.storage_account: Creation complete after 25s [id=/subscriptions/8fa861fe-6a38-4b52-bc30-4df1ac4a70b5/resourceGroups/rgMassimoTf/providers/Microsoft.Storage/storageAccounts/stmassimo]
azurerm_storage_container.storage_container: Creating...

Error: failed creating container: containers.Client#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The specified resource does not exist.\nRequestId:5a9ae7d9-501e-0046-2ddf-611bd2000000\nTime:2020-07-24T17:26:11.1834147Z"

  on storage_account.tf line 13, in resource "azurerm_storage_container" "storage_container":
  13: resource azurerm_storage_container storage_container {
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. Wait x amount of minutes, maybe 5-10 minutes and apply again and issue solved.

### Terraform Configuration Files

```
provider azurerm {
  features {}
}

resource azurerm_storage_account storage_account {
  name                     = "stmassimo"
  resource_group_name      = "rgMassimoTf"
  location                 = "southcentralus"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource azurerm_storage_container storage_container {
  name                  = "massimotest"
  storage_account_name  = azurerm_storage_account.storage_account.name
  container_access_type = "private"
}
```

**Note:** I am using South Central US as the location. I also tried West US 2 and same error. It doesn't seem to be location related.

**Comment by amanpurwar1** [comment]
**Working fine for me as i have destroyed and run apply again instantly** 


-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_resource_group.rg21 must be replaced
-/+ resource "azurerm_resource_group" "rg21" {
      ~ id       = "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/rg21" -> (known after apply)
      ~ location = "westus2" -> "eastus" # forces replacement
        name     = "rg21"
      - tags     = {} -> null
    }

  # azurerm_storage_account.storage_account must be replaced
-/+ resource "azurerm_storage_account" "storage_account" {
      ~ access_tier                      = "Hot" -> (known after apply)
        account_kind                     = "StorageV2"
        account_replication_type         = "LRS"
        account_tier                     = "Standard"
        allow_blob_public_access         = false
        enable_https_traffic_only        = true
      ~ id                               = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159" -> (known after apply)
        is_hns_enabled                   = false
      ~ location                         = "westus2" -> "eastus" # forces replacement
        name                             = "storage1159"

 /clouddrive/SRE/Azure/Terraform/storage$ terraform apply
azurerm_resource_group.rg21: Refreshing state... [id=/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Refreshing state... [id=/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_container.storage_container: Refreshing state... [id=https://storage1159.blob.core.windows.net/container1159]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_resource_group.rg21 must be replaced
-/+ resource "azurerm_resource_group" "rg21" {
      ~ id       = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21" -> (known after apply)
      ~ location = "westus2" -> "eastus" # forces replacement
        name     = "rg21"
      - tags     = {} -> null
    }

  # azurerm_storage_account.storage_account must be replaced
-/+ resource "azurerm_storage_account" "storage_account" {
      ~ access_tier                      = "Hot" -> (known after apply)
        account_kind                     = "StorageV2"
        account_replication_type         = "LRS"
        account_tier                     = "Standard"
        allow_blob_public_access         = false
        enable_https_traffic_only        = true
      ~ id                               = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159" -> (known after apply)
        is_hns_enabled                   = false
      ~ location                         = "westus2" -> "eastus" # forces replacement

   azurerm_storage_account.storage_account: Destroying... [id=/subscriptionsxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_account.storage_account: Destruction complete after 6s
azurerm_resource_group.rg21: Destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 10s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 20s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 30s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 40s elapsed]
azurerm_resource_group.rg21: Destruction complete after 49s
azurerm_resource_group.rg21: Creating...
azurerm_resource_group.rg21: Creation complete after 2s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Creating...
azurerm_storage_account.storage_account: Still creating... [10s elapsed]
azurerm_storage_account.storage_account: Still creating... [20s elapsed]
azurerm_storage_account.storage_account: Creation complete after 24s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]

Apply complete! Resources: 2 added, 0 changed, 2 destroyed.          

-------------------------------------------------------------------------------------------------------------------------

resource "azurerm_resource_group" "rg21" {
  name     = "rg21"
  location = "West US 2"
}

resource azurerm_storage_account storage_account {
  name                     = "storage1159"
  resource_group_name      = azurerm_resource_group.rg21.name
  location                 = azurerm_resource_group.rg21.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource azurerm_storage_container storage_container {
  name                  = "container1159"
  storage_account_name  = azurerm_storage_account.storage_account.name
  container_access_type = "private"
}

O/p
azurerm_resource_group.rg21: Creating...
azurerm_resource_group.rg21: Creation complete after 2s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Creating...
azurerm_storage_account.storage_account: Still creating... [10s elapsed]
azurerm_storage_account.storage_account: Still creating... [20s elapsed]
azurerm_storage_account.storage_account: Creation complete after 28s [id=/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_container.storage_container: Creating...
azurerm_storage_container.storage_container: Creation complete after 1s [id=https://storage1159.blob.core.windows.net/container1159]
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

**Comment by amanpurwar1** [comment]
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_resource_group.rg21 must be replaced
-/+ resource "azurerm_resource_group" "rg21" {
      ~ id       = "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/rg21" -> (known after apply)
      ~ location = "westus2" -> "eastus" # forces replacement
        name     = "rg21"
      - tags     = {} -> null
    }

  # azurerm_storage_account.storage_account must be replaced
-/+ resource "azurerm_storage_account" "storage_account" {
      ~ access_tier                      = "Hot" -> (known after apply)
        account_kind                     = "StorageV2"
        account_replication_type         = "LRS"
        account_tier                     = "Standard"
        allow_blob_public_access         = false
        enable_https_traffic_only        = true
      ~ id                               = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159" -> (known after apply)
        is_hns_enabled                   = false
      ~ location                         = "westus2" -> "eastus" # forces replacement
        name                             = "storage1159"

 /clouddrive/SRE/Azure/Terraform/storage$ terraform apply
azurerm_resource_group.rg21: Refreshing state... [id=/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Refreshing state... [id=/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_container.storage_container: Refreshing state... [id=https://storage1159.blob.core.windows.net/container1159]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_resource_group.rg21 must be replaced
-/+ resource "azurerm_resource_group" "rg21" {
      ~ id       = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21" -> (known after apply)
      ~ location = "westus2" -> "eastus" # forces replacement
        name     = "rg21"
      - tags     = {} -> null
    }

  # azurerm_storage_account.storage_account must be replaced
-/+ resource "azurerm_storage_account" "storage_account" {
      ~ access_tier                      = "Hot" -> (known after apply)
        account_kind                     = "StorageV2"
        account_replication_type         = "LRS"
        account_tier                     = "Standard"
        allow_blob_public_access         = false
        enable_https_traffic_only        = true
      ~ id                               = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159" -> (known after apply)
        is_hns_enabled                   = false
      ~ location                         = "westus2" -> "eastus" # forces replacement

   azurerm_storage_account.storage_account: Destroying... [id=/subscriptionsxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_account.storage_account: Destruction complete after 6s
azurerm_resource_group.rg21: Destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 10s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 20s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 30s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 40s elapsed]
azurerm_resource_group.rg21: Destruction complete after 49s
azurerm_resource_group.rg21: Creating...
azurerm_resource_group.rg21: Creation complete after 2s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Creating...
azurerm_storage_account.storage_account: Still creating... [10s elapsed]
azurerm_storage_account.storage_account: Still creating... [20s elapsed]
azurerm_storage_account.storage_account: Creation complete after 24s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
Apply complete! Resources: 2 added, 0 changed, 2 destroyed.

**Comment by amanpurwar1** [comment]
/clouddrive/SRE/Azure/Terraform/storage$ terraform apply
azurerm_resource_group.rg21: Refreshing state... [id=/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Refreshing state... [id=/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_container.storage_container: Refreshing state... [id=https://storage1159.blob.core.windows.net/container1159]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_resource_group.rg21 must be replaced
-/+ resource "azurerm_resource_group" "rg21" {
      ~ id       = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21" -> (known after apply)
      ~ location = "westus2" -> "eastus" # forces replacement
        name     = "rg21"
      - tags     = {} -> null
    }

  # azurerm_storage_account.storage_account must be replaced
-/+ resource "azurerm_storage_account" "storage_account" {
      ~ access_tier                      = "Hot" -> (known after apply)
        account_kind                     = "StorageV2"
        account_replication_type         = "LRS"
        account_tier                     = "Standard"
        allow_blob_public_access         = false
        enable_https_traffic_only        = true
      ~ id                               = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159" -> (known after apply)
        is_hns_enabled                   = false
      ~ location                         = "westus2" -> "eastus" # forces replacement

   azurerm_storage_account.storage_account: Destroying... [id=/subscriptionsxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_account.storage_account: Destruction complete after 6s
azurerm_resource_group.rg21: Destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 10s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 20s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 30s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 40s elapsed]
azurerm_resource_group.rg21: Destruction complete after 49s
azurerm_resource_group.rg21: Creating...
azurerm_resource_group.rg21: Creation complete after 2s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Creating...
azurerm_storage_account.storage_account: Still creating... [10s elapsed]
azurerm_storage_account.storage_account: Still creating... [20s elapsed]
azurerm_storage_account.storage_account: Creation complete after 24s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]

Apply complete! Resources: 2 added, 0 changed, 2 destroyed.

**Comment by amanpurwar1** [comment]
Working fine for me as i have destroyed and run apply instantly  it created SA as well as Container

clouddrive/SRE/Azure/Terraform/storage$ terraform apply
  azurerm_storage_account.storage_account must be replaced
-/+ resource "azurerm_storage_account" "storage_account" {
      ~ access_tier                      = "Hot" -> (known after apply)
        account_kind                     = "StorageV2"
        account_replication_type         = "LRS"
        account_tier                     = "Standard"
        allow_blob_public_access         = false
        enable_https_traffic_only        = true
      ~ id                               = "/subscriptions//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159" -> (known after apply)
        is_hns_enabled                   = false
      ~ location                         = "westus2" -> "eastus" # forces replacement

   azurerm_storage_account.storage_account: Destroying... [id=/subscriptionsxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
azurerm_storage_account.storage_account: Destruction complete after 6s
azurerm_resource_group.rg21: Destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 10s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 20s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 30s elapsed]
azurerm_resource_group.rg21: Still destroying... [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21, 40s elapsed]
azurerm_resource_group.rg21: Destruction complete after 49s
azurerm_resource_group.rg21: Creating...
azurerm_resource_group.rg21: Creation complete after 2s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21]
azurerm_storage_account.storage_account: Creating...
azurerm_storage_account.storage_account: Still creating... [10s elapsed]
azurerm_storage_account.storage_account: Still creating... [20s elapsed]
azurerm_storage_account.storage_account: Creation complete after 24s [id=/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg21/providers/Microsoft.Storage/storageAccounts/storage1159]
Apply complete! Resources: 2 added, 0 changed, 2 destroyed.

**Comment by amanpurwar1** [comment]
resource azurerm_storage_account storage_account {
  name                     = "storage1159"
  resource_group_name      = azurerm_resource_group.rg21.name
  location                 = azurerm_resource_group.rg21.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource azurerm_storage_container storage_container {
  name                  = "container1159"
  storage_account_name  = azurerm_storage_account.storage_account.name
  container_access_type = "private"
}

**Comment by massimo1993** [comment]
I don't know what else to say, it must be some environment issue or maybe my Azure account. I guess we can close this issue for now. It's kind of odd and weird that I am always able to reproduce it in every try.

**Comment by amanpurwar1** [comment]
You can close the issue

Regards
Aman
