### ISSUE TITLE
CDN Profile in Global region not compatible with AzureRM v2.20.0

### ISSUE THREAD

**Issue by oleksiypavlenko** [terraform-providers/terraform-provider-azurerm#7881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.29
+ provider.azurerm v2.20.0

### Affected Resource(s)

* `azurerm_cdn_profile`
* `azurerm_cdn_endpoint`

### Terraform Configuration Files

This is existing configuration used in Terraform v0.12.28 & AzureRM v2.19.0 without problem:

```hcl
resource "azurerm_cdn_profile" "some-cdn" {
  name                = "some-cdn"
  location            = "Global"
  resource_group_name = azurerm_resource_group.resource-group.name
  sku                 = "Standard_Microsoft"

  tags = {
    environment = azurerm_resource_group.resource-group.tags.environment
  }
}
```

### Expected Behavior

Should detect no changes after upgrading to AzureRM v2.20.0

### Actual Behavior

Error: "global" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,k
oreacentral,koreasouth,indiasouth,indiawest,indiacentral,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlan
dwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast"

Also tried changing configuration to region of resource group:

```hcl
resource "azurerm_cdn_profile" "some-cdn" {
  name                = "some-cdn"
  location            = "eastus2"
  resource_group_name = azurerm_resource_group.resource-group.name
  sku                 = "Standard_Microsoft"

  tags = {
    environment = azurerm_resource_group.resource-group.tags.environment
  }
}
```

In this case got message:
```hcl
 # azurerm_cdn_profile.some-cdn must be replaced
/+ resource "azurerm_cdn_profile" "some-cdn" {
     ~ id                  = "/subscriptions/......
     ~ location            = "global" -> "eastus2" # forces replacement
       name                = "some-cdn"
       resource_group_name = "Some-ResourceGroup-EastUS2"
       sku                 = "Standard_Microsoft"
       tags                = {
           "environment" = "engr"
       }

     - timeouts {}
   }
```
Tried removing the resource from Terraform state by using `terraform state rm` and re-importing using region specific config without luck, still results in "must be replaced" message.

### Steps to Reproduce

1. Upgrade AzureRM provider to v2.20.0
2. `terraform plan`

### Important Factoids

The resource is reported to be in Global region

![image](https://user-images.githubusercontent.com/17528298/88350734-d8442b00-cd08-11ea-9f08-af84e84bdf2a.png)

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Terraform introduces an environment variable `ARM_PROVIDER_ENHANCED_VALIDATION` for improving the location validation and default value is true since 2.20. For your case, if you want to use `global` location, please set this environment variable as `false` and try again, then it should pass. See more details from [changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#2200-july-23-2020).

**Comment by oleksiypavlenko** [comment]
Thank you for the workaround @neil-yechenwei 
It's unfortunate the validation needs to be disabled, because there are other resources in the same workspace which would benefit from it.
Please close the ticket if there are no plans of introducing "global" region.
