### ISSUE TITLE
Version 2.20.0 reports an error during plan for BotChannel

### ISSUE THREAD

**Issue by ElliotMatthew** [terraform-providers/terraform-provider-azurerm#7891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_bot_channels_registration`

### Terraform Configuration Files

```hcl
# Bot channels registration
resource "azurerm_bot_channels_registration" "cr" {
  # Bot channels registration names must be globally unique across Azure, so use
  # a hashed seed value to generate a name with a high chance of being unique.
  # names must also be at most 42 characters, so trim the result.
  name                = substr("bot-reg-${md5(var.seed_value)}", 0, 42)
  location            = "global"
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "F0"
  microsoft_app_id    = local.app_reg_id
  endpoint            = "https://${azurerm_app_service.app.default_site_hostname}/api/messages"
}
```

### Debug Output

https://gist.github.com/ElliotMatthew/8f09456ec52d67cefaf4ff3e33fbccf7

### Expected Behavior

The resource should be created with the location "global".

### Actual Behavior

The resource failed to be configured and the Plan stage fails within gitlab pipeline

### Steps to Reproduce

1. Create a resource containing a BotChannel registration as above (with a global location)
2. `terraform plan -out "planfile.txt"`

### References

* #0000

**Comment by oleksiypavlenko** [comment]
Looks like related to this issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/7881
Cannot create CDN in "global" region after v2.20.0 upgrade

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Terraform introduces an environment variable `ARM_PROVIDER_ENHANCED_VALIDATION` for improving the location validation and default value is true since 2.20. For your case, if you want to use `global` location, please set this environment variable as `false` and try again, then it should be passed.
