### ISSUE TITLE
Support for max_surge parameter on azurerm_kubernetes_cluster_node_pool

### ISSUE THREAD

**Issue by jmcshane** [terraform-providers/terraform-provider-azurerm#7892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support the max surge parameter for upgrading node pools. Available in sdk-for-go in the 2020-04-01 API version [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerservice/mgmt/2020-04-01/containerservice/models.go#L1214).

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  
  upgrade_settings {
    max_surge = 2
    ## or max_surge = 50%
  }
  tags = {
    Environment = "Production"
  }
}

```

### References

* https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-up-the-preview-feature-for-customizing-node-surge-upgrade

**Comment by shapeofarchitect** [comment]
Can we please , please start to merge these important Pull Requests ?
