### ISSUE TITLE
Feature Requests: Express route peering for ExpressRoute routing domains

### ISSUE THREAD

**Issue by rafael6** [terraform-providers/terraform-provider-azurerm#790]
Feature Requests 
Express route peering for ExpressRoute routing domains
https://docs.microsoft.com/en-us/azure/expressroute/expressroute-circuit-peerings

### Terraform Version
11.2

### Affected Resource(s)
- azurerm_express_route_circuit

### Terraform Configuration Files
N/A Request for new feature 

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
N/A

### Actual Behavior
N/A

### Steps to Reproduce
N/A

### Important Factoids
Using Azurerm provider

### References
N/A

**Comment by tombuildsstuff** [comment]
hey @rafael6 

Thanks for opening this issue :)

Just to let you know that support for this shipped yesterday in v1.3.1 of the AzureRM Provider: https://www.terraform.io/docs/providers/azurerm/r/express_route_circuit_peering.html :)

Thanks!
