### ISSUE TITLE
Azure Kubernetes cluster => unsupported block type error.

### ISSUE THREAD

**Issue by deepanshumarwah** [terraform-providers/terraform-provider-azurerm#7903]
### Terraform (and AzureRM Provider) Version

Provider version : 2.15
Terraform version: 0.12

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "K8s" {
  name                    = var.name
  location                = var.location
  resource_group_name     = var.resource_group_name
  tags                    = var.tags
  private_cluster_enabled = var.private_cluster_enabled
  dns_prefix              = var.dns_prefix

  default_node_pool {
    name       = var.node_name
    vm_size    = var.vm_size
    node_count = var.node_count
  }

  identity {
    type = var.identity_type
  }

  network_profile {
    network_plugin    = var.network_plugin
    load_balancer_sku = var.load_balancer_sku
  }

  addon_profile {
    oms_agent {
      enabled = var.oms_agent_enabled
    }
    kube_dashboard {
      enabled = var.kube_dashboard_enabled
    }
  }
}
```

### Actual Behavior

Error: Unsupported block type

  on main.tf line 61, in module "azurerm_kubernetes_cluster":
  61:   default_node_pool {

Blocks of type "default_node_pool" are not expected here.

Error: Unsupported block type

  on main.tf line 67, in module "azurerm_kubernetes_cluster":
  67:   identity {

Blocks of type "identity" are not expected here.

Error: Unsupported block type

  on main.tf line 71, in module "azurerm_kubernetes_cluster":
  71:   network_profile {

Blocks of type "network_profile" are not expected here.

Error: Unsupported block type

  on main.tf line 76, in module "azurerm_kubernetes_cluster":
  76:   addon_profile {

Blocks of type "addon_profile" are not expected here.

[terragrunt] 2020/07/27 09:41:46 Hit multiple errors:
exit status 1

### Steps to Reproduce

1. `terraform plan`

**Comment by amanpurwar1** [comment]
Whats variables you have declared in vars.tf

**Comment by deepanshumarwah** [comment]
All of these 
```variable "name" {
  description = "The name of the Managed Kubernetes Cluster."
  type        = string
}

variable "location" {
  description = " The Azure location where the Managed Kubernetes Cluster will be provisioned."
  type        = string
}

variable "resource_group_name" {
  description = "The name of the resource group in which this Managed Kubernetes Cluster will be provisioned."
  type        = string
}

variable "tags" {
  description = "A mapping of tags to assign to the resource."
  type        = map(string)
  default     = {}
}

variable "dns_prefix" {
  description = "The DNS prefix associated to the managed cluster."
  type        = string
}

variable "kubernetes_version" {
  description = "Version of Managed Kubernetes Cluster."
  type        = string
  default     = "1.16.10"
}

variable "private_cluster_enabled" {
  description = "This is to expose API server to internal IP addresses only."
  type        = bool
  default     = true
}

variable "identity_type" {
  description = "The type of identity used for the managed cluster."
  type        = string
  default     = "SystemAssigned"
}

variable "network_plugin" {
  description = "Network plugin to use for networking."
  type        = string
  default     = "azure"
}

variable "load_balancer_sku" {
  description = "This is the sku for load balancer used for Kubernetes Cluster."
  type        = string
  default     = "Standard"
}

variable "log_analytics_workspace_id" {
  description = "The ID of log analytics workspace for AKS self monitoring by Sentinel."
  type        = string
}

variable "oms_agent_enabled" {
  description = "This is to enable oms agent on AKS cluster for self monitoring by sentinel."
  type        = bool
  default     = true
}

variable "kube_dashboard_enabled" {
  description = "This is to enable Kubernetes dashboard."
  type        = bool
  default     = true
}

variable "node_name" {
  description = "The name of node inside node pool."
  type        = string
  default     = "logstash-dev"
}

variable "vm_size" {
  description = "The size of virtual machine for each node."
  type        = string
  default     = "Standard_DS1_v2"
}

variable "enable_auto_scaling" {
  description = "This is to enable auto-scaling of nodes."
  type        = bool
  default     = false
}

variable "node_count" {
  description = "The number of nodes required to be deployed."
  type        = number
  default     = 3
}

variable "vnet_subnet_id" {
  description = "The subnet id inside vnet where aks cluster is to be deployed."
  type        = string
}

variable "os_disk_size_gb" {
  description = "The size of os disk in gb."
  type        = string
  default     = "30"
}

variable "node_pool_tags" {
  description = "A mapping of tags to assign to the nodes."
  type        = map(string)
  default     = {}
}
```

**Comment by amanpurwar1** [comment]
Remove dash in name of node_name. in vars.tf 

harish@Azure:~/clouddrive/SRE/Azure/Terraform/aks1$ terraform apply
var.dns_prefix
  The DNS prefix associated to the managed cluster.

  Enter a value: exampleaks1

var.location
   The Azure location where the Managed Kubernetes Cluster will be provisioned.

  Enter a value: East US

var.log_analytics_workspace_id
  The ID of log analytics workspace for AKS self monitoring by Sentinel.

  Enter a value: testLogAnalyticsWorkspaceName1

var.name
  The name of the Managed Kubernetes Cluster.

  Enter a value: aks234

var.resource_group_name
  The name of the resource group in which this Managed Kubernetes Cluster will be provisioned.

  Enter a value: rg1234

var.vnet_subnet_id
  The subnet id inside vnet where aks cluster is to be deployed.

  Enter a value: aks-subnet


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_kubernetes_cluster.K8s will be created
  + resource "azurerm_kubernetes_cluster" "K8s" {
      + dns_prefix              = "exampleaks1"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + kube_admin_config       = (known after apply)
      + kube_admin_config_raw   = (sensitive value)
      + kube_config             = (known after apply)
      + kube_config_raw         = (sensitive value)
      + kubelet_identity        = (known after apply)
      + kubernetes_version      = (known after apply)
      + location                = "eastus"
      + name                    = "aks234"
      + node_resource_group     = (known after apply)
      + private_cluster_enabled = true
      + private_fqdn            = (known after apply)
      + private_link_enabled    = (known after apply)
      + resource_group_name     = "rg1234"
      + sku_tier                = "Free"

      + addon_profile {

          + kube_dashboard {
              + enabled = true
            }

          + oms_agent {
              + enabled            = true
              + oms_agent_identity = (known after apply)
            }
        }

      + auto_scaler_profile {
          + balance_similar_node_groups      = (known after apply)
          + max_graceful_termination_sec     = (known after apply)
          + scale_down_delay_after_add       = (known after apply)
          + scale_down_delay_after_delete    = (known after apply)
          + scale_down_delay_after_failure   = (known after apply)
          + scale_down_unneeded              = (known after apply)
          + scale_down_unready               = (known after apply)
          + scale_down_utilization_threshold = (known after apply)
          + scan_interval                    = (known after apply)
        }

      + default_node_pool {
          + max_pods             = (known after apply)
          + name                 = "logstashdev"
          + node_count           = 3
          + orchestrator_version = (known after apply)
          + os_disk_size_gb      = (known after apply)
          + type                 = "VirtualMachineScaleSets"
          + vm_size              = "Standard_DS1_v2"
        }

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + network_profile {
          + dns_service_ip     = (known after apply)
          + docker_bridge_cidr = (known after apply)
          + load_balancer_sku  = "Standard"
          + network_plugin     = "azure"
          + network_policy     = (known after apply)
          + outbound_type      = "loadBalancer"
          + pod_cidr           = (known after apply)
          + service_cidr       = (known after apply)

          + load_balancer_profile {
              + effective_outbound_ips    = (known after apply)
              + idle_timeout_in_minutes   = (known after apply)
              + managed_outbound_ip_count = (known after apply)
              + outbound_ip_address_ids   = (known after apply)
              + outbound_ip_prefix_ids    = (known after apply)
              + outbound_ports_allocated  = (known after apply)
            }
        }

      + role_based_access_control {
          + enabled = (known after apply)

          + azure_active_directory {
              + admin_group_object_ids = (known after apply)
              + client_app_id          = (known after apply)
              + managed                = (known after apply)
              + server_app_id          = (known after apply)
              + server_app_secret      = (sensitive value)
              + tenant_id              = (known after apply)
            }
        }

      + windows_profile {
          + admin_password = (sensitive value)
          + admin_username = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

**Comment by deepanshumarwah** [comment]
cool. thanks for your help.

**Comment by amanpurwar1** [comment]
Please close the issue

Regards
Aman
