### ISSUE TITLE
Crash when importing azurerm_virtual_network

### ISSUE THREAD

**Issue by antuAnoro** [terraform-providers/terraform-provider-azurerm#791]
### Terraform Version
0.11.3

### Affected Resource(s)
azurerm_virtual_network

### Terraform Configuration Files
```hcl
...

# Variables

variable "az_subscription_id" {
  description = "Id suscripción azure"
}

variable "az_client_id" {
  description = "Cliente azure"
}

variable "az_client_secret" {
  description = "Clave cliente azure"
}

variable "az_tenant_id" {
  description = "Tenant azure"
}

# Providers. 

provider "azurerm" {
  subscription_id = "${var.az_subscription_id}"
  client_id = "${var.az_client_id}"
  client_secret = "${var.az_client_secret}"
  tenant_id = "${var.az_tenant_id}"
}

# Data.

data "azurerm_resource_group" "UNIR" {
  name = "UNIR_DevOps_rg"
}

data "azurerm_virtual_network" "UNIR" {
  name = "UNIR_DevOps_rg-vnet"
  resource_group_name = "${data.azurerm_resource_group.UNIR.name}"
}

...

```

### Panic Output
https://github.com/antuAnoro/PracticasDevOps/blob/master/terraform/LAMP_Multicapa/crash.log

### Expected Behavior
Succesful import of the data

### Actual Behavior
Crash

### Steps to Reproduce
'terraform plan'

### Important Factoids
Azurem Virtual Network created through the Portal, with 1 default subnet. No custom DNS servers.

### References
https://github.com/hashicorp/terraform/issues/9410

**Comment by tombuildsstuff** [comment]
hey @antuAnoro 

Thanks for opening this issue :)

Taking a look into this this is the same issue as #801 - which will be fixed in #803. Rather than keeping multiple issues open tracking the same thing - I'm going to close this issue in favour of #801

Thanks!
