### ISSUE TITLE
Support for [thing]

### ISSUE THREAD

**Issue by daniel-elhs** [terraform-providers/terraform-provider-azurerm#7923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It's about attaching ACR to AKS like: az aks update -n myAKSCluster -g myResourceGroup --attach-acr <acrName>
Any chance to introduce that one?

See also: https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration?toc=/azure/container-registry/toc.json&bc=/azure/container-registry/breadcrumb/toc.json 

I am going to try that a long way with managed service principals, but I am certain you can find a more convenient approach :-)

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

**Comment by aristosvo** [comment]
This works for me:
```hcl

resource "azurerm_role_assignment" "acrpull_role" {
  scope                            = data.azurerm_subscription.primary.id
  role_definition_name             = "AcrPull"
  principal_id                     = azurerm_kubernetes_cluster.deployment.kubelet_identity.0.object_id
  skip_service_principal_aad_check = true
}
```

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here as @aristosvo has mentioned this should be possible by using a Role Assignment, and as I'm going to close this issue for the moment - but if that doesn't work for you please let us know and we can reopen this and take another look.

Thanks!

**Comment by daniel-elhs** [comment]
Thanks a lot for that, looks now for me, but I had to upgrade my role to "owner". Any hint for a more specific role or even custom role would be welcome.
Finally, having something like acr = myAcrName within aks terraform resource would be much more intuitive, on the other hand a nice to have, at the approach above works well

**Comment by tombuildsstuff** [comment]
@daniel-elhs either 'Contributor' or 'User Access Administrator' to the relevant scope for the role assignment should give you permissions - however note that AKS provisions to a new resource group at the subscription level, so you'd need permissions to manage these at the subscription level rather than being able to scope that to a resource group ahead of time, due to the way AKS is designed today (unfortunately).
