### ISSUE TITLE
azurerm_container_group  doesn't support multiple environment_variables

### ISSUE THREAD

**Issue by lengland** [terraform-providers/terraform-provider-azurerm#7928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
▶ terraform -v
Terraform v0.12.29
+ provider.azurerm v2.20.0
```

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "example" {
  name                = "example-continst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  os_type             = "Linux"
  restart_policy      = "Never"

  identity {
    type = "SystemAssigned"
  }

  container {
    name   = "my-container"
    image  = "busybox"
    cpu    = "0.5"
    memory = "1.5"

    ports {
      port     = 5000
      protocol = "TCP"
    }
    
    environment_variables = {
      SERVER_NAME   = "server.example"
      DATABASE_NAME = "database"
    }
  }
}
```

### Expected Behavior

The container instance in the group is created with all the environment variables attached

### Actual Behavior

Only the first environment variable is set in the Container Instance

### Steps to Reproduce

1. `terraform apply`
1. Check the Container Instance properties in the Azure Portal

### Important Factoids

I have tried running this with the keys and values quoted, eg `"SERVER_NAME"="server.example"`. And also as a plain property block, eg ` environment_variables { ... }`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested with below tfconfig, seems I cannot repro this issue since these two environment variables can be created successfully. Could you have a try below tfconfig to check whether the issue still exists? Thanks.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-aci-resources"
  location = "eastus2"
}

resource "azurerm_container_group" "example" {
  name                = "example-continst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  os_type             = "Linux"
  restart_policy      = "Never"

  identity {
    type = "SystemAssigned"
  }

  container {
    name   = "my-container"
    image  = "busybox"
    cpu    = "0.5"
    memory = "1.5"

    ports {
      port     = 5000
      protocol = "TCP"
    }
    
    environment_variables = {
      SERVER_NAME   = "server.example"
      DATABASE_NAME = "database"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/19754191/88770118-e635f800-d1af-11ea-9c00-2f4bc3d8f712.png)

**Comment by lengland** [comment]
Hi @neil-yechenwei ,

I've tried your solution and it works perfectly in both the `eastus2` and `uksouth` regions. I also applied my previous config to find that that also worked now. So it seems I was facing a transient problem last night.

Comparing the TF Plan outputs of both configs produces the same results, so I assume this is resolved. 

Thanks

**Comment by neil-yechenwei** [comment]
Since this issue has been resolved, could you close this issue? If you have other issues, please open a new one. Thanks.
