### ISSUE TITLE
Unable to Create Cognitive Account Bing Spell Check Resource

### ISSUE THREAD

**Issue by ebunassar** [terraform-providers/terraform-provider-azurerm#7931]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.25
+ provider.azurerm v2.20.0

### Affected Resource(s)

* `azurerm_cognitive_account`

### Terraform Configuration Files

```hcl
locals {
  env        = substr(terraform.workspace, 0, 3)
  location   = "northcentralus"
  tags       = {
    "PROVISIONED_BY" : "Terraform"
  }
}

resource "azurerm_resource_group" "resource_group" {
  name     = format("rg-%s-%s", local.location, terraform.workspace)
  location = local.location
  tags     = local.tags
}

resource "azurerm_cognitive_account" "cog" {
  name                = format("cog-%s-%s", azurerm_resource_group.resource_group.location, terraform.workspace)
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  kind                = "Bing.SpellCheck.v7"
  sku_name            = "F0"
  tags                = local.tags
}
```

### Expected Behavior

Spell Check resource should have been created.

### Actual Behavior

Error: Error creating Cognitive Services Account "REMOVED" (Resource Group "REMOVED"): cognitiveservices.AccountsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiSetId" Message="The account type 'Bing.SpellCheck.v7' is either invalid or unavailable in given region."

### Steps to Reproduce

1. `terraform workspace new bingsearchtest`
2. `terraform apply`

### Important Factoids

I also tried the following:
+ Manually create the resource via the Azure Portal
+ `terraform import azurerm_cognitive_account.cog <manually created resoruce ID>`
+ `terraform plan`

which shows the following output:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_cognitive_account.cog must be replaced
-/+ resource "azurerm_cognitive_account" "cog" {
      ~ endpoint             = "https://REMOVED.cognitiveservices.azure.com/bing/v7.0/spellcheck" -> (known after apply)
      ~ id                   = "/subscriptions/REMOVED/resourcegroups/REMOVED/providers/Microsoft.CognitiveServices/accounts/REMOVED" -> (known after apply)
        kind                 = "Bing.SpellCheck.v7"
      ~ location             = "global" -> "northcentralus" # forces replacement
        name                 = "REMOVED"
      ~ primary_access_key   = (sensitive value)
        resource_group_name  = "REMOVED"
      ~ secondary_access_key = (sensitive value)
        sku_name             = "F0"
      ~ tags                 = {
          + "PROVISIONED_BY" = "Terraform"
        }

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```
If you try changing the location to "global" as it shows from the manually created resource you get the following error:
```
Error: "global" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,indiasouth,indiawest,indiacentral,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast"
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #8042
