### ISSUE TITLE
Ability for Application Gateway to Ignore Rules Externally Added (e.g. from AGIC)

### ISSUE THREAD

**Issue by davejhahn** [terraform-providers/terraform-provider-azurerm#7935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using Azure Gateway Ingress Controller (AGIC), which works in conjunction with Application Gateway, rules are added as part of application deployments.  

After deploying applications, which adds the rules, if the gateway is subsequently deployed through Terraform, everything that is added from AGIC is wiped and put in the initial state.  

### New or Affected Resource(s)
azurerm_application_gateway

### Potential Terraform Configuration
This could probably be solved a couple of different ways, but the one that makes most sense is just ignoring rules that are not explicitly defined in Terraform.  e.g. if there is a backend_address_pool, backend_http_settings, http_listener, that is found, do not destroy, only address the items that are in Terraform.  I'm pretty sure there are other Terraform resource modules that work this way--if it is updated outside of Terraform, it doesn't destroy it.   Maybe this could be an option if it is not desirable for everyone.

### References
At least one person has created a module to do just this, although there are disclaimers so not sure of the current state:
https://github.com/avinor/terraform-azurerm-application-gateway

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Per my understanding, terraform manages resources on resource level, which means it wouldn't handle resource on property level. So suggests to use terraform to add these properties or use ignore_changes to workaround these properties.

**Comment by davejhahn** [comment]
@neil-yechenwei in looking at how ignore_changes works and azurerm_application_gateway I'm not sure it would work.  

For example, one or more backend_http_settings blocks are required within the azurerm_application_gateway resource.  If you start with one block on creation, e.g. a default, even if you had ignore_changes on that, because the other blocks don't yet exist, when the external process (AGIC) adds additional backends, running again will have nothing for it in the backend_http_settings and just delete it.

`resource "azurerm_application_gateway" "k8s" {
    name                 = var.gateway_name
    location             = var.gateway_location
    resource_group_name  = var.resource_group_name

  backend_http_settings {
    name                  = "appGatewayBackendHttpSettings"
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 30
  }  
}

`
As above, since the new backend_http_settings doesn't exist, there is nothing you can put ignore_changes around, if it was defined, it would be another backend_http_settings block.

**Comment by JorTurFer** [comment]
Hi @davejhahn ,
I answered you in https://github.com/Azure/application-gateway-kubernetes-ingress/issues/959#issuecomment-667200213
The problem here is that you should add the properly ignores in the terraform lifecycle

**Comment by davejhahn** [comment]
I was able to get this to work by using the ignore_changes--thanks for everyone's help.
