### ISSUE TITLE
Feature Request: new resource to attach disks to virtual machines

### ISSUE THREAD

**Issue by ned1313** [terraform-providers/terraform-provider-azurerm#795]
An issue that I have run into recently is the inability to use a count function when adding data disks to a VM storage configuration.  I can create the data disks using a count function outside of the resource, but I have to specify multiple storage_data_disk items in the azurerm_virtual_machine resource to get them attached.  Hashicorp is considering ways to added a count function within a resource (using the foreach terminology in this [thread](https://github.com/hashicorp/terraform/issues/7034)).  

Rather than waiting for that approach to shake out, I would like to request that resources like azurerm_managed_disk support a mapping function to attach to a azurerm_virtual_machine resource, or that a new mapping resource be created that will map the attachment of the disk to the virtual machine, something like azurerm_managed_disk_attach.  Here's an example of how that would work:

```hcl
resource azurerm_managed_disk_attach {
  name  =  "disk-attach-${count.index}"
  count  =  "${var.number-of-disks}"
  disk_id  =  "${element(azurerm_managed_disk.mydisk.*.id, count.index)}"
  vm_id  =  "${azurerm_virtual_machine.mymachine.id}"
}
```

**Comment by clangaxon** [comment]
This would be a huge benefit for us as well.

**Comment by tombuildsstuff** [comment]
👋 hey all

I spent some time on Friday trying to work out how we'd achieve this and have opened #1207 which includes a new resource for attaching disks. This is still in an early phase and needs extensive testing - which we'll look into later in the week

Thanks!
