### ISSUE TITLE
Provider behavior changed for azurerm_api_management_api resource and now subscription_required defaults to false

### ISSUE THREAD

**Issue by amit-ch** [terraform-providers/terraform-provider-azurerm#7950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.16.0
```

### Affected Resource(s)

* `azurerm_api_management_api`

### Terraform Configuration Files

```terraform
provider "azurerm" {
  version = "=2.16.0"
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_api_management" "example" {
  name                = "example-apim"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku_name = "Developer_1"
}

resource "azurerm_api_management_api" "example" {
  name                = "example-api"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  revision            = "1"
  display_name        = "Example API"
  path                = "example"
  protocols           = ["https"]

  import {
    content_format = "swagger-link-json"
    content_value  = "http://conferenceapi.azurewebsites.net/?format=json"
  }
}
```

### Expected Behavior

Earlier version of azurerm <= 2.15 created an API with subscription_required = true by default which makes all the APIs secure.
![image](https://user-images.githubusercontent.com/28331812/88827847-5e0d1e00-d1c2-11ea-8095-bb39c8136598.png)

### Actual Behavior

AzureRm now creates API with subscription_required = false by default, making all apis that were previously secure suddenly public. Also this is not the same experience when API is created manually through portal which also have checkbox selected by default for subscription required. Those who have not pinned the azurerm version may accidentally release a public API in production. Better to set the default as true and secure and allow users to override it by setting it to false when a public API is required

![image](https://user-images.githubusercontent.com/28331812/88828840-ae38b000-d1c3-11ea-96a6-ab2b1813aeab.png)

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/3863

**Comment by alastairtree** [comment]
This is a security issue for us and has made some stuff public that required keys before, as we use modules that do not restrict provider version. Please fix!
