### ISSUE TITLE
azurerm_app_service_hybrid_connection - clarification on send_key_name

### ISSUE THREAD

**Issue by Marcus-James-Adams** [terraform-providers/terraform-provider-azurerm#7955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
+ provider.azurerm v2.16.0

### Affected Resource(s)

azurerm_app_service_hybrid_connection

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
resource "azurerm_relay_namespace" "main" {
  name                = var.name
  location            = var.location
  resource_group_name = azurerm_resource_group.main.name

  sku_name = "Standard"
}

resource "azurerm_relay_hybrid_connection" "main" {
  name                 = var.name
  resource_group_name  = azurerm_resource_group.main.name
  relay_namespace_name = azurerm_relay_namespace.main.name
}

resource "azurerm_app_service_hybrid_connection" "main-app-web" {
  app_service_name    = azurerm_app_service.main.name
  resource_group_name = azurerm_resource_group.main.name
  relay_id            = azurerm_relay_hybrid_connection.main.id
  hostname            = "${var.env_short}-${var.composer_server}"
  port                = 1433
  send_key_name       = azurerm_relay_namespace.main.name
}

```
### Expected  Behavior
Should apply ok
### Actual Behavior

The app service is already created in TF, the namespace & relay_hybrid_connection create ok but on going to make the app_service_hybrid_connection it fails.

Error: unable to List Access Keys for Namespace "nf-c17-uks-advz-rns" (Resource Group "nf-c17-uks-advz-rsg"): relay.NamespacesClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "\"The requested resource XXXXXXX does not exist.\"" error: json: cannot unmarshal string into Go value of type azure.RequestError

It is unsure from the documentation what the value of send_key_name  should be.
https://www.terraform.io/docs/providers/azurerm/r/app_service_hybrid_connection.html

The docs say send_key_name - (Required) The name of the Service Bus key. as per above
the Example says "exampleSharedAccessKey" which implies it to b eazurerm_relay_namespace.main. primary_key 
but as the example is just text, I have also tried creating an access string and trying that.
Each way I get the above message with the XXXXXXX resource being shown as whatever I put in the send_key_name field

* #0000

**Comment by njuCZ** [comment]
@Marcus-James-Adams I am sorry that the document is not detailed. The `send_key_name` means: The name of the Service Bus key which has Send permissions. This is used to authenticate to Service Bus.

According to https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#shared-access-authorization-policies
```
When you create a Service Bus namespace, a policy rule named RootManageSharedAccessKey is automatically created for the namespace. This policy has Manage permissions for the entire namespace
```

you could directly use `send_key_name = "RootManageSharedAccessKey"` (this is also the default value) or create a new rule and then use it as `send_key_name`.

I will also fire a PR to update the document. Thanks

**Comment by Marcus-James-Adams** [comment]
Hi,
thanks for that,

I did try that and it resolved the error on creation.  However when you run the hybrid collector client on the endpoint server whilst it shows the connection it is grayed out as it shows the endpoint as blank
