### ISSUE TITLE
azurerm_dns_a_record; "Can not perform requested operation on nested resource. Parent resource 'privatelink.web.core.windows.net' not found."

### ISSUE THREAD

**Issue by fluffy-cakes** [terraform-providers/terraform-provider-azurerm#7964]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v0.12.26

### Affected Resource(s)

* `azurerm_private_dns_zone`
* `azurerm_dns_a_record`

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_zone" "hub_storage_dns_zone" {
    name                    = "privatelink.web.core.windows.net"
    resource_group_name     = azurerm_resource_group.azure_dns_rg.name
    tags                    = var.global_settings.tags
}

resource "azurerm_dns_a_record" "asdf" {
    name                    = "asdf"
    zone_name               = azurerm_private_dns_zone.hub_storage_dns_zone.name
    resource_group_name     = azurerm_resource_group.azure_dns_rg.name
    ttl                     = 300
    records                 = ["1.1.1.1"]
    depends_on              = [
        azurerm_private_dns_zone.hub_storage_dns_zone
    ]
}
```

### Debug Output
```hcl
Error: Error creating/updating DNS A Record "asdf" (Zone "privatelink.web.core.windows.net" / Resource Group "rg-prd-uks-asdf-azure-dns"): dns.RecordSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'privatelink.web.core.windows.net' not found."
```

### Expected Behavior

Created an A record with the IP value

### Actual Behavior

Failed; can't find the DNS zone, but it does exist. Retried multiple times.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We need to create a specific private DNS zone centrally in our hub for all spokes to reference. The zone name is specific to the type of service endpoints used to connect, see https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns. 

I suspect it won't create this record because it is of a special type of DNS zone, however the zone is definitely there and I manually created the record myself, tested OK.

### References

* #0000

**Comment by neil-yechenwei** [comment]
@fluffy-cakes , thanks for opening this issue. I assume if you want to add dns record to private dns zone, you have to use `azurerm_private_dns_a_record`. Hopes it would be helpful.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-dnsrecord-test"
  location = "eastus2"
}

resource "azurerm_private_dns_zone" "test" {
    name                    = "privatelink.web.core.windows.net"
    resource_group_name     = azurerm_resource_group.test.name
}

resource "azurerm_private_dns_a_record" "test" {
  name                = "asdf"
  resource_group_name = azurerm_resource_group.test.name
  zone_name           = azurerm_private_dns_zone.test.name
  ttl                 = 300
  records             = ["1.2.3.4", "1.2.4.5"]
}
```

**Comment by fluffy-cakes** [comment]
👍 i guess that's my fault for not looking at the resources properly. sorry, and thanks. it works
