### ISSUE TITLE
Support for controlling the TLS version in a storage account. 

### ISSUE THREAD

**Issue by adamyager** [terraform-providers/terraform-provider-azurerm#7966]
today, there is no way to change or enforce the TLS version of a storage account in the Azure RM provider.
The default for a storage account is TLS 1.0
We really need a way to control this version. In our use case we will set it to 1.2, but other companies may want to be more selective on make it work based on thier needs.

So exposing someting like tls_version would be critical.

TLS 1.0 has known security issues and should not be the default in Azure, but that is a another story all together...
https://www.terraform.io/docs/providers/azurerm/r/storage_account.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://www.terraform.io/docs/providers/azurerm/r/storage_account.html

* #0000

**Comment by vaclav-dvorak** [comment]
Seems this is already addressed in this PR:
#7879

**Comment by giotab** [comment]
Duplicate of #7778
