### ISSUE TITLE
tmp assigned to random volume on Ubuntu 20.04

### ISSUE THREAD

**Issue by lubars** [terraform-providers/terraform-provider-azurerm#7974]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v2.21.0
+ provider.null v2.1.2

### Affected Resource(s)

* `azurerm_virtual_machine`
* `azurerm_managed_disk`

### Terraform Configuration Files

We have defined four azurerm_managed_disks (with unique name/id/lun) which we have in variable local.disks; in the azurerm_virtual_machine resource, we attach them in a loop:

```
  dynamic "storage_data_disk" {
    for_each = local.disks
    content {
      name            = storage_data_disk.value.source[count.index].name
      managed_disk_id = storage_data_disk.value.source[count.index].id
      disk_size_gb    = storage_data_disk.value.source[count.index].disk_size_gb
      lun             = storage_data_disk.value.lun
      create_option   = "attach"
    }
  }
```

### Expected Behavior
In Ubuntu 18.04, this always results in the following devices under /dev:

```
sda
sda1
sdb
sdb1
sdb14
sdb15
sdc
sdd
sde
sdf
```
sda is the OS volume, sdb is the tmp volume, and sdc/sdd/sde/sdf are the four data volumes.  Note that the OS volume gets partition "sda1", and the tmp volume gets partitions sdb1/sdb14/sdb15.  At this point we typically run "mkfs" on the data volumes and mount them.

### Actual Behavior
With Ubuntu 20.04, tmp is being assigned to a random volume; for example, on this run, /dev/sde became the tmp volume:

```
sda
sda1
sdb
sdc
sdd
sde
sde1
sde14
sde15
sdf
```

### Steps to Reproduce

This is an Ubuntu 18.04 image we have been using without issue:

```
  storage_image_reference {
    publisher = "Canonical",
    offer     = "UbuntuServer",
    sku       = "18.04-LTS",
    version   = "18.04.201909030"
  }
```

This is an Ubuntu 20.04 image that exhibits the issue:

```
  storage_image_reference {
    publisher = "Canonical",
    offer     = "0001-com-ubuntu-server-focal",
    sku       = "20_04-lts",
    version   = "20.04.202007080"
  }
```

### References

See Azure docs:

- [Your VM Temporary drive](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/optimization#your-vm-temporary-drive)
- [Temporary disk](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/managed-disks-overview#temporary-disk)

**Comment by ArcturusZhang** [comment]
hi @lubars Thanks for opening this issue.

I suppose this issue is not related with the provider but an issue with the Azure itself. Could you please contact the Azure support or open a thread in [one of the Community Resources](https://www.terraform.io/community.html)?

Thanks!

**Comment by lubars** [comment]
Hi @ArcturusZhang.  Given the number of open issues I have with Azure, I'd prefer to leave the issue open here in the hopes that it might reside within Terraform: Perhaps some kind of race condition allocating multiple volumes, or a new flag to the Azure API.  Thanks you -

**Comment by lubars** [comment]
Looking in `/dev/disk/azure/scsi1/` the mappings are apparent:

```
$ ls -l /dev/disk/azure/scsi1
total 0
lrwxrwxrwx 1 root root 12 Aug 14 15:29 lun1 -> ../../../sdb
lrwxrwxrwx 1 root root 12 Aug 14 15:30 lun2 -> ../../../sdd
lrwxrwxrwx 1 root root 12 Aug 14 15:30 lun3 -> ../../../sde
lrwxrwxrwx 1 root root 12 Aug 14 15:30 lun4 -> ../../../sdc
```

This suggests that attempts to predict device names (based on past behavior and guidance from Microsoft) should be abandoned, and straight LUN values used instead.

**Comment by tombuildsstuff** [comment]
👋 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
