### ISSUE TITLE
azurerm_management_lock: Unhelpful "NoRegisteredProviderFound" error message when lock name is invalid

### ISSUE THREAD

**Issue by pacon-vib** [terraform-providers/terraform-provider-azurerm#7982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.0-rc1
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0
```

### Affected Resource(s)

* `azurerm_management_lock`

### Terraform Configuration Files

My Terraform config deploys a resource lock for each of a set of resources, and I used the resource ID as the lock name because naming things is hard.

```hcl
resource "azurerm_management_lock" "shared_things" {
  for_each   = { for id in [
    azurerm_resource_group.module.id,
    azurerm_app_service_plan.module.id,
    azurerm_redis_cache.module.id,
    azurerm_key_vault.certs.id,
    module.mysql_server.server_id
  ] : id => id}
  name       = each.key
  scope      = each.value
  lock_level = "CanNotDelete"
}
```

### Expected Behavior

The config should be rejected as invalid because of the slashes in the lock name.

### Actual Behavior

```
Error: Error checking for presence of existing Management Lock "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Storage/sto
rageAccounts/REDACTED" (Scope "REDCTED"): locks.ManagementLocksClient#GetByScope: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'australiaeast' and API version '2016-09-01' for type 'storageAccounts'. The supported api-versions are '2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'eastus, eastus2, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, northeurope, brazilsouth, australiaeast, australiasoutheast, southindia, centralindia, westindia, canadaeast, canadacentral, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast'."

  on main.tf line 85, in resource "azurerm_management_lock" "shared_things":
  85: resource "azurerm_management_lock" "shared_things" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- I got my config working by using `regex()` to strip out the invalid characters from the lock name, just thought I should stick a ticket in here for any other poor soul googling "azurerm_management_lock NoRegisteredProviderFound" and getting zero results

### References

- https://docs.microsoft.com/en-us/rest/api/resources/managementlocks/createorupdateatresourcelevel (Azure API requires lock name to be appended to URL unencoded, which causes chaos if the lock name contains slashes)

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I can repro it. After investigated, I assume it's an API issue since api returned unexpected error message while creating/getting management lock in parallel. So I filed an issue on Azure/azure-rest-api-specs#10337.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here the `azurerm_management_lock` resource contains validation that the name isn't an empty string, as such whilst this is a bug in the Azure API I believe this should be being caught in Terraform and so I'm going to close this issue for the moment, however please let us know if you're still seeing this in the latest version of the Azure Provider and we'll take another look.

Thanks!
