### ISSUE TITLE
Error adding operation policy to versioned api

### ISSUE THREAD

**Issue by DigIntSys** [terraform-providers/terraform-provider-azurerm#7988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.12.23
* provider.azurerm v2.12.0

### Affected Resource(s)

* `azurerm_api_management_api_operation_policy`

### Terraform Configuration Files

resource "azurerm_api_management_api" "apiv1" {
     name                = "${var.apiName}-${local.apiV1Version}"
     resource_group_name = data.azurerm_resource_group.apimRg.name
     api_management_name = data.azurerm_api_management.apim.name
     revision            = var.apiRevision
     display_name        = "${var.apiDisplayName} ${local.apiV1Version}"
     version = "v1"
     version_set_id = azurerm_api_management_api_version_set.deviceDomainVS.id
}

resource "azurerm_api_management_api_version_set" "deviceDomainVS" {
     name                = "${var.apiName}-version-set"
     resource_group_name = data.azurerm_resource_group.apimRg.name
     api_management_name = data.azurerm_api_management.apim.name
     display_name        = var.apiDisplayName
     versioning_scheme   = "Segment"
}

resource "azurerm_api_management_api_operation_policy" "apiV1OperationsWithUserId" {
     for_each            = var.operationIdsWithUserId
     api_name            = azurerm_api_management_api.apiv1.name
     api_management_name = data.azurerm_api_management.apim.name
     resource_group_name = data.azurerm_resource_group.apimRg.name
     operation_id        = each.key

  xml_content =       `<<XML
      <policies>
         <inbound>
          <base />
         </inbound>
         <backend>
           <forward-request />
         </backend>
         <outbound>
           <base />
         </outbound>
         <on-error>
           <base />
         </on-error>
      </policies>
  XML
`
    depends_on = [azurerm_api_management_api.apiv1]
}

### Expected Behavior

Operation policies are added to the api

### Actual Behavior

Terraform command 'apply' failed with exit code '1'.:  creating or updating API Operation Policy : apimanagement.APIOperationPolicyClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="Entity with specified identifier not found"

### Steps to Reproduce

1. create azurerm_api_management_api_version_set resource
2. create azurerm_api_management_api resource with version_set_id matching the version_set id
3. create azurerm_api_management_api_operation_policy resource

* #0000

**Comment by yupwei68** [comment]
Hi @DigIntSys , thanks for opening this issue. Would you mind trying Azurerm 2.18.0? I have merged a PR to fix raw-xml related issue in `azurerm_api_management_api_operation_policy` and it has been released in 2.18.0. Please refer to https://github.com/terraform-providers/terraform-provider-azurerm/pull/7639.
If the error continues to run out, please provide a more detailed `azurerm_api_management_api_operation_policy` with a more specific `xml_content` to help to reproduce this error.

**Comment by DigIntSys** [comment]
Hi @yupwei68 . I have upgraded to 2.18 and retried but i got the same error. 

I don't think this is related to xml_content. I was running the exact same azurerm_api_management_api_operation_policy resource fine before i added the api to a version set. 

The error says 
Status=400 Code="ValidationError" Message="Entity with specified identifier not found". 
To me it seems that the api identifier has changed and cannot be found when the api is applied to a version set.

In any case, i've added a basic policy to the example. Is there any way I can provide more information regarding this?

**Comment by DigIntSys** [comment]
Hi again. I've tried applying the policy to the api level using azurerm_api_management_api_policy resource and it works fine. I cannot use this resource though because i need to apply operation specific policies.

Whatever is going wrong seems to be related to the azurerm_api_management_api_operation_policy resource.

**Comment by yupwei68** [comment]
Hi @DigIntSys I have tried your provided code with Azurerm  v2.21.0. And it was applied successfully. Sorry that I could not reproduce your error. Please try a later release. And if the error still runs out, please provide the configuration of `azurerm_api_management`, and `azurerm_api_management_api_operation`.

**Comment by DigIntSys** [comment]
hi @yupwei68 . i have figured out the problem. it was not related to the resource. i was attempting to apply policies on the operations of the v2 version of the api which did not exist. the error was clear. when it attempted to apply the policy it could not find the operation.

Thank you for your help. it helped isolate the cause. I will close this for now. keep it up!
