### ISSUE TITLE
Support for dnsPrefix property in App Service Environment

### ISSUE THREAD

**Issue by jonathaneckman** [terraform-providers/terraform-provider-azurerm#7989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Our resource naming convention is complex. The ASE resource currently uses the same value for the DNS sufix of the ASE name. We would like to see these individually. This is possible through ARM. 

### New or Affected Resource(s)

azurerm_app_service_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_environment" "ase" {
  name = "ABC-DEF-GHI-ASE-01"
  internal_load_balancing_mode = "Web, Publishing"
  resource_group_name = azurerm_resource_group.app.name
  dns_sufix = myapp  # NEW
}
```

### References

See [this example](https://github.com/Azure/azure-quickstart-templates/blob/85918fcc72a1bb947747c7a88f96bdaf174ff8f1/201-web-app-asev2-ilb-create/azuredeploy.json#L66).

**Comment by LaurentLesle** [comment]
the link you reference is for dns_suffix.

**Comment by jonathaneckman** [comment]
My mistake. I corrected the request. Our team no longer needs this because we were able to configure a custom domain on the app service and get what we needed from the ASE DNS suffix.
