### ISSUE TITLE
Terraform PLAN show state change without code change

### ISSUE THREAD

**Issue by fernandomatsuosantos** [terraform-providers/terraform-provider-azurerm#7992]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
- terraform: 0.12.29
- azurerm: 2.16.0

### Affected Resource(s)

* `azurerm_postgresql_server`

```hcl
resource "azurerm_postgresql_server" "postgresql_server" {
  name                = "example-psqlserver"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  administrator_login          = "psqladminun"
  administrator_login_password = "H@Sh1CoR3!"

  sku_name   = "GP_Gen5_4"
  version    = "11"
  storage_mb = "5120"

  backup_retention_days        = 7
  geo_redundant_backup_enabled = true
  auto_grow_enabled            = true

  infrastructure_encryption_enabled = true
  public_network_access_enabled     = true
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"

  threat_detection_policy {
      enabled = false
  }
}
```

### Expected Behavior
The first time you run an APPLY the database will be deployed... 
After that a PLAN should not output a change to threat_detection_policy = false since threat_detection_policy is already false

### Actual Behavior

After the APPLY a new PLAN with no code changes tries to update threat_detection_policy = false

### Steps to Reproduce

1. RUN an APPLY to create the database
2. RUN a PLAN after database has been created and it will show a change to threat_detection_policy - false
 (even if you do not make any change in the code)

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` (after apply finishes)

### References

* #0000

**Comment by Dmitry1987** [comment]
Don't know if to open a new bug or add to the above, but in my case this resource also shows more diff for no reason, in the `threat_detection_policy`. 
My manifest is:
```
  threat_detection_policy {
    email_account_admins = false
    email_addresses      = [
        "email@mydomain.com",
      ]
    enabled              = true
    retention_days       = 30
  }
```
and any time the plan and apply runs it makes the following diff:
```
      ~ threat_detection_policy {
          ~ disabled_alerts      = [
              - "",
            ]
            email_account_admins = false
            email_addresses      = [
                "email@mydomain.com",
            ]
            enabled              = true
            retention_days       = 30
        }
```

So it sticks this one in, for no reason. Should be ignored 'as is' IMHO, when not specified. A minor bug but is annoying. 
```
          ~ disabled_alerts      = [
              - "",
            ]
```
