### ISSUE TITLE
Unable to reference data block for azurerm_private_dns_zone: "Parent resource '...' not found"

### ISSUE THREAD

**Issue by fcatacut** [terraform-providers/terraform-provider-azurerm#7993]
I'm trying to use a data-block to retrieve an existing Private DNS zone so that it can be referenced when creating additional resources, such as `azurerm_private_dns_zone_virtual_network_link` and `azurerm_private_dns_a_record`.

### Community Note

* Please vote on this issue by adding a 👍  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
+ provider.azurerm v2.21.0

### Affected Resource(s)

* `azurerm_private_dns_zone`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_private_dns_zone" "example" {
  name                = "privatelink.documents.azure.com"
  resource_group_name = "<change me>"
}

resource "azurerm_resource_group" "example" {
  name     = "myrg"
  location = "eastus"
}

resource "azurerm_virtual_network" "example" {
  name                = "myvnet"
  resource_group_name = azurerm_resource_group.example.name
  location            = "eastus"
  address_space       = ["10.0.0.0/20"]
}

resource "azurerm_private_dns_zone_virtual_network_link" "example" {
  name                  = "myvnetlink"
  resource_group_name   = azurerm_resource_group.example.name
  private_dns_zone_name = data.azurerm_private_dns_zone.example.name
  virtual_network_id    = azurerm_virtual_network.example.id
}

output "data_private_dns_zone" {
  value = data.azurerm_private_dns_zone.example
}
```

### Debug Output

<https://gist.github.com/fcatacut/59b3005ef022f629502d8f6d6cc4ce41>

### Expected Behavior

`azurerm_private_dns_zone_virtual_network_link` should be successfully created.

### Actual Behavior

```bash
Error: error creating/updating Private DNS Zone Virtual network link "myvnetlink" (Resource Group "myrg"): privatedns.VirtualNetworkLinksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'privatelink.documents.azure.com' not found."

  on main.tf line 22, in resource "azurerm_private_dns_zone_virtual_network_link" "example":
  22: resource "azurerm_private_dns_zone_virtual_network_link" "example" {
```

### Steps to Reproduce

1. Create a Private DNS zone. For the sample code, `privatelink.documents.azure.com` is used.
2. Update the 2 `<change me>` references to the Name of the Resource Group containing the Private DNS zone.
3. `terraform apply`

### Important Factoids

Commenting out the `azurerm_private_dns_zone_virtual_network_link` resource block yields the expected output:

```bash
Outputs:

data_private_dns_zone = {
  "id" = "/subscriptions/.../resourceGroups/.../providers/Microsoft.Network/privateDnsZones/..."
  "max_number_of_record_sets" = 25000
  "max_number_of_virtual_network_links" = 1000
  "max_number_of_virtual_network_links_with_registration" = 100
  "name" = "privatelink.documents.azure.com"
  "number_of_record_sets" = 3
  "resource_group_name" = "<change me>"
  "tags" = {}
}
```

**Comment by neil-yechenwei** [comment]
@fcatacut, thanks for opening this issue. After investigated, I found you are using incorrect resource group name while creating private dns zone virtual network link. You have to use the resource group where the Private DNS Zone exists. I assume it's a document issue. So I made a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7998) for it.

Sample code:
```
resource "azurerm_private_dns_zone_virtual_network_link" "example" {
  ....
  resource_group_name   = <The resource group where the Private DNS Zone exists>
  ....
}
```

**Comment by fcatacut** [comment]
> I suspect you are using incorrect resource group name while creating private dns zone virtual network link.

As noted in Step 2 of the "Steps to Reproduce" section, `<change me>` should be changed to the resource group name where the Private DNS Zone was created.  I verified that I was referencing the correct resource group name by commenting out the `azurerm_private_dns_zone_virtual_network_link` resource block which results in the output that contains the attributes retrieved by the data block used to retrieve the Private DNS Zone.

**Comment by neil-yechenwei** [comment]
@fcatacut, could you have a try below my tfconfig which is similar with yours to check whether the issue still exists since I cannot repro this issue with below tfconfig? Thanks.

First apply:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "dnszone-test01"
  location = "eastus"
}

resource "azurerm_private_dns_zone" "test" {
  name                = "privatelink.documents.azure.com"
  resource_group_name = azurerm_resource_group.test.name
}
```

Result:
```
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

Second apply:
```
provider "azurerm" {
  features {}
}

data "azurerm_private_dns_zone" "example" {
  name                = "privatelink.documents.azure.com"
  resource_group_name = "dnszone-test01"
}

resource "azurerm_resource_group" "example" {
  name     = "dnszone-test02"
  location = "eastus"
}

resource "azurerm_virtual_network" "example" {
  name                = "myvnettest01"
  resource_group_name = azurerm_resource_group.example.name
  location            = "eastus"
  address_space       = ["10.0.0.0/20"]
}

resource "azurerm_private_dns_zone_virtual_network_link" "example" {
  name                  = "myvnetlinktest01"
  resource_group_name   = "dnszone-test01"
  private_dns_zone_name = data.azurerm_private_dns_zone.example.name
  virtual_network_id    = azurerm_virtual_network.example.id
}

output "data_private_dns_zone" {
  value = data.azurerm_private_dns_zone.example
}
```

Result:
```
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

data_private_dns_zone = {
  "id" = "/subscriptions/xx-xx-xx-xx/resourceGroups/dnszone-test01/providers/Microsoft.Network/privateDnsZones/privatelink.documents.azure.com"
  "max_number_of_record_sets" = 25000
  "max_number_of_virtual_network_links" = 1000
  "max_number_of_virtual_network_links_with_registration" = 100
  "name" = "privatelink.documents.azure.com"
  "number_of_record_sets" = 1
  "resource_group_name" = "dnszone-test01"
  "tags" = {}
}
```

**Comment by fcatacut** [comment]
For #2, replace the `azurerm_private_dns_zone_virtual_network_link` resource block with below so that the resource is in the same resource group as the VNet.

```
resource "azurerm_private_dns_zone_virtual_network_link" "example" {
  name                  = "myvnetlinktest01"
  resource_group_name   = "dnszone-test02"
  private_dns_zone_name = data.azurerm_private_dns_zone.example.name
  virtual_network_id    = azurerm_virtual_network.example.id
}
```

**Comment by fcatacut** [comment]
Sorry, long morning. I finally realized what you pointed out in your initial response.  The link has to be in the same resource group as the Private DNS Zone.

**Comment by neil-yechenwei** [comment]
Yes. That’s right. You got my point.
