### ISSUE TITLE
Unable to increase minimum node count while autoscaling is enabled

### ISSUE THREAD

**Issue by sbalinen** [terraform-providers/terraform-provider-azurerm#8007]
I am trying to increase both minimum node count as well as the existing node count in AKS Cluster but i am getting the below error when trying to apply terraform. Could this functionality be changed as there might be scenarios where we have to increase the node count even though auto scaling is enabled. Currently we can achieve it only by disabling Auto scaling then manually scale the nodes and enable back Auto scaling 

Error: cannot change node_count when enable_auto_scaling is set to true

**Comment by abelal83** [comment]
Similar issue

Error: expanding `default_node_pool`: `node_count`(2) must be equal to or greater than `min_count`(3) when `enable_auto_scaling` is set to `true`

So I change to satisfy then get this error
Error: expanding `default_node_pool`: cannot change `node_count` when `enable_auto_scaling` is set to `true`

Not sure how to go about changing this.

**Comment by tombuildsstuff** [comment]
hi @sbalinen 

Unfortunately this limitation comes from AKS itself, which doesn't allow changing the minimum node count without disabling/enabling auto-scaling - as such Terraform is just returning a more descriptive error here. I'd suggest [filing an issue on the AKS repository](https://github.com/Azure/AKS) - since once the AKS Service supports this we should be able to change this behaviour - but for the moment unfortunately this behaviour isn't supported by the Azure API (and thus isn't something we can change).

Thanks!

**Comment by PSanetra** [comment]
@tombuildsstuff there is already an issue in the AKS repository: https://github.com/Azure/AKS/issues/1758

It seems like this is already supported by the AKS api.

**Comment by marwanad** [comment]
@tombuildsstuff So there's two separate asks here from the AKS issue.

1) The ability to change minCount to a value that's greater than the current count. This is supported today by AKS API but it seems there's a check in TF that does requestedMinCount <= count <= maxCount today. Note, that this won't force AKS to scale up to the specified requestedMinCount but the scale down operators will respect this new minCount and the next scale up operation that requires delta(requestedMinCount - current) would respect that.


2) The ability to change the node count without disabling/enabling autoscaling. Today, this isn't supported and the provided count will be ignored by the APIs if autoscaling is on.

**Comment by sbalinen** [comment]
@tombuildsstuff  Could you please review above comments and provide an update.
