### ISSUE TITLE
Support for Getting Function App host keys

### ISSUE THREAD

**Issue by chaseWillden** [terraform-providers/terraform-provider-azurerm#8008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very nice to be able to get Function App host_keys as a data source.

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
data "azurerm_function_app" "example" {
  name                = "example-function"
  resource_group_name = "Example"
}

# Usage would be
data.azurerm_function_app.example.host_keys["default"]
```

### References

* #1493

**Comment by njuCZ** [comment]
duplicate as #699, and there is already a PR for it: https://github.com/terraform-providers/terraform-provider-azurerm/pull/7902

**Comment by mybayern1974** [comment]
hi  @chaseWillden, firstly thank you for opening this issue! Given assume this is a duplicate issue with #699, would you mind subscribing to #699 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!
