### ISSUE TITLE
Replace cycle for [azurerm_backup_protected_vm] when the backup item resource group name is uppercased from azure api

### ISSUE THREAD

**Issue by elongstreet88** [terraform-providers/terraform-provider-azurerm#8009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
provider.azurerm v2.21.0

### Affected Resource(s)

* azurerm_backup_protected_vm

### Terraform Configuration Files

```hcl
resource "azurerm_backup_protected_vm" "main" {
  count               = var.azure_vm_backups_enabled == true ? 1 : 0
  resource_group_name = var.stackSettings.azurerm_resource_group.name
  recovery_vault_name = var.stackSettings.azurerm_recovery_services_vault.name
  source_vm_id        = azurerm_virtual_machine.main.id
  backup_policy_id    = var.stackSettings.azurerm_backup_policy_vm.id
}
```

### Debug Output

```
 # module.core.module.server1.azurerm_backup_protected_vm.main[0] must be replaced
-/+ resource "azurerm_backup_protected_vm" "main" {
        backup_policy_id    = "/subscriptions/xxxxxxxxx-xxxx-xxxxxxx-xxxxxxxx/resourceGroups/abc123-rg/providers/Microsoft.RecoveryServices/vaults/abc123rv/backupPolicies/abc123-rp"
      ~ id                  = "/subscriptions/xxxxxxxxx-xxxx-xxxxxxx-xxxxxxxx/resourceGroups/abc123-rg/providers/Microsoft.RecoveryServices/vaults/abc123rv/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;abc123-rg;abc123-vm0f11/protectedItems/VM;iaasvmcontainerv2;abc123-rg;abc123-vm0f11" -> (known after apply)
        recovery_vault_name = "abc123rv"
        resource_group_name = "abc123-rg"
      ~ source_vm_id        = "/subscriptions/xxxxxxxxx-xxxx-xxxxxxx-xxxxxxxx/resourceGroups/ABC123-RG/providers/Microsoft.Compute/virtualMachines/abc123-vm0f11" -> "/subscriptions/xxxxxxxxx-xxxx-xxxxxxx-xxxxxxxx/resourceGroups/abc123-rg/providers/Microsoft.Compute/virtualMachines/abc123-vm0f11" # forces replacement
      - tags                = {} -> null
    }
```

### Expected Behavior

No changes

### Actual Behavior

Terraform sees the uppercase version of the resource group and tries to replace every apply

### Steps to Reproduce

I have 3 VMs in a build, 2 have the uppercase version pinned to the item, 1 is lower case.
I have been unable to reproduce this state, and even manually deleting/recreating the items in azure portal will not remove the uppercase versions. 

I have an active ticket with MS to figure out why this occurred.
They are stating the API may or may not return uppercase, so terraform may need to be adjusted for the condition where a backup source_vm_id may be uppercase in the API, but lowercase in the state.

**Comment by tombuildsstuff** [comment]
@ArcturusZhang is there a Rest API Specs bug open tracking this?

**Comment by elongstreet88** [comment]
We just had this similar thing happen for a disk import as well:
```HCL
  # module.core.module.server_sql.azurerm_managed_disk.main[4] must be replaced
-/+ resource "azurerm_managed_disk" "main" {
        create_option        = "Empty"
      ~ disk_iops_read_write = 500 -> (known after apply)
      ~ disk_mbps_read_write = 100 -> (known after apply)
        disk_size_gb         = 100
      ~ id                   = "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/DEF456-RG/providers/Microsoft.Compute/disks/vm0db9-datadisk-4" -> (known after apply)
        location             = "centralus"
        name                 = "def456-vm0db9-datadisk-4"
      ~ resource_group_name  = "DEF456-RG" -> "def456-rg" # forces replacement
      + source_uri           = (known after apply)
        storage_account_type = "Premium_LRS"
      - zones                = [] -> null

      - timeouts {}
    }
```

This disk was added through the portal by mistake, and we imported it.
After the import and attempting run an apply, it wants to replace it for a similar reason as the backup item.
It seems like items potentially updated/created through the portal are sometimes pinning the uppercase resource group name to the metadata/path and terraform imports it and expects it to be lowercase, however, it may not be.

**Comment by elongstreet88** [comment]
I was able to work around this by:

1. manually setting the resource group name reference to lowercase on the object
```powershell
get-azvm -Name abc123-vm0f11 -ResourceGroupName abc123-rg |Update-AzVM
```
2. Updating all references to the uppercase version in my terraform state file manually


After this, there were no changes detected in terraform.
I believe the underlying issue should still be addressed, whether in adding consistency to the azure api or having terraform/azure cli account for this possible discrepancy.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang is there a Rest API Specs bug open tracking this bug in the Azure API?

Opened https://github.com/Azure/azure-rest-api-specs/issues/10357 to track this issue from the upstream

**Comment by tombuildsstuff** [comment]
👋 

Since this needs to be fixed upstream within the Azure API - I'm going to close this in favour of [the upstream issue](https://github.com/Azure/azure-rest-api-specs/issues/10357) but once this is fixed there this will be fixed in Terraform - as such I'd recommend subscribing to the upstream issue here.

Thanks!
