### ISSUE TITLE
azurerm_app_service_certificate_order needs location global, but that's not in the approved list

### ISSUE THREAD

**Issue by drdamour** [terraform-providers/terraform-provider-azurerm#8034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

from pipeline so can't run -v but it's 12.29 with these plugins
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...
- Downloading plugin for provider "azuread" (hashicorp/azuread) 0.11.0...
- Downloading plugin for provider "azurerm" (hashicorp/azurerm) 2.21.0...

### Affected Resource(s)

* azurerm_app_service_certificate_order 

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_certificate_order" "ex" {
  name                = "ex"
  resource_group_name = module.certs.resource_group.name
  location            = "global"
  tags                = module.certs.resource_group.tags
  distinguished_name  = "CN=example.com"
  product_type        = "Standard"
  # doing 1 year because maybe managed certs will be out of preview soon and we can switch
  validity_in_years   = 1
  auto_renew          = true
}
```

### Expected Behavior

global is allowed

### Actual Behavior

global is NOT allowed with error 
Error: "global" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,indiasouth,indiawest,indiacentral,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast"

### Steps to Reproduce

1. `terraform apply`

### References

none

yes i can disable validation to work around, that is what i've done

**Comment by njuCZ** [comment]
@drdamour Thanks for opening this issue. Terraform introduces an environment variable `ARM_PROVIDER_ENHANCED_VALIDATION` for improving the location validation and default value is `true` since 2.20. For your case, if you want to use `global` location, please set this environment variable as `false` and try again, then it should pass. See more details from [changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#2200-july-23-2020).

**Comment by drdamour** [comment]
@njuCZ yeah which is exactly what i said im using last line of ticket
