### ISSUE TITLE
Support for Azure Netapp Files NFSv4.1 Kerberos Encryption Configuration

### ISSUE THREAD

**Issue by tbugfinder** [terraform-providers/terraform-provider-azurerm#8038]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ANF supports additional setups for kerberos encryption configuration of NFSv4.1 exports.
https://docs.microsoft.com/en-us/azure/azure-netapp-files/configure-kerberos-encryption

### New or Affected Resource(s)

* azurerm_netapp_volume

### Potential Terraform Configuration

```hcl
export_policy_rule {
  rule_index = 1
  protocols_enabled = ["Kerberos5p"]
  kerberos5_read_only = true
}
export_policy_rule {
  rule_index = 2
  protocols_enabled = ["Kerberos5i"]
  kerberos5_read_write = true
}
```

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, I found seems this feature hasn't been supported by [rest api](https://github.com/Azure/azure-rest-api-specs/blob/6ea6ec5c1685147b140f3991d1f7145d1ca124d2/specification/netapp/resource-manager/Microsoft.NetApp/stable/2020-02-01/netapp.json#L2240) since I cannot find any kerberos related property in it.

**Comment by tbugfinder** [comment]
Would I rather have to wait or would I have to create an issue there?

**Comment by neil-yechenwei** [comment]
Suggests to close this issue and file an issue on [rest api repo](https://github.com/Azure/azure-rest-api-specs/issues/new) for this feature request. Once the API is ready, you could reopen this issue.

**Comment by tbugfinder** [comment]
Thank you

#https://github.com/Azure/azure-rest-api-specs/issues/10461
