### ISSUE TITLE
Azure Terraform incompatible changes that lead to loadbalancer recreation in upgrade to v0.11.2

### ISSUE THREAD

**Issue by OlegGerber** [terraform-providers/terraform-provider-azurerm#804]
We upgrading the terraform for v0.10.6 to v0.11.2

As the result we got the mention below warnings and applied the required changes to align with the new format:

``
Warning: azurerm_lb_backend_address_pool.haproxy_backend_pool: "location": [DEPRECATED] location is no longer used
Warning: azurerm_lb_probe.appssh_probe: "location": [DEPRECATED] location is no longer used
Warning: azurerm_lb_probe.https_probe: "location": [DEPRECATED] location is no longer used
Warning: azurerm_lb_rule.haproxy_lb_appssh: "location": [DEPRECATED] location is no longer used
Warning: azurerm_lb_rule.haproxy_lb_https: "location": [DEPRECATED] location is no longer used
``

Unfortunately terraform plan shows that these changes cause to the LB component recreation and this brings downtime to any service that is fronted by it.

### Terraform 
v0.10.6 -> v0.11.2

### Affected Resource(s)
 azurerm_lb_backend_address_pool.haproxy_backend_pool: 
 azurerm_lb_probe.appssh_probe:
azurerm_lb_probe.https_probe: 
azurerm_lb_rule.haproxy_lb_appssh:
azurerm_lb_rule.haproxy_lb_https: 

### Expected Behavior
No changes

### Actual Behavior
Recreation of the component.
Plan: 5 to add, 5 to destroy.

As you can see terraform was unable to detrmine that the actual resources managed in the IaaS / state did not really change and requires actual recreation. 

this is very critical is to avoid the above downtime if possible as this brings downtime to any resource backed by the Azure LBs after applying steps fixing the TF deprecated syntax.

**Comment by katbyte** [comment]
Hi @OlegGerber,

Could I trouble you 2 things before we investigate this:
- the version of the provider you are using, this can be found by running `terraform -v`
- the actual plan showing the destroy/recreation

Thank you 🙂

**Comment by tombuildsstuff** [comment]
hi @OlegGerber 

Since we've not heard back from you here I'm going to close this issue for the moment. Please feel to reopen this with a Terraform Configuration that reproduces this issue and we'll take another look :)

Thanks!
