### ISSUE TITLE
Azure Application Gateway rules always marked for recreation

### ISSUE THREAD

**Issue by DAL3001** [terraform-providers/terraform-provider-azurerm#8043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
AzureRM Provider 2.19.0

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
  request_routing_rule {
    name                       = "rule-${var.gateway_backend_env}-public"
    rule_type                  = "basic"
    http_listener_name         = "lstn-${var.gateway_backend_env}-public"
    backend_address_pool_name  = "pool-${var.gateway_backend_env}-private"
    backend_http_settings_name = local.gateway_http_settings_name
  }
```

### Expected Behavior

Nothing -  when I run a `terraform plan` I wouldn't expect anything to change. The Application Gateway itself is created by referencing a module from the root module. Some of the values passed to the Application Gateway module are combined with some local values (as seen above) to construct the values for the routing rule. There are no changes to the root module or the child module containing the App Gateway config but the rule is always marked for deletion/creation, as below. 

### Actual Behavior

Rule configuration is marked for deletion/creation:

```
- request_routing_rule {
          - backend_address_pool_id    = "/subscriptions/xxxxxxxxxxxxxxx" -> null
          - backend_address_pool_name  = "pool-dev-private" -> null
          - backend_http_settings_id   = "/subscriptions/xxxxxxxxxxxxxxx" -> null
          - backend_http_settings_name = "http-settings-bff" -> null
          - http_listener_id           = "/subscriptions/xxxxxxxxxxxxxxx" -> null
          - http_listener_name         = "lstn-dev-public" -> null
          - id                         = "/subscriptions/xxxxxxxxxxxxxxx" -> null
          - name                       = "rule-dev-public" -> null
          - rule_type                  = "Basic" -> null
        }
      + request_routing_rule {
          + backend_address_pool_id    = (known after apply)
          + backend_address_pool_name  = "pool-dev-private"
          + backend_http_settings_id   = (known after apply)
          + backend_http_settings_name = "http-settings-bff"
          + http_listener_id           = (known after apply)
          + http_listener_name         = "lstn-dev-public"
          + id                         = (known after apply)
          + name                       = "rule-dev-public"
          + redirect_configuration_id  = (known after apply)
          + rewrite_rule_set_id        = (known after apply)
          + rule_type                  = "basic"
          + url_path_map_id            = (known after apply)
        }
```

### Steps to Reproduce

1. `terraform apply`

### References

I can see some other issues relating to similar issues around ordering etc... which are similar but not in any use cases as shown above. 

* #7870 
* #6896

I suspect maybe this is to do with constructing the values for the rule with a mixture of local values and variables provided to the module when called but I'm unsure? It could also be a quirk of Terraform that I'm not familiar with. I am constructing some other Application gateway configuration blocks in a similar fashion and not seeing the same behaviour. In practical terms it doesn't have much impact but clutters the plan and apply outputs when you're not expecting these changes. 

Thanks!

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems you configured rule_type with lower case letter. After investigated, I found seems TypeSet + suppress.CaseDifference doesn't take effect to ignore case. But I suppose it's expected since I assume terraform cannot compare the case difference for unordered collection. So I made a [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8043)for this issue and you also can use standard format such as "Basic" to configure rule_type.
