### ISSUE TITLE
docs: Add AzureKubernetesService in the list of supported FQDN tags for Azure Firewall app rule collection

### ISSUE THREAD

**Issue by mikemowgli** [terraform-providers/terraform-provider-azurerm#8047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_firewall_application_rule_collection`

### Important Factoids

I tested that the resource `azurerm_firewall_application_rule_collection` supports the FQDN tag `AzureKubernetesService` though not documented here: https://www.terraform.io/docs/providers/azurerm/r/firewall_application_rule_collection.html#fqdn_tags
Doc could be updated to match feature support.

### References

https://www.terraform.io/docs/providers/azurerm/r/firewall_application_rule_collection.html#fqdn_tags

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Hopes this [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8140)would be helpful.
