### ISSUE TITLE
threat_detection_policy is not working with azurerm_sql_server

### ISSUE THREAD

**Issue by AanchalKanodia** [terraform-providers/terraform-provider-azurerm#8050]
The following code is a part of a Terraform module that deploys a SQL server, SQL database and storage account for collecting threat detection logs. It does not give any errors but when I try to navigate to the console, I can't seem to find ATP enabled for the SQL database:

```
resource "azurerm_sql_database" "example" {
  name                = "sqltestabcd123"
  resource_group_name = azurerm_resource_group.example.name
  location            = var.location
  server_name         = azurerm_sql_server.example.name

  threat_detection_policy {
    state                      = "Enabled"
    retention_days             = 6
    email_addresses            = []
    storage_account_access_key = azurerm_storage_account.example.primary_access_key
    storage_endpoint           = azurerm_storage_account.example.primary_blob_endpoint
    use_server_default         = "Disabled"
  }
}

```
Has someone else faced this issue or knows what the problem is?

**Comment by yupwei68** [comment]
Hi @AanchalKanodia , thanks for opening this issue. Since I could not find the ATP setting in the database either, it created a `sqldbtdlogs` in the storage account. I have opened an issue https://github.com/Azure/azure-rest-api-specs/issues/10396 to get further information from service team.

**Comment by yupwei68** [comment]
Hi @AanchalKanodia , we have got reply from service team in the issue https://github.com/Azure/azure-rest-api-specs/issues/10396. Please refer to the reply image to find threat detection policy on portal.

**Comment by AanchalKanodia** [comment]
Thank you!

**Comment by yupwei68** [comment]
The service team replies:
> In order to see the setting for the TD policy, please click on the settings button.
> ![image](https://user-images.githubusercontent.com/56525716/90218440-64440100-de36-11ea-9336-a1f32b41d2f3.png)

Since this answers your question I am going to go ahead and close this issue, if you feel your question what not answered sufficiently please feel free to re-open this issue or open a new one, thanks again for opening this issue.
