### ISSUE TITLE
Documentation for cdn_endpoint is misleading

### ISSUE THREAD

**Issue by nmiodice** [terraform-providers/terraform-provider-azurerm#8054]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `cdn_endpoint`

### Terraform Configuration Files

```hcl
# https://www.terraform.io/docs/providers/azurerm/r/cdn_endpoint.html
resource "azurerm_cdn_endpoint" "endpoint" {
  name         = format("%s-endpoint", local.prefix)
  profile_name = azurerm_cdn_profile.profile.name

  # Locations like westus2 are not supported, but westus is. So we trim the number
  location            = replace(data.azurerm_resource_group.rg.location, "/\\d/", "")
  resource_group_name = data.azurerm_resource_group.rg.name
  is_http_allowed     = false

  origin {
    name      = "Storage Account Origin"
    host_name = azurerm_storage_account.sa.primary_blob_endpoint
  }

  # set a 15 minute expiration on the cache
  global_delivery_rule {
    cache_expiration_action {
      behavior = "Override"
      duration = "00:15:00"
    }
  }

  tags = local.tags
}
```

### Documentation issue

The documentation states that the `global_delivery_rule` and `delivery_rule` blocks live under `geo_filter`, but they are root-level configuration options for this resource.

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Steps to Reproduce

N/A

### References

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #8055
