### ISSUE TITLE
"global" is not a valid location when trying to create Bot Channels Registration

### ISSUE THREAD

**Issue by alexpls** [terraform-providers/terraform-provider-azurerm#8058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

**Terraform version**: 0.12.25
**AzureRM Provider version**: 2.20.0

### Affected Resource(s)

- `azurerm_bot_channels_registration`

### Terraform Configuration Files

```hcl
resource "azurerm_bot_channels_registration" "bot_registration" {
  name                = var.deployment_name
  location            = "global"
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "F0"
  microsoft_app_id    = azuread_application.app.application_id
}
```

### Expected Behavior

Resource is created in the `global` region.

### Actual Behavior

This error is thrown:

```
Error: "global" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,indiasouth,indiawest,indiacentral,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast"
```

### Steps to Reproduce

1. Declare a `azurerm_bot_channels_registration` resource with a `global` location.
1. `terraform plan`

### References

These issues appear to be related:

- https://github.com/terraform-providers/terraform-provider-azurerm/issues/8034
- https://github.com/terraform-providers/terraform-provider-azurerm/issues/7931

---

For now, I will try to work around this by setting [`AWS_PROVIDER_ENHANCED_VALIDATION`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#2200-july-23-2020) to `false`, however that does not seem like a good long term solution.

**Comment by tombuildsstuff** [comment]
Fixed via #8042
