### ISSUE TITLE
Split azurerm_app_service_custom_hostname_binding - allows breaking the circular dependency when using a azurerm_app_service_managed_certificate

### ISSUE THREAD

**Issue by AdamCoulterOz** [terraform-providers/terraform-provider-azurerm#8069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `azurerm_app_service_custom_hostname_binding` performs both the custom domain assignment and TLS certificate binding in the same step. This causes a managed certificate to have circular dependencies. As provisioning  `azurerm_app_service_managed_certificate` will require that first the custom hostname is validated, then you can provision the managed certificate, then you can bind the certificate to the hostname.

### New or Affected Resource(s)

Propose to create new resource `azurerm_app_service_custom_hostname_certificate_binding` which allows for the certificate binding part of `azurerm_app_service_custom_hostname` to be updated separately, to break the circular dependency.

`azurerm_app_service_custom_hostname` - continue to use the existing resource but set the `ssl_state` and `thumbprint` fields as ignored when using in conjunction with an `azurerm_app_service_managed_certificate`.

New:
`azurerm_app_service_custom_hostname_certificate_binding `
(copied mostly from existing resource, but just the cert binding part), use `certificate_id` instead of `thumbprint`, as the managed certificate thumbprint changes over time, as the cert is automatically rotated by azure app services.

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_custom_hostname_certificate_binding" "example" {
  hostname_binding_id = azurerm_app_service_custom_hostname.example.id
  certificate_id    = azurerm_app_service_managed_certificate.example.id
  ssl_state = "SniEnabled"
}
```

### References

Fixes #4824

**Comment by phekmat** [comment]
I think this would be useful for tighter ACME/Let's Encrypt integration as well, especially since changing the thumbprint on the hostname binding currently forces a new resource to be created. @AdamCoulterOz are you planning on opening a PR?

**Comment by AdamCoulterOz** [comment]
@phekmat I've not got time atm, otherwise I would... I've worked around it for now with an example implementation shown in #4824

**Comment by AdamCoulterOz** [comment]
@jackofallops - are you able to help us get this one done, as it will then solve the complete picture for #4824.
