### ISSUE TITLE
Support for base64 output in azurerm_key_vault_certificate

### ISSUE THREAD

**Issue by algattik** [terraform-providers/terraform-provider-azurerm#8072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

 azurerm_key_vault_certificate outputs certificate_data as a hex string, while azuread_service_principal_certificate requires base64 format.

### New or Affected Resource(s)

* `azuread_service_principal_certificate`
* `azurerm_key_vault_certificate`

### Potential Terraform Configuration

```hcl
resource "azuread_service_principal_certificate" "example" {
  service_principal_id = azuread_service_principal.example.id
  type                 = "AsymmetricX509Cert"
  value                = azurerm_key_vault_certificate.example.certificate_data # broken - is hex string, provider expects base64
  end_date             = azurerm_key_vault_certificate.example.certificate_attribute[0].expires
}

resource "azurerm_key_vault_certificate" "example" {
  name         = "generated-cert"
```

### References

Tested with:
```
Terraform v0.12.29
+ provider.azuread v0.11.0
+ provider.azurerm v2.22.0
```

**Comment by CaptainStealthy** [comment]
Just in case anyone comes across this thread, I did actually find a temporary workaround, which I've posted about in another issue: https://github.com/hashicorp/terraform-provider-azuread/issues/385

**Comment by hazzik** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/8482#issuecomment-712645111

@tombuildsstuff 

> As @vidarw has mentioned this is an unfortunate oversight on our part - this likely needs to be introduced as a new field, deprecating the existing field (to ultimately be removed in 3.0), rather than breaking the behaviour of the existing field. 

As the existing field is completely useless now, I believe, it should be fine to fix it in place.
