### ISSUE TITLE
ability to tag OS disk in azurerm_virtual_machine

### ISSUE THREAD

**Issue by kasenna** [terraform-providers/terraform-provider-azurerm#8086]
Hi all,

Issue: it is not possible to provide tags for OS disk in `azurerm_virtual_machine` resource, `storage_os_disk` block does not have such support.

How i see this new feature:
```hcl
resource "azurerm_virtual_machine" "XXX" {
  storage_os_disk {
    tags = {
       ...
      }
    }
  }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @kasenna 

Thanks for opening this issue.

At this point in time the `azurerm_virtual_machine` resource [has been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#disclaimers) - and as such we're no longer adding new features or functionality to this resource - and as such whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment.

If you're looking for this functionality to be supported on the newer `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources then would you mind opening a new issue containing more information with the specific use-cases you're looking to solve here?

Thanks!
