### ISSUE TITLE
azurerm_container_group does not store empty secrets in state, resulting in unnecessary recreations of resource

### ISSUE THREAD

**Issue by jeromewaibel** [terraform-providers/terraform-provider-azurerm#8096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.29
+ provider.azurerm v2.22.0
```
Also tried terraform v0.13.0, same results.

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  tenant_id = "..."
  subscription_id = "..."
  version = "=2.22.0"
  features {}
} 

resource "azurerm_resource_group" "example" {
  name     = "jerome-test"
  location = "westeurope"
}

resource "azurerm_container_group" "example" {
  name                = "example-continst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  ip_address_type     = "public"
  dns_name_label      = "jerome-aci-label"
  os_type             = "Linux"

  container {
  
    name   = "hello-world"
    image  = "microsoft/aci-helloworld:latest"
    cpu    = "0.5"
    memory = "1.5"

    ports {
    port     = 8000
    protocol = "TCP"
    }
    
    secure_environment_variables = {
      PRIVATE_EMPTY = ""
      PRIVATE_VALUE = "test"
    }
    environment_variables = {
      PUBLIC_EMPTY = ""
      PUBLIC_VALUE = "test"
    }
  }
}
```

### Expected Behavior

The container group should only be created once. A second terraform apply should not see any changes that force a recreation of the resource.

### Actual Behavior

Every call of terraform apply claims there is a change in the containers secure_environment_variables, which forces a complete destroy and replacement of the container group.

When checking the terraform.tfstate you can see that the empty secret is missing in the state, whereas the empty non-secret is stored. The missing secret variable will make terraform think there has been a change.

```
"container": [
                "environment_variables" : {
                  "PUBLIC_EMPTY": "",
                  "PUBLIC_VALUE": "test"
                },
                "secure_environment_variables" : {
                  "PRIVATE_VALUE": "test"
                },
( ... )
            ],

```
### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`again

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, I found [d.GetOk(fmt.Sprintf("container.%d.secure_environment_variables.%s", oldContainerIndex, *envVar.Name))](https://github.com/terraform-providers/terraform-provider-azurerm/blob/a719cb5f91144a17408d27e0a7292a371ad059b9/azurerm/internal/services/containers/container_group_resource.go#L1155) would return "false", which means terraform doesn't find the value of "PRIVATE_EMPTY" property when the value of PRIVATE_EMPTY property is set as "" in tfconfig. So empty string value of PRIVATE_EMPTY isn't set in the tfstate file for  = "". I assume the root cause is that d.GetOk() doesn't distinguish between `nil` and `""`.
