### ISSUE TITLE
Terraform[azurerm_subnet] fails when using var.address_prefixes[count.index]

### ISSUE THREAD

**Issue by tracphil** [terraform-providers/terraform-provider-azurerm#8101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0
```

### Affected Resource(s)

* `azurerm_subnet`

#### Works

```hcl
resource azurerm_subnet subnet {
  count = length(var.address_prefix)

  address_prefix       = var.address_prefix[count.index]
  name                 = "snet-${module.azurerm_subnet_label.id}-${format("%02d", count.index + 1)}"
  resource_group_name  = var.resource_group_name
  virtual_network_name = var.virtual_network_name
}
```

#### Does not work

```hcl
resource azurerm_subnet subnet {
  count = length(var.address_prefixes)

  address_prefixes     = var.address_prefixes[count.index]
  name                 = "snet-${module.azurerm_subnet_label.id}-${format("%02d", count.index + 1)}"
  resource_group_name  = var.resource_group_name
  virtual_network_name = var.virtual_network_name
}
```
Variable in question:

```
variable address_prefixes {
  description = "CIDRs for Virtual Networks."
  type        = list(string)
}
```

### Debug Output

https://gist.github.com/tracphil/830ce2ce425f4eb081a28fa313631480

### Expected Behavior

`terraform apply` should have completed without error

### Actual Behavior

```
Error: Incorrect attribute value type

  on ../../modules/terraform-azurerm-subnet/main.tf line 17, in resource "azurerm_subnet" "subnet":
  17:   address_prefixes     = var.address_prefixes[count.index]

Inappropriate value for attribute "address_prefixes": list of string required.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @tracphil 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by tracphil** [comment]
@tombuildsstuff It seems as though it is a bug since it worked before the provider changed `address_prefix` in favor of `address_prefixes`. By closing the issue, are you implying that it is not a bug?
