### ISSUE TITLE
Potentially incorrect data source

### ISSUE THREAD

**Issue by jonasthehobbit** [terraform-providers/terraform-provider-azurerm#8102]
https://github.com/terraform-providers/terraform-provider-azurerm/blob/ebe16117488cd91ba6426000df8c6ff0a335589d/examples/app-service/backup/main.tf#L35

Terraform plan and apply both ran without errors but there looks to be an issue with the deployed backup URI, I can only seem to get the backups to run successfully when switching to:

`data "azurerm_storage_account_blob_container_sas" "test" { `

Does this example need updating?

**Comment by neil-yechenwei** [comment]
@jonasthehobbit, sorry. I am confused. Do you mean azurerm_storage_account_sas doesn't output some property but azurerm_storage_account_blob_container_sas outputs it? May I ask which property does azurerm_storage_account_blob_container_sas output but azurerm_storage_account_sas doesn't output?

**Comment by neil-yechenwei** [comment]
After tested with this example, seems it works fine. Below is the output of the example.
```
C:\Personal\terraform\projects\terraform-provider-azurerm\examples\app-service\backup>terraform apply --auto-approve
var.location
  The Azure location where all resources in this example should be created
  Enter a value: eastus2
var.prefix
  The prefix used for all resources in this example
  Enter a value: neiltest
azurerm_resource_group.test: Creation complete after 3s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/neiltest-resources]
azurerm_app_service_plan.test: Creation complete after 17s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/neiltest-resources/providers/Microsoft.Web/serverfarms/neiltest-splan]
azurerm_storage_account.test: Creation complete after 37s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/neiltest-resources/providers/Microsoft.Storage/storageAccounts/neiltestsa]
azurerm_storage_container.test: Creation complete after 2s [id=https://neiltestsa.blob.core.windows.net/neiltest-sc]
azurerm_app_service.test: Creation complete after 1m7s [id=/subscriptions/xx-xx-xx-xx/resourceGroups/neiltest-resources/providers/Microsoft.Web/sites/neiltest-appservice]
Apply complete! Resources: 5 added, 0 changed, 0 destroyed.
Outputs:
app_service_default_hostname = https://neiltest-appservice.azurewebsites.net
app_service_name = neiltest-appservice
```

**Comment by katbyte** [comment]
@jonasthehobbit - given the example works just fine and no further detail was provider, i'm going to close this issue. Please do reopen it if we are missing anything.

**Comment by jonasthehobbit** [comment]
Apologies, I have been away on holiday. You are correct the Terraform apply runs without errors, however, the deployed resources do not function as they should.

If you deploy the original tf then check your backup status on the App service they will all be marked as failed.

If you change the data source to `azurerm_storage_account_blob_container_sas` then the backups run successfully.
