### ISSUE TITLE
Threat_detection_policy azurerm_mysql_server cannot find storage endpoint

### ISSUE THREAD

**Issue by jmeadowcroft** [terraform-providers/terraform-provider-azurerm#8107]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Terraform (and AzureRM Provider) Version**
AzureRM: 2.22
Terraform: v0.12.29

**Affected Resource**
azurerm_mysql_server 
Specifically with the threat_detection_policy block, when the storage endpoint is configured an unexpected error occurs

**Terraform Configuration Files**
resource "azurerm_mysql_server" "mysql" {
name                                               = "azmsql${var.location_code}${var.mysqlname}${var.resource_count}"
location                                           = var.location
resource_group_name                    = var.resource_group_name
sku_name                                        = var.sku_name
administrator_login                        = var.administrator_login
administrator_login_password       = random_password.admin_password.result
version                                            = "8.0"
ssl_enforcement_enabled               = true
infrastructure_encryption_enabled = true
auto_grow_enabled                        = true
storage_mb                                     = 5120
backup_retention_days                   = 7
geo_redundant_backup_enabled    = false

threat_detection_policy {
enabled                                 = true
email_account_admins          = true
email_addresses                    = [var.threat_protection_email]
retention_days                       = 7
storage_account_access_key = var.storage_account_access_key
storage_endpoint                  = data.azurerm_storage_account.sta.primary_blob_endpoint
}
}

**Debug Output**
https://gist.github.com/jmeadowcroft/7944fdcab9870b2eacbc5d0113913a40

**Expected Behavior**
Deploy with expected configuration

**Actual Behavior**

 Error: error waiting for creation/update of mysql server security alert policy (server "azmsqlwu2db4001", resource group "Test01"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '0e302d66-3ff7-49ff-b35a-806afe701423'"

on ....\mysql\mysql.tf line 10, in resource "azurerm_mysql_server" "mysql":
10: resource "azurerm_mysql_server" "mysql"

**Steps to Reproduce**

1. `terraform apply`

**Comment by yupwei68** [comment]
Hi @jmeadowcroft , thanks for opening this issue. Since I could create a `azurerm_mysql_server` with `threat_detection_policy` to a storage account with success, would you mind providing the configuration of your storage account? Is your storage account behind firewall or in a virtual network?

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment, but if this is still an issue and your able to provide the information we need to take another look into this then please let us know and we'll take another look.

Thanks!
