### ISSUE TITLE
Support for tags within resource azurerm_hpc_cache

### ISSUE THREAD

**Issue by tbugfinder** [terraform-providers/terraform-provider-azurerm#8117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please also expose tags of resource `azurerm_hpc_cache`.
### New or Affected Resource(s)

* azurerm_hpc_cache

### Potential Terraform Configuration

```hcl
tags = {}
```

**Comment by lrxtom2** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/10931

**Comment by ArcturusZhang** [comment]
There is a [swagger issue](https://github.com/Azure/azure-rest-api-specs/issues/10931), therefore we could not start the implementation of tags until this upstream issue is resolved.
