### ISSUE TITLE
Support for Application Health Extension for azurerm_windows_virtual_machine_scale_set/azurerm_linux_virtual_machine_scale_set for automatic and rolling updates

### ISSUE THREAD

**Issue by rhys96** [terraform-providers/terraform-provider-azurerm#8120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using ARM templates it is possible to create an automatic or rolling update scale set without using a load balancer probe. Instead, ARM templates create an Application Health Extension.  This type of implementation is useful for situations where the load balancing is done external to Azure services, requiring each VM to have a unique network address to the external component.

### New or Affected Resource(s)
- azurerm_windows_virtual_machine_scale_set
- azurerm_linux_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_virtual_machine_scale_set" "example" {
  name                = "example-vmss"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "Standard_F2"
  instances           = 1
  admin_password      = "P@55w0rd1234!"
  admin_username      = "adminuser"

  enable_automatic_updates = true
  upgrade_mode  = "Rolling"

  rolling_upgrade_policy {
    max_batch_instance_percent              = 20
    max_unhealthy_instance_percent          = 20
    max_unhealthy_upgraded_instance_percent = 5
    pause_time_between_batches              = "PT300S"
  }

  application_health_extension {
      protocol: "https"
      port: 443
      request_path: "/"
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter-Server-Core"
    version   = "latest"
  }

  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadWrite"
  }

  network_interface {
    name    = "example"
    primary = true

    ip_configuration {
      name      = "internal"
      primary   = true
      subnet_id = azurerm_subnet.internal.id
    }
  }
}
```

### References

- [Application Health Extension](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension)
- [Microsoft.Compute virtualMachineScaleSets template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-07-01/virtualmachinescalesets)
- [azurerm_windows_virtual_machine_scale_set](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine_scale_set.html)
- [azurerm_linux_virtual_machine_scale_set](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html)

**Comment by ArcturusZhang** [comment]
Hi @rhys96 thanks for this issue!

I believe this issue is related with https://github.com/terraform-providers/terraform-provider-azurerm/issues/5976, but not exactly a duplicate. This could only be resolved when we introduce the inline extension back, but this is not enough, since in your case, you would also require the `upgrade_mode` could be `Rolling` without a `health_probe_id` assigned.

**Comment by rhys96** [comment]
@ArcturusZhang Thanks for your reply. I agree, the ```health_probe_id``` is the differentiator in this scenario. Hence, why a separate resource attribute might need to be added to allow the appropriate logic to be configured. 

I'll track #5976 for the inline extension support. This support will be fantastic when it is implemented, it will avoid the scale set having to update again for the VM extensions.

**Comment by krarey** [comment]
I'm running into this issue as well. While #5976 has added the inline extension blocks, parsing the `settings` attribute seems to fail during apply.

Deploying an azurerm_linux_virtual_machine_scale_set resource with `ARM_PROVIDER_VMSS_EXTENSIONS_BETA=true`, using the following code:
```
resource "azurerm_linux_virtual_machine_scale_set" "consul_cluster" {
[...]
  extension {
    name                       = "ConsulHealthExtension"
    publisher                  = "Microsoft.ManagedServices"
    type                       = "ApplicationHealthLinux"
    type_handler_version       = "1.0"
    auto_upgrade_minor_version = false

    settings = jsonencode({
      protocol    = "http"
      port        = var.consul_health_port,
      requestPath = "health"
    })
  
  }
```
results in ``Error: failed to parse JSON from `settings`: unexpected end of JSON input``. 

Similarly, using an already JSON-formatted template string returns the same error:
```
  extension {
    name                       = "ConsulHealthExtension"
    publisher                  = "Microsoft.ManagedServices"
    type                       = "ApplicationHealthLinux"
    type_handler_version       = "1.0"
    auto_upgrade_minor_version = false

    settings = <<-EOT
    {
      "protocol": "http",
      "port": ${var.consul_health_port},
      "requestPath": "health"
    }
    EOT
  }
```

**Comment by krarey** [comment]
This seems to effect all VM extensions on the VM Scale Set resources, even when using the default/empty `settings` attribute. For example:

```
resource "azurerm_linux_virtual_machine_scale_set" "consul_cluster" {
[...]
  extension {
    name                       = "AADLoginForLinux"
    publisher                  = "Microsoft.Azure.ActiveDirectory.LinuxSSH"
    type                       = "AADLoginForLinux"
    type_handler_version       = "1.0"
    auto_upgrade_minor_version = true
  }
}
```

```
Error: failed to parse JSON from `settings`: unexpected end of JSON input

  on consul-cluster.tf line 53, in resource "azurerm_linux_virtual_machine_scale_set" "consul_cluster":
  53: resource "azurerm_linux_virtual_machine_scale_set" "consul_cluster" {
```

**Comment by ArcturusZhang** [comment]
Hi @krarey the JSON parsing issue should have been fixed by this PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/8222

**Comment by patademahesh** [comment]
We are getting the below error at the time of VMSS creation and deletion as well. Please suggest any quick fix.

`Error: Error creating Linux Virtual Machine Scale Set "production-cms-vmss" (Resource Group "production-centralindia-resource-group"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Automatic repairs not supported for this Virtual Machine Scale Set because a health probe or health extension was not provided."`


**automatic_instance_repair** is set to true
**azurerm_virtual_machine_scale_set_extension** is set as below. 

> **Note:** we have tried with extension as block in azurerm_linux_virtual_machine_scale_set resource as well

```
+ resource "azurerm_virtual_machine_scale_set_extension" "vmss_extension" {
      + auto_upgrade_minor_version   = true
      + id                           = (known after apply)
      + name                         = "production-southindia-cms-vmss-extension"
      + publisher                    = "Microsoft.ManagedServices"
      + settings                     = jsonencode(
            {
              + port        = 80
              + protocol    = "http"
              + requestPath = "/robots.txt"
            }
        )
      + type                         = "ApplicationHealthLinux"
      + type_handler_version         = "1.0"
      + virtual_machine_scale_set_id = "XXXXXXX"
    }
```

**Comment by marcelkmfst** [comment]
Gent´s is there any update on this?
