### ISSUE TITLE
Linux consumption plan apps created using terraform return 500 because of WEBSITE_CONTENT* settings

### ISSUE THREAD

**Issue by ritugoyal12** [terraform-providers/terraform-provider-azurerm#8130]
link issue : https://github.com/terraform-providers/terraform-provider-azurerm/issues/5209

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.26
azurerm_v2.22.0

### Affected Resource(s)
azurerm_function_app

### Terraform Configuration Files
```
resource "azurerm_app_service_plan" "service_plan" {
  name                = "xx"
  location            = "xx"
  resource_group_name = "xx"
  kind                = "FunctionApp"
  reserved            = true
  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "function" {
  name                       = "test-function"
  location                   = "East US"
  resource_group_name        = "function-test"
  app_service_plan_id        = azurerm_app_service_plan.service_plan.id
  version                    = "2"
  storage_account_name       = "xxx"
  storage_account_access_key = "xxx"

  app_settings = {
    FUNCTIONS_EXTENSION_VERSION = "2"
    FUNCTIONS_WORKER_RUNTIME    = "python"
  }
  identity {
    type = "SystemAssigned"
  }

}
```
### Expected Behavior
Function_app  is created successfully with no error code

### Actual Behavior
Terraform failed with following error: 
Error updating Application Settings for Function App “xx”: web.AppsClient#UpdateApplicationSettings: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="Unknown" Message="Unknown service error" Details=[{"Code":"InternalServerError","Details":[{"Message":null},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":null}}],"Innererror":null,"Message":null,"Target":null}]

The function_app is created but with incomplete application configuration settings. The `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and `WEBSITE_CONTENTSHARE` settings  are added by default.  Even, after  WEBSITE_CONTENTSHARE and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING settings are manually removed from Linux Consumption plan app, function still couldn't get its python requirements installed from requirements.txt.
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

As per the below links, it seems the issue was resolved in azure provider version 2.14, but it is still not working. 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/5209
https://github.com/terraform-providers/terraform-provider-azurerm/pull/7230

**Comment by njuCZ** [comment]
@ritugoyal12 could you please try following TF config, I have tested in my local successfully and there is no diff
```
resource "azurerm_storage_account" "test" {
  name                     = "xxxxx"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "test" {
  name                = "xxxxx"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  kind                = "FunctionApp"
  reserved            = true
  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "test" {
  name                       = "xxxxxx"
  location                   = azurerm_resource_group.test.location
  resource_group_name        = azurerm_resource_group.test.name
  app_service_plan_id        = azurerm_app_service_plan.test.id
  storage_account_name       = azurerm_storage_account.test.name
  storage_account_access_key = azurerm_storage_account.test.primary_access_key
  os_type = "linux"
  version = "~2"
  app_settings = {
    FUNCTIONS_WORKER_RUNTIME    = "python"
  }

  identity {
    type = "SystemAssigned"
  }
}
```
