### ISSUE TITLE
Can't create virtual network gateway - expected SKU to be one of [Basic]

### ISSUE THREAD

**Issue by DatYannou** [terraform-providers/terraform-provider-azurerm#8132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.23.0

### Affected Resource(s)

* `azurerm_virtual_network_gateway`

### Terraform Configuration Files

Variables are : 
```
variable "env" {
  default = "test"
}

variable "rg-name" {
  default = "rg-test"
}

variable "location" {
  default = "West Europe"
}
```

The components are : 
```
resource "azurerm_resource_group" "rg" {
  name = var.rg-name
  location = var.location
}

resource "azurerm_virtual_network" "vnet" {
  name = "virtual-network"
  location = var.location
  resource_group_name = var.rg-name
  address_space = ["10.0.0.0/20"]

  depends_on = [azurerm_resource_group.rg]
}

resource "azurerm_subnet" "vnet-gateway-subnet" {
  name = "GatewaySubnet"
  resource_group_name = var.rg-name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes = ["10.0.128.0/27"]

  depends_on = [azurerm_virtual_network.vnet]
}


resource "azurerm_virtual_network_gateway" "vnet-gateway" {
  name = "vnet-gateway"
  location = var.location
  resource_group_name = var.rg-name

  type = "Vpn"
  vpn_type = "PolicyBased"
  sku = "VpnGw1"
  # skus : [ Basic, VpnGw1, VpnGw2, VpnGw3, VpnGw4, VpnGw5, VpnGw1AZ, VpnGw2AZ, VpnGw3AZ, VpnGw4AZ, VpnGw5AZ ]

  ip_configuration {
    name = "vnet-gateway-config"
    public_ip_address_id = azurerm_public_ip.vpn-pip.id
    private_ip_address_allocation = "Dynamic"
    subnet_id = azurerm_subnet.vnet-gateway-subnet.id
  }

  depends_on = [azurerm_resource_group.rg, azurerm_subnet.vnet-gateway-subnet, azurerm_public_ip.vpn-pip]
}
```

### Debug Output

https://gist.github.com/DatYannou/7d4fdc27bd1a85608a1e5f3def27f332

### Expected Behavior

Terraform should just create the Virtual Network Gateway using the existing SKU "VpnGw1".
If the "Basic" SKU is used, then it should create the component with Basic SKU.

### Actual Behavior

If SKU is set to "VpnGw1", output is : 
```
Error: expected sku to be one of [Basic], got VpnGw1
```
Whereas VpnGw1 SKU actually exists

If SKU is set to "Basic", output is : 
```
Error: Error waiting for completion of AzureRM Virtual Network Gateway "vnet-gateway" (Resource Group "rg-test"): Code="InvalidGatewaySize" Message="The specified gateway size is not valid, supported gateway sizes are HighPerformance,VpnGw1,VpnGw2,VpnGw3,VpnGw1AZ,VpnGw2AZ,VpnGw3AZ,ErGw1AZ,ErGw2AZ,ErGw3AZ,VpnGw4,VpnGw5,VpnGw4AZ,VpnGw5AZ." Details=[]
```
It seems to say that every SKU but "Basic" exists.

So if I set "Basic", I should set another SKU like "VpnGw1"
And if I set "VpnGw1", I sould set to "Basic" SKU

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -out out.plan`
3. `terraform apply out.plan`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. According by the [document description](https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway.html#sku), seems vnet gateway cannot be created with "VpnGw1" when vpn_type is "PolicyBased".

Creating vnet with Basic sku:
```
resource "azurerm_virtual_network_gateway" "example" {
  name                = "testneilte-vnetgw"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type     = "Vpn"
  vpn_type = "PolicyBased"
  sku      = "Basic"

  ip_configuration {
     name                          = "vnetGatewayConfig"
     public_ip_address_id          = azurerm_public_ip.example.id
     private_ip_address_allocation = "Dynamic"
     subnet_id                     = azurerm_subnet.example.id
  }
}
```

Creating vnet with vpngw1 sku:
```
resource "azurerm_virtual_network_gateway" "example" {
  name                = "${var.prefix}-vnetgw"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type     = "Vpn"
  vpn_type = "RouteBased"
  sku      = "VpnGw1"

  ip_configuration {
     name                          = "vnetGatewayConfig"
     public_ip_address_id          = azurerm_public_ip.example.id
     private_ip_address_allocation = "Dynamic"
     subnet_id                     = azurerm_subnet.example.id
  }
}
```

**Comment by DatYannou** [comment]
Thanks for that, I didn't get that Policy based included you have to set it as Basic, but I tried it too.
Look, in the issue, the error I get when I set the SKU to "Basic". It just seems I can't user "Policy based" at all as neither "Basic" nor any other SKU works.

**Comment by neil-yechenwei** [comment]
Sorry. I just want to double confirm. You mean you want to create vnet gateway with Basic sku not updating sku from one to another one, right? If yes, could you have a try below tfconfig to check whether the issue still exists since I can create vnet gateway successfully?
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "testneilte-resources"
  location = "eastus2"
}

resource "azurerm_virtual_network" "example" {
  name                = "testneilte-vnet"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "GatewaySubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.0/24"
}

resource "azurerm_public_ip" "example" {
  name                = "testneilte-pip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Dynamic"
}

resource "azurerm_virtual_network_gateway" "example" {
  name                = "testneilte-vnetgw"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type     = "Vpn"
  vpn_type = "PolicyBased"
  sku      = "Basic"

  ip_configuration {
     name                          = "vnetGatewayConfig"
     public_ip_address_id          = azurerm_public_ip.example.id
     private_ip_address_allocation = "Dynamic"
     subnet_id                     = azurerm_subnet.example.id
  }
}

```

**Comment by DatYannou** [comment]
With my Terraform files (quoted in the issue), willing to build a Policy based Vnet Gateway with Basic SKU, I get this error : 
```
Error waiting for completion of AzureRM Virtual Network Gateway "vnet-gateway" (Resource Group "rg-test"): Code="InvalidGatewaySize" Message="The specified gateway size is not valid, supported gateway sizes are HighPerformance,VpnGw1,VpnGw2,VpnGw3,VpnGw1AZ,VpnGw2AZ,VpnGw3AZ,ErGw1AZ,ErGw2AZ,ErGw3AZ,VpnGw4,VpnGw5,VpnGw4AZ,VpnGw5AZ." Details=[]
```
Am I wrong or it really says "Basic" SKU doesn't exist ?


Anyway, I used your files and the Policy Based Vnet Gateway with Basic SKU seems to be working fine. Although our files are the same. Could it depend on other resources ?

**Comment by neil-yechenwei** [comment]
I assume it's dependency issue since I also tried to explicitly add dependency while running tf apply. But the resource still can be created successfully. For the improvement of the usage, I also submit a [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8141) to add examples for this scenario.

**Comment by DatYannou** [comment]
I tried a few things since yesterday and I managed to find the difference between our two settings @neil-yechenwei 
You set your public IP to Dynamic and I set mine to Static. I tried both this morning and the errors I mentionned in the issue (both for "Basic" and "VpnGw1" SKU vnet gateways) only occur when I set my public IP to a static allocation.
It doesn't seem normal to me, is there anything I'm not aware of  ?

Anyway, I can't really do with a dynamic public IP as I must set, for my Site-to-Site VPN, a public IP corresponding to my Azure network. Do you have in mind anything I could to to get past this ?

**Comment by neil-yechenwei** [comment]
After tested with static public ip, I didn't get the error `Error: expected sku to be one of [Basic], got VpnGw1` you mentioned. Could you share your tfconfig that trigger this issue?

**Comment by DatYannou** [comment]
Here's the ZIP containing simple variables and the whole infrastructure in one file. I rebuild that file using what you sent yesterday and changed things so it matches my configuration.

[tfconfig_vnetgw.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5089592/tfconfig_vnetgw.zip)

**Comment by neil-yechenwei** [comment]
I can repro it now and get the error "Error waiting for completion of AzureRM Virtual Network Gateway "vnet-gateway" (Resource Group "rg-test"): Code="InvalidGatewaySize" Message="The specified gateway size is not valid, supported gateway sizes are HighPerformance,VpnGw1,VpnGw2,VpnGw3,VpnGw1AZ,VpnGw2AZ,VpnGw3AZ,ErGw1AZ,ErGw2AZ,ErGw3AZ,VpnGw4,VpnGw5,VpnGw4AZ,VpnGw5AZ." Details=[]". I assume you didn't specify vpn_type as RouteBased since VpnGw1 doesn't support basic sku.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "testneilte-resources"
  location = "eastus2"
}

resource "azurerm_virtual_network" "example" {
  name                = "testneilte-vnet"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "GatewaySubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.1.0/24"
}

resource "azurerm_public_ip" "example" {
  name                = "testneilte-pip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_virtual_network_gateway" "example" {
  name                = "testneilte-vnetgw"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type     = "Vpn"
  vpn_type = "RouteBased"
  sku      = "VpnGw1"

  ip_configuration {
     name                          = "vnetGatewayConfig"
     public_ip_address_id          = azurerm_public_ip.example.id
     private_ip_address_allocation = "Dynamic"
     subnet_id                     = azurerm_subnet.example.id
  }
}
```

**Comment by DatYannou** [comment]
Thanks for your enlightenment. I already tried your second sample and it's seems to work fine. Your first sample is basically what my infrastructure looked like before I got that problem and created this issue. Thing is, my Site-to-Site VPN seems to need a policy based gateway and have a Static public IP. Should I conclude I can't have that ? (With Terraform)

**Comment by neil-yechenwei** [comment]
I assume it's Service API limitation not terraform limitation. If you have more questions about api usage, please submit issue on [azure rest api repo](https://github.com/Azure/azure-rest-api-specs). Thanks.

**Comment by DatYannou** [comment]
Ok I check on Azure Portal and, yes, it's the same. I'll see what I can do with that.
Thanks again for your help !
