### ISSUE TITLE
Terraform v0.13.0 with AzureRM v2.23.0 Initialization Error "Failed to install provider"

### ISSUE THREAD

**Issue by AErmie** [terraform-providers/terraform-provider-azurerm#8137]
When running terraform init with the latest version of Terraform (v0.13.0), and the latest version of the AzureRM provider (v2.23.0), Terraform throws the error "Failed to install provider"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.0
AzureRM v2.23.0

### Affected Resource(s)

None, occurs during Terraform init

* `azurerm_v2.23.0`

### Terraform Configuration Files

```hcl
terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 2.0.0"...
- Installing hashicorp/azurerm v2.23.0...

Error: Failed to install provider

Error while installing hashicorp/azurerm v2.23.0: mkdir
.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.23.0/windows_amd64:
The filename or extension is too long.
```

### Expected Behavior

Terraform init should download and install any providers required based on the configuration files/code. 

### Actual Behavior

Error produced stating:

Error: Failed to install provider

Error while installing hashicorp/azurerm v2.23.0: mkdir
.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.23.0/windows_amd64:
The filename or extension is too long.

### Steps to Reproduce

1. `terraform init`

**Comment by ArcturusZhang** [comment]
Hi @AErmie thanks for this issue!

Based on your error messages, this should not be an issue with the provider itself. Windows has a limit on [path length of 260 characters](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file). I am not sure how long is your current absolute path when you are running the command `terraform init`, but the error message is suggesting this. 

Terraform will create the sub-directory `.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.23.0/windows_amd64` in your current working directory, which has a length of 79. This makes you to have up to 181 characters (slash included) for your current working directory's absolute path.

Could you please double check if your path length has exceeds the limit?

**Comment by tombuildsstuff** [comment]
hey @AErmie 

Thanks for opening this issue.

Taking a look into this, unfortunately this appears to be an issue with Terraform Core (since that's downloading and launching the providers here) - as such would you mind re-opening this on the Terraform Core repository where that team should be able to take a look into this?

Thans!

**Comment by AErmie** [comment]
Sure thing @tombuildsstuff 
Here's the link (for reference): https://github.com/hashicorp/terraform/issues/25877
