### ISSUE TITLE
azurerm_automation_certificate - base64Value is invalid

### ISSUE THREAD

**Issue by K4hL** [terraform-providers/terraform-provider-azurerm#8143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azuread v0.11.0
+ provider.azurerm v2.23.0
+ provider.local v1.4.0

### Affected Resource(s)

* `azurerm_automation_certificate`

### Terraform Configuration Files

```hcl
resource "azurerm_automation_certificate" "example" {
  name                    = "certificate1"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name

  description = "This is an example certificate"
  base64      = base64encode(file("certificate.pfx"))
}
```

```hcl
resource "azurerm_automation_certificate" "example" {
  name                    = "certificate1"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name

  description = "This is an example certificate"
  base64      = filebase64("certificate.pfx")
}
```

### Expected Behavior
```hcl
 # azurerm_automation_certificate.main will be created
  + resource "azurerm_automation_certificate" "main" {
      + automation_account_name = "automationaccount1"
      + base64                  = (sensitive value)
      + description             = "This is an example certificate"
      + exportable              = (known after apply)
      + id                      = (known after apply)
      + name                    = "certificate1"
      + resource_group_name     = "resourcegroup1"
      + thumbprint              = (known after apply)
    }
```
Plan: 1 to add, 0 to change, 0 to destroy.

### Actual Behavior

`base64encode(file("certificate.pfx"))`
Call to function "file" failed: contents of certificate.pfx are not valid UTF-8; use the filebase64 function to obtain the Base64 encoded contents or the other file functions (e.g. filemd5, filesha256) to obtain file hashing results instead.

`filebase64("certificate.pfx")`
automation.CertificateClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Certificate base64Value is invalid."

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

certificate.pfx works fine to upload in Azure portal and with Powerhell cmdlt New-AzureRmResourceGroupDeployment.

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume now you have to use [filebase64](https://www.terraform.io/docs/configuration/functions/filebase64.html) to get base64 value for pfx file. Seems I can create automation certificate successfully after tested with below tfconfig and [pfx](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services/automation/tests/testdata). Maybe I missed something. Could you have a try below tfconfig to check whether the issue still exists?
```
provider "azurerm" {
  features {}
  version = "2.23.0"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-autocreti-test01"
  location = "eastus2"
}

resource "azurerm_automation_account" "test" {
  name                = "acctest-autoacct-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku_name            = "Basic"
}

resource "azurerm_automation_certificate" "test" {
  name                    = "certificatetest01"
  resource_group_name     = azurerm_resource_group.test.name
  automation_account_name = azurerm_automation_account.test.name
  description             = "This is an example certificate"
  base64                  = filebase64("testdata/automation_certificate_test.pfx")
}
```
![image](https://user-images.githubusercontent.com/19754191/90582818-49d8a180-e201-11ea-9829-aee4b531fe50.png)

**Comment by K4hL** [comment]
I did use filebase64() and it seem to work with "testdata/automation_certificate_test.pfx", but when I use the .pfx that I generate by using Powershell cmdlts 'New-SelfSignedCertificate' and 'Export-PfxCertificate' I get the error message 'Certificate base64Value is invalid.'

Are you able to add a new selfsigned certificate and if so how do you go about creating that?

**Comment by arestarh** [comment]
@K4hL Probably, your .pfx is password protected while test one [pfx](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services/automation/tests/testdata) is not.

**azurerm_automation_certificate** resource does not have argument to specify pfx password and I suppose it's because you can't specify pfx password using Azure REST API as well https://docs.microsoft.com/en-us/rest/api/automation/certificate/createorupdate. But via Azure Portal you can specify pfx password during creating Azure Automation asset.

**Comment by K4hL** [comment]
@arestarh That could be it, but is it not strange that I would need a .pfx without password as these are the most common? Even seem difficult to to create your own selfsigned certificates without password and I am struggling to find a solution for this.

**Comment by arestarh** [comment]
@K4hL
>That could be it, but is it not strange that I would need a .pfx without password as .pfx with password is a lot more common?

I agree with you and Azure Portal\Az Powershell module allows to specify password for pfx.

>Even seem difficult to to create your own self-signed certificates without password and I am struggling to find a solution for this.

You can try to check here https://docs.microsoft.com/en-us/azure/automation/shared-resources/certificates#create-a-new-certificate-with-a-resource-manager-template

As another workaround you can try to:

- Import pfx to Azure Key Vault using **azurerm_key_vault_certificate** https://www.terraform.io/docs/providers/azurerm/r/key_vault_certificate.html
- Get info about imported certificate (with private key) using data source **azurerm_key_vault_secret** https://www.terraform.io/docs/providers/azurerm/d/key_vault_secret.html
- Use **value** attribute that is exported by **azurerm_key_vault_secret** data source as value for base64 argument of **azurerm_automation_certificate** https://www.terraform.io/docs/providers/azurerm/r/automation_certificate.html

**Comment by arestarh** [comment]
@tombuildsstuff is it worth to create feature request for improving **azurerm_automation_certificate**:
- ability to specify **password** for pfx
- ability to specify **isExportable** argument
 
I'm asking, because as stated in Azure Rest API https://docs.microsoft.com/en-us/rest/api/automation/certificate/createorupdate we can specify **isExportable** argument, but **password** for pfx we can't.

**Comment by K4hL** [comment]
@arestarh thanks a lot for the keyvault workaround it worked very well, even though the ability to get certificates through data source azurerm_key_vault_secret with the 'name' was a kinda hidden feature. 

```hcl
data "azurerm_key_vault_secret" "certificate" {
  name         = "name-of-azurerm_key_vault_certificate-resource"
  key_vault_id = azurerm_key_vault.main.id
}
```hcl

**Comment by K4hL** [comment]
@arestarh do you happen to know if there is a similar workaround for getting the .pem **value** from KeyVault into azuread_service_principal_certificate ?

**Comment by arestarh** [comment]
@K4hL You can try to use **certificate_data** attribute that is exported by **azurerm_key_vault_certificate** data source.
**certificate_data** attribute is not mentioned in **azurerm_key_vault_certificate** data source docs https://www.terraform.io/docs/providers/azurerm/d/key_vault_certificate.html, but seems like in source code it's presented.

I'll try to do 2 things:
- Create PR to update **azurerm_key_vault_certificate** data source docs to add missing attribute(s).
- Create **issue** (Enhancement) to add ability to specify password for pfx and ability to specify isExportable argument to **azurerm_automation_certificate** resource.

**Comment by K4hL** [comment]
@arestarh The **certificate_data **  does not seem to be in the correct format for azuread_service_principal_certificate value argument, I tried both raw and with base64encode(data.azurerm_key_vault_certificate.main.certificate_data) and Azure throws error message"Invalid certificate: Key value is invalid certificate" for both.

**Comment by arestarh** [comment]
@K4hL Take a look at https://github.com/terraform-providers/terraform-provider-azurerm/pull/8184
It should resolve story with **azuread_service_principal_certificate**

**Comment by K4hL** [comment]
@arestarh Nice and thanks for the notification.
