### ISSUE TITLE
Always getting error trying to import Traffic Manager Profile

### ISSUE THREAD

**Issue by alexvy86** [terraform-providers/terraform-provider-azurerm#8164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
 v0.12.26
+ provider.azurerm v2.23.0
```

### Affected Resource(s)

* `azurerm_traffic_manager_profile`

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "resource_group" {
  name     = "my-rg"
}

resource "azurerm_traffic_manager_profile" "traffic-manager" {
  name                   = "my-traffic-manager-profile"
  resource_group_name    = data.azurerm_resource_group.resource_group.name
  traffic_routing_method = "Weighted"

  dns_config {
    relative_name = "my-relative-name"
    ttl           = 100
  }

  monitor_config {
    protocol                     = "tcp"
    port                         = 443
    interval_in_seconds          = 30
    timeout_in_seconds           = 5
    tolerated_number_of_failures = 3
  }
}
```

### Debug Output

My console buffer wasn't big enough so I couldn't capture the full debug logs, but I think the last section is really the interesting one. Gist [here](https://gist.github.com/alexvy86/04f2c0b3cb797db10793d4a257b4c9b7).

### Panic Output

N/A

### Expected Behavior

Traffic Manager profile should have been imported successfully.

### Actual Behavior

Terraform reports an error and does not import the Traffic Manager profile.

### Steps to Reproduce

I created a Traffic Manager profile in the Portal and I'm trying to import it into my Terraform template/state.

1. `terraform import azurerm_traffic_manager_profile.traffic-manager "/subscriptions/<my-subscription-id>/resourcegroups/my-rg/providers/Microsoft.Network/trafficmanagerprofiles/my-traffic-manager-profile"`

When setting `TF_LOG="Trace"`, I can see that the issue is a `400 Bad Request` response when making a request to read the list of traffic manager profiles from the Azure REST API (`https://management.azure.com/subscriptions/<my-subscription-id>/resourceGroups/my-rg/providers/Microsoft.Network/trafficmanagerprofiles/?api-version=2018-04-01`).

I tested that request in the Azure documentation/portal where you can try calls to this API, and it worked, so it seems Terraform is not sending something? The `Authorization` header, maybe?

### Important Factoids

Nothing out of the ordinary. Regular Azure Cloud.

### References

N/A

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume your import command has problem. Could you have a try below command since I can import successfully with below command? Thanks.

```
terraform import azurerm_traffic_manager_profile.test /subscriptions/<insert your subscription id>/resourceGroups/<insert your resource group name>/providers/Microsoft.Network/trafficManagerProfiles/<insert your traffic manager profile name>
```

**Comment by alexvy86** [comment]
Ah, my issue was the casing of `trafficmanagerprofiles` in the Azure resource Id (it's supposed to be `trafficManagerProfiles`). Tahkns @neil-yechenwei !
