### ISSUE TITLE
Creating Nested level directories in azure storage file share and uploading the files.

### ISSUE THREAD

**Issue by Abhishekqwerty** [terraform-providers/terraform-provider-azurerm#8168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_storage_share_directory cannot create a nested level directory within the file share. It only allows one level nested directory. 
This functionality can be achieved using azure cli.

azurerm_storage_share_directory also does not have the feature to upload the files to the file share directories.

### Terraform Version 
Terraform v0.13.0

### AzureRM Provider: 
provider.azurerm v2.21.0

### New or Affected Resource(s)

* azurerm_storage_share_directory

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_share_directory" "file_share_directories" {
  name = "email"
  share_name = azurerm_storage_share.file_share.name
  storage_account_name = azurerm_storage_account.storage_account.name
  depends_on = [azurerm_storage_share.file_share]
}

resource "azurerm_storage_share_directory" "file_share_directoriesone" {
  name = "email/user"
  share_name = azurerm_storage_share.file_share.name
  storage_account_name = azurerm_storage_account.storage_account.name
  depends_on = [azurerm_storage_share_directory.file_share_directories]
}

resource "azurerm_storage_share_directory" "file_share_directoriestwo" {
  name = "email/user/img"
  share_name = azurerm_storage_share.file_share.name
  storage_account_name = azurerm_storage_account.storage_account.name
  depends_on = [azurerm_storage_share_directory.file_share_directoriesone]
}
```

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems I can create successfully with nested directory. Could you have a try below tfconfig to check whether the issue still exists? For uploading file to share, after checked, seems azure rest api hasn't support it since I didn't find any upload function on rest api spec. Maybe I missed something. Could you share some document about it? Thanks.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-share-test01"
  location = "eastus2"
}

resource "azurerm_storage_account" "test" {
  name                     = "acctestsa01"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "test" {
  name                 = "fileshare"
  storage_account_name = azurerm_storage_account.test.name
  quota                = 50
}

resource "azurerm_storage_share_directory" "parent" {
  name                 = "parent"
  share_name           = azurerm_storage_share.test.name
  storage_account_name = azurerm_storage_account.test.name
}

resource "azurerm_storage_share_directory" "child" {
  name                 = "${azurerm_storage_share_directory.parent.name}/child"
  share_name           = azurerm_storage_share.test.name
  storage_account_name = azurerm_storage_account.test.name
}

resource "azurerm_storage_share_directory" "child_two" {
  name                 = "${azurerm_storage_share_directory.parent.name}/childtwo"
  share_name           = azurerm_storage_share.test.name
  storage_account_name = azurerm_storage_account.test.name
}
```

**Comment by Abhishekqwerty** [comment]
Yes, @neil-yechenwei. As mentioned in the description we can only create one level nested directory, but if I want to create two OR three level nested directory, then we are not able to perform.

**Comment by neil-yechenwei** [comment]
@Abhishekqwerty , I assume the value of name in below sample means this is a two level nested directory, right? If yes, I assume it has been implemented.

resource "azurerm_storage_share_directory" "child_two" {
  name                 = "${azurerm_storage_share_directory.parent.name}/childtwo"
  share_name           = azurerm_storage_share.test.name
  storage_account_name = azurerm_storage_account.test.name
}

**Comment by tombuildsstuff** [comment]
@neil-yechenwei this is referencing a multi-level directory structure e.g. `name = "first/second/third"` which isn't currently supported (today only "first/second" works, as per your example)

**Comment by Abhishekqwerty** [comment]
Yes, @tombuildsstuff.

**Comment by Abhishekqwerty** [comment]
> @Abhishekqwerty , I assume the value of name in below sample means this is a two level nested directory, right? If yes, I assume it has been implemented.
> 
> resource "azurerm_storage_share_directory" "child_two" {
> name = "${azurerm_storage_share_directory.parent.name}/childtwo"
> share_name = azurerm_storage_share.test.name
> storage_account_name = azurerm_storage_account.test.name
> }

Sorry, @neil-yechenwei. I didn't elaborate much.
