### ISSUE TITLE
Support for azurerm_cluster_node_pool with min_count 0

### ISSUE THREAD

**Issue by arodriguezdlc** [terraform-providers/terraform-provider-azurerm#8219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for aks nodepools with min count to 0. I have seen there is a TODO at the code, but I couldn't find any issue to keep track of this feature. 

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "user" {
  name                  = "user"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count             = 0
  max_count             = 20
  max_pods              = 80
}
```

**Comment by jackofallops** [comment]
Closing as resolved by 8300 which will be part of the 2.31.0 release.
