### ISSUE TITLE
Application Insights provider ignores application_type - always sets to "ASP.Net"

### ISSUE THREAD

**Issue by sjwaight** [terraform-providers/terraform-provider-azurerm#822]
When creating a new Application Insights instance for a non-web resource (like Functions) you can set the application_type to "Other" according to documentation. However, when you do this the resulting Application Insights instance is still set to a type of "ASP.Net".

### Terraform Version
- Terraform v0.11.2
- provider.azurerm v1.1.0

### Affected Resource(s)
- azurerm_application_insights

### Terraform Configuration Files
```hcl
resource "azurerm_application_insights" "demo_funcs_ai" {
  name                = "ai-fa-demofunctions"
  location            = "West US 2"
  resource_group_name = "demo-rg-appinsights"
  application_type    = "Other"
}
```
### Expected Behavior
An Application Insights instance was created with a "Type" of "General".

### Actual Behavior
An Application Insights instance was created with a "Type" of "ASP.Net".

### Steps to Reproduce
Run above HCL snippet and the result can be immediately observed.

**Comment by stack72** [comment]
@tombuildsstuff I have been working on this - PR will be incoming soon! I just need to work out the best way to structure the tests to make sure all works as expected
