### ISSUE TITLE
azurerm_mssql_elasticpool - service tier 'Basic' must have whole numbers as their 'minCapacity'

### ISSUE THREAD

**Issue by jwshive** [terraform-providers/terraform-provider-azurerm#8226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.24.0

### Affected Resource(s)

* `azurerm_mssql_elasticpool`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "sql_elastic_pool" {
  name = "agency-dept-dev-app-epool"
  location = "eastus"
  resource_group_name = azurerm_resource_group.resource_group.name
  server_name = azurerm_mssql_server.sql_server.name
  max_size_gb = 4.8828125


  per_database_settings {
    min_capacity = 0.5
    max_capacity = 5
  }

  sku {
    capacity = 50
    name = "BasicPool"
    tier = "Basic"
  }
  depends_on = [azurerm_mssql_server.sql_server]
}
```

### Expected Behavior

a sql elastic pool is created

### Actual Behavior
```
Error: service tier 'Basic' must have whole numbers as their 'minCapacity'

  on main.tf line 46, in resource "azurerm_mssql_elasticpool" "sql_elastic_pool":
  46: resource "azurerm_mssql_elasticpool" "sql_elastic_pool" {
```
### Steps to Reproduce

1. `terraform plan`

### References
According to [this link](https://docs.microsoft.com/en-us/azure/azure-sql/database/resource-limits-dtu-elastic-pools) , basic elastic pools have a Min DTU per database choices valid option of only 0,.5. When I attempt to set the value to 0.5, I receive the error above. When I set it to a whole number, ie: 1, I get 
```
Error: sql.ElasticPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidInputValueForDatabaseDtuMin" Message="The DTU min per database (1) for the elastic pool does not belong to the allowed values for service tier 'Basic'."

  on dfr-impact-env.tf line 240, in resource "azurerm_mssql_elasticpool" "sql_elastic_pool":
 240: resource "azurerm_mssql_elasticpool" "sql_elastic_pool" {
```

This fails both in Azure DevOps Pipelines and manually with terraform plan.

When I create a database within the portal, since I can't do it with terraform, the min_capacity is set to 0. Which also doesn't appear to be valid but yet, that's how they are created and I see no way to change that during portal creation. I can't seem to create or import a mssql database using terraform. This is kind of a big deal.

* #0000

**Comment by yupwei68** [comment]
Hi @jwshive , thanks for opening this issue. I have tried your code. The`min_capacity` in `per_database_settings` could not be set "0.5" because you're using a "BasicPool" sku elastic pool. 
Another question you raised is that you can not set `min_capacity` in `per_database_settings` to be "0". But I have tried your code with "0" and applied successfully in Azurerm 2.24.0.
You need either change the sku_name either set  `min_capacity` in `per_database_settings` to be "0"

```
resource "azurerm_mssql_elasticpool" "sql_elastic_pool" {
  ...

  per_database_settings {
    min_capacity = 0
    max_capacity = 5
  }

  sku {
    capacity = 50
    name = "BasicPool"
    tier = "Basic"
  }
  depends_on = [azurerm_mssql_server.sql_server]
}
```

or 

```
resource "azurerm_mssql_elasticpool" "sql_elastic_pool" {
  ...

per_database_settings {
    min_capacity = 0.5
    max_capacity = 4
  }

  sku {
    capacity = 6
    name     = "GP_Gen5"
    tier     = "GeneralPurpose"
    family   = "Gen5"
  }
  depends_on = [azurerm_mssql_server.sql_server]
}
```

**Comment by jwshive** [comment]
I can still create the ePool with your settings, but my problem remains when I do a terraform import of the database I create via the portal and then do a terraform plan to see if if everything is clean.

```
Error: expected min_capacity to be one of [0.5 0.75 1 1.25 1.5 1.75 2 2.25 2.5 3 4 5], got 0.000000

  on main.tf line 30, in resource "azurerm_mssql_database" "sql-database":
  30: resource "azurerm_mssql_database" "sql-database" {
```

Using your suggested changes

```hcl
resource "azurerm_mssql_elasticpool" "sql_elastic_pool" {
  name = "agency-department-environment-application-epool"
  location = "eastus"
  resource_group_name = azurerm_resource_group.resource_group.name
  server_name = azurerm_mssql_server.sql_server.name
  max_size_gb = 4.8828125

  per_database_settings {
    min_capacity = 0
    max_capacity = 5
  }

  sku {
    capacity = 50
    name = "BasicPool"
    tier = "Basic"
  }
  depends_on = [azurerm_mssql_server.sql_server]
}
```

This is the terraform show output of the db resource that was created via the portal.

```hcl
resource "azurerm_mssql_database" "sql-database" {
    auto_pause_delay_in_minutes = 0
    collation                   = "SQL_Latin1_General_CP1_CI_AS"
    elastic_pool_id             = "/subscriptions/subscription-id/resourceGroups/agency-department-dev-application-rg/providers/Microsoft.Sql/servers/fssa-dfr-dev-impact-sqlsvr/elasticPools/agency-department-dev-application-epool"
    id                          = "/subscriptions/subscription-id/resourceGroups/agency-department-dev-application-rg/providers/Microsoft.Sql/servers/fssa-dfr-dev-impact-sqlsvr/databases/agency-department-dev-application-db"
    max_size_gb                 = 2
    min_capacity                = 0
    name                        = "agency-department-dev-application-db"
    read_replica_count          = 0
    read_scale                  = false
    server_id                   = "/subscriptions/subscription-id/resourceGroups/agency-department-dev-application-rg/providers/Microsoft.Sql/servers/agency-department-dev-application-sqlsvr"
    sku_name                    = "ElasticPool"
    tags                        = {}
    zone_redundant              = false

    threat_detection_policy {
        disabled_alerts      = []
        email_account_admins = "Disabled"
        email_addresses      = []
        retention_days       = 0
        state                = "Disabled"
        use_server_default   = "Disabled"
    }

    timeouts {}
}
```

So I still can't use 0 when I try to plan with the database itself, and I can't use 0.5 to build the pool, and I can't use terraform at all to build the database because of [this bug](https://github.com/Azure/azure-rest-api-specs/issues/10411)

**Comment by tombuildsstuff** [comment]
@jwshive just to confirm, is this Azure Public or another Azure Environment?

**Comment by jwshive** [comment]
This is the basic public cloud.
