### ISSUE TITLE
terraform does not update blob files if they already exist

### ISSUE THREAD

**Issue by jpveritone** [terraform-providers/terraform-provider-azurerm#8227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.12 with azurerm_1.44.0

### Affected Resource(s)

* `azurerm_storage_blob`

### Terraform Configuration Files

```hcl
data "template_file" "prep-system" {
  template = "${file("files/prep-system-fastcore.sh.tftemplate")}"

  vars {
    swapsizeMB   = "${var.swapsizeMB}"
    domain_name  = "${var.vpc_dns_zone_name}"
    node_exporter_url = "${var.node_exporter_url}"
    prometheus_mon_dir = "${var.prometheus_mon_dir}"
    mon_container_script = "${var.mon_container_script}"
    mon_container_file = "${local.mon_container_link}"
  }
}

resource "local_file" "prep-system" {
  content     = "${data.template_file.prep-system.rendered}"
  filename = "${path.module}/${var.prep_system_script}"
}

# Here we do the actual upload to blob of our rendered script
resource "azurerm_storage_blob" "prep-system" {
  depends_on = ["local_file.prep-system"]
  name = "${var.prep_system_script}"
  source = "${var.prep_system_script}"
  type = "block"

  resource_group_name    = "${data.terraform_remote_state.stor-blob-veritone.resource_group_name}"
  storage_account_name   = "${data.terraform_remote_state.stor-blob-veritone.stor_account_name}"
  storage_container_name = "${data.terraform_remote_state.stor-blob-veritone.stor_container_name}"
}
```

### Expected Behavior

Anytime I change my template and run terraform apply I see the new rendering of template but the 
resource "azurerm_storage_blob will not upload or replace file in blob since it already exist. If I delete the blob 
it does upload fine. This is discussed in https://github.com/terraform-providers/terraform-provider-azurerm/issues/3147 but that issue was closed without a resolution.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @jpveritone 

Thanks for opening this issue.

At this time the `azurerm_storage_blob` doesn't track the contents of the blob due to the MD5 checksum being returned from Azure being different to a regular MD5 checksum (I forget the specifics) - however that's being tracked in #1990 which when implemented should fix this issue.

Since this is issue will be resolved by #1990 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #1990 - would you mind subscribing to that issue for updates?

Thanks!
