### ISSUE TITLE
azurerm_monitor_diagnostic_setting produces inconsistent plan

### ISSUE THREAD

**Issue by favoretti** [terraform-providers/terraform-provider-azurerm#8230]
Error: Provider produced inconsistent final plan

When expanding the plan for
module.generic_sa_fdx_qa.azurerm_monitor_diagnostic_setting.this["this"] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.log: planned set element
cty.ObjectVal(map[string]cty.Value{"category":cty.UnknownVal(cty.String),
"enabled":cty.UnknownVal(cty.Bool),
"retention_policy":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"days":cty.UnknownVal(cty.Number),
"enabled":cty.UnknownVal(cty.Bool)})})}) does not correlate with any element
in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ provider registry.terraform.io/hashicorp/azurerm v2.24.0
### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

**Comment by magodo** [comment]
@favoretti Thank you for submitting this :+1:

This bug is being tracked in #6254 which I'm going to close this in favour of - would you mind subscribing to that issue for updates?

**Comment by favoretti** [comment]
Ah, didn't find it easily, thank you!
