### ISSUE TITLE
Option to enable or disable BGP route propagation on Route Table

### ISSUE THREAD

**Issue by sppwf** [terraform-providers/terraform-provider-azurerm#824]
Hi there,

Azure gives option to enable or disable BGP route propagation on Route Table level.
Terrafomr does not give configuration option for the above Feature

### Terraform Version
Terraform v0.11.2
terraform-provider-azurerm_v1.1.1_x4

### Affected Resource(s)
- azurerm_route_table

### Terraform Configuration Files
```hcl
resource "azurerm_route_table" "rt1" {
  name                         = "${var.specific["scope"]}-${var.specific["env"]}-route-table-${var.specific["region_tag"]}"
  resource_group_name          = "${azurerm_resource_group.rg1.name}"
  location                     = "${azurerm_resource_group.rg1.location}"
}

```
### Expected Behavior
Option to add  BGP route propagation ON/OFF Feature

### Actual Behavior
No Option to enable the feature

**Comment by katbyte** [comment]
Hi @sppwf,

I took a look today and it appears that this option has not [been exposed by the API/SDK yet](https://github.com/Azure/azure-sdk-for-go/issues/1974)

**Comment by katbyte** [comment]
Hello again @sppwf,

Looks like I was wrong! We are just on the wrong version of the SDK so we just need to update it then should be good to include add the property.
