### ISSUE TITLE
Missing keys in azurerm_bot_channel_directline: extensionKey1, extensionKey2

### ISSUE THREAD

**Issue by ikru** [terraform-providers/terraform-provider-azurerm#8248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

I am using azurerm_bot_channel_directline on ASE and there are two relatively new keys, that are not exposed in the azurerm_bot_channel_directline: extensionKey1, extensionKey2. It would be nice if they were implemented as output, so we could use them as azurerm_bot_channel_directline.mydl.extensionKey1 / azurerm_bot_channel_directline.mydl.extensionKey2 in other resources.

In Azure they are available in direct line settings:

![image](https://user-images.githubusercontent.com/3754123/91190983-36767c00-e6c2-11ea-9d56-2afb47750bc2.png)

Also it can be retrieved with az cli:

az bot directline show --resource-group MY_RESOURCE_GROUP --name MY-BOT-WEB-APP --with-secrets

```
{
  "changedTime": "0001-01-01T00:00:00Z",
  "entityTag": "W/\"qwerty/25/2020 2:46:52 PM\"",
  "etag": null,
  "id": "/subscriptions/<subscriptionid>/resourceGroups/RG/providers/Microsoft.BotService/botServices/MY_BOT_NAME/channels/DirectLineChannel",
  "kind": null,
  "location": "global",
  "name": null,
  "properties": {
    "channelName": "DirectLineChannel",
    "etag": "W/\"qwerty/25/2020 2:46:52 PM\"",
    "location": "global",
    "properties": {
      "DirectLineEmbedCode": null,
      "sites": [
        {
          "isBlockUserUploadEnabled": false,
          "isEnabled": true,
          "isSecureSiteEnabled": false,
          "isV1Enabled": true,
          "isV3Enabled": true,
          "key": "qwerty.TCfg4MEPahPdeMxdeRmfhDgqeGRkbRlFJ4x69NXTtbA",
          "key2": "qwerty.Oz3QZQFU5E8Bu4E96qjVQSJBmRdENPd09IjEUncuDV0",
          "siteId": "qwerty",
          "siteName": "Default Site",
          "trustedOrigins": null
        }
      ]
    }
  },
  "provisioningState": "Accepted",
  "resource": {
    "channelName": "DirectLineChannel",
    "etag": "W/\"qwerty/25/2020 2:46:52 PM\"",
    "location": "global",
    "properties": {
      "sites": [
        {
          "isBlockUserUploadEnabled": false,
          "isEnabled": true,
          "isSecureSiteEnabled": false,
          "isV1Enabled": true,
          "isV3Enabled": true,
          "key": "qwerty.TCfg4MEPahPdeMxdeRmfhDgqeGRkbRlFJ4x69NXTtbA",
          "key2": "qwerty.Oz3QZQFU5E8Bu4E96qjVQSJBmRdENPd09IjEUncuDV0",
          "siteId": "qwerty",
          "siteName": "Default Site"
        }
      ]
    }
  },
  "resourceGroup": "RESOURCE_GROUP_NAME",
  "setting": {
    "botIconUrl": "https://docs.botframework.com/static/devportal/client/images/bot-framework-default.png",
    "botId": "MY_BOT_NAME",
    "channelDisplayName": "Direct Line",
    "channelId": "directline",
    "extensionKey1": "qwerty.GNeFkWm8RE626WtgQQdrcMjpV5FQHBheY3RvZqNfqkY",
    "extensionKey2": "qwerty.USs7930NV1JTnw2tk_ai9FVCYfaaJ46OMn5c2kIY_5Q",
    "isEnabled": true,
    "sites": [
      {
        "eTag": "\"qwerty\"",
        "isBlockUserUploadEnabled": false,
        "isEnabled": true,
        "isSecureSiteEnabled": false,
        "isV1Enabled": true,
        "isV3Enabled": true,
        "isWebchatPreviewEnabled": false,
        "key": "qwerty.TCfg4MEPahPdeMxdeRmfhDgqeGRkbRlFJ4x69NXTtbA",
        "key2": "qwerty.Oz3QZQFU5E8Bu4E96qjVQSJBmRdENPd09IjEUncuDV0",
        "siteId": "qwerty",
        "siteName": "Default Site"
      }
    ]
  },
  "sku": null,
  "tags": null,
  "type": null
}
(IDs are fake)
```

Wanted to note, that these are different keys from those available under direct line sites as key1, key2.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
Closing since this is now available within the `site` block: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bot_channel_directline#key

**Comment by ikru** [comment]
Hi @tombuildsstuff,

There are two set of keys in direct line channel:
1. Under site key1, key2 - these were always available
2. Under settings extensionKey1, extensionKey2 - these are still missing. 
Please look at the picture and json in the description.

Thanks

**Comment by ikru** [comment]
Please reopen?

**Comment by ikru** [comment]
Hey @tombuildsstuff, @mybayern1974,

Please reopen:
There are two set of keys in direct line channel:

Under site key1, key2 - **these were always available**
Under settings extensionKey1, extensionKey2 - **these are still missing!!!**
Please look at the picture and json in the description.
Thanks

**Comment by neil-yechenwei** [comment]
Thanks @ikru for raising this issue. TF would ignore the default site. I assume you have to create bot directline channel with custom site name. Below is a sample.
```
resource "azurerm_bot_channel_directline" "test" {
  bot_name            = azurerm_bot_channels_registration.test.name
  location            = azurerm_bot_channels_registration.test.location
  resource_group_name = azurerm_resource_group.test.name

  site {
    name    = "UserCustomTestSite"
    enabled = true
  }
}
```

**Comment by ikru** [comment]
Hi @neil-yechenwei,

Not really it's a separate set if keys for completely different purpose. These keys are there to configure bot for direct line extension. They just need to be added as properties for directline channel.

Please Look at json in my original message:
extensionKey1
extensionKey2

They aren't under sites and they have nothing to do with sites.

**Comment by neil-yechenwei** [comment]
@ikru , thanks for your clarification. After do more investigation, seems go sdk client would omit extensionKey1 and extensionKey2 in API response. So I assume it's Service API problem not TF problem. I already raised an [issue](https://github.com/Azure/azure-rest-api-specs/issues/15400) for tracking.

**Comment by ikru** [comment]
You should use with-keys flag for the API. Then all keys including extensionKey1 and extensionKey2 are included. Which api are you using? I can craft the request.

**Comment by ikru** [comment]
Ok, thank you! Can you reopen this one as well to address these keys after api is updated?
