### ISSUE TITLE
Upgrade to v15 of the Azure SDK for Go & AutoRest v10.6

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#825]
Now that [the Azure SDK for Go's has hit General Availability](https://azure.microsoft.com/blog/build-go-apps-for-azure-with-the-go-sdk-now-generally-available/) we should upgrade to it, since the interface should be stable for the foreseeable future

I'll pick this task up this week - I'm opening the task to ensure nobody else picks up the same task :)

**Comment by sonram2536** [comment]
Sonram

**Comment by sonram2536** [comment]
Ponla3536

**Comment by Jakkob** [comment]
Hey @tombuildsstuff.
I'd like to make some quick changes to the CosmosDB resource that requires this update (Add support for CosmosDB Table Storage).

Any movement planned on this issue in the near future?

**Comment by tombuildsstuff** [comment]
@Jakkob I've got a WIP branch locally for this - but we should be getting to this as part of the v1.4 release :)

**Comment by tombuildsstuff** [comment]
hey @Jakkob - just to let you know that this is now being tracked in #1077 which we're hoping to merge tomorrow; sorry for the delay here! Thanks!

**Comment by tombuildsstuff** [comment]
Fixed via #1077
