### ISSUE TITLE
Should azurerm_log_analytics_workspace resource be updated such that SKU value is optional?

### ISSUE THREAD

**Issue by artburkart** [terraform-providers/terraform-provider-azurerm#8254]
In https://github.com/terraform-providers/terraform-provider-azurerm/issues/1078 the "PerGB2018" SKU was introduced to this provider code base. Since the SKU doesn't seem to be documented on the Azure website and defining the SKU is only relevant to Azure customers who were already on older SKUs, would it make sense to make this value optional and default to "PerGB2018"?

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems api would set sku with default value pergb2018 when sku isn't specified in request body. So I assume it could be updated. Hopes the [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8272) is helpful.
