### ISSUE TITLE
Support for maximum scale out limit for functions on a consumption plan

### ISSUE THREAD

**Issue by benbelow** [terraform-providers/terraform-provider-azurerm#8259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

See the Microsoft documentation here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#limit-scale-out

I can't see a way to introduce this limit to a functions app via terraform.

### New or Affected Resource(s)

* azurerm_function_app

### References

See the Microsoft documentation here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#limit-scale-out

**Comment by Radamonas** [comment]
Are there any timeline for implementing this?

**Comment by fgbaezp** [comment]
+1 for this
