### ISSUE TITLE
azurerm_function_app.functions.identity is empty list of object

### ISSUE THREAD

**Issue by michalchecinski** [terraform-providers/terraform-provider-azurerm#8262]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.5.0
```

### Affected Resource(s)

* `azurerm_function_app`
* `azurerm_role_assignment`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~>2.5.0"
  features {}
}

terraform {
  backend "azurerm" {
    resource_group_name  = "redacted_name"
    storage_account_name = "redacted_name"
    container_name       = "redacted_name"
    key                  = "terraform.tfstate"
  }
}

resource "azurerm_resource_group" "rg" {
  name     = var.rg_name
  location = var.location
}

resource "azurerm_application_insights" "functions" {
  name                = var.function_app_insights_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  application_type    = "web"
}

resource "azurerm_storage_account" "functions" {
  name                     = var.function_storage_name
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "functions" {
  name                = var.function_service_plan_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "FunctionApp"
  reserved            = true

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "functions" {
  name                      = var.function_app_name
  location                  = azurerm_resource_group.rg.location
  resource_group_name       = azurerm_resource_group.rg.name
  app_service_plan_id       = azurerm_app_service_plan.functions.id
  storage_connection_string = azurerm_storage_account.functions.primary_connection_string
  os_type                   = "linux"
  identity {
    type = "SystemAssigned"
  }

  version = "~3"

  app_settings = {
    https_only               = true
    FUNCTIONS_WORKER_RUNTIME = "python"
    FUNCTION_APP_EDIT_MODE   = "readonly"
    HASH                     = "base64encode(filesha256(${var.function_app_name}))"
    APP_INSIGHTS_KEY         = azurerm_application_insights.functions.instrumentation_key
    storage_name             = azurerm_storage_account.storage.name
  }
}

resource "azurerm_storage_account" "storage" {
  name                     = var.storage_name
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_role_assignment" "storage" {
  scope                = azurerm_storage_account.storage.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_function_app.functions.identity[0].principal_id
}

```

### Expected Behavior

`azurerm_function_app.functions.identity[0].principal_id` should have returned the managed identity service principal id of azure functions.

### Actual Behavior

```
Error: Invalid index

  on src/infrastructure/main.tf line 82, in resource "azurerm_role_assignment" "storage":
  82:   principal_id         = azurerm_function_app.functions.identity[0].principal_id
    |----------------
    | azurerm_function_app.functions.identity is empty list of object

The given key does not identify an element in this collection value.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` or `terraform plan`

### References

* #5663

**Comment by tombuildsstuff** [comment]
hi @michalchecinski 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). Taking a look through this appears to be a question around Terraform Configuration, and as such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by michalchecinski** [comment]
No it's not a problem with a config. Look at the issue I mentioned at the end of the dedcription. There was this bug some time ago, and it seems not to be fixed yet. This comment was posted after theoretical fix of the problem: https://github.com/terraform-providers/terraform-provider-azurerm/issues/5663#issuecomment-585429660
