### ISSUE TITLE
Error setting the draft Automation Runbook, azurerm_automation_runbook fails with 404 Error

### ISSUE THREAD

**Issue by cmptscpeacock** [terraform-providers/terraform-provider-azurerm#8269]
### Terraform (and AzureRM Provider) Version

Terraform Version
Terraform v0.12.12

provider.azurerm v2.21.0

### Affected Resource(s)

azurerm automation account runbook

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "loggingRG"
  location = "eastus2"
}

resource "azurerm_automation_account" "example" {
  name                = "testaccount"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"

  sku {
    name = "Basic"
  }
}

data "local_file" "example" {
  filename = "${path.module}/Users/testuser/tftest/Conncetionscript.ps1"
}

resource "azurerm_automation_runbook" "example" {
  name                             = "Conncetionscript"
  location                         = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  account_name              = "${azurerm_automation_account.example.name}"
  log_verbose                  = "true"
  log_progress                = "true"
  description                    = "testing tf template"
  runbook_type                = "PowerShell"
  content = "${data.local_file.example.filename}"

  depends_on = ["azurerm_automation_account.example"]
}
```

### Debug Output

azurerm_automation_runbook.runbook_start: Error setting the draft Automation Runbook automation.RunbookDraftClient#ReplaceContent: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/testaccount/runbooks/Conncetionscript' under resource group 'loggingRG' was not found." "

### Expected Behavior

Runbook should be created

### Actual Behavior

Looking for creating runbook which doesn't exist

### Steps to Reproduce

terraform apply

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/4403

**Comment by njuCZ** [comment]
@cmptscpeacock First of all I believe you are not using azurerm v2.21.0. Because after azurerm version 2.0, "sku" block in "azurerm_automation_account" is removed, so does the field "account_name" in "azurerm_automation_runbook". your pasted script is invalid.

I have tried the latest provider using the following script, there is no problem. Could you please have a try ?
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "loggingRG"
  location = "eastus2"
}

resource "azurerm_automation_account" "example" {
  name                = "testaccount"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku_name = "Basic"
}

resource "azurerm_automation_runbook" "example" {
  name                    = "Conncetionscript"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  log_verbose             = "true"
  log_progress            = "true"
  description             = "testing tf template"
  runbook_type            = "PowerShell"
  content                 = <<CONTENT
# Some test content
# for Terraform acceptance test
CONTENT
}
```

**Comment by cmptscpeacock** [comment]
@njuCZ 

Ok, I've tried the same against an automation account that already exists, rather than creating a new one, and the same error:

data "local_file" "file1" {
  filename = "./resources/scripts/Runbook1.ps1"
}

resource "azurerm_automation_runbook" "Runbook1" {
  name                    = "Runbook1"
  location                = var.location
  resource_group_name     = var.automationAccount1ResourceGroup
  automation_account_name = var.automationAccount1Name
  log_verbose             = "true"
  log_progress            = "true"
  description             = "Powershell Runbook"
  runbook_type            = "PowerShell"
  publish_content_link {
    uri = "https://STORAGEACCOUNT.blob.core.windows.net/temp/Runbook1.ps1"
  }
  content = data.local_file.file1.content

  tags = var.tags
}


As you can see, I also tried using the publish_content_link to see if this made a difference, but I've it with and without this and the same error occurs:

Error: Error setting the draft Automation Runbook "Runbook1" (Account "AUTOMATIONACCOUNT" / Resource Group "RESOURCEGROUP"): automation.RunbookDraftClient#ReplaceContent: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/AUTOMATIONACCOUNT/runbooks/Runbook1' under resource group RESOURCEGROUP' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

It's also definitely using azurerm provider v2.21.0

**Comment by njuCZ** [comment]
@cmptscpeacock 
First question: could you confirm whether the script without using `publish_content_link` could work?
second question: if using `publish_content_link`, could you confirm that the uri exists? I am afraid that the uri "https://STORAGEACCOUNT.blob.core.windows.net/temp/Runbook1.ps1" is not accessable. You could also try my following script:
```
resource "azurerm_automation_runbook" "example" {
  name                    = "Conncetionscript"
  location                = var.location
  resource_group_name     = var.resource_group_name
  automation_account_name = var.automation_account_name
  log_verbose             = "true"
  log_progress            = "true"
  description             = "testing tf template"
  runbook_type            = "PowerShell"

  publish_content_link {
    uri = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/c4935ffb69246a6058eb24f54640f53f69d3ac9f/101-automation-runbook-getvms/Runbooks/Get-AzureVMTutorial.ps1"
  }

  content = <<CONTENT
# Some test content
# for Terraform acceptance test
CONTENT
}
```

about the error message, I think it's because the uri does not exist and the creation call failed, but we missed that message. About this point, I am gonna fix it.

**Comment by cmptscpeacock** [comment]
@njuCZ 

As per last message "I also tried using the publish_content_link to see if this made a difference, but I've it with and without this and the same error occurs"

So, not using it results in the same error.

The link is a fake link for this issue ticket, but I used a real link in my tests.

**Comment by cmptscpeacock** [comment]
@njuCZ any update?

**Comment by artyq** [comment]
I am getting the same error as of today.  

> Error: Error setting the draft Automation Runbook "Start-SqlVms" (Account "hostingops-sql-dev-aa" / Resource Group "hostingops-sql-dev-rg"): automation.RunbookDraftClient#ReplaceContent: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/hostingops-sql-dev-aa/runbooks/Start-SqlVms' under resource group 'hostingops-sql-dev-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

```
data "local_file" "startsqlvms" {
  filename = "infrastructure/runbooks/Start-SqlVms.ps1"
}

resource "azurerm_automation_runbook" "startsqlvms" {
  name                = "Start-SqlVms"
  location            = var.location
  resource_group_name = var.rg
  account_name        = azurerm_automation_account.sqlhosting.name
  log_verbose         = true
  log_progress        = true
  description         = "Starts SQL Vms each morning."
  runbook_type        = "PowerShellWorkFlow"
  content             = data.local_file.startsqlvms.content

  # Always required, using dummy
  publish_content_link {
    uri = "https://portal.azure.com"
  }
}
```

**Comment by cmptscpeacock** [comment]
@artyq 

Can you check your automation account's activity log. Do you see an error like this after you try to deploy?

statusMessage":"{\"code\":\"BadRequest\",\"message\":\"{\\\"Message\\\":\\\"The request is invalid.\\\",\\\"ModelState\\\":{\\\"runbook.tags\\\":[\\\"Too many tags.\\\"]}}\"}"

I have a ticket open with Azure support and this is their first finding.

**Comment by artyq** [comment]
@cmptscpeacock The only message I can find is this:

`The Resource 'Microsoft.Automation/automationAccounts/hostingops-sql-dev-aa/runbooks/Start-SqlVms' under resource group 'hostingops-sql-dev-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

I manually added the runbook for now. I ran a plan and terraform was ok with it, I continued through the apply step and it succeeded.

For further testing, I let Terraform remove the manually added runbook and the schedules.  It removed it fine.  I added it back, and again Terraform failed with the same message as before.

**Comment by cmptscpeacock** [comment]
Ok, looks like we're getting similar results anyway.

Hopefully this gets raised as a bug asap and resolved quickly

**Comment by njuCZ** [comment]
@artyq I guess the reason of your script is the publish_content_link url is not a valid runbook script. You could simply remove the `publish_content_link` block, it's not a required field.

**Comment by cmptscpeacock** [comment]
@njuCZ 

As explained, I've tried this with ONLY publish_content_link and NOT content. Error

Then I tried ONLY content and NOT publish_content_link. Same error

Please raise as a bug and investigate

**Comment by cmptscpeacock** [comment]
any progress from anyone?

**Comment by cmptscpeacock** [comment]
I believe I've resolved this. The TF code was adding tags with the resource. This was in addition to tags that were being inherited when the resource was being deployed. The message identified by Azure Support of "too many tags" confirmed this. I've chosen not to include any tags with this resource and it deploys now. 

The error given is a bit misleading, so hopefully this will help someone at a future date.

**Comment by njuCZ** [comment]
@cmptscpeacock about the misleading error message, I have submitted a PR to fix it, sorry for the wrong error message
