### ISSUE TITLE
Data source for `azurerm_lb_rule`?

### ISSUE THREAD

**Issue by LukeCarrier** [terraform-providers/terraform-provider-azurerm#8271]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When working with AKS Clusters we quote often need to get the egress IP address of the cluster for use in firewall rules. It's currently quite difficult to find the correct IP as we can't easily look up the frontend IP configuration and public IP associated with a named LB rule (`aksOutboundRule`).

### New or Affected Resource(s)

* `data.azurerm_lb_rule`

### Potential Terraform Configuration

```hcl
// Already present
data "azurerm_lb" "lb" {
  name = "my-lb"
  resource_group_name = "my-rg"
}

// Missing
data "azurerm_lb_rule" "named_rule" {
  name = "my-rule"
  loadbalancer_id = data.azurerm_lb.lb.id
}
```

### References

_N/A_

**Comment by LukeCarrier** [comment]
Doh 🤦

**Comment by alvintang** [comment]
Hello. I'd like to give this a shot :)
