### ISSUE TITLE
VMSS - Updating Custom Data - Update Instances true should be optional

### ISSUE THREAD

**Issue by marcelkmfst** [terraform-providers/terraform-provider-azurerm#8282]
When using VMSS with custom data, an update of custom data currently triggers an update of the VMSS instances because the provider is sending an UpdateInstances:true in the payload.

This can´t be configured currently. 

However, this is different to how Azure works out of the box where custom data update is not updating the instances automatically.

_Can I update custom data after the VM has been created?
For single VMs, custom data in the VM model cannot be updated, but for VMSS, you can update VMSS custom data via REST API (not applicable for PS or AZ CLI clients). When you update custom data in the VMSS model:

Existing instances in the VMSS will not get the updated custom data, only until they are reimaged.
Existing instances in the VMSS that are upgraded will not get the updated custom data.
New instances will receive the new custom data._

Having this as an optional setting would be good!

**Comment by tombuildsstuff** [comment]
hi @marcelkmfst 

Thanks for opening this issue.

Internally, whilst Terraform has to determine when instances are rolled - we only do this if the user has opted into this (which is the default behaviour) - if you need to roll these externally this can be done configuring the feature flag within the `features` block, as shown below:

```
provider "azurerm" {
  features {
    virtual_machine_scale_set {
      roll_instances_when_required = false # or true, which is the default if this block is omitted
    }
  }
}
```

As such I believe this functionality is already available, would you be able to take a look?

Thanks!

**Comment by marcelkmfst** [comment]
Thanks Tom, will test this!

**Comment by tombuildsstuff** [comment]
Closing since this functionality should already be available - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
