### ISSUE TITLE
Support for event grid system topic resources (az eventgrid system-topic)

### ISSUE THREAD

**Issue by chrisfraschetti** [terraform-providers/terraform-provider-azurerm#8293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for using Terraform to create Azure Event Grid System Topics appears to be missing.

### New or Affected Resource(s)

* azurerm_eventgrid_topic

### Potential Terraform Configuration

```hcl
resource "azurerm_eventgrid_systemtopic" "example" {
  name                = "my-eventgrid-systemtopic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  tags = {
    environment = "Production"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/event-grid/create-view-manage-system-topics-cli

**Comment by pdesjardins90** [comment]
I'm able to create an event subscription that uses a system topic, but the system topic is autogenerated by terraform and I have no way of accessing its resource ID elsewhere in my terraform template. I can't, for example, create a `azurerm_monitor_metric_alert` that points to it. 

Here's how I can create that subscription for now (with an IoT hub as source):

```hcl
resource "azurerm_eventgrid_event_subscription" "example" {
  name  = "example-event-subscription"
  scope = azurerm_iothub.example.id
  included_event_types = [
    "Microsoft.Devices.DeviceTelemetry"
  ]

  azure_function_endpoint {
    function_id                       = "${azurerm_function_app.example.id}/functions/some_python_module"
    max_events_per_batch              = 1
    preferred_batch_size_in_kilobytes = 64
  }

  depends_on = [
    azurerm_function_app.subscriber_function_app
  ]
}
```

The auto-generated Event Grid System Topic is called: `example-312b2006-4d3f-4d8b-9927-2eb1c9t01f8c`, but, as I said, there's no way to reference it in the rest of the template.

**Comment by jrauschenbusch** [comment]
@pdesjardins90 

> ..., but the system topic is autogenerated by terraform and I have no way of accessing its resource ID elsewhere in my terraform template. 

That's not 100% correct. The system topic is not created by Terraform (or the AzureRm Provider), it's created by Azure. With system and partner topics, Azure introduced a new abstraction layer which now allows better integration to other services like the before mentioned Azure Monitor.

Before this change, one has just created event subscriptions out of existing resources using the Events section, which under the hood maybe created those topics in the background, but there was no "visibility" of the them.

Now one can either create event subscriptions like before, resulting in the auto creation of a bound system topic, or create a system topic before and bind the event subscription "manually" to it.

This new APIs are currently only available within the preview namespace of the *azure-sdk-for-go*:
https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/eventgrid/mgmt/2020-04-01-preview/eventgrid

If i'll find the time i'll give it a try to implement the Terraform support for it.

**Comment by pdesjardins90** [comment]
Thank you for the clarification, this is all so confusing sometimes
