### ISSUE TITLE
[Feature Request] ability to define custom autoscale config for kusto clusters

### ISSUE THREAD

**Issue by brandonh-msft** [terraform-providers/terraform-provider-azurerm#8302]
Kusto clusters have the ability to define scaling characteristics. Currently, TF only supports the "optimized autoscale" feature, which doesn't satisfy all user needs.

TF should provide the ability to define custom autoscale rules:

![image](https://user-images.githubusercontent.com/20270743/91736932-48916800-eb63-11ea-9e6d-862f8fc36304.png)

As these are possible via ARM:

```json
{
	"type": "microsoft.insights/autoscalesettings",
	"apiVersion": "2014-04-01",
	"name": "[parameters('autoscalesettings_xxx_Autoscale_480_name')]",
	"location": "South Central US",
	"dependsOn": [
		"[resourceId('Microsoft.Kusto/Clusters', parameters('Clusters_xxx_name'))]"
	],
	"properties": {
		"profiles": [
			{
				"name": "Auto created scale condition",
				"capacity": {
					"minimum": "2",
					"maximum": "8",
					"default": "2"
				},
				"rules": [
					{
						"metricTrigger": {
							"metricName": "IngestionUtilization",
							"metricNamespace": "microsoft.kusto/clusters",
							"metricResourceUri": "[resourceId('Microsoft.Kusto/Clusters', parameters('Clusters_xxx_name'))]",
							"timeGrain": "PT1M",
							"statistic": "Average",
							"timeWindow": "PT1M",
							"timeAggregation": "Average",
							"operator": "GreaterThan",
							"threshold": 70,
							"dimensions": [],
							"dividePerInstance": false
						},
						"scaleAction": {
							"direction": "Increase",
							"type": "PercentChangeCount",
							"value": "50",
							"cooldown": "PT5M"
						}
					},
					{
						"metricTrigger": {
							"metricName": "IngestionUtilization",
							"metricNamespace": "microsoft.kusto/clusters",
							"metricResourceUri": "[resourceId('Microsoft.Kusto/Clusters', parameters('Clusters_xxx_name'))]",
							"timeGrain": "PT1M",
							"statistic": "Average",
							"timeWindow": "PT2M",
							"timeAggregation": "Average",
							"operator": "LessThan",
							"threshold": 50,
							"dimensions": [],
							"dividePerInstance": false
						},
						"scaleAction": {
							"direction": "Decrease",
							"type": "PercentChangeCount",
							"value": "50",
							"cooldown": "PT5M"
						}
					}
				]
			}
		],
		"enabled": true,
		"name": "[parameters('autoscalesettings_xxx_Autoscale_480_name')]",
		"targetResourceUri": "[resourceId('Microsoft.Kusto/Clusters', parameters('Clusters_xxx_name'))]"
	}
}
```

**Comment by tombuildsstuff** [comment]
hi @brandonh-msft 

Thanks for opening this issue :)

Taking a look through here I believe this functionality is available via [the `azurerm_monitor_autoscale_setting ` resource](https://www.terraform.io/docs/providers/azurerm/r/monitor_autoscale_setting.html) - would you be able to take a look and see if that works for you?Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by brandonh-msft** [comment]
Oo that's very interesting; I didn't think to look under azure monitor since that's not what I'm scaling. I'll have a look, thanks.

**Comment by brandonh-msft** [comment]
Doesn't look like this works as we thought it would, @tombuildsstuff :

```
Error: Error creating AutoScale Setting "adxcluster-autoscale" (Resource Group "xxx"): insights.AutoscaleSettingsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
```

No reason I can see for a 409; there is no existing autoscale setting so can't see why `CONFLICT` would be returned.

**Comment by tombuildsstuff** [comment]
@brandonh-msft the resource is correct, unfortunately the Monitor API pretty notoriously returns 409's - perhaps if you can post the config being used then @magodo can assist further since he's been working with it recently/has the most context?

**Comment by brandonh-msft** [comment]
Got it worked through, thanks. Even though it _looked_ like I'd deleted the autoscale config, it still showed up in the JSON section. 🤷🏻‍♂️
