### ISSUE TITLE
azurerm_container_group - Out of date constraint on 'ip_address_type' + 'identity'

### ISSUE THREAD

**Issue by gregberns** [terraform-providers/terraform-provider-azurerm#8307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the Terraform documentation [here](https://www.terraform.io/docs/providers/azurerm/r/container_group.html#ip_address_type) 

> Note: dns_name_label, identity and os_type set to windows are not compatible with Private ip_address_type

And notes in the code [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/container_group_resource.go#L74) 

> You cannot use a managed identity in a container group deployed to a virtual network.

Seem to claim that you cannot configure a Container Instance with a `ip_address_type` + `network_profile_id` + `identity`.

**This appears to be a limitation that existed in the preview, but may not exist now.**

The `ConflictsWith` condition was added Jun 22, 2019, which may have been during 'Preview'. The Azure Documentation that is linked no longer contains notes I could see regarding the constraint.

As of today, it appears that at least "You cannot use a managed identity in a container group deployed to a virtual network." does not appear to be a limitation any longer. In the example below, if the `identity` block is removed, then script is `apply`ed, it is possible to go into the Container Instance in Azure Portal and add a User Assigned Identity.

I haven't ever modified a terraform provider, but I'll try this later and remove the condition [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/container_group_resource.go#L77), but if any one else thats familiar with Container Instances I'd appreciate it.

```
provider "azurerm" {
  version                    = "2.21.0"
  skip_provider_registration = true
  features {}
}

provider "azuread" {
  version = "=0.7.0"
}

terraform {
  required_version = ">=0.12.29"
}

data "azurerm_virtual_network" "vnet" {
  name                = local.vnet_name
  resource_group_name = local.resource_group_name
}

data "azurerm_subnet" "subnet" {
  name                 = local.subnet_name
  virtual_network_name = data.azurerm_virtual_network.vnet.name
  resource_group_name  = local.resource_group_name
}
resource "azurerm_network_profile" "network" {
  name                = local.network_profile_name
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name

  container_network_interface {
    name = "examplecnic"

    ip_configuration {
      name      = "exampleipconfig"
      subnet_id = data.azurerm_subnet.subnet.id
    }
  }
}

resource "azurerm_container_group" "datasync" {
  name                = local.container_group_name
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
  os_type             = "Linux"

  ip_address_type = "private"
  # ERROR: "network_profile_id": conflicts with identity
  # See documentation notes: https://www.terraform.io/docs/providers/azurerm/r/container_group.html#ip_address_type
  #  > Note: dns_name_label, identity and os_type set to windows are not compatible with Private ip_address_type
  network_profile_id = azurerm_network_profile.network.id

  identity {
    type         = "UserAssigned"
    identity_ids = [data.azurerm_user_assigned_identity.mi.id]
  }
...
}
```

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume you're right. Hopes this [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8310) would be helpful.

**Comment by gregberns** [comment]
Tested locally and that allows the Container Instance to be deployed...But there do appear to be some issues when actually deploying. My container needs to get an AD OAuth token with Managed Identity and in the vNet it does not appear to be able to do that with this setting set (and thats the whole point of setting `identity`).

Jus found this:

> You can't use a managed identity in a container group deployed to a virtual network.

https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/container-instances/container-instances-virtual-network-concepts.md#other-limitations

**Comment by neil-yechenwei** [comment]
After confirmed with service team, they are not doing any validation to reject this request, but the statement in [document ](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/container-instances/container-instances-virtual-network-concepts.md#other-limitations) that these two are not supported at the same time currently is correct. So if you try to access the managed identity from the container group you created here it will not work. So the constraint cannot be removed from terraform.
