### ISSUE TITLE
Azure Firewall Network Rule collection Compatibility 

### ISSUE THREAD

**Issue by ShahradGH** [terraform-providers/terraform-provider-azurerm#8312]
https://www.terraform.io/docs/providers/azurerm/r/firewall_network_rule_collection.html

Whilst adhering to the requirements, I note that destination addresses in the rule block can be: "(Required) A list of destination IP addresses, IP ranges, or **FQDNs**."

When creating a rule with FQDN (so it can both utilise Firewall DNS (something I cant see how to configure in Terraform so had to do otherwise) and as a bi-product DNS Proxy) I get the error on compile:

![image](https://user-images.githubusercontent.com/4907864/91843645-02650300-ec4e-11ea-869b-5779aab09ea4.png)

`network.AzureFirewallsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AzureFirewallRuleInvalidIpAddressOrRangeFormat" Message="AzureFirewallRule RULENAME001: Invalid IP address value or range or Service Tag destination.subdomain.com.`

Code being attempted to run:

`  rule {
    name = "RULENAME001"

    source_addresses = [
      "192.168.0.1",
      "192.168.0.2",
    ]

    destination_addresses = [
      "destination.subdomain.com",
    ]

    destination_ports = [
      "22",
    ]

    protocols = [
      "TCP"
    ]
  }`

Can I confirm that terraform does support Network Rules by FQDN and perhaps be given a steer on how best to get a rule with the below logic implemented in the AzFirewall as a rule, as well as how best to implement turning on DNS Settings (pointed to Azure) and using DNS proxy:

Source IP1 -> Outbound -> destination.subdomain.com -> port random such as 64721

![image](https://user-images.githubusercontent.com/4907864/91843942-7ef7e180-ec4e-11ea-9f64-2ff2e2e2b68d.png)

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated and tested, seems dns proxy has to be enabled if you want to use fqdn per the [document](https://docs.microsoft.com/en-us/azure/firewall/fqdn-filtering-network-rules). After checked, seems [additionalProperties](https://github.com/Azure/azure-rest-api-specs/blob/ee23954e1987dd2688617c68213a9e80f94adcb1/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/azureFirewall.json#L566) can enable dns proxy but terraform hasn't support it. I assume it would be supported in near future but there is no ETA yet.

**Comment by ShahradGH** [comment]
> Thanks for opening this issue. After investigated and tested, seems dns proxy has to be enabled if you want to use fqdn per the [document](https://docs.microsoft.com/en-us/azure/firewall/fqdn-filtering-network-rules). After checked, seems [additionalProperties](https://github.com/Azure/azure-rest-api-specs/blob/ee23954e1987dd2688617c68213a9e80f94adcb1/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/azureFirewall.json#L566) can enable dns proxy but terraform hasn't support it. I assume it would be supported in near future but there is no ETA yet.

Hi,

Thank you for that confirmation!

As said I can import that config once it's made available, are we saying that therefore, due to the rationale above:

- FQDN filters rules also not supported as of yet but once the terraform version does, that it can continue to use the same.network rule properties but FQDNs will just work, or do they already work now??

**Comment by neil-yechenwei** [comment]
Yes. I assume terraform doesn't support fqdns rule for now. It would be supported in near future but there is no ETA yet.

**Comment by magodo** [comment]
@ShahradGH I just made a PR #8878 to support both the DNS setting in firewall and also the FQDNs in the network rule collection.
