### ISSUE TITLE
Setting minimumElasticInstanceCount for Azure Function premium plan

### ISSUE THREAD

**Issue by ajmal744** [terraform-providers/terraform-provider-azurerm#8313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Function Premium plan provides property for Always Ready instance called minimumElasticInstanceCount see this link https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan#always-ready-instances, we can currently do that by using AZURE CLI, but we do not have this in Terraform Azure Provider.

Only property exposed in Terraform is preWarmedInstanceCount https://www.terraform.io/docs/providers/azurerm/r/function_app.html#pre_warmed_instance_count

### New or Affected Resource(s)

* azurerm_2.6.0

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, seems this property hasn't supported by azure rest api so that terraform cannot support it yet. Suggest to file an issue on [rest api side](https://github.com/Azure/azure-rest-api-specs/issues) for this feature. Once it is supported on rest api, then terraform could also support it. Thanks.

**Comment by ajmal744** [comment]
@neil-yechenwei thanks for looking into this, will raise issue with MS

**Comment by shan0809** [comment]
Bumping this up to confirm if terraform now supports creation of Azure premium function.

**Comment by scuderig** [comment]
Is this still pending?
