### ISSUE TITLE
azurerm_security_center_contact return error with status code 201

### ISSUE THREAD

**Issue by csemio** [terraform-providers/terraform-provider-azurerm#8317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
terraform v0.13.0
azurerm v2.24.0
````

### Affected Resource(s)

* `azurerm_security_center_contact`

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_contact" "contact" {
  email                = var.security_settings.security_center.contact.email
  phone                = var.security_settings.security_center.contact.phone 
  alert_notifications  = var.security_settings.security_center.alert_notifications
  alerts_to_admins     = var.security_settings.security_center.alerts_to_admins
}
```

### Debug Output
```
Error creating Security Center Contact: security.ContactsClient#Create: Failure responding to request: StatusCode=201 
-- Original Error: autorest/azure: Service returned an error. Status=201 Code="Unknown" Message="Unknown service error"
Details=[
  {
    "etag":"\"11111111-1111-1111-1111-111111111111\"",
    "id":"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXXXXXXXX/providers/Microsoft.Security/securityContact/default1",
    "location":"West Europe","name":"default1","properties": 
    {
        "alertNotifications":"On",
        "alertsToAdmins":"On",
        "email":"xxxxx.xxxxx@domain.com",
        "phone":"+33628345678"
    },
    "type":"Microsoft.Security/securityContact"
}]
```

### Panic Output

No panic

### Expected Behavior

Contact is created

### Actual Behavior

Contact is created but apply failed

### Steps to Reproduce

1. `terraform apply`

**Comment by matthorgan** [comment]
Can confirm that I'm getting the same issue with `terraform v.12.26` and `azurerm v2.25.0`. I've tried multiple providers with the same results.

**Comment by SXiQTest** [comment]
Still happening on TF v0.13.2 with AzureRM v2.27.0.

**Comment by lflint** [comment]
Still happening on TF v0.13.2 with AzureRM v2.27.0.
