### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by cloudcomplex** [terraform-providers/terraform-provider-azurerm#8318]
When trying to upgrade from 2.17.0 to 2.25.0 we see the following error:
Error: Provider produced inconsistent final plan

```
When expanding the plan for
azurerm_role_assignment.master_id-keyvault-reader[0] to include new values
learned so far during apply, provider "registry.terraform.io/-/azurerm"
produced an invalid new value for .principal_id: was
cty.StringVal("hashvalue1"), but now
cty.StringVal("hashvalue2").
```
Re-applying does not reproduce this error, but produces one that looks related/dependent:
```
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal <principal id> does not exist in the directory <tenant-id>
```

**Comment by njuCZ** [comment]
@cloudcomplex could you please provide more context about this problem, such as the example script. for now, it's hard for us to diagnose the reason

**Comment by cloudcomplex** [comment]
The same terraform code that produced the 'bug in provider', produces the following on a subsequent run with 0 code changes:
`
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal <SOME PRINCIPAL ID> does not exist in the directory <OUR TENANT ID>."

  on roles-k8s.tf line 254, in resource "azurerm_role_assignment" "master_id-storage_role_scripts-sai-assign":
 254: resource "azurerm_role_assignment" "master_id-storage_role_scripts-sai-assign" {
`
Here is the portion of roles-k8s.tf I can share:
```
resource "azurerm_role_assignment" "master_id-storage_role_scripts-sai-assign" {
255   count              = length(var.zones)                                        
256   scope              = "${data.azurerm_subscription.primary.id}/resourceGroups/${var.backend_resource_group}/providers/Microsoft.Storage/sto    rageAccounts/${var.cluster_storage_account}"
257   role_definition_id = azurerm_role_definition.storage_role_scripts.id          
258   principal_id       = azurerm_linux_virtual_machine_scale_set.dp_master_scale[count.index].identity[0].principal_id
259 }                                                                               
260                                                                                 
261 resource "azurerm_role_assignment" "master_id-master_role-sai-assign" {         
262   count              = length(var.zones)                                        
263   scope              = "${data.azurerm_subscription.primary.id}/resourceGroups/${azurerm_resource_group.k8s.name}"
264   role_definition_id = azurerm_role_definition.master_role.id                   
265   principal_id       = azurerm_linux_virtual_machine_scale_set.dp_master_scale[count.index].identity[0].principal_id
266 }                 
```

**Comment by njuCZ** [comment]
@cloudcomplex I am sorry that it's hard for us to diagnose the real reason of this problem through this snippet. Could you please check the principal_id of those azurerm_linux_virtual_machine_scale_set ? it's possible to assign the role through the portal?

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if your able to provide a Terraform Configuration that reproduces this error then we can reopen this and take another look.

Thanks!
