### ISSUE TITLE
Support for Managed Boot diagnostic Storage Account

### ISSUE THREAD

**Issue by Dilergore** [terraform-providers/terraform-provider-azurerm#8319]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support to be able to set Managed Boot Diagnostic Storage Account for Virtual Machines

### New or Affected Resource(s)

- azurerm_windows_virtual_machine
- azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
boot_diagnostics = true #(without specifying storage_account_uri)
```

### References
https://docs.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#boot-diagnostics-storage-account

ARM Example:
```
"diagnosticsProfile": {
                    "bootDiagnostics": {
                        "enabled": true
                    }
}
```

**Comment by jimmfarley** [comment]
We need this yesterday!

**Comment by jimfarley1** [comment]
Yes, please add soon.

**Comment by severity1** [comment]
please add support for this.
