### ISSUE TITLE
VM extension dependency on previous extension when using count

### ISSUE THREAD

**Issue by PleaseStopAsking** [terraform-providers/terraform-provider-azurerm#832]
### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.1
+ provider.random v1.1.0

### Affected Resource(s)
azurerm_virtual_machine_extension

### Terraform Configuration Files
```hcl
resource "azurerm_virtual_machine_extension" "Server_DSC" {
    name = "${format("${var.customerProject}${var.environment}${var.machineAcronyms["Server"]}%02d", count.index + 1)}-dsc"
    location = "${var.location}"
    resource_group_name = "${azurerm_resource_group.rg.name}"
    virtual_machine_name = "${element(azurerm_virtual_machine.ArcGIS_Server.*.name, count.index)}"
    publisher = "Microsoft.Powershell"
    type = "DSC"
    type_handler_version = "${var.dsc_extension}"
    auto_upgrade_minor_version = true
    depends_on = ["azurerm_storage_share.fileShare"]
    count = "${var.Server_Specs["Number_of_Machines"]}"
    settings = <<SETTINGS
    {
        "configuration": {
	    "url": "${var.resourceStore["fileShareUrl"]}${var.resourceStore["dscArchiveName"]}${var.azureCredentials["storageKey"]}",
	    "function": "contenthostingha",
	    "script": "contenthostingha.ps1"
	},
	"configurationArguments": {
	    "ExternalDNS": "${var.externalDNS}",
	    "NumberOfMachines": "${var.Server_Specs["Number_of_Machines"]}",
	    "AzureFileUrl": "azurerm_storage_share.fileShare.url",
	    "AzureFileShareKey": "${azurerm_storage_account.storageAccount.secondary_access_key}"
        }
    }
    SETTINGS
    protected_settings = <<PROTECTED_SETTINGS
    {
        "configurationArguments": {
	    "RunAsAccountCredential": {
	        "UserName": "${var.RunAsAccountCredentials["Username"]}",
		"Password": "${var.RunAsAccountCredentials["Password"]}"
            }
        }
    }
    PROTECTED_SETTINGS
}
```

### Expected Behavior
There should be a way to set the depends_on property to force the vm extension to wait until the previous one is completed before moving on to the next count in the index.

### Actual Behavior
The extensions are all deployed together. 

### Important Factoids
If the machines were not dependent on each other, this would not be an issue but in some scenarios, we should have the functionality to force the extensions to be created in serial instead of parrallel.

ARM templates provided this functionality as of now with the following syntax.
```
"copy": {
    "name": "exampleCopy",
    "count": 4,
    "mode": "serial",
}
```

**Comment by tombuildsstuff** [comment]
hi @PleaseStopAsking 

Thanks for opening this issue :)

This is current possible using independent dependent resources with a `depends_on` as shown below:

```
resource "azurerm_virtual_machine_extension" "first" {
  name = "first"
  # ...
}

resource "azurerm_virtual_machine_extension" "second" {
  name = "second"
  # ...
  depends_on = ["azurerm_virtual_machine_extension.first"]
}

resource "azurerm_virtual_machine_extension" "third" {
  name = "third"
  # ...
  depends_on = ["azurerm_virtual_machine_extension.second"]
}
```

The `count` parameter used in the configuration posted above is a metaparameter from Terraform Core which creates these resources independently. Whilst having these split out (as above) works, I can see the desire to achieve this with the `count` parameter and some kind of override to be able to say "deploy these serially". Given this enhancement would need to be added to Terraform Core -  would you mind [re-opening this issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues)? (whilst I can do this for you, you'll be subscribed to notifications this way 😄)

Thanks!
