### ISSUE TITLE
Invalid LoadBalancer "Basic" SKU defaulted and allowed when creating AKS cluster with multiple node pools

### ISSUE THREAD

**Issue by shoop** [terraform-providers/terraform-provider-azurerm#8324]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.29 / AzureRM 2.14.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "aks-${var.cluster_name}"
  location            = azurerm_resource_group.k8s.location
  resource_group_name = azurerm_resource_group.k8s.name
  dns_prefix          = "dns-${var.cluster_name}"
  kubernetes_version  = var.kubernetes_version
  node_resource_group = "${azurerm_resource_group.k8s.name}-aks"

  # default node pool definition (standby node pool, real used nodepool will be describe below in the azurerm_kubernetes_cluster_node_pool section)
  # Will be used to shutdown all the worker nodes and just keep alive this one nodepool with an smaller vm to save money
  default_node_pool {
    name            = "agentpool"
    node_count      = 1
    vm_size         = "Standard_DS2_v2"
    os_disk_size_gb = 128
    type            = "VirtualMachineScaleSets" 
    node_labels     = {
      "nodetype" = "keep-alive-node"
    }
  }
  
  service_principal {
    client_id     = var.client_id
    client_secret = var.client_secret
  }
  
  role_based_access_control {
    enabled = true
  }
    
  tags = {
    Owner = var.owner
    Maintainer = var.maintainer
    CreatedBy = var.createdBy
  }

  addon_profile {
    aci_connector_linux {
      enabled = false
    }

    azure_policy {
      enabled = false
    }

    http_application_routing {
      enabled = false
    }

    kube_dashboard {
      enabled = true
    }

    oms_agent {
      enabled = false
    }
  }
}

# definition of the real worker node pool
resource "azurerm_kubernetes_cluster_node_pool" "k8s" {
  name                  = "worker"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.k8s.id
  vm_size               = var.vm_size
  node_count            = var.node_count
  os_disk_size_gb       = 128
  mode                  = "User"
  node_labels           = {
    "nodetype" = "worker-node" 
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

An error to be generated at terraform plan time, due to the fact that the default load balancer SKU is "Basic", and this is not supported in Azure for a cluster with multiple node pools: https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#before-you-begin

Note the absence of `network_profile.load_balancer_sku` in the configuration above.

Note as well that clusters created by hand in the portal automatically get LoadBalancer SKU "Standard", hence they do not exhibit this problem.

### Actual Behavior

The cluster got created with load balancer SKU "Basic". Afterwards deployments to the cluster failed. We observer 50x errors in the tunnel-front and metrics-server.

### Steps to Reproduce

1. `terraform apply` with the above configuration
2. deploy something, e.g. using helm, to the cluster
3. observe 50x errors

### Important Factoids

Using Azure public cloud. Attached is an (anonymized) exported ARM template from a terraform-created cluster with the incorrect LoadBalancer SKU.

### References

N/A

**Comment by shoop** [comment]
[anonymized-template.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5161900/anonymized-template.zip)

**Comment by njuCZ** [comment]
for azurerm provider, terraform plan only checks some validation rule for single field level. For example, it should be a specific string, it should be a specific kind resource id. We don't check complicated backend logic.

The reason why we don't do this in terraform side is:
1. it's common that the backend service have a lot of validation logic, it's hard for us to know those rules
2. it's common that the backend service team will change their validation logic, it's hard for us to know and keep the same rule.

so for complicated logic validation, we rely on the error message from backend service. Hopes you could understand the situation, thanks very much

**Comment by shoop** [comment]
hi @njuCZ , that is clear, thank you. Would you agree that this should then be filed as a bug with AzureRM which allows this instantiation without an error message from the backend?

**Comment by njuCZ** [comment]
@shoop As you said, it's a backend restriction for aks that basic sku does not support multiple node pool. I don't think it's a bug. If you want to provision a kubernetes cluster with load balancer SKU "standard", you could try following script:
```
resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestaks"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "acctestaks"

  default_node_pool {
    name           = "default"
    node_count     = 2
    vm_size        = "Standard_DS2_v2"
    vnet_subnet_id = var.subnet_id
  }

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    network_plugin    = "azure"
    load_balancer_sku = "Standard"
  }
}
```

**Comment by shoop** [comment]
Thanks for the response. Closing this issue.
