### ISSUE TITLE
"http_application_routing_zone_name" of resource azurerm_kubernetes_cluster is empty

### ISSUE THREAD

**Issue by luc1f4** [terraform-providers/terraform-provider-azurerm#8326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.25
AzureRM  2.23.0
### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl

resource "azurerm_kubernetes_cluster" "this" {
  count   = var.common_dev_rc ? 0 : 1
  name                = local.component_names["name"]
  location            = var.region
  resource_group_name = azurerm_resource_group.this.0.name
  tags                = local.tags
  
  dns_prefix         = "dns-${local.component_names["name"]}"
  enable_pod_security_policy = false
  kubernetes_version = var.k8s_version

   default_node_pool {
    name                = "default"
    node_count      = var.vm_count
    vm_size             = var.vm_size
    enable_auto_scaling = var.enable_auto_scaling

    min_count = var.vm_count
    max_count = var.vm_maxcount

    os_disk_size_gb = 30
    vnet_subnet_id  = azurerm_subnet.this.0.id
    type                   = "VirtualMachineScaleSets"
  }

  addon_profile {
    http_application_routing {
      enabled = true
    }
  }
  
  network_profile {
    network_plugin = "azure"
    load_balancer_sku = "Basic"
  }
  
  service_principal {
    client_id     = var.aks_sp_client_id
    client_secret = var.aks_sp_client_secret
  }

  linux_profile {
    admin_username = "linux"

    ssh_key {
      key_data = var.aks_ssh_public_key
    }
  }

  role_based_access_control {
    enabled = false
  }

  lifecycle {
    ignore_changes = [
      windows_profile,
    ]
  }
}


output "dnszone" {
  value = azurerm_kubernetes_cluster.this.0.addon_profile[0].http_application_routing.0.http_application_routing_zone_name
}
```
### Debug Output

Tried to solve the data ressource in "terraform console". The output is also empty

> azurerm_kubernetes_cluster.this.0.addon_profile[0].http_application_routing.0.http_application_routing_zone_name
{
  "enabled" = true
  "http_application_routing_zone_name" = ""
}

### Expected Behavior

The correct zone name should be printed out

### Actual Behavior

http_application_routing_zone_name is empty. Yesterday it worked as usual. This issue started beginning today.

**Comment by tombuildsstuff** [comment]
hi @luc1f4 

Thanks for opening this issue.

To be able to look into this we're going to need a Terraform Configuration showing how the AKS Cluster is provisioned - would you mind updating the description above to include that?

Thanks!

**Comment by wandrew26** [comment]
I assume, that the naming of the properties have changed on azure side. 😞 
The [microsoft documentation](https://docs.microsoft.com/en-us/azure/aks/http-application-routing) states that you can get the value with the query:

`az aks show --resource-group myResourceGroup --name myAKSCluster --query addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName -o table`

But it doesn't seem to be valid since a few days. 
Callling: az aks show --resource-group xxxx --name xxxx --query addonProfiles.**httpapplicationrouting** will output:

`{
  "config": {
    "httpapplicationroutingzonename": "xxxxxxxxxx.yyyyyyyyy.aksapp.io"
  },
  "enabled": true,
  "identity": null
}`

They using lowercase now instead of camel case. 😭 Which leads to a breaking change on tf side.

**Comment by luc1f4** [comment]
I created a Pull Request with the changes to catch this issue: 
https://github.com/terraform-providers/terraform-provider-azurerm/pull/8387

Can somebody review this?
Thanks.

**Comment by robbiezhang** [comment]
Hi all, this is Robbie from the AKS team. Sorry about the breaking change. We're working on a hotfix to revert it back to the previous behavior - preserve the casing from the input. Please kindly stay tuned.

**Comment by wandrew26** [comment]
Microsoft deployed a hotfix, issue can be closed. @luc1f4

**Comment by robbiezhang** [comment]
The hotfix is rolled out to all the regions last week. For the new clusters, the casing of the addon name and addon config names are preserved. for the existing cluster, you need to re-enable the addon with the desired casing to fix the issue.
