### ISSUE TITLE
ACI deployment into VNET: Support managed identities

### ISSUE THREAD

**Issue by flobeier** [terraform-providers/terraform-provider-azurerm#8327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment managed identities for an Azure Container Instances group aren't supported if it shall be deployed into a VNET (see https://github.com/terraform-providers/terraform-provider-azurerm/issues/6186#issuecomment-604176567). However, they can be added manually after the group was created, so apparently this configuration is supported by the Azure platform.

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

```hcl
resource "azurerm_container_group" "example" {
    name = "examplegroup"
    location = "eastus"
    resource_group_name = "example"
    ip_address_type = "Private"
    network_profile_id = azurerm_network_profile.example.id
    os_type = "Linux"

    identity {
      type = "SystemAssigned"
    }

    container {
        name = "example"
        image = "nginx:alpine"
        cpu = 0.25
        memory = 0.1

        # Apparently one port needs to be exposed, even though no public IP address is used
        # (see https://github.com/terraform-providers/terraform-provider-azurerm/issues/1697
        ports {
            port = 443
            protocol = "TCP"
        }
    }
}
```

### References

* #6186

**Comment by tombuildsstuff** [comment]
hi @flobeier 

This got asked recently in #8307 and [after reaching out to the service team](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8307#issuecomment-685262566) it appears this functionality is unsupported - insofar as it'll provision but won't work.

Whilst the API itself should be rejecting this configuration as invalid - unfortunately it's not - can you confirm if it's possible to obtain the identity via the Managed Identities API from a container inside a Virtual Network? If so we should be able to take another look here - but unfortunately at the moment it sounds like this behaviour is unsupported within the Azure API, and so there's not a great deal we can do here.

Thanks!

**Comment by flobeier** [comment]
Hi @tombuildsstuff 

Sorry, I didn't see #8307 . I can confirm that one can add a managed identity to the Container Instances Group but trying to use it in a container (I tried `az login --identity --username <UserID>` with a user assigned managed identity) fails, the command just hangs with no output.

**Comment by tombuildsstuff** [comment]
hey @flobeier 

Apologies for the delayed response here.

As you've confirmed this fails via the CLI and isn't supported via #8307 - I'm going to close this issue for the moment - but should this be supported by the service in the future we can reopen this and take another look.

Thanks!
