### ISSUE TITLE
Add Private Endpoint Settings to Azure SignalR Service

### ISSUE THREAD

**Issue by jongio** [terraform-providers/terraform-provider-azurerm#8328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The SignalR Service block is missing the Private endpoint setting option
https://www.terraform.io/docs/providers/azurerm/r/signalr_service.html

![image](https://user-images.githubusercontent.com/2163001/92017326-7237c400-ed08-11ea-9473-006eb8e78869.png)

### New or Affected Resource(s)

* azurerm_signalr_service

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

azsdke2e

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume you have to use "azurerm_private_endpoint" resource to implemented this scenario.

**Comment by tombuildsstuff** [comment]
👋 

As @neil-yechenwei has mentioned this should be possible using [the `azurerm_private_endpoint` resource](https://www.terraform.io/docs/providers/azurerm/r/private_endpoint.html) I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
