### ISSUE TITLE
Support for Log Analytics destination for `extended_auditing_policy` setting for `azurerm_sql_server`

### ISSUE THREAD

**Issue by dhirschfeld** [terraform-providers/terraform-provider-azurerm#8338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* `azurerm_sql_server`

### References

* https://docs.microsoft.com/en-us/azure/azure-sql/database/auditing-overview#audit-log-analytics-destination

Related?
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/7486

**Comment by mybayern1974** [comment]
hi  @dhirschfeld 

Thanks for opening this issue !

Given this appears to be a duplicate of #7486- rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7486 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Comment by paranoob** [comment]
Hi @mybayern1974 

Its not the same issue, currently Terraform only supports sending Azure SQL Audit logs to a storage account, while in the Azure portal we now have the options of sending them to a Log Analytic workspace.  I think the option is in preview only though.

Regards,

**Comment by dhirschfeld** [comment]
@mybayern1974 - paranoob is correct, this is a different issue requesting the ability to send the logs to a *Log Analytics Workspace*.

#7486 is about what is required to give the server identity the right permissions to write to a *Storage Account*.

I think if *this* feature were implemented it would neatly side-step the problem in #7486 as the identity would no longer need permissions to a storage account. It wouldn't help people who actually wanted to write their logs to a storage account though so these are two independent issues.

As such I think this should be re-opened.

NB: As paranoob notes (and as mentioned in the linked docs) this feature is currently in preview.

**Comment by mybayern1974** [comment]
Thank you @paranoob , @dhirschfeld for calling out. Reopen to track this ask.

**Comment by yupwei68** [comment]
Hi @dhirschfeld , thanks for opening this issue. Would you mind subscribing to https://github.com/terraform-providers/terraform-provider-azurerm/issues/6849 to get any updates from our side?

**Comment by mybayern1974** [comment]
hi @dhirschfeld, @paranoob , then is it ok that we close this issue for dup and you could follow #6849?

**Comment by dhirschfeld** [comment]
> is it ok that we close this issue

Sure. I thought that `mssql-server` was a different thing to `sql-server` but am I right in now thinking that `mssql-server` is a new api for spinning up the same infrastructure and `sql-server` is the old/deprecated api?

**Comment by yupwei68** [comment]
@dhirschfeld You're right. `mssql_server` is a more advanced version of `sql_server`. Currently, `mssql_server` supports more features than `sql_server`. And if we'll add new features and new resources, we'll add them in `mssql` package.

**Comment by dhirschfeld** [comment]
Thanks for the confirmation @yupwei68 :+1:

I eventually came to that conclusion but it would be very useful for future users if the documentation actually stated that:
  1. They refer to the same infrastructure
  2. `azurerm_mssql_server` is the preferred api to use for all new projects

**Comment by dhirschfeld** [comment]
Closing in favour of #6849
