### ISSUE TITLE
"azurerm_storage_share_directory" fails to create folder with two hyphens in name

### ISSUE THREAD

**Issue by mrmatimba** [terraform-providers/terraform-provider-azurerm#8341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13
AzureRM 2.25.0

### Affected Resource(s)

* `azurerm_storage_share_directory`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_share_directory" "folder01" {

  name                 = "test-folder-1"
  share_name           = var.share_name
  storage_account_name = var.storage_account_name
}
```

### Expected Behavior

Folder "test-folder-1" is created

### Actual Behavior
Error output:

Error: name must contain only uppercase and lowercase alphanumeric characters, numbers and hyphens. It must start and end with a letter and end only with a number or letter and can only be nested one level
   on code/iac/sftp/main.tf line 57, in resource "azurerm_storage_share_directory" "folder01":
   57: resource "azurerm_storage_share_directory" "folder01" {

### Steps to Reproduce

1. `terraform apply`

### References

Probably caused due to new regex pattern from #7382 for validating folder names
* #7382

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Hopes this [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8366) would be helpful.

**Comment by mrmatimba** [comment]
Hi @neil-yechenwei ,

Looks totally fine. Thanks for the quick help!
