### ISSUE TITLE
delete azurerm_key_vault_secret and add with same name retains original value

### ISSUE THREAD

**Issue by derek-burdick** [terraform-providers/terraform-provider-azurerm#8347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.0

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
resource random_password pw {
 length = 16
}

resource azurerm_key_vault_secret shared_secret {
  name         = "test-key-value"
  value        = random_password.pw.result
  key_vault_id = var.keyvault_id
}

output pw {
 value = random_password.pw.result
}

output kvpw {
 value = azurerm_key_vault_secret.shared_secret.value
}
```

### Expected Behavior

Terraform apply, followed by Terraform destroy, followed by terraform apply, should show the latest value in the azure keyvault key.

### Actual Behavior

The first secret added is in the value in  azure key vault key.

### Steps to Reproduce

1. terraform apply
2. terraform destroy
3. terraform apply 

### Important Factoids

The value of the secret is generated using a random provider.

### References

* #0000

**Comment by njuCZ** [comment]
@derek-burdick I have tried to reproduce this issue. It seems after the second teraform apply, the portal still shows the first version secret. After a while(several seconds), refresh the portal and we could find the version for the secret is changed, and it contains the right value. So I believe it's a bug for portal, but not an issue for terraform.

**Comment by tareks** [comment]
Is this because soft-delete is enabled on the keyvault resulting in recovery of the secret on the second apply? 

Have had similar issues and have only been able to get around that by running a purge after terraform destroy to make sure it's a clean slate. Unfortunately, this approach seems to have started failing a few days ago because it appears that soft deletion is not as fast as one would expect resulting in the deleted secret not showing up as "deleted" fast enough.

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but as @tareks has mentioned there's a larger question regarding Soft Delete here, which is being tracked in #5659 - as such would you mind subscribing to that issue for updates?

Thanks!
