### ISSUE TITLE
Can't enable "Allow Azure services and resources to access this server" for SQL Server

### ISSUE THREAD

**Issue by nadworny** [terraform-providers/terraform-provider-azurerm#8352]
### Terraform (and AzureRM Provider) Version
Terraform v0.13.0
+ provider registry.terraform.io/-/azuread v0.11.0
+ provider registry.terraform.io/-/azurerm v2.24.0
+ provider registry.terraform.io/-/kubernetes v1.12.0
+ provider registry.terraform.io/-/random v2.3.0
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.24.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/random v2.3.0

### Affected Resource(s)

* `azurerm_mssql_server`
* `azurerm_sql_firewall_rule`

### Terraform Configuration Files

```
resource "azurerm_mssql_server" "project" {
  name = format("%s-%s-db-srv", var.project, terraform.workspace)
  location = azurerm_resource_group.project.location
  resource_group_name = azurerm_resource_group.project.name
  version = "12.0"
  administrator_login = var.project
  administrator_login_password = random_string.sql_server_admin_pwd.result
  public_network_access_enabled = false
}

resource "azurerm_sql_firewall_rule" "allow_azure_services" {
  name = "AllowAzureServices"
  resource_group_name = azurerm_resource_group.project.name
  server_name = azurerm_mssql_server.project.name
  start_ip_address = "0.0.0.0"
  end_ip_address = "0.0.0.0"
}
```

### Debug Output

```
azurerm_sql_firewall_rule.allow_azure_services: Creating...

Error: Error creating SQL Firewall Rule AllowAzureServices (Resource Group starlight-sit-rg, Server starlight-sit-db-srv): sql.FirewallRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: json: c
annot unmarshal array into Go struct field serviceError2.details of type map[string]interface {}

  on network.tf line 13, in resource "azurerm_sql_firewall_rule" "allow_azure_services":
  13: resource "azurerm_sql_firewall_rule" "allow_azure_services" {
```

### Expected Behavior

"Allow Azure services and resources to access this server" should be enabled on the server. When I enable the public access, the terraform apply is successful but this is not what I want to achieve. In the portal I can enable both "Allow Azure services and resources to access this server" and "Deny public network access" so I would like to do the same using your provider.

### Actual Behavior

Firewall rule won't be created and therefore "Allow Azure services and resources to access this server" is not enabled.

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume you have to use azurerm_private_endpoint to implement the scenario what you described. 
The instruction from azure portal:
![image](https://user-images.githubusercontent.com/19754191/92349953-23c06600-f10a-11ea-95b1-daaf814a6c65.png)

TF config as example:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-sqlfw-test01"
  location = "eastus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_space       = ["10.5.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "acctestsnetendpoint-test01"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.5.2.0/24"]

  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_mssql_server" "test" {
  name                         = "acctestsqlservertest01"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "ccddminiyutator"
  administrator_login_password = "thisAsBog12"
  public_network_access_enabled = true
}

resource "azurerm_private_dns_zone" "test" {
  name                = "privatelink.sql.database.azure.com"
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctest-privatelink-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  subnet_id           = azurerm_subnet.test.id

  private_service_connection {
    name                           = "acctest-privatelink-mssc-test01"
    private_connection_resource_id = azurerm_mssql_server.test.id
    subresource_names              = ["sqlServer"]
    is_manual_connection           = false
  }
}

resource "azurerm_sql_firewall_rule" "test" {
  name                = "acctestsqlservertest01"
  resource_group_name = azurerm_resource_group.test.name
  server_name         = azurerm_mssql_server.test.name
  start_ip_address    = "0.0.0.0"
  end_ip_address      = "255.255.255.255"
}
```

**Comment by nadworny** [comment]
Thanks @neil-yechenwei for an answer. I already have a private endpoint setup but I didn't think it's relevant and that why I didn't include it here. Still I want both ("Allow Azure services and resources to access this server" & "Deny public network access") to be enabled and with an example from above, when you set as per documentation the both start and end IP's of the firewall rule to 0.0.0.0, the creation of the FW rule fails.

**Comment by neil-yechenwei** [comment]
I assume it's related with private endpoint. If you want enable both them, you have to enable private endpoint otherwise "Deny public network access" is not allowed to set. Above warning in snapshot has described it. After checked, terraform's behavior is the same with azure portal.

**Comment by nadworny** [comment]
But I have private endpoint already enabled for it so I think your suggestion won't work unless you have tried it out on your own already?

**Comment by neil-yechenwei** [comment]
I assume both ("Allow Azure services and resources to access this server" & "Deny public network access") cannot be enabled together. Even if azure portal also cannot enable them together.

The repro steps on azure portal:
1. Click yes for "Deny public network access".
![image](https://user-images.githubusercontent.com/19754191/92548812-8b9dba80-f28a-11ea-9c0c-61f2ce4288be.png)
2. Click yes for "Allow Azure services and resources to access this server"
![image](https://user-images.githubusercontent.com/19754191/92548843-9b1d0380-f28a-11ea-90f3-6ee468b1f497.png)
3. Click "save" button
![image](https://user-images.githubusercontent.com/19754191/92548862-a7a15c00-f28a-11ea-86c4-a9b7fe09266c.png)
4. Refresh azure portal.
![image](https://user-images.githubusercontent.com/19754191/92548950-d15a8300-f28a-11ea-8fa7-b8d0fb40f7f6.png)

**Comment by nadworny** [comment]
I can so I'm not sure why you can't:
![image](https://user-images.githubusercontent.com/1425919/92587200-9f035280-f297-11ea-9ddf-9dbd321c86c3.png)

**Comment by neil-yechenwei** [comment]
Did you refresh Azure portal after clicked "save" button?

**Comment by nadworny** [comment]
Sorry I have to say it but this is really a silly suggestion. Of course I did refresh, multiple times.

On top of that, when the "Allow Azure services..." is set to "No", my services running within AKS can't access the database so that's why I'm trying to enable it. After setting to "Yes" the services can access the database.

**Comment by neil-yechenwei** [comment]
For some reason, the "Allow Azure services and resources to access this server" would be rollback to false after refreshed portal. Could you have a try below tfconfig that can enable both them?
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-sqlfw-test02"
  location = "westus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet-test02"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_space       = ["10.5.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "acctestsnetendpoint-test02"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.5.2.0/24"]

  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_mssql_server" "test" {
  name                         = "acctestsqlservertest02"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "ccddminiyutator"
  administrator_login_password = "thisAsBog12"
  public_network_access_enabled = false
}

resource "azurerm_private_dns_zone" "test" {
  name                = "privatelink.sql.database.azure.com"
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctest-privatelink-test02"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  subnet_id           = azurerm_subnet.test.id

  private_service_connection {
    name                           = "acctest-privatelink-mssc-test02"
    private_connection_resource_id = azurerm_mssql_server.test.id
    subresource_names              = ["sqlServer"]
    is_manual_connection           = false
  }
}

resource "azurerm_sql_firewall_rule" "test" {
  name                = "acctestsqlservertest03"
  resource_group_name = azurerm_resource_group.test.name
  server_name         = azurerm_mssql_server.test.name
  start_ip_address    = "0.0.0.0"
  end_ip_address      = "0.0.0.0"
}
```
![image](https://user-images.githubusercontent.com/19754191/92893830-9d2ec000-f44c-11ea-8659-e1de39d553fe.png)

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment, but please let us know if the solution proposed above doesn't work for you and we'll take another look.

Thanks!

**Comment by nadworny** [comment]
Sorry for getting back to you so late... 

I've just taken the tf code from @neil-yechenwei and deployed it without any changes. I'm getting the same error as above:
```
Error: Error creating SQL Firewall Rule acctestsqlservertest03 (Resource Group acctestRG-sqlfw-test02, Server acctestsqlservertest02): sql.FirewallRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Er
ror: json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface {}

  on test.tf line 55, in resource "azurerm_sql_firewall_rule" "test":
  55: resource "azurerm_sql_firewall_rule" "test" {
```

Not sure how it could work on your side. Which tf version are you using?
```
terraform version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.35.0

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
```
