### ISSUE TITLE
Link Azure App-Service to Hybrid-Connection fails if its on separate Resource Groups

### ISSUE THREAD

**Issue by GelbB** [terraform-providers/terraform-provider-azurerm#8354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
azurerm_app_service_hybrid_connection

### Expected Behavior

I have got the code below that creates a Hybrid-connection, an App-Service and then trying to link them together by using a resource that was released in version 2.14.0, called `azurerm_app_service_hybrid_connection`. the difference between my example and the one provided by [Terraform](https://www.terraform.io/docs/providers/azurerm/r/app_service_hybrid_connection.html), is that the Hybrid-Connection and the App-Service are deployed on separate Resource Groups in Azure.  
An interesting point to note is that, the resource has an argument called `resource_group_name`, which is expecting the name of the resource group where the App-Service is deployed, but there is no argument to provide the RG  where the Hybrid-Connection is deployed. Seems like the code is assuming they are on the same RG. 
I'm expecting the code to recognize the RG where the HyCo is deployed, because it can extract that information from it's `Id` field

```
resource "azurerm_resource_group" "appservice" {
  name     = "AppServiceRG"
  location = "West Europe"
}

resource "azurerm_resource_group" "hyco" {
  name     = "HyCoRG"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "example" {
  name                = "exampleAppServicePlan1"
  location            = azurerm_resource_group.appservice.location
  resource_group_name = azurerm_resource_group.appservice.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "example" {
  name                = "exampleAppService1"
  location            = azurerm_resource_group.appservice.location
  resource_group_name = azurerm_resource_group.appservice.name
  app_service_plan_id = azurerm_app_service_plan.example.id
}

resource "azurerm_relay_namespace" "example" {
  name                = "exampleRN1"
  location            = azurerm_resource_group.hyco.location
  resource_group_name = azurerm_resource_group.hyco.name

  sku_name = "Standard"
}

resource "azurerm_relay_hybrid_connection" "example" {
  name                 = "exampleRHC1"
  resource_group_name  = azurerm_resource_group.hyco.name
  relay_namespace_name = azurerm_relay_namespace.example.name
  user_metadata        = "examplemetadata"
}

resource "azurerm_app_service_hybrid_connection" "example" {
  app_service_name    = azurerm_app_service.example.name
  resource_group_name = azurerm_resource_group.appservice.name
  relay_id            = azurerm_relay_hybrid_connection.example.id  # Actual value: "/subscriptions/mySubscription/resourceGroups/HyCoRG/providers/Microsoft.Relay/namespaces/exampleRN1/hybridConnections/exampleRHC1" 
  hostname            = "testhostname.example"
  port                = 8080
  send_key_name       = "exampleSharedAccessKey"
}
```

### Actual Behavior

When running the `Apply changes` cmd, I get an error `unable to List Access Keys for Namespace "myNamespace" (Resource Group: AppServiceRG )`. The code is searching for the namespace in the AppserviceRG, not in the namespace RG. 
But the link is YES created. and the state file contains that link information. even though the cmd failed. 
But the link doesn't connect, because it failed to receive an access key from the Relay.

**Comment by njuCZ** [comment]
@GelbB thanks for pointing this issue. It's actually a bug. I will try to submit a PR to fix it soon
