### ISSUE TITLE
Terraform plan fails when behind corporate proxy

### ISSUE THREAD

**Issue by jeevesdavid** [terraform-providers/terraform-provider-azurerm#8358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform plan -v

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.23.0

### Affected Resource(s)

It does not matter what resource is being provisioned is. It always happens.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
provider "azurerm" {
  version = "2.23.0"
  subscription_id = var.subscription_id
  skip_provider_registration  = "true"
  features {}
}

#https://www.terraform.io/docs/providers/azurerm/r/storage_account.html

resource "azurerm_storage_account" "storage" {
  name                     = var.tf_state_storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "GZRS"

  tags = {
        organization = var.organization_id
        product = var.prod_id
        subproduct = var.sub_prod_id
        environment = var.environment
  }

}

resource "azurerm_storage_container" "container" {
  name                  =  var.tf_state_container_name
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}

### Expected Behavior

Terraform plan command should run successfully and output the plan.

### Actual Behavior

Error: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: WARNING: Connection verification disabled by environment variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warn

### Steps to Reproduce

1. Disable certificate verification as this has to be run behind a corporate proxy.
2. `terraform plan`

### Important Factoids

Terraform is run behind a corporate proxy.

Azure CLI commands work fine behind the proxy as long as certificate verification is disabled.

Authentication used is managed service authentication.

Terraform init worked fine.

### References

https://discuss.hashicorp.com/t/terraform-authenticating-using-azure-cli-when-behind-proxy/13708

**Comment by tonedefdev** [comment]
I work behind a proxy and I have no issues with the Azure CLI. In order to get Azure CLI working I have to set:
`export HTTPS_PROXY=<your_corp_proxy>` and then it works. If you're on Windows `$env:HTTPS_PROXY=<your_corp_proxy>`

**Comment by jeevesdavid** [comment]
I got azure cli to work by setting these variables and disabling certificate verification. So it is only terraform plan/apply that does not work.

**Comment by magodo** [comment]
@jeevesdavid  Thank you for submitting this!

Having went through the code and finding that this is a bug in the auth logic in another repo, where I have submit a fix to address it. Since it is a dependency to this provider codebase, please anticipate another PR for dependency update, which might need some other investigation as it involves some other changes.

**Comment by jeevesdavid** [comment]
@magodo ,

Thanks for the update! Does this bug manifest only when a proxy is involved. I had no issues in another environment without the corporate proxy.

**Comment by magodo** [comment]
@jeevesdavid Yes, the issue derives from (incorrectly) regarding non-empty output at stderr after running az command as an error. The output in stderr in this case is actually a warning.
