### ISSUE TITLE
User-Agent does not report terraform CLI version

### ISSUE THREAD

**Issue by paultyng** [terraform-providers/terraform-provider-azurerm#836]
### Expected Behavior
The `User-Agent` header should report the CLI version, not the vendored library version.

### Actual Behavior
The `User-Agent` header sends the vendored version of Terraform

This requires a change in core first to pass the CLI version to the provider process, once completed we can update this provider to use that value in the `User-Agent` string.

See hashicorp/terraform#17340

**Comment by tombuildsstuff** [comment]
Taking a look through it appears we now pass through both the version of Terraform Core being used from the protocol (if available, defaulting to 0.11-compatible otherwise) - and the version of the Plugin SDK being used; as such I'm going to close this issue for the moment.
