### ISSUE TITLE
azurerm_kubernetes_cluster kubernetes version is not defaulting to latest version if kubernetes_version is not set. 

### ISSUE THREAD

**Issue by VipinAgarwal** [terraform-providers/terraform-provider-azurerm#8362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azuread v1.0.0
+ provider.azurerm v2.26.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "aks"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  dns_prefix          = "someapplication"
  default_node_pool {
    name                  = "default"
    vnet_subnet_id        = azurerm_subnet.subnet.id
    type                  = "VirtualMachineScaleSets"
    availability_zones    = ["1", "2", "3"]
    enable_auto_scaling   = true
    enable_node_public_ip = false
    max_count             = 3
    min_count             = 1
    os_disk_size_gb       = 256
    vm_size               = "Standard_D2_v2"
  }
  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed                = true
      admin_group_object_ids = [azuread_group.aks-admin-group.id]
    }
  }
  identity {
    type = "SystemAssigned"
  }
  network_profile {
    network_plugin    = "azure"
    network_policy    = "azure"
    load_balancer_sku = "Standard"
  }

  addon_profile {
    aci_connector_linux {
      enabled = false
    }

    azure_policy {
      enabled = true
    }

    http_application_routing {
      enabled = false
    }

    kube_dashboard {
      enabled = true
    }
  }
}
```

### Expected Behavior

kubernetes_version is not set in the terraform code. According to documentation if not specified, the latest recommended version will be used at provisioning time 
Current **azure latest kubernetes version in East Us - 1.17.9**

```
az aks get-versions --location eastus --output table

KubernetesVersion    Upgrades
-------------------  ----------------------------------------
1.18.6(preview)      None available
1.18.4(preview)      1.18.6(preview)
1.17.9               1.18.4(preview), 1.18.6(preview)
1.17.7               1.17.9, 1.18.4(preview), 1.18.6(preview)
1.16.13              1.17.7, 1.17.9
1.16.10              1.16.13, 1.17.7, 1.17.9
1.15.12              1.16.10, 1.16.13
1.15.11              1.15.12, 1.16.10, 1.16.13

```

### Actual Behavior
**Terraform creates the cluster with 1.16.13**

### Steps to Reproduce

1. `terraform apply`

**Comment by SegersIan** [comment]
Agreed with @njuCZ. As you can see in the Azure Portal, the "default" is not the same as the latest version. This is controlled by the AKS service team. Implementing your requested behaviour would actually overwrite the default behaviour of Azure. In my opinion that should be avoided. 

<img width="769" alt="screen" src="https://user-images.githubusercontent.com/1368259/92711277-b9513500-f358-11ea-9815-12547a18fc0b.png">

**Comment by VipinAgarwal** [comment]
I think that makes sense. Thanks for the input.
