### ISSUE TITLE
Support for DNS settings

### ISSUE THREAD

**Issue by 1aziz** [terraform-providers/terraform-provider-azurerm#8363]
At the moment it's not possible to enable DNS proxy. Since it will be needed to add FQDN network rules, it could be considered as a nice feature to add in future.
To see those settings on Portal: go to an Azure Firewall, open _DNS (preview)_ and select _Enabled_.

**Comment by magodo** [comment]
@1aziz Thank you for subimitting this!

I assume you are asking what #7390 implemented, this PR is now under review.
