### ISSUE TITLE
azurerm_container_group should allow multiple ports per container

### ISSUE THREAD

**Issue by jmcnevin** [terraform-providers/terraform-provider-azurerm#837]
### Terraform Version
0.11.3

### Affected Resource(s)
- azurerm_container_group

### Expected Behavior
Per the Azure documentation [here](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-group), multiple ports can be declared open per container.

### Actual Behavior
The resource accepts only a single port per container.

**Comment by tombuildsstuff** [comment]
Duplicate of #1662 which I'm going to close this in favour of (since there's more activity in that issue).
