### ISSUE TITLE
Getting an error while trying to create Azure KeyVault

### ISSUE THREAD

**Issue by omershliva** [terraform-providers/terraform-provider-azurerm#8373]
provider "azurerm" {
  version = "=2.25.0"
  features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "Encrypt-resources"
  location = "North Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "Encrypt-network"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
}

resource "azurerm_subnet" "internal" {
  name                 = "internal"
  resource_group_name  = "${azurerm_resource_group.example.name}"
  virtual_network_name = "${azurerm_virtual_network.example.name}"
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "example" {
  name                = "Encrypt-nic"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = "${azurerm_subnet.internal.id}"
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_key_vault" "example" {
  name                        = "TF-keyvault-omersh"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  tenant_id                   = "${data.azurerm_client_config.current.tenant_id}"
  sku_name                    = "premium"
}

resource "azurerm_key_vault_key" "example" {
  name         = "TF-key-omersh"
  key_vault_id = "${azurerm_key_vault.example.id}"
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_disk_encryption_set" "example" {
  name                = "example-set"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  key_vault_key_id    = "${azurerm_key_vault_key.example.id}"
  
  identity {
    type = "SystemAssigned"
  }
}
resource "azurerm_key_vault_access_policy" "disk-encryption" {
  key_vault_id = "${azurerm_key_vault.example.id}"
  tenant_id = "${azurerm_disk_encryption_set.example.identity.0.tenant_id}"
  object_id = "${azurerm_disk_encryption_set.example.identity.0.principal_id}"
  key_permissions = [
    "get",
    "wrapkey",
    "unwrapkey",
  ]
}

I'm getting the following error:
Error:  keyvault.BaseClient#GetKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=<appid>;numgroups=2;iss=https://sts.windows.net/******/' does not have keys get permission on key vault 'TF-keyvault-omersh;location=westus2'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njuCZ** [comment]
@omershliva this error is because you have no permission to create "azurerm_key_vault_key". You should grant yourself relevant permission. For example, you could have a try of following script
```
resource "azurerm_key_vault" "example" {
  name                     = "TF-keyvault-omersh"
  location                 = "${azurerm_resource_group.example.location}"
  resource_group_name      = "${azurerm_resource_group.example.name}"
  tenant_id                = "${data.azurerm_client_config.current.tenant_id}"
  sku_name                 = "premium"
  soft_delete_enabled      = true
  purge_protection_enabled = true
  
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "create",
      "delete",
      "get",
      "list",
    ]
  }
}

resource "azurerm_key_vault_key" "example" {
  name         = "TF-key-omersh"
  key_vault_id = "${azurerm_key_vault.example.id}"
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_disk_encryption_set" "example" {
  name                = "example-set"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  key_vault_key_id    = "${azurerm_key_vault_key.example.id}"

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_key_vault_access_policy" "disk-encryption" {
  key_vault_id = "${azurerm_key_vault.example.id}"
  tenant_id    = "${azurerm_disk_encryption_set.example.identity.0.tenant_id}"
  object_id    = "${azurerm_disk_encryption_set.example.identity.0.principal_id}"
  key_permissions = [
    "get",
    "wrapkey",
    "unwrapkey",
  ]
}
```

**Comment by omershliva** [comment]
Hi, thank you for your response. I'm still getting the same error.

**Comment by njuCZ** [comment]
@omershliva Could you please paste some [debug](https://www.terraform.io/docs/internals/debugging.html) log info? Are you still failed at the step of creating azurerm_key_vault_key? Could you please confirm you have the correct permission in the keyvaults from the portal?

**Comment by omershliva** [comment]
@njuCZ , I'll terraform destroy the code and apply it again. Then, will screenshot the Azure UI. Sorry, but I didn't understand how can I send debug (I'm using Visual studio on my windows host machine).

**Comment by omershliva** [comment]
okay okay, it's working after terraform destroy and terraform apply again. Thank you so much.
So, this is OS disk encryption. What about 'Data disks' encryption?

**Comment by njuCZ** [comment]
@omershliva I am sorry that I am not so familiar with Compute relevant resources. Maybe you means "azurerm_managed_disk"? In general, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html)
