### ISSUE TITLE
Networks Security Group claimed to not be tracked by terraform state when it is already tracked

### ISSUE THREAD

**Issue by achalupa-ptc** [terraform-providers/terraform-provider-azurerm#8378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

[root@saltsyndic2-euw:19 customer]# terraform -v
Terraform v0.12.25
+ provider.azurerm v2.26.0

### Affected Resource(s)

* `azurerm_network_security_group`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "gateway" {
  name                = module.naming.customer_agw_name
  resource_group_name = azurerm_resource_group.customer.name
  location            = azurerm_resource_group.customer.location

  tags = merge(local.common_tags, {
    Name               = module.naming.customer_agw_name
    Description        = "NSG for ${module.naming.environment_label} Application Gateway"
  })
}
```

### Debug Output

For this terraform execution the only change present in the resource was on tags.  The terraform plan reported the right changes to the resources (showing tag changes only)

Error: A resource with the ID "/subscriptions/88108c56-f00a-4aa6-96a1-41e061318dcd/resourceGroups/cs-rg-svnet-rochb-euw/providers/Microsoft.Network/networkSecurityGroups/rochb-euw-agw" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_network_security_group" for more information.

  on app_gateway.tf line 34, in resource "azurerm_network_security_group" "gateway":
  34: resource "azurerm_network_security_group" "gateway" {

but if you try to import the resource it states that it's already present:

[root@saltsyndic2-euw:19 customer]# terraform import azurerm_network_security_group.gateway /subscriptions/88108c56-f00a-4aa6-96a1-41e061318dcd/resourceGroups/cs-rg-svnet-rochb-euw/providers/Microsoft.Network/networkSecurityGroups/rochb-euw-agw
azurerm_network_security_group.gateway: Importing from ID "/subscriptions/88108c56-f00a-4aa6-96a1-41e061318dcd/resourceGroups/cs-rg-svnet-rochb-euw/providers/Microsoft.Network/networkSecurityGroups/rochb-euw-agw"...
azurerm_network_security_group.gateway: Import prepared!
  Prepared azurerm_network_security_group for import

### Expected Behavior

It should have applied the tag changes.

If I revert back to provider 2.25.0 it works as expected

### Actual Behavior

terraform complains that the network security group is not being tracked in the tf state when it already is.

### Steps to Reproduce

1. `terraform apply` with a network security group with azure provider earlier than 2.26.0
2. change the tags on the NSG resource
3. 'terraform apply' with 2.26.0 azurerm provider

* #0000

**Comment by magodo** [comment]
@achalupa-ptc Thank you for letting us know this issue at the first moment :+1: It will be fixed by #8384
