### ISSUE TITLE
Anyone used os_profile_secret for azurerm_virtual_machine?

### ISSUE THREAD

**Issue by bhushangholve2006** [terraform-providers/terraform-provider-azurerm#839]
Hi there,
I have searched for suitable example about the `azurerm_virtual_machine ` resource with `os_profile_secret`  but no luck. Used below link.
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html

So my question here is has anyone used azure vault secret for creating `azurerm_virtual_machine ` in `os_profile_secret`  ? If yes please provide me example or guide me.

Thanks,
Bhushan

**Comment by tombuildsstuff** [comment]
hey @bhushangholve2006 

Thanks for opening this issue

So I've not got an example to point you to at this point in time - however I believe the following should be what you're after - would you be able to take a look and see if that solves your issue?

```
resource "azurerm_virtual_machine" "test" {
  os_profile_secrets {
    source_vault_id = "${azurerm_key_vault.test.id}"
    vault_certificates {
      certificate_url = "${azurerm_key_vault_certificate.test.id}"
    }
  }
}
```

Thanks!

**Comment by bhushangholve2006** [comment]
Hey @tombuildsstuff ,
Thanks for responding to this.

My intention behind this is to use vault instead of storing ssh key in my variable.tf file.
First of all is this possible? If yes...
As per your description parameters like `source_vault_id` is okay but what is the certificate url? how we can for that... As I see in document 

certificate_url - (Required) Specifies the URI of the key vault secrets in the format of `https://<vaultEndpoint>/secrets/<secretName>/<secretVersion>`. Stored secret is the Base64 encoding of a JSON Object that which is encoded in UTF-8 of which the contents need to be
```
{
  "data":"<Base64-encoded-certificate>",
  "dataType":"pfx",
  "password":"<pfx-file-password>"
}
```

Confused about either provide the url for vault or the Base64 encoded JSON?

**Comment by bhushangholve2006** [comment]
Following are the results

script scenario 1
```
resource "azurerm_virtual_machine" "test" {
 os_profile_secrets {
      source_vault_id = "/subscriptions/00000-0000-0000-0000-000000000/resourceGroups/testgr/providers/Microsoft.KeyVault/vaults/testvault"
      vault_certificates {
        certificate_url = "https://test.vault.azure.net/certificates/myssh/31781287612631232323237612361236"
      }
    }

    os_profile_linux_config {
      disable_password_authentication = true,
      ssh_keys {
            path     = "/home/azureuser/.ssh/authorized_keys"
            # key_data = "${var.ssh_key}"
        }
    }
}
```

Error
* azurerm_virtual_machine.azure_vm: 1 error(s) occurred:

* azurerm_virtual_machine.azure_vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid."

test script 2
```
resource "azurerm_virtual_machine" "test" {
 os_profile_secrets {
      source_vault_id = "/subscriptions/00000-0000-0000-0000-000000000/resourceGroups/testgr/providers/Microsoft.KeyVault/vaults/testvault"
      vault_certificates {
        certificate_url = "https://test.vault.azure.net/certificates/myssh/31781287612631232323237612361236"
      }
    }

    os_profile_linux_config {
      disable_password_authentication = true,
      /* ssh_keys {
            path     = "/home/azureuser/.ssh/authorized_keys"
            # key_data = "${var.ssh_key}"
        } */
    }
}
```
Error
Error: Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine.azure_vm: 1 error(s) occurred:

* azurerm_virtual_machine.azure_vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="Authentication using either SSH or by user name and password must be enabled in Linux profile."

Looks like I need to give either ssh key or password but I thought it will take `os_profile_secret`  instead :(

**Comment by tombuildsstuff** [comment]
hi @bhushangholve2006 

Thanks for getting back to us - apologies for the delayed response here!

As you're seeing in the error message from Azure:

> azurerm_virtual_machine.azure_vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="Authentication using either SSH or by user name and password must be enabled in Linux profile."

Either a Password/SSH key must be specified as a requirement from Azure. The `os_profile_secrets` block is for use with Windows boxes when configuring WinRM (there may be other uses too, that's just the one I've commonly seen) - where certificates can be loaded onto the box and used for connections etc.

The functionality you're after isn't current supported by Azure - as such we'd suggest loading this value from Key Vault and then passing it into the VM resource. There's a Feature Request to add a Data Source to pull Secrets from Azure KeyVault in issue #606 - which I'm going to close this in favour of.

Thanks!

**Comment by kishorebasisth** [comment]
@tombuildsstuff  Sorry to tag you on an already existing post, does this mean that the `os_profile_secrets` is windows only?
