### ISSUE TITLE
azurerm_storage_blob - Parallelism and size force replacement

### ISSUE THREAD

**Issue by jwperry** [terraform-providers/terraform-provider-azurerm#8392]
### **Community Note**

Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Terraform (and AzureRM Provider) Version**

Terraform v0.13.2
AzureRM 2.26.0

### **Affected Resource(s)**

azurerm_storage_blob

### **Terraform Configuration Files**

```
resource "azurerm_storage_blob" "mongobackups" {
  name = "mongobackups.sh"
  storage_account_name = azurerm_storage_account.sagenstorage.name
  storage_container_name = azurerm_storage_container.provisioners.name
  type = "Block"
  source = "..\\provisioners\\mongobackups.sh"
  parallelism = 8
  size = 0
}
```

### **Debug Output**

Can provide full debug output if needed, but would prefer not to post it publicly.

### **Expected Behavior**

Able to `terraform import` azurerm_storage_blob resources.

### **Actual Behavior**

The `parallelism` and `size` attributes of azurerm_storage_blob resources force creation of a new resource, with default values of 8 and 0 respectively. Even after adding them, as shown in the configuration above, they show "forces replacement." The `source` attribute is also forcing replacement, but `parallelism` and `size` are the only two that always show up (if I remove the `source` attribute entirely, Terraform doesn't complain about it).

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems API wouldn't return the properties `Parallelism`, `size` and `source`. So terraform cannot keep them into state file so that there is difference after imported. I assume you have to use `ignore_changes` as workaround after imported. Once you want to change one of these properties, you have to remove the property name from ignore_changes. After applied, you wouldn't get difference anymore for this property.

sample:
```
resource "azurerm_storage_blob" "test" {
  ......
  lifecycle {
    ignore_changes = [source, parallelism, size]
  }
}
```

**Comment by jwperry** [comment]
You're welcome, and thanks Neil! Happy to use `ignore_changes` as a workaround for the time being. Have a great day!
