### ISSUE TITLE
ACI: Support for specifying DnsConfig when creating container group

### ISSUE THREAD

**Issue by BharatNarasimman** [terraform-providers/terraform-provider-azurerm#8398]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure container instances allows specifying custom dns config to be injected into the container group. This is done by specifying dnsconfig in the PUT request. https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups.

### New or Affected Resource(s)

* azurerm_container_group

### References

* dnsConfig in https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups

**Comment by njuCZ** [comment]
duplicate as #6360, already implemented, will be available in azurerm v2.30

**Comment by tombuildsstuff** [comment]
Closing in favour of #6360
