### ISSUE TITLE
Upgrading azurerm from 1.44.0 to 2.26.0 - azurerm_network_interface_security_group_association

### ISSUE THREAD

**Issue by 1arrow** [terraform-providers/terraform-provider-azurerm#8399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Azure User Login detected
Terraform v0.12.29
+ provider.azurerm v2.26.0
+ provider.chef v0.2.0
+ provider.external v1.2.0
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* `azurerm_network_interface_security_group_association`
* `azurerm_network_interface`

### Terraform Configuration Files

```hcl
# Create network interface
resource "azurerm_network_interface" "app-nic" {
  count               = "${var.app-vm-nodes}"
  name                = "${var.appname}-nic${count.index}-${var.region}-${var.environment}"
  location            = "${var.region_description}"
  resource_group_name = "${azurerm_resource_group.app-rg.name}"

  ip_configuration {
    name                          = "${var.appname}${count.index}-${var.region}-${var.environment}"
    subnet_id                     = "${local.app_subnet_id}"
    private_ip_address_allocation = "dynamic"
  }

  lifecycle {
    prevent_destroy = false
  }

  tags = {
    environment = "${var.environment}"
    region      = "${var.region}"
    managed-by  = "terraform"
  }
}

resource "azurerm_network_interface_security_group_association" "app-nic-nsg-link" {
  count                     = "${var.app-vm-nodes}"
  network_interface_id      = element(azurerm_network_interface.app-nic.*.id, count.index)
  network_security_group_id = element(azurerm_network_security_group.app-vm-nsg.*.id, count.index)
}

```

### Debug Output

Im upgrading azurerm from 1.44.0 to 2.26.0, it asked me to remove network_security_group_id and add azurerm_network_interface_security_group_association. Below is the documentation from upgrade guide

`The deprecated field network_security_group_id will be removed. This has been replaced by the azurerm_network_interface_security_group_association resource.`

Saw below error

```
Error: A resource with the ID "/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkInterfaces/lkgb-app-nic0-eastus-qa|/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkSecurityGroups/lkgb-app-vm-nsg-eastus-qa" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_network_interface_security_group_association" for more information.

  on app-vm-node.tf line 25, in resource "azurerm_network_interface_security_group_association" "app-nic-nsg-link":
  25: resource "azurerm_network_interface_security_group_association" "app-nic-nsg-link" {



Error: A resource with the ID "/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkInterfaces/lkgb-app-nic1-eastus-qa|/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkSecurityGroups/lkgb-app-vm-nsg-eastus-qa" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_network_interface_security_group_association" for more information.

  on app-vm-node.tf line 25, in resource "azurerm_network_interface_security_group_association" "app-nic-nsg-link":
  25: resource "azurerm_network_interface_security_group_association" "app-nic-nsg-link" {
```

### Expected Behavior

Terraform upgrade to go through smoothely when upgrading from 1.44.0 to 2.26.0

### Actual Behavior

terraform apply fils with above error

### Steps to Reproduce

- Have a NIC configured in with azurerm 1.44.0 and associate a NSG to it with NSG Id

```
# Create network interface
resource "azurerm_network_interface" "app-nic" {
  count                     = "${var.app-vm-nodes}"
  name                      = "${var.appname}-nic${count.index}-${var.region}-${var.environment}"
  location                  = "${var.region_description}"
  resource_group_name       = "${azurerm_resource_group.app-rg.name}"
  network_security_group_id = "${azurerm_network_security_group.app-vm-nsg.id}"

  ip_configuration {
    name                          = "${var.appname}${count.index}-${var.region}-${var.environment}"
    subnet_id                     = "${local.app_subnet_id}"
    private_ip_address_allocation = "dynamic"
  }

  lifecycle {
    prevent_destroy = false
  }

  tags = {
    environment = "${var.environment}"
    region      = "${var.region}"
    managed-by  = "terraform"
  }
}
```

- `terraform apply` will go through fine without issue

- To upgrade azurerm version 2.26.0, make the provider update

```
provider "azurerm" {
  version = "=2.26.0"
  features {}
}
```

And also add azurerm_subnet_network_security_group_association

```
variable "app-subnet-iprange" {
  description = "Environment Specific application subnet in the OPS vnet - see the spreadsheet for coordinated cidrs"
  default     = ""
}

# Subnet for all the environment specifci Virutal Machines
resource "azurerm_subnet" "app-subnet" {
  count                = "${var.app-subnet-iprange == "" ? "0" : "1"}"
  name                 = "${var.appname}-subnet-${var.region}-${var.environment}"
  resource_group_name  = "${local.ops-mgmt-rg}"
  virtual_network_name = "${local.ops-network}"
  address_prefix       = "${var.app-subnet-iprange}"
  service_endpoints    = ["Microsoft.Sql", "Microsoft.Storage"]

  lifecycle {
    prevent_destroy = false
  }
}

# NSG for appnet
resource "azurerm_network_security_group" "app-subnet-nsg" {
  count               = "${var.app-subnet-iprange == "" ? "0" : "1"}"
  name                = "appnet-nsg-${var.region}-${var.environment}"
  resource_group_name = "${local.ops-mgmt-rg}"
  location            = "${var.region_description}"

  lifecycle {
    prevent_destroy       = false
    create_before_destroy = false
  }

  tags = {
    environment = "${var.environment}"
    region      = "${var.region}"
    managed-by  = "terraform"
  }
}

# Assiciate Subnet with NSG
resource "azurerm_subnet_network_security_group_association" "app-subnet-nsg-link" {
  count                     = "${var.app-subnet-iprange == "" ? "0" : "1"}"
  subnet_id                 = "${azurerm_subnet.app-subnet.0.id}"
  network_security_group_id = "${azurerm_network_security_group.app-subnet-nsg.0.id}"
}

```

- Run terraform apply and you will see the said error

### References

* #0000

**Comment by magodo** [comment]
Hey @1arrow Thank you for submitting this!

The error you saw above is expected. `azurerm_network_interface_security_group_association` is actually a logical resource that is responsible to maintain the relationship between NIC and NSG. As you have already created that relationship in your existing provision, that means the logical resource `azurerm_network_interface_security_group_association` already exist (as the error message has compained).

To resolve the error, simply follow the instrucment in the error message. Run following command to import the relationship in your new config:

```bash
$ terraform import "azurerm_network_interface_security_group_association.app-nic-nsg-link[0]" "/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkInterfaces/lkgb-app-nic0-eastus-qa|/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkSecurityGroups/lkgb-app-vm-nsg-eastus-qa"
$ terraform import "azurerm_network_interface_security_group_association.app-nic-nsg-link[1]" "/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkInterfaces/lkgb-app-nic1-eastus-qa|/subscriptions/6cae49f5-1e4f-487a-8f43-cdbb8b50642f/resourceGroups/lkgb-app-eastus-qa-rg/providers/Microsoft.Network/networkSecurityGroups/lkgb-app-vm-nsg-eastus-qa"
```

**Comment by 1arrow** [comment]
We have 1000+ VMs provisioned with terraform, importing all would be painful :(
This could have been handled better

**Comment by magodo** [comment]
@1arrow unfortunately, this is by design. Althoug terrafrom could handle some cases of migration (mostly in turns of schema of the same resource), but is not designed to handle the provider upgrading in some breaking change way - as in your case the major version bumps.

To bulk import the resources, for now you can write some script to invoke the `terraform import` command 1000+ times, given the resource ID could be easily retrieved from the error message. But it takes time. Another better choice is to use an upcoming feature introduced by hashicorp/terraform#22227, which could do a bulk import in one shot. Although it is not yet available, you can do a local build and use it do this adhoc operation.

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment, but please let us know if the solution proposed above doesn't work for you and we'll take another look.

Thanks!
