### ISSUE TITLE
Feature Request: add support for DNS Name Label for Azure Container Instance

### ISSUE THREAD

**Issue by szinck1** [terraform-providers/terraform-provider-azurerm#840]
ACI now supports public DNS names. The CLI option is --dns-name-label.  The public DNS will follow the container when its IP address changes.

It would be great if Terraform could add support for it.

**Comment by tombuildsstuff** [comment]
Hey @szinck1 

Thanks for opening this issue :)

From what I can see this field will be added to the Azure SDK [in the new API version for Azure Container Instances which will added in #827](https://github.com/terraform-providers/terraform-provider-azurerm/pull/827/files#diff-9810778e25352a442bf7ffb22dda690fR459). Once #827 has been merged we should be able to expose this field.

Thanks!

**Comment by tombuildsstuff** [comment]
:wave: hey @szinck1 

Just to let you know that support for this has just been released in v1.2.0 of the AzureRM Provider - full details of what's included are available here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.2.0/CHANGELOG.md#120-march-02-2018

Thanks!
