### ISSUE TITLE
Cannot create Consumption SKU Azure API management

### ISSUE THREAD

**Issue by toxgator** [terraform-providers/terraform-provider-azurerm#8405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* AzureRM is not able to create API Management Resource for Consumption SKU.
* azurerm_api_management is showing following error while creating consumption tier based API Management even if not adding any block for custom properties:
	- "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30' customProperties are not supported in SkuType Consumption."

### Terraform Version 
* Terraform v0.13.0

### AzureRM Provider: 
* provider.azurerm v2.25.0

### Affected Resource(s)

* azurerm_api_management

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "apim-rg" {
  name     = "rg-apim"
  location = "West Europe"
}

resource "azurerm_api_management" "apim" {
  name                = "demo-apim"
  location            = azurerm_resource_group.apim-rg.location
  resource_group_name = azurerm_resource_group.apim-rg.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku_name = "Consumption_1"
}
```

### Debug Output

```
{
   "error":{
      "code":"NotSupported",
      "message":"'Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30' customProperties are not supported in SkuType Consumption.",
      "details":null,
      "innerError":null
   }
}
```

```
{
   "location":"southcentralus",
   "properties":{
      "certificates":[
         
      ],
      "customProperties":{
         "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Ssl30":"false",
         "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls10":"false",
         "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls11":"false",
         "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168":"false",
         "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30":"false",
         "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls10":"false",
         "Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls11":"false"
      },
      "hostnameConfigurations":[
         
      ],
      "publisherEmail":"<publisher_Email>",
      "publisherName":"<publisher_Name>",
      "virtualNetworkType":"None"
   },
   "sku":{
      "name":"Consumption",
      "capacity":1
   },
   "tags":{
      
   }
}
```

**Comment by yupwei68** [comment]
Hi @toxgator ,  thanks for opening this issue. Would you mind subscribing to https://github.com/terraform-providers/terraform-provider-azurerm/issues/6730 to get more updates from our side. We have an open PR to fix it, but currently it's blocked by some go-sdk issues.

**Comment by mybayern1974** [comment]
Hi @toxgator , per yupwei68's suggestion, would you mind if we close this issue for dup and you could subscribe #6730 ?

**Comment by toxgator** [comment]
Hi @mybayern1974 , Sure, I'll subscribe to #6730, Closing current issue.
