### ISSUE TITLE
AzureRM: Azure Automation: VM Desired State: Updated JSON syntax does not appear to be supported

### ISSUE THREAD

**Issue by AlexcFrench** [terraform-providers/terraform-provider-azurerm#8419]
Hi,

Referencing : https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-template#update-from-a-previous-format

When configuring the JSON for the desired state endpoint configuration, the correct attribute is now 'configurationArguments' instead of 'Properties' (highlighted below).

However, if 'configurationArgument' is used as a direct replacement for 'Properties' in the terraform file JSON 'Settings' section of the 'azurerm_virtual_machine_extension' resource, deployment fails as it cannot find any of the configuration to authenticate to the automation account.

Current Property name | Previous schema equivalent
-- | --
settings.wmfVersion | settings.WMFVersion
settings.configuration.url | settings.ModulesUrl
settings.configuration.script | First part of settings.ConfigurationFunction (before \\)
settings.configuration.function | Second part of settings.ConfigurationFunction (after \\)
settings.configuration.module.name | settings.ModuleSource
settings.configuration.module.version | settings.ModuleVersion
**settings.configurationArguments | settings.Properties**
settings.configurationData.url | protectedSettings.DataBlobUri (without SAS token)
settings.privacy.dataCollection | settings.Privacy.dataCollection
settings.advancedOptions.downloadMappings | settings.AdvancedOptions.DownloadMappings
protectedSettings.configurationArguments | protectedSettings.Properties
protectedSettings.configurationUrlSasToken | settings.SasToken
protectedSettings.configurationDataUrlSasToken | SAS token from protectedSettings.DataBlobUri

example (working):
  settings = <<SETTINGS
    {
      "WmfVersion": "latest",
        "Privacy": {
          "DataCollection": ""
          },
        "Properties": {
          "RegistrationKey": {
            "UserName": "PLACEHOLDER_DONOTUSE",
            "Password": "PrivateSettingsRef:registrationKeyPrivate"
            },  
          "RegistrationUrl": "${var.AutomationAccountEndpoint}",
          "NodeConfigurationName": "PSExecPolicy.local",
          "ConfigurationMode": "ApplyandAutoCorrect",
          "ConfigurationModeFrequencyMins": 15,
          "RefreshFrequencyMins": 30,
          "RebootNodeIfNeeded": true,
          "ActionAfterReboot": "continueConfiguration",
          "AllowModuleOverwrite": true
          }
      }
    SETTINGS
  
  protected_settings = <<PROTECTED_SETTINGS
    {
      "Items": {
        "registrationKeyPrivate" : "${var.AutomationAccountKey}"
        }
    }
    PROTECTED_SETTINGS
}

example (fails):
  settings = <<SETTINGS
    {
      "WmfVersion": "latest",
        "Privacy": {
          "DataCollection": ""
          },
        "configurationArguments": {
          "RegistrationKey": {
            "UserName": "PLACEHOLDER_DONOTUSE",
            "Password": "PrivateSettingsRef:registrationKeyPrivate"
            },  
          "RegistrationUrl": "${var.AutomationAccountEndpoint}",
          "NodeConfigurationName": "PSExecPolicy.local",
          "ConfigurationMode": "ApplyandAutoCorrect",
          "ConfigurationModeFrequencyMins": 15,
          "RefreshFrequencyMins": 30,
          "RebootNodeIfNeeded": true,
          "ActionAfterReboot": "continueConfiguration",
          "AllowModuleOverwrite": true
          }
      }
    SETTINGS
  
  protected_settings = <<PROTECTED_SETTINGS
    {
      "Items": {
        "registrationKeyPrivate" : "${var.AutomationAccountKey}"
        }
    }
    PROTECTED_SETTINGS
}

Unless I'm doing it wrong !!! :-)

Thanks

Alex

**Comment by ArcturusZhang** [comment]
Hi @AlexcFrench thanks for this issue!

I am not quite sure if I fully understand your question - but currently the Azure SDK does not specify a certain format for the `settings` and `protected_settings`. Therefore you could assign anything to these two attributes, and the service will check if those are valid.

**Comment by tombuildsstuff** [comment]
hi @AlexcFrench 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
