### ISSUE TITLE
No Terraform resource available to add "Certificate Authorities"

### ISSUE THREAD

**Issue by callppatel** [terraform-providers/terraform-provider-azurerm#8425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_certificate_authorities

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

Currently we dont have Terraform resource to add "Certificate Authorities" in KeyVault Cert. Can we add this as enhancement request. 
![image](https://user-images.githubusercontent.com/17652733/92758038-55c90680-f35c-11ea-8eb6-2a89fe4dead2.png)

![image](https://user-images.githubusercontent.com/17652733/92757912-34681a80-f35c-11ea-80bc-cabde8b18720.png)

**Comment by LaurentLesle** [comment]
Have you checked certificate issuer https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_certificate_issuer

**Comment by tombuildsstuff** [comment]
👋 

Since this functionality already appears to be available (as per @LaurentLesle's comment above) - I'm going to close this out for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
