### ISSUE TITLE
Terraform plan taking too long to run while creating Azure SQL DB

### ISSUE THREAD

**Issue by rtk888** [terraform-providers/terraform-provider-azurerm#8427]
**Problem:**
While running Terraform plan command in VScode to create AzureSQL DB the command hangs and doesn't produce an output. To identify the error I have enabled trace. The same script was used to create Azure SQL server but failed while creating Azure SQL database. When I ran the script again to create the SQL database, the script failed from the terraform plan step.

Below powershell command was run before running terraform.

az login
az account set --subscription "XXXXXXXXX"

### **Terraform (and AzureRM Provider) Version**
terraform 0.13.0
azurerm 2.27.0

### **Affected Resource(s)**
azurerm_sql_database.db

### **Terraform Configuration Files-**
```

provider "azurerm" {
  version = "=2.27.0"
  features {}
}

terraform {
  required_version=">=0.11.7"
}

resource "azurerm_resource_group" "test" {
  name     = "tformrg"
  location = "Canada Central"
}
resource "azurerm_sql_server" "sql" {
  name                         = "rtktestsql"
  resource_group_name          = "tformrg"
  location                     = "Canada Central"
  version                      = "12.0"
  administrator_login          = "useradmin"
  administrator_login_password = "test123*"

  tags = {
    environment = "test"
  }
}
resource "azurerm_sql_database" "db" {
  name                = "rtktestsqldb1"
  resource_group_name = "tformrg"
  location            = "Canada Central"
  server_name         = "rtktestsql"

  tags = {
    environment = "test"
  }
}
```

### **Debug Output**

```
2020/09/10 14:39:58 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)"
2020/09/10 14:40:03 [TRACE] dag/walk: vertex "azurerm_sql_server.sql (expand)" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"]"
2020/09/10 14:40:03 [TRACE] dag/walk: vertex "azurerm_sql_database.db (expand)" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"]"
2020/09/10 14:40:03 [TRACE] dag/walk: vertex "azurerm_resource_group.test (expand)" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"]"
2020/09/10 14:40:03 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" is waiting for "azurerm_resource_group.test (expand)"
```

**### Expected Behavior**

SQL Database should be created as per the script.

**### Actual Behavior**

Plan command hangs. The error in the trace shows it as "azurerm_sql_database.db (expand)" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"]

**### Steps to Reproduce**

1.terraform init
2.terraform plan

**Comment by yupwei68** [comment]
Hi @rtk888 , thanks for opening this issue. Sorry that I could not reproduce your error. I have changed your code a little bit and I applied it with success. Would you mind retrying the configuration and seeing if the error is reproducible? If so, could you paste a more complete error log? 
```
provider "azurerm" {
  version = "2.27.0"
  features {}
}


resource "azurerm_resource_group" "test" {
  name     = "tformrg"
  location = "eastus"
}
resource "azurerm_sql_server" "sql" {
  name                         = "rtktestsql"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "useradmin"
  administrator_login_password = "test123*"

  tags = {
    environment = "test"
  }
}
resource "azurerm_sql_database" "db" {
  name                = "rtktestsqldb1"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  server_name         = azurerm_sql_server.sql.name

  tags = {
    environment = "test"
  }
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment, but please let us know if the solution proposed above doesn't work for you and we'll take another look.

Thanks!
