### ISSUE TITLE
Using 2.27 with new data source azurerm_function_app_host_keys crashes terraform

### ISSUE THREAD

**Issue by Renetnielsen** [terraform-providers/terraform-provider-azurerm#8428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 13.2
AzureRM 2.27

### Affected Resource(s)

* `azurerm_function_app_host_keys `

### Terraform Configuration Files

```hcl
data "azurerm_function_app_host_keys" "azfun_deletemessages_keys" {
  name                = "azfun-deletemessages-${var.environment}"
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_key_vault_secret" "kvs_deletemessages_function_key" {
  name          = "FUNCTION--KEY--DELETEMESSAGES"
  value         = data.azurerm_function_app_host_keys.azfun_deletemessages_keys.default_function_key
  key_vault_id  = module.kv_main.id
  tags          = local.tags_timeseries
}
```

### Debug Output
https://gist.github.com/Renetnielsen/e81ecce58ddfb68f2ee8a1c449d9694e

### Panic Output

Since our terraform only runs in a pipeline on a virtual machine in DevOps i can't access this file.

### Expected Behavior

The function key would have been inserted as a secret in our keyvault.

### Actual Behavior

_!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!_

### Steps to Reproduce

1. Create a function app using terraform
2. Use new azurerm_function_app_host_keys data source to get function key
3. Run `terraform init`
4. Run `terraform plan`
5. Crash

**Comment by Renetnielsen** [comment]
@mbfrahry Thanks for your quick look into this.
Is there a workaround to bypass this error fix you created? I can see its something with Id, is this on the azurerm_function_app_host_keys resource i need to pass ID?

**Comment by mbfrahry** [comment]
No problem @Renetnielsen. Without seeing your resources it's hard to say why you're hitting the crash but for whatever reason the `id` of the function app is nil. I'd make sure the function app exists/the name is correct.
