### ISSUE TITLE
Azure node pool tags for the node are not honoring case

### ISSUE THREAD

**Issue by Hector-Costa** [terraform-providers/terraform-provider-azurerm#8429]
Hi,

Currently when deploying a node pool for AKS via terraform, we are seeing that the node labels that are set are all getting switched to lower case on the node instead of camel case.
This behaviour has broken all our cluster deployments. Could you help me understand why this is happening?

**Terraform code:**

resource "azurerm_kubernetes_cluster_node_pool" "pool" {
  for_each = var.agent_pools
  // 'azN' is appended to pool name by deployment code, so 9 is used to include last 6 chars of pool_id.
  name                  = format("cb%s", substr(each.key, -9, 9)) # example: "ac4b5972by1"
  max_pods              = var.max_pods
  kubernetes_cluster_id = data.azurerm_kubernetes_cluster.couchbase.id
  vnet_subnet_id        = data.azurerm_subnet.couchbase.id
  enable_auto_scaling   = true
  availability_zones    = [each.value["availabilityZone"] != "" ? each.value["availabilityZone"] : tostring(var.availability_zones[index(local.list_agent_pool, each.key) % length(var.availability_zones)])]
  vm_size               = each.value["instanceSize"]
  node_count            = each.value["instanceCount"]
  max_count             = each.value["instanceCount"] * 2
  min_count             = each.value["instanceCount"]
  node_labels = {
    serverGroupName = each.key
  }
}

--
Thanks.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, seems API would return the lower case node label key. I assume it's an API issue. So I raised an issue on Azure/azure-rest-api-specs#10763.

**Comment by tombuildsstuff** [comment]
👋 

Since this is a bug in the upstream Azure API rather than a Terraform issue, I'm going to close this issue in favour of the upstream issue: Azure/azure-rest-api-specs#10763.

Thanks!
