### ISSUE TITLE
azurerm_mssql_server_extended_auditing_policy not implemented

### ISSUE THREAD

**Issue by mikemowgli** [terraform-providers/terraform-provider-azurerm#8437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
AzureRM v2.27.0

### Affected Resource(s)

* `azurerm_mssql_server_extended_auditing_policy`

### Actual Behavior

Having an `extended_auditing_policy` in an `azurerm_mssql_server` triggered a warning: `Warning: "extended_auditing_policy": [DEPRECATED] the `extended_auditing_policy` block has been moved to `azurerm_mssql_server_extended_auditing_policy` and `azurerm_mssql_database_extended_auditing_policy`. This block will be removed in version 3.0 of the provider.`
This is ok up to here, but when adding the requested `azurerm_mssql_server_extended_auditing_policy` resource the best I could because it is only documented for the [database](https://www.terraform.io/docs/providers/azurerm/r/mssql_database_extended_auditing_policy.html), I get this error message: 
```
The provider provider.azurerm does not support resource type
"azurerm_mssql_server_extended_auditing_policy".
```

### References

- https://github.com/terraform-providers/terraform-provider-azurerm/pull/7793
- https://www.terraform.io/docs/providers/azurerm/r/mssql_database_extended_auditing_policy.html

**Comment by tombuildsstuff** [comment]
Fixed via #8447
