### ISSUE TITLE
Changing collation of Azure SQL Database should force a new resource to be created

### ISSUE THREAD

**Issue by phekmat** [terraform-providers/terraform-provider-azurerm#844]
### Terraform Version
Terraform v0.10.7
Azure v1.1.1

### Affected Resource(s)
- azurerm_sql_database

### Expected Behavior
Changing the collation on an Azure SQL DB when the `create_mode` is default should create a new DB with the new collation

### Actual Behavior
Terraform reports a success, but the collation is unchanged

### Important Factoids
The other DB types (`azurerm_postgresql_database` and `azurerm_mysql_database`) create a new resource when the collation changes as well. I'm not sure if I'm missing any nuances around Azure SQL's collation option (since it's ignored if `create_mode` is not `Default`) or if this is just a straightforward change to the schema to add `ForceNew: true`.

**Comment by katbyte** [comment]
Closing this as it seems to have been fixed by #1066
