### ISSUE TITLE
Azure Firewall - Network Rule support for Service Tags

### ISSUE THREAD

**Issue by roshanp85** [terraform-providers/terraform-provider-azurerm#8440]
Hi Team,

Do we have support for terraform, to implement the service tags in Azure firewall: azurerm_firewall_network_rule_collection.

We see them in our portal, but in the documentation we are not able to see anything that will implement the service tags, with source addresses. Please advise thanks.

**Comment by magodo** [comment]
Hi @roshanp85 Thank you for submitting this!

You can simply specify service tags in the [`destination_addresses`](https://www.terraform.io/docs/providers/azurerm/r/firewall_network_rule_collection.html#destination_addresses) property (indeed Azure API reuse that same attribute for service tags). Note that you can not specify service tags and IP/IP ranges in the same rule.

I opened #8448 to highlight this usage in the document.
