### ISSUE TITLE
[azurerm_storage_blob] "InvalidHeaderValue" Unable to upload a file

### ISSUE THREAD

**Issue by NK74** [terraform-providers/terraform-provider-azurerm#8449]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.1
provider registry.terraform.io/hashicorp/azurerm v2.20.0

### Affected Resource(s)

* `azurerm_storage_blob`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_blob" "source-package" {
  name                   = "package.zip"
  storage_account_name   = azurerm_storage_account.bootstrap.name
  storage_container_name = azurerm_storage_container.launch-sources.name
  type                   = "Block"
  source_uri             = "sources/Package.zip"
  depends_on = [
    azurerm_storage_account.bootstrap,
    azurerm_storage_container.launch-sources,
  ]
}

```

### Debug Output
TF CLI Output + Debug  : https://gist.github.com/NK74/28463efbb1fc1c859ea14cfc11d66888

`Error: Error creating Blob "package.zip" (Container "launch-sources" / Account "XXXXXX"): Error copy/waiting: Error copying: blobs.Client#Copy: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:9b0c1a0b-101e-0037-2b72-8a4270000000\nTime:2020-09-14T08:38:44.8401402Z"`

### Expected Behavior
create an azurerm_storage_blob block using the specified local file, it works for smaller files (this one is 88MB)

### Actual Behavior
Crash during the resource creation (try to create a blob file block, try to upload the local file to this Blob storage block but fail at the beginning of the process.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems I can upload successfully with 120MB. Could you have a try below tfconfig using latest azurerm to check whether the issue still exists? Thanks.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "test-blob-test01"
  location = "eastus2"
}

resource "azurerm_storage_account" "test" {
  name                     = "teststoracctest01"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "test" {
  name                  = "contenttest01"
  storage_account_name  = azurerm_storage_account.test.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "test" {
  name                   = "TestPackage3.zip"
  storage_account_name   = azurerm_storage_account.test.name
  storage_container_name = azurerm_storage_container.test.name
  type                   = "Block"
  source                 = "testdata/TestPackage3.zip"
  
  depends_on = [
    azurerm_storage_account.test,
    azurerm_storage_container.test,
  ]
}
```
![image](https://user-images.githubusercontent.com/19754191/93174313-57ca0580-f760-11ea-8a0c-1fc4eedbfbdc.png)

**Comment by NK74** [comment]
Hi Neil,

Thanks for your reply, **`source_uri`** was the issue.
`source_uri -----> source  = "testdata/TestPackage3.zip"`

Now i'm able to upload my ~80MB file with your suggestion. however, there is a limitation on the max file size = 256MB (https://docs.microsoft.com/en-us/rest/api/storageservices/Put-Blob?redirectedfrom=MSDN#remarks)

Thanks again
