### ISSUE TITLE
Is there a support for Data protection - storage account on Azure using Terraform?

### ISSUE THREAD

**Issue by omershliva** [terraform-providers/terraform-provider-azurerm#8450]
Is there a resource I can use in order to enable Azure's blob data protection objects: soft delete && versioning?

**Comment by pearcec** [comment]
This is a duplicate #8268

**Comment by mybayern1974** [comment]
Hi @omershliva , per pearcec's suggestion and giving a quick look, this might be a dup. Instead of tracking the same thing in multiple issues, would you mind subscribe to #8268 ? Or feel free to suggest to reopen if you believe these two issues are not talking about the same thing. Thank you!
