### ISSUE TITLE
"context deadline exceeded" when refreshing state for azurerm_monitor_autoscale_setting

### ISSUE THREAD

**Issue by elliotchaim** [terraform-providers/terraform-provider-azurerm#8456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.21.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/terraform-providers/mongodbatlas v0.6.3
```

### Affected Resource(s)

* `azurerm_app_service_plan`
* `azurerm_monitor_autoscale_setting`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  per_site_scaling    = true

  sku {
    tier = "Standard"
    size = "S1"
  }

  tags = {
    environment ="prod"
    component   = "example"
  }
}

resource "azurerm_monitor_autoscale_setting" "example" {
  name                = azurerm_app_service_plan.example.name
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  target_resource_id  = azurerm_app_service_plan.example.id

  profile {
    name = "${azurerm_app_service_plan.example.name}-cpu"

    capacity {
      default = 1
      minimum = 1
      maximum = 10
    }

    rule {
      metric_trigger {
        metric_name        = "CpuPercentage"
        metric_resource_id = azurerm_app_service_plan.example.id
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT5M"
        time_aggregation   = "Average"
        operator           = "GreaterThan"
        threshold          = 75
      }

      scale_action {
        direction = "Increase"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT1M"
      }
    }

    rule {
      metric_trigger {
        metric_name        = "CpuPercentage"
        metric_resource_id = azurerm_app_service_plan.example.id
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT5M"
        time_aggregation   = "Average"
        operator           = "LessThan"
        threshold          = 25
      }

      scale_action {
        direction = "Decrease"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT1M"
      }
    }
  }

  notification {
    email {
      send_to_subscription_administrator    = true
      send_to_subscription_co_administrator = true
      custom_emails                         = ["alias@domain.com"]
    }
  }
}
```

### Expected Behavior

It should have executed my updates

### Actual Behavior

```
Error: Error reading AutoScale Setting "example" (Resource Group "example"): insights.AutoscaleSettingsClient#Get: Failure sending request: StatusCode=500 -- Original Error: context deadline exceeded
```

### Steps to Reproduce

1. `terraform init -input=false -backend-config="resource_group_name=terraform" -backend-config="storage_account_name=example"`
1. `terraform plan -input=false -out=tfplan`

### Important Factoids

* Running in GitHub Actions with an `azurerm` backend (though have also reproduced locally)

**Comment by magodo** [comment]
Hi @elliotchaim

The context deadline exceeded issue is a bit tricky to debug, which might be caused by network jitter. I tried your configuration locally with no problem.

May I know is that always reproducible? It would be appreciated if you can provide the debug log here.

**Comment by elliotchaim** [comment]
Hi @magodo 

It seems this was caused by connectivity issues with Azure itself: https://status.azure.com/en-gb/status/history/

I've retested and I can confirm that this now works as expected.

Thank you for your help.
