### ISSUE TITLE
Intermittent Destroy+Create of MongoDB flavored CosmosDB Account

### ISSUE THREAD

**Issue by erikerikson** [terraform-providers/terraform-provider-azurerm#8460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Apologies for a lack of anything concrete to reproduce or support this report.  I have observed this every once in awhile (4 times over the past few months) where Terraform randomly decides to wipe my CosmosDB account and recreate it despite a lack of changes in the config.  I recently introduced a TTL that depends on an AZ command to configure.  It would be easy to blame that (which was expected to trigger a destroy/create cycle [and did so without mishap]) but it happened prior to and then after this one and only change to the account over the last ~4 months.

I realize that the correct behavior is to gate the apply and I do that for important environments but the generation of a destroy/create is sufficient to make opening the bug worthwhile.

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

Collection and fields renamed.

```hcl

resource "azurerm_cosmosdb_account" "cosmosAccount" {
  name                            = "${local.prefix}-cosmos-account"
  location                        = var.region
  resource_group_name             = azurerm_resource_group.resourceGroup.name
  offer_type                      = "Standard"
  kind                            = "MongoDB"
  enable_automatic_failover       = false
  enable_multiple_write_locations = false
  consistency_policy {
    consistency_level       = "ConsistentPrefix"
  }
  geo_location {
    prefix            = "${local.prefix}-cosmos-account-geo-location-0"
    location          = var.region
    failover_priority = 0
  }
  capabilities {
    name = "mongoEnableDocLevelTTL"
  }
}

resource "azurerm_cosmosdb_mongo_database" "cosmosDatabase" {
  name                = "${local.prefix}-cosmosDatabase"
  resource_group_name = azurerm_resource_group.resourceGroup.name
  account_name        = azurerm_cosmosdb_account.cosmosAccount.name
  throughput          = var.cosmosdb_throughput
}

resource "azurerm_cosmosdb_mongo_collection" "collection" {
  name                = "collection"
  resource_group_name = azurerm_resource_group.resourceGroup.name
  account_name        = azurerm_cosmosdb_account.cosmosAccount.name
  database_name       = azurerm_cosmosdb_mongo_database.cosmosDatabase.name

  default_ttl_seconds = var.cosmos_default_ttl_seconds
  shard_key           = var.cosmos_shard_key
  throughput          = var.cosmosdb_throughput

  index {
    keys = ["field0", "field1", "field2", "field3"]
    unique = true
  }
  index {
    keys = ["field4"]
  }
  index {
    keys = ["field3"]
  }
  index {
    keys = ["_ts"]
  }
}

# Mitigate an Azure TTL bug.  See:
# https://github.com/terraform-providers/terraform-provider-azurerm/issues/6081
# https://github.com/Azure/azure-cli/issues/13229
# the following command is deprecated but does the job
resource "null_resource" "collectionTtl" {
  triggers = {
    # using timestamp runs it everytime because the indexes are updated (due to
    # https://github.com/terraform-providers/terraform-provider-azurerm/issues/7825
    # which causes indexes to be created every apply) and those updates nullify
    # the effect of running the command
    always_run = "${timestamp()}"
  }
  provisioner "local-exec" {
    command = "az cosmosdb collection update --resource-group-name ${azurerm_cosmosdb_mongo_collection.collection.resource_group_name} --name ${azurerm_cosmosdb_mongo_collection.collection.account_name} --db-name ${azurerm_cosmosdb_mongo_collection.collection.database_name} --collection-name ${azurerm_cosmosdb_mongo_collection.collection.name} --default-ttl ${var.cosmos_default_ttl_seconds}"
  }
  depends_on = [azurerm_cosmosdb_mongo_collection.collection]
}
```

### Debug Output

Excerpts:

```
[...]
azurerm_cosmosdb_account.cosmosAccount: Refreshing state...
[...]
azurerm_cosmosdb_account.cosmosAccount: Destroying...
[...]
azurerm_cosmosdb_account.cosmosAccount: Creating...
[...]
```
### Panic Output

It crashed shortly thereafter for a seemingly unrelated reason.  This has been usually working for months.

### Expected Behavior

No change to HCL should mean no change to resources.

### Actual Behavior

Cosmos Account deleted and recreated, wiping out data

### Steps to Reproduce

No consistent reproduction

**Comment by yupwei68** [comment]
Hi @erikerikson , thanks for opening this issue. We might need a more specific reproducing steps to investigate this problem. `Terraform apply` will ask your approval before the changes are applied. It'll destroy and create this resource for some changes in hcl configuration or in the remote resource state.  Could you give the reproducing steps like `terraform apply` with which changes?

**Comment by erikerikson** [comment]
Thank you yupwei68.  As stated during open, I don't have a reliable reproduction yet.  I can guarantee that there were no changes in the HCL on these occasions.  I can guarantee that we only use Terraform to create and change the account.  I cannot guarantee that the remote API is giving a consistent response so that's my leading hypothesis for the moment.

I have set `TF_LOG=DEBUG` to collect more data for next time the event occurs.  If there's anything else I should do to ensure useful data in case of recurrence, please let me know.  My thought is to leave this bug open so I can add more useful information as it becomes available and in the meantime share awareness.

**Comment by erikerikson** [comment]
Hi @yupwei68 - today, despite not changing anything  about my account since last deploy and taking no other action to modify the account, the following were marked as the reason for replacing my account:

```
      - capabilities { # forces replacement
          - name = "AllowSelfServeUpgradeToMongo36" -> null
        }
      - capabilities { # forces replacement
          - name = "DisableRateLimitingResponses" -> null
        }
```

Out of curiosity, I attempted to add those to my terraform config to try avoiding the conflict.  After that I got the following slightly filtered output:

```
Error: expected capabilities.0.name to be one of [EnableAggregationPipeline EnableCassandra EnableGremlin EnableTable EnableMongo MongoDBv3.4 mongoEnableDocLevelTTL], got AllowSelfServeUpgradeToMongo
Error: expected capabilities.1.name to be one of [EnableAggregationPipeline EnableCassandra EnableGremlin EnableTable EnableMongo MongoDBv3.4 mongoEnableDocLevelTTL], got DisableRateLimitingResponses
```

So either my account will be paved because I can't include them or I can't apply the config because I have.

Admittedly, I don't know how to get an account into that state in order to reproduce this issue.

FWIW, I have upgraded to Terraform v0.13.3 since opening this issue.

**Comment by yupwei68** [comment]
Hi @erikerikson Thanks for updates. This problem has been fixed and released in Azurerm 2.27.0. Would you upgrade the Azurerm version and retry?

**Comment by erikerikson** [comment]
Thank you very much @yupwei68 - updating azurerm to 2.29.0 (latest atm) and along with adding those capabilities avoided the suggested re-creation of my account (and the associated data loss that would have occurred).

That's nice for my development environment and solves the momentary blocker but I find myself curious about whether I can depend on that state having changed in the other directories/accounts/workspaces.  Regardless of whether it has, the default behavior to repave the account and destroy state/data seems like a significant issue.  Even if we are forgoing use of `-auto-approve` and using manual review of plans by humans injects an ongoing risk of human error and inconsistency.  Maybe the approach is too deeply built into the product to consider fixing it but if there's any chance this is an enormous challenge for using Terraform (+the AzureRM plugin).

Is this behavior seen as an issue with Terraform (+the AzureRM plugin) or is it considered working as designed?  Perhaps a mode exists that changes the behavior or there is another third option?  Reacting to this seems likely to deeply ripple through, twist, and perhaps block any reasonable automation.  Given the track record, I have to ask whether continuing down this path is wise.  I appreciate that Terraform has supported more compact specification and some pre-baked workflows but the savings is fairly minor compared to the revisions I'm concerned will be required to avoid these problems.

**Comment by yupwei68** [comment]
Hi @erikerikson Currently cosmosdb forces mongodb 3.6. With mongodb 3.6, I don't reproduce this problem. 
With the configuration below, it doesn't require "AllowSelfServeUpgradeToMongo36" and "DisableRateLimitingResponses".
```
resource "azurerm_cosmosdb_account" "cosmosAccount" {
  name                            = "yup-cosmos-account"
  location                        = azurerm_resource_group.test.location
  resource_group_name             = azurerm_resource_group.test.name
  offer_type                      = "Standard"
  kind                            = "MongoDB"
  enable_automatic_failover       = false
  enable_multiple_write_locations = false
  consistency_policy {
    consistency_level       = "ConsistentPrefix"
  }
  geo_location {
    location          = "eastus"
    failover_priority = 0
  }
  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "EnableMongo"
  }
}
```

**Comment by erikerikson** [comment]
I suspect it may not make much sense to allow a self-service upgrade to 3.6 from an instance already at 3.6.

I've moved on from the context where I reported this but as I recall that capability was something added by Microsoft to my Cosmos account.  I recall getting them to add that capability to my production account through the support team in order to assure parity.

At this point I have no personal motivation to keep this issue open. If you would like to close it, please feel free and I will not object.  However, I would suspect the underlying matter of the handling of Microsoft changes to capability is unresolved.  Thank you for looking into it.

**Comment by katbyte** [comment]
closing as requested
