### ISSUE TITLE
Support graceful Linux/Windows VM shutdown

### ISSUE THREAD

**Issue by jstachowiak** [terraform-providers/terraform-provider-azurerm#8469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider forcefully skips the graceful shutdown period when destroying resources. This is undesirable in situations where we want the existing init system to stop the application properly.

For example, we want to use Terraform `create_before_destroy` behavior to migrate existing Nomad workloads from decommissioned nodes. The idea is that on shutdown, the init system toggles a drain mode on a given node.

### New or Affected Resource(s)

* azurerm_linux_virtual_machine
* azurerm_windows_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine" "test" {
  ...  
  skip_shutdown = false # Defaults to true to preserve the existing behavior.
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/poweroff
* https://azure.microsoft.com/en-gb/blog/linux-and-graceful-shutdowns-2

**Comment by jstachowiak** [comment]
I plan to submit a MR soon.

**Comment by jstachowiak** [comment]
I'll create a pull request soon.

**Comment by jstachowiak** [comment]
I'd appreciate some guidance on what tests to add since `resourceLinuxVirtualMachineDelete` and `resourceWindowsVirtualMachineDelete` functions have none.

**Comment by jstachowiak** [comment]
I'd appreciate some guidance on what tests to add since `resourceLinuxVirtualMachineDelete` and `resourceWindowsVirtualMachineDelete` functions are not exported.

**Comment by jstachowiak** [comment]
I'd appreciate some guidance on what tests to add since `resourceLinuxVirtualMachineDelete` and `resourceWindowsVirtualMachineDelete` have none.

**Comment by jstachowiak** [comment]
I'd appreciate some guidance on what tests to add since `resourceLinuxVirtualMachineDelete` and `resourceWindowsVirtualMachineDelete` functions have none.

**Comment by georgefrank** [comment]
This would also be useful for Consul server nodes being replaced with create_before_destroy, as you can set [leave_on_terminate](https://www.consul.io/docs/agent/options#leave_on_terminate) - without a graceful shutdown, cluster leadership does not transition cleanly.

**Comment by jstachowiak** [comment]
I added acceptance tests but `tflint`/`test` jobs failed with the following error:
```
golangci/golangci-lint info checking GitHub for tag 'v1.24.0'
golangci/golangci-lint crit unable to find 'v1.24.0' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
GNUmakefile:14: recipe for target 'tools' failed
make: *** [tools] Error 1
The command "make tools" failed and exited with 2 during .
Your build has been stopped.
```
I can see the tag, so I assume it's a glitch. Could someone please rerun these jobs?

**Comment by jstachowiak** [comment]
Hi @ArcturusZhang! Sorry for the direct ping but I wonder how we could move forward with this enhancement. It will enable a lot of interesting workflows.

**Comment by jstachowiak** [comment]
@ArcturusZhang, it's me again. @tombuildsstuff provided an awesome feedback in the PR, so you can ignore my previous comment. 💪
