### ISSUE TITLE
CORS block in azurerm_app_service is causing failure in app service deployment

### ISSUE THREAD

**Issue by anuradhaarao** [terraform-providers/terraform-provider-azurerm#8480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
# resource "azurerm_app_service" "testappservice" {
  name                = "testing-app-service"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = data.azurerm_app_service_plan.example.id

  site_config {
    dotnet_framework_version = "v2.0"
    cors {
      allowed_origins = ["https://foo-bar.com"]
    }
  }
```

### Expected Behavior

Should have added cors allowed origins to app service

### Actual Behavior

Error: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

  on app_service.tf line 140, in resource "azurerm_app_service" "appservice":
 140: resource "azurerm_app_service" "testappservice" {

### Steps to Reproduce

1. `add cors_block to site_config under azurerm_app_service`
2. `terraform apply`

### Important Factoids

Provider version ~> 2.14.0

### References

* #0000

**Comment by njuCZ** [comment]
@anuradhaarao I have tried your script, through the [debug](https://www.terraform.io/docs/internals/debugging.html) log, we could find the real reason for this problem:  Cannot update the site 'testing-app-service' because the integrated CORS feature does not support the target .NET Framework version.
So this is not a terraform issue, but a backend service restriction.

**Comment by anuradhaarao** [comment]
@njuCZ  - oh my bad. Tried that, it works now. Thanks!
