### ISSUE TITLE
Documentation bug for default_node_pool in azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by tjololo** [terraform-providers/terraform-provider-azurerm#8501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.27.0

### Affected Resource(s)

Documentation bug

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "${var.prefix}-k8s"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "${var.prefix}-k8s"
  kubernetes_version  = 1.17.9

  default_node_pool {
    name                = "default"
    enable_auto_scaling = true
    node_count          = 1
    min_count           = 1
    max_count           = 2
    vm_size             = "Standard_DS2_v2"
    orchestrator_version = 1.17.9 #according to the documentation this field is not available if enable_auto_scaling = true
  }
#....
}
```

### Expected Behavior

According to the documentation the orchestrator_version should not be available/have any affect if enable_auto_scaling is set to true.

### Actual Behavior

To upgrade default node pool kubernetes_version the orchestrator_version needs to be updated.
The field is also set at creation time if omitted in my terraform scripts

### Steps to Reproduce

1. `terraform apply` with kubernetes_version and orchestrator_version set to 1.17.9
2. Update terraform kubernetes_version and orchestrator_version to 1.18.8
3. `terraform apply` cluster and default_node_pool is updated to version 1.18.8 (as expected I would say)

### References

https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#orchestrator_version

**Comment by njuCZ** [comment]
@tjololo the doc says the orchestrator_version won't auto-upgrade. Upgrading the kubernetes_version will not automatically upgrade orchestrator_version. It does not mean this field is not available if enable_auto_scaling = true.

The actual behaviour based on your description is right

**Comment by tjololo** [comment]
@njuCZ  When I read through the documentation the orchestrator_version is after this line:
> If enable_auto_scaling is set to false, then the following fields can also be configured:

If this field is valid for enable_auto_scaling=false and enable_auto_scaling=true maybe it should be moved up like it is in the documentation for azurerm_kubernetes_cluster_node_pool?

**Comment by njuCZ** [comment]
@tjololo yes, you are right! Sorry for missing this. I will submit a PR soon to move it up
