### ISSUE TITLE
Support for more than two client certificate thumbprint sections for Azure Service Fabric Cluster

### ISSUE THREAD

**Issue by viktors-telle** [terraform-providers/terraform-provider-azurerm#8506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for more than two client certificate thumbprint sections for the `azurerm_service_fabric_cluster` resource. Currently, you can add only two certificate thumbprints.

> client_certificate_thumbprint - (Optional) One or two client_certificate_thumbprint blocks as defined below.

### New or Affected Resource(s)

* azurerm_service_fabric_cluster

### Potential Terraform Configuration

```hcl
client_certificate_thumbprint {
    thumbprint        = ""
    is_admin          = true
}

client_certificate_thumbprint {
    thumbprint        = ""
    is_admin          = true
}

client_certificate_thumbprint {
    thumbprint        = ""
    is_admin          = true
}

...
```

### References

https://www.terraform.io/docs/providers/azurerm/r/service_fabric_cluster.html#client_certificate_thumbprint

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems it works fine to create more than two client certificate thumbprints. So I made a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8521) for this issue. Hopes it would be helpful.

**Comment by viktors-telle** [comment]
Looks good to me, thank you for such a quick response!
