### ISSUE TITLE
azurerm_function_app_host_keys unusable unless function has already be created

### ISSUE THREAD

**Issue by andrew-sumner** [terraform-providers/terraform-provider-azurerm#8515]
### Terraform (and AzureRM Provider) Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0
+ provider registry.terraform.io/hashicorp/external v1.2.0

### Affected Resource(s)

* `azurerm_function_app_host_keys`

### Terraform Configuration Files

```hcl
...

resource "azurerm_function_app" "item" {
  name                                      = "BugExample"
  resource_group_name           = module.lookup.azurerm_resource_group.name
  location                                  = module.lookup.azurerm_resource_group.location
  app_service_plan_id               = module.lookup.azurerm_app_service_plan.id
  storage_account_name          = module.lookup.azurerm_storage_account.name
  storage_account_access_key  = module.lookup.azurerm_storage_account.primary_access_key
  version                                    = "~1"
  client_affinity_enabled            = false
  app_settings                            = {}
  identity {
    type = "SystemAssigned"
  }
  site_config {
    always_on = true
  }
}

data "azurerm_function_app_host_keys" "item" {
  name                = azurerm_function_app.item.name
  resource_group_name = azurerm_function_app.item.resource_group_name
}

output "azurerm_function_app_host_keys" {
  value = data.azurerm_function_app_host_keys.item  
}
```

### Debug Output

```
terraform apply
module.lookup.data.azurerm_resource_group.item: Refreshing state...
module.lookup.data.azurerm_key_vault.item[0]: Refreshing state...
module.lookup.data.azurerm_storage_account.item[0]: Refreshing state...
module.lookup.data.azurerm_servicebus_namespace.item[0]: Refreshing state...
module.lookup.data.azurerm_app_service_plan.item[0]: Refreshing state...
module.lookup.data.azurerm_application_insights.item[0]: Refreshing state...

Error: cannot read ID for AzureRM Function App "BugExample" (Resource Group "ice-example-rg")

  on main.tf line 83, in data "azurerm_function_app_host_keys" "item":
  83: data "azurerm_function_app_host_keys" "item" {
```

### Expected Behavior

The function should have been created before azurerm_function_app_host_keys attempts to read the values as there is a dependency between azurerm_function_app_host_keys and the function app.

### Actual Behavior

azurerm_function_app_host_keys failed because the function hasn't been created yet.

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`

**Comment by andrew-sumner** [comment]
I was able to get this to work by adding `depends_on` parameter:

```
data "azurerm_function_app_host_keys" "item" {
  name                = azurerm_function_app.item.name
  resource_group_name = azurerm_function_app.item.resource_group_name

  depends_on = [
    azurerm_function_app.item
  ]
}
```
Shouldn't this be the default behavior, not something that needs to be forced?

**Comment by njuCZ** [comment]
@andrew-sumner this seems an issue for terraform 0.13. You could take a look at that issue. For workaround, you could use depends_on or use terraform 0.12

**Comment by 3mard** [comment]
@njuCZ I wonder why the test case is passing if that's true. any idea what terraform version does the test suit uses ?

**Comment by njuCZ** [comment]
@3mard for terraform 0.12.x there is no problem for such case. for terraform 0.13.x, according to the terraform issue I mentioned above, the maintainer says if all value of a data source can be determined under plan phase (azurerm_function_app.item.name and azurerm_function_app.item.resource_group_name is known), terraform will read the data source immediately rather than wait for dependency, so it will reports error beucase it does not exist

**Comment by 3mard** [comment]
@njuCZ thanks for the clarification!
However, it doesn't solve the mystery for me! 
There is a test case that exactly does what @andrew-sumner  is trying to do
 https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/web/tests/data_source_function_app_host_keys_test.go
(creates a new function, gets the key , asserts the key exists )

**Comment by njuCZ** [comment]
@3mard currently the acctest is not using terraform, it has its own test framework. So there might be some difference between acctest and specific terraform version

**Comment by tombuildsstuff** [comment]
👋 

Since this appears to be a bug in Terraform 0.13 - I'm going to close this in favour of the upstream issue: https://github.com/hashicorp/terraform/issues/26074 - would you mind subscribing to that issue for updates?

Thanks!
