### ISSUE TITLE
azurerm_policy_assignment - Unable to create policy assignments with parameters 

### ISSUE THREAD

**Issue by anirbansingharoy** [terraform-providers/terraform-provider-azurerm#8527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform Version : 0.13.2
Provider Version: 2.27.0

### Affected Resource(s)

* `azurerm_policy_assignment`

### Terraform Configuration Files

```hcl
resource "azurerm_policy_assignment" "no-privileged-containers" {
  name                 = "restricted-standards"
  policy_definition_id = "/providers/Microsoft.Authorization/policySetDefinitions/42b8ef37-b724-4e24-bbc8-7a7708edfe00"
  scope                = azurerm_kubernetes_cluster.test-cluster.id
  enforcement_mode     = false
  parameters           = <<PARAMETERS
  {
    "effect": "Audit",
    "excludedNamespaces": {
      "value": [
        "kube-system",
        "gatekeeper-system",
        "azure-arc",
        "management"
      ]
    }
  }
  PARAMETERS
}
```

### Expected Behavior

We should be able to create policy assignments.

### Actual Behavior

```hcl
Error: expanding JSON for `parameters` "  {\n    \"effect\": \"Audit\",\n    \"excludedNamespaces\": {\n      \"value\": [\n        \"kube-system\",\n        \"gatekeeper-system\",\n        \"azure-arc\",\n        \"management\"\n      ]\n    }\n  }\n": json: cannot unmarshal string into Go value of type policy.ParameterValuesValue
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ArcturusZhang** [comment]
Hi @anirbansingharoy thanks for this issue!

Per the convention in policy assignment parameters, in the `parameters` JSON string, every value of the entry must be a JSON object with a key of `value`. Could you please try the following config:
```
resource "azurerm_policy_assignment" "no-privileged-containers" {
  name                 = "restricted-standards"
  policy_definition_id = "/providers/Microsoft.Authorization/policySetDefinitions/42b8ef37-b724-4e24-bbc8-7a7708edfe00"
  scope                = azurerm_kubernetes_cluster.test-cluster.id
  enforcement_mode     = false
  parameters           = <<PARAMETERS
  {
    "effect": {
      "value": "Audit"
    },
    "excludedNamespaces": {
      "value": [
        "kube-system",
        "gatekeeper-system",
        "azure-arc",
        "management"
      ]
    }
  }
  PARAMETERS
}
```

**Comment by anirbansingharoy** [comment]
Hi @ArcturusZhang , Thanks for your help.  It worked for me 👍
