### ISSUE TITLE
[Feature Request] Support for gitRepo Volume Mount in ACI

### ISSUE THREAD

**Issue by seffyroff** [terraform-providers/terraform-provider-azurerm#853]
### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
- azurerm_container_group

### Expected Behavior
What should have happened?
When defining an ACI, the functionality exists within Azure RM to [mount a remote Git Repo](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-gitrepo).  This is soooper handy.  Right now it seems like TF only supports the azureFile mounts.  At an API level, the gitRepo endpoints appear to be [well documented](https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/createorupdate#volume).

**Comment by metacpp** [comment]
@seffyroff Thanks for opening this issue. We're using #1860 to track this feature request, hope you don't mind that I close this one.

You can still leave the comment here and we'll respond in time.
