### ISSUE TITLE
Support for AAD based RBAC on Azure Kubernetes

### ISSUE THREAD

**Issue by shashankbarsin** [terraform-providers/terraform-provider-azurerm#8535]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This feature allows using Azure Active Directory based role assignments to control authorization checks on Azure Kubernetes Service clusters.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"
  
  aad_role_based_access_control = "true"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Production"
  }
}
```

### References
* https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac

**Comment by mbfrahry** [comment]
Hey @shashankbarsin, thanks for opening this issue. 

I do see that we support [role_based_access_control](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#azure_active_directory) which allows you to specify the information needed to work with Azure Active Directory for kubernetes clusters. Is that what you're looking for are we still missing something related to AAD and kubernetes clusters.

**Comment by aristosvo** [comment]
I think @shashankbarsin refers to https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac . All other options (managed AAD and K8sRBAC enablement) are already present.

Azure RBAC for AKS is in preview and needs enablement on the cluster before Kubernetes roles can be assigned with Azure RBAC. The option is already present in the latest version of the AKS API AFAIK.

**Comment by shashankbarsin** [comment]
@mbfrahry The AAD profile block currently supported in Terraform under role_based_access_control is actually used only for authentication and not for authorization. Ideally the whole AAD profile block should be outside role_based_access_control similar to the swagger schema and ARM template. The feature I proposed requires managed AAD v2, but it's an optional feature within that. In that context, here's an example request sent to the ARM API for AKS cluster creation.

```json
{
  "location": "westus2",
  "properties": {
    "kubernetesVersion": "",
    "dnsPrefix": "dnsprefix6",
    "agentPoolProfiles": [
      {
        "name": "nodepool1",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "osType": "Linux",
        "type": "VirtualMachineScaleSets",
        "availabilityZones": [
          "1",
          "2",
          "3"
        ],
        "mode": "System"
      }
    ],
    "networkProfile": {
      "loadBalancerSku": "standard",
      "outboundType": "loadBalancer",
      "loadBalancerProfile": {
        "managedOutboundIPs": {
          "count": 2
        }
      }
    },
    "autoScalerProfile": {
      "scan-interval": "20s",
      "scale-down-delay-after-add": "15m",
      "balance-similar-node-groups": "true"
    },
    "servicePrincipalProfile": {
      "clientId": "a6f8fc57-197d-4cd8-bc85-a65b15ff2327",
      "secret": "918b4bdb-5e50-45f2-8801-980f72c0b1f1"
    },
    "addonProfiles": {},
    "aadProfile": {
      "managed": true,
      "enableAzureRBAC": true
    },
    "enableRBAC": true
  }
}
```

Also here's the [full swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/f64d232ce9d05ca4cb06c2ef319df501890e2327/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-09-01/managedClusters.json#L2774) for reference.

To replicate the aadProfile and enableRBAC part as shown above, it will a breaking change for users. But it makes sense to have `azure_active_directory` block outside `role_based_access_control` from a user experience perspective. In fact we are already getting support issues reported due to users expecting the Azure RBAC feature to be available when the `azure_active_directory` block is set within  `role_based_access_control`.  In that context, what are the options available to introduce [AAD RBAC feature](https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac) in Terraform?

**Comment by shashankbarsin** [comment]
Here's the spec I propose to address authn/authz requirements:

```hcl
identity {
    authentication {
      aad_authentication      = true
      admin_group_object_ids  = [for key, value in local.cluster_admins : value.object_id] 
    }

    authorization {
      rbac_enabled            = true
      azure_rbac_enabled      = true  #only applicable if aad_authentication == true and rbac_enabled == true
    }
}
```

**Comment by aristosvo** [comment]
@shashankbarsin I hope you don't mind, but for a start I've implemented it as I proposed [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8535#issuecomment-695823970).

If it makes more sense to the HC maintainers to review the AuthN/AuthZ structure we can definitely change it, but based on my experience I suspect we move forward without breaking the current implementation until a major release.

**Comment by shashankbarsin** [comment]
@aristosvo we are getting feedback mails from customers on confusion between AAD authn and authz due to the current syntax nesting even the authn part under role_based_access_control.  I think that if we go ahead with the current syntax, it'll lead to more confusion for the users. Let's discuss this issue further with the maintainers.

**Comment by aristosvo** [comment]
I understand your concern better now. To be honest, the confusion of it being nested under `role_based_access_control` is easier to address then moving to a completely different structure, which also differs from the Azure APIs.

Unfortunately, biggest part of the confusion should be solved by the Azure team, as introducing new concepts and diverging from the Azure API structure with Terraform makes it only more confusing.

Is a structure like below already tackling your concerns? This is easier to achieve with a good depreciation tactic than your proposal.

```hcl
role_based_access_control {
   enabled = true
}

azure_active_directory_profile {
   managed                 = true
   azure_rbac_enabled      = true
   admin_group_object_ids  = [for key, value in local.cluster_admins : value.object_id] 
}
```

**Comment by shashankbarsin** [comment]
Having `azure_rbac_enabled` outside `role_based_access_control` I think is still a little confusing. I propose a small change to the experience I had shared earlier on the issue. Here I've moved authentication and authorization out of identity and we can have it at the top level. The clear grouping/differentiation of authentication and authorization will still provide clarity on which scenario each of these specific AAD controls are for:

```hcl
authentication {
  aad_authentication      = true
  admin_group_object_ids  = [for key, value in local.cluster_admins : value.object_id] 
}

authorization {
  rbac_enabled            = true
  azure_rbac_enabled      = true  #only applicable if aad_authentication == true and rbac_enabled == true
}
```

**Comment by aristosvo** [comment]
A few remarks. Feel free to contact me on the Terraform azure provider slack, maybe easier than here ;-)

- Why `admin_group_object_ids` in `authentication`?
  It feels like `authorization` to me..
  
- What about all the other objects in `role_based_access_control.azure_active_directory`?
  Your suggestion creates some extra work. I'm happy to contribute, but it is work which has to be done. Enabling this feature with a minimal restructuring effort is easier than to restructure existing resources in a backwards compatible way

- What about the customers who are used to the Azure API structure?
  The current structure is approximately the same as the Azure APIs, except for the nesting in `role_based_access_control`.  It is already mostly structured (like the Azure API), but around the technical components involved instead based on the functional distinction of AuthZ and AuthN.

  Grouping `azure_rbac_enabled` makes sense to me from a technical point of view, as I expect Azure RBAC to go through Azure AD. To keep this Terraform provider maintainable and simple, it is easier to follow Azure more or less than to go our own way.

To be honest, it is a mess when you first `azurerm_kubernetes_cluster` and engineers working with it should know a lot before it makes sense. `azurerm_kubernetes_cluster` is quit a resource, with more features than most customers will use. To really work with it, you have to know about the concepts like Azure RBAC, AuthN, AuthZ, AD, but also how this translates to Kubernetes access. This is quit hard, and I am always trying to make onboarding as easy as possible, I'm just not convinced that your suggestion will make it easier for everybody and is worth the energy.

I think most of the mess should first be solved by Azure. Terraform is simply a layer, API translation kinda tool. 

As a suggestion: if you want to abstract the complexity, it is probably a lot easier to build a module with sane defaults which abstracts 90% of the complexity than to restructure an Terraform resource!
