### ISSUE TITLE
Not able to do role assignment on Role definition on New Release 2.28.0

### ISSUE THREAD

**Issue by suriya91** [terraform-providers/terraform-provider-azurerm#8547]
Tried creating the role definition provided on the terraform documentation .

Reference doc : https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html

code :

data "azurerm_subscription" "primary" {
}

data "azurerm_client_config" "example" {
}

resource "azurerm_role_definition" "example" {
  name               = "my-custom-role-definition"
  scope              = data.azurerm_subscription.primary.id

  permissions {
    actions     = ["Microsoft.Resources/subscriptions/resourceGroups/read"]
    not_actions = []
  }

  assignable_scopes = [
    data.azurerm_subscription.primary.id,
  ]
}

resource "azurerm_role_assignment" "example" {
  scope              = data.azurerm_subscription.primary.id
  role_definition_id = azurerm_role_definition.example.id
  principal_id       = data.azurerm_client_config.example.object_id
}

terraform apply:

Getting below Error : 
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRoleDefinitionId" Message="The role definition ID '072dd7ad-7dc5-fe96-411f-a4a223b5d3cf|' is not valid."

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0

Please look into this issue.

**Comment by kensykora** [comment]
Seeing the same thing. Fortunately there is a workaround -- Here is our terraform plan. note how the resource Id has a `|` with another reference to a particular subscription after it.

```
  # azurerm_role_assignment.ado-service-principal-vnet-peering-vnet01-uat will be created
  + resource "azurerm_role_assignment" "ado-service-principal-vnet-peering-vnet01-uat" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = "3defe365-2eb3-41c7-a025-55649d591ede"
      + principal_type                   = (known after apply)
      + role_definition_id               = "/subscriptions/12772dbc-1865-4692-bd55-123903f9727a/providers/Microsoft.Authorization/roleDefinitions/c4a36f19-2ac1-de10-be53-2f72cdd39198|/subscriptions/12772dbc-1865-4692-bd55-123903f9727a"
      + role_definition_name             = (known after apply)
      + scope                            = "/subscriptions/12772dbc-1865-4692-bd55-123903f9727a/resourceGroups/azwe01rg01/providers/Microsoft.Network/virtualNetworks/azwe01vnet01"
      + skip_service_principal_aad_check = (known after apply)
    }
```

I was able to workaround this by splitting on the `|` and using the first part with the actual resource ID. Modifying my resource definition as such:

```hcl
resource "azurerm_role_assignment" "ado-service-principal-vnet-peering-vnet01-uat" {
  scope              = "/subscriptions/${local.subscriptions.prod}/resourceGroups/azwe01rg01/providers/Microsoft.Network/virtualNetworks/azwe01vnet01"
  role_definition_id = split("|", azurerm_role_definition.vnet-peer-manager.id)[0]
  principal_id       = local.azure_dev_ops_service_principals.uat.object_id

  provider = azurerm.dev
}
```

**Comment by njuCZ** [comment]
@suriya91 sorry for the inconvience. In recent version, there are some breaking changes for "azurerm_role_definition" because the backend service changed the behaviour. there is a new field introduced for resource "azurerm_role_definition": https://www.terraform.io/docs/providers/azurerm/r/role_definition.html#role_definition_resource_id   we could use this field ranther than the `id` field.
```
resource "azurerm_role_assignment" "example" {
    scope              = data.azurerm_subscription.primary.role_definition_resource_id
    role_definition_id = azurerm_role_definition.example.id
    principal_id       = data.azurerm_client_config.example.object_id
}
```

I will also submit a PR to update the doc soon.
