### ISSUE TITLE
azurerm_application_insights_web_test invalid scope

### ISSUE THREAD

**Issue by davejhahn** [terraform-providers/terraform-provider-azurerm#8551]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.28
+ provider.azurerm v2.27.0

### Affected Resource(s)
* `azurerm_monitor_metric_alert`

### Terraform Configuration Files

```hcl

resource "azurerm_application_insights_web_test" "webtest" {
  name                    = "webtest"
  location                = azurerm_resource_group.monitor_rg.location
  resource_group_name     = azurerm_resource_group.monitor_rg.name
  application_insights_id = azurerm_application_insights.app_insights.id
  kind                    = "ping"
  frequency               = 300
  timeout                 = 120
  enabled                 = true
  retry_enabled           = true
  geo_locations           = var.geo_locations
  configuration           = var.webtest

  lifecycle {
    ignore_changes = [
      tags
    ]
  }  
}

resource "azurerm_monitor_metric_alert" "webtest" {
    name                = "availability-webtest"
    resource_group_name = azurerm_resource_group.monitor_rg.name
    scopes              = [azurerm_application_insights_web_test.webtest.id,azurerm_application_insights.app_insights.id]
    description         = "Availability monitoring"
    enabled             = true
    auto_mitigate       = true
    frequency           = "PT5M"
    severity            = var.availability_severity
    application_insights_web_test_location_availability_criteria {
        web_test_id             = azurerm_application_insights_web_test.webtest.id
        component_id            = azurerm_application_insights.app_insights.id
        failed_location_count   = 2      
    }

    action {
        action_group_id = azurerm_monitor_action_group.primary.id
    }
    action {
        action_group_id = azurerm_monitor_action_group.secondary.id
    }      
}
```

### Debug Output
Error: Error creating or updating metric alert "availability-webtest" (resource group "xxxxxxxxxxxrg001"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Alert scope is invalid. Activity ID: XXXXXX-XXXX-XXXXXX-XXXXXXX."

  on metric_alert.tf line 1, in resource "azurerm_monitor_metric_alert" "webtest":
   1: resource "azurerm_monitor_metric_alert" "webtest" {

### Expected Behavior

Alert created

### Actual Behavior

Failed with scope error

The webtest is created and looks fine.  Just unable to create the alert.

**Comment by davejhahn** [comment]
It appears that you must have BOTH the WebTest and App Insights as part of the scope (and if you do, this error disappears).  However, the problem is that Terraform is not preserving the scope order and the WebTest scope must be before the App Insights scope or it is not added in Azure.  

If you look at the trace logs, regardless of the order that the scope is provided in Terraform, it always is in the same order, with the App Insights before the Web Test.

```hcl
{
 "location": "global",
 "properties": {
  "description": "My alert",
  "severity": 3,
  "enabled": true,
  "scopes": [
   "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/microsoft.insights/components/myappinsights",
   "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/microsoft.insights/webtests/mywebtest"
  ],
  "evaluationFrequency": "PT1M",
  "windowSize": "PT5M",
  "targetResourceType": "",
  "targetResourceRegion": "",
  "criteria": {
   "componentId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/microsoft.insights/components/myappinsights",
   "failedLocationCount": 2,
   "odata.type": "Microsoft.Azure.Monitor.WebtestLocationAvailabilityCriteria",
   "webTestId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/microsoft.insights/webtests/mywebtest"
  },
  "autoMitigate": true,
  "actions": []
 },
 "tags": {
  "hidden-link:/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/myResourceGroup/providers/microsoft.insights/components/myappinsights": "Resource",
  "hidden-link:/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/myResourceGroup/providers/microsoft.insights/webtests/mywebtest": "Resource"
 }
}
```
e.g.
/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/microsoft.insights/components/myappinsights

and
/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/microsoft.insights/webtests/mywebtest

/components comes before /webtests, regardless of the order specified in Teraform.

If I take the JSON from the TRACE, change the order, and do a REST PUT to Azure, it works perfect.  Delete alert, change it back with App Insights before Web Test, it only adds the App Insights to the scope.

It seems that the order of the list was preserved in Terraform with https://github.com/hashicorp/terraform/issues/10747 - so I'm not sure if it resurface or if it is something happening internal to AzureRM.

What it comes down to is that there is no way to properly scope a web_test alert.  

On a side note, I also realized that you must add tags with hidden-link to both of the same resources for the UI to work properly.  If they aren't there, when you select Open Alerts, it just opens the web test.  Although this isn't an AzureRM issue, it would be nice to see that documented there, because it took me a bit of time to figure that out and it's doubtful that anyone would know that unless they had previously used the ARM template to do the same thing.

Any thoughts on how I can force the order?  Is it a resurfaced bug in Terraform?  Or is it something being done specifically in AzureRM, can we change it?

**Comment by magodo** [comment]
Hey @davejhahn Thank you for submitting this and digging quite deep to the problem.

From your description above, there seems to be two problems:

1. The "incorrect" scope order (appinsight - webtest) will cause the scope of webtest not added

    I noticed that with either ordering the scope are all set to the API (as you can see it is returned from the response). But the Portal seems to have some visual bug causing in some provision you only see the scope set to webtest and in some provision you only see the scope set to app insights.

    But you can still access the alert rule in both resources by clicking **Alerts** -> **Manage Alert Rules**. I wonder whether you have some functional issues?

2. The absense of the hidden-link tag will cause some UI issue

    I wonder what hidden-link should be set to tag and what UI issue will be caused otherwise? If they are not set, *when you select Open Alerts, it just opens the web test*. Would you please give more clues? In my case, everything works fine as I mentioned above.

**Comment by davejhahn** [comment]
@magodo 

Based on your comments, I did a little more experimenting, and it seems like this is in fact a UI problem in Azure tied to the hidden-link tags, which seem to be used internally to the UI to connect resources or possibly even something else, although I don't have anything to support that other than what I am seeing.  I don't think it has anything to do with scope order anymore.

If you create an alert using Terraform without the hidden link tags, you can't access the alert through the web test (go into a web test, under availability, select ..., then Open Alert Rules)--it just opens up the edit page.  But you can access by going into App Insights, Manage Alert Rules.

So if the tags are not there, you can't access through the Web Test (only through Manage Alerts in App Insights).  But, if you create the alert through Terraform with the tags, you can access it in both places, BUT the scope is still wrong.  

What I found is that if I do a GET on the resource through Postman, it works after that--works meaning the correct scope is displayed and it is accessible from either method (Web Test or App Insights).  This is the case whether I supply the tags or not in Terraform--after a GET everything just works in either case.

There is a tag for each resource in scope (same as the scope), and look like:

  "tags": {
    "hidden-link:/subscriptions/XXX/resourcegroups/XXX/providers/microsoft.insights/components/XXX": "Resource",
    "hidden-link:/subscriptions/XXX/resourcegroups/XXX/providers/microsoft.insights/webtests/XXX": "Resource"
  },

So to answer your question, I did not verify there is a functional problem, I didn't proceed because it didn't look correct.  But, based on what I am seeing, I think this is purely a UI issue in Azure and wouldn't affect the functionality.  I am going to proceed with that assumption.

I don't know if these tags  are 100% the cause, but it definitely seems to impact the UI, that I've confirmed by not supplying them and not being able to open the alerts when missing through the web test directly.

I'm good with closing this because I don't think it's a Terraform issue at all now.   Will leave open for a bit.  At minimum, someone else can find this and not pull their hair out for a day like I did.

**Comment by davejhahn** [comment]
@magodo unfortunately it looks like it does impact the functionality.  When a web test has a failed availability condition, the associated alert doesn't fire if it is showing it scoped to app insights only.

**Comment by magodo** [comment]
@davejhahn Thank you a lot for providing this follow-up investigations :+1:

In fact, during the `terraform apply` process, it will make a GET right after the PUT, so I am not sure whether another GET via other means would somehow fix this UI issue. On the other hand, if those two tags could solve the issue, you are free to add it explicitly using `tags` property.

**Comment by davejhahn** [comment]
@magodo I think that after more testing, there is just some weird UI stuff going on.  

If I don't add the tags, some of the alerts show the correct scope, some don't, seems to change when I go back later, so I really don't know what the pattern is.  But, it doesn't appear to affect the core functionality for the alerts, only not being able to view the alert off the availability test, which that also seems to be inconsistent.  

Since I can always get in from the manage alerts and the core functionality of triggering the alerts is working, it's not really a big deal.  

Appreciate your assistance.  Going to close this because I don't see anything being caused by azurerm.

Thanks again!

Dave
