### ISSUE TITLE
azurerm_lighthouse_definition role_definition_id doesn't take resource address 

### ISSUE THREAD

**Issue by jdaminato** [terraform-providers/terraform-provider-azurerm#8553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0

### Affected Resource(s)

* azurerm_lighthouse_definition

### Terraform Configuration Files

```hcl
locals {
  roles = ["Contributor", "Reader", "Managed Services Registration assignment Delete Role"]
  abc_tenant = "xxx-xxx-xxx-xxx-xxxx"
}

data "azurerm_subscription" "main" {}

data "azurerm_role_definition" "roles" {
  for_each = toset(local.roles)
  name = each.value
}

resource "azurerm_lighthouse_definition" "reader" {
  name = "ABC Managed Services"
  description = "ABC 1234"
  managing_tenant_id = local.abc_tenant
  scope = data.azurerm_subscription.main.id

  authorization {
    principal_id = "9734c1bd-4945-4d6d-95b4-76517ac296c4"
    role_definition_id = data.azurerm_role_definition.roles["Reader"].id
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Should accept the long format role ID (no error).

### Actual Behavior

Error: expected "authorization.0.role_definition_id" to be a valid UUID, got /providers/Microsoft.Authorization/roleDefinitions/91c1777a-f3dc-4fae-b103-61d183457e46

  on arm.tf line 22, in resource "azurerm_lighthouse_definition" "reader":
  22: resource "azurerm_lighthouse_definition" "reader" {

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Work around: role_definition_id = split("/", data.azurerm_role_definition.roles["Reader"].id)[4]

authorization/role_definition_id should accept the longer form ID rather than purely the uuid.
data.azurerm_role_definition does not output in the pure uuid form, which makes using this more complex than needed.

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems terraform returns resource id not role definition id while passing retrieving role definition by name. So I submit a PR to fix it.

**Comment by tombuildsstuff** [comment]
hi @jdaminato 

In the Terraform Configuration above you're using the Resource ID and not the UUID (available as `role_definition_id`) - where the API requires the UUID (and not the Resource ID) - as such you should be able to fix this by updating the Terraform Configuration here.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by jdaminato** [comment]
Hi @tombuildsstuff,

The azurerm provide v2.28.0 returns Resource ID for both role_definition_id and id. It does not return just the UUID as suggested. So the error is the same either way (I had tested both cases and show the evidence of that below).

The azurerm_lighthouse_definition resource is new with 2.28.0, and I think this is a case of this new module being inconsistent with other azurerm resources in the use of uuid versus resource id.

Thanks for reviewing - I had initially through role_definition_id would match up content-wise (which the naming would imply), but here the resource I think is inconsistent.

So I believe this remains a bug.

Cheers!

```
Error: expected "authorization.0.role_definition_id" to be a valid UUID, got /providers/Microsoft.Authorization/roleDefinitions/91c1777a-f3dc-4fae-b103-61d183457e46

  on main.tf line 64, in resource "azurerm_lighthouse_definition" "definitions":
  64: resource "azurerm_lighthouse_definition" "definitions" {
```

> hi @jdaminato
> 
> In the Terraform Configuration above you're using the Resource ID and not the UUID (available as `role_definition_id`) - where the API requires the UUID (and not the Resource ID) - as such you should be able to fix this by updating the Terraform Configuration here.
> 
> This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).
> 
> Thanks!

**Comment by jdaminato** [comment]
Hi @tombuildsstuff @neil-yechenwei  -

Just checking in on this one - I believe this was closed in error as a UUID is not available on source modules, i.e. data.azurerm_role_definition.role_definition_id and data.azurerm_role_definition.id are both resource ids. So this new resource azurerm_lighthouse_definition does not work consistently with other modules.

Cheers
