### ISSUE TITLE
ignore_changes not working | azurerm_kubernetes_cluster network_profile

### ISSUE THREAD

**Issue by paulpuvi06** [terraform-providers/terraform-provider-azurerm#8563]
### Terraform (and AzureRM Provider) Version

terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.24.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
    lifecycle {
    ignore_changes = [
      network_profile
    ]
  }
  
  name                = local.clustername
  location            = azurerm_resource_group.aks.location
  resource_group_name = azurerm_resource_group.aks.name
  dns_prefix          = replace(local.clustername, "-", "")
  kubernetes_version  = var.k8_version #"1.17.9"
  node_resource_group = local.noderg
  api_server_authorized_ip_ranges = var.authorized_ip_ranges

  addon_profile {
    kube_dashboard {
      enabled = false
    }

    oms_agent {
      enabled = false
    }
  }

  default_node_pool {
    name                = "default"
    max_pods            = var.max_pods
    os_disk_size_gb     = "100"
    vm_size             = var.vm_size
    vnet_subnet_id      = azurerm_subnet.aks.id
    enable_auto_scaling = true
    node_count          = var.node_count
    min_count           = 1
    max_count           = 10

  }

  network_profile {
    network_plugin     = "azure"
    network_policy     = "calico"
    dns_service_ip     = "172.32.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
    service_cidr       = "172.32.0.0/16"
  }

  role_based_access_control {
    enabled = true

    azure_active_directory {
      admin_group_object_ids = ["XXXXXXXXX"] 
      managed                = true
    }
  }
  identity {
    type = "SystemAssigned"
  }

  tags = local.common_tags

}
```

### Panic Output

n/a

### Expected Behavior

I am trying to use same IP for inbound and outbound. I can achieve this by deploying ingress controller and bind the IP to outbound rule in SLB. 

    lifecycle {
    ignore_changes = [
      network_profile
    ]
  }

this should ignore the changes in load_balancer_profile section.

### Actual Behavior

1. Create AKS cluster(VMSS) using Terraform.
2. Deploy nginx ingress and bind the ip to outbound rule.
3. Remove Outbound ip created by terraform.
4. Run terraform apply (this will create new outbound ip and update outbound rule to new ip)

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. May I ask some questions for further investigation.
1. May I ask what means "ignore_changes not working"? Could you provide the error/warning?
2. How to deploy nginx ingress and bind the ip to outbound rule? Could you share the tfconfig?
3. How to remove Outbound ip created by terraform? Could you share the tfconfig?

**Comment by paulpuvi06** [comment]
@neil-yechenwei  Sure .

Once the cluster is provisioned using terraform, i have removed the outbound IP and updated outbound rule to use nginx IP in the portal (Manual step). it works , but if i rerun the terraform apply, it is creating new Outbound IP and updating the outbound rule to use new IP.

1. May I ask what means "ignore_changes not working"? Could you provide the error/warning?
   **There is no error / warning.** 

2. How to deploy nginx ingress and bind the ip to outbound rule? Could you share the tfconfig?
**I have deployed nginx using helm chart and here is the tf code . I have to update outbound rule manually in portal after this deployment.**
```
resource "helm_release" "nginx-ingress" {
  count            = var.deploy ? 1 : 0
  name             = "nginx"
  namespace        = "nginx"
  create_namespace = true
  repository       = "https://kubernetes.github.io/ingress-nginx"
  chart            = "ingress-nginx"
  version          = var.nginx_version
  cleanup_on_fail  = true
  max_history      = "2"
  lint             = true


  values = [templatefile("${path.module}/ingress.yaml.tpl", {
    ip = var.public_ip
  })]

}
```
3. How to remove Outbound ip created by terraform? Could you share the tfconfig?
    **This is manual change in the Azure portal.**

4. When to add ignore_changes
     **Since we do the changes manually in the portal for outbound IP, i thought **ignore_changes** block would ignore the manual changes when we rerun the terraform apply . But it has created new IP and updated Outbound rule .**

```
lifecycle {
    ignore_changes = [
      network_profile
    ]
  }

```

**Comment by paulpuvi06** [comment]
@neil-yechenwei any suggestions ? whatever changes we do on loadbalancer profile (rules, frontend ip updates) level is getting reverted when we re-run terraform apply.

**Comment by neil-yechenwei** [comment]
May I ask how to bind new ip to outbound rule and how to remove Outbound ip?

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if your able to reply to the above comment then we can take another look.

Thanks!
