### ISSUE TITLE
Feature Request: Application Gateway Backend Pool in VMSS

### ISSUE THREAD

**Issue by squiggleuk** [terraform-providers/terraform-provider-azurerm#857]
### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.1

### Affected Resource(s)
 azurerm_virtual_machine_scale_set (When used with azurerm_application_gateway)

I'm deploying **azurerm_virtual_machine_scale_set** with **azurerm_application_gateway**, but I can't see a way to associate the VMSS nodes, with the backend pool.

It can be done successfully using **azurerm_lb**...

azurerm_virtual_machine_scale_set.network_profile.ip_configuration.load_balancer_backend_address_pool_ids = ["${azurerm_lb_backend_address_pool.bpepool.id}"]

But if I swap out the backend pool id for one used by **azurerm_application_gateway** I get the following error:

ag-beap is referencing resource of a wrong type. The Id is expected to reference resources of type loadBalancers/backendAddressPools. 

Should there be another attribute under azurerm_virtual_machine_scale_set.network_profile.ip_configuration - Like application_gateway_backend_pools?

...or maybe there is another way to do this that I'm missing?

**Comment by tombuildsstuff** [comment]
Hey @squiggleuk 

Thanks for opening this issue :)

Taking a quick look into this - [it appears there's a separate block available in ARM Templates and the API](https://github.com/Azure/azure-quickstart-templates/blob/master/201-vmss-windows-app-gateway/azuredeploy.json#L257) which is required to connect an Application Gateway attached to the VM Scale Sets. I've verified that support for configuring the Application Gateway backend exists in the Azure SDK - as such we should be able to implement this in the near future.

Thanks!

**Comment by bob2build** [comment]
+1 for this feature

**Comment by wtfiwtz** [comment]
Hi @bob2build you could manually build this Pull Request (https://github.com/terraform-providers/terraform-provider-azurerm/pull/884) or alternatively use this CLI / Powershell code (https://github.com/terraform-providers/terraform-provider-azurerm/issues/619#issuecomment-372093765) to manually attach the App Gateway to the VMSS after it is built

Just remember to "upgrade" your VMSS instances afterwards for them to be attached to the App Gateway.

**Comment by bob2build** [comment]
Thanks @wtfiwtz You are a life saver.
