### ISSUE TITLE
creation of multiple azurerm_api_management_subscription resources fails, works if a single one is created

### ISSUE THREAD

**Issue by fedragon** [terraform-providers/terraform-provider-azurerm#8571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.26
+ provider.azurerm v2.28.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_api_management_subscription`

### Terraform Configuration Files

```
terraform {
  required_version = "= 0.12.26"

  required_providers {
    azurerm = "= 2.28.0"
    random  = "= 2.2.1"
  }
}

provider "azurerm" {
  features {}
}

# variables
variable "resource_name" {
  type        = string
}

variable "resource_group_name" {
  type        = string
}

variable "location" {
  type        = string
}

variable "sku_name" {
  type        = string
}

variable "virtual_network_name" {
  type        = string
}

variable "backend_service_url" {
  type        = string
}

variable "address_prefix" {
  type        = string
}

# data and locals
data "azurerm_client_config" "current" {}

data "azurerm_subscription" "current" {}

locals {
  resource_name = "my-api"

  apis = {
    a = {
      display_name     = "API a"
      path             = "a"
      backend_url      = "${var.backend_service_url}/a"
    }

    b = {
      display_name     = "API b"
      path             = "b"
      backend_url      = "${var.backend_service_url}/b"
    }

    c = {
      display_name     = "API c"
      path             = "c"
      backend_url      = "${var.backend_service_url}/c"
    }
  }
}

# resources
resource "azurerm_subnet" "this" {
  name                 = "my-subnet"
  resource_group_name  = var.resource_group_name
  virtual_network_name = var.virtual_network_name
  address_prefixes     = [var.address_prefix]
}

resource "azurerm_api_management" "this" {
  name                = var.resource_name
  location            = var.location
  resource_group_name = var.resource_group_name
  sku_name            = var.sku_name
  publisher_name      = "Demo"
  publisher_email     = "demo@example.com"

  virtual_network_type = "External"
  virtual_network_configuration {
    subnet_id = azurerm_subnet.this.id
  }
}

resource "azurerm_api_management_api" "apis" {
  for_each = local.apis

  name                = each.key
  resource_group_name = azurerm_api_management.this.resource_group_name
  api_management_name = azurerm_api_management.this.name
  revision            = "1"
  display_name        = each.value.display_name
  path                = each.value.path
  protocols           = ["https"]
  service_url         = each.value.backend_url

  subscription_required = true
  subscription_key_parameter_names {
    header = "Ocp-Apim-Subscription-Key"
    query  = "subscription-key"
  }
}

resource "azurerm_api_management_product" "a" {
  product_id            = "a"
  api_management_name   = azurerm_api_management.this.name
  resource_group_name   = azurerm_api_management.this.resource_group_name
  display_name          = "Product A"
  subscription_required = true
  published             = true
  approval_required     = false
}

resource "azurerm_api_management_product_api" "a" {
  api_name            = azurerm_api_management_api.apis["a"].name
  product_id          = azurerm_api_management_product.a.product_id
  api_management_name = azurerm_api_management.this.name
  resource_group_name = azurerm_api_management.this.resource_group_name
}

resource "azurerm_api_management_product" "b" {
  product_id            = "b"
  api_management_name   = azurerm_api_management.this.name
  resource_group_name   = azurerm_api_management.this.resource_group_name
  display_name          = "Product B"
  subscription_required = true
  published             = true
  approval_required     = false
}

resource "azurerm_api_management_product_api" "b" {
  api_name            = azurerm_api_management_api.apis["b"].name
  product_id          = azurerm_api_management_product.b.product_id
  api_management_name = azurerm_api_management.this.name
  resource_group_name = azurerm_api_management.this.resource_group_name
}

resource "random_string" "user_id" {
  length  = 16
  number  = true
  special = false
}

resource "azurerm_api_management_user" "demo" {
  user_id             = random_string.user_id.result
  api_management_name = azurerm_api_management.this.name
  resource_group_name = azurerm_api_management.this.resource_group_name
  first_name          = "De"
  last_name           = "Mo"
  email               = "user@example.com"
  state               = "active"
}

resource "azurerm_api_management_subscription" "a" {
  api_management_name = azurerm_api_management.this.name
  resource_group_name = azurerm_api_management.this.resource_group_name
  user_id             = azurerm_api_management_user.demo.id
  product_id          = azurerm_api_management_product.a.id
  display_name        = "Subscription A"
}

resource "azurerm_api_management_subscription" "b" {
  api_management_name = azurerm_api_management.this.name
  resource_group_name = azurerm_api_management.this.resource_group_name
  user_id             = azurerm_api_management_user.demo.id
  product_id          = azurerm_api_management_product.b.id
  display_name        = "Subscription B"
}
```

### Expected Behavior

`Subscription B` should have been created along with the other resources.

### Actual Behavior

The first time I ran `terraform apply` all resources were created except for `Subscription B`, whose creation failed with the following error:

```
apimanagement.SubscriptionClient#CreateOrUpdate: Failure responding to request: StatusCode=412 -- Original Error: autorest/azure: Service returned an error. Status=412 Code="PreconditionFailed" Message="Exception of type 'Microsoft.WindowsAzure.ApiManagement.Management.Core.Exceptions.PreconditionFailedException' was thrown."
```

I have then run `terraform apply` a second time and the creation of `Subscription B` succeeded.

#### Important

After further investigation, I have observed the very same behaviour even when the other resources (API Management, APIs, Products) already exist: applying a configuration that 2+ subscriptions (and only those) fails with an error; the very same configuration works if only 1 subscription is left though.

### Steps to Reproduce

1. `terraform apply`
2. some resources created, then error is raised
3. `terraform apply`
4. all resources created

### Important Factoids

Azure Cloud, Western Europe

### References

My issue _might_ be related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/6648 which was closed due to lack of input from the reporter (the symptoms are the same although it's hard to say because there is no TF configuration in the issue)

**Comment by yupwei68** [comment]
Hi @fedragon , thanks for opening this issue. I could reproduce this problem. I have opened an ICM ticket for service team.

**Comment by fedragon** [comment]
@yupwei68 awesome, thank you!

**Comment by yupwei68** [comment]
Hi @fedragon , according to the service team, we may suggest that you add a dependency on one of these two subscriptions to be created: 

> A 412 (Pre-condition failed) generally indicates that you're trying to perform two concurrent operations on the same entity (for example a User, Product, API etc.). We lock entities during update operations to maintain data integrity and this failure is expected when concurrent operations are performed on the same entity. The recommendation would be to add appropriate dependencies to your ARM template such that two operations on the same entity are not being performed in parallel. In this example, the common entity between the two operations is the user for which the subscriptions are being created. 
> 
> Microsoft.WindowsAzure.ApiManagement.Management.Core.Exceptions.PreconditionFailedException: Exception of type 'Microsoft.WindowsAzure.ApiManagement.Management.Core.Exceptions.PreconditionFailedException' was thrown. ---> System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified

**Comment by yupwei68** [comment]
An example would be:

```
resource "azurerm_api_management_subscription" "a" {
  api_management_name = azurerm_api_management.this.name
  resource_group_name = azurerm_api_management.this.resource_group_name
  user_id             = azurerm_api_management_user.demo.id
  product_id          = azurerm_api_management_product.a.id
  display_name        = "Subscription A"
}

resource "azurerm_api_management_subscription" "b" {
  api_management_name = azurerm_api_management.this.name
  resource_group_name = azurerm_api_management.this.resource_group_name
  user_id             = azurerm_api_management_user.demo.id
  product_id          = azurerm_api_management_product.b.id
  display_name        = "Subscription B"
  
  depends_on = [azurerm_api_management_subscription.a]
}
```

**Comment by fedragon** [comment]
Thank you @yupwei68, I'll test your example tomorrow!

**Comment by fedragon** [comment]
@yupwei68 I can confirm that in this way I can create all resources without getting any errors, so in a way it's solved, thanks! 
The only side effect is that this creates a chain of dependencies between resources that have potentially nothing in common (in my use case, they refer to different products) so the resulting configuration can create a bit of confusion, unless clarified in comments.
