### ISSUE TITLE
azurerm_lighthouse_assignment fails on resource group scope

### ISSUE THREAD

**Issue by jdaminato** [terraform-providers/terraform-provider-azurerm#8573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0

### Affected Resource(s)

* azurerm_lighthouse_assignment

### Terraform Configuration Files

```hcl
locals {
  abc_tenant = "xx-xx-xx-xx-xx"
  abc_support = "xx-xx-xx-xx-xx"
  roles = ["Contributor", "Reader", "Managed Services Registration assignment Delete Role"]
}

data "azurerm_subscription" "main" {}

data "azurerm_role_definition" "roles" {
  for_each = toset(local.roles)
  name = each.value
}

resource "azurerm_lighthouse_assignment" "abc" {
  scope = data.azurerm_subscription.main.id
  lighthouse_definition_id = azurerm_lighthouse_definition.reader.id
}

resource "azurerm_lighthouse_assignment" "abc-rg" {
  # scope - (Required) The scope at which the Lighthouse Assignment applies too, such as /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333 or /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup. Changing this forces a new resource to be created.
  # This part fails
  scope = module.setup.resource_group.id
  lighthouse_definition_id = azurerm_lighthouse_definition.reader.id
}

resource "azurerm_lighthouse_definition" "reader" {
  name = "ABC Platform support services"
  description = "Support of your ABC platform environment."
  managing_tenant_id = local.abc_tenant
  scope = data.azurerm_subscription.main.id

  authorization {
    principal_id = local.abc_support
    role_definition_id = split("/", data.azurerm_role_definition.roles["Managed Services Registration assignment Delete Role"].id)[4]
  }
}
```

### Debug Output

NA

### Panic Output

NA

### Expected Behavior

Should run without error - i.e. a resource group should be enrolled on Lighthouse.

### Actual Behavior

Error: "scope" expected to be valid subscription ID, got other ID type "/subscriptions/xxx-xx-xx-xx-xx/resourceGroups/rg-abc-test-az-2"

  on arm.tf line 22, in resource "azurerm_lighthouse_assignment" "abc-rg":
  22: resource "azurerm_lighthouse_assignment" "abc-rg" {

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Documented as should work: https://www.terraform.io/docs/providers/azurerm/r/lighthouse_assignment.html
scope - (Required) The scope at which the Lighthouse Assignment applies too, such as /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333 or /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup. Changing this forces a new resource to be created.
(nb docs typo in above - too vs to)

### References

https://www.terraform.io/docs/providers/azurerm/r/lighthouse_assignment.html

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems currently scope validation only support subs id. So I made a [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8601) to resolve this issue.
