### ISSUE TITLE
azurerm_kubernetes_cluster - unable to increase min_node value when auto scale is enabled

### ISSUE THREAD

**Issue by leesutcliffe** [terraform-providers/terraform-provider-azurerm#8576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                            = "example-aks"
  location                        = azurerm_resource_group.example.location
  resource_group_name             = azurerm_resource_group.example.name
  kubernetes_version              = "1.16.13"
  node_resource_group             = "example-rg"
  dns_prefix                      = "aks-example"
  enable_pod_security_policy      = false
  private_cluster_enabled         = false
  api_server_authorized_ip_ranges = null
 
  default_node_pool {
    name                = "default"
    enable_auto_scaling = true
    min_count           = 3
    max_count           = 8
    vm_size             = "Standard_D2_v2"
    os_disk_size_gb     = 30
    vnet_subnet_id      = "/subscriptions/*/resourceGroups/example-rg/providers/Microsoft.Network/virtualNetworks/example-vnet/subnets/example-snet-k8s"
    max_pods            = 60
    type                = "VirtualMachineScaleSets"
    availability_zones  = ["1", "2", "3"]
    orchestrator_version = "1.16.13"
  }
```

### Expected Behavior

At the time of testing AKS had 2 nodes in the default node pool, intention was to increase the minimum node_count to 3

After changing the value for ```min_nodes``` from 2 to 3, the expected result would be for a Terraform plan to be applied successfully. 
AKS would auto-scale from a minimum of 2 nodes, to 3. 
It is noted that node_count is optional when ```enable_auto_scaling``` is set to true

### Actual Behavior

Terraform apply step fails with the following output

```
Error: expanding `default_node_pool`: `node_count`(2) must be equal to or greater than `min_count`(3) when `enable_auto_scaling` is set to `true`
```

```node_count``` is not set in the Terraform configuration but is present in the state file. 
Removing ```node_count``` from the state file yields the same result, moreover, ```"node_count": 2,``` is returned to the state file after a ```terraform apply```

### Steps to Reproduce

1. AKS Cluster running with two nodes with auto scale configured
1. Change ```min_nodes = 2``` to ```min_nodes = 3```
1. `terraform plan`
2. `terraform apply`

### References

https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Per the [document](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#node_count), node_count would be set with min_count when node_count isn't set and enable_auto_scaling is true. So I assume it's expect behavior. I assume you have to explicitly set node_count when min_count is updated.

**Comment by leesutcliffe** [comment]
Thanks for the reply @neil-yechenwei 
I cannot see anywhere in the page you reference where it states _"node_count would be set with min_count when node_count isn't set and enable_auto_scaling is true"_

That said I have attempted to explicitly set node_count to be equal or greater than min_count yes the error still remains

The following error is from a cluster that currently has 3 nodes and attempting to ```set min_count = 4``` and node_count is not set
```
Error: expanding `default_node_pool`: `node_count`(3) must be equal to or greater than `min_count`(4) when `enable_auto_scaling` is set to `true`
```

The following error is from another attempt to set ```min_count = 4```, this time explicitly setting ```node_count = 4```
```
Error: expanding `default_node_pool`: cannot change `node_count` when `enable_auto_scaling` is set to `true`
```

**Comment by neil-yechenwei** [comment]
I assume the words "node_count - (Optional) The initial number of nodes which should exist in this Node Pool. If specified this must be between 1 and 100 and between min_count and max_count." in document already indicates node_count would be initialized.

I think the error "Error: expanding `default_node_pool`: cannot change `node_count` when `enable_auto_scaling` is set to `true`" is expected error, which means you cannot update `node_count` when `enable_auto_scaling` is set to `true`. 

For more usage problem, please raised question on [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers). Thanks.

**Comment by leesutcliffe** [comment]
I am aware of the expected error: "Error: expanding default_node_pool: cannot change node_count when enable_auto_scaling is set to true" - this was just for demonstration purposes, given your comment previous comment. 

But the original issue still stands - being unable to increase min_count, even when node_count is not set (although it does appear in the state file)

**Comment by neil-yechenwei** [comment]
Yes. I assume you're right. I assume there is no need to compare min_count with node_count when enable_auto_scaling is true because node_count at this time is useless while updating. So I submit a PR to fix it. Thanks.
