### ISSUE TITLE
azurerm_role_assignment failed with RoleAssignmentNotFound

### ISSUE THREAD

**Issue by fraenkel** [terraform-providers/terraform-provider-azurerm#8584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.27.0

### Affected Resource(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_user_assigned_identity" "identity" {
  name                = "myname"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  tags                = local.default_tags
}

resource "azurerm_role_assignment" "myacr" {
  scope                            = data.azurerm_resources.acr.resources[0].id
  role_definition_name             = "AcrPull"
  principal_id                     = azurerm_user_assigned_identity.identity.principal_id
  skip_service_principal_aad_check = true
}

```

### Actual Behavior

```
Error: authorization.RoleAssignmentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\\\"RoleAssignmentNotFound\\\" Message=\\\"The role assignment '571b2c47-4ad9-fc2d-59fc-915c14b5bcf9' is not found.
``
### Steps to Reproduce
This happens infrequently but does happen.
1. `terraform apply`

### Important Factoids


* #0000

**Comment by chrizkim** [comment]
@fraenkel Upgrading to v2.29.0 seems to have fixed this for me

**Comment by fraenkel** [comment]
Will give it a go... its random when it happens.

**Comment by magodo** [comment]
@fraenkel I can't reproduce this in my local. Can you please confim the issue still exists in v2.29.0? If so, please kindly provide the debug log to help us further investigate.

**Comment by fraenkel** [comment]
I haven't seen it since the upgrade. Will reopen if it happens again.
