### ISSUE TITLE
Support for autoscaling in azurerm_servicebus_namespace resource

### ISSUE THREAD

**Issue by chriss745** [terraform-providers/terraform-provider-azurerm#8591]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On the Azure portal for Service Bus Namespace we can choose between two type of scaling, manual scale or custom autoscale. Currently with Terraform we can set manual scale with capacity 1,2,4,8. Based on the actual Terraform documentation autoscale is not supported at the moment.

This is a very useful and widely used feature, it would be great to have it in Terraform.

Thank you!

### New or Affected Resource(s)

* azurerm_servicebus_namespace

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume this feature has been implemented. You have to use "azurerm_monitor_autoscale_setting" to implement it.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-sb-test01"
  location = "eastus2"
}

resource "azurerm_servicebus_namespace" "test" {
  name                = "acctestservicebusnamespace-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Premium"
  capacity            = 2
}

resource "azurerm_monitor_autoscale_setting" "test" {
  name                = "acctestautoscale-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  target_resource_id  = azurerm_servicebus_namespace.test.id

  profile {
    name = "primary"

    capacity {
      default = 1
      minimum = 1
      maximum = 1
    }
  }
}
```

**Comment by chriss745** [comment]
Thank you, I tried and it is working. Please update the documentation with a reference to this azurerm_monitor_autoscale_setting resource.
