### ISSUE TITLE
Resource with IDFormatter used for setting ID should also be used all over the place

### ISSUE THREAD

**Issue by magodo** [terraform-providers/terraform-provider-azurerm#8593]
For resources whose ID type implemeted the `resourceid.Formatter` interface, the ID should be used at least following places:

- when setting the resource id in create callback
- when formating the import error message
- other places

Addtionally, we need to ensure the ID Parser conforms to the ID Formatter, in turns of casing.

## Affected Types

- azurerm/internal/services/cdn/parse/cdn_endpoint.go:48:1: CdnEndpointId
- azurerm/internal/services/cdn/parse/cdn_profile.go:42:1: CdnProfileId
- azurerm/internal/services/compute/parse/availability_set.go:21:1: AvailabilitySetId
- azurerm/internal/services/compute/parse/dedicated_host.go:23:1: DedicatedHostId
- azurerm/internal/services/compute/parse/dedicated_host_group.go:21:1: DedicatedHostGroupId
- azurerm/internal/services/compute/parse/disk_encryption_set.go:21:1: DiskEncryptionSetId
- azurerm/internal/services/compute/parse/image.go:21:1: ImageId
- azurerm/internal/services/compute/parse/managed_disk.go:21:1: ManagedDiskId
- azurerm/internal/services/compute/parse/proximity_placement_group.go:21:1: ProximityPlacementGroupId
- azurerm/internal/services/compute/parse/shared_image.go:23:1: SharedImageId
- azurerm/internal/services/compute/parse/shared_image_gallery.go:21:1: SharedImageGalleryId
- azurerm/internal/services/compute/parse/shared_image_version.go:25:1: SharedImageVersionId
- azurerm/internal/services/compute/parse/virtual_machine.go:21:1: VirtualMachineId
- azurerm/internal/services/compute/parse/virtual_machine_extension.go:23:1: VirtualMachineExtensionId
- azurerm/internal/services/compute/parse/virtual_machine_scale_set.go:21:1: VirtualMachineScaleSetId
- azurerm/internal/services/compute/parse/virtual_machine_scale_set_extension.go:23:1: VirtualMachineScaleSetExtensionId
- azurerm/internal/services/frontdoor/parse/backend_pool.go:19:1: BackendPoolId
- azurerm/internal/services/frontdoor/parse/frontdoor.go:56:1: FrontDoorId
- azurerm/internal/services/frontdoor/parse/frontend_endpoint.go:19:1: FrontendEndpointId
- azurerm/internal/services/frontdoor/parse/health_probe.go:19:1: HealthProbeId
- azurerm/internal/services/frontdoor/parse/load_balancing.go:19:1: LoadBalancingId
- azurerm/internal/services/frontdoor/parse/routing_rule.go:19:1: RoutingRuleId
- azurerm/internal/services/frontdoor/parse/web_application_firewall_policy.go:21:1: WebApplicationFirewallPolicyId
- azurerm/internal/services/loganalytics/parse/log_analytics_workspace.go:21:1: LogAnalyticsWorkspaceId
- ~azurerm/internal/services/logic/parse/logic_app_workflow.go:21:1: LogicAppWorkflowId~
- azurerm/internal/services/network/parse/load_balancer.go:21:1: LoadBalancerId
- azurerm/internal/services/network/parse/load_balancer_backend_address_pool.go:15:1: LoadBalancerBackendAddressPoolId
- azurerm/internal/services/network/parse/load_balancer_frontend_ip_configuration.go:23:1: LoadBalancerFrontendIPConfigurationId
- ~azurerm/internal/services/sentinel/parse/sentinel_alert_rules.go:23:1: SentinelAlertRuleId~
- ~azurerm/internal/services/sentinel/parse/sentinel_alert_rules.go:65:1: SentinelAlertRuleActionId~

**Comment by tombuildsstuff** [comment]
👋 

Unfortunately this is something we need to do a little more gradually across all resources, including state migrations and patching ID's in the response where necessary; as such whilst we could leave this open tracking these select packages, ultimately this is going to become a longer-term task to ensure these are updated, and at the same time we'll also add Validation to fields where these fields are referenced too.

Since this is a larger task than the packages mentioned above, requiring changes across the codebase - I'm going to close this issue for the moment - but this is something we'll be working through over the coming months.

Thanks!
