### ISSUE TITLE
Kubernetes: Network Security Group is not properly associated for Azure CNI 

### ISSUE THREAD

**Issue by feend78** [terraform-providers/terraform-provider-azurerm#8600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0
```
### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "current" {
  name     = "testcase-rg"
  location = "eastus2"
}

resource "azurerm_virtual_network" "current" {
  name                = "testcase-vnet"
  address_space       = ["10.0.0.0/12"]
  resource_group_name = azurerm_resource_group.current.name
  location            = azurerm_resource_group.current.location
}

resource "azurerm_subnet" "current" {
  name                 = "testcase-subnet"
  address_prefixes     = ["10.0.0.0/16"]
  resource_group_name  = azurerm_resource_group.current.name
  virtual_network_name = azurerm_virtual_network.current.name
}

resource "azurerm_kubernetes_cluster" "current" {
  name                = "testcase-aks"
  location            = azurerm_resource_group.current.location
  resource_group_name = azurerm_resource_group.current.name
  dns_prefix          = "api"

  default_node_pool {
    name            = "default"
    node_count      = 1
    vm_size         = "Standard_B2s"
    vnet_subnet_id  = azurerm_subnet.current.id
  }

  network_profile {
    network_plugin = "azure"
    network_policy = "azure"

    docker_bridge_cidr  = "172.17.0.1/16"
    service_cidr        = "10.1.0.0/16"
    dns_service_ip      = "10.1.0.10"
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output

https://gist.github.com/feend78/f97a1e8c75d339f1308d1efae904c5fe

### Panic Output

No error thrown; terraform apply indicates successful completion.

### Expected Behavior

After creation, the `node_resource_group` contains a network security group that contains rules meant for the cluster's subnet. This NSG is updated by AKS when new services of type LoadBalancer are configured within the cluster. 

After creation, the generated NSG should be associated with the subnet whose ID is passed in the `default_node_pool.vnet_subnet_id` key.

### Actual Behavior

After creation, the vnet, subnet, and NSG in are successfully created, but no subnet-NSG association is created.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Azure public cloud - US East 2 region

### References

N/A

**Comment by njuCZ** [comment]
@feend78 I am sorry that I am not so familiar with kubernetes RP, May I ask why the generated NSG should be associated with the subnet ID, is there any doc about this? I have tried creating a kubernetes cluster in the portal, there is no subnet-NSG association created either

**Comment by feend78** [comment]
In answer to your first question, the NSG contains rules that govern traffic entering and exiting a subnet. Unless associated with a subnet, the NSG's rules are not active. I have struggled to find documentation of this, but when creating a cluster via the portal (or Terraform) that uses Basic/kubenet networking, the provisioning service creates both the vnet/subnet and NSG, and after creation, the NSG is properly associated with the subnet. 

Without the NSG association, it does appear that traffic flows into the cluster, but without restriction. The NSG has default "Deny all" rules along with narrow "Allow" rules that should limit traffic to the configured ingress addresses. Having the cluster's subnet open to any incoming traffic seems dangerous.

That said, I am seeing the same behavior you are when creating a cluster with CNI/advanced networking through the portal, so perhaps this is a question for Microsoft Azure support, rather than an issue with the azurerm provider for Terraform.

**Comment by tombuildsstuff** [comment]
hey @feend78 

Apologies for the delayed reply here.

Taking a look through this appears to be a question for the AKS Team, rather than something specific to Terraform - as such I'm going to redirect you to their repo: https://github.com/Azure/AKS where they should be able to confirm the expected behaviour here.

Thanks!
