### ISSUE TITLE
managed_application only supports string as parameters

### ISSUE THREAD

**Issue by Dilergore** [terraform-providers/terraform-provider-azurerm#8608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
* `azurerm_managed_application`

### Terraform Configuration Files
```hcl
resource "azurerm_managed_application" "CBS" {
  name                        = "CBD"
  location                    = azurerm_resource_group.example.location
  resource_group_name         = azurerm_resource_group.example.name
  kind                        = "MarketPlace"
  managed_resource_group_name = "managed-rg-name"

  parameters = {
    location                  = "eastus"
    zone                      = 1
    arrayName                 = "purearrayname"
    orgDomain                 = "domain.com"
    licenseKey                = "XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX"
    vnetName                  = "vnetname"
    vnetResourceGroupName     = "vnetrgname"
    systemInterfaceSubnetName = "CBS_system"
    subnetName                = "CBS_management"
    #additionalTags           = ""
    alertRecipients           = "mail@domain.com"
    #pureuserPublicKey        = ""
    setupHA                   = false
    setupInitiator            = false
    sku                       = "small"
    useProximityGroup         = false
  }

  plan  {
    name        = "6_0_0_beta4-0f043f4"
    product     = "cloud_block_store_beta-preview"
    publisher   = "purestorageinc1578960262525"
    version     = "1.0.0"
  }
}
```

### Error message
Error: failed to wait for creation of Managed Application "CBD" (Resource Group "CBS-Resourcegroup"): Code="ApplianceProvisioningFailed" Message="Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Boolean'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'." AdditionalInfo=[{"info":{"lineNumber":48,"linePosition":20,"path":"parameters.setupHA"},"type":"TemplateViolation"}]

### Expected Behavior
Be able to specify parameters properly with type. Today all the params are getting converted to a string. While it works for what we have in the documented examples, there are managed applications waiting for non-string vals. 

### Actual Behavior
All the values are getting converted to a string causing deployment issues for apps waiting for other kind of parameter types.

### Steps to Reproduce
We tried to deploy Pure CBS closed beta as a Managed App. I strongly believe there can be other managed apps waiting for non-string parameters.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Hopes the [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8632) would be helpful.

**Comment by Dilergore** [comment]
> Thanks for opening this issue. Hopes the [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8632) would be helpful.

TYVM, hope it will be part of the next release.
