### ISSUE TITLE
Support for Security Center export to Log Analytics Workspace

### ISSUE THREAD

**Issue by sebastus** [terraform-providers/terraform-provider-azurerm#8611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Export Security Center events to Log Analytics workspace.

### New or Affected Resource(s)

* azurerm_security_center_export (new)

### References

* https://docs.microsoft.com/en-us/rest/api/securitycenter/automations
* #6066

**Comment by benc-uk** [comment]
Shall we call the new resource `azurerm_security_center_automation` as at the Azure API level that what it is referred to?
The portal and docs call the features of this API two different things, but there is a single API
https://aka.ms/ASCWorkflowAutomationLearnMore
This is a question of having Terraform match what users will see in the portal or the docs, or align to the underlying Azure APIs
