### ISSUE TITLE
azurerm_cognitive_account- SKU-S-MISSING in Terraform

### ISSUE THREAD

**Issue by akhildevops24** [terraform-providers/terraform-provider-azurerm#8613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
0.13 > 0.13.3

### Affected Resource(s)

* `azurerm_cognitive_account`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
name = "rg-np-cognitive-services"
location = "eastus2"
}

resource "azurerm_cognitive_account" "cs-np-text-analytics" {
name = "cs-np-text-analytics"
resource_group_name = azurerm_resource_group.rg.name
location = azurerm_resource_group.rg.location
kind = "TextAnalytics"
sku_name = "S"
}
```

### Debug Output
```
Terraform v0.13.3
Configuring remote state backend...
Initializing Terraform configuration...

Error: expected sku_name to be one of [F0 F1 S0 S1 S2 S3 S4 S5 S6 P0 P1 P2], got S

  on cr-np-appconfiguration.tf line 6, in resource "azurerm_cognitive_account" "cs-np-text-analytics":
   6: resource "azurerm_cognitive_account" "cs-np-text-analytics" {

```

### Expected Behavior

For the above-mentioned config file, it should deploy Azure Cognitive account (Text Analytics) with  Standard 'S' SKU.

### Actual Behavior

Error: expected sku_name to be one of [F0 F1 S0 S1 S2 S3 S4 S5 S6 P0 P1 P2], got S. `SKU S` is missing in the Terraform. 

### Steps to Reproduce

1. `terraform apply`

### References
![Azure_Cognitive_Servoces_PT](https://user-images.githubusercontent.com/46358147/94157423-3a2b2900-fe4f-11ea-852b-f7626858eb8e.jpeg)

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume you're right. Hopes the [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8639)would be helpful.
