### ISSUE TITLE
Support for large partition key in cosmosdb

### ISSUE THREAD

**Issue by kishore25kumar** [terraform-providers/terraform-provider-azurerm#8653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
CosmosDB supports large partition keys upto 2 KB. [This link](https://docs.microsoft.com/en-us/azure/cosmos-db/large-partition-keys?tabs=dotnetv3) talks in detail about large partition keys. While creating the cosmos db resource similar option as UI should be supported.

### New or Affected Resource(s)

* CosmosDB

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://docs.microsoft.com/en-us/azure/cosmos-db/large-partition-keys?tabs=dotnetv3

* #0000

**Comment by yupwei68** [comment]
Hi @kishore25kumar , thanks for opening this issue. According to your provided document, I think the large partition key has been supported in `azurerm_cosmosdb_sql_container`, because our api version is higher than `2017-05-03`. 
Please refer to our resource [doc](https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_sql_container.html#partition_key_path)

> partition_key_path - (Optional) Define a partition key. Changing this forces a new resource to be created.
