### ISSUE TITLE
Support for PostgreSQL Flexible Server

### ISSUE THREAD

**Issue by dhirschfeld** [terraform-providers/terraform-provider-azurerm#8654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft have just released a new type of PostgreSQL deployment called *Flexible Server*
* https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/overview

### New or Affected Resource(s)

I *assume* it would be a deployment option on [`azurerm_postgresql_server`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_server)

### References

* https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest#az_postgres_flexible_server_create

**Comment by dhirschfeld** [comment]
Somewhat related to #5040?

**Comment by tamland** [comment]
> Somewhat related to #5040?

No? Unlike Citus, Flexible Server _does_ have API support.

**Comment by evertonmc** [comment]
> I _assume_ it would be a deployment option on [`azurerm_postgresql_server`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_server)
I don't think so. The API is pretty different.

**Comment by jcorioland** [comment]
Has anybody started to work on this item? cc @tombuildsstuff

**Comment by fuesec** [comment]
would love to see this

**Comment by fra-ga** [comment]
Until this is implemented, maybe this will help others. I got it up and running with local exec. Here some code to get you started.
It creates the minimum database in westeurope and adds firewall rules for a web app created in another part of the code. 
The commands are documented [here](https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest). Adjust to your needs.
```
resource "null_resource" "database" {
  triggers = {
    RESOURCE_GROUP_NAME = azurerm_resource_group.rg.name
    DATABASE_NAME       = local.database_name
    ADMIN_PASSWORD      = random_password.rnd_database_secret.result
    ADMIN_USER          = local.database_user
    SKU_NAME            = "Standard_B1ms"
    TIER                = "Burstable"
  }
  provisioner "local-exec" {
    when    = create
    command = "az postgres flexible-server create --storage-size 32 --public-access none --sku-name ${self.triggers.SKU_NAME} --tier ${self.triggers.TIER} --version 12 --name ${self.triggers.DATABASE_NAME} --admin-password ${self.triggers.ADMIN_PASSWORD} --admin-user ${self.triggers.ADMIN_USER} --location westeurope --resource-group ${self.triggers.RESOURCE_GROUP_NAME}"
  }
  provisioner "local-exec" {
    when    = destroy
    command = "az postgres flexible-server delete --resource-group ${self.triggers.RESOURCE_GROUP_NAME} --name ${self.triggers.DATABASE_NAME} --yes"
  }
}

resource "null_resource" "database_firewall" {
  count = 10
  triggers = {
    RESOURCE_GROUP_NAME = azurerm_resource_group.rg.name
    DATABASE_NAME       = local.database_name
    APP_ACCESS_NAME     = local.webapp_name_backend
    IP                  = (split(",", azurerm_app_service.as_webapp_backend.possible_outbound_ip_addresses))[count.index]
  }
  provisioner "local-exec" {
    when    = create
    command = "az postgres flexible-server firewall-rule create --resource-group ${self.triggers.RESOURCE_GROUP_NAME} --name ${self.triggers.DATABASE_NAME} --rule-name ${self.triggers.APP_ACCESS_NAME}-${count.index} --start-ip-address ${self.triggers.IP} --end-ip-address ${self.triggers.IP}"
  }
  depends_on = [null_resource.database, ]
}
```

**Comment by nigel-decosta-rft** [comment]
Is there any update yet on when Postres Flexible Server will be supported? I can use the null_resource approach above but it is less than ideal.

Thanks

**Comment by LukaszSzalek-Tomtom** [comment]
hi
I would like to use azurerm_postgresql_database to create db on azurerm_postgresql_flexible_server.
but is seems that the call goes to Server instead of FlexibleServer.
Error:
Error: postgresql.DatabasesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.DBForPostgreSQL/servers/fakeDB' under resource group 'myRG' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

Code
resource "azurerm_postgresql_database" "coresup_cpp" {
  depends_on = [azurerm_postgresql_flexible_server.fakeDB]
  name                = "cpp"
  resource_group_name = var.RESOURCE_GROUP_NAME
  server_name         = data.azurerm_postgresql_flexible_server.fakeDB.name
  charset             = "UTF8"
  collation           = "English_United States.1252"
}

provider 2.57
TF v0.15.1

Thanks

Lukasz

**Comment by BenWyattMilliman** [comment]
Flexible Server is actually a separate resource type, `azurerm_postgresql_flexible_server`. You can view the documentation here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server

**Comment by marcoboffi** [comment]
So will a new resource be add in a near future to create db on _azurerm_postgresql_flexible_server_ ?
