### ISSUE TITLE
aks: support for ephemeral disks on default & custom node pools

### ISSUE THREAD

**Issue by 4c74356b41** [terraform-providers/terraform-provider-azurerm#8657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add an ability to create node pools with ephemeral disks

### New or Affected Resource(s)

* azurerm_kubernetes_cluster
* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration
```hcl
    default_node_pool {
        xxx
        os_disk_type = "Ephemeral" # or "Managed"
        xxx
    }
```

### References
https://github.com/Azure/AKS/issues/1370
https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerservice/mgmt/2020-09-01/containerservice/models.go#L1379
https://docs.microsoft.com/en-us/rest/api/aks/agentpools/createorupdate#osdisktype

**Comment by davidack** [comment]
A big thumbs-up on this one, but please add `kubernetes_cluster_node_pool` to the affected resources.

For anyone not already aware, this problem can be worked around by creating a node pool with `az aks nodepool add EnableEphemeralOSDisk=true` then importing the newly created node pool into the Terraform state, but this is of course non-optimal.

**Comment by 4c74356b41** [comment]
@davidack yeah, sorry, my bad, forgot about it

**Comment by davidack** [comment]
Thanks all for getting this done, you are awesome!

**Comment by blafry** [comment]
As I can see support for `os_disk_type` was added only to `kubernetes_cluster_node_pool` resource. Thanks a lot for that!

But what about `azurerm_kubernetes_cluster` mentioned in first comment? `default_node_pool` should also support `os_disk_type`.

**Comment by mrowken** [comment]
According to [AKS release notes](https://github.com/Azure/AKS/releases/tag/2020-11-16) Ephemeral OS is now GA and used as default.
Current behavior of `azurerm_kubernetes_cluster` makes it impossible to use this feature, because it always sets `default_node_pool->os_disk_type = "Managed"` and doesn't expose parameter to override.

Could you please prioritize this change or is there any particular reason for being missing ?
