### ISSUE TITLE
Terraform wants to update collection index every time

### ISSUE THREAD

**Issue by Edblakejitsuin** [terraform-providers/terraform-provider-azurerm#8660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.16
+ provider.azuread v0.10.0
+ provider.azurerm v2.29.0
+ provider.null v2.1.2
+ provider.random v2.3.0
### Affected Resource(s)

* `azurerm_cosmosdb_mongo_collection`

### Terraform Configuration Files

Example configuration: attempt to set "_id" as index
```hcl

resource "azurerm_cosmosdb_mongo_collection" "example" {
  provider            = azurerm.cosmos
  name                = var.example
  resource_group_name = data.azurerm_cosmosdb_account.example.example
  account_name        = data.azurerm_cosmosdb_account.example.name
  database_name       = var.example


  default_ttl_seconds = "0"
  
  index {
      keys = [
        "_id"
      ]
      unique = true
  }
  
  index {
      keys = [
        "$**"
      ]
  }

  shard_key = var.cosmosdb_shard_key
}
```

### Expected Behavior

terraform should create the "_id" index on first "terraform apply" only

### Actual Behavior

Attempting to set the "_id" index as a regular index (Example configuration) works, but subsequent "terraform apply" commands continue to want to update the resource to include the "_id" index every time:

Terraform will perform the following actions:
```hcl
  # module.example.azurerm_cosmosdb_mongo_collection.example will be updated in-place
  ~ resource "azurerm_cosmosdb_mongo_collection" "example" {
        account_name        = "example"
        database_name       = "example"
        default_ttl_seconds = 0
        id                  = "/subscriptions/c6fb3d89-ebe2-49de-a6e1-7478c8321505/resourceGroups/exampleproviders/Microsoft.DocumentDB/databaseAccounts/example/mongodbDatabases/example/collections/example"
        name                = "example"
        resource_group_name = "example"
        shard_key           = "shardkey"
        system_indexes      = [
            {
                keys   = [
                    "_id",
                ]
                unique = true
            },
        ]
        throughput          = 0

        index {
            keys   = [
                "$**",
            ]
            unique = false
        }
      + index {
          + keys   = [
              + "_id",
            ]
          + unique = true
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Previously we were not setting indexes at all on our Cosmos collections. Moving from AzureRM 1.44 to 2.29 and we are finding that we now have to specify "_id" as in index, or the following error is returned:
Code="BadRequest" Message="Index definition does not contains '_id' index specification.

Was successful in adding it as an "index" but it attempts to update it every "terraform apply".

### References

* #0000

**Comment by drone2of6** [comment]
Terraform v0.13.4

    provider.azuread v1.0.0
    provider.azurerm v2.30.0
    provider.random v2.3.0

I can confirm I'm still getting similar issues with this.
I too encountered an error when creating new collections or simply doing a 'plan' after upgrading and using server version 3.6:
Code="BadRequest" Message="Index definition does not contains '_id' index specification.

This has worked fine previously before starting to use server version 3.6. After upgrading the above error message was seen when adding new collections.

I've now added the following which seems to be 'required' for Terraform not to error:

index {
      keys = [
        "_id"
      ]
      unique = true
  }

It created the collections ok, but on a subsequent plan with no changes made it's trying to add it again:

      + index {
          + keys   = [
              + "_id",
            ]
          + unique = true
        }
    }

Plan: 0 to add, 7 to change, 0 to destroy.

**Comment by boybundit** [comment]
I can confirm this does not happen in v2.28.0

**Comment by ldfloresgon** [comment]
hi guys any news with this issue?, i have the same problem with the last azurerm version 2.37.0.

**Comment by SpaWn2KiLl** [comment]
Still facing this issue on azurerm version 2.40.0. Very annoying because terraform plan is full of these changes.

**Comment by blame19** [comment]
Still facing this issue with 2.42.0.
