### ISSUE TITLE
Terraform provider Azure - how to manage Identity and Access Management (Azure AD)?

### ISSUE THREAD

**Issue by omershliva** [terraform-providers/terraform-provider-azurerm#8675]
Is it possible to manage users and groups using Terraform?

Operations such as MFA, user-types, Authentication methods, Registration, notification, User settings, group settings, and Device settings.

**Comment by tombuildsstuff** [comment]
hi @omershliva 

Support for Azure Active Directory is available in [the Azure Active Directory provider](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs) - please see that providers documentation for more information.

Thanks!
