### ISSUE TITLE
Support for additional dedicated host SKU DSv4-Type1

### ISSUE THREAD

**Issue by briancunningham-ais** [terraform-providers/terraform-provider-azurerm#8681]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The newly introduced azurerm_dedicated_host validates the sku_name property for one of DSv3-Type1, DSv3-Type2, ESv3-Type1 ESv3-Type2, FSv2-Type2 valid values. Microsoft Azure introduced additional SKU DSv4-Type1 for their Dedicated Host offering. Request that validation for azurerm_dedicated_host implementation be changed to allow the additional SKU.

### New or Affected Resource(s)

Affects existing azurerm_dedicated_host resource, sku_name property.

### Potential Terraform Configuration

No changes to existing Terraform configuration. Existing property should support additional valid values.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

Based on the 1.42 delivered feature, tracked in this pull [request](https://github.com/terraform-providers/terraform-provider-azurerm/pull/5513)

* #5513

**Comment by nexxai** [comment]
Submitted PR [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8718)
