### ISSUE TITLE
terraform plan doesnt work for prefix_length other than 28

### ISSUE THREAD

**Issue by swapnild2111** [terraform-providers/terraform-provider-azurerm#8684]
Hello,

I have an Azure IP prefix with `prefix_length = 30`
Then I imported that with `terraform import xxx` and I could see perfect data in tfstate. All good.

After which when I run `terraform plan`, I could see resource will be replaced due to `prefix_length` getting changed from 30 to 28.

Terraform version - 

```bash
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.29.0
```

Terraform config - 

```bash
resource "azurerm_public_ip_prefix" "test-prefix" {
  name                = "test-prefix"
  resource_group_name = "xxx"
  location            = "westeurope"
}
```

Terraform import command -

```bash
terraform import azurerm_public_ip_prefix.test-prefix /subscriptions/x-y-z/resourceGroups/xxx/providers/Microsoft.Network/publicIPPrefixes/test-prefix
```

Terraform state file - 

```bash
{
  "version": 4,
  "terraform_version": "0.13.3",
  "serial": 1,
  "lineage": "4598e109-1138-8ad1-aa83-e26c6f8c114d",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "azurerm_public_ip_prefix",
      "name": "test-prefix",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "/subscriptions/x-y-z/resourceGroups/xxx/providers/Microsoft.Network/publicIPPrefixes/test-prefix",
            "ip_prefix": "xxx/30",
            "location": "westeurope",
            "name": "test-prefix",
            "prefix_length": 30,
            "resource_group_name": "xxx",
            "sku": "Standard",
            "tags": {
              "Self Managed": "Yes"
            },
            "timeouts": {
              "create": null,
              "delete": null,
              "read": null,
              "update": null
            },
            "zones": []
          },
          "private": "xxx"
        }
      ]
    }
  ]
}
```

Terraform plan output - 

```bash
Terraform will perform the following actions:

  # azurerm_public_ip_prefix.test-prefix must be replaced
-/+ resource "azurerm_public_ip_prefix" "test-prefix" {
      ~ id                  = "/subscriptions/x-y-z/resourceGroups/xxx/providers/Microsoft.Network/publicIPPrefixes/test-prefix" -> (known after apply)
      ~ ip_prefix           = "xxx/30" -> (known after apply)
        location            = "westeurope"
        name                = "test-prefix"
      ~ prefix_length       = 30 -> 28 # forces replacement
        resource_group_name = "xxx"
        sku                 = "Standard"
      - tags                = {
          - "Self Managed" = "Yes"
        } -> null
      - zones               = [] -> null

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I tested this with couple of other resource groups and result is same.

Can someone please help?

**Comment by swapnild2111** [comment]
Any help?

**Comment by tombuildsstuff** [comment]
@swapnild2111 you need to set the field `prefix_length` to 31 since you're using a custom value here  - see [the documentation](https://www.terraform.io/docs/providers/azurerm/r/public_ip_prefix.html#prefix_length) for more information

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by swapnild2111** [comment]
Wait, what?

It is issue with the import. How would you know what value to set in case of import??

**Comment by swapnild2111** [comment]
I want to manage existing IP prefix resource with Terraform. Import works fine.

But when I do `terraform-plan` it tries to create new resource because of `prefix_length`. The `prefix_length` is getting set to `28` which is a default value instead of setting it to the value imported. Right?

Or do you still want me to raise it to broader community ?

**Comment by tombuildsstuff** [comment]
@swapnild2111 your not defining this property in the configuration, so the default value for this field (`28`) is being proposed as a replacement value for `30` - so you just need to define this field in the configuration to resolve the diff here :)
