### ISSUE TITLE
azurerm_linux_virtual_machine ignores error codes from cloud init script

### ISSUE THREAD

**Issue by kankomi** [terraform-providers/terraform-provider-azurerm#8695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform 0.13.2
provider.azurerm v2.29.0

### Affected Resource(s)
* `azurerm_linux_virtual_machine `

### Terraform Configuration Files

```hcl
data "template_file" "setup_script" {
  count    = var.agent_count
  template = file("scripts/setup.sh")
  vars = {
    POOL_NAME        = var.pool_name
    AGENT            = "agent-${count.index}"
    ORGANIZATION_URL = var.organization_url
    TOKEN            = var.token
    TERRAFORM_VERSION = var.terraform_version
    VSTS_AGENT_VERSION = var.vsts_agent_version
  }
}

resource "azurerm_linux_virtual_machine" "vmachine" {
  count               = length(module.network.network_interfaces)
  name                = "agent-${count.index}"
  resource_group_name = azurerm_resource_group.deployment-agents.name
  location            = azurerm_resource_group.deployment-agents.location
  size                = "Standard_B1ms"
  admin_username      = "adminuser"

  network_interface_ids = [
    module.network.network_interfaces[count.index].id,
  ]

  admin_ssh_key {
    username   = "adminuser"
    public_key = var.ssh_public_key
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-LTS"
    version   = "latest"
  }

  boot_diagnostics {
    storage_account_uri = azurerm_storage_account.boot.primary_blob_endpoint
  }
  custom_data = base64encode(data.template_file.setup_script.*.rendered[count.index])
}
```

```bash
# scripts/setup.sh
# --- snip ----
apt-get install azure-cli
if [ $? -gt 0 ]; then
  echo "Cannot install azure cli!"
  exit 1
fi

# Test
exit 1
```

### Expected Behavior

I'd expect that if the cloud init script exits with a status code > 0, that the deployment of the resource would fail, which is not the case.

### Actual Behavior

terraform reports the resource was deployed successfully.

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @kankomi 

Thanks for opening this issue.

Taking a look through here this appears to be a usage question around Cloud Init, rather than specific to the Terraform/Azure Provider - and as such I'm going to close this issue for the moment (since we use this forum to track bugs/feature enhancements in the Azure Provider) - however I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
