### ISSUE TITLE
Support for InitContainers on azurerm_container_group

### ISSUE THREAD

**Issue by allantargino** [terraform-providers/terraform-provider-azurerm#8697]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

 Azure Container Instances `2019-12-01` API introduced init containers. We should have a `init_container` property to support this use case.

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

```hcl
resource "azurerm_container_group" "example" {
  name                = "example-aci"

  init_container {
    name   = "init-1"
    image  = "busybox"
  }   

  init_container {
    name   = "init-2"
    image  = "busybox"
  }   

  container {
    name   = "hello-world"
    image  = "microsoft/aci-helloworld:latest"
  }
```

### References

* https://docs.microsoft.com/en-us/azure/container-instances/container-instances-init-container
* https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerinstance/mgmt/2019-12-01/containerinstance/models.go#L841

**Comment by switte-sf** [comment]
Is this a duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/8085 ?

**Comment by allantargino** [comment]
Yes @switte-sf, thanks for raising this. I searched for InitContainer and not Init Containers 😄 
Thanks for you PR too!
