### ISSUE TITLE
azurerm_key_vault - network_acls - ip_rules keeps re-applying

### ISSUE THREAD

**Issue by etaham** [terraform-providers/terraform-provider-azurerm#8701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
"azurerm" (hashicorp/azurerm) 2.29.0...

### Affected Resource(s)

* azurerm_key_vault

### Terraform Configuration Files

```hcl
locals {
  allowed_ip_ranges = [
    "68.65.48.2",
    "68.24.22.2"
  ]
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "this" {
  location = "eastus2"
  name = "test123"
}

resource "azurerm_key_vault" "this" {
  name                        = "tenf38ja32"
  location                    = azurerm_resource_group.this.location
  resource_group_name         = azurerm_resource_group.this.name
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_enabled         = true
  purge_protection_enabled    = true

  sku_name = "standard"

  network_acls {
    bypass         = "AzureServices"
    default_action = "Deny"
    ip_rules       = local.allowed_ip_ranges
  }
}
```

### Expected Behavior

There should be nothing to apply when running the terraform a second time.

### Actual Behavior

The provider attempts to remove and re-add each ip address under `azurerm_key_vault->network_acls->ip_rules`. The API does not allow us to specify IP's as /32 cidrs due to a recent API change by azure. As such, we do not know of a work around.

```
data.azurerm_client_config.current: Refreshing state...
azurerm_resource_group.this: Refreshing state... [id=/subscriptions/6e535158-ab8a-4695-88bc-81c1aa786c70/resourceGroups/test123]
azurerm_key_vault.this: Refreshing state... [id=/subscriptions/6e535158-ab8a-4695-88bc-81c1aa786c70/resourceGroups/test123/providers/Microsoft.KeyVault/vaults/tenf38ja32]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_key_vault.this will be updated in-place
  ~ resource "azurerm_key_vault" "this" {
        access_policy                   = []
        enabled_for_deployment          = false
        enabled_for_disk_encryption     = false
        enabled_for_template_deployment = false
        id                              = "/subscriptions/6e535158-ab8a-4695-88bc-81c1aa786c70/resourceGroups/test123/providers/Microsoft.KeyVault/vaults/tenf38ja32"
        location                        = "eastus2"
        name                            = "tenf38ja32"
        purge_protection_enabled        = false
        resource_group_name             = "test123"
        sku_name                        = "standard"
        soft_delete_enabled             = false
        soft_delete_retention_days      = 0
        tags                            = {}
        tenant_id                       = "282a3295-5c42-4d93-9ec1-6631001cc5f7"
        vault_uri                       = "https://tenf38ja32.vault.azure.net/"

      ~ network_acls {
            bypass                     = "AzureServices"
            default_action             = "Deny"
          ~ ip_rules                   = [
              + "68.24.22.2",
              - "68.24.22.2/32",
              + "68.65.48.2",
              - "68.65.48.2/32",
            ]
            virtual_network_subnet_ids = []
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

### Steps to Reproduce

1. `terraform apply`
1. `terraform apply` a second time.

**Comment by smitp11** [comment]
We are seeing the same behaviour with `azurerm_key_vault`.

```
Terraform v0.12.24
azurerm 2.14.0
```

The terraform code is as follows:
```
variable "ip-rules" {
  description = "Address space"
  type        = list(string)
  default     = ["xx.aa.yyy.zz"]
}
```

After a `terraform apply`, I see this in the portal

`xx.aa.yyy.zz/32`

so the next time I run a `terraform plan` it shows:
```
              + "xx.aa.yyy.zz",
              - "xx.aa.yyy.zz/32",
```

Flip/Flopping back and forth between the two after each `terraform apply`.

**Comment by etaham** [comment]
The docs have been [updated](https://github.com/MicrosoftDocs/azure-docs/commit/54798885ab4835c7309696abbe1e3a9297930941#diff-7fd6f1fa4e4c6a1434e0d9304ba9f8732032e0f8914dfbde0091b31a54e0a7f0) to allow /32 cidrs. This is the recommended work around. Will close once we confirm this addresses the issue.

**Comment by smitp11** [comment]
- Using an IP CIDR with /32 does resolve the issue.
- However shouldn't we be able to use a single IP?
- Using a single IP **is** currently possible in the Storage Account Firewall?
