### ISSUE TITLE
Unable to use Local Values for security rule in azurerm_network_security_group

### ISSUE THREAD

**Issue by hykins1** [terraform-providers/terraform-provider-azurerm#8702]
### Terraform (and AzureRM Provider) Version
Terraform v0.13.2
+ provider.azurerm v2.27.0

### Affected Resource(s)

* azurerm_network_security_group

### Terraform Configuration Files

locals {
    Allow-SMB = {
    name                        = "Allow-SMB"
    priority                    = 2001
    direction                   = "Inbound"
    access                      = "Allow"
    protocol                    = "*"
    source_port_range           = "*"
    destination_port_ranges     = ["139", "445"]
    source_address_prefix       = "10.0.0.0/24"
    destination_address_prefix  = "*"
        }
    
    Allow-Internal-RPC = {
    name                       = "Allow-Internal-RPC"
    priority                   = 2003
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "135"
    source_address_prefix      = "10.0.0.0/8"
    destination_address_prefix = "*"
        }
}

resource "azurerm_network_security_group" "common-services-nsg" {
	name                = "Common-Services-NSG"
	location            = azurerm_resource_group.common.location
	resource_group_name = azurerm_resource_group.common.name
	security_rule = [
    local.Allow-SMB,
    local.Allow-Internal-RPC
  ]
}

### Expected Behavior

Plan: 2 to add, 0 to change, 0 to destroy.

### Actual Behavior
Inappropriate value for attribute "security_rule": element 0: attributes
"description", "destination_address_prefixes",
"destination_application_security_group_ids", "destination_port_range",
"source_address_prefixes", "source_application_security_group_ids", and
"source_port_ranges" are required.

**Now, I added the suggested attributes as shown below (though documentation stated they are optional)** 

description = "allow-smb"
destination_address_prefixes = "*"
destination_application_security_group_ids = "*"
destination_port_range = "*"
source_address_prefixes  = "*"
source_application_security_group_ids = "*"
source_port_ranges = "*"

**And then got new errors below**
Inappropriate value for attribute "security_rule": element 0: attribute
"destination_port_range": string required.

It keeps throwing errors even with string declared values

### What works
When I declared the security rules directly rather than use locals, it works fine. So I need to know if locals aren't allowed for declaring security rules for azurerm_network_security_group

I need to find a way to avoid repeating the same values (security rule) multiple times in the configuration hence the need for local values.

**The below works fine without locals.**

resource "azurerm_network_security_group" "common-services-nsg" {
  name                = "Common-Services-NSG"
  location            = azurerm_resource_group.common.location
  resource_group_name = azurerm_resource_group.common.name
  
security_rule {
    name                        = "Allow-SMB"
    priority                    = 2001
    direction                   = "Inbound"
    access                      = "Allow"
    protocol                    = "*"
    source_port_range           = "*"
    destination_port_ranges     = ["139", "445"]
    source_address_prefix       = "10.0.0.0/24"
    destination_address_prefix  = "*"
    }
    
    security_rule{
    name                       = "Allow-Internal-RPC"
    priority                   = 2003
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "135"
    source_address_prefix      = "10.0.0.0/8"
    destination_address_prefix = "*"
        }
}

### Steps to Reproduce
1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @hykins1 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
