### ISSUE TITLE
azurerm_cosmosdb_account.connection_strings is missing required query parameters for mongodb 3.6

### ISSUE THREAD

**Issue by restfulhead** [terraform-providers/terraform-provider-azurerm#8703]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.29.0
```

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Expected Behavior

Expect `azurerm_cosmosdb_account.db.connection_strings[0]` to match with the primary connection string that you can see in the Azure Portal: `mongodb://**:**@**cosmos.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=***`

### Actual Behavior

Output of `azurerm_cosmosdb_account.db.connection_strings[0]`: `mongodb://**:**@**cosmos.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb`

### Important Factoids

Due to the missing `retrywrites=false` query parameter, Mongo insert operations fail with the following error:
`MongoError: Retryable writes are not supported. Please disable retryable writes by specifying "retrywrites=false" in the connection string or an equivalent driver specific config.`

This means I can't use the output directly. I'm not sure if this is a provider issue or if the Azure API returns the incomplete connection string.

**Comment by katbyte** [comment]
Hey @restfulhead, sorry this is a problem for you.

We just grab those strings from the API response:

```
var connStrings []string
	if connStringResp.ConnectionStrings != nil {
		connStrings = make([]string, len(*connStringResp.ConnectionStrings))
		for i, v := range *connStringResp.ConnectionStrings {
			connStrings[i] = *v.ConnectionString
		}
	}
	d.Set("connection_strings", connStrings)
```

As this is not an issue with the provider i suggest you instead contact microsoft support or open an issue on any number of the azure githubs such as Azure/azure-sdk-for-go.
