### ISSUE TITLE
Incorrect subscription id resollution for terraform apply

### ISSUE THREAD

**Issue by Ramutis** [terraform-providers/terraform-provider-azurerm#8731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.3+ provider registry.terraform.io/hashicorp/azurerm v2.25.0

### Affected Resource(s)

* azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Azure alert rule should be created in multiple subscriptions. All required variables are stored in csv file.
for alert rule creation used resource "azurerm_monitor_scheduled_query_rules_alert"
### Actual Behavior

Terraform plan shows correct subscriptions where rule should be created, after terraform apply get message that alert rule exists and can't be created, but this alert rule exists in different subscription which it's not in scope

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

ome warnings found in debug log:
2020/09/23 01:36:37 [WARN] Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_monitor_scheduled_query_rules_alert.main["2"], but we are tolerating it because it is using the legacy plugin SDK.
The following problems may be the cause of any confusing errors from downstream operations:
- .location: planned value cty.StringVal("westeurope") does not match config value cty.StringVal("West Europe")
- .query_type: planned value cty.StringVal("ResultCount") does not match config value cty.NullVal(cty.String)
2020/09/23 01:36:37 [WARN] Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_monitor_scheduled_query_rules_alert.main["1"], but we are tolerating it because it is using the legacy plugin SDK.
The following problems may be the cause of any confusing errors from downstream operations:
- .query_type: planned value cty.StringVal("ResultCount") does not match config value cty.NullVal(cty.String)
- .location: planned value cty.StringVal("eastus") does not match config value cty.StringVal("East US")

Interesting entry in debug log

2020-09-23T01:51:37.409+0300 [DEBUG] plugin.terraform-provider-azurerm_v2.25.0_x5.exe: GET /subscriptions/629f9ad3-

Subscription 629f9ad3- nowhere listed or hardcoded. There is the issue, somehow plugin gets this subscription processing.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Ramutis 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration (and how the Statefile works) - since there appears to be resources tracked in a local statefile.

Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by Ramutis** [comment]
Hello,

It very strange, because I have cleared state file and behavior the same.  Maybe some files exists somewhere else not in project directory?
