### ISSUE TITLE
How to make a new subscription or Active Directory with Terraform

### ISSUE THREAD

**Issue by rodneyjoyce** [terraform-providers/terraform-provider-azurerm#874]
Hi,

I need to create an Azure Active Directory and then create a Subscription and associate it with this AD using Terraform. Looking at the Azure Provider it always seems to work in the context of a Subscription:

# Configure the Microsoft Azure Provider
provider "azurerm" {
  subscription_id = "..."
  client_id       = "..."
  client_secret   = "..."
  tenant_id       = "..."
}

Is this possible with Terraform?

**Comment by katbyte** [comment]
Hello @rodneyjoyce,

In short it is not. Currently creating Azure active directories and subscriptions are not supported within the terraform provider as there are no APIs exposed to create an active directory or a Subscription. Terraform requires a service principal in an existing active directory tied to a subscription and would not have any permissions outside said subscription.

Additionally when you set up a subscription credit card information needs to be submitted to Azure. 

I hope this clears things up. As there is nothing we can do I am going to close this issue.
