### ISSUE TITLE
azurerm_policy_definition mode is case sensitive

### ISSUE THREAD

**Issue by sebastus** [terraform-providers/terraform-provider-azurerm#8748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_policy_definition `

### Terraform Configuration Files

```hcl
resource "azurerm_policy_definition" "key_vault_soft_delete" {
  name                  = "Key-Vault-Soft-Delete"
  policy_type           = "Custom"
  mode                  = "indexed"
  display_name          = "Key-Vault-Soft-Delete"
  management_group_name = var.definition_management_group
  policy_rule           = file("${path.module}/policies/keyVaultSoftDelete/policyRule.json")
}
```

### Expected Behavior

When this snippet is applied, a policy definition is created as one would expect. A "terraform plan" after apply should yield that no changes are required.  

### Actual Behavior

However, a "terraform plan" after "terraform apply" yields the need to update the resource.  

The problem is a case sensitive comparison on the 'mode' property and that mode "indexed" is stored as "Indexed" during apply. 

### Steps to Reproduce

1. `terraform apply` with the snippet
2. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @sebastus 

Thanks for opening this issue.

Taking a look into this this appears to be a bug where the validation for the `mode` field allows this to be the incorrect case - Terraform is case-sensitive and as such this validation wants updating here. For now you should be able to remove the diff by updating `indexed` to `Indexed` to match what's coming back from Azure here.

Thanks!
