### ISSUE TITLE
Virtual network gateway required subnet to be named 'GatewaySubnet'

### ISSUE THREAD

**Issue by martinbjorgan** [terraform-providers/terraform-provider-azurerm#875]
### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_network_gateway

Error messge after terraform apply:
* module.vpn_ipsec_gateway.azurerm_virtual_network_gateway.vnet_gateway: expected ip_configuration.0.subnet_id to reference a gateway subnet with name GatewaySubnet

Changing the name of the referenced subnet to "GatewaySubnet" fixed the issue. 

Should be able to call the subnet whatever?

resource_arm__virtual_network_gateway.go
func validateArmVirtualNetworkGatewaySubnetId(i interface{}, k string) (s []string, es []error) {

if subnet != "GatewaySubnet" {
		es = append(es, fmt.Errorf("expected %s to reference a gateway subnet with name GatewaySubnet", k))
	}
}

**Comment by tombuildsstuff** [comment]
hey @martinbjorgan 

Thanks for opening this issue :)

As far as I'm aware it's a requirement on the Azure side that the subnet is named `GatewaySubnet` (hence the validation and the documentation) - however should this change in the future we can certainly look to update the validation here. Given there's not a lot we can do here I'm going to close this issue for the moment - however we'll be sure to take another look into this should it change in the future.

Thanks!

**Comment by gk-fschubert** [comment]
Hey, the problem still exist. Is there a plan to fix this? Best Regards

**Comment by martinbjorgan** [comment]
@gk-fschubert Azure requires the subnet associated with the virtual network gateway to be named 'GatewaySubnet'.
Same as for the azure firewall for example, this subnet needs to be named 'AzureFirewallSubnet'

**Comment by gk-fschubert** [comment]
@martinbjorgan, sorry for the misunderstanding. I thought it was a bug because you can "choose" the name
