### ISSUE TITLE
azurerm_cdn_endpoint request_uri_condition if "any" match_values still required

### ISSUE THREAD

**Issue by snofe** [terraform-providers/terraform-provider-azurerm#8770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.21
+ provider.azurerm v2.30.0
```

### Affected Resource(s)

* `azurerm_cdn_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_endpoint" "example" {
  name                = "example-${terraform.workspace}"
  resource_group_name = var.RESOURCE_GROUP.name
  location            = var.RESOURCE_GROUP.location
  profile_name        = azurerm_cdn_profile.iam-cdn-profile.name

  origin {
    name      = "example${terraform.workspace}"
    host_name = var.PLUGIN_JS_ENDPOINT
  }

  delivery_rule {
    name  = "SecurityHeaders"
    order = 1

    request_uri_condition {
      operator     = "Any"
      match_values = ["*"]
    }

    modify_response_header_action {
      action = "Append"
      name   = "X-Frame-Options"
      value  = "SAMEORIGIN"
    }
  }

  origin_host_header = var.PLUGIN_JS_ENDPOINT
}
```

### Expected Behavior

Expected TF to create new rule with request uri condition

### Actual Behavior

The following error occurs:
```
Error: Error waiting for the CDN Endpoint "example" (Profile "example-cdn-dev" / Resource Group "example") to finish updating: Code="BadRequest" Message="{\"ErrorMessage\":\"Invalid RulesEngineConfig: (Match value(s) must not be provided for Operator 'Any').\"}"

  on CDN\terraform.tf line 107, in resource "azurerm_cdn_endpoint" "example":
 107: resource "azurerm_cdn_endpoint" "example" {
```

### Comment

I tried to not using **match_values** or to set it to **null** but it is required by azurerm provider validation.

**Comment by magodo** [comment]
@snofe Thank you for letting us know this bug :+1:

Except to the `request_uri_condition`, I guess some of the other conditions also have the same issue. I will submit a PR to fix that.
