### ISSUE TITLE
azurerm_windows_virtual_machine_scale_set isn't creating a system identity

### ISSUE THREAD

**Issue by miat-asowers** [terraform-providers/terraform-provider-azurerm#8780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.29.0
```

### Affected Resource(s)

* `azurerm_windows_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
resource "azurerm_windows_virtual_machine_scale_set" "ct" {
  name                = "${var.prefix}-ct-vmss"
  resource_group_name = azurerm_resource_group.workflow.name
  location            = azurerm_resource_group.workflow.location
  sku                 = "Standard_F2"
  instances           = 1
  admin_username      = var.vmss_ct_username
  admin_password      = var.vmss_ct_password

  custom_data         = filebase64("Powershell/install-deployment-agent.ct.${var.env}.ps1")

  computer_name_prefix = "${var.prefix}-ct"

  identity {
    type = "SystemAssigned"
  }
  
  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-Datacenter"
    version   = "latest"
  }

  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadWrite"
  }

  network_interface {
    name    = "nic"
    primary = true

    ip_configuration {
      name      = "internal"
      primary   = true
      subnet_id = azurerm_subnet.ct.id
    }
  }
}

# snip

resource "azurerm_key_vault_access_policy" "test" {
  key_vault_id = azurerm_key_vault.devops.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_windows_virtual_machine_scale_set.ct.identity.0.principal_id

  key_permissions = [
    "get"
  ]

  secret_permissions = [
    "get"
  ]

  certificate_permissions = [
    "get"
  ]

  }
```

### Expected Behavior

I would expect the VMSS to have a system-assigned identity that I can then use to assign permissions on a keyvault instance. 

### Actual Behavior

```
Error: Invalid index

  on workflow.tf line 154, in resource "azurerm_key_vault_access_policy" "test":
 154:   object_id    = azurerm_windows_virtual_machine_scale_set.ct.identity.0.principal_id
    |----------------
    | azurerm_windows_virtual_machine_scale_set.ct.identity is empty list of object

The given key does not identify an element in this collection value.
```

I have also verified in the portal that the system assigned identity is disabled.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running in Azure US Government

**Comment by tombuildsstuff** [comment]
hi @miat-asowers 

Thanks for opening this issue.

Taking a look through here this appears to be a bug in Terraform Core - and as such I'm going to close this in favour [of this issue which is tracking this bug](https://github.com/hashicorp/terraform/issues/25578) - would you mind subscribing to that issue for updates?

Thanks!

**Comment by asowers-jcma** [comment]
I have read through the linked issue and many of the linked issues, and I still don't see how this is related to count indexes. From what I can tell, terraform is correctly telling me that the object list is empty, because the terraform azurerm provider did not create a system managed identity (this is consistent with what I see in the portal). We have subsequently moved on to Azure RM web apps and have the same issue with system managed identity creation. 

What am I missing here?
