### ISSUE TITLE
azurerm_kubernetes_cluster Creates Resources with Incorrect Resource Group Name

### ISSUE THREAD

**Issue by krikork** [terraform-providers/terraform-provider-azurerm#879]
Creating an azurerm_kubernetes_cluster in Terraform provisions a number of resources but most of them disobey the value provided in field resource_group_name.

My tf file looks like this: 
resource "azurerm_kubernetes_cluster" "container_service" {
  name                   = "${var.container_service_name}"
  location               = "${var.resource_group_location}"
  resource_group_name    = "${var.resource_group_name}"
  kubernetes_version     = "1.8.2"
  dns_prefix             = "${var.dns_name_prefix}"
...

Where var.resource_group_name is "k8s".

The result is that resources get created in Azure but most of them get a resource group name of "MC_k8s_k8s-containerservice_eastus" instead of the expected "k8s". Only the Container service resource has the expected resource group name of "k8s".

This causes a problem if someone wants to locate the resources for further configuration.

**Comment by Stavrus** [comment]
I came across this as well, but it's not an issue with the Terraform provider. See https://github.com/Azure/AKS/issues/3

**Comment by krikork** [comment]
Thanks!
