### ISSUE TITLE
Support for WVD Hostpool RDP Properties

### ISSUE THREAD

**Issue by alexwilcox9** [terraform-providers/terraform-provider-azurerm#8800]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it is possible to create Windows Virtual Desktop Hostpools through Terraform but not to configure any of the RDP properties such as blocking device redirection, clipboard access etc.
Adding this functionality would make life a lot easier as it would reduce my teams dependancy on ARM templates

Thanks for the great work you're all doing, keep it up!

### New or Affected Resource(s)

* azurerm_virtual_desktop_host_pool

### Potential Terraform Configuration

One possible implementation could be to provide the RDP configuration as a string which is how I've been doing it in ARM
```hcl
resource "azurerm_virtual_desktop_host_pool" "personalautomatic" {
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  name                             = "personalautomatic"
  friendly_name                    = "personalautomatic"
  description                      = "Acceptance Test: A Personal host pool - personalautomatic"
  type                             = "Personal"
  load_balancer_type               = "Persistent"
  personal_desktop_assignment_type = "Automatic"

  rdp_properties = "redirectclipboard:i:0;camerastoredirect:s:*;redirectprinters:i:0"

}
```
Or there could be an rdp_properties block that supports the various options
```hcl
resource "azurerm_virtual_desktop_host_pool" "personalautomatic" {
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  name                             = "personalautomatic"
  friendly_name                    = "personalautomatic"
  description                      = "Acceptance Test: A Personal host pool - personalautomatic"
  type                             = "Personal"
  load_balancer_type               = "Persistent"
  personal_desktop_assignment_type = "Automatic"

  rdp_properties {
    redirectclipboard = false
    camerastoredirect = "*"
    redirectprinters  = false
  }

}
```
### References

* https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files
* #3507 
* #8605

**Comment by pritkallu** [comment]
I have discovered a typo in the documentation when using the argument to configure a WVD host pool validation environment.  The documentation states the argument is **validation_environment** but terraform will only accept **validate_environment**
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_host_pool
