### ISSUE TITLE
Support for spatial indexes in `azurerm_cosmosdb_sql_container` indexing policy

### ISSUE THREAD

**Issue by favoretti** [terraform-providers/terraform-provider-azurerm#8817]
Please add support for spatial indexes in `azurerm_cosmosdb_sql_container` indexing policy.
I'll probably be working on this myself, but opening up an issue in case someone feels compelled as well :)

**Comment by SimonGasparKentico** [comment]
Any update? :)

**Comment by favoretti** [comment]
Oh yeah... I kinda forgot about it, sorry about that. I'll see what I can do early next week.

**Comment by yupwei68** [comment]
I'll work on that.
