### ISSUE TITLE
Application Gateway: Rewrite rules not working for HTTP Header variables

### ISSUE THREAD

**Issue by jozephp** [terraform-providers/terraform-provider-azurerm#8818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_v2.10.0`
* `terraform_v0.12.29`

### Terraform Configuration Files

```hcl
rewrite_rule_set {
    name                        = "Http2HttpsRewriteRule"
    rewrite_rule {
      name                      = "RewriteLocationHeader"
      rule_sequence	            = 101
      condition {
        variable                = "var_location"
        pattern                 = "http:(.*)$"
      }
      response_header_configuration {
        header_name             = "Location"
        header_value            = "https:{http_resp_Location_1}"
      }
    }
  }
```

### Actual Behavior

Error: Error Creating/Updating Application Gateway "apgw-twa1-cm-appgateway001" (Resource Group "XXX"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRewriteRuleConditionUnknownServerVariable" Message="Condition variable: var_location, does not follow supported syntax. Unknown server variable mentioned. For more details refer to the documentation here: https://aka.ms/appgwheadercrud." Details=[]

  on deploy.tf line 310, in resource "azurerm_application_gateway" "apg_poc":
 310: resource "azurerm_application_gateway" "apg_poc" {
### Steps to Reproduce

1. `terraform apply`

### References

* As per https://github.com/terraform-providers/terraform-provider-azurerm/issues/3284 this seems to have been fixed but looks to be not fixed

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Per [document](https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers-url#server-variables) and above error message, I assume you're using incorrect server variable. Below is the example for the scenario you're requesting. For more usage problems, suggest to raise question on [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers).
```
rewrite_rule_set {
    name = local.rewrite_rule_set_name

    rewrite_rule {
      name          = local.rewrite_rule_name
      rule_sequence = 1

      condition {
        variable = "var_request_scheme"
        pattern  = "http"
      }

      request_header_configuration {
        header_name  = "Location"
        header_value = "https:{http_resp_Location_1}"
      }
    }
  }
```

**Comment by jozephp** [comment]
@neil-yechenwei  The intention was to understand if the _condition_ block supports _HTTP header_ _Header Response_ variable Location too besides the Server variable as mentioned on [3284](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3284)

**Comment by neil-yechenwei** [comment]
Per the [doc](https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers-url#server-variables) and API error message, I assume server variables doesn't support location variable. After checked the [doc](https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers#modify-a-redirection-url) and the [usage](https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers#rewrite-actions), I assume you have to use http header variable to rewrite location header. Below is the example.
```
rewrite_rule_set {
    name = local.rewrite_rule_set_name

    rewrite_rule {
      name          = local.rewrite_rule_name
      rule_sequence = 1

      condition {
        variable = "http_resp_Location"
        pattern  = "http:(.*)$"
      }

      response_header_configuration {
        header_name  = "Location"
        header_value = "https:{http_resp_Location_1}"
      }
    }
  }
``` 
or
```
rewrite_rule_set {
    name = local.rewrite_rule_set_name

    rewrite_rule {
      name          = local.rewrite_rule_name
      rule_sequence = 1

      condition {
        variable = "http_req_Location"
        pattern  = "http:(.*)$"
      }

      request_header_configuration {
        header_name  = "Location"
        header_value = "https:{http_resp_Location_1}"
      }
    }
  }
```
