### ISSUE TITLE
terraform 0.13: state blob is already locked / blob metadata "terraformlockid" was empt

### ISSUE THREAD

**Issue by gdubya** [terraform-providers/terraform-provider-azurerm#8819]
This is a duplicate of [25818 in the terraform repo](https://github.com/hashicorp/terraform/issues/25818), but i think it might be caused by the azure provider rather than terraform itself?

### Config

```
  backend "azurerm" {
    resource_group_name  = "myrg"
    storage_account_name = "mysa"
    container_name       = "terraform"
    key                  = "mystate.terraform.tfstate"
  }
```

### Version
```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.31.1
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
```

### Expected Behavior
* Migrate from local backend provider to azure storage
* Execute terraform plan ok
* Execute terraform apply ok

### Actual Behavior
```
➜terraform plan

Error: Error locking state: Error acquiring the state lock: 2 errors occurred:
	* state blob is already locked
	* blob metadata "terraformlockid" was empty



Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
```

**Comment by tombuildsstuff** [comment]
hi @gdubya 

Thanks for opening this issue.

The Azure Backend is entirely contained as a part of Terraform Core at this time and as such is unaffected by the provider behaviour - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of https://github.com/hashicorp/terraform/issues/25818 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by gdubya** [comment]
Hi @tombuildsstuff 
oh ok, will do. sorry for making a mess and thanks for the explanation!
