### ISSUE TITLE
Destroying azurerm_storage_account_customer_managed_key configured with existing key vault key (data resource) not working 

### ISSUE THREAD

**Issue by philippbussche** [terraform-providers/terraform-provider-azurerm#8839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.28
+ provider.azurerm v2.31.1

### Affected Resource(s)

* `azurerm_storage_account_customer_managed_key`

### Terraform Configuration Files

```hcl
data "azurerm_key_vault" "key_vault" {
  name                = local.key_vault_name
  resource_group_name = local.security_resource_group_name
}

data "azurerm_key_vault_key" "key_vault_key" {
  name         = local.key_vault_key_name
  key_vault_id = data.azurerm_key_vault.key_vault.id
}

resource "azurerm_key_vault_access_policy" "storage" {
  key_vault_id = data.azurerm_key_vault.key_vault.id
  tenant_id    = data.azurerm_subscription.current.tenant_id
  object_id    = azurerm_storage_account.datalake.identity.0.principal_id

  key_permissions    = ["get", "create", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
  secret_permissions = ["get"]
}

resource "azurerm_storage_account" "datalake" {
  name                     = local.datalake_name
  location                 = var.resource_group_location
  resource_group_name      = var.resource_group_name
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "LRS"
  is_hns_enabled           = true
  allow_blob_public_access = false
  min_tls_version          = "TLS1_2"

  identity {
    type = "SystemAssigned"
  }

  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices"]
    virtual_network_subnet_ids = var.allow_subnet_ids
  }
}

resource "azurerm_storage_account_customer_managed_key" "datalake_cmk" {
  storage_account_id = azurerm_storage_account.datalake.id
  key_vault_id       = data.azurerm_key_vault.key_vault.id
  key_name           = data.azurerm_key_vault_key.key_vault_key.name
}
```

### Expected Behavior

Similar to being able to load the existing key (via the data source) and then using it for configuring the customer managed key for the storage account it should be possible to remove the customer managed key configuration (obviously not the key itself) for the storage account.

### Actual Behavior

terraform apply succeeds, however terraform destroy fails with the following error message:

Error: Error removing Customer Managed Key for Storage Account "xxxx" (Resource Group "yyy"): storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="KeyVaultAuthenticationFailure" Message="The operation failed because of authentication issue on the keyvault."

Please not that this is a return code 400 and not 403. Since the creation of the resource succeeded as well as loading the key this should not be a permissions (access policy) issue.

Running a simple deployment as specified in the [provider docs](https://www.terraform.io/docs/providers/azurerm/r/storage_account_customer_managed_key.html) succeeds if the access policy for the client is configured within the composition. However this will result in having Terraform managing the access policy (creation and deletion). This is great for a new key as well as if the client (in my case this would be a service principal) is not already configured in the access policies through some other means. Also with this setup I cannot load an existing key to be used.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by philippbussche** [comment]
Hi again. I think I found the issue. I have missed a dependency that will delay the deletion of the resource azurerm_storage_account_customer_managed_key to after the policy azurerm_key_vault_access_policy has been removed. This seems to have been my issue. The policy that grants the storage account permissions to interact with the key vault were removed too early. The dependency that I have added with which my setup is now working is:

data "azurerm_key_vault_key" "key_vault_key" {
  name         = local.key_vault_key_name
  key_vault_id = data.azurerm_key_vault.key_vault.id
  depends_on = [
    azurerm_key_vault_access_policy.storage
  ]
}

Again I don't need an access policy for the client and depend on that since this permission is already given outside of TF.

Thanks
Philipp

**Comment by nishantsondhi16** [comment]
Adding an explicit depends in the resource "azurerm_storage_account_customer_managed_key" on the policy worked for me.

resource "azurerm_storage_account_customer_managed_key" "this" {
  provider = azurerm.local
  count    = local.present

  depends_on = [azurerm_key_vault_access_policy.storage]

  storage_account_id = azurerm_storage_account.this[0].id
  key_vault_id       = local.key_vault_id
  key_name           = local.key_name
}

resource "azurerm_key_vault_access_policy" "storage" {
  provider = azurerm.local
  count    = local.present

  key_vault_id       = local.key_vault_id
  tenant_id          = data.azurerm_client_config.current.tenant_id
  object_id          = azurerm_storage_account.this[0].identity.0.principal_id
  key_permissions    = ["get", "create", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
  secret_permissions = ["get"]
}

**Comment by tombuildsstuff** [comment]
hi @philippbussche 

Thanks for opening this issue.

Taking a look through here this, as @nishantsondhi16 has men tioned appears to be an issue with the Terraform Configuration - where the Storage Account doesn't have permission to access the Key Vault Key it's referencing, due to a missing `depends_on` within the Storage Account resource on the Key Vault Access Policy resource.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
