### ISSUE TITLE
Unable to enable container insights on an existing cluster

### ISSUE THREAD

**Issue by d-tris** [terraform-providers/terraform-provider-azurerm#8852]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```text
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.31.1
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

* [First revision](https://gist.github.com/d-tris/604d672d09fab0be24148ed50ca18228)
* [Second revision](https://gist.github.com/d-tris/a142cd80cfdc17f33d51417d30539b31)

### Debug Output

https://gist.github.com/d-tris/ca485a54da64c3bab2729dfbc1652705

### Expected Behavior

Applying the second revision of the config file to resources created with the first revision of the config file should enable the OMS Agent for the k8s cluster and give it the "Monitoring Metrics Publisher" role so that it can actually publish metrics.

### Actual Behavior

Terraform exits with an error:

```text
Error: Invalid index

  on main.tf line 54, in resource "azurerm_role_assignment" "k8s_oms_agent_monitoring_metrics_publisher":
  54:   principal_id         = azurerm_kubernetes_cluster.k8s.addon_profile.0.oms_agent.0.oms_agent_identity.0.object_id
    |----------------
    | azurerm_kubernetes_cluster.k8s.addon_profile[0].oms_agent[0].oms_agent_identity is empty list of object

The given key does not identify an element in this collection value.
```

****

### Steps to Reproduce

1. Run `terraform apply` on the first revision of the provided config file
2. Run `terraform apply` on the second revision of the provided config file

### Notes

I wasn't able to find a good workaround for this. The best one I found is to abuse `for_each` for the role assignment in this way:

```hcl
resource "azurerm_role_assignment" "k8s_oms_agent_monitoring_metrics_publisher" {
  for_each = toset(azurerm_kubernetes_cluster.k8s.addon_profile.0.oms_agent.0.oms_agent_identity.*.object_id)

  scope                = azurerm_kubernetes_cluster.k8s.id
  role_definition_name = "Monitoring Metrics Publisher"
  principal_id         = each.key
}
```

However, doing it this way requires two applies - the first one enables the OMS agent and the second one creates the role assignment.

**Comment by tombuildsstuff** [comment]
hey @d-tris 

Thanks for opening this issue.

Taking a look through here this appears to be a bug in Terraform Core - and as such I'm going to close this in favour [of this issue which is tracking this bug](https://github.com/hashicorp/terraform/issues/25578) - would you mind subscribing to that issue for updates?

Thanks!

**Comment by d-tris** [comment]
Hi @tombuildsstuff,

I am not entirely sure if the linked issues is 100% relevant (it seems like every problem with indexing falls into that issue, which isn't super helpful), but I'll keep an eye on it.

Also, it seems like this wouldn't be an issues if azurerm didn't use lists for things that are not lists, such as `addon_profile`, `oms_agent` and `oms_agent_identity` here.

If the structure were instead like this:

```text
addon_profile = {
  oms_agent = {
    enabled = ...
    oms_agent_identity = {
      client_id = ...
      object_id = ...
      user_assigned_identity_id = ...
    }
  }
}
```

then I'm pretty sure that terraform would be fine with `azurerm_kubernetes_cluster.k8s.addon_profile.oms_agent.oms_agent_identity.object_id`. The `object_id` can still be null if the `oms_agent` is disabled, so that should be fine.

Is there a particular reason why these things are stored in lists?
