### ISSUE TITLE
Error: flattening `default_node_pool`: The Default Agent Pool "" was not found

### ISSUE THREAD

**Issue by Karadiavinay** [terraform-providers/terraform-provider-azurerm#8869]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.16

provider.azurerm v2.25.0
provider.kubernetes v1.17.9

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

####backend.tf script content
```hcl
terraform {
  required_version = ">= 0.12"
  required_providers {
    azurerm = "=2.25.0"
  }
  backend "azurerm" {
  }
```
#### Existing AKS cluster resource config
```hcl
resource "azurerm_kubernetes_cluster" "cluster" {
  location            = azurerm_resource_group.group.location
  resource_group_name = azurerm_resource_group.group.name
  name                = var.cluster_name
  kubernetes_version  = var.kubernetes_version
  node_resource_group = "${var.cluster_name}-infra"

  dynamic "agent_pool_profile" {
    for_each = var.agent_pools
    content {
      name                = format("%s%s%02d", agent_pool_profile.value.os == "Windows" ? "w" : "l", var.location_short, agent_pool_profile.key)
      count               = agent_pool_profile.value.min_count
      vm_size             = agent_pool_profile.value.vm_size
      os_type             = agent_pool_profile.value.os
      os_disk_size_gb     = agent_pool_profile.value.os_disk_size
      type                = "VirtualMachineScaleSets"
      min_count           = agent_pool_profile.value.min_count
      max_count           = agent_pool_profile.value.max_count
      max_pods            = agent_pool_profile.value.max_pods
      enable_auto_scaling = true
      vnet_subnet_id      = azurerm_subnet.k8s_subnet.id
    }
  }
  network_profile {
    ...
  }

  windows_profile {
    ...
  }
  service_principal {
    ...
  }
  role_based_access_control {
    enabled = true
  }
  addon_profile {
    oms_agent {
      ...
    }
  }
  depends_on = [azurerm_subnet.k8s_subnet]
  tags       = var.resource_tags
}
```

#### Updating AKS cluster resource as written below:
```hcl
resource "azurerm_kubernetes_cluster" "cluster" {
  location            = azurerm_resource_group.group.location
  resource_group_name = azurerm_resource_group.group.name
  name                = var.cluster_name
  kubernetes_version  = var.kubernetes_version
  node_resource_group = "${var.cluster_name}-infra"

  default_node_pool {
    name                = format("%s%s%s","sys","l", var.location_short)
    vm_size             = var.system_node_pool.vm_size
    os_disk_size_gb     = var.system_node_pool.os_disk_size
    type                = "VirtualMachineScaleSets"
    min_count           = var.system_node_pool.min_count
    max_count           = var.system_node_pool.max_count
    max_pods            = var.system_node_pool.max_pods
    enable_auto_scaling = true
    vnet_subnet_id      = azurerm_subnet.k8s_subnet.id
    node_taints         = ["CriticalAddonsOnly=true:NoSchedule"]
  }
  network_profile {
    ...
  }
  windows_profile {
    ...
  }
  service_principal {
   ...
  }
  role_based_access_control {
    enabled = true
  }
  depends_on = [azurerm_subnet.k8s_subnet]
  tags       = var.resource_tags
}
```

### Panic Output

[error]Terraform command 'plan' failed with exit code '1'.:  flattening `default_node_pool`: The Default Agent Pool "" was not found
### Expected Behavior

terraform plan should work without throwing an error, or at least give a better error description that enables the user to fix the error on their own.
### Actual Behavior

terraform plan throws an error

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I am upgrading a terraform deployment from azurerm 1.36.1 to 2.25.0
### References

* As per this earlier issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/7813#issuecomment-682127444  it should be resolved.

**Comment by tombuildsstuff** [comment]
hi @Karadiavinay 

Thanks for opening this issue.

In order to represent breaking changes on the Azure side, the `azurerm_kubernetes_cluster` resource has gone through several major changes since the 1.x releases. Whilst it's possible to workaround this by upgrading to different versions of the Azure Provider (using the upgrade notes in the [changelog](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md) which contains the upgrade steps necessary here) - I'd suggest it'd be easier to remove this AKS Cluster from your statefile and reimport it using `terraform import`.

Due to the frequent breaking changes in the AKS service, whilst we try our best to maintain schema and resource compatibility over time - unfortunately we're limited by the AKS Service - as such when using AKS we recommend using the latest version of the Azure Provider at all times. Since in this instance this should be fixed by removing the AKS Cluster from your statefile and reimporting this, I'm going to close this issue for the moment.

Thanks!

**Comment by notzippy** [comment]
I tried to remove and add the AKS cluster using `state import`  and get the exact same message.

```
 Prepared azurerm_kubernetes_cluster for import
azurerm_kubernetes_cluster.shared: Refreshing state... [id=]


Error: flattening `default_node_pool`: The Default Agent Pool "" was not found
```

**Comment by notzippy** [comment]
The node pool has the mode set to "User", which it looks like someone has identified as an issue here #7813

https://github.com/terraform-providers/terraform-provider-azurerm/blob/76a112f5c206835e0b945305022112ffe8e939de/azurerm/internal/services/containers/kubernetes_nodepool.go#L401-L403

However I cannot change the mode on my AKS
```
az aks nodepool update --cluster-name shared --resource-group mygroup -n shared --mode System
BadRequestError: Operation failed with status: 'Bad Request'. Details: AgentPool APIs supported only for clusters with VMSS agentpools. For more information, please check https://aka.ms/multiagentpoollimitations
```
It also appears I cannot add additional node pools in the portal (to switch over). Any thoughts on what else I could try?

**Comment by tombuildsstuff** [comment]
@notzippy just to clarify, your using the AvailabilitySet mode

**Comment by notzippy** [comment]
@tombuildsstuff no I am not.

**Comment by xsreality** [comment]
I am facing same issue while trying to import an existing AKS cluster. Is there any workaround available?
