### ISSUE TITLE
azurerm_cdn_endpoint : OriginHostHeader must match the regex

### ISSUE THREAD

**Issue by jfcoz** [terraform-providers/terraform-provider-azurerm#8870]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.29
+ provider.azuread v0.11.0
+ provider.azurerm v2.22.0
+ provider.random v2.3.0
+ provider.tls v2.2.0
```

### Affected Resource(s)

* `azurerm_cdn_endpoint`

### Terraform Configuration Files

From documentation : 

> origin_host_header - (Optional) The host header CDN provider will send along with content requests to origins. Defaults to the host name of the origin.

When using azurerm_cdn_endpoint without a origin_host_header we get this error.

`Error: Error waiting for CDN Endpoint "…" (Profile "…" / Resource Group "…") to finish creating: Code="BadRequest" Message="{\"ErrorMessage\":\"Errors found in Model: OriginHostHeader must match the regex '(^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9_\\\\-]*[a-zA-Z0-9])\\\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\\\-]*[A-Za-z0-9])$)|((?:[:0-9A-Fa-f]+))'.\"}"`

From https://docs.microsoft.com/en-us/rest/api/cdn/endpoints/create : 

> properties.originHostHeader | string | The host header value sent to the origin with each request. This  property at Endpoint can only be set allowed when endpoint uses single  origin. If you leave this blank, the request hostname determines this  value. Azure CDN origins, such as Web Apps, Blob Storage, and Cloud  Services require this host header value to match the origin hostname by  default.

With `origin_host_header = ""`, same error.

Manual setup via portal works.

### References

* #3084

**Comment by steve-88** [comment]
Any update on this? I want a blank origin_host_header but "" and null do not work

**Comment by rikribbers** [comment]
ran into the same issue. in the API specs ( https://docs.microsoft.com/en-us/rest/api/cdn/endpoints/create )

The host header value sent to the origin with each request. This property at Endpoint can only be set allowed when endpoint uses single origin. If you leave this blank, the request hostname determines this value. Azure CDN origins, such as Web Apps, Blob Storage, and Cloud Services require this host header value to match the origin hostname by default.

So depending on your origin it is required.
