### ISSUE TITLE
`azurerm_policy_set_definition` reports error during update

### ISSUE THREAD

**Issue by ArcturusZhang** [terraform-providers/terraform-provider-azurerm#8880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.12.29

### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = ">=2.31.0"
  features {}
}
data "azurerm_policy_definition" "activity_log_exist_admin_operations" {
  display_name = "An activity log alert should exist for specific Administrative operations"
}
resource "azurerm_policy_set_definition" "cis_custom" {
  name                  = "CIS Custom Effects"
  policy_type           = "Custom"
  display_name          = "CIS Custom Effects"
  policy_definition_reference {
    policy_definition_id = data.azurerm_policy_definition.activity_log_exist_admin_operations.id
    parameter_values = jsonencode({
      operationName = { value = "Microsoft.Sql/servers/firewallRules/delete" }
    })
  }
}
```

### Expected Behavior

The policy set definition could be updated successfully

### Actual Behavior

An error occurs:
```
Error: expanding `policy_definition_reference`: cannot set both `parameters` and `parameter_values`
```

### Steps to Reproduce

1. `terraform apply` with the config above
1. change the display name and `terraform apply` again

### References

* #0000

**Comment by gettek** [comment]
## Also related

`parameter_values = {}`

### Results in:

`Inappropriate value for attribute "parameter_values": string required.`

**Comment by gettek** [comment]
# Also Related

`parameter_values` now expects a string should be an object map

`Inappropriate value for attribute "parameter_values": string required.`

**Comment by ArcturusZhang** [comment]
> # Also Related
> `parameter_values` now expects a string but should be an object map:
> 
> `Inappropriate value for attribute "parameter_values": string required.`

Actually `parameters` is an object map (and deprecated), `parameter_values` is a JSON string with the same format as the `parameters` in `azurerm_policy_assignment`.

Please note the `jsonencode` function in the config I posted in the description.

**Comment by gettek** [comment]
> > # Also Related
> > `parameter_values` now expects a string but should be an object map:
> > `Inappropriate value for attribute "parameter_values": string required.`
> 
> Actually `parameters` is an object map (and deprecated), `parameter_values` is a JSON string with the same format as the `parameters` in `azurerm_policy_assignment`.
> 
> Please note the `jsonencode` function in the config I posted in the description.

The docs should be updated then:
`parameter_value` - (Optional) Parameter values for the referenced policy rule. This field is a **json object** that allows you to assign parameters to this policy rule.

**Comment by ArcturusZhang** [comment]
Hi @gettek I also include the doc update in my fix for this issue.
