### ISSUE TITLE
action_set in rewrite_rule not working

### ISSUE THREAD

**Issue by piyush94** [terraform-providers/terraform-provider-azurerm#8897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0

### Affected Resource(s)
azurerm_application_gateway

### Terraform Configuration Files
```
rewrite_rule_set {
    name = "path-rewrites"
    rewrite_rule {
        name          = "set_path_variable"
        rule_sequence = 100

        condition {
            ignore_case = true
            negate      = false
            pattern     = ".*path/(.*)"
            variable    = "var_uri_path"
        } 

        action_set {
            url_configuration = "/new/path/here-{var_uri_path_1}"
        }

    }
}
```

### Debug Output
```
2020/10/15 05:41:15 [TRACE] eval: *terraform.EvalSequence
2020/10/15 05:41:15 [TRACE] eval: *terraform.EvalGetProvider
2020/10/15 05:41:15 [TRACE] eval: *terraform.EvalValidateResource
2020/10/15 05:41:15 [ERROR] eval: *terraform.EvalValidateResource, err: Unsupported block type: Blocks of type "action_set" are not expected here.
2020/10/15 05:41:15 [ERROR] eval: *terraform.EvalSequence, err: Unsupported block type: Blocks of type "action_set" are not expected here.
```

### Notes
We could not find a working example of `action_set`. So, after looking the source code we made an informed guess for the location of `action_set` block. Any help will be appreciated.
Thanks

**Comment by tombuildsstuff** [comment]
hi @piyush94 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by piyush94** [comment]
@tombuildsstuff To me, it looks like a bug only as there is no reference for `action_set` in `terraform-provider-azurerm\azurerm\internal\services\network\application_gateway_resource.go`
But when we create a condition-based rewrite rule, it throws an error that `action_set` is a required block.

Community discussion opened by us, https://discuss.hashicorp.com/t/how-to-specify-an-actionset-in-a-rewriterule-for-azurerm-application-gateway/12787

**Comment by piyush94** [comment]
@tombuildsstuff Kindly reopen this issue. This is affecting many people and no answer has been provided in the discussion forums.
Thanks.

https://discuss.hashicorp.com/t/how-to-specify-an-actionset-in-a-rewriterule-for-azurerm-application-gateway/12787
https://discuss.hashicorp.com/t/azure-application-gateway-rewrite-rule-with-block-condition-then/9885
