### ISSUE TITLE
Feature Request: add redirect_configuration sub resource to azurerm_application_gateway

### ISSUE THREAD

**Issue by jansepke** [terraform-providers/terraform-provider-azurerm#891]
Hi,

can we implement the [redirect_configuration](https://docs.microsoft.com/en-us/rest/api/application-gateway/applicationgateways/createorupdate#ApplicationGatewayRedirectConfiguration) sub resource to azurerm_application_gateway? And add the redirect-config reference to the request_routing_rule. Then it would be possible to create application gateway redirects (e.g. http -> https) in terraform.

e.g.
```HCL

resource "azurerm_application_gateway" "main" {
  ...
  redirect_configuration {
    name                        = "example"
    type                          = "Permanent"
    include_path             = true
    include_query_string = true
    target_listener            = "https"
  }

  request_routing_rule {
    name                     = "example-redirect"
    rule_type                = "Basic"
    http_listener_name = "http"
    redirect_config        = "example"
  }
}
```

currently I'm using local-exec with the azure-cli

```HCL
resource "null_resource" "redirect-config" {
  triggers {
    gateway = "${azurerm_application_gateway.main.name}"
  }

  provisioner "local-exec" {
    command = <<EOF
      az network application-gateway redirect-config create \
        --gateway-name ${azurerm_application_gateway.main.name} \
        -g ${local.rg} \
        -n example \
        --type Permanent \
        --include-path true \
        --include-query-string true \
        --target-listener ${lookup(azurerm_application_gateway.main.http_listener[1], "name")}
    EOF
  }
}

resource "null_resource" "redirect-rule" {
  triggers {
    gateway = "${azurerm_application_gateway.main.name}"
  }

  provisioner "local-exec" {
    command = <<EOF
      az network application-gateway rule create \
        --gateway-name ${azurerm_application_gateway.main.name} \
        -g ${local.rg} \
        -n example-redirect \
        --rule-type Basic \
        --http-listener ${lookup(azurerm_application_gateway.main.http_listener[0], "name")} \
        --redirect-config celum-test
    EOF
  }
}
```

**Comment by tombuildsstuff** [comment]
hey @jansepke 

Thanks for opening this issue

A feature request to add support for Redirect Rules in the `azurerm_application_gateway` resource has previously been requested in #552, as such I'm going to close this issue in favour of that one. We're currently [waiting on a bug in the Azure API to be fixed](https://github.com/Azure/azure-rest-api-specs/issues/2187) before we add additional functionality (and test cases) for Application Gateway - but once that's fixed we should be able to take a look into this.

Thanks!
