### ISSUE TITLE
long_term_retention_policy values differ, week_of_year can't be 0

### ISSUE THREAD

**Issue by yene** [terraform-providers/terraform-provider-azurerm#8913]
* version = "=2.32.0"

terraform plan configuration always shows value differences between state and deployed
```
      ~ long_term_retention_policy {
            monthly_retention = "P3M"
          ~ week_of_year      = 0 -> 1
            weekly_retention  = "P3W"
          ~ yearly_retention  = "PT0S" -> "P0D"
        }
```

Are the values not correctly transformed?

Note: I am also unable to set week_of_year to 0.

**Comment by pearcec** [comment]
Duplicate #9067?  Prefer #9067 since it is more complete.

**Comment by tombuildsstuff** [comment]
Closing this in favour of #9067 as @pearcec says this appears to be a duplicate - please subscribe to that issue for updates
