### ISSUE TITLE
CreateTrafficManagerBlade","code":"InvalidTemplateDeployment","message upon centralusandcentral india region only permission

### ISSUE THREAD

**Issue by grcchandra** [terraform-providers/terraform-provider-azurerm#892]
Hi,

I have set azure subscription to central US and central India but unable to create Traffic Manager profile
 with error 
{"telemetryId":"3e5ff4b8-e9aa-45d4-9994-531ae302bc1c","bladeInstanceId":"Blade_16cce221f22641b3ad944464dcf3c3d9_11_0","galleryItemId":"Microsoft.TrafficManagerProfile-ARM","createBlade":"CreateTrafficManagerBlade","code":"InvalidTemplateDeployment","message":"The template deployment failed because of policy violation. Please see details for more information.","details":[{"code":"RequestDisallowedByPolicy","target":"cutraff","message":"Resource 'cutraff' was disallowed by policy. Policy identifiers: '[{\"policyDefinitionId\":\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\",\"policyAssignmentId\":\"/subscriptions/e56962a6-89ad-4d66-9296-87cb7a3736b0/providers/Microsoft.Authorization/policyAssignments/CIO\"}]'.","innererror":{"policyInfo":[{"policyDefinitionDisplayName":"Allowed locations","policyAssignmentDisplayName":"CIO","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionEffect":"Deny","policyAssignmentId":"/subscriptions/efefeffe4-89ad-4d66-9296-87cb7a3736b0/providers/Microsoft.Authorization/policyAssignments/CIO","policyAssignmentName":"CIO","policyAssignmentScope":"/subscriptions/7e0c7c04-89ad-4d66-9296-87cb7a3736b0","policyAssignmentSku":{"name":"A0","tier":"Free"},"policyAssignmentParameters":{"listOfAllowedLocations":{"value":["centralindia","centralus"]}}}]}}]}

What cold be the issue..

Thanks and Regards,
Chandra.

**Comment by tombuildsstuff** [comment]
hi @grcchandra 

Thanks for opening this issue.

Based on this error message in the output, I believe there's Resource Policies set up on your Azure Subscription which prevent the deployment of Traffic Manager instances:

> The template deployment failed because of policy violation. Please see details for more information.

I'm not particularly familiar with Resource Policies, but it appears there's a policy configured for which region and SKU the Traffic Manager can be deployed in. As such - I'd suggest checking which policies are active on the subscription to identify what configuration/location you're able to deploy into.

Given this isn't a bug with Terraform (but instead a Resource Policy within the Azure Subscription) - I'm going to close this issue for the moment.

Thanks!

**Comment by grcchandra** [comment]
Hi,

I have set policy to allow all resources in region central us and central
India.

I can overcome this issue if I remove this policy.but I want to restrict to
central India.

Thanks and regards,
Chandra
