### ISSUE TITLE
azurerm_api_management_subscription should not require product and user?!

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#8923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_api_management_subscription`

### Expected Behavior

In APIM through the Azure Portal as well as through the [Powershell command](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementsubscription?view=azps-4.8.0), you can create a new subscription without referencing a Product and/or user. Instead you can scope it, for example, to one or more APIs. This should be possible through Terraform as well.

### Actual Behavior

azurerm_api_management_subscription requires `user_id` and `product_id`

It looks like a bug to me that those are required - or did I miss some other way to create a subscription?

#

**Comment by mcalster** [comment]
It is not a bug. The logic around subscriptions has been extended.
https://docs.microsoft.com/en-us/azure/api-management/api-management-subscriptions#subscriptions-for-all-apis-or-an-individual-api

_When we introduced the Consumption tier of API Management, we made a few changes to streamline key management:

- First, we added two more subscription scopes: all APIs and a single API. The scope of subscriptions is no longer limited to an API product. It's now possible to create keys that grant access to an API, or all APIs within an API Management instance, without needing to create a product and add the APIs to it first. Also, each API Management instance now comes with an immutable, all-APIs subscription. This subscription makes it easier and more straightforward to test and debug APIs within the test console.

- Second, API Management now allows standalone subscriptions. Subscriptions are no longer required to be associated with a developer account. This feature is useful in scenarios such as when several developers or teams share a subscription._

**Comment by sebader** [comment]
@mcalster I'm not quite sure what you are saying, or why you are saying that this is not a bug?! 
> The scope of subscriptions is no longer limited to an API product.
That is my point exactly. But `azurerm_api_management_subscription` requires to specify a product_id and user_id

**Comment by mcalster** [comment]
@sebader Sorry if it was unclear. I only meant to say that it is a "new" feature of the APIM and it is an enhancement more than a bug. Which I would very much like to have access to in terraform.

**Comment by Planche95** [comment]
Is this will be a part of the next release? I can't create a subscription in my consumption api becasue it requires user_id, and users are not supported for this tier.
