### ISSUE TITLE
Cannot delete VNETs and Subnets

### ISSUE THREAD

**Issue by pixelicous** [terraform-providers/terraform-provider-azurerm#894]
### Terraform Version
AzureRM provider 1.1.2
Terraform v0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:
azurerm_subnet
azurerm_virtual_network

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
module "vnet_cidraddress" {
    source              = "git::http://gitmoduleaddress"
    location            = "${var.location}"
    environment         = "${var.environment}"
}

resource "azurerm_resource_group" "rg" {
  name      = "${var.name_prefix}-net-rg"
  location  = "${var.location}"
  tags      = "${var.tags}"
}

module "network" {
    source              = "git::http://gitmoduleaddress"
    resource_group_name = "${azurerm_resource_group.rg.name}"
    location            = "${var.location}"
    vnet_name           = "${var.name_prefix}-net-vnet"
    address_space       = "${module.vnet_cidraddress.address_space}"
    subnet_prefixes     = ["${cidrsubnet(module.vnet_cidraddress.address_space, 5, 12)}","${cidrsubnet(module.vnet_cidraddress.address_space, 5, 13)}","${cidrsubnet(module.vnet_cidraddress.address_space, 5, 19)}"]
    subnet_names        = ["${var.name_prefix}-net-subnet-int01", "${var.name_prefix}-net-subnet-int02","${var.name_prefix}-net-subnet-ext01"]
    tags       = "${var.tags}"
}

resource "azurerm_subnet" "subnet" {
  name  = "${var.name_prefix}-net-subnet-ext01"
  address_prefix = "${cidrsubnet(module.vnet_cidraddress.address_space, 5, 19)}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  virtual_network_name = "${module.network.vnet_name}"
  network_security_group_id = "${azurerm_network_security_group.ssl.id}"
}
```
Network module taken from web
```
#Azure Generic vNet Module
resource "azurerm_resource_group" "network_rg" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.vnet_name}"
  location            = "${var.location}"
  address_space       = ["${var.address_space}"]
  resource_group_name = "${azurerm_resource_group.network_rg.name}"
  dns_servers         = "${var.dns_servers}"
  tags                = "${var.tags}"
}

resource "azurerm_subnet" "subnet" {
  name                 = "${var.subnet_names[count.index]}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  resource_group_name  = "${azurerm_resource_group.network_rg.name}"
  address_prefix       = "${var.subnet_prefixes[count.index]}"
  count                = "${length(var.subnet_names)}"
}
```
### Output
```
module.network.azurerm_subnet.subnet.0: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-int01, 9m0s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-ext01, 9m0s elapsed)
module.network.azurerm_subnet.subnet.1: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-int02, 9m0s elapsed)
module.network.azurerm_subnet.subnet.1: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-int02, 9m10s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-ext01, 9m10s elapsed)
module.network.azurerm_subnet.subnet.0: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-int01, 9m10s elapsed)
module.network.azurerm_subnet.subnet.1: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-int02, 9m20s elapsed)
module.network.azurerm_subnet.subnet.0: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-int01, 9m20s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXX-XXXX-XXX-XXX-...net/subnets/azeu2-prd-net-subnet-ext01, 9m20s elapsed)
```

### Expected Behavior
Subnet should have gotten deleted

### Actual Behavior
Subnets either get deleted, or not, mixed results.
Running destroy again will finally finish the job.

### Steps to Reproduce
1. Create vnet/subnet
2. Delete

**Comment by pixelicous** [comment]
@tombuildsstuff Again i had this weird issue.. 

Deleting 3 subnets, all got destroyed, 2 quicker than the third, but even after the third got deleted, terraform didn't "notice" that it actually deleted it.

azurerm_subnet.subnet: Destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01)
azurerm_subnet.subnet: Destruction complete after 1s
azurerm_network_security_group.ssl: Destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...soft.Network/networkSecurityGroups/ssl)
azurerm_network_security_group.ssl: Still destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...soft.Network/networkSecurityGroups/ssl, 10s elapsed)
azurerm_network_security_group.ssl: Destruction complete after 11s
module.network.azurerm_subnet.subnet[1]: Destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-subnet-name-02)
module.network.azurerm_subnet.subnet[2]: Destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01)
module.network.azurerm_subnet.subnet[0]: Destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-subnet-name-01)
module.network.azurerm_subnet.subnet[0]: Destruction complete after 0s
module.network.azurerm_subnet.subnet[1]: Destruction complete after 1s
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01, 10s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01, 20s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01, 30s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01, 40s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01, 50s elapsed)
module.network.azurerm_subnet.subnet.2: Still destroying... (ID: /subscriptions/XXXXXXX-XXX-XXX-XXX-...net/subnets/our-other-subnet-name01, 1m0s

**Comment by pixelicous** [comment]
@tombuildsstuff Hi Tom, this clearly still happens. I had two vnets, each with a different amount of subnets, but no resources attached to it (NICs or anything).
When deleting, one vnet got deleted no problem, while the other got stuck.
After this test i noticed that one of them had a VNETPeering on it, i know it because i recreated the vnet and trying to recreate the peering again resulted in an error, because it only cleared one side of the peering (from the deleted vnet).

I thought to myself that i found the issue, but then i trial and errored the same vnets with and without vnetpeering, the results were completely random.

I don't think you can push this issue any further in terms of milestones, this is a big thing, not being able to reconstruct our networking from scratch is a big hit, especially as today terraform has issues with relevant items, such as changing NSG details, if the change requires destruction of the resource, terraform just doesnt handle the dettach/reattach as it should (thats another issue of course)

**Comment by pixelicous** [comment]
@tombuildsstuff hey, did you get a chance to see my response for your question to test again?

**Comment by pixelicous** [comment]
@katbyte Tom has requested this 3 months after, after pushing it from 1.2.0 all the way to 1.6.0
Basically it is the most simplistic terraform file you can think of, a VNET and a subnet. I will prepare and upload this somewhere and send a link here.

**Comment by tombuildsstuff** [comment]
hi @pixelicous 

Since we've not heard back from you here I'm going to close this issue for the moment. If this is still an issue you're seeing with the latest version of the provider then please feel free to reopen this with a Terraform Configuration that reproduces this and we'll take a look :)

Thanks!
