### ISSUE TITLE
Support for EnableAnalyticalStorage capability in `azurerm_cosmosdb_account`

### ISSUE THREAD

**Issue by jamesggraf** [terraform-providers/terraform-provider-azurerm#8943]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for the preview capability `EnableAnalyticalStorage`.

### New or Affected Resource(s)

azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAnalyticalStorage"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 10
    max_staleness_prefix    = 200
  }

  geo_location {
    location          = var.failover_location
    failover_priority = 1
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/cosmos-db/analytical-store-introduction

**Comment by annetle** [comment]
Hi! Will analytical store TTL be configurable in azurerm_cosmosdb_sql_containers?
