### ISSUE TITLE
When min_cound is = to max_count get error Error: `max_count` must be >= `min_count` when using azurerm_kubernetes_cluster_node_pool resource

### ISSUE THREAD

**Issue by chrisp787** [terraform-providers/terraform-provider-azurerm#8944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

resource "azurerm_kubernetes_cluster_node_pool" "windows" {
  count                          = var.enable_windows_pool ? 1 : 0
  name                          = "win"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.gdo-aks.id
  os_type                       = "Windows"
  vm_size                       = var.windows_node_size
  enable_auto_scaling   = true
  min_count                   = 1
  max_count                   = 1
  vnet_subnet_id             = azurerm_subnet.aks-sn2.id  
}

### Actual Behavior

When this runs you will get the error  Error: `max_count` must be >= `min_count`

As you can see that they are equal so this should run.

When you set the same for the default node_pool in the azurerm_kubernetes_cluster this will work fine.

### Steps to Reproduce

In the azurerm_kubernetes_cluster_node_pool set min_count and max_count to teh same value 
1. `terraform apply`

### Important Factoids

I have looked through the code for azurerm_kubernetes_cluster_node_pool and see the following on lines 354 to line 356 

		if minCount >= maxCount {
			return fmt.Errorf("`max_count` must be >= `min_count`")
		}

Where as if you view this in the code for the azurerm_kubernetes_cluster resource you will see 

                if minCount > maxCount {
			return nil, fmt.Errorf("`max_count` must be >= `min_count`")
		}

Hense it works for the default node pool.

### References

* #0000

**Comment by jackofallops** [comment]
Closing based on merge of 8957
