### ISSUE TITLE
Support for a datasource generating a login token for AAD-enabled postgresql server 

### ISSUE THREAD

**Issue by googol** [terraform-providers/terraform-provider-azurerm#8945]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Continuing my quest for enabling the AAD integration for my postgres servers (https://github.com/terraform-providers/terraform-provider-azurerm/issues/8291), I'd also like automate adding the AAD users to the database server with terraform, using something like the postgres provider.

To be able to add AAD users to postgres, you need to be logged in as the AAD admin (the normal admin user can't do this). To login via AAD, you need to fetch an access token. I can easily fetch the token with the az cli, but I'd like to automatically get the token with the credentials I'm using for the azurerm provider, regardless of whether it's the az cli session or a service principal or an MSI. To me it seems like a data source would be the simplest solution for this

I'd like to hear if this seems like a reasonable solution to you, or if you have some other solutions for this already. As a workaround I can use a provisioner script that uses `az account get-access-token`, but it is a bit clunky.

### New or Affected Resource(s)

* azurerm_access_token

Replicates the functionality of the `az account get-access-token` cli command. Takes as a parameter the resource type (for my purposes I'd use `oss-rdbms` to get a token for postgres). The authentication and subscription id would come from the provider.

### Potential Terraform Configuration

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West US"
}

resource "azurerm_postgresql_server" "example" {
  name                         = "example-psqlserver"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "9.6"
  administrator_login          = "4dm1n157r470r"
  administrator_login_password = "4-v3ry-53cr37-p455w0rd"
}

resource "azurerm_postgresql_active_directory_administrator" "example" {
  server_name         = azurerm_postgresql_server.example.name
  resource_group_name = azurerm_resource_group.example.name
  login               = "sqladmin"
  tenant_id           = data.azurerm_client_config.current.tenant_id
  object_id           = data.azurerm_client_config.current.object_id
}

data "azurerm_access_token" "example" {
  resource_type = "oss-rdbms"
}

provider "postgresql" {
  host            = azurerm_postgresql_server.example.fqdn
  port            = 5432
  database        = "postgres"
  username        = "sqladmin"
  password        = data.azurerm_access_token.example.access_token
  sslmode         = "require"
  connect_timeout = 15
}
```

### References

* https://docs.microsoft.com/en-us/azure/postgresql/howto-configure-sign-in-aad-authentication
*

**Comment by manicminer** [comment]
Hi @googol, thanks for requesting this. I don't believe this is a good fit for a data source in Terraform, since it's essentially a create operation (generating a token) and because these tokens expire quickly (between 5-60 minutes), would cause regular state churn anywhere it was used.

As you mention, scripting this via a provisioner might be your best option if you wish to pursue adding this (see the related issue https://github.com/terraform-providers/terraform-provider-azuread/issues/321 for other examples). However I'd suggest a native postgres account might be the simplest approach, although I understand you may have constraints that make this impossible.

It's unlikely this will be added as a data source, accordingly I'm going to close this issue, but please free to continue the discussion if you feel this is unwarranted.
