### ISSUE TITLE
azurerm_kubernetes_cluster: state not recorded in case of failure

### ISSUE THREAD

**Issue by jambt** [terraform-providers/terraform-provider-azurerm#895]
Hi,

I ran into a bug with the azurerm_kubernetes_cluster. The deployment state is not recorded properly in case of a failure.

### Terraform Version
Terraform v0.11.3
azurerm (1.1.2)

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_kubernetes_cluster

### Terraform Configuration Files
```hcl
resource "azurerm_kubernetes_cluster" "aks_container" {
  name = "${var.name}"
  location = "${var.location}"
  resource_group_name = "${var.resource_group}"
  kubernetes_version = "1.8.7"
  dns_prefix = "default"

  linux_profile {
    admin_username = "admin"
    ssh_key {
      key_data = "${file("~/.ssh/id_rsa.pub")}"
    }
  }

  agent_pool_profile {
    name = "agentpool"
    count = "${var.node_count}"
    vm_size = "${var.node_vm_size}"
    os_type = "Linux"
  }

  service_principal {
    client_id = "${var.client_id}"
    client_secret = "${var.client_secret}"
  }
}
```
Please note the usage of `admin` as admin_username. Thus, resource creation will fail as this default value is not valid.

### Expected Behavior
The resource should be marked as created, but `tainted`.

### Actual Behavior
The resource is not recorded as created.

### Steps to Reproduce
1. `terraform apply`
2. Change `admin_username` to something different
3. `terraform apply` will _not_ work, since the SDK tries to update the username which is not possible.

**Comment by katbyte** [comment]
Hello @jambt,

Thank you for finding and reporting this bug. 

You are correct, it appears that when `admin_username` is changed a new resource should be created. To fix this we will just have the property force a new resource when it changes.
