### ISSUE TITLE
Feature Request: azurerm_kubernetes_cluster: Make linux_profile optional

### ISSUE THREAD

**Issue by jambt** [terraform-providers/terraform-provider-azurerm#896]
Hi,

I ran into an inconsistency between required arguments of azurerm_kubernetes_cluster and the Azure CLI version created by that resource.

### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.2

### Affected Resource(s)
- azurerm_kubernetes_cluster

### Terraform Configuration Files
```hcl
resource "azurerm_kubernetes_cluster" "aks_container" {
  name = "${var.name}"
  location = "${var.location}"
  resource_group_name = "${var.resource_group}"
  kubernetes_version = "1.8.7"
  dns_prefix = "default"

  linux_profile {
    admin_username = "custom_admin"
    ssh_key {
      key_data = "${file("~/.ssh/id_rsa.pub")}"
    }
  }

  agent_pool_profile {
    name = "agentpool"
    count = "${var.node_count}"
    vm_size = "${var.node_vm_size}"
    os_type = "Linux"
  }

  service_principal {
    client_id = "${var.client_id}"
    client_secret = "${var.client_secret}"
  }
}
```

### Expected Behavior
Since `az aks create` can create a cluster without a linux_profile (admin username and key), I believe that this section should be optional.

### Actual Behavior
The linux_profile is required.

### Related (but different) problem:
By specifying an empty `admin_username` and `ssh_key` as an empty list, terraform *crashes* on apply. I can open a new ticket with detailed information, but am unsure which bug tracker is the right place. Advice would be welcome.

**Comment by katbyte** [comment]
Hello @jambt,

Thank you for the suggestion, but I don't believe we can make it optional at the moment. While the cli `az aks create` command works, if omitted in the go api the following error is returned:

`* azurerm_kubernetes_cluster.aks_container: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InternalOperationError" Message="An error has occurred in subscription c0a607b2-6372-4ef3-abdb-dbe52a7b56ba, resourceGroup: kt.20180227-akc2 request: missing Properties.LinuxProfile."`

As this seems to be a limitation in the API I am going to close this issue

I verified that an empty `admin_username` does not crash terraform, however an empty `ssh_key` does and that is a bug in the provider. It should be a separate issue in this repository however as I'm about to fix it I will create the issue myself.
