### ISSUE TITLE
Support for `azureFilesIdentityBasedAuthentication` and `routingPreference` in `storage_account`

### ISSUE THREAD

**Issue by yupwei68** [terraform-providers/terraform-provider-azurerm#8960]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for `azureFilesIdentityBasedAuthentication` and `routingPreference` in `storage_account`

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "test"{
  ...
  azure_files_identity_based_authentication{
  ...
  }
  .. 
  routing_preference{
  ...
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/storage/files/storage-files-active-directory-overview
* https://docs.microsoft.com/en-us/azure/virtual-network/routing-preference-overview

**Comment by tombuildsstuff** [comment]
@yupwei68 since this is waiting on API compatibility from the Service Team, I'm going to unmilestone this for now - please let us know when the Service Team have an update.
