### ISSUE TITLE
azurerm_storage_account doesn't handle `identity` property changes

### ISSUE THREAD

**Issue by tillig** [terraform-providers/terraform-provider-azurerm#8976]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.13.3
Azure provider 2.32.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.32.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">=3.0.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "location" {
  type    = string
  default = "westus2"
}

variable "name_base" {
  type    = string
  default = "idrepro"
}

locals {
  full_name = "${var.name_base}${random_string.suffix.result}"
}

resource "azurerm_resource_group" "repro" {
  name     = local.full_name
  location = var.location
}

resource "azurerm_storage_account" "repro" {
  name                     = local.full_name
  resource_group_name      = azurerm_resource_group.repro.name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  # identity {
  #   type = "SystemAssigned"
  # }
}

resource "random_string" "suffix" {
  length  = 8
  upper   = false
  lower   = true
  number  = true
  special = false
}

# output "principal_id" {
#   value = azurerm_storage_account.repro.identity.0.principal_id
# }
```

### Expected Behavior

The identity should have been established so an output could be determined. Ideally this would mean a resource modification rather than a full destroy/re-create cycle.

### Actual Behavior

```text
Error: Invalid index

  on repro.tf line 57, in output "principal_id":
  57:   value = azurerm_storage_account.repro.identity.0.principal_id
    |----------------
    | azurerm_storage_account.repro.identity is empty list of object

The given key does not identify an element in this collection value.
```

### Steps to Reproduce

1. `terraform apply` on the HCL. You should get a resource group with a storage account in it.
2. Uncomment the two commented sections - one to establish an `identity` with the storage account, one to output the principal ID from that identity.
3. `terraform apply` on the updated HCL.

### References

* #5663 - This issue is the same problem, just with `azurerm_function_app` rather than `azurerm_storage_account`. It's possible a similar fix could be applied to resolve this. That said, it was supposed to have been resolved for function apps in v1.44.0 and, based on the conversation in that issue, it wasn't actually resolved.

**Comment by tillig** [comment]
I tried doing a `terraform taint` on the storage account to force a destroy/apply to run but it seems outputs get calculated first (?) so you still get the same error even though after the destroy/apply the identity would be populated.

**Comment by tillig** [comment]
The only way I can work around it without having to totally destroy and re-create everything is to do a little .tfstate hackery. Obviously YMMV and all that, but here's what works for me.

```powershell
# Manually assign an identity and get the relevant info out.
$StorageAccountName = "mystorageaccountname"
$ResourceGroup = "resourcegroup"
az storage account update --assign-identity -n $StorageAccountName -g $ResourceGroup
az storage account show --query "identity" -n $StorageAccountName -g $ResourceGroup
```

Basically, assign an identity and then get the identity and tenant ID info out. You'll end up with a JSON block like this:

```json
```

**Comment by tombuildsstuff** [comment]
hey @tillig 

Thanks for opening this issue.

Taking a look through here this appears to be a bug in Terraform Core - and as such I'm going to close this in favour [of this issue which is tracking this bug](https://github.com/hashicorp/terraform/issues/25578) - would you mind subscribing to that issue for updates?

Thanks!
