### ISSUE TITLE
Adding support for Virtual Network Gateways

### ISSUE THREAD

**Issue by abhijeetgaiha** [terraform-providers/terraform-provider-azurerm#9]
### Terraform Version
0.9.7-dev

### Expected Behavior
The ability to configure Virtual Network Gateways from terraform

### References
https://docs.microsoft.com/en-us/rest/api/network/virtualnetworkgateways
https://docs.microsoft.com/en-us/azure/vpn-gateway/

**Comment by abhijeetgaiha** [comment]
I'm working on this.

**Comment by tombuildsstuff** [comment]
Just noticed this is a duplicate of #17 - as such I'm going to close this issue in favour of that one. Please feel free to re-open this if I've mis-understood and this isn't the case :)
