### ISSUE TITLE
azurerm_app_service transient error - "RepoUrl VSTSRM is not supported"

### ISSUE THREAD

**Issue by devedse** [terraform-providers/terraform-provider-azurerm#9005]
Original issue was closed in the middle of some discussions. This issue has not been solved as both me and multiple other people are still running into it.

Original issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8171

**Comment by tombuildsstuff** [comment]
@devedse since the original issue's been resolved for some people, can you please reopen this completing the issue template for your specific scenario and we'll take another look: https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Bug_Report.md

Thanks!

**Comment by devedse** [comment]
I would rather suggest to reopen the original issue, there's so much more details in there. Way more then I can ever provide here :)
