### ISSUE TITLE
Support for new-pod-scale-up for autoscaler profile on AKS

### ISSUE THREAD

**Issue by alk-rniveau** [terraform-providers/terraform-provider-azurerm#9008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The new hidden parameter for autoscaler profile new-pod-scale-up (https://github.com/Azure/AKS/issues/1716) is not yet supported by azurerm provider.

Do you plan to do it ?

### New or Affected Resource(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
 auto_scaler_profile = {
    balance_similar_node_groups      = false
    max_graceful_termination_sec     = 600
    scale_down_delay_after_add       = "10m"
    scale_down_delay_after_delete    = "10s"
    scale_down_delay_after_failure   = "3m"
    scan_interval                    = "10s"
    scale_down_unneeded              = "1m"
    scale_down_unready               = "20m"
    scale_down_utilization_threshold = "0.5"
    new_pod_scale_up                 = "5m"
  }
```

**Comment by dstrebel** [comment]
I can create a PR for this.

**Comment by tillepille** [comment]
@dstrebel @alk-rniveau 
It would be awesome if the `azurerm_kubernetes_cluster_node_pool` resource would support this as well!
