### ISSUE TITLE
VMSS properties enhancement 

### ISSUE THREAD

**Issue by djsly** [terraform-providers/terraform-provider-azurerm#901]
### Affected Resource(s)
- azurerm_virtual_machine_scale_set

https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html#id-1

it would be beneficial to augment the attribute reference list of the scale_set with the VM name and IPs to allow us to perform remote provisioner on them. 

We are currently migrating from Availability Set to ScaleSet (auto-scaling disabled) and want to still use our post-provisioning logic. 

From what I see, the azure-go-sdk allows us to fetch that information. https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetvms.go

Would you be open to augment the list of attributes? I'm looking on a general agreement before starting any PR work.

**Comment by tombuildsstuff** [comment]
hey @djsly 

Thanks for opening this issue :)

So we'd certainly be interested in exposing that information, presumably as a Computed List of some sort?

I have a separate question since I'm unfamiliar with the lifecycle of Failed instances within a VM Scale Set with auto scaling disabled: I'm wondering if it'd be better to use a VM Extension in this instance, since if a machine is recycled/replaced due to entering the Failed state then it'll come up without the Provisioner having run?

Thanks!

**Comment by djsly** [comment]
@tombuildsstuff great question indeed! I was thinking the same and my understanding is that the VMSS will return once all of the initial VM count is populated. 

The computed list of VM info should be the same size of the requested scale count. To scale up the number of VM, terraform would still be the source of truth, therefore, on the next `apply` the ScaleSet size would increase and the computed list be updated to reflect the new addition. 

In case a VM fails, it will be recreated using the same OS/Data Disk, therefore the pre-provisioning stage would still be intact. To be honest, I'm not a big fan or remote-provisioner with ScaleSet... I think that leveraging `cloud-init` is the best mechanisms for this use case once you start using the auto-scaling feature. 

Regarding the expected PR:

as a first stage, I would like to see a computed list of VMs with their IP and status being exposes as ScaleSet properties. I'm sure that there are a lot more nuts and bolt we could add to enhance the VMSS, but I'm aiming for a minimal first iteration :)

**Comment by bpoland** [comment]
If you are intending to manage the lifecycle with terraform, why use a scale set at all?  Certainly if you start using auto-scaling, you wouldn't want to use terraform provisioners or any other per-VM actions would you?

I don't believe the Azure scale set auto-recreates failed VMs.  And depending on the failure I don't think you can guarantee that the OS/data disks would be preserved.

**Comment by djsly** [comment]
We are migrating from AS to VMSS in intermediate steps. 
The Auto-scaler feature we will be using will come from Kubernetes. (1.10 as alpha support for both VMSS and Cluster AutoScaler). SO we will not rely on the Azure autoscaler feature.

We need to migrate from AS to VMSS to start providing feedback to the kubernetes community. Before we migrate our post install logic from cloud-init and immutable images we will stick to what we have and is working best (remote-provisioner)

Regarding 

> I don't believe the Azure scale set auto-recreates failed VMs

What makes you believe that ?

**Comment by bpoland** [comment]
Ah ok, interesting.  From what I have seen the creation of the scale set does not wait for the instances to finish creating, so there may be a timing issue there to pick up the IPs of the instances.  But if you think you can get it working, I can see the benefit if you're moving from AS to VMSS (although it might not be that hard to rewrite provisioners in cloud-init).  In my project we started with VMSS and ended up just using cloud-init from the start.

As a point of reference, I took a quick look at the AWS terraform provider and how it handles auto scaling groups -- it doesn't seem to return a list of VMs and allow running provisioners on them.

Regarding the auto-recreate -- when we were initially looking at scale sets we were hoping it would do that.  But so far I have not found any documentation or evidence that it does so.  And it's not easy to cause a failure to see for ourselves :)

If you have found anything that indicates auto-recovery on errors, I would be interested to see it!

**Comment by djsly** [comment]
Cool, It is still an explored territory for me as well. So you best guess might be right and I might have the same hope as you initially did ! :)

I might look at moving everything to cloud-init but right now, the retry on failures support with cloud-init isn't great and almost inexistent...

**Comment by bpoland** [comment]
Yeah cloud-init can definitely be a pain sometimes.

**Comment by djsly** [comment]
Closing since the work was refused even though initially it was accepted.
