### ISSUE TITLE
Support for setting FirewallPolicy ID in ApplicationGateway PathRules

### ISSUE THREAD

**Issue by toopricey** [terraform-providers/terraform-provider-azurerm#9040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Azure Terraform provider does not support setting the `firewallPolicy` field in `PathRule` objects, see https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/per-site-policies#apply-a-per-uri-policy-preview and https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2020-05-01/applicationgateways.  

### New or Affected Resource(s)

* azurerm_network

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  url_path_map {
    name = "example-name"
    path_rule {
       name = "example-rule"
       paths = ["/foo/bar"]
       firewall_policy = some_waf_policy.id
    }
  }
}
```

### References

* #0000

**Comment by SureshGoli123** [comment]
+1 experiencing problems with global WAF for exclusions.
