### ISSUE TITLE
Import azurerm_virtual_desktop_workspace_application_group_association fails with error

### ISSUE THREAD

**Issue by mrgeoffrich** [terraform-providers/terraform-provider-azurerm#9046]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.13.5
AzureRM: 2.33.0

### Affected Resource(s)

* azurerm_virtual_desktop_workspace_application_group_association

### Expected Behavior

Resource should import.

### Actual Behavior

The following message was displayed:

`Error: Error parsing Resource ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.DesktopVirtualization/workspaces/workspace-name|/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.DesktopVirtualization/applicationgroups/application-group-name": ID contained more segments than required: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.DesktopVirtualization/workspaces/workspace-name|/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.DesktopVirtualization/applicationgroups/application-group-name", map[applicationgroups:application-group-name subscriptions:00000000-0000-0000-0000-000000000000]`

### Steps to Reproduce

1. `terraform import azurerm_virtual_desktop_workspace_application_group_association.association "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.DesktopVirtualization/workspaces/workspace-name|/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.DesktopVirtualization/applicationgroups/application-group-name"`

**Comment by tombuildsstuff** [comment]
Fixed via #9057
