### ISSUE TITLE
MissingParameterOnPrivateLinkServiceConnection error when adding private endpoint for key vault

### ISSUE THREAD

**Issue by doherty100** [terraform-providers/terraform-provider-azurerm#9058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.33.0
+ provider registry.terraform.io/hashicorp/random v2.3.1

### Affected Resource(s)

* `azurerm_private_endpoint`
* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "key_vault_01" {
  name                            = "kv-${random_id.random_id_key_vault_01_name.hex}-001"
  location                        = azurerm_resource_group.resource_group_01.location
  resource_group_name             = azurerm_resource_group.resource_group_01.name
  tenant_id                       = var.aad_tenant_id
  sku_name                        = var.key_vault_sku_name
  tags                            = var.tags
  enabled_for_deployment          = true
  enabled_for_disk_encryption     = true
  enabled_for_template_deployment = true
}
resource "azurerm_private_endpoint" "key_vault_01_private_endpoint" {
  name                = "pend-${random_id.random_id_key_vault_01_name.hex}-003"
  resource_group_name = azurerm_resource_group.resource_group_01.name
  location            = azurerm_resource_group.resource_group_01.location
  subnet_id           = azurerm_subnet.vnet_hub_01_subnets["private_endpoints"].id
  tags                = var.tags

  private_service_connection {
    name                           = "keyvault"
    private_connection_resource_id = azurerm_key_vault.key_vault_01.id
    is_manual_connection           = false
  }
}

```

### Debug Output

[terraform.tfstate.backup](https://gist.github.com/doherty100/0d353e209658028fd3ea64903c6c5713)
### Panic Output

N/A

### Expected Behavior

Apply operation should provision new azurerm_private_endpoint resource without errors. 

### Actual Behavior

```
Error: creating Private Endpoint "pend-1eb0156cd527cd1a-003" (Resource Group "rg-vdc-nonprod-001"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingParameterOnPrivateLinkServiceConnection" Message="Private link service connection /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-vdc-nonprod-001/providers/Microsoft.Network/privateEndpoints/pend-1eb0156cd527cd1a-003/privateLinkServiceConnections/keyvault is missing required parameter 'group Id'." Details=[]

  on 50-keyvault.tf line 54, in resource "azurerm_private_endpoint" "key_vault_01_private_endpoint":
  54: resource "azurerm_private_endpoint" "key_vault_01_private_endpoint" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Keyvault support for private link / private endpoint is generally available.

### References

* [Integrate Key Vault with Azure Private Link](https://docs.microsoft.com/en-us/azure/key-vault/general/private-link-service)

**Comment by njuCZ** [comment]
@doherty100, you could try following script to create key vault private endpoint connection
```
resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet"
  resource_group_name = azurerm_resource_goup.test.name
  location            = azurerm_resource_goup.test.location
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "acctestsubnet"
  resource_group_name  = azurerm_resource_goup.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.0.0/24"]

  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctest-privatelink"
  resource_group_name = azurerm_resource_goup.test.name
  location            = azurerm_resource_goup.test.location
  subnet_id           = azurerm_subnet.test.id

  private_service_connection {
    name                           = "acctest-privatelink"
    is_manual_connection           = false
    private_connection_resource_id = azurerm_key_vault.test.id
    subresource_names = ["vault"]
  }
}
```

**Comment by doherty100** [comment]
@njuCZ no dice, now I'm getting this error:

Error: creating Private Endpoint "pend-78c531fb1a726040-001" (Resource Group "rg-vdc-nonprod-001"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidValuesForRequestParameters" Message="Call to Microsoft.Storage/storageAccounts failed. Error message: Values for request parameters are invalid: GroupId: vault." Details=[]

  on 50-keyvault.tf line 54, in resource "azurerm_private_endpoint" "key_vault_01_private_endpoint_vault":
  54: resource "azurerm_private_endpoint" "key_vault_01_private_endpoint_vault" {

**Comment by doherty100** [comment]
@njuCZ that did the trick thanks! Note that docs at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#subresource_names are out of date and missing the value "vault".
