### ISSUE TITLE
Terraform using unsupported api (2020-07-01-preview)

### ISSUE THREAD

**Issue by attackmode** [terraform-providers/terraform-provider-azurerm#9059]
Having issues with deploying Wowza streaming engine into Azure. Terraform fails with an error message saying that the image is not available from Azure Marketplace. I've logged a ticket with Azure and they have confirmed that Terraform is using an outdated api; 2020-07-01-preview.

`##[error]Terraform command 'apply' failed with exit code '1'.:  creating Linux Virtual Machine "my-vm1" (Resource Group "my-rg"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'Offer with PublisherId: 'wowza', OfferId: 'wowzastreamingengine' cannot be purchased due to validation errors. For more information see details. Correlation Id: '4bc76640-e86f-418c-b669-7475b991d9d5' Offer with PublisherId: 'wowza' and OfferId: 'wowzastreamingengine' was removed from the marketplace for new purchase. See similar offers here 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps?page=1%2526search=wowza%2520wowzastreamingengine'. Correlation Id '524b0687-8909-8e77-3747-6743d28f7d12'.'" |  creating Linux Virtual Machine "my-vm2" (Resource Group "my-rg"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'Offer with PublisherId: 'wowza', OfferId: 'wowzastreamingengine' cannot be purchased due to validation errors. For more information see details. Correlation Id: 'b69104ef-4ea8-4ff9-bc89-3a869614184e' Offer with PublisherId: 'wowza' and OfferId: 'wowzastreamingengine' was removed from the marketplace for new purchase. See similar offers here '
`

The image is available from the marketplace and I have tested:
`az vm image show --location uksouth --urn wowza:wowzastreamingengine:linux-paid:4.8.5`

Terraform version being used:
`/usr/local/bin/terraform version
Terraform v0.13.4
`

**Comment by tombuildsstuff** [comment]
hi @attackmode 

Taking a look at the error being returned from the Azure API here:

> Offer with PublisherId: 'wowza' and OfferId: 'wowzastreamingengine' was removed from the marketplace for new purchase.

This image (offer) is no longer available for use at this version - whilst it can be looked up/queried, it can't be provisioned. I'm unfamiliar with this image, but it's possible there's a newer version of this image which should be used instead, you can try setting the version to `latest`, or confirm the new version in the Azure Portal/CLI.

Since this is a usage question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but unfortunately this error is coming from Azure where this image version is no longer available, so if your unable to determine this I'd recommend reaching out to Azure support here.

Thanks!

**Comment by attackmode** [comment]
@tombuildsstuff as I said Azure have looked at the issue and have confirmed the reason is due to Terraform using an out of date api version. If the image doesn't exist the result would be null, and 4.8.5 is the latest version.

**Comment by tombuildsstuff** [comment]
@attackmode we're not using that API version anywhere in this codebase:

```
$ grep -R "2020-07-01-preview" ./vendor/github.com/Azure/azure-sdk-for-go/

```

> If the image doesn't exist the result would be null, and 4.8.5 is the latest version

The image does exist, but it's not available for new purchases - so will be returned; in this instance you'd likely need to reach out to the vendor publishing the image, unfortunately this isn't an error with Terraform based on the error message above.

**Comment by attackmode** [comment]
@tombuildsstuff Thanks so much for confirming! Yeh it's as I thought but it really difficult as Im in the middle. I really appreciate your help 👍
