### ISSUE TITLE
azurerm_key_vault_secret values that are put in azurerm_function_app app_settings blocks are not sensitive

### ISSUE THREAD

**Issue by romeomorcia** [terraform-providers/terraform-provider-azurerm#9071]
### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.0-beta2
+ provider registry.terraform.io/hashicorp/azurerm v2.33.0
```

### Affected Resource(s)
```
azurerm_key_vault_secret
azurerm_function_app
```

### Question

Hello everyone, i've been struggling in the last period in keeping secured the output of sensitive values during the editing of resources.
With version 0.14.0-beta2 I've enabled an experiment to the terraform configuration which allows me to hide sensitive values from the output console while modifying another resource.
For instance if I have a sensitive value and I add it to the app settings of my function app, when I will run terraform apply I will have in the output the information that the new config has been added and the value is (sensitive).
![image](https://user-images.githubusercontent.com/56087756/97546275-81678500-19cc-11eb-84ed-575ff6b832e0.png)
But the same doesn't happen when I add the value of a keyvault secret. In fact, the values in the terminal are shown without issues and this is a security issue that I cannot afford to have in my solution.

A link to the requested feature to hide values as sensitive is here below:
https://github.com/hashicorp/terraform/issues/26625

My question is: Is it normal that when we create these key vault secrets, the terminal shows that the value is "secret" but when we modify these values and add them as configuration, they're visible in the output?
Shouldn't be those `sensitive` too? Thanks!

PS: code of the sensitive variable is here:
```
variable "sensitiveString" {
  type = string
  default = "thisIsNothing"
  sensitive = true
}
```
The key_vault_secret resource instead is like every other key vault secrets but the value comes from another resource:

```
resource "azurerm_key_vault_secret" "test_secret" {
  name  = "keyvault_secret_name"
  value = azurerm_application_insights.appins.connection_string
  key_vault_id = data.azurerm_key_vault.keyvault.id
  content_type = azurerm_application_insights.appins.id
}
```

**Comment by tombuildsstuff** [comment]
hey @romeomorcia 

Thanks for opening this issue.

Unfortunately this appears to be a bug in the 0.14 beta - rather than directly related to the Azure Provider - since [you've reopened the parent issue with this comment](https://github.com/hashicorp/terraform/issues/26625#issuecomment-718474566) I'm going to close this issue in favour of that one, would you mind following up there instead where the Core team should be able to take a look?

Thanks!
