### ISSUE TITLE
azurerm_route fails when re-indexing

### ISSUE THREAD

**Issue by tormodsrbank** [terraform-providers/terraform-provider-azurerm#9072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.33.0

### Affected Resource(s)

* `azurerm_route`

### Terraform Configuration Files

main.tf
```hcl
variable "routes" {
  type = list(object({
    name           = string
    address_prefix = string
    next_hop_type  = string
  }))
  default = []
}

resource "azurerm_resource_group" "rg" {
  name     = "testRG"
  location = "West Europe"
}

resource "azurerm_route_table" "rt" {
  name                = "testRT"
  location            = "West Europe"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_route" "route" {
  count = length(var.routes)

  name                = var.routes[count.index].name
  resource_group_name = azurerm_resource_group.rg.name
  route_table_name    = azurerm_route_table.rt.name
  address_prefix      = var.routes[count.index].address_prefix
  next_hop_type       = var.routes[count.index].next_hop_type
}
```

test1.tfvars
```
routes = [
    {
      name           = "test1"
      address_prefix = "10.10.10.1/32"
      next_hop_type  = "None"
    },
    {
      name           = "test2"
      address_prefix = "10.10.10.2/32"
      next_hop_type  = "None"
    }
]
```

test2.tfvars (**Note: I have inserted a new route between the two previous one's**)
```
routes = [
    {
      name           = "test1"
      address_prefix = "10.10.10.1/32"
      next_hop_type  = "None"
    },
    {
      name           = "test3"
      address_prefix = "10.10.10.3/32"
      next_hop_type  = "None"
    },
    {
      name           = "test2"
      address_prefix = "10.10.10.2/32"
      next_hop_type  = "None"
    }
]
```

### Debug Output

Running first time:
https://gist.github.com/tormodsrbank/5d7f20e26688c330896269d22ab0d343

Running second time:
https://gist.github.com/tormodsrbank/a5af1572198f26632f951c45b1705154

### Expected Behavior

I expect the routes to be configured as per the input variable. The "plan" step shows the correct expected result, but it's not being applied correctly.

### Actual Behavior

What happens is that when applying the plan it starts deleting the route that should be replaced. Concurrently it starts adding the third route, which has the same name as the route it started to delete. This produces the error that the route already exists.
This needs to be handled somehow, possibly by waiting for deletes to finish before adding, or something even smarter?

### Steps to Reproduce

1. `terraform apply -var-file=test1.tfvars`
1. `terraform apply -var-file=test2.tfvars`

### References

* #0000

**Comment by magodo** [comment]
@tormodsrbank Thank you for submitting this!

The unexpected replacement on the existing route is caused by the fact that you are using `count`, in which case, each resource instance is identified by their index instead of the string values in the list. Once you changed the index (e.g. `test2` in this case), it will be regarded as a new instsance. To avoid that, we should use `for_each` instead (see [When to Use `for_each` Instead of `count`](https://www.terraform.io/docs/configuration/resources.html#when-to-use-for_each-instead-of-count) for details).

For this specific case, in order to using the `for_each`, you have to refine your declaration of the variable a bit, to make it to be a `map`:

```terraform
...
variable "routes" {
  type = map(object({
    address_prefix = string
    next_hop_type  = string
  }))
}
...
resource "azurerm_route" "route" {
  resource_group_name = azurerm_resource_group.rg.name
  route_table_name    = azurerm_route_table.rt.name

  #   count = length(var.routes)
  #   name                = var.routes[count.index].name
  #   address_prefix      = var.routes[count.index].address_prefix
  #   next_hop_type       = var.routes[count.index].next_hop_type

  for_each       = var.routes
  name           = each.key
  address_prefix = each.value.address_prefix
  next_hop_type  = each.value.next_hop_type
}
```

And the corresponding variables definition:

```terraform
routes = {
  "test1" : {
    address_prefix = "10.10.10.1/32"
    next_hop_type  = "None"
  },
  "test3" : {
    address_prefix = "10.10.10.3/32"
    next_hop_type  = "None"
  },
  "test2" : {
    address_prefix = "10.10.10.2/32"
    next_hop_type  = "None"
  }
}

```

**Comment by tormodsrbank** [comment]
Ooops.. my bad. Sounds totally reasonable.

Thank you for the suggestion, I will test it and report back.

**Comment by tormodsrbank** [comment]
Refactored my modules now, and it seems to work great. Again, thank you.
