### ISSUE TITLE
Feature Request: Cognitive Service Account support

### ISSUE THREAD

**Issue by Nepomuceno** [terraform-providers/terraform-provider-azurerm#908]
Hi there,

There is no support for azure [cognitive service Accounts](https://azure.microsoft.com/en-us/services/cognitive-services/) there is support for it on the [Go SDK](https://github.com/Azure/azure-sdk-for-go/tree/master/services/cognitiveservices) docs for the usage [here](https://docs.microsoft.com/en-gb/azure/#pivot=products&panel=ai)

### Affected Resource(s)

- cognitive_account

**Comment by tombuildsstuff** [comment]
I've assigned @Nepomuceno since he's looking into/adding support for this
