### ISSUE TITLE
Add support for outbound_ports configuration in azurerm_lb_outbound_rule resource

### ISSUE THREAD

**Issue by skunevich** [terraform-providers/terraform-provider-azurerm#9080]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have a public ip prefix assigned to a frontend_ip_configuration for an azurerm_lb with 4 public ips.  When we create an azurerm_lb_outbound_rule there is no option to configure the port allocation in terraform and the default is configured.  We would like to be able to manually choose the number of ports per instance.

The cli supports updating it with the following command
```sh
az network lb outbound-rule update --lb-name MyLB --name MyOutboundRule --outbound-ports 2000 --resource-group MyRG1
```
### New or Affected Resource(s)

* azurerm_lb_outbound_rule

### Potential Terraform Configuration

```hcl
resource "azurerm_lb_outbound_rule" "my_lb_outbound_rule" {
  resource_group_name            = var.resource_group_name
  loadbalancer_id                = azurerm_lb.my_lb.id
  name                           = "my-tcp-lb-rule"
  protocol                       = "Tcp"
  enable_tcp_reset               = true
  backend_address_pool_id        = azurerm_lb_backend_address_pool.my_backend_address_pool.id

  frontend_ip_configuration {
    name = "my-ip-config"
  }

  port_allocation_configuration {
    choose_by: ports_per_instance/max_backend_instances
    outbound_ports_allocated: 2000
  }
}
```
port_allocation_configuration would be optional.  outbound_ports_allocated would be optional unless ports_per_instance is selected for choose_by.

**Comment by magodo** [comment]
Hello @skunevich Are you looking for [`allocated_outbound_ports`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_outbound_rule#allocated_outbound_ports)?

**Comment by skunevich** [comment]
That is exactly what I was looking for, sorry I missed it in the documentation.
