### ISSUE TITLE
r/monitor_diagnostic_setting: missing validation on the name field

### ISSUE THREAD

**Issue by Flaniga3** [terraform-providers/terraform-provider-azurerm#9083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version: 0.12.20
AzureRM Version: 2.33.0

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

Data Sources:
```hcl
data "azurerm_resources" "key_vault_resources" {
  type = "Microsoft.KeyVault/vaults"
}

data "azurerm_resources" "database_resources" {
  type = "Microsoft.Sql/servers/databases"
}
```

Diagnostic Settings Resources:
```hcl
# Log Analytics metrics for Key Vaults
resource "azurerm_monitor_diagnostic_setting" "key_vault_diagnostic_settings_la" {
  for_each                   = toset(data.azurerm_resources.key_vault_resources.resources.*.id)
  name                       = each.value
  target_resource_id         = each.value
  log_analytics_workspace_id = <REDACTED>

  log {
    category = "AuditEvent"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = true
      days    = 30
    }
  }
}

# Log Analytics metrics for Azure SQL databases
resource "azurerm_monitor_diagnostic_setting" "database_diagnostic_settings_la" {
  for_each                   = toset(data.azurerm_resources.database_resources.resources.*.id)
  name                       = each.value
  target_resource_id         = each.value
  log_analytics_workspace_id =<REDACTED>

  log {
    category = "SQLInsights"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "AutomaticTuning"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "QueryStoreRuntimeStatistics"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "QueryStoreWaitStatistics"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "Errors"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "DatabaseWaitStatistics"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "Timeouts"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "Blocks"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  log {
    category = "Deadlocks"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  metric {
    category = "Basic"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  metric {
    category = "InstanceAndAppAdvanced"

    retention_policy {
      enabled = true
      days    = 30
    }
  }

  metric {
    category = "WorkloadManagement"

    retention_policy {
      enabled = true
      days    = 30
    }
  }
}
```

### Debug Output

https://gist.github.com/Flaniga3/15d7ff017aca0b3d4cd4896dfb872a31

Repeat for every resource imported.

### Panic Output

N/A

### Expected Behavior

Terraform should have created the diagnostic settings according to the plan output and configuration.

### Actual Behavior

Plan succeeds, showing the exact output expected. Apply fails with a code 400 and the above output. It should be noted that this has been attempted using the "azurerm_key_vault" and "azurerm_sql_database" resources directly, passing the IDs of these to the diagnostic_setting resource. This demonstrates to me that our IDs are correct, at the very least, but this configuration produces the same error. We have many Terraform configurations in many repositories and many separate pipelines. We're trying to perform a broad sweep of our entire subscription to enforce compliance.

### Steps to Reproduce

Create a Key Vault, Azure SQL Server and Database, and Log Analytics account in a single subscription, and run Terraform plan and apply with a configuration similar to the above.

### Important Factoids

None.

### References

None.

**Comment by tombuildsstuff** [comment]
hey @Flaniga3 

Thanks for opening this issue.

The error from the Azure API here is coming from the fact that the Resource ID is being used as the name in the configuration above - whilst it's unfortunate that Terraform doesn't catch this with it's validation (which is why I've tagged this as a bug so that we can fix this issue) - I believe that should fix this for you in the interim. Would you be able to take a look and see if that works for you?

Thanks!

**Comment by Flaniga3** [comment]
I was mostly just trying to provide something unique, while simultaneously being really lazy. We're still in an experimental phase with this particular configuration. It does, in fact, look like that was the issue. Thanks for your help!

**Comment by tombuildsstuff** [comment]
@Flaniga3 glad to hear this is working for you - we'll leave this bug open until the validation is fixed either way 👍
