### ISSUE TITLE
Log Analytics Solution Failing to Create

### ISSUE THREAD

**Issue by tbayer1995** [terraform-providers/terraform-provider-azurerm#9092]
Hi there,

I'm trying to create  a log analytics solution as part of a module by referencing a log analytics workspace via a data block. When trying to apply the changes, Terraform is returning the following error:

`Error: Error creating/updating Log Analytics Solution "ContainerInsights(<our_LAW>)" (Workspace "/subscriptions/<our subscription>/resourcegroups/<our_RG>/providers/microsoft.operationalinsights/workspaces/<our_LAW>" / Resource Group "<our RG>"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'W' looking for beginning of value

  on ../../modules/aks/main.tf line 41, in resource "azurerm_log_analytics_solution" "logs":
  41: resource "azurerm_log_analytics_solution" "logs" {
`

This is a new error to us. Previously, we were creating a log analytics workspace as apart of this module as well, but recently we moved to a centralized LAW, and now just need to reference the pre-created LAW. Before making this update to the code, the Log Analytics Solution was created successfully. 

Additionally, the log analytics solution we are requesting to be created is being created in Azure, but Terraform will not update the state to reflect this resource being created. 

Below is the code that is being used as part of a larger module: 

```hcl
data "azurerm_log_analytics_workspace" "aks_law"{
  name=var.log_analytics_name
  resource_group_name = var.lawRGName
}


resource "azurerm_log_analytics_solution" "logs" {
 solution_name                 = "ContainerInsights"
 location                      = var.location
 resource_group_name           = var.resource_group
 workspace_resource_id         = data.azurerm_log_analytics_workspace.aks_law.id
 workspace_name                = var.log_analytics_name

 plan {
   publisher                   = "Microsoft"
   product                     = "OMSGallery/ContainerInsights"
 }
}
```

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested with below tfconfig, I can repro this issue. After checked, seems "log analytics workspace" and "log analytics solution" cannot be in the different "resource group". Could you have a check whether your "log analytics workspace" and "log analytics solution" are in the different "resource group"?

The tfconfig which repros this issue:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-las-test01"
  location = "eastus2"
}

resource "azurerm_resource_group" "test2" {
  name     = "acctestRG-las-test02"
  location = "eastus2"
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "acctestLAW-test011111"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
}

resource "azurerm_log_analytics_solution" "test" {
  solution_name         = "ContainerInsights"
  location              = azurerm_resource_group.test2.location
  resource_group_name   = azurerm_resource_group.test2.name
  workspace_resource_id = azurerm_log_analytics_workspace.test.id
  workspace_name        = azurerm_log_analytics_workspace.test.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}
```

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back from you here I'm going to close this issue for the moment - but if your able to reply to the above comment then we can take another look.

Thanks!
