### ISSUE TITLE
Request support for Storage Account Private Endpoint

### ISSUE THREAD

**Issue by ryan-peterson3** [terraform-providers/terraform-provider-azurerm#9093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable to configure Private Endpoint on Azure Storage Accounts.  This would allow the Storage Account to be configured with a private IP address.

### New or Affected Resource(s)

Resource: Storage Account
Settings: Private endpoint connections

* azurerm_storage_account

**Comment by tombuildsstuff** [comment]
hi @ryan-peterson3 

Thanks for opening this issue.

Support for this is available via the `azurerm_private_endpoint` resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint - would you be able to take a look and see if that works for you?

Since I believe this resource is already available I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by ryan-peterson3** [comment]
Thank you for showing this to me as I did not see it.  Will check it out.

**Comment by ryan-peterson3** [comment]
@tombuildsstuff Hey Tom, what am I missing here?  Documentation https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint says "subresource_names" is optional, but I'm getting an error without it.

Terraform Validate & Plan both pass the initial error check, but when it runs it errors out:
module.file_share.azurerm_private_endpoint.this: Creating...

Error: creating Private Endpoint "pe-ait-ryan-test" (Resource Group "ryan-test-files"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingParameterOnPrivateLinkServiceConnection" Message="Private link service connection /subscriptions/c1f6ce30-b729-44dc-adb9-1985a0d0cfd2/resourceGroups/ryan-test-files/providers/Microsoft.Network/privateEndpoints/pe-ait-ryan-test/privateLinkServiceConnections/pe-ait-ryan-test is missing required parameter 'group Id'." Details=[]

So then I attempt to add "subresource_names" but I can't tell what the syntax is:
[code]
resource "azurerm_private_endpoint" "this" {
  name                = var.private_endpoint
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  subnet_id           = data.azurerm_subnet.this.id
  tags                = var.tags

  private_service_connection {
    name                           = var.private_endpoint
    private_connection_resource_id = azurerm_storage_account.this.id
    is_manual_connection           = false
    subresource_names              = file
  }
[/code]


Getting an error:
Error: Invalid reference

  on ..\..\Bitbucket\terraform-azure-files-module\main.tf line 139, in resource "azurerm_private_endpoint" "this":
 139:     subresource_names              = file

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.

I think I'm close to getting this to work.  Appreciate any help!

**Comment by ryan-peterson3** [comment]
@tombuildsstuff Nevermind!  I found an example over here I was able to copy: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/private-endpoint/postgresql/main.tf

Hurray it works!  You guys rock!
