### ISSUE TITLE
set ddos_protection_plan in Azurerm_virtual_network to null

### ISSUE THREAD

**Issue by sysadmin-exe** [terraform-providers/terraform-provider-azurerm#9113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Trying to Automate creation of DDOS plan using bool and if set to false (meaning DDOS will not be created) the azurerm_virtual_network requests ddos_protection_plan to have a value. 

### New or Affected Resource(s)

#creating DDOS if enabled on vnet
resource "azurerm_network_ddos_protection_plan" "main_ddos" {
  count               = var.create_ddos_plan ? 1:0
  name                = "${var.resource_prefix}_ddos"
  location            = var.region
  resource_group_name = azurerm_resource_group.main.name
}

#creating Vnet with its address space, name, region, resource group and subnets
resource "azurerm_virtual_network" "main_vnet" {
  name                = var.vnet_name
  location            = var.region
  resource_group_name = azurerm_resource_group.main.name
  address_space       = var.vnet_address_space
  dns_servers         = var.vnet_dns_servers

#tried to use this to add a condition that will enable DDOS to the vnet if it was created but could not work
#because id here cannot be null if a ddos is not created
  ddos_protection_plan {
    id                = var.create_ddos_plan == true ? azurerm_network_ddos_protection_plan.main_ddos[0].id:null
    enable            = var.create_ddos_plan 
  }
-------
so can we have it set to null when variable is like so  >>>
variable "create_ddos_plan" {
  description = "If set to true, create DDOS plan for vnet"
  type        = bool
}

* #0000

**Comment by magodo** [comment]
@sysadmin-exe Thank you for submitting this!

One solution is to use the [`dynamic block`](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) as below:

```hcl
provider "azurerm" {
  features {}
}

variable "create_ddos_plan" {
  description = "If set to true, create DDOS plan for vnet"
  type = bool
}

resource "azurerm_resource_group" "main" {
  name = "vnetddos-rg"
  location = "west us2"
}

#creating DDOS if enabled on vnet
resource "azurerm_network_ddos_protection_plan" "main_ddos" {
  count = var.create_ddos_plan ? 1:0
  name = "ddos_protection_plan"
  location = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_virtual_network" "main_vnet" {
  name = "vnet1"
  location = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space = ["10.0.0.0/16"]

  dynamic "ddos_protection_plan" {
    for_each = var.create_ddos_plan == true ? range(1):range(0)
    iterator = v
    content {
      id = azurerm_network_ddos_protection_plan.main_ddos[0].id
      enable = true
    }
  }
}
```

Although it could work on the first provision, but it can't work when, e.g., changing from enabled to disabled. In which case, it requires an update in the vnet and a destroy for the ddos protection plan, in the specific order. To keep the order, we have to introduce the dependency between them and adding the [`create_before_destroy`](https://www.terraform.io/docs/configuration/resources.html#create_before_destroy) lifecycle annotation for vnet. However, as the dependency between these two resources are introduced conditionally, it seems CBD cannot work in this case. For this, I have submit an issue to core team: hashicorp/terraform#26775. Once it is addressed, you shall be able to toggle it with no problem.

**Comment by sysadmin-exe** [comment]
Thanks @magodo,
This works like magic. I actually thought using null would work but this is brilliant!!
