### ISSUE TITLE
Azure mess up deployment for multiple subscriptions

### ISSUE THREAD

**Issue by timtsoit-crypto** [terraform-providers/terraform-provider-azurerm#9115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version:  v0.13.5
AzureRM Version: v2.34.0

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  alias = "test"

  tenant_id       = "xxxxx"
  subscription_id = "xxxxx1"

  features {}
}

provider "azurerm" {
  alias = "prod"

  tenant_id       = "xxxxx"
  subscription_id = "xxxxx2"

  features {}
}

provider "azurerm" {
  alias = "staging"

  tenant_id       = "xxxxx"
  subscription_id = "xxxxx3"

  features {}
}

module "test" {
  source = "module/module1"
  providers = {
    azurerm = azurerm.test
  }

  var = value
}

module "prod" {
  source = "module/module1"
  providers = {
    azurerm = azurerm.prod
  }

   var = value
}

module "staging" {
  source = "module/module1"
  providers = {
    azurerm = azurerm.staging
  }

   var = value
}

```

### Expected Behavior

It won't show adding resource which the resources has already existed.
It won't show changing resources which indeed no change at all.

### Actual Behavior

Even the created resources already inside the state file, when I click apply again without any code changes. It always show there are resources will be added or there are resources will be changed. And every time the number of resource adding and resource changing is varying.

### Steps to Reproduce

az login
terraform apply

### Important Factoids
My account has linked with multiple subscriptions with contributor role
### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @timtsoit-crypto 

Thanks for opening this issue.

Taking a look through here this appears to be a bug in the Azure CLI when requesting multiple tokens in parallel, manifesting when multiple instances of the Azure Provider request a token simultaneously. There's an issue open tracking this in the form of https://github.com/terraform-providers/terraform-provider-azurerm/issues/5702, which (rather than having multiple issues open tracking the same thing) I'm going to close this in favour of - would you mind subscribing to this for updates?

Thanks!
