### ISSUE TITLE
Getting error azurerm_network_interface.mynic is tuple with 2 elements while destroying the resources (private ip's)

### ISSUE THREAD

**Issue by radhakrishnamca10** [terraform-providers/terraform-provider-azurerm#9116]
Hi ,
can anyone help me quikely, below is what i followed , getting the issue while running terraform destroy for private ips only, 
 but working fine for public ips. 

Step1: This is my code for multiple Vms spin up in azure. Able to spin up two vms with below code. 

# Create Network Interface 
resource "azurerm_network_interface" "mynic" {
  count               = "${var.vmcount}"
  name                = "${var.myvmname}-mynic${count.index+1}"
  location            = "Southeast Asia"
  resource_group_name = "Azure_DevOps_RapidOps"

 

  ip_configuration {
      name                          = "myNicConfig"
      subnet_id                     = "${data.azurerm_subnet.myterraformsubnet.id}"
      private_ip_address_allocation = "Dynamic"
#      public_ip_address_id          = azurerm_public_ip.mytfpublicip.id
      public_ip_address_id          = element(azurerm_public_ip.mytfpublicip.*.id, count.index)
    }
     tags = {
        environment = "Terraform Demo"
       }
  }

 

# Output section for private Ip with Vm names.

 

output "vm_name_and_private_ip_address" {
 value = "${formatlist(
    "%s_privateip = %s",
    (data.azurerm_virtual_machine.mytfvm.*.name),
    (azurerm_network_interface.mynic.*.private_ip_address)
  )}"

 

}

 

## After apply getting below success

 

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

 

Outputs:

 

azurerm_network_interface = [
  "172.17.14.23",
  "172.17.14.22",
]
public_ip_address = [
  "52.187.191.19",
  "52.187.191.12",
]
vm_name_and_private_ip_address = [
  "dev-vm1_privateip = 172.17.14.23",
  "dev-vm2_privateip = 172.17.14.22",
]
vm_name_and_public_ip_address = [
  "dev-vm1_publicip=52.187.191.19",
  "dev-vm2_publicip=52.187.191.12",
]

 

while destroying the managed infrastructure getting below error.

 

[devopsadmin@elasticsearch dev-vm1]$ sudo terraform destroy -var="vmsize=Standard_B1ms" -var="myvmname=dev-vm" -var="vmcount=2"
data.azurerm_subnet.myterraformsubnet: Refreshing state...
data.azurerm_resource_group.Azure_DevOps_RapidOps: Refreshing state...
data.azurerm_virtual_network.Azure_DevOps_RapidOps-vnet: Refreshing state...

 

Error: Invalid function argument

 

  on main.tf line 192, in output "vm_name_and_private_ip_address":
 189: 
 190: 
 191: 
 192:     (azurerm_network_interface.mynic.*.private_ip_address)
 193: 
    |----------------
    | azurerm_network_interface.mynic is tuple with 2 elements

 

Invalid value for "args" parameter: argument 2 has length 2, which is
inconsistent with argument 1 of length 0.

**Comment by tombuildsstuff** [comment]
hi @radhakrishnamca10 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by radhakrishnamca10** [comment]
sure thanks tom
