### ISSUE TITLE
EnableAnalyticalStorage capabilities not detected in resource azurerm_cosmosdb_account

### ISSUE THREAD

**Issue by Philippe-Padok** [terraform-providers/terraform-provider-azurerm#9119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When the EnableAnalyticalStorage capability is already added to your azurerm_cosmosdb_account. Terraform plan doesn't detect it and try to recreate the resource with the capability enabled during the plan.

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "acdb" {
  name                = local.resource_name
  location            = data.azurerm_resource_group.project_resource_group.location
  resource_group_name = data.azurerm_resource_group.project_resource_group.name
  offer_type          = var.acdb_offer_type
  kind                = var.acdb_kind
  ...

  capabilities {
    name = "EnableAnalyticalStorage"
  }

  ...

}
```

### Plan Output
```hcl
  + capabilities { # forces replacement
          + name = "EnableAnalyticalStorage"
      }
```
### Expected Behavior

Terraform plan should have detected the already activated capability

### Actual Behavior

Terraform want to recreate the complete resource to activate the capability

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The last update (2.34) give us control to enable the capability you can find the link to the PR below
https://github.com/terraform-providers/terraform-provider-azurerm/pull/9010

**Comment by DenWin** [comment]
If you output the result of the data source, does it also outputs the "EnableAnalyticalStorage" capability?

```
data"azurerm_cosmosdb_account" "acdb" {
  name                = local.resource_name
  location            = data.azurerm_resource_group.project_resource_group.location
}
```

Assumably as it is this new the return is not properly implemented.

**Comment by Philippe-Padok** [comment]
It is not declared in the list of capabilities either in the property during my plan.

In the ARM export in the portal, this capability is declared as a property and not in the capabilities list

**Comment by favoretti** [comment]
@Philippe-Padok I'm trying to look into this, but API gives me 
```
Error: Error creating CosmosDB Account "vlad-test-2" (Resource Group "vlad-test"): Error creating/updating CosmosDB Account "vlad-test-2" (Resource Group "vlad-test"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Invalid capability EnableAnalyticalStorage.\r\nActivityId: 00bb75d5-93a6-413e-ae33-5d10ce9c11b5, Microsoft.Azure.Documents.Common/2.11.0"
```

Did the creation snippet of terraform ever work for you? Cause as you say, it seems to be a property, hence I'm not sure how this could ever work at all..

**Comment by favoretti** [comment]
Nevermind, I see it now. Rewriting how it should be + a test.
