### ISSUE TITLE
Change SKU of [azurerm_databricks_workspace] without recreating the workspace.

### ISSUE THREAD

**Issue by w0ut0** [terraform-providers/terraform-provider-azurerm#9124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation describes that changing the Databricks SKU requires the resource to be created. However, the [Azure documentation](https://docs.microsoft.com/en-us/azure/databricks/administration-guide/account-settings/account#--upgrade-or-downgrade-an-azure-databricks-workspace) proposes a way to change the SKU without redeploying the workspace. According to the documentation, you can create a new deployment (with the same name/subscription/resource group), and change the SKU. This should not cause the deletion and recreation of the workspace.

### New or Affected Resource(s)

* azurerm_databricks_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_databricks_workspace" "example" {
  name                = "databricks-test"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "standard"

  tags = {
    Environment = "Production"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/databricks/administration-guide/account-settings/account#--upgrade-or-downgrade-an-azure-databricks-workspace

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated, seems the scenarios "trial->standard->premium" and "premium->standard" can directly update. Downgrading from "standard" to "trial" doesn't support to directly update, so which deserves "forceNew". So I submit a [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/9541)for this issue. Hopes it would be helpful.
