### ISSUE TITLE
Can't use "azurerm_kubernetes_cluster" with "depends_on"

### ISSUE THREAD

**Issue by philthynz** [terraform-providers/terraform-provider-azurerm#9132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.30.0

### Affected Resource(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

```
# Create aks cluster
# A new resource group will be auto created for node_resource_group
resource "azurerm_kubernetes_cluster" "aks" {
  name                            = "${var.RESOURCE_GRP_NAME}-AKS"
  location                        = var.LOCATION
  resource_group_name             = azurerm_resource_group.k8s_resource_grp.name
  dns_prefix                      = "${var.RESOURCE_GRP_NAME}-AKS"
  node_resource_group             = "${var.RESOURCE_GRP_NAME}-INF"
  kubernetes_version              = var.KUBERNETES.KubernetesVersion
  api_server_authorized_ip_ranges = var.KUBERNETES_ALLOWED_IP_RANGES
  tags                            = var.TAGS


  default_node_pool {
    name                = "default"
    type                = "VirtualMachineScaleSets"
    node_count          = var.KUBERNETES.NodeCount
    availability_zones  = var.KUBERNETES.AvailabilityZones
    vm_size             = var.KUBERNETES.NodeVmSize
    enable_auto_scaling = var.KUBERNETES.AutoScaleBool
    os_disk_size_gb     = var.KUBERNETES.OSDiskSize
    max_pods            = var.KUBERNETES.MaxPods
    node_labels         = var.KUBERNETES.Labels
    node_taints         = var.KUBERNETES.Taints
    min_count           = var.KUBERNETES.AutoScaleMinCount
    max_count           = var.KUBERNETES.AutoScaleMaxCount
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true

    azure_active_directory {
      managed = true
      admin_group_object_ids = var.KUBERNETES.AdminGroupObjectIds
    }
  }

  addon_profile {
    oms_agent {
      enabled = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.log_analytics_workspace.id
    }
    kube_dashboard {
      enabled = false
    }
    azure_policy {
      enabled = true
    }
  }

  network_profile {
    load_balancer_sku  = "standard"
    outbound_type      = "loadBalancer"
    network_plugin     = "azure"
    network_policy     = "azure"
    dns_service_ip     = "10.0.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
    service_cidr       = "10.0.0.0/16"
  }
}
```

```
resource "azurerm_virtual_network" "aks_vnet" {
    name                        = "vnet"
    location                    = var.LOCATION
    resource_group_name         = "${var.RESOURCE_GRP_NAME}-INF"
    address_space               = ["10.0.0.0/8"]
    tags                        = var.TAGS
    depends_on = [azurerm_kubernetes_cluster.aks]
}
```

### Debug Output

```
Error: Cycle: azurerm_virtual_network.aks_vnet, azurerm_subnet.pods_subnet, azurerm_kubernetes_cluster.aks
```

### Expected Behavior

Āble to use "azurerm_kubernetes_cluster" with "depends_on"

### Actual Behavior

Error.

### Steps to Reproduce

1. `terraform validate`

**Comment by njuCZ** [comment]
@philthynz in fact, every resource and data source could use "depends_on". terraform will calculate the dependency and make a Directed acyclic graph, then terraform knows the execution order. So in terraform cycle dependency is not allowed.

**Comment by tombuildsstuff** [comment]
hi @philthynz 

Thanks for opening this issue.

Taking a look through this appears to be a Terraform Configuration issue, insofar as there's a circular reference between all resources - as this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
