### ISSUE TITLE
azurerm_network_service_tags does not work for globally deployed resources (e.g. FrontDoor)

### ISSUE THREAD

**Issue by jbrailsford** [terraform-providers/terraform-provider-azurerm#9156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform: 0.13.0
* AzureRM:  2.33.0

### Affected Resource(s)

* azurerm_network_service_tags

### Terraform Configuration Files

```hcl
data "azurerm_network_service_tags" "frontdoor_networks" {
  location = "uksouth"
  service  = "AzureFrontDoor.Backend"
}
```

### Debug Output
Condensed log showing the full response from the Azure service tag API (including the service tag `AzureFrontDoor.Backend`:
https://gist.githubusercontent.com/AviateX14/f4b36fc559625b71846d30a9347ea455/raw/a139e9688ec81aee435ef4186782a5c85e9a325c/tflog

### Expected Behavior
The data source should've returned the list of address prefixes that are listed under the service tag `AzureFrontDoor.Backend`.

### Actual Behavior
The data source is unable to find the `AzureFrontDoor.Backend` service tag in the response, and errors with:

```
Error: specified service tag `AzureFrontDoor.Backend` not found globally

  on main.tf line 16, in data "azurerm_network_service_tags" "frontdoor_networks":
  16: data "azurerm_network_service_tags" "frontdoor_networks" {
```
### Steps to Reproduce

1. Create a file with the above data source in (exactly as it is there)
2. `terraform apply`

### Important Factoids

The unique thing about FrontDoor vs other services that this data source **does** work for, is that it does not have a region, since it's globally deployed service. In the response from the API, the all three FrontDoor service endpoints list the region as `"region": "",`. I suspect the cause will be related to that, perhaps the client is disregarding it due to the lack of region / trying to find it within a specific region?

**Comment by georgegil** [comment]
I used it is this way, and it worked for me:

`data "azurerm_network_service_tags" "example" {
  location        = "West US"
  service         = "AzureFrontDoor"
}`

**Comment by georgegil** [comment]
I used it as such, and it worked:

```
data "azurerm_network_service_tags" "example" {
  location        = "West US"
  service         = "AzureFrontDoor"
}
```

**Comment by katbyte** [comment]
@jbrailsford - it seems like @georgegil has proposed a solution that seems to work as such i am going to close this issue - please do reopen it if its still an problem for you!
