### ISSUE TITLE
Issues with BGP peering_address for azurerm_virtual_network_gateway  

### ISSUE THREAD

**Issue by qvallance** [terraform-providers/terraform-provider-azurerm#916]
Hey,

I'm running into an issue with the bgp peering_address for Virtual Network Gateways:

1. Cannot set the bgp peering address using Terraform, as Azure returns an error indicating that the setting cannot be modified (`Status=400 Code="VirtualNetworkGatewayBgpPeeringAddressCannotBeModified"`)

2. Cannot leave out the bgp peering address, as after the initial `terraform apply` completes provisioning any subsequent `terraform apply` will try to unset the `peering_address` set by Azure.  This will result in the same error, indicating that the peering address cannot be modified.
```
 ~ module.infra-vpn.azurerm_virtual_network_gateway.default
      bgp_settings.0.peering_address:   "192.168.0.4,192.168.0.5" => ""
```

### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.2
+ provider.random v1.1.0
+ provider.template v1.0.0

### Affected Resource(s)
- azurerm_virtual_network_gateway

### Terraform Configuration Files
```hcl
# ********************** VPN GATEWAY ********************** #
resource "azurerm_virtual_network_gateway" "default" {
  name                = "${var.vnet_gateway_name}"
  location            = "${var.location}"
  resource_group_name = "${data.azurerm_virtual_network.default.resource_group_name}"

  type          = "Vpn"
  vpn_type      = "RouteBased"
  active_active = true
  enable_bgp    = true
  sku           = "${var.vpn_sku}"

  ip_configuration {
    name                 = "gw-ip1"
    subnet_id            = "${azurerm_subnet.gateway.id}"
    public_ip_address_id = "${azurerm_public_ip.default.*.id[0]}"

    private_ip_address_allocation = "Dynamic"
  }

  ip_configuration {
    name                 = "gw-ip2"
    subnet_id            = "${azurerm_subnet.gateway.id}"
    public_ip_address_id = "${azurerm_public_ip.default.*.id[1]}"

    private_ip_address_allocation = "Dynamic"
  }

  bgp_settings {
    asn             = "${var.azure_bgp_asn}"
  }

  default_local_network_gateway_id = "${var.enable_forced_tunneling ? azurerm_local_network_gateway.local_sites.0.id : ""}"
}
```

### Debug Output
https://gist.githubusercontent.com/qvallance/ac9ca60056ecbc8eb956ad0a84a43524/raw/29972126271fe0b2be23926dd16187fc07879ddf/tf_azure_vnetgw_bgp_peering_address.txt

### Expected Behavior
When the `peering_address` is not set in `bgp_settings` config of the `azurem_virtual_network_gateway` resource when the resource was created, running a second apply shouldn't try to set the peeering_address value that was retrieved with a blank value.

### Actual Behavior
When the `peering_address` is not set in `bgp_settings` config of the `azurem_virtual_network_gateway` resource when the resource was created, running a second apply tries to set `peeering_address` to an empty value.

### Steps to Reproduce
1. Create a azurem_virtual_network_gateway with only the `asn` set in `bgp_settings`
2. `terraform apply`
3. Wait for virtual network gateway to be created.
4. `terraform apply`

### Important Factoids
- The Virtual Network Gateway is being setup as active-active
- Trying to specify the `peering_address` in the terraform config does not work.  Azure provides the same error about `The BgpPeeringAddress for the virtual network gateway [...] cannot be modified`

### References
N/A

**Comment by tombuildsstuff** [comment]
hey @qvallance 

Thanks for opening this issue :)

Taking a look into this, it appears the `peering_address` field should be `ForceNew` - which would make Terraform create a new resource when this field changes. It may be possible to make this change without a recreation on a newer version of the API - but we'd need to investigate this. Either way - I'm tagging this as a bug and we'll take a look in the near future

Thanks!
