### ISSUE TITLE
Support for proxiomity groups in azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by vaclav-dvorak** [terraform-providers/terraform-provider-azurerm#9164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Based on referenced document it should be possible to set proximity group on node pools created for AKS. It would be nice to have this ability in provider.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster
* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
    proximity_placement_group_id = "00000000-0000-0000-0000-000000000000"
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
}
```

### References

* https://docs.microsoft.com/en-gb/azure/aks/reduce-latency-ppg

**Comment by favoretti** [comment]
I can try and have a look at it tomororw/monday. Just checked, latest API supports this as well.
