### ISSUE TITLE
Unable to delete ip_restrictions in azurerm_app_service

### ISSUE THREAD

**Issue by TPPWC** [terraform-providers/terraform-provider-azurerm#9171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
module "app_service_1" {
  source  = "tfe........"
  version = "1.1.2-pre-04" # to pin the version use "1.1.x"
  app_service_plan_id                    = module.app_service_plan_1.id
  instance                               = "01"
  # optional parameters are initially uncommented
  appservice_stack_dotnet               = "v4.0"
  ip_restrictions                       = [
       {
     name       = "ALLOW01"
     priority   = 101
     ip_address = "195.xxx.xxx.xxx/27"
   },
   {
     name       = "ALLOW02"
     priority   = 102
     ip_address = "217.xxx.xxx.xxx/27"
   }
  ]
  default_documents                     = ["index.html", "default.html"]
```
```hcl
dynamic "ip_restriction" {
      for_each = var.ip_restrictions != null ? var.ip_restrictions : []
      content {
        priority                  = ip_restriction.value.priority
        ip_address                = lookup(ip_restriction.value, "ip_address", null)
        name                      = lookup(ip_restriction.value, "name", null)
        action                    = lookup(ip_restriction.value, "action", "Allow")
      }
    }
  }
```

### Expected Behavior

When I set the parameters in the module cal the ip_restrictions will be set. When I delete them they will be deleted in the app service as well.

### Actual Behavior

Once I set the ip_restrictions there is no way to delete them anymore. If I delete the ip_restriction section or even leave it empty nothing changes. The ip_restrictions cannot be deleted anymore.

### Steps to Reproduce

- deploy an app service with ip_restrictions set
- delete the ip:restrictions

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
As docs state here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#ip_restriction

User has to explicitly set `ip_restriction` to empty slice (`[]`) to remove it.

**Comment by TPPWC** [comment]
Well this does not work, that's why I opened the issue. And in my example it will be [] when nothing is set:

for_each = var.ip_restrictions != null ? var.ip_restrictions : **[]**

Also the variables is set to [] as default if we just delete the line.

**Comment by favoretti** [comment]
If I read your code correctly - `dynamic` with `for_each` over an empty array won't generate any entries.
What you need is to generate an empty `ip_restrictions` array:
```
ip_restrictions = []
```

**Comment by TPPWC** [comment]
Well that is what the loop does, if there is an entry it is var.ip_restrictions otherwise if no entry it is []

**Comment by TPPWC** [comment]
This is a simpler version of it and does not work as well. I can add and delete single entries but if there are none it does not work. The terraform plan even shows that no updates made.

dynamic "ip_restriction" {
      for_each = var.ip_restrictions
      iterator = ip_restriction
      content {
        ip_address = ip_restriction.value
      }
    }
  }

**Comment by favoretti** [comment]
What I'm trying to say is that `dynamic`, when iterating over an empty map or an array will not produce _any_ entries, i.e. it won't give you `ip_restrictions = []`, it will produce nothing. Unless I'm completely misunderstanding it.

**Comment by TPPWC** [comment]
Hmm good point, I will test this

**Comment by TPPWC** [comment]
Well I tried it this way, but does not seem to work. Like you mentioned somehow the empty array is not recognized. I would expect that the dynamic block is not active.

```hcl
dynamic "ip_restriction" {
      for_each = [for v in var.ip_restrictions : v if length(v) > 0]
      iterator = ip_restriction
      content {
        ip_address = ip_restriction.value
      }
    }
  }
  ```

**Comment by favoretti** [comment]
So I'm not really sure how to make this work the way it should if you wanna use `dynamic`. Found this, maybe this will help? 
https://www.reddit.com/r/Terraform/comments/ezqb22/how_can_you_create_an_empty_dynamic_block/

**Comment by TPPWC** [comment]
Yes that's the solution of the problem. Dynamic block does not work for this attribute.

```hcl
ip_restriction = [ 
      for ip_range in var.ip_restrictions: {
        ip_address = ip_range
        name                      = null
        priority                  = null
        action                    = "Allow"
        subnet_id                 = null
        virtual_network_subnet_id = null
      }
     ]
  }
```

This block works now.

Thx for the hint!

**Comment by TPPWC** [comment]
Solution found
