### ISSUE TITLE
Synapse Analytics with Private Endpoint fails

### ISSUE THREAD

**Issue by bytemech** [terraform-providers/terraform-provider-azurerm#9176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.34.0

### Affected Resource(s)
+ azurerm_private_endpoint
+ azurerm_synapse_workspace

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
resource "azurerm_synapse_workspace" "main" {
  name                = var.synapse_workspace_name
  resource_group_name = azurerm_resource_group.main.name
  location            = var.location
  tags                = var.tags

  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.datalake.id
  sql_administrator_login_password     = random_password.sql.result
  sql_administrator_login              = var.sql_admin_username

  aad_admin {
    login     = azuread_application.spn.name
    object_id = azuread_service_principal.spn.object_id
    tenant_id = data.azurerm_client_config.current.tenant_id
  }
}

resource "azurerm_synapse_firewall_rule" "main" {
  name                 = "AllowAllWindowsAzureIps"
  synapse_workspace_id = azurerm_synapse_workspace.main.id
  start_ip_address     = "0.0.0.0"
  end_ip_address       = "0.0.0.0"
  //See https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/synapse_firewall_rule.html.markdown
}

resource "azurerm_private_endpoint" "synapse" {
  name                = var.synapse_workspace_name
  resource_group_name = azurerm_resource_group.main.name
  location            = var.location
  subnet_id           = azurerm_subnet.main.id

  private_service_connection {
    name                           = var.synapse_workspace_name
    private_connection_resource_id = azurerm_synapse_workspace.main.id
    is_manual_connection           = false
    subresource_names              = ["sqlServer"]
  }
}
```
### Expected Behavior
Private link endpoint deploys

### Actual Behavior

```
Error: creating Private Endpoint "syn8wqe45" (Resource Group "rg-8wqe45"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateEndpointConnectionProxyValidationFailed" Message="Call to Microsoft.Synapse/workspaces failed. Error message: Private Endpoint Connection Proxy validation failed, check error details for more information" Details=[{"code":"InvalidGroupIdInPrivateLinkServiceConnection","message":"Invalid group ID: sqlServer specified in Private Link Service Connection"}]
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @bytemech 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Terraform Configuration - since the value `sqlServer` isn't valid for the `subresource_names` field in this instance, as SQL Server and Azure Synapse are two different products, different values may be necessary.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by bytemech** [comment]
Hi @tombuildsstuff 

Thanks for your prompt response, though it's somewhat unhelpful.

1. I'm aware this is the Azure provider, having submitted PRs here before. 
2. As per [the Azure documentation](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#private-link-resource) **sqlServer is the correct subresource name for Azure Synapse Analytics**
3. I appreciate you wanting to keep the issues list clean, but this is a bug. It may be an upstream bug with the Go SDK, or with the ARM REST api, but it's still a bug nevertheless.

Could you please reopen this issue or give a better reason for why you've closed it? 

Cheers,
BG

**Comment by kulmam92** [comment]
@bytejunkie 

I had the same issue. However, I wasn't able to get it working.
Even though [The Azure documentation](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#private-link-resource) states "Sql Server (sqlServer)", values in the drop-down are like below.

![synapseworkspace-target-sub-resource](https://user-images.githubusercontent.com/4615942/98849200-b382d900-2407-11eb-9986-dd7311f12bb6.png)

Therefore, I tried with "Sql" and the private endpoint creation went through.

```
  private_service_connection {
    name                           = module.naming.private_service_connection.name
    private_connection_resource_id = azurerm_synapse_workspace.synapse.id
    is_manual_connection           = false
    # https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#private-link-resource
    # Sql, SqlOnDemand, Dev
    subresource_names              = ["Sql"]
  }
```

**Comment by bytemech** [comment]
Thanks @kulmam92 :+1:
