### ISSUE TITLE
azurerm_redis_cache - rdb_storage_connection_string & access keys changing on every run of terraform plan/apply

### ISSUE THREAD

**Issue by manish-eros** [terraform-providers/terraform-provider-azurerm#9203]
**Terraform (and AzureRM Provider) Version**

`Terraform v0.13.5`
`+ provider registry.terraform.io/hashicorp/azurerm v2.32.0`
`+ provider registry.terraform.io/hashicorp/template v2.2.0`

**Terraform Configuration Files**

```
resource "azurerm_redis_cache" "redis-instance" {
  name                = "en-${var.env}-${var.name}-redis"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  capacity            = "${var.capacity}"
  family              = "${var.family}"
  sku_name            = "${var.cache_type}"
  enable_non_ssl_port = true
  minimum_tls_version = "1.2"
  shard_count = "${var.shard_count}"

  patch_schedule {
    day_of_week = "${var.day_of_week}"
    start_hour_utc = "${var.start_hour_utc}"
  }
  redis_configuration {
    enable_authentication = "${var.auth_value}"
    rdb_backup_enabled = true
    rdb_backup_frequency = 1440
    rdb_backup_max_snapshot_count = "${var.rdb_backup_max_snapshot_count}"
    rdb_storage_connection_string = "${var.rdb_storage_connection_string}"
  }
  subnet_id = "${var.subnet_id}"
  tags = {
    environment = "${var.env} Managed by Terraform for Azure"
    name = "${var.name} - Managed by Terraform for Azure"
  }
}
```

Two observations:
1. "rdb_storage_connection_string" is set at the run time as follows:

`rdb_storage_connection_string = "DefaultEndpointsProtocol=https;BlobEndpoint=https://appstorage.blob.core.windows.net;AccountName=appstorage;AccountKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"`

On each & every run of terraform plan & above field is updated as an inline change? I'm not able to figure out why.

2. At the same time I see that the access keys are changing on each & every run.

How do I stop from both of these from happening?

Thanks,
Manish.

**Comment by tombuildsstuff** [comment]
hi @manish-eros 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by manish-eros** [comment]
Hi Tom,

I was able to fix this by using following block:

```
  lifecycle {
    ignore_changes = [redis_configuration.0.rdb_storage_connection_string]
  }
```
Thanks,
