### ISSUE TITLE
Support for Identity-based access for file shares with AAD DS

### ISSUE THREAD

**Issue by alexwilcox9** [terraform-providers/terraform-provider-azurerm#9221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This functionality would allow you to enable or disable Identity-based access for file shares (using AADDS) on Storage Accounts.
Currently you either need to enable this through the GUI or az cli post Terraform apply

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "example" {
  name                = "storageaccountname"
  resource_group_name = azurerm_resource_group.example.name

  location                      = azurerm_resource_group.example.location
  account_tier                  = "Standard"
  account_replication_type      = "LRS"
  identity_based_access_enabled = true

  network_rules {
    default_action             = "Deny"
    ip_rules                   = ["100.0.0.1"]
    virtual_network_subnet_ids = [azurerm_subnet.example.id]
  }

  tags = {
    environment = "staging"
  }
}
```

### References

https://docs.microsoft.com/en-us/azure/storage/files/storage-files-identity-auth-active-directory-domain-service-enable?tabs=azure-cli#enable-azure-ad-ds-authentication-for-your-account
* #6687

**Comment by yupwei68** [comment]
Hi kt, would you close this issue, for the related PR has been merged?

**Comment by alexwilcox9** [comment]
Added in v2.59.0
https://github.com/terraform-providers/terraform-provider-azurerm/pull/11485
