### ISSUE TITLE
Creating vnet injected databrick Terraform creates extra nsg

### ISSUE THREAD

**Issue by Mitanshirathor** [terraform-providers/terraform-provider-azurerm#9232]
Creating vnet injected databrick Terraform creates extra nsg with name similar to "Microsoft.Databricks-workspaces_UseOnly_databricks-worker-to-sql" and others and removes actions from subnet "Microsoft.Network/virtualNetworks/subnets/join/action" which were not part of the script when applied again. Not sure why it adds additional nsg in the first place and then when re-deployed removes them. I would like to know the reason for this.

---

Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by manicminer** [comment]
hi @Mitanshirathor, thanks for opening this issue.

We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). Accordingly I'm going to close this issue, but I believe you should be able to get an answer on the community discussion portal.
