### ISSUE TITLE
azurerm_monitor_metric_alert missing possibility of adding multiple alert groups id like in other alerts

### ISSUE THREAD

**Issue by romeomorcia** [terraform-providers/terraform-provider-azurerm#9240]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_monitor_metric_alert missing the possibility of adding an array of alert groups because a string accepted instead of an array of string.

This functionality is working for azurerm_monitor_scheduled_query_rules_alert

### New or Affected Resource(s)

* azurerm_monitor_metric_alert

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "main" {
  name     = "example-resources"
  location = "West US"
}

resource "azurerm_storage_account" "to_monitor" {
  name                     = "examplestorageaccount"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_monitor_action_group" "main" {
  name                = "example-actiongroup"
  resource_group_name = azurerm_resource_group.main.name
  short_name          = "exampleact"

  webhook_receiver {
    name        = "callmyapi"
    service_uri = "http://example.com/alert"
  }
}

resource "azurerm_monitor_action_group" "niam" {
  name                = "example-actionmail"
  resource_group_name = azurerm_resource_group.main.name
  short_name          = "examplemail"

  email_receiver {
    name          = "sendtoadmin"
    email_address = "admin@contoso.com"
  }
}

resource "azurerm_monitor_metric_alert" "example" {
  name                = "example-metricalert"
  resource_group_name = azurerm_resource_group.main.name
  scopes              = [azurerm_storage_account.to_monitor.id]
  description         = "Action will be triggered when Transactions count is greater than 50."

  criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts"
    metric_name      = "Transactions"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 50

    dimension {
      name     = "ApiName"
      operator = "Include"
      values   = ["*"]
    }
  }

  action {
    action_group = [azurerm_monitor_action_group.main.id, azurerm_monitor_action_group.niam.id]
  }
}
```

This is not allowing me to use the resource as I cannot in any way add more than one action group.

**Comment by favoretti** [comment]
Unfortunately API only accepts 1 (one) group id per action:
https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/createorupdate#metricalertaction

**Comment by romeomorcia** [comment]
@favoretti Is there a chance you know how to raise this to microsoft?

**Comment by romeomorcia** [comment]
@favoretti i'm afraid you're wrong:
REST API allows to add an array of alerts:

https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/createorupdate
I've also tested it and it works.
![image](https://user-images.githubusercontent.com/56087756/99378765-1d97f400-28c8-11eb-9b3f-3d86c7b2b693.png)

**Comment by tombuildsstuff** [comment]
@romeomorcia the API allows a single when using the "Single" type, which we're doing today - there's a "Multiple" type which is now available (and working) which'll unblock this - however this requires switching to the "Multiple" type to be able to specify multiple types here.

**Comment by romeomorcia** [comment]
@tombuildsstuff thanks for the explanation. Does this mean that are you going to switch that to unblock it? Thanks!

**Comment by tombuildsstuff** [comment]
@romeomorcia at some point, yes.

Support for that is being tracked in #4337, rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4337 for updates?

Thanks!

**Comment by romeomorcia** [comment]
@tombuildsstuff i'm afraid that is not the same issue I have now? Here I want to add multiple action groups to a singoular alert, not to the entire resource group?

**Comment by tombuildsstuff** [comment]
@romeomorcia the fix will be the same for both, switching from Single to Multiple enables both scenarios.
