### ISSUE TITLE
Missing "depends_on" in documentation of data "azurerm_public_ip"

### ISSUE THREAD

**Issue by TormodLandet** [terraform-providers/terraform-provider-azurerm#9266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description of issue

This is a documentation bug.

The web page https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/public_ip is missing the "depends_on" that is required to get the IP address of a newly created VM, see e.g. issue 310 https://github.com/terraform-providers/terraform-provider-azurerm/issues/310

```terraform
data "azurerm_public_ip" "example" {
  name                = azurerm_public_ip.example.name
  resource_group_name = azurerm_virtual_machine.example.resource_group_name

  # Required! Otherwise the recipe fails if the IP address is not already created on Azure
  depends_on = [azurerm_virtual_machine.example]
}
```

**Comment by tombuildsstuff** [comment]
hi @TormodLandet 

Thanks for opening this issue.

Taking a look through this appears to be a regression in Terraform Core, where dependencies aren't detected when a non-ID field is used as a reference - as such would you mind opening an issue [on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone from the Terraform Core team should be able to take a look?

Thanks!

**Comment by tombuildsstuff** [comment]
Actually apparently this has been fixed in the upcoming version of Terraform Core, v0.14: https://github.com/hashicorp/terraform/issues/25961 - which is currently in Beta: https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-beta
