### ISSUE TITLE
azurerm_log_analytics_workspace - DailyQuotaGb is a read only property and cannot be changed

### ISSUE THREAD

**Issue by jdruffel** [terraform-providers/terraform-provider-azurerm#9269]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.35.0

### Affected Resource(s)

*azurerm_log_analytics_workspace*

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "bpg-it-rg-automation" {
  name     = "bpg-it-rg-automation"
  location = "westeurope"
}

resource "azurerm_automation_account" "bpg-it-automationaccount" {
  name                = "bpg-it-automationaccount"
  location            = azurerm_resource_group.bpg-it-rg-automation.location
  resource_group_name = azurerm_resource_group.bpg-it-rg-automation.name
  sku_name            = "Basic"
}

resource "azurerm_log_analytics_workspace" "bpg-it-loganalytics-automation" {
  name                = "bpg-it-loganalytics-automation"
  location            = azurerm_resource_group.bpg-it-rg-automation.location
  resource_group_name = azurerm_resource_group.bpg-it-rg-automation.name
  sku                 = "Free"
```

### Debug Output

https://gist.github.com/jdruffel/88bbff8dc87aec0fd67edcafe09ce824

### Expected Behaviour

azurerm_log_analytics_workspace should have deployed normally, no changes should have been made

### Actual Behaviour

Terraform wants to change the readonly property DailyQuotaGb which it cannot change.
I did not specify that property, If I specify it it does not change anything.

Original Error: Code="BadRequest" Message="DailyQuotaGb is a read only property and cannot be changed"
### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @jdruffel 

Thanks for opening this issue :)

This has been fixed in #9228 and will become available in version 2.36.0 of the Azure Provider - since support for this has been merged I'm going to close this issue for the moment; however I've assigned this to the 2.36.0 milestone so @hashibot will comment when the release is available.

Thanks!
