### ISSUE TITLE
Data source for Azure Servicebus Subscription

### ISSUE THREAD

**Issue by ritesh-modi** [terraform-providers/terraform-provider-azurerm#9278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no existing data source related to Azure Servicebus Subscription. 

### New or Affected Resource(s)

azurerm_Servicebus

### Potential Terraform Configuration

data "azurerm_servicebus_subscription" "test" {
	name                = azurerm_servicebus_subscription.test.name
	resource_group_name = azurerm_resource_group.test.name
	namespace_name      = azurerm_servicebus_namespace.test.name
	topic_name          = azurerm_servicebus_topic.test.name
  }

**Comment by HarleyB123** [comment]
Hey - quite new to Terraform Development but can happily give this one a go?
