### ISSUE TITLE
Support for AVS

### ISSUE THREAD

**Issue by yupwei68** [terraform-providers/terraform-provider-azurerm#9283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure VMware Solution provides you with private clouds that contain vSphere clusters, built from dedicated bare-metal Azure infrastructure.
All provisioned private clouds have vCenter Server, vSAN, vSphere, and NSX-T. You can migrate workloads from your on-premises environments, deploy new virtual machines (VMs), and consume Azure services from your private clouds.

### New or Affected Resource(s)

* azurerm_avs_private_cloud
* azurerm_avs_cluster
* azurerm_avs_authorization

### Potential Terraform Configuration

```hcl
resource "azurerm_avs_private_cloud" "example" {
  name                = "example-avs-private-cloud"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku_name            = "AV36"

  management_cluster {
    cluster_size = 3
  }

  network_block      = "192.168.48.0/22"
  internet_connected = false
  nsxt_password      = "QazWsx13$Edc"
  vcenter_password   = "QazWsx13$Edc"
  tags = {
    foo = "bar"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/azure-vmware/introduction
*https://docs.microsoft.com/en-us/azure/azure-vmware/tutorial-create-private-cloud

**Comment by ctaggart** [comment]
Is this being blocked on feedback for the trace header issue?
https://github.com/Azure/azure-resource-manager-rpc/issues/101

**Comment by jimmfarley** [comment]
Yes, we need this soon!

**Comment by dylanhughes** [comment]
@yupwei68 looks like we are close to bringing this resource to the Azure provider, there are no blockers now correct? It is just on a long list or priorities to get reviewed?

**Comment by yupwei68** [comment]
Close for they are all supported.
