### ISSUE TITLE
azurerm_firewall_policy_rule_collection_group destination_ports argument does not support "*" or "1-65535"

### ISSUE THREAD

**Issue by minimalz** [terraform-providers/terraform-provider-azurerm#9304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.13.5
azurerm 2.35.0

### Affected Resource(s)

* `azurerm_firewall_policy_rule_collection_group`

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_policy_rule_collection_group" "defaultgrouprules" {
  name               = "DefaultNetworkRuleCollectionGroup"
  firewall_policy_id = azurerm_firewall_policy.pol01.id
  priority           = 200

 network_rule_collection {
    name     = "CollectionforTesting"
    priority = 1000
    action   = "Allow"
    rule {
      name                  = "AllowAll"
      protocols             = ["Any","ICMP","TCP","UDP"]
      source_addresses      = ["*"]
      destination_addresses = ["*"]
      destination_ports     = ["*"]
    }
  }
 network_rule_collection {
    name     = "DenyTest"
    priority = 101
    action   = "Deny"
    rule {
      name                  = "DenyTest"
      protocols             = ["ICMP"]
      source_addresses      = ["161.211.222.59"]
      destination_addresses = ["10.187.9.4"]
      destination_ports     = ["*"]
    }
  }
}
```

### Expected Behaviour

Either skip existing rules or apply new rules as specified in the configuration file.

### Actual Behaviour

An error results when using "*" as a destination_ports argument.  An asterisk is a valid destination_port argument when using the Azure Portal.  We have existing rules already configured via the Azure portal using asterisks for destination_ports.

Error: invalid format of "network_rule_collection.3.rule.0.destination_ports.0"
   on main.tf line 37, in resource "azurerm_firewall_policy_rule_collection_group" "defaultgrouprules":
   37: resource "azurerm_firewall_policy_rule_collection_group" "defaultgrouprules" {

or attempting to use "1-65535" port range instead

Error: port 65535 is out of range (0-64000)
   on main.tf line 37, in resource "azurerm_firewall_policy_rule_collection_group" "defaultgrouprules":
   37: resource "azurerm_firewall_policy_rule_collection_group" "defaultgrouprules" {

### Steps to Reproduce

1. Run terraform apply using configuration above with "*" as an argument for destination_ports

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested on Azure portal, seems it allows "1-65535" for destination ports. But seems api service doesn't allow "1-65535". I assume it should be an API bug. So I raised an issue on Azure/azure-rest-api-specs#11831.

And according by the error message from API, seems the lower limit of destination ports should be 1 not 0. So I submitted a [PR ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/9490)to fix.
Error message:
```
Error: creating Firewall Policy Rule Collection Group "acctest-fwpolicy-RCG-test01" (Resource Group "acctestRG-fwpolicy-RCG-test01" / Policy: "acctest-fwpolicy-RCG-test01"): network.FirewallPolicyRuleCollectionGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"message":"The request is invalid.","modelState":{"resource":["{\"Status\":\"Failed\",\"Error\":{\"Code\":\"FirewallPolicyRuleConditionInvalidPortOrRangeFormat\",\"Message\":\"Firewall Policy Rule Condition nat_rule_collection1_rule1: Invalid port value or range. User ports must be in [1, 64000]\",\"Target\":null}}"]}}]
```

**Comment by daruskorz** [comment]
Hello, do you have any eta about fix release ?
