### ISSUE TITLE
Support for publicNetworkAccess property on resource azurerm_redis_cache

### ISSUE THREAD

**Issue by robin-sf** [terraform-providers/terraform-provider-azurerm#9307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This optional property allows setting the Redis server to block public connections and only allow connections over private links.

As per https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-private-link the non-TF way to do it is to issue the following patch request to the resource: 

```
PATCH  https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resourcegroup}/providers/Microsoft.Cache/Redis/{cache}?api-version=2020-06-01
{    "properties": {
       "publicNetworkAccess":"Disabled"
   }
}
```

This feature was in public preview at the time of writing

### New or Affected Resource(s)

* azurerm_redis_cache

### Potential Terraform Configuration

```hcl
resource "azurerm_redis_cache" "example" {
  name                  = "example-cache"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  capacity              = 2
  family                = "C"
  sku_name              = "Standard"
  enable_non_ssl_port   = false
  minimum_tls_version   = "1.2"
  public_network_access = false
  redis_configuration {
  }
}
```

**Comment by tombuildsstuff** [comment]
Fixed via #10410
