### ISSUE TITLE
Feature request: Service Principal Name (SPN) creation

### ISSUE THREAD

**Issue by pixelicous** [terraform-providers/terraform-provider-azurerm#932]
Hi,

Today terraform doesn't support creation of SPN account with respective ad application.
ARM Template also do not support it.
Rendering the need to use external provider wiht powershell and somehow pass clear text credentials to powershell to log in and actually create the SPN..

**Comment by tombuildsstuff** [comment]
hey @pixelicous 

Thanks for opening this issue :)

I'm not completely familiar with the breakdown of SPN's - but I believe this is a duplicate feature request of #16 - would you be able to confirm if that's the case?

If so - this is on our short-term roadmap, but I'm unable to give a more detailed timeframe at this point, unfortunately.

Thanks!

**Comment by pixelicous** [comment]
@tombuildsstuff hey.. thanks for the response.. it is a duplicate, i actually looked on issues before but it was titled differently. 
Thank you, waiting anxiously for this.. imho it should be prioritized for azurerm provider, a lot relies on those spns and granting them permissions to create resources themselves

The rbac roles support in the title is supported in terraform for all i know

**Comment by tombuildsstuff** [comment]
@pixelicous thanks for confirming; I'll close this in favour of #16 - RBAC isn't currently supported but it should be _soon_ :)
