### ISSUE TITLE
Support for Assets in  Azure Media Services Account

### ISSUE THREAD

**Issue by jcanizalez** [terraform-providers/terraform-provider-azurerm#9323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hoping to get support for the creation and manipulation of Assets in Azure Media Services Account.

### New or Affected Resource(s)

* azurerm_media_asset

### Potential Terraform Configuration

```hcl
resource "azurerm_media_asset" "asset" {
  name                     = "asset1"
  resource_group_name      = azurerm_resource_group.media.name
  media_services_account_name = azurerm_media_services_account.ams.name
  description = "My asset description"
}
```

### References

https://docs.microsoft.com/en-us/azure/media-services/latest/assets-concept
https://docs.microsoft.com/en-us/azure/templates/microsoft.media/mediaservices/assets

**Comment by jcanizalez** [comment]
I would like to work on this issue

**Comment by tombuildsstuff** [comment]
Looks like support for this is available in the SDK: https://github.com/Azure/azure-sdk-for-go/tree/master/services/mediaservices/mgmt

**Comment by jcanizalez** [comment]
Thank you Tom I created this PR #9387
