### ISSUE TITLE
azurerm_eventgrid_system_topic is failing to create topic_type "Microsoft.Resources.Subscriptions" due to location

### ISSUE THREAD

**Issue by cerocool1203** [terraform-providers/terraform-provider-azurerm#9335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.36.0
### Affected Resource(s)

* `azurerm_eventgrid_system_topic`

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_system_topic" "example" {
  name                   = "example-topic"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  source_arm_resource_id = "/subscriptions/{sub_ID}
  topic_type             = "Microsoft.Resources.Subscriptions"
}

```

### Expected Behaviour

azurerm_eventgrid_system_topic applied correctly given Subscription do not have a "region" based location and linked to an Azure Event Grid Subscription as per github issue 9141

### Actual Behaviour

Error: eventgrid.SystemTopicsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequest" Message="System topic's location must match with location of the source resource /subscriptions/{sub_ID}"

### Steps to Reproduce

azurerm_eventgrid_system_topic applied correctly given Subscription do not have a "region" based location

1. `terraform apply`

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
After completion I should be able to like the system topic to a subscription as per ticket below
https://github.com/terraform-providers/terraform-provider-azurerm/issues/9141

* #0000

**Comment by piotrgwiazda** [comment]
I have the same error for type "Microsoft.Resources.ResourceGroups" and also with version v2.37.0
Tried both "West Europe" and "westeurope" but the plan always show "westeurope".

**Comment by jrauschenbusch** [comment]
@cerocool1203 As it seems you have to use the constant string value `Global` as location. This is currently not documented. So maybe give me feedback if this works for you, then i'll update the docs.

@piotrgwiazda Your problem is a different one. The `terraform plan` step already performs some Azure resource sync calls (Resource Read operation), where `West Europe` will be automatically changed to `westeurope` by the Azure backend. This could be fixed by implementing a relaxed diff for the location attribute of the resource schema. But this is just a minor issue i would say.

**Comment by piotrgwiazda** [comment]
Should I raise a separate issue then? Is there a workaround?

niedz., 6 gru 2020, 13:42 użytkownik Jochen Rauschenbusch <
notifications@github.com> napisał:

**Comment by jrauschenbusch** [comment]
@piotrgwiazda I've now tested your issue. It seems that you also have to use `location = "Global"` for the topic_type `Microsoft.Resources.ResourceGroups`.

I'll now test if a `terraform apply` followed by a `terraform plan` directly will tell you that there are changes to be applied.

I think there is an update of the docs and integration tests required for the `location = "Global"` thing.
