### ISSUE TITLE
Feature Request: Deployment Credentials for AKS

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#934]
Chatting internally about using the `azurerm_kubernetes_cluster` resource - we should look into returning the Kubernetes credentials, which are needed to connect to the cluster and could be used in other resources/provisioners.

We return this information in [the equivalent resource in Google Cloud](https://www.terraform.io/docs/providers/google/r/container_cluster.html#master_auth) - and it appears to be available [in the Azure CLI too](https://github.com/Azure/azure-cli/blob/f22ee404aadf7f3e8fb9610be170d32d6e6edcbc/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L904) although it is via connecting to the box and using secure copy.

**Comment by paultyng** [comment]
Here is an example workaround in the TF guides repo: https://github.com/hashicorp/terraform-guides/blob/master/infrastructure-as-code/k8s-cluster-acs/main.tf#L74

**Comment by paultyng** [comment]
I think the other issue with this is the resource currently only gets the public SSH key data, not the private key, so we'd have to add that in order to connect to the machine I think? Perhaps this should just be like a separate data source to pull these credentials?

**Comment by rberlind** [comment]
I would love it if the new azurerm_kubernetes_cluster did return the credentials (3 keys/certs) the way the GKE equivalent does.  The code you referred to to work around is by me.  :)

**Comment by tombuildsstuff** [comment]
Support for this shipped in v1.5.0 and can be found in [the `kube_config` block](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#kube_config_raw) - as such I'm going to close this issue.
