### ISSUE TITLE
documentation on import of azurerm_monitor_diagnostic_setting resource

### ISSUE THREAD

**Issue by sean-t-shen** [terraform-providers/terraform-provider-azurerm#9347]
This is to report a correction on the online documentation of "azurerm_monitor_diagnostic_setting"

The original link of the Terraform documentation is here:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#import

where it discusses how to import this resource from Azure if one already exists.  The documentation states:

=====================
Diagnostic Settings can be imported using the resource id, e.g. 

terraform import azurerm_monitor_diagnostics.example /subscriptions/XXX/resourcegroups/resource_group/providers/microsoft.keyvault/vaults/vault|logMonitoring
=====================

First of all, the import command should start out with "terraform import azurerm_monitor_diagnostics_setting".  
"_setting" must be there, because that is the actual resource type.

Also, PLEASE NOTE, there is a pipe character "|" between "vault" and "logMonitoring".   This pipe "|" should be preceded by an escape character, otherwise, it will be misconstrued by the OS as a pipe, which will cause the portion of the command before the pipe to be executed first, and then the result piped into the part after the "|" character.  Thus the whole command will result in failure.

If one is running this command on Windows command line, then the escape character is "^".  If you are on Linux, then it is back slash.  In either case, the example should read like this:

# on Windows
terraform import azurerm_monitor_diagnostics.example /subscriptions/XXX/resourcegroups/resource_group/providers/microsoft.keyvault/vaults/vault^|logMonitoring"

# on linux
terraform import azurerm_monitor_diagnostics.example /subscriptions/XXX/resourcegroups/resource_group/providers/microsoft.keyvault/vaults/vault\\|logMonitoring"

Please review and validate.  If what I stated above is accurate, please update the documentation.

Thanks
Sean

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume you're right. The resource type "azurerm_monitor_diagnostics_setting" should be updated. But for the resource id, I assume you have to wrap resource id in double quotes.
