### ISSUE TITLE
Support for delegatedManagedIdentityResourceId to azurerm_role_definition resource

### ISSUE THREAD

**Issue by grayzu** [terraform-providers/terraform-provider-azurerm#9348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enable the Azure Lighthouse scenario described in this article with Terraform: [Deploy a policy that can be remediated within a delegated subscription](https://docs.microsoft.com/en-us/azure/lighthouse/how-to/deploy-policy-remediation)

In order to accomplish this, a new property has been added to role definitions in 2019-04-01-preview API. This property "delegatedManagedIdentityResourceId" is required for assigning roles in Azure Lighthouse. Update the [azurerm_role_assignment resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment) to include the new property.

### New or Affected Resource(s)

* azurerm_role_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_role_assignment" "example" {
  scope                             = data.azurerm_subscription.primary.id
  role_definition_name              = "Reader"
  principal_id                      = data.azurerm_client_config.example.object_id
  delegated_managed_identity_id     = azurerm_user_assigned_identity.example.id
}
```

**Comment by grayzu** [comment]
Swagger PR (draft) that will enable Terraform to support this new property: https://github.com/Azure/azure-rest-api-specs/pull/11510

**Comment by justin-ldn** [comment]
We are super keen to have this feature as we are blocked on use of Terraform through Lighthouse using this.

**Comment by njuCZ** [comment]
`delegatedManagedIdentityResourceId` is a new field introduced in this PR https://github.com/Azure/azure-rest-api-specs/pull/11506, however there is some problem in this PR which would cause go sdk generation failed. The service team has known this Issue and would fix it soon. For now it's blocked

**Comment by justin-ldn** [comment]
@njuCZ Thanks for explaining the dependency - is that work to resolve the issue with the merged PR above being tracked on GitHub?
