### ISSUE TITLE
Re-Deploying azurerm_storage_account doesn't recreate storage containers

### ISSUE THREAD

**Issue by duncan9562** [terraform-providers/terraform-provider-azurerm#9353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
provider.azurerm v2.36.0
```

### Affected Resource(s)
```
azurerm_storage_account
azurerm_storage_container
azurerm_storage_blob
```

### Terraform Configuration Files

```
resource "azurerm_storage_account" "storage_account" {
  count                    = var.create_storage_account == true ? 1 : 0
  name                     = var.storage_account_name == "" ? lower("${replace(var.project_name, "-", "")}${var.environment}storage") : var.storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  min_tls_version          = var.min_tls_version_storage_account
  allow_blob_public_access = "false"

  tags = {
    project      = var.project_name
    environment  = var.environment
    billing_code = var.billing_code
    cost_centre  = var.cost_centre
  }
}

resource "azurerm_storage_container" "application_container" {
  count                 = var.create_storage_account == true ? 1 : 0
  name                  = lower("${var.project_name}-${var.environment}-application")
  storage_account_name  = azurerm_storage_account.storage_account[0].name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "application_blob" {
  count                  = var.create_storage_account == true ? 1 : 0
  name                   = "application_blob"
  storage_account_name   = azurerm_storage_account.storage_account[0].name
  storage_container_name = azurerm_storage_container.application_container[0].name
  type                   = "Block"
}

resource "azurerm_storage_container" "server_container" {
  count                 = var.create_storage_account == true ? 1 : 0
  name                  = lower("${var.project_name}-${var.environment}-server")
  storage_account_name  = azurerm_storage_account.storage_account[0].name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "server_blob" {
  count                  = var.create_storage_account == true ? 1 : 0
  name                   = "server_blob"
  storage_account_name   = azurerm_storage_account.storage_account[0].name
  storage_container_name = azurerm_storage_container.server_container[0].name
  type                   = "Block"
}
```
### Expected Behaviour

Terraform will destroy the resource `azurerm_storage_account.storage_account[0]` and recreate it along with the 2 containers and 2 blobs that are specified in the code.

### Actual Behaviour

Terraform destroys the resource `azurerm_storage_account.storage_account[0]` and recreates it but doesn't create the storage containers or blobs. These resources __are__ created when running a __second__ `terraform apply`.

### Steps to Reproduce

With all resources deployed:-
* Mark the resource `azurerm_storage_account.storage_account[0]` as tainted `terraform taint "azurerm_storage_account.storage_account[0]"`
* Run a plan `terraform plan`
* Run `terraform apply`

### Important Factoids

* None

### References

* None

**Comment by tombuildsstuff** [comment]
hey @duncan9562 

Thanks for opening this issue.

Taking a look into this unfortunately this is a bug in Terraform Core and as such would need to be fixed there. There's an upstream issue tracking this (https://github.com/hashicorp/terraform/issues/8099) where the Terraform Core team should be able to take a look and make a fix; but once the fix is added that should automatically become available to all providers. Since this isn't something we're able to work around in the Azure Provider directly; for the moment I'm going to close this in favour of the upstream issue https://github.com/hashicorp/terraform/issues/8099 - would you mind subscribing to that issue for updates?

Thanks!
