### ISSUE TITLE
azurerm_app_service_virtual_network_swift_connection  Apply takes a long time and always fails

### ISSUE THREAD

**Issue by kinwolfqc** [terraform-providers/terraform-provider-azurerm#9362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.13.4
### Affected Resource(s)

* `azurerm_app_service_virtual_network_swift_connection `

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_virtual_network_swift_connection" "PesGpTx" {
  for_each = {
    for s in var.appServMap : "${s.palier_key}.${s.slot}" => s
  }
  app_service_id = azurerm_app_service.serviceY[each.key].id
  subnet_id      = var.subnetId
}
```

### Debug Output

https://gist.github.com/kinwolfqc/612fb40a9e692216f4e5b1a59995939a
### Expected Behaviour
Applying the plan should succeed and the vnet integration should work.

### Actual Behaviour

It takes over 6m trying to ceate the ressource, but it eventually fails every time.  
### Steps to Reproduce

1. `terraform apply`
2. that's it.

### Important Factoids

None
### References

* #0000

**Comment by aristosvo** [comment]
Hi @kinwolfqc ! Can you explain what exactly you are trying to accomplish here? Is this something you've tried manually as well? As per [Microsoft Docs](https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet#regional-vnet-integration) there are some limitations on this kind of connection, I've highlighted the options most probable to be violated:

- You can't reach resources across global peering connections.
- The feature is available from all App Service scale units in Premium V2 and Premium V3. It is also available in Standard but only from newer App Service scale units. If you are on an older scale unit you can only use the feature from a Premium V2 App Service plan. If you want to be certain of being able to use the feature in a Standard App Service plan, create your app in a Premium V3 App Service plan. Those plans are only supported on our newest scale units. You can scale down if you desire after that.
- **The integration subnet can be used by only one App Service plan.**
- The feature can't be used by Isolated plan apps that are in an App Service Environment.
- The feature requires an unused subnet that's a /28 or larger in an Azure Resource Manager VNet.
- **The app and the VNet must be in the same region.**
- You can't delete a VNet with an integrated app. Remove the integration before you delete the VNet.
- You can only integrate with VNets in the same subscription as the app.
- **You can have only one regional VNet Integration per App Service plan. Multiple apps in the same App Service plan can use the same VNet.**
- You can't change the subscription of an app or a plan while there's an app that's using regional VNet Integration.
- Your app cannot resolve addresses in Azure DNS Private Zones without configuration changes

**Comment by kinwolfqc** [comment]
Hi,  basically only trying to add the App Service to a vNet.  It works when doing it manually.

We are compiant with everything listed, but I just saw something...  It seems that to be able to work through the API(which terraform must use I guess) it requires a delegation on the targeted subnet within the vNet that doesn't seem required when doing it manually.  I'll try to test today with the delegation set and see if that is the problem.

**Comment by aristosvo** [comment]
Nice, good to hear. Didn't remember that trick, but it's been a while.

If you're having problems with setting subnet delegation via TF, #5975 has a nice example how an other user implemented it.

**Comment by kinwolfqc** [comment]
It was the delegation.  Closing this.
