### ISSUE TITLE
Terraform is not adding tags to network interfaces created by other resource.

### ISSUE THREAD

**Issue by namratasuresh** [terraform-providers/terraform-provider-azurerm#9365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I am creating several private endpoints through Terraform and also updating the tags as required. But, the Terraform doesn't add tags to the NIC which it creates with endpoint. Is there any way to overcome this?

### Terraform (and AzureRM Provider) Version

terraform {
  required_version = ">= 0.13"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.0"
    }
  }
  backend "azurerm" {
  }
}

### Affected Resource(s)

* `azurerm_private_endpoint`

### Terraform Configuration Files

data "azurerm_resource_group" "keyvault" {
  name     = var.resource_group_name
}

resource "azurerm_key_vault" "keyvault" {
  name                            = var.keyvault_name
  location                        = data.azurerm_resource_group.keyvault.location
  resource_group_name             = data.azurerm_resource_group.keyvault.name
  enabled_for_disk_encryption     = true
  enabled_for_deployment          = true
  enabled_for_template_deployment = false 
  tenant_id                       = var.keyvault_tenant_id
  sku_name                        = "standard"
  
  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
  }

  tags = var.resource_tags
}

data "azurerm_resource_group" "privatelink" {
  name     = var.privatelink_resource_group_name
}

data "azurerm_subnet" "privatelink" {
  name                 = "PrivateLink"
  virtual_network_name = var.vnet_name
  resource_group_name  = var.vnet_resource_group_name
}

resource "azurerm_private_endpoint" "keyvault" {
  name                      = "PRIVATELINK-KV-${upper(azurerm_key_vault.keyvault.name)}"
  resource_group_name       = data.azurerm_resource_group.privatelink.name
  location                  = data.azurerm_resource_group.privatelink.location
  subnet_id                 = data.azurerm_subnet.privatelink.id
  tags = var.resource_tags
  
  private_service_connection {
    name                           = azurerm_key_vault.keyvault.name
    private_connection_resource_id = azurerm_key_vault.keyvault.id
    is_manual_connection           = false
    subresource_names              = ["Vault"]
  }
}

### Debug Output

Creates NIC associated with Private endpoint. But, doesn't add tags.

### Expected Behaviour

Expecting Terraform to add same tags to NIC as the Private Endpoint.

### Actual Behaviour

Creates NIC associated with Private endpoint. But, doesn't add tags.

### Steps to Reproduce

Create a private endpoint for a resource through Terraform.

**Comment by tombuildsstuff** [comment]
hi @namratasuresh 

Thanks for opening this issue.

Taking a look through this appears to be an issue with the Terraform Configuration but unfortunately there's not enough information above for us to be able to ascertain the specific issue here - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
