### ISSUE TITLE
Add tags to Azure Private DNS Zones with ":"

### ISSUE THREAD

**Issue by namratasuresh** [terraform-providers/terraform-provider-azurerm#9366]
I am looking do something similar to this. Add tags to DNS Zones with ":"
Is there any way to achieve this?

_Originally posted by @namratasuresh in https://github.com/terraform-providers/terraform-provider-azurerm/issues/6129#issuecomment-729154534_

**Comment by tombuildsstuff** [comment]
hi @namratasuresh 

Thanks for opening this issue.

This API bug is being tracked in #6129 - rather than having multiple issues open tracking the same thing I'm going to close this one in favour of that one, would you mind subscribing to that issue for updates?

Thanks!
