### ISSUE TITLE
Azure provider - NetApp

### ISSUE THREAD

**Issue by sudev5678** [terraform-providers/terraform-provider-azurerm#9369]
Creating an **azurerm_netapp_volume** from a snapshot. 

Currently, we are able to create a new Azure NetApp Files volume, however, I don't see an option to create a new volume from a previous snapshot. 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/netapp_volume
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/netapp_snapshot

**Comment by tombuildsstuff** [comment]
hi @sudev5678 

Thanks for opening this issue.

At this time creating a NetApp Volume from a snapshot isn't supported - if you're interested in support for doing so, then [please open a feature request containing all the necessary information](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) and we can take a look.

Thanks!
