### ISSUE TITLE
azurerm_frontdoor_custom_https_configuration with error code="CustomDomainSecureDeliveryKeyVaultCustomDomainHostnameNotIncluded"

### ISSUE THREAD

**Issue by naikajah** [terraform-providers/terraform-provider-azurerm#9397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.12.26`

Azurerm provider version

`2.23.0`

### Affected Resource(s)

* `azurerm_frontdoor_custom_https_configuration `

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor_custom_https_configuration" "enable-https" {	
  for_each = {	
    for frontend in var.frontends : frontend.name => frontend	
  }	
  frontend_endpoint_id              = "/subscriptions/${var.subscription_id}/resourcegroups/${azurerm_frontdoor.main.resource_group_name}/providers/Microsoft.Network/frontdoors/${azurerm_frontdoor.main.name}/frontendendpoints/${each.value["name"]}"	
  resource_group_name               = azurerm_frontdoor.main.resource_group_name	
  custom_https_provisioning_enabled = lookup(each.value, "enable_ssl", true)	
  dynamic "custom_https_configuration" {	
    for_each = lookup(each.value, "enable_ssl", true) ? [1] : []	
    content {	
      certificate_source                         = var.ssl_mode	
      azure_key_vault_certificate_vault_id       = var.ssl_mode == "AzureKeyVault" ? data.azurerm_key_vault.certificate_vault.id : null	
      azure_key_vault_certificate_secret_name    = var.ssl_mode == "AzureKeyVault" ? data.azurerm_key_vault_secret.certificate[each.value["name"]].name : null	
      azure_key_vault_certificate_secret_version = var.ssl_mode == "AzureKeyVault" ? data.azurerm_key_vault_secret.certificate[each.value["name"]].version : null	
    }	
  }	
}
```

### Debug Output

`Error: unable to update Custom HTTPS configuration for Frontend Endpoint "XXXXX" (Resource Group "XXXXX"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "XXXXX" (Resource Group "XXXXX"): waiting to enable Custom Domain HTTPS for Frontend Endpoint: Code="CustomDomainSecureDeliveryKeyVaultCustomDomainHostnameNotIncluded" Message="The certificate doesn't include the hostname to be secured."`

### Expected Behaviour

The certificate should be applied as it gets applied successfully when done directly from the portal

### Actual Behaviour

I get the following error message

`Error: unable to update Custom HTTPS configuration for Frontend Endpoint "XXXXX" (Resource Group "XXXXX"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "XXXXX" (Resource Group "XXXXX"): waiting to enable Custom Domain HTTPS for Frontend Endpoint: Code="CustomDomainSecureDeliveryKeyVaultCustomDomainHostnameNotIncluded" Message="The certificate doesn't include the hostname to be secured."`

There seems to be a discrepancy in the way certificates are applied to frontdoor via portal and via terraform. 
 
* #0000

**Comment by tombuildsstuff** [comment]
hi @naikajah 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Terraform Configuration, where as the API is returning via this error, the Certificate doesn't appear to include the hostname that this is being bound too?

Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I'd suggest double-checking the hostnames on the certificate, but should you require further assistance I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by naikajah** [comment]
@tombuildsstuff Terraform configuration is correct as per the terraform plan output. Terraform plan does say what certificate terraform is going to apply. Certificate does include the hostname otherwise should it not provide the same error when applying through portal?
