### ISSUE TITLE
azurerm_private_endpoint doesn't work with private dns zone

### ISSUE THREAD

**Issue by nvaklinov** [terraform-providers/terraform-provider-azurerm#9408]
I have created a mysql server with disabled public access. 
I am trying to create a private endpoint that connects this mysql with a vnet and then a private dns record.
Doing that on the UI everything works as expected. Doing it from the terraform fails to create an A record in the zone and even if I manually create the A record still doesn't work. It seems to me that there are some internal Azure associations that I don't see and can't control. Here is the code:

esource "azurerm_private_endpoint" "pe_mysql" {
  name                = "private_endpoint_mysql_qac"
  location            = azurerm_resource_group.rg_qac.location
  resource_group_name = azurerm_resource_group.rg_qac.name
  subnet_id           = azurerm_subnet.subnet1.id

  private_service_connection {
    name                           = "private_endpoint_mysql_qac"
    private_connection_resource_id = azurerm_mysql_server.server.id
    subresource_names              = ["mysqlServer"]
    is_manual_connection           = false
  }
  private_dns_zone_group  {
    name                 = azurerm_private_dns_zone.pz_pe_mysql.name
    private_dns_zone_ids = [azurerm_private_dns_zone.pz_pe_mysql.id]
  }
}

resource "azurerm_private_dns_zone" "pz_pe_mysql" {
  name                = "privatelink.mysql.database.azure.net"
  resource_group_name = azurerm_resource_group.rg_qac.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "pl_pe_mysql" {
  name                  = "privatelink-vnet-mysql"
  resource_group_name   = azurerm_resource_group.rg_qac.name
  private_dns_zone_name = azurerm_private_dns_zone.pz_pe_mysql.name
  virtual_network_id    = azurerm_virtual_network.vnet.id
}

After spinning up all of these I can see the private_endpoint as well as the private dns zone and everything seems to be right except the fact that is missing the A record. The odd thing is that with the same code worked once and then it stopped no matter how many times I redeployed. I am also spinning up two additional private endpoints from which 1 is successfully creating the A record but the rest just won't.

Terraform v0.13.5
Azure provider: 2.20.0

**Comment by xenalite** [comment]
I ran into a similar problem on 2.46.1. I was deploying a private endpoint for an event hub namespace `abc`.
I created private DNS zone `abc.privatelink.servicebus.windows.net` and linked it to the private endpoint.
This did not create an A record set. I expected `@` record set to be created.

I then created private DNS zone `privatelink.servicebus.windows.net` and linked it to the same private endpoint.
Re-running the terraform apply created A record set with correct private IP value.

Obviously the latter case stops you from talking over public IP to any other event hub namespace which has a private endpoint enabled.

**Comment by tombuildsstuff** [comment]
hi @nvaklinov 

Thanks for opening this issue - apologies for the delayed review here!

Taking a look through this appears to be a question regarding Terraform Configuration rather than a bug in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [on the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
