### ISSUE TITLE
Feature Request: Support for Shared Access Policies for ServiceBus Namespaces

### ISSUE THREAD

**Issue by scottrangerio** [terraform-providers/terraform-provider-azurerm#941]
Hey all,

Similar to https://github.com/terraform-providers/terraform-provider-azurerm/issues/735, it would be great to see support for shared access policies on a service bus namespace level 

https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/namespaces/authorizationrules

**Comment by Lucretius** [comment]
@tombuildsstuff I believe this was solved by https://github.com/terraform-providers/terraform-provider-azurerm/pull/1498

**Comment by tombuildsstuff** [comment]
@Lucretius agreed, thanks for the heads up 👍
