### ISSUE TITLE
Error deleting a VM linked to a backend address pool association (reopening)

### ISSUE THREAD

**Issue by edwardsp** [terraform-providers/terraform-provider-azurerm#9412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v1.44.0
```

### Affected Resource(s)

* azurerm_network_interface_backend_address_pool_association
* azurerm_virtual_machine

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.33"
}

variable "prefix" {
  default = "tfvmex"
}

resource "azurerm_resource_group" "test" {
  name     = "paul-example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "example-pip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
}

resource "azurerm_lb" "test" {
  name                = "example-lb"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  frontend_ip_configuration {
    name                 = "primary"
    public_ip_address_id = azurerm_public_ip.test.id
  }
}

resource "azurerm_lb_backend_address_pool" "test" {
  resource_group_name = azurerm_resource_group.test.name
  loadbalancer_id     = azurerm_lb.test.id
  name                = "acctestpool"
}

resource "azurerm_network_interface" "test" {
  name                = "example-nic"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = azurerm_subnet.test.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_network_interface_backend_address_pool_association" "test" {
  #depends_on              = [azurerm_virtual_machine.main]
  network_interface_id    = azurerm_network_interface.test.id
  ip_configuration_name   = "testconfiguration1"
  backend_address_pool_id = azurerm_lb_backend_address_pool.test.id
}

resource "azurerm_virtual_machine" "main" {
  #depends_on            = [azurerm_network_interface_backend_address_pool_association.test]
  name                  = "${var.prefix}-vm"
  location              = azurerm_resource_group.test.location
  resource_group_name   = azurerm_resource_group.test.name
  network_interface_ids = [azurerm_network_interface.test.id]
  vm_size               = "Standard_DS1_v2"

  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
  storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  os_profile {
    computer_name  = "hostname"
    admin_username = "testadmin"
    admin_password = "Password1234!"
  }
  os_profile_linux_config {
    disable_password_authentication = false
  }
  tags = {
    environment = "staging"
  }
}
```

### Expected Behaviour

The resources can be successfully created and terraform apply and deleted with terraform destroy.

### Actual Behaviour

`terraform destroy` failed with:

```
Error: Error waiting for removal of Backend Address Pool Association for NIC "example-nic" 
(Resource Group "paul-example-resources"): Code="OperationNotAllowed" Message="Operation 
'startTenantUpdate' is not allowed on VM 'tfvmex-vm' since the VM is marked for deletion. You 
can only retry the Delete operation (or wait for an ongoing one to complete)." Details=[]
```

This problem is only occurring when the `azurerm_network_interface_backend_address_pool_association` and the `azurerm_virtual_machine` are deleted **at the same time**.  One workaround is to add a dependency - but this is not really the correct solution as either of these can be deleted first, i.e. setting `azurerm_network_interface_backend_address_pool_association` to depend on `azurerm_virtual_machine` or vice versa both work.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #4330

**Comment by tombuildsstuff** [comment]
hi @edwardsp 

At this point in time the older `azurerm_virtual_machine` resource has been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Since the older `azurerm_virtual_machine` resource has fallen out of sync from the behaviour of the Azure API, to avoid unintentionally breaking users relying on this behaviour the older resources are feature-frozen.

As this resource is feature-frozen to maintain compatibility, I'm going to close this issue for the moment - but I'd recommend instead checking out the `azurerm_linux_virtual_machine` resource, which better represents how the Azure API behaves for this resource, but if this is still an issue in the newer resources then please let us know and we'll take another look.

Thanks!
