### ISSUE TITLE
app_service_environment v3

### ISSUE THREAD

**Issue by derekrprice** [terraform-providers/terraform-provider-azurerm#9420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform 0.12.24
* azurerm 2.37

### Affected Resource(s)

* `azurerm_app_service_environment`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_environment" "default" {
  name                         = "ase-v3-example"
  subnet_id                    = azurerm_subnet.default.id
  pricing_tier                 = "I1v2"
  front_end_scale_factor       = 10
  internal_load_balancing_mode = "Web, Publishing"
}
```

### Expected Behaviour

Creates an ASE v3 instance.

### Actual Behaviour

`expected pricing_tier to be one of [I1 I2 I3], got I1v2`

### Steps to Reproduce

1. `terraform apply`

### References

ASE v3 is in public preview as of Nov 1: https://docs.microsoft.com/en-us/azure/app-service/environment/creation

* #0000

**Comment by jackofallops** [comment]
Hi @derekrprice - ASEv3 isn't currently supported by the provider, but it's something I'm already looking into. If the preview looks stable and the Azure Go SDK supports it, we'll try to include it as soon as we can.
