### ISSUE TITLE
Role assignment api version is not in supported list

### ISSUE THREAD

**Issue by cehoffman** [terraform-providers/terraform-provider-azurerm#943]
### Terraform Version

`0.11.3`

### Affected Resource(s)

- azurerm_role_assignment

### Terraform Configuration Files
```hcl
resource "azurerm_role_assignment" "function-app" {
  name               = "${uuid()}"
  scope              = "${data.azurerm_subscription.dev.id}/resourceGroup/Hackathon"
  role_definition_id = "${azurerm_role_definition.function-app.id}"
  principal_id       = "${azuread_guest_user.shelley_bess.id}"

  lifecycle {
    ignore_changes = ["name"]
  }
}
```

### Debug Output

```
* azurerm_role_assignment.function-app: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2015-07-01' is invalid. The supported versions are '2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

### Expected Behavior
What should have happened?

A role assignment was created

### Actual Behavior
What actually happened?

An exception was thrown

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

We are deploying this to East US 2 and have logs from successful role assignment with 1.1.2 version on Feb. 26th. We tried with 1.2.0, 1.0.1, and 1.0.0. All with the same error.

**Comment by cehoffman** [comment]
Turns out the problem is that the scope was invalid. There was a missing `s` on `resourceGroup`. The error message though is absolutely awful for detecting that.

**Comment by tombuildsstuff** [comment]
hey @cehoffman 

Thanks for opening this issue.

> Turns out the problem is that the scope was invalid. There was a missing s on resourceGroup. The error message though is absolutely awful for detecting that.

Yeah, I had a feeling this was the case - but was waiting to take a look at this with a fresh pair of eyes this morning; unfortunately with the mis-spelling it ends up at another API (which is where the error about the wrong API version comes from). In general to work around this we'd suggest making use of [the `azurerm_resource_group` data source](https://www.terraform.io/docs/providers/azurerm/d/resource_group.html) and scoping like so:

```
data "azurerm_resource_group" "test" {
  name = "dsrg_test"
}

resource "azurerm_role_assignment" "function-app" {
  name               = "${uuid()}"
  scope              = "${data.azurerm_resource_group.test.id}"
  # ...
}
```

Given this is an issue with the way the Azure API works (and unfortunately as this field is extremely generic, it's not something that Terraform can easily fix) - I'm going to close this issue for the moment; however please feel free to re-open it if you're still having issues and we'll take another look.

Thanks!
