### ISSUE TITLE
Availability set and PlatformFaultDomainCount

### ISSUE THREAD

**Issue by FrenchBen** [terraform-providers/terraform-provider-azurerm#944]
Trying to deploy on Azure within the wrong region could have some severe consequences. 
For example, using the West Central US, will lead to errors when using the availability set defaults

### Terraform Version
`Terraform v0.11.3`

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_availability_set

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "test" {
  name     = "resourceGroup1"
  location = "West US"
}

resource "azurerm_availability_set" "test" {
  name                = "acceptanceTestAvailabilitySet1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  tags {
    environment = "Production"
  }
}
```

### Debug Output
```
[ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred: azurerm_availability_set.vm: compute.AvailabilitySetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The specified fault domain count 3 must fall in the range 1 to 2."
```

### Expected Behavior
The azure plugin should be smart enough to figure out what the fault domain count is. Or an API endpoint should be available for the plugin to determine what the proper `platform_update_domain_count` and `platform_fault_domain_count` should be. 

### Actual Behavior
Your code failed, because you didn't know that Azure has limitations, that are semi-poorly referenced here:
https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/managed-disks-common-fault-domain-region-list.md

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` (using one of the regions listed above with only 2 Fault Domain

**Comment by tombuildsstuff** [comment]
hey @FrenchBen 

Thanks for opening this issue :)

Unfortunately I don't believe there's an API which exposes this information; which means I believe the best we can do at this point in time is to document this limitation. I've opened #976 which references the document you've referred too, which should at least notify others about this limitation - however should an API become available in the future we can investigate something more dynamic here.

Thanks!
