### ISSUE TITLE
Support for publicNetworkAccess property on resource azurerm_data_factory

### ISSUE THREAD

**Issue by dinedal** [terraform-providers/terraform-provider-azurerm#9445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This optional property allows setting the Data Factory to block public connections and only allow connections over private links.

As per https://docs.microsoft.com/en-us/azure/data-factory/data-factory-private-link the non-TF way to do it is to issue the following patch request to the resource:

```
PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataFactory/factories/{factoryName}?api-version= 2018-06-01
{    "properties": {
       "publicNetworkAccess":"Disabled"
   }
}
```

* azurerm_data_factory

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory" "dataFactory" {
  name                = "example-dataFactory"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  public_network_access_enabled = false
}
```

### References

* https://docs.microsoft.com/en-gb/azure/data-factory/data-factory-private-link
* https://docs.microsoft.com/en-gb/rest/api/datafactory/factories/createorupdate#factory

**Comment by judaondo** [comment]
Yes, that would be pretty useful
