### ISSUE TITLE
Azurerm_metric_alertrules tag $type is treated as changed after apply

### ISSUE THREAD

**Issue by yzhang-myob** [terraform-providers/terraform-provider-azurerm#945]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.2
+ provider.template v1.0.0

### Affected Resource(s)
- azurerm_metric_alertrule

### Terraform Configuration Files
```hcl
resource "azurerm_metric_alertrule" "critical_cpu" {
  count               = "${length(local.cpu_critical_rule) > 0 ? length(var.resource_names) : 0}"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.location}"

  name        = "${var.resource_names[count.index]}-cpu-critical"
  description = "CPU is high (>${local.cpu_critical_rule[0]}), please check for a potential auto-scaling issue"
  enabled     = true

  resource_id = "${var.resource_ids[count.index]}"
  metric_name = "Percentage CPU"
  operator    = "GreaterThan"
  threshold   = "${local.cpu_critical_rule[0]}"
  aggregation = "${local.cpu_critical_rule[1]}"
  period      = "${local.cpu_critical_rule[2]}"

  email_action {
    send_to_service_owners = false

    custom_emails = "${local.critical_notification_emails}"
  }

  tags = "${merge(var.tags, map("metric", "CPU", "level", "critical"))}"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
When plan metric alert, the tags should be exactly the number of tags I set via tags property. Tag $type should be treated as unchanged.

### Actual Behavior
Tags $type been treated as changed. 

      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "9" => "8"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

**Comment by metacpp** [comment]
@yzhang-myob I could not see tags.$type in my plan. Can you share more details about your var.tags ?

**Comment by yzhang-myob** [comment]
@metacpp I did't see it in my plan. I saw it after you applying the resource, and then plan or refresh state again. Like I said, if you created the resource with customised tag, apply and re-run the plan. You will see it as change

**Comment by metacpp** [comment]
@yzhang-myob can you share the value of customized tag with me ?

**Comment by yzhang-myob** [comment]
Sure. 
project            = "my-project"
service            = "my-service"
applicationVersion = "1.0.0"

**Comment by yzhang-myob** [comment]
@metacpp To be more helpful, this is the current state:

```
id                                    =  <id>
aggregation                           = Average
description                           = CPU is high (>90), please check for a potential auto-scaling issue
email_action.#                        = 1
email_action.0.custom_emails.#        = 2
email_action.0.custom_emails.0        = <email>
email_action.0.custom_emails.1        = <email2>
email_action.0.send_to_service_owners = false
enabled                               = true
location                              = southeastasia
metric_name                           = Percentage CPU
name                                  = api-cpu-critical
operator                              = GreaterThan
period                                = PT5M
resource_group_name                   = api
resource_id                           = <resourceId>
tags.$type                            = Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage
tags.%                                = 9
tags.environment                      = prod
tags.level                            = critical
tags.metric                           = CPU
tags.nation                           = SME
tags.project                          = myproject
tags.service                          = myservice
tags.team                             = myteam
tags.tribe                            = mytribe
threshold                             = 90
webhook_action.#                      = 0
```

if I run plan again:

```
~ module.sea_alert_rules.azurerm_metric_alertrule.critical_cpu
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "9" => "8"
```

**Comment by metacpp** [comment]
@yzhang-myob Is 0.11.3 the version used in your case ?

**Comment by yzhang-myob** [comment]
@metacpp 0.11.5 for terraform now

**Comment by tombuildsstuff** [comment]
@metacpp FYI there's [a filter which removes the `$type` tag from the `webhook_action.0.properties`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_metric_alertrule.go#L264) - I guess we're going to need a similar filter for the `tags` object on this resource?

**Comment by metacpp** [comment]
I can reproduce it with this [configuration](https://gist.github.com/metacpp/49962970f2a181971e0e0efc4e22e664):

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_metric_alertrule.critical_cpu
      tags.$type: "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.WindowsAzure.Management.Common.Storage" => ""
      tags.%:     "9" => "8"


Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by tombuildsstuff** [comment]
hey @yzhang-myob 

Just to let you know that v1.4.0 of the Azure Provider has been released which includes the fix for this :)

Thanks!

**Comment by yzhang-myob** [comment]
Thank you @tombuildsstuff . I can confirm it is fixed. 👍
