### ISSUE TITLE
azurerm_cosmosdb_account with zone_redundant = true errors on minor updates (e.g. change tags)

### ISSUE THREAD

**Issue by mnjhey** [terraform-providers/terraform-provider-azurerm#9463]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.37.0

### Affected Resource(s)
* "azurerm_cosmosdb_account"

### Terraform Configuration Files

```
resource "azurerm_resource_group" "debug_resource_group" {
  name     = "rg-debug"
  location = var.location
}

resource "azurerm_cosmosdb_account" "debug" {
  name                = "mn-cosmos-debug"
  location            = azurerm_resource_group.debug_resource_group.location
  resource_group_name = azurerm_resource_group.debug_resource_group.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = false

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = azurerm_resource_group.debug_resource_group.location
    zone_redundant = true  
    failover_priority = 0
  }

  tags = {
      Role      = "ChangedToNewValue"
  }

}
```

### Debug Output
https://gist.github.com/mnjhey/01ac1b8b629cd26f0bd6280ae634265e

### Expected Behaviour

The value of the "Role" tag should have been changed to "ChangedToNewValue".   This does not error if you update the tag value through the console.

### Actual Behaviour
Looking at the debug log, Terraform is calling a PUT against `/subscriptions/cc40dd1c-a034-4332-b88b-40d9131cb5db/resourceGroups/rg-debug/providers/Microsoft.DocumentDB/databaseAccounts/mn-cosmos-debug?api-version=2020-04-01`  with ```{"kind":"MongoDB","location":"westeurope","properties":{"consistencyPolicy":{"defaultConsistencyLevel":"BoundedStaleness","maxStalenessPrefix":100000,"maxIntervalInSeconds":300},"locations":[{"failoverPriority":0,"locationName":"West Europe"}],"databaseAccountOfferType":"Standard","ipRules":[],"isVirtualNetworkFilterEnabled":false,"enableAutomaticFailover":false,"capabilities":[{"name":"EnableMongo"}],"virtualNetworkRules":[],"enableMultipleWriteLocations":false,"publicNetworkAccess":"Enabled","enableFreeTier":false},"tags":{"Project":"DebugProject","Role":"ChangedToNewValue1"}}```

This returns a 400 error with {"code":"BadRequest","message":"Zone redundancy cannot be changed for existing region West Europe. Please remove and re add the region, to change Zone redundancy on the region.\r\nActivityId: a1fd9772-1c32-40a4-b972-4923a234a4aa, Microsoft.Azure.Documents.Common/2.11.0"}

The non-debug Terraform error is.
```
Error: Error updating CosmosDB Account "mn-cosmos-debug" properties (Resource Group "rg-debug"): Error creating/updating CosmosDB Account "mn-cosmos-debug" (Resource Group "rg-debug"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Zone redundancy cannot be changed for existing region West Europe. Please remove and re add the region, to change Zone redundancy on the region.\r\nActivityId: a1fd9772-1c32-40a4-b972-4923a234a4aa, Microsoft.Azure.Documents.Common/2.11.0"
```

### Steps to Reproduce

1. `terraform apply`  
2. Change the value of the tag
3. `terraform apply` 

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account

**Comment by mnjhey** [comment]
Attempting to debug this further, I wonder if the issue is that "PUT" request contains
 `"locations":[{"failoverPriority":0,"locationName":"West Europe"}]`
ie. it's missing the `"isZoneRedundant": "boolean"` 
https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/2020-04-01/databaseaccounts

**Comment by mnjhey** [comment]
I've not done any Go development but I wonder if it might be that oldLocations doesn't seem to read the Zone Redundancy setting https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/cosmos/cosmosdb_account_resource.go#L499-L502 which is then passed in at L526 ?

**Comment by kvendingoldo** [comment]
I'm trying to fix it in my fork, but it's difficult to test :(
https://github.com/kvendingoldo/terraform-provider-azurerm/commit/365274aea3e4f7e4baa6d6fcbbac20b989d14b46

**Comment by kvendingoldo** [comment]
MR is here https://github.com/terraform-providers/terraform-provider-azurerm/pull/9485

**Comment by kvendingoldo** [comment]
Test result:

```
  TF_ACC=1 go test -v ./azurerm/internal/services/cosmos -run=TestAccAzureRMCosmosDBAccount_zoneRedundant_update_mongo -timeout 60m -ldflags="-X=github.com/terraform-providers/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccAzureRMCosmosDBAccount_zoneRedundant_update_mongo
=== PAUSE TestAccAzureRMCosmosDBAccount_zoneRedundant_update_mongo
=== CONT  TestAccAzureRMCosmosDBAccount_zoneRedundant_update_mongo
--- PASS: TestAccAzureRMCosmosDBAccount_zoneRedundant_update_mongo (2174.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/cosmos      2178.383s
```

**Comment by kvendingoldo** [comment]
@mbfrahry @ztbrown can you check it, please?

**Comment by mnjhey** [comment]
Thanks kvendingoldo.  That's quick work!
