### ISSUE TITLE
Terraform try to destroy Netapp pool before destroy volumes !

### ISSUE THREAD

**Issue by Kumoservices** [terraform-providers/terraform-provider-azurerm#9479]
Hello,

When i launch a destroy on my netapp files, terraform tried to destroy pool before theirs volumes.

**Error Message :**
_azurerm_netapp_pool.default[0]: Destroying... [id=/subscriptions/f364a072-1b9e-44fe-9257-0f72021ed3e7/resourceGroups/som-nas-trs-rgp-nas-001/providers/Microsoft.NetApp/netAppAccounts/somnastrsnac001/capacityPools/services]

Error: Error deleting NetApp Pool "services" (Resource Group "som-nas-trs-rgp-nas-001"): netapp.PoolsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="CannotDeleteResource" Message="Can not delete resource before nested resources are deleted."_

**Provider and Terraform Versions used :**
Azurerm version : 2.37.0
Terraform version : 0.13.4

**Source :**

```terraform

resource "azurerm_netapp_account" "default" {
  name                = "${var.entity}${var.short_app_code}${var.environment}nac001"
  resource_group_name = azurerm_resource_group.default.name
  location            = azurerm_resource_group.default.location

  active_directory {
    username            = var.ad_user
    password            = data.azurerm_key_vault_secret.terraform_adds_admin_password.value
    smb_server_name     = var.smb_server
    dns_servers         = [var.ad_dns1, var.ad_dns2]
    domain              = var.domain
    organizational_unit = var.ad_ou
  }
}

resource "azurerm_netapp_pool" "default" {
  count               = length(var.netapp_pool)
  name                = var.netapp_pool[count.index]
  account_name        = azurerm_netapp_account.default.name
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
  service_level       = lookup(var.netapp_pool_sla, var.netapp_pool[count.index])
  size_in_tb          = lookup(var.netapp_pool_size, var.netapp_pool[count.index])
}

resource "azurerm_netapp_volume" "services" {
  count               = length(var.netapp_services_volume)
  name                = var.netapp_services_volume[count.index]
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
  account_name        = azurerm_netapp_account.default.name
  pool_name           = azurerm_netapp_pool.default.0.name               # .0. for "services" Pool (see tfvars file)
  volume_path         = lookup(var.netapp_services_volume_path, var.netapp_services_volume[count.index])
  service_level       = azurerm_netapp_pool.default.0.service_level      # .0. for "services" Pool (see tfvars file)
  protocols           = [lookup(var.netapp_services_volume_protocol, var.netapp_services_volume[count.index])]
  subnet_id           = data.azurerm_subnet.default.id
  storage_quota_in_gb = lookup(var.netapp_services_volume_quota, var.netapp_services_volume[count.index])

 lifecycle {
    prevent_destroy = false
  }

}

# Manages a NetApp Snapshot.
resource "azurerm_netapp_snapshot" "services" {
  count               = length(var.netapp_services_volume)
  name                = "${var.entity}-${var.short_app_code}-${var.environment}nss-${lookup(var.netapp_services_volume, count.index)}"
  account_name        = azurerm_netapp_account.default.name
  pool_name           = azurerm_netapp_pool.default.0.name
  volume_name         = azurerm_netapp_volume.services.*.name[count.index]
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
}
```

Thanks for your help

**Comment by tombuildsstuff** [comment]
hi @Kumoservices 

Thanks for opening this issue.

Taking a look through this appears to be a question regarding Terraform Configuration - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by Kumoservices** [comment]
hello, 

Are you sure of this ? 
because destroy-plan cycle graph do not appears azurerm_netapp_volume in the destroy cycle ... 
In my mind it's really tried destroy pool without considering volumes...

Command use for graph is : terraform graph -verbose -draw-cycles -type=plan-destroy | dot -Tsvg > graph.svg

Regards
