### ISSUE TITLE
Azurerm_search_service should allow CIDR blocks in the allowed_ips section

### ISSUE THREAD

**Issue by tpyle** [terraform-providers/terraform-provider-azurerm#9488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform v0.13.4
azurerm v2.37.0

### Affected Resource(s)

* `azurerm_search_service`

### Terraform Configuration Files

```hcl
resource "azurerm_search_service" "ss" {
    name = "example-search-service"
    resource_group_name = "example-rg"
    location = "westus2"
    sku = "basic"
    public_network_access_enabled = false
    allowed_ips = ["1.2.3.0/24", "2.3.0.0/16"]
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behaviour

The resource should have been created successfully, as per [the documentation](https://docs.microsoft.com/en-us/azure/search/service-configure-firewall) and the portal, which indicate that CIDR blocks are allowed in the network rules

### Actual Behaviour

The provider throws an error that the CIDR block is an invalid IP address:
Error: "allowed_ips.0" is not a valid IPv4 address

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Hopes the [fix ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/9493)would be helpful.
