### ISSUE TITLE
Support ADLS Gen 2 Premium for azurerm_storage_account

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#9528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Support Premium tier for Azure Data Lake Storage.
Currently --> 
is_hns_enabled - (Optional) Is Hierarchical Namespace enabled? This can be used with Azure Data Lake Storage Gen 2 (see here for more information). Changing this forces a new resource to be created.
NOTE:
When this is set to true the account_tier argument must be set to **Standard**

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "adls" {
  name                     = "myadlsacccountname"
  resource_group_name      = "myrgname"
  location                 = "westeurope"
  account_kind             = "BlockBlobStorage"
  account_tier             = "Premium"
  account_replication_type = "LRS"
  is_hns_enabled           =  true

  #Security Best Practice
  min_tls_version           = "TLS1_2"
  enable_https_traffic_only = "true"

}
```

### References

* Creation procedure through the portal, PowerShell or AZ CLI available [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-create-account-block-blob?WT.mc_id=DP-MVP-5003548)

**Comment by dhirschfeld** [comment]
When I tried this I got the below error:
```
Error: Error creating Azure Storage Account: storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestPropertyValue" Message="The value 'True' is not allowed for property isHnsEnabled. For more information, see - https://aka.ms/storageaccounthns"
```

I was able to fix it by changing `account_kind` to `BlockBlobStorage` from `StorageV2`. Is it correct that `Premium`/`HNS` storage isn't supported for `StorageV2` accounts?

**Comment by JamesDLD** [comment]
Hi @dhirschfeld ,
yes it's by design, you can refer to this doc [Enabling the premium performance tier](https://docs.microsoft.com/en-us/azure/storage/blobs/premium-tier-for-data-lake-storage?WT.mc_id=DP-MVP-5003548#enabling-the-premium-performance-tier) for info.
"You can use the premium tier for Azure Data Lake Storage by creating a BlockBlobStorage account with the Hierarchical namespace setting enabled."
Jamesdld

**Comment by dhirschfeld** [comment]
Thanks for the clarification @JamesDLD! If my understanding is correct then I think https://github.com/terraform-providers/terraform-provider-azurerm/pull/10225 might help make that clear in the docs.
