### ISSUE TITLE
Create virtual network rule for Azure SQL service

### ISSUE THREAD

**Issue by bostonmoto** [terraform-providers/terraform-provider-azurerm#955]
Hi there,

A new feature just came out I believe a couple of months ago in azure to create a virtual network rule which allows subets in a virtual network to communicate with Azure SQL.

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-overview

You can also add a "virtual network" to the SQL server through the portal or powershell.

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-vnet-service-endpoint-rule-powershell

I do not see any support yet in terraform for adding a vnet rule to an azure SQL server - Can we add support for this by any chance? Right now I have to manually add the virtual network rule from the console to allow my servers to talk to the Azure SQL in a secure manner. Is this something we can get added to terraform? Please let me know if any other details needed.

cc: @tombuildsstuff 

Thanks!

**Comment by tombuildsstuff** [comment]
hey @bostonmoto 

Thanks for opening this issue :)

Just to let you know that support for SQL Virtual Network Rules was added in #978 which [has been released as part of v1.3.1](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.3.1/CHANGELOG.md) and is now available [on the Terraform Website](https://www.terraform.io/docs/providers/azurerm/r/sql_virtual_network_rule.html) - as such I'm going to close this issue :)

Thanks!
