### ISSUE TITLE
azurerm_security_center_automation continuous export integration not working for eventhubs

### ISSUE THREAD

**Issue by pratiksharma-dev** [terraform-providers/terraform-provider-azurerm#9565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.0
Provider registry.terraform.io/hashicorp/azurerm v2.37.0

### Affected Resource(s)

* `azurerm_security_center_automation`

### Terraform Configuration Files

data "azurerm_eventhub_namespace" "eventhub" {
  name                = "petest22"
  resource_group_name = "group-ingress-eastus2-dev"
}

resource "azurerm_eventhub_authorization_rule" "authrule" {
  name                = "asc"
  namespace_name      = "petest22"
  eventhub_name       = "test"
  resource_group_name = "group-ingress-eastus2-dev"
  listen              = false
  send                = true
  manage              = false
}

resource "azurerm_security_center_automation" "export" {
  name                = "export-logs"
  location            = "eastus2"
  resource_group_name = "group-ingress-eastus2-dev"

  action {
    type              = "EventHub"
    resource_id       = data.azurerm_eventhub_namespace.eventhub.id
    connection_string = azurerm_eventhub_authorization_rule.authrule.primary_connection_string
  }

  source {
    event_source = "Alerts"
    rule_set {
      rule {
        property_path  = "properties.metadata.severity"
        operator       = "Equals"
        expected_value = "High"
        property_type  = "String"
      }
    }
  }

  scopes = ["/subscriptions/${data.azurerm_client_config.current.subscription_id}"]
}
### Debug Output

Terraform run completes successfully but there is no change on Azure security center continuous export settings, but resource is created in azure

![image](https://user-images.githubusercontent.com/11813857/100613119-02060200-333a-11eb-82fc-51801173a5cc.png)

![image](https://user-images.githubusercontent.com/11813857/100613204-295ccf00-333a-11eb-819e-6b1de3593f41.png)

**Comment by pratiksharma-dev** [comment]
Hello contributors, 

Unable to get a response to this issue since yesterday, can you help out?

 @tombuildsstuff @katbyte

**Comment by pratiksharma-dev** [comment]
@njuCZ @tombuildsstuff 

Can you look into this issue?

**Comment by njuCZ** [comment]
@pratiksharma-dev duplicated as #9975, I have replied in that thread

**Comment by pratiksharma-dev** [comment]
Thanks @njuCZ will test and let you 👍
