### ISSUE TITLE
azurerm_monitor_diagnostic_setting from categories on elastic pool

### ISSUE THREAD

**Issue by dlm69** [terraform-providers/terraform-provider-azurerm#9568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
azurerm v2.38.0

### Affected Resource(s)

* azurerm_mssql_elasticpool
* azurerm_monitor_diagnostic_categories
* azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "default" {
  name                = var.elasticpool_name
  resource_group_name = azurerm_resource_group.default.name
  location            = azurerm_resource_group.default.location
  server_name         = azurerm_mssql_server.default.name
  max_size_gb         = var.elasticpool_max_size_gb
  lifecycle {
    prevent_destroy = true
  }

  sku {
    name     = var.elasticpool_sku_name
    tier     = var.elasticpool_sku_tier
    family   = var.elasticpool_sku_family
    capacity = var.elasticpool_sku_cores
  }

  per_database_settings {
    min_capacity = var.elasticpool_db_min
    max_capacity = var.elasticpool_db_max
  }

  tags = {
    Environment = local.environment_name
    Application = local.application_name_tag
  }
}

data "azurerm_monitor_diagnostic_categories" "elasticpool" {
  resource_id = azurerm_mssql_elasticpool.default.id
}

resource "azurerm_monitor_diagnostic_setting" "elasticpool" {
  name                       = "LogAnalytics"
  target_resource_id         = azurerm_mssql_elasticpool.default.id
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.oms.id

  dynamic "log" {
    iterator = log_category
    for_each = data.azurerm_monitor_diagnostic_categories.master.logs

    content {
      category = log_category.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 0
      }
    }
  }

  dynamic "metric" {
    iterator = metric_category
    for_each = data.azurerm_monitor_diagnostic_categories.master.metrics

    content {
      category = metric_category.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 0
      }
    }
  }
}

```

### Expected Behaviour

I would've expected the azurerm_monitor_diagnostic_categories to bring back the correct logs and metrics. In this case there are no logs just metrics and it seems 'WorkloadManagement' is no longer supported.

### Actual Behaviour

Error: Error creating Monitor Diagnostics Setting "LogAnalytics" for Resource "/subscriptions/xxxx-xxxx-xxxx-xxx/resourceGroups/myresourcegroup/providers/Microsoft.Sql/servers/mysqlserver/elasticPools/myelasticpool": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Metric category 'WorkloadManagement' is not supported."

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @dlm69 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
