### ISSUE TITLE
Feature Request: Support the WriteAccelerator property on datadisks

### ISSUE THREAD

**Issue by anandramakrishna** [terraform-providers/terraform-provider-azurerm#959]
### Affected Resource(s)
- azurerm_compute_virtual_machine

### References
See azure-sdk-for-go/services/compute/mgmt/2017-12-01/compute/models.go for information about the WriteAccelerator property.

**Comment by anandramakrishna** [comment]
@katbyte I was reviewing your PR and observed that this is set to default to "true".  I don't think that's correct, as that would be a change for existing terraform deployments. 

We should make the default be "false" for this .

**Comment by katbyte** [comment]
Hi @anandramakrishna, 

Thank you for taking a look 🙂

Currently the property is optional, so I believe if it is left out it will be false and not enable the feature. Currently I can not fully test this PR as it is in public preview and I don't think our subscription is whitelisted, I haven't checked yet.

**Comment by anandramakrishna** [comment]
I can get your subscription whitelisted if necessary.  Please let me (or others at MS) know which one.

**Comment by tombuildsstuff** [comment]
@anandramakrishna based on your message, is this functionality invite-only at this point; or can users self-register for it?

**Comment by anandramakrishna** [comment]
Let me follow-up on this.  I'll get back to you.

**Comment by anandramakrishna** [comment]
I've enabled your subscription.  Users will be able to use it publicly without needing whitelisting in another week (approximately).

**Comment by katbyte** [comment]
Hey @anandramakrishna,

Just wanted to provide an update: We are currently waiting for capacity on our subscription so we can test and run acceptance tests. Once we have quote and can verify everything works as expected we can merge an close this out.

**Comment by BAnbalagan** [comment]
Hi 
Please let me know how to use it, I can test it.

**Comment by katbyte** [comment]
Hi @BAnbalagan,

Thank you for the offer but not only do we need confirm it works, we need a way to continuously test it going forward as changes are made to the resource.

**Comment by katbyte** [comment]
Hey @anandramakrishna, @BalaAnbalagan,

Just wanted to let you know this has been included in 1.7 and releases today.

**Comment by BalaAnbalagan** [comment]
Awesome
