### ISSUE TITLE
The api-version '2018-05-01' used to deploy the template does not support 'Scope' property. 

### ISSUE THREAD

**Issue by blueboxes** [terraform-providers/terraform-provider-azurerm#9595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When I create a policy using azurerm_policy_definition that has a deployIfNotExists step that deploys a resource lock all works fine. 

If I extend this to add a scope (needed when a remediation task is run across a subscription)  I get the error "The api-version '2018-05-01' used to deploy the template does not support 'Scope' property." although the scope is part of "2016-09-01" lock spec specified. 

```
"resources": [
                            {
                                "type": "Microsoft.Authorization/locks",
                                "apiVersion": "2016-09-01",
                                "name": "[parameters('resourceName')]",
                                "scope": "[resourceId(parameters('resourceGroup'),parameters('resourceType'), parameters('resourceName')]",
                                "properties": {
                                    "level": "CanNotDelete",
                                    "notes": "Lock applied by Azure Policy"
                                }
                            }
                        ]
```

I believe AzureRM is using '2018-05-01' with the policy creation which is causing this issue.

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
AzureRM v2.37.0

### Affected Resource(s)
 
* `azurerm_policy_definition`

### Expected Behaviour

Scope should be supported and the script executed

### Actual Behaviour

When I run a remediation task with the policy the following error is shown.

The api-version '2018-05-01' used to deploy the template does not support 'Scope' property. Please use api-version '2019-05-01' or later to deploy the template. Please see https://aka.ms/arm-template/#resources for usage details.'.

### Steps to Reproduce

1. Create a new policy with a deployIfNotExists step that deploys a resource lock 
1. Ensure scope is added to the new lock
1. Assign the policy
1. Create a resource group with non-compliant
1. Create a remediation task using the policy

**Comment by tombuildsstuff** [comment]
hi @blueboxes 

Taking a look into this it appears that Terraform is using API version `2019-09-01` from version `2.14.0` of the Provider onwards ([introduced in this commit](https://github.com/terraform-providers/terraform-provider-azurerm/commit/6db45cd402a908c7305fdca886f32d15ed570b48)) - and the Template Deployment resources use API version `2020-06-01`
