### ISSUE TITLE
Azure Virtual Network Subnet Block requires and disallows ID being provided in .tf.json files.

### ISSUE THREAD

**Issue by hdpoe** [terraform-providers/terraform-provider-azurerm#9613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0
```

### Affected Resource(s)

`azurerm_virtual_network`
*subnet nested block specifically*

### Terraform Configuration Files

```hcl
[
    {
        "resource": {
            "azurerm_resource_group": {
                "big_e_rg": {
                    "name": "mork_rg",
                    "location": "westus2"
                }
            }
        }
    },
    {
        "resource": {
            "azurerm_virtual_network": {
                "gork_vnet": {
                    "address_space": [
                        "10.0.0.0/16"
                    ],
                    "location": "westus2",
                    "name": "gork_vnet",
                    "resource_group_name": "mork_rg",
                    "subnet": [
                        {
                            "address_prefix": "10.0.0.0/24",
                            "name": "cunning_brutality",
                            "security_group": ""
                        }
                    ]
                }
            }
        }
    }
]
```

### Debug Output

https://gist.github.com/hdpoe/2c05b309d5188dff34406977bd64a6cd

### Panic Output

N/A

### Expected Behaviour

A Vnet would be created with the name `gork_vnet` and a subnet within it called `cunning_brutality`

### Actual Behaviour

I get the following error when running validate, plan, or apply. 

```
Error: Incorrect attribute value type

  on main.tf.json line 22, in [1].resource.azurerm_virtual_network.gork_vnet:
  22:                     "subnet": [
  23:                         {
  24:                             "address_prefix": "10.0.0.0/24",
  25:                             "name": "cunning_brutality",
  26:                             "security_group": ""
  27:                         }
  28:                     ]

Inappropriate value for attribute "subnet": element 0: attribute "id" is
required.
```

If the id attribute is added to the subnet sub-object the following error is produced

```
Error: "subnet.0.id": this field cannot be set

  on main.tf.json line 30, in [1].resource.azurerm_virtual_network.gork_vnet:
  30:                 }
```

### Steps to Reproduce

1. Create a terraform file JSON config file like that has an array of subnets nested within the `azurerm_virtual_network` JSON object.
2. Run a `terraform validate` or a `terraform plan` or a `terraform apply`

### Important Factoids

- This issue only appears if one tries to create a JSON Terraform config, in a standard .tf config file this issue does not manifest.
- The documentation provided by Terraform on how JSON resources are to be configured (https://www.terraform.io/docs/configuration/syntax-json.html#nested-block-mapping) indicates that the subnet block should actually appear as the following

```hcl
           "resource": {
            "azurerm_virtual_network": {
                "gork_vnet": {
                    "address_space": [
                        "10.0.0.0/16"
                    ],
                    "location": "westus2",
                    "name": "gork_vnet",
                    "resource_group_name": "mork_rg",
                    "subnet": [
                        { "cunningly_burtal": 
                          {
                              "id": "brutal_cunning",
                              "address_prefix": "10.0.0.0/24",
                              "name": "cunning_brutality",
                              "security_group": ""
                          }
                        }
                    ]
                }
            }
        }
```

But when this configuration is used the following error is produced

```
Error: Incorrect attribute value type

  on main.tf.json line 22, in [1].resource.azurerm_virtual_network.gork_vnet:
  22:                     "subnet": [
  23:                         { "cunningly_burtal":
  24:                           {
  25:                               "address_prefix": "10.0.0.0/24",
  26:                               "name": "cunning_brutality",
  27:                               "security_group": ""
  28:                           }
  29:                         }
  30:                     ]

Inappropriate value for attribute "subnet": element 0: attributes
"address_prefix", "id", "name", and "security_group" are required.
```
### References
StackOverflow question that provides more context: https://stackoverflow.com/questions/65100723/terraform-json-requires-an-azure-subnet-that-is-nested-in-an-azure-vnet-object-t

**Comment by tombuildsstuff** [comment]
hi @hdpoe 

Thanks for opening this issue - apologies for the delayed response here.

Taking a look through here unfortunately this is due to an issue within Terraform Core, where the "Blocks as Attributes" mode isn't correctly supported in the JSON syntax - as such when using the JSON syntax you will need to specify all of the fields (using `null` as a value) which should solve this, more information can be found in this issue: https://github.com/hashicorp/terraform/issues/27673#issuecomment-773756416.

Thanks!
