### ISSUE TITLE
Support for custom_data when using azurerm_kubernetes_cluster_node_pool to create dynamic node pools

### ISSUE THREAD

**Issue by thpang** [terraform-providers/terraform-provider-azurerm#9633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking for the ability to pass in `custom_data`, either as a base script or cloud-init script to setup system level items on every node.

Where `custom_data` is passed into the `azurerm_linux_virtual_machine_scale_set` which, then would pass this into the vm's created by this scale_set as the cluster grows shrinks.

**NOTE:** The `custom_data` field will have the same restrictions on type as defined in the `azurerm_linux_virtual_machine_scale_set` resource.

The benefit of having this value passed in keeps one from creating a daemon set or other post infra setup script in the cluster to perform system level commands on each node. Now it's part of the infra stood up by terraform and is easily maintained.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "autoscale_node_pool" {
  count                        = var.enable_auto_scaling ? 1 : 0
  name                         = var.node_pool_name
  kubernetes_cluster_id        = var.aks_cluster_id
  vnet_subnet_id               = var.vnet_subnet_id
  availability_zones           = var.availability_zones
  proximity_placement_group_id = var.proximity_placement_group_id == "" ? null : var.proximity_placement_group_id
  vm_size                      = var.machine_type
  os_disk_size_gb              = var.os_disk_size
  enable_auto_scaling          = var.enable_auto_scaling
  node_count                   = var.node_count
  max_count                    = var.max_nodes
  min_count                    = var.min_nodes
  node_labels                  = var.node_labels
  node_taints                  = var.node_taints
  tags                         = var.tags

  custom_data                  = var.cloud_init

  lifecycle {
    ignore_changes = [node_count]
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @thpang 

Thanks for opening this issue.

Based on what I can see unfortunately the AKS API doesn't expose a means of customizing this functionality at this time - as such I'm going to suggest [opening an issue on the AKS Repository](https://github.com/Azure/AKS/issues) where somebody from that team should be able to comment as to their plans here.

Since this functionality is dependent on the functionality being available in the AKS API, I'm going to close this issue for the moment however should this become available in the APU, then we can investigate adding support for this to Terraform in the future.

Thanks!
