### ISSUE TITLE
Subsequent runs of azurerm_mssql_database and azurerm_mssql_database_extended_auditing_policy result in an error regarding server ID being incorrect

### ISSUE THREAD

**Issue by faisaleem-na** [terraform-providers/terraform-provider-azurerm#9655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.13.4
2.38.0

### Affected Resource(s)

azurerm_mssql_database
azurerm_mssql_database_extended_auditing_policy

### Terraform Configuration Files

resource "azurerm_mssql_database" "db" {
  for_each                        = var.databases
  name                            = each.value.name
  server_id                       = data.azurerm_mssql_server.sqlserver[each.key].id
  collation                       = each.value.collation 
  license_type                    = each.value.licensetype 
  max_size_gb                     = each.value.maxsizegb
  read_scale                      = each.value.readscale
  sku_name                        = each.value.skuname 
  zone_redundant                  = each.value.zoneredundant
  create_mode                     = each.value.createmode
  creation_source_database_id     = each.value.createmode == "copy" ? data.azurerm_mssql_database.sqldb[each.key].id : null
  elastic_pool_id                 = data.azurerm_mssql_elasticpool.elp[each.key].id
  min_capacity                    = each.value.mincap
  tags                            = each.value.tags

  threat_detection_policy {
    state                        = lookup(each.value.tdpolicy, "state", null)
    disabled_alerts              = lookup(each.value.tdpolicy, "disabled_alerts", null )
    email_addresses              = lookup(each.value.tdpolicy, "emailadds", null )
    retention_days               = lookup(each.value.tdpolicy, "retentiondays", null )
  }

  short_term_retention_policy {
      retention_days             = lookup(each.value.stbkp, "retention_days", null )
  }

  long_term_retention_policy {
    weekly_retention             = lookup(each.value.ltbkp, "weekly", null )
    monthly_retention            = lookup(each.value.ltbkp, "monthly", null )
    yearly_retention             = lookup(each.value.ltbkp, "yearly", null )
    week_of_year                 = lookup(each.value.ltbkp, "week_of_year", null )
  }

}

resource "azurerm_mssql_database_extended_auditing_policy" "mssql_ext_audit" {
  for_each = {
      for k, r in var.databases : k => r
      if contains(keys(r), "auditpol")
    }
  database_id                             = azurerm_mssql_database.db[each.key].id
  storage_endpoint                        = data.azurerm_storage_account.sa[each.key].primary_blob_endpoint
  storage_account_access_key              = data.azurerm_storage_account.sa[each.key].primary_access_key
  storage_account_access_key_is_secondary = false
  retention_in_days                       = lookup(each.value.auditpol, "retention_days", null)
}

### Expected Behaviour

auditing policy should be created/applied when resource created and in subsequent runs should do nothing if unchanged or adjust if changed

### Actual Behaviour

even without making any changes, in subsequent applies the below error occurs:

Error: failure in issuing create/update request for SQL Database "database_name" Blob Auditing Policies(SQL Server "SQL server_name"/ Resource Group "my_resource_group"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingNoServerIdentity" Message="The server identity is not correctly configured on server 'SQL server_name'. Please re-configure Identity on the server."

### Steps to Reproduce

re-run the terraform configuration

**Comment by tombuildsstuff** [comment]
hi @faisaleem-na 

Thanks for opening this issue.

Taking a look through this appears to be an issue with the Terraform Configuration being used, rather than an issue specific to the Azure Provider. This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by faisaleem-na** [comment]
> hi @faisaleem-na
> 
> Thanks for opening this issue.
> 
> Taking a look through this appears to be an issue with the Terraform Configuration being used, rather than an issue specific to the Azure Provider. This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).
> 
> Thanks!

Hi,
thanks for the reply
can i just ask if there is something in particular that leads you to believe that this is an issue with configuration?
as to me it doesnt make sense why the configuration would run successfully on the first run but then fail on subsequent runs?
thanks

**Comment by GrooveGod** [comment]
Hi @faisaleem-na - Were you able to find a work-around for this?  I'm seeing it too.  Difference is, I'm using the older resource for sql database `azurerm_sql_database` with the new one, `azurerm_mssql_database_extended_auditing_policy`.  
Terraform v0.12.29 / provider.azurerm v2.40.0

**Comment by faisaleem-na** [comment]
> Hi @faisaleem-na - Were you able to find a work-around for this? I'm seeing it too. Difference is, I'm using the older resource for sql database `azurerm_sql_database` with the new one, `azurerm_mssql_database_extended_auditing_policy`.
> Terraform v0.12.29 / provider.azurerm v2.40.0

Afraid not!
at the moment I'm just applying the audit the first run then commenting it out all subsequent runs, but that's not a solution and I am still only at testing phase so not a big deal at the moment.
if you figure it out please let me know, and vice versa I will do the same
thanks
