### ISSUE TITLE
Upgrade go sdk version from v48.1.0 to latest one

### ISSUE THREAD

**Issue by neil-yechenwei** [terraform-providers/terraform-provider-azurerm#9683]
Could you help to upgrade go sdk package to latest one since some new properties require new go sdk package?

**Comment by tombuildsstuff** [comment]
@neil-yechenwei due to the breaking changes in SDK v49 - and the larger changes currently on-going - it's likely this won't be upgraded for a couple of weeks to avoid conflicts.

Would you be able to provide a link to the Github issues tracking the features/use-cases being solved by upgrading here?

Thanks!

**Comment by neil-yechenwei** [comment]
Sure.
1. The `[ExpressionEvaluationOptions](https://github.com/Azure/azure-sdk-for-go/blob/v49.0.0/services/resources/mgmt/2020-06-01/resources/models.go#L727)` property in azurerm_resource_group_template_deployment requires new go sdk package.
2. The `[EventGroupingSettings](https://github.com/Azure/azure-sdk-for-go/blob/c760106e3c564f57cd7d264c872bc5ef324c592f/services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/models.go#L12187)` property in azurerm_sentinel_alert_rule_scheduled requires new go sdk package.
3. The `[queryString](https://github.com/Azure/azure-rest-api-specs/blob/7184ee0b5506063fd3c800cc2e08f31ca88333e6/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L4486)` property in azurerm_resource_group_template_deployment requires new go sdk package. This property currently isn't released to `azure-sdk-for-go` repo. Once it's released, terraform side also needs to upgrade go sdk package to involve this property.

**Comment by tombuildsstuff** [comment]
@neil-yechenwei can we add Github issues to track the use-cases we're looking to solve by adding these new fields? Thanks!

**Comment by neil-yechenwei** [comment]
Add github issue link https://github.com/terraform-providers/terraform-provider-azurerm/issues/9722 for queryString property.
Add github issue link https://github.com/terraform-providers/terraform-provider-azurerm/issues/9723 for ExpressionEvaluationOptions property.
