### ISSUE TITLE
Support for EngineV3 in kusto_cluster

### ISSUE THREAD

**Issue by kosinsky** [terraform-providers/terraform-provider-azurerm#9695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kusto aka ADX announced public preview of EngineV3: "Kusto EngineV3 is Azure Data Explorer’s next generation storage and query engine. It's designed to provide unparalleled performance for ingesting and querying telemetry, logs, and time series data."

EngineType is a new property of [ClusterProperties](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/kusto/mgmt/2020-09-18/kusto#ClusterProperties) in 2020-09-18 of the Kusto API that allows to choose engine type during cluster creation.

### New or Affected Resource(s)

* azurerm_kusto_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kusto_cluster" "test" {
  name                = "acctestkc%s"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    name     = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }
  engine			  = "V3"
}
```

### References

* https://docs.microsoft.com/en-us/azure/data-explorer/engine-v3

**Comment by jrauschenbusch** [comment]
@kosinsky @mbfrahry  I think this feature is now implemented and this ticket can be closed.

**Comment by kosinsky** [comment]
Yeas. It's done
