### ISSUE TITLE
Error reading Throughput on Cosmos Mongo Collection for Serverless CosmosDb 

### ISSUE THREAD

**Issue by IvanPranovich** [terraform-providers/terraform-provider-azurerm#9697]
AzureRm provider supports creation of Serverless CosmosDb with Mongo API but fails refreshing state for azurerm_cosmosdb_mongo_collection. Azure does not support Throughput parameter for Serverless CosmosDb with MongoAPI. 

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5
provider registry.terraform.io/hashicorp/azurerm v2.39.0

### Affected Resource(s)

* azurerm_cosmosdb_mongo_collection
* azurerm_cosmosdb_account (kind=MongoDb, capabilities=EnableMongo+EnableServerless

### Terraform Configuration Files

provider "azurerm" {
  environment     = "public"
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "testgroup"
  location = "eastus"
}

resource "azurerm_cosmosdb_account" "cosmodaccount" {
  name                = "todelete-test-cosmosdb-random"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  capabilities {
    name = "EnableMongo"
  }
  capabilities {
    name = "EnableServerless"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 10
    max_staleness_prefix    = 200
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}

resource "azurerm_cosmosdb_mongo_database" "cosmosdb" {
  name                = "testname"
  resource_group_name = azurerm_cosmosdb_account.cosmodaccount.resource_group_name
  account_name        = azurerm_cosmosdb_account.cosmodaccount.name
}

resource "azurerm_cosmosdb_mongo_collection" "proposals" {
  name                = "testcollection"
  resource_group_name = azurerm_cosmosdb_account.cosmodaccount.resource_group_name
  account_name        = azurerm_cosmosdb_account.cosmodaccount.name
  database_name       = azurerm_cosmosdb_mongo_database.cosmosdb.name

  default_ttl_seconds = "0"
  shard_key           = "shardKey"

  index {
    keys   = ["_id"]
    unique = true
  }
}
```

### Debug Output

Error: Error reading Throughput on Cosmos Mongo Collection "testname" (Account: "todelete-test-cosmosdb", Database: "testname"): documentdb.MongoDBResourcesClient#GetMongoDBCollectionThroughput: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Message: {\"code\":\"BadRequest\",\"message\":\"Reading or replacing offers is not supported for serverless accounts.\\, Microsoft.Azure.Documents.Common/2.11.0\"}, Request URI: /offers, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.11.0"


### Expected Behaviour

MongoCollection for serverless CosmosDb (in preview) does not support throughtput for databases/collections. Azure does not return throughput parameter at refreshing the state (and ignores it during creation). azurerm_cosmosdb_mongo_collection fails during refresh. 

### Actual Behaviour

"terraform refresh" produces error:
Error: Error reading Throughput on Cosmos Mongo Collection "testname" (Account: "todelete-test-cosmosdb", Database: "testname"): documentdb.MongoDBResourcesClient#GetMongoDBCollectionThroughput: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Message: {\"code\":\"BadRequest\",\"message\":\"Reading or replacing offers is not supported for serverless accounts.\\, Microsoft.Azure.Documents.Common/2.11.0\"}, Request URI: /offers, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.11.0"

### Steps to Reproduce

1. `terraform apply --auto-approve`
2. terraform refresh

**Comment by FreyMo** [comment]
Can confirm this even with Release 2.43.0.

**Comment by OisinKyne** [comment]
Can confirm this issue is still present in release `2.44.0`. Also identified in https://github.com/terraform-providers/terraform-provider-azurerm/issues/9417#issuecomment-757514223 by @nomoarbleh

**Comment by OisinKyne** [comment]
Is there any chance a maintainer could take a look at this PR which seems to address this bug? Unaddressed for 3+ weeks now. https://github.com/terraform-providers/terraform-provider-azurerm/pull/10389 🙏
