### ISSUE TITLE
CosmosDB database and container missing option to use the same throughput

### ISSUE THREAD

**Issue by joaocpribeiro** [terraform-providers/terraform-provider-azurerm#9705]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.14.0
azurerm version: 2.31.0

### Affected Resource(s)

* `azurerm_cosmosdb_sql_database`
* `azurerm_cosmosdb_sql_container`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_sql_database" "cosmosdb_database" {
  name                = "${var.projectname}-sql-db"
  resource_group_name = data.azurerm_resource_group.rg.name
  account_name        = azurerm_cosmosdb_account.cosmosdb_account.name
  throughput = 400
}

resource "azurerm_cosmosdb_sql_container" "cosmosdb_container_users" {
  name                = "users"
  resource_group_name = data.azurerm_resource_group.rg.name
  account_name        = azurerm_cosmosdb_account.cosmosdb_account.name
  database_name       = azurerm_cosmosdb_sql_database.cosmosdb_database.name
  partition_key_path  = "/PostCode"
  throughput = 400
}
```

### Debug Output

[Does not apply]

### Panic Output

[Does not apply]

### Expected Behaviour

It should be possible to set that a container should not use dedicated throughput.
It should also be possible to set that a database does not have provisioned throughput.

As mentioned in the documentation (https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#set-throughput-on-a-database):
> When you provision throughput on an Azure Cosmos database, the throughput is shared across all the containers (called shared database containers) in the database. An exception is if you specified a provisioned throughput on specific containers in the database.

### Actual Behaviour

Using terraform, one always need to set the provisioned throughput in the database and in the containers.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

[Does not apply]

### References

[Does not apply]

### Notes

I wrote a question about it in Hashicorp (as suggested when creating a question  in GitHub), but I got no feedback so far:
https://discuss.hashicorp.com/t/azurerm-cosmosdb-sql-container-without-dedicated-throughput/18411

**Comment by phatcher** [comment]
@joaocpribeiro If you look at the documentation is says...

`A container with provisioned throughput cannot be converted to shared database container. Conversely a shared database container cannot be converted to have a dedicated throughput.`

So the allocation of throughput is a creation time decision, so what I've done in my modules is to have two variables...

* autoscale: This must be set upon creation otherwise it cannot be updated without a manual terraform destroy-apply
* throughput: Throughput of the container, default 0, shares database throughtput, treated as max-throughput if autoscale set

And then I have three conditional resources...  `auto`, `throughput` and `shared`

**Comment by joaocpribeiro** [comment]
@phatcher , thank you for the reply. Two things to point out:

1. As far as I can see in [terraform docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_sql_container), the default value of the throughput is 400, and not 0, for both database and containers.

2. Your comment does not properly answer my issue. My issue is that we have to set the provisioned throughput for both database and containers, even though Microsoft documentation states that it should be possible to not set any provisioned throughput.

**Comment by phatcher** [comment]
@joaocpribeiro I think you are missing the point from the that throughput is **optional**. If you don't set it, at the database level, then you cannot subsequently set it, and similar for a container.

So, creating a database with no throughput is...

```
resource "azurerm_cosmosdb_sql_database" "z" {
  name                = "mydb"
  account_name        = var.cosmos_account.name
  resource_group_name = var.cosmos_account.resource_group_name
}
```

However, I think it won't work not setting throughput at the container level, if you surrounding database does not have a throughput value, and my current understanding is it it's better to put autoscale on the database at say 4000 which will cost a min of 400 RU and then only allocate container values if you actually need to. That way the majority of containers are running under your shared provision

**Comment by joaocpribeiro** [comment]
@phatcher You are fully right, I missed that.
I would also add this info to the documentation, but that's another story.
Thank you for the solution!

**Comment by scottgn** [comment]
There may still be an issue with this unless I'm missing something, simplest steps to reproduce:

1. Create a cosmos sql database in the portal, (do not provision throughput)
2. Import into terraform
3. The next plan wants to update the throughput from 0 -> 400, even if throughput is not present on the resource.
