### ISSUE TITLE
Add property to document required providers when using azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by sharebear** [terraform-providers/terraform-provider-azurerm#9714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using `azurerm_resource_group_template_deployment` there is no way for terraform to know which providers are necessary to successfully apply the deployment. This means that when running terraform in a locked-down production environment with the `skip_provider_registration` feature enabled terraform has no way to identify which providers could be needed within the template, potentially resulting in an error message such as the following.

```
Error: waiting for creation of Template Deployment "eventgrid-deployment" (Resource Group "<redacted>"): Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"MissingSubscriptionRegistration\",\r\n    \"message\": \"The subscription is not registered to use namespace 'Microsoft.EventGrid'. See https://aka.ms/rps-not-found for how to register subscriptions.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"MissingSubscriptionRegistration\",\r\n        \"target\": \"Microsoft.EventGrid\",\r\n        \"message\": \"The subscription is not registered to use namespace 'Microsoft.EventGrid'. See https://aka.ms/rps-not-found for how to register subscriptions.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]
```

Would it be an idea to add a `required_providers` list to the resource that the azurerm provider could use to identify dependent providers?

Alternatively could this be an explicit resource type?

### New or Affected Resource(s)

* azurerm_resource_group_template_deployment
* azurerm_subscription_template_deployment

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group_template_deployment" "main" {
  name                = "eventgrid-deployment"
  resource_group_name = var.resource_group_name
  deployment_mode     = "Incremental"
  required_providers  = ["Microsoft.EventGrid"]   # <--- NEW ARGUMENT HERE
  template_content    = <<TEMPLATE
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.EventGrid/systemTopics",
            "apiVersion": "2020-04-01-preview",
            "name": "mytopic",
            "location": "${var.location}",
            "properties": {
                "source": "${azurerm_storage_account.mysa.id}",
                "topicType": "Microsoft.Storage.StorageAccounts"
            }
        },
        {
            "type": "Microsoft.EventGrid/systemTopics/eventSubscriptions",
            "apiVersion": "2020-04-01-preview",
            "name": "[concat('mytopic', '/mysubscription')]",
            "dependsOn": [
                "[resourceId('Microsoft.EventGrid/systemTopics', 'mytopic')]"
            ],
            "properties": {
                "destination": {
                    "properties": {
                        "resourceId": "[concat('${azurerm_function_app.myfunction.id}', '/functions/my-trigger')]",
                        "maxEventsPerBatch": 1,
                        "preferredBatchSizeInKilobytes": 64
                    },
                    "endpointType": "AzureFunction"
                },
                "filter": {
                    "includedEventTypes": ["Microsoft.Storage.BlobCreated"],
                    "subjectBeginsWith": "/blobServices/default/containers/mycontainer/"
                },
                "labels": [],
                "eventDeliverySchema": "EventGridSchema",
                "retryPolicy": {
                    "maxDeliveryAttempts": 30,
                    "eventTimeToLiveInMinutes": 1440
                }
            }
        }
    ]
}
TEMPLATE
}
```

**Comment by sharebear** [comment]
Additional notes:
* This issue was the first problem I hit leading to feature request #9713
* I'm only using this template while waiting for #9141

**Comment by sharebear** [comment]
I just saw in the release notes that [azurerm_resource_provider_registration](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7951) was merged, coupled with a `depends_on` to ensure the correct ordering, that could solve this use-case.

Leaving the issue open for now in case someone else sees why this might not work as I expect.

**Comment by katbyte** [comment]
closing as this appears to have been fixed
