### ISSUE TITLE
azurerm_storage_data_lake_gen2_path ace block always shows changes

### ISSUE THREAD

**Issue by stuartmelroseqbe** [terraform-providers/terraform-provider-azurerm#9728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0

### Affected Resource(s)

* `azurerm_storage_data_lake_gen2_path`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "<rg name>"
  location = "<location>"
  tags     = {<tags>}
}

resource "azurerm_storage_account" "example" {
  name                     = "<sa name>"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = <location>
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = "true"
  tags     = {}
}

resource "azurerm_storage_data_lake_gen2_filesystem" "example" {
  name               = "filesystem01"
  storage_account_id = azurerm_storage_account.example.id
}
resource "azurerm_storage_data_lake_gen2_path" "example" {
  path               = "directory01"
  filesystem_name    = azurerm_storage_data_lake_gen2_filesystem.example.name
  storage_account_id = azurerm_storage_account.example.id
  resource           = "directory"

  ace {
    id          = "<object id>"
    permissions = "rwx"
    scope       = "access"
    type        = "user"
  }
}
```

### Expected Behaviour

Can apply and reapply without any shown changes if none are made

### Actual Behaviour

The statefile shows multiple 'ace' blocks that were not defined as part of the path resource (assume these are defaults set in the background by terraform). On reapply it picks this up and shows multiple changes to the path resource, removing the 'ace' blocks that weren't defined by us

```hcl
Terraform will perform the following actions:

  # azurerm_storage_data_lake_gen2_path.example will be updated in-place
  ~ resource "azurerm_storage_data_lake_gen2_path" "example" {
        filesystem_name    = "filesystem01"
        group              = "<object id>"
        id                 = "https://<sa name>.dfs.core.windows.net/filesystem01/directory01"
        owner              = "<object id>"
        path               = "directory01"
        resource           = "directory"
        storage_account_id = "<sa id>"

      ~ ace {
          + id          = "<object id>"
            permissions = "rwx"
            scope       = "access"
            type        = "user"
        }
      - ace {
          - id          = "<object id>" -> null
          - permissions = "rwx" -> null
          - scope       = "access" -> null
          - type        = "user" -> null
        }
      - ace {
          - permissions = "r-x" -> null
          - scope       = "access" -> null
          - type        = "group" -> null
        }
      - ace {
          - permissions = "rwx" -> null
          - scope       = "access" -> null
          - type        = "mask" -> null
        }
      - ace {
          - permissions = "---" -> null
          - scope       = "access" -> null
          - type        = "other" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` - This when done after the initial apply shows changes to be made

**Comment by ross-p-smith** [comment]
There are other access control entries that make up the list. In your example, you have only defined the one you wanted to add, you will need to specify the full list of ACE that are needed, and in the CORRECT order to prevent a plan from triggering when re-run. I have copied what we have successfully used and we do not get any planned changes.

NB - in our example here we had multiple security groups with different permissions that we were assigning to a path (each.key). You could probably remove the loop if you just have a single group you are assigning.

resource "azurerm_storage_data_lake_gen2_path" "path" {
  storage_account_id = var.storage_account_id
  filesystem_name    = var.file_system
  for_each           = local.folders_sorted_permissions
  path               = each.key
  resource           = "directory"
  #
  # When the ACL is written to Datalake, the service puts the entries in a standard order.
  # Reading back the ACL returns the values in the standard order/
  # By replicating that order here we avoid making updates to the permissions when not needed.
  #
  # The order seems to be:
  #  - access scope comes before default
  #  - then the order is user, group, mask, other
  #  - then sorted by id (with blank first)
  #

  ace {
    # no id => owning user (i.e. deployment account)
    permissions = "rwx"
    scope       = "access"
    type        = "user"
  }
  ace {
    permissions = "---"
    scope       = "access"
    type        = "group"
  }
  dynamic "ace" {
    for_each = [for permission in each.value.permissions : { scope = "access", type = "group", id = permission.security_group_id, permissions = permission.ace_permissions }]
    content {
      id          = ace.value["id"]
      permissions = ace.value["permissions"]
      type        = ace.value["type"]
      scope       = ace.value["scope"]
    }
  }
  ace {
    permissions = "rwx"
    scope       = "access"
    type        = "mask"
  }
  ace {
    permissions = "---"
    scope       = "access"
    type        = "other"
  }

  ace {
    permissions = "---"
    scope       = "default"
    type        = "user"
  }
  ace {
    permissions = "---"
    scope       = "default"
    type        = "group"
  }
  dynamic "ace" {
    for_each = [for permission in each.value.permissions : { scope = "default", type = "group", id = permission.security_group_id, permissions = permission.ace_permissions }]
    content {
      id          = ace.value["id"]
      permissions = ace.value["permissions"]
      type        = ace.value["type"]
      scope       = ace.value["scope"]
    }
  }
  ace {
    permissions = "rwx"
    scope       = "default"
    type        = "mask"
  }
  ace {
    permissions = "---"
    scope       = "default"
    type        = "other"
  }
}

**Comment by stuartmelroseqbe** [comment]
Thanks @ross-p-smith, good to know the ordering. I did try setting them like this before but wasn't sure on the ordering so it was still tracking as changes! I've tried it out as above and looks like it's behaving as expected. I will close this issue as I believe this has solved what I was looking for
