### ISSUE TITLE
Changing the node_labels in azurerm_kubernetes_cluster_node_pool should not force replacement

### ISSUE THREAD

**Issue by khaldoune** [terraform-providers/terraform-provider-azurerm#9730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
`Terraform v0.14.0-rc1`  `azurerm v2.36.0`

### Affected Resource(s)
`azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```
variable "aks-nodepools" {
  type = map(object({
    nodepool-name        = string
    vm-size              = string
    node-count           = number
    aks-usernp-autoscale = bool
    availability-zones   = list(string)
    max-count            = number
    min-count            = number
    node-labels          = map(string)
    max-pods             = number
  }))
  description = "AKS nodepools to provision"
  default     = {}
}

resource "azurerm_kubernetes_cluster_node_pool" "nodepools" {
  for_each              = var.aks-nodepools
  name                  = each.value.nodepool-name
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks2.id
  vm_size               = each.value.vm-size
  node_count            = each.value.node-count
  vnet_subnet_id        = data.azurerm_subnet.aks-nodes-snet.id
  availability_zones    = each.value.availability-zones
  enable_auto_scaling   = each.value.aks-usernp-autoscale
  max_count             = each.value.aks-usernp-autoscale ? each.value.max-count : null
  min_count             = each.value.aks-usernp-autoscale ? each.value.min-count : null
  max_pods              = each.value.max-pods
  mode                  = "User"
  node_labels           = each.value.node-labels
  orchestrator_version = local.orchestrator-version
  tags                 = {}
  lifecycle {
    ignore_changes = [node_count]
  }
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

If we change the node_labels, the node_pool should not be recreated.

### Actual Behaviour

`terraform plan` shows that the nodepool will be replaced by a new one due to changes on node_labels.
 
```
# azurerm_kubernetes_cluster_node_pool.nodepools["asm"] must be replaced
-/+ resource "azurerm_kubernetes_cluster_node_pool" "nodepools" {
      - enable_node_public_ip = false -> null
      ~ id                    = "/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx/agentPools/asmnp" -> (known after apply)
        name                  = "asmnp"
      ~ node_labels           = **{ # forces replacement**
          ~ "cloud.google.com/gke-nodepool" = "asm" -> "apigee-asm"
        }
      - node_taints           = [] -> null
      ~ os_disk_size_gb       = 128 -> (known after apply)
      - tags                  = {} -> null
        # (14 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. Use this tfvars (as an example): 
```
aks-nodepools = {
  asm = {
    nodepool-name        = "asmnp"
    vm-size              = "Standard_B4ms"
    node-count           = 3
    availability-zones   = ["1", "2", "3"]
    aks-usernp-autoscale = true
    node-labels = { "cloud.google.com/gke-nodepool" : "apigee-asm" }
    max-count = 7
    min-count = 4
    max-pods = 10
  }
}
```
2. `terraform apply`
3. Replace the `node_labels` by `node-labels = { "cloud.google.com/gke-nodepool" : "apigee-asm" }`
4. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @khaldoune 

Thanks for opening this issue.

At this point in time my understanding is that whilst the AKS API accepts an update for this field, it's never actually updated on the Node Pool itself - which is why this is marked as a ForceNew, since it's the only way to update this value. Would you be able to confirm if this is updatable using another mechanism, such as the Azure CLI?

Thanks!

**Comment by khaldoune** [comment]
Hi @tombuildsstuff 

Thanks for your answer.

The Az Cli does not allow that according to the documentation:
https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest#ext_aks_preview_az_aks_nodepool_add-optional-parameters

Using the REST API, the put request responds OK when sending the payload below and the Terraform see that there is a change and tries to forceNew if we re-apply using the old values , but even with the API, a `kubectl get nodes --show-labels` shows that the the new labels are not applied. Even after a scale up, the new nodes does not have these labels.

`PUT https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx/agentPools/asmnp?api-version=2020-09-01
Authorization: Bearer eyJ0eXAiOiJKV1Q...
Content-type: application/json`

```
{
  "properties": {
    "nodeLabels": {
        "cloud.google.com/gke-nodepool":"ASMNP",
        "toto":"tata"
     }
  }
}

```
**Response:**
Response Code: 200
```
{
  "id": "/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx/agentPools/asmnp",
  "name": "asmnp",
  "type": "Microsoft.ContainerService/managedClusters/agentPools",
  "properties": {
    "count": 3,
    "vmSize": "Standard_B4ms",
    "osDiskSizeGB": 128,
    "osDiskType": "Managed",
    "vnetSubnetID": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx",
    "maxPods": 10,
    "type": "VirtualMachineScaleSets",
    "availabilityZones": [
      "1",
      "2",
      "3"
    ],
    "provisioningState": "Updating",
    "powerState": {
      "code": "Running"
    },
    "orchestratorVersion": "1.17.13",
    "enableNodePublicIP": false,
    "nodeLabels": {
      "cloud.google.com/gke-nodepool": "ASMNP",
      "toto": "tata"
    },
    "mode": "User",
    "osType": "Linux",
    "nodeImageVersion": "AKSUbuntu-1604-2020.11.11"
  }
}

```
I'm confused.

**Comment by khaldoune** [comment]
Hi,
Closing as this subject is tracked here:
https://github.com/Azure/AKS/issues/1515
Thanks @tombuildsstuff
