### ISSUE TITLE
azurerm_linux_virtual_machine resource are not able to handle an empty string in custom_data

### ISSUE THREAD

**Issue by anatolylebedev-tomtom** [terraform-providers/terraform-provider-azurerm#9737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I was working on refactoring our vm modules and found out that `azurerm_linux_virtual_machine`, comparing to `azurerm_virtual_machine` are not able to handle an empty string. I have two compareable states currently the old one that I'm rewriting and the current. I would expect `custom_data` block would work in the same way like it was with the new resource.
### Terraform (and AzureRM Provider) Version

Old state with:
❯ terraform -v
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.16.0
+ provider registry.terraform.io/hashicorp/null v3.0.0

New state:
❯ terraform -v
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/azurerm v2.37.0
+ provider registry.terraform.io/hashicorp/null v3.0.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_virtual_machine`

### Terraform Configuration Files
old_main.tf
```hcl
locals {
  middle_name = trimsuffix(format("%s-%s-%s-%s", var.project, var.role, var.stage, lower(terraform.workspace != "default" ? terraform.workspace : "")), "-")
}

resource "azurerm_virtual_machine" "vm" {
  count               = var.vm_count
  name                = format("vm-${local.middle_name}-%003d", count.index + 1)
  resource_group_name = var.rg_name
  location            = var.location
  network_interface_ids = [
  element(azurerm_network_interface.nic.*.id, count.index)]
  vm_size = var.vm_size

  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    id      = data.azurerm_shared_image.foundation_image.id
    version = var.image_version
  }

  storage_os_disk {
    name              = format("dsk-${local.middle_name}-os-vm%003d", count.index + 1)
    create_option     = "FromImage"
    caching           = "ReadWrite"
    managed_disk_type = var.storage_type
  }

  dynamic storage_data_disk {
    for_each = range(var.nb_maps_disk)
    content {
      name              = azurerm_managed_disk.managed_disk_vm_copy[count.index].name
      create_option     = "Attach"
      lun               = storage_data_disk.value
      managed_disk_type = var.storage_type
      managed_disk_id   = azurerm_managed_disk.managed_disk_vm_copy[count.index].id
      disk_size_gb      = azurerm_managed_disk.managed_disk_vm_copy[count.index].disk_size_gb

    }
  }

  identity {
    type         = var.user_defined_identities == null ? "SystemAssigned" : "SystemAssigned, UserAssigned"
    identity_ids = var.user_defined_identities
  }

  os_profile {
    computer_name  = "${format("${local.middle_name}-%003d", count.index + 1)}.${var.domain[var.stage]}"
    admin_username = "az_user"
    custom_data    = var.custom_data
  }

  os_profile_linux_config {
    disable_password_authentication = var.enable_ssh_key

    dynamic "ssh_keys" {
      for_each = var.enable_ssh_key ? [
      local.ssh_key_pub] : []
      content {
        path     = "/home/${var.remote_user}/.ssh/authorized_keys"
        key_data = local.ssh_key_pub
      }
    }
  }

  tags = merge(
    {
      flavor = var.vm_size
    },
    var.tags
  )
}
```
part_of_var.tf
```hcl
variable "custom_data" {
  description = "The custom data to supply to the machine. This can be used as a cloud-init for Linux systems."
  default     = ""
}
```
refactor_main.tf
```hcl
resource "azurerm_linux_virtual_machine" "vm" {
  location = var.location
  name = var.vm_name
  network_interface_ids = [azurerm_network_interface.nic.id]
  resource_group_name = var.rg_name
  size = var.vm_size
  source_image_id = data.azurerm_shared_image.foundation_image.id
  computer_name  = "${var.vm_name}.${var.domain[var.stage]}"
//  "${format("${local.middle_name}-%003d", count.index + 1)}.${var.domain[var.stage]}"
  admin_username      = "az_user"
  disable_password_authentication = "true"
  custom_data = var.custom_data
  admin_ssh_key {
    public_key = var.ssh_key_pub != null ? var.ssh_key_pub : file(var.ssh_key_pub_path)
    username = "az_user"
  }

  os_disk {
    caching = "ReadWrite"
    storage_account_type = var.storage_type
  }
  identity {
    type         = var.user_defined_identities == null ? "SystemAssigned" : "SystemAssigned, UserAssigned"
    identity_ids = var.user_defined_identities
  }

  tags = merge(
    {
      flavor = var.vm_size
    },
    var.tags
  )
}
```

### Debug Output

No Debug Log available

### Panic Output

❯ terraform plan -out=dev.tfplan

Error: expected "custom_data" to not be an empty string, got 

  on ../main.tf line 20, in resource "azurerm_linux_virtual_machine" "vm":
  20: resource "azurerm_linux_virtual_machine" "vm" {

### Expected Behaviour

with azurerm_virtual_machine plan works fine and accepting an empty string.

### Actual Behaviour

failing with message that it's not accept an empty string

### Steps to Reproduce

1. use `azurerm_linux_virtual_machine`
2. set custom_data to empty string
3. try to run `terraform plan` and `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @anatolylebedev-tomtom 

Thanks for opening this issue / apologies for the delayed response here.

Older versions of Terraform Core (0.11 and below) used to use an empty string to signify an empty value, as such the older `azurerm_virtual_machine` resource treats the value `""` or `null` (available from 0.12+) for the `custom_data` field as the same value, null - meaning Terraform won't base64 encode this value and send it to the Azure API.

By contrast the newer `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` requires that the `custom_data` field is submitted using a Base64-encoded value (called out in the documentation), or `null` - with validation to confirm that it's either/or, which reflects the behaviour your seeing here.

As such it should be possible to mirror the earlier behaviour using a coalesce statement, for example:

```
resource "azurerm_linux_virtual_machine" "vm" {
    custom_data = var.custom_data != "" ? base64encode(var.custom_data) : null
}
```

Which'll conditionally base64 encode the custom data if it's specified, else set a `null` value which means this won't be set/shown in the plan - would you be able to take a look and see if that works for you?

Since this behaviour is intentional in these new resources, and it's possible to mirror the existing behaviour using a coalesce function, I'm going to close this issue for the moment, but should you have further usage questions I'd point you towards [the community discuss forum](https://discuss.hashicorp.com).

Thanks!
