### ISSUE TITLE
Issue #9687

### ISSUE THREAD

**Issue by x264243** [terraform-providers/terraform-provider-azurerm#9776]
In reference to the Issue #9687. We need use de module azurerm_sql_resource with the properties:

ssl_minimal_tls_version_enforced
public_network_access_enabled

Thanks in advance

**Comment by tombuildsstuff** [comment]
hi @x264243

Unfortunately there are no plans to backport this field to this resource, since as mentioned in #9687 this has been superseded by the `azurerm_mssql_server` resource here - as such you'd need to migrate to using the `azurerm_mssql_server` resource instead.

Thanks!
