### ISSUE TITLE
azurerm_databricks_workspace support DBFS CMK  prepare_encryption and encryption in custom_parameters

### ISSUE THREAD

**Issue by paulhudson** [terraform-providers/terraform-provider-azurerm#9785]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.39.0
+ provider.databricks v0.2.9
```
### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "main" {
  location            = var.azurerm_location_long
  name                = local.full_name
  resource_group_name = data.azurerm_resource_group.rg.name
  sku                 = var.databricks_sku

  custom_parameters {

    prepare_encryption     = true

    encryption {
        key_source = "Microsoft.Keyvault"
        keyvaulturi = azurerm_key_vault.dbfs.vault_uri
        key_name = "dbfs"
        keyversion = "00000000000000000000000000000000"
    }
  }

}
```

### Expected Behaviour

Workspace is prepared for encryption and configured with CMK via Azure Key Vault.

As Described in Azure API Reference: https://docs.microsoft.com/en-us/rest/api/databricks/workspaces/createorupdate#create-a-workspace-which-is-ready-for-customer-managed-key-(cmk)-encryption

### Actual Behaviour

```
$ terraform apply

Error: Unsupported argument

  on az_databricks.tf line 12, in resource "azurerm_databricks_workspace" "main":
  12:     prepare_encryption   = true

An argument named "prepare_encryption" is not expected here.


Error: Unsupported block type

  on az_databricks.tf line 14, in resource "azurerm_databricks_workspace" "main":
  14:     encryption {

Blocks of type "encryption" are not expected here.
```

### Steps to Reproduce

1. Define Terraform resource - as per above example above, passing custom_parameters specified in Azure API Reference 
2. `terraform apply`

### Important Factoids

None

**Comment by istairbn** [comment]
Creating a workspace with CMEK is a requirement

**Comment by istairbn** [comment]
PR #12310 gets us half way there. It turns on the Managed Identity and also allows for the Infrastructure Encryption.
