### ISSUE TITLE
Support for Event Subscription for an Event Grid System Topic (az eventgrid system-topic event-subscription) 

### ISSUE THREAD

**Issue by chandanchawhan** [terraform-providers/terraform-provider-azurerm#9788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for using Terraform to create Event Subscription to Azure Event Grid System Topics appears to be missing.

### New or Affected Resource(s)

* azurerm_eventgrid_system_topic 
* azurerm_eventgrid_system_topic_event_subscription 

### References

* https://docs.microsoft.com/en-us/cli/azure/ext/eventgrid/eventgrid/system-topic/event-subscription?view=azure-cli-latest

**Comment by jrauschenbusch** [comment]
Duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/9141

**Comment by chandanchawhan** [comment]
Closing feature request as it's a duplicate.
