### ISSUE TITLE
Support for azurerm_managed_disk

### ISSUE THREAD

**Issue by aidaDiazFdez** [terraform-providers/terraform-provider-azurerm#9796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The networkAccessPolicy property is required to be included in the azurerm_managed_disks module just as it exists in arm templates. 
It may have the values:

- public
- private
- DenyAll

So you can configure the connectivity method.

### New or Affected Resource(s)

azurerm_managed_disk

**Comment by cmendible** [comment]
Added a WIP PR to fix this issue: #9862
