### ISSUE TITLE
Azure Site Replication has to fail to release lock to allow Azure to complete replication

### ISSUE THREAD

**Issue by CDLP2U** [terraform-providers/terraform-provider-azurerm#9809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.2
registry.terraform.io/hashicorp/azurerm v2.39.0

### Affected Resource(s)

azurerm_site_recovery_replicated_vm

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replicated_vm" "__FAKE_ENV_NAME__-DISR-REP" {
  name                                      = "__FAKE_TARGET_VM_NAME__-ASRReplica"
  resource_group_name                       = azurerm_resource_group.__TARGET_ENV_NAME__-RG.name
  recovery_vault_name                       = azurerm_recovery_services_vault.__TARGET_ENV_NAME__-VL.name
  source_recovery_fabric_name               = azurerm_site_recovery_fabric.__TARGET_ENV_NAME__-PROD-FB.name
  source_vm_id                              = "/subscriptions/FAKE/resourceGroups/FAKE/providers/Microsoft.Compute/virtualMachines/FAKE"
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.__FAKE_ENV_NAME__-DISR-PO.id
  source_recovery_protection_container_name = azurerm_site_recovery_protection_container.__TARGET_ENV_NAME__-PROD-PC.name
  target_network_id                         = azurerm_network_interface.__FAKE_ENV_NAME__-DISR-NIC.id
  target_resource_group_id                  = azurerm_resource_group.__TARGET_ENV_NAME__-RG.id
  target_recovery_fabric_id                 = azurerm_site_recovery_fabric.__TARGET_ENV_NAME__-DISR-FB.id
  target_recovery_protection_container_id   = azurerm_site_recovery_protection_container.__TARGET_ENV_NAME__-DISR-PC.id
```

### Debug Output

2020-12-10T15:25:52.9216533Z An execution plan has been generated and is shown below.
2020-12-10T15:25:52.9217612Z Resource actions are indicated with the following symbols:
2020-12-10T15:25:52.9218688Z -/+ destroy and then create replacement
2020-12-10T15:25:52.9219157Z 
2020-12-10T15:25:52.9219504Z Terraform will perform the following actions:
2020-12-10T15:25:52.9219851Z 
2020-12-10T15:25:52.9514492Z   # azurerm_site_recovery_replicated_vm.FAKE-DISR-REP is tainted, so must be replaced
2020-12-10T15:25:52.9515425Z -/+ resource "azurerm_site_recovery_replicated_vm" "FAKE-DISR-REP" {

### Expected Behaviour

Terraform to complete replication setup and allow Azure to set the VM to protected.

### Actual Behaviour

Terraform timesout regardless of how long the timeout is set and while running the VM being replicated will get stuck waiting to become protected. Once Terraform fails, the Azure resource completes as expected.
Any addition runs of the script detects the resource as tainted, but Azure doesn't seem to support untaint commands from DevOps causing the resource to be recreated each time.

### Steps to Reproduce

Replicate a VM to a recovery vault in Azure, no special settings required the example on the TerraForm site has the same issue.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/site_recovery_replicated_vm

* #0000

**Comment by AndreasFrangopoulos** [comment]
Having the same problem here. I feel like there's no real requirement to have the deployment wait until confirmation of synchronisation is complete. Some larger VMs can take a whole day to finish synchronisation and it doesn't make sense to have deployments run for this long.

**Comment by tombuildsstuff** [comment]
👋🏻

One of the core design principals of Terraform is that a resource isn't finished creating until it's finished, since this allows you to chain resources together and have them provision in a consistent manner. Taking a look through here unfortunately this appears to be an issue with the Azure API where this takes an excessive amount of time to replicate - as such the performance issues would need to be fixed within the Azure API here.

Whilst it's possible that Terraform could skip waiting for this to replicate - since this is a core design principal unfortunately this isn't something we plan to do, instead it's possible to configure a custom timeout against these resources should they take longer to provision than expected. As mentioned above since this appears to be a performance issue within the Azure API, I'm going to close this issue for the moment - but I'd encourage you to reach out to Microsoft about this performance issue.

Thanks!
