### ISSUE TITLE
Wildcards are not supported for Application Gateway

### ISSUE THREAD

**Issue by jf781** [terraform-providers/terraform-provider-azurerm#9835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Not able to create a listener in Azure's Application Gateway v2 if they have wildcards in the hostname.  

### New or Affected Resource(s)

azurerm_application_gateway

### Potential Terraform Configuration

```hcl
#### App Gateway Listner Config
variable "agwListeners"{
  description = "Defines listeners for Application Gateway"
  type        = list(object({
    name                            = string
    frontend_ip_configuration_name  = string
    frontend_port_name              = string
    protocol                        = string
    ssl_certificate_name            = string 
    fqdn                            = string
    require_sni                     = bool
  }))
  default     = [
    {
      name                            = "qa0-httpsListner"
      frontend_ip_configuration_name  = "qa0-frontendIP"
      frontend_port_name              = "qa0-frontendHttpsPort"
      protocol                        = "Https"
      ssl_certificate_name            = "qaCompany-Cert"
      fqdn                            = "*.qa0.company.com"
      require_sni                     = false
    },
    {
      name                            = "qa0-httpListner"
      frontend_ip_configuration_name  = "qa0-frontendIP"
      frontend_port_name              = "qa0-frontendHttpPort"
      protocol                        = "Http"
      ssl_certificate_name            = null
      fqdn                            = "*.qa0.company.com"
      require_sni                     = false
    },
    {
      name                            = "qa1-httpsListner"
      frontend_ip_configuration_name  = "qa0-frontendIP"
      frontend_port_name              = "qa0-frontendHttpsPort"
      protocol                        = "Https"
      ssl_certificate_name            = "qaCompany-Cert"
      fqdn                            = "*.qa1.company.com"
      require_sni                     = false
    },
    {
      name                            = "qa1-httpListner"
      frontend_ip_configuration_name  = "qa0-frontendIP"
      frontend_port_name              = "qa0-frontendHttpPort"
      protocol                        = "Http"
      ssl_certificate_name            = null
      fqdn                            = "*.qa1.company.com"
      require_sni                     = false
    }
  ]
}

```

### References

This feature is currently in preview so I understand I may be getting the horse ahead of the cart. [MS Docs article](https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview#wildcard-host-names-in-listener-preview)

**Comment by AliAllomani** [comment]
@jf781 have you tried to use `host_names` parameter instead of `host_name` ?

https://github.com/terraform-providers/terraform-provider-azurerm/blame/master/website/docs/r/application_gateway.html.markdown#L291-L293

```markdown
* `host_name` - (Optional) The Hostname which should be used for this HTTP Listener. Setting this value changes Listener Type to 'Multi site'.

* `host_names` - (Optional) A list of Hostname(s) should be used for this HTTP Listener. It allows special wildcard characters.
```

```golang
type ApplicationGatewayHTTPListenerPropertiesFormat struct {
...
	// HostName - Host name of HTTP listener.
	HostName *string `json:"hostName,omitempty"`
...
	// HostNames - List of Host names for HTTP Listener that allows special wildcard characters as well.
	HostNames *[]string `json:"hostNames,omitempty"`
...
}
```

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v49.0.0+incompatible/services/network/mgmt/2020-06-01/network#ApplicationGatewayHTTPListenerPropertiesFormat

The values are being sent as they are on the provider side.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/9891508ebabb69d2f0f82c076c3c7b166e185e0d/azurerm/internal/services/network/application_gateway_resource.go#L396-L408

https://github.com/terraform-providers/terraform-provider-azurerm/blob/9891508ebabb69d2f0f82c076c3c7b166e185e0d/azurerm/internal/services/network/application_gateway_resource.go#L2247-L2261

**Comment by jf781** [comment]
Thanks @AliAllomani.  That took care of it.  Not sure how I missed that.  Thanks for the help!!
