### ISSUE TITLE
vm-joined-to-active-directory - not able to domain promote

### ISSUE THREAD

**Issue by kendrickcc** [terraform-providers/terraform-provider-azurerm#989]
### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
azurerm_virtual_machine_extension

### Terraform Configuration Files
```hcl
// the `exit_code_hack` is to keep the VM Extension resource happy
locals {
  import_command       = "Import-Module ADDSDeployment"
  password_command     = "$password = ConvertTo-SecureString ${var.admin_password} -AsPlainText -Force"
  install_ad_command   = "Add-WindowsFeature -name ad-domain-services -IncludeManagementTools"
  configure_ad_command = "Install-ADDSForest -CreateDnsDelegation:$false -DomainMode Win2012R2 -DomainName ${var.active_directory_domain} -DomainNetbiosName ${var.active_directory_netbios_name} -ForestMode Win2012R2 -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true"
  shutdown_command     = "shutdown -r -t 10"
  exit_code_hack       = "exit 0"
  powershell_command   = "${local.import_command}; ${local.password_command}; ${local.install_ad_command}; ${local.configure_ad_command}; ${local.shutdown_command}; ${local.exit_code_hack}"
}

// NOTE: we **highly recommend** not using this configuration for your Production Environment
// this provisions a single node configuration with no redundancy.
// Verify extensions are current
// command: az vm extension list --query "[?starts_with(name, 'CustomScriptExtension')]"
resource "azurerm_virtual_machine_extension" "create-active-directory-forest" {
  name                 = "create-active-directory-forest"
  location             = "${azurerm_virtual_machine.domain-controller.location}"
  resource_group_name  = "${var.resource_group_name}"
  virtual_machine_name = "${azurerm_virtual_machine.domain-controller.name}"
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.8"

  settings = <<SETTINGS
    {
        "commandToExecute": "powershell.exe -Command \"${local.powershell_command}\""
    }
SETTINGS
}
```

### Expected Behavior
What should have happened?
Expect to have the domain controller be promoted in the new forest. 

### Actual Behavior
What actually happened?
AD DS does install, but the next step to promote to domain and create the forest does not appear to occur. 

Terraform appears to work as expected. It is with the PowerShell command that attempts to execute the promotion.

**Comment by tombuildsstuff** [comment]
hi @kendrickcc 

Thanks for opening this issue

> AD DS does install, but the next step to promote to domain and create the forest does not appear to occur.

So based on my understanding when writing the sample the DC Promotion is achieved during the subsequent reboot (triggered once this is installed via the `shutdown -r -t 10` you see in the command) when the DC restarts; if it possible to see the error message that you're seeing here?

Thanks!

**Comment by kendrickcc** [comment]
I rebooted the server again. Then accessed it from the client. The domain promote did not initiate. I don't think it ever gets to the promote command. It appears to reboot when the system name is changed. I am not seeing any errors on the output of terraform, everything shows successful.

**Comment by tombuildsstuff** [comment]
@kendrickcc in the case of this example, there's a 15 minute sleep between the Client VM being provisioned and the script to join the AD Domain; which should be long enough for the Domain Controller to finish provisioning the AD Domain (about 5 minutes) and reboot into the new configuration (3m), with a little leeway.

The Domain Controller configuration/setup is intentionally not recommended for use in a Production Environment (hence the disclaimers!), so we'd strongly recommend not replicating the Domain Controller set up via this script - but it does demonstrate the VM Extension which is the primary purpose of the example.

> I rebooted the server again. Then accessed it from the client. The domain promote did not initiate. I don't think it ever gets to the promote command. It appears to reboot when the system name is changed. I am not seeing any errors on the output of terraform, everything shows successful.

I'm a little confused here, are you saying the Client machine isn't bound to the domain?

Thanks!

**Comment by kendrickcc** [comment]
The DC never completes the promotion into a new forest. It appears to stop after AD DS installs. I understand not to use for production. My goal is to leverage this and have small test labs available when needed. Therefore if the goal is to just demonstrate the extension, then I probably need to take a different approach. Thank you! I really appreciate all the work that went into this repository.

**Comment by kendrickcc** [comment]
Thank you. Agree, I'm thinking about separating this out into another script where I can tailor the lab environment as needed. But yes, just need to jump start the dcpromo differently.

**Comment by kendrickcc** [comment]
I figured out why the promotion was not working. I'm relatively new to Git so I'm not sure how to post an update for review. Can you advise or point me to a reference.
