### ISSUE TITLE
Need Private link enable feature  and ESP package support  for  the  TF Resource "azurerm_hdinsight_interactive_query_cluster"

### ISSUE THREAD

**Issue by Terraformazure** [terraform-providers/terraform-provider-azurerm#9941]
Need Private link enable feature  for  below TF resurce.

 azurerm_hdinsight_interactive_query_cluster
 
This is currently available in AZ CLI,  ARM template
**Enabling private link :**
       az hdinsight create -t spark --version 3.6 -g MyResourceGroup -n MyCluster \
-p "HttpPassword1234!" --storage-account MyStorageAccount \
--subnet "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/fakevnet/subnets/default" \
--resource-provider-connection Outbound --enable-private-link

**ESP package :** 

az hdinsight create --esp -t spark -g MyResourceGroup -n MyCluster \
-p "HttpPassword1234!" \
--storage-account MyStorageAccount \
--subnet "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRG/providers/Microsoft.Network/virtualNetworks/MyVnet/subnets/subnet1" \
--domain "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRG/providers/Microsoft.AAD/domainServices/MyDomain.onmicrosoft.com" \
--assign-identity "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/MyMsiRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MyMSI" \
--cluster-admin-account MyAdminAccount@MyDomain.onmicrosoft.com \
--cluster-users-group-dns MyGroup

**Comment by tombuildsstuff** [comment]
@Terraformazure support for the ESP package is tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/5023 - please subscribe to that issue for updates

For supporting Private Link wit for HDInsights [would you mind opening a new issue completing the Feature Request form](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D), which has all of the information we need to look into this?

Thanks!
