### ISSUE TITLE
Support for identities in AKS VMSS

### ISSUE THREAD

**Issue by bbgobie** [terraform-providers/terraform-provider-azurerm#9965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
VMSS User Assigned Managed Identity are one of the ways to retrieve secrets with Azure KV in AKS with the Azure CSI KV Plugin.
Currently assigning a user or system managed identity to a VMSS is not possible with the module.

Link to Plugin documentation with identity access options
https://github.com/Azure/secrets-store-csi-driver-provider-azure#provide-identity-to-access-key-vault

Specific User Identity assignment to VMSS 
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/user-assigned-msi-mode.md

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

Similar to whats already available in VMSS
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#identity

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://github.com/Azure/secrets-store-csi-driver-provider-azure#provide-identity-to-access-key-vault

* #0000

**Comment by Tenseiga** [comment]
@bbgobie , cant this be done using aad pod identities ? https://github.com/Azure/aad-pod-identity

**Comment by bbgobie** [comment]
@Tenseiga Yes this can also be done via pod identities.
Was just hoping that terraform supported the available option so we could choose how to implement the solution.

**Comment by tombuildsstuff** [comment]
hi @bbgobie

Support for this is available as [the `identity` block within the `azurerm_kubernetes_cluster` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#type) where you can specify either a System Assigned or User Assigned Identity. Since this is a configuration question rather than a bug in the Azure Provider, I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
