### ISSUE TITLE
Failed to import second data disk using azurerm_virtual_machine_data_disk_attachment

### ISSUE THREAD

**Issue by mvaferreira** [terraform-providers/terraform-provider-azurerm#9979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
PS C:\terraform> terraform -v
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
PS C:\terraform>
```

### Affected Resource(s)

azurerm_virtual_machine_data_disk_attachment

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_data_disk_attachment" "disk_att_vdihost1_DataDisk_0" {
  managed_disk_id    = azurerm_managed_disk.disk_vdihost1_DataDisk_0.id
  virtual_machine_id = azurerm_windows_virtual_machine.vm_vdihost1.id
  lun                = 0
  caching            = "ReadOnly"
}

resource "azurerm_virtual_machine_data_disk_attachment" "disk_att_vdihost1_datadisk_1" {
  managed_disk_id    = azurerm_managed_disk.disk_vdihost1_datadisk_1.id
  virtual_machine_id = azurerm_windows_virtual_machine.vm_vdihost1.id
  lun                = 1
  caching            = "ReadOnly"
}
```

### Expected Behaviour

Both managed data disks should be imported successfully.

### Actual Behaviour

***First disk (data disk on lun id 0) is imported successfully.***

```
C:\terraform>terraform import azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_DataDisk_0 /subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_DataDisk_0
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_DataDisk_0: Importing from ID "/subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_DataDisk_0"...
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_DataDisk_0: Import prepared!
  Prepared azurerm_virtual_machine_data_disk_attachment for import
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_DataDisk_0: Refreshing state... [id=/subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_DataDisk_0]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

***Second data disk (lun id 1) fails to import, saying it is non-existent***

```
C:\terraform>terraform import azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1 /subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_datadisk_1
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1: Importing from ID "/subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_datadisk_1"...
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1: Import prepared!
  Prepared azurerm_virtual_machine_data_disk_attachment for import
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1: Refreshing state... [id=/subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_datadisk_1]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1, the
provider detected that no object exists with the given id. Only pre-existing
objects can be imported; check that the id is correct and that it is
associated with the provider's configured region or endpoint, or use
"terraform apply" to create a new remote object for this resource.
```

### Steps to Reproduce

terraform import azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_DataDisk_0 /subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_DataDisk_0

terraform import azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1 /subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1/dataDisks/vdihost1_datadisk_1

***"terraform plan", says it will add a new resource:***

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1 will be created
  + resource "azurerm_virtual_machine_data_disk_attachment" "disk_att_vdihost1_datadisk_1" {
      + caching                   = "ReadOnly"
      + create_option             = "Attach"
      + id                        = (known after apply)
      + lun                       = 1
      + managed_disk_id           = "/subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/disks/vdihost1_datadisk_1"
      + virtual_machine_id        = "/subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/virtualMachines/vdihost1"
      + write_accelerator_enabled = false
    }

Plan: 1 to add, 0 to change, 0 to destroy.
------------------------------------------------------------------------
```

***"terraform apply", says LUN 1 already exists:***

```
azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1: Creating...

Error: Error updating Virtual Machine "vdihost1" (Resource Group "rdsvdi") with Disk "vdihost1_datadisk_1": compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="A disk at LUN 1 already exists." Target="dataDisk.lun"

  on resources.tf line 264, in resource "azurerm_virtual_machine_data_disk_attachment" "disk_att_vdihost1_datadisk_1":
 264: resource "azurerm_virtual_machine_data_disk_attachment" "disk_att_vdihost1_datadisk_1" {

PS C:\terraform>
```

* #0000

**Comment by ruandersMSFT** [comment]
@mvaferreira Try the following import, based on the Azure Resource ID for the Data Disk shown in the Terraform Plan:

terraform import azurerm_virtual_machine_data_disk_attachment.disk_att_vdihost1_datadisk_1 /subscriptions/<subscription_id>/resourceGroups/rdsvdi/providers/Microsoft.Compute/disks/vdihost1_datadisk_1

**Comment by tombuildsstuff** [comment]
hi @mvaferreira 

Thanks for opening this issue.

Taking a look through here it appears that the ID being used to import the secondary disk attachment is incorrect, which is why the `import` is failing here, but the `create` is failing since the `name` is different - as such it should be possible to fix this by switching to use the `name` of the disk at LUN 1. Notably this error message (`A disk at LUN 1 already exists.`) is being returned from the Azure API rather than Terraform, which is why this isn't suggesting to import this / showing the ID which needs to be used here - so you'd need to check which disk is attached at this LUN to resolve the conflict.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by mvaferreira** [comment]
Yes, indeed it was the wrong id, but because the managed disk name was actually vdihost1_**d**ata**d**isk_1, while the data disk attachment on vm vdihost1 was vdihost1_**D**ata**D**isk_1. Thank you!
