### ISSUE TITLE
Support for compression type in azurerm_data_factory_dataset_delimited_text 

### ISSUE THREAD

**Issue by markusgulden** [terraform-providers/terraform-provider-azurerm#9980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The DelimitedText dataset on Azure supports has a compression type setting (see also https://docs.microsoft.com/en-us/azure/data-factory/format-delimited-text#dataset-properties).
As far as I can see in the documentation and also the source code of the resource implementation, this is currently not supported by azurerm_data_factory_dataset_delimited_text.

### New or Affected Resource(s)

* azurerm_data_factory_dataset_delimited_text 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.microsoft.com/en-us/azure/data-factory/format-delimited-text#dataset-properties

**Comment by brunhil** [comment]
Looks like the current version of the SDK allows for this property to be set. I'll see if I can take a stab at this!

**Comment by markusgulden** [comment]
Thanks a lot for taking care of that so quickly!

Is there a specific reason why you only provide "Optimal" and "Fastest" as values?
Users probably would prefer to be able to choose the exact compression type to be used (like bzip2, gzip, etc.).
All of them have specific characteristics like efficiency, performance, being splittable or not, etc., and as a developer, I definitely need control here.

**Comment by brunhil** [comment]
Hi @markusgulden ! The reason behind _Optimal_ and _Fastest_ is those are the only two values allowed by the API, see attached screenshot below. Let me know if you have any other questions!

![Screen Shot 2021-01-13 at 10 45 58 AM](https://user-images.githubusercontent.com/2320689/104482461-947e0000-558c-11eb-9a60-022e9dde1763.png)

Did you intend to request the **compressionCodec** as well?

**Comment by markusgulden** [comment]
Hi @brunhil thanks a lot again for the quick response, appreciate that!

Then is again an example of poor documentation/inconsistency on Azure side.
When I mentioned compression type, I was referring to the Azure Portal, and that means compression codecs there:
![image](https://user-images.githubusercontent.com/24793790/104483217-df504580-5595-11eb-8051-c289643faf46.png)

So yes, I actually intended to be able of controlling the used compression codec.
Sorry for the confusion, but I thought using the term from the Portal would be unambiguous.

**Comment by brunhil** [comment]
No worries @markusgulden ! I have been bitten by that before 😅 . I'll add a follow-on PR to actually add the "real" compression type (compression_codec in Azure API)

**Comment by markusgulden** [comment]
Awesome! I wish AWS would react that quickly on feature requests for CloudFormation.
