### ISSUE TITLE
Feature Request: Allow setting properties on `azurerm_storage_blob` objects

### ISSUE THREAD

**Issue by dcolebatch** [terraform-providers/terraform-provider-azurerm#999]
When creating blobs for serving static sites or content, setting the `Content-Type` property is important. The default `octet-stream` causes all files, even `index.html`, to download in the browser, not render.  If we set `Content-Type: text/html` file is served correctly.

A powershell example of setting the property to enable static file hosting in Azure:
https://stackoverflow.com/a/42893335

Here's an example of a blob where I'd like to set the Content-Type: https://github.com/dcolebatch/azure_serverless_example/blob/master/setup/main.tf#L51

**Comment by katbyte** [comment]
Closed via #1304 and set to be released in `1.7.0`

**Comment by katbyte** [comment]
@dcolebatch,

Just wanted to let you know we have released 1.7 and it should resolve this issue.
